### ISSUE TITLE
Project manager 

### ISSUE THREAD

**Issue by luongquynhdieu** [awesome-jobs/vietnam#1000]
## Location

Ha Noi, Viet Nam

## Salary Expectation

1500 - 2500$

## Requirements
- Có 2 năm kinh nghiệm PM/Brse
- Tiếng Nhật từ N2 trở lên, giao tiếp thành thạo

## Skills
- Có khả năng leadership, có ý thức trách nhiệm cao, có tinh thần làm việc teamwork
- Kỹ năng phân tích, xử lý vấn đề tốt

### Why it would be awesome to work with us
- Mức lương hấp dẫn up to $2500
- Làm việc 5 ngày/tuần . Nghỉ cả ngày thứ 7 &amp; Chủ Nhật.
- Review lương 2 lần/ năm vào tháng 1 và tháng 6.
- Thưởng theo doanh thu cuối năm và các ngày lễ tết hấp dẫn.
- Được cấp Macbook để thỏa sức sáng tạo
- Được tham gia các khóa đào tạo tiếng Nhật tổ chức định kì
- Cơ hội đi công tác nước ngoài (Nhật Bản)
- Được tham gia các hoạt động team building,..

### Contact
Ms. Diệu
Mail: luongquynhdieu@gmail.com
Skype: luongquynhdieu
SDT: 01675 028 224
Linkedin: https://www.linkedin.com/in/qu%E1%BB%B3nh-di%E1%BB%87u-headhunter-9ba245123/

**Comment by huydx** [comment]
we don't accept JD from 3rd party recruiter. and this JD is in wrong format.
