### ISSUE TITLE
9cv9 - Python Team Lead - Saigon - FT

### ISSUE THREAD

**Issue by ndmthu1997** [awesome-jobs/vietnam#1004]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2500/month or range

## Requirements
* Python
* Able to work clean codes and to build an infrastructure from scratch
* English

### Must Have

* System networking
* Python and its framework, Django, Flask
* English

### Ideally
* Frontend Javascript, ReactJS is a bonus
* Strong knowledge in building on hosting servers, AWS, Docker
### Responsibilities

* Build up an automated and smart loan making system

### Why it would be awesome to work with us
* Good Career Prospects
* Follow Vietnamese Labor law
### Interesting engineering projects
The project will be exciting and huge
### Contact
Email: minhthu@9cv9.com
Phone: 01299997746
Link JD and Apply: https://bit.ly/2GNLWmQ

**Comment by huydx** [comment]
it seems that 9cv9 is agency company, and our rule is NOT accept any 3rd party recruiter.
