### ISSUE TITLE
[9cv9] - [Android/iOS] - [Ho Chi Minh] - [FT]

### ISSUE THREAD

**Issue by ngodomyngan** [awesome-jobs/vietnam#1005]
## Location

* Saigon, Vietnam
* FT

## Salary Expectation

* Up to $2500/month

### Must Have

* You have at least 5 years of Android app development experience.
* You have a solid understanding of OO design patterns.
* You want to build large-scale applications that are well tested and easy to maintain.
* You have worked on larger-scale consumer-facing app.
* You have experience with server-side architecture and have ideally worked on Ruby on Rails environment.
* You have experience publishing apps on Play Store.

### Ideally

* You are motivated to automate your works and write the test for your own code.
* You enjoy working in a start-up and open environment.
* You take pride and ownership in your work.
* You are self-motivated and can work well under pressure.
* You have a good sense of humour and for you programming is passion.

### Responsibilities

* Design and improve upon existing app architecture in Android
* Work closely with product and design to build and improve features
* Work on performance and reliability
Work on existing and new features and interfaces that greatly improve the productivity and effectiveness
* Plan and document technical specifications for features or system design
* Contribute towards improving engineering culture and approach
* Innovate and work on products and features to provide convenience for customers
* Play a lead role either in terms of technical development and architecture or in terms of team management
* Mentor and nurture engineers

### Why it would be awesome to work with us
 
* An opportunity to build and develop a product widely used in Asia
* International environment where you can work and learn from co-workers coming from different 20 countries.
* 1-month training in Singapore
* Competitive salary
* New Macbook provided
* Insurance and tax payment according to Vietnamese labor law
* 14 annual leave days

### Contact
Kindly apply your CV here: h_t_t_p_s_://goo.gl/CreLhD

**Comment by huydx** [comment]
not accept 3rd party recruiter.
