### ISSUE TITLE
HDWEBSOFT - Ruby on Rails Developers - HCM - FT

### ISSUE THREAD

**Issue by hunglq** [awesome-jobs/vietnam#101]
HDWEBSOFT is a young software company with a fresh mindset in software development. If you are looking for a positive and creative job you can find it at us.
We are very strong in developing large scale and complex business web applications. HDWebsoft aims to use the latest web technologies like HTML5, CSS3, JavaScript, PHP, Python, Ruby On Rails, CakePHP, Zend, Symfony, Yii, CodeIgniter, Phalcon, NodeJS, MongoDB, MySQL, InfoBright, AngularJS, Backbone.js, Knockout.js, KendoUI, Knockback.js, data visualization such as D3, D3.Js, Leaflet.
We are also applying the great AGILE SCRUM software development methodology, and our works are qualified with TDD, BDD and Visual Test.
http://www.hdwebsoft.com

Job description:
- Very good knowledge in Ruby on Rails and Web Front-end technologies like HTML5, CSS3
- Experienced working with more than one Ruby on Rails frameworks.
- At least 1 year of working experience in the related field is required for this position.

We offer to the successful candidates benefit as following:
- Competitive salary
- Health Insurance (in and out patients)
- Accident insurance 24/24
- Good working conditions and environment
- Continuing development of technical and soft skills through work and formal training
- Company’s labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trips, Team building etc.)
- Monthly bonus

Please submit your cv at contact@hdwebsoft.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
