### ISSUE TITLE
[Grasp] - [Senior Ruby on Rails Developer] - [Ho Chi Minh city] - [FT]

### ISSUE THREAD

**Issue by haonguyen992** [awesome-jobs/vietnam#1011]
## Location
* Saigon, Vietnam

## Salary Expectation
* $1000 - $2000/ month

## Requirements
* Ruby
* Rails
* Javascript, HTML, CSS
* 2+ years experience in Ruby on Rails

### Must Have
* Bachelor degree in Computer Science or Computer Engineering
* 2+ years of experience with Ruby on Rails
* Proficiency in Javascript, HTML, CSS

### Ideally
* Experience in Amazon Web Services
* Experience in Automated Test and Test Driven Development
* Experience in RESTful and services like Google, Facebook
* Proficiency in object-oriented analysis, design, and programming
* Understanding of metaprogramming and design pattern
* Experience in git and gitflow
* Ability to provide analysis and problem-solving skills.
* Ability to use Photoshop or AI is a plus
* Must possess desire to learn new technologies. Ability to learn quickly.
* Must possess strong communications skills, both written and oral. Ability to articulate technical viewpoints to team members and clients.
* Must be a self-starter/self-reliant to define strategies and work collaboratively to harden/publish strategies. Able to work independently, take ownership of tasks and deliver high quality products and customer services 

### Responsibilities
The Ruby on Rails Developer will be a member of our Software Development team and will be deeply
involved in the full product lifecycle of multiple applications. The ideal candidate will be an energetic
overachiever, with a team-focused startup mentality, who is passionate about solving problems and
doing whatever is necessary to get the job done.

### You’ll be responsible for
* Working with project managers and other stakeholders to get clarification on business requirements and then implementing solutions including code development and database design
* Ensuring high-quality solutions by implementing unit tests and supporting the creation and design of integration, load and user acceptance tests
* Support operations by identifying, researching and resolving performance and production issues

### Why it would be awesome to work with us
* Competitive Salary and bonuses (for holidays and year-end), project bonus
* Allowance for lunch and diligence
* Performance Review (2 times per year)
* Compassionate Leave
* Social insurance, medical insurance and unemployment insurance under Vietnamese Law
* Yearly company trip
* Team building activities
* Training courses (tech skills, soft skills, foreign languages)
* Work in a professional and dynamic environment
* Opportunities to work onsite for short-term and long-term

### Contact
Email: helen@graspvietnam.com 
Phone: 0974911901
Skype: haominhtn

**Comment by huydx** [comment]
grasp vietnam is agency too.
