### ISSUE TITLE
LOGIVAN - ReactJS/React Native Developer - HN - FT

### ISSUE THREAD

**Issue by kiendt07** [awesome-jobs/vietnam#1015]
## Location

* Hanoi, Vietnam

## Salary Expectation

$800 - $1500

## Responsibilities

You will be joining our Tech team to build apps and tools for LOGIVAN's platform, that matches trucks' spare capacity with shipment.

Some hard problems that we're trying to solve:

* How to ship features across multiple apps for shipper and carrier with speed and quality.
* Build apps and tools for customers and corporations that crash-free and easy to use.

## Requirements

* 1+ years experience working with ReactJS/React Native.
* Experience in writing unit test is a plus
* Experience in shipping a real product is a plus, includes how to distribute an app and use insights to gain users.

## Skills

* Great collaboration skills is needed, we must use Git, JIRA and our mouth in a very sufficient way to ship everything with speed and quality.
* Product-minded is also needed, because LOGIVAN is built by product-minded people and will always be.

## We will really appreciate someone that could

* Writing clean, easy-to-read Javascript code.
* Understand user's behavior and be able to build apps that people love to use.

## Why it would be awesome to work with us

* Awesome colleagues. Our team is full of young, humble people that work hard and open to ideas.
* The opportunity to join a promising, well-funded startup.
* Gain experience in building a real product with lots of hard problems to solve.

### Contact
Homepage: [LOGIVAN.com](http://www.logivan.com (http://www.logivan.com/))
Email: kien@logivan.com

**Comment by tucq88** [comment]
Amazing! Such a cool team.
