### ISSUE TITLE
ANYMIND Group - Data Scientist - HCMC - FT

### ISSUE THREAD

**Issue by thucnhan** [awesome-jobs/vietnam#1065]
![aaaaa](https://user-images.githubusercontent.com/38033330/38239946-65263b10-3758-11e8-8dd0-fa70ee8690db.jpg)

AnyMind Group (https://anymindgroup.com) provides businesses and professionals with AI-based solutions that enable businesses to achieve greater scale and efficiency.

**LOCATION** 
F16, Ruby Tower, 81-85 Ham Nghi, Nguyen Thai Binh Ward, District 1, Saigon, Vietnam 

**SALARY EXPECTATION**
You will love you

**WHAT YOU SHOULD HAVE**

- At least 2 year of real work in NLP.
- Solid understanding of Machine Learning and NLP.
- CRF, FastText, RNN, LSTM, Logistic regression, CNN is part of your vocabulary.
- Practical experience training word embeddings using unsupervised learning.
- Practical experience with classification and regression models.
- Fluent in English.
- Love for data.
- 2 years of management experience is a big plus

**WHAT YOU WILL DO**
As a Data Scientist, you will train Machine Learning models for NLP. You will also be involved in curating data for our ML models. The ideal candidate will have experience in applying machine learning on large text corpora, as well as the use of NLP in software, including design, implementation, algorithms, correctness, user experience, and performance.

- Sentiment analysis using word embeddings trained on social media corpus.
- Named Entity Recognition for Brand discovery on social media comments.
- Segmentation of a Curriculum Vitae in different areas: Basic info, Working experience, Skills.
- Train custom NER for extracting entities like job_title from the Working experience section of a Curriculum Vitae.

**HOW AWESOME IS IT TO WORK WITH US**
We don't offer you a job, we offer you an career opportunity :) 
 
- Competitive Salary with two Performance Review per year
- Performance Bonus (1 time per year from 0.5-month to 3-month salary amount )
- MacBook to be provided, well-stocked pantry awaiting, cool team-players to have a blast with
- Join dynamic environment where growth-oriented mindset is encouraged
- Good chance to explore new trends in a digital market, where you can experience the most advanced advertising technology platforms
- No fixed day for promotion - Perform well and get promoted anytime!
- Quarterly, Annual MVP Awards (prizes up to 8,000USD)

**OUR INSPIRING PRODUCTS**
To provide businesses and professionals with AI-based solutions that enable businesses to achieve greater scale and efficiency. 
Our 3 key products are: : 

- ADP (https://adasiaholdings.com), provides a suite of AI-based Advertising solutions to enable marketers and publishers to achieve greater returns.

- TalentMind (https://talentmind.ai), provides human resource and recruitment professionals with an AI-driven recruitment platform to make hiring more efficient and targeted. 

- CastingAsia (https://casting-asia.com) leverages on artificial intelligence to provide marketers with a smart and safe environment for their influencer marketing activities.

Love to hear more about our journey of initiating these inspiring products? 
**Contact us for our story, our vision, our mission**
(S) tuna251095
(M) nhan@anymindgroup.com 
Homepage: https://anymindgroup.com/
Life at ANYMIND: https://www.youtube.com/watch?v=Fi1YSGbhCnI

![35076657_240855280008522_9167412869300486144_o](https://user-images.githubusercontent.com/38033330/41576626-a4bab86e-73b2-11e8-880a-fef63a88439f.jpg)
![img_0474](https://user-images.githubusercontent.com/38033330/41576652-d62b0462-73b2-11e8-87ae-d632ab60ca93.JPG)
![img_8525](https://user-images.githubusercontent.com/38033330/41576701-0b6954e4-73b3-11e8-9aaf-d44ec8f0df6f.JPG)

**Comment by euronck** [comment]
very cool stuff happening over there!! We are also now using NLP with Spacy :) learning to train models. Very easy stuff once you get passed the bumps.
