### ISSUE TITLE
9cv9 - Blockchain Developer - HCMC - FT

### ISSUE THREAD

**Issue by Huyenpham26101995** [awesome-jobs/vietnam#1066]
## Quận 1, HCM

* Saigon, Vietnam
* Fulltime

##Salary Range: 

* $2500/month or more if good

## Requirements
* Ethereum
* Python
* Nodejs
* Blockchain experience
* Java 

### Must Have

* Be able to communicate in English

### Ideally

* Experience with Ethereum or HyperLedger

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building Smart contract

### Why it would be awesome to work with us
- Laptop provided ( Mac - good one)
- Premium insurance
- Friendly environment
- Working from Monday to Friday

### Contact
Email: huyenpham@9cv9.com 
Skype: huyenpham26101995

**Comment by huydx** [comment]
don't accept recruting firm
