### ISSUE TITLE
[ĐÀ NẴNG] .NET/C# SENIORS

### ISSUE THREAD

**Issue by LaiDungLam** [awesome-jobs/vietnam#1072]
## Location
* Da Nang, Vietnam
* 10th Floor, Vinh Trung Plaza, 225 - 227 Hung Vuong, Thanh Khe, Da Nang

## Salary Expectation

* up to $2,000

## Requirements
* Knowledge of .NET & C# frameworks
* Deep understanding of OOP, design patterns, web services, and SQL server database
* Expertized in HTML and JavaScript, and fluent at least one JavaScript library or 

### Why it would be awesome to work with us:
* Open, friendly, modern working environment
* Flexible working hours( check in 8 – 10 A.M)
* 13th month salary  
* Periodically performance review and salary increase base on competency

## Interested applicants please send CVs to careers@2clicksolutions.com

**Comment by huydx** [comment]
wrong format
