### ISSUE TITLE
SOLAZU LTD,.CO- Ruby On Rails Developer - District 1, SAIGON - FT

### ISSUE THREAD

**Issue by voongvinhlan** [awesome-jobs/vietnam#1122]
## Location
* 55-57 Nguyễn Văn Giai, Phường Đakao, Quận 1, HCM
* Full-time ( Monday ~ Friday, 8:30 ~ 17:30)

## Salary Expectation
* From $700 / month ~

## Requirements
* Có kinh nghiệm RubyOnRails >= 1 năm
* Nền tảng Tư Duy Lập Trình Tốt

## Contact
* mail to lanvv@solazu.com
* Skype : vinhlan1807

**Comment by huydx** [comment]
Lacking 

### Why it would be awesome to work with us (REQUIRED)
### Interesting Engineering Projects (REQUIRED)

**Comment by voongvinhlan** [comment]
Thanks for your check .
