### ISSUE TITLE
[Miyatsu Viet Nam] 02 Smart Contract Developer 

### ISSUE THREAD

**Issue by ngdangdung92** [awesome-jobs/vietnam#1123]
## About us

Miyatsu Vietnam Co., is a Japanese software development company providing services in a wide range of fields to customers both domestic and overseas. 
We are proud to have pioneered Forex and Crypto-currency systems development in Vietnam markets. 

### Location

* 18F, Ladeco Building, 266 DoiCan Str, BaDinh, Hanoi, Vietnam
* Open with candidates from Da Nang, Ho Chi Minh

### Salary & Benefit

* 1500 USD - 2000 USD /month
* Package 14 months salary
* Chance to earn crypto-currency as bonus based on performance

##  Job Description

You will perform following tasks:
- This job is a good opportunity for you to join interesting Crypto-currency and Smart-Contract Project with customers from Japanese & Korea
- Design and implement backend applications in Node JS that interact with smart contracts and other components.
- Maintain code quality, security, organization and automation
- Updates job knowledge by researching new Web technologies and software products;

## Job Requirements: 
The following skills are required to achieve successful performance in this position:
- Strong skill in functional programming in javascript is a must.
- Experience in programming Smart Contract in Solidity
- Have experience in Google FireBase, NoSql, keyvalue database or MongoDB
- Have experience in ECMA 6 is a plus
- Good understanding at software development processes
- Willingness to learn new technologies both by training and self-learning
- Proficient in English 

## Why it would be awesome to work with us

• Have a chance to research more about Blockchain - the newest and #1 trending technology recently.
• Review salary 1 time/year based on employee's performance and contribution 
• 2 month probationary period with 100% salary 
• Bonus: 1 time/ year or more depending on company financial situation 
• Insurance premiums are paid on gross salary 
• Benefit of Union policy and social activities 
• Attractive company allowances in Vietnamese holidays 
• Other benefit follows Vietnam Labor Law 
• Healthy care: once/ year
• Holiday: twice/ year (Summer holiday & Winter trip)
• Teambuilding: 300.000 VND/ month/ person (All Staff)
• Beauty care: 400.000 VND/ month/ person (Only women)
• Bonus for team: twice/ year
• Free Drind/ food
• Work Environment: profesional, youthfull, dynamic
• Having many oppotunities to develop career path

## Contact
Email: nguyen.dang.dung@miyatsu.vn
Website: http://www.miyatsu.vn/

**Comment by TanNgocDo** [comment]
Is this position available for remote working with people from HoChiMinh ?

**Comment by ngdangdung92** [comment]
> Is this position available for remote working with people from HoChiMinh ?

Not yet. But Miyatsu will support about Accommodation Allowance for candidate from Ho Chi Minh & Da Nang
