### ISSUE TITLE
Yojee - Senior Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by sarah1927** [awesome-jobs/vietnam#1126]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000/month or range

## Requirements
* Elixir
* Ruby
* Go
* PostgreSQL
* 4+ years Software Engineering experience

### Must Have

* Be able to work with at least two programming languages

### Ideally

* Production experience with Elixir & Phoenix
* Node.js, Angular.js, React.js or React native
* DevOps experience with Heroku, AWS or Azure, Docker
* Understanding of OTP

### Responsibilities

* Design, develop and execute software solutions to address business issues
* Troubleshoot code level problems quickly and efficiently

### You can bring

* Attention to detail and reliability are what you take pride in
* Excellent communication and collaboration skill
* Enjoy driving things over getting tasks assigned

### Contact
[Easy Apply](https://yojee.bamboohr.com/jobs/view.php?id=26&source=GitHub)
Homepage: Yojee.com
Yojee Careers: hr_at_yojee_dot_com

**Comment by enixdark** [comment]
@sarah1927 Hi, is this position empty for Elixir/Devops job ?
