### ISSUE TITLE
Pixta Vietnam - Jr/Sr Ruby Developer - Hanoi - FT

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#1128]
## Location
* Hanoi

## Salary Expectation
* 500$ - 1500$

## Responsibilities
* Work on both back-end & front-end of web application
* Write clean code and develop a next generation E-commerce system applying Ruby, Amazon Web Service...
* Directly work with oversea team (Thailand, Taiwan, Korea, Japan) to discuss, develop new features (search function, payment, infrastructure…) and implement projects to improve product
* Search & study about new technologies to propose solutions

## Technical Environment
* Programming language: Ruby (90%), Python (Ruby Course is available)
* Frameworks/ Libraries: Tensorflow, Ruby on Rails, ..
* Modern front-end framework including AngularJS, React, Vue, Emberjs.
* Database: Treasure Data, MySql, DynamoDB, SQL...
* Infrastructure: Amazon Web Services (AWS): Opsworks, EC2, S3, DynamoDB, Cloudsearch, Elastic
* Tools: GitHub, Trello, CircleCl, .

## Requirements
* Have Web Development knowledge related to one of the Language programmings (Ruby, Python, C, C++, .Net,...)
* Be familiar with software/web development based on Unix/Linux
* Possess self-learning skill, team work skill and good attitude

### Why it would be awesome to work with us
* Basic salary package: Up to 1500$ + up to 2 months year bonus
* Good rate of salary increasing every year
* Opportunities to push your ability at PRODUCT COMPANY and deeply focus on studying technologies
* Working environment: very friendly, young and professional which encourages innovation, transparency and idea sharing
* Annual company trip, monthly company party, regularly health checkup and lunch allowance
* Club: Table tennis club, English club, Toastmaster club, Photography club...

### Contact
Home page: pixtastock.com / snapmart.jp / fotowa.jp
Facebook: Pixta Vietnam
If you are keen on the job, kind send your CV to: recruit.vn@pixta.co.jp
Many thanks!

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
