### ISSUE TITLE
System Administrator

### ISSUE THREAD

**Issue by Robotinfra** [awesome-jobs/vietnam#1130]
## Location

* Kuala Lumpur, Malaysia
* Remote

## Salary Expectation

* $1000 - $1500

## Requirements

* Proven experience as a System Administrator, Network Administrator or similar role
* Knowledge of system security and data backup/recovery	
* Resourcefulness and problem­ solving aptitude
* Excellent communication skills
* Strong background in Linux/Unix Administration
* Experience with automation/configuration management
* Ability to use a wide variety of open source technologies and cloud services
* Understanding of code and script (Python, Golang)
* Knowledge of best practices and IT operations in an always­ up, always­ available service		
* You’re proactive and curious: always eager to learn new things and happy to share your knowledge with others	
* You enjoy challenges		
* Ability to learn by yourself new technologies
* Functional english reading and writing
* Motivation to work alone in a virtual team		
* Feel responsible of what you’re doing		
* Git source control management

Skills

* Resourcefulness is a necessary skill in this role. You should be able to diagnose and resolve problems quickly. 
* You should also have the patience to communicate with a variety of interdisciplinary teams and users.

### Responsibilities

* Deploy and configure software from existing Ansible formulas and Helm charts
* Manage network servers and tools
* Set up accounts		
* Monitor performance and maintain systems according to requirements	
* Troubleshoot issues and outages	
* Ensure security through access controls, backups and firewalls	
* Upgrade systems with new releases		
* Support internal end users on usage of internal tools		
* Ensuring security and efficiency of IT infrastructure			
* Maintains existing technical documentation	

### You’ll be responsible for

* To maintain, upgrade, manage and monitor our stack.

### Why it would be awesome to work with us

* Working environment: very friendly, young and professional which encourages innovation, transparency and idea sharing

### Interesting engineering projects

* You’ll be working on various web and not­ web related projects, in various industries. Most of them are actually quite fun as it involves a lot of bleeding edge tech, exotic use cases, blockchain and cryptos. No boring stuff.

### Contact

If you think you are the right candidate, send your resume to jobs@robotinfra.com   
NO AGENCIES

**Comment by huydx** [comment]
wrong format
