### ISSUE TITLE
Fulltime PHP Senior

### ISSUE THREAD

**Issue by Vietnambiz** [awesome-jobs/vietnam#1142]
## Location
House number 152, Tran Vy Street, Mai Dich Ward, Cau Giay District, Hanoi

* Hanoi, Vietnam

## Requirements
- 2+ years Dev PHP, OOP, MVC

## Skills
- Proficiency in Js, Jquery, preferred by VueJs
- Have knowledge of HTML, CSS

### You’ll be responsible for

- System architecture design, Database
- Business optimization, source code, SQL statement

### Why You'll Love Working Here
• Clear public roadmap through OKRs, KPIs and corporate policies.
• Bonus: 13th month salary.

### Contact
Ms.Nhung - Recruiter: 0972.433.805
Email: nhungtrieu1606@gmail.com

**Comment by huydx** [comment]
wrong format
