### ISSUE TITLE
Grab - Fullstack Engineer - Sai Gon - FT

### ISSUE THREAD

**Issue by quocthangtran** [awesome-jobs/vietnam#1143]
## Location
Saigon, Vietnam

## Salary Expectation
$2,500 - $5,000

## Requirements
Nice to have: 
- Experience with ES6/ES2015 or ES7/ES2016
- Experience with React, Redux/Typescript
- Experience with at least one CSS preprocessor: Sass, Less, PostCSS, Stylus, etc

## Must Have
- At least 2 years of experience working in the same position
- Experience in shipping web applications to production, CI/CD flow
- Familiarity with the whole web stack, web protocols, and web performance optimization techniques
- In-depth understanding of web frameworks (willing to receive application with diversified programming languages)
- Detailed knowledge of minimum one modern JavaScript framework: React, Ember, Angular, etc
- Proficient understanding of the HTTP protocol

## Responsibilities
- Design, implement & manage web apps that impact millions of users.
- Experience a shipping culture that uses the state of the art web technologies.
- Grow in an environment passionate about knowledge-sharing and code review.
- Learn software engineering practices for coding at scale: static analysis, feature flags, instrumentation, and more.

## Why it would be awesome to work with us
- Bonus: Annual bonus (13th salary).
- Free drive with Grab (budget follow your level)
- Extra Medical Insurance.
- Macbook is provided.
- Fresh fruit, snack and coffee everyday.
- 14 days annual leaves.
- Weekly Tech talks.
- High growth opportunities.
- Working hour: Monday – Friday. Flexible working hours.

JD for you: http://bit.ly/2KfD0ID
Contact
Quoc Thang: quocthang.tran10@gmail.com

**Comment by sluongng** [comment]
Sent CV via Topdev 👍
