### ISSUE TITLE
Front End Developer - HCMC - FT

### ISSUE THREAD

**Issue by TakuVietnam** [awesome-jobs/vietnam#1144]
## Location
Saigon, Vietnam

## Salary Expectation
$1,000-$1,500

## Requirements
Must Have
- Experience with HTML, CSS, Javascript
-  Software development experience in one or more general purpose programming languages.
- English as business level

Nice to have
- Familiar with the modern Javascript library and build system(e.g. React, Redux, VueJS, webpack and etc.).
- Experience to release a web application
- Design skills

### Responsibilities
- Understand our client’s need and improve UI/UX.
- Take ownership to design and implement our new product from scratch.
- Technology selection on client-side.
- Write client-side code for web-based applications, create fast, easy-to-use and develop production ready application quickly.
- Write tests for production code and fix bugs.
- Optimize web applications to maximize speed and scale. 

Great power comes with great responsibilities!

### Why it would be awesome to work with us
- Bonus as 13th Salary
- 12 days annual leaves.
- Have monthly event at our client restaurant
- Chance to learn F&B business
- Chance to try many good food at client restaurant
- Working hour : Monday - Friday 09:00-17:30 *Can be flexible
- High growth opportunity
- Big responsibility

### Interesting engineering projects
We are the first BtoB market place for F&B industry. How F&B business source and order to their supplier for the ingredient is super inefficient right now. We are solving this inefficiency by the power of IT. 

### Contact
Email : info@kamereo.vn
Phone number : 01239443000
Homepage: http://www.kamereo.vn

**Comment by huydx** [comment]
wrong format
