### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - QA/QC Engineer - HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1146]
## Location

* Level 3, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 9:00 to 18:00)

## Salary Expectation
- Commensurate with experience.

## Job Description

Our client’s project will empower the world’s freelance community by creating the largest worker-centric decentralized ecosystem where independent workers can pursue their passions and get the value they deserve from the gig economy.
  * Gather and analyze requirements, prepare and review test plan (test scenarios and conditions, etc).
  * Assist the implementation and automation of various QA projects.
  *  Monitor and analyze/log failures for: automated regression, performance, and various other QA related jobs.
  *  Manage execution time effort to leverage the testing coverage.
  *  Provide input to the project QA estimates.
  *  Defect and Issue identification, logging, tracking, resolution and reporting.
  *  Writing QA Engineering reports.

## Skills Requirements

  *  Proficiency with most frontend/backend aspects as they relate to web based applications, including HTML5, CSS, javascript, react, mongo, rest interfaces etc.
  *  Proficiency with various web debugging tools.
  * Strong web testing automation experience. Solid task automation skills.
  * Good scripting and web related coding skills.
  * Experience testing with mobile devices.
  * 4+ years experience on Testing SW products.

## Why it would be awesome to work with us

 * Attractive salary and annual salary review.
 * Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
 * Extensive on job training, you will always have chance to work with new emerging technologies.
 * Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
 * 12-day annual leave per year.
 * 13th month salary and Bonus based on performance.
 * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

 ## Contact
 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
