### ISSUE TITLE
FETCH TECHNOLOGY VIET NAM - Python Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1147]
## Location:

* 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation:

-  Up to 2000$

## Job Description:
- You can choose to apply for project 1 or 2.

*** Project 1: 

Our client is a software company that develops trading software for reconciliation. They are looking for a backend developer who has experience in Python background. 

You will be working with a team to build automated reports for trading firms and optimizing performance for the speed and accuracy. 

*** Project 2:

Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. 

We are looking for a backend developer who has experience in Python background. You will be working with a team to build backend services cater to our mobile frontend. You will have a chance to be part of a team to bring our app from MVP to production ready.

## Skills Requirements:

  * 1+ years of Python development experience.
  * Understanding of OOP.
  * Experience in using message bus framework.
  * Desire to write clean readable code. 

*** Nice to have:

  *  Experience in Django and Flask.
  * Experience in building/designing chat/Functional Programming.
  *  Have worked in a team who released production app before.
  * Experience in designing technical solution that uses message bus like RabbitMQ, Solace.
  * Experience in Amazon Web Services e.g. S3, EC2.

## Why it would be awesome to work with us

 *  Transportation & Lunch Allowance.
 *  MacBook for work.
 *  Attractive salary, working directly with client, it means 100% of your work efficiency will be recognized for annual salary review.
 *  Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
 *  Extensive on job training, you will always have chance to work with new emerging technologies.
 *  Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
 * 12-day annual leave per year.
 * 13th month salary and Bonus based on performance.
 * Enjoy diversified activities: Happy Hour everyday, Hang out Days, Teambuilding, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

 ## Contact
 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
