### ISSUE TITLE
FETCH TECHNOLOGY VIET NAM - Senior dotNet Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1148]
## Location

* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

- Up to 1800$.

## Job Description

Our client - leading digital wallet service in the Southeast Asia Region, where consumers can easily
purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin. The company was founded in 2014 and headquartered in Singapore.
  * They are looking for a Senior dotNet Developer - The right individual will be self-driven. Someone who takes pride in his product as a developer.
  * Placing emphasis in the maintainability and performance driven code.
  * Assist in building a more efficient environment - automation and dev Ops.

## Skills Requirements

  *  At least 2-3 years developing .NET projects.
  *  Write well designed, testable, efficient code.
  *  At least a Bachelor's Degree in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
 *  Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
 *   Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
 *   Able to apply good security practices.
 *   Familiar with and passionate about BitCoin, its network and protocol.
 *   Independent and self-motivated, great team-player.
 *  Fluent in English, written and spoken.

## Why it would be awesome to work with us

 *  Transportation & Lunch Allowance.
 *  MacBook for working.
 *  Onsite Singapore Opportunity.
 *  Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
 *  Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
 *  Extensive on job training, you will always have chance to work with new emerging technologies.
 *  Social insurance, medical insurance & unemployment insurance according to Vietnam
Labor Law.
 *  12-day annual leave per year.
 *  13th month salary and Bonus based on performance.
 *   Enjoy diversified activities: Happy Hour every day, Hang out Days, Teambuilding, Company trip, Play
Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

  ## Contact
 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
