### ISSUE TITLE
FETCH TECHNOLOGY VIET NAM - iOS Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1151]
## Location

* 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

-  Commensurate with experience.

## Job Description

Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. They are looking for a frontend developer who has experience in Swift
development. You will be working with a team to build the iOS frontend and also create service class to integrate with our enterprise message bus backend system. You will have a chance to be part of a team to bring our app from MVP to production ready.
 
## Skills Requirements

 * MacBook for working
 * 1+ years of Swift development experience
 * Understanding of OOP
 * Able to work in team and follow Git Flow
 * Experience in release iOS App

##Nice to have:

* Experience in releasing an iOS App to App Store.
* Experience in integrating with Restful API/ Message bus.
* Understand MVVM and other design principles.
* Experience in writing unit testing.

## Why it would be awesome to work with us

 * Transportation & Lunch Allowance.
 * Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
 * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
 * Extensive on job training, you will always have chance to work with new emerging technologies.
 * Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
 *12-day annual leave per year.
 *13th month salary and Bonus based on performance.
 * Enjoy diversified activities: Happy Hour every day, Hang out Days, Teambuilding, Company trip, Play
Game (PlayStation, CS Go), Play Sport (Football, Badminton...)

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
