### ISSUE TITLE
FETCH TECHNOLOGY VIET NAM - Devops Engineer - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1152]
## Location

* Ho Chi Minh Branch office: 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, HCMC.
* Ha Noi Branch office: Level 3, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

- Commensurate with experience.

## Job Description

Our client is a leading South East Asia internet group based in Malaysia. They build and invests in disruptive tech companies in emerging markets. They have been in the SEA tech scene for almost 20 years. Within this period, they have made 60 investments, are currently employing 3000+ employees across our portfolio companies and IPOed 5 companies (4 in Australia Stock Exchange and 1 in Bursa Malaysia). Some of the more well-known companies started by our client include: iProperty Group, iflix.
  * Contributing to the engineering culture at our new team, sharing your knowledge and ideas with others, and being open to working in different ways.
  * Be independent-minded & vocal on design & value-add vs cost of implementation of user experience enhancements & features.
  * Unit-test code for robustness, including edge cases, usability, and general reliability.
  * Work on bug fixing and improving application performance.

## Skills Requirements

  * Proven experience in managing horizontally scaled products (with multiple server processes running in parallel, with computing and state synchronized).
  * Experience scaling Redis or other sharded key-value stores.
  * Experience in using and managing AWS managed services (eg. AWS Kinesis, CloudFront, Lambda). You are not required to know the ones that we are using, but you need to be familiar with the AWS environment and products to pick up the implementations fast.
  * Having knowledge using message queues (eg. RabbitMQ, RocketMQ, Kafka) will be a plus.
  * Familiar with continuous integration and deployment practices and tools.
  * Familiar with bug monitoring tools.
  * Comfortable with rapid development cycles and tight schedules.

## Why it would be awesome to work with us

  * Transportation & Lunch Allowance.
  * Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be
recognized for annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary and Bonus based on performance.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game
(PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
