### ISSUE TITLE
TopCV - PHP Developer - Hanoi - FT

### ISSUE THREAD

**Issue by trunghieuhf** [awesome-jobs/vietnam#1158]
## Location
Building 169 Nguyen Ngoc Vu, Cau Giay, Hanoi, Vietnam

## Salary Expectation
$1000 - $1500

## Requirements
* PHP
* Laravel Framework
* MySQL, NoSQL
* 2+ years PHP Dev

## Skills
Proficiency in JS, Jquery, VueJS

## Responsibilities
Great power comes with great responsibilities!

## You’ll be responsible for
* Coding new features
* Business optimization, source code
* Build API, server side for mobile app

## You can contribute for our products
* CV Builder Online: TopCV.vn
* Job sites for Vietnamese young people (vieclam.topcv.vn | viecngay.vn)
* HRM for Companies/Recruiters/HR
* CRM for Business

## Why it would be awesome to work with us
* Work with over 1M users & 10K Business in Vietnam.

## Contact for details
Mr. Hieu Tran - Founder & CEO
hieutran@topcv.vn

**Comment by gamevnlc** [comment]
@trunghieuhf 
Hi Mr Hieu. Is the job still available?

**Comment by trunghieuhf** [comment]
@gamevnlc Yes, it’s always available for talents :D

**Comment by gamevnlc** [comment]
@trunghieuhf 
Thank you, 
I'm not particularly smart. But I have experience. 
Anw I will sent you my CV latter.
