### ISSUE TITLE
HCM Full Time Junior Java Developer

### ISSUE THREAD

**Issue by fluffmyllamaa** [awesome-jobs/vietnam#1159]
## Location

* Saigon, Vietnam
* On-site or work from home

## Salary Expectation

* Upto $900/month

## Skills

* 2+ years of experience in web development technologies & have in-depth knowledge of core Java and Java EE applications. 
* Experience in architecture patterns, coding conventions & best practices
* Experience in one or more of the following Open-source frameworks: Spring 3/4/5 (Boot, MVC, Security, Data, batch, ..)
* Good knowledge / understanding of the following tools and concepts: Maven, Apache Tomcat, ORM (Hibernate, Spring Data), RESTFul APIs, XML, Guava
* Good Knowledge in Relational DBMS: MySQL, PostgreSQL, Oracle 
* Knowledge/Experience in NoSQL DBMS (MongoDB, CouchDB ...)
* Knowledge in CI/CD, Docker, and Restful API 
* Experience in web security
* Hands-on Java IDE: IntelliJ/ Eclipse
* Good communication in English
* Strong leadership, collaboration, presentation skill, ability to think creatively and strategically

### Ideally

* Experience with Elasticsearch, Amazon AWS is an advantage 
* Knowledge of front-end development: HTML, CSS, Bootstrap, ReactJS is an advantage

### You’ll be responsible for

* Building a website for Start-up Project

### Why it would be awesome to work with us

* Competitive salary 
* Be able to work on-site or work from home
* Opportunity to work and learn with senior developers

### Contact
Email: huong.tran@ciaotada.com
Skype: dhuong161095@gmail.com 
Facebook: https://www.facebook.com/FluffMyLlama

**Comment by huydx** [comment]
wrong format
