### ISSUE TITLE
Sendo.vn - Data Engineer (BI Engineer) - HCMC - Fulltime

### ISSUE THREAD

**Issue by thuynguyen93** [awesome-jobs/vietnam#1167]
## Location

* District 7, Saigon, Vietnam
* Fulltime
* Sendo.vn is the online marketplace of FPT Group which connects buyers and sellers around the country. Originally an e-commerce project of FPT Online JSC, Sendo.vn was officially launched on Sept 2012. On May 13rd 2014, Sendo Technology JSC was founded as a member of FPT Group and is responsible for operating Sendo.vn marketplace.
Up to now, more than 80,000 shops have been operating on Sendo.vn, offering a diverse range of products with over 5 million products from 21 different categories.

## Salary Expectation

* $1700/month or negotiation

## Requirements

* Tốt nghiệp đại học/Cao đẳng thuộc ngành quản trị hệ thống thông tin hoặc ngành liên quan.
* Có hiểu biết sâu rộng và có niềm đam mê trong lĩnh vực xử lý và phân tích.
* Có kỹ năng lập trình tương tác với API, kỹ năng lập trình xử lý dữ liệu từ các nguồn khác nhau.
* Có kỹ năng ETL/Datawarehouse/BI là ưu thế.
* Đã sử dụng ít nhất 1 ngôn ngữ lập trình như C/Java, ưu tiên biết Python.
* Đã sử dụng ít nhất 1 hệ quản trị CSDL như SqlSerer/Oracle/NoSql, ưu tiên đã đùng BigQuery.
* Có khả năng học hỏi kiến thức mới, làm việc với áp lực cao, tư duy tích cực và nhiệt huyết, trách nhiệm trong công việc là bắt buộc.
* Ưu tiên: 
** Có kinh nghiệm về Thương mại Điện tử
** Có kinh nghiệm sử dụng BigQuery, cloud service.

### You’ll be responsible for

* Thực hiện các công việc xử lý dữ liệu phục vụ cho các báo cáo BI.
* Lập trình tự động hoá quy trình xử lý.
* Theo dõi việc tổng hợp dữ liệu và xử lý các vấn đề liên quan đến dữ liệu.
* Nghiên cứu các công nghệ mới có thể áp dụng vào công việc để tăng hiệu quả.

### Why it would be awesome to work with us:

* Competitive package: $1700/month, 13th month- salary and 1-6 months bonus salary
* Salary review: 1 time/ year
* Applicable for all normal benefits: insurances, 13th salary, annual outing trip, team building activities
* FPT Care Health Insurance
* Sport and club activities: Football, guitar, yoga.

### Contact
Nguyen Thi Thanh Thuy - Recruiter
Email: thuyntt@sendo.vn
Skype: phuthuyxanh
LinkedIn: linkedin.com/in/thuynguyen93

**Comment by huydx** [comment]
wrong format
