### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by KellyDang86** [awesome-jobs/vietnam#1172]
## Location

* Tan Binh, Saigon, Vietnam
* Full time

## Salary Expectation

* $500 - $1500 

## Requirements
* Frontend Angular
* Min 1+ years Software Engineering experience

### Must Have

* Strong experience in native JavaScript, jQuery, 
* Commercial experience in HTML5, CSS3.

### Ideally

* Understand design pattern and know how to apply it into programming.

### Responsibilities

Ability to work as part of a team, understand the problems of other team members from their perspective, and, when necessary, go above and beyond the job description to work towards a broader team goal

### You’ll be responsible for

* Building a new company project

### You can bring
![monster-pixel office](https://user-images.githubusercontent.com/42370372/44144491-efcd8be8-a0b1-11e8-9631-b7a80d0d490e.jpg)

* Passion for web design and new technologies
* A good analyis skill

### Why it would be awesome to work with us
We provide generous salary, paid time off and a fun, comfortable work environment. You will also have the chance to work with a team of professional software developers who are the best of the best. We also provide free cooked lunches every day in our offices and many chances to socialize outside of work. 
### Contact
Homepage: monsterpixel.us
Place: 168/8 Bùi Thị Xuân Phường 3 Quận Tân Bình HCM
Apply via: anh@monsterpixel.us
Phone: 0902613128 Huệ Anh

**Comment by huydx** [comment]
wrong format
