### ISSUE TITLE
NetEngine - Software Engineer Ruby on Rails - Remote/Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by matthewbarram** [awesome-jobs/vietnam#118]
## The Job

NetEngine is setting up a Vietnam team to support development of our growing apps in that region. We're looking for a senior, experienced ruby on rails software engineer who can lead a team. You'll be one of our first developers in Vietnam, but part of a global happy and talented company building products used globally by companies like Red Hat. We are looking for high quality coders and hackers who take pride in the software and results they create. Become a part of our product development team, and make your mark on some of the most exciting pieces of tech coming out of Australia right now.

**Responsibilities**:
- Gel with the NetEngine values 
- Write and maintain good code 
- Architect and maintain complex applications 
- Optimise app and server performance 
- Working, collaborating and knowledge sharing with other engineers
### Must have:
- Ruby 2.2 - Rails 3 & 4 
- RESTful API design 
- Performance optimisation 
- Unit and integration testing experience 
- Deployment of web applications 
- Agile development methodologies 
- User experience and user workflows 
- Clean, beautiful code 
- Git
### Nice to have:
- NoSQL databases (e.g. Redis, MongoDB) 
- Docker 
- HTML5/CSS3/Javascript (e.g. React, AngularJS) 
- *nix Server Administration 
- AWS: EC2, S3, Cloudfront, RDS
### Why You'll Love Working Here

NetEngine is an agile, creative, software engineering company. Among our clients, you'll find Red Hat, Flight Centre and TEDx as well as local government organisations. We've built a team of smart, energetic and passionate technologists who genuinely love that their work is exciting, innovative and most importantly worthwhile - or we don't do it!

Our lead product Outfit has just secured a 3 year global deal with the biggest open source software company in the world, and our SAAS project collaboration and billing software Trigger is used by hundreds of creative agencies around the world.
## How to Apply

Send an email with CV with a link to your github username to madeleine@netengine.com.au. Please also include details on why you think you would be a good fit for this job.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by matthewbarram** [comment]
@joneslee85 Is there further changes needed? You comment doesn't seem to be here anymore. Thanks Matthew :smile:

**Comment by joneslee85** [comment]
@matthewbarram looks good, thanks :+1:
