### ISSUE TITLE
9cv9 - API Engineer - HCMC - FT

### ISSUE THREAD

**Issue by nhuquynh183** [awesome-jobs/vietnam#1187]
## Location
* HCMC, Vietnam
* Full time

## Salary Expectation
* Up to 2000 USD/Month

## Requirements
* 2-5 years of experience
* Java or Python
* Expert in working with RESTful APIs
* Fluent in English

### Responsibilities
* Build upon our existing technology
* Be instrumental in designing new features / redesigning old features with a view to a final product
* Provide technical product support to external and internal teams

### Contact
* Apply directly here: https://lnkd.in/fcTvMhp
* Skype: nhuquynh18397
* Email: nhuquynh@9cv9.com

**Comment by huydx** [comment]
wrong format
