### ISSUE TITLE
9cv9 - Automation Test Architect - Saigon - FT

### ISSUE THREAD

**Issue by PNi2010** [awesome-jobs/vietnam#1188]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000-2500/month

## Requirements

* Min. 6 years of experiences working on automation test system development
* Min. 3 years of experiences working on similar role.
* Designing system architecture for scalable automation test system and researching new technologies and come up with solutions proposal for new requirements.
* Automated test cases in: Python/Java,  Selenium, AutoTest, Django, etc.
* Networking and Wifi products/protocol such as 802.11, TCP/IP, Switching, Routing, VLAN

### Must Have
* Modern programming language like Python/Java,  Selenium, AutoTest, Django, etc
* Experience in working with cameras and Wifi products
* Good communication English

### Ideally

* Be able to go working onsite in USA and Hong Kong
* CWNA or CCNA certificated

### Responsibilities

* Work directly with the customer to analyze the requirements
* Work with the team to design framework and come up with solutions/system architect
* Lead the team to deliver the products on time with high quality
* Participate in coding and reviewing code of other members
* Monitor and ensure the members following coding guideline and system design
* Travel onsite in US and HongKong to deploy test systems

### Why it would be awesome to work with us

Well compensation package based on performance and value creation
* Bonus review bi-annually based on performance
* Bonus for excellent project performance
* Annually company trip & project close team outing
* Additional health care policy for employees and benefit for family
* Opportunities to work onsite in USA and Hong Kong immediately
* Opportunities to work with leader and learn from brightest people

### Interesting engineering projects
* Travel onsite in US and HongKong to deploy test systems for clients
* Constantly update and experience with new technologies, especially in cameras and Wifi products

### Contact
LinkedIn: https://www.linkedin.com/in/pnghi/
Skype: pnghi@live.com

**Comment by huydx** [comment]
don't accept recruting firm
