### ISSUE TITLE
9cv9 - .NET - HCMC - FT

### ISSUE THREAD

**Issue by nhuquynh183** [awesome-jobs/vietnam#1189]
## Location
* HCMC or Ha Noi, Vietnam
* Full time

## Salary Expectation
* 20-25 million VND

## Requirements
* 3 years of experience 
* .NET
* Nice to have experience in Android/iOS development

### Contact
Apply here: https://lnkd.in/fgWRxQb
Skype: nhuquynh18397

**Comment by huydx** [comment]
wrong format
