### ISSUE TITLE
Python Team Lead in HCMC, Vietnam

### ISSUE THREAD

**Issue by gilbertravels** [awesome-jobs/vietnam#1190]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2,500

## Requirements

– Able to work clean codes and to build an infrastructure from scratch

– Strong understanding of system networking

– Strong in Python and its framework, Django, Flask, etc

– Good in Frontend Javascript, ReactJS is a bonus

– Strong knowledge in building on hosting servers, AWS, Docker

– Fluent in English

## Skills

Python

### Must Have

Strong in Python and its framework, Django, Flask, etc

### Ideally

* Experience with Python and Django

### Responsibilities

Help build up an automated and smart loan making system. The project will be exciting and huge.

### You’ll be responsible for

* A Smart Loanmaking App

### You can bring

* A good eyes for design
* A good backend and python architect skills

### Why it would be awesome to work with us

We are from Singapore

### Contact
Homepage: https://9cv9.com/jobs/python-team-lead/

**Comment by huydx** [comment]
wrong format

**Comment by gilbertravels** [comment]
Can u explain more on this? Thanks!

**Comment by huydx** [comment]
@gilbertravels you could see the correct format in https://github.com/awesome-jobs/vietnam README.md . Please read it **carefully** and make sure your JD is at least correct indent. Careless JD == bad company
