### ISSUE TITLE
Python Team Lead in HCMC (USD2,500 per month)

### ISSUE THREAD

**Issue by gilbertravels** [awesome-jobs/vietnam#1195]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2,500/Month

## Requirements
* Python
- Django
- Flask

## Skills

* Python
- Django
- Flask

### Must Have

* Python
- Django
- Flask

### Ideally

* Able to work clean codes and to build an infrastructure from scratch

### Responsibilities

Help build up an automated and smart loan making system. The project will be exciting and huge.

### You can bring

* A good eyes for design
* A good technical architecture skill

### Why it would be awesome to work with us

– Good Career Prospects

– Follow Vietnamese Labor law

### Contact

Send your CV to hello@9cv9.com
https://9cv9.com/jobs/python-team-lead/

**Comment by huydx** [comment]
wrong format
