### ISSUE TITLE
02 Android Developers (District 1, Hcmc)

### ISSUE THREAD

**Issue by nghinguyen1188** [awesome-jobs/vietnam#1196]
Hello there, we are looking for team members- Android developers to work on our exciting projects. Are you interested? 

**Location:**  District 1, Ho Chi Minh city, Vietnam
Company: Mega Blocks
**Salary Expectation**: around $1,300 net/month

**Do you have......?**
●	At least 2 years of experience as a native Android programmer.
●	Highly efficient in Android Studio 3 and able to code in Kotlin or Java language
●	Deep understanding on Material Design, AppCompat framework and layouts.
●	Construct efficient User-interfaces that are flexible and also draw-cycle efficient.
●	Excellent debugger with Android Studio.
●	Excellent skill in object-oriented programming, SOLID principle.
●	Experience with Web-api, Json, Asynchronous programming.
●	Good experience with create app that support multiple screen resolutions and aspect ratio.
●	Familiar with basic framework such as Retrofit, Json mapping, etc.
●	Basic understanding of financial system, crypto currency and decentralised systems.
 
**You will:** 
●	Work and collaborate with team lead and members to design & develop the most user friendly and responsive native Android Social trading app.
●	Roll out product features on schedule with high QA coverage and quality.
●	Ensure excellent UX and keep Security of the app as top priority.
●	Adopt best practices, coding convention and performance/security guidelines.
●	Collaborate with other team members and participate in cross-functional groups

**We would love to offer you** 
● Above-market salary and bonuses (13th salary bonus, 100% salary in probation period)
● Weekly happy hours, drinks and snack
● Fun and active team activities
● Modern, open and comfortable working environment
● Creative and friendly colleagues, enthusiast and supportive management
● Working from 9:00 to 18.00 Monday to Friday.

### Contact
**Email:** nghi.nguyen@megablocks.io
**Skype:** nghinguyen1188

**Comment by huydx** [comment]
wrong format

**Comment by nghinguyen1188** [comment]
Sorry @huydx , I will create a new one with correct format. Cheers,
