### ISSUE TITLE
Scommerce - Senior Data Engineer - Saigon - FT

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#1198]
## Location

* Rivera Park District 10, Saigon, Vietnam

## Salary Expectation
Up to 1500$/Month

## About us

Founded in 2015 in Ho Chi Minh City, Vietnam, AhaMove is an on-demand logistics service based on the concept of a shared economy, providing customers to fill excess capacity for logistics suppliers and reduce costs for consumers.

You can find out more about us as a Facebook case study or on prestigious Asia Nikkei news This is a tremendous opportunity to take your career to the next level. Please review the
information below and if you are interested, follow the Apply instructions.

## Requirements
- Bachelor degree in Computer Science or Software Engineering. Specialization in data science or a higher degree is a big plus.  

- At least 02-years experience building data platforms and pipelines for analytics

- Excellence at Python (Ruby/Go/Nodejs is a plus)

- Experience with different database systems: MongoDB, Postgresql, Elasticsearch, ...

- Exposure to emerging open source technologies
## Skills
Python, Linux, Database: MongoDB, Postgresql, Elasticsearch, ...

### The Job

- Maintain & Optimize in-house data infrastructure including database, ETL pipeline

- Migrate data infrastructure into the cloud-hosted solution based on AWS/GCP

- Explore and benchmark data systems

- Build/Adopt real-time data processing engine

- Build/Adopt machine learning infrastructure

- Develop data algorithms and ETL pipeline

## Why you love working here

- Disruptive innovations

- Unique challenges with real-world data problems

- People-oriented philosophy of doing business

- Your footprint on the regional on-demand market

- Sharp, motivated colleagues in a fun office environment

- Competitive salaries and benefits according to experience and education level
### 
### Contact
Mr. Dong
Email  dongdd@scommerce.asia
Telegram 091 291 0678
Skype live:mrdongdo
Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
Homepage: 
https://www.facebook.com/scommerce.asia/
https://www.linkedin.com/company/scommerce.asia/

**Comment by huydx** [comment]
wrong format
