### ISSUE TITLE
Scommerce - Sr Front End Engineer - HCM- FullTime

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#1199]
## Location

* 21 Nguyen Trung Ngan District 1, Vietnam
* Fulltime

## Salary Expectation

* $1000-1500/month

## Requirements
**About us**

Founded in 2015 in Ho Chi Minh City, Vietnam, AhaMove is an on-demand logistics service based on the concept of a shared economy, providing customers to fill excess capacity for logistics suppliers and reduce costs for consumers.

You can find more about us as a Facebook case study or on prestigious Asia Nikkei news 

This is a tremendous opportunity to take your career to the next level. Please review the information below and if you are interested, follow the Apply instructions.

##The Job

 Develop highly-responsive, web-based user interface components and modules using Vue.js/React/AngularJS

 Constantly learn and keep abreast of emerging technologies

 Work with product team and UX designers to understand user interactions and iteratively

build customer-facing features.

 Ability to work in an agile environment and Iterate quickly based on customer and

internal feedback.

  
## Your Skills and Experience

 Minimum 1-3 year commercial experience with HTML, JavaScript, CSS or other web technologies

 Knowledge of Javascript frameworks like Vue.JS, ReactJS, AngularJS

 Familiarity with principles of good user experience

 Knowledge of the principles of accessibility and ability to create products that are accessible to users with disabilities, a plus

 Ability to work independently within a highly collaborative team

## Why you love working here

 Disruptive innovations

 People-oriented philosophy of doing business

 Your footprint on the regional on-demand market

 Sharp, motivated colleagues in a fun office environment

 Working 5 days/week at Dreamplex, the best co-working space in HCMC

## Skills
Vue.JS, ReactJS, AngularJS

### Contact
Mr. Dong
Email  dongdd@scommerce.asia
Telegram 091 291 0678
Skype live:mrdongdo
Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
Homepage: 
https://www.facebook.com/scommerce.asia/
https://www.linkedin.com/company/scommerce.asia/

**Comment by huydx** [comment]
wrong format
