### ISSUE TITLE
Scommerce - Sr Java Developer - HCM- FullTime

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#1200]
## Location

* Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC

## Salary Expectation

* $1000-1500/month

## Requirements
•	Xây dựng các hệ thống vận hành của công ty  phát triển tính năng / sửa lỗi để phục vụ cho nhu cầu phát triển vận hành của công ty
•	Hỗ trợ xây dựng các hệ thống khác khi có yêu cầu
•	Định hướng / cải thiện quy trình xử lý của hệ thống, tăng cường hiệu năng và đơn giản hóa các quy trình.
•	Tính năng chính của hệ thống (Lastmile):
o	Quản lý chuyến đi lấy / giao / trả
o	Quản lý trạng thái đơn hàng lấy / giao / trả
o	Các tính năng liên quan đến bàn giao, điều phối và xử lý hàng hóa.
o	Các tính năng cải thiện năng suất của tài xế & nhân viên xử lý tại kho.
o	Các tính năng theo dõi và báo cáo tình hình vận hành.
o	Các tính năng tự động hóa giúp rút gọn quy trình giao hàng.
o	Các tính năng quản lý hàng hóa tại kho.
o	Tính năng quản lý lỗi quy trình & mất / hư hỏng đơn hàng.
•	Tham gia vào việc thảo luận, đề xuất và đưa ra quy trình / tính năng để tối ưu hiệu suất của toàn bộ quy trình vận hành
## NHIỆM VỤ CHÍNH :
•	Phát triển tính năng mới
•	Sửa lỗi
•	Triển khai tính năng mới
•	Viết tài liệu mô tả
•	Thực hiện các bước trong quy trình phát triển phần mềm (documentation, unit testing, …) chung để đảm bảo chất lượng của sản phẩm
•	Cải thiện tốc độ / hiệu năng của hệ thống
•	Nghiên cứu ứng dụng công nghệ mới
•	Hỗ trợ sửa lỗi / xử lý sự cố trong khả năng khi có lỗi / sự cố, có thể của cả phòng ban khác.
•	Hỗ trợ lập trình, xử lý nghiệp vụ cho bộ phận / phòng ban / dự án khác khi được yêu cầu
•	Giao tiếp cải thiện quan hệ với đồng nghiệp
•	Tham gia các hoạt động ngoài chuyên môn của công ty

## YÊU CẦU:

**KIẾN THỨC**
•	Có kiến thức căn bản tốt về lập trình: OOP, Design Pattern, Data Structure, Algorithm …
•	Có kiến thức sâu / vững một trong các ngôn ngữ Java, Python, .Net, Golang
•	Am hiểu về lập trình / kiến trúc web
**KINH NGHIỆM LÀM VIỆC :** 
•	Ít nhất 2 năm tham gia lập trình Web với vai trò Software Engineer
•	Có kinh nghiệm với hệ thống tương đối lớn ( > 100k Daily Active Users)
•	Có kinh nghiệm về SQL lẫn NoSQL
•	Có kinh nghiệm về phát triển Web API (RESTful)
•	Có kinh nghiệm với HTML, CSS, JS là một lợi thế
•	Có kinh nghiệm với cloud (GCP, AWS) là một lợi thế
**KỸ NĂNG**
•	Giải quyết vấn đề
•	Thiết kế hệ thống, cơ sở dữ liệu
•	Luôn luôn có suy nghĩ cải tiến mọi thứ 
•	Làm việc nhóm và độc lập 
**THÁI ĐỘ**
•	Ưu tiên khách hàng
•	Cầu tiến, sẵn sàng học công nghệ mới
•	Sẵn sàng phát huy và đóng góp cho sản phẩm / công ty
•	Sẵn sàng làm việc với thời gian linh động
•	Làm đúng thiết kế, không vi phạm quy trình
### Contact
Mr. Dong
Email  dongdd@scommerce.asia
Telegram 091 291 0678
Skype live:mrdongdo
Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
Homepage: 
https://www.facebook.com/scommerce.asia/
https://www.linkedin.com/company/scommerce.asia/

**Comment by huydx** [comment]
wrong format
