### ISSUE TITLE
Spiderbox Design - ReactJS Developer - Remote/Saigon - C

### ISSUE THREAD

**Issue by SuTran** [awesome-jobs/vietnam#1202]
## Location

* Remote

## Salary Expectation

* 8$-15$/hour

## Requirements
* ReactJS
* CSS
* HTML
* Illustrator

### Must Have

* At least 1 year working with ReactJS

### Responsibilities

* Write high quality code
* Pixel perfect followed design in *.ai file
* Tested before commit

### You’ll be responsible for

* Re-skin our current web app
* Sample UI that you will work with
![UI Sample](https://drive.google.com/uc?export=view&id=1RVpFKKrkR5MJe1gMzdgg1k5n1H8dAaRl)

### Contact
Su Tran: su_at_spiderbox_dot_design or trannguyentiensu_at_gmail_dot_com (0933_056_722)

**Comment by huydx** [comment]
wrong format
