### ISSUE TITLE
Front-End Software Engineer 

### ISSUE THREAD

**Issue by hanvn** [awesome-jobs/vietnam#1203]
## Location

* Saigon, Vietnam
* 7/ 28 Thanh Thai, Dist 10 - Rivera Park Building

## Salary Expectation

* $700 - $1200

## Requirements
* React.js OR React Native
* Javascript Framework - Vue.js/ React/ Angular 
* Web UI, Mobile UI, Design pattern
* 1+ years Software Engineering experience

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop highly-responsive, web-based user interface components and modules
* Constantly learn and keep abreast of emerging technologies
* Work with product team and UX designers to understand user interactions and iteratively
build customer-facing features.

### Why it would be awesome to work with us
* Disruptive innovations
* People-oriented philosophy of doing business
* Sharp, motivated colleagues in a fun office environment
* Working 5 days/week 
* Competitive salaries and benefits according to experience and education level

### Contact
Homepage: Scommerce.asia
HR: hanvn@scommerce.asia (0968 004088)

**Comment by huydx** [comment]
wrong format
