### ISSUE TITLE
Gini - Senior Front End (React/React Native) - Remote - $1500 - FT

### ISSUE THREAD

**Issue by TrangNgTh** [awesome-jobs/vietnam#1209]
## Location

* Remote

## Salary Expectation

* $1500/month (gross)

## Skills
* **React** and/or **React Native**
* JavaScript
* Cloud based services (AWS) or HTTP API
* 2+ years experience in software development

## Requirements
* Education Level (pursuing / obtained) : Bachelor's degree and above preferred
* Required Level of Work Experience : 2-6 years experience in software development

Show us how you love communications and technology, working and playing as a team, solving problems, and managing projects.

### This position will require you to:
* Work closely with UX/UI designers to implement the best user experience for our users
* Have enthusiasm for Agile project management methodologies
* Use your communication skills, we expect you to become an expert in one area of your choosing and be able to voice your ideas and concerns
* Own one or more components of the Gini software stack, from design to implementation to monitoring and operations.
* Be a team player and willing to learn and mentor fellow engineers

## We can bring
* A Guarantee Offer
* Heath Insurance
* Performance Bonus and 13th Salary
* Attractive package, 14 days of annual leave
* Eligible travel to Hong Kong. 

## Contact
Ms. Trang Nguyen 
Email: trang.nguyenthu3@harveynash.vn
Skype: hilly.chan

**Comment by huydx** [comment]
don't accept 3rd party recruiter
