### ISSUE TITLE
IT Finder - Ruby on Rails Developer - District 1, HCM - FT

### ISSUE THREAD

**Issue by nganphungitfinder** [awesome-jobs/vietnam#1210]
## Location

* Saigon, Vietnam
* District 1

## Salary Expectation

* $2000/month

## About Us

You will work for a powerful and affordable social media monitoring and analytics solution for European & USA clients. Based on a search engine that monitors all types of sources (online news, blogs, forums, Twitter, Facebook, Instagram, YouTube …) lets you create alerts on your brand, your competitors, your industry to know what’s being said about you on the internet and measure your online presence with key insights.

You will be part of an ambitious and exciting project with exponentially growing volumes of data to process.

## Requirements
* Knowledge and skills in Lan/Wan, internet service system, computer server system, backup systems, network/workstation peripherals, software application and computer hardware etc.
* Understanding of network system, database, office machine.
* You have a minimum of 3 years of experience with Ruby on Rails.
* You have experience with MySQL/ Redis and a good understanding of scalability issues and distributed architecture.
* You have experience with Ruby on Rails, Capistrano, GIT.
* You know HTML, XML, JavaScript, Ajax.
* Experience with Heroku, Sidekiq and APIs such as Twitter, Facebook, Instagram, LinkedIn is a plus.
* You know how to organize your code following best practices (design patterns) in order to have a code that is maintainable and easy to test.
* You know how to write unit tests.
* You know about Database design and architecture.
* Experience with front-end development (AngularJS) is a plus.
* You can easily communicate in English (strong written English).
* You are inquisitive, know how to problem solve and find solutions that work. You’re autonomous and a team player all at once. Manipulating hundreds of millions of lines of code in a database table does not scare you

## Responsibilities

* Build new features, with unit tests.
* Improve/ Maintain existing features.
* Help to refactor the code base and implement unit tests.
* Contribute to the maintenance, development and improvement of the back end and API.
* Help to solve bugs and address production issues when they happen.

## Why you’ll love working with us

* Annual leave: 15 – 18 days/year
* Social insurance, health insurance, unemployment insurance
* Nice working environment
* 13th-month salary
* Bonus according to the project
* Premium Healthcare for senior employees (12 months)
* Environment-friendly, fun, dedication
* Team-building

### Contact

Ngân Phùng: ngan.phung@itfinder.vn

**Comment by huydx** [comment]
don't accept 3rd party recruiter
