### ISSUE TITLE
IWA Labs Vietnam - Full stack developer - Ho Chi Minh City - full time

### ISSUE THREAD

**Issue by Kaimaan** [awesome-jobs/vietnam#1211]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* $1000-$2000/month or range

## Requirements 
* Bachelor’s Degree in Computer Science or any related discipline preferred
* Experience with 2 or more programming languages
* Experience with databases
* 3+ years Software Engineering experience

### Must Have

* English speaking and writing
* Ability to learn new things quickly
* Team working skills
* Problem solving skills

### Ideally

* Be able to fly
* Be able to dodge bullet
* Be able to tell differences between Java and JavaScript

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building kick-ass software
* Identify bottlenecks and bugs
* Help maintain code quality, organization, and automatization
* Supporting team

### Why it would be awesome to work with us

* Excellent and competitive salary package with 13th monthly salary
* Chance for remote work
* Chance to work from Thailand or Finland 
* Company trips in Asia and Europe
* Office in District 1, Ho Chi Minh City
* Opportunity to improve English skills within a multinational team 
* Guaranteed long-term employment and orient your career development.

### Interesting engineering projects

* blockchain
* big data
* AR 

### Contact
Homepage: www.iwa.fi
Trollman: kai@iwa.fi

**Comment by TanNgocDo** [comment]
Is this a part time or full time job ?

**Comment by Kaimaan** [comment]
Full time (FT)
