### ISSUE TITLE
Carousell - Software Engineer, Full Stack - Saigon - Permanent Full-Time Employee

### ISSUE THREAD

**Issue by phattv** [awesome-jobs/vietnam#1212]
## Location

* Saigon, Vietnam

## Salary Expectation 

* SGD $1,500 - 3,500 (depending on seniority)

## Requirements 

* Full stack experience (Javascript/React for frontend; Java/Python/Go for backend)
* Experience in scrum/agile development cycle to deliver features
* Able to communicate in English (required to work with international colleagues)

## Skills

* Javascript - ideally ReactJS
* Java, Python or GOlang

### Ideally

* Experience with internal tools development

### Responsibilities

* Design and build internal tooling for all Carousell staff members to be productive with the Carousell platform
* Work closely with our Trust and Automation team to build tooling and features to support our internal team
* Work with our Marketplace Operations team to optimize user flow and journey on the internal tooling to achieve higher throughput
* Work with delivery teams to enhance the development experience of the internal tools to simplify development effort of internal tooling
* Write clean, testable code with unit tests

### Why it would be awesome to work with us 

* Free lunch every Friday
* Full medical benefits (including dependents)
* First class equipments (Macbook Pro, dedicated rotatable monitor etc)
* Excellent working environment
* SGD500 learning and development budget every year
* Opportunity to travel to Singapore and/or Taiwan
* Work with engineers from different countries
    
### Interesting Engineering Projects 

* Implementing AI Machine Learning models for detection 
* Implementing detection system in chats 
* Expanding Phone verification / Device Id check to know who are users
* Detecting risky behavior and adding friction for those user
* Working on search results to demote listings of risky users
* Revamp review system

### Contact 

* Homepage: careers.carousell.com
* Contact person: charlotte.lee@thecarousell.com
* Job posting: https://boards.greenhouse.io/carousell/jobs/1268156

**Comment by huydx** [comment]
@phattv review this too
