### ISSUE TITLE
Carousell - Senior Engineering Manager - Saigon - Permanent Full Time Employee

### ISSUE THREAD

**Issue by phattv** [awesome-jobs/vietnam#1213]
## Location

* Saigon, Vietnam

## Salary Expectation

* SGD $5,000 - 7,000 (depending on seniority)

## Requirements 

* People Management Experience
* Degree/Masters in Computer Science, Software Engineering or other equivalent degrees/experience
* At least 5 years of relevant engineering work experience on large-scale software projects and at least 1-2 years of hands-on technical leadership and/or people management experience.
* Ability to coach and mentor team members in their professional development and build self-sustaining teams
* Ability to mediate conflicts and use your experience to drive change and help engineers solve complex problems
* Have exceptional communication skills and an ability to build rapport with everyone in the organization, not just with engineers

### Responsibilities

* Be actively involved for guiding the engineering technical strategy, make strategic decisions and clearly communicate high-level strategy to our team members in order to lead Carousell Engineering to work better and more efficiently in bringing great features to our users faster
* Continuously inspire and mentor our team of Engineers to grow in their careers and professional development
* Be able to clearly communicate technical details to non-technical members of our organization in a manner that is easily understandable
* Communicate the roadmap, scope, and risks of your projects, and lead the delivery of major initiatives on clear timelines
* Be able to stay on top of the bleeding edge of technology and know how to assess a new tech and how it may help Carousell Engineering improve our work and our product
* Anticipate headcount needs and work with the recruiting team to attract and retain high-quality engineering talent for our organization

### Why it would be awesome to work with us

* Free lunch every Friday
* Full medical benefits (including dependents)
* First class equipment (MacBook Pro, dedicated rotatable monitor etc)
* Excellent working environment
* SGD500 learning and development budget every year
* Opportunity to travel to Singapore and/or Taiwan
* Work with engineers from different countries
    
### Interesting Engineering Projects

* Server-Driven Rendering for mobile: render native UI on mobile, but UI and layout configurable on backend, allowing great native UX and rapid changes to UI as needed
* Developer tooling automation: allow engineers to develop internal tooling on our internal platform with no code, auto-generated based on schemas (eg. Protobuf) and layouts to minimize developer time

### Contact 
* Homepage: careers.carousell.com
* Contact person: charlotte.lee@thecarousell.com
* Job posting: https://boards.greenhouse.io/carousell/jobs/1268140

**Comment by huydx** [comment]
@phattv please revise your JD (indent / contact target..)

**Comment by phattv** [comment]
@huydx updated, please review, thanks
