### ISSUE TITLE
MORTGAGE CLUB - 2 RUBY ON RAILS HACKERS - HCMC - FT

### ISSUE THREAD

**Issue by geenguyen** [awesome-jobs/vietnam#122]
**Come join us to build a made-in-Vietnam product that can compete successfully in the US market!**

We would love for you to have a go at this simple programming test http://goo.gl/7R0zmM. This is a good chance for you to learn more about the stuff that we do, as well as for us to learn more about your coding style. 
If interested, please send us your resume, Github repository and application demo's URL. Contact me today at gee@mortgageclub.co

**About Us**
Mortgage Club is an early based stage fintech startup in San Francisco. We leverage data and technology to revolutionize $240 billion dollar mortgage industry by making it cheaper, faster, and more transparent. We aim to be Uber of the mortgage industry by providing a real-time mortgage marketplace where homebuyers can easily apply, shop, and lock in the best loan in minutes.  

**Location**
Work at Citihub Coffee and Co-working Space at 93 Nguyen Van Thu, District 1. It's a new industrial chic open space co-founded by our CEO. Please check out the pics here: https://goo.gl/aM6OVL

**Your Skills and Experience**
- 1 to 5 years of experience in object oriented design, development and implementation using Ruby on Rails
- Experience with ReactJS (or another Javascript framework)
- Hands-on experience writing automated tests using RSpec, Cucumber
- Knowledge in image processing is a plus
- Comfortable with reading and writing in English

**Why you’ll love working here**
- Competitive salary (depends on your talent, not experience)
- Potential salary increase of 20-50% after 1 year
- Stock options for outstanding team members
- Your choice of Macbook Pro or Macbook Air (sorry no Windows)
- Free lunch everyday (we always get headache deciding what and where to eat so let’s just do catered lunch)
- Free gym membership (getting fit is good for both your physical appearance and career) 
- Free laundry (you think washing and folding clothes is a good use of your time?)
- Relaxing and flexible working environment
- Opportunity to travel to San Francisco to work with the team 

**Joel Test score: 10 out of 12**
The [Joel Test](http://www.joelonsoftware.com/articles/fog0000000043.html) is a twelve-question measure of the quality of a software team.
:+1: Do you use source control?
:+1: Can you make a build in one step?
:+1: Do you make daily builds?
:+1: Do you have a bug database?
:+1: Do you fix bugs before writing new code?
:+1: Do you have an up-to-date schedule?
:+1: Do you have a spec?
:+1: Do programmers have quiet working conditions?
:+1: Do you use the best tools money can buy?
:construction_worker:  Do you have testers?  _but we write tests with RSpec + Cucumber_
:+1: Do new candidates write code during their interview? 
:construction_worker: Do you do hallway usability testing?

![download](https://cloud.githubusercontent.com/assets/14802786/10300702/3afe1da0-6c24-11e5-836e-042de8c56fd5.png)

**Comment by mekf** [comment]
hi Gee, do you guys consider remote worker?

**Comment by billytran1222** [comment]
@mekf Sorry as of now, we don't consider remote hackers yet. Our team is in Saigon and San Francisco.

**Comment by geenguyen** [comment]
I have included a programming test to this job description. Go go go! http://i.giphy.com/HoffxyN8ghVuw.gif
