### ISSUE TITLE
XIGA Tech - Senior Rails developer - Remote/Hanoi - PT

### ISSUE THREAD

**Issue by giangnguyennet** [awesome-jobs/vietnam#1223]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* $8-$12/hour
* monthly payment around 10th via VN bank transfer

## Requirements
* Ruby 2.2, Rails 4.2, MySQL
* Plesk API

## Skills
* can use rbenv/rvm correctly (rbenv preferably)
* self-organized
* can read legacy code (important)

### Must Have

* 3+ years experience with Rails
* at least 3 hours/weekday available (important)
* not too bad communication ability

### Ideally

* Experienced with EngineYard, Plesk is a plus
* Computer with MacOS or Ubuntu or any *nix distribution.

### Responsibilities

* Maintain a running web app for selling domain/hosting

### You can bring

* Anything you want as you will be working from anywhere you want.

### Why it would be awesome to work with us

* We're a very small developing team with a strict/funny/smart leader and members
* Good documentation for the project

### Contact
Please send your latest CV in PDF format to Mr. Giang NGUYEN (36): hr@xiga.info

**Comment by phanhoanglong2610** [comment]
Dear Mr. Giang Nguyen,

I'm from Hochiminh City. Is this job still available and suitable for remote working from Hochiminh City?
Looking forward to your reply. Hope that we will have a chance to work together.

Have a good day.
Long

**Comment by giangnguyennet** [comment]
@qcam @nvquanghuy @joneslee85 this is outdated and I would love to have it removed. Could you please consider removing this issue? Thank you.

**Comment by giangnguyennet** [comment]
Is there anyone to take this action please? @joneslee85 @qcam

**Comment by hieuk09** [comment]
@giangnguyennet: We can't delete any job posts (issue) from Github. A job post is considered removed when it is closed. We're now locking this.
