### ISSUE TITLE
9cv9 - Data Scientist - Saigon - FT

### ISSUE THREAD

**Issue by PNi2010** [awesome-jobs/vietnam#1227]
## Location

* D7, Saigon, Vietnam

## Salary Expectation

* $2500-3500/month

## Requirements

* Experience with Machine Learning techniques (e.g., classification, clustering and feature engineering) is a big advantage
* Experience with Artificial Intelligence (e.g., Natural Language Processing – especially for the Vietnamese language, and Computer Vision) is a big advantage
* Good knowledge of algorithms and data structures
* Critical thinking and good problem solving skills
* Good programming skills in one or more languages, especially Java, Python, R
* Good knowledge of databases. Experience with NoSQL databases such as MongoDB and HBase is an advantage
* Experience with software development on Linux
* Master’s or PhD degree in Computer Science, Statistics, Mathematics or a related field is an advantage
* Experience with the following technologies is an advantage:
o Machine learning frameworks, e.g., Mahout, MLlib and scikit-learn
o Search engines, e.g., Elasticsearch and Solr
o Big data technologies, e.g., Hadoop and Spark

### Must Have

* Experience with Machine Learning techniques 
* Experience with Artificial Intelligence
* Good knowledge of algorithms and data structures

### Ideally

* Master’s or PhD degree in Computer Science, Statistics, Mathematics or a related field is an advantage
* Experience with the following technologies is an advantage:
o Machine learning frameworks, e.g., Mahout, MLlib and scikit-learn
o Search engines, e.g., Elasticsearch and Solr
o Big data technologies, e.g., Hadoop and Spark

### Responsibilities
* Develop new algorithms and improve existing ones for client’s various data products (which are employed on multiple platforms: Desktop website, Mobile website and Android & iOS mobile apps). Potential projects include improving / implementing the following systems:
o A search engine to return the products that are most relevant to a user’s search keyword, based on language data (e.g., semantics extracted from Vietnamese search keywords) and past user behavior data.
o A product ranking system to predict the best-selling products of each category (e.g., fashion and electronics), based on past transaction data and user behavior data.
o An advertising system based on users’ search keywords (which is similar to Google AdWords, and requires large-scale, real-time processing capabilities).
o A recommender system to predict products that a user may like, based on his or her past behavior data.
o A system to detect counterfeit products, based on product attributes (e.g., price), textual cues (e.g., product description) and visual cues (e.g., product images).

* In order to develop the above systems, you will have access to various data sources (client’s website):
o User behavior logs (e.g., search keyword data, product impression data and product click data)
o Transaction data (e.g., completed orders and cancelled orders)
o Product databases (e.g., product description and images)
o Third-party data (e.g., Google Analytics data)

* Work with the Head of Data Science through all stages of the algorithm development process:
o Build train and test datasets from the aforementioned data sources
o For each system, develop an algorithm that balances accuracy and speed (client’s websites have millions of visits per month, and thus speed is of great importance)
o Work with data engineers to deploy the developed algorithms in production
o Design A/B tests to measure the impact of the developed algorithms on e-commerce metrics such as click-through rate (CTR) and conversion rate (CR)

* Perform ad-hoc analyses of user behavior logs and transaction data to derive important business insights and metrics, e.g., customer retention rate and customer lifetime value

### Why it would be awesome to work with us
* A great opportunity to develop large-scale data products for a leading e-commerce marketplace with millions of visits per month
* You will work directly with the Head of Data Science (PhD in Computer Science, National University of Singapore (NUS))
* Dynamic and creative work environment
* 13th month salary
* Premium healthcare insurance (Special Care Policy offered by the company), social insurance and unemployment insurance
* Each year, the best employees are awarded a company-sponsored overseas trip

### Contact
LinkedIn: https://www.linkedin.com/in/pnghi/
Skype: pnghi@live.com
Email: pnghi.ttpn@gmail.com

**Comment by huydx** [comment]
don't accept recruting firm
