### ISSUE TITLE
Restaff - Sharepoint/Web Developer - HCM - FT

### ISSUE THREAD

**Issue by bangnguyen2510** [awesome-jobs/vietnam#1232]
## Location:

* Tran Huy Lieu, Phu Nhuan Dist., Ho Chi Minh City, Vietnam
* Full-time

## Salary Expectation:

* $800 - $1200/month

## Requirements:

* At least 1 years working experience in development of latest __SharePoint__ platforms
* At least 1 years’ experience as __SharePoint Developer__
* At least 1 years’ experience with __ASP.NET__
* At least 2 years’ experience in __CSS, HTML and JavaScript/JQuery__. 

### Must Have:

* Good experience in __OOB, ASP.NET, CSOM, JSOM & REST, JQuery__ with __AJAX__
* Experience with __SharePoint Online/Office365/SharePoint Apps__
* Understand __SharePoint architecture__ and __OOTB features__
* Experience in any of the following __SharePoint Technologies__: SharePoint Search, Site taxonomy (Lists & Libraries), Web parts, Timer jobs, Workflows, InfoPath forms
* Have knowledge in one or more integration issues (ITSM, CRM and Portal solutions)
* Customer focused, strong team player, analytical and critical thinking, open-minded, pays attention to details
* Good at communication using __English__, communicate directly with customer via email, conference call

### Ideally:

* Experienced in making Office add ins
* Experienced in working with TFS, Git
* Experience in Agile software development methodologies
* Experienced in European company

### Responsibilities:

* Custom application development utilizing __SharePoint 2010/2013__ technologies.
* Support for administration and maintenance of SharePoint 2010/2013
* Design, develop and implementation of applications using __C#__ and __ASP.NET MVC__ framework.
* Evaluating new technologies and software products to determine feasibility and desirability of incorporating their capabilities within the company's products.
* Implementing new processes, procedures, technologies and tools in order to improve productivity, product quality and performance.
* Analyze the requirements together with team in Norway and Vietnam
* Estimate & plan detailed tasks based upon the requirements from customer
* Develop, unit test and perform code review of applications development using SharePoint
technologies
* Have chance to go and work directly with customer in Norway

### You can bring:

* Have constant curiosity, be creative, responsible and willing to learn new things.

### Why it would be awesome to work with us:

* __Qualified candidates get full 13th month salary for 2018__
* Good career advancement opportunities
* Agile project management style. Dynamic and English-speaking working environment
* Opportunity to acquire technical knowledge and experience in the latest technologies
* Opportunity to go work on-site in Norway
* Extra annual holiday. Social, health, and employment insuranced paid
* Support for team building activities: company trip, sport (football, badminton, etc.), annual trip, happy hour,
* Working hours: 8 hours x 5 days/week (Monday to Friday)
* Free language training: English (company sponsored)

### About us:

__Restaff/House Of Norway__ was established in 2007 and has offices in both Norway and
Vietnam. We are an open and global company with strong commitment to software development
and testing. A global IT world offers great opportunities and challenges. This has led to a more
open and dynamic software industry, which must adapt faster. We live and breathe for this.
Our values are important to us. They tell us about our behavior and our actions. Our values are
based on a fundamental faith in human beings, openness and trust. We believe that lasting values
are created in a vibrant environment of motivated people.

Product-based company with products related from oiling gas to labelling, parking system, etc.

### Contact:

Homepage: https://www.restaff.no/careers
Skype: bang.nguyen2510
Mail: bang.nguyen@restaff.no

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
