### ISSUE TITLE
Lampart Co. - 8  Fresher/Junior PHP Engineer ( Training Program)- HCMC - Full Time 

### ISSUE THREAD

**Issue by Lampart-Company** [awesome-jobs/vietnam#1233]
## Địa chỉ

1st Floor, No.21K, Nguyen Van Troi St, ward 12, Phu Nhuan Dist., HCMC
http://lampart-vn.com/

## Các phúc lợi đặc biệt dành cho bạn:
* Có cơ hội tham gia khóa đào tạo hoàn toàn và được nhận lương.
* Được học hỏi công nghệ mới từ các kỹ sư hàng đầu.
* Trải nghiệm môi trường làm việc của Nhật trẻ trung, năng động và chuyên nghiệp.

## Nội dung công việc:
Đối với các bạn sinh viên mới ra trường vì còn thiếu kinh nghiệm dự án thực tế nên gặp không ít khó khăn khi phải giao tiếp, xác nhận với cấp trên và những người xung quanh hoặc gặp phải những vấn đề về kỹ thuật trong trường các bạn chưa được học.

Hiểu được nỗi lo lắng và khó khăn của các bạn, bắt đầu từ cuối tháng 10/2018 công ty Lampart tiếp tục mở bộ phận đào tạo khóa IV, trong đó chủ yếu sẽ triển khai “Chương trình đào tạo chuyên biệt” dành cho các bạn Fresher/ Junior có mong muốn được tham gia đào tạo trước khi vào dự án thực tế.

Qua khóa học này, bạn sẽ được dạy những vấn đề sau:	

- Trong giai đoạn đào tạo ( 3 tháng): 
* Đào tạo kỹ năng mềm về phong cách làm việc trong công ty nước ngoài, năng lực giao tiếp, Bảo mật,..	
* Đào tạo xoay quanh những giáo trình kỹ thuật (※HTML, CSS, JS, Git, Mysql, PHP,...)	
* Nâng cao kỹ năng giải quyết tình huống thực tiễn nhờ những lớp học đề tài liên quan đến nghiệp vụ thực tế.
- Kết thúc khoá học: 
* Tham gia trực tiếp vào dự án cùng các kỹ sư, đóng vai trò là một PHP Engineer phát triển hệ thống WEB liên quan đến nghiệp vụ.

### Yêu cầu bắt buộc

* Biết HTML, CSS, JS, PHP, MySQL cơ bản	
* Nắm vững các kiến thức nền tảng như cấu trúc dữ liệu, thuật toán, lập trình Hướng đối tượng	
* Có khả năng tự học các kiến thức mới nhanh chóng 
* Ngoại ngữ: Tiếng Anh đọc hiểu tài liệu	
* Sinh viên mới tốt nghiệp và ứng viên từ các khoa Công nghệ thông tin, Toán – Tin hoặc các ngành có liên quan	

### Yêu cầu khác:	
* Ưu tiên ứng viên có kinh nghiệm trong lập trình phần mềm.	
* Giao tiếp tốt với người khác	
* Chủ động tiếp thu học hỏi cái mới	
* Tuân thủ nghiệp vụ với tư cách là thành viên trong team	
* Nhiệt huyết và tinh thần trách nhiệm cao	
* Tự giác hành động đối với những nhiệm vụ nghiệp vụ được giao	
* Có khát vọng mong muốn phát triển cao hơn hiện tại	
* Vui vẻ, nhiệt huyết với công việc	

## Cơ hội - Quyền lợi: 
● Bạn sẽ được tham gia khóa đào tạo tập trung ở Lampart xuyên suốt trong 3 tháng đầu, dựa trên chương trình đào tạo duy nhất của Lampart từ các giảng viên đại học có kinh nghiệm và những kỹ sư cấp trên giàu kinh nghiệm thực tiễn.	
● Sau 3 tháng bạn sẽ được làm việc trực tiếp với các dự án thực tế của công ty.
● Qua 20 tháng học tập và làm việc trong chương trình (bao gồm 3 tháng học + 17 tháng đào tạo và làm việc), công ty Lampart mong muốn sẽ đào tạo ra được nhiều kỹ sư giỏi về kỹ thuật cũng như nghiệp vụ trong tương lai.	
**Lương:** 
+ Lương tháng trong giai đoạn đào tạo (3 tháng): 4,250,000VND ～ 6,500,000VND
+ Lương tháng sau khi được tuyển dụng sau khoá đào tạo: 5,000,000VND ～ 7,500,000VND
● Thời gian làm việc: Từ 8:00 ~ 17:00, Thứ Hai đến Thứ Sáu.	
● Nghỉ Thứ Bảy, Chủ Nhật và các ngày Lễ, Tết.
**Hoạt động:** 
+ Có cơ hội đi ONSITE ở Nhật (1 năm 2 lần)
+ Phúc lợi chi phí TEAMBUILDING cho nhân viên hàng tháng về các hoạt động ăn uống vui chơi trong team 
+ DU LỊCH công ty 1 năm 1 lần & khám sức khỏe 1 năm/lần. 
+ Các buổi TIỆC như tiệc Halloween, Giáng Sinh, Tiệc cuối năm, Tiệc sinh nhật hàng tháng, .... ( Bạn có thể xem thêm trên fanpage FB của Lampart)
+ Hoạt động THỂ DỤC, THỂ THAO thường xuyên với các câu lạc bộ : Bóng đá, bơi lội v.v.... 
**Một số phúc lợi khác**
+ Ngoài các gói bảo hiểm cơ bản, bạn còn được tham gia gói bảo hiểm tai nạn lao động tại Lampart. 
+ Có hỗ trợ tiền ăn tối nếu tăng ca sau 19h00 
+ Hàng tháng có trà, sữa, coffee,... miễn phí
+ Tăng ca đêm sẽ được nghỉ bù có lương vào ngày hôm trước và ngày hôm sau. 
+ Có thưởng nóng dành cho nhân viên chuyên cần hàng quý và hàng năm 
+ Ngày nghỉ đặc biệt dành cho nhân viên nữ: 0.5 ngày/ tháng. 
+ Trợ cấp đối với nhân viên chờ chỉ thị làm việc tại nhà trong các dịp Lễ Tết 
+ Được hưởng những phúc lợi đặc biệt như chương trình quà tết, bánh trung thu, tiền mừng đám cưới (5,000,000 VND), tiền mừng khi sanh con (2,000,000 VND), hoa và tiền phúng điếu.
+ Đối với nhân viên ký hợp đồng không xác định thời hạn: thì từ thời điểm ký hợp đồng không xác định thời hạn, cứ mỗi năm được cộng thêm 1 ngày nghỉ phép. Ngày nghỉ phép không sử dụng hết trong năm sẽ trả vào lương tháng cuối cùng của năm.

### Quy trình tuyển dụng:	

Vòng 1: Thực hiện bài test trên máy tính, về kiến thức Logic, MySQL và kiến thức về lập trình.
Vòng 2: Thực hiện bài test tính cách
Vòng 3: Phỏng vấn trực tiếp	
Hồ sơ ứng tuyển: CV theo mẫu của công ty Lampart [.](http://lampart-vn.com/wp-content/uploads/2017/10/LAMPART_Format_CV.xls) 

### Thời gian:
+ Thời gian nhận hồ sơ： 20/9/2018 ～19/10/2018
+ Thời gian test và phỏng vấn: 1/10/2018 ～26/10/2018
+ Thời gian bắt đầu khóa học: 30/10/2018

## Liên hệ:
Email: recruit@lampart-vn.com
Hoặc số điện thoại: (+84 0) 28-3990-3296　  (+84 0) 28-3990-3297

**Comment by huydx** [comment]
Wrong format
