### ISSUE TITLE
TalentHub Asia - Senior Java Developer - HCMC&Singapore-Independent Contractor

### ISSUE THREAD

**Issue by haonguyen992** [awesome-jobs/vietnam#1234]
## Location
* Nguyen Thi Minh Khai Street, District 1, Saigon, Vietnam

We are a Singapore based company building a recruitment platform that will revolutionize the industry. We’re looking for motivated and hardworking individuals to join our new Vietnam based team that will build software that will revolutionise the industry further.

Once hired, you will be working with individuals from other parts of the world. Therefore, fluency in English (speaking and writing) is a must. As you’ll be working as a team, it’s important to be a team player, easy to work with and keep a positive spirit amongst other team members.

## Salary Expectation
* 2000 USD - 3000 USD monthly

## Requirements
* Java Spring
* RESTful API
* Frontend (at least HTML, CSS, JS)
* 5+ years Software Engineering experience

### Must Have
* At least 5 years of proven knowledge as a Java developer. 
* Experience with RESTful services and microservices. 
* You know your way in a terminal and CLI’s. 
* You can understand and speak English  
* AGILE 
* OOP, OOA, TDD 
* SQL, GWT, Maven, Spring 
* Front-end skills including at least HTML, CSS and (vanilla) JS 
* Experience with Google Cloud Platform is a big plus  

### Ideally
* Experience with AngularJS/ ReactJS/NodeJS

### You’ll be responsible for
* Maintain and improve (existing) technical documents to accurately represent application design and code.  
* Consult about optimal server configuration related to the platform’s load and requirements
* Collaborate with the team to define the specifications of new features
* Define the team requirements and capacity together with the CTO to optimize productivity.
* Monitor production servers to assure maximum uptime - possibly outside of the traditional working hours. 

### Contact
Helen: helen@talenthub.asia/ Skype: haominhtn

**Comment by huydx** [comment]
wrong format, lack of Interesting engineering project etc
