### ISSUE TITLE
KMS Technology - SENIOR RUBY ON RAILS DEVELOPER - HCM - Vietnam

### ISSUE THREAD

**Issue by tholaihr** [awesome-jobs/vietnam#1235]
**JOB DESCRIPTION**
The Brilliant Career You Love 

Are you passionate about innovative software development and be eager to sharpen your expertise every day?

Do you want to be a part of the Great Team who create awesome billion-dollar Software Products for U.S clients?

Do you love to work in the Best Software Outsourcing Company in Vietnam with Good Investment into People Development?

If yes, we strongly believe that you will enjoy each single working day at KMS Technology where you certainly contribute to developing cutting-edge software products for worldwide users with your experience and expertise.

Your key responsibilities:

Love Coding.
Follow Your Passion.
Enjoy Every Single Working Day with Your Nice Colleagues and Our Kind Clients.
Take Your Skill to the Next Level.
The responsibility includes: design, coding, troubleshooting and working with project team as well as customers on features/bug fixes. 

**QUALIFICATIONS**
Skills You need to be Successful:

Strong experience in Ruby on Rails (more than 2 years)
Experience in Amazon Web Services (AWS)
Experience in HTML5, CSS3 and JavaScript
Experience in at least one CSS framework ie Bootstrap
Passionate about building a great UI/UX apps
Competent in English and has the ability to communicate with the client effectively

ADDITIONAL INFORMATION
Perks you enjoy at KMS

- Working in one of the Best Places to Work in Vietnam
- Building large-scale & latest technology software products
- Working & growing with Passionate & Talented Team
- Attractive Salary and Benefits
- Performance appraisal twice a year
- Onsite opportunities: short-term and long-term assignments in U.S
- Flexible working time
- Various training on hot-trend technologies, best practices, and soft skills
- Premium health care insurance for you and your loved ones
- Company trip in every summer, big annual year-end party every year, team building, etc.
- Fitness & sports activities: football, tennis, table-tennis, badminton, yoga, swimming…
- Joining community development activities: 1% Pledge, charity every quarter, blood donation, public seminars, career orientation talks,…
- Free in-house entertainment facilities (foosball, ping pong, boxing, gym…), coffee (latte, cappuccino, espresso) and snack (instant noodles, cookies, candies…)

And much more, join us and let yourself explore other fantastic things!

### KMS Career Page https://careers.kms-technology.com/all/

*** I'm excited to talk to you via Skype: tho.lai / Email: tholai@kms-technology.com

**Comment by huydx** [comment]
wrong format
