### ISSUE TITLE
Harvey Nash - Senior Software Engineer (JS/Ruby/Python) - Remote/Vietnam - $1800 - FullTime

### ISSUE THREAD

**Issue by TrangNgTh** [awesome-jobs/vietnam#1236]
## Location

* Remote
* Daily Fulltime

## Salary Expectation

* $1800/month (gross) and negotiate.

## Skills
* **Ruby** OR **Python** OR **JavaScript**
* **API design** (RESTful and/or GraphQL)
* Data stores
* 4+ years Software Engineering experience

## Requirements 
* Education Level (pursuing / obtained) : Bachelor's degree and above preferred
* Required Level of Work Experience : 4-6 years experience in software development
* Good Communications in **English**.
Show us how you love communications and technology, working and playing as a team, solving problems, and managing projects.

### This position will require you to:

1. **Familiar with:**
* API design, RESTful and/or GraphQL
* Writing tests at different levels of the stack, from unit to integration to functional
* Data stores like MySQL and DynamoDB
* Operations, monitoring and Infrastructure - plus for AWS experience
* Web and Data security
* Very comfortable with at least one scripting language (JS, Python, Ruby, etc)
* Plus for experience in a functional language - Clojure
2. Software development best practices like TDD, Infrastructure as code, CI/CD.
3. At least 4 years of experience developing and operating applications at scale.
4. Experienced with launching an app into the commercial market.

## We can bring
* A **Harvey Nash** Guarantee Offer
* Heath Insurance
* Performance Bonus and 13th Salary
* Attractive package, 14 days of annual leave
* Eligible travel to Hong Kong.

## Contact
Ms. Trang Nguyen
* Email: trang.nguyenthu3@harveynash.vn
* Skype: hilly.chan

**Comment by huydx** [comment]
don't accept any 3rd party JD

**Comment by TrangNgTh** [comment]
@huydx Hi Mr. This is for my company. So a Outsourcing Company can't post our jobs in here?

**Comment by TrangNgTh** [comment]
@huydx No, I think you misunderstood. This is my company's job.

As an outsourcing company, we have a client, of course, but this is business between 2 companies. 

But this job is for our company. The candidates will be come our employee, our staff.

**Comment by huydx** [comment]
I know that, be we want to owner of the project, the job itself must represent the JD, that's why this repo call awesome job :).

**Comment by TrangNgTh** [comment]
@huydx I don't understand what you mean? I think I don't need to explain to you how an outsourcing company working. I think you have enough experience to understand.
What I understand from your answer is You allow the Product company post jobs because that is their project and outsourcing company can't do that because they don't own the project. 

The JD - I wrote it myself, It belongs to me. Just let you know that. If about the JD then just told me to fix it if it can't be present the job.

**Comment by huydx** [comment]
> What I understand from your answer is You allow the Product company post jobs because that is their project and outsourcing company can't do that because they don't own the project.

Yes you're correct

**Comment by TrangNgTh** [comment]
@huydx ok, so 9cv9? Hitachi? Evolab? Sound isn't right.

I can commit with you this a specific project, not kind of normal outsourcing project. Absolute is for Product Line.
I'm a recruiter, not a technical guru like you, obviously. So may be my words/post isn't right with your thinking.

And can we chance to another way to discuss? This is quite difficult? Through Skype? or Line?

After I explain it to you. If you seem it is a ... awesome job then I create a new post?
