### ISSUE TITLE
 Full Stack Developer - JioHealth VietNam

### ISSUE THREAD

**Issue by tyluudinh** [awesome-jobs/vietnam#1237]
## Location

* 83b Hoàng sa, District 1 - HCM, Vietnam
## JOB DESCRIPTION
-	Be a full stack developer for front end, back end, and database related tasks in our team.
-	Develop new features for our products and backoffice systems.
-	Maintain and enhance existing systems.
-	Integrate with third party systems.
-	Work in close contact with non-technical staff to gather and clarify requirements.
-	Define and suggest possible solutions based on those requirements.
-	Implement, deploy, and monitor those solutions.

## Requirements
* You are a RESPONSIBLE person who takes his/her promises to the hearts
* You are a GO-GETTER: you are unafraid to go beyond roles and titles to get great work done, able to spot what is missing, initiate solutions, and connect people naturally.
* You are PASSIONATE, CURIOUS and OPEN to candid feedbacks about your performance and seek any constructive real-time points as a great way to grow.
* You are a DOER who thrives in a fast-paced and collaborative environment and demonstrate strong judgment and a solution-driven mindset. Multi-tasker, but with clear time management and prioritization skills.
* You LOVE DOING GOOD DEEDS to the society and people around you, being kind is your priority in general social context
* 4+ years Software Engineering experience

## Skills/Qualifications
-	In-depth experience with Java; Python is a plus.
-	Experience with MySQL on an advanced level
-	Solid knowledge of HTML5, CSS, JavaScript, and frameworks like AngularJS
-	Good English and communication skills

### Contact
Send your CV to quangn@jiohealth.com

**Comment by huydx** [comment]
wrong format
