### ISSUE TITLE
Restaff - Web Developer - HCM - FT

### ISSUE THREAD

**Issue by bangnguyen2510** [awesome-jobs/vietnam#1242]
## Location:

* Tran Huy Lieu, Phu Nhuan Dist., Ho Chi Minh City, Vietnam
* Full-time

## Salary Expectation:

* $1000 - $1400/month

## Requirements:

* Mimimum 2 years of experience in professional web-app development
* Proficient in __.NET__ Framework technologies C# (ASP.NET MVC, SOAP/REST Web Services …) is required.
* Solid knowledge of modern web development technologies & framework based on JavaScript, HTML, CSS such as Bootstrap, jQuery, etc... is a must.
* Knowledge of __ReactJS__ or similar JS framework (AngularJS, VueJS, etc...)
* Ability to follow good coding conventions, design patterns to develop clean and maintainable project with large and complex code bases.
* Good English comunication (both writing and speaking)
* High responsibility & high reliability.
* Good teamwork, sociable, and hard work.

### Must Have:

* Mimimum 2 years of experience in professional web-app development
* Proficient in __.NET__ Framework technologies C# (ASP.NET MVC, SOAP/REST Web Services …) is required.
* Solid knowledge of modern web development technologies & framework based on JavaScript, HTML, CSS such as Bootstrap, jQuery, etc... is a must.
* Knowledge of __ReactJS__ or similar JS framework (AngularJS, VueJS, etc...)

### Ideally:

* Knowledge with Unix / Linux environment.
* Knowledge or willing to learn data visualization and 3D software development (threejs, unity, WebGL, d3, etc..).
* Experience with GIT.
* Experience with Azure.
* Willing to learn/research other technique to implement for the tasks/projects.

### Responsibilities:

* Develop user friendly cloud-based web management systems with latest web development technologies mainly on __.NET Core__, __ReactJS__ and NodeJS.
* Participate in different phases of the software development cycle including analyzing & designing, implementing, testing, and documenting.
* Contribute & support our team to create great working environment for you and others at Restaff.
* Report directly to Project Manager in Norway.

### You can bring:

* Have constant curiosity, be creative, responsible and willing to learn new things.

### Why it would be awesome to work with us:

* __Qualified candidates get full 13th month salary for 2018__
* Good career advancement opportunities
* Agile project management style. Dynamic and English-speaking working environment
* Opportunity to acquire technical knowledge and experience in the latest technologies
* Opportunity to go work on-site in Norway
* Extra annual holiday. Social, health, and employment insurance paid
* Support for team building activities: company trip, sport (football, badminton, etc.), annual trip, happy hour,
* Working hours: 8 hours x 5 days/week (Monday to Friday)
* Free language training: English (company sponsored)

### About us:

__Restaff/House Of Norway__ was established in 2007 and has offices in both Norway and
Vietnam. We are an open and global company with strong commitment to software development
and testing. A global IT world offers great opportunities and challenges. This has led to a more
open and dynamic software industry, which must adapt faster. We live and breathe for this.
Our values are important to us. They tell us about our behavior and our actions. Our values are
based on a fundamental faith in human beings, openness and trust. We believe that lasting values
are created in a vibrant environment of motivated people.

Product-based company with products related from oiling gas to labelling, parking system, etc.

### Contact:

Homepage: https://www.restaff.no/careers
Skype: bang.nguyen2510
Mail: bang.nguyen@restaff.no

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
