### ISSUE TITLE
[HANOI] Full-time Ruby on Rails Developer at RAKUNA

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1251]
## Location
* Ly Nam De, Hoan Kiem, Hanoi, Vietnam

## Salary Expectation
* NET US$500+/month - heavily depends on your skills and negotiable
* Signing bonus of VND1,000,000 after 2 months of trial

### Responsibilities
* What you make is what you own and be responsible for.
* Manage product pipelines including planning, development, maintenance and strategies.
* Collaborate with core functional teams - Marketing, Mobile, Quality & Operation to achieve business goals in-time.

### Qualification 
* Strong communication skills - both verbal and written for collaboration across different teams and to maintain proper documents
* Write clean, maintainable and efficient code
* Familiar with Node JS or Ruby on Rails (entry level) 
* Familiar with TDD, MVC, PostgresSQL, Redis...etc
* A strong sense of design is a plus
* A human 4.0 Industry by actively participating in technology communities
* Love startup-like environment, want to challenge yourself, and aim for a leadership prospect

## Why join Rakuna
* A chance to be a part of a young & dynamic multi-functional team that serves U.S & global customers with new everyday challenges
* Endless opportunities to challenge yourself through various projects and training
* Regular team-building activities 
* Free lunches!

### Apply
* Apply: http://smrtr.io/HSgd

### Contact
* Talent Acquisition Coordinator: Ly Nguyen - ly@rakuna.co
* For more information: https://www.rakuna.co/

**Comment by ducthien1490** [comment]
![LGTM](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)
