### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Full-Stack Developer (NodeJS, React JS) - HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1258]
## Location

* Level 3, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2000.

## Job Description
Our client is a Singapore based crypto currencies exchange that providing fiat to crypto and crypto to crypto exchange. They aim to be the first exchange to let you trade Blockchain ideas, knowledge and values.

## Skills Requirements
  * More than 3 years working experience with Express, Angular, Node technology stack.
  * Proficient in AWS related services.
  * Proficient in HTML, CSS and JavaScript.
  * Interested in Crypto currency and Blockchain.
  * Proficiency in Apps (Android, IOS) programming language is a plus.

## Why it would be awesome to work with us

  * Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary and Bonus based on performance.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
