### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - iOS Developer (Swift) - HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1260]
## Location

* Level 3, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $1500.

## Job Description
Our client is a leading South East Asia internet group based in Malaysia. They build and invests in disruptive tech companies in emerging markets. They have been in the SEA tech scene for almost 20 years. Within this period, they have made 60 investments, are currently employing 3000+ employees across our portfolio companies and IPOed 5 companies (4 in Australia Stock Exchange and 1 in Bursa Malaysia). Some of the more well-known companies started by our client include: iProperty Group, iflix.

Product is a mobile entertainment platform that provides live and interactive entertainment content in Indonesia. Their first show is a live mobile quiz show in Indonesia, where users can play for free and winners earn a cash prize as well as bragging rights. This is backed by our client. As a counter-thesis to the traditional TV, they aim to build a platform that users can – and want to – adapt their lifestyles around. The product delivers short but high-energy sessions in real time, enabling a shared social experience beyond the screen.

They are in the process of scaling it now, and are looking for an iOS developer. This role is focussed on building a great real-time interactive experience for their users at a scale of hundreds of thousands of concurrent users, and will require excellent team collaboration across business development and other parts of engineering.
  * To write clean, modular and testable code with consistent code style.
  * Contributing to the engineering culture at our new team, sharing your knowledge and ideas with others, and being open to working in different ways.
  * Be independent-minded & vocal on design & value-add vs cost of implementation of user experience enhancements & features.
  * Unit-test code for robustness, including edge cases, usability, and general reliability.
  * Work on bug fixing and improving application performance.

## Skills Requirements
  * At least 2+ years of experience writing native mobile applications in Swift (preferably know Objective-C as well).
  * Proven experience managing REST APIs and Websockets.
  * Familiar with Xcode.
  * Familiar with continuous integration and deployment practices and tools.
  * Familiar with app analytics and bug monitoring tools.
  * Familiar with multitier architecture for mobile apps (ie. clear separation of UI, application and data layers) and associated tools to manage the interaction in-between the layers.
  * Strong execution capabilities surrounding common front-end components such as state management, live/HTTP-based server networking, navigation, presentational components, animation, video playback, file uploading, notifications etc.
  * Strong attention to detail on every line of code, every unit test, and every commit message.
  * Comfortable with rapid development cycles and tight schedules.

## Why it would be awesome to work with us

  * Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary and Bonus based on performance.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
