### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Graphic Designer - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1261]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

* Up to 18.000.000 VND.

## Job Description
Our client is a tech company building a smart chat for finance. They are looking for a graphic designer to join their team in Ho Chi Minh city.

1. Set the right directive.
2. Creates visuals that represent brand’s DNA and objectives.
3. Scope of day-to-day projects.
  * Creates visuals for social updates, including:
      - 2D graphics (illustration, info graphics).
      - Short video animation.
      - GIF animation.
      - Illustration.
  * Marketing assets:
      - Google ads.
      - Social ads (Twitter, Instagram, Facebook, Linkedln, etc).
      - Type of assets: E-flyers, banners, video banner, video campaign, testimonial videos.
  * PR assets:
      - Video.
      - 2D graphics.
      - Short video animation.
      - Video.
      - GIF animation.
  * Professional presentation / video presentation.
  * Website materials.
  * Company’s collaterals.

## Skills Requirements
  * Familiarity with production and rendering methods, including drawing, offset printing, photography, interactive media.
  * Creative thinking skills.
  * Knowledge of Graphic Design software and tools:
     - Adobe InDesign.
     - CorelDRAW.
     - QuarkXPress.
     - Adobe Illustrator.
     - Adobe Photoshop.
     - Adobe Dreamweaver.
  * Ability to work with programming scripts, including XML and HTML.
  * Understanding of the printing process and specifications.

## Why it would be awesome to work with us

* Transportation&Lunch Allowance.
* Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
