### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Python Developer 1 - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1262]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

* Up to $2000.

## Job Description
Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. We are looking for a backend developer who has experience in Python background. You will be working with a team to build backend services cater to our mobile frontend. You will have a chance to be part of a team to bring our app from MVP to production ready.

## Skills Requirements
  * 1+ years of Python development experience.
  * Understanding of OOP.
  * Experience in using message bus framework.
### Nice to have
  * Experience in Django and Flask.
  * Experience in building/designing chat system.
  * Have worked in a team who released production app before.
  * Experience in designing technical solution that uses message bus like RabbitMQ, Solace.

## Why it would be awesome to work with us

* Transportation & Lunch Allowance.
* Macbook for working.
* Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
