### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - iOS Developer - HCMC - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1263]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

* Range $1000 - $2000.

## Job Description
Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. We are looking for a backend developer who has experience in Python background. You will be working with a team to build backend services cater to our mobile frontend. You will have a chance to be part of a team to bring our app from MVP to production ready.

## Skills Requirements
  * 1+ years of Swift development experience.
  * Understanding of OOP.
  * Able to work in team and follow Git Flow.
  * Experience in release iOS App.
### Nice to have:
  * Experience in releasing an iOS App to App Store.
  * Experience in integrating with Restful API/ Message bus.
  * Understand MVVM and other design principles.
  * Experience in writing unit testing.

## Why it would be awesome to work with us

* Transportation & Lunch Allowance.
* Macbook for working.
* Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
