### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Python Developer 2 - HCMC - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1264]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

* Commensurate with experience.

## Job Description
Our client is a software company that develops trading software for reconciliation.
They are looking for a backend developer who has experience in Python background. You will be working with a team to build automated reports for trading firms and optimizing performance for the speed and accuracy.

## Skills Requirements
  * 1+ years of Python development experience.
  * Understanding of OOP.
  * Desire to write clean readable code.
### Nice to have:
  * Experience in Functrional Programming.
  * Experience in Django.
  * Have worked in a team who released production app before.
  * Experience in Amazon Web Services e.g. S3, EC2.

## Why it would be awesome to work with us

* Transportation & Lunch Allowance.
* Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
