### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - QA Team leader - HCMC - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1265]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $1500.

## Job Description
Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. They are looking for a Software QA Engineer to join QA Team. Their team is responsible for chat-based app which is an fintech app that besides socializing, they also support real-time financial interactions and bots integration. You will be responsible for Automating the iOS app flows and related web services with a focus on quality and making sure their clients have the best user experience with their products. In addition, you will be interacting with internal teams to explore and make more improvements on their products. With the potentials to be the unicorn in applying technology to finance, they are a enthusiastic and fast-growing team. Come join them!
* Responsible for testing and Automating client application and qualification of the chats and bots content delivery and ingest systems primarily focused on mobile applications.
* Experience with testing client-server interactions should also be a core area of experience as well as the ability to access and interpret system and application level logs.
* Experience with building and maintaining custom iOS apps will be considered a plus.
* This position requires a strong individual contributor that can work on projects independently and collaborate with cross functional teams in addition to working with engineering teams to debug and reproduce issues. Candidate must be dynamic and prepared to test and regress a high volume of changes on a day-to-day basis.
* This position requires strong analytical skills in not only approaching and executing tests but in analyzing the details of test results for projects. Strong bug reporting skills and ability to communicate clearly with developers are a must.

## Skills Requirements

* BS in Computer Science or similar work experience.
* 3+ years of QA experience, with a consistent track record detecting and writing bug reports.
* 2+ years of QA Automation experience on Mobile testing on different platforms and Python Webservices.
* Experience working with OS X and iOS platforms.
* Proficiency in Python, Javascript, Unix.
* Flexible and able to adapt to rapidly changing requirements.
* Proven ability to partner and communicate multi-functionally, and to seek out information when required.
* Able to work independently.
* Comfortable with command-line interfaces, some exposure to shell scripts and UNIX.
* Strong analytical skills and ability to autonomously solve problems, as well as collaborate with your team.
* Strong verbal and written communication.
* Positive attitude and strong interest in learning new systems and skills.
* Be able to provide QA solutions for a given system.
* Have experiences in building a QA team.

### Nice to have:
* Knowledge about google cloud platform (Datastore, Firebase, etc.).
* Knowledge about Swift and mobile testing automation tools (Appium, etc.).

## Why it would be awesome to work with us

* Transportation & Lunch Allowance.
* Macbook for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
