### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - UX/UI Designer - HCMC - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1266]
## Location

* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $1000.

## Job Description
Our client is a tech company building a smart chat for finance. They are looking for a UX/UI designer to join their team in Ho Chi Minh city.
* Discussing new features for the app during brainstorming sessions.
* Design graphic UI elements, like menus, tabs, widgets, charts.
* Laying out flowchart for the Developper team.
* Identify potential UX problems & find solutions.

## Skills Requirements

* At least 2-3 years experience in building previous UI/UX for mobile applications.
* Proven work experience as a UI/UX designer or similar role (2-3 years minium).
* Knowledge of wireframe tools (Invision).
* Knowledge of design software (Adobe Photoshop).
* Knowledge in using Sketch App.
* Good self management (autonomous with task).
* Capable to work in team with Developers.
* Details oriented.
* Good Communication Skills: Fluency in English is a must.
### Nice to have:
* Knowledge in app gamification.
* Knowledge/experience in Finance/investing.

## Why it would be awesome to work with us

* Transportation & Lunch Allowance.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.
* Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: hana@fetch.tech
 * Skype: nghinghi283152
 * Phone: 0169 441 3798
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by huydx** [comment]
not support recruiting agent
