### ISSUE TITLE
WORKNETICS VIETNAM - Senior Big Data Engineer - HCMC - FT

### ISSUE THREAD

**Issue by worknetics-hr** [awesome-jobs/vietnam#1282]
## Location

* HCMC, Vietnam
* Full time 

## Salary Expectation

* USD $1500 - $2500/month

## Job Description
We are looking for a talented individual who would be up  for the rewarding challenge to be our Senior Big Data Developer. You  will participate in all aspects of the software development lifecycle  which includes estimating, technical design, implementation,  documentation, testing, deployment and support of application.

Here at Worknetics we embrace an inclusive **team-based culture** where employee participation at all levels is valued. We encourage communication, feedback and ideas to be exchanged in every team meeting. We believe that our organization culture is a representation of who we are to our members, clients and partners. When you're an engineer at Worknetics, you are part of the heart and soul of the company.

## Responsibilities
* Build data integration pipelines to extract, cleanse, and integrate data from a variety of sources and formats for analysis and use across cases.
* Perform data profiling, discovery, and analysis to identify/determine location, suitability and coverage of data, and identify the various data types, formats, and data quality which exist within a given data source.
* Craft re-usable data extraction/ingestion pipelines and templates to demonstrate the logical flow and manipulation of data required to move data from source systems into the target data lake, warehouse, and/or sandbox.
* Perform hands on data development to build the data extraction, movement and integration, leveraging state of the art tools and practices, including both streaming and batched data ingestion techniques.
* Assist in creation of data requirements and model design as necessary and appropriate.

## Requirements
* Minimum of 3 years of work experience with the Apache Hadoop Ecosystems to extract, integrate, cleanse and organize data, including experience with either the Hortonworks or Cloudera distributions.
* Key Tools and Technologies - Spark, Scala, Python, Java
* Experienced in working with the following types of workloads and data pipelines:
* Enterprise-scale ETL and ELT batched workloads
* Near real-time micro-batches
* Streaming data
* Experience in Data Governance frameworks
* Some experience performing conceptual and logical data model design
* Strong NoSQL, SparkSQL, and ANSI SQL query language skills
* Strong verbal and written communication and English language skills
* Experience in AWS or Azure

## Why you'll love with us
We have a strong belief in value adding, therefore, our passion is anchored in the work that we do, and this is reflected in our product which strives to make an impact in millions of lives on a daily basis.
Our team is empowered by creating amazing services and tools that aims to serve people across all walks of life.

Opportunities & Benefits: 
* Work with our team in **Singapore** & onsite working opportunity in Singapore

* We believe in investing our team through **continuous learning and overall development**. We want to help you grow holistically along side us.

* We are very selective with our Clients, we only work on awesome Products we believe have strong market potential which in turn **adds significant value to your resume portfolio**.

* We believe in work-life balance, by putting in place a standard 8 hour daily work schedule from Monday to Friday. **Work hard and play equally hard with us!**

* Be rewarded with attractive remuneration for initiating ideas that bring innovation

* Insurance coverage

* 13th month salary bonus + performance based bonus

### Tell Us!
We would love to hear what skills, work projects or achievements make you a strong candidate for this position

### Contact
***Apply now! Email: hr@worknetics.net**

**Comment by qcam** [comment]
Closing because the job has been expired 🚀.
