### ISSUE TITLE
[feedAustralia] - [Experienced Software Engineer: Full Stack Ruby on Rails - [Melbourne, Australia] - [FT]

### ISSUE THREAD

**Issue by davidsalajan** [awesome-jobs/vietnam#1283]
## Location

* Melbourne, Australia
* Remote 

## Salary Expectation

* $30 - $50 AUD per hour

## Requirements
* Ruby
* Rails
* PostgreSQL
* Javascript

### Must Have

* Excellent written and verbal English
* 5+ years of Ruby experience

### Ideally

* Skilled in TDD/BDD - if you cover all your code with specs and comments, and have a clear 
understanding what specs are used for, we're looking forward to talking to you!

* Experience in relational Databases. (performance/compatibility/fundamental features)

* Experienced in modular applications: different independent parts with internal and external API's

* Solid analytical skills. Ability to think proactively and to cover all aspects of a new feature/requirement

* Experienced in HTML, JS (Backbone, Angular JS) and mobile development frameworks 

* Working knowledge of postgresql 9.2, triggers, stored procedures, constraints

* OOP history

* Unix/Linux experience

* Experience with legacy ruby/rails/javascript code

* Prototype and JQuery

* Fast Learner

* Contributive thinker

* Amazon EC2 experience

* Team Player

### Contact
David 
david at hubhello dot com
hubhello.com
feedaustralia.org.au

**Comment by qcam** [comment]
Closing because the job has been expired 🚀.
