### ISSUE TITLE
Fetch Technology Vietnam - React Native 1 - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1287]
## Location

* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, Ho Chi Minh City.
* Level 3, 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* Level 3, Dai Phat Building - 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$

### Us 

Our client is a decentralized data curation protocol with a mission to make trusted and reliable information readily accessible to everyone. Through token staking and game theory, they incentivize data submission and verification at scale.

They’re a Thai/Singapore blockchain startup with a young, passionate and talented Stanford-MIT team, funded by world-class VCs. They are looking for similar candidate who share their vision and make the world a better place through power of decentralization.

They are looking for skilled developers to join the core team to build mobile application on top of their blockchain protocol. Our client is an open, permissionless blockchain protocol for decentralized data curation on token incentivized communities. This is a unique opportunity to develop applications at the forefront of blockchain technology. 
### Job

* Design, build and maintain API endpoints for interfacing with our client blockchain and SQL database.
* Develop mobile application using React Native.
* Derive execution plan from product requirements — able to own the solution and be responsible for the deliverable of the product.
* Write high-quality, clean, maintainable code using engineering best practices (unit testing, source control, continuous integration, etc.).
* Provide input on UI/UX, identify and fix bugs before they get to the users.
* Work with product manager/marketer to integrate various analytics tools for optimizing growth and usability, including A/B testing.
* Collaborate cross-functionally with other teams, including engineering (internal and external), data science, product management, executive leadership, and recruiting.
* Be a steward and influencer of our early engineering culture.

## Requirements

* At least 1 year of experience in mobile application development.
* Highly proficient in mobile application development using React Native.
* Highly proficient in JavaScript and front-end development technology.
*  Experience with testing framework and technique.
*** Nice to have:
* Experience in UI/UX design.
* Experience in launching and maintaining large-scale mobile applications.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/
Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
