### ISSUE TITLE
Fetch Technology Vietnam - React Native 2 - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1288]
## Location

* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, Ho Chi Minh City.
* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$

## About job
Our client is a software development company producing software for electronic trading, a SaaS offering based on monthly licensing.You will produce two applications.The first application will be a chat application (the second one based on success in the first application). 

The basic functionality is like what one expects in any of the many chat applications. The main difference between something like WhatsApp and the application they will create is that most chat applications are geared towards generating a network of participants as easily and quickly as possible, primarily through the use of the mobile address book to automatically find "friends" and make these contacts available in the address book. Their app will instead be geared towards privacy. 
Therefore, they will never automatically establish contacts, chats can only be established via explicit permission from the user. Also, contacts will not be shareable to other users. So here are some basic functionalities:
* User will establish an account in the app with email verification.
* Once the account is established the user may add contacts. Contacts are invited either by sharing QR Code in person (one person displays QR Code, the other person scans it) or the app generates a URL which is then shared via email, sms or any available mechanism.
* Once the invite is accepted the users can chat and all the usual behavior applies: users can send text, emojis and pictures

## Requirements

* At least 1 year experience with React Native (non-Expo).
* Have development experience with real time chat application.
* Experiences with external libraries such as QR code scanner, access device's contact/SMS, sharing, upload picture.
* Know and skilled with at least one state manager framework (Redux or MobX).

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/
Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
