### ISSUE TITLE
Fetch Technology Vietnam - QA Engineer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1289]
## Location
* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$

## About job

Our client is a digital lending company that is revolutionizing access to financial products for millions of emerging consumers in Indonesia. They have developed the first digital data-driven credit underwriting and risk assessment platform to process consumer loan applications and determine their credit worthiness using its mobile app.
Established in late 2016, they deployed its lending platform in Jakarta and surrounding cities, and they are about to enter a hyper-growth period. Expansion to the rest of Indonesia is expected to complete within a year. Our client is based in Jakarta and is backed by leading venture capital firms in Indonesia and Singapore.
They are looking for a Software QA Engineer with CAN-BREAK attitude for cleverly uncovering bugs, flaws, and breaking points in our software so that we always release high quality products as scheduled.

* Manually identify and report bugs early.
* Fully understand all of product requirements and technical implementations of all their apps, services, and tools.
* Report bugs clearly with all the relevant information to make it fixing easier.
* Maintain test cases such that they have good test coverage, informative, and easy to execute.
* Analyse and systematically approach bugs reported, always coming up with practical short term and long-term process improvements to avoid them.
* Identify things that can go wrong early but also quick to investigate bugs reported in production.
* Work closely with other engineers, products, data scientists, operations.

## Requirements

* Pay attention to detail, expect high quality, and care about user experience.
* Have deep knowledge on web services and mobile applications.
* Great team player, have excellent work ethics, and have solid technical communication skills.
* Meticulous in following processes and highly organized.
* Have experience in all kinds of development, testing, and deployment tools.
* Experience in agile development process and applications such as Trello.
* Engineering/Computer/IT degree with 2 years of diverse software development experience and teams.

*** Nice to have:
* Have some experience in coding, testing, debugging, and troubleshooting with a programming language, especially in Python.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
