### ISSUE TITLE
1dreamm - Ruby on Rails Developer - Ho Chi Minh - PT

### ISSUE THREAD

**Issue by cuongxg** [awesome-jobs/vietnam#129]
## About us
- We are a young startup team and looking for a Ruby on Rails developer working part time and remote at Ho Chi Minh city. You will work with another RoR developer, we also have iOS, Android developer, designer in our team.
## Location
- Saigon, Vietnam
- Remote
## Time
- Work remotely 4 hours a day from Monday to Thursday
- Sunday: Work at Binh Thanh district office from 13:30 to 17:30
## Salary Expectation
- $200 - $500/month
## Requirements
- Good experience on Ruby on Rails, front-end, back-end development
- Good knowledge on html, javascript, css
- Experience with git, github, bitbucket
- Prepare A laptop with MacOS or Linux OS (Ubuntu) to work remotely
### You’ll be responsible for
- Building a web and mobile web with Ruby on Rails
### Contact

Mr. Hien
Email: hien@1dreamm.com
In your CV, please write about RoR projects that you have participated in and how did you contribute to these projects.

**Comment by joneslee85** [comment]
Bạn đọc lại README về guideline của job pót vì post không hợp lệ. Cập nhật và chỉnh sửa xong thì cho mình biết. Post không hợp lệ sẽ bị xoá sau 2 ngày

**Comment by cuongxg** [comment]
Mình đã edit lại rồi nhé

**Comment by joneslee85** [comment]
please fix the title, it does not comply

**Comment by cuongxg** [comment]
Bạn xem giúp nhé

**Comment by joneslee85** [comment]
:+1:
