### ISSUE TITLE
Fetch Technology Vietnam - Senior Devops - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1291]
## Location
* Level 3, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 2000$

## About job

Our client is a digital lending company that is revolutionizing access to financial products for millions of emerging consumers in Indonesia. They have developed the first digital data-driven credit underwriting and risk assessment platform to process consumer loan applications and determine their credit worthiness using its mobile app.
Established in late 2016, they deployed its lending platform in Jakarta and surrounding cities, and they are about to enter a hyper-growth period. Expansion to the rest of Indonesia is expected to complete within a year. Our client is based in Jakarta and is backed by leading venture capital firms in Indonesia and Singapore.

* Design, set up, build, and maintain software infrastructure using open source software or cloud services to maximize rapid software delivery and quickly scale our all of services as usage demands.
* Analyse and systematically approach requirements and bugs reported, always coming up with practical short term and long-term solutions that minimize complexity and maximize value.
* Passionate about automation and follow ‘Infrastructure as Code’.
* Include security, maintainability, reusability, and testability when developing software solutions and code reviewing.
* Factor Linux/Unix OS system internals, data storage, computing resources, microservices in the produced software architecture.
* Identify things that can go wrong early but also investigate bugs reported in production.
* Apply and tailor software development concepts and best practices.
* Work closely with other their engineers, products, data scientists, operations.

## Requirements

* Have working experience in developing, testing, debugging, and troubleshooting system-level scripts in Python or Bash.
* Highly skilled in all kinds of infrastructure tools that turns source code in a text file to infrastructure resources in production, including but not limited to: Linux (Ubuntu), Git, Ansible, Docker, Kubernetes, Alibaba Cloud/AWS.
* Experience in database management, be it RDBMS or in-memory data storage.
* Experience in Big Data Infrastructure.
* Engineering/Computer/IT degree with 3 to 5 years of back-end software development and 1-year cloud infrastructure experience and teams.
* Great team player, have excellent work ethics, and have solid technical communication skills in English.

*** Nice to have:
* Experience in agile development process and applications such as Trello.
* Communicate in Indonesian.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
