### ISSUE TITLE
Atmarkcafe VN - Senior Mobile (IOS/Android) - HN - FT

### ISSUE THREAD

**Issue by nhung693** [awesome-jobs/vietnam#1294]
## Location

* 36 Hoang Cau, O Cho Dua, Dong Da, HN

## Salary Expectation

* Depends on Experience

## Requirements
1. IOS:
* Have at least 3 years of practical experience in one of the Swift or Object-C languages
* Prioritize:
* Knowledge of UI-UX
* Have knowledge of MVC, MVP, MVVM
* Mastering knowledge of RxSwift, Realm,
* Mastering knowledge of multithreading, data structures, algorithms and design, Auto Layout, Memory management, Core data
* Knowledge of OOP, Design Pattern.
* Make good use of source management tools: SVN, GIT.

2. Android:
* Experienced 3 years or more.
* Knowledge of Java, Kotlin, Android, RxAndroid, RxJava.
* Have good knowledge of new technology related to adroid. • Knowledge of UI-UX, Design Parttern, SVN, Git.
* Experienced in MVC, MVP, MVVM.
* Prior experience in mobile applications (iOS, Android)
* Use Japanese is advantage.
* Having a store application is an advantage.
* Ability to work independently and teamwork

## Skills
* Swift or Object-C, UI-UX, Java, Kotlin, Android, RxAndroid, RxJava.

### Why it would be awesome to work with us
* Immediately cover all statutory insurance schemes when you sign a contract with Atmarkcafe (after 2 months probation).
* Bonus according to year-end sales and attractive holidays.
* Review salary twice a year
* Organize teambuilding regularly and annual travel company in attractive locations (5 million / person / year + family rate)
* Environment friendly, dynamic, diverse, many opportunities for promotion
* Continuously provide advanced training to help employees improve their skills and achieve better performance.
* Opportunity to travel abroad (Japan).
The company's benefits: birthday, lunch at the company, ... are held periodically.

### Contact
* Homepage: atmarkcafe.org
* Email: hr@atmarkcafe.org
* Call: 024 3734 9747

**Comment by huydx** [comment]
not support recruiting agent
