### ISSUE TITLE
Fetch Technology Vietnam - Front-end Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1295]
## Location
* Floor 3rd, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Ward Phuoc Long A, District 9, Ho Chi Minh City.
* Floor 3rd, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$.

## About job

Our client is a decentralized data curation protocol with a mission to make trusted and reliable information readily accessible to everyone. Through token staking and game theory, they incentivize data submission and verification at scale. 
They’re a Thai/Singapore blockchain startup with a young, passionate and talented Stanford-MIT team, funded by world-class VCs. They are looking for similar candidate who share their vision and make the world a better place through power of decentralization.
They are looking for skilled developers to join the core team to build web application on top of their blockchain protocol. Our client is an open, permissionless blockchain protocol for decentralized data curation on token-incentivised communities. This is a unique opportunity to build and deploy softwares at the forefront of blockchain technology.
* Architect and build state-of-the-art responsive web application that works flawlessly on all modern browsers.
* Write clean and maintainable code using engineering best practices (unit testing, source control, continuous integration, etc).
* Maintain documentation and support for internal and external use.
* Collaborate cross-functionally with other teams, including engineering (internal and external), data science, product management, executive leadership, and recruiting.
* Be a steward and influencer of our early engineering culture.

## Requirements

* Highly proficient in JavaScript and CSS.
* Highly proficient in React and Redux or similar state-management framework.
* Passion for building decentralized applications.
* At least 1 year of experience in web development.

*** Nice to have:
* Understanding of blockchain technology and crypto economics.
* Strong background in web development technologies.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
