### ISSUE TITLE
Fetch Technology Vietnam - VueJS Developer - HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1297]
## Location
* Floor 3rd, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$.

## About job

Our client is having a platform providing all the tools needed to make the process of ship chartering easier. It aims to be an all-in-one platform to connect ship brokers, chartering managers, and ship owners together by encouraging them to collaborate and fix deals online. 

It will begin its mission by offering a messaging solution designed specifically to facilitate collaboration among chartering teams. It is working with A*Star Institute of Infocomm Research (I2R) to develop a natural language processing engine to perform automatic data extraction of ship positions from unstructured email texts.
* Improve and optimize existing systems.
* Front-end develop and integrate new search function.
* Details will be discussed through the interview.

## Requirements
* BA/BS degree in Engineering, Computer Science, IT or a related field.
* At least 2 years of experience in VueJS.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
