### ISSUE TITLE
Fetch Technology Vietnam - Full-Stack Developer - HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1298]
## Location
* Floor 3rd, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1700$.

## About job
Our client is a Singapore based crypto currencies exchange that providing fiat to crypto and crypto to crypto exchange. They aim to be the first exchange to let you trade Blockchain ideas, knowledge and values.
* More than 3 years working experience with Express,Angular, Node technology stack.
* Proficient in AWS related services.
* Proficient in HTML, CSS and JavaScript.
* Interested in Crypto currency and Blockchain.
* Proficiency in Apps (Android, IOS) programming language is a plus.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
