### ISSUE TITLE
Fetch Technology Vietnam - Graphic Designer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1299]
## Location
* Floor 3rd, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 900$.

## About job
Our client is a tech company building a smart chat for finance. They are looking for a graphic designer to join their team in Ho Chi Minh city.
1. Set the right directive.
2. Creates visuals that represent brand’s DNA and objectives.
3. Scope of day-to-day projects:
* Creates visuals for social updates, including: 2D graphics (illustration, info graphics), Short video animation, GIF animation, Illustration.
* Marketing assets: Google ads, Social ads (Twitter, Instagram, Facebook, Linkedln, etc), Type of assets: E-flyers, banners, video banner, video campaign, testimonial videos.
* PR assets: Video, 2D graphics, Short video animation, GIF animation.
* Professional presentation / video presentation.
* Website materials.
* Company’s collaterals.

## Requirements

* Familiarity with production and rendering methods, including drawing, offset printing, photography, interactive media.
* Creative thinking skills.
* Knowledge of Graphic Design software and tools: 
+ Adobe InDesign.
+ CorelDRAW, QuarkXPress.
+ Adobe Illustrator.
+ Adobe Photoshop.
+ Adobe Dreamweaver.
+ Ability to work with programming scripts, including XML and HTML.
+ Understanding of the printing process and specifications.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
