### ISSUE TITLE
Fetch Technology Vietnam - iOS Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1302]
## Location
* Floor 3rd, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1700$.

## About job

Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. They are looking for a front-end developer who has experience in Swift development. You will be working with a team to build their OS front-end and also create service class to integrate with our enterprise message bus back-end system. You will have a chance to be part of a team to bring our app from MVP to production ready.

* 1+ years of Swift development experience.
* Understanding of OOP.
* Able to work in team and follow Git Flow.
* Experience in release iOS App.

*** Nice to have:
* Experience in releasing an iOS App to App Store.
* Experience in integrating with Restful API / Message bus.
* Understand MVVM and other design principles.
* Experience in writing unit testing. 

## Why it would be awesome to work with us:

* MacBook for working.
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
