### ISSUE TITLE
Fetch Technology Vietnam - Python Developer (Senior, Junior) - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1303]
## Location
* Floor 3rd, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1700$.

## About job
Our client is a social trading platform where we empower local communities to share their knowledge and make income from it. We are looking for a back-end developer who has experience in Python background. You will be working with a team to build back-end services cater to our mobile front-end. You will have a chance to be part of a team to bring our app from MVP to production ready.

* 1+ years of Python development experience.
* Understanding of OOP.
* Experience in using message bus framework.

*** Nice to have:
* Experience in Django and Flask.
* Experience in building/designing chat system.
* Have worked in a team who released production appbefore.
* Experience in designing technical solution that uses message bus like RabbitMQ, Solace.

## Why it would be awesome to work with us:

* MacBook for working. 
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
