### ISSUE TITLE
Tripath Vietnam Co., Ltd. - Back-end Developer - Hanoi - FT

### ISSUE THREAD

**Issue by Khang26** [awesome-jobs/vietnam#1314]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $2000/month

## Requirements
* Ruby
* Ruby on Rails
* HTML5

### Must Have

* Experience with designing RESTful WS
* Experience with relational DB (Postgres, MySQL, ...). Must be able to comprehend complex queries in SQL and understand the EXPLAIN query
* Experience with Git

### Ideally

* Experience with SPA stack (Angular, React + redux, VueJS) is a plus
* Experience with using Docker is an advantage 

### You’ll be responsible for

* Building educational management system with Rails
* Designing schema for relational DB with high flexibility (reusability, configurability)

### Why it would be awesome to work with us

* Attractive salary & bonus.
* 13th salary policy
* Full labor insurance (social, health, unemployed) and personal healthcare
* Daily various foods, drink, and seasonal fresh fruits;
* Promoting Opportunities
* Chance to work in Korea
* Young, dynamic, open, friendly working environment

### Vision

* To be proved as advanced software developer by government and well-known enterprises.
* To be valuable cross border commerce service provider between customers and resellers.

### Contact
Homepage: http://tripath.vn
Email: khang.trandang26@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
