### ISSUE TITLE
Perlin - Frontend Lead - Singapore/Remote - FT

### ISSUE THREAD

**Issue by iwasaki-kenta** [awesome-jobs/vietnam#1315]
## Location

* Singapore/Remote

## Salary Expectation

* USD$2500/month

### Must have

* 3+ years experience in front-end development and software engineering.
* Web frontend UI/UX design and development for technical web apps.
* Data visualization via. D3 or any other JavaScript library.
* Experience in TypeScript, React/Vue, and MobX.

### Responsibilities

We are looking for an experienced frontend developer with good taste in design and code style to be in charge of the open-source development and design of web applications for Perlin.

Apart from being an experienced frontend developer, you will be responsible for kickstarting/managing the web development team for Perlin and recommending any necessary changes of frontend/backend technology (example: suggest adding new API endpoints to backend) straight to the core development team.

### Why would it be awesome to work with us

Perlin has brought together new research from distributed systems, cryptography and database consensus to introduce an open, permissionless decentralized ledger benchmarked to yield 10k+ transaction/second. The ledger supports WebAssembly-driven smart contracts, a plugin system to extend ledger functionality, and supports running computationally heavy code in a decentralized, scaable manner.

In our mission of bringing the benefits of decentralization to software developers and businesses, we love and encourage open-source development.

You have the opportunity to be paid for working on technically challenging projects, and to have your work open-sourced to the masses.

By working with us, you will:
* Get to travel to various developer/blockchain conferences with the team.
* Get to enjoy corporate retreats with the team and other companies in various countries.
* Get to work either in one of our offices in New York/San Francisco/Hong Kong, or otherwise work entirely remotely.
* Be funded to develop and release technically-challenging open-source projects and libraries.
* Get to broaden your experience working with the entire tech. stack for a company.
* Get to experiment with new technologies with complete freedom.

### Interesting Engineering Projects

* Web app for sending/receiving cryptocurrency, and controlling a ledger node via. HTTP API interface.
* Web app for on-the-fly development and debugging of WebAssembly smart contracts.

### Contact

Homepage: https://perlin.net
Kenta: kenta@perlin.net

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
