### ISSUE TITLE
[First Alliances] - DevOps Engineer - HCMC - US Company

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#1317]
## Location

* District 1, HCMC, Vietnam

## Salary Expectation

* $2,000 - 2,500 USD Gross

## Requirements
* 3-5 years of experience in software development
* Solid programming skills in Python and Java (GO a great plus)
* Familiarity with existing open-source software packages and the DevOps toolchain
* Experience with Continuous Integration and Continuous Deployment
* A great support attitude (our job is to make life easier for other teams!)
* Be an analytical thinker with exceptional problem solving skills
* Able to work independently with minimal direction

## Skills

* Improving, monitoring and supporting our software infrastructure
* Developing software systems in Python (and Java or Scala if you have a background)
* Integrating best-of-breed tools and technologies such as Spark, Kafka, Zookeeper, Mesos, Docker, Elasticsearch
* Assembling platforms and frameworks to automate business processes
* Collaborating with internal technology, research and portfolio management teams

### Contact
Email: tran.ngo@fa.net.vn 
Skype: tran.ngoc.161

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
