### ISSUE TITLE
WhiteCloud - .Net or PHP Developer (Javascript, C#, .NET) - Saigon

### ISSUE THREAD

**Issue by tramanh25** [awesome-jobs/vietnam#1318]
## Location

* Saigon, Vietnam

## Salary Expectation

* $3000/month

## Requirements
* PHP
* .Net
* 2+ years Software Engineering experience

### Must Have

* Expertise with PHP, MySQL, Apache stack development.
* Strong knowledge of Microsoft Products.
* Strong front end knowledge; JavaScript, HTML, CSS (JQuery, AngularJS, Bootstrap).

### Ideally

* Experience with 

### Responsibilities
* We ask you to solve a business problem first, technical problem is secondary. You'll learn how your work matter and solve real life issues.
* Developing Windows and Web Application (Frontend, Backend, Desktop app), Web APIs systems, report output based systems.
* Responsible for the solutions to business logic challenges.
* Analyze system requirements and review specifications.
* Participate in creating solutions/estimations for high-level requirements.
* Participate in code review and optimization of system performance.
* Supporting the planning and testing features.
* Profiling and optimizing existing features.
* Proactively researching for bottlenecks and proposing your solutions.

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* Competitive salary with 13th month paid. Review salary one each year.
* Work in an international environment, young, supportive, innovative with great career growth potential.
* Social benefit: according to Vietnamese Labor Law. Accident insurance. Private Medical Insurance.
* Other allowances: parking fee; office supplies, such as noodle, milk, coffee, … to ensure employees’ health.
* Framework and technical training. Good English development environment. 
* Business training about Logistic and professional project developing management system.
* Overtime is rare and you will be paid for overtime hours.
* Professional environment and clear processes. Young, friendly, active and sociable colleagues.
* Time working: 09:00 AM - 06:00 PM from Monday to Friday.

### Contact
Email: tramanh019225@gmail.com
Title: WhiteCloud - PHP/.Net

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
