### ISSUE TITLE
Tek Experts - Solution Architect - HN - FT

### ISSUE THREAD

**Issue by Ericnguyen1** [awesome-jobs/vietnam#1319]
## Location
- Ba Dinh District, Hanoi City

## Salary Expectation

- Offer: Negotiable

## Requirements

- The Solution Architect should have expert level knowledge required to assist our team in architecting, planning, testing, and deploying solutions and their experience should include the following:
- The ideal candidate will have a degree relevant to Information Technology/Computer Science, Engineering (or equivalent) and at least 8 years of relevant work experience;
- Proven success and expertise in architecting innovative solutions both internally and externally;
- Ability to execute using standard architectural methods, processes, and tools;
- Proven experience estimating, scoping, and writing effective statements of work that clearly set expectations and limit risk for architecture;
- Demonstrated excellence facilitating company design & awareness sessions focused on complex application solution architectures;
- Deep technical knowledge in architecting solutions using Microsoft .Net;
- Deep knowledge of Cloud and Azure, ideally with experience in multiple sectors and industries;
- Demonstrated capabilities in developing an understanding of the customer business value associated with the deployment of modern business productivity, system-to-system, and end-user applications;
- Architectural understanding of and implementation experience with the following solution architecture areas: Modern Applications, Business Productivity including but not limited to portal and browser-based workflow  solutions, Application Architectures including the use of cloud-based technology capabilities such as Azure/SPO, Application Life Cycle Management and Application Platform processes and technology capabilities, Data and DB Management, SQL/BI, and application middleware and messaging architectures;
- Large enterprise deployment experience in complex heterogeneous environments;
- Ability to move between high-level architectural review/design and lower-level implementation by fully understanding the SDLC.
- Excellent communication and documentation skills.
- Excellent English language skills (both spoken and written);

## Skills
- .Net, Azure, SQL Server, Business Intelligence

### Responsibilities
The Solution Architect is expected to significantly impact and drive digital transformation by architecting and orchestrating solutions that map our current business requirements to end-to-end technology solutions. 

### You’ll be responsible for

- Drives and delivers strategy through leading technology decisions and proving expertise across multi domain solutions & offerings;
- Quantifies the needs of the business to achieve value outcomes, champions required methodology, captures/reuses IP and shares recommended practice;
- Drives delivery excellence ensuring quality transformation plans and solutions are delivered;
- Performs risk management and architectural oversight for cross domain solutions;
- Participates in opportunity development focused on complex solutions in line with company strategy.

### Why it would be awesome to work with us

- Competitive salary & performance bonus.
- Opportunities to work with the world’s leading IT companies.
- Summer trip, year-end party, team building activities.
- A collaborative and dynamic working environment.
- Flexible working schedule.

### Contact
Homepage: https://www.tek-experts.com/en-us/vietnam
Email: ericnguyen1159@gmail.com
Skype: ericnguyen1159
Title: TekExperts - SA

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
