### ISSUE TITLE
Envato - Ruby Dev - Remote/Melbourne - FT

### ISSUE THREAD

**Issue by joneslee85** [awesome-jobs/vietnam#132]
<img width="225" alt="screen shot 2015-12-14 at 10 23 00 pm" src="https://cloud.githubusercontent.com/assets/135605/11779752/476ca796-a2b1-11e5-9d23-4d93fd24945c.png">
![](https://igcdn-photos-a-a.akamaihd.net/hphotos-ak-frc/t51.2885-15/e15/10748165_373630152800800_630178802_n.jpg)

Xin chào Việt Nam!

We're continuing to grow our team and we're looking for great developers who would love the opportunity to work at Australia's premier Ruby development company. We're calling out to developers with deep commercial Ruby experience who have built high traffic applications and like working in cross-functional teams. If you have solid commercial experience and only a small amount of experience with Ruby, however would love to continue growing and have a passion for Ruby and RoR, then we'd also love to hear from you.

Envato is loved by our customers and our sites receive an extremely high amount of traffic - larger than most websites in Australia.  In September 2014, one of our sites, [ThemeForest](https://boards.greenhouse.io/envato/jobs/themeforest.net), was the 90th most visited website in the world and it is currently the most visited Australian-owned website on the planet! We have over 250 staff globally, and have paid out more than [$300 million](http://press.envato.com/109048-envato-pays-over-300-million-to-creative-community) to our community of creative sellers. If you're interested, we'd love to give you a role in our company that strives for technical excellence, is relaxed, humane and lets you make decisions.

All applicants will be considered for all open engineering roles across the Envato ecosystem of sites (Market, Tuts+, Studio, etc.)
## Location
- Melbourne, Australia (VISA Sponsorship) OR
- Remote (Wherever you like)
## Expectation

At Envato, our Engineers expect certain things of each other. Not all of these are easy to uphold. Are you ready to join the team and meet the expectations of your peers at Envato? Read about the [expectations](http://webuild.envato.com/expectations/) and how they were developed by our team on our [technical blog](http://webuild.envato.com/blog/how-envato-defined-the-expectations-of-our-developers/). 
## What you'll be doing
- Writing clean, maintainable, reliable code that is well tested
- Leading the delivery of mid to large scale projects by cross-functional teams
- Creating high level software designs that solve complex technical problems  
- We don't have testers, so you'll be responsible for ensuring your code works in production
- We don't have sysadmins, so you'll be responsible for deploying to production and being first line operational support 
## Essential Requirements
- Be a nice person
- Communicate well in person and in writing
- Be a curious person committed to continual learning
- Be capable of writing clean, well thought out, and reliable code
- Be able to follow a project through from the original fuzzy brief through development and deployment and beyond with minimal oversight required
- Be comfortable in a Linux software development and deployment environment
## Preferred Requirements
- Have commercial Ruby on Rails experience
- Have solid TDD/BDD experience
- Have experience of other high volume/scale web apps
- Contribute to Open Source projects
- Past experience in other agile environments
- Excellent linux knowledge
### A Great Team and Culture
- Developers are responsible for features from inception through to them being in the hands of customers. The devs talk directly to customers about what they're working on
- We do continuous delivery properly: any team member can deploy, and we regularly do several deploys a day
- We publish portions of our code as open source, and contribute back to open source projects we use
- We were recently named Australia's Coolest Tech Company by JobAdvisor and one of the Best Places to Work in Australia
- A fantastic culture of creatively minded, hard working people who are passionate about Envato and being part of its growth and success
- Flexible working conditions – we want you to love your work but also your life outside of Envato
- We actively work on creating a safe, inclusive environment free from discrimination
- In addition to hiring for our Melbourne CBD office, we will also consider applications from experienced Ruby Developers who would like to work remotely (Australia wide)
- Future career progression will be available across the entire business - we're big on internal opportunities and professional growth!
## Who should apply?

We care deeply about diversity at Envato, and welcome applicants of all types, and from all backgrounds. If you think you have the skills and experience needed for this role then we'd like to hear from you.

Please apply at http://grnh.se/moqr8f
## Contact

Mr. Trung Lê: trung_dot_le_at_envato_dot_com

**Comment by doradken** [comment]
Mr. Trung Lê: trung_dot_le_at_envato_dot_com = trung.le@envato.com . Need to use brain's notron  to send mail :D

**Comment by huydx** [comment]
@doradken we use this syntax to prevent spam from some crawling bot, so please remove your comment, tks ;)

**Comment by doradken** [comment]
Hi,

Sorry for my kidding , :D 
I removed.


=========================
Thanks & Best Regards


Ngo Minh Nghia

Fone : 0127 818 7939
YM: nghiaapfx@yahoo.com
Skype: nghiaapfx
============================

--------------------------------------------
On Tue, 12/15/15, Φφ <notifications@github.com> wrote:

 Subject: Re: [job_board] Envato - Senior Ruby Dev - Remote/Melbourne - FT (#132)
 To: "ruby-vietnam/job_board" <job_board@noreply.github.com>
 Cc: "doradken" <nghiaapfx@yahoo.com>
 Date: Tuesday, December 15, 2015, 12:22 PM
 
 @doradken we use this
 syntax to prevent spam from some crawling bot, so please
 remove your comment, tks ;)
 
 —
 Reply to this email directly or view
 it on GitHub.
