### ISSUE TITLE
TicketSoft Co., Ltd - BACK-END DEVELOPER (PHP, NodeJS) - HCM - FT

### ISSUE THREAD

**Issue by tran196dat** [awesome-jobs/vietnam#1321]
## Location

* First Floor, H3 Building, 384 Hoang Dieu Str., Ward 6, Four Dist., HCMC, VN.

## Salary Expectation

* $800 - $1,500/ month

## Requirements
* PHP
* NodeJs
* 1-3 years of professional experience in web application development

### Must Have

* Experienced in NodeJS, PHP, ElasticSearch, MySQL, REST web services, GIT
* Familiar with microservices, front-end technologies (ReactJS, Angular), non-functional aspects (security and scalability) is a plus
* Good writing and reading English

### Ideally

* Write clean code and improve the readability of a codebase.
* Research new technologies, apply and train other team members
* Perform code review, code refactor

### Responsibilities

* We are seeking experienced, results-driven, and passionate developers to join our giig.asia team. Our ideal candidate is a self-starter and has excellent communication skills. 
* Our collaborative environment relies heavily on innovation, technical savvy, and problem-solving skills.
* This position will play a primary role in delivering high-quality products to our customers and bringing our development team to a higher level.

### Why it would be awesome to work with us
* 13th salary policy.
* Free parking, and event tickets
* Full labor insurance (social, health, unemployed) and personal healthcare
* Free in-house entertainment facilities (foosball), drinks and snacks...
* Annual leave 12 days
* An optimized management system that helps you feel comfortable at work
* Company trip, team-building
* Young, dynamic, open, friendly working environment
* Join our clubs: badminton, table tennis, ...
* Participate in workshops held in HCMC

### Contact
Homepage:  https://www.giig.asia/
Email: Tran196dat@gmail.com
Subject: [TicketSoft - Back-end - Your name]

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
