### ISSUE TITLE
Machine Learning Engineer - HCMC/Singapore/Remote - Quod AI

### ISSUE THREAD

**Issue by hroussel** [awesome-jobs/vietnam#1324]
## Location

* HCMC, Singapore
* Remote

## Salary Expectation

* $2000/month 

## Requirements

* Java or Python
* 2+ years Software Engineering experience

### Must Have

* Outstanding programming skills

### Ideally

* Experience with NLP a plus

### Responsibilities

* Work closely with our software architect and data scientist to develop and maintain our core product.
* Develop highly scalable code that leverages ML, natural language processing and rules based models that integrates into our data pipeline.
* Adapt and deploy ML/AI models (Java or Python, Elasticsearch, Redis, Apache Beam).
* Evaluate and improve ML/AI models (Python, Tensorflow, Jupyter notebook).

### You can bring

* Ability to learn quickly
* Ability to get things done

### Why it would be awesome to work with us

Quod AI is a young and exciting AI/NLP start-up with an unmatched team of engineers and scientists. We’re applying Deep Learning and NLP on source code  to empower software engineering teams to build products faster and better. We are funded and backed by Entrepreneur First and SGInnovate.

![Team](https://s3-ap-southeast-1.amazonaws.com/quod.ai/IMG_4751_xs.jpg "Team")

Our [CEO](https://www.linkedin.com/in/hroussel/) is a well recognized thought leader and speaker on AI and Software Engineering. He is an ex Silicon Valley CTO with 10+ years of experience in the US. He is also an advisor and mentor for organizations such as the IBM AI XPRIZE, PlatoHQ (YC’16), RMIT, AngelHack and more.
Our [Chief Scientist](https://www.linkedin.com/in/mikhfilippov/) is an is an award winning mathematical physicist. He is an expert at modeling complex systems (weather, neurobiological systems, real estate and more). His research background has led him to create AI & NLP models for prestigious institutions like UCL, NTU Complexity Institute & Polytechnique Paris and used by world renowned organizations like NASA & MAS.

### Contact
Homepage: quod.ai

**==> Click [here](http://bit.ly/2OL3YtA) to apply <==**

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
