### ISSUE TITLE
[Rockship] - Backend Developer (NodeJS/Python/Golang) - HCM - Fulltime 

### ISSUE THREAD

**Issue by ThanhHien0804** [awesome-jobs/vietnam#1325]
## ABOUT US:
Rockship specialises in software development: Live- Streaming, Real-time and
BlockChain technology. We offers software development partnership with founders of tech startup to build the product. Rockship aims to be excellent at product development & engineering by applying
best software development framework and practices.
Visit our website: www.rockship.co to learn more about working for Rockship.
## WE EXPECT FROM YOU:
* Willing to work with new technologies in big and challenge projects
* +1 year experience with programming languages like NodeJS, Golang or Python (We’re open any language)
* Participate in the entire application lifecycle, focusing on coding
* Write clean code to develop functional web applications
* Optimization of the application for maximum speed, scalability and re-
usability
* Ability to find solutions to the new challenges daily
* Always have a willing to learn and can-do attitude
## WHAT YOU WILL BE RESPONSIBLE FOR:
* Build efficient, testable, scalable, and reusable modules
* Solve complex performance problems and architectural challenges
* Not only be cooperative and friendly, but also proactive and responsible and great believer of teamwork
* For Senior Engineering Positions:
Play a lead role either in terms of technical development and architecture, or in terms of team   management
Mentor and nurture engineers

## WHY WOULD YOU WANT TO JOIN WITH US:
* Attractive salary
* 13th-month salary yearly
* Annual salary reviews based on performance and contribution 2 times per year
* 15 days leave per year
* Young and dynamic environment combined with supportive, fun and flexible work environment that values innovation, creativity and new ideas
* Free snacks and coffee (Gym, Swimming Pool, BBQ, etc)
* Annual company trip

### CONTACT
Email: Hien@rockship.co 
Skype: thanhhien1484

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
