### ISSUE TITLE
[Rockship] - Frontend Developer (ReactJS/VueJS) - HCM - FT 

### ISSUE THREAD

**Issue by ThanhHien0804** [awesome-jobs/vietnam#1326]
## ABOUT US:
Rockship specialises in software development: Live- Streaming, Real-time and BlockChain technology. We offers software development partnership with founders of tech startup to build the product.
Rockship aims to be excellent at product development & engineering by applying best software development framework and practices.
Visit our website: www.rockship.co to learn more about working for Rockship.

## WE EXPECT FROM YOU:
* +2 years experience
* Expert in HTML, CSS and JavaScript
* Thoroughout understanding of ReactJS/VueJS
* Ability to translate mockups into seamless web pages with perfect visual
and functional elements
* Ability to find solutions to the new challenges daily
* Always have a willing to learn and can-do attitude

## WHAT YOU WILL BE RESPONSIBLE FOR:
* Build web applications. Follow coding standards
* Translate designs and style guides provided by the UI/UX team into high
performance functional user interfaces
* Contribute to continual improvement by suggesting new and emerging
front-end technologies
* Recommend appropriate technologies to implement new features

## WHY WOULD YOU WANT TO JOIN WITH US:
* Attractive salary
* 13th-month salary yearly
* Annual salary reviews based on performance and contribution 2 times per year
* 15 days leave per year
* Young and dynamic environment combined with supportive, fun and flexible work environment that values innovation, creativity and new ideas
* Free snacks and coffee (Gym, Swimming Pool, BBQ, etc)
* Annual company trip

### CONTACT
Email: Hien@rockship.co 
Skype: thanhhien1484

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
