### ISSUE TITLE
[Rockship] - iOS Developer (Swift) - HCM - FT

### ISSUE THREAD

**Issue by ThanhHien0804** [awesome-jobs/vietnam#1327]
## ABOUT US:
Rockship specialises in software development: Live- Streaming, Real-time and BlockChain technology. We offers software development partnership with founders of tech startup to build the product.
Rockship aims to be excellent at product development & engineering by applying best software development framework and practices.
Visit our website: www.rockship.co to learn more about working for Rockship.
## WE EXPECT FROM YOU:
* +2 years experience in iOS developement
* Have published one or more iOS apps in the app store
* Strong experience with Swift
* Working knowledge of the general mobile landscape, architectures, trends
* Help maintain code quality, organization, and automatization.
* Ability to find solutions to the new challenges daily
* Always have a willing to learn and can-do attitude
## WHAT YOU WILL BE RESPONSIBLE FOR:
* Design and build advanced applications on iOS
* Ensure the performance, quality, and responsiveness of applications
* Collaborate with a team to define, design, and ship new features
* Identify and correct bottlenecks
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency
* For Senior Engineering Positions: Supervise and support other junior developers in fulfilling tasks as well as improving their skills

## WHY WOULD YOU WANT TO JOIN WITH US:
* Attractive salary
* 13th-month salary yearly
* Annual salary reviews based on performance and contribution 2 times per year
* 15 days leave per year
* Young and dynamic environment combined with supportive, fun and flexible work environment that values innovation, creativity and new ideas
* Free snacks and coffee (Gym, Swimming Pool, BBQ, etc)
* Annual company trip

### CONTACT
Email: Hien@rockship.co
Skype: thanhhien1484

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
