### ISSUE TITLE
Nexus Frontier Tech - Technical Consultant (Front-end, Back-end) - Hanoi - FT

### ISSUE THREAD

**Issue by tranvquoc** [awesome-jobs/vietnam#1328]
## Address

*  35 Le Van Luong, Hanoi, Vietnam

## Salary

* From $1500/month to infinity and beyond

## Requirements

* At least 4 year of hands-on software development experience, both front-end and back-end languages
* At least 1 year experience as team lead

### You may also need

* Understanding of the entire web development process, with an emphasis on front-end design and development
* Strong communication skills to effectively collaborate with developers, and other relevant staff members or clients

## You’ll be responsible for

* Manage 3-5 projects from Sales closure to Customer Success
* Lead company-wide technology asset creations (library, common modules, etc)
* Communicate with Developers, Project Managers and QC Leader to make sure Developers involved in Quality process
* Further details will be discussed in the interview

## Why it would be awesome to work with us

* Offer from $1,500 salary based on your experience, capacity & negotiable
* 13-month salary and monthly financial support policies; English class (in case), monthly club activities
* Be exposed to the latest technology and the most innovative ideas worldwide
* Salary review: twice per year
* Yearly events: team building activities, Year-end party, Christmas, etc
* Flexible working time schedule and leave policy as we know the importance of work-life balance
* And many more waiting for you to discover

## Send your CV to or contact me via

Email: vinh.t.quoc21@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
