### ISSUE TITLE
Tripath Vietnam Co., Ltd. - Junior/Senior iOS Developer - Hanoi - FT

### ISSUE THREAD

**Issue by vinhle7859** [awesome-jobs/vietnam#1329]
![tripath_topdev_3](https://user-images.githubusercontent.com/44989679/48387959-55449200-e72a-11e8-92a9-d0dcdf2f31a6.jpg)

## Location

* De La Thanh, Dong Da District, Hanoi

## Salary Expectation

* Up to $1,200 / Months

## Requirements
* iOS 
* Swift 
* Objective - C

### Junior-level
* Using Swift is a must
* At least 1 year or 1 production project in experience.
* Know how to use Git.
* Managing third party libraries with CocoaPods

### Senior-level
* Follow best practice conventions and project structure
* Reading blogs and compelling ideas how to improve our skills.
* Know how to handle the entire software development life cycle, end to end.
* Extensive socket, threading, data stream and apps profiling experience
* Objective-C++ experience
### Ideally

* Experience with Swift

### You’ll be responsible for

* Develop applications on iOS stack for Korean clients
* Take regular business and training trips to Korea
* Evaluate colleague source code

### Why it would be awesome to work with us
* Attractive salary ($700 - $1,200)  & bonus + 13th salary policy
* Full labor insurance (social, health, unemployed) and personal healthcare
* Daily various foods, drink, and seasonal fresh fruits;
* Promoting Opportunities
* Chance to work in Korea
* Young, dynamic, open, friendly working environment

### Contact
Job Description: https://bit.ly/2zKdIPs
Apply CV via: huyvinh785@gmail.com with title Tripath - iOS - Your Name

**Comment by qcam** [comment]
@vinhle7859 thanks for posting but we do not accept jobs from recruiting agency.
