### ISSUE TITLE
Envato - Frontend Developer - Remote (Australia wide) / Melbourne, Australia (VISA Sponsor) - FT

### ISSUE THREAD

**Issue by joneslee85** [awesome-jobs/vietnam#133]
Xin chào!

Join our thriving global, online business, in our Melbourne CBD HQ
- Constant encouragement to improve your craft; career progression opportunities
- Recently named Australia’s Coolest Tech Company!

Headquartered in Melbourne, Australia, we're a completely online company with an ecosystem of sites and services to help people get creative. In September 2014, one of our sites, ThemeForest, was the 90th most visited website in the world. We have over 250 staff globally, and have paid out more than $224 million to our community of creative sellers.

Our sites include Envato Market (http://market.envato.com), the leading marketplace for themes, project files, images, and creative assets; Envato Studio (http://studio.envato.com), where clients connect with handpicked freelance talent; and Tuts+ (http://tutsplus.com), where we offer thousands of tutorials and video courses on creative and digital topics.

In this role you’ll have access to Envato wide career progression opportunities.
## The Role

As a Front-End Developer, you’ll work as a member of a close-knit, agile product team, whilst undertaking extensive hands-on front-end web development work. You will have the opportunity to mentor team members with less experience and will collaborate with other developers, designers and stakeholders to deliver an exceptional front-end user experience for Envato web applications.

We value shipping code on a regular basis (we typically deploy 5+ times a day), so you must be comfortable with short-cycles between the development of your code and it being used by millions of people a day (our sites generate around 5 million pageviews a day). We're iterating fast on a very successful, global web application whose primary audience is design-focussed digital professionals, so your work will come under the microscope!

To be successful in this role, you must be comfortable working in an agile team, moving fast and incrementally to improve our product in our collaborative, people focused organisation whilst living and breathing [Envato’s Values](http://webuild.envato.com/expectations/).
## What we’re looking for

You must have extensive experience in front-end development roles and possess expert knowledge of HTML, CSS, JavaScript and have experience with build systems for front-end applications. It would be great if you have solid Git Fu, can Test Drive your JS development and have an eye for great design, including managing style-guides and their evolution.

As a bonus, we’d love experience with SASS/Compass/ReactJS, ES5/6/CoffeeScript, SMACSS/BEM, Progressive Enhancement, Responsive Design, Node.js and microservices built in Node.js (not essential). Experience with ecommerce, online communities, search and web frameworks such as Ruby on Rails are also highly desirable, along with exposure to AWS.
## What we offer
- A fantastic culture of creatively minded, hard working people who are passionate about Envato and being part of its growth and success
- Flexible working conditions – we want you to love your work but also your life outside of Envato
- We actively work on creating a safe, inclusive environment free from discrimination
- A fast paced and progressive environment where everyone has regular interaction with teammates and
  Envato community members from all over the world!
- Read more from our staff about why they love working at Envato by visiting www.envato.com/careers/top-5
  and www.jobadvisor.com.au/envato
## Who should apply?

We care deeply about diversity at Envato, and welcome applicants of all types, and from all backgrounds. If you think you have the skills and experience needed for this role then we'd like to hear from you. This role is only open to people who wish to be based at our Melbourne CBD head office; we will not consider remote workers for this position although we will offer flexible hours and work from home days.
## How to Apply

To apply please submit a cover letter to jobs@envato.com with the subject line “I’m your ideal Front-End Developer because...” along with a current copy of your resume.
In your email application, please answer following questions:
- Are you eligible to work in Australia? If no, please specify visa requirements.
- How many years experience do you have in a similar role?
- Do you have a relevant degree or tertiary qualification?
- When are you available to start?
- What is your expected annual salary?
- Tell us about your most successful project and include a link if available.

**Comment by joneslee85** [comment]
up hộ cái nào

**Comment by tucq88** [comment]
job vẫn open chứ anh @joneslee85  ?

**Comment by joneslee85** [comment]
@tucq88 yes
