### ISSUE TITLE
PIXTA VIETNAM - Senior Web Developer - Hanoi - FT

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#1330]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 20m - 40m/month (+ 1 month bonus if joining in 2018)

### You’ll be responsible for

* Develop product: Snapmart (https://snapmart.jp/)
* Cooperate with Japan team to take control of all technical issues

## You can bring
* Good web development skills set
* English proficiency at working level

## We appreciate if you could
* Use Ruby on Rails
* Use AWS as S3, Sqs, rds, elastic search
* Code swift 3 or Object c (*use for ios) is advantage
* Have logic thinking to solve payment bugs
* Have experience working with payment method 

### Why it would be awesome to work with us
* Good salary: 20m - 45m
* Receive 1 month salary bonus if on board in 2018
* Be equipped with Laptop, screen, mouse... 
* Activities: Company trip, Company dinner, picnic, Birthday party, Happy Hour, Table tennis club, photography club... 
* 12 days off/year, Premium Health Care Insurance...

### Contact
Email: recruit.vn@pixta.co.jp
Fanpage: Pixta Vietnam (https://www.facebook.com/pixtaVN/)
Recruiter: Van Pham (https://www.facebook.com/vanpham289)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
