### ISSUE TITLE
HVN - Senior Front End (React Native) - Remote - FT 

### ISSUE THREAD

**Issue by TrangNgTh** [awesome-jobs/vietnam#1331]
## Location
* Vietnam
* Remote

## Salary Expectation
* $1700/month **GROSS**

## Description
* Project is first personal finance app powered by bank-level security based in Hong Kong. Our application is a simple, safe, smart way to save - mobile banking has never been so rewarding.
## Skills
- React and/or React Native
- JavaScript
- Cloud based services (AWS) or HTTP API
- 2+ years experience in software development

## Requirements

* Education Level (pursuing / obtained) : Bachelor's degree and above preferred
* Required Level of Work Experience : 2-6 years experience in software development
* Show us how you love communications and technology, working and playing as a team, solving problems, and managing projects.

### This position will require you to:

* Work closely with UX/UI designers to implement the best user experience for our users.
* Have enthusiasm for Agile project management methodologies.
* Use your communication skills, we expect you to become an expert in one area of your choosing and be able to voice your ideas and concerns.
* Own one or more components of the App software stack, from design to implementation to monitoring and operations.
* Be a team player and willing to learn and mentor fellow engineers.

## We can bring
* A Guarantee Remote Contract
* Heath Insurance Package.
* Performance Bonus,13th Salary
* Eligible travel to Hong Kong.

## Contact
Ms. Trang Nguyen
Email: trang.nguyenthu3@harveynash.vn
Skype: hilly.chan

**Comment by qcam** [comment]
@TrangNgTh Thanks for posting but we would need more input about the position and the company. Also is this position in-house for Harvey Nash?

The post will remain closed until the questions are addressed.

**Comment by TrangNgTh** [comment]
@qcam Yes, It is our in-house project. But you can close this post cause our project is filled.
