### ISSUE TITLE
TOPICA - PHP Developer - HN - FT

### ISSUE THREAD

**Issue by DuongLe11** [awesome-jobs/vietnam#1334]
## Location

* 75 Phuong Mai St, Dong Da Dist., Ha Noi, Vietnam

## Salary Expectation

* $1,000 - $2,000/month 

## Requirements
* At least 3 years experience with PHP/ JavaScript
* Have experience in framework such as CakePHP/ Laravel/ Magento/ CodeIgnitor 

## Skills
PHP/ JavaScript

### You’ll be responsible for
* Participate in the development of large software systems.
* Develop product/ new modules work stably according to the existing design.
* Responsible for product quality and code quality.
* Adheres to the Agile development process, Scrum.
* Code enthusiasts, trainers, tutors or techleaders to other team members are a plus.

### Why it would be awesome to work with us
* Competitve salary, up to $2,000/ month
* Performance review 4 times/ year
* Onsite opportunity
* Dynamic and creative working environment

### Contact
Email: duong.le0217@gmail.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
