### ISSUE TITLE
1PAC Vietnam - Technical Leader - HCM - FT

### ISSUE THREAD

**Issue by thaobee** [awesome-jobs/vietnam#1335]
## Location

* District 1, Ho Chi Minh City, Vietnam
* Our website: http://1pac.vn 
* Our fanpage: https://www.facebook.com/1pacvietnam/

## Salary Expectation

* $1000-$1800

## Requirements

* 2 years working with Ruby and Ruby on Rails framework

### Must Have

* Having knowledge of TDD/BDD and writing test with RSpec
* Good understanding of object oriented programming and design patterns
* Able to design database and system
* Experienced with RDBMS Postgres/MySQL and In-memory db Redis/Memcache
* Experienced with JavaScript, HTML/CSS/SASS
* Understanding CI/CD process and apply it in development
* Experienced with infrastructure such as AWS, Heroku
* Good knowledge of Git

### Ideally

* We also do PHP projects, so it's nice if you can also do PHP. Mostly we use Laravel and Wordpress
* Frontend: ES6/VueJS/Gulp/Webpack
* Github account with public projects

### Your job

* Manage and assign tasks to other members
* Gather and analyze requirements from client
* Ability to train and help fresh/junior members to improve skill
* Participate in outsource projects from big companies in Japan
* Work on all phases of project development (designing, implementation, delivery)
* Research trending technologies and apply it to real production
* Be keen on refactoring code and delivering products with high quality
* Participate in R&D project to build company's own application

### Why it would be awesome to work with us

* Personal Macbook Pro provided
* We use some of the coolest application and service: Github, Slack, AWS, Sketch, Zeplin 
* Review salary 2 times/year
* Business trip in Japan
* Company trip 1-2 times/year
* Team-building activities (dinner party, watch movie, movie, soccer, bowling…)
* Others benefits such as holidays and insurance benefits follow Vietnamese law.

### Interesting engineering projects

* Attendance management web/ application using RoR and React Native
* A media site for foreigners who are interested in Japan or currently living in Japan using RoR

### Contact
Person in charge: Ms.Thao
Email: redstar.thao@1pac.vn
Phone: 090-2816-440

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
