### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Senior Java Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1343]
## Location
* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.
* 3rd Floor, Dai Phat Building – Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 3000$.

## Job Description
Our client is building an all-in-one application for personal finance combining a multi-currency wallet, globally accepted payment card, and a financial services marketplace. They are on a mission to make money simple - they believe everyone, everywhere should have the power to easily manage their own finances. 
After a highly successful token sale, they are rapidly expanding their team to create the future of finance. Each of their engineering team takes full responsibility of the product quality and every line of code they ship. This means writing automated tests to ensure your code works correctly, doing real time production monitoring and fixing any issues that come up. 
There is no manual QA - if CI is green code in master is automatically deployed to production. Today they have 6 engineers with a never-ending passion towards technology, product, and user experience. By the end of next year,they are expecting to grow at least 7x - this is your chance to be on board early and create the future yourself.
* The full-stack developer will help to build the next generation of financial applications. The goal is to provide the best experience to their users and they are excited to dive into any area of the web stack to make it happen.
* You rarely have a typical day: One day you might be writing front-end code and another you might be discussing the best approach making their web apps work in our service-oriented architecture.

## Requirements

* Fluency in Java (or Kotlin) - we use Spring Boot.
* Strong understanding of OOP and Clean Code.
* Experience with reactive UI development using React or similar, experience with Flutter is a plus.
* Experience with relational databases, SQL and schema design.
* A fan of writing unit tests and TDD.
* Understanding of RESTful APIs.
* Customer focus - you believe that talking to customers is essential to figure out what to build next.
* Knowledge of the Lean Startup principles (MVP, Build Measure-Learn).
* Ability to work independently and deliver your own solutions to problems.

Nice to have:
* Experience with Devops - setting up infrastructure (AWS)& CI.
* Knowledge of payment platforms, crypto & blockchain.
* Understanding of Agile principles, Scrum/Kanban.
* Experience in distributed and concurrent systems,knowing the trade offs between stateful/stateless and synchronous/asynchronous architectures.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
