### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Front-end Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1344]
## Location
* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1500$.

## About job

Our client is a Rakuten-funded start-up redefining the corporates erviced apartment business. It is Asia’s leading platform for quality and affordable corporate serviced apartments – Airbnb for Business Travellers. 
Instead of tourist, its customers are large corporation where it provides a guaranteed apartment experience at a fraction of branded serviced apartment’s prices. It maintains a high quality of experience by providing asset owners a simple turnkey professional property management services. It is humbled to have Rakuten and 500 Startups as its lead investors who have collectively funded USD$3.5 million.
* Building, testing, debugging, troubleshooting, producing clean and compliant code along with working with server-side engineers to integrate it all into a final product.
* As a key member of the team, you will be working closely together with UX designers and the back-end team to bring our products to life.
* The team looks after a wide range of in-house developed products. So you’ll be responsible not only for building the website for our customers but helping to build and develop our custom built CMS and integrations with 3rd party systems that the company uses every day.

##Requirements

* Have at least 3-5 years of experience in developing web applications.
* At least 1 year experience using React, and Redux. Knowledge of other front-end frameworks is a plus.
* Solid understanding of web concepts and up to date with latest web technologies.
* Knowledge of RWD principles.
* Keen to standards and best practices, load-time reduction and accessibility features.
* Experience with source/version control system. Knowledge of GIT flow is plus.
* Experience working in a team and participating in peer review.
* Familiarity with testing frameworks and tools and writing own test.
* Decent English skills is a must.
* Knowledge of SEO is plus.
* Excellent problem solving skills.
* Proactive and willing to learn.

## Why it would be awesome to work with us:

* MacBook for working.
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
