### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Mobile Developer (Android/iOS) - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1345]
## Location
* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.
* 3rd Floor, Dai Phat Building – Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* from 1300$.

## Job Description

Our client project is a global payments online which was backed by a team of investors from Decent Capital. It was founded with one mission in mind: to make financial services fairer, faster and more accessible to the world. 
By circumventing traditional payment channels and building a network of partnerships with financial institutions, they are able to deliver cost efficient, faster and better payment experiences. It is a one-stop solution designed to help customers take charge of the business’s payments and manage treasury in a cost-effective and seamless manner. 
As an engineer, you do not just hide behind screens and mindlessly push code without examining the impact of their own work. They are looking for passionate software engineers who take pride and ownership in their work.You will translate their wire frames and mock-ups into code and integrating their core APIs to provide the best user experience for our customers. 
The best part? You will not be writing lines of code in a silo by yourself. They work across departments to understand various facets of the business in order to prioritise user stories and suggest appropriate technology choices to deliver the sprints.

* Develop client-centric features in either Android or iOS platform.
* Build, support and maintain high quality, maintainable mobile native apps.
* Work closely with product management and experience design team to define and refine feature specifications.
* Analyzing and improve the efficiency, scalability and stability of our mobile applications.

## Requirements

* Bachelor Degree (or above) in Computer Science or equivalent.
* At least 3 years of experience in mobile development.
* Strong foundation in computer science with a deep understanding of data structures and algorithms.
* Experience in mobile device provisioning, deployment, and account management.
* Understanding of application architecture and object-oriented design, specifically in the mobile world.
* Mastery in professional software engineering practices for the full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations.

Attitude
* Resonate with the mission to make financial services fairer,faster and more accessible to the world.
* Inquisitive with an analytical mind to understand the various facets of developing a product, from technical requirements to business decisions.
* Driven and proactive in exploring creative solutions to solve challenging problems.
* Empathetic with the customers' pain points and base your decisions upon solving their problems.
* Unafraid to challenge the team if you feel something can be done in a better way.
* Communicative, fun and open-minded to work together with.

Nice to have:
* Practical experience in Scrum and Agile methodologies.
* Experience in building automated test cases for mobile application (i.e Unit testing, integration testing).
* Have previous experience in startups, especially in the FinTech domain.
* Actively contribute back to the community through opensource repositories, blogging and public speaking.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
