### ISSUE TITLE
KAMEREO - Senior Back End Developer - HCM - FT

### ISSUE THREAD

**Issue by TakuVietnam** [awesome-jobs/vietnam#1346]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2500-3500/month

## Requirements

* Highly motivated to have an impact by solving problems faced by our users
* Has a strong sense of ownership take pride in what you’ve built
* Has at least 4 years of good experiences as backend engineer
* Has at least 2 years of experienced with Java
* Has at least 2 years of developing and maintaining large system
* Has strong architecture & software design skills: OOP, SOLID, Code smells, Refactoring, and what not.
* Familiar with Test Driven Development, Continuous Integration
* Has superb logical skills
* Is a great communicator with strong written and verbal English skills.

## Skills

* Java (Backend services)
* Spring Framework
* gRPC
* Javascript 
* NodeJS, GraphQL, gRPC (API server)
* ReactJS
* Elasticsearch
* MongoDB
* RDS
* Redis
* AWS

### Ideally

* Has experienced with NodeJS
* Familiar with AWS, DevOps, Infrastructure as Code

### You’ll be responsible for

* Design and build scalable APIs for the KAMEREO platform across multiple microservices
* Write clean, well-structured and tested code, fast!
* Troubleshooting/fixing problems
* Discuss/design a new service/system architecture

### Why it would be awesome to work with us

* 2 months probation period(full salary)
* 13 month bonus
* Salary review once a year (Salary change from Jan every year)
* Annual Leave is 12 days/year after probation period
* Chance to connect with many F&B owners, join F&B events and so on
* Chance to have team lunch/dinner at our client restaurants

### Contact

* Homepage: http://www.kamereo.vn
* Taku : info@kamereo.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
