### ISSUE TITLE
NFQ Asia – Ruby On Rails – HCM – FT

### ISSUE THREAD

**Issue by trucvo26** [awesome-jobs/vietnam#1347]
## Location

* NFQ Asia Office: 11 Floor, Vincom Center Building (45 Ly Tu Trong st or 72 Le Thanh Ton st, Dist 1, HCM
* Fulltime

## Salary Expectation

* Up to $2000

## Requirements
* +2 years of experience with Ruby on Rails, along with other common libraries such as Sidekiq, Grape, RPush, RailsAdmin, Cells, Sinatra.
* +2 years of experience with full web stack including HTTP, CSS, REST, JWT Token Authentication...
* Good database experience in any of these areas: PostgreSQL or other SQL database server etc
* Testing with Rspec, FactoryGirl and Faker
* Good knowledge on server side development with good performance, distributed system, understand well good design pattern and architecture principles
* Good English Communication skills.

- Big Bonus
* Experience in unit test, integration test, automated test, CI/CD on the cloud Amazon/Azure/Google.
* Writing Documentation & API Specification are plus, such as Swagger, OpenApi.
* Experience with Ruby Metaprogramming & Hacking
* Experience with WebSockets / ActionCable

### Responsibilities
* You will be joining an awesome startup team to build cool applications that serve millions of users, from idea to production.
* As our customers are typically ambitious foreign startups, you will have a chance to improve your English, learn about startup culture and product mindset along the way. If you want to make a great impact on the world, this is your chance now.
* Managing full lifecycle customer projects with Agile methods.
* Developing strong relationships with customers, acting as the primary point of contact as well as managing stakeholder expectations and always seek for solution improvement.
- Perks
* Macbook Pro
* Loyalty bonus scheme (up to $48,000)
* Work onsite - overseas

If you are awesome, dedicated, love to work and learn from a bunch of successful entrepreneurs then we are searching for you!

### Why it would be awesome to work with us

- Tech Rockstar : Apply the latest technology
- Fun-Friendly-Flexible : Professional & English speaking working environment
- Exciting Projects : Working with overseas clients and awesome projects.
- Growing Opportunity : Work with top-notch experts from around the world.

Benefits include:
- MacBook Pro is provided.
- A fun & dynamic environment and freedom to be creative.
- Rock in open-mind, kind & humble band.
- Modern office with the flexible relaxing zone.
- Company trip, team building & other community Tech activities.
- Year-end bonus, Loyalty bonus (up to 48,000$).
- Performance review  2 times/ year.
- Extra Medical Insurance.
- 15 days annual leaves, working Monday – Friday.

### Contact
Homepage: https://www.nfq.asia/
Email: career@nfq.asia
Skype: trucvo26

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
