### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Mobile Developer (Android/iOS) 2 - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1350]
## Location
* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.
* 3rd Floor, Dai Phat Building – Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* from 2000$ and commensurate with experience.

## Job Description

Our client is an artificial intelligence company that focuses in visual recognition - Video and Image recognition. The aim is to transform the way offline content is being consumed by bridging O2O (offline to online) media properties with its latest cutting edge Carrot Visual Technology where various platforms and channels can be integrated, allowing seamless interaction between consumers and online & offline content. 
This technology empowers consumers with the ability to interact with their favourite brand’s products, anywhere, any time of the day. They do not sell an abstract, futuristic technology - they sell a solution that businesses can use to solve real-world problems. They believe that AI technology should be accessible and be readily available for any company to take advantage of Computer Vision for their competitive advantage. 

* Build, support and maintain high quality,maintainable mobile native apps.
* Responsible for working on all layers of our Android/iOS.
* Architect and maintain our set of native mobile applications.
* Building applications in memory- and network-constrained scenarios.
* Integrating with in-house built APIs.
* Solid understanding of UI/UX concepts and principles for mobile devices.
* Partner closely with our design and product team to architect a gorgeous application flow that is seamless and works intuitively for our users.
* Influence every aspect of the Android/iOS development process from API creation, design, to the final product.
* Own important pieces of the product that has high visibility both internally and externally.
* Stay informed on the latest versions of Android and mentor other developers/Xcode and Objective C APIs and mentor other developers.
* Envision new products and features that are inspired, considered and forward thinking.

## Requirements

* Diploma or Bachelor’s Degree in Computer Science or equivalent.
* At least 1 year of experience developing an object-oriented Android App/iOS apps.
* Foundation in computer science, with strong competencies in data structures, algorithms and software design.
* Knowledge of cutting-edge Android/iOS technologies.
* Fluency with at least one of more of the following Java, Kotlin,Objective-C, Cocoa, and/or Swift.

*** Nice to have:

* Experience working with various APIs is always a plus.
* Android/ iOS experience and generalist engineers with backgrounds in related technologies is a plus.

*** New Graduate:

* Minimum 1 year relevant academic/internship experience developing Android apps/Native iOS apps.
* Excellent verbal and written communications skills and demonstrated experience in presenting details and resolving differences across a variety of tasks.
* Excellent writing, analytical and organizational skills for documentation and reporting.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
