### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - DevOps Engineer - HCM/HN - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1351]
## Location
* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.
* 3rd Floor, Dai Phat Building – Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Ha Noi City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* from 2000$ and commensurate with experience.

## Job Description

Our client is an artificial intelligence company that focuses in visual recognition - Video and Image recognition. The aim is to transform the way offline content is being consumed by bridging O2O (offline to online) media properties with its latest cutting edge Carrot Visual Technology where various platforms and channels can be integrated, allowing seamless interaction between consumers and online & offline content. 
This technology empowers consumers with the ability to interact with their favourite brand’s products, anywhere, any time of the day. They do not sell an abstract, futuristic technology - they sell a solution that businesses can use to solve real-world problems. They believe that AI technology should be accessible and be readily available for any company to take advantage of Computer Vision for their competitive advantage. 

* Responsible for working on all layers of our AWS infrastructure.
* Maintain and improve our infrastructure for better CI/CD and scalability.
* Work with best practises to optimise our DB structures and data housing.
* Influence every aspect of the development process from API creation,content visualization, to final scalable product.
* Own important pieces of the product that has high visibility both internally and externally.
* Stay informed on the latest versions of software and mentor other developers.
* Envision new products and features that are inspired, considered, and forward thinking.
* Partner closely with our back-end and R&D teams to architect a fast,efficient and scalable application flow that is seamless and works intuitively for our developers and ultimately our users.

## Requirements

* Masters or degree in computer science or equivalent.
* Minimum 5 years application design and development experience.
* Minimum 2 years professional experience in DevOps.
* Excellent Linux/Unix Knowledge.
* Excellent knowledge of AWS, DNS and system architecture.
* Working experience with Docker, Jenkins, Kubernetes is expected.
* Experience with some of Terraform, Node agents, ansible re also expected.
* Hands on with CoreOS.
* Strong Database skills, Mongo, Redis, Elasticache, Fluentd, MySQL.
* A working understanding of code; PHP, Python etc.
* Excellent verbal and written communications skills and demonstrated experience in presenting details and resolving differences across a variety of tasks.
* Excellent writing, analytical and organizational skills for documentation and reporting.

*** Competencies or Skills:
* Vast experience developing scalable architectures.
* Foundation in computer science, with strong competencies in data structures, algorithms and software design, including APIs.
* Knowledge of cutting-edge technologies.
* Strong framework outside of DevOps is always a plus.
* Scripting experience and generalist engineers with backgrounds in related technologies is a plus.

## Why it would be awesome to work with us:

* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
