### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Golang Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1355]
## Location
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 1700$.

## About job

With our client website for business, SMEs can pay rent, salaries, invoices and even corporate tax using the credit cards they already have in their wallet today. SMEs love this website because it works like a credit card but pays like cash. It’s secure and easy to use platform reliably delivers payments to vendors while freeing up cash and providing access to interest free credit. 
Forget the delays and aggravations that come with traditional SME financing options. Schedule recurring payments, manage invoices, set payment reminders, and monitor payment status all from one dashboard. It’s never been easier for SMEs to meet monthly payment obligations while keeping cash available to fuel growth, bridge receivable gaps, and make immediate investment in the supplies, services, and expertise needed to drive a growing business forward.
* Analyse, design, develop new features and maintain, improve available features to ensure everything is high performance and stable.
* Cooperate with tech team members to debug and resolve complex issues.
* Collaborate with product and teams to define and prototype feature specifications.

## Requirements

* Highly skilled in developing, testing, debugging,troubleshooting with Golang programming language.
* Especially for building Restful web service.
* Engineering/Computer/IT degree with 3 to 5 years of diverse software development experience and teams.
* Understand well-known pattern SOLID and web security.
* Experience in a RDS like Postgres (prefer), Mysql, Oracle.

*** Nice to have:
* Experience in cloud, server stuffs like AWS, Linux and Cloudflare.
* Experience in an automation testing framework, Go tool.
* (Optional) Experience in other programming languages: NodeJS, PHP.

## Why it would be awesome to work with us:

* MacBook for working.
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
