### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Ruby on Rails Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1357]
## Location
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 2000$.

## About job

Our client is a leading digital wallet service in the Southeast Asia Region, where consumers can easily purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin. The company was founded in 2014 and headquartered in Singapore.

* Full-stack developer to maintain and develop online services.
* Work closely with product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website,mobile and web and applications.
* Participate in user testing on production.

## Requirements

* MUST HAVE GOOD ENGLISH.
* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* Minimum 2 years of experience in any of the followings: Ruby on Rails, Golang.
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Familiar with linux system administration and provisioning systems using Amazon Web Services.
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Enjoys challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over communicating).
* Language barriers aside, you must be willing to make an effort to communicate as much as.
* Overthink security.

*** Nice to have:
* Familiar with and passionate about BitCoin and crypto currencies, its network and protocol.
* Able to code in multiple languages - Java, Scala, Golang, Ruby.

## Why it would be awesome to work with us:

* MacBook for working.
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
