### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - QA Engineer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1358]
## Location
* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 2000$.

## About job

Our client is a leading digital wallet service in the Southeast Asia Region, where consumers can easily purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin. The company was founded in 2014 and headquartered in Singapore.

* Execute manual and write automated tests and identify actionable bugs quickly.
* Manage QA coverage of multiple web and mobile based projects.
* Planning/organizing necessary test passes, staying on top of all important issues, help triaging bugs and driving issues tore solutions and keeping everyone aware of QA status.
* Work with different team (Engineering/PM/Operation) to collect necessary information to assure the QA coverage, and also provide feedback on quality issues.
* Work with onsite and offshore team to set their priorities and remove their roadblocks to make sure sufficient coverage is done for the release.
* Assess the status of the release and help make sure that the release goes out on time with high quality level.
* Create and support test dashboards/reports.

## Requirements

* BA/BS degree in Engineering, Computer Science, IT, or related field.
* At least 2 years Quality Assurance experience in testing web or mobile applications.
* Ability to construct test cases and get them prioritized based on changes.
* Knowledge of test and tool development methodology.
* Experience in coding language.
* Communication skills, including development of presentations.

## Why it would be awesome to work with us:

* MacBook for working.
* Attractive salary and annual salary review.
* Working directly with foreign client, you will have a chance to directly communicate and discuss with foreigners, and 100% of your work efficiency will be recognized for annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy Hour every day, Team-building,Company trip, Play Game (PES, Uno, Werewolf), Play Sport (Football, Billiards..).

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
