### ISSUE TITLE
FETCH TECHNOLOGY VIETNAM - Senior Java Developer - HCM - FT

### ISSUE THREAD

**Issue by hana1104** [awesome-jobs/vietnam#1359]
## Location
* E. Town Central - 11 Doan Van Bo, Ward 12, District 4, Ho Chi Minh City.

## Salary
* Full-time (Monday to Friday from 9:00 to 18:00).
* Up to 2000$.

## About job

Our partner is an end-to-end urban logistics expert that provides reliable and economical solutions to help businesses maximize its sales potential. They offer warehousing, multi-channel commerce and delivery solutions. As top logistic corporation in Asia, they works closely with its parent company to leverage on mutual strengths. With a strong background in logistics, as well as their ability to tap into extensive network & resources, a full suite of services that include eCommerce, inventory management, warehousing & last mile delivery. They are able to tailor solutions to meet your unique needs.

## Requirements

* Fluency in Java (or Kotlin)-we use Spring Boot.
* Strong understanding of OOP and Clean Code.
* Experience with relational databases, SQL and schema design.
* A fan of writing unit tests and TDD. Understanding of RESTful APIs.
* Customer focus - you believe that talking to customers is essential to figure out what to build next.
* Knowledge of the Lean Startup principles (MVP, Build Measure-Learn).
* Ability to work independently and deliver your own solutions to problems.

*** Nice to have:
* Experience with Devops - setting up infrastructure (AWS) &CI.
* Knowledge or experience working with ERP or logistic systems is a plus.
* Understanding of Agile principles, Scrum/Kanban.
* Experience in distributed and concurrent systems, knowing the trade offs between stateful/stateless and synchronous/asynchronous architectures.

## Why it would be awesome to work with us:

* Attractive salary, working directly with foreign client, it means 100% of your work efficiency will be recognized for annual salary review.
* Be part of an incredible team of people from all over the world.
* Work in a rapidly expanding team and grow your responsibilities in time.
* Extensive on job training, you will always have chance to work with new emerging technologies. Especially large scale distributed systems and Cloud-native micro services.
* Social insurance, medical insurance &unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary and Bonus based on performance.

## Contact

* Email: hana@fetch.tech
* Skype: nghinghi283152
* Phone: 0169 441 3798
* Fanpage: https://www.facebook.com/fetchvietnam/
* Website: https://fetch.tech/

Our beautiful HR team will support you from A-Z. What you need to do is just send us your CV, all the world let Fetch worries!

**Comment by huydx** [comment]
not support recruiting agent
