### ISSUE TITLE
AXON - Senior Software Engineers - Core Platform - HCM - FT

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#1361]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam

## Salary Expectation
* Competitive

## About Axon

![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)

Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 

We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 

Early in 2017, Axon acquired Misfit Computer Vision and Machine Learning team and the team in Ho Chi Minh City has already made significant improvements for our solution and with Axon. We are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.

Our teams work in an agile environment - with the latest processes and technology. Our squad model gives your team full autonomy to solve business problems as it sees fit. We often deliver software improvements worldwide every day.

## Requirements

* 5+ years professional software development experience
* Practical skills delivering high-availability, scalable cloud software
* Proven ability to mentor junior engineers and good code review practices
* Strong communication skills in English and Vietnamese
* Customer focus: Axon's customers expect and deserve the best

### Preferred Qualifications

* You follow the latest in software engineering and open source technologies
* Back-end service experience in Java, Scala, Go, C#, or similar. Our platform stack is a combination of Go and Scala
* Understanding of cloud technologies in use today, such as: Apache Kafka, MySQL Clusters, Kubernetes, Spark Framework, etc...

### Must Have

* Willing to learn
* Passionate for delivering high-availability, scalable cloud software

### Ideally

* Background in Data Science, AI, or distributed systems

### Responsibilities

* Build a data storage cluster using new technologies such as Elasticsearch and vitess.io
* Implement a new notification and message routing pipeline to deliver time-sensitive confidential information to our customers
* Design a stream processing pipeline with Apache Kafka and Spark to process hundreds of millions of events per day and automate key insights
* Constructing a high performance distributed data verification engine 

### Interesting engineering projects

Our team is solving some of the hardest cloud challenges today. Every day we manage petabytes of video from hundreds of thousands of police officers around the world, and help the public with creative solutions from the courtroom to public disclosure. Come work in an exciting environment in which you use your passion, experience, and strong analytical skills to help bring new technologies to public safety and leave a positive impact on the world.

**Your Impact**
Do you enjoy coding challenging distributed systems? Are you not afraid of recompiling the Linux kernel if it helps you solve a problem? Can you bring technical insight to help make the right architectural decisions?

You are a Senior Software Engineer with a background in cloud services and distributed systems who enjoys unique challenges, growing junior engineers, and making the world a better place. Our teams work in a highly agile environment - with efficient processes and technology. Our squad model gives engineering teams full autonomy to solve business problems. We often deliver software improvements worldwide every day.

### Why it would be awesome to work with us

*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired

### Contact

Homepage: axon.com/careers
Dao Nguyen (daonguyen@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
