### ISSUE TITLE
AXON - Senior Backend Software Engineer - RMS AI - HCM - FT

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#1362]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam

## Salary Expectation
* Competitive

## About Axon

![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)

Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 

We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 

Early in 2017, Axon acquired Misfit Computer Vision team and now we are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.

Our teams work in an agile environment - with the latest processes and technology. Our squad model gives your team full autonomy to solve business problems as it sees fit. We often deliver software improvements worldwide every day.

## Requirements

* 5+ years of experience in software engineering.
* Degree in Computer Science, Physics, Mathematics, AI, Electrical Engineering, or related field.
* You have a track record of building and deploying complex software
* You can adapt to different programming languages and technologies
* You have made tough technical decisions based on requirements, trade-offs, and user experience.
* You enjoy mentoring and growing Junior Engineers
* You are comfortable with a lot of autonomy.
* Background in Data Science, AI, or distributed systems is a plus

### Core Technologies Used

* Golang with GraphQL powered backend
* React.js
* Tensorflow and Caffe2 AI frameworks
* Kubernetes
* High performance messaging using Protobuf

### Must Have

* Willing to learn
* Have a track record of building and deploying complex software

### Ideally

* Background in Data Science, AI, or distributed systems

### Your Mission

You are a talented software engineer who wants to work closely with our PhD and Product teams to build new technology which changes the world. You have a passion for AI and Machine Learning and want to learn more. You are also detail-oriented, looking at problems from different directions to deliver the best technical solutions.

Your mission: Leverage advanced technology, AI, and computer vision to change the way policing is done.

### Interesting engineering projects

Axon Records Management (RMS) is a groundbreaking new product designed to change how police officers collect and share information on a day-to-day basis. By leveraging Axon's family of connected cameras, sensors, and devices we can automate the generation of police report, instantly share information between officers to solve crimes faster, and increase public trust by having police officers spend more time with their communities and less time doing data entry.

Would you love to shape this future and join a team that is building it right now?

Watch a short video that goes more in depth here: https://vimeo.com/221924983

### Why it would be awesome to work with us

*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired

### Contact

Homepage: axon.com/careers
Dao Nguyen (daonguyen@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
