### ISSUE TITLE
AXON - Engineering Manager - Redaction and Video - HCM - FT

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#1364]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam

## Salary Expectation
* Competitive

## About Axon

![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)

Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 

We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 

Early in 2017, Axon acquired Misfit Computer Vision team and now we are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.

Our teams work in an agile environment - with the latest processes and technology. Our squad model gives your team full autonomy to solve business problems as it sees fit. We often deliver software improvements worldwide every day.

## Requirements

* Degree in Computer Science, Physics, Mathematics, AI, Electrical Engineering, or related field
* Strong C/C++ experience is preferred
* Experience with Video Streaming / RTSP a plus, however we do offer training
* You have made tough technical decisions based on requirements, trade-offs, and user experience
* You are comfortable with a lot of autonomy
* Background in Data Science, AI, or distributed systems is a plus
* Experience building and managing a strong team of engineers

### Core Technologies Used

* Golang and Scala based Microservices
* C/C++ optimized code for video decoding and playback
* OpenCV, GStreamer, FFMPEG, and more
* WebRTC, RTSP, HLS, Mpeg-DASH Support.
* React.js
* Tensorflow and Caffe2 AI frameworks
* Kubernetes, Docker, and GPU solutions for Docker (NVidia)
* High performance messaging using Protobuf

### Must Have

* Willing to learn
* Strong C/C++ experience

### Ideally

* Experience with Video Streaming / RTSP

### Responsibilities

You are a strong Engineering Manager who enjoys helping build flexible, reliable, and scalable services. You think about all aspects of our lifecycle - such as autoscaling expensive GPU clusters during high demand and pulling them back when the demand is low. You have a passion for AI and Machine Learning and want to learn more. You are also detail-oriented, looking at problems from different directions to deliver the best technical solutions. You also love video streaming and playback, and find it an interesting challenge.

Your mission: Leverage advanced technology, AI, and computer vision to change the way policing is done.

### Interesting engineering projects

Our Video and Redaction Squads enable our customers to quickly watch, annotate, sort, highlight, and redact this information directly in the browser - either from recorded video or live streamed from the field. They are also the key engineers behind bringing a simple user experience to our powerful video AI tools - such as License Plate detection, Computer Screen Redaction, Skin Blurring, and facial blurring.

The Video and Redaction teams build everything from a custom real-time in-browser video editing solutions (based on React with a custom streaming backend), to innovative internal tools to train AI models on video data for use within our products.

Our Video Squad engineers also contribute many of our innovations back to the open source community - through improvements to gstreamer, ffmpeg, and other open source tools and systems.

Watch a short video that showcases some of our new technologies here: https://vimeo.com/221924983

## Why it would be awesome to work with us

*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired

### Contact

Homepage: axon.com/careers
Dao Nguyen (daonguyen@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
