### ISSUE TITLE
[NHN Vietnam] - Java Developer - Binh Thanh District/ HCMC - FT

### ISSUE THREAD

**Issue by huyenchau915** [awesome-jobs/vietnam#1367]
## Location

* Bình Thanh District, Saigon, Vietnam
* Fulltime

## Salary Expectation

* upto 2000$ /month or range

## Requirements
* Must have knowledge about computer engineering
* Must have knowledge about JAVA, JVM Architecture
* Must have knowledge about Multi-Threading
* Have good understanding with OOP
* Knowledgeable with Web Server and Web Application Server
* Knowledgeable with Spring framework or other MVC framework
* Knowledgeable with RESTful
* Knowledgeable with MySQL or RDB
* Familiar with Git, Maven, IntelliJ IDEA or Other IDE
* English: Intermediate/ Advanced
* Other skills: Good communication skill and ingenious behavior
* Ability to work in fast-paced environment, learn rapidly, multitask, organize, and prioritize work
* Logical thinking and problem analysis

### Responsibilities
* Develop software application in JAVA
* Collaborates with leads to explore existing systems, determines areas of complexity, potential
risks to successful implementation, learns the applications capabilities
* Follows coding standards, builds appropriate unit tests, integration tests and deployment scripts
* Writing reusable, testable, and efficient code implementation of security and data protection.
* Contributes to continual improvement by suggesting improvements to user interface, software
architecture or new technologies
* Level: All Levels

### Why it would be awesome to work with us
* Work in friendly and professional working environment
* Opportunities to join in-house projects
* Opportunities to do monitoring our products.
* Entitle to full of Benefit package of NHN Viet Nam

### Contact
Please send your CV to mail below:
Mail: recruit_vn@nhnent.com (Ms. Chau Duong)
skype: huyenchau915
Phone: +84 028 73098179
Address: 
Floor 13, 194-Golden Building 473 Dien Bien Phu Street,
Ward 25, Binh Thanh District
http://www.nhnent.com/asia/vn/company/companyInfo.nhn
https://www.facebook.com/nhnvietnam/

![nhn viet nam _java developer all levels](https://user-images.githubusercontent.com/42532483/49640134-532ad600-fa3f-11e8-9272-f82bca5055ec.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
