### ISSUE TITLE
[NHN Vietnam] - iOS Developer - Binh Thanh District/ HCMC - FT

### ISSUE THREAD

**Issue by huyenchau915** [awesome-jobs/vietnam#1368]
## Location

* Bình Thanh District, Saigon, Vietnam
* Fulltime

## Salary Expectation

* upto 2000$ /month or range

## Requirements

* Min experience: 2 + years in native iOS development
* University graduation from related industry
* Understanding of OOP, design pattern and multi-thread programming
* Good practice and fluent with Swift
* Knowing Objective C is a plus
* Fluent with database and network framework such as Realm and
Alamofire
* Familiar with XCode Instruments for application Tuning and detect
memory leaks
* Experience in iOS UI/UX, using 3rd library, customizing view is a big plus
* Other: Experienced with CI tools such as Fastlane, Jenkins or Travis-CI is
a big plus
* Basic knowledge of Git Flow is essential
* Experience iTunes connect, Testflight, Xcode Crash Report
* A good working attitude with Samurai ethics and a desire to do research
and learn new things, a can-do attitude will be appreciated.

### Responsibilities

* Working as a team or an individual to develop native iOS apps
* Experience in Tuning application for speed and memory management
* Read existing code to expand new features and maintain
documentation
* Using animation for a smooth user-experience and third party
framework to
customize views
* Level: Experienced

### Why it would be awesome to work with us

* Work in friendly and professional working environment
* Opportunities to join in-house projects
* Opportunities to do monitoring our products.
* Entitle to full of Benefit package of NHN Viet Nam

### Contact

Please send your CV to mail below:
Mail: recruit_vn@nhnent.com (Ms. Chau Duong)
skype: huyenchau915
Phone: +84 028 73098179
Address: Floor 13, 194-Golden Building 473 Dien Bien Phu Street,
Ward 25, Binh Thanh District
http://www.nhnent.com/asia/vn/company/companyInfo.nhn
https://www.facebook.com/nhnvietnam/

![nhn viet nam _ios developer](https://user-images.githubusercontent.com/42532483/49640376-07c4f780-fa40-11e8-8cc2-62c9e6bb60fa.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
