### ISSUE TITLE
[NHN Vietnam] - Android Developer - Binh Thanh District/ HCMC - FT

### ISSUE THREAD

**Issue by huyenchau915** [awesome-jobs/vietnam#1369]
## Location

* Bình Thanh District, Saigon, Vietnam
* Fulltime

## Salary Expectation

* upto 2000$ /month or range

## Requirements

* 3 - 5 years experience in native Android development
* University graduation from related industry
* Knowledge of OOP, design pattern, the client-server model and Architecture Pattern (MVP, MVVM)
* Good practice of Java programming
* Familiar with Android SDK tools, Android Studio
* Experience in RxJava and Git-flow
* Can communicate, read and write technical English document
* Other skills: Experience in Android UI/UX, using 3rd library, customizing view and multi-thread programming is a big plus

### Responsibilities

* Join a team to develop Android app for South East Asia market
* Lead the project, review code, architecture and find solutions for issues
in project
* Design and develop new mobile app, or from an existing code
* Read code to and writing document
* Research new technologies understanding and share knowledge to
team members.
* Level: Experienced

### Why it would be awesome to work with us

* Work in friendly and professional working environment
* Opportunities to join in-house projects
* Opportunities to do monitoring our products.
* Entitle to full of Benefit package of NHN Viet Nam

### Contact
Please send your CV to mail below:
Mail: recruit_vn@nhnent.com (Ms. Chau Duong)
skype: huyenchau915
Phone: +84 028 73098179
Address: Floor 13, 194-Golden Building 473 Dien Bien Phu Street,
Ward 25, Binh Thanh District
http://www.nhnent.com/asia/vn/company/companyInfo.nhn
https://www.facebook.com/nhnvietnam/

![nhn viet nam _aos developer_jd mr c](https://user-images.githubusercontent.com/42532483/49640751-ef091180-fa40-11e8-960f-af13833dc097.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
