### ISSUE TITLE
[NHN Vietnam] - QC Engineer - Binh Thanh District/ HCMC - FT

### ISSUE THREAD

**Issue by huyenchau915** [awesome-jobs/vietnam#1370]
## Location

* Bình Thanh District, Saigon, Vietnam
* Fulltime

## Salary Expectation

* upto 1000$ /month or range

## Requirements

* Min experience: 2 ~ 3 years experience
* Experienced with over with 10 QC resources team
* (Optional) Nice to have experiences with following Process model: Agile, Water Fall
* (Plus) Experience API performance test
* (Plus) Experienced in Automation test
* English: Intermediate

### Responsibilities

* Level: 2-3 years
* Devising procedures to inspect and report quality assurance issues
* Appraise customers’ requirements and make sure they are satisfied
* Facilitate proactive solutions by collecting and analyzing quality data
* Assure the reliability and consistency of production by checking processes and final output
* Keep records of quality reports, statistical reviews and relevant documentation
* Review current standards and policies

### Why it would be awesome to work with us

* Work in friendly and professional working environment
* Opportunities to join in-house projects
* Opportunities to do monitoring our products.
* Entitle to full of Benefit package of NHN Viet Nam

### Contact
Please send your CV to mail below:
Mail: recruit_vn@nhnent.com (Ms. Chau Duong)
skype: huyenchau915
Phone: +84 028 73098179
Address: Floor 13, 194-Golden Building 473 Dien Bien Phu Street,
Ward 25, Binh Thanh District
http://www.nhnent.com/asia/vn/company/companyInfo.nhn
https://www.facebook.com/nhnvietnam/

![nhn viet nam _senior qc_tester](https://user-images.githubusercontent.com/42532483/49640947-6e96e080-fa41-11e8-8884-041bb4d2273d.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
