### ISSUE TITLE
[NHN Vietnam] - Project Manager - Binh Thanh District/ HCMC - FT

### ISSUE THREAD

**Issue by huyenchau915** [awesome-jobs/vietnam#1371]
## Location

* Bình Thanh District, Saigon, Vietnam
* Fulltime

## Salary Expectation

* upto 2000$ /month or range

## Requirements

* Min experience: At least 2 year experience as Project Manager
* Having strong responsibility and enjoying development
* Have experiences involved in in-house mobile product
* Logical thinking and problem analysis
* Good communication skill and ingenious behavior
* Ability to manage and lead the team
* Logical thinking and problem analysis
* English: Advanced

### Responsibilities

* Project Manager: In charge of management, schedule and quality for product
development.
* Product strategy: PRD, Wireframe
* Accountable for delivering outcomes appropriate to and/on beyond requirements in
defined timeline as schedule
* Define, manage, develop and customize necessary processes for project management
online with company circumstances
* Manage UI and QA process
* Manage whole development departments for our in-house projects (Comico) as well as
other new projects
* Responsible for resources planning, recruitment, allocation and utilization for the
department
* Analyze issues and planning development process / policy / KPIs for development
departments
* Provide coaching and mentoring on people management and leadership skills to the team
leads and managers
* Implement continuous improvement of software development services
* Level: Experienced

### Why it would be awesome to work with us
* Work in friendly and professional working environment
* Opportunities to join in-house projects
* Opportunities to do monitoring our products.
* Entitle to full of Benefit package of NHN Viet Nam

### Contact
Please send your CV to mail below:
Mail: recruit_vn@nhnent.com (Ms. Chau Duong)
skype: huyenchau915
Phone: +84 028 73098179
Address: Floor 13, 194-Golden Building 473 Dien Bien Phu Street,
Ward 25, Binh Thanh District
http://www.nhnent.com/asia/vn/company/companyInfo.nhn
https://www.facebook.com/nhnvietnam/

![nhn viet nam _project manager](https://user-images.githubusercontent.com/42532483/49641330-68553400-fa42-11e8-8212-a803a0006edf.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
