### ISSUE TITLE
FPT Telecom - Big Data Engineer - HCMC - FT

### ISSUE THREAD

**Issue by vinhdangphuc** [awesome-jobs/vietnam#1373]
## Location

* FPT Tan Thuan 2, Tan Thuan Road, Tan Thuan EPZ, District 7, Ho Chi Minh City, Viet Nam

## Salary Expectation

* Up to $2000

## About FPT Telecom

FPT Telecom is one of the biggest internet companies in Viet Nam, we are currently providing a variety of telecom products and services including:
* ADSL/VDSL, TriplePlay, FTTH
* Leased line, Domain, Email, Web Hosting, Data Center
* Internet value added services: FPT TV, Voice over IP (VoIP), Remote Monitoring (IP Camera), Certificate Authority (CA), Cloud Computing,...

FPT Telecom is constantly researching and implementing more and more integrated value-added services on one same Internet connection to provide maximum benefits to customers.

-----------------------------------------------------------------------------------------------------------------------------
We are looking for a Big Data Engineer that will work on collecting, storing, processing, and analyzing huge sets of infrastructure, OTT application data. The primary focus will be on choosing optimal solutions to use for these purposes, implementing and monitoring as well as maintaining. You will also be responsible for integrating them with the architecture used by more than 14000 employees and tens of millions customers.

## Requirements

* Good at problem solving, algorithms, data structures, functional programming, design pattern
* Having statistical thinking is a plus
* Good knowledge of SQL & NoSQL, database systems.
* Having knowledge & experience of Hadoop Ecosystem (Spark, Hadoop, Druid, Clickhouse, ELK,..) is a big plus
* Basic knowledge of Linux and operating system
* Experience but not limited to: Scala, Java or Python,..

### Must Have
* Willing to learn, attention to details
* Ability to communicate with both technical and non-technical team members

### Responsibilities

* Proactively communicate with business teams, network engineers to understand their needs and help them solve their problems
* Analysis and detect anomalies in the internet infrastructure, provide/predict meaningful alert for fixing problems as soon as possible
* Research, design and develop the data processing pipeline for real-time analytics dashboard and monitor our infrastructure and OTT services
* Build high performance data warehouse, BI platform for data analytics, handle high volume of data (terabytes per day)
* Building toolsets/frameworks to manage, integrate with the various data sources, provide an efficient way for data science and business team exploring the data
* Working with data scientist in the design of machine learning models, analysing our customer behaviour, improve user experiences
* Evaluate and develop new technologies/solutions to make our infrastructure more reliable, high availability

### Why it would be awesome to work with us

* Data pipelines still in an early stage and have lots of things to improve
* Great opportunity to dive deeply into a big data system
* Challenging working environment, open for new ideas and solutions based on a huge dataset in many domains
* We often conduct presentations to improve our individual skill sets, sharing our domain knowledge together
* You are encouraged to contribute ideas, corporate with the others and get your ideas to work efficiently
* Unique culture with many exciting activities: rookie training, 72 hours experience, team building, village festival, club, color fest, happy hour, birthday celebration,...
* Best employees are awarded a company-sponsored overseas trip every year
* Obtaining full legal insurance coverage with FPT-Care
* We are offering around 15-17 months' wage/year, performance-based bonus

### Contact

Vinh Dang
Email: vinhdp4@fpt.com.vn  
Skype: [live:vinhdp_2](https://join.skype.com/invite/bZueGEcKLmPe)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
