### ISSUE TITLE
LittleLives - Backend Engineer (PHP, NodeJs) - HCMC - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#1376]
## Location
Green Hub, Level 9, 186 Bis Trần Quang Khải, P. Tân Định, Q.1

## Salary Expectation
800 - 2000 USD

### What you will be doing:

- Develop backend services in Node.js and PHP for modules in our existing platform
- R&D novel and ingenious solutions to unique problems - RethinkDB, DC/OS, BigQuery
- Collaborate with a diverse multinational team of engineers
- Build new features: cashless payments, intelligent automated workflows, integration with government services
- Be a vital voice in sprint planning and daily stand up meetings
- Automate everything!

### Here's what you can achieve with us:

- Develop a wide experience in different technologies, earning you respect in problem solving
- A chance to make a difference to the lives of thousands of preschool educators, and  children all over the world will benefit.
- Develop your strengths; your contributions will make you irreplaceable. We can't get another you in a minute.
- Explore your leadership potential, code review your peers, and pass down the knowledge .

### Must have :

- Deep expertise in PHP 7, Node.js, PostgreSQL and Redis
- Experience with container technology (Docker, DC/OS)
- Linux guru - piped commands with sed easily roll off your fingertips
- Sound coding practices - git, unit testing, CI/CD, design patterns, service oriented architecture
- Strong sense of user empathy and ownership over the products you've created.
- Team player, doing anything and everything needed to get things done

### Nice to have:

- Personally deployed Kubernetes, or any other container orchestration systems
- Production level serverless (lambda, google cloud functions) experience
- Comfortable with more languages than you have fingers
- Your own ideas!

## Why You'll Love Working Here

- 14 days annual paid leave
- Competitive salary
- We WILL push you to learn new things together with us
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Macbook Pro and additional screens
- Yearly Bonus
- Travel for our team building event every year
- Take on lead roles as the team expands
- Have your say in the culture of our still young Vietnamese office

## Contact
- Email: changinglives@littlelives.com
- What do you need to apply?
    - Your CV (English)
    - Your Github (or equivalent open source community) profile

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by dominhquan** [comment]
@qcam : can i reopen it again and push it on top ? Or i have to create another one

**Comment by qcam** [comment]
@dominhquan please create a new one.
