### ISSUE TITLE
Worknetics Singapore

### ISSUE THREAD

**Issue by worknetics-hr** [awesome-jobs/vietnam#1377]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $1000 to $1500 USD per month

## Requirements
3 – 4 years of full stack development experience 
Experience in working in Agile and Continuous Integration/Continuous Delivery methodologies 
A collaborative attitude and a lifelong learner 
Ability to work independently
Possess critical thinking when solving problems
Takes ownership and responsibility
Excellent command of English

## Skills

 PHP, Laravel, Git and Javascript

### Responsibilities

Take on a key tech engineer role 
Proficient in all backend and frontend programming language (open source language) 
Specialize in PHP, Laravel, Git and Javascript
Supervise system infrastructure to ensure functionality and efficiency 
Build quality assurance and data protection processes 
Build quality database structure 
Integrate all the systems onto Google Cloud
Communicate technology strategy to partners and investors 
Monitor KPIs and IT budgets to assess technological performance

### Benefits

Insurance coverage
13th-month salary bonus
Variable performance bonus based on project contributions

### Why it would be awesome to work with us

Worknetics is hiring for a story-tech start-up that envisions to empower the Asian community with a voice through storytelling. Very often, we realize that stories and content available in the market are very western-centric. While the quality may be great, we also want to ask ourselves, “What about Asia? Aren’t there great stories to share over this part of the world as well?” The answer is a resounding, “Yes!”. The only challenge is that in the Asian community, people tend to be a less vocal and do not feel as comfortable articulating their beliefs as compared to their western counterparts. As such, we recognize the value and importance of developing a platform in Stories of Asia to build a strong and inclusive community which will empower the people with the confidence to share their stories. That way, we can then all learn, grow and create a meaningful exchange with the rest of the world. We have the opportunity to change the world for the better and create something that we can truly be proud of. Are you game for it?

### Opportunities

Work with our core team in Singapore and potentially members in other parts of Asia as the business expands.
Potential leadership role in the tech team if you can prove yourself
Improve your English language as that will be the main form of communication with the core team.
Be the champion for the platform development and build a game-changing platform
Further, enhance your technical skills while working with us

### Contact
Homepage: www.worknetics.net
Email: hr@worknetics.net

**Comment by huydx** [comment]
wrong format
