### ISSUE TITLE
8 Bit Rockstars - Front End Team Leader - Saigon - FT

### ISSUE THREAD

**Issue by itaibaruch** [awesome-jobs/vietnam#138]
![Alt text](http://8bitrockr.com/img/logo_w.png)
## Location
- Saigon, Vietnam
- http://www.8bitrockr.com
## Salary Expectation
- 1,500$ - 2,000$ /month
## The Job
- **Rockstar** - Join our Rockstars team to truly become Front End Rockstar 
- **Fun** - Join a young and dynamic team in an international, professional and English speaking working environment 
- **Tech Rockstar** - Apply the latest technology like ReactJs, AngularJs, ES2015 etc... 
- **Exciting Projects** - Working with oversea clients and awesome projects 
- **Leader** - Supervise and support other junior developers in fulfilling their tasks and improving their skills 
- **Problem Solver** - Ability to find answers through researching and reading documentation
## Requirements
- Javascript ES5, ES2015
- Javascript Frameworks  React / Angular 
- HTML, HTML5, CSS, CSS3, CSS frameworks like Bootstrap / Foundation 
- 4+ year experience in working with front-end projects
## Skills
- Positive attitude, responsible and proactive with the ability to learn and achieve superior results. 
- Strong communication skills in English, verbal and written 
- Experience working with a team and deadlines 
- Strong teamwork and contribution spirit 
- Understanding of continuous integration 
- Experience with Agile methodology (Scrum) 
- Having good leadership skills and attention to details 
- Open-minded and good at adapting to frequent changes 
- Willing to learn new technologies while working
### Our Tech Stack
- Node / Alt / React / Webpack 
- RoR / Alt / React / Broweserify 
- client only - React / Webpack / Redux 
### Why You'll Love Working Here
- Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things 
- Attractive, competitive salary and incentives 
- Year end bonus (13th month salary and so much more based how awesome you are!) 
- Healthcare coverage 
- Extra health and accident insurance where you can benefit from international standards treatment 
- Short and long-term international training / work 
- Fun and flexible working environment in a modern office in District 1 
- Opportunities to work with international experts and cool startup entrepreneurs 
- Annual company trip (local or internationally), monthly team building events, after release parties and much more 
- 40 hour work weeks 
- 15 days of vacation per year
### Contact

hr@8bitrockr.com

**Comment by vuongdothanhhuy** [comment]
Correction: Email should be **_hr@8bitrockr.com_**
