### ISSUE TITLE
[Chotot.com–701Search group] - Project Manager - HCM - FT

### ISSUE THREAD

**Issue by anhdn** [awesome-jobs/vietnam#1381]
## Location
* 2 Ngo Duc Ke, District 1, Ho Chi Minh City, Vietnam
* (Near Pho Di Bo Nguyen Hue)

## Salary Expectation
* Competitive

## Requirements
- Drive project management including budgeting, planning, scheduling, documentation, reporting, and communication.
- Provide technical project coordination and join in system design activity that would break down complex technical project to small sub problems and achievable milestones.
- Assist stakeholders and engineering team in problem definition, systems analysis including detailed specifications and documentation of architecture approach.
- Organized and maintains technical support documentation, implementation calendars, communicate updates relevant stakeholders and management team on the project status.
- Provides relevant user and teams with training and knowledge transfer as necessary for implementation.
- Manage and plan project implementation budget and work with Finance team on making sure the execution cost is according to budgeted.

## Qualifications:

- Bachelor’s degree (Information Technology or related field), having three years related experience in technical project management in an Agile product organization.
- Strong background in server side tech implementation, preferably with actual hands on experience in implementing the solution.
- Familiarity with all cloud native technologies and concepts with the capability to self-learn to comprehend new technologies and their applications.
- Strong systematic problem solving, communication and presentation skill set.
- Detailed oriented team player with outstanding interpersonal and communication plus conflict resolution skills.
- Excellence command in English communication,  and good technical writing skill is a must.

## About 701 Search 
701Search group are Telenor companies running top online classified marketplaces in countries such as Malaysia, Vietnam and Myanmar. Our product and engineering teams are growing passing 100 across countries such as Singapore, Malaysia, Vietnam, Indonesia and Myanmar, successfully enabling high quality product development for number one marketplaces such as chotot.com and mudah.my. This opening position in DevRel will help drive our engineering quality and engagement to the next level both internally and externally. If you are a passionate technologist driven by seeing fruitful impact of excellence engineering practice then join us to be the key driver of this exciting movement. You can be based in either Vietnam or Malaysia with frequent travel across these countries plus others in the ASEAN region.

### Contact
* Homepage: careers.chotot.com
* Contact: anhdang@chotot.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
