### ISSUE TITLE
Taggle Health - Senior Unity App Developer - Saigon - FT

### ISSUE THREAD

**Issue by nathando** [awesome-jobs/vietnam#1383]
## Location

* Saigon, Vietnam (working remotely, Singapore based company)

## Salary Expectation

* Competitive

## Requirements

* Strong knowledge on OOP principles and design patterns
* Strong knowledge on Unity3D best practices and usage
* Experience in building game/app with Unity3d on mobile devices (iOS, Android) is a plus
* Experience in connecting Unity3D with wearables through Bluetooth is a plus
* Candidate must have good communication skills with positive attitude

### Must Have

* Expert-level knowledge on Unity, its programing usage and patterns
* Keen eye on gamification and bring gaming to ordinary application

### Ideally

* At least 3 years working with Unity3D game engine
* Publish a few games/ mobile applications with Unity

## Responsibilities

We are looking for an experienced Unity3D developer who can be a part of our team. You must have experience writing games with Unity3D, well-versed in its usage patterns and strong background in programming in general.

### You'll be responsible for

* Together with the Vietnamese team design, develop our core digital health app
* Design, develop mini games that adds on to the core app
* Research and implement integration of health devices with games
* Work in a team and able to mentor junior members when needed

You will help create applications that take care of public's health and will be used widely in Singapore. Through gamification, these applications help elderly and patients to regain their health and have fun in the process.

## Why it would be awesome to work with us

* Flexible working environment. We value quality of our work not any admin procedure
* Fun and exciting digital health startup solving problems that will make life better for our clients
* Small team means you can explore different new technology and move faster

## Contact

Please include your other technical profiles (beside github) such as linkedin, stackoverflow, technical blog if available

Homepage: https://tagglehealth.com/  
Email: nathan@tagglehealth.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
