### ISSUE TITLE
Rakuna - Senior Mobile App Developer - Hanoi / HCM - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1384]
## Location

* Hanoi, Vietnam
* HCM, Vietnam 

## Salary Expectation

* Competitive
* Negotiable based on experiences and skills

## Skills

* Strong background in mobile application development with significant cross-platform mobile engineering experience (3+ years) in iOS and Android
Expertise working on at least one large application and/or have released multiple apps (business and/or personal)
* Familiarity with mobile threading, memory management, MVC/MVVC concepts and how they apply to mobile applications
* Ability to develop effective UX solutions through user feedback loops, leveraging both quantitative and qualitative metrics
* Effective project management skills; creative problem-solving skills; strong communication skills

## Responsibilities

The Senior Mobile App Developer will be responsible for the development and maintenance of applications aimed at a range of devices including mobile phones and tablet computers. You will be working alongside other engineers and developers working on different layers of the infrastructure.

_Note: This position is open to all international candidates who are willing to relocate to our APAC office in Hanoi, Vietnam._ 

* Design, develop, and optimize mobile application
* Plan and implement complex new features and functionality, as well as entire applications end-to-end
* Consult on project goals (best practices, conversion, Usability, UI / UX)
* Work closely with developers and designers to create beautiful, functional solutions
* Handle multiple clients and internal projects simultaneously

## Why it would be awesome to work with us

* Work in a vibrant, diverse, multinational start-up team; Flexibility and high work ownership
* Ability and freedom to bring own idea to the table without discriminating or shutting one up
* Comprehensive Compensation and Benefits package
* Flexible work hours 
* Trained to be diverse in several areas or get to train others to become as skilled as you are. If you just know one area, before leaving, you will know several areas of your job you felt are not necessary or important
* Dress code ain’t no problem, just wear whatever you got
* Free lunch, frequent bonding events
* Company retreats twice a year
* Performance-based and negotiable salary that heavily depends on your skills (more details to be given during interviews)

## Apply

Send resume with a portfolio on past work to apply: https://jobs.smartrecruiters.com/RAKUNA1/743999681453234-senior-mobile-app-developer

_Please include your other technical profiles (besides GitHub) such as LinkedIn, StackOverflow, technical blog if available._

Only qualified candidates will be contacted.

## Contact

Homepage: www.rakuna.co
Email: ly@rakuna.co (Ly - Talent Acquisition Coordinator)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
