### ISSUE TITLE
Rakuna - Software Developer - Hanoi / HCM - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1385]
## Location

* Hanoi, Vietnam
* HCM, Vietnam 

## Salary Expectation

* Competitive
* Negotiable based on experiences and skills

### Must-have
* BS degree in Computer Science, a similar technical field of study or equivalent practical experience
* At least 1 year of software development experience in one or more general purpose programming languages
* Database: MySQL, Postgres, Redis, MongoDB
* Have a strong knowledge of TDD, BDD 
* Interest and ability to learn other coding languages as needed

### Ideally
* Working proficiency and communication skills in verbal and written English
* Effective project management skills; creative problem-solving skills; strong communication skills
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect
* A strong sense of design

## Responsibilities

_Note: This position is open to all international candidates who are willing to relocate to our APAC office in Hanoi, Vietnam._ 

* Manage product pipelines including planning, development, and maintenance.
* Collaborate with core functional teams - Sales & Marketing, Quality and Customer Success, and * Operations to achieve the ultimate business goals.

## Why it would be awesome to work with us

* Work in a vibrant, diverse, multinational start-up team; Flexibility and high work ownership
* Ability and freedom to bring own idea to the table without discriminating or shutting one up
* Comprehensive Compensation and Benefits package
* Flexible work hours 
* Trained to be diverse in several areas or get to train others to become as skilled as you are. If you just know one area, before leaving, you will know several areas of your job you felt are not necessary or important
* Dress code ain’t no problem, just wear whatever you got
* Free lunch, frequent bonding events
* Company retreats twice a year
* Performance-based and negotiable salary that heavily depends on your skills (more details to be given during interviews)

## Apply

Send resume to apply: https://jobs.smartrecruiters.com/RAKUNA1/743999681453405-software-developer

_Please include your other technical profiles (besides GitHub) such as LinkedIn, StackOverflow, technical blog if available._

Only qualified candidates will be contacted.

## Contact

Homepage: www.rakuna.co
Email: ly@rakuna.co (Ly Nguyen - Talent Acquisition Coordinator)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
