### ISSUE TITLE
Home Credit - Senior Android Developer - HCM - FT

### ISSUE THREAD

**Issue by YenPhamHC** [awesome-jobs/vietnam#1387]
## Location

* Dist 2, HCMC

## Salary Expectation

* Upto 2000$

## Requirements
* 8 years of programming profession
* 3 years of Android Studio with Java
* Proven development experience in medium-to-large scale mobile app development
* 5+ years Software Engineering experience
* Strong background on data structures and algorithms
* Firm understanding of design patterns
* Good experience of programming Thread, Handler, AsyncTask, Memory optimization and scheduling technique
* Extensive knowledge of UI elements & layout, advanced animation techniques
* Solid understanding of the full mobile development life cycle
* Strong experience in handling Push Notification, Google Maps Android and camera
* Solid experience in working with Server Side using REST and, SOAP
* Strong experience working with Firebase, Hockey and other libraries
* Good English communication

### Responsibilities

* We are looking for an ambitious and talented Senior Mobile Developer (Android) to join our team. You will be a key-person in building the company’s new innovative Mobile App solutions. Home Credit is an important factor for millions of families in financing vehicles, consumer durables, credit cards and cash loans. Your solutions will have a large impact on how we communicate and interact with our existing as well as new customers.

* You will be working in a peaceful and fantastic office building at Thao Dien in a multi-department, multi-nationality, financial-oriented working environment with friendly, funny and pro-active team members to:

* Develop fully responsive, user-friendly, feature-rich and modern mobile applications using Android
* Integrate mobile applications with third-party systems
* Work closely with outsourcing partners in developing our mobile applications
* Perform coding and unit testing, build scripts, and solve technical problems.
* Review product’s code
* Communicate and coordinate effectively in English with other developers and managers to ensure optimal progress towards our goals
* Meet project milestones and timely release of software according to scheduled plans

### Why it would be awesome to work with us
* Attractive Salary
* 13th Salary Fixed and KPI Bonus
* AON Health Care
* 24/7 Accidental Insurance
* 100% Social Insurance Pay
* Meal Allowance
* Yearly Medical Checkup
* 15 Annual Leaves
* Professional and Transparent Working Environment.

### Contact
Homepage: https://www.homecredit.vn/en/career#
YenPham: yen.ptn@homecredit.vn (0932 067 949)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
