### ISSUE TITLE
ELEK - UI & UX Designer - Saigon/Remote - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#1389]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Unto $1000

## Requirements
* 2 – 4 years of experience as an UI-UX Designer or similar role
* UI & UX projects portfolio
* Active knowledge of Adobe range of design tools including Photoshop, Illustrator, InDesign, XD
* Experience with HTML5, CSS3, and Bootstrap **(a plus)**
* Knowledge of Usability Factors in Human Computer Interaction.
* Knowledge of wireframe tools (e.g. Wireframe.cc and InVision)
* Proficient with Visual Communication including (Layout, Color, Typography, Icons, Images, and Design theory
* Knowledge of Usability Factors in Human Computer Interaction.
* Bachelor’s degree in Design, Computer Science / Technology, or relevant field
* Detail oriented and critical thinker
* Problem solver and customer-centered believer
* Ability to work under pressure and meet deadlines
* Ability to discuss and explain design options
* Team spirit; good communication skills to collaborate with various stakeholders
* Good written and verbal communication skills (good level of English language - both spoken and written, the interview will be in English as the main language)

### Responsibilities

We are building highly complex rich web and mobile apps. and we are looking for UI & UX Designer with experience in UI and UX design for complex web and mobile applications.

You will be working in a peaceful and fantastic ELEK office in a multi-department, multi-nationality, IOT-oriented working environment with friendly, funny and pro-active team members to:

* Communicate with product owner to understand company's business goals and objectives
* Develop a visual concept which aligns with the brands and project goals 
* Gather and evaluate requirements in collaboration with product owner
* Create effective, captivating, illustrative, testable, and usable designs
* Illustrate design ideas using storyboards, process flows, sitemaps
* Design graphic user interface elements, like menus, tabs and widgets, page navigation buttons, images, sketches and tables, and fields
* Promote ELEK brand through delivering high quality pieces on tight deadlines.
* Delivering pixel perfect design ready to be converted to html and css
* Develop UI mockups and prototypes that clearly illustrate how systems function and look like 
* Plan and implement new designs
* Simplify complex data presentation and architectural challenges through design
* Prepare and present rough drafts to internal teams and key stakeholders
* Identify and troubleshoot UX problems 
* Conduct layout adjustments based on user feedback
* Adhere to style standards on fonts, colors and images
* Strive to deliver intuitive and user-centered solutions
* Conduct user experience research related to ongoing product development and idea in 

### Why it would be awesome to work with us

We’re passionate about opening access to a historically exclusive marketplace to an ever broader customers, we’re relentlessly building a system, so intuitive that customers with innovative and quality driven minds will easily get their appetite satisfied through our product and services. Join our growing team consisting of intelligent individuals with market research, product development, IOT fanatics, and systems enablers. Also, below are some captivating benefits provided:

* 13th monthly salary
* Social Insurance, Health Insurance & Unemployment Insurance applied
* Annual company trip, monthly team-building activities and happy hours
* Well-functioning and latest computer with up-to-date tools is provided
* Young and dynamic teams working in exciting technologies in an international and multidisciplinary environment
* Stable and solid company, with some opportunities to develop some technical and leadership skills, get responsibilities, and grow within the organization

### Contact
Homepage: https://elek.vn/
Trollman: arnaud.douezy@smartec.com.vn

**Comment by rebyn** [comment]
What does `IOT` (`IOT-oriented working environment`) mean?

**Comment by Dawensky** [comment]
> What does `IOT` (`IOT-oriented working environment`) mean?

It means **Internet of Things**
