### ISSUE TITLE
[HCM] Fullstack Developer (.NET & Angular 2+)

### ISSUE THREAD

**Issue by HelenVo** [awesome-jobs/vietnam#1392]
## Location

* CMT8 Street, District 10, Ho Chi Minh City, Vietnam
* Fulltime
## Salary Expectation

* Negotiate

## Requirements
* Experience in .NET Core and Angular 2+ frameworks
* Proficiency in MySQL and SQL language
* Familiar with various design and architectural patterns
* Optimization of the application for maximum speed and scalability
* Experience working with agile methodologies
* Implementing automated testing platforms and unit tests
* Proficient understanding of code versioning tools (Git) and continuous integration
* Working knowledge of English
* Good interpersonal and communication skills
* Self-motivated, independent, committed
 
### Responsibilities

* Translate application storyboards and use cases into functional applications
* Design, build, and maintain efficient, reusable, and reliable front-end and back-end code
* Ensure the best possible performance, quality, and responsiveness of applications
* Identify bottlenecks and bugs, and devise solutions to these problems
* Help maintain code quality, organization, and automatization
* Work in close-knit team to deliver exciting new products
* Conduct testing (unit, integration, performance…)
* Research and recommend new technologies

### Contact
Email: thuyduong@9cv9.com
Skype: vothithuyduong0396

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
