### ISSUE TITLE
[HCM] Mobile Developer (Ionic Framework)|| up to $1400

### ISSUE THREAD

**Issue by HelenVo** [awesome-jobs/vietnam#1393]
## Location

* CMT8 Street, District 10, Ho Chi Minh City, Vietnam
* Fulltime

## Salary Expectation

* $1000-$1400/month

## Requirements
* Have at least 2 years experience in Mobile Hybrid.
* Good experience on Mobile App life cycle: app state, user behavior,...
* Trouble shooting
* Debugging
* Familiar with development tool for Hybrid and native platform: XCode, Android Studio
* Good exp working with server side team to handle request, response
* Have exp on Websocket
* Be able to communicate in English.

### Contact
Email: thuyduong@9cv9.com
Skype: vothithuyduong0396

**Comment by qcam** [comment]
@HelenVo Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
