### ISSUE TITLE
TOPICA - 13 FUTURE CTOs - HN - FT

### ISSUE THREAD

**Issue by tran196dat** [awesome-jobs/vietnam#1399]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* $1,500 - $3,000

## Requirements
* PHP, Java, Ruby on Rails, Python, .NET
* 5+ years Software Engineering experience

### Ideally

* Experience with HTML5, CSS, JS

### Responsibilities

Will be disscuss at the interview

### You’ll be responsible for

New tech products

### Contact
Tran196dat@gmail.com
Title: [Topica] - Full-name

**Comment by rebyn** [comment]
This arguably might be the worst job post I've seen in a while.

**Comment by qcam** [comment]
@tran196dat Please checkout README and make sure the post conform to the format.

I like your job title being creative, but a more informative version would be more appreciated.
