### ISSUE TITLE
MrQuan - Customize Discourse - Hanoi/Remote - C

### ISSUE THREAD

**Issue by muctau191** [awesome-jobs/vietnam#140]
Hi guys!
I am looking for a freelancer to customize the Discourse - https://github.com/discourse/discourse
Forums demo: https://meta.discourse.org/
I need to customize the discourse in two main factors:
- Modify the existing tagging-plugin
- Make the Main-Categories and Sub-Categories selectable in different fields when posting like when choosing Categories from the homepage.
  I would pay as much as you want to cover the time you spend and other things related.
## Location
- Hanoi (preferred)
- Remote
## Salary Expectation
- Negotiable
## Requirements

Discourse is built With
- Ruby on Rails — Our back end API is a Rails app. It responds to requests RESTfully in JSON.
- Ember.js — Our front end is an Ember.js app that communicates with the Rails API.
- PostgreSQL — Our main data store is in Postgres.
- Redis — We use Redis as a cache and for transient data.
## Skills
- Experience with Ruby
### Must Have
- Have sufficient knowledge about Discourse installing and how to create a Plugin for Discourse
### Responsibilities

Great power comes with great responsibilities!
### Contact
- muctau191@gmail.com 
- Skype: muctau191

**Comment by joneslee85** [comment]
@muctau191 are you sure about Lotus as the requirement?

**Comment by muctau191** [comment]
I actually do not understand what you mean :(

**Comment by joneslee85** [comment]
In your description you wrote:

```
Requirements

Ruby
**Lotus Framework**
PostgreSQL
```

Do you have any idea what you wrote or you just blindly copy & paste?

**Comment by muctau191** [comment]
@joneslee85 I have just modified the job description. You seem to be very expert and have huge of relationships. Please help :(

**Comment by joneslee85** [comment]
@muctau191 please share this job post again in #job room
