### ISSUE TITLE
Tripath Vietnam - Front-End Developer - Hanoi - FT

### ISSUE THREAD

**Issue by dattran105** [awesome-jobs/vietnam#1400]
## Location

* De La Thanh, Dong Da Street, Hanoi

## Salary Expectation

* Up to $1,500

## Requirements

* ReactJS/AngularJS/VueJS 
* Experience with designing and interacting with RESTful APIs & API authentication schemes
* Experience with using VUE.js/ AngularJS/ ReactJS on at least 1 production project
* Proficient understanding of Git
* Follow best practice conventions and project structure
* DRY code

## Skills

* JavaScript
* ReactJS/AngularJS/VueJS 

### Ideally

* Experience with 1 year experiences

### You’ll be responsible for

* Build educational management system
* Write reusable web components
* Enhance and refactor your code on a daily basis
* Participate in team discussion and code reviews

### Why it would be awesome to work with us

* Attractive salary & bonus + 13th salary policy
* Full labor insurance (social, health, unemployed) and personal healthcare
* Daily various foods, drink, and seasonal fresh fruits;
* Chance to work in Korea
* Young, dynamic, open, friendly working environment

### Contact

Homepage: tripath.vn
Email: trandat.1005@gmail.com
Subject: Tripath- FE - Your Name

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.

Please also be noted that we do not accept jobs from recruiting agency.
