### ISSUE TITLE
fram^ - Senior Backend Developer - HCMC - FT

### ISSUE THREAD

**Issue by vabbyn** [awesome-jobs/vietnam#1401]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* Microservices, RESTful-services and Principles
* Docker and one of the big clouds (AWS, Azure, Google)
* Fluent in English (both written and spoken)
 
### Must Have

* Golang or Two other different languages (Java, C#, Python, Ruby, etc)
* Microservice/Cloud/Docker
* English

### Ideally

* Experience with Golang

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* In charge of building up in Backend side of the product
* Daily working & collaborating with onshore team in Sweden

### Why it would be awesome to work with us

We are passionate individuals that are driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals who have a desire to build something new and actively support our young company in its growth to greatness.

### What we offer you

* Excellent and competitive salary package with 13th monthly salary and a good long‑term and performance bonus
* 5-day working week (Monday-Friday) with working hours to some extent flexible & remote working up to 5 days/months
* More annual leaves than Vietnam’s Labor Law (Swedish national day, Christmas Eve & your Birthday) and will increase by working years
* Vietnamese standard health insurance plus extra Premium health care package
* Friday Beer time combined with Technical Sharing & extra team-building activities every week
* Quarterly Meetings & Parties are held where our B.O.D will share about achievements, missions & visions of fram^ for mutual transparent and committed growth
* Professional and open working environment, with the culture and office of a Scandinavian online company in the heart of Ho Chi Minh city
* Opportunities to improve English skills within an international team – English is an official language in fram^ office. Also regular English lessons once per week by native English instructor in the office
* Self-development courses including technical & non-technical programs are offered
* Opportunities to gain hands-on experience in cutting-edge technologies
* Opportunities to become one of the key members of fram^ as we build this fast growing company together!
* Guaranteed permanent employment and career development.

### Contact
Homepage: www.wearefram.com
Email: thanh.vo@wearefram.com
Skype: vnghthanh (Ms.Thanh)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
