### ISSUE TITLE
FinOS - Business Intelligence (BI) Analyst - Saigon - FT

### ISSUE THREAD

**Issue by chuajiesheng** [awesome-jobs/vietnam#1403]
## Location

* Saigon, Vietnam preferred
* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* Bachelor’s degree in Business Administration, Finance, Economics, Computer Science, Data Science, Engineering or other related fields
* Significant experience in a senior role in Finance, Operations, or other related fields
* Expert working knowledge on SQL and/or similar tools to perform data querying, building data models and conducting data analysis.
* Exceptional visualisation skills using Tableau, Qlikview or other relevant visualisation tools.
* Exhibits sound business judgment, a proven ability to influence others, strong analytical skills, and a proven track record of taking ownership, leading data-driven analyses, and influencing results
* Strong written and verbal communication skills, with a track record of presenting to senior management
* Effective self-starter who excels in a lean and fast-paced organisation

## Skills

* SQL, Tableau, Excel, ...

### Must Have

* Fluent in English and Vietnamese
* Bachelor’s degree in Business Administration, Finance, Economics, Computer Science, Data Science, Engineering or other related fields

### Ideally

* Good understanding of different types of databases and their relevant use cases
* Working experience in the financial industry
* Experience in conducting data mining studies and employing machine learning
* Experience working within a high-growth, technology company is highly beneficial
* Experience working on AWS is a big plus

### Responsibilities

* Create, develop and own the APAC BI reporting and analytical environment
* Collaborate with the Data Engineer on the design, development and maintenance of data models
* Lead the development and provision of BI reporting through the deployment of self-service reports and dashboards
* Lead the development and provision of advanced analysis through the use of classical statistical and machine-driven techniques
* Maintain thorough knowledge of existing and emerging open source and proprietary BI and advanced analysis tools

### Why it would be awesome to work with us

FinOS is the definitive platform for financial services that powers digital financial products & services across Southeast Asia. We pave the way to provide financial support to the unbanked through simple, affordable and tech-enabled financial products & services. 

In this role, the Business Intelligence (BI) Analyst serves as the primary bridge through the business to communicate high-value information to support data-driven decision-making demands. He/she will continuously evolve management reporting, conduct complex data analysis and deliver business insights in an environment of rapid growth and increasing complexity.

The successful candidate must be able to roll up his/her sleeves and work directly with very large data sets and BI tools. He/she will be passionate about their work, detail-oriented, highly analytical and have excellent problem-solving skills.

### Contact
Wan Ting / Jie Sheng (JS)
Email: poh.wan.ting@finos.asia / chua.jie.sheng@finos.asia
Telegram https://t.me/joinchat/AuYbJhVGdt2l7bTSahsUcg

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
