### ISSUE TITLE
FinOS - Data Scientist - Saigon - FT

### ISSUE THREAD

**Issue by chuajiesheng** [awesome-jobs/vietnam#1404]
## Location

* Saigon, Vietnam preferred
* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* Master's or Bachelor’s degree (with at least 3 years of experience), in Computer Science, Electrical/Computer Engineering, Operations Research or Mathematics/Statistics
* Understanding of machine learning, deep learning, data mining, algorithmic foundations of optimization
* Past and current experience writing and speaking about complex technical concepts to broad audiences in a simplified format
* Ability to develop experimental and analytic plans for data modelling processes, use of strong baselines, ability to accurately determine cause and effect relations
* Experience with machine learning framework (scikit-learn, Spark MLlib etc)
* Proficient in one or more of the following programming languages: Python, R, Scala.
* Experience in building ML models at scale, using real-time big data pipelines on platforms such as Spark/MapReduce
* Familiar with NoSQL, postGIS, stream processing and distributed computing platforms
* Self-motivated, independent learner, and willing to share knowledge with team members
* Detail-oriented and efficient time manager in a dynamic and dynamic working environment
* Strong written and verbal communication skills, with a track record of presenting to senior management

## Skills

* Python, R, Statistic, Spark, SQL, ...

### Must Have

* Fluent in English and Vietnamese
* BS or MS degree in computer science or equivalent field.
* 2+ years Software Engineering experience

### Ideally

* Working experience in the financial industry
* Experience working within a high-growth, technology company is highly beneficial
* Experience working on AWS is a big plus

### Responsibilities

* Work with product owners and business development team to define hypotheses, develop and execute necessary tests, experiments, and analyses to prove or disprove them
* Translate data speak to human speak by effectively conceptualizing analysis to team members and business stakeholders
* Build, validate, test, and deploy machine learning models (e.g. predictive, forecasting, clustering) using proven and experimental techniques. Deploy an online learning model where applicable

### Why it would be awesome to work with us

FinOS is the definitive platform for financial services that powers digital financial products & services across Southeast Asia. We pave the way to provide financial support to the unbanked through simple, affordable and tech-enabled financial products & services. 

FinOS’s Data Science team works on some of the most challenging and fascinating problems in the financial industry. We foster a culture where we enjoy raising the bar constantly for ourselves and others, and that strongly supports the freedom to explore and innovate. If you have a strong passion for data science and machine learning, excited to develop complex machine learning models and feel strongly about communicating effectively with product owners, come talk to us!

### Contact
Wan Ting / Jie Sheng (JS)
Email: poh.wan.ting@finos.asia / chua.jie.sheng@finos.asia
Telegram https://t.me/joinchat/AuYbJhVGdt2l7bTSahsUcg
Skype live: chuajiesheng@outlook.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
