### ISSUE TITLE
5 Full stack Web Developers (For Japan Product Company)

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#1405]
## Location

* Hanoi, Vietnam

## Salary Range

* 600$ - 1600$

## You’ll be responsible for
* Work on both front-end & back-end of web application
* Work with database of 40,000,000 images & 1,300,000 users world wide
* Involve in all stages of developing E-commerce platform for selling and buying licensed images, video... for Asian Market 
* Search & study about new technologies to actively propose solutions for web application improvement

## Requirements
* Have Web Development base and be good at one of the OOP Language programmings (Ruby, Python, Java, C++)
* Be familiar with software/web development based on Unix/Linux
* Have English proficiency at working level
* Possess self-learning skill, team work skill and good attitude

## Work with Pixta, you can learn
* Programming language: Ruby, Node.js, Python 
* Frameworks/ Libraries: Ruby on Rails, React,..
* Database: MySql, DynamoDB, Redis,  ...
* Infrastructure: Amazon Web Services  (EC2, S3, DynamoDB,SQS, ECS…), ElasticSearch,
* Tools: GitHub, Trello, CircleCl, ..

## Benefit Package
* Salary: 600$ ~ 1600$ + up to 2 months bonus at the end of year
* Allowance: Lunch & parking
* Modern facilities: Laptop, screen
* Opportunities to build up work experience, acquire new skills from teams of multinational talents
* Chance to have business trip to Japan each year
* Internal activities: Annual company trip, monthly company party, regularly health checkup and lunch allowance, special health insurance, Code Camp, Code Contest
* Working environment: open, dynamic and respected that encourages innovation, transparency and idea sharing (seminar, book reading...)
* Working time: 5 working day, no compulsory 

## Contact
Email: recruit.vn@pixta.co.jp
Web page: https://pixta.vn/
Fanpage: Pixta Vietnam (https://www.facebook.com/pixtaVN/)

**Comment by qcam** [comment]
@VanPham289 Could you provide more information about the company and the position? Thank you. Also please make sure all mandatory sections are filled.

**Comment by trungnvfet** [comment]
Cool
