### ISSUE TITLE
Python- GoLang - NodeJS - Senior Back End or Full-stack Software Engineer (Full time)

### ISSUE THREAD

**Issue by prohle** [awesome-jobs/vietnam#1409]
Our agile team is always looking for more talents to join us on a full-time basis. Apply today if you are interested. We look forward to meeting with you. 

## Bonus
We also provide generous referral bonus if you find us a fit candidate. Referrer will receive $500 for each successful candidate placement.

## Location
* Remote or on-site (Hanoi)

## Salary Expectation

* Depends on Experience (generally $1000 and above)

## Must Have at least 2 of the following
Experience in creating bidding real-time system
Experience in real-time reporting system
Experience in real-time instant messaging
Experience in building algorithms for data acquisition and traffic analytics
Experience in setup payment gateway

## Requirements
1.	Languages:  Go/golang, Python, Javascript(NodeJS)
2.	Framework: Express, RESTful API with Django, Scrapy, SocketIO
3.	Database: PostgreSQL, Redix, NoSQL, Cassandra
4.	Operating System: Linux/Ubuntu
5.	Version control with Git
6.	Storage: Azure Microsoft, AWS S3, etc.
7.	Security/ network: Complex distributed development and testing
8.	Sync and Asynchronous REST programming
9.	Microservices with RabbitMQ or the like

### Ideally
* Nice to have: Project management skill: Ability to manage a team of 4-10 developers.
* Nice to have: Deep learning, machine learning, image processing

### Responsibilities

Great power comes with great responsibilities!

### Must have
Demos

### You can bring

* A good eyes for design
* A good analysis skill

### Contact
Please send attached your resume and contact information to
teamprotechhr@gmail.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.

Please also be noted that we do not accept posts from recruiting agencies.
