### ISSUE TITLE
TrustCircleGlobal - Full-stack Developer - Saigon - FT

### ISSUE THREAD

**Issue by tkhieu** [awesome-jobs/vietnam#141]
Supporting a team with world-class founders, world-class investors and a gigantic global market of 3.5 trillion USD is such a rare chance. We invite you to participate in such an opportunity right in the middle of Ho Chi Minh City.

TrustCircle is looking for a grounded, reliable, and skillful engineer who want to succeed with us and commit to building solid operational software tools for the whole team. To do this, we want you to join us wholeheartedly like all other members of the team. In return, we will provide you with the best supports and resources to succeed in your taking.

Positions: **Full-stack Engineer**

Location: **151 Ton Dat Tien, SB - 02, Garden Court View 1, District 7, Ho Chi Minh City**

**Responsibilities:**
● Support existing internal software tools.
● Participate in the development of new web-based products.
● Design and implement new internal tools based on requests from Business Team.  
● Be able to work with Business Team to prioritize requests which make the most sense to business goals.
● Others tasks assigned by Operating Officer

**Qualifications & Skills:**
**In general:**
● Be studious, committed to result, reliable, pay attention to details.
● Be comfortable with Project Management tools
● Be clear communication.
● Be comfortable with English in technical reading and writing

**Front-end:**
● Be fluent in JavaScript (especially React), and demonstrably good knowledge of HTML5 and CSS3.
● Experienced in creating responsive, intuitive websites accessible from mobile, tablet and desktop
● Had Previous experience with ES6, SASS and Flux, Redux
● Be proficient in JavaScript testing frameworks (Jasmine, Mocha, etc.)
● Be Interest in always being up-to-date with the latest IT trends and technologies
● Expose to architectural patterns of a large, high-scale web application
● Be fluent in HTML5, CSS, and JavaScript

**Back-end:**
● Be skillful with Python. 
● Experienced in setting up, optimizing, scaling and maintaining a database of both SQL-like and non-SQL
● Experienced in setting up, optimizing, scaling and maintaining a web-server

**Benefits:**
We will do our best to make sure you are motivated, happy, healthy, and productive. Followings are the few things that we will do:
● Being challenged to build solid operational software tools for the whole team. 
● Have opportunities to work with other A-level engineers.
● Competitive salary: to make sure you are able to maintain a comfortable living for you and your
loved ones.
● Motivated stock plan: which will make you well off when the company succeeds.
● Health insurance: to make sure you will not be worried about you or your loved ones get sick.
● Onsite laundry dropoff and pickup: make sure you always look good and clean without spending
much time and effort.
● Financial support for self-study.
● Potential trip to US to attend technical conferences: we want our people to be at the cutting edge of the tech world.
● The list can go on, but the bottom line is: we want you to succeed with us, and we are willing to go far and beyond to make it happen.

**Contact:**
If you are compelled about what we mentioned above, please contact us with your CV at huynh.nguyen@trustcircleglobal.com , you will be glad you do.

**Comment by trankimhieu** [comment]
Hi @joneslee85 . Help me review it and labeling. Thanks so much. This position is a bit urgent.
