### ISSUE TITLE
Graphical Engineer/ User-interface/ User-experience Designer

### ISSUE THREAD

**Issue by prohle** [awesome-jobs/vietnam#1411]
Our agile team is always looking for more talents to join us on a full-time basis. Apply today if you are interested. We look forward to meeting with you.

## Bonus
We also provide generous referral bonus if you find us a fit candidate. Referrer will receive $500 for each successful candidate placement.

## Location
* Remote or on-site (Hanoi)

## Salary Expectation

* Depends on Experience ($800 and above)

## Requirements
1.	Design beautiful advertisement templates and user interface for internal and external clients/projects

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Awesome interface & icons & promotion clips

### You can bring

* A good eyes for design
* A good analysis skill

### Contact
Please send attached your resume and contact information to
teamprotechhr@gmail.com

**Comment by qcam** [comment]
Same as #1409.
