### ISSUE TITLE
Lecle Vietnam - Front-end Developer - HCMC - FT

### ISSUE THREAD

**Issue by ynhilengo** [awesome-jobs/vietnam#1416]
## Work Location
* 3 Nguyen Luong Bang Street, District 7, Ho Chi Minh City, Vietnam
* Full-time Job

## Salary
* $600 - $2000 Gross/month 

## Job Description
We are seeking for Front-end Developers to join our growing development team in launching our Blockchain product called Cryptobadge. 

## Requirements
* 1+ years of experience
* In-depth knowledge of HTML5, JavaScript/ReactJS and CSS3
* Solid understandings of Web Technologies: HTTP, AJAX, RESTful API
* Ability to adapt to web frameworks and implement them in ongoing projects
* Understanding of how Scrum and Agile work
* Profound understanding of Version control systems (Git)
* Eagerness to grasp new technologies and programming languages

### Why it would be awesome to work with us
Lecle provides you with the opportunity to take ownership of your work, get exposure to the latest technologies and developments, and work on interesting and challenging problems while building a Blockchain product. In addition, our company would be a great fit for you if you prefer start-up culture!

**_Let's have a look at some perks we have for you at Lecle:_**
- We allow flexible working time from 7AM - 9AM 
- Macbook Pro provided
- 13th-month salary + year-end bonus 
- 15 days of annual leave per year
- Performance review twice a year
- Onsite opportunity in Korea every three working years
- Events & activities: company trip at least once a year & company dinner once or twice a month
- Other benefits such as holidays and insurance benefits will follow Vietnam laws
- Free snack, coffee and other drinks 

### Contact to apply
* Email: career@lecle.co.kr
* Phone: 028-5416-5548
* Recruiter: Nhi Le - Skype: ynsecretgil

### Know more about us
Website: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam
Facebook: www.facebook.com/LecleVietnam

**Comment by nhbduy** [comment]
Dear **LECLE Vietnam**,
 
I am very interested in applying for the **_Front-end Developer position_** you advertised on _ITViec_ and _Github_ recently. My qualifications and experience match your specifications almost exactly.
 
Please take a moment to review my profile as the link below: [My CV](https://drive.google.com/open?id=1hDn-ngg3Kqk1ebnLjalOXoTak4pqsdex)

It would be a sincere pleasure to hear back from you soon to discuss this exciting opportunity.

Sincerely,
Duy NGUYEN

**Comment by ynhilengo** [comment]
> Dear **LECLE Vietnam**,
> 
> I am very interested in applying for the **_Front-end Developer_** position you advertised on _ITViec_ and _Github_ recently. My qualifications and experience match your specifications almost exactly.
> 
> Please take a moment to review my profile as the link below: [My CV](https://drive.google.com/open?id=1hDn-ngg3Kqk1ebnLjalOXoTak4pqsdex)
> 
> It would be a sincere pleasure to hear back from you soon to discuss this exciting opportunity.
> 
> Sincerely,
> Duy NGUYEN

Hi Duy Nguyen,

We have received your CV and will contact you soon. Thank you for spending your time on your application and your interest in our job opportunity.

With best regards,
Nhi Le.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
