### ISSUE TITLE
Lecle Vietnam - Back-end NodeJS Developer - HCMC - FT

### ISSUE THREAD

**Issue by ynhilengo** [awesome-jobs/vietnam#1417]
## Work Location
* 3 Nguyen Luong Bang Street, District 7, Ho Chi Minh City, Vietnam
* Full-time Job

## Salary
* Up to $2000 Gross/month 

## Job Description
LECLE is building a Blockchain platform for communities, aiming to decentralizing every community called Cryptobagde. We are looking for many Back-end Developers to join us in this project.

As a Back-end Developer at Lecle, you are responsible for product quality. Our job position would be a great fit for you if you like to make great products, and especially if you have a passion for learning and applying cutting-edge technologies to make a good product in reasonable time.
Let’s have a look at our stack:
- Blockchain (EOSIO)
- Javascript (NodeJS, ReactJS)
- Serverless backed by AWS, GraphQL, DynamoDB
- Docker

## Requirements
- 1+ years of experience in the related field
- Ability to adapt to web frameworks and implement them in ongoing projects
- Good task management skill
- Familiarity with common design patterns and OOP techniques
- Solid understanding of Web Technologies: HTTP, AJAX and RESTful API
- Understanding of how Scrum and Agile work
- Understanding of the fundamentals of data structures, algorithms and networking protocols
- Profound understanding of Version control systems (Git)

## Why it would be awesome to work with us
Lecle provides you with the opportunity to take ownership of your work, get exposure to the latest technologies and developments, and work on interesting and challenging problems while building a Blockchain product. In addition, our company would be a great fit for you if you prefer start-up culture!

**_Let's have a look at some perks we have for you at Lecle:_**
- We allow flexible working time from 7AM - 9AM 
- Macbook Pro provided
- 13th-month salary + year-end bonus 
- 15 days of annual leave per year
- Performance review twice a year
- Onsite opportunity in Korea every three working years
- Events & activities: company trip at least once a year & company dinner once or twice a month
- Other benefits such as holidays and insurance benefits will follow Vietnam laws
- Free snack, coffee and other drinks 

### Contact to apply
* Email: career@lecle.co.kr
* Phone: 028-5416-5548
* Recruiter: Nhi Le - Skype: ynsecretgil

### Know more about us
Website: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam
Facebook: www.facebook.com/LecleVietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
