### ISSUE TITLE
Persol Vietnam - Technical PM - HCM - FT

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#1418]
## Location

117 - 119 Ly Chinh Thang St, Dist. 3, HCMC

## Salary Expectation

Up to $3,000

## Requirements
* Have strong knowledge about JAVA or PHP or C#.
* At least 4-years experience in software development.
* Strong written and verbal communication English skills.
* Japanese language: ~N2

### Ideally

* Candidates who have worked in Japan or have experience working with Japanese partners is prioritized.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Manage changes to the project scope, project schedule.
* Manage a schedule to ensure work to be identified, assigned and completed on time.
* Analyze, clarify and transfer requirements to members.
* Participate in making design documents, test cases.
* Manage the relationship with the client by excellent communication.

### Why it would be awesome to work with us
* Performance review 2 times per year.
* Global, friendly environment. 
* Care programs: Wedding, Close family pass away, Giving Birth, Premium Insurance.
* Free drinks: Coffee, Tea & Beer.
* Leave paid: Summer holiday, Company birthday, Annual Leave (max 24 days).
* Employee relationship: company trip, monthly team building.
* Working time: 8:30 AM – 11:30 AM and 12:30 AM – 5:30 PM from Monday to Friday.

### Contact
Homepage: https://www.persol-group.co.jp
Email: huykhanh.tran3108@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
