### ISSUE TITLE
Fetch Technology - Full-stack Developer - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1420]
## Location

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2000.

## Job Description
Our client is a digital lending company that is revolutionizing access to financial products for millions of emerging consumers in Indonesia. They have developed the first digital data-driven credit underwriting and risk assessment platform to process consumer loan applications and determine their creditworthiness using its mobile app.
Established in late 2016, they deployed its lending platform in Jakarta and surrounding cities, and they are about to enter a hyper-growth period. Expansion to the rest of Indonesia is expected to complete within a year. Our client is based in Jakarta and is backed by leading venture capital firms in Indonesia and Singapore. They are looking for a Senior Software Engineer with CAN-DO attitude to build systems that leverage massive amount of data to drive the company financial products ready for nationwide scale.

## Skills Requirements
  * Highly skilled in developing, testing, debugging, and troubleshooting with any of these programming language: Python, Node.js, and Golang. Especially for building backend services.
  * Highly skilled in developing, testing, debugging, and troubleshooting with any of these programming language: Vue, Angular, or similar. Especially for building web clients.
  * Highly skilled in designing complex real world database structures and storing, managing, and analyzing large amount of data in SQL.
  * Highly skilled in all kinds of development tools that brings source code in a text file to running code in production.
  * Experience in agile development process and applications such as Trello.
  * Engineering/Computer/IT degree with 3 to 5 years of diverse software development experience and teams.
  * Great team player, have excellent work ethics, and have solid technical communication skills in English.
### Nice to have:
  * Developing, managing, testing, debugging, and troubleshooting containerization tools, especially Docker and Kubernetes.
  * Can communicate in Indonesian.

## Why it would be awesome to work with us

  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
@VyVy07 Thanks for posting. Please correct me if I'm wrong but we only accept posts for in-house positions.
