### ISSUE TITLE
Fetch Technology - Senior Android Developer - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1421]
## Location

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Competitive and commensurate with experience.

## Job Description
Our client is building a fintech project that aims at creating a chat platform with integrated real-time financial data and bots. They are looking for a Senior Android Developer who will be responsible for developing their Android app, focusing on quality and making sure their users have the best experience with product.
In addition, you will be working in a fast-paced and demanding environment, that requires a lot of interaction with diverse internal teams to explore and make improvements on the product.

## Skills Requirements
  * BS/MS degree in Computer Science or related field.
  * Must be a “True”, well versed, Android App Developer.
  * Have 4+ years of experience in Android App Development.
  * Good at English and communication skills.
  * Played a significant role in at least one Android app deployed to Google Play store.
  * Able to implement compelling user experiences with average support from dedicated experience designers.
  * Broad knowledge of the Android toolset, including Android Studio, NDK, SDK.
  * Have knowledge of Kotlin is a must.
  * Able to lead and build the team and be able to train non-Android developers how to code in Kotlin.
  * Ability to keep up with Android Releases and closely follow the evolution of Android.
  * Awareness of the latest features/changes of Android.
  * Prior experience evolving an App through Android SDK updates.
  * Experience with open source projects/3rd party libraries and how to leverage them.
  * Working knowledge of the general mobile landscape, architecture, common design patterns, trends and emerging technologies.
  * Solid understanding of the full mobile development lifecycle.
  * Experience with at least one source control tool, preferably git.
  * Self-starter and highly independent thinker, able to work well with others.
### Nice to have:
  * Prior experience rapidly integrating apps with MQTT/MQTTS- based micro services, including network programming and associated standards.
  * Familiarity with Android product design and Zeplin tool.

## Why it would be awesome to work with us
  * MacBook for work.
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, and well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Full Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
@VyVy07 Thanks for posting. Please correct me if I'm wrong but we only accept posts for in-house positions.
