### ISSUE TITLE
Fetch Technology - Python Developer - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1422]
## Location

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2000.

## Job Description
Our client is a fintech Singapore start-up that builds a smart messaging app for traders/retail investors by simplifying information sourcing and sharing with bots to save time and trade better. They are looking for a backend developer who has experience in Python background. You will be working with a team to build backend services cater to our mobile frontend. You will have a chance to be part of a team to bring our app from MVP to production ready.

## Skills Requirements
  * 1+ years of Python development experience.
  * Understanding of OOP.
  * Experience in using message bus framework.
### Nice to have:
  * Experience in Django and Flask.
  * Experience in building/designing chat system.
  * Have worked in a team who released production app before.
  * Experience in designing technical solution that uses message bus like RabbitMQ, Solace.

## Why it would be awesome to work with us
  * MacBook for work.
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, and well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Full Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy Hour every day, Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
@VyVy07 Thanks for posting. Please correct me if I'm wrong but we only accept posts for in-house positions.

**Comment by VyVy07** [comment]
Hi there,

I think there might be a mistake here. I am not sure about the “in-house
position” that you mentioned ealier. Could be please explain to me more
about it?
Thank you!

Best regards,
Vy Ha.

**Comment by qcam** [comment]
Hi, at the moment we only accept job posts submitted by the HR personnels who work at the company, that's hiring, not recruiting agencies.

Would the hired working for Fetch Technology or for the clients you mentioned in the post?
