### ISSUE TITLE
Framgia Inc. - iOS Developer - Hanoi/Ho Chi Minh City/Danang - FT

### ISSUE THREAD

**Issue by blien1994** [awesome-jobs/vietnam#1429]
## **LOCATION**

* Hanoi: Keangnam Landmark 72 Tower, Nam Tu Liem, Hanoi
* HCMC: Nice building, 467 Dien Bien Phu Str., Binh Thanh district, HCMC
* Danang: FHome Building, 16 Ly Thuong Kiet Str., Hai Chau district, Da Nang 

## **BENEFITS**

* 600 - 1500 USD (full salary on probation)
* Lunch + transportation allowance
* Premium healthcare insurance

## **WHY IT WOULD BE AWESOME TO WORK WITH US**
* Dynamic and young working environment, full of challenges that can enhances your skills to the next level
* A large pantry with free foods and drinks
* Various interesting hobby clubs for you to discover

## **REQUIREMENTS**
* At least 1 year working experience with iOS
* Strong knowledge about C/C++/Objective-C/ Swift
* Strong knowledge about data structrures, algorithm, design pattern, OOP, OOD
* Experience with Agile method

## **CONTACT**
Ms Lien 
Skype: live:do.bichlien
Email: do.bich.lien@framgia.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All `REQUIRED` sections must be filled.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
