### ISSUE TITLE
LARION - Quality Control (Manual) - HCMC - FT 

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1430]
## Location

* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $600 - $800

## Requirements
* At least 2 year experience in testing
* Good English skills to understand specifications (in English)
* Has basic knowledge in the testing concept
* ISTQB/ ISEB Foundation level or equivalence
* Independence to work in assigned testing tasks
* Execute test, analyze the issues, and propose the solution/ method to improve the system
* Understand and Experience to work in different software development process (RUP, Agile)
* Being good in designing Test cases which are clear, organized by applying the testing techniques
* Have knowledge of Automated Testing is a plus
* Able to read & well understand English materials, transfer information from visual to text in English and handle normal English verbal conversation in both life and work related

### Responsibilities
* Study customer requirements, acceptance criteria, software requirement specification, design (if any, customer constraints on the conduct of test to identify test requirement)
* Develop test plan user requirements, based on risk, importance/ using frequency of requirement/ function
* Define testing method, exit criteria and measurement for test, considerations, resources and conditions for performing test
* Create test cases (test condition, scenario, expected result)
* Review test plan, test cases
* Conduct test based on test cases and/ or test scripts, log defects and create test report
* Analyze change requests and update test documents (Test plan, test cases,…)
* Coordinate with Developer team during testing activities
* Initiate work-flows, processes, guidelines, template for better performance and management
* Do other tasks requested by Project Manager

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
  Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
* Skype: chrisnow111015
* Email: [recruitment@larion.com](mailto:recruitment@larion.com)
* Phone: (028) 37154153
[https://www.facebook.com/LARIONSolutions/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
