### ISSUE TITLE
LARION - Senior Java Developer - HCMC - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1431]
## Location

* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* Negotiation

## Requirements
* More than 5 years of experience in software development
* Java based web services
* Relational Databases, SQL and ORM
* J2EE framework
* Object Oriented Analysis and Design
* JSP
* EJB (Enterprise Java Beans)
* XML,X query, XSL
* Test-Driven Development

### Responsibilities
* Design, implement and maintain java application phases
* To take part in software and architectural development activities
* Conduct software analysis, programming, testing and debugging
* Identifying production and non-production application issues
* Transforming requirements into stipulations
* Develop, test, implement and maintain application software
* Recommend changes to improve established java application processes
* Develop technical designs for application development
* Develop application code for java programs

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
  Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
* Skype: chrisnow111015
* Email: [recruitment@larion.com](mailto:recruitment@larion.com)
* Phone: (028) 37154153
  [https://www.facebook.com/LARIONSolutions/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
