### ISSUE TITLE
LARION - NodeJS Technical Lead - HCMC - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1432]
## Location
* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $2000 - $3000

## Requirements
* At lest 6 years of working experience in Software Development
* 4+ years Experience is must in designing solution for Social Network or eComerce Platforms.
* 1+ years Experience is must in these technologies: Node.js, Apache Cassandra, Apache Kafka, RabbitMQ, ElasticSearch, PostgreSQL.
* Good working knowledge of these programming languages: JavaScript, TypeScript.
* Good experience of architecting and implementing softwares with micro-services architecture under big data context.
* Experience driving the growth of technical skills within the team & excellent problem solving skills.
* Excellent English communication skills both written and verbal.

## Skills
* Node.js
* Apache Cassandra, 
* Apache Kafka 
* RabbitMQ
* ElasticSearch 
* PostgreSQL.

### Responsibilities
* Develop and evolve Technical Strategy & Roadmap.
* Develop & Define Architecture and Design a Complex Distributed System.
* Specify, propose and present innovative solutions and lead high-quality end-to-end and design.
* Prototype, evaluate and recommend the most suitable platform.
* Collaborate closely with development team and scientific advisor to generate ideas and creative solutions to problems.
* Review all critical functionality & test code. Help Teams in removing bottlenecks.
* Great power comes with great responsibilities!

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
* Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
Skype: chrisnow111015 (Mr. Quân Lê)
Email: recruitment@larion.com
Phone: (028) 37154153
https://www.facebook.com/LARIONSolutions/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
