### ISSUE TITLE
LARION - NodeJS Developer - HCMC - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1433]
## Location
* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $1700 - $2000

## Requirements
* Strong proficiency with JavaScript, newer specifications of ECMAScript and TypeScript
* Knowledge of Node.js and frameworks available for it such as Koa.js, Express.js and Socket.io
* Understanding the nature of asynchronous programming and its quirks and workarounds
* User authentication and authorization between multiple systems, servers, and environments
* Integration of multiple data sources and databases into one system
* Good experience with RESTful APIs and WebSocket APIs
* Understanding fundamental design principles behind a scalable application and microservice architecture
* Creating database schemas that represent and support business
* Experience with DevOps processes and tools such as Jenkins, Docker, Vagrant and Kubernetes is a plus

## Skills
* JavaScript
* Node.js
* Koa.js
* Express.js
* Socket.io

### Responsibilities
* Writing reusable, testable, and efficient code
* Design and implementation of low-latency, high-availability, and performant services
* Implementation of security and data protection
* Integration of multiple backend solutions such as Redis, Apache Cassandra, Apache Solr and Apache Kafka

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
  Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
* Skype: chrisnow111015 (Mr. Quân Lê)
* Email: [recruitment@larion.com](mailto:recruitment@larion.com)
* Phone: (028) 37154153
  [https://www.facebook.com/LARIONSolutions/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
