### ISSUE TITLE
 Toripu - Frontend Web Developer - HCMC - FT 

### ISSUE THREAD

**Issue by jessie-toripu** [awesome-jobs/vietnam#1434]
## Location
We are currently looking for an office space, but we will be located near or within District 1/2 of Ho Chi Minh City.

## Salary Expectation
* US$700 to US$1500+, depends on expected salary and experience.

## Requirements
- Proven track record of delivery of complex projects to build high-performance, high-reliability web services
- Familiarity with the whole web stack, web protocols, and web performance optimization techniques
- In-depth understanding of web frameworks
- Proficient understanding of the HTTP protocol
- Hands-on experience with network diagnostics, network analytics tools
- Basic knowledge of Search Engine Optimization process
- Strong analytical skills
- Prior experience of a travel based product startups is a plus.
- Passion for learning new things, solving challenging problems.

### Must Have
- Proficient with Javascript
- Solid Understanding of HTML5/CSS3, jQuery, and Responsive Design
- Detailed knowledge of minimum one modern JavaScript framework: React, Ember, Angular, Ruby on Rails, etc
- Ability to Get Stuff Done!
- Communication and presentation skills in English is a MUST, other languages are advantage

### Ideally
- Able to build websites from scratch using Rails/ ReactJS/ Laravel/ etc.
- Able to maintain websites and implement security and data protection.
- Have experience in integrating external libraries/ SDKs e.g. payment.
- Have some experience in business intelligence and data analytics.

### Responsibilities
- Design, build & manage web apps that impact millions of users in travel
- Ensure web apps are responsive on mobile and cross-browsers
- Design and implement RESTful APIs
- Build and deploy modern web applications e.g. React, Redux, Webpack, ES6, Flow and Typescript
- Deal with data visualisation and presentation
- Architect efficient and scalable backend systems
- Identify and resolve performance and scalability issues
- Implementation of security and data protection
- Contribute to the evolution of the technology, product and experience
- Communicate, collaborate and work effectively across cross-functional teams in a global environment

### You’ll be responsible for
- Building and maintaining Toripu websites
- Building and maintaining CRM/CMS

### Why it would be awesome to work with us
- No overtime. We respect work-life balance.
- We keep sustainable pace by working standard 8 hour days from Monday to Friday, ensuring we only plan for what we can achieve.
- We value your commitment, ensuring biannual salary review based on your performance and results.
- We are a group of collaborative, driven, fast paced, innovative and passionate people.

### About Us
We are building Asia’s new, exciting and upcoming travel app. We connect travellers and drivers to bring better and more enjoyable travel experiences. We are planning to build web apps and mobile apps for our product.

The team in Vietnam is estimated to have 20+ manpower, including tech, business and finance teams.

At Toripu Pte Ltd, we are collaborative, driven, fast paced, innovative and passionate. We are looking for passionate people to join the pioneer team and lead their respective fields. 

Moreover, we believe in taking good care of our employees especially those with good working attitude. We value people who can get things done. Work hard, play hard. 

### Contact
Homepage: toripu.com
Toripu: contact@toripu.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
