### ISSUE TITLE
Employment Hero - Junior/Fresher Developer - Saigon - FT

### ISSUE THREAD

**Issue by phatle** [awesome-jobs/vietnam#1435]
## Location
🌇Cach Mang Thang 8, Viettel Complex Building, District 10, Ho Chi Minh. [See map](https://www.google.com/maps?q=285%20Cach%20Mang%20Thang%208,%20Viettel%20Complex%20Building,%20District%2010%20Ho%20Chi%20Minh)

## Salary Expectation
500 - 1,500 USD/month 💰 💵

## The Job
- Research and learn new technologies 📖🚀🔬
- Assist in the development of new platform features and enhancements ⛵️💪😋 
- Undertake rotations within our senior development team 🐣🐛🐝

## Your Skills and Experience

- Will be a natural problem solver who can analyse the situation from many different angles 💥🗿
- Will have strong English communication skills - (written and speaking) 🙊📝
- Solid understanding of data structures and algorithms 🔭 💪🔬 
- An open mind and willingness to learn   😇 :octocat: 📚
- Basic competency in several programming languages 📜📋
- Current Git/Uni projects or portfolio  📄 📃 📑
- Currently studying Computer Science, Maths, Engineering or similar  🏆 🏢

### Why You'll Love Working Here

**Here is a list of the awards we won in 2018:** 🏆🎉🌻🚀
- LinkedIn Top 25 Startups 2018
- EY Entrepreneur of the Year National Finalist 2018
- Deloitte Technology Fast 50 2018, ranked # 12 in Australia
- HRD Gold Medalist – Human Capital Management Systems 2018
- HRD Gold Medalist – Rewards and Recognition Service Provider 2018
- Dynamic Business Top 10 Entrepreneurs, our CEO Ben Thompson ranked # 2
- HRD Rewards and Recognition Employer of Choice 2018

**We also have a great range of perks:** 😱💸🍺
- Free lunch / Drinks every working day 
- 20 annual leave days 
- Parking fee funded by company 
- Birthday celebration - Annual health check 
- Life and Health Care Insurance (for your family).
- A dedicated MacBook Pro and large monitor 
- USD 500/ annual/ person for books/ tech conferences/courses 
- USD 500/ annual/ person for English learning

### Contact
Homepage: https://employmenthero.com
Trollman: gigi.phuong@employmenthero.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
