### ISSUE TITLE
Mega Blocks - Vuejs Developer - Saigon - FT

### ISSUE THREAD

**Issue by KhanhLy2510** [awesome-jobs/vietnam#1436]
## Location

* Saigon, Vietnam
* 10 District

## Salary Expectation

* Up to 800 - 1500

## Requirements

* Bachelor’s Degree in Computer Science or any related discipline preferred
* At least 2 years’ experience as a frontend developer.
* Strong experience in Vuejs and TypeScript.
* Good experience with some of these technologies such as Bootstrap, JavaScript/jQuery, HTML5 and CSS3

### Must Have

* Understanding of server-side CSS pre-processing platforms, such as LESS and SASS
* Familiarity with package management tools like Webpack, NPM, Browserify
* Excellent Teamwork, communication, and interpersonal skills
* Experience in mobile, trading or financial system is a big advantage

### Responsibilities

* Work with team members to design architect the next generation social trading crypto platform and blockchain toolsets.
* Develop user interface components
* Build reusable front-end libraries for future use
* Ensure the technical feasibility of UI/UX designs
* Peer code review and designs.
* Provide best practices, coding convention and code coverage guidelines.
* Work with QA to achieve 100%unit test and test automation. Work with QA to achieving high code coverage.
* Collaborate with other team members and participate in cross-functional groups
* Basic understanding of financial system, crypto currency and decentralised systems.

### Why it would be awesome to work with us

* Above-market salary and bonuses (13th salary bonus, 100% salary in probation period)
* Weekly happy hours, drinks and snack
* Fun and active team activities
* Modern, open and comfortable working environment
* Creative and friendly colleagues, enthusiast and supportive management
* Working from 9:00 to 18.00 Mon to Fri

### Interesting Engineering Projects

* We commit building advanced technology projects around the world in various fields such as transportation, crypto-currencies, blockchain technology.

### Contact

* Skype: nkl251096
* Email: ly.nguyen@megablocks.io

**Comment by qcam** [comment]
Same as #1437.

**Comment by KhanhLy2510** [comment]
@qcam Thanks for your feedback. I have made changes, please review.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
