### ISSUE TITLE
Mega Blocks - QA/QC/Tester - Saigon - FT

### ISSUE THREAD

**Issue by KhanhLy2510** [awesome-jobs/vietnam#1437]
## Location

* Saigon, Vietnam
* 10 District

## Salary Expectation

* 800-1500

## Requirements

* Bachelor’s Degree in Computer Science, IT or any related discipline preferred
* Excellent skill in Software Testing Life-Cycle.
* Experience in testing web/mobile apps- trading or financial systems
* At least 1 year of experience as a QA/QC/Tester in web and mobile apps.

### Must Have

* Excellent Teamwork, communication, and interpersonal skills
* Good to have experience testing micro services on Amazon Webservice (AWS)
* Good at english ( writing and reading)
* Testing Financial application and blockchain and crypto currency related products are highly advantageous.

### Responsibilities

* Create and execute test plans and testing strategy.
* Log, Track and Report bugs in Bug Tracker efficiently and timely
* In charge of quality of all department/products: backend, web app and mobile app
* Manage release process.
* Smooth communication with developers to support bug fix verification.
* Participate pro-actively in all team activities, such as Bug Bash, Milestone review and Daily Stand Up.

### Why it would be awesome to work with us

* Above-market salary and bonuses (13th salary bonus, 100% salary in probation period)
* Weekly happy hours, drinks and snack
* Fun and active team activities
* Modern, open and comfortable working environment
* Creative and friendly colleagues, enthusiast and supportive management
* Working from 9:00 to 18.00 Mon to Fri

### Interesting Engineering Projects

* We commit building advanced technology projects around the world in various fields such as transportation, crypto-currencies, blockchain technology.

### Contact
* Skype: nkl251096
* Email: ly.nguyen@megablocks.io

**Comment by qcam** [comment]
@KhanhLy2510 Thanks for posting. Could you please give more information about the position and the company? Also please make sure to fill out all required sections in [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format).

I'll keep this post down until things are addressed. Thanks.

**Comment by KhanhLy2510** [comment]
@qcam Thanks for your feedback, I have made changes. Please review.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
