### ISSUE TITLE
TINYpulse - Full Stack Developer (All Levels) - Saigon - FT

### ISSUE THREAD

**Issue by harley** [awesome-jobs/vietnam#1438]
![](https://cloud.githubusercontent.com/assets/19971922/16145378/71ae83c0-34a2-11e6-9694-3b97e45380dd.jpg)

TINYpulse is a mature startup with offices in Seattle (US) and Saigon (Vietnam). Our products help leaders at 1500+ companies, from small to large, grow happy and high performing employees. 

_Now in 2019, we're making many hires again and we hope you join a new cohort of talented and passionate engineers._

## Location

* Saigon, Vietnam

## Salary 

* $1000-$5000 matching experience and skills (based on our Career Path)
* Company stock options and health insurance/fitness benefits

## Requirements

* You want to be the best programmer you can be.
* You believe in writing tests, unit or integrated.
* You know Ruby or can pick up Ruby fast because you're already a polyglot.
* You love ORM but you are not afraid to look at raw SQL queries.
* You believe that fixing bugs is great to learn and hate making the same mistake twice.
* You know or can be trained on Agile methodologies fast
* You want to learn as much as you can from others, and want to share knowledge with others.
* [Senior] You love solving hard problems, such as re-architecting the application to support new features that the old assumptions no longer apply.

## Responsibilities

* Apply yourself to one or more engineering responsibilities in your team: develop and test new features, maintain and improve current system, upgrading systems, reducing technical debt, extracting modules, improving security, document your work, and contributing to open source when opportunities arise.
* Grow according to the career path at TINYpulse, from needing guidance to being able to self manage to being proactive to go the extra mile to contributing to technical leadership.

### A few basic bits on the environment you will be working in:

* About 50 people in Vietnam, who make up the product team that uses a mix of Scrum and Kanban
* About 60 people in Seattle working on sales, marketing and customer success
* Sharp, motivated co-workers in a fun, beautiful office environment with an amazing view of Saigon and the river

### Benefits

* Free laptop (Macbook Pro/ Window) that fits your need. iOS, Android testing devices.
* Unlimited vacation policy; work hard and take time when you need it.
* Full medical inpatient & outpatient/ dental/ maternity package to fit your and your spouse's' needs.
* All benefits followed Vietnamese labour law, including 13th month salary.
* Unlimited snacks & drinks in our bar, mini parties biweekly, followed with big events quarterly.
* Opportunity to travel to U.S. Build product that companies around the world are using to improve their employee's happiness.
* Training opportunities: continuing development of technical, soft skills, and English through both internal and external classes

### Contact

Attach your resume in our [application form](https://hire.withgoogle.com/public/jobs/tinypulsecom/view/P_AAAAAADAABIKTPK_Z8U6Ni) and submit.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
