### ISSUE TITLE
Lecle Vietnam - iOS Developer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1439]
## Location
* District 7
* Saigon, Vietnam

## Salary Expectation

* From $400/month

## Requirements
* 0-2 year of experience in related field
* Have knowledge of Objective-C or Swift.
* Have knowledge of XCode, iOS SDK,  Interface Builder, Storyboards and AutoLayout
* Experience in Version Source Control (Git)

## Why it would be awesome to work with us
Lecle provides you with the opportunity to take ownership of your work, get exposure to the latest technologies and developments. In addition, our company would be a great fit for you if you prefer start-up culture!

### Profits
* Macbook Pro provided
* 13th-month salary + Year-end bonus
* 15 days of annual leave
* Company trip at least once a year & company dinner once or twice a month
* Other benefits such as holidays and insurance benefits will follow Vietnam laws
* Free coffee, drinks and snack

### Contact
Phone: 028-5416-5548
Email: career@lecle.co.kr

### Know more about us
Facebook: www.facebook.com/LecleVietnam
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
