### ISSUE TITLE
KitFe - Ruby on Rails developer - Hồ Chí Minh - FT

### ISSUE THREAD

**Issue by TaPhuocHai** [awesome-jobs/vietnam#144]
Bạn là một developer `ruby on rails` và thích sự `linh động`, muốn `làm việc tự do`, không ép buột về thời gian, làm việc ở quán cafe, v.v.. 
Hãy tham gia với KitFe. Chúng tôi đang cần 1 vị trí như vậy.
## Yêu cầu

⁃ 1 năm kinh nghiệm ruby on rails

⁃ Từng làm qua javascript frontend như angular js, react frontend

⁃ Có kinh nghiệm về bootstrap

⁃ Điều kiện: làm việc fulltime tại HCM

⁃ Chủ động trong công việc
## Quyền lợi

⁃Thời gian làm việc linh động.

⁃Lương thỏa thuận (500->900$)

Không cần CV. Gởi thông tin ứng tuyển về mailto: `phuochai@kitfe.com`
hoặc
skype: `phuochai8x`

**Comment by joneslee85** [comment]
@TaPhuocHai bài post không hợp lệ về format, xin đọc kỹ lại README.

Bài post sẽ bị xoá nếu không có thay đổi trong 24h

**Comment by joneslee85** [comment]
Vẫn chưa hợp lệ ở cái title, xin bạn bỏ cái chữ `tuyển 1 developer` đi, tốt nhất bắt chước các bài post trước

**Comment by quocnv** [comment]
:+1:

**Comment by cks2pks** [comment]
:+1:
