### ISSUE TITLE
LARION - C/C++ Developer - HCMC - FT 

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1441]
## Location
* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $1200 - $2000

## Requirements
* Bachelor degree in Computer Science, Electrical Engineering or related fields, from an outstanding
university. Master degree is a plus.
* Minimum two years’ work experience in a technology or financial company
* Good knowledge on data structures and algorithms
* Possess core technical skills, including the following:
    ** C/C++ (required)
    ** UNIX/Linux (required)
    ** Python (desirable)
    ** Database Administration/Programing (desirable)
    ** Knowledge/experience in generic programming and algorithms (STL/boost) (desirable)
* Experience in working with financial market data is a plus
* Be dedicated and self-disciplined with a strong work ethic and be willing to help others
* Be proactive and possess good communication skills within a global team environment

### Responsibilities
* Process and analyze financial market data
* Build software systems that manage huge amount of data efficiently and can facilitate effective quantitative analysis and research, develop utility tools that can further automate the software development, testing and deployment workflow 
* Provide technical support on data related issues for global researchers, including diagnosing root causes of technical problems and proposing solutions for developers 

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
  Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
* Skype: chrisnow111015 (Mr. Quân Lê)
* Email: [recruitment@larion.com](mailto:recruitment@larion.com)
* Phone: (028) 37154153
  [https://www.facebook.com/LARIONSolutions/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
