### ISSUE TITLE
BETTER LIFE tech - 05 Dev for E-commerce Project - backend Ruby [Ho Chi Minh]

### ISSUE THREAD

**Issue by hakudang** [awesome-jobs/vietnam#1443]
## Location
* P.12, Tan Binh, HCM, Vietnam

## Salary Expectation
* $1200-2500/month or range

## Requirements
* Ruby
* Ruby on Rail Framework 
* mySQL
* 1+ years Software Engineering experience

## Skills
HTML, CSS, JavaScript
Ruby (Ruby on Rails)
PHP, Java, dotNet are advantages
MySQL, ...
English (reading comprehension)
Japanese is the advantage ... level from N5-N1

## Remuneration
Income: 1,200 - 2,500
13 month salary
Considering a 1-year salary increase (10%)
OT mode, reaching target bonuses
There are social insurance - health insurance - unemployment insurance
Vacation 12 days, Travel, 5 days/week
Level of Macbook for SE senior

### Contact
Mr. Đặng Bá
Homepage: http://betterlifejp.com/
email: s.haku@betterlifejp.com (skype: dangba1111)

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All `REQUIRED` sections must be filled.
