### ISSUE TITLE
AXON - Senior Manual QA Engineer - HCM - FT

### ISSUE THREAD

**Issue by nnguyenaxon** [awesome-jobs/vietnam#1445]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam
 
## Salary Expectation
* Competitive
 
## About Axon
 
![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)
 
Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 
 
We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 
 
Early in 2017, Axon acquired Misfit Computer Vision team and now we are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.
 
Come work in an exciting environment in which you’ll use your passion, experience, and strong analytical skills to help bring new technologies to public safety and leave a positive impact on the world. We cultivate an environment that favors agility, initiative, and creative thinking. Our mission is to protect life, making the world a safer place through smart devices and software services. We genuinely love what we do and are looking for others who share this passion.

Our team has responsibility to provide testing services for multiple projects. We are now searching multiple QA Engineers who have passion in testing, creative thinking, carefully and dare to challenge yourself.
 
## Requirements
 
*Have minimum 5 years’ experience in software testing across a wide variety of applications and infrastructure components, QA processes, test management and automated testing tools.
*Solid understanding of software QA methodologies, tools and processes
*Experience in API testing (using SoapUI, Postman or similar)
*Familiarity with version control, bug tracking (Jira), and CI / CD systems (Teamcity or Jenkins).
*Strong communication skills in English and Vietnamese.
*A passion for quality.
 
### Ideally

*Experience in Automation testing (using Selenium or Appium) is a plus
*Programming skills (Java, Python) is a plus
*Ability to collaborate, make questions and communicate directly with colleagues in US.

### Responsibilities
 
You will work closely with our talented team in Vietnam and US which you will be assigned to:
*Review requirements, specifications and technical design documents to provide timely and impactful feedback
*Develop and execute a manual test strategy where appropriate
*Use exploratory testing techniques to discover and prevent issues
*Produce detailed reports documenting test results and process to be provided to the *Product/Project Manager and QA Manager
*Track defects and issues using JIRA and participate in regular sprint and release planning sessions with the development team
*Implement and improve existing QA processes
 
**Your Impact**

Participate in planning, estimating and prioritizing processes to ensure successful execution of testing activities for all projects, you will help us continually improve the quality of our existing products.

### Why it would be awesome to work with us
 
*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired
 
### Contact
 
Apply: https://bit.ly/2IpJnxi
or contact: Hien Ha (hha@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
