### ISSUE TITLE
AXON - Senior Front-end Software Engineer - HCM - FT

### ISSUE THREAD

**Issue by nnguyenaxon** [awesome-jobs/vietnam#1446]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam
 
## Salary Expectation
* Competitive
 
## About Axon
 
![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)
 
Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 
 
We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 
 
Early in 2017, Axon acquired Misfit Computer Vision team and now we are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.
 
Our team is solving some of the hardest cloud challenges today. Every day we manage petabytes of video from hundreds of thousands of police officers around the world, and help the public with creative solutions from the courtroom to public disclosure. Come work in an exciting environment in which you use your passion, experience, and strong analytical skills to help bring new technologies to public safety and leave a positive impact on the world.
 
## Requirements
 
* 5+ years of experience in frontend / full-stack software engineering
* Ability to write clean and concise code
* Deep understanding of frontend technologies
* Ability to work within an existing codebase
* Good sense of design
* Knowledge of CS fundamentals
* Ability to explain core frontend principles and technologies to other engineers
 
### Used Technology

* Javascript
* Lerna
* Webpack
* Babel
* React + Redux
* Flow
* Jest + Enzyme
* PostCSS
* Interfacing with Scala and Go backend services
 
### Responsibilities
 
As a senior software engineer on the Frontend Core team, you'll be responsible for building and maintaining the core frontend tools and framework used by every product team at Axon. Your day-to-day responsibilities will include defining reusable React components, defining our organization's standards and best practices, optimizing our build and test tools to maximize efficiency, and refactoring our products to improve overall quality and user experience. You will also have the opportunity to contribute to open source tools and libraries.
 
**Your Impact**
The ideal candidate for this role is someone who is good at executing on large projects, and isn't afraid to make big changes to fundamental aspects of our code. You should have a good sense of design and a strong drive to do right by our customers. As a senior engineer, you'll be expected to participate in design reviews and provide guidance for more junior team members in the form of PR reviews and general mentorship. You'll have the opportunity to make changes that benefit our customers and all other frontend engineers, so it's important to be able to explain what changes you're making and why, to make it easier for the other teams to understand.

 
### Why it would be awesome to work with us
 
*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired
 
### Contact
 
JD: https://bit.ly/2IzbBFV
Or contact: Dao Nguyen (daonguyen@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
