### ISSUE TITLE
Wonolo  Startup Company - Ruby on Rails - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by lhchanh** [awesome-jobs/vietnam#145]
Loại công việc: Toàn thời gian cố định
Số lượng cần tuyển: 5
Thời gian nộp hồ sơ: 15/01/2016
Nơi làm việc: Hồ Chí Minh
Lương : 800$-1200$ (tùy năng lực)

<h2>Nhiệm vụ: </h2>

Lập trình backend dùng ruby on rails

<h2>Yêu cầu:</h2>

<h3>Yêu cầu chung</h3>

Tiếng Anh tốt, đặc biệt về khả năng đọc hiểu thành thạo
Khả năng nắm bắt, học hỏi kỹ thuật mới nhanh
Có khả năng làm việc tự chủ và làm việc theo nhóm
Tinh thần làm việc tốt, có trách nhiệm, thái độ cầu tiến trong công việc

<h3>Yêu cầu về lập trình ruby on rails</h3>

Ít nhất 2 năm kinh nghiệm làm các dự án dùng Ruby on Rails
Ưu tiên các ứng viên có thêm một trong các kinh nghiệm sau:
Có kinh nghiệm về Javascript, CSS3, HTML5, XML, XSLT, JSON
Có kinh nghiệm về MySQL, MongoDB, PostgreSQL
Có kinh nghiệm về Linux server administration, shell script
Có kinh nghiệm về config web server trên Linux

<h2>Quyền lợi:</h2>

Thu nhập thỏa thuận tùy theo năng lực của ứng viên, cạnh tranh
Bảo hiểm Y tế, xã hội, Bảo hiểm wonolo care hàng trăm triệu mỗi năm
Các chương trình lễ hội, văn hóa, du lịch của công ty
Khóa học anh văn nâng cao
Liên hệ : todinhthi@gmail.com
skype : dinhthi1610

**Comment by joneslee85** [comment]
Tin đăng không hợp lệ với format, xin nhà tuyển dụng coi kỹ lại README.md

Nếu không có thay đổi gì, 24h sau bài này sẽ bị xoá

**Comment by joneslee85** [comment]
@lhchanh vẫn chưa hợp lệ

* cái title cái từ `Rail` không có `s` ở cuối, phải là `Rails`
* Phần nội dung hoàn toàn mất format cho header

**Comment by lhchanh** [comment]
@joneslee85 Ok chưa bạn ha. bạn có thể xoá comment cũ để tin tuyển dụng mình trong đẹp hơn ko bạn ha

**Comment by quocnv** [comment]
:+1:
