### ISSUE TITLE
AXON - Senior .NET Software Engineer Lead - HCM - FT 

### ISSUE THREAD

**Issue by nnguyenaxon** [awesome-jobs/vietnam#1450]
## Location
* 8th floor, Etown Central, 11 Doan Van Bo, District 4, Ho Chi Minh City, Vietnam
 
## Salary Expectation
* Competitive
 
## About Axon
 
![image](https://itviec.com/system/production/employers/logos/4066/axon-logo-170-151.png?1527066156)
 
Axon, an US product company, blends hardware, software, firmware, wearable technologies, artificial intelligence and innovation in one house. 
 
We strive to make the bullet obsolete and replace all police handguns with electronic devices. We also develop and manufacture in-car cameras and body-worn cameras that protect truth by capturing the scene, encrypting and watermarking the video while sending all the data up to the cloud in our SaaS platform that allows police, prosecutors, defense attorneys to view the evidence and see what happened when. 
 
Early in 2017, Axon acquired Misfit Computer Vision team and now we are expanding our investment and growing the office in all perspectives: Research & AI, Software development, Embedded & Firmware, Hardware.
 
## Requirements
 
- 5+ years of experience in software engineering
- 2+ years of experience leading software developers building customer-facing software applications
- .NET/C# expertise: C#, LINQ, WPF, WCF, WinForms, ADO.NET, Entity Framework
- SQL development (stored procedures, functions, tables, indices, optimizing queries, etc)
- Experience building complex and impactful software in a team environment
- Experience implementing an engineering process that emphasized security, availability, scalability, and operational discipline
- You have kept your engineering skills sharp so you can review your team's code, evaluate design options, and provide high-level cost estimates
- You mentored junior and senior engineers, helping them understand themselves, influence others, and advance towards their career goals

 
### Preferred Skills
 
- Experience designing and delivering high-availability, scalable cloud-based systems
- Familiarity in other languages like Java, Scala, Golang, React, Node.js
- Knowledge in creating and maintaining simple application installers, Windows services
- Experience in build and Continuous Integration tools/processes like MsBuild, TeamCity, FinalBuilder
- You have worn multiple technology hats, working on a variety of areas like back-end, front-end, client, mobile
- You have refactored aspects of a significant code base
 
## Responsibilities

- Design, write, test and maintain .NET applications with web services and client components for Windows
- Develop infrastructure for enhancing automation, scalability, performance and robustness of the platform
- Assist in developing specifications and architecture design for application systems
- Prepare prototypes to evaluate technology choices for various applications and databases
- Track your own projects and clearly communicate status and risks in team meetings
- Monitor everyday activities of system and provide required support
- Mentor and lead others by understanding requirements and delivering features

 
### Your Impact
You are a Senior .NET Software Engineer Lead with experience building high-quality scalable software applications. You have deep interest in backend and frontend technologies with excellent engineering practices. In this role you will use innovative thinking to connect our wearable devices, client applications and cloud services into a smooth end-to-end customer experience. This role will require you to think through challenges around data sovereignty and limited network bandwidth, as well as enabling hybrid workflows by connecting our cloud and on-premise offerings together.

Come work in an exciting environment where you use your passion, experience, and analytical skills to help bring new solutions to public safety and leave a positive impact on the world.
 
## Why it would be awesome to work with us
 
*  An awesome office/working environment with the latest technologies and work with top engineers in the world
*  Competitive salary and benefits including a great medical insurance plan for you and your family
* Free lunch, gym, phone stipend, parking
* Fun team activities and outings
* Flexible working hours
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired
 
### Contact
 
Apply: https://bit.ly/2BUTLXX
Or contact: Hien Ha (hha@axon.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
