### ISSUE TITLE
Mega Blocks - Golang Back end - Saigon - FT

### ISSUE THREAD

**Issue by KhanhLy2510** [awesome-jobs/vietnam#1451]
## Location

* Saigon, Vietnam
* Q10

## Salary Expectation

800 - 1500

## Requirements

1+ years experience developing Backend with Golang

### Must Have

* Go Design patterns such as composition
* Go pointers, interface, slice, map
* Go concurrency
* Profiling and Unit Test in Go
* net/http
* Go Modules
* Experience with RESTful Api, JWT
* Experience with PostgreSQL or MySQL
* Experience with AWS, Docker, etc..

### Responsibilities

* Design and develop Web service
* Design database schema
* Developing a clean and maintainable code

### Why it would be awesome to work with us

* Above-market salary and bonuses (13th salary bonus, 100% salary in probation period)
* Weekly happy hours, drinks and snack
* Fun and active team activities
* Modern, open and comfortable working environment
* Creative and friendly colleagues, enthusiast and supportive management
* Working from 9:00 to 18.00 Mon to Fri

### Interesting engineering projects

* We commit building advanced technology projects around the world in various fields such as transportation, crypto-currencies, blockchain technology.

### Contact

* Skype: nkl251096
* Email: [ly.nguyen@megablocks.io](mailto:ly.nguyen@megablocks.io)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
