### ISSUE TITLE
LARION - DevOps - HCMC - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1452]
## Location
* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $1200 - $1800

## Requirements
**Qualities critical for success**
* Enthusiasm for automation
* Ability to learn and adapt rapidly to changing conditions
* Ability to work independently as part of a global, distributed team
* Taking initiative to identify problems and propose solutions
* Attention to detail
* Good English communication skills, especially in writing

**Technical skills we need**
* Comfort and facility with Linux, especially on the command line
* Solid Python scripting ability
* A strong knowledge of SQL
* Experience with unit, integration, and QA/UAT testing processes
* Experience with, or strong desire to learn and implement CI/CD techniques
* Familiarity with Docker and Kubernetes

## Skills
* Python
* SQL
* QA/UAT testing 
* CI/CD

### Ideally
Experience an ideal candidate will have
* PostgreSQL configuration and administration
* Python web frameworks such as Django and Django REST Framework
* Open source NoSQL technologies and stream processing tools
* Experience with 

### Responsibilities
Our Company Asset Management is seeking a talented and motivated engineer to help build and support our next generation operations monitoring platform. The new platform will utilize an exciting array of technologies to enhance our technical operations and deliver new insights. We are seeking expertise in modern DevOps tools and techniques to ensure that our systems are highly available and robust to changes in our fast-moving, agile environment.

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
  Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Contact
* Skype: chrisnow111015 (Mr. Quân Lê)
* Email: [recruitment@larion.com](mailto:recruitment@larion.com)
* Phone: (028) 37154153
  [https://www.facebook.com/LARIONSolutions/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
