### ISSUE TITLE
CubiCasa - Senior Software Engineer lead (Python/vuejs) - HCM - FT 

### ISSUE THREAD

**Issue by vananh250191** [awesome-jobs/vietnam#1453]
## Location

* Saigon, Vietnam
* District 1

## Salary Expectation

* Competitive (US$2500+, depends on expected salary and experience)

## About CubiCasa

CubiCasa, a Finnish SaaS product company, market leader in Finnish real-estate marketing solutions sector and widening to global market especially US. We have been offered our service to more than 60 countries around the world with thousands of active users. We are focusing on 3D models, machine learning and AI with the passion to build the most scalable interior data understanding tech. 

The headquartered is in Oulu - a computer engineer's city. Cubicasa has offices in Helsinki, Palo Alto and Ho Chi Minh, and Hue. 

We just launched a new room scanning app and released it to App store recently. We decide to expand the develop team to strengthen our service and prepare for the challengeable future.  

## Requirements/skills (must have)
* 5+ years of experience in software engineering
* At least 2 years’ experience as a developer team lead
* Expertise: Python/Flask
* Strong experience in Vuejs and Javascript ES6 
* Familiarity with Rest APIs, AWS (Elastic Beanstalk), Postgres
* Good experience with some of these technologies such as JavaScript/jQuery, HTML5 and CSS3
* Good at english
* Good teamwork, communication, and interpersonal skills

### Responsibilities.
* Design, implement and maintain the applications for production team and clients based on existing versions: Strategic app planning, debug and define corrective actions, QA, user testing. 
* Investigate defect reports from production support and isolate their causes
* Design/architect complex web applications
* Manage a tech team
* Maintain and improve code quality by code reviews and best practices
* Communicate application requirements and design with other parties (production core development team (tech) and production) 

### Why it would be awesome to work with us
* You will play the key role to develop the team in Vietnam. Being the very first brick for our empire in Vietnam and Asia, your work will certainly have significant impacts in our success in Asia market. 
* Flexibility comes with responsibility and trust: you could work remote sometimes when you need. Flexible working hours (within reason).
* Office exchange opportunities: (Palo Alto, California, Finland). Enjoy coding with snow and Santa Claus :) 
* 100% salary in probation period
* 15+ annual vacation paid days
* Laptop/computer will be provided

### Contact
* To apply, please send your CV, together with any profile of yours (e.g. LinkedIn. GitHub) to vananh@cubicasa.com.
* About our team: https://www.cubi.casa/about/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
