### ISSUE TITLE
Employment Hero - Senior Developer - Saigon - FT

### ISSUE THREAD

**Issue by Gigitran** [awesome-jobs/vietnam#1455]
## Location
🌇Cach Mang Thang 8, Viettel Complex Building, District 10, Ho Chi Minh. [See map](https://www.google.com/maps?q=285%20Cach%20Mang%20Thang%208,%20Viettel%20Complex%20Building,%20District%2010%20Ho%20Chi%20Minh)

## Salary Expectation
2,000 - 4,000 USD/month 💰 💵

## The Job

- Developing new critical features.
- Enhancements to legacy features for our award-winning HR tech platform.
- Provide input into our technical strategy whilst being hands-on with coding, mentoring about coding best-practice and leading more junior devs.
- Learn and collaborate with some of the most highly respected Full-stack developers in Vietnam.
- This is ideally suited to someone who is passionate about overcoming complex technical challenges and is excited to join a high performing and supportive team as we move into our next period of major growth.

## Your Skills and Experience

- 2+ years experience in full-stack development - front-end, server-side and API development
- High level Object oriented programming skills
- Demonstrated experience implementing, maintaining and deploying full-stack web technologies
- Strong English speaking skills
- Bachelor degree in Computer Science of Engineering or an equivalent
- A team player that always puts colleagues ahead of yourself and has a highly adaptable and versatile approach to work.

- Bonus skills : Proven experience with any of the following would be beneficial:
  - Ruby on Rails
  - React JS
  - API development

### Why You'll Love Working Here

**Here is a list of the awards we won in 2018:** 🏆🎉🌻🚀
- LinkedIn Top 25 Startups 2018
- EY Entrepreneur of the Year National Finalist 2018
- Deloitte Technology Fast 50 2018, ranked # 12 in Australia
- HRD Gold Medalist – Human Capital Management Systems 2018
- HRD Gold Medalist – Rewards and Recognition Service Provider 2018
- Dynamic Business Top 10 Entrepreneurs, our CEO Ben Thompson ranked # 2
- HRD Rewards and Recognition Employer of Choice 2018

**We also have a great range of perks:** 😱💸🍺
- Free lunch / Drinks every working day 
- 20 annual leave days 
- Parking fee funded by company 
- Birthday celebration - Annual health check 
- Life and Health Care Insurance (for your family).
- A dedicated MacBook Pro and large monitor 
- USD 500/ annual/ person for books/ tech conferences/courses 
- USD 500/ annual/ person for English learning

### Contact
Homepage: https://employmenthero.com
Trollman: gigi.phuong@employmenthero.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
