### ISSUE TITLE
hasBrain - UI/UX Designer - Saigon - FT

### ISSUE THREAD

**Issue by vlpquynh** [awesome-jobs/vietnam#1456]
## Location

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, Saigon, Vietnam

## Salary Expectation

* Competitive

## Requirements

* Driven by Customer matrix
* Experience in designing consumer or enterprise internet products.
* Proficiency with visual design tools such as Sketch and/or the Adobe Creative Suite, Figma.
* Intimate familiarity with Design Thinking and Lean UX methodologies
* Strong experience engaging with customers to validate designs, run user tests, design A/B tests, etc.
* Have a strong portfolio that showcases your design work
* Can articulate the reasoning behind your design decisions
* Can think through user problems while understanding technical constraints

### Ideally

* Experience with bringing data to life using visualizations and interactive reporting
* Meticulous
* Able to clearly communicate technical concepts to both technical and non-technical audiences
* Positive attitude with a hunger for learning
* Ability to self-study and research, willing to learn attitude
* Like to work in an agile development environment
* Self-driven and able work well in a team
* Ability to work in areas outside of their usual comfort zone and get things done quickly
* "Do what it takes" attitude is critical
* Good verbal and written English communications skills and demonstrated experience in presenting details and resolving differences across a variety of tasks.

### Responsibilities

* Be a thoughtful, creative and user-centric designer, designing the core product experiences
* Provide creative direction to the company and our products
* Lead user research activities
* Create and lead usability tests
* Produces pixel-perfect visual design artifacts
* Work collaboratively with product managers, engineers, and others in the company to get designs implemented
* Develop design guidelines, style guide, best practices and templates
* Work with others to critique and improve the design of our products

### You’ll be responsible for

* Flat UI, Material UI

### Why it would be awesome to work with us

* Work with a product driven team of founders and developers directly to drive change
* Be exposed to our users to see the change and value you are bringing to society
* Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
* International exposure. We are a result driven international team. The core team worked in Silicon Valley, Singapore and you can expect the culture to be built on trust and results
* Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm on Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours 
* Competitive salary. Depends on how good you are. 
* Further benefits including flights, training and other living expenses while training, exchanging with other teams and liaising with clients
* Convenient office location in District Binh Thanh, Nguyen Huu Canh street with lunch and breakfast included. 
* 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
* No dress code. It’s your choice to be confident and comfortable
* Pantry area with snacks, beer and other beverages. 

### Contact
Homepage: http://www.mstage.io/ or http://www.hasbrain.com/
Email: quinn@hasbrain.com
Skype: vlpquynh

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
