### ISSUE TITLE
hasBrain - Project Management Assistant - Saigon - FT

### ISSUE THREAD

**Issue by vlpquynh** [awesome-jobs/vietnam#1457]
## Location

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, Saigon, Vietnam

## Salary Expectation

* Competitive

## Role Overall
* The Assistant Project Manager is responsible for assisting Project Manager. 
* In this role, he/she will be responsible for the administration of network and server infrastructure within all departments, planning for technology projects, managing our team of IT professionals, implementing technology security and the execution of all technology-related tasks and initiatives.
* Be able to work full-time from April 2019.

## Skills and Experiences

* Proven track record with understanding and solve complex problems. Be ready to show portfolio of technical projects that you have done. We welcome developers who want to transit to a PM role. 
* Wide range of interest in data related fields. From understanding HDFS, spark, to running kernels and the user experience that users have when running data experiments. You do not need to be an expert, we are looking for people who are naturally curious,  want to learn fast and solve challenging problems. 
* Have a clear end to end idea of the development lifecycle. Is excited about getting your hands dirty in the actual work. That may include writing test cases, talking to users to find out about the problems they face, solving the problem and coming up with processes to make sure it does not happen again. 
* Interested or experienced in Data Science

### Attitude Needed

* Meticulous
* Able to clearly communicate technical concepts to both technical and non-technical audiences
* Positive attitude with a hunger for learning
* Ability to self-study and research, willing to learn attitude
* Like to work in an agile development environment
* Self-driven and able work well in a team
* Ability to work in areas outside of their usual comfort zone and get things done quickly
* "Do what it takes" attitude is critical
* Good verbal and written English communications skills and demonstrated experience in presenting details and resolving differences across a variety of tasks.

## Responsibilities

* Provide technology strategy planning
* Integrate information technologies into the company for optimal effectiveness
* Understand current and future business goals and ongoing IT issues to ensure business success
* Develop a renewal and upgrade schedule for company software programs
* Ensure that employees are following company’s policies, information security and privacy
* Participate in recruitment, orientation and ongoing training of new IT staff
* Supervise and direct IT personnel - Testing the product

## Why it would be awesome to work with us

* Work with a product-driven team of founders and developers directly to drive change
* Be exposed to our users to see the change and value you are bringing to society
* Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
* International exposure. We are a result-driven international team. The core team worked in Silicon Valley, Singapore and you can expect the culture to be built on trust and results
* Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm from Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours 
* Competitive salary. Depends on how good you are. 
* Further benefits including flights, training and other living expenses while training, exchanging with other teams and liaising with clients
* Convenient office location in District Binh Thanh, Nguyen Huu Canh street with lunch and breakfast included. 
* 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
* No dress code. It’s your choice to be confident and comfortable
* Pantry area with snacks, beer and other beverages. 

### Contact
Homepage: http://www.mstage.io/ or http://www.hasbrain.com/
Email: quinn@hasbrain.com
Skype: vlpquynh
Click [here](https://drive.google.com/open?id=1_UUVM6fJy6Pnuyexrh4swOgM-BQKWejk) for more information.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
