### ISSUE TITLE
Grab - Back-End Engineer (Golang) - Saigon - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1458]
## Location

* MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon

## Salary Expectation

* $1,000 - $3,000

## Requirements
* Experience in coding Golang for real project
* Experience in shipping web applications to production, CI/CD flow
* Familiarity with running large scale web services; understanding of systems internals and networking are a plus
* Strong understanding of system performance and scaling
* Experience in writing good unit test

### Must Have

* Coding Golang for real project
* Possess excellent communication, sharp analytical abilities with proven design skills, able to think critically of the current system in terms of growth and stability
* Experience in shipping web applications to production, CI/CD flow

### Responsibilities

* Define and shape the fundamentals of engineering at Grab.
* Design and write maintainable code at scale
* Continuously discuss, debate with other team members to propose optimal solutions for different problems
* Maintain and monitor the systems to make sure there is no disruption in our services

### Why it would be awesome to work with us
* A culture of learning
* Free rides with Grab
* Medical coverage
* Diverse teams
* Weekly Tech talks
* High growth opportunities
* Quarterly Hackathons
* Flexible working hours

### Contact
Homepage: https://grab.careers/ or https://grab.careers/locations-vietnam
Email: cuong.vo0906@gmail.com 

![golang](https://user-images.githubusercontent.com/39041308/53716849-db771680-3e88-11e9-8bce-c21ccbb62259.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
