### ISSUE TITLE
Conera - Senior Front-End Developer - Hanoi - FT

### ISSUE THREAD

**Issue by TuanNguyennnn** [awesome-jobs/vietnam#1459]
## Location
17 Floor, HL Tower,  6/82 Duy Tan street, Dich Vong Hau ward, Cau Giay District, Hanoi.

## Salary Expectation
Negotiable

## Requirements
At least 2 years of experience in the Front-end position.
Knowledge of UI / UX and Material Design language.
Deep experience of programming Front end systems using JS Frameworks (ReactJS, Angular ..)
work.

### Ideally
Having experience as a team leader is a plus
### Responsibilities
Regularly report to the Manager and Company Leaders.
Join the company management in resource planning and planning with Team Front End.

### Why it would be awesome to work with us
Participate in large projects, set up and manage a large system, technology-oriented development orientation.
To be entitled to pay health insurance and social insurance under the Vietnam's regulation.
Join the company's benefits: rewarding holidays, Tet, annual vacation, sports, TeamBuilding.

### Contact
Homepage: http://conera.io/
Email: at.nguyen.0104@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
