### ISSUE TITLE
Data Sharma - Senior Full Stack Javascript Developer - HCMC - FT.

### ISSUE THREAD

**Issue by belinguyen** [awesome-jobs/vietnam#1460]
## Location:
Ho Chi Minh city

## Salary Expectation
$3,000 - $4,000+
(Depend on experience, but start from $3,000 / month for qualified Senior Developers)

## Requirements & Skills
• 5-7 years experience, preferably within a large company
• Strong understanding of modern JavaScript, CSS and HTML concepts
• Strong understanding of Restful API design and Swagger
• Strong understanding of Service Oriented Architectures and microservices architectures
• Expert understanding and experience with the MEAN Stack, including 3+ years experience working
with Angular and 5+ year experience working with Node.js
• Expert understanding and experience with Mongo, MySQL, and PostgreSQL and a clear
understanding of the use cases for relational and non-relational data
• Demonstrable experience and/or familiarity with React and Vue
• Understanding of front-end development (HTML, CSS/SASS, etc) with an understanding of UX/UI
design principles
• Fluency in Git, GitHub and source code management concepts
• 5+ years working in a team environment using Scrum or another agile software development process
• Experience teaching and mentoring junior developers
• Experience working in distributed / remote work teams and work environments
• Strong english skills

### What you'll do 
• Collaborate with our team in every stage of a product’s lifecycle; from planning to delivery
• Create clean, modern, testable, well-documented code
• Work within an Agile team environment with modern JavaScript technologies to develop complex web
applications
• Confidently communicate daily to understand and deliver technical requirements
• Manage your own workflow to meet the deadlines set with the team.

### You're a great fit if you:
• Have a deep understanding of designing, writing, running, maintaining and debugging applications
across the whole JavaScript stack.
• Enjoy being part of a highly collaborative, remote-friendly environment.
• Have the ability to be self-directed and be effective working independently, yet feel equally comfortable
contributing in a team environment.
• Work well with technical and non-technical people to deliver high-value results.
• Are a problem solver with a business-driven approach.

  _We’re looking for someone who can comfortably work on applications / features / user stories independently. The ideal candidate has strong skills in both front-end development (CSS, HTML, React, Angular) and backend development (API design, NodeJs services, etc.) and can take a mock-up and create a working application. The ideal fit for our team is someone who has a love for coding and learning, works well in a remote / distributed team environment and is a high-energy strong communicator who can join an expert team and work with limited direction._**

### Get to Know Us:
Data Sharma is a mission-focused technology consulting company helping organizations operating on the forefront of humanity to optimize their impact. We are on a crusade to eradicate the world from outdated technologies and bring equality to technology access, tackling challenges in 20 countries and impacting over $100 million of initiatives and 100,000 people. The problems we solve everyday are real and require creativity, grit and determination. We are building a culture that challenges norms while fostering experimentation and personal growth. We are hiring team members who are passionate and energized by the vision of using technology to solve some of the world’s most important challenges. We would love for you to join us as we strive each day to find new ways of leveraging technology and data for good

### Contact
Please send all resumes to partners@datasharma.com with the subject line ‘Senior JavaScript
Developer’. No cover letter needed – honestly, we’d just love a really candid intro email where you
describe what you are hoping to do next and why you’d be interested in working with us. We will respond to every single email – so if you haven’t heard back we are probably busy reviewing!

**Comment by belinguyen** [comment]
@qcam Could you help to add more label "JavaScript"? Thank you.

**Comment by qcam** [comment]
@belinguyen Could you please help to split these two positions into their own posts?

**Comment by belinguyen** [comment]
> @belinguyen Could you please help to split these two positions into their own posts?

@qcam Yea, i did. Thank you for supporting!

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
