### ISSUE TITLE
EAP - ASP.NET Core Developer - Remote - FT or PT

### ISSUE THREAD

**Issue by BaranOzdemir** [awesome-jobs/vietnam#1465]
## Location

* Australia, New Zealand
* Remote
* Full time or part time

## Salary Expectation

* Negotiable

## Requirements
* ASP.NET Core
* Web API
* Azure App Services, Azure Functions, WebJobs
* MS SQL
* EF Core
* 5+ years Software Engineering experience

## Skills
* Communication (English)
* Team player
* Agile

### Must Have

* Be able to fly

### Ideally

* Microservices
* Web API
* SOA
* SignalR 

### Responsibilities

Responsible for writing exceptional code to deliver world class web solutions to global customers.

### You’ll be responsible for

* Working on restful web api.

### You can bring

* A good eyes for design
* Critical thinking
* Energy

### Why it would be awesome to work with us
* We are agile
* We trust people
* We empower people

### Contact
Homepage: www.eap.ph
Contact: contact@eap.ph

**Comment by qcam** [comment]
@BaranOzdemir Thanks for posting. Is being able to fly really a must-have for this position? Also could you please provide more information about the company and the position, as well as fill out all the required sections specified in the README.

The post will remain close until all the issues are addressed.

**Comment by BaranOzdemir** [comment]
Hi,

Yes, the developers need to be able to fly to Kuala Lumpur once every 3 months for regional meetings.

I looked at the other posts and tried to provide with similar details. But yes I can add more information about the company.

I thought I filled all mandatory sections. I will check them again.

Regards
Baran

**Comment by BaranOzdemir** [comment]
Where do I put more information about the company?

**Comment by qcam** [comment]
@BaranOzdemir 

> Where do I put more information about the company?

Before "Location" section should be fine.

**Comment by zigzacvy** [comment]
How can I apply for this job?

**Comment by BaranOzdemir** [comment]
Hi,

Thanks for your email. Can you please email your resume to the following address?

contact@eap.ph<mailto:contact@eap.ph>

Regards

**Comment by zigzacvy** [comment]
Yes, I have already sent my CV, but I don't have received response form your company.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
