### ISSUE TITLE
EnableStartup - Javascript Fullstack Developer - Danang - FT

### ISSUE THREAD

**Issue by quaywin** [awesome-jobs/vietnam#1467]
## Location

* Danang, Vietnam
* Full-time

## Salary Expectation

* $700 - $1500

## The job

Enable Startup is Da Nang based company with 15 developers and designers. Enable Startup is offering outsourcing and offshore services for global clients. Most of the clients are Startup Companies in South East Asia. We are looking for creative and analytical problem-solvers to join one our growing Information Technology Team and help us continue to improve our services and processes so that our members and customers can reach their goals. As a company that heavily relies on cutting-edge IT operations to serve its clients, Enable Startup is seeking ambitious individuals with a strong team mentality and a genuine passion for software engineering. Join a company where programming design and quality is expected, appreciated, and nurtured.

### Responsibilities

* Turning designs and client requirements into the new fully functional web application.
* Building project structures and communicating it to your team.
* Working with the graphic designer, project manager, and backend teams to ensure the web application is running optimally at all times
* Communicate and report internally or directly to the client on status or result of work.
* Participate in On-board training and probation challenges

### Skills

*	2+ years experiences with front-end technologies such as React, Redux
*	2+ years experiences working with NodeJS
*	2+ years experiences working SQL and NoSQL databases
*	Have solid knowledge about OOP
*	Experience with new ES6 and Typescript.
*	Experience with the Express and Loopback framework in NodeJS
*	Experience with testing frameworks like Jasmine, Karma and Mocha
*	Experience with Git version control
*	Understanding of CI/CD
*	Strong understanding of the agile software development process
*	English communication skills
*	Teamwork

### Why it would be awesome to work with us

*	Truly a friendly working environment, focusing on personal development, training, and satisfaction
*	Clear career development path for both professional and personal growth.
*	Many opportunities to learn new technologies
*	Quarterly and annual bonus, annual health care insurance, and yearly performance review

### Contact
Homepage: https://enablestartup.com

Email: hr@enablestartup.com

Title: [Javascript Fullstack Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
