### ISSUE TITLE
EnableStartup - Junior Developer - Danang - FT

### ISSUE THREAD

**Issue by quaywin** [awesome-jobs/vietnam#1468]
## Location

- Danang, Vietnam
- Full-time

## Salary Expectation

- $300 - $600

## The job

Enable Startup is Da Nang based company with 15 developers and designers. Enable Startup is offering outsourcing and offshore services for global clients. Most of the clients are Startup Companies in South East Asia. We are looking for creative and analytical problem-solvers to join one our growing Information Technology Team and help us continue to improve our services and processes so that our members and customers can reach their goals. As a company that heavily relies on cutting-edge IT operations to serve its clients, Enable Startup is seeking ambitious individuals with a strong team mentality and a genuine passion for software engineering. Join a company where programming design and quality is expected, appreciated, and nurtured.

### Responsibilities

- Turning designs and client requirements into the new fully functional web application.
- Building project structures and communicating it to your team.
- Working with the graphic designer, project manager, and backend teams to ensure the web application is running optimally at all times
- Communicate and report internally or directly to the client on status or result of work.
- Participate in On-board training and probation challenges

### Skills

- Good IT background, critical and logical thinking skills.
- Strong background in PHP, MySQL, PHP Frameworks such as Laravel, Zend
- Being a team player with a high responsibility mindset
- Familiar with popular frontend frameworks such as ReactJS, VueJS is a big plus.
- Have knowledge of HTML/CSS, Responsive Design.
- Comfortable working with existing code and writing code from scratch.
- Familiar with source control systems (Git) is preferred.
- English: good reading & writing, basic speaking & listening.
- Teamwork

### Why it would be awesome to work with us

- Truly a friendly working environment, focusing on personal development, training, and satisfaction
- Clear career development path for both professional and personal growth.
- Many opportunities to learn new technologies
- Quarterly and annual bonus, annual health care insurance, and yearly performance review

### Contact

Homepage: https://enablestartup.com

Email: hr@enablestartup.com

Title: [Junior Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
