### ISSUE TITLE
Lecle Vietnam - iOS Developer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1469]
## Location
District 7
* Saigon, Vietnam
* Remote

## Salary Expectation

* from $400/month

## Requirements
* 0-2 year of experience in related field
* Have knowledge of Objective-C or Swift.
* Have knowledge of XCode, iOS SDK,  Interface Builder, Storyboards and AutoLayout
* Experience in Version Source Control (Git)

## Profits
* MacBook Pro provided
* 13th-month salary + Year-end bonus
* 15 days of annual leave
* Company trip at least once a year & company dinner once or twice a month
* Other benefits such as holidays and insurance benefits will follow Vietnam laws
* Free coffee, drinks and snack

## Contact

* Phone: 028-5416-5548
* Email: career@lecle.co.kr

## Know more about us
* Facebook: www.facebook.com/LecleVietnam
* Homepage: https://www.lecle.co.kr/
* Medium page: https://medium.com/leclevietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
