### ISSUE TITLE
Dinovative - UX-UI Designer (Junior) - Saigon - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#1470]
## Location

* Dinovative is looking for a great analytical and creative UX/UI Designer to get involved and drive UX across projects. You will be responsible for all aspects of UX/UI from research, to ideating, defining the experience design to perfecting the design of every screen or asset. You’ll be working in a multi-disciplinary team, collaborating and ensuring that projects are delivered in the best possible way. 

* 204 Pasteur, Ward 6, Distrist 3

## Salary Expectation

* $600 - $1000

## Requirements
* 2-3 years of digital design experience
* Experience designing for a range of platforms and devices, such as: iOS; Android; Responsive; Tablet; and Mobile.

### Must Have

* English proficiency
* Familiar with design and prototyping tools such as: Sketch; Zeplin; InVision
* Familiar with graphic design tools, specially Adobe Suite.
* Strong communication, facilitation and presentation skills.
* Excellent attention to detail.
* Analytical and strong problem solving skills. 
* Ability to produce results independently as well as collaboratively in a team environment.
* Curiosity, enthusiasm and willingness to learn.

### Ideally

* Experience designing for a range of platforms and devices, such as: iOS; Android; Responsive; Tablet; and Mobile.

### You’ll be responsible for
* all aspects of UX/UI from research, to ideating, defining the experience design to perfecting the design of every screen or asset.
* working in a multi-disciplinary team, collaborating and ensuring that projects are delivered in the best possible way.

### Why it would be awesome to work with us

* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:
* Working in dynamic, young, friendly, flexible invironment
* Laptop is provided
* 12+ days annual leaves, working Monday - Friday, flexible working time
* Attractive salary based on skills and experiences
* Salary review: Once a year, base on individual performance review
* Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy 
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding 
* Free fruits/ snacks on happy hours time
* Celebration: birthday
* Party time: Team building (frequent) and Xmas
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development 

### Contact
Email: oanh.tang@dinovative.com
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
