### ISSUE TITLE
Ecom365 - Senior Java/ Java Technical Lead - Saigon - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#1471]
## Location
* At Ecom365, we’re building the next generation ERP, supply chain solutions and e-commerce platforms for the retail and distribution industry. On a daily basis, we help our SME businesses automate their daily mundane tasks, so they can focus on what matters: sales, manage relationships with customers and suppliers. Furthermore, our SaaS platform enables those businesses to expand their operations effortlessly.
* Do you like opportunity of building and leading your own development team?
* Do you love challenges of a lead architect designing a scalable platform for millions of both corporate users and end consumers?
* Do you like a challenging, yet at the same time flexible and rewarding environment?
* 204 Pasteur, Ward 6, Distrist 3

## Salary Expectation

* $1500 - $2000

## Requirements
* At least 4-6 years working experience
* Java core
* OOP languages, data structure and functional programming
* Designing and developing REST APIs

### Must Have

* Experience with enterprise system architectures.
* Experience in database systems and data schema design (relational, semi-structured and no-structure data)
* Hands-on experience designing and developing REST APIs
* Thinking big and acting fast. You’ll need a startup mentality with enterprise awareness
* Ability to manage competing priorities
* Influential

### You’ll be responsible for

* Technical and architectural vision of our SaaS platform (backend, database, microservices, RESTFUL APIs).
* Collaboration with Design, Product Manager and QA team doing product development.
* Mentoring and recruitment of the development team
* Establishing and managing the agile development process, ultimately responsible for the technical quality of the product.
* Collaborate and organize technical support to customer facing teams.

### Why it would be awesome to work with us
* Working in a dynamic, technological environment
* Competitive remuneration packages
* All Ideas are appreciated – No barriers– No limitation
* Collaborative environment
* Designing a scalable platform for millions of both corporate users and end consumers

### Contact
Email: oanh.tang@dinovative.com
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
