### ISSUE TITLE
Toripu - Backend Developer - HCMC - FT 

### ISSUE THREAD

**Issue by jessie-toripu** [awesome-jobs/vietnam#1474]
## Location
Within/nearby District 1 of Ho Chi Minh City.

## Salary Expectation
$700 to $2000+, depending on experience, skill and expected salary.

## Requirements

- 1+ years of hands-on experience in designing, developing, testing and deploying large scale applications in any language or stack
- Your experience may be in mobile engineering, full-stack, back-end, architecture and infrastructure, web services and tooling.
- Hands-on experience working on one or more front end technologies - Web, Android or iOS - and understand their nuances
- Data modelling experience in both Relational and NoSQL databases.
- Ability to design and build highly scalable, reliable and fault tolerant systems
- Ability to optimise backend application for maximum speed, scalability and availability
- Ability to design and implement low latency and secure RESTful services. Familiar with Version Control System.
- Ability to implement security and data protection
- Working knowledge of unit testing and design patterns
- Have prior experience working in high performance or distributed systems.
- Understanding differences between multiple delivery platforms such as mobile vs desktop, and optimizing output to match the specific platform.
- Having knowledge of devops is a plus. Able to streamline and accelerate the interactions between development and operations.
- Prior experience of a travel based product startups is a plus.
- Passion for learning new things, solving challenging problems.
- Experience in Golang / Ruby a plus.
- Experience in ElasticSearch a plus.
- Experience in AWS/GCP a plus. Have experience with container technologies: CGroups, Docker, Rocket, LXC etc is a plus.
- Experience in machine learning a plus

### Must Have

- Good knowledge of data structures and algorithms.
- Build, maintain and optimise backend applications for maximum speed, scalability and availability.
- Have basic knowledge of AWS/GCP.
- Have knowledge of security and data protection measures.
- Drive for excellent engineering: Improving process and best practices.
- Passion for learning new things, solving challenging problems.
- Ability to Get Stuff Done!
- Communication and presentation skills in English is a MUST, other languages are advantage

### Ideally

- Able to design, build and maintain backend servers and database.
- Able to respond quickly to live issues on servers.
- Continuously learning and propose ways to improve backend applications for maximum speed, scalability and availability with minimal cost and minimal development time.
- Able to propose and implement security and data protection.
- Have experience in integrating external libraries or SDKs e.g. payment.
- Have some experience in business intelligence and data analytics.
- Have a basic understanding of cluster orchestrators and schedulers (Kubernetes, LXD etc)

### Responsibilities

- Integration of user-facing elements developed by a front-end developers with server side logic.
- Optimisation of backend application for maximum speed, scalability and availability
- Implementation of security and data protection
- Design and implementation of data storage solutions
- Contribute to API Infrastructure design and set up
- Respond immediately to live backend issues and fix quickly
- Contribute to the evolution of the technology, product and experience
- Quickly grasp concepts, problems and implement solutions with guidance
- Communicate, collaborate and work effectively across cross-functional teams in a global environment

### You’ll be responsible for
- Building, maintaining and secure all backend applications. Respond to live issues immediately.
- Support frontend team with implementations of server side logic,

### Why it would be awesome to work with us
- No overtime. We respect work-life balance.
- We keep sustainable pace by working standard 8 hour days from Monday to Friday, ensuring we only plan for what we can achieve.
- We value your commitment, ensuring biannual salary review based on your performance and results.
- We are open and flexible as long as you can get stuff done.

### About Us
We are building Asia’s new, exciting and upcoming travel app that connects travellers and drivers to bring better and more enjoyable travel experiences. We are planning to build web apps and mobile apps for our product.

The Vietnam team is expected to have 20+ manpower, including tech, business and finance teams.

**At Toripu Pte Ltd, we are committed, collaborative, driven, fast paced and innovative. We are looking for passionate people to join the pioneer team and lead their respective fields.**

Moreover, we believe in taking good care of our employees especially those with good working attitude and can get things done. 

> Work hard, play hard. 

> A dream you dream alone is only a dream. A dream you dream together is reality. - Yoko Ono

### Contact
Homepage: [toripu.com](toripu.com)
Email: [contact@toripu.com](mailto:contact@toripu.com) (skype:jessie.jiang_7)

**Comment by jackiedo91** [comment]
Tuyển dev toàn năng hay sao mà full option vậy @@

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
