### ISSUE TITLE
Sendo.vn - Middle/Senior NodeJS Developer - HCMC - FT

### ISSUE THREAD

**Issue by thuynguyen93** [awesome-jobs/vietnam#1484]
## Location

- District 7, Saigon, Vietnam

- Fulltime

Sendo.vn is the online marketplace of FPT Group which connects buyers and sellers around the country. Originally an e-commerce project of FPT Online JSC, Sendo.vn was officially launched on Sept 2012. On May 13rd 2014, Sendo Technology JSC was founded as a member of FPT Group and is responsible for operating Sendo.vn marketplace.

Up to now, more than 80,000 shops have been operating on Sendo.vn, offering a diverse range of products with over 5 million products from 21 different categories.

## Salary Expectation

* up to 45mil

## Requirements

- At least 2 years of strong back-end development experience.
- Experience with popular Node.js web frameworks and/or utility libraries such as Express, Koa.js, Hapi, Underscore/Lodash, Bluebird.
- Understand deeply about nonblocking I/O, socket in Nodejs
- Experience in front-end development (ReactJS) is a big advantage
- Strong proficiency in working with database systems such as MySQL, MongoDB, Redis
- Capable of developing business-critical software which involves flexibility and high productivity.
- Experience working in Agile development
- Git and Repository Management

## Responsibilities

We are looking for a Node.js Developer responsible for managing the interchange of data between the server and the users. Your primary focus will be the development of all server-side logic, definition and maintenance of the central database, and ensuring high performance and responsiveness to requests from the front-end.
- Integration of user-facing elements developed by front-end developers with server side logic
- Writing reusable, testable, and efficient code
- Design and implementation of low-latency, high-availability, and performant applications
- Implementation of security and data protection

### Why it would be awesome to work with us

- Competitive compensation package: 13th month- salary and 1-3 months bonus salary
- Performance review: 2 times/ year
- FPT Care Health Insurance
- 18 days annual leave
- Applicable for all normal benefits: insurances, annual company trip, team building activities

### Contact
Thuy Nguyen (Ms) - Recruiter
Email: thuyntt@sendo.vn
Skype: phuthuyxanh

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
