### ISSUE TITLE
ReadyTech - Mid Developer - Nha Trang - FT

### ISSUE THREAD

**Issue by rauxalach** [awesome-jobs/vietnam#1485]
## Location

* A1 Street, VCN  Building, Nha Trang, Khanh Hoa.

## Salary Expectation
800 - 1,500 USD/month

## Requirements
* 2+ years experience in full-stack development includes front-end, server-side and API development
* High level OOP skills
* Strong English verbal skill
* Ability to understand and debug large and complex code bases
* Be able to write best coverage spec.

## Skills
* Ruby on Rails
* React JS
* Postgres SQL / MySQL

### Responsibilities

* Enhancements to our legacy apps that are using by 300+ clients.
* Actively working on projects from our SOA roadmap.
* Mentoring our junior/intern devs for coding best-practice.

### Why it would be awesome to work with us

* 20 annual leave days
* Dedicated MacBook Pro
* English learning
* Tech Talk
* Be able to become Speaker at our frequent Tech Seminar at Nha Trang's universities

### Contact
Huy Le: huyl@jobready.com.au (0908.108.625)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
