### ISSUE TITLE
NFQ Asia - Senior iOS Developer (React Native) - HCMC - FT

### ISSUE THREAD

**Issue by trucvo26** [awesome-jobs/vietnam#1488]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* up to $3000

## Requirements

- You will be joining an awesome startup team to build cool applications that serve millions of users, from idea to production.
- As our customers are typically ambitious foreign startups, you will have a chance to improve your English, learn about startup culture and product mindset along the way. If you want to make a great impact on the world, this is your chance now.
- Managing full lifecycle customer projects with Agile methods.
- Developing strong relationships with customers, acting as the primary point of contact as well as managing stakeholder expectations and always seek for solution improvement.

## Skills

- Have at least 3 years of experience with React Native
- Have strong experience with iOS Native 
- Excellent experience with React/React Native Library best practices and conventions, JSX, React Component, Redux (or Mobx), Flexbox.
- Love to work, responsibility, and teamwork

**Big Bonus**

- Familiar with state/data management libraries (Redux,etc.);
- Excellent English Communication skills.
- Experience with APN, GCM
- Knowledge of software development in Agile methodologies
- Knowledge about iOS design patterns (MVVM, MVP, VIPER)
- Knowledge of some frameworks (RxSwift, RxAlamofire)

Great power comes with great responsibilities!

### Why it would be awesome to work with us

- Tech Rockstar : Apply the latest technology
- Fun-Friendly-Flexible : Professional & English speaking working environment
- Exciting Projects : Working with overseas clients and awesome projects.
- Growing Opportunity : Work with top-notch experts from around the world.

**Benefits include:**

- MacBook Pro is provided.
- A fun & dynamic environment and freedom to be creative.
- Rock in open-mind, kind & humble team.
- Modern office with the flexible relaxing zone.
- Company trip, team building & other community Tech activities.
- Year-end bonus, Loyalty bonus (up to 45,000$).
- Performance review  2 times/ year.
- Extra Medical Insurance.
- 15 days annual leaves, working Monday – Friday.

### Contact
NFQ Asia/ 8bit Rockstars
Skype: trucvo26
Email: career@nfq.asia
Phone: (028) 66812733
https://www.facebook.com/nfq.asia/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
