### ISSUE TITLE
CardPool Vietnam - Backend Developer (NodeJS, Team Leader) - HCMC - FT - up to $2K+

### ISSUE THREAD

**Issue by adam84luong** [awesome-jobs/vietnam#1489]
## Location

* Saigon, Vietnam
* Remote (work from home)

## Salary

* Highly competitive salary: up to $2K+

## Requirements
* Familiarity with common design patterns and OOP techniques
* Solid understanding of Web Technologies: HTTP, AJAX and RESTful API
* Understanding of how Scrum and Agile work
* Profound understanding of Version control systems (Git)
* Experience with Amazon API Gateway, AWS Lambda (NodeJS), AWS SQS, AWS SNS

## Skills
* NodeJS
* NoSQL
* AWS
* Javascript
* TypeScript
* Git

## Benefit

* Highly competitive salary: up to $2K+
* The company has an unlimited vacation and sick leave policy. You just need to coordinate with your manager and team to make sure there is coverage.
* Support online course fees
* Team building activities regularly

## Role Description

The team leader is responsible for leading, developing, mentoring and auditing the quality of code written by the team. The team leader is ultimately responsible for delivering the epics and working with the VN manager, Scrum Master, and team members to ensure the goals of the Epic are met.

## Responsibilities

* Create an inspiring team environment with an open communication culture
* Create the task lists for each of the epics that the team will complete
* Complete code reviews for all team members to ensure quality
* Set clear team goals
* Delegate tasks and set deadlines
* Oversee day-to-day operation
* Monitor team performance and report on metrics
* Motivate team members
* Discover training needs and provide coaching
* Listen to team members’ feedback and resolve any issues or conflicts
* Recognize high performance and reward accomplishments
* Encourage creativity and risk-taking
* Suggest and organize team building activities

## Contact
* Email: adam.luong@cardpool.com
* Skype: adam-luong

## Know more about us
* Homepage: [https://www.cardpool.com/](https://www.cardpool.com/)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
