### ISSUE TITLE
RingBlaze - Ruby Engineer - Remote - FT/PT

### ISSUE THREAD

**Issue by liemdo** [awesome-jobs/vietnam#149]
RingBlaze is a cross-platform mobile application which reinvents a better way to communicate and collaborate in business. To succeed in this role, you need to be customer focused, creative and is not afraid to take charge using your world-class skills. 
## Responsibilities:
- Write awesome code using Ruby to help the world communicate effectively.
- Help define architecture to grow our internal and external APIs.
- Proactively look for ways to improve our software to be more scalable and reliable. 
- Collaborate with a small but passionate team.
## Qualifications:
- Remote work experience
- B.S. or M.S. in Computer Science or equivalent practical experience.
- 1+ years of relevant work experience.
- Solid knowledge of Ruby.
- Good knowledge of testing frameworks such as RSpec and Cucumber. 
- Strong knowledge of full web application stack. 
- Strong understanding of application architecture, object-oriented design, database concepts and algorithms. 
## Nice to have:
- Javascript and AngularJS framework knowledge. 
- AWS stack.
- PostgreSQL knowledge.
- Working knowledge with networking and messaging protocols.

Please send your resume and desired salary to ldo@ringblaze.com

**Comment by joneslee85** [comment]
@liemdo please update the title to match our guideline.
