### ISSUE TITLE
Allied Tech Base - PHP Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by ngdangdung92** [awesome-jobs/vietnam#1491]
## Location

* Hanoi, Vietnam
* Full-time

## Salary Range

* Junior level: 500-700 USD
* Middle level: 700-1200 USD
* Senior level: 1200-1800 USD
* Expert level: Up to 2500 USD

## Job Description
- Communicate with client or supervisor to clearly user needs and business goals by using English or Japanese.
- Developing high-quality software design and architecture within detail documents.
- Identify, prioritize and execute tasks in the software development lifecycle.
- Implement programs and applications by producing clean, efficient code.
- Troubleshoot, test and maintain the core product software and databases to ensure strong optimization and functionality.
- Collaborate with internal teams and vendors to ensure product always is high performance and up-to-date with latest technologies.

## Job Requirements

**Must Have:**
- At least 3 years working with PHP
- Strong experience in Requirement Analysis, System Design, Test Design.
- Strong experience in Web Application Development using the LAMP
- Experience at least one PHP Framework (Laravel, CakePHP, Yii, Codeigniter, Symfony,…).
- In-depth knowledge of MySQL and proficient in writing, optimizing SQL query with high performance.
- In-depth knowledge of object-oriented programming and proficient in using design patterns
- Knowledge of web technologies including HTML/CSS/Javascript/AJAX etc,…
- Understanding & proficient in using code versioning tools such as Git, Subversion.
- Analytical mind with problem-solving aptitude.
- Ability to work independently.

**Nice to Have:**
- Familiar with Unix-type operating systems (e.g. CentOS).
- Ability growing up team members
- Willing to learn and share new knowledge
- Good English skills
- Good organizational and leadership skills.

## Our core expertise

Based on our principles of "Connecting People and Companies through Social Technology", we provide a variety of services supporting companies' marketing with SNS.
We support companies' marketing with high performance, through our 3 main businesses: SNS Promotion Business, Data Management Business, and Ad Technology Business.

SNS Promotion Business creates relations between companies and customers.
Data Management Business accumulates, manages, and sorts user data through our Promotion.
Ad Technology Business utilizes accumulated data as a means to SNS advertisement.

## Our culture

Accountability and responsibility. Everyone has to commit on what he/she promised.
You’re respected. It means you can make a decision on the project technical approach.
You have right to lead project/product to get success.
Tell us what you need to deliver a great job.
You need to learn hard, work hard to get success here.
You need to discuss and present your idea before coding, it’s a MUST.

## Basic benefit

Salary 13th months.
Performance and salary review every 6 months.
Regular social insurance support.
Periodical health check-up.
Extra health insurance.
Company trip (every year)
Birthday party (every month)
Happy lunch (every week)
Weekend picnic,...

### Education
Japanese training course.
Extra bonus for technical certification (1 time)
Support ticket for join technical event/seminar.
Opportunities for Japan/South Asia for business trips and technical exchange.

## Contact
Homepage: https://www.alliedtechbase.com/
Email: hr@alliedtechbase.com
Skype of hot man: ng.dangdung

**Comment by qcam** [comment]
@ngdangdung92 Please do not put salary on title. Thanks!

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
