### ISSUE TITLE
Groove Technology - .NET Developer - HCM - FT

### ISSUE THREAD

**Issue by Nguyenphong1226** [awesome-jobs/vietnam#1494]
## Location

* Saigon, Vietnam

## Salary Expectation

* $900 - $1,300/ month

## Requirements
* .NET
* C#
* Microsoft stack
* 2+ years of experience

### Must Have

* Solid front end experience with HTML5, CSS3 / SAAS, Typescript, Javascript.
* Experience creating, maintaining, optimising and writing queries for MS SQL / Postgres.
* Experience using an ORM library such as Entity Framework or Dapper.

### Ideally
* Experience integrating with 3rd party systems.

### Responsibilities
* Reporting to the Project Manager and Tech Lead.
* Liaising with the key stakeholders of the project.
* Delivering fully implemented vertical feature sets based on the specification within estimates and without defects.
* Identify and mitigate risk in the projects implementation.
* Participating in code reviews.
* Lead and mentor less senior members of the team

### You can bring

* Basic English communication skills

### Why it would be awesome to work with us
* International, dynamic, friendly working environment.
* Clear and stable career growth
* Many opportunities for personal and professional growth.
* Regular team building events, sport activities…
* Medical and Accident Insurance program
* Professional training 
* Competitive and attractive salary

### Contact
Homepage: groovetechnology.com
Email: Phong.nguyen@groovetechnology.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
