### ISSUE TITLE
Tripla - Fullstack Rails Engineer - Tokyo - FT

### ISSUE THREAD

**Issue by Vinh0305** [awesome-jobs/vietnam#1495]
## Location

* Tokyo, Japan

## Salary Expectation

* $5k – $10k / month
* Stock options: 0.01% – 1.0%

## Requirements
- Possess a good understanding of the syntax of Ruby and its nuances 
- Experience designing, building large-scale Ruby on Rails applications 
- Experience in building APIs for client facing-apps in Ruby on Rails 
- Experience in creating and maintaining scalable infrastructure leveraging modern AWS products like RDS, ElastiCache, Dynamo DB and others 
- Basic familiarity with networking systems, load balancers, and TCP/IP network constructs. 
- Experience in building micro service structure 

### Must Have
- Passion for always improving (yourself, the app, the company, etc.) 
- Ownership: You feel responsible for creating an excellent, end-to-end platform that supports the needs of our users. 
- Comfort with data: you know when you don't know enough to make a design decision, and you seek out answers. 
- An interest in exploration: you think about what to build now and what to build in 
the future. 
- Should be confident in English (for ref: >=800 TOEIC or >= 6.0 IELTS should be enough)

### You’ll be responsible for
We are looking for a Ruby on Rails developer responsible for managing the interchange of data between the server and the users. Your primary focus will be development of all server-side logic, definition and maintenance of the central database, developing micro services to support the rapid growth of services and ensuring high performance and responsiveness to requests from the front-end. You will also be responsible for integrating the front-end elements built by your co-workers into the application. 

### Why it would be awesome to work with us
- Flexible working time
- Endless challenges. We are a small team and there are tons of things to solve every day
- Remote work (3 days a week)
- Can have options to work fully remote in one month for your own time
- Compensation holidays
- We don't value you based on working time but on the quality of features you build

### Contact
Homepage: tripla.ai
Skype: vinhtt0305@gmail.com

**Comment by namtx** [comment]
@Vinh0305 is Japanese required for this postion?

**Comment by Vinh0305** [comment]
@namtx No requirements for Japanese, bro :D

**Comment by tuanbinhhai** [comment]
@Vinh0305 how can I apply?

**Comment by Vinh0305** [comment]
@tuanbinhhai Hi, please drop me a message via my Skype :)

**Comment by Vinh0305** [comment]
@qcam Would you mind adding `Visa Sponsor` label for this Job? Thank you

**Comment by namnguyentat** [comment]
@Vinh0305 Job hịn quá :)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
