### ISSUE TITLE
Tripla - Frontend Engineer (Vuejs, Reactjs) - Tokyo - FT

### ISSUE THREAD

**Issue by Vinh0305** [awesome-jobs/vietnam#1496]
## Location

* Tokyo, Japan

## Salary Expectation

* $5k - $10k/month
* Stock options: 0.01% – 1.0%

## Requirements
* HTML5 & CSS3
* VueJS, ReacJS or any of modern Javascript frameworks
* Web Technologies

### Must Have

* Exceptional understanding of front end development skills 
* Experience on building web apps with Vue.js or other modern JS frameworks (React/Angular) 
* Familiarity with browser testing and debugging 
* Passion for always improving (yourself, the app, the company, etc.) 
* Ownership: You feel responsible for creating an excellent, end-to-end platform that supports the needs of our users. 
* Comfort with data: you know when you don't know enough to make a design decision, and you seek out answers. 
* An interest in exploration: you think about what to build now and what to build in 
the future. 
* Experience working with style guides. 
* A solid perspective on how users engage with chatbot.

### You’ll be responsible for
We are looking for an exceptional senior frontend engineer with strong frontend skill to build our next generation AI chatbot platform for hospitality industry. The ideal candidate would have great problem solving and communication skills and be comfortable with fast paced design, development and deployment in an agile environment. You should have extensive experiences on web application development and used Vue.js and Rails(optional). We are looking for smart, innovative thinkers to help us solve the complex challenges of building innovative service. 

### You can bring
You’ll help brainstorm, scope and build a wide range of products. You will leverage your frontend development expertise to build products that will have high impact to our business. 

People who do well on our team are self-motivated engineers with a passion for both the business and technology innovation. We look for individuals with deep knowledge of JavaScript framework (Vue.js/React/Angular), CSS, and HTML who are comfortable writing custom JavaScript but also know when to apply off-the-shelf solutions for the problem. We also value people who are passionate about user experience and have an eye for improving the service.

### Why it would be awesome to work with us
* Flexible working time
* Endless challenges. We are a small team and there are tons of things to solve every day.
* Remote work (3 days a week)
* Can have options to work fully remote in one month for your own time
* Compensation holidays
* We don't value you based on working time but on the quality of features you build

### Contact
Homepage: tripla.ai
Skype: vinhtt0305@gmail.com

**Comment by Vinh0305** [comment]
We found an awesome FE guy 🏆

**Comment by nnluukhtn** [comment]
Congrats anh @Vinh0305

**Comment by Vinh0305** [comment]
Thanks @nnluukhtn 💃
