### ISSUE TITLE
Junior Golang

### ISSUE THREAD

**Issue by VanCami** [awesome-jobs/vietnam#1499]
## Good to have:
* Familiar with Golang, TypeScript
* Experienced with Docker & AWS
* Experienced with the complete life cycle of application development: design, implementation, test,deployment & maintenance
* Can communicate in English as you will work with people across teams
## Must to have:
*Competencies in algorithms, data structures & basic concurrent programming
*Be highly responsible, take ownership over your works, work independently with minimum
supervision, and be a lifelong learner with a positive collaborative attitude
*Familiar with test driven development
*Experienced in developing a couple of mobile applications

##Apply on : ntVan.cami@gmail.com

**Comment by qcam** [comment]
Hi, thanks for posting. Please make the post conform to our requirements in README. The post will be closed until all the requirements are met.
