### ISSUE TITLE
Tinkerbox - ROR Engineer - HCM - FT

### ISSUE THREAD

**Issue by Rosedao03** [awesome-jobs/vietnam#150]
## Company

Tinkerbox Studios Pte. Ltd. is one of the most well known development house in Singapore. We provide Ruby on Rails development and user experience design services.
At Tinkerbox, we help your business realize value through our core service offerings in UX Design, Agile Web Development and Business Solutions

Website: http://www.tinkerbox.com.sg/
Facebook: https://www.facebook.com/tinkerbox/
## Location

HCMC, Vietnam
## Salary

$1000-1500
## Requirements
- 3+ years experience with ROR
- Helpful and responsible
## Benefits:
- Project bonus
- Free lunch
- Free English training
- International working environment with talented colleagues.
## Contact

Rose Dao: rose.dao712@gmail.com

**Comment by joneslee85** [comment]
Please check the title format, it does not comply with our guideline
