### ISSUE TITLE
TEKO Vietnam - Backend Developer (Python/Golang) Up to Senior - HCM - FT

### ISSUE THREAD

**Issue by NhatBM** [awesome-jobs/vietnam#1500]
# Location

* Saigon, Vietnam
* Hanoi, Vietnam

# Salary Expectation

* Up to 2000$!!

# Requirements
-  Able to work independently, withstand pressure and complete assigned tasks on time
-  Enthusiastic, careful, accurate, patient, honest, willing to learn and open to experience
- Ensure company’s information and database security
- Total experience in programming: at least 3 years
- Total experience in server-side programming: at least 2 years

## Database: 
- Experience in handling performance on MySQL and designing medium and small-sized database (<=30 tables)
- Understand clearly MySQL’s  mechanism of transaction management
-  Experience working with NoSQL (Redis, Cassanadra, MongoDB...) 

## Programming: 
- Specialize in at least 1 of these programming languages: Python, Go, Java, PHP. Having deep experience in Go and Python is an advantage
- Have a good background in OOP, Object-oriented design and basic understanding of Design Patterns.
- Have the expertise and experience in tuning systerm performance and scaling system up to multiple instances running parallel
- Having experience with CI/CD, Docker, Kubernetes, DevOps is an advantage
- Have ability to design class or create code structure to expand and support long-term maintenance and development
- Have good command of reading English technical materials

## Skills
- Problem-solving  
- Logical thinking                
- Analytical thinking

# You’ll be responsible for
- Develop management system satisfying the requirements of high speed and good scalability
- Develop in-house products based on micro services and DevOps architecture
- Create APIs to communicate with other systems and support libraries

# Why it would be awesome to work with us

* Negotiable salary based on capacity (13 months salary + bonus + shares)
* Competitive remuneration policy: lunch support, free drinks, daily food...
* Open, youthful working environment; numerous opportunities for career advancement
* Enjoy all social insurance regimes, participate in Genarali insurance with numerous benefits in accordance with company policy
* Participate in company’s teambuilding and vacation programs held annually
* Entitled to 14 allowable day-offs per year and 6 days per year of sick leave on full pay

# Contact
* Homepage: teko.vn
* Contact: Skype: buiminhnhat.nb
* Or send your CV via mail tuyendung@teko.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
