### ISSUE TITLE
TRAVALA UK -  Front-End Developer (CSS, AngularJS, JavaScript, HTML) - Hanoi - FT

### ISSUE THREAD

**Issue by NhaHien** [awesome-jobs/vietnam#1502]
## Location
- Floor 3th, Udic Complex Tower , Hoang Dao Thuy street, Cau Giay district, Hanoi

## Salary Expectation
- Up to: $1,800

## Requirements
- A minimum of 3 years of experience with one or more general purpose programming languages, including but not limited to: Web development with JavaScript/AngularJS, HTML, CSS.

### Must Have
- Must have a proactive and can do attitude
- Outgoing personality, organizing and motivating team
- Result orientation
- Passionate learners who aren’t afraid of new tools and technologies to build a great end-to-end customer experience.

### Ideally
- Experience with Booking Engine Platform/ E-Commerce, CMS/CRM systems is a plus
- Technical understanding or experience with Blockchain and distributed systems.
- Experienced in Digital Payment system is a plus
- Prior experience working in a start-up

### Responsibilities
- Build responsive and interactive websites, slick animation, beautiful scrolling, stunning transitions. 
- Follow best practices and coding standards to ensure we have clean HTML and CSS, and things work smoothly regardless of the browser or device.
- Collaborate with designers to build UI/UX to provide for customers, and be proactively involved in the design stages. 
- Work as part of a team to meet demanding project requirements.
- Stay motivated and up-to-date on the latest developments and trends in web Booking online design & development.

### Why it would be awesome to work with us
- Competitive income, depending on experience and ability
- Nice workplace with good services such as free coffee, tea and entertainment in Co-Working Space
- Training course, new technology (Blockchain, Fintech), English
- Participating in tourism activities, outdoor activities ... of the company
- Chance to become one of key persons of Company
- Young, dynamic and professional working environment

### Contact
Homepage: https://www.travala.com/
Send CV to: it.huynhnguyennhahien@gmail.com 
Title: TRAVALA - FE Dev - Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
