### ISSUE TITLE
Zalo Group - Fullstack Web Developer - HCMC - FT

### ISSUE THREAD

**Issue by PNi2010** [awesome-jobs/vietnam#1505]
## Location

Flemington Tower, Dist.11, HCMC

## Salary Expectation

* Up to $1500/month

## Requirements
* 1+ years of web development
* Strong knowledge in HTML5 and best-practices, also best-practices/methodologies in CSS, familar with Bootstrap
* Strong knowledge in javascript (AJAX, jQuery) and JS frameworks
* Have a solid background in Unix/Linux environment and Shell scripting
* 2+ years of experience in at least one programming language: Python, Java, JS
* Experience with revision control software such as Git and SVN

### Must Have
* 2+ years of experience in at least one programming language: Python, Java, JS
* Strong knowledge in HTML5 and best-practices, also best-practices/methodologies in CSS, familar with Bootstrap
* Strong knowledge in Javascript (AJAX, jQuery) and JS frameworks
* Experience with revision control software such as Git and SVN

### Ideally
* Experience developing scalable and robust software applications in web environments with exposure to both frontend and backend technology stacks
* Deep understanding in one of SQL and/or NoSQL databases
* Experience with microservices, caching tools, data visualization, queuing systems or distributed systems is plus.

### Responsibilities
* Develop high-performance web applications in Java / Python, Javascript
* Write clear and maintainable code
* Develop existing and new projects
* This is an opportunity to work in a high-growth, fast-paced environment where you are encouraged to disrupt, learn, build, ship, fail and fail fast, reiterate and more importantly, your code and intellect will be a key driver of the product’s success

### You’ll be responsible for

* Develop high-performance web applications in Java / Python, Javascript, which serves the special projects for the AILabs in Zalo
* Develop existing and new projects and feature requests

### You can bring

Excellent problem-solving skills
* Strong knowledge of Data Structure and Algorithms
* Interested in or experienced with data collecting and ETL process
* High responsibility

### Why it would be awesome to work with us
* Adequate pantry with free food and drinks which are continuously filled up
* Huge system structure which enhances your skills to the next level really fast
* 13-month salary and performance bonuses
* Dynamic and excellent bosses and colleagues
* Free parking and lunch stipend

### Interesting engineering projects
* Joining Zalo Group, you're contributing to the most innovative technology ecosystem in Vietnam

### Contact
Phone: 0785898293
Email: nghittp@zalo.me
Website: https://careers.zalo.me/jobs#jobs

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
