### ISSUE TITLE
thuocsi (B2B Pharmacy Marketplace Startup) - Fullstack Rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by anhvu0911** [awesome-jobs/vietnam#1506]
thuocsi.vn is a B2B startup for pharmacy industry. Its vision is to change the way pharmacy/clinics buy/sell medicines, to provide accurate medicine information and to increase clients' profits.

## Location

* District 10, Saigon

## Salary Expectation

* Attractive. The more the experience, the higher the pay.
* Stock option available

### Must Have

* 2+ years with Ruby on Rails
* HTML/CSS/Javascript. Has experience with Bootstrap, jQuery
* PostgreSQL
* Passion in improving yourself, the application and the company.

### Ideally

* Experience with Angular/React/Vue
* Experience with Zalo, Tiki... any projects in B2C/B2B domain 
* Have knowledge of DevOps, CI/CD with AWS Services is a plus.
* Know Python

## Responsibilities

* Write main website from scratch in Ruby on Rails. Ensure it is easy to use, performant, and responsive. 
* Develop an Inventory management, Order fulfillment e-commerce website.
* Integrate platform with third party's API such as GHTK, Giao Hang Nhanh, Orderhive, Zalo...
* Optimize SEO score of individual products.

## You can bring

* A good eyes for design.
* A good analysis skill.
* An artistic talent like playing guitar, singing.

## Why it would be awesome to work with us

* Startup environment provides many challenges to train yourself as a full-stack developer: front-end, back-end, devops, software design...
* Benefit allowances for meal, parking, transportation and telephone.
* Stock option
* Young, professional and constructive environment. You also have a chance to help other departments (sales, warehouse) improve their productivity.
* Various snacks and drinks in our bar.
* 15-day annual leaves, social insurances based on Vietnam labour law.
* Team building activities.

## Contact
Homepage: thuocsi.vn (Many things to improve? We know. Come and improve together)
Email: anhvu@thuocsi.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
