### ISSUE TITLE
Dinovative - Front-end React/ React Native Developer (Junior) - Saigon - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#1509]
## Location

* Dinovative is looking for Front-end React/ React Native Developer who is excited to work alongside a talented group of innovators to craft digital products. Being part of the conversation from the start, you will be expected to lead full lifecycle webbased projects including guiding technical scoping, design and implementation.
Collaborating with UX & UI designers, researchers and other engineers (web & mobile), you will have the ability to flex your full stack chops to help shape, design and build digital products that help solve key business needs. We want people who love being involved in challenging and innovative work.

* 63A Nam Ky Khoi Nghia, Ben Thanh Ward, District 1

## Salary Expectation

* Negotiable

## Requirements
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies
* Strong JavaScript and React/ React Native skills.
* Experience building responsive web apps
* Strong analytical and problem solving abilities
* Strong communication and client facing skills

## Skills
* Strong Javascript
* Strong knowledge of React/React Native, Redux
* RESTful API 
* Database mySQL, MongoDB, PostgreSQL

### Must Have
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS, Reactjs/React Native or other web technologies
* Solid understanding of HTML, CSS3, Bootstrap, SASS, LESS, responsive design
* Be able to writing tests with unit test
* Be able to working with Git or SVN

### Ideally
* Experience building responsive web apps
* Experience with ES6 feature, MEAN stack, other frameworks such as ExpressJS, Loopback ,...

### Responsibilities
* Front-end Mobile Web development (HTML5, CSS3, React/React Native, integration with RESTful Web API)
* Maintain existing software
* Constantly learn and keep abreast of emerging technologies
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Critique software designs and architectures
* Peer review colleagues code and identify areas for improvement
* Provide development task effort estimates
* Conduct client requirements gathering and analysis
* Review test plans
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:
* Working in dynamic, young, friendly, flexible invironment
* Laptop is provided
* 12+ days annual leaves, working Monday - Friday, flexible working time
* Attractive salary based on skills and experiences
* Salary review: Once a year, base on individual performance review
* Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy 
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding 
* Free fruits/ snacks on happy hours time
* Celebration: birthday
* Party time: Team building (frequent) and Xmas
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development 
* Training new technology frequently, and become a fullstack developer

### Interesting engineering projects
* We use international standard in building system such as agile, test driven development, continuous integration and continuous deployment.
* Various projects with so many new technologies applied

### Contact
Email: oanh.tang@dinovative.com
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
