### ISSUE TITLE
Lixibox - ROR Engineer (full stack) - HCM - FT

### ISSUE THREAD

**Issue by vantran** [awesome-jobs/vietnam#151]
## Location
- Saigon, Vietnam
- Full-time onsite
## Salary & benefits
- $600 - $2500 negotiable depends on skills
- BaoViet Insurance
- Company lunch provided daily
## Requirements & skills
- Competency at Ruby/Ruby on Rails framework
- Experience working with Javascript/HTML/CSS
- Experience with working with mobile responsive layout
- Good knowledge about software testing, automation testing (Rspec, Capybara)
- Experience working with the Git version control system
### Ideally
- You have a lot of experience with Ruby & Rails.
- You work on both back-end and front-end on a daily basis. HAML, CSS & Javascript/Coffee feels as natural to you as Ruby and SQL
- You understand the importance of software testing and give your best effort to write tests for things you write
- You are more than just a cog in the machine. You are not afraid to voice your own ideas and feelings about what makes and improve a good product.
## What you will do
- Work with tech team to build Lixibox.com to be the best e-commerce platform.
- Work cross-functional across multiple teams to understand and develop new features, as well as maintain existing features.
- Assist marketing team to grow Lixibox user base.
- Scale Lixibox to accommodate a huge user base.
## We're looking for someone similar to us
- Very competitive and loves startup environment
- Can communicate ideas and express themselves in English
- A young spirit with a lot of energy. Age is only a number.
- A great working attitude. You feel pride and a sense of responsibility in the products you work on.
- A great sense of humor. We like to laugh a lot and often :smiley: 
## About the company

Lixibox is a young and fast-growing e-commerce start-up funded by well-known Silicon Valley investors (Joe Lonsdale of Clarium Capital, Eric Chen of Tiny Prints, Alin Bui of Anduin Transactions etc.). The company aims to disrupt the whole online cosmetic market with creative use of tech and big data. Started in early 2015, Lixibox is already one of Vietnam's favourites among cosmetic enthusiasts.

Joining the team, you will have the opportunity to work with passionate and talented people in their fields. Our founders have deep experience with e-commerce and have helped start many other companies.

Lixibox is very different from your typical tech company in VN. We value our technical product deeply, and thus pay much more attention on polishing them. We want developers who feel responsibilities for their products. We all feel pride in our work and we expect the same from you.

Our tech stack is built from experience, using the best practice of automated deployments and Git working standard. Working with us, you can learn much more about code and how to build reliable, scalable tech that can serve a great number of concurrent users.

We follow pure American working style that will allow you to be as comfortable as you want with family culture, flexible working time, beautiful non-traditional office, free drinks (juice, soft drinks even beer if you want), snacks, lunch and a competitive salary.
### Contact

Van Tran: van at lixibox dot com

**Comment by joneslee85** [comment]
Please update the title, it does not comply with our guideline

**Comment by joneslee85** [comment]
@vantran :+1:

**Comment by vantran** [comment]
@joneslee85 Thanks for reminding :)
