### ISSUE TITLE
TIKI Corporation - Frontend Engineer - Saigon - FT 

### ISSUE THREAD

**Issue by lethanh94951997** [awesome-jobs/vietnam#1513]
## Location

* Viettel Complex Building 285 Cach Mang Thang 8 Street, HCM
* Fulltime

## Salary Expectation

* 900$ - 2000$

## Requirements
* Proficient understanding of web markup, including HTML5, CSS3
* Basic understanding of server-side CSS pre-processing platforms, such as LESS, SASS, CSS Modules
* Should have the knowledge of advanced Javascript libraries and frameworks, such as VueJS and/or ReactJS
* Good understanding of asynchronous request handling, partial page updates, AJAX, NodeJS and tools built Grunt, Gulp, Webpack
* Proficient understanding of code versioning tools, such as Git, SVN
* Proficient understanding of cross-browser compatibility issues and ways to work around them

### Why it would be awesome to work with us
* Open communication with passionate and experienced members.
* Challenging working environment.
* Easy access to the library with tons of startup, product, UX, coding... books.
* Private healthcare insurance.
* Annual health check-ups.
* Special internal programs for Tikiers when shopping on Tiki.vn (free ship TikiNow service, discount...).
* Internal events to bond our mutual understanding & spirit such as team building, team outing, Tiki's birthday, year-end party...
* New & beautiful office with a pantry room (with bar), entertainment & gymnastic equipment, yoga rooms, a library and an open space facilitating cross-department communication.
* Competitive salary and performance review (twice a year), 13th-month pay based on performance.

### Interesting engineering projects
* Operation Product
* Seller Center
* Commercial Product

### Contact
* Please apply your CV to email: lethanh94951997@gmail.com

**Comment by qcam** [comment]
@lethanh94951997 Would you mind using your company email instead?

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
