### ISSUE TITLE
LittleLives - Mobile Engineer (Java, Swift, Kotlin) - HCMC - FT 

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#1514]
## Location
Green Hub, Level 9, 186 Bis Trần Quang Khải, P. Tân Định, Q.1

## Salary Expectation
800 - 2000 USD

### What you will be doing :

- Develop in-house apps using Swift/Kotlin
- Update and maintain current iOS/Android apps
- Keep up to date on the latest industry trends in the mobile technologies
- Collaborate with a diverse multinational team of engineers
- Be a vital voice in sprint planning and daily stand up meetings

### Here's what you can achieve with us:

- Develop a wide experience in different technologies, earning you respect in problem-solving
- A chance to make a difference in the lives of thousands of preschool educators and children all over the world will benefit
- Develop your strengths; your contributions will make you irreplaceable. We can't get another you in a minute
- Explore your leadership potential, code review your peers, and pass down the knowledge 
- Automate everything and keep things powerful yet effortlessly simple

### Must have:

- Bachelor’s Degree in Computer Science/IT/Programming or related fields
- 1-3 years of experience working with iOS/Android by designing, implementing robust features
- Good knowledge about iOS/Android SDK
- Good understanding of software engineering principles and techniques
- Strong knowledge of object-oriented programming
- Good understanding of the full mobile development life cycle, structural and popular design pattern such as MVC, MVVM
- Excellent programming skills in Swift/Kotlin
- Good understanding of Android Jetpack Components (LiveData, Room, Navigation, WorkManager)
- Familiar with commonly used third-party library (Retrofit, Dagger 2, Stetho, Timber)
- Familiar with Git and Gitflow
- Familiarity with GraphQL
- Familiarity with CocoaPods and well-known open source libraries
- Attention to detail and a keen eye for good UI/UX
- Understanding of Apple’s design principles and interface guidelines
- Understanding of Android design principles and android material design guidelines
- Experience with iOS frameworks such as Core Data, Core Animation, as well as offline storage, threading, and performance tuning
- Have published one or more iOS apps/Play Store in the app store
- Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

### Nice to have:

- Basic knowledge of Functional Programming 
- Experience with Android mobile app development using Java/Kotlin
- Familiarity using Firebase platform
- Experience managing a team of mobile developers

## Why You'll Love Working Here

- 14 days annual paid leave
- Competitive salary
- We WILL push you to learn new things together with us
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- MacBook Pro and additional screens
- Yearly Bonus
- Travel for our team building event every year
- Take on lead roles as the team expands
- Have your say in the culture of our still young Vietnamese office

## Contact
- Email: changinglives@littlelives.com
- What do you need to apply?
- Your CV (English)
- Your Github (or equivalent open source community) profile

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
