### ISSUE TITLE
FinOS Vietnam- Data Scientist - Saigon - FT

### ISSUE THREAD

**Issue by Uyenai** [awesome-jobs/vietnam#1516]
## Location

* Saigon, Vietnam (preferred)
* Ha Noi

## Salary Expectation

* Starting 5k USD up, open for negotiation

## Requirements
* Master's or Bachelor’s degree (with at least 3 years of experience), in Computer Science, Electrical/Computer Engineering, Operations Research or Mathematics/Statistics
* Understanding of machine learning, deep learning, data mining, algorithmic foundations of optimization
* Past and current experience writing and speaking about complex technical concepts to broad audiences in a simplified format
* Ability to develop experimental and analytic plans for data modeling processes, use of strong baselines, ability to accurately determine cause and effect relations
* Experience with machine learning framework (scikit-learn, Spark MLlib etc)
* Proficient in one or more of the following programming languages: Python, R, Scala.
* Experience in building ML models at scale, using real-time big data pipelines on platforms such as Spark/MapReduce
* Familiar with NoSQL, postGIS, stream processing and distributed computing platforms
* Strong written and verbal communication skills, with a track record of presenting to senior management

## Skills
* Python, R, Statistic, Spark, SQL, ...

### Must Have
* Effective English communicator
* BS or MS degree in computer science or equivalent field.
* 2+ years Software Engineering experience

### Ideally
* Working experience in the financial industry
* Experience working on AWS is a big plus

### Responsibilities
* Work with product owners and business development team to define hypotheses, develop and execute necessary tests, experiments, and analyses to prove or disprove them
* Translate data speak to human speak by effectively conceptualizing analysis to team members and business stakeholders
* Build, validate, test, and deploy machine learning models (e.g. predictive, forecasting, clustering) using proven and experimental techniques. Deploy an online learning model where applicable

### Why it would be awesome to work with us
* FinOS, established by Allianz SE - the world’s most trusted financial service provider, headquartered in Munich, Germany (https://lnkd.in/fuu-rDH), is to pave the way to provide financial support to the unbanked through simple, affordable and tech-enabled financial products & services. 

* FinOS’s Data Science team works on some of the most challenging and fascinating problems in the financial industry. We foster a culture where we enjoy raising the bar constantly for ourselves and others, and that strongly supports the freedom to explore and innovate. 

* If you are haunted to bring financial inclusion to SEA, FinOS data team is your answer.

### Contact
Uyen Do
uyen.do@finos.asia

**Comment by Uyenai** [comment]
Benefits:
- 13rd month salary
- Full government insurance
- Health insurance
- 15 AL, 30 sick leaves
- And others to come

**Comment by Uyenai** [comment]
Skype id: uyendo156

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
