### ISSUE TITLE
FinOS Vietnam - Data Engineer - Saigon - FT

### ISSUE THREAD

**Issue by Uyenai** [awesome-jobs/vietnam#1517]
## Location

* Saigon, Vietnam (preferred)
* Ha Noi

## Salary Expectation

* 2.5 - 3.5 k USD, open for negotiation 

## Requirements

* Mastery of one of Python, or similar language.
* Experience with Relational databases or NoSQL databases.
* Proven understanding of the full software development lifecycle including testing,
continuous integration, and deployment.
* Excellent problem solving, critical thinking, and communication skills.
* Solid grasp of computer science fundamentals including data structures and algorithms.
* Understanding on machine learning techniques.
* Proven ability to evaluate and apply new technologies in a short time.
* Self-motivated, proactive, and solution-oriented.
* Experience with cloud platform services desired.

### Ideally

* Experience in building data science or data analysis tools a plus.
* Machine learning background a plus.
* Familiarity with Agile software development process, Test-Driven development and
Continuous Integration a plus.
* Familiarity with DevOps tools such as Ansible and Terraform a plus.

### Responsibilities

With the large volume of data which we will be leveraging, our job is to build and maintain proper data processing solution to bring reliable experiences for our customers. As a Data Science Engineer, you work closely as part of a small setup in FinOS to lead the design and implementation of systems and tools to support the effort of FinOS. You will be:
* Developing and implementing production backend system to serve data science prediction.
* Designing system and data architecture. 
* Working with partners to integrate systems.
* Problem-solve and develop solution at the intersection of data and systems.
* Innovating by recognizing opportunities for automation and tools improvements.
* Providing technical leadership for a team of data scientists.

### Why it would be awesome to work with us

* FinOS, established by Allianz SE - the world’s most trusted financial service provider, headquartered in Munich, Germany (https://lnkd.in/fuu-rDH), is to pave the way to provide financial support to the unbanked through simple, affordable and tech-enabled financial products & services.
* FinOS’ Data Science (DS) team is responsible for ensuring the company is well equip with the skills and technology needed to improve, change and solve engineering problem involving system, integration, deployment and development. DS runs multiple environment using continuous integration and deployment practice. We work side-by-side with the business to define the technical requirements and with the data science team to implement scalable, production-ready API and infrastructure using best practices.
* If you are haunted to bring financial inclusion to SEA, FinOS data team is your answer.

* Benefits: 13rd month salary, full government insurance, health insurance, 15 AL, 30 sick leaves, and more to come

### Contact
uyen.do@finos.asia
skype: uyendo156

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
