### ISSUE TITLE
Teky Holdings - Python Developer (Technical Leader) - Hanoi - FT

### ISSUE THREAD

**Issue by NguyenLeDinhNguyen** [awesome-jobs/vietnam#1520]
## Location

* Ha Dong, Hanoi, Vietnam

## Salary Expectation

* 20-25 millions VNĐ

## Requirements
* Experience in Python.
* HTML, CSS (Bootstrap) và Javascript (jQuery).
* Linux basic (Ubuntu hay CentOS).
* SVN, GIT, hay TFS.

### Must Have

* Experience in Python

### Ideally

* Experience with Framework Odoo/OpenERP.

### You’ll be responsible for

* Coding Python by Framework Odoo.
* Building and maintaining a company management software provided for small and medium clients. 
* Good reading in some document of describing user's requirement (URD, SRS).
* Participating in design and writing documents of details designer  (SAD, SDD, Screen Design).
* Supporting team on project, QA team, Test, customer implement project.
* Building working plan, report, performance evaluation self-assessment, contributing ideas to improve the quality, job performance.

### Why it would be awesome to work with us
* Offer + bonus, starting salary: 20 -25 millions VNĐ/month.
* Startup environment is flexible, professional, modern equipments.
* Have full of insurance such as Health Insurance, social insurance, ... 
* Special bonus for other projects.
* Company trip, Team building.
* 13th salary; Performance bonus; Tet bonus. 

### Interesting engineering projects: 
* TEKY is a technology innovation institute with education programme STEAM (Science – Technology – Engineering – Art – Mathematics) suits for the first American standard in Vietnam is for children from 4 to 18 years old.

### Contact
Gmail: dinhnguyen.nguyenle@gmail.com
Tittle: Python - Teky -  Your Name

**Comment by cesarmanzo** [comment]
Is it possible to apply if I'm not from Vietnam?

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
