### ISSUE TITLE
ONACLOVER - Back-End Engineer (Ruby on Rails, Ruby) - Hanoi - FT

### ISSUE THREAD

**Issue by HongNgoc2801** [awesome-jobs/vietnam#1523]
## Location
* 162 Phuong Liet Street, Thanh Xuan District, Hanoi

## Salary Expectation
* Up to $1,500

## Requirements
* 6+ months Ruby/Ruby on Rails experience
* Have experience/knowledge on Front-End : using CSS framework (Bootstrap, Foundation,..) and Javascript framework (ReactJS, VueJS)

### Ideally

* Experience with one of these Javascript, Python, Java, Go is a big plus

### Responsibilities
* Develop features from ideas to products.
* Support, communicate with the Customer Service team to find out the origin of customer problems and give good solutions.
* Engage with managers to discuss, offer solutions to improve products.
* Working with the UX / Design team, the frontend team, mobile team create support APIs, features/logic to complete features/products.

### Why it would be awesome to work with us
* Competitive salary, suitable for capacity
* Evaluate performance review every 6 months, fast salary growth rate (average 20% / year), no ceiling restriction if good dedication
* Be trained in skills, programming thinking, and project management skills
* The system of Level personnel is clearly divided, with a route to promote under the periodic evaluation. When fully devoted, you will receive bonus shares worth hundreds of thousands of dollars in the next 5 years
* Be proactive in contributing ideas to product development, assigning rights to individual projects and teams.

### Contact
* Email: lehoang.hongngoc2801@gmail.com 
* Title: [ONACLOVER - Ruby on Rails Dev - Your Name]

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
