### ISSUE TITLE
BeGroup - Typescript developer - HCMC - PT

### ISSUE THREAD

**Issue by heraid** [awesome-jobs/vietnam#1525]
## Location
* Be Group is based in NYC, and we have a small team in HCMC, Vietnam
* Remote

## Salary Expectation
* your desired hourly rate

## Requirements
Remote senior developer who is meticulous and thorough to improve and build on discrete features of a client portal that will serve several clients.

## Skills
* Typescript
* familiarity with AWS key management
* data encryption and partitioning 

### Must Have
* 5+ years Software Engineering experience

### Ideally
* Experience with working client portals and applications similar to Slack's file sharing and channels.
* Experience with data encryption and partitioning client files 

### Responsibilities
*work independently, create and meet timelines

### You’ll be responsible for
* Building or improving an earlier version of a feature

### You can bring
* Your great ideas, solutions, and expertise

### Why it would be awesome to work with us
 * we give our developers lots of independence and clear instructions

### Contact
Homepage: heraid@begroup.io

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
