### ISSUE TITLE
Cinnamon AI - Software Engineer - Hanoi/HCM/Da Nang - FT

### ISSUE THREAD

**Issue by giangnguyen2710** [awesome-jobs/vietnam#1526]
## Location

* Ha Noi/HCM/Da Nang

## Salary Expectation

* $600 - $2500

## Requirements

For Junior:
• Strong coding skills.
• Solid understanding of computer science concepts: time complexity, algorithms and data
structure.
• Self-motivated and creative thinking – we’re building technology from the ground up, not
tweaking legacy systems.
• Good communicator and team player.

For upper levels:
• Strong understanding of software engineering concepts such as testing, continuous
integration and deployment.
• Experience with architecture skills: Strong knowledge of design patterns and software
architecture.
• Experience in designing and building distributed systems.
• The ideal candidate will have knowledge about Machine Learning.
• Experience in big data frameworks are a big plus.
• Grit: passion and perseverance, drive and a strong feeling of ownership coupled with
collaboration and leadership.

### You’ll be responsible for

For Junior level:
• Develop effective solutions to challenging problems with comprehensive production quality software.
• Write maintainable and extensible code with high quality tests and documentation.
• Participate in system architecture design sessions.

For upper levels:
• Design and build scalable and highly available software system and tools in our Machine Learning platform to speed up our deployment life cycle.
• Collaborate with Delivery to gather requirements from internal teams as well as external clients.
• Collaborate with an incredible team of highly skilled group of AI Engineers and AI Researchers to help them solve technical challenges.

### Why it would be awesome to work with us
This is an exciting opportunity for those who love challenges and want be part of the team building one of the first Machine Learning platforms, in Deep Learning for Computer Vision, NLP and Speech Recognition; who want to grow and become world-class in the field of Software
Engineering and AI. 

Senior candidates (i.e., with years of experience / leadership) and junior candidates are welcome to apply; we have and will offer positions appropriate to expertise and level of experience.

### Interesting engineering projects

Cinnamon Software Engineering team is currently working on software systems that bring Cinnamon AI solutions to big enterprises as well as building Machine Learning system that empowers Machine Learning life cycle in Cinnamon. You will be a member of a team of strong software and system engineers, working to understand and solve the challenges posed by AI development. This is not your usual software development job: the problems we are solving are being approached for the first time. We are at the frontier of technology.

### What you will get in return:

• Attractive compensation and benefits.
• Employee-centric culture and a belief that we should hire those who are good at what they do and then give them the tools they need to achieve success, further their expertise and grow their career.
• A commitment to learning and growth, with a training budget, education assistance, mentorship programs and collaborative learning sessions.
• A collaborative environment that fosters communication via Slack and an open-door policy.

### Contact
Please submit your CV to email: talent@cinnamon.is as soon as you reach this line in the post!
Have a nice day!
[Cinnamon_Software Engineer_(updated).pdf](https://github.com/awesome-jobs/vietnam/files/3137398/Cinnamon_Software.Engineer_.updated.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
