### ISSUE TITLE
Parcel Perform - Front-end Developer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#1528]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - 2,500

## Requirements
* Be responsible with task and be open to discuss, give questions to build up products with high
quality and rich front-end experiences for our users.
* Understand clearly about object-oriented programming and design pattern.
* Willing to learn and research new technology or jump out of your comfortable zone.
* Passionate about quality and the design of the code, productivity of the work and maintainability of the end result.

## Skills
* 1+ years professional front-end software development experience in Reactjs, or similar platforms.
* Have strong knowledge in ES5/ES6.
* Experience at one or more CSS compiler (LESS/SASS/PostCSS)
* Proficient in code review, code refactoring, Unit Testing
* Prefer for additional skills
-- Bundle code with Webpack/Browserify
-- AMP-HTML
-- Progressive web app (PWA)
-- Implementing a ChatBot
-- RxJS/Reactive programming

### Must Have
* Experience in Reactjs, or similar platforms

### Responsibilities

As a frontend developer, you will be building the interfaces to interact with Parcel Perform system. Our goal has always been to create a seamless experience between human and computer. And because of that, we continuously incorporate latest advancement in web technologies and expand the scope of user interface. Some of the latest additions are conversational UI, Progressive Web App, and Accelerated Mobile Page.

### Why it would be awesome to work with us
* The opportunity to work in a fast growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing, and focuses on succeeding - we
continuously work with you on your strengths and weaknesses across many important
dimensions, and look at ways for you to address them and further your development
* Your entry ticket into being part of the Parcel Perform startup Universe, where you will work with and alongside people people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast growing company like free lunch, annual wage
supplement, various training programs, free fruit, amazing oces including sleeping rooms, and
more.

### Interesting engineering projects
You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide.

### Contact
Homepage: www.parcelperform.com
Mr. Huy - HR Manager - huy@parcelperform.com (+84 906 05 4484)

![PP Cover](https://user-images.githubusercontent.com/49466111/55857806-4f978f00-5b98-11e9-8e41-0acb03f2ba88.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
