### ISSUE TITLE
Pegasi Recruitment - Java Solution Architect - Saigon - FT

### ISSUE THREAD

**Issue by HoaPegasi** [awesome-jobs/vietnam#1529]
## Location

* Ho Chi Minh City, Vietnam
* Full-Time Permanent

## Salary Expectation

* $2,000 - $ 3,000 Net per month

## Requirements
* Expert in the system design and address well the high –ability requirements of the large systems
* Strong experience in web application and web service frameworks such as Spring/Spring MVC, Struts2, JAX-WS, JAX-RS
* Experience with enterprise application integration frameworks such as EJB/MDB, Spring Integration, Apache Camel, Mule ESB, WSO2 and SOA.
* Strong knowledge in MS-SQL/MySQL server, database design, data access frameworks …
* Expert in code quality, coding standard, OOP principles, design patterns, enterprise architecture design patterns, and enterprise integration patterns.
* Strong leadership, Good in English for confident discussions with customer about technical approaches or issues in details
* Nice to have skills: Experience in other technology stack such as Open Source, .Net, Mobile …

### Responsibilities

* Be responsible for the overall design of the application and mapping client business requirements to system designs
* Work with the stakeholders such as TAs, development teams, Product Managers, Engagement Manager, etc, to deliver the complete solution for the client
* R&D the new technical skills and build the relevant core team around for company based on the business needs and technical trends
* Participate in pre-sales supports and company-wide activities (trainings, cross project technical supports, interview, etc)
* Discuss, present and influence the relevant stakeholders to follow the defined technical solutions/approaches
* Set guidelines, review architecture alternatives, and perform technical evaluations

### What's on offer
* 13-month salary per year
* Performance bonus
* Social – Health – Insurance paid fully
* Healthcare: Annual health check-up, Premium Health Insurance
* Annual leaves: 14 ~ 18 days
* Clubs program: Football, Badminton, Swimming, Tennis, Rock, Yoga…
* Training courses: Technical skills – Soft skills – English
* People are extremely important to us and that’s why we have a clear vision: to make Company a great place to work in its sector. We pride ourselves on:

Professional and Flexible Working Environment
* Great Teamwork
* International Assignments
* WeCare - WeShare - WeDare - WeInnovate Engagement Programl

### Contact
Homepage: www.pegasi.com.vn 
Email: recruit@pegasi.com.vn | Tel: +84 28 7109 9077

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
