### ISSUE TITLE
Logix_PHP ( Yii) good English for RMIT

### ISSUE THREAD

**Issue by thuongbui1904** [awesome-jobs/vietnam#1532]
## Location

* Saigon, Vietnam
* RMIT - District 7

## **Salary Expectation**

* $1000-$2000/month 

**## Requirements**
-	4 Years + experience in PHP technologies.
-	Good at Zend or Yii framework
-	Good at writing efficient SQL queries
-	Problem solving

### Must Have

-    English communication 
-    Strong troubleshooting & analyzing
-    Customer oriented
-    Problem solving

### **Responsibilities**

- Designing, developing and coding new features, applications, upgrades and bug fixes to high-quality standards and customer expectations
         - Estimating Agile user stories and tasks and proposing technical solutions
         - Progressing tasks and coding deliverables to completion
        - Taking part in code reviews and collaborate with other developers
         - In the early phase to join the Team service project to expand and grow the team.

**You are offered**
-  Career path development and on-going training
-  Competitive salary package, annual salary review based on employee's performance and contribution.
-  Year-end bonus, performance bonus and Project bonus based on company's salary policy
-  Healthcare and incident insurance

Other benefits:, Insurance, 13th salary, company trip, 18 annual leaves, teambuilding,….

### Contact
Email : thuong.bui@logixtek.com

**Comment by qcam** [comment]
@thuongbui1904 Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
