### ISSUE TITLE
Project Manager (NodeJS/PHP/Ruby on Rails) - Da Nang - Viet Nam

### ISSUE THREAD

**Issue by QuynhNguyen14** [awesome-jobs/vietnam#1533]
## Location

* Da Nang, Vietnam
* Fulltime 

## Salary Expectation

* 15,000,0000 - 25,000,000/month 

## Requirements
* Having 3 – 4 years working experience in PHP/ Node Js/ Ruby on rails
*  Understanding DB optimization
*  Having ability to analyze and design big system
*  Carrying out at least 10 seminars about technology
*  Being able to use another backend technology that is equivalent J3
*  Good communication in English
*  Having training ability.
* Excellent at management and problem-solving skills

### Why it would be awesome to work with us
12 days annual leave
13th-month salary
Performance bonus plan
Annual company trip
Opportunity to onsite in Japan
Team building monthly, quarterly
Clear career path for each candidate
Semi-annually performance and salary review
Opportunity to work in a dynamic start-up environment
Personal development: Japanese, English courses for staff
Gifts for family: Tet, Children’s Day, Mid-Autumn Festival
Fully Insurance package with 27% contribution from company.

### Contact
Linkedin: https://www.linkedin.com/in/quynhnguyen14/ 
Email: quynh.nguyen@jobseeker.vn

**Comment by qcam** [comment]
@QuynhNguyen14 
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
