### ISSUE TITLE
AhaMove - Full Stack Software Engineer - HCMC - Full Time

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#1539]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000-$1800/Month

## Requirements
Founded in 2015 in Ho Chi Minh City, Vietnam, AhaMove is an on-demand logistics service based on the concept of a shared economy, providing customers to fill excess capacity for logistics suppliers and reduce costs for consumers.

You can find more about us as a Facebook case study or on prestigious Asia Nikkei news This is a tremendous opportunity to take your career to the next level. Please review the information below and if you are interested, follow the Apply instructions.

The Job

Contribute to the codebase by developing new MicroServices/APIs in Node.js

Develop/use APIs on multiple systems (AWS, Google)

Front-end Mobile Web development (HTML5, CSS3, Angular)

Maintain and enhance existing internal CMS web app (HTML5, CSS3, Angular 1.0)

Constantly learn and keep abreast of emerging technologies

Provide development task effort estimates

Review test plans

Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

**Your Skills and Experience**

At least 1-year experience in Full-Stack Engineer 

Strong JavaScript and AngularJS (or VueJs or ReactJs) skills for web development

Strong experience in writing secured and scalable Node.js server code

Experienced in working with MongoDB, RMDB (Postgres) and Redis

Experienced in building responsive web apps

Understanding of HTTP protocol, RESTful data structures, and JSON format

Knowing Docker/ReactJs/VueJs is a plus

**Why you love working here**

Disruptive innovations

People-oriented philosophy of doing business

Your footprint on regional on-demand market

Sharp, motivated colleagues in a fun office environment

Working 5 days/week at Dreamplex, the best co-working space in HCMC

Competitive salaries and benefits according to experience and education level

### Contact
Homepage: https://ahamove.com/
https://www.linkedin.com/company/6587395/
Mr. Dong
Dong (Mr.)
Email dongdd@scommerce.asia
Skype live:mrdongdo
Telegram: https://t.me/DongDoD

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
