### ISSUE TITLE
AUTONOMOUS (US startup) - 2 Software QA/QC Testers - Saigon - FT

### ISSUE THREAD

**Issue by May-chan** [awesome-jobs/vietnam#1540]
## Location

* 139 Hong Ha, Phu Nhuan, Saigon, Vietnam

## Salary Expectation

* $800 - $1,300 
* Fulltime

## Projects
Check out the product at www.autonomous.ai
Deep dive in our source code on Github www.github.com/ninjadotorg

## The Job: 02 QA/QC software testers 
* Understand and analyze requirements for web-based products. Our web stack includes React, CSS, HTML, Python and Go.
* Design test plans, test cases, test procedures, test scripts and test data.
* Setup test environment, execute test based on test strategy.
* Record and document test results and compare them to expected results.
* Investigate potential defects and discuss them with engineers.

## Requirements
2+ years of QA QC / Tester in Software Development with the required skills as follows:

* Professional software manual testing experience in all areas
* Experience in automation testing is a plus
* Experience in software testing process development
* Ability to adapt and learn new technologies
* Strong management skills
* Excellent communication in both English and Vietnamese
* Good organisational skills
* Attention to details
* Flexibility with business changes
* Preferred experience with Scrum/Agile methodologies

## Ideally

* Excellent verbal and written communication in English
* Teamwork, flexibility, initiative, communication, and organization
* Play soccer

### You can bring

* A passionate & dynamic mind
* A risk taker, a dreamer
* A willing-to-learn person

### Team Culture Requirements

* Willingness to constantly learn new programming languages, tools, and technologies.
* You must be a fast and thorough learner, capable of systematically inquiring into new technologies and their foundations. Think and rethink, from the ground up.
* Able to constantly challenge yourself to stay on top of your game and upgrade yourself every day.

### Bonus Points (Not Required)
* Contribution to open-source projects.
* Excellent verbal and written communication in English.
* Teamwork, flexibility, initiative, communication, and organization.
* Play soccer.

### Why it would be awesome to work with us
* You be you.  We deeply care about helping everyone at Autonomous work on what they love, freely express their ideas within the organization, and grow to to their true potential.
* You be a better you.  Most of the time, you’ll be working on cutting edge technologies.  You’ll be constantly learning and improving your knowledge as an engineer, researcher or scientist.
* You are your own boss.  There is very little hierarchy at Autonomous.  Decision making processes are transparent and open to vote. We welcome all different ways of thinking and trust the people we work with to do what they do best. There is no micromanagement here.
* You the inventor.  Most of the time, you’ll find yourself working on a problem that doesn’t have a solution - yet. That’s where you come in.
* Solve problems for the world, not just Vietnam. Most of the problems we’re solving are for the global audience of today, and of tomorrow.
* Open source culture. We open source all of our projects on Github.

### The essentials
* Above-market salary and bonuses
* Total health care benefits for you and your family
* Standing desk, ergonomic chair
* Computers of your choice (Macbook Pro or Linux)
* Healthy lunch
* Private American English teacher 3 times a week
* Gym, yoga, zumba, karate classes throughout the week.  We play soccer every Friday!
* Company retreat & quarterly team retreat
* Travel internationally to conferences and tradeshows as needed

### Contact
Email: hoa@autonomous.nyc
Phone: 02862690290
Career page: 
www.autonomous.ai/talents/senior-qc-engineer-tester
www.facebook.com/Autonomouscareers

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
