### ISSUE TITLE
AUTONOMOUS (US startup) - 1 Backend Engineer Nodejs - Saigon - FT

### ISSUE THREAD

**Issue by May-chan** [awesome-jobs/vietnam#1541]
## Location

* 139 Hong Ha, Phu Nhuan, Saigon, Vietnam

## Salary Expectation

* $1500 - $2,000
* Fulltime

## Projects
About Autonomous
From a small apartment in NYC to 10 locations around the world
Rewind to 2014: A small group of tinkerers in a tiny apartment in Hell’s Kitchen, New York shipped the first SmartDesk to their first Kickstarter backer.
2018: we power 110,000+ companies in over 60+ countries, the SmartDesk is AI, and we are reimagining not just workspaces, but workplaces. What happens when you reach across the world and create a borderless, decentralized, autonomous organization? What does it an idea built on the blockchain look like?
Our global offices - California, Saigon, Shenzhen, Amsterdam, New York - share the same DNA. Autonomous belongs to dreamers, risk-takers, engineers, and artists dedicated to breaking down ideas and building them up again - bolder and better.
Our products: https://receptionist.autonomous.ai/

## The Job: Backend Nodejs Engineer

Join the 50+ talented developers at My Constant to builds blockchain powered financial tools for a connected world. 

It is OK if you do not have experience with blockchain yet.  As long as you have strong background in other backend languages/frameworks and have the desire to build decentralized applications, you will have the opportunity to learn blockchain technologies on the job.

## Requirements
* NodeJS or similar backend languages like Go, Python.
* Databases SQL and NoSQL.
* Designing and implementing scalable REST APIs.
* Software architecture, system analysis, design patterns, and unit testing.

## Ideally

* Excellent verbal and written communication in English
* Teamwork, flexibility, initiative, communication, and organization
* Play soccer

### You can bring

* A passionate & dynamic mind
* A risk taker, a dreamer
* A willing-to-learn person

### Team Culture Requirements

* Willingness to constantly learn new programming languages, tools, and technologies.
* You must be a fast and thorough learner, capable of systematically inquiring into new technologies and their foundations. Think and rethink, from the ground up.
* Able to constantly challenge yourself to stay on top of your game and upgrade yourself every day.

### Bonus Points (Not Required)
* Contribution to open-source projects.
* Excellent verbal and written communication in English.
* Teamwork, flexibility, initiative, communication, and organization.
* Play soccer.

### Why it would be awesome to work with us
* You be you.  We deeply care about helping everyone at Autonomous work on what they love, freely express their ideas within the organization, and grow to to their true potential.
* You be a better you.  Most of the time, you’ll be working on cutting edge technologies.  You’ll be constantly learning and improving your knowledge as an engineer, researcher or scientist.
* You are your own boss.  There is very little hierarchy at Autonomous.  Decision making processes are transparent and open to vote. We welcome all different ways of thinking and trust the people we work with to do what they do best. There is no micromanagement here.
* You the inventor.  Most of the time, you’ll find yourself working on a problem that doesn’t have a solution - yet. That’s where you come in.
* Solve problems for the world, not just Vietnam. Most of the problems we’re solving are for the global audience of today, and of tomorrow.
* Open source culture. We open source all of our projects on Github.

### The essentials
* Above-market salary and bonuses
* Total health care benefits for you and your family
* Standing desk, ergonomic chair
* Computers of your choice (Macbook Pro or Linux)
* Healthy lunch
* Private American English teacher 3 times a week
* Gym, yoga, zumba, karate classes throughout the week.  We play soccer every Friday!
* Company retreat & quarterly team retreat
* Travel internationally to conferences and tradeshows as needed

### Contact
Email: hoa@autonomous.nyc
Phone: 02862690290
Career page: 
www.autonomous.ai/talents/senior-qc-engineer-tester
www.facebook.com/Autonomouscareers

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
