### ISSUE TITLE
Jio Health - Senior Android Developer - HCMC - FT

### ISSUE THREAD

**Issue by quangnguyenbh** [awesome-jobs/vietnam#1542]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Who are you?
- You are a RESPONSIBLE person who takes his/her promises to their heart.
- You are a GO-GETTER: you are unafraid to go beyond roles and titles to get great work done, able to spot what is missing, initiate solutions, and connect people naturally.
- You are PASSIONATE, CURIOUS and OPEN to candid feedbacks about your performance and seek any constructive real-time points as a great way to grow.
- You are a DOER who thrives in a fast-paced and collaborative environment and demonstrate strong judgment and a solution-driven mindset. Multi-tasker, but with clear time management and prioritization skills.
- You LOVE DOING GOOD DEEDS to the society and people around you, being kind is your priority in general 

### You’ll be responsible for

- Develop and maintain complex applications in Android: Objective C, Swift, or Java, Kotlin
- Communicate with other teams in the organization; e.g. backend, web, QA.
- Prepare estimations.
- Prepare API requirements and specifications.
- Validate UI/UX and business logic.
- Write documentation.

### What we can offer
- Attractive salary
- Social insurance, health insurance, unemployment insurance according to Labor Laws
- Professional, dynamic working environment
- Macbook Pro 2018

### About the company
Jio Health is an ambitious, fast-growing healthcare technology company, founded in California - USA, and established in Ho Chi Minh city - Vietnam.

At Jio Health, we believe that everyone should be able to gain instant access to trusted, affordable, and convenient healthcare services, no matter who they are and where they are. With that holding principle, we’ve been rethinking everything-healthcare-related from an user’s point of view, from appointments to prescriptions, ever since.

In the past briefed 1.5 year, our team has been building an intuitive Integrated Healthcare Platform connecting licensed doctors, pharmacists, lab services to patients and those in need. As the business grows, we’re looking for bright, energetic, entrepreneurial minds to join us in the mission of making quality healthcare universally accessible and affordable.

### Contact
Homepage: https://www.jiohealth.com
Quang: quangn at jiohealth dot com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
