### ISSUE TITLE
Groove Technology - Junior Fullstack Javascript Developer - HCM - FT

### ISSUE THREAD

**Issue by Nguyenphong1226** [awesome-jobs/vietnam#1547]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - $1,300/month

## Requirements

* Experience with Javascript
* 2 years as a Web Developer

## Skills

* Javascript
* Any Back-end Programming language

### Must Have

* English communication skills
* Teamwork

### Ideally

* Experience implementing eCommerce Systems.
* Experience with bootstrap or similar CSS frameworks.
* Experience implementing eCommerce Systems.

### Responsibilities

* Reporting to the Project Manager and Tech Lead.
* Liaising with the key stakeholders of the project.
* Delivering fully implemented vertical feature sets based on the specification within estimates and without defects.
* Identify and mitigate risk in the projects implementation.
* Participating in code reviews.
* Lead and mentor less senior members of the team.

### You can bring

* Experience debugging and optimizing JavaScript (writing effective JavaScript code).
* A flexible, client-focused attitude and the ability to adapt to team-oriented culture and environment.
* High-level communication skills, both written and verbal, with the ability to write clear technical documentation
* Experience with source control systems such as SVN or GIT.

### Why it would be awesome to work with us

* International, dynamic, friendly working environment.
* Clear and stable career growth
* Many opportunities for personal and professional growth.
* Regular team building events, sport activities…
* Medical and Accident Insurance program
* Professional training
* Competitive and attractive salary
### Contact
Email: Phong.nguyen@groovetechnology.com
Title: [Junior Fullstack Javascript] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
