### ISSUE TITLE
KVY Tech - Senior Rails Engineer - HCMC - FT

### ISSUE THREAD

**Issue by longkvy** [awesome-jobs/vietnam#1548]
## Location

* Lầu 3, số 9 Hoa Cau, phường 7, quận Phú Nhuận, Hồ Chí Minh

## Salary Expectation

* 1.5k - 3k USD

## What you will do
- Design and build reliable Ruby/Rails code, from backend to frontend.
- Involve in communicating with customers to understand their ideas and requirements.
- Collaborate with teammates to make strategic technical decisions.
- Writing clean code, and testing it throughout the development process to ensure the quality is up to standards
- Experience with the Github development flow and code reviews
- Onboard and mentor new team members.

## Requirements
- Architect and build product features end to end in Ruby on Rails, Javascript (ES6), and React
- 3+ years experience full-stack development building real world web applications
- Experienced with Relational Databases and SQL.
- Rather good at speaking and writing English.
- Experience with other languages such as NodeJS, Elixir is preferred.
- Experience working with cloud services (AWS, Google Cloud, etc.)
- Experience with ReactJS is preferred.
- Passion for learning new technologies fast

### Contact
Homepage: https://kvytechnology.com
Email: long@kvytechnology.com
Email subject: [Senior Rails Engineer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
