### ISSUE TITLE
KVY Tech - Senior React Developer - HCMC - FT

### ISSUE THREAD

**Issue by longkvy** [awesome-jobs/vietnam#1550]
## Location

* Lầu 3, số 9 Hoa Cau, phường 7, quận Phú Nhuận, Hồ Chí Minh

## Salary Expectation

* 1.5k - 3k USD

## What you will do
- Architect and implement the challenging solutions in our React SPA code base.
- Keep an eye on new developments in the React, JavaScript and TypeScript world and drive adoption of better solutions.
- Spread the knowledge about architecture decisions, new technologies and best practices among the development teams.
- Development of our React/Typescript frontend as part of one of our Scrum teams.
- Writing clean code, and testing it throughout the development process to ensure the quality is up to standards
- Experience with the Github development flow and code reviews

## Requirements
- You have in-depth knowledge and experience in React, HTML, CSS and ideally TypeScript.
- 3+ years experience full-stack development building real world web applications
- Experienced with Relational Databases and SQL.
- You have strong communication and written language skills in English.
- Experience with other languages such as NodeJS, Ruby is preferred.
- Experience working with cloud services (AWS, Google Cloud, etc.)
- Passion for learning new technologies fast

### Contact
Homepage: https://kvytechnology.com
Email: long@kvytechnology.com
Email subject: [Senior React Engineer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
