### ISSUE TITLE
Shipmates - Front End Developer - Saigon/Hanoi/Remote - FT

### ISSUE THREAD

**Issue by allbombs** [awesome-jobs/vietnam#1552]
![developers-wanted](https://user-images.githubusercontent.com/2031239/51401548-02ea7c00-1b86-11e9-87cf-1393a85870aa.png)

We're looking for a JS hero to help develop ecommerce websites and applications for clients around the world. Do you regularly geek out and enjoy exploring/playing with modern JavaScript tools? Read on!

You will join the team to build Shopify Plus websites and Shopify applications. We have internal products and partner with other companies to build ecommerce stores used by millions of people around the world.

## Location

* Hanoi or Saigon, Vietnam
* Remote

## Salary Expectation

* $500 to $1500 per month

## Requirements
* Awesome. Talented developer with a great attitude.
* 2+ years experience
* Need to be able to show some code / github code review
* Degree in Computer Science or related field a plus
* At least 2 shipped apps
* Outstanding communication skills, can read/write/speak english
* Accountable, and will do what it takes to ship products and puts customers first

## Skills / Experience
* HTML / CSS / VUE.JS / Liquid. You should be into writing lightweight javascript
* Have experience converting designs into pixel perfect code (that works flawlessy and renders quickly across all devices and browsers)
* You should have websites that demonstrate your frontend skills
* Bonus if you have experience working Shopify or another CMS /eCommerce platform

### Why it would be awesome to work with us

* We love product, great design, and ecommerce.
* Interesting chance to work on multiple websites from all over the world. 
* Level up your skills (Development), get mentorship from senior developers from NA
* Talented team. We have fun, but work very hard. Strong on product, move fast.

### Contact
Superstars welcome, huge egos are not. Please send us an email and introduce yourself. 

To apply, please visit this form https://forms.gle/meJuoZYk4itJryTv5

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
