### ISSUE TITLE
NubeIO - Senior DevOps - Ha Noi - FT/PT

### ISSUE THREAD

**Issue by zero-88** [awesome-jobs/vietnam#1553]
## Location

* Ha Noi, Vietnam

## About us

Nube iO is an end-to-end smart building solution that enables asset owners to reduce trade servicing costs, improve comfort conditions and save energy by reducing cost barriers in commercial buildings.

We are in developing phase with numerous technologies that will be launching soon.
See more at: https://nube-io.com/

## Salary Expectation

* FT: `$2000` - `$3000`
* PT: Minimum `$12.5/h`

## Requirements

* Strong knowledge in designing and implementing `CI/CD` workflow effectively
* Solid experienced with container/virtualization technology, such as `Docker`, `Vagrant`, `VMWare` or `Virtualbox`, etc
* Good understanding of `computer networking`, `linux/unix administration` with advanced shell scripting skill
* Proficient understanding in routine maintenance, recovery, and handling failover of a `database`
* Familiar with `Kubernetes`, `Mesos/CoreOS` or similar clustering solutions
* Exposure to cloud platforms, like `GCP`, `AWS`, `Azure`, etc.
* Experience with automation/configuration management, virtualization and fine tuning of servers

### Must Have

* **Critical thinking** self-directed, self-disciplined, self-monitored, and self-corrective thinking
* Able to discuss and explain problems with peers and provide technical solution and plan
* Documentation skill
* Git flow and release management
* Excellent in designing and implementing `CI/CD` workflow
* Strong at least one of programming/scripting language (`Bash`, `Batch/Powershell`, `Python`, `Groovy`, `Go`, `Perl`, `Ruby`)
* Experienced in `IaC` tool: `Terraform`, `Ansible`, etc
* Familiar with one of alert and monitoring systems `Prometheus`, `Sensu`, `Grafana`, `Graphite`, `InfluxDB`, etc.

### Ideally

* `Jenkins`
* `Python` + `Bash`
* `Terraform`
* `Ansible`
* `GCP`

### Big plus

* DBA Admin `PostgreSQL`, `MongoDB` and some `NoSQL` databases (`Elasticsearch`, `Redis`, `Vault`, `Consul`, etc.)

### Responsibilities

- Helping teams become more autonomous
- Improve `CI/CD pipeline` for automate build, test, deployment
- Define and manage cloud infrastructure in `IaC`, configuration and deployment orchestration scripts
- Scale up our infrastructure in `microservice` architecture
- Monitor and alert system for `scalability`, `high availability` and `cyber security`
- Contributing to open source projects that we are using (or that we may use at a later stage)

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

- Startup spirit
- Flexible time & part-time job (at least 30 hrs/week)
- Opportunity be switched to long terms job, become one of first members in Hanoi office with more benefits

### Contact

* Email: tts@nube-io.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
