### ISSUE TITLE
NubeIO - Senior Java Engineer - Ha Noi - FT

### ISSUE THREAD

**Issue by zero-88** [awesome-jobs/vietnam#1554]
## Location

* Ha Noi, Vietnam

## About us

Nube iO is an end-to-end smart building solution that enables asset owners to reduce trade servicing costs, improve comfort conditions and save energy by reducing cost barriers in commercial buildings.

We are in developing phase with numerous technologies that will be launching soon.
See more at: https://nube-io.com/

## Salary Expectation

* FT: `$2000` - `$3000`
* PT: Minimum `$12.5/h`

## Requirements

* Excellent knowledge in `java`
* Strong knowledge in `TDD` and its spirit
* Good understanding of `asynchronous`, `multithreading` and `multiprocessing`
* High effective in design and implement `REST API`, `websocket`, `SSE`
* Experienced in distributed system with event driven messaging (`SOA` architecture)
* Solid experienced with `application design pattern` and `database design`
* Good knowledge in `application` security
* General knowledge in `Docker` technology

### Must Have

* **Critical thinking** self-directed, self-disciplined, self-monitored, and self-corrective thinking
* Able to discuss and explain problems with peers and provide technical solution and plan
* Open-minded and good at adapting to frequent changes, willing to learn new technologies while working
* Git flow and release management
* Build tools: `gradle`, `maven`
* Write code testable on both `unit test`, `integration test` that backed by automation test

### Ideally

* Functional programming

### Big plus

* Knowledge in `groovy`, `scala`, `python`, `bash`
* `Kafka`, `Spark`

### We expect you to

- Be a good team player
- Be better than yourself yesterday
- Solve the problem, not the task
- Ensure high-quality output
- Scale up our applications in `microservice` architecture
- Sharing coding best practices

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

- Startup spirit
- Flexible time
- Opportunity be switched to long terms job, become one of first members in Hanoi office with more benefits

### Contact

* Email: tts@nube-io.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
