### ISSUE TITLE
UrbanFox_Senior Java Developer_HCM_Full-time

### ISSUE THREAD

**Issue by VanCami** [awesome-jobs/vietnam#1555]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* $2000 USD/ per month

## Requirements
* Fluency   in Java (or Kotlin)-we use Spring Boot.
*Strong understanding of OOP and Clean Code.
*Experience   with relational databases, SQL and schema design.
*A fan of writing unit tests and TDD.   §  Understanding   of RESTful APIs.
*Customer focus - you believe that talking to   customers is essential to figure out what to build next.
*Knowledge of the Lean Startup principles (MVP, Build Measure-Learn). 
*Ability to work independently and deliver your own solutions to problems.
--

### Must Have

* Minimum 2 years to work as Java developer.

### Ideally

* Experience  with Devops - setting up infrastructure (AWS) & CI.    
* Knowledge or experience working with ERP or logistic systems is a plus .
* Understanding  of Agile principles, Scrum/Kanban.
--

### You can bring

* A good eyes for design
* A good analyis skill

### Why you join with us:
* Attractive salary, working directly with foreign client, it   means 100% of your work efficiency will be recognized for annual salary   review. 
Be part of an incredible team of people from all over the world. 
Work in a rapidly   expanding team and grow your responsibilities in time.
Extensive on job training, you will always have chance to work   with new emerging technologies. Especially largescale distributed systems and   Cloud-native microservices.
Social insurance, medical insurance & unemployment insurance   according to Vietnam Labor Law. 
12-day annual leave per year.
--

### Contact:
Email : Van.cami@gmail.com
skype: Van Cami (nguyentuongvanav01@outlook.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
