### ISSUE TITLE
Groove Technology - Front-end (HTML5, CSS3, Javascript) Developer - HCM - FT

### ISSUE THREAD

**Issue by Nguyenphong1226** [awesome-jobs/vietnam#1556]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000 - 13000/month

## Requirements
* HTML5
* CSS3
* Javascript
* 2+ Years of experience

### Must Have

* Strong understanding of HTML5, CSS3 and Bootstrap
* Experience with responsive and adaptive design
* Strong understanding of cross-browser compatibility issues and ways to work around them
* Strong understanding of server-side CSS pre-processor such as SASS, LESS
* Code quality and debugging tools, PixelPerfect, CSS Lint
* Good understanding of core JavaScript and its best practices such as object definition, prototypal inheritance, closures, event delegation, scope, higher-order functions…
* Experience debugging and writing effective JavaScript

### Ideally

* Familiarity with code smells and refactoring JavaScript code
* Experience with jQuery library
* A flexible, client-focused attitude and the ability to adapt to team-oriented culture and environment
* High-level communication skills, both written and verbal, with the ability to write clear technical documentation
* Experience with source control systems such as SVN or GIT

### Responsibilities

* Reporting to the Project Manager and Tech Lead.
* Liaising with the key stakeholders of the project.
* Delivering fully implemented vertical feature sets based on the specification within estimates and without defects.
* Identify and mitigate risk in the projects implementation.
* Participating in code reviews.
* Lead and mentor less senior members of the team.

### You can bring

* English skills
* Teamwork

### Why it would be awesome to work with us

* Competitive and attractive salary
* Annual bonus (13th salary)
* International, dynamic, friendly working environment.
* Free English training courses with foreign teacher.
* Well-equipped facilities: laptop, IMAC, or PC with 2 monitors
* Clear and stable career growth
* Many opportunities for personal and professional growth.
* Annual performance review: recognize your efforts and identify development/ improvement needs
* Regular team building events, sport activities…
* Medical and Accident Insurance program
* Professional training

### Contact
Email: Phong.nguyen@groovetechnology.com
Title: [Front-end] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
