### ISSUE TITLE
VCCloud - Ruby Developer & Internship - Hanoi - FT

### ISSUE THREAD

**Issue by tunglam14** [awesome-jobs/vietnam#156]
## Location
- Hà Nội, Việt Nam
## Salary Expectation
- 400$ -700$
#### for both Internship & Developer:
- Đam mê lập trình, có khả năng **Convert Caffeine into Code**
- Yêu thích mã nguồn mở, thích vọc vạch
- Kiên trì; không ngại khó khăn, không bỏ cuộc trước thách thức
- Trách nhiệm cao trong công việc
#### for Developer:
- Có kinh nghiệm lập trình Fullstack Ruby trên Linux (hoặc OS X) tối thiểu 1 năm
- Đã từng làm việc với MySQL, MongoDB, Redis, Sidekiq...
- Có khả năng phân tích, thiết kế cơ sở dữ liệu
- Biết sử dụng git, git workflow
- "Guru" Javascript là hai điểm cộng
- Có hiểu biết về 1 trong các thuật ngữ: Docker, CI/CD, Agile Development, REST API là một lợi thế
- Có tư duy về mô hình hệ thống, luôn tìm cách tối ưu code
- Có 1-2 sản phẩm demo
### You’ll be responsible for
- Các Web Control Panel/Web API phục vụ hệ thống Cloud sử dụng Ruby on Rails
- Transactional Email system
- Các service dùng chung cho các hệ-thống/ứng-dụng khác (SOA)
### Benefits
- Được trang bị desktop/laptop xịn (i5/8Gb), mạng khỏe (10MB/s)
- **Được sử dụng Cloud/server thoải mái để thử nghiệm và làm chủ các công nghệ mới**
- Workflow làm việc tiên tiến, liên tục đc cải tiến
- Môi trường làm việc năng động, thoải mái (sếp dễ tính)
- Mức lương hấp dẫn - tương xứng với năng lực và kết quả công việc
- Chính sách BHXH, BHYT theo quy định của pháp luật
### Contact
- CV gửi về lamdt@vccloud.vn kèm link tài khoản Github, gitlab.com, Bitbucket của bạn nếu có

**Comment by joneslee85** [comment]
:+1: hộ

**Comment by hiendinhngoc** [comment]
:+1:

**Comment by itsjef** [comment]
Giờ còn tuyển và tuyển Intern/Junior không bác @tunglam14

**Comment by tunglam14** [comment]
@itsjef bạn gửi CV vào mail trên cho mình nhé.

**Comment by itsjef** [comment]
@tunglam14 done :gem:
