### ISSUE TITLE
Toripu - Backend Developer - HCMC - FT 

### ISSUE THREAD

**Issue by jessie-toripu** [awesome-jobs/vietnam#1562]
## Location
Within/near District 1 of Ho Chi Minh City.

## Salary Expectation
$700 to $2000+, depends on experience, skill and expected salary.

## Requirements

- 1+ years of hands-on experience in backend designing, developing, testing and deploying applications in any language or stack.
- Data modelling experience in both Relational and NoSQL databases.
- Ability to design, build and optimise backend application for maximum speed, scalability and availability.
- Ability to implement security and data protection.

### Good To Have
- Knowledge of unit testing and design patterns is a plus
- Having knowledge of devops is a plus. Able to streamline and accelerate interactions between development and operations.
- Experience in Golang is a plus.
- Experience in AWS/GCP a plus. Have experience with container technologies: CGroups, Docker, Rocket, LXC etc is a plus.
- Experience in ElasticSearch is a plus.
- Prior experience of a travel based startups is a plus.

### Must Have

- Good knowledge of data structures and algorithms.
- Able to design and build highly scalable, reliable and fault tolerant systems.
- Have basic knowledge of AWS/GCP.
- Have knowledge of security and data protection measures.
- Drive for excellent engineering: Improving process and best practices.
- Passion for learning new things and solving challenging problems.
- Ability to Get Stuff Done!
- Communication and presentation skills in English is a MUST, other languages are advantage

### Responsibilities

- Support front-end development with server side logic implementations.
- Design, write and maintain backend codes. Ensure code is understandable to other team members.
- Implementation of security and data protection.
- Design and implementation of data storage solutions.
- Contribute to API Infrastructure design and set up.
- Respond immediately to live backend issues and fix quickly.
- Contribute to the evolution of the technology, product and experience.
- Quickly grasp concepts, problems and implement solutions with guidance.
- Communicate, collaborate and work effectively across cross-functional teams in a global environment.

### Why it would be awesome to work with us
- No overtime. We respect work-life balance.
- We keep sustainable pace by working 8 hours/day from Monday to Friday, ensuring we only plan for what we can achieve.
- We value your commitment, ensuring biannual salary review based on your performance and results.
- We are open and flexible as long as you can get stuff done.
- We believe in continuous learning of new technologies and we want you to strive for excellence in software engineering.

### About Us
We are building Asia’s new, exciting and upcoming travel app that connects travellers and drivers to bring better and more enjoyable travel experiences. We are planning to build web and mobile apps for our product.

The Vietnam team is expected to have 20+ manpower, including tech, business and finance teams.

**At Toripu Pte Ltd, we are committed, collaborative, driven, fast paced and innovative. We are looking for passionate people to join the pioneer team and lead their respective fields.**

Moreover, we believe in taking good care of our employees especially those with good working attitude and able to get things done. 

> Work hard, play hard. 

> A dream you dream alone is only a dream. A dream you dream together is reality. - Yoko Ono

### Contact
Homepage: [toripu.com](toripu.com)
Email: [contact@toripu.com](mailto:contact@toripu.com) (skype:jessie.jiang_7)

![Hiring_Post_Vietnam_IG copy 8](https://user-images.githubusercontent.com/47729247/57497479-0c991a80-7302-11e9-8666-b7816db1201d.png)
![IG_Hiring_Post_IG copy 7](https://user-images.githubusercontent.com/47729247/57497484-10c53800-7302-11e9-9c84-42896c89fd64.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
