### ISSUE TITLE
Toripu - Mobile Developer (iOS/Android) - HCMC - FT

### ISSUE THREAD

**Issue by jessie-toripu** [awesome-jobs/vietnam#1566]
## Location
Within/near District 1 of Ho Chi Minh City.

## Salary Expectation
$700 to $2000+, depends on experience, skill and expected salary.

## Requirements

- 1+ years of hands-on experience in developing and testing apps on Android or iOS for large scale applications.
- Up-to-date on modern Android or iOS programming paradigm.
- Experience in programming in RxJava/Kotlin (Android), Objective-C/Swift (iOS)
- Able to write high-quality code which is modular, functional, testable and reusable with excellent unit test coverage.
- Able to plan, develop and optimise frontend application for maximum speed, quality and responsiveness.
- Able to troubleshoot issues effectively. 
- Have working knowledge of several architectural approaches, caching, data storage and security.
- Experience with the publishing process for Apple or Google app stores.

### Good To Have
- Strong foundations in OOPs, Design Patterns, Clean Code fundamentals.
- Understanding of MVC, MVP, MVVM
- Good understanding of agile methodologies, TDD and test automation.
- Good understanding of continuous integration and continuous delivery principles and related tool stack.
- Knowledge about UX/UI on mobile is a plus.
- Knowledge of analytics is a plus.
- Prior experience of a travel based startups is a plus.

### Must Have

- Working experience with popular libraries on Android or iOS.
- Able to design and build highly scalable, reliable and fault tolerant systems.
- Produce fully functional mobile applications writing clean code
- Have basic knowledge of security and data protection measures.
- Drive for excellent engineering: Improving process and best practices.
- Passion for learning new things and solving challenging problems.
- Ability to Get Stuff Done!
- Communication and presentation skills in English is a MUST, other languages are advantage

### Responsibilities

- Build and improve the mobile experiences for a mobile app in travel.
- Gather specific requirements and suggest solutions
- Design and build highly scalable, reliable and fault tolerant systems.
- Implementation of security, caching, data storage.
- Identify bottlenecks and fix bugs.
- Unit test code for robustness, usability and reliability.
- Quickly grasp concepts, problems and implement solutions with guidance
- Monitor the performance of the live apps, respond to fix live bugs quickly and continuously improve them on both code and experience level.
- Evaluate new mobile methodologies and technologies. Contribute to the evolution of the technology, product and experience.
- Communicate, collaborate and work effectively across cross-functional teams in a global environment.

### Why it would be awesome to work with us
- No overtime. We respect work-life balance.
- We keep sustainable pace by working 8 hours/day from Monday to Friday, ensuring we only plan for what we can achieve.
- We value your commitment, ensuring biannual salary review based on your performance and results.
- We are open and flexible as long as you can get stuff done.
- We believe in continuous learning of new technologies and we want you to strive for excellence in software engineering.

### About Us
We are building Asia’s new, exciting and upcoming travel app that connects travellers and drivers to bring better and more enjoyable travel experiences. We are planning to build web and mobile apps for our product.

The Vietnam team is expected to have 20+ manpower, including tech, business and finance teams.

**At Toripu Pte Ltd, we are committed, collaborative, driven, fast paced and innovative. We are looking for passionate people to join the pioneer team and lead their respective fields.**

Moreover, we believe in taking good care of our employees especially those with good working attitude and able to get things done. 

> Work hard, play hard. 

> A dream you dream alone is only a dream. A dream you dream together is reality. - Yoko Ono

### Contact
Homepage: [toripu.com](toripu.com)
Email: [contact@toripu.com](mailto:contact@toripu.com) (skype:jessie.jiang_7)

![Hiring_Post_Vietnam_IG copy 8](https://user-images.githubusercontent.com/47729247/57497479-0c991a80-7302-11e9-8666-b7816db1201d.png)
![IG_Hiring_Post_IG copy 7](https://user-images.githubusercontent.com/47729247/57497484-10c53800-7302-11e9-9c84-42896c89fd64.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
