### ISSUE TITLE
Groove Technology - .NET Developer - HCM - FT

### ISSUE THREAD

**Issue by Nguyenphong1226** [awesome-jobs/vietnam#1567]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - $1,300/month

## Requirements
* Microsoft Stack (C#)
* .NET
* 3+ Years of experience

### Must Have

* Having more than 2 years of work experience as an Engineer delivering projects using Microsoft Stack (C#)
* Strong understanding of object-oriented programming
* Strong experiences in developing complex SQL queries, stored procedures, views and functions
* Understanding of index design and T-SQL performance tuning techniques
* Knowledge of software development and user interface web applications
* Experience with source control such as TFG / SVN / GIT

### Ideally

* Having methods for problem solving
* Having analytical thinking abilities
* Having a competent judgment to inform problems to superiors on time
* Experience managing timelines and task priority
* Strong written and verbal communication in English
* BScdegree in Computer Science or relevant field

### Responsibilities

* Reporting to the Project Manager and Technical Lead.
* Modifying databases and products according to client needs and perform tests
* Optimize and maintain legacy systems
* Solve database usage issues and malfunctions
* Liaise with developers to improve applications and establish best practices
* Identify and mitigate risk in the projects implementation

### Why it would be awesome to work with us
* International, dynamic, friendly working environment.
* Clear and stable career growth
* Many opportunities for personal and professional growth.
* Regular team building events, sport activities…
* Medical and Accident Insurance program
* Professional training
* Competitive and attractive **salary**
### Contact
Email: Phong.nguyen@groovetechnology.com
Title: [.NET] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
