### ISSUE TITLE
Chopp.vn - Backend Engineer - HCMC - FT/C

### ISSUE THREAD

**Issue by constantx** [awesome-jobs/vietnam#1568]
![logo-v4-color@0 5x](https://user-images.githubusercontent.com/113969/57604139-a58f9600-758d-11e9-9b96-0c3f13321581.png)

## Location
* District 1, Saigon, Vietnam

## Salary Expectation
* $400 - $1500 (Junior -> VP)

## Requirements
* Strong experience in JavaScript/Node.js, Go or Python
* Solid understanding of RESTful APIs
* 2+ years of experience in any of the following languages: JavaScript (preferred), Python, Go
* Experience building medium to large scale infrastructure on AWS
* Writes clean, modular and readable code
* Comfortable in Linux/Unix environment
* Comfortable with web technologies (HTML, CSS and Javascript) and web application frameworks
* Comfortable with source code management practice using Git/GitHub

### Must Have (or "How To Be Awesome at Chopp")
* Be open-minded, collaborative, accountable, yet independent
* Grow others as you grow yourself
* Don’t tolerate BS, question authority and say what you mean
* Embrace uncertainty and face challenges head on
* Pay attention to details
* Be passionate and take ownership of your work
* Be scrappy and take iniative
* Proficient English communication skills and writing
* Have a deep curiosity and passion for how things are designed, how things work and how to best bring ideas to the world

### Ideally
* Writes clean, modular and well-documented code
* Attention to details and ability to see the big picture
* Entrepreneurial spirit and self-motivated
* Ability to prioritize tasks in a fast-paced environment
* Collaborates and works efficiently with cross functional team
* A real passion for building product with good user experience

### Responsibilities
* Develop, optimize, maintain, scale Chopp's E-commerce and Logistics platform
* Work with the mobile engineering team to implement and improve our product experience
* Support the marketing and operation team with data analytics

### Why it would be awesome to work with us
* Make a difference and make people’s lives better
* True startup culture with no BS
* Generous stocks / equity
* Cutting edge technology stack
* Awesome product/perks/office
* Cool, talented and passionate colleagues
* Snacks & drinks in office
* Live the brand: use Chopp with no service fee!
* Bi-weekly team happy hour
* Tickets to events and workshop
* Paid holiday
* Quarterly team Off-Site

### Contact
* [careers@chopp.vn](mailto:careers@chopp.vn)
* See more: https://chopp.vn/careers/
* Apply: https://chopp.vn/apply/

![Chopp vn on Shark Tank](https://user-images.githubusercontent.com/113969/57604346-1d5dc080-758e-11e9-8c7c-07d26ceb2135.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by constantx** [comment]
@qcam how can we renew this? New issue?

**Comment by qcam** [comment]
Please create a new one. Thanks.
