### ISSUE TITLE
Fetch - Front-end Developer (Senior) - HCM/HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1569]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9.

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District. 

* 3rd Floor, Dai Phat Building - 82 Lane, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2500.

## Job Description

The project is about providing B2B2C digital wealth/robo advisory platform for banks, brokers, wealth managers and insurers.
We are looking to add a front-end engineer to our engineer team as we build and customize and launch products the B platform. The successful incumbent will have ample opportunity for broad exposure across the company and with clients in various geographies.
We are looking for a multi-tasker who appreciates the rewards and understands the pressures of working in a startup.

## Skills Requirements
  * Degree in computer science or a related field, 5+ years of software development experience.
  * At least 1 year of experience with Angular 2+ tech-stack. Some keywords you should be familiar with: TypeScript/EcmaScript 6, Reactive Programming (RxJS), NgRx/Store, Functional Programming, Angular Reactive Form, Angular Routing, Lazy Loading.
  * Strong programming skills and base knowledge: OOP, SOLID, Data Structure and Algorithm, software development design patterns.
  * Excellent English communications and interaction skills.
  * Knowledge of Continuous Integration and Automated Testing is a plus: Webpack, Docker, Karma, Protractor, Browser Stack.
  * Mobile app development experience is a bonus (NativeScript, Ionic, PWA).
  * Experience with a front-end chart library (Highchart) is a plus.
  * Have been working in finance service related companies or a fintech startup is a plus.

## Why it would be awesome to work with us
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
### What we offer:
  * Be part of an incredible team of people from all over the world.
  * Work in a rapidly expanding team and grow your responsibilities in time.
  * Immense learning opportunity in Blockchain and Cryptocurrencies.
  * Competitive salary, motivation package, and all kinds of small perks to keep you happy with us.
  * An environment that encourages self-development, learning, and growth.
  * “Work hard, play hard” culture - regular team events from skiing weekends and trekking to happy-hours and board game nights.

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
