### ISSUE TITLE
Futureworkz - Ruby On Rails Developer (Have training) - HCMC - FT 

### ISSUE THREAD

**Issue by FutureworkzVietnam** [awesome-jobs/vietnam#157]
## About us

Futureworkz is a Singapore-based Web Design company that specialized in Agile development with (mainly) Ruby on Rails. We are a strong vibrant team of designers and developers. All our projects are mainly from Singapore.

We are a totally geeky company that loves coding and designing for great web and mobile applications. We adopt world-class development methodologies and project management processes.

Futureworkz is a learning and family culture company. The world is moving fast and we are constantly evolving ourselves to learn new things and adopt new thinking.

Join us to grow yourself as a developer and as a person. Let's grow together!
## Location

Binh Thanh District, HCMC
## Salary:

**$700 - $1800**
- We are looking for highly-motivated and totally-geekish Ruby on Rails programmers to develop web app. We have a wide diversity of projects from NoSQL data system, ReactJS interface, video streaming, chat apps, mobile apps, API servers and of course the plain-O-simple-sites.
- There will be a 2-week training course of Ruby on Rails at our company. After the course, you can get a chance to work at Futureworkz.
## Scope of work:
- Develop & maintain web applications
- Participate in daily standups and sprint meetings
- Participate in client and project manager meetings
- Provide assistance to project manager in managing projects
- Do presentation or workshop on new technologies to co-workers
- Learning English
## Benefits:
- Macbook is provided for work which you can bring home
- Opportunity to be on business trips overseas
- Review salary 2 times a year
- 5 work days a week
- 14 days paid annual leave
- 3 days paid compassionate leave
- 7 days paid medical leave
- 13th month bonus
- Social insurance
- Monthly gathering programs
- Annual company holiday
- Code training
## What you will grow into:
- Improve your English
- Will be able to manage a project by yourself with Singapore clients
- Will be able to consult clients on their business objectives aligned with development needs
- Will become an experienced Ruby on Rails developer with many different kinds of projects under your belt
- Will adopter of world-class development practices such as Git, CI, CM tools, TDD
- Will be able to contribute back to the world through presentations or OSS
## Requirements:
- All Fresh graduates and experienced coders can apply.
- Programmers from any language (PHP, Java, iOS, etc..) are all welcomed. We will train you to code in Ruby on Rails.
- Have knowledge of HTML, CSS, JavaScript
- Able to understand English is a plus
- An open mind to learn
- Team spirit to work and learn together
- Willingness to share with others

To understand what kind of company we are and what kind of coders we are looking for, you can refer to our company playbook at the following link:
https://github.com/futureworkz/playbook
## Contact

Any interested CV please send to recruitment_at_futureworkz_dot_com 
You can visit our website at: http://futureworkz.com/

**Comment by joneslee85** [comment]
Thanks for the post. Please up the heading style to ensure they are all consistent.

For the salary expectation, please split the number to a new line. You can bold it if you like.

**Comment by FutureworkzVietnam** [comment]
Hi joneslee85, thank you for your comment. I have edited as your advice.

**Comment by quocnv** [comment]
:+1:

**Comment by FutureworkzVietnam** [comment]
Hi joneslee85, please help me add labels for this post. Thank you.

**Comment by FutureworkzVietnam** [comment]
Thank you @huydx :+1:

**Comment by hienvd** [comment]
:+1:

**Comment by FutureworkzVietnam** [comment]
Updated
