### ISSUE TITLE
Fetch - Full-stack Python Developer (Senior) - HCM/HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1570]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9.

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District. 

* 3rd Floor, Dai Phat Building - 82 Lane, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2500.

## Job Description

The project is about providing B2B2C digital wealth/robo advisory platform for banks, brokers, wealth managers and insurers.
We are looking to add senior full stack python developer to our team of engineers as we build and customize and launch products the B platform. The successful incumbent will have ample opportunity for broad exposure across the company and with clients in various geographies.
We are looking for a multi-tasker who appreciates the rewards and understands the pressures of working in a startup.

## Responsibilities:
  * Develop backend Restful API for financial applications/tools using Django Python framework to help investors build, customise and analyse their investment assets.
  * Write well-written logic code to optimize investment portfolio or planning long-term investment. (basic maximize/minimize problems in mathematic)
  * Building loosely coupled system which consists of many services/components and deploys these services to AWS infrastructure.
  * Work with different teams (in multiple regions) and follow Agile development processes.

## Skills Requirements
  * 4+ years of experience in web development with strong knowledge of Linux ecosystem, Agile, Git, working with CI/CD pipeline development process. 
  * Min 3+ year of experience in Python programming and Django with Django Rest Framework to build RESTful API backend.
  * Having 2+ year of experience with one of Single Page Application front-end technology (Angular/React) and have the ability to customise HTML5 and CSS template.
  * Experienced with Postgres RDBMS, NumPy, SciPy, CVXOPT, celery, wkhtmltopdf, nginx, AWS cloud infrastructure.
### Nice to have:
  * Have basic dev-ops skill and a good understanding of server side technologies (bash, SSH, Docker container, microservices, OAuth, JWT, AES encryption, etc ..).
  * Strong mathematic skill or having finance knowledge is a plus.- Familiarity with Test Automation Tools and Unit Testing frameworks.
  * Excellent problem solving and debugging skills.- Comfortable working with existing code and also writing code from scratch.
  * Team player with strong organizational and interpersonal skills.
  * Bachelor/Master graduated in Computer Science related fields.

## Why it would be awesome to work with us
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
### What we offer:
  * Be part of an incredible team of people from all over the world.
  * Work in a rapidly expanding team and grow your responsibilities in time.
  * Immense learning opportunity in Blockchain and Cryptocurrencies.
  * Competitive salary, motivation package, and all kinds of small perks to keep you happy with us.
  * An environment that encourages self-development, learning, and growth.
  * “Work hard, play hard” culture - regular team events from skiing weekends and trekking to happy-hours and board game nights.

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
