### ISSUE TITLE
Fetch - Java Developer - HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1571]
## Location

* 3rd Floor, Dai Phat Building - 82 Lane, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District.
* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * Up to $2500.

## Job Description

The project aims to make coffee more accessible and available through an ecosystem of technology and innovative solutions.

We are currently developing an IOT hardware as well as an online platform that is due for shipment and release in 2019. The development phase is quickly progressing as part of this exciting journey in launching a product and service, both made and designed for the global coffee market. We are working closely with award-winning industrial designers and highly experienced manufacturers to bring this project to fruition.

## Skills Requirements
  * 3+ years’ experience with Java/J2EE Full Stack Spring framework Developer: Java/J2EE, with Tomcat.
  * RESTFUL API Service Design and Integration.
  * Familiar with SQL and MySQL Database.
  * Software Development on AWS Cloud Platform.
  * Manage Advanced AWS Components (EC2, RDS, MQTT, Cloudwatch, S3 etc).
  * Source control with Git.
  * Degree in Computer Science or relevant fields.

### Nice to have:
  * Docker Related Skill.
  * AWS IOT Service Integration and AWS IOT Cloud Experience.
  * Experience Working with App Developers for 2+ Years.
  * Good reading and written communication in English language.
  * Average verbal communication in English language.

## Why it would be awesome to work with us
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
### What we offer:
  * Be part of an incredible team of people from all over the world.
  * Work in a rapidly expanding team and grow your responsibilities in time.
  * Immense learning opportunity in Blockchain and Cryptocurrencies.
  * Competitive salary, motivation package, and all kinds of small perks to keep you happy with us.
  * An environment that encourages self-development, learning, and growth.
  * “Work hard, play hard” culture - regular team events from skiing weekends and trekking to happy-hours and board game nights.

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
