### ISSUE TITLE
Lecle Vietnam - Senior Backend Developer (NodeJS) - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1573]
## Location
* Q7/Q1
* Saigon, Vietnam
* Remote

## Salary Expectation

*up to $2000/month

## Requirements
* 4+ years of experience in the related field
* Familiarity with common design patterns and OOP techniques
* Solid understanding of Web Technologies: HTTP, AJAX and RESTful API
* Understanding of how Scrum and Agile work
* Profound understanding of Version control systems (Git)

### Benefits
* Highly competitive salary
* 13th-month salary + Year-end bonus
* MacBook Pro provided
* 15 days of annual leave
* Onsite opportunities in Korea every 3 years
* Company trip at least once a year & company dinner once or twice a month
* Free coffee, drinks, and snack
#### Contact
Phone: 028-5416-5548
Send your CV to email: career@lecle.co.kr

##### Know more about us
* Facebook: www.facebook.com/LecleVietnam
* Homepage: https://www.lecle.co.kr/
* Medium page: https://medium.com/leclevietnam

**Comment by lehoangduc** [comment]
Is this Part-time or Full-time job?

**Comment by trungnguyenhr** [comment]
> Is this Part-time or Full-time job?

Hi, thanks for asking. This is Full-time job.

**Comment by lehoangduc** [comment]
> > Is this Part-time or Full-time job?
> 
> Hi, thanks for asking. This is Full-time job.

Do you have skype for chatting?

**Comment by trungnguyenhr** [comment]
> > > Is this Part-time or Full-time job?
> > 
> > 
> > Hi, thanks for asking. This is Full-time job.
> 
> Do you have skype for chatting?

Yes, of course. Please send me your Skype ID and I will contact to you soon.

**Comment by lehoangduc** [comment]
> > > > Is this Part-time or Full-time job?
> > > 
> > > 
> > > Hi, thanks for asking. This is Full-time job.
> > 
> > 
> > Do you have skype for chatting?
> 
> Yes, of course. Please send me your Skype ID and I will contact to you soon.

Please add bi.duc.vt. Thanks.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
