### ISSUE TITLE
TurndotMedia - Jr Python Fullstack Developer - Remote - FT/PT

### ISSUE THREAD

**Issue by meckin** [awesome-jobs/vietnam#1579]
## Location

* Remote

_For the first 8-12 months the job will be completely remote; however, we're looking to add offices within Saigon within the next 8-12 months. That being stated, if you don't live in SGN we're not requesting you to relocate.  We'll love for you come in once in a while._ 

## Salary Expectation

* 1000 for 20-25 hours a week

## Requirements

* 4+ years of experience in web development with strong knowledge of Linux ecosystem (ubuntu), development process.
* Comfortable with web technologies (HTML, CSS and Javascript) 
* 2+ years of experience with Python language including apps like Django and Flask
 * 1+ years experience with PostgresSQL with a strong ability on creating queries and minimizing lookup times.  
* Experience with Nginx (We're using Openresty)
* Experience with web scrapping (no framework required)
* Willingness to learn or experience with Python Async 
* Quiet place to work

### Must Have

* **Proficient English communication skills and writing**
* Be openminded and willing to learn about new technologies 
* Question everything, but understand the goals
* Move fast and break things (Sorry for the Facebook motto).... but its true.. We care more about pushing, testing, and then redefining (we're not working on clients stuff, so we're more understanding to bugs.)... Sometimes things just work, even if they are ugly! 
* Foresee issues that might happen within the production environment and make a risk assessment to define within our priorities.
* Willingness to understand what needs to be done vs what is nice to have... (busy work is a no no)
* Focus on built-in Python features that make sense instead of always adding complexity
* Talk to non-developers to help build out ideas
* Eye for automation 

### Ideally

* Experience with following libs (Github if you don't know)
```
- Sanic
- Redis
- html5-parser
- jinja 
- Flask
```
* Consist hashing 
* Mirco services 
* Randomization algos 

## Job Description / Introduction

We're currently moving forward on building out what was once a side project into a full flagship project. 

As it stands we have a collection of applications that have a strong codebase that need further development and retooling. 

New developer task is to dig deep into the code base, focus on current priorities, and further the application for improvements. 

In a sense take over as lead developer of the project. 

### Responsibilities

- Develop, optimize, maintain, scale existing apps
- Develop redundancy to limit the amount of downtime
- Create well-documented code

### You can bring

* FUCK YES attitude

### Why it would be awesome to work with us

* Working on solutions that most people WILL NOT encounter in their career ie an app that deals with 12-30 million web request per DAY.. YES PER DAY!

* We want someone that is interested in being at the ground floor of things, become a key player in the company. 

* We're completely honest about our limitations as a company, and what things we're looking to improve upon. 

* Introduction into the affiliate marketing space 

* No office political or nonsense like that... We want to stay small in terms of man power, but use tech for what it should be used for... To scale things. 

* We're not seflish, if we grow, we want to bring you with us. 
* We respect your time, family, and life.
* If you're the same person in 6 months.... we'll feel bad for you.
* No BS!
* Sorry we don't have sneaks, but we're growing and we respect the fact you might not like sneaks lol. 
* We believe in team grow above all 
* CODE SOMETHING DEPLOY LIVE! Yep... deploy live always... We do this for a reason 
* 13 Months Salary + Increase salary over time based on performance 

### Contact
Email me charles@turndotmedia.com

**Comment by meckin** [comment]
Updated information

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
