### ISSUE TITLE
New Begining Media (NBM) - Front-End Developer (AngularJS, NodeJS, ReactJS) - Hanoi - FT

### ISSUE THREAD

**Issue by NhaHien** [awesome-jobs/vietnam#1580]
## Location

* 5th Floor, P501 Vinahud Tower, Trung Yen 9 street,  Cau Giay District, Hanoi

## Salary Expectation

* From $500 to $1,000

## Requirements
* At least 6 months to 1 year experience with Front-End
* Have knowledge/Experience with framework (AngularJS, ReactJS, NodeJS)

### Must Have
* Basic English 

### Responsibilities
* Implementing the company's product development projects
* Working with modern technology based on ES6, React, Redux, GraphQL
* Actively discuss and advise on the Back-end API

### Why it would be awesome to work with us
* Competitive offer up to $ 1,000
* Friendly working environment  dynamic, diverse, with many promotion opportunities
* The Company's benefits: birthday, lunch at the company, ... are held periodically.

### Contact
Homepage: nbm.vn
Email: it.huynhnguyennhahien@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
