### ISSUE TITLE
Technical Product Manager

### ISSUE THREAD

**Issue by spencerluu167** [awesome-jobs/vietnam#1581]
## Location

* Hanoi, Vietnam
* Full time

## Salary Expectation

* $2000/month 

### Responsibilities
•	Work closely with other team members (product manager, software engineers, research engineers, QA, tech lead).
•	Participate in feature design, product roadmap development, experiment design and execution.
•	In charge of writing user stories and technical specs
•	Represent the technical product team in Vietnam and help engineers and QAs understand every single detail of each technical product feature
•	Own product release schedule, work closely with engineers and QA teams to make sure that every release is high quality and timely
•	Collaborate with other teams to prepare for public release and gather feedback

### Must Have
•	Attitude: self-motivated, driven, responsible, detail-oriented.
•	Computer Science, Mathematics or Engineering undergraduate degree or equivalent plus hands-on software engineering experience
•	Above average project management skills
•	4+ years experience delivering highly successful and innovative Internet products with tons of users; including experience in an operational service delivery capacity
•	Excellent English skills
•	Get it done attitude

### Ideally
•	Startup experience
•	Experience working with distributed development teams.
•	Prior experience as a Product Owner in an scrum team

### Why it would be awesome to work with us
•	Young, vibrant, hard-working, and all-in startup team.
•	Free lunches.
•	Free diners if working at the office past 7pm.
•	Free food and snacks all the time (some of us gained 5-7kgs since started working at Got It).
•	Monthly gym/health class benefit.
•	Transportation compensation for working errands.
•	Macbook is our standard but can always provide you what helps you work the best.
•	Team outing, happy hours, etc.
•	Working with leaders in the team based in Silicon Valley.

### Contact
Homepage: https://got-it.ai
Luu Nguyet: nguyet.luu@fa.net.vn ; 0359 625 873

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
