### ISSUE TITLE
Sun* (new brand of Framgia) - Frontend Developer - Hanoi/Danang - FT

### ISSUE THREAD

**Issue by blien1994** [awesome-jobs/vietnam#1584]
## **Location**
* Hanoi: Keangnam Landmark 72 Tower, Nam Tu Liem, Hanoi
* Danang: FHome Building, 16 Ly Thuong Kiet Str., Hai Chau district, Da Nang

## **Benefits**
* 600 - 1500 USD (full salary on probation)
* Lunch + transportation allowance
* Premium AON healthcare insurance

## **Requirements**
* Strong knowledge about HTML5, CSS3, JavaScript
* At least 1 year working experience as a frontend developer
* Experience with Agile method

### **Why it would be awesome to work with us**
* Dynamic and young working environment, full of challenges that can enhances your skills to the next level
* A large pantry with free foods and drinks
* Various interesting hobby clubs for you to discover

### **Contact**
Fell free to contact Ms Lien for more information:
* Skype: live:do.bichlien
* Email: do.bich.lien@sun-asterisk.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
