### ISSUE TITLE
TIKI - SDE (Software Development Engineer) - HCM/HN - FT

### ISSUE THREAD

**Issue by TanHR** [awesome-jobs/vietnam#1585]
## Location

* HCM: Floor 3 - Viettel Building - 285 CMT8, Ward 12, District 10.
* HN: VIT Building, Kim Ma, Ba Dinh.

## Salary Expectation: Up to 2k

* We are Tiki.vn - the most trusted E-Commerce platform in Vietnam. We serve millions of customers and post 3-digit growth every year. On a typical day, our system handles over 200 million database transactions, enabling thousands of sellers and staffs to operate on the platform. Every piece in Tiki’s system has to be reliable, stable and scalable.

* Tiki Marketplace platform allows sellers to promote and sell their products to millions of customers. Product quality always comes first at Tiki, thus it is our mission to empower sellers with such products to grow their online businesses.

## Marketplace system has great responsibilities at:

1. How to manage a thousand sellers efficiently? It allows sellers to register, manage their accounts, permissions based on their role.

2. How to manage a million products with complicated attribute structure and many kind fulfilment processes?

3. How to operate a sophisticated order business flow?

4. How to report revenue of thousand sellers with flexible commission/fee model?

5. How to provide high-performance API to other systems that can handle at least 1k requests per second and 4 million data changes per day

6. How to integrate in real time to various kinds of system:

* Warehouse system to manage inventory adapt to multiple warehouse location
* Accounting system to report revenue
* Order system to manage order flow
* Caching/Indexing system to update high-performance data source such as Redis, Elastic, Mongo Database…

## _We_ are looking for talented software engineers who’d love to tackle challenges in a complex E-commerce system. You will be building and optimizing critical components of the platform:

* Catalogue management system: scale up management of millions of physical and virtual products. Technology: PHP, MySQL, Kafka

* Indexing system: ensure smooth propagation of changes between databases and provide fast data access to be able to handle thousands of messages per second. Technology: Java, Kafka Stream, Mongo, Elastic...

* High-performance product catalogue API: scale up the highest throughput API in Tiki’s system. These APIs have to handle at least ten thousand requests per seconds. Technology: Node.JS, Mongo, Redis

* Seller management system: help internal staff manage sellers registrations and set up advanced commission/fee model. Technology: PHP, MySQL

* Order management system: help sellers process their orders as fast as possible. Technology: PHP, MySQL

## Inside our engineering team:

* We iterate constantly. There's no such thing as the best version of anything, just a constant streams of improvements and tests.
* We move fast, really fast. Major changes can be executed in a few days, many times just a few hours.
* We have a data-informed mindset. We try to use data to inform our decision as much as possible.
* We are independent. Most of the time, your team will not need technical assistance from other teams.
* We take risks. We're not afraid to challenge "best practices".
## Our attractive offers include:
* Open communication with passionate and experienced members.
* Challenging working environment.
* Easy access to the library with tons of startup, product, UX, coding... books.
* Private healthcare insurance.
* Annual health check-ups.
* Special internal programs for Tikiers when shopping on Tiki.vn (free ship TikiNow service, discount...).
* Internal events to bond our mutual understanding & spirit such as team building, team outing, * Tiki's birthday, year-end party...
* New & beautiful office with a pantry room (with bar), entertainment & gymnastic equipment, yoga rooms, a library and an open space facilitating cross-department communication.
Competitive salary and performance review (twice a year), 13th-month pay based on performance.

## Skills
* Bachelor of computer science
* Good at problem-solving
* Good at least one of programming languages: PHP, Java, Python, Node.Js, Go, C/C++ ...
* Good at OOP
## For senior require more:
* 5+ years of Software Engineering, with a proven track record of delivering large-scale, distributed, web-based production systems.
* Understanding of design for large scalability, performance and reliability.
* Experience working on a large scale deployment and performance tuning.
* Strong at object-oriented analysis and design.

### Contact
HP: 0916 555 337
Skype: hoaitan.hr@outlook.com
mail: tan.trinh@tiki.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
