### ISSUE TITLE
1 NodeJS Backend ($1300-$2000) - Javac - HCM

### ISSUE THREAD

**Issue by nguyennm621992** [awesome-jobs/vietnam#1588]
## Location

* 19A Cong Hoa Street, Tan Binh District, Saigon, Vietnam
* Full-time

## Salary Expectation

*  $1300-$2000

## Requirements
* 2 years of experiences with NodeJS, React.JS and Redux.
* Strong knowledge of HTML5/CSS3.
* Understanding of native Javascript es5 & es6+.
* Strong UI/UX experience and pay attention to improve website performance.
* 1-2 years experiences with Fullstack (PHP) is a big plus.
* Ability to communicate, read, and write in English.

### Must Have

* English verbal

### Ideally

* Experience with NodeJS

### Responsibilities

 * Implementing High Quality web site/application
 * Integrating the front-end elements built by your co-workers into the application.
 * Testing carefully functions, projects before delivering to customers.
 * Sharing development knowledge, challenges with other members.

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

* 13 month salary per year
* Performance bonus
* Performance appraisal once a year and you could request unlimited to be reviewed whenever you like
* Social – Health – Insurance paid fully
* Healthcare: Annual health check-up, Premium Health Insurance
* Annual leaves: 12 days
* Football club
* From Vietnam, we have crafted brilliant products for millions of users in the US.
* We’re committed to investing in our people and building a workplace you’ll love coming to every day.
* Building large-scale & latest technology software products
* Working & growing with Passionate & Talented Team
* Attractive Salary and Benefits
* Flexible working time
* Free in-house entertainment facilities: tea, coffee and snack (instant noodles, cookies, candies…)
* Western management style: professional, dynamic, open minded, creative, supportive, friendly, and encouraged for feedback.
* Company trip, big annual year-end party every year, team building, etc.

### Contact
Skype ngo.minh.nguyen
Email: nguyen@javactechnology.com
Phone: 0907000592
Facebook: https://www.facebook.com/mine.ngo
Messenger: https://www.messenger.com/t/mine.ngo

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
