### ISSUE TITLE
dataPlor - Full Stack Rails Developer - Remote - FT

### ISSUE THREAD

**Issue by rurabe** [awesome-jobs/vietnam#1590]
![dataPlor](https://assets.dataplor.com/random/header.png)

## Location

* You - Remote, probably in Vietnam
* Us - Based in the US

## Salary Expectation

* $1500USD - $3000USD / month

## Skills
* Great Ruby skills
* Know Rails inside and out
* Know your way around SQL

## Requirements
* You would be the third member of our engineering team, so you will be working closely with our CTO and mobile engineer. As a key member of a small team, **great communication skills** (and fluency in English) is essential.
* Our API is written in Ruby using Rails and **strong experience with RoR** is required.
* We believe in testing, and use Rspec to unit and integration test our API. You should be **familiar with testing techniques** and have a sense of when testing is appropriate and when it’s not.
* We store data in a SQL database, and use SQL liberally throughout the app to improve performance. We also use SQL to generate data reports that Operations and Sales rely on, so you should be **proficient in SQL**.

### Ideally

* We maintain multiple client apps that consume our API that are written in Javascript using React. The ideal candidate would be **proficient in Javascript** as well, but at a minimum you should have some experience with Javascript and be willing to work towards productivity in React.
* We have a mobile Android engineer, but if you can **contribute in Kotlin** as well, that’s a huge bonus.
* We are heading towards products that incorporate **Natural Language Processing**, so experience with that would also be a huge bonus.

### Responsibilities

* Maintain and build APIs for our multiple client apps
* Analyze and improve performance of the API
* Develop multi-modal communication flows over email, SMS, in-App notifications
* Build awesome internal tools to support sales and operations
* Contribute to the web and android client apps

### Why it would be awesome to work with us

* We are a young company who work remotely but move fast to hit our goals. 
* You'll be given as much responsibility as you can handle, and the sky's the limit.
* We're trying to build a world class group of people who are solid, well-rounded engineers for our tech team.
* We promote learning and growing the skillset of every member on the team.
* We have daily standups, and get together a couple of times a year to interact with each other face to face, eat, drink, and have fun together.

### Our tech team so far
[![Ryan](https://media.licdn.com/dms/image/C4D03AQGgtsv-jBjHag/profile-displayphoto-shrink_200_200/0?e=1564012800&v=beta&t=NYaY9Tv6tHNrdCCKLZV4j8n9Tb5CHq9vJSy6go03mW0)](https://github.com/rurabe)
[![Edgar](https://media.licdn.com/dms/image/C4D03AQEWon6VJaUmTA/profile-displayphoto-shrink_800_800/0?e=1564012800&v=beta&t=yWrcB3-n-mbWZhfQojHD31rbng-7L46RujBVC2uFsaY)](https://github.com/edgarplor)

### Contact
Homepage: https://www.dataplor.com
Email: adam@dataplor.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
