### ISSUE TITLE
Senior/Lead Ruby on Rails developer DevOps/AWS (Ho Chi Minh – Singapore)

### ISSUE THREAD

**Issue by clement-chretien** [awesome-jobs/vietnam#1592]
## Location

* Saigon, Vietnam
* Singapore

## Salary Expectation

* +$3000/month 

## Who are you?
Are you an experienced Ruby on Rails developer/leader with interests in DevOps practices and Cloud computing using AWS? We are looking for you! This is an amazing chance to work with a fast-growing American start-up based in HCM and Singapore! Take a step up in your career today and get in touch with us.
Below more information about the scope of work: 

## Requirements
•	Design, develop and maintain our core operational systems utilizing clean, maintainable code.
•	Help to plan, oversee and implement new features within our product and systems.
•	Partner with product managers, designers and QA engineers to bring life to new features and products.
•	Utilize monitoring and logging to improve the quality and speed of our codebase.
•	Evangelize best practices within the engineering groups.
•	Help to develop our internal processes and tools as we move towards a fully automated Cl/CD process.
•	Perform and participate in code reviews and "lunch and learns" to foster training and
•	development across the team.
•	Provide mentorship and support to junior team members.

## Skills
•	5+ years of professional Ruby on Rails experience with a proven track record of successful projects.
•	Expert using ROR & JavaScript.
•	Strong understanding of object-oriented programming best practices and design patterns.
•	Strong familiarity with data stores - we use MySQL, Redis, Memcached and Elasticsearch.
•	Significant experience building, scaling and supporting web applications both internal and consumer-facing.
•	Comfortable being productive independently while staying integrated with the larger engineering team.
•	Experience working with G it and Git Hub (specifically working with pull requests).
•	Excellent written and verbal communication skills.

### Ideally
o	Experience working with an agile team.
o	Familiarity with React, Redux or GraphQL is a big positive.
o	Knowledge working with data pipelines (we use Amazon Kinesis) and data & Bl platforms (we utilize TreasureData, Amazon Red Shift, Amazon Lambda and Cha rt.io).
o	Experience with service-oriented architectures.
o	Familiarity with AWS or Google Cloud Platform.
o	Experience doing DevOps work is a big plus (we prefer Ansible, Terraform and AWS but appreciate all experience!)

### Why it would be awesome to work with us

We are building a local talent network for global needs! 
We connect elite developers with Singaporean startups so they can grow their careers faster.

### Contact
For more information about the company, the role and the attractive salary – get in touch with Clement Chretien or Meraj Qazi asap. We will get back to you with information and feedback!
Please send an updated CV and information about your current situation to: 

clement.chretien@expanda.io
meraj.qazi@expanda.io

https://developers.expanda.io/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
