### ISSUE TITLE
LARION - Senior Web Dev (Python/ RoR/ PHP) - HCMC - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#1596]
## Location

* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation

* $1000 - $2500

## Requirements
* Bachelor Degree in Information Technology, Computer Engineering, Computer Science or related fields
* At least 1 years of hands-on industry experience in end-to-end web development
* Extensive experience in at least one server-side technology: Python/ Ruby on Rails/ PHP
* Experience with modern client-side framework or libraries such as ReactJS, AngularJS, etc.
* Experience in building scalable web applications in cloud-based environments
* Have excellent debugging and problem solving skills
* Have a working knowledge of Unix/Linux

## Skills
* Python
* Ruby on Rails
* PHP

### Responsibilities

We are seeking a hands-on Web Developer to join our mission-critical simulator development team. The selected candidate will help design and develop a next-generation, scalable, fault-tolerant, global online platform for quantitative financial modeling. Our next stage of growth includes expanding the global footprint of our web-based simulation engine, creating this new opportunity

### Why it would be awesome to work with us
* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year,
Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Free in-house entertainment facilities: coffee, football, table-tennis, boxing, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks, etc.

### Contact
Skype: ngoctranthibao (Ngoc Tran)
Email: recruitment@larion.com
Phone: 0356945706

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
