### ISSUE TITLE
Lecle Vietnam - Bridge Software Engineer (BrSE) - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1597]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Negoitiation

## Requirements
* 3+ years of experience in Software Development
* Good English communication skills
* Solid IT background knowledge
* logical thinking and analysis, self-motivated and eager to learn

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + Year-end bonus
* Macbook Pro provided
* 15 days of annual leave
* Onsite opportunities in Korea every 3 years
* Working with a passionate team and professional Korean experts
* Company trip at least once a year & company dinner once or twice a month
* Free coffee, drinks and snack

JD for detail: http://smrtr.io/39YN2
## Contact
* Phone: 028-5416-5548
* Send your CV to email: career@lecle.co.kr
## Know more about us
Facebook: www.facebook.com/LecleVietnam
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
