### ISSUE TITLE
Christina's - Senior Software Engineer (Python) - Saigon - FT

### ISSUE THREAD

**Issue by ChristinasVN** [awesome-jobs/vietnam#1601]
## Location
* Saigon, Vietnam
* District 1 

## About the company
Team Christina’s consists of world travellers, Vietnamese returnees, and local graduates, citizens, and entrepreneurs from all different backgrounds. We believe that in order to best understand and anticipate the needs of our guests, our team needs to reflect the diversity of our guests as much as possible.

## About our products
At Christina’s, we call ourselves a tech-enabled travel company. Having a technology team since the beginning is one of the most crucial conditions that enable us to scale up the company at a rapid rate, while still maintaining our amazing guest experience. In just 4 years, we have grown from 2.5 people in Saigon into a team of more than 400 people in 6 cities and we are still growing fast to other cities and countries. Together with that growth, technology is getting a more and more important role in the company.

Christina’s Tech team is working alongside with our operation teams to create software products that facilitate the team’s operation and enhance the experience of travelers. Our products range from operating software, booking websites, to communication apps, travel planning tools, and a lot more.

We are looking for more software engineers to join us on our road to become the #1 fully integrated travel experience company in the world.

Check-out our hosts technology at https://www.christinas.vn/host-tech/

## What will you do
* To create software products that enhance the experience of travellers and facilitate the team's operations.
* To be involved in every phase of the development process: ideation, development, launch, and maintenance.
* To be able to work closely with other teams.
* To keep the software products high-quality and maintainable.

## What will you need
* 3+ years of software development experience.
* Demonstrable ability to work on at least one of these types of software products: web apps, mobile apps, or desktop apps.
* Ability to quickly learn and adapt to new technologies. We do not have requirements on previous experience with any specific technology because technologies are continuously changing. Therefore, we believe the ability to learn is more important. (By the way, we are using Django, PostgreSQL, React and React Native).
* Ability to communicate, present ideas, and handle feedbacks constructively.
* Willing to help your teammates, share your knowledge with them, and learn from them.
* Ability to work independently with little or no supervision.
* Experiences on creating your own products are a big plus.

## What we offer
* Working very closely with the operation teams, you can see clearly the impact of your own works everyday.
* We encourage rotating between projects, and learning new technologies, so there will be a lot of chances to learn.
* Flexible working schedule, apart from a few (only a few) scheduled in-person meetings with team, you can decide on your own time and place to work. Our team members can work at the office, coffee shop, at home, when they can be most productive.

## How to join
If you think you have what it takes, then simply send us your CV and cover letter to get started: talent@christinas.vn or apply directly through our website: https://www.christinas.vn/joinus/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
