### ISSUE TITLE
NEC Vietnam (Japanese Company) - Front-End Developer (Onsite based in Vietnam) - HCMC - FT

### ISSUE THREAD

**Issue by NghiaHuynhh** [awesome-jobs/vietnam#1602]
## Location
* 9th floor  E. Town 3 Building, 364 Cong Hoa street, Tan Binh District, HCMC 

## Salary Expectation
* Negotiable

## Requirements
* 2+ years Front-End experience (HTML5, CSS3, Typescript)
* Have knowledge/experience with Angular
* Have experienced/worked with the Japanese project 

### Ideally
* Experience with Flex will be a plus

### Responsibilities
* Work on the full life cycle of software development projects
* Recommend appropriate technologies to implement new features
* The responsibility includes: design, coding, troubleshooting and work with project team as well as customers on features/bug fixes
* Responsible for implementing visual and interactive elements that users engage with through their web browser when using a web application.

### Why it would be awesome to work with us
* Basic salary + quarterly bonus, Tet holiday + 13th month salary
* Annual salary increased 1 time/per year
* Working in a young, friendly and dynamic environment
* Fully pay social insurance after 2 months of probation
* Annual activities with company (Company trips, parties, .. )

### Contact
Homepage: https://vn.nec.com/
Title: [Nec Vietnam - Front-End Developer - Your Name]
Contact:
Email: recruiter.nghiahuynh@gmail.com
Skype: recruiter.nghiahuynh@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
