### ISSUE TITLE
Christina's - Product Designer (UI/UX) - Saigon - FT

### ISSUE THREAD

**Issue by ChristinasVN** [awesome-jobs/vietnam#1603]
## Location
* Saigon, Vietnam
* District 1 

## About us
Team Christina’s consists of world travellers, Vietnamese returnees, and local graduates, citizens, and entrepreneurs from all different backgrounds. We believe that in order to best understand and anticipate the needs of our guests, our team needs to reflect the diversity of our guests as much as possible.

## What exactly is a Product Designer (UI/UX)?
You’ll be a part of Christina’s technology team which consists of both engineers and designers working closely together to design and build high-impact products that help drive the growth of the company. As a team, we place a strong emphasis on building functional and delightful user experience at the core of our technology to make it not only user-friendly and efficient for the people who use the products, it aims to enhance people’s lives for better work-life balance as well.

Check-out our hosts technology at https://www.christinas.vn/host-tech/

## The must-haves
* Personal principles and values that align with the company core values and mission.
* To be able to learn independently under minimal guidance and supervision.
* To communicate, present ideas, and handle feedbacks constructively.
* To learn and adapt quickly to new design technologies and softwares such as Sketch and Figma.
* A strong portfolio of relevant design projects or experiences (including published articles or case studies) with a focus on problem-solving.
* Mid to high fluency in English, preferably good at copy writing and reading comprehension.

## What can you expect to be doing…
* You are the OWNER of your works and processes.
* You do works that you fully understand and believe in. You dig deep into problems until there is absolute clarity and zero doubt.
* You are the end-to-end problem solver of your projects which will require understanding of multiple perspectives, including business, operation and design.
* You can independently explore, observe, and pursue opportunities to improve the company and our mission through design.
* You are able to collaborate and work together with members across all teams in the company to deliver kick-ass design solutions.
* Participate and contribute in shaping our company core values to keep our workplace awesome for yourself and others.

### Why would you want to join us?
* Diverse range of products ranging from websites to native mobile apps to horn your skills in different areas.
* Peer-to-peer mentorship and on-the-job training.
* Awesome startup culture where reasons matter more than titles.
* Opportunities to meet and interact with travelers from around the world.
* A diverse, inclusive, and supportive working environment.
* Supportive leadership that cares about your growth.
* Opportunities to travel around our homes across the country and make new friends.
* A competitive total compensation package with attractive base salary and performance incentives.
* Additional private health insurance, paid days-off to travel, and flexible working schedule.

### How to join
If you think you have what it takes, then simply send us your CV and cover letter to get started: talent@christinas.vn or apply directly through our website: https://www.christinas.vn/joinus/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
