### ISSUE TITLE
Christina's - Data Scientist - Sai Gon, Vietnam - FT

### ISSUE THREAD

**Issue by ChristinasVN** [awesome-jobs/vietnam#1604]
## Location
* Saigon, Vietnam
* District 1 

## About us
Team Christina’s consists of world travellers, Vietnamese returnees, and local graduates, citizens, and entrepreneurs from all different backgrounds. We believe that in order to best understand and anticipate the needs of our guests, our team needs to reflect the diversity of our guests as much as possible.

## About Data Scientist team
You will help shape the future of what we built at Christinas, you will get to work with new ideas, novel problems, you will get to design things from scratch, and see your insights turned into reality, then prove the existence of these realities with proper scientific tests.

The suitable candidate will have a background in a quantitative or technical field, will have experience working with strong data sets, and will have some experience in data-driven decision making. You are focused on results, a self-starter, and have demonstrated success in using analytics to drive the understanding, growth, and success of a product.

Check-out our hosts technology at https://www.christinas.vn/host-tech/

## The must-haves
* Encompass a high level of integrity.
* Exemplify a strong work ethic.
* Be fluent in English (writing, reading, speaking).
* 2+ years of experience doing quantitative analysis.
* Experience with statistical software (e.g., R, Python, Julia, MATLAB) and database languages (e.g., SQL).
* Ability to communicate the results of analyses with the teams to influence the strategy of the product.
* Understanding of statistics (e.g., hypothesis testing, regressions).
* Experience manipulating data sets. Experience with building data sets would be a plus.
* Strong problem solving skills.
* A drive to learn and master new technologies and techniques.

## What can you expect to be doing
* Work closely with various key business stakeholders and team to understand our operation and to ensure that data science projects fulfill the evolving needs of the team.
* Design data product that align with the team’s needs.
* Create data architectures, data models and algorithms.
* Built custom data sets.
* Propose and determine key product metrics, monitor them and understand root causes of changes in metrics.
* Design and evaluate experiments.
* Communicate state of business, experiment results in a precise and easy to understand to the teams.
* Spread best practices to the teams.

## Why would you want to join us?
* Opportunity to build challenging data product.
* Freedom of thinking. You are free to explore and to form new hypothesis.
* Ethical data product.
* Learning materials from world's top educators.
* Awesome startup culture where reasons matter more than titles.
* A diverse, inclusive, and supportive working environment.
* Supportive leadership that cares about your growth.
* Opportunities to travel around our homes across the country and make new friends.
* A competitive total compensation package with attractive base salary and performance incentives.
* Additional private health insurance, paid days-off to travel, and flexible working schedule.

## How to join
If you think you have what it takes, then simply send us your CV and cover letter to get started: talent@christinas.vn or apply directly through our website: https://www.christinas.vn/joinus/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
