### ISSUE TITLE
Fetch - Tester (Junior) - HCM - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1605]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9.

* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * From $400 - $800.

## Job Description

The project is about an online marketplace for Advertisement spaces.

What is so cool about us is that we want to reinvent the way people see and use spaces, turning all the Available Idle spaces into Rentable advertising space! We hope that through this, everyone can have better use of idle space and access to affordable marketing! 

We have a platform for anyone to list available “AIR-spaces” and for anyone to book them for advertisement placements. What is an AIR-space? It is any public facing space. Cafes interior, tables, shop windows, car fleets, toilets.. You name it!

The project is creating a marketplace that allows businesses (AIR-space Owners) to maximize underutilises spaces they have, to help businesses (Advertisers) with the opportunity to reach out to their customers at a more affordable cost.

We hope to empower businesses of all sizes to stay competitive in the market place by fostering mutual support amongst non competing businesses through win-win opportunities; everyone gets more value with the available existing resources.

## Responsibilities: 
  * Execute manual and write automated tests and identify actionable bugs quickly.
  * Manage QA coverage of multiple environment.
  * Planning/organizing necessary test passes, staying on top of all important issues, help triaging bugs and driving issues to resolutions and keeping everyone aware of QA status.
  * Work with different team (Engineering/PM/Operation) to collect necessary information to assure the QA coverage, and also provide feedback on quality issues.
  * Work with team to set their priorities and remove their roadblocks to make sure sufficient coverage is done for the release.
  * Create and support test dashboards/reports.

## Skills Requirements
  * BA/BS degree in Engineering, Computer Science, IT, or related field.
  * At least 2 years Quality Assurance experience in testing web.
  * Ability to construct test cases and get them prioritized based on changes.
  * Experience in stress test.
  * Knowledge of test and tool development methodology.
  * Experience in coding.
  * Communication skills, including development of presentations.

## Why it would be awesome to work with us
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
### What we offer:
  * Be part of an incredible team of people from all over the world.
  * Work in a rapidly expanding team and grow your responsibilities in time.
  * Immense learning opportunity in Blockchain and Cryptocurrencies.
  * Competitive salary, motivation package, and all kinds of small perks to keep you happy with us.
  * An environment that encourages self-development, learning, and growth.
  * “Work hard, play hard” culture - regular team events from skiing weekends and trekking to happy-hours and board game nights.

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
