### ISSUE TITLE
Fetch - Full-stack PHP Laravel Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1606]
## Location

* Ho Chi Minh: 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District.
* Ha Noi: 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District.

* Full-time. (Monday to Friday from 9:00 to 18:00).

## Salary Expectation

  * From $1000 - $2000.

## Job Description

The project is about the platform that offers derivative products and services across various markets globally. We are looking to expand our product and service offerings with the introduction of fin tech revolutionary features that include the famed loyalty program and the implementation of our proprietary Social Trading software.

You will work as a Senior Web Application Developer and report directly to the Chief Technology Officer.

### Job overview
  * You will be responsible for developing and maintaining client-facing and back-end operation web applications, including testing and documentation.
  * Able to create technical design and data modelling while working alongside designer to implement UI and UX designs, among other duties.
  * Creating and consuming API to link up back-end operation applications with trading platform.
  * Maintaining and support trading platform servers.
  * Full software development life cycle for Social trading platform in the pipeline.
  * Chance and opportunity to learn and develop auto trading system or indicators.
  * Chance and opportunity to learn and develop Android app to complement client-facing applications.

## Responsibilities
  * Ideally you are equally strong in front-end programming languages: HTML, JavaScript, CSS/ Sass, styling and Back-end programming Languages: PHP, SQL.
  * Developing and maintaining client-facing and back-end operation web applications.
  * Testing and code review to ensure applications free of bugs.
  * Implementing UI and UX designs created by our designer.
  * Ensuring cross-platform optimization for mobile phones.
  * Ensuring responsiveness and security of applications.
  * Seeing through projects from conception to finished product.
  * Designing, developing and consuming RESTful API.
  * Staying abreast of developments in web applications and programming languages.
  * Leading of junior developer and participating in code reviews.

## Skills Requirements
  * At least 2 years of experience on PHP 7, Laravel Framework, PostgreSQL and Bootstrap front-end framework.
  * Experience in MySQL and data modelling.
  * Experience in VueJS JavaScript Framework.
  * Expert with Git and knowledgeable with Git workflow.
  * Ability to convert PSD design into HTML5 and CSS3/Sass.
  * Demonstrated analytical, problem-solving, interpersonal and communication skills.
  * Experience with C++, C# or Android app development will be a bonus.

## Why it would be awesome to work with us
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
### What we offer:
  * Be part of an incredible team of people from all over the world.
  * Work in a rapidly expanding team and grow your responsibilities in time.
  * Immense learning opportunity in Blockchain and Cryptocurrencies.
  * Competitive salary, motivation package, and all kinds of small perks to keep you happy with us.
  * An environment that encourages self-development, learning, and growth.
  * “Work hard, play hard” culture - regular team events from skiing weekends and trekking to happy-hours and board game nights.

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
