### ISSUE TITLE
Lecle Vietnam - Senior Python Developer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1607]
## Location

* D1, HCMC
## Salary Expectation

* Negotiation

## Requirements
* Solid experience in Python programming language
* Familiarity with some ORM libraries
* Good understanding of server-side templating languages such as Jinja 2, Mako, etc...
* Basic understanding of front-end technologies, such as JavaScript, HTML5, and CSS3
* Knowledge of user authentication and authorization between multiple systems, servers, and environments
* Able to create database schemas that represent and support business processes
* Experience with Python frameworks (e.g. Django, Flask, Odoo...) is a plus

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + Year-end bonus
* Macbook Pro provided
* 15 days of annual leave
* Onsite opportunities in Korea every 3 years
* Working with a passionate team and professional Korean experts
* Company trip at least once a year & company dinner once or twice a month
* Free coffee, drinks and snack
JD for detail: http://smrtr.io/395sH

### Contact
* Phone: 028-5416-5548
* Send your CV to email: career@lecle.co.kr
### Know more about us
* Facebook: www.facebook.com/LecleVietnam
* Homepage: https://www.lecle.co.kr/
* Medium page: https://medium.com/leclevietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
