### ISSUE TITLE
TechBase Vietnam - NodeJS Developer - HCM - FT

### ISSUE THREAD

**Issue by NghiaHuynhh** [awesome-jobs/vietnam#1608]
## Location
* 10th floor, Tower 2 Saigon Centre Building, 67 Le Loi Street, District 1, HCMC

## Salary Expectation
* Salary: $600 – $1,500

## Requirements
* 2+ years web application development experience
* Having experience development with NodeJS
* Strong experience with OOP design
* Good at using Linux, MySQL and Git

### Ideally
* Experience and good at PHP, Java, HTML, CSS, JavaScript libraries are plus
* Reading and writing in Japanese is big plus

### Why it would be awesome to work with us
* 13th month & Performance bonus up to 4-months salary
* Chance to become Yahoo! JAPAN Corporation staff
* New year holiday: 5-days leave (our company only: from 30th Dec to 3rd Jan) and Tet holiday based on the annual announcement of the Government
* Company trip, annual health check, year end party: once per year
* Voluntary health insurance (Bao Viet care 24/24 Insurance)
* Premium Friday, meaning you can leave office early at 4 P.M on the last Friday of each month
* Monthly lunch and team building allowance (VND 700.000)
* Birthday gift (VND 500.000, and 1 leave day in birthday month)
* Free Japanese class
* Commend MVP persons, MVT team every quarter
* Other interesting activities: weekly fruit party, team building, ping-pong, PS4
* Free 24/7 bike park in Saigon Centre

### Contact
Homepage: https://www.techbasevn.com/
Email: nghia.huynh@hri.com.vn
Skype: live:recruiter.nghiahuynh
Title: [Techbase - NodeJS Developer - Your Name]

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
