### ISSUE TITLE
The Loop - PHP Developer - HCMC - FT

### ISSUE THREAD

**Issue by truongvan** [awesome-jobs/vietnam#1612]
## Location
* Q. Phu Nhuan
* Saigon, Vietnam

## Salary Expectation
* up to 20M VNĐ per month

## Requirements
* Experience with Laravel framework.
* Have development experiences of the Web application by PHP at least 02 years
* Ability to work independently or with team.

## Responsibilities
* Designing and developing APIs and back-end website applications.
* Design, develop, and maintain efficient, reusable, and reliable code using best practices.
* Identify bottlenecks and bugs, and devise solutions to troubleshoot and address issues.
* Collaborate with front-end developers for integration
* Optimize website for maximum speed, scalability, and security.
& Ensure the technical feasibility of UI/UX designs, Improve the User Experience of the website regularly.

### Contact
Mr Đăng
* Skype: haidangbayern
* Phone: 0933 832 017

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
