### ISSUE TITLE
TiKi - SDE (Search Team) - FT

### ISSUE THREAD

**Issue by tramtran279** [awesome-jobs/vietnam#1614]
## Location

* Ho Chi Minh, Vietnam

## Salary Expectation

* Up to $2000/month

## Requirements
* Proficiency with Java.
* Knowledge of basic algorithms and data structures
* High load, low latency is the 1st requirement to build such system as search. Experienced with asynchronous programming and multi-threading is a plus.
* Experience with cloud services is a plus
### Must Have
* C++ and/or Java

## Responsibilities:
* Drive and implement technical solution to a variety of features that serve high throughput and also high availability.
* Build, test and ship back-end APIs support search and recommendation features.
* Design, implement and maintain streaming flow of products, categories, brands, even customer interactions,… from multiple data sources with high accuracy.
* Understanding business objectives, working closely with Data scientist to analyze, develop, ship and optimize machine learning models used in search ranking and recommendation.

## Who would be your companions:
* Your team: product manager, front-end, UI/UX designers, quality control engineers.
* Other: Chapter back-end, group of all back-end developers at Tiki, gathered and played as a backbone to share best practices, solutions for difficult problems, oriented technical vision across teams,...

## 5 reasons why you should join us:
* We are constantly iterating! There is no such best version for anything, no fastest API, no best machine learning models. We build, test, ship, and optimize, and test. Just a stream of improvements and tests.
* We have data-driven mindset, every point of changes must be tested to gain insights into its impacts on key metrics. It's a long process, but over time, we gradually learn and become confident in our approach.
* We have "enough" valuable data to analyze and gain insights into customers, which helps us adjust our features to bring the best experience to customers.
* We love "best practices". Serving important features with high throughput always give us a hitch to research and apply best practices. Any experiment or optimization is always welcomed.
* We are both independent and open. We own our products. Technical problems would be discussed internal, but for difficult one, we could request other's help.

### Contact
Homepage: tuyendung.tiki.vn
Email: ha.nguyen5@tiki.vn

**Comment by sluongng** [comment]
well this is a bit low effort post dont you think?

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
