### ISSUE TITLE
VAREAL K.K - Fresher Ruby on Rails Developer - Hanoi - FT

### ISSUE THREAD

**Issue by TuanNguyennnn** [awesome-jobs/vietnam#1617]
## Location
* 107 Nguyen Phong Sac Street, Cau Giay District, Hanoi.

## Salary Expectation

* Up to $1,500

## Requirements
* Fresher with Ruby on Rails
* Have knowledge with Front-End (HTML,CSS,Javascript)

### Ideally
* Basic English/Japanese

### Responsibilities
* Participate in development projects with Japanese customers
* Working with BSE, PM, cooperating with other members
* Develop and maintain back-end services on Ruby on Rails
* Develop solutions, write software according to company requirements

### Why it would be awesome to work with us
* Salary: Up to 1,500 USD (depending on experience)
* Consider salary increase 2 times / year.
* 13th Month Salary Bonus and according to the project
* Health insurance, social insurance, unemployment insurance, under the insurance law
* Lunch/Travel/Parking allowances and English allowance 
* Participate in Japanese, English, professional advanced classes 
* Annual travel, team-building and opportunity to train or work in Japan 

### Contact
Homepage: https://www.vareal.co.jp
Contact: at.nguyen.0104@gmail.com
Title: VAREAL K.K - Ruby on Rails Dev - Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
