### ISSUE TITLE
FETCH - NodeJS Developer - HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1621]
## Location

* 3rd Floor, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 8:30 to 17:30).

## Salary Expectation

  * Up to $2000.

## Job Description
Our project is about a secured Staking-as-a-Service provider for high quality, proof-of-stake based protocols. We are deeply rooted in the blockchain and cryptocurrency space and are currently building a Staking-as-a-service that is deeply involved in the staking blockchains ecosystem. We operate performant validation nodes with a multi-region, multi-tiered node architecture – providing a robust, high availability and secured validation setup for all stakeholders in the staking ecosystem.

We foresee huge potential in this industry and envision becoming pioneering leaders in the space. We have considerable traction and revenue with close to 40M LOOM tokens staked (~2,800,000 USD worth of tokens) staked with us for our first project with a pipeline of 10 other projects to come and looking to close a funding round shortly.

The longer term vision is to leverage the existing foothold we have in this nascent staking industry to build API proxies that allows for Non-Crypto users to access our nodes and deployment tools to build decentralized applications.

This convenient one-stop-shop platform as a service would allow for easy deployment across multiple public blockchain platforms and scalable middleware solutions. Let think of us as a Heroku, Serverless for Blockchain Applications and Web 3.0.

## RESPONSIBILITIES: 
  * Develop business logic for the blockchain explorer, light client and data collector, adhering to risk and compliance requirements.
  * Designing optimised and highly available microservices.
  * Develop rate limit logic across all public endpoints.
  * Develop data collection backend on all open services for monitoring and analysis.
  * Ensure that all public endpoints and services are hardened with industry best practices for web security.

#### You may need to be responsible for: 
  * Build out proprietary multi-cloud, multi- VM automation system.
  * Automate key infrastructure tasks.
  * Patching / Upgrading / Troubleshooting of applications.
  * Configure and support containers and container orchestration tools such as Docker, Nomad.
  * Familiar with alerting, monitoring, visualization frameworks such as InfluxDB, Grafana, Telegraf, Prometheus.

## Skills Requirements
  * 1+ years working as developer (backend or full-stack), working with Node.js.
  * Familiar with Node.js ecosystem, including tools such as NPM, Yarn, Webpack and Grunt.
  * Familiar with Git or similar SCM system.
  * Strong understanding of JWT (JSON Web Token), OAuth2 (and OpenID Connect) authentication protocol.
  * Degree in Computer Science, Information Systems, or other related engineering fields.
  * Ability to take lead and ownership on design, implement, fix bugs and deliver new features.
  * Ability to quickly learn and adapt to new technologies and workflows.
  * Resourcefulness and commitment to do what is needed to get the job done.
  * Experience in design, architect and lead implementing software solutions for corporations is a big plus.
#### Advantageous to have (most likely secure role with these experiences):
  * Proven experience in working with Centos / Fedora / Ubuntu distributions in a secure environment.
  * Experience working with Node.js for systems automation.
  * Experience in automation for common sysadmin tasks via software.
  * Knowledge of monitoring tools, ELK / TICK stack.
  * Familiar with alerting, monitoring, visualization frameworks such as InfluxDB, Grafana, Telegraf, Prometheus.
  * Strong understanding of web security best practices, including OWASP.
  * Experience in design, architect and lead implementing software solutions for corporations.

## Why it would be awesome to work with us
Being a Software developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
