### ISSUE TITLE
FETCH - Android Developer - HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1622]
## Location

* 3rd Floor, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 8:30 to 17:30).

## Salary Expectation

  * From $800 to $1500.

## Job Description
Our project is about crypto currency exchange app that providing fiat to crypto and crypto to crypto exchange. They aim to be the first exchange to let you trade Blockchain ideas, knowledge and values.

## Skills Requirements
  * 2+ years of native Android app development experience.
  * A portfolio of multiple apps, preferably transaction-based business critical apps for reputable companies. 
  * Proficient in Java with experience in memory management and caching mechanisms specific to mobile devices and embedded systems.
  * Experience and understanding of large and complex code bases and architectures.
  * A degree in computer science, software engineering, information technology or related fields.
  * Deep understanding of Android Studio, Java, Android NDK, etc.
  * Experience in API design, SDK architecture, and mobile software lifecycle development practices.
  * Strong UX/UI design exposure and experience in making apps work intuitively and with pixel perfect interfaces.
  * Strong CS fundamentals (with competencies in algorithms and data structures).
  * Highly accountable and takes ownership, with collaborative attitude, and a lifelong learner.

## Why it would be awesome to work with us
Being a Software developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
