### ISSUE TITLE
FETCH - PHP Laravel Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by VyVy07** [awesome-jobs/vietnam#1623]
## Location

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* 3rd Floor, Dai Phat Building – 82 Lane, Duy Tan Street, Ward Dich Vong Hau, Cau Giay District, HNC.
* Full-time. (Monday to Friday from 8:30 to 17:30).

## Salary Expectation

  * From $1000 to $1700.

## Job Description
The project is about building a platform for providing Digital Marketing service that offers digital solutions specializing in Search Engine Optimization (SEO) and Search Engine Marketing (SEM) to ensure that unique business goals are met.

## RESPONSIBILITIES: 
  * Develop & maintain web application using PHP framework (Laravel).
  * Conduct user-acceptance testing to ensure the program can be use easily and accurately.
  * Explore new technologies and experiment with new software.
  * Continue the development of OAP (OOm Adwords Platform) using following technologies:
    * PHP 7 (Laravel 5.5)
    * Angular 7 (optional)
    * Angular Material (optional)
    * Maria DB 10
    * Google Ads API
    * Google Ads Scripts

#### Must have:
  * At least 2 years working experience with PHP Laravel is required.
  * At least 2 years working experience with Maria DB or MySQL is required.
  * At least 1 year Experience in Adwords API and Google Ads Scripts is required.
  * Experience in interacting with APIs on the advertising of third parties such as: Amazon, Google, Microsoft.
  * Knowledge in REST api is required.
  * Familiarity on OOP.
  * Experience in GIT and Agile Development is required.
#### Optional but is a plus:
  * At least 1 year Experience in Angular Material and Angular 7 (or 5, 6) is a required.
  * Extensive knowledge and broad experience in PHP, MySQL or MariaDB, JSON, Ajax, Jquery, HTML & CSS.
  * Knowledge in Cron Job (PHP) or Scheduler (Laravel) is a plus.
  * Knowledge in Search Engine Marketing (SEM) is a plus.

### Soft skills:
  * Ability to work independently and in a team environment.
  * Strong interpersonal and organizational skills.
  * Preferably Junior Executives specializing in IT/Computer - Software or equivalent.
  * Able to communicate in English.

## Why it would be awesome to work with us
 Being a Software developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
  * Attractive salary and annual salary review.
  * Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
  * Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
  * Extensive on job training, you will always have chance to work with new emerging technologies.
  * Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
  * 12-day annual leave per year.
  * 13th month salary.
  * Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact

 * Email: vyha@fetch.tech.
 * Skype: angelsoi0701.
 * Phone: 0787 421 567.
 * Fanpage: https://www.facebook.com/fetchvietnam/
 * Website: https://fetch.tech/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
