### ISSUE TITLE
Junior Implementation Engineer

### ISSUE THREAD

**Issue by christopherg36** [awesome-jobs/vietnam#1627]
## Location

* Ho Chi Ming, Vietnam

## Salary Expectation

* USD 800 - 1000

## Requirements
* Are able to understand data structure and optimize technical performance
* 0-2 Years’ experience as a programmer/developer
* Have experience in working in an Agile environment
* Are able to multitask effectively and adjust quickly to different situations
* Are willing to learn and adapt to new and different technologies
* Have impeccable written and verbal communication skills, both in local language and English
* Are obsessed with detail, and have an analytical mindset
* Strong team player, but still a self-starter
* Willing to work with customers for product installation, troubleshooting and monitoring.

## Skills

* Have technical working knowledge of 
- SQL
- HTML
- Javascript
* Have a good understanding of RESTful API
* Knowledge in PHP/NodeJS/React is an added plus

### Must Have

Basic technical skills and the willing to learn + grow

### Responsibilities

* Preparing data specification and integration for customers using our solutions
* Interfacing with customers on a regular basis, working with their marketing and development team to ensure successful on-boarding and long-term success
* Work collaboratively with cross functions departments to constantly provide solutions and deliver performance for our customers
* Taking ownership of customer issues reported and seeing problems through to resolution
* Following standard procedures for proper escalation of unresolved issues to the appropriate internal teams
* Proactively finding opportunities to improve customer performance 

### You’ll be responsible for

* Preparing data specification and integration for customers using our solutions
* Interfacing with customers on a regular basis, working with their marketing and development team to ensure successful on-boarding and long-term success
* Work collaboratively with cross functions departments to constantly provide solutions and deliver performance for our customers
* Taking ownership of customer issues reported and seeing problems through to resolution
* Following standard procedures for proper escalation of unresolved issues to the appropriate internal teams
* Proactively finding opportunities to improve customer performance 

### You can bring

* Good expertise in coding and web development
* Great collaboration and communication skills

### Why it would be awesome to work with us

* All the perks that comes along with working in a startup and we pay competitively
* Be part of a fast growing company that nurtures entrepreneurial nature, startup culture and wants to unlock the best version of you
* Work with a diverse team of smart people who are also fun after work
* Collaborate with a multi-national team across APAC
* Opportunity to travel for better exposure across our operating markets

### Interesting engineering projects

* Please share a link

### Contact
Email: christopher.gerard@ematicsolutions.com
Site: ematicsolutions.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
