### ISSUE TITLE
Fram^ - Senior/Principle Ruby Engineer - HCMC - FT

### ISSUE THREAD

**Issue by framcompany** [awesome-jobs/vietnam#163]
**About us:**
Fram - the Swedish software Company helps Scandinavian and Northern European companies leverage the talent and power of Vietnamese rock star developers and other online industry talent. Fram is a very different company. First of all, our culture is different – we believe that to write world class code you need to work in an environment that energizes you and with colleagues that inspire and challenge you. Hence, we sit in a special designed, Scandinavian office on Nguyen Cong Tru in central Ho Chi Minh City. We only work with Scandinavia’s top online employers and we only hire Vietnam’s top 2% developers and internet industry talent. 

**Location**
- 22nd Floor, TNR Tower, 180-192 Nguyen Cong Tru, Dist.1, Vietnam

**Salary Expectation**

**Up to USD 2,500**

Fram is now looking for Senior / Principle Ruby engineer to play a key role in developing the product of Sweden’s fastest growing online HR platform.

**The project**

Our client is changing the way companies work with employer branding and recruiting online. Want to help us make HR heroes? The team you will be working with is a young and fast moving tech startup with smart peoples that are passionate about their work.

**Role descriptions**

Being a start-up, we still have a lot of ground to cover and big questions to answer. Given that, we’re looking for someone that thrives when faced with complex problems, and likes to think outside the box.

Your project is a Ruby on Rails app and other key components in our current setup is postgresql, elastic search, redis. Previous relevant experience is a great, but we value the ability to learn new things more than past experience.

**Requirements**
- +3 years of experience in designing, developing, deploying and maintaining Ruby on Rails systems
- Solid understanding of database system characteristics
- Able to write well-structured, modular and maintainable code
- Strong English, in speech and in writing
- Acquired intuition and instinct in solving problems after analyzing multiple solutions
- Eager to learn new things, both technical and business-related
- Passionate about building products to solve real problems, not merely "coding"
- Knowledge in Javascript, CSS, LESS/ SASS

**Nice to have**
- An eye for good user experience
- Deep understanding of frontend technologies
- Familiarity with Unix-based systems
- Experience with an alternative web framework

**Benefits:**
More on Fram – what is it like to work in Fram?

We are passionate individuals driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals with a desire to build something new and actively support our young company in its growth to greatness.

You will love working here!
- Excellent salary package (up to $2,400 gross for talented candidates), with both 13th month salary and additional performance related annual bonus on top
- 5-day working week (Monday-Friday), working hours to some extent flexible
- Professional and open working environment, with the culture and office of a Scandinavian online company, on Hai Ba Trung in central Ho Chi Minh City
- Annual leave and insurance policies in compliance with Vietnam’s Labor Law and company's regulations
- Opportunities to improve English skills within an international team – English is official language in fram^ office. Also regular English lessons two times per week by native English teachers in the office
- Opportunities to gain hands-on experience in cutting-edge technologies
- Opportunities to become one of key member of fram^ as we build this fast growing company together!

**Contact**

For application or asking for further information, kindly contact back to:
- Ms. Lan Anh, Talent Manager, HR Department
- Email: ttla@framco.se
- Skype: mary.trananh
- Website: http://framco.se/

**Comment by joneslee85** [comment]
Thanks for the job post, can you pleas fix up the format of headers, they are not consistent to each other. And the "Your Skill and Experience" line seems to be a header but not bold not concatenate me with the next line.

Lastly we prefer that Contact is at the very bottom as it has been proven more effective UX-wise for flow reading

**Comment by framcompany** [comment]
Dear Trung,

 

Thanks for your noticed.

 

I’ll fix this immediately.

 

Kind Regards,

Tran Thi Lan Anh
Talent Manager, HR Department, fram^ Ltd Vietnam | www.framco.se <http://www.framco.se/> 

Email: ttla@framco.se <mailto:ttla@framco.se>  | Skype: mary.trananh

Phone: (VN) +84-905 250 286

**Comment by hnq90** [comment]
@framcompany Your header is missing `[Job Type]`. The correct format should be `[Company Name] - [Job Title] - [Location] - [Job Type]`

>in which [Job Type] could be:
FT (for Full Time)
PT (for Part Time)
C (for Contract)

*Example:* `Facebook - Chief Software Architect - Remote/Saigon - FT`

**Comment by framcompany** [comment]
Dear Huy,

 

Thanks so much for your kind and clearly guide us how to post our position.

 

This is the first time I joined group, then if I need to fix any term, kindly let me know.

 

Thank you,

 

Kind Regards,

Tran Thi Lan Anh
Talent Manager, HR Department, fram^ Ltd Vietnam | www.framco.se <http://www.framco.se/> 

Email: ttla@framco.se <mailto:ttla@framco.se>  | Skype: mary.trananh

Phone: (VN) +84-905 250 286

**Comment by lessless** [comment]
Hello fellow Rubyists,
I want to weight out that Fram^ is a really good place to be with a very friendly team and good working conditions. 
The operations are based on Swedish standards which mean flat structure, social care and decent flexibility in working hours. 
Please, be very welcome to find out more :)
