### ISSUE TITLE
CSSOFT - Python Developer (Django) - HN - FT

### ISSUE THREAD

**Issue by phuckhang123** [awesome-jobs/vietnam#1630]
## Location

* Ha Noi
* Fulltime

## Salary Expectation

* Negotiable

## Requirements
* Experience 3+ year in Python.
* Experience 2+ year in Django  framework.
* Use English in writing

### Responsibilities

* Analyzing requirements, project development planning.
* Researching, learn new technologies

### Why it would be awesome to work with us
* Offer + bonus, 13th salary; Performance bonus; Tet bonus, Birthday,....
* Have full of insurance such as Health Insurance, social insurance, ...
* Have opportunity to work in Japan, Da Nang.
* Professional working environment, friendly, dynamic, creative, encouraging personal development.
* Working hour: Monday to Friday (8h30 - 17h30)

### Contact
Send CV via mail: phuckhang.ttran@gmail.com
Title: [CSSOFT - PYTHON - YOUR NAME]

**Comment by namqdam** [comment]
v    o
