### ISSUE TITLE
AVERSAFE - LEAD/SR. BACKEND ENGINEER (PHP) - HCMC - FT

### ISSUE THREAD

**Issue by dtrang0102** [awesome-jobs/vietnam#1631]
## Location

* District 11, HCMC, Vietnam
* Full time

## Salary Expectation

* up to $1800/month 

## Requirements
* Fullstack
* PHP, Go, Javascript
* MVC frameworks
* MySQL, Postgres, Redis, CockroachDB
* 4+ years Software Engineering experience

### Must Have

* 4+ years PHP (or similar dynamic language) experience
* 2+ years experience as a key member in a development team
* Excellent English communication skills (i.e. listening, speaking, and writing)

### Ideally

* Experience with excellent software engineering skills, actively propose solutions to problems, and work well with teams to define the best way to roll out and manage growing services on our technology stack.

### Responsibilities

* Develop code to meet the continued business needs for new application features and refinement of existing functionality;
* Identifying and rectifying coding issues or bugs in new or existing tools;
* Contribute to architecture direction and discussions and assist in the progressive evolution of our existing code base;
* Analyze high-level requirements and write detailed functional code to meet the requirements;
* Writing maintainable code with extensive test coverage in a professional software engineering environment (with source control, dev/stage/prod release cycle, continuous deployment);
* Assessing the impact of production system changes to the existing features;
* Collaborate with our project managers, designers and frontend team.

### You can bring

* A passion at write code, ship products.
* A great skill to solve real problems.
* Ability to get things done

### Why it would be awesome to work with us

Aversafe is a technology startup dedicated to reducing fraud in the hiring process. We connect
educational institutions, job seekers, and employers on our network, helping each party improve
trust, lower costs and reduce liability. Here’s how it works. We help universities, language centers
and professional development organizations issue verifiable digital certificates to their graduates. Graduates and job seekers use the Aversafe app to claim their certificates and, in conjunction with employers, build out their trusted profiles by exchanging and verifying one another’s work histories and professional information. Employers can request access to users’ pre-verified profiles, reducing HR overheads and accelerating time-to-hire.

Aversafe is a company taking over the world, working with Universities, Governments, Individuals
and large-scale employers. If you’re passionate about changing the world and reducing fraud you should come and join us.

### Contact
Homepage: www.aversafe.com
Trang (Ms): trang_at_aversafe_dot_com (0909667062)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
