### ISSUE TITLE
AVERSAFE - REACT NATIVE MOBILE ENGINEER - HCMC - FT

### ISSUE THREAD

**Issue by dtrang0102** [awesome-jobs/vietnam#1632]
## Location

* District 11, HCMC, Vietnam
* Full time

## Salary Expectation

* Up to $1200

## Requirements

* React Native
* Objective-C
* Swift
* Java
* 2+ years Software Engineering experience

### Must Have

* End-to-end mobile development experience, including shipping to the Play and/or iTunes store.
* 2+ years designing & implementing mobile applications in React Native, and/or native mobile development for iOS or Android in Objective-C, Swift, or Java.
* A design-oriented approach; empathy to the end-user experience and thoughtful about what we can do to make it better (you love to sweat the details!).
* Memory management and experience optimizing application performance is highly valued.
* Knowledge of test driven development is highly valued.
* Be passionate about design and UI and provide feedback on design and UX.
* Good English communication is a must.
* Ability to collaborate and work effectively with cross functional teams.
* Excellent communication, time management and organizational skills.
* The ability to determine when to deliver architectural masterpieces versus quick ship solutions, and capable of modulating your approach as-needed.

### Ideally

* Previous experience working on successful consumer apps, a passion for mobile UI/UX, an awesome portfolio, and/or a fan of sporting or other live events.

### Responsibilities

* Extend and enhance our React Native mobile apps for iOS and Android.
* Own significant portions of application development from concept through deployment and support.
* Participate in code reviews and ensure exceptional code quality.
* Collaborate with design and product teams to develop a premium, fun mobile user experience.
* Ship software regularly within an agile environment.
* Follow emerging technologies and anticipate opportunities to expand existing applications or create new ones.
* We are passionate about user experience and design, and you will be laser focused on ensuring high quality delivery of an app that solves real customer needs.

### You’ll be responsible for

Development and design of our iOS and Android applications that are securing personal data and reducing credential fraud globally. We make it easy for job seekers to build trust in the hiring process while protecting their personal information and speeding up the hiring process. You will work with the wider team of engineers to continue our investment in the world’s most respected credential issuance and verification platform.

### You can bring

* Ability to get things done
* Ability to learn new things

### Why it would be awesome to work with us

Aversafe is a technology startup dedicated to reducing fraud in the hiring process. We connect
educational institutions, job seekers, and employers on our network, helping each party improve
trust, lower costs and reduce liability. Here’s how it works. We help universities, language centers
and professional development organizations issue verifiable digital certificates to their graduates. Graduates and job seekers use the Aversafe app to claim their certificates and, in conjunction with employers, build out their trusted profiles by exchanging and verifying one another’s work histories and professional information. Employers can request access to users’ pre-verified profiles, reducing HR overheads and accelerating time-to-hire.

Aversafe is a company taking over the world, working with Universities, Governments, Individuals
and large-scale employers. If you’re passionate about changing the world and reducing fraud you should come and join us.

### Contact
Homepage: www.aversafe.com
Trang (Ms): trang_at_aversafe_dot_com (0909667062)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
