### ISSUE TITLE
VINOVA - Ruby on Rails Developer - HCMC - FT

### ISSUE THREAD

**Issue by Sara-Trinh** [awesome-jobs/vietnam#1633]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000 - $3000/month

## Must Have
•	3+ years of experience in web application development for a senior position 
•	Experience with Ruby on Rails, along with other common libraries such as RSpec and Rescue
•	Good understanding of the syntax of Ruby and its nuances
•	Good understanding of server-side CSS preprocessors 
•	Have a strong background in IT (general knowledge about the algorithm, data structure, programming principle, database).
•	A strong web backend experience is preferred.
•	Solid understanding of object-oriented programming principle (OOP).
•	Experienced with web service protocols such as HTTP/ REST, SOAP.
•	Experienced with HTML 5/CSS 3/SASS/Jquery/Ajax is a plus.
•	Experienced in a deploying system on Heroku/Amazon EC2.
•	Proficient understanding of code versioning tools e.g. Git, Mercurial or SVN
•	Familiarity with development aiding tools 
•	Familiarity with continuous integration

### Nice to have
•	Self-improver with a Can-do mindset.
•	Clean and efficient code lover.
•	A commitment to quality and a thorough approach to work.
•	Good teamwork and reliability.
•	Able to read/write well in English

### Opportunities 

•       Direct coaching from top management
•       Chance to work overseas based on the request from clients
•       Chance to improve technical skills during working with clients on new technology.
•       Chance to become a leader of a dynamic and growing company.
•       Chance to improve English skills since the main communication is English during working hours.

### Benefits

* We have a fun, Silicon Valley style startup culture that values openness, fun, and awesomeness.

•       Attractive salary and annual salary review.
•       Provide MacBook Pro for work.
•       A fun, awesome work environment with multiple exciting bonus schemes (13th-month bonus, performance bonus, peer-to-peer bonus...)
•       Progressive and international working environment.
•       Exciting weekly/annually company activities.

### Contact
* Website: www.vinova.sg
* Facebook: https://www.facebook.com/vinova.sg
* Please send your CV to: hr.hcm@vinova.sg

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
