### ISSUE TITLE
Quoine - Backend Engineer - Blockchain, Virtual Machine - Saigon - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1634]
# Location

* Saigon, Vietnam

# Salary Range

* US $1000 - $4000

#### We are looking for rockstar Backend Engineers (all levels) to join our rapidly expanding Blockchain Tech team in our Saigon office. 

# Responsibility 
### As Blockchain Engineers at QUOINE:

* We build and maintain the crypto asset platform that controls all crypto funds in and out of the company. This is a highly available system that requires extreme attention to detail from engineers that have a good sense of quality and security. 
* We solve hard problems to build a new blockchain system and ensure its robustness, performance, and scalability. The blockchain plays a central role in the company’s commitment to innovation and contributes to the Blockchain ecosystem as a whole.

# Technology
#### An engineer responsible for building a VM on blockchain must also have:
* Knowledge of compiler and virtual machine. Ideally having worked with either a Stack-based or a Register-based VM.
* And/Or knowledge of Linux kernel system calls. Especially interfaces that handle memory management.

### Why it would be awesome to work with us
* Join a global leading Fintech company
* Bring cutting-edge technologies into play
* Enjoy exceptional benefits package (tech/non-tech training courses, gym sponsor, extra health insurance for you and your immediate family, etc.)
* Work in one of the most modern & innovative spaces in town

# Contact
* Homepage: https://careers.liquid.com/
* Linh: linh.truong@quoine.com 
* Mobile no.: 0938 019 369
* Skype: linh.truong.my

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
