### ISSUE TITLE
Cinnamon AI - PMO Lead - Hanoi/HCM - FT

### ISSUE THREAD

**Issue by giangnguyen2710** [awesome-jobs/vietnam#1636]
## Location

* 36 Hoang Cau, Dong Da, Ha Noi
* Ton Duc Thang, Ben Nghe, Quan 1, Ho Chi Minh

## Salary Expectation

* Up to $2500

## Requirements

● Define the PMO strategy and lead the design and implementation of a common project management methodology, standards and tools to drive and facilitate the successful delivery of projects.
● Manage the PMO team and provide performance feedback and goal-setting; provide support, advice and assistance to PM/BA and/or other departments across the organization managing their own projects.
● Manage interdependencies and coordination across projects to ensure that information relating to project deliverables, risks and issues are effectively communicated between stakeholders and that key performance indicators are monitored and evaluated.
● Track and ensure resource availability, allocation and optimization (in case of limited resources) for all on-progress projects.
● Facilitate and coordinate internal resources for the flawless execution of projects.
● Develop or update project plans for information technology projects including information such as project objectives, technologies, systems, information specifications, schedules and members.
● Monitor or track project milestones and deliverables.
● Schedule and facilitate meetings related to information technology projects.
● Prepare project status reports by collecting, analyzing, and summarizing information and trends.
● Measure project performance using appropriate systems, tools and techniques.
● Collect planned and actual costs and give a clear financial overview across clients/internal projects

## Skills

● Demonstrable experience at a senior level within a PMO function and handling multiple
technical projects at the same period of time.
● Strong in negotiation, complex problem solving, problem sensitivity, time management, management of personnel resources.
● Good at English communication skills (speaking, listening, reading) and Business-professional English (document writing).
● Solid understanding of project management processes and methodologies.
● A team player and leader, able to build and maintain relationships with strong decision-making abilities.
● Proactive, responsive and assertive attitude to achieve clear project goals and deliverables.
● Demonstrated ability to work within defined processes, with excellent eye for details
● Familiar to Jira/Redmine. Strong MS Project, Work, Outlook and Excel skills.

### Why it would be awesome to work with us

● Competitive allowance and benefits
● Full-time contracts will be offered based on your performance and potential to learn.
● An open working environment and full of opportunities for talents to grow.
● Offering training opportunities, education assistance, mentorship programs and
collaborative learning sessions.
● A collaborative environment that fosters communication via slack and an open-door
policy.

### Contact

Homepage: cinnamon.is
Email: talent@cinnamon.is or grace@cinnamon.is

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
