### ISSUE TITLE
[Remote] Looking for an experienced fullstack JS dev to join our Sports Tech startup

### ISSUE THREAD

**Issue by ptgamr** [awesome-jobs/vietnam#1637]
## Location
* Remote

## Salary Expectation

* 1-2k

## Skills
* Strong JavaScript
* React 
* React Native 
* TypeScript (would be nice if you already now it, as we're heavily using it)
* Passion for technology + sports

### You’ll be responsible for

* Developing and maintain a Video Analytics / Scouting portal / mobile app, used by hundreds of clubs and players around Europe and North America.
* Contribute your idea how to make the platform better our users

### Why it would be awesome to work with us
* Lean team, currently 2 devs, 1 QA, 1 designer with lots of interesting problem to solve
* You'll have the chance to work and make impact to the Sports industry. Hockey is the starting point, later can be football, baseball etc. CEO is a former professional hockey player & FIFA staff
* Interesting technology, we move fast and work with new / modern technology

### Contact
Anh Trinh (anh.trinhtrung@gmail.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
