### ISSUE TITLE
EdgeWorks Software - Senior Python (Django) Developer - Saigon - FT

### ISSUE THREAD

**Issue by rickytarrant** [awesome-jobs/vietnam#1638]
## Location

* Bcons Tower, Nguyen Van Thuong (D1) Street, Binh Thanh District, Saigon, Vietnam

## Salary Expectation

* Up to 1500$/month

## Requirements
* At least 3 years of experience with Python (Django)

### Must Have

* Python (v2.7, v3.0+)
* Django; Django JET, jQuery
* JavaScript, HTML5, CSS3
* SQL (PostgreSQL 9.x, 10+ preferred) & Non-SQL DataBases
* MVC pattern
* Linux OS (Ubuntu, CentOS)
* Excellent work capacity & efficiency
* Adaptable, fast-learner, friendly & trustworthy
* Decent English reading, writing and listening

### Ideally/Advantages:

* Experience with Flask; React JS; AngularJS (v1.2+); Ext JS (v3.4+); Vue.JS (2.6+); jQuery
* PostgreSQL 9.x, 10+; MySQL 5.x; MariaDB; MongoDB; Redis; NoSQL
* ElasticSearch; Restful API; GraphQL; MQTT
* Git; Gitlab CI; GitFlow; Semaphore CI; Bitbucket; Docker; Jenkins; Supervisor
* System architecture, APIs (Google Maps, Mapbox, Fb,…), AWS EC2, S3, Cloudfront
* Familiar with agile development methodologies (Scrum).
* Excellent analytical and problem-solving abilities with attention to detail.
* Soft: Good communication / English, creative, innovative

### Responsibilities

* Overall, developing, maintaining and improving new or existing assigned solutions / products / features (business software, web-sites / shops / apps).
* Translating functional diagrams into technical specifications / documents.
* Providing high quality code for new critical products / features, by respecting guidelines / standards and executing unit tests.
* In addition, for seniors / engineers: Analyzing client requirements, designing solutions architecture or structure, improving legacy solutions, estimating the workload, mentoring juniors, improving procedures and techniques.
* Reporting development progression, alerting / escalating.
* Updating / learning new technologies.

### Why it would be awesome to work with us
**@EdgeWorks**, you’ll be part of an international class software company benefitting from a friendly agile team ambiance in a European style, only 8 minutes away from HCMC center and with a river view…

As any business we follow market trends, but we also value our people’s aspirations and we welcome and study any viable ideas and initiatives from any EdgeWorkers.

**BENEFITS:**
Social insurance package
1-2 additional day(s) off for Christmas
13th month salary + performance bonus
Annual salary review
Personalized training program (English + technical + methodological + managerial skills) based on a sharing/mentoring spirit
Parking for free
Friendly ambiance in a European style, team building activities, birthdays, events, drinks, gifts…

### Interesting engineering projects
You will increase your value on the job market thanks to a lot of experience with different projects (from 2 weeks to several years) with international clients (from startups to multinational companies) and within diverse industries (e-commerce, manufacturing, healthcare, Fashion and sportswear, transportation...).

Because our clients have specific requirements, you will alternatively work on project and product mode, will be challenged with different methodologies and tools, and will enjoy making research on new technologies (frameworks, libraries, paradigms, tools...)

### Contact
Homepage: edge-works.net
Email: recruit@edge-works.net

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
