### ISSUE TITLE
Fram^ - Senior front-end engineer - HCMC - FT

### ISSUE THREAD

**Issue by framcompany** [awesome-jobs/vietnam#164]
**About us**
Fram - the Swedish software Company helps Scandinavian and Northern European companies leverage the talent and power of Vietnamese rock star developers and other online industry talent. Fram is a very different company. First of all, our culture is different – we believe that to write world class code you need to work in an environment that energizes you and with colleagues that inspire and challenge you. Hence, we sit in a special designed, Scandinavian office on Nguyen Cong Tru in central Ho Chi Minh City. We only work with Scandinavia’s top online employers and we only hire Vietnam’s top 2% developers and internet industry talent.

**Location**

22nd Floor, TNR Tower, 180-192 Nguyen Cong Tru, Dist.1, Vietnam

**Salary Expectation**

**Up to USD 2,000**

Fram is now looking for a Senior front-end engineer to play a key role in developing the product of Sweden’s fastest growing online HR platform.

Our client is changing the way companies work with employer branding and recruiting online. Want to help us make HR heroes? The team you will be working with is a young and fast moving tech startup with smart peoples that are passionate about their work.

You will be playing a key role in a fast growing team focused on the very challenging tasks of developing a set of platforms for market leading online HR platform brands. If you have the ambition to have a stronger improvement for your career path in front-end, there are very few roles more suitable than this one.

You have a minimum five productive years of experience in front-end and JavaScript, extensive experience in web development in general. Good English skills are required.

Most important is that your coding should be at the highest standard, easily maintainable and easy to read. You are able to work independently, you deliver on time and you take initiative to keep team communication alive at all times.

**Requirements**
- Experience with diversified projects, reference cases available.
- Knows how to ship a product with quality, keen on details.
- Good experience in html5/css3 and responsive.
- Experience in front-end performance.
- Experience in AngularJS is a must.
- Team worker.
- Long term commitment to the job, willing to grow with the company.
- Strong English, in speech and in writing.

**Nice to have**
- Acquired intuition and instinct in solving problems after analyzing multiple solutions
- Experience in Ember/React
- Good knowledge in backend development
- Deep understanding of frontend technologies

**Benefits:**
More on Fram – what is it like to work in Fram?

We are passionate individuals driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals with a desire to build something new and actively support our young company in its growth to greatness.

**You will love working here!**
- Excellent salary package (up to 2,000 USD gross), with both 13th month salary and additional performance related annual bonus on top
- 5-day working week (Monday-Friday), working hours to some extent flexible
- Professional and open working environment, with the culture and office of a Scandinavian online company, on Nguyen Cong Tru in central Ho Chi Minh City
- Annual leave and insurance policies in compliance with Vietnam’s Labor Law and company's regulations
- Opportunities to improve English skills within an international team – English is official language in fram^ office. Also regular English lessons two times per week by native English teachers in the office
- Opportunities to gain hands-on experience in cutting-edge technologies
- Opportunities to become one of key member of fram^ as we build this fast growing company together!

**Contact**
For application or asking for further information, kindly contact back to:
- Ms. Lan Anh, Talent Manager, HR Department
- Email: ttla@framco.se
- Skype: mary.trananh
- Website: http://framco.se/

**Comment by joneslee85** [comment]
Like previous post, please fix up the headers
