### ISSUE TITLE
Yojee - Fullstack Engineer - Saigon - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1643]
## Location

* District 4, Saigon, Vietnam

## Salary Expectation

* $1700-2600/month + or negotiable

## Requirements
* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 2+ years of experience in development of various complex systems
* Experienced and proficient in working with at least two languages, preferably Elixir, Javascript, Ruby on Rails, Go, Scala, Haskell or any other functional programming language.
* Experience with frontend technologies like Angular.js, React.js or vue.js
* Experience working with relational database systems (preferably PostgreSQL)

### Nice to have

* DevOps experience with AWS or Azure, Docker
* Production experience with Elixir & Phoenix
* Scripting (Python, Lambda, Bash) 

### About the role

Yojee is looking for a Software Engineer who enjoys developing features end-to-end in a cloud platform environment with Elixir/Phoenix. Due to our strong commitment to team ownership, you will have many opportunities to bring in your ideas and architecture suggestions. A background with DevOps technologies and scripting will enable you to maintain and extend our Continuous Integration environment.

### About Yojee

Our mission is to bring the hundreds of thousands of logistics companies into the digital era, the same way the web browser enabled consumers and sellers to trade online securely.

We are a young team of software engineers who are enthusiastic about using the right technologies for the right job while sticking to best practices and keeping the quality high. This approach helped us to create a platform that reliably handles millions of transactions. We have a strong engineering culture and embrace bottom-up decision making.

### Contact
Homepage: Yojee.com
Lily: Lily@yojee.com
Apply [here](https://yojee.bamboohr.com/jobs/view.php?id=47&source=Github-Awesome)

**Comment by xclusive1111** [comment]
Nice job. Do you guys consider using Elm for the front-end part?

Anyway, this job is literally my dream stack but sadly, it’s too far :((

**Comment by Lilyyojee** [comment]
> Nice job. Do you guys consider using Elm for the front-end part?
> 
> Anyway, this job is literally my dream stack but sadly, it’s too far :((

No we dont use Elm, thanks for your words. Hope to have chance cooperating in near future.
