### ISSUE TITLE
Quoine - Senior Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1646]
# Location

* Saigon, Vietnam

# Salary Range

* US $1500 - $3000

#### We are looking for Senior Front End Engineers with solid ReactJS experience responsible for the client side of our platform delivery. Your primary focus will be to implement amazing user interfaces, using the latest technologies with a focus on performance and usability. You will work in an amazing and dynamic team of leading developers, product designer, digital marketers, and customer service professionals.  

# Responsibility 

* Delivering a complete front end application
* Ensuring high performance on mobile and desktop
* Writing tested, idiomatic, and documented JavaScript, HTML5/CSS3
* Coordinating the workflow between the graphic designer, the HTML coder, and yourself
* Cooperating with the back-end developer in the process of building the RESTful API
* Communicating with external web services

# Requirement

* Deep knowledge of ReactJS and VanillaJS
* Strong understanding of PWA/SPA frontend-architecture
* Creating self-contained, reusable, and testable modules and components
* Ensuring a clear dependency chain, in regard to the app logic as well as the file system
* Thorough understanding of the responsibilities of the platform, database, API, caching layer, proxies, and other web services used in the system
* Experience writing extensive unit tests using automated TDD tasks
* Creating configuration, build, and test scripts for Continuous Integration environments 
* Basic understanding of Nodejs & modern frontend build tools
* Professional, precise communication skills

### Why it would be awesome to work with us
* Join a global leading Fintech company
* Bring cutting-edge technologies into play
* Enjoy exceptional benefits package (tech/non-tech training courses, gym sponsor, extra health insurance for you and your immediate family, daily snack, billiards competition, football weekly... you name it.)
* Work in one of the most modern & innovative spaces in town

# Contact
* Homepage: https://careers.liquid.com/
* E: linh.truong@quoine.com 
* M: 0938 019 369
* Skype: linh.truong.my

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
