### ISSUE TITLE
Truebase–We're building a new kind of software stack...from scratch

### ISSUE THREAD

**Issue by paul-go** [awesome-jobs/vietnam#1647]
## Location

* Remote

## Salary Expectation

* Negotiable

## Requirements
* Knowledge of TypeScript
* Knowledge of Compilers (Parsing, AST transforms, static analysis, etc)
* Courage

## About Us

At Truebase, we're building a new kind of software stack. It's based on a platform that extracts insights from [Truth](https://github.com/paul-go/Truth) code (our open-source type-safe data language). It then uses these insights to emit various digital assets such as native Mac/Windows/iOS/Android apps, data visualization tools, web-based information systems, etc. This technique is based on years of scientific research, and we're now starting to gain major traction from large enterprises. We can't hire as fast as we can close sales.

### Must Have

First and foremost, we're looking for people who can work at the system level. For example: 

- Could you write your own custom regular expression evaluator?
- How about doing code transformations based on static analysis of abstract syntax trees?
- Does building a platform like Electron or React or Bitcoin **from scratch** sound exciting?

The idea is not that you've done these things specifically, but rather that you're eager to slay dragons of this difficulty. Experience with application-level frameworks isn't of much use here–our outstanding issues **do not** look like "Implement a sharing of widgets", but rather "Implement bounded contravariance in the Truth type checker".

Additionally, we're looking for a fairly senior developer that understands what code engineered for a 10+ year lifespan looks like. You should be comfortable being given loose requirements, punching your way through unfamiliar territory, and coming back with an elegant, performant, well-thought-out code library that is a joy for other developers to use (inside or outside the company).

### Why it would be awesome to work with us

We're contrarians–but not for contrarian sake. We have a track record of achieving things deemed "impossible", which we've done by operating genuinely outside the box, rather than simply operating inside a different box, occupied by some ruling class. To be effective at Truebase, you should be energized by our tendency to violate convention, versus object with reasons why we should just do things like The Cool Kids™.

*Side note: Everyone in this company dropped out of school. A lack of degree makes you **more** appealing at Truebase (Pure Math degrees excepted).*

### Interesting engineering projects

We’re working on one of the world’s most pressing computer science problems. Most software and the internet itself can be defined as an information management system, albeit one that has not been generalized yet, hence the legions of developers writing the same CRUD app over and over. And there have been casualties in this area. For example, in the 1980’s, the Japanese government poured ~$500M into trying to solve this problem, and failed.

We’re taking a very different approach towards a solution. For example, we’re not going to just hire a bunch of Math PhD’s in order to get into a position where we can say something like “we know type theory better than the people at Microsoft Research”. This has been tried, and it hasn't worked. Our approach has been to attempt things that are so far out in left field that the mainstream / establishment / academic MSR types wouldn't even have thought of it. So far it’s working. As in, people are paying us.

### Contact
Homepage: [truebase.com](https://www.truebase.com)
Email: jobs (a) truebase (.) com

Or just follow me on GitHub.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
