### ISSUE TITLE
Tiki - Hiring Android Developer for all levels

### ISSUE THREAD

**Issue by tramtran279** [awesome-jobs/vietnam#1648]
## Location

* Viettel Complex Building 285 Cách Mạng Tháng 8, Quận 10

## Salary Expectation

* 700$ up to 1500$/month

## Description
* Design and build high impact features for the Android platform
* Collaborate with cross-functional teams to define, design, and ship new features
* Foster strong culture of software engineering best practices by implementing processes and tools (code reviews, code quality, automation, CI/CD to monitoring)
* Work closely with App Infrastructure team to build scable app architecture and robust testing system

## Requirements
* Bachelor's degree in computer science/engineering
* Experiences in Mobile development (Java), experience in mobile development technology such as React Native, Kotlin Native, OTA update, Instant appk
* Excellent problem-solving skills

## Skills
* Android
* Java
* Kotlin
* React Native

## Benefits
* Macbook provided
* Stock options and healthcare
* Customer-first, open-minded, data-informed culture
* Many opportunities to use next gen technologies to solve interesting problems.

## Contact
Please take a visit the JD and apply at: http://bit.ly/31iuxhm 
Or send me your CV if interested to: tram.tran3@tiki.vn.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
