### ISSUE TITLE
1PAC Vietnam - Backend Developer - Ruby on Rails/AWS/SQL - HCMC - FT

### ISSUE THREAD

**Issue by ThaoHa0107** [awesome-jobs/vietnam#1649]
## Location

* District 1, Ho Chi Minh City, Vietnam
* Our homepage: http://1pac.vn
* Our facebook: https://www.facebook.com/1pacvietnam/

## Salary Expectation

* Up to $2000

## Requirements

* Good understanding of object oriented programming and design patterns
* At least 2 years of working with Ruby and Ruby on Rails framework
* Having knowledge of TDD/BDD and writing test with RSpec
* Able to design database and system
* Experienced with RDBMS Postgres/MySQL and In-memory db Redis/Memcache
* Experienced with infrastructure such as AWS, Heroku
* Good knowledge of Git and Github workflow
* Understanding of CI/CD process and how to implement
* Experienced with JavaScript, HTML/CSS/SASS

## How's your day in 1PAC

* Participate in outsource projects and building company's own product
* Work with other teams on all phases of project development
* Be keen on refactoring code and delivering products with high quality

## Why it would be awesome to work with us

* Personal Macbook Pro provided
* You can work and learn directly from senior Japanese engineer in head office
* We use the one of the coolest application: Github, slack
* Business trip in Japan
* Company trip 1-2 times/year
* Free snacks and drink
* Dinner and lunch party every month
* Extra activities (watch movie, picnic…)
* Career path promotional opportunities
* Others benefits such as holidays and insurance benefits follow Vietnamese law.

## Contact

Email: 1pac.info@1pac.vn
Phone: (+84)28 3925 0000

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
