### ISSUE TITLE
Fram^ - Full stack PHP engineer - HCMC - FT

### ISSUE THREAD

**Issue by framcompany** [awesome-jobs/vietnam#165]
**About us**
Fram - the Swedish software Company helps Scandinavian and Northern European companies leverage the talent and power of Vietnamese rock star developers and other online industry talent. Fram is a very different company. First of all, our culture is different – we believe that to write world class code you need to work in an environment that energizes you and with colleagues that inspire and challenge you. Hence, we sit in a special designed, Scandinavian office on Nguyen Cong Tru in central Ho Chi Minh City. We only work with Scandinavia’s top online employers and we only hire Vietnam’s top 2% developers and internet industry talent.

**Location**

22nd Floor, TNR Tower, 180-192 Nguyen Cong Tru, Dist.1, Vietnam

**Salary Expectation**

**Up to USD 1,600**

Fram is now looking for an experienced full stack PHP developer that is writing short code in a specific and structured way. You will be playing a key role in the tech team of the Scandinavian e-commerce project, which is reaching to a phase of exciting global expansion.

You have a minimum of 2 years (preferably more) of experience in web development. Good English skills are required.

Most important is that your coding should be at the highest standard, easily maintainable and easy to read. You are able to work independently, you deliver on time and you take initiative to keep team communication alive at all times.

Some examples of the tasks that you would be handling:

• Make a general face lift to present site - renew the start page, product pages, make changes and adopt the site for mobile usages. 
• Develop and improve the checkout process. 
• Develop and improve functionality and up-sales process during checkout 
• Improve the warehouse management system and its integration to the web.

**Requirements**
• PHP, HTML, CSS, MySQL, and JavaScript 
• Opensource CMS (e.g. Joomla, Magento, Wordpress, or PrestaShop) 
• Able to write well-structured, maintainable code 
• Good English 
• Can-do-attitude and put the goals of the team before your own prestige 
• You are able and hungry to take on a lot of responsibility 
• You are passionate about what you do and naturally take an interest in the news flow related to your field of expertise as well as make sure you are well informed and up to date on new frameworks and methodologies

**Nice to have**
• E-commerce experience

**Benefits:**
More on Fram – what is it like to work in Fram?

We are passionate individuals driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals with a desire to build something new and actively support our young company in its growth to greatness.

**You will love working here!**
- Excellent salary package (up to 1,600 USD gross), with both 13th month salary and additional performance related annual bonus on top
- 5-day working week (Monday-Friday), working hours to some extent flexible
- Professional and open working environment, with the culture and office of a Scandinavian online company, on Nguyen Cong Tru in central Ho Chi Minh City
- Annual leave and insurance policies in compliance with Vietnam’s Labor Law and company's regulations
- Opportunities to improve English skills within an international team – English is official language in fram^ office. Also regular English lessons two times per week by native English teachers in the office
- Opportunities to gain hands-on experience in cutting-edge technologies
- Opportunities to become one of key member of fram^ as we build this fast growing company together!

**Contact**
For application or asking for further information, kindly contact back to:
- Ms. Lan Anh, Talent Manager, HR Department
- Email: ttla@framco.se
- Skype: mary.trananh
- Website: http://framco.se/

**Comment by joneslee85** [comment]
Please fix up inconsistent headers format

**Comment by framcompany** [comment]
Dear Trung,

 

I have fixed all your recommended.

 

Thanks so much for supporting us.

 

Kind Regards,

Tran Thi Lan Anh
Talent Manager, HR Department, fram^ Ltd Vietnam | www.framco.se <http://www.framco.se/> 

Email: ttla@framco.se <mailto:ttla@framco.se>  | Skype: mary.trananh

Phone: (VN) +84-905 250 286
