### ISSUE TITLE
ROCKSHIP - iOS - SAIGON - FT

### ISSUE THREAD

**Issue by PhamNhuY18** [awesome-jobs/vietnam#1654]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $800/month or range

## Requirements
* Swift, Objective-C
* 1+ years iOS experience

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Design and build advanced applications on iOS
* Ensure the performance, quality, and responsiveness of applications
### You can bring

* A good eyes for design
* A good analyis skill

### Contact
Homepage: rockship.co
Mail : career@rockship.co or Skype : yptn13405

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
