### ISSUE TITLE
TBox - 2 DevOps/SRE Engineers - HCM - FT

### ISSUE THREAD

**Issue by tbox-vn** [awesome-jobs/vietnam#1655]
## Location

* Saigon, Vietnam
* Remote (open after three months of on-site probation)

## Salary Expectation

* $1500 - $2500/month

## About Us

**TBox** is a platform that customers use to book tickets to events (entertainment, sports, all kinds) and movies in Viet Nam. Our aim is to create a vibrant ecosystem around our highly integrated platform. Our web and mobile apps enable consumers to easily discover and get instant access to enjoy quality entertainment. We aspire to radically transform content promotion and distribution and enable our business partners in the entertainment industry to enhance their operations.

We are looking for 2 DevOps/SRE engineers with strong Amazon Web Services (AWS) experience. As a DevOps/SRE Engineer, you will be part of a three-person DevOps/SRE team to build a hybrid cloud strategy and architecture for our multi-tenant, multi-service application stack, delivering components and pipelines as to those in a PaaS product.

You'll define and manage cloud infrastructure as code (IAC), construct & iterate CI/CD pipelines (then transfer it over to development teams), ensure reliability of our systems, build monitoring & instrumentation stacks, maximize the potential of orchestration tools (ECS, Kurbenetes) in our datacenters (based in both Viet Nam and Singapore).

You’ll also work in parallel with our +10-person software development team to ensure our apps:
- Have a clean contract with the underlying systems, offering maximum portability between DCs and between environments (staging, beta, production);
- Are suitable for deployment on cloud platforms and at the same time: platform agnostic, gradually obviating the need for in-house, on-premise servers and silo’d systems administration;

We're utilizing a broad toolset for DevOps/SRE like Docker, Terraform, Grafana, Kurbenetes, Operable/Cog, Circle CI ... and leveraging multiple services from AWS: VPC, ECS/EKS, S3/Athena, RDS/Aurora, ACM, Route53, CloudWatch (in near future: Direct Connect, PrivateLink, EventBridge). We’re also actively looking for a capable cloud provider in Viet Nam to serve as traffic ingestion gateway and backup DC (in case of networking failures). You’ll also be part of the evaluation effort too.

## Requirements

- Minimum of 3 years of total experience to include a minimum of 1 years of web or software development experience.
- Experience automating the provisioning of environments by designing, implementing, and managing configuration and deployment infrastructure as code solutions.
- Experience with building and deploying containers to a production environment.
- Experience delivering scalable solutions utilizing at least one prominent public cloud provider (AWS, GCP, Azure).
- Experience (or willing to take on) with deploying and administering Kubernetes on a cloud platform or on-premise.
- Experience automating and streamlining build, test, and deployment phases for continuous integration.
- Experience configuring and deploying logging and monitoring services - fluentd, logstash, GeoHashes, etc.
- Experience with Git/GitHub/GitLab.
- Comfortable communicating in English (writing is a part of the job and we expect you to co-author multiple internal documentations).
- Having the ability to clearly understand and focus on business outcomes is a real additional value.

## Bonus Skills

- Experience with HashiCorp Vault, administration, and Goldfish; frontend Vault UI.
- Experience with helm for deployment to kubernetes.
- Experience with VPNs; OpenVPN preferable.
- Experience with AWS spot instances or Google preemptible.
- Experience with kubernetes-based software - example - heptio/ark, ingress-nginx, anchore engine.
- Familiarity with the ELK Stack

### PERSONAL ENHANCEMENT
To motivate individual employee improvement to achieve a higher level of success and joy, we offer learning and personal development opportunities for ongoing career. Upon committing, we provide you with our indoor/outdoor technical courses. Expect hack days to be a norm, a whole team is going to dive full head into problems that are nagging at our roadmap but be rest assured you’ll be released after 7PM (on these occasional hackdays).

### SALARY AND BENEFITS
- Our compensation scheme is designed to appreciate and value your efforts through commitments and deliveries (not months worked)
- 13th month salary, seniority bonus
- Work within well defined (or friendly to changes) sprints and milestones
- Annual leave up to 12 days
- Viettel Complex office floor with dedicated desk, amble room for concentration
- We pay you for every hour you work. Need something extra? Give yourself a raise by doing more hours when you can

### Contact
viet.nguyen@tiki.vn

Note: You need not having all the bullet items above and a tailored cover letter would fast track your application a lot.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
