### ISSUE TITLE
Pod Foods Vietnam - Frontend/ReactJS/VueJS - Hanoi - FT

### ISSUE THREAD

**Issue by HaChan** [awesome-jobs/vietnam#1657]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1000 - $2000/month

## Requirements

*  2+ years of experience as a front end web developer
*  2+ years experience with TypeScript or modern JavaScript
*  2+ years experience with a modern UI framework (eg: ReactJS, Redux, VueJS)
*  Experience working with REST APIs
*  Experience building responsive websites and progressive web apps
*  Proficient with modern CSS resources (eg: SCSS, Foundation)
*  Proficient in web development tools and debugging
*  Familiarity with JavaScript unit test tools (eg: Mocha, Jasmine, Jest)
*  BS or MS in Computer Science or other related technical discipline (or equivalent).

### Must Have

* Be a team player with a sense of empathy, awareness, and responsibility

### Ideally

*  Experience working in startups is a plus 
*  Ability to communicate in English is a plus

### Responsibilities

* Help foster a spirit of innovation and collaboration both within the engineering team and across the organization
* Work to create impactful and sustainable solutions to complex problems by taking bold and measured risks
* Balance your technical excellence with a high E.Q., 
* Share the knowledge you gain generously with your peers to perpetuate a culture of engineering excellence

### You can bring

* A good eyes for design
* A good value to our shared target

### Why it would be awesome to work with us

* Competitive compensation based on experience
* Quarterly evaluation with salary and bonus reviews
* Beautiful Silicon Valley inspired office in Lotte Center. It is brand new, let’s come and decorate our second home together!
* Flexible, self-managed paid time off
* Team outings and birthday celebrations
* Self-improvement courses can be requested
* Annual health check
* Premium Life & Healthcare insurance
* Free parking
* The best team and working environment you’ll ever find! 

### Contact
Homepage: https://podfoods.co/
Email: linhdth.tbc[at]gmail.com (Skype: halilee930208)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
