### ISSUE TITLE
CSSOFT - Python Developer (Django) - HN - FT

### ISSUE THREAD

**Issue by phuckhang123** [awesome-jobs/vietnam#1658]
## Location

* Ha Noi, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

## Requirements

* Experience 1+ year in Python 
* Experience with Django framework
* Can use  GIT
* Experience with Linux (Ubuntu)
* Use English in writing

### Responsibilities

* Analyzing requirements, project development planning.
* Researching, learn new technologies

### Why it would be awesome to work with us

* Offer + bonus, 13th salary; Performance bonus; Tet bonus, Birthday,....
* Have full of insurance such as Health Insurance, social insurance, ...
* Have opportunity to work in Japan, Da Nang.
* Professional working environment, friendly, dynamic, creative, encouraging personal development.
* Working hour: Monday to Friday (8h30 - 17h30)

### Contact
Send CV via mail: phuckhang.ttran@gmail.com
Title: [CSSOF - Python - Your Nam]

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
