### ISSUE TITLE
AIA (Vietnam) - Assistant Manager, Solution Architect - HCMC - FT

### ISSUE THREAD

**Issue by AIA-Vietnam** [awesome-jobs/vietnam#1659]
## Location

* Saigon, Vietnam

## Salary Expectation

* Competitive Package

## Requirements

* BSc/BA in Computer Science, Engineering or a related field
* Experience in IT architecture, infrastructure, and cloud development/technologies (AWS, Azure)
* Knowledge of selected coding languages: Java, C#, HTML/CSS, JavaScript
* Familiarity with various operating systems (Linux, Windows) and databases (Mssql, Oracle)
* Broad knowledge of hardware, software and programming
* Engineering and software architecture design
* Good interpersonal, communication and client-handling skills, with the ability to manage expectations and explain technical detail
* Problem-solving aptitude
* Good time management, communication and team work skills
* Good at English skills
* Life insurance knowledge is an advantage

### Responsibilities

* Analyze the technology environment
* Analyze enterprise specifics
* Analyze and documenting requirements
* Setting the collaboration framework
* Create a solution prototype
* Participate in technology selection
* Control solution development
* Support project management

### You’ll be responsible for

* The solution architect’s job focuses on solution-level decisions and analysis of their impact on the overall business goals and outcomes
* Finding the best tech solution among all possible to solve the existing business problems

### Contact
* If you are keen to explore or know someone who'd be a good fit, please do not hesitate to contact me at Duy-Khang.Pham@aia.com.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
