### ISSUE TITLE
AIA (Vietnam) - Business Analyst  - HCMC - FT

### ISSUE THREAD

**Issue by AIA-Vietnam** [awesome-jobs/vietnam#1660]
## Location

* Saigon, Vietnam

## Salary Expectation

* Competitive Package

## Requirements
* University graduation in IT field
* 3-5 years experiences in Information Technology industry and Business analysis role
* Experience in Life insurance domain is preferred
* Good at spoken and written in both Vietnamese and English
* Good teamwork skills
* Good Analytical skills
* Good Project Management skills

### Responsibilities
* Works with business partner to elicit high-level requirements and capture business needs 
* Clearly articulates and documents business requirements 
* Coordinates project delivery by participating in design reviews and walk-throughs to communicate systems designs and validate proposed solutions 
* Engages with knowledge workers to incorporate usability and user interface needs when designing systems
* Obtains key inputs from enterprise architecture teams and identifies solution interdependencies 
* Proactively resolves customer satisfaction issues
* Assesses the risks of various solutions and prioritizes competing business demands
* Manages ongoing relationship with business partner to drive satisfaction with IT
* Manage assigned projects, coordinate among stakeholders of the projects to ensure the projects are finished on time, on budget

### You’ll be responsible for

* Work as a liaison between business users and IT on business requirements of IT projects
* Project management on assigned projects to ensure the projects are finished on time, on budget

### Contact
* If you are keen to explore or know someone who'd be a good fit, please do not hesitate to contact me at Duy-Khang.Pham@aia.com.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
