### ISSUE TITLE
AIA (Vietnam) - Assistant Manager, System Analyst – Service Delivery - HCMC - FT

### ISSUE THREAD

**Issue by AIA-Vietnam** [awesome-jobs/vietnam#1661]
## Location

* Saigon, Vietnam

## Salary Expectation

* Competive Package

## Requirements
* Education – Bachelor’s degree in Computer Science, Information Systems, a related discipline.
* Min. 5 years of experience, 3 years in IT area 
* Good at English skills.
* Good time management, communication and team work skills
* Broad knowledge of hardware, software and programming
* Good interpersonal and client-handling skills, with the ability to manage expectations and explain technical detail
* Business awareness
* A methodical, investigative and inquisitive mind
* Presentation skills

### Responsibilities

* Examine existing IT systems and business models
* Analyze system’s requirements, develop solutions & assume responsibility of product development
* Execute, configure and test feasible solutions.
* Extensively liaise with external and/or internal clients
* Document and map interfaces between new systems and legacy
* Convert client requirements into highly specified project briefs
* Identify alternatives for potential solutions and estimate them for both technical and business suitability
* Produce reports about project feasibility and costings
* Ability to present proposals to clients
* Ability to work and plan flexibly to deadlines
* Work closely with colleagues, developers, testers and a variety of end users to ensure technical compatibility and user satisfaction
* Cooperate with developers to ensure designs are built to spec
* Design landscape, create business diagram, and supervise peers to implement system
* Supervise implementation of a new system including data migration
* Support users on change control and system updates
* Provide training and user manuals of a new system to users
* Keep up-to-date with technology and industry
* Capable to study and research for the best suitable solutions and apply to the product/project
* Comply to all documented standards, guidelines and procedures
* Troubleshoot technical issues
* Risk mitigation planning
* Conduct regular reviews of systems and generating reports on efficiencies and improvement areas

### You’ll be responsible for

* Collaborate with Business Analysts, Project Leads, IT team to resolve issues and ensuring solutions are viable and consistent, all with the aim of improving business efficiency and productivity

### Contact
* If you are keen to explore or know someone who'd be a good fit, please do not hesitate to contact me at Duy-Khang.Pham@aia.com.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
