### ISSUE TITLE
AIA (Vietnam) - Supervisor/Assistant Manager, Technical Architect - HCMC - FT

### ISSUE THREAD

**Issue by AIA-Vietnam** [awesome-jobs/vietnam#1662]
## Location

* Saigon, Vietnam

## Salary Expectation

* Competive Package

## Requirements

* BSc/BA in Computer Science, Engineering or a related field
* Proven experience as a Technical Architect, cloud technologies (AWS, Azure)
* Hands-on experience with software development and system administration
* Understanding of strategic IT solutions
* Experience in project management, service-oriented architecture (SOA) and Micro-services
* Knowledge of selected coding languages: Java, C#, HTML/CSS, JavaScript
* Familiarity with various operating systems (Linux, Windows) and databases (Mssql, Oracle)
* Good interpersonal, communication and client-handling skills, with the ability to manage expectations and explain technical detail
* Problem-solving aptitude
* Good time management, communication and team work skills
* Good at English skills
* Life insurance knowledge is an advantage

### Responsibilities

* Understand company needs to define system specifications
* Plan and design the structure of a technology solution
* Communicate system requirements to software development teams
* Evaluate and select appropriate software or hardware and suggest integration methods
* Oversee assigned programs (e.g. conduct code review) and provide guidance to team members
* Assist with solving technical problems when they arise
* Ensure the implementation of agreed architecture and infrastructure
* Address technical concerns, ideas and suggestions
* Monitor systems to ensure they meet both user needs and business goals

### You’ll be responsible for

* Design functional technology solutions & provide technical leadership and support to software development teams

### Contact
* If you are keen to explore or know someone who'd be a good fit, please do not hesitate to contact me at Duy-Khang.Pham@aia.com.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
