### ISSUE TITLE
Success-SS - Project Team Leader - Saigon - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#1666]
## Location
* Saigon, Vietnam
* Remote

## Salary Expectation
* $1500 - $3000 gross /month

## Requirements
* 2-4 years of experience in software development project of full life cycle
* Good knowledge in software development process, quality models, standards
* Degree in Computer Science or related technical discipline
* Capable of using English language professionally (speaking, writing, reading and listening skills) equivalent to TOEIC 600 scores
* Good analytical and report writing skills, communication skills, problem solving skills
* Good presentation skills
* Team-oriented
* Aptitude to learn and understand new and emerging technologies

### Level 1
* Coordinate all aspects of a project management and ensure smooth project execution, delivery of quality software products, and client is satisfied with the work that project is doing
* Plan the project (estimate, staff, risk management, training, software development plan, etc.)
* Allocating work and resource (people, equipment, facilities, materials, etc.) for the project team
* Manage resources, staffing, skill sets transferring, and recruiting of the project
* Monitor and control projects
* Communicate project status and issues to management (Delivery Manager, CEO) and client
* Developing team spirit, motivating and building morale; dealing with problems
* Mentor and provide guidance to project members
* Make presentation/white papers for new initiatives
* Take responsibility for establishing, implementing, maintaining and improving the process compliance of each corresponding department

### Level 2
* Participate in the recruitment when necessary
* Participate in pre-sales meetings and marketing events when necessary Authorities
* Approve the performance, career path for the subordinate
* Check appropriate software/hardware purchases and other project items

### Challenges for you
* Be responsible for closely monitoring the schedule, scope and budget of the project. 
* Coordinates all functional aspects of project team initiatives – Requirements Management, Design, Development, Quality Control, and 3rd party vendors – to ensure that requirements are met and exceeded. 
* Carry out this responsibility by motivating and guiding project teams while collaborating with internal/external clients throughout the software development process until project completion.

### You can bring
* A good eyes for design
* A good analysis skill
* A good collaboration and communication skills (interaction skill)
* A great sense of humor
* Being Proactive and Active
* Simplicity and flexibility

## Why it would be awesome to work for Success Software Services?
Founded in 2012, Success Software Services has quickly grown into a leading global provider of digital consulting and software development services. Our satisfied customers span four continents and an array of industries. With world-class delivery centers located in metropolitan Ho Chi Minh City, Vietnam, our distributed teams rival the best engineering talent to be found anywhere. We are both a people-oriented and process-driven organization, having achieved CMMI Level 3 and ISO 9001 designations, and maintain a best-in-class Agile practice.
With the friendly working environment, the great policies, the enormous benefits as well as the excellent leadership team, Success Software Services has been building its team with nearly 100 IT talents in Vietnam. We welcome any aspiring candidates out there who are looking to challenge themselves and leave a big impact on their career path.

## Other interesting benefits you will enjoy
* Company trip.
* Team building for quarterly.
* Year-end party, … and activities for special days in the year.
* Sport (badminton, football).
* Happy hour (twice/month).
* Technical seminar incentive.
* 24/7 Insurance.
* Training activities: Management, Soft skill, Technology.
* Others: Charity events, Women day, Children day, Employee of the Quarter/Year, etc.
* Tet bonus.
* English incentive from 12-24 million/ year.
* Referral bonus from 10 -30 million.
* Specialized research and in-house training conducting bonus.
* Certificates incentive.
* Annual leave: 12 days.
* Public leave: 10 days.
* Christmas leave: 1 day.
* Birthday leave: 1 day.
* Annual Health-check Program.
* Working time from 08:30- 17:30 (Monday – Friday). 

## Contact
Homepage: https://successsoftware.global/
Dare John Adesanya: dare.adesanya@success-ss.com.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
