### ISSUE TITLE
VNG - Senior Software Engineer (Golang) - HCM - FT

### ISSUE THREAD

**Issue by Nguyen-Nguyen-Quynh-Huong** [awesome-jobs/vietnam#1671]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiate

## Requirements
* Golang
* Redis, Memcache... 
* MySQL, PostgreSQL, ...
* 3+ years Software Engineering experience

### Responsibilities

* Great power comes with great responsibilities!

### You’ll be responsible for

* Building ZaloPay - a mobile payment application with many unique features

### Contact
* Skype: huongngng96
* Mail: huongnnq@vng.com.vn

![13925835_1106215049445501_7122732178064345412_o](https://user-images.githubusercontent.com/52448078/62591348-89379700-b8f9-11e9-8ea1-33f82fb48d6b.png)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
