### ISSUE TITLE
Resola - React Native Developer - Anywhere - C

### ISSUE THREAD

**Issue by kshioz** [awesome-jobs/vietnam#1672]
## Location

* Anywhere(remote work)

## Salary Expectation

* $1500-$2000/month
* This is temporary work for 3 months!: Sep-Nov or Oct-Dec 2019

## Requirements

* Strong communication with English or Japanese
* Good working experience in using JavaScript, HTML5, CSS.
* Report your daily task

## Skills
* Strong Javascript
* Strong knowledge of React Native libs, React Component, ES6
* RESTful API
* Database MySQL

### Must Have

* Minimum 2 year commercial experience in mobile app development with React Native
* Solid understanding of HTML, CSS3, Bootstrap, SASS, LESS, responsive design
* Good knowledge in RESTful API
* Be able to manage version with Git

### Ideally

* Experience with iOS/Android native app development is a plus
* Experience with ReactJS is a plus

### Responsibilities

* Front-end Mobile Web development (HTML5, CSS3, React Native, integration with RESTful Web API)
* Review test plans
* Follow our rule to develop software
* Integration test with connecting to a server.

### Why it would be awesome to work with us

* Flexible work style
* Multinational members

### Interesting Engineering Projects

* We apply latest techlonogy to our product

### Contact
Homepage: https://resola.ai/
Email: okuda@resola.ai

**Comment by datvp09** [comment]
hi @kshioz 
Is this job still available?
Resola còn tuyển ko ạ

**Comment by kshioz** [comment]
@datvp09 
Can you send email to Mr. okuda? Please see "Contact" for his address.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
