### ISSUE TITLE
MyKaki- Technical Leader/ Senior Software Engineer (Python)- HCM - FT

### ISSUE THREAD

**Issue by ndmthu1997** [awesome-jobs/vietnam#1674]
## Location

* Q3, HCM, Vietnam

## Salary Expectation

* Up to $3000/month 

![image](https://user-images.githubusercontent.com/39650798/62600919-55b93480-b91a-11e9-906e-5a10559a8f09.png)

## Requirements

- Knowledge and Experience in Python and Angular is a benefit
- Proactive and responsible attitude
- Good proficiency in English
- Self-organized, able to deliver quality documentation and code reviews
- Knowledge in software architecture
- Experience with building, maintaining and debugging software in production

### Responsibilities

As Technical Leader, a core member for our product, you will advance our mission to bring logistics to millions of people by developing easy-to-use and innovated platform for all sellers, buyers and even you.

✈ Break down product requirements and user stories into technical specifications

✈ Database Design, using Entity Relationship (ER) Diagrams

✈ Design and review API contracts

✈ Communicate design to team

✈ Run daily standups to remove blockers

✈ Track project progress ensuring highest quality of work

✈ Support and monitor developers and QA team

✈ Do code review (full stack preferred)

✈ Communicate with various stakeholders (Product, Design, Business)

### You’ll be responsible for

* Development of Logistics Platform, an automated solution for international logistics systems

### Why it would be awesome to work with us
🌏Have opportunities to learn, explore and build a product from scratch and about logistics which is developing more and more popular these days and changing the lifestyles.

🚤 Have opportunities to travel to China, Vietnam, Singapore for business trip when required

🏫 Acquire a variety of technical and soft skills from experienced Software Engineers and Entrepreneurs

💪 Intensive training & development with the focus on-the-job training and coaching by business managers

💰 13th month salary

👩‍⚕️ Extra Health Insurance PVI

💳 Labor contract, social insurance, annual days off are based on Vietnamese law

🥇Employee of the Month Award with Attractive gifts recognize outstanding contributions.

💻Working devices are provided

🛣 Clearly defined long-term career road-map for those who are qualified

🌱Working in a young, dynamic, friendly, well-equipped environment both with Singaporean and Vietnamese

### Contact
Email: june@swlog.com.sg
Join Us: https://airtable.com/shr06MC06uFCe3CGm

![job 5-08](https://user-images.githubusercontent.com/39650798/62600218-85ffd380-b918-11e9-8319-c018ef2d7398.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
