### ISSUE TITLE
LOGIVAN - Senior Backend Engineer (Ruby) - HCM - FT

### ISSUE THREAD

**Issue by logivanhr** [awesome-jobs/vietnam#1675]
## Location

* 506 Nguyen Dinh Chieu, Ward 4, District 3, Ho Chi Minh, Vietnam
* Full-time

## Salary Expectation

* Up to $2,300 / month

## Requirements
* At least 3 years of experience as a Backend Engineer
* Strong understanding of object-oriented programming
* Experience working with relational databases
* Basic understanding of frontend technologies, such as HTML, JavaScript, CSS
* Experience in shipping web applications to production, CI/CD flow
* Familiarity with running large scale web services
* Enthusiasm to join a fast-paced start-up environment
* Ability to think like the end user to understand, fulfil and delight customers
* Excellent problem solving skills
* English language to a good standard is an advantage

### You’ll be responsible for

- Collaborating across functions in your scrum team
- Designing and developing backend services and actually working on code that makes you happy
- Writing clean, simple and efficient code, covered with tests
- Suggesting and proposing creative solutions to solve problems
- Peer-reviewing other members’ work
- Training and mentoring more junior engineers
- Joining an open, friendly and performance-oriented culture

### Why it would be awesome to work with us
- Environment: Start-up, young & dynamic
- Bonuses: Cash performance-linked bonus and stock options
- Benefits: Flexible working hours, remote working allowance, office food & drink, team social events and competitive benefits package

### Contact
Homepage: https://www.logivan.com/
Email: hr@logivan.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
