### ISSUE TITLE
LOGIVAN - Senior Frontend Engineer (ReactJS) - HCM - FT

### ISSUE THREAD

**Issue by logivanhr** [awesome-jobs/vietnam#1676]
## Location

* 506 Nguyen Dinh Chieu, Ward 4, District 3, HCMC
* Full-time

## Salary Expectation

* Up to $2,300 / month

## Requirements
- 3 years experience working with JavaScript (ideally ES6), ReactJS and frontend web development
- Proficiency in ReactJS is essential
- Experience working with Redux
- Understanding of HTTP, RESTful APIs, and JSON format
- Knowledge of modern authorization mechanisms, such as JSON Web Token
- Experience with bundlers like Webpack
- Proficiency and passion with automated testing (like Jest)
- Good product mindset, communication and English skills

### You’ll be responsible for
- Collaborating across functions in your scrum team
- Designing and developing backend services and actually working on code that makes you happy
- Writing clean, simple and efficient code, covered with tests
- Suggesting and proposing creative solutions to solve problems
- Peer-reviewing other members’ work
- Training and mentoring more junior engineers
- Joining an open, friendly and performance-oriented culture

### Ideally
- Experience with CI/CD
- Experience with crash analytics and reporting

### Why it would be awesome to work with us
- Environment: Start-up, young & dynamic
- Bonuses: Cash performance-linked bonus and stock options
- Benefits: Flexible working hours, remote working allowance, office food & drink, team social events and competitive benefits package

### Contact
Homepage: https://www.logivan.com/
Email: hr@logivan.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
