### ISSUE TITLE
LOGIVAN - React Native Developer - HN & HCM - FT

### ISSUE THREAD

**Issue by logivanhr** [awesome-jobs/vietnam#1677]
## Location

* 3rd Floor D2, Giang Vo, Ba Dinh, Ha Noi, Vietnam
* 506 Nguyen Dinh Chieu, Ward 4, District 3, HCM
* Full-time

## Salary Expectation

* Up to $2,300 / month

## Requirements
- Experience in API design, SDK architecture, and mobile software lifecycle development practices.
- Experience working with Redux
- Familiarity with native build tools, like Xcode or Android Studio
- At least one year of real work experience with React Native, must understand basic philosophy of React Native and React component lifecycle
- Experience with push notification
- Solid understanding of how to convert design into mobile application, ability to effectively layout to adapt to different screen sizes.
- Knowledge of modern authorization mechanisms, such as JSON Web Token is a plus
- Understanding of HTTP, RESTful data structures, and JSON format.
- Good product mindset, communication and English skills

### You’ll be responsible for
- Collaborating across functions in your scrum team
- Designing and developing frontend products and actually working on code that makes you happy
- Writing clean, simple and efficient code, covered with tests
- Suggesting and proposing creative solutions to solve problems
- Taking ownership of the features you design and develop right through into usage
- Peer-reviewing other members’ work
- Training and mentoring more junior engineers
- Joining an open, friendly and performance-oriented culture

### Ideally
- Experience with mobile CI/CD
- Crash analytics and reporting
- Experience with CodePush or other release delivery service

### Why it would be awesome to work with us
- Environment: Start-up, young & dynamic
- Bonuses: Cash performance-linked bonus and stock options
- Benefits: Flexible working hours, remote working allowance, office food & drink, team social events and competitive benefits package

### Contact
Homepage: https://www.logivan.com/
Email: hr@logivan.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
