### ISSUE TITLE
Orchard.vn - Python Developer (Odoo)

### ISSUE THREAD

**Issue by congdpt** [awesome-jobs/vietnam#1678]
## Location
* 5th floor, 79 Truong Dinh st, Ben Thanh ward, district 1, HCMC
* Full - Time

## Salary Expectation
* Up to 1,000$ / month

## Skills
* Python
* Odoo (OpenERP)
* PostgreSQL, CSS, XML.
* Linux

### Must Have
* Experience with Odoo,
* Strong experience with Python
* Have Knowledge of PostgreSQL, CSS, XML

### Ideally
* Experience with Odoo version 10

### Responsibilities
* Get Odoo requirements (OpenERP), analyze and build solutions, build functions as required by the company.
* Supporting end-users during operate system: Guiding, training, handling arising situations.

### You’ll be responsible for
* Building an internal module (Stock, Purchase, Sale, HR, POS)

# Contact 
Website:  www.orchard.vn
Email: cong.duongphamthanh@orchard.vn
Subjects: [Python - Fullname]

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
