### ISSUE TITLE
Spiderbox Design - Full Stack Senior Developer (ReactJS) - Saigon - FT

### ISSUE THREAD

**Issue by donnguyen** [awesome-jobs/vietnam#1681]
## Location

* Saigon, Vietnam

## Salary Expectation

* Up to $1800/month

## Requirements

* Over 2 years working experience with ReactJS and any of backend stack (Java, .NET or ROR). 
* Good understanding of asynchronous request handling, partial page updates, and AJAX. 
* Proficient understanding of code versioning tools, such as Git 
* Familiar with asynchronous programming, ES6, typescript
* Clear communication skills for reporting needs and answering technical and service questions 
* Experience working in an agile development environment

### Ideally

* Java Backend experience 
* Familiar with CI/CD 
* Familiar with TDD/BDD 
* Quality English communication & experience 
* Experience with AWS / Google Cloud deployment 
* Experience working with foreign companies, in particular Australia 
* Experience working in a fast paced agile team 
* Is available to travel to Australia where required

### Responsibilities
Full Stack Senior Developer will be part of a fast growing team of developers to support a range offront end and back end projects for a large Australian client. You will be working with a small team ofsenior developers and QA initially to build velocity and support as a foundation team developing thefront end to support a range of products for the Australian Utility Industry. We work within an AgileSCRUM methodology.

* Report directly to team leader-Develop highly-responsive, web-based user interface components and modules using ReactJS. 
* Ability to work in an agile environment and Iterate quickly based on customer and internal feedback. 
* Constantly learn and keep abreast of emerging technologies. 
* Accurate estimation and delivery of  deadlines 
* Support the QA process and ensure client delivery is 100% tested and stable

### Why it would be awesome to work with us

Based in Melbourne, Seattle and Saigon, Spiderbox Design is a fast growing, small software firm thatdevelops for clients as an agency as well as internal self owned/funded software.

We value and understand the importance of our team and their happiness and career ambitions. It isimportant to Spiderbox that our staff are not only happy but are provided the opportunity to continueto grow, learn and improve their expertise and skills.

With a nothing is impossible attitude, Spiderbox Design has grown and worked across a range ofchallenging and exciting full stack projects and apps.

* Competitive and attractive salary 
* New Computer (Mac/PC) that fits your need. 
* Comfortable work environment. 
* A conveniently located in D3 office. 
* International, dynamic, friendly working environment. 
* Annual performance review: recognize your efforts and identify development/ improvement needs 
* Clear KPI’s and expectations.

### Contact
Homepage: https://spiderbox.design
Don Nguyen: don@spiderbox.design

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
