### ISSUE TITLE
SourceSage- NINJA Software Engineer (Python/Angular/React)- HCM - FT

### ISSUE THREAD

**Issue by jianminsim** [awesome-jobs/vietnam#1682]
## Location

* Saigon, Vietnam (Q10, UP Coworking)

## Salary Expectation

* $1200/month to $2200/month 

## Requirements
* Knowledge and Experience in Python and Angular is a must
* DevOps knowledge
* Proactive and responsible attitude
* ok in an English environment (but not required)
* Self-organized, able to deliver quality documentation and code reviews
* Knowledge in software architecture
* Experience with building, maintaining and debugging software in production
* 3+ years Software Engineering experience
* Bonus if have payments related knowledge or experience

### Must Have

* Knowledge and Experience in Python and Angular/React is a must

### Responsibilities

Great power comes with great responsibilities!
As a core member for our product, you will advance our mission to bring B2B transactions to millions of people by developing easy-to-use and innovated platform for all sellers, buyers and even you.

✈ Break down product requirements and user stories into technical specifications

✈ Database Design, using Entity Relationship (ER) Diagrams

✈ Design and review API contracts

✈ Communicate design to team members and product team

✈ Run daily standups to remove blockers

✈ Track project progress ensuring highest quality of work

✈ Support and monitor developers and QA team

✈ Do code review (full stack preferred)

✈ Communicate with various stakeholders (Product, Design, Business)

### You’ll be responsible for

* Development of B2B Platform, and automating creation of marketplaces for companies

### Why it would be awesome to work with us

* Have opportunities to learn, explore and build a product from scratch and about local vietnam B2B marketplace (VINsme) which is developing more and more popular these days.

* Have opportunities to travel to Singapore and India for business trip when required

* Acquire a variety of technical and soft skills from experienced Software Engineers and Entrepreneurs

* Intensive training & development with the focus on-the-job training and coaching by business managers

* Performance incentives and promotion in role

* Referral bonus for those who refer other engineers will be rewarded!

* Employee of the Month Award with Attractive gifts recognize outstanding contributions.

* Clearly defined long-term career road-map for those who are qualified

* Working in a young, dynamic, friendly, well-equipped environment both with Singaporean and Vietnamese

### Contact
Homepage: https://sourcesage.co
Contact email: hr@sourcesage.co; jian.sim@sourcesage.co 
Job application link: https://docs.google.com/forms/d/e/1FAIpQLScH4Vul7IJLomAzn995_spWlqtnC6HZ-gy6i-vxPh8bzSNfZw/viewform

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
