### ISSUE TITLE
VCCorp - Back-end Server Developer - HN - FT

### ISSUE THREAD

**Issue by LammDuongg2611** [awesome-jobs/vietnam#1687]
## Location

* HaNoi, Vietnam
* Fulltime

## Salary Expectation

* Up to $1,500/month or range

## Requirements
* At least 1 year of experience working with Golang, Python, NodeJS.
* 3 years of experience with server-side programming language.
* Object oriented programming.
* Experience in working with MySQL, Redis, MongDB.
* Experience in RPC, namely gRPC.
* Work well with Git.
* Having an understanding of optimal performance handling, Security is an advantage.
* Golang:
Have a good understanding of Go syntax, read Go code.

* Python:
Have a good understanding of Python syntax, read Python code.
Experience in machine learning, photo or video processing
Understanding Libav
Knowledge of Supervised, Unsupervised and Incremental Training dataset.

* NodeJS:
Have at least 1 year experience in HTML, Javascript
Master at least 1 of 3 frameworks: React, Angular or Vue
Experience in RPC, namely gRPC
Have a good understanding of Nodejs syntax, read Nodejs code.
### Responsibilities
* Participate in developing projects using servers with Golang language, NodeJS, Python related AI, Machine learning, image and video processing.
* Requirement analysis, detailed design, project development planning.

### Why it would be awesome to work with us
* The income level deserves the ability.
* Policies of social insurance, health insurance and other benefits in accordance with the provisions of the Labor Law and the Company.
* Provided modern equipment needed to improve working efficiency.
* Lunch offered, work allowance ...
* Working in a dynamic environment, having opportunities to improve professional skills regularly, there are many exciting cultural activities.
* To maximize his department.

### Contact
Send CV via mail: duongthanhlam261198@gmail.com
Title: [VCCorp - Backed Server - Fullname]

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
