### ISSUE TITLE
SourceSage - Business Development/Partnership/Sales Guru

### ISSUE THREAD

**Issue by jianminsim** [awesome-jobs/vietnam#1688]
## Location

* Saigon, Vietnam (Q10, UP Coworking) or Hanoi (negotiable)

## Salary Expectation

* $700/month to $1500/month

## Requirements
* Knowledge of b2b enterprise sales
* Ecommerce experience in onboarding suppliers/merchants
* Alternatively, experience working in banks
* Experience ~3 or more years is a bonus

### Must Have

* Enterprise B2B business development or sales or partnership experience is a must

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building relationships with local companies, MNCs, suppliers and banks
* Facilitate buying and selling (ecommerce) between buyers and sellers on the platform
* Facilitate fulfillment on the orders placed on the platform
* Get more buyers and sellers on the platform
* Talk to government in Hanoi

### Why it would be awesome to work with us

* Have opportunities to learn, explore and build a product from scratch and about local vietnam B2B marketplace (VINsme) which is developing more and more popular these days.

* Have opportunities to travel to Singapore and India for business trip when required

* Acquire a variety of technical and soft skills from experienced Software Engineers and Entrepreneurs

* Intensive training & development with the focus on-the-job training and coaching by business managers

* Performance incentives and promotion in role

* Employee of the Month Award with Attractive gifts recognize outstanding contributions.

* Clearly defined long-term career road-map for those who are qualified

Working in a young, dynamic, friendly, well-equipped environment both with Singaporean and Vietnamese

### Contact
Homepage: https://sourcesage.co
Email: jian.sim@sourcesage.co, hr@sourcesage.co

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
