### ISSUE TITLE
B&K Software - Ruby on Rails Developer - Hanoi/Saigon - FT

### ISSUE THREAD

**Issue by vinhle7859** [awesome-jobs/vietnam#1689]
## Location

* Kim Anh Building, No. 1, Lane 78, Duy Tan, Dich Vong Hau, Cau Giay District, Ha Noi
* Level 10th Dreamplex Building, 195 Dien Bien Phu Street, Ward 15, Binh Thanh District, Ho Chi Minh City

## Salary Expectation

* Up to $2,000 per month

## Requirements
* Ruby
* Ruby on Rails
* 3+ years experience

## Skills

* Skill: Ruby on Rails, Java, NodeJS, ReactJS/VueJS
* Experience with Automated Test and Test Driven Development.
* Experience in unit testing such as RSpec, selenium-web driver…
* Understand and be able to use good meta programming and design patterns.
* Experience in git and Gitflow.
* Need to have Self-Learning skill and be able to work under pressure.
* Ability to communicate and solve good problems.

### Responsibilities

Join us in participating Ruby on Rails projects of top Japanese customers. Potential technical lead or delivery lead for Japan market in Ha Noi.
* Analysis of system requirements, system design.
* Providing optimal technical solutions, solving problems.
* Carry out development work.
* Always improve productivity and quality of yourself.
*Proficient use JavaScript, HTML and CSS.

### Why it would be awesome to work with us

* Attractive salary agreed upon capacity.
* Enjoying good remuneration of company when becoming an employee: social insurance, annual company trip, 13th salary, End Year bonus,…
* Recognition and rewards based on your performance.
* Continuous and professional training to fully develop your potential.
* Creative, modern and open working place.
* Working hours: 8:30 ~ 17:30, 5 days/ week.

### Contact
Apply CV via: **huyvinh785@gmail.com** 
=> Subject: **B&K_RoR_Your Name**
Websites: https://bnksolution.com/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
