### ISSUE TITLE
Success-SS - Intermediate ASP. Net Developer - Saigon - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#1690]
## Location
* Saigon, Vietnam

## Salary Expectation
* $800 - $950 gross /month

## Requirements
* 2 and above years of experience
* Diploma Degree in Computer Science/IT
* Knowledge of software development process, especially software analysis & design processes, implementation process
* Have knowledge about MVC, Web API, Entity framework
* Experience in application domains and technologies that match the company’s focus.
* Capable of English writing and listening skills which is equivalent to TOEIC 400 score
* Aptitude to learn and understand new and emerging technologies.
* Team-oriented

## Responsibilities
* Can be assigned to play the role of Developer, or Designer, or Database:
* Take responsibility for establishing, implementing, maintaining and improving the process compliance of each corresponding department

### Level 1 - Developer
* Participate in design/code reviews
* Coding, implementing, maintain, and troubleshoot software
* Aid in creating prototype/test applications
* Work with members of project teams to make certain specifications are satisfied
* Adhere to strict delivery schedules

### Level 2 - Developer/Software Architect
* Select the most appropriate technical solution (architecture, design approaches or preliminary designs) and then demonstrate proposed solution to the client and the development team
* Understand non-functional requirements such as performance, scalability, security, maintainability and consult Technical Leads to create solutions meeting those requirements for a complex enterprise application
* Write implementation documentation

### Level 3 - Developer/Software Architect
* Design the software application based on architecture and requirements (design packages, design subsystems, …)
* Write design documentation
* Review code

### Challenges for you
* You will work in a team of developers to deliver working software solutions for clients
* You will be responsible for the implementation of software applications. 
* You will play many different roles in a project implementation such as Software Designer, Developer, Database Administrator.

### You can bring
* A good eyes for design
* A good analysis skill
* A good collaboration and communication skills (interaction skill)
* A good sense of humor
* Being Proactive and Active
* Simplicity and flexibility

## Why it would be awesome to work for Success Software Services?
Founded in 2012, Success Software Services has quickly grown into a leading global provider of digital consulting and software development services. Our satisfied customers span four continents and an array of industries. With world-class delivery centers located in metropolitan Ho Chi Minh City, Vietnam, our distributed teams rival the best engineering talent to be found anywhere. We are both a people-oriented and process-driven organization, having achieved CMMI Level 3 and ISO 9001 designations, and maintain a best-in-class Agile practice.
With the friendly working environment, the great policies, the enormous benefits as well as the excellent leadership team, Success Software Services has been building its team with nearly 100 IT talents in Vietnam. We welcome any aspiring candidates out there who are looking to challenge themselves and leave a big impact on their career path.

## Other interesting benefits you will enjoy
* Company trip.
* Team building for quarterly.
* Year-end party, … and activities for special days in the year.
* Sport (badminton, football).
* Happy hour (twice/month).
* Technical seminar incentive.
* 24/7 Insurance.
* Training activities: Management, Soft skill, Technology.
* Others: Charity events, Women day, Children day, Employee of the Quarter/Year, etc.
* Tet bonus.
* English incentive from 12-24 million/ year.
* Referral bonus from 10 -30 million.
* Specialized research and in-house training conducting bonus.
* Certificates incentive.
* Annual leave: 12 days.
* Public leave: 10 days.
* Christmas leave: 1 day.
* Birthday leave: 1 day.
* Annual Health-check Program.
* Working time from 08:30- 17:30 (Monday – Friday). 

## Contact
Homepage: https://successsoftware.global/
Dare John Adesanya: dare.adesanya@success-ss.com.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
