### ISSUE TITLE
ORO Viet Nam - PHP Developer - HCMC - FT

### ISSUE THREAD

**Issue by tuandnacv** [awesome-jobs/vietnam#1691]
## Location

* Saigon, Vietnam

## Salary Expectation

* From 700$ - 1200$/month

## Requirements

* PHP
* PHP frameworks such as WordPress, Magento 2, etc
* MySQL
* 2+ years Software Engineering experience

## Skills

* Have knowledge about OOP and MVC.
* Have 2 years or more experience in working with PHP and at least one of PHP frameworks such as WordPress, Magento 2, etc.
* Have experience in working with databases such as MySQL.
* Have experience in working with HTML, Javascript, and CSS.
* Have experience in working with source control system such as GitHub.
* Read English well.

## Others skills:

* Have knowledge about compatibility between browsers.
* Have good communication skills and collaborate well with other members.

## Bonus (Not required):

* Have experience with other PHP Frameworks such as WordPress, Magento 2, CakePHP, etc.
* Have experience with Server operation such as CentOS
* Have experience with Google services.
* Have knowledge with Amazon Web Services.
* Have passionate to explore new technology

## Soft skills:

* Be disciplined.
* Be responsible.
* Be progressive.

## Why You'll Love Working Here
* Working with Japanese experts can help you improve your ability to work
* International, challenging, and friendly working environment
* Salary for 13th month
* Full of social welfare under Vietnamese Labor Law (Insurance, annual leave, ...)
* Annual travel and team building activities
* 12 annual leave days and 3 paid summer holidays
* Training: Trained in soft and technical skills

### Contact
Apply CV via: dang.ngoc.tuan@oro.com
=> Subject: ORO_PHP_Your Name
Website: https://www.vn.oro.com/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
