### ISSUE TITLE
VMAX - Back-End Blockchain Engineer - Saigon - FT

### ISSUE THREAD

**Issue by phunguyen1990** [awesome-jobs/vietnam#1693]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* $1,500/month 

## Requirements
* NodeJS or similar back-end languages like Go, Python. 
* Willingness to constantly learn new programming languages, tools, and technologies. 
* You must be a fast and thorough learner, capable of systematically inquiring into new technologies and their foundations.

### Ideally
* 1+ year experience

### Responsibilities
* Databases SQL and NoSQL. 
* Designing and implementing scalable REST APIs. 
* Software architecture, system analysis, design patterns, and unit testing.

### You can bring
* An excellent attitude to getting work done.
* Ability to manage your self and enjoy your work.

### Why it would be awesome to work with us
We will offer ATTRACTIVE benefits:
* 13th month salary
* Social insurance package
* Skill development
* Personalized training program (English + technical + methodological + managerial skills) based on a sharing/mentoring spirit
* Friendly ambiance
* Learn new technologies

### Contact
Via email: phu19677nguyen@gmail.com
Title Job: [VMAX_Position]-Your Full Name
Website: https://www.vmax.vn/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
