### ISSUE TITLE
KVY Tech - Senior Front-end Developer - HCMC or Remote - FT

### ISSUE THREAD

**Issue by HungNguyenKVY** [awesome-jobs/vietnam#1694]
## We need a kickass front-end developer with proficiency with TypeScript, React, Redux and a taste for good UX (and to constantly strive to improve it).

You will get the freedom and trust to work with autonomy from anywhere in the world. The platform we are building will have real impact.

## Location

* Saigon, Vietnam
OR
* Remote

## Desire skills

- Proficient in user interface design and development; JavaScript, HTML, CSS
- Commercial experience with React, Redux and Node.js
- Excellent understanding of UX/UI design principles
- Experience with build tools like Webpack
- Experience with back-end APIs (Ruby on Rails back-end is a plus)
- Experience with Progressive Web Apps, Native development or React Native is a plus
- Commercial experience with TypeScript is a plus

## What you will be doing

- Transforming one of our tools to a mind blowing user experience, with lighting fast interactions
- Innovating and contributing to a platform for auditing, analysing and controlling energy consumption
- Providing technical leadership for a growing team
- Writing clean, well thought out and reliable code
- Participating as a member of a small cross functional team containing members with different skills and experience

### Technologies we use

- Ruby, Javascript, NodeJs, Elixir

- Rails, Spree, Phoenix

- PostgreSQL, MongoDB

- Heroku, AWS, Google Cloud Platform

- Rollbar, NewRelic, Github, Slack, Trello, Jira 

### Perks you Enjoy

- Working & Developing with Passionate & Talented Team
- Internationally remote friendly & out of the box thinking
- Grow your skills in state of the art technologies
- Competitive salary package & performance bonus
- Mon-Fri (9 a.m -6 p.m), flexible and up to 5 remote working days per month
- Company events: year-end party every year, team building, etc.
- Free in-house entertainment facilities (foosball, boardgame…), tea, coffee, juice & snack

### Contact

- Homepage: https://kvytechnology.com
- Email: hung@kvytechnology.com
- Email subject: [Senior Front-end Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
