### ISSUE TITLE
Marketer/ Partnerships Executive

### ISSUE THREAD

**Issue by jianminsim** [awesome-jobs/vietnam#1695]
## Location

* Saigon, Vietnam (Q10, UP Coworking) or Hanoi (negotiable)

## Salary Expectation

* $500/month to $1000/month

## Requirements
* Knowledge of creating online marketing materials, slides, blogs
* Experience in organizing community events is a plus
* Written and spoken english and vietnamese proficiency
* Interest and experience in meeting prospective partners is a plus

### Must Have

* Written and spoken english and vietnamese proficiency

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building relationships with local and overseas partners
* Written and spoken communications/ PR
* Meetings Coordination/ Events Organization
* Online Marketing Materials/ Assets & Maintaining of Weekly Emails/ Mailing Lists

### Why it would be awesome to work with us

* Have opportunities to learn, explore and build a product from scratch and about local vietnam B2B marketplace (VINsme) which is developing more and more popular these days.

* Have opportunities to travel to Singapore and India for business trip when required

* Acquire a variety of technical and soft skills from experienced Software Engineers and Entrepreneurs

* Intensive training & development with the focus on-the-job training and coaching by business managers

* Performance incentives and promotion in role

* Employee of the Month Award with Attractive gifts recognize outstanding contributions.

* Clearly defined long-term career road-map for those who are qualified

* Working in a young, dynamic, friendly, well-equipped environment both with Singaporean and Vietnamese

### Contact
Homepage: https://sourcesage.co
Email: jian.sim@sourcesage.co, hr@sourcesage.co

**Comment by qcam** [comment]
Hey @jianminsim, thanks for posting but we aren’t taking job posts from marketing field currently.

Have a good day.
