### ISSUE TITLE
Nextop - Back-End Developer (Golang) - HN - FT

### ISSUE THREAD

**Issue by huynguyen-11** [awesome-jobs/vietnam#1696]
## Location

* 12Floor, Keangnam Landmark Tower, E6, Me Tri, Quan Tu Liem, Ha Noi

## Salary Expectation

* Up to $1,500/month

## Requirements
* Years of experience required: 2 - 3 years.
* Golang
* Practical experience with Design Patterns, Software Architecture. 
* Extensive experience with Go
* Experience with scripting with Bash, ZSH, etc. 
* A solid understanding of Linux development 

### Responsibilities

Our stack consists of: 
* Microservice architecture. 
* Redis, Blockchain, SQL and key-value storage, Message queue 
* Cloud-based infrastructure following 12 factors using Docker. 
* Go as main language 

### Why it would be awesome to work with us
* Salary: Competitive with lucrative add-ons (based on skills and experience)
* Bonus : Twice a year (equivalent to 2 months salary). Salary Review: 2 times/year based on employee's performance and contribution
* Well-equipped with insurance package as stated by Labor code
* Excellent Overtime compensation policy
* Other benefits as per stated in Vietnamese Labor Law
* Working hours: 9:00 ~ 17:00 (5 days per week)

### Contact
Homepage: https://www.nextop.asia/
Apply now via email: quochuy111nguyen@gmail.com 
Subject: Nextop - Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
