### ISSUE TITLE
Sioux High Tech Software - Senior Reactjs Developer - Da Nang - FT

### ISSUE THREAD

**Issue by baotran0803** [awesome-jobs/vietnam#1697]
## Location

* Da Nang, Vietnam

## Salary 

* $1100 - $2000

## Requirements
* BS in computer science or a related field
* Familiarity with Agile scrum
* A solid understanding of architecture design, security, session management, network diagnostics, network analytics tools and best development practices;

## Skills
* Ability to generate technical proposal, problem diagnosis and creative problem-solving skills
* OOP, Solid, Design Pattern and Relational/NoSQL database systems.

### Must Have
* Proven working experience with ReactJS
* In-depth knowledge of modern technologies: HTML5/CSS3, Bootstrap, jQuery and its plugins, responsive design.
* Experienced in Dev Tools (e.g.: Git/SVN, Gulp, WebPack, Less, Sass).

### Ideally

* Fluent in English (speaking and writing)

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for
* Communicating with project manager and customer to clarify requirements;
* Participating in project’s requirements analysis;
* Understanding the domain knowledge and translate into data models;
* Collaborating with internal & international teams to produce software design and architecture;
* Integrating data from various back-end services and databases;
* Developing documentation throughout the software development life cycle.

### You can bring

* Front-end architecture based on ReactJS best practices;
* Well designed, testable, efficient code by using best software development practices

### Why it would be awesome to work with us
* International working environment;
* Government Social Insurance based on full of Gross salary;
* 13th month salary (and 14th month salary based on performance metrics);
* Monthly lunch allowance;
* 16 leave days and 3 sick leave days per year;
* Premium health card & annual health check;
* Diverse company culture activities: Orange Day, yearly company trip, outdoor activities, etc.

### Contact
Homepage: https://jobs.sioux.asia
Email: jobs@sioux.asia
Skype: baotran0803

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
