### ISSUE TITLE
Chopp - Full-Stack Engineer - HCMC - FT

### ISSUE THREAD

**Issue by constantx** [awesome-jobs/vietnam#170]
# Full-Stack Engineer
## Why you’ll love working with Chopp:

We are an early stage, fully-funded startup that aims to bring world-class customer service and convenience to grocery shopping in Vietnam. Our team is lean with lots of opportunities to grow and learn. If you’re ready to take on a challenging and rewarding role in a dynamic Silicon-Valley-Style team and help shape the future of on-demand service from the ground up, join us!
## Location
- Saigon, Vietnam
## Salary Expectation
- Competitive and negotiable with generous stock / equity
## Skills
- Expertise in JavaScript/Node.js
- Experience in Linux /Unix environment
- Solid understanding of security practices
- Strong experience with developing RESTful web services
- Good knowledge of MongoDB
- Good understanding of native web technologies (HTML, CSS and Javascript)
- Good understanding of MV-Javascript frameworks such as ReactJS, AngularJS, etc
## Must Have
- Writes clean, modular and well-documented code
- A solid understanding of user-centered design principles 
- Careful attention to detail and ability to see the big picture
- Ability to prioritize tasks in a fast-paced environment
- Collaborates and works efficiently with cross functional team
- \- Entrepreneurial spirit and self-motivated
- Proficient English communication skills; speaking and writing
## Ideally
- Familiarity with Git and/or GitHub
- Comfortable with agile development environment
- Team lead experience
- Past startup experience
## You’ll be responsible for
- Our infrastructure, API and native web app.
- Bring happiness to our customers through a world-class product.
## Perks and Benefits
- Startup culture with no BS
- Generous stocks / equity
- 13th month bonus + additional quarterly performance bonuses
- Bi-weekly team happy-hour
- Quarterly off-site trips
- Awesome office in the heart of D1 equipped with expresso machines, kitchen, lounge etc
## Contact
- please send CV or Linkedin to join@chopp.vn

**Comment by joneslee85** [comment]
The job title wrote full stack yet the heading stated backend dev. Can you please amend it for the sake of consistency?

**Comment by joneslee85** [comment]
Please also update the title to conform with our format

**Comment by constantx** [comment]
bump

**Comment by constantx** [comment]
bump

**Comment by constantx** [comment]
@joneslee85 can I close this and repost?

**Comment by constantx** [comment]
What's a good way to renew for visibility?

**Comment by joneslee85** [comment]
@constantx the best way is to close any old post and create a new one. I would renew every 3 months if you have not found a candidate

**Comment by constantx** [comment]
got it, thanks :)
