### ISSUE TITLE
Mini School - Senior Frontend Javascript / React Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by minischoolHR** [awesome-jobs/vietnam#1700]
## Location
* 219 Trung Kính, Yên Hoà, Cầu Giấy, Hà Nội 100000, Vietnam
  (Head office is located in Seoul, South Korea)

## Salary Expectation
* $1,500-$2,500 (negotiable) / month
* Full-time

## Requirements
* 3+ years of experience in Reactjs
  (Javascript and its ecosystem, including ES6, babel, npm, yarn, and webpack is a plus)
* 5+ years of experience in frontend
* Experience in covering from PSD, Sketch to HTML/CSS
* Commercial experience with React, Redux and Node.js
* Excellent understanding of UX/UI design principles
* Experience with build tools like Webpack
* Experience with back-end APIs
* Commercial experience with TypeScript is a plus
* Communicate with Korean teams in English

### Ideally
* Experience in ReactNative
* Experience in NodeJS
* Experience in WebGL
* Experience in WebRTC 

### You’ll be responsible for
* Develop, update and maintain Minischool Platform and Service
* Collaborate with both the Vietnamese team and Korean team
* Maintain and Operate service in Vietnam

### Why it would be awesome to work with us
* Bonus: 13th-month salary and performance bonus
* Provide employees with a working device
* Severance pay following by Vietnamese labor law
* Paid vacation for employee's or his/her family's congratulations or condolences
* Opportunities to travel to other countries for a business trip when required

### What Minischool Service is
* Real-time Interactive Learning Platform using Cartoon Characters
* Book Development Tool on the Web, Smart Editor
* Service Video: www.youtube.com/watch?v=MmTpkPW6YjA

### Contact
* Email: recruit@minischool.co.kr
* Please send me your CV via the email.
* If you have any questions, feel free to ask.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
