### ISSUE TITLE
Mini School - Senior React Native / iOS Developer - Hanoi - FT

### ISSUE THREAD

**Issue by minischoolHR** [awesome-jobs/vietnam#1701]
## Location
* 219 Trung Kính, Yên Hoà, Cầu Giấy, Hà Nội 100000, Vietnam
  (Head office is located in Seoul, South Korea)

## Salary Expectation
* $1,500-$2,500 (negotiable) / month
* Full-time

## Requirements
* 5+ years of Swift/React Native/Redux development experience
* Experience in release App
* Working experience with popular libraries on iOS
* Experience in API design, SDK architecture, and mobile software lifecycle development practices.
* Understand the basic philosophy of React Native and React component lifecycle
* Experience with push notification
* Knowledge of modern authorization mechanisms, such as JSON Web Token is a plus
* Understanding of HTTP, RESTful data structures, and JSON format
* Communicate in English

### Ideally
* Experience in ReactNative
* Experience in NodeJS
* Experience in WebGL
* Experience in WebRTC 

### You’ll be responsible for
* Experience in Cocos2dX/WebRTC

### Why it would be awesome to work with us
* Bonus: 13th-month salary and performance bonus
* Provide employees with a working device
* Severance pay following by Vietnamese labor law
* Paid vacation for employee's or his/her family's congratulations or condolences
* Opportunities to travel to other countries for a business trip when required

### What Minischool Service is
* Real-time Interactive Learning Platform using Cartoon Characters
* Book Development Tool on the Web, Smart Editor
* Service Video: www.youtube.com/watch?v=MmTpkPW6YjA

### Contact
* Email: recruit@minischool.co.kr
* Please send me your CV via the email.
* If you have any questions, feel free to ask.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
