### ISSUE TITLE
KVY Tech - Junior Front-end Developer - HCMC or Remote - FT

### ISSUE THREAD

**Issue by HungNguyenKVY** [awesome-jobs/vietnam#1702]
###We are looking forward to working with passionate people that love to polish their craft, not worried about learning new things and eager to tackle challenges.

By joining the team in the early stage, you’ll get the opportunity to work on many of our various projects with a team of highly skilled software developers who are also the founders of KVY. We are a young and startup-culture development shop where you can sharpen your technical skills and other soft-skills as well. Because you will be involved in every step of the project, not only about coding but also about communicating and working directly with customers.

## Location

* Saigon, Vietnam
or
* Remote

## Salary Expectation

Negotiable

## Desire skills

- Have solid experience using JavaScript, HTML, CSS, with a major frontend framework (ReactJs, Vue.js, Angular or similar)
- Have knowledge of UX/UI design principles
- Experience with build tools like Webpack
- Understanding of API structures, REST concepts as well as JSON data structures
- Experience with back-end APIs (Ruby on Rails back-end is a plus)
- Experience with TypeScript is a plus
- Fairly good at English speaking

## What you will be doing

- Transforming one of our tools to a mind-blowing user experience, with lighting fast interactions
- Working directly with clients to well capture their expectations, requirements, and feedbacks
- Involving in the process of building a software product from A to Z: from ideation to execution and product-market fit with feedbacks from end-users
- Collaborating with back-end developers and designers to bring the concept to life
- Participating as a member of a small cross functional team containing members with different skills and experience

### Technologies we use

- Ruby, Javascript, NodeJs, Elixir
- Rails, Spree, Phoenix
- PostgreSQL, MongoDB
- Heroku, AWS, Google Cloud Platform
- Rollbar, NewRelic, Github, Slack, Trello, Jira

### Perks you Enjoy

- Working & Developing with Passionate & Talented Team
- Internationally remote friendly & out of the box thinking
- Grow your skills in state of the art technologies
- Competitive salary package & performance bonus
- Mon-Fri (9 a.m -6 p.m), flexible and up to 5 remote working days per month
- Company events: year-end party every year, team building, etc.
- Free in-house entertainment facilities (foosball, boardgame…), tea, coffee, juice & snack

### Contact us

- Hung Nguyen, Business Development Manager
- Email: hung@kvytechnology.com
- Phone: +84 372684398
- Email subject: [Junior Frontend Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
