### ISSUE TITLE
INCOGNITO (blockchain startup) - 1 Backend Engineer Golang - Saigon - FT

### ISSUE THREAD

**Issue by May-chan** [awesome-jobs/vietnam#1709]
## Location

* 139 Hong Ha, Phu Nhuan, Saigon, Vietnam

## Salary Expectation

* $1,500 - $2,200
* Fulltime

## Projects: My Constant
**What is Incognito?**
[Incognito](https://incognito.org) is building the privacy layer for the decentralized web.  Store, send and receive all your crypto assets — like BTC, ETH, and USDT — with total privacy.  Know that no one can see your balances or track your activity.  You can even mint your own privacy token.

**Our story**
Every idea starts with a problem.  Ours was simple: blockchain data is public.  

Duy was running Autonomous where he paid a team of 100+ people in 6 different countries with an ERC20 stablecoin.  While he saved processing time and money on international wire fees, employee salaries were exposed publicly on the Ethereum blockchain. It was a mess.  

Many of the team had similar experiences, frustrated at how hard it was to send, receive and store crypto privately, even in a rapidly tokenizing world.  No one wants to show their bank statements to the entire world.

We started Incognito to create an alternative – the choice of privacy whenever needed, simple for anyone to obtain. Incognito mode for blockchains.

As of August 2019, the project has in total [12,000+ commits](https://github.com/incognitochain?tab=repositories) and 1M+ lines of code.  It’s on the [Testnet](https://test-explorer.incognito.org/) now.  The Mainnet is scheduled to go live in October 2019.

## The Job: Backend Engineer Golang
Join the 50+ talented developers at Incognito to builds blockchain powered financial tools for a connected world. 

It is OK if you do not have experience with blockchain yet.  As long as you have strong background in other backend languages/frameworks and have the desire to build decentralized applications, you will have the opportunity to learn blockchain technologies on the job.

## Requirements
* At least 3 year experience in backend development with Golang
* Expert in Databases SQL & NoSQL (level DB is a plus)
* Expert in designing and implementing scalable REST APIs.
* Experience in Software architecture, system analysis, design patterns, and unit testing.
* Good understanding of the software development process.
* Experience in DevOps and web security is a plus.
* Good understanding of blockchain core BTC or any others is a plus
* Familiar with multi thread.
* Good communications skills.
* Always be curious. Always learning.
* Can work independently and in a dynamic team environment

## Ideally

* Excellent verbal and written communication in English
* Teamwork, flexibility, initiative, communication, and organization
* Play soccer

### You can bring

* A passionate & dynamic mind
* A risk taker, a dreamer
* A willing-to-learn person

### Team Culture Requirements

* Willingness to constantly learn new programming languages, tools, and technologies.
* You must be a fast and thorough learner, capable of systematically inquiring into new technologies and their foundations. Think and rethink, from the ground up.
* Able to constantly challenge yourself to stay on top of your game and upgrade yourself every day.

### Bonus Points (Not Required)
* Contribution to open-source projects.
* Excellent verbal and written communication in English.
* Teamwork, flexibility, initiative, communication, and organization.
* Play soccer.

### Why it would be awesome to work with us
* You be you.  We deeply care about helping everyone at Incognito work on what they love, freely express their ideas within the organization, and grow to to their true potential.
* You be a better you.  Most of the time, you’ll be working on cutting edge technologies.  You’ll be constantly learning and improving your knowledge as an engineer, researcher or scientist.
* You are your own boss.  There is very little hierarchy at Incognito.  Decision making processes are transparent and open to vote. We welcome all different ways of thinking and trust the people we work with to do what they do best. There is no micromanagement here.
* You the inventor.  Most of the time, you’ll find yourself working on a problem that doesn’t have a solution - yet. That’s where you come in.
* Solve problems for the world, not just Vietnam. Most of the problems we’re solving are for the global audience of today, and of tomorrow.
* Open source culture. We open source all of our projects on Github.

### The essentials
* Above-market salary and bonuses
* 13th month salary
* Premium healthcare package for you and your family
* Standing desk, ergonomic chair
* Computers of your choice (Macbook Pro or Linux)
* Healthy lunch
* Gym, yoga, zumba classes throughout the week.  We play soccer every Friday!
* Company retreat & quarterly team retreat
* Travel internationally to conferences and tradeshows as needed

### Contact
Email: hoa@incognito.org
Phone: 02862690290

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
