### ISSUE TITLE
Fram^ - Senior full-stack engineer (Python, AngularJS) - HCMC - FT

### ISSUE THREAD

**Issue by framcompany** [awesome-jobs/vietnam#171]
**About us:**
Fram - the Swedish software Company helps Scandinavian and Northern European companies leverage the talent and power of Vietnamese rock star developers and other online industry talent. Fram is a very different company. First of all, our culture is different – we believe that to write world class code you need to work in an environment that energizes you and with colleagues that inspire and challenge you. Hence, we sit in a special designed, Scandinavian office on Nguyen Cong Tru in central Ho Chi Minh City. We only work with Scandinavia’s top online employers and we only hire Vietnam’s top 2% developers and internet industry talent.

**Location**
22nd Floor, TNR Tower, 180-192 Nguyen Cong Tru, Dist.1, Vietnam

**Salary Expectation**
**Up to USD 2,300**

Fram^ is now looking for **Senior full-stack engineer** to be part of engineer team that own the complete development process and the infrastructure **for digital textbooks project**.

You are a software engineer who likes get things done, and do them well. You are pragmatic, like when things are moving fast and having fun while at it. You appreciate smart, dedicated colleagues that truly care about you, and about the product and the technical solutions. You know the value of simplicity, and you believe in code reviews and Continuous Integration.

**Requirement Technical skills:**
- Full stack web development experience
- Python/Django or Ruby/Rails or similar
- RESTful API’s
- HTML5
- Javascript; AngularJS / React
- CSS + SASS + Responsiveness
- Good English
- Can-do-attitude and put the goals of the team before your own prestige
- You are able and hungry to take on a lot of responsibility

Nice to have
- AMQP/Celery/RabbitMQ
- TDD/CI/Selenium, Testing strategies
- Experience of UX, graphical frameworks
- Grunt/Gulp or similar tools
- Jasmine/Karma testing
- Working with AWS, CDN etc

**Benefits:**
More on Fram – what is it like to work in Fram?

We are passionate individuals driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals with a desire to build something new and actively support our young company in its growth to greatness.

**You will love working here!**
- Excellent and competitive salary package (up to $2,300 gross for talented candidates), with up to 02 months salary bonus based on your performance and contribution.
- 5-day working week (Monday-Friday), working hours to some extent flexible
- Professional and open working environment, with the culture and office of a Scandinavian online company, on Nguyen Cong Tru in central Ho Chi Minh City
- More annual leaves than Vietnam’s Labor Law (Swedish national day and Christmas Eve).
- Opportunities to improve English skills within an international team – English is official language in fram^ office. Also regular English lessons two times per week by native English teachers in the office
- Opportunities to gain hands-on experience in cutting-edge technologies
- Opportunities to become one of key member of fram^ as we build this fast growing company together!

**Contact**

For application or asking for further information, kindly contact back to:

Ms. Lan Anh, Talent Manager, HR Department
Email: ttla@framco.se
Skype: mary.trananh
Website: http://framco.se/

**Comment by nnti3n** [comment]
My email couldn't reach ttla@framco.se
