### ISSUE TITLE
Employment Hero - Junior Backend Engineer - Saigon -Up to $2000 - FT

### ISSUE THREAD

**Issue by nguyenquangminh0711** [awesome-jobs/vietnam#1712]
## Location
Cach Mang Thang 8, Viettel Complex Building, District 10, Ho Chi Minh

## Salary Expectation

* $1000-$2000 USD/month 💵 💵 💵

## Who are we

There is a massive amount of challenges waiting for you to solve at Employment Hero. Employment Hero is a young and fast-growing startup company based in Australia. We are ambitioned to change the way companies are handling employment and improve employee happiness significantly. Aiming for that lifetime goal, we provide a platform to manage HR, payroll, and employee benefits all in one place. The whole engineering team is working hard to improve the platform in terms of resiliency and efficiency to create as much reliable as possible environment for our beloved customers.

As a member of a product team, you'll work closely with product owners, designers, and other engineers in other stacks to solve customer pain points. As a member of the backend team, you'll be responsible for system architecture, and writing codes. Oh hey, we have been aiming for high technical standards: 

* Your architecture must be well-designed and thoughtful. Our system is complicated, but modern, and require a high level of architecture design to ensure hundreds of engineers can work together with confidence, and hundred of features are delivered at the highest quality.
* Your code must be elegant, clean, and fast.
* Your deployment must pass a series of automatic tests and metrical checks.
* Our observability system and bot army help you responsible for any bugs, data integrity, and performance issues after.

Achieving all of them is hard, but don't worry, we create an excellent environment for you to learn and grow. Moreover, as a part of the engineering team, you may join in building the technical foundations and leadership to help others grow. 

## You'll need to
* Enjoy being a generalist and a problem solver to solve issues for delight users, both internally and externally.
* You are a lifelong and fast learner. You are continually teaching yourself new things, and you love learning from others.
* Always seek for long-term solutions; you'll need to assess system-wide impacts that ensure the product evolves in the right way.
* Be proficient in at least one programming language, relational databases, object-oriented programming, and other stuff in backend stacks.
* Have good communication skills, in both Vietnamese and English.

## It would be great if you have
* Experience with Ruby programming language.
* Experience with microservice architecture, Kubernetes, and Amazon AWS.
* History of collaboration with teammates, mentorship, or technical leadership

## Why it would be awesome to work with us
* Numerous rooms for you to grow, aka a vast amount of problems for you to solve.
* Competitive compensation package. We pay what you deserve, regardless of your years of experience.
* Work in an open-minded, friendly, positive, transparent, and flexible environment.
* Huge self-growing budget, sponsorships for books, conferences, etc.
* 20 days off annually
* A latest Macbook Pro.

## Contact
Homepage: https://employmenthero.com
Contact: minh.nguyen@employmenthero.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
