### ISSUE TITLE
Saigon Technology Solutions - Frontend Engineer (Angular) - HCM/Da Nang - FT

### ISSUE THREAD

**Issue by vub** [awesome-jobs/vietnam#1713]
## Location

* Sai Gon/Da Nang

## Salary Expectation

*  Upto $1800

## Requirements
* Experience in Angular 5+
* Have good knowledge or experience in front-end technologies, such as HTML5, and CSS3
* Experience with GIT source control, Agile process
* Must be good at English communication

### You’ll be responsible for

* Develop UI Elements to integrate with server side logic
* Work with customer to clarify requirements
* Solve technical problems
* Support teammates to solve problems

### Why it would be awesome to work with us

Saigon Technology Solutions is a Vietnam software development company focused on delivering the best and most cost-effective solutions to our clients in areas such as e-finance, e-business, healthcare, and media. Combining proven expertise in technology, and domain expertise, we deliver a range of software outsourcing services that includes Custom Application Development/ Software Outsourcing Services, Offshore Software Development, Web Application Development, Mobile Application Development. Saigon Technology has very strong expertise in Java, .NET, PHP and Mobile application programming.

### Benefits include:

* **13th Salary**
* **Bonus Project**
* **PVI Healthcare** Program
* Free **English Class** every week
* Performance and **salary review** every **6 months**
* **Company trip** every year
* **Happy hour** every Friday and **happy birthday party** monthly
* Enjoy Relax and Beauty Pantry in the company
* Team building events and much more

### Contact
Homepage: saigontechnology.com
Drop your CV to vu.bui@saigontechnology.com and we will be in touch with you shortly!

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
