### ISSUE TITLE
Cinnamon AI - Project Manager - HN/HCMC - FT

### ISSUE THREAD

**Issue by giangnguyen2710** [awesome-jobs/vietnam#1714]
## Location

* Hanoi, Vietnam
* Ho Chi Minh, Vietnam

## Salary Expectation

* Up to $2000/month

## Requirements
● Ensure transparent communication among internal stakeholders, Japanese sales team and delivery team.
● Ensure resource availability and allocation. Facilitate and coordinate internal resources for the flawless execution of projects.
● Develop or update project plans for information technology projects including information such as project objectives, technologies, systems, information specifications, schedules and staffing.
● Monitor or track project milestones and deliverables.
● Assign duties, responsibilities, and spans of authority to project personnel.
● Schedule and facilitate meetings related to information technology projects.
● Measure project performance using appropriate systems, tools and techniques.
● Prepare project status reports by collecting, analyzing, and summarizing information and trends.
● Conduct analysis, report current situation, issues and risks, and propose necessary changes to the stakeholders.
● Create and maintain comprehensive project documentation.

### Must Have

● Strong in negotiation, communication skills, complex problem solving, problem sensitivity, time management, management of personnel resources.
● Attention to detail and multi-tasking skills
● Strong verbal and written expression
● Communicable English (speaking, listening &amp; reading) and Business-professional English (document writing).
● Minimum 3 years of working experience in project management (especially in defining requirements by understating business needs).
● Experience in software development with Scrum and Kanban.
● Understanding all aspects of the software life cycle, using Agile or Waterfall software development practices.
● Experience in handling multiple projects at the same period of time.
● Experience with modern project management tools.
● Experience in making proposals and defining requirements about systems, especially for open system.
● PMP certification is a plus (not a must)

### Why it would be awesome to work with us

● Attractive compensation and benefits.
● Employee centric culture and a belief that we should hire those who are good at what they do and then give them the tools they need to achieve success, further their expertise and grow their career.
● A commitment to learning and growth and easy ways to achieve both including a training budget, education assistance, mentorship programs and collaborative learning sessions.
● A collaborative environment that fosters communication via slack and an open-door policy.

### Contact
Homepage: www.cinnamon.is
Email: talent@cinnamon.is (0899 866 003)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
