### ISSUE TITLE
PowerGate Software - Ruby on Rails Developers - Hanoi - Up to 1500$

### ISSUE THREAD

**Issue by anhia** [awesome-jobs/vietnam#1715]
## Location
* Ha Noi, Vietnam
* Fulltime

## Salary Expectation
Competitive & Negotiable, depends on how experienced you are. At least $1000+ monthly.

## Requirements
* Have at least 2-3 years of relevant professional experience
* Experience with Ruby on Rails, along with other common libraries such as RSpec and Resque, Sikekiq
* Good understanding of the syntax of Ruby and its nuances
* Familiarity with concepts of MVC, Mocking, ORM, and RESTful
* A knack for writing clean, readable Ruby code
* Good English is a plus
* Willingness to learn new technologies both by training and self-learning

### Why it would be awesome to work with us
Attractive salary, based on skills and experience.
Salary from 1000$- 1500$
Have opportunities to communicate and work directly with US or UK Customers
Vacation days, social assurance and medical assurance according to the Labor Law
Working time: 5days/ week (From Monday – Friday)

### Contact
Email: hr@powergatesoftware.com
Website: https://powergatesoftware.com/
Add: 2nd floor, Trung Yen Plaza, No 1 Trung Hoa, Cau Giay Dist, Ha Noi, Vietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
