### ISSUE TITLE
Kyber Network (Blockchain) - Applied Cryptography Researcher - HCMC - FT

### ISSUE THREAD

**Issue by thanhdtp** [awesome-jobs/vietnam#1716]
## Location

* HCMC, Vietnam

## Salary

* Competitive
* Negotiable

## The Job

One-liner: Design and implementation of protocols based on public blockchains to achieve privacy based on cutting-edge applied cryptography research.

At [Kyber Network](https://kyber.network) we are adding privacy layer to decentralized trading on public blockchains with Zero-Knowledge Proofs (ZKP) and other applied cryptography protocols. The main goal is to enable privacy in secure and decentralized trading for cryptocurrencies and other assets on public blockchains.

## Why it would be awesome to work with us

* Challenging, first-of-its-kind tasks with a lot of responsibility and autonomy
* Instant deployment and usage by a global market
* Very competitive compensation
* Friendly work environment and world-class team
* Options to work in Ho Chi Minh and Singapore.

### Must have

* Strong background in applied cryptography / information security
* Experience designing and evaluating cryptographic protocols
* Interest in Zero-Knowledge Proofs (SNARKs, STARKs, Bulletproofs, etc.)
* Eager to learn, ownership mindset and a proven track record of applied cryptography research.

### Cool to have

* Excellent English comprehension and communication skills

## About Kyber Network

Kyber Network is an IT startup entity headquartered in Singapore with two Development centers in Israel and Vietnam. We are young, innovative and ambitious to fulfill our dream mission: creating a top convenient and secure platform for international payment based on blockchain technology. The current products are [Kyber Network Protocol](https://kyber.network/) and [KyberSwap exchange](https://kyberswap.com).

Our Kyber Network project attracted great attention from cryptocurrencies community when raising USD 52 million from our September 2017 token sale, leading us into the World Top 10 ICO Startups ever. We has a list of top-notch investors, partnerships and advisors (one of those is Vitalik Buterin, the Founder of Ethereum). Our Co-founders, Dr. Loi Luu and Mr. Victor Tran, are honored in the 2017 Forbes Asia 30 under 30 list in Finance and Venture Capital. Dr. Loi Luu is widely known as the only Vietnamese PhD holder majoring in blockchain securities so far.

With that great mission in mind, our team needs the most ambitious experts in their field and commits to support them to the fullest. Let’s join Kyber Network and work with the best for the best!

## Contact
Apply to email: hr@kyber.network
Or via link: http://bit.ly/KyberJobApplication
Homepage: https://kyber.network
Facebook page: https://www.facebook.com/KyberVietnam/
Skype/Telegram: @thanhdtp

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
