### ISSUE TITLE
SNAP innovations Pte Ltd - Back-End Developer (PHP/Python) - HCM - FT

### ISSUE THREAD

**Issue by lamhoang-nhatphuong** [awesome-jobs/vietnam#1717]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1000 - $2000/month

## Requirements

* At least 2+ years experience in PHP. Or At least form six months to 01 years experience  in Python
* Good to have have experience with many different programming languages (Python, PHP, Django, JavaScript ....) 
* Good experience with writing SQL scripts
* Have knowledge and experience of Front-end  is a plus
* Using professional software development systems like Jira and Git
* Ability to work in short, agile, iterative development cycles
* Solution-oriented and a quick learner, logic skills
* Be able to communication in English (written and spoken). Chat with your boss who is Singapore

### Responsibilities

* Research new features, analyze requirements, estimate implementation, design software, code reviews, and document solutions
* Develop and maintain products written in Python / PHP
* Prepare unit tests, participate in quality assurance of the Software deliveries
* Participate in development and maintenance of platform test automation suites
* Make sure that applications are continuously delivered with requested level of quality

### Why it would be awesome to work with us

* 13th Salary, Salary Review (2 time / year), Bonus Project
* The wage agreements in interview
* Able to work in an active and professional working environment
* Company Trip
* Weekly Office Party
* Time working: 09:00 AM - 06:00 PM from Monday to Friday.

### Interesting engineering projects

Snap is a technology company focusing on areas of Artificial Intelligence, Fintech and Blockchain. We aim to be always at the forefront of technologies and seek to break new grounds all the time.
Established in 2011 based on the early research work in Snap Decision Making Model, we extended our work on AI to various areas of Fintech and Blockchain. In terms of coverage, we expand from our head office in Singapore to many international offices.

### Contact
Send CV via mail: nhatphuong.lamhoang@gmail.com
Subject: [SNAP - Position - Your Name]
Website: http://www.snapinnovations.com/

**Comment by lamhoang-nhatphuong** [comment]
.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
