### ISSUE TITLE
Coinhouse - Senior Rails Engineer - Paris, France - FT

### ISSUE THREAD

**Issue by surzycki** [awesome-jobs/vietnam#1721]
## Location

* Paris, France
* In Paris with visa sponsorship

## Salary Expectation

* $3750/month - $5000/month

## Requirements
* Ruby on Rails
* Github
* Coffee (the drink)
* 5+ years Software Engineering experience

### Must Have

* The ability to know good code from bad code
* Highly developed ~spidey~ code-sense for smelling code smells
* The desire to do great things

### Ideally

* Experience with AWS, Docker, and other devOps-sey kind of things
* A love for Object Oriented design
* If SOLID was a religion you might be a preacher. 

### Responsibilities

* Helping to scale the platform and build out new features
* Interfacing with various blockchains to build out custom monitoring tools
* Contributing to the growth of the company, develop new skills
* Advance and strengthen the design and architecture of the core platform
* Not taking yourself too seriously, life is meant to be enjoyed
* Take ownership over projects, timelines and deliverables

### You can bring

Writing code is an art-form and we are looking for those special, talented and motivated engineers who can hit the ground running. Building things is hard and it takes the right people working together skillfully to get things done.  As an engineer at Coinhouse.com, you will be building the tools today that will redefine tomorrow's currency markets. Technology is at the core of our business.

### Why it would be awesome to work with us

* Paris is kind of neat
* The French like vacation (30+ days a year), all work and no play makes Jack a dull boy. 
* We have a great engineering team recruited from around the world 
* We love code, and making it beautiful. 

### Interesting engineering projects

* Advance data modeling for trading
* Contribution to open source community / projects
* Smart Contracts
* Functional / stateless programming

### Contact
Homepage:  [Coinhouse](https://www.coinhouse.com)
Apply: [Apply at Coinhouse](https://lmdb.welcomekit.co/jobs/senior-backend-engineer-core-platform-ruby-on-rails_paris)
Email: stefan_dot_surzycki_at_coinhouse_dot_com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
