### ISSUE TITLE
BAP Solutions - Blockchain Team Leader - HCM

### ISSUE THREAD

**Issue by Nhunie** [awesome-jobs/vietnam#1725]
## Location

* [Viettel Complex Building 285 CMT8 St, W12, D10, HCMC, Vietnam](https://www.google.com/maps/place/Viettel+Complex+Building/@10.7780386,106.6781763,17z/data=!3m1!4b1!4m5!3m4!1s0x31752f2639b32e09:0x97169d1fc37df0b6!8m2!3d10.7780386!4d106.680365)
* Full-time
* From Monday to Friday

## Salary Expectation

* Up to $3,000/month

### You’ll be responsible for
* Leading a blockchain team.
* Develop smart contracts to enrich apps ecosystem on blockchain
* Participate in design, development and implementation of blockchain solutions.
* Research on latest blockchain solutions in the industry.
* Research and implement best practices to secure blockchain private keys.

## Skills
* 3+ years Senior Blockchain Engineer experience
* Experience working with Blockchain development in a professional environment including Bitcoin, Ethereum, Hyperledger
* Solid understanding of Web Technologies: HTTP, AJAX, RESTful API/GraphQL
* Working knowledge integrating 3rd party API’s, libraries, and frameworks.
* Experience architecting and building cloud solutions on AWS is a plus.
* Experience with different blockchain smart contract platforms is a plus.

### We will offer ATTRACTIVE benefits:
* 13th-month salary
* Social insurance package.
* Total health care benefits for you.
* Computers of your choice (Macbook Pro or Window).

### Contact
Homepage: https://bap-solutions.com/ 
Email : nhungnn@bap-solutions.com
Phone/ Zalo: 0783465773

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
