### ISSUE TITLE
KVY Tech - Fullstack Developer - HCMC - FT

### ISSUE THREAD

**Issue by HungNguyenKVY** [awesome-jobs/vietnam#1726]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

### Desire skills
* 2+ years of experience
* Architect and build product features end to end in Ruby on Rails or Javascript (ES6)
* Have knowledge of UX/UI design principles
* Experience with build tools like Webpack
* Understanding of API structures, REST concepts as well as JSON data structures
* Experience with back-end APIs
* Experience with NodeJS, TypeScript or React is a plus
* Fairly good at English speaking

### What you will be doing
* Transforming one of our tools to a mind-blowing user experience, with lighting fast interactions
* Working directly with our team to develop our in-house product
* Involving in the process of building a software product from A to Z: from ideation to execution and product-market fit with feedbacks from end-users
* Collaborating with back-end developers and designers to bring the concept to life
* Participating as a member of a small cross functional team containing members with different skills and experience

### Technologies we use
* Ruby, Javascript, NodeJs, Elixir
* Rails, Spree, Phoenix
* PostgreSQL, MongoDB
* Heroku, AWS, Google Cloud Platform
* Rollbar, NewRelic, Github, Slack, Trello, Jira

### Perks you Enjoy
* Working & Developing with Passionate & Talented Team
* Internationally remote friendly & out of the box thinking
* Grow your skills in state of the art technologies
* Competitive salary package & performance bonus
* Mon-Fri (9 a.m -6 p.m), flexible and up to 5 remote working days per month
* Company events: year-end party every year, team building, etc.
* Free in-house entertainment facilities (foosball, boardgame…), tea, coffee, juice & snack

### Contact us
* Hung Nguyen, Business Development Manager
* Email: hung@kvytechnology.com
* Phone: +84 372684398
* Email subject: [Fullstack Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by tuanngocptn** [comment]
Hello 
Is this job still available?
Thanks.
