### ISSUE TITLE
Lecle Vietnam - Junior QA Engineer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#1729]
## Location

* Saigon, Vietnam
* District 1

## Salary Expectation

* Negotiation

## Requirements
* 1 - 2 years of experience
* Experience in writing clear test plans and test cases
* Attention to detail
* Analytical mind and problem-solving aptitude
* Quick learner and proven problem-solving ability.
* Good communication skill.

### Responsibilities

* JD: https://smrtr.io/3tL9M

## Contact
* Phone: 028-5416-5548
* Send your CV to email: career@lecle.co.kr
### Know more about us
Facebook: www.facebook.com/LecleVietnam
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
