### ISSUE TITLE
Woowa Brothers - Back-End Developer (NodeJS) - HCMC - FT

### ISSUE THREAD

**Issue by dattran105** [awesome-jobs/vietnam#1730]
## Location

* 22nd Floor, Etown Central Building, 11 Doan Van Bo, Ward 12, District 4, HCMC

## Salary Expectation
* Negotiable

## Requirements
* JavaScript 
* TypeScript, Node.js, MongoDB, Redis, AWS.
* 1+ years of coding experience in JavaScript or TypeScript.

## Skills

* 3+ years of server-side software engineering experience.
* A degree in Computer Science, Software Engineering or experiences in related fields. (IT, Software).
* Knowledge and experiences in NoSQL (e.g. MongoDB).
* Knowledge and experiences in cloud base infrastructure (e.g. AWS, GCP).

### Responsibilities

* Develop and provide API for BAEMIN service.
* Collaborating with the front-end developers and other team members to establish objectives and design more functional, cohesive codes to enhance the user experience.
* Analyze and improve efficiency, scalability, and stability of our system.

### Why it would be awesome to work with us

* Meal allowance
* Full employee benefit system according to the law & company regulation
* Health check and company trip
* Year-end bonus, public holiday bonus, birthday bonus
* Opportunity to be trained & worked in a leading e-commerce company in Vietnam
* Appraisal and salary review every year
* Working time: 5 days/week, 9 am – 5:30 pm

### Interesting engineering projects
* Baemin is a food tech startup in Vietnam. We are invested by Woowa Brothers, Korea's number 1 food delivery unicorn

### Contact
Website: www.woowahan.com
Apply now: trandat.1005@gmail.com 
Subjects: Back-End Developer (NodeJS)_Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
