### ISSUE TITLE
Yojee - Product Manager - HCMC - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1731]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000-2000 USD/month or negotiable

## Requirements
* Bachelor Degree in Computer Science or related technical field preferred.
* 3-6 years of working experience; 1 year or more of product management experience preferred
* Strong communication skills and ability to understand perspectives of different users and prioritize needs
* Analytical problem-solver, detail-oriented and self-driven
* Fast-learner, comfortable in leading independently without much supervision in a fast-paced environment
* Domain knowledge of our market
* Some experience in quality assurance and continuous improvement processes

## You’ll be responsible for

* Lead and oversee one or more products in Yojee.
* Lead the strategy and development of products, and oversee their lifecycle from ideation to release, and the ongoing developments and improvements.
* Identify and fill product gaps and generate new ideas, improve customer experience and drive growth.
* Scope and prioritize activities based on business and customer impact.
* Translate product strategies into detailed requirements and prototypes.
* Coordinate, schedule and work closely with engineering teams and executives to serve the needs of the business and to optimize the utilization of development resources.
* Perform and handle other ad-hoc duties as required.

## Why it would be awesome to work with us
We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.
* Company stock
* Provided Macbook 
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### Contact
Homepage: https://yojee.com/
Lily : lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
