### ISSUE TITLE
FETCH Tech - dotNET Developer - Saigon - FT

### ISSUE THREAD

**Issue by laciefetch** [awesome-jobs/vietnam#1732]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Saigon, Vietnam
* FT

## Salary Expectation

* Up-to $2000 USD/month

## Requirements

* At least 4 years experience in C# and .NET Technologies. (1 or 2 years for Junior).
* Proficient in .NET Core and OOP framework and architectures..
* Experience in NoSQL solutions such as MongoDB
* DevOps.
* HTML, CSS, Javascript. React preferred.
* Good understanding in CQRS & Clean Architecture.

### Responsibilities

* We are looking for passionate technical evangelist to help transform our currently technical landscape. You will assist in implementing the latest .Net Core technology along with best practices and architectures.
* You will also be participating in experimenting and adopting new framework from time to time.
* If you are someone who love to continually improve and takes pride in your code. This is definitely for you.

### Why it would be awesome to work with us

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Fanpage: Fetch Vietnam
Skype: lacie.soul12
Mail: lacie@fetch.tech

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
