### ISSUE TITLE
FETCH Technology - Ruby On Rails Developer - HCMC - FT

### ISSUE THREAD

**Issue by luudanggiahan** [awesome-jobs/vietnam#1733]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Ho Chi Minh city

## Salary Expectation

* $1000 - 2000/month or negotiable
## Requirements

* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information 
* Technology or related disciplines.
* Minimum 2 years of experience in any of the followings: Ruby on Rails, Golang.
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Familiar with linux system administration and provisioning systems using Amazon Web Services.
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Enjoys challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over communicating, language barriers aside, you must be willing to make an effort to communicate as much as).
* Overthink security.
* Can communicate well in English.

### Ideally

* Able to code in multiple languages - Java, Scala, Golang, Ruby. 

### Responsibilities

* Full-stack developer to maintain and develop online services.
* Work closely with product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web and applications.
* Participate in user testing on production.

### Why it would be awesome to work with us
* Attractive salary and allowances.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Email: haleyluu@fetch.tech
Skype: luudanggiahan

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
