### ISSUE TITLE
[Fetch Technology] - [React Native Developer] - [Ho Chi Minh City] - [FT]

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#1734]
## Location

* 3rd Floor, 194 Golden Building - 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, Ho Chi Minh City. 

## Salary Expectation

* upto $2000/month
## Requirements
* 4+ years of experience working in Software Development. 
* 2+ years working with React Native.
* Experience working with Redux, Redux Saga, Native iOS, Native Android, APIs. 
* Familiar with mobile application terminologies and patterns, especially React Native libraries such as React Navigation. 
* Familiar with Git.
* Ability to take lead and ownership on design, implement, fix bugs and deliver new features. 
* Ability to quickly learn and adapt to new technologies and workflows. 
* Resourcefulness and commitment to do what is needed to get the job done. 

### Ideally

* Experience publishing applications on App Store and Google Play Store. 
* Experience with Typescript.
* Experience with Mobile CI/CD in Gitlab.

### You’ll be responsible for

* Can create performant, customized and adaptive UI. 
* Handle interactions in a fluid and elegant manner. 
* Write stateful code in a maintainable and readable way. 
* Are familiar with the native build system and how to configure and deploy applications for release. 
* Are focused on shipping product and are able to deliver features independently. 
* Work well in a cross functional team. 

### Why it would be awesome to work with us
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* Full 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).
* Working Device: Mac Pro 2019

### Contact
Fanpage: Fetch Vietnam
Mail: vynguyen@fetch.tech
Skype: vynht.hrm
Phone: 0854 645 045

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
