### ISSUE TITLE
[BAP Solutions] Senior Blockchain

### ISSUE THREAD

**Issue by Nhunie** [awesome-jobs/vietnam#1735]
## Location

* Saigon, Vietnam
*  [Viettel Complex Building 285 CMT8 St, W12, D10, HCMC](https://www.google.com/maps/place/Viettel+Complex+Building/@10.7780439,106.6781763,17z/data=!3m1!4b1!4m5!3m4!1s0x31752f2639b32e09:0x97169d1fc37df0b6!8m2!3d10.7780386!4d106.680365)

## Salary Expectation
* $3000/month 

## This exciting position
* Participate in design, development and implementation of blockchain solutions.
* Research on latest blockchain solutions in the industry.
* Research and implement best practices to secure blockchain private keys.
* Build distributed nodes leveraging cloud micro services.
* Develop smart contracts to enrich apps ecosystem on blockchain
* Leading a blockchain team.

## Background
* **Have over 3 years** of experiences working with Blockchain development
* Experience working with Blockchain development in a professional environment including * **Bitcoin, Ethereum, Ripple, Hyperledger**
* Solid understanding of Web Technologies: **HTTP, AJAX, RESTful API/GraphQL**
* Working knowledge integrating 3rd party API’s, libraries, and frameworks.
* Experience architecting and building cloud solutions on **AWS** is a plus.
*Experience with different **blockchain smart contract platforms** is a plus.

## Why it would be awesome to work with us
* **Attractive salary up to $ 3,000** 
* 13th-month full salary
* Social insurance full package
* Computers of your choice (Macbook Pro or Window)
* International environment with colleagues from different countries (Vietnam, US, Japan, Australia, Malaysia,...)
* Opportunity to work with revolutionary blockchain technology

### Contact
Homepage: https://bap-solutions.com/ 
Skype: _**nhungnn.hip**_
Mail: nhungnn@bap-solutions.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
