### ISSUE TITLE
Data Engineer - HCMC - Quod AI

### ISSUE THREAD

**Issue by hroussel** [awesome-jobs/vietnam#1738]
## Location

* HCMC

## Salary Expectation

* $2000-$3000/month 

## Requirements
* Java
* 2+ years Software Engineering experience

### Must Have

* Outstanding programming skills
* Expert in Java
* Solid foundations with SQL and databases

### Ideally

* Experience with ETL or data pipelines a plus
* Experience with parser/crawlers a plus
* Experience with NLP a plus

### Responsibilities

* Design and implement a system that can handle 1 billion lines of code or 2 terabytes of streaming data 

### You can bring

* Ability to learn quickly
* Ability to get things done

### Why it would be awesome to work with us

What if every software engineer could hold 1 billion lines of code in their head? 
How would it change the way we build software? 
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create the first AI assistant for software engineering team. Our first product translates raw source code into natural language to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

<img src="http://bit.ly/quod-ai-photo-team" alt="Team" width="300" />

Our team has ex Silicon Valley engineers and award winning AI researchers from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.

<img src="http://bit.ly/quod-ai-logo-schools" height="40" />

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

<img src="http://bit.ly/quod-ai-logo-investors" height="40" />

### Contact
Homepage: quod.ai

**==> Click [here](http://bit.ly/2OL3YtA) to apply <==**

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
