### ISSUE TITLE
Acuity - Junior/Mid-level Full Stack Software Engineer (Elixir) - Onsite/Remote - FT

### ISSUE THREAD

**Issue by acuityengineers** [awesome-jobs/vietnam#1739]
## Location

* HCMC, Vietnam
* Remote

## Salary Expectation

* `>=` 3000+ SGD

## Requirements

* Design and build reliable trading software platform primarily in Elixir and Javascript
* Maintain clean and human-readable software artifacts with unit testing
* Participate in periodic code review sessions
* Communicate with team members effectively, both written and verbally

## Skills

* 1+ years of experience with Elixir
* Experience working with Open Telecom Platform (OTP)
* Experience with Relational Databases and SQL

### NICE TO HAVE

* Exposure to NodeJS and/or Ruby is preferred
* Experience with ReactJS would be a plus

### TECHNOLOGIES WE USE
* Elixir, Javascript, Ruby
* Vue.js, Ruby on Rails
* PostgreSQL, Redis
* Heroku, AWS
* Sentry, Slack, Gitlab, Trello

### Contact
Homepage: https://www.acuity.sg
Send your CV to this email with the subject title as [Elixir Engineer]: long_at_acuity_dot_sg

**Comment by Minh-Khang** [comment]
hello, how can I apply to this position ?

**Comment by acuityengineers** [comment]
@Minh-Khang can you send your cv to this email long@acuity.sg

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
