### ISSUE TITLE
Morphotech (UK blockchain startup) - ReactJS Developer - Saigon - FT

### ISSUE THREAD

**Issue by linhphan-morphotech** [awesome-jobs/vietnam#1740]
## Location

* 412 Nguyen Thi Minh Khai, Ward 5, District 3, Ho Chi Minh city, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* 2+ years of experience

### Must Have

* Strong experience in JavaScript
* Experience working with React
* Experience working with HTML5, CSS
* Knowledge/Experience with build tools (Webpack / Rollup)
* Knowledge of RESTful APIs and OAuth / JWT flows for authorization
* Knowledge of Redux core principles
* Familiarity with distributed computing and asynchronous programming paradigms
* Experience with code sub-versioning using Git
* Experience with unit and integration test development

### Ideally

* Experience with containerization and virtualization tools (Docker)
* Experience with AWS 
* Familiarity with web front-end frameworks (React) and technologies (HTML5, CSS, JavaScript, Redux) 
* Knowledge of blockchain/Ethereum/Bitcoin

## You’ll be responsible for

* Write readable and maintainable code that not only performs the task but eases future modifications
* Work in a team environment, cooperating on designing and implementing user friendly solutions
* Keep up with security standards for user privacy
* Translate designs and wireframes into highly reusable code
* Keep track of work progress and work in an objective oriented environment
* Create and maintain documentation on solution design and maintenance

## Why it would be awesome to work with us
* Opportunity to build/grow a team of supernovas right from the start
* Work in a multinational, dynamic and young environment
* 15 days annual leave + birthday
* Full social insurance & unemployment insurance
* Flexible working arrangements
* Motorcycle parking
* AC Office space

## Contact
Homepage: https://morphotech.co.uk
Email: linh.phan@morphotech.co.uk

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
