### ISSUE TITLE
Morphotech (UK blockchain startup) - React Native Developer - Saigon - FT

### ISSUE THREAD

**Issue by linhphan-morphotech** [awesome-jobs/vietnam#1743]
Morphotech (UK blockchain startup) - React Native Developer - Saigon - FT

## Location

* 412 Nguyen Thi Minh Khai, Ward 5, District 3, Ho Chi Minh city, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* 2+ years of experience

### Must Have

* Experience in developing both for iOS and Android, using React Native
* Strong experience in JavaScript
* Knowledge of iOS SDK and/or Android SDK
* Experience with the publishing process for both Apple and Google app stores (share your apps with us)
* Experience with multithreading, memory management, and caching mechanisms specific to mobile devices
* Experience with code sub-versioning using Git
* Experience with unit and integration test development
* Fluency in English language

### Ideally

* Experience with containerization and virtualization tools (Docker)
* Good grasp of SQL and relational database management systems (PostgreSQL)
* Knowledge of blockchain/Ethereum/Bitcoin

## You’ll be responsible for

* Write readable and maintainable code that not only performs the task but eases future modifications
* Work in a team environment, cooperating on designing and implementing user friendly solutions
* Keep up with security standards for user privacy
* Translate designs and wireframes into highly reusable code
* Keep track of work progress and work in an objective oriented environment
* Create and maintain documentation on solution design and maintenance

## Why it would be awesome to work with us
* Opportunity to build/grow a team of supernovas right from the start
* Work in a multinational, dynamic and young environment
* 15 days annual leave + birthday
* Full social insurance & unemployment insurance
* Flexible working arrangements
* Motorcycle parking
* AC Office space

## Contact
Homepage: https://morphotech.co.uk
Email: linh.phan@morphotech.co.uk

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
