### ISSUE TITLE
CodeLink - Devops Engineer (AWS, Docker) - HCMC - FT

### ISSUE THREAD

**Issue by khacanh** [awesome-jobs/vietnam#1744]
![jd_photo_slideshow](https://user-images.githubusercontent.com/122055/57909658-90787700-78ad-11e9-9630-e38138d697b5.jpeg)

## Location

We are conveniently located beside the Zoo on Xo Viet Nghe Tinh, at the border of District 1 and District Binh Thanh, with easy access for all districts and a plentiful amount of awesome food and great coffee shops around the office.

## Salary Expectation
* $1500+

## About us

CodeLink is an innovative and design-focused development studio made up of an international mix of Designers and Developers. Our main stacks are Rails, NodeJS, VueJS and ReactJS. We have built products in different industries, including Finance, Education, Entertainment, HR, etc for clients ranging from start-ups such as CryptoKitties to big companies such as Air Asia and Electronic Arts.

We are building an engineer-first environment. We want all members to grow with the company through hands-on projects and industry best practices. Our clients have extremely high expectations and that sets a bar for our quality of work.

Our engineers work directly with international teams from Canada, US (Silicon Valley, Boston), Germany and other well-developed tech scenes. We have learned a lot from them, and vice versa. 

We are willing to adopt new but proven technologies provided that they bring business values to our clients and learning opportunities for our engineers. We have our freedom to choose and recommend what solutions are best for a certain project.

## Requirements

+ Hands-on experience with Docker and Kubernetes
+ Experience with at least these Amazon services: EC2, Elastic Beanstalk, SQS, S3, Lambda
+ Had setup several CI and CD systems for both web and mobile applications
+ Hands-on experience with deployment, scaling, monitoring and performance tuning
+ Git, Github and Pull Request knowledge
+ Excellent written and verbal communication skills in English
+ Familiar with Microservices architecture
+ Familiar with Terraform and Ansible
+ Familiar with GCP: Google Container Engine, GCE, GAE etc. 
+ Familiar with Microsoft Azure
+ Familiar with System Design and multi-component Architecture experience
+ Familiar with Agile process and scrum methodologies

## Responsibilities

+ Work closely with the developers to help them solve tricky problems in a production environment: scale, performance, security etc. 
+ Work closely with all team members to boost productivity by optimizing and automating workflows
+ Help setup multiple environments for development, testing, staging and production purposes
+ Make sure a system is production-ready
+ Optimize existing systems to make sure they are cost-effective
+ Actively involved in product discussions and sprint planning
+ Contribute to the local tech ecosystem by mentoring, writing articles and joining events.

## How we work

We work with a true team mindset, with every member having equal say in how we run our projects, our technologies and our product decisions. We work as a tight and unified team, investing in the development of all members of our team and the furthering of their abilities. 

We focus on creating qualified software and on improving our engineers. You are required to write neat code and follow highly efficient workflow, but you are about to learn tons of new things along the way via pair programming, code review and mentorship. 

## Why you’ll love working with us

- Absolutely no overtime. We respect work-life balance. 
- We fully invest in our team, we will help you build yourself up in any area you feel you need development, be it in English, learning a new programming language, product understanding and more. We want to make sure that you’re always learning and developing yourself whilst a part of our team. 
- We respect both Product and Technology equally, ensuring all of the Products we work on have features with true market potential and ensuring all of the team contribute to, understand and believe in what they are developing. 
- We are very selective with our Clients, we only work on awesome Products we believe in and that show strong market potential. 
- We respect you and your personal hours, we keep sustainable pace by working standard 8 hour days from Monday to Friday, ensuring we only plan for what we can achieve. 
- We work fully Agile, and only work with Clients who work the same, working with set sprint goals and working at our rate of velocity. 

## Contact

Khac Anh: ka_at_codelink_dot_io

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
