### ISSUE TITLE
FETCH Tech - Ruby on Rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by laciefetch** [awesome-jobs/vietnam#1746]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, Saigon, Vietnam
* FT

## Salary Expectation

* Up-to $2000 USD/month

## Requirements

* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* Minimum 2 years of experience in any of the followings: Ruby on Rails, Golang.
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Familiar with linux system administration and provisioning systems using Amazon Web Services
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Enjoys challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over communicating, language barriers aside, you must be willing to make an effort to communicate as much as).
* Overthink security.
* Can communicate well in English.

### Ideally

* Familiar with and passionate about BitCoin and crypto currencies, its network and protocol.
* Able to code in multiple languages - Java, Scala, Golang, Ruby.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Full-stack developer to maintain and develop online services.
* Work closely with product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web and applications.
* Participate in user testing on production.

### Why it would be awesome to work with us

* Attractive salary and allowances.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Homepage: fetch.tech
Skype: lacie.soul12
Mail: lacie@fetch.tech

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
