### ISSUE TITLE
Acuity - Junior/Mid-level Full Stack Software Engineer (Ruby) - Onsite/Remote - FT

### ISSUE THREAD

**Issue by acuityengineers** [awesome-jobs/vietnam#1747]
## Location

* HCMC, Vietnam
* Remote

## Salary Expectation

* `>=` 3000+ SGD

## Requirements

* Design and build reliable trading software platform primarily in Ruby, Ruby on Rails, Elixir and Javascript
* Willing to learn Elixir/Phoenix 
* Maintain clean and human-readable software artifacts with unit testing
* Participate in periodic code review sessions
* Communicate with team members effectively, both written and verbally

## Skills
* 2+ years of experience with Ruby, Ruby on Rails
* Experience working with concurrent web application.
* Experience with Relational Databases and SQL

### NICE TO HAVE

* Exposure to Elixir is preferred
* Exposure to NodeJS and/or Ruby is preferred
* Experience with ReactJS would be a plus

### TECHNOLOGIES WE USE
* Elixir, Javascript, Ruby
* Vue.js, Ruby on Rails
* PostgreSQL, Redis
* Heroku, AWS
* Sentry, Slack, Gitlab, Trello

### Contact
Homepage: https://www.acuity.sg
Send your CV to this email with the subject title as [Elixir Engineer]: long_at_acuity_dot_sg

**Comment by LilyaLe** [comment]
Hi,
I want to apply this position but I don't see the contact information.
Could you please let me know the email address to send my CV?
Thankyou.

**Comment by kimquy** [comment]
Hi @LilyaLe contact info is in the description. 

But you can email your CV to here long@acuity.sg

Thank you.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
