### ISSUE TITLE
CinqSmile - Android Developer - HCMC - FT

### ISSUE THREAD

**Issue by hnchuong** [awesome-jobs/vietnam#1748]
## Location

* 38E Tran Cao Van, Ward 6, Dist 3, HCMC
* FT

## Salary Expectation

* Up to $1000

## Requirements

- At least 2 year experience with Android development
- Solid understanding of the full Android development life cycle.
- Having knowledge about caching, lazy loading, SQLite, Content Provider, HTTP, AsyncTask, Socket, Ninepatch, Fragment, Push Notification Technologies
- Knowledge of UI elements & layout, basic animation technique
- Excellent problem solving, critical thinking, and communication skills
- Experience in working with Server Side using RESTful, SOAP
- Experience in working with 3rd libraries, Kotlin is a big plus
- Understanding basic knowledge of security.
- Strong desire to build a high-quality product.
- Ability to work in a team.

### You’ll be responsible for

- Developing applications for Android smartphone using Java, Android SDK.
- Working under the division of Leader;
- Assuring the progress of work assigned and report tasks everyday;
- Being fond of and having a strong desire to work for Japanese company;

More details will be discussed in the interview.

### Why it would be awesome to work with us

- Salary review twice a year
- 13th month salary
- Insurance follow Vietnamese labor law
- Professional and friendly Japanese working environment
- Birthday bonus
- Social insurance, yearly health checking & good annual holidays.
- Annual company trip
- Working time：Mon-Fri, 8:00-17:00

### Contact
Email: cinqsmile-vn@5smile.com
Phone: 02839117417

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
