### ISSUE TITLE
CinqSmile - Full-stack Developer (Ruby on Rails, AngularJS) - HCMC - FT

### ISSUE THREAD

**Issue by hnchuong** [awesome-jobs/vietnam#1749]
## Location

- 38E Tran Cao Van, Ward 6, Dist 3, HCMC
- FT 

## Salary Expectation

* Up to $2000

## Requirements

- At least 2 years of experience with Ruby on Rails
- Experience in front end development with javascript, Angular
- Good knowledge of css, html
- Good knowledge of database and SQL, particularly MySQL
- Experience with source control (git, subversion…)
- Can communicate in English or Japanese
- Can read technical books in English
- Eager to research and learn in a self-directed way to keep an eye on the major players in the industry (always improving)
- Easygoing, fun, and a team player

### You’ll be responsible for
We are looking for web developers to contribute to a successful social network application for corporates.

- Be familiar with agile development, write high-quality, clean, simple, and maintainable code, build common libraries
- Analyse requirements, design and develop functionality, according to product specifications;
- Acquire an in-depth understanding of products, constantly optimize the products, diagnose and fix problems, improve stability and user experience;
- Design and implement various supporting tools as required;
- Collaborate with other software engineers, product managers, user experience designers, and operation engineers to build new products.
More details will be discussed in the interview

### Why it would be awesome to work with us

- Salary review twice a year
- 13th month salary
- Insurance follow Vietnamese labor law
- Professional and friendly Japanese working environment
- Birthday bonus
- Social insurance, yearly health checking & good annual holidays.
- Annual company trip
- Working time：Mon-Fri, 8:00-17:00

### Contact
Email: cinqsmile-vn@5smile.com
Phone: 02839117417

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
