### ISSUE TITLE
CinqSmile - Fresher Full-stack Developer (Ruby on Rails, AngularJS) - HCMC - FT

### ISSUE THREAD

**Issue by hnchuong** [awesome-jobs/vietnam#1750]
## Location

- 38E Tran Cao Van, Ward 6, Dist 3, HCMC
- FT

## Salary Expectation

* $300 - $500

## Requirements

- Students have just graduated from Information Technologies or related fields. 
- Has sound knowledge about OOP, data structures and algorithms.
- Has knowledge about database, SQL
- Has knowledge about web technologies: HTML, CSS, JS
- Has been an intern working as a developer before is an advantage
- Eager to learn and be a team player attitude.
- Can read technical materials in English
- Know Japanese is an advantage

### Responsibilities

We are looking for fresh web developers to contribute to a successful social network application for corporates.

- Under supervisor of a mentor:
- Develop functionality, according to product specifications;
- Acquire good understanding of products, diagnose and fix problems
- Implement various supporting tools as required;
- Collaborate with other software engineers, product managers, user experience designers, and operation engineers to build new products.
- More details will be discussed in the interview

### Why it would be awesome to work with us

- Salary review twice a year
- 13th month salary
- Insurance follow Vietnamese labor law
- Professional and friendly Japanese working environment
- Birthday bonus
- Social insurance, yearly health checking & good annual holidays.
- Annual company trip
- Working time：Mon-Fri, 8:00-17:00

### Contact

- Email: cinqsmile-vn@5smile.com
- Phone: 02839117417

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
