### ISSUE TITLE
Rakuna - Web Developer - Long Bien (HN) - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1751]
## Location
* 156 Viet Hung, Long Bien, Hanoi, Vietnam

## Salary Expectation
* $500-900/month

## Responsibilities
* Manage web product pipelines including planning, development, hotfix, and maintenance
* Collaborate with core functional teams - Sales & Marketing, Customer Success, and Operations to achieve the ultimate business goals
* Support Operations team in solving customer's technical issues and/or inquiries 

### Must Have
* At least 1 year of software development experience in one or more general-purpose programming languages
* Database: MySQL, Postgres, Redis, MongoDB
* Have a strong knowledge of TDD, BDD 
* Working proficiency and communication skills in verbal and written English
* Interest and ability to learn new coding languages quickly 
* Ability to proactively do research and always self-update with new technical knowledge 

### Ideally
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect
* A strong sense of design is a plus

## Why it would be awesome to work with us
* A chance to be a part of a young, dynamic, multinational and multi-functional team that serves U.S. customers with new everyday challenges
* High work flexibility and ownership
* Comprehensive compensation and benefits package

## Contact
Website: www.rakuna.co
Submit resume: Email ly@rakuna.co with subject "Name - Web Developer"

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
