### ISSUE TITLE
Rakuna - Software Engineer Intern - Long Bien (HN) - PT/FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1752]
## Location
* 156 Viet Hung, Long Bien, Hanoi, Vietnam

## Salary Expectation
* To be discussed and negotiated during/post-interview 

## Responsibilities
* Assist the Product Team in building and/or manage product pipelines including planning, development, and maintenance.
* Analyze information and evaluate results to choose the best solution to effectively solve problems.
* Understand deeply the company's product suite 
* Learn in-depth about how to create a product in a start-up environment. You might be the next entrepreneurial commander for your future start-up!

### Must Have
* Currently enrolled in a Bachelor's program in Computer Science, Information Technology or a related technical field.
* Experience of coding in one of the following programming languages including but not limited to: Ruby, C++, Java, Python.....
* Have contributed in or lead at least 1 software development project in one or more general-purpose programming languages.
* Working proficiency and communication skills in verbal and written English
* Ability to proactively do research and always self-update with new technical knowledge 
* Effective teamwork, creative problem-solving, and communication skills

### Ideally
* Technology internship experience or work experience (e.g: research assistant, teaching assistant, personal projects, etc.) 
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect
* A strong sense of design 

## Why it would be awesome to work with us
* A chance to be a part of a young, dynamic, multinational and multi-functional team that serves U.S. customers with new everyday challenges
* High work flexibility and ownership
* Comprehensive compensation and benefits package

## Contact
Website: www.rakuna.co
Submit resume: Email ly@rakuna.co with subject "Name - Software Engineer Intern" 
Deadline: Position open until filled.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
