### ISSUE TITLE
Rakuna - Mobile App Developer - Phu Nhuan (HCMC) - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1753]
## Location
* Dao Duy Anh, Phu Nhuan, Ho Chi Minh City, Vietnam 

## Salary Expectation
* $600-1000

## Responsibilities
The Mobile App Developer will be responsible for the development and maintenance of applications aimed at a range of devices including mobile phones and tablet computers. You will be working alongside other engineers and developers working on different layers of the infrastructure.

* Design, develop, and optimize mobile application
* Support the Senior Mobile App Developer in implementing complex new features and fixing bugs 
* Consult on project goals (best practices, conversion, Usability, UI / UX)
* Work closely with developers and designers to create beautiful, functional solutions
* Support multiple clients and internal projects simultaneously
* Understand deeply the company's product suite 
* Learn in-depth about how to create a product in a start-up environment. You might be the next entrepreneurial commander for your future start-up!

### Must Have
* Strong background in mobile application development with significant cross-platform mobile engineering experience (1+ years) in Android
* Expertise working on at least one large application and/or have released multiple apps (business and/or personal)
* Familiarity with mobile threading, memory management, MVC/MVVC concepts and how they apply to mobile applications
* Ability to develop effective UX solutions through user feedback loops, leveraging both quantitative and qualitative metrics
* Working proficiency and communication skills in verbal and written English
* Ability to proactively do research and always self-update with new technical knowledge 
* Effective teamwork, creative problem-solving, and communication skills

### Ideally
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect
* A strong sense of design 

## Why it would be awesome to work with us
* A chance to be a part of a young, dynamic, multinational and multi-functional team that serves U.S. customers with new everyday challenges
* High work flexibility and ownership
* Comprehensive compensation and benefits package

## Contact
Website: www.rakuna.co
Submit resume and portfolio of past Mobile App projects: Email ly@rakuna.co with subject "Name - Mobile App Developer" 
Deadline: Position open until filled.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
