### ISSUE TITLE
Rakuna - Product (UX/UI) Designer - Long Bien (HN) - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1754]
## Location
*156 Viet Hung, Long Bien, Hanoi, Vietnam 

## Salary Expectation
* $500-800

## Responsibilities
We are looking for a talented Product Designer who is able to tie form and function into an elegant interface to join us. As a part of the Product Team, you are highly collaborative, driven by excellence, always push for innovation and take ownership of projects. You are not afraid of learning new knowledge and grow new skills.

* Understand deeply Rakuna's product suite, branding guideline, product positioning, and competitors in the market
* Develop creative concepts into prominent designs matched with brand guidelines and positioning according to products requirements such as banners, marketing materials, website, online banners,...etc
* Create design deliverables such as specifications, wireframes, prototype, and mock-ups
* Collaborate with the Product Team (Web, Mobile, Quality Assurance) to provide design ideas and strategies
* Support the Marketing Team in designing landing pages and other sales/marketing materials per request

### Must Have
* At least 1 year of relevant work experience 
* Portfolio with a focus on UI, UX, and IA for web and mobile technologies
* Product design experience at a SaaS or web applications business 
* Experience with user research and feedback analysis
* Proactive, self-motivated, high attention to detail, ability to deliver work on time and with quality
* Working proficiency and communication skills in verbal and written English
* Ability to proactively do research and always self-update with new technical knowledge 

### Ideally
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect

## Why it would be awesome to work with us
* A chance to be a part of a young, dynamic, multinational and multi-functional team that serves U.S. customers with new everyday challenges
* High work flexibility and ownership
* Comprehensive compensation and benefits package
* Own creative freedom, wear multiple hats and work on a wide variety of exciting projects

## Contact
Website: www.rakuna.co
Submit resume and portfolio of past work: Email ly@rakuna.co with subject "Name - Product Designer" 
Deadline: Position open until filled

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
