### ISSUE TITLE
US startup - Frontend web developer - Ho Chi Minh - FT/Remote

### ISSUE THREAD

**Issue by daywednes** [awesome-jobs/vietnam#1755]
## Location

* Based in Ho Chi Minh, Vietnam.
* Can work remotely and report to the founder in US in first few months.

## Salary Expectation

* $1000 - $2000/month

## Requirements
* 3+ years of experience as a front end web developer
* 3+ years experience with TypeScript or ES6
* 3+ years experience with a modern UI framework (eg: ReactJS, Redux, VueJS)
* Experience working with REST and Graphql APIs
* Experience building responsive websites and progressive web apps
* Proficient with modern CSS resources (eg: SCSS, Foundation)
* Proficient in web development tools and debugging
* Familiarity with JavaScript unit test tools (eg: Mocha, Jasmine, Jest)
* We do not care about your degree but BS or MS in Computer Science is a plus.
* Experience in mobile development (Android and IOS) is a big plus

### Must Have

* Be a team player with a sense of empathy, awareness, and responsibility

### Ideally

* Experience working in startups is a plus
* Ability to communicate in English is a plus

### Responsibilities

* As a core member of the new startup, you will report directly to the founder
* Becoming a core member of a new startup, you will have the opportunity to design and build the product from crash and make influence to later team members.

### You can bring

* A good eyes for design
* A good value to our shared target

### Why it would be awesome to work with us

* Be a part of core member working with a US startup.
* Competitive compensation based on experience
* Quarterly evaluation with salary and bonus reviews
* Self-improvement courses can be requested
* Annual health check
* We only offer you the job if you are really happy with the offer
* We really care about your growth, happiness and your life

### Contact
Email: daywednes@gmail.com
Linkedin: https://www.linkedin.com/in/daywednes/

Thank you for spending time reading this post.

**Comment by qcam** [comment]
@daywednes Could you provide more information about the company please?

The job post will remain closed until the question is addressed.
