### ISSUE TITLE
HR1VN - Senior ROR - $2500 - HCMC - Fulltime 

### ISSUE THREAD

**Issue by minatran** [awesome-jobs/vietnam#1757]
## Location: 
Binh Thanh - HCM - Product US Company
Dist.2 - HCM - Outsource Canada Company 
Fulltime
## Salary Expectation

* up to $2500 gross/month

## Responsibility

- Working with the team on new projects and existing projects, from implementation
- and deployment of the completed project.
- Leading the technical direction during design and development processes by driving
- decisions and coordinating efforts with the project team.
- Providing insight and effectively communicating with internal and external
- stakeholders to demonstrate how the solution will be leveraged to meet clientbusiness demands on new projects.
- Engineering leading-edge systems for clients in a variety of industries, with solutions
- targeting a variety of customer models such as B2C and B2B engagements•Driving the technical culture of company forward as a thought leader among our team
- You should bring to the table:
- Working experience with Ruby on Rails development process in an agile environment
- and the ability to create apps for client requirements
- Strong knowledge and experience with integrations to back-end systems
- Ability to come up with accurate development estimates based on high-level business
- and/or technical requirements
- Ability to lead and mentor teams of onshore and offshore engineers working on
- eCommerce solutions
- A keen interest in emerging technologies and how they might impact future design
- decisions and strategic directions
- 3+ years of experience in Ruby on Rails development
- Experience working with Shopify is a Plus
- Strong understanding and Knowledge of MySQL
- Strong HTML/CSS and JQuery knowledge

## Skills

- Good verbal and written English
- 2+ years of experience with Ruby on Rails framework
- Experience with CSS3
- Experience with eCommerce platforms
- Experience writing Javascript (ES6, jQuery, Web APIs)
- Good knowledge in data processing (SQL, XML)
- Experience with Git and using the command line

### Why it would be awesome to work with us

- 13th-month salary.
- Rewards based on project success
- 2 Types of Insurance: Healthcare (private insurance company paid 100%) +
- Flexible time
- 12 holidays during the year and the day of the year is increased by the number of years
- employees sticking.
- Company trip each year
- 

### Contact
Email: hoa.tran@hr1vietnam.com
Skype: hoattm97

**Comment by qcam** [comment]
@minatran thanks for posting but currently we only take posts directly submitted by the employer.
