### ISSUE TITLE
HR1VN - Senior/ principle Vuejs Developer - $2500 - HCM

### ISSUE THREAD

**Issue by minatran** [awesome-jobs/vietnam#1758]
## Location

* Belgium Company 
* Tan Binh HCM
* Fulltime

## Salary Expectation

* $2500/month 

## Requirements

•Minimum 3 years experience in professional web design using HTML5,
CSS, CSS3, and Javascript(Vuejs)
•Proficient in HTML/XHTML, HTML5, Javascript, jQuery, and
performance optimization
•Ability to work with IDEs (Sublime Text is required)
•Strong experience and background in Javascript is required
•Experience with Javascript(Vuejs)framework is required
•Strong background in HTML5/CSS3
•Knowledge of CSS3 Animation, Javascript Animation, SVG Animation.
•Experience working with mobile and web templates
•Knowledge and experience in graphic design for web, Photoshop, and
Illustrator is a strong plus
•Knowledge to create an Email Marketing, New Letter Template can
compatibility on the most of the platforms & different environments (Browsers,
Outlook Application, Mobile, Tablet ...).
•Good knowledge of responsive compatibility on devices.
•Familiar with Email Marketing Campaign Tools (eg. MailChimp).
•Familiar with Task Runner (eg, GulpJS, GruntJS) inNodeJS.
•Familiar with ad publishers (eg. Double Click)
•Familiar with European or US styles (international standards)
•Knowledge in W3C Standards (or able to learn quickly about them)
•Independent, responsible, and proactive with the ability to learn and
achieve superior results.

### Why it would be awesome to work with us
•The latest technologies for mobile & web development
•Teammates that challenge you to exceed your limits
•The finest IT tools to raise your potential to even greater heights
•The power to deliver some truly awesome products & services
•Cutting-edge collaborative software development
•A career path that allows you to learn and grow
•Attractive annual bonuses
•Private health care program
•Strong teamwork and contribution skills

### Contact
Do you recognize yourself in this role? And, are you willing to shape the future
of the digital world with us?
Or, would you like to refer your friend to this job?
Please send an email to hoa.tran@hr1vietnam.com or skype: hoattm97 .

**Comment by qcam** [comment]
@minatran Could you please format the job post compliant to our guideline? Also, will the hired be working at HR1VN or outsourcing clients? 

The post will remain closed until questions above are addressed. Thanks.

**Comment by minatran** [comment]
@qcam the hired be working at outsourcing clients?
