### ISSUE TITLE
Grab - Back-End Engineer (Golang Preferred) - Saigon - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1759]
## Location

* MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon

## Salary Expectation

* Negotiable

## Requirements
* Have 2+ years of experience coding Backend with various programming languages, willing to work with Golang
* Experience in shipping web applications to production, CI/CD flow
* Familiarity with running large scale web services; understanding of systems internals and networking are a plus
* Strong understanding of system performance and scaling
* Possess excellent communication, sharp analytical abilities with proven design skills, able to think critically of the current system in terms of growth and stability
* Experience in writing good unit test

## Skills
* ALL SKILL ACCEPTED 

### Ideally 

* Experience with Golang

### You’ll be responsible for

* Design and write with the cutting edge Golang to improve the availability, scalability, latency, and efficiency of Grab's range of services
* Work with engineering team to explore and create new design / architectures geared towards scale and performance
* Work with product managers, data analysts and implement products and features, and test their impact to business metrics.
* Participate in code and design reviews to maintain our high development standards.
* Work closely with infrastructure team in building and scaling back-end services as well as performing root cause analysis investigations.
* Design, build, analyze and fix large-scale systems.
* Debug and modify complex, production software.

### You can bring

* A culture of learning
* Free rides with Grab
* Medical coverage. Extra Medical Insurance.
* Macbook is provided.
* 14 days annual leaves.
* Diverse teams
* Weekly Tech talks + Quarterly Hackathons
* High growth opportunities
* Flexible working hours

### Why it would be awesome to work with us
* Positive & Collaborative environment
** Grabbers thrive in a corporate culture that values every team member's contribution towards our goal of improving lives.

* Rocket fuel for careers
** Grabbers experience hyper professional growth and all the challenges that entails. Grow your skills while working to solve real issues across the region.

* Fun & dedicated family
** Grabbers work hard and play hard. Our teams grow as one as they overcome challenges and have fun along the way.

### Contact
Homepage: https://grab.careers/ or https://grab.careers/locations-vietnam
Email: cuong.vo0906@gmail.com

![Golang_2](https://user-images.githubusercontent.com/39041308/67163853-518ba780-f39e-11e9-843a-7ca762e4081c.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
