### ISSUE TITLE
ABIVIN - Algorithm Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by TuanNguyennnn** [awesome-jobs/vietnam#1761]
## Location

* 100 Doc Ngu, Ba Dinh District, Hanoi

## Salary Expectation

* Negotiable

## Requirements
* Experience/Having patience with Classical Algorithm and solve the NP problem (optimal solution not known in linear time)
* Proficiency in some popular languages such as C ++, Java; prefer Python, TypeScript / JavaScript, Scala / Java; 
* Be able to quickly learn new programming languages

### Ideally

* Familiar with SQL databases, preferably knowing NO-SQL (Not-Only SQL), big data analysis systems (Big Data) is an advantage
* Passion for solving difficult problems, optimizing algorithms

### Responsibilities

* Solving algorithm problems and NP problems
* Work with internal departments (product design, sales, sales team) or external clients or groups to ensure project performance
* Propose and develop high quality features to increase speed, scale and usability
* Ensuring the architecture of the platform is scalable, readily available and practical to meet the level of service committed
* Handling throughout the software development process, diagnosing and fixing the problems encountered
* Other jobs as directed by superiors

### Why it would be awesome to work with us
* Attractive salary, bonus based on ability, OT bonus according to the Labor Law
* Insurance + evaluating working efficiency 2 times / year
* Stocks for outstanding individuals
* Free lunch at the company, support parking costs
* Working with modern technologies and tools; The partner is the world's leading multinational corporation
* Trained, shared experience with experienced people working at large corporations like Google
* Young, friendly, professional environment where you can listen to and develop yourself
* Join the teambuilding activities fun monthly
* Working time: Monday - Friday (8h30 - 18h, lunch break from 12h - 13h30).

### Interesting engineering projects
* ABIVIN specializes in big data analysis and system optimization for Logistics (Big Data Analytics & Optimization for Logistics). This is a new and potential field in Vietnam and Southeast Asia with customers of large corporations (Fortune 500 & Forbes Global 2000) with increasing demand.
* Abivin's customers are the leading corporations in the world (Fortune 500 & Forbes Global 2000 such as P&G, Friesl and Campina).

### Contact
Link ABIVIN On Shark Tank:  https://www.youtube.com/watch?v=TDKIGUytr7k    
Apply Now via: at.nguyen.0104@gmail.com
Subjects: Algorithm Engineer _ Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
