### ISSUE TITLE
ABIVIN - Back End Engineer (Python/NodeJS) - Hanoi - FT

### ISSUE THREAD

**Issue by TuanNguyennnn** [awesome-jobs/vietnam#1762]
## Location

* 100 Doc Ngu, Ba Dinh District, Hanoi

## Salary Expectation

* Negotiable

## Requirements
* Proficient in NodeJS
* Ability to plan and take responsibility for their own plans, work with the highest spirit and responsibility for the work
* Proficient in application development principles through API and server architecture, load mechanism
* Proficient in basic to distributed databases such as MySQL, MongoDB, Redis
* Proficient in source and project management tools like Git, Github, documentation for API, tool for code quality management, API doc

### Ideally

* Using CI / CD tools (like Jenkins) to ensure continuous connectivity is an advantage
* English is preferred; ability to work independently and in groups, 
* Working at high intensity and under good pressure; logical thinking, self-learning new technologies fast; be proactive and creative at work. 

## Responsibilities

* Participate in the entire development cycle of software products, ongoing projects
* Work with internal departments (product design, sales, sales team) or external clients or groups to ensure project performance
* Propose and develop high-quality (Front-end + Back-end) features to increase speed, scale, and usability
* Handling throughout the software development process, diagnosing and fixing the problems encountered
* Other jobs as directed by the director

### Why it would be awesome to work with us
* Attractive salary, bonus based on ability, OT bonus according to the Labor Law
* Insurance + evaluating working efficiency 2 times / year
* Stocks for outstanding individuals
* Free lunch at the company, support parking costs
* Working with modern technologies and tools; The partner is the world's leading multinational corporation
* Trained, shared experience with experienced people working at large corporations like Google
* Young, friendly, professional environment where you can listen to and develop yourself
* Join the team-building activities fun monthly
* Working time: Monday - Friday (8h30 - 18h, lunch break from 12h - 13h30).

### Interesting engineering projects
* ABIVIN specializes in big data analysis and system optimization for Logistics (Big Data Analytics & Optimization for Logistics). This is a new and potential field in Vietnam and Southeast Asia with customers of large corporations (Fortune 500 & Forbes Global 2000) with increasing demand.
* Abivin's customers are the leading corporations in the world (Fortune 500 & Forbes Global 2000 such as P&G, Friesl and Campina).

### Contact
* Link ABIVIN On Shark Tank: https://www.youtube.com/watch?v=TDKIGUytr7k
* Apply Now via: at.nguyen.0104@gmail.com
** Subjects: Back-End Engineer _ Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
