### ISSUE TITLE
ABIVIN - Front-End Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by TuanNguyennnn** [awesome-jobs/vietnam#1763]
## Location

* 100 Doc Ngu, Ba Dinh District, Hanoi

## Salary Expectation

* Negotiable

## Requirements
* At least 2 years of experience working with Front-End platforms
* Proficient in JavaScript, ReactJS
* Knowing AngularJS, Bootstrap is an advantage
* Mastering the knowledge of object-oriented programming (OOP), MVC model, structure design
* Proficient in Git source management tools, project management tools

### Ideally

* Experience with Cross Platform tools like Ionic is an advantage
* Experience in using one of the basic to distributed databases such as MySQL, MongoDB, Redis, Cassandra, Hadoop. If you have experience designing, developing databases, APIs
* English is preferred

## Responsibilities

* Participate in the entire software development cycle of ongoing projects
* Self-managed work to ensure the most important and urgent tasks need to be completed early and best according to project progress
* Working with internal departments (product group, design, sales), customers, cooperation groups to ensure project activities
* Ensuring the architecture of the platform is scalable, readily available, and practical to meet the level of service committed
* Handling throughout the software development process, diagnosing and fixing the problems encountered
* Other jobs as directed by superiors

### Why it would be awesome to work with us

* Attractive salary, bonus based on ability, OT bonus according to the Labor Law;
* Insurance + evaluating working efficiency 2 times / year;
* Stocks for outstanding individuals;
* Free lunch at the company, support parking costs;
* Working with modern technologies and tools; The partner is the world's leading multinational corporation;
* Trained, shared experience with experienced people working at large corporations like Google
* Young, friendly, professional environment where you can listen to and develop yourself;
* Join the teambuilding activities fun monthly;
* Working time: Monday - Friday (8h30 - 18h, lunch break from 12h - 13h30).

### Interesting engineering projects
* ABIVIN specializes in big data analysis and system optimization for Logistics (Big Data Analytics & Optimization for Logistics). This is a new and potential field in Vietnam and Southeast Asia with customers of large corporations (Fortune 500 & Forbes Global 2000) with increasing demand.
* Abivin's customers are the leading corporations in the world (Fortune 500 & Forbes Global 2000 such as P&G, Friesl and Campina).

### Contact
* Link ABIVIN On Shark Tank: https://www.youtube.com/watch?v=TDKIGUytr7k
* Apply Now via: at.nguyen.0104@gmail.com
** Subjects: Front-End Engineer _ Your Name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
