### ISSUE TITLE
Dinovative - Angular Developer (Junior) - Saigon - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#1767]
## Location

* Dinovative is looking for Angular Developer who is excited to work alongside a talented group of innovators to craft digital products. Being part of the conversation from the start, you will be expected to lead full lifecycle webbased projects including guiding technical scoping, design and implementation.
Collaborating with UX & UI designers, researchers and other engineers, you will have the ability to flex your full stack chops to help shape, design and build digital products that help solve key business needs. We want people who love being involved in challenging and innovative work.

* N0 11, D1 Street, Tan Hung Ward, District 7

## Salary Expectation

* Negotiable

## Requirements
* Good working experience in using JavaScript, HTML5, CSS, Bootstrap
* Strong working experience and best practices with Angular 7, Typescript, ES6
* Strong analytical and problem solving abilities
* Strong communication and client facing skills

## Skills
* Strong Javascript
* RESTful API 
* Database mySQL, MongoDB, PostgreSQL

### Must Have
* Minimum 1 – 3 years of experience in web app development with Angular 7
* Solid understanding of HTML, CSS3, Bootstrap, SASS, LESS, responsive design
* Good knowledge in RESTful API
* Experience building responsive web apps 
* Be able to writing tests with unit test
* Proficient understanding of code version control tools, such as Git

### Ideally
* Experience with iOS/Android native app development is a plus
* Experience using NodeJS, ReactJS, Webpack is a plus

### Responsibilities
* Key contributor to our front-end applications written in Angular 7 and TypeScript 
* Work with design and engineering team members to build features from concept through implementation
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Learn and share expertise with teammates through code reviews and other avenues
* Research and propose new approaches to work, new tools, and new best practices for the team
* Integrate with assigned product development team and participate in cross-functional collaborations
* Provide development task effort estimates
* Conduct client requirements gathering and analysis
* Review test plans
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:
* Working in dynamic, young, friendly, flexible invironment
* Laptop is provided
* 12+ days annual leaves, working Monday - Friday, flexible working time
* Attractive salary based on skills and experiences
* Salary review: Once a year, base on individual performance review
* Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy 
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding 
* Free fruits/ snacks on happy hours time
* Celebration: birthday
* Party time: Team building (frequent) and Xmas
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development 
* Training new technology frequently, and become a fullstack developer

### Interesting engineering projects
* We use international standard in building system such as agile, test driven development, continuous integration and continuous deployment.
* Various projects with so many new technologies applied

### Contact
Email: oanh.tang@dinovative.com
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
