### ISSUE TITLE
KVY Tech - Fullstack Engineer (Junior/Mid - Ruby/Elixir/Javascript) - HCMC or Remote - FT

### ISSUE THREAD

**Issue by kvyadmin** [awesome-jobs/vietnam#1768]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Very competitive 

## What you will be doing
* Familiar with the full software development lifecycle, including participation in code reviews and sprint planning to deliver world-class software.
* Develop quality, scalable, efficient software using Ruby, Ruby on Rails, React, Elixir, Phoenix, AWS.
Practice good, consistent software development hygiene.
* Involve in communicating with customers to understand their ideas and requirements.
* Collaborate with teammates to make strategic technical decisions.

## Desired skills

* 1+ years of professional experience building and deploying scalable web applications.
* Experience with Ruby/Rails, Elixir/Phoenix, and Javascript
* Understanding of SQL.
* Nice to have front-end skills: React.js/Vue.js
* Excellent communication skills

### Contact
Homepage: https://kvytechnology.com
Send your CV to this email address: hello@kvytechnology.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
