### ISSUE TITLE
[WaoStudio] - [Ruby on Rail Developer] - [Binh Thanh, HCMC] - [F]

### ISSUE THREAD

**Issue by Quinnnlp** [awesome-jobs/vietnam#1769]
## Location

* Saigon, Vietnam
* Vinhome Central Park, 208 Nguyen Huu Canh, Q.Binh Thanh

## Salary Expectation
* Up to $1500/month 

### Must Have
*Experience as Ruby on Rails developer (All Level)
*Experience with web front-end such as HTML, JavaScript, CoffeeScript, CSS, SASS, jQuery.
*Experience with RESTful API
*Experience with database system (Postgres, MongoDB)
*Experience with Git

### Ideally
*Experience with React JS is a plus
*Experience with Firebase is a plus
*Good English/Japanese verbal and written communication skills

### You’ll be responsible for
*Product development and see your features and ideas being implemented and used by thousands of users everyday.
*Join a young, winning and regional team working on disruptive technologies.
*Work closely with the regional teams (product, businesses) to see user’s and business teams feedback and provide solutions to improve your own product.
*You will work in Agile/Scrum environment.

### Why it would be awesome to work with us
*Working in an environment with plenty of opportunities to grow.
*Join Technical Traning Program.
*Salary: up to $1500.
*Lunch allowance.
*Working weekly from Monday to Friday.
*Other benefits as per stated in Vietnamese Labor Law.

### Contact
Homepage: waostudio.com
WaoStudio Contact: hello_at_waostudio_dot_com (0938962486)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
