### ISSUE TITLE
Fetch Technology - Ruby on Rails Developer - HCMC - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#1771]
## Location

* 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, HCMC
* FT

## Salary Expectation

* $1000 - 2000/month gross

## Requirements
* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* Minimum 2 years of experience in any of the followings: Ruby on Rails, Golang.
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Familiar with linux system administration and provisioning systems using Amazon Web Services.
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Enjoys challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over communicating, language barriers aside, you must be willing to make an effort to communicate as much as).
* Overthink security.
* Can communicate well in English.
Nice to have:
* Familiar with and passionate about BitCoin and crypto currencies, its network and protocol.
* Able to code in multiple languages - Java, Scala, Golang, Ruby.

### You’ll be responsible for

* Full-stack developer to maintain and develop online services.
* Work closely with product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web applications.
* Participate in user testing on production.

### Why it would be awesome to work with us
* Being a Software Engineer intern at Fetch Technology, you will experience a youthful, flexible and creative work environment:
- Attractive salary and allowances.
- Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
- Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
- Extensive on job training, you will always have chance to work with new emerging technologies.
- Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Fanpage: Fetch Vietnam
Mail: vynguyen@fetch.tech
Skype: vynht.hrm

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
