### ISSUE TITLE
Fetch Technology - Senior Java Developer - HCM/HN - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#1772]
## Location

* Ho Chi Minh City: 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9.
* Hanoi: 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District.

## Salary Expectation

* $2500/month

### Requirements

* BS/MS degree in Computer Science, Engineering or a related subject.
* Proven hands-on Software Development experience of at least 5 years.
* Proven working experience in Java development of at least 5 years.
* Hands on experience in designing and developing applications using Java EE platforms.
* Object Oriented analysis and design using common design patterns.
* Excellent knowledge of Relational Databases, SQL and ORM technologies (JPA2, Hibernate).
* Experience in Spring Framework.
* Experience in developing web applications using at least one popular web framework (JSF, Wicket, GWT, Spring MVC).
* Experience with web services and server application development.
* Experience with security concepts and cryptography, including key life cycle requirements, symmetric and asymmetric encryption methodologies and algorithms applicable to the financial payment and services industry.
* Experience with secure coding and application development involving cryptography operations integrating with HSM (Hardware Secure Module).

### Responsibilities

Implement a tokenization solution for payment gateway.

### Why it would be awesome to work with us

* Being a Software developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact

Fanpage: Fetch Vietnam
Mail: vynguyen@fetch.tech
Skype: vynht.hrm

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
