### ISSUE TITLE
FullStack Dev - Remote - Full time 

### ISSUE THREAD

**Issue by ngocphuong199** [awesome-jobs/vietnam#1775]
## Location

* Vietnam
* Remote

## $500 - $4000 

* Less than 1 year: $500 
* 1 - 3 years: $500 - $1000
* More than 3 years: $1000 - $4000 

## Requirements
* Back end - Ruby On Rails
* Front end - ReactJS
* Mobile - React Native 

### Benefits 

* MacbookPro 
* Health Insurance - Vinmec Premium. 
* The 13th-month Salary. 
* Full Salary during probation time. 
* Review Salary every year. 

##### Contact
Facebook: https://www.facebook.com/phuongnguyen39bd
Gmail: phuongnguyen39bd@gmail.com 
Phone: 0986 376 343

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
