### ISSUE TITLE
Quoine - Senior Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1776]
# Location

* D.1, Saigon, Vietnam

# Salary Range

* US $1500 - $4000

#### We are looking for Operations Technology Software Engineers (middle and senior) to help develop the growth of our industry-leading exchange platform Liquid. QUOINE's place in the block-chain based economy is growing quickly and your role will be to track, report, and reconcile assets - both crypto and fiat for reporting to senior management.  

# Responsibility 

* Implement new functionalities within our back-office system
* Provide technical and functional expertise to a cross-functional engineering team
* Solve hard business logic with elegant design and ensure system robustness, performance, and scalability
* Write well tested, bug-free code

# Requirement

* 3+ years of industry experience in engineering working with production-scale apps in Java, Ruby
* Extreme attention to detail (dealing with core crypto asset management)
* Passion for disruptive and open financial systems

## Nice to have

* Financial back office experience - (General/Subledger, Regulatory reporting, Reconciliation)
* AWS, Heroku
* Agile/Scrum methodology

## Others

* Proactive and self-starter
* Engineers who are able to take ownership of different components in the system
* Honest, intelligent, able to get things done
* Conversational and written English
* Have strong skill sets to handle multiple projects at the same time

# Why it would be awesome to work with us?

* Join a global leading Fintech company
* Bring cutting-edge technologies into play
* Enjoy exceptional benefits package (tech/non-tech training courses, gym sponsor, extra health insurance for you and your immediate family, daily snack, billiards competition, football weekly... you name it.)
* Work in one of the most modern & innovative spaces in town

# Contact

* Homepage: https://careers.liquid.com/
* E: linh.truong@quoine.com 
* M: 0938 019 369
* Skype: linh.truong.my

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
