### ISSUE TITLE
CINQSMILE -  Full-stack Web Developer - HCM - FT

### ISSUE THREAD

**Issue by phunguyen1990** [awesome-jobs/vietnam#1780]
## Location

* Saigon, Vietnam
* Full Time 

## Salary Expectation

* $1,200 - $2,000

## Requirements
* 1 years of experience with Ruby on Rails
* Experience in front end development with javascript, Angular
* Good knowledge of css, html
* Good knowledge of database and SQL, particularly MySQL
* Experience with source control (git, subversion…)

### Good to Have

* Eager to research and learn in a self-directed way to keep an eye on the major players in the industry. 

### You’ll be responsible for

* Be familiar with agile development, write high-quality, clean, simple, and maintainable code, build common libraries
* Develop functionality, according to product specifications
* Acquire good understanding of products, diagnose and fix problems
* Implement various supporting tools as required;
* Collaborate with other software engineers, product managers, user experience designers, and operation engineers to build new products.

### Why it would be awesome to work with us
* Laptop + 2nd monitor
* Competitive salary and attractive bonus
* Performance and salary review twice a year
* Parking allowance, snacks, and drinks
* Annual team-vacation trips
* An open and friendly working environment
* Team building activities

### Contact
Phu Nguyen: phu19677nguyen@gmail.com 
via CINQSMILE -  Full-stack Web Developer - Your full name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
