### ISSUE TITLE
[Remote Fulltime] Software Engineer (.Net Core) - MP Data

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#1782]
## Location

* Remote

## Salary Expectation

* From 1,500 USD (Open to negotiate)

## Requirements
* Strong knowledge of .NET web framework
* Proficient in C# with a good knowledge of their ecosystems
* Strong understanding of object-oriented programming
* Skill for writing reusable libraries
* Familiar with various design and architectural patterns
* Knowledge of concurrency patterns
* Familiarity with Microsoft SQL Server
* Familiarity with Azure Cloud Platform and Services
* Experience with popular web application frameworks
* Knack for writing clean, readable, and easily maintainable code
* Understanding of fundamental design principles for building a scalable application
* Experience creating database schemas that represent and support business processes
* Basic understanding of Common Language Runtime (CLR), its limitations, weaknesses, and workarounds
* Experience implementing automated testing platforms and unit tests
* Proficient understanding of code versioning tools (such as Git, SVN, and Mercurial)
* Bachelors/Masters degree in IT / Computer Science required
* Required language(s): English.

### You’ll be responsible for

* Translate application storyboards and use cases into functional applications
* Design, build, and maintain efficient, reusable, and reliable code
* Integrate data storage solutions
* Ensure the best possible performance, quality, and responsiveness of applications
* Identify bottlenecks and bugs, and devise solutions to mitigate and address these issues
* Help maintain code quality, organization, and automatization

### Why it would be awesome to work with us
* Working remotely with Technical team from Malaysia and Indonesia
* English working environment
* Product company, young and dynamic technical team
* Have a chance to work as data analyst role

### Contact
Ms. Tran: tran@ikonnectvn.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
