### ISSUE TITLE
Pixta Vietnam - Ruby Developer (All level) - Hanoi - Full Time

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#1783]
## Location

* Phung Chi Kien, Cau Giay, Hanoi, Vietnam

## Salary Expectation

* From 600$ to 2000$

## Job roles
* Develop TOP E-commerce platform for selling and buying licensed images, video… for Asian Market (pixtastock.com)
* Work with items flow (image, video…): modules building, image resize, item storage, automatic image review tool, new features development
* Solve problems related to system **scaling** (increase more than 30K items per day, database of 40,000,000 images & 1,300,000 users world wide)
* Break Mono into Micro-services
* Database **optimization**, cost optimization in AWS
* Directly work with oversea team (Thailand, Taiwan, Korea, Japan) 

## Requirements
* 1+ years of experience with web development
* Strong at one of the OOP language programming (Ruby, Python, Java, C++)
* Comfort working in a fast-paced environment and constantly revising assumptions in response to new requirements
* Detail oriented, self-awareness and a desire to continually improve
* Be familiar with Agile/Scrum development
* Possess English proficiency at working level
* Demonstrate self-learning skills, team work skills

## Our tech stack
* Programming language: Ruby, Python (Ruby training course is available)
* Frameworks/ Libraries: Ruby on Rails, ..
* Modern front-end framework: AngularJS, React…
* Database: Treasure Data, MySql, DynamoDB, SQL…
* Infrastructure (Amazon Web Services): Opsworks, EC2, S3, DynamoDB, Cloudsearch, Elastic
* Tools: GitHub, Trello, 

## Salary and career advancement
* Salary: 600$ ~ 2000$, review 2 times/year
* Bonus: up to 2 months end of year
* Room to show off your expertise, propose solutions to improve system by applying new * technologies
* Opportunity to rotate among teams, work onsite in Japan or oversea offices
* Coursera accounts and internal training courses
* Be listened, Be valued and Be recognized
* Environment: youthful, flexible & fast-growing business that encourages innovation, transparency and idea sharing

## Others
* Lunch allowance, free parking fee in building
* Full insurance, Bao Viet extra health care insurance
* Internal Activities: Code Camp, Code Contest, Company trip (Yearly), Company outing (Quarterly), * Clubs (Table tennis, photography, English, Japanese…)
* Annual leave: 12 days
* Facilities: Laptop, screen…

## Why it would be awesome to work with us
* Interesting engineering projects
* New technologies
* Collaborative, creative and youthful environment

### Contact
Fanpage: https://www.facebook.com/pixtaVN/
Website: https://pixta.vn/
Email: recruit.vn@pixta.co.jp

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
