### ISSUE TITLE
SSKPI - Senior Python Developer - Hanoi - FT 

### ISSUE THREAD

**Issue by xuanht2103** [awesome-jobs/vietnam#1784]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $1000 - $1500/month + bonus 

## Requirements
* Overall 3+ years experience in Python; Django
* Good knowledge of HTML; CSS; Javascript
* Experience with PostgreSQL; MongoDB
* Good knowledge of RestAPI; Socket.io
* Strong experience with GitFlow

### Must Have

* Work independently, proactively and creatively
* Ability to manage projects and teams with a size of 10 people or more
* Ability to quickly learn new technologies.

### Ideally

* Able to communicate in English 

### Responsibilities

* Develop API Server system for products based on Micro services;
* Develop Web Application, API Server;
* Building automatic integration systems, automatic testing;
* Project management with Scrum Agile model
* Other duties as required by management

### Why it would be awesome to work with us

- [x] **Career launcher**:

* Be exposed to a complete process of product development, not simply code. Implement outsourcing projects while simultaneously developing the core product - human resources management software.
* Be updated on latest technologies
* Be provided with a promising career path and opportunities to get promoted to Technical Lead, Project Manager,...
* Receive internal and external training: management and technical skills from leaders who are former talented CEOs, CTOs, PMs of both outsourcing companies and product companies

- [x] **Income boost**:

* $1000-1500/month with project reward and quarterly performance bonus
* Salary review conducted twice per year.

- [x] **Work-life balance**:

* Monthly team-building activities
* Creative culture
* Young & smart teammates
* Performance managed by target
* Flexible working time from Monday to Friday

### Interesting engineering projects
* Large-scale project, global market
* New technology 

### Contact
Website: [Link] (https://sskpi.com/)
Email: **xuanht@sskpi.com** (0966927446 - Ms. Ha Xuan)
Skype: **live:haxuan2103**

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
