### ISSUE TITLE
BAP Solutions_Senior Java Developer (Sign-on bonus) 

### ISSUE THREAD

**Issue by Nhunie** [awesome-jobs/vietnam#1786]
## Location

* Saigon, Vietnam
*  [Viettel Complex Building 285 CMT8 St, W12, D10, HCMC](https://www.google.com/maps/place/Viettel+Complex+Building/@10.7780439,106.6781763,17z/data=!3m1!4b1!4m5!3m4!1s0x31752f2639b32e09:0x97169d1fc37df0b6!8m2!3d10.7780386!4d106.680365)

## Salary Expectation
* $2000/month 

## This exciting position
* Contribute in all phases of the software development lifecycle
* Ensure designs are in compliance with specifications
* Write well design, testable, efficient source code
* Ensure the best possible performance, quality, and responsiveness of the applications
* Support continuous improvement by investigating alternatives and technologies and presenting these for architectural review

## Background
* At least 3 years experience of Java and 1 years of the Leader role
* Must be able to communicate English
* Experienced in developing Java backend API 
* Experienced in frameworks: Spring, Spring Boot
* Proficiency in Linux environment
* Have knowledge about EIP (Enterprise Integration Pattern)
* Have working experience in JPA (OpenJPA, Hibernate..)
* Worked in Web service (Restful service, SOAP Services)
* Strong problem-solving and analytical skills

## Why it would be awesome to work with us
* **Attractive salary up to $ 2,000** 
* 13th-month full salary
* Social insurance full package
* Computers of your choice (Macbook Pro or Window)
* International environment with colleagues from different countries (Vietnam, US, Japan, Australia, Malaysia,...)
* Opportunity to work with revolutionary blockchain technology

### Contact
Homepage: https://bap-solutions.com/ 
Skype: _**nhungnn.hip**_
Mail: nhungnn@bap-solutions.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
