### ISSUE TITLE
[Cốc Cốc] - [C++ Developer for Browser] - [HCM / HN] - [FT]

### ISSUE THREAD

**Issue by maiphuong712** [awesome-jobs/vietnam#1787]
## Responsibilities

* Work on the browser code to embed new and interesting solutions
* Change and improve the browser user interface
* Take part in developing new solutions and capabilities
* Integrate numerous fascinating and complex tasks into the browser core
* Work on revising and improving our features like downloader, torrents, media player, addtone, etc
* Implement solutions to make the browser more convenient for Vietnamese users
* Merge with the latest Chromium sources to keep the core up to date
* Improve the performance and stability of the browser, analyze crash reports and users’ feedback
* Work on multi-platform solutions to support different OS, including mobile
* Find alternative algorithms and approaches in order to solve problems, and give explanations of their benefits
* Help to support our users and solve their problems.

## Requirements
* Confident knowledge of C++ and STL
* Experience writing multi-threaded applications, using multi-threading and inter-process communication, synchronization primitives
* Ability to read (read a lot) and change somebody else's code
* Experience with MS Visual Studio and debugging tools for Windows
* Knowledge of SVN and GIT (preferable).

## Benefits
* Flexible working hours, 05 working days/1 week, no Over Time
* Remote work policy and casual clothes
* 13th-month bonus
* Trade Union benefits for staff and family: 5M VND for wedding, 5M VND for a new born child, 1M VND for birthday
* Annual leave: 12 days/year, bonus 0.5 days/a year of working
* Sick leave without Medical Certificate: 7 days/year
* Medical support (Medical Expenses): Diagnostic & Out-patient treatment: 12M/year, In-patient treatment: 12M/year, Pregnancy & Childbirth: 12M/year, Surgical operation & Hospitalization: 100%
* Doing great work with talented colleagues in the international working environment
* Participating in many exciting internal events: All-Hands Meeting, Happy Hour, Team-building, 08/03, 20/10, Men’s Day, X-mas, Year End Party ... to make you feel like home when working at Cốc Cốc
* Joining many interesting Hobby Clubs: Yoga, Bicycle, Painting, Board game...
* Modern and cozy kitchen with plenty of free noodles, coffee/tea bar and fresh fruits every day.

See more our jobs at: [Cốc Cốc Job List](http://bit.ly/CocCocJobList2019)
## Contact
* Working location:
- Ho Chi Minh: 3rd Floor, Block AB, 27B Nguyen Dinh Chieu, Da Kao Ward, District 1.
- Ha Noi: 16th Floor, HiTTC Building, 185 Giang Vo Street.
* Submit CV via email: job@coccoc.com
* Skype 1: maiphuong_712 (Ms. Mai Phương)
* Skype 2: jangin.kan (Ms. Giang Trịnh)
* Skype 3: phucnguyen2803 (Mr. Phúc Nguyễn)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
