### ISSUE TITLE
JourneyHorizon_RUBY ON RAILS_HCMC_FT

### ISSUE THREAD

**Issue by JHrecruit** [awesome-jobs/vietnam#1788]
## Location

* 5A/2 Tran Phu, Ward 4, District 5, HCMC, Vietnam
* Full-time

## Salary Expectation

* $1600/month 

## Requirements

* Ruby 2.6 +
* Ruby on Rails 5.1.1 +
* MySQL 5.7 +
* React + jQuery
* Node.js 7.8 (for compiling JavaScript assets)
* Kubernetes
* Amazon Web Services (EC2, DNS)
* Background job: delayed_job
* Gems:
* devise | Authentication
* omniauth-facebook | Third party login: Facebook
* haml and ERB | HTML templating
* mysql2 | MySQL library for Ruby
* paperclip | Image upload management
* passenger | Web application server
* react_on_rails | Integration of React + Webpack + Rails
* factory_girl, capybara, rspec-rails, cucumber-rails, selenium-webdriver | Testing

## Experience
[RUBY ON RAILS.pdf](https://github.com/awesome-jobs/vietnam/files/3822838/RUBY.ON.RAILS.pdf)

* Software Development in a team environment
* Source code control (git), pull requests, and code reviews
* Ability to connect to API’s, micro-services and other RESTFul services
* Ability to turn Photoshop, Sketch or Adobe XD design into pixel perfect UI
* Familiar with Trello and Slack or other teamwork/task management platforms is
a plus

### Why it would be awesome to work with us

* You will love the people you work with 
* High performing team
* Flexible work hours
* Premium health care
* Best gear
* 13th month bonus
* Opportunities to learn and grow
* Professional, dynamic working environment
* Free Parking
* Free Snacks
* Team drinks and parties
* Team t-shirts, water-bottles and backpacks
* Paid Birthday (don't work on your birthday...enjoy the day)

### Contact
Homepage: https://journeyh.io/
Skype: kate.hughes12
Email: success@journeyh.io

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
