### ISSUE TITLE
JourneyHorizon_DEVOPS LEAD_HCMC_FT

### ISSUE THREAD

**Issue by JHrecruit** [awesome-jobs/vietnam#1789]
## Location

* 5A/2 Tran Phu, Ward 4, District 5, HCMC, Vietnam
* Full-time

## Salary Expectation

* $1000 - $2000/month

## Requirements

We work with a wide range of exciting technologies and expect you to have worked with some of these in the past:

* Docker, Postgres, Kubernetes, Microservice architectures and continuous delivery.
Google cloud (Broad range of services), AWS, Azure or other cloud services a benefit.
* IaC - Terraform, Serverless, Github/Gitlab, CI/CD pipelines, Strong scripting/development, ideally with multiple languages such as Python, Bash, Node JS etc.
* Integration testing
* Experience deploying polyglot architecture.
* With 10 years IT background and 2-5 years hands-on experience as DevOps Engineer

### Ideally

* Experience with working in Agile development beneficial.

### Why it would be awesome to work with us

* You will love the people you work with
* High performing team
* Flexible work hours
* Premium health care
* Best gear
* 13th month bonus
* Opportunities to learn and grow
* Professional, dynamic working environment
* Free Parking
* Free Snacks
* Team drinks and parties
* Team t-shirts, water-bottles and backpacks
* Paid Birthday (don't work on your birthday...enjoy the day)

### Contact
Homepage: https://journeyh.io/
Skype: kate.hughes12
Email: success@journeyh.io
[Devops Lead.pdf](https://github.com/awesome-jobs/vietnam/files/3822854/Devops.Lead.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
