### ISSUE TITLE
JourneyHorizon_GOLANG DEVELOPER_HCMC_FT

### ISSUE THREAD

**Issue by JHrecruit** [awesome-jobs/vietnam#1790]
## Location

* 5A/2 Tran Phu, Ward 4, District 5, HCMC, Vietnam
* Full-time

## Salary Expectation

* $1000 - $2000/month

## Requirements

We work with a wide range of exciting technologies and expect you to have worked with some of these in the past:

* Experience developing RESTful web service API’s
* GRPC experience
* Strong technical background working in Google Cloud platform ​
* Container Experience – Docker and Kubernetes
* Microservice architectures
* 2-5 years experience in Golang 

### Ideally

* Experience working with Agile development is a plus

### Why it would be awesome to work with us

* You will love the people you work with
* High performing team
* Flexible work hours
* Premium health care
* Best gear
* 13th month bonus
* Opportunities to learn and grow
* Professional, dynamic working environment
* Free Parking
* Free Snacks
* Team drinks and parties
* Team t-shirts, water-bottles and backpacks
* Paid Birthday (don't work on your birthday...enjoy the day)

### Contact
Homepage: https://journeyh.io/
Skype: kate.hughes12
Email: success@journeyh.io
[GOLANG DEVELOPER.pdf](https://github.com/awesome-jobs/vietnam/files/3822873/GOLANG.DEVELOPER.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
