### ISSUE TITLE
JourneyHorizon_AUTOMATED TESTER_HCMC_FT

### ISSUE THREAD

**Issue by JHrecruit** [awesome-jobs/vietnam#1791]
## Location

* 5A/2 Tran Phu, Ward 4, District 5, HCMC, Vietnam
* Full-time

## Salary Expectation

* $500 - $2000/month

## Requirements

* 2-5 years experience
* All round testing experience and ability; including backend, database, API and
integration testing experience
* Experience in the preparation of Test plans, test scripts, test results, defect
reports and other test documentation
* Demonstrated experience working within cross-functional Agile teams
* Intermediate English or above

### You’ll be responsible for

* Define testing plan
* Define unit, integration and functional tests
* Build automated regression suites
* Produce test results documentation

### Why it would be awesome to work with us

* You will love the people you work with
* High performing team
* Flexible work hours
* Premium health care
* Best gear
* 13th month bonus
* Opportunities to learn and grow
* Professional, dynamic working environment
* Free Parking
* Free Snacks
* Team drinks and parties
* Team t-shirts, water-bottles and backpacks
* Paid Birthday (don't work on your birthday...enjoy the day)

### Contact
Homepage: https://journeyh.io/
Skype: kate.hughes12
Email: success@journeyh.io
[AUTOMATED TESTER.pdf](https://github.com/awesome-jobs/vietnam/files/3822890/AUTOMATED.TESTER.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
