### ISSUE TITLE
JourneyHorizon_Web-Mapping and Spatial Data Analysis Expert_HCMC_FT

### ISSUE THREAD

**Issue by JHrecruit** [awesome-jobs/vietnam#1792]
## Location

* 5A/2 Tran Phu, Ward 4, District 5, HCMC, Vietnam
* Full-time

## Salary Expectation

* $1000 - $2000/month

## Requirements

We work with a wide range of exciting technologies and expect you to have worked with some of these in the past:
* Fullstack web mapping, web and geospatial applications, backend data processing and analytics
* Demonstrated skills in core modern web development technologies and techniques;
* API development and continuous delivery;
* Knowledge of modern DevOps approaches such as containerisations and
infrastructure as code
* Demonstrated skills with RDBMS databases;
* Experience with cloud computing, specifically Google Cloud Services and
associated processes, systems and integration;
* Experience with the ESRI and Open Source GIS platforms highly regarded.
* 2-5 years experience

### Why it would be awesome to work with us

* You will love the people you work with
* High performing team
* Flexible work hours
* Premium health care
* Best gear
* 13th month bonus
* Opportunities to learn and grow
* Professional, dynamic working environment
* Free Parking
* Free Snacks
* Team drinks and parties
* Team t-shirts, water-bottles and backpacks
* Paid Birthday (don't work on your birthday...enjoy the day)

### Contact
Homepage: https://journeyh.io/
Skype: kate.hughes12
Email: success@journeyh.io
[Web-Mapping and Spatial Data Analysis Expert.pdf](https://github.com/awesome-jobs/vietnam/files/3822900/Web-Mapping.and.Spatial.Data.Analysis.Expert.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
