### ISSUE TITLE
[LINE - HCMC] Backend Engineer (Java Preferred)

### ISSUE THREAD

**Issue by phuongquach110** [awesome-jobs/vietnam#1794]
## Location

* Saigon, Vietnam
* 412 Nguyen Thi Minh Khai, Ward 6, Dist 3

## Salary Expectation

* $2000 to $3000

## Requirements

* Proven experience in Java / C,C++ developing language
* Proven experience in operating/structuring Big Data, Storage and Analysis System
* Understanding & experience in Data structure, Algorithm, Distributed Service
* Motivation to join LINE in new global challenges and build a success with LINE
* No problem with business trips overseas
* Communicate in English

## Responsibilities

* Architect and develop stable web service
* Software Engineer, Data: Big Data, Storage and Analysis
* Software Engineer, Service: Vietnam Contents Portal, LINE Family Service, E-commerce
* Rapidly build, iterate, test and deploy new features and products
* Maintain a high-quality robust codebase
* Manage and contribute code to large scale projects from inception to completion

### Why it would be awesome to work with us
We’re now developing our Dev Center in HCMC for business settlement in next few years. So we’re looking for BE, FE for several projects relating to portal (image recognition), computer vision, etc.

### Interesting engineering projects
For Line, as you may know, we’ve been expanding our eco-system based on Line community (~190mil MAU). Some typical product:
-	Clova AI:  https://clova.ai/techdemo
-	Blockchain:  https://www.bitbox.me/
-	And other products: e-wallet (Line Pay), e-commerce (Line Shopping), etc.

### Contact
Homepage: linecorp.com
Email: phuongquach@linecorp.com / Skype: +84938396624 (Phuong Quach)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
