### ISSUE TITLE
[Axon] - [Frontend Software Engineer, Maps] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1796]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your impact

As a frontend software engineer working on maps, you'll have an opportunity to work on a core component that spans across all of our applications and services. Your contributions will enable officers to respond to incidents faster, supervisors to be able to locate officers more quickly and respond to incidents, and video reviewers to have more context on where incidents are happening. Your day-to-day responsibilities will focus on building a set of shared mapping components, upgrading our existing map implementations using the new components, and improving features and workflows related to maps.

You will be focused on building new mapping features, testing them out, and applying them in real world, mission-critical situations. The ideal candidate for this role is someone who loves going deep when learning and mastering a new technology. You’ll have the opportunity to work with each of our product teams to ensure that the solution you are building meets their needs, and will be responsible for solving complex engineering problems. 

## Core Technologies Used:

• JavaScript
• Lerna
• Webpack
• Babel
• React + Redux
• Flow
• Jest + Enzyme
• PostCSS
• Interfacing with Scala and GO backend services

## Basic Qualifications

- 4 years of experience in frontend / full-stack software engineering
- Bachelor's degree or equivalent experience
- Ability to write clean and concise code
- Knowledge of CS fundamentals
- Basic understanding of frontend technologies
- Ability to work within an existing codebase
- Desire to continue learning and improving

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
