### ISSUE TITLE
[Axon] - [Senior Frontend Software Engineer, Evidence Viewing & Playback] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1797]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your impact

You are a Senior Frontend Software Engineer with experience building large-scale software applications. You have deep interest in frontend technologies. You are excited about the care, feeding and growth of a high-availability, scalable cloud-based systems.

Come work in an exciting environment where you use your passion, experience, and analytical skills to help bring new solutions to public safety and leave a positive impact on the world.

## Core Technologies Used:

• JavaScript
• Lerna
• Webpack
• Babel
• React + Redux
• Flow
• Jest + Enzyme
• PostCSS
• Interfacing with Scala and GO backend services

## Basic Qualifications

- 5+ years of experience in frontend / full-stack software engineering
- Ability to write clean and concise code
- Deep understanding of frontend technologies
- Ability to work within an existing codebase
- Good sense of design
- Knowledge of CS fundamentals
- Ability to explain core frontend principles and technologies to other engineers

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
