### ISSUE TITLE
[Axon] - [Senior Embedded Engineer - Linux - Jambo Delta] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1798]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your impact

Axon has specific “Delta Teams” that are focused on new opportunities, new products, and/or markets. The idea is to operate like fast startups. You will get to be a leader within the startup and work with the same pace and autonomy. This delta team is focused on some of the most important and critical growth opportunities for the company. The details of the project are not yet public information. However, the goal is to be creative, innovative, and autonomous like a start up. Focus for this team will touch all parts of the company from body cameras, to our digital evidence management system, to records, dispatch, and beyond.

We are searching for Senior Embedded Software Engineer to help us build high quality, reliable, and always-connected IoT devices for various users around the world.

## Core Technologies Used:

• Python
• C++
• Go
• Protobuf
• Tensorflow
• FFMPEG
• Yocto / Open-embedded
• Robot Test Framework
• CI/CD tools (Jenkins or TeamCity)

## Your Day to Day

- Develop solutions that deliver key awareness and communications outcomes to first responders
- Build robust management, telemetry, and security features to help Axon monitor the health of millions of devices worldwide
- Work with the product manager and the delta team leader in ensuring the product is of high quality and scalable.
- Guide the technical architecture of the solution

## Basic Qualifications

- 5+ year experience in developing and/or testing IoT applications
- Strong programming skills in C/C++, Python, Go, Rust, or equivalent
- Deep knowledge of unit testing, system testing, and integrating quality and test concepts into product engineering.
- Experience with at least 3 of the following: video playback, audio/video streaming, USB, Ethernet, wireless (BT, BLE, LTE, WiFi), IoT-Cloud-integration
- Ability to read schematics and understand electronic circuitry
- Ability to mentor junior engineers
- Excellent English

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
