### ISSUE TITLE
[Axon] - [Senior .NET Software Engineer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1799]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Day to Day

- Design, write, test and maintain .NET applications with web services and client components for Windows
- Develop infrastructure for enhancing automation, scalability, performance and robustness of the platform
- Assist in developing specifications and architecture design for application systems
- Prepare prototypes to evaluate technology choices for various applications and databases
- Track your own projects and clearly communicate status and risks in team meetings
- Monitor everyday activities of system and provide required support

## Basic Qualifications

- 5+ years of experience in software engineering
- .NET/C# expertise: LINQ, TPL, WPF, WinForms, Web Api, ADO.NET, Entity Framework
- SQL development (stored procedures, functions, tables, indices, optimizing queries, etc)
- Experience building complex and impactful software in a team environment
- Proven ability to quickly learn new technologies and passion for quality, innovation, and world-class design
- Problem solving, creativity, and communication skills are essential working with remote co-workers
- 

## Preferred Qualifications

- Experience designing and delivering high-availability, scalable cloud-based systems
- Familiarity in other languages like Java, Scala, Golang, React, Node.js
- Knowledge in creating and maintaining simple application installers, Windows services
- Experience in build and Continuous Integration tools/processes like MsBuild, TeamCity, FinalBuilder
- You have worn multiple technology hats, working on a variety of areas like back-end, front-end, client, mobile
- You have refactored aspects of a significant code base
- You enjoy mentoring and growing junior engineers

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
