### ISSUE TITLE
[Axon] - [Software Engineer (C/C++, GOLANG)] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1800]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Day to Day

- Implement new features for Axon’s camera devices.
- Work with engineers on a breadth of platforms including mobile & desktop applications as well backend services.
- Consider scale and security implications to new features that you develop.
- Monitor your features in devices after they are deployed to customers.

## Basic Qualifications

- 2+ years experience of professional software development in C/C++, Go or Rust
- 2+ years experience writing unit, integration and/or system level tests
- Understanding of Computer Science fundamentals in data structures, algorithms, run-time analysis, object-oriented design and code quality verification
- English working proficiency

## Preferred Qualifications

- Experience with RTOS and/or Embedded Linux development
- Experience with Yocto/Open-Embedded
- Experience with Python or equivalent
- Experience with Jenkins and/or other CI/CD systems
- Experience with Splunk and/or other data indexers
- Experience with audio, video, networking and/or security technologies
- Experience with Bluetooth, Wi-Fi and/or Cellular technologies
- Experience working with REST APIs, Thrift and/or Protocol Buffers
- Experience collaborating with design, product and non-technical partners

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
