### ISSUE TITLE
[Axon] - [Senior QA Manual Engineers] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1802]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Impact

Our team has responsibility to provide testing services for multiple projects. We are now searching multiple QA Engineers who have passion in testing, creative thinking, carefully and dare to challenge yourself.

Participate in planning, estimating and prioritizing processes to ensure successful execution of testing activities for all projects, you will help us continually improve the quality of our existing products.

## Your Day-to-Day

- You will work closely with our talented team in Vietnam and US which you will be assigned to:
- Review requirements, specifications and technical design documents to provide timely and impactful feedback
- Develop and execute a manual test strategy where appropriate
- Use exploratory testing techniques to discover and prevent issues
- Produce detailed reports documenting test results and process to be provided to the Product/Project Manager and QA Manager
- Track defects and issues using JIRA and participate in regular sprint and release planning sessions with the development team
- Implement and improve existing QA processes

## Basic Qualifications

- Have minimum 5 years’ experience in software testing across a wide variety of applications and infrastructure components, QA processes, test management and automated testing tools
- Solid understanding of software QA methodologies, tools and processes
- Ability to collaborate, make questions and communicate directly with colleagues in US
- Strong communication skills in English and Vietnamese
- A passion for quality

## Preferred Qualifications

- Experience in Automation testing (using Selenium or Appium) is a plus
- Programming skills (Java, python) is a plus

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
