### ISSUE TITLE
[Axon] - [Senior QA Automation Engineer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1803]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Impact

- You will be responsible for designing and delivering technology to measure and improve the quality and performance of the Axon Records platform, enabling the team to ship early and ship often with high confidence of customer satisfaction.
- By leveraging the latest technologies such as Gatling, Cucumber, and Cypress, combined with powerful internal frameworks, our QA code is embedded deeply into the engineering pipeline to catch faults and regressions as early as possible.
- You will be a key part of the engineering organization, participating in architecture and design reviews, product planning, and prioritization and resourcing decisions.
- At Axon, we have a passion for quality and drive our QA team to represent the customer in all aspects of their work. We also cultivate an environment that favors agility, initiative, and creative thinking. We wholly support engineers contributing back to the open source community where possible, and to help further the state of the art in their field.

Come work in an exciting environment and use your skills to leave a positive impact on the world.

## Your Day-to-Day

- Develop a risk-based test plan to determine the highest areas of risk in the product
- Engineer and execute performance and functional tests
- Focus on scale: Deliver solutions that can be quickly adapted to changing scenarios.
- Review requirements, specifications and technical design documents to provide timely and impactful feedback
- Leverage software to produce detailed reports documenting test results and process to be provided to the engineering team.
- Champion the quality process through all stages of the product.

## Basic Qualifications

- A minimum of 4 years experience in software testing across a wide variety of applications and infrastructure components, QA processes, test management and automated testing tools
- Excellent programming skills and flexibility with a variety of frameworks.
- You write clean, maintainable, well-documented code.
- Solid understanding of software QA methodologies, tools and processes
- Ability to collaborate and communicate directly with colleagues in US
- Strong communication skills in English and Vietnamese
- A passion for quality

## Preferred Qualifications

- Experience in Automation and Performance Testing using a variety of tools.
- Python, Java, or Scala programming experience
- Strong Linux/Unix/Mac experience. 

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
