### ISSUE TITLE
[Axon] - [QA Manager] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1804]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Our Product

We are building Axon Records, a brand new cloud-based web application that will eliminate tedious paperwork, save time, save lives, and make the job of police officers more fulfilling. Over time, Axon Records will evolve into a family of law enforcement tools designed to make our communities safer.

## Your Impact

- You will be leading the team responsible for measuring the quality and performance of the Axon Records and Axon Standards platform. With your leadership and guidance, your talented team of manual testers and automation engineers will be a key part of enabling us to ship product early and often with high confidence and high customer satisfaction.
- The Axon Records QA team consists of a mix of talented manual testers and creative automation engineers who balance their skills to best analyze and mitigate risk areas of our software product. As the QA Engineering Manager, you will ensure that we focus on the right aspects of product quality at the right time. Your leadership will help the QA, Product, and Engineering organizations align on common goals for quality and customer acceptance making sure our customers have a great experience with our products.
- You will be a key part of the engineering organization, participating in architecture and design reviews, product planning, and prioritization and resourcing decisions.
- At Axon, we have a passion for quality and drive our QA team to represent the customer in all aspects of their work. We also cultivate an environment that favors agility, initiative, and creative thinking. We wholly support engineers contributing back to the open source community where possible, and to help further the state of the art in their field.

Come work in an exciting environment and use your skills to leave a positive impact on the world.

## Your Day-to-Day

- Manage a team of manual testers and automation engineers to investigate and measure quality of the Axon Records product across a variety of criteria.
- Develop a risk-based test plan to determine the highest areas of risk in the product
- Lead and mentor employees
- Focus on scale: Deliver solutions that can be quickly adapted to changing scenarios.
- Review requirements, specifications and technical design documents to provide timely and impactful feedback
- Represent the customer in all aspects of product quality.
- Produce detailed reports documenting test results and process to be provided to the engineering team.
- Empower your team to drive for results independently.
- Champion the quality process through all stages of the product.

## Basic Qualifications

- A minimum of 4 years experience in software testing across a wide variety of applications and infrastructure components, QA processes, test management and automated testing tools.
- Management experience
- Excellent programming skills and flexibility with a variety of frameworks.
- The ability to mentor engineers and provide guidance on technical decisions.
- Solid understanding of software QA methodologies, tools and processes
- Ability to collaborate and communicate directly with colleagues in US
- Strong communication skills in English and Vietnamese
- A passion for quality

## Preferred Qualifications

- Strong knowledge of Automation and Performance Testing using a variety of tools.
- Experience dealing with geographically separate teams and complex software products
- Excellent written and spoken English.

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
