### ISSUE TITLE
[Axon] - [QA Manual Engineer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1805]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Day-to-day

- You will work closely with our talented team in Vietnam and US which you will be assigned to:
- Review requirements, specifications and technical design documents to provide timely and impactful feedback
- Develop and execute a manual test strategy where appropriate
- Use exploratory testing techniques to discover and prevent issues
- Produce detailed reports documenting test results and process to be provided to the Product/Project Manager and QA Manager
- Track defects and issues using JIRA and participate in regular sprint and release planning sessions with the development team
- Implement and improve existing QA processes

## Basic Qualifications

- Have 1-5 years of experience in manual testing
- Solid understanding of software QA methodologies, tools and processes
- Ability to collaborate, make questions and communicate directly with colleagues in US.
- Comfortable with Linux, MacOS, Windows
- Strong communication skills in English and Vietnamese.

## Preferred Qualifications

- Experience in API testing (using SoapUI, Postman or similar)
- Experience in Automation testing (using Selenium or Appium) is a plus
- Programming skills (Java, python) is a plus
- Familiarity with version control, bug tracking (Jira), and CI / CD systems (Teamcity or Jenkins).

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
