### ISSUE TITLE
[Axon] - [QA Automation Engineer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1806]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Day-to-day

- Develop automation test framework to increase the test coverage for end to end test, smoke test, functional test and regression test
- Execute manual testing when we have any issue in the development process
- Provide the solutions and experience to improve the quality process
- Handle CI/CD tools like Teamcity or Jenkins

## Basic Qualifications

- Have 1-5 years of experience in automation testing
- Experience in scripting like bash shell
- Experience in UI test automation tools (Selenium WebDriver, Spectron, Appium, Espresso or similar), API testing (using SoapUI, Postman or similar)
- Familiarity with version control, bug tracking (Jira), CI/CD systems (Teamcity or Jenkins) and procedures
- Comfortable with Linux, MacOS, Windows
- Strong communication skills in English and Vietnamese

## Preferred Qualifications

- Experience in Python
- Experience with Scala or Golang or Ruby
- Experience in Saucelabs
- Experience with Cucumber

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
