### ISSUE TITLE
Avatech -Junior Back-end Developer (Golang) - Saigon - FT

### ISSUE THREAD

**Issue by vinhle7859** [awesome-jobs/vietnam#1807]
## Location
* Nguyen Huu Canh, W.22, Binh Thanh Dis, HCMC 

## Salary Expectation
* Negotiable

## Requirements
* Golang
* From 6 months to 2 years' experience with Golang (Accept for them freshers who want to learn about Golang) 
* Abilities work as group or individuals 
* Excellence Logical Thinking skill, Problem-Solving

### Ideally
* Good at English is a Plus

### You’ll be responsible for

* Dealing and report tasks directly to CTO. 
* Build & develop supporting functions and new functions for the company's Back-end
* Learn how to build from the ground up when there is nothing to complete the project, and contribute directly built for running product with over 2 million transactions / day 
* Collaborate with Front-end teams to ensure the best end-user experience
* Develop and cultivate new skills, languages and frameworks as needed to support the work.

### Why it would be awesome to work with us
* Salary review twice a year, increase at least 10%, the highest increase is not limited if you excel (6 months performance review 1 time).
* Tet bonuses and 13th salary.
* You are guaranteed to develop a career and skills development at the company
* 100% international customers (Come from Southeast Asia, Asia,etc.) 
* The products make customers run officially and have good sales.
* Working hours is from Monday - Friday (9:00 am - 6:00 pm). No OT.

### Contact
Apply CV via: huyvinh785@gmail.com
=> Subject: Avatech - Golang - Your Name

![IMG_0822](https://user-images.githubusercontent.com/44989679/68652280-b086ab80-055b-11ea-801f-b5fd80ff6f39.png)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
