### ISSUE TITLE
[Axon] - [Senior Backend Software Engineer - Spitfire] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by AxonVietnam** [awesome-jobs/vietnam#1811]
## Location

* 8th floor, Etown Central, 11 Doan Van Bo, Ward 12, District 4, HCMC

### About Axon
**Our mission is to protect life.**
We’re out to make the world a safer place by solving big problems and taking on the public safety challenges of our time. From our company's inception building the TASER device to a full suite of hardware and software solutions, we are focused on providing police agencies with the state-of-the-art devices and services they need to successfully serve and protect us. In the next few years, we're going to eliminate the burden of paperwork in policing, so officers can increase the time they spend building relationships and serving in their communities. We’ll put video at the heart of the police record so our justice system can get to the truth faster. And we won't stop innovating until the bullet is rendered obsolete.

It’s a big mission, but it’s one we’ll pursue relentlessly every single day. 

## Your Mission

10 years ago, Axon changed the world with a groundbreaking police body camera and cloud platform (Evidence.com) that would change how the police captured and managed video evidence and public interactions. Today, Axon's Evidence.com is the premier digital evidence management solution in law enforcement. With over 30 petabytes of data, and growing at 3 petabytes per month, this data represents an important part of the law enforcement process.

Our Platform Technology Squad (nicknamed Spitfire) is the bridge that makes all of this happen. This team is building scalable data storage systems that enable us to quickly share information with police agencies across the world leads to better policing, faster response times, and better public safety. To give back to the community, Platform squad also makes numerous open source contributions to give back to the community.

Your mission: Leverage advanced technology to change the way policing is done.

## Your Day to Day

- Responsible for delivering our core micro-service platform architecture and design, data systems and patterns (Kafka, NoSQL), implementing core technologies such as Kubernetes
- Solve hard problems around data storage and management for the massive volume of video evidence and metadata
- Help mentor for junior engineers

## Basic Qualifications

- Degree in Computer Science, Electrical Engineering, or related field
- Have 5+ years' experience in a modern backend language such as Java, Go, C#, or similar
- You have made tough technical decisions based on requirements, trade-offs, and user experience
- You write well-tested code with good unit tests and technical documents
- You are comfortable with a lot of autonomy
- High performance messaging using Protobuf, Thrift
- Enjoy mentoring junior engineers

## Preferred Qualifications

- You love working on technology that empowers others to do their best work
- Background in DevOps or distributed systems is a plus
- Experience working with Kubernetes, Service Mesh, Docker...

## Why it would be awesome to work with us

- An awesome office/working environment with the latest technologies
- Competitive salary and benefits including a great medical insurance plan for you and your family
- Free lunch, gym, phone stipend, parking
- Fun team activities and outings
- Flexible working hours
- Opportunities for training in the US
- Opportunities to ride along with real US police officers in real life situations, see them use our technology, and get inspired

### Contact
Homepage: axon.com/careers
Email: recruitingvn@axon.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
