### ISSUE TITLE
Acuity - Senior Full Stack Software Engineer (Ruby/Elixir) - Onsite/Remote - FT

### ISSUE THREAD

**Issue by acuityengineers** [awesome-jobs/vietnam#1813]
## Location

* HCMC, Vietnam
* Remote

## Salary Expectation

* `>=` 4000+ SGD

## Requirements

* Design and build reliable trading software platform primarily in Ruby, Ruby on Rails, Elixir and Javascript
* Willing to learn Elixir/Phoenix 
* Maintain clean and human-readable software artifacts with unit testing
* Participate in periodic code review sessions
* Communicate with team members effectively, both written and verbally

## Skills
* 2+ years of experience with Ruby, Ruby on Rails
* Experience working with concurrent web application.
* Experience with Relational Databases and SQL
* Understand concurrency and parallelism concept

### NICE TO HAVE

* Exposure to Elixir is preferred
* Exposure to NodeJS and/or Ruby is preferred
* Experience with ReactJS would be a plus

### TECHNOLOGIES WE USE
* Elixir, Javascript, Ruby
* Vue.js, Ruby on Rails
* PostgreSQL, Redis
* Heroku, AWS
* Sentry, Slack, Gitlab, Trello

### Contact
Homepage: https://www.acuity.sg
Send your CV to this email with the subject title as [Elixir Engineer]: long@acuity.sg

**Comment by trungkien1503** [comment]
@acuityengineers I just send my CV to your email, please check if this position is still open. Thanks

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
