### ISSUE TITLE
[KVY Tech] Ruby/Python Developer - HCMC - FT

### ISSUE THREAD

**Issue by HungNguyenKVY** [awesome-jobs/vietnam#1815]
We need a kickass developer with proficiency in Ruby and/or Python programming languages.

You will get the freedom and trust to work with autonomy from anywhere in the world. The platform we are building will have real impact.

## Location

* Saigon, Vietnam

## Salary Expectation
* Negotiable

## Desire skills
* Proficient in Ruby programming language or similar
* Commercial experience with web frameworks such as Ruby on Rails
* Commercial experience with event sourced systems is a huge plus
* Good grasp of Object Orientated Design principles
* Solid approach to testing
* Commercial experience working with Relational DB's such as PostgresSQL
* Experience working with AWS is a plus
* Good at English communication

### What you will be doing

* Innovating and contributing to a platform for auditing, analysing and controlling energy consumption
* Providing technical leadership for a growing team
* Writing clean, well thought out and reliable code
* Participating as a member of a small cross functional team containing members with different skills and experience

### Technologies we use

* Ruby, Javascript, NodeJs, Elixir
* Rails, Spree, Phoenix
* PostgreSQL, MongoDB
* Heroku, AWS, Google Cloud Platform
* Rollbar, NewRelic, Github, Slack, Trello, Jira

### Perks you Enjoy

* Working & Developing with Passionate & Talented Team
* Internationally remote friendly & out of the box thinking
* Grow your skills in state of the art technologies
* Competitive salary package & performance bonus
* Mon-Fri (9 a.m -6 p.m), flexible and up to 5 remote working days per month
* Company events: year-end party every year, team building, etc.
* Free in-house entertainment facilities (foosball, boardgame…), tea, coffee, juice & snack

### Contact
Homepage: https://kvytechnology.com
Email: hung@kvytechnology.com
Email subject: [Ruby/Python Developer] - Your name

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
