### ISSUE TITLE
Tripla - Rails Engineer - Hanoi

### ISSUE THREAD

**Issue by Vinh0305** [awesome-jobs/vietnam#1818]
## Location

* Hanoi, Vietnam

## Salary Expectation
* Minimum: $2000

## Requirements
- Possess a good understanding of the syntax of Ruby and its nuances 
- Experience designing, building large-scale Ruby on Rails applications 
- Experience in building APIs for client facing-apps in Ruby on Rails 
- Experience in creating and maintaining scalable infrastructure leveraging modern AWS products like RDS, ElastiCache, Dynamo DB and others 
- Basic familiarity with networking systems, load balancers, and TCP/IP network constructs. 
- Experience in building micro service structure 

### Must Have
- Passion for always improving (yourself, the app, the company, etc.) 
- Ownership: You feel responsible for creating an excellent, end-to-end platform that supports the needs of our users. 
- Comfort with data: you know when you don't know enough to make a design decision, and you seek out answers. 
- An interest in exploration: you think about what to build now and what to build in 
the future. 

### You’ll be responsible for
We are looking for a Ruby on Rails developer responsible for managing the interchange of data between the server and the users. Your primary focus will be development of all server-side logic, definition and maintenance of the central database, developing micro services to support the rapid growth of services and ensuring high performance and responsiveness to requests from the front-end. You will also be responsible for integrating the front-end elements built by your co-workers into the application. 

### Why it would be awesome to work with us
- Flexible working time
- Coworking space fee
- Play as the very first member of our new team in Vietnam (means a lot of opportunities to clear our challenges and thrive)
- Newest Macbook 13" + external monitor
- Japanese holidays + substitute holidays + 8 paid leaves

### Contact
Homepage: tripla.ai
Skype: vinhtt0305@gmail.com

**Comment by zoegod911** [comment]
@Vinh0305 I am interested: techniquea2z@protonmail.com

**Comment by Vinh0305** [comment]
@zoegod911 Hi, I cannot reach you via that SkypeID, could you add me?
Skype: vinhtt0305@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
