### ISSUE TITLE
FullStack Dev - Remote - Full time - $500 - $4000

### ISSUE THREAD

**Issue by ngocphuong39** [awesome-jobs/vietnam#1820]
## Location
* Vietnam
* Remote

## Salary Expectation

* $500 - $4000/month 

## Requirements
* Ruby
* ReactJS
* React Native 
* Giải Thuật 

### Benefits

* MacbookPro 
* Health Insurance - Vinmec Premium.
* The 13th-month Salary.
* Full Salary during probation time.
* Review Salary every year.

### Company: Remitano 

*Remitano was established in 2015 by Babylon Solutions Limited at Seychelles when cryptocurrency was entirely new to the community. After more than 4 years, Remitano is proud to be one of the largest peer-to-peer cryptocurrencies trading platform in Vietnam, where people can buy and sell Bitcoin, Ethereum, Bitcoin Cash, Litecoin, USTD, Ripple. Currently, Remitano has services in many countries, including Australia, Malaysia, Nigeria, Cambodia, India,... 

Joining in Remitano, you can work online anywhere. Besides,  you can quickly learn new things from your global colleagues who are professional, enthusiastic, and responsible. Living in Remitano culture, you have a golden opportunity to take a challenge and develop yourself.

### Contact 

Facebook: https://www.facebook.com/phuongnguyen39bd
Gmail: phuongnguyen39bd@gmail.com
Phone: 0986 376 343

**Comment by trungkien1503** [comment]
@ngocphuong39 Is this position still open?

**Comment by camnguyenitepu** [comment]
@ngocphuong39 Is this still open?

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
