### ISSUE TITLE
LendoChat - Software Engineering Lead - Ho Chi Minh city - FT

### ISSUE THREAD

**Issue by Marusya101** [awesome-jobs/vietnam#1821]
## Location

* Ho Chi Minh city, Vietnam

## Salary Expectation

* $1500 - $2000/month

## Requirements
* at least 3 years of experience with the required stack of technologies
* understanding of modern JavaScript Full-Stack development technologies
* TypeScript and ES 7+.
* PostgreSQL, Redis, Tarantool, ClickHouse, MongoDB.
* APIs (ReSTFull, gRPC, SOAP, WebSocket)
* BackEnd Framework: KOA, ExpressJS (with TypeScript).
* React, Redux, Ant Design, SASS, Socket.IO (with TypeScript).
* GitLab CI (pipeline, docker).
* Testing tools: MochaJS, Jasmine, Jest.

### Must Have

* Proficiency in written and spoken English
* Being a good communicator and a team player

### Responsibilities

* Responsible for developing software applications
* Able to read and understand technical specifications
* Implement the application in compliance with established software quality standards of the company and perform unit testing
* Participate in design/code review
* Write technical specifications with support from technical architecture

### You’ll be responsible for

* Building a chat-platform for the hospitality industry to ease communication between hotels and their foreign guests

### Why it would be awesome to work with us

* LendoChat is a fast-growing startup in the field of hospitality. We've been successfully operating on the Far East and Russian markets and now actively expanding to SEA markets. We are looking to form a team in Vietnam to make it a development center for all our growth and customer care activities for our clients all over the world. You are a good fit if you have some interest in the hospitality and travel fields, enjoy working in a multinational environment, enjoy challenges and solving new problems. 
* Trips to different locations within Vietnam
* Trips to industry events to other countries
* Time Off events

### Contact
Homepage: https://lendo.chat/
Marina Usenko: m.usenko@lendohotel.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
