### ISSUE TITLE
Schola - Senior Fullstack/Lead Engineer - Saigon - FT

### ISSUE THREAD

**Issue by ThuTrangAnn** [awesome-jobs/vietnam#1822]
## Location

* Ho Chi Minh, Vietnam

## Salary Expectation

* Upto $2,000/month

## Requirements
* Java
* MongoDB
* MySQL
* DART/Kotlin (good to have)
* AWS/ Google Cloud
* 3+ years Software Engineering experience

### Must Have
* Passion for always improving (yourself, the app, the company, etc.)
* Ownership: You feel responsible for creating an excellent, end-to-end platform that supports the needs of our users.
* Excellent communication skills - both written and verbal. 
* Ability to break down tasks for managing timeline.
* Train junior engineers as needed.
* Understand experimentation approach to building world-class products. 

### You'll be responsible for

You will have the opportunity to work with a great team of founders and team members to change the education system in Vietnam and Asia. You will build state of the art education web and mobile educational products ensuring the platform and infrastructure is built to scale. World with company wide stake holders to deliver excellent technology solutions for customer and business needs. The system is built on micro-services architecture with Java for the server and react/flutter front-end.

### Why it would be awesome to work with us
* World class team of ex-Facebook product manager and business teams
* Learn important skills of building products through experimentation. How biggest products are built in USA.
* You will be a core part of the company's success and can be compensated with equity.
* We are funded by American investors like 500 Startups and also top Vietnamese investors, including Shark Binh.
* Besides the office perks and fun environment are amazing.
* New product development

### Contact
Email: recruiting@schola.tv
Founder email: adityag@schola.tv (Aditya Gupta - ex Facebook Product Manager)
Homepage: https://schola.tv/
FB: https://facebook.com/scholakids

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
