### ISSUE TITLE
Fetch Technology- C#/dotNET Developer - Saigon - FT

### ISSUE THREAD

**Issue by laciefetch** [awesome-jobs/vietnam#1823]
## Location

* Ho Ba Phan, District 9, Ho Chi Minh City, Vietnam
* FT

## Salary Expectation

* $500 - $1700

## Requirements
* > 2 years experience in C# and .NET Technologies.
* Proficient in .NET (Framework/Core).
* Domain Driven Design, SOLID Principles and Clean Architecture.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc
* Experience in both SQL and NoSQL solutions.
* HTML, CSS, Javascript. ReactJS preferred.
* Keen on communication and able to work as a team.

### Responsibilities

* Take ownership of business services (backend API Microservices).
* Constantly improving our services with new technologies and work closely with business team to grow these services.
* If you are someone who love to continually improve and takes pride in your code. This is definitely for you!

### Why it would be awesome to work with us

Being a Software Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Email: lacie@fetch.tech
Skype: lacie.soul12

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
