### ISSUE TITLE
Magnolia Vietnam - Middle/Sr Java Developer - SaiGon - FT

### ISSUE THREAD

**Issue by ngtu828** [awesome-jobs/vietnam#1824]
## Location

* Etown Building, 364 Cong Hoa St., Ward 13, Tan Binh Dist, Ho Chi Minh City, Vietnam

## Salary Expectation

* $1500 - $2400 NET/month

## Requirements
* Education: Bachelor of IT or equivalent
* Language: Intermediate English (good in all skills, especially writing and communicating)
* Strong knowledge in JAVA-web technologies (filter chains/servlet/jsp/EJB/REST), system design, technical troubleshooting, and problem-solving

### Must Have

* Strong knowledge in Java Web & Enterprise (EE) technologies, system design, technical troubleshooting, and problem-solving
Servlet API, JAX-RS (REST), JSON-P; Apache Tomcat, JBoss AS/Wildfly, etc.
* Java SE 8 (lambdas, streams, interface evolution), APT, Lombok, Groovy, JUnit 4 and 5, Mockito, Hamcrest matchers
* Experienced in IoC (Spring Framework or Google Guice) and service design Templating (Freemarker, Handlebars, Velocity)
* Rapid application & UI development frameworks (Vaadin, SpringBoot), Sass, JavaScript
* Strong in database design and programming (MySQL, H2), as a plus, JCR 2.0 (Java Content Repository), Jackrabbit, Lucene
* Experience with Maven, Git, CI/CD, Jenkins Pipelines, Docker, Selenium
* Knowledge of cloud based development is a plus
* Experienced in open-source solutions such as CMS, CRM, E-commerce, Portal, and social networks is a plus
* Solid soft skills: group discussion leading, teamwork, problem-solving, presentations
* Must be independent, responsible, and self-motivated with the ability to learn and achieve superior results
* Possessing strong methodologies when researching new technologies

### Ideally

* Knowledge of cloud based development is a plus
* Skilled in Liferay, CQ5, JIVE, Tapestry 5, and Lucene is a plus
* Experienced in open-source solutions such as CMS (Hybris, Magnolia), Portal, and social networks is a plus
* Experience with Google Web Toolkit and Vaadin is a plus
* Experience with MySQL database is preferable

### Responsibilities

We are looking for awesome people to join the Magnolia-CMS team in Vietnam. Our team members reflect the character of our CMS through a flexible, friendly, and open culture that is both inspiring, fun, and filled with challenges

### You’ll be responsible for

* You will work as a Senior Java Developer on web-based application projects in JAVA-related and open-source technologies
* Analyze system requirements
* Participate in system design and implementation
* Perform as a key member in technical problem resolution on projects under experienced team leaders
* Play the role of a team leader managing a small number of developers on specific projects

### Why it would be awesome to work with us
Life at Magnolia Vietnam

* Our core value is our people. We define it through our employees’ happiness and success.

PERSONAL ENHANCEMENT
 
* To motivate individual employee improvement to achieve a higher level of success and joy, we offer learning opportunities for ongoing career. 
 * Upon committing, we provide you with our indoor/outdoor training activities such as technical courses, English classes, soft skills training, football, swimming, bowling, cinema and a lot more.

PERSONAL AND FAMILY PREMIUM HEALTH CARE
 
* Taking care of employees is our central concern. It goes along with the Magnolia culture and our family atmosphere.
* Covers 100% of all employees’ and their dependents’ healthcare premiums, meaning you can claim up to thousands of dollars a year for medical expenditure.

EMPLOYEE FAMILY CARE
 
* At Magnolia, we really look out for our employees and their families by offering health insurance, organizing summer vacations and events like Family Day, Children's day and Mid-autumn festival, when we hand out presents for the employees’ children.

SALARY AND COMPENSATION

* Our recognition scheme is designed to appreciate and value your efforts through a very attractive salary, 13th month salary, seniority bonus (1 month bonus in 3rd year, 2 months bonus in 5th year and day-off)
* Flexible working time
* Regular exchange program to Switzerland for 2 weeks at a time, twice a year
* Annual leave of up to 16 days
* Stylish office, equipped with a 15” Macbook Pro and 27” Apple Thunderbolt Display for each employee

YOU ARE PAID FOR EVERYTHING
 
* It’s a part of our overall strategy, since our culture and our people are extremely valued and important to us. We keep a refrigerator fully stocked with beers, soft drinks, fruits and snacks. Meals every evening, especially on Whoopie Fridays when we can meet, chat, exchange knowledge – and a whole lot more team building activities.

This tempting now-or-never opportunity is open now. Wait no more to become a fellow Magnolian and work with us on a cutting-edge CMS product!

### Contact
Contact
Email: linh.nguyenlethao@magnolia-cms.com
Or skype: thaolinh.nguyenle
Website: https://www.magnolia-cms.com/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
