### ISSUE TITLE
Magnolia Vietnam - (Sr.) DevOps Engineer - SaiGon - FT

### ISSUE THREAD

**Issue by ngtu828** [awesome-jobs/vietnam#1825]
## Location

* Etown Building, 364 Cong Hoa St., Ward 13, Tan Binh Dist, Ho Chi Minh City, Vietnam

## Salary Expectation

* $1500 - $2800 NET/month

## Requirements
* Strong background in Linux/Unix Administration and scripting using shell scripts
* Experience with automation/configuration management using either Ansible, Puppet, Chef or an equivalent
* Ability to use a wide variety of open source technologies and cloud services (experience with AWS is mandatory)
* Strong experience with SQL and MySQL
* Relevant working experiences of code and script (Python, Perl and/or Ruby)
* Knowledge of best practices and IT operations in an always-up, always-available service
* Demonstrated experience in enterprise network administration and troubleshooting/analysis (DNS, IPsec VPN, BGP, Load Balancing)
* Proven expertise in virtualization, experience with Vagrant
* Additional knowledge in other Cloud Platforms preferable, aka: Google Cloud Platform, IBM Bluemix, Cloud Foundry, etc.
* An upper english level is required as you will evolve in an international environment (good in all skills, especially in writing and communicating).
* Having the ability to clearly understand and focus on business outcomes is a real additional value.

### Must Have

* An upper english level is required as you will evolve in an international environment (good in all skills, especially in writing and communicating).
* Strong background in Linux/Unix Administration and scripting using shell scripts
* Experience with automation/configuration management using either Ansible, Puppet, Chef or an equivalent
* Ability to use a wide variety of open source technologies and cloud services (experience with AWS is mandatory)
* Strong experience with SQL and MySQL
* Relevant working experiences of code and script (Python, Perl and/or Ruby)

### Ideally

* Experience with 

### Responsibilities

Magnolia Cloud Platform is an agile, enterprise-grade CMS delivered as a convenient cloud-based service.
Entirely developed in our production center in Vietnam, we are looking for DevOps engineers with strong Amazon Cloud computing experience.

### You’ll be responsible for

* As a DevOps Engineer, you will be part of a team to build AWS cloud architecture for our Java applications, delivering products as PaaS.
* You'll define and manage cloud infrastructure as code (IAC), improve CI/CD pipeline, ensure scalability and availability of the system, build monitoring stack, automate build, configuration and deployment orchestration scripts, ...
* You can also participate in developing Java and Python applications & services for our cloud platform.
* We're utilizing a broad toolset for DevOps/Infra like Terraform, Packer, Ansible, Vagrant, Jenkins, Grafana, ... and leveraging multiple services from AWS: EC2, S3, RDS, ACM, Route53, CloudWatch

### Why it would be awesome to work with us
Life at Magnolia Vietnam

* Our core value is our people. We define it through our employees’ happiness and success.

PERSONAL ENHANCEMENT
 
* To motivate individual employee improvement to achieve a higher level of success and joy, we offer learning opportunities for ongoing career. 
* Upon committing, we provide you with our indoor/outdoor training activities such as technical courses, English classes, soft skills training, football, swimming, bowling, cinema and a lot more.

PERSONAL AND FAMILY PREMIUM HEALTH CARE
 
* Taking care of employees is our central concern. It goes along with the Magnolia culture and our family atmosphere.
* Covers 100% of all employees’ and their dependents’ healthcare premiums, meaning you can claim up to thousands of dollars a year for medical expenditure.

EMPLOYEE FAMILY CARE
 
* At Magnolia, we really look out for our employees and their families by offering health insurance, organizing summer vacations and events like Family Day, Children's day and Mid-autumn festival, when we hand out presents for the employees’ children.

SALARY AND COMPENSATION

* Our recognition scheme is designed to appreciate and value your efforts through a very attractive salary, 13th month salary, seniority bonus (1 month bonus in 3rd year, 2 months bonus in 5th year and day-off)
* Flexible working time
* Regular exchange program to Switzerland for 2 weeks at a time, twice a year
* Annual leave of up to 16 days
* Stylish office, equipped with a 15” Macbook Pro and 27” Apple Thunderbolt Display for each employee

YOU ARE PAID FOR EVERYTHING
 
* It’s a part of our overall strategy, since our culture and our people are extremely valued and important to us. We keep a refrigerator fully stocked with beers, soft drinks, fruits and snacks. Meals every evening, especially on Whoopie Fridays when we can meet, chat, exchange knowledge – and a whole lot more team building activities.

This tempting now-or-never opportunity is open now. Wait no more to become a fellow Magnolian and work with us on a cutting-edge CMS product!

### Contact
Email: linh.nguyenlethao@magnolia-cms.com
Or skype: thaolinh.nguyenle
Website: https://www.magnolia-cms.com/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
