### ISSUE TITLE
Inapps Technology - Mobile (React Native) Engineer

### ISSUE THREAD

**Issue by UniqueNguyen** [awesome-jobs/vietnam#1826]
## Location
288 Phạm Văn Hai, Tân Bình District
* Saigon, Vietnam
* Fulltime

## Salary Expectation

*** $1200-2000/month**
*** offer share
*** offer % revenue of project

## Requirements
2+ years of experience working with Native iOS + Android OR React Native 
Has ‘CAN-DO’ attitude
Good English skill is a plus
Experience working in SCRUM methodology
Proficient in the mobile app development process from designing to deploying to Apple Store / Google Play Store.
Must be the self-starter, proactive and willing to learn and grow with the business.
Ability to work well under pressure and manage multiple tasks simultaneously.
Strong problem-solving skills
Familiar with using common third-party libraries.

## Skills
Develop features and maintain mobile apps using Native iOS + Android OR React Native
Collaborate with UI/UX team to design future versions
Work closely with Product Manager & Engineering teams and other stakeholders to deeply understand customer’s problems, business & product requirements
Be up-to-date and knowledgeable about mobile development technologies and methodologies.
Analyze problems and implement appropriate technical solutions

### Why it would be awesome to work with us
Attractive income + bonus
Have the chances to work with various products
Team building
Support parking fee
Support lunch
13th-month salary
And other benefits
### Contact:
skype: thuynguyen2486
Email: thuy.nguyen@inapps.net
Homepage: https://www.inapps.net/inapps-job/senior-mobile-developer/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
