### ISSUE TITLE
IMA - Full-stack Developer (Silicon Valley startups)

### ISSUE THREAD

**Issue by hung-phan** [awesome-jobs/vietnam#1827]
## Location

* Remote

## Salary Expectation

* $3000++

## Requirements
- Good programming skills with NodeJS, React. - Deeply understand non blocking asynchronous programming - Experienced in designing performance, caching techniques, system scaling, real 
time application - Being serious about code quality, familiar with unit testing - Have been working with TDD is a plus. - Interested in Machine Learning.

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

- Backend: 
	- Web server: Nodejs
- Database: MongoDB
- Server: Google Cloud
- Frontend: 
	- Front end Architecture: React- Redux - Redux-Sagas 

### Responsibilities

IMI is a healthcare tech startup founded by Stanford and UCSF alumni. We’re looking for an experienced full-stack developer with good engineer background to join our team. Ideal candidate would be someone who loves the startup culture and is self-motivated. You will have the opportunity to work closely with an amazing team that has a diverse background in web development, medical domain, and machine learning. 
Our goal is to build a good system and interface for doctors to manage and read patients’ medical records easily while being able to provide quick feedback, comments, and annotations on top of the medical records. The candidate is expected to be able to learn from an existing codebase and extend its functionalities. We also expect the candidate to manage time well, can break work into small tasks, and be proactive in finding solutions. 

### Contact
IMI AI Inc. https://imi.ai/ Contact: wendy@imi.ai

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
