### ISSUE TITLE
Transimex (A Total Logistics Provider) - dotNET developer - Saigon - FT

### ISSUE THREAD

**Issue by ngantran1611** [awesome-jobs/vietnam#1828]
# About us

**Transimex Corporation** is a leading global logistics service provider in Vietnam that is able to meet every customer's needs. We provide complete logistics solutions from inland transportation, ocean shipping and air freight to warehousing, distribution and customs services. With more than 30 years of experience in the field of freight forwarding combined with modern infrastructure, **cutting-edge technology** and professional services enable us to provide an efficient supply chain to all our customers.

# Location

Head office: 172 (Floor 9th-10th) Hai Ba Trung Str., Đakao Ward, District. 1, HCM city, Vietnam

# Compensation

From **$600 - $800** (depends on your experience)

# Why our compensation is not so **"beefy"**?

Our company is **A TOTAL LOGISTIC PROVIDER**. This means we focus on Logistics related things, and IT department will play a crucial role in boosting our workflow efficiency and effectiveness by developing more features. Our workload is not as intensive as compared to a Software-focused companies; however tasks will be complex and challenging enough to keep you interested in your work.

<br>We will describe what you will be in charge of right below

# Job description
- Support users on a daily basis to ensure proper usage of softwares in managerial tasks throughout the company.
- Solve problem and develop more features or contact software provider to solve unexpected software problem based on ISO process.
- Learn the process relating to the software that Transimex is using and deploying
- Build property management software using **.NET framework, C# and SQL server**.
- Back up software database periodically.
- Send weekly, periodically, and on-demand report to direct manager or Head of HR department.
- Execute other tasks as delegated by your direct manager and head of HR department.

# What we expect from you?
- A college degree with major in Information Technology
- Have at least 1 year experience as a dotNET developer and familiar working with SQL Server.
- Good communication skill.
- Good at working individually and in team.
- We also expect you to be a meticulous, energetic, enthusiastic, wise, agile and professional partner.
- It would be great if it is you consider Transimex as a long-term workplace.

# Why it would be great to work with us?
- Our reputation as a prestigious **Total Logistics Provider** has long been established in the Logistics market (~36 years). Therefore, if you are looking for **a stable work for a stable life development**, Transimex is your ideal destination.
- If you happen to learn new language and/or new technologies during your working period with us, we are glad to support. We consider it is our responsibility to help our employee grow both in their career and personal life.
- Not only is training limited to technical skills, it is open to soft skills as well. In general, we provide training assistance as your demand.
- Our success has long been built on a **WIN WIN** relationship with all the stakeholder.

# Contact information
- Homepage: [Transimex](http://transimex.com.vn)
- Apply by sending your CV via the email: **hrs2@transimex.com.vn**
- Or call directly at our hotline: 0838 63 83 93 (Mr. Phúc Như)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
