### ISSUE TITLE
8 Bit Rockstars - Senior Front End Developer - Saigon - FT

### ISSUE THREAD

**Issue by 8BIT-ROCKSTARS** [awesome-jobs/vietnam#183]
![8BR](http://8bitrockr.com/img/logo_w.png)
# 8 BIT ROCKSTARS
Floor 8th, Vincom B, 72 Le Thanh Ton, Ben Nghe Ward, Dist.1, HCMC
http://8bitrockr.com/
hr@8bitrockr.com

#### Salary: Up to 2.000 USD /month
Email CV to: **_hr@8bitrockr.com_**

## About us

• **8 Bit Rockstars** is part of the global NFQ enterprise that began in 2000 in Germany and spans Europe, Vietnam, and Singapore.
• We empower successful international startups, large websites and highly scaled applications worldwide.
• We have 15 years of experience in building high-performing teams out of Europe. Currently over 250 NFQ engineers accelerate the success of various high profile startups worldwide including leading US websites like KAYAK.com.
• 8 Bit Rockstars is the nation's coolest agile tech firm, specializing in PHP, and one of the leaders in utilizing Elasticsearch.

## Job Description

We are looking for people who can work well independently and love to be part of a team. 

• **Rockstar** - Join our Rockstars team to truly become Front End Rockstar
• **Fun** - Join a young and dynamic team in an international, professional and English speaking working environment
• **Tech Rockstar** - Apply the latest technology like ReactJs, AngularJs, ES6/7 etc...
• **Exciting Projects** - Working with oversea clients and awesome projects 
• **Experience** - Use your experience to building great Web-Apps
• **Problem Solver** - Ability to find answers through researching and reading documentation

**Who will you work with?**

• You will be working with international clients on very interesting products. This is not the standard corporate website job but high load, complex projects which require dedication, skill and that you put your heart into the job. This is an excellent opportunity to gain experience, deliver happiness, and push your technical boundaries.
• In this role you will work directly with international clients to scale and maintain one of their sites using technology such as: Symfony2, Elasticsearch, Laravel, Drupal, Memcached, RabbitMQ, AngularJS, React, React native and much more. If you are experienced in any of these technologies or have knowledge in something similar please mention that in your cover letter.

 
### Skill and experience:

• Positive attitude, responsible and proactive with the ability to learn and achieve superior results.
• Strong communication skills in English, verbal and written
• 4+ year experience in working with front-end projects - **MUST**
• Proficient at Javascript library and framework (React / Angular / Ember / Backbone, and jQuery) - **MUST**
• Excellent at HTML, HTML5, CSS, CSS3
• Good knowledge of CSS preprocessors (i.e. Less / Sass)
• Excellent with CSS frameworks like Bootstrap / Foundation
• Proficient understanding of cross-browser compatibility issues and solving them
• Working experience with Git / SVN
• Experience working with a team and deadlines
• Strong teamwork and contribution spirit
• Understanding of continuous integration
• Experience with Agile methodology (Scrum)
• Having good leadership skills and attention to details
• Open-minded and good at adapting to frequent changes
• Willing to learn new technologies while working

### Big Plus

•	PHP framework (Symfony / Laravel / Zend)
•	Good understanding of SEO principles
•	Coding conventions
•	CMS (Drupal / Wordpress)
•	Restful APIs
•	MySQL, NoSQL

### What We Can Offer

• Oportunity to grow and learn from other talented individuals. 
• Opportunities to work with International Experts and cool startup entrepreneurs
• Work as a member in fun, fast-paced, and friendly team
• Very fun and friendly colleagues, global and professional working environment
• Modern office in District 1 with entertainment zone, relax area, coffee bar, etc.

8 Bit Rockstars has been featured in Tech in Asia and e27. 

### Benefits include:
• Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things
• Attractive, **competitive salary** and incentives
• Year end **bonus** (13th month salary ++)
• 40 hour work weeks (9:00-18:00, Mon-Fri)
• **15 days** of vacation per year
• **Probation** with **100% of salary**
• Performance and **salary review** every **6 months**
• **International Medical Insurance** will be paid by the company
• **English Class** with foreigner 3 times a week.
• New **Technologies Club** every week
• Quarterly **rockstar Hackathon** with the Best prizes
• Short and long-term **international training** / work
• **Company trip** (local or internationally) every year
• **Team building events**, party monthly and much more
• **Entertainment Zone** for all members with full media in company (game, music, TV…).
• Enjoy **Relax and Coffee Bar** in company.

Email CV to: **_hr@8bitrockr.com_**

**Comment by joneslee85** [comment]
Thanks for using our board. I hope that this post actually brought you the right candidate. If so, please help spread the word for us.
