### ISSUE TITLE
TenPoint7- Senior Fullstack (Python/Node.js/ ROR/Java)

### ISSUE THREAD

**Issue by Phuoc1904** [awesome-jobs/vietnam#1830]
## Location
* Saigon, Vietnam
* Full-time
## Salary Expectation
* $2000 - $3000 (or Negotiate).
## Requirements
- Bachelor of Science degree in computer science,
- 5+ years of experience in web application development,
- 2+ years of experience building and leading teams, managing projects, and providing clarity and transparency on project status to all stakeholders,
- Very good verbal and written English language with strong communication skills.
## Skills
- Frontend skills: Javascript (React), HTML5, CSS.
- Backend skills: Know at least one of these languages: Python, Node.Js, Java, and SQL (MySQL/Postgres).
- Experience with AWS is preferred.
### Must Have
*  Has extensive experience designing and building web application base on React, Redux, D3, Flask (Python), and many others. Experience developing and maintaining a commercial quality B2B SaaS platform is highly preferred as well as involvement on AWS.
(Amazon Web Services) or Microsoft Azure.
### You’ll be responsible for
- Define, develop, and maintain the TenPoint7 Cloud platform,
- Lead activities to gather, analyze, and document project functional requirements,
- Define epics, user stories, tasks, and subtasks for projects,
- Design and develop new features for the SaaS platform,
- Maintain and enhance existing features of the SaaS platform,
- Create unit tests, perform unit testing and fix bugs,
- Assist in project management responsibilities including scope, schedule, issues and risks,
- Help validate that solutions meet requirements and service/quality level agreements,
- Communicate project status to team members,
- Mentor junior team members,
- Maintain quality standards of excellence and ensure compliance with TenPoint7 delivery standards and best practices,

### Why it would be awesome to work with us
- Competitive salary, bonus on 13th month,
- Paid premium healthcare,
- Using and improving English every day,
- No limit on your career development, we take excellent care of our talents,
- Two days off per week,15 days of annual leave per year,
- 1-2 paid trips to company HQ in Seattle, Washington,
- Company trip, team building every year,
- Happy hours with free snacks, soft drinks, fruit, and coffee etc,
- Celebrating party: team lunch, birthday, welcome, other activities.
### Contact
Email: phuoc@tenpoint7.com
Skype: Phuoc Nguyen (phuoc@tenpoint7.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
