### ISSUE TITLE
Orange Logic - Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by hanguyenOL** [awesome-jobs/vietnam#1831]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2000 - $3000 (or Negotiate)

## Requirements

* Proficiency with English, both verbal and written
* A strong fundamental understanding of software development.
* An understanding of complex algorithms and data structures, as well as a passion for intellectual challenges.

## Skills

* Backend skills: Know at least one of these languages: Python, .Net, Java, Ruby
* Practical experience on a web-based application is a plus
* Experience with the database management tool SQL is a plus, but not mandatory.

### Must Have

* Strong self-discipline for delivering well-tested, complete features/modules under a tight schedule and the capability for rational thinking.

### You’ll be responsible for

* Taking ownership of projects and having the opportunity to further your knowledge by exploring web application developing, machine learning, security, DevOps, and more.
* Developing scalable new features for our software product that exceeds our customer’s needs.
* Building architecture for our platform to ensure optimal performance.
* Obtaining requirement feedback from internal teams/clients to maintain/support product development.
* Write the Unit Tests for robust development.
* Performing code reviews on other team member’s work.

### Why it would be awesome to work with us

* There is no upper limit on how much you can earn. It’s all based on your performance and contributions.
* Amazing team: smart, energetic, open-mind, hard-working and passionate engineers. They came from the US, France, UK, and Vietnam hence you could improve your English and explore different country cultures
* 18 days of annual leave per year + 4 days for an abroad company trip (Taiwan, Thailand, etc)
* 13th-month salary no matter when you join the team
* Monthly team outing activity
* Premium personal healthcare insurance
* SHUI based on your full Gross salary
* Allowances for lunch, gym, parking, etc
* Gyms, fitness, and sports: Extra dollars in your pocket to spend on your own fitness, swimming, running
* Birthday bonus
* Daily free snacks, soft drinks, fruit, and coffee
* Latest gadgets for work 

### Contact
Homepage: 
Email: ha.nguyen@orangelogic.com
Skype: Ha Nguyen (ha.nguyen@orangelogic.com)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
