### ISSUE TITLE
Truly Scaled - Senior Python 3 Developer - Remote - FT C

### ISSUE THREAD

**Issue by tguillemaud** [awesome-jobs/vietnam#1833]
## Why work with us?

Are you sick of working inefficiently on boring projects within bureaucratic office environments?  Are you exceptionally motivated and want to do something uncommon on your terms?

Today, we generate 110+ million pageviews/month to our websites and foresee this figure to be 200+ million by the end of 2019. In other words, be ready for a challenge!

You’ll be working remotely (from your home, a cafe, etc.) for a lean high-growth (300% per year) online media company that embraces flexibility in your work schedule. Since our ambitions to grow match your own, you’ll have a significant say in your career direction for years to come.

Let's together engineer a new gold standard for remote working. Let’s get rid of outmoded ideas and empower you to take your abilities to an entirely new level.

We need you to work on the customization, deployment, and maintenance of two in-house products.  The ultimate goal of this initiative is to significantly improve website load times and ad revenue and to prepare us for continuously optimizing our high-traffic websites. 

You will work directly with our motivated and organized lead Senior Python developer.

Be ready for a challenge!

## Location

* Remote
* Saigon, Vietnam

## Salary Expectation

* From $2000/month

## Requirements

* 6+ years of Python web application development
* Google Cloud Platform technologies
* Write cats and dogs in your application so we know you read this
* Processing and analysis of data
* Ability to take high-level instruction and turn it into functional software

### Must Have

We seek a results-oriented doer who can serve as a core team member of our app development team.

* Exceptionally disciplined, trustworthy, and organized
* Deep interest in learning new things
* Works smart - through focused prioritization - and loves technology
* High IQ - you will be tested!
* Articulate, with excellent spoken and written English
* Highly detail-oriented and proactive problem solver

### Ideal soft skills

* Honesty, discretion, and transparency
* Strong communication skills in English with all levels in and outside of our company
* Exceptional reliability and commitment - we offer the same in return!
* Tactful, diplomatic, and sensitive to other cultures - our team is distributed around the globe

### You’ll be responsible for customizing, deploying and maintaining:

* A Python-based campaign analytics and automation tool
* A Python-based CMS hosted on Google Cloud Platform

### Why it would be awesome to work with us

* Monthly compensation negotiable based on experience
* Paid time off for all full-timers
* Location and schedule flexibility (you can work from anywhere in the world)
* Annual performance-based bonuses (paid at beginning-of-year)
* Annual compensation increases as you grow with Truly Scaled
* Company-sponsored team meet-ups in different parts of the world!

### Contact

* [Homepage](https://trulyscaled.com/)
* [Click here to apply](https://jobs.trulyscaled.com/o/remote-senior-python-developer/?source=GitHub)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
