### ISSUE TITLE
VIG - Data Engineer - Saigon - FT

### ISSUE THREAD

**Issue by Vietnam-Investment-Group** [awesome-jobs/vietnam#1834]
## Location
* Centec Tower, Dist. 3, Saigon, Vietnam

## General
We are a next-generation marketing and payment mobile platform that connects leading brands with consumers through a simple-to-use, fully integrated and data-driven coalition loyalty program. Our solution enables consumers to earn and burn loyalty points conveniently, while using other value-add features such as payment solutions. We are operating a nation-wide merchant network that reaches 30% of the Vietnamese consumers, covering a wide range of industries (retail, F&B, entertainment, education, etc.)

We are looking for a Data Engineer to develop the code, pipeline and infrastructure that extracts, processes and prepares data generated by our CRM, loyalty app, payment solutions, and other sources. You will also have the opportunity to work on analytics, developing dashboards and visualization to get insights from our rich data sets.

If you are passionate about building big data solutions, solving hard problems in creative ways, join us and be part of this exciting start-up journey!

## Requirements
* Python/Java
* A degree or higher in Computer Science, Software Engineering, Information Technology or other related technical disciplines.
* At least 3 years of experience in handling large data sets (multiple TBs) and working with structured, unstructured and geographical datasets. 
* Deep understanding of databases and best engineering practices - include handling and logging errors, monitoring the system, building human-fault-tolerant pipelines, understanding how to scale up, addressing continuous integration, knowledge of database administration, maintaining data cleaning and ensuring a deterministic pipeline.
* Excellent communication skills.
* Entrepreneurial mindset with a high tolerance for ambiguity and just-do-it attitude.

## You’ll be responsible for
* Assemble large, complex data sets from existing sources (extensive CRM, loyalty app, payment, etc.) 
* Build out scalable and reliable ETL pipelines and processes to ingest data from a large number and variety of data sources.
* Plan, create, coordinate, and deploy data warehouses.
* Support the development and validation required through the lifecycle of the DWH and Business Intelligence systems, maintain user connectivity, and provide adequate security for data warehouse.
* Monitor the DWH and BI systems performance and integrity provide corrective and preventative maintenance as required.
* Maintain and optimize the performance of our data analytics infrastructure to ensure accurate, reliable and timely delivery of key insights for decision making.
* Create data tools for analytics and data scientist team members that assist them in building and optimizing our product into an innovative industry leader.
* Develop reporting dashboards to support brands in tracking business metrics effectively.

## Contact
Email: ha.v.ho_at_vigroup_dot_com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
