### ISSUE TITLE
VIG - Senior Java Developer - Saigon - FT

### ISSUE THREAD

**Issue by Vietnam-Investment-Group** [awesome-jobs/vietnam#1835]
## Location
Centec Tower, Dist. 3, Saigon, Vietnam

## General
We are a next-generation marketing and payment platform that connects market-leading brands with consumers through a simple-to-use, fully integrated and data-driven coalition loyalty program. Our solution enables consumers to earn and burn loyalty points conveniently by interacting and transacting with the brands of their choices across nation-wide merchant network that today reaches 30% of the Vietnamese consumers. Our goal is to revolutionize the omni-channel shopping experience in Vietnam and set the standards for how brands should engage their customers by leveraging data to drive consumer insights, marketing efficiency and product personalization. We also offer technology solution to help established businesses enhance their existing loyalty programs with access to a broad, diversified portfolio of brands and rewards.

## Requirements
* Bachelor degree in IT and other related fields;
* At least 3+ years of programming experience with Java-based technologies (Java, J2EE, Hibernate, Spring Framework) and OOP.
* Experience with Spring Data Rest (Restful), Web services integration (SOAP, REST, Websocket, etc.).
* Strong experience in Java 1.8 and above, Spring Boot Framework, Spring Data Rest Framework, Spring Security, and Spring Cloud
* Experience with one or multi-application servers: Tomcat/JBoss/WebLogic
* Experience with design patterns and data modeling.
* Familiar with one of the followings: Java CDI, JAX-WS, JDBC
* Be able to work on Linux OS
* Great motivation and willingness to learn new technologies.

## Responsibilities
* Develop mission-critical distributed applications for a broad range of clients and industries, using state-of-the-art tools and agile methodologies.
* Work closely with business analysts and software architects to design reliable, secure and highly efficient systems; participate directly in technical decisions.
* Be actively involved in the complete project lifecycle, from requirements analysis to final delivery.
* Contribute to knowledge sharing and continuous improvement activities.

### You’ll be responsible for
* Implement applications with large scale commercial quality
* Adheres to programming conventions and good programming practices
* Design, develop and execute unit tests
* Collaborate with a professional team through Scrum meeting every day
* Adheres to strict delivery schedules
* Experience in Java/J2EE,  Microservices Framework, Spring Framework, Hibernate, with a good knowledge of its ecosystems
* A strong sense of ownership and responsibility for code quality that follows best practices
* Being active in the open source community is a plus

### Contact
Email: ha.v.ho_at_vigroup_dot_com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
