### ISSUE TITLE
Quoine / Liquid - DevOps Engineers - Saigon - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1836]
# Location

* D.1, Saigon, Vietnam

#### We’re looking for experienced DevOps Engineers in our Saigon office that are responsible for the deployment and maintenance of our global cloud-based cryptocurrency exchanges.  

# Responsibility 

#### Your responsibilities incorporate but not limited to the followings:

* Deploy, automate, maintain and manage AWS cloud based production system, to ensure the availability, performance, scalability and security of productions systems.
* Build, release and configuration management of production systems.
* Pre-production Acceptance Testing to help assure the quality of our products / services.
* Be responsible for system troubleshooting and problem solving across platform and application domains.
* Recommend architecture improvements, process improvements.
* Evaluate new technology options and vendor products. 
* Ensure critical system security through the use of best in class cloud security solutions.

# Requirement

* AWS: 2+ years’ experience with using a broad range of AWS technologies (e.g.: EC2, RDS, ELB, EBD, S3, VPC, Glacier, IAM, CloudWatch, KMS) to develop and maintain an Amazon AWS based cloud solution, with an emphasis on best practice cloud security.
* DevOps: Solid experience as a DevOps Engineer in a 24x7 uptime Amazon AWS environment, including experience with infrastructure scaling and release management platforms such as Heroku
* Scripting Skills: Strong scripting (e.g. Bash, Python) and automation skills.
* Operating Systems: Linux system administration.
* Monitoring Tools: Experience with system monitoring tools (e.g. Nagios, Prometheus, etc.).
* Problem Solving: Ability to analyze and resolve complex infrastructure resource and application deployment issues.
* Professional commitment to high quality, and a passion for learning new skills.
* Detail-oriented individual with the ability to rapidly learn new concepts and technologies.
* Ability to work in a fast past multicultural 24/7 environment

## Nice to have

* DB Skills: Basic DB administration experience, Postgres, etc.
* Agile Methodologies: Experience with Agile software development, project management methodologies and tools such as Confluence and Jira
* Version Control: Experience administrating version control systems using Git, Gitflow, Githu, etc. 
* Networking: Understanding network topologies and common network protocols and services (DNS, HTTP(S), SSH, FTP, SMTP).
* Container technologies: Kubernetes, Docker (for senior role)
* Familiar with CI/CD development practice (Jenkins)
* Security mind-set
* Conversational and written English

# Why it would be awesome to work with us?
 
* Bring cutting-edge technologies into play
* Expose yourself to a multicultural workplace
* Capable candidates get competitive packages
* Enjoy exceptional benefits package (tech/non-tech training programs, extra health insurance for you and your immediate family, daily snack, billiards competition, football weekly... you name it.)
* Work in one of the most modern & innovative spaces in town

# Contact

* Homepage: https://careers.liquid.com/
* E: linh.truong@quoine.com 
* M: 0938 019 369
* Skype: linh.truong.my

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
