### ISSUE TITLE
Junior Front end dev - ReactJS.  - Saigon or Remote. 

### ISSUE THREAD

**Issue by jketts** [awesome-jobs/vietnam#1837]
## Location
Circo, Ho Chi Minh City, District 4, Vietnam

#### Or  work remotely
If you prefer!

## Start date
The sooner the better :)

## Salary Expectation
* $800 - $1500 / month USD

### WHAT YOUR DAY TO DAY WILL BE LIKE: 

* Full Time office based environment (if onsite)
*  Working with our Saigon based team of back-end, full-stacks, designers and dev-ops to continuously deploy improved front end code.
*  Ensuring responsiveness of applications. 
*  Understanding and implementation of security and data protection from DOS, Cross site and injection attacks.
*  Seeing through each project from Alpha and Beta to finished product with continuous integration and delivery. 
* Daily standups with Saigon and Singapore teams
*  Staying abreast of developments in web applications and programming languages. 

#### Must Have
* Experience with fundamental front end stack - principally ReactJS, Redux, Typescript, CSS, SASS.
* Proficiency with server side languages - Node.js
* Experience with any database technology (MongoDB, MySQL, PostgresQL). 
* Knowledge of code versioning with Git.
* Good problem solving skills and attention to detail. 

#### Additional skills which would be awesome (but are not required):
* Familiarity with materialUI design a plus.
* Familiarity in creating and deploying API servers using Flask/Django in Python. 
* Familiarity with GraphQL a plus.
* Familiarity with JSS.
* Familiarity with Apollo a plus.
* Experience with AWS a plus
* Experience with Jenkins (or other CI/CD framework) a plus
* Good command of written English.

### Why it would be awesome to work with us
* Full social insurance and income tax coverage according to Vietnam Labor Law (if in HCM)
* Work with international companies
* Opportunity to travel for work
* 13th month salary bonus 
* Attractive salary based on skill and experience 
* Yearly salary review based on performance 
* Work out of a luxurious co-work community space in District 4 Ho Chi Minh City if desired.

### Contact
Homepage: https://staple.io
Contact: josh@staple.io

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
