### ISSUE TITLE
Grab - Business Process Automation Integration Team Manager - HCMC - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1839]
## Location
* Saigon, Vietnam
* MapleTree, 1060 Nguyen Van Linh Str., Tan Phong Ward, District 7, HCMC

## Salary Expectation

* **Unlimited Salary Package (Depend on your abilities)**

### Must Have

* Strong understanding of software development life cycle, continuous integration and delivery methodologies.
* Be familiar with networking topology, Linux OS, mainstream middle ware/db engines/virtualization technologies.
* **Experience working with JavaScript and/or Python.**
* Full proficiency with Git.
* Strong communication, interpersonal and stakeholder management skills.
* Strong English (especially spoken English) is a must.
* Experience of managing full life-cycle of App publishing; Build, Test and Release process of web applications.
* **4+ years experience in software development.**
* University Graduate, in Computer Science or if not, multiple years of work experience programming JavaScript.

## You’ll be responsible for
* Manage the Automation Integration team, ensure the core infrastructure of the BPA team runs smoothly and supports all needed features for automation efforts.
* Continuously improve the BPA team core infrastructure while also supporting automation projects that require Integration team support.
* Coordinate with the other team managers and Process Improvement team to ensure core infrastructure features meet or exceed existing or new requirements.
* Architect new websites, internal systems and/or browser automation hacks in coordination with the other Team Leads and stakeholders to ensure operations automation needs are met.
* Develop automated tests, perform code review for team members to ensure quality releases under time constraints.
* Maintaining the team’s AWS cluster, daily problem solving, precaution formulation, performance optimization, etc.
* Design & implement ops supporting systems, including but not limited to deployment system, monitoring system, CI tools, etc.
* Investigate tools and processes and integrate them so that they can improve the reliability, stability and efficiency with which we release our apps and services.
* Continuous improvement of the automation release process.

## Why it would be awesome to work with us
* A culture of learning
* Free rides with Grab
* Medical coverage. Extra Medical Insurance.
* **MacBook** is provided.
* 14 days annual leaves.
* Diverse teams & high growth opportunities
* Weekly Tech talks & quarterly Hackathons
* **Flexible working hours**

### Contact
* Homepage: https://grab.careers/
* Email: **_cuong.vo0906@gmail.com_** 
* Subjects: **_Your Position_Your Name_**
![Manager](https://user-images.githubusercontent.com/39041308/70680774-d4105380-1ccb-11ea-9b1c-9418f9e5ddd0.jpg)

**Comment by qcam** [comment]
We have received report claiming this post is a scam.
