### ISSUE TITLE
[Larion] - [Senior Ruby on Rails Developer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#1840]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 1200$ - 2500$

### Interesting engineering projects

You will join to develop and operate an attractive and efficient E-Commerce solution which
* Support multiple interfaces: Web, Android app, iOS app
* Span multiple countries around SEA and more in the future
* Back by data-driven intelligent engine

## Requirements

* At least 2 years of experience in Ruby on Rails development
* Experience with file system, cloud storage, network resources
* Experience with normalized relational model and non-relational data stores
* Solid understanding of object-oriented programming
* English: Intermediate level or above

### Responsibilities

* Work with product team to develop functional and technical software requirements
* Design, build, maintain efficient, reusable and reliable code
* Contribute in all phases of the development life-cycle
* Drive continuous adoption and integration of relevant new technologies into design
* Conduct code refactoring, optimization
* Maintain and operate live production system

### Why it would be awesome to work with us
* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the
year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Will be provided MacBook Pro, Onsite working opportunity
* Various training on technical and soft skills, Teambuilding, Company trip, Year-end
party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.

### Contact
Homepage: https://larion.com/careers/all-open-jobs/ruby-on-rails-developer/
Email: recruitment@larion.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
