### ISSUE TITLE
AhaMove - Android Developer - SaiGon - FT

### ISSUE THREAD

**Issue by duongnhi126** [awesome-jobs/vietnam#1841]
## Location

- Saigon, Vietnam
- Rivera Park, Thanh Thai Str., District 10, HCMC

## Salary Expectation

* 1000 - 2000 USD/month

## Requirements
* Bachelor’s degree in Computer Science, Software Engineering, or related field with 3+ years’ experience in Android development.  
* Intense knowledge of `Java`, `Kotlin`, REST and JSON
* Deep knowledge of Google’s Android SDK framework, Android Jetpack Compose 
*  Expert in Android platform development and IDE such as Android Studio
* Worked on location-based applications is a plus 
* Significant hands-on experience with Fragments, Intents, networking, real –time 
    large catalog management, real-time threads driven app  
* Hands-on experienced with localization methodology, strategy, and delivered at least 
    one verifiable app deployed internationally  
* Understanding of the full mobile development life cycle  
* Experience with consumer facing UI development  
* Unit-test code and UI test for robustness 

## Responsibilities

We need to add a Senior Android Software Engineer to our team. This is an excellent opportunity to be responsible for the architecture design, development and maintenance of AhaMove Android applications - ensuring that the applications are created and deployed in a timely fashion and maintained to a high quality and in accordance with the AhaMove procedures and systems. 

### You’ll be responsible for
- Develop, maintain, document and release the AhaMove app for Android-based phones
- For assigned projects, take overall responsibility for delivering the product to production; including requirements generation, documentation, regulatory testing and Agile release requirements. It is expected that projects should be managed with minimal supervision.
## Must Have:
* 3+ years’ experience in Android development.  
* Intense knowledge of Java, Kotlin, REST and JSON
## Why it would be awesome to work with us
* Disruptive innovations   
* People-oriented philosophy of doing business  
* Your footprint on regional on-demand market  
* Sharp, motivated colleagues in a fun office environment  
* Competitive salaries and benefits according to experience and education level
* 13th salary, Performance bonus, PVI Care
* Comfortable Private working Area for TECH team
* Team-building, Outing trip Join Training Courses and Tech Sharing Mid-Autumn Party, Christmas Party, Year-end Party 
* Sports club: football, badminton
### Interesting Engineering Projects:
* The architecture design
* Google Maps, Location 
### Contact
Email: nhidnl1212@gmail.com
Subjects: Your Position_Your Name
Skype live:nhidnl1212_1
![18140_ahamove](https://user-images.githubusercontent.com/58930688/70890202-0cd76200-2017-11ea-9bb8-2ec451f7110b.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
