### ISSUE TITLE
Scommerce - Data Engineer

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#1842]
Salary Expectation
$2000 to $3000

RESPONSIBILITIES:

- Develop methods to unlock access to data for stakeholders across the Partnerships Organization
- Design, build and launch efficient & reliable data pipelines to move and transform data (both large and small amounts) 
- Optimize and maintain existing pipelines, ensuring that data arrives accurately and on-time
- Build and ensure data tables can serve as the source of truth for various high-level priorities 
- Create scripts to automate operational processes
- Work cross-functionally to define problem statements, collect data, and make recommendations 
- Build data expertise and own data quality for allocated areas of ownership
- Define and manage SLA for all data sets in allocated areas of ownership 
- Work with data infrastructure to triage infra issues and drive to resolution
- Support on-call shift as needed to support the team

REQUIREMENTS:

- BS/BTech in Computer Science, Math or related field 3+ years experience in the data warehouse space
- 3+ years experience in custom `ETL/data` pipeline design, implementation and maintenance
- 3+ years of SQL (Oracle, Vertica, Hive, etc.) or relational database experience (Oracle, MySQL) writing queries 
- Experience with programming languages, `Python`
- Experience with data architecture, data modeling, schema design and software development 
- Experience with large data sets, `Hadoop,` and data visualization tools
- Experience initiating and driving projects, and communicating data warehouse plans to internal clients/stakeholders 
- Familiar with Google `Cloud` Platform or Amazon Web Services 

YOU’'ll LOVE WORKING HERE

- 13th salary.
- Performance bonus 
- Comfortable Private working Area for TECH team
- PVI Care
- Team-building.
- Outing trip Join Training Courses and Tech Sharing Mid-Autumn Party, Christmas
- Party Year-end Party 
- With the delivery network cover more than 98% the geographical area of Vietnam, you will be welcome anywhere of Vietnam for traveling
- Sports club: football, badminton

ADDRESS: 3rd Floor, Rivera Park Building, 7/28 Thanh Thai,  District 10, Ho Chi Minh*
Please contact  Ms. Anh Hoang via Email (anhhnt@scommerce.asia), skype (tremlobisi94) or phone number (0981 851 385) if you’ve got any concern on this position

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
