### ISSUE TITLE
AhaMove - UI/UX Designer - HCMC - Full Time

### ISSUE THREAD

**Issue by NguyenNguyen2410** [awesome-jobs/vietnam#1843]
## Location

* District 10, Ho Chi Minh, Vietnam

## Salary Expectation

* $800-$1000/month

## About us

Founded in 2015 in Ho Chi Minh City, Vietnam, AhaMove is an on-demand logistics service based on the concept of a shared economy, providing customers to fill excess capacity for logistics suppliers and reduce costs for consumers. 
You can find more about us as a Facebook case study or on prestigious Asia Nikkei news This is a tremendous opportunity to take your career to the next level. Please review the information below and if you are interested, follow the Apply instructions.

Anh now we are looking for a UI/UX Juggernaut to join our rapidly growing Mobile & Enterprise team. The ideal candidate will be an enthusiastic practical-minded perfectionist. The candidate must be passionate about user experience, willing to take creative risks and do whatever it takes to do the best work possible. Able to handle a range of project types—some of them simultaneously—from discovery to concept and ideation to design. If this sounds like you – we’d love to hear from you!

## The Job

* Design the information architecture and interaction models for our projects. This may include websites, mobile experiences, or other touch-points 
* Work in close collaboration with Development and Product Management teams to develop initial strategy—addressing product, brand, marketing, content, and overall user experience 
* Conduct user research including contextual interviews and usability testing, and present findings to customers/partners 
* Create internal and external deliverables including conceptual diagrams, site maps, interaction flows, storyboards, schematics/wireframes, and detailed functional specifications 
* Work iteratively; develop ideas from sketches to prototypes 
* Collaborate with engineers team and product managers to generate superb design work 

## Skills & Experience

* Minimum 1 years hands-on experience with background in Wireframing, Information Architecture, User experience and UI Design for web and mobile interfaces. 
* Experience designing and conducting user research, including contextual inquiry and usability testing 
* Excellent deliverables including prototypes, detailed page schematics, sketches, interaction flows, site maps, navigation systems, and web-appropriate writing 
* Ability to work well with engineers team and product team to articulate issues and communicate persuasively 
* Experience working in small collaborative teams 
* Ability to work independently, prioritize, and solve problems proactively 
* An outstanding portfolio that demonstrates your approach to projects, quality thought, 
    storytelling, and an ability to bring your ideas to life. The portfolio that is relevant to O2O projects is a plus.

### Why it would be awesome to work with us
* Disruptive innovations 
* People-oriented philosophy of doing business 
*  Your footprint on regional on-demand market 
* Sharp, motivated colleagues in a fun office environment 
* Working 5 days/week 
* Competitive salaries and benefits according to experience and education level 

### Contact
Homepage: https://ahamove.com/
https://www.linkedin.com/company/6587395/
Mr.Nguyen
Email: nguyennvb@scommerce.asia
Telegram: https://t.me/NguyenNVB

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
