### ISSUE TITLE
Ascenda Loyalty -  Backend Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by longkt90** [awesome-jobs/vietnam#1844]
## Location

* Saigon, Vietnam

## Salary Expectation

- Junior-Mid level: $1500 - $2500 / month 
- Senior: $2500 - $5000 / month 
- Exceptional: negotiable

### Must Have

- Have at least 4 years of development experience (fresh grad/juniors feel free to apply too)
- Have strong experience in at least one back-end language (Ruby preferred, but not obligatory). 
- Have solid knowledge of how web applications and backend services (e.g. APIs) work.
- Have solid knowledge over deployments & scaling applications
- Be able to write good quality code supported by automated tests
- Know how to debug, measure and optimise performance of application
- Great analysis skills, able to thrive under pressure
- Be a team player, willing to help other developers and caring about the product you build
- Have good communication skills, are not afraid of suggesting changes and improvements
- Be a fast learner, able and willing to learn new languages and libraries

### Ideally

- Know at least one functional language
- Have experience working with a high traffic application
- Strong experience with Ruby or Elixir.

### You’ll be responsible for

- Build, design and architect backend services, APIs across Ascenda's end-to-end loyalty platform. 
- Debug and troubleshoot production issues
- Work with engineers from multiple teams to develop and design reliable, performant and secure services.
- Play a crucial role in developing Ascenda's engineering culture
- Take ownership in the development of backend products
- Have the opportunity to solve problems in multiple domains, such as performance optimisations, building flexible business logic, improving security.
- Maintain and improve high availability and throughput systems - handling millions of requests per day for our customers globally.

### Why it would be awesome to work with us

- Competitive salary and benefits
- Travel benefits
- Flexible working environment (we allow for remote working, flexible hours when needed)
- Comfortable working environment (Every new hire gets a brand new Macbook Pro and 2 screens!)
- Diverse and friendly working culture. Members of our team come from over 20 nationalities worldwide!
- Good engineering practices and processes including code review, test first, and training... 

### About us

Ascenda is a global provider of innovative loyalty solutions and operates premium rewards propositions for major financial services and travel brands worldwide. As a trusted partner powering over 70 of the world’s leading rewards programs, Ascenda develops end-to-end solutions to address the most meaningful challenges facing the loyalty industry today. By deeply profiling local market needs to provide the right technology, content and value propositions alongside careful management of marketing, servicing, costs, and fraud, Ascenda delivers highly compelling and beautifully simple plug & play offerings that eliminate the trade-off between cost and customer value.

At its heart, Ascenda is an engineering and technology company. Our products and services help many financial services and travel brands serve millions of customers globally better. We take pride in building beautifully designed, performant, easy to use but yet secure products and place a huge emphasis on delivering great code.

We're looking to bring in passionate backend engineers who're keen to learn and grow in a fast-paced environment. You take great pride and your work and feel a great sense of accomplishment in building beautiful products that scale. 

At Ascenda, we work on a wide variety of backend services built on both Ruby and Elixir. We're hiring across all levels for this role, ranging from junior to senior levels.

### Contact
- Apply via website: https://careers.ascendaloyalty.com/o/backend-software-engineer-vietnam-hcm
- Send your CV to:  job.dksbf(at)ascendaloyalty.recruitee.com

**Comment by longkt90** [comment]
frontend JD #1861

**Comment by trungkien1503** [comment]
@longkt90 I just applied via the website, thank.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
