### ISSUE TITLE
FETCH TECHNOLOGY - Senior Python Developer - HCMC - FT

### ISSUE THREAD

**Issue by JunnieNguyen** [awesome-jobs/vietnam#1845]
## Location

* 3rd Floor, Golden Building, 473 Dien Bien Phu Street, Ward 25, Binh Thanh District, HCMC.
* Full-time

## Salary Expectation

* 1000$-2000$

## Requirements
* Highly skilled in developing, testing, debugging, and troubleshooting with programming language: Python (nice to have Node.js, Golang).Especially for building backend services.
* Highly skilled in designing complex real world database structures and storing, managing, and analyzing large amount of data in SQL. PostgreSQL
* Highly skilled in all kinds of development tools that brings source code in a text file to running code in production.
* Experience in agile development process and applications such as Trello.

## Responsibilities
* Analyse and systematically approach requirements and bugs reported, always coming up with practical short term and long-term solutions that minimize complexity and maximize value.
* Design and build modular components and reusable subsystems using various suitable tools, cloud services, and applications to scale complexity and scale massive data transfer.
* Include security, maintainability, reusability, and testability when developing software solutions and code reviewing.
* Factor Linux/Unix OS system internals, data storage, computing resources, microservices in the produced software architecture.

### Why it would be awesome to work with us
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Email: dungnguyen@fetch.tech
Skype: dungphuongdh

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
