### ISSUE TITLE
Manabie Vietnam - Senior Backend Engineer - HCMC - FT

### ISSUE THREAD

**Issue by duytran1993** [awesome-jobs/vietnam#1846]
## Location

* 180 Nguyen Cong Tru, Nguyen Thai Binh Ward, Q1, Vietnam

## Salary Expectation

* $2000/month or range

## Requirements
* Golang
* gRPC
* TDD (Test Driven Development) - No Test, No Merge!
* Algorithms and Data Structure

### Must Have

* Golang/ NodeJs

### Ideally

* Experience with gRPC
* Experience with AWS

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Implement & maintain Microservices with Golang & Node.js
* Work closely with our product managers to understand feature specifications
* Communicate with QA engineers to design and understand technical specs
* Proactively give feedback and ask questions to contribute to product specifications’ improvement
* Work closely with mobile & frontend engineers for API design & integration 
* Make a thing work first before make it better
* Test driven development with unit and integration tests (no test, no merge culture) 

### You can bring

* A scale able and stable system.

### Why it would be awesome to work with us

* A strong and friendly team, who will support you when needed, and troll you when bored.
* A culture that encourage you to speak your mind and take ownership to the product that you made.
* A place where you can bring your Business sense and awareness to a whole new level through transparency and candidacy.

### Interesting engineering projects

* If whole Education ecosystem, with lots of interesting feature is not enough for you, lots of internal tools are waiting.

### Contact
Homepage: https://manabie.com/careers#tech
Email: dylan.tran@manabie.com / careers@manabie.com
Tel: 0915 342 782
Skype: ducduy1293

Take a look at our team!

![0](https://user-images.githubusercontent.com/35828838/71248484-88098280-234d-11ea-889d-80ff24e5991e.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
