### ISSUE TITLE
Tech Apollo - Ruby on Rails Developer - HCM - FT

### ISSUE THREAD

**Issue by khanhngannguyen** [awesome-jobs/vietnam#1850]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Up to $1,500/month

## Requirements

* At least 1 year of experience with Ruby on Rails.
* Solid foundation in HTML, CSS, and Javascript
* Experience with HTML, CSS & Javascript
* Able to work independently and in a team

### Ideally

* Experience with one of the following technology: Angular, React, Vue
* Fast learning ability
* Good communication
* English: reading & writing

### Responsibilities

* Manage individual project priorities, deadlines and deliverables
* Work with the project team as well as clients
* Design, build and maintain efficient, reusable, and reliable Ruby code
* Work on both front-end and back-end side of an application

### Why it would be awesome to work with us

* 2-month probation with 100% salary
* Working in a friendly, fun and open-minded environment
* Sharing & transparent culture
* Annual leave: 15 days
* Career growth opportunities
* Competitive salary, 13th salary
* Team parties
* Time working: 08:00 AM - 05:00 PM from Monday to Friday.

### Interesting engineering projects

*  E-Commerce application for agricultural products.
* Automatic Travel Scheduling - TripHunter (won the first prize in Start-up Hunt 2019, top 5 Vietnamese Start-ups organized by VnExpress, completed VIISA Acceleration Program Batch 6)

### Contact

Send CV via mail: khanhngan.nguyen112@gmail.com
Subject: [TA - RoR - Your Name] 
Website: https://techapollo.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
