### ISSUE TITLE
Amaris Vietnam - .NET Developer (All Level) - HCM - FT

### ISSUE THREAD

**Issue by nghiahuynh14** [awesome-jobs/vietnam#1851]
## Introduction
Amaris is an independent, international Technologies and Management Consulting Group. Created in 2007, Amaris is already established in over 50 countries and supports 500 clients worldwide throughout their projects’ lifecycle. Our expertise covers 5 areas of innovation: Business and Management, IT/IS, Telecom, Engineering and High Technologies, Biotech and Pharma. With 65 offices across the World, the Group offers proximity support to its clients in all their locations and many opportunities of international careers for employees.  
In 2019, Amaris aims to reach a turnover of 300 million euros, 6500 employees and the ability to recruit one new employee every 5 hours. We expect to triple our workforce within the next years and reach an international leader position in independent consulting. 

## Location
Saigon, Vietnam

## Salary Expectation
Negotiable (Attractive)

### Ideally
- Bachelor’s degree from engineering school in Computer Science or related technical discipline (or equivalent). 
- At least 1 to 5+ years of experience in application/software development
- Experience on Object-Oriented Programming (C#/ ASP .NET, MVC as preferred), **fresh graduates are welcomed.** 
- Hands-on experience in .Net Core, .Net Framework (4.0 and up), C#, ASP.Net MVC (4.0 and up), Web API, Entity Framework, LINQ and SQL Server

### Responsibilities
- Develop software application using Microsoft Technologies such as: .Net Core, C#, ASP.Net MVC, etc.  
- Create enhancements, new functionalities, integrations and bug fix.  
- Research new techniques to apply to the projects if required.  
- Work as part of a team and participate in customer support activities as needed.  
- Develop documentation throughout the software development lifecycle.  
- Other tasks are assigned by Manager/Supervisor. 

### Why it would be awesome to work with us
- Competitive salary package based on competences  
- 13th month salary  
- Private healthcare insurance, starting from your probation period  
- 14+ annual leaves per year, extra medical leaves  
- Special treatments on your special occasions  
- Clear career path and various opportunities to grow within the company  
- Yearly performance bonus and appraisal  
- Global trainings and language courses  
- Annual company trip  
- Company events: Mantu Foundation, Mid-Autumn/Christmas/Year-end parties, etc.  
- Teambuilding activities: Team lunch/dinner, football tournaments, sports clubs, etc.

### Contact
- Homepage: www.amaris.com / www.mantu.com
- Email: nhuynh1@mantu.com
- Phone: +84 287 300 1723  / +84 9327 69654
- Location: Viettel Tower, 15th Floor, 285 Cach Mang Thang 8 Street, Ward 12, District 10, HCM, Viet Nam

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
