### ISSUE TITLE
Full-Stack Junior～Senior Developer (PHP/Java) - Full Time

### ISSUE THREAD

**Issue by ngocphuong39** [awesome-jobs/vietnam#1853]
## Location
Điện Biên Phủ - Phường 3 - Hồ Chí Minh

## Lương
Thương Lượng 

## Requirements
* Programming languages: More than 3 years of WORK EXPERIENCE as a PHP or Java developer·
* Database: Postgres SQL, MySQL·
* Experience in Seasar / Symfony / Silex / Doctrine· Experience in HTML, CSS, jQuery, Ajax·
* Experience in reviewing work results of others (cross review)·
* Understanding about software development processesPreferred qualifications:·
* Experience in E-commerce, EC-CUBE is a BIG PLUS.· Experience in big data processing such as Hadoop, Vertica or optimizing the performance of database is a BIG PLUS·
* Understanding about object-oriented programming·
* Have knowledge about software testing, Database analyzing·
* Not only software designing but also system and infrastructure architectural designing capability· Using Japanese is a BIG PLUS

## What you will do?
 You will participate in a whole software development project. The main responsibilities of developers are: requirement, architecture, detail design, coding and unit testing, testing.

### Contact:  
 Email: ngocnguyen.hrfreelancer@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
