### ISSUE TITLE
[Linkbynet] - [DevOps Engineer] - [Hochiminh City] - [FT]

### ISSUE THREAD

**Issue by hhieuvvu** [awesome-jobs/vietnam#1856]
## Location

* 285 CMT8, Ward 12, District 10, Hochiminh City, Vietnam
* Full time

## Salary Expectation

* 1500$ - 2500$ (Gross/negotiate)

## Responsible:

The **DevOps Engineer** will be responsible for:
* Automating the release, deployment and management of applications (customers or internal one) from development through production. 
* Design, Deploy, Improve and automate application infrastructure (IaaC infrastructure) 
* Investigate and troubleshoot application miss behaving and take the needed action to fix it

You will be working collaboratively with developers; System engineers and Customer based anywhere in the world to architect and build solution:

* Automated provisioning, configuration management in cloud environments or on premise 
* CI/CD of applications 
* Automatic incident remediation

## Your activities:

* Strong understanding of production context and risk analyzes 
* Provide direct and indirect support to customers (internal or external); 
* Analyze requirements and specifications
* Develop software applications infrastructure; 
* Deploy new product releases and upgrades; 
* Administer internal systems and cloud service 
* Create and maintain scripts and applications to automate repetitive tasks 
* Research and keep up to date with the latest technologies 
* Write/update technical and user documentations 

## Your Skills and Experience:

* Everyday usage of git version control system, it’s a plus to know Gitlab 
* Familiar with development language MVC framework, CI/CD, unit testing 
* Speaking to REST-API is something you do every week 
* Knowledge of container, micro-service, database data model  
* You know what production is, what’s to manage incident and you want to avoid it at all cost 
* Significant experience in cloud infrastructure is a plus, especially with AWS, Azure or Google 
* One of the following System flavor: 
   * Windows flavored guy, since the release of PowerShell, you should have forgotten how to use your mouse and be Windows Core addict. 
   * Linux flavored guy, your speaking Python and you’re Jedi master of the shell 
* You are defined by the following autonomous, curious and technology enthusiast. You can take ownership of projects and drive them to completion. 
* Excellent communication and documentation skills. 

## Qualifications: 

* More than 3 years of experience in a similar position or equivalent

### Additional Information
Created in 2011, Treeptik assists its customers in modernizing their IT. We provide advice, training and realization around these three pillars: Journey to the cloud | Containerization | DevOps.

Our multidisciplinary teams assist our clients in finding the solution that suits them while guaranteeing quality and safety.

Since August 2017, Treeptik has joined **Linkbynet Group**, composed of 800 people. We are now the Group's Consulting Center.

Thanks to our passion for the latest technologies, we have developed a whole network of partners: "Premium Partner" Docker since 2012 (highest level of accreditation delivered by Docker), Nutanix, Neuvector, Azure, AWS, Google.

With our entire team, we animate events throughout the year around these topics:
* DEVOPS D-DAY: Conference day at the Orange velodrome (more than 1200 people from IT in 2018)
* DevOps tour: DevOps awareness days in several cities in France
* Meetup Docker & DevOps

### Contact
Mail: h.vu@linkbynet.com (Hieu Ms.)
Linkedin: <https://www.linkedin.com/in/hieuvu212/>

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
