### ISSUE TITLE
The Kirin Lab - React Native Mobile Developer - Hanoi - FT

### ISSUE THREAD

**Issue by michael-kirin** [awesome-jobs/vietnam#1858]
## Location

* Hanoi, Vietnam (We're located at Hai Ba Trung District)

## Salary Expectation

* Competitive remuneration

## Requirements

* At least 1 year of React Native experience in production
* Ability to work independently and build a React Native app from scratch
* 3+ years of Software Engineering experience
* Attention to detail and reliability are what you take pride in.
* You enjoy driving things over getting tasks assigned

### Must Have

* React Native

### What makes you stand out

* Able to communicate your ideas in English is a plus
* Had experiences leading a team is a plus

### You’ll be responsible for

The Kirin Lab is looking for an experienced Mobile Engineer who enjoys developing and designing React Native Mobile App. Together with the team, you will have ownership of the services you build. 

### Why it would be awesome to work with us

The Kirin Lab is a startup consulting company incorporated in Singapore and focusing on the Singapore market. You will join a team of experts who have worked in various startups in Singapore with lots of experiences. As a consultant, you will work directly with early stage startups and help them develop their product from initial idea to launch stage. 

### Technologies we use

* Languages: Elixir, Ruby, React Native, Kotlin, Swift
* Platforms:  Phoenix, Rails, ReactJS
* Infra: AWS, Heroku
* Tools: Github, Slack, Trello, Notion, Figma

### Contact
Website: [The Kirin Lab](https://www.thekirinlab.com)
Please send your resume to career@thekirinlab.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
