### ISSUE TITLE
[Bocasay Vietnam] Senior NodeJS Developer 

### ISSUE THREAD

**Issue by tualam** [awesome-jobs/vietnam#1859]
## Location
* Hanoi, Vietnam

## Salary Expectation
* $1300 - 1800/month

## Requirements
* Node JS
* MongoDB
* 3+ years of experience in web backend development
* Good command of English.

### Responsibilities
* Take a leading role in using NodeJS for web development activities to gain the high level of satisfaction from Bocasay's customers. 
* Define and communicate technical and design requirements from client.
* Design, implement, and document Node.js applications and other required backend services, involve and participate in the overall application life cycle.-
* Implement integrations with external APIs and data providers
* Collaborate with an agile team to build flexible web applications.
* Be in charge of database creation, integration, and management

### Why it would be awesome to work with us
* Exceptional talents will be matched with an exceptional salary
* Young & Friendly working environment
* Encourage people to be lead & push new ideas forward in our small teams
* Social/Health/Unemployment Insurances are fully levied on the salary
* 15 days of annual leave
* Salary review: 2 times/year
* 13th salary is paid before the Lunar New Year
* PVI Healthcare Insurance
* On-boarding program (opportunities to work abroad after 2 years)
* Loyalty bonus (10-year scheme)
* Training & study sponsorship
* Tons of fun & exciting team activities: annual company trip, monthly BBQ night, happy hours, etc.

### Contact
Homepage   : www.bocasay.com
Skype/email : alam@bocasay.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
