### ISSUE TITLE
VRED - Senior Reactjs/Nodejs Developer - HCM - FT

### ISSUE THREAD

**Issue by Lethanhthihr** [awesome-jobs/vietnam#1860]
## Location

* 104 Mai Thi Luu street, Dakao Ward, District 1, HCMC, Vietnam

## Salary Expectation

* $1200 - $1700

## Requirements
* At least 2+ years of experience with NodeJS/ReactJS.
* Databases: PostgreSQL, MySQL, MongoDB.
* APIs: RESTful.
* Familiarity with SQL/NoSQL databases and their declarative query languages.

## Skills
* Ability to coach and mentor team members in their professional development and build self-sustaining teams.
* Ability to work independently as well as in a team.
* Keep abreast of latest development techniques and security practice.

### Must Have
* At least 2+ years of experience with NodeJS/ReactJS.

### Ideally
* User authentication and authorization between multiple systems, servers, and environments.
* Understanding accessibility and security.
* Integration of multiple data sources and databases into one system.
* Creating database schemas that represent and support business processes.
* Familiarity with SQL/NoSQL databases and their declarative query languages.
* Proﬁcient understanding of code versioning tools, such as Git.

### Responsibilities
* Architect and develop stable and high availability web service.
* Rapidly build, iterate, test and deploy new features and products.
* Maintain codebase.
* Solve complex performance problems and architectural challenges.
* Integration of third party solutions as needed.
* Create modern, high performance JavaScript Framework (NodeJS, ReactJS, Redux…) sites from visual designs.
* Ensure cross-browser, cross-device performance, compatibility and responsiveness.
* Optimize application for maximum speed and scalability.

### You’ll be responsible for
* Rapidly build, iterate, test and deploy new features and products.

### Why it would be awesome to work with us
* Competitive salary & stock option.
* Review salary raise every 6 months.
* Bonus: performance, team bonus.
* 13th month salary per year & Full working facilities.
* Social – Health – Insurance paid fully
* 12 annual leaves per year
* Annual company trip
* Professional and Flexible Working Environment
* Great Teamwork
* Extensive Training Program and Team-building activities, events.
…
### Interesting engineering projects
Product: Fintech & Wholesales

### Contact
Email: hr@vred.com.vn
Skype: Thanhthi.hr
Phone: (+84) 988 428 440

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
