### ISSUE TITLE
Ascenda Loyalty - Frontend Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by longkt90** [awesome-jobs/vietnam#1861]
## Location

* Saigon, Vietnam

## Salary Expectation

$1000 - $4000 / month

### Must Have

* Have at least 1-3 years of web development experience ideally. We welcome fresh graduate applicants too
* Have strong experience in JavaScript (knowing ES6 and at least one popular JS framework like Ember, Angular or React is a must)
* Experience in working with APIs
* Experience in building responsive web applications that work across multiple devices and resolutions.
* Be passionate about building front ends with modern tools and frameworks such as Angular 8, NgRx, Webpack, etc
* Understand and be able to implement good tests for frontend code
* Know how to debug, measure and optimise performance of application
* Be a team player, willing to help other developers and caring about the product you build
* Have good communication skills, are not afraid of suggesting changes and improvements
* Be a fast learner, able and willing to learn new languages and libraries
* Be able to empathise with the many different users that might use Ascenda's loyalty platform

### Ideally

* Understand UX well
* Are also familiar with backend languages such as Ruby

## Responsibilities

* Build, design and architect Ascenda's frontend products across our entire end-to-end loyalty platform
* Debug and troubleshoot production issues
* Work closely with engineers from various teams (e.g. backend) to develop and build high quality software.
* Play a crucial role in developing Ascenda's engineering culture
* Take ownership in the development of frontend products

### Why it would be awesome to work with us

* Competitive salary and benefits
* Travel benefits
* Flexible working environment (we allow for remote working, flexible hours when needed)
* Comfortable working environment (Every new hire gets a brand new Macbook Pro and 2 screens!)
* Diverse and friendly working culture. Members of our team come from over 20 nationalities worldwide!

### Contact
Homepage: https://careers.ascendaloyalty.com/o/frontend-software-engineer-vietnam-hcm

**Comment by longkt90** [comment]
backend position is at https://github.com/awesome-jobs/vietnam/issues/1844

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
