### ISSUE TITLE
Rakuna - Front-End Developer - HN/HCMC - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1863]
## Location
* Hanoi, Vietnam
* Saigon, Vietnam

## Salary Expectation
* $500-700/month
* Competitive and negotiable based on work experiences

## Responsibilities
* Closely coordinate with other members of the Sales, Marketing, and Product teams to ensure all requests are completed on time.
* Create and update static HTML pages using CSS, HTML, JavaScript following SEO standards.
* Develop HTML, CSS, and JavaScript for front end web applications.
* Optimize web page to work functionally on major devices and browsers.
* Create and update guidelines for front end development.

### Must Have
* Strong knowledge and experience with HTML, vanilla Javascript and modern CSS.
* Experienced with cross-browsers development.
* Used to work with at least one modern front end framework: React, Vue, Angular.
* Familiar with modern build and automation tools(SASS, Gulp, Grunt).
* Good sense of design.
* Willingness to share ideas and teach/learn from others.
* Working proficiency and communication skills in verbal and written English.

### Nice to have
* Familiarity with Agile development
* Experience working in startup-like environments with iterative, value-driven product releases.

## Why it would be awesome to work with us
* Be a part of a young, dynamic, multinational and multi-functional team that serves global customers with new everyday challenges (Our team has staff working in Finland, U.S and Vietnam).
* Join a working culture that is fast-paced, goals driven, and committed to long-term career development.
* Have a monthly 1-1 performance review with your supervisor/manager to ensure you meet your goals and get the support you need to succeed in your position. 
* Possess high work flexibility and ownership (We don’t count every single hour you show up at the office, what we care more is are you able to achieve your tasks each month).
* Receive a comprehensive compensation and benefits package.
* Attend frequent bonding events and training sessions (leadership, technical knowledge,...)

## Contact
Homepage: www.rakuna.co
Spam us at: ly@rakuna.co
Call us, beep us at: 0981675673 (Ly)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
