### ISSUE TITLE
Rakuna - Mid-Level Software Developer - HN/HCMC - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1864]
## Location
* Hanoi, Vietnam
* Saigon, Vietnam

## Salary Expectation
* $600-800/month
* Competitive and negotiable based on work experiences

## Responsibilities
Design, Implementation & Research:
* Work with the Product Development team to implement their vision while providing feedback and taking ownership of the behavior, design, and implementation of features. 
* Design and build advanced applications for the Android platform.
* Execute and drive mid-size feature application design and development efforts to completion.
* Unit-test code for robustness, including edge cases, usability, and general reliability.
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

Troubleshooting:
* Analyze and troubleshoot coding, application performance, and design challenges.
* Research in root cause of development and performance concerns as well as the resolution of defects.
* Work on bug fixing and improving application performance.
* Refactor existing code with pride.

### Must Have
* 2-3 years of experience with application and services development with Android and Java (portfolio required as proof).
* Familiar with Android Studio IDE, Perforce, Git and Gradle build scripts. Deep exposure to Perforce is strongly recommended.
* Understanding of networking and building client-server based applications.
* Adequate Technical, Analytical, problem-solving written and verbal skills.
* Prior experience and understanding of the product/software development process.
* Highly motivated and able to work proactively.
* Working proficiency and communication skills in verbal and written English.

### Nice to have
* Familiarity with Agile development
* Experience working in startup-like environments with iterative, value-driven product releases.
* A good sense of design

## Why it would be awesome to work with us
* Be a part of a young, dynamic, multinational and multi-functional team that serves global customers with new everyday challenges (Our team has staff working in Finland, U.S and Vietnam).
* Join a working culture that is fast-paced, goals driven, and committed to long-term career development.
* Have a monthly 1-1 performance review with your supervisor/manager to ensure you meet your goals and get the support you need to succeed in your position. 
* Possess high work flexibility and ownership (We don’t count every single hour you show up at the office, what we care more is are you able to achieve your tasks each month).
* Receive a comprehensive compensation and benefits package.
* Attend frequent bonding events and training sessions (leadership, technical knowledge,...)

## Contact
Homepage: www.rakuna.co
Spam us at: ly@rakuna.co
Call us, beep us at: 0981675673 (Ly)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
