### ISSUE TITLE
Rakuna - Mid-Level Android App Developer - HN/HCMC - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1865]
## Location
* Hanoi, Vietnam
* Saigon, Vietnam

## Salary Expectation
* $600-800/month
* Competitive and negotiable based on work experiences

## Responsibilities
* Deeply participate in the product development process of analyzing requirements, designing system, implementation, testing, and deployment.
* Collaborate with core functional teams - Sales & Marketing, Customer Success, and Operations to achieve the ultimate business goals.
* Understand and work within the brand and corporate guidelines

### Must Have
* Master at least one of these programming languages: Ruby, Javascript, Golang
* At least 2+ years of software development experience 
* Have a strong knowledge of TDD, BDD
* Interest in and ability to learn new technologies
* Experience with a modern web framework (a must for Web developer)
* Working proficiency and communication skills in verbal and written English

### Nice to have
* Familiarity with Agile development
* Experienced with cloud services (AWS, GCP, Azure)
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect
* A good sense of design

## Why it would be awesome to work with us
* Be a part of a young, dynamic, multinational and multi-functional team that serves global customers with new everyday challenges (Our team has staff working in Finland, U.S and Vietnam).
* Join a working culture that is fast-paced, goals driven, and committed to long-term career development.
* Have a monthly 1-1 performance review with your supervisor/manager to ensure you meet your goals and get the support you need to succeed in your position. 
* Possess high work flexibility and ownership (We don’t count every single hour you show up at the office, what we care more is are you able to achieve your tasks each month).
* Receive a comprehensive compensation and benefits package.
* Attend frequent bonding events and training sessions (leadership, technical knowledge,...)

## Contact
Homepage: www.rakuna.co
Spam us at: ly@rakuna.co
Call us, beep us at: 0981675673 (Ly)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
