### ISSUE TITLE
Rakuna - Software Engineer Intern - HN - PT/FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#1866]
## Location
* Hanoi, Vietnam

## Salary Expectation
* Competitive and negotiable based on work experiences

## Responsibilities
* Assist in building and/or managing product pipelines including planning, development, and maintenance.
* Analyze information and evaluate results to choose the best solution to effectively solve problems.
* Provide quality assurance (QA) support through product testings.
* Work with peers, managers, and teams to create and support core functional teams - Sales & Marketing, Quality and Customer Success, and Operations.
* Learn in-depth about how to create a product in a start-up environment. You might be the next entrepreneurial commander for your future start-up!

### Must Have
* Currently enrolled in a Bachelor's or Master's program in Computer Science, Information Technology or a related technical field.
* Experience of coding in one of the following programming languages including but not limited to: Ruby, C++, Java, Python.....
* Have contributed in or lead at least 1 software development project in one or more general-purpose programming languages.
* Demonstrated interest and ability to learn other coding languages as needed.
* Developed communication skills, and the ability to speak and write in English fluently and idiomatically.
* Effective teamwork, project management, creative problem-solving. strong communication skills.
* Can commit at least 6-months as an intern; may have the opportunity to be offered full-time post-internship if shown excellency at work. 

### Nice to have
* Technology internship experience or work experience (e.g: research assistant, teaching assistant, personal projects, etc.).
* Familiarity with Agile development.
* Love startup-like environment, want to challenge yourself and aim for a leadership prospect.
* A good sense of design.

## Why it would be awesome to work with us
* Be a part of a young, dynamic, multinational and multi-functional team that serves global customers with new everyday challenges (Our team has staff working in Finland, U.S and Vietnam).
* Join a working culture that is fast-paced, goals driven, and committed to long-term career development.
* Have a monthly 1-1 performance review with your supervisor/manager to ensure you meet your goals and get the support you need to succeed in your position. 
* Possess high work flexibility and ownership (We don’t count every single hour you show up at the office, what we care more is are you able to achieve your tasks each month).
* Receive a comprehensive compensation and benefits package.
* Attend frequent bonding events and training sessions (leadership, technical knowledge,...).

## Contact
Homepage: www.rakuna.co
Spam us at: ly@rakuna.co
Call us, beep us at: 0981675673 (Ly)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
