### ISSUE TITLE
Yojee - Engineering Manager - HCM - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1867]
## Location

* Saigon, Vietnam

## Salary Expectation

* VND 70M to VND 115M gross per month

## About the role

Yojee is looking for an Engineering Manager who will be responsible for leading and supervising our team of engineers in our Ho Chi Minh City office as they develop, create, test and modify new and existing features of our platform. This role will be located in Vietnam and reporting directly to the CTO in Singapore. 

## Requirements

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 5+ years of experience in Agile Software Development, preferably Scrum.
* 2+ years of experience in people management.

### Nice to have

* Certified Scrum Master.

### Responsibilities

* Supervise and lead engineers and oversee development, operations and quality control.
* Have ownership of the services you maintain to ensure their continued availability.
* Ensure that our Scrum process is followed.
* Remove obstacles for the team.
* Hire, train, and mentor software engineers and supporting staff.
* Write performance reviews and solve internal issues.
* Coordinate with recruiting agencies, office management, external partners in Vietnam.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Chief Technology Officer.

### Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=56&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
