### ISSUE TITLE
Yojee - Data Analyst - HCM - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1868]
## Location

* Saigon, Vietnam

## Salary Expectation

* VND 13M to VND 30M gross per month

## About the role

Yojee is looking for a Data Analyst to dig deep into our master data set, create reports for both internal stakeholders and our growing user base, and create actionable insights.

## Requirements

* Bachelor in Computer Science/Data Analytics or related studies.
* 2 years of work experience in the Data Analytics area.
* Strong understanding of key concepts, techniques and considerations in data analytics .
* Experience in SQL, preferably PostgreSQL.
* Experience using visualization software (e.g. Tableau or Qlik, ideally Holistics).
* Proven ability to translate complex technical subjects into clear and concise communications to stakeholders at all levels.

### Responsibilities

* Engage, influence, communicate with stakeholders to support data analytics plan and strategies.
* Identify actionable insights and recommend options for analysis and models.
* Support the stakeholders with business reports build in Holistics.
* Cooperate with Product Management to build and improve reports embedded in our platform.
* Research technologies for and build embedded dynamic dashboards.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Lead Engineer.

### Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=57&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
