### ISSUE TITLE
Yojee - Fullstack Engineer - HCM - FT 

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1869]
## Location

* Saigon, Vietnam

## Salary Expectation

* VND 40M to VND 60M gross per month

## About the role

Yojee is looking for a Fullstack Engineer who enjoys developing features end-to-end in a cloud platform environment with React and Elixir/Phoenix. Due to our strong commitment to team ownership, you will have many opportunities to bring in your ideas and architecture suggestions. Since we are aware that you might be coming either from frontend development or backend development, missing experience on one side can be balanced with strong skills on the other end - but we expect the will to ramp up on the full stack. 

## Requirements

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 2+ years of experience in development of various complex systems.
* Experienced and proficient in working with at least two languages, preferably Elixir, Javascript, Ruby on Rails, Go, Scala, Haskell or any other functional programming language.
* Experience with frontend technologies like Angular.js, React.js or vue.js.
* Experience working with relational database systems (preferably PostgreSQL).

### Nice to have

* DevOps experience with AWS or Azure, Docker.
* Production experience with Elixir &amp; Phoenix.
* Scripting (Python, Lambda, Bash).

### Responsibilities

* Continuous improvement and maintenance of our backend systems as well as frontend modules.
* Writing reusable, testable and efficient code.
* Write and maintain external and internal the documentation across all modules ranging from frontend to backend.
* Ensuring and enabling reliable connectivity and functionality across services. 
* Work with a large variety of products, connected by APIs.
* Work with the DevOps team to ensure reliable, proactive, and efficient scaling. 
* Have ownership of the services you maintain to ensure their continued availability (including after-hours emergency recovery). 
* Work with the other teams to ensure feature parity and cross compatibility.
* Identify, recommend and refactor code as when needed to improve the overall stability.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Engineering Manager.

### Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=58&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
