### ISSUE TITLE
Yojee - QA Engineer - HCM - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1870]
## Location

* Saigon, Vietnam

## Salary Expectation

* VND 20m to VND 45m gross per month

## About the role

Yojee is looking for a QA Engineer that enjoys taking over responsibility of automated integration and regression testing in a dynamic startup. As part of the development team, you will have ownership of the services we build, and to share your ideas regarding architecture and process.

## Requirements

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* Minimum 2 years of relevant QA experience.
* Proven history of being able to setup, manage and execute quality assurance services for one or more products.
* Experience automating website testing with Selenium.
* Experience with mobile testing & Appium framework .
* Attention to detail and reliability are what you take pride in.
* You enjoy driving things over getting tasks assigned.

### Nice to have

* Experience working with agile software development practices.
* Experience with BDD using Cucumber.

### Responsibilities

* Work with the development team and Product Management to understand requirements and provide feedback about feasibility and quality & usability aspects.
* Manual test web and mobile user interfaces.
* Create test plans for existing and new features.
* Create automated API tests with Postman or similar.
* Create automated user interface tests with Selenium or similar.
* Create automated mobile app tests with Appium or similar.
* Manage defects in JIRA.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Engineering Manager. 

### Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=59&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
