### ISSUE TITLE
Yojee - Senior Backend Engineer - HCM - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1871]
## Location

* Saigon, Vietnam

## Salary Expectation

* VND 50m - VND 80m gross per month

## About the role

Yojee is looking for a Senior Backend Engineer who enjoys developing and designing backend services in a cloud platform environment with Elixir/Phoenix. Together with the team, you will have ownership of the services you build, and you love to share your ideas regarding architecture and functionality.

## Requirements

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 4+ years of various complex systems.
* Experienced and proficient working with at least two languages, preferably Elixir, Ruby, Go or any functional programming language.
* Experience designing and working with relational database systems (preferably PostgreSQL).
* Design, develop and execute software solutions to address business issues.
* Troubleshoot code level problems quickly and efficiently.
* You enjoy driving things over getting tasks assigned.
* Attention to detail and reliability are what you take pride in.
* Excellent communication and collaboration skill.
 
### Nice to have

* Experience with Microservice architecture.
* Node.js, Angular.js, React.js or React native.
* DevOps experience with Heroku, AWS or Azure, Docker.
* Production experience with Elixir & Phoenix. 
* Understanding of OTP.

### Responsibilities

* Design and implement API endpoints for the Yojee API backend in Elixir.
* Participate in the Scrum process as part of the team.
* Take part in grooming meetings & provide input on how to solve requirements and build.
great architecture.
* Take ownership of the systems the team is responsible for and participate in their development were necessary.
* Follow best practices and produce high quality code.
* Maintain and improve existing Elixir code bases.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Engineering Manager.

### Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

### About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=61&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
