### ISSUE TITLE
VRED - SENIOR REACTJS DEVELOPER - HCM - FT

### ISSUE THREAD

**Issue by Lethanhthihr** [awesome-jobs/vietnam#1872]
## Location

* 104 Mai Thi Luu, Dakao Ward, District 1, HCMC

## Salary Expectation

* Negotiable

## Requirements
* Ideally 2+ years of experience with ReactJS.
* Experience working with JavaScript, ES6, and front-end web development.
* Proficient in ReactJS, understand lifecycle and best practices when designing React components.
* Experience working with Redux, Redux thunk, redux state, immutable data, one-way data flow.
* Know how to set up tests and use unit testing frameworks.
* Familiar with command line tools (npm, NodeJS, bash, shell scripts…).
* General understanding of fundamental software development and software engineering 
* knowledge: Web Service, API, HTTP, Git, CI/CD, Testing, Agile, Algorithm.
* Specialized in at least one CSS framework (Bootstrap/Foundation/…).

## Skills
* Good at teamwork skills
### Must Have
* Experience with Reactjs, Redux or Redux-saga

### Responsibilities
* Create modern, high performance JavaScript Framework (NodeJS, ReactJS, Redux…) sites from visual designs.
* Ensure cross-browser, cross-device performance, compatibility and responsiveness.
* Optimize application for maximum speed and scalability.
* Support Back-end development and troubleshooting.
* Ability to work independently as well as in a team.
* Keep abreast of latest development techniques and security practice.

### Why it would be awesome to work with us
* Competitive salary & stock option.
* Review salary raise every 6 months.
* Bonus: performance, team bonus.
* 13th month salary per year & Full working facilities.
* Social – Health – Insurance paid fully
* 12 annual leaves per year
* Annual company trip
* Professional and Flexible Working Environment
* Great Teamwork
* Extensive Training Program and Team-building activities, events.
…
### Interesting engineering projects
*Product: Fintech & Wholesales

### Contact
Email: hr@vred.com.vn
Skype: Thanhthi.hr
Phone: 0988 428 440

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
