### ISSUE TITLE
CINNAMON AI - PROJECT MANAGER - HN/HCM - FT

### ISSUE THREAD

**Issue by giangnguyen2710** [awesome-jobs/vietnam#1876]
## Location

* Hanoi, Ho Chi Minh

## Salary Expectation

* $1000 - $1600

### Must Have

* Strong in negotiation, communication skills, complex problem solving, problem sensitivity, time management, management of personnel resources.
* Attention to detail and multi-tasking skills
* Strong verbal and written expression
* Communicable English (speaking, listening & reading) and Business-professional English (document writing).
* Experience in software development of the web-based system on Linux.
* Understanding all aspects of the software life cycle, using Agile or Waterfall software development practices.

### Ideally

* Experience in software development with Scrum or and Kanban.
* Experience in handling multiple projects in the same period of time.
* Experience with modern project management tools.
* Experience in making proposals and defining requirements about systems, especially for an open system.
* PMP certification.
* AI technology knowledge.

### Responsibilities

* Ensure transparent communication among internal stakeholders, the Japanese sales team and the delivery team.
* Ensure resource availability and allocation. Facilitate and coordinate internal resources for the flawless execution of projects.
* Develop or update project plans for information technology projects including information such as project objectives, technologies, systems, information specifications, schedules, and staffing.
* Monitor or track project milestones and deliverables.
* Assign duties, responsibilities, and spans of authority to project personnel.
* Schedule and facilitate meetings related to information technology projects.
* Measure project performance using appropriate systems, tools, and techniques.
* Prepare project status reports by collecting, analyzing, and summarizing information and trends.
* Conduct analysis, report the current situation, issues and risks, and propose necessary
changes to the stakeholders.
* Create and maintain comprehensive project documentation.

### Why it would be awesome to work with us
* Competitive  allowance and benefits
* Full-time contracts will be offered based on your performance and potential to learn.
* An open working environment and full of opportunities for talents to grow.
* Offering training opportunities, education assistance, mentorship programs, collaborative learning sessions.
* A collaborative environment that fosters communication via slack and an open-door policy.

### Contact
Email: talent@cinnamon.is
Hotline: 0899.866.003 (Giang)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
