### ISSUE TITLE
Fetch - Full Stack (Javascript, .NET, C#) - Sai Gon - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#1878]
![image](https://user-images.githubusercontent.com/60914247/74222065-27138080-4ce6-11ea-80ff-1636dce6d16b.png)

## HCM

* Full Time

## Salary up to

* 1,700 USD/month

## About Fetch
* Fetch Technology is a comprehensive global provider of Human Resource Outsourcing Services in IT field such as recruitment, training and coaching programming languages, consulting and human resources management. Founded in 2016, Fetch Technology Vietnam helps IT organizations of all types and sizes unlock their business potential.
* We bring along our vision to the market: “to be the first-choice trusted partner for organizations and young people who is looking to build their future”.

* Our mission is to provide customized and high-touch human resource in IT field to organizations of all types and sizes, enabling their growth and help people get their jobs done right choice.

* For 2 years, we have built a wide reputation in Singapore, Malaysia, Vietnam… and has been trusted by many customers.

## About Client
* Our client is a Singapore’s fastest growing mobile ordering, payment, and loyalty platform. They have a mission: to make mobile ordering and payment the new way of life when dining out.
* Through their next-generation mobile point-of-sale (POS) that covers the entire customer ordering and payment process, they enhance customer experience, improve operating efficiency, and allow our merchants to stay connected with their customers and engage them anytime, anywhere. They launched their services in Singapore in 2018 and have since gained market share quickly while delivering best-in-class customer experience. 

* They are backed by some of the top-tier venture capitalist and entrepreneurs in the region, including the likes of East Ventures, Quest Ventures, Goh Yiping (ex-Matahari Mall chief product officer).

### Job Description

* 2+ years experience in C# and .NET Technologies.
* Proficient in .NET (Framework/Core).
* Good understanding in Domain Driven Design, SOLID Principles and Clean Architecture.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Experience in both SQL and NoSQL solutions.
* HTML, CSS, Javascript. ReactJS preferred.
* Keen on communication and able to work as a team.

### Why it would be awesome to work with us
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law;
12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
* Skype: trangdong0111@gmail.com
* Mail: trangdong@fetch.tech

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
