### ISSUE TITLE
Grab - Back-End Engineer - Saigon - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1879]
## Location

* **MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon**
* **The Grab Vietnam R&D lab** focuses on building and nurturing the best engineering talents from diverse academic backgrounds and industry experience to deliver high profile projects using data-driven methodologies.
* Join us if you want to grow and mentor others in a tight-knit lab out of Ho Chi Minh City.

## Salary Expectation

* Negotiable

## Requirements
* 5 years back-end experience
* Strong computer science fundamentals in algorithms and data structures
* Familiarity with running large scale micro-services services
* Strong understanding of system performance and scaling
* Excellent communication skills, sharp analytical abilities with proven design skills, ability to think critically system growth and stability
* Familiarity with AWS

## Skills
* ALL SKILL ACCEPTED 
* Golang Preferred 

### You’ll be responsible for

* Design and write with the cutting edge Golang to improve the availability, Scalability, latency, and efficiency of Grab's range of services.
* Work with engineering team to explore and create new design / architectures geared towards scale and performance. 
* Work with product managers, data analysts and implement products and features, and test their impact to business metrics.
* Participate in code and design reviews to maintain our high development standards.
* Work closely with infrastructure team in building and scaling back-end services as well as performing root cause analysis investigations.
* Design, build, analyze and fix large-scale systems.
* Debug and modify complex, production software.

### Why it would be awesome to work with us

* A culture of learning.
* Free rides with Grab.
* Medical coverage. Extra Medical Insurance.
* MacBook is provided.
* 14 days annual leaves.
* Diverse teams.
* Weekly Tech talks.
* High growth opportunities.
* Quarterly Hackathons. 
* Flexible working hours. 

### Interesting engineering projects

* Grab began as a taxi-hailing app in 2012, but has extended its product platform to include **private car services (GrabCar & GrabShare)**, **motorcycle taxis (GrabBike)**, **social carpooling (GrabHitch)**, **last mile delivery (GrabExpress & GrabFood)**, **bus & shuttle services (GrabCoach & GrabShuttle)** as well as a **mobile payments services (GrabPay)**. We are focused on pioneering new commuting and payment alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in **Singapore, Indonesia, Philippines, Malaysia, Thailand, Vietnam, and Myanmar**; however, we also have **R&D offices** in **Singapore, Seattle, Beijing, Bangalore, Jakarta, & Vietnam.**

### Contact
* Email: **cuong.vo0906@gmail.com**
** Titles: **Grab_Position_Your Name** 
* Skype: _**live:cuong.vo0906**_

**Comment by qcam** [comment]
We have received report claiming this post is a scam.
