### ISSUE TITLE
Cookpad Inc. - Web Engineer - Vietnam/Remote & extensive travel - C

### ISSUE THREAD

**Issue by vietzombie** [awesome-jobs/vietnam#188]
![cookpad logo](https://global.cpcdn.com/en/assets/logo_cookpad_large-827bc0b34d5c7ab322d3ff8de882e9f828d06bc5ae46d09c88d25aaf02686132.png)
## Who we are

Cookpad Inc. (TSE 2193) is the largest online recipe sharing service in the world. Since its launch in 1997, Cookpad has attracted about 2.5 million recipes and 80 million unique users in Japan & other countries (as of Feb 2016). Our mission is to **make everyday cooking fun** for people of all ages. 🍚🍳😄    

Since 2014, Cookpad service has been expanding internationally and is now available in Vietnamese, English, Spanish, Indonesian, Thai, Arabic and Filipino. We are currently seeking Vietnamese candidates with a passion to share our value to Vietnamese as well as global audience.

https://cookpad.com/vn
https://cookpad.com/vn/download
## Why you should join us

[![Why join Cookpad](https://i.ytimg.com/vi/6Z2ZpTefbjU/mqdefault.jpg)](https://youtu.be/6Z2ZpTefbjU)
[Watch video](https://youtu.be/6Z2ZpTefbjU)

We are looking for a talented person, who shares our passion and can help us push the development of Cookpad service in Vietnam and globally. Headquartered in Tokyo, we have international offices in USA, Spain, Indonesia, Lebanon, India and more to come. We work and collaborate online, and often get together in different countries to be closer to and understand our users. 
## Responsibilities
- Develop Cookpad’s global platform together with the international team
- Build Cookpad Vietnam engineer team 
## Basic qualification
- Motivation, capacity and versatility to work in a global team
- Deep insights and experience working directly with users
- Fluent Vietnamese and English are essential
- Understand basic technologies to support each device of PC web, Smartphone app, Smartphone web, Tablet, as well as comprehensive overview of basic use case in each device
- Knowledge of Ruby on Rails is welcome
## Ideal candidate has experience in one or several of the followings
- Familiar with relational databases
- Experience in designing UX
- Experience in developing large scale internet services
## Location
- Vietnam/Remote
- Extensive travel overseas to international Cookpad offices 
## Salary Expectation
- Negotiable
### Contact

Trang Yazu: info-vn@cookpad.com. Send us:
1. Your resume
2. Example app codebase that shows your best work
3. Github profile link, and 
4. Tell us "Why Cookpad?" 😎

**Comment by karmiphuc** [comment]
Q&A Transcript from Vietnam Ruby chatroom with CookPad
---

#### Context
> [@trang-yazu](https://vietnamrb.slack.com/team/trang-yazu):
> Hi, my name is Trang. I joined Cookpad 1 year ago in March 2015. I’m in charge of Cookpad Vietnam, finance and M&A of Intl biz development team.
> Before Cookpad, I was working in an American hedge fund in Spore. My career has been in equity investments in different countries.
> Our pleasure to join your community and thank you very much for joining this Q&A.
> Today Q&A is about the web engineer position, working remotely in Vietnam with intl team. If you wish to relocate to Tokyo, that would be great, too. We are flexible re locations.
> Also, we are looking for iOS/Android engineers and can have another Q&A re these positions.
> Re any tech questions, feel free to email for me to forward to our head engineer. We may be able to do another Q&A if there is demand.

#### Q&A Log

_Disclaimer: All answers came directly from the Slack account of CookPad's representative, [trang-yazu](https://vietnamrb.slack.com/team/trang-yazu), on [Vietnam Ruby chatroom](https://vietnamrb.slack.com/archives/jobs/p1460597897000381). Vietnam Ruby admins or administrators won't be held liable on those answers._

1.  I find the resemblance between https://cookpad.com/vn and http://www.cooky.vn/, what are the differences in your product
>A: We welcome competition. It encourages us to grow ourselves. Moreover, more cooking online services will help make cooking easier and more fun for more people :smile: Actually, we wanna ask you: What do you think about cooky.vn? Tech-wise and service-wise? Which will be popular in VN in the future? and why?

2. I found that Cookpad developers contribute back to the community a lot. Did they do that in their free time or they were allowed to work on open source software in work time (like Google 20% time).
>A: It depends. As long as engineers can deliver results in their work, it is fine. We encourage engineers to contribute back to community. Many cookpad engineers write books and talk at conferences.

3. Chị ơi, chị có thể cho các bạn ở đây biết nhiều hơn về phúc lợi của `Cookpad`
>A: Do you mean benefits working in Vietnam or in Japan?

4. What are the requirements for Web engineer? What should I do for remote working?
>A: Ruby on Rails knowledge is welcome. Other pluses: Experience developing services for multi-million users, start-up experience.
We do not understand your second question. Can you help elaborate?

5. Do you offer stock option for the hired employees?
>A: It depends.

6. Team size của `Android` và `iOS` là bao nhiêu người.
>A: Currently fewer than 20 engineers in global app teams. The team is taking care of over 10 million users. We are looking for more talented and passionate people :simple_smile:

7. Trong công ty có team `R&D` để research mấy cái lạ lạ trước khi xài không
>A: Yes.

8. I heard of the hardworking culture of Japan, is it fair to say that Cookpad follow the same culture? What do you believe in productivity?
>A: Yes, we work hard, and we care about our employees’ happiness and health. Our working time is flexible, so each engineer needs to manage his own time —> result oriented, entrepreneurial and strong independent working skills are required

9. Does Cookpad have a career roadmap for senior developers?
>A: It is up to the developer’s interests. He/she can choose to become an expert engineer or manager.

10. How do you keep tracking the people that are working remotely?
>A: Work deliverables and results

11. Why recruiting from Vietnam? Is there anything in particular that interests you? What about other South East Asian countries? 
>A: Good questions. Because there is a demand to make cooking fun in Vietnam, and we think we are the best team to deliver this mission to Vietnamese users. :wink:
Our service is also available in Indonesian and Thai.

12. What are your current challenges as a remote team?_
>A: Good question! We make best effort to communicate regularly with remote teams to share our value and mission. For example, we have regular global call directly with Cookpad founder.

13. What could be preventing your company from growing?
>A: We grow with passion and focus on our mission.

14. Top 3 things that your team need to improve on?
>A: People. People. People
