### ISSUE TITLE
Grab - Software Engineer, Full-Stack (Golang, ReactJS) - Saigon - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1880]
## Location

* **MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon**

## Salary Expectation

* Negotiable

## Requirements
* Web stack (front-end, back-end and database)
* Go, Java, JavaScript, C# or Python
* MySQL, PostgreSQL, Oracle, etc.
* 8+ years Software Engineering experience.

### Must Have

* A proactive approach in terms of getting things done in a fast-paced environment.
* Taking ownership and responsibility of components and modules.
* Being a team player and helping the team achieve shared objectives.
* Intensive knowledge and hands-on experience with at least one modern JavaScript UI framework such as React, Ember, Angular, etc. for single page application development.
* Good understanding of modern web frameworks and security.
* Experience in building micro-services, designing and implementing Rest APIs using Go or Java.

### You’ll be responsible for

* Propose and help the team to decide scalable web applications architecture.
* Write high-quality web components and build products that delight our end-users.
* Design and implement scalable and reliable RESTful APIs.
* Develop dynamic and responsive web interfaces using React framework.
* Write unit, functional and end-to-end tests.
* Collaborate closely with User Experience Design, Product, Development, Finance, and Operations teams.
* Identify and resolve performance and scalability issues.
* Help the team to review and ensure clean and efficient code.

### Why it would be awesome to work with us
* A culture of learning.
* Free rides with Grab.
* Medical coverage. Extra Medical Insurance.
* MacBook is provided.
* 14 days annual leaves.
* Diverse teams.
* Weekly Tech talks.
* High growth opportunities.
* Quarterly Hackathons. 
* Flexible working hours. 

### Interesting engineering projects

* Grab began as a taxi-hailing app in 2012, but has extended its product platform to include **private car services (GrabCar & GrabShare)**, **motorcycle taxis (GrabBike)**, **social carpooling (GrabHitch)**, **last mile delivery (GrabExpress & GrabFood)**, **bus & shuttle services (GrabCoach & GrabShuttle)** as well as a **mobile payments services (GrabPay)**. We are focused on pioneering new commuting and payment alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in **Singapore, Indonesia, Philippines, Malaysia, Thailand, Vietnam, and Myanmar**; however, we also have **R&D offices** in **Singapore, Seattle, Beijing, Bangalore, Jakarta, & Vietnam.**

### Contact
* Email: **cuong.vo0906@gmail.com**
** Titles: **Grab_Position_Your Name** 
* Skype: _**live:cuong.vo0906**_

**Comment by qcam** [comment]
We have received report that this post is a scam.
