### ISSUE TITLE
Grab - Senior/Lead Software Engineer, Front-End - Saigon - FT

### ISSUE THREAD

**Issue by cuongvo0906** [awesome-jobs/vietnam#1881]
## Location

* **MapleTree, 1060 Nguyen Van Linh Str., District 7, Saigon**
* **The Grab Vietnam R&D lab** focuses on building and nurturing the best engineering talents from diverse academic backgrounds and industry experience to deliver high profile projects using data-driven methodologies.
* Join us if you want to grow and mentor others in a tight-knit lab out of Ho Chi Minh City.

## Salary Expectation

* Negotiable

## Requirements
* 8 years of professional experience
* Familiarity with the entire web stack (front-end, back-end and database)
* React framework

### Must Have

* A proactive approach in terms of getting things done in a fast-paced environment.
* Taking ownership and responsibility of components and modules.
* Being a team player and helping the team achieve shared objectives.
* Good understanding of modern web frameworks.
* Knowledge of web security and performance.
* Knowledge and experience with Software Design patterns.
* Knowledge and experience with Application Integration patterns.

### You’ll be responsible for

* Write high-quality web applications that delight end-users of the product.
- Develop dynamic and responsive web interfaces using React framework.
- Develop reusable web components.
- Write unit, functional and end-to-end tests.
- Identify and resolve performance and scalability issues.
- Convert from design/prototype to responsive interface on the web.
- Work with product managers, data analysts and UI designers to implement products and features, and test their impact on business metrics.
- Participate in code and design reviews to maintain our high development standards.
- Engage in service capacity and demand planning, software performance analysis, tuning and optimization.
- Design, build, analyze and fix large-scale systems.
- Debug and modify complex, production software.

### Why it would be awesome to work with us
* A culture of learning.
* Free rides with Grab.
* Medical coverage. Extra Medical Insurance.
* MacBook is provided.
* 14 days annual leaves.
* Diverse teams.
* Weekly Tech talks.
* High growth opportunities.
* Quarterly Hackathons. 
* Flexible working hours. 

### Interesting engineering projects
* Grab began as a taxi-hailing app in 2012, but has extended its product platform to include **private car services (GrabCar & GrabShare)**, **motorcycle taxis (GrabBike)**, **social carpooling (GrabHitch)**, **last mile delivery (GrabExpress & GrabFood)**, **bus & shuttle services (GrabCoach & GrabShuttle)** as well as a **mobile payments services (GrabPay)**. We are focused on pioneering new commuting and payment alternatives for drivers and passengers with an emphasis on speed, safety, and reliability. Currently we offer services in **Singapore, Indonesia, Philippines, Malaysia, Thailand, Vietnam, and Myanmar**; however, we also have **R&D offices** in **Singapore, Seattle, Beijing, Bangalore, Jakarta, & Vietnam.**

### Contact
* Email: **cuong.vo0906@gmail.com**
** Titles: **Grab_Position_Your Name** 
* Skype: _**live:cuong.vo0906**_

**Comment by qcam** [comment]
We have received a report that this post is a scam.
