### ISSUE TITLE
Rabiloo - Software Engineer - Hanoi - FT 

### ISSUE THREAD

**Issue by phuongg2298** [awesome-jobs/vietnam#1882]
![83514582_816367752172259_4622606634202431488_o](https://user-images.githubusercontent.com/60953858/74301272-2847ba80-4d85-11ea-9cb0-2c8311116ee9.jpg)

## Location

- 3F C14 Bac Ha Building, To Huu Street, Nam Tu Liem District, Ha Noi. 

## Salary Expectation

- VND 8M to VND 25M per month

## Requirements

- At least 1 year experience in Software Development 
- Great problem-solving skill
- Good knowledge of Computer Science (Algorithm, Data Structure, Object-oriented Design, Databases) 
- Experience with one of these programming languages: C/C++, Java, Python, Javascript
- Have knowledge of dispersion system and asynchronous architecture
- Good communication skills, and collaborate well with others members 

## Responsibilities

- Develop system from Japanese customers’ requests and our company (Now we are building a new product – which is a AI Chatbot Platform - fanpage, online sales management software)
- Responsible for maintaining, processing the product after release
- Research, study new technologies to adapt to new projects 

## Why it would be awesome to work with us

- Attractive salary and twice-a-year salary review on April and October
- Social insurance, health insurance paid fully
- Working in a professional, young and friendly environment 
- 13th, 14th month salary
- Extensive on job training and skills: technological skills, soft skill, project management skills…
- Free Japanese or English classes in company 
- Learn new knowledge: Big Data, AI, NLP, chatbot, Image processing
- Annual leaves: from probation contracts 
- Company trip, Year-End Party, Teambuilding, Picnic, etc
- Football Club, Game Club
- Free in-house entertainment facilities: tea, coffee and snack (instant noodles, candies, cookies..) 

## Contact

- CV send to email: hr@rabiloo.com  
- Title mail: Name_Job Position
- Phone number: Ms Giang 0359855389 or via skype live:danggiang1
- Website: http://rabiloo.com  
- Fanpage: https://www.facebook.com/RabilooOfficial/ 
- Location: 3F C14 Bac Ha Building, To Huu Street, Nam Tu Liem District, Ha Noi.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
