### ISSUE TITLE
[SportContract] Experienced FullStack developer - 100% Remote

### ISSUE THREAD

**Issue by ptgamr** [awesome-jobs/vietnam#1883]
## About SportContract
SportContract is a video, analytics and scouting platform in pro hockey. We are partner with hockey leagues and clubs worldwide. 

Website: https://sportcontract.net
LinkedIn: https://www.linkedin.com/company/sportcontract/
Instagram: https://www.instagram.com/sportcontract/

## Location
* 100% Remote
* Daily meeting @Gmeet - 8AM UTC (usually 2PM, Vietnam time)

## Salary Expectation
* Negotiable

## The ideal candidate's skills
* Confident with JavaScript (both frontend & backend)
* Experienced with React / Redux / Hook & Usage with TypeScript
* React Native (Android + iOS)
* **Most important**: Ability to work independently and asking the right questions

## Nice to have
* AngularJS
* Docker, Kubernetes
* Elixir / Rust
* Machine Learning, Computer Vision
* Passion for technology application in sports

## What you will be working with?
* A **Web Platform for Video Analytics and Scouting** - used by hundreds of Hockey clubs and players around Europe and North America in their day-to-day training. It's originally written in **AngularJS 1.7x + TypeScript** - still function very well and we enjoy maintaining the existing features. However, all new features (like our next-generation Video Tagging Editor) will be written in **React + TypeScript** - we will slowly migrating the whole platform to a more modern stack.
* A **Mobile Application** written in **React Native**, which brings users functionalities like: realtime chat, watch hockey videos, create and share playlists.
* All powered by a **backend microservices infrastructure** written in **NodeJS / Elixir / Rust**. We started the migration to **Kubernetes**, it would be awesome if you could help with that.

## Why it would be awesome to work with us?
* Our team is lean and you will have the chance to make visible impact in a short time.
We do not wait for a big release, we releases many continuous improvements to our users in a daily basics, as fast as we can.
* We move fast and constantly adapt to new/modern technology.
* The Sport Industry is big and Hockey is just the starting point, later it can be football, basketball etc. We started with hockey because our CEO is a former Professional Hockey Player & FIFA staff. He has lots of connections in the Sport world. Our task is just focusing on creating awesome products! 
## It's a big NO if you:
* Expect to be told what to-do - because we want your input on how to solve things
* Expect a team that run with traditional Software Development process - because we favor pragmatism, to bring values to users in the fastest way possible.
* Could not explain technical problem in fluent English.
* Do not like to ask questions.

### How to apply & Contact

If you find this job interested and want to join our team, please send me an email with your Resume and several sentences to express your interest and reasons why you think you're a good fit.

Anh Trinh (anh.trinh@sportcontract.net)

**Comment by ptgamr** [comment]
I've got a couple of emails asking how to apply... sorry for not being clear!

 I have updated the last section to indicate how to apply for the job.

Thanks for your interest

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
