### ISSUE TITLE
ZIGExN VeNtura - Ruby on Rails Developer - SaiGon - FT

### ISSUE THREAD

**Issue by phuctm92** [awesome-jobs/vietnam#1884]
## Location
* 131 Xô Viết Nghệ Tĩnh, P.17, Binh Thanh

## Working Time
* Monday - Friday
* Full-time
* No OT

## Salary Range
* 1000$-2500$

## Responsibility
* Join in a product/system design phase with Japan team to analyze system requirements.
* Suggest, propose creative solutions to solve problems.
* Design, develop and test high-traffic Web applications in Ruby on Rails (sometimes do DevOps to deploy to production).
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

## Requirements
* Graduated from College/University in Information Technology/Computer .
* **At least 02 year experience** as a Ruby on Rails Developer.
* Experience with Ruby, Ruby on Rails frameworks.
* High level Object oriented programming skills.
* Relational database design and implementation using PostgreSQL/MySQL.
* Basic understanding of front-end technologies, such as HTML, JavaScript, CSS and jQuery.
* Strong analytical and problem solving abilities, support other members and can do code reviews.

## Nice to have
* Experience with Redis, Index Engines (Apache Solr, Elastic Search).
* Experience setting up servers (Nginx, Apache, etc.) and automating deployment process (Capistrano, Ansible, Chef, etc.)
* Experience using GCP (VM, GLB, VPC, GCS, CloudSQL, CloudSDK, etc.) or AWS (EC2, S3, SQS, Lambda, etc.)
* Experience writing tests with RSpec and doing Continuous Integration.

## Language Skills:
* Can basically communicate (writing, speaking) in English.
* Japanese is a huge plus

## Why it would be awesome to work with us
* 15-18 days of paid leave for employees with 1+ year of working.
* 13th month salary.
* Performance review every quarter to improve performance, level.
* Salary raises or bonus by work performance every 6 months.
* Bao Viet Healthcare Insurance.
* Annual health check
* All insurances according to Vietnamese Labor law.
* Awards for most outstanding individuals every quarter, year.
* Company activities: monthly team meetups, monthly birthday, yearly company trip, quarterly and annual events,...
* Happy events: New Year, Halloween, Mentors' Day,  X-mas,…
* Support fee for parking, lunch, marriages, child births, hospitalization,...

## Contact
Skype: live:10c62f4b786a844 
Email: phuc.tm4192@gmail.com

**Comment by zoegod911** [comment]
I am interested: techniquea2z@protonmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
