### ISSUE TITLE
Code Eninge Studio - Java Developer - Danang - FT

### ISSUE THREAD

**Issue by shchoi78** [awesome-jobs/vietnam#1885]
## Location

* Danang, Vietnam

## Salary Expectation

* $800-$2000/month

## Requirements
* Java
* 4+ years of experience

### Must Have

* In-depth knowledge of relational databases and NoSQL databases
* Write high-quality, clean, maintanable code using engineering best practices (unit testing, source control, continuous integration, automation, etc.)
* Skilled with Java/JSP/JSF, MVC, Spring/Struts Framework, XML/XSLT/XPATH, REST/JSON/SOAP and Java Application server technologies

### Ideally

* Experience with Liferay, Java-based portal and CMS.  
* Experience with OSGi, Jenkins, AWS, Advance caching and indexing, LDAP/SSO/OAuth
* Experience in Service Oriented Architecture, Web Services, Design Patterns, RDBMS and other data sources.
* Experience designing data models (logical and physical models), and constructing database schemas and complex SQL queries,
* Implementing automated testing platforms

### Responsibilities

Working together with our team to deliver projects for many of our clients across the world.  Demonstrate technical leadership through self-assignment of tasks and using appropriate technical solutions and architecture.  Perform design and code reviews and teach the team good coding practices and logic.  Participate in installation, on-going maintenance and production support of software systems.

### Why it would be awesome to work with us
We are a digital outsourcing and technology partner who helps our clients in USA, Canada, Europe and SE Asia. We succeed by turning our clients ideas and strategies ito high-end digital products.  We are an international team of passionate people who believe that doing our best work comes from within.  When you join our family we care about who you are and not just what you do.  Our vision is to help our employees reach their greatest potential by helping them develop their skills and character.  

We take pride in creating a great company culture that builds up the team, and that together we can accomplish anything!  We are also more than our work and give back to this city through community service programs.

### Benefit Highlights
* Fun and open family like work
* Excellent salary with 13th month and performance bonus
* Additional 4 Million in health allowance renewed yearly
* Additional 4 Million in training allowance renewed yearly
* Work M-F with no overtime hours.
* 12 days of vacation + Standard holidays and Christmas holiday and 5 days of paid sick leave
* Emphasis on personal and career devlopment (2 hrs/week of English classes and weekly soft skills training)
* Free lunch everyday and monthly team social events

### Contact
Homepage: www.codeenginestudio.com
FB: www.fb.com/codeengine
Apply at https://codeenginestudio.freshteam.com/jobs/-5V-0GHHxBTg/java-developer-intermediate-to-senior?source=Direct_3000076456&medium=Social_3000070649

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
