### ISSUE TITLE
JavisEnterprise - Ruby Developer - Hanoi - FT

### ISSUE THREAD

**Issue by thuhangnguyen280895** [awesome-jobs/vietnam#1889]
## Location
* Hanoi, Vietnam
* Fulltime
- Make web service using Ruby on Rails.
- Representative Web service :
    - Curation SNS
    - 50 ~ 100 pages including admin.
    - Responsive design.
    - Needs to behave quickly.
- And Join other web service projects
## Salary Expectation
* $1500/month 
## Requirements
- Rails coding
- Git, gitflow, unit testing.
- wiring clean codes.
- Can make good performance structure, codes and SQL.
- Can do text base communication in English normally.
## Skills
 - php
 - react.js
* Experience with 
- join or make big web service project which needs high response speed
- use docker and using it on deploy.
## Why it would be awesome to work with us
• Attractive salary and annual salary review.
• Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
• Working directly with foreign client, all your dedication to work will be fairly recognized for performance review
• Extensive on job training, you will always have chance to work with new emerging technologies.
• Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law;
    12-day annual leave per year.
• 13th month salary.
Contact
• Mail: mshangnguyen@javis.vn
• Fb direct: https://www.facebook.com/pippy95

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
