### ISSUE TITLE
Quoine - (Senior) Blockchain Engineer - Saigon - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1890]
# Location

* D.1, Saigon, Vietnam

# Salary Range

* US $1500 - $4000

#### We are looking for passionate Blockchain Engineers (at middle and senior levels) to help bring our product to the next level while advancing their career in this challenging yet fascinating field.  

# Responsibility 
#### As Blockchain Engineer at QUOINE, you will:

* build and maintain the crypto asset platform that controls crypto funds in and out of the company. This is a banking-grade system that requires extreme attention to detail from engineers that have a good sense of quality and security.
* solve hard problems to build a new blockchain system and ensure its robustness, performance, and scalability. The blockchain plays a central role in the company’s commitment to innovation and contributes to the Blockchain ecosystem as a whole.

# Requirement
## Others

* Proactive and self-starter
* Engineers who can take ownership of different components in the system
* Honest, intelligent, able to get things done
* Conversational and written English
* Have strong skill sets to handle multiple projects at the same time

# Why it would be awesome to work with us?

* Join a global leading Fintech company
* Bring cutting-edge technologies into play
* Enjoy exceptional benefits package (tech/non-tech training courses, gym sponsor, extra health insurance for you and your immediate family, daily snack, billiards competition, football weekly... you name it.)
* Work in one of the most modern & innovative spaces in town

# Contact

* Homepage: https://careers.liquid.com/
* E: linh.truong@quoine.com 
* M: 0938 019 369
* Skype: linh.truong.my

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
