### ISSUE TITLE
Fetch - Senior Android - HCM - FT

### ISSUE THREAD

**Issue by xuandoan** [awesome-jobs/vietnam#1892]
## General

* Location: 42B Ho Ba Phan Street, Phuoc Long A Ward, District 9, HCMC
* Type: Fulltime
* Salary range: $1000-2000
* Working time: 9AM - 6PM, Mon to Fri

## About company:
* Company is a leading digital wallet service in the Southeast Asia Region, where consumers can easily purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin... The company was founded in 2014 and headquartered in Singapore.

## Requirements
* At least 3 years of native Android app development experience for seniors.
* A degree in computer science, software engineering, information technology or related fields.
* Strong CS fundamentals (with competencies in algorithms and data structures).
* Strong UX/UI design exposure and experience in making apps work intuitively and with pixel perfect interfaces.
* Experience in API design, SDK architecture, and mobile software lifecycle development practices.
* Proficient in Java, Kotlin with experience in memory management and caching mechanisms specific to mobile devices.
* Highly accountable and takes ownership, with collaborative attitude, and a lifelong learner.

## Benefit:
* Attractive salary and annual salary review,
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact
* Email: xavia@fetch.tech
* Skype: live:afcf1eb1181fcd5c

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
