### ISSUE TITLE
Ymese - Full Stack PHP Developer - Danang - FT

### ISSUE THREAD

**Issue by gaupoit** [awesome-jobs/vietnam#1893]
## Location

* Danang, Vietnam

## Salary Expectation

* $800-$1500/month 

## Requirements
* 3+ years experience with PHP
* 2+ years experience with Modern Front End Framework (Vue, React)
* Strong knowledge with cloud computing technology (preferably AWS)
* Strong experience with HTML5, CSS & SASS

### Must Have

* Write high-quality, clean, maintainable code using engineering best practices (unit testing, source control, continuous integration, automation, etc.)
* In-depth knowledge of PHP and JavaScript
* Self-motivation and good time management are required for this role

### Ideally

* Experience in building WordPress plugins
* Experience with cloud computing technology (preferably AWS)
* Leadership and mentorship 

### Responsibilities

* Plan, develop, test and maintain major features for our main plugins and extensions 
* Review, optimize, and refactor existing codes with other team members
* Troubleshoot customer’s reported bugs and issue as well as coming up with good solutions 
* Suggest improvements and best practices in terms of security and performance. At Ymese, your voice is always be heard
* Create product documentation and write tutorial blog posts sharing knowledge with our team members and audiences
* Mentor junior developers in the team

### Why it would be awesome to work with us

* Stock options and/or annual profit sharing available
* Flexible working hours (8.30 am – 5.00 pm), from Monday to Friday
* Dynamic and friendly working environment
* Freedom to get creative in managing your own and team work
* Monthly bonus plus 13th, 14th and 15th-month salary if performing consistently well
* Free lunch and petrol if you live far from the office
* Snack bar, sports activities after work, e.g. football & badminton

### Interested?
Please email your CV and Cover letter (English preferred) to hello@ymese.com with the subject:
[Senior Developer] – Full name
In your email or cover letter, please explain why you think you’re suitable for this position.
We can’t wait to see and get to know you personally.

### Contact
Homepage: https://ymese.com/

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
