### ISSUE TITLE
GoldenCloud - Go/Vuejs Developer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by nguyenvanduocit** [awesome-jobs/vietnam#1894]
## Location

* Charmington La Pointe Building, 181 Cao Thang Str, Ward 12, District 10, Ho Chi Minh.
* Fulltime.

## Salary Expectation

* $800 - $1200/month.

## Requirements

* 2+ years experience in Golang or Python/NodeJS/PHP and willing to challenge yourself with Golang.
* 1+ year(s) experience in Vuejs.
* AWS products.
* Serverless.
* MongoDB.
* Self-motivated to work with little supervision.
* Result-oriented.

### Nice to have

* Be able to fly.
* Experience with high-performance websites catering to millions of daily traffic.
* Experienced in building the Shopify app.

### You’ll be responsible for

* Building applications on the Shopify platform.

### You can bring

* Underwear (in case you can fly).

### Why it would be awesome to work with us

~Well, just like any other start-up company.~

* Bonus.
* Join a great team to conquer the world.
* Company Trip and Team building annually.
* Training to develop our employees.
* Performance Review every year to adjust Salary and title/position.

### Interesting engineering projects

* 100% serverless backend.
* Modular front end with Vuejs.

### Contact

Homepage: [trueProfit.io](https://trueprofit.io)
Mr. Được: duocnguyen@goldencloud.io

**Comment by dongnguyenltqb** [comment]
https://dongnguyen.dev
Please look at my cv on this site and i hope that i have a chance.

**Comment by nguyenvanduocit** [comment]
@dongnguyenltqb Thank you for a good CV, we are considering.

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
