### ISSUE TITLE
Parcel Perform - DevOps Engineer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#1895]
![image001](https://user-images.githubusercontent.com/49466111/59088978-38281880-8933-11e9-95f8-2bace44d6968.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $700 - 1,200

## Skills
* 2+ years of experience using a broad range of cloud technologies, especially AWS.
* Strong scripting (e.g. Python) and automation skills. Software development background is a strong plus.
* Experienced with system and application monitoring tools.
* Familiar with Unix-based environments.

### Must Have
* Strong scripting (e.g. Python)

### Responsibilities

Our DevOps team is responsible for the deployment and maintenance of Parcel Perform cloud-based SaaS solution. We want DevOps to focus on building platform rather than running operational chores, so we are pretty much working on automating ourselves out of the job. As part of the DevOps team, you will be driving Parcel Perform engineering culture in a number of ways:
* Decide how our code gets deployed and automated. Parcel Perform deploys code in small chunks, multiple times a day, across different services. Having a fluid pipeline and knowing exactly what went wrong, where are crucial for us.
* Engage in the discussion when to use existing services from the cloud provider and when to build the in-house product, all in the name of productivity and cost-efficiency.
* Envision Parcel Perform system as a whole and how can it stay relevant in the next 5 years. To be honest, we absolutely want to stay relevant longer than that, but technology is ever-changing, deciding what exists today and still makes sense in the next 5 years is already challenging.

### Why it would be awesome to work with us
* The opportunity to work in a fast-growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing, and focuses on succeeding - we
continuously work with you on your strengths and weaknesses across many important
dimensions, and look at ways for you to address them and further your development
* Your entry ticket into being part of the Parcel Perform startup Universe, where you will work with and alongside people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast-growing company like competitive salary, extra insurance, free lunch, free fruit, snacks, cool oﬃce, team bonding events, various training programs, and more.

### Interesting engineering projects
You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide.

### Contact
Find more jobs and apply on https://www.parcelperform.com/careers
Or drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)

![image](https://user-images.githubusercontent.com/49466111/74827292-c2889f00-533f-11ea-909b-fe9ce3b83aeb.png)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
