### ISSUE TITLE
Linagora - Fullstack Javascript Developer - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1897]
## Location

* 4th Floor, Viet Tower Building, No. 1 Thai Ha, Dong Da Dist., Hanoi

## Salary Expectation

* Up to $2000 (Gross)

## Requirements

* Background in Computer Science/ Information Technology or equivalent
* Strong knowledge of JavaScript, NodeJS
* Knowledge of the Git version control system
* Experience with at least some of the following technologies: NoSQL, AngularJS, ExpressJS, VueJS
* Awareness of latest technologies and the discipline to know when to make use of them instead of using a proven solution
* Good level in English

### Ideally

* Eventually an experience in UI and UX design
* Knowledge of the Docker 
* Contribution to open source projects on Github

### You’ll be responsible for

* Write high-quality, clean, maintainable, reusable code using engineering best practices (unit testing, source control, continuous integration, automation, design patterns, etc.).
* Analyze requirements, design and develop features
* Understand the product, constantly optimize the product, identify and fix problems, improve stability and user experience
* Collaborate with fellow developers, product managers, user experience designer, and operation engineers to build products with web technologies
* Optimize application for maximum performance and scalability.
* Participate in regular internal technology sharing and other regional tech event.

### Why it would be awesome to work with us

* Work in an international team with high skilled people
* Opportunity to be promoted to senior/management position in company that is having a huge growth in Hanoi
* Correct work-life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week , from Monday to Friday
* Lunch allowance, 13th month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate to Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact

Email: vnhr@linagora.com
Phone: 84-86-550-4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
