### ISSUE TITLE
Linagora - DevOps Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1898]
## Location

* 4th Floor, Viet Tower Building, No. 1 Thai Ha Str, Dong Da Dist., Hanoi

## Salary Expectation

* Up to $2000 (Gross)

## Requirements

* Background in Computer Science / Information Technology or equivalent.
* Knowledge of CI/CD and IT security concepts
* Knowledge of Sourcecode Mangement Systems: Gitlab, Github, Bitbucket
* Knowledge and experience of Kubernetes (k8s), Docker•
* Knowledge of Provisioning and Configuration Management tools such as Ansible, Terraform, Puppet is a plus
* Good level of English

### You’ll be responsible for

* Implement and improve monitoring and alerting
* Build and maintain highly available systems on Kubernetes
* Implement and manage CI/CD pipelines
* Implement an auto-scaling system for our Kubernetes nodes
* Participate in on-call rotations

### Why it would be awesome to work with us

Work in an international team with high skilled people
* Opportunity to be promoted to senior/management position in company that is having a huge growth in Hanoi
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week , from Monday to Friday
* Lunch allowance, 13th month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate to Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact
Email: vnhr@linagora.com
Phone: 84-86-550-4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
