### ISSUE TITLE
Linagora - Automation Tester - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1899]
## Location

* 4th Floor, Viet Tower Building, No. 1 Thai Ha Str., Dong Da Dist, Hanoi

## Salary Expectation

* Up to $1000 (Gross) 

## Requirements

*Have any degree or certificate in IT field.
* Have knowledge about automation test for Web or Mobile.Have knowledge about Selenium Webdriver or one of the automation testing. framework (Ex: Robotframework, Cucumber, WebdriverIo, ... ).
* Have basic knowledge about programming language.
* Knowledge of HTML, CSS, JavaScript.
* Knowledge of HTTP/HTTPS protocol.
* At least 1 year's experience on Automation testing.

### You’ll be responsible for

* Work on an Open Source platform
* Business is all around collaboration and communication for enterprise: emails, calendars, contacts, chat, video conference, document management & edition.
* Analyze users stories and/use cases/requirements for validity and feasibility
* Design test plans, test cases/test procedures
* Creation, execution and maintenance of the automated scripts.- Report bugs if found any when run automation or perform manual test.
* Collaborate closely with other team members and departments to ensure the automated scripts work effectively and the quality of product.
* Building a new Facebook

### Why it would be awesome to work with us

* Work in an international team with high skilled people.
* Opportunity to be promoted to senior/management position in company that is having a huge growth in Hanoi.
* Correct work/life balance.
* Annual company trip, other exciting activities for team building.
* Working 5 days/week , from Monday to Friday.
* Lunch allowance, 13th month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate to Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

Email: vnhr@linagora.com
Phone: 84-86-550-4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
