### ISSUE TITLE
eMobi - Senior Quality Control - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#1907]
## Location
* Saigon, Vietnam

## Salary Expectation
* $900 - $1200 gross /month

## Requirements
* Minimum 2 years experience in software quality control (test case designing, black and
white box testing techniques, quality concepts etc.)
* Good knowledge in testing process, quality models, and standards
* Identify, isolate, and track bugs throughout testing cycle
* Good logical, critical, and analytical skills, report writing skills, communication skills, and
problem solving skills
* Capable of English speaking, writing and listening skills which is equivalent to TOEIC 550
scores
* Know at least one programming language (Java , Kotlin, Scala)
* Hands-on experience with a Test Management tool: Zephyr/TestRail/others.
* Hands-on experience with some more Testing tools: Generate Test data, Layout test, GA
tracking, JMeter, others
* Hands-on experience in performance tests and ability to work independently – self-directed
* Hands-on experience at test automation studio/tools (keyword-driven, data-driven)
* Good knowledge of Cloud-based apps (AWS, Azure, etc.)
* Aptitude to learn and understand new and emerging technologies

## Responsibilities
* Take responsibility for establishing, implementing, maintaining and improving the process
compliance of each aspect of our development
* Design test plans and test cases and manage creation of test-related artifacts
* Review test cases/test procedures for sprint backlog items with the development team
* Conduct tests for different functionalities on daily basis to ensure "our system and each
function works perfectly and correctly”
* Perform functional testing including integration testing, smoke testing, interface testing,
regression testing, beta/acceptance testing
* Perform different nonfunctional testing including performance testing, load testing,
compatibility testing, reliability testing, usability testing, compliance testing, localization
testing
* Perform automated testing and verify that results complies with the defined qualities
recorded in test plans
* Set up campaigns and monitor performance of marketing campaigns
* Participates in R&D, training activities related to quality control
* Testing tools such as Selenium, WebDriver, Postman
### Challenges for you
* We are looking for a Senior Quality Control (QC) Engineer that is capable of performing test
functions on existing and new functionalities of our solutions. 
* As a Senior QC Engineer, you will participate in requirement review and change control. 
* You will perform different functional and nonfunctional testing types to ensure that works completed by designated developers meet business and solution requirements as well as the quality standards set internally. 
* You will provide concurrent reports on the quality of the developed functionalities of eMobi solutions.

### You can bring
* Hands-on experience Micro-service Architecture, Big data knowledge is a plus
* Good knowledge of Performance Test (using JMeter/Gatling, measure for Mobile apps),
Security test is a plus
* ISTQB CTFL certification is required
* ISTQB Test Automation Certification
* ISTQB Performance Certification
* Hands-on experience in designing, implementing and executing in Test automation:
** Programming: Java/.Net/JavaScript/Python
** Selenium, Appium, TestNG/JUnit
** Git, SVN
** Gherkin, Cucumber-BDD
** CI/CD tools: Jenkins/Bamboo

## Why it would be awesome to work for eMobi?
eMobi is a fast growing financial technology startup, specializing in mobile payments that drive
results for e-commerce businesses around the world. We build payment solutions integrating
custom mobile marketing campaigns and content services aimed at generating leads and
conversions that hit ROI targets. Our network helps brands to connect with millions of consumers
‘On-The-Go’ by facilitating productive partnerships between advertisers and publishers alike.

We are both a people-oriented and process-driven organization. Our talented and responsive
distributed teams maintain Agile practices and principles; delivering well-curated features that
provide instant ROIs for our partners and customers that in return give us a competitive edge in
becoming a leading figure in the digital market.

Our multicultural teams with talents across different countries are growing quickly. We welcome any
aspiring candidates who are looking to challenge themselves and leave a big impact on eMobi as well on their career path.

## Other interesting benefits you will enjoy
* Company trip.
* Flexible working hours
* Working in a well-funded start-up and dynamic international team
* Private health insurance
* A new professional challenge with many responsibilities and a role with enormous growth
potential
* A friendly atmosphere
* Free access to the gym and pool
* Free snacks, coffee and team activities
* Learning and development opportunities
* Working time from 09:00 - 18:00 (Monday – Friday). 

## Contact
Homepage: https://emobi.biz/ & https://adstartmedia.com/ 
Dare John Adesanya: john@emobi.biz

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
