### ISSUE TITLE
Rabiloo - React Native Developer - Hanoi - FT 

### ISSUE THREAD

**Issue by phuongg2298** [awesome-jobs/vietnam#1909]
![_MG_8904](https://user-images.githubusercontent.com/60953858/75336027-025e0200-58bd-11ea-8b00-4d7143c7b098.JPG)

## Location

 3F C14 Bac Ha Building, To Huu Street, Nam Tu Liem District, Ha Noi.

## Salary Expectation

VND 8M to VND 25M per month

## Requirements

- Logical thinking, good solving-problem skill, have team spirit but also work independently.
- Require a minimum of 6 months of experience in React Native
- Proficient in HTML, CSS, Javascript
- Experience in developing Android and iOS application
- Solid knowledge in Native Core, Cross platform
- Familiar with MVC, MVP, MVVM
- Experience in working with JSX, SASS, LESS, CSS-module … is a plus

### Responsibilities

- Build Mobile applications
- Design and implement new features/patterns
- Create and improve current products
- Research, study new technology, language on Mobile platform
- Work with partners, stakeholders in the progress of building software
- Survey, analyze, architect and develop new the company’s service products

### Why it would be awesome to work with us

- Attractive salary and twice-a-year salary review on April and October
- Social insurance, health insurance paid fully
- Working in a professional, young and friendly environment
- 13th, 14th month salary
- Extensive on job training and skills: technological skills, soft skill, project management skills…
- Free Japanese or English classes in company
- Learn new knowledge: Big Data, AI, NLP, chatbot, Image processing
- Annual leaves: from probation contracts
- Company trip, Year-End Party, Teambuilding, Picnic, etc
- Football Club, Game Club
- Free in-house entertainment facilities: tea, coffee and snack (instant noodles, candies, cookies..)

### Contact

CV send to email: hr@rabiloo.com
Title mail: Name_Job Position
Skype: phuong2298 
Phone: 0336946557

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
