### ISSUE TITLE
Cookpad Inc. - Android Engineer - Vietnam/Remote & extensive travel - C

### ISSUE THREAD

**Issue by vietzombie** [awesome-jobs/vietnam#191]
![cookpad logo](https://global.cpcdn.com/en/assets/logo_cookpad_large-827bc0b34d5c7ab322d3ff8de882e9f828d06bc5ae46d09c88d25aaf02686132.png)
## Who we are

Cookpad Inc. (TSE 2193) is the largest online recipe sharing service in the world. Since its launch in 1997, Cookpad has attracted about 2.5 million recipes and 80 million unique users in Japan & other countries (as of Feb 2016). Our mission is to **make everyday cooking fun** for people of all ages. 🍚🍳😄    

Since 2014, Cookpad service has been expanding internationally and is now available in Vietnamese, English, Spanish, Indonesian, Thai, Arabic and Filipino. We are currently seeking Vietnamese candidates with a passion to share our value to Vietnamese as well as global audience.

https://cookpad.com/vn
https://cookpad.com/vn/download
## Why you should join us

[![Why join Cookpad](https://i.ytimg.com/vi/6Z2ZpTefbjU/mqdefault.jpg)](https://youtu.be/6Z2ZpTefbjU)
[Watch video](https://youtu.be/6Z2ZpTefbjU)

We are looking for a talented person, who shares our passion and can help us push the development of Cookpad mobile service in Vietnam and globally. Headquartered in Tokyo, we have international offices in USA, Spain, Indonesia, Lebanon, India and more to come. We work and collaborate online, and often get together in different countries to be closer to and understand our users. 
## Responsibilities
- Develop Cookpad’s global application together with the international team
- Build Cookpad Vietnam engineer team 
## Basic qualification
- Motivation, capacity and versatility to work in a global team
- Deep insights and experience working directly with users
- Fluent Vietnamese and English are essential
- Experience developing and releasing apps in Play Store
## Ideal candidate has experience in one or several of the followings
- Familiar with relational databases
- Experience in designing UX
- Experience in developing large scale internet services
## Location
- Vietnam/Remote
- Extensive travel overseas to international Cookpad offices 
## Salary Expectation
- Negotiable
### Contact

Trang Yazu: info-vn@cookpad.com. Send us:
1. Your resume
2. Example app codebase that shows your best work
3. Github profile link, and
4. Tell us "Why Cookpad?" 😎

**Comment by hoanghcmus** [comment]
Dear vietzombie,
I have just sent you( info-vn@cookpad.com) an email for application this job. 
Could you tell me that you are still recruiting? I look forward to hearing from you soon, thank you!
