### ISSUE TITLE
Car Next Door - Lead Ruby on Rails Software Engineer - Remote/Hanoi/Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by KenCND** [awesome-jobs/vietnam#1911]
### About Us
We are the fastest-growing car-sharing network in Australia, 5th largest globally (and the best), on a mission to fundamentally change the way people think about transport. Since starting we’ve grown our community to more nearly 4,000 owners who share their cars with over 150,000 members. 75% of bookings taken are repeat bookings by individual members.

* 2014- Green Lifestyle Awards, winner - transport company
* 2017 - Westpac Businesses of Tomorrow, top 200 winner
* 2018 - SmartCompany Smart 50, 5th place
* 2018 - Service Innovation Awards, Finalist
* 2019 - Australian Growth Company Awards, winner - Company to watch
* 2019 - Deloitte Technology Fast50

### About the role
As part of our investment in our core products, new exciting features, and an amazing customer experience to support our double and triple digit growth rates we need Senior Ruby on Rails engineer with a combination of technical and man-management leadership. 
 
You will be joining an experienced and committed development team. As a Lead you will help drive the future technical direction of the business as we expand throughout Australia and Overseas. You will mentor/support our Mid-level developers and other Seniors, perform code-review, perform 1:1’s and performance reviews with members of your team and report directly to the CTO and work closely with the broader Product Team.
 
Our offshore remote working policy is we expect a minimum of 4 hours cross over during 8 am - 6 pm AEST. We offer a highly flexible work environment with a large team of remote engineers. Familiarity managing disparate teams using collaboration tools hugely advantageous.   

**As a core part of the team, you'll be:

* Contributing to the development of Car Next Door's core car-sharing platform through building new functionality; integrating with internal and external systems;
working with mapping systems and vehicle telematics; and automating core processes.
* Contributing to the direction of our technical environment and development practices Rapidly iterating as we push ahead with new development while maintaining and improving the current systems
* Both People management (20% of role) and technical leadership of a number of remote resources

### Experience & Skills
* 7+ years' commercial software development experience (with at least two years RoR)
* 1+ years exposure to people management 
* Experience with Javascript and CSS
* A focus on detail including around automated tests and documenting your code
* Experience debugging and optimising web applications for speed and scale
* An agile mindset and the ability to adapt to changing priorities and requirements
* Pride in your work and a desire to contribute to a small team of dedicated and talented people
* An understanding of what we're doing (and why) and a passion to get involved
* Good English verbal and written skills

### Desirable:
* Computer Science Degree
* A special area of focus, eg., data visualisation, performance tuning, cloud DevOps, or automated testing.

### Our current Tech Stack
**Experience of these or interest in building expertise will be useful:**
* Web: Rails 6, StimulusJS, Tailwind CSS
* Hybrid Apps: Angular 8/Ionic 4
* DB: PostgreSQL
* Cloud Hosting: AWS
* CI: Buildkite
* Productivity Tools: Asana, GitHub, Slack, Zoom
* Key Platforms: Looker (Analytics), Segment (CDP), Braze (CRM), Zendesk (Customer Service)

### Why Work with us:
* We are making a huge impact on car ownership in Australia and offer an opportunity to be part of that journey. 
* With our huge growth and investment in our platform the technology team offers substantial opportunities for technical and career growth
* Amazing flexibility, work from anywhere with reasonable time-zone crossover with our teams, and all the tools/processes to make this successful
* As an employee you also receive a monthly credit to use the platform
* If you are remote we fly you into our Sydney HQ office at least 3 times a year

 
### Sound like your dream job?
* Interesting information about you! - include how you heard about Car Next Door and the position, your visa situation, and how you address the skills and requirements for the role
* The most difficult API/library/software bug you've squashed
* The most technically impressive thing you've ever built
* The largest deployment you've worked on
* Links to your portfolio/GitHub profile or code samples to help us get a feel for how you write code

## Apply here https://forms.gle/CGGziG9m9vqEP69p7

At Car Next Door, we value all people for who they are and what they bring to our community. We encourage our employees to be their genuine, authentic selves and know that our team, our product and our members’ experiences are enhanced by the diversity of perspectives of everyone who works at Car Next Door. We offer equal opportunities to all applicants and promote merit and fairness in our employment practices. If you’re passionate about product development and creating an amazing platform for our community, come as you are!
 
### Note: We are currently not accepting candidates from Agencies. Thank you

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
