### ISSUE TITLE
Car Next Door - Senior Front End Javascript Engineer - Remote/Hanoi/Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by KenCND** [awesome-jobs/vietnam#1912]
### About Us
We are the fastest-growing car-sharing network in Australia, 5th largest globally (and the best), on a mission to fundamentally change the way people think about transport. Since starting we’ve grown our community to more nearly 4,000 owners who share their cars with over 150,000 members. 75% of bookings taken are repeat bookings by individual members.

* 2014- Green Lifestyle Awards, winner - transport company
* 2017 - Westpac Businesses of Tomorrow, top 200 winner
* 2018 - SmartCompany Smart 50, 5th place
* 2018 - Service Innovation Awards, Finalist
* 2019 - Australian Growth Company Awards, winner - Company to watch
* 2019 - Deloitte Technology Fast50

### About the role
We are looking to attract an experienced and self-motivated mid or senior JavaScript engineer to join a highly experienced and committed development team as we scale up. The role would suit someone who wants to play a key part in the development team, working on exciting projects in one of Australia's most promising startups. You will help drive the technology direction of the company, supported by our well-rounded team as we embark on a fast-paced programme of development to help the business expand throughout Australia and beyond.

This is a full-time role with an immediate start.  Our offshore remote working policy is we expect a minimum of 4 hours cross over during 8 am - 6 pm AEST. We offer a highly flexible work environment with a large team of remote engineers. Familiarity managing disparate teams using collaboration tools hugely advantageous.   

To apply, please submit your application via this link: https://forms.gle/3AcqvaLzfvJHVbRr9

### As a core part of the team, you’ll be:
* Working as a member of one of our small cross-functional teams tasked with taking our native mobile apps to the next level in terms of UX, UI and features. 
* Examples include a better camera and mapping integrations, along with adding Bluetooth capabilities;
* Contributing to the continual improvement of the web platform through AB testing, performance and conversion and SEO optimisation; and
* Contributing to the direction of our technical environment and development practices.

### What you’ll need to be successful:
* 5+ years of commercial experience writing HTML, JavaScript and CSS
* 3+ years of experience with modern JS frameworks like Angular, React or Vue.js - ## **We use Angular8**
* Strong experience with app development (Ionic/Cordova, React Native or Native iOS/Android - Swift/Objective-C or Java) - ## **We use Ionic v4**
* Experience using test frameworks - e.g. Jasmine, Mocha, Jest, Protractor, etc.
* A focus on detail pushing wireframes and mockups through to production
* An agile mindset and the ability to adapt to changing priorities and requirements 
* Pride in your work and a desire to contribute to a team of dedicated and talented people
* An understanding of what we’re doing (and why) and a passion to get involved

### It would be a bonus if you had:
* A Computer Science, Design or equivalent degree
* An interest in visual design
* Experience with user testing and A/B testing

### Our current Tech Stack: 
(experience of these or interest in building expertise will be useful)
* Web: Rails 6, StimulusJS, Tailwind CSS
* Hybrid Apps: Angular 8/Ionic 4
* DB: PostgreSQL
* Cloud Hosting: AWS
* CI: Buildkite
* Productivity Tools: Asana, GitHub, Slack, Zoom
* Key Platforms: Looker (Analytics), Segment (CDP), Braze (CRM), Zendesk (Customer Service)

### Sound like your dream job?
Please note that we are only accepting applications that have completed our 5min application form for this role. 
To apply, please submit your application via this link: https://forms.gle/3AcqvaLzfvJHVbRr9

Upload both your cover letter and CV detailing:

* Interesting information about you! - include how you heard about Car Next Door and the position, your visa situation, and how you address the skills and requirements for the role
* The most difficult API/library/software bug you've squashed
* The most technically impressive thing you've ever built
* The largest deployment you've worked on
* Links to your portfolio/GitHub profile or code samples to help us get a feel for how you write code

At Car Next Door, we value all people for who they are and what they bring to our community. We encourage our employees to be their genuine, authentic selves and know that our team, our product and our members’ experiences are enhanced by the diversity of perspectives of everyone who works at Car Next Door. We offer equal opportunities to all applicants and promote merit and fairness in our employment practices. If you’re passionate about product development and creating an amazing platform for our community, come as you are!

NOTE: We are currently not accepting candidates from Agency. Thank you

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
