### ISSUE TITLE
Fetch - ReactJS Developer - HCM- Up to 2200USD - FT

### ISSUE THREAD

**Issue by xuandoan** [awesome-jobs/vietnam#1914]
## General

* Location: 473 Dien Bien Phu, Ward 25, Binh Thanh District
* Working time: 9am-6pm, Mon - Fri
* Salary range: $1000-2200

## About company

* Company is a subsidiary of AccorHotels, a world-leading travel & lifestyle group and digital innovator offering unique experiences in more than 4,500 hotels, resorts and residences across 100 different countries.
* As a recently founded digital venture in Singapore, it is building a new product for changing dining experiences. It will provide a personalized, engaging F&B experience through a consumer mobile application and website, to transform the way diners discover, book, and pay.

## Requirements
* 4+ years working experience in Software Development. 
* 2+ years experience working with ReactJS. 
* Experience working with Redux, Redux Saga, Webpack, CSS/ CSS preprocessors. 
* Proficient in HTML, CSS and JavaScript. 
* Familiar with concepts such as MVC, OOP.
* Strong attention to detail on every line of code, every unit test, and every commit message. 
* Nice to have: Experience in Gatsby and GraphQL

## Benefit
* 13th month salary bonus.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact
* Email: xavia@fetch.tech
* Skype: live:afcf1eb1181fcd5c

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
