### ISSUE TITLE
[HCM] AI Developer

### ISSUE THREAD

**Issue by Nhunie** [awesome-jobs/vietnam#1915]
**This exciting position**
BAP-AI Development team is looking for a versatile and talented Machine Learning Developer to work in a multidisciplinary team of engineers with the goal of building the next generation of artificial intelligence solutions for Computer Vision and Business Intelligence.

**Responsibilities include:**
- Reproducing published algorithms in Machine Learning, Deep Learning papers.
- Assisting Research Engineers in prototyping and evaluating new algorithms in Machine Learning, Deep Learning
- Collaborating with Software Development and QA teams on transitioning the prototypes to commercial products and services

**Background**
- Background in Machine Learning and Computer Vision, Data Science, Mathematics.
- Experiences in using one of Deep Learning frameworks such as TensorFlow, Pytorch, Caffe, Keras
- Deep understanding and building blocks of CNNs.
- Having experience in working with C++, OpenCV.
- Having experience in building and deploying with large scale environments such as AWS, KuberFlow, SageMaker is a plus.
- Proficiency with Python.

**Preference will be given to candidates with the following skills and experience:**
- Hands-on experience in Objects detection
- Previous software development experiences
- Strong communication skills in English

**Why would it be awesome to work with us?**
- Open salaries for all levels and project bonuses.
- Social insurance full package 
- Monthly team-building funds.
- Company trip 2 times per year, Year End Party, 2/9, 8/3, 20/10...
- Personal and professional development opportunities such as English/ Japanese/ Photoshop programs, workshops, seminars...
- Promotion opportunity
- International environment with colleagues from different countries (Vietnam, US, Japan, Australia, Malaysia,...)

`Contact me for more information Skype: nhungnn.hip | Phone: 078 3465773`

**Comment by huydx** [comment]
wrong format
