### ISSUE TITLE
Serenity - Frontend Web Developer - HCMC - PT

### ISSUE THREAD

**Issue by SerenityHolding** [awesome-jobs/vietnam#192]
## Who We Are

Serenity is a dynamic forward-thinking organization that conceptualizes, designs, builds and manages hospitality brands. It is uniquely placed as the only fully vertically integrated hospitality company. Following the huge success of flagship resort Fusion Maia Da Nang, Serenity revolutionized Vietnam’s tourism industry by launching 3 new brands since 2010, and developed 7 new resorts within 12 months.

Providing exceptional lifestyle holidays with unique wellness offerings, a focus on heart-warming down to earth service and elegant yet simple contemporary designs are hallmarks of the Serenity hospitality experience. Its brands are Fusion Resorts, Fusion Suites, Alma Resorts and À La Carte Living.
## Job Description

We are looking for an outstanding full stack web developer to be responsible for rebuilding our existing websites, adding portals for new hotels, customizing our internal web, and overall maintenance of content and ecosystem of social medias.

You will work closely with our top management, IT, sales and marketing, and graphic design teams to develop web services. You will take a group level approach in projects to ensure excellent end-user experience across all commonly used web browsers and handheld devices. 

Programming, basic web design, ERP, and database development are all elements of this position.
## Location
- Ho Chi Minh City, Vietnam
## Salary Expectation
- negotiable
## Requirements
- 3 years minimum experience in web development
- Able to communicate fluently in English
### Must Have
- Strong skills in front-end web development
- Strong knowledge of HTML, CSS, and JS
- Up-to-date with the latest best web development standards, practices, and techniques
- Eager to optimize web sites for cross-browser compatibility, security, speed, and SEO
- Experience in setting-up e-commerce services and HTML emails
- Be proactive, dynamic
### Ideally
- Some basics of back-end development
- Familiarity with either Node.js, PHP, Ruby on Rails, or Django
- Experience with relational databases such as MySQL
- Experience in designing responsive web sites with good UX in mind
- Able to provide technical support and consulting to other teams
### Responsibilities
- Build and design webpages showcasing promotions and other events
- Create HTML emails for reservation systems and eBlasts/newsletters
- Maintain existing websites
- Work with outsourcing firms to build new websites
- Cooperate with designers to match visual themes
### Contact

Christophe Buchart: christophe _at_ serenity-holding.com

**Comment by joneslee85** [comment]
Hi Christophe

Thanks for the posting.

I have few things to weigh in on this post:

* Your fullstack is very broad, we do not allow such post that is in this scope, if you truly know your stack, please narrow it down
* It IS crazy to see such a long list of responsibilities. I do not think it is realistic, and I don't believe this is a good environment for devs

I hope you understand this job board is not like other where people can post whatever they like, we hold the rights to select on only the best and most elite jobs for our community.


Regards

**Comment by SerenityHolding** [comment]
Hi Trung!

We understand your points and want to comply with them. As a result we decided to update our job offer by shifting the focus on the front-end side of things. We hope this will match your guidelines more closely, please let us know if this still isn't the case.


Thank you for your time!

Kind regards,
Serenity Team.
