### ISSUE TITLE
FlowNote AI - UI UX Designer - HCMC - FT

### ISSUE THREAD

**Issue by daphnee97** [awesome-jobs/vietnam#1922]
## Location

* HCMC, Vietnam
* Fulltime

## Salary Expectation

* $1200+/month (salary negotiable based on seniority)

## Requirements
* Node.js/ Python/ Golang
* CI/CD, Docker, Airflow, Kubernetes and microservices
* 3+ years Software Engineering experience

### Responsibilities

* Writing reusable, testable, and efficient code
* Design and implementation of low-latency, high-availability, and performance applications
* Integration of user-facing elements developed by front-end developers with server side logic
* Implementation of security and data protection
* Integration of data storage solutions

### You’ll be responsible for

* Backend for the https://www.flownote.ai/ 

### Why it would be awesome to work with us
We are a Singapore high growth startup commit to growing our team members' potential. From capturing data lineage automatically to analyzing users behaviors, we help clients scale with data of millions of users

Our culture
* **Be a problem solver and generate positive impact:** We do not tolerate teammates who look at problems and just complain about it, blame it on someone else instead of actively solving it. Own the problem that you see, if you feel that your city has really bad air, own it. Start a movement. Be part of the solution.
* **Have product focus on the problem we are solving:** We are a human data company. Regardless of your role and seniority, build the product, use the product, collect meaningful data, and suggest how to make it better. Use data in every aspect of your work.
* **Embrace an open and growth mindset:** Adapt to change, take feedback, and look at everything that comes your way, even and especially challenges, as growth opportunities.

### Interesting engineering projects
Our products serve clients like Verkada, Disney, Dreamworks, Fox, etc and milions of users
* https://www.flownote.ai/
* http://www.mstage.io/

### Contact
Homepage: https://talent.flownote.ai/
Daphne: daphne@hasbrain.com | Skype: daphne.win

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
