### ISSUE TITLE
A stealth startup - Mobile Engineer - Remote/Saigon - FT

### ISSUE THREAD

**Issue by tienle** [awesome-jobs/vietnam#1923]
We are a stealth startup building an ecosystem for cross border logistics. Our products connect trucks, containers, forwarders, and customers across South East Asia to reduce cost, increase efficiency and reliability for the entire cross-border-logistics industry in the particular and regional economy in general. Our company is founded by 2 founders who have multiple successes in building startups, a tech team of young and highly skilled engineers, a business team of experts in the logistics field. We are looking for:

## Location

* Saigon, Vietnam
* Remote (applicable for Senior level and above)

## Salary Expectation

* Negotiation

## Requirements

* 1.5+ years experience in mobile development.
* Good knowledge at OOP
* Experience in Java, Android studio or Swift/Objective-C, XCode.
* Experience with mobile application lifecycle and coding conventions.
* Master in interface building tools.
* Experience in network, core library, Social Network and other frameworks…
* Experience with asynchronous programming, multithreading.
* Had apps submitted to AppStore.
* Experience in customizing views, handle keyboard appearance.
* Experience with debugging tools in XCode or Android studio.

### Ideally

* Experience in both android and iOS is a plus.
* Experience in React programing is a plus.

### You’ll be responsible for

* Will participate in the development and architecture design of our mobile applications (native Android/iOS).
* Devising possible solutions to anticipated problems;
* Conducting testing and installing mobile applications into production

### Why it would be awesome to work with us
* To solve a practical logistic problem that deeply impacts Vietnamese and South East Asia economy
* To be a part of a young, dynamics and enthusiastic team whose founders have founded and succeeded with multiple startups
* Competitive compensation and benefits

### Contact
Dung Nguyen: dqnguyen@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
