### ISSUE TITLE
BTASKEE - Golang Developer - HCM - FT

### ISSUE THREAD

**Issue by NhaHien** [awesome-jobs/vietnam#1925]
## Location

* No. 69 Hoang Trong Mau Street, Him Lam Riverside, Tan Hung Ward, Dist 7, HCMC

## Salary Expectation

* $800 - $1,000

## Requirements
* Golang
* Git.

### Must Have

* Basic knowledge of API, Web, Micro-service.
* Basic knowledge of Nodejs.
* Passion for writing great, simple, clean, efficient code.
* Basic Knowledge of databases (MongoBD, SQL,...).

### Ideally

* Appreciated: Docker, k8s.

## You’ll be responsible for

* Be in charge of architecture, implementing and maintaining core Back-end features of our micro-services.
* Working with the founder/product owner and project manager.
* Contribute idea and play role in the growth of the company.
* Enjoy great career growth opportunities.

## Why it would be awesome to work with us 
* Bonus 13th-month salary .
* We provide training to help you catch up with the current team .
* Work in a startup environment where Innovation, Passion, Openness and Trust are at its core .
* Salary increases every 6-12 months .
* Company trip every year!
* Monthly team building event .
* Learn new thing every week! We encourage our employee to spend 1 day a week to learn new stuffs.

### Contact
Homepage: https://www.btaskee.com/en/
Email: it.huynhnguyennhahien@gmail.com
`Titles: Your Name_Position`

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
