### ISSUE TITLE
Fetch - Senior Backend Developer - Onsite Singapore - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#1926]
![image](https://user-images.githubusercontent.com/60914247/76821645-1b652d80-6841-11ea-80d3-0fc725c6d3cb.png)

## Singapore

* Onsite Singapore

## Responsibilities:
* Design, implement and maintain efficient, reusable, and reliable Ruby on Rails code.
* Implement high availability backend solution.
* Integration of MYSQL data storage.
* Write and maintain RSpec unit test/functional test cases.
* Develop backend projects with micro-services architecture and the communications between each service.
* Develop REST/GraphQL API for website functionality.
* Build backend REST/GRAPHQL API.
* Identify bottlenecks and bugs, and devise solutions to these problems.
* Raise the code quality by reviewing each other’s code, sharing knowledge and helping out within and across teams.
* Evaluate new practices and technologies for backend development.

## Requirements
* Good understanding of common rails gem, eg. Devise, Resque.
* Competencies in algorithms, data structures & concurrent programming.
* Familiar and experienced in building scalable micro-service architecture backends.
* Knowledge in various communication channels between microservices eg. message broker, queue, grpc.
* Proficient understanding of MYSQL database, sql query, design of schema, master/slave, data sharding, indexing.
* Able to implement automated unit/functional test cases.
* Familiarity with development aiding tools eg.
* Bundler, Rake, RVM, Docker.
* Be highly responsible, take ownership over your works, work independently with minimum supervision, and be a lifelong learner with a positive collaborative attitude.
* Bachelor’s degree in computer science, applied mathematics, or another similar technical discipline.

### Why it would be awesome to work with us
* Onsite Singapore.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* 12-day annual leave per year.
* 13th month salary.

### Contact
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
