### ISSUE TITLE
[Snap Innovations] - IOS Developer - HCMC - Fulltime

### ISSUE THREAD

**Issue by superladk** [awesome-jobs/vietnam#1927]
We always welcome passionate and creative talents to join our company. You will have the opportunity to challenge yourself with numerous projects. 

Snap Innovations has since extended our technology expertise into real-world Artificial Intelligence solutions for deployment in Finance, HR management, proprietary trading and various areas of Fintech and Blockchain.

## Location

* Binh Thanh district, HCMC, Vietnam

## Salary Expectation
Negotiation

## Responsibilities
* Design and develop iPhone/iPad applications from customer requirements.
* Work closely with graphic designer to transform design idea to coding.
* Explore new technologies to solve technical challenges.
* If you can give good ideas to build new applications for our company, you will be a key person.
* Work closely with other teams to develop the Payoo mobile app and SDKs.
* Maintain and fix bugs.
* Other projects to be discussed

## Expected Skills

1. For junior level
* Swift, Objective C
* iOS Development (at least 1 year experience)
* Object-oriented programming (OOP)
* Data Structure and Algorithms
* Networking
* Familiarity with JSON, REST-based APIs, XML, JavaScript, and interfacing iPhone/iPad applications to server-side API’s
* Experience with version control and dependency management tools

2. For senior level
* At least 2 years experience in native iOS development role
* Native mobile application development on iOS with fluency in Swift, Core Foundation, UIKit, –Cocoa Touch, Core Animation and other frameworks provided by Apple
* Applied understanding of resource constraints including battery life, network availability, and the like
* Familiarity with multiple architectural patterns such as MVC and MVVM
* Familiarity with JSON, REST-based APIs, XML, JavaScript, and interfacing iPhone/iPad applications to server-side API’s
* Strong understanding of Apple’s Human Interface Guidelines as well as interaction design best practices

## Why it would be awesome to work with us
* International and Professional Working Environment
* Great Teamwork with Flexible working time (Office hours 9AM - 6PM Monday to Friday)
* Snack free + lunch support
* 13th month Salary + Salary Review (2 time/year),
* 14 Day-offs per year 
* Company Trip, Team Building, Year End Party etc.

## Contact Us
* Homepage: https://snapinnovations.com
* Email subject: [Snap Innovations] - Junior/Senior IOS developer- Your name
* Email: careers@snapinnovations.vn
* Skype: Maifffam (Ms. Mai)
* Phone: +84.372684398 (Mr. Hung)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
