### ISSUE TITLE
Senior Front-end Developers

### ISSUE THREAD

**Issue by ontheheadhunter** [awesome-jobs/vietnam#1928]
## Location

* Phu Nhuan Dist., HCMC
* Full-time

## Salary Expectation

* 20.000.000VND or more

## Requirements
* Có kinh nghiệm làm việc từ 2 năm trở lên với JavaScript, và trên 1 năm với phiên bản từ ES2015(ES6) trở lên).
* Có kinh nghiệm sử dụng FrameWork/Library như react/vue/angular để lập trình JavaScript.
* Có kinh nghiệm Coding bằng HTML5＋CSS3 (kinh nghiệm làm việc thực tiễn từ 3 năm trở lên).
* Có kinh nghiệm sử dụng ngôn ngữ lập trình Meta (Sass (SCSS), Less, Stylus) để thiết kế CSS.

### Better to have

* Có kinh nghiệm tạo HTML/CSS theo các quy tắc chuẩn của Coding (Bao gồm kinh nghiệm sử dụng Quy tắc đặt tên phổ biến BEM.v.v...)
* Có kinh nghiệm sử dụng Tool quản lý version như Git, v.v...
* Có kinh nghiệm sử dụng Task runner.
* Kỹ năng quản lý
* Có kinh nghiệm làm việc và build website với 2 front-end dev trở lên

### Responsibilities

* Sử dụng CMS (như WordPress) hoặc những kỹ thuật như HTML, CSS, JavaScript (AngularJS/ ReactJS/ VueJS) v.v… để viết Code và tạo Website dành cho PC và Smartphone
* Lên kế hoạch, thiết kế, tạo Website mới.
* Kiểm tra hiệu quả của trang web đã tạo.
* Chỉnh sửa, cập nhật những trang Web có sẵn
* Tạo trang Web mới dựa trên mẫu hoặc trang web có sẵn
* Đưa ra các biện pháp, đối sách để cải thiện phản hồi cũng như nâng cao các trải nghiệm cho người dùng.

### Why it would be awesome to work with us

* Nghỉ Thứ Bảy, Chủ Nhật và các ngày Lễ, Tết.
* Thưởng: 2 lần/năm, ngoài ra, còn có bonus và thưởng nóng cho những cá nhân xuất sắc trong tháng và năm. 
* Xét tăng lương: ít nhất 1 lần/ năm.
* Có cơ hội đi Onsite ở Nhật
* Phúc lợi chi phí Teambuilding cho nhân viên hàng tháng về các hoạt động ăn uống vui chơi trong team
* Du lịch công ty 1 năm 1 lần & khám sức khỏe 1 năm/lần.
* Các buổi tiệc như tiệc Halloween, Giáng Sinh, Tiệc cuối năm, Tiệc sinh nhật hàng tháng, .... (Bạn có thể xem thêm trên fanpage FB của Lampart)
* Hoạt động thể dục, thể thao thường xuyên với các câu lạc bộ: bóng đá, bơi lội v.v...
* Ngoài các gói bảo hiểm cơ bản theo quy định của Luật Lao Động, bạn còn được tham gia gói bảo hiểm tai nạn lao động tại Lampart.
* Hàng tháng có trà, sữa, coffee,... miễn phí
* Tăng ca đêm sẽ có tiền tăng ca ban đêm, ngoài ra được nghỉ bù có lương vào ngày hôm trước và ngày hôm sau.
* Ngày nghỉ đặc biệt dành cho nhân viên nữ: 0.5 ngày/ tháng.
* Được hưởng những phúc lợi đặc biệt như chương trình quà tết, bánh trung thu,, tiền mừng đám cưới (5,000,000 VND), tiền mừng khi sanh con (2,000,000 VND),…
* Đối với nhân viên ký hợp đồng không xác định thời hạn: thì từ thời điểm ký hợp đồng không xác định thời hạn, cứ mỗi năm được cộng thêm 1 ngày nghỉ phép. Ngày nghỉ phép không sử dụng hết trong năm sẽ trả vào lương tháng cuối cùng của năm.
* Chế độ đào tạo: Công ty có chế độ cho nhân viên đi học bên ngoài nếu xét thấy việc học cần thiết để nâng cao kiến thức áp dụng vào công việc ( tùy vào hình thức học có thể hỗ trợ 100% học phí)

### Contact
More job here: https://onheadhunter.wordpress.com/
Email: oanhtrinh.k41@gmail.com
Skype: oanhtrinh.k41

**Comment by nguyenvanhoang26041994** [comment]
"Front-end Developers" it better title for this job description. Just say it
