### ISSUE TITLE
BAP - Senior CakePHP Developer - HCMC - FT

### ISSUE THREAD

**Issue by Nhunie** [awesome-jobs/vietnam#1932]
## Location

* Viettel Complex Building, 285 CMT8, Ward 12, District 10, HCMC, Vietnam

## Salary Expectation

* Negotiate (based on experience)

## Responsibilities

BAP seeks experienced and talented CakePHP developers responsible for managing back-end services and the interchange of data between the server and the user, who will join our new projects for an automated building system to managing Beauty Centers. Your main responsibilities will be:
* Integration of user-facing elements developed by front-end developers
* Building efficient, testable and reusable CakePHP components
* Solving complex performance problems and architectural challenges
* Integration of data storage solutions
* Design and implement efficient and reusable CakePHP components

## Requirements

* **Strong grasp on PHP** as a language and knowledge of its quirks
* At least **3 years experience** of CakePHP development
* Strong knowledge of **CakePHP (2.8)** and its extensive feature set
* Strong knowledge of **MySQL databases** and their declarative query languages
* Fluency in web data handling including various forms of cloud service provider data storage (e.g. **AWS**).
* Integration of multiple data sources and databases into one system
* Creating database schemas that represent and support business processes
* Have good **logical thinking, troubleshooting, problem solving**

## Preferred

* Experience working with **Japanese Client**
* Can communicate **English** or **Japanese**

## Why it would be awesome to work with us

* We value your ideas, thoughts, creativity and opinions
* Competitive Salary (**based on experience**)
* Social **insurance full package** 
* Performance review **2 times per year** 
* Promotion opportunity, **incentive** for Practising Certificate, Management level...
* Company trip 2 times per year, Year End Party, 2/9, 8/3, 20/10...
* Monthly team-building funds.
* Personal and professional development opportunities such as English/ Japanese/ Photoshop programs, workshops, seminars...
* **International environment** with colleagues from different countries (Vietnam, Japan, Australia, Singapore,...).

## Contact

* Ms Nhung: `nhungnn@bap-solutions.com` | Skype: `nhungnn.hip` | Phone/ Zalo: `0783465773`
* Homepage: [https://bap-software.net/en/](url)
* Facebook: [https://www.facebook.com/bap32/](url)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
