### ISSUE TITLE
Robust Tech House - Web Software Engineer - Tan Binh/HCM - FT

### ISSUE THREAD

**Issue by duongquocphat** [awesome-jobs/vietnam#1934]
## Location

* Tan Binh, HCM city, Vietnam
* Fulltime

## Job Description

We are looking for a team of Web Developers with a range of skills and experience levels (junior, mid and senior). Please send in your CV if you have experience in any of these (VueJS, ReactNative, ReactJS, AngularJS, Java, Ruby, Python or .NET). We’ll reach out to chat more with you!

## Requirements

* Degree in Computer Science, Information Science or a related field
* Relevant technical hands-on development experience
* Good in English
* Proactive, eager to learn and can pick up new skills quickly
* Great work attitude, willing to go the extra mile
* Detail-oriented, logical-minded and takes pride in creating robust software

## Skills

* VueJS, ReactNative, ReactJS, AngularJS, Java, Ruby, Python or .NET

### Why it would be awesome to work with us

* Flexible working time (9h - 18h Mon to Fri)
* Work from home on every Friday
* Macbook for work
* Friendly and funny teammates
* Team building everyday

### Apply and more information link:
Link: [`Apply here`](https://portal.socialsourcing.com/refer/c448a14dc1f417b71ea4490e7f0ebd7e)
or
Email: duongquocphat@hotmail.com

**Comment by jackiedo91** [comment]
Sorry, I cant apply via link "Apply Here"

**Comment by duongquocphat** [comment]
> Sorry, I cant apply via link "Apply Here"

sorry about this, you can apply [`this link`](https://portal.socialsourcing.com/refer/c448a14dc1f417b71ea4490e7f0ebd7e)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
