### ISSUE TITLE
FETCH TECHNOLOGY - Senior PHP Laravel Developer - Hanoi - Full-time

### ISSUE THREAD

**Issue by JunnieNguyen** [awesome-jobs/vietnam#1935]
## Location

* 3rd Floor, Dai Phat Building, Lan 82 Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Hanoi.
* Full-time

## Salary Expectation

* 2000$/month 

## Requirements
* At least 5 years of experience on PHP, include at least 1 year experience working with Laravel Framework (your current work need to be work with Laravel framework), PostgreSQL and Bootstrap front-end framework.
* Experience in MySQL and data modelling
* Expert with Git and knowledgeable with Git workflow.
* Ability to convert PSD design into HTML5 and CSS3/Sass.
* Experience with C++, C# or Android app development will be a bonus.
* Experience in VueJS, JavaScript Framework is a plus.

### Ideally

* Equally strong in front-end programming languages: HTML, JavaScript, CSS/ Sass, styling and Back-end programming Languages: PHP, SQL.

### Responsibilities

* Developing and maintaining client-facing and back-end operation web applications.
* Testing and code review to ensure applications free of bugs.
* Implementing UI and UX designs created by our designer.
* Ensuring cross-platform optimization for mobile phones.
* Ensuring responsiveness and security of applications.
* Designing, developing and consuming RESTful API.

### Why it would be awesome to work with us
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

### Contact
Email: dungnguyen@fetch.tech
Skype: dungphuongdh
Telegram: JunnieNguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
