### ISSUE TITLE
[LARION] - [Senior NodeJS Developer] - [Saigon] - [PT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#1938]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 12-17$/ hour

## Requirements

* At least 2 years of working experience with NodeJS
* Proficiency in JavaScript, ECMAScript6+, and TypeScript
* Experience with micro-services architecture and its core principles and challenges
* Experience with Nest.js

### Responsibilities

* Implement and enhance backend API services
* Develop RESTFul APIs to support frontend applications
* Coordinate with various teams working on distinct layers

### Why it would be awesome to work with us

* Very attractive salary and open for negotiation

### Interesting engineering projects

* Supply Chain product

### Contact

* Please send CV via email: recruitment@larion.com
* For further inquiries, please reach out: Skype: ngoctranthibao/ Zalo: 035.6945.706

**Comment by lunmatu101** [comment]
Hi @tranthibaongoc,
I sent my CV to recruitment@larion.com and wish to work with you in the future.
