### ISSUE TITLE
Senior Ruby On Rails Developer

### ISSUE THREAD

**Issue by ontheheadhunter** [awesome-jobs/vietnam#1943]
## Location

* Saigon, Tân Bình Dist.
* Full-time

## Salary Expectation

* Up to $1500 NET

## Requirements

* At least 3 years of experience with Ruby on Rails. 
* Knowledge about HTML, CSS, Javascript, Bootstrap, Restful API, JSON.
* Understand what is MVC, how to develop a Responsive website or make an existing website responsive.
* Experience with Backend or Front end, AWS, Heroku, Google App Engine is an advance.

## Skills

* English skills is a plus.

### Responsibilities

* You will work on some software development projects with a startup company in Singapore to make worldwide shipping & logistics industries more efficient and effective. 
* You and your team will receive requirements as User Stories from end-users (Singapore, China, Taiwan, Malaysia, Thailand, India, Japan).
* Beside coding tasks, you will have access to every steps in LEAN software development cycle: UI-UX, Architecture, Unit Testing, Automation Testing, User Interview...

### Why it would be awesome to work with us

You’ll have the chance to build world-class products for people around the world. In addition to that, here are the perks at working with our team:

* Regular on-the-job training by our team leads.
* 13th month salary.
* Regular technical seminar and training allowance to improve your technical skills.
* Improve your presentation skill by hosting a seminar on your favorite topic.
* Salary review based on performance every 6 months (if applicable).
* PVI Insurance package and 100% social & medical insurance paid 
* MacBook + 2nd monitor
* Join us on our annual company trip, every year.
* Free food & drink anytime you want.
* Tons of cool toys (PS4, Drones etc.)
* Work in an nice, open and flat office.
* Improve your health, communication skill with every week outdoor team building activities.

### Contact
Email: oanhtrinh.k41@gmail.com (Skype)
More job at: https://onheadhunter.wordpress.com/

**Comment by qcam** [comment]
Hi, thanks for posting but unfortunately we only accept job posts from in-house recruiters.
