### ISSUE TITLE
Sea Group - Sr/Software Engineers (Go) - HCMC - FT

### ISSUE THREAD

**Issue by vanhtuan0409** [awesome-jobs/vietnam#1944]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2000+ / month

## Requirements

* Bachelor's degree or higher in Computer Science or related fields (Experienced);
* Strong Knowledge & experience in algorithms; Operation System & Memory Control;
* Familiar with common network protocols (TCP, UDP, HTTP), and network programming;
* Excellent working attitude, problem-solving, critical thinking and communication skills;
* Passionate about programming, innovation, and solving challenging problems;
* Comprehensive knowledge in all areas of computer science
* Familiar with Go/Python, hands-on experience is preferred;
* Familiar with Linux development environments, and multi-threaded programming;

## Responsibilities

* Handle server-side design & development of Sea Group's products;
* Be familiar with agile development, write high-quality, clean, simple, and maintainable code, build common libraries
* Analyse requirements, design and develop functionality, according to product demands;
* Acquire an in-depth understanding of products, constantly optimize the products, diagnose and fix problems, improve stability and user experience;
* Design and implement various supporting tools as required;
* Collaborate with other software engineers, product managers, user experience designers, and operation engineers to build new products.

# Contact

Email: anhtuan.vuong@foodycorp.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
