### ISSUE TITLE
Sea Group - Sr/Jr/Frontend Engineers (React) - HCMC - FT

### ISSUE THREAD

**Issue by vanhtuan0409** [awesome-jobs/vietnam#1945]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2000+ / month

## Requirements

* At least 1-year hands-on experience of using JavaScript
* Bachelor’s degree or higher in Computer Science or related fields
* Passionate about coding and programming, innovation, and solving challenging problems;
* Grasp strong JavaScript fundamentals
* Knowledge with React is a plus
* Know browser well enough
* Love technologies
* Enjoy teamwork

## Responsibilities

* Design and implement leading platforms that is impacting millions' daily life in Southeast Asia.
* Involve in fierce and candid code review with peers
* Implement solutions to complex business features to horn your skills
* Maintain and improve our high-quality in-house JavaScript libraries and toolsets, for example, a * complete React UI library.
* Participant in regular internal technology sharings and other regional tech events

# Contact

Email: anhtuan.vuong@foodycorp.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
