### ISSUE TITLE
Kỹ Sư Phát Triển Phần Mềm Kiêm Quản Lý Dự Án (Công Nghệ 5G) (Linux, C++, C#)

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#1946]
## Địa điểm làm việc

* **Đà Nẵng**

## Offer

* **$2,300 - $2,700**

## Yêu cầu công việc

* Thời gian đầu sẽ được đào tạo từ 3 đến 6 tháng tại trụ sở chính ở thành phố Tachikawa, Tokyo. Sau đó sẽ về Đà Nẵng hỗ trợ start up công ty mới.
* Ưu tiên có kinh nghiệm phát triển phần mềm ở Nhật, kỹ sư cầu nối.
* Có kinh nghiệm quản lý (quản lý nhóm từ 10 người trở lên).
* Tiếng Nhật giao tiếp tốt từ N3 trở lên.
* Biết các ngôn ngữ: C, C#, C++.
* Hệ điều hành OS: Linux.       
* Có tinh thần trách nhiệm, kỹ năng quản lý nhóm.

## Mô tả công việc

* Xây dựng, phát triển các sản phẩm và hệ thống công ty đang kinh doanh.
* Quản lý dự án, làm kỹ sư cầu nối giữa chi nhánh ở Đà Nẵng với công ty mẹ bên Nhật.
* Chịu trách nhiệm về việc hỗ trợ thành lập chi nhánh ở Đà Nẵng (bao gồm việc quản lý tổng thể nhân sự, tiến độ công ty...).

## Đãi ngộ
* Lương tháng: ¥250,000 ～ ¥300,000
* Thu nhập năm bao gồm thưởng lên tới ¥5,000,000
* Khi làm việc ở Nhật sẽ có thêm phụ cấp nhà ở và đi lại.
* Giờ làm việc: Thứ 2 ~ Thứ 6 (8h45 ~ 17h30).

## Contact
Homepage: https://919vn.com/
Email: huykhanh.tran3108@gmail.com
Skype: huykhanh.tran3108@gmail.com

**Comment by qcam** [comment]
@Khanhtranf Thanks for posting. Would you please modify the post to comply to our format? https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post

Thank you and the post will be temporarily closed until all issues are well addressed.
