### ISSUE TITLE
Ruby on Rails - Remote Job - $500 - $3500 

### ISSUE THREAD

**Issue by ngocphuong39** [awesome-jobs/vietnam#1949]
## Requirements
* Ruby on Rails
* Know about Vim is a plus 
* A programmer who reads, writes and speaks English fluently
* A programmer who knows design pattern and how to apply it
* A programmer who can build architecture whenever we need
* A programmer who understands how database works and knows how to improve the 

## Benefits: 
* MacbookPro
* Health Insurance
* 13th-month Salary
* Annual Salary Review

### About Us: 
Remitano: One of the largest peer-to-peer (p2p) cryptocurrency trading platforms in the world, currently serving users in more than 30 countries. The platform provides an escrowed p2p crypto marketplace allowing users to buy, sell and swap crypto and fiat easily and safely. Remitano is a market leader in the p2p platform space, featuring an intuitive and user-friendly interface, 24/7 customer support, and boasts some of the lowest fees in the industry.

- Contact
Email: ngocphuong@remitano.com

**Comment by qcam** [comment]
Hi could you please provide more info about the company in the description, as well as make sure that the post conforms to our format? The post will be temporarily closed until all issues are addressed. Thanks!
