### ISSUE TITLE
LINAGORA - Automation Tester - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1951]
## Location

* No. 1 Thai Ha Str., Dong Da Dist., Vietnam

## Salary Expectation

* 700 USD - 1000 USD

## Responsibilities

* Work on an Open Source platform.
* Business is all around collaboration and communication for enterprise: emails, calendars, contacts, chat, video conference, document management & edition.
* Analyze users stories and/use cases/requirements for validity and feasibility.
* Design test plans, test cases/test procedures.
* Creation, execution and maintenance of the automated scripts.- Report bugs if found any when run automation or perform manual test.
* Collaborate closely with other team members and departments to ensure the automated scripts work effectively and the quality of product.

## Requirements

* Have any degree or certificate in IT field.
* Have knowledge about automation test for Web or Mobile.Have knowledge about Selenium Web driver or one of the automation testing. framework (Ex: Robot framework, Cucumber,... ).
* Have basic knowledge about programming language.
* Knowledge of HTML, CSS, JavaScript.
* Knowledge of HTTP/HTTPS protocol.
* At least 1 year's experience on Automation testing.

## Why you'll love working with us

* Opportunities for promotions and chance to travel or work in France.
* Family culture in international working environment: friendly, helpful, cooperative and respectful.
* International Software projects bring you to highly international position.
* Working in Linagora headquarter in Southeast Asia.
* Annual company trip, other exciting activities for team building.
* Working 5 days/week , from Monday to Friday.
* Lunch allowance, 13th month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Modern working place, free coffee.

### Contact

* Homepage: linagora.com
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
