### ISSUE TITLE
LINAGORA - Manual Tester - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1952]
## Location

* No. 1 Thai Ha Str., Dong Da Dist., Hanoi

## Salary Expectation

* 600 USD - 800 USD

## Responsibilities

* Create and maintain tests specifications.
* Execute test cases on the mobile app/web according to the specifications.
* Report bugs if found any when running test.
* Monitor of all the QA activities: test results, cause analysis, etc.
* Allocate all the bugs to the proper parties (dev, product teams, other teams).
* Monitor the progress of developer teams Scrums, and test new features and bug fixes as they enter the code base of the product.
* Collaborate with developer team to provide feedback and guidance to setting the test strategies and assuring to delivery the project on time.
* Ensure all development tasks meet quality criteria through test planning, test execution.

## Requirements

* Bachelor’s degree in information technology, or related field.
* At least 2 years of experience of mobile/web testing.

## Why it would be awesome to work with us

* Opportunities for promotions and chance to travel or work in France.
* Family culture in international working environment: friendly, helpful, cooperative and respectful.
* International Software projects bring you to highly international position.
* Working in Linagora headquarter in Southeast Asia.
* Annual company trip, other exciting activities for team building.
* Working 5 days/week , from Monday to Friday.
* Lunch allowance, 13th month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Modern working place, free coffee.

## Contact

* Homepage: linagora.com
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
