### ISSUE TITLE
LINAGORA - DevOps Engineer - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1953]
## Location

* No. 1 Thai Ha Str., Dong Da Dist., Hanoi

## Salary Expectation

* 1000 USD - 2000 USD

## Responsibilities

* Implement and improve monitoring and alerting.
* Build and maintain highly available systems on Kubernetes.
* Implement and manage CI/CD pipelines.
* Implement an auto-scaling system for our Kubernetes nodes.
* Participate in on-call rotations.

## Requirements

* BA Degree in Computer Science / Information Technology or equivalent.
* Knowledge of CI/CD and IT security concepts.
* Knowledge of Sourcecode Mangement Systems: Gitlab, Github, Bitbucket.
* Knowledge and experience of Kubernetes (k8s), Docker.
* Knowledge of Provisioning and Configuration Management tools such as Ansible, Terraform, Puppet is a plus.
* Good level of English

### Why it would be awesome to work with us

* Opportunities for promotions and chance to travel or work in France
* Family culture in international working environment: friendly, helpful, cooperative and respectful
* International Software projects bring you to highly international position
* Working in Linagora headquarter in Southeast Asia
* Annual company trip, other exciting activities for team building
* Working 5 days/week , from Monday to Friday
* Lunch allowance, 13th month salary, competitive salary
* Annual health checkups and other benefits based on labor law

### Contact

* Homepage: linagora.com
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
