### ISSUE TITLE
Koidra - Senior Software Engineer - Saigon/Binh Dinh/Remote - FT

### ISSUE THREAD

**Issue by zer0n** [awesome-jobs/vietnam#1954]
<img src="https://user-images.githubusercontent.com/3055719/81139074-a5528c80-8f8e-11ea-99ad-f26f90201589.png" width="200">

is #hiring top-notch software engineers in all of these categories: **frontend/backend/full-stack**

## Location
* Saigon, Vietnam
* Binh Dinh, Vietnam

## Salary Expectation
$1.5K - $2.5K/month

### Must Have
* 3+ years Software Engineering experience
* Excellent programming, debugging, and analytical skills
* Fluent in `Python` OR at least two other mainstream programming languages (e.g. `C#`, `Java`, `JS`, ...)
* Experience in one of the major cloud platforms (GCP, AWS, Azure, etc.)
* Passionate about solving customer-driven technical challenges

### Ideally
Experience (the more the better) with our tech stack so that you can contribute from day 1.

**Tech Stack that we're using**
- Frontend: `Vue.JS`, `TypeScript`
- Frameworks: `Django`, `Pandas`, `Sentry`, `Hasura/GraphQL`
- Infrastructure: `GCP`, `PostgreSQL`
- AI: Machine Learning (Bayesian), IoT, Optimal Control, Differential Equations

### Responsibilities
*  Write clean, high-quality, high-performance, maintainable code
*  Develop and support software including applications, database integration, interfaces, and new functionality enhancements
*  Coordinate cross-functionally to insure project meets business objectives and compliance standards
*  Support test and deployment of new products and features
*  Participate in code reviews

### Why it would be awesome to work with us
Founded by Kenneth Tran, formerly a Principal Machine Learning Scientist at Microsoft Research (MSR), Koidra's mission is to change the industrial automation industry, applying cutting edge research in AI, IoT, and hybrid cloud+edge computing. Check out some early **[media coverage about us](https://www.notion.so/Press-Releases-354cdc2b6461476b98c2d01dfa1d22dc)**.

At Koidra, you'll have an opportunity to work with world experts in Machine Learning and Software Engineering.

### Contact
Kenneth Tran (CTO): ken@koidra.ai (0935069639 or WhatsApp: +15124363250)

In addition to your CV, please include one of the following materials:
- LinkedIn profile
- GitHub profile
- Stackoverflow profile
- Your personal homepage or technical blog

**Comment by xxxle0** [comment]
@qcam , FT/PT/C  is Full-time/Part-time/Contract , right ?

**Comment by zer0n** [comment]
@xxxle0 , Koidra is open to all full-time, part-time, and contractors. We are fairly flexible at this point.

**Comment by lunmatu101** [comment]
I sent my CV (included LinkedIn profile) to your email, please check it. Thanks.

**Comment by zer0n** [comment]
@xxxle0 , could you please add the `Lang:Python` label as it is our primary language?

**Comment by phanngt** [comment]
@zer0n I sent my CV to your email. Thanks :)
