### ISSUE TITLE
Holistics Software - Fullstack Engineer (open-source) - Saigon - FT

### ISSUE THREAD

**Issue by haibinhboong** [awesome-jobs/vietnam#1955]
## Location

* Saigon, Vietnam

## Salary Expectation

* $650 - $1300/month

## Requirements

* Strong problem solving (most important)
* Excited about working with open-source projects or developer-tool software
* Experiences with JavaScript/NodeJS a plus (though not required)
* Have at least 1 year of experiences in Software Development
* Good English communication skill (reading and writing)
* Both senior and junior positions are welcome

## Responsibilities
Work on developing 3 related projects revolving around database documentations:
* Our open-source database markup language: [dbml.org](https://www.dbml.org/)
* Our database diagram drawing tool (based on DBML): [dbdiagram.io](https://dbdiagram.io/)
* Our database documentation tool (based on DBML): [dbdocs.io](https://dbdocs.io/)

### Why it would be awesome to work with us

* 14 Annual leaves/year, 14 Sick leaves/year
* 13th month-salary; Performance review twice a year
* 24/7 Healthcare Insurance, Periodic Medical Checkup
* Shares (Stock Options) for high-contributing individuals
* Workstation provided for maximal productivity: Macbook (or Laptop), Leopold FC750R mechanical keyboard, Razer Abyssus V2 computer mouse, 24’ Ultrasharp Monitor
* Active and agile working environment; Flexible time culture; Weekly happy hours, fruits, snack...
* Weekly TED talks to expand skills and knowledge, games, and social sports activities with the company; Company trip and company-organized events.
* An opportunity to work with top-notch experts from around the world.

### Interesting Engineering Projects

* We launched [dbdiagram.io](https://dbdiagram.io/) as a side-project in late 2018 with no marketing budget (still no marketing budget now) and at the moment (April 2020) it has over 150K users with over 60K monthly active users (MAUs), with than 70% of them are developers
* Our second project, [dbdocs.io](https://dbdocs.io/) is a tool to help developers create database documentation sites for their applications.
* Seeing the potential of this, we spun off its DSL language into open-source language DBML ([github](https://github.com/holistics/dbml)) to define database schema. It has been picked up and adopted by organizations across the world since.
* Our vision is to see DBML become the open-source industry-standard for defining database schema for every web application. Imagine in every web application, besides your usual README.md or packages.json, there will be a database.dbml to define the database structure.
* We’re looking for a full-stack engineer who’s excited by this vision to join us on this ambitious project.

### Contact
Homepage: [holistics.io](https://www.holistics.io/), [dbdiagram.io](https://dbdiagram.io/)
Apply for Holistics: https://bitly.com.vn/07WAq

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
