### ISSUE TITLE
NAB VDC - Integration Senior Java Engineer - Saigon - FT 

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1956]
# Location

* Etown 3, Tan Binh Dist., Saigon

# Salary Range

* USD Super Attractive 

#### NAB is undergoing an exciting "Cloud First" technology transformation by taking advantage of the latest tools and techniques used by leading technology and digital companies globally. But it’s not just about the Tech, we are also investing heavily in our people, so if you have an appetite to learn, grow and elevate others around you, this is the place for you!   

# Responsibility 
#### As Senior Integration Software Engineer (Java) at NAB, your scope includes but not limited to the followings:

* Participate in Agile software development, unit testing, and peer review to build scalable microservices-based products and APIs using Java technologies on AWS Cloud architecture
* Take ownership/accountability for the investigation of requirements and come up with technology solutions
* Design and deliver quality microservices and cloud-based solutions that benefit our customers and stakeholders
* Take ownership of the  analysis and design of applications programs and databases
* Be responsible for code reviews, white-box testing & test framework maintenance
* Provide support on significant production changes & issues when required and being part of a 24x7 on-call roster

# Requirement
* 5+ years of experience working in Software Development;
* Solid experience in Java 8;
* Solid experience in Java open-source frameworks, including developing using modern frameworks, e.g. Spring Boot;
* Deep expertise in designing & developing RESTful APIs and microservices-based system;
* Proven experience using API and microservices utilizing AWS;
* Practical experience in Containers (ECS, Kubernetes, Docker) and FaaS (AWS Lambda) technologies;
* Experience in Agile development environments;
* Well-versed in writing structured, well-documented, maintainable and clean code;
* Strong English communication skills (both verbal & written), especially in the global software development environment

# Why it would be awesome to work with us?

* Join a global software development environment
* Competitive remuneration package
* Enjoy exceptional perks (tech/non-tech training courses, extra health insurance for you and your family (2 members), daily snack, billiards competition, ... you name it.)
* Business Trips to Australia
* Comfortable and inspiring workplace

# Contact

* E: linh.truong@pycogroup.com 
* M: 0787 363 214
* Skype: linh.truong.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
