### ISSUE TITLE
[LINAGORA] SENIOR PHP DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1958]
## Location

* No. 1 Thai Ha Street, Dong Da Dist., Hanoi

## Salary Expectation

* Up to 40M VND/ Month

## Requirements

* BS/MS degree in Computer Science, Engineering or a related subject.
* Proficient in PHP web frameworks (+3 years experience): Laravel Bootstrap, WordPress is required.
* Ability to read, write and communicate in English is requited.

### Responsibilities

* Work directly with BA, Designer to produce detailed.
* Work with QA to warranty the quality and on time delivery product to customer.
* Write “clean”, well-designed code.
* Troubleshoot, test and maintain the core product software and databases to ensure strong optimization and functionality.
* Contribute in all phases of the development life cycle.
* Develop and deploy new features to facilitate related procedures and tools if necessary.

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact

* Homepage: https://linagora.com/
* Contact: vnhr@linagora.com or 086.550.4412 (Ms Phuong)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
