### ISSUE TITLE
[GHN] Product Owner - HCM - Fulltime

### ISSUE THREAD

**Issue by NguyenNguyen2410** [awesome-jobs/vietnam#1959]
Product Owner is an important role to connect user with Engineer team. You will be in charge everything about product since it’s an idea till it launches to production. Follow it, enhance it, make users happy, do metrics calculation to prove your product is healthy.

## Location

* Ho Chi Minh
* Fulltime  

## Salary Expectation

* $700-$1000/month

## **YOU WILL**

* Analyze operation process to provide solutions by system. 
* Setup plan for feature development. 
* Write specification to help developers implement the product. 
* Give opinion to improve UI/UX. 
* Support UAT in testing, verifying bugs/issues. 
* Monitoring product & tracking new features, analyze what feature need to be improved.

## **YOUR SKILLS AND EXPERIENCE**
* At least 1+ years of experience as Product Owner/Business Analyst.
* Customer perspective: always play customer role when considering to create / update / remove a feature.
* Able to use mockup software to design UX/UI, layout and navigation flows.
* Communicate with impact: able to explain complex problems in one or two sentences.
* An attention to details and a never-satisfying attitude: able to pick out small discrepancies in layout design and propose solutions.
* Simple approach: always find simplest solutions

### **WHY YOU'LL LOVE WORKING HERE**

* Fair team 
* Annual health check-ups.
* Sports club: Running, football, badminton
* Open communication with Senior Engineer & Technical Leader
* Challenging working environment with attractive domain as Logistics
* Specific pantry with nice decoration & Coffee/Milk Coffee/Chocolate & Tea
* Comfortable Private working Area for TECH team
* Annual Team-building + Outing trip
* Join Training Courses and Tech Sharing
* Mid-Autumn Party, Christmas party, Year-end Party
* With the delivery network cover more than 98% geographical area of Vietnam, you will be welcome anywhere in Vietnam for traveling
* Competitive salary and 13th-month pay.

### Contact
Homepage: https://ghn.vn/
https://www.linkedin.com/company/giaohangnhanh/
Mr.Nguyen
Email: nguyennvb@scommerce.asia
Telegram: https://t.me/NguyenNVB

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
