### ISSUE TITLE
[LINAGORA] FRONT-END VUE/ANGULAR DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1960]
## Location

* 1 Thai Ha, Dong Da Dist., Hanoi

## Salary Expectation

* Negotiable

## Requirements

* 3+ years of professional experience in developing websites & web applications
* 2+ years of professional experience in TypeScript
* 2+ years experience with Angular 8+ or VueJS 2.2+
* Good understanding of code versioning with Gitlab
* Able to work with an Issues Tracking system (Redmine, Jira)
* Experience with Bootstrap 4+ and LESS
* 2+ original mobile apps developed in Angular or VueJS
* Experience with cross-browsers compatibility issues
* Client side validation and error handling best practices
* Great communicator in Vietnamese and in English, at least in writing

### You’ll be responsible for

* Development of front ends web applications and web sites based on provided design and specifications.
* Create/Implement design prototypes, including graphic design, site navigation, and layout of content, for company and other affiliate websites.
* Interact with PM to raise user experience and interface issues and resolution.
* Cross-browser and cross-platform integration, testing and problem solving.
* Research and apply adequate libraries, frameworks, tools, technologies.
* Advise and participate in design/code reviews.
* Work closely with members of project teams to make sure all specifications is satisfied.

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee. 

### Contact

* Homepage: https://linagora.com/
* Email: vnhr@linagora.com 
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
