### ISSUE TITLE
[LINAGORA] NODEJS DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1961]
## Location

* 1 Thai Ha, Dong Da, Ha Noi

## Salary Expectation

* Negotiable

## Requirements

* Work closely with our Product and Server teams to gather requirements
* Work in an agile scrum environment and develop using a continuous deployment cycle
* Building REST APIs using NodeJS
* Developing low-latency, high-availability, scalability and security for web services.

### You’ll be responsible for

* Good understanding fundamental design principles of scalable and distributed systems
* Experience turning performance and making things faster
* 2+ years experience working with or integrating with server-side NodeJS applications
* 2+ years of experience in RESTful web services.
* Experience with databases: MongoDB, Postgres, Redis, MySQL.
* Experience with frameworks including NestJS, Sails, Loopback, or Express.
* Understanding Angular and/or VueJS interaction with NodeJS
* Experience with GraphQL or Falcor is a plus
* Experience in developing NodeJS modules is a plus

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact
* Homepage: https://linagora.com/
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
