### ISSUE TITLE
[LINAGORA] SOFTWARE TESTER -  HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1962]
## Location

* 1 Thai Ha, Dong Da, Hanoi

## Salary Expectation

* Negotiable

## Requirements

* Has strong background of testing
* Has strong analysis skills
* Able to do multi-tasks
* Able to do testing based on DB
* Have knowledge in database structure• Able to train/support other team members
* Able to understand the algorithm, business logic
* Good in English (document reading comprehension)

### You’ll be responsible for

* Be responsible for a project testing from UI to DB
* Perform testing in multi-projects
* Cooperate with Development team for requirement analysis and improvements
* Be back-up of TL for handling projects in team
* Study and apply automation test in tea

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact

* Homepage: https://linagora.com/
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
