### ISSUE TITLE
[LINAGORA] SENIOR BE NODEJS/ GRAPHQL DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1963]
## Location

* 1 Thai Ha, Dong Da, Hanoi

## Salary Expectation

* Negotiable

## Requirements

* 5+ years experience in TypeScript with deep understanding of types and schemas development with NodeJS.
* 5+ years professional experience with GraphQL, Swagger, Kafka, gRPC, Graphene including building serverless GraphQL API on top of a Microservice architecture
* 5+ years professional experience in NodeJS, NestJS, Sails, Loopback, Express, Fastify and Koa
* 5+ original apps developed in with GraphQL or Falcor
* Mastering Multi-Threading, Multiple Process, Caching, Clustering in Node.js
* Experience with numerous NodeJS NPM packages
* Experience with RESTful APIs, OAuth authorization mechanisms, JSON Web Token
* Experience with relational databases (MySQL, PostgreSQL or Oracle) and NoSQL
databases (MongoDB, DynamoDB, Elastic Search, Redis or Cassandra)
* Experience with Angular 8+ or VueJS 2.2+ is a plus
* Full understanding of GraphQL and NodeJS security weaknesses and having experience to secure it
* Speaking and writing English is a must

### You’ll be responsible for

* Building highly-scalable and resilient infrastructures
* Developing APIs / GraphQL endpoints with a strong focus on security
* Work on cutting-edge apps that will be used by millions of consumers
* Work collaboratively in a cross-functional team (PM, UX, R&D) to transform user stories into prototypes & production code
* Thoughtfully apply software architecture principles & best practices
* Contribute to our existing platforms identifying & eliminating performance and scale issues that ripple from front-end to back-end

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact

* Homepage: https://linagora.com/
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
