### ISSUE TITLE
[LINAGORA] SENIOR NATIVESCRIPT MOBILE DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1964]
## Location

* 1 Thai Ha, Dong Da, Hanoi

## Salary Expectation

* Negotiable

## Requirements

* 3+ years experience with Angular 8+ or VueJS 2.2+, and in NativeScript.
* 3+ years experience with testing frameworks including FastLane, TestFairy, Appium, and SauceLabs.
* 2+ years experience with one GraphQL framework.
* Experience with numerous NativeScript plugins including Firebase, Notification Banner, Push Notification.
* Experience with UI Kits, RESTful APIs, Oauth authorization mechanisms, JSON Web Token.
* Solid working knowledge of Git and SCM best practices.
* Professional experience with NodeJS and NestJS.
* Good knowledge on Placing Apps in stores.
* Experience with PhoneGap, Cordova, CoreData, SQLite, Swift and Kotlin is a plus.
* Speaking and writing English is a must.

### You’ll be responsible for

* Working on a cutting-edge app that will be used by millions of customers.
* Work collaboratively in a cross-functional team (PM, UX, R&D) team to transfer user stories into prototypes & production code.
* Thoughtfully apply UI design principles & best practices for both iOS and Android.
* Build an app with best engineering practices.
* Identify and eliminate performance and scales issues that ripple from front-end to back end.

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact

* Homepage: https://linagora.com/
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
