### ISSUE TITLE
[LINAGORA] SYMFONY/LARAVEL DEVELOPER - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#1965]
## Location

* 1 Thai Ha, Dong Da, Hanoi

## Salary Expectation

* Negotiable

## Requirements

* Front-end and Back-end work
* Easily understand written English such as customer requirements
* Occasionally write some internal deliverable in English
* Bachelor’s Degree in Computer Science/IT
* 1 to 4 years experience in web development
* Experience in PHP, MySQL, HTML, CSS, JavaScript, XML
* Strong in OOP
* Experience in Symfony 2+ or Laravel 5+ framework
* Aptitude to learn and understand new and emerging technologies
* Ability to work independently with strong problem solving skills.
* Excellent communication and presentation skills, a positive attitude, and ability to work
* Experience with Git
* Understand non-functional requirements such as performance, scalability, security, extensibility, maintainability and consult Technical Leads to create solutions meeting those requirements for complex websites

### You’ll be responsible for

* Design the web application based on architecture and requirements (design packages, modules, design subsystems...).
* Coding, implementing, maintain, and troubleshoot the website or web application.
* Adhere to strict delivery schedules.

### Why it would be awesome to work with us

* An excellent working atmosphere, associated with a strong corporate culture.
* Opportunity to work in a culturally diverse team with high skilled people in international software projects.
* A high level of autonomy and responsibility.
* Attractive package and benefits: 13rd month bonus, lunch allowance, annual company trip, bar camp for tech teams, health-check, 14 annual leaves and others based on Labor Law.
* Open, modern working space, and free coffee.

### Contact

* Homepage: https://linagora.com/
* Email: vnhr@linagora.com
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
