### ISSUE TITLE
Koidra - Machine Learning Research Engineer - Saigon/Remote - FT

### ISSUE THREAD

**Issue by zer0n** [awesome-jobs/vietnam#1967]
<img src="https://user-images.githubusercontent.com/3055719/81139074-a5528c80-8f8e-11ea-99ad-f26f90201589.png" width="200">
is hiring talented machine learning research engineers (MLE). As a MLE, you will design and develop accurate, robust, and highly scalable machine learning models.

## Location
* Saigon, Vietnam
* Remote

## Salary Expectation
$700 - $2000/month

### Must Have
- Excellent programming, debugging, and analytical skills. In order to be a decent MLE at Koidra, you need to be a rock-solid software engineer first.
- Experience in building Deep Learning models using either PyTorch or Tensorflow
- Passion for working with open source frameworks
- Fit our culture, explained in [Koidra's core principles](https://www.notion.so/Core-Principles-3ad14330f8ab4e418e8c1dc35968d9bb)

### Ideally
- Solid understanding of Neural Networks, CNNs, RNNs, their advantages as well as their limitations
- Basical understanding of Bayesian learning, probabilistic modeling, uncertainty quantification, etc.
- Experience in building models for time series or sequential data

### Exceptions
For this position, we will also hire fresh graduates who are high achievers, technically strong, and interested in real-world machine learning. We will train you!

## Responsibilities
- Contribute to the open-source [Deep4Cast](https://github.com/MSRDL/Deep4Cast) library, in conjunction with Microsoft data scientists
- Develop accurate, robust, and efficient deep learning models. And deploy these models and end-to-end. You will work on real-world ML problems that are key to our products.
- Develop other components for our AI platform and solutions

## Why it would be awesome to work with us
Founded by Kenneth Tran, formerly a Principal Machine Learning Scientist at Microsoft Research (MSR), Koidra's mission is to change the industrial automation industry, applying cutting edge research in AI, IoT, and hybrid cloud+edge computing. Check out some early **[media coverage about us](https://www.notion.so/Press-Releases-354cdc2b6461476b98c2d01dfa1d22dc)**.

At Koidra, you'll have an opportunity to work with world experts in both Machine Learning and Software Engineering.

**Other benefits**
- Active and agile working environment; flexible time culture
- An environment for you to be maximally productive
- Opportunity to impact the company (and hence the global stage) in big ways

## Contact
Kenneth Tran (CTO): ken@koidra.ai (0935069639 or WhatsApp: +15124363250)

**Comment by hongquan** [comment]
Look nice

**Comment by ng-hoangduc** [comment]
Is it still open?

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
