### ISSUE TITLE
UNIT CORP - JAVA DEVELOPER - HCM - FT #HCM #Java #Fulltime

### ISSUE THREAD

**Issue by PhamNhuY18** [awesome-jobs/vietnam#1968]
## Location

* Saigon, Vietnam
* Full time; Monday - Friday (8:30 AM - 5:30 PM)

## Salary Expectation

* Up to $1500/month or range

## Requirements
* Java core, Java 8, JEE2
* Spring MVC Framework
* Oracle, My SQL, SQL Server
* 2+ years Software Engineering experience

### Must Have

* Ability to work independently & teamwork
* Work with attitude “Nothing is impossible”

### Ideally

* Good at basic programming knowledge: OOP

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* In charge of programming, error checking & reporting for line manager
* Participate in big projects belongs to Banking, Finance & Insurance
* Participate in developing projects on Java & other technologies

### Why it would be awesome to work with us
* Understand the process of design software product, get knowledge about business, and know the purpose of products;
* The process is designed & built from the beginning, understanding the expertise in each area;
UNIT specializes in making solutions and products related to: Banking, Insurance, Finance, Construction;
* Opportunity to learn and develop skills in many fields;
* Opportunity to join many big projects in Vietnamese & foreign markets;
* Working on the latest technology platform;
* Friendly working environment and many chance to develop & challenge;
* Rewards on projects and work efficiency;
* UNIT-Care health care insurance;
* Join in company trip, teambuilding & community activities.

### Contact
Homepage: https://unit.com.vn/
Mail: yptn@unit.com.vn or Skype: yptn13405

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
