### ISSUE TITLE
UNIT CORP - .NET DEVELOPER - HCM- FT

### ISSUE THREAD

**Issue by PhamNhuY18** [awesome-jobs/vietnam#1969]
## Location

* Saigon, Vietnam
* Full time : Monday -  Friday

## Salary Expectation

* $1000/month or range

## Requirements
* .Net core, 
* ASP.NET Framework
* Oracle, PostgreSQL, SQL
* 1+ years Software Engineering experience

### Must Have

• Requires 1 years of experience in technology development which may include using .NET technologies (C#) SQL development (SQL Server) and Oracle database.
• Understanding of Cloud based solutions hosted in AWS and CI/CD practices.
• Knowledge in client-side libraries like Angular, ReAct and Secure coding.
• Contribute strong technical expertise to software product development for head department and IT manager.
• Familiarity with the ASP.NET framework, SQL Server and design/architectural patterns (e.g. Model-View-Controller (MVC)).
• Knowledge of at least one of the .NET languages (e.g. C# .NET) and HTML5/CSS3.
• Familiarity with architecture styles/APIs (REST, RPC).
• Understanding of Agile process methodologies.

### Responsibilities

• Participate in requirements analysis.
• Collaborate with internal teams to produce software design and architecture.
• Write clean, scalable code using .NET programming languages.
• Test and deploy applications and systems.
• Revise, update, refactor and debug code.
• Improve existing software.
• Develop documentation throughout the software development life cycle (SDLC).
• Serve as an expert on applications and provide technical support

### Why it would be awesome to work with us
•Negotiation salary depends on candidate’s ability

•Total income from 13 to 14 months of salary

•Rewards on each project

•Participate in community & extracurricular activities
•Understand the process of design software product, get knowledge about business, and know the purpose of products;
•The process is designed & built from the beginning, understanding the expertise in each area;
UNIT specializes in making solutions and products related to: Banking, Insurance, Finance, Construction;
•Opportunity to learn and develop skills in many fields;
•Opportunity to join many big projects in Vietnamese & foreign markets;
•Working on the latest technology platform;
•Friendly working environment and many chance to develop & challenge;
•Rewards on projects and work efficiency;
•UNIT-Care health care insurance;
•Join in company trip, teambuilding & community activities.
### Contact
Homepage: https://unit.com.vn/
Mail: yptn@unit.com.vn or skype: yptn13405, Telegram ( 058.619.0390)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
