### ISSUE TITLE
[Scommerce] Full Stack Engineer

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#1970]
We are looking for a highly skilled computer programmer who is comfortable with both front and back end programming. Full Stack Engineer are responsible for developing and designing front end web architecture, ensuring the responsiveness of applications and working alongside graphic designers for web design features, among other duties.
 
Full Stack Engineers will be required to see out a project from conception to final product, requiring good organizational skills and attention to detail.

RESPONSIBILITIES:

* Developing front end website architecture.
* Designing user interactions on web pages.
* Developing back end website applications.
* Creating servers and databases for functionality.
* Ensuring cross-platform optimization for mobile phones.
* Ensuring responsiveness of applications.
* Working alongside graphic designers for web design features.
* Seeing through a project from conception to finished product.
* Designing and developing APIs.
* Meeting both technical and consumer needs.
* Staying abreast of developments in web applications and programming languages.

*REQUIREMENTS:*

* Degree in Computer Science.
* Strong organizational and project management skills.
* Proficiency with fundamental front end languages such as HTML, CSS and JavaScript.
* Familiarity with JavaScript frameworks such as Angular JS, React and Amber.
* Proficiency with server side languages such as Python, Ruby, Java
* Familiarity with database technology such as MySQL, Oracle and MongoDB.
* Excellent verbal communication skills.
* Good problem solving skills.
* Attention to detail.
* Preferred Requirements:
    * Experienced using Google Cloud Platform (GCP) cloud services.
    * Identify suitable GCP technologies, databases, and services to create a suitable ecosystem for our applications.
    * Setup CI/CD for automatic deployment on GCP.

*YOU’'ll LOVE WORKING HERE*

*  13th salary.
* Performance bonus 
* Comfortable Private working Area for TECH team
* PVI Care
* Team-building.
* Outing trip Join Training Courses and Tech Sharing 
* Mid-Autumn Party, Christmas Party Year-end Party 
* With the delivery network cover more than 98% the geographical area of Vietnam, you will be welcome anywhere of Vietnam for traveling
* Sports club: football, badminton

*ADDRESS: 3rd Floor, Rivera Park Building, 7/28 Thanh Thai,  District 10, Ho Chi Minh*
Please contact  Ms. Anh Hoang via Email (anhhnt@scommerce.asia) or phone number (0981 851 385) if you’ve got any concern on this position

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
