### ISSUE TITLE
[GHN] Senior Software Engineer (Java, Golang)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#1971]
### Your responsibility will be involved in development from front-end to back-end including:

* Participate in all phases of the development life-cycle
* Design and write technical specification
* Collaborate with cross-functional teams to design, develop and delivery new features
* Perform bugs fixing, maintaining, enhancement of existing application
* Optimize the system for reliability and performance

### YOUR SKILLS AND EXPERIENCE

* 4+ year of exprience as a Software Developer
* Good knowledge of OOP, Design Pattern, Data Structure, Algorithm
* Knowledge with Python, OpenERP is a plus
* Familiar with RESTful API
* Experience with Java or Golang 
* Experience with SQL, NoSQL, Caching
* Experience with messaging system such as ActiveMQ, Rabbit, Apache Kafka etc.
* Experience with Google Cloud, Kubernetes is a plus
* Experience with HTML, CSS, JS is a plus 
* Self-motivated to explore new technologies and environments.

### YOU’'ll LOVE WORKING HERE*

* 13th salary.
* Performance bonus Comfortable Private working Area for TECH team
* Team-building.
* Outing trip Join Training Courses and Tech Sharing Mid-Autumn Party, Christmas
* Party Year-end Party With the delivery network cover more than 98%
* the geographical area of Vietnam, you will be welcome anywhere of Vietnam for traveling
* Sports club: football, badminton

### ADDRESS: 3rd Floor, Rivera Park Building, 7/28 Thanh Thai, District 10, Ho Chi Minh
Please contact Ms. Anh Hoang via Email (anhhnt@scommerce.asia) or Skype: tremlobisi94 if you’ve got any concern on this position

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
