### ISSUE TITLE
[AHAMOVE]SENIOR UI/UX DESIGNER - HCM - FT

### ISSUE THREAD

**Issue by duongnhi126** [awesome-jobs/vietnam#1972]
## Location

* Saigon, Vietnam

## Salary Expectation

* 1000$ - 2000$/month

## Requirements
* **Minimum 4 years hands-on experience** with background in Wireframing, Information Architecture, User experience and UI Design for web and mobile interfaces
* Experience designing and conducting user research, including contextual inquiry and usability testing
* Excellent deliverables including prototypes, detailed page schematics, sketches, interaction flows, site maps, navigation systems, and web-appropriate writing
* Ability to work well with engineers team and product team to articulate issues and communicate persuasively Experience working in small collaborative teams
* Ability to work independently, prioritize, and solve problems proactively
* An outstanding portfolio that demonstrates your approach to projects, quality thought, storytelling, and an ability to bring your ideas to life

## Skills
* User experience
* User Interface

### Responsibilities
* Design the information architecture and interaction models for our projects. This may include websites, mobile experiences, or other touch-points
* Work in close collaboration with Development and Product Management teams to develop initial strategy—addressing product, brand, marketing, content, and overall user experience
* Conduct user research including contextual interviews and usability testing, and present findings to customers/partners
* Create internal and external deliverables including conceptual diagrams, site maps, interaction flows, storyboards, schematics/wireframes, and detailed functional specifications
* Work iteratively; develop ideas from sketches to prototypes
* Collaborate with engineers team and product managers to generate superb design work

### Why it would be awesome to work with us
* Disruptive innovations
* People-oriented philosophy of doing business
* Sharp, motivated colleagues in a fun office environment
* Competitive salaries and benefits according to experience and education level
* Performance bonus Comfortable Private working Area for TECH team

### Contact
Email: nhidnl@scommerce.asia
Skype: nhidnl1212_1
Phone: 0917121296

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
