### ISSUE TITLE
Fetch Technology - PHP Laravel - HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#1978]
![image](https://user-images.githubusercontent.com/60914247/81652093-62e0f200-945d-11ea-918c-5139b8e9ecfd.png)
## Ha Noi

* Full Time

## Requirements
* At least 3 years of experience on PHP, include at least 2 year experience working with Laravel Framework (your current work need to be work with Laravel framework), PostgreSQL and Bootstrap front-end framework.

*  Experience in MySQL and data modelling.

*  Expert with Git and knowledgeable with Git workflow.

*  Ability to convert PSD design into HTML5 and CSS3/Sass.

* Demonstrated analytical, problem-solving, interpersonal and communication skills.

*  Experience with C++, C# or Android app development will be a bonus.

*  Experience in VueJS JavaScript Framework is a plus.

## Responsibilities

* Ideally you are equally strong in front-end programming languages: HTML, JavaScript, CSS/ Sass, styling and Back-end programming Languages: PHP, SQL.

* Developing and maintaining client-facing and back-end operation web applications.

* Testing and code review to ensure applications free of bugs.

* Implementing UI and UX designs created by our designer.

* Ensuring cross-platform optimization for mobile phones.

* Ensuring responsiveness and security of applications.

* Seeing through projects from conception to finished product.

* Designing, developing and consuming RESTful API.

* Staying abreast of developments in web applications and programming languages.

* Leading of junior developer and participating in code reviews.

## Why it would be awesome to work with us?
* Being a Software developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.

* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.

* Working directly with foreign client, all your dedication to work will be fairly recognized for performance review.

* Extensive on job training, you will always have chance to work with new emerging technologies.

* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.

* 12-day annual leave per year.

* 13th month salary.

* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact: 
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by muhamedRadwan** [comment]
can I apply now?
