### ISSUE TITLE
[LARION] - [Senior NodeJS Developer] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#1981]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 1500$ - 2500$

## Requirements

* At least 3 years of working experience with NodeJS
* Strong proficiency in JavaScript, ECMAScript6+, and TypeScript
* Good experience with micro-services architecture and its core principles and challenges
* Experience with Kafka queue, ElasticSearch
* Experience with NoSQL, Cassandra, Redis, CQRS and EventSourcing is a plus
* Good team player and technical leadership skills
* Good time management skill
* Good interpersonal and communication skills

### Responsibilities

We are looking for a senior/ team lead NodeJS who is experienced with micro-services architecture.
The primary focuses on leading a team and implementing backend APIs for frontend applications. A
commitment to collaborative problem solving and product quality are important.

* Coordinate with various teams working on distinct layers to clarify system requirements and dependences
* Provide technical approach and guide a group of developers to complete sprint goals
* Close collaborating with technical lead to complete non-functional system requirements
* Develop RESTFul APIs to support frontend applications

### Why it would be awesome to work with us

* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year,
Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, etc.

### Interesting engineering projects

* Supply Chain product

### Contact

* Please send CV via email: recruitment@larion.com
* For further information, please contact via Skype: ngoctranthibao/ Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
