### ISSUE TITLE
[LARION] - [IT Business Analyst] - [Saigon] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#1982]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 700$ - 1500$

## Requirements

* Proactively communicate and collaborate with external and internal stakeholders to analyze information needs and propose viable solutions that bring high value for business and end-users
* Deliver requirements clearly and comprehensively to ensure the understanding of Development team
* Work with Development team to review specifications, consider solutions and solve problems
* Scope and prioritize development activities based on system, available resources, business goals, and end-user impact
* Propose new features (as well as improvements/ enhancements) for software
* Assist bidding in pre-sales support activities especially on analysis phase

### Responsibilities

* At least 1.5 years of experience in software industry as Business Analyst or similar position
* Good knowledge of Software Development Life Cycle
* Strong at the tools, techniques, processes required to capture requirements at generic and detailed levels. For example: UML, Mindmap, Trello, Basecamp, etc.
* Ability to write documents Business Requirement Spec, SRS etc.
* Analytical and structured work method, detail-oriented, critical thinking
* Good English skill (read and understand specialized documents)
* Good communication and interpersonal skills, flexibility and teamwork spirit
* Specific business domain knowledge in DMS, Supply Chain or ERP is a plus

### Why it would be awesome to work with us

* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year,
Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, etc.

### Interesting engineering projects

* Supply Chain product

### Contact

* Please send CV via email: recruitment@larion.com
* For further information, please contact via Skype: ngoctranthibao/ Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
