### ISSUE TITLE
FPT Telecom - Sr/Jr/Fr/Big Data Engineer (Scala, Hadoop Ecosystem) - District 7, HCMC - FT

### ISSUE THREAD

**Issue by vinhdangphuc** [awesome-jobs/vietnam#1984]
## Location

* FPT Tan Thuan 2, Tan Thuan Road, Tan Thuan EPZ, District 7, Ho Chi Minh City, Viet Nam

## Salary Expectation

- Fresher: 400$ - 700$+
- Junior: 700$ - 1500$+
- Senior: 1500$ - 2000$+

## Requirements

- Good at problem solving, algorithms, data structures, functional programming, design pattern
- Good knowledge of SQL, database systems
- Basic knowledge of Linux and operating system
- Experience with programming, ideally Scala, Java or Python,..
- Constantly challenge yourself, upgrade yourself every day

**For Senior Level:**
- Experience in software engineering and distributed system architecture design
- Having knowledge & experience of Hadoop Ecosystem (Spark, Hadoop, HBase, Kylin, Clickhouse, ELK,..)
- Strong experience in designing data-intensive systems with Lambda / Kappa Architecture
- Strong experience with Networking & Linux system
- Experience in project management, good time management, communication and teamwork skills
- Strong leadership skills

### Must Have
* Willing to learn, attention to details
* Ability to communicate with both technical and non-technical team members

### Responsibilities
- Research, design and develop the data processing pipeline for real-time analytics dashboard and monitor our infrastructure and OTT services
- Building toolsets/frameworks to manage, integrate with the various data sources, provide an efficient way for data science and business team exploring the data
- Using Spark, SQL, Hadoop to manipulate data pipeline, improve and extend fault-tolerant pipelines to integrate large amounts of data from many diverse storage systems, databases
- Evaluate and develop new technologies/solutions to make our infrastructure more reliable, high availability
- Working with data scientist in the design of machine learning models, analysing our customer behaviour, improve user experiences

**For Senior Level:**
- Build high-performance data warehouse, BI platform for data analytics, handle high volume of streaming data (terabytes per day)
- Taking lead on technical best practices and internal research
- Working with stakeholders to define system specifications, plan and design the system architecture, select appropriate software or hardware and suggest integration methods
- Solving technical problems, mentoring other junior team members, build a good team culture

### Why it would be awesome to work with us

- Great opportunity to dive deeply into a big data system with high volume of data in challenging domains
- Challenging working environment, open for new ideas and solutions
- We often conduct presentations to improve our individual skill sets, sharing our domain knowledge together
- You are encouraged to contribute ideas, corporate with the others and get your ideas to work efficiently
- Unique culture with many exciting activities: rookie training, 72 hours experience, team building, village festival, club, color fest, happy hour, birthday celebration,...
- Best employees are awarded a company-sponsored overseas trip every year
- Obtaining full legal insurance coverage with FPT-Care (official employee)

-----------------------------------------------------------------------------------------------------------------------------
## About FPT Telecom

FPT Telecom is one of the biggest internet companies in Viet Nam, we are currently providing a variety of telecom products and services including:
* ADSL/VDSL, TriplePlay, FTTH
* Leased line, Domain, Email, Web Hosting, Data Center
* Internet value-added services: FPT TV, Voice over IP (VoIP), Remote Monitoring (IP Camera), Certificate Authority (CA), Cloud Computing,...

FPT Telecom is constantly researching and implementing more and more integrated value-added services on one same Internet connection to provide maximum benefits to customers.

## Contact

Vinh Dang
Email: vinhdp4@fpt.com.vn  
Skype: [live:vinhdp_2](https://join.skype.com/invite/bZueGEcKLmPe)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
