### ISSUE TITLE
FPT Telecom - Fullstack Engineer - District 7, HCMC - FT

### ISSUE THREAD

**Issue by vinhdangphuc** [awesome-jobs/vietnam#1985]
## Location

* FPT Tan Thuan 2, Tan Thuan Road, Tan Thuan EPZ, District 7, Ho Chi Minh City, Viet Nam

## Salary Expectation

- Fresher: 400$ - 700$+
- Junior: 700$ - 1000$+
- Senior: 1000$ - 2000$+

## Requirements

- Good at problem-solving, algorithms, data structures, functional programming, design pattern
- Good knowledge of SQL, relational database systems
- Good at programming, ideally Scala, Java or Python,...
- Good at frontend technologies like Angular.js, React.js or vue.js.
- Constantly challenge yourself, upgrade yourself every day

**For Senior Level:**
- Experience in large scale deployment and performance tuning
- Experience in JVM based technologies
- Strong at object-oriented analysis and design
- Experience in project management, good time management, communication and teamwork skills
- Strong leadership skills

### Must Have
* Willing to learn, attention to details
* Ability to communicate with both technical and non-technical team members

### Responsibilities
- Build toolset for data exploration, data governance, API services, bring insight to end-users
- Develop our backend systems as well as frontend modules, reporting dashboard
- Design and implement scalable and reliable RESTful APIs using micro-services architecture, modern web frameworks
- Ownership of the services you develop & maintain to ensure their availability
- Work with the other teams to ensure functionality, feature reliable, proactive, and efficient scaling
- Collaborate closely with data engineer, data analyst and scientist, propose and help them to decide scalable web applications architecture

**For Senior Level:**
- Working with DevOps to develop highly scalable services architecture, observability mechanism for monitoring
- Taking lead on technical best practices and internal research
- Working with stakeholders to define system specifications, plan and design the system architecture
- Solving technical problems, mentoring other junior team members, build a good team culture

### Why it would be awesome to work with us

- Great opportunity to dive deeply into a big data system with high volume of data in challenging domains
- Challenging working environment, open for new ideas and solutions
- We often conduct presentations to improve our individual skill sets, sharing our domain knowledge together
- You are encouraged to contribute ideas, corporate with the others and get your ideas to work efficiently
- Unique culture with many exciting activities: rookie training, 72 hours experience, team building, village festival, club, colour fest, happy hour, birthday celebration,...
- Best employees are awarded a company-sponsored overseas trip every year
- Obtaining full legal insurance coverage with FPT-Care (official employee)

-----------------------------------------------------------------------------------------------------------------------------
## About FPT Telecom

FPT Telecom is one of the biggest internet companies in Viet Nam, we are currently providing a variety of telecom products and services including:
* ADSL/VDSL, TriplePlay, FTTH
* Leased line, Domain, Email, Web Hosting, Data Center
* Internet value-added services: FPT TV, Voice over IP (VoIP), Remote Monitoring (IP Camera), Certificate Authority (CA), Cloud Computing,...

FPT Telecom is constantly researching and implementing more and more integrated value-added services on one same Internet connection to provide maximum benefits to customers.

## Contact

Vinh Dang
Email: vinhdp4@fpt.com.vn  
Skype: [live:vinhdp_2](https://join.skype.com/invite/bZueGEcKLmPe)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
