### ISSUE TITLE
Yojee - DevOps Engineer - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#1986]
## Location

* District 4, Saigon, Vietnam

## Salary Expectation

* VND35m to VND55m gross per month

## Requirements
* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 2+ years of experience in development of various complex systems.
* Experienced and proficient in working with one of these languages, preferably Elixir, Javascript, Ruby on Rails, Go, Scala, Haskell or any other functional programming language.
* DevOps experience with AWS, GC or Azure, Docker, CI tools, configuration management tools.
* Scripting (Python, Lambda, Bash).
* Experience working with relational database systems (preferably PostgreSQL) and Elasticsearch
* Experience in working with Kubernetes for automation and configuration.

## Nice to have
* Experience with frontend technologies like Angular.js, React.js or Vue.js.
* Production experience with Elixir & Phoenix.
* Open source repositories and contributions.

## Reporting Structure - Who Will Help You Win
* This role will be located in Vietnam and will report to the VP of Engineering (Platform).

## Responsibilities
* Plan, monitor, maintain and improve Platform Infrastructure, supporting Development and Operational needs by focusing on points below but not limited to: -
* CI / CD Pipeline,
* Infrastructure Scalability,
* Infrastructure Security,
* Infrastructure Configuration Management,
* Load testing & Benchmarking.
* May be required to perform other related duties as required.

## Why it would be awesome to work with us

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimises freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

## Contact
Homepage: yojee.com
Lily: lily@yojee.com 

## How to apply
Apply [here](https://yojee.bamboohr.com/jobs/view.php?id=68&source=Github)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
