### ISSUE TITLE
NAB VDC - Senior Front End Reactjs Engineer - Saigon - FT 

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1987]
# Location

* Etown 3, Tan Binh Dist., Saigon

# Salary Range

* USD Super Attractive 

#### NAB is undergoing an exciting "Cloud First" technology transformation by taking advantage of the latest tools and techniques used by leading technology and digital companies globally. But it’s not just about the Tech, we are also investing heavily in our people, so if you have an appetite to learn, grow and elevate others around you, this is the place for you!   

# Responsibility 
#### As Senior Frontend Engineer (Reactjs) at NAB, your scope includes but not limited to the followings:

* Design, develop, review, implement, and manage React.js application code and services for the production and pre-release environments;
* Design, develop, review, implement, and manage continuous integration, build management and deployment scripts, systems and any code as required;
* Participate in Agile software development, prototyping, and code review with international development teams to build scalable microservices-based products;
* Understand the requirements of the customer or business and utilize this knowledge to develop applications that are consistent with this;
* Work with delivery teams to achieve success through development using CI/CD and DevOps practices, processes and tooling;
* Provide robust coding practices, solid unit/component test coverage, and debugging code.

# Requirement
* +5 years' experience working in Software Development
* ​Solid experience in JavaScript ES6/TypeScript working with React.js or similar technologies (Angular.js, Vue.js);
* Expert in all areas of web development (HTML5, CSS3, Bootstrap, Foundation, JQuery, JSON) including accessibility and security concerns;
* Solid experience in modern front-end build pipelines and tools (e.g. Git, Webpack, Gulp, NPM);
* Experience in Cloud computing and Amazon Web Services - particularly Serverless Development:
* Experience in Containers (ECS, Kubernetes, Docker) and FaaS (AWS Lambda) technologies.
* Strong understanding of RESTful APIs design (GraphQL desirable) and microservices-based systems;
* Experience in DevOps and Continuous Delivery skillset
​* Experience in modern CI/CD pipelines and tools (e.g. Git, Ansible, Jenkins, Gulp, NPM, Gradle).
* Solid experience in Agile development environments;
* Well-versed in writing structured, well-documented, maintainable, and clean code;
* Excellent in problem-solving and analytical skills;
* Strong understanding of standard Software Engineering processes, Testing, and Agile methodology;
* Strong English communication skills (both verbal & written), especially in the global software development environment.

# Why it would be awesome to work with us?

* Join a global software development environment
* Competitive remuneration package
* Enjoy exceptional perks (tech/non-tech training courses, extra health insurance for you and your family (2 members), daily snack, billiards competition, ... you name it.)
* Business Trips to Australia
* Comfortable and inspiring workplace

# Contact

* E: linh.truong@pycogroup.com 
* M: 0787 363 214
* Skype: linh.truong.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
