### ISSUE TITLE
NAB VDC - Technical Architect (Nodejs/Reactjs)- Saigon - FT 

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#1988]
# Location

* Etown 3, Tan Binh Dist., Saigon

# Salary Range

* USD Super Attractive 

#### NAB is undergoing an exciting "Cloud First" technology transformation by taking advantage of the latest tools and techniques used by leading technology and digital companies globally. But it’s not just about the Tech, we are also investing heavily in our people, so if you have an appetite to learn, grow and elevate others around you, this is the place for you!   

# Responsibility 
#### We're on the hunt for top Technical Architect (ReactJS + NodeJS) who is passionate about great quality digital products and willing to work on the entire stack, from DevOps, API to front-end and even testing automation. You love solving problems, have the ability to work independently but even better in a team and you have a strong thirst to learn new technology and frameworks. We are looking for great team players that share their knowledge and willing to do what it takes to deliver:

* Collaborate with other NAB's technology leaders towards improving and fulfilling the NAB technical direction;
* Evangelize and promote JavaScript - Node.js & React.js best practices;
* Design, develop, review, implement, and manage Node.js & React.js application code and services for the production and pre-release environments;
* Design, develop, review, implement and manage continuous integration, build management and deployment scripts, systems, and any code as required;
* Participate in Agile software development, prototyping, and code review with international development teams to build scalable microservices-based products;
* Understand the requirements of the customer or business and utilize this knowledge to develop applications that are consistent with this;
* Work with delivery teams to achieve success through development using CI/CD and DevOps practices, processes and tooling;
* Provide robust coding practices and solid unit and component test coverage, and code debugging.

# Requirement
* Experience architecting, developing, and deploying modern architectural patterns/techniques (microservices, DDD, TDD ...)  
* Experience as a Technical Architect in a complex, enterprise-level development environment;
* +10 years' experience working in Software Development covering Web Development, JS MV* and Microservices
* Solid DevOps and Continuous Delivery skillset: Experience in modern CI/CD pipelines and tools (e.g. Git, Ansible, Jenkins, Gulp, NPM, Gradle)
* Solid experience in modern front-end build pipelines and tools (e.g. Git, Webpack, Gulp, NPM)
* Solid experience in Agile development environments;
* Well-versed in writing structured, well-documented, maintainable, and clean code;
* Excellence in problem-solving and analytical skills;
* Strong understanding of secure coding practices and application security;
* Strong work ethic, self-motivation, dedication, and commitment
* Excellent teamwork and coaching skills
* Strong English communication skills (both verbal & written), especially in the global software development environment

# Why it would be awesome to work with us?

* Join a global software development environment
* Competitive remuneration package
* Enjoy exceptional perks (tech/non-tech training courses, extra health insurance for you and your family (2 members), daily snack, billiards competition, ... you name it.)
* Business Trips to Australia
* Comfortable and inspiring workplace

# Contact

* E: linh.truong@pycogroup.com 
* M: 0787 363 214
* Skype: linh.truong.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
