### ISSUE TITLE
LINE Vietnam - Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by huynhminhtufu** [awesome-jobs/vietnam#1989]
## Location
* Saigon, Vietnam

## Salary Expectation
* Competitive and negotiable

### Must have
* Strong at Java, C/C++ or a system programming language
* Strong at the problem-solving skill
* Good at both verbal and non-verbal English

### Qualifications
* Proven experience in operating/structuring Big Data, Storage and Analysis System
* Understanding & experience in Data structure, Algorithm, Distributed System
* Motivation to join LINE in new global challenges and build success with LINE
* No problem with business trips overseas

## Responsibilities
* Architect and develop stable web service
* Rapidly build, iterate, test and deploy new features and products
* Maintain a high-quality robust codebase
* Manage and contribute code to large scale projects from inception to completion

## Why it would be awesome to work with us
* Competitive salaries and benefits according to experience and education level
* Developing your career in a famous product company and working with the latest technologies in the world.
* Working in a very Silicon Valley start-up style with a professional, international environment.
* A latest Macbook Pro 15" model with a 27" monitor, free snack and drink at office's pantry.

## Interesting engineering projects
* [LINE App](https://line.me/) ecosystem with monthly 200m active users.

## Contact
Email: tu.huynh@linecorp.com

**Comment by huynhminhtufu** [comment]
We're still hiring 😄

**Comment by huynhminhtufu** [comment]
We're still looking for new engineers in HCM :hand:

**Comment by huynhminhtufu** [comment]
We're still needing backend engineers in HCM ![](https://emoji.slack-edge.com/T0GCQ370X/arggg/dd230f01b4742079.gif)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
