### ISSUE TITLE
LINE Vietnam - Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by huynhminhtufu** [awesome-jobs/vietnam#1990]
## Location
* Saigon, Vietnam

## Salary Expectation
* Competitive and negotiable

### Must have
* Fluent in JavaScript, HTML5, CSS3 and have interest in core.
* Experienced in SPA development, with modern frontend frameworks.
* Good at both verbal and non-verbal English

### Qualifications
* Passionate about development, building highly functional, great eyes on details, always look for UX improvement to deliver the outstanding user experience.
* High ownership, self-sufficient and continuous effort to find solutions for doing repeated tasks, easily adapt and learn new things.
* Basic understanding of server, database, and good experience in RESTful API design and development.
* No problem with business trips overseas

## Responsibilities
* Implement frontend for web applications with modern technology (React, Vue.js).
* Improve the efficiency of existing products.
* Build the architecture and design of new products and features
* Implement UI components and libraries.

## Why it would be awesome to work with us
* Competitive salaries and benefits according to experience and education level
* Developing your career in a famous product company and working with the latest technologies in the world.
* Working in a very Silicon Valley start-up style with a professional, international environment.
* A latest Macbook Pro 15" model with a 27" monitor, free snack and drink at office's pantry.

## Interesting engineering projects
* [LINE App](https://line.me/) ecosystem with monthly 200m active users.

## Contact
Email: tu.huynh@linecorp.com

**Comment by huynhminhtufu** [comment]
We're still hiring 😄

**Comment by huynhminhtufu** [comment]
We're still looking for new engineers in HCM :hand:

**Comment by huynhminhtufu** [comment]
We're still needing frontend engineers in HCM ![](https://emoji.slack-edge.com/T0GCQ370X/arggg/dd230f01b4742079.gif)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
