### ISSUE TITLE
Perifit- React Native Software Engineer - Remote - FT

### ISSUE THREAD

**Issue by xiaohule** [awesome-jobs/vietnam#1996]
## Location
Remote in Vietnam (the rest of the team works remotely from Ho Chi Minh City)

## Salary Expectation
$1800 to $2600/month depending on experience

## Description
[Perifit](https://perifit.co/) is a femtech startup created in Paris, France currently offering the most fun and effective self-care solution for female pelvic floor muscles rehabilitation.
We’re a small size team in a fast-growing startup (500% YOY growth in 2019), so everyone that joins has a direct impact on the direction and success of the company. Today’s hires will be tomorrow’s leaders.

We are looking for passionate, hardworking React Native mobile app engineers who have experience building innovative mobile applications that customers love.

Our mobile application is the best ranked in its category with 4.7⭐ on [Google Play](https://play.google.com/store/apps/details?id=starshipproduct.perifitmainapp) and [Apple App Store](https://apps.apple.com/us/app/perifit/id1183437203). 
Your first mission will be to help us reach 5⭐!

## Responsibilities
* Mentor other team members on the application of the best React Native architectural principles and design patterns
* Contribute programming skills to develop world-class mobile apps with a grandiose user experience 
* Write clean, maintainable code and high-quality unit tests
* Identify and resolve functional, performance and scalability issues
* Work with a cross-functional team of software engineers, game developers, QA and Product Manager to build new features, measure their impact and learn about our users needs first hand
* Proactively identify and suggest areas of future work for the team
* Contribute to the technical support of our user to maintain an up-to-date vision of their pain points

## Requirements
* Bachelor’s Degree in Computer Science, Software Engineering, or related field
3+ years of professional React Native and Redux development experience
* Experience with at least one object-oriented native mobile language in {Java, Kotlin, Objective-C, Swift} and using tools like Redux, ES6 and Typescript
* Experience contributing to the architecture and design of mobile applications
* Experience building and shipping top-ranking mobile apps to Apple App Store and Google Play
* Clear spoken and written communication in English
* Positive energy and a continuous learner mindset

## Benefits
* Flexible working hours, location and vacations
* A culture of pragmatic, science-driven innovation
* An enormous opportunity to have an impact on the life of thousands of women
* a Vietnamese-French-German team of unique and very talented individuals
* A high salary and responsibilities that will grow along with the company

## Our stack
* React Native, Redux, Redux-Saga, ES6, TypeScript
* Java (Android), Objective-C (iOS), Unity (games), BLE (Device connection)
* AWS, PHP, MySQL, RESTful APIs
* Firebase, Mixpanel, Appium, Jenkins

## Contact
If you are interested, please send me your CV and a few words about your past realizations and wishes for the future at jules@perifit.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
