### ISSUE TITLE
Dinovative-Ruby on Rails Dev-Dist 7-FT

### ISSUE THREAD

**Issue by MpkOanh** [awesome-jobs/vietnam#1998]
## Location

* Saigon, Vietnam

## Salary Expectation

* 1200$/month or range

## Requirements
* 3+ years Software Engineering experience
* Experience with Ruby on Rails or Grape API   
* Experience writing tests with RSpec/MiniTest and doing Continuous Integration is a p
* Experience working with relational database (PostgreSQL)   
* Experience setting up servers (nginx etc.) and automating deployment process (Docker, Ansible, Chef etc.)   
* Basic understanding of front-end technologies, such as JavaScript, HTML5, and CSS3

### Must Have

* Solid understanding of object-oriented programming   
* Strong analytical and problem solving abilities 
* Strong communication and client facing skills 

### Responsibilities

* Design, build, and maintain efficient, reusable, and reliable Ruby code   
* Integration of data storage solutions 
* Help maintain code quality, organization and automatization 
* Constantly learn and keep abreast of emerging technologies   
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Critique software designs and architectures
* Peer review colleagues code and identifying areas for improvement 
* Provide development task effort estimates
* Conduct client requirements gathering and analysis 
* Review test plans  
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control  

### You can bring

Collaborating with UX & UI designers, researchers and other engineers (web & mobile), you will have the ability to flex your full stack chops to help shape, design and build digital products that help solve key business needs

### Why it would be awesome to work with us

* Dynamic, young, friendly, flexible environment  
* Laptop is provided  
* 12+ days Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding  
* Free fruits/ cakes on happy hours time  
* Celebration: birthday  
* Party time: Team building, Xmas, New Year,…  
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws  
* Great opportunity for career development

### Interesting engineering projects
Dinovative is looking for Back-end Software Engineer who is excited to work alongside a talented group of innovators to craft digital products. Being part of the conversation from the start, you will be expected to lead full lifecycle webbased projects including guiding technical scoping, design and implementation. 

### Contact
Facebook Link: https://www.facebook.com/dinovative/ 
Trollman: oanh.my@dinovative.com (0962011059
[[Dinovative] Ruby On Rails Developer JD.pdf](https://github.com/awesome-jobs/vietnam/files/4714775/Dinovative.Ruby.On.Rails.Developer.JD.pdf)
)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
