### ISSUE TITLE
Dinovative - Python junior - Dist 7 - FT

### ISSUE THREAD

**Issue by MpkOanh** [awesome-jobs/vietnam#1999]
## Location

* Saigon, Vietnam

## Salary Expectation

* up to 800$/month or range

## Requirements
* University degree in Computer Science, Engineering or equivalent preferred.
* Minium 1 – 2 years of experience as a Software Engineer or similar role.
* Coding proficiency in at least one modern programming language such as Python (Pandas, NumPy, Scikit-learn), Java, Scala, Ruby
* Experience with non-relational & relational databases (SQL, MySQL, NoSQL, MongoDB
* Experience with cloud-based system Google Cloud Platform, Amazon Web Services: BigQuery, Dataflow, EC2, EMR, Redshift. 
* Kafka, Hadoop, Cassandra, Elasticsearch knowledge is a plus.

### Must Have
* Minium 1 – 2 years of experience as a Software Engineer or similar role.
* Coding proficiency in at least one modern programming language such as Python (Pandas, NumPy, Scikit-learn), Java, Scala, Ruby

### Responsibilities

* Create and maintain optimal data pipeline architecture. 
* Identify, design, and implement internal process improvements: automating manual processes, optimizing data delivery, re-designing infrastructure for greater scalability, etc. 
* Build the infrastructure required for optimal extraction, transformation, and loading of data from a wide variety of data sources using SQL and Google Cloud ‘big data’ technologies.

### Why it would be awesome to work with us
• Dynamic, young, friendly, flexible invironment  
• Laptop is provided  
• 12+ days annual leaves, working Monday - Friday  
• Attractive salary based on skills and experiences  
• Salary review: Once a year, base on individual performance review  
• Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy  
• Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding  
• Celebration: birthday  
• Party time: Team building, Xmas, New Year,…  
• Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws  
• Great opportunity for career development 

### Interesting engineering projects
Dinovative is looking for Python Software Engineer who combines superb technical, communication, and analytical capabilities with a demonstrated ability to get the right things done quickly and effectively. You must be comfortable working with a team of software development engineers to raise the bar of the data pipelines we build and maintain. You should be highly self-directed having good cross-team collaboration skills

### Contact
Facebook Link: https://www.facebook.com/dinovative/ 
Mail: oanh.my@dinovative.com (0962011059
[Dinovative-Python- Software - Engineer-JD.pdf](https://github.com/awesome-jobs/vietnam/files/4714833/Dinovative-Python-.Software.-.Engineer-JD.pdf)
)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
