### ISSUE TITLE
Deliveree-On-demand Logistics - Lead/Senior ReactJS Developer - Saigon - FT

### ISSUE THREAD

**Issue by inspire2017** [awesome-jobs/vietnam#2000]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* Open salary range

## Requirements
* JavaScript
* ReactJD
* Redux
* 3+ years Software Engineering experience

### Must Have

* At least 2 years of experience with building ReactJS web applications for ReactJS position
* At least 5 year of experience with ReactJS for Senior position
* Understanding of how to integrate with RESTful API Backends.
* Significant experience with ES6/7 Features, CSS, and HTML
* Work with React & Redux single-page applications
* Write testable, maintainable, and understandable code
* Experience working with React core APIs
* Deep care for web performance and maintaining quality user-experiences
* Comfortable in a small, intense and high-growth startup environment.

### Ideally

* Startup experience , integrated with Firebase, Google Map API
* Good communication spoken and written English
* Ambition to learn more about UI/UX and design is highly valued.

### Responsibilities

* Develop our Web Applications with ReactJS and integrate with RESTful API backends.
* Interest in and ability to learn new technologies on-the-job.
* Work closely with product managers, designers, and other team members to understand, 
  particulate, and break down customer needs into technical requirements.
* You will ensure that these components and the overall application are robust and easy to 
  maintain. 
* Work closely with Backend teams throughout implementation.

### Why it would be awesome to work with us

* Are you looking to be more than just an ordinary coder? Do you have what it takes to see where you can improve the lives of others through making great mobile and web products to solve issues and improve life? Do you want your products to be used by millions of users in the world and know immediately how much they love your work?

* As the React JS or Senior React, you will build useful and disruptive products, design and develop company applications, and lead and coordinate a ReactJS development team to deliver quality software technologies and systems. You will provide technical input to product teams and stakeholders to help make business and product decisions and be part of creating great technology products. This is a challenging but rewarding opportunity that will increase your experience in a fast moving product startup company. Join us to disrupt the logistic industry with your skills, abilities and passion for technologies.

### Contact

* E-mail: tien.vu@deliveree.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
