### ISSUE TITLE
Stably - Senior Software Developer - Saigon - Fulltime

### ISSUE THREAD

**Issue by Monica-chan** [awesome-jobs/vietnam#2005]
### About us

Stably is a fast growing FinTech company from Seattle founded in April 2018 by a team of former bankers and Amazon software engineers. We have raised close to $3M in funding to date from angel investors as well as leading venture capital firms like 500 Startups, BEENEXT and Pay It Forward. 
Traditional banks and payment providers are slow, expensive, hard-to-access and antiquated. As a result, we are now helping companies build their own digital money through our regulated stablecoin-as-a-service platform. Stably’s solution allows enterprises and their customers to unbank from traditional financial rails, cut down transaction time, lower cost, unlock new revenue channels, access liquidity, enhance brand image and customer loyalty as well as generate new user insights from blockchain data.

### Why work at Stably?

We are changing the landscape of financial accessibility by creating products and infrastructure to empower users. We are democratizing access to financial services that used to be out of reach for many people, creating programmable money that anyone can build on top of, and creating infrastructure that allows money to be more frictionless and borderless.

### How do you know if you're a good fit?

- You enjoy challenges and solving new problems
- You are a lifelong learner and enjoy picking up new skills
- You learn from those around you and help educate others
- You can not only code, but also communicate your ideas clearly
- You have some interest in finance, economics, or trading

### Requirements:

- At least 4 years experience in development across the stack
- Have worked on at least 2 large projects in 2 different team environments
- Proficient in software engineering (processes, design patterns, testing, etc…)
- Familiarity with Golang or other statically typed languages
- Able to teach and transfer skills to junior developers
- Proficient in speaking and writing English

### Nice to have:

- Familiarity with Python, Javascript, or TypeScript
- Experience with ReactJS or other frontend frameworks
- Experience with relational and non-relational databases
- A technical understanding of blockchain
- Familiarity with event driven systems
- Practical cyber security knowledge
- Experience developing and deploying web applications in production
- Experience with DevOps and DevOps infrastructure

## Location

* Thao Dien, District 2, Saigon, Vietnam
* Onsite Fulltime

## Salary Expectation

* $1500 - $2500 Gross/month

## Perks & Benefits:

- Company-provided Macbook Pro for work that you’re allowed to take home with you
- Paid travel for annual business trips to Kuala Lumpur and Hong Kong
- 10 paid vacation days + 5 paid sick days + paid national holidays + WFH days
- Office coffee, juices, snacks, fruits + occasional company lunches/dinners
- US H1B work visa sponsorship after 36 months of employment
- A young, diverse, open-minded, friendly, collaborative and ego-free work environment 
- Being part of a world-leading stablecoin & blockchain company backed by top venture capital investors, including 500 Startups Vietnam

### Contact
Email: careers@stably.io

**Comment by Monica-chan** [comment]
We're hiring more talents to join us.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
