### ISSUE TITLE
Saigon Technology Solutions - SQL Developer - HCM - Fulltime

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2006]
## Location

* Tan Bình, HCM
* Fulltime

## Salary Expectation

* Upto $1800 NET

## Requirements
* SQL Server
* .NET

### Must Have

* Have at least 4 years of experience in MSSQL Server projects
* Skilled at optimizing large complicated SQL statements
* Experience of best practices when dealing with relational databases
* Very good at verbal/non-verbal English, able to work in an international environment
* Good at analyzing & problem-solving skill

### Nice to have

* Have at least 1 year of experience in .NET Web applications
* ASP .NET MVC, .NET Core
* XML, XSD
* Docker / Docker-compose 

### Responsibilities
* Work directly with US client to implement features of the Healthcare System
* Develop, implement and optimize stored procedures and functions using T-SQL
* Analyze existing SQL queries for performance improvements
* Develop procedures and scripts for data migration
* Build appropriate and useful reporting deliverables

### Why it would be awesome to work with us
* 13th-month salary
* Salary review twice a year
* PVI Insurance
* Happy hour every week, technical sharing every month and company trip every year.
* More details will be shared during the interview

### Contact
Email: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
