### ISSUE TITLE
Tech Outpost - Senior Ruby Developer - Saigon - FT

### ISSUE THREAD

**Issue by RobDoan** [awesome-jobs/vietnam#201]
A website is not just a mash up of graphics and words, it is the gateway to your business and it tells your story, brand and vision. First impressions matter, and we believe in making it count. At Tech Outpost, we don’t just build websites, we create memorable experiences that communicates the essence of your brand.

We’re a team of dreamers, storytellers and brainiacs, coming together to help you change the world.
## Location
- Saigon, Vietnam
- FullTime
## Salary Expectation
- negotiable
## Requirements
- Education: College or Bachelor of IT-Software or equivalent
- Strong insight into Ruby and Rails and their nuances
- Solid understanding of object-oriented programming
- Able to write unit, functional, and integration tests for rails applications
- Hand on experience with PostgreSQL / Mysql
- English: Intermediate level or above
### Ideally
- Have several years experience developing web applications
- Have experience building products with Ruby, and operating them in production
- Understand and practice some form of TDD / BDD
- Javascript experience
- Use their experience and the problems at hand to become a better developer, feeding that back into their work
### Responsibilities
- Design, build, and maintain efficient, reusable, and reliable Ruby code
- Ensure the best possible performance, quality, and responsiveness of the applications
- Identify bottlenecks and bugs, and devise solutions to these problems
- Strive to continually improve technical and developmental skills
### Contact

Quy Doan: quy.doan@techoutpost.co (0908217594)

**Comment by joneslee85** [comment]
Thanks for the submission

Please amend this job post to comply with our guideline:

- Job Post title

Besides, can you please describe what your company is on?

Thanks

**Comment by joneslee85** [comment]
@RobDoan So it is Senior Ruby Dev? If so, please update the title to Senior Ruby Developer
