### ISSUE TITLE
Scommerce - Senior Golang Developer - HCMC - FT

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#2011]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1200-2000$/month

## Requirements
* 4+ years of experience as a Software Developer
* 1 year of experience Golang
* Good knowledge of OOP, Design Pattern, Data Structure, Algorithm
* Knowledge with Python, OpenERP is a plus
* Familiar with RESTful API
* Experience with SQL, NoSQL, Caching
* Experience with messaging system such as ActiveMQ, Rabbit, Apache Kafka, etc.
* Experience with Docker, Kubernetes
* Experience with  Front End technologies (HTML, CSS, JS)
* Self-motivated to explore new technologies and environments
## Skills
Golang
### Must Have
* At least 1 year of experience Golang

### Why You'll Love Working Here

* Fair team
* Macbook 
* Annual health check-ups.
* Sports club: Running, football, badminton
* Open communication with Senior Engineer & Technical Leader
* Challenging working environment with attractive domain as Logistics
* Specific pantry with nice decoration & Coffee/Milk Coffee/Chocolate & Tea
* Annual Team-building + Outing trip
* Join Training Courses and Tech Sharing
* Mid-Autumn Party, Christmas party, Year-end Party
* With the delivery network cover more than 98% geographical area of Vietnam, you will be welcome anywhere in Vietnam for traveling
* Competitive salary and 13th-month pay.

### Contact
Dong (Mr.)
Email dongdd@scommerce.asia
Skype https://join.skype.com/invite/Ii3KnTLNg4Rk
Telegram: https://t.me/DongDoD

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
