### ISSUE TITLE
Saigon Technology Solutions - Fullstack NodeJS/ReactJS (MERN Stack) - HCM - Fulltime

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2016]
## Location

* 2 Nguyen The Loc, Ward 12, Tan Binh District, HCMC, Vietnam
* Fulltime

## Salary Expectation

* Upto 1800 USD NET

### **Must Have**
* Have at least 3 years of experience in web development
* Have at least 2 years of experience in **NodeJS** and **ReactJS** projects
* **ExpressJS**, Restful API, Microservices
* Experience in **MongoDB** and one of the relational databases MySQL, Postgresql
* Dependency Injection and inversion of control (in SOLID)
* Architecture, algorithm knowledge
* Very good at verbal/non-verbal **English**, able to work in an international environment
* Good at analyzing & problem-solving skill

### Nice to have
* Docker
* GraphQL
* AWS, Serverless

### Responsibilities
* Work directly with US client to implement features of systems
* Assist with application architecture design and implementation.
* Develop API and UI Elements
* Adhere to and recommend improvements to project coding standards.
* Work in a team environment with shared code; disciplined use of source code control and process documentation.
* Solve technical problems

### Why it would be awesome to work with us
* Salary review twice a year
* Full of insurance packets
* PVI Insurance
* Happy hour every week, Birthday party every month, company trip every year
* Lovely pantry with full of snacks, noodles, etc.

### Contact
**Homepage**: https://saigontechnology.com/
**Email**: kien.tran@saigontechnology.com
**Phone**: 0398993171 (Skype, Zalo, Whatsapp, Telegram)
[You can also read the JD on the Facebook Page](https://www.facebook.com/job_opening/1346320625559392)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
