### ISSUE TITLE
Parcel Perform - Senior Back-end Engineer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#2017]
![image001](https://user-images.githubusercontent.com/49466111/59088978-38281880-8933-11e9-95f8-2bace44d6968.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $2,000 - 3,000

## Requirements
* Be responsible with task and be open to discuss, give questions to build up products with high
quality and rich front-end experiences for our users.
* Understand clearly about object-oriented programming and design pattern.
* Willing to learn and research new technology or jump out of your comfort zone.
* Passionate about quality and the design of the code, productivity of the work and maintainability of the end result.
* An inspirational team player to successfully deliver team outcome.

## Skills
* At least 3 years, solid experience working with Python (2.7 and 3).
* Strong knowledge of scaling practices such as in-memory databases, load balancing, caching, etc.
* Comfortable with both SQL and NoSQL databases
* Worked on at least one project using a MQ as a communication hub. If you start one today, that still counts.
* Fluent in RESTful and real-time communication protocols.
* Familiar with AWS stack to get the most out of infrastructure.
* Eager to get involved in data engineering process
* Wide exposure to multiple technology stacks is an advantage, we love full stack guys (and girls!).

### Must Have
* Experience in Python

### Responsibilities

As a senior backend engineer, you will be building scalable systems with microservices. You will get to write code bases that are small and focused on doing one thing well. We choose microservices for technology freedom, resilience, and scalability, though there will be a lot of communication between services (does MQ ring any bell?), much automation and tons of metrics we need to keep an eye on. Such system isn’t easy, especially with a focus on good engineering practices. But that is ok. We aren’t here for ease anyway. We are here for people who want to operate at the next level in their career.

### Why it would be awesome to work with us
* The opportunity to work in a fast-growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing, and focuses on succeeding - we
continuously work with you on your strengths and weaknesses across many important
dimensions, and look at ways for you to address them and further your development
* Your entry ticket into being part of the Parcel Perform startup Universe, where you will work with and alongside people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast-growing company like competitive salary, extra insurance, free lunch, free fruit, snacks, cool oﬃce, team bonding events, various training programs, and more.

### Interesting engineering projects
You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide.

### Contact
Please drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)
For further information about our company: https://www.parcelperform.com/

![Email Banner - Notification Score (13Apr)](https://user-images.githubusercontent.com/49466111/85096191-db399080-b21d-11ea-9b17-c8b5eaaf5a0e.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
