### ISSUE TITLE
OnPoint - Senior/Junior FullStack (Elixir) - Saigon - FT

### ISSUE THREAD

**Issue by duyleop** [awesome-jobs/vietnam#2018]
## Location

* Saigon
* District 1

## Salary Expectation

* Senior up to 2900$/month
* Junior up to 1500$/month

## Requirements
* Bachelor’s degree in computer science, information systems or a related field.
* Having 1 - 3+ years of experience in web development.
* Experience with multiple programming languages(Elixir, Python, Ruby, or Go).
* Experience with Redis, Elasticsearch has knowledge about Caching is a plus.
* Experience with web API technologies: RESTful, Authentication, Authorization, and multi-devices session.
* Experience with Postgresql other (Mysql, NoSQL) is a plus.
* Experience with version control (Git)
* Experience with frontend work: HTML/CSS, bootstrap, SASS, ReactJS, etc
* Good knowledge of eCommerce, Saas, etc.
* Knowledge of Integrations with various Third-party CRM.
* Ability to quickly master new technologies and push the envelope for performance and reliability.
* Experience with agile development processes and frequent release cycles.
* Great interest in eCommerce.

### Responsibilities

* Work closely with the Technical Manager, Product Manager, and Product Designer to build a next-generation web application.
* Design and develop new features for the platform/system.
* Evaluate and clarify product requirements. Participate in reviewing product design.
* Maintain quality standards of excellence and ensure compliance with standards and best practices.
* Mentor junior team members.
* Build efficient and reusable code and systems.
* Identify and address performance bottlenecks.
* Participate in architecture design and code reviews.
* Communicate with other team members to determine the best solutions to difficult problems.
* Passion for performance debugging and benchmarking.

### Why it would be awesome to work with us

Onpoint is the largest E-commerce enabler in Vietnam, providing end-to-end services, helping brands to accelerate and become more successful online in Vietnam and SEA region. Onpoint's mission is to make E-commerce easy for brands, to create sustainable values for businesses, consumers, and partners.

It's a privilege for us to serve top tier clients. Our integrated capabilities encompass all aspects of the E-commerce value chain covering store commercial and operations, digital marketing, customer services, warehousing, and fulfillment. We help brands execute their E-com strategies by selling their goods directly to customers online or by providing services to assist with their E-com operations. Our business ranges from the largest online shopping platforms as well as social shopping channels.

Since day one, we have dedicated ourselves to the needs of our brand partners. We work closely to ensure our direction and thought processes are tightly aligned with their needs
Join us, make a difference, and create value for life!

### Contact
Homepage: https://www.onpoint.vn/
Send CV to duy.le@onpoint.vn

**Comment by duyleop** [comment]
@qcam ơi help mình update lại tag là Elixir nhé! Thanks!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
