### ISSUE TITLE
Grab VN - Senior Backend Engineer (Golang) - HCMC - FT

### ISSUE THREAD

**Issue by hongngocanhthu** [awesome-jobs/vietnam#2020]
## Location

* Dist 7, Saigon, Vietnam
* Fulltime

## Get to know the role
* Learn and influence the fundamentals of engineering at Grab
* Relentless focus on delivering high-quality, maintainable and bug-free code at scale
* Discuss and debate with other team members to find optimal solutions
* Monitor systems to make sure there is no disruption in our services

## The day-to-day activities
* Design and write cutting-edge backend services for Grab's range of products that serve millions of users
* Conceive, analyze, design, build and maintain large-scale systems, ensuring system is robust, highly optimized for performance, highly scalable, highly available.
* Work with your team to explore and create new designs geared towards scale and performance
* Participate in code and design reviews to maintain our high development standards
* Work with product managers, data analysts and UI designers to implement products and test their impact to business metrics
* Engage in service capacity and demand planning, software performance analysis, tuning and optimization
* Collaborate with product and experience teams to define and prototype features
* Work closely with infrastructure team in building and scaling back-end services as well as performing root-cause analysis investigations
* Conduct performance tuning and optimization
* Debug and modify complex, production software

### Must Have

* 3-7 years backend experience
* Strong computer science fundamentals in algorithms and data structures
* Familiarity with running large scale microservices services
* Strong understanding of system performance and scaling
* Excellent communication skills, sharp analytical abilities with proven design skills, ability to think critically system growth and stability
* Familiarity with AWS
* Experience in writing good unit tests
* Conversational English

### Nice to have

* Work experience in Java or Go (strongly preferred)
* A degree in Computer Science, Software Engineering or related fields
* Understanding of distributed systems and network protocols
* Familiar with Cloud service providers: AWS, Azure.
* Elastic Search, MySQL, Cassandra, DynamoDB, Kafka, Redis, Terraform, Docker, Gitlab, Jenkins, LUA 

### Positive & Collaborative environment
Grabbers thrive in a corporate culture that values every team member's contribution towards our goal of improving lives.

### Rocket fuel for careers
Grabbers experience hyper professional growth and all the challenges that entails. Grow your skills while working to solve real issues across the region.

### Fun & dedicated family
Grabbers work hard and play hard. Our teams grow as one as they overcome challenges and have fun along the way.

### Some of benefits are:
* Macbook is provided.
* Extra Medical Insurance.
* 14 days annual leaves, working Monday - Friday.
* Free drive with Grab (budget follow your level)

### Contact
Ms. Hong Ngoc Anh Thu - Talent Acquisition Business Partner (Engineering)
Email: thu.hong@grabtaxi.com
Jobs opening: https://grab.careers/jobs/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
