### ISSUE TITLE
Viettel Cyber Security - Senior Web Developer (Python - Go) - FT - HN

### ISSUE THREAD

**Issue by phuckhang123** [awesome-jobs/vietnam#2022]
## Location

* Ha Noi, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

### Requirements
* Minimum 4 years for solution development experience, 2 years for Web
* Good Python / Go programming
* Proficiency in using Linux.
* Have participated in at least 1 major project with the role of tech lead / PM/system designer
* There is a high sense of responsibility at work, positive, proactive, enthusiastic at work.

#### Should Have
- Experience using Docker, UnitTest, CI flow in service development (DevOps) in projects running production
- Experience in web development using Python, Flask, Django, Angular, NodeJS
- Experience using ELK Stack, Redis, Kafka
- Participate in developing Security / Network projects or experience using Cloud security solutions (AWS, Azure, GCP ...)

### Responsibilities
* Analyze requirements, design, develop large and complex websites, meet hundreds of thousands of users.
* Participate in research and development of new features, solutions, and technologies to provide Security services on the Cloud platform
* Improving, optimizing features, business flow, user experience about Security services

### Why it would be awesome to work with us
* Attractive salary
* Young and dynamic working environment: football club, table tennis, billiard, painting, e-sport, jogging, cycling, ...
* There is an additional insurance policy at Central Military Hospital 108 and a special treatment area for Viettel employees and relatives.
* Having the opportunity to work with leading experts, long experience in the security industry (top 100 hacker Facebook, Microsoft, ...)
* Have the opportunity to participate in ATTT conferences in the country and in the world (Singapore, USA, Spain, ...)
* Participating in extracurricular, sports and cultural activities of the Company
* Flexible working time, comfortable clothes. Quarterly team-building events, 12 days of annual leave & 3 days of vacation with the support of 9 million VND / person

### Interesting engineering projects

Viettel network security company is a unit of the Military Telecommunications Industry Group, performing in-depth research on security and programming to develop security solutions for systems and providing products/services to our customers outside

### Contact
Kindly send CV via mail: phuckhang.ttran@gmail.com
Subject: [Viettel - Position - Your name]

**Comment by qcam** [comment]
Hi, thanks for posting. May I know if you could use the work email from Viettel? Please note that we do not accept posts from agency at the moment. Thanks.
