### ISSUE TITLE
Senior Backend Engineer, Automation License Plate Recognition

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#2024]
## AXON

* 8th Floor, E.Town Central Building, 11 Doan Van Bo St, Ward 12, Dist 4, Ho Chi Minh City

## Salary Expectation
* **Negotiable**

## Great power comes with great responsibilities!
You'll be responsible for:
* Maintain and deploy existing Return Asset Merchandise Assets product written in Scala.
* Implement new features for Automation License Plate Recognition cloud system.
* Work with engineers on a breadth of platforms including in-car, mobile and desktop systems as well backend services.
* Consider scale and security implications of new features that you develop.
* Create metrics and monitor them as your features are deployed to customers.

## Ideally, you should meet most of these requirements:
* You have 6+ years of experience coding and shipping and supporting high quality products.
* You have owned the design and implementation of software backend components.
* You have shipped production features in either languages: **Golang, C/C++, Scala, C#, or Java**.
* You have utilized performance analysis tools and incoming telemetry to improve services.
* You are self-motivated team member and positively engage to productively work out the best architectural choices for the team's areas.
* Excellence in English skills.

## Why it would be awesome to work with us
* Competitive salary and benefits including a great medical insurance plan
* An awesome office/working environment with the latest technologies and work with top engineers in the world
* Fun team activities and outings
* Opportunities for training in the US
* Opportunities to ride along with real US police officers in real life situations, see them use technology, and get inspired
* Flexible working hours
* Mon - Fri

## Contact
* Apply now: **https://topdev.vn/s/IBuxPAhA**
* Email: **huykhanh.tran3108@gmail.com**

**Comment by qcam** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
