### ISSUE TITLE
VieON - R&D Engineer - HCM City - FT

### ISSUE THREAD

**Issue by ducminhgd** [awesome-jobs/vietnam#2025]
## Location

222, Pasteur, Ward 6, District 3, Hồ Chí Minh City, Vietnam

## Salary Expectation

* 20 - 25 Million/month
* Negotiable

## Requirements

* Knowledge about several programming languages is a plus, ideally Go, Python, JS.
* Having knowledge about Cloud platform, such as AWS, GCP, or OpenStack.
* Having knowledge about Database: MySQL, PostgreSQL, MongoDB
* Caching: memcache, redis,...
* Others: Elasticsearch, Git, A/B Testing

## Skills

* English.
* Team working.
* Working independently.
* Can work in high pressure environment.
* Problem solving

### Ideally

* Experienced with OTT, Streaming, VOD, SVOD, AVOD.
* Having knowledge about TDD, CI/CD, Microservices

### Responsibilities

* Research, develop, share and consult solutions for other teams.
* Support other teams to apply new solutions.

### Why it would be awesome to work with us

* We are the biggest group of Media in Vietnam.
* We are archiving to be a world-class video streaming platform and to be a Unicorn.
* _Group has a large number of beautiful ladies and gentlemen, also celebrities to refresh your eyes and your mind_

### Interesting engineering projects

Vieon.vn

### Contact

HRBP Manager: oanh.le.hoang@datvietvac.vn
R&D Manager: minh.gia@dzones.vn

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
