### ISSUE TITLE
[LINAGORA] Senior PHP Architect - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2029]
## Location

* Viettower, No. 1 Thai Ha Str., Vietnam
* Full-time

## Salary Expectation

* Up to $2000

### Ideally

* 3+ Experience as a PHP Developer and wish to invest in an R&D team in an Open Source environment.
* Experience in the design of complex software architectures.
* Experience in using technologies from the PHP ecosystem.
* Experience on develop and deploy the WordPress, Moodle, working with Ngnix and develop the REST API base on the PHP server
* Basic knowledge about deployment web system on to production
* Master the Git version management system. You have notions in HTML5, CSS3.
* Knowledge of Docker, GitLab, GitLab-CI, Jenkins, CyPress.io, WebPack is a plus.
* Integrated into international teams, good practice of professional English is required.

### You’ll be responsible for

* Work in Agile mode (Scrum), and use the best practices of application development: code review, continuous integration, pair programming ... in a full Open Source environment.
* Be in charge of the development of motor of the calendar and contact in the development of collaborative messaging of the platform.
* Add functionality, refactor, transfer bugs and features to the Saber community, as well as develop and maintain automatic integration tests based on the OpenSource SabreDAV server.
* Invoke to development project of company relative to PHP technologies, working as developer, architect and deployment to have fully life-cycle of product development.
* Be an integral part of the process of developing the implementation of the functionalities.
* Contribute to the development of skills of our junior developers.
* Know how to get high, and you know how to integrate a specific job into a global functionality.

### Why it would be awesome to work with us?

* Work in an international team with high skilled people and for international projects
* Opportunity to be promoted to senior/management position in company that is having a huge growth in Hanoi
* Correct work/life balance
* Working 5 days/week , from Monday to Friday
* Competitive salary, lunch allowance, 13th month salary
* Annual health checkups and other benefits based on labor law
* Annual company trip & exciting activities for team building
* Participate to Open Source communities and tech conferences in Vietnam
* Modern working space, free coffee.

### Contact

Homepage: linagora.vn
If you are interested in this opportunity, please kindly send your CV to the email address: **vnhr@linagora.com**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
