### ISSUE TITLE
[LINAGORA] Android Developer - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2030]
## Location

* Viettower, No. 1 Thai Ha Str., Hanoi

## Salary Expectation

* Negotiable

### Ideally

* Bachelor’s degree in information technology, or related field
* 2-3  years of experience

## Required Knowledge, Skills, and Abilities: 

* App design
* Backend web services knowledge
* Unit tests, automation, and code reviews
* Willingness to learn new technology
* Strong OO design and programming skills in Java or Kotlin, APIs
* Familiar with the Android SDK
* Complex solving problem
* Fluency in English

### Responsibilities

You’ll develop from scratch the Android mobile application of the OpenPaaS (https://open-paas.org/) platform. We target two first mobile applications :
* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices
* a Chat application, linked to the OpenPaaS Chat web module, to allow people to keep chating on their mobiles

You are passionate, motivated in the Open Source projects. Beside coding, it’s important that you learn our business and help to align technology innovation with our customer needs.

Other responsibilities:
* Participate in product design, offer new ideas
* Collaborate with product and business teams to define our product that are suitable for the market
* Design and implement a mobile application for Android using Java or Kotlin
* Work in team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our teams maintain high standards
* Support international teams in developing products to meet the clients’ requirements
* Keep up to date on the latest industry trends in the mobile technologies

### Why it would be awesome to work with us?

* Work in an international team with high skilled people and for international projects
* Opportunity to be promoted to senior/management position in company that is having a huge growth in Hanoi
* Correct work/life balance
* Working 5 days/week , from Monday to Friday
* Competitive salary, lunch allowance, 13th month salary
* Annual health checkups and other benefits based on labor law
* Annual company trip & exciting activities for team building
* Participate to Open Source communities and tech conferences in Vietnam
* Modern working space, free coffee.

### Contact
Homepage: linagora.vn
If you are interested in this opportunity, please kindly send your CV to the email address: vnhr@linagora.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
