### ISSUE TITLE
[LINAGORA] DevOps Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2031]
## Location

* Viettower, No. 1 Thai Ha Str., Hanoi
* Full-time

## Salary Expectation

* Up to $2000

### Ideally

* Background in Computer Science / Information Technology or equivalent.
* Knowledge of CI/CD and IT security concepts
* Knowledge of Sourcecode Mangement Systems: Gitlab, Github, Bitbucket
* Knowledge and experience of Kubernetes (k8s), Docker
* Knowledge of Provisioning and Configuration Management tools such as Ansible, Terraform, Puppet is a plus
* Good level of English

### You’ll be responsible for

As a DevOps Engineer, the incumbent will report to DevOps Team Leader and cover the following
main duties and responsibilities:
* Implement and improve monitoring and alerting
* Build and maintain highly available systems on Kubernetes
* Implement and manage CI/CD pipelines
* Implement an auto-scaling system for our Kubernetes nodes
* Participate in on-call rotations

### Why it would be awesome to work with us?

* Work in an international team with high skilled people and for international projects
* Correct work/life balance
* Working 5 days/week , from Monday to Friday
* Competitive salary, lunch allowance, 13th month salary
* Annual health checkups and other benefits based on labor law
* Annual company trip & exciting activities for team building
* Participate to Open Source communities and tech conferences in Vietnam
* Modern working space, free coffee.

### Contact

Homepage: linagora.vn
If you are interested in this opportunity, please kindly send your CV to the email address: vnhr@linagora.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
