### ISSUE TITLE
[LINAGORA] Software Engineer (OSSA Team) - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2032]
## Location

* Viettower, No. 1 Thai Ha Str., Hanoi

## Salary Expectation

* Negotiable

### Ideally

* Knowledge about Linux environments (Debian / CentOS / RHEL / Suse) and basic network and System Administration skills.
* Fluent French (written and spoken)
* General knowledge in Open source
* Agile Management knowledge

### You’ll be responsible for

Job overview: The daily duties of an OSSA team Member are very close to those of an R&D software engineer:
* Qualification of customers’ user stories,
* Grooming to develop the best technical answers to our customers,
* Permanent experience sharing with clients’ ops teams
* Development
* Documentation and contribution to the original Open Source community

Responsibilities and Duties:

* Receive e-mails, faxes, telephone calls from customers
* Perform the filtering of requests and the classification of incidents
* Record them in the technical database of the support platform;

### Why it would be awesome to work with us

* Opportunity to become the next Service Manager in Vietnam
* Work in an international team with high skilled people
* Correct work/life balance
* Working 5 days/week , from Monday to Friday
* Participate to Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact
Homepage: linagora.vn
If you are interested in this opportunity, please kindly send your CV to the email address: vnhr@linagora.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
