### ISSUE TITLE
Dinovative - Python Developer (middle level) - Dist 7 - FT

### ISSUE THREAD

**Issue by MpkOanh** [awesome-jobs/vietnam#2034]
## Location

* District 7, HCMC, Vietnam

## Salary Expectation

* 700-1100$ (gross)

## Requirements
* University degree in Computer Science, Engineering or equivalent preferred.
* Minimum 1 - 2 years of experience as a Software Engineer or similar role.
* Coding proficiency in at least one modern programming language such as Python (Pandas, NumPy, Scikit-learn), Java, Scala, Ruby.
* Experience with non-relational & relational databases (SQL, MySQL, NoSQL, MongoDB).
* Experience with cloud-based system Google Cloud Platform, Amazon Web Services: BigQuery, Dataflow, EC2, EMR, Redshift.
* Kafka, Hadoop, Cassandra, Elasticsearch knowledge is a plus.

### Responsibilities
* Create and maintain optimal data pipeline architecture.
* Identify, design, and implement internal process improvements: automating manual processes, optimizing data delivery, re-designing infrastructure for greater scalability, etc.
* Build the infrastructure required for optimal extraction, transformation, and loading of data from a wide variety of data sources using SQL and Google Cloud ‘big data’ technologies.

### Why it would be awesome to work with us
Come and work with us. You will have opportunity to learn new technologies with international
standard, build products that are different/innovative and get various benefits:
* Dynamic, young, friendly, flexible environment
* Laptop is provided
* 12+ days annual leaves, working Monday - Friday
* Attractive salary based on skills and experiences
* Salary review: Once a year, base on individual performance review
* Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding
* Celebration: birthday
* Party time: Team building, Xmas, New Year,…
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development

### Interesting engineering projects
Dinovative is looking for Python Software Engineer who combines superb technical, communication, and analytical capabilities with a demonstrated ability to get the right things done quickly and effectively. You must be comfortable working with a team of software development engineers to raise the bar of the data pipelines we build and maintain. You should be highly self-directed having good cross-team collaboration skills.
The ideal candidate for our team is a thinker and a doer: someone who loves sophisticated algorithms and mathematical precision, but at the same time enjoys implementing real systems, and is motivated by the prospect of spectacular business returns.

### Contact
Fanpage: https://www.facebook.com/dinovative/
Mail: oanh.my@dinovative.com 
[[Dinovative] Python developer JD.pdf](https://github.com/awesome-jobs/vietnam/files/4856833/Dinovative.Python.developer.JD.pdf)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
