### ISSUE TITLE
Resola - Full-Stack Developer - Remote or Japan - C

### ISSUE THREAD

**Issue by evert0n** [awesome-jobs/vietnam#2035]
## Location

* Remote
* Shibuya, Tokyo / Japan

## Salary Expectation

* $1500USD ~ $3000USD month

# Job brief

- We are looking for a Full-Stack Developer to produce well design and scalable software solutions
- You'll be part of a cross-function team that's responsible for the full software development life cycle, from conception to deployment
- As a Full-Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries 
- You should also be a team player

### Responsibilities

- Collaborate with the rest of the engineering and product team to design and launch new features
- Contribute to the entire app lifecycle
- Design client-side and server-side architecture
- Develop and manage well-functioning applications and databases
- Write effective APIs
- Writing clean, functional code on the front- and back-end
- Write well tested software to ensure quality, responsiveness and efficiency
- Write technical documentation
- Troubleshooting issues and problem solving as necessary

### Requirements

- Proven experience as a Full-Stack Developer or similar role
- Experience developing web and mobile applications
- Familiarity with common stacks
- Knowledge of multiple front-end languages and libraries (e.g. HTML/ CSS, JavaScript)
- Knowledge of multiple back-end languages (e.g. Python, Go, NodeJS)
- Knowledge of multiple frameworks (e.g. React, Django)
- Familiarity with databases (e.g. MySQL, MongoDB)
- Familiarity with development tools (e.g. Git, Docker)
- Excellent communication and teamwork skills
- Great attention to detail
- Organizational skills

### Benefits and Perks

- Remote friendly
- Visa sponsorship - Come work with us in Japan

### Contact

Apply with Angel.co https://angel.co/l/2sYJNu

**Comment by ngankilo** [comment]
Can I apply?

**Comment by muhamedRadwan** [comment]
I applied and hope to be shortlisted :)

**Comment by muhamedRadwan** [comment]
Okay I just shortlisted, now I hope to be hired soon  😂😂😂❤

**Comment by evert0n** [comment]
Thank you all we have filled all 5 positions for this! ❤️
