### ISSUE TITLE
SPARK X LAB - Senior Ruby developer - Saigon - FT 

### ISSUE THREAD

**Issue by hiroki-tkg** [awesome-jobs/vietnam#204]
![SPARK X LAB](https://camo.githubusercontent.com/e4cffbc3b96c16599e70ab2272ad7e07d4ad8cb3/687474703a2f2f737061726b786c61622e636f6d2f696d616765732f66625f6f67702e706e67)
## Location

224A-224B Dien Bien Phu Street, Ward 7, District 3, Ho Chi Minh City, Vietnam.
## Salary Expectation
- $800 - $1500+ / month 
  (Negotiable)
## Requirements
- Experience with Ruby, Rails and JavaScript in Linux/Unix environment.
- Knowledge of RESTful routing and proper MVC architecture
- Experience dealing with 3rd-party APIs
- Database design, performance tuning and optimization. (MySQL/PostgreSQL)
#### Bonus points if you have:
- Familiar with IaaS, PaaS (like AWS, GCP, Heroku, GAE)
- Experience with developing API for mobile apps.
- Experience with modern web development (Agile, Immutable Infrastructure, TDD, ChatOps, CI, etc.)
- Communication skills in English
## Benefits
- Chances to build a great product and become key founders of the team
- Chances to work with latest technologies and tools
- Improvement in English communication and international communication standard
- Chances to create business and service from scratch
- Chances to work with well experienced entrepreneurs
## Contact

[info@sparkxlab.com](mailto:info@sparkxlab.com)  
[http://sparkxlab.com/#page-recruit](http://sparkxlab.com/#page-recruit)

**Comment by joneslee85** [comment]
Please fix up the header format of `Bonus point` and `Benefits`

**Comment by joneslee85** [comment]
The post has not been amended for the last 2 days. Feel free to re-open this after making amendment

**Comment by hiroki-tkg** [comment]
@joneslee85 I just amended it now. Thank you.
