### ISSUE TITLE
Trobz - Odoo/ERP developers - HCM, Vietnam - FT

### ISSUE THREAD

**Issue by ddkv1988** [awesome-jobs/vietnam#2044]
## About Trobz
Being the leading Odoo solutions provider in Vietnam, founded since 2009, Trobz currently operates globally from Vietnam with projects comes from many countries (Southeast Asia, Europe, Australia…). Now, Trobz is currently looking for a Software Developer. The successful candidate will work in a dynamic, professional and multicultural environment that allows excelling personal development through teamwork, individual performance and training.
The successful candidates will work in a dynamic, professional and multicultural environment, that allow to excel personal development through teamwork, individual performance and trainings.

## Location
* Saigon, Vietnam
* Fulltime

## Requirements
Knowledge of web technologies and object oriented programming
Knowledge of modern development methodologies and tools (agile methodologies, automated testing, continuous integration, distributed version control systems, wikis, trac, jira,…)

## Skills

**Nice to have**
Experience in software development, open-source projects, development tools (Eclipse, Versioning tools, Bug tracking tools) is a plus
Knowledge of Python and/or Odoo (formerly, OpenERP) is a plus (Odoo will be trained for all newcomers)
Understanding of the processes of a company (sales, purchases, stock management, accounting, human resources,…) is a plus
Skills on Mobile, E-commerce, devops, sysadmin, data migration, odoo upgrade…is a plus

### Responsibilities
Understand the requirements provided by the business analysts
Code following the coding guidelines and best practices
Ensure the correctness of the implementation before transmitting to the QC team

### Why it would be awesome to work with us
Competitive salary
Multicultural, supportive and friendly working environment
Diverse types of subsidies & bonus
English course / Bonus
Reference bonus
13-month salary
Extra insurance
Knowledge sharing and happy hour every Friday
Quarterly, yearly bonding activities with company

### Contact
Homepage: https://trobz.com/jobs/detail/odoo-erp-developers-2
Trollman: job@trobz.com (Tel: +84 28 62 737 605)
![Recruitment Dev (2)](https://user-images.githubusercontent.com/67954868/86768242-71234700-c077-11ea-8efb-98d4f4e82aca.jpg)

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
