### ISSUE TITLE
Pixcap - Frontend Lead - Remote - FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2047]
## Location

* Remote

## Salary Expectation

* $5000/month 

## Requirements
* JavaScript skills with knowledge and experience of any reactive framework (React, Angular,
Vue)
* Demonstrated ability with coding web applications at scale
* Extensive experience with html5, css, canvas, and svg
* Experience with ES6, typescript, webpack and transpilers like babel
* Understanding of different browser requirements for responsive web design
* Experience with a Javascript WebGL library, e.g. BabylonJs or ThreeJs
* Proficiency in spoken and written English

### Must Have

* R & D ability
* 3D human motion or deep learning for computer vision and human pose estimation

### Ideally

* Github repositories, with more than 100 stars
* Contributed to open-source projects
* Have led a frontend team
* 3+ years work experience in front-end or full-stack engineering of web applications
* General knowledge of 3D animation or experience using 3D animation tools (e.g. Maya,
Blender, Unity, etc)

### You’ll be responsible for

*  Implement GUI for managing application data to and from the 3D animation engine
*  Create wireframes and contribute to the UI/UX of the 3D animation product
*  Responsive web design
*  Build reusable code as libraries for future use
*  Optimize application for speed and scalability
*  Write reliable and automatic tests to incorporate into the deployment pipelines for stable and
reliable releases

### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
