### ISSUE TITLE
Pixcap - 3D Graphic Engineer - Remote - FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2048]
## Location

* Remote

## Salary Expectation

* $5000/month 

## Requirements
*  Demonstrated ability to implement a 3D animation software application, such as animation
curves, rigging and retargeting
*  Solid grasp of 3D mathematics, geometry and basic linear algebra
*  Experience with graphics pipelines e.g. Maya, Unity, Unreal Engine
*  Familiarity with scripting on 3D graphic platforms e.g. Blender python, Maya Embedded
Language Web development experience
*  Familiarity with Python or C/C++ for rapid algorithm prototyping
* Proficiency in spoken and written English

### Must Have
* Strong background in Javascript and WebGL frameworks (Babylon.js, three.js)
* 3+ years work experience in front-end or full-stack engineering of web applications
### Ideally
* Publication in computer graphics journals (e.g. SIGGRAPH)
* 5+ years of 3D web graphics development
*  Experience with shaders (GLSL/HLSL)
*  Experience with WebAssembly
*  Experience rigging and animating 3D characters
*  Experience working with Maya/Blender/Unity APIs

### You’ll be responsible for

* Design and architect 3D web software for character and general animation
* Develop features such as animation curves, auto-rigging, mesh morphing, retargeting and IK
in Javascript or Python

### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
