### ISSUE TITLE
Pixcap - 3D Computer Vision Engineer -  Remote - FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2049]
## Location

* Remote

## Salary Expectation

* $5000/month 

## Requirements
*  Experience with OpenPose or related 3D pose estimation algorithms
*  Solid grasp of 3D geometry and linear algebra
*  Experience with architecting a supervised/semi-supervised machine learning pipeline for
training
*  Proficiency in spoken and written English

### Must Have
* 4 years+ of industry or research experience
* Strong knowledge and familiarity with deep learning libraries including Pytorch and
Tensorflow
* In-depth understanding of OpenCV and 3D libraries e.g. PCL, Open3D
* Strong Python and C++ programming skills
### Ideally
* Publication in computer graphics journals (e.g. SIGGRAPH)
* 5+ years of 3D web graphics development
*  Experience with shaders (GLSL/HLSL)
*  Experience with WebAssembly
*  Experience rigging and animating 3D characters
*  Experience working with Maya/Blender/Unity APIs

### You’ll be responsible for

* Develop computer vision, visual geometry and deep learning algorithms for monocular 3D
human pose estimation.
*  Typical algorithms used include Object Detection, top-down or bottom-up 2D/3D Keypoint  Detection, SMPL parameterization and sequential networks used for video motion capture.
*  You will help solidify existing algorithms, and work with large amounts of real and synthetic
data to continuously improve the algorithmic and computational performance
vResearch and implement state-of-the-art papers for training and inference
### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
