### ISSUE TITLE
BBV Vietnam - Solution Architect .Net - Saigon - FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2050]
## Location

* Saigon

## Salary Expectation

* vnd 60 million/month(Net) 

## Requirements
* Bachelor's degree or equivalent with focus on computer science, information technology,
systems development or a related field.
* Experience with non-functional aspects, i.e. security, performance, and scalability.
* Have CI/CD experience with TFS/VSTS, Bamboo, GitLab, Bitbucket or similar tools.
* Can advise project teams on the use of static code analysis tools and configure the tools.
* Can provide technical leadership in complex projects and guide a team of 10 developers.
* Fluent in spoken and written English.
* Able to adjust your working time according to the project schedule.
### Must Have
* Have at least 7 years of experience in analysis, design, and development of .NET software
solutions.
* Strong understanding and experience of common software design patterns.
*  In-depth development experience with clean code, coding standards, and code review.
*  In-depth development experience with unit tests, mocking libraries, code coverage, and code
refactoring.
*  In-depth development experience with any kind of database platforms such as Oracle, MS
SQL, Graph Database, or MySQL.
* In-depth development experience with REST, SOAP, XML technology.
* In-depth development experience with .NET ecosphere: ASP.NET, ASP.NET MVC, WCF,
Web API, Entity Framework, .NET Code, and ASP.NET Core.
### Ideally
*  Experience in Scrum/Agile/Kanban.
*  Experience in Front-end technology (e.g. Angular 2+, React JS, HTML, SCSS...)
*  Experience with TDD/BDD.
* UML, arc42, structure101.
*  Experience in profiling and performance monitoring tools.
*  Experience with infrastructure network/hardware such as virtualization, load balancing,
ADFS, LDAP, AD.
*  Microsoft Certified Professional (MCP) certificate is a plus.

### You’ll be responsible for
* Participate in analyzing requirements, design architecture, implementation, code review, unit
* test, test, and deployment process.
*  Technical leadership for .NET teams.
*  Discuss and propose solutions for team and monitor progress.
* Review source code and coach colleagues to follow coding standards, design patterns and
implement tests.
*  Research technologies and make workshops.
*  Assist and support PMs and teams in their daily work to build knowledge base and improve
the development, testing, and deployment process together.
*  Lead and provide estimation for requirements.
### Why it would be awesome to work with us 
* Net salary: we will cover your medical, social and unemployment insurance for you as well as
your personal income tax.
*  Monthly lunch allowance
*  Annual medical check
*  Premium health insurance
*  13th month salary
*  Loyalty bonus: after the first year, you will receive a loyalty bonus equal to 50% of your current
monthly salary each year.
*  14 days annual leave
*  Regular team dinners and End Year Party.
*  Annual company trip and team building activities.
*  Chance to work with top talents from Switzerland.
*  Chance to work with latest technologies (microservices, CI/CD, latest version of .NET Core,
Angular...).
*  Tuition fee support will be offered for English improvement at top English centers in HCMC.
*  Others: company sponsored sport clubs, parking fee, free coffee, snacks.

### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
