### ISSUE TITLE
Cyberlogitec - Senior FullStack Engineer - Saigon - FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2051]
## Location

* Saigon

## Salary Expectation

* up to 2500$ gross 

## Requirements
* Innovative and high-tech passion.
* Management experience
* Good English communication
### Must Have
*  At least 5 years of experience in:
> Back-end: OOP - Design pattern, Java spring
> Database: Database Design (Data Modeling), SQL Server, Oracle, MySQL,MongoDB ...
>  Front-end: Strong Javascript

### Ideally
*  Selenium
* Microservices
* ReactJS, Redis, Rabbit MQ
* Linux
* ADFS, LDAP, AD.
### You’ll be responsible for
* Team Leading & Team Management.
* Software design (Data model, software structural design).
* Develop & maintain Web/Back-end applications.
* Contribute to the company growth.
* Enjoy great career growth opportunities.
* Be comfortably flexible in technology to fit the project situations
### Why it would be awesome to work with us 
* Well trained and dedicated to being able to catch the pace smoothly.
* Attracted salary based on your ability.
* Salary review every 6 months based on your working performance.
* 13th-month salary and bonus for holidays.
* Team building once a month.
* Company trip once a year.
* PVI healthcare insurance.
* Full social benefits in accordance with the company and the law of Vietnam.
* Professional environment and clear procedures.
* Great opportunity to improve English.
* Opportunity to learn Logistics and professional management system of project development
process.

### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
