### ISSUE TITLE
Grasshopper - Data Scientist - Saigon -FT

### ISSUE THREAD

**Issue by viinhpham** [awesome-jobs/vietnam#2052]
## Location

* Saigon

## Salary Expectation

* Negotiation

## Requirements
* Experience working with and creating data architectures.
* Experience with distributed data/computing tools: Map/Reduce, Hadoop, Hive, Spark, Gurobi, MySQL, etc.
* We’re looking for creative, critical thinkers who enjoy taking systems apart to understand the
“why”, and using programming or maths in their daily life to solve problems.
* the work will require custom data processing that’s not easy to do efficiently in a language
like Python.
*  The ideal candidate would also have a strong familiarity with low-level programming and the
OS/network stack.
*  Interest in and knowledge of financial markets is a plus.
### Must Have
* Know at least one data analysis language, like Python or R, and one higher-performance language like C or C++,

### Ideally
*  Should have a strong background in either data science, and a
demonstrated history of successful problem-solving.
* Knowledge and experience in statistical and data mining techniques: GLM/Regression, Random Forest, Boosting, Trees, text mining, social network analysis, etc.
### You’ll be responsible for
* The primary responsibility of the role involves developing hypotheses about how to improve
our trading competitiveness, through statistical analysis, reverse engineering and modelling
of the networks and trading systems in which we operate, working with terabytes of market
and packet data. You’ll then build tooling and software to test these hypotheses in the live
market, working closely with our cutting-edge low-latency FPGA developers.
### Why it would be awesome to work with us 
* 13th month salary & performance review
*  Governmental insurances based on labour law (after probation)
*  100% of salary in the probation time (Included Personal income tax)
*  15 days of annual leave apart from national holidays by law
* Childcare leave:
*  2 days of childcare leave a year (With Grasshopper for at least 3 continuous months)
*  6 days of paid childcare leave per year, regardless of the number of children you have
(With company for at least 1 year).
*  Only be applicable for employees with children below 7 years old.
*  Marriage Leave
*  Maternity/Paternity leave: based on Labour law
* Off in lieu:
*  For working 4 hours or less on a weekend/non-trading day, you will be granted time off in
lieu of 4 hours on a working day.
* For working more than 4 hours on a weekend/non-trading day, you will be granted a full
day off on a working day.
*  Innovation leave: staff allowed to take up to 20% of their work time to work on innovation or
training. Innovation idea has to be posted on Innovation Board on Jira before taking of leave.
*  Out-patient and hospitalisation health insurance package (applicable also to spouse and/or
children where required)
*  Annual dental care package
*  Working equipment provided (laptop, extra monitor, etc)
*  Motorcycle parking fee allowance
*  Flexible work time arrangement where applicable
*  Team building activities, happy-hour, etc.
*  Opportunity to work with talented colleagues to improve your knowledge. Professional &
English speaking working environment and more...

### Contact
Homepage: None
Trollman: trinhanh.hr_at_gmail_dot_com

**Comment by hieuk09** [comment]
Thanks for posting but unfortunately we are only accepting job posts for in-house positions.
