### ISSUE TITLE
 Koidra - IoT Engineer - Saigon - FT

### ISSUE THREAD

**Issue by zer0n** [awesome-jobs/vietnam#2054]
<img src="https://user-images.githubusercontent.com/3055719/81139074-a5528c80-8f8e-11ea-99ad-f26f90201589.png" width="200">
is a fullstack IoT-AI company, offering data-driven automation solutions for hi-tech greenhouses. We are looking for talented IoT & Automation engineers to help us change the world.

The IoT & Automation engineers will be an integral part of our new Arduino-based `μControl` product that addresses the industry's digital integration barriers (more details in [this article](https://urbanagnews.com/blog/exclusives/when-will-artificial-intelligence-come-to-the-commercial-greenhouse-industry/)).

## Location
Saigon, Vietnam

## Salary Expectation
$1000 - $3000/month, depending on level

### Must Have
- Bachelor Degree in Computer Engineering, Electrical Engineering, Industrial Automation, or related fields
- 2+ year of professional experience in embedded programming
- Operating systems programming experience (e.g. C/C++, Linux, etc.)
- Experience with embedded IoT Device programming (Arduino, Raspberry Pi, etc.).
- Knowledge of industrial control and protocol for networking and data acquisition of PLC (Programmable Logic Controllers) to SCADA (Supervisory Control and Data Acquisition)
- Broad knowledge of electrical instrumentation and devices
- Experience with installation and maintenance of process automation devices for data acquisition and monitoring (e.g. real-time and on-line)
- Strong programming, debugging, and analytical skills
- Experience with `git`

### Ideally
You fit our culture, explained in these core principles
- **Customer obsession**
    Start with the customer and work backwards. Each of us must always understand our immediate customers, either internal or external. We always think customers first and work vigorously to earn and keep their trust.

- **Start simple and continuously improve**
    It’s better to make small changes, improve/push/deploy continuously than to code until perfection.

- **Insist on the highest standards**
    Koiers continually raise the bar and drive team members to deliver high quality products, services and processes.

- **Bias for action**
     Speed matters in business. Many decisions and actions are reversible and do not need extensive study. We value calculated risk taking.

- **Disagree and Commit**
    Koiers are obligated to respectfully challenge decisions when they disagree, even when doing so is uncomfortable or exhausting. Koiers have conviction and are tenacious. They do not compromise for the sake of social cohesion. However, once a decision is determined, they commit wholly.

## Responsibilities
- Design and implement the IoT OS for our Arduino-based PLC, ensuring scalability and easy integration
- Implement adapters for connecting sensors/actuators to the IoT OS
- Support development of software interfaces as between manufacturing machines and data repositories for advanced analytics
- Deploy for our customers
- Write clean, bug-free, and maintainable code
- Coordinate cross-functionally to insure project meets business objectives and compliance standards

## Why it would be awesome to work with us
Founded by Kenneth Tran, formerly a Principal Machine Learning Scientist at Microsoft Research (MSR), Koidra's mission is to change the industrial automation industry, applying cutting edge research in AI, IoT, and hybrid cloud+edge computing. Check out some early **[media coverage about us](https://www.notion.so/Press-Releases-354cdc2b6461476b98c2d01dfa1d22dc)**.

At Koidra, you'll have an opportunity to work with world experts in Machine Learning and Software Engineering.

**Other benefits**
- Active and agile working environment; flexible time culture
- An environment for you to be maximally productive
- Opportunity to impact the company (and hence the global stage) in big ways

## Contact
Kenneth Tran (CTO): ken@koidra.ai (0935069639 or WhatsApp: +15124363250)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
