### ISSUE TITLE
 Koidra - Frontend Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by zer0n** [awesome-jobs/vietnam#2055]
<img src="https://user-images.githubusercontent.com/3055719/81139074-a5528c80-8f8e-11ea-99ad-f26f90201589.png" width="200">
is looking for strong frontend+mobile engineers with a strong passion for web/app design, open source software stacks, and cloud computing.

## Location
Saigon, Vietnam

## Salary Expectation
$1500 - $2500/month

### Must Have
- 2+ years of professional experience in frontend or full-stack development
- Experience in TypeScript and familiarity with modern frontend libraries and tooling
- Fluency in HTML, CSS, and related web technologies
- Strong coding, debugging, optimization, and problem solving skills
- Passion for and experience in using open source frameworks
- Organized and self-sufficient
- Obsessed with customer satisfaction

### Preferred
Familiar with full-stack development can work on the backend when needed

### Ideally
You fit our culture, explained in these core principles
- **Customer obsession**
    Start with the customer and work backwards. Each of us must always understand our immediate customers, either internal or external. We always think customers first and work vigorously to earn and keep their trust.

- **Start simple and continuously improve**
    It’s better to make small changes, improve/push/deploy continuously than to code until perfection.

- **Insist on the highest standards**
    Koiers continually raise the bar and drive team members to deliver high quality products, services and processes.

- **Bias for action**
     Speed matters in business. Many decisions and actions are reversible and do not need extensive study. We value calculated risk taking.

- **Disagree and Commit**
    Koiers are obligated to respectfully challenge decisions when they disagree, even when doing so is uncomfortable or exhausting. Koiers have conviction and are tenacious. They do not compromise for the sake of social cohesion. However, once a decision is determined, they commit wholly.

## Responsibilities
- Implement new and improve existing features for our web and mobile apps
- Architect efficient and reusable front-end systems that drive complex applications
- Identify and resolve performance and scalability issues
- Collaborate with other software engineers and other key stakeholders to deliver compelling user-facing products

## Why it would be awesome to work with us
Founded by Kenneth Tran, formerly a Principal Machine Learning Scientist at Microsoft Research (MSR), Koidra's mission is to change the industrial automation industry, applying cutting edge research in AI, IoT, and hybrid cloud+edge computing. Check out some early **[media coverage about us](https://www.notion.so/Press-Releases-354cdc2b6461476b98c2d01dfa1d22dc)**.

At Koidra, you'll have an opportunity to work with world experts in Machine Learning and Software Engineering.

**Other benefits**
- Active and agile working environment; flexible time culture
- An environment for you to be maximally productive
- Opportunity to impact the company (and hence the global stage) in big ways

## Contact
Kenneth Tran (CTO): ken@koidra.ai (0935069639 or WhatsApp: +15124363250)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
