### ISSUE TITLE
NodeJS developer - Geospatial company in Hanoi #Fulltime

### ISSUE THREAD

**Issue by hoangvietanh** [awesome-jobs/vietnam#2057]
## Ví trí

*Hanoi Vietnam

## Mức lương

* USD 600 - 1000

## Yêu cầu
Có nền tảng kiến thức công nghệ thông tin.
Nắm được quy trình phát triển phần mềm, Database design/SQL.
Có kiến thức về lập trình web (backend hoặc frontend)
Có kiến thức về  NodeJS, Java là một lợi thế.
Có kiến thức cơ bản về Git, Docker là một lợi thế.
Có khả năng tự học hỏi.

## Giới thiệu về cty
Green Field consulting (GFD) là một công ty tư vấn và triển khai các giải pháp bản đồ số/GIS, ứng dụng phân tích không gian cho quản lý tài nguyên thiên nhiên, hệ sinh thái và kinh tế xã hội.
Tại GFD bạn sẽ làm việc với một nhóm nhỏ gồm các kỹ sư phần mềm, kỹ sư trắc địa tin học, kỹ sư GIS/Viễn thám, chuyên gia về thống kê và phân tích dữ liệu, chuyên gia về rừng và sinh thái học. GFD cung cấp các giải pháp IT cho quản lý rừng, mobile app cho mapping/data collection, xử lý và phân tích ảnh viễn thám, xây dựng các ứng dụng liên quan đến quản lý tài nguyên, quản lý không gian. Ngoài ra chúng tôi cũng thực hiện các dự án nghiên cứu về lĩnh vực Geospatial cho các bộ ngành và các nhà tài trợ như World Bank, ADB, JICA. Một số sản phẩm của công ty đã được bàn giao và triển khai ở các nước Đông Phi, Nam Mỹ, Ấn Độ, Trung Quốc.
Một số dự án đang thực hiện gồm
* Giải pháp theo dõi diễn biến rừng ứng dụng ảnh vệ tinh thời gian thực. Nhà tài trợ USAID;
* Hệ thống theo dõi diễn biến rừng cho tỉnh Bình Thuận; Sở NN tỉnh Bình Thuận.
* Hệ thống đánh giá ảnh hưởng thiên tai trên nền GIS. Nhà tài trợ UNDP.
* Ứng dụng Machine learning cho xây dựng thiết bị phát hiện tiếng cưa máy giúp bảo vệ rừng.
* Hệ thống học máy cho tự động phát hiện biến động rừng từ ảnh vệ tinh sử dụng cloud computing;
* Hệ thống theo dõi, giám sát dự án cho chương trình giảm phát thải từ rừng quốc gia.
* Hệ thống theo dõi chuỗi hành trình gỗ hợp pháp cho hiệp hội lâm sản Quy Nhơn;
* Hệ thống thu thập dữ liệu đường phố phục vụ cho các hãng xe và logistic lớn.
* Hệ thống bản đồ WebGIS và ứng dụng khảo sát tre cho tổ chức Tre quốc tế (INBAR)
* Hệ thống quan trắc môi trường thủy sản (hợp tác với Đại Học Queensland)
* Bạn có thể xem thêm trang web hoặc facebook page để xem thêm về công việc của chúng tôi.
[www.gfd.com.vn](www.gfd.com.vn)
[https://www.facebook.com/GFDVietnam/](https://www.facebook.com/GFDVietnam/)
Địa điểm làm việc: 14 Trần Hưng Đạo, Hoàn Kiếm Hà Nội
Thời gian làm việc: thứ 2 đến thứ 6. Hầu như không có overtime.

### Công việc

Tham gia xây dựng hệ thống cảnh báo real time và near real-time về diễn biến rừng.
Phát triển và hoàn thiện ứng dụng di động (cả backend và client) cho lĩnh vực lâm nghiệp/ môi trường; thu thập số liệu thực địa; tự động xử lý, phân tích và cung cấp dữ liệu đã qua xử lý tới cho khách hàng qua các giao thức web, app, mail và SMS.
Phát triển ứng dụng Web và mobile liên quan tới xây dựng cổng thông tin, quản lý sản xuất trên nền tảng WebGIS, hệ thống dẫn đường, phân tích và xử lý dữ liệu không gian.
GFD là một nhóm nhỏ nên bạn sẽ phải làm từ A-Z và nhanh chóng trở thành full-stack.

### Contact
Gửi thông tin qua form sau

[https://airtable.com/shr9e6LroeQ9HXPmG
](https://airtable.com/shr9e6LroeQ9HXPmG
)

**Comment by qcam** [comment]
Please help to rewrite the job post in English and also follow our guidelines at README. Thanks.

**Comment by hoangvietanh** [comment]
Thanks, I wil post somewhere else. It's silly to force the use of English for recruitment of Vietnamese employee.
