### ISSUE TITLE
[LINAGORA] (Senior) DevOps Engineer - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2061]
## Location

* 1 Thái Hà, Đống Đa, Hà Nội

## Salary Expectation

* Up to $2000 Gross

## Requirements

* Background in Computer Science / Information Technology or equivalent.
* Knowledge of CI/CD and IT security concepts
* Knowledge of Sourcecode Management Systems: Gitlab, Github, Bitbucket
* Knowledge and experience of Kubernetes (k8s), Docker•
* Knowledge of Provisioning and Configuration Management tools such as Ansible, Terraform, Puppet is a plus
* Good level of English

### You’ll be responsible for

As a DevOps Engineer, the incumbent will report to DevOps Team Leader and cover the following
main duties and responsibilities:
* Implement and improve monitoring and alerting
* Build and maintain highly available systems on Kubernetes
* Implement and manage CI/CD pipelines
* Implement an auto-scaling system for our Kubernetes nodes
* Participate in on-call rotations

### Why it would be awesome to work with us

* Work in an international team with highly skilled people
* Opportunity to be promoted to senior/management position in a company that is having a huge growth in Hanoi
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate in Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact
Homepage: linagora.vn
Email: vnhr@linagora.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
