### ISSUE TITLE
[LINAGORA] Android Developer - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2062]
## Location

* 1 Thái Hà, Đống Đa, Hà Nội

## Salary Expectation

* Up to $1700

## Requirements

Bachelor’s degree in information technology, or related field
At least 3 years of experience
Required Knowledge, Skills, and Abilities
* App design
* Backend web services knowledge
* Unit tests, automation, and code reviews
* Willingness to learn new technology
* Strong OO design and programming skills in Java or Kotlin, APIs
* Familiar with the Android SDK
* Complex solving problem
* Fluency in English

### You’ll be responsible for

You’ll develop from scratch the Android mobile application of the OpenPaaS (https://open-paas.org/) platform. We target two first mobile applications :
* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices
* a Chat application, linked to the OpenPaaS Chat web module, to allow people to keep chatting on their mobiles
You are passionate, motivated in the Open Source projects. Besides coding, it’s important that you learn our business and help to align technology innovation with our customer needs.

Other responsibilities:

* Participate in product design, offer new ideas
* Collaborate with product and business teams to define our product that are suitable for the market
* Design and implement a mobile application for Android using Java or Kotlin• Work in team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our teams maintain high standards
* Support international teams in developing products to meet the clients’ requirements
* Keep up to date on the latest industry trends in the mobile technologies

### Why it would be awesome to work with us

* Work in an international team with highly skilled people
* Opportunity to be promoted to senior/management position in a company that is having a huge growth in Hanoi
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate in Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact
Homepage: linagora.vn
Email: vnhr@linagora.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
