### ISSUE TITLE
Uiza - Techical Writer (Fresh/Junior/Senior) - HCM - FT

### ISSUE THREAD

**Issue by linhrily** [awesome-jobs/vietnam#2064]
## Location

* Saigon, Vietnam
* Remote/Full-time/Part-time

## Salary Expectation

* Negotiate

## Requirements

* A strong fundamental understanding of the software development cycle.
* Proven skill in a technical domain or in a technical writing role (for mid-level).
* You are proficient in the Google suite and pick up new software easily.
* You’ve experience working with live streaming software such as OBS, Streamlabs…

## Skills

* English (IELTS >=5.0) is a plus.
* Strong written and email etiquette skills as well as oral communication skills, including the ability to present technical information in user-friendly language.
* Experience using tools to create, manage, and publish documentation. 

### Responsibilities

Our technical writers ensure that Uiza products are clearly described in documentation that is accurate and useful.
Create conceptual information:
* Create Step-by-step procedures
* Write out API descriptions and example commands
* Be one of the first to try new features as you work with developers and designers to improve the related user experience, UI text, error messages, and API design
* Interact directly with customers and use their feedback to improve the documentation dynamically, then update and publish your documentation on demand

### You can bring

* Love and passion for helping customers and delivering satisfaction even when faced with difficult customers.
* A good team player, willing to share with others and work together.

### Why it would be awesome to work with us
At Uiza, we believe that video will make a huge impact on the world that we are living in and shift it along with its technologies in a new direction. That is the reason why we carry a mission of making video universally accessible by building a Universal Streaming Operating System that could power all videos. We have been serving developers and their audiences in 180 countries in the world in a wide-range of use-cases.

Uiza is committed to each employee’s growth, learning, development and entire employee experience. We restlessly promote a growth mindset, innovation, transparency and commitment because we know that our vision is only achieved when our team members succeed. We want you and your ideas to thrive at Uiza. Come join us.

### Send CV and Contact
Mail: linhnht@uiza.io
Our website: https://uiza.io/

**Comment by linhrily** [comment]
#

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
