### ISSUE TITLE
A stealth startup - Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by tienle** [awesome-jobs/vietnam#2065]
Our very early-stage startup is founded by 3 members who used to be the core members and Head of Engineering of a well-known startup in Sydney (hundred of millions in valuation).

We’re looking for exceptional people to join our team. The people who like to work with great engineers in town; have the chance to learn from them and believe that we can accomplish so much more together than apart.

## Location

* Saigon, Vietnam

## Salary Expectation

* $500-700 USD/month

## Requirements
We are always looking for great people to join our team. Above specific skills for the specific role, we're looking for candidates who share the following traits: 

- Performance-minded, able to listen hard and change fast
- A lifelong learner who is able to learn rapidly and eagerly
- You take smart risks
- You maintain calm poise in stressful situations
- Honesty & Humility

We are doing React-native (ReasonML), Ruby/Elixir daily. But, we’re more interested in how you think and learn than what you already know. If you don't know them, your capability and willingness to learn is enough. You have the chance to be trained by our best engineers.

### Responsibilities

* Help us build features and apps that people love to use
* Make your coworkers laugh

### Why it would be awesome to work with us

Our office, our team size is small now, but our dream, our passion is real big.

At Camelo, we are true believers in how important it is to make it is easy to collaborate people work and to have better work achievement together. We spend our days building a product we love, the mobile app for helping non-desk workers.

Our team culture speaks for itself. You will surround yourself with smart, humble, and humorous coworkers. 

If you are looking for a challenging workplace where you can use/develop your talents for something big and meaningful then Camelo could be the place for you. 

Be a part of something amazing that starts with you.

-----

FYI, here is a snapshot of the benefits & perks

- Company equity
- Macbook
- Snacks and drinks
- Unlimited paid time off (no approval needed)
- Flexible working hours (self-management)
- Team bonding activities: Swimming, Gym and play poker

### Contact

Tien Le: tienlx at g mail dot com

![88505611-2a839580-d002-11ea-9963-84f9beaaf247-min](https://user-images.githubusercontent.com/190798/88506137-78e56400-d003-11ea-8d2e-b085e43458be.png)

![image](https://user-images.githubusercontent.com/190798/88505475-c1038700-d001-11ea-9f2a-079bb0c4ad94.png)

**Comment by khacanh** [comment]
Up!

**Comment by bdthinh** [comment]
Up!

**Comment by manucianvy97** [comment]
Do you need Flutter Developer?

**Comment by Raes2000** [comment]
Im a  student in end of second year just know basics about coding may i apply for this job ?

**Comment by tienle** [comment]
@manucianvy97  We are doing React Native currently and if you are willing to switch to do RN daily. Feel free to contact us ;) 
@Raes2000 Sure, contact us. We’re more interested in how you think and solve problems than experience years or so.

**Comment by ldchinhcr** [comment]
Do you still recruit for React position during this time? I have some experience in making with some projects with ReactJS (e-commerce, chat application)... and I'm willing to learning for the new framework base on Javascript for the projects if needed.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
