### ISSUE TITLE
Raksul Vietnam - Senior / Lead VueJS Frontend Engineer - HCMC - FT

### ISSUE THREAD

**Issue by le-tuan-dung** [awesome-jobs/vietnam#2068]
## Location
* HCMC, Vietnam

## Salary
* 2,000 - 4,000 USD

## TOP 3 BENEFITS
1. High impact product
2. Talented system engineers
3. International colleagues

## We are looking to hire candidates for the following responsibilities
* Act as the bridge between engineering teams in Japan and Vietnam
* Partner with business teams in Japan to understand business requirements
* Provide assistance and advice on the definition of system requirement and system design
* Provide guidance and mentoring to junior members

### Must Have
* Working experience in front-end frameworks (fluent in at least 1 of the following: Vue.js, Angular, React)
* Experience in development using Git with a team
* Experience as a team leader and a reviewer
* Ability to communicate fluently in at least two of the following languages: Vietnamese, English and Japanese

### Nice-to-have
* Experience in front-end development using TypeScript, FlowType, etc.
* Experience in designing and tuning UI interaction using CSS animation.
* Experience in build front-end development environment using Webpack, Gulp, etc.
* Experience in improving legacy code/system and working with REST API
* Experience in pair programming and/or mob programming
* Experience in working with cloud computing such as AWS

### Other important factors
* Ability to contribute to the expansion of the Vietnam (HCMC) development team
* Ability to work with others and preference on teamwork
* Proactively think and speak-up
* High interest in learning and using new technology
* Ability to define service issues or technical issues and proactively solve them
* Strong interest to change old industries with technology

### Excellent environment
* Flexible working time
* "Hackweek", one week hackathon in every year. Try new technology to build any product by your idea in a small team
* Weekly tech meetup hour to share own knowledge
* MacBook Pro/Air provided

### Competitive salary
* Salary reviews every 6 months
* Two times bonus in a year
* Health insurance

### Many other benefit
* Monthly team building lunch or dinner
* At least 15 paid days off per year.
* A 40-hour regular work week with little or no after-hours work requirements

### Contact
Homepage: https://corp.raksul.com/en/
Email: vietnam-hr-uc@raksul.com

Other: 
https://itviec.com/companies/raksul-inc

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
