### ISSUE TITLE
Sendo - Golang Developer (Mid-Senior) - Saigon D7 - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2070]
## Location

* District 7, Ho Chi Minh city, Vietnam

## Salary Expectation

* Range: 1000-2000 USD gross

## Requirements

- 2+ years in Golang
- PostgreSQL, MongoDB, MySQL
- 2+ years Software Engineering experience

### Responsibilities

Write scalable, robust, testable, efficient, and easily maintainable code.
Write document, review code and support technical for junior members.
Collaborate to R&D, System, Product, Seller teams to build or maintain Sendo’s products.
Working in squad Account to improve Sign in/up flow, User Authentication, Authorization,
User Segmentation to help improve buyers & sellers experience
Great power comes with great responsibilities!

### Why it would be awesome to work with us

**Why SENDO?**

At SENDO we believe that our employees are the keys to our success. Happier employees will perform very well! We not only provide an awesome working environment where young and talented employees work, share ideas and help each other improve, but we also have lots of fun activities. Besides, you will work on the biggest e-commerce product using the latest technology and with top engineers in Vietnam

**SENDO benefits and Perks**

- Competitive salary and benefits including extra medical insurance.
- 13th-month salary.
- Performance Review up to 2 times/year
- Company and team-building trip every year
- Gift on special days like birthday, Tet and Holidays
- Many fun and meaning activities such as sport and social clubs
- Opportunity to training both technical and soft skills to develop your career path

### Contact
Drop your updated CV to quyenpm@sendo.vn
Homepage: https://careers.sendo.vn/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
