### ISSUE TITLE
Orange Logic - Software Engineering Intern - HCMC - FT

### ISSUE THREAD

**Issue by hanguyenOL** [awesome-jobs/vietnam#2071]
## Location

* HCMC, Vietnam

## Salary Offer

* $1000

## Requirements

* Currently enrolled in a Bachelor / Master degree  in **Computer science / Software engineering** or equivalent
* Excellent academic grades / Top of the class 

## Skills

* Experience with data structures or Algorithms (from university, an internship, hobby or other practical experience)
* Coding experience in one of the following languages: .NET / C# / Java 
* A good command of English both verbal and written

### Must Have

* Strong **self-discipline** and the capability for **rational thinking**.
* Be able to work **full-time**, for **12-14 consecutive weeks**, starting in **September 2020**

### The opportunity

Our **selective** internship program is an opportunity to gain hands-on experience as a software engineer, understand further the **software production** principles, and discover the business of an editor, along with its unique **company culture**
 
Specifically, as an intern, you will:

- Work in teams to deliver concrete projects for our prestigious clients (Airbnb, BBC, Reuters…) 
- Complete learnings (training, lectures, graded assignments) organized for you in our office
- Learn about our company & its DAM product, and contribute to its development and good reputation

Depending on your achievements, you may be offered a **permanent position** at Orange Logic.

### Why it would be awesome to work with us

* Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development. At Orange Logic, it does not matter how many years of experience you have, or your age. We believe that each individual, regardless of these factors, has the ability to evoke change within the organization.
* Amazing team: smart, open-mind, and passionate engineers. They came from the US, France, UK, and Vietnam hence you could improve your English and explore different country cultures
* 18 days of annual leave (cashback for unused days) + 4 days for an abroad company trip (Taiwan, Thailand, etc)
* 13th-month salary no matter when you join the team
* Performance bonus (average $700/month in 2020)
* Monthly team outing activity
* Premium healthcare insurance ($10.000 cover) after probation
* Full Insurance based on your Gross salary
* Allowances for lunch, gym, parking ($100)
* Birthday bonus ($100), Tet gift, etc
* Daily free snacks, fresh fruit, coffee & soft drinks
* Latest gadgets for work (include noise-canceling headphones)

### Contact
Please send your resume and transcript to ha.nguyen@orangelogic.com
You can drop me a message on [Skype](https://join.skype.com/invite/mNKg28GbjKfr) or [Linkedin](https://www.linkedin.com/in/ha-nguyen-01a752ba/)
[Our Homepage ](https://www.orangelogic.com/digital-asset-management-customer-examples)

> Can't wait to have a detailed discussion if you have any questions or concerns!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
