### ISSUE TITLE
Agency Revolution - Dev Team Lead (.NET) - Saigon -  FT

### ISSUE THREAD

**Issue by lucasjans** [awesome-jobs/vietnam#2072]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2,200+

## Job Description

You are a catalyst and respected among your peers. With you on the team, everyone is the best version of themselves. People around you work hard, but to them, it doesn’t feel like work. You understand the other team members and elevate them. You try to understand first, then try to be understood. You are a clear writer and a sharp thinker. You have a passion for technology and growth. 

You are an excellent proactive communicator who has the willingness and ability to accommodate different time zones, including direct communication with US teams on a weekly basis. You are experienced in influencing others to make decisions and taking extreme ownership of everything related to your allocated departmental processes. 

You will be the coach of a team full-stack engineers and quality assurance engineers for a US-based product team. You will report to the product manager and have a direct connection with the US-based Director of Engineering - an amazing person. You will be coding and designing systems, and guiding the team to success. You test your work and follow the YBIYRUYFI principle (you build it, you run it, you fix it). When you send something to QA, it's for the seal of approval, not to test your work.

### Qualificatons

- 5+ years experience as a full-stack engineer designing, coding, deploying, troubleshooting and maintaining web applications
- Experience with SQL and schemaless databases.
- Knowledge of multiple back-end languages (e.g., C#, Java, Python) and JavaScript frameworks (e.g., React, Angular, Vue)
- Excellent ability to solve open-ended problems in an elegant, scalable manner; critical thinker
- Strong interpersonal skills with the ability to work in teams and independently
- Great communication, attention to detail, and a strong teamwork ethic

### Personality

- “People person” who loves to help others grow
- Enjoy challenging conversations and guiding progress in others
- System oriented - not afraid to run reports, gather the facts and follow a dynamic process
- Patient listener, never interrupting and always showing empathy.
- Make people feel safe sharing their opinions
- Servant leadership - prefers to guide people to success rather than give orders
- Growth mindset orientation over a fixed mindset

### Preferred Qualifications

- A bachelor’s degree in Computer Science/Information Technology or equivalent;
- A strong DevOps mindset, experience with shell scripting and automation tools, like Ansible.
- Experience with big data and time-series data.
- Experience building software in a microservices environment

## Responsibilities

- Work with teams to collaboratively design, implement and release new features and products on the platform
- Work regularly with the US-based engineering leadership team on best practices and guiding the team to success
- Stay abreast of our product domain so you can innovate and collaborate with our product team. 
- Understand all parts of a project and identify risks so that the team can mitigate them
- Communicate project status to stakeholders, ensure that internal systems are up to date
- Manage the technical debt and refactor aging architecture when it drags the team down.

## Why work at FMG Suite?

- Why work at FMG Suite?
- We’re a US-based product company - and growing
- 12 days annual leave provided per year (not including holidays)
- Up to 30 days per year for long term employees
- A bonus day off for your Birthday
- Flexible working hours (40h/week)
- Optional work-from-home two days per week
- Professional equipment - Laptop + 2 screens
- Premium health insurance for you and your spouse (husband or wife)
- 13th-month salary, including probation time
-

### Contact
More about us: www.fmgsuite.com and www.agencyrevolution.com
To apply, email lucas.jans@fmgsuite.com

**Comment by dvkndn** [comment]
> a direct connection with the US-based Director of Engineering - an amazing person

Hi Lucas, it's interesting you mentioned this. Is there a name that I can search to learn more about her/him?

**Comment by lucasjans** [comment]
Nate Alvar is our VP of Engineering

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
