### ISSUE TITLE
SCS Solutions - Technical Architect (.NET) - HCMC - FT

### ISSUE THREAD

**Issue by hatran171** [awesome-jobs/vietnam#2073]
## HCMC

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $2000/month or range

## Requirements
* Experience of common software design patterns
* In-depth development experience with .NET ecosphere: ASP.NET, ASP.NET MVC, WCF, WebAPI, Entity Framework, .NET Code, and ASP.NET Core
* Experience with any kind of database platforms such as Oracle, MSSQL, Graph Database, or MySQL
* At least 7 years of experience in analysis, design, and development of .NET software solutions

### Responsibilities
* Participate in analyzing requirements, design architecture, implementation, code review, unittest, test, and deployment process.
* Technical leadership for .NET teams.
* Discuss and propose solutions for team and monitor progress.
* Review source code and coach colleagues to follow coding standards, design patterns and implement tests.
* Research technologies and make workshops.
* Assist and support PMs and teams in their daily work to build knowledge base and improve the development, testing, and deployment process together.
* Lead and provide estimation for requirements.

### Contact
Homepage: www.scssolutions.io
Mail: recruitment@scssolutions.io 
Mobile: 0903253593

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
