### ISSUE TITLE
SCS Solutions - .NET Developer - HCMC - FT

### ISSUE THREAD

**Issue by hatran171** [awesome-jobs/vietnam#2074]
## Location

Lê Văn Sỹ, Tân Bình, HCMC

## Salary Expectation

* $1500/month or range

## Requirements
- 3+ YOE
- Strong experiences with C#, .Net Framework, Entity Framework, LINQ
Nice to have: knowledge of E-commerce Integration : Amazom(s3), Shopify

### Responsibilities
•	Translate application storyboards and use cases into functional applications
•	Design, build, and maintain efficient, reusable, and reliable code
•	Join to solution analyze and documents
•	Ensure the best possible performance, quality, and responsiveness of applications
•	Identify bottlenecks and bugs, and devise solutions to mitigate and address these issues
•	Help maintain code quality, organization, and automation

### Contact
Homepage: https://scssolutions.io/
Mail: recruitment@scssolutions.io
Skype: ttp.ha985
Mobile: 0903253593

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
