### ISSUE TITLE
Senior Java Developer (Team Lead)

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#2077]
## SEN Platform

**Sunrise Cityview**, 33 Nguyen Huu Tho Street, Tan Hung Ward, District 7, Ho Chi Minh City

### **Offer: $1,200 - $1,500**

**_Apply now: https://topdev.vn/s/NO7JOTxt_**

## You will be in charge of:
* Design features, Coding, debug, develop apps and functions of products  

* Responsible for packaging products to ensure the quality meet requirements, support and handle technical issues from customers

* Support CTO in maintaining, improving products and supporting customers

* Management developer team and testers

## We are looking for candidates with:
* 3+ years of experience with back-end Spring Framework Java, AWS and Google Cloud

* Experience and knowledge in Javascript (JQuerry) AngularJS,  HTML5, CSS, Twitter, Bootstrap 3

* Excellent analytical, problem solving, and time management skills, make sure work schedule and reputation with foreign partners  

* Experience management for a team of 3-5 developers 

* Graduated in Computer Science/ Math... or related majors

* Good English is advantage 

* Experience in educational products 

* Fun, sociable, committed 

## Why it would be awesome to work with us:
* Super competitive salary

* Working with IT experts, projects with foreign partners

* Oversea training opportunities

* Joining start-up training

* Friendly, funny working environment

* Experience the online training technology in the US and Vietnam

* Working time: Mon - Fri

## You can reach us through:
Email: huykhanh.tran3108@gmail.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
