### ISSUE TITLE
Rakuna - Mid-Level Software Developer - Hanoi/HCM - FT

### ISSUE THREAD

**Issue by ly-rakuna** [awesome-jobs/vietnam#2080]
## Location

- Hanoi, Vietnam

- HCM, Vietnam

## Salary Expectation

- Competitive and negotiable

### Must Have
- Master at least one of these programming languages: Ruby, Javascript, Golang
- At least 2+ years of software development experience 
- Have a strong knowledge of TDD, BDD
- Experience with modern web framework (a must for Web developer)
- Working proficiency and communication skills in verbal and written English

### Ideally

- Familiar with Agile development
- Experienced with cloud services (AWS, GCP, Azure)
- Love startup-like environment, want to challenge yourself and aim for a leadership prospect
- A good sense of design

### Responsibilities

- Deeply participate in the product development process of analyzing requirements, designing system, implementation, testing and deployment.
- Collaborate with core functional teams - Sales & Marketing, Customer Success, and Operations to achieve the ultimate business goals.
- Understand and work within the brand and corporate guidelines

### Why it would be awesome to work with us

- We have an energetic and intimate environment with a team of millennials who are hustlers and passionate about building things that matter. We are looking for fun, driven, hardworking, and savvy team members to help to take our brand to the next level.

### Contact

- Homepage: www.rakuna.co
- Email: khaint@rakuna.co

**Comment by ducthien1490** [comment]
up

**Comment by ly-rakuna** [comment]
up!

**Comment by ly-rakuna** [comment]
Up up again! Contact khaint@rakuna.co if you have any questions!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
