### ISSUE TITLE
[LINAGORA] DevOps Engineer - Hanoi - Full time

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2081]
## Location

* 5 Dien Bien Phu, Ba Dinh, Ha Noi

## Salary Expectation

* Up to $2000

## Requirements

* Background in Computer Science / Information Technology or equivalent.
* Knowledge of CI/CD and IT security concepts
* Knowledge of Sourcecode Management Systems: Gitlab, Github, Bitbucket
* Knowledge and experience of Kubernetes (k8s), Docker•
* Knowledge of Provisioning and Configuration Management tools such as Ansible, Terraform, Puppet is a plus
* Good level of English

### You’ll be responsible for

* Implement and improve monitoring and alerting
* Build and maintain highly available systems on Kubernetes
* Implement and manage CI/CD pipelines
* Implement an auto-scaling system for our Kubernetes nodes
* Participate in on-call rotations

### Why it would be awesome to work with us?

* Work in an international team with highly skilled people
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate in Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact

Homepage: linagora.vn
Email: vnhr@linagora.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
