### ISSUE TITLE
Lecle Vietnam - Back-end Developer - HCMC - FT

### ISSUE THREAD

**Issue by uyennguyenhr** [awesome-jobs/vietnam#2084]
### Location

* Saigon, Vietnam
* District 1

### Requirements
* 3+ years of experience in the related field
* Ability to adapt to web frameworks and implement them in ongoing projects
* Familiarity with common design patterns and OOP techniques
* Solid understanding of Web Technologies: HTTP, AJAX and RESTful API, AWS
* Understanding of how Scrum and Agile work
* Understanding of the fundamentals of data structures, algorithms and networking protocols
* Profound understanding of Version control systems (Git)

### Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + KPI bonus at the end of the year
* 15 days of annual leave per year
* Onsite opportunity in Korea
* Company trip at least once a year, monthly company parties & other Teambuilding activities
* Free coffee, snack and drinks

JD for detail: https://smrtr.io/4g8FJ

### Contact
Phone: 028-6295-8827
Send your CV to email: career@lecle.co.kr

### Know more about us
Facebook: https://www.facebook.com/LecleVietnam/
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
