### ISSUE TITLE
[LINAGORA] Senior Automation Tester - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2087]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ba Dinh, Hanoi

## Salary Expectation

* Up to $1300 gross

## Requirements

* 3+ years’ experience in Automation testing for Web/mobile applications.
* Experience in automation test using Robotframework.
* Familiar with Page Object Model.
* Experience in performance testing is a PLUS
* Automation framework design and development experience is plus.
* Good communication in English.

### You’ll be responsible for

* Join QA team to contribute to the development of various products including collaboration and communication tools for enterprises (mainly web-based, plus mobile app)
* Mainly work on building/maintaining automation scripts for our products based on the scenarios provided by the functional test team
* Report bugs found by the tests and follow up with development team to get them fixed
* Support manual testing when needed
* Work closely with QA head and development team on the plan for automation testing
* Share knowledge with other QA members, actively contribute to Open Tech Talk and internal workshops
* Be willing to learn other technical testing skills/tools

### Why it would be awesome to work with us

* Work in an international team with highly skilled people
* Opportunity to be promoted to senior/management position in a company that is having a huge growth in Hanoi
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate to Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact

Homepage: linagora.vn
If you are interested in this opportunity, please kindly send your CV in English to the email address: vnhr@linagora.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
