### ISSUE TITLE
[LINAGORA] System Administrator - Hanoi - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2088]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ba Dinh, Hanoi

## Salary Expectation

* Up to $1500

## Requirements

* Knowledge about Linux environments (Debian / CentOS / RHEL / Suse) and basic network and System Administration skills.
* Fluent English (written and spoken)
* General knowledge in Open source
* Agile Management knowledge

### You’ll be responsible for

The daily duties of a System Engineer (OSSA Team) are very close to those of an R&D software engineer:
* Qualify customers’ user stories,
* Develop the best technical answers to our customers,
* Share permanent experience with clients’ ops teams
* Contribute to the original Open Source community
* Handle all new requests for assistance.
* Set up, interface, deploy, and integrate free software supported in the context of the beneficiaries.

### Why it would be awesome to work with us

* Work in an international team with highly skilled people
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate in Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact

Homepage: linagora.vn
If you are interested in our job opportunity, please kindly send you CV in English to the email address: vnhr@linagora.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
