### ISSUE TITLE
Yojee - Product Manager - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#2089]
## Location

* District 4, Saigon, Vietnam

## Salary Expectation

* VND 50m - VND 80m gross per month

## About the role

Yojee is looking for a Product Manager that enjoys working in a dynamic startup and will be responsible for delivering world class logistics services across the globe. The ability to work with product managers and ensuring engineering hits deadlines and deliverables is something you take pride in. Together with the team, you will have full ownership of the services you build.

## Requirements

* Bachelor Degree in Computer Science or related technical field preferred.
* 3-6 years of working experience; 1 year or more of product management experience preferred.
* Strong communication skills and ability to understand perspectives of different users and prioritize needs.
* Analytical problem-solver, detail-oriented and self-driven.
* Fast-learner, comfortable in leading independently without much supervision in a fast-paced environment.
* Domain knowledge of our market.
* Some experience in quality assurance and continuous improvement processes.

## Responsibilities

* Lead and oversee one or more products in Yojee.
* Lead the strategy and development of products, and oversee their lifecycle from ideation to release, and then ongoing developments and improvements.
* Identify and fill product gaps and generate new ideas, improve customer experience and drive growth.
* Scope and prioritize activities based on business and customer impact.
* Translate product strategies into detailed requirements and prototypes.
* Coordinate, schedule and work closely with engineering teams and executives to serve the needs of the business and to optimize the utilization of development resources.
* Perform and handle other ad-hoc duties as required.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Senior Product Manager.

## Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

## About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Product team at Yojee

Yojee Product team comes up with the best strategy for product features and roadmap to solve on-ground logistics problems. We are accountable for the entire product lifecycle, right from planning through development, go-live, and retirement phases

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=53&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
