### ISSUE TITLE
FETCH TECH - Senior BE NodeJs Developer - Full-time - Hanoi

### ISSUE THREAD

**Issue by JunnieNguyen** [awesome-jobs/vietnam#2094]
## Location

* 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Cau Giay District, Hanoi
* Full-time

## Salary Expectation

* 2500 USD/month 

## Requirements

* More than 4 years working experience with Express, Angular, Node or Python, Golang technology stack.
* Solid knowledge of modern web development technologies & framework based on JavaScript, HTML, CSS.
* Experience with SQL and NoSQL database. Familiar with DynamoDB
* Experience in design and implement REST, GraphQL APIs.
* Experience in automated trading system, trading bot.
* Proficient in AWS related services.
* Fully familiar with Software development lifecycle.
* Strong problem solving and time management skills.
* Willing to learn new technology, product mind-set.
* Interested in Cryptocurrency and Blockchain.
* Proficiency in Apps (Android, IOS) programming language is a plus.

### Responsibilities

* Building management backend (server-side) for systems operating: monitoring system, reporting system, data integration 
* Write code features according to operational needs, docker, message queue, database (MySQL, Mongo ...), API, CI/CD …
* Participate in software architecture design and data structure.
* Research and apply techniques that ensure user requirements.
* Optimize the system to process large data.
* Deploy code on server test and production.
* Write clean, clear, easy-to-maintain code.

### Why it would be awesome to work with us.

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...). 

### Contact

Email: dungnguyen@fetch.tech
Skype: dungphuongdh
Telegram: JunnieNguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
