### ISSUE TITLE
[Groove Technology] - [Mid level React native] - [Ho Chi Minh City] - [FT]

### ISSUE THREAD

**Issue by Nguyenphong1226** [awesome-jobs/vietnam#2096]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Negotiable

## Requirements
* Strong proficiency with JavaScript
* 2 years+ of experience of React Native

### Must Have
* Javascript
* React Native

### Responsibilities

* Development focused mobile application projects, javascript web projects
* Analyze the customer needs and design, document, test, and develop software as required to satisfy the functional and non-requirements.
* Reporting to the Project Manager and Technical Lead
* Delivering fully implemented vertical feature sets based on the specification within estimates and without defects.
* Identify and mitigate risk in the implementation of the project.
* Participating in code reviews.

### Why it would be awesome to work with us
* International, dynamic, friendly working environment.
* Clear and stable career growth
* Many opportunities for personal and professional growth.
* Regular team building events, sport activities…
* Medical and Accident Insurance program
* Professional training
* Competitive and attractive salary

### Contact
* Email: Phong.nguyen@groovetechnology.com
* Title: [React native] - Your Name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
