### ISSUE TITLE
Viet Nam Wacoal - .NET Developer - Dong Nai Province - FT

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#2101]
## Location

* Bien Hoa, Dong Nai Province

## Salary Expectation

* Negotiable

## Requirements
* Under 30 years old, graduated from University
* Proficient in programming .NET Webform, Winform or C #, ASP.NET, Java, VBA
* Good use of database management system: MySQL, MSSQL,...
* Experience in building and administering websites, designing Responsive Web (Desktop + Mobile)
* Priority for candidates who are staying in Bien Hoa, Dong Nai

### Must Have

* Proficient in programming .NET Webform, Winform or C #, ASP.NET
* Experience in building and administering websites, designing Responsive Web (Desktop + Mobile)

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Design and administer internal website
* Programming and developing a number of applications, integrated modules to serve production needs
* Some work under the assignment of management

### Why it would be awesome to work with us
* Working 270 days / year (~ 22.5 days / month)
* Negotiable salary, annual bonus from 2.4 ~ 3.6 month salary
* Fully complying with insurance and annual leave policies as prescribed
* Get regular checkups and cancer screening every year
* Tuition fee support
* Participate in training programs on professional skills and management skills
* Visiting tourism, participating in entertainment activities organized by the Company
* Some other policies are implemented at a level higher than the prescribed level by the Law,...
* There is a shuttle bus for staff in Ho Chi Minh City

### Contact
Email: huykhanh.tran3108@gmail.com
Detailed information: https://bit.ly/3gzR3J1

**Comment by qcam** [comment]
Hello, thanks for posting but we currently don’t accept jobs from head hunters
