### ISSUE TITLE
QUOD AI - Data Analyst Intern - Singapore - FT

### ISSUE THREAD

**Issue by imtrieeu** [awesome-jobs/vietnam#2102]
## Location

* Singapore

## Salary Expectation

* At market rate

What if every software engineer could hold 1 billion lines of code in their head? 
How would it change the way we build software? 
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create the first AI assistant for software engineering team. Our first product translates raw source code into natural language to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

### <p align="center">Quod AI Team</p>

<img src="http://bit.ly/quod-ai-photo-team" alt="Quod AI Team" width="600" />

Our team has ex Silicon Valley engineers and award-winning AI researchers from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.

<img src="http://bit.ly/quod-ai-logo-schools" height="40" />

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

<img src="http://bit.ly/quod-ai-logo-investors" height="40" />

### What will I do 🙋‍♂‍🙋‍♂‍🙋‍♂‍?

* Interpret source code, analyze results and provide ongoing reports
* Identify, analyze, and interpret trends or patterns in complex data sets

### What do I need 🧐? 

* Some technical expertise regarding one programming language and web or mobile software development (Javascript preferred)
* Strong analytical skills with the ability to collect, organize, analyze, and disseminate significant amounts of information with attention to detail and accuracy
* Adept at queries, report writing and presenting findings

### Education and Experience 🎓

* Studying towards university degree in computer science or similar education.
* Strong verbal and written communication skills in English.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
