### ISSUE TITLE
Autory - Mid or Senior React Native - Remote (Fulltime/Parttime)

### ISSUE THREAD

**Issue by theavatar7** [awesome-jobs/vietnam#2105]
## Location

* Remote

## Salary Expectation

* $1000+/month

## Requirements
* Proficiency with JavaScript/Typescript.
* At least 2+ years in React Native development.
* Familiar with iOS/Android development.
* Familiar with code review / github pull request process.
* Write clean code, follow existing coding convention (or contribute idea for improvements).
* Self-discipline.

### Must Have

* JavaScript/Typescript
* React Native
* Basic understanding on iOS/Android development.

### Ideally

* Experience with iOS/Android development to ensure high app performance.

### Responsibilities

* In charge to develop mobile app in React Native.

### Why it would be awesome to work with us
We are a small team with many years experience in software engineering and automotive industry. We are starting a brand new enterprise SaaS startup.
* Fully remote.
* Flexible working hours, we care about result and let you decide how to get there (of course with support from us).

### Contact
email: admin@autory.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
