### ISSUE TITLE
B&K Software - Ruby On Rails Developer - Ha Noi - Ft

### ISSUE THREAD

**Issue by hongloc5998** [awesome-jobs/vietnam#2106]
## Location

* Số 3, ngõ 78 Duy Tân, Phường Dịch Vọng Hậu, Quận Cầu Giấy, Thành phố Hà Nội

## Salary Expectation

* Negotiable/month or range

## Requirements
* Have at least 2 years working on Ruby on Rails.
* Proficient use Javascript, HTML and CSS.
* Experience in git and gitflow.

### Ideally

* Experience in Amazon Web Services (AWS) is the plus point.
* Experience in restful work and services like google, facebook is the plus point.

### You’ll be responsible for

* Analysis of system requirements, system design.
* Providing optimal technical solutions, solving problems.
* Carry out development work.
* Always improve productivity and quality of yourself.

### Why it would be awesome to work with us:
* Attactive salary agreed upon capacity.
* Review salary twice/year.
* Recognition and rewards based on your performance.
* Creative, modern and open working place.
* Continuous and professional training to fully develop your potential.
* Enjoying good remuneration of company becoming an employee: social insurance, annual company trip, 13th salary, End Year bonus,…

### Contact
Homepage: https://bnksolution.com
Email: hongloc5998@gmail.com
Title: Your Position - Your name

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
