### ISSUE TITLE
FETCH TECHNOLOGY - Junior/Senior React JS - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2107]
![image](https://user-images.githubusercontent.com/60914247/92566168-fdcfc880-f2a5-11ea-857a-843158153d44.png)

## Requirements
* At least 1-year experience (junior) and 2.5-years experience (senior) of working as frontend developer.
* Proficient in React stack (ReactJS, Redux, State Management, Functional Programming).
* Expert knowledge with HTML5, CSS3, SASS/SCSS.
* Solid knowledge of modern web development technologies & framework based on JavaScript, HTML, CSS.
* Expert with developing responsive layouts leveraging CSS and media queries.
* Design and implement robust client-side solutions with RESTful API.
* Strong competency in responsive, mobile-first layouts leveraging CSS and media queries.
* Intermediate level of comprehension of the english language.

## Responsibilities

* Build new software front end for advanced user experience.
* Build reusable components/modules for static websites with responsive design.
* Work with API endpoints for dynamic content updating.
* Ensure UI/UX of developed pages and software with near pixel-perfect design.
* Develop and optimize front end UI to ensure the application is rendered consistently in cross-browser environments.
* Cooperate to connect front end software development with expert backend team.

## Why it would be awesome to work with us ?
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Weekly Sport Day (Football, Badminton...), Monthly Team-building, Company trip, Play Game (PlayStation, Board Games). 

## Contact:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by Jesse111-flyaway** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

Thanks for your information. This job is from our company, my email is belong to company email (fetch.tech), not personal email.
