### ISSUE TITLE
Cinnamon AI - Front-end Developer - HN/HCMC - FT 

### ISSUE THREAD

**Issue by NgHLien** [awesome-jobs/vietnam#2111]
## Location

* 36 Hoang Cau, Hanoi, Vietnam
* Ton Duc Thang, Dist 1, HCM, Vietnam

## Salary Expectation

* $1000 - 3000/month

## Requirements

* Deep understanding of JavaScript and its core concepts (object prototype, callbacks, events loop, throttling, memoization, immutability, promises…).
* Proficient in DOM manipulations concepts: events bubbling, ShadowDOM..
* Good understanding of SPA (Single Page Application) (experienced with React.JS and its ecosystem is a plus).
* Good at using Chrome DevTools: debugging, profiling...
* Good understanding of modern web protocols (HTTPS, WebSocket, Web Workers, Caching…).
* Experienced with modern build tools (Webpack, Parcel,...) and different bundling techniques (lazy-loading, tree-shaking, cache busting, polyfills, environments splitting, modules resolution (AMD/UMD/CommonJS)...) to improve cross-browser compatibilities and performance.
* Good knowledge of JavaScript Transpiler (Babel).
* Proficient in NodeJS.
* Good understanding of VCS – Version Control System (Git).
* Understanding of UI/UX design.
* Experience of building Web UI from scratch
* Experienced with SASS, Stylus, SCSS
* Good command of English

## Responsibilities and Performance Objectives

* Develop performant web applications.
* Build reusable code and libraries for future use.
* Ensure the technical feasibility of UI/UX designs.
* Collaborate with stakeholders.

## Why it would be awesome to work with us
* High-tech spaceship with laptop provided. GPU, AWS all are ready for model training.
* Flexible working time: 3 days remote working online monthly.
* Wide ranges of internal community events to promote connections and healthy life, including Happy Monday, Company Trip, 10++ Health Clubs (Running, Swimming, Football,...) with free snacks and drinks.
* Talent development & innovation encouragement at our core through these programs: Cin Sota, Give Me 10%,...
* Great opportunity to access and acquire top expert knowledge and experiences internally and externally
* Competitive salary range.

## Contact

* Submit CV to: talent@cinnamon.is
* Website: [https://cinnamon.is/](url)
* Facebook Fanpage: [https://www.facebook.com/cinnamonai/](url)
* Brief Introduction: [bit.ly/Cin_Brochure2020](url)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
