### ISSUE TITLE
Cinnamon AI - Project Manager - HN/HCMC - FT 

### ISSUE THREAD

**Issue by NgHLien** [awesome-jobs/vietnam#2112]
## Location

* 36 Hoang Cau, Hanoi, Vietnam
* Ton Duc Thang, Dist 1, HCM, Vietnam

## Salary Expectation

* $850 - 3500/month

## Requirements

* Strong in negotiation, communication skills, complex problem solving, problem sensitivity, time management, management of personnel resources.
* Attention to detail and multi-tasking skills.
* Strong verbal and written expression.
* English (speaking, listening, reading, writing) and Business-professional.
* Minimum 3 years of working experience in project management (especially in defining requirements by understating business needs).
* Experience in software development with Scrum and Kanban.
* Understanding all aspects of the software life cycle, using Agile or Waterfall software development practices.
* Experience with modern project management tools.
* Experience in making proposals and defining requirements about systems, especially  for open systems.
* Motivation and challenging spirits for new service and technology.
* Critical thinking, teamwork mindset and service orientation (actively seeking for ways to help people).
* Active listening to people, active learning about the AI industry.

### Plus

* PMP certification 
* AI technology knowledge

## Why it would be awesome to work with us

* High-tech spaceship with laptop provided. GPU, AWS all are ready for model training.
* Flexible working time: 3 days remote working online monthly.
* Wide ranges of internal community events to promote connections and healthy life, including Happy Monday, Company Trip, 10++ Health Clubs (Running, Swimming, Football,...) with free snacks and drinks.
* Talent development & innovation encouragement at our core through these programs: Cin Sota, Give Me 10%,...
* Great opportunity to access and acquire top expert knowledge and experiences internally and externally
* Competitive salary range.

## Contact

* Submit CV to: talent@cinnamon.is
* Website: https://cinnamon.is/
* Facebook Fanpage: https://www.facebook.com/cinnamonai/
* Brief Introduction: bit.ly/Cin_Brochure2020

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
