### ISSUE TITLE
LARION – Senior Python Developer - HCMC - FT

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#2113]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 1500$ - 2500$

## Requirements

* At least 3 years of working experience with Python
* Working knowledge with databases
* Should be able to write clean, scalable codes
* Good logical thinking and critical thinking in handling process and requirements
* Have entrepreneurial spirit and willingness to share training with colleagues

### Responsibilities

We are looking for a great and proficient Python developer. You will be one of the key contributors in our organization and develop high quality financial system solution following well-known Python workflows and best practices. Being our developer, you will focus to:

* Understand and analyze the requirements / designs clearly
* Implement features from design specifications and deliver code with high quality
* Perform code review, code refactor
* Ensure components and the overall application are robust and easy to maintain
* Contribute to all aspects of the product development process, from specification and design, throughout integration, release and maintenance
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency

### Why it would be awesome to work with us

* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, etc.

### Interesting engineering projects

* You'll join our FinTech project that will specialize in building a real-time system to proceed, manage and analyze data of US stock market

### Contact

* Please send CV via email: ngocttb@larion.com
* For further information, please contact via Skype: ngoctranthibao / Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
