### ISSUE TITLE
VHEC - Java Leader - Hanoi - Fulltime

### ISSUE THREAD

**Issue by oanhtran2710** [awesome-jobs/vietnam#2114]
## Location:

* 23rd floor, Viwaseen Office Building, 48 To Huu, Trung Văn Ward, Nam Từ Liêm District, Ha Noi

## Requirements:

- Experience in standard Java development.

- Exposure to the Spring Framework

- Creative and forward thinking

- Exposure to web services technologies (HTML/SOAP/REST)

- Databases (JDBC/SQL)

- Knowledge of versioning Source Control systems (CVS/Git)

- Good experience in Object Oriented design and development.

- Experience in the use of Java application servers (Tomcat/JBoss)

- Fault diagnosis and resolution experience.

- Excellent spoken and written English.

### Preferred skills / experience

- A knowledge of the rental order processing lifecycle

- Unix/Windows knowledge (SSH/SCP).

### Best about this position:

- Salary review: 1 time/year based on employee's performance and contribution

13th salary.

- Annual company trip, health check-up.

- Free parking.

- Professional and motivated team.

- Social – Health – Insurance paid fully.

- Mon -Fri

### Contact
Email: tranhoangoanh27@gmail.com
Skype: hoangoanh2710@outlook.com
Job description: **https://topdev.vn/s/7wt0ZVTL**

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
