### ISSUE TITLE
AdvaHealth Solutions - QA Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by lynnielyn** [awesome-jobs/vietnam#2115]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,600 to $2,000 USD

## Requirements

* Diploma or Certificate in Computer Science 
* Knowledge of QET/QA methodology & software development processes (Agile, Scrum etc)
* Extensive knowledge of leading and managing test activities and resourcing
* Extensive experience with various types of testing including unit, component, integration, system, performance, user acceptance, reliability, usability, and exploratory testing 
* Ability to communicate effectively in English and Vietnamese
* 4+ years QA testing experience

### Must Have 

* Teamwork
* Good communication 
* Handle pressure

### Ideally

* Experience in managing test automation framework.
* Experience in developing automated tests.
* Experience and knowledge of working with JIRA and Testlink.

### Responsibilities

* Specifying, designing, implementing, and evolving our automated test framework to achieve higher test throughput with increased accessibility and test execution flexibility 
* Develop detailed, comprehensive and well-structured test plans and test cases 
* Develop and apply testing processes for new and existing products to meet software requirement needs 
* Review system requirements and track quality assurance metrics 
* Estimate, prioritise, plan and coordinate testing activities
* Identify, record and document thoroughly to be able to track bugs
* Conduct system diagnostic analysis and troubleshooting to identify areas for continuous improvements and resolve complex software issues 
* Stay up-to-date with new testing tools and test strategies

### You’ll be responsible for

* Testing new features for our products

### Why it would be awesome to work with us

We are a HealthTech Software Development Company who have a desire to take over the world! Our products are used within the healthcare industry to provide for better patient outcomes for the community. We are spread between Vietnam and Hong Kong and already have clients and leads in HK, Australia and New Zealand.
We are a company with a strong team culture and our management team is very supportive and we care about our people. Don't be fooled, we work hard, but we also play hard!

### Interesting Projects

* Link to connect a health service to a provider

### Contact

Homepage: advahealthsolutions.com
AdvaHealth Solutions: lynette_dot_fong_at_advahealthsolutions_dot_com

**Comment by lynnielyn** [comment]
Total noob, please be kind!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
