### ISSUE TITLE
Lecle Vietnam - Senior Front-end Developer (ReactJS, JS) - HCMC

### ISSUE THREAD

**Issue by uyennguyenhr** [awesome-jobs/vietnam#2116]
## Location
* Saigon, Vietnam
* District 1

## Requirements
* 5+ years of experience
* In-depth knowledge of HTML5, JavaScript/ReactJS and CSS3
* Solid understandings of Web Technologies: HTTP, AJAX, RESTful API
* Ability to adapt to web frameworks and implement them in ongoing projects
* Understanding of how Scrum and Agile work
* Profound understanding of Version control systems (Git)
* Eagerness to learn new technologies and programming languages
* Good English skills

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + KPI bonus at the end of the year
* 15 days of annual leave per year
* Onsite opportunity in Korea
* Company trip at least once a year, monthly company parties & other Teambuilding activities
* Free coffee, snack and drinks

JD for detail: https://smrtr.io/4p7Pk

## Contact
Phone: 028-6295-8827
Send your CV to email: career@lecle.co.kr

## Know more about us
Facebook: https://www.facebook.com/LecleVietnam/
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
