### ISSUE TITLE
CREATORY - Front-end Developer - HCMC - FT 

### ISSUE THREAD

**Issue by NgTTrg** [awesome-jobs/vietnam#2117]
## Location

* Ho Chi Minh City, Vietnam
* Full-time

## Salary Expectation
* $1,500 -$2,800 / month in Gross

## Main Skills
* JavaScript 
* ReactJS, Redux
* 4+ years Software Engineering experience

### Specialty
- 3+ years of **JavaScript** experience, including concepts like asynchronous programming, closures, types, and **ES6**
- 2+ years experience with **React.js** and **Redux**
- Strong experience with HTML/CSS, including concepts like layout, specificity, cross-browser compatibility, and accessibility.
- Experience in developing hybrid apps based on iOS and Android.
- Solid knowledge of ES6, ES2016
- Strong understanding of browser **APIs** and optimizing front-end performance.
- Comfortable with GIT and use of terminal
- Familiar with current trends and best practices in front-end architecture, including performance, security, and usability

### Ideally
- Strong technical background in Python and/or Node.js, Webpack is a strong plus
- Knowledge of TypeScript
- Familiarity with Linux
- Comfortable working with python/spring backends
- Interest in building software Artificial Intelligence products
- Excellent communication in English.

## You’ll be responsible for
AI / Machine Learning is nothing without data and human interactions. Interactions happen through front-end interfaces. The truth is: an interface can make or break a machine learning system. To collect data and train machine learning systems, we need high-quality interfaces for both: human annotators and end-users. To build next-generation systems that can learn and be taught requires building next-generation interfaces to make this happen. Are you a front-end developer who is interested in AI/machine learning?

### You can bring
As the **first dedicated front-end engineer**, you will lead the way in defining the frontend culture for CREATORY. You will do this and you should be ready to do this:

- Web portal and mobile app development.
- Architect efficient and reusable front-end systems that drive complex web applications.
- Implement features and user interfaces - including analytics dashboards for admin and other screens related to common web community concepts.
- Collaborate with Product Designers, Product Managers, and Software Engineers to deliver compelling user-facing products.
- Identify and resolve performance and scalability issues.
- Create, from scratch, unit test, code release, and deployment processes.
- Own the front-end implementation of our products, end to end

### We may need

* Resume
* Detailed Project: Skills based on the experience of the project (project name, duration, work performed, project contribution, URL, etc.)
* Portfolio or samples of work demonstrating your project

## Why it would be awesome to work with us
Our World-Class company culture leads the way people in CREATORY work, grow and live. We WORK together in a happy environment, which help us to GROW and value our LIVES under the light of 3 main values: **Envisioning, Transformation, Excellence** and 7 cultures which are:
1. Dare to dream big
2. Evolve through learning
3. Positive and passionate
4. Practice transparency and candor
5. Turn customers into raving fans
6. Help others rock their greatest lives
7. Honor my words with action

Self-Evolution & Ownership of work & productivity are all that we care about. CREATORY doesn’t need people to obey working time of 9-6, we don't force them to stay serious on their seat all day. They are given the power to choose what makes them comfortable and willing to come to the office every morning.

### Other cool things
- Guaranteed 13th-month salary.
- Annual salary review.
- Additional Health insurance.
- Learning & Development opportunities. 
- Team outing & bonding activities. 
- Contribution awards...etc

## Contact
Homepage: https://www.creatory.vn/en/career/
Email: hrs@creatory.vn  |  trang.nguyen@creatory.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
