### ISSUE TITLE
VinID - Back-end Engineer (Golang/Java) - SG - FT

### ISSUE THREAD

**Issue by khanghldk** [awesome-jobs/vietnam#2118]
## Location
* Five star tower 28 biz Mac Dinh Chi, District 1, HCMC, Vietnam
* Full-time

## Job Description
* We are looking for an experienced Back-end Developer to join our product team to build an “Amazing Super App” VinID: Fintech, Loyalty, Ticketing, Platform, Health care, Retail, Home services…
* Be part of an agile team designing and developing high-performance components/micro-services for a wide range of digital transformation projects
* You will be inspired by not our Tech start-up culture, but our talent co-workers and the cutting-edge technologies we applied
* Work with our CI / CD process and give suggestions to improve it
* Monitor and improve the scalability and security of current systems

## Requirements
* 2-3 years of experience in one of the following languages: Go or Java
* Good at Algorithm is a big plus
* Experience with RESTful APIs, Microservices
* Experience with Docker/Kubernetes and Cloud Infrastructure is a plus
* Proactive attitude and good communication skills

## Why it would be awesome to work with us
* Attractive compensation package (you’ll love it)
* 13th salary and target incentive (up to 1,5-month salary), rewards for achievements, initiatives and good deeds
* Performance review 2 times/ year
* Annual leave: 15 – 20 working days/year and Other leaves/public holidays in accordance with the Labor Law of Vietnam
* Periodic medical checkup, Health/Social Insurances & Bao Viet Insurance
* Benefits for employees using services at VinID, Vinmec, Vinpearl, Golf, Safari, Vinmart and Vinschool…
* Agile working environment, no dress code (it’s your choice to be confident and comfortable)
* Training courses: The Company will provide customized training courses according to business needs, Udemy, Coursera, Linkedin Learning are available upon your request
* Team building, staff retreats and summer camp for excellent employees’ children
* Gym area, football club, running club, ...

### Contact
Homepage: [http://career.vinid.net](http://career.vinid.net/)
Mail: khang.ha@onemount.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
