### ISSUE TITLE
Parcel Perform - QA/QC Engineer (Manual Tester) - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#2120]
![Vietnam](https://user-images.githubusercontent.com/49466111/93553154-803e4380-f99c-11ea-95a8-d113304d74da.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $800 - $1,200

## Requirements
We at Parcel Perform believe in innovation, energy, and resourcefulness for everything we do. We will not stop to deliver an outstanding product that we can be proud of and need you to help us to inform the world. You need to feel the same way about our offering and bring along the following things:

## Skills
* At least 2-3 years of experience as core tester
* Must have experience in test web services, API using tools like postman, SOAPUI
* Experience with manual testing techniques for web
* Experience with desktop and mobile testing
* Solid test plan and test case writing skill
* Excellent understanding of SDLC and quality process
* Excellent oral and written communication skill
* Having solid knowledge of testing design techniques and testing strategies
* Familiar with Agile projects, able to work in fast-paced project cycle by adapting to ambiguous project objectives, changing requirements, and re-prioritized testing focus.
* Able to read, write, and speak English, and communicate effectively with both technical and non-technical co-workers.
* Experience with test automation for web is plus

### Must Have
* Experience in test web services, API using tools like postman, SOAPUI

### Responsibilities
As a QA Engineer, you will be responsible for working closely with our development and business teams to ensure excellent quality of software products and meeting user requirements. We choose microservices for technology freedom, resilience, and scalability, though there will be lot of communication between services and tons of metrics we need to keep an eye on.
Such systems aren’t easy. But that is ok. We aren’t here for ease anyway. We are here for people who want to operate at the next level in their careers. The successful candidates will join the existing QA/QC team and will take part in designing and developing testing capabilities. This includes maturing, as well as executing and maintaining the current testing logic.

### Why it would be awesome to work with us
* The opportunity to work in a fast-growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing, and focuses on succeeding - we
continuously work with you on your strengths and weaknesses across many important
dimensions, and look at ways for you to address them and further your development
* Your entry ticket into being part of the Parcel Perform startup Universe, where you will work with and alongside people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast-growing company like competitive salary, extra insurance, free lunch, free fruit, snacks, cool oﬃce, team bonding events, various training programs, and more.

### Interesting engineering projects
You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide.

### Contact
Please apply on our career site: https://parcelperform.freshteam.com/jobs/FxO62P5gzP0v
Or drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)
Find more jobs and further information about our company: https://www.parcelperform.com/careers

![Date of Arrival Predictions Banner (2)](https://user-images.githubusercontent.com/49466111/93553682-d1026c00-f99d-11ea-92d6-63fa02132704.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
