### ISSUE TITLE
Fonos - Lead Developer - Saigon - FT

### ISSUE THREAD

**Issue by oscarjes** [awesome-jobs/vietnam#2121]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1800 - 2500/month

## Requirements
* NodeJS
* ReactJS
* AWS
* PostgreSQL
* 5+ years Software Engineering experience

### Who you are
_This role might be for you if..._

* **You love taking on new challenges.** Life at an early stage startup can be chaotic and require you to tackle different kinds of problems each week. You thrive in such an environment and enjoy getting to deal with new challenges.
* **You want to develop your leadership skills.** You'll work directly with our CEO to build out the developer team at Fonos. You'll have a chance to develop and improve your leadership abilities.
* **You like small teams.** Even though Fonos is growing very quickly, we don't plan to have a lot of employees in the upcoming future. We prefer small teams of excellent people. You like working at smaller companies, where each individual can contribute a lot.
* **Both your written & spoken English are very good.** You'll be working directly with our CEO, who doesn't speak Vietnamese, so it's important for you two to be able to communicate well.
* **You're hard working.** We're an early stage startup and everyone on our team has to pull their weight. We move quickly and need team members who are able to keep up.

### You’ll be responsible for

You'll be the lead developer on our team and work directly with our CEO, who is also a developer. You'll help us build out the tech team as we grow and you'll be directly responsible for the developers we hire in the future to work below you. We're looking for someone that has already worked in positions as a team & project leader and is now ready to take on the challenge of building a tech team from scratch at a high-growth startup.

We're building an amazing app that is loved by customers and your technical know-how will be key in helping us reach that goal. We won't just need your help with building new features but also optimizing existing systems, improving performance, and deal with technical debt.

This is a role for someone who enjoys the challenge of both setting up new systems and optimizing and scaling existing ones. You'll have a diverse set of challenges to tackle every day: whether it's dealing with AWS, fixing issues with Apple IAP, or improving app performance.

### Who we are

At Fonos, we're building the best audiobook & audio content app for Vietnam. We're partnering with the largest book publishers in the country to create audio versions of best-selling local and international books. We're also creating the best original content such as meditations, sleep stories, book summaries, and more.

We're early-stage and backed by amazing local and international investors (such as [Thai Van Linh](https://www.facebook.com/linhthaiofficial) and a fund from Silicon Valley). Oscar, our co-founder and CEO, has many years of experience working in marketing and programming roles for startups in the US and UK. Xuan, our second co-founder & COO, is an accomplished entrepreneur having built a successful F&B chain that now has locations both in Vietnam and Korea.

### Why it would be awesome to work with us

* **Exciting challenges.** You'll be our lead developer and you'll be able to help us take this startup from the early stage to a large successful tech company. You'll have a chance to show and develop your leadership and technical skills.
* **Flexibility.** Even though we have an office in District 7, we don't expect you to go to the office everyday. Instead, we will meet from time to time and otherwise communicate over Slack or WhatsApp. You're free to work from the office, a co-working space, or even from home. We care about results and getting work done, not about time spent in the office.
* **Career opportunities.** Being a lead developer at a high-growth startup will put you in a great position for your future, whether you decide to stay and grow with us as we keep scaling, start your own project or work at a large company.
* **You'll be able to contribute.** You'll be a key employee at Fonos and you'll be able to contribute to the direction of business in many ways, not just when it comes to technical aspects.

### Contact
* Email: oscar_at_fonos.vn
* [Website](http://fonos.vn/)
* [Facebook](https://www.facebook.com/fonosvietnam/)
* [Fonos on iOS App Store](https://apps.apple.com/vn/app/fonos/id1491002000?l=vi)
* [Fonos on Google Play](https://play.google.com/store/apps/details?id=vn.fonos.mobile&hl=vi)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
