### ISSUE TITLE
Fonos - React Native Developer - Saigon - FT

### ISSUE THREAD

**Issue by oscarjes** [awesome-jobs/vietnam#2122]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1200 - 1800/month

## Requirements
* React Native
* 2+ years Software Engineering experience

### Who you are
_This role might be for you if..._

* **You want to do work you can be proud of.** We're aiming to build an amazing app, not just one that is good enough. You're someone who takes pride in creating an exceptional product.
* **You love taking on new challenges.** Life at an early stage startup can be chaotic and require you to tackle different kinds of problems each week. You thrive in such an environment and enjoy getting to deal with new challenges.
* **You like small teams.** Even though Fonos is growing very quickly, we don't plan to have a lot of employees in the upcoming future. We prefer small teams of excellent people. You like working at smaller companies, where each individual can contribute a lot.
* **Both your written & spoken English are very good.** You'll be working directly with our CEO, who doesn't speak Vietnamese, so it's important for you two to be able to communicate well.
* **You're hard working.** We're an early stage startup and everyone on our team has to pull their weight. We move quickly and need team members who are able to keep up.

### You’ll be responsible for

You'll be our first full time in-house React Native developer (we've been working with freelancers so far). You'll work closely with our tech lead, who will be focusing on the backend. We have very high standards for our app and you will be a key person to help us create an amazing product and an app that users love.

You'll have a chance to be a key player in our development team as our company grows with many opportunities for career advancement if you prove yourself.

### Who we are

At Fonos, we're building the best audiobook & audio content app for Vietnam. We're partnering with the largest book publishers in the country to create audio versions of best-selling local and international books. We're also creating the best original content such as meditations, sleep stories, book summaries, and more.

We're early-stage and backed by amazing local and international investors (such as [Thai Van Linh](https://www.facebook.com/linhthaiofficial) and a fund from Silicon Valley). Oscar, our co-founder and CEO, has many years of experience working in marketing and programming roles for startups in the US and UK. Xuan, our second co-founder & COO, is an accomplished entrepreneur having built a successful F&B chain that now has locations both in Vietnam and Korea.

### Why it would be awesome to work with us

* **Work you can be proud of.** Fonos helps people read more books and you can be one of the people who help us achieve that mission.
* **Exciting challenges.** You'll help us take this startup from the early stage to a large successful tech company. You'll have a chance to show and develop your leadership and technical skills.
* **Flexibility.** Even though we have an office in District 7, we don't expect you to go to the office everyday. Instead, we will meet from time to time and otherwise communicate over Slack or WhatsApp. You're free to work from the office, a co-working space, or even from home. We care about results and getting work done, not about time spent in the office.
* **Career opportunities.** Being the first React Native developer at a high-growth startup will put you in a great position for your future, whether you decide to stay and grow with us as we keep scaling, start your own project or work at a large company.
* **You'll be able to contribute.** You'll be a key employee at Fonos and you'll be able to contribute to the direction of business in many ways, not just when it comes to technical aspects.

### Contact
* Email: oscar_at_fonos.vn
* [Website](http://fonos.vn/)
* [Facebook](https://www.facebook.com/fonosvietnam/)
* [Fonos on iOS App Store](https://apps.apple.com/vn/app/fonos/id1491002000?l=vi)
* [Fonos on Google Play](https://play.google.com/store/apps/details?id=vn.fonos.mobile&hl=vi)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
