### ISSUE TITLE
FETCH TECHNOLOGY - Senior Backend (Python) - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2123]
![image](https://user-images.githubusercontent.com/60914247/93869839-93337980-fcf6-11ea-92a6-41e124eaef77.png)

#  HCM - Dist 3

#  1,300 - 1,800 USD

## Requirements
* At least 3 years working as the position of Back-end Developer.
* Having an eagerness to learn new things.
* Willing to work with Python and ReactJS.
* Good understanding of web/app development process (planning, development, implementation).
* Having strong knowledge about databases and systems: MySQL, MongoDB, Redis.
* Ability to work well in high speed environments with a lot of pressure;
* Experience building software from scratch.
* Management Experience.
* Having experience working as a Fullstack Developer.
* Having experience with Javascript front-end framework, especically working with ReactJS.
* Having a Portfolio and many side projects.
* Having high GPA, knowing Golang.

## Responsibilities

* The Senior Back-end Developer will be responsible for building and managing web pages and various website applications. You will use back-end coding languages, development frameworks and third-party libraries. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. You will also be collaborating with the other team members such as the Content Team as well as the Design Team to refine the website and fix the technical issues.

* Participate in the entire process of product development: analyze, design system, code and debug on demand.
* Design detailed technical plans for projects based on requirements from business teams.
* Integrate with backend services, give constructive feedbacks on UI/UX/API design to create a high quality web app for end-users.
* Write clean and maintainable codes, with frequent code-reviews performed to a best practice standard.
* Good attitude, problem-solving and communication skills, not afraid of new challenges.

## Why it would be awesome to work with us?
* Competitive Salary & Stock Options.
* Highly motivated in the working environment.
* Performance review every 3 months.
* Salary + Bonus base on your performance.
* Allowance: Lunch, Dinner, parking fee, tel Card.
* Social insurance, medical insurance and unemployment insurance in line with Labor Law.
* Yearly company trips.
* 13th salary and bonus.

## Contact:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
