### ISSUE TITLE
FETCH TECHNOLOGY - Senior Cloud & Back-end Engineer - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2124]
![image](https://user-images.githubusercontent.com/60914247/93870767-e5c16580-fcf7-11ea-876e-0d0dbb5998ea.png)

## Requirements

* Strong interpersonal and communication skills. Experience in a startup or high-growth environment.
* Capable of working with ambiguous requirements and minimal direction. 
* 4+ years of experience design and develop complex development projects through all phases of the system development life cycle. 
* Over 2+ years of experience in Golang, Python. Excellent coding and problem - solving skills with ability to work as a Developer.
* Good hands-on experience in designing, developing, implementing and deploying applications on cloud using AWS (Cognito, EC2, RDS, Glue, ...).
* Experienced in handling IoT data systems.
* Experienced with Linux operating system principles and network layer protocols.
* Experienced in using Agile, SCRUM methodology to deliver the projects.
* B.S. in Computer Science or equivalent.
* Solid software engineering background, with 6+ years of experience developing enterprise-scale commercial products. 
* Strong experience with both back-end and front-end technologies.
* Strong knowledge of modern cloud architectures and technologies.
* Throughout understanding of IT concepts including networking, distributed computing, database, data structures, application development techniques and testing techniques. 
* Commercial mobile healthcare experience (mHealth experience). 
* Passionate, inspired by Earable’s mission and products.

## Responsibilities

* Drive the implementation of development activities.
* Work directly with the engineering director and product manager to understand high-level requirements and develop system architecture and design. 
* Create and drive the detailed planning, scheduling and execution of development plans to meet business goals and schedules. 
* Help define and enforce development practices, including unit tests and code reviews.
* Promote and drive innovation in technologies, processes, and tools. 
* Mentor and develop team members.

## Why it would be awesome to work with us
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Weekly Sport Day (Football, Badminton,…), Monthly Team-building, Company trip, Play Game (PlayStation, Board Games).

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
