### ISSUE TITLE
QUOD AI - Full Stack Engineer - HCMC - FT

### ISSUE THREAD

**Issue by hroussel** [awesome-jobs/vietnam#2126]
<p align="center">
  <img src="https://uploads-ssl.webflow.com/5e5cb288c9fe845aa6a23577/5e61f580280007c802c95ac7_quod-ai-logo.png" alt="Quod AI logo"/>
</p>
<p align="center">Singapore, Vietnam | Engineering & Applied Sciences</p>

# Full Stack Engineer 

What if every software engineer could hold 1 billion lines of code in their head? 
How would it change the way we build software? 
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create the first AI assistant for software engineering team. Our first product translates raw source code into natural language to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

### <p align="center">Quod AI Team</p>

<img src="http://bit.ly/quod-ai-photo-team" alt="Quod AI Team" width="600" />

Our team has ex Silicon Valley engineers and award winning AI researchers from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.

Opportunities to be mentored by our Ex Silicon Valley CTO 😉

<img src="http://bit.ly/quod-ai-logo-schools" height="40" />

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

<img src="http://bit.ly/quod-ai-logo-investors" height="40" />

### What will I do 🙋‍♂‍🙋‍♂‍🙋‍♂‍?

* Use HTML, CSS, JavaScript, and React to create the frontend of a web application
* Use Node.js to create the backend of an application and connect it to a frontend
* Developing backend website applications
* Use MySQL, ElasticSearch to create databases for content and data management
* Maintain and review code for fellow team members
* Meeting both technical and customer needs

### What do I need 🧐?

* Strong skills with Javascript.
* Relevant experience with Google Cloud or AWS is a plus.
* Superior analytical, conceptual and problem-solving skills.
* The ability to learn and iterate quickly.
* An obsession with agile and lean principles (GitHub, Trello)
* Deep understanding of databases is a plus.
* Experience with Elasticsearch is a plus

### Education and Experience 🎓

* Recent graduates (0-2 years of experience)
* Studying towards a university degree in computer science or similar education.
* Strong verbal and written communication skills in English.
* Candidate must be Singaporean or PR.

### 📑 [Apply now](http://bit.ly/quod-ai-apply) 📑

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
