### ISSUE TITLE
InterGreat Education Group - Senior Drupal Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by Khanhtranf** [awesome-jobs/vietnam#2127]
## Location

* 20th Floor, ICON4 Building, 243A De La Thanh, Lang Thuong Ward, Dong Da District, Hanoi City

## Salary Expectation

* Up to $1,800/ month

## Requirements
* Having experience of any JavaScript front-end framework
* Good knowledge of Git, GitFlow
* Experienced third-party system connection: payment gateway, shipping …
* Write optimized SQL queries, interact on big data
* Ability to self-learn and adapt to new technologies quickly
* Ability to both collaborate with team members and to work independently
* Results-oriented, reliable, able to work under pressure

### Must Have

* Minimum 4 years working experience with Drupal 7, 8 (proven record via worked projects)
* Strong knowledge of PHP to develop web-based applications
* Solid experience with MySQL and writing efficient SQL queries for reporting
* Good experience with unit testing
* Good at JavaScript skills

### Ideally

* Comfortable working without routine supervision.
* A desire to remain technically capable and an expert in current technologies.
* Excellent personal organisation and ability to prioritise and carry out multiple tasks.
* Proven experience in leading and managing the delivery of system/software development projects in a structured environment.
* Experience in a variety of software development approaches and methodologies including Agile (Scrum).

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Custom programming and web application development for Drupal
* Testing, maintenance and troubleshooting of existing company sites
* Contributing ideas and efforts towards internal projects and working as part of a team to find solutions on various problems

### Why it would be awesome to work with us
* Annual salary review
* Annual leave, working conditions follow Vietnam labor laws
* Support for learning and certificate examination
* Annual Vacation: follows company’s policy every year
* International, dynamic, friendly working environment
* Have chance to build long term relationships with colleagues via multiple projects
* Plenty of food, all the time
* Other allowances: transportation allowance, lunch allowance, working on-site allowance, etc.
* Working time: Mon - Fri

### Contact
Email: huykhanh.tran3108@gmail.com

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
