### ISSUE TITLE
Yojee - Senior Mobile Developer - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#2128]
## Location

* District 4, Saigon, Vietnam

## Salary Expectation

* VND 50m - VND 90m gross per month

## About the role

Yojee is looking for a Senior Mobile Developer to join our Engineering team, to develop and maintain high quality mobile applications and support for the entire application lifecycle. This candidate should also appreciate the notions of their running efforts which will empower and enhance the logistic services for potentially millions of users across a wide variety of industries.

## Requirements

* Minimum Bachelor Degree in Computer Science or Computer Engineering or its equivalent related experience.
* Minimum 4-5 years of relevant work experience.
* 2-3 years of relevant experience in mobile development.
* Experienced and proficient working with Javascript, React Native and Git.
* Existing apps in app store or play store with considerable usage would be a huge bonus.
* Knowledge of Ruby on Rails, Elixir and being a polyglot is a strong advantage.
* Excellent understanding of the full mobile development life cycle.
* Effective written/oral communication skills and able to communicate ideas effectively to a corporate audience and excellent interpersonal skills.
* Able to work independently, self-directed and solutions-oriented.

## Responsibilities

* Design and build advanced logistics applications for the mobile apps/ platforms.
* Collaborate with cross-platform and product development teams to define interfaces and ensure feature interoperability.
* Write in unit-tests, integration tests, and interoperability test for our SDK and applications built on our SDKs.
* Identify performance improvements and efficiency optimizations for implementation, build, and deployments of the technology.
* Implement UI from specifications provided by the UX/UI team.
* Act in a developer support role for those implementing using our SDKs or White Label applications.
* Undertake any other ad-hoc work as assigned.
* May be required to perform other related duties as required.

### Reporting Structure - Who Will Help You Win

* This role will be located in Vietnam and will report to the Engineering Manager.

## Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..

## About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=75&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
