### ISSUE TITLE
Quick Vietnam - Web Developer - Remote - FT 

### ISSUE THREAD

**Issue by vkhang-truong** [awesome-jobs/vietnam#2129]
## Location

* Ho Chi Minh City
* Remote

## Salary Expectation

* $1,500 - $3,000

## Requirements
* Graduated from university with a major in information technology
* Japanese equivalent level N2

### Must Have

* Have 2 years of experience in developing back-end website, web system using ColdFusion, PHP or Ruby.
* Have 2 years of experience in using SQL Server database management system and Window server operating system.

### Ideally

* Experienced in back-end programming for systems such as order management and inventory management
* Have experience working in a Japanese company

### Responsibilities

Great power comes with great responsibilities!
* Responsible for a collaborative project on commercial sales website for contact lenses, and a project on back-end system (currently in use) used to operate a Japanese e-commerce website and Hongkong's core system.

### Why it would be awesome to work with us
* Work 7,5 hours
* Work from home
* Vacation according to the Japanese calendar and Vietnamese Lunar New Year

### Interesting engineering projects
* The company was established in 2003 in Japan and has branches in many countries, operates and owns the most popular selling websites for cosmetics and skincare products

### Contact
Email: vkhang.truong@gmail.com
Title: [Quick VN _ Web Dev]

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
