### ISSUE TITLE
Injective Protocol (Blockchain) - Senior Golang/Backend Engineer - Remote - FT

### ISSUE THREAD

**Issue by albertchon** [awesome-jobs/vietnam#2130]
## About Injective Protocol

At Injective Protocol, you'll have an opportunity to work at the bleeding edge of decentralized finance on products that will redefine our global financial markets. By joining us at this early stage, you will be able to have a high impact on the growth of Injective as well as advance the state of the art of DeFi. 

*  We are building a fully decentralized Layer-2 derivatives exchange that allows anyone to create and trade derivatives on any arbitrary market.
* We're a world-class team from Stanford and NYU Stern with top backers and advisors including Binance, Pantera Capital, StartX, QCP, and Hashed.

## Location

* Remote

## Salary Expectation

* Very Competitive
* Negotiable

## Requirements

* Strong command of the English language
* Worked on at least two production Golang codebases that are reasonably large and performant
* Strong knowledge of Go idioms and libraries
* Strong knowledge of CS fundamentals such as data structures and API design
* Strong understanding of blockchain

### Must Have 

* Ability to communicate technical concepts with other technical & non-technical team members
* Ability to learn quickly and work independently 
* Eager to learn, ownership mindset. 

### Ideally

* Experience with Cosmos-SDK/Tendermint
* Experience with Ethereum/Solidity (bonus points if you've worked with Layer-2 before!)
* Knowledge of financial instruments and markets

### Responsibilities 

* Build, maintain and test core components on our Cosmos-SDK based sidechain including our decentralized orderbook, trade execution coordinator, order matcher, and Layer-2 execution environment.
* Write open source Golang clients that allow users to interact directly with our protocol and smart contracts.
* Build high performance REST & WebSocket APIs to power our exchange frontend as well as programmatic traders

### Why it would be awesome to work with us 

* Challenging, first-of-its-kind tasks with a lot of responsibility and autonomy
* Instant deployment and usage by a global market
* Very competitive compensation
* Friendly work environment and world-class team
* Flexibility to work remotely 

### Contact 
Homepage: injectiveprotocol.com
Apply at: https://airtable.com/shruNBYlMJ9pq7kSj
Email: contact@injectiveprotocol.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
