### ISSUE TITLE
Cốc Cốc - Product Manager - Hanoi - HoChiMinh - Fulltime

### ISSUE THREAD

**Issue by oanhtran2710** [awesome-jobs/vietnam#2132]
## Location

* 185 Giang Vo, Cat Linh Ward, Dong Da District, Hanoi
* 27B Nguyen Dinh Chieu, Da Kao Ward, District 1, HoChiMinh

## Requirements
* At least 5 years of Product Management experience with a proven track record of building Internet products that users love
* BA/BS in a technical discipline and Computer Science or related majors.
* Excellent analytical, problem-solving, organizing, strong communication, and interpersonal skills.
* Experience with user research/testing, UI/UX design.
* Experience gathering business requirements and turning them into detailed technical requirements.
* Be able to work across teams to drive the implementation of new features as well as resolve operational issues.
* Demonstrated capacity for developing and understanding strategy with a strong aptitude for determining the optimal way to position products in the market..
* Ability to thrive under pressure and function effectively in a fast-paced environment, strong leadership skill, and ability to multitask.
* Self-driven, independent with a commitment to excellence.
* Fluent in professional English.

## Preferred qualifications:
* Background in software engineering and/or project management is preferred.
* Experience with Firebase and Google Analytics.
* Experience building and shipping products from the ground up is a plus.

## Soft skills:
* Proactively seeks learning opportunities beyond current requirements
* Ability to self-study and overcome the weaknesses.
* Good teamwork player.

## Best about this position:
* What we are doing is difficult, and this is why there are a lot of opportunities to learn and grow – no pain, no gain

* You will have to work alongside talented team members who have a unique skill set and expertise in this market

* Coc Coc is a Vietnamese company but we are also working in an international environment with team members/partners/customers that are local and international

* We have a mix of on the job learning/coaching/training to support you in your job and help you grow.

* Competitive and attractive salary

* Great Trade Union benefits for staff and family

* Special Annual policy and Remote Work policy

* Exciting internal events to help you understand the whole business and make you feel like you are part of the Cốc Cốc family

* Modern and cozy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day, to make sure energy level is high when you need it

* There are many interesting hobby clubs to share your non-professional passions: Yoga, Bicycle, Painting, Board game...

* Working time: Mon - Fri

## Contact: 

Email: tranhoangoanh27@gmail.com
Skype: hoangoanh2710@outlook.com
Job description: **https://topdev.vn/s/uSmslPy3**

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
