### ISSUE TITLE
NAB VDC - Senior Engineer (Chatbot, Azure) - Saigon - FT 

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#2134]
# Location

* Etown Central, Dist. 4, Saigon

# Salary Range

* USD Super Attractive 

# Job Overview

#### We are seeking passionate Senior Software Engineer who identifies automation opportunities and convert them into development of stories via code/algorithms to promote the Cognitive Process Transformation agenda for all National Australia Bank technology, aligned to Workplace Service support strategy.

# Your responsibilities: 
* Collaborate with the SMEs from the Service Support teams to understand the current workflows and help design autonomous solutions empowered by chosen AI IP stack (Azure, Google, AWS, etc.)
* Contribute to the solution design, usually in collaboration with business analysts, platform architects, security architects and product owners
* Work closely with other software engineers in a hands-on fashion, to implement the solutions in a programming environment

# What we look for:
* 5+ years of relevant industry experience in a technical role, including cloud development, user experience, machine learning and data analytics at the enterprise level: MS Azure (2-3 years), Chatbot DevOps (2-3 years),
* Minimum 4 years programming experience in C#/Node JS and fair knowledge of one of the followings: NLP, NLU, NLG, R, Python, Matlab, Java
* Ability to build guided conversations for a chatbot technology platform
* Strong understanding of operating systems & networking concepts.
* Good understanding of storage, load balancers, virtualization, web, database and messaging services with the ability to dive deep into any of these areas when necessary.
* Displays proven knowledge and expertise in the digital space 
* Ability to work collaboratively in a cross-functional DevOps team environment 
* Experience building machine learning algorithms, and then testing results against trained data sets, using unstructured inputs and converting them into structured form is desired
 * End-to-End customer experience management is desired
* Excellent communication skills in English
* High attention to detail and always ready to push the limits

 
### Desirable
* Desirable Certification: AZ-900/203/400, AI-100, ITIL v3

# Why it would be awesome to work with us?

* Join a global software development environment
* Competitive remuneration package
* Enjoy exceptional perks (tech/non-tech training courses, extra health insurance for you and your family (2 members), daily snack, billiards competition, ... you name it.)
* Business Trips to Australia
* Comfortable and inspiring workplace

### Want to experience yourself? Visit our brand new Agile office & have a chat with us over a cup of coffee!

# Contact

* E: linh.truong@nab.com.au 
* M: 0787 363 214
* Skype: linh.truong.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
