### ISSUE TITLE
[Remote Job] - Fullstack Dev - Ruby on Rails - $3000 - $4000 

### ISSUE THREAD

**Issue by ngocphuong39** [awesome-jobs/vietnam#2136]
## Location

* Remote

## Salary Expectation

* $3000 - $4000 (net) 

## Requirements
* A programmer who reads, writes and speaks English fluently
* A programmer who knows design pattern and how to apply it
* A  programmer who knows how to test your code and troubleshoot problems really well
* A programmer who understands how the database works and knows how to improve the performance of a system.

### Must Have

* Ruby on Rails 
*  4+ years experience

### Ideally

* Know about Vim is an advantage 

### Responsibilities

* Lead Reviewer 

### Why it would be awesome to work with us
* MacbookPro
* Health Insurance: $900/year 
* 13th-month Salary
* Annual Salary Review
* Training Support: $500 - $4000 
* Sport Allowance: $100 - $150/month
* Working hour: from Monday to Friday (8 a.m - 5 p.m)

### About us: 
Remitano was established in 2015 by Babylon Solutions Limited at Seychelles when cryptocurrency was entirely new to the community. After more than 4 years, Remitano is proud to be one of the largest peer-to-peer cryptocurrencies trading platform in Vietnam, where people can buy and sell Bitcoin, Ethereum, Bitcoin Cash, Litecoin, USTD, Ripple. Currently, Remitano has services in many countries, including Australia, Malaysia, Nigeria, Cambodia, India,... 

Joining in Remitano, you can work online anywhere. Besides,  you can quickly learn new things from your global colleagues who are professional, enthusiastic, and responsible. Living in Remitano culture, you have a golden opportunity to take a challenge and develop yourself.

### Contact
Email: ngocphuong@remitano.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
