### ISSUE TITLE
Kaopiz - Angular || Ruby || React || PM || BrSE || Tester - office/Hanoi - FT

### ISSUE THREAD

**Issue by loclv** [awesome-jobs/vietnam#2141]
## About company

`Kaopiz` is a company with 100% Vietnamese capital, develop projects for Japanese customers.

Established in September 2014

You can google `Kaopiz` for more information.

## Location

* Office in Tố Hữu street, Hanoi, Vietnam

## Salary Expectation

* dealing

## Requirements Skills

* Angular || Ruby || React || PM || BrSE || Tester

## Why it would be awesome to work with us

* bonus salary for IT, Japanese, English certificate

## Contact

to me: loclv@kaopiz.com

**Comment by qcam** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by loclv** [comment]
@qcam 
Thank you for your feedback!

I changed my contact to `loclv@kaopiz.com`. :smile:

**Comment by loclv** [comment]
@qcam Thank! :rocket:

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
