### ISSUE TITLE
FETCH TECHNOLOGY - Senior Node JS Developer - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2142]
![image](https://user-images.githubusercontent.com/60914247/95534890-37186700-0a11-11eb-9609-8711a14422ea.png)

## Requirements
* At least 3 years working as the position of NodeJS Developer and Typescript.
* Having an eagerness to learn new things.
* Willing to work with ReactJS.
* Good understanding of web/app development process (planning, development, implementation).
* Having strong knowledge about databases and systems: MySQL, MongoDB, Redis.
* Ability to work well in high-speed environments with a lot of pressure.
* Experience building software from scratch.
* Management Experience.
* Having experience working as a Fullstack Developer is a plus.
* Having experience with Javascript front-end framework, especially working with ReactJS is a plus.
* Having a Portfolio and many side projects is a plus.

## Responsibilities

* The Senior Back-end Developer will be responsible for building and managing web pages and various website applications.
* You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment.
* You will also be collaborating with the other team members such as the Content Team as well as the Design Team to refine the website and fix the technical issues.
* Participate in the entire process of product development: analyze, design system, code, and debug on demand.
* Design detailed technical plans for projects based on requirements from business teams.
* Integrate with backend services, give constructive feedback on UI/UX/API design to create a high-quality web app for end-users.
* Write clean and maintainable codes, with frequent code-reviews performed to a best practice standard.
* Good attitude, problem-solving and communication skills, not afraid of new challenges.

## Why it would be awesome to work with us?
* Being a Senior NodeJS Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on the job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
