### ISSUE TITLE
FETCH TECHNOLOGY - Senior Cocos2D Game Developer - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2143]
![image](https://user-images.githubusercontent.com/60914247/95536723-df302f00-0a15-11eb-9d7a-bb694b3bb36c.png)

## Requirements
* At least 2 years of experience with cocos2d.
* Diploma or Degree or in any IT related.
* Good knowledge of either Javascript/Typescript.
* Excellent knowledge of Mobile and Web Game Development (Online/Offline).
* Proficient knowledge of code versioning tools: GIT
* Portfolio and experience in at least 2 games published to multiple platforms.
*** Huge Advantage: Experiences in the card and slot games.
## Responsibilities
* As a senior cocos2d developer in our team, you will work closely with graphic designers and backend developers for developing and distributing games to the community.
* You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment.

## Why it would be awesome to work with us
Being a Senior Cocos2D Game Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on the job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
