### ISSUE TITLE
FETCH TECHNOLOGY - Search Engine Marketing Specialist - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2144]
![image](https://user-images.githubusercontent.com/60914247/95539612-050b0300-0a19-11eb-95ab-548ccf7e5cd9.png)

## Requirements
* Producing important keywords for content production.
* Proficiency in HTML, CSS, and many of the most common programming languages.
* Identifying, producing, and managing targeted and original content.
* Proven portfolio or track record in SEO.

*** Nice to have:

* A degree or equivalent in marketing or computer science.
* Understanding of the Gaming industry.
* Hands-on experience of at least one year in online marketing.

## Responsibilities
* Our Search Engine Marketing Specialist’s life is lived managing and structuring around details, as they plan, manage and implement our website’s SEO strategy, involving web marketing and analytics, keyword strategy, content strategy planning and link building.
* The most important characteristic of our Search Engine Marketing Specialist is the need for instant gratification, where your ad placements produce traffic to our website almost immediately, enhancing rankings on SERP or increased visibility. 
Living in the weeds of data and digging into Excel sheets, marketing dashboards and reports ripe with insights, our Search Engine Marketing Specialist churns metrics about the effectiveness of paid and organic search engine enhancements, and measurable success on investment. 
* Using statistical software and analytics, you glean website traffic patterns to drive search marketing efforts. Your sound research acumen has you busy developing test plans, implementing new strategies, measuring results and performing A/B Tests to optimize page designs.
* A silent listener and persistent lurker, our Search Engine Marketing Specialist spies on competitor marketing campaigns in order to co-opt winning strategies and develop superior marketing campaigns. Your success is measured in efficiency, clarity, accountability, and our climb to the top of web search rankings.

## Why it would be awesome to work with us?
Being a Search Engine Marketing Specialist at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on the job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).
### Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
