### ISSUE TITLE
VNIB Tech - Senior Full-stack Developer || Java || VueJS || Spring ||- Saigon/Ho Chi Minh - FT

### ISSUE THREAD

**Issue by Hill-Nguyen** [awesome-jobs/vietnam#2145]
![Banner 728x90px](https://user-images.githubusercontent.com/55223882/95813989-71e90a80-0d43-11eb-8fdf-cbbf68863cef.jpg)

## Location

* Saigon, Vietnam

## Salary Expectation

* $1200 ~ $1500/month

## Requirements
*  __3+ years of proven experience with Java, specialized J2EE stack.__
* __Strong skills in Javascript Frameworks (VueJS/ React/ AngularJS, etc.)__
* Spring framework: Core, Data, Boot, Security, and MVC.
* RESTful API development.
* English: good at reading and writing; can communicate at the basic level.

### Must Have

* JavaScript (VueJS/React/AngularJS, etc.)
* Java core, Data, Boot, Security, and MVC

### Ideally

* Experience with J2EE stack. 
* Good at English in all skills (reading, writing, listening, and speaking).

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Implementation of Web/Java application.
* Implementation of Rest APIs.

### Why it would be awesome to work with us

* Insurance base on the gross salary

* Probation time (2 months) with full salary

* 13th-month salary bonus.

* Annual performance review; Pay for unused annual leaves.

* Year-end party; Monthly happy hours after teams’ meeting

* Good opportunities for promotion and career development

* Company trip, team building, and other community activities

* Various and mixed light refreshments as snacks, green tea, coffee, etc. for your options.

* Professional, fun, and exciting work environment.

* Opportunity to improve your English performance specialized in writing, reading, and even speaking skills by chatting and video calling with the Korean team and CEO.

### Contact
* Homepage: https://www.vnib.net/
* Applied mail: recruitment.vn@innerbus.com
* Product: http://www.logcenter.net/

### VNIB's Team

![Halloween](https://user-images.githubusercontent.com/55223882/95814163-ec198f00-0d43-11eb-8815-60a8f7b7edf7.jpg)

![Halloween1](https://user-images.githubusercontent.com/55223882/95814222-0bb0b780-0d44-11eb-8bf2-7f6b8b9b21eb.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
