### ISSUE TITLE
Quod AI - Junior Source Code Data Analyst - Saigon/Singapore - FT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2146]
## Location
* Saigon, Vietnam
* Singapore, Singapore

## Salary Expectation
At the market rate

## Requirements
* Some technical expertise regarding one programming language and web or mobile software development (JS or Java preferred)
* Strong analytical skills with the ability to collect, organize, analyze, and disseminate significant amounts of information with attention to detail and accuracy
* Adept at regular expressions and presenting findings
* A deep passion for dumplings.

## Education and Experience
* Studying towards university degree in computer science or similar education.
* Strong verbal and written communication skills in English.

### Responsibilities
* Interpret source code, analyze results and provide ongoing reports
* Identify, analyze, and interpret trends or patterns in complex data sets

### About us
What if every software engineer could hold 1 billion lines of code in their head?
How would it change the way we build software?
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create **the first AI assistant** for software engineering team. Our first product **translates raw source code into natural language** to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

![95429515-b3a93800-0974-11eb-86cf-70dd15ce7fd3](https://user-images.githubusercontent.com/71882499/95812715-339e1c00-0d40-11eb-8636-22e9a0aecfff.jpg)

Our team has **ex Silicon Valley engineers** and **award-winning AI researchers** from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.

![95429465-a4c28580-0974-11eb-85e4-45e34058f37c](https://user-images.githubusercontent.com/71882499/95812745-43b5fb80-0d40-11eb-84b3-0b2c75aa793c.png)

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

![95429434-983e2d00-0974-11eb-8c6a-35086d0680a5](https://user-images.githubusercontent.com/71882499/95812773-4e709080-0d40-11eb-9528-acdfb7b518bb.png)

### Contact
Homepage: https://www.quod.ai/
[**Apply now**](https://docs.google.com/forms/d/e/1FAIpQLSd0n7WUvlu8B27VINJ4fO86T64MkeiZ2XWEEWFfeLvvOL9xnQ/viewform?fbzx=7745572257721885000)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
