### ISSUE TITLE
VNIB Tech - Fresher Tester (Manual) - Saigon/HCM - FT

### ISSUE THREAD

**Issue by Hill-Nguyen** [awesome-jobs/vietnam#2149]
![Hero Banner](https://user-images.githubusercontent.com/55223882/95817521-ddcf7100-0d4b-11eb-94c1-fdd6b5cc49f5.jpg)

## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* 8.000.000 ~ 9.000.000 Mil (Gross)/month

## Who we are looking for:
* __Female only.__
* __Bachelor's degree in the IT field; Software beginners are welcomed (will be trained).__
* __Completed a course about the testing.__
* English: good at reading and writing; Can communicate at the basic level.

### Responsibilities

* Join the full training process about both company's products and testing techniques.
* Make the test cases based on specifications.
* Report bugs in detail to the bug tracking system.
* Report the daily progress and status regarding overall testing.

### Why it would be awesome to work with us

* __Insurance base on the gross salary__
* __Probation time (1 month) with full salary__
* __13th-month salary bonus.__
* Annual performance review; Pay for unused annual leaves.
* Year-end party; Monthly happy hours after teams’ meeting
* Good opportunities for promotion and career development
* Company trip, team building, and other community activities
* Various and mixed light refreshments as snacks, green tea, coffee, etc. for your options.
* Professional, fun, and exciting work environment.
* Opportunity to improve your English performance specialized in writing, reading, and even speaking skills by chatting and video calling with the Korean team and CEO.

### Contact
Homepage: https://www.vnib.net/
Email: recruitment.vn@innerbus.com
Product: http://www.logcenter.net/ 

### VNIB's Team

![Mooncake](https://user-images.githubusercontent.com/55223882/95817642-330b8280-0d4c-11eb-9352-1686fa2d18b2.jpg)

![start](https://user-images.githubusercontent.com/55223882/95817712-5d5d4000-0d4c-11eb-8acf-623ef862b12b.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
