### ISSUE TITLE
Grab Platform/Gateway - Senior Software Engineer, Backend - HCM - FT

### ISSUE THREAD

**Issue by hongngocanhthu** [awesome-jobs/vietnam#2151]
## Location

* Mapletree Business Center, 1060 Nguyen Van Linh Street, Tan Phong Ward, District 7, Ho Chi Minh City, Vietnam
* Fulltime

## Your team
Come join the team that literally serves Grab - the Grab Gateway team. We front hundreds of APIs and process billions of incoming network messages for Grab's customers every day via our gateway systems. As a leader in an exciting and fast-paced industry that is evolving daily, we are seeking talented engineers to join our platform team!

## Your role
You specialize in building and maintaining leading edge solutions built on world-class technology stacks that bring our unique on-demand services experience to South-East Asia every day — be it transport, payments, food, or "the awesome things to come". Millions of people will be impacted by your contributions, which is demanding in terms of design and quality but also incredibly rewarding.

## You will
* build and own Grab's gateway systems connecting mobile devices, web apps and backend services with Grab's service mesh.
* work at Grab VN, closely integrated with product teams and devops to help building secure solutions with the right protocol, technology and patterns.
* be at home in a multi-cloud environment and build scalable, zero-downtime network traffic routing and analytics solutions for Grab's "public edge", serving billions of daily requests to Grab customers

## Your daily routine
* Independently drive projects across teams end to end, from inception to rollout
* Find and troubleshoot issues in Grab's entire infrastructure and code base
* Routinely resolve production incidents
* Implement quality solutions using Go and C++, and maintain the high bar of standards for code reviews and rollout processes. You mentor peers and promote development and operational excellence best practices while achieving excellent user experience

## Your experience
You are a habitual problem solver, and naturally assume ownership of your team’s systems and software components. You know how to be responsible for mission-critical systems and
* have a very good understanding of TCP/IP, HTTP and the internet
* are an expert in at least one of Assembly, C, C#, C++, Go, Java, Pascal
* know how to build highly-available distributed systems
* have significant industry experience and built several large scale mobile and public APIs
* You are familiar enough with C/C++ to debug and troubleshoot issues in 3rd-party open-source solutions we deploy

## Your advantage

* HTTP/2 and gRPC expertise, Hands-on experience with the Envoy code base
* Dealing with massive concurrency and designing resilient algorithms
* IaaS providers and their limitations (AWS, Google, Microsoft), Terraform experience
* Hands-on experience with large scale Docker / Kubernetes deployments
* Exposure to Machine Learning / Big Data Real-time Analytics
* Experience in a startup

### Why it would be awesome to work with us
* Macbook is provided.
* Extra Medical Insurance.
* 14 days annual leaves, working Monday - Friday.
* Free drive with Grab (budget follow your level)

### Contact
Tech Blog: https://engineering.grab.com/
Email: thu.hong@grabtaxi.com
Skype: hongngocanhthu

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
