### ISSUE TITLE
[LINAGORA] (Senior) iOS Developer - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2152]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* Bachelor’s degree in information technology, or related field + At least 3 years’ experience.
* Proficient with Objective-C or Swift, and Cocoa Touch.
* Experience with iOS frameworks such as Core Data, Core Animation, etc.
* Familiarity with RESTful APIs to connect iOS applications to back-end services
* Knowledge of other web technologies and UI/UX standards
* Understanding of Apple’s design principles and interface guidelines
* Proficient understanding of code versioning tools
* Familiarity with cloud message APIs and push notifications
* Have knowledge about other cross-platform development: Flutter, Cordova, ReactJS is a PLUS
* Fluency in English

### You’ll be responsible for

**Job Overview:**

You’ll develop from scratch the mobile application of the OpenPaaS (https://open-paas.org/) platform:

* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices.
* a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles.

**Responsibilities and Duties**:

* Participate in product design, offer new ideas
* Design and build applications for the iOS platform
* Collaborate with product and business teams to define our products that are suitable for the market
* Design and implement a mobile application for iOs using Swift
* Work in a team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our team maintain high standards
* Support international teams in developing products to meet the clients’ requirements
* Keep up to date on the latest industry trends in the mobile technologies
* Coaching the member in the team and attend to interview process to scan technical parts

### Why it would be awesome to work with us?

* Work in an international team with highly skilled people
* Correct work/life balance
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Participate in Open Source communities and conferences in Vietnam
* Modern working space, free coffee

### Contact

* Homepage: http://linagora.vn/
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
