### ISSUE TITLE
[LINAGORA] Java Developer - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2153]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* Strong background in Java development
* Strong development processes: Agile (scrum), Git & code review, Continuous integration (Jenkins)
* Experience with at least some of the following technologies: NoSQL (Cassandra, ElasticSearch), messaging (RabbitMQ), object storage (Swift), load testing (Gatling)
* Curiosity towards new technologies
* Knowledge of mail protocols is a plus (SMTP, IMAP, JMAP)
* Good level of English

### Why it would be awesome to work with us

* Strong interactions with the Apache James community
* Opportunities for promotions and the chance to travel or work in France
* Family culture in an international working environment: friendly, helpful, cooperative, and respectful
* International Software projects bring you to a highly international position
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Modern working space, free coffee

### Contact
* Homepage: http://linagora.vn/
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
