### ISSUE TITLE
[LINAGORA] Senior Automation Tester - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2155]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* 3+ years’ experience in Automation testing for Web/mobile applications.
* Experience in automation tests using Robotframework.
* Familiar with Page Object Model.
* Experience in performance testing is a PLUS
* The automation framework design and development experience is a plus.
* Good communication in English.

### You’ll be responsible for

* Join QA team to contribute to the development of various products including collaboration and communication tools for enterprises (mainly web-based, plus mobile app)
* Mainly work on building/maintaining automation scripts for our products based on the scenarios provided by the functional test team
* Report bugs found by the tests and follow up with the development team to get them fixed
* Support manual testing when needed
* Work closely with QA head and development team on the plan for automation testing
* Share knowledge with other QA members, actively contribute to Open Tech Talk and internal workshops
* Be willing to learn other technical testing skills/tools

### Contact

* Homepage: http://linagora.vn/
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
