### ISSUE TITLE
[LINAGORA] Full-stack Javascript Developer - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2156]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* Background in Computer Science/ Information Technology or equivalent.
* 3+ years of working for Javascript & NodeJS applications & 2+ years of VueJS
* Good communication in English.
* Highly proficient with the JavaScript language and its modern ES6+ syntax and features
* Knowledge of functional programming and object-oriented programming paradigms
* Familiarity with automated JavaScript testing, specifically testing frameworks such as Jest or Mocha
* Highly proficient with Vue.js framework and its core principles such as components, reactivity, and the virtual DOM
* Proficiency with modern development tools, like Babel, Webpack, and Git
* Experience with both consuming and designing RESTful APIs
* Knowledge of Object Oriented Programing languages like Java, PHP, etc (preferred)

### You’ll be responsible for

* Write high-quality, clean, maintainable, reusable code using engineering best practices (unit testing, source control, continuous integration, automation, design patterns, etc.).
* Analyze requirements, design, and develop features.
* Understand the product, constantly optimize the product, identify and fix problems, improve stability and user experience.
* Collaborate with fellow developers, product managers, user experience designers, and operation engineers to build products with web technologies.
* Optimize application for maximum performance and scalability.
* Participate in regular internal technology sharing and other regional tech events.

### Why it would be awesome to work with us

* Work in an international team with highly skilled people.
* Correct work/life balance.
* Annual company trip, other exciting activities for team building.
* Working 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

* Homepage: http://linagora.vn/
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
