### ISSUE TITLE
[LINAGORA] System Admin Engineer - Hà Nội - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2157]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* A system admin background, willing to work in a modern, automated environment (call it the cloud).
* A solid system administrator experience and customer projects experience.
* Any of the following technologies is a plus:
  * Docker knowledge
  * Running JVM applications
  * Knowledge about the Kubernetes eco-system
  * Knowledge with the Ansible automation tool
  * Performance testing
  * Database administration experience with the following databases: Apache Cassandra, ElasticSearch, RabbitMQ, Object Storage S3 API
  * Runtime monitoring (Zabbix, Prometheus, FluentBit, Grafana)
  * Git version system usage

### You’ll be responsible for

* Join a dynamic team working on a cutting edge distributed email server. Horn your dev-ops skill, setting up the required execution environment for the Apache James server, both for SaaS or on-premise execution. 
* Work with modern software, developed with scalability and availability in mind. 
* Exchanging with the DEV team, you will help engineer and improve the OPS experience for Apache James. You will get support from other OPS at Linagora. You will, with them, help refine the OPS standards we are using. 
* Furthermore, you will have the chance to get involved in an Apache community.

### Contact

* Homepage: http://linagora.vn/
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1
* Phone: 086.550.4412

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
