### ISSUE TITLE
Quod AI - Junior DevOps Engineer - Singapore/Saigon - FT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2159]
## Location
* Saigon, Vietnam
* Singapore, Singapore

## Salary Expectation
At the market rate

## Requirements
* Knowledge or experience with UNIX/Linux and experience working with open source software (MySQL, Postgres, etc.)
* Experience with scripting (Bash and Python)
* Experience with deploying web apps to cloud infrastructure (AWS or GCP)
* (Bonus) Experience with Kubernetes and Docker

## Education and Experience
* Mid level (1-4 years of experience)
* Strong verbal and written communication skills in English.

### Responsibilities
* Design, implement, and deploy internal tools to accelerate productivity of the wider Engineering team
* Maintain our infrastructure by automating software deployment, infrastructure configuration
* Evaluate, debug and integrate with various systems & applications
* Help the customer support team to respond to any escalations from the Customers
* Participate in our on-call rotation, troubleshoot and resolve production issues.
* Participate in post-mortem reviews of incidents and take corrective actions to improve our systems

### Why it would be awesome to work with us
What if every software engineer could hold 1 billion lines of code in their head?
How would it change the way we build software?
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create **the first AI assistant** for software engineering team. Our first product **translates raw source code into natural language** to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

![95429515-b3a93800-0974-11eb-86cf-70dd15ce7fd3](https://user-images.githubusercontent.com/71882499/96107601-cf798480-0f06-11eb-834a-aafe2928760a.jpg)

Our team has **ex Silicon Valley engineers and award winning AI researchers** from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.

![95429465-a4c28580-0974-11eb-85e4-45e34058f37c](https://user-images.githubusercontent.com/71882499/96107644-dc967380-0f06-11eb-830f-66b5d9f5eb47.png)

Opportunities to be **mentored by our Ex Silicon Valley CTO** 😉

![95429434-983e2d00-0974-11eb-8c6a-35086d0680a5](https://user-images.githubusercontent.com/71882499/96107688-e5874500-0f06-11eb-8ff4-25ab7404576b.png)

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

### Contact
Homepage: https://www.quod.ai/
Send your application to yen@quod.ai

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
