### ISSUE TITLE
CARDANO Labo Vietnam - Blockchain Technology Developer - HCMC - FT

### ISSUE THREAD

**Issue by ThanhCardano** [awesome-jobs/vietnam#216]
## Location

Saigon, Vietnam

Recent development in world economic and geopolitical background has triggered a number of world leading advanced technology such as "Smart contract" and Blockchain (distributed ledger system), the application of which have not yet and supposedly will never be contained in a certain industry or territory.

Such technology has been taught and researched at world-renowned institutions such as Massachusetts Institute of Technology (MIT), Stanford University and key enterprises in the world including Microsoft, Morgan Stanley and Deustch Bank. Unfortunately such technology has not yet been deployed in Asia, including Vietnam. 

CARDANO Labo is the leading cryptocurrency research and development startup focusing on blockchain-empowered advanced entertainment services. Our services are relentlessly developed and fine-tuned to facilitate enhanced circulation and liquidity of cryptocurrencies. CARDANO Labo is based in Vietnam – one of the leading IT markets in the region with the corporate vision centers around blockchain research, development and application.

By adopting such technology, we aim to achieve innovative technical breakthroughs to make the world a better and more convenient place. Thanks to the expansion of crypto-services and market in which Bitcoin has constantly been in the spotlight as a revolutionary approach to stimulate and reinvigorate world economic development, CARDANO Labo Vietnam has been developing Fintech and entertainment services leveraging state-of-the-art encryption technology to usher unrivalled, unprecedented yet accessible solutions to everyday life. We are definitely in need of dedicated, competent and passionate people to realize and accompany our ambitious agenda. Drop by or contact us should you be the ONE!
## Salary Expectation

Negotiable salary plus:
- 13th month salary and bonus
- Annual health check
- Business trips in Japan and company trips
## Requirements
- At least 2 year experience with Java/ Javascript/ NodeJS/ Python/ GoLang/ PHP/ C++/ C#/ ASP .NET/ Android/ iOS.
- Strong exprience in Data Structures and Algorithms (DSA)
- Knowledge with SQL (Oracle, MySQL, Postgre) or NoSQL (LevelDB, MongoDB, CouchDB), Big Data (Hadoop)
- Knowledge with PhoneGap, Titanium, Cocos, Unity, Qt for Mobile
- Preferred skills: Back-end, Network, Server, Socket, Blockchain, Bitcoin, Ethereum, Crypto-currency
## Skills

Passion to learn, teamwork,
Be able to read and write either in English or Japanese
### Responsibilities
- Business system Programming (Business Process ) 
- Test products and fix bugs
- Research new technology such as smart contact, Fintech to come up with technical solutions in Fintech, gaming and entertainment industries
- The sky is the limit ! 

[Cardano Labo Vietnam- Developer Recruitment.pdf](https://github.com/awesome-jobs/jobs/files/274149/Cardano.Labo.Vietnam-.Developer.Recruitment.pdf)
### Contact

Address: 2F, Athena Building, 146 - 148 Cong Hoa, Tan Binh District, HCMC
Phone: (+84) 914605151
Email: info@cardano-labo.com; datdt@cardano-labo.com

**Comment by joneslee85** [comment]
@ThanhCardano please revise the post, it does not comply with our guideline.

* s/Full Time/FT
* the `-` should have space in between, that is ` - `
* Why location details and location header on same line?
* Inconsistent indentation

Please ensure you get it right this time. I could not tolerate for another poor attempt as this waste my time and other reviewers.

**Comment by ThanhCardano** [comment]
Dear anh Trung,

I believe this is a community website rather than a commercial service.
Hence please understand that a non technical person can make some mistakes
and we are pleased to do revision. I do believe you and other members are
also doing this from merit base and supportive attitude.

From a member point of view I think your tone is quite unacceptable. I dont
ask you to do revision nor do I ask to waste your time. Please be clear and
precise and emotional tone should not used when we are discussing.

Thank you and if possible I would like to talk with someone more patient
than you in charge of technical issues. I am quite a non technical person
so I need more time and study to post in the right way.

Thank you for your time.

Thanh

On Fri, May 20, 2016 at 5:49 PM, Trung Lê <notifications@github.com> wrote:

> @ThanhCardano <https://github.com/ThanhCardano> please revise the post,
> it does not comply with our guideline.
>
>    - s/Full Time/FT
>    - the - should have space in between, that is -
>    - Why location details and location header on same line?
>    - Inconsistent indentation
>
> Please ensure you get it right this time. I could not tolerate for another
> poor attempt as this waste my time and other reviewers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/awesome-jobs/jobs/issues/216#issuecomment-220575486>
>



-- 
THANH Nguyen (Miss)
HP (+84) 943 378 452

**Comment by huydx** [comment]
@ThanhCardano 
Sorry for any inconvenience. However , we have a very clear guideline with a link (with template included) to submit a job. You just need to click the link to have correct guide-line.

![image](https://cloud.githubusercontent.com/assets/535718/15426512/09b1fe16-1eca-11e6-962f-95a53114c422.png)

**Comment by rebyn** [comment]
Guidelines are there for uniforms, uniforms exist for the sake of readability. I can't stress this enough for Ruby and Ruby community wise so what you're _complaining_ about doesn't seem like you've read enough, Thanh.

**Comment by joneslee85** [comment]
Dear Thanh

My apology for my hot temper.

It is indeed a community website and please understand I and like other reviewers are volunteer. I hope for your understanding.

Besides, this job board has a clear instruction on how to submit a job post. This seems to me that our instruction is not easy or clear enough for our users. Can you please contribute suggestion what we could do better?

Kind regards

**Comment by ThanhCardano** [comment]
Thanks both.
I believe your guideline is excellent. Just that please dont take it default that everyone can understand and will never make some minor errors such as space before and after the dash (-) or inconsistent identation, especially with a non technical person like me.
I have revised my post. Hope that is fine enough for you.

Regards,

**Comment by huydx** [comment]
@ThanhCardano thanks for your cooperation. Btw you do not have to repeat that you are non-tech person, almost our job post came from non-tech guys ;)

**Comment by joneslee85** [comment]
@ThanhCardano thanks for the feedbacks. FYI, most of the posts here are from HR people who are not technical people at all. But I think they all share one obsession for details and are very competitive in their arts to snatch the attention of the best talents in the pool.

**Comment by ThanhCardano** [comment]
Thank you, I am not an HR person either. I am not a person obssessed about details but rather about community development as its more of my job. Hence I believe in the virtue of tolerance and patience with people.

Hope that my post if fine enough to you. Good day!

**Comment by joneslee85** [comment]
@ThanhCardano I am glad you said that. To be honest, it is not 100% up to my par yet..

* s/Postgre/PostgreSQL
* the space after each `/` in ` Java/  ..`
* Phone: +84) 914605151 <-- missing the open `(` quote
* the `The sky is the limit ! Just tell us what you can do.` has ending `.` whilst the other dot point line do not

and it seems to me you don't fully know about the responsibilities of your company. The `Resp` section is kinda duplicating the `You’ll be responsible for` section. Furthermore, I think the description is too vague or too 'broad', if I were a candidate, I would not be interested in such details.

**Comment by ThanhCardano** [comment]
@joneslee85 dear anh, is there anyway you can help delete instead of close this issue only?
