### ISSUE TITLE
Senior Front-end Developer (ReactJS)

### ISSUE THREAD

**Issue by NhungLeee** [awesome-jobs/vietnam#2160]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* $1800-2500/month

### Responsibilities

Along with the entire development team, you may be responsible for building a CRM, a virtual classroom, or a learning management system:

*  Develop new user-facing features, maintain the current features
* Assist with architecture as well as work on actual implementation
* Build reusable code and libraries for future use, review other team members’ coding, ensure the implementation of agreed architecture and infrastructure.
* Work with fronted/backend team to plan and design structure of platform technology solution, help define standard for Laboratory
* Address technical concerns, ideas and suggestions
* Focus on UI/UX and work with designers and PO’s when necessary
* Optimize platform applications for maximum speed and scalability
* Monitor systems to ensure they meet both user needs and business goals
* Collaborate with other team members and stakeholders
* Mentor/train junior and fresher employees as necessary

## Requirements
* JavaScript
* React Framework
* 3+ years Software Engineering experience

## Skills
* English communication
* Object-Oriented Programming (OOP)

Great power comes with great responsibilities!

### Why it would be awesome to work with us
* A super young and dynamic environment where everyone's ideas are heard
* A flexible place where you can work remotely 1 day/week
* Bonuses based on your performance once you have done your project
* Team bonding event every month: Birthday party, Christmas, New Year, Halloween, etc.

### Contact
Career site: https://1on1english.freshteam.com/jobs 
Email: nhung.lth@1on1english.vn/ recruitment@1on1english.vn
Phone number: 028 7778 8880

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
