### ISSUE TITLE
Micas - Golang backend developer - Danang - FT

### ISSUE THREAD

**Issue by anhmv** [awesome-jobs/vietnam#2161]
## Location

* Hai Chau, Da Nang

## Salary Expectation

* Up to 25M

## Requirements
- 2+ years experience with back-end
- 1+ years experience with Golang
- Have knowledge in the following technologies: Docker, Git
- Experience working on non-relational databases (MongoDB)
- Experience working on Redis for caching/speeding up apps performance, Elasticsearch for optimize searching
- Excellent working attitude, problem solving skill, critical thinking, and communication skill.
- Enjoy technical challenges and are eager to explore new technologies

## Responsibilities
- Write scalable, robust, testable, efficient, and easily maintainable code.
- Write document, review code and support technical for junior members.
- Collaborate to R&D, System, Product, Seller teams to build or maintain products.

## Contact
Hưng (Mr.)
Email: contact@micas.vn
Homepage: https://micas.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
