### ISSUE TITLE
LINE Vietnam - Server-side Engineer - Saigon - FT

### ISSUE THREAD

**Issue by tuhuynh27** [awesome-jobs/vietnam#2162]
## Location
* Saigon, Vietnam

## Salary Expectation
* Market-Competitive and very attractive

### Must have
* Strong at a server-side programming language (Java preferred, but not obligatory)
* Strong at the problem-solving skill
* Good at both verbal and non-verbal English

### Qualifications
* Proven experience in operating/structuring Big Data, Storage and Analysis System (fresh grad/juniors feel free to apply too)
* Understanding & experience in Data structure, Algorithm, Distributed System
* Motivation to join LINE in new global challenges and build success with LINE
* No problem with business trips overseas

## Responsibilities
* Work with engineers from multiple teams to architect and develop stable web service
* Rapidly build, iterate, test and deploy new features and products
* Maintain a high-quality robust codebase
* Manage and contribute code to large scale projects from inception to completion

## Why it would be awesome to work with us
* Competitive salaries, incentives and benefits according to experience and education level
* Developing your career in a famous product company and working with the latest technologies in the world.
* Good engineering practices and processes including code review, test first, and training.
* Travel benefits (Korea, Japan, Thailand, Taiwan...)
* Working in a very Silicon Valley start-up style with a professional, international environment (we allow for remote working, flexible hours when needed).
* A latest Macbook Pro 16" model with dual 27" 2K monitors, free snack and drink at office's pantry.

## Interesting engineering projects
* [LINE App](https://line.me/) ecosystem with monthly 200m active users from Japan, Thailand, Taiwan, Indonesia...

## Contact
Send your CV to email: tu.huynh@linecorp.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by tuhuynh27** [comment]
How to re-open this? ![](https://emoji.slack-edge.com/T0GCQ370X/okay/a2a0742ac962c66e.png)

**Comment by qcam** [comment]
@tuhuynh27 I’d suggest creating a new post with the same content.
