### ISSUE TITLE
Employmenthero - Senior Backend Developer (Ruby) - Remote/Saigon - FT 

### ISSUE THREAD

**Issue by giakytrann** [awesome-jobs/vietnam#2164]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation
$2000 - $4000 up to 

## Requirements

- Enjoy being a generalist and a problem solver to solve issues for delight users, both internally and externally.
- You are a lifelong and fast learner. You are continually teaching yourself new things, and you love learning from others.
- Always seek for long-term solutions; you'll need to assess system-wide impacts that ensure the product evolves in the right way.
- Be proficient in at least one programming language, relational databases, object-oriented programming, and other stuff in backend stacks.
- Have good communication skills, in both Vietnamese and English.

* Experience with 

- Experience with Ruby programming language.
- Experience with Microservice architecture, Kubernetes, and Amazon AWS.
- History of collaboration with teammates, mentorship, or technical leadership

Great power comes with great responsibilities!

### You’ll be responsible for
As a member of a product team, you'll work closely with product owners, designers, and other engineers in other stacks to solve customer pain points. As a member of the backend team, you'll be responsible for system architecture, and writing codes. Oh hey, we have been aiming for high technical standards: 

- Your architecture must be well-designed and thoughtful. Our system is complicated, but modern, and require a high level of architecture design to ensure hundreds of engineers can work together with confidence, and hundred of features are delivered at the highest quality.
- Your code must be elegant, clean, and fast.
- Your deployment must pass a series of automatic tests and metrical checks.
- Our observability system and bot army help you responsible for any bugs, data integrity, and performance issues after.
- Achieving all of them is hard, but don't worry, we create an excellent environment for you to learn and grow. Moreover, as a part of the engineering team, you may join in building the technical foundations and leadership to help others grow. 

### Why it would be awesome to work with us

**We also have a great range of perks:**

- Free lunch / Drinks every working day
- 20 annual leave days
- Australian Trip for who are eligible
- Parking fee funded by company
- Birthday celebration - Annual health check
- Life and Health Care Insurance (for your family).
- A dedicated MacBook Pro and large monitor
- USD 500/ annual/ person for books/ tech conferences/courses
- USD 500/ annual/ person for English learning
- Allow remote working across Vietnam 

### Contact
- Email: ky.tran@employmenthero.com 
- Skype: giakytrann 

Thank you for your interest in career opportunities in Employment Hero!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
