### ISSUE TITLE
GHN - IT Business Analyst - HCMC - FT

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#2167]
## Location

*District 10, Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1000-1500$/month
Business Analyst role works directly with business units to analyze the internal process, business requirements, and as-is system to build a complete ERP system. You will be a liaison between the development team and stakeholders to deliver a system to meet the demand of business needs and parallel overall business strategies.

*The Job*

* Responsible for closely working with stakeholder to elicit and analyze business requirement
* Prepare user requirement, workflow, data requirement, and functional specification document
* Design data modeling and application mock-up/wireframe
* Work together with QC to produce testing plan and test case
* Participate in system and acceptance testing
* Conduct product operation training as needed
* Provide support for analysis of production issue to fix the functional defect

## Requirements
** Minimum 2 years of working experience in a Technical Business Analyst role
* Strong analytical skills with the ability to collect, organize, analyze, and disseminate significant amounts of information with attention to detail and accuracy
* Experience in UML design, data modeling, and PL/SQL
* Good understanding of product management/development
* Solid oral and written communications skills
* Background in Computer Science or Engineering. An MBA degree is a plus.
## Skills
Analysis, SQL
### Why You'll Love Working Here

* Fair team
* Macbook 
* Annual health check-ups.
* Sports club: Running, football, badminton
* Open communication with Senior Engineer & Technical Leader
* Challenging working environment with the attractive domain as Logistics
* Specific pantry with nice decoration & Coffee/Milk Coffee/Chocolate & Tea
* Annual Team-building + Outing trip
* Join Training Courses and Tech Sharing
* Mid-Autumn Party, Christmas party, Year-end Party
* With the delivery network cover more than 98% geographical area of Vietnam, you will be welcome anywhere in Vietnam for traveling
* Competitive salary and 13th-month pay.

### Contact
Dong (Mr.)
Email dongdd@scommerce.asia
Skype https://join.skype.com/invite/Ii3KnTLNg4Rk
Telegram: https://t.me/DongDoD

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
