### ISSUE TITLE
Quod AI - Junior FullStack Engineer - Singapore/Saigon - FT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2168]
## Location
* Saigon, Vietnam
* Singapore, Singapore

## Salary Expectation
At the Market rate

## What do I need
* Strong skills with JavaScript.
* Relevant experience with Google Cloud or AWS is a plus.
* Superior analytical, conceptual and problem-solving skills.
* The ability to learn and iterate quickly.
* A deep passion for dumplings.
* An obsession with agile and lean principles (GitHub, Trello)
* Deep understanding of databases is a plus.
* Experience with Elasticsearch is a plus

## Education and Experience
* Recent graduates (0-2 years of experience)
* Studying towards a university degree in computer science or similar education.
* Strong verbal and written communication skills in English.

### What will I do
* Use HTML, CSS, JavaScript, and React to create the frontend of a web application
* Use Node.js to create the backend of an application and connect it to a frontend
* Developing backend website applications
* Use MySQL, ElasticSearch to create databases for content and data management
* Maintain and review code for fellow team members
* Meeting both technical and customer needs

### Why it would be awesome to work with us
What if every software engineer could hold 1 billion lines of code in their head?
How would it change the way we build software?
How would it accelerate our innovations for the rest of the world?

Quod AI aims to create **the first AI assistant for software engineering team**. Our first product **translates raw source code into natural language** to help software engineering team manage the complexity of large codebase. To do this, we apply NLP and Deep Learning onto more than 1 billion lines of code.

![95429515-b3a93800-0974-11eb-86cf-70dd15ce7fd3](https://user-images.githubusercontent.com/71882499/96440939-dcfa7b80-1232-11eb-8dd2-57367d3e7797.jpg)

Our team has **ex Silicon Valley engineers and award winning AI researchers** from top institutions like Cornell University, IBM AI XPRIZE, UCL, NTU Complexity Institute & Polytechnique Paris.
Opportunities to be mentored by our Ex Silicon Valley CTO 😉

![95429465-a4c28580-0974-11eb-85e4-45e34058f37c](https://user-images.githubusercontent.com/71882499/96441225-63af5880-1233-11eb-8b67-2c44511b5d28.png)

We are funded and backed by 500 Startups, Xooglers Angels, Entrepreneur First and SGInnovate.

![95429434-983e2d00-0974-11eb-8c6a-35086d0680a5](https://user-images.githubusercontent.com/71882499/96441242-6e69ed80-1233-11eb-9a7f-85143e36ec41.png)

### Contact
Homepage: https://www.quod.ai/
**[📑 Apply now 📑](https://docs.google.com/forms/d/e/1FAIpQLSd0n7WUvlu8B27VINJ4fO86T64MkeiZ2XWEEWFfeLvvOL9xnQ/viewform?fbzx=7745572257721885000)**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
