### ISSUE TITLE
StoryTree / US startup company - Senior Backend (Python) - Remote / Ha Noi - FT

### ISSUE THREAD

**Issue by dxungngh** [awesome-jobs/vietnam#217]
## Location
- Ha Noi, Vietnam
- Remote

Silicon Valley Startup - Hanoi Office

Storytree is an award winning startup based in Silicon Valley with founders from from Stanford and MIT. Its apps have been recognized by the New York Times, Techcrunch, SXSW and have been featured by Apple. Our main project is SimplePrints, one of the most popular apps in the US for printed photo albums.

The Storytree Vietnam team is based out of Hanoi. We currently have a small team of 4 engineers (iOS, Android, Backend) and we are seeking to hire a few more talented people. Our backend is Django (Python), servers are on AWS EC2, storage is on AWS S3, database is Postgres, we have apps on iOS and Android.
## Salary Expectation:
- Between $1500 and $2500 per month
## Requirements
- Bachelor of Computer Science, or equivalent.
- Passionate to learn new technologies.
- Cooperate well with the others.
- Can work comfortably in a fast paced environment.
- Be able to read and write in English well (to communicate with US team).
## Recommended:
- Proficient in spoken English.
- Strong sense of Data Structures and Algorithms (DSA).
- Great engineering skills: problem solving, coding, system designing,...
- Experienced in SQL (Oracle, Postgres), AWS services (EC2, S3, RDS,...).
- Experienced in Python and Django.
### Contact
- CEO: matt@storytree.me
- Ha Noi: dxungngh@gmail.com
- Website: www.getsimpleprints.com

**Comment by matthawaii** [comment]
Location
Ha Noi, Vietnam
Remote

Silicon Valley Startup - Hanoi Office

Storytree is an award winning startup based in Silicon Valley with founders from from Stanford and MIT. Its apps have been recognized by the New York Times, Techcrunch, SXSW and have been featured by Apple. Our main project is SimplePrints, one of the most popular apps in the US for printed photo albums. We are working on a similar app for small businesses.

The Storytree Vietnam team is based out of Hanoi. We currently have a small team of 4 engineers (iOS, Android, Backend) and we are seeking to hire a few more talented people. Our backend is Django (Python), servers are on AWS EC2, storage is on AWS S3, database is Postgres, we have apps on iOS and Android.

Salary Expectation:
Between $1500 and $2500 per month

Requirements:
University degree in Computer Science or equivalent.
A passion to learn new technologies.
Works well with others.
Comfortable in a fast paced work environment.
Be able to read and write in English (to communicate with US team).

Recommended:
Fluent in spoken English.
Strong experience in Data Structures and Algorithms (DSA).
Experience with SQL (Oracle, Postgres), Amazon service (EC2, S3).
Experience with Python and Django 
Experience with iOS development (for iOS position).

Contact
CEO: matt@storytree.me
Ha Noi: dxungngh@gmail.com
Website: www.getsimpleprints.com

**Comment by joneslee85** [comment]
@matthawaii thanks for posting here with us. Can you get in touch with @dxungngh to consolidate the job post? (then please delete your comment). TIA

**Comment by anhldbk** [comment]
@dxungngh Is the position still available?

**Comment by dxungngh** [comment]
Hello @anhldbk 
Thanks for your question, but this position is not available now. Hope that we can work together in the future.
Keep in touch.
