### ISSUE TITLE
Humanly.io - Junior Software Engineer - Saigon/Remote - FT

### ISSUE THREAD

**Issue by barjo** [awesome-jobs/vietnam#2170]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $400-$1200/month

## Requirements

* Relevant degree in computer science and/or 1 to 2 years of experience in software development.
* Good knowledge of data structures and algorithms.
* Working knowledge of relational databases.

### Must Have

* Good English communication skills.
* Self-motivated, independent, and detail-oriented, with excellent teamwork and interpersonal skills.
* Availability for a video call ~10PM at least once a week.

### Ideally

* Experience with web development using HTML, CSS, and/or JavaScript.
* Experience with Git.
* Experience with functional programming.

### Responsibilities

As a member of our engineering team, you will focus on the design, development, testing, and maintenance of all of Humanly. You will learn about and work on both the backend and frontend of our web applications, gaining experience with virtually every component in the web development stack.

### You’ll be responsible for

* Design, development, testing, and maintenance of software applications.
* Participation in engineering team meetings and code reviews.
* Adherence to coding and testing best practices.
* Collaboration with the entire Humanly team to continuously improve our products, services, and process.

### Why it would be awesome to work with us

We’re excited to bring on new teammates who are energized by an entrepreneurial, fast-paced environment with fantastic growth potential. You’ll have a chance to work with an extremely talented group of folks who challenge each other and are focused on making a big impact.

### What we use

Elixir (with Phoenix framework), Elm, PostgreSQL, Kubernetes, Git

### About us

Humanly is committed to solving recruiting’s toughest challenges with innovative AI and ML technologies. The future of hiring is here and Humanly aims to be the market leader in this space. 

As a Y-Combinator (W 20) graduate with robust seed funding, Humanly’s product streamlines candidate screening and scheduling for companies with high applicant volume. Our solution engages and screens job candidates that come to company job pages, social media, and job boards, saving hiring teams 60+ hours per open role on average, while improving candidate's experience and helping remove bias from the application process.

### How to apply

You can apply directly through our wonderful application [here](https://chat.humanly.io/humanly-junior-engineer-vn).

### Contact

Homepage: humanly.io
Jonathan: jonathan_at_humanly_dot_io

**Comment by barjo** [comment]
Thanks @lactroi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
