### ISSUE TITLE
PHP DEVELOPER

### ISSUE THREAD

**Issue by vkhang-truong** [awesome-jobs/vietnam#2173]
## Location

* Golden West Apartment, No. 2 Le Van Thiem Street, Nhan Chinh Ward, Thanh Xuan District, Hanoi City

## Salary Expectation

* Up to $1,200

## Requirements
* Good thinking ability
* Capable of teamwork
* Careful, meticulous, eager to learn, responsible
* Capable of reading comprehension, self-learning from documents in English

### Must Have

* From 01 - 02 years of experience as a Full-stack developer with PHP MVC frameworks like Laravel
* Have good knowledge of one or more ORM frameworks
* Have good knowledge of MySQL or PostgresQL
* Extensive experience and proficiency in basic frontend programming (HTML, CSS, Ajax, jQuery, Bootstrap)
* Fluent Javascript programming
* Understand OOP, MVC pattern, Dependency Injection and important programming patterns

### Ideally

* Experienced in WooCommerce, Wordpress is an advantage
* Good experience in MongoDB, Redis, ElasticSearch is an advantage
* Experience in advanced frontend programming (ReactJS, Angular, Vue), or mobile programming (React Native) is an advantage

### You’ll be responsible for

* Teamwork to design, install feature, fix bugs, maintain, and improve product performance according to customer requirements
* Research, evaluate and apply new technology trends to optimize work efficiency with the company team
* Participate in seminars, presentations introducing projects as well as technologies at the company as the organizer or contributor
* Complete work on time
* Report work situation to superiors / supervisors

### Why it would be awesome to work with us
* Full range of regimes in accordance with the law
* 13th month salary for employees who have been with the company for 1 year
* Opportunities to improve English through working and communicating directly with international customers
* Promotion opportunities with clear roadmap
* Youthful and friendly working environment
* Monthly team-building activities, travel
* TV entertainment, boardgame, daily teabreak, birthday party and monthly sports
* Working from Monday to Friday every week

### Contact
Homepage: https://brightsoftsolution.com/
Email: vkhang.truong@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
