### ISSUE TITLE
The Talent Shark - Senior Developer, Android Mobile - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by LCSgp** [awesome-jobs/vietnam#2177]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* Per applicant's relevant experience and skillsets. 

## Requirements
* Bachelor's degree or above in Computer Science, Software Engineering, or related majors
* Intermediate (CEFR B2) or higher level of spoken and written English
* Good interpersonal skills, analytical mind, conscientious attitude, and passion for engineering excellence
* Willingness and ability to adapt to changes in priorities and requirements
* Active learner who is passionate about technology and keeps up-to-date with changes in technology

### Must Have

* Minimum 5 years of experience in software engineering and development for mobile applications including Analysis and Design skills
* Strong knowledge of Android SDK, different versions of Android, and how to deal with different screen sizes
* Solid knowledge of UI/UX standards
* Solid knowledge of Android UI design principles, patterns, and best practices
* Familiar with offline storage, threading, and performance profile tool
* Familiar with cloud message APIs and push notifications
* Experienced in Restful APIs to integrate Android applications to backend services
* Experience of source code control tools (e.g., GIT, SVN)
* Experience of CI/CD tools (e.g., Jenkins, SonarQube)
* Understanding of different phases of software development lifecycle and understanding of Agile Scrum processes

### Ideally

* Familiar with collaborative interface tools like Invision, Figma
* Proficient in micro-service-related technologies (API gateway, service discovery, containerization, Docker, etc.)
* Experienced in working with one of the popular public clouds such as Azure, AWS, GCP
* Experience in other mobile developments like Android native by Java or React Native
 
### Responsibilities

* Design and build applications for Android platform
* Translate designs and wireframes into high quality code
* Ensure the quality, performance, and stability of the applications
* Write high quality and testable code following clean code and SOLID design principles
* Identify causes of problems and fix bugs
* Create and design, technical and project documentation
* Plan and schedule own work for tasks and projects, also implement functionality without direct supervision
* Follow and understand defined software development processes, such as tasks assignments, daily issue tracking etc
* Working with operation team and end user to get the project deliverables to be accepted and released in production environment
* Work independently while in close collaboration with others in the team and across projects
* Coach junior colleagues

### Why it would be awesome to work with us (REQUIRED)

Our Client is a global US Consulting MNC. They offer:
* Friendly team and enjoyable working environment
* Opportunity to work with international employees and customers
* Work-life balance and flexible schedule
* Online training library, mentoring, career development and potential partial grant of certification
* Referral bonuses
* Competitive compensation and benefits
    
### Interesting Engineering Projects (REQUIRED)

* Collaborate with international brands and companies to achieve success stories on digital technology break-through.

### Contact

Kindly submit your resume to https://the-talent-shark.breezy.hr/p/466e5d6be013-senior-developer-android/apply
Thank you for your interest.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
