### ISSUE TITLE
StoryTree / US startup company - Senior iOS developer - Remote / Ha Noi - FT

### ISSUE THREAD

**Issue by dxungngh** [awesome-jobs/vietnam#218]
## Location
- Ha Noi, Vietnam
- Remote

Silicon Valley Startup - Hanoi Office

Storytree is an award winning startup based in Silicon Valley with founders from from Stanford and MIT. Its apps have been recognized by the New York Times, Techcrunch, SXSW and have been featured by Apple. Our main project is SimplePrints, one of the most popular apps in the US for printed photo albums.

The Storytree Vietnam team is based out of Hanoi. We currently have a small team of 4 engineers (iOS, Android, Backend) and we are seeking to hire a few more talented people. Our backend is Django (Python), servers are on AWS EC2, storage is on AWS S3, database is Postgres, we have apps on iOS and Android.
## Salary Expectation:
- Between $1500 and $2500 per month
## Requirements
- University degree in Computer Science or equivalent.
- A passion to learn new technologies.
- Works well with others.
- Comfortable in a fast paced work environment.
- Be able to read and write in English (to communicate with US team).
## Recommended:
- Fluent in spoken English.
- Strong experience in Data Structures and Algorithms (DSA).
- Experience with iOS development.
- Clean code and good software architecture.
### Contact
- CEO: matt@storytree.me
- Ha Noi: dxungngh@gmail.com
- Website: www.getsimpleprints.com

**Comment by solarcraft** [comment]
Did you find the appropriate developer ? I would like to apply for iOS developer position?

**Comment by joneslee85** [comment]
@solarcraft if the post is active, that means the company is still open for application. Please get in touch with the company directly rather posting comment here. Such comment might make the company reflect wrongly about you because they might take the you are not serious enough to read through the post.

**Comment by dxungngh** [comment]
@solarcraft we are finding the `appropriate developer`
