### ISSUE TITLE
Saigon Technology Solutions - Mid/Sr .NET Developer - Tan Binh District - FT

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2181]
## Location

* 02 Nguyen The Loc, Ward 12, Tan Binh District, HCMC
* Fulltime

## Salary Expectation

* 20 million VND - 45 million VND per month

## Skills
- Good verbal/non-verbal English
- Good at analyzing & problem-solving skill
- Good teamwork and generates enthusiasm among team members
### Must Have

- Have at least 3 years of experience in .NET projects
- Web App/ Restful API, SPA
- MVC 5, Web API 2.2, Entity Framework
- .NET Core 2.0+, Entity Framework Core 2+
- SQL Server 2012+
- Windows Server 2012+
- HTML 5, CSS3, Bootstrap 3 or 4
- Dependency Injection and Inversion (in SOLID)

### Ideally
* Angular2+, React JS
* Microsoft Azure / Amazon
* Algorithm knowledge
* Leadership skill is a plus 

### Responsibilities

- Work directly with Holland Technical Lead to implement features of banking systems
- Assist with application architecture design and implementation.
- Adhere to and recommend improvements to project coding standards.
- Work in a team environment with shared code; disciplined use of source code control and process documentation.
- Solve technical problems

### Why it would be awesome to work with us
At **Saigon Technology Solutions**, we believe that "Your success is our mission", that’s why we build an excellent working environment along with exceptional benefits:

- Attractive salary and benefits( 13th, Salary review – twice/year)
- Project bonus
- Free English course
- PVI health care program
- Company trip every year
- Weekly happy hour
- The staff of the month/year reward
- Party celebration(Christmas, Birthday,...)
- Team-building activities
- Technical training sessions(internal-external)
- Weekly Knowledge Exchange
- Professional working environment with Agile – Scrum
- Sport clubs (football, badminton…)
- Enjoy Relax and beautiful Pantry in the company

### Contact
Homepage: saigontechnology.com
Kien Tran - HR Executive: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
