### ISSUE TITLE
UNSTATIC - iOS Developer - HN

### ISSUE THREAD

**Issue by zanzan211** [awesome-jobs/vietnam#2182]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Up to 30M Net

## Requirements
* 2-3 years of experience developing for Apple Devices
* Fluent at Swift 
* Have experience with RESTful, GraphQL, SQLite, Realm
* Strong knowledge of data structures, algorithm, design pattern, clean code, SOLID
* Have knowledge of common architectural patterns like MVC, MVVM
* Preferred to have experience with SwiftUI and Reactive programming

### Responsibilities

* Analyzing and developing application features
* Working with Marketing team to deploy ideas
* Proposing solutions/new technology trend to improve the product

### Why it would be awesome to work with us
* Competitive net salary
* Performance review twice a year
* Dynamic and young product company working environment

### Contact
Skype: live:e0ac26a3c611176e (Phuong)
Email: bichphuong@unstatic.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
