### ISSUE TITLE
Saigon Technology Solutions - Mid/Sr PHP Developer - Tan Binh District - FT

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2184]
## Location

* 02 Nguyen The Loc, Ward 12, Tan Binh District, HCMC
* Fulltime

## Salary Expectation

* Up to 1500$/month

### Must Have

* At least 3 years of experience in PHP frameworks (Laravel)
* Experience in Restful API, advanced JavaScript (including prototype-based inheritance, event delegation, closures, AJAX, JSON).
* Experience in MySQL
* Architecture, algorithm knowledge 
* Good at verbal/non-verbal English
* Good at analyzing & problem-solving skill

### Ideally

* Experience with CI/CD tools
* Experience with AWS: S3, RDS, EC2, SES, Route53, DynamoDB
* Ability to participate in multiple projects simultaneously 

### Responsibilities

* Work directly with Australia client to clarify requirements and implement features
* Design application architecture and implementation.
* Maintain existing applications
* Work on other tasks assigned by Team Leader

### Why it would be awesome to work with us
At **Saigon Technology Solutions**, we believe that "**_Your success is our mission_**", that’s why we build an excellent working environment along with exceptional benefits:
* Attractive salary and benefits (13th, Salary review – twice/year)
* 100% salary in probation period
* Project bonus
* Free English course
* PVI health care program
* Company trip every year
* Weekly happy hour
* The staff of the month/year reward
* Party celebration(Christmas, Birthday,...)
* Team-building activities
* Technical training sessions(internal-external)
* Weekly Knowledge Exchange
* A professional working environment with Agile – Scrum
* Sports clubs (football, badminton…)
* Enjoy Relax and beautiful Pantry in the company

### Contact
Homepage: saigontechnology.com
Kien Tran - HR Executive: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
