### ISSUE TITLE
iRuuza - Full Stack Developer / RoR / React - Full Remote - FT/C

### ISSUE THREAD

**Issue by nao215** [awesome-jobs/vietnam#2185]
## About Us
**Less Coding More Innovation!!**

We are nocode start up and incubator of a lots of web service. our business are
- Create code automation platform. *not open now. using only inside company
- Create web service or native app (client work) using code automation tool by us.

## About This Job
help our clients to build software (web, ios, android) with our code generator. So you would do 
- our client work *ex. create dating app, saas platform...etc
- create source code generator and automate coding!!

## Location
* Full Remote

## Work condition
- full remote and you can work from all over the world
- HQ is in Tokyo. We may ask meeting in JST but we can make arrangement for meeting schedule.

## Salary Expectation
* $25k-$50k/month

## Requirements
* Ruby, RoR
* React, React Native
* MySQL
* 3+ years Software Engineering experience

### Must Have
- RoR skills (at least 2-3 years)
	- you need to have knowledge about MVC, service, decorator, serializer, or any other architecture
	- well know about database (MySQL, postgresql...etc)
  - Restful architecture
  - unit testing
- React skills (at least 1-2 years)
	- good knowledge of redux, component life cycle, react hook
	- good at frontend development. implement with good design will be needed to *dont need to create design with figma or adobe xd or sketch... etc. but need to implement with these design tools.
- Fluent English

### Ideally
- Experience with Infrastructure with AWS
  - cloudformation, DevOps... etc
- Experience of code automation
- contribution for Famous OSS

### About your personality
- have responsibility
- have passion to remove unnecessary coding and create innovation
- have honesty and good heart

### You’ll be responsible for
- Building code automation tool
- some client work with code automation platform.

### Why it would be awesome to work with us
We are small team, but every engineer is really awesome. One have oss with 100+ stars, One have experience to commit rails/rails repo!

### Interesting engineering projects
I don't need to talk about why our project is interesting. Because if you are good engineer with laziness to write boring code, you would love our vision!

### Contact
Homepage: https://iruuza-inc.com/ *not in vn yet
Nao: n.yanagisawa@iruuza.com
Angellist: https://angel.co/company/iruuza/jobs/1043144-full-stack-engineer-ror-react-react-native-full-remote-hiring-from-all-over-the-world

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
