### ISSUE TITLE
LINAGORA - Moodle LMS Developer (Freelance)

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2186]
## Location

* Hanoi, Vietnam
* Remote

## Package

* Negotiable

## Requirements

* Proficient in PHP, HTML, CSS
* Moodle LMS development knowledge (modules, plugins, functionalities, and themes)
* Develop Moodle server-side web service API experiences
* Linux Server & site administration knowledge
* Communication skill, express idea
* Proactive and flexible to solve the problem
* Being able to work independently and work with a team
* English speaking

### You’ll be responsible for

**Job Overview**: Perfect role for someone looking to grow with a fast-paced and thriving software services and consulting organization. This Moodle Developer performs a key role in creating and maintaining learning management systems based on Moodle and PHP, including design, configurations, and customization.

**Responsibilities and Duties**:
* Perform design, configure, customize and implement LMS Moodle
* Support Moodle (PHP & HTML/CSS) implementations and resolve any technical issues
* Support course backup and user enrollment.
* Deploy the Dev environment, production environment for customer
* Working with a Training specialist to build/customize the course
* Responsible for training for the customer the development/customization Moodle

### Contact

📧 Email: vnhr@linagora.com
☎️ Phone: 086.550.4412
🎯 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
