### ISSUE TITLE
LINAGORA - Java Developer - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2192]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ba Dinh, Ha Noi

## Salary Expectation

* Up to $2000 gross

## Requirements

* Working with the team to set new milestones for our roadmap.
* Adding new features, and improve test automation to cover cloud operations. 
* Implementing using modern big data technologies like Apache Cassandra, ElasticSearch, and RabbitMQ.
* Contributing a JMAP implementation, a new mail protocol standard that we participate to elaborate, disrupting the way client mail user applications are being written.

### You’ll be responsible for

* Working with the team to set new milestones for our roadmap.
* Adding new features, and improve test automation to cover cloud operations. 
* Implementing using modern big data technologies like Apache Cassandra, ElasticSearch, and RabbitMQ.
* Contributing a JMAP implementation, a new mail protocol standard that we participate to elaborate, disrupting the way client mail user applications are being written.

### Why it would be awesome to work with us?

* Strong interactions with the Apache James community
* Opportunities for promotions and the chance to travel or work in France
* Family culture in an international working environment: friendly, helpful, cooperative, and respectful
* International Software projects bring you to a highly international position
* Working in Linagora headquarter in Southeast Asia
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Modern working space, free coffee

### Contact

📧 Email: vnhr@linagora.com
☎️ Phone: 086.550.4412
🎯 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
