### ISSUE TITLE
LINAGORA - iOS Developer - HN - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2193]
## Location

* 8th Floor (Toong), VPBank Tower, 5 Dien Bien Phu, Ba Dinh, Ha Noi

## Salary Expectation

* Up to $1500 gross

## Requirements

* Bachelor’s degree in information technology, or related field + At least 3 years’ experience.
* Proficient with Objective-C or Swift, and Cocoa Touch.
* Experience with iOS frameworks such as Core Data, Core Animation, etc
* Familiarity with RESTful APIs to connect iOS applications to back-end services
* Knowledge of other web technologies and UI/UX standards
* Understanding of Apple’s design principles and interface guidelines
* Proficient understanding of code versioning tools
* Familiarity with cloud message APIs and push notifications
* Have knowledge about other cross-platform development: Flutter, Cordova, ReactJS is a PLUS
* Fluency in English

### You’ll be responsible for

* **Job overview**:
You’ll develop from scratch the mobile application of the OpenPaaS (https://open-paas.org/) platform:
* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices.
* a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles.
* **Responsibilities and Duties**:
* Participate in product design, offer new ideas
* Design and build applications for the iOS platform
* Collaborate with product and business teams to define our products that are suitable for the market
* Design and implement a mobile application for iOs using Swift
* Work in a team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our team maintain high standards
* Support international teams in developing products to meet the clients’ requirements
* Keep up to date on the latest industry trends in the mobile technologies
* Coaching the member of the team and attend to interview process to scan technical parts

### Why it would be awesome to work with us?

* Strong interactions with the Apache James community
* Opportunities for promotions and the chance to travel or work in France
* Family culture in an international working environment: friendly, helpful, cooperative, and respectful
* International Software projects bring you to a highly international position
* Working in Linagora headquarter in Southeast Asia
* Annual company trip, other exciting activities for team building
* Working 5 days/week, from Monday to Friday
* Lunch allowance, 13th-month salary, competitive salary
* Annual health checkups and other benefits based on labor law
* Modern working space, free coffee

### Contact

📧 Email: vnhr@linagora.com
☎️ Phone: 086.550.4412
🎯 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
