### ISSUE TITLE
CodeLink - Senior .NET Core Developer (C# / .NET / ReactJS) - HCMC - FT #2176

### ISSUE THREAD

**Issue by khacanh** [awesome-jobs/vietnam#2194]
![CodeLink Year-end Party](https://user-images.githubusercontent.com/122055/73826276-17042880-4830-11ea-99d8-1495c6362e94.jpg)

## Salary Expectation
* $1800+

## About us

CodeLink is an innovative and design-focused development studio made up of an international mix of designers and developers. Our main stacks are Golang, Rails, NodeJS, .NET and ReactJS. We have built products in different industries, including Finance, Education, Entertainment, HR, etc for clients ranging from start-ups such as CryptoKitties to big companies such as Air Asia and Electronic Arts.

We are building an environment where personal development is a focus. We want all members to grow with the company through hands-on projects and industry best practices. Our clients have extremely high expectations and that sets a bar for our quality of work.

Our team members work directly with international teams from Canada, US (Silicon Valley, Boston), Germany and other well-developed tech scenes. This level of collaboration and exposure help us skill up to meet the international standards. 

We are willing to adopt new but proven technologies provided that they bring business values to our clients and learning opportunities for our team. We have our freedom to choose and recommend what solutions are best for a certain project.

We are looking for a full-stack .NET Core developer. This will be our first .NET hire, so we are expecting this person to bring in the expertise to help grow the team. You will be working directly with a team in the US to design, build and deploy new projects of a large legal firm. 

Company website: [www.codelink.io](https://www.codelink.io)
Design work: [www.behance.net/codelink](https://www.behance.net/codelink)
Team activities: [www.facebook.com/codelink.io](www.facebook.com/codelink.io)

## What you'll be doing:
+ Working with other team members (engineers, testers, designers, POs) to design, build and deploy new applications. 
+ Designing back-end API using .NET Core. 
+ Implementing front-end components with ReactJS. 
+ Handling daily communication with the team in the US. 
+ Working with other engineers in Vietnam to form a productive team. 
+ Mentoring new members to help them onboard and contribute the the project. 
+ Collaborating with other team members to improve and optimize existing designs and applications

## Required skills
+ Require a minimum of 5 years of experience with .NET, C#, MVC design pattern and RESTful API. 
+ Require experience with SPA such as AngularJS or ReactJS. 
+ Require relevant knowledge of relational database systems such as MySQL, PostgreSQL and SQL Server.
+ Require experience with one of these cloud platforms: Azure, AWS or GCP.
+ Require experience with Service Oriented Architecture. 
+ Required experience with deployment, scaling, monitoring and performance tuning.
+ Experience with Extreme Programming methodologies such as Test Driven Development, Refactoring and Continuous Integration. 
+ Experience with Agile Process and Scrum Methodologies.
+ Excellent written and verbal communication skills in English.

## Optional skills
+ Experience with security, performance, scalability.
+ Experience with NoSQL, Message Queue, gRPC. 
+ Experience with AWS. 
+ Experience with Azure DevOps Services. 

## How we work

We work with a true team mindset, with every member having equal say in how we run our projects, our technologies and our product decisions. We work as a tight and unified team, investing in the development of all members of our team and the furthering of their abilities. 

We focus on creating qualified software and on improving our engineers. You are required to write neat code and follow highly efficient workflow, but you are about to learn tons of new things along the way via pair programming, code review and mentorship. 

## Why you’ll love working with us

- Absolutely no overtime. We respect work-life balance. 
- We fully invest in our team, we will help you build yourself up in any area you feel you need development, be it in English, learning a new programming language, product understanding and more. We want to make sure that you’re always learning and developing yourself whilst a part of our team. 
- We respect both Product and Technology equally, ensuring all of the Products we work on have features with true market potential and ensuring all of the team contribute to, understand and believe in what they are developing. 
- We are very selective with our Clients, we only work on awesome Products we believe in and that show strong market potential. 
- We respect you and your personal hours, we keep sustainable pace by working standard 8 hour days from Monday to Friday, ensuring we only plan for what we can achieve. 
- We work fully Agile, and only work with Clients who work the same, working with set sprint goals and working at our rate of velocity. 

## Contact

Khac Anh: ka_at_codelink_dot_io

**Comment by khacanh** [comment]
Thanks @lactroi !

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
