### ISSUE TITLE
Senior Java (Fintech domain with a mindset on Data Engineering)

### ISSUE THREAD

**Issue by jovibizstack** [awesome-jobs/vietnam#2196]
## Contact me
Jovi Ho: jovi_dot_ho_at_gft_dot_com
Thao Nguyen: thao.nguyen@gft.com
Website: www.gft.com

## Location

* Saigon District 1, Vietnam
* Wework offices

## Salary Expectation

**You'll love it**

## Requirements
* Java, Stream API, Spring Boot, Spring Cloud.
* Redis, Aerospike, Lucene / Elasticsearch / Solr.
* PostgreSQL, RabbitMQ/Kafka
* 5+ years Software Engineering experience for Product company

### Must Have

Please find below the detailed requirement-
* Able to design and build robust & highly scalable distributed services in Java, Stream API, Spring Boot, Spring Cloud.
* Ability to write clean, maintainable and performant code making use of appropriate design principles and patterns.
* Experience in building large, scalable distributed systems with good understanding of microservices architecture and associated principles.
* Experience with building APIs and services using REST, SOAP, etc.
* Experience with TDD/BDD and agile methodologies
* Excellent knowledge of RDBMS such as PostgreSQL and technologies such as Redis, Aerospike, Lucene / Elasticsearch / Solr.
* Having good knowledge of streaming and data pipeline frameworks such as RabbitMQ/Kafka.
* Experience with build automation technologies like Maven, Jenkins, etc.
* Experience with monitoring technologies.

### Ideally

* Experience with Java 11 / Kotlin / Python and Data Engineering stack

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new digital bank with our world-class team of Architect, Engineering, Product and Platform

### Why it would be awesome to work with us
* **Competitive** salary and bonus.
* Opportunities for your professional growth in fintech, especially in digital banking
* Social insurance (max), premium medical insurance
* Parking allowance, snacks, and coffee.
* Monthly team-building and social activities.

### Interesting engineering projects
* We build a professional & fun working environment.
* We focus on your growth, yes the long-term growth.
* We develop the future-ready digital bank platform.

![EA001EFE-A746-4DB5-B675-AF9349CE1DD5](https://user-images.githubusercontent.com/1146571/98456700-72928680-21b3-11eb-9a49-cb4e90704d03.png)

**Comment by jovibizstack** [comment]
![Uploading MicrosoftTeams-image (6).png…]()

**Comment by jovibizstack** [comment]
![Uploading MicrosoftTeams-image (6).png…]()

**Comment by jovibizstack** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/1146571/98456616-7bcf2380-21b2-11eb-8cd0-e5780a4de876.png)

**Comment by jovibizstack** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/1146571/98456665-06b01e00-21b3-11eb-9a62-bf7ddb99c8ea.png)

**Comment by jovibizstack** [comment]
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/1146571/98456673-17609400-21b3-11eb-80cb-8b3296c97c9e.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
