### ISSUE TITLE
Parcel Perform - Infrastructure Engineer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#2197]
![Vietnam](https://user-images.githubusercontent.com/49466111/93553154-803e4380-f99c-11ea-95a8-d113304d74da.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - $3,000

## Requirements
We at Parcel Perform believe in innovation, energy, and resourcefulness for everything we do. We will not stop to deliver an outstanding product that we can be proud of and need you to help us to inform the world. You would be a good fit if the followings describe you:
* You are curious about how complex systems work. You are eager to open up abstraction levels lower than what a typical backend engineer is comfortable with.
* You keep yourself up-to-date on technical trends. You are eager to explore new technologies but are careful in evaluating their merits and tradeoffs based on sound principles rather than hearsay.
* You believe that good tooling and automation systems play a crucial role in an engineering-heavy organization. You like to identify drawbacks of existing, off-the-shell tools, and to build custom solutions to rectify their deficiencies.
* You have the habit of thinking and communicating both qualitatively and quantitatively. You tend to make data-driven decisions and clearly articulate them. You value simple but well-documented solutions over clever but opaque systems.

## Skills
In terms of knowledge and experience, we expect that you have:
* Hands-on experience with cloud-based infrastructures (AWS, GCP, or Azure). Ability to evaluate tradeoffs involved with various cloud services.
* Comfortability writing Bash/Python for ad-hoc automation tasks. Familiarity with infrastructure-as-code practices and tools.
* Fluency with common Unix's administrative tools and administration tasks.
* Good grasp of common network protocols: TCP/IP, TLS, HTTP, SSH... Basic understanding of Linux’s internals. For example process scheduling, memory management, IO mechanisms.
* Clear understanding of different types of storage system, and their respective tradeoffs.

### Must Have
* Experience with cloud-based infrastructures (AWS, GCP, or Azure)
* Bash / Python or any other scripting language

### Responsibilities
Our infrastructure team is responsible for the foundation on which other engineering teams build Parcel Perform’s suite of SaaS products. As a member of the team, you will:
* Work with other engineering teams to design, build and operate cloud-based infrastructures that meet their needs.
* Design and conduct reliability tests. Carry out capacity planning. Identify performance bottlenecks and optimize systems’ performance.
* Manage production incidents, investigate, analyze root causes, resolve issues and build up prevention mechanisms.
* Build internal tools and automation systems that improve engineering productivity, efficiency, and quality. For example efficient CI/CD pipelines, self-service observability tools, code quality checkers. Define workflows, conventions, best practices. Provide guidance for other engineers on how to use these tools effectively.

### Why it would be awesome to work with us
* The opportunity to work in a fast-growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing, and focuses on succeeding - we
continuously work with you on your strengths and weaknesses across many important
dimensions, and look at ways for you to address them and further your development
* Your entry ticket into being part of the Parcel Perform startup Universe, where you will work with and alongside people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast-growing company like competitive salary, extra insurance, free lunch, free fruit, snacks, cool oﬃce, team bonding events, various training programs, and more.

### Interesting engineering projects
You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide. Join our team and help us build our core infrastructure to drive Parcel Perform’s growth!

### Contact
Please apply on our career site: https://parcelperform.freshteam.com/jobs/d4cCsDrP8Faq
Or drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)
Find more jobs and further information about our company: https://www.parcelperform.com/careers

![Date of Arrival Predictions Banner (2)](https://user-images.githubusercontent.com/49466111/93553682-d1026c00-f99d-11ea-92d6-63fa02132704.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
