### ISSUE TITLE
C2C Tech Hub - Senior Back-end Engineer | Platform - Saigon - FT

### ISSUE THREAD

**Issue by phamvuhoang** [awesome-jobs/vietnam#2199]
## Location

* Binh Thanh District, Saigon, Vietnam

## Salary Expectation

* $1,500+

## About us

**C2C Tech Hub** is a startup company with a mission to change the daily-life of people around the world via C2C-type applications. We firmly believe in the future of work where the Customer-to-Customer (C2C) model becomes mainstream and people would benefit greatly from a platform that connects their values. Forming partnerships in various industries, we provide technical expertise and business consultancy to our partners, support their C2C business and competition in the global market.

As our business grows, we set out to develop an in-house platform to support this effort and realize our vision. The platform consists of fundamental building blocks which would be used to develop C2C-type applications for our partners and our own products.

C2C Tech Hub is looking for a Senior Back-end Engineer to join our Platform team in developing its core services. Our platform engineers own their system end-to-end, work on solving complex problems while upholding high quality standards of our services.

## Requirements

* 4+ years of non-internship professional software development experience.
* Minimum 1 year experience in **NodeJS** or PHP.

### Must Have

* Hands on experience with back-end stack:
  OS: Ubuntu, CentOS.
  Proficiency in at least 1 back-end language, preferably ES6 (NodeJS); Familiarity with Typescript is a plus.
  REST API, web socket development.
  Strong experience with MongoDB, familiarity with MySQL, PostgreSQL, Redis, RabbitMQ.
  Cloud services: AWS (preferred), Heroku, GCP.
* Familiarity with CI/CD and TDD practice.
* Bachelor’s degree in Computer Science or equivalent experience.
* Good English skills, especially speaking and writing.
* Willingness to learn new technologies.

### Ideally

* Master’s degree in Computer Science or equivalent experience.
* Programming experience with OOP design; good knowledge of software design, computer networking, algorithms and data structures.
* Strong knowledge of design and development of secure web applications.
* Good understanding of event-driven architecture, distributed systems.
* Strong communication skills in English and Vietnamese; Ability to articulate effectively technical challenges and solutions.
* Ability to deal well with ambiguous and undefined problems, identify underlying requirements from feature requests.
* Ability to write well-documented, well-tested code.
* Hands on experience with modern front-end technologies such as ReactJS and Redux, NextJS.
* Professional, honest, open-minded and have an overall positive attitude.

### Responsibilities

* Design and develop stable, secure and highly available web applications.
* Analyze requirements, identify potential problems and develop appropriate solutions.
* Drive design and development of our platform services and tools, support the continuous development of existing products.
* Participate in all software development activities following the Scrum process.
* Maintain high quality codebase.
* Inspire and provide guidance to junior developers.

### Why it would be awesome to work with us

* A friendly and international working environment.
* Flexible working hours.
* Competitive salary, including 13th month salary.
* Annual health checkup.
* Attractive health care insurance package.
* Up to 18 days paid Annual Leave.

### Contact
Homepage: c2c-techhub.io
Email: hello(at)c2c-techhub.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
