### ISSUE TITLE
NAB VDC - Senior DevOps Engineer (AWS, DBA) - Saigon - FT 

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#2201]
# Location

* Etown Central, Dist. 4, Saigon / Etown 3, Cong Hoa St., Tan Binh Dist.

# Salary Range

* USD Super Attractive 

# Job Overview

#### As a Senior DevOps Engineer, you will join an experienced Agile team and reach your full potential by involving in building innovative products with cutting-edge cloud and microservices technologies..

# What will you be responsible for? 
* Collaborating with other NAB's technology leaders towards improving and fulfilling the NAB technical direction;
* Define/implement tools and processes to standardize and automate the way project software is developed, built, tested, and deployed;
* Take responsibility to ensure a homogeneous way of implementing continuous integration and/or continuous delivery across projects;
* Be responsible for monitoring and reporting to management the status of applying and implementing DevOps processes across projects;
* Assist with the development and design of resilient, secure, supportable, and scalable systems;
* Automate infrastructure deployments and rollbacks for all developed work, assuming responsibility for process support;
* Lead investigations into production incidents with assistance from the development team;
* Proactively manage any risks to the production environment;
* Continually improve the supportability of our systems by feeding improvements back into the design and development cycles. 

# What we look for:
* At least 5 years of DevOps engineering experience;
* Have an in-depth understanding of microservices architecture, API management, and distributed systems concepts;
* Solid experience with cloud services is essential, in particular, our core AWS Technologies (EC2, ECS, Lambda, S3, SQS, SNS, & Cloud Watch) or Azure Technologies
* Excellent scripting skills in Linux with shell scripting & python and automation experience with Ansible & Terraform. 
* Experience in building CI/CD pipeline automation, tooling (Github, Jenkins, Artifactory, Docker, and Kubernetes) and Compliance as code;
* Strong English communication skills (both verbal & written), especially in the global software development environment

### Nice to have:
* Security Skills ( XSS attacks, SQL attacks, and more)
Good understanding of RDS Databases, Redis Clusters
* AWS Batch
* Basic under of Java and Restful APIs

# Why it would be awesome to work with us?

* Join a global software development environment
* Competitive remuneration package with an attractive Tet sign-on bonus 
* Enjoy exceptional perks (tech/non-tech training courses, extra health insurance for you and your family (2 members), daily snack, billiards competition, ... you name it.)
* Business Trips to Australia
* Comfortable and inspiring workplace

### Want to experience yourself? Visit our brand new Agile office & have a chat with us over a cup of coffee!

# Contact

* E: linh.truong@nab.com.au 
* M: 0787 363 214
* Skype: linh.truong.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
