### ISSUE TITLE
BoringPPL - Mid Fullstack Engineer (NodeJS & ReactJS) - HCMC/Remote - FT

### ISSUE THREAD

**Issue by daph-td** [awesome-jobs/vietnam#2202]
## Location

* HCMC, Vietnam
* Remote

## Salary Expectation

* $700-$2000/month

## Requirements
* 3+ years of experience as a Full-stack developer
* NodeJS and ReactJS

### Must Have

Backend
* Programming Language: NodeJS / Python / Scala
* Knowledge of user authentication and authorization between multiple systems, servers, and environments
* Understanding of fundamental design principles behind a scalable application
* Understanding of the differences between multiple delivery platforms, such as mobile vs desktop, and optimizing output to match the specific platform
* Able to create database schemas that represent and support business processes
* Ability to develop and implement open source software projects
* Effective operation in a fast-paced, deadline-driven, and collaborative programming environment

Frontend
* Strong working knowledge of HTML5, CSS, JavaScript and ReactJS
* Ability to develop and implement open source software projects 
* Using the cutting edge of HTML 5, Javascript, AJAX and CSS to develop and test on the latest desktop and mobile browsers.
* Develop innovative Web-based tools and specifications, and make recommendations on the use of new and emerging technologies for a wide variety of projects for our clients.

### Ideally

* Desire to learn and adapt to new technologies
* Able to work independently and effectively in a team
* Strong attention to detail, analytical and love solving problems 
* Good verbal and written communication skills
* Ability to work in a fast-paced environment 
* Excellent time and project management skills

## Responsibilities

Great power comes with great responsibilities!

### Participate in entire application lifestyle

* Build robust and scalable software in NodeJS and ReactJS
* Write clean code to develop functional web applications on mobile and desktop
* Review and implement UX/UI designs
* Implementation of security and data protection
* Design and implementation of data storage solutions

### Support internal improvements

* Build reusable code and libraries for future use
* Continuously improve your programming skills 
* Develop and propose new products or features by monitoring the industry

### Collaborate closely with internal teams

* Collaborate with other developers and designers to build user-friendly interfaces, and integrate it with server-side logic
* Work closely with the designers, product managers, and system administrators to identify and build new features 
* Provide training and support to internal teams

## Why it would be awesome to work with us
You'll work closely with a fast-growing team of 3-4 world-class teammates, who graduates from MIT, Cambridge, NUS, etc. and have years of full-time experience at bluechip companies like PayPal, Bain & Company, Google, etc. to build robust software on the back-end and front-end.

### Interesting engineering projects
Check this out: http://talent.boringppl.com/#exciting-products

### Contact
Details and Apply : http://talent.boringppl.com/
Skype: daphne.win | Whatsapp/Telegram/Zalo/iMess: (+84) 938 605 402

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
