### ISSUE TITLE
Orange Logic - QA Engineer - Saigon - FT

### ISSUE THREAD

**Issue by hanguyenOL** [awesome-jobs/vietnam#2204]
## Location

* HCMC, Vietnam

## Salary Expectation

* $1500+/ Negotiate

## Requirements

- An average command of **English** (oral + written)
- A strong drive to build the **perfect product**
- **Organizational** skills, attention to **details** and high level of **empathy**
- Significant experience with **testing** of **complex** applications required
- A fundamental understanding of software development.
- Strong self-discipline for delivering well-tested, complete features/modules under a tight schedule and the capability for rational thinking.
- Practical experience on a web-based application is a plus

## Your Responsibilities

>As a QAE, you will help to ensure that the product systematically meets and exceeds our users expectations.

You will contribute by designing & executing the **most efficient manual testing strategy** to ensure that:

1. **90+% of defects are identified & documented before reaching the end users**

*Exclusive of defects that can only be detected in the client environment*

2. **All features behave as they should (i.e no regression)**

*For all the releases supported*

3. **All new features are evaluated from an End User perspective**

*Understand users and create relevant testing scenarios*

4. **Proactively suggest improvements for our product and methodologies**

*Report what does not work well or is broken, even if not part of the current assignments*

### Must Have

* Strong self-discipline for delivering well-tested, complete features/modules under a tight schedule and the capability for rational thinking.

### Why it would be awesome to work with us

>At Orange Logic, it does not matter how many years of experience you have, or your age. We believe that each individual, regardless of these factors, has the ability to evoke change within the organization.
* Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development.
* Amazing team: smart, open-mind, and passionate engineers. They came from the US, France, UK, and Vietnam hence you could improve your English and explore different country cultures.
* 18 days of annual leave (cashback for unused days) + 4 days for an abroad company trip (Taiwan, Thailand, etc)
* 13th-month salary no matter when you join the team
* Performance bonus 
* Monthly team outing activity
* Premium healthcare insurance ($10.000 cover) after probation
* Full Insurance based on your Gross salary
* Allowances for lunch, gym, parking ($100)
* Birthday bonus ($100), Tet gift, etc
* Daily free snacks, fresh fruit, coffee & soft drinks
* Latest gadgets for work (include noise-canceling headphones)

### Contact
* Please send your resume to ha.nguyen@orangelogic.com
* You can drop me a message on [Skype](https://join.skype.com/invite/mNKg28GbjKfr) or [Linkedin](https://www.linkedin.com/in/ha-nguyen-01a752ba/)
* [Our Homepage ](https://www.orangelogic.com/digital-asset-management-customer-examples)

> Can't wait to have a detailed discussion if you have any questions or concerns!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
