### ISSUE TITLE
JobHopin - Senior DevOps Engineer - Dist.1, HCMC - PT

### ISSUE THREAD

**Issue by mlebui13** [awesome-jobs/vietnam#2205]
## Location

 Vinhomes Bason, Dist.1, HCMC

## Salary Expectation

** Up to $2600**

##Job Overview

**We are looking for an experienced DevOps (Development and Operations) professional to join our fast growing organization. In this position, you will manage project’s infrastructure and processes. Keen attention to detail, problem-solving abilities, and a solid knowledge base are essential.**

##What will you response for?

- Work directly with development team and team leader to manage and monitor project’s infrastructure.
- Setup and manage CI/CD.
- Hands-on experience with cloud resources and services such as AWS, Microsoft Azure, Google Cloud...
- Handle code deployment in all environments.
- Monitor metrics and work out improvements.
- Strictly follow all processes and best practices laid out by the team as well as contributing in developing said processes.

## What we look for:

- Firm knowledge and experience working as a DevOps or related position in a product company environment.
- Familiarity with Linux infrastructure, database systems (MySQL, Redis, MongoDB, etc.)
- Familiarity with container management platforms such as Docker, Docker Swarm, Kubernetes, etc.
- Familiarity with CI/CD tools & scripting.
- Familiarity with Agile workflow methodologies (SCRUM).
- Good programming skill (Python, Ruby)

## Why it would be awesome to work with us:

- Health insurance and Social insurance regulated by Vietnam Labor Law.
- KPI - performance based bonus and promotion.
- 13th month salary 
- Happy Friday with delicious food and drinks provided
- New Computer (Macbook/ Window) that fits your need.
- Competitive compensation and regular assessments and salary reviews.
- The opportunity to learn/ improve your business English.

### Contact

- Email: le.bui@jobhopin.com
- Phone: 0396 190 884
- Skype: live:.cid.5b6eb8c33606ee7b

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
