### ISSUE TITLE
Crane - Full-stack NodeJS Software Engineer - Remote - Contract

### ISSUE THREAD

**Issue by thsonvt** [awesome-jobs/vietnam#2206]
## Location

[Crane](https://www.wearecrane.com) is a community for lifelong learning and a social space where like-minded individuals gather for fitness, workshops, lifestyle events, and co-working.  

* Remote

## Salary Expectation

* $ 2000 - 3000 (Negotiable )
* This is a contract job but will be open to full-time remote job in the future

## Requirements
* Set up/maintain the cloud infrastructure of web applications.
* Self-driven, detail-oriented, and has the ability to work independently.

### Must Have

* 2-3 years of development experience using Ruby on Rails OR Node.js Express (backend) + Javascript with framework React|Vue|Svelte (frontend) + PostgreSQL
* Hands-on experience in AWS
* Good communication skills to communicate with the team and other stakeholders

### Responsibilities

* Collaborate with client/project manager to understand user requirements and provide technical solutions.
* Develop excellent quality software using agile techniques.

### You’ll be responsible for

* Help Crane fly to the next level.

### Why it would be awesome to work with us
Because it's a company that is growing and a very international team

### Contact
Homepage: https://www.wearecrane.com
Trollman: federico_at_wearecrane_dot_com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
