### ISSUE TITLE
UNIT_Middle Manual Tester_Full Time_Dist 3 #tester #manualtesting #APITesting

### ISSUE THREAD

**Issue by PhamNhuY18** [awesome-jobs/vietnam#2207]
## Location

* Saigon, Vietnam
* Full Time: From Monday to Friday

## Salary Expectation

* up to $1200/month 

## Requirements
* Minimum of 3+ years working as QA/QC or Test Engineer in a Software Development.
* Experience in design test plan, test cases, test procedures, reporting test result, issues/bugs.
* Experience in executing testing on software application, web application and mobile app.
* API Testing as Postman, SoapUI,...

### Ideally

* Experience with API Testing

### Responsibilities

•	Reading and documenting software requirements in English
•	Write a test plan, test case, execute test case
•	Supporting the BA team to update documents when there are new requests
•	Software testing on Website, Mobile ...
•	Managing the life cycle of errors.
•	Coordinate with programmers to analyze errors and fix errors
•	Ability to analyze quickly and get the job done quickly
•	Perform the tasks assigned by the Manager
•	Support customer testing software

### You’ll be responsible for

* Join project in Fintech as banking, finance, insurance,..

### Contact
Homepage: unit.com.vn
Mail: yptn@unit.com.vn
Skype: yptn13405

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
