### ISSUE TITLE
Holistics.io - Open-source Software Engineer - Junior/mid-level - HCMC

### ISSUE THREAD

**Issue by nvquanghuy** [awesome-jobs/vietnam#2210]
Holistics is looking for a full-stack open-source software engineer to work on an ambitious open-source project that has potential to impact developer teams around the world.

![fullstack_engineer](https://user-images.githubusercontent.com/519800/99372099-4e8d1e80-28f2-11eb-8764-ed150cce48ee.jpg)

## Background

We launched [dbdiagram.io](http://dbdiagram.io/) as a side-project in late 2018 with no marketing budget (still no marketing budget now) and at the moment (Nov 2020) it has over 250K users with over 70K monthly active users (MAUs), with than 70% of them are developers.

Our second project, [dbdocs.io](http://dbdocs.io/), is a tool to help developers create database documentation site for their applications.

Seeing the potential of this, we spun off its DSL language into open-source language DBML ([github](https://github.com/holistics/dbml)) to define database schema. It has been picked up and adopted by organizations across the world since.

Our vision is to see DBML become the open-source industry standard for defining database schema for every web application. Imagine in every web application, there is a `database.dbml`  to represent the database structure.

We’re looking for a junior/mid-level full-stack engineer who’s excited by this vision to join us on this ambitious project.

## Job Scope

Work on developing 3 related projects revolving around database documentations:

- Our open-source database markup language: [dbml.org](http://dbml.org/)
- Our database documentation tool (based on DBML): [dbdocs.io](http://dbdocs.io/)
- Our database diagram drawing tool (based on DBML): [dbdiagram.io](http://dbdiagram.io/)

## Requirements
- Strong problem solving (most important)
- Excited about working with open-source projects or developer-tool softwares
- Experiences with JavaScript/NodeJS a plus (though not required)
- Have at least 1 year of experiences in Software Development
- Good English communication skill (reading and writing)
- Both senior and junior positions are welcome

## Benefits

- Compensation: 800$ - 1300$
- 14 Annual leaves/year, 14 Sick leaves/year
- 13th month-salary; Performance review twice a year
- 24/7 Healthcare Insurance, Periodic Medical Checkup
- Shares (Stock Options) for high-contributing individuals
- Workstation provided for maximal productivity: Macbook (or Laptop), Leopold FC750R mechanical keyboard, Razer Abyssus V2 computer mouse, 24’ Ultrasharp Monitor
- Active and agile working environment; Flexible time culture; Weekly happy hours.
- Weekly TED talks to expand skills and knowledge, games and social sport activities with company; Company trip and company-organized events.

## Location
* Saigon, Vietnam

### Contact

Apply at: https://careers.holistics.io/6vdhgd3/open-source-fullstack-engineer

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
