### ISSUE TITLE
FinOS Technology - Senior DevOps and IT Operations Engineer - Ha Noi - FT

### ISSUE THREAD

**Issue by Uyenai** [awesome-jobs/vietnam#2211]
## Location

* Ha Noi, Vietnam
* Full-time

## Salary Expectation

* Up to 2,000 USD gross

## Requirements
* DevOps
* Lenux
* AWS
* 5+ years experience

### Must Have

* Experience with CI/CD tools (Jenkins is prefefed) and infstrastructure as code (AWS Cloudformation, Terraform, Ansible)
* Experience on Kubernetes, Rancher, Microservices
* Experience in managing Git or other Git on cloud services
* A deep understanding of the Linux operating systems.
* Ability to debug and solve configuration, performance and reliability problems quickly; sometimes under pressure if there are issues that are directly affecting product users.
* Knowledge of standard methodologies: configuration management, monitoring, alerting, metrics.
* Knowledge of networks basis and work of TCP/IP.
* Knowledge of database administration (Postgres, Elastic search)
* 3+ years of operational experience as System Administrator or System Engineer or DevOps engineer.
* Scripting and/or development skills to automate everything.
* Ability to automate routine processes using Python, Bash.
* Good service attitude and proactive

### Ideally

* Proficient English
* Experience in Java/Spring Cloud/Spring Boot programing

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop and maintain an understanding of the software development and deployment pipeline. This includes initial software architecture and development, the continuous integration workflow, deployment of software through the pipeline to production, and monitoring of software and infrastructure in production.
* Participation in managing DevOps side of things of new applications and projects.
* Work with high load applications.
* Design and build infrastructure on AWS/on-premises -- Kuberntetes.
* Monitor and maintain alive services and servers on AWS/on-premises -- Kuberntetes.
* Design highly available and fault tolerant environments.
* Make automation systems to deploy must do so reliably with zero downtime and the ability to easily rollback.
* Providing support Level 2 (L2) for production system (troubleshooting, fixing or create L3 ticket for development team)
* Support internal users on IT system (operating system, network, VPN)
* Design and implement monitoring and alerting that are actionable.

### Why it would be awesome to work with us

* Personal healthcare insurance
* 15 AL & 30 sick leaves
* Lunch box, Macbook

### Interesting engineering projects
* Fintech projects

### Contact
Homepage: https://finos.asia
Facebook: https://www.facebook.com/finosvietnam
Email: ly.duong@finos.asia

**Comment by Uyenai** [comment]
Thanks @lactroi for adding the labels for us

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
