### ISSUE TITLE
FinOS - DevOps (Senior to AM level) - HN

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#2212]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to $US2500/month

## About us

* FinOS is a Fintech company funded by Allianz SE - the world’s most trusted financial service provider, headquartered in Munich, Germany (https://www.allianz-asiapacific.com). FinOS’ mission is to provide simple, affordable and tech-enabled financial products & services through all digital ecosystems across SEA.

## Job description
* We are looking for the passionate DevOps Engineer (From Senior to AM level) to join our fantastic highly skilled team of operation engineers to help managing, developing and extending our robust infrastructure (We utilize both AWS and on-premises). We are looking for someone who loves containerized, who is intimately familiar with microservice infrastructure based on Kubernetes, who wants to obtain and increase the skills in scalability and performance load management.

### Position Responsibilities

* Develop and maintain an understanding of the software development and deployment pipeline. This includes initial software architecture and development, the continuous integration workflow, deployment of software through the pipeline to production, and monitoring of software and infrastructure in production.
* Participation in managing DevOps side of things of new applications and projects.
* Work with high load applications.
* Design and build infrastructure on AWS/on-premises -- Kubernetes.
* Monitor and maintain alive services and servers on AWS/on-premises -- Kubernetes.
* Design highly available and fault tolerant environments.
* Make automation systems to deploy must do so reliably with zero downtime and the ability to easily rollback.
* Providing support Level 2 (L2) for production system (troubleshooting, fixing or create L3 ticket for development team)
* Support internal users on IT system (operating system, network, VPN) 
* Design and implement monitoring and alerting that are actionable.

### Your skills and experience

* Very fast learner
* Experience with CI/CD tools (Jenkins is preferred) and infrastructure as code (AWS Cloudformation, Terraform, Ansible)
* Experience on Kubernetes, Rancher, Microservices
* Experience in managing Git or other Git on cloud services
* A deep understanding of the Linux operating systems.
* Ability to debug and solve configuration, performance and reliability problems quickly; sometimes under pressure if there are issues that are directly affecting product users.
* Knowledge of standard methodologies: configuration management, monitoring, alerting, metrics.
* Knowledge of networks basis and work of TCP/IP.
* Knowledge of database administration (Postgres, Elasticsearch) 
* 3+ years of operational experience as System Administrator or System Engineer or DevOps engineer.
* Scripting and/or development skills to automate everything.
* Ability to automate routine processes using Python, Bash.
* Good service attitude and proactive
* Proficient English
* Experience in Java/Spring Cloud/Spring Boot programing is preferred.

### Contact
Our website: finos_dot_asia
Our HR team: hr_dot_vn_at_finos_dot_asia
[FinOS JD DevOps Engineer_Nov 2020.pdf](https://github.com/awesome-jobs/vietnam/files/5572461/FinOS.JD.DevOps.Engineer_Nov.2020.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
