### ISSUE TITLE
FinOS - Solution Architect (SA) - HN

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#2213]
## Location

* HN, Vietnam

## Salary expectation
* Up to $US6000/month

## About us

* FinOS is a Fintech company funded by Allianz SE - the world’s most trusted financial service provider, headquartered in Munich, Germany (https://www.allianz-asiapacific.com). FinOS’ mission is to provide simple, affordable and tech-enabled financial products & services through all digital ecosystems across SEA.

## Key Responsibilities 
* Level of this position: Senior SA to Chief SA
* Providing technical consultation to prospects and clients regarding frameworks, methodologies, off-the-shelf products and custom solutions for the client's enterprise or their solution's architectural needs
* Responsible for leading strong architecture practices, especially for large enterprise applications (including financial systems, B2B e-commerce, and system integration)
* Consult the operation team on infrastructure architecture, architecture practices, and operation practices
* Responsible for the optimization of development practices and environments, providing hands-on assistance through code reviews and providing reference examples
* Troubleshooting for performance, scalability and availability issues for integrated solutions, and debugging production problems
* Leading technical pre-sales activities, including providing estimations, quotations, and solutions for proposals
* Coaching and mentoring technical architects and developers on the team
* Hands-on coding when needed. 

## Required competencies and skills

* Very fast learner
* 8+ years of experience in web development technologies in general, with in-depth knowledge of Java, Python, and DevOps
* Experience with web and/or mobile development, designing secured, high-performing, high availability, scalable systems, including hosting and infrastructure
* DevOps experience with on-premise, AWS and/or Azure
* Experience architecting, developing and deploying microservices
* Experience working with financial systems (e.g., Lending or Investment) and e-commerce platforms.
* Soft skills: leading client and team discussions, team player, ability to train others
* Strong work ethic, self-motivation, dedication, and commitment
* Excellent technical documentation and diagramming skills
* Very strong English communication skills (both written and speaking)
* Passionate with new technologies e.g., Blockchain, AI, FinTech, Cloud, Containers, etc.
* Prefer to have a good understanding in Cloud/Container technologies

## Line Manager

* This position is reporting to Chief Architect or CTO.

### Contact
Our website: finos_dot_asia
Our HR team: hr_dot_vn_at_finos_dot_asia
[FinOS JD SA Nov 2020.pdf](https://github.com/awesome-jobs/vietnam/files/5572616/FinOS.JD.SA.Nov.2020.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
