### ISSUE TITLE
FinOS - Data Engineer - HCM

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#2214]
## Location

* Saigon, Vietnam

## Salary expectation
* Up to $US5000/month

## About us

* FinOS is a Fintech company funded by Allianz SE - the world’s most trusted financial service provider, headquartered in Munich, Germany (https://www.allianz-asiapacific.com). FinOS’ mission is to provide simple, affordable and tech-enabled financial products & services through all digital ecosystems across SEA.

## Hiring position

* FinOS is the definitive platform for financial services that powers digital financial products & services across Southeast Asia. We pave the way to provide financial support to the unbanked through simple, affordable and tech-enabled financial products & services. 
* FinOS’ Data Science (DS) team is responsible for ensuring the company is well equip with the skills and technology needed to improve, change and solve engineering problem involving system, integration, deployment and development. DS runs multiple environment using continuous integration and deployment practice. We work side-by-side with the business to define the technical requirements and with the data science team to implement scalable, production-ready API and infrastructure using best practices. 

## Key Responsibilities 

We are seeking a customer-focused, passionate and driven Data Science Engineer with experience in developing Python-based API and cloud-based infrastructure. With the large volume of data which we will be leveraging, our job is to build and maintain proper data processing solution to bring reliable experiences for our customers. If you’re interested in being a part of a team that’s constantly learning and problem-solving, we’d love to talk with you. As a Data Science Engineer, you work closely as part of a small setup in FinOS to lead the design and implementation of systems and tools to support the effort of FinOS. You will be: 

* Developing and implementing production backend system to serve data science prediction. 
* Designing system and data architecture. 
* Working with partners to integrate systems. 
* Problem-solve and develop solution at the intersection of data and systems. 
* Innovating by recognizing opportunities for automation and tools improvements. 
* Providing technical leadership for a team of data scientists. 

### Required competencies and skills

* Mastery of one of Python, or similar language. 
* Experience with Relational databases or NoSQL databases. 
* Proven understanding of the full software development lifecycle including testing,  continuous integration, and deployment. 
* Excellent problem solving, critical thinking, and communication skills. 
* Solid grasp of computer science fundamentals including data structures and algorithms. 
* Understanding on machine learning techniques. 
* Proven ability to evaluate and apply new technologies in a short time. 
* Self-motivated, proactive, and solution-oriented. 
* Experience with cloud platform services desired. 
Additional Requirements 
* Experience in building data science or data analysis tools a plus. 
* Machine learning background a plus. 
* Familiarity with Agile software development process, Test-Driven development and Continuous Integration a plus. 
* Familiarity with DevOps tools such as Ansible and Terraform a plus. 

### Line Manager

* This position is reporting to Chief Data Scientist.

### Contact
Our website: finos_dot_asia
Our HR team: hr_dot_vn_at_finos_dot_asia
[FinOS JD Data Engineer.pdf](https://github.com/awesome-jobs/vietnam/files/5572852/FinOS.JD.Data.Engineer.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
