### ISSUE TITLE
[LARION] - [Senior DevOps Engineer - [Saigon] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#2215]
### Location

* QTSC Building 1, Quang Trung Software City, District 12

### Salary Expectation

* 1500$ - 2500$

### Requirements

* At least 3 years of experience with DevOps Engineer or relevant position
* Solid understanding and working experience with Linux
* Hands-on knowledge of Docker, Podman, LXC
* Experience with CI/CD, GitLab (preferred), GitHub or Git
* Good experience with AWS
* Experience in network engineering
* Good troubleshooting and problem solving skills

### Responsibilities

We are looking for a great DevOps Engineer who will work closely with Software Engineers to help them
deploy and operate different systems. In addition, they help to automate and streamline operations and
processes. Being our DevOps Engineer, you will focus to:

* Create and improve deployment workflows and system automation scripts
* Execute deployment and upgrade on-going releases in development
* Support development team to troubleshoot and resolve system problems
* Set up technical environment for development team
* Monitor servers for uptime and functionality
* Revise and ensure data are stored and distributed in a secure manner
* Automate maintenance processes
* Improve and enhance existing CI/CD pipeline
* Administer and improve existing AWS infrastructure
* Ensure high reliability and availability of all the components of the system

### Why it would be awesome to work with us
 
* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, etc.

### Contact

* Please send CV via email: ngocttb@larion.com
* For further information, please contact via Skype: ngoctranthibao / Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
