### ISSUE TITLE
[LIKELION] Python Data Engineer & JS Fullstack Developer (React.js & Node.js) - HCMC

### ISSUE THREAD

**Issue by RyanKor** [awesome-jobs/vietnam#2217]
![Artboard 1@4x](https://user-images.githubusercontent.com/40455392/100598076-d29ec780-3330-11eb-9bcd-7eded7852900.png)

## Location

* HCMC, Vietnam
* Remote

## Salary Expectation

- At least $2000 per Course
- We can negotiate the payroll according to your skill level

## Requirements

- Minimum of 3 years of experience as a software engineer (CV Required)
- Very fluent to use JS or Python
- A wealth of fieldwork development knowledge to help students

## Skills(Optional, preferred)

- Programming Course Instructor Experience (we will have an extra lecture interview)
- A person who can handle more than one of the two items below.

    1. React, Typescript, GraphQL, Apollo, Node.js, MongoDB
    2. Python, Numpy, Pandas, Tensorflow, Scikit-learn, Keras

### Must Have

* Python, Data engineering project experience

OR

* JS Stack Project Experiences

### Roles & Responsibilities

- We focus on part-time, long-term work, for freelancing side jobs.
- We are finding a self-driven person who is eager to learn new technologies.
- Make an online programming course during our contract
- Check course review after you make all the lecture
- Q & A discussion with course students

### You’ll be responsible for

* Building a new online programming course
* If you have no experience to make an online course, no worries. LIKELION has a guideline to build the course.

### You can bring

* A fine sense to make a course curriculum & lecture
* A good analysis skill
* A good communication skill between you and LIKELION Team

### Contact
    - Email : likelion.vn@likelion.net
    - Phone : 090-888-5090

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
