### ISSUE TITLE
[LARION] - [Senior Fullstack Python Engineer - [Saigon] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#2218]
### Location

* QTSC Building 1, Quang Trung Software City, District 12

### Salary Expectation

* 2200 - 3000$

### Requirements

* At least 3 years of working experience with web development
* Experience with front-end side: HTML, CSS, JavaScript, JavaScript frameworks
* Experience with Python web frameworks such as Django, Flask, etc.
* Experience in developing scalable and robust software applications in web environments
* Have working knowledge and experience with Unix/ Linux environment
* Have good knowledge and experience with databases such as MySQL, PostgreSQL

### Responsibilities

We are looking for a great Full-stack Python Developer who will be one of the key contributors in our organization and develop high quality software solutions. Being our developer, you will focus to:

* Understand and analyze the requirements/ designs clearly
* Implement features from design specifications and deliver code with high quality
* Perform code review, code refactor
* Ensure components and the overall application are robust and easy to maintain
* Contribute to all aspects of the product development process, from specification and design, throughout integration, release and maintenance
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency

### Why it would be awesome to work with us
 
* Attractive salary and benefits (13th Salary, Outstanding employee of the quarter and the year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Various training on technical and soft skills
* Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.
* Commitment to community development: charity every quarter, blood donation, etc.

### Contact

* Please send CV via email: ngocttb@larion.com
* For further information, please contact via Skype: ngoctranthibao / Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
