### ISSUE TITLE
HirePost - iOS developer - Remote - FT

### ISSUE THREAD

**Issue by thsonvt** [awesome-jobs/vietnam#222]
## About

The people here at HirePost don’t just work on a solution, we have a journey — we create the kind of wonder that will create opportunities for people to apply jobs for better lives ahead simply. It’s the challenges of those people and their initial thoughts that inspire the creation that runs through everything we do, from amazing technology to go to market efforts.

Join HirePost, and help us make the world better than we wish to be in. We are looking for an iOS Developer who possesses a passion for making magic with mobile technologies and challenge the management to build the next generation of mobile applications to meet our vision for better lives. Remember, right jobs and better lives ahead and that’s the mission and vision we have at HirePost.
## Location

Vietnam, Remote

This position is on the remote basis, you will be working along with the business development person based in Singapore and the designer based in the US. 
## Salary Expectation
- 1000 SGD /month (negotiable). There will be additional bonus if you perform well.
## Requirements
- Design and build advanced applications for the iOS platform
- Collaborate with cross-functional teams to define, design, and ship new features.
- Unit-test code for robustness, including edge cases, usability, and general reliability.
- Work on bug fixing and improving application performance.
- Continuously discover, evaluate, and implement new technologies to maximize development efficiency.
### Must Have
- BS/MS degree in Computer Science, Engineering or a related subject
- Proven working experience in software development
- Working experience in iOS development
- Have published one or more iOS apps in the app store
- Experience with third-party libraries and APIs
- Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies
- Solid understanding of the full mobile development life cycle
### Ideally
- Passionate about developing a mission to help others
- Experience working with iOS frameworks such as Core Data, Core Animation, Core Graphics and Core Text
### Contact

Email your CV to : [bizdevt@live.com]

**Comment by solarcraft** [comment]
Did you find the appropriate developer ? I would like to apply for iOS developer position?

**Comment by thsonvt** [comment]
We are still looking for the developer. Please go ahead with applying.

**Comment by joneslee85** [comment]
@thsonvt thanks for posting. Please revise following:

* fix up the bullet point format (please use `*`)
* do you represent the HR of the company? the email states that you are on `live.com`, I'd prefer to have contact point of the company's own domain

Thanks

**Comment by thsonvt** [comment]
@Trung Lê,

Thanks for help with correction of the format. I don't represent the HR, I
was just helping my friend to hire a developer. He's still early with his
startup, he has bought a domain name but has no time to setup the email
address with the domain name yet.



On Tue, May 31, 2016 at 7:17 AM, Trung Lê <notifications@github.com> wrote:

> @thsonvt <https://github.com/thsonvt> thanks for posting. Please revise
> following:
>
>    - fix up the bullet point format (please use *)
>    - do you represent the HR of the company? the email states that you
>    are on live.com, I'd prefer to have contact point of the company's own
>    domain
>
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/awesome-jobs/vietnam/issues/222#issuecomment-222564793>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAzexit3zq-132I91y5OSQYUbMkdw2kxks5qG3AIgaJpZM4IphEu>
> .
>



-- 
Warmest regards,
Son
Whatsapp: +6598008187
Skype: thsonvt

**Comment by joneslee85** [comment]
@thsonvt any update on the job post format? I am sorry that I will have to close this issue if there is no update within next 24hrs.

**Comment by thsonvt** [comment]
@joneslee85 I have updated the job post format. Sorry for inconvenience caused.
