### ISSUE TITLE
Senior Machine Learning Engineer - Saigon - FT

### ISSUE THREAD

**Issue by zer0n** [awesome-jobs/vietnam#2220]
<img src="https://user-images.githubusercontent.com/3055719/81139074-a5528c80-8f8e-11ea-99ad-f26f90201589.png" width="200">

Koidra is hiring top-notch machine learning research engineers (MLE) or engineering-minded ML researchers for a highly specialized research direction (`Neural Differential Equations` or `Physics-informed Deep Learning`) with global application impact.

## Location
* Saigon, Vietnam
* Remote

## Salary Expectation
* $3000-$5000/month, depending on your competence and fitness

# Responsibilities
- Contribute to the development of our proprietary machine learning frameworks
- Develop and train end-to-end models
- Deliver results

# Qualifications
### Must Have
- Excellent programming, debugging, and analytical skills. (To be a MLE at Koidra, you need to be a rock-solid software engineer first.)
- Experience in building complex Deep Learning models using PyTorch
- Solid understanding of mathematical modeling, differential equations, numerical methods, matrix computations. Good understanding of Physics is a plus.

### Preferred Qualifications
- Familiarity with and strong interests in one or more of the following machine learning research areas: `model-based reinforcement learning`, `bayesian learning`, `neural differential equations`, `uncertainty quantification`
- Experience in building models for time series or sequential data

### Exceptions
We also hire fresh graduates who are high achievers, having high potential, and interested in real-world machine learning.

# About Us
Founded by Kenneth Tran, formerly a Principal Machine Learning Scientist at Microsoft Research (MSR), Koidra's mission is to change the industrial automation industry, applying cutting edge research in AI, IoT, and hybrid cloud+edge computing. Check out some early **[media coverage about us](https://www.notion.so/Press-Releases-354cdc2b6461476b98c2d01dfa1d22dc)**.

At Koidra, you'll have an opportunity to work with world experts in both Machine Learning and Software Engineering.

### Koidra's Core Principles
Please read carefully our [Core Principles](https://www.notion.so/Core-Principles-3ad14330f8ab4e418e8c1dc35968d9bb) before applying. We live and breath these principles.

# How to Apply
Does this role sound like a good fit? Send us your resume to careers@koidra.ai

**Comment by huuthonguyen76** [comment]
Hi, Is the position still available?

**Comment by zer0n** [comment]
Yes, it is still available.

**Comment by huuthonguyen76** [comment]
Actually, I've sent the email with my resume. But I don't see any replies yet. Just want to make sure if you're still hiring this position.

**Comment by zer0n** [comment]
Sorry about that. The email careers@koidra.ai seems to be changed to hr@koidra.ai. Please send again. Thank you.

**Comment by huuthonguyen76** [comment]
Thanks, I've already sent.
