### ISSUE TITLE
Back-end Developer (Golang) - PRESSMERCE - FT - HN

### ISSUE THREAD

**Issue by lamhoang-nhatphuong** [awesome-jobs/vietnam#2221]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* From 15 Mil VND 

## Requirements
* Golang
* MySQL,
* PostgreSQL
* 2+ years Backend Development experience

### Must Have

* 2+ years Backend Developer
* Experience with Golang

### Ideally

* Knowledge of MySQL, Postgresql
* Knowledge of GraphQL is an advantage.
* Knowledge of data structures and algorithms is an advantage.
* Knowledge of information safety and security is an advantage

### Responsibilities

* Design, develop and maintain corporate internal software systems.
* Build a high-performance and optimized backend system, responsive to traffic and big data.
* Coordinate teamwork under the assignment of Project Manager.
* Participate in researching optimal solutions, system security; Contribute ideas about technology and products.

### Why it would be awesome to work with us

* Average income from 15 million or more, depending on capacity.
* Lunch allowance 30,000 VND + parking allowance. Salary and reward worthy of work performance and capacity.
* 13th-month bonus + business performance salary of the company.
* Bonus holidays, Tet according to the business situation of the company.
* To sign a labor contract and fully enjoy the benefits prescribed by the State (pay social insurance, health insurance, and unemployment insurance premium).
* Consider increasing salary every 6 months.

### Contact
Homepage: https://pressmerce.com
Send CV via mail: nhatphuong.lamhoang@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
