### ISSUE TITLE
[gumiVietnam] - Middle Fullstack PHP Engineer - [Saigon] - [FT]

### ISSUE THREAD

**Issue by huytp** [awesome-jobs/vietnam#2222]
## Location
* 39, Nguyen Thi Dieu, ward 6, district 3, HCMC
* Fulltime

## Requirements
* Proficient in PHP (Laravel);
* Proven experience in developing application with Laravel;
* Experience 2 year wiht Vue JS or angular JS Experienced with GIT;
* Experienced with SQL database;
* Self-motivated, 
* excellent problem-solving skills, attention to detail and ability to learn new technologies quickly and work well.

### Big Plus:
* Experience in Socket handling.Experience in developing systems/ websites can handle many requests simultaneously.
* Experience in building / coding big data systems.

### Why it would be awesome to work with us
* Working in a professional, friendly, well-equipped environment both with Japanese and Vietnamese.
* Career path promotional opportunities.
* Labor contracts, insurance, annual days off are based on Vietnamese law.

### Contact
* Please send CV via email: phuhuy.tran@gumiviet.com
* For further information, please contact via Skype: mr.phuhuy / Zalo: 0974044308
[Job Description_PHP_ Middle.docx](https://github.com/awesome-jobs/vietnam/files/5657169/Job.Description_PHP_.Middle.docx)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
