### ISSUE TITLE
[LINAGORA] Full-stack Javascript Developer - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2223]
## Location

* 5 Dien Bien Phu, Ba Dinh, Ha Noi
* Open for full-time remote

## Salary Expectation

* Up to $1800 (Gross)

## Requirements

* Background in Computer Science/ Information Technology or equivalent.
* 1+ year’s experience in NodeJS, Typescript, back-end frameworks (Expressjs, Fastify, etc.), front-end frameworks (Vuejs, Angularjs, etc), state management tools (Vuex, Redux, etc.).
* Knowledge of SQL & NoSQL databases, REST API, Git.
* Highly proficient object-oriented programming paradigm
* Familiarity with automated testing, specifically testing frameworks such as Jest or Mocha
* Highly proficient with Vue.js framework and its core principles such as components, reactivity, and the virtual DOM
* Proficiency with modern development tools, like Babel, Webpack, and Git
* Experience with both consuming and designing RESTful APIs
* Good level in English skills: written and spoken

### You’ll be responsible for

* Write high-quality, clean, maintainable, reusable code using engineering best
practices (unit testing, source control, continuous integration, automation, design
patterns, etc.).
* Analyze requirements, design, and develop features.
* Understand the product, constantly optimize the product, identify and fix problems, improve stability and user experience
* Collaborate with fellow developers, product managers, user experience designers, and operation engineers to build products with web technologies.
* Optimize application for maximum performance and scalability.
* Participate in regular internal technology sharing and other regional tech events.

### Why it would be awesome to work with us

* Work in a multinational team with highly skilled people for international projects.
* Correct work-life balance.
* Annual company trip, exciting team-building activities.
* Working time: 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

📌 Homepage: linagora.vn
☎ Phone: 086.550.4412
🧐 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
