### ISSUE TITLE
[LINAGORA] Mobile Developer (Android, iOS, Flutter)

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2224]
## Location

* 5 Dien Bien Phu, Ha Noi
* Open for full-time remote

## Salary Expectation

* Up to $1800 (Gross)

## Requirements

* Bachelor’s degree in information technology, or related field
* Proficient with Flutter/ iOS/ Android 
* Familiarity with RESTful APIs to connect applications to back-end services
* Knowledge of other web technologies and UI/UX standards
* Understanding of iOS/Android’s design principles and interface guidelines
* Proficient understanding of code versioning tools
* Familiarity with cloud message APIs and push notifications
* Has knowledge about other cross-platform development: Flutter, ReactNative is a PLUS
* Back-end web services knowledge
* Unit tests, automation, and code reviews
* Willingness to learn new technology
* Strong OO design and programming skills
* Complex solving problem

### You’ll be responsible for
**Job Overview**:
You’ll develop from scratch the mobile application of the OpenPaaS (https://open-paas.org/) platform.
* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices
* a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles

**Job Responsibilities:**
* Participate in product design, offer new ideas
* Collaborate with product and business teams to define our product that is suitable for the market
* Design and implement a mobile application for iOS using Swift or Android using Java or Kotlin.
* Work in the team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our team maintain high standards
* Support international teams in developing products to meet the requirements.
* Keep up to date on the latest industry trends in the mobile technologies
* Coach the member in the team and attend to interview process to scan technical part

### Why it would be awesome to work with us

* Work in a multinational team with highly skilled people for international projects.
* Correct work-life balance.
* Annual company trip, exciting team-building activities.
* Working time: 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

🤩 Homepage: linagora.vn
☎️ Phone: 086.550.4412
🎯 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
