### ISSUE TITLE
[LINAGORA] System Admin Engineer - FT

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2226]
## Location

* 5 Dien Bien Phu, Ha Noi
* Open for full-time remote

## Salary Expectation

* Up to $2000 (Gross)

## Requirements

- A system admin background, willing to work in a modern, automated environment.
- Willing to work in Open Source.
- Good level of English.
- Any of the following technologies is a plus:

> - Git version system usage
> - Docker knowledge
> - Running JVM applications
> - Knowledge about the Kubernetes eco-system
> - Knowledge with the Ansible automation tool
> - Performance testing - with Gatling
> - Database administration experience with the following databases: Apache Cassandra, ElasticSearch, RabbitMQ, Object Storage S3 API
> - Runtime monitoring (Zabbix, Prometheus, FluentBit)

### You’ll be responsible for

- Join a dynamic team working on a cutting edge distributed email server.
- Set up the required execution environment for the Apache James +server, both for SaaS or on-premise execution.
- Get involved in an Apache community.
- Helped by Linagora's DevOps tribe, you will design and set-up the running environment for the Apache James server.
- Take an active role to spread DevOps culture within the Linagora company.

### Why it would be awesome to work with us

- Work in a multinational team with highly skilled people for international projects.
- Correct work-life balance.
- Annual company trip, exciting team-building activities.
- Working time: 5 days/week, from Monday to Friday.
- Lunch allowance, 13th-month salary, competitive salary.
- Annual health checkups and other benefits based on labor law.
- Participate in Open Source communities and conferences in Vietnam.
- Modern working space, free coffee.

### Contact

🤩  Homepage: linagora.vn
☎️ Phone: 086.550.4412
🎯 Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
