### ISSUE TITLE
NFQ Asia - Senior PHP Developer

### ISSUE THREAD

**Issue by Havtn** [awesome-jobs/vietnam#2227]
NFQ Asia is looking for a talented developer to join our dynamic team

## The job
* You will be joining an awesome startup team to build cool applications that serve millions of users, from idea to production.
* As our customers are typically ambitious foreign startups, you will have a chance to improve your English, learn about startup culture and product mindset along the way. If you want to make a great impact on the world, this is your chance now.
* Managing full lifecycle customer projects with Agile methods.
* Developing strong relationships with customers, acting as the primary point of contact as well as managing stakeholder expectations and always seeking for solution improvement.
* Design, develop, test internal REST API
* Design and implement scalable and robust applications
* Analyze functional requirements and creation of software design
* Participate in code and design reviews to maintain our high development standards
* Work closely with infrastructure team in building and scaling back-end services as well as performing root-cause analysis investigations
* Write API documentation for better communication with front-end developer

## Your Skills and Experience
* 3+ years of  PHP development experience, with an emphasis on web applications..
* Proficient understanding of code versioning tools (Git is preferred)
* Sufficient in using English (both verbal and written) 
* Strong knowledge of web frameworks
* Experience in unit testing frameworks
* Experience in CI/CD methodologies

### Must Have
* Work experience in Symfony 
* Proficiency in database design &amp; SQL skills
* Experience in REST API development
* Knowledge on Realtime Communication (Pusher, PubNub, FireBase)
* Strong understanding of system performance and scaling

### Our core value:

* Honest we only tell the truth (upfront)
* Transparent we share information adequately, and openly
* Open-minded we approach things with candid attitude
* Respect we treat everyone with the same kindness
* Empathy sharing feelings matters

### Benefits include:

* Laptop is provided.
* A fun & dynamic environment and freedom to be creative.
* Rock in open-mind, kind & humble band.
* Modern office with the flexible relaxing zone.
* Company trip, team building & other community Tech activities.
* Year-end bonus.
* Performance review 2 times/ year.
* Extra Medical Insurance.
* 15 days annual leaves, working Monday – Friday.

### Contact
Homepage: www.nfq.asia
Send us your CV via email: career@nfq.asia or Skype: ngocha.123

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
