### ISSUE TITLE
Grabhotel - Software Engineer Junior (Frontend/Backend) - HCMC Vietnam

### ISSUE THREAD

**Issue by sansanng** [awesome-jobs/vietnam#2229]
## Location
* Hado Centrosa, 12 Ward, District 3, HCMC, Vietnam
* Full-time

## Salary Expectation
* 500-800$/month (or Negotiate)

## Requirements
At least 6 months to 1 year of working experience with web development
Experience with back-end side: React, MongoDB, Firebase
Experience in developing scalable and robust software applications in web environments
Have working knowledge and experience with Unix/ Linux environment
Have good knowledge and experience with databases such as MySQL, PostgreSQL

### Must Have
Backend skills: A solid problem-solving skill with well-practiced and consistent approach. You will have a chance to tackle any problems by breaking it down and solving it logically and systematically. 
Practical experience on a web-based application is a plus
Experience with the database management tool SQL is a plus.

### Responsibilities
Design and develop stable, secure and highly available web applications.
Analyze requirements, identify potential problems and develop appropriate solutions.
Drive design and development of our platform services and tools, support the continuous development of existing products.
Participate in all software development activities following the Scrum process.
Maintain high quality codebase.
Inspire and provide guidance to junior developers.

### Why it would be awesome to work with us
Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development.
Amazing team: smart, open-mind, and passionate engineers.

### Interesting engineering projects
Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development.
Amazing team: smart, open-mind, and passionate engineers.

### Contact
Send your CV to email: hr@cititech.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
