### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by dungitbk** [awesome-jobs/vietnam#223]
removed

**Comment by joneslee85** [comment]
@dungitbk thanks for posting with us. Please revise the format of your post to comply with our guideline as stated in https://github.com/awesome-jobs/vietnam/blob/master/README.md.

**Comment by dungitbk** [comment]
@joneslee85 thank you, I've updated, please advise if something wrong.

**Comment by joneslee85** [comment]
@dungitbk please revise the *title*

Besides, what do you mean by _updated_ as in `Send you updated resume to: dungle.itbk@gmail.com`?

Lastly, are you the direct HR contact point?

**Comment by dungitbk** [comment]
@joneslee85 title updated
you can see the answer for your question here: http://workplace.stackexchange.com/questions/38950/what-do-recruiters-mean-when-asking-for-an-updated-resume
will have domain email when we finalize it, thanks for your concerns.
