### ISSUE TITLE
FETCH TECHOLOGY - ReactJS Developer (Junior, Senior) - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2230]
![image](https://user-images.githubusercontent.com/60914247/102183466-7915cb80-3ee0-11eb-95b4-df873daac048.png)

## Requirements
* At least 1-year experience working as frontend developer (junior), 3-4 years of experience (for senior).
* Proficient in React stack (ReactJS, Redux, State Management, Functional Programming).
* Expert knowledge with HTML5, CSS3, SASS/SCSS.
* Solid knowledge of modern web development technologies & frameworks based on JavaScript, HTML, CSS.
* Expert with developing responsive layouts leveraging CSS and media queries.
* Design and implement robust client-side solutions with RESTful API.
* Strong competency in responsive, mobile-first layouts leveraging CSS and media queries.
* Intermediate level of comprehension of the English language

## Responsibilities
* Build new software front end for advanced user experience.
* Build reusable components/modules for static websites with responsive design.
* Work with API endpoints for dynamic content updating.
* Ensure UI/UX of developed pages and software with near pixel-perfect design.
* Develop and optimize front end UI to ensure the application is rendered consistently in cross-browser environments.
* Cooperate to connect front end software development with expert backend team.

## Why it would be awesome to work with us?
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on the job training, you will always have the chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Weekly Sports Day (Football, Badminton...), Monthly Team-building, Company trip, Play Game (PlayStation, Board Games).

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
