### ISSUE TITLE
FETCH TECHNOLOGY - Product Manager/ Product Owner - HCM/HN -  FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2231]
![image](https://user-images.githubusercontent.com/60914247/102183901-31437400-3ee1-11eb-9855-c08178f9933e.png)

## Requirements
* At least 2+ years of experience in Product Owner/Product Manager position.
* Demonstrated ability to evolve product strategy based on research, data and industry trends.
* A passion & expertise for web/mobile platforms and technologies.
* A diverse portfolio of projects that demonstrate your skills in product management.
* Great communication skills and an ability to explain your design decisions clearly, including the problem you are solving, alternative options you considered, and preferred solutions.
* An interest in high-level product strategy and vision and a recognition of how your work can impact it.
* BA/BS degree in Computer Science or related technical field, or equivalent practical experience.
* Experience building and shipping products from the ground up is a plus.
* Engagement and retention is a huge plus.

### Responsibilities
* Define product vision, strategy, and roadmap with an in-depth understanding of markets, competition, and user needs.
* Identify and target key user segments for existing and new products.
* Validate ideas and design decisions with qualitative and quantitative feedback by conducting and analyzing user research.
* Drive product development from small features to entirely new products and ensure successful product delivery.
* Be the owner of the entire product life cycle and work hands-on with various teams such as user experience, user research, marketing, engineering, legal and business development to research, plan, build, ship and manage products.
* Define and analyze metrics that inform the success and direction of products.

### Why it would be awesome to work with us
Being a Product Manager/ Product Owner at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* MacBook/laptop for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).

### Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
