### ISSUE TITLE
FETCH TECHNOLOGY - Test Engineer - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2233]
![image](https://user-images.githubusercontent.com/60914247/102184400-fbeb5600-3ee1-11eb-9535-6106f61f85de.png)

## Requirements
* At least 2 years of experience in developing automated test systems.
* At least 1 year in software development.
* Familiar with various testing tools, scripting languages, SQL, Bash, basic system administration.
* Degree in Computer Science or equivalent practical Experience.
* Experience in Ruby on Rails and RSpec is a bonus.
* Experience with Blockchain technologies at the transactional level.
* Organized and methodical, able to map the impact of software changes and plan tests to ensure correctness and prevent regression.
* Excellent communication skills.

## Responsibilities
* Ensure quality and excellence of the product on various interfaces, including Web, Mobile and APIs.
* Work with the product team to establish quality parameters.
* Formulate plans to verify that products and features are working as expected.
* Read engineering design proposal for new features and provide suggestions about how and where to build in testability.
* Orchestrate the rapid testing and releasing of products/features.
* Write and maintain automated tests to verify the correctness of the feature/product.
* Investigate stack traces from monitoring and logging systems, and search the code base to find the correct owner for escalation.
* Collaborate on determining the root cause of a production defect, then pinpoint tests that need to be added to prevent similar defects in the future.

## Why it would be awesome to work with us

Being a Test Engineer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
