### ISSUE TITLE
NFQ Asia - Technical Architect - HCMC - FT

### ISSUE THREAD

**Issue by Havtn** [awesome-jobs/vietnam#2234]
## Location

Level 11, Vincom Center, 72 Le Thanh Ton, D.1

## Salary Expectation

* up to $4000/month

## The job
* As a Technical Architect you’ll work as part of a team to deliver innovative, cost-effective and efficient IT solutions to an organization.
* You will be responsible for driving technology strategy, building out the technology team of one of our main competencies (PHP, NodeJS, Javascript, Cloud Computing) and delivering on the shared growth vision. Deep understanding of Tech and Hands-On Attitude are a must (yes, sometimes you will need to jump in and show the boys how to code…)
* You’ll be working with cutting edge frameworks, automation, and use the latest technologies for error tracking, reporting, and testing, with a high level of test coverage to maintain high-quality products that our clients use to run their entire business. We take pride in clean code built for our highly scalable systems. We work in small teams for clients from all around the world, follow agile work methods, and use continuous integration and delivery methodologies to move fast without sacrificing quality.
* Your task is to help firefight problems in the various teams as well as educate the teams to avoid them at all.
* Developing strong relationships with customers, acting as the primary point of contact as well as managing stakeholder expectations and always seeking for solution improvement. 
* Work closely with the DevOps team in building and scaling back-end services as well as performing root-cause analysis investigations.
* Report directly to the Head of Engineering.

## Your Skills and Experience

* 5+ years of overall software development experience, with an emphasis on web applications, both Frontend (ReactJS / VueJS), Backend (PHP / Python / RoR) and DevOps.
* Deep knowledge of web frameworks and Cloud technologies.
* Experience in Automation Test frameworks
* Experience in CI/CD methodologies
* 2 years of experience working as a Technical Architect.
* Good at verbal and written in English

### Big bonus:

* Experience in booking business domain (hotel booking, car rental)
* Work experience in Symfony, Elasticsearch, React (strongly preferred)
* Proficiency in database design & SQL skills
* Knowledge on Real Time Communication (Pusher, PubNub, FireBase)
* Strong understanding of system performance and scalingt

### Why You’ll Love Working Here

Our core value:

* Honest we only tell the truth (upfront)
* Transparent we share information adequately, and openly
* Open-minded we approach things with candid attitude
* Respect we treat everyone with the same kindness
* Empathy sharing feelings matters

### Benefits include:

* MacBook Pro is provided.
* A fun & dynamic environment and freedom to be creative.
* Rock in open-mind, kind & humble band.
* Modern office with the flexible relaxing zone.
* Company trip, team building & other community Tech activities.
* Year-end bonus
* Performance review 2 times/ year.
* Extra Medical Insurance.
* 15 days annual leaves, working Monday – Friday.

### Want to apply for this vacancy?

Simply send us an email with your enclosed updated CV to: career@nfq.asia or reach me on Skype: 

- [ ] ngocha.123

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
