### ISSUE TITLE
Danh Khôi - Senior Business Analysis - HCM - FT

### ISSUE THREAD

**Issue by nghiangodinh** [awesome-jobs/vietnam#2236]
## Location

* 89 Phan Dinh Phung st., Phu Nhuan Dist., HCMC, Vietnam
* FullType

## Salary Expectation

* Competitive

## Top 3 Reasons To Join Us
* Bonus by projects
* Competitive salary that matches your talent
* Join a dynamic and growing fast team

### Primary Role
Business Analyst is responsible for understanding our products need, capturing the domain expertise that our other internal departments have, and translating this accurately into a succinct requirement document that will serve as the input to the software designers.

### Working relationships
•	Report directly to the CIO/CTO.
•	Work with project team members and other departments.
•	Communicate with client counterparts if any.

### Professional Responsibilities
•	Assess client’s business needs and business processes (current and future);
•	Interview and domain experts of our departments to capture all relevant domain knowledge;
•	Document product’s vision and project’s scope;
•	Document client’s business requirements in detail, (using use cases or functional specifications/User Stories) with all 
assumptions and caveats included;
•	Define quality attributes, external interfaces, constraints and other nonfunctional requirements;
•	Lead requirements analysis and verification, ensuring that requirement statements are complete, consistent, concise, comprehensible, traceable, feasible, unambiguous, and verifiable, and that they conform to standards;
•	Participate in peer reviews and inspections of requirements documents.
•	Participate in peer reviews of work products derived from requirements specifications to ensure that the requirements were interpreted correctly;
•	Serve as an internal point of contact for development whenever requirements need to be clarified;
•	Support UAT in testing, verifying bugs/issues with users/clients;

### Professional Requirement
•	At least 05 years of working experience of which 03 year in analyzing requirement;
•	Knowledge of software development process, especially software requirement analysis;
•	Excellent communication skill and interpersonal skill;
•	Proven ability to document business requirements in an accurate, unambiguous and succinct fashion;
•	Exceptional presentation and client relation skills;
•	Experience with Real Estate and/or CRM is a plus;
•	Good at writing documents User Story, URD, SRS;
•	Ability to work with minimal or no direction;

### Education/Training
•	BS degree is required.
•	Advanced degree and professional certification are preferred.

## Why You'll Love Working Here
•	Competitive salary that matches your talent
•	13th month of salary
•	International premium healthcare
•	Awesome team who are all experience and free in spirit
•	Free bike parking and lunch

### Want to apply for this vacancy?
Simply send us an email with your enclosed updated CV to: tuyendung@danhkhoi.com.vn or reach me on Skype: nghiangodinh

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
