### ISSUE TITLE
Fullstack web developer

### ISSUE THREAD

**Issue by JunioVN** [awesome-jobs/vietnam#2237]
## Location

* Etown Central, 11 Doan Van Bo Street, Ward 12, District 4, Hochiminh city, Vietnam

## Salary Expectation
* $1500/month UP

## Requirements
* 3+ years development experience.
* JavaScript frameworks like React, Redux, React Router.
* Front-end development workflow: Yarn, Gulp, WebPack.
* Experience with PHP 7, Symfony Frameworks, ORM such as Doctrine or a general understanding of MVC frameworks. Microservice Architecture is plus.
* Hands-on experience in NodeJS and ES6.
* Experience with JMS Messaging (ActiveMQ or RabbitMQ or Kafka).
* Local Vietnamese

## Responsibilities

We are looking for an Agile Full-Stack Web Developer responsible for the development and maintenance of our digital services aimed at helping people and company achieve their dreams. Your primary focus will be development of the front-end uses a combination of HTML, CSS, and JavaScript to build everything a user sees and interacts with on a website and the back-end develop the application, server, and database that make up the foundational structure of a website. You will be working alongside other engineers and developers working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and the creation of quality products is essential.

As a Full Stack Web Developer, you are responsible to handle these following things, but not limited to:
* Join and discuss with team to find suitable solution
* Handle backend functional about develop webservice API, maintain and upgrade current site, refactor legacy code.
* Define and integrate with front-end side.
* Mentor new members.
* Training and improve both of technical and soft skill to resolve problems.
* Design if it's quick or if there is no design.
* Be user-centered, since the front-end side is the interface that interacts with users.
* Identify the various boxes/components in order to re-create the design in HTML and CSS, responsively for both Mobile and Desktop. This could include webpages or email templates.
* Turn the static pages into a micro app: make the app interactive with animations, enhance how users see and interact with the site on any browser, get users' inputs and send to server, then correctly responses to users' actions, collaborate on APIs that communicate between front-end and back-end, a little UX knowledge would be helpful on this (because many times, a static design could not reflect all the interactions between the app and users)
* Modify and maintain legacy front-end functionalities.
* Test the site during development for usability and fixing any bugs
* Research on front-end trending, best practices, good technologies to suggest and apply to the site, in order to enhance user experience.
* Collaborate with a agile team to define, design, and ship new features.

## Why it would be awesome to work with us
* Attractive salary package
* Friendly working environment
* Work - life balance
* Quarterly recognition awards; Service awards; Valuable benefits for all employees
* Up to 22 days full paid leave of a year.

## Contact
* Homepage: https://www.vietnamworks.com/full-stack-web-developer-32-1324272-jd/?source=searchResults&searchType=1&placement=4&sortBy=date

Mr. Tri Le
* Email: tri.le@navigosgroup.com
* Cellphone: 0909103610

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
