### ISSUE TITLE
Oivan - Full Stack Ruby on Rails/NodeJS/Angular Developer - Vietnam - FT

### ISSUE THREAD

**Issue by tuukka-kaltiainen** [awesome-jobs/vietnam#2238]
## Location

* Saigon/Danang/Hanoi, Vietnam
* Remote/onsite both ok

## Salary Expectation

* $1.500-3.000

## Requirements

Oivan is seeking full stack developers with 3+ years of experience in Ruby on Rails and other relevant technologies to join our growing Ho Chi Minh City team.

Oivan has flexible hours and remote work options with open culture and European/Nordic management style. We have great remote work processes and tools in use to support our growing team.

We have the drive and enthusiasm of a startup and the stability of a well-established company. We work in an agile/scrum environment delivering rock solid digital solutions to our customers.

If you look to step-up your career as a senior developer, a Oivan self-organizing team could be your next home!

### Must Have

* +3 years experience with Ruby on Rails
* Front end experience such as HTML, JavaScript, Angular, CSS, SASS, jQuery
* Experience with RESTful API
* Experience with database systems (postgreSQL)
* Experience with Git
* Excellent verbal and written English skills

### Ideally

* Experience with NodeJS, postgreSQL and others a plus

### You’ll be responsible for

* Building microservices for our biggest project involving a growing government real estate booking system.

### You can bring

* Chill attitude
* Technical competence

### Why it would be awesome to work with us

* Flexible hours and remote work - our team can work outside office up to 3 days a week
* Macbook Pro, Phone and Headphones
* Premium insurance from PVI
* Free weekly team lunch outside
* Travel opportunity to Oivan international locations and client sites
* International team and work environment opportunities (Europe, US, Asia and Middle-East)
* Coffee, Drinks and Snacks as much as you want.
* Regular team social events
* Self-study time and company-sponsored opportunities for development
* 12 Days Annual Leave
* Annual Health Checkup
* 13th Month Salary

### Contact

Send your CV to :

Tuukka Kaltiainen
tuukka.kaltiainen@oivan.com 
+84919055235

www.oivan.com
https://itviec.com/companies/oivan

**Comment by tin612** [comment]
pump +1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
