### ISSUE TITLE
Mid- to Senior BI Engineers

### ISSUE THREAD

**Issue by gergana-pl** [awesome-jobs/vietnam#2239]
## Location

* Ho Chi Minh, Vietnam
* Da Nang, Vietnam

### Skills
* Fluent SQL skills
* Looker (or other BI tools: Tableau Software / Qlik / Power BI)
* ELT process
* Data modelling
* Version control: Git
* First experience with OOP (Python, Java or web development)

### Must Have

* 3+ years' experience

## Responsibilities

Our BI Engineers turn vast amounts of data into insightful, easy-to-use, automated business intelligence reports. They work closely with both the internal team of engineers and our partners’ projects teams to deliver reports that empower business owners to make better and more informed decisions.

## Why it would be awesome to work with us

* Extensive training to turn you into a superstar
* Latest tech to work with: Google Cloud Functions, AWS API Gateway/Lambdas, Snowflake, Terraform, Cucumber, SpringBoot
* Remote work opportunities
* Unlimited holiday, yes, you got that right
* Company MacBook + other hardware
* A chance to work on diverse projects in fintech, healthtech, biotech, edtech, energy and more

## How to apply

Send your **CV in PDF** format to careers@infinitelambda.com. Other formats will not be considered.
Homepage: [https://infinitelambda.com/](https://infinitelambda.com/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
