### ISSUE TITLE
LOOP Smart POS - Integration Engineer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#2241]
## Location

* Saigon, Vietnam
* District 4

## Salary Expectation

* Negotiation
## Responsibilities
* Evaluates existing components or systems to determine integration requirements and to ensure final solutions meet organizational needs.
* Plan, design and implement the integration process. This can also include creating documentation for the process so that future engineers know how the entire system/feature work.

## Requirements
* 1-3 years of experience in software development using Microsoft Technologies.
* Knowledge of C# as well as .NET framework.
* Expertise in most of the following: ASP.NET MVC, Web API, gRPC.
* Knowledge of MySQL, Postgresql, Mongo, Elasticsearch, Redis, Rabbitmq or Kafka.
* Experience in AWS service, Google cloud service is a plus.
* Strong technical, analytical and problem solving skills.
* Technically confidence, flexibility and a strong team spirit.

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + Year-end bonus
* To be free to create, to express oneself, not to be restrictive, not to be patterned.
* Events & activities: Company trip , monthly company parties & other teambuilding activities.

### Contact
Send your CV to email: hr@loop.vn
Skype: nguyenthitrunglopa1

Know more about us
Facebook: https://www.facebook.com/loopvn
Homepage: https://loop.vn/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
