### ISSUE TITLE
LOOP Smart POS - Junior Backend Developer - HN - FT

### ISSUE THREAD

**Issue by trungnguyenhr** [awesome-jobs/vietnam#2242]
## Location

* Ha Noi, Vietnam
* Thanh Xuan District

## Salary Expectation

* Negotiation

## Requirements
* Bachelor's degree in Computer Science
* 1-3 years of experience in software development using Microsoft Technologies
* Knowledge of C# as well as .NET framework
* Expertise in most of the following: ASP.NET MVC, Web API, gRPC
* Knowledge of MySQL, Postgresql, Mongo, Elasticsearch, Redis, Rabbitmq or Kafka
* Experience in AWS service, Google cloud service is a plus
* Very strong technical, analytical and problem solving skills
* Technically confidence, flexibility and a strong team spirit

### You’ll be responsible for
* Develop mission-critical distributed applications for a broad range of clients and industries, using state-of-the-art tools and agile methodologies.
* Work closely with business analysts and software architects to design reliable, secure and highly efficient systems; participate directly in technical decisions.
* Be actively involved in the complete project lifecycle, from requirements analysis to final delivery.
* Contribute to knowledge sharing and continuous improvement activities.

### Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + Year-end bonus
* To be free to create, to express oneself, not to be restrictive, not to be patterned.
* Events & activities: Company trip , monthly company parties & other teambuilding activities.

### Contact
Send your CV to email: hr@loop.vn
Skype: nguyenthitrunglopa1

### Know more about us
Facebook: https://www.facebook.com/loopvn
Homepage: https://loop.vn/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
