### ISSUE TITLE
Money Forward Vietnam - Software Engineer (Golang) - HCMC

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2243]
**LOCATION**
21Fl, ETown Central Building, 11 Doan Van Bo, District 4, Ho Chi Minh

**WORKING TIME**
- Monday - Friday
- Full-time
- No OT

**SALARY RANGE**
Very acttractive

**RESPONSIBILITIES**
- Develop and design service
- Design database schema
- Write clean and maintainable code
- Discuss and debate with other team members to find optimal solutions

**REQUIREMENTS**
_Must-Have_
- 2+ years of Golang experience
- Experience in reviewing code
- Experience in writing good unit tests

_Nice-To-Have_
- Experience with frontend development (ReactJS, VueJS, jQuery)

**LANGUAGE SKILL**
- Can basically communicate (writing, speaking) in English.
- Japanese is a huge plus

**WHY IT WOULD BE AWESOME TO WORK WITH US?**
- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

**CONTACT**
Skype ID: nguyentoloan2009
Email: nguyen.thi.to.loan@moneyforward.vn

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by nguyentoloan** [comment]
To whom it mays concern,
I’m recruiter from Money Forward Vietnam and I’m posting this job on behalf of HR Team Money Forward Vietnam, not a headhunter or a headhunting agencies. 
I have to use personal email address because our current recruiment email is set for mail receiving purpose only. 
Could you please open the job post again? 
In case you require further information or clarification, please let me know. 
Regards,
Loan Nguyen
Money Forward Vietnam

Được gửi từ iPhone của tôi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
