### ISSUE TITLE
[Motorist] - [Web Developer] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by tuongvi0209** [awesome-jobs/vietnam#2248]
## Location

District 2, HCMC

## Salary Expectation

Up to $2000 depending on experience

## Requirements
* Bachelor’s degree in Computer Science or related field
* Proficiency in database design and SQL skills
* Solid understanding of adaptive and responsive design principles
* Proficient understanding of code version control tools, such as Git
* Knowledge of website optimization techniques, fast page and SEO friendly
* Experience in writing automated tests for web applications

## Skills: 
* Could communicate in English
* Good team work skill

### Must Have
* At least 1 year experience as a Ruby on Rails Developer
* At least 3 year experience in front-end development
* Have good knowledge or experience in front-end technologies, such as HTML5, CSS3, Javascript and Bootstrap

### Ideally
* Knowledge of development based on RESTful API or Microservices
* Experience working with AWS, Redis, Capistrano and Rspec & Capybara
* Experience with front-end libraries and frameworks such as ReactJS, AngularJS, VueJS

### Contact
Email: tuongvinguyendiep@motorist.sg

**Comment by thuyettiensinh** [comment]
Motorist Pte Ltd
Is this your company?
Is it a Singapore IT product company?
Please answer yes/no and I will read more about your company for myself, thanks 🙇 !

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
