### ISSUE TITLE
Code Engine Studio - Senior Java Developer - Danang - FT

### ISSUE THREAD

**Issue by shchoi78** [awesome-jobs/vietnam#2249]
![Image](https://scontent.fdad1-1.fna.fbcdn.net/v/t1.0-9/133298721_3710540919040701_8761888266089047645_o.jpg?_nc_cat=102&ccb=2&_nc_sid=e3f864&_nc_ohc=cBOSATxddfgAX8I115m&_nc_ht=scontent.fdad1-1.fna&oh=980506a5fcf636a45280cea0883cead6&oe=60231A6F)

## Location

* Da Nang, Vietnam

## Salary Expectation 

* $1000 - $2000/month

## Requirements 

* Minimum of 6 years of experience in software development
* Work experinece as a Senior Java Developer or similar role
* Experience desigining, building and testing Java EE applications
* Experience with the following technologies is highly desirable: Liferay, Java-based portal and CMS. 
* In-depth knowledge of popular Java frameworks like JSF and Spring MVC
* In-depth knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB)
* Experienced with following is a plus: OSGi, Jenkins, AWS, Advance caching and indexing, LDAP/SSO/OAuth.
* Write high-quality, clean, maintainable code using engineering best practices (unit testing, source control, continuous integration, automation, design patterns, etc.)

### Responsibilities 

* Identify and analyze user requirements
* Prioritize, assign and execute tasks throughout the software development life cycle
* Write well-designed, efficient code
* Review, test and debug team members’ code
* Participates in installation, on-going maintenance and production support of software systems.
* Maintain a high standard of quality through knowledge and coding of unit and integration testing.

### Why it would be awesome to work with us 

* Full 13 month salary and up to an additional month performance bonus
* 12 days of vacation, 5 days of sick leave, and Christmas holiday off
* 5 day work week (Mon - Fri) with no overtime hours
* Additional health and training allowance renewed yearly
* 2 to 4 hours per week of english class and soft skill training during work hours
* Free lunch everyday and monthly team social events
* Fully English speaking environments working with clients from USA, Canada, Europe, and SE Asia.
* Relocation budget available
    
### About Code  Engine Studios

Code Engine Studio is a digital outsourcing and technology partner and Google Cloud Certified Partner who helps our clients in USA, Canada, Europe, and SE Asia. We succeed by turning our clients ideas and strategies into high-end digital products. We are an international team of passionate people who believe that doing our best work comes from within. When you join our family we care about who you are and not just what you do. Our vision is to help our employees reach their greatest potential by helping them develop both their skills and character.

### Contact 
HR: hr@codeenginestudio.com or apply at [CES job](https://codeenginestudio.freshteam.com/jobs/9c29wBFDZVpa/java-developer-intermediate-to-senior?ft_source=ZipRecruiter_3000076465&ft_medium=Job%20Boards_3000070653)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
