### ISSUE TITLE
Innaway - PHP Developer - Hanoi - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#225]
## Location
- Villa 15, Lane 76 To Ngoc Van, Tay Ho. Hanoi, Vietnam
## Salary Expectation
- Negotiable
## Requirements
1. Have a look at our prototype here (www.innaway.co) to understand our concept and business.
2. Proven knowledge with experience in the following areas:
   - PHP / PHP5
   - MySQL 
   - HTML / HTML5 
   - CSS / CSS3 
   - JavaScript 
   - JQuery 
   - Angular.JS
   - Third-party APIs (Google, Facebook, etc)
   - Data-Oriented Searching.
   - SOAP and/or RESTful API web services
   - Proven knowledge in distributed systems development
   - Passion for best design and coding practices and a desire to develop new bold ideas
3. Good oral and written communication skills and interpersonal skills required. 
4. Ability to handle multiple concurrent tasks with constant interruptions
5. BS/MSc Degree in Computer Science, Computing, Software engineering or equivalent
### Responsibilities
- Define architecture solutions
- Design high-level solutions
- Build up core components
- Developing APIs
- Research and apply cutting-edge technologies
- Suggest integration process for new technologies
- Attend meetings on regular basis
- Working closely with business analyst and UI designer to establish and achieve critical goals and other KPIs
- Helping with data integration, cleaning data, porting, lists consolidation, etc.
- Contributing to technical-related questions
### Contact

To apply for this opportunity, please email us at info@innaway.co

**Comment by joneslee85** [comment]
Thanks for posting. Can you please revise the post format to comply with our guideline?

**Comment by Dawensky** [comment]
I used the same format. I just remove sections that I don't need.

**Comment by huydx** [comment]
@Dawensky we mean title ;)

**Comment by huydx** [comment]
Quote:


What is the format of the job post?

Every job post MUST strictly follow below format:

[Company Name] - [Job Title] - [Location] - [Job Type]
in which [Job Type] could be:

FT (for Full Time)
PT (for Part Time)
C (for Contract)
for eg:

Facebook - Chief Software Architect - Remote/Saigon - FT
Please be noted, title cannot be all in uppercase like this:

FACEBOOK - CHIEF SOFTWARE ARCHITECT - REMOTE/SAIGON - FT

**Comment by joneslee85** [comment]
@Dawensky please look at other posts' title and update this post title
