### ISSUE TITLE
Senior Mobile Developer (Flutter/iOS/Android)

### ISSUE THREAD

**Issue by uyennguyenhr** [awesome-jobs/vietnam#2250]
## Location

* Saigon, Vietnam
* District 1

## Requirements
* At least 3 years of experience in Mobile Development (Android / iOS)
* At least 1 year of experience in developing Flutter applications
* In-depth knowledge in Flutter, Dart, Flutter layout, BloC, and the mobile app development lifecycle
* Strong knowledge of OOP, REST APIs and design patterns
* Familiarity with modern architectures (MVP, MVVM etc.)
* Experience in publishing mobile apps in Google Play or App Store or Firebase App Distribution
* Good English skills (reading & speaking)
* Analytical skills, and Problem-solving skills
* Self-starter who can take ownership of projects

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + KPI bonus at the end of the year
* 15 days of annual leave per year
* Onsite opportunity in Korea
* Company trip at least once a year, monthly company parties & other Teambuilding activities
* Free coffee, snack and drinks

JD for detail: https://smrtr.io/4R3Hm

## Contact
Phone: 028-6295-8827
Send your CV to email: career@lecle.co.kr

## Know more about us
Facebook: https://www.facebook.com/LecleVietnam/
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
