### ISSUE TITLE
Mobile Developer (Flutter/iOS/Android)

### ISSUE THREAD

**Issue by uyennguyenhr** [awesome-jobs/vietnam#2251]
## Location

* Saigon, Vietnam
* District 1

## Requirements
* Bachelor degree in Computer Science or relevant fields
* 0 - 3 years of experience in mobile development - iOS/Android; Experience with Flutter is a strong plus
* Familiarity with OOP design principles
* In-depth knowledge of at least one of these programming languages Dart/Java/Kotlin/Swift/Objective-C
* Experience in third-party libraries and APIs
* English skills (Reading & Speaking)
* Ability to work individually as well as in team
* Good analytical and problem-solving skills

## Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + KPI bonus at the end of the year
* 15 days of annual leave per year
* Onsite opportunity in Korea
* Company trip at least once a year, monthly company parties & other Teambuilding activities
* Free coffee, snack and drinks

JD for detail: https://smrtr.io/4R4Rt

## Contact
Phone: 028-6295-8827
Send your CV to email: career@lecle.co.kr

## Know more about us
Facebook: https://www.facebook.com/LecleVietnam/
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
