### ISSUE TITLE
Money Forward Vietnam - Software Engineer (Java)

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2252]
**LOCATION**
21Fl, ETown Central Building, 11 Doan Van Bo, District 4, Ho Chi Minh

**WORKING TIME**
- Monday - Friday
- Full-time
- No OT

**SALARY RANGE**
- Very attractive

**RESPONSIBILITIES**
- Develop and design service
- Design database schema
- Write clean and maintainable code
- Discuss and debate with other team members to find optimal solutions

**REQUIREMENTS**
_Must-Have_
1. Technical skill
- 3+ years of experience as Java software engineer
- Strong knowledge in Core Java, server-side Java, and Spring framework
- Design, build, and maintain efficient, reusable, scalable, testable and reliable Java code
- Implementing automated testing platforms and unit tests
- Proficient understanding of code versioning tools, such as Git
- Familiarity with build tools such as Ant, Maven, and Gradle

2. Soft skill
- Good verbal and written communication in English is required
- Sense of Teamwork, Responsibility, Communication skills
- Collaborate on requirement analysis and specifications

_Nice-To-Have_
1. Technical skill
- Strong knowledge on security and performance
- Familiar with various design and architectural patterns
- Experience with popular web application frameworks, such as Play and Spark
- Basic understanding of the class loading mechanism in Java
- Familiarity with continuous integration

2. Soft skill
- Willingness to learn and build a deep understanding
- Share knowledge and experience with your colleagues

**LANGUAGE SKILL**
- Can basically communicate (writing, speaking) in English.
- Japanese is a huge plus

**WHY IT WOULD BE AWESOME TO WORK WITH US?**
- Top 1 Fintech Company from Japan
- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Flexible working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

**FLEXIBLE POINTS**
- You can join the interview now and can set your entrance schedule after Tet holiday.

**CONTACT**
- Skype ID: nguyentoloan2009
- Email: nguyen.thi.to.loan@moneyforward.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
