### ISSUE TITLE
FETCH TECHNOLOGY - Senior UI/UX Designer - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2253]
![image](https://user-images.githubusercontent.com/60914247/104999790-0ad4a380-5a60-11eb-9f3c-c570b860d52a.png)

## Requirements
* Minimum 4 years of experience as a UX Designer, Interaction, or User Interface Designer.
* Ability for rapid prototyping, turn rigorous wireframes and mockups quickly in an iterative environment.
* Demonstrated visual design expertise; capacity for creating fun, highly pragmatic and simple designs and layouts.
* General understanding of how design impacts development; ensuring designs are not overly complicated and costly to develop.
* Proficiency in a variety of design tools including Photoshop, Sketch, Invision, and Zeplin.
* Experience working in a collaborative team environment.
* The ability to prototype using tools from Invision to code like HTML and Javascript.
* Proficiency with mobile and tablet design standards (iOS and Android).
* Excellent English speaking and writing skills.

*** Qualifications:

* Bachelor's Degree in Interaction Design or Human-Computer Interaction or related is highly desirable.
* Relevant work experience in UX Research, Product Design, UX design, Visual Design is an advantage.
* Certified Scrum Product Owner is a plus.

## Responsibilities

* Excellent presentation and facilitation ability to walkthrough team members and stakeholders on user experience journeys. Help them see, understand, and empathize with the customers who’ll use the solutions they build.
* Broad experience in user research, wire-framing, prototyping, user experience design, user testing, and visual design.
* Able to create a world-class user-centered design that takes into consideration research, business drivers, customer segments, and usability feedback.
* Collaborate remotely with product owners and business to translate business requirements into high-level customer experience requirements.
* Design the UI architecture, interface, and interaction flow of mobile and tablet applications.
* Develop conceptual diagrams, wireframes, visual mockups, and prototypes.
* Fluency in modern visual design and user experience best practices for web and mobile.
* Foster an open, honest, and transparent relationship with key stakeholders.
* Must be enthusiastic and bring high-energy to the delivery team.

## Why it would be awesome to work with us
Being a Senior UIUX Designer at Fetch Technology, you will experience a youthful, flexible, and creative work environment:

* MacBook for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on the job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
