### ISSUE TITLE
FETCH TECHNOLOGY - Senior Devops - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2254]
![image](https://user-images.githubusercontent.com/60914247/105000687-33a96880-5a61-11eb-81bc-35e63a241670.png)

## Requirements
* 4+ years experience in DevOps engineering environment. 
* Strong background in Linux / Unix, preferably with experience in NixOS. 
* Have experienced with GCP, AWS or Hetzner. 
* Experience with CI/CD processes using self-managed tools or relevant cloud technologies (e.g Jenkins, CircleCI, Drone, GoCD, etc.) 
* Hands-on experience in operating and maintaining high intensive RDBMS. 
* Have to experience with application containerization an orchestrators such as Kubernetes etc. 
* Familiar with the following tools: Jira, Jira Service Desk, PagerDuty, NewRelic, Terraform, Ansible, Vault... 
* Knowledge about Computer Security, Application Security, and Security Standards & Best Practices. 
* Hands-on experience in networking, system administration, monitoring, infrastructure maintenance on-premise or cloud environments. 

## Responsibilities

* Build & maintain successfully CI/CD in our software environment. 
* Collaborate with software engineers to understand software architecture, main components, current obstacles, and provide solutions. 
* Develop automation tools, including shell scripts to automate necessary tasks. 
* Support development team to setup and configure the development environment. 
* Design and deploy cloud platform capabilities - full-stack network, load balancing, caching, DNS, security, databases, etc. 
* Perform advanced technical troubleshooting for public, private, and hybrid cloud environments. 
* Define and monitor system metrics to ensure predefined SLA, SLO. 

## Why it would be awesome to work with us
Being a Senior DevOps Engineer at Fetch Technology, you will experience a youthful, flexible and creative work environment.  

* Onsite Singapore opportunity. 
* MacBook for working. 
* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese. 
* Extensive on the job training, you will always have a chance to work with new emerging technologies. 
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law. 
* 12-day annual leave per year. 
* 13th-month salary. 
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).  

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
