### ISSUE TITLE
rakumo - Backend Developer (PHP/Python) - TanBinh,Saigon - FT

### ISSUE THREAD

**Issue by trangrakumohr** [awesome-jobs/vietnam#2256]
## Location

* 364 Cong Hoa, Etown 2 Tan Binh Ho Chi Minh
* Full time

## Salary range

* 700 - 1,500 USD

## Requirements

- Bachelor's degree in Software Engineer or related fields.
- Have at least 1 year of experience in PHP or Python.
- Have knowledge about OOP, design pattern.
- Basic knowledge of Front-end.
- PHP candidate: have knowledge about CakePHP, Zend, Symfony Framework.
- Python candidate: good at Javascript. Have knowledge about Google App Engine is an advantage.

###Nice to have:

- Knowledge of Google Cloud Platform and Salesforce Development.
- Knowing how to use Linux, MySQL and Git.
- Good at solving problem, communication and presentation. Must be logical.

## You’ll be responsible for

- Develop web application, systems and maintain according to the needs of customers.
- Coordinate with QC team to ensure product quality.
- Report to Leader/ PM.
- Perform other tasks assigned by Leader/ PM.

## Why it would be awesome to work with us

- Onsite opportunity in Japan.
- Working directly with foreign customers.
- Holiday (30/4, 2/9),Year-end, TOEIC/Japanese/Google Cloud Platform (GCP) certificate & recommendation bonus.
- 13th-month salary before Tet.
- Bao Viet premium health insurance
- Annual company trip, team building, picnic programs & happy hour monthly
- 12 days annual leave (14 days for female) + 1 day “rakumo day” + 1 day your birthday

## Contact
Fanpage: http://bit.ly/2MNMzFH
Send us your CV via email: trangtq@rakumo.vn or Skype: live:trangtq_5

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
