### ISSUE TITLE
rakumo - iOS Developer - TanBinh,Saigon - FT

### ISSUE THREAD

**Issue by trangrakumohr** [awesome-jobs/vietnam#2257]
## Location

* 364 Cong Hoa, Etown 2 Tan Binh Ho Chi Minh
* Full time

## Salary range

* 700 - 1,500 USD

## Requirements
*Must Have:

- At least 1 year-experience in Swift, iOS SDK.
- Strongly understanding of OOP, design patterns.
- Have knowledge of web services (XML, SOAP, REST, JSON).
- Have experience in developing client-server app.
- Have experience in using Core Data, custom UI on iOS, using the social frameworks such as Facebook, Twitter.
- Familiar with network programming, socket, WebSocket, RESTful API, push notifications.
- Have experience in releasing apps on the App Store.
- Have experience in Unit tests on iOS.

*Nice to have:

- Ability to develop mobile applications on Android.
- Able to work under pressure of deadlines and quality of products.
- Ability to work proactively, with a sense of responsibility for work assigned.

## You’ll be responsible for

- Design, develop, test and integrate our native mobile iOS applications.
- Coordinate with QC team to ensure product quality.
- Optimize, solve issues based on user feedback.
- Report to leader / PM.

## Why it would be awesome to work with us

- Onsite opportunity in Japan.
- Working directly with foreign customers.
- Holiday (30/4, 2/9),Year-end, TOEIC/Japanese/Google Cloud Platform (GCP) certificate & recommendation bonus.
- 13th-month salary before Tet.
- Bao Viet premium health insurance.
- Annual company trip, team building,  picnic programs & happy hour monthly.
- 12 days annual leave (14 days for female) + 1 day “rakumo day” + 1 day your birthday.

## Contact
Fanpage: http://bit.ly/2MNMzFH
Send us your CV via email: trangtq@rakumo.vn or Skype: live:trangtq_5

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
