### ISSUE TITLE
[National Australia Bank - VDC in partnership with PYCOGROUP] - Senior React Native Engineer - Ho Chi Minh city - FT

### ISSUE THREAD

**Issue by talenthubasia** [awesome-jobs/vietnam#2258]
## Location

* Etown Central, Doan Van Bo Street, District 4, HCMC
* Etown Cong Hoa, 365 Cong Hoa Street, Tan Binh District, HCMC

## Salary range

* USD Super Attractive

## Job Overview
We're seeking experienced and talented Mobile Engineers to work on our flagship mobile platform that serves millions of customers daily. As a Senior React Native Engineer, you'll join other Engineers, Manager Engineers, Test Automation Engineers, Business Analysts, and UX Designers. You’ll own key modules of our global product where you’ll use and grow your experience to architect and build mobile applications to maintain high availability and reliability.

## Your responsibilities
* Collaborate with other NAB's technology leaders towards improving and fulfilling the NAB technical direction;
* Design, develop, review, implement, and manage application code and services for the production and pre-release environments;
* Design, develop, review, implement and manage continuous integration, build management and deployment scripts, systems, and any code as required;
* Participate in Agile software development, prototyping, and code review with international development teams to build mobile apps;
* Understand the requirements of the customer or business and utilize this knowledge to develop applications that are consistent;
* Monitors for and anticipates platform trends and upcoming critical changes;
* Monitors client feedback for problems and proactively schedules resolutions where needed;
* Work with delivery teams to achieve success through development using CI/CD and DevOps practices, processes and tooling;
* Provide robust coding practices and solid unit and component test coverage, and code debugging.

### Must Have

* Over 5 years' working experience in software development covering mobile application development;
* Experienced across the full software delivery life cycle (planning, analysis, design, implementation, testing, deployment, and maintenance);
* Experience working with diverse teams from development, testing, security (pinning and cryoto), architecture, infrastructure to business and management;
* Knowledgeable of agile software development and management methods;
* Solid experience with React Native, its eco-system, and architectural patterns - Clean Architecture, MVVM, MVP, SMVP, MVC;
* Experienced working as an engineer within one or more backend technologies as well as RESTful JSON APIs;
* Experienced with Unit tests, UI Tests, API Testing: Mocks, Stubs; Security Mobile Apps: Application Security Transport, Local Data Storage, Reverse Engineer;
* Experienced in build management tools including continuous integration and delivery practices and tools (Gradle/ Jenkins/ FastLane/ XcodeBuild/ Git);
* Strong knowledge and experience with SOLID principles;
* Good understanding of modern software development practices and automation testing;
* Strong English communication skills (both verbal & written), and problem-solving and analytical skills;
* Coming from a solid technical background in Android development (Android Studio/ SDK, Java, at least one year in Kotlin); or iOS  development (XCode, Objective-C, Swift).

### Ideally

* University degree in IT field or equivalent industry experience;
* Experience in the Banking or Financial Services industry (preferred);
* Experienced in controlling change risk in a large application;
* Experienced in Performance test, Accessibility for mobile apps;
* Experienced with device fragmentation issues;
* Microservices approach.

### Why it would be awesome to work with us?
* Opportunity to join in a global software development environment
* Very competitive remuneration package
* Generous private family healthcare for yourself and two family members
* A solid team behind you - great people who love what they do
* The pleasant, enthusiastic, international work environment
* Opportunity for traveling & training in Australia
* A brand new & state of the art Agile office
* Latest technologies, flexible working hours
* A promising training and career path
* Fun team activities & outing
* English learning with native English teachers

**_CLOUD FIRST
NAB is undergoing an exciting "Cloud First" technology transformation by taking advantage of the latest tools and techniques used by leading technology and digital companies globally. But it’s not just about the Tech, we are also investing heavily in our people, so if you have an appetite to learn, grow and elevate others around you, this is the place for you!_**

**_IT'S MORE THAN MONEY!
We naturally also provide a very competitive remuneration package but a career with us is about a lot more than money. We believe in people with ideas and dreams, and we want you to achieve your aspirations. We'll work together to deliver exceptional products and outcomes that push the limits of our own aspirations. Our passion for creating value and exceeding our customers' expectations means we're constantly striving to redefine our standards of excellence. You'll have our backing to develop and our encouragement to explore, realize and reach your full potential._**

### Contact
Email: hao.nguyen@pycogroup.com 
Mobile: 0974 911 901
Skype: haominhtn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
