### ISSUE TITLE
Smarp - Backend engineer/intern - Remote - FT/C

### ISSUE THREAD

**Issue by truongsinh** [awesome-jobs/vietnam#226]
## Location
- Remote
## Salary Expectation
- From €400 (student/intern) to €2000 (guru) per month; €1 = 25375VND as of 6th of June, 2016
### Must Have
- Professionalism
- Self-motivation
- Adaptability
- Inter-personal communication
- Fluent English written and oral communication ([CEFR](http://www.coe.int/t/dg4/linguistic/Cadre1_en.asp) B1, TOEFL iBT 72, IELTS 5.5 or equivalent)
- Fast learning capability
### Ideally
- Golang
- [Graph database](https://en.wikipedia.org/wiki/Graph_database) / [OrientDB](http://orientdb.com/)
### If chosen, you would
- Use Golang to continuously build a clean, testable, scalable Smarp backend
- Spin-off Smarp backend frequently used modules to open source
- Optimize all SQL queries using `EXPLAIN`
- Minimize backend to database roundtrips
- Work with third party APIs
- Keep track of changes from third party APIs
- Perform debugging, quality control testing and response to user complaints
- Stay up-to-date on new technology, development tools and emerging standards
- Maintain documentation of RESTful endpoints and APIs to be used by (web) frontend and mobile apps
### What we offer
- Fast-growing, international, investor-backed start-up with a kick-ass sales and tech teams
- Chance to leave your mark and have some of the world’s leading companies use your work
- Growth with the company
- Multicultural work environment, [check out our fun loving team in action>>](https://vimeo.com/161968725)
- Flexibility and work-life balance
- Competent development team
- Latest yet compatible and mature technology
- Contribution to and recognition by open source community
- Business/technical meetups and conferences
## What is Smarp?

Smarp, [featured on BBC](https://www.youtube.com/watch?v=jBmug2bSZAQ), is a leading employee advocacy SaaS provider. Smarp exists to inspire every professional to be an influencer by making knowledge sharing simple and rewarding. At it’s core, Smarp helps employees discover and share professional content to their networks that creates value for their employer, their networks and themselves as professionals. Smarp is the number 1 choice for employee advocacy software, [see how it works >>>](https://www.youtube.com/watch?v=jrTOg0pQCG4)

As a company, Smarp is an award winning, global and fast growing start-up focused on employee advocacy. Employee advocacy is all about encouraging employees to participate in communications by discovering and sharing inspiring content to their external social media networks. Currently, we have operations in Helsinki, Stockholm, London and New York with over 50 full-time team members.

Look for more info from our homepage: www.smarp.com
## Still interested? Apply now

http://smarp.breezy.hr/

PS: about me (all in Vietnamese)
- http://www.giaoduc.edu.vn/chang-trai-viet-in-hinh-tren-tem.htm
- http://phunuonline.com.vn/thoi-su/xa-hoi/lam-viec-de-cam-on-cuoc-doi-74990/
- http://thanhnien.vn/gioi-tre/ra-bien-lon-437057.html
- http://www.bbc.com/vietnamese/inpictures/story/2006/12/061208_vietfaces_gn.shtml

**Comment by Gnouc** [comment]
Is the job expected a remote worker? I don't see the description page mention `remote`.

**Comment by truongsinh** [comment]
Hi @Gnouc, thank you for pointing that out. To answer your question, yes this job can ALSO be expected as remote (besides onshore engineers in Helsinki). This is done to broaden our talent pool.

**Comment by catvm** [comment]
Hi @truongsinh ,

I got a few years experience in .NET, may I have a chance to apply as remote worker ? 

Thanks,
Cat

**Comment by truongsinh** [comment]
Hi @catvm,

We exclusively use Go for our backend work, but as described, we always appreciate fast learner, and are willing to help you succeed as an engineer.

**Comment by catvm** [comment]
Hi @truongsinh,
How can I contact you ? 

Thanks,
Cat

**Comment by joneslee85** [comment]
@truongsinh please update your post with contact details
