### ISSUE TITLE
FETCH TECHNOLOFY - Front-end Angular JS Developer - HCMC - FT

### ISSUE THREAD

**Issue by Phamtranyennhi** [awesome-jobs/vietnam#2260]
## Ho Chi Minh

* District 9, Ho Chi Minh

## Requirement: 
* 4 years of experience 
* Has included 2 years working with ROR or Golang
* Good English communication

**Benefits**

* Provide Mac book for wok 
* Insurance in full salary
* 13th salary bonus
* Review salary 2 times/year
* Allow to work from home 2-3 days/week
* Team building,team social activities every week (football, ...)

### Contact
Email: nhipham@fetch.tech
Skype: phamnhi1097@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by qcam** [comment]
@Phamtranyennhi Could you please update the post to be in English and conform to our format? Thanks.

**Comment by Phamtranyennhi** [comment]
Dear admin, 

This is recruitment need from Fetch Technology Viet Nam, we have the legal enterprise agreement to work in Viet Nam and have been contributing in the market for over 4 years. This is my work email and attached in the posting too: nhipham@tech.fetch

If you need any information for the verifying, please do not hesitate to contact me.

Thank you

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
