### ISSUE TITLE
LINE Technology Vietnam - Project Lead - Hanoi - FT

### ISSUE THREAD

**Issue by BichThuy12** [awesome-jobs/vietnam#2270]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation
* Market-Competitive and very attractive
* Up to $4000/month

## Responsibilities
- Estimate, make plan, be in charge of the system development life cycle
- Requirement analysis and system analysis
- Build architecture design, review design document
- Team member management

## Qualifications
MUST:
- Experience in managing a development team with at least 05 members.
- Experience in designing client-server development.
- Besides coding, be able to create and review the software architecture design from basic to detail level as well as can take quality control of the project.

PREFER:
- Good in communication skill with partner teams directly in English.
- Ability to get requirement directly from business team or product manager, then analyze and discuss among the stakeholders to make them clear. The real challenge is that you should not only receive information passively but also try to propose some good ideas or effective solutions in a reasonable way.
- Ability to give solution for difficult problem. With a group of very large user, in-active applications, we always encourage our engineers to find out the best solution to improve them even they have no problem at that time.
- You are welcomed to do these tasks from just giving idea, designing, to coding or code reviewing tasks.

### Why it would be awesome to work with us
- Opportunity to collaborate with a global team encompassing various functions and viewpoints;
- Field projects in Branding and Partnership to fast-track your career development;
- Ability to realize your ambitions through direct work with leadership team;
- WOW benefit package by Corporation standards.
- Bonus: Performance bonus 2 times per year (up to 3 month-salary/year) and 13th month salary
- Training: join our language classes for free (English, Japanese)
- Healthcare for employee and 3 family members (100% sponsored by company)
- Company activities: Annual company trip, Sport activities (Football, billiard, ping-pong, yoga, etc.)

### Contact
Homepage: https://linetechnology.com.vn/en/
Email: dl_lv_recruit@linecorp.com
Skype: bichthuypham15

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
