### ISSUE TITLE
LINE Technology Vietnam - Java Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by BichThuy12** [awesome-jobs/vietnam#2271]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation
* Market-Competitive and very attractive
* Up to $2500/month

## Responsibilities
- Build and develop products or systems with high numbers of users.
- Improve the efficiency of existing products.
- Build the architecture and design of new products and features.
- Researching new technologies to apply in current and future projects. - Coaching and mentoring skills for junior developers.
- Adhere to the company's project development process.

## Qualifications
MUST:
- Strong experience with JAVA.
- Deep knowledge of OOP, design pattern.
- Have Experience in one of these frameworks as Spring, Struts, JSF...
- Review code skills.
- Strong knowledge of databases (Database Design & Optimization).
- Eager to learn new technology and to resolve project.
- Have a passion for exploring new technology and have always been the pioneer into exploring new technology.

PREFER:
- No Language Skills Required. Good at English or Japanese is advantage.
- Experience with development/operation of systems with large quantities of data and traffic.

### Why it would be awesome to work with us
- Opportunity to collaborate with a global team encompassing various functions and viewpoints;
- Field projects in Branding and Partnership to fast-track your career development;
- Ability to realize your ambitions through direct work with leadership team;
- WOW benefit package by Corporation standards.
- Bonus: Performance bonus 2 times per year (up to 3 month-salary/year) and 13th month salary
- Training: join our language classes for free (English, Japanese)
- Healthcare for employee and 3 family members (100% sponsored by company)
- Company activities: Annual company trip, Sport activities (Football, billiard, ping-pong, yoga, etc.)

### Contact
Homepage: https://linetechnology.com.vn/en/
Email: dl_lv_recruit@linecorp.com
Skype: bichthuypham15

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
