### ISSUE TITLE
LINE Technology Vietnam - Frontend Engineer (Reactjs / Vuejs) - Hanoi - FT

### ISSUE THREAD

**Issue by BichThuy12** [awesome-jobs/vietnam#2272]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation
* Market-Competitive and very attractive
* Up to $2500/month

## Responsibilities
- Participate product/application development life cycle, including planning, analysis, design, implementation and maintenance, focus on UX/UI design both for PC and mobile. 
- Create user-friendly web application with modern technologies (JavaScript/ HTML5/ CSS3) and framework (VueJS/ ReactJS)
- Proposing and designing UI with consideration of UX.
- Build reusable code and libraries for future use.
- Keep yourself up-to-date with emerging technologies.
- Write technical specifications based on conceptual design, business/technical requirements.
- Collaborate with Back-end Engineer and others to improve usability.

## Qualifications
MUST:
- More than 2 years of work experience in Front-end development.
- Excellence knowledge of HTML/CSS/DOM/JavaScript.
- Good knowledge of browser troubleshooting and debugging.
- Ability to build a web application with at least one of JS frameworks like ReactJS/ VueJS from the beginning.
- Have passion for exploring and learning new technology
- High sense of responsibility

PREFER:
- English from intermediate to advanced.
- Experience in using cloud services such as AWS, Azure, etc.
- Experience in using tools for build and task runners (CI/CD).
- Experience in developing applications with server-side languages such as Java, Perl, php, ruby, .net, python…
- Preferred knowledge of web performance technology.
- Experience with Agile/Scrum development.
- Contribution to OSS projects and communities.

### Why it would be awesome to work with us
- Opportunity to collaborate with a global team encompassing various functions and viewpoints;
- Field projects in Branding and Partnership to fast-track your career development;
- Ability to realize your ambitions through direct work with leadership team;
- WOW benefit package by Corporation standards.
- Bonus: Performance bonus 2 times per year (up to 3 month-salary/year) and 13th month salary
- Training: join our language classes for free (English, Japanese)
- Healthcare for employee and 3 family members (100% sponsored by company)
- Company activities: Annual company trip, Sport activities (Football, billiard, ping-pong, yoga, etc.)

### Contact
Homepage: https://linetechnology.com.vn/en/
Email: dl_lv_recruit@linecorp.com
Skype: bichthuypham15

**Comment by ngobach** [comment]
Tuyển mình đi bạn ơi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
