### ISSUE TITLE
OnPoint - Senior/Junior FullStack (Elixir) - Saigon - FT

### ISSUE THREAD

**Issue by Giang-Vo** [awesome-jobs/vietnam#2276]
## Location

* Saigon, Vietnam
* Quận1

## Salary Expectation

* Senior up to 2500$/month
* Junior up to 1500$/month

## Requirements
* Bachelor’s degree in computer science, information systems or a related field.
* Having 1 - 3+ years of experience in web development.
* Experience with multiple programming languages(Elixir, Python, Ruby, or Go).
* Experience with Redis, Elasticsearch has knowledge about Caching is a plus.
* Experience with web API technologies: RESTful, Authentication, Authorization, and multi-devices session.
* Experience with Postgresql other (Mysql, NoSQL) is a plus.
* Experience with version control (Git)
* Experience with frontend work: HTML/CSS, bootstrap, SASS, ReactJS, etc
* Good knowledge of eCommerce, Saas, etc.
* Knowledge of Integrations with various Third-party CRM.
* Ability to quickly master new technologies and push the envelope for performance and reliability.
* Experience with agile development processes and frequent release cycles.
* Great interest in eCommerce.

## Skills
*Elixir, Python, Ruby, or Go
### Must Have
*Python

### Responsibilities
* Work closely with the Technical Manager, Product Manager, and Product Designer to build a next-generation web application.
* Design and develop new features for the platform/system.
* Evaluate and clarify product requirements. Participate in reviewing product design.
* Maintain quality standards of excellence and ensure compliance with standards and best practices.
* Mentor junior team members.
* Build efficient and reusable code and systems.
* Identify and address performance bottlenecks.
* Participate in architecture design and code reviews.
* Communicate with other team members to determine the best solutions to difficult problems.
* Passion for performance debugging and benchmarking.

### WHY YOU'LL LOVE WORKING HERE
* An opportunity to learn at a company that is growing for regional scale (South East Asia)
* Working in a young, super talented and supportive team environment
* Attractive salary (Up to 2500 USD)
* Company trip, team building
* PTI Insurance
* Macbook Pro for Developer

### Contact
Homepage: https://www.onpoint.vn/
Send CV to hangiang.vo@onpoint.vn

**Comment by Giang-Vo** [comment]
fullstack,

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
