### ISSUE TITLE
[LINAGORA] Mobile Developer (iOS, Android, Flutter) - Full-time - Hà Nội

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2277]
## Location

* 5 Dien Bien Phu, Ba Dinh, Ha Noi

## Salary Expectation

* Up to 40m gross

## Requirements

* Bachelor’s degree in information technology, or related field.
* At least 2 years in mobile software development (Android, iOS, or Flutter).
* Familiarity with RESTful APIs to connect applications to back-end services.
* Knowledge of other web technologies and UI/UX standards.
* Understanding of State management approaches.
* Proficient understanding of code versioning tools.
* Familiarity with cloud message APIs and push notifications.
* Strong OO design and skills in Functional programming, Reactive programming.
* Fluency in English.

### Responsibilities

You’ll develop from scratch the mobile application of the OpenPaaS (https://open-paas.org/) platform (mail, calendar application for fulfilling OpenPaaS Eco-system).
* a Drive application, giving users the ability (https://linshare.org) files on their mobile devices to have their LinShare
* a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles
* a Subscription management application for the flagship software Twake Console
* a LinEDU application to contribute to Eco-system with LMS

**Duties & Responsibilities**
* Participate in product design, offer new ideas
* Design and build applications for mobile platforms
* Collaborate with product and business teams to define our products that are suitable for the market
* Design and implement a mobile application for mobile platform using new technology
* Work in a team, using AGILE methodologies, to deliver software on time
* Collaborate with other team members to ensure our team maintain high standards
* Support international teams in developing products to meet the client‘s requirements
* Keep up to date on the latest industry trends in the mobile technologies
* Coaching the member of the team and attend to interview process to scan the technical part

### Why it would be awesome to work with us

* Work in a multinational team with highly skilled people for international projects.
* Correct work-life balance.
* Annual company trip, exciting team-building activities.
* Working time: 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

* Homepage: linagora.vn
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
