### ISSUE TITLE
[LINAGORA] Java Developer - Fulltime - Hà Nội

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2279]
## Location

* 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to 40m gross

## Requirements

* Strong background in Java development
* Strong development processes: Agile (scrum), Git & code review, Continuous integration (Jenkins)
* Experience with at least some of the following technologies: NoSQL (Cassandra, ElasticSearch), messaging (RabbitMQ), object storage (Swift), load testing (gatling)
* Curiosity towards new technologies
* Knowledge of mail protocols is a plus (SMTP, IMAP, JMAP)
* Good level of English

### Responsibilities

* Working with the team to set new milestones for our roadmap.
* Adding new features, and improve test automation to cover cloud operations.
* Implementing using modern big data technologies like Apache Cassandra, ElasticSearch, and RabbitMQ.
* Contributing a JMAP implementation, a new mail protocol standard that we participate to elaborate, disrupting the way client mail user applications are being written.

### Why it would be awesome to work with us

* Work in a multinational team with highly skilled people for international projects.
* Correct work-life balance, flexible remote work policy.
* Annual company trip, exciting team-building activities.
* Working time: 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

* Homepage: linagora.vn
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
