### ISSUE TITLE
[LINAGORA] Senior Automation Tester - Fulltime - Hà Nội

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2282]
## Location

* 5 Dien Bien Phu, Ba Dinh, Ha Noi

## Salary Expectation

* Up to 40m gross

## Requirements

* Good level of English
* Passionate about OpenSource and Free Software
* Basic knowledge of Linux operating systems
* Master at least one automation frameworks (preferably Robotframework)
* Be familiar with CI/CD configuration
* Have knowledge about a variety of automation test frameworks
* Have knowledge/experience in at least one of the following fields: performance testing, security testing 
* Eager to learn new techniques
* Willing to share knowledge with other team members

### Responsibilities

While you are expected to build/maintain our automation test scripts (mainly using Robotframework), we are also ambitious to approach new technical test techniques to enhance the quality of our software products.

**Responsibilities and Duties**:

* Build/main our automation test scripts.
* Support/train other team members about technical test skills.
* Research on other technical test areas including performance/security/… and apply to our projects
* Configure CI/CD for the automation script to run in synchronization with the builds on the test platform.

### Why it would be awesome to work with us

* Work in a multinational team with highly skilled people for international projects.
* Correct work-life balance.
* Annual company trip, exciting team-building activities.
* Working time: 5 days/week, from Monday to Friday.
* Lunch allowance, 13th-month salary, competitive salary.
* Annual health checkups and other benefits based on labor law.
* Participate in Open Source communities and conferences in Vietnam.
* Modern working space, free coffee.

### Contact

* Homepage: linagora.vn
* Email: vnhr@linagora.com
* Skype: live:27503e33718408d1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
