### ISSUE TITLE
One of top securities company - React Native - HCMC - Offer up to $1200

### ISSUE THREAD

**Issue by viettaholic** [awesome-jobs/vietnam#2283]
## Location
* Saigon, Vietnam

## Requirements
* 1+ years React Native developer experience

### Contact
Homepage: vdsc.com.vn

Mô tả công việc
- Phát triển ứng dụng giao dịch trực tuyến trên nền tảng di động;
- Phát triển/vận hành các sản phẩm dịch vụ theo nhu cầu phát triển của công ty;
- Đề xuất các ý tưởng hay, công nghệ mới để giúp hoạt động công ty ngày càng ổn định và hiệu quả;
- Phối hợp với các nhân viên trong bộ phận và các phòng ban nghiệp vụ để hỗ trợ sử dụng, bảo trì và phát triển các ứng dụng.            (Chi tiết sẽ trao đổi trong buổi phỏng vấn)
--
Yêu cầu 
Tốt nghiệp Cao đẳng/Đại học hoặc tương đương chuyên ngành Công nghệ thông tin;
Tối thiểu 1 năm kinh nghiệm về lập trình ngôn ngữ Reactive Native/Java;
Có kiến thức về các ngôn ngữ lập trình Objective-C, Swift, Android(java) là 1 lợi thế;
Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành tài chính.

Số lượng : 2
Phúc lợi công ty:
- Lương cạnh tranh, thưởng theo năng lực, hiệu quả công việc;
- Môi trường làm việc chuyên nghiệp, thân thiện;
- Cơ hội tham gia các chương trình đào tạo, các hoạt động phát triển nghề nghiệp của Công ty;
- Khám sức khỏe định kỳ hàng năm, bảo hiểm tai nạn, bảo hiểm sức khỏe;Hưởng đầy đủ các chế độ bảo hiểm theo quy định pháp luật Việt Nam;
- Hỗ trợ chi phí trang phục, du lịch hàng năm và các chế độ phúc lợi khác theo quy định của Công ty.

Nơi nhận hồ sơ | Phòng Nhân sự & Đào tạo – Tầng 4, Số 141 Nguyễn Du, P.Bến Thành, Quận 1, TP.HCMNgười liên hệ: Ms. Thi/Ms.TươiEmail: tuyendung@vdsc.com.vnĐiện thoại: (028) 6299 2006 -1441/1443

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
