### ISSUE TITLE
Data Engineer - Omnilytics - Remote

### ISSUE THREAD

**Issue by cypherius17** [awesome-jobs/vietnam#2284]
## Location

* Malaysia
* Remote

## Salary Expectation

* $2k-3k/month

## Requirements
* Strong computing, devops or dataops background.
* Strong proficiency in Python
* Experience in working with cloud technologies such as AWS and GCP
* Technical experience building, optimising and managing data pipelines
* At least 3 years of data engineering-related experience

## About The Role
* We are looking for a Data Engineer to join our innovative Data team. You will be transforming businesses all around the world in making better data-driven decisions by:
* Enhancing data collection and processing procedures and pipelines;
* Processing, cleansing, and verifying the integrity of data used for analysis;
* Developing processes, techniques, and tools to analyse and monitor model performance while ensuring data accuracy;
* Coordinating with various technical/functional teams to implement models and monitor results; and
* Upholding the quality of any Company-related web products and services by testing for and resolving bugs.

 You will fit right in to our team if you posses the following traits:

* Technical excellence - You possess good engineering skills and an eye for clean, maintainable code. To you, engineering is not just coding; it involves wisdom, drive, collaboration, and methodology. There are few who view engineering as a tool—means to an end. But you view engineering as an art form in itself. You are constantly improving your craft. You take pride in your work. You write code for other humans to read (it just happens to be executable by machines!). Engineering is for the most part a conscious effort, not mere trial and error.

* Problem solving mindset - You eat challenges for breakfast. You believe that problems are made to be solved and not avoided. Often you will try many different ways instead of giving up when presented with obstacles. If you have a reputation for being a defeatist or throws the first excuse that comes in mind when presented with a challenge, this role is not for you.

* Strong aptitude to learn - You will be required to learn a lot of new things. If you are aware that change makes you uncomfortable, do reconsider your career choice in technology. Technology is fast paced, fun and we have access to the latest know-hows in the industry. Here at Omnilytics, you will be part of a team that continues to learn and grow in both industry knowledge and technical skills.

## Contact
Email: danhthais17@gmail.com
Skype: danhthais17

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
