### ISSUE TITLE
[SUTUNAM] - Middle/Senior Back-End (PHP/JavaScript) - Hanoi - FT 

### ISSUE THREAD

**Issue by NhatHoa-Sutunam** [awesome-jobs/vietnam#2286]
[2021 - Sutunam - PHP Backend Developer - Job description.pdf](https://github.com/awesome-jobs/vietnam/files/6002733/2021.-.Sutunam.-.PHP.Backend.Developer.-.Job.description.pdf)
We are seeking for **Back-End Developers** who are keen to use the very latest in web technologies and experienced in developing highly polished website for client. Strong passion for web development, eagerness to apply new technologies at work.

You will join a team of talented developers and work on international web application, e-commerce and mobile platforms (PWA) with beautiful UX/UI creation and high standard!

## Location

* Hanoi, Vietnam
* Full-time

## Salary Expectation

* $1000 - $3000/month

## Requirements

You will be working closely with our amazing design team, other front-end developers, and project managers to deliver world-class publicly visible websites.

* Minimum 2-year experiences in PHP and/or JavaScript web development, systems integration (**for Middle**);
* Minimum 4-year experiences in PHP and/or JavaScript web development, systems integration (**for Senior**);
* Experience with internal and external applications, Unix or Linux;
* Experienced in optimizing the code & server for high traffic websites
* Magento or framework experience (Symfony, Laravel);
* Able to write well-structured, maintainable code;
* Can-do-attitude and put the goals of the team before your own prestige;
* You are able and hungry to take on a lot of responsibility;
* Able to communicate, read, and write in English.

## Skills
* PHP / Magento / Javascript / Symfony

## Responsibilities
* Configuration and management of website architecture, including application, and database layers.;
* Participate in "**Technical Engineering**" of a Project, which may include Operational Procedure discovery and recommendations for improvement;
* Relational database design and development;
* Lead Custom Development Projects, with or without, internal and externally based Developers/ Project Managers;
* Troubleshooting and resolution of production issues;
* Continued development of new and existing websites, adding functionality and improving existing operations;
* QA testing code.

### Why it would be awesome to work with us
* Because you want to be part of a **multi-winning award** digital Agency;
* Because you want to work with talented colleagues;
* Because you want to work on the exciting new tech;
* Because you want to grow in a professional & **English-speaking**; environment where your voice will be heard;
* Because you believe **small changes** everyday make **great achievements**;
Or, just because you **love** us! ;)

### Interesting engineering projects
Let's check out our worldwide projects at: https://en.sutunam.vn/our-work/

### Contact us to have a meet! ;)
Website: https://beahero.sutunam.com/
Mail box: [hr.vietnam@sutunam.com](mailto:hr.vietnam@sutunam.com)

**Comment by khanhlinh2295** [comment]
Cool! (y)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
