### ISSUE TITLE
Raksul Vietnam - Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by thaopham-bee** [awesome-jobs/vietnam#2288]
Raksul is a B2B platform builder headquartered in Tokyo, Japan. To change the world by reinventing legacy industry structures with the power of the internet, it is now operating three sharing platforms in printing, advertising and logistics. 

Raksul’s biggest platform, raksul.com, is an online printing e-commerce service released in 2013, and it has over 1 million registered users in Japan. 

Due to the rapid product expansion, Raksul has just set up a new entity in Vietnam in June 2020, and grown its team of local engineering talents.

## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - 2,000 USD

### Must Have

* Ability to discuss in English with global members
* About 3 years or equivalent working experience for Linux base software development
* Experience in developing web applications with OOP in Ruby, Python, Java or similar.
* Working experience in web frameworks (at least 1 of the following: Laravel, CakePHP, Symfony, Ruby on Rails, Django, etc.)
* Experience in designing and tuning relational database like MySQL or PostgreSQL.

### Ideally

* Experience in Ruby
* Experience in front-end development using Sass, TypeScript, Transpiler, etc.
* Experience in improving legacy code/system and working with REST API
* Experience in pair programming and/or mob programming
* Experience in working with cloud computing such as AWS 

### Other important factors

* Proactive thinking and execution
* Ability to work with others and preference on teamwork
* High interest in learning and using new technology
* Strong interest to change old industries with technology
*  Freshers can also apply

### We are looking to hire candidates for the following responsibilities

With the guide by senior members, 

* Demonstrate product ownership with product managers and business teams.
* Guarantee the products quality for long term operation.
* Provide assistance and advice on the definition of system requirement and system design.
* DevOps of various services, and partner solutions.

### Why it would be awesome to work with us

* Flexible working hours, working from home conditionally
* Free drink, monthly team building party
* Opportunities for business trip to Japanese partner company and HQ office
* Salary review every 6 months & health insurance
* At least 15 paid days off per year
* MacBook Pro provided 

### Interesting engineering projects
* Our main product, Raksul (https://raksul.com/), a printing platform connects those who have printing requirements with printing companies. 

### Contact
Homepage: https://recruit-vn.raksul.com/
Email: vietnam-hr-uc@raksul.com 

Other:
https://itviec.com/companies/raksul-inc

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
