### ISSUE TITLE
TourNative - Senior Ruby on Rails developer - San Francisco, CA, USA / Remote  - FT 

### ISSUE THREAD

**Issue by quinnie0930** [awesome-jobs/vietnam#229]
TourNative is a for connecting travelers with local tour guides and experts. Locals post unique experiences that immerse you in their culture. TourNative serves as a bridge between travelers who are looking to experience a country in its full authenticity and the natives who are eager to show their local hidden gems. 

Our mission is to provide a global platform where travelers can connect with locals for culturally immersive experiences in a simple and easy-to-use manner. We also wish to support local communities and help provide income for the natives by fostering and facilitating entrepreneurship.
## Location
- San Francisco, California, USA
- Remote
## Salary Expectation
- $1500-2500/month or negotiable & stock options
## Requirements
- B.S in Computer Science
- At least 3 years experience with Ruby On Rails
- JavaScript (React JS,  Angular, etc)
- PostgreSQL
- 5+ years Software Engineering experience
- Use TDD for their code
- English proficiency
- involve and contribute to open source community
### Responsibilities

Help develop and build marketplace startups.  We're are a silicon-valley based startup (http://tounative.com) that will soon go for a round of financing in 3rd and 4th quarter of 2016
### You can bring
- open to feedbacks
### Contact

Email resume and github account to quynhpham at gmail dot com

**Comment by joneslee85** [comment]
@quinnie0930 thanks for posting with us.

Please revise your post to ensure that:

* Title complies with our guideline
* Company name / details must be revealed
* Ensure technical terms are correct, for eg JavaScript instead of javascript
* You are the HR / employee of the company - NOT the 3rd party recruiter

Cheers
