### ISSUE TITLE
TINYpulse - Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by TINYpulse** [awesome-jobs/vietnam#2292]
TINYpulse makes truly unique software tools for businesses that treasure their most valued resource — their people. We believe happier employees result in stronger companies! We are seeking employees that are inspired by our goal to transform the manager-employee feedback loop. Together we can make stronger cultures.

Over 1,000 companies from around the globe use TINYpulse to engage and develop high-performing teams, including Stitch Fix, HubSpot, Capital One, and Brooks Shoes & Apparel. We are also committed to giving back by donating 1% of our time to our local community, 1% of our product to non-profits, and 1% of our profits to non-profit organizations.

We are looking for a Back end Developer who is able to build single page applications including implementing, testing, integrating and utilizing APIs with latest front-end web technologies.
## Location

* Saigon, Vietnam

## Salary Expectation

* Up to USD $3,300

## How do you know if this is the right fit for you? If you,

- Enjoy a fast-paced entrepreneurial environment
- Have strong analytical and problem-solving skills
- Are coachable and personable, and, ideally, with a good sense of humour!
- Are a team player, who is willing to disseminate knowledge to other team members
- Are a passionate individual who is not afraid to ask questions and eager to learn
- Maintain a high degree of knowledge of current technologies and tools
- Make recommendations to improve effectiveness of the team
- Have good communication skills, in both Vietnamese and English

## Requirements and Skills

- Languages: being efficient in any of the following languages: Ruby, Java, PHP
- Framework: strong experience in modern web technologies such as Ruby on Rails,etc.
- Ability to build standalone Ruby gems or any reusable libraries
- Third-party API Integration
- Database: relevant experience with relational databases such as MySQL or PostgreSQL
- Test coverage: competent skills in unit and integration tests (RSpec / Cucumber)
- Platform: adequate knowledge of Continuous Integration/Deployment, AWS and Docker=
- Be familiar with Microservices Architecture and Distributed System

### Bonus

- UI/UX knowledge
- Experience with React.js
- Familiarity with Reactive Programming or Functional Programming

### Why it would be awesome to work with us

-  Free laptop Macbook that fits your needs.
- Unlimited vacation policy; work hard and take time when you need it.
- Full medical in­patient & out­patient/ dental/ maternity package to fit your and your spouses' needs.
- All benefits followed Vietnamese labour law, including 13th month salary.
- Employees are showered with snacks & drinks in our bar, mini parties every week, followed with big events every quarter.
- Training opportunity: continuing development of technical, soft skills, and English through both internal and external classes

### Interesting Engineering Projects

Our main product, www.tinypulse.com, the world’s leading employee engagement platform trusted by over 1,000 businesses to reduce turnover, improve communication, and build a world-class culture.

### Contact
Homepage: www.tinypulse.com
Email: joy@tinypulse.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
