### ISSUE TITLE
LUNA - Ruby Developer - Saigon - FT

### ISSUE THREAD

**Issue by monkeydl** [awesome-jobs/vietnam#2294]
## Location

* Saigon, Vietnam

## Salary Expectation

* Up to 30M/month for Junior
* Up to 40M/month for Intermediate
* Negotiable for Senior

## Requirements
* Strong fundamental understanding of software development
* A passion for startup
* A taste for good products
* Curiosity and the will to learn
* Web development experience, ideally both in Frontend and Backend

### Must Have

* Ruby on Rails
* HTML/CSS/JS

### Ideally

* 2 years experience in developing web application using Rails
* Understanding of both Backend and Frontend

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop new LUNA mobile app and website
* Participate in brainstorm, design and development new features
* Maintaining existing features
* Ensure top quality and experience for users
* Minimize bugs and crashes, as well as continuously improving user experience and ease of use

### You can bring

* Craftmanship in mind
* Attention to details
* Appreciation for perfection - we accept at least 95% polished product only.

### Why it would be awesome to work with us

* Beautiful office at Vincom Center
* Competitive salary
* Founding employee stock

### Contact
Homepage: luna2.me (in development)
Email: hung@lunatrading.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
