### ISSUE TITLE
BE VIETNAM - Senior Backend Engineer - FT - HCM city 

### ISSUE THREAD

**Issue by codercoppypaste** [awesome-jobs/vietnam#2295]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1100 - $2500  

### Must Have

* Experience coding Backend with various programing languages, willing to work with Golang/NodeJS
*  Understanding of system performance and scaling
* 2+ years Software Engineering experience

### Ideally

* Good at English
* Possess excellent communication, sharp analytical abilities with proven design skills, able to think critically of the current system in terms of growth and stability
* Experience in writing good unit test

### You’ll be responsible for

* Design and write with the cutting edge Golang/Java/NodeJS to improve the availability, scalability, latency, and efficiency of BE's range of services
* Work with engineering team to explore and create new design / architectures geared towards scale and performance
* Work with product managers, data analysts and implement products and features, and test their impact to business metrics.
* Participate in code and design reviews to maintain our high development standards
* Engage in service capacity and demand planning, software performance analysis, tuning and optimization
* Collaborate with product and experience teams to define and prototype feature specifications
* Work closely with infrastructure team in building and scaling back-end services as well as performing root cause analysis investigations
* Design, build, analyze and fix large-scale systems
* Learn full stack performance tuning and optimization
* Debug and modify complex, production software
### Why it would be awesome to work with us
* Fast growing, learning environment
* 13th salary, Performance bonus
* Medical healthcare
* Annual health check
* 15 days annual leave
* Transportation fee (BE's services)
* Holiday bonus
* Team Building and many engagement activities

### Interesting engineering projects
* One of the leading ride-hailing platforms in Vietnam with various project about Fintech, Mobility, ....
### Contact
Homepage: https://be.com.vn/
email: toan.luong@be.com.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
