### ISSUE TITLE
Dinovative - Back-end NodeJS Developer - HCM - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#2297]
## Location

* 11 D1 Street, Tan Hung Ward, District 7

## Salary Expectation

* $700 - $1200

## REQUIREMENTS
* Minimum 1-3 year working experience with Nodejs.
* Solid understanding of front-end technologies, such as JavaScript, HTML5, and CSS3.
* Agile/Scrum development cycle understanding
* Strong experience with RESTful APIs and WebSocket APIs.
* Experience working with database system such as mySQL, MongoDB, NoSQL.
* Solid understanding of object-oriented programming.
* Understanding fundamental design principles behind a scalable application and microservice architecture.
* Experience with the Express.js framework
* Knowledge working closely with git
* Experience in front-end development (ReactJS) is a big advantage.
* Strong analytical and problem solving abilities.
* Strong communication and client facing skills

### KEY RESPONSIBILITIES
* Design, build, and maintain efficient, reusable, and reliable Nodejs code.
* Integration of data storage solutions.
* Help maintain code quality, organization and automatization.
* Constantly learn and keep abreast of emerging technologies.
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping.
* Critique software designs and architectures.
* Peer review colleagues code and identifying areas for improvement.
* Provide development task effort estimates.
* Conduct client requirements gathering and analysis.
* Review test plans.
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control.

### You can bring
Collaborating with UX & UI designers, researchers and other engineers (web & mobile), you will have the ability to flex your full stack chops to help shape, design and build digital products that help solve key business needs

### Why it would be awesome to work with us
* Dynamic, young, friendly, flexible environment
* Laptop is provided
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding
* Free fruits/ cakes on happy hours time
* Celebration: birthday
* Party time: Team building, Xmas, New Year,…
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development

### Interesting engineering projects
Dinovative is looking for Back-end Software Engineer who is excited to work alongside a talented group of innovators to craft digital products. Being part of the conversation from the start, you will be expected to lead full lifecycle webbased projects including guiding technical scoping, design and implementation.

### Contact
Email: oanh.tang@dinovative.com
Skype: tangoanh
Zalo: 0909617173
[[Dinovative] Back-end NodeJS Developer JD.pdf](https://github.com/awesome-jobs/vietnam/files/6048661/Dinovative.Back-end.NodeJS.Developer.JD.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
