### ISSUE TITLE
Dinovative - Data Engineer (junior, middle level) - Dist 7, HCM

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#2298]
## Location

* District 7, HCMC, Vietnam

## Salary Expectation

* 700-1200$/month

## REQUIREMENTS
* Minimum 1 - 2 years of experience as a Software Engineer or similar role.
* Coding proficiency in at least one modern programming language such as Python (Pandas, NumPy, Scikit-learn), Java, Scala, Ruby.
* Experience with non-relational & relational databases (SQL, MySQL, NoSQL, MongoDB).
* Experience with cloud-based system Google Cloud Platform, Amazon Web Services: BigQuery, Dataflow, EC2, EMR, Redshift.
* Kafka, Hadoop, Cassandra, Elasticsearch knowledge is a plus.

### KEY RESPONSIBILITIES
* Create and maintain optimal data pipeline architecture.
* Identify, design, and implement internal process improvements: automating manual processes, optimizing data delivery, re-designing infrastructure for greater scalability, etc.
* Build the infrastructure required for optimal extraction, transformation, and loading of data from a wide variety of data sources using SQL and Google Cloud ‘big data’ technologies.

### Why it would be awesome to work with us

* Dynamic, young, friendly, flexible environment
* Laptop is provided
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding
* Free fruits/ cakes on happy hours time
* Celebration: birthday
* Party time: Team building, Xmas, New Year,…
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development

### Contact
Contact
Email: oanh.tang@dinovative.com
Skype: tangoanh
Zalo: 0909617173
[Dinovative_Data Engineer_JD.pdf](https://github.com/awesome-jobs/vietnam/files/6048659/Dinovative_Data.Engineer_JD.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
