### ISSUE TITLE
Dinovative - Devops Engineer - Dist 7 - FT

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#2299]
## Location
Dinovative is looking for Devops Engineer who has strong experience in infrastructure and
good in system administrator background. You will design and build the next-generation
infrastructure that support the Dinovative’s cloud network. You will enhance our pure DevOps
environment with your expertise in the areas of Systems Engineering, Network Engineering, and
automation. You will work closely with the CTO and Experienced Engineers to identify and
establish Devops practices in the company.

11 D1 Street, Tan Hung Ward, District 7

## Salary Expectation

* Negotiable

## REQUIREMENTS
* Minium 2 – 5 years of System Administrator experience or similar role.
* Strong experience in infrastructure.
* Experience in managing the wide area network (Wan), company’s servers located at data
center.
* Experience in working with Ubuntu Server, Ubuntu operating systems, Desktop, Linux Mint
* Experience in monitoring daily network activity, data backup, system configuration backup
periodically.
* Essential knowledge in Development tools (SVN, Jenkins, Jira, Deployment) is preferred
* Knowledge in DevOps and Automation principle is desirable.
* Proficiency managing web (e.g. Apache, Nginx, Tomcat) and database (e.g. PostgreSQL)
servers.
* Experience with configuration management systems (Ansible, Chef, Puppet, Saltstack).

### KEY RESPONSIBILITIES

* Work closely with the developers to help them solve tricky problems in a production
environment: scale, performance, security.
* Develop and maintain scripts to automate system deployment to scale infrastructure
* Help setup multiple environments for development, testing, staging and production purposes
* Make sure a system is production-ready.
* Optimize existing systems to make sure they are cost-effective

### Why it would be awesome to work with us
* Dynamic, young, friendly, flexible environment
* Laptop is provided
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding
* Free fruits/ cakes on happy hours time
* Celebration: birthday
* Party time: Team building, Xmas, New Year,…
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development

### Contact
Email: oanh.tang@dinovative.com
Skype: tangoanh
Zalo: 0909617173
[[Dinovative] Devops Engineer JD.pdf](https://github.com/awesome-jobs/vietnam/files/6048657/Dinovative.Devops.Engineer.JD.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
