### ISSUE TITLE
Butterfly Hub - iOS Developer - HCMC - FT

### ISSUE THREAD

**Issue by lamnguyen01** [awesome-jobs/vietnam#230]
### Introduction

Butterfly Hub is now seeking for an iOS Developer who thrives to solve problems using intelligent big data system. You will be a part of an agile and dynamic startup crew that collectively changes the world through innovative technologies.  At Butterfly Hub, we create and iterate through rapid processes to unveil the beauty of human and make it better.  We turn caterpillars into butterflies as we create the best environment to foster your talent.  
### Location
- 35 Hoa Hong Street, Phu Nhuan District, HCMC, Vietnam  
### Benefits
-  Up to 1000 USD/ month (negotiable)
-  Be a part of a global startup based in US and Vietnam.
-  Have a chance to tackle computer vision, big data and artificial intelligence with experts and leaders from Vietnam and the world.
-  Idea consulting, logical training from CEO and Vietnamese alumni of MIT.
-  Free lunch and coffee.
-  Competitive salary.
### What You Will Do
-  Design and build an advanced application in iOS platform.
-  Collaborate with creative and design crew to release new features.
-  Build exquisite UI and UX applications.
-  Fix bugs and enhance applications.
### Requirements
-  Bachelor Degree in Software Engineer or Computer Science
-  At least one-year experience in iOS.
-  Experience in Swift and Core Animation is preferred.
-  Good critical thinking and communication skills are preferred.
-  Dare to dream on.
### How To Apply
-  Please kindly send your CV to lam.nguyen@butterflyhub.com with the subject as follows [Your name]_[Position].
### About The Company

Butterfly Hub is a fast-paced technology startup located in US and Vietnam. Our mission is to tackle the world of beauty and cosmetics through the most advanced technology. We change the way human makes beauty related decisions by providing them accurate analysis and user feedback information. Our product aims to become the number-one source of unified, personalized and intelligent information on beauty in US, Korea, Japan and Vietnam.

At Butterfly Hub Vietnam, we focus on human-centered development. We bring the world class professionalism to develop people and help them become better every day. We thrive to be dynamic and creative, in conjunction with strong bonds among colleagues, and embrace individual diversity.

More details at www.butterflyhub.com

**Comment by joneslee85** [comment]
@lamnguyen01 please revise the title, it misses few important details

Please also change the title to be captilised title instead of all bold and uppercase like now.

Cheers

**Comment by lamnguyen01** [comment]
@joneslee85 

I've just changed the titles into correct format. 

Can you specify what details I missed so that I can add on.

Cheers

**Comment by joneslee85** [comment]
You missed the `FT` at the tail

**Comment by lamnguyen01** [comment]
@joneslee85  I've already added FT at the tail. 
Thank you very much!

**Comment by dlpigpen** [comment]
Do we have any remote position?

**Comment by lamnguyen01** [comment]
@dlpigpen Temporarily, remote working is fine. In case you need help to move on to HCM, please let us know and we can handle all of it. 

Keep up with me through lam.nguyen@butterflyhub.com.

Cheers.
