### ISSUE TITLE
Dinovative - React Native Developer - Dist 7 - FT 

### ISSUE THREAD

**Issue by Oanhttk** [awesome-jobs/vietnam#2300]
## Location

* 11 D1 Tan Hung Ward, District 7

## Salary Expectation

* $700 - $1200

## REQUIREMENTS
* Minimum 1-3 year commercial experience in mobile app development with React Native
* Good working experience in using JavaScript, HTML5, CSS
* Strong working experience and best practices with React Native libs, React Component, Firebase, Redux 
* Good working experience in optimizing the performance of Mobile App (memory usage, memory leak, cache, …)
* Good knowledge in RESTful API
* Experience with ReactJS or NodeJS is a plus
* Experience with iOS/Android native app development is a plus
* Proficient understanding of code version control tools, such as Git, SVN
* Strong analytical and problem solving abilities
* Strong communication and client facing skills

### KEY RESPONSIBILITIES
* Front-end Mobile Web development (HTML5, CSS3, React Native, integration with RESTful Web API)
* Maintain existing software
* Constantly learn and keep abreast of emerging technologies
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Critique software designs and architectures
* Peer review colleagues code and identify areas for improvement
* Provide development task effort estimates
* Conduct client requirements gathering and analysis
* Review test plans
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### You can bring
Collaborating with UX & UI designers, researchers and other engineers (web & mobile), you will have the ability to flex your full stack chops to help shape, design and build digital products that help solve key business needs

### Why it would be awesome to work with us
* Dynamic, young, friendly, flexible environment
* Laptop is provided
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding
* Free fruits/ cakes on happy hours time
* Celebration: birthday
* Party time: Team building, Xmas, New Year,…
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development

### Interesting engineering projects
* Dinovative is looking for React Native Developer who is excited to work alongside a talented group of innovators to craft digital products. Being part of the conversation from the start, you will be expected to lead full lifecycle webbased projects including guiding technical scoping, design and implementation.

### Contact
Email: oanh.tang@dinovative.com
Skype: tangoanh
Zalo: 0909617173
[[Dinovative] Frontend developer JD (React Native).pdf](https://github.com/awesome-jobs/vietnam/files/6048702/Dinovative.Frontend.developer.JD.React.Native.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
