### ISSUE TITLE
Anysense - PHP Developer (Junior/Middle) - HCM - FT

### ISSUE THREAD

**Issue by jackiedo91** [awesome-jobs/vietnam#2301]
## Location

* District 12, Saigon, Vietnam
* Fulltime

## Salary Expectation

* Junior 500 ~ 1000$/month (Net) ( < 1.5 years)
* Middle 1000 ~ 1500$/month (Net)  ( > 1.5 years)

## Requirements
* At least 1 year of experience using PHP with any frameworks: **Laravel**, Symfony, Magento ...
* Knowledge in working with HTML/CSS/JavaScript.
* You are well versed in best practices in OOP, design patterns, SOLID principles.
* Familiar with MySQL/PostgreSQL design database, solve performance issues .
* Can communicate in English (Reading and Writing).
* Can communicate in Japanese is a plus.

### Responsibilities

- Work with Vietnamese and Japanese team to design, build, and maintain PHP Projects.
- Constantly learn and keep abreast of emerging technologies.

### Why it would be awesome to work with us
* We are about to set up a brand new office in Ho Chi Minh city. You will have a long term career path with many great opportunities promoted to be a leader.
* Macbook is provided.
* Dynamic, young, friendly, flexible environment.
* 13th – month salary.

### Contact
Email: dh.huy@anysense.co.jp / huydo91@outlook.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
