### ISSUE TITLE
Anysense - Mobile Developer iOS/Android/Flutter (Middle) - HCM - FT

### ISSUE THREAD

**Issue by jackiedo91** [awesome-jobs/vietnam#2303]
## Location

* District 12, Saigon, Vietnam
* Fulltime

## Salary Expectation

* 1000 ~ 1500$/month (Net)  ( > 1.5 years)

## Requirements
* At least 1.5 year of experience with iOS/Android/Flutter
* Knowledge: 
  * Programming languages: Swift (iOS) / Java/Kotlin (Android) / Dart (Flutter)
  * Application development: Application Lifecycle, basic UI elements & layout, basic animation technique.
  * Concurrency: Thread, Handler, Async Tasks, Memory optimization and scheduling technique.
  * Database: SQLite, ORMLite ...
  * Familiar with RESTful api.
  * Follow best practices using design patterns, DRY, SOLID.
* Can communicate in English (Reading and Writing).
* Can communicate in Japanese is a plus.

### Responsibilities
- Design and build advanced applications for the Android 
- Work with Vietnamese and Japanese team to design, build, and maintain mobile applications.
- Constantly learn and keep abreast of emerging technologies.

### Why it would be awesome to work with us
* We are about to set up a brand new office in Ho Chi Minh city. You will have a long term career path with many great opportunities promoted to be leader.
* Macbook is provided.
* Dynamic, young, friendly, flexible environment.
* 13th – month salary.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
