### ISSUE TITLE
Jio Health - Senior Java Backend Developer - HCMC - FT

### ISSUE THREAD

**Issue by phapli** [awesome-jobs/vietnam#2306]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Who are you?

* You are a RESPONSIBLE person who takes his/her promises to their heart.
* You are a GO-GETTER: you are unafraid to go beyond roles and titles to get great work done, able to spot what is missing, * initiate solutions, and connect people naturally.
* You are PASSIONATE, CURIOUS and OPEN to candid feedbacks about your performance and seek any constructive real-time points as a great way to grow.
* You are a DOER who thrives in a fast-paced and collaborative environment and demonstrate strong judgment and a solution-driven mindset. Multi-tasker, but with clear time management and prioritization skills.
* You LOVE DOING GOOD DEEDS to the society and people around you, being kind is your priority in general

## You’ll be responsible for

* Develop new features for our products and backoffice systems.
* Maintain and enhance existing systems.
* Integrate with third party systems.
* Work in close contact with non-technical staff to gather and clarify requirements.
* Define and suggest possible solutions based on those requirements.
* Implement, deploy, and monitor those solutions.

## Skills/Qualifications

* At least 3 years of experience with backend programming using Java, in particular Spring Boot and
JBDC.
* Very good SQL knowledge; preferably about MySQL.
* Experience with AWS and Linux is a plus.
* Experience with other languages, especially Python or PHP, is a plus.
* Experience with current issue tracking systems and code repositories required

## What we can offer

* Attractive salary
* Social insurance, health insurance, unemployment insurance according to Labor Laws
* Professional, dynamic working environment
* Macbook Pro

## About the company

Jio Health is an ambitious, fast-growing healthcare technology company, founded in California - USA, and established in Ho Chi Minh city - Vietnam.

At Jio Health, we believe that everyone should be able to gain instant access to trusted, affordable, and convenient healthcare services, no matter who they are and where they are. With that holding principle, we’ve been rethinking everything-healthcare-related from an user’s point of view, from appointments to prescriptions, ever since.

In the past briefed 1.5 year, our team has been building an intuitive Integrated Healthcare Platform connecting licensed doctors, pharmacists, lab services to patients and those in need. As the business grows, we’re looking for bright, energetic, entrepreneurial minds to join us in the mission of making quality healthcare universally accessible and affordable.

## Contact
Homepage: https://jiohealth.com
Tin Tran: tin.tran@jiohealth.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
