### ISSUE TITLE
Parcel Perform - Front-end Engineer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#2308]
![Vietnam](https://user-images.githubusercontent.com/49466111/109776226-f0800f00-7c34-11eb-9089-0b388be4eb71.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - 3,000 Gross

## Requirements
* Be responsible with task and be open to discuss, give questions to build up products with high quality and rich front-end experiences for our users.
* Understand clearly about object-oriented programming and design pattern.
* Willing to learn and research new technology or jump out of your comfort zone.
* Passionate about quality and the design of the code, productivity of the work and maintainability of the end result.
* An inspirational team player and always ready to take a leading role to successfully deliver team outcomes.

## Skills
* Front-end software development experience in Reactjs, or similar platforms.
* Have strong knowledge in ES5/ES6.
* Experience at one or more CSS compiler (LESS/SASS/PostCSS)
* Proficient in code review, code refactoring, Unit Testing
* Prefer for additional skills
-- Bundle code with Webpack/Browserify
-- AMP-HTML
-- Progressive web app (PWA)
-- Implementing a ChatBot
-- RxJS/Reactive programming

### Must Have
* Experience in ReactJs

### Responsibilities

As a frontend engineer, you will be building the interfaces to interact with Parcel Perform system. Our goal has always been to create a seamless experience between human and computer. And because of that, we continuously incorporate the latest advancement in web technologies and expand the scope of user interface. Some of the latest additions are conversational UI, Progressive Web App, and Accelerated Mobile Page.

Such complexity can be hard, especially with a focus on good engineering practices. But that is ok. We aren’t here for ease anyway. We are here for people who want to operate at the next level in their career.

### Why it would be awesome to work with us
* The opportunity to work in a fast-growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry. You will be the needle of success on the growth of a global product that will become a key platform behind successful e-commerce logistics worldwide.
* The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
* An environment where everybody never stops growing and focuses on succeeding - we continuously work with you on your strengths and weaknesses across many important dimensions and look at ways for you to address them and further your development.
* Your entry ticket into being part of the Parcel Perform journey, where you will work with and alongside people from around the world that share the same passion and dedication.
* All the usual perks you’d expect from a fast-growing company like competitive salary, flexible working time, unlimited leaves, extra insurance, free lunch, free fruit, snacks, open space, team bonding events, various training programs, and more.

### Interesting engineering projects
* [Parcel Perform partnered up with AWS in building ML models to leverage post-purchase experience.](https://www.youtube.com/watch?v=mzUi4wSgbGs)
* [Parcel Perform-powered order tracking pages serve a wide variety of customers, some of them ships coffee capsules all over the world!](https://www.nespresso.com/au/en/track-your-order)
* [Parcel Perform Logistics Intelligence provides an overview of customer's logistics pipeline and gives out concrete actionable items.](https://iprice.my/trends/insights/how-malaysias-delivery-industry-counters-covid-19-pressure/)

### Contact
Find more jobs and apply on https://www.parcelperform.com/careers
Or drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)

![PP-Join-our-team-email-banner](https://user-images.githubusercontent.com/49466111/109784058-45278800-7c3d-11eb-9ebd-fc70f35df70b.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
