### ISSUE TITLE
SpiderboxDesign - .Net Developer - District 3, HCMC - FT

### ISSUE THREAD

**Issue by oclockvn** [awesome-jobs/vietnam#2309]
### ⭐⭐⭐⭐⭐Vietnamese notes at the end

---

## Location

* District 3, HCMC, Vietnam (we're going to relocate to District 2 in May)

## Salary Expectation

* USD 1k - 1.5k

## Requirements
* c#
* reactjs
* git
* english (able to chat)

## Skills
* no need any special skills

### Must Have
* honest
* open mind

### Ideally
* fullstack .net
* good at js
* experience with azure services or any cloud services

### Responsibilities
* don't worry about anything, you will be received helps

### You’ll be responsible for
* adding features/fixing small bugs or just simple to help everyone else

### You can bring
* a friendly working environment

### Why it would be awesome to work with us
* nothing specials, we're small but cool, we're skillful but kind, we're young but honest and respect everybody

### Contact
email: quang@spiderbox.design

---

(Hy vọng note này sẽ được admin chấp thuận vì khả năng diễn đạt tiếng Anh của mình không đủ để thể hiện những gì mình muốn nói)

Okay, tình hình là mình đang tuyển thêm thành viên cho 1 dự án đã hoạt động được 1 thời gian dài. Các yêu cầu thì như mình nêu ở trên, chỉ cần khoảng 2 năm kinh nghiệm ở .net, biết js (tự tin ở js thì tốt, proj dùng reactjs), có chút vốn liếng tiếng Anh thì ok.

Vấn đề là bữa giờ mình cũng phỏng vấn khá nhiều rồi, quan điểm của mình là bạn có thể không cần phải giỏi hoặc biết sâu về chuyện gì, miễn là bạn **trung thực, thẳng thẳng, không ngại học hỏi** thì mình đánh giá cao hơn là bạn biết sâu nhưng hay chém gió này nọ. Chính vì vậy nên tới giờ cũng chưa tuyển đủ vì không hiểu sao tình hình ae giờ biết thì không bao nhiêu mà chém gió thì vô đối.

Nếu bạn là người thân thiện, suy nghĩ chín chắn, thấu đáo, hòa đồng, ham học hỏi, gửi cv cho mình ở email trên, phỏng vấn nhẹ nhàng tình cảm, đi làm sớm. Nếu bạn chỉ muốn thử vì lương lậu thì xin đừng làm tốn thời gian của nhau. Thanks ae.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
