### ISSUE TITLE
Merchize - DevOps/SRE Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by kangkong1** [awesome-jobs/vietnam#2310]
## Location

* Hanoi, Vietnam
* Fulltime

## Benefit

* up to $2000/month
* 13th month salary
* Performance review 2 times per year
* and monthly KPI, anually bonus
* Creative, Open, Productive working environment
* Free drinking
* and so on...

## Requirements
* 3+ years DevOps or SRE experience
* Kubernetes and microservices arch
* AWS or GCP
* Ability to fix the production issues, network issues and security issues.
* Alert and incident system
* Linux, Docker
* CI/CD tools
* Automate the leg-work with Python/Bash or a similar tool
* Would love to learn and work with enterprise cloud provider

### Ideally

* Familiar with NoSQL as MongoDB
* Familiar with NodeJS
* Linux/UNIX

### Responsibilities

Great power comes with great responsibilities!

* Build the tool and solution to optimize the security and productivity of the infrastructure.
* Ready for the issue, incident to resolve and find the root cause.

### Contact
Homepage: https://merchize.com/
Trollman: gate@foobla.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
