### ISSUE TITLE
Senior Data Architect in Ho Chi Minh City

### ISSUE THREAD

**Issue by gergana-pl** [awesome-jobs/vietnam#2312]
## Location

* Ho Chi Minh City, Vietnam
* Remote

## Requirements

- SQL as fluent as your mother tongue
- Able to architect, design complex data warehouses
- Able to pick the right data modelling technique for the given use case
- Fully understand the details of the data modelling techniques: Kimball, Data Vault
- Data Warehousing: Snowflake,BigQuery, Redshift, Greenplum, Oracle, DB2 or similar
- Relational Databases: Oracle, PostgreSQL, MySQL, Microsoft or similar
- NoSQL Databases: MongoDB (Atlas), Cassandra, DynamoDB or similar
- OS: Linux, MacOS
- Version Control: Git

### Responsibilities

We are looking for a Data Architect to work on diverse and challenging projects. Here, you will be involved in everything from writing custom code for data pipelines (batch and streaming) to using ETL/ELT tools, architecting, designing and implementing data warehouse models (SQL, dbt, Dataform).

### Interesting engineering projects

We have clients in tens of industries, including

- Edtech
- Healthtech
- Adtech
- NGO
- Fintech
- Entertainment
- D2C

### Contact
Apply here: [https://infinitelambda.com/post/career/data-architect/](https://infinitelambda.com/post/career/data-architect/)
Linkedin: [https://www.linkedin.com/company/infinite-lambda/ ](https://www.linkedin.com/company/infinite-lambda/ )

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
