### ISSUE TITLE
Senior BI Engineer @ Ho Chi Minh City

### ISSUE THREAD

**Issue by gergana-pl** [awesome-jobs/vietnam#2313]
## Location

* Ho Chi Minh City, Vietnam
* Remote

## Requirements

- Fluent SQL skills
- Looker (or other BI tools: Tableau Software / Qlik / Power BI)
- ELT process
- Data modelling
- Version control: Git
- Experience with OOP (Python, Java or web development)

### Responsibilities

Our BI Engineers turn vast amounts of data into insightful, easy-to-use, automated business intelligence reports. They work closely with both the internal team of engineers and our partners’ projects teams to deliver reports that empower business owners to make better and more informed decisions.

### Why it would be awesome to work with us

- Private health insurance
- Extensive training
- Working your local hours
- Flexible hours and location
- Inclusive culture

###Interesting engineering projects
We have clients in tens of industries, including

- Edtech
- Healthtech
- Adtech
- NGO
- Fintech
- Entertainment
- D2C

###Contact
Apply here: https://infinitelambda.com/post/career/data-architect/
Linkedin: https://www.linkedin.com/company/infinite-lambda/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
