### ISSUE TITLE
IndustraCom - Full-Stack .Net Engineer - Remote/Vietnam - FT

### ISSUE THREAD

**Issue by JeremyNathan933** [awesome-jobs/vietnam#2316]
## Location
 
* Remote, Vietnam
 
## Salary Expectation
 
* $1300 to $2500 /month (USD)
 
## Requirements
 
* 2+ years using the microsoft stack (C#, .NET, MVC, Web API, ASP.NET Core)
* Database Coding, Reports & Queries (SQL)
* CSS /SCSS, HTML5
* JavaScript Frameworks / Libraries (JQuery, VueJS)
 
### Must Have
 
* Amazing english - written and verbal
* Confident and mature
* True full-stack: Able to display lots of accessible web facing work you have done
 
### You’ll be responsible for
 
* Building new features and applications
* Optimization and bug fixing
 
### You can bring
 
* A good eye for detail
* Strong personal organization and efficiency
* Confidence and passion
 
### Why it would be awesome to work with us
 
* Join a fast-growing Australian tech company with an amazing culture and strong values
* Get supported within a nurturing team environment
* Be heard - Influence product performance and strategy
 
### Contact
Homepage: Industracom.com
Jeremy: jeremy_at_industracom_dot_com (+61 414 570 501)
![Industracom](https://user-images.githubusercontent.com/80295206/110398721-83eb9100-80c8-11eb-8e5f-fefba1601d81.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
