### ISSUE TITLE
Shopee VN - Middle/Senior Backend (Python/Golang)

### ISSUE THREAD

**Issue by ndkhaivn** [awesome-jobs/vietnam#2317]
## Location

* Saigon, Vietnam

## Salary Expectation

* ~$2000++/month (USD gross)

## Requirements
* Bachelor's degree or higher in Computer Science or related fields.
* At least 2 years of server-side programming (Experienced level)
* Passionate about coding and programming, innovation, and solving challenging problems
* Strong Knowledge & experience in algorithms ; Operation System & Memory Control
* In-depth understanding of computer science fundamentals (data structures and algorithms, operating systems, networks, databases, etc)
* Familiar with one of the programming languages including Go, Python, C++ and Java; hands-on experience is preferred
* Familiar with common network protocols (TCP, UDP, HTTP) and network programming
* Familiar with Linux development environments and multi-threaded programming

### Ideally
* Experience in web technologies and security is preferred
* Experience in design and development of large-scale distributed systems is preferred

### You’ll be responsible for
* Server side design and development of the services / systems / platforms used by our products and our users
* Write high-quality, clean, simple, and maintainable code; build common libraries
* Analyze requirements, design and develop functionalities based on the product requirements
* Understand the product thoroughly, constantly optimize the product, identify and fix problems, improve stability and user experience
* Design and implement various supporting tools as required
* Collaborate with other software engineers, product managers, user experience designers, and operations engineers to build the product

### Contact
Github: @ndkhaivn
Email: ndkhaivn@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
