### ISSUE TITLE
Shopee VN - Jr/DevOps Engineer (Google Cloud, Linux)

### ISSUE THREAD

**Issue by ndkhaivn** [awesome-jobs/vietnam#2318]
## Location

* Saigon, Vietnam

## Salary Expectation

* ~$1000/month (USD)

### Must Have
* At least 1 year experience as a DevOps Engineer or similar software engineering roles
* Experience with configuration and deployment management tools
* Experience in a public facing high-traffic environment
* Understanding of Linux / Unix system & command line interface

### Ideally
* Good knowledge of Go/Python
* Working knowledge of databases and SQL
* In-depth experience of Google Cloud Platform
* Google Cloud certification is a plus
* Problem-solving attitude
* Team spirit
* Google Cloud Platform
* Linux / Unix OS
* Knowledge of network & security
* Coding and Shell scripting
* Database tuning & debugging
* Understanding of Major DevOps Tools: Ansible, Docker, Kubernetes, Puppet, Chef, GitLab, Istio, ELK, Jenkins, CI/CD tool....

### Responsibilities

* Deploy source codes to Google Cloud, identifying production issues.
* Deploy and coordinate releases to Production and/or Staging environments
* Manage release cycle & processes
* Implement policies for facilitating release processes
* Track progress of released features
* Track performance of released features
* Coordinate on release issues
* Manage the versions of control system
* Experience with GKE (Google Cloud Kubernetes Engine)
* Support MySQL databases
* Perform migration for systems and databases
* Assists developers with software development and deployment procedures
* Running tests
* Perform root cause analysis for production errors

### Contact
Github: @ndkhaivn
Email: ndkhaivn@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
