### ISSUE TITLE
U.S. company looking for freelancer - NodeJS, VueJS, ReactJS

### ISSUE THREAD

**Issue by PrimeTimeTran** [awesome-jobs/vietnam#2319]
## Location

* Can be remote
* Preferred those in Saigon.

## Salary Expectation

* $1000/month + bonus(percentage of total value of project)

## Requirements
* VueJS or ReactJS
* NodeJS, SQL, Sequelize, MongoDB, Mongoose
* 5+ years Software Engineering experience

### Must Have

* Flexible 
* Committed
* Professional experience using React or Vue & SQL or MongoDB.

### Ideally

* Experience with all the stacks above.

### Responsibilities

Delivering project features & requirements in a timely and professional manner.

### You’ll be responsible for

* Working on a project from the U.S. which can help save lives.

![demo](https://user-images.githubusercontent.com/16382165/110462918-e1e99a00-8103-11eb-8a8f-60cd2fcbb782.gif)

### You can bring

* A good eyes for design
* A good analysis skill
* Ability to think on your feet
* Willingness to work independently without handholding

### Why it would be awesome to work with us

Because we have many more projects in the pipeline & we're willing to pay more than market rate(percentage of total value of the project) for someone who can work independently and hard so that we all win together. 

### Contact
Please email at 
email: datloiboi@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
