### ISSUE TITLE
NIC HR - Ruby on Rail Developer - Hanoi / Remote - FT

### ISSUE THREAD

**Issue by phuoctuan** [awesome-jobs/vietnam#232]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* $600-900/month or negotiable

## Requirements
* At least 1-2 years experiences in Ruby on Rails Framework
* BS degree in Computer Science, Engineering or a related subject
* Experience with HTML, CSS, JavaScript
* Experience of working with MySQL
* Significant knowledge with MVC, OOP
* Skillful in using source code management system especially GIT
* Able to work in Linux or having will to learn it

## Skills
* Strong analytical and problem solving skills along with balance to be cooperative with us to do it
* English (both reading and writing)
* High engergy, proactive and high responsibility in working
* Able to feel fun to work with Japanese

### You’ll be responsible for
* Develop web application with Ruby on Rails while understanding spec sometimes from simple document, sometimes from explanation of Japanese person in English and sometimes analyzing by yourself from insufficient spec by discussion 
* Collaborate with Japan side frequently and effectively while considering situation on both side
* Improve yourself and learn more and more as long as we will provide opportunity

### Contact
* Phuoc Tuan: tuannp@nicvn.com 
* Mobile phone: 0938634015 or +84 8 3824 4988 (ext:230)
* Skype: phuoctuan173

**Comment by hieuk09** [comment]
Hi @phuoctuan, your job post is not comply with the guide, could you please update it?

**Comment by joneslee85** [comment]
@phuoctuan please check the bulletpoint formatting of markdown

**Comment by phuoctuan** [comment]
I fixed, but i am not sure that is right., not is. please help me show retail of my error.  Thanks a lot.

**Comment by joneslee85** [comment]
@phuoctuan please fix up the *Contact* section by splitting one line into multi-line

**Comment by phuoctuan** [comment]
@joneslee85 Thanks so much for your time and supporting. that is the very first time i post on this. wish u a happy day.

**Comment by hieuk09** [comment]
Hi Tuan,

I took a look at your company and believe this job post is for another company. As we don't accept job post from agency, I'm sorry that we have to close this PR. 

Thank you for your time to post on our board. If you have any jobs post for your OWN company, please feel free to post it here.
