### ISSUE TITLE
Rikkeisoft - Developer (All Levels - English Speaking) - Java/etc -  @ HaNoi City

### ISSUE THREAD

**Issue by hungnguyen-rikkeisoft** [awesome-jobs/vietnam#2320]
## Job briefs
* Work with customers from Europe - America, Japan, and Vietnam (Candidates can choose the market)
* Developing features of products according to customer requirements
* Work, teamwork coordination under the assignment of project management.
* Research requirements, learn technology related to the project

## Location

* HaNoi, Vietnam

## Salary Expectation

* Up to $2,600 USD

## Requirements 
* Graduated from College / university in Information Technology or other related major
* Experience programming for 1 year or more in HTML / CSS / Javascript.
* Have experience in real projects or in school with 1 of the languages NodeJS, ReactJS, Angular, VueJS, iOS, Android, .NET, PHP, Java, Python, ...
* Reading specialized English documents (preferably being able to communicate in English)
* Have knowledge of object oriented programming.
* Be careful, patient and ready to learn new technologies
* Have skills in analyzing and solving problems.
* Ability to work independently and in groups
* Recruit all levels (Fresher, Junior, Middle, Senior)

### Why it would be awesome to work with us
* Salary: Minimum of 13 salary months / year. Consideration for salary increase 2 times / year.
* BONUS: Tet bonus, project bonus, holiday bonus, HR recommendation bonus...
* Join a free Japanese class taught by a native teacher.
* Monthly allowance if you have Japanese certification (N1: 5 million VND, N2: 3 million VND, N3: 1 million VND). Soon we will have this policy for English certification as well.
* Seniority allowance (working time from 2 years or more).
* 5 official working days per week, 1 day off / month. Participate in the weekly Saturday vocational training activity with lunch support and allowance.
* Saturday, Sunday + 12 days off per year (maximum 20 days off per year, any exceeded days off will be paid 500,000 VND / day).
* Clubs and many cultural - sport - art activities sponsored or supported by the company (For example: football, table tennis, badminton, swimming, music, English, games... )
* Ensure health: Periodic health check, support to buy high quality health insurance...
* Join the Rikkei Care Health Plan.
* Spiritual comfort: Play music on demand every day, fresh fruit, integrated teambuilding activities and Travel.
* Opportunity to go to Japan to work and travel everywhere.

### Contact
Mobile: (+84) 974 04 9763
Email: hungnv_tt@rikkeisoft.com 
Skype: Nguyen Viet Hung / live:.cid.fb1f1c6294f8415a

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
