### ISSUE TITLE
Okxe - iOS Technical Leader - Hanoi - FT

### ISSUE THREAD

**Issue by anniebui3010** [awesome-jobs/vietnam#2321]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $2000/month 

## Requirements
* 5+ years’ iOS development experience
* Proficient in Swift.
* Extensive experience with iOS Frameworks such as Core Data and Core Animation.
* Proficient in code versioning tools including Mercurial, Git, and SVN.
* Basic English Communication skills are required.

### Responsibilities

* We are looking to hire a talented iOS Technical Leader to design, build, and maintain the next generation of iOS applications, and lead the iOS team.

* To ensure success as an iOS Technical Leader, you should have a strong working knowledge of iOS Frameworks, be proficient in Swift, and be able to lead the iOS team. Ultimately, an outstanding iOS Technical Leader should be able to design architecture of programming and communicate well with not only your team but also other teams.

### Contact
Homepage: https://www.okxe.vn/
Email: p.anhbui@okxe.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
