### ISSUE TITLE
Fonos - Backend Lead (NodeJS, AWS) - D7 Saigon - FT

### ISSUE THREAD

**Issue by oscarjes** [awesome-jobs/vietnam#2322]
## Location

* D7 Saigon, Vietnam

## Salary Expectation

* $1800/month and up depending on experience

## Your Role

You'll be the lead backend & devops developer on our team and work directly with the CEO/CTO. You'll help us build out the tech team as we grow and you'll be directly responsible for the developers we hire in the future to work under you. We're looking for someone that has already worked in positions as a team & project leader and is now ready to take on the challenge of building a tech team from scratch at a high-growth startup.

At Fonos, we're building the leading audiobook & audio content app for Vietnam and your technical know-how will be key in helping us reach that goal. We have tens of thousands of passionate users who care deeply about our product. You won't just contribute by building new features but also by optimizing existing systems, improving performance, and deal with technical debt.

This is a role for someone who enjoys the challenge of both setting up new systems and optimizing and scaling existing ones. You'll have a diverse set of challenges to tackle every day: whether it's dealing with AWS, fixing issues with Apple IAP, or improving app performance.

### Our tech stack

* NodeJS & Postgres backend
* ReactJS websites
* React Native apps for iOS and Android
* AWS & local server and DNS solutions

### Who you are
_This role might be for you if..._

* **You love taking on new challenges.** Life at an early stage startup can be chaotic and require you to tackle different kinds of problems each week. You thrive in such an environment and enjoy getting to deal with new challenges.
* **You want to develop your leadership skills.** You'll work directly with our CEO to build out the developer team at Fonos. You'll have a chance to develop and improve your leadership abilities.
* **Both your written & spoken English are very good.** You'll be working directly with our CEO, who doesn't speak Vietnamese, so it's important for you two to be able to communicate well.
* **You're hard working.** We're an early stage startup and everyone on our team has to pull their weight. We move quickly and need team members who are able to keep up.

## Requirements

* Proven 5+ years as a backend developer with at least 3 years' commercial experience in developing backend code using NodeJS
* 3+ years of experience deploying products with large active user numbers on AWS
* Worked in positions as a team & project leader with other developers reporting to you
* (Bonus) Some experience writing ReactJS code, ideally also some experience with React Native
* Experience building and deploying production-ready backends for mobile apps
* Strong communication skills and a good command of written and spoken English.
* Experience working with App Store Connect and Google Play Store (especially IAP)
* Familiar with implementing mobile platforms' basic features, such as location services, push notifications, etc.

## What's in it for you

* **Exciting challenges.** You'll be our lead developer and you'll be able to help us take this startup from the early stage to a large successful tech company. You'll have a chance to show and develop your leadership and technical skills.
* **Career opportunities.** Being a lead developer at a high-growth startup will put you in a great position for your future, whether you decide to stay and grow with us as we keep scaling, start your own project or work at a large company.
* **You'll be able to contribute.** You'll be a key employee at Fonos and you'll be able to contribute to the direction of business in many ways, not just when it comes to technical aspects.

## Benefits

* Competitive salary
* Office in HCMC D7
* Macbook for work
* Social insurance, medical insurance & unemployment insurance according to Vietnam Labor Law
* 13th-month salary and bonus based on performance

# Who we are

At Fonos, we're building the leading audiobook & audio content app for Vietnam. We partner with the largest book publishers in the country to create audio versions of best-selling local and international books. We're also creating original content such as meditations, sleep stories, book summaries, and more. We’re a small team of passionate individuals on a mission to make books & acquiring new knowledge more accessible to people in Vietnam.

Fonos is the leading audiobook app in Vietnam, has tens of thousands of users, and our company is backed by amazing local and international investors (such as [Thai Van Linh](https://www.facebook.com/linhthaiofficial) and investors from Silicon Valley).

### Fonos app & social

* [Fonos on iOS App Store](https://apps.apple.com/vn/app/fonos/id1491002000?l=vi)
* [Fonos on Google Play](https://play.google.com/store/apps/details?id=vn.fonos.mobile&hl=vi)
* [Website](http://fonos.vn/)
* [Facebook](https://www.facebook.com/fonosvietnam/) & [IG](http://instagram.com/fonosvietnam)

### Learn more

* [Watch this behind the scenes video to see how we record audiobooks](https://www.youtube.com/watch?v=7wjPMxaDQdk)
* [Watch the video JVevermind made about Fonos](https://www.youtube.com/watch?v=SoIpNVsPiNM)
* [See what Helly Tong says about our app](https://www.instagram.com/p/CFo1zY6H6Pw/)

### Contact
Homepage: fonos.vn
Oscar (CEO): oscar_at_fonos_dot_vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
