### ISSUE TITLE
FETCH TECHNOLOGY - FULLSTACK (.NET, REACT JS) - HCM - FT 

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2323]
![image](https://user-images.githubusercontent.com/60914247/110766938-49305700-8288-11eb-94e9-b74dfd3114a3.png)

## Requirements
* 1-year experience in dotNet, Entity Framework, React, Redux, Hook.
* Strong understanding of OOP and Clean Code.
* Experience in SQLServer databases and schema design.
* Experience in Javascript (ES6) & HTML / CSS.
* Understanding of RESTful APIs.
* Experience in Git.
* Experience with Infrastructure/DevOps is a plus.
* Strong command of English and good communication skills.
* Nice to have: CQRS, DDD pattern.

## Responsibilities

* Work together with client to get requirement.
* Build efficient, reusable components and high-quality front-end.
* Handling full-stack programming tasks for the development.
* Triage bugs and troubleshoot production issues.

## Why it would be awesome to work with us?
Being a Junior Full-stack Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
* With extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).

## WORKING TIME & LOCATION

* Working time: 9 AM - 6 PM from Monday to Friday.
* Location: 3rd Floor, BCONS TOWER 2 - 42/1 Ung Van Khiem Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

## Contact
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
