### ISSUE TITLE
FETCH TECHNOLOGY - Full-stack Web Developer (PHP Laravel/React) - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2325]
![image](https://user-images.githubusercontent.com/60914247/110771799-7f240a00-828d-11eb-92ff-a9ad3001e035.png)

## HCM

#  1200 - 2500 USD

## Requirements
* Experience (years): Senior Developer/3+ years experience. 
* PHP 2+ years of experience.
* Knowledge of front-end technologies like Javascript, Html, CSS...
* Have to experience with any PHP web frameworks (Laravel or Symfony or Zend) (Laravel preferred).
* Have experience with modern Javascript frameworks (React or Angular) (React preferred).
* Understand common design patterns, SOLID, DDD, Datamapper, Repository.
* Experience with Linux OS.
* Experience with REST API and API design.
* Experience with CMS.
* DevOps skill with AWS.
* Good understanding of SEO principles and ensuring that the application will adhere to them.
* Interest in and passion for the startup ecosystem.
* Interest in blockchain technology and its potential use cases. 

## Responsibilities
* End-to-end ownership of feature development.
* Ensure the technical feasibility of UI/UX designs.
* Building reusable code and libraries for future use.
* Optimization of the application for maximum speed and scalability.
* Design and implementation of data storage solutions.
* Collaborate with other team members and stakeholders.
* Great power comes with great responsibilities!

## Why it would be awesome to work with us?
* This is a unique opportunity to be part of a vibrant and exciting new company that has received positive traction in the blockchain space and has partnerships with top corporate firms such as IBM, Intel and BMW and technical protocols such as ConsenSys, R3 and VeChain. We work closely with a variety of stakeholders; startups, government agencies, technical protocols and corporate firms. 
* If you join us, you will have hands-on experience and ownership executing the company’s vision of building the blockchain ecosystem in Singapore. If you enjoy working with startups and building something new with us, be a part of us today. 
* Being a Senior Full-stack Web Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).  
## WORKING TIME & LOCATION
* Working time: 9 AM - 6 PM from Monday to Friday.
* Location: 3rd Floor, BCONS TOWER 2 - 42/1 Ung Van Khiem Street, Ward 25, Binh Thanh District, Ho Chi Minh City.
## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
