### ISSUE TITLE
Telio-Lead Engineer-HN/HCM-FT

### ISSUE THREAD

**Issue by thiendi1205** [awesome-jobs/vietnam#2327]
## Location

* Ha Noi, Vietnam
* Ho Chi Minh City, Viet Nam

## Salary Expectation

* $3000-$4000 (USD Gross)
## Requirements
* Minimum of 6 years of software development experience
* Strong expertise in designing complex frontend and backend applications using cutting edge technologies like **Kafka, MongoDB, Redis, ElasticSearch** etc.
* Strong expertise with both **SQL and NoSQL databases**
* Should be a polyglot and should have experience working with multiple technologies like **JavaScript, Go, Java, Kotlin, React/React Native, NodeJS** etc.
* Substantial **experience in building complex and high performance web scale systems using microservices**
* Strong object-oriented design skills, ability to apply design patterns, and an uncanny ability to design intuitive module and class-level interfaces
* The ability to do deep problem solving and build elegant, maintainable solutions to complex problems
* Experience leading multi-engineer projects and mentoring junior engineers
* Experience working with geographically distributed multi-cultural teams
* Experience working in fast paced agile environments or start-up companies
* Good to have knowledge of Android, Kotlin, Golang etc.
* Experience working in any cloud platform like AWS, Google cloud etc.
* Good to have prior knowledge of containers using  docker and Kubernetes. 

### Responsibilities
* Research, Design and Develop highly reliable, available and scalable web-scale distributed microservices based systems
* Lead by example, mentor and guide team members on everything from structured problem solving to development best practices
* Participate in deciding your team’s roadmap in collaboration with Management and Product teams
* Collaborate effectively with product managers towards building the right features
* Estimate and manage deliveries of features in a predictable manner
* Continuously contribute to improving our technology ecosystem, libraries, frameworks, utilities and services
* Collaborate, mentor and guide team members as needed

### You’ll be responsible for

* Building Vietnam’s largest B2B commerce platform

### Contact
Homepage: https://telio.talent.vn/
Email: trandung@telio.vn
Skype:dungtt.topcv
Zalo: 0934 583 094

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
