### ISSUE TITLE
RUBY ON RAILS DEVELOPER - WE NEED YOU NOW

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#233]
Location

* Saigon, Vietnam
* Remote

Requirements

I'm in urgent need of finding good RoR developers to form a team around the mobile app. 
- Graduated from College/ University specialized in Information Technology
- At least 2 years of experience as a Ruby on Rails developer
- Experienced in Ruby programming and Ruby on Rails framework
- Good at English

Last but not  least, you have a passion and enthusiasm to contribute to the development of a IT Outsourcing start-up company. Please do not hesitate to contact me.

Contact

Mai Ngo (Ms.)
Tel: 01243 894 915
Email: ngocmai2291@gmail.com
Skype: mai.ngo91

**Comment by huydx** [comment]
@RecruiterMaiNgo your post is invalid. And we think that you're not company's person. Please read guide [here](https://github.com/awesome-jobs/jobs). We will close within 2 days if there's no response

**Comment by huydx** [comment]
Because this post seems to violate deeply with our guide, so I decide to close it first, and will open later if got appropriate response

**Comment by RecruiterMaiNgo** [comment]
Hi Admin, 

Thanks for your reminder
Could you please help me to edit this post for this my very first time? As I am struggling with this posting :( For the next ones, I had experience so I will make it right easier.
Thank you so much for your help!!!

**Comment by hieuk09** [comment]
Hi Mai,

I believe we already have a very detail guide and template about how to write a valid job post. Please take your time to learn how to write following the guide. We're doing this for free, so we don't really have time to do other's job.

**Comment by RecruiterMaiNgo** [comment]
Okay, thanks. I understood from your side. Please help to close this ad for me. I will post another new one later. 
Once again, thanks for you time to support.
