### ISSUE TITLE
AEG - Fullstack Java Developer - Hanoi - FT

### ISSUE THREAD

**Issue by helen-bui** [awesome-jobs/vietnam#2336]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 20,000,000VND - 40,000,000VND

## Requirements
* HTML/CSS
* Spring Boot, Hibernate, Spring Data JPA, Spring Cloud
* PostgreSQL, Oracle
* 1-2 years Software Engineering experience

## Skills
* English: basically read and communicate

### Must Have

* Degree in Information Technology or Computer Science

### Ideally

* Experience with supplying REST APIs, SOAP
* Experience with SOA, Microservices
* Experience with CICD 

### Responsibilities

Join company's projects

### You’ll be responsible for

* Developing Software Products

### You can bring

* contribution to our team

### Why it would be awesome to work with us
Good salary Promotion chances, off 2 Saturday per month
### Contact 
For more information, feel free to contact
Linkedin: https://www.linkedin.com/in/helen-bui-08/
Email: huongbui2008.neu@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
