### ISSUE TITLE
HCMC  Fullstack NodeJS developer

### ISSUE THREAD

**Issue by Hoanguyen8895** [awesome-jobs/vietnam#2337]
## Location

* Saigon, Vietnam

## Salary Expectation
15.000.000 - 20.000.000 VND

## Job Description
 Design, build, and maintain efficient, reusable, and reliable Nodejs code. 
 Integration of data storage solutions. 
 Help maintain code quality, organization and automatization. 
 Constantly learn and keep abreast of emerging technologies. 
 Contribute to the software design processes including whiteboarding sessions, workshops 
and prototyping. 
 Critique software designs and architectures. 
 Peer review colleagues code and identifying areas for improvement. 
 Provide development task effort estimates. 
 Conduct client requirements gathering and analysis. 
 Review test plans. 
 Follow defined development best practice including commenting and documenting code, 
contribute to development wikis and using source control.

## JOB QUALIFICATIONS
 Minimum 1-3 year working experience with Nodejs. 
 Solid understanding of front-end technologies, such as JavaScript, HTML5, and CSS3. 
 Agile/Scrum development cycle understanding 
 Strong experience with RESTful APIs and WebSocket APIs. 
 Experience working with database system such as mySQL, MongoDB, NoSQL. 
 Solid understanding of object-oriented programming. 
 Understanding fundamental design principles behind a scalable application and microservice 
architecture. 
 Experience with the Express.js framework 
 Knowledge working closely with git 
 Experience in front-end development (Vuejs) is a big advantage. 
 Strong analytical and problem solving abilities. 
 Strong communication and client facing skills 

## BENEFITS
Come and work with us, you will have opportunity to learn new technologies with international 
standard, build products that are different/innovative and get various benefits: 
 Working time: Monday – Friday, 9:30 AM – 18:30 PM
 Dynamic, young, friendly, flexible environment 
 12+ days annual leaves, working Monday - Friday 
 Attractive salary based on skills and experiences 
 Salary review: Once a year, base on individual performance review 
 Performance bonus: Twice a year (every 6 months), base on individual performance, profit 
and company policy 
 Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding 
 Free fruits/ cakes on happy hour time 
 Celebration: birthday 
 Party time: Team building, Xmas, New Year…
 Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws 

### Contact
 Contact Person: 0768888843 (Mr Cong)
 Email: Agusdreamchaser@agugroup.vn
 Website agugroup.vn
 Link: https://www.facebook.com/agugroup.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
