### ISSUE TITLE
NIC HR - PHP developer - Hanoi - FT

### ISSUE THREAD

**Issue by phuoctuan** [awesome-jobs/vietnam#234]
## Location

* Hanoi, Vietnam

## Salary Expectation

* negotiable

## Requirements
* At least 6 months experience in Code-igniter framework
* BS degree in Computer Science, Engineering or a related subject
* Experience with HTML, CSS, JavaScript
* At least 1.5 year experience of working with MySQL
* Significant knowledge with MVC, OOP
* Skillful in using source code management system especially GIT
* Able to work in Linux or having will to learn it
* 5+ years Software Engineering experience

## Skills
* Strong analytical and problem solving skills along with balance to be cooperative with us to do it
* English (both reading and writing)
* High engergy, proactive and high responsibility in working
* Able to feel fun to work with Japanese

### You’ll be responsible for

* Develop web application with PHP while understanding spec sometimes from simple document written in English, sometimes from Vietnamese person, sometimes analyzing by yourself from insufficient spec by discussion 
* Collaborate with Japan side while considering situation on both side
* Improve yourself and learn more and more as long as we will provide opportunity

### Contact
* Phuoc Tuan: tuannp@nicvn.com 
* Mobile phone: 0938634015 or +84 8 3824 4988 (ext:230)
* Skype: phuoctuan173

**Comment by hieuk09** [comment]
Hi Tuan,

I took a look at your company and believe this job post is for another company. As we don't accept job post from agency, I'm sorry that we have to close this PR.

Thank you for your time to post on our board. If you have any jobs post for your OWN company, please feel free to post it here.

**Comment by phuoctuan** [comment]
Dear Mr. Hieu,
Thanks so much for your note. I sincerely appreciate your professional style on this. 
Regards.
