### ISSUE TITLE
Orange Logic - Technical Product Owner - Saigon - FT

### ISSUE THREAD

**Issue by hanguyenOL** [awesome-jobs/vietnam#2341]
## Location

* HCMC, Vietnam

## Salary Expectation

* $2500 - $5000/ Negotiate

## Requirements

* Proficiency with English, both verbal and written
* A strong fundamental understanding of software development, as well as a passion for intellectual challenges
* Significant experience as a Product Owner working on complex/large products developed in **quick implementation cycles**.
* Excels in understanding **business requirements**, turn them into **executable development plans** that technical teams fully endorse, and follow up through the execution
* UI UX sensibility appreciated

## Skills

* A solid problem-solving skill with well-practiced and consistent approach. You will have a chance to tackle any problem by breaking it down and solving it logically and systematically
* Practical experience on a web-based application is a plus
* **Technical background** is a big plus but not mandatory

### Must Have

* **Strong self-discipline** for collaborating with the dev team, on delivering well-tested, complete features/modules under a tight schedule, and the capability for rational thinking.

### You’ll be responsible for **the end to end implementation of product releases**

* Manage the (release) backlog  
_Clarify requirements with key stakeholders, document user stories,  set priorities and plan sprints_ 

* **Oversee the implementation progress**
_Support the teams to ensure both time & quality objectives are met (Troubleshooting, priorities management, testing…)_

* **Ensure deliverables meet the company quality standards**
_Conduct functional reviews before changes are delivered to users and help build the engineering culture_ 

As you get a better understanding of the product & the vision driving its development, you will gradually take a key role in the **global backlog management** and **weigh-in early on requirements** to ensure they fit in the global picture.

### Why it would be awesome to work with us

> At Orange Logic, it does not matter how many years of experience you have, or your age. We believe that each individual, regardless of these factors, has the ability to evoke change within the organization.

* Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development. 
* Amazing team: smart, open-mind, and passionate engineers. They came from the US, France, UK, and Vietnam hence you could improve your English and explore different country cultures.
* 18 days of annual leave (cashback for unused days) + 4 days for an abroad company trip (Taiwan, Thailand, etc)
* 13th-month salary
* Performance bonus (average $700/month in 2020)
* Monthly team outing activity
* Premium healthcare insurance ($10.000 cover) after probation
* Full Insurance based on your Gross salary
* Allowances for lunch, gym, parking ($100)
* Birthday bonus ($100), Tet gift, etc
* Daily free snacks, fresh fruit, coffee & soft drinks
* Latest gadgets for work (include noise-canceling headphones)

### Contact
* Please send your resume to ha.nguyen@orangelogic.com
* You can drop me a message on [Skype](https://join.skype.com/invite/mNKg28GbjKfr) or [Linkedin](https://www.linkedin.com/in/ha-nguyen-01a752ba/)
* [Our Homepage ](https://www.orangelogic.com/digital-asset-management-customer-examples)

> Can't wait to have a detailed discussion if you have any questions or concerns!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
