### ISSUE TITLE
Pod Foods Vietnam - Backend Developer (Ruby on Rails) - Hanoi - FT

### ISSUE THREAD

**Issue by podfoodsco** [awesome-jobs/vietnam#2342]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1000-$1500/negotiable

### Must Have

* 2+ years of experience with Ruby on Rails 
* Experience building API’s using RoR and building and scaling applications and components using AWS
* Proficient with GitHub
* A portfolio of projects utilizing the above skills
* Excellent communication and problem-solving skills
* Ability to self-manage, collaborate and be a team player
* BS degree in Computer Science or equivalent backgrounds

### What we expect from you

* Comfortable within a mature Rails codebase
* Design and implement robust, scalable and secure features
* Consider the performance impacts of your technical choices
* Participate in architectural decisions and refactors

### Why it would be awesome to work with us

> Pod Foods is a software enabled B2B food distributor focused on local
> and emerging brands. We are based in San Francisco, with operations in
> Chicago, New York and Los Angeles. We are a fast growing company
> backed by Silicon Valley venture capital firms. The team comes with
> decades of industry experience and our engineering team is based in
> Hanoi. This is a great opportunity to join us on our exciting growth
> throughout the rest of the United States.

### Benefits & Perks

* Competitive compensation based on experience
* Annual evaluation with salary and bonus reviews
* Flexible, self-managed paid time off
* Team outings and birthday celebrations
* Self-improvement courses can be requested
* Premium Life & Healthcare insurance
* Free parking
* The best team and working environment you’ll ever find!

### Contact

* Please send your resume to  [thiem@podfoods.co](mailto:thiem@podfoods.co) or text me: 0982 85 87 83 (Mr. Thiem)
* [Pod Foods Homepage](https://podfoods.co/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
