### ISSUE TITLE
Pandigita - Fullstack Developer React.js & Node.js - 100% Remote (Vietnam/World) - FT

### ISSUE THREAD

**Issue by pandigita** [awesome-jobs/vietnam#2343]
## A Job With Meaning

Join our international team immediately and remotely from any location in Vietnam.

We're work for a German NGO that offers free psychological counseling for poor people. Help us make people's lives better - be a hero!

We're working on several exciting SaaS web applications that we need your help for - a video conferencing platform, an eLearning platform and more.

## Location 

* 100% Remote - Vietnam, Worldwide
* OR optionally join us in person at our office in Hoi An (always, sometimes, or never - as you like)

## Salary Expectation

* $1500-$2000

## Requirements 

* Mid-level to senior-level: you code fast & you code high-quality
* Fullstack: you master all of the following:
* 2+ years experience React.js
* CSS & Responsive Design
* 2+ years experience in Node.js
* 1+ years experience in SQL: MySQL, PostGreS, MariaDB
* ideally DevOps experience: setting up a server to run Node.js apps
* Excellent working attitude, communication skills and critical thinking
* You have your own thoughts, opinions and you want a team that **listens** to your thoughts
* Good English

### Must Have

* 2+ years Node
* 2+ years React.js
* Be able to tell the difference between Java and JavaScript ;-)

### Ideally

* Experience with MariaDB
* DevOps experience

### Responsibilities

_Initially, you'll have the following responsibilities:_
* Continue developing video conferencing app that connects patient and psychological counsellor including:
* scheduling functionality
* user management
* implementing WebRTC BaaS (externally hosted video conferencing service)

_Long-term, there are many exciting projects we'll work on both for our client (the NGO) and SaaS products we offer ourselves_

### You can bring

* Attention to detail
* Your own opinion
* The confidence to tell your boss "maybe you're wrong"
* The confidence to tell your colleagues "maybe I'm wrong"

### Why it would be awesome to work with us 

* You're helping make the world a better place, by helping us reduce people's mental health issues
* 100% Remote
* 100% international team - high standards & growing together
* Awesome colleagues
    
### Interesting Engineering Projects
* WebRTC (open source video conferencing protocol) integration
* Smart services integration between SaaS offerings and organizations

### Contact (MUST)
Homepage: www.pandigita.com
Email: peoplepower@pandigita.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
