### ISSUE TITLE
Pandigita - Frontend Developer React.js - 100% Remote (Vietnam/World) - FT

### ISSUE THREAD

**Issue by pandigita** [awesome-jobs/vietnam#2344]
## A Job With Meaning

Join our international team immediately and remotely from any location in Vietnam.

We're work for a German NGO that offers free psychological counseling for poor people. Help us make people's lives better - be a hero!

We're working on several exciting SaaS web applications that we need your help for - first, we'll work on an eLearning platform.

## Location 

* 100% Remote - Vietnam, Worldwide
* OR optionally join us in person at our office in Hoi An (always, sometimes, or never - as you like)

## Salary Expectation

* $1300-$1800

## Requirements 

* Mid-level to senior-level: you code fast & you code high-quality
* 3+ years coding modern JavaScript (any framework)
* 2+ years experience coding only React.js
* experience with CSS & Responsive Design
* Excellent working attitude, communication skills and critical thinking
* You have your own thoughts, opinions and you want a team that **listens** to your thoughts
* Good English

### Must Have

* 2+ years React.js
* Be able to tell the difference between Java and JavaScript ;-)

### Ideally

* Long-term commitment preferred
* Skilled at state management planning & development (Redux, MobX, Context)
* CSS Ninja

### Responsibilities

_Initially, you'll have the following responsibilities:_
* Continue developing eLearning Platform
* Students teaching Students Videoconferencing Feature
* Students & Teachers messaging feature
* Many other cool features

_Long-term, there are many exciting projects we'll work on both for our client (the NGO), like another video conferencing platform and SaaS products we offer ourselves_

### You can bring

* Attention to detail
* Your own opinion
* The confidence to tell your boss "maybe you're wrong"
* The confidence to tell your colleagues "maybe I'm wrong"

### Why it would be awesome to work with us 

* You're helping make the world a better place, by helping us reduce people's mental health issues
* 100% Remote
* 100% international team - high standards & growing together
* Awesome colleagues
    
### Interesting Engineering Projects
* WebRTC (open source video conferencing protocol) integration
* Smart services integration between SaaS offerings and organizations

### Contact (MUST)
Homepage: www.pandigita.com
Email: peoplepower@pandigita.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
