### ISSUE TITLE
Pod Foods Vietnam - Frontend Developer (VueJS) - Hanoi - FT

### ISSUE THREAD

**Issue by podfoodsco** [awesome-jobs/vietnam#2346]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1200-$1500/negotiable

### Must Have

* At least 1 year of experience with VueJS
* Experience using REST API data sources
* Proficient with GitHub
* A portfolio of projects utilizing the above skills
* Excellent communication and problem-solving skills
* Ability to self-manage, collaborate and be a team player
* BS degree in Computer Science or equivalent backgrounds

### Big plus if you have...

* Experience with React
* Experience working with design tools (Figma, Sketch)
* Experience using animation libraries (Lottie)
* Experience with e-commerce application development
* Experience using test and build tools (NPM, Yarn, Jest, Webpack)
* A positive attitude and sense of humor

### What we expect from you

* Own technical design and development of presentation layer components utilizing the Vue.js SPA framework
* Help define technical roadmap and architecture based on technology and business needs
* Collaborate with peers within engineering and other teams to deliver the best customer experience possible
* Participate in designing new features while working with product and UX experts
* Contribute to continuous integration / continuous deployment pipeline
* Proactively recommend improvements and new approaches to addressing systemic pain points and technical debt

### Why it would be awesome to work with us

> Pod Foods is a software enabled B2B food distributor focused on local
> and emerging brands. We are based in San Francisco, with operations in
> Chicago, New York and Los Angeles. We are a fast growing company
> backed by Silicon Valley venture capital firms. The team comes with
> decades of industry experience and our engineering team is based in
> Hanoi. This is a great opportunity to join us on our exciting growth
> throughout the rest of the United States.

### Benefits & Perks

* Competitive compensation based on experience
* Annual evaluation with salary and bonus reviews
* Flexible, self-managed paid time off
* Team outings and birthday celebrations
* Self-improvement courses can be requested
* Premium Life & Healthcare insurance
* Free parking
* The best team and working environment you’ll ever find!

### Contact

* Please send your resume to  [thiem@podfoods.co](mailto:thiem@podfoods.co) or text me: 0982 85 87 83 (Mr. Thiem)
* [Pod Foods Homepage](https://podfoods.co/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
