### ISSUE TITLE
Pod Foods Vietnam - UI/UX Designer - Hanoi - FT

### ISSUE THREAD

**Issue by podfoodsco** [awesome-jobs/vietnam#2347]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1000-$1500/negotiable

### Must Have

* At least 2 years of experience in UX/UI Design roles.
* At least 1 year working closely with frontend engineers so you can forecast the feasibility of realizing your designs.
* A strong UX/UI portfolio to demonstrate the capabilities.
* A strong working knowledge of wireframing and prototyping tools (Figma, Sketch)
* Previous experience with user centered design principles and practices, web/mobile standards.
* Excellent attention to detail.
* Ability to work independently and collaborate with a team in a fast-paced, agile environment.

### Big plus if you have...

* Experience with presentation softwares (PowerPoint)
* Experience using animation libraries (Lottie)
* A relevant degree in-related field.
* Experience with e-commerce application development
* A positive attitude and sense of humor
* A willingness to jump in and do what it takes to help the team achieve results.

### What we expect from you

* Deliver attractive and effective user interfaces across a range of features in-app and operation tools.
* Create user flows, design wireframes, concept sketches and produce prototypes.
* Collaborate with the cross-functional product team from the start to the launch of a final product.
* Work closely with the product management and design team to ensure any UI solutions will help to compliment the overall user experience and journey.
* Contribute to the product's design system.
* Employ design thinking and questioning techniques to develop strategies and execution plans where pathways are not always obvious.

### Why it would be awesome to work with us

> Pod Foods is a software enabled B2B food distributor focused on local
> and emerging brands. We are based in San Francisco, with operations in
> Chicago, New York and Los Angeles. We are a fast growing company
> backed by Silicon Valley venture capital firms. The team comes with
> decades of industry experience and our engineering team is based in
> Hanoi. This is a great opportunity to join us on our exciting growth
> throughout the rest of the United States.

### Benefits & Perks

* Competitive compensation based on experience
* Annual evaluation with salary and bonus reviews
* Flexible, self-managed paid time off
* Team outings and birthday celebrations
* Self-improvement courses can be requested
* Premium Life & Healthcare insurance
* Free parking
* The best team and working environment you’ll ever find!

### Contact

* Please send your resume to  [thiem@podfoods.co](mailto:thiem@podfoods.co) or text me: 0982 85 87 83 (Mr. Thiem)
* [Pod Foods Homepage](https://podfoods.co/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
