### ISSUE TITLE
Senior Backend Developer

### ISSUE THREAD

**Issue by NhungLeee** [awesome-jobs/vietnam#2348]
## Location

* Saigon, Vietnam
* Full-time position

## Salary Expectation

* $3000 - 3500/month

## Requirements
* Python (Django/Flask) - 3 yrs experience
* CI/CD experience
* PostgreSQL
* AWS
* 4+ years Software Engineering experience

### Must Have

* Experience in building things from scratch 
* Experience in leading a tech team
* User experience-oriented
* Good at using English (Speaking and writing)
* Flexible, open-mined

### Ideally

* Experience with DevOps

### Responsibilities

* Working on building and supporting the backend of a LXP (Learning Experience Platform), including CRM, LMS, Virtual Classroom and Ed-apps
* Participate in all phases of the software development lifecycle
* Write reusable, testable, efficient, and secure code to build backend features in Python (Django/Flask)
* Debug the programs to fix issues
* Refactor and optimize code to improve maintainability and performance
* Prepare technical documentation
* Train/ guide and manage Junior/Middle Backend Developers to complete their tasks
* Report directly to CEO/COO

### You’ll be responsible for

* Building a superrrrr cool platform which helps educators digitalize their works

### Why it would be awesome to work with us

* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Homepage: https://ooolab.edu.vn/
Email: nhung.le@ooolab.edu.vn
Skype: rosie.307

**Comment by NhungLeee** [comment]
Re-open this position

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
