### ISSUE TITLE
Parcel Perform - Back-end Engineer - Saigon - FT

### ISSUE THREAD

**Issue by leonfoxnguyen** [awesome-jobs/vietnam#2349]
![Vietnam](https://user-images.githubusercontent.com/49466111/109776226-f0800f00-7c34-11eb-9089-0b388be4eb71.png)

## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - 3,000 Gross

## Requirements
* Be responsible with task and be open to discuss, give questions to build up products with high
quality and rich front-end experiences for our users.
* Understand clearly about object-oriented programming and design pattern.
* Willing to learn and research new technology or jump out of your comfort zone.
* Passionate about quality and the design of the code, productivity of the work and maintainability of the end result.
* An inspirational team player to successfully deliver team outcome.

## Skills
* At least 2 years, solid experience working with Python (2.7 and 3).
* Strong knowledge of scaling practices such as in-memory databases, load balancing, caching, etc.
* Comfortable with both SQL and NoSQL databases
* Worked on at least one project using a MQ as a communication hub. If you start one today, that still counts.
* Fluent in RESTful and real-time communication protocols.
* Familiar with AWS stack to get the most out of infrastructure.
* Eager to get involved in data engineering process
* Wide exposure to multiple technology stacks is an advantage, we love full stack guys (and girls!).

### Must Have
* Python

### Responsibilities

As a backend engineer, you will be building scalable systems with microservices. You will get to write code bases that are small and focused on doing one thing well. We choose microservices for technology freedom, resilience, and scalability, though there will be a lot of communication between services (does MQ ring any bell?), much automation and tons of metrics we need to keep an eye on. Such a system isn’t easy, especially with a focus on good engineering practices. But that is ok. We aren’t here for ease anyway. We are here for people who want to operate at the next level in their career.

### Why it would be awesome to work with us
* We offer a fair and competitive compensation package, and we have a preference for internal promotions whenever opportunities come.
* Having presences in Singapore, Vietnam, and Europe, our team is international and highly motivated. You will have many opportunities to work with and alongside people from around the world that share the same passion and dedication.
* Through 1-1 catchups, we continuously work with you on your strengths and weaknesses across many important dimensions and look at ways for you to address them and further your development.
* Locating in a quiet area with little traffic, full of natural light and within walking distance to many convenient facilities, our office in Ho Chi Minh City makes work-life integration to the fullest.
* Our working environment is open and our working hour is flexible. Work From Home is available by request and the leave plan is unlimited.
* And all the usual perks you’d expect from a fast-growing company like free lunch, free fruit, snacks, extra insurance and health care, team bonding events, various training programs, and more.

### Interesting engineering projects
* [Parcel Perform partnered up with AWS in building ML models to leverage post-purchase experience.](https://www.youtube.com/watch?v=mzUi4wSgbGs)
* [Parcel Perform-powered order tracking pages serve a wide variety of customers, some of them ships coffee capsules all over the world!](https://www.nespresso.com/au/en/track-your-order)
* [Parcel Perform Logistics Intelligence provides an overview of customer's logistics pipeline and gives out concrete actionable items.](https://iprice.my/trends/insights/how-malaysias-delivery-industry-counters-covid-19-pressure/)

### Contact
Find more jobs and apply on https://www.parcelperform.com/careers
Or drop your CV directly to Mr. Huy - HR Manager at huy@parcelperform.com (+84 906 05 4484)

![PP-Join-our-team-email-banner](https://user-images.githubusercontent.com/49466111/109784058-45278800-7c3d-11eb-9ebd-fc70f35df70b.png)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
