### ISSUE TITLE
Ematic Solutions - Customer Success Engineer - HCMC - FT

### ISSUE THREAD

**Issue by Ematicvietnam** [awesome-jobs/vietnam#235]
Do you want to join a recently funded, fast-growing software start-up? Work with international team members that are passionate about digital marketing? Learn a ton and have fun doing it? Ematic Solutions just might be the place for you! We’re a SaaS provider offering an Email Intelligence Platform that helps digital marketers nimbly build and deploy sophisticated and high-ROI email marketing programs. Our Email Intelligence Platform seamlessly integrates with a company’s Email Service Provider (ESP) and leverages a powerful suite of plug-and-play apps. Our apps have been proven to massively increase conversions by driving database growth and improving customer engagement. Our goal is to make the digital marketer smarter, and you’ll play a role in that relationship. The Ematic Solutions team is a small group of smart people from different backgrounds, based around the world, and share one passion: helping customers achieve better results. At lunch we find ourselves talking shop, and actually enjoying it. We’re a nimble, flexible and fun group, where your good ideas can make a difference.
## Location
- Saigon, Vietnam
## Salary Expectation
- Competitive
## Requirements
- Impeccable written and verbal communication skills in both Vietnamese and English; and experience with multicultural environments is a plus
- Problem Solving skills
- Data Structure and optimizations experience and skills
- Comfortable with taking on leadership roles and responsibilities
- Strong SQL, HTML5 and PHP knowledge is strongly preferred
- Strong MailChimp API knowledge is a plus
- 0-2 years of relevant experience
- Detail oriented and analytical
- Must be willing to work flexible hours to adapt to customer requests
- Strong team player, but still a self-starter
- Thrives in a multitasking environment and can adjust priorities on-the-fly
- You are tech-savvy - learning new tools does not scare you!
- You’re driven, and eager to learn, adapt and perfect your work
- You want to help and serve our customers: they win, so you win
### Responsibilities

Great power comes with great responsibilities!
### You’ll be responsible for
- Attending customer meetings, interfacing with the client. 
- Preparing data specification for customers
- Helping with data integration, cleaning data, porting, lists consolidation, etc.
- Preparing API working payload examples for the customers
- Work with customers to establish and achieve critical goals and other KPIs
- Help customers understand MailChimp basics (e.g. lists consolidation), and answering data/technical-related questions
- Work to identify and/or develop up-sell opportunities
- Advocate customer needs/issues cross-departmentally.
### Contact

Nick Ippel, Vietnam Country Manager, nick.ippel@ematicsolutions.com | 012165180498

![logo-highres-01](https://cloud.githubusercontent.com/assets/19338123/15990472/578c3ad4-30bd-11e6-8686-3d004c360bf7.png)

**Comment by joneslee85** [comment]
Thanks for posting with us. Please revise the format of the title, bullet points. Besides, what is this fancy job title? Is it related to customer support or solely programming?

**Comment by Ematicvietnam** [comment]
Hi Trung,

Thank you very much for the quick reply and support. I've updated the
format with Markdown. Could you please take a look and look if it's okay?

The Customer Success Engineer is more related to customer support. They
prepare data specification for customers - data maping, they help with data
integration, cleaning the data porting, lists consolidation (most tasks are
in the JD). A decent amount of critical thinking is required because of the
requirements for each customer are very different.

Please let me know if you require any additional information!

Cheers,
Nick



On Sun, Jun 12, 2016 at 6:15 PM, Trung Lê <notifications@github.com> wrote:

> Thanks for posting with us. Please revise the format of the title, bullet
> points. Besides, what is this fancy job title? Is it related to customer
> support or solely programming?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/awesome-jobs/vietnam/issues/235#issuecomment-225427070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AScTixmvmTO91nZJhjDa9tlwq75TNgDsks5qK-pngaJpZM4IzwOC>
> .
>



-- 

*Nick Ippel*
Country Manager Vietnam
Mobile: +84 1265 180498
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs5w6vVnW3M2qYF5wvn3-VRJgRK56dTCqd4sbSv02?t=http%3A%2F%2Fwww.ematicsolutions.com%2F&si=5992266989305856&pi=04bc079e-f4ef-4f06-92b3-971ae46b3b2c>
