### ISSUE TITLE
TINYpulse - QA Engineer - Saigon - FT

### ISSUE THREAD

**Issue by TINYpulse** [awesome-jobs/vietnam#2350]
## Location

* Saigon, Vietnam
* Flexible 

## Salary Expectation

* Up to $2,700 USD/month

## Requirements

* Ruby
* At least 1 year of experience in automation testing

## Skills

- Experience developing test automation or combination of development and test experience. 
- Familiarity with some of the tools such as Cucumber, Selenium Webdriver, Browser Inspector, POSTMAN, cURL and so on. Minimum 1 year of experience. 
- Understanding of and experience with high-quality test automation for a variety of feature types.
- Experience in software QA with well-developed exploratory testing skills.
- Experience in Performance/Security testing is a big plus.

### Must Have

- Coachable and personable- ideally with a good sense of humor!
- Team player- willing to disseminate knowledge to other team members.
- Passionate- not afraid to ask questions and eager to learn.
- Knowledge seeking- strives to improve current technologies and tools.
- Not afraid to make recommendations to improve effectiveness of the team.

### Why it would be awesome to work with us

- Flexible working hours
- A shiny laptop Macbook that fits your need.
- Unlimited vacation policy; work hard and take time when you need it.
- Stock options: all full-time employees get shares in the company. Along with the rest of us, you will be an owner of the company.
- Full medical inpatient & outpatient/ dental/ maternity package to fit your and your spouse's' needs.
- All benefits followed Vietnamese labour law, including 13rd month salary.
- Employees are showered with snacks & drinks in our bar, mini parties every week, followed with big events every quarter.
- Training opportunity: continuing development of technical, soft skills, and English through both internal and external classes

### Contact
Homepage: https://www.tinypulse.com/
Email: sgn-accounting@tinypulse.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
