### ISSUE TITLE
Tripla K.K. - Senior Site Reliability Engineer - Remote

### ISSUE THREAD

**Issue by Vinh0305** [awesome-jobs/vietnam#2353]
## Location
* Remote

## Salary Expectation
$3500 - $5000 (negotiable)

## Requirements
* A degree in computer science, software engineering or similar education
* 5+ years of professional DevOps or Site Reliability Engineering experience in fast paced work environment.
* Proven track record of securely architecting and managing AWS (e.g. IAM, EC2, VPC, ELB, ALB, Autoscaling, Lambda) using Infrastructure as Code techniques such as CloudFormation,Terraform
* Clear understanding of Networking concepts (e.g Firewalls, NAT, Port, Subnetting, VPC, VPNs, DNS, etc)
* Experience with managing CI/CD environment
* Experience with designing and owning production Unix container ecosystems (Docker, EKS, Fargate/ECS, Kubernetes, service discovery, service registry)
* Experience in designing and running a predictive alerting platform using monitoring tools such as Cloudwatch, NewRelic, DataDog or Pingdom
* Proficiency with APIs / microservices architecture
* Knowledge of data backup/recovery
* Ability to create scripts using Bash, Python or other language
* Excellence in Analytical and problem-solving skills
* Excellent oral and written communication
* Ability to work under indirect supervision

## Skills
* With serious desire to build great Well Architected cloud software
* Drive towards automating everything
* Drive towards building secure, efficient, scalable architectures
* That takes ownership of the solution and deliver
* With a team mindset, highly collaborative and enjoys a fast-paced, team environment
* That enjoys learning new technologies, concepts, and areas of business
* Champions the causes of uptime, reliability, compliance, and security 

### Why it would be awesome to work with us
- Remote work 100%
- Diversity first (engineer team from all around the world)
- Fast pace Startup in Chatbot/Booking Engine
- Global project: we are supporting Japan/Taiwan/Korea marketplace now and aim to support other marketplaces in near future
- Macbook + external monitor provided
- 8 paid leaves and Japanese holidays and more (we are flexible in holiday leave)
- Flexible working time

### Contact
Homepage: https://en.tripla.io
Trollman: vinh@tripla.jp

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
