### ISSUE TITLE
Loyal Capital - Senior Backend Developer (2 positions) - Hà Nội - FT

### ISSUE THREAD

**Issue by thanhpham** [awesome-jobs/vietnam#2356]
- As a software developer of our team, you will be involved in the architecture decisions that will shape software development applied in **Real Estate Industry**. This position requires high availability and fast, consistent performance. You will lead the workload with the latest open source technologies and can leverage your system design skills to make the right technical decisions for outstanding results.​
- ​Let's join us to work with a passionate, mission-driven group of members who want to positively contributes for remarkable projects entering competitive international markets.
- Salary: USD $1,000 - $1,500 (Based on experience, negotiable)

**Must have:**
- Ruby on Rails (minimum 3 years of experience for Senior role)
- React/NodeJS (minimum 1 year of experience)
- Front-end skills (JavaScript, HTML, CSS, jQuery, Bootstrap)
- RDBMS such as MySQL or PostgreSQL
- Experience with AWS and Serverless architecture.
- Write and optimize client-side code of the web applications, create a fast application with good UI/UX
- A deep understanding of Object-Oriented programming, OOP design patterns, and the SOLID principles.
- Senior Role: 3+ years experience.

**Nice to have:**

- College/Bachelor's Degree in Computer Science, IT, Engineering, or related field
- Experience with Docker;
- Experience and proficiency with Javascript and its runtime (Nodejs) / library (Reactjs) 
- CI/CD, Automation test;
- Love to work in Agile (Scrum) process, have a self-testing mindset;
- Have good teamwork skills.
- Have the open mindset
- Being active and energetic in activities in the company

​**Work Location:** 106 Hoàng Quốc Việt, Cầu GIấy, Hà Nội
**Contact:** Please send your resume/portfolio to _info@loyalcapital.ca_
**See more at:** [https://www.loyalcapital.ca/career](https://www.loyalcapital.ca/career)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
