### ISSUE TITLE
Loyal Capital - Frontend Developer (1 position) - Hà Nội - FT

### ISSUE THREAD

**Issue by thanhpham** [awesome-jobs/vietnam#2357]
- As a front developer of our team, you will be involved in the architecture decisions that will shape software development applied in Real Estate Industry
- ​Let's join us to work with a passionate, mission-driven group of members who want to positively contributes for remarkable projects entering competitive international markets.
- Salary: USD $800 - $1,300 (Based on experience, negotiable)

**Must have:**

- Strong understanding of JavaScript and web markup (HTML5/CSS3) (minimum 3 years of experience for Senior role)
- Good understanding of browser rendering behavior and performance
- Solid Knowledge of ReactJS or JsRender/JsViews JavaScript libraries
- Decent understanding of asynchronous request handling, partial page updates, and AJAX
- Familiarity with JavaScript module loaders, such as Require.js and AMD
- Experience with front-end build tools, such as Grunt and Gulp.js
- Proficient understanding of Git code versioning tool

**Nice to have:**

- College/Bachelor's Degree in Computer Science, IT, Engineering, or related field
- Experience in developing applications in Laravel/Rails  
- Love to work in Agile (Scrum) process, have a self-testing mindset;
- Have good teamwork skills.
- Have the open mindset
- Being active and energetic in activities in the company
​

​​**Work Location:** 106 Hoàng Quốc Việt, Cầu GIấy, Hà Nội
**Contact:** Please send your resume/portfolio to _info@loyalcapital.ca_
**See more at:** [https://www.loyalcapital.ca/career](https://www.loyalcapital.ca/career)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
