### ISSUE TITLE
Cloud Engineer (AWS, Linux)

### ISSUE THREAD

**Issue by uyennguyenhr** [awesome-jobs/vietnam#2358]
## Location

* Saigon, Vietnam
* District 1

## Requirements
* At least 1.5 years of experience in managing infrastructure in AWS service
* Experience in Linux System Administrator and Bash/Python Scripting
* Experience in software VPN technologies in multiple configurations (client access, site-to-site tunneling, NIC tunnel mesh)
* Experience in infrastructure security practices
* Intermediate English communication level to work with foreign partners

It would be nice if you have:
* Understanding and/or experience in DevOps culture, best practices, implementation
* The 5 Pillars of the AWS Well-Architected Framework mindset
* Knowledge of Serverless

### Why it would be awesome to work with us
* Highly competitive salary
* 13th-month salary + KPI bonus at the end of the year
* 15 days of annual leave per year
* Onsite opportunity in Korea
* Company trip at least once a year, monthly company parties & other Teambuilding activities
* Free coffee, snack and drinks

### Contact
Phone: 028-6295-8827
Send your CV to email: career@lecle.co.kr

### Know more about us
Facebook: https://www.facebook.com/LecleVietnam/
Homepage: https://www.lecle.co.kr/
Medium page: https://medium.com/leclevietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
