### ISSUE TITLE
Devhse Singapore - IOS team leader - HCM - FT

### ISSUE THREAD

**Issue by Rosedao03** [awesome-jobs/vietnam#236]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1200-1500/month or negotiable

## Requirements
* IOS/Swift skill + Android developement
* BS degree in Computer Science, Information Technology or a related subject
* 5 year + experience as an iOS developer.
* 1 year +  at Team lead position 
* Good teamwork and communication skill.
* Good learning attitude, professionalism and high sense of responsibility.
* Good English in writing and verbal
* Solid understanding of the full mobile development life cycle.
* Good time management and problem solving skill.

## What we can offer

* Performance review and salary adjustment 2 times a year
* Promotion opportunity
* Monthly team-building activity
* English training class

### Contact

Rose Dao: rose.dao712@gmail.com

**Comment by huydx** [comment]
@Rosedao03 Sorry, there is one thing we want to ask, are you represent the company (Devhse Singapore) ? In our jobboard, we prefer company's people instead of agency

**Comment by Rosedao03** [comment]
yes :) I represent for them

**Comment by joneslee85** [comment]
@Rosedao03 can you please provide a _direct_ contact point at Devhse? And are you a agency that represent the company?

**Comment by Rosedao03** [comment]
@joneslee85 this is a new company and I am the sole point of contact for them to setup a team in Vietnam

**Comment by joneslee85** [comment]
@Rosedao03 our rules demands that there is a direct contact at the company, this is not for the HR inquiry but technical / non-related HR. Please update the post with a 2nd contact point (it could be the CTO/CEO) of this startup.

**Comment by joneslee85** [comment]
@Rosedao03 I am closing this post because it does not have the 2nd contact point as requested. Please feel free to update the post and re-open when you have the piece of info.
