### ISSUE TITLE
[TTC Solutions-HN] JAVA DEVELOPER

### ISSUE THREAD

**Issue by Thuy-sarah** [awesome-jobs/vietnam#2364]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation
* upto 1500$ /month or range

## Requirements
* 3+ years Java experience
* Framework: Spring, Sping boot, Rest API 
* Strong expertise with both SQL and NoSQL databases
* Basic English communication

### Responsibilities
* Build and develop products/ systems with a high munber of users. 
* Improve with efficiency of existing products
* Coordinate with relevant departments (testing, operating the system ...) to deploy and operate the project in different evi ronments 
* Adhere to the company's project development process
* Implement and report work progress for project  management 

### Contact
Email: thuyntt@ttc-solutions.com
Skype: thuthuyn97

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
