### ISSUE TITLE
Altern8 - Frontend Software Engineer (Vue.js) - Remote - FT/PT/C

### ISSUE THREAD

**Issue by kennethjayden** [awesome-jobs/vietnam#2367]
## Location

* Remote

## Salary Expectation

* up to $2,500

## Requirements

* 2+ years of professional experience in frontend or full-stack development
* 1+ years of professional experience in Vue.js
* BS degree in Computer Science or equivalent backgrounds/experience 

### Must Have

* Strong coding, debugging, optimization, and problem solving skills
* Takes pride in building great technical solutions
* Excellent communication (English) and problem-solving skills
* Ability to self-manage, collaborate and be a team player
* Fun personality who's willing to learn new things

### Ideally

* Any experience with Amazon Web Services & Google Cloud will be advantageous
* Any experience with Laravel will be advantageous 
* Any experience with design (UI/UX) will be advantageous 

### Responsibilities

* You will be involved in a project of migrating a large legacy system to new system on Google Cloud, Laravel & Vue.js (Vuetify).
* Implement new and improve existing features for our web and mobile apps
* Architect efficient and reusable front-end systems that drive complex applications
* Identify and resolve performance and scalability issues
* Collaborate with other software engineers to deliver compelling user-facing products

### Why it would be awesome to work with us

* 100% Remote
* Awesome colleagues
* Flexible working time / arrangements 
* International working environment
* Gain experience with the option to work on different projects / roles

### Contact

We are open to negotiate the various roles and working arrangements/contracts. Do drop us an email.

Homepage: [altern8.sg](altern8.sg)
Email: info@altern8.sg

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
