### ISSUE TITLE
Golden Owl - Ruby On Rails Engineers - FT

### ISSUE THREAD

**Issue by hongloc5998** [awesome-jobs/vietnam#2369]
## Location:

* 538 Cách Mạng Tháng Tám, Phường 11, Quận 3, Thành phố Hồ Chí Minh
* Full-time

## Requirements: 
* Experience working as a Ruby developer. (Freshers are welcome).
* Good knowledge of OOP, PostgreSQL, MySQL, jQuery, Ajax.
* Hands-on experience in building products from scratch, etc.

### Responsibilities: 
* Communicate directly with clients to gather requirements and write code.
* Take part in system architect and design.
* Write clean code and reusable code.
* Troubleshoot and debug applications.

### Benefit:
* Provided Macbook to work.
* Performance review and salary adjustment 2 times a year.
* Private health check.
* Chance to become team leader if you could demonstrate strong leadership skills.
* Regular training and team sharing sessions.
* Company trip.

### Contact
Please send CV via loc.nguyen@topdev.vn 
Title: [Golden Owl] - Your name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
