### ISSUE TITLE
8Bit Rockstars - DevOps Engineer - Saigon - FT

### ISSUE THREAD

**Issue by 8BIT-ROCKSTARS** [awesome-jobs/vietnam#237]
![8BR](http://8bitrockr.com/img/logo_w.png)
#8 BIT ROCKSTARS

Floor 8th, Vincom B, 72 Le Thanh Ton, Ben Nghe Ward, Dist.1, HCMC
http://8bitrockr.com/
hr@8bitrockr.com

Email CV to **_hr@8bitrockr.com_**
## Salary

**_Up to 1,500 USD_**
## Job Description

We are looking for an **DevOps engineer**, who will work with us on building and scaling our startup teams. 

**You will have responsibility for:**
- Develop high-scale / high-load / distributed solutions with AWS technologies
- Implement, deploy, troubleshoot and maintain software systems
- Develop command-line tools that enable developers to quickly build, test and deploy images locally and to the cloud
- Work with Dev teams to provide an easy and predictable way to set things up and code with ease in mind
## Requirement
- Strong understanding of AWS Platform and all of its Cloud Computing Services
- Experienced with AWS CloudFormation / CLI and automated self-service platform in AWS
- Experienced with container technology, such as Docker, Vagrant, VMWare or OpenStack, etc.
- Experienced setting up and maintaining databases like MySQL (ElasticSearch or other NoSQL is a huge plus)
- Experienced with tools for Configuration Management, such as Puppet, Chef, or Ansible
- Strong experienced in one or more scripting languages (PHP, Python, Ruby)
- Proficient in Linux operating system administrations (shell, bash, automate scripts, etc.)
- Understand and can explain Test-Driven Development with ease
- Hierarchical and distributed code repository management tools (like GIT)
- Experienced setting up and maintaining Continuous Integration Workflows (with Jenkins, Bamboo or others.)
### Big Plus
- Experienced setting up and maintaining ElasticSearch or NoSQL databases (MongoDB, Redis, etc.)
- Familiar with monitoring systems solutions, such as Sensu, Nagios, Grafana, Graphite, InfluxDB, etc.
- Exposure to other cloud platforms, like Rackspace, Google App Engine, Azure, etc.
- AWS Certified Solutions Architect
- Good negotiation and communication skills.
## Benefits:
- Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things
- Attractive, **competitive salary** and incentives
- Year-end **bonus** (13th month salary ++)
- 40 hour work weeks (9:00-18:00, Mon-Fri)
- **15 days** of vacation per year
- **Probation** with **100% of salary**
- Performance and **salary review** every **6 months**
- **International Medical Insurance** will be paid by the company
- **English Class** with foreigner 3 times a week.
- New **Technologies Club** every week
- Quarterly **rockstar Hackathon** with the Best prizes
- Short and long-term **international training** / work
- **Company trip** (local or internationally) every year
- **Team building events**, party monthly and much more
- **Entertainment Zone** for all members with full media in the company (game, music, TV…).
- Enjoy **Relax and Coffee Bar** in the company.

Drop your CV to: **_hr@8bitrockr.com_** and we will be in touch with you shortly!

**Comment by vohuythao** [comment]
Very interesting and challenged job :D

**Comment by thanhngvpt** [comment]
great job
