### ISSUE TITLE
Frontend Lead

### ISSUE THREAD

**Issue by nhuquynhh** [awesome-jobs/vietnam#2370]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* up to $3000

### You’ll be responsible for

* Front-end Coding and Development: Along with the entire development team, you may be responsible for building a LXP (Virtual Classroom, LMS, CMS, CRM)
- Develop new user-facing features, maintain the current features
- Assist with architecture as well as work on actual implementation
- Build reusable code and libraries for future use, review other team members’ coding, ensure the implementation of agreed architecture and infrastructure.
- Work with frontend/backend team to plan and design structure of platform technology solution, help define the standard for Laboratory
- Address technical concerns, ideas and suggestions
- Focus on UI/UX and work with designers and PO’s when necessary
- Optimize platform applications for maximum speed and scalability
- Monitor systems to ensure they meet both user needs and business goals
- Collaborate with other team members and stakeholders
- Train/ guide and manage Junior/Middle Frontend Developers to complete their tasks
- Report directly to CEO/COO

## Requirements
* Degree in Software Engineering, Information Technology or relevant
* Have good knowledge about Object-Oriented Programming (OOP)
* At least 4 years of work experience in ReactJS, Javascript
* Experienced in Git or other source control systems
* Experience in leading a tech team

### Why it would be awesome to work with us
* Comfortable working conditions and flexible working time
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Website: https://ooolab.edu.vn/ 
Email: nhuquynh@1on1english.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
