### ISSUE TITLE
Liquid Blockchain Labs - Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by chinhq** [awesome-jobs/vietnam#2382]
## About us
Liquid is a top digital assets exchange in Japan and one of the highest-ranked exchanges globally.
The Block Labs plays a central role in the company’s commitment for innovation and contributes to the Blockchain ecosystem as a whole. Via Blockchain-oriented products, we want to play a major part in mainstream awareness and adoption of cryptocurrency and other Blockchain services to create an open financial system.

## Location

* Saigon, Vietnam

### Must Have

* Extensive experience implementing maintainable and testable code bases
* Hand-on experience designing, building, and scaling high-performance production systems.

### Nice To Haves:

* Experience with Golang and/or Typescript. 
* Understanding of smart contract implementation on Ethereum/Polkadot/EOS
* Knowledge of Blockchain Systems and/or Elliptic Curve Cryptography

### Responsibilities

* Build and maintain Liquid Wallet Service that controls all inflow and outflow crypto funds
* Solve hard problems to build a new blockchain system and ensure its robustness, performance and scalability
* Implement smart contract to build decentralized applications

### Contact
Homepage: liquid.com
Contact: chinh@liquid.com
You can apply directly by email or via https://careers.liquid.com/?gh_jid=5121943002

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
