### ISSUE TITLE
TourMega - Machine Learning Engineer - Remote - C

### ISSUE THREAD

**Issue by lekhuong07** [awesome-jobs/vietnam#2383]
## Location

* Remote

## Salary Expectation

* $2000+ / month

## Requirements
* Knowledge of Python, Java and R
* Experience with machine learning frameworks (like Keras or PyTorch) and libraries (like scikit-learn)
* Pursuing a advanced degree in Computer Science or related fields
* Strong communication (advanced English level)

### Must Have
* Understanding of NLP techniques for text representation, semantic extraction techniques, data structures and modeling

### Ideally
* 3+ years experience in Machine Learning, NLP Engineer or related roles
* Knowledge or experience with Ruby on Rails

### Responsibilities
* Implement and train state of the art NLP models like Bert to build Alexa for travel
* Find and implement the right algorithms and tools for NLP tasks
* Train the developed model and run evaluation experiments

### You’ll be responsible for
* Use effective text representations to transform natural language into useful features
* Develop NLP systems according to requirements
* Perform statistical analysis of results and refine models

### You can bring
* Creativity, problem solving skills
* Communicate well with other employees from different countries

### Why it would be awesome to work with us
* Startup experience
* Solve  problems to improve user experience
* Improve travel experience + discount coupons

### Contact or Full time
Homepage: https://www.tourmega.com/
Email: jobs@tourmega.com with Subject [Github-ML] - YourName (attached your resume)

**Comment by huuthonguyen76** [comment]
Hi, Is the job still available?

**Comment by khuongtour20** [comment]
> Hi, Is the job still available?

Yes, it is still available.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
