### ISSUE TITLE
TourMega - React Native Developer - Remote - C

### ISSUE THREAD

**Issue by lekhuong07** [awesome-jobs/vietnam#2384]
## Location

* Remote

## Salary Expectation

* $2000+ / month

## Requirements
* Bachelor’s degree in Computer Science or related fields
* 3+ years React Native mobile development experience
* Proficient in creating web configuration, understand and make API calls
* Fundamental JavaScript skills (ES5 and ES6) and TypeScript

### Must Have
* 4+ years mobile development & general software development experience
* Solid understanding of React Native / React, how it workflows - (Redux, Navigation, State) works and its core principles
* Confident yet humble in attitude, open to feedback and adjust as needed
* Strong communication (advanced English level).

### Ideally
* 5+ years mobile development
* Handle and work pressure well 
* Be able to meet deadline

### Responsibilities
* Leverage native APIs for deep integrations with both platforms.
* Diagnose and fix bugs and performance bottlenecks for performance that feels native.

### You’ll be responsible for
* Build pixel-perfect, buttery smooth UIs across both mobile platforms.
* Maintain code and write automated tests to ensure the product is of the highest quality.

### You can bring
* Creativity, problem solving skills
* Communicate well with other employees from different countries

### Why it would be awesome to work with us
* Startup experience
* Solve problems to improve user experience
* Improve travel experience + discount coupons

### Interesting engineering projects
* Mobile application for travel user

### Full time or Contract
Homepage: https://www.tourmega.com/
Email: jobs@tourmega.com with Subject [Github-Mobile] - YourName (attached your resume)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
