### ISSUE TITLE
Senior Tester

### ISSUE THREAD

**Issue by nhuquynhh** [awesome-jobs/vietnam#2385]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* up to $2500

## Requirements
* At least 4 years of practical experience in Software Testing (both manual and automation).
* Proven tracking record in working with Web, Mobile, and API Testing in both manual & automation testing.
* Strong knowledge of test automation tools and processes such as Git, Appium, Selenium, TestNG, Cucumber, CI/CD pipelines, etc.
* Hands-on experience with a programming language such as Python/Java
* Have good knowledge on SQL, HTML, Javascript, CSS.
* Knowledge about performance and security testing for API, Web is a plus.
* Experience in using bug and feature tracking tools: Jira...

## Skills
* Good problem-solving skills and team-work skills

### You’ll be responsible for

* Perform all phases of testing including QA, Staging, and Production environments.
* Understand and decide test coverage
* Create/Modify test-related artifacts (test cases, test report)
* Execute and maintain existing automated test scripts based on test results and/or changes in the product design.
* Ensure the assigned tasks to be performed on-time and with high quality
* Follow the project and organization processes, policies and regulations

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Email: nhuquynh@1on1english.vn
Website: https://ooolab.edu.vn/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
