### ISSUE TITLE
[TTC Solutions - HN] ANDROID DEVELOPER 

### ISSUE THREAD

**Issue by Thuy-sarah** [awesome-jobs/vietnam#2387]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $1000/month or range 
* More benefit

## Requirements 
* Have experience working in java, or kotlin android
* Basic understanding of models MVC, MPV, MVVM (layers, activity flow,
deployment)
* Know how to use Retrofit, DataBinding, LiveData, RxAndroid, Navigation
Component.
* Have knowledge of SVN, Git
* PostgreSQL
* 1+ years Android developer experience

### Responsibilities

* Create a base project for the project, write shared components. 
* Develop new features, optimize old ones
* Fix the errors of the application
* Report work to management

### Contact
phone/zalo/telegram: 0967.770.936
email: thuyntt@ttc-solutions.com
skype: thuthuynv97

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
