### ISSUE TITLE
CyberEye - .NET Developer - Hanoi - Fulltime

### ISSUE THREAD

**Issue by HungNguyenAalto** [awesome-jobs/vietnam#2389]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to 1200$

## Requirements
* Have a good knowledge of data structures, algorithms and object oriented programming (OOP)
* 3 years experience in C #, T-SQL programming language
* Proficient in ASP.NET or ASP NETCore
* Have good knowledge of system design
* Experienced in designing and querying database
* Experience in handling Cached
* Experience in handling Solr, ElasticSearch, big data 
* Experience in handling NodeJS, AngularJS, SignalR, OneSignal

## Responsibilities

* Building and Deploying ERP products and archives for customers
* Receiving SRS documents, analyzing and designing the system
* Planning for implementation, control, and support team members in the project
* Participate in building, upgrading platforms, integrating new technologies into the system
* Perform various researches, programming other functional modules as required by the manager

### Nice to have

* Technical document reading (URD, SRS, SRD)
* Experience in using SVN, Git
* Have skills for independent work, problem solving, and communication skills
* Ability to work under pressure (on progress and working time)
* Having DBA-related certification (MSSQL), MCSA is an advantage

## Why it would be awesome to work with us

* Income includes: base salary + 13th month salary + Bonus based on project implementation result + KPI bonus (2 - 3 months salary) + Year End bonus.
* Dynamic, friendly and professional working environment with many promotion opportunities. Working with leading Vietnamese technology experts.
* Training courses by professional training units to improve knowledge, technical skills, soft skills and management skills.
* Evaluate salary increase 2 times per year in January and July.
* Teambuilding 1 time / year, company trip 2 times / year.
* Company birthday and collective activities such as 1st of June (family festival), Mr. Perfect (Nam Vuong) contest, 8th of March activity, 20th of October celebration.
* Benefits according to the state laws (Insurance, annual leave) comes after 2 months of probation period.
* Working time is from Monday - Saturday morning (Morning: 8:00 - 12:00; afternoon: 13:30 - 17:30).

### Contact
Hung Nguyen, Business Development Manager
Email: hung.nguyen@ipowerpartner.com
Phone: +84 372684398
Skype: ef.ladk
Email subject: [.NET Developer] - Your name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
