### ISSUE TITLE
Vicare - Front-end / Javascript Developer - HN - FT 

### ISSUE THREAD

**Issue by huongdx** [awesome-jobs/vietnam#239]
If you are an experienced front-end developer with a strong drive to learn new technologies, a passion for crafting beautiful, user-friendly products and a taste for taking exciting challenges, this position is for you.
## Location
- Hanoi, Vietnam
- Fulltime
## Salary Expectation
- $500 - $1,500/month
## Requirements
- You must be very good at Javascript. Just knowing how to install some jQuery plugins won't be enough. You should be are able to code efficiently and structurally in the Javascript language, and you understand its good parts.
- Experience with a Javascript MVC framework such as AngularJS, Backbone or React is not required but will be an advantage.
- You should be an HTML expert - writing in semantic HTML is like writing in your mother tongue.
- You should be good at CSS.
- You should have a strong interest in creating great UI / UX. You are passionate about building friendly, powerful user interfaces for the average person.
- You should have a good foundation in software programming.
### You’ll be responsible for

You will be joining our tech team to design, build and grow the core product of the business - an online platform to revolutionize healthcare in Vietnam.

Your day to day tasks will include, but not be limited to, the following:
- Brainstorm, design, and develop our online products - including our main web sites, mobile web apps, online management,  and everything tech-based.
- Optimise our front-end code to achieve our ambitious growth targets on mobile and desktop space. This will require both imagination and data-driven thinking - it's an unique job that is at the crossroad of art and science.
- Be pro-actively involved in the full Agile/Lean product development life-cycle - that includes carrying out experiments, analysing data and collecting valuable learnings along the way. It will be a different experience from working in outsource projects, and you will love it.

With us you will find an exciting blend of a vibrant startup environment and professional operations from experienced executives. There will be real and meaningful challenges, as you will be leading your own initiatives and get things done within a wide range of areas, where team effort is pivotal and solutions rarely obvious. 

There will be perks of working in a young, fast-growing business, such as: a fast track to become manager given early employment status, stock options, flexible time and working space.
### About Vicare

ViCare is a startup with a vision to make quality healthcare more accessible to every Vietnamese by making information more transparent and connection to medical facilities seamless. We are a team of young and hungry entrepreneurs who want to learn, do things and make a positive change in the world, and in the process transforming ourselves for the better. We are about to the receive the second round of funding, and are expanding our team and our coverage aggressively.
### About the co-founders

Pham Anh Duc – co-founder and CEO: A young entrepreneur with extensive experience in strategy and day-to-day operation. Previously CEO of Nhanh Ltd, a SaaS start-up and Chief Commercial Officer of Vatgia Group. Before that country head of Marketing at Lazada Vietnam and management consultant with 2+ year at McKinsey&Co with strong retail and SME banking background in Vietnam, Indonesia and Thailand. Areas of experience include E-commerce and its ecosystem, online marketing and partnership, Business Unit strategy, design and implementation of credit risk tool and organizational transformation.

Dave Bui – co-founder and CTO: Over six years of experience working in three of the best-known digital marketing agencies in Australia and United Kingdom (Isobar UK, Isobar Australia, Next Digital Group). Having a global mindset from living and traveling to different cultures across 4 continents. Strongly passionate about making empowering technology products that could change everyday life. Coming back to Vietnam in 2015, Dave had worked at VNDIRECT Securities as Director of Technology.
### Contact

Please send your CV to Ms Huong at huongdx.hr@gmail.com or Mr Dave at dave@vicare.vn, with email subject "Application for Front-end / Javascript Developer position".

**Comment by joneslee85** [comment]
Thanks for posting with us. Are you working for Vicare or a agency that represent the company?

**Comment by huongdx** [comment]
Dave Bui is my friend and he want me to help him select CV, this job is not for agency. Tks.

**Comment by joneslee85** [comment]
@huongdx I see. Can you please also add Dũng's contact in the contact section too?

**Comment by huongdx** [comment]
Updated, tks for support
