### ISSUE TITLE
CyberEye - Frontend Developer - Hanoi- Fulltime

### ISSUE THREAD

**Issue by HungNguyenAalto** [awesome-jobs/vietnam#2390]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to 1200$

## Requirements
* Good communication skill
* At least 2 years of experience working with HTML5, CSS3, Bootstrap css, Bootstrap validator
* Experience with Javascript is an advantage
* Have a good knowledge of IT and understands technical design
* Responsive skills for each screen and device
* Ability to work independently as well as in a team
* Eager to learn and make progress at work 

### Responsibilities

* Build HTML, CSS based on the prototype of the project
* Responsive handling, Javascript for functional modules
* Other tasks assigned by superiors

### Why it would be awesome to work with us

* Income includes: base salary + 13th month salary + Bonus based on project implementation result + KPI bonus (2 - 3 months salary) + Year End bonus.
* Dynamic, friendly and professional working environment with many promotion opportunities. Working with leading Vietnamese technology experts.
* Training courses by professional training units to improve knowledge, technical skills, soft skills and management skills.
* Evaluate salary increase 2 times per year in January and July.
* Teambuilding 1 time / year, company trip 2 times / year.
* Company birthday and collective activities such as 1st of June (family festival), Mr. Perfect (Nam Vuong) contest, 8th of March activity, 20th of October celebration.
* Benefits according to the state laws (Insurance, annual leave) comes after 2 months of probation period.
* Working time is from Monday - Saturday morning (Morning: 8:00 - 12:00; afternoon: 13:30 - 17:30).

### Contact
Hung Nguyen, Business Development Manager
Email: hung.nguyen@ipowerpartner.com
Phone: +84 372684398
Skype: ef.ladk
Email subject: [Frontend Developer] - Your name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
