### ISSUE TITLE
Q-P - Rust HPC - Vietnam or Switzerland - FT/PT/C

### ISSUE THREAD

**Issue by q-p-j** [awesome-jobs/vietnam#2394]
## Location

* Vietnam (remote) or Switzerland

## Salary Expectation

* $1-5k/month or equivalent, depending on experience

## Requirements

* Proficient Rust

### Must Have

* Affinity with low-level (systems) programming in Linux
* Ability to write high-performance code
* Good enough English to communicate comfortably
* Self-motivation and ability to take ownership
* Ability to work in an international team

### Ideally

* Experience with low-latency networking
* Deep experience with profiling/code optimisation in Rust or any other systems programming language
* Some knowledge of Haskell

### Responsibilities

You will take responsibility for parts of the trading infrastructure within a team of highly skilled Rust programmers. Our focus is low latency, so much of the time is spent on profiling and code optimisation.

### Why it would be awesome to work with us

* We have very interesting HPC coding tasks, there is no legacy code!
* The team is friendly and highly skilled - great opportuniy to learn
* We have a very flat hierarchy, there is no corporate BS, you won't need to talk to clients!
* We are based in Switzerland, so we invite you to visit Switzerland regularly if you like (at our expense).
* We offer the opportunity to work remotely. We also welcome if you like to move to Switzerland permanently! (I.e. we would also be willing to sponsor the Swiss work permit.)
### Interesting Engineering Projects

* Low-latency trading systems in pure Rust

We have the opportunity to start fresh and build the whole infrastructure completely in Rust (we love Rust). So we are looking for several able Rust programmers at all levels of seniority! Please contact us if you want to know more!

### Contact (MUST)
Q-P: q-p@tuta.io

**Comment by TanNgocDo** [comment]
sound interesting

**Comment by q-p-j** [comment]
There is some C/C++, but we want to replace it. I can give more details in a private chat.

**Comment by tien-dat-nguyen** [comment]
wow, a very interesting project - Low-latency trading systems in pure Rust, as I remembered there is an Korean company they took the same approach and its performance is comparable to the C++, love this job.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
