### ISSUE TITLE
McKinsey & Company - Frontend, Backend, Lead Engineers - Saigon - FT

### ISSUE THREAD

**Issue by kienphamMcK** [awesome-jobs/vietnam#2395]
## Location
* Saigon, Vietnam

## Salary Expectation
* Very attractive ++

## Requirements
_For Frontend Engineer_:
* Familiarity with various JavaScript standards, libraries, frameworks, compilers, and transpilers including ES6, TypeScript, Babel, Web Workers, React, and Angular
* Experience with package managers (npm), task runners (Gulp, Webpack, Grunt), CSS processors (Sass, Stylus), and APIs (WebSocket)
_For Backend Engineer_:
* Strong working experience in Java (Spring, Play, etc.) and Nodejs(Express, Hapi, etc.) 
* Expertise in programming languages preferably Perl, Python, PHP, C/C++, Go, or Ruby
* Familiarity with Perl, CPAN, NGINX, JavaScript, Redis, and Git
* 5+ years Frontend/ Backend/ Lead Engineering experience

## Skills
* Consulting & problem solving skill
* Collaboration skill
* Fluent communication in English

### Must Have
* Be able to travel
* Be able to dodge bullet

### Ideally
* Experience with Agile methodology

### Responsibilities
* Develop and maintain advanced features, tools and applications according to the best practices in UI/UX, front-end development and hybrid mobile application development.
* Test and debug our ever-evolving product line to improve their speed, scalability and usability across multiple browsers, devices and web standards
* Contribute to the architecture across the technology stack, from database to native apps

### Why it would be awesome to work with us
* You’ll typically work on projects across all industries and functions and will be fully integrated with the rest of our global firm
* Our office culture is casual, fun and social, with an emphasis on education and innovation

### Interesting engineering projects
* From IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation

### Contact
Homepage: https://www.mckinsey.com/careers/search-jobs#?cities=Hanoi&interest=Digital
kien_pham@mckinsey.com

**Comment by kienphamMcK** [comment]
Constantly looking for SWEs with excellent problem-solving skills ;)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
