### ISSUE TITLE
HCM - Technical Leader .NET - Fulltime 

### ISSUE THREAD

**Issue by QuynhNguyen14** [awesome-jobs/vietnam#2397]
## Location
Q1, HCM 
* Saigon, Vietnam

## Salary Expectation
negotiation 

## Requirements
* Bachelor's degree in Computer Science, Computer Engineering, Mathematics or in a related field.
* Have 5+ years of experience using a .NET development environment, understand basic server commands.
* Have a solid understanding of OOP, Coding Principles, Design Patterns, and Architectures.
* Hand on Web Development technologies using AngularJS, HTML5/CSS3.
* Strong at database modelling and understanding of transactions.
* Able to obtain a deep knowledge of the project technologies and work independently.
* Effective use of source control system including branching, merging code, and create pull requests.
* Experience in mentoring, supporting, and doing code review.
* Able to self-learn and adapt to new technologies quickly.
* Strong leadership skills, both organizational and technical.
* The confidence to communicate your own technical ideas in an open forum and to encourage your team mates to communicate theirs.
* Excellent English communication skills.
* Familiar with Agile development methodologies.

## Skills
.NET, .NET Core, .NET Framework, SQL, AngularJS, HTML5/CSS3

### Must Have

* Fluent in communicating in English.
* Experience in leading a team of developers.
* Experience with Node.js.
* Logistics domain experience.

### Responsibilities

* Work with UK Technical Architect on “Core Technology” Product development.
* Build and maintain deep-level knowledge of Core Tech approved development frameworks/platforms, i.e. Azure, .NET Core, .NET Framework, SQL, AngularJS, Node.js.
* Responsible for the coaching and mentorship of the offshore development teams in the application of Core Technology.
* Help drive quality through performing code reviews, ensuring adherence to existing standards and processes while providing input into further improvement measures.
* Maintain awareness of all concurrent development workstreams, help resolve technical blockers, reduce conflicts between workstreams, and identify potential synergies for improved efficiency.
* Lead the onboarding process for all new development recruits.
* Be a senior technical advisor to the Development Manager; help identify strengths, weaknesses, opportunities, and threats within the team.

### Why it would be awesome to work with us

* 13th-month salary and 14 annual leave.
* Medical and Accident Insurance program.
* International, dynamic, friendly working environment.
* Clear and stable career growth.
* Many opportunities for personal and professional development.
* Professional training.
* Company trip and regular team building events, sports activities…

### Contact
Skype: nhuquynh1495@outlook.com
Fanpage: https://www.facebook.com/quynhnguyen.blogs
Website: http://quynhnguyen.top/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
