### ISSUE TITLE
Quod AI - Junior Big Data Engineer - Saigon - FT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2398]
## Location
Saigon, Vietnam

## Salary Expectation
$800-$1200 (Gross)

## Requirements
* Solid skills with Java. Python is a plus.
* Solid understanding of databases.
* Relevant experience with Google Cloud or AWS.
* Superior analytical, conceptual and problem-solving skills.
* The ability to learn and iterate quickly.
* An obsession with agile and lean principles (GitHub, Trello).
* Experience with complex text parsing and web scraping a plus.
* Experience with data pipelines or ETL a plus.

### Education and Experience 
* University degree in computer science or similar education.
* Minimum 2 years of experience with focus on backend development.
* Strong verbal and written communication skills in English.

### Responsibilities  
* Work with fellow engineers and data scientists to develop and maintain our core product.
* Implement our data pipelines (Java, Elasticsearch, Redis, Apache Beam).
* Work on the implementation of new features, leaving things properly implemented, well documented and delivered on time.
* Always be on the lookout for opportunities to create and improve. From our development process, up to final user’s experiences.

### Contact
Homepage: [https://www.quod.ai/](https://www.quod.ai/)
[Apply here](https://docs.google.com/forms/d/e/1FAIpQLSd0n7WUvlu8B27VINJ4fO86T64MkeiZ2XWEEWFfeLvvOL9xnQ/viewform?fbzx=7745572257721885000)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
