### ISSUE TITLE
FETCH TECHNOLOGY - Front-end Angular/React Developer - HCMC - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2406]
## Binh Thanh District, Ho Chi Minh

* Saigon, Vietnam

## Salary Expectation

* Up to 2000$

## Requirements
* 2-4 years of experience in front-end development.
* Good understanding of Angular/React.
* Proficiency in HTML5, CSS3, JavaScript.

## Benefits

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).  

### Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech
Zalo: 0886626167

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
