### ISSUE TITLE
FETCH TECHNOLOGY - Full-stack Web Developer (PHP Laravel/Javascript) - HCM - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2407]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114515019-1baf4280-9c66-11eb-987b-749b28baebb5.jpg)

## Requirements
* Experience (years): Senior Developer/3+ years experience. 
* PHP 2+ years of experience.
* Knowledge of front-end technologies like Javascript, Html, CSS...
* Have experience with any PHP web frameworks (Laravel or Symfony or Zend) (Laravel preferred).

## Why you'll love working here
This is a unique opportunity to be part of a vibrant and exciting new company that has received positive traction in the blockchain space and has partnerships with top corporate firms such as IBM, Intel and BMW and technical protocols such as ConsenSys, R3 and VeChain. We work closely with a variety of stakeholders; startups, government agencies, technical protocols and corporate firms. 

If you join us, you will have hands-on experience and ownership executing the company’s vision of building the blockchain ecosystem in Singapore. If you enjoy working with startups and building something new with us, be a part of us today. 

Being a Senior Full-stack Web Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).  

## Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
