### ISSUE TITLE
FETCH TECHNOLOGY - Python Developer - HCM - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2408]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114515880-08e93d80-9c67-11eb-8c59-00f8875ab2c6.jpg)
## Requirements

* At least 1 year of Python and Django framwork.
* Experience using databases (postgresql, mysql,..).
* Experience** designing Rest APIs and using Rest APIs testing tools eq: Postman,...

## Why it would be awesome to work with us
* Being a Python Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* PVI Health Care.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...).  

## Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
