### ISSUE TITLE
FETCH TECHNOLOGY - Test Engineer (middle/senior) - HCM - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2409]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114516770-e99ee000-9c67-11eb-8cb7-ebe7404a6bcb.jpg)
## Requirements
* At least 2 years of experience in developing automated test systems.
* At least 1 year in software development.
* Familiar with various testing tools, scripting languages, SQL, Bash, basic system administration.
* Degree in Computer Science or equivalent practical experience.
* Have experience in manual testing (Web/Mobile).
* Strong knowledge in APIs testing.
* Excellent communication skills.

## Why it would be awesome to work with us
Being a Test Engineer at Fetch Technology, you will experience a youthful, flexible and creative work environment: 

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese. 
* Extensive on job training, you will always have a chance to work with new emerging technologies. 
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law. 
* 12-day annual leave per year. 
* 13th-month salary. 
* PVI Health Care
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact
Skype: Tonnhatha3@gmail.com 
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
