### ISSUE TITLE
TINYpulse - Full Stack Developer - Saigon - FT

### ISSUE THREAD

**Issue by TINYpulse** [awesome-jobs/vietnam#241]
![image](https://cloud.githubusercontent.com/assets/19971922/16145378/71ae83c0-34a2-11e6-9694-3b97e45380dd.jpg)

_We are **TINYpulse** - We help leaders gather ongoing feedback from their team members and take action resulting in a happy and productive work environment. 
We are looking for a **Full Stack Developer** who is able to build single page applications including implementing, testing, integrating and utilising APIs with latest front-end web technologies._
## Location
- Saigon, Vietnam
## Salary Expectation
- Negotiable
### What skill sets are we looking for from you?
- Languages: being efficient in any of the following languages: Ruby, JavaScript
- Framework: strong experience in modern web technologies such as Ruby on Rails, and Backbone.js
- Database: relevant experience with relational databases such as MySQL or PostgreSQL
- Test coverage: competent skills in test automation (unit test, and integration test)
- Platform: adequate knowledge of Continuous Integration and web application deployment
### Preferable if you have these skills:
- UI/UX knowledge
- Reactive programming experience
- React experience
### How do you know if this is the right role for you? If you:
- Enjoy a fast-paced entrepreneurial environment
- Have strong analytical and problem-solving skills
- Are coachable and personable, and, ideally, with a good sense of humour!
- Are a team player, who is willing to disseminate knowledge to other team members.
- Are a passionate individual who is not afraid to ask questions and eager to learn.
- Maintain a high degree of knowledge of current technologies and tools
- Make recommendations to improve effectiveness of the team
### A few basic bits on the environment you will be working in:
- About 60 people in Vietnam, who make up the product team that uses a mix of Scrum and Kanban
- It's flat- which means there is not a lot of management or bureaucracy
- About 55 people in Seattle working on sales, marketing and customer success
- Sharp, motivated co-workers in a fun, beautiful office environment with ridiculous view
### Benefits
- Free laptop (Macbook/ Window) that fits your need. iOS, Android testing devices.  
- Unlimited vacation policy; work hard and take time when you need it.
- Full medical inpatient & outpatient/ dental/ maternity package to fit your and your spouse's' needs.
- All benefits followed Vietnamese labour law, including 13rd month salary.
- Employees are showered with snacks & drinks in our bar, mini parties every week, followed with big events every quarter.
- The opportunity to travel to U.S. Build product that companies around the world are using to improve their employee's happiness.
  *Training opportunity: continuing development of technical, soft skills, and English through both internal and external classes 

For more details: [Link](http://tinypulse.com)
### Contact

Joy: joy@tinypulse.com

**Comment by joneslee85** [comment]
@TINYpulse thanks for posting with us. Great post btw
