### ISSUE TITLE
FETCH TECHNOLOGY - DevOps Engineer - HCM - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2411]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114520203-63849880-9c6b-11eb-9f04-aceb94b59dd3.jpg)
## Requirements
* 3+ years experience in DevOps engineering environment. 
* Strong background in Linux / Unix, preferably with experience in NixOS. 
* Have experienced with AWS, GCP or Hetzner. 
* Experience with CI/CD processes using self-managed tools or relevant cloud technologies (e.g Jenkins, CircleCI, Drone, GoCD etc.) 
* Familar with the following tools: Jira, Jira Service Desk, PagerDuty, NewRelic, Terraform, Ansible, Vault... 
* Knowledge about Computer Security, Application Security, and Security Standards & Best Practices. 
* Hands-on experience in networking, system administration, monitoring, infrastructure maintenance on premise or cloud environments. 
* Knowledge of microservice architecture, RESTful.

## Why it would be awesome to work with us
Being a Devops Engineer at Fetch Technology, you will experience a youthful, flexible and creative work environment.  

* MacBook or high-end laptop for working. 
* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese. 
* Extensive on job training, you will always have a chance to work with new emerging technologies. 
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law. 
* 12-day** annual leave per year. 
* 13th month salary. 
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).  

## Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
