### ISSUE TITLE
FETCH TECHNOLOGY - Senior/Middle Backend Developer (RoR) - HCM - FT 

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2412]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114521030-3b496980-9c6c-11eb-90a6-e01cb9155133.jpg)
## Requirements
* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* 4+ years of software development experience (with at least 2 years in Ruby on Rails).
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Able to apply good security practices.

## Why it would be awesome to work with us
Being a Senior/Middle Back-end Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese
* Extensive on job training, you will always have a chance to work with new emerging technologies
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).

## Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
