### ISSUE TITLE
FETCH TECHNOLOGY -  IT/NOC Ops - HCM - FT 

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2413]
![Fetch team building](https://user-images.githubusercontent.com/77085508/114524107-215d5600-9c6f-11eb-8855-9bbee7a34d86.jpg)
## Requirements
* A degree in IT, Computer Science, Software Engineering.
* Relevant experience in NOC / IT operations is preferred.
* Familiarity with Logging, Monitoring and Alerting tools.
* Familiarity with GCP, AWS Cloud Services is preferred but not necessary.

## Why it would be awesome to work with us
Being an IT Ops at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* MacBook/laptop for working.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive** on job training, you will always have a chance to work with new emerging technologies.
* Career progression in a fast-growing company.
* Devops training to help you progress to more senior roles within the company.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Team dinner, Team-building, Company trip, Play games (PlayStation, CS Go), Play Sport (Football, Badminton...).

## Contact
Skype: Tonnhatha3@gmail.com
Email: Nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
