### ISSUE TITLE
JobSeekervn- Fullstack Developer - Saigon - Fulltime

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2417]
## Location
* Saigon, Vietnam
* Fulltime

## Requirements
* At least 3 years of experience in both front-end and back-end languages (NodeJS & ReactJS preferred).    
* Experience working with system design, database architecture, and middleware development...
* Familiar with development and deployment in Linux and Amazon Web Services like EC2, S3, ElasticSearch
* Familiar with Android programming and AOSP systems a plus.
* Maintain a good coding standard, familiar with Test Driven development. Experience with writing unit test for NodeJS, ReactJS.

### Responsibilities
*Participate in projects as a web team member to develop, review and optimize code base for Web application.
*And perform similar duties as he deems fit for the proper execution of his duties and duties as delegated by the direct manager or the Employer.

### Why it would be awesome to work with us
* Social insurance, health/life/disability insurance, annual health check
* 13th-month salary 
* Yearly bonus up to 2 month pay depending on performance review
* 14 days of paid vacation                
* Work laptop
* Company trip and other team benefits

### Contact
Email: nhiha@jobseeker.vn 
Skype: hahoainhi
Website: nhiha.top

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
