### ISSUE TITLE
SCS - Juninor/Mid Ruby on Rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by trucpt** [awesome-jobs/vietnam#243]
## Location
* Saigon, Vietnam

## Salary Expectation
* +$1000/month or negotiable

## Requirements
- At least 1-year experience in RoR
- A toolbox full of awesome gems.
- Front end development: HTML, CSS, Javascript, Bootstrap
- To be a Git-ninja
- To be a good team's player.
- Can host a seminar in English
- COURAGE to change the world with our team.

### Ideally
- Passion in coding
- Pay attention to the smallest detail.
- You can use command-line for any activities.
- You want to be proud of your works.
- Have experience with startup tool stack: Slack, CI, GitHub, Asana, Trello,…
- Desire to become fullstack ninja

### You’ll be responsible for

* Building products in Logistics indutry to change the world step by step

### You can bring

* A good eyes for design
* A good analyis skill

### Contact
hr@dounets.com

**Comment by joneslee85** [comment]
@trucpt thanks for posting with us. Please revise your post as I could find typo, such as `Juninor`

**Comment by joneslee85** [comment]
@trucpt there is no update after 2 days thus the job post is now closed. Feel free to make amendment and re-open it.
