### ISSUE TITLE
Titan Technology - ReactJS/.NET Developer - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2430]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* ReactJS or .NET/C# 
* From 3 years experience

### Must Have

* Degree in Software Engineering, Information Technology, or relevant.
* At least 3 years of work experience in developing web applications.
* Experienced in ReactJS and/or .NET and/or .NET Core
* Have good knowledge about Object-Oriented Programming (OOP).
* Experienced in Git or other source control systems.
* Good English skills.
* Good time management, communication, and problem-solving skills.
* Good teamwork spirit and logical thinking.
* Proactive, well self-organized, and responsible at work.
* Able to quickly manage new technologies.

Great power comes with great responsibilities!

### You’ll be responsible for

* Code, implement, unit test, maintain and troubleshoot web application.
* Comply with established coding quality standards of the company.
* Work closely with the QA team to ensure the project quality
* Report to Team Leader.
* Assist Team Leader in reviewing work results of low-level members.
* Participate in R&D, training, knowledge sharing activities.
* Follow the project and organization processes, policies and regulations.
* Ensure the assigned tasks to be performed on time and with high quality.

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Interesting engineering projects
* Fintech/ Auditing for Western Client

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **an.ngo@titancorpvn.com** 
** Subjects: **Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
