### ISSUE TITLE
Chotot - Backend Engineer - HCM - FT

### ISSUE THREAD

**Issue by lethanh94951997** [awesome-jobs/vietnam#2432]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* 1500$ - 2200$

## Requirements
* Experience working with one or more from the following: web application development, Unix/Linux environments, distributed systems, machine learning, networking, developing large software systems.
* Experience in Golang or confident that you can pick it up in no time.
* Solid production experience with one or more general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6.
* Experience with two or more data systems but not limited to: Postgres, Mongodb, Elasticsearch, Redis, Kafka, Cassandra.
* Experience with Docker, Kubernetes.
* Familiar with Microservices, event driven architecture.
* BA or MA degree in engineering, computer science or other technical related field. Or formerly competitive programmer.
Working proficiency and communication skills in verbal and written English.

## Skills
* GO/NODEJS/PYTHON

### Responsibilities
* Solve engineering problem to enable smart Marketplace ecosystem of products and services.
* Design, Build, Run and improve backend services and framework of create micro services.
* Manage individual project priorities, deadlines and deliverables.
* Improve engineer efficiency with common libraries, tooling and platform.

### Contact
* Send CV to email: lethanh94951997@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
