### ISSUE TITLE
FETCH TECHNOLOGY - REACT NATIVE - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2433]
![image](https://user-images.githubusercontent.com/60914247/115335509-8e20a500-a1c7-11eb-8f1c-e8f3dbfe69b6.png)

## Requirements
* Experience in quickly developing basic MVP with CRUD functions with a longer-term vision for architecture planning.
* Experience in leading a team and project management.
* Fluent in conversing and working in English.
* Able to work on: Flutter/React Native/Ionic, MongoDB/any other relational databases, API & SDK integrations
* About 3 Years’ experience.
* Testing.
* Research, score and select cloud servers to access user data securely & efficiently.
* User support.
* Adding of new features.

Good to know: Integration with barcode scanner API, scheduling of delivery, meal plan API, face scan SDK.
* Good to have a background in any of the things below:
* Consumer health apps.
* AI/ML.
* Working on bio-informatics data points and flow.

## Responsibilities

* Understanding & prioritizing customer use cases and jobs (working alongside founders) (customer interview is already done, use cases already determined but open for adjustments).
* Building wireframes.
* Working with UXUI contractor with high fidelity mockups.
* Building out and going live with MVP with minimal features (e.g. CRUD) to handle at least 1-2K users during beta launch (within 1 month).

## Why it would be awesome to work with us?
Being a React Native Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive on-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...). 

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
