### ISSUE TITLE
FETCH TECHNOLOGY - QA ENGINEER (Automation test) - HCM/HN - Remote - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2434]
![image](https://user-images.githubusercontent.com/60914247/115335919-5a924a80-a1c8-11eb-8f47-b57807a33b91.png)

## Requirements
* Proven work experience in software development.

* Proven work experience in software quality assurance.

* Strong knowledge of software QA methodologies, tools and processes.

* Experience in writing clear, concise and comprehensive test plans and test cases.

* Hands-on experience with both white box and black-box testing.

* Hands-on experience with automated testing tools.

* Solid knowledge of SQL and scripting.
* 
## Responsibilities
* They are looking for a Quality Assurance (QA) engineer to develop and execute exploratory and automated tests to ensure product quality.

* QA engineer responsibilities include designing and implementing tests, debugging and defining corrective actions. You will also review system requirements and track quality assurance metrics (e.g. defect densities and open defect counts.)

* The QA technician role plays an important part in their company’s product development process. Their ideal candidate will be responsible for conducting tests before product launches to ensure software runs smoothly and meets client needs while being cost-effective. If you hold an engineering background and enjoy providing end-to-end solutions to software quality problems, they’d like to meet you.

* Ultimately, you should monitor all stages of software development to identify and resolve system malfunctions to meet quality standards.

* Review requirements, specifications and technical design documents to provide timely and meaningful feedback.

* Create detailed, comprehensive and well-structured test plans and test cases.

* Estimate, prioritize, plan and coordinate testing activities. 

* Design, develop and execute automation scripts using open source tools. 

* Identify, record, document thoroughly and track bugs.

* Perform thorough regression testing when bugs are resolved. 

* Develop and apply testing processes for new and existing products to meet client needs. 

* Liaise with internal teams (e.g.developers and product managers) to identify system requirements. 

* Monitor debugging process results.

* Investigate the causes of non-conforming software and train users to implement solutions.

* Track quality assurance metrics, like defect densities and open defect counts.

* Stay up-to-date with new testing tools and test strategies.

## Why it would be awesome to work with us?
* You will be joining a young startup in a growth phase and you will also be working remotely (they don't intend to get an office anytime soon). This means a couple of things:

* Flexible schedule. You will have a more flexible schedule but you will also have to be prepared to fight fires at odd hours when you least expect.

* Pull your own weight. As employee #12, you make up 8.3% of our company. There'll be no hand-holding and they expect you to pull your own weight - like everyone else.

* Things get messy. There's no sugarcoating this. Things are unstructured and processes might be lacking. They're not where they want to be but they're getting there.

* You must be able to thrive in ambiguous situations (see point above).

* You are willing to put in the time to get the most out of any opportunity.

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
