### ISSUE TITLE
FETCH TECHNOLOGY - FULLSTACK DEVELOPER (REACT,NEST/EXPRESS JS) - Remote - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2435]
![image](https://user-images.githubusercontent.com/60914247/115336429-6e8a7c00-a1c9-11eb-9219-a8e90353c0b7.png)

## Remote (HCM/HN)

# 2,000 - 2,500 USD

## Requirements
* Your background is less important than the key skills, which might include:

* Great communication and articulation skills (English).
* ReactJS/NextJS framework (SSR – good to have an understanding on server-side rendering).
* Good understanding of functional components, React hooks and React lifecycle.
* Good understanding of React debugging tools and optimizing for best performance.
* Worked with common JS libraries such as dayjs, Immutable.js.
* Good understanding of data management tools such a React context and redux.
* Experience building reusable components and libraries for multi-project use.
* Worked with UI libraries such as Chakra UI, material UI and Tailwind CSS.
* Cross-Browser Compatibility and Multi-Device knowledge.
* Worked with codebase written in Typescript.
* The ability to think quickly and integrate 3 rd party APIs like stripe, acuity and many more.
* Good with versioning tools such as Git.
* Worked with deploying CI/CD pipelines and writing automation scripts to improve the build process.
* Deploy libraries/packages to NPM and use them as submodules.
* A good understanding and have developed projects in serverless architecture.
* Worked with serverless function providers such as AWS Lambda or Google Cloud Functions with frameworks such as ExpressJs and NestJS.
* Understands the microservice architecture. 
* Worked with ORMs such as Typeform.
* Worked with PostgreSQL.
* Worked with Firebase firestore and authentication.
* Integrate front-end communication with the backend through internal APIs and 3 rd party external SDKs.
* Good eye for translating designs into modular components structure for multiple projects.
* Familiar with RESTful APIs.
* Good understanding of GraphQl.

## Responsibilities

* This is a full-time role and you will become the 12th full-time hire at their company. 
* The mission of our client is to provide men with a safe haven for all things men’s health, whether it’s making discreet, affordable and convenient alternatives to receiving treatment more accessible to men, or raising awareness and acceptance of some of the more private conditions that men may feel embarrassed about. 
* You’ll be involved in building the most ambitious digital healthcare platform in the region.  

## Why it would be awesome to work with us?
* You will be joining a young startup in a growth phase and you will also be working remotely (they don't intend to get an office anytime soon). This means a couple of things: 
* Flexible schedule. You will have a more flexible schedule but you will also have to be prepared to fight fires at odd hours when you least expect. 
* Pull your own weight. As employee #12, you make up 8.3% of our company. There'll be no hand-holding and they expect you to pull your own weight - like everyone else. 
* Things get messy. There's no sugarcoating this. Things are unstructured and processes might be lacking. They're not where they want to be but they're getting there. 
* You must be able to thrive in ambiguous situations (see point above). 
* You are willing to put in the time to get the most out of any opportunity.  

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
