### ISSUE TITLE
Splus Software - Python Developer (Django, ReactJS) - FT - HCM - Negotiable

### ISSUE THREAD

**Issue by Kieuly1708** [awesome-jobs/vietnam#2436]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

## Requirements

* Bachelor’s degree in Computer Science Engineering or other related courses.
* Proven experience as a Python developer.
* At least 6 month experience in Python programming and other relevant frameworks like Django
(Accept for INTERN)
* Have experience with ReactJS and SQL
* Good knowledge of Object-relation mapping.
* Good understanding of server-side logic and server-side languages.
* Familiarity with various testing tools.
* Knowledge of integrating various data sources in a single application.
* Good teamwork spirit and capability to work independently when needed.
* Having Japanese (N3) is advantage.

### Responsibilities

* Work in collaboration with the development team to understand the requirement and expectations
from the application.
* Write effective and scalable Python codes.
* Develop various back-end components.
* In collaboration with the front-end, developers integrate the user-facing components in the
application.
* Perform various tests and debug programs.
* Administer the working of the existing applications and improve its functionalities as needed.
* Implement various security solutions and data protection solutions.
* Asses feature request and prioritize them.
* Accommodate various data storage solutions

### Why it would be awesome to work with us

* Competitive salary package and specific benefits
* TET bonus from 1 to 2 month salary according to seniority, work results and business situation of the
company.
* The company pays (32%) the costs of social insurance, health insurance and unemployment
insurance for its employees.
* Performance review twice a year
* Annual holiday: 12 annual leave and Corporate Birthday 11/27
* Working in a dynamic and professional environment with many promotion opportunities.
* Receive benefits according to senority
* Being trained in foreign languages, sponsored to learn certificates to improve professional skills and
soft skills.
* Lots of opportunities to go to Onsite at SPLUS JAPAN (for staff with Japanese proficiency from N3
and above)
* Sports activities: Football
* Annual company trip, teambuilding, birthdays for employees in the month and special events of the
year (March 8, October 20, Mid-Autumn Festival, Christmas ...).

### Contact

Homepage: https://www.splus-software.com.vn/
Kindly, send your CV via mail: lykty@splus-software.com.vn or contact me via Skype: kieuly1708 for more information
Title: [Position - Your Name]

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
