### ISSUE TITLE
[JobSeekervn] Senior Magento Developer - Fulltime - Saigon

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2439]
## Location

* Saigon, Vietnam
* Full-time

## Requirements
*Minimum 6+ years of overall development experience
* Experience working on large scale projects deployments
* Magento 1 & 2 programming experience (certification is a plus)
* Web application development experience with PHP Frameworks (Symfony, Laravel, ...)
* Ability to interact with the product owner and work within the customer environment
* Fluent in English

### Responsibilities
* Contribute to large-scale digital project development (e-Commerce, OMS, PIM, CMS, Mobile, PWA, ...)
* Understand user stories and convert them into implementation tasks
* Identify, prioritize and execute tasks in the software development lifecycle
* Ensure code quality, best practices, and design patterns are implemented
* Create unit tests and continuously deliver the software (CI - DevOps, ...)
* Work in an agile environment (Scrum, Kaban, ...)
* Provide technical guidance and mentoring to junior developers

### Why it would be awesome to work with us
●  Competitive salary
●  13th month
●  Medical insurance
●  MacBook Pro
●  Certifications program
●  Friendly, dynamic, and open-minded environment
●  Performance review 2 times/ year.
●  Working Monday – Friday

### Contact
Email: nhiha@jobseeker.vn 
Skype: hahoainhi
My personal blog: http://nhiha.top/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
