### ISSUE TITLE
Apide Vietnam - Mid Ruby On Rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#244]
## A 100% foreign owned company

You are passionate about software development and doing it the right way? Awesome so are we, our customers deserve the best they can get!

You embrace changes and see it as a necessity in order to make great software? Yup so do we, and we love the agile approach!

Join Apide Vietnam as we set out on our mission to become the best software development company in Việt Nam!
## Location
- Saigon, Vietnam
## Salary Expectation
- $1000 - $1500/month
## Requirements
- Checking stories before starting on a  project
- Writing code and automated tests as  required
- Requirements analysis with  clients
- Tech breakdowns with the  team
- Using the app and manual  testing
- Deploying code, building  servers
- Working with other agencies to e.g. agree on APIs, comment on   designs
- End of project process (demos &  retrospectives)
## Skills
- Learning: Can get up to speed on new technologies quickly, and independently by using online resources
- Independence & collaboration: Can work individually or as part of a technical team depending on the project
- Communication: Can extract a clear set of requirements from a non­technical client through careful questioning, and communicate proficiently in English, both orally  and in writing
- Product design: Can adapt requirements to something technically feasible and commercially successful
- Databases: Can use MySQL and query the database directly using SQL, furthermore it’s an advantage to be familiar with MongoDB and other non­SQL databases
### Must Have
- Code: Can write Ruby (on Rails), 3-4 years of working experience
- Neo4j or at least some experience with MongoDB
- Have experience with test driven development
- APIs for mobile applications
- HTML5 and preferably experience with HAML
- Backoffice services using Sidekiq
- Automated testing
- Server configuration and deployment
- AngularJS
### Ideally
- Server: Can deploy to, and manage a Linux  box
- UX: Can create efficient user  flows
- Visuals: Can create visual  designs
- Scrum: Can write user stories, plan sprints, draw burndowns, and run   demos
- Training: Can train others through blogging, mentoring, and   presenting
- Knowledge about other programming languages + frameworks: Can program in PHP with a framework such as Symphony or C# with MVC   .NET
- Experience with WordPress customization such as theme   development
### You can receive
- Work in an amazing start-up company in Vietnam with very open and friendly working environment
- Develop "sense of ownership" of product company in an Out-sourcing company
### Contact
- Ms Mai Ngo - Recruiter: 01243 894 915 
- Skype: mai.ngo91
- Email: mai@apide.vn

**Comment by joneslee85** [comment]
@RecruiterMaiNgo thanks for posting with us. I would like to ask if you work for this company?

**Comment by RecruiterMaiNgo** [comment]
Yes, I do. We are a start-up company so I use my personal email instead at the moment. Thanks for your caring!

**Comment by joneslee85** [comment]
So you are no longer working for NIC?

**Comment by RecruiterMaiNgo** [comment]
Yep, I have just changed job recently. I didn't work for Headhunting company anymore. So I will highly appreciate if you could support to advertise this post to RoR Network.
Thanks so much!

**Comment by joneslee85** [comment]
@RecruiterMaiNgo 👍 , please update this post with the contact details of the CTO or CEO and it is ready to go

**Comment by RecruiterMaiNgo** [comment]
It's done. I'm wondering if you need me to add the CTO's phone number and Skype or not? As he is so busy and his time goes too fast these days so I'm afraid to share his detailed contact.

**Comment by joneslee85** [comment]
Email should be good.

**Comment by RecruiterMaiNgo** [comment]
Thanks so much!
