### ISSUE TITLE
CMC Global - RUBY ON RAILS - HCM/HN (Sing/HK project) - Fulltime

### ISSUE THREAD

**Issue by linhvuong313** [awesome-jobs/vietnam#2442]
## Location

* HCM/HN

## Salary Expectation

* 25,000,000 - 28,000,000 VND/month

## You’ll be responsible for

- Work with fellow engineers, product managers, and business owners in the team to ensure product requirements and timelines are feasible.
- Communicate with external stakeholders and ascertaining product requirements.
- Hold the team accountable for delivering high-quality code within schedule
- Be personally responsible for defining the team’s success metric and measure it daily.
- Build and maintain APIs exposed externally for businesses.
- Integrate with third-party APIs to enable local and global payments.
- Understand at least 2 different domains within your team and ensure that architectural requirements are well implemented

## Requirements

- Ruby on Rails (more than 2 years)
- 3 - 6 years of engineering experience. BS/MS Degree in any relevant major. (ex: IT, Computer Science, etc) OR Significant open source project contribution with adequate computer science fundamentals studies from online courses.
- An understanding of algorithms and data structures.
- Experience with a database management tool, MySQL preferred.
- Experience with building internal and external APIs is a plus.
- Have a good knowledge of Git.

## Skills

- Ruby on rails
- Good English (all 4 skills)

## Why it would be awesome to work with us

- Working in one of the Best Places to Work in Vietnam.
- Building large-scale & global software products for our clients.
- Working & growing with a Passionate & Talented Team.
- Diverse career opportunities with Software Outsourcing, Software Product Development, IT Solutions & Consulting.

### Attractive Salary and Benefits

- Monthly salary up to 1300 USD
- Performance appraisals every year.
- Onsite opportunities: short-term and long-term assignments in Europe, Asia.
- Premium healthcare insurance for you and your loved ones.
- Company trip, big annual year-end party, team building.
- Bonus on occasions like Company Anniversary, Corporation Anniversary, Vietnam National Day 
- Free in-house entertainment facilities, coffee (latte, cappuccino, espresso), and snacks (instant noodles, cookies, candies…)
- And much more, join us and let yourself explore other fantastic things!

### Contact
Mail: vmlinh@cmc.com.vn
Skype: linhvuong313

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
