### ISSUE TITLE
Ninja Van Tech Lab - Senior Software Engineer (Backend) - Go/ Nodejs/ Java

### ISSUE THREAD

**Issue by vickydiep1306** [awesome-jobs/vietnam#2444]
## Location

* District 10, HCMC
* Fulltime

## Salary Expectation

* up to $2500 gross

## Requirements
* 5+ years Software Engineering experience
* 3-6 years of backend development in a product company, with a proven track record of shipping successful software products.
* Deep experience in most of our tech stack or similar technologies. (Java/ NodeJS/ Golang)
* Solid Computer Science fundamentals, excellent problem-solving skills
* Good English communication

### Ideally

* Experience with Golang/ MySQL/ Reactjs

### Responsibilities

- Design, develop and maintain software that powers Ninja Van's complex logistics operations. 
- Help design the architecture, own development of major initiatives and modules. 
- Work in cross functional teams with product managers, UX designers and QA engineers to ship software on-quality and on-time.
- Help level up the team; share knowledge, conduct code and design review; drive code quality and process improvement initiatives. 
- Write code that you are proud of, with extensibility, scalability and performance in mind

### Why it would be awesome to work with us
Ninja Van is a late-stage logtech startup that is disrupting a massive industry with innovation and cutting edge technology. Launched 2014 in Singapore, we have grown rapidly to become one of Southeast Asia's largest and fastest-growing express logistics companies. Since our inception, we’ve delivered to 100 million different customers across the region with added predictability, flexibility and convenience. Join us in our mission to connect shippers and shoppers across Southeast Asia to a world of new possibilities. 

More about us: 
- We process 250 million API requests and 3TB of data every day.
- We deliver more than 1.5 million parcels every day.
- 100% network coverage with 1000+ hubs and stations in 6 SEA markets (Singapore, Malaysia, Indonesia, Thailand, Vietnam and Philippines), reaching 500 million consumers.
- 600,000 active shippers in all e-commerce segments, from the largest marketplaces to the individual social commerce sellers.
- Raised US$400 million over four rounds.

### Benefits:

- Flexible working time and environment
- SHUI contributed based on gross salary
- Health insurance allowance
- 13th month salary
- Performance bonus up to 4 months salary
- Learning and development opportunity

### Contact
Homepage: https://www.ninjavan.co/
Trollman: vicky.diep@ninjavan.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
