### ISSUE TITLE
Ninja Van Tech Lab - Software Engineering Manager 

### ISSUE THREAD

**Issue by vickydiep1306** [awesome-jobs/vietnam#2445]
## Location

* District 10, HCMC

## Salary Expectation

* Negotiable 

## Requirements

- At least 5 years of software development experience, preferably in horizontally scalable services in a cloud environment.
- At least 2 years of managing an elite engineering team with multiple release cycles under your belt.
- Proven ability to recruit, develop and retain talent.
- Steeped in Agile ways. Deep knowledge of software engineering best practices; burning desire to drive the team to adopt them.
- Highly adept at project management in a demanding fast-changing environment with tight deadlines and scarce resources. Ability to multi-task is key.
- Bachelor’s or Master’s degree in Computer Science or related field from a top university.

### Ideally

* Experience with managing a team of 10-13 members
* Experience with DevOps, infrastructure will be a plus

### Responsibilities

- Manage and develop a team of world-class engineers to keep them motivated, grow their technical expertise and meet their career aspirations. 
- Spend about half your time on hands-on technical work, including coding.
- Manage projects end to end in a fast-paced Agile environment to deliver quality software on time, and follow through post-release to ensure effective usage.
- Partner with business owners and product managers to help shape product strategy, sharpen product specs and come up with innovative solutions. 
- Drive continual process improvements in areas like unit test, code review, static analysis, CI, CD

### Why it would be awesome to work with us
Ninja Van is a late-stage logtech startup that is disrupting a massive industry with innovation and cutting-edge technology. Launched in 2014 in Singapore, we have grown rapidly to become one of Southeast Asia's largest and fastest-growing express logistics companies. Since our inception, we’ve delivered to 100 million different customers across the region with added predictability, flexibility, and convenience. Join us in our mission to connect shippers and shoppers across Southeast Asia to a world of new possibilities. 

More about us: 
- We process 250 million API requests and 3TB of data every day.
- We deliver more than 1.5 million parcels every day.
- 100% network coverage with 1000+ hubs and stations in 6 SEA markets (Singapore, Malaysia, Indonesia, Thailand, Vietnam, and Philippines), reaching 500 million consumers.
- 600,000 active shippers in all e-commerce segments, from the largest marketplaces to individual social commerce sellers.
- Raised US$400 million over four rounds.

### Benefits

- Flexible working time and environment
- SHUI contributed based on gross salary
- Health insurance allowance
- 13th-month salary
- Performance bonus up to 4 months salary
- Learning and development opportunity

### Contact
Homepage: https://www.ninjavan.co/
Trollman: vicky.diep@ninjavan.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
