### ISSUE TITLE
FETCH TECHNOLOGY - SENIOR IOS DEVELOPER - HCM - FT 

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2446]
![image](https://user-images.githubusercontent.com/60914247/116364546-7e8c0680-a82e-11eb-9493-d70fb44b4bb5.png)

## HCM
# 1,000 - 2,500 USD
## Requirements
* Advanced knowledge (at least 3 years of experience) in mobile development with Swift.
* Experience in developing high-performing mobile applications: client-server application, fast and highly responsive.
* Strong OOP knowledge. Familiar with Unit-testing and best practices in software development.
* Be able to perform individually as well as in a team.
* Have a strong sense of ownership, be open-minded, and eager to learn and share.
* Excellent analytical, problem-solving, code optimization, code organization and debugging skills.
* Strong English communication skills.
* Deep understanding of storyboard, auto-layout, constraint, content hugging, compression resistance priorities.
* Have experience with Firebase will be a plus.

## Responsibilities
* Design and build advanced applications for the iOS platform.
* Collaborate with cross-functional teams to define, design, and ship new features.
* Work with outside data sources and API’s.
* Unit-test code for robustness, including edge cases, usability, and general reliability.
* Assist in automation test setup and testing protocol.
* Work on bug fixing and improving application performance.
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

## Why it would be awesome to work with us?
Being a Senior iOS Developer at this company, you will experience a youthful, flexible and creative work environment:

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snacks, Weekly and Monthly Team-building, Company trips, Play Games (PlayStation, Board games), Play Sport (Football, Badminton...).
## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by Jesse111-flyaway** [comment]
Bên e cần 3 Senior IOS Developer nhé mọi người ơi

**Comment by Jesse111-flyaway** [comment]
Em vẫn đang tuyển job này ạ

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
