### ISSUE TITLE
FETCH TECHNOLOGY - SENIOR ANDROID DEVELOPER - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2447]
![image](https://user-images.githubusercontent.com/60914247/116364988-0114c600-a82f-11eb-96cc-ac3c43e4124d.png)

## HCM
# 1,000 - 2,500 USD

## Requirements
* At least 3 years of native Android app development experience for seniors. 
* A degree in computer science, software engineering, information technology, or related fields. 
* Strong CS fundamentals (with competencies in algorithms and data structures). 
* Strong UX/UI design exposure and experience in making apps work intuitively and with pixel-perfect interfaces. 
* Experience in API design, SDK architecture, and mobile software lifecycle development practices. 
* Proficient in Java, Kotlin with experience in memory management and caching mechanisms specific to mobile devices. 
* Highly accountable and takes ownership, with a collaborative attitude, and a lifelong learner

## Responsibilities
* Analyze, Design, Develop and Test applications for the Android platform.
* Ensure the performance, quality, and responsiveness of applications.
* Build beautiful and highly functional user interfaces.
* Work with the product team to set relevant standards that will be used by all teams.
## Why it would be awesome to work with us

Being a Senior Android Developer at this company, you will experience a youthful, flexible and creative work environment: 

* Attractive salary and annual salary review.
* MacBook for work.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese. 
* Working directly with foreign clients, all your dedication to work will be fairly recognized for performance review. 
* With extensive on job training, you will always have a chance to work with new emerging technologies. 
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law. 
* 12-day annual leave per year. 
* 13th-month salary. 
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play games (PlayStation, CS Go), Play Sport (Football, Badminton...).
## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by Jesse111-flyaway** [comment]
Job này bên e cần 6 Senior Android Developer ạ

**Comment by Jesse111-flyaway** [comment]
Em vẫn đang tuyển nhé mọi người ơi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
