### ISSUE TITLE
A Finland Product Company - Frontend Engineer - ReactJS/VueJS

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#2448]
## Location

* Remote

## Salary Expectation

* 2,000 - 2,500 USD Gross

## Requirements
* 5+ years of experience in software engineering and frontend development
* High level of knowledge about web applications and web standards.
* Strong experience with React or Vue.js and HTML/CSS
* Strong understanding of REST APIs
* Experience with AWS or some other cloud provider
* Experience with Docker
* Experience with npm
* Experience with Bootstrap 4
* Experience with building UI tests
* Familiar with UI design, ability to build simple frontend features without graphics by mimicking existing designs
* Have eye for design/UI and UX (we’ll ask for examples)
* Experience with Adobe Illustrator / Sketch / other graphic design tool
* Basic understanding of the Gitflow principle
* Basic understanding of web backend systems
* Outstanding communication and team work skills
* Good at English

### Responsibilities

* Design and implement frontend features with Vue.js
* Work together with product team, backend team and API development to define best solution for requested features
* Maintain and improve UI framework (a custom Bootstrap 4 theme)
* Deploy new frontend versions to AWS

### Why it would be awesome to work with us
* A key role in high growth startup with the possibility to change how real estate market works
* A lot of freedom and flexibility to organize your work day as you wish
* Possibility to learn new skills related to your job
* To build a new product from scratch
* International development team

### Contact
* Homepage: LinkJD: https://ikonnectvn.com/detail/11
* Email: tran@ikonnectvn.com
* Skype: tran.ngo.161 (Ms. Trân)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
