### ISSUE TITLE
8Bit Rockstars - Key Account Manager - Saigon - FT

### ISSUE THREAD

**Issue by 8BIT-ROCKSTARS** [awesome-jobs/vietnam#245]
![8BR](http://8bitrockr.com/img/logo_w.png)
# 8 BIT ROCKSTARS
Floor 8th, Vincom B, 72 Le Thanh Ton, Ben Nghe Ward, Dist.1, HCMC
http://8bitrockr.com/
hr@8bitrockr.com

Email CV to **_hr@8bitrockr.com_**

## Salary

**_VERY ATTRACTIVE & NEGOTIABLE_**

## Job Description

We are looking for a **KEY ACCOUNT MANAGER**, who would love to build "win-win-win" situations between our teams, clients and the goals of our company. This is an excellent opportunity to gain experience, deliver happiness, and push your boundaries.

In this role, you will work directly with international clients to scale their teams or help selling them our expertise. Other duties might be: deliver reports, help solving issues with the local team, quality management, help implement process to create transparency, and last but not least make our international clients happy and show them how much fun Ho Chi Minh city can be.

**You will have responsibility for:**
- _Collaborate_ with our clients/partners internationally
- _Work closely_ with the project team to:
  - _Maintain_ a continuous knowledge of project status
  - _Identify_ potential issues and/or opportunities within or related to the project
  - _Take responsibility_ for the overall project management and proactively _advise_ clients on the best solutions for a successful project
- _Ensure_ that all processes and procedures are completed, quality standards are met, and that projects are profitable
- _Coordination and creation_ of processes with our clients
- _Maintenance_ of developer teams
- _Build_ and _grow relationship_ between the developers and the clients
- Make sure that visiting customers have an extraordinary experience and help them to _embrace_ the Vietnamese culture

## Requirement 

- **At least 3 years of experience** in similar position in agency
- **Excellent client service skills** to develop business with new clients and current accounts
- **Perfect communication and negotiation skills**
- **Fluent English** (speaking and written).
- **Excellent organizational and time management skills**
- **Troubleshooting and solution-finding skills**
- Ambitious, empathy, tenacious, systematic, innovative and insightful, responsibility and accuracy.
- Capability to accomplish impossible missions
- Great sense of humor
- _Western mindset/attitude is a plus_

## Benefits:

- Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things
- Attractive, **competitive salary** and incentives
- Year-end **bonus** (13th month salary ++)
- 40 hour work weeks (9:00-18:00, Mon-Fri)
- **15 days** of vacation per year
- **Probation** with **100% of salary**
- Performance and **salary review** every **6 months**
- **International Medical Insurance** will be paid by the company
- **English Class** with foreigner 3 times a week.
- New **Technologies Club** every week
- Quarterly **rockstar Hackathon** with the Best prizes
- Short and long-term **international training** / work
- **Company trip** (local or internationally) every year
- **Team building events**, party monthly and much more
- **Entertainment Zone** for all members with full media in the company (game, music, TV…).
- Enjoy **Relax and Coffee Bar** in the company.

Drop your CV to: **_hr@8bitrockr.com_** and we will be in touch with you shortly!

**Comment by huydx** [comment]
hi @8BIT-ROCKSTARS , unfortunately we are supporting technical job only :). It's not only about policy, it's also about posting non-technical job here will have really bad performance IMHO. So we will close this JD.
