### ISSUE TITLE
KYANON DIGITAL - Frontend Developer (HTML/CSS/JS) - HCM - FT

### ISSUE THREAD

**Issue by dung-thao** [awesome-jobs/vietnam#2454]
### **Location**
Kyanon Production House, Saigon, Vietnam

### **Salary Expectation**
* $1500 Net/month

### **Requirements**
-  At least 2+ years of experience.
- Hands-on experience in HTML5, CSS3, JavaScript (jQuery), PugJS, SCSS, 
- Hands-on experience in CMS: WordPress / Drupal 
- Knowledge of converting a design from Photoshop/AI/XD/Sketch/Figma to HTML/CSS 
- Familiar with bug tracking systems: Jira / Redmine / Mantis is a plus 
- Reading technical document skill in English

### **Skills**
* CSS3, HTML5, JQUERY

### Must Have
- Technology-savvy.
- Time management skills.
- Basic English Skills in Reading technical documents.

### **Responsibilities**
- Great power comes with great responsibilities!

### **Why it would be awesome to work with us**
- Bonus structure + 13th month Bonus.
- Flexible working time: only 8 hours required as continual working-time at the office.
- 12 days Annual leave.
- Coffee and snacks provided.
- Holiday celebrations and parties for team members and family.
- Company trip, team building activities.

### **Interesting engineering projects**
- Experience working as a member of a small agile software development team, e.g. participating in planning sessions and interpreting user stories, doing code reviews, pair programming.
- Improve English skills. 
- Have a chance to study new technology, new domain through workshops, seminars, and conferences.

### Contact
Homepage: https://kyanon.digital/
Mail: career@kyanon.digital (0967.457.491 - Ms.Dung)

**Comment by dung-thao** [comment]
our job stil openning

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
