### ISSUE TITLE
[FMG Suite] - Senior Fullstack Node - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by lucasjans** [awesome-jobs/vietnam#2458]
## Location

* Saigon, Vietnam
* Flexible work options

## Salary Expectation

* $2,000 to $3,500 a month

## Requirements
- Strong communication in English
 - NodeJS (Webpack & Gulp) and ReactJS
 - Familiar with C# .NET Core a plus
- NoSQL (such as RethinkDB, MongoDB, DynamoDB, CosmosDB) is required
- SQL experience is a plus
- Experience with Google Cloud Platform or AWS is a big plus
- Experience with REST API, microservices model is required, experience with Redis is a plus
- Experience with Git and continuous deployment

## Responsibilities

- Work in a product company and use the latest technologies, such as microservices, Node, .NET Core, React and Golang
- Analyze, design, code, test, document, and development for solutions used by 25,000+ business users every month
- Provide maintenance and support for existing developed functionalities
- Developing high-performance applications by writing testable, reusable, and efficient code

### FMG Suite Backstory

We’re a marketing software company that serves small business owners, primarily financial advisors, and insurance agents in the United States. Most of our team is in the US, and we have a small product engineering center in Ho Chi Minh city.

About 25,000 small businesses use our tools and send out our content. Generally, these businesses don’t have marketing departments but are growth-minded enough to know they need to market themselves. Our software helps them do just that. We automate email and social campaigns to drive traffic back to their websites, helping them build better relationships with their customers with less hands-on effort.

We are focused on culture and investing in opportunities where our teams are able to grow professionally and inspire one another. We are very results-oriented with a bias to action. We value humility and a team-first, company-first approach and are willing to laugh at ourselves. We acknowledge that our people are the greatest assets and we make sure to provide our talent with an exciting job and work-life balance.

## Benefits

- Premium healthcare insurance provided by Pacific Cross for you and your spouse (husband or wife) with an annual medical check
- Attractive salary with 13th-month salary
- Flexible working hours (40h/week) with optional work-from-home 2 days per week
- Up to 28 paid leaves per year (12 annual leaves, 10 national holidays, 5 sick leaves, 1 birthday leave)
- Additional times off for long-time and senior positions
- Full benefits for employees according to the Vietnam Labor Laws: social, health, unemployment insurance

## Others

- Modern office located in D. 7
- Provided high settings laptop for working plus 2 high definition monitors
- Mechanical keyboard by choice ⌨️⌨️
- 100% salary during probation
- Working with cutting edge technologies
- ✈️✈️ Annual company trip
- Quarterly Team Building Activity

## About Me

I moved to Vietnam in 2014 to build a team and start Agency Revolution, a marketing automation SaaS company. I love Vietnam and can't imagine leaving. We joined forces with FMG Suite in 2017 and now I run the growing Vietnam office for the company. We have engineers in Europe, Brazil and our HQ is in the US.

### To apply, contact
hoang.tran@fmgsuite.com or lucas.jans@fmgsuite.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
