### ISSUE TITLE
 [Fiahub Exchange] - Senior IOS/ Android - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by bdthinh** [awesome-jobs/vietnam#2459]
## Location

* Saigon, Vietnam
* Flexible time

## Salary Expectation

* 2000$ - 2500$ a month

## Requirements
* Background in computer science with at least 1 year experience in software development, strong knowledge in data structure and algorithm.
* Familiar with Swift if you are IOS developer; Falimiar with Kotlin if you are Android developer
* Experience with REST API, microservices model is required
* SQL experience
* Experience with Google Cloud Platform or AWS is a big plus
* Experience with Git and continuous deployment

### Ideally

* Experience with whole state of the art in your mobile development stack

### Responsibilities

* Write quality and maintainable code as well as their corresponding unit tests.
* Self-managed, able to come up solution for technical problem, you are usually handle end-to-end for a feature: discussion, design, implementation
* Maintain and refactor the existing code base
* Provide support to the Customer Support team to debug/fix issues faced by customers.
* Occasionally perform manual testing and write documentation.
* Great power comes with great responsibilities!

### You’ll be responsible for

* Building a top fiat-cryptocurrency exchange heading to a bridge of new money in blockchain era

### Others
* Modern office located in Thao Dien, D. 2
* Provided high settings laptop and monitors
* 100% salary during probation
* Working with explosive technologies
* Annual company trip
* Half year review

### Why it would be awesome to work with us
* We are young, lean, and strong team which is proven by the market
* We are toward to world-class product which serve million of people to adapt blockchain into real life

### Contact
* Please contact to docs@fiahub.com and have chat after that

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
