### ISSUE TITLE
[Money Forward Vietnam] - Software Engineer (Frontend - VueJs) - HCMC

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2462]
## Location
Etown Central Building, 11, Doan Van Bo, District 4, Ho Chi Minh City

## Salary Expectation
* Very attractive

## Requirements
**Must have**
- 2+ years experience in the frontend (e.g., React.js, Vue.js)
- Have good UI-skills (e.g., HTML, CSS)
- Experience with organizing CSS (e.g. BEM)

**Nice to have**
- Experience with the web framework (e.g., Ruby on Rails, Laravel, Express.js, django)
- Motivation to learn new programming languages
- Experience with the testing framework (e.g., Jest, Mocha, Ava)
- Experience with Amazon Web Services

### Responsibilities
* Keep our services well maintained
* Improve user experience

### Why it would be awesome to work with us
- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

### Contact
Mail: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
