### ISSUE TITLE
JobSeekervn - Senior Front-end Developer (ReactJS/Typescript)- Ha Noi

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2463]
## Location
* Hà Nội, Việt Nam
* Full-time

## Salary Expectation
* $1800 - $2400 

## Requirements
* Strong agile mindset, someone who is able to iterate fast and give early feedback
* Proven experience with React JS, TypeScript and Redux: redux-observable
* Strong knowledge of styling: CSS, SCSS, Material-UI framework for React
* Proven experience with applying design patterns
* Understanding of best practices to optimize code quality and web performance
* Strong communication skills in English - asking questions when needed and sharing
your knowledge and learnings

### Responsibilities
* You will contribute to building new product lines and features for our web
applications as well as improving and maintaining the quality of the entire front-end
codebase
* You will participate in the full product lifecycle: planning, conception, development,
testing, customer feedback, and iteration
* You will proactively suggest improvements across the whole front-end stack
* You will help maintain our web application tech stack: React JS, TypeScript, Redux,
CSS, SCSS, NPM and whatever else is required to get the job done

### Why it would be awesome to work with us
* Health Insurance
* Performance-based quarterly bonus
* 13th month salary
* Annual leave: 15 days/year
* Sick leave: 5 days/year
* National holidays leave
* On-site opportunity (United States)

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
