### ISSUE TITLE
[Groove Technology] Senior Fullstack .NET Developer - HCMC 

### ISSUE THREAD

**Issue by QuynhNguyen14** [awesome-jobs/vietnam#2467]
## Location

* Q1, HCM, Vietnam
* Fulltime 

## Requirements

- 4+ years working as an Engineer delivering projects using the Microsoft stack.
- Experience creating, maintaining, optimizing and writing queries for MS SQL.
- Experience using an ORM library such as Entity Framework or nHibernate.
- Experience using various dependency injection frameworks such as Ninject, Autofac, Unity, Spring etc.
- Experience building and integrating with RESTful web services built using WebApi.
- Experience with the ASP.net MVC
- Client-side experience using JavaScript and JavaScript libraries.
- Experience with Angular 2+, React.JS or similar on the client side.
- Experience with Bootstrap or similar CSS
- Experience with source control systems such as SVN or GIT.

### Must Have

Soft skills:

- Troubleshooting
- Critical thinking, creativity, and problem-solving
- Team work

### You’ll be responsible for

- Report to the Project Manager and Tech Lead.
- Work directly with foreign software engineers in AU and UK.
- Liais with the key stakeholders of the project.
- Deliver fully implemented vertical feature sets based on the specification within estimates and without defects.
- Identify and mitigate risk in the project’s implementation.
- Participate in code reviews.
- Designand optimize tables and queries for MS SQL Server.
- Lead and mentor less senior members of the team.

###Why you’ll love working here?

- 13th-month salary and 14 annual leave.
- Medical and Accident Insurance program.
- International, dynamic, friendly working environment.
- Clear and stable career growth.
- Many opportunities for personal and professional development.
- Professional training.
- Company trip and regular team building events, sport activities…

### Contact
Email: quynh.nguyen@groovetechnology.com 
Skype: nhuquynh1495@outlook.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
