### ISSUE TITLE
[Money Forward Vietnam] - Ruby on Rails - HCMC

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2470]
## Location
* 21Fl, ETown Central Building, 11 Doan Van Bo, District 4, Ho Chi Minh

## Salary Expectation
* Very attractive

## Requirements
- 2 year experience in Backend (Ruby, Rails)
- You will do a Ruby coding challenge

**Must have:**
- Experience with Ruby on Rails
- Experience with MySQL or PostgreSQL
- Motivation to learn new programming languages and techniques
- Ability to communicate in English

**Nice to have**
- Familiarity with unit test in RailsExperience with frontend development (ReactJS, VueJS, jQuery)
- Experience with Amazon Web Service

### Responsibilities
- Design and develop services
- Design database schema
- Write clean and maintainable code
- Discuss system/software architecture with team
- Train junior/middle software engineers

### You’ll be responsible for
- Building a financial platform for all

### Why it would be awesome to work with us
- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

### Contact
Mail: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
