### ISSUE TITLE
[Money Forward Vietnam] - Software Engineer (Golang) - HCMC

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2471]
## Location
* Ho Chi Minh City

## Salary Expectation

* Very competitive

## Requirements
**Must Have**
- 2+ years of Golang experience
- Experience in reviewing code
- Experience in writing good unit tests

**Ideally**
- Experience with frontend development (ReactJS, VueJS, jQuery)
- Can communicate in English

## Responsibilities
- Develop and design service
- Design database schema
- Write clean and maintainable code
- Discuss and debate with other team members to find optimal solutions

## Why it would be awesome to work with us
- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

## Contact
Mail: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
