### ISSUE TITLE
[Hanoi] Front-End Web App Developer - MIRAWAY

### ISSUE THREAD

**Issue by hongloc5998** [awesome-jobs/vietnam#2473]
## Location

> **Tầng 5 - Tòa nhà Cục Bản Đồ, Số 14 Pháo Đài Láng, Phường Láng Thượng, Quận Đống Đa, Thành phố Hà Nội**
* Full-time

## What You’re In Charge?

* Tham gia phát triển các sản phẩm và chịu trách nhiệm phát triển về Front End cho các ứng dụng nền Web và di động với HTML/CSS, JavaScript, sử dụng các framework/thư viện như Angular, Bootstrap…
* Thực hiện việc chuyển đổi sang HTML5/CSS3 & Javascript từ PSD theo chuẩn W3C.
* Phân tích, xem xét, phản hồi cho các yêu cầu và thiết kế sản phẩm.
* Xây dựng các thành phần (component) có thể tái sử dụng trong tương lai.
* Nghiên cứu và áp dụng các công nghệ mới để tối đa hóa hiệu quả phát triển sản phẩm.

## What We’re Searching?
* Ít nhất 2 năm kinh nghiệm lập trình trong Frontend development (HTML5 / CSS3 / JavaScript). Ưu tiên các ứng viên có kinh nghiệm quản lý và xây dựng team.
* Có kinh nghiệm làm việc với Restful API, Websocket.
* Ưu tiên các ứng viên có kinh nhiệm sử dụng các JavaScript Libraries/Frameworks như Angular hoặc các Frontend Developer Tools (Webpack, npm, bower, grunt…).
* Đam mê và nhiệt huyết trong việc xây dựng các sản phẩm có chất lượng cao.

##       Best About This Position
* Mức lương, thưởng cạnh tranh, phù hợp với năng lực.
* Công ty có chính sách thưởng lương tháng 13, thưởng theo dự án dựa trên kết quả đánh giá KPI và hiệu suất công việc.
* Môi trường làm việc năng động, chuyên nghiệp, trẻ trung và vui vẻ.
* Được làm việc với các khách hàng, đối tác trong và ngoài nước.
* Được tiếp cận với những công nghệ mới.

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
