### ISSUE TITLE
Front-end ReactJS & React Native Dev

### ISSUE THREAD

**Issue by katy-le** [awesome-jobs/vietnam#2479]
## Location

* The Hive Villa, District 2, HCMC, Vietnam
* Full-time

## Salary

* **$1000 - $2200**

## Job Overview
Avian Jets is looking to expand its team with a front-end developer to work as the right hand of the current lead developer. All products of Avian Jets is created in-house and needs an extra hand to keep on track with our set roadmap.

Once hired, you will be working with teams around the world. Therefore, fluency in English (speaking and writing) is a must. As you’ll be working as a team, it’s important to be a team player, easy to work with and keep a positive spirit amongst other team members.

## Requirements

* You know ReactJS or React Native, JavaScript, ES6+, React Hooks.
* At least 3 years of proven knowledge (portfolio) as a developer.
* Fluent English.
* Experience with RESTful services, Redux, HTML, CSS, SASS/LESS.
* You are familiar with native build tools such as, XCode, Android Studio, third-party dependencies and debugging dependency conflicts.
* Experience with unit tests, test-driven development, code coverage, testing frameworks and refactoring code
AGILE.

### You’ll love working with us if you are:
* Passionate about technology
* Independent but also a good team player
* Product mindset
* Strong willingness to learn new practices and technologies
* Keen on presenting your ideas to your peers and management

## You’ll be responsible for

* Develop technical documents and handbooks to accurately represent application design and code.
* Convert ideas to great designs.
* Write quality code to build complete webpages within deadlines.
* Collaborate with the team to define the specifications for new features.

## Why it would be awesome to work with us
* Competitive salary.
* **Full benefits and salary rank during probation**.
* Macbook Pro is provided & free coffee.
* Work-life balance 40-hr per week from Mon to Fri.
* 12-day annual + 3-day sick leave per year.
* Be part of an international team to build a product that will disrupt the Private Aviation Industry.

## Contact
Homepage: [avianjets.com](avianjets.com)
Email: hai@avianjets.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
