### ISSUE TITLE
Reeting Internet - Senior iOS Developer - Saigon - FT

### ISSUE THREAD

**Issue by mylinh2607** [awesome-jobs/vietnam#248]
Reeting is a trusted online marketplace for people to list, discover, and rent accommodations. Reeting is the easiest way to connect apartment hunters and home owners. Utilising our rich and accurate apartment database, Reeting makes the process of listing or booking appointments with landlords effortless and efficient. 
With our unique management and analysis tools for homeowners, Reeting offers the widest variety of insights into the current real estate market as well as your business' growth.

## Location

* Saigon, Vietnam

## Salary Expectation
* Negotiable

## Requirements
* Minimum 2 years of experience in iOS mobile app development (a Bachelor’s in Computer Science or Master’s is a plus)
* Background on creating consumer facing software, online services, social network, is a plus
* Excellent debugging skill.
* Experience in OOP design patterns
* Fluency Objective-C experience is a must
* Strong experience Core Graphics and Cocoa Touch experience is a plus
* Mobile web development, excellent mobile sensibilities and agile experience is a plus
* Proficient in English reading and speaking skills.
* Excellent communication skills, both verbal and written
* Good time management skills.
* Excellent organization skills

### Responsibilities

* Managing requirements
* Prepare reports for the Product Manager on the performance of each project.
* Developing code alone or with other team
* Ensuring code quality and bug fixing
* Unit test and integration test
* Documenting key aspects of the system
* Tutoring junior developers

Attributes
* Energetic and self-motivated.
* Honest and trustworthy.

### Contact
Please send your CV to Charlie Do at charlie.do@reeting.com

**Comment by phucnm** [comment]
This requirement `Minimum 2 years of experience in native Android mobile app development` when you are hiring an iOS position ?

**Comment by huydx** [comment]
@mylinh2607 do review your JD, or we have to close it.

**Comment by joneslee85** [comment]
@mylinh2607 I am closing this post because I have not received any response from you.
