### ISSUE TITLE
[HCMC] Mobile Developer (React Native)

### ISSUE THREAD

**Issue by esp-dqtran** [awesome-jobs/vietnam#2481]
## Job overview
Eastplayers is a rising star in E-com Tech & Outsourcing companies from Vietnam. We are a proudly Made-in-Vietnam start-up. We are not experts at technical. **We play technical!** We’re now looking for a **true Player** to join the battle. This person should possess an intense passion for technology & constantly challenge and exceed their comfort zone. In another word, **this person must be a real fighter!**

## Location
Block Iris 2, Hado Centrosa Garden, 3/2 Street, Ward 12, District 10, HCMC

## Salary Expectation
Up to 1200$/month

## Requirements
- 1+ years of experience on the React Native
- Understand practices for high code quality: maintainability, reusability, code reviewing, unit testing, etc.
- You write well-tested code with good unit tests and technical documents
- Desire to continue learning and improving
- Experience working with SQL or NoSQL databases
- Good Linux/Unix/Mac experience
- Good skills of English

### Ideally
- You have experience in Nodejs
- Have experience in Objective-C/Swift iOS or Java Android programming
- You have experience in Microservices
- You have knowledge of Docker, CI/CD
- You keep up to speed with latest technologies

### Responsibilities
- Develop features and enhancements on existing products based on defined requirements and designs
- Follow given procedures and instructions to produce well-designed, testable, and clean code
- Participate in numerous activities for building software product: requirement analysis / enhance UI-UX design / Scrum process/customer support / improve DevOps infrastructure / …
- Actively contribute ideas and efforts to product success
- Work alongside with other engineers in teams to promote technology and ensure consistency in accordance with industry best practices.
- Provide recommendations for continuous improvement.
- Self-driven individual to work independently, yet collaboration as a team member to reach a collective team goal.

### Why it would be awesome to work with us
- Yearly Awards for excellent employees
- 13th month salary
- 10 public holidays, 12 annual leave days based on Vietnam Government regulations
- Company sponsored activities such as sports, dining/drinking

### Contact
Homepage: https://eastplayers.io/
Email: hr@eastplayers.io
Phone: 070 313 2822

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
