### ISSUE TITLE
[HCMC] Backend Developer (PHP)

### ISSUE THREAD

**Issue by esp-dqtran** [awesome-jobs/vietnam#2482]
## Job overview
Eastplayers is a rising star in E-com Tech & Outsourcing companies from Vietnam. We are a proudly Made-in-Vietnam start-up. We are not experts at technical. **We play technical!** We’re now looking for a **true Player** to join the battle. This person should possess an intense passion for technology & constantly challenge and exceed their comfort zone. In another word, **this person must be a real fighter!**

## Location
Block Iris 2, Hado Centrosa Garden, 3/2 Street, Ward 12, District 10, HCMC

## Salary Expectation
Up to 1200$/month

## Requirements
- Previous working experience as a PHP / Laravel developer for 2+ years
- In depth knowledge of object-oriented PHP and Laravel 5+ PHP Framework
- Hands on experience with SQL schema design, SOLID principles, REST API design
- Software testing (PHPUnit, PHPSpec, Behat)
- MySQL profiling and query optimization
- Creative and efficient problem solver
- Desire to continue learning and improving
- Experience working with SQL or NoSQL databases
- Good Linux/Unix/Mac experience
- Good skills of English

### Ideally
- You have experience in unit test
- You have experience in Microservices
- You have knowledge of Docker, CI/CD
- You keep up to speed with latest technologies

### Responsibilities
- Gather the requirements and provide sound solutions for the requirements.
- GUI development by utilization of new front-end technologies (SPA and PWA).
- Write efficient and stable code in support for the backend API.
- Work alongside with other engineers in teams to promote technology and ensure consistency in accordance with industry best practices.
- Provide recommendations for continuous improvement.
- Self-driven individual to work independently, yet collaboration as a team member to reach a collective team goal.

### Why it would be awesome to work with us
- Yearly Awards for excellent employees
- 13th month salary
- 10 public holidays, 12 annual leave days based on Vietnam Government regulations
- Company sponsored activities such as sports, dining/drinking

### Contact
Homepage: https://eastplayers.io/
Email: hr@eastplayers.io
Phone: 070 313 2822

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
