### ISSUE TITLE
[Cubicstack Solutions] - [QA QC Engineer] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by CubicstackSolutions** [awesome-jobs/vietnam#2484]
## Location

* Saigon, Vietnam

## Salary Expectation

* $700 to $1,200/month 

## Requirements

* Understand business requirements to design quality assurance and testing strategies
* Innovate testing tools, testing technologies, testing platform, testing life cycle of product R&D, improve the
testing efficiency
* Perform UI testing on different browsers like Chrome, Edge, Firefox, mobile browsers.
* Perform UI testing on native apps
* Perform API testing using Postman tools

### Must Have
* Minimum 3+ years of relevant experience.
* Strong analysis and design skills, capable to develop testing framework and integrate solutions
* Familiar with Cucumber BDD framework.
* Self-taught and open-minded candidates are highly encouraged
* Familiar with automation test tools (Selenium) is a plus

### Ideally
Good English fluency and communication skills is a plus
Product driven mindset with an eagerness to learn and apply new technologies
Experience with projects implemented automation test

### Why it would be awesome to work with us
● Attractive salary schemes including 13th month salary
● Impressive office location with paid parking and great nearby amenities
● Monthly team dinners and annual company trips
● Equipment provided includes Macbook Pro and widescreen monitor
● Opportunity to greatly improve English skills with CubicStack’s international clientele
● Embracing multiple, new technical stacks to accelerate business development
● Allowed flexible working hours with annual leaves package
● Premium healthcare package

### Contact

Contact us to schedule a friendly discussion
Ms Tracy+84 909234922  (Zalo/Telegram/Whatsapp)
trang@cubicstack.net

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
