### ISSUE TITLE
[Cubicstack Solutions] - [PHP Developer] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by CubicstackSolutions** [awesome-jobs/vietnam#2485]
## Location

* Saigon, Vietnam

## Salary Expectation

* $900 to $1,300/month 

## Requirements
● 2 years or more experience working as a PHP Developer, using frameworks such as Symphony, 
CodeIgniter and/or Laravel
● Usage and management of UNIX based and LAMP stack operating systems
● Solid knowledge of Object-Oriented Programming (OOP) and Design Patterns
● Deep understanding in database architecture and usage of MySQL, Memcached, Redis and/or 
ElasticSearch
● Ability to manage, develop and work with API driven applications
● Ability in and highly motivated to adapt new technical stacks
● Self-taught and open-minded candidates are highly encouraged
● Our current tech stack: PHP, Laravel, ReactJS, NextJS, Docker, Kubernetes, Gitlab, Bitbucket, JIRA, 
Youtrack, Confluence, TestRail, Selenium, UILicious, Slack

### Nice to haves
● Good English fluency and communication skills is a plus
● Product driven mindset with an eagerness to learn and apply new technologies
● Experience with front-end technologies such as ReactJS, VueJS and CSS

### Responsibilities
● Develop consumer and enterprise web applications with a focus on seamless user experiences
● Maintain existing web applications that are within the company’s portfolio
● Work independently or as a team across various countries to efficiently deliver solutions based on 
business requirements and timely estimations
● Work with existing microservices architectures to create solutions and integrations

### Why it would be awesome to work with us
● Attractive salary schemes including 13th month salary
● Impressive office location with paid parking and great nearby amenities
● Swimming pool access for all employees
● Monthly team dinners and annual company trips
● Equipment provided includes Macbook Pro and widescreen monitor
● Opportunity to greatly improve English skills with CubicStack’s international client
● Embracing multiple, new technical stacks to accelerate business development
● Allowed flexible working hours with annual leaves package
● Premium healthcare package

### Contact
Contact us to schedule a friendly discussion
Ms Tracy+84 909234922  (Zalo/Telegram/Whatsapp)
trang@cubicstack.net

[Cubic Stack JD - PHP Developer.pdf](https://github.com/awesome-jobs/vietnam/files/6520219/Cubic.Stack.JD.-.PHP.Developer.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
