### ISSUE TITLE
Pionero - Backend Engineer (NodeJS) - Hanoi - FT

### ISSUE THREAD

**Issue by vanhuyz** [awesome-jobs/vietnam#2487]
## Location

* 505 Minh Khai, Hai Ba Trung, Hanoi, Vietnam

## Salary Expectation

* $800~$1700/month

## Requirements
* Javascript, NodeJS
* PostgreSQL/MySQL
* 2+ years Software Engineering experience

### Must Have
* At least 2-year experience in backend development
* Working knowledge of Javascript and/or Python, Golang
* Familiar with SQL databases such as MySQL/PostgreSQL
* Familiar with Docker containers 

### Ideally

* Experience with frontend frameworks such as ReactJS
* Hands-on experience with Amazon Web Services (AWS) toolset
* Ability to read English documents

### Responsibilities

As a Backend Engineer in our team, you will help us build scalable systems and beautiful web/APIs for our clients.
* Work with project managers, and engineering leads to understand application requirements
* Work closely with AI engineers to deliver solutions to Japanese clients (no Japanese required)
* Design architecture for backend systems
* Implement web/backend systems using NodeJS, Python
* Configure CI/CD and deploy applications to cloud (AWS, GCP)

### Why it would be awesome to work with us
* Flexible working hours between 8 AM ~ 7:30 PM (average 8 hours/day)
* 2 months probation with 100% of gross salary
* 13th-month salary
* Have opportunities to talk with world-class engineers through monthly company’s meetups 
* Strong engineering culture and passion for new technologies

### Contact
Email: contact@pionero
Homepage: https://pionero.io/
[Facebook Page](https://www.facebook.com/pionero.io)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
