### ISSUE TITLE
[JobSeekervn] Senior QA Engineer - Sài Gòn

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2488]
## Location

* Saigon, Vietnam
* Full-time 

## Salary Expectation
* $1200 - $1500

## Requirements
* At least 4 years work experience in software quality assurance.
* Has 3+ years of experience in automation test by using the automation testing framework.
* Experience in build and enhancement the automated testing framework using Selenium WebDriver.
* Good knowledge of software testing methodologies, automated testing tools, and processes.
* Experience in iOS, Android, Web and API testing.
* Experience in working with the continuous delivery deployment framework.
* Experience working in an Agile/Scrum development process.

### Responsibilities
- Participate in review and analyze the project requirement to understand test objectives, provide input on testability of requirements and estimation for the testing activities
- Collaborate with the Software Engineer team and Product team to ensure consistent product test cases execution
- Build automated testing tools and scripts for driving application tests
- Define, develop, implement, and maintain the automation test scripts
- Provide the testing approach, develop the automation test strategy, testing framework for automation testing projects.
- Design the test case, writing the automation scripts.
- Provide training and mentoring to test automation engineers. This includes conducting code reviews, training test automation engineers on new coding and testing methodologies, guidelines, and best practices.
- Do manual testing when the project needed.
- Contribute to the building of continuous Integration (CI) environment and ongoing Process improvement activities.

### Why it would be awesome to work with us

- MacBook and monitor provided.
- Open and friendly working environment with unlimited vacation and flexible working hour.
- 13th month salary and annual salary review.
- CFYC gym/fitness membership and Liberty healthcare insurance.
- Birthday celebration, monthly team lunch and dinner.
- PS4 and pool table for recreation. Snacks and drinks at fuel bar.
- Great package for annual company trip.
- Opportunity for exchange working program in the US.

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi
Website: nhiha.top

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
