### ISSUE TITLE
Star Global - Senior iOS Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2489]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work from home and office)

## Salary Package

* Very impressive - We can't share our range but you can share your expected salary and we'll let you know if that fits in our range of seniority

## Requirements
* 5+ years of iOS experience
* Strong programming knowledge of Objective-C/Swift
* Experience with CoreData, Multitasking and Networking
* Knowledge of mobile application architecture, design patterns, understanding of refactoring techniques
* Knowledge of TDD and experience with Unit and UI Testing
* Solid knowledge of development tools, environments and utilities
* Proactive goal-focused mindset, desire to create high-quality products
* Passion for continuous learning and adapting to new technologies

## Skills
* Swift
* Objective-C
### Must Have
* Good written and spoken English, good communication skills

### Ideally
* Experience with continuous integration/continuous delivery
* Knowledge in the latest trends in the mobile industry and platforms
* Python, Shell script knowledge
* Knowledge of Dart/Flutter
* BSc/MSc degree in Computer Science
* Your own apps on App Store

### Responsibilities
* Design, develop and maintain efficient, reusable and reliable code.
* Implement new features and build REST APIs
* Write unit and integration tests
* Collaborate with the team members within a Scrum Framework
* Perform code reviews and share best practices with colleagues

### You’ll be responsible for

* We are looking for an iOS Engineer to become a core member of one of our team. Our client builds a platform that is intended for small and medium businesses like restaurants, retail stores, services, etc. One of the platform’s components enables cafe and restaurant owners to effectively administer a load of their places by modeling the arrangement of tables and seats. Then this plan streamlines the process of tables reservations and optimizes the ongoing seating of incoming guests. You will communicate with the customer, determine the product functionality, define the architecture and estimate the overall work.

### Why it would be awesome to work with us
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Latest MacBook Pro & monitor or you can bring your own device and we'll reimburse 
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
Homepage: https://star.global/careers/senior-ios-engineer-5/
HR: Victor Phan - quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
