### ISSUE TITLE
Reeting Internet - Senior Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by mylinh2607** [awesome-jobs/vietnam#249]
Reeting is a trusted online marketplace for people to list, discover, and rent accommodations. Reeting is the easiest way to connect apartment hunters and home owners. Utilising our rich and accurate apartment database, Reeting makes the process of listing or booking appointments with landlords effortless and efficient. 
With our unique management and analysis tools for homeowners, Reeting offers the widest variety of insights into the current real estate market as well as your business' growth.
## Location
- Saigon, Vietnam
## Salary Expectation
- Negotiable
## Requirements

*Experience in an Agile/Scrum environment
- Minimum 2 years of experience as a backend developer
- Strong programming skills: C#, ASP.NET, MVC
- Experience with Cloud Computing and GIT
- Experience with IIS platform
- Experience with Web API 2.0, SQL Server 2014 and entity framework 6
- Proficient in English reading and speaking skills.
- Excellent communication skills, both verbal and written
- Good time management skills.
- Excellent organization skills
### Responsibilities
- Managing requirements
- Prepare reports for the General Director on the performance of each project.
- Developing code alone or with other team
- Ensuring code quality and bug fixing
- Unit test and integration test
- Documenting key aspects of the system
- Tutoring junior developers
### Contact

Please send your CV to Charlie Do at charlie.do@reeting.com

**Comment by joneslee85** [comment]
@mylinh2607 can you please replace numbered bullet points with unnumbered bullet points?
