### ISSUE TITLE
[JobSeekervn] Senior Full-stack  Developer (Laravel) - Hanoi

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2490]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation

* $2200 - $3000

## Requirements

● Proven experience with PHP (7+) particularly with Laravel framework
● Good knowledge of JavaScript/TypeScript
● Experience developing SaaS style applications and/or public API’s
● Strong communication skills in English - asking questions when needed and sharing your knowledge and learnings

### Responsibilities

● You will contribute to building new product lines and features for our web applications as well as improving and maintaining the quality of the entire codebase
● You will participate in the full product lifecycle: planning, conception, development, testing, customer feedback, and iteration
● You will proactively suggest improvements across the whole stack
● You will help maintain our web application tech stack: Laravel PHP, React JS/TS, MariaDB, Redis, Kafka and whatever else is required to get the job done

### Why it would be awesome to work with us
- Health Insurance
- Performance-based quarterly bonus
- 13th month salary
- Annual leave: 15 days/year
- Sick leave: 5 days/year
- National holidays leave
- On-site opportunity (United States)

### Contact

Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
