### ISSUE TITLE
Mobytelab Solution - Fullstack Javascript Developer - HCMC - FT

### ISSUE THREAD

**Issue by LoanNguyen0312** [awesome-jobs/vietnam#2498]
## Location

* 151 Dao Duy Anh, Ward 9, Phu Nhuan District, HCMC, Vietnam
* Full-time

## Salary Expectation

* $1500 NET/month 

## Requirements
* Javascript
* NodeJS
* ReactJS
* 3+ years Software Engineering experience

### Your Skills and Experience

* Bachelor’s degree in Computer Science, Information technology or a related subject.
* 3+ years of experience or higher in Web development, especially focused in Fullstack Javascript skill.
* Strong proficiency with JavaScript/ TypeScript and ReactJS.
* Practically experienced in React Native.
* Strong experienced in NodeJS, Express, SQL or NoSQL database.
* Strong experienced in REST APIs design and implementation.
* Strong analytical ability and problem-solving skills. (MUST)
* Experience in cloud platforms such as AWS, Azure, and Google.
* Experience in deployment using CI/CD Pipeline, Docker and Kubernetes.
* English: Good at communication and writing skills.

### Why You'll Love Working Here
* Work in a professional and creative environment with promotions and opportunities to cooperate with foreign clients.
* Get opportunity to work abroad.
* Joining projects with millions of users in the world is a challenge.
* Improve yourself every day.
*  Have opportunities to learn new techniques and find ambition.
* 13th Month salary.
*  Salary review up to ability.
*  Social insurance, health insurance, unemployment insurance according to Labor Laws.
* Company trip every year, Happy hour every week, team building, birthday party.
* Full of Modern equipment is provided
* Snack, tea, coffee every day
* Working time: Monday – Friday.
* Working place: 151 Dao Duy Anh Stress, Ward 9, Phu Nhuan Dist, HCMC.

### Contact
* Email: loan.nguyen@mobytelab.com
* Skype: nguyenloanld0312
* Website: https://mobytelab.com/
* Fanpage: https://www.facebook.com/mobytelab

**Comment by ngnclht1102** [comment]
Used to work with the Mobytelab team! The team is good! The company is a good place to work!

**Comment by LoanNguyen0312** [comment]
> Used to work with the Mobytelab team! The team is good! The company is a good place to work!
Hi Mr. Nam, thank you for your feedback. Hope you have a great day!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
