### ISSUE TITLE
The Kirin Lab - Backend Developer (Elixir) - Remote - FT

### ISSUE THREAD

**Issue by vnnoder** [awesome-jobs/vietnam#2499]
## Location
* Remote, từ T2 - T6 (9h - 18h múi giờ Việt Nam)

## Salary Expectation
* Mức lương cạnh tranh

## Requirements 
* Phát triển API cho ứng dụng tư vấn tâm lý dẫn đầu thị trường Singapore và Malaysia.
* Phát triền các tính năng, các màn hình mới cho admin portal
* Tối ưu tốc độ của những tính năng đã có
* Tạo report, chart thông qua hệ thống phân tích dữ liệu Metabase
* Sửa lỗi được khách hàng báo cáo
* Chia sẻ kiến thức, trải nghiệm với các đồng đội trong công ty
* Làm việc với đội ngũ thiết kế, Frontend trong công ty
* Làm việc với khách hàng từ Singapore và Malaysia
* Để tìm hiểu thêm thông tin về sản phẩm, xin hãy truy cập https://www.thoughtfull.world/

### Must have
* Có kinh nghiệm làm việc trên production với Phoenix và Elixir hoặc các ngôn ngữ khác như Ruby, Golang, Java, Python.
* Có kinh nghiệm làm Backend trên production ít nhất 1 năm
* Nắm được design patterns, test-driven development và tự hào với code bạn đã viết ra.
* Chịu trách nhiệm, chủ động trong công việc
* Có tinh thần cầu tiến và học hỏi, sẵn sàng học một ngôn ngữ lập trình mới

### Ideally
* Elixir/Phoenix
* Có khả năng đọc, viết Tiếng Anh đủ tốt để giao tiếp với khách hàng

### The Job
* Môi trường làm việc trẻ trung, được khuyến khích thể hiện cá tính, trình bày quan điểm, chia sẻ kiến thức và được tạo điều kiện tốt nhất cho phát triển cá nhân
* Mức lương cạnh tranh với thị trường
* Cơ hội nâng cao kỹ năng nghề nghiệp khi làm việc với các dự án từ các công ty khởi nghiệp
* Làm việc với khách hàng nước ngoài, có cơ hội thực hành và phát triển tiếng Anh
* Được giao quyền quyết định và chịu trách nhiệm với quyết định của mình
* Được hỗ trợ tận tình khi làm việc với đội ngũ kinh nghiệm, với công nghệ mới nhất
* Design và API document chuyên nghiệp, rõ ràng

### The Company
Mục tiêu của The Kirin Lab là phát triển các ứng dụng tốt nhất để giúp khách hàng hiện thực hoá mô hình kinh doanh. Phần lớn khách hàng của chúng tôi là các công ty khởi nghiệp nước ngoài. The Kirin Lab có hướng đi theo mô hình doanh nghiệp xanh ngọc, nơi công ty như một gia đình nhỏ ở đó mọi người sẵn sàng chia sẻ ước mơ, nguyện vọng của chính mình và được đồng đội hỗ trợ nhiệt tình. Bạn có thể tìm hiểu thêm thông tin về công ty trên trang web thekirinlab_chấm_com

### Interesting Engineering Projects
* Blazing-fast messaging system that support text and media
* Zero-downtime deployment and scaling Phoenix servers

### Contact
Nếu bạn thấy phù hợp, xin hãy liên hệ và gửi CV cho chúng tôi tới email career_a_còng_thekirinlab_chấm_com

**Comment by ngnclht1102** [comment]
Nice!

**Comment by qcam** [comment]
@vnnoder Thanks for posting. I'm definitely not trying to make anyone's life harder but could you please update the job post to English?

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
