### ISSUE TITLE
Reeting Internet - Senior Android Developer - Saigon - FT

### ISSUE THREAD

**Issue by mylinh2607** [awesome-jobs/vietnam#250]
Reeting is a trusted online marketplace for people to list, discover, and rent accommodations. Reeting is the easiest way to connect apartment hunters and home owners. Utilising our rich and accurate apartment database, Reeting makes the process of listing or booking appointments with landlords effortless and efficient. 
With our unique management and analysis tools for homeowners, Reeting offers the widest variety of insights into the current real estate market as well as your business' growth.
## Location
- Saigon, Vietnam
- Remote
## Salary Expectation

Negotiable
## Requirements
- Minimum 2 years of experience in native Android mobile app development
- Background on creating consumer facing software, online services, social network, is a plus
- Excellent debugging skill
- Experience in OOP design patterns
- Fluency in Java is a must
- Experience in HTML, Django, and JavaScript
- Mobile web development, excellent mobile sensibilities and agile experience is a plus
- Proficient in English reading and speaking skills.
- Excellent communication skills, both verbal and written
- Good time management skills
- Excellent organization skills
### Responsibilities
- Managing requirements
- Prepare reports for the Product Manager on the performance of each project.
- Developing code alone or with other team
- Ensuring code quality and bug fixing
- Unit test and integration test
- Documenting key aspects of the system
- Tutoring junior developers
### Contact

Please send your CV to Charlie Do at charlie.do@reeting.com

**Comment by huydx** [comment]
@mylinh2607 it's better if you can give us information about reeting.com.

**Comment by joneslee85** [comment]
@mylinh2607 thanks for posting with us, but your post still need to conform with our post format, for example the bullet point should not be numbered bullets

**Comment by mylinh2607** [comment]
Hello,

Thank you for you feedback! I will adjust my post accordingly
