### ISSUE TITLE
HCM - ILT - Frontend Developer ( ReactJS)

### ISSUE THREAD

**Issue by tanacullen13** [awesome-jobs/vietnam#2500]
## Location

* Sala Q2, HCM, VN
* Full-time

## Salary Expectation

* 2200$/month

### Must Have

- At least 3 years of experience in ReactJS library.
- In-depth knowledge in HTML5, CSS3, JavaScript, and design patterns.
- Expert with developing responsive layouts leveraging CSS and media queries.
- Familiar with Photoshop / Sketch, assets exports, PSD to HTML.
- Experience with applications that require local database storage usage, animation, and social networks.

### Nice to have

- Experience with Blockchain.
- Experience with web3.js, TronGrid APIs, TronLink SDK, and TrustWallet SDK.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

- Participate in the full life cycle of Blockchain and related software development, including design, architecture and implementation of different dApps using Smart Contracts.
- Enforce adequate level of security for managing crypto assets.
- Contribute creativity and insight to solve both technical and business challenges.

### Why it would be awesome to work with us

- Attractive salary ( up to 2200$).
- Receive a full salary during the probationary period.
- Committed 13th-month bonus + Attractive yearly performance bonus + Attractive bonus for each excellent project  + Annual salary appraisal.
- Health care programs for all staff.
- Company trip, Team building, etc.
- Exciting company activities: Happy hours, Birthday party, International Women’s Day, Mid Autumn Festival, big annual year-end party every year, etc.
- Healthy lunch provided.
- Free parking lot.

### Contact
Email: nhandtt@inspirelab.io
Skype: nhandtt96

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
