### ISSUE TITLE
SpiritLabs - Backend Developer (NodeJS) - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by dongnguyenltqb** [awesome-jobs/vietnam#2501]
## Location

* 1 District, Saigon, Vietnam
* Full-time

## Salary Expectation

* Up to $1500

### Must Have

* **2+ years** of experience with or proficiency with **NodeJS**
* **1+ year** of experience with **Agile/Scrum** methodologies
* Ability to build high performing application that processes large amounts of hourly requests
* Ability to work in a fast-paced and agile development environment
* Experience with integrating REST API to front end components
* Experience with PostgreSQL, MongoDB for data storage, Redis for in-memory data structures, Elasticsearch for our full-text search engine
* Experience scaling an application to handle an increasing user base or having the ambition to put your scaling ideas into practice is a plus
* Good knowledge of design, analytics, development, coding, testing, and application programming

### Ideally

* A fast learner who can pick up new technologies quickly
* Experience working with the full-stack of web and mobile applications
* Experience building fast and efficient web applications
* Experience creating single-page applications Angular or React
* Be excited and understand front end and robust app server architecture, and scalable backend design 

## Responsibilities

* Develop back-end website applications;
* Create servers and databases for functionality;
* See-through a project from conception to finished product;
* Design and developing APIs;
* Meet both technical and consumer needs;
* Stay abreast of developments in web applications and programming languages

### You can bring

* A good eyes for design
* A good analysis skill

## Why it would be awesome to work with us

- 13th-month salary
- Social insurance contributions following your gross salary (100%)
- Private Health Insurance
- Company trip per year
- Yearly salary review
- Other welfare is in accordance with Vietnam labor regulations

## Contact

- Please send your resume to dong.nguyen@spiritlabs.co 
- [**Company Homepage**](https://spiritlabs.co)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
