### ISSUE TITLE
CycAI - Frontend Developer (ReactJS) - Remote/Hanoi/Saigon - [FT]

### ISSUE THREAD

**Issue by mbui0327** [awesome-jobs/vietnam#2502]
## Location
* Hanoi/Saigon, Vietnam
* Remote

## Salary Expectation 
* Up to 2500USD - Above the market + stock options as long as you are really good.

## Job Descriptions
We are an early-stage startup in Silicon Valley looking for exceptional front-end developers in Vietnam, who will own/build/deploy our web applications. You will be working and mentored by successful startup founders, who have built and sold companies in Silicon Valley and have experience working in top technology companies such as Amazon, Google and Facebook. You will own the web front of our applications but might also have to work on back-end and other tasks if the team needs your help. This position is NOT for someone who is looking for a steady and well-defined job. This is for someone who has an entrepreneurial mentality, who can embrace changes, fast execution speed, and are eager to learn/explore new things.

## Requirements
* Strong experience with ReactJS/NextJS/HTML/CSS/Python.
* 2-3 years of experience.
* You own the frontend but can also do full-stack.
* You should a top coder at your level.

### Ideally
* You are young and hungry. You love building kick-ass products so much that sometimes you forget that you are living on earth. You are willing to work really really hard regardless of time and get great reward for doing so.
* You have built and deployed 1 or 2 serious web apps. It is not required but that is how we know you are really good.
* You have an entrepreneurial mentality. Always want to learn new things and explore  new technology frontiers. 
* Your friends found you boring because you are always talking about coding.
* You admit your mistakes and learn fast to not repeat the same ones.

### Contact
Mark: mark@cyc-ai.com

**Comment by mbui0327** [comment]
Hi @lactroi, just wonder how long does it take for the review to be done?
Thank for your service. Appreciate it.

**Comment by qcam** [comment]
@mbui0327 Hey! I think you’re all set. Ads are valid and active as long as they’re not closed.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
