### ISSUE TITLE
FETCH TECHNOLOGY - SENIOR/LEADER RUBY ON RAILS - HCM/HN - FT 

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2503]
![image](https://user-images.githubusercontent.com/60914247/120160121-190daa00-c220-11eb-9a4a-0036f7815a52.png)

## Requirements
* Good experience with recent versions of Ruby & Ruby on Rails (3-5 years preferred)
* Strong aptitude towards testing, preferably with frameworks such as RSpec.
* Good understanding of source-code versioning tools such as Git, SVN, or others.
* Experience with working with HTML, CSS, HTTP/S and/or other web technologies.
* Strong grasp on object-oriented development & design.
* Experience with development in the cloud (preferably Digital Ocean & AWS).
* Experience with RDBMS.
* Experience with using & developing RESTful APIs.
* Great communication skills, solution-oriented attitude and working with global teams and partners.
* Proficient in English.
* Experience with stimulus application.
* University Degree in Computer Science, Engineering or equivalent

## Responsibilities
* Writing scalable Ruby code on the front-end & back-end.
* Maintaining & improving existing code as well as working on new components.
* Adding unit tests and assisting QA.
* Performing support, identifying & fixing bottlenecks & bugs.

## Why it would be awesome to work with us
Being a Ruby on Rails Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment: 

* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

## WORKING TIME & LOCATION

 Location:
+ 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau ward, Cau Giay District, Hanoi.

+ 3rd Floor, BCONS TOWER 2 - 42/1 Ung Van Khiem Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

Working time: From Monday to Friday, 9AM - 6PM.

## Contact
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
