### ISSUE TITLE
FETCH TECHNOLOGY - SENIOR RUBY ON RAILS - HCM - FT (2,000 - 3,500 USD)

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2504]
![image](https://user-images.githubusercontent.com/60914247/120159843-d77cff00-c21f-11eb-94cd-9bf0dfaf51f7.png)

## RESPONSIBILITIES:

* Full-stack developer to maintain and develop online services
* Work closely with the product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web and applications.
* Participate in user testing on production. 
## REQUIREMENTS

* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* 4+ years of software development experience (with at least 2 years in Ruby on Rails).
* Good UI/UX design sense and ability to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS is a super plus.
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
* Enjoys challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over-communicating).
* Language barriers aside, you must be willing to make an effort to communicate as much as.
* Overthink security.
* Able to communicate by English.

Nice to have:

* Familiar with and passionate about BitCoin and cryptocurrencies, its network and protocol.
* Able to code in multiple languages: Java, Scala, Golang, Ruby.
## WHY YOU WILL LOVE WORKING HERE?

Being a Senior/Middle Back-end Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese
* With extensive on job training, you will always have a chance to work with new emerging technologies
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), * Play Sport (Football, Badminton...).
## WORKING TIME & LOCATION

* Working time: 9AM - 6PM from Monday to Friday. 
* Location: 4th Floor, HQ Tower - No. 9 Tran Nao street, Binh An ward, Thu Duc City (District 2), Ho Chi Minh City.

## CONTACT: 
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by Jesse111-flyaway** [comment]
Range lương thay đổi open từ 2,000 - 3,500 USD nhé mọi người ơi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
