### ISSUE TITLE
FETCH TECHNOLOGY - JUNIOR FULLSTACK - HCM - FT

### ISSUE THREAD

**Issue by cutiedinosaur** [awesome-jobs/vietnam#2507]
## Location

* Saigon, Vietnam

## Salary Expectation
* 500 - 900$

## Requirements

- 1 year experience in dotNet, Entity Framework, React, Redux, Hook.
- Strong understanding of OOP and Clean Code.
- Experience in SQLServer databases and schema design.
- Experience in Javascript (ES6) & HTML / CSS.
- Understanding of RESTful APIs.
- Experience in Git.
- Experience with Infrastructure/Devops is a plus.
- Strong Command of English and good communication skills.
- Nice to have: CQRS, DDD pattern.

## Why it would be awesome to work with us
Being a Junior Full-stack Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

- Attractive salary and annual salary review.
- Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
- Extensive on job training, you will always have a chance to work with new emerging technologies.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
- 12-day annual leave per year.
- 13th month salary.
- PVI Health Care.
- Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

## Contact
* Skype: tonnhatha3@gmail.com 
* Zalo: 0886626167
* email: nhatha@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
