### ISSUE TITLE
Raksul Vietnam - Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by thaopham-bee** [awesome-jobs/vietnam#2508]
We've opened a software development office in Ho Chi Minh City in May 2020, and our teams are delivering several products to lots of customers every day with Japanese development teams. 
Now, Raksul Vietnam are working with 20 members and most of them are backend engineers and project managers.

Then, we're building frontend development team in Vietnam. 

In this position, you'll not only develop product with headquarter's and HCMC's development teams, but we're also expecting you to build the frontend development team together in Ho Chi Minh City's office.

## Location

* Saigon, Vietnam

## Salary Expectation

* 2,500 - 5,000 USD

### We are looking to hire candidates for the following responsibilities

* Demonstrate product ownership with product managers and business teams.
* Provide assistance and advice on the definition of system requirement and system design
* DevOps of various services, and partner solutions
* Provide guidance and mentoring to junior members

### Main technology:

* Vue.js, Typescript + Javascript for frontend
* Ruby on Rails for backend
* AWS for infrastructure

### Must Have

* Ability to communicate in English
* Working experience in HTML, CSS, and JavaScript
* Working experience in front-end frameworks (fluent in at least 1 of the following: Vue.js, Angular, React)
* Experience as a team leader

### Ideally

* Experience in front-end development using TypeScript, FlowType, etc. 
* Experience in designing and tuning UI interaction using CSS animation.
* Experience in build front-end development environment using Webpack, Gulp, etc.
* Experience in improving legacy code/system and working with REST API
* Experience in pair programming and/or mob programming
* Experience in working with cloud computing such as AWS

### Other important factors

* Proactively think and execute
* Ability to contribute to the expansion of the Vietnam development team
* Ability to work with others and preference on teamwork
* High interest in learning and using new technology
* Ability to define service issues or technical issues
* Strong interest to change old industries with technology

### Why it would be awesome to work with us

* Flexible working hours, working from home conditionally
* MacBook Pro provided 
* Salary review every 6 months & health insurance
* At least 15 paid days off per year
* Free drink, monthly team building party
* Opportunities for business trip to Japanese partner company and HQ office

### Interesting engineering projects
* Our main product, Raksul (https://raksul.com/), a printing platform connects those who have printing requirements with printing companies. 

### Contact
Homepage: https://recruit-vn.raksul.com/
Email: vietnam-hr-uc@raksul.com 

Other:
https://itviec.com/companies/raksul-inc

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
