### ISSUE TITLE
KYANON DIGITAL - SENIOR SOFTWARE ENGINEER - HCM - Up to $3000

### ISSUE THREAD

**Issue by LamAnhVu** [awesome-jobs/vietnam#2509]
### **Location**
Kyanon Production House, Saigon, Vietnam

### **Salary Expectation**
* $3000 Net/month

### **Requirements**
- At least 5 years experience as a software engineer with one of tech stack:

1. - Backend: Golang, NodeJS or .NET, familiarity with one of its framework, and design/architectural patterns
2. - Frontend: Angular, ReactJS
3. - Mobile: React Native, Flutter

- Familiarity with architecture styles/APIs (REST, RPC)
- Understanding of Agile methodologies and DevOps
- Excellent troubleshooting and communication skills
- Ability to work independently, as well as part of a large team
- BSc/BA in Computer Science, Engineering or a related field
- English
- Good at Algorithm is a big plus

### **Responsibilities**

- Join an amazing team to build one of the biggest e-grocery platform in Vietnam
- Participate in backlog refinement/requirement analysis.
- Collaborate with internal teams to produce software design and architecture
- Write clean, scalable, and high-performance code
- Test and deploy applications and systems
- Revise, update, refactor and debug code
- Develop documentation
- Serve as a technical expert and provide support

### **Why it would be awesome to work with us**
- Bonus structure + 13th month Bonus.
- Flexible working time: only 8 hours required as continual working-time at the office.
- 12 days Annual leave.
- Coffee and snacks provided.
- Holiday celebrations and parties for team members and family.
- Company trip, team building activities.

### **Interesting engineering projects**
- Experience working as a member of a small agile software development team, e.g. participating in planning sessions and interpreting user stories, doing code reviews, pair programming.
- Improve English skills. 
- Have a chance to study new technology, new domain through workshops, seminars, and conferences.

### Contact
Homepage: https://kyanon.digital/
Mail: career@kyanon.digital (0359.189.555 - Ms. Anh)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
