### ISSUE TITLE
[JobSeekervn] Fullstack Javascript Developer - remote, fulltime - Saigon

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2510]
## Location

* Fulltime
* Remote

## Salary Expectation

* $2000 - $25000

## Requirements
* Degree in Computer Science, Software Engineering or relevant engineering degree
* Significant experience with Cloud Services such as AWS
* Experience with developing and designing REST API’s
* Experience with database technology such as MySQL
* Experience with JavaScript frameworks such as Angular
* Experience with Node.js and TypeScript
* Experience with version control tools such as Git
* Experience with DevOps is a bonus

### Responsibilities
* Maintaining the performance and security of the application
* Managing cloud infrastructures
* Implementing and maintaining integrations with third-party applications
* Involved in all aspects of the software development (Design, develop, test, and deploy)
* Developing wireframes into a beautiful user experience
* Transferring user requirements into technical specifications
* Reviewing code with a constructive attitude
* Developing automated testing frameworks

### Contact
Please contact me via skype hahoainhi or email: nhiha@jobseeker.vn for more information. 
Thank you!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
