### ISSUE TITLE
SUTUNAM - Mid/Sr Front-end superhero 🦸 (HTML/CSS, Javascript) - Up to 2,000$ - Hanoi - FT

### ISSUE THREAD

**Issue by TramAnh-Sutunam** [awesome-jobs/vietnam#2516]
[2021 - Sutunam - Front-end developer (HTML/CSS, Javascript) - Job desciption](https://drive.google.com/file/d/1tdxXfa4mfGVT-NDMVrS9Mrf_Hd3ZzUeD/view)
We seek a **detail-oriented Front-End Engineer** 🦸 who is proficient with Javascript knowledge and keen to use the latest in web technologies and is experienced in **developing highly polished websites** for clients. Strong passion for web development, eagerness to apply new technologies at work.

You will join a team of talented developers and work on international web application, e-commerce and mobile platforms (PWA) with beautiful UX/UI creation and high standard!

## Location

* Hanoi, Vietnam
* Full-time

## Salary Expectation

* $1000 - $2000/month

## Requirements

You will be working closely with our amazing design team, other back-end developers, team leaders, and project managers to deliver world-class websites.

-  Strong knowledge of **HTML5/CSS3** (Bootstrap, Zurb Foundation is a PLUS);
- Solid understanding of **Javascript** coding (jQuery or ES6, etc);
- Knowledge of SASS/LESS, Grunt/Gulp, or Webpack and PWA;
- Experience with **VueJS** or **ReactJS** is a plus;
- Strong UI/UX experience and pay attention to improve website performance;
- Ability to implement complex sequences using Velocity, GSAP, or similar;
- Experience in Agile Development methodologies, SCRUM process;
- Strong aesthetic sense and good understanding of motion is PLUS (i.e: Google motion design);
- Ability to communicate, read, and write in English.

## Skills
* Javascript / HTML/CSS

## Responsibilities
- Convert designs to HTML/CSS documents using Sketch/Photoshop/Illustrator/Zeplin.
- Your products should be well-structured, SEO friendly, flexible to customize and be compatible with modern browsers;
- Customize website interface using HTML/CSS/Javascript to adapt requirements from client (Symfony and Magento);
- Stay up-to-date on the latest developments and trends in web design and development;
- Collaborate with design team to build UI/UX competency, and participate in designing stages proactively to build responsive and interactive websites;
- Work with interaction, motion, slick animation, beautiful scrolling, and stunning transitions.

## Why it would be awesome to work with us
* Because you want to be part of a **multi-winning award** digital Agency;
* Because you want to work with talented colleagues;
* Because you want to work on the exciting new tech;
* Because you want to grow in a professional & **English-speaking**; environment where your voice will be heard;
* Because you believe **small changes** everyday make **great achievements**;
Or, just because you **love** us! ;)

## Interesting engineering projects
Let's check out our worldwide projects at: https://en.sutunam.vn/our-work/

## Contact us to have a meet! 😉
Website: https://beahero.sutunam.com/
Apply via our mailbox: [hr.vietnam@sutunam.com](mailto:hr.vietnam@sutunam.com)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
