### ISSUE TITLE
Orange Logic - Software Engineer (integrations projects) - HCMC

### ISSUE THREAD

**Issue by hanguyenOL** [awesome-jobs/vietnam#2518]
## Location

* HCMC, Vietnam

## Requirements

* Software engineering background and a broad knowledge of web development: this allows you to quickly understand new tools, framework and programming languages
* Enjoy building projects from scratch, and it shows in your rich portfolio (professional & personal)
* Have 3+ years of experience as full-stack engineer (strong back-end abilities and decent front-end skills)
* Master at least one popular programing language like Javascript (React, Angular...) or Python
* Work fast with little guidance but without missing any important details
* Versatile, flexible and agile to explore new tools, libraries and technologies 
* Your command of English is enough to interact with foreigners

### Must Have

* Strong self-discipline under a tight schedule and the capability for rational thinking.

### You’ll be responsible for

* Build innovative features for our clients and help extend Cortex functionalities

* Be free to explore available tech and select the best third-party solutions to complete the project

* After validating your approach with a prototype, you will build custom integration to bring the feature into Cortex and to our clients

### Why it would be awesome to work with us

> At Orange Logic, it does not matter how many years of experience you have, or your age. We believe that each individual, regardless of these factors, has the ability to evoke change within the organization.

* Work alongside a group of skilled engineers, share and contribute their ideas, and have a direct impact on our software development. 
* Amazing team: smart, open-mind, and passionate engineers. They came from the US, France, UK, and Vietnam hence you could improve your English and explore different country cultures.
* 18 days of annual leave (cashback for unused days) + 4 days for an abroad company trip (Taiwan, Thailand, etc)
* 13th-month salary
* Performance bonus (average $700/month in 2020)
* Premium healthcare insurance ($10.000 cover) after probation
* Full Insurance based on your Gross salary
* Allowances for lunch, gym, parking ($100)
* Birthday bonus ($100), Tet gift, etc
* Daily free snacks, fresh fruit, coffee & soft drinks
* Latest gadgets for work (include noise-canceling headphones)

### Contact
* Please send your resume to ha.nguyen@orangelogic.com
* You can drop me a message on [Skype](https://join.skype.com/invite/mNKg28GbjKfr) or [Linkedin](https://www.linkedin.com/in/ha-nguyen-01a752ba/)
* [Our Homepage ](https://www.orangelogic.com/digital-asset-management-customer-examples)

> Can't wait to have a detailed discussion if you have any questions or concerns!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
