### ISSUE TITLE
2Click Solutions - .NET Software Engineer - HCMC - FT

### ISSUE THREAD

**Issue by trungnguyen2CS** [awesome-jobs/vietnam#2519]
## Location

* District 12, HCMC

## Salary Expectation

* Negotiation

## Job Description
We are looking for Full Stack Developer who is passionate about innovation and willing to take challenges with 2Click Solutions. This job opens only to Vietnamese locals living in Vietnam.

## Requirements
* Understand OOP, SOLID, and SQL server database
* Experience in C# and .NET technology is mandatory
* Knowledge of HTML and JavaScript, with at least one Single Page Application framework
* Communicate with colleagues and stakeholders in English via verbal and non-verbal means
* Understandings of testing techniques

### Why it would be awesome to work with us
* 8 working hours per day with flexible entry (8:00 – 10: 00 AM) 
* 2 remote working days every month  
* 13th month salary 
* Free lunch at work  
* Annual health check and company trip

### Contact
Homepage: https://2clicksolutions.com/
Email: careers@2clicksolutions.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
