### ISSUE TITLE
Ruby Yoda - Javascript Developer - Remote/Saigon - C

### ISSUE THREAD

**Issue by webgago** [awesome-jobs/vietnam#252]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $10/h, negotiable

## Requirements
* Javascript
* Angular.js
* Jasmine
* 5+ years Software Engineering experience
* 5+ years Javascript experience
* Use TDD for their code
* English proficiency

### Responsibilities

Rework current front-end to SPA with angular.js 

### Contact

Tony: asozontov_at_gmail_dot_com

**Comment by joneslee85** [comment]
@webgago thanks for posting with us. Can you please let us on in what your project is about?

**Comment by joneslee85** [comment]
I am closing this because I have not received any response from you.

**Comment by webgago** [comment]
Sorry, didn't see the question.
The project is SPA for a medical company in USA. 
I'm an owner of consulting company Ruby Yoda here in vietnam. We develop business apps for american/european.
