### ISSUE TITLE
Telio Vietnam - Lead Engineer (JS, Nodejs, Go, ReactJS) - Saigon/Hanoi - FT - Upto $4000

### ISSUE THREAD

**Issue by vyvyphan** [awesome-jobs/vietnam#2520]
## Location 

* Saigon/Hanoi, Vietnam

## Salary 

* $3000 - $4000/month

## Requirements 

* 6+ years of software development experience (JS, Nodejs, Go, ReactJS)

* Strong expertise in designing complex frontend and backend applications using cutting edge technologies like Kafka, MongoDB, Redis, ElasticSearch etc.

* Strong expertise with both SQL and NoSQL databases

* Substantial experience in building complex and high performance web scale systems using microservices

* Fluency in English + Vietnamese

### You’ll be responsible for

* Research, Design and Develop highly reliable, available and scalable web-scale distributed microservices based systems

* Lead by example, mentor and guide team members on everything from structured problem solving to development best practices

* Participate in deciding your team’s roadmap in collaboration with Management and Product teams

* Collaborate effectively with product managers towards building the right features

* Estimate and manage deliveries of features in a predictable manner

* Continuously contribute to improving our technology ecosystem, libraries, frameworks, utilities and services

* Collaborate, mentor and guide team members as needed

### Contact 
email: tuongvy@telio.vn
skype: live:36246099c2b4806a

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
