### ISSUE TITLE
[Crypto Project] - Back End Developer (NodeJS) - [Hanoi] - Up to $3000 

### ISSUE THREAD

**Issue by TieuThu** [awesome-jobs/vietnam#2523]
## Location

* Hanoi, Vietnam
* Full-time

## Requirements
* Design, develop and maintain high traffic and large scale systems with high effects and optimization.
* Work with other stakeholders in project management analysis.
* Participate in researching security systems and solutions, contribute ideas about technology and products.

### Must Have
* Ideally 3+ years of work experience on Backend to serve large-scale and high-traffic projects
* Preferably with 1+ year of experience in NodeJS.
* Understanding of RBD and NoSQL.
* Strong working knowledge of data structures, algorithms is a plus.

### Ideally
* Having experiences working with Blockchain, Cryptocurrencies
* Having experiences in Docker/Kubernetes and Cloud Infrastructure is a plus
* Having experiences in Ethereum, Solidity is a plus
* Knowledge of information security is a big plus
* Ability to work as a team or independently

## Why it would be awesome to work with us
* Work directly with top-managers, group experts in Fintech, Blockchain, and Cryptocurrencies.
* Work and learn from the young, energetic, and awesome team.
* Build product from scratch until deployment and improvement.
* Engage in continuous learning program for professional development and personal enhancement;

### Compensation & Benefits:
* 13th salary and performance bonus
* Performance review + salary review twice a year.
* Working hour: 9:00 AM - 6:30 PM, Monday to Friday (lunch break 1.5 hours)
* Weekly happy hour, monthly team building activities
* Annual health check-up
* Healthcare Insurances
* Equipments for work
* Chillax office with gym, swimming pool, free snacks & drink all day.

## Interviewing Process 
* Phone screen > Technical Interview with Technical Leader

## Report to:
* This position reports to Technical Leader

## Contact:
* Telegram: @Chinhle177
* Zalo/Whatsapp: +84 938 598 328

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
