### ISSUE TITLE
Yojee - Senior Product Manager - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#2527]
## Location

* District 4, Saigon, Vietnam

## Salary 

* Negotiate 

## About the role

Yojee is looking for a Snr Product Manager that enjoys working in a dynamic startup and will be responsible for delivering world class logistics services across the globe. The person will lead and oversee one or more product squads in Yojee. They should lead the strategy and development of these products, and oversee their lifecycle from ideation to release, and then ongoing developments and improvements.

The ability to work with other product owners and ensuring engineering hits deadlines and deliverables is something you take pride in. Together with the team, you will have full ownership of the services you build.

## Requirements

* Domain knowledge in logistics, preferably transport.
* 5+ year experience in Product Management/Ownership.
* Proven track record of working with technical engineers.
* Background in agile development methodology highly desirable.
* Strong communication skills, both verbal and written, essential.
* Demonstrated leadership skills to own product squads and nurture a high performing culture.
* Self-directed, takes initiatives and comfortable leading without much supervision in a fast-paced environment.
* Attention to detail and good design skills.
* Good English communication.

### Nice to have 
* Bachelor Degree in Computer Science or related technical field preferred.

## Responsibilities

* Lead and oversee one or more product squads in Yojee.
* Lead the strategy and development of products, and oversee their lifecycle from ideation to release, and then ongoing developments and improvements.
* Identify and fill product gaps and generate new ideas, improve customer experience and drive growth.
* Scope and prioritize activities based on business and customer impact.
* Translate product strategies into detailed requirements (Epics and Stories) and prototypes.
* Coordinate, schedule and work closely with engineering teams and executives to serve the needs of the business and to optimize the utilization of development resources.
* User Acceptance Testing.
* Release note documentation.
* Together with the Engineering Manager, be a leadership figure in the growing Vietnam office.
* Perform and handle other ad-hoc duties as required.

## Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock: equivalent to 1-3months salary based on your performance
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..
* No 13th month salary
* Unlimited paid day off
* 100% official salary in probation time
* Full social insurance paid based on salary
* Free parking 

## About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Product team at Yojee

Yojee Product team comes up with the best strategy for product features and roadmap to solve on-ground logistics problems. We are accountable for the entire product lifecycle, right from planning through development, go-live, and retirement phases.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=101&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com
Phone: 0924605299

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
