### ISSUE TITLE
FETCH TECHNOLOGY - PYTHON DEVELOPER - HCM - FT 

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2529]
![image](https://user-images.githubusercontent.com/60914247/121003912-3f9b8a00-c7b8-11eb-9315-8630a8b56c65.png)

# HCM

# 700 - 1,200 USD

## RESPONSIBILITIES
* Analyze and systematically approach product requirements and work closely with PMs, QAs, and Tech Leads to build business backend features/apps that are modular and reusable. 
* Come up with practical short and long-term solutions that minimize complexity and maximize value Include security, maintainability, reusability, and testability when developing software solutions and code reviewing. 
* Factor Linux/Unix OS system internals, data storage, computing resources, microservices in the produced software architecture. 
* Identify things that can go wrong early but also thoroughly investigate bugs reported in production.
* Apply and tailor software development concepts and best practices.
##  REQUIREMENT
* Experience in developing, testing, debugging, and troubleshooting with any of these programming languages and technologies:

*** Must have:

* At least 1.5 years of Python and Django framework.
* Experience using databases (PostgreSQL, MySQL,..).
* Experience designing Rest APIs and using Rest APIs testing tools eq: Postman,...
* Git, Git hooks, unit test frameworks.
* Experience using Linux OS and Docker technologies.

*** Nice to have:

* Monitoring tools like Sentry, APM tools like Datadog.
* CI tools like CircleCI, Jenkins.
* Provisioning tools like Ansible.
* Knowledge in web frontend technologies eq: Node.js,Vua.js,...
## WHY YOU‘LL LOVE WORKING HERE
* Being a Python Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health 
* insurance & unemployment insurance according to Vietnam Labor Law.
* PVI Health Care.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, CS Go), Play Sport (Football, Badminton...). 

## WORKING HOURS & LOCATION

* Working hours: From 9 AM - 6 PM, Monday to Friday
* Location: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC. 

##  CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
