### ISSUE TITLE
FETCH TECHNOLOGY - MIDDLE DEVOPS ENGINEER - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2530]
![image](https://user-images.githubusercontent.com/60914247/121004663-2941fe00-c7b9-11eb-9ccd-956d59006e57.png)

# HCM
# 1,000 - 1,500 USD 

## RESPONSIBILITIES

* Build & maintain successfully CI/CD in our software environment.
* Collaborate with software engineers to understand the software architecture, main components, current obstacles and provide solutions. 
* Develop automation tools, including shell scripts to automate necessary tasks. 
* Support development team to set up and configure the development environment. 
* Design and deploy cloud platform capabilities - full-stack network, load balancing, caching, DNS, security, databases, etc. 
* Perform advanced technical troubleshooting for public, private, and hybrid cloud environments. 
* Define and monitor system metrics to ensure predefined SLA, SLO.  
## REQUIREMENT

*  2+ years experience in Linux, preferably with experience in Ubuntu OS.
* 1+ years experience in DevOps engineering environment.
* Experience in scripting: Bash, Python.
* Experience with CI/CD processes using self-managed tools or relevant cloud technologies (e.g Jenkins, CircleCI, Ansible, Terraform etc).
* Hands-on experience in networking, system administration, monitoring, infrastructure maintenance on premise or cloud environments.
* Knowledge about monitoring tools like ELK, Grafana,...
*  Good English communication skills.
*  Practical problem solver, highly analytical, great team player, have excellent work ethic, and have strong care in process automation.
*  Can communicate clearly, timely, and professionally With technical and non-technical users.
Expert in multi-tasking, both in planning, executing, and managing projects thoroughly in issue tracking tools like Jira.

*** Nice to have:

* Have experienced with AWS, GCP, Alibaba Cloud.
* Knowledge about microservice eq docker, k8s.
## WHY YOU‘LL LOVE WORKING HERE
Being a DevOps Engineer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 
## WORKING HOURS & LOCATION

* Working hours: From 9 AM - 6 PM, Monday to Friday
* Location: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC.
## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
