### ISSUE TITLE
FETCH TECHNOLOGY - DEVSECOPS ENGINEER - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2531]
![image](https://user-images.githubusercontent.com/60914247/121004663-2941fe00-c7b9-11eb-9ccd-956d59006e57.png)

# HCM
# 1,000 - 2,000 USD 

## INTRODUCTION
a. About Fetch:
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

b. About Client:
Originally founded in Silicon Valley in 2014 and headquartered in Singapore, our client is a market-leading, and one of the oldest, homegrown cryptocurrency platforms. Their aim is to accelerate access to cryptocurrencies throughout the ASEAN region and we focus on localized cryptocurrency exchange services – acting as cryptocurrency gateway services in multiple countries.

## RESPONSIBILITIES
* Design, implement and maintain a secure and reliable cloud infrastructure platform. Work with other infrastructure teams and DevOps to understand CI/CD processes and integrate automation security solutions into the development process.
* Analyzing and collecting data/metadata from cloud systems (IAM, VPC, Cloud audit log…) to determine the abnormal behavior/traffic of cloud systems.
* Develop, optimize, and automate the build and deployment processes for the provisioning application, using security and cloud best practices.
* Secured containerized applications and Kubernetes clusters (Vulnerability, Hardening, Network Policies).
* Reviewing and addressing cyber-security issues as well as propose security solutions and architecture.
* Performing research to stay abreast of new technologies and security vulnerabilities preferably in a distributed, cloud, or micro-service environment.

## REQUIREMENT
* Have secured public cloud deployments for infrastructure and applications running on the public cloud: GCP, AWS.
* Experience with DevSecOps or DevOps, Continuous Integration & Continuous Delivery (CI/CD), and automated test tools such as Security Source Code, Jenkins, and/or Gitlab CI.
* Experience developing software or scripting with Bash, Php, PowerShell, Python or similar, ideally in an agile development environment.
* 1-2 years of ELK knowledge.
* 1-2 years of IT Security Operation.
* Have experience in Cloud Workload Protection Platform and Cloud Security Posture Management.
* Professional qualifications such as OSCP, SANS preferred.
* Competencies: Integrity, Collaboration, Delivery Excellent, Innovation

Functional:

* Ability to influence and resolve conflict through timely and transparent communications.
* Ability to work to deadlines and under pressure.

## WHY YOU‘LL LOVE WORKING HERE
Being a DevSecOps at this company, you will experience a youthful, flexible and creative work environment:

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Premium Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).
## WORKING TIME & LOCATION

* Working time: 9 AM - 6 PM from Monday to Friday. 
* Location: 4th Floor, HQ Tower - No. 9 Tran Nao street, Binh An ward, Thu Duc City (District 2), Ho Chi Minh City.

## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
