### ISSUE TITLE
[Closed] Star Global - Ruby Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2534]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* Very impressive - We can't share our range but you can share your expected salary and we'll let you know if that fits in our range of Engineer Level

## Requirements
● 3+ years of experience developing backend side of mobile apps commercially or
equivalent experience with millions of users.
● Experience and proficiency with Ruby.
● Experience with Ruby On Rails Framework.
● Expertise with some AWS services, especially AWS CloudFormation.
● Experience with Docker containers or similar technologies.
● Experience with CI/CD pipelines and providers such as CircleCI or similar.
● Solid understanding of backend architectures/design patterns.
● Expertise with and attention to security best practices.
● Solid understanding of CAP theorem, SOLID, etc.
● Expertise with Postgresql language (AWS AuroraDB).
● Expertise in building complex workflows.
● Familiarity with RESTful APIs to connect mobile applications to back-end services.
● Familiarity with SCRUM and Agile practices.
● Expertise in writing unit tests and testable code.
● Experience collaborating on cross-functional project teams with design and all stakeholders.
● Strong interpersonal and communication skills.
● Able to work independently and drive for results.

### Responsibilities

● Plan and implement solutions to business challenges, working directly with core engineering and product management.
● Develop features, maintain and improve existing applications to support our clients.
● Create tooling and automation to make our team more efficient.
● Deliver finished work integrated with the existing infrastructure, with test coverage and documentation necessary to achieve high quality.
● Participate in all phases of Software Development Life Cycle, implementing features and addressing issues.
● Have a wide scope of responsibility and flexibility in selecting the appropriate technical solutions to business challenges and opportunities.
● Actively and constantly communicate with all team members utilizing pair programming or collaborating in engaging technical discussions, both written (chat) and verbal (videoconference).

_**In the first days your expected deliverables will include**_
● Complete onboarding training with a mentor.
● Understand technical solutions delivered to our clients.
● Deliver complete PRs and get improved by our feedback.
● Become a strong team player and raise our overall quality.

### You’ll be responsible for

We are looking for a Ruby Backend Engineer to become a core member of our new projects. You will be involved in the end-to-end process: from the initial project inception to the successful release of the products or features. Our mission is to unleash the power of data by providing the tools & capabilities needed, by reducing or removing barriers, and by delivering meaningful value today. The technology is used by major banks, accounting software companies and fintech companies in Japan.

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month 
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ New Macbook and accessories provided
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/ruby-engineer-2-8/ 
HR: quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
