### ISSUE TITLE
Star Global - Android Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2535]
## Location

Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

Very impressive - We can't share our range but you can share your expected salary and we'll let you know if that fits in our range of Engineer Level

## We require

- Good knowledge of Java and Kotlin languages.
- 5+ years of experience in Android development.
- Knowledge of Unit, Functional and UI Testing frameworks (Espresso, JUnit).
- Good knowledge of Android IDE, tools and libraries.
- Good coding skills, knowledge of algorithms, design patterns, concurrency, networking.
- Knowledge of Continuous Integration practices.
- Knowledge in the latest trends in the mobile industry and platforms.
- Good English.

**_We appreciate_**

- Knowledge of Android ecosystem – analytics, advertising, publishing, UI design concepts.
- Understanding of Android security practices.
- Personal applications in Google Play.

## Skills
Kotlin or Java

### Responsibilities

- Design, build and maintain efficient, reusable and reliable code.
- Perform code-reviews, collaborate with the engineering team to contribute in product improvements.
- Build, evolve and support Android automation tools for stable and efficient automation execution. Integrate tests into the build pipelines, with a focus on continuous delivery.
- Collaborate with the team members and customer representatives

### You’ll be responsible for

We are looking for a Senior Android Developer (with Java and Kotlit) to join our team and create innovative, world-class products. You will handle the entire product development process  a significant part of it, and work closely with the customer’s tech-team. You will determine product functionality, define the architecture, and estimate the scope of work. In addition, you will participate in internal knowledge-sharing meetings, external tech talks, and conferences as an attendee or speaker.

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month 
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ New Macbook and accessories provided
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/android-engineer-vn-1611749098/
HR: quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
