### ISSUE TITLE
[REMOTE JOB - FULLTIME] FullStack (React/React Native) Engineer

### ISSUE THREAD

**Issue by tieuvu9x** [awesome-jobs/vietnam#2539]
## Location

* Remote (prefer candidate living in Ha Noi)

## Salary Expectation

$1100 - $2600

## Requirements

- At least 4 years experience in React or React Native and its core principles
- Has relevant experiences working with Firebase, Firestore, Firestore Security Rules, Firebase Cloud Functions (or equal technology)
- Strong understanding of React State Management system and Redux Toolkit
- Familiarity with RESTful APIs
- Good with frontend development and maintain graphic standards and branding throughout the product’s interface
- Expert in JS ES5/ES6, TypeScript and HTML5, CSS3/SASS, responsive web design
- Knowledge in NodeJS

What We're Looking For:
- A self-motivated and proactive individual with a 'can-do' and entrepreneurial attitude
- Able to give technical suggestions and articulate tradeoffs and plan long term solutions
- Demonstrated expertise working with one or more of the following: Infrastructure, Front End Development, Mobile Application Development, Building SaaS platforms
- Experience architecting and developing solutions to ambiguous problems with significant impact
- Keen to research new technology
- Interest and ability to learn other coding languages as needed
- Intimate knowledge of mobile apps development quirks and best practices

## Priority for candidates
- Knowledge of SQL, Restful API, GraphQL, Git, NodeJS, and Python is a plus

### Job Overview & Responsibility

We are looking for an enthusiastic, hands-on, and self-motivated engineer, to be a key part of a dynamic team in a fast-moving and entrepreneurial environment. The successful candidate will be working closely with the co-founders. The role is ideal for someone who enjoys problem-solving and has a keen interest in building a SaaS product.

- Developing the mobile application and features using React Native
- Designing a modern highly responsive web-based user interface
- Building reusable components and front-end libraries for future use
- Translating designs and wireframes into high-quality code
- Learn and understand user interactions
- Optimizing components for maximum performance across a vast array of web-capable devices and browsers
- Coordinating with various teams working on distinct layers
- As a React.js developer, you will be involved from conception to completion with projects that are technologically sound and aesthetically impressive.

### Why Candidate should apply for this position

We're achieving our mission by creating tools that allow day-to-day operations to be handled remotely by business owners. We are looking for entrepreneurial folks to help power the 17,000,000,000 offline businesses across Southeast Asia.

- Learn from the best: CEO - who exited 2 venture-funded companies by the age of 30, talented CTO and other amazing colleagues
- Flexible working hours, there is a daily standup meeting, we work in sprints
- Work anywhere: Options to work from home if you'd like
- 13th month and bonus
- 14 days of annual leave
- Yearly team activity
- Fully Equipped: If you need software or hardware, just let us know
- Generous vacation policy: Your well-being matters to us!
- ESOP Options Available: We want to reward you for believing in us!
- Culture of fun: We support your pet projects (and work with you on them)

### Interviewing Process

1st: Quick phone screen - 2nd: Live coding test + technical interview - 3rd: Culture fit

### Report To

CEO and Lead/Principal Engineer

### Contact
Skype: natsuyuki91
Telegram: @leephuongg
Zalo: +84926953942
Connect Linkedin: https://www.linkedin.com/in/leephuong

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
