### ISSUE TITLE
Titan Technology - Automation QA - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2540]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable 

## Requirements

* 3+ Years QC/QA 
* Java
* Automation Testing (Selenium, Cucumber, etc.) 

## Skills

* At least 3 years of work experience as QC/QA.
* At least 1 year's experience in Java.
* At least 1 year's experience in Automation testing on Web App, Mobile App (Selenium, Cucumber, TestNG, Appium, etc.)
* Have deep knowledge of Web servers and Web services.
* English skills (Reading & Writing)

### You’ll be responsible for

**We are looking for Automation QA Engineer who will be the key member to drive QA and improve automation framework to meet client's expectation.**
* Follow test cases that provide by the manual team to develop test scripts
* Oversee the creation and execution of test cases and test scripts.
* Guide the automation testing efforts and liaise with leads to ensure any developed QA frameworks are reusable across similar technologies.
* Evangelize the QA practice and the QA professionals in the team.
* Communicate status, risks, and issues to senior management and team members.
* Drive QA process and standards changes to benefit high-performing teams.
* Daily / Weekly / On-demand report to leader the progress and status of the assigned tasks.
* Ensure the assigned tasks to be performed on time and with high quality.

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Interesting engineering projects
* Fintech for  Canadian Client

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **an.ngo@titancorpvn.com** 
** Subjects: **Github - Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
