### ISSUE TITLE
Titan Technology - Angular2+ Developer - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2541]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam
* 50 Cuu Long Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable 

## Requirements

* 3+ Years in web applications
* JavaScript, HTML, CSS, jQuery
* Angular 2+

## Skills

* **At least 03 years of work experience in developing web applications.**
* **Experience with Angular, HTML, CSS, JavaScript, jQuery.**
* Good knowledge about software development life cycles.
* Good logical thinking.
* Highly responsible in work, proactive, self-organized, and good teamwork spirit.
* Experience with PHP, Symfony, MySQL is a plus.

### You’ll be responsible for

* Perform assigned tasks independently.
* Ensure the assigned tasks to be performed on time and with high quality.
* Investigate and analyze the requirements.
* Code, implement, unit test, maintain and troubleshoot web application.
* Comply with the established coding quality standards of the company.
* Review design/technical solutions/code.
* Weekly and/or on-demand reporting to supervisor.

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **recruitment@titancorpvn.com** 
** Subjects: **Github - Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
