### ISSUE TITLE
Titan Technology - Senior Security Engineer (SIGN-ON bonus) - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2542]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam
* 50 Cuu Long Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable 

## Requirements

* Linux & Windows
* Cloud (Azure, AWS) 
* Experience in IT System Admin or Security Engineer

## Skills

* **At least 1 year of experience working in Cloud (AWS, Azure) environment.**
* **At least 5 years of experience in IT system admin and/or security engineer.**
* Strong knowledge of network and firewall.
* Strong knowledge of Linux and Windows.
* Degree in System/Networking or relevant.
* Determining and finding information technology solutions if needed.
* Good at teamwork, capable of managing team members.
* Good analytical and problem-solving skills.

### You’ll be responsible for

* Daily work with customer to define, develop and maintain an Information Security Management System (ISMS, SOC2) including planning, policies, standards, and procedures.
* Implement the security solutions for application, cyber, network and keep the checks on the compliance with the standards (SOC2 or ISMS).
* Follow the Risk Management and conduct security annual risk assessment and risk treatment and continues improvement.
* Maintain secure architecture which includes infrastructure secure architecture, application secure architecture, and information/data security architecture.
* Maintain Security Vulnerability Management standard, and implement related tools and conduct the scan result reporting and follow-ups for remediation.
* Maintain company application scan program and deploy related tools and conduct the scan result reporting and follow-ups for remediation.
* Maintain the identity and access management procedure and perform periodic access reviews and assess privilege access requests.
* Responsible for security audit activities.

### Why it would be awesome to work with us

* **SIGN-ON BONUS 1 MONTH GROSS SALARY FOR CANDIDATE JOIN BEFORE JULY 1ST**
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **recruitment@titancorpvn.com** 
** Subjects: **Github - Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
