### ISSUE TITLE
Titan Technology - DevOps Engineer - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2543]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam
* 50 Cuu Long Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable 

## Requirements

* Azure, AWS, or Office 365
* Cylance, McAfee Cloud, Palo Alto, or Burp Suite Enterprise.
* WSUS (Cloud), Azure Account Automation

## Skills

* Experience on the platform: Azure, AWS or Office 365
* Experience in monitoring tool: New Relic, Splunk
* Experience in security tools: Cylance, McAfee Cloud, Palo Alto or Burp Suite Enterprise.
* Experience in patch management: WSUS (Cloud), Azure Account Automation
* Experience in scripting: Bashshell, Powershell, Python, .NET, Json or Terraform.
* Experience in High Availability environment (Cloud)
* Familiar with process tool: Jira, Confluence or Azure DevOps (VSTS)
* Good English skills
* Excellent analytical and problem-solving skills.
* Proactive, well self-organized and responsible in work.
* Able to self-investigate new technology
* Co-operative, careful, meticulous, patient.

### You’ll be responsible for

* Perform assigned tasks independently
* Able to use the admin panels in Azure and AWS to spin up VMs
* Able to deploy software to those VMs using our DevOps process
* Able to monitor and troubleshoot the VMs as necessary
* Manage the deployment process
* Work with monitoring software to ensure everything is healthy
* Analyze problems and complete detailed reports
* Daily / Weekly / On-demand report to Leader the progress and status of the assigned tasks
* Ensure the assigned tasks to be performed on time and with high quality

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Interesting engineering projects
* Fintech for  Canadian Client

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **recruitment@titancorpvn.com** 
** Subjects: **Github - Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
