### ISSUE TITLE
Titan Technology - Intermediate/Senior .NET Developer (SIGN-ON bonus) - HCM - FT

### ISSUE THREAD

**Issue by AnngoTiTanCorp** [awesome-jobs/vietnam#2544]
## Location

* 40 Lam Son Street, Ward 2, Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable 

## Requirements

* 3+ Years 
* C# 
* .NET

## Skills

* **At least 3 years of work experience in developing web applications.**
* **Experienced in .NET and/or .NET Core**
* Have good knowledge about Object-Oriented Programming (OOP).
* Experienced in Git or other source control systems.
* Good English skills.
* Good time management, communication, and problem-solving skills.
* Good teamwork spirit and logical thinking.

### Ideally

* Proactive, well self-organized and responsible in work.

### You’ll be responsible for

* Fintech project of a Canadian client.
* Code, implement, unit test, maintain and troubleshoot web application.
* Comply with established coding quality standards of the company.
* Participate in R&D, training, knowledge sharing activities.
* Follow the project and organization processes, policies, and regulations.
* Ensure the assigned tasks to be performed on time and with high quality.

### Why it would be awesome to work with us

* **SIGN-ON BONUS 1 MONTH GROSS SALARY FOR CANDIDATE JOIN BEFORE JULY 1ST**
* Competitive salary depending on skills and capabilities;
* 13th-month salary and additional bonuses based on the business performance;
* Performance review twice a year;
* Comfortable working conditions and flexible working time;
* Good career growth opportunities with interesting and challenging projects;
* English, technical and soft skills training courses;
* Additional healthcare insurance and annual health check-up;
* Light beverage and food are available all the time in the office;
* Outdoor activities with company support: sports clubs, team building, happy hour party, birthday, company trip, staff and family events, etc.

### Interesting engineering projects
* Fintech for  Canadian Client

### Contact
* Homepage: https://www.titancorpvn.com/careers
* Email: **an.ngo@titancorpvn.com** 
** Subjects: **Github - Position - Your Name**
* Skype: **live:tuananngo**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
