### ISSUE TITLE
Weploy - Ruby on Rails developers - HCMC - FT

### ISSUE THREAD

**Issue by longnt80** [awesome-jobs/vietnam#2545]
## Location

* Ho Chi Minh City, Vietnam
* Remote (possibility)

## Salary Expectation
* $1000 - $4000

## Top 3 Reasons To Join Us
* 1 month salary Sign-on Bonus + MacBook for everyone 
* 24 Annual leave + 5 sick leave days
* Premium Insurance, Yearly Medical Checkup

### The Opportunity
We are looking for Ruby on Rails Software Engineers, ranging from junior to senior, to join our team in Vietnam. You will be responsible for designing, coding, and writing automated tests. These roles will report to our Development Head in Ho Chi Minh city, Vietnam.

### Your Skills and Experience
You will excel in this role if you:
* Are an awesome human being
* Are pragmatic and not dogmatic
* Are proactive and like to take initiative
* Make data- and research-driven decisions
* Understand what it takes to deliver successful product outcomes
* Have a strong technical background (equivalent to 1+ years of experience)

### Our tech set up
* Ruby on Rails (prior experience mandatory)
* Turbolinks
* Stimulus JS
* Tailwind CSS
* AWS Fargate
* Docker

### Why You’ll Love Working Here
* Accident and Private Health insurance, Yearly medical checkup
* 12 days of annual leave plus 5 days of sick leave
* 10 days of public holidays plus 2 days of Christmas and Boxing Day public holidays
* 13-month salary, Apple MacBook laptop
* Work hours allocated for Innovation and Learning sessions
* Work life balance. Long hours or overtime are not expected.
* Annual performance review providing career growth opportunities
* Direct employment with Weploy as part of its wider Engineering team.
* Exciting industry space, exposure to Australian tech startup culture
* A team of diverse, fun, and welcoming people
* Opportunity to work with senior staff in Australia, who have worked in leading AU and UK companies such as REA, Redbubble and Deliveroo
* Future opportunities for short-term (3 months) secondment in Melbourne, Australia

## Contact:
Email: **[cong.nguyen@weployapp.com](mailto:cong.nguyen@weployapp.com)**
Skype: **congnguyen0207**

[https://www.weployapp.com/vietnam](https://www.weployapp.com/vietnam)

**Comment by jackie-do** [comment]
Làm về domain gì vậy bạn ?

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
