### ISSUE TITLE
goGame - DevOps Engineer - HCMC - FT

### ISSUE THREAD

**Issue by minhdang86** [awesome-jobs/vietnam#255]
## _Location_
- Saigon, Vietnam (Address: Ung Van Khiem Street, Binh Thanh Dist, HCMC)
## _Salary Expectation_
- Negotiable - Can be up to **$2000**
### **Technical Requirements**
- Diploma / Bachelor Degree in a relevant field;
- 3+ years experience maintaining, deployment of production software systems;
- Strong background in Linux/Unix Administration with advanced shell scripting;
- Experience with automation/configuration management, virtualization and fine tuning of servers;
- Ability to use a wide variety of open source technologies and Aws Cloud Services; 
- A working understanding of code and scripts (Bash, Java, PHP, Python, Perl and/or Ruby);
- Experience with monitoring systems such as Sensu, Nagios, Grafana, Graphite, InfluxDB, StatsD and cAdvisor;
- Experience running Docker containers;
- Knowledge of router/switch or load balancer configuration;
- Knowledge of L2/L3 networking;
### **Desired Soft-skills**
- Experience working in a large, mixed physical/virtual environment;
- Strong written and verbal communication skills;
- Independent thinker; result-focused;
- Have a sense of humour and a drive to win!;
- Previous experience in a technology or gaming industry organization would give you an additional edge!
## _Responsibilities_
- Requirements gathering, system design, preempt server needs and reduce downtime for servers;
- Create, implement, deploy, troubleshoot and maintain software systems;
- Solid working experience with the latest in Amazon AWS Cloud Technologies;
- Developing high-scale / high-load / distributed solutions;
- Work on understanding and fixing bugs as well as improving deployment application performance;
- Continuously discover, evaluate, and implement new technologies to maximize deployment efficiency;
- Document the process for deployment of application servers;
- Automation of the deployment tools for speed and stability of the servers.
## _Benefits_
- International workplace
- goGame have FUN!
- goGame is offering you a chance to join our team of goGetters who are passionate on all-things goGame and is driven to make good games GREAT! 
- Equipped with high-specification desktops for game coder/designer
- Working time: 9:00 - 18:00 Monday - Friday
- Teambuilding and amazing company activities
- Chance to work with foreign clients and projects
- Professional working style
## _Contact_

Please send your CV via my personal email minhdang86.le@gmail.com or via HR email aihang.nguyen@gogame.net 

Thank you.

**Comment by joneslee85** [comment]
@minhdang86 thanks for posting with us. Please revise:

* markdown header format

Are you the HR people of the company? If not, can you please provide the HR or the CTO/CEO email here?

**Comment by minhdang86** [comment]
Thks for your review. I've edited my JD format.
