### ISSUE TITLE
[HOT] Fullstack Engineer - Salary up to $5000

### ISSUE THREAD

**Issue by SetelAssignment** [awesome-jobs/vietnam#2550]
## Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* Up to $5000/month 

## Requirements
* 3+ years as a Software Engineer for a large-scale, mobile-first product
* Great verbal and written communication skills horizontally and vertically
* Deployed mobile-responsive and highly reactive front end web applications that serves thousands of concurrent users
* Experience with Material Design, Angular and ReactJS Framework
* Experience with microservice architectures and understand scaling and concurrency concerns.
* Built, deployed and managed high-performant backend APIs on Node JS
* Followed coding best practices such as SOLID, Functional Programming or DDD
* Working knowledge of Javascript and/or Typescript
* Data are stored in MongoDB/DynamoDB, MySQL/Postgres, and cached in Redis/Memcached
* Familiarity with Docker containers using Swarm / Kubernetes orchestration
* Used application performance monitoring tools e.g. New Relic, Prometheus, DataDog etc
* Used common tools for software development (Git, Slack, JIRA)
* Built Payment / Rewards & Loyalty / Marketplace / e-Commerce / SaaS products
* Hands-on experience with Amazon Web Services (AWS) toolset is a bonus
* Experience working with a distributed team across multiple time zones

### Responsibilities
* Implement application architecture in conjunction with the engineering leads.
* Work with product managers, and engineering leads to understand application requirements, identify solutions, and determine feasibility & timelines
* Build & deploy web applications and integrate with internal backend and external APIs
* Build & deploy various microservices and APIs as well as develop applications that depend upon them
* Follow best practices alongside your team for all aspects of the software development lifecycle, including process & conventions
* Write unit test cases and follow code quality across entire engineering teams
* Monitor API performance and suggest methods to improve
* Provide support for resolving customer issues and finding root cause
* Contribute to the continuous improvement of engineering processes and tools
* Regularly communicate with engineering leads on project and delivery status

### Why it would be awesome to work with us
* Very competitive package (above market average).
* Become a key member as our team is growing rapidly with resources and sponsors from Petronas (Malaysia's only Global Fortune 500 company).
* You will work alongside talented engineers who previously worked at Amazon, Booking.com, Grab and learn from them.
* We set a high quality bar for coding and have a strong engineering culture. You will work on truly SOLID source code and services following Jeff Bezos's API mandate, in a cross-functional team operating in Agile/Scrum.
* Opportunities to work on-site in Malaysia
* Flexible time. 

### Contact
* Send your email to thomas.dao@setel.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
