### ISSUE TITLE
[HOT] Automation QA - Salary up to $3000

### ISSUE THREAD

**Issue by thomas-dao** [awesome-jobs/vietnam#2551]
## Location

* 100 Nguyen Thi Minh Khai, Ward 6, District 1, Saigon, Vietnam
* Full-time

## Salary Expectation

* $3000/month

## Requirements
* 3+ years of experience as a QA Engineer with at least 1 year in Automated QA
* Hands-on experience with testing mobile applications, web applications, and REST APIs
* Strong knowledge and practical experience with client-server architecture
* Experience with Crashlytics, Instabug or similar error reporting services
* Familiar with Performance and Load testing such as k6, JMeter etc.
* Strong knowledge of software QA methodologies, tools and processes
* Hands-on experience with both white box and black box testing
* Experience working in an Agile/Scrum development process
* Practical experience with bug tracking systems (JIRA)
* Highly detail-oriented when writing test cases for negative and edge-cases
* Experience with Payment / Rewards & Loyalty / Marketplace / e-Commerce / SaaS apps would be a plus
* Experience working with a distributed team across multiple time zones

### Responsibilities
* Review requirements, specifications, and design documents
* Create manual test cases, checklists and other types of test documentation
* Write automation test scripts for API, Mobile and Web based on OpenSource frameworks like Selenium, Appium and Cucumber among others
* Estimate the required testing time for each user story
* Perform functional and regression tests on mobile/web clients and backend services
* Prepare test summary reports
* Collaborate with, and provide status updates to, SW Engineers and Product Leads
* Monitor app performance and suggest methods to improve
* Provide support for resolving customer issues and finding root cause

### Why it would be awesome to work with us
* Very competitive package (above market average).
* Become a key member as our team is growing rapidly with resources and sponsors from Petronas (Malaysia's only Global Fortune 500 company).
* You will work alongside talented engineers who previously worked at Amazon, Booking.com, Grab and learn from them.
* We set a high quality bar for coding and have a strong engineering culture. You will work on truly SOLID source code and services following Jeff Bezos's API mandate, in a cross-functional team operating in Agile/Scrum.
* Opportunities to work on-site in Malaysia
* Flexible time

### Contact
* Please send your CV to thomas.dao@setel.my

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
