### ISSUE TITLE
AZoom Vietnam - Backend/ Front/Fullstack (Nodejs, VuJS) - Hanoi - FT - Upto 35M 

### ISSUE THREAD

**Issue by DaoTuanAnh278** [awesome-jobs/vietnam#2556]
## Location

* Vietnam
* backoffice

## Requirements
* 1+ years experience

## Skills
Nodejs, VuJS, ReactJS.

### Contact
gmail: daotuananh278@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
