### ISSUE TITLE
NUS Technology - Fullstack Web Developer - HCMC - FT

### ISSUE THREAD

**Issue by ThamDo** [awesome-jobs/vietnam#256]
# Location
- Scetpa Building, 19A Cong Hoa Street, Wall 12, Tan Binh District, HCMC
## Salary Expectation
- Very attractive
### You will:
- Be part of a dynamic and helpful group
- Be involved in the process of clarifying customer's needs, designing and implementing them in accordance with coding standards and conventions
- Be encouraged to suggest ideas
- Be involved in testing, deploying application and rapidly resolving issues
  *Contribute ideas and play an important role in the growth of the company
## Technical requirements:
- Bachelor degree in Computer Sciences / Information Technology, or equivalent
- Experience on designing and building Web applications using Ruby on Rails or PHP.
- Strong experience on at least one MVC framework such as: Ruby on Rails, Yii, Laravel, Zend...
- Good understanding and experience on browser-side technologies such as HTML5, Javascript, CSS3, etc
- Experience on using Bootstrap, jQuery
- Familiarity with Javascript frameworks (Bootstrap.js, Backbone.js, Underscore.js, etc) is a huge plus
- Comfortable with using Linux operating systems
- Deployment platforms (Heroku, AWS, Engine Yard...) experience is a big plus
- Intermediate English, especially reading / research skill
- Active team player – active communication, open mind, and friendliness
- Details orientation
- Eager-to-learn mindset
### Why You'll Love Working Here:
- Clear personal and career development path
- More-than-enough support to improve expertise
- Frequent tech training and techtalks
- Young and friendly working environment
- Countless team building fun activities
- Company trips on yearly and sudden basis
- Attractive salary with clear review plan
- Free lunch, free parking, coffee break
- Football club, English club
- Other events: staff birthday, mid-year, anniversary, YEP, etc.
### Contact
- Email: hr@nustechnology.com
- Skype: tham.do5
- Phone: 0906 984 088

**Comment by joneslee85** [comment]
Please revise the post title format to comply with our guideline

**Comment by ThamDo** [comment]
joneslee85 I revised post title as your guideline. Thanks
