### ISSUE TITLE
Fetch Technology- Java Manager- HCM- FT

### ISSUE THREAD

**Issue by Thusky68** [awesome-jobs/vietnam#2560]
## Location

* Binh Thanh, Saigon, Vietnam

## Salary Expectation

* $1500-2500/month or range

## Requirements
* 5+ years of software development experience, preferably in delivering large scale engineering products & services.
* 2+ years of engineering management experience.
* Ability to clearly communicate high level strategy and technical details effectively.
* Strong bias for action; ability to juggle multiple priorities and build a sense of urgency in a dynamic environment.
* Ability to manage, support and grow a team of talented software engineers.
* Experience working in a fast paced, startup environment.
* From technical software development aspects:
- Familiarity with the entire web application stack (specifically **backend and database, frontend experience** would be a bonus).
- Experience with programming languages such as **Java**, Python, Javascript.
- Sound in computer science fundamentals including data structures, algorithms and multithreading.
- Knowledge of web application frameworks, relational and NoSQL data stores.
- Knowledge of **microservices**, build and deployment concepts.
- Good understanding of the HTTP protocol and networking.

### Responsibilities

* Lead a team of software engineers by assisting with their professional and technical development.
* Developing, testing and maintaining the backend system by implementing the features required.
* Build a large-scale web application with high availability, security.
* Design database architecture, translate features to an efficient model schema and business.
* Programming in a clear and structured manner while adhering to the existing architecture and guidelines.
* Building reusable code and libraries for future use.
* Performing all other related tasks. 

### Why it would be awesome to work with us
Being a Engineering Manager at Fetch Technology, you will experience a youthful, flexible and creative work environment: 

* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

### Contact
Email: lethu@fetch.tech
Skype: tranthilethu890@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
