### ISSUE TITLE
Fetch Technology- Senior React Native Developer- HN- FT

### ISSUE THREAD

**Issue by Thusky68** [awesome-jobs/vietnam#2561]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1000-$2500/month or range

## Requirements
* From 3+ years of experience in React Native.
* Highly organised driven individual with skills in an agency environment.
* Good communication skills in English. 
* A commitment to quality and a thorough approach to work.
* Good teamwork and reliability.

### Responsibilities

* Perform a technical analysis of requirements.
* Produce a solid, detailed technical design.
* Write clean, modular, robust code to implement the desired requirements with little or no supervision.
* Work with the other partners to triage and fix bugs with rapid turnaround.
* Contribute ideas for making the application better and easier to use.
* Develop and maintain mobile related application on iOS/Android using React Native.
* Active participation in customer/partner design meetings and general engagements.
* Ensure on time, on budget, and the quality of the product. 

### Why it would be awesome to work with us
Being a Senior React Native Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 

### WORKING TIME & LOCATION
3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau ward, Cau Giay District, Hanoi.
From Monday to Friday, 9AM - 6PM.

### Contact
Email: lethu@fetch.tech
Skype: tranthilethu890@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
