### ISSUE TITLE
Fetch Technology - Senior Front-end Developer (Angular) - HN - Fulltime

### ISSUE THREAD

**Issue by haiyen402** [awesome-jobs/vietnam#2562]
**Location**
- Duy Tan, Ha Noi

**Salary Expectation**
- 1000 - 2500USD/month

**Responsibilities**
- Develop high-performance web applications.
- Analysis requirements and maintain technical documentation.
- Contribute ideas & solutions to the products.
- Write clear and maintainable code.
- Participate in all phases of the product development process including analyzing user requirements, designing system architecture, coding, testing and deployment. 
- Build front end for advanced user experience.
- Build reusable components/modules for websites with responsive design.
- Work with API endpoints or Socket for dynamic content updating.
- Ensure UI/UX of developed pages and software with near pixel-perfect design.
- Develop and optimize front end UI to ensure the application is rendered consistently in cross-browser environments.
- Cooperate to connect front end software development with expert backend team. 

**Requirements**
- 3+ year experience in developing web application.
- 3+ year experience in Angular (prefer v9 and higher) and HTML, CSS, JavaScript.
- Experience using JavaScript frameworks/libraries.
- Knowledge in responsive design technique and front-end optimization techniques.
- Experiences in UI programming are appreciated.
- A team player who can work both as an individual and as a team.
- A passion for software development, new trends and technologies in IT.
- Able to communicate in English.

**Why it would be awesome to work with us**
- Attractive salary and annual salary review.
- Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
- Extensive on job training, you will always have a chance to work with new emerging technologies.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
- 12-day annual leave per year.
- 13th month salary.
- Enjoy diversified activities: �Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
