### ISSUE TITLE
Fetch Technology - Game Producer - HCM - Fulltime

### ISSUE THREAD

**Issue by haiyen402** [awesome-jobs/vietnam#2565]
## Location
- Binh Thanh, HCM

## Salary Expectation
- upto 2400USD

## Requirements

- 3 years of game producer experience.
- Bachelor's degree in game design, computer science or computer engineering.
- Enthusiasm and knowledge of the industry.
- Relevant certification in programming languages.
- Portfolio of sample projects.

### Responsibilities

- Creating innovative games for entertainment or education purposes.
- Conceptualizing and developing characters, rules, settings and stories for new games.
- Pitching new game ideas to executives and clients.
- Managing multiple teams and projects.
- Prototyping new games.
- Following industry trends and good practices.
- Monitoring work and cash flows.
- Developing design and gaming protocols.
- Doing quality control.

### Why it would be awesome to work with us
Being a Game producer at Fetch Technology, you will experience a youthful, flexible and creative work environment: 
- Attractive salary and annual salary review. 
- Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
- Extensive on job training, you will always have a chance to work with new emerging technologies.
- Full social insurance, PVI health insurance & unemployment insurance according to Vietnam Labor Law.
- 12-day annual leave per year.
- 13th month salary.
- Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

### Contact

- Skype: trinhthihaiyen201096@gmail.com
- Email: haiyen@fetch.tech

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
