### ISSUE TITLE
LocalizeDirect - Senior frontend developer - HCM - FT

### ISSUE THREAD

**Issue by hieuhtr** [awesome-jobs/vietnam#2566]
## Location

* Centec Tower, 72 Nguyen Thi Minh Khai Street, HCMC, District 3, Ho Chi Minh
* Remote (at this time -  covid19)

## Salary Expectation

* 1,500 - 2,200 USD

## Requirements
* Deep experience in ReactJS, React Hook, Redux
* Strong knowledge of Javascript in prototypal, ES6, HOC, asynchronous/functional programming
* Knowledge of component life-cycle and state management
* Experienced in RESTful API integration
* Efficient with customising HTML5, CSS3
* Proficiency with Responsive Web Design (using Bulma or Tailwind CSS is a plus)
* A get-things-done and passionate kind of developer

It's nice if you also have:
* Good writing and verbal English skills
* Experience with Yup, Formrik, React DnD, Immutablejs
* Experiences with Websocket, Git and Yarn

## Responsibilities
Do you want to create an advanced web application's UI that **reaches the browser’s limit?** 

We're building a **powerful enterprise product for the top game and web studios** and looking for a front-end developer with experience in developing advanced and complex components.

After joining us, you will:
* Develop new user-facing features using ReactJS
* Improve and optimize UI for maximum speed and responsiveness
* Keep end-user in mind and suggest ideas and improvements on features
* Work with UX designer to ensure technical feasibility
* Collaborate with back-end developers for integration
* Research and apply new & cool technologies

## Why You'll Love Working Here
* 100% online recruitment process. We want you to be safe and healthy in this Covid-19 turbulence.
* Premium health care programs (insurance, health check, sports)
* A long-term career with plenty of opportunities for job advancement
* Allow you to grow and be the owner of your work
* 13th-month salary
* Flexible working hours
* 5 day work week
* More annual leaves than Vietnamese labor law
* Daily tea break, weekly snacks, monthly dinner, etc
* Yearly company retreat. Last year we did it at Fusion Resort Cam Ranh (try Googling the place, we believe you will love to join us being there)
* MacBook Pro
* We're fun, friendly, fast, and flexible

### Contact
Homepage: https://www.localizedirect.com AND https://www.gridly.com
CV to: gn@localizedirect.com (Giang Nguyễn)
Email title with source from **Webuild**, thank you

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
