### ISSUE TITLE
Biomatters - Fullstack Engineer - New Zealand - FT

### ISSUE THREAD

**Issue by ZeroX-DG** [awesome-jobs/vietnam#2567]
## Location

*  On-site Auckland, New Zealand

## Skills and experience

- At least a Bachelor degree in Computer Science or equivalent experience. We seek applicants from a range of experience levels, graduate through to senior.
- Great written and verbal English
- Experience with AWS, Java, Scala and Front-end TypeScript would be ideal.
- Knowledge of Biology is not required, but would be beneficial (we have a lot of Biologists who are happy to share their passion, if you don't have the domain experience).
- Must be based in Auckland, New Zealand; or be willing to relocate.
- Must be eligible to work in New Zealand.
- Hitting 100% across all of the above areas is not essential: enthusiasm and a willingness to learn/adapt/create is.

## Responsibilities

- Develop and maintain Geneious cloud products across their various components, mainly in Java, TypeScript and Scala.
- Take full ownership of what you build by practicing DevSecOps.
- Collaborate regularly with colleagues and customers to establish requirements and iterate on designs.
- As part of a cross­-functional development team, take on testing, documentation and support when needed.

## Why it would be awesome to work with us

We are a down-to-earth and honest bunch, and while we're often in t-shirts, we are professional and passionate about our work. Once an employee joins Biomatters, they tend to stick around.
Why? Because we:

- Are building software that we believe will meaningfully make the world a better place by contributing to primary scientific research and improving human health.
- Have an open-plan culture where you can chat with the CEO or anyone else.
- Allow for very flexible working arrangements.
- Offer health, life and critical illness insurance.
- Take care of you with fresh fruit delivered twice a week, a well-stocked drinks fridge and a proper espresso machine.
- Hold "EvoLab" days, where everyone in the company can work on anything they believe will evolve Biomatters (and the world) into a better place.
- Have various social activities ranging from weekly team lunch to card game, and especially we play Hacky Sack every day!

### Contact
Homepage: https://www.geneious.com/
CV and cover letter (optional) to: viethung@geneious.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
