### ISSUE TITLE
Parcel Perform - Senior/Junior Python Developer - Saigon - FT

### ISSUE THREAD

**Issue by kentnguyen** [awesome-jobs/vietnam#257]
## Requirements
- At least 2 years (for senior), solid experience working with **Python** language and frameworks.
- Strong knowledge of scaling practices such as in-memory databases, load balancing, caching, etc.
- Worked with at least one project using a MQ as communication hub. If you start one today, that still counts.
- Fluent in RESTful and real-time communication protocols.
- Familiar with AWS stack to get the most out of infrastructure.
- Wide exposure to multiple technology stacks is an advantage, we love full stack guys (and girls!).
- Experience with building microservices architecture.

`T3VyIGN1cnJlbnQgcHJvamVjdCB1c2VzIGEgbWl4IG9mIFB5dGhvbiBEamFuZ28gYW5kIE5vZGVKUyBpbiB0aGUgYmFja2VuZCBhbmQgQW5ndWxhckpTIGluIHRoZSBmcm9udCBlbmQuIFRoZSBwcm9qZWN0IGp1c3QgZ290IHN0YXJ0ZWQuIEl0IGlzIGEgbGFyZ2UgZGF0YSBhbmFseXRpY3Mgc3lzdGVtIGJ1aWxkaW5nIGZyb20gc2NyYXRjaC4gV2UgY291bGRuJ3QgZGlzY2xvc2UgbW9yZSBpbmZvcm1hdGlvbiwgYnV0IGlmIHlvdSB0YWtlIHVwIHRoZSBpbnRlcnZpZXcsIHdlIHdpbGwgdGVsbCB5b3UuIA==
`
## Salary Expectation
- $1200-1700/month
## What is Parcel Perform

Parcel Perform is a partner of **[Silicon Straits](http://siliconstraits.vn)**, sharing the same office, culture and benefits as Silicon Straits. _(Yes, it might be confusing, speak to us to find out more)._

We are on a mission together to change the e-commerce logistics world and are in it for the journey and the opportunities it offers to all of us. Become part of the team and experience the excitement of contributing to this incredible team effort.  

You'll get:
- The opportunity to work in a fast growing, super exciting and innovative business that will revolutionize the e-commerce logistics industry. You will develop a global product that will become a key platform behind successful e-commerce logistics worldwide. 
- The experience to work with the latest technologies, tools and frameworks that will make our platform unique and competitive in the market. We will go the extra mile to come up with the most innovative solutions.
- The ability to continuously learn and develop in an international setting with you being a critical driver behind the success of us achieving our mission.
- An environment where nobody ever stops growing, and focuses on succeeding - we continuously work with you on your strengths and weaknesses across many important dimensions, and look at ways for you to address them and further your development
- All the usual perks you’d expect from a fast growing company like free lunch, annual wage supplement, various training programs, free weekly football, free fruit, amazing offices including sleeping rooms, annual company retreats (e.g. Dalat, Cambodia etc.)
### Contact

If this sounds like you, do get in touch by September 30th, 2016! We would like to personally get to know you, discuss your visions & ideas. As a first step, please submit your updated CV to hr@siliconstraits.com.

**Comment by kentnguyen** [comment]
@joneslee85 we renewed our posting, could you help to add Junior tag as well?

**Comment by joneslee85** [comment]
@kentnguyen updated
