### ISSUE TITLE
iRuuza - Full Stack Developer / RoR / React - Full Remote - FT

### ISSUE THREAD

**Issue by nao215** [awesome-jobs/vietnam#2571]
## About Us
**Less Coding More Innovation!!** ~ Brand new software development ~

We are nocode start up and incubator of a lots of web service. our business are
- Create code automation platform. *not open now. using only inside company
- Create web service or native app (client work) using code automation tool by us.

And our developers is really awesome :) some one is from Amazon AWS, someone is from unicorn venture company. Everyone is so kind and supportive. We really respect  each other so want to welcome if you can respect us and we can respect you :)

## About This Job
help our clients to build software (web, ios, android) with our code generator. So you would do 
- our client work *ex. create dating app, saas platform...etc
- create source code generator and automate coding!!

## Location
* Full Remote

## Work condition
- full remote and you can work from all over the world
- HQ is in Tokyo. We may ask meeting in JST but we can make arrangement for meeting schedule.

## Salary Expectation
* $25k-$45k/month

## Requirements
* Ruby, RoR
* React, React Native
* MySQL
* 3+ years Software Engineering experience

### Must Have
- RoR skills (at least 2-3 years)
	- you need to have knowledge about MVC, service, decorator, serializer, or any other architecture
	- well know about database (MySQL, postgresql...etc)
  - Restful architecture
  - unit testing
- React skills (at least 1-2 years)
	- good knowledge of redux, component life cycle, react hook
	- good at frontend development. implement with good design will be needed to *dont need to create design with figma or adobe xd or sketch... etc. but need to implement with these design tools.
- Fluent English

### Ideally
- Experience with Infrastructure with AWS
  - cloudformation, DevOps... etc
- Experience of code automation
- contribution for Famous OSS

### Build the Next Era of Software Development

There are so many problems and difficulty in software development. I know you faced a lots of problem when you create software. Like hard to learn, delay for release, incident with fatal bug. But every company and every person need software. It's obvious. So, currently, in this world, too many demand and less supply. If we can find the better way to create software, If we can change the way of software development, If we can establish brand new software development, things will change and we can build the next era of software development.
Let's Build the Next Era of Software Development with us. And let's create move values of software for everyone.

### Our Value

Love & Success
For our client, for team mates, for everyone, strongly recommend you to love ppl who will work with. Because without love, it's too hard for you to use your important time. Do you know that love is the technology? Everyone want to be loved, but it's rare to know how to love.
I recommend you to read this if you wanna know more [https://en.wikipedia.org/wiki/The_Art_of_Loving](https://en.wikipedia.org/wiki/The_Art_of_Loving)
And once, you can learn how to love, your work will be happier than before. But don't forget about success. Love is just for preparation for success. We need to guide our client to success. Because we are doing business. So love them until their success, and after their success, let's celebrate!
But Don't forget! Most successful company should be us!!

### Professional

We need to be professional because our mission is "Build the Next Era of Software Development". To archive this, we'll require so high level skill. Because only ppl who have high skill can change the software development way. Without software development skill, we cannot change the way of it of course. For project management, for business analysis, for coding, we need a lots of skills. So let's be professional. And not only skill, we need output too of course. Only skill doesn't mean good work. To "Build the Next Era of Software Development", we need to be professional for any work and need to create great output with high skill!

### Hack

Find the break through point. Find Leverage point. Find where we can hack so that we can get great output. Don't be tied up with old idea. Our mission is Build the Next Era of Software Development and to archive this, we need to find the point of hack. Then we can change this software development which is so difficult and having too many problem. Without hack, we'll be just normal or just good company. To be great company, let's find where we can hack, and let's execute it!!
Don't think your current work is the best.
The key is get biggest achievement with smallest effort.

### You’ll be responsible for
- Building code automation tool
- some client work with code automation platform.

### Why it would be awesome to work with us
We are small team, but every engineer is really awesome. One have oss with 100+ stars, One have experience to commit rails/rails repo!

### Interesting engineering projects
I don't need to talk about why our project is interesting. Because if you are good engineer with laziness to write boring code, you would love our vision!

### Contact
Homepage: https://iruuza-inc.com/jobs
Nao: hr@iruuza.com
Angellist: https://angel.co/company/iruuza/jobs/1043144-full-stack-engineer-ror-react-react-native-full-remote-hiring-from-all-over-the-world

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
