### ISSUE TITLE
Senior Full-stack developer

### ISSUE THREAD

**Issue by NhungLeee** [awesome-jobs/vietnam#2573]
##  #Location

* Saigon, Vietnam
* Full-time

## Salary Expectation

* $2500 - 3000/month

## Requirements
* Experienced with ReactJS
* Experienced with Python
* Experience with such tools as Webpack, Git, GitHub, GitLab
* Solid understanding of OOP principles 
* 3+ years Software Engineering experience

### Ideally
* Experience with any of the following:
* Server side web frameworks (e.g. Express, Django, etc.)
* Building user interfaces using JavaScript, HTML, CSS, and front end frameworks (e.g React, Flutter etc.)
* Developing applications backed by RDBMS or NoSQL data stores (e.g.MySQL, Postgresql, etc.)
* Unit testing frameworks (e.g. Mocha, Chai, unittest, pytest, etc.)

### Responsibilities

* Integration of user-facing elements developed by front-end developers with server-side logic;
* Building reusable code and libraries for future use;
* Optimization of applications for maximum speed and scalability;
* Implementation of security and data protection;
* Design and implementation of data storage solutions.

### You’ll be responsible for
Along with the entire development team, you may be responsible for building an LXP (CRM, a virtual classroom, a learning management system, a content management system)

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and supportive colleagues;
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Homepage: https://ooolab.edu.vn/
Email: nhung.le@ooolab.edu.vn
Skype: rosie.307
LinkedIn: https://www.linkedin.com/in/nhung-le-22a41180/ #

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
