### ISSUE TITLE
FPT TELECOM - IOS Developer - Ha Noi

### ISSUE THREAD

**Issue by Tranhath2** [awesome-jobs/vietnam#2574]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* Thỏa thuận
## Requirements
* IOS
* Objective-C/Swift
* 1 năm kinh nghiệm trở lên
-  Có kiến thức về cấu trúc dữ liệu, giải thuật, lập trình hướng đối tượng
- Hiểu và làm việc được với các mô hình MVC,MVVM, các framework: UIKit, StoreKit, MessageUI,CFNetwork…
- Có kinh nghiệm làm việc với Firebase, Realm, RxSwift
- Có kinh nghiệm lập trình giao tiếp giữa mobile với server qua các giao thức TCP/IP, WebSocket, WebService và JSON/XML...
- Đã có ứng dụng đưa lên Apple Store là một lợi thế, ưu tiên các ứng viên đã từng làm các sản phẩm lớn, hoặc các ứng dụng về Ví điện tử hoặc Mobile Banking.

### Responsibilities

- Tham gia vào dự án phát triển và nâng cấp phần mềm của Công ty
- Nghiên cứu, lựa chọn và đề xuất ứng dụng công nghệ mới vào phát triển sản phẩm.
- Tham gia tích hợp ứng dụng với các hệ thống, dịch vụ như Google SDK, Facebook SDK hoặc bên thứ 3 khác.
- Thực hiện các công việc liên quan khác theo yêu cầu của Công ty (trong phạm vi chuyên môn).

### Why it would be awesome to work with us

- Gói thu nhập tương đương từ 14 - 17 tháng lương quy đổi (Thưởng lương tháng 13, lương kinh doanh, tiền mừng tuổi...).
- Đầy đủ các chế độ theo luật lao động hiện hành.
- Chính sách phúc lợi theo quy định của Công ty đa dạng: Chăm sóc sức khỏe định kì hàng năm; Gói bảo hiểm sức khỏe chuyên biệt (FPT Care – Khám chữa bệnh miễn phí tại tất cả các bệnh viện); Các hoạt động tri ân, chăm lo đời sống tinh thần CBNV và Thân nhân...
- Môi trường làm việc thân thiện, cởi mở.
- Cơ sở vật chất và công cụ làm việc hiện đại, tiện nghi.
- ​Nhiều cơ hội phát triển và thăng tiến.
- Văn hóa Doanh nghiệp đặc sắc, sinh động bậc nhất với nhiều các hoạt động hấp dẫn: tân binh, 72 giờ trải nghiệm, teambuilding, thi trạng, hội làng, hội diễn Sao Chổi, sinh nhật FPT, ngày 08/03, ngày 11/11,...
- Hưởng các gói ưu đãi cước khi sử dụng dịch vụ của FPT Telecom.

### Get to know FPT Telecom:

Công ty cổ phần viễn thông FPT - FPT Telecom là nhà cung cấp dịch vụ internet, truyền hình và các dịch vụ gia tăng trên nền tảng internet với hơn 20 năm hình thành và phát triển. HIện tại FPT Telecom đang có mặt trên 59 tỉnh thành trong nước và một số thị trường quốc tế. Với phương châm “mọi dịch vụ trên một kết nối”, chúng tôi kỳ vọng mỗi gia đình việt nam đều sử dụng ít nhất một dịch vụ của FPT Telecom trong tương lai.

### Contact

- Homepage: [https://fptjobs.com/ios-developer-junior--senior-mang-fintech-10507](url)
- Email: hattt54@fpt.com
- Skype: tranha.ql

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
