### ISSUE TITLE
Central Retail VN - Full Stack Developer - HCM - Fulltime

### ISSUE THREAD

**Issue by tiennguyencrv** [awesome-jobs/vietnam#2575]
## Location
* Phu Nhuan dist, Ho Chi Minh city, Vietnam

## Salary Expectation
* $1000 -> $2300/month

## Requirements
* At least 3 years of experience with PHP using any ecommerce platforms such as Magento, Drupal commerce, CSCart…
* Strong with OOP, design pattern
* Strong understanding about ecommerce websites and it's eco system 
* Strong with any MVC frameworks such as Symfony, Laravel...
* Strong experience with MySQL, and PostgreSQL.
* Strong experience with RESTful API.
* Good English, or willing to learn

## Ideally
* Strong analytical and independent thinking to propose and evaluate solutions.
* Experience with customization open source CRM, EPR and Omni Channel is a big plus.
* Experience with CI/CD (Docker, Kubernetes) is plus
* Experience with Microservice is plus
* Experience with other languages, especially NodeJS, React native, VueJs is a plus.
* Knowledge about cloud computing (Azure, AWS, GCP...) is a plus
* Product mindset with Design thinking and Agile

## Responsibilities
* Maintain and develop ecommerce systems (front office website, back office applications: sale, marketing, payment, delivery, warehouse, accounts and finance, loyalty, customer support) follow Agile methodology.
* Integrate with third party systems like Lazada, Tiki, DHL...
* Support junior developer on technical side (if you're strong enough)
* Other tasks assigned by line manager

### Why it would be awesome to work with us
* Central Retail VN is one of the top national retail group. We own Big C, Go!, Nguyen Kim, Lan Chi supermarkets and Hello Beauty, Supper Sport chain stores...Our revenues has surpassed $1B and we still invest more to expand our presentation across Vietnam. We respect every talent who join with us to boost up our online channel as a part of our vision.
* Open, transparent and trustworthy environment. 
* Challenging project with awesome leaders and co-workers.
* Personalize training plan and career development
* Attractive compensation package (you’ll love it)
* Performance review 1 time/ year
* Annual leave: 15 working days/year, and Other leaves/public holidays in accordance with the Labor Law of Vietnam
Periodic medical checkup, Health/Social Insurances & Bao Viet Insurance

### Contact
Homepage: https://www.centralretail.com/
Email: tien.quoc.nguyen02@vn.centralretail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
