### ISSUE TITLE
LOTUS SOFT - Technical Lead  .NET/C#- HCMC - FT

### ISSUE THREAD

**Issue by baonvlotus** [awesome-jobs/vietnam#2576]
## Location

* Binh Thanh, Tp HCM, Vietnam
* Full-time

## Salary Expectation

* $1500-$2500/month or range

## Requirements
* 5+ years experience in software development and have 4 years experience in .NET competence
* Proficient C#, NET Framework/.NET Core Framework, MVC, Web API, Entity Framework, and SQL Server/ Oracle
* Good knowledge of HTML, CSS, JavaScript.
* Having experience of developing the Database: SQL/MySQL
* Good knowledge of Info security in programing and performance optimization
* Good knowledge of programming patterns and principles e.g Separation of Concern, Repository Pattern, UnitOfWork, DRY…
* Good knowledge of architecture design: Microservices, SOA, ...
* Good knowledge of DevOps: CI/CD (eg: Jenkins)
* Good. knowledge testing: Unit-testing, integration testing, UI testing, and automation testing.
* Be able to do code review and support junior developers
* Effective communication in English & Vietnamese (speaking, listening, reading & writing).
* Effective and smooth collaboration with customers, partners, and suppliers

## Responsibilities
As the technical lead, you will be responsible for the technical and quality of Blockchain, Web App & Mobile App products for Australia, UK & Singapore markets. Including multi-million USD projects and Banking projects from Australia:
* Deliver great applications with modern technologies (Blockchain, Fintech, AI, Xamarin & Flutter, DataScience)
* Keep yourself up-to-date with technical skills
* Design technical solution
* Training and mentor the dev team to improve their skill
* Review technical for important projects

## Why it would be awesome to work with us
* Onsite in Australia (several weeks per year)
* Become a Member of the Core Team. You have the right to contribute to the important decisions of the Company.
* Very high Stock bonus = 6%. And an opportunity to buy up more Stock.
* Working directly with other COO, Technical Lead & Managers from Singapore, Australia & Argentina.
* You are trained in monthly training courses for technical (with 70% - 100% of scholarships paid by the Company)
* High total income with KPI Bonus

## Contact
* Home page: https://lotussoft.vn
* CV to: hr@lotussoft.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
