### ISSUE TITLE
Viettel Security - Senior C++ developer - Hanoi - FT

### ISSUE THREAD

**Issue by thutrang0914** [awesome-jobs/vietnam#2580]
## Location

* Hanoi, Vietnam

## Salary Expectation

* up to $2500/month on average

## Requirements
* At least 3 years of experience working on C/C++ projects
* Good understanding of OOP and Design Pattern
* Familiarity with Linux Kernel, Intel DPDK Platform is a big plus
* Logical thinking, system thinking and system architect
* Experience in developing, debugging applications using multi-thread or multi-core
* Ability to work independently as well as work in a team
* Intermediate English level

### Must Have

* C++ 
* ICP/IP Debugging

### Ideally

* Experience working in Agile/Scrum environments

### You’ll be responsible for

* Collaborate with team members to define the issues and solutions
* Analyze, design and build the system
* Develop features following C/C++ specifications for Linux(Ubuntu)
* Review and refactor codes for the best performance of the system
* Define and keep the coding guidelines alive; make sure the team members follow the guide

### Why it would be awesome to work with us
* Opportunity to work for one of the lead groups in Vietnam
* Flexible working hours; open, professional and creative working environment
* Attractive remuneration packages
* Development of skills and knowledge through challenges
* Annual health check
* 12 annual leaves per year and 3 vacation days
* Paid insurance in accordance with the law, after 2 months of probation
* Relaxation activities: Ping pong, Happy hour, Billiards 
### Contact
Zalo/Telegram: 0962.346.837 (Ms. Trang)
Email: trangntt_vcs@viettel.com.vn

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by thutrang0914** [comment]
Hi,
Sorry for this inconvenience. I am an internal recruiter working at Viettel Security and you can see my company email right there. The personal email is just my Skype ID. In case it is not acceptable, please allow me to adjust the information. Thanks

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
