### ISSUE TITLE
BAP IT - SENIOR PROJECT MANAGER (PM) - DA NANG/ HUE - FULLTIME

### ISSUE THREAD

**Issue by HongNguyenDN** [awesome-jobs/vietnam#2581]
## Location

* **DA NANG**
* **HUE**

## Salary Expectation

* **$2000 - $3000/month**

## Requirements
* 5+ years Software Engineering experience
* From **5+ years’ Project Management in Software Development**.
* Japanese (N3 up) or Good at English communication
* Strong with QCD process
* **Strong technical abilities** to understand the true needs and problems of your customers
* Excellent **negotiation skill and project management skills**, including estimating, planning, organizing, and leading
* **Entrepreneurial mindset, Open mind, long-term commitment** and sharing
* **Highly responsible, well-organized, communicative**, proactive, dare-to-lead characters

### Nice to have

* Work experience in foreign companies/ overseas education is a big plus
* Have ability to negotiate with customer
* Have **PMP certification** is an advance

### You’ll be responsible for

**_Great power comes with great responsibilities!_**

* Have a **significant influence on our company’s success**.
* **Work with key stakeholders and project team members** to scope, size, and develop project plans at a task, budget, and resource level
* Be **in charge of major product releases**: timeline, deadlines, coordination between team members, from Business, QC, Systems, and Software Engineering teams
* Track and report, provide internal and external stakeholders;  all levels of management with accurate and timely project information and status updates
* **Manage issues, engage the team** on an ongoing basis to identify and proactively manage project issues, risks, action plans, and implications
* Manage and document proposed and accepted changes to the scope
* Compile historical data from previous Iterations/Releases and provide it for team-wide use and future estimating activities.
* **Mentor team** leads to develop their project management discipline.
* Contribute to **improving processes and support the development of the PMO**.
* Any other tasks assigned by the company from time to time.

### Why it would be awesome to work with us
**_BAP IT Co., JSC - a software services provider (outsource, product, consultant; HQ: Da Nang, Office: HCM, Hue, Japan)
We always aim to bring innovation to all products of our customers as well as our own.
We're on the way growing from 300 to 1000 staff and looking for SENIOR PROJECT MANAGER to join our PMO/ HO in Da Nang and Hue.
If you’re excited to be part of a winning team, BAP is a great place to grow your career._**
* Attractive salary: **2000 – 3000 USD**
* 13th month salary
* 12 days annual leave, 18 days for women
* **Insurance package + extra international health insurance package**
* Opportunity to add dependants to your extra insurance package
* Opportunity to get Life insurance with top performance with  total value up to 20 million dong
* Holiday Bonus
* **Seniority Rewards**: 5,000,000 VND – 30,000,000 VND
* **Performance reward program 2 times/ year**
* **Salaries and performance review 2 times/ year**
* Promotion opportunity
* Team-building, kickoff, release funds
* Opportunity to get 10 million dong/year  for personal development program
* Japanese onsite opportunity
* Gifts for family: Tet, Children’s Day, Mid-Autumn Festival
* Diverse company culture activities: Company trip, Christmas night, Year end party, Women’s day, Men’s day…
* International environment with colleagues from different countries (Vietnam, Japan, Australia, Singapore, etc.).
### Interesting engineering projects
*  **Variety projects industries**, size small to large
* Applied **technologies are new and variety**
### Contact
**_Kindly drop your CV to the email or contact us for more information via:_**
* **Homepage: https://bap-software.net/en/**
* **Email: hongnt@bap.jp**
* **skype: nthong.hr**

**_We hope to meet you soon at BAP. Cheers!_**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
