### ISSUE TITLE
BAP IT - SOFTWARE ARCHITECT (SA) - DA NANG/ HUE - FULLTIME

### ISSUE THREAD

**Issue by HongNguyenDN** [awesome-jobs/vietnam#2583]
## Location

* **DA NANG**
* **HUE**

## Salary Expectation

* **$2000 - $3000/month**

## Requirements
* **5+ years of experience in architecture and design of IT systems**, design patterns, and frameworks
* Minimum  **5 years’ experience in developing software, solid understanding in Web Full-stack development** with ReactJS/ Java/ Nodes/ Python... or Mobile (iOS/ Android…)
* **Experience as a Technical Leader** and designing software solutions
* Expert in **code quality, coding standard, OOP principles, design patterns, common framework, UML, microservice, enterprise architecture** design patterns, and enterprise integration patterns
* Strong ability to **learn and approach new technologies**
* Strong **ability to propose solutions for problems in projects** and guide team to solve it completely
* Familiar with **Scrum Agile**
* Having experience working with **CI/CD**
* Familiar with at **least one cloud computing platform** (Google Cloud Platform, AWS, Microsoft Azure)
* A good team player, positive attitude, proactive, highly responsible and committed
* Analytical mind and problem-solving attitude
* Ability to self-study, self-teach, thinking outside the box
* No hesitation to share, train and speak up

### Nice to have

* Good at English/ Japanese (N3 up) is a big plus
* **DevOps** skills are plus

### You’ll be responsible for

**_Great power comes with great responsibilities!_**

* Software Architecture should be **flexible enough and be adaptable to the changing and varied work settings**.
* **Research new technologies**, multitasking on multiple web projects with other team members;
* **Guide, mentor and develop teams** of skilled software engineers
* **Build up technical knowledge base of architectural** lessons learnt, patterns, common libraries
* **Technical solution:** Interact and work collaboratively with multiple project teams for application architecture and design
* **Develop technical proposal**
* Writing reusable, testable, and efficient code
* **Make technical decisions** that constrain the overall design and implementation for the project
* **Give advices for system** level technical problems
* Other assignments from Line Manager

### Why it would be awesome to work with us
**_BAP IT Co., JSC - a software services provider (outsource, product, consultant; HQ: Da Nang, Office: HCM, Hue, Japan)
We always aim to bring innovation to all products of our customers as well as our own.
We're on the way growing from 300 to 1000 staff and looking for SENIOR PROJECT MANAGER to join our PMO/ HO in Da Nang and Hue.
If you’re excited to be part of a winning team, BAP is a great place to grow your career._**
* Attractive salary: **2000 – 3000 USD**
* 13th month salary
* 12 days annual leave, 18 days for women
* **Insurance package + extra international health insurance package**
* Opportunity to add dependants to your extra insurance package
* Opportunity to get Life insurance with top performance with  total value up to 20 million dong
* Holiday Bonus
* **Seniority Rewards**: 5,000,000 VND – 30,000,000 VND
* **Performance reward program 2 times/ year**
* **Salaries and performance review 2 times/ year**
* Promotion opportunity
* Team-building, kickoff, release funds
* Opportunity to get 10 million dong/year  for personal development program
* Japanese onsite opportunity
* Gifts for family: Tet, Children’s Day, Mid-Autumn Festival
* Diverse company culture activities: Company trip, Christmas night, Year end party, Women’s day, Men’s day…
* International environment with colleagues from different countries (Vietnam, Japan, Australia, Singapore, etc.).
### Interesting engineering projects
*  **Variety projects industries**, size small to large
* Applied **technologies are new and variety**
### Contact
**_Kindly drop your CV to the email or contact us for more information via:_**
* **Homepage: https://bap-software.net/en/**
* **Email: hongnt@bap.jp**
* **skype: nthong.hr**

**_We hope to meet you soon at BAP. Cheers!_**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
