### ISSUE TITLE
[Citigo Software] - [Senior .NET] - [Hà Nội] - [Fulltime]

### ISSUE THREAD

**Issue by Dungnguyen1201** [awesome-jobs/vietnam#2586]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $2000/month

## Requirements
Education, knowledge and professional qualifications: Graduated from university majoring in IT

The skills needed for the job

Experience with .Net/.Net Core

Experience in working with SQL Server, ability to optimize queries is an advantage

Knowledge and ability to apply OOP, SOLID, Design Pattern

Having background knowledge and experience in: JQuery, Angular, Typescript, HTML5/CSS3, HTML/XHTML/XML,CSS, Bootstrap...

Preferred: Knowledge and experience in Kafka, RabbitMQ, Redis, Mongodb

Priority: Experience working with Microservice systems

Priority: Experience in system development with EDA (Event Driven Design), DDD (Domain Driven Design), CQRS

### Responsibilities

Participating in the development of Kiotviet sales management software products.

Coordinate with other departments in business analysis, product development and deployment.

Build product functionality including back-end and front-end for the system > 100K users.

Solve difficult problems about system optimization as well as user operations.

Research new solutions and technologies to improve products

### Why it would be awesome to work with us

Attractive starting salary, competitive, commensurate with capacity and working experience;

Approved for salary increase 2 times/year & 13th month salary according to work results;

Project bonus, quarterly bonus;

Working from Monday to Friday, flexible working shifts; Have 4 more hours off every month

Opportunities for training and good promotion at work. Clear career development roadmap;

Enjoy benefits and regimes as prescribed by law (Holidays, social insurance, health insurance...);

Bonuses for holidays, New Year, birthdays, incentives for relatives, annual travel;

Working in a young and dynamic environment

Provided with high configuration computers, modern working equipment;

### Contact
Homepage: citigo.com.vn
Emai: dung.nt@citigo.com.vn
Skype: dung.nt_13
Linkein: https://www.linkedin.com/in/nguy%E1%BB%85n-th%C3%B9y-dung-b4b218154/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
