### ISSUE TITLE
ZINZA Senior/Junior FullStack (Golang, Ruby, Python)-HN-FT

### ISSUE THREAD

**Issue by vuvu1094** [awesome-jobs/vietnam#2590]
## Location

* HaNoi, Vietnam
* Fulltime

## Salary Expectation
* Senior up to 1500$/month
* Junior up to 800$/month

## Requirements
* Bachelor’s degree in computer science, information systems or a related field.
* Having 1 - 3+ years of experience in web development.
* Experience with multiple programming languages(Python, Ruby, or Golang).
* Experience with Redis, Elasticsearch has knowledge about Caching is a plus.
* Experience with web API technologies: RESTful, Authentication, Authorization, and multi-devices session.
* Experience with Postgresql other (Mysql, NoSQL) is a plus.
* Experience with frontend work: HTML/CSS, bootstrap, SASS, ReactJS, etc
* Good English

## Skills
* Python, Ruby on Rails, or Golang

### Responsibilities

* Work closely with the PM/techlead to build a next-generation web application.
* Design and develop new features for the platform/system.
* Evaluate and clarify product requirements. Participate in reviewing product design.
* Maintain quality standards of excellence and ensure compliance with standards and best practices.
* Mentor junior team members.
* Communicate with other team members to determine the best solutions to difficult problems.

### Salary and Bonus:
* Salary according to ability, up to $1500
* Paid full insurance in accordance with the law, after 2 months of probation
* 13th salary month bonus, calculated according to the number of actual working months paid at the end of the year.
* Review salary 2 times/year
and https://zinza.com.vn/detail-recruitment/lap-trinh-vien-android/

### Allowance:
* Japanese allowance: N1 (nego); N2 (3M); N3(1M)
* Training allowance (for employees participating in training for new employees, or organizing seminars in the company)
Overtime allowance.

### Contact
Email: tuyendung@zinza.com.vn
Homepage: https://zinza.com.vn/recruitments/tuyen-dung/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
