### ISSUE TITLE
[VNEXT] FRONTEND DEVELOPER - Hà Nội - UP TO: $1200

### ISSUE THREAD

**Issue by chali138** [awesome-jobs/vietnam#2592]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $1200/month 

## Requirements

- Có từ 3 năm kinh nghiệm trở lên làm việc ở vị trí Front-end;
- Có từ 3 năm kinh nghiệm làm việc với VueJS hoặc ReactJS;
- Có kinh nghiệm làm việc với các thư viện CSS như bootrap;
- Đã từng làm jQuery;
- Sẵn sàng học ngôn ngữ mới khi công việc yêu cầu;
- Thành thạo HTML, CSS, JavaScript;
- Có khả năm đánh giá UI và phân tích, đề xuất UX.

### Responsibilities

- Lập trình chính trong các dự án gia công phần mềm sử dụng ngôn ngữ Front-end cho khách hàng;
- Tham gia vào tất cả các khâu trong quá trình phát triển phần mềm, bao gồm: tìm hiểu yêu cầu, phân tích, thiết kế, nghiên cứu công nghệ mới…;
- Phối hợp với các thành viên nhóm dự án khác dưới sự điều phối của Quản lý trực tiếp và tiếp xúc trực tiếp với khách hàng.

### Why it would be awesome to work with us

- Mức lương khởi điểm hấp dẫn, cạnh tranh, tương xứng với năng lực và kinh nghiệm làm việc;
- Thu nhập: 13 tháng lương/năm + thưởng dự án, thưởng Tết và các dịp lễ…;
- Xét tăng lương 2 lần/năm theo năng lực và hiệu quả công việc;
- Nghỉ thứ 7, Chủ nhật + Nghỉ phép theo Quy định của Pháp luật hiện hành;
- Được tham gia bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo Quy định của Pháp luật hiện hành và quy định công ty;
- Khám sức khỏe định kỳ 1 năm/1 lần;
- Bảo hiểm chăm sóc sức khỏe 24/24 ( PVI Care);
- Trợ cấp tiếng Nhật và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...);
- Được tham gia các Câu lạc bộ của Công ty: CLB Bóng đá, các CLB Game…..
- Được tham gia các hoạt động tập thể sôi động của công ty: Nghỉ mát hàng năm, Teambuilding hàng quý, Gala cuối năm….

**Đặc biệt**

- Được tham gia các lớp học Tiếng Nhật miễn phí tại công ty;
- Cơ hội làm việc và đào tạo tại Nhật Bản với các ứng viên có tiếng Nhật;
- Làm việc trong môi trường chuyên nghiệp, được hỗ trợ phát huy khả năng, phát triển công việc tối đa.

### Contact
Emai: linhnt@vnext.com.vn
Skype: tranglinh13
Linkein: https://www.linkedin.com/in/tranglinh13/
FB: https://www.facebook.com/tranglinh138/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
