### ISSUE TITLE
[HN-VNEXT] NodeJS Developer - UP TO: $1200

### ISSUE THREAD

**Issue by chali138** [awesome-jobs/vietnam#2593]
## Location

* Hanoi, Vietnam
*Fulltime

## Salary Expectation

* $1200/month

## Requirements

- Có từ 01 năm kinh nghiệm trở lên làm việc với Nodejs;
- Hiểu về lập trình OOP;
- Nắm vững kiến thức về các ngôn ngữ cơ bản: HTML, javascript, CSS, NodeJS…;
- Biết về UML(Activity diagram, Class diagram, Sequence diagram,…);
- Có hiểu biết về design pattern;
- Có kinh nghiệm làm việc với Git, SVN.

### Ideally

Ưu tiên ứng viên có kỹ năng phía dưới là lợi thế:

- Front End;
- Cloud (AWS, GCP);
- Docker;
- Config server (apache, nginx).

### Responsibilities

- Lập trình chính trong dự án lớn gia công phần mềm sử dụng Nodejs cho khách hàng Nhật;
- Phân tích yêu cầu từ phía khách hàng;
- Thực hiện viết tài liệu design cho chức năng được đảm nhận;
- Tham gia quản lý nhóm nếu có khả năng phù hợp.

### Why it would be awesome to work with us

- Mức lương khởi điểm hấp dẫn, cạnh tranh, tương xứng với năng lực và kinh nghiệm làm việc;
- Thu nhập: 13 tháng lương/năm + thưởng dự án, thưởng Tết và các dịp lễ…;
- Xét tăng lương 2 lần/năm theo năng lực và hiệu quả công việc;
- Nghỉ thứ 7, Chủ nhật + Nghỉ phép theo Quy định của Pháp luật hiện hành;
- Được tham gia bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo Quy định của Pháp luật hiện hành và quy định công ty;
- Khám sức khỏe định kỳ 1 năm/1 lần;
- Bảo hiểm chăm sóc sức khỏe 24/24 ( PVI Care);
- Trợ cấp tiếng Nhật và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...);
- Được tham gia các Câu lạc bộ của Công ty: CLB Bóng đá, các CLB Game…..
- Được tham gia các hoạt động tập thể sôi động của công ty: Nghỉ mát hàng năm, Teambuilding hàng quý, Gala cuối năm….

**Đặc biệt**
- Được tham gia các lớp học Tiếng Nhật miễn phí tại công ty
- Cơ hội làm việc và đào tạo tại Nhật Bản với các ứng viên có tiếng Nhật
- Làm việc trong môi trường chuyên nghiệp, được hỗ trợ phát huy khả năng, phát triển công việc tối đa.

### Contact
Emai: linhnt@vnext.com.vn
Skype: tranglinh13
Linkein: https://www.linkedin.com/in/tranglinh13/
FB: https://www.facebook.com/tranglinh138/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
