### ISSUE TITLE
[VNEXT] PHP Developer (Zend,Laravel) - UP TO $1200

### ISSUE THREAD

**Issue by chali138** [awesome-jobs/vietnam#2594]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $1200/month 

## Requirements

- Có ít nhất 1 năm kinh nghiệm làm việc với PHP;
- Có kiến thức nền tảng tốt về OOP, Web Development, DBMS, ORM, Design Pattern;
- Có kinh nghiệm sử dụng một trong các Framework PHP: Zend, Laravel;
- Thao tác tốt với HTML, CSS, JavaScript (Jquery, AngularJS, ...), Bootstrap, JSON, XML,...
- Có kinh nghiệm làm việc với MySQL) - Nắm vững mô hình MVC;
- Thành thạo Git.

### Responsibilities
- Lập trình trong các dự án gia công phần mềm sử dụng ngôn ngữ PHP cho khách hàng Nhật Bản;
- Tham gia vào phát triển các dự án với vai trò developer từ giai đoạn Basic Design, Detail Design, Development, Release;
- Khắc phục sự cố ứng dụng và các vấn đề về kỹ thuật;
- Tiến hành phân tích các yêu cầu về trang web và ứng dụng;
- Phối hợp với các thành viên nhóm dự án khác dưới sự điều phối của Quản lý trực tiếp và tiếp xúc trực tiếp với khách hàng.

### Why it would be awesome to work with us
- Mức lương khởi điểm hấp dẫn, cạnh tranh, tương xứng với năng lực và kinh nghiệm làm việc;
- Thu nhập: 13 tháng lương/năm + thưởng dự án, thưởng Tết và các dịp lễ…;
- Xét tăng lương 2 lần/năm theo năng lực và hiệu quả công việc;
- Nghỉ thứ 7, Chủ nhật + Nghỉ phép theo Quy định của Pháp luật hiện hành;
- Được tham gia bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo Quy định của Pháp luật hiện hành và quy định công ty;
- Khám sức khỏe định kỳ 1 năm/1 lần;
- Bảo hiểm chăm sóc sức khỏe 24/24 ( PVI Care);
- Trợ cấp tiếng Nhật và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...);
- Được tham gia các Câu lạc bộ của Công ty: CLB Bóng đá, các CLB Game…..
- Được tham gia các hoạt động tập thể sôi động của công ty: Nghỉ mát hàng năm, Teambuilding hàng quý, Gala cuối năm….

**Đặc biệt**
Đư

- ợc tham gia các lớp học Tiếng Nhật miễn phí tại công ty;
- Cơ hội làm việc và đào tạo tại Nhật Bản với các ứng viên có tiếng Nhật;
- Làm việc trong môi trường chuyên nghiệp, được hỗ trợ phát huy khả năng, phát triển công việc tối đa.

### Contact
Emai: linhnt@vnext.com.vn
Skype: tranglinh13
Linkein: https://www.linkedin.com/in/tranglinh13/
FB: https://www.facebook.com/tranglinh138/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
