### ISSUE TITLE
[VNEXT] SENIOR ANDROID DEVELOPER - UP TO: $1500

### ISSUE THREAD

**Issue by chali138** [awesome-jobs/vietnam#2595]
## Location

- Hanoi, Vietnam
- Fulltime

## Salary Expectation

* $1500/month

## Requirements

- Có tối thiểu 3 năm kinh nghiệm làm việc với Android Java, Kotlin;
- Thành thạo ngôn ngữ lập trình Android Java, Kotlin;
- Nắm vững kiến thức cơ bản về lập trình hướng đối tượng, UML, thiết kế mẫu (design partern), mô hình MVC, MVVM;
- Nắm vững các kỹ thuật về caching, lazy loading, SQLite, RESTful API, Push Notification.;
- Có thể sử dụng thành thạo 1 số công cụ như SVN, Git;

### Responsibilities
- Lập trình chính cho dự án phát triển ứng dụng có hàng triệu người dùng ở thị trường Nhật Bản và Âu Mĩ;
- Tham gia vào toàn bộ quá trình phát triển sản phẩm;
- Phân tích và đưa ra kết luận về tính khả thi và thời gian hoàn thành; 
- Tham gia review source code, hỗ trợ các thành viên trong dự án;
- Đưa ra các giải pháp kỹ thuật và tối ưu hiệu năng cho sản phẩm.

### Why it would be awesome to work with us

- Mức lương khởi điểm hấp dẫn, cạnh tranh, tương xứng với năng lực và kinh nghiệm làm việc;
- Thu nhập: 13 tháng lương/năm + thưởng dự án, thưởng Tết và các dịp lễ…;
- Xét tăng lương 2 lần/năm theo năng lực và hiệu quả công việc;
- Nghỉ thứ 7, Chủ nhật + Nghỉ phép theo Quy định của Pháp luật hiện hành;
- Được tham gia bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo Quy định của Pháp luật hiện hành và quy định công ty;
- Khám sức khỏe định kỳ 1 năm/1 lần;
- Bảo hiểm chăm sóc sức khỏe 24/24 (PVI Care);
- Được tham gia các Câu lạc bộ của Công ty: CLB Bóng đá, các CLB Game…..
- Được tham gia các hoạt động tập thể sôi động của công ty: Nghỉ mát hàng năm, Teambuilding hàng quý, Gala cuối năm….

### Contact
Emai: linhnt@vnext.com.vn
Skype: tranglinh13
Linkein: https://www.linkedin.com/in/tranglinh13/
FB: https://www.facebook.com/tranglinh138/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
