### ISSUE TITLE
THE EAST WEST INITIATIVE - FULL STACK (Angular, .Net) - Da Nang/HCM

### ISSUE THREAD

**Issue by ajvan2808** [awesome-jobs/vietnam#2598]
## Location

* Saigon, Da Nang
* Onsite, remote available

## Salary Expectation

* Up to $2500

## Requirements
* Angular
* AngularJS, JavaScript, HTML5, CSS, TypeScript
* ASP.NET Core, Azure DevOps, ASP.NET Core (additional skills)
* 3+ years Software Engineering experience
* Good English communication skills.
* Available to working onsite client's office upon requests. 

## Responsibilities
* Designing and developing user interfaces using AngularJS, Angular best practices.
* Migration of a public web application on the front end side from AngularJS framework to current Angular framework.
* Conducting performance tests.
* Consulting with the design team.
* Ensuring high performance of applications and providing support...

### Why it would be awesome to work with us
* Working hours from 9am - 6pm, Monday to Friday.
* 21 paid leave days
* Performance review 3 times/year
* Comfortable and open working environment.
* Opportunities to gain hands-on experience in cutting edge technologies, Extreme programming, Agile methodologies.
* Unlimited potential for career growth as we majored in product development as well as outsourcing globally.

### Contact
Email: hanh.van@eastwest.live
Skype: hanhvan28@outlook.com
Website: eastwest.live

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
