### ISSUE TITLE
[CMC GLOBAL] - [SENIOR JAVA] - [HN&HCMC]

### ISSUE THREAD

**Issue by quocchu** [awesome-jobs/vietnam#2599]
**1. Job Description**

- Demonstrated ability to simplify a complex solution into discrete components to parallelize development efforts reducing the overall time to market
- Partner with Product Managers, Solution Architects and your Engineering peers to define, analyze, estimate levels of effort to deliver at-scale solutions to meet customer requirements.
- Guide and advocate with technical expertise in the areas of architecture, design, implementation, and testing
- Write well designed, testable, efficient code
- Ensure designs are in compliance with specifications
- Prepare and produce releases of software components

**2. Job Requirement**

- Proficient in building Micro Services with Java 1.8 or higher, J2EE, spring, Spring Boot
- Exposure to Apigee, Ping Federate, OAuth and OpenID Connect
- Experience in using containerization technologies and cloud, Azure and Pivotal Cloud Foundry preferred
- Prior experience working with Continuous Integration and Deployment in a DevOps oriented product development environment and familiarity with modern MML technologies like Splunk, New Relic and Pager Duty
- Working experience on asynchronous messaging patterns like IBM MQ, Rabbit MQ, Kafka
- Proficient with No SQL and Relational Databases
- Working knowledge of Agile development methodology like Scrum, XP and Kanban

**3. Benefits**

- Salary range: 32,000,000 - 65,000,0000 VND per month
- Package 12 salary months + 2 salary KPI months, 13 leave days
- “CMC care” health insurance
- Annual Summer Vacation: follows company’s policy
- Salary review 2 times/year or on excellent performance
- International, dynamic, friendly working environment
- Annual leave, working conditions follow Vietnam labor laws.
- Other allowances: working on-site allowance, etc.
- Total allowances: 16.000.000 VND ~ 17.000.000 VND per year

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
