### ISSUE TITLE
Got It Vietnam - Backend Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by dokhanhhuyendieu** [awesome-jobs/vietnam#2603]
## Location

* Hanoi, Vietnam

## Salary Expectation

* At least 800 USD

## Requirements
* 1+ years of experience in software engineering
* Experience working on Python or NodeJS
* Experience working on MySQL, Nginx
* Knowledge of caching, message queue
* Knowledge of client-server communication protocols (REST, HTTP, JSON)
* Object-oriented development
* Be able to write clean, performance-centric, reusable, and understandable code with unit tests
* Experience designing and developing RESTful web services for mobile apps
* Ability to work in a fast-paced and dynamic team
* Self-starter, capable of leading and owning a large aspect of the product
* BS or higher in Computer Science, Mathematics or technical related fields 

### Extra Bonus
* Experience in designing and developing scalable backend components
* Experience working on a large scale and high traffic systems
* Experience building asynchronous Single Page Applications
* Experience working with Ads networks or social networking platforms
* Knowledge of React, AngularJS
* For C++ developer: experience working on event-based, multithread, GCC in Linux environment
* Desire to learn and extend the roles within the engineering team whatever it is, like analytics, automated test, business development, product management, DevOps,...
* Intellectually curious

### Why You'll Love Working Here

* **Amazing team:** Work with the smartest and most hard-working people you’ve ever met. Our team is from Google, Facebook, Lyft, Apple, Oracle, GREE,  and other best companies in Vietnam
* **Competitive compensation package:** Great salary, bonuses, and stock options. There is no upper limit on how much you can earn. It’s all based on your performance and contributions
* **Best working environment:** Coffee shop like open office space, kitchen full of snacks and drinks, West lake view bar, video games, 3D TV, soccer table, etc.
* **Latest gadgets for work:** MacBook Pro Retina 15”, external HD displays, latest smartphones and tablets
* **Training and personal development:** Tuition and textbook reimbursement for approved work-related courses. Free video training programs from Lynda.com, Udacity, Udemy, and The Great Courses Plus. Free English classes of your choice taught by native-speaking teachers. Company library with the newest technology and business books.
* **Flexible working hours**
* **Gyms, fitness, and sports:** Full-service gym memberships, soccer or extra dollars in your pocket to spend on your own fitness, swimming, dancing
* **Free daily lunches and dinners** 
* **Others:** Office happy hours, weekly lunch out, monthly team outings, participating in self-organized clubs like sports, games, algorithms, piano, etc. 

### Contact
**Homepage:** https://vn.got-it.ai/
**Email:** hdo@gotitapp.co
**LinkedIn:** https://www.linkedin.com/in/huyendk13/
**Skype:** sundial.dreams

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
