### ISSUE TITLE
Arrow High Tech - PHP Developer - Hà Nội - Fulltime 

### ISSUE THREAD

**Issue by ThuNgocHR** [awesome-jobs/vietnam#2605]
## Location

*Hanoi, Vietnam

## Salary Expectation

* upto 25M gross/month

## Requirements

* Có từ 1 năm kinh nghiệm làm các dự án PHP. Làm việc được với một trong các Framework PHP như: Magento, Wordpress, Shopify, Laravel, Yii...
* Ưu tiên làm việc được với Magento hoặc sẵn sàng làm việc với công nghệ mới.
* Thành thạo lập trình PHP: HTML, CSS, JQuery, JavaScript, Bootstrap…
* Hiểu về lập trình hướng đối tượng OOP là một lợi thế
* Có đam mê về Lập trình
* Có khả năng giao tiếp, đọc, hiểu tài liệu chuyên ngành bằng tiếng Anh.
* Biết tiếng Nhật và có kinh nghiệm làm dự án với khách hàng Nhật là lợi thế.

### Responsibilities

* Tham gia thiết kế, lập trình và triển khai các dự án xây dựng Website, web based application sử dụng Magento, Wordpress và các Framework khác như: Laravel, Shopify, Codeigniter, Yii …
* Làm việc theo sự phân công của trưởng nhóm/Quản lý dự án.

### Why it would be awesome to work with us

* Mức lương theo năng lực, review 3-6 tháng/lần
* 13 tháng lương, Thưởng hiệu quả theo hiệu suất làm việc.
* Được hưởng trợ cấp chuyên môn/ ngoại ngữ.
* Được tư vấn, định hướng về career-path rõ ràng.
* Có cơ hội được cử đi đào tạo, làm việc tại Nhật.
* Tham gia các chương trình đào tạo nội bộ nâng cao năng lực tại công ty
* Làm việc trong môi trường năng động, chuyên nghiệp. Học hỏi và phát triển cùng đồng nghiệp tài năng và nhiệt huyết
* Làm việc 8:15 - 17:30, Từ Thứ 2 - Thứ 6

**Cùng với chế độ:**

* Xét tăng lương 3 tháng/lần
* Du lịch nghỉ mát, Teambuilding 2-3 lần/ năm
* Tham gia Bảo hiểm xã hội theo đúng quy định của Pháp luật
* Khám sức khỏe định kỳ hàng năm
* 12 ngày nghỉ phép nguyên lương/năm
* Có cơ hội thi các chứng chỉ quốc tế
* Thưởng Lễ, Tết, Sinh nhật, Nhân viên xuất sắc năm.

### Contact
Homepage: https://talent.arrowhitech.com/
Zalo: 0989824746
Email: ngocbtt@arrowhitech.com
Skype: live:7fb766222f62bcc0
Linkedin: https://www.linkedin.com/in/thu-ngoc-754a79179/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
