### ISSUE TITLE
Arrow High Tech -Wordpress Developer - Hà Nội - Fulltime

### ISSUE THREAD

**Issue by ThuNgocHR** [awesome-jobs/vietnam#2607]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Upto 25M gross/month

## Requirements

* Có từ 1 năm kinh nghiệm về Wordpress (Back-end)
* Có kiến thức tốt về việc phát triển website hoặc phần mềm trên nền tảng Wordpress và các plugin phổ biến như WooCommerce, Polylang, WPML, MemberPress, GravityForm ...
* Có kinh nghiệm cài đặt, triển khai, vận hành website WordPress
* Nắm vững kiến thức về HTML, CSS, Javascript, JQuery, Bootstrap
* Có kinh nghiệm làm việc với MySQL, tối ưu SQL, Redis
* Đọc, hiểu tài liệu tiếng Anh. Nếu có thể giao tiếp bằng tiếng Anh là lợi thế
* Trách nhiệm, chủ động trong công việc

### Responsibilities

* Tham gia thiết kế, xây dựng, cài đặt các trang web, phần mềm cho khách hàng nước ngoài trên nền tảng WordPress
* Thực hiện các nhiệm vụ bảo trì, fix lỗi các trang web, phần mềm
* Tối ưu performance, SEO cho các trang web
* Thực hiện công việc khác theo sự phân công của PM

### Why it would be awesome to work with us

* Lương thưởng cạnh tranh, review lương 3 tháng/lần
* Lương tháng thứ 13, lương KPI và thưởng hiệu suất công việc
* Thưởng và quà tặng nhân viên các dịp lễ, Tết, sinh nhật, và các ngày lễ khác
* Được tư vấn và có lộ trình thăng tiến, phát triển bản thân rõ rang
* Tham gia các khóa đào tạo nội bộ về kỹ thuật, kỹ năng mềm, ngôn ngữ (Tiếng Anh, Tiếng Nhật)
* Tham gia team building, nghỉ mát 2-3 lần/năm
* 12 ngày phép/năm
* Khám sức khỏe định kỳ hang năm
* Đóng bảo hiểm theo quy định nhà nước
* Môi trường làm việc thoải mái, thân thiện, được hỗ trợ tối đa trong công việc
* Cơ hội được công ty tài trợ học và thi các chứng chỉ bằng cấp liên quan
* Thời gian làm việc: Từ 8.15 AM – 5.30 PM (thứ 2 – thứ 6), nghỉ trưa 1h15’

### Contact
Homepage: https://talent.arrowhitech.com/
Zalo: 0989824746
Email: ngocbtt@arrowhitech.com
Skype: live:7fb766222f62bcc0
Linkedin: https://www.linkedin.com/in/thu-ngoc-754a79179/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
