### ISSUE TITLE
[Edsolabs, Blockchain Project] Java Developer min $1500

### ISSUE THREAD

**Issue by Stella-Nguyen** [awesome-jobs/vietnam#2608]
## Location

* Duy Tan, Dich Vong Hau, Cau Giay, Hanoi
* Fulltime

## Salary Expectation

* max $1500 for members, min $1500 for Leaders

## Requirements
* Java
* Springboot
* Microservice
* 3+ years Software Engineering experience

### Must Have

* 3+ years experience in software development using Java
* Proficient in Java, and Springboot
* Experience with microservice
* A focus on detail including around automated tests and documenting your code
* Experience debugging and optimising web applications for speed and scale
* An agile mindset and the ability to adapt to changing priorities and requirements
* Pride in your work and a desire to contribute to a small team of dedicated and talented people
* An understanding of what we're doing (and why) and a passion to get involved
* Fast learner excited to develop new skills
* Product-oriented mindset.

### Ideally

* Understanding of blockchain technology, especially Ethereum, Bitcoin, EOS
* Knowledge of Blockchain fundamentals, smart contracts, consensus algorithms

### Responsibilities

Great power comes with great responsibilities!

* Be a part of an amazing product team
* Build Blockchain platform using Java language

### Why it would be awesome to work with us

* Interesting and challenging engineering projects
* Attractive salary and package. 
* Working time: 8:30-18:00 (off 1.5h from 12h to 13h30 for lunch) from Monday to Friday
* Flat and hierarchy structure
* Self-management is appreciated
* Friendly, innovative, and supportive environment
* Interesting projects
* 13th month salary, annual heath-check, insurance under Vietnamese Labor Law, monthly teambuilding
* Psychological safety; Your ideas are always welcomed.

_If you are always willing to learn, if you like challenges, if you want to get an attractive package and be a part of exciting projects, don’t hesitate to send your CV to: huent2@edsolabs.com.
Thank you!_

### Contact
Ms. Hue: huent2@edsolabs.com| huenguyen043 (skype)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
