### ISSUE TITLE
Arrow High Tech -Salesforce Developer - Hà Nội - Fulltime

### ISSUE THREAD

**Issue by ThuNgocHR** [awesome-jobs/vietnam#2609]
## Location

* Hanoi, Vietnam

## Salary Expectation

* upto $2000 gross/month 

## Requirements

* Tốt nghiệp đại học các ngành Khoa học máy tính, Công nghệ thông tin, Hệ thống thông tin hoặc có liên quan
* Từ 1 năm kinh nghiệm Salesforce Commerce trở lên
* Kinh nghiệm với Storefront Reference Architecture, Page designer, Commerce API, ISML, Apex code, Lightning component, Web Lightning component 
* Khả năng tiếp thu vấn đề nhanh, chủ động trong công việc
* Tiếng Anh đọc, hiểu tốt tài liệu kỹ thuật, có thể trao đổi với khách hàng là lợi thế

### Responsibilities

* Tham gia các dự án thực tế về Salesforce (Sales Cloud, Service Cloud, Commerce Cloud, Platform)
* Code: Storefront Reference Architecture, Commerce API, Lightning component, Visualforce page, Apex code, JS
* Admin: Page designer, thiết lập các cấu hình Profile, Role, Permission, Object, ….
* Low-code: Phát triển các tính năng dựa trên nền tảng low-code của Salesforce Processbuilder, Flow, 
* Làm việc theo sự phân công của trưởng nhóm/Quản lý dự án, phối hợp giữa các nhóm để phát triển sản phẩm

### Why it would be awesome to work with us

* Mức lương theo năng lực, review lương 3 tháng/lần 
* 13 tháng lương, Thưởng hiệu quả theo hiệu suất làm việc
* Được tư vấn, định hướng về career-path rõ ràng
* Tham gia các chương trình đào tạo nội bộ nâng cao năng lực tại công ty
* Làm việc trong môi trường năng động, chuyên nghiệp. Học hỏi và phát triển cùng đồng nghiệp tài năng và nhiệt huyết
* Làm việc 8:15 - 17:30, Từ Thứ 2 - Thứ 6

**Cùng với chế độ:**

* Du lịch nghỉ mát, Teambuilding 2-3 lần/ năm
* Tham gia Bảo hiểm xã hội theo đúng quy định của Pháp luật
* Khám sức khỏe định kỳ hàng năm
* 12 ngày nghỉ phép nguyên lương/năm
* Có cơ hội thi các chứng chỉ quốc tế
* Thưởng Lễ, Tết, Sinh nhật, Nhân viên xuất sắc năm.

### Contact

Homepage: https://talent.arrowhitech.com/
Zalo: 0989824746
Email: ngocbtt@arrowhitech.com
Skype: live:7fb766222f62bcc0
Linkedin: https://www.linkedin.com/in/thu-ngoc-754a79179/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
