### ISSUE TITLE
Boost Commerce - NodeJS Developer - Remote/Ho Chi Minh/Ha Noi/Other - FT

### ISSUE THREAD

**Issue by jennynguyen95** [awesome-jobs/vietnam#2611]
## Location

- Ho Chi Minh, Hanoi, Other, Vietnam
- Remote

## Salary Expectation

- Upto $1500/month

## Requirements

- At least 2 years experience of web application development
- Proficiency in a backend languages (preferably Typescript + NodeJS) and database technologies: Elasticsearch, Mongodb, MySQL, Redis
- Extensive experience with version control systems (Git)
- Experience with Docker and containerization technologies

## Skills

- Able to work remotely with team global members
- Always seeking for continuous improvement
- Critical thinking, creativity, and problem-solving
- Good communication skills with the ability to present technical information in a clear between team members
- Basic English

### Responsibilities

- Works closely with a team of software engineers to design, develop and support REST APIs and other software products
- Contributes to technical architecture to enable scalable and extensible solutions
- Ensures up-to-date documentation for systems, applications, and procedures
- Collaborates on best practices for all phases of development, testing, and deployment
- Writes clean, well-documented code for company's product by applying Design Patterns and industry best practices

### Work hour 

- Working time: 8:00 AM - 5:00 PM from Monday to Friday

### Benefit

- Salary review 2 times per year
- 13th-month salary and performance bonus
- Day-off: 14 days/year and Vietnam holidays
- Macbook provided after probation period
- Bao Viet Health Care Insurance (after 3-month in the role)
- Monthly company party and quarterly company trip
- Free online learning and Reimbursement for selected courses.
- Free access to the co-working space
- Annual health checks
- Allowance for gyms, fitness, yoga plus cash bonuses for lots of occasions around the year
- Great chance to improve your skills and English communication via international exposure
- Get support and work with talented and friendly members
- 100% remote culture. Live and work from wherever you feel happiest

### Contact
Email: jenny@boostcommerce.net
Skype: hoaiphuong8795

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
