### ISSUE TITLE
CANIFA - Python (Odoo) developer - Hà Nội - Full-time

### ISSUE THREAD

**Issue by canifacareers** [awesome-jobs/vietnam#2612]
**[CANIFA Hà Nội] 2 Odoo (Python) developer**

– Địa điểm: 170 La Thành, Đống Đa

– Lương: Cạnh tranh (thử việc hưởng 100% lương) + thưởng hiệu quả công việc/tháng + rất nhiều loại thưởng trong năm

– Tối đa 18 ngày nghỉ hưởng nguyên lương/ năm

– Văn phòng thân thiện, free trà bánh, biscuits ^^

– Số lượng: 2 người

**_<Mô tả công việc>_**

Phát triển backend cho dự án E-commerce có sử dụng Odoo frameworks (kết nối đến các hệ thống trên nền tảng Odoo). Dự kiến sẽ mở rộng thêm các dự án nội bộ của tập đoàn (phát triển các hệ thống quản trị tích hợp)

1. Phát triển các tính năng mới trên hệ thống phần mềm nền tảng Odoo

– Tham gia thiết kế và phát triển các ứng dụng theo nền tảng odoo.
– Phát triển các tính năng mới đáp ứng yêu cầu người dùng
– Phối hợp với nhân sự trong nhóm để phân tích, thiết kế phần mềm ..

2. Phối hợp hỗ trợ vận hành và khắc phục sự cố hệ thống

– Phối hợp cùng các thành viên trong bộ phận hỗ trợ vận hành hệ thống phần mềm cho người dùng cuối.
– Khắc phục các sự cố phát sinh trong quá trình vận hành
– Nghiên cứu và đề xuất giải pháp nhằm tối ưu tính năng trên các hệ thống được giao.

**_<Yêu cầu công việc>_**

– Tốt nghiệp Cao đẳng hoặc tương đương trở lên Chuyên ngành CNTT; Ưu tiên đọc hiểu tài liệu tiếng anh.

– Tối thiểu 1-3 năm kinh nghiệm ở vị trí tương đương.

– Thành thạo ngôn ngữ lập trình: Python trên nền tảng Odoo.
– Thành thạo cơ sở dữ liệu : SQL server, Postgres.
– Sử dụng hệ điều hành Linux centos, Ubuntu.
– Biết sử dụng công cụ quản lý mã nguồn : Gitlab, Github

**_<Quyền lợi chung>_**

Thử việc: 02 tháng, hưởng 100% lương và toàn bộ phụ cấp
Thời gian làm việc: 44h/tuần (nghỉ linh hoạt 2 sáng thứ 7/tháng)
Ngày nghỉ:- 12 ngày Nghỉ phép theo Luật định + tối đa 06 ngày nghỉ phép cân bằng cuộc sống (có hưởng 100% lương)/năm
Phúc lợi:- Thu nhập dựa trên nguyên tắc “cạnh tranh, công bằng, hợp lý” và dựa trên kết quả công việc của cá nhân, Thử việc hưởng nguyên lương
– Thưởng: Thưởng hiệu quả công việc (OKR), thưởng kết quả kinh doanh, thưởng ý kiến sáng kiến, thưởng thành tích vượt trội, thưởng thâm niên…,
Phụ cấp khác :- Phụ cấp ăn trưa;
– Các chế độ khác: Quà tặng dịp Lễ Tết lên đến 4tr/năm, Nghỉ cân bằng công việc & cuộc sống (6 ngày/năm), khám sức khỏe định kỳ, ưu đãi mua hàng,…
– Tham gia các chương trình Teambuilding Phát triển đội ngũ, happy hour, Hội CANIFA Vì cộng đồng, CLB Bóng đá, Hội khuyến học …

<Liên hệ>
E: lanpt@canifa.com / T: 037 502 8998

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
