### ISSUE TITLE
[Hà Nội - Fulltime] Flutter Developer - Upto 1800$

### ISSUE THREAD

**Issue by SunshineCareers** [awesome-jobs/vietnam#2614]
## Location

* 16 Phạm Hùng, Nam Từ Liêm, Hà Nội, Việt Nam

## Salary Expectation

* Upto 1800$/month

## Requirements

- Có ít nhất 01 năm kinh nghiệm với Flutter/ Android/ iOS

- Thành thạo một trong các ngôn ngữ Java (kotlin) hoặc Swift

- Có khả năng deploy ứng dụng lên AppStore/ PlayStore, biết dùng Fastlane, CodeSign là lợi thế

- Kinh nghiệm tích hợp các Restful API, Firebase và các SDK, thư viện trong quá trình phát triển ứng dụng

- Có kỹ năng viết Unit test, Function test, Integration test (DDD)...

- Có kiến thức về database, Design Pattern, OOP

- Hiểu biết về đánh giá và tối ưu hóa hiệu suất ứng dụng

- Sử dụng thuần thục các công cụ kiểm soát lõi, profiling

- Biết về blockchain là một lợi thế

- Biết về Flutter, React là một lợi thế

- Làm việc nhóm hiệu quả với công cụ Git, Giftlow

### Responsibilities

- Xây dựng ứng dụng moile liên quan đến ngân hàng (Internet banking, mobile banking, cổng thanh toán ứng dụng...)

- Chuyển đổi các thiết kế (Sketch, Ps, Figma..) sang mã nguồn

- Tối ưu hóa hiệu năng ứng dụng

- Phối hợp công việc theo nhóm dưới sự phân công của Quản lý dự án

- Tham gia nghiên cứu các giải pháp tối ưu, bảo mật hệ thống; đóng góp ý tưởng về công nghệ và sản phẩm

- Phát triển dự án mới và công nghệ mới của Tập đoàn trong lĩnh vực: Ngân hàng, Chứng khoán, Đầu tư tài chính, Bất động sản, Quản lý nội bộ...

### Why it would be awesome to work with us

- Mức lương lên đến 35 triệu/ tháng + phụ cấp ăn trưa, gửi xe 

- Văn phòng làm việc hạng A, cung cấp trang thiết bị đầy đủ 

- Được hưởng các chính sách của Tập đoàn lớn như ưu đãi các dịch vụ do tập đoàn cung cấp: hỗ trợ mua nhà, mua sắm S’Mart, S’Cafe, học tập S’School, nghỉ dưỡng, chăm sóc sức khỏe, đi lại

- Môi trường làm việc chuyên nghiệp, năng động, là Tập đoàn đi đầu trong việc ứng dụng công nghệ 4.0 

- Được tiếp cận với các công nghệ tiên tiến nhất và làm việc cho các dự án quy mô lớn

- Lương thỏa đáng theo năng lực, xét tăng lương sau 3 – 6 tháng

- Du lịch nghỉ mát hàng năm

- Các chế độ khác theo quy định của Luật lao động

### Contact
Homepage: https://sunshinegroup.vn/
Email: linhtt1@sunshinegroup.vn
Phone/Zalo/Viber: 0339155035
Linkedin: https://www.linkedin.com/in/linh-tạ-716544214/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
