### ISSUE TITLE
[HN/HCM- Fulltime] Backend Developer (Java/ .Net) - Upto 1800$

### ISSUE THREAD

**Issue by SunshineCareers** [awesome-jobs/vietnam#2615]
## Location

* Hà Nội: 16 Phạm Hùng, Nam Từ Liêm, Hà Nội, Việt Nam
* Hồ Chí Minh: Block 5, Lô I-3B-1, Đường N6, Khu công nghệ cao, Phường Tân Phú, Thành phố Thủ Đức, Việt Nam

## Salary Expectation

* Upto 1800$

## Requirements
- Có ít nhất 02 năm kinh nghiệm

- Thành thạo một trong những ngôn ngữ lập trình Java, Python, Golang, .NET (có kinh nghiệm nhiều hơn 01 ngôn ngữ hoặc 01 framework phổ biến là lợi thế)

- Có kinh nghiệm chuyên sâu khi viết Unit Test, Function Test và Integration Test

- Có kiến thức tốt về cả RDBM và NoSQL

- Có kiến thức tốt về cấu trúc dữ liệu và giải thuật là một lợi thế

- Biết sử dụng Restful API, web service

- Có kinh nghiệm về Docker/ Kubernetes và Cloud Infrastructure là một lợi thế

- Sử dụng được ReactJs, Vuejs, AngularJs là một lợi thế
 

### Responsibilities

– Phát triển các ứng dụng liên quan đến các hệ thống ngân hàng trực tuyến: Internet Banking, Mobile Banking, cổng thanh toán (payment gateway), phát triển các tiện ích thanh toán thẻ và các hệ thống ứng dụng khác hỗ trợ giao dịch trực tuyến.

– Phát triển các ứng dụng quản trị nội bộ: Quản lý và phê duyệt khoản vay, số hóa thủ tục giấy tờ, quản lý bán hàng và các ứng dụng hỗ trợ thúc đẩy công tác quản lý và kinh doanh của ngân hàng

– Phát triển ứng dụng trên hệ thống ngân hàng (Core banking) hoặc ứng dụng tích hợp với hệ thống ngân hàng

– Tối ưu hóa hiệu năng ứng dụng

– Phối hợp công việc theo nhóm dưới sự phân công của Quản lý dự án

– Tham gia nghiên cứu các giải pháp tối ưu, bảo mật hệ thống; đóng góp ý tưởng về công nghệ và sản phẩm

– Phát triển các dự án mới của Tập đoàn trong lĩnh vực Ngân hàng, Chứng khoán, Đầu tư tài chính, Bất động sản.. 

– Sử dụng các công nghệ mới: kiến trúc Microservice; DBMS Oracle, MySQL; Docker, Kafka...

### Why it would be awesome to work with us
- Mức thu nhập hấp dẫn, mức lương hưởng theo năng lực

- Được làm việc trong các hệ thống ứng dụng lớn của công ty, cơ hội tham gia vào siêu dự án của Tập đoàn, tiên phong ứng dụng công nghệ 4.0 vào thị trường BĐS, Tài chính, Ngân hàng, Chứng khoán

- Môi trường làm việc trẻ trung, thân thiện, chuyên nghiệp, năng động, tiếp xúc với nhiều công nghệ tiên tiến

- Tham gia các ác hoạt động của công ty như: team building, annual trips, barbecues, ...

- Được hưởng đầy đủ các quyền lợi theo luật lao động, nghỉ phép, được tham gia đóng BHXH, BHYT

- Được hưởng ưu đãi khi mua nhà của tập đoàn Sunshine

- Được hỗ trợ ăn trưa, gửi xe

- Được hưởng các chính sách, ưu đãi về dịch vụ của Tập đoàn đối với nhân viên như mua nhà, mua sắm S’Mart, S’Cafe, học tập S’School, nghỉ dưỡng, chăm sóc sức khỏe, đi lại....

### Contact
Homepage: https://sunshinegroup.vn/
Email: hoann@sunshinegroup.vn
Phone/Zalo/Viber: 0327509955
Linkedin: https://www.linkedin.com/in/hoa-nguyen-88bb4818b/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
