### ISSUE TITLE
Full time Senior/Leader - Full-Stack Dev (Java ; JS )

### ISSUE THREAD

**Issue by ThuyHRBluebelt** [awesome-jobs/vietnam#2616]
## Location

241 Xuan Thuy, Cau Giay, Ha Noi

## Salary Expectation

35,000,000 VND-55,000,000 VND per month

## Requirements
- Create user information solutions by coding, developing, implementing, and maintaining Java based components and interfaces; 
- Participate in designing and developing systems/platforms; 
- Code, test and review code of other members; 
- Develop user interfaces to internet/intranet applications by setting expectations and features priorities throughout development life cycle; determining design methodologies and tool sets; completing programming using languages and software products; designing and conducting tests;

## Skills
Job Requirement: 
- At least 3 years of experience in programming with Java, Spring, Hibernate, Struts…; 
- Good knowledge of OOP and design patterns; 
- Familiar with Struts/Spring MVC framework; 
- Experience with web development using HTML/CSS/Javascript; 
- Experience in SQL, have knowledge in MySQL is an advantage; 
- Experience in Tomcat, Apache Web Server, ActiveMQ shall be an advantage; 
- Experience in using Frontend library (React JS, Ember JS...) 
- Should be strong in communication skills; - Experience in implementing large systems 
- Experience in using docker, kubernetes, CI, CD 
- Experience in survey and analysis requiement       

- Good logical thinking, knowledge of system architecture 
- Strong coding with good performance, Experience in extending system 
- Be able to communicate in English is an advantage

Personality Requirements: 
- Hard working, responsible, strong interpersonal and communication skills; 
- Ability of working independent and teamwork, can work under high pressure; 
- Ready to work overtime; 

### Benefit
- Working time: 9:00 ~ 17:00 (Monday to Friday);
- Salary: 100% offered salary from probation time; 
- Competitive with lucrative add-ons (based on skills and experience); 
- Performance Review: 2 times/year based on performance and contribution;
- Annual health checking/Aon Insurance

### Contact
Homepage: https://hd.bluebelt.asia/
Email: recruit@bluebelt.asia (024 6287 0333)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
