### ISSUE TITLE
[Hà Nội - Fulltime] Project Manager - Upto 1300$

### ISSUE THREAD

**Issue by SunshineCareers** [awesome-jobs/vietnam#2617]
## Location

* 16 Phạm Hùng, Nam Từ Liêm, Hà Nội, Việt Nam

## Salary Expectation

* Upto 1300$/month

## Requirements
–  Tốt nghiệp Cao đẳng trở lên chuyên ngành Công nghệ thông tin hoặc các ngành khác liên quan

–  Có it nhất 02 năm kinh nghiệm quản lý dự án với quy mô nhóm 10+ thành viên

–  Có kinh nghiệm lập kế hoạch dự án, thực hiện, kiểm soát và quản lý rủi ro dự án

–  Kiến thức vững chắc về quản lý kỹ thuật, phân tích thông tin và hệ thống phần mềm máy tính

–  Giải quyết vấn đề và kỹ năng lãnh đạo để hướng dẫn nhóm dự án thông qua các giai đoạn của dự án đa quy mô

–  Năng động, chủ động, tận tâm, có khả năng tự tổ chức và làm việc chăm chỉ

### Responsibilities
–  Quản lý nhiều dự án phát triển phần mềm bao gồm kế hoạch, ngân sách dự án, quản lý tài nguyên, quản lý rủi ro, quản lý chất lượng

–  Xác định lịch trình dự án, phân bổ nguồn lực và theo dõi tiến độ

–  Quản lý mối quan hệ hàng ngày với các phòng ban liên quan về vấn đề dự án: cung cấp các báo cáo trạng thái thường xuyên và chủ động đưa ra các giải pháp để đảm bảo nghiệp vụ

–  Xây dựng tinh thần nhóm dự án bằng cách huấn luyện, thúc đẩy, kết nối các thành viên trong nhóm để đóng góp cho thành công của công ty và dự án

–  Tích hợp công nghệ thông tin vào nhóm để đạt hiệu quả tối ưu

–  Luôn cập nhật với cấp trên với tình trạng dự án/ tài nguyên, các vấn đề hoặc sáng kiến

–  Giải quyết và xác định các vấn đề, chức năng để cung cấp các giải pháp công nghệ

–  Quản lý các dự án/ sản phẩm của Tập đoàn trong lĩnh vực: Ngân hàng, Chứng khoán, Đầu tư tài chính, Bất động sản, Quản lý nội bộ…

### Why it would be awesome to work with us
– Được hưởng mức thu nhập cạnh tranh

– Được đào tạo, bồi dưỡng về nghiệp vụ trong quá trình làm việc;

– Thưởng lễ, Tết theo quy định của Tập đoàn và kết quả SXKD của Tập đoàn.

– Được hưởng đầy đủ các quyền lợi theo luật lao động, nghỉ phép, được tham gia đóng BHXH, BHYT sau khi ký hợp đồng lao động chính thức.

– Được hưởng các chính sách, ưu đãi về dịch vụ của Tập đoàn đối với nhân viên như mua nhà Sunshine Home, mua sắm S’Mart, S’Cafe, học tập S’School, nghỉ dưỡng, chăm sóc sức khỏe…

### Contact
Homepage: https://sunshinegroup.vn/
Email: linhtt1@sunshinegroup.vn
Phone/Zalo/Viber: 0339155035
Linkedin: https://www.linkedin.com/in/linh-tạ-716544214/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
