### ISSUE TITLE
[Remote] Senior full stack developer (#Javascipt, #Reactjs, #Nodejs, #React_Native)

### ISSUE THREAD

**Issue by huyenvu301** [awesome-jobs/vietnam#2618]
**About the job**
We're looking for someone who has a passion for technology and continuous improvement, and enjoys a collaborative approach to software development. You'll help us scale to meet the demands of a million-plus global users and you'll help decide on the tools and approaches we use.
As a Senior Software Engineer well into your career, we know you're exceptional at what you do. You take pride in being someone that more junior members look up to, but you're still eager to learn and hone in on skills as a Senior Software Engineer... That's why we're placing a heavy emphasis on leaning on your expertise to take on a high level of responsibility while being a role model and mentor to others on the team.
**Responsibilities:**
 Drive complex projects autonomously, from technical design to launch.
 Tackle complex architecture challenges, apply architectural standards and start using them on new projects.
 Designing, implementing, testing and deploying various software products
 Contributing to the overall technical solution design
 Managing and maintaining existing systems in line with our product custodianship strategy
 Provide thought leadership and make contributions to continually improve the cross-platform development practices
 Participating in engineering practices that produce testable, maintainable products to be proud of
 Knowledge sharing & mentoring other developers within the team on-shore and off-shore
 Perform code reviews & documentation as well as take on complex bug fixes, especially on high-risk problems.
 Set the standard for thorough, meaningful code reviews.
 Work in collaboration with team members and adhere to timelines and milestones
**Requirements:**
 3-5 years' experience in Mobile/Web Development Experience.
 Have a passion for React Native, JavaScript & Node Js and are excited to advocate for the platform
 Excellent JavaScript/Typescript skills. Applies security and reliability principles when designing systems.
 Understand the principles of Redux/Mobx and make strong architectural recommendations
 Stay abreast of the latest React and JS libraries and can offer well formed opinions when selecting a tech stack
 Bring your knowledge of design patterns in development (eg SOLID) and platform architecture (Microservices, Event Driven, DDD)
 Experience with test automation at all levels of the test pyramid and beyond, and experience working in a Continuous Deployment model
 GraphQL & AWS Experience a bonus
 Considers the customer impact when making technical decisions.
 Really good communicator both with the stakeholders and the team.
 A real appetite for learning and growing, both as a developer and teammate.
 Great at scripting, knowledge of linux/unix systems commands, shell scripting / python.
 Strong foundation of HTML5, CSS and JavaScript DOM.
 Agile development, experience with scrum or kanban and on-shore offshore models.
**Nice to have:**
 Ideally have worked in fast-growing startups, so you understand the need and ability to be able to move fast.

**Contact:**
Ms. Huyền - 0981.096.290
Email: huyen.vuthu@manpower.com.vn

**Comment by ghost** [comment]
Wow you're looking for React Native candidate as well? How lucky when i am doing that .......
