### ISSUE TITLE
Data Scientist - FT - REMOTE

### ISSUE THREAD

**Issue by Gin19** [awesome-jobs/vietnam#2619]
## Location
* Remote

## Salary Expectation

* $1500 - $3500

## Requirements
● Master or Ph.D. in Computer Science, Statistics, Industrial Engineering, Mathematics, Economics or quantitative discipline
● At least 3 years of hands-on experience in a Data Science role with exposure and proficiency in quantitative and statistical analysis, predictive analytics, multivariate testing, and algorithm optimization for machine learning. Commercial experience are highly desirable.
● Strong knowledge in big data ETL processes, data, and data exploration algorithms
● Strong working knowledge of data science algorithms including decision trees, probability networks, association rules, clustering, regression, and neural networks
● Fluid in programming skills (MySQL, SQL, Python, R or similar)
● Fluid in a variety of visualization tools
● Broad-minded with attention to detail and strong business acumens and insights

### Responsibilities

Singapore's No 1 fastest-growing company in 2021 is looking for an experienced data scientist to start and lead our data science efforts. Do you love sifting through data troves to find gems to analyse? Read on! We’re looking for a data scientist to help us to dice and mince the big data into trends and analytics. This is a hands-on role, but you’ll have full autonomy in choosing the toolkit and approach you want to apply to achieve a data objective. You will have ownership over important project areas that include defining the roadmap of data science. You will work with our structured and unstructured data to find a pattern/trend of how our users are using the product and present these insight reports to the business stakeholders. You have a sharp mind and hands-on approach when it comes to tackling technical challenges.

What you will be doing:
● Exploring and visualizing large datasets to drive insights
● Fluid at extracting and transforming data from systems using tools
● Fluid at practical data mining techniques (pattern detection, predictive modeling, anomaly detection, and optimization) to identify areas of improvement for business/product
● Identify and highlight areas of opportunities to help business/product owners optimize existing or new business opportunities/processes
● Applying machine learning techniques for a variety of modeling and relevance problems
● Designing and implementing metrics that help teams focus on what to optimize for
● Assist with developing strategies and managing operational metric for various projects
● Manage, hiring and mentor your fellow team members

### Why it would be awesome to work with us

- Opportunities to gain hands-on experience in cutting-edge technologies.
- Fast-tracked career opportunities to lead teams as Carro scales
- Group Health Insurance
- Transportation Allowance
- MacBook Pro provided (once they passed probation)
- Staff Welfare Allowance (Recreational Allowance)
- Self-Learning Development Fund, AWS. Sponsor/subsidize course fee. Work-related courses
- Annual performance review
- 12 Days Annual Leave
- Pantry, Social Gathering
- Professional, dynamic and open working environment

### Report to
Singapore core team
### Process interview
1) Screening call with HR, 2) Interview with the Hiring Manager + Take-home assignment, 4) Technical Interview

### Contact
Skype: Huehuenoivu
Zalo/Tele: 0886005769

**Comment by qcam** [comment]
Please kindly provide more information of the post.
