### ISSUE TITLE
GIANTY - Jr. / Sr. Ruby On Rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by nguyenmai2911** [awesome-jobs/vietnam#262]
GIANTY is one member of Global Group one of the leading mobile contents and services providers with millions of users worldwide. Global Group has expanded its business network to international branches located worldwide, spreading from Japan to Chinese, USA and Vietnam.
 There are about 300 staffs working in Vietnam and we are looking for Ruby on Rail Developer for our expanding plan.
Our page : https://www.facebook.com/Giantycareer/?fref=ts
## Location

35 Ton Duc Thang, District 1, Saigon, Vietnam
## Salary

Negotiable
## Requirements
- Bachelor degree in IT or Math.
- At least 2+ years of experience in Ruby on Rails development.
- Strong experience with client side, web technologies (HTML/CSS/JS).
- Experience with DBMS, MySQL is a plus.
- Understand the basic Unix commands.
## Skills

Ruby on Rails
### Responsibilities
- Develop E-commerce web application for Japan market.
### You can bring
- Competitive salary; 
- Bonus assessment once a year; 
- Annual medical checkups; 
- Company teambuilding excursions; 
- Work-life balance: Happy Hours, Team Building, Company trip, various social and sport activities;
- Birthday gift and other tokens of appreciation; 
- Support lunch, team building expenses.
### Contact

Please send your CV to mai.ntt@gianty.com.vn or recruitment@gianty.com.vn

**Comment by nguyenmai2911** [comment]
## About Our Company
GIANTY is one member of Global Group (www.gnt.co.jp), one of the leading mobile contents and services providers with millions of users worldwide. Global Group has expanded its business network to international branches located worldwide, spreading from Japan to Chinese, USA and Vietnam.
There are about 300 staffs working in Vietnam and we are looking for Ruby on Rail Developer for our expanding plan.

**Comment by joneslee85** [comment]
It's been a week without response or amendment. i close this post for now.

**Comment by nguyenmai2911** [comment]
Dear Trung,

May be you had a misunderstood.
I had responsed to you by a "like" button and also revise the formart of the buttlet points before you closed my post.

**Comment by joneslee85** [comment]
@nguyenmai2911 Hi, I did not misunderstand you. I requested you revise the bullet points format on 21st July but after 2 days I haven't seen you addressed the request.

**Comment by nguyenmai2911** [comment]
Dear Trung,

I've just finished revised the bullet points format agains. If you still see the old one, just remove if you want.
