### ISSUE TITLE
[VNTravel Group] - [Backend Developer] - [HaNoi] - [Full time]

### ISSUE THREAD

**Issue by VanHRVNTravel** [awesome-jobs/vietnam#2620]
## Location

__PeakView Tower, 36 Hoang Cau, Ha Noi, Viet Nam__

## Salary Expectation

* Upto $2500/month

## Requirements
* Bachelor Degree in Information Technology, Computer Science, or equivalent.
* At least 2 year of relevant working experience with strong Computer Science fundamentals in algorithms and data structures.
* Knowledge in Restful API frameworks (Spring, Play, ...)
* Knowledge in Linux OS (Ubuntu, CentOS,...) is a Plus Point
* Programming Language: Java
* Knowledge in database programming or design skills, including relational database skills (SQL, etc.) and non-relational database skills (MongoDB, Redis, ElasticSearch, etc.)
* Knowledge in in-memory cache (redis, memcache, ...)
* Familiar with MessageQueue (RabbitMQ, ActiveMQ, ...)
* Huge plus: strong English communications skills

### Responsibilities
* Develop back-end features using Restful API, Microservice, AWS stacks technologies.
* Develop internal tools to support production users and to investigate technical issues.
* Design and implement features that support client side and improve the availability, scalability, latency, and efficiency using Java, Python 
* Write high-quality, well-tested, clean, simple, and maintainable code; build common libraries.
# FOR SENIOR LEVEL:
* Take lead on technical best practices and guide internal research.
* Coach other junior team members to help them reach their maximum potential.
* Build a good team culture of humility, commitment, humor and customer service.

### Why it would be awesome to work with us
* 13th-month salary
* Dynamic and challenging environment
* Receive preferred company stock
* Promotion
* Insurance PVI
* Team activities, company events
* Free coffee, tea, breakfast, snack,…Lunch allowance
* Play Station & Books

### Contact
Homepage: https://vntravelgroup.vn/
Email: van.nt@tripi.vn
Skype: vannguyen.1890

**Comment by VanHRVNTravel** [comment]
Please contact me if you have any questions about this position.
Skype: vannguyen.1890
Telegram: @vaannt

**Comment by VanHRVNTravel** [comment]
For more information, please click the link: 
https://vntravelgroup.vn/
https://www.facebook.com/vntravelgroup.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
