### ISSUE TITLE
[KiotViet] [Android Developer] [HoanKiem-HaNoi] [FT]

### ISSUE THREAD

**Issue by hangvuhr9** [awesome-jobs/vietnam#2624]
## Location

* Hanoi, Vietnam

## Requirements
*  Java, RxJava, SDK Android and Android Studio
*  Kotlin Framework
* PostgreSQL
* 3+ years Software Engineering experience

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analysis skill

### Contact
Homepage: vuthihanghr1910
Trollman: hang.vt@citigo.com.vn

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section?
