### ISSUE TITLE
[Hà Nội] Senior/Leader Magento Developer ~ $2000

### ISSUE THREAD

**Issue by TrangHRIT** [awesome-jobs/vietnam#2625]
## Location

* Duy Tân, Cầu Giấy, Hà Nội

## Salary Expectation

* $1200 - $2000/tháng

## Requirements
- Có 4 năm trở lên làm liên tục với PHP và có 2 năm trở lên kinh nghiệm dự án với Magento 2 hoặc Magento 1.
- Có kinh nghiệm deploy hệ thống sử dụng AWS Cloud, Linux server.
- Có hiểu biết, kinh nghiệm về tích hợp với hệ thống ngoài như thanh toán, vận chuyển, quản lý kho, quản lý sản phẩm đặc biệt là hệ thống thuộc thị trường Đông Nam Á, Nhật …
- Có hiểu biết kiến thức về việc vận hành hệ thống thương mại điện tử.
- Có kinh nghiệm tổ chức, quản lý công việc của bản thân và team qua các tool Git, Redmine, Backlog.
- Có khả năng làm báo cáo năng suất chất lượng, dự đoán và quản lý rủi ro.
- Có kinh nghiệm làm với team từ 5 thành viên trở lên ở vị trí Technical leader hoặc Team Leader trong các dự án outsource dùng tiếng Anh hoặc Nhật là lợi thế.

### Responsibilities

- Giao tiếp, tư vấn giải pháp cho KH, quản lý team phát triển trong dự án lớn phát triển hệ thống thương mại điện tử sử dụng Magento/PHP cho khách hàng Nhật và khối Đông Nam Á.
- Tham gia các công đoạn tìm hiểu yêu cầu, phân tích, thiết kế, nghiên cứu công nghệ khi được phân công.
- Tham gia estimate dự án khi có yêu cầu.

### Why it would be awesome to work with us
- Mức lương khởi điểm hấp dẫn, cạnh tranh, tương xứng với khả năng và kinh nghiệm làm việc.
- Thưởng mềm ít nhất 2 lần/năm
- Xét tăng lương 2 lần/năm theo năng lực và hiệu quả công việc
- Được hưởng BHXH, BHYT, BHTN theo chế độ nhà nước ban hành
- Bảo hiểm Sức khỏe dành cho CBNV, khám sức khỏe hàng năm
- Ngày phép: ~14 ngày/năm
- Trợ cấp tiếng Nhật, chứng chỉ IT, teambuilding, du lịch nghỉ mát hàng năm
**Đặc biệt:**
- Tham gia học tiếng Nhật từ sơ cấp đến N2 hoàn toàn miễn phí trong giờ hành chính
- Cơ hội làm việc và đào tạo tại Nhật Bản với các ứng viên có tiếng nhật
- Làm việc trong môi trường chuyên nghiệp, được hỗ trợ phát huy khả năng, phát triển công việc tối đa

### Contact
Email: trang.hr@co-well.vn
Phone/Zalo: 0988 998 740 | Skype: trang_hr
Linkedin: https://www.linkedin.com/in/nguyentranghrm/

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
