### ISSUE TITLE
ITE - Back-End Developer - HaNoi - FT

### ISSUE THREAD

**Issue by HrITE** [awesome-jobs/vietnam#2627]
## Location

* HaNoi, Vietnam
* Fulltime

## Salary Expectation

* $????/month or range

## Requirements
* Java
* Spring, Hibernate Framework
* Having experience: System, Monitoring, Logging
* SQL Server / MySQL / MongoDB / ElasticSearch
* Having knowledge of banking, finance, and telecommunications
## Skills
* Teamwork
* Able to use English at work

## Benefit
* Attractive financial benefit and sales incentive
* Dynamic, creative, fun, and friendly working environment
* Annual staff trips and charity activities organized by the company
* Be well-trained in soft skills and in-depth professional skills

## Contact
 Email: hr@itegroup.vn
 Contact: 02463289520 (Ms.Ngọc)

**Comment by HrITE** [comment]
Detailed Job Description (Vietnam version): https://careerbuilder.vn/vi/tim-viec-lam/back-end-developer-chuyen-vien-phat-trien-ung-dung-he-thong.35B65F38.html

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
