### ISSUE TITLE
[VNTravel Group] [IOS Developer] [HaNoi] [Full-time]

### ISSUE THREAD

**Issue by VanHRVNTravel** [awesome-jobs/vietnam#2629]
## Location

* PeakView Tower, 36 Hoang Cau, Dong Da, Ha Noi

## Salary Expectation

* Upto $2500/month 

## Requirements
* Minimum of 2 years developing native mobile applications in iOS (Senior: 2 years exp above, Junior: 1-2 years of exp).
* Good knowledge in Web services, REST APIs, Oauth 2.0 and applications with Client-Server interface
* Advanced level skills in programming OOP, MVC, MVP, Design Patterns, iOS SDK as well as Data Structure and Algorithms
* Willing to explore new technologies to solve sophisticated technical issues.
* Strong problem analyzing & solving skill
* Self-learning & updating new technologies
* Compatible to working independently & high-responsibly
* Familiar with coding Objective-C is a plus

### Responsibilities
* Deploying application for booking air ticket as well as hotel room & tour travel for Tripi – the 1st travel platform in Vietnam
* Deploying travel applications in coordination with Vietnam Tourism Association.
* Deploying SDK to connect with business partners to promote & sell Tripi’s travel services on their sales channels.
* Coordinating directly with designer to convert ideas into coding
* Working directly with Tester to assure the best quality of products.

### Why it would be awesome to work with us
* 13th-month salary
* Dynamic and challenging environment
* Receive preferred company stock
* Promotion
* Insurance PVI
* Team activities, company events
* Free coffee, tea, breakfast, snack,…Lunch allowance
* Play Station & Books

### Contact
Homepage: https://vntravelgroup.vn/
Email: van.nt@tripi.vn

**Comment by VanHRVNTravel** [comment]
Please contact me if you have any questions about this position.
Skype: vannguyen.1890
Telegram: @vaannt

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
