### ISSUE TITLE
[OpenCommerce Group] Full-stack Developers (PHP, Java, Golang) - Open for candidates at HN and HCMC

### ISSUE THREAD

**Issue by gracy886** [awesome-jobs/vietnam#2630]
## Location

* Hanoi: 130 Trung Phung Street, Dong Da District, Hanoi
* HCMC: 2/3A Nguyen Thi Minh Khai Street, Da Kao Ward, District 1, Ho Chi Minh City

## Salary Expectation

* Negotiable

## You’ll be responsible for

* Development of technology products; technology support tools for products.
* Analysis and development of services, systems, APIs for system integration.
* Participation in maintenance and upgrade of existing technology products and services to ensure stable performance of the product.

## Requirements
* Candidates from 1-2 years experience
* Golang on BKGo framework and other frameworks such as Symfony, Laravel to build product backend
* Javascript with framework VueJS, ReactJS to build front-end for web or mobile
* Willing to learn new programming languages, new technologies and improve problem-solving skills
* Experience in software engineering and microservice
* Familiar with database (SQL + NoSQL) is a plus
* Passion for product development with millions of users

## Why it would be awesome to work with us
* Competitive NET salary package
* 6-month salary review 
* Working with a team full of young and passionate talents
* Having chances to provide solutions for real e-commerce problems
* Dynamic, flexible, and equal working environment
* Flexible working hours, no dress code

## Contact
Homepage: opencommercegroup.com
Recruitment: CV sends to duyenvu@opencommercegroup.com
More information: Zalo 0978282250/ Skype: live:hanhduyenvuthi

**Comment by gracy886** [comment]
Detailed Job Description (Vietnam version): https://www.topcv.vn/viec-lam/fullstack-developer-php-java-golang-ho-chi-minh/450363.html?ta_source=JobSearchList

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
