### ISSUE TITLE
[HN] Java Developer- [$900-$1700]

### ISSUE THREAD

**Issue by Hatt2** [awesome-jobs/vietnam#2631]
## Giới thiệu 
Là doanh nghiệp dẫn đầu trong lĩnh vực Thương mại điện tử, Sapo mang đến những giải pháp cho khách hàng trong việc kinh doanh, nền tảng quản lý và bán hàng đa kênh. Với hơn 100.000 khách hàng trên toàn quốc tin tưởng sử dụng, Sapo đang là doanh nghiệp có nền tảng quản lý và bán hàng đa kênh từ Online đến Offline được sử dụng nhiều nhất tại Việt Nam.

Đội ngũ nhân viên Sapo hiện có hơn 1000 nhân sự có trình độ chuyên môn cao, luôn làm việc với tất cả sự nhiệt huyết và sức sáng tạo của tuổi trẻ đã xây dựng nên 1 văn hoá vô cùng trẻ trung và năng động. Đến với Sapo, bạn sẽ được trải nghiệm môi trường tuyệt vời, với chế độ đãi ngộ xứng đáng và đạt được thành công vượt mong đợi!

## Mô tả công việc

- Phân tích yêu cầu hệ thống, thiết kế giải pháp cho từng dịch vụ và tính năng cụ thể.
- Đánh giá cấu trúc hệ thống hiện tại và xây mới, đề xuất các giải pháp để cải thiện hệ thống, hướng dẫn team dev thực hiện các giải pháp đưa ra.
-Cung cấp các giải pháp về mặt kỹ thuật và kiến trúc cho các sự cố gặp phải trên môi trường thật.
- Xây dựng định hướng về việc thay đổi kiến trúc hệ thống đáp ứng những yêu cầu mới và nhu cầu mở rộng quy mô trong tương lai, đảm bảo đối ứng được các yêu cầu về mặt chức năng cũng như phi chức năng như tính bảo mật, hiệu năng, tính sẵn sàng
-Quản trị và giám sát các thành phần công nghệ trong hệ thống CNTT nhằm đảm bảo tính dùng lại và tối ưu các thành phần kiến trúc.

## Quyền lợi

- Lương/thưởng hấp dẫn theo quy định của công ty
- Được xét tăng lương 2 lần/năm
- Chế độ BHXH, BHYT theo luật Lao động, ngoài ra được tham gia chương trình bảo hiểm Sapo Care
- Được tham gia các khoá đào tạo từ các chuyên gia hàng đầu về thương mại điện tử, marketing online, phầm mềm ...
- Được làm việc trong môi trường chuyên nghiệp, trẻ trung, năng động.

##  Yêu cầu công việc
- Có từ 1.5 năm kinh nghiệm lập trình Java, có hiểu biết về các Framework: Spring, Hibernate

- Có kiến thức về System, Monitoring, Logging là 1 lợi thế

- Có kinh nghiệm với NoSQL (Redis, MongoDB), các hệ thống Message Queue (Kafka, RabbitMQ) là 1 lợi thế

- Có kinh nghiệm làm việc với hệ thống cơ sở dữ liệu SQL Server / MySQL / MongoDB / ElasticSearch là 1 lợi thế

- Có kinh nghiệm làm việc trên môi trường UNIX/Linux là 1 lợi thế.

## Liên hệ
Để tìm hiểu thêm chi tiết, vui lòng liên hệ:
- SĐT: 0387480634 (Ms Hà)
- Email: Hatt2@sapo.vn/ tuyendung@sapo.vn
- Website công ty: https://www.sapo.vn/
- Fanpage TD: https://www.facebook.com/tuyendungsapo/

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
