### ISSUE TITLE
Lập trình viên Python/Odoo [Hà Nội]

### ISSUE THREAD

**Issue by Hatt2** [awesome-jobs/vietnam#2633]
## Mô tả công việc
- Tìm hiểu, phân tích quy trình của Odoo (OpenERP) nói chung và quy trình đặc thù của một công ty software để áp dụng vào hệ thống.

- Lập trình & tích hợp các module Odoo

- Customize Module Odoo theo yêu cầu

- Triển khai những chức năng mới, chức năng bổ sung theo yêu cầu

## Quyền lợi

- Lương/thưởng cạnh tranh, offer upto không giới hạn
- Xét tăng lương 2 lần/năm
- Chế độ BHXH, BHYT theo luật Lao động, ngoài ra được tham gia chương trình bảo hiểm Sapo Care.
- Được tham gia các khoá đào tạo từ các chuyên gia hàng đầu về thương mại điện tử, marketing online, phần mềm ...
- Được làm việc trong môi trường chuyên nghiệp, trẻ trung, năng động.

## Yêu cầu công việc
- Từ 2 năm kinh nghiệm làm dự án phần mềm, có kinh nghiệm triển khai các dự án thực tế trên Odoo có ít nhất 100 người sử dụng
- Có khả năng phát triển/customize hoàn chỉnh cho 1 module theo yêu cầu nghiệp vụ. Hiểu rõ về front-end và back-end của Odoo
- Có kinh nghiệm làm việc về HTML, Javascript, Python, Odoo Framework
- 
## Ưu tiên
- Ứng viên có kinh nghiệm và hiểu tổng quan về quy trình nghiệp vụ doanh nghiệp ở 1 số mảng như CRM, HR, Sales, Accounting...
- Ứng viên đã từng triển khai, vận hành các hệ thống ERP

## Liên hệ
Để tìm hiểu thêm chi tiết, vui lòng liên hệ:
- SĐT:  (84.24) 7308 6880, Ext: 516
- Email: Hatt2@sapo.vn
- Website công ty: https://www.sapo.vn/
- Fanpage TD: https://www.facebook.com/tuyendungsapo/

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
