### ISSUE TITLE
[Hà Nội] Lập trình viên IOS/Swift - Upto 35M

### ISSUE THREAD

**Issue by Hatt2** [awesome-jobs/vietnam#2634]
## Giới thiệu
Là doanh nghiệp dẫn đầu trong lĩnh vực Thương mại điện tử, Sapo mang đến những giải pháp cho khách hàng trong việc kinh doanh, nền tảng quản lý và bán hàng đa kênh. Với hơn 100.000 khách hàng trên toàn quốc tin tưởng sử dụng, Sapo đang là doanh nghiệp có nền tảng quản lý và bán hàng đa kênh từ Online đến Offline được sử dụng nhiều nhất tại Việt Nam.

Đội ngũ nhân viên Sapo hiện có hơn 1000 nhân sự có trình độ chuyên môn cao, luôn làm việc với tất cả sự nhiệt huyết và sức sáng tạo của tuổi trẻ đã xây dựng nên 1 văn hoá vô cùng trẻ trung và năng động. Đến với Sapo, bạn sẽ được trải nghiệm môi trường tuyệt vời, với chế độ đãi ngộ xứng đáng và đạt được thành công vượt mong đợi!

Xu hướng mobile là điều tất yếu trong các ứng dụng dành cho business, nằm trong hệ sinh thái sản phẩm của Sapo và với mục tiêu tăng trưởng khách hàng rất lớn trong năm tới, chúng tôi cần bạn tham gia team như sau:

## Mô tả công việc
- Phát triển các app mobile (trên nền tảng iOS) của công ty, đáp ứng hàng trăm nghìn khách hàng cùng lúc.

- Đảm bảo chất lượng, tiến độ và trải nghiệm người dùng (hiệu năng, tính dễ sử dụng, cũng như mức độ ổn định của sản phẩm)

- Phối hợp với team để làm các tính năng mới và cải tiến liên tục các phân hệ đã ra mắt.

## Quyền lợi

- Lương/thưởng hấp dẫn theo quy định của công ty.
- Được xét tăng lương 2 lần/năm
- Chế độ BHXH, BHYT theo luật Lao động, ngoài ra được tham gia chương trình bảo hiểm Sapo Care
- Được tham gia các khoá đào tạo từ các chuyên gia hàng đầu về thương mại điện tử, marketing online, phần mềm ...
- Được làm việc trong môi trường chuyên nghiệp, trẻ trung, năng động.
## Yêu cầu

- Thành thạo ngôn ngữ lập trình Swift.

- Có kinh nghiệm xây dựng các ứng dụng sử dụng client server và sử dụng RESTful API

- Sử dụng thành thạo công cụ quản lý mã nguồn Git, và một trong các công cụ quản lý công việc Jira/Trello.

- Có kinh nghiệm về design pattern, thuật toán, quản lý bộ nhớ là một lợi thế.

## Liên hệ
Để tìm hiểu thêm chi tiết, vui lòng liên hệ:
- SĐT: 038.748.0634 (Ms Hà)
- Email: Hatt2@sapo.vn
- Website công ty: https://www.sapo.vn/
- Fanpage TD: https://www.facebook.com/tuyendungsapo/

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
