### ISSUE TITLE
[Citynow Co., LTD] - [Frontend Developer] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by thienthanhne** [awesome-jobs/vietnam#2636]
## Location
* Nguyen Dinh Chieu, Dist.3, HCM
* fulltime/Remote

## Salary Expectation
* up to $1500 NET and negotiable

## Requirements
* 1,5+ years experience

## Skills
* Responsive Web Design
* Unit test (Jest, Mocha, Jasmine)
* Automation test, Containers (Kubernetes, Docker)

### Must Have 
* ReactJS/VueJS/TypeScript
* SCSS, LESS
* Git Workflow
* Be resilient

### Responsibilities

Great power comes with great responsibilities!

### You can bring

* Your passion and hunger for new technologies
* Resilience
* Open to discuss
* leadership mindset
* good logic 

### Why it would be awesome to work with us
* Attractive salary, open to negotiation
* Performance review twice a year
* Chances to go onsite in Japan once the pandemic say farewell
* Month 13 bonus 
* Training perks, tickets to high-tech events, growing career path, ....
* Dynamic culture, team building, company trip, ...

[CITYNOW_JD_FRONTEND DEVELOPER (Junior, Senior).pdf](https://github.com/awesome-jobs/vietnam/files/6700930/CITYNOW_JD_FRONTEND.DEVELOPER.Junior.Senior.pdf)

### Contact
Email: hr@citynow.jp
Tel.: 028 38658926 (Ext 1)
Website: https://citynow.vn
LinkedIn: https://www.linkedin.com/company/citynow/
Fanpage: https://www.facebook.com/citynow.connect
Youtube: https://www.youtube.com/watch?v=OhNKk9Lc59c

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
