### ISSUE TITLE
[Cốc Cốc] Software Engineer, iOS

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#2637]
Currently, We’re looking for talented iOS developers to join our iOS team. You’ll have a chance to develop the Vietnamese mobile browser used by millions of users.

**LOCATION:**  Nguyen Dinh Chieu, District 1, HCMC

**SALARY RANGE**: $2000 - $2500 for level Senior-Leader

**JOB DESCRIPTION**

- Development of Cốc Cốc browser for iOS
- Optimizing performance and quality of the application
- Identify and correct bottlenecks and fix bugs
- Review and document code.

**JOB REQUIREMENTS**

- At least 2 years experience in IOS development using Objective-C
- Will be a plus if you have experience with C++ and/or JavaScript
- Strong communication and interpersonal skills (including reading-writing in English).

 
**WHY YOU'LL LOVE WORKING FOR CỐC CỐC** 

Few countries have local challengers in the search and browser space. Vietnam is one of those countries thanks to Cốc Cốc. There are a lot of challenges in competing against dominant global players, but also lots of rewards when we succeed.

_**Professional growth:**_

What we are doing is difficult, and this is why there are a lot of opportunities to learn and grow – no pain, no gain
You will have to work alongside talented team members who have a unique skill set and expertise in this market
Cốc Cốc is a Vietnamese company but we are also working in an international environment with team members/partners/customers that are local and international
We have a mix of on the job learning/coaching/training to support you in your job and help you grow.

**_Compensations:_**

- Competitive & Attractive salary
- Great Trade Union benefits for staff and family
- Special Annual policy
- Remote work policy.

_**Working environment:**_

- Exciting internal events to help you understand the whole business and make you feel like you are part of the Cốc Cốc family
- Modern and cozy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day, to make sure energy level is high when you need it
- There are many interesting hobby clubs to share your non-professional passions: Yoga, Bicycle, Painting, Board game...

**Contact**
You can visit our career site to find more vacancies: https://careers.coccoc.com/jobs.
If you need to discuss further how we can cooperate, don't hesitate to skype me: khanhhatran213 or email: hattk@coccoc.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
