### ISSUE TITLE
EPAM - JAVA Software Engineer

### ISSUE THREAD

**Issue by Nhudoan16** [awesome-jobs/vietnam#2639]
We are looking for an energetic **Software Engineer specialized in Java** in Ho Chi Minh City office. We have many upcoming opportunities with global brand-name clients for high-profile projects that require someone with excellent technical delivery skills. 

### Responsibilities #

- Write high quality and testable code following clean code principles 
- Implement functionality by following defined software development process without direct supervision 
- Read and understand project and requirement documentation 
- Create documentation describing code 
- Participate in Agile Scrum activities: daily standup, demo session, retrospective, planning, etc.  

### Requirements  

- Bachelor's degree or above in Computer Science, Software Engineering or related majors 
- Welcome all levels of candidates having at least 1.5 years to of experience in software engineering 
- Strong knowledge of Core Java, Spring Boot/Spring, JSON and Maven and REST API 
- Good knowledge of Design Patterns; SOLID, DRY principles 
- Good interpersonal skills, analytical mind, get things done attitude, and passion for engineering excellence 
- Good understanding of software development lifecycle, experience in Agile Scrum process and willingness to adapt to changes in priorities and requirements. 
- Active learner who is passionate about technology and keeps up to date with technology changes 
- Intermediate (CEFR B1) or higher level of spoken and written English 

### Nice to have

- Knowledge of TDD, BDD practices 
- Good understanding of SOLID design principles 
- Knowledge of Database programming e.g. Oracle PL/SQL 
- Experience of development process and CI/CD tools e.g. Atlassian JIRA, Rally, Jenkins, Bamboo, SonarQube, 
- Knowledge in frontend technologies (e.g., JavaScript, React) 
- Experience of Spring Cloud, Microservices 
- Ability to communicate with clients on a regular basis to clarify business requirements

 ### Benefit:
- 19 days paid vacation and 10 days paid sick leave
- Premium Healthcare package
-  Regular assessments and salary reviews 
- Multinational working environment
- 1-1 mentor programs with Epam experts to prepare your next levels and projects at Epam focusing on both Technical and soft skills 
- Unlimited training courses including Technical, English, and Softskill sponsored by EPAM

**EPAM SYSTEMS VIETNAM** 
Level 13, MB Sunny Tower, 259 Tran Hung Dao Street, Co Giang Ward, District 1, HCMC 

### **Contact**
You can visit our career site to find more vacancies: [https://www.epam.com/careers/job-listings?country=Vietnam](url)
Feel free to drop me a line for more detail email: Nhu_doan@epam.com Skype: nhu.doan@outlook.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
