### ISSUE TITLE
Got It Vietnam - Frontend Engineer (JavaScript, AngularJS, ReactJS) - Hanoi - FT

### ISSUE THREAD

**Issue by dokhanhhuyendieu** [awesome-jobs/vietnam#2640]
## Location

* Hanoi, Vietnam

## Salary Expectation

* At least 800 USD

## Requirements
- Strong experience in JavaScript, HTML, and CSS
- 1+ year experience in modern web development
- Good computer science background: algorithm, problem-solving, OOP, Design Patterns
- Experience in responsive web and mobile-first application
- Experience in CSS frameworks and tools (like SASS, LESS, Bootstrap)
- Understanding about REST APIs, client-server communication

### Extra Bonus
- Good knowledge in OOP and design patterns with JS
- Experience with JS frameworks like React.js or Angular.js or Vue.js...
- Experience with ECMAScript 6 or TypeScript or Node.js...
- Knowledge of frontend building tools like Webpack, npm...
- Experience in building JavaScript SDK, Web Widget
- Experience in unit testing frameworks
- Knowledge of web application optimization and securities
- Knowledge of user behavior tracking using the analytics tools like Mixpanel, Google Analytics, etc.

### Why You'll Love Working Here

* **Amazing team:** Work with the smartest and most hard-working people you’ve ever met. Our team is from Google, Facebook, Lyft, Apple, Oracle, GREE,  and other best companies in Vietnam
* **Competitive compensation package:** Great salary, bonuses, and stock options. There is no upper limit on how much you can earn. It’s all based on your performance and contributions
* **Best working environment:** Coffee shop like open office space, kitchen full of snacks and drinks, West lake view bar, video games, 3D TV, soccer table, etc.
* **Latest gadgets for work:** MacBook Pro Retina 15”, external HD displays, latest smartphones and tablets
* **Training and personal development:** Tuition and textbook reimbursement for approved work-related courses. Free video training programs from Lynda.com, Udacity, Udemy, and The Great Courses Plus. Free English classes of your choice taught by native-speaking teachers. Company library with the newest technology and business books.
* **Flexible working hours**
* **Gyms, fitness, and sports:** Full-service gym memberships, soccer or extra dollars in your pocket to spend on your own fitness, swimming, dancing
* **Free daily lunches and dinners** 
* **Others:** Office happy hours, weekly lunch out, monthly team outings, participating in self-organized clubs like sports, games, algorithms, piano, etc. 

### Contact
**Homepage:** https://vn.got-it.ai/
**Email:** hdo@gotitapp.co
**LinkedIn:** https://www.linkedin.com/in/huyendk13/
**Skype:** sundial.dreams

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
