### ISSUE TITLE
[VNTravel] [UI/UX Designer] [HaNoi] [Full-time]

### ISSUE THREAD

**Issue by VanHRVNTravel** [awesome-jobs/vietnam#2641]
## Location

* PeakView Tower, 36 Hoang Cau, HaNoi, VietNam

## Salary Expectation

* Upto $1500/month

## Requirements
* 2+ years of UI/UX experience on Mobile/Web
* Have knowledge about graphic and branding
* Understand UI/UX, be self-motivated in researching and updating new UI/UX trends in the web/mobile field, have knowledge about the principles and elements of design.
* Enthusiastic to learn, creative, flexible, product-oriented design
* Careful, perseverance, meticulous and responsibleness
* Be social, listen and actively contribute to the design of the group
* Can use the application: Figma, Mind map, Photoshop, Illustrator, ... the design description tools is an advantage
* Be able to read English documents well
* Be able to create animation or motion graphic is an advantage

### Responsibilities
* Design and development user interface for app mobile and website follow system design.
* Research, analyze, orient for design’s product follow the new trend and user experience
* Support and coordinate with the remaining teams, creating products with maximum value.

### Why it would be awesome to work with us
* Salary: Up to 1500$ 
* Working in a dynamic and challenging environment, many opportunities for self-development
* Comfortable and good colleagues worked in high technology environments such as Google, IBM, Yahoo
* Interact with the founders, learn problem-solving skills
* Expand knowledge in the field, cultivate skills for the future
* Promotion
* Insurance
* 13th-month salary, 12 days annual leave
* Team activities, company events: football league, birthday party, Tripi Escape Party, movie watching, team building, tourist trip, …
* Free breakfast, coffee, tea, milk and fruits, lunch allowance
* Play Station & Books
* Working time 8:30 – 17:45 (1 hour 15 minutes for break time) Monday – Friday

### Contact
Homepage: https://vntravelgroup.vn/
Email: van.nt@tripi.vn

**Comment by VanHRVNTravel** [comment]
Please contact me if you have any questions about this position.
Skype: vannguyen.1890
Telegram: @vaannt

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
