### ISSUE TITLE
[NFQ Asia] Senior/Lead Nodejs Developer - HCMC/DN - FT

### ISSUE THREAD

**Issue by bangnguyen2510** [awesome-jobs/vietnam#2642]
## Location

* Ho Chi Minh, Da Nang, Vietnam.

## Salary Expectation

* $2000~$3500/ month 

## Requirements
* Strong knowledge of NodeJS, RestFul API (minimum 4 year of experience)
* Good experience with DBMS like MySQL, Redis, NoSQL, ElasticSearch.
* Ensures code modularity and DRYness for maintainability and ensure high performance on Microservices.
* Advanced knowledge and best programming practices of web application vulnerabilities such as cross-site scripting (XSS), session hijacking, SQL injection, CSRF (Cross-Site Request Forgery), OWASP Top 10, and other attack vectors.
* Good English Communication skills.

### Big bonus

* Experience with Front-end Frameworks like Angular, ReactJS.
* Experience in unit test, integration test, automated test, continuous integration on the cloud Amazon/Azure/Google.
* Have good grip on Object Oriented Programming, MVC, Functional Programming.
* Used framework Socket.io is a plus.
* Knowledge in Open API Specifications/Swagger.

### Responsibilities

* Work with super nice clients, make sure that we understand their needs, and deliver their dreams.
* As a central point of contact with our foreign clients, you will have a significant influence on our company’s success by using your excellent English communication skills, your head, and common sense.
* Collaborate with clients/business users to research and validate functional requirements.
* Collaborate with team members throughout the Software Development Life Cycle process using Agile methodologies for requirements gathering, feedback on proposed designs and models.

### Our core value:

* Honest: we only tell the truth
* Transparent: we share information adequately, and openly
* Open-minded: we approach things with candid attitude
* Respect: we treat everyone with the same kindness
* Empathy: sharing feelings matters

### Benefits include:

* Laptop is provided.
* A fun & dynamic environment and freedom to be creative.
* Rock in open-mind, kind & humble band.
* Modern office with a flexible relaxing zone.
* Company trip, team building & other community Tech activities.
* Year-end bonus.
* Loyalty program: Life insurance is provided after 2 years of working at NFQ.
* Performance review 2 times/ year.
* Extra Medical Insurance.
* 15 days annual leaves, working Monday – Friday (9AM-6PM).

### Contact
Email: bang.nguyen@nfq.asia
Skype: bang.nguyen2510

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
