### ISSUE TITLE
TDT Asia - iOS Developer - HN - FT

### ISSUE THREAD

**Issue by Huyen-Trangg** [awesome-jobs/vietnam#2644]
## Location

* Hanoi, Vietnam

## Salary Expectation

* up to 1300$/month

## Requirements
* REST API 
* Read and understand documents in English
* 2+ years experience in Objective C/Swift
### Must Have

* Experience in using one of the database management systems such as MySQL, SQL Server....
* Do a lot of charting, charting, visualize data
 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Participate in the development of applications related to finance (Forex, Stock) on IOS
*  Participating in the installation, writing unit tests, and reviewing the source code of team members.
* Research and apply new technologies to product development.
*  Support deployment on Development, Stagging, Production environments.
* Working with partners in many countries around the world such as Singapore, Japan, Turkey... to discuss the project.
* From teamlead level upwards, manage 3-5 employees.
* Report work results to PM.

### Why it would be awesome to work with us
* Working with leading seniors in the field who have successfully built major technology products at home and abroad.

* Gaining knowledge and skills through big projects in Finance, using new technologies and trends in the world.
* To participate in domestic and foreign workshops organized by the corporation: to research new technologies: AI, Machine Learning, AR, VR, IoT, ... or hobbyist technologies.
* Be trained and develop professionally according to your orientation
* Many opportunities to advance to Teamlead and Project Leader positions for young actors

### Contact
Trollman: Alana.vu@mindbank.tech

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
