### ISSUE TITLE
Fetch - Technical Leader (Fullstack) - HCM - FT - Up to 6,000 USD

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2645]
![Uploading image.png…]()

## HCM

# 4,000 - 6,000 USD

## RESPONSIBILITIES

* Lead the technical team to develop both web and mobile products and follow best coding practices.
* Participate in architectural design, code review, and hands-on development.
* Manage server deployment and maintenance.
* Communicate with stakeholders to consult on technical matters.

## REQUIREMENT

* At least 10 years experience of working in software development with more than 4 years experience in Technical Lead or Technical Architecture.
* Good understanding of SDLC and Agile methodologies.
* Good in English communication, both verbal and written skills.
* Understanding and experience of Kotlin.
* Good backend server creation capabilities using Database communications.
* Good business logic composition capabilities.
* Experience using Node JS and Spring Framework.
* Communication capabilities with Frontend developers using APIs.

Preferred if the candidate has:

* Understanding Microsoft architecture.
* Understanding and experiencing communication between services such as AMQP and gRPC.
* Understanding virtualization solutions such as Docker, k8s.
* Understanding and practical use of event drive frameworks such as AxonIQ. 

## WHY YOU‘LL LOVE WORKING HERE

Being a Technical Lead at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Premium Health Care.
* Opportunity to be part of the pioneer team of a fast-growing start-up making an impact on the mobility landscape in Vietnam. 
* A platform to develop your career through working closely with senior executives and managers in the organization.
* A fulfilling role with lots of learning opportunities in a fun and highly motivating working environment.
* Enjoy diversified activities: Free snack, Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 

## WORKING HOURS & LOCATION

* Working hours: From 9 AM - 6 PM, Monday to Friday.
* Location: 
HCM: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC. 

## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

## OR APPLY IN THIS LINK: https://bit.ly/3h1NYUt

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
