### ISSUE TITLE
[HN] MobileFolk - Ruby on Rails Developer (1,000 - 2,000)

### ISSUE THREAD

**Issue by Giang132** [awesome-jobs/vietnam#2646]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 1,000 - 2,000 USD/month

## About MobileFolk
MobileFolk is a boutique software developer based in Toronto. Since 2008, we have produced top-ranking mobile applications with millions of downloads for the iOS and Android platforms. We provide end-to-end services for mobile and web application creation, including requirements gathering, design, application and server-side programming, testing, documentation, launch and future support

## Requirements

- Good knowledge of Ruby On Rails with at least 1+ year of experience in web development with a portfolio of previous work
- Basic understanding of algorithms, data structures, design patterns
- Knowledge of PostgreSQL, MySQL, Redis
- Excellent knowledge of back-end web development 
- Some experience with search engines (Solr, Elasticsearch) is a plus
- Troubleshooting, debugging, optimizing performance.
- Attention to detail, quality, disciplined work.
- Organized, responsible and able to meet deadlines

## Responsibilities
- Work directly with US-based client on a successful, high growth project
- Deeply participate in the product development process of analyzing requirements, designing systems, implementation, testing, and deployment.
- Collaborate with core functional teams (Sales & Marketing and Operations) to achieve the ultimate business goals.
- Understand and work within the brand and corporate guideline

Great power comes with great responsibilities!

### What we offer you:

- Competitive salary and annual salary review
- English working environment and on the job English training
- Flexible working hours, 5 days a week & flexible paid leaves
- Free food and drink, lunch support with a private chef
- Provide Macbook or Mac mini for work
- Team building and company trip twice/year
- Monthly 1-1 performance review with line manager to ensure you meet your goals
- High work flexibility and ownership.
- Frequent training activities with opportunities to learn new tools and technologies

### Contact
Homepage:  https://mobilefolk.com/
Email: giang@mobilefolk.com
[MobileFolk - Ruby On Rails Developer.pdf](https://github.com/awesome-jobs/vietnam/files/6717411/MobileFolk.-.Ruby.On.Rails.Developer.pdf)

**Comment by dodat98** [comment]
Can you check my email? I send a CV but don't have response

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
