### ISSUE TITLE
[VNPT EPAY - Hà Nội] 02 PHP Developer for Fintech Product (Up to 1600$)

### ISSUE THREAD

**Issue by Tuyendungvnptepay** [awesome-jobs/vietnam#2649]
## Location

* Tầng 14, Tòa Handico Phạm Hùng, Nam Từ Liêm,  Hà Nội
* Thời gian: 8h30 - 17h30 từ thứ 2 - thứ 6

## Salary Expectation

* Up to 1600$/tháng

## Requirements
* Có kinh nghiệm từ 2-3 năm cho vị trí PHP Developer;
* Am hiểu và có kinh nghiệm làm trong lĩnh vực Ngân hàng, tài chính, ví điện tử, cổng thanh toán, các đơn vị trung gian tài chính là một lợi thế;
* Có thể làm tốt front end, am hiểu về HTML/CSS/JavaScript, Responsive, Bootstraps, Less CSS ...; 
* Thành thạo ngôn ngữ lập trình PHP, framework Laravel  hoặc Codeigniter;
* Có kinh nghiệm làm việc với Database Oracle;
* Thành thạo công cụ quản lý source code Git;
* Cẩn thận, trung thực và làm việc có kế hoạch;
* Có tư duy và đam mê làm product, không ngừng học hỏi, nâng cao kỹ năng chuyên môn để hoàn thiện sản phẩm của công ty.

### Responsibilities

*  Tham gia phát triển các dịch vụ của công ty như: Hệ thống ví điện tử MegaV, dịch vụ TOPUP, Dịch vụ ESAN, Dịch vụ chi tiền liên ngân hàng Firm Banking,..;
*  Đóng góp ý kiến và xây dựng các tính năng vận hành hệ thống tự động giúp nâng cao chất lượng công việc;
*  Xây dựng kế hoạch công việc, báo cáo công việc hàng ngày với Team leader;
*  Thực hiện các công việc khác liên quan khi được giao.

### Why it would be awesome to work with us
*  Thu nhập lên tới 1600 USD/tháng;
*  Lương tháng 13 và các khoản thưởng quý, thưởng dự án, thưởng định kỳ, thưởng lễ, Tết;
*  Đánh giá tăng lương 1 lần/năm;
*  Được hưởng các khoản phụ cấp ăn trưa, điện thoại, đi lại, công tác… theo yêu cầu công việc;
*  Được hưởng chế độ bảo hiểm theo quy định nhà nước;
*  Được mua bảo hiểm sức khỏe và chế độ khám sức khỏe chuyên sâu định kỳ 1 lần/năm;
*  Được tham gia các hoạt động của công ty: Xem phim, teambuilding, company trip với chất lượng 4 sao trở lên và các hoạt động thể thao văn nghệ gắn kết khác của công ty;
*  Được làm việc trong môi trường chuyên nghiệp, trẻ trung, năng động và cởi mở đồng thời các thành viên gắn kết như một gia đình.

### Contact
Email: tuyendung@vnptepay.com.vn
Phone number: 0961822258 (Ms. Yến)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by Tuyendungvnptepay** [comment]
thanks I will update in english
