### ISSUE TITLE
Littlelives - Mobile Technical Leader

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#2650]
## Location
* Saigon, Vietnam

## Salary Expectation

* 1500$ - 3000$

### Responsibilities
- Lead the technical team to develop mobile products and follow best coding practices.
- Participate in architectural design, code review, and hands-on development.

## Requirements
* Familiar with push notifications, APIs, cloud messaging, and location tracking.
* Understanding of testing practices TDD & BDD.
* 5+ years Software Engineering experience

### Must Have

- Excellent programming skills in Swift/Kotlin and in-depth knowledge of the developments in the iOS/Android SDK 
- Familiar with commonly used third-party library (Retrofit, Dagger 2, Stetho, Timber)
- Experience with offline storage, threading, and performance tuning
- Deep understanding of the application lifecycle and how to capitalize on the Android system to maximize the user experience
- A personality that enjoys working in a start-up environment where collaboration is open with no shortage of challenging problems to solve

### Ideally
* Kotlin coroutines, RxKotlin experience
* Comfortable using functional programming in your code
* Maintained an app used by hundreds of thousands of users

### Why it would be awesome to work with us

- We WILL push you to learn new things together
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Personalized leadership growth based on your strengths
- 14 days annual paid leave
- Competitive salary
- Macbook Pro and additional screens
- Premium healthcare
- Yearly Bonus

### Contact
Homepage: https://www.littlelives.com
Trollman: quando@littlelives.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
