### ISSUE TITLE
MOBIWORK.,JSC - BACKEND DEVELOPER (FRESHER/JUNIOR) - HANOI - FT

### ISSUE THREAD

**Issue by MOBIWORKVN** [awesome-jobs/vietnam#2651]
## Location 

* Hanoi, Vietnam

## Salary Expectation

* $1000/month or range

## Requirements
* Javascript
* Rest API
* NodeJS (Express, Restify)
* MongoDB
* Proficient in Javascript, JSON, AJAX
* Experience in backend, Rest API
* Prior experience in making systems for orders and warehouses
* Experience in NodeJS (Express, Restify), MongoDB is preferred

### Responsibilities 
* Developing and maintaining Mobiwork's existing DMS (Distribution Management System) products
* Backend programming: provide Rest API for Frontend
* Participating in feature design, reporting according to customer requirements
* Maintain existing features

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analysis skill

### Contact
Homepage: mobiwork.vn
Emai: tuyendung.mobiwork@gmail.com/ngocanh3010.hr@gmail.com
Hotline: 0332213636 - Ms. Anh HR

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
