### ISSUE TITLE
[Full-time] Software Developer

### ISSUE THREAD

**Issue by phungmanhcuong** [awesome-jobs/vietnam#2652]
## Location

* Remote then relocation to Singapore later

## Salary Expectation

* SGD$3000 - $6000

## Requirements
* You have 4+ years of experience using Java based technologies and/ or adjacent development technologies (such as Javascript, Ruby, C#, etc.) with experience in Object-Oriented programming
* You can write clean, high-quality code in a variety of languages and are also able to spot (and improve) bad code
* You're resilient in ambiguous situations and can approach challenges from multiple perspectives
* You have experience with Agile, Lean and/or Continuous Delivery approaches such as Continuous Integration (CI), Test-Driven Development (TDD), Infrastructure as Code etc.
* You are familiar with few databases like MySQL, Oracle, PostgreSQL, SQL Server, NoSQL, etc.
* You’re willing and able to commit to travel to client sites in order to solve their business problems

## Skills
* TDD
* SOLID principles
* OO design
* Pair programming

### Job Overview & Responsibility

* You will champion best practices like writing clean and reusable code using practices like TDD, SOLID principles, OO design, and pair programming
* You will partner with other technologists from cross-functional teams advocating DevOps culture
* You will work in collaborative, product-focused teams to build innovative customer experiences
* Take ownership and accountability beyond individual deliverables, always pushing the envelope in order to deliver awesome results for our clients
* Learn, digest and subsequently apply the latest technology thinking from our tech radar to solve client problems

### Why it would be awesome to work with us
* Remote working for famous international company
* Great opportunity to create a positive impact on the world through technology
* Great benefit: 13th month salary, medical care, ...

### Contact
Homepage: https://www.thoughtworks.com
Skype: cuong.phungmanh
Whatapps: +65 84096090
Zalo: +84 938824817
Connect Linkedin: https://www.linkedin.com/in/phungmanhcuong

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
