### ISSUE TITLE
[FULLTIME REMOTE][ANYWHERE IN THE WORLD] - RUBY ON RAILS/NODEJS/SHOPIFY/ANGULAR/REACT

### ISSUE THREAD

**Issue by zoo-topia** [awesome-jobs/vietnam#2655]
## Location

* Anywhere in the world
* Fully Remote

## Salary Expectation

* $500 ~ $1500/month or range

## Requirements (any of the below)
* Ruby
* PostgreSQL
* 5+ years Software Engineering experience
* Node
* Shopify
* Angular
* React

### Must Have

* Github
* Skype / Slack

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

**Comment by rajukc530** [comment]
contact ?
