### ISSUE TITLE
[Remote job] Senior Developer (Web/ mobile, Reactjs, Nodejs, React Native)

### ISSUE THREAD

**Issue by huyenvu301** [awesome-jobs/vietnam#2656]
* Type of job: Remote job

* Range of salary: $1500-2500

## Requirements

• 3-5 years' experience in Mobile/Web Development Experience.
• Have a passion for React Native, JavaScript & Node Js and are excited to advocate for the platform
• Excellent JavaScript/Typescript skills. Applies security and reliability principles when designing systems.
• Understand the principles of Redux/Mobx and make strong architectural recommendations
• Stay abreast of the latest React and JS libraries and can offer well formed opinions when selecting a tech stack
• Bring your knowledge of design patterns in development (eg SOLID) and platform architecture (Microservices, Event Driven, DDD)
• Experience with test automation at all levels of the test pyramid and beyond, and experience working in a Continuous Deployment model
• GraphQL & AWS Experience a bonus
• Consider the customer impact when making technical decisions.
• Really good communicator both with the stakeholders and the team.
• A real appetite for learning and growing, both as a developer and teammate.
• Great at scripting, knowledge of linux/unix systems commands, shell scripting / python.
• Strong foundation of HTML5, CSS and JavaScript DOM.
• Agile development, experience with scrum or kanban and on-shore offshore models.

• Ideally have worked in fast-growing startups, so you understand the need and ability to be able to move fast

### You can bring

As a Senior Software Engineer well into your career, we know you're exceptional at what you do. You take pride in being someone that more junior members look up to, but you're still eager to learn and hone in on skills as a Senior Software Engineer... That's why we're placing a heavy emphasis on leaning on your expertise to take on a high level of responsibility while being a role model and mentor to others on the team.

### Why it would be awesome to work with us (REQUIRED)

* Opportunity to work on various projects
* Able to work everywhere, no fixed location
* Opportunity to work and share from worldwide colleagues
    
### Contact (MUST)
Mobile phone number: 0981.096.290/ Zalo: 034.2092.367

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
