### ISSUE TITLE
FETCH - SENIOR FRONTEND (ANGULAR, REACT JS) DEVELOPER - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2657]
![image](https://user-images.githubusercontent.com/60914247/123893930-829be800-d987-11eb-8ad8-1ca6bb4d9259.png)

## HCM

# 1,000 - 2,000 USD

## RESPONSIBILITIES
* Develop high-performance web applications.
* Analysis requirements and maintain technical documentation.
* Contribute ideas & solutions to the products.
* Write clear and maintainable code.
## REQUIREMENT

* Have 3+ years of experience in Angular, ReactJS, Vue and HTML, CSS, JavaScript (Can be more proficient in Angular than ReactJS or vice versa)
* Have solid knowledge and deep understanding of Angular and ReactJS. Can analyze and compare algorithms to decide on frontend technologies and build projects from scratch.
* Have solid knowledge of data algorithms, data structures, and code complexity.
* Have solid knowledge in responsive design techniques and front-end optimization techniques.
* Experiences in UI programming are appreciated.
* A team player who can work both as an individual and as a team.
* A passion for software development, new trends, and technologies in IT.
## WHY YOU‘LL LOVE WORKING HERE
Being a Frontend Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* MacBook or high-end laptop for working.
* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

## WORKING TIME & LOCATION

* Working time: 9 AM - 6 PM from Monday to Friday. 
* Location: 4th floor, HQ Tower - No. 9, Tran Nao Street, Binh An Ward, Thu Duc City (District 2), Ho Chi Minh City.

## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
