### ISSUE TITLE
New Ocean Information System - Fresher/ Junior Dot Net - Remote/HCMC - FT

### ISSUE THREAD

**Issue by ngocthao205** [awesome-jobs/vietnam#2659]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

*$900/range

## Requirements
* Microsoft MCP/MCSD on Web Applications or Azure Solutions
* ASP.NET MVC frameworks (3,4,5,6), JavaScript, jQuery, JSON, Web API
* Be familiar with technologies: Asp.Net core, EF6 Code first, Identity Server 4, RESTful, SQL Server 2016, C#, Unit Test
* 1+ years .NET or .NET Core experience

### Must Have

* Honest and confident to directly work with clients
* Loves to work on an innovative product and is ready to learn new things.

### Ideally

* Experience with WPF, Winform, NodeJS, ReactJS
* Agile/Scrum development methodology. 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop ASP.Net and ASP .NET Core based web application or Web API;
* Apply Azure cloud services on application development;
* Participate in software design and codebase architecture with other senior software developers or team leaders;
* Analyze and resolve software issues, software bugs

### You can bring

* A good technical skill and strong spirit for work
* Personal accessories for work

### Why it would be awesome to work with us

* Interesting projects
* Income in accordance with your ability
* Good benefits: insurance, health check, salary increase, funny activities,...
* Young and dynamic working environment

### Contact
Website: https://www.newoceaninfosys.com/
Email: hr@newoceaninfosys.com or thao.pham@nois.vn
Linkedin: https://bit.ly/3hgy3S4

**Comment by ngocthao205** [comment]
Online Interview via Microsoft Team

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
