### ISSUE TITLE
Niteco - Sr. Ruby on Rails Developer - HCMC - Vietnam - FT

### ISSUE THREAD

**Issue by HienTTran** [awesome-jobs/vietnam#266]
Niteco is a world-class software development company with expertise in building custom applications, mobile solutions, and implementation of web content management and e-commerce strategies. Our teams have a proven track record in achieving fantastic success with our global client base by working in close partnership and providing superior consultation value. We are forward thinking and we take pride in delivering a high standard of quality and service to customers. You can have a look at our website http://niteco.com/.

**Location**
- E.town Building 1, 364 Cong Hoa, Ward 13, Tan Binh District, HCMC, Vietnam

**Salary Expectation**
- Attractive
## Requirements
- Relevant technical degree, preferably as software engineer or the likes
- Relevant experience in developing CMS systems, general systems and web development
- At least 3 years of experience with Ruby On Rails development and relevant frameworks
- Knowledge about DB design, IT-architecture and object oriented frameworks
- Experience with automated test and Test Driven Development
- Speak and write English - to be able to participate in daily standup
- Knowledge about Git and preferably GitHub
- Basic knowledge about React, Javascript, HTML and CSS

**Optional:**
- Knowledge about PhP frameworks
- Knowledge about Databases such as PostgreSQL, Redis, MongoDB etc.
- Hosting and deployment in the cloud - e.g. Heroku, Pantheon, Amazon eller Acquia 
## Skills

Ruby on Rails
## Responsibilities
- Take part in various projects for our international clients based on Ruby on Rails platform
- Develop and host our CMS system created for our editorial sites together with our team in located Denmark  
- Participate in defining and implementing the architecture while still following the guidelines provided by the team in Denmark
- Follow best practices and coding standards to ensure the best system performance and deliveries are reusable as well as maintainable
- All hosting and administration is cloud based and is handled by the team
## We offer
- Highly competitive remuneration package: attractive monthly salary with allowances (including allowance for employees with children under 03 years old), 13th  month salary, and additional performance bonus for top performers, high public holiday bonuses, and birthday gift, employee service award up to $1,000 for employees with 3+ years.
- Attractive AON healthcare coverage including health and accident insurance in addition to basic insurances regulated by the Labor Code. Annual company summer vacation abroad and team-building package.
- Opportunities to work onsite for international projects in Sweden, Australia, UK, USA, etc.
- Everyday training opportunities: Pronunciation English classes, Business English Certificate, Project Management courses, soft skills training, Technical Exchange Forum, etc.
- English-speaking, international and professional work environment: working with expatriates from eight different countries, state of the art working space with a wonderful view over the city skyline, modern facilities include computer dual 23.5” screens running Windows 8.1, Office 2013, and Visual Studio 2013.
- Western management style: professional, dynamic, open minded, creative, supportive, friendly, and encouraged for feedback.
- Company’s Management always communicate to all employees about Company’s strategy, development plan and new opportunities for employees.
- Employee and family are engaged and taken care by the company via Trade Union activities.
- Diversified social and charity activities often organized by NICEF - Niteco Charity Engagement \* Foundation to create opportunities for our young employees to raise funds and help people with difficulties in Vietnam.
- Physical care environment where you are taken care, feeling relaxed and enjoying lots of leisure activities clubs such like badminton, ping pong, football, dancing, etc.
### Contact

Hien Tran: hien.tran@niteco.se

**Comment by bluzky** [comment]
Do you have any position for junior Ruby on Rails?
I have experience with Python too.

**Comment by HienTTran** [comment]
@bluzky Hi Dung, at the moment we are building the team so experienced developers would be more suitable. When the project is built, opportunities should also open to juniors. Please feel free to drop me a message via hien.tran@niteco.se or Skype ID: hien-tran-niteco if you have any concerns.
Thank you.
