### ISSUE TITLE
[JobSeekervn] Senior Magento/ Magento Lead - HCMC - $1800 - $2400/ $2300 - $3000

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2661]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation
* Senior Magento Developer - $1800 - $2400/month
* Magento Lead - $2300 - $3000/month

## Requirements
* Strong experience in PHP/MySQL/Javascript building object-oriented websites using popular techs/frameworks
* Very strong experience with Magento 2 framework and modules development, especially for multistore e-commerce
* Know how to integrate Magento 2 with other systems, and be able to do testing
* Must have the ability to develop and customize Magento 2 plugins/extensions for feature enhancement providing new functionality to users.
* Experience with website optimization (site speed, cross-platform responsiveness)
* Experience in personalized themes/customization development
* Solid knowledge of /understanding in Agile, lean code, system design
* Integrity, Commitment, and can-do attitude: There is always a way to overcome the problem, all we need to do is to stay focus, challenge ourselves to deliver what we promised; it's ok to make mistakes, but you would learn from it, not repeat it.

### Responsibilities
* Work with other cross-functional teams to produce technical designs, solutions and also estimation for projects features )mobile-first application)
* Identify, prioritize and execute tasks in the software development lifecycle
* Ensure code quality, best practices, and design patterns are implemented
* To be part of our exciting team, utilizing the newest technologies
* Involved and work with the team in an Agile way.
* Contribute to the continued growth of the teammate skills & processes

### Why it would be awesome to work with us
* Competitive salary. We pay what you deserve, not what the paper says
* We support you go to work using Grab
* Apple Macbook, the external monitor to work
* 20 days for annual leaves
* Private Health Insurance
* 13th-month bonus salary

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn
Homepage: nhiha.top

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
