### ISSUE TITLE
MTI TECHNOLOGY - TECHNICAL ARCHITECT (.NET) - HCM - FT

### ISSUE THREAD

**Issue by aryajerl** [awesome-jobs/vietnam#2663]
## Location

* Tan Binh, HCMC
* Hai Chau, Danang
* 2 remote working days per week

## Salary Expectation

* up to 4000 USD 

## Requirements

- Expert in .NET/.NET Core
- Advanced in cloud platforms Azure or GCP or AWS 
- Advanced in modern architectures/models such as Clean Architecture, Microservices, DDD, Serverless,...
- Intermediate in Database and Query Performance Tuning
- Good experience in CI/CD and Software Testing
- Good experience in Cloud Infrastructure
- Good at Software Designs SOLID, DRY, Design Patterns,...
- Good experience in Performance Optimization, Software Security and other Non-functional requirements
- Good at training/mentoring
- Good at problem-solving skill
- Fluency in English

## Nice-to-have

- Knowledge on Django (Python), Pytest
- Knowledge on Mobile Development (Flutter)
- Knowledge on Container/Docker/Kubernetes
- Knowledge on frontend frameworks Vue.js, React.js
- Familiar with working in an Agile environment
- Knowledge on DevOps/DevSecOps
- Have experience in Kaizen methodology
- Have the ability to handle stressful situations

* Experience with Fintech/Artificial Intelligent

### Why it would be awesome to work with us

At MTI Technology Vietnam, we believe in making our employees stayed happy and beneficial from our talent developing culture and our perks. We offer you a dynamic and international workplace where you solve the big questions for our million-user products and be part of MTI Community. This is the place where you will develop your talent and meet with many other talented colleagues to share your big ideas, receive feedbacks and improve. Let's work smart and play hard with many enjoyable activities at MTI Technology Vietnam!

OUR PERKS!

- 05 working days/week (From Monday to Friday), applying flexible working hours
- **2 days of remotely WFH per week** (based on team's decision)
- Lunch + Gasoline + Coffee Allowance 
- Health, Social and Unemployment Insurance (based on gross-based salary, according to Labor Code) and PVI Health Insurance
- 13th-month salary and Performance bonus
- Annual salary review
- 12 days annual leave plus extra 02 days company leave
- Company trips, sponsored team building, monthly Happy Hour, Sport Clubs (Soccer, Badminton, Pingpong, Yoga) and other joyful events
- A culture of relentless learning with free courses in specialized skills, soft skills, and English
- Yearly health-checkup
- Seniority benefits: allowance & PVI Health Insurances for family members
- Technical-certificate bonus
- Japanese-certificate bonus
- Employee Referral Incentive

### Interesting engineering projects
MTI Ltd. (MTI)  have one of the largest numbers of paid-subscribers in Japan, and their service applications such as “music.jp” or “LunaLuna” are well-known in Japan. MTI has been listed with the first section of Tokyo Stock Exchange since March 24, 2015.
### Contact
Homepage: https://mti-vietnam.vn/
Email to us: nhithp@mti-tech.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
