### ISSUE TITLE
MTI TECHNOLOGY - JUNIOR JAVA DEVELOPER - HCM - FT

### ISSUE THREAD

**Issue by aryajerl** [awesome-jobs/vietnam#2664]
## Location

* Tan Binh, HCM
* 2 remote working days per week

## Salary Expectation

* up to $2000/month or range

## Requirements

- Good knowledge of OOP 	
- Good analysis and problem resolving 	
- Good in JavaCore (Thread, ThreadPool, Java Stream and Lambda) 	
- Experience with Java Spring and write the UnitTest 	
- Experience with T-SQL (MySQL is a big plus) 	
- Experience with HTML, CSS, Typescript

## Nice-to-have:
- Experience in VueJs and NuxtJs

### Responsibilities

- Translate application storyboards and use cases into functional applications
- Design, build, and maintain efficient, reusable, and reliable Java code
- Ensure the best possible performance, quality, and responsiveness of the applications
- Identify bottlenecks and bugs, and devise solutions to these problems
- Help maintain code quality, organization, and automatization
- Working autonomous, proactive following SCRUM (Agile) 
- Report to supervisor/client timely and effectively

### You’ll be responsible for

* Building a platform called Solamichi - a cloud electronic prescribing service that "connects pharmacies and patients" with easy operation that is easy for anyone to us.

### Why it would be awesome to work with us

At MTI Technology Vietnam, we believe in making our employees stayed happy and beneficial from our talent developing culture and our perks. We offer you a dynamic and international workplace where you solve the big questions for our million-user products and be part of MTI Community. This is the place where you will develop your talent and meet with many other talented colleagues to share your big ideas, receive feedbacks and improve. Let's work smart and play hard with many enjoyable activities at MTI Technology Vietnam!

OUR PERKS!

- 05 working days/week (From Monday to Friday), applying flexible working hours
- 2 days of remotely WFH per week (based on team's decision)
- Lunch + Gasoline + Coffee Allowance
- Health, Social and Unemployment Insurance (based on gross-based salary, according to Labor Code) and PVI Health Insurance
- 13th-month salary and Performance bonus
- Annual salary review
- 12 days annual leave plus extra 02 days company leave
- Company trips, sponsored team building, monthly Happy Hour, Sport Clubs (Soccer, Badminton, Pingpong, Yoga) and other joyful events
- A culture of relentless learning with free courses in specialized skills, soft skills, and English
- Yearly health-checkup
- Seniority benefits: allowance & PVI Health Insurances for family members
- Technical-certificate bonus
- Japanese-certificate bonus
- Employee Referral Incentive

### Interesting engineering projects
MTI Ltd. (MTI) have one of the largest numbers of paid-subscribers in Japan, and their service applications such as “music.jp” or “LunaLuna” are well-known in Japan. MTI has been listed with the first section of Tokyo Stock Exchange since March 24, 2015.

### Contact
Homepage: https://mti-vietnam.vn/
Email to us: nhithp@mti-tech.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
