### ISSUE TITLE
[Chợ Tốt] Backend Engineer (Golang, Nodejs, Python)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#2666]
**Cho Tot team is expanding to continuously innovate our marketplace ecosystem to better serve Vietnamese via advance technology. We are looking for talented and passionate individuals to join our foundation software engineering team.**

You will be one of the few key talents who build and run services that are used by ten of millions of Vietnamese people. You will need to tackle highly scaled distributed systems, work in highly automated devops environment on top of many open source, CNCF softwares. You will be supported by our solid SRE team to really craft the software and run the product that you are proud of and other engineers admire.

**Responsibilities:**
Solve engineering problem to enable smart Marketplace ecosystem of products and services.
Design, Build, Run and improve backend services and framework of create microservices.
Manage individual project priorities, deadlines and deliverables.
Improve engineer efficiency with common libraries, tooling and platform.

**Requirements:**
Experience working with one or more from the following: web application development, Unix/Linux environments, distributed systems, machine learning, networking, developing large software systems.
At least 1 year of experience in **Golang** or confident that you can pick it up in no time.
Solid production experience with one or more general purpose programming languages including but not limited to: **C/C++, Python, Java, avascript ES6.**
Experience with two or more data systems but not limited to: **Postgres, Mongodb, Elasticsearch, Redis, Kafka, Cassandra.**

**### Feel free to get in touch via anhhoang@chotot.vn or Skype: tremlobisi94**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
