### ISSUE TITLE
Yojee - Engineering Manager - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#2667]
## Location

* District 4, Saigon, Vietnam

## Salary 

* Negotiate 

## About the role

Yojee is looking for an Engineering Manager who will be responsible for leading and supervising part of our team of engineers in our Ho Chi Minh City office as they develop, create, test and modify new and existing features of our platform. We are looking for an excellent technical leader who will be part of building our product. Being a multinational company, the role will work with international colleagues around the world.
 

## Requirements

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* 5+ years of experience in Agile Software Development, preferably Scrum. 2+ years of experience in people management.
* Experienced and proficient in working with at least two languages, preferably Elixir, Javascript, Ruby on Rails, Go, Scala, Haskell or any other functional programming language.
* Experience with frontend technologies like Angular.js, React.js or vue.js.
* Experience working with relational database systems (preferably PostgreSQL).
* A natural desire to coach, mentor and see other engineers grow in their profession.
* Excellent communication skills and English language proficiency.
* Self-driven, takes responsibility for driving results and embraces an entrepreneurial, start-up culture.

### Nice to have 
* DevOps experience with AWS or Azure, Docker.
* Production experience with Elixir & Phoenix.
* Scripting (Python, Lambda, Bash).
* Certified Scrum Master.
* Experience developing software products for the logistics industry

## Responsibilities

 **Leadership:**
* Together with the existing Engineering Manager, be a leadership figure in the growing Vietnam office.
* Provide strong technical leadership in the development of the Yojee product and coaching of existing engineers.
* Hire, train, and mentor software engineers.
* Write performance reviews and solve internal issues.

**Technical:** 
* Work as part of an agile squad to deliver on product features.
* Continuous improvement and maintenance of our backend systems as well as frontend modules.
* Writing reusable, testable and efficient code.
* Ensuring and enabling reliable connectivity and functionality across services. 
* Work with a large variety of products, connected by APIs.
* Work with the DevOps team to ensure reliable, proactive, and efficient scaling. 
* Work with the other teams to ensure feature parity and cross compatibility.
* Identify, recommend and refactor code as when needed to improve the overall stability.
* May be required to perform other related duties as required.

## Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Company stock: equivalent to 1-3months salary based on your performance
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..
* No 13th month salary
* Unlimited paid day off
* 100% official salary in probation time
* Full social insurance paid based on salary
* Free parking 

## About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=103&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com
Phone: 0924605299

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
