### ISSUE TITLE
[BOGO VIET NAM] - [Mid/Senior PHP/Lavarel developer] - [Hà Nội] - [Fulltime]

### ISSUE THREAD

**Issue by Bogo-VietNam** [awesome-jobs/vietnam#2668]
**Location**
 Hanoi, Vietnam

**Salary Expectation**

* $1100/month 

 **Requirements:**
* Laravel
* JavaScript
* MySQL
* 2+ years Software Engineering experience

**The skills needed for the job**
Experience with Laravel
Experience in working with JavaScript and JS frameworks
Knowledge and ability to apply Jquery, CSS 3, HTML 5
Priority: Experience building browser extensions
Priority: Knowledge and experience in: MySQL, PosgresQL.

**Responsibilities:**
Participate in software product development of the company
Research new solutions and technologies to improve products

**Why it would be awesome to work with us**
Attractive starting salary, competitive, commensurate with capacity and working experience;
Approved for salary increase 2 times/year & 13th month salary according to work results;
Project bonus;
Working from Monday to Friday
Opportunities for training and good promotion at work. Clear career development roadmap;
Enjoy benefits and regimes as prescribed by law (Holidays, social insurance, health insurance...);
Bonuses for holidays, New Year, birthdays, incentives for relatives, annual travel;
Working in a young and dynamic environment

**Contact**
Homepage: https://www.facebook.com/itteaminc
Email: thuy-hr@bogo.vn
SK: thuyleds.8695@gmail.com
Linkedin: https://www.linkedin.com/in/le-thuy-a30a55194/

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
