### ISSUE TITLE
[Chợ Tốt x Carousell] Security Engineer 

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#2671]
Carousell Group’s security team is seeking a security talent who has a solid technical background in application security. You will become the primary security expert for multiple product lines, and act as the point of contact for engineering and security.

**Responsibilities:**
Perform architecture reviews to steer projects in the right direction early, participate in security code reviews, and perform penetration testing against products prior to shipping.
Develop secure coding practices and train engineering teams.
Develop, document, and maintain security and compliance capabilities in support of DevOps processes.
Expertise finding and fixing common security vulnerabilities (e.g., OWASP Top 10)
Performing technical security assessments on our web applications, native clients, internal services

**Minimum qualifications:**
3+ years of demonstrated experience in CyberSecurity, preferred to be in Software/E-commerce companies
Hands-on experience in implementing and operating modern SDLC stack tooling (SAST/SCA/DAST/IAST).
Programming skills in at least one: Go, Java, Python, NodeJS, etc.

**Preferred qualifications (a plus):**
Production experience in security testing of web applications and native apps
Strong understanding of web application architecture and design principles
Background in software engineering in a collaborative and dynamic environment

**### Feel free to get in touch via anhhoang@chotot.vn or Skype: tremlobisi94**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
