### ISSUE TITLE
[Chợ Tốt] Quality Control Engineer (auto)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#2672]
We are looking for Quality Control Engineer, who will focus on building automatic test frameworks as well as design and maintain test scripts to support our continuous integration and deployment process.

**Responsibilities:**
Take ownership and responsibility for the design and development of all aspects of automated testing along with creation, execution and maintenance of automated scripts.
To work with multiple languages such as Java, JavaScript to turn manual tests into auto test scripts, which maintain control regression bugs.
To work closely with Product and Tech teams to understand all system architectures and business use cases, in order to be able to design comprehensive test cases and test plan, define and establish automation strategy and process.
To work with Agile developer and system engineer teams and be responsible for the stability and robustness quality of live software in productions system.

**Requirements:**
Degree in computer science or similar
2 year experience working as Quality control developer, or related position with equivalent experience
Teamwork spirit, problem solving
Ability to work independently with task requires high attention
An expert in scripting and have worked with at least one or more programming language from Java, JavaScript, C/C++, Python, Ruby
Experienced with at least one of open source tools, for e.g Selenium, Cucumber, TestNG, Appium, JMeter

**Plus points:**
Experienced with web application testing, web services testing, performance and load testing
Experienced building and maintaining test automation frameworks
Experienced with Docker and micro services architecture
Experienced integrating test suites into CI/CD tools like Gitlab, Jenkins

**### Feel free to get in touch via anhhoang@chotot.vn or Skype: tremlobisi94**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
