### ISSUE TITLE
[Full time] PHP ENGINEER - HN

### ISSUE THREAD

**Issue by minhquandong** [awesome-jobs/vietnam#2673]
## About us
Chúng tôi là công ty IT-Product được thành lập với 100% vốn đầu tư Nhật Bản. Công ty với 100% vốn đầu tư Nhật Bản, chuyên về phát triển hệ thống, sử dụng ngôn ngữ lập trình PHP.
Một trong những dự án của công ty là hệ thống quản lý đặt chỗ số 1 Nhật Bản được hơn 170 nghìn công ty đưa vào sử dụng và hơn 12 triệu người dùng ở đa dạng các ngành nghề khác nhau bao gồm: Nhà hàng, khách sạn, y tế, sự kiện, salon, v.v…

Hãy gia nhập đội ngũ nhân sự và trở thành Key Member của chúng tôi!

## Location

* Cầu Giấy, Hà Nội
## Salary Expectation

* $1800 - 2200/month

## Requirements
* Có từ 3 năm kinh nghiệm trở lên làm về PHP, nắm vững mô hình MVC, OOP, design pattern, Restful API, Javascript
* Có kinh nghiệm thực tế về thiết kế tài liệu Technical Design/Detailed Design
* Có kinh nghiệm tham gia nâng cấp các dự án đang chạy thực tế.
* Có kinh nghiệm làm hệ thống đa ngôn ngữ.
* Có kinh nghiệm tham gia dự án với lượng người dùng lớn.
* Có kiến thức tốt về Database đặc biệt là Postgre SQL hoặc MySQL.
* Có kinh nghiệm sử dụng Framework.
* Có kinh nghiệm với Git, Github
* Có kinh nghiệm Teamwork.

## Ideally
* Ưu tiên ứng viên có kinh nghiệm thiết kế Functional Design/Basic design
* Ưu tiên có kinh nghiệm về Laravel, Fuel PHP, Symfony, CodeIgniter, CakePHP, Yii.
* Có kinh nghiệm quản lý team là 1 lợi thế.
* Ngôn ngữ : Ưu tiên ứng viên có Toeic trên 600 điểm hoặc tiếng Nhật N4 trở lên

## You’ll be responsible for
* Dựa trên tài liệu thiết kế cơ bản, tạo thiết kế chi tiết
* Thực hiện code, check, fix lỗi theo yêu cầu công việc.
* Tùy theo từng dự án, nhân viên lập trình của trụ trở chính sẽ cùng thực hiện dự án.
* Lập trình theo nhóm (1 nhóm từ 2~ 3 người).

## Why it would be awesome to work with us
* Có cơ hội trở thành Key Member
* Làm việc trong môi trường Công ty đa quốc gia
* Được tham gia phát triển dự án lớn, có tính ổn định cao
* Không phải Over Time
* Cơ hội đi onsite bên trụ sở chính ở Tokyo
* Thử việc hưởng 100% lương 
* Tài trợ party nhóm
* Thời gian làm việc T2~T6 (8h~17h)

## Contact
Linkedin: https://www.linkedin.com/in/minh-quân-đồng-838692196
Email: quan.dm@iconic-intl.com
Zalo/Tel: 0904.532.569

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
