### ISSUE TITLE
Star Global - Senior DevOps Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2675]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* Very impressive - We can't share the range but you can share your expected salary and we'll let you know if that fits in our range of Engineer Level

## Requirements
**Essential skills**
- Strong Linux/Unix administration skills
- Software lifecycle management experience
- Networking fundamentals (switching, routing, load balancing)
- Versioning (Git, GitHub etc.)
- Scripting/programming skills (Bash, Python/Ruby, etc.)
- Monitoring tools (Grafana, Prometheus, Datadog, etc.)
- Experience with relational DBMS (MySQL, PostgreSQL, etc.)
- Excellent written communication and the ability to communicate verbally with the customer (English)
- Bachelor’s degree (or equivalent work experience)

**DevOps skills**
- Continuous Integration/Delivery (CircleCi, GitLab CI, Jenkins etc.)
- Cloud/virtualization experience (AWS, Docker ecosystem, KVM/XEN, Vagrant etc.)
- Cloud orchestration (Terraform, etc.)
- Practice experience with AWS (EKS, CloudFront, EC2, S3, kubectl)
- Configuration management (Chef, Puppet, Ansible, Salt, etc.)

**Bonus skills**
- NoSQL DB knowledge (Redis, Memcached, MongoDB, Cassandra, etc.)
- Understanding of containerization concepts, scheduling and orchestration systems
- Understanding of Distributed Systems concepts, High Availability, vertical and horizontal scalability
- Log analytics (ELK/EFK stack, Sumologic, Splunk, etc.)
- Any other public cloud experience (Google cloud, Azure)

### Must Have

* Solid DevOps experience
* Good communication in English (TOEIC 700/IELTS 6.0)

### The Opportunity

We’re looking for an experienced engineer to jump right in and join our _**high-performance DevOps group**_. As a team member, you’ll experience software operations and development engineers working together across the entire service lifecycle – from design through the development process to product support. It’s a new way of working that builds on the recognition that there’s one entity standing behind a successful product: the delivery team.

We care about simplicity and we believe the Agile Manifesto is a better way of doing software development. Our everyday practice involves virtualization, containerization, dealing with the Cloud, networking, configuration management systems, deployment automation and much, much more. Co-creation is what we’re all about. 

Join us and get involved!

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ New Macbook and accessories provided
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/senior-devops-engineer-1617105118/
Recruiter: quyenphan@star.global (Skype: pmq0406)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
