### ISSUE TITLE
JENFI - HEAD OF ENGINEERS (RUBY) - HANOI/SAIGON - FT- REMOTE

### ISSUE THREAD

**Issue by cuongnc0211** [awesome-jobs/vietnam#2676]
## Company Introduction

Jenfi provides lends to businesses in Asia for growth based activities using revenue and alternative data to underwrite.

Small businesses in Asia are highly “bankable” yet over 50% are unable to obtain a loan. The simple reason boils down to economics. Jenfi solves this problem by providing an automated digital platform to help business owners finance their growth. The Jenfi platform utilizes revenue and alternative data via various data integrations to underwrite businesses quickly. The borrower can choose repayment options that are tied to a percentage of their future sales.

Jenfi launched in 2019 in Singapore and currently expanding in SEA.

## Location

* Vietnam
* Remote

## Salary Expectation

* upto 5000$ or beyond

## About The Role

We are looking for a strong, energetic, deeply technical leader, with a growth mindset to lead the Rails team, unify infrastructure and platforms for Jenfi.

As Head of Engineering you will partner with the CTO on strategy and vision for the Jenfi’s technical foundation, and lead teams in execution to achieve it. You will champion Jenfi’s mission by developing user experience, driving the use of modern system software and developer productivity, enhancing our cloud native infrastructure services, building quality into everything we do, and coaching teams of high-performing engineers, and engineering leaders. You will collaborate closely with the Product Owner, Credit Team and CEO to fully integrate solutions that delight our users and achieve business goals.

The role reports to the CTO.

## Key Responsibilities

Own the technical strategic roadmap planning and execution for new common platform products and system architecture, including end-to-end implementation and integrations.
Lead the development of our group’s software system architecture and infrastructure services to deliver a reliable, efficient, secure and developer friendly platform that enables high speed software development at scale.
Ensure our global platform operates securely and efficiently 24x7.
Contribute in senior product strategy planning as a champion of technology and quality engineering.
Collaborate with both technical and non-technical stakeholders across geographical regions to define relevant must-win engineering issues.
Own the engineering practices, raising the bar for the quality and speed of software delivery and operations.
Set clear measurable goals for your engineers and engineering leaders.
Foster a culture of continuous growth improvement through coaching, mentoring, feedback and clear measurable outcomes.
Define and manage SLA for data sets in allocated areas of ownership.
Attract, develop and retain great engineering talent, passionate about foundations engineering and serving internal and external users

## Qualifications

Focus on impact and results. You work on the right things and get them done.
Drive and resourcefulness to persevere and overcome obstacles achieving challenging goals.
Exceptional technical judgement. Willingness and ability to take smart risks and fail forward.
Ability and motivation to to roll up the sleeves and dive deep to help the team when needed.
Track record of successfully solving complex and ambiguous problems.
High integrity and ability to positively collaborate with others
Ability to speak and write succinctly and clearly in English.

## Requirements/Functional Skills

5+ years experience as a hands-on engineering senior leader, with experience managing remote teams across countries.
7+ years of experience in engineering.
A track record of developing and leading production platform teams via mentorship and coaching diverse, multi-cultural engineers and engineering managers.
Deep knowledge of Rails/Ruby, and knowledge Postgres, Redis, AWS, Docker, DevOps
Strong CS foundation and practical experience with software development, architecture and design. Excellent knowledge of monolithic design patterns, problems and solution patterns.
Experience working with following software architectures, techniques and technologies: Docker, Docker-compose, Redis, PostgreSQL, cloud infrastructure using AWS and GCP.
Business understanding and ability to manage a budget. Ability to identify, evaluate and convey the engineering and technology choices and trade offs.
Bachelor’s degree, with a strong academic record, in Computer Science or Engineering, Masters preferred.

### Contact
Homepage: justin@jenfi.com
product: jenfi.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
