### ISSUE TITLE
[iKonnect] - Site Reliability Engineer - Relocate to London, UK - FT

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#2677]
## Location

* London, UK (Fully Visa Sponsor)

## Salary Expectation

* 50,000 - 65,000 £ per year

## Requirements

- You are very strong at algorithm, logical-thinking
- You enjoy making infrastructure more automated, flexible and robust
- You have a deep knowledge of operating system fundamentals (we use Ubuntu).
- You enjoying collaborating with others
- You are familiar with a scripting language, like Python or Bash
- You enjoy troubleshooting and know how the common profiling/debugging tools work
- You have knowledge of containerised environments and configuration management tools
- You are interested in working in a modern AWS and Kubernetes environment.

### Responsibilities

Reliability/infrastructure engineers work on critical systems underlying the rest of the firm’s technology, making use of both their SRE skills and mindset. The team is building a reliable, low-latency, highly concurrent system capable of handling thousands of executions per second. As our engineers deploy to production several times a day, the underlying system has to be robust and support good observability in an ever-changing environment. We are improving our AWS/Kubernetes infrastructure, and are looking for someone passionate to help us build a low-friction, highly available production environment.

This is not a traditional SRE role - more of a fusion between classic DevOps and Site Reliability Engineering. In fact, the team should not maintain systems. They write code and tools to take care of it instead.

### Contact
Homepage: https://ikonnectvn.com/
Ms. Tran: tran@ikonnectvn.com (Skype: tran.ngoc.161)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
