### ISSUE TITLE
Star Global - React Native Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2678]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* Very impressive - We can't share the range but you can share your expected salary and we'll let you know if that fits in our range of Engineer Level

## Requirements

- 1+ year of production experience in React Native
- 2+ year of production experience in React
- Experience in writing tests: Jest, React Native Testing Library and Detox
- Experience with building delivery pipeline: mobile CI/CD, Fastlane and beta distribution
- Experience in working with native modules for React Native as well as using third party open source modules
- Expert developing against RESTful APIs
- Upper-Intermediate level of spoken and written English

## Skills

- **React Native + ReactJS**
- Good communication in English (TOEIC 700/IELTS 6.0)

### Responsibilities
We are looking for a Front-End Engineer with React Native & React experience to become a core member of our new projects. You will handle either the entire product development process or, at the very least, a significant part of it. You will work closely with the clients, determine the product functionality, define the architecture, and estimate the overall work. When you join our ranks, you will work closely with world-class technology entrepreneurs from the world’s most prominent innovation hubs. These include Silicon Valley, Scandinavia, United Kingdom, Germany, and many other countries that may require business trips.
Your primary focus will be on developing user-interface components and implementing them following well-known React.js workflows (Redux, Redux-Saga) with React Native on the mobile. You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality product are important.

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ New Macbook and accessories provided
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/react-native-engineer-2-12/
Recruiter: quyenphan@star.global (Skype: pmq0406)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
