### ISSUE TITLE
 Middle/senior full stack Django developer

### ISSUE THREAD

**Issue by nguyenducgiang** [awesome-jobs/vietnam#2679]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* $1000 - $2500/month

## Requirements
* 2+ years of experience with Django
* Have experience with Vue/Nuxt
* Conversational English

### Must Have

* Python 3, Django 3
* Conversational English

### Ideally

* Experience with Vue/Nuxt

### Responsibilities

Cooperate with other team members and client teams to develop various products for internal and external use.

### You can bring

* A good analysis and communication skill

### Why it would be awesome to work with us

- Macbook pro is provided for work
- 13th-month salary
- Liberty health insurance
- Yearly vacation trip
- Salary review once a year
- Team building activities
- Grants for online courses, books & other learning materials
- Private English class (this is per case and needs to be reviewed and approved from management)

### Contact
Homepage: https://flyingwhales.io/
Email: hello@flyingwhales.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
