### ISSUE TITLE
FPT TELECOM - SOFTWARE DEVELOPER (JAVA) - HN - FT

### ISSUE THREAD

**Issue by Tranhath2** [awesome-jobs/vietnam#2680]
## About Company

_Công ty cổ phần viễn thông FPT - FPT Telecom là nhà cung cấp dịch vụ internet, truyền hình và các dịch vụ gia tăng trên nền tảng internet với hơn 20 năm hình thành và phát triển. HIện tại FPT Telecom đang có mặt trên 59 tỉnh thành trong nước và một số thị trường quốc tế. Với phương châm “mọi dịch vụ trên một kết nối”, chúng tôi kỳ vọng mỗi gia đình việt nam đều sử dụng ít nhất một dịch vụ của FPT Telecom trong tương lai._

_Trung tâm thanh toán điện tử FOXPAY là môi trường với đội ngũ nhân viên chuyên nghiệp, tạo nhiều cơ hội phát triển và mở rộng hiểu biết, nâng cao kỹ năng một cách tốt nhất_

## Location

*  FPT Tower - 10 Phạm Văn Bạch, Dich Vong Hau, Cau Giay, Hanoi.
*  Thứ 2 - Thứ 6
*  Fulltime

## Responsibilities

- Số lượng: 6
- Phát triển core service theo kiến trúc micro service trên nền tảng Java, Spring Boot.
- Phát triển các service tích hợp với đối tác, đảm bảo an toàn, bảo mật.
- Nghiên cứu áp dụng các công nghệ mới, phát triển sản phẩm mới.
- Làm việc theo sự phân công của Trưởng nhóm/Quản lý dự án, phối hợp giữa các nhóm để phát triển sản phẩm.
- Phòng Phát triển ứng dụng, Phòng tích hợp, Phòng Core Ví & Cổng

## Requirements

- Phát triển core service theo kiến trúc micro service trên nền tảng Java, Spring Boot.
- Phát triển các service tích hợp với đối tác, đảm bảo an toàn, bảo mật.
- Nghiên cứu áp dụng các công nghệ mới, phát triển sản phẩm mới.
- Làm việc theo sự phân công của Trưởng nhóm/Quản lý dự án, phối hợp giữa các nhóm để phát triển sản phẩm.
- Phòng Phát triển ứng dụng, Phòng tích hợp, Phòng Core Ví & Cổng

### Benefit

* Gói thu nhập tương đương từ 14 - 17 tháng lương quy đổi (Thưởng lương tháng 13, lương kinh doanh, tiền mừng tuổi...).
* Chính sách phúc lợi theo quy định của Công ty đa dạng: Chăm sóc sức khỏe định kì hàng năm; Gói bảo hiểm sức khỏe chuyên biệt (FPT Care – Khám chữa bệnh miễn phí tại tất cả các bệnh viện); Các hoạt động tri ân, chăm lo đời sống tinh thần CBNV và Thân nhân...
* Môi trường làm việc thân thiện, cởi mở.
* Cơ sở vật chất và công cụ làm việc hiện đại, tiện nghi.
​* Nhiều cơ hội phát triển và thăng tiến.
* Văn hóa Doanh nghiệp đặc sắc, sinh động bậc nhất với nhiều các hoạt động hấp dẫn: tân binh, 72 giờ trải nghiệm, teambuilding, thi trạng, hội làng, hội diễn Sao Chổi, sinh nhật FPT, ngày 08/03, ngày 11/11,...
* Hưởng các gói ưu đãi cước khi sử dụng dịch vụ của FPT Telecom.

### Contact

* Email: hattt54@fpt.com
* Skype: tranha.ql
* Phone: 0946 929 092 (Telegram/Zalo)
* Linkedin: https://www.linkedin.com/in/tranthuha-hr/

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
