### ISSUE TITLE
[CMC Global] - [Junior-Senior-Techlead Java Developer] - [Ha Noi] - [FullTime]

### ISSUE THREAD

**Issue by HuyCMCGlobal** [awesome-jobs/vietnam#2682]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $700-2000/month or range

## Requirements

* Have at lease 1+ years Software Engineering experience
* Have knowledge about: Java/J2EE; OOP
* Can use framework Java Srping boot, Spring, Framework Java and have knowledge ablout frontend is a plus.
* Database: SQL/MySQL or Oracle....

### You’ll be responsible for

* Design, implement and maintain software components in complex, distributed systems; 
* Work closely with other groups (QA, Tech Support) to effectively diagnose and resolve software defects
* Design, implement and maintain software components in complex, distributed systems; 
* Prioritize tasks and communicate to senior management effort estimates and project status periodically.

### Why it would be awesome to work with us
* Young and dynamic working environment. 
* Continuous development of hard and soft skills through work and  professional trainings. 
* Opportunity to approach newest technology trends 
* Exciting leisure: sport and art events (football club, family day...) 
* Company's labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trip, Holiday, etc.) 16M/years

### Interesting engineering projects
* You will join our's project in US,UK, India...

### Contact
* Email: tvhuy@cmc.com.vn
* Skype: huytv2612   or Phone: 0967383196
* Linkedin: https://www.linkedin.com/in/huytranhr2612/

**Comment by HuyCMCGlobal** [comment]
Ai đó đừng bơ em nữa đi mà =)))

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
