### ISSUE TITLE
Engineering Manager - Hanoi - Fulltime

### ISSUE THREAD

**Issue by nttvan176** [awesome-jobs/vietnam#2683]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Negotiable/No limit 

## Responsibilities

* Act as technical lead of Back-End Engineering Team
* Advise solutions for the technical challenges and issues
* Train engineers to make sure they reach and improve skills, based on LINE's standard levels
* As part of the Organizational Growth Team, create impacts on both individual and organizational level. You'll coach and mentor engineers to help them grow, and see if their development is reflected during the performance appraisal
* Be on the front-line of our Talent Acquisition efforts: you'll join in the Recruitment and Employer Branding activities to attract and hire top talents

## Requirements
* At least 5+ years with Engineering Manager
* Deep, hands-on programming experiences using Java/Golang/Python
* Strong experiences in shipping high-quality web applications (server-side)
* Significant experiences leading a team in the delivery of web applications for PC and mobile
* Knowledge of Accessibility, Usability, and Security standards
* Strong track record of building and growing a highly productive software engineering team

### Must Have

* Python
* Golang
* Server
* Java

## Ideally

* Desire to research and apply new technologies
* Challenge-welcoming mindset
* user-first perspective when developing services
* Proven leadership and interpersonal skills
* Ability to effectively communicate high-level strategy and technical details across disciplines, locations, and teams
* Public speaking skills

## Priority for candidates

* Experience developing Internet products with high usability
* Experience developing iOS and Android mobile client applications
* Experience in Front-End development
* Direct experience in open-source projects and community activities
* A strong desire to learn and share tech knowledge

## Why it would be awesome to work with us

 * Package: Competitive package, including 13th-month salary, and performance bonus every 6 months on top of monthly salary.
* Allowances: Monthly team-building, transportation, and language training allowances
* Fully-paid company trip, monthly Happy Friday, and various events throughout the year
* Fully-paid social insurance and premium health insurance for employees and their family
* Corporate stock options
* Top-notch equipment & tool
* Facilities for efficient working and winding down
* Opportunity to collaborate with a global team

## Report To

* CEO

## Interviewing Process
* 1. Interview with BOD -> 2. Online Test -> 3. Interview with Tech lead 

## Contact
* Email: nttvan1762@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
