### ISSUE TITLE
Star Global - NodeJS Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2684]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* Very impressive - We can't share the range but you can share your expected salary and we'll let you know if that fits in our range of Engineer Level

## Requirements

- 3+ years of experience as a Back-End Engineer using Node.js
- Proven hands-on experience in GraphQL and SQL (Postgres DB)
- An expert in developing RESTful APIs and has knowledge about CORS
- Experience with TypeScript/JavaScript
- Experience with koa.js and Apollo GraphQL
- Experience in working with Yarn and Lerna
- Understanding of CI concepts
- Understanding of app/browser performance
- Understanding of Agile/SCRUM principles
- Bachelor’s degree in a technical discipline and related fields
- People-oriented and a team player
- Upper-Intermediate spoken and written English
- Excellent written and verbal communication skills with customers
- Familiarity with React.js or any other front-end frameworks is a plus
- Experience in writing semantic HTML5, CSS3, and CSS preprocessors like Sass and Less

Nice to have experience with:

- tray.io
- Google APIs (Google Calendar API)

### Must Have

NodeJS & GraphQL

### Responsibilities

We are looking for a Back-End Engineer (Node.js) to become a core member of our new project. It’s a SaaS-based enterprise solution that integrates building systems into a single, centralized, digital platform. 

- You will handle a significant part of the product development process, and build integrations between the client platform and third-party products.
- You will work closely with the clients, determine the product functionality, define the architecture, and estimate the overall work.

When you join our ranks, you will work closely with world-class technology entrepreneurs from the world's most prominent innovation hubs. These include Silicon Valley, Scandinavia, United Kingdom, Germany, and many other countries that may require business trips.

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ Latest MacBook Pro & monitor or you can **Bring your own Device**, we'll compensate you monthly!
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/nodejs-engineer-8889983/
Recruiter: quyenphan@star.global (Skype: pmq0406)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
