### ISSUE TITLE
CrossTech - ReactJS  Developer - HCMC - FT (currently remote) 

### ISSUE THREAD

**Issue by CrossTechHeadhunt** [awesome-jobs/vietnam#2685]
## Location
* Saigon, Vietnam
* Remote
* We are conveniently located on Thu Duc/ District 3.

## Salary Expectation
*$700+ for junior developer
*$1300+ for mid-level developer

## Requirements
- Bachelor/College degree in IT, Computer science or equivalent
- At least 1 year of experience
- Proficient with ReactJS
- Ability to communicate clearly verbally and in writing in English.
- Willing to learn, understand new/emerging technologies & good teamwork skills

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!
- Study, analyze & clarify projects’ requirements together with the team
- Design, develop, unit test, and deploy software applications in good quality.
- Assure delivery of the final product based on scope, requirements, schedule, etc.
- Make research and development (finding solutions for difficult issues, studying new software, reading technical articles, searching for new development environment...).

* A good eyes for design
* A good analysis skill

### Contact
Email: headhunt.crosstech@gmail.com
Phone: 0963282927

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
