### ISSUE TITLE
CodeBox Solutions - Fresher Web Developer - HCMC - FT

### ISSUE THREAD

**Issue by lntan** [awesome-jobs/vietnam#269]
## Location

HCMC, Vietnam. Not recruit the remote candidates.

## Salary Expectation

$350 - $500

## What You Will Do

- To be trained on web development in RoR or .NET in real projects
- To work on both front-end and back-end
- Have the chance to work directly with Project Owner in the US or AUS
- Regular online meetings with client team
- Requirement analysis and finalization
- Implement new features and improve the existing ones
- Quality maintenance (production support, bug fixing, etc.)...
- Enjoy our friendly working environment

##  What You Are Good At

- No working-experience is required
- Bachelor’s degree (Computer Science/IT or equivalent major)
- Verbal communication in English
- Enthusiasm for web development
- Enthusiasm for learning new programming languages and technologies
- Basic understanding of HTML, JavaScript, CSS, Rest API, AJAX and MVC
- Knowledge of development on Linux environment is a plus
- Knowledge of Agile/Scrum development is a plus
- Logical and proactive thinking

## Contact

CodeBox Solutions Recruitment: hr@codebox.vn or FB https://www.facebook.com/codebox.vn
Company information: http://codebox.vn/

## About Our Company

CodeBox Solutions Ltd. is an international software development company based in Vietnam – HCMC with its branch in the United State - California.

We are a group of very selected people who share the same passion and enthusiasm on developing software that speak the language of the end user. Specializing in Ruby (our favorite), .NET, and mobile programming languages, we have been delivering high value products and professional services to our clients across 5 countries. 

At CodeBox, we also have innovative, business-driven quality assurance and independent testing services.

We are growing quickly and believe in creating a culture of openness where the relationship between the manager and staff is always honest and respectful. This ensures the growth of both our team and individuals. 

We always welcome talented and enthusiastic software engineers to join us!

### Why Work With Us

- Be your own manager. We only manage the quality 
- Want challenges and rewards? We have both for you 
- A very friendly environment where we grow together
- Opportunity to work abroad with Project Owner in the US or AUS
- An optimizied management system that helps you feel comfortable at work
- 13th salary and attractive project bonus
- Support purchase laptop (50% of the value)
- Work-from-homework policy
- Compliance fully to Vietnam labor code
- Company trip, teambuilding
- Birthday celebration
- Extra healthcare package

**Comment by GitBulk** [comment]
Is there any chance for .Net experienced dev ?

**Comment by lntan** [comment]
Yes. There is.

**Comment by lntan** [comment]
@GitBulk  https://github.com/awesome-jobs/vietnam/issues/264

**Comment by nnti3n** [comment]
Is the salary only limit at $350-$500

**Comment by hieubkcse** [comment]
@nnti3n for Fresher Web Developer
