### ISSUE TITLE
[Moneyforward Vietnam] - Senior RoR Engineer - HCM/FT

### ISSUE THREAD

**Issue by ncbtoan** [awesome-jobs/vietnam#2692]
## Location

* 21Fl, ETown Central Building, 11 Doan Van Bo, District 4, Ho Chi Minh

## Salary Expectation

* Very attractive 

## Requirements
* Experienced as a Software Engineer
* Expert with RoR

### Must Have

* 5+ Yoe with Ruby on Rails
* Experience with MySQL or PostgreSQL
* Ability to communicate in English

### Ideally

* Familiarity with unit test in Rails
* Experience with frontend development (ReactJS, VueJS, jQuery)
* Experience with Amazon Web Services
* Experience with fintech

### Why it would be awesome to work with us

- Salary review: Twice a year
- Bonus: 13th-month salary
- Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
- Awards: Monthly Culture Hero, Half-year MVP for excellent members
- Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
- Devices: MacBook Pro + Dell Monitor
- Working hour: Monday to Friday (working hour starts from 8am to 9am)
- Health care: Annual health check
- Insurance: Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary); Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
- Training: External or internal training courses; Internal workshop; Support Attending Conference; Scrum training; Order books based on member's requests
- Others: Grab expenses on the party day; Club activities, playstation, billiard, etc… Free bike parking, fruits and coffee

### Contact
Email: recruit@moneyforawrd.vn
Skype: [Toan Nguyen](https://join.skype.com/invite/wV7detxuGSNo)
Homepage: https://careers.moneyforward.vn/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
