### ISSUE TITLE
[FinOS Technology] Senior Java Fullstack Developer (Spring/ Angular)

### ISSUE THREAD

**Issue by TamNguyen16** [awesome-jobs/vietnam#2693]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to $2500 per month

## Requirements
* Proven hands-on experience on Java ecosystem, Spring boot, Microservices, PostgreSQL
* Experience creating web application using Angular.io and Bootstrap
* Strong knowledge of writing secured codes and good understanding of design patterns
* Experience in agile scrum-based development process.
* Cloud based technologies: AWS, Kubernetes, Docker is BIG plus.
* Working knowledge of Scala/Spark/Kafka or any functional programming languages is a very BIG plus.

## Responsibilities

* Work as senior software developer on the web-based application product in JAVA- related and open-source technologies.
* Develop and enhance product offerings in accordance with design, consistent with business objectives.
* Continuously research and implement new technologies to maximize development efficiency.
* Identify potential issues and working out possible solutions.
* Develop new user interface features in a large-scale of web application.
* Ensure the technical feasibility of UI/UX designs.
* Optimize application for maximum speed and scalability.
* Develop web templates based on graphical web layout designs that follow the strict requirements.

## Why it would be awesome to work with us

* Attractive salary 
* 13rd month salary + Performance bonus
* Open and flexible working environment
* Full social insurance and benefits according to the legislation
* Healthcare: Annual health check-up, Premium Health Insurance
* 16 AL, 30 sick leaves
* Lunch & Mobile Allowances
* Flexible benefit
* Macbook Pro 15 inch
* And more to come

## Contact
Website: https://finos.asia/
Skype: ntnt1695
Email: tam.nguyen@finos.asia

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
