### ISSUE TITLE
Virtual Internships - UI/UX Designer - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by vi2021** [awesome-jobs/vietnam#2694]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* $1,000 - $1,500 per month

As **[Virtual Internships]**(virtualinternships.com) enters a high-growth phase we are seeking hiring a passionate, user centered UI/UX Designer to join a collaborative and innovative team to create visually delightful and easy-to-use digital products. 
You will work with stakeholders, developers to understand the big problems and collaborate on effective solutions. You will be engaged in every part of the UX process, including user research, interaction design, user interface design, and visual design.

## Requirements

- Managing user research, including focus groups, customer interviews and usability testing. 
- Analyzing client needs and translating into detailed, organized documentation and prototypes
- Work with quality engineering, development, and marketing teams to understand product and branding directions and develop appropriate and consistent design solutions
- Create concept visual solution or framework and pitch to product and tech team from historical, design, business and competitive standpoint.
- Assist in task management and planning for on time delivery.
- Follow DEV sprint framework (Srum methodology)  to deliver on time for developers to start on implementation.
- Follow and improve internal design process : brief, wireframe, concept, variations, deliverables.
- Design UI; UX for Webapp.
- Collaborate with front-end developers to create professional and UX-optimized products.
- Create design artifacts of the appropriate fidelity depending on the needs. This can range from sketching, to flat mockups, to interactive HTML/CSS prototypes
- Production of custom UI assets as required by the development team.
- Maintain and develop company products style guide.

## Skills

- 2+ years hands-on experience in interaction design.
- Experience with common design software (Adobe products, Sketch, Figma, Keynote/PPT for the creation of IXD artifacts, documentation, and presentations -or- fluency with Photoshop and Illustrator or Sketch). 
- Experience working in agile and lean environments.
- Already based in Vietnam with right to work.
- Enjoy and thrive working in a start-up environment.
- Interest/Passion in EdTech.

### Why it would be awesome to work with us

* Remote flexible
* International team
* Possibilities to fasten your career track
    
### Job Description & Where to Apply: 

Apply at our [Careers Page](https://www.virtualinternships.com/about-us/careers/)
OR send your resume to Email: recruitment@virtualinternships.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
