### ISSUE TITLE
[LINAGORA VIETNAM] JAVASCRIPT DEVELOPER - FULLTIME - HANOI

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2695]
## LOCATION

* 5 Dien Bien Phu, Hanoi

## SALARY RANGE

* Up to 40m gross

## BASIC QUALIFICATIONS

* Background in Computer Science/ Information Technology or equivalent.
* Experience in Javascript or Typescript
* Backend service experience in Nodejs and frameworks like Expressjs or Fastify
* Experience with JavaScript and modern frameworks like React or Vue
* Experience in building Restful APIs
* Experience in using Git
* Good level in English skills: written and spoken

## PREFERRED QUALIFICATIONS

* Experience designing and delivering high-availability, scalable cloud-based systems
* Experience working in state management like Vuex or Redux
* Experience working with SQL or NoSQL data stores
* Good Linux/Unix experience• Experience in automated testing
* Knowledge of modern development tools, like Docker, Webpack, etc.

## RESPONSIBILITIES

* Write high-quality, clean, maintainable, reusable code using engineering best practices
* Analyze requirements, design, and develop features.
* Understand the product, constantly optimize the product, identify and fix problems, improve stability and user experience.
* Collaborate with fellow developers, product managers, user experience designers, and operation engineers to build products with web technologies.
* Optimize application for maximum performance and scalability.
* Participate in regular internal technology sharing and other regional tech events.

## WHY YOU’LL LOVE WORKING WITH US?
 
* Competitive salary (up to 40m gross), lunch allowance, 13th-month salary
* Work from everywhere, correct work-life balance.
* Work with highly skilled people for international projects.
* Modern working space
* Team retreats

### CONTACT

* Homepage: https://linagora.vn/
* If you are interested in the company, please kindly send your CV to vnhr@linagora.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
