### ISSUE TITLE
[Eastplayers] Software Engineer (ReactJs)

### ISSUE THREAD

**Issue by esp-dqtran** [awesome-jobs/vietnam#2699]
## Job overview
Eastplayers is a rising star in E-com Tech & Outsourcing companies from Vietnam. We are a proudly Made-in-Vietnam start-up. We are not experts at technical. **We play technical!** We’re now looking for a **true Player** to join the battle. This person should possess an intense passion for technology & constantly challenge and exceed their comfort zone. In another word, **this person must be a real fighter!**

## Location
Block Iris 2, Hado Centrosa Garden, 3/2 Street, Ward 12, District 10, HCMC

## Salary Expectation
Up to 1200$/month

## Requirements
- Skilled in HTML, CSS, SCSS, Responsive, FlexBox
- Ability to write clean and concise code
- Deep understanding of frontend technologies
- Solid experience with modern build tools (Webpack, Parcel,...).
- Good command of English
- 1+ years experience in ReactJS or another modern Javascript framework Angular, VueJs

### Ideally
- You keep up to speed with latest technologies

### Responsibilities
- Develop new user-facing features
- Ensure the technical feasibility of UI/UX designs
- Work alongside with other engineers in teams to promote technology and ensure consistency in accordance with industry best practices.
- Self-driven individual to work independently, yet collaboration as a team member to reach a collective team goal.

### Why it would be awesome to work with us
- Yearly Awards for excellent employees
- 13th month salary
- 10 public holidays, 12 annual leave days based on Vietnam Government regulations
- Company sponsored activities such as sports, dining/drinking

### Contact
Homepage: https://eastplayers.io/
Email: hr@eastplayers.io
Phone: 070 313 2822

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
