### ISSUE TITLE
WTHApps - Senior Full-stack web developer - HCM - FT

### ISSUE THREAD

**Issue by thinhhuynh** [awesome-jobs/vietnam#270]
## Location

* Dreamplex Office Saigon, Vietnam
* Full time

## Salary Expectation

* $1500 - 1800 /month

## What will you do
Senior full-stack Developer will work with members of the development team.  You will join whole phases of software development process such as make requirement, design, development, implementation code review, testing and deployment. 

### Professional Responsibilities:

To be the member of Vietnamese/Canadian start-up company aiming to become one of leading Company in Global SaaS consumer software and services.
We are looking for the passionate and creative programmer who could help us make cool product. We need you to help us to wow people in the industry.
Your task is to develop new programs/products/applications that do not currently exist.  You will work with our talented software team and use your creativity as well as your technical skills to make amazing products.

### Excellent Skill in: 
* Web API technologies: RESTful, Authentication, Authorization, and multi devices session 
* Database: PostgreSQL or MySQL or MS SQL Server and/or NoSQL (MongoDB, Redis ,etc.)

### Decent skills in: 
*      Ruby on Rails
*	.NET desktop apps e.g. Add-ins, WPF and or Universal
*	HTML5, CSS
*	AWS (EC2, S3, etc.)
*	Source code control: Bit bucket or GitHub

### Good to have:
*	Object C or Swift and/or Java to make iOS and/or Android apps
*	AngularJS
*	Real-time technologies (cross platform and cross devices)
*	Kanban or Scrum process

### Experience with: 
*	Online services solutions for end users
*	Online payments setup (Braintree or similar)
*	E-fax service creation (integrate 3rd party code into our apps)
*	DNS service creation (integrate 3rd party code into our apps)

### Experience with (or can pick up skills):
*	Backend for social media site 
*	Evernote type programs – develop
*	Add-ons for software like: Outlook, Excel, Word, Photoshop, Illustrator

## [Academic / Business] We need:
 *Graduated from university or college.
*Good command of English 
*(Office communications are in English as CEO is from Canada)
*Responsible for high quality and productive work
*Ability to work independently and with a team

## [Personality/Personal Skill] We Need: 
* Creative and smart with good problem solving skills
* Good initiative
* Good people skills (we like nice people)
* Able to pick up other programming languages as needed
* Flexible to work on different projects at same time (multi-tasking)
* No BS! in working. 
* We want people who take pride in their work and will make the success of WTH a priority – we treat you well and you do amazing work! 

## Why you'll work with us:
* Opportunity to work in a professional environment with Canadian/international company
* Opportunity to work with top-level and high professional team to build cool Products for Global * Market
* Opportunity to show your Creative Skills
* Opportunity to work in a Challenging environment to improve your technical and soft skills 
English when working in WTHAPPS to improve your English Skill 
* Work in a Nice – Cool – and Open Office Space at DREAMPLEX.CO – DIST 1 
* Flexible vacation time 
* Working time: 8:30 AM – 5:30 PM 

jack: jack@wthapps.com

**Comment by joneslee85** [comment]
Thanks for posting with us, please remove the salary from the title as it does not comply with our guideline.

Additionally, please also ensure that all bullet points are correctly formatted, and replace all uppercased title with standardised lower-case header.

The contact section can be improved by placing under a section with dedicated header

**Comment by joneslee85** [comment]
Please revise the bullet points format, please see screenshot
<img width="580" alt="screen shot 2016-08-10 at 12 57 00 am" src="https://cloud.githubusercontent.com/assets/135605/17521121/777e26c6-5e95-11e6-8d91-8a605ccf29fe.png">

**Comment by joneslee85** [comment]
I am closing this job because I have not seen any amendment made to the bullet point since the last 2 days.
