### ISSUE TITLE
[Linagora Vietnam] Mobile Developer (Android, iOS, Flutter)

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2700]
## Location

* 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to 40m gross

## Requirements

* 2+ years' experience in mobile software development (Android, iOS, or Flutter).
* Familiarity with RESTful APIs to connect applications to back-end services.
* Knowledge of other web technologies and UI/UX standards.
* Understanding of State management approaches.
* Proficient understanding of code versioning tools.
* Familiarity with cloud message APIs and push notifications.
* Strong OO design and skills in Functional programming, Reactive programming.
* Good communication of English.

### Responsibilities

You’ll develop the mobile application of the OpenPaaS (https://open-paas.org/) platform
(mail, calendar application for fulfilling OpenPaaS Eco-system).
* a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices
* a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles
* a Subscription management application for the flagship software Twake Console
* a Mail application with the modern JMAP protocol

### Why it would be awesome to work with us

* Competitive salary (up to 40m gross), lunch allowance, 13th-month salary
* Work from everywhere, correct work-life balance.
* Work with highly skilled people for international projects.
* Modern working space
* Team retreats

### Contact

* Homepage: https://linagora.vn/
* If you are interested in the opportunity, please kindly send your CV in English to vnhr@linagora.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
