### ISSUE TITLE
[Linagora Vietnam] Java Developer - Fulltime - Hà Nội

### ISSUE THREAD

**Issue by linagora-vietnam** [awesome-jobs/vietnam#2701]
## Location

* 5 Dien Bien Phu, Ha Noi

## Salary Expectation

* Up to 40m gross

## Requirements

* Strong background in Java development
* Strong development processes: Agile (scrum), Git & code review, Continuous integration (Jenkins)
* Experience with at least some of the following technologies: NoSQL (Cassandra, ElasticSearch), messaging (RabbitMQ), object storage (Swift), load testing (Gatling)
* Curiosity towards new technologies
* Knowledge of mail protocols is a plus (SMTP, IMAP, JMAP)
* Good level of English

### Responsibilities

* Working with the team to set new milestones for our roadmap.
* Adding new features, and improve test automation to cover cloud operations.
* Implementing using modern big data technologies like Apache Cassandra, ElasticSearch, and RabbitMQ.
* Contributing a JMAP implementation, a new mail protocol standard that we participate to elaborate, disrupting the way client mail user applications are being written.

### Why it would be awesome to work with us

* Competitive salary (up to 40m gross), lunch allowance, 13th-month salary
* Work from everywhere, correct work-life balance.
* Work with highly skilled people for international projects.
* Modern working space.
* Team retreats.

### Contact

* Homepage: https://linagora.vn/
* If you are interested in the opportunity, please kindly send your CV in English to vnhr@linagora.com.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
