### ISSUE TITLE
Robert Bosch - Fresher Java/.NET - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by TrietCao178** [awesome-jobs/vietnam#2702]
## Location

* Ho Chi Minh City, Vietnam

## About Bosch

The Bosch Group is a leading global supplier of technology and services. In 2013, its roughly 281,000 associates generated sales of 46.4 billion Euros. Since the beginning of 2013, its operations have been divided into four business sectors: Automotive Technology, Industrial Technology, Consumer Goods, and Energy and Building Technology. 
The Bosch Group comprises Robert Bosch GmbH and its roughly 360 subsidiaries and regional companies in some 50 countries. If its sales and service partners are included, then Bosch is represented in roughly 150 countries. This worldwide development, manufacturing, and sales network is the foundation for further growth

RBVH - Robert Bosch Engineering and Business Solutions Vietnam Company Limited is 100% owned subsidiary of Robert Bosch GmbH. 
RBVH has started its operations from 19th October, 2010 at e-Town2 in HCMC. This engineering development center will be engaged in developing embedded systems and software, mechanical design and simulation, and will provide IT (SAP Consulting, JAVA Development….) and Business Services (Finance and accounting, Economics, Purchasing, Logistics, Translations Japanese-English-Japanese, Information Security ) solutions to the Bosch group of companies globally. 

## Salary Expectation

- 400$ - 600$/Month

## Requirements

- Last-year students, majored in IT, Computer Science or equivalent
- Good knowledge in Java or .Net
- Good knowledge in HTML/ Javascript/ CSS.  
- It's a plus to have knowledge in Angular/ ReactJS.
- Basic English communication skills

### Responsibilities

- Learning web application development framework and process
- Developing web application features under supervision of Senior Engineers
- Report the progress

### Why it would be awesome to work with us

- Committed 13-month bonus
- Collaboratively yearly performance bonus
- Meal & Parking allowances
- Premium insurance (PVI) for employee and 2 family members
- Overseas training programs and working onsite opportunity
- Good benefits of Trade Union activities, team building and company trip.
- Opportunity to work in global projects of fast developing company and being a part of innovation team
- Engage in our diverse training programs which surely help strengthen both your personal

### Contact
Homepage: https://www.bosch.com.vn
Email: triet.caohuynhminh@vn.bosch.com
LinkedIn: https://www.linkedin.com/in/trietcao

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
