### ISSUE TITLE
FETCH TECHNOLOGY - Senior Mobile (Android, IOS Native) - HCM - FT - Up to 4,000 USD 

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2705]
# HCM

# Up to 4,000 USD

## INTRODUCTION

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily on the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client:**

Joining one of Asia’s most exciting startups as part of the pioneer team in Vietnam! Our ride-hailing application is Asia’s 1st blockchain on-demand ride-booking service. This is the first zero-commission truck platform that connects thousands of logistics and trucking companies in Vietnam.

The successful candidate will be responsible for leading a development team, software design as well as coordinating with stakeholders.

## RESPONSIBILITIES

* Perform native mobile development tasks and work with back-end developers, designers to complete the features on time.
* Perform the unit tests, code review, and quality assurance.
* Perform mobile app deployment and maintenance 
## REQUIREMENT

* At least 5 years working experience in mobile app development, with at least 3 years of native app hands-on experience.
* Good understanding of SDLC and Agile methodologies.
* Good English communication.
* Considering the architecture of programs, not just only features.
* Proficiency in Swift or Kotlin programming languages.
* Autolayout experiences.
* Basic understanding of async network process & handling.
* Understanding & experience in MVVM Architecture.
* Experience in releasing a mobile app to store.
* Able to manage APNS, FCM related jobs per different apps.
* Preferable if having experience with SAAS.
## WHY YOU‘LL LOVE WORKING HERE
Being a Senior Mobile Developer (Android, IOS Native) at Fetch Technology, you will experience a youthful, flexible and creative work environment: 

* Opportunities to be part of the pioneer team of a fast-growing start-up making an impact on the mobility landscape in Vietnam.
* A platform to develop your career through working closely with senior executives and managers in the organization.
* A fulfilling role with lots of learning opportunities in a fun and highly motivating working environment.
* Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
* With extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* Attractive salary, 13th-month bonus and other benefits.
* Premium Health Care.
* Opportunity to be part of the pioneer team of a fast-growing start-up making an impact on the mobility landscape in Vietnam.
* A platform to develop your career through working closely with senior executives and managers in the organization.
* A fulfilling role with lots of learning opportunities in a fun and highly motivating working environment.
* Enjoy diversified activities: Free snack, Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 
## WORKING HOURS & LOCATION

* Working hours: From 9 AM - 6 PM, Monday to Friday.
* Location: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC.

## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com
* Linkedin: https://www.linkedin.com/in/thu-trang-jesse/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
