### ISSUE TITLE
HCM - Senior React Native DeveloperActive - FT - Remote

### ISSUE THREAD

**Issue by Gin19** [awesome-jobs/vietnam#2706]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $2,000 - 3,000/mothly

## Requirements
- 5+ years experience React Native developer, ideally with hands-on iOS Native coding.
- Strong in algorithms and passionate about learning deep technical expertise.
- Good reading & writing English communication skills.
- Agile and flexible start-up mindset.
- Having open-source contributions on Github is an advantage.
- Having published your own app on the App Store / Play Store is an advantage.

## Skills

React Native × 5
IOS × 5

### You’ll be responsible for
 Be part of the Core Development team, responsible for development of all mobile-related work.
- Take part in designing the architecture of core Mobile apps.
- Establish a team working process and follow good practices in Agile Development.
- Help to hire and train up other team members.
- Learn new technologies, share with team members, and proactively apply new technologies to the development process.
- Reach out to the open source community to encourage and help implement mission-critical software fixes—React Native moves fast and often breaks things.
- Maintain code and write automated tests.

### Why it would be awesome to work with us

Benefit
- Any potential VN full-time candidate should go through a 3-month Contractor Agreement with EST via Deel first. Employees will receive salary directly in a VN Bank account.
- Remote work for now (until Covid situation improves).
- Then move to a Co-working space office, potentially in Sala, D2 or D1.

Working hour
- Follow VN working hours and VN Holidays.
- Daily meeting with the CTO / Team via Zoom (until Covid situation changes).
- Weekly meeting with a larger team via Zoom.
- Occasionally meeting with Management team and Design team around 10-11pm VN Time.
###Report to
CTO
 interview
Round 1: Technical Interview -> Round 2: CTO -> Round 3: optional (với CTO hoặc CEO).
Note: 
Only open for candidates located and living in HCM city only

### Contact
Skype: Huehuenoivu

**Comment by Gin19** [comment]
Zalo: 088 600 5769

**Comment by tieuvu9x** [comment]
Remote luôn hay phải làm office vậy bạn?
