### ISSUE TITLE
[BASEBS.COM] - [JUNIOR .NET DEVELOPER] - [Hồ Chí Minh] - [Fulltime]

### ISSUE THREAD

**Issue by vynt2007** [awesome-jobs/vietnam#2708]
## Địa điểm làm việc
REE Tower, quận 4, Hồ Chí Minh 

## Mức Lương
Từ 10,000,000 Gross đến 20,000,000 Gross

## Mô Tả Công Việc

- Triển khai tích hợp phần mềm
- Phân tích và cung cấp các giải pháp kỹ thuật cho các dự án được giao.
- Phân tích, đưa ra đề xuất cải tiến liên tục cho sản phẩm.
- Nghiên cứu và tối ưu hóa sản phẩm.
- Công việc chi tiết sẽ được trao đổi qua buổi phỏng vấn. 

### Yêu Cầu Công Việc

- Ít nhất 02 năm kinh nghiệm về phát triển phần mềm trên các công nghệ .Net, Asp.Net, MS SQL.
- Có hiểu biết tốt về các nền tảng API như Web API/ RESTful API, Web Service, ...
- Có kĩ năng đánh giá/phân tích yêu cầu
- Có tác phong nhanh nhẹn, chững chạc, giao tiếp tốt và chấp nhận onsite/ công tác theo yêu cầu công việc.

### Phúc Lợi

- Thời gian làm việc: 08h00-17h00 (từ thứ 2- thứ 6) 
- Phúc lợi: chế độ lương hấp dẫn,chế độ phúc lợi khác theo Luật lao động và chính sách của công ty.
- Được tham gia đầy đủ BHXH theo quy định nhà nước và gói bảo hiểm sức khỏe cho nhân viên.
- Cấp Laptop làm việc.
- Cơm trưa tại văn phòng.
- Du lịch hàng năm, các hoạt động nội bộ mỗi tháng.
- Môi trường làm việc năng động, Đồng nghiệp thân thiện gắn kết

### Contact
Email: vynt@basebs.com
Skype: vyngo2007
Website: www.basebs.com

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
