### ISSUE TITLE
SCS Solutions - Technical Architect (.NET) - HCM - FT 

### ISSUE THREAD

**Issue by hatran171** [awesome-jobs/vietnam#2709]
## Location

* Saigon, Vietnam

## Salary Expectation

* $3000/month or range

## Requirements

* 7+ years of experience in analysis, design, and development of .NET software solutions.
* Strong experienced in Microservices 
* Strong understanding and experience of common software design patterns.
* In-depth development experience with clean code, coding standards, and code review.
* In-depth development experience with unit tests, mocking libraries, code coverage, and code refactoring.
* In-depth development experience with .NET ecosphere: ASP.NET, ASP.NET MVC, WCF, WebAPI, Entity Framework, .NET Code, and ASP.NET Core.
* In-depth development experience with any kind of database platforms such as Oracle, MSSQL, Graph Database, or MySQL.
* In-depth development experience with REST, SOAP, XML technology.
* Able to advise project teams on the use of static code analysis tools and configure the tools.
* Able to provide technical leadership in complex projects
* Fluent in spoken and written English.o Able to adjust your working time according to the project schedule

### Must Have

* Microservice
* In-depth development experience with .NET ecosphere: ASP.NET, ASP.NET MVC, WCF, WebAPI, Entity Framework, .NET Code, and ASP.NET Core.

### Responsibilities

* Participate in analyzing requirements, design architecture, implementation, code review, unit test, test, and deployment process.
* Technical Adviser for the Product of SCS Solutions
* Discuss and propose solutions for team and monitor progress.
* Review source code and coach colleagues to follow coding standards, design patterns and implement tests
* Research technologies and make workshops

### Interesting engineering projects
* Product Company from U.S
* Focus on U.S Market
* Domain: Logistic, Supply Chain 

### Contact
Homepage: https://scssolutions.io/
Mail: recruitment@scssolutions.io
Skype: ttp.ha985

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
