### ISSUE TITLE
Apide Vietnam - PHP/Laravel FullStack Developer with eCommerce touch - Saigon - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#271]
## A 100% foreign owned company

You are passionate about software development and doing it the right way? Awesome so are we, our customers deserve the best they can get!

You embrace changes and see it as a necessity in order to make great software? Yup so do we, and we love the agile approach!

Join Apide Vietnam as we set out on our mission to become the best software development company in Việt Nam!
## Location
- Saigon, Vietnam
## Salary Expectation
- $1200
## Requirements
- Work on modern and innovative projects from startups

**Have fun with**
- PHP/Laravel
- Magento
- SpreeCommerce (RoR)
- Payment integrations
- Front-Ends for eCommerce
## Skills
- Mid level in PHP with knowledge of Laravel and if possible Magento
- A sensibility to Ruby On Rails (no need to be an expert) 
- Good skills on Front-end Javascript and SCSS frameworks (Foundation or Bootstrap) 
- A touch of experience with Magento and/or Spree Commerce
### Why you love working here
- Work in an amazing start-up company in Vietnam with very open and friendly working environment
- To be a proactive individual in a company with a flat transparent structure, where everyone's opinion is valued
- Develop "sense of ownership" of product company in an Out-sourcing company
### Contact
- Ms Mai Ngo - HR Recruiter: 01243 894 915
- Skype: mai.ngo91
- Email: mai@apide.vn

**Comment by tucq88** [comment]
Hell yeah, A very good PHP job. Thanks for posting. #phpstrongagain ✌️

**Comment by RecruiterMaiNgo** [comment]
@tucq88 Could you please add labels for it? Thanks so much!

**Comment by joneslee85** [comment]
@RecruiterMaiNgo let me, it seems to me this is a migration job from Spree to Magento. Challenging I guess.

**Comment by RecruiterMaiNgo** [comment]
@joneslee85 Thanks! Hope it will be attractive enough to good candidates :smile:
