### ISSUE TITLE
Star Global - Lead Java Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2710]
## Location

* Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* It will match with your expectation and your expertise

### Must Have

- 5+ years of Java development experience.
- 2+ years of Team Leading experience.
- Proven experience in designing architecture as well as building and deploying scalable solutions using AWS cloud platform.
- Expert knowledge in designing RESTful API contracts.
- Strong knowledge of Java 8+ and Spring (Boot, Cloud, Data, Security).
- Hands-on experience with RDBMS (Postgres) and NoSQL (MongoDB, Redis).
- Knowledge of design principles, patterns and best practices such as Service Registration and Discovery, Load Balancing, Caching, Observability, Resiliency and Redundancy.
- Advanced level of English and the ability to communicate with a client directly.

### Ideally

- Understanding of microservices architecture and practical experience building microservices within a cloud platform.
- Experience with event-driven architectures and messaging systems (Kafka, Amazon SQS).
- Experience with ElasticSearch
- Passion for various engineering practices and proper process setup
- Experience with Docker and CI/CD

### Responsibilities

You will have a chance to be responsible for the architecture decisions and you will help shape the final product vision - and corresponding technical solutions - in close collaboration with the client. This includes leading the team, multiple workshops and brainstorming sessions. There are multiple interesting challenges along the way including Microservices engagement, managing and maintaining a lot of integrations with external service providers.

### You’ll be responsible for

- Work closely with the client to design the architecture of the cloud platform and its core components.
- Provide technical leadership and guidance to the development team to ensure that platform services are built according to defined contracts.
- Develop server-side components and integrations with external systems.
- Define non-functional requirements for scalability, throughput, response time and ensure proper implementation.
- Conduct architecture meetings, assist the development team in presenting technical solutions and accelerate their implementation.
- Maintain technical excellence backlog and facilitate the process of decreasing the amount of technical debt on the project
- Adapt existing methods and procedures to create alternative solutions to moderately complex problems.
- Use own judgment to determine the optimal solution to recommend.
- Determine methods and procedures on new assignments with minimal guidance.
- Manage medium-small-sized teams and/or work efforts.

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ Latest MacBook Pro & monitor or you can Bring your own Device, we'll compensate you monthly!
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/lead-java-engineer-999756/
Recruiter: quyenphan@star.global (Skype: pmq0406)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
