### ISSUE TITLE
HN - DFY - Front End Lead - Up to $3,000 & token bonus 

### ISSUE THREAD

**Issue by Lynn2606** [awesome-jobs/vietnam#2711]
## Location

* Cau Giay, Hanoi, Vietnam

## Salary Expectation

* $1500 - $3,000

## Requirements
* 5+ years of overall software development experience, with an emphasis on web applications and front-end technologies
* Proficient in Frontend frameworks/ libraries like Vue.js, or Angular
* Proficient understanding of code versioning tools (Git is preferred)
* In-depth understanding of in HTML/CSS, Javascript
* A strong fundamental understanding of software development
* Good sense of teamwork and responsibility
* Have good knowledge and experience with Agile/SCRUM development method
* Experience with Blockchain projects is big plus.

### You’ll be responsible for

* Develop web applications using Vue.js 
* Analyze, review, feedback for product requirements and designs
* Build reusable components for future use
* Optimize application performance and develop new feature
* Participate in coding and reviewing code of other members
* Collaborate with back-end developers and web designers to improve usability.

### Why it would be awesome to work with us
* Attractive salary and package, from $1500 - $3,000
* Working time: 8:30-18:00 (off 1.5h from 12h to 13h30 for lunch) from Monday to Friday
* Flat and hierarchy structure
* Annual salary review
* Self-management is appreciated
* Friendly, innovative, and supportive environment
* Interesting projects
* 13th month salary, annual health-check, insurance under Vietnamese Labor Law, monthly teambuilding
* Psychological safety; Your ideas are always welcomed.
* Token bonus 

### Contact
If you are always willing to learn, if you like challenges, if you want to get an attractive package and be a part of exciting projects, don’t hesitate to send your CV to: linhdd@blockchaindeveloper.asia

To understand more about us: https://defiforyou.uk/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
