### ISSUE TITLE
[JobSeekervn - Saigon] Senior NodeJS Developer - $1800 - $2500

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2712]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1800/$2500/month 

## Requirements
* 4 years experience backend development for in web or mobile application
* Strong technical skills: NodeJS, Typescript, SQL database (preferably PostgreSQL)
* Experiences in NodeJS frameworks: NestJS, TypeORM is a big plus
* Experiences in GraphQL is a big plus
* Experiences in ReactJS or React Native (or willing to learn) is a big plus
* English speaking 

### Responsibilities
* Work closely with other cross-functional teams to define, design and deliver new features with high quality and responsiveness for a mobile-first application
* Participate in technical solution proposal and estimation for features to be delivered
* Participate in code review, promote best practices and coding guidelines to ensure code quality and maintainability
* Maintain, troubleshoot and fix issues in a timely manner based on the severity
* Bouncing ideas with other engineers to boost the development experience, speed and quality
* Promote team-player culture, assist other engineers to overcome technical obstacles

### Why it would be awesome to work with us
* Traffic allowance 
* Laptop provided, external monitor to work
* 20 days for annual leaves
* Private Health Insurance
* 13th-month bonus salary

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi
Website: nhiha.top

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
