### ISSUE TITLE
[Groove Technology] Senior Fullstack .NET Developer - HCM 

### ISSUE THREAD

**Issue by QuynhNguyen14** [awesome-jobs/vietnam#2714]
## HCM 

* Saigon, Vietnam
* Fulltime 

## Salary Expectation

* Discussion 

## Requirements

- 3+ years working as an Engineer delivering projects using the Microsoft stack.
- Experience creating, maintaining, optimising and writing queries for MS SQL.
- Experience using an ORM library such as Entity Framework or nHibernate.
- Experience using various dependency injection frameworks such as Ninject, Autofac, Unity, Spring etc.
- Experience building and integrating with RESTful web services built using WebApi.
- Client side experience using Javascript and Javascript libraries.
- Experience with source control systems such as SVN or GIT.

### The following is considered highly advantageous:

- Experience with a message broker/message bus framework such as RabbitMQ, nServiceBus or similar.
- Experience with Angular.js, React.JS, or similar on the client-side.
- Experience with bootstrap or similar CSS frameworks.
- Exposure to any kind of NoSql database technologies.
- Experience integrating with 3rd party systems.
- Logistics experience.

### Why you’ll love working here?

- 13th month salary and 14 annual leave.
- Medical and Accident Insurance program.
- International, dynamic, friendly working environment.
- Clear and stable career growth.
- Many opportunities for personal and professional development.
- Professional training.
- Company trip and regular team building events, sports activities…

### Contact
Skype: nhuquynh1495@outlook.com
Email: quynh.nguyen@groovetechnology.com 
Linkedin: https://www.linkedin.com/in/quynhnguyen14/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
