### ISSUE TITLE
Lixibox - Staff Software Engineer(Backend) - Saigon - FT

### ISSUE THREAD

**Issue by rofiuddin** [awesome-jobs/vietnam#2719]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,700 - $2,500/month (Negotiable)

## Requirements

* At least 5 years experience in an IT company with relevant large-scale backend system
* Excellent software engineering skills, with fully vetted development cycle such as understanding the requirements, design, implementation, testing and deployment
* Excellent coding and problem solving skills with mentality to tackle challenging tasks
* Be able to work independently in a fast-pace environment focusing on deliverables
* Experiences with Ruby on Rails framework are strongly preferred, but experiences with similar backend framework such as NodeJS/Python/Golang are acceptable
* Prove yourself to be a fast learner, willing to learn new languages/tooling/frameworks
* Experience CI/CD and cloud platform deployment such as AWS/Google Cloud are strongly preferred
* Good knowledge about software testing, automation testing (Rspec, Capybara, JUnit, GoTest) is a big bonus
* Experience working with JS/HTML/CSS/ReactJS is a bonus
* Experience working with mobile responsive layout
* Experience working with the Git version control system is a must
* Basic ability to communicate in English is a must

## Responsibilities
As a senior member of the engineering team, you are expected to:

* Fully understand the business of building an e-commerce platform from both operational and technological standpoints
* Deeply involve in the design and development of Lixibox.com backend system
* Be able to improve the system to achieve scalability, high performance and security
* Work with other team members to build new systems that serve the operational needs as well as expanding the company to new sectors
* Mentor junior members to ramp up and raise the team's quality
* Have fun and grow yourself to the next level

### Why it would be awesome to work with us

* Join one of the best tech teams in Vietnam (Seriously!)
* Attractive annual raise/bonus (subject to performance achievement)
* Top-of-the-line equipment to perform your work: Laptop (MacBook or PC) and large screen monitors
* Private PVI Healthcare Insurance
* Employee discount upon buying on Lixibox.com
* Daily fresh lunch and yoga class at office
* Opportunities to go on business trips to US, Japan, China and attend international seminars to meet the world's top engineers
* 12-day annual leave per year.
* Play Sport: Badminton, yoga
* Flexible work from home policy

### Contact
✉️ career@lixibox.com  
📞 (028) 3636 7489
🌐 https://careers.lixibox.com/jobs

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
