### ISSUE TITLE
Subiz Vietnam - Fulltime AngularJS/ReactJS Developer - HN

### ISSUE THREAD

**Issue by Vietnambiz** [awesome-jobs/vietnam#272]
## Location
- Hanoi, Vietnam
## Salary Expectation
- $800-$1200/month or negotiable
## Requirements
- 2+ years JavaScript, ReactJS/AngularJS experience
- Having experience with NodeJS, Golang, Docker is a plus
## You’ll be responsible for
- Turning all the complex ideas into simple and easy-to-use product for users
- Designing and creating some important parts of UI
- Evaluating and optimizing to increase performance
- Implementing auto test
## Why You'll Love Working Here

Subiz is a tech startup which provides communication tool for businesses all over the world. We are a team of young, dynamic and creative people who always work with love and fun.
## Contact
- Ms.Nhung - Recruiter: 0972.433.805
- Email: work@subiz.com (Subject: [SUBIZ] Position - Full name)

**Comment by joneslee85** [comment]
Thanks for the posting. Can you please revise the job title? Because it is missing the job type (in your case I believe it is full time)

Furthermore, please search replace `Reactjs` with `ReactJS` / `Angular.js` with `AngularJS`.

**Comment by Vietnambiz** [comment]
@joneslee85 I've revised my post and made some adjustments. Plz kindly check it again. Thanks alot!
