### ISSUE TITLE
Manabie Vietnam - Senior Backend Engineer - HCMC - FT #1846

### ISSUE THREAD

**Issue by duytran1993** [awesome-jobs/vietnam#2722]
## Location

* (Copac Square Building) 12 Ton Dan, 13th Ward, District 4, HCMC

## Salary Expectation

* $3500/month Gross

## Requirements
* Golang (or any Backend development languages) 
* gRPC
* TDD (Test Driven Development) - No Test, No Merge!
* Algorithms and Data Structure

### Must Have

* SQL (PostgreSQL)
* System Design

### Ideally

* Experience with gRPC
* Experience with AWS

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Implement & maintain Microservices with Golang.
* Work closely with our product managers to understand feature specifications
* Communicate with QA engineers to design and understand technical specs
* Proactively give feedback and ask questions to contribute to product specifications’ improvement
* Work closely with mobile & frontend engineers for API design & integration 
* Make a thing work first before make it better
* Test driven development with unit and integration tests (no test, no merge culture) 

### You can bring

* A scaleable and stable system.

### Why it would be awesome to work with us

* A strong and friendly team, who will support you when needed, and troll you when bored.
* A culture that encourage you to speak your mind and take ownership to the product that you made.
* A place where you can bring your Business sense and awareness to a whole new level through transparency and candidacy.

### Interesting engineering projects

* If whole Education ecosystem, with lots of interesting feature is not enough for you, lots of internal tools are waiting.

### Contact
Homepage: https://manabie.breezy.hr/
Email: dylan.tran@manabie.com / tabp@manabie.com
Tel: 0915 342 782
Skype: ducduy1293

![Add a heading (3)](https://user-images.githubusercontent.com/35828838/127246896-e81ee833-ced9-439e-9ed1-3bb419cc1298.gif)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
