### ISSUE TITLE
Backend Engineer - Rust

### ISSUE THREAD

**Issue by daywednes** [awesome-jobs/vietnam#2724]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $1000 to $5000

## Job Description
* We are looking for a backend developer to join our team.
* You will be joining a small and awesome startup team to build an economic incentive blockchain infrastructure to make web3 apps fully decentralized.
* You will be working with other team members, who are ex-googlers, PhD(s) to design highly available and scalable systems in a fast-paced development environment.

## Requirements
* 2+ years of experience, smart and get things done, able to learn new technologies quickly.
* Experience with Rust and devops is a big plus.
* Blockchain interest and experience is a plus.
* Solidity experience is another big plus.

## Skills
 * Rust
 * Python or Golang
 * Devops
 * Github Actions

### Ideally

* Experience with Rust

### Why it would be awesome to work with us
* Negotiable salary, depending on your skills and experience
* Earn monthly tokens/equity which could be 10x appreciated
* No worries about the job stability as the startup is well-funded.
* Free Lunch offered.
* Gym,  beautiful swimming pools, park for jogging available as our office is located at Vinhomes Central Park.
* Growth opportunity by learning and working with ex-googlers and Silicon Valley entrepreneurs.
* Flexible environment provided as long as you can get the job done in the right way.
* Become one of the first core members of the team.
* Bonus + 13th month salary option available.

### Interesting engineering projects
* Ambitious NFT + metaverse project
* Infrastructure for blockchains
* Cross-chain DEFI

### Contact
Homepage: https://github.com/massbitprotocol/
Contact: mikedoan82@gmail.com or https://www.linkedin.com/in/daywednes

#Rust, #Devops, #Python

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by daywednes** [comment]
Hello, I'm. the founder of MassBit protocol and I have created another issue - instead of specifying my email I'm using massbit.io email this time together with the Google form. Thank you.

**Comment by daywednes** [comment]
@lactroi Thank you for your feedack. May you please help to tag our new issues?

https://github.com/awesome-jobs/vietnam/issues/2725
https://github.com/awesome-jobs/vietnam/issues/2726

**Comment by qcam** [comment]
@daywednes Thanks for fixing them. Please follow the guide at https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post then the posts will be tagged accordingly. Thank you.

**Comment by daywednes** [comment]
@qcam @lactroi I have followed the guide. Please help tag #2725
