### ISSUE TITLE
Codelight - Backend Engineer (Rust) - SaiGon - FT

### ISSUE THREAD

**Issue by daywednes** [awesome-jobs/vietnam#2725]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $1000 to $5000

## Job Description
* We are looking for a backend developer to join our team.
* You will be joining a small and awesome startup team to build an economic incentive blockchain infrastructure to make web3 apps fully decentralized.
* You will be working with other team members, who are ex-googlers, PhD(s) to design highly available and scalable systems in a fast-paced development environment.

## Requirements
* 2+ years of experience, smart and get things done, able to learn new technologies quickly.
* Experience with Rust and devops is a big plus.
* Blockchain interest and experience is a plus.
* Solidity experience is another big plus.

### Must Have
* 2+ years of experience, smart and get things done, able to learn new technologies quickly.
* Rust, Python
* Github Action
* Devops

### Ideally
* Rust, Golang, Python, Github Actions, Devops

### Responsibilities
* Take ownership of different backend-end projects.
* Be able to learn new technologies quickly

### Ideally

* Experience with Rust

### Why it would be awesome to work with us
* Negotiable salary, depending on your skills and experience
* Earn monthly tokens/equity which could be 10x appreciated
* No worries about the job stability as the startup is well-funded.
* Free Lunch offered.
* Gym,  beautiful swimming pools, park for jogging available as our office is located at Vinhomes Central Park.
* Growth opportunity by learning and working with ex-googlers and Silicon Valley entrepreneurs.
* Flexible environment provided as long as you can get the job done in the right way.
* Become one of the first core members of the team.
* Bonus + 13th month salary option available.

### Interesting engineering projects
* Ambitious NFT + metaverse project
* Infrastructure for blockchains
* Cross-chain DEFI

### Contact
Homepage: https://github.com/massbitprotocol/
Contact: mikedoan82@gmail.com or  https://forms.gle/5YJF3JyNS8mYrZkk9

**Comment by rajukc530** [comment]
@daywednes - any jobs related to java for remote .

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
