### ISSUE TITLE
[HN] DevOps Engineer - Mirabo JSC #

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2727]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $700 - $1200/month 

## Requirements

* Have at least 1+ years Software Engineering experience
* Have knowledge about: Docker, K8s, Ansible...
* Database Mysql, PostgreSQL, MongoDB,...
* Language: NodeJs, Java, Python,...
* CI/CD experience (Gitlab, Jenkins,...)

### Ideally

* Experience with DevOps

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Create environment for production, staging, testing, dev for products including web, app, streaming system, VR/AR application.
* Design system for project in Japan

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Homepage: https://mirabo.com.vn/
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
