### ISSUE TITLE
[HN] NodeJS Developer - Fulltime 

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2728]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $600 - $1200/month 

## Requirements
* Have at least 1+ years experience
* Have knowledge about: SOCKET.IO, WEBRTC...
* Have knowledge about: Restful APIs 
* Database Mysql, PostgreSQL, MongoDB,...
* CSDL: MySQL, Postgres...

### Ideally

* Experience with NodeJS Dev

### Responsibilities

Great power comes with great responsibilities!

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.
### Contact
Homepage: https://mirabo.com.vn/
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
