### ISSUE TITLE
Remote Ruby on Rails Engineers from 3 YOE - iRuuza is expanding 

### ISSUE THREAD

**Issue by jitera-inc** [awesome-jobs/vietnam#2729]
_2 interview needed_
Monthly salary: **$3000 - $4500**
**About Us**
We are no code start-up and incubator of a lot of web services. Our business is:
- Create a code automation platform. *not open now. using only inside the company
- Create web service (client work) using code automation tool by us.

**About This Job**
Help our clients to build software (web, ios, android) with our code generator. So you would do :
- Our client work ***ex**: create a dating app, saas platform...etc
- Create a source code generator and automate coding!!

**Requirements**
**Duties and Responsibilities:**

- RoR skills (at least **2-3 years**) 
- Have knowledge about MVC, service, decorator, serializer, or any other architecture
- Well know about the database (MySQL, PostgreSQL...etc)
- Restful Architecture
- Unit testing
- React skills (at least **1-2 years**) 
- Good knowledge of redux, component life cycle, react hook
- Good at front-end development. implement with good design will be needed to **don't need to create a design with Figma or adobe xd or sketch... etc*. But need to**implement these design tools.** 

**Hope to know about**

- Infrastructure and DevOps
- Infrastructure as a code
- AWS, GCP, Azure...
- Deep knowledge about computer science
- Experience of No code or OSS contribution

**You will be a great fit if you:**

- Have responsibility
- Have the passion to remove unnecessary coding and create innovation
- Have honesty and a good heart

**Benefits **
- Full remote and you can work from all over the world
- At least you need to attend video calls without delay and work on a stable internet. We may ask to meet in **JST** but we can make arrangements for meeting schedule.
- We'll provide some benefits if you'll work as a full-time regular employee.   
- Tax (maximum 10% of salary)
- Premium insurance
- 20 Annual Leaves
- MacBook Pro M1 provided
Contact: 
Mail: **recruitment@iruuza.com**
Telegram/WhatsApps/Line/Viber: +84 38122719

**Comment by jitera-inc** [comment]
if you are curious about this position in details, feel free drop you cmt, I will contact you

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
