### ISSUE TITLE
CodeBox Solutions - DevOps Engineer - HCMC - FT

### ISSUE THREAD

**Issue by lntan** [awesome-jobs/vietnam#273]
## Location

HCMC, Vietnam. Not recruit the remote candidates.

## Salary Expectation

Commensurate with experience

## The Job

We are looking for a DevOps Engineer with a passion for learning new technologies and a strong interest in infrastructure automation and continuous deployment. 
- Must be familiar with the software development cycle and have a strong understanding of security best practices. 
- Must be comfortable being involved in the full application stack from infrastructure automation to database optimization and code contributions. 
- Will need to work closely with developers to optimize workflow and solve issues.

### Must Have

- Linux 
- networking
- security
- scripting
- git
- AWS
- SSL

### Nice to have

- docker/vagrant
- chef/puppet/capistrano
- jenkins
- nginx
- unicorn

## Other Requirements

- Able to communicate smoothly in English
- Able to work independently
- Problem solving skills

## Contact

CodeBox Solutions Recruitment: hr@codebox.vn or FB https://www.facebook.com/codebox.vn
Company information: http://codebox.vn/

## About Our Company

CodeBox Solutions Ltd. is an international software development company based in Vietnam – HCMC with its branch in the United State - California.

We are a group of very selected people who share the same passion and enthusiasm on developing software that speak the language of the end user. Specializing in Ruby (our favorite), .NET, and mobile programming languages, we have been delivering high value products and professional services to our clients across 5 countries. 

At CodeBox, we also have innovative, business-driven quality assurance and independent testing services.

We are growing quickly and believe in creating a culture of openness where the relationship between the manager and staff is always honest and respectful. This ensures the growth of both our team and individuals. 

We always welcome talented and enthusiastic software engineers to join us!

### Why Work With Us

- Be your own manager. We only manage the quality 
- Want challenges and rewards? We have both for you 
- A very friendly environment where we grow together
- Opportunity to work abroad with Project Owner in the US or AUS
- An optimizied management system that helps you feel comfortable at work
- 13th salary and attractive project bonus
- Support purchase laptop (50% of the value)
- Work-from-homework policy
- Compliance fully to Vietnam labor code
- Company trip, teambuilding
- Birthday celebration
- Extra healthcare package

**Comment by joneslee85** [comment]
Thanks for posting with us, please revise the bullet point format of `Your Skills and Experience` and `Other Requirements` sections because they are not `*`.

**Comment by lntan** [comment]
@joneslee85 updated
