### ISSUE TITLE
[HN] MIRABO JSC - IOS DEVELOPER

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2732]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 15.000.000 - 30.000.000/month

## Requirements
* Have at least 1+ years experience 

### Responsibilities

Working on outsourcing projects with Japanese customers

### Why it would be awesome to work with us

* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Homepage: https://mirabo.com.vn/
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
