### ISSUE TITLE
Trs Sea - Java Developer - Hanoi/Hochiminh - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2733]
## Location

* Ha Noi
* Ho Chi Minh

## Salary Expectation

* Up to 2000$/month

## Requirements
* 3+ Year experience in core JAVA, Spring framework, Hibernate
* Have knowledge about RESTful API development and API query language GraphQL
* Hands on exposure in Agular JS, npm, web based technologies HTML/CSS
* Good at English

### Must Have

* Java
* English communication. 

### Ideally

* Experience in fintech, bank, finance companies/projects.

### Responsibilities

* Designing implementing, and maintaining Java applications that are often highvolume and low-latency, required for mission-critical systems
* Delivering high availability and performance
* Contributing in all phases of the development lifecycle
* Writing well-designed, efficient, and testable code
* Conducting software analysis, programming, testing and debugging
* Managing Java and Java EE application development
* Ensuring designs comply with specifications
* Preparing and producing releases of software components
* Supporting continuous improvement
* Investing alternative and technologies

### Why it would be awesome to work with us
* Competitive salary and benefit package, with a clear and attractive promotion plan
suitable for individual.
* Young and dynamic foreign environment.
* Social & health insurance as regulated in the law,
* Quarterly/yearly sales bonus + 13th month salary.
* Training courses and team building activities
### Interesting engineering projects
* Work with banks and finance company. 
* Develop different projects in e-payment, debt checking, POS etc 
### Contact
Email: diepnguyen@r-starsea.com 
Phone Number: 0374118602

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
