### ISSUE TITLE
[Chợ Tốt] Front-End Engineer

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#2734]
Are you a Front End Software Engineer who finds building great UI simply irresistible? If yes, this role is for you!

We’re looking for dynamic talents to join us on a mission to continue building smart marketplaces in Vietnam.

**What will you be doing?**
Be a valued member of an autonomous, cross-functional agile team
Implement and be responsible for end-to-end product features on Web platform
Develop UI components using React.js and implement high performance universal web applications
Proactively contribute to the improvement of delivery as well as engineering processes

**What do you need for the role?**
Minimum 1 year experience with Front-end/Web development
Proficiency in SEO-friendly HTML and mobile-first CSS
Proficiency in modern JavaScript (ES6+) and ES modules
Experienced in one or more data-rich SPA projects that utilize React.js
Experienced in debugging and optimize web apps
Passion for building great UI/UX mobile-first design
Familiarity with Git version control tool and Gitflow
Degree in Computer Science, Information Technology or equivalent
Would be great if you are also:

Experienced in Next.js framework and universal JS applications
Experienced in one of CSS preprocessors and/or CSS-inJS solutions
Familiar with Web page optimization and Web Vitals toolings
Experienced in server side Node.js
Familiar with Docker and container
Experienced in scrum and agile process

**What’s in it for you?**
Join plenty of Sharing and Learning activities as part of our initiative to contribute to the tech community in Vietnam
Get 15 days of annual leave and 5 days of sick leave per year
Get a Macbook Pro as your workstation
Get 13th months salary and annual performance-bonus
Participate in regular team building activities and company parties
Get opportunities to attend training courses abroad
Most importantly, the code you write will be impacting the lives of millions!

### Feel free to get in touch via anhhoang@chotot.vn or Skype: tremlobisi94

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
