### ISSUE TITLE
KMS Technology - Senior Test Engineer - Da Nang - FT - WFH during COVID-19

### ISSUE THREAD

**Issue by Quynhtn170299** [awesome-jobs/vietnam#2735]
## Location

* Da Nang, Vietnam

## Requirements
* Good knowledge of software development process, especially the software testing process, testing methodologies, and database skills are required
* Solid experience in creating and implementing test strategies and detailed test plans, test cases/scripts
* Strong experience in estimating test activities and delivery
* Able to understand, communicate, analyze requirements, and identify gaps in requirements
* Able to perform all kinds of testing effectively & independently 
* Able to participate in defining/tailoring software testing process which can jointly be applied for the QA team & client’s teams
* Good organizational, analytical and problem-solving skills, with the ability to think out of box
* Able to perform testing in a high-pressure environment with teams in local and distributed locations
* Positive attitude and be able to collaborate effectively across teams  
* Experience with testing web-based/ mobile applications/ Web service & healthcare domain is a plus
* Good knowledge and experience in automation tests is a plus

### Must have
* At least an intermediate skill level of English
* Likely having 3+ years of experience in software testing

### Responsibilities
* Understand domain knowledge & client testing process clearly to implement all testing activities independently and effectively
* Work directly with client on daily assignments and testing solutions
* Join daily/weekly meeting with client
* Review requirements, specifications and technical documents to provide timely and meaningful feedback
* Review requests, forecast team capacity & allocate resources accordingly
* Address technical issues and providing client with appropriate solutions 
* Work closely with project team and management team on:
* Estimate test effort accurately and coordinate with team members for work activities
* Create detailed, comprehensive and well-structured test plans and test cases
* Deliver products in high quality and on time
* Drive QA process and standards changes to optimize testing quality and team productivity  

### Benefits and Perks
* Working in one of the Best Places to Work in Vietnam
* Building large-scale & latest technology software products
* Working & growing with Passionate & Talented Team
* Attractive Salary and Benefits
* Performance appraisal twice a year
* Flexible working time
* Various training on hot-trend technologies, best practices, and soft skills
* Premium health care insurance for you and your loved ones
* Company trip in every summer, big annual year-end party every year, team building, etc.
* Joining community development activities: 1% Pledge, charity every quarter, blood donation, public seminars, career orientation talks,…
And much more, join us and let yourself explore other fantastic things

## Contact
Career page: https://careers.kms-technology.com/
LinkedIn: https://www.linkedin.com/in/p170299/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
