### ISSUE TITLE
DXC Technology Vietnam – Cobol Internship Program – Work from home – FT

### ISSUE THREAD

**Issue by ThamH7** [awesome-jobs/vietnam#2737]
## Location

* Work from home
* Saigon, Vietnam

## Salary Expectation

* 5,000,000 VND/month

## Requirements
* New graduated students from Universities who pursuing career Java Programmer Analyst/Developer
* Bachelor’s degree in Computer Science, Software Engineer, IT or equivalent
* English Level: Intermediate
* Full-time participation is required (Monday through Friday, 9:00AM – 6:00PM)
* Commit to working at DXC Vietnam for at least 2 years

### Responsibilities

You will be trained COBOL and Insurance programs on DXC Insurance platforms by our experts

### Why it would be awesome to work with us

After the training, you will be able to work as a Cobol Developer for Insurance projects at DXC where you can further advance your career

### Contact
Homepage: http://www.dxc.technology/vn_en
Email: thamhohong.huynh@dxc.com
<img width="502" alt="Cobol Intern" src="https://user-images.githubusercontent.com/87801518/126612628-dc050cb7-c7e9-4845-be87-8e79d84fc6e0.png">

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
