### ISSUE TITLE
Meteor + React, React-Native Developer - Remote work

### ISSUE THREAD

**Issue by jelenajjo** [awesome-jobs/vietnam#274]
## Location

* Remote

## Salary Expectation

* $1000-2000/month or negotiable

## Requirements
* Javascript

## Skills
* Meteorjs
* React-Native
* React

### Must Have

* Apps done with meteor/React-native

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Finishing Uber like app for web & mobile

### You can bring

* A good eyes for design

### Contact

Apply on https://goo.gl/forms/UJw2O8JsL7DXhPS92 

Jelena - stefan@vanila.io 

www.vanila.io

**Comment by hieuk09** [comment]
Could you add more information about the job as well as the company?

**Comment by jelenajjo** [comment]
Hi @hieuk09 

Job details will be announced to chosen developer.

About company, we are located in **Serbia**, but we are mostly **remote team**.

**Comment by hieuk09** [comment]
Since we want to keep the high quality of the job post here, the detail job description and company description is a must-have requirement for all job posts ([here](https://github.com/awesome-jobs/vietnam/issues/242) is a great example).

**Comment by jelenajjo** [comment]
Ok, I will fix it later, I am in the middle of work.

**Comment by hieuk09** [comment]
It's been a week without amendment. I close this post for now.
