### ISSUE TITLE
Fullstack JS Developer

### ISSUE THREAD

**Issue by tranle11** [awesome-jobs/vietnam#2740]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Range

* $1000-$1500

## Requirements
* Nodejs, Reactjs/Angular
* Experience in using javascript or Typescript, React Components and Redux, Node.
* 2+ years of production experience building and maintaining ReactJs/Nodejs web applications.

### Must Have

* Familiarity with broader web concepts (i.e. CORS, REST requests, web security.
* Knowledge of design patterns and best practices.
* Experience in HTML5 / CSS3 (Flexbox),MongoDB, Jquery and responsive design.
* Experience in Backbone, Docker, React, ExpressJS
* Firm grasp of the JavaScript (and TypeScript or ClojureScript) language, including ES6+ syntax.
* Knowledge of functional or object-oriented programming and its design principles.
* Understanding of REST APIs or GraphQL, the document request model, and offline storage.
* Ability to write well-documented, clean Javascript code.
* Rock solid at working with third-party dependencies and debugging dependency conflicts.

### Ideally

* Knowledge of AWS mobile services such as AWS AppSync, AWS Cognito User Pool, Push Notification.
* Be able to use AWS Amplify framework to build mobile applications.
* Having existing mobile apps on Apple App Store or Google Play is a plus.

### You’ll be responsible for

* Develop web applications using ReactJS, Nodejs.
* Work closely with the PM to provide ideas and solutions to the development of new features.
* Cooperate with UI Designer to implement modern minimalist designs into production.
* Integrate third-party API's.
* Stay motivated and up-to-date on the latest developments and trends in web / mobile design &
development.

### Why it would be awesome to work with us
As a start-up company, our team is our highest priority and we welcome new talent in our team. Along
with our young spirit, our aim is to create an ideal and open environment where each person is eager to
work and encouraged by the creative ability of every member of our team.

● We put human development as the first priority.
● We give you challenging and interesting work to develop your career path.
● Flexibility and authorizing culture in our company.
● Activities: Yearly company trips, Year-end Party, Teambuilding, Football Clubs.
● Training activities weekly: English, Management, Soft Skills, Technology.
● Career guidance and support daily from Manager, Leader and Senior Level.
● 13th payment, and extra bonus for excellent employees.
● Salary and promotion review: twice / year
● Promotion opportunities for Senior and Leader level.
● Bonus on Public holiday.
● Overtime is rarely required, you will get paid for the extra work.

### Contact
Email: tran.le@innomizetech.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
