### ISSUE TITLE
Trs Sea - Fullstack Java Developer - Hanoi - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2742]
## Location

* Minh Khai, Ha Noi

## Salary Expectation

* Up to $2500/month

## Requirements
* English: Basic Communication skills
* At least 3 years of professional experience, as a developer.
* Must be used to working with (and enjoy) Unit/Integration Test Automation, Scrum.
* Current technologies in use include Java Spring/.NET Web API, and Angular 2+.
* Proven skills in creating scalable and resilient software designs.
* Ability to follow established architectural guidelines for both design and implementation.
* Prefer experience with SCRUM / Jira, Confluence

### Must Have
* 3 years of professional experience, as a developer.
* Must be used to working with (and enjoy) Unit/Integration Test Automation, Scrum.
* Current technologies in use include Java Spring/.NET Web API, and Angular 2+.

### Responsibilities

The Java Developer will be responsible for, but not be limited to, the following:

* Becoming an active part of the team and embody the culture of the company.
* Participating in workshops with Product Owner and team to get best possible solu-tions.
* Development, including coding, testing, unit-testing and code reviewing.
* Troubleshooting system issues and analyze errors for root causes and propose solution.
* Deploying bug fixes and feature releases.

### Why it would be awesome to work with us
* Becoming an active part of the team and embody the culture of the company.
* Up to 14-month salary package
* 18 - 20 leaves per year (including at least 13 annual leaves, 5 personal leaves not including publics holidays and work from home).
* Personal medical benefit and family medical benefit (AON Insurance package).
* Have a chance to travel onsite in the company global office in Denmark, Dubai...
* Free meal, snacks, refreshment.
* Working in a global working environment
* Working time: 9:00 AM - 6:00 PM from Monday to Friday

### Contact
* Email: diepnguyen@r-starsea.com 
* Phone: Ms. Diep - 0374 118 602)
* LinkedIn: https://www.linkedin.com/in/nguyen-diep-64963b166/
* Skype: Diep Nguyen (diepnguyen.neuhn@gmail.com)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by XuanDiep55** [comment]
Oh no. I'm using my company email: ***@***.***
Maybe you see the personal email that I'm using for skype. Please check it
again for me.

Thank you so much.

Best regards,
Diep

Vào 16:20, T.6, 23 Th7, 2021 Lạc Trôi ***@***.***> đã viết:

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
