### ISSUE TITLE
[Cốc Cốc] Software Engineer, PHP (Laravel)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#2743]
We are looking for talented developers to join our prosperous Browser Backend team. With the mission to be a team which designs, develops and maintains backend products consisting of backend core systems, api services, web applications.
As a Browser Backend developer, besides developing and maintaining back-end services of Cốc Cốc products (such as browser, business intelligence, etc), you will also co-operate with other teams to design and develop new web applications.

* Saigon, Vietnam
* Remote in Covid pandemic
* Level: Senior & Middle

## RESPONSIBILITIES:

- Developing new and supporting old features for sales, platforms; search team, browser team and others;
- Searching and fixing/optimizing problems in developed products;
- Pro-actively enhance our products;
- Mentoring newcomers to grow as successful developers;
- Other tasks requested by Direct Manager.

## REQUIREMENTS:

**Must have:**

- 5+ years of PHP development experience
- Hands-on experience working with PHP frameworks Laravel, Slim
- Familiar with SOLID principles, design patterns, Domain Driven Design
- Experience working with container environment: docker, docker-compose, Kubernetes
- Experience working with Linux environment
- Experience with different databases. Relational (eg. PostgreSQL, MySQL) or NoSQL (eg. MongoDB, …)

**Plus:**

- Experience in leading a small team is a plus
- Experience working with queue system (RabbitMQ, Kafka)
- Experience working with cache system (Redis, Memcache)
- Experience working with Nginx as proxy
- Experience with large-scale and high-traffic projects
- Extensive REST API development experience
- Experience in Test Driven Development (TDD)
- Attention to detail and demonstrable design and UX sensibilities.

## COMPENSATIONS: 

- Competitive & Attractive salary
- Great Trade Union benefits for staff and family
- Special Annual policy
- Remote work policy.

### WORK ENVIRONMENT: 

- Exciting internal events to help you understand the whole business and make you feel like you are part of the Cốc Cốc family
- Modern and cozy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day, to make sure energy level is high when you need it
- There are many interesting hobby clubs to share your non-professional passions: Yoga, Bicycle, Painting, Board game...

## CONTACT:
- Email: hattk@coccoc.com
- Skype: khanhhatran213
- JD: https://careers.coccoc.com/job/php-software-engineer-back-end-browser

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
