### ISSUE TITLE
[Cốc Cốc] Manual Test Engineer

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#2744]
The Quality Assurance team is responsible for performing in-scrum, acceptance, system, performance test activities for all Cốc Cốc browser and search engine products. The team strives to ensure that product activities are conducted to a high standard aligned with the right business priorities and needs.

* Saigon, Vietnam
* Remote in Covid pandemic
* Level: Senior (from 4-5 years of exp.)

## Responsibilities:

- Plan and execute tests against software and hardware products using a variety of manual techniques and automated tools to ensure requirements are met
- Interact with team members and other groups to ensure all requirements have been tested, defects have been documented, and quality issues identified during the testing process have been resolved
- Create and maintain test documentation such as test cases, defect reports and test result summaries
- Communicate product and process information to other members of the team, other departments, and customers as necessary
- Monitor and coach junior Test Engineer to work in the projects

#### Must have:

- Experience with manual testing, testing techniques and testing methodologies: cross-browser and cross platform
- Have experience in testing mobile application is required
- Have experience in working with various of devices: iOS devices, Android devices
- Experience in testing API, performance using Postman/SOAP UI is plus
- Have knowledge on database such as database schema and simple SQL query and familiar with entity relationship diagrams and the SQL queries is plus
- Good understanding of software development life cycle & common using software development process as Agile
- Experience in management tools such as JIRA, Confluence, testing tool
- English skills: Basic communication

#### Nice - to - have skills: 

- Experience in performance test and security test is a plus
- Experience in Automation test is a plus
- Have ISTQB Certified is a plus

### Compensations:

- Competitive & Attractive salary
- Great Trade Union benefits for staff and family
- Special Annual policy
- Remote work policy.
 
### Working environment:
 
- Exciting internal events to help you understand the whole business and make you feel like you are part of the Cốc Cốc family
- Modern and cozy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day, to make sure energy level is high when you need it
- There are many interesting hobby clubs to share your non-professional passions: Yoga, Bicycle, Painting, Board game...
- ### Interesting engineering projects

### Contact

- Email: hattk@coccoc.com
- Skype: khanhhatran213

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
