### ISSUE TITLE
[Kaito-Wings] - Development - Saigon - FullTime 

### ISSUE THREAD

**Issue by shjnvo** [awesome-jobs/vietnam#2746]
## Location

* Saigon, Vietnam

## Salary Expectation

* 20tr  〜 35tr depending on skill

## Requirements
* One of Rails / React / Vue (should study everything after joining)
* All of HTML/CSS/JS
* Understanding requirement, specification based on customer’s business
* At least 3 years experience at work

### You’ll be responsible for

* Development our service https://vn.minato-jp.com/
* Development web based vue/rails project
* Development web based react/rails project with rspec/EtoE test

### Contact
Homepage: https://kaito-wings.com/
Trollman: shjnvo89@gmail.com (Đức Lợi)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
