### ISSUE TITLE
Finan - Golang Developer - HCM - FT

### ISSUE THREAD

**Issue by trantuthien** [awesome-jobs/vietnam#2747]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* from 1100/month 

### Must Have

- 1 years of experience in software development.  
- Have knowledge of OOP, RESTful, Design Patterns.  
- Experience with REST, gRPC, and RabbitMQ APIs  
- Used to work with PostgresSQL  
- Ability to develop own Back-end Architecture when necessary.  
- Experience with Prometheus/Elastic, Kibana/Grafana, Ansible and Cloud Infrastructure 

### Responsibilities
- Improving our core technical platform. Making it more stable, more performant, easier to work in and more scalable.  
- Building features that provide quick value to users.  
- Contribute to all stages in the product life cycle. Design, implementation, testing, deployment, and monitoring  
- Learn and try new things to feed your thirst for knowledge and experience  
- Work as key developer and/or team leader in projects.  
- Work with Project Managers to determine needs and apply/customize appropriate technologies to deliver solutions.  
- Work closely with the Technical Manager, Product Manager, and Product Designer to build a next-generation web application.  
- Design and develop new features for the platform/system.  
- Build efficient and reusable code and systems.  
- Communicate with other team members to determine the best solutions to difficult problems. 

### Contact
Homepage: https://finan.me
Email: thien.tran@finan.me

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
