### ISSUE TITLE
[JobSeekervn - Saigon ] Senior Mobile Developer ( React Native) - $1800 - $2500

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2749]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1800 - $2500/month 

## Requirements
* Work closely with other cross-functional teams to define, design and deliver new features with high quality and responsiveness for a mobile-first application
* Participate in technical solution proposal and provide estimation for features to be delivered
* Participate in code review, promote best practices and coding guidelines to ensure code quality and maintainability
* Maintain, troubleshoot and fix issues in a timely manner based on the severity
* Bouncing ideas with other engineers to boost the development experience,speed and quality
* Promote team-player culture, assist other engineers to overcome technical obstacles

### Responsibilities
* 4 years experience in building a mobile application
* Strong mobile technical skills: React-Native, Typescript, native components, app responsiveness
* Experiences in GraphQL is a big plus
* Experience in (or willing to learn) NodeJS, NestJS, TypeORM is a plus
* Understand how to write clean code
* Understand how to write good tests
* Experience in Agile development

### Why it would be awesome to work with us
* Apple Macbook, external monitor to work
* 20 days for annual leaves
* Private Health Insurance
* 13th-month bonus salary

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn 
Job list: http://nhiha.top/job.php

**Comment by qcam** [comment]
@hahoainhi Thanks for posting. Currently we do not accept jobs from head-hunters or agencies.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you.
