### ISSUE TITLE
AOI Systems Vietnam - Back-end Developer (Java/PHP) - HCMC - FT

### ISSUE THREAD

**Issue by ASV-recruit** [awesome-jobs/vietnam#275]
## Location
- Tan Binh, HCMC, Vietnam
## Salary Expectation
- $550 - 900/month or negotiable
## Requirements

University graduated: Software Engineer, IT, …
At least 1 year experience. 
Have knowledge about OOP and design patterns.
Java candidate: have knowledge about Java, Spring Framework (IOC, AOP, Spring Transactions, JDBC Templates). Experience at UNIX / Linux, able to write shell scripts is an advantage.
PHP candidate: experience in programming PHP at least 1 year, have knowledge about SQL databases (preferably MySQL). Used to work with HTML, CSS, JavaScript.
## Benefits:

13th month salary. Annual leave 12 days. Health care Insurance.
Company trip. Team Building.
Working time: 8 am-17:30 pm (Monday to Friday)
Social insurance, health insurance, unemployment insurance and other benefits under the provisions of the Company. Annual medical examination. 
Working directly with Japanese clients, access to new technologies and have opportunities for personal development.
### Contact

web: aoi-sys.vn
HR Dept: tuyendung@aoi-sys.vn

**Comment by huydx** [comment]
It seems that this job is duplicated with https://github.com/awesome-jobs/vietnam/issues/276, can you check?

**Comment by ASV-recruit** [comment]
@huydx sorry, it seems my mistake. could I delete #276?

**Comment by huydx** [comment]
I've closed it

**Comment by ASV-recruit** [comment]
thanks for your support ^^
