### ISSUE TITLE
Senior Front End Developer (ReactJS, VueJS) - Fulltime HCM

### ISSUE THREAD

**Issue by tieuvu9x** [awesome-jobs/vietnam#2750]
## Location

* Remote during the Covid-19 (Then move to a Co-working space office, potentially in Sala, D2 or D1-HCM)
* Only open for candidates located and living in HCM city only

## Salary Expectation

* $2000 - $3000

## Requirements

- Frontend (Web) Developer with at least 5 years of hands-on coding.
- Experienced with multiple Javascript front-end frameworks (ReactJS/Angular/VueJS/Backbone/Ember).
- Experienced with building complex and large-scale systems.
- Understand how to build fast-rendering, complex front-end websites.
- Strong in algorithms and passionate about learning deep technical expertise.
- Good reading & writing English communication skills.
- Agile and flexible start-up mindset.

### Priority for candidates
- Having open-source contributions on Github is an advantage.
- Full-stack web experience (NodeJS / PHP/ Python / Ruby).
- Having worked at both outsourcing & product companies.

### Job Overview & Responsibility

- Be part of the Core Development team, responsible for development of all front-end web components.
- Take part in shaping platforms’ components, following microservices architecture.
- Establish a team working process and follow good practices in Agile Development.
- Help to hire and train up other team members.
- Learn new technologies, share with team members, and proactively apply new technologies to the development process.
- Reach out to the open source community to encourage and help implement mission-critical software fixes.
- Maintain code and write automated tests.

### Why Candidate should apply for this position

Benefit
- Remote work for now (until Covid situation improves).
- Then move to a Co-working space office, potentially in Sala, D2 or D1.

Working hour
- Follow VN working hours and VN Holidays.
- Daily meeting with the CTO / Team via Zoom (until Covid situation changes).
- Weekly meeting with a larger team via Zoom.
- Occasionally meeting with Management team and Design team around 10-11pm VN Time.

### Interviewing Process

2-3 rounds

### Report To

CTO

### Contact
Skype: natsuyuki91
Telegram: @leephuongg
Zalo: +84926953942
Connect Linkedin: https://www.linkedin.com/in/leephuong

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
