### ISSUE TITLE
Senior Backend Engineer (Go/Python) - Fulltime HCM

### ISSUE THREAD

**Issue by tieuvu9x** [awesome-jobs/vietnam#2751]
## Location

* Binh Thanh, HCM, Viet Nam

## Salary Expectation

* $2000 - $4000

## Requirements

• At least 3 years experience in delivering clean and concise code in Go/Python or Java and eagerness to learn more (medior / senior experience)
• Experience in a product company, software system, or SAAS
• Experience with developing complex distributed software systems and quality deployment and system reliability.
• Familiarity with large-scale distributed storage and database systems (SQL or NoSQL, e.g. Postgres, Cassandra, Clickhouse, Redis, Elasticsearch)
• Solid grasp on good software engineering practices such as code reviews, deep focus on quality and documentation
• Integration patterns knowledge & Enterprise integration experience,
• Experience with delivering data-oriented solutions in recent jobs (DW, BI, ETL, Hadoop, etc), cloud technologies such as GCP, AWS.
• Basic knowledge of Internet security, authentication (HTTP Basic, OAuth, …), data security and privacy, GDPR, encryption data-at-rest/in-transit.
• Great team spirit and solution-oriented attitude.

### Priority for candidates

• Martech experience ( DMPs, DSP, Emails, CDP, CDXP … )
• Work experience in B2B SaaS in online retail/e-commerce analytics, marketing.
• Work experience in engineering team in retail/commerce companies

### Job Overview & Responsibility

• Team-work with EM, PO/PM, FE engineers, DE/DS & play an important role in developing the backend of the 1st awesome Customer Data Analytics & eXperience platform made-in Vietnam, with our experienced & passionate team.
• Participating effectively in our Agile/SCRUM process, in software architecture design, deliverable sprints, code reviews and enhancements with the team, etc. as well as proposing new alternatives to existing tech and design solutions.
• Designing maintainable, testable code with high test coverage requirements.
• Creating integration and acceptance test coverage to new features and deployment.

### Why Candidate should apply for this position

• 13-month salary, milestone bonus, performance bonus
• Laptop provided and 1-2 screens (if needed)
• 12 paid annual leave days
• Great career opportunity with New & Deep Technology environment at the global quality standard
• Rewards & bonus by shares (ESOP plan) is available for highly committed seniors
• Innovative, open, and scientific working environment

### Interviewing Process

2 rounds: Technical Interview & Management Interview

### Report To

Principal Engineer

### Contact
Skype: natsuyuki91
Telegram: @leephuongg
Zalo: +84926953942
Connect Linkedin: https://www.linkedin.com/in/leephuong

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
