### ISSUE TITLE
Spiderbox Design - Fullstack (Laravel/Reactjs) - D2, HCM - FT

### ISSUE THREAD

**Issue by Uyenptm** [awesome-jobs/vietnam#2754]
## Location
* Saigon, Vietnam
* FT

## Salary Expectation
* $700 - $2,000/ month

## Requirements
* Over 2-year working experience with Laravel and ReactJS.

### Must Have
* Familiar with TDD/BDD
* Proficient understanding of code versioning tools, such as Git
* Clear communication skills for reporting needs and answering technical and service questions
* Experience working in an agile development environment
* Good problem-solving skills
* Good English communication 

### Ideally
* Experience working with foreign companies, in particular Australia
* Experience working in a fast paced agile team
* Is available to travel to Australia where required

### Responsibilities
* Laravel/ReactJS Full Stack Developer will be part of a fast growing team of developers to support a
range of front end and back end projects for a large Australian client.
* We work within an Agile SCRUM methodology.
- Report directly to team leader
- Ability to work in an agile environment and Iterate quickly based on customer and internal
feedback.
- Constantly learn and keep abreast of emerging technologies.
- Accurate estimation and delivery of deadlines
- Support the QA process and ensure client delivery is 100% tested and stable

### You’ll be responsible for
* Laravel/Reactjs

### Why it would be awesome to work with us
* Competitive and attractive salary
* Private health care
* New Computer (Mac/PC) that fits your needs
* Comfortable working time: 9am - 6pm (flexible), Mon - Fri
* A conveniently located office in D2, HCMC.
* International, dynamic, friendly working environment
* Annual performance review: recognize your efforts and identify development/ improvement needs
* Clear KPI’s and expectations
* Free English class
* Internal activities: weekly games, English talk with gift vouchers, free snacks & drinks

### Interesting engineering projects
* Based in Melbourne, Seattle and Saigon, Spiderbox Design is a fast growing, small software firm that develops for clients as an agency as well as internal self owned/funded software.
* We value and understand the importance of our team and their happiness and career ambitions. It is important to Spiderbox that our staff are not only happy but are provided the opportunity to continue to grow, learn and improve their expertise and skills.

### Contact
Homepage: https://spiderbox.design/
Email: uyen.pham@spiderbox.design (Uyen - 0981235794)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
