### ISSUE TITLE
Ecomobi looking for 1 Frontend Developer (Reactjs, Redux, AWS, Azure or GCP,...) Hanoi

### ISSUE THREAD

**Issue by dinhhuehr** [awesome-jobs/vietnam#2755]
## Location

* Hanoi, Vietnam
* Fulltime, office

## Salary Expectation

* 20M - 30M/ month

## Requirements
Qualification: Bachelor degree in IT or related field

Experience:

Must have hands-on experience in React.js for at least 2-3 years;
Experience with popular React.js workflows Redux; 
Experience in working with programming languages such as PHP, Javascript (NodeJS); 
Experience on working with cloud platforms like AWS, Azure or GCP.

Knowledge:

Thorough understanding of React.js and its core principles; 
Knowledge about Real-time Web applications with WebSocket; 
Good knowledge of SASS, LESS, REST API, HTML template engines;
Strong knowledge of server and database technologies including Linux, Nginx, MySQL, MongoDB is prefered.

Skill:

Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model;
Good interpersonal and communication skills; 
Good English skills (reading and writing).

### Responsibilities

Work collaborative with the team to understand requirements, design, code, test and build great user interfaces and experiences for innovative applications.
Work independently on tasks with the opportunity to get input from other engineers as needed.
Participate in peer reviews of pull requests and provide productive feedback to improve quality of work.

### Why it would be awesome to work with us
100% Salary for Probation.
Lunch allowance: 35.000 VND/working day
Flexible time: 9AM – 6PM (7,5 hours/day From Monday to Friday)
Fund for Training & Development.
Yearly bonus: 13th-month salary and performance-based bonus (as company's policy)
Bonus based on working performance (quarterly) and Salary review twice a year
Personal Healthcare Insurance beside Social and Medical Insurance
Teambuilding: from 2-3 times/year, both local and overseas
International working environment with foreign colleagues and partners
Opportunities for professional training on jobs and skills

### Contact
Homepage: https://ecomobi.com/en/
Ms Hue Dinh - Skype dinhhue.hr
Mail recruitment@ecomobi.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
