### ISSUE TITLE
GOLDEN PHOENIX MEDIA - SENIOR FRONTEND DEVELOPER - HANOI - FT

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#2757]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* $1000 - $2000/month

## Requirements (must-have)
* From 3 – 5 years of experience in FE development
* Familiar with HTML, CSS, JavaScript (ES6+), React, VueJS
* Experience working with APIs
* GIT

### Nice-to-have

* Leadership experience and the ability to make an impact and drive changes
* Mentoring experience
* Ecommerce domain
* Shopify or other ecommerce platform
* UX/UI

### Ideally

* Experience with Ecommerce

### Responsibilities

* Work on the web-based application product
* Develop and enhance product offerings in accordance with design, consistent with business objectives
* Continuously research and implement new technologies to maximize development efficiency
* Identify potential issues and working out possible solutions
* Develop new user interface features in a large-scale of web application.
* Ensure the technical feasibility of UI/UX designs.
* Optimize application for maximum speed and scalability.
* Assure that all user input is validated before submitting to back-end.

### You’ll be responsible for

* leading front-end team and drive technology forward

### You can bring

* what technologies should be using
* best experience to customers

### Why it would be awesome to work with us
* Social insurance
* 13th month salary
* High year-end bonus
* Lunch allowance
* Team building and travelling
* High ownership

### Interesting engineering projects
* New ecommerce site setup

### Contact
Homepage: goldenphoenixvn.com
Email: hr_at_goldenphoenixvn_dot_com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
