### ISSUE TITLE
MEGAZONE - Fullstack Java Developer 

### ISSUE THREAD

**Issue by dangokuson** [awesome-jobs/vietnam#2758]
## Location
* Hanoi, Vietnam

## Salary Expectation

* Up to $2000/month or range

## Requirements
* Proficient in Java/JEE and Spring framework, with a good knowledge of its ecosystems
* Strong understanding of object-oriented programming
* Familiar with various design and architectural patterns
* Skill for writing reusable Java libraries
* Knowledge of concurrency patterns in Java
* Experience with both external and embedded databases
* Understanding fundamental design principles behind a scalable application
* Creating database schemas that represent and support business processes
* Implementing automated testing platforms and unit tests
* Proficient understanding of code versioning tools, such as Git
* Ability to clearly communicate with both technical and non-technical team members

### Must Have

* 3+ years Software Engineering experience
* Familiarity with concepts of MVC, JDBC, and RESTful
* Proficiency with SQL, Hibernate, JPA
* Experience with Agile Scrum
* Experience with Ember or other JavaScript
* Familiarity with build tools such as Ant, Maven, and Gradle

### Responsibilities

The Fullstack Java Developer will be responsible for

* Translate application user stories into functional applications
* Design, build, and maintain efficient, reusable, and reliable Java code
* Ensure the best possible performance, quality, and responsiveness of the applications
* Identify bottlenecks and bugs, and devise solutions to these problems
* Maintain code quality, organization, and automatization
* Write and maintain high quality unit tests
* Perform code review
* Adhere to the acceptance criteria and the Definition of Done

### Why it would be awesome to work with us

* Product company with global reputation specialized in end-point security
* Very attractive salary (Negotiation)
* 13th month salary
* Birthday’s gift
* Flexible working hours (Working time: 8:30 AM - 5:30 PM from Monday to Friday)
* Training & development opportunities
* Macbook Pro for everyone

### Contact

Email: sondn@mz.co.kr
JD: https://itviec.com/it-jobs/full-stack-java-j2ee-spring-2000-megazone-5204?utm_campaign=gsn_brand_hn&utm_medium=key_cpcutm_campaign%3Dgsn_brand_hn&utm_source=google&lab_feature=employer_job

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
