### ISSUE TITLE
Golden Phoenix Media - Senior UI/UX Designer - Ha Noi - FT

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#2759]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* $1000 - $2000

## Requirements
* Good eyes for visual design and hands on experience in user interface design.
* Strong understanding of ecommerce UX best practices
* A mobile-first mindset and ability to design responsive interfaces & interactions across devices and screen sizes
* Familiar with data and able to identify problem areas, further map out user journey and break these problems into smaller chunks.
* Able to communicate well with teams to present your design ideas and decisions clearly

### Nice to have

* understanding of CSS and technical design implementation

### Ideally

* Experience with Ecommerce

### Responsibilities

* Research modern trends about design application especially worldwide ecommerce site.
* Design Systems: Help us build an internal product style guide: Standardized components and libraries will allow us to increase our velocity in experimentation to better serve our customers
* Interface Design & Growth Experimentation: Bring ecommerce UX’s best practices in building & running experiments that can drive customer acquisition, retention, overall satisfaction

### You’ll be responsible for

* Joining and developing a scaling ecommerce business

### You can bring

* A good eyes for design
* A good analysis skill
* A logical thinking

### Why it would be awesome to work with us

* Social insurance
* 13th month salary
* High year-end bonus
* Lunch allowance
* Team building and travelling
* High ownership

### Contact
Homepage: goldenphoenixvn.com
Email: hr_at_goldenphoenixvn_dot_com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
