### ISSUE TITLE
MEGAZONE - PHP Developer (Laravel / Magento)

### ISSUE THREAD

**Issue by dangokuson** [awesome-jobs/vietnam#2760]
## Location
* Hanoi, Vietnam

## Salary Expectation

* Up to $2000/month or range

## Requirements
* University degree in Computer Sciences, or equivalent.
* Basic knowledge of OOP, SOLID principles, PHP coding standard.
* Good knowledge of PHP development, at least one PHP framework (Laravel/Symfony). 
* Good knowledge of web service development (SOAP, RESTful). 
* Good knowledge of HTML5, CSS3, JavaScript, Ajax. 
* Have ability to do development work for both back-end and front-end. 
* Logical thinking and problem-solving skills

### Must Have

* 2+ year experience LAMP competence (Linux, Apache/Nginx, MySQL, PHP).
* Familiarity with concepts of MVC, and RESTful
* Experience with Agile Scrum
* Experience with Ember or other JavaScript
* Experienced in one JavaScript Front-end framework (Angular/ReactJS/VueJS).

### Responsibilities

The Senior PHP Developer will be responsible for

* To develop software applications with limited support from senior engineers.
* To write program from design specifications in compliance with established coding quality standard of the company.
* To write unit tests and run through all the test cases for assigned tasks and ensure all cases tested and passed before release for testing.
* To perform code review, code refactor if required.
* To document detailed designs as part of technical leaders (lead by Technical Architect or Solution Architect).
* To self-train on new technologies.
* To follow strictly all the customer’s process if being requested, company’s processes.

### Why it would be awesome to work with us

* Product company with global reputation specialized in end-point security
* Very attractive salary (Negotiation)
* 13th month salary
* Birthday’s gift
* Flexible working hours (Working time: 8:30 AM - 5:30 PM from Monday to Friday)
* Training & development opportunities
* Macbook Pro for everyone

### Contact

Email: sondn@mz.co.kr
JD: https://itviec.com/it-jobs/senior-php-magento-laravel-2000-megazone-5225?utm_campaign=gsn_brand_hn&utm_medium=key_cpcutm_campaign%3Dgsn_brand_hn&utm_source=google&lab_feature=employer_job

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
