### ISSUE TITLE
fram^ - Senior ReactJS Engineer - Danang - FT

### ISSUE THREAD

**Issue by HoVanThi** [awesome-jobs/vietnam#2761]
## Location

* DaNang, Vietnam
* Fulltime

## Salary Expectation

* Negotiate

## Requirements
* At least 3 years in ReactJS/ React Hook, etc
* English level: Intermediate, upper intermediate is a big plus

### You’ll be responsible for
* Direct contribution to the codebase as a frontend engineer, as part of a product team
* Identifying, documenting, and communicating technical improvements within your area of responsibility in the team
* Supporting in the development and reinforcement of frontend engineering standards and guidelines
* Participating in cross-team engineering initiatives as individual contributor

### Why it would be awesome to work with us
* Work with our key project (https://www.personio.com/) from Germany
* One of our Personio team members was sponsored to relocate his family to Germany to live and work directly with our client
* No one else leave this team since established date - Dec 2017
* English working environtment with Germany team

### Contact
Homepage: https://wearefram.com/careers/senior-frontend-engineer-reactjs-2/
Skype: live:vanthy195 or M:0905215963

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
