### ISSUE TITLE
FETCH TECHNOLOGY - Junior Fullstack Developer (dotNet) - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2768]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/128285914-adb1c0b2-a89a-4f06-8693-538036037a1d.jpg)

# HCM
# 500 - 1,000 USD 

## INSTRUCTION

a. About Fetch:
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

b. About Client:
Our client is the preferred financing partner in supporting Vehicle/COE Financing, floor stocking, equipment financing, accounts receivable financing/factoring, loans for industrial/commercial property and property development, renovation loans, and other forms of commercial lending. They are planning to steadily expand their range of financial services to cater to more of the customer’s financing needs.

## RESPONSIBILITIES
* Work together with clients to get requirements.
* Build efficient, reusable components and high-quality front end.
* Handling full-stack programming tasks for the development.
* Triage bugs and troubleshoot production issues.

# REQUIREMENT
* 1-year experience in dotNet, Entity Framework, React, Redux, Hook.
* Strong understanding of OOP and Clean Code.
* Experience in SQLServer databases and schema design.
* Experience in Javascript (ES6) & HTML / CSS.
* Understanding of RESTful APIs.
* Experience in Git.
* Experience with Infrastructure/DevOps is a plus.
* Strong command of English and good communication skills.
*Nice to have: CQRS, DDD pattern.

# WHY YOU‘LL LOVE WORKING HERE
Being a Junior Full-stack Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
* Extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

# WORKING TIME & LOCATION

* Working time: 9 AM - 6 PM from Monday to Friday.
* Location: 3rd Floor, BCONS TOWER 2 - 42/1 Ung Van Khiem Street, Ward 25, Binh Thanh District, Ho Chi Minh City.

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by Jesse111-flyaway** [comment]
Apply trực tiếp qua link JD này cũng được nhé mọi người ơi: https://bit.ly/3q4A7iL

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
