### ISSUE TITLE
FETCH TECHNOLOGY - 04 Middle/Senior DevOps Engineer - HCM - FT - Up to 3,500 $

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2770]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/128287900-4babd059-1f97-443d-b7b4-78398d683a31.jpg)

# HCM
# up to 3,500 USD

# INTRODUCTION
**a. About Fetch:**
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client:**
Originally founded in Silicon Valley in 2014 and headquartered in Singapore, our client is a market-leading, and one of the oldest, homegrown cryptocurrency platforms. Their aim is to accelerate access to cryptocurrencies throughout the ASEAN region and we focus on localized cryptocurrency exchange services – acting as cryptocurrency gateway services in multiple countries.

# RESPONSIBILITIES 

- Build & maintain successful CI/CD pipelines across multiple environments. 
- Support the development team to set up and configure the development environment. 
- DevOps mindset with automation flow design capability. Develop automation tools, including shell scripts to automate necessary tasks. 
- Build monitoring, auditing, automating, and reporting frameworks that support security and compliance needs.
- Collaborate with software engineers to understand the software architecture, main components, current obstacles and provide solutions. 
- Design and deploy cloud platform capabilities - full-stack network, load balancing, caching, DNS, security, databases, etc. 
- Experienced working in an Agile, ITIL Process, fast-paced DevOps environment.
- Perform advanced technical troubleshooting for public, private and hybrid cloud environments. 
- Define and monitor system metrics to ensure predefined SLA, SLO. 

# REQUIREMENT 

- 3+ years experience in DevOps engineering environment.
- Strong background in Linux / Unix, preferably with experience in NixOS.
- Ability to debug and analyze problems quickly.
- Ability to manage time efficiently, working independently and in a team.
- Ability to learn quickly and apply new skills effectively.
- Ability to multitask and retain a high attention to detail.
- Have experienced with AWS: EKS on Fargae/EC2 group, cert-manager, Transit Gateway, VPN, VPC, Security group, S3, CloudFront.
- Experience with CI/CD processes using self-managed tools or relevant cloud technologies: GitActions, ArgoCD, helm chart, drone, CodeBuild, CodePipeline.
- Hands-on experience in operating and maintaining high intensive RDBMS (eg: Postgresql).
- Have experience with application containerization and orchestrator such as Kubernetes etc.
- Familar with the following tools: Jira, Jira Service Desk, PagerDuty, NewRelic, Terraform, Ansible, Vault...
- Knowledge about Computer Security, Application Security, and Security Standards & Best Practices.
- Hands-on experience in networking, system administration, monitoring, infrastructure maintenance on premise or cloud environments.
- Knowledge of microservice architecture, RESTful.

# WHY YOU‘LL LOVE WORKING HERE 
Being a DevOps Engineer at this company, you will experience a youthful, flexible and creative work environment.  

- MacBook or high-end laptop for working.
- Attractive salary and bonus package (13th-month salary, performance bonus).
- Salary review twice a year.
- 14+ annual leave, 60 days working from home per year.
- Working in a professional, friendly, flexible, well-equipped environment.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law; Premium Health Care.
- Personal Growth Development Plan.
- Enjoy diversified activities: Snack every day, Happy Friday every week, Monthly Team-building, Company trip (2 trips per year), Game, Sport (Football, Badminton...). 

# WORKING TIME & LOCATION

- Working time: 9AM - 6PM from Monday to Friday.
- Location: 4th floor, HQ Tower - No. 9, Tran Nao Street, Binh An Ward, Thu Duc City (District 2), Ho Chi Minh City.

# CONTACT:

- Mail: trangdong@fetch.tech
- Skype: trangdong0111@gmail.com

# OR APPLY THROUGH THIS JD: https://bit.ly/3ptrKx0

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
