### ISSUE TITLE
FETCH TECHNOLOGY - Senior ReactJS Software Engineer - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2771]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/128289087-07678310-7f86-4c62-afae-aef2c8184cfd.jpg)

# HCM/HN

# 1,000 - 2,500 USD

# INTRODUCTION
**a. About Fetch:**
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client**

NIFTEX.org is pioneering Non-Fungible Finance by enabling the fractionalization of Non-Fungible Tokens (NFTs) from leading projects such as Axie Infinity, CryptoPunks, Decentraland and many more. Our markets have generated more than $14m in volume since May 2020 and we’ve just completed a funding round to take NIFTEX to the next level.

# RESPONSIBILITIES
We need one new core member who has taken a growing number of tasks to push innovations of NFT fractionalization and joining efforts in building SDK.

* Develop high-performance web applications.
* Analysis requirements and maintain technical documentation.
* Contribute ideas & solutions to the products.
* Write clear and maintainable code.
* Participate in all phases of the product development process including analyzing user requirements, designing system architecture, coding, testing and deployment. 
* Build front end for advanced user experience.
* Build reusable components/modules for websites with responsive design.
* Work with API endpoints or Socket for dynamic content updating.
* Ensure UI/UX of developed pages and software with near pixel-perfect design.
* Develop and optimize front-end UI to ensure the application is rendered consistently in cross-browser environments.
* Cooperate to connect front-end software development with an expert backend team.

# REQUIREMENT
* At least 3 years experience of working as frontend developer. 
* Proficient in React stack (ReactJS, Redux, State Management, Functional Programming).
* Solid knowledge with HTML5, CSS3, SASS/SCSS.
* Experience in developing responsive layouts leveraging CSS and media queries.
* Design and implement robust client-side solutions with RESTful, GraphQL API and Socket.
* Strong competency in responsive, mobile-first layouts leveraging CSS and media queries. 

 **Nice to have:**

* Web3.js experience is strongly preferred.
* NFT knowledge is strongly preferred.

# WHY YOU‘LL LOVE WORKING HERE
Being a Senior ReactJS Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment: 

* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

# LOCATION: 

- Ho Chi Minh: Bcons Tower 2 - 42/1 Ung Van Khiem Street, Ward 25, Binh Thanh District.

- Ha Noi: 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
