### ISSUE TITLE
Anduin Transactions_Front-end Engineer_Saigon_Full-time

### ISSUE THREAD

**Issue by uyendinh9254** [awesome-jobs/vietnam#2772]
## Location

* Saigon, Vietnam
* Full-time (WFH now)

## Salary Expectation

* Competitive (Top market)

## Requirements

- Deep understanding of vanilla JavaScript, CSS, and HTML
- Comfortable working with and making changes to large existing code base
- Experience with front end frameworks such as React
- Have experience with building reusable UI components
- Have experience with building responsive websites, especially web-based mobile applications
- Proficient understanding of cross-browser compatibility issues and ways to work around them
- Familiar with researching and evaluating open source libraries, figuring out their trade-offs and choosing the right solutions
- Familiar or involved with open­ source projects
- Comfortable working with design team

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

- Embraces ownership of domain areas and goes above and beyond to execute
- Develop new user-facing features
- Build reusable code and libraries for future use
- Ensure the technical feasibility of UI/UX designs
- Optimize application for maximum speed and scalability
- Collaborate with other team members and stakeholders

### Why it would be awesome to work with us
Anduin Transactions is a groundbreaking new financial technology startup founded by Joe Lonsdale, co-founder of Palantir Technologies and Addepar. As leaders and engineers at Palantir Technologies, Facebook, Google, IBM, One King's Lane, and WalmartLabs, the founding team has hands-on experience applying Silicon Valley best practices to team building and product creation. Our mission is to create a universal standard for tracking and managing transactions in private markets. We are forming a world-class team in the U.S and Ho Chi Minh City and are backed by top-tier industry influencers and insiders.

Our top benefit:
- Awesome colleagues
- Generous compensation
- Unlimited vacation policy
- Comprehensive health insurance
- Nice office with lots of cool stuff to relax (games, billiards)

### Interesting engineering projects

Our products: Fundsub.io - Metadataroom.io - Anduinsign.io 

We are looking for a Front-End Engineer who is motivated to combine the art of design with the art of programming. Responsibilities will include translation of the UI/UX design wireframes to actual code that will produce visual elements of the application. You will work with the UI/UX designer and bridge the gap between graphical design and technical implementation, taking an active role on both sides and defining how the application looks as well as how it works.

### Contact
uyendinh@anduintransact.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
