### ISSUE TITLE
Quod AI - Kotlin Developer Intern - Saigon - FT/PT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2773]
## Location

* Saigon, Vietnam

## Salary Expectation

* 3,000,000VND - 6,000,000VND

## Requirements

* Experience with Kotlin
* Good understanding of micro-services
* Relevant experience with Google Cloud or AWS or Azure.
* The ability to learn and iterate quickly.
* An obsession with agile and lean principles (GitHub, Trello).
* Prior development of JetBrains plugin would be a plus.

### Education and Experience

* Strong verbal and written communication skills in English.

### Responsibilities

* Work closely with the product team to develop and maintain JetBrains plugins for our core-product.
* Work on the implementation of new features, leaving things properly implemented, well documented and delivered on time.
* Always be on the lookout for opportunities to create and improve. From our development process, up to final user’s experiences.

### Contact
Homepage: [https://www.quod.ai/](https://www.quod.ai/)
**[Apply here](https://docs.google.com/forms/d/e/1FAIpQLSd0n7WUvlu8B27VINJ4fO86T64MkeiZ2XWEEWFfeLvvOL9xnQ/viewform?fbzx=7745572257721885000)**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
