### ISSUE TITLE
Vinova - Ruby on Rails Developer - HCMC - FT

### ISSUE THREAD

**Issue by jonathan-vinova** [awesome-jobs/vietnam#278]
## Company Information :

We, VINOVA (VIbrant inNOVAtors), earn respect from customers for being committed to quality, flexibility and speed. We strike to build killing products by working closely with customer, by working passionately, and by collaborating openly and disciplinary. Vinova is among **TOP10** Mobile Applications Development Companies in Singapore - according to Medium.com. 
_Website_: [www.vinova.sg](www.vinova.sg)
_Facebook_: [https://www.facebook.com/vinova.sg](https://www.facebook.com/vinova.sg)
## Salary Expectation
- Commensurate with experience
## Job Description
# The job:
- Design and build advanced web app/mobile API; 
- Collaborate with cross-functional teams to deliver value features; 
- Work on bug fixing and improve application performance; 
- Continuously discover, evaluate, and implement new technologies to maximize development efficiency; 
- Carry out relevant R&D to address new trends and new technologies that could be applicable to the current products.
- Supervise and support other junior developers in fulfilling tasks as well as improving their skills
## Requirements:
- At least 1+ years of experience with Ruby on Rails
- Have a strong background in IT (general knowledge about algorithm, data structure, programing principle, database). 
- Solid understand of object oriented programming principle. 
- Experienced with web service protocols such as HTTP/ REST, SOAP.
- Experienced with HTML 5/CSS 3/SASS/Jquery/Ajax is a plus.
- Experienced in deploying system on Heroku/Amazon EC2.
- A commitment to quality and a thorough approach to work.
- Good teamwork and reliability.
- Able to read/write well in English. 
## Why'll you love working here:
# Opportunities
- Direct coaching from top management
- Chance to work overseas based on the request from clients
- Chance to improve the technical skill during working with clients on new technology.
- Chance to become leader of a dynamic and growing company.
- Chance to improve English skill since the main communication is English during working hours.
# Benefits

We have a fun, Silicon Valley style startup culture that values openness, fun and awesomeness.
- Attractive salary and annual salary review.
- Provide Macbook Pro for work.
- A fun, awesome work environment with multiple exciting bonus schemes (13th month bonus, performance bonus, peer-to-peer bonus...)
- Progressive and international working environment.
- Exciting weekly/annually company activities.
## Contact
- Please send your CV to Jonathan Le: `hr.hcm@vinova.sg`

**Comment by huydx** [comment]
Hi @jonathan-vinova , please conform to our JD by remove "Wanted" part in your title
