### ISSUE TITLE
FPT Telecom - Python Developer - Hanoi - FT

### ISSUE THREAD

**Issue by ThanhtraITrecruiter** [awesome-jobs/vietnam#2780]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 20M-30M VND

## Requirements
* Flask/Django Framework
* Experience with Python

### Ideally
*  Experience with HTML/JS/CSS , any front-end framework is a plus

### You’ll be responsible for

* Build company's websites
* Write programs, apps on desktop, mobiles
* Research on new technology, analyze database, automate operation tasks of FPT's internet system.

### You can bring

* Your talent is everything we look for 💯 

### Why it would be awesome to work with us
* Salary package equivalent to 14-22 month salary (13th-month bonus, KPI bonus, etc)
* Insurance package (FPT care)
* Great, innovative, prospering working environment
* Unique, inclusive company culture
* Sponsorship for international certificates
* And many more benefits 
### Contact
Email: trant11@fpt.com.vn
Zalo: 0336699494

**Comment by ThanhtraITrecruiter** [comment]
contact me for more information nhen. We are really in need of talents right now

**Comment by Huy-Ngo** [comment]
> Experience with Python

Can you specify how much experience does this job require?

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
