### ISSUE TITLE
[HCM] Fullstack Java developer - max $2000

### ISSUE THREAD

**Issue by tienle-hr** [awesome-jobs/vietnam#2782]
## Ho Chi Minh

* Saigon, Vietnam
* Fulltime

##$2000

## Requirements
* Ruby
* Lotus Framework
* PostgreSQL
* 5+ years Software Engineering experience

## Skills

Key Requirements 
•	Master or Bachelor Degrees in Information Technology, Mathematics or Sciences
•	0-3 years of experience with the software development cycle: product specification, design, implementation, QA, release, maintenance for junior and middle. Min 4 years experience for senior.
•	Knowledge of SQL (select, join, union, group by, etc)
•	Knowledge of Java (spring or hibernate) and/or scripting languages such as UNIX Shell or Javascript
•	Fluent English and good communication skills is a plus

Preferred Requirements

•	Other programming experience a plus, esp Angular, Python
•	Knowledge of Data Dictionaries, Templates, Workflows
•	Keen interest in financial markets. Working knowledge of financial products a plus
•	Strong passion for learning and adapting to new technologies
•	Strong analytical and problem-solving skills

### Contact
Mail: camtien.le@upskills.com
Skype: camtien96.hr@gmail.com
Facebook: https://www.facebook.com/profile.php?id=100038612225580

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
