### ISSUE TITLE
Money Forward Vietnam - Lead Engineer - HCMC - FT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2783]
## Location

* HCMC, Vietnam

## Salary Expectation

* $1800 - $4000
* Sign-on bonus: 1 month salary

## Requirements
* Education: Bachelor of IT or equivalent
* Language: Good English communication

### Must Have

* 5+ year experience of development with Ruby on Rails/ or Golang
* Good understanding of SOLID principles, common design patterns and best practices
* Solid experience with MySQL or PostgreSQL including performance tuning and optimization
* Experience with complicated system architecture which includes API linkage with external systems
* Experience with application performance monitoring and optimisation
* Experience with automation testing, E2E testing
* Extensive knowledge of web security
* Familiarity with CI/CD, Docker
* Good English communication skills
* Experience of leading a project as a team leader
* Strong sense of ownership

### Ideally

* Experience with Amazon Web Services
* Experience with service operation on production
* Experience with frontend development (TypeScript, ReactJS/VueJS)
* Experience of training junior/middle members

### Responsibilities

* Design and develop services which can handle a massive amount of data
* Design good database considering functional and non-functional requirements
* Write clean and maintainable code
* Improve code by continuous refactoring
* Monitor application performance and fix system failures
* Train junior/middle members

### You’ll be responsible for

* Our mission is "Building a financial platform for all". You will be a part of it

### Why it would be awesome to work with us
* Sign-on bonus 1 month salary
* No probation applied for technical positions (all levels)
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
