### ISSUE TITLE
Senior/ Mid-senior level Ruby On Rails engineer

### ISSUE THREAD

**Issue by karg-betacode** [awesome-jobs/vietnam#2785]
## Location

* Remote, able to work +-3 hours Malaysia timezone.

## Salary Expectation
* $1500 - $2000 USD/month

## Requirements
* Ruby
* RubyOnRails
* ReactJS
* PostgreSQL
* Unit Tests - Rspec
* 4-5+ years Software Engineering experience

### Must Have

* At least 4 years experience in RubyOnRails.
* Comfortable to speak English. We do not expect perfect English.
* Train/ mentor junior developers

### Ideally

* Other languages one or more: JS/TS, Python, C#
* Docker
* Shopify/ BigCommerce integration
* AWS
* Terraform

### Responsibilities

Help the team to implement best practices.
Advice in task priority and dependencies.

### You’ll be responsible for

* Building backend on RubyOnRails. 
* Continous improvement to existing code quality and system stability.
* Code review and mentorship to junior developers
* Continous self-improvement
* Experiment / R&D on alternative approach in development.
* System design & architecture
* Assist front-end development if needed - we use ReactJS and VueJS.

### Why it would be awesome to work with us
* 100% remote team
* You plan your working hours
* Unlimited time-off but please do not abuse this privilege.
* Work with local and international startups and our own products.

### Contact
Homepage: betacode.io
Email your interest to: karg@betacode.io.  Subject: "RubyVN -  Ruby On Rails engineer"

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
