### ISSUE TITLE
MCVGo - Junior Back-end engineer - HCM D7

### ISSUE THREAD

**Issue by hungmcvgo** [awesome-jobs/vietnam#2788]
## Location

* Saigon, Vietnam
* Fulltime
* District 7

### Company domain:
* Live Streaming
* Real-time Interactive
* Private Social Network

## Salary Expectation

* $700-800

## Requirements
* Java
* Spring Boot
* PostgreSQL/MySQL
* 1+ years as a Backend dev experience

### Must Have

* BA in Computer Science, Information Systems, or related field;
* At least 1 year working experience as a Backend Developer or similar title;
* Good knowledge about Design Patterns, OOP, MVC, code versioning tools and Gitflow;
* Experience in Front-end development with Javascript/CSS  is a plus;
* Good English reading and writing skills.

### You’ll be responsible for

* Build, Deploy, and Maintain software components for projects on Server side;
* Analyze and improve efficiency, scalability, and stability of various system resources;
* Practice disciplined software engineering (e.g. unit test, code reviews, gitflow);
* Write technical documentation.

### Why it would be awesome to work with us
* Dynamic, technological and Agile working environment
* Self-development: online technical seminar, career talk and various trainings on hot-trend technologies, languages and soft-skills
* Talented and enthusiastic fellows
* Creative office spaces with free coffee, snacks and table tennis, billiards
* 13th-month salary, Annual salary raise review
* Macbook 

### Contact
Mr. Hùng
hungvd@mcvgo.com
0936907925

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
