### ISSUE TITLE
Money Forward Vietnam - PHP Engineer - HCMC - FT 

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2790]
## Location

* Saigon, Vietnam
* 100% online working temporarily due to Covid19

## Salary Expectation

* We offer salary at your expectation

## Requirements

* Education: Bachelor of IT or equivalent
* Language: Good English communication

### Must Have

* Passion as a problem solver / software engineer
* You love to learn new things
* Skills Advance Knowledge in PHP, HTML5, CSS3, JavaScript, JQuery & Ajax is must
* 1-2 years of experience of Web Development using any Web Framework
* Familiar with Yii Framework
* Familiar with other programming / scripting language such as Python / Ruby will be advantage
* You know how to test your code
* Experienced with JavaScript framework: ReactJS OR Angular 4
* Good understanding about database (Mysql/MongoDB)
* Know the basic of Linux administration
* Experience with cloud computing
* Experience with web service/app scaling
* Solid understanding with coding best practice and design patterns

### Ideally

* Eager to refactor bad code.
* Have experience deploying an app to production environment.
* Have experience with Docker.
* Open source contributor.

### Responsibilities

* Develop products for our customers
* Work closely with product owner to develop solution for our customers
* Work closely with DevOps to maintain the application in our infrastructure

### You’ll be responsible for

* Building one of the biggest SaaS projects

### Why it would be awesome to work with us

* No probation applied for technical positions (all levels)
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee

### Interesting things about this job
* Big & interesting project
* Chance to work with international team

### Contact
* Email: nguyen.thi.to.loan@moneyforward.vn
* Skype: nguyentoloan2009
* Phone: 0906 516 291 (Direct call/Zalo/WhatsApp/Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
