### ISSUE TITLE
HCM - Aspire Vietnam - 9 Junior, Middle, Senior React Native, Vuejs Engineer + 6 QA Engineers

### ISSUE THREAD

**Issue by nghiemthanh1801** [awesome-jobs/vietnam#2800]
## Location
* Circo Building, 222 Dien Bien Phu Street, District 3, Saigon, Vietnam

## Salary Expectation
700- 2500 USD

## Requirements
● At least 3 years of experience for senior roles, 1 years of working experience in junior role
● Firm grasp of the JavaScript and TypeScript language and its nuances, including ES6+
syntax
● Knowledge of functional programming
● Ability to write well-documented, clean Javascript code
● Rock solid at working with third-party dependencies and debugging dependency
conflicts
● Familiarity with native build tools.
● Understanding of REST APIs, the document request model, and offline storage
● Good command of English speaking.

### Responsibilities
● Build pixel-perfect, buttery smooth UIs across both mobile platforms.
● Leverage native APIs for deep integrations with both platforms.
● Diagnose and fix bugs and performance bottlenecks for performance that feels native.
● Transition existing VueJS web apps to React Native.
● Coordinate with co-developers and keep project managers well informed of the status of development effort and serves as liaison between development staff and project manager

### Contact
● Thành Nghiêm – quocthanh@aspireapp.com – 0936156822
● Skype: nghiemquocthanh1801
● https://www.linkedin.com/company/aspire-sea/mycompany/
[ASPIRE - SENIOR REACT NATIVE ENGINEER JD.pdf](https://github.com/awesome-jobs/vietnam/files/7004061/ASPIRE.-.SENIOR.REACT.NATIVE.ENGINEER.JD.pdf)
[ASPIRE - JUNIOR, SENIOR FRONTEND ENGINEER (JD).pdf](https://github.com/awesome-jobs/vietnam/files/7004064/ASPIRE.-.JUNIOR.SENIOR.FRONTEND.ENGINEER.JD.pdf)
[ASPIRE - QA ENGINEER (JD).pdf](https://github.com/awesome-jobs/vietnam/files/7004066/ASPIRE.-.QA.ENGINEER.JD.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
