### ISSUE TITLE
Tulpo Software - Blockchain Developer - Hanoi - Fulltime

### ISSUE THREAD

**Issue by Locnguyen4696** [awesome-jobs/vietnam#2802]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* From $2500/month

## Requirements
* Understanding of Blockchain technology.  
* 2-5 years of Solidity or Vyper development experience.
* Experience with smart contract static analysis tooling (e.g. Manticore) or formal verification (e.g. KEVM) would be a plus.
* 2-5 years of experience in server-side programming languages (e.g. Typescript, Golang, NodeJS).
* 2-5 years of experience in Test-Driven Development.
* 2-5 years of experience in development lifecycle automation, continuous development, continuous integration.
* Strong organizational skills, interpersonal skills, and having the ability to juggle conflicting requirements from many different stakeholders.
* Docker, Linux, gRPC, database (MySQL, Postgres), API, continuous integration
* Knowledge of peer-to-peer distributed networks
* Know how to deploy and configure Blockchain nodes such as Bitcoin, Ethereum, EOS
* Knowledge of front-end frameworks and technologies (e.g. React.js, Vue.js, Mobx, Redux) would be a plus.

### Responsibilities

* Research, design, implement, and maintain all decentralized finance systems incubated/supported.

* Work closely with product managers, designers, strategists, DevOps engineers, security engineers, and quants to ensure the high-quality systems by following the product and technical standards and deliver to the market on time.

### Contact
* Tel: 0334 532 210
* Mail: nhuhoahr@tulpo.vn
* Skype: leuhoavc_1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
