### ISSUE TITLE
Tulpo Software - Senior Backend Game Developer - Hanoi - Fulltime

### ISSUE THREAD

**Issue by Locnguyen4696** [awesome-jobs/vietnam#2803]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Up to $2500/month

## Requirements
-	Have more than 3 years of experience in Back-end program with languages: NodeJS, Golang, Rust and experience in making games - multiple players.
-	Experience work with MySQL, MongoDB, Redis (Kafka or RabbitMQ)
-	Experience in building and managing microservices architecture.
-	Knowledge of Amazon Web Services (AWS), CI/CD is an advantage.
-	Able to work under pressure to meet the requirements of time and product quality.
-	Can use Docker, Nginx
-	Proficiently use Git to manage source code.
-	Able to work in groups as well as independently.
-	Have good logical thinking, ability to evaluate, update and approach new technology quickly.
-	Good ability to read and understand English.

### Responsibilities
-	Design, build, analyze, and repair large-scale systems globally.
-	Requirements analysis, detailed design, project development planning.
-	Participate in the design and evaluation of the source code, ensuring the product standards set by the company.
-	Team management, support team members to develop skills.
-	Work with product managers to ensure compliance with product specifications and features.
-	Actively feedback and contribute ideas to improve product quality.
-	Provide code documentation and other inputs to technical documentation.

### Contact
* Tel: 0334 532 210
* Mail: nhuhoahr@tulpo.vn
* Skype: leuhoavc_1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
