### ISSUE TITLE
Employment Hero - Database Developer - Remote - FT

### ISSUE THREAD

**Issue by luong-komorebi** [awesome-jobs/vietnam#2805]
## Location

* We are a remote first company, so we dont require talents to be working in an office
* We do offer an office in Saigon if you are interested in separating your working place from your ordinary life

## Salary Expectation and Benefit

- **up to $8000/month** 
- 20 annual leave days
- 1 Leisure Rules day
- Top private healthcare package (Included your spouses and children)
- Work From Home Allowance
- USD 500/ annual/ person for books/ tech conferences/courses
- USD 500/ annual/ person for English learning
- Parking fee funded by company
- Lunch allowance for every working day
- Australian Trip for who are eligible
- Very attractive Referral Bonus

### Essential:

- Proven track record of designing and developing database solutions, with solid understanding of SQL-based database structures, theories & practices
- 5+ years designing, running and optimising large and complex database systems on a PostgreSQL platform
- Knowledge and experience running databases within the AWS cloud platform (AWS RDS, AWS Aurora)
- 3+ years of programming experience with proficiency in one of the following languages: C, C++, C#, Go, JavaScript, Python, **Ruby**
- Experience within a microservices-based architecture and its influence on database design
- Strong communication and written skills
- Excellent troubleshooting and problem-solving skills
- Bachelor's degree in Computer Science, Software Engineering or equivalent

### Bonus:

- Experience working with and managing non-SQL database platforms

### Responsibilities

- Analysing, maintaining and optimising Employment Hero databases
- Ownership and reporting of performance metrics of SQL and non-SQL databases
- Regular identification and improvement of slow-running queries and related optimisations
- Work closely with Engineering team to improve applications and establish best practices for database performance and concurrency
- Drive currency and upgrades of database platforms

### Why it would be awesome to work with us

As a business building products to make employment easier, we are/did:
```
* Deloitte Technology Fast 50 2020, ranked `#42` in Australia
* LinkedIn Top 10 Startups 2020
* Raise $140 million in a Series E funding round, led by global venture capital firm. This brings our valuation to $800 million.
* Raise $22M Series C Round led by Seek July 2019
* Raise $8 mill series B round led by Seek and OneVentures
* Deloitte Technology Fast 50 2019, ranked `#20` in Australia
* GetApp Category Leader Q1 2019
* Deloitte Technology Fast 50 2018, ranked `#12` in Australia
* HRD Gold Medalist - Human Capital Management Systems 2018
* HRD Gold Medalist - Rewards and Recognition Service Provider 2018
* HRD Rewards and Recognition Employer of Choice 2018
* LinkedIn Top 25 Startups 2018
* EY Entrepreneur of the Year National Finalist 2018
* Dynamic Business Top 10 Entrepreneurs, our CEO Ben Thompson ranked `#2`
* BRW Most Innovative Companies 2015
* Anthill Smart 100 List 2015
* Startup Daily Top 50 Emerging Leaders 2015
* HRD Employer of Choice Award 2015
* Aon Hewitt Best Employers 2013
```
and these achievements would not be possible without a sustainable platform where we hold a high standard for our codes, our infrastructures and our process. We look forward to sustaining and raising the bar as there are definitely a lot of room to grow and improve

### Contact

- Homepage: employmenthero.com
- Workable link: https://apply.workable.com/employment-hero/j/5A6555B155/ 
- Email: `luong.vo@employmenthero.com`

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
