### ISSUE TITLE
Base.vn - PHP Developer - Hanoi - Fulltime - 2021

### ISSUE THREAD

**Issue by thuthuyhr** [awesome-jobs/vietnam#2807]
**## Location**

* Hanoi, Vietnam

## **Salary Expectation**

* $1500/month

## **Requirements**
* PHP
* HTML/Javascript.
* MySQL
* jQuery, Redis, NoSQL, socket

Great power comes with great responsibilities!

### **You’ll be responsible for**

* Requirements analysis, project development planning.
* Participate in the design and evaluation of the source code, ensuring the product standards set by the company.

### **Contact**
* Phone: 038 7928 068
* Skype: thuthuyhrm

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
