### ISSUE TITLE
Money Forward Vietnam - Lead/Senior Frontend Engineer - HCM - FT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2809]
## Location

* Saigon, Vietnam
* 100% online working temporarily due to Covid19

## Salary Expectation

* $1400 - $3000

## Requirements
* Education: Bachelor of IT or equivalent
* Language: Good English communication

### Must Have

* 4+ years experience of development in frontend.
* Strong knowledge of HTML/CSS and JavaScript.
* Have good sense of UX/UI.
* Experience with organizing CSS (e.g. BEM)
* Experience with React/Vue.js.
* Experience with TypeScript.
* Experience with testing framework (e.g., Jest, Mocha, Ava)

### Ideally

* Motivation to learn new programming languages.
* Backend development experience is a big plus (e.g., Ruby on Rails, Laravel, Express.js, django)
* Experience with CI/CI (github workflow, Circle CI) and infrastructure (AWS, Heroku) is also a plus.

### Responsibilities

* Keep our services well maintained
* Improve user experience

### You can bring

* A good sense of UI/UX

### Why it would be awesome to work with us

* No probation applied for technical positions (all levels)
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee

### Interesting engineering projects
* Develop brand-new services for the Japanese market with teams in Japan
* Develop new features in personal financial management service which has No.1 market share in Japan

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009
Phone: 0906 516 291 (Direct call/Zalo/WhatsApp/Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
