### ISSUE TITLE
MySQUAR - Android Engineer - HCM - FT

### ISSUE THREAD

**Issue by ThaoMySQUAR** [awesome-jobs/vietnam#281]
## Location
- 246 Cong Quynh, District 1, HCM, Vietnam.
## Salary Expectation
- Above 1000$
## Requirements
- From 2 years experiences.
- Material Design
- Best tools out there: Android Studio, Fabric, New Relic
- Smooth sailing with Github, code review, unit test, Gradle and Jenkins
- We are not afraid to apply new design patterns and concepts like RxAndroid, MVVM, MVP
- We are agile and customer-oriented. We do a lot of usability testing, A/B testing for new features
## What you get
- Love from the team
-  A competitive salary
- Full health benefits and social insurance
- A training budget
- A macbook and a 21&quot; screen
- ESOP
- Possible travel to Myanmar to meet users and the team as well as Singapore
- Lots of cool stuff to relax (who said Foosball?)
## The recruitment process goes this way
- You send us a resume and tell us why you&#39;d love to work with us.
- The team reviews it and sends you a questionnaire and schedules a call.
- Once the call is done, a coding challenge is scheduled where you meet the team and do some
  coding with them.
- If everyone is happy, we will schedule the onboarding.
## Technologies used
- Git/Github RxJava/RxAndroid IntelliJ/Android Studio
- JIRA MVVM/MVP REST
- Scrum/Kanban Gradle Fabric
- JUnit Jenkins New Relic
## Work methodology:
- Code Reviews every pull request Version Control System - Github
- Pair Programming no Issue Tracking Tool - Jira
- Unit Tests yes Knowledge Repository - Github wiki
- Integration Tests's Tester(s) - QA team
- Build Server - Jenkins Agile management scrum/kanban
- Static Code Analysis no Freedom to choose tools
## Contact us

Would you like to know more? Resumes and questions, please get in touch with [thao@mysquar.com](), or
apply at: [http://vietnam.mysquar.com](http://vietnam.mysquar.com)

**Comment by rhacker** [comment]
```
Must Have

Be able to fly
Be able to dodge bullet
```
Are you sure ?

**Comment by checkraiser** [comment]
@ThaoMySQUAR 
- About Location: You can provide more details about address ?
- About Salary: A serious position needs more serious salary description than the `????`
- About Skills: You should provide more details about skills here, so that both applicants and you could expect from each other.
- About Responsibilities: It's too general for what could be called `responsibility`
- About `You Can Bring`: Why not `Your benefit` ?

**Comment by ThaoMySQUAR** [comment]
Sorry we just updated the article
