### ISSUE TITLE
Vietneer - Intern - Singapore - Remote

### ISSUE THREAD

**Issue by sonle-creator** [awesome-jobs/vietnam#2811]
Vietneer.community is a community built by Vietnamese for Vietnamese software engineers living in Singapore. We are looking for an intern to help us build the first version of the website for the community.

## Location
* Vietnam
* Remote

## Salary Expectation

* $15- $30 / hourly depending on experience.

## Requirements
* Our website is built using Ghost, the open-source CMS tool
* NodeJs, MySQL
* Handlebar templating
* HTML, CSS
* Familiar with software engineering or related fields 
* Software engineering/maths students are welcome

### Must Have

* Be able to be independent with minimum supervision
* Be able to pro-active in problem solving
* Love community building work 
* Bonus point if you like writing especially about career development

### Ideally

* Experience with Handlebar or similar templating engine
* Have worked with Ghost open-source blogging tool even for a side project

### Responsibilities

* Develop the integration of 3rd party tools available on Ghost marketplace to streamline the experience for software engineers, students when they participate in activities organized by our community.
* Customize the Ghost source on the front-end side to make the website be responsive on cross devices.

### You’ll be responsible for

* Building the Vietneer.community website

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us
* You will be working with experienced Vietnamese software engineers working at big tech companies in Singapore, they are on the board of ex-co team for Vietneer.

### Contact
Homepage: Vietneer.community
Trollman: sonle_creator_at_gmail_dot_com

**Comment by longtm1810-vct** [comment]
I sent you an email. Hope to have contact from you soon. Thanks a lot.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
