### ISSUE TITLE
 REMOTE - SENIOR FULLSTACK  (ReactJS,Nodejs ) - FT

### ISSUE THREAD

**Issue by janjan987** [awesome-jobs/vietnam#2814]
- Location
Remote

**- Salary Expectation
up to 4000$
Our technology stack: Reactjs, Nodejs, Apollo, GraphQL**

- Requirements
1. Fullstack experiences with senior level (3-4 years of experiences)
2. Experienced with Reactjs, Nodejs
3. Strong in algorithms and passionate about learning deep technical expertise.
4. Good English communication skills.
5. Agile and flexible start-up mindset

- Responsibilities
1. Be part of the Core Development team, responsible for development of fullstack (frontend, backend)
2. Learn new technologies, share with team members, and proactively apply new technologies to the development process.
3. Maintain code and write automated tests.

-  Why it would be awesome to work with us

1. Competitive salary
2. Macbook and dual monitors
3. 13th month salary
4. Opportunities to work abroad
5. Dedicated time for training
6. Flexible working time
7. Work from home or in the office
8. Flexible working space

Contact: 
Skype: giangtran0404

**Comment by revskill10** [comment]
@janjan987 Your skype contact seems invalid. PLease recheck.

**Comment by janjan987** [comment]
> @janjan987 Your skype contact seems invalid. PLease recheck.

@revskill10 : thanks for reminding. But I re-check my skype is giangtran0404. Maybe 'cause of internet connection, the profile does not appear, you can re-check

**Comment by revskill10** [comment]
@janjan987 I'm sorry, but i couldn't find your skype name. Do you have email for me to contact ?
Thanks.

**Comment by janjan987** [comment]
@revskill10 : can you share your skype ? I will contact you via your skype. Thanks

**Comment by revskill10** [comment]
@janjan987 My skype is revskill

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
