### ISSUE TITLE
DXC Technology Vietnam – Java Intern – Work from home – FT

### ISSUE THREAD

**Issue by ThamH7** [awesome-jobs/vietnam#2815]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* 5,000,000 VND/month

## Requirements
•	New graduated students from Universities who pursuing career Java Programmer Analyst/Developer
•	Bachelor’s degree in Computer Science, Software Engineer, IT or equivalent
•	English Level: Intermediate
•	Full-time participation is required (Monday through Friday, 9:00AM – 6:00PM)
•	Commit to working at DXC Vietnam for at least 2 years

### Responsibilities

You will be trained Java and related technologies, DXC product and the domain knowledge by our experts.

### Why it would be awesome to work with us

After the training, you will be able to work as a Java Developer at DXC where you can further advance your career.

### Contact
Homepage: http://www.dxc.technology/vn_en
Email: thamhohong.huynh@dxc.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
