### ISSUE TITLE
KYANON DIGITAL - PYTHON ENGINEER - HCM- UP TO $2000

### ISSUE THREAD

**Issue by LamAnhVu** [awesome-jobs/vietnam#2816]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* UP TO $2000 or Negotiate

## Requirements
* Proven experience as a software engineer with NodeJS/ Python expertise
* Familiarity with one of NodeJS/ Python framework, and design/architectural patterns
* Familiarity with architecture styles/APIs (REST, RPC)
* Understanding of Agile methodologies and DevOps
* Excellent troubleshooting and communication skills
* Ability to work independently, as well as part of a large team
* BSc/BA in Computer Science, Engineering or a related field
* English

### Skills
* Python
* Django
* English

## Responsibilities
* Participate in backlog refinement/requirement analysis.
* Collaborate with internal teams to produce software design and architecture
* Write clean, scalable, and high-performance code using NodeJS/ Python programming languages
* Test and deploy applications and systems
* Revise, update, refactor and debug code
* Develop documentation
* Serve as a technical expert and provide support

## Why it would be awesome to work with us
* Bonus structure + 13th month Bonus.
* Flexible working time: only 8 hours required as continual working-time at the office.
* 12 days Annual leave.
* Coffee and snacks provided.
* Holiday celebrations and parties for team members and family.
* Company trip, team building activities.

## Contact
Homepage: https://kyanon.digital/
Mail: career@kyanon.digital (0359.189.555 - Ms. Anh)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
