### ISSUE TITLE
Backend Engineer (Java, Golang, Python)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#2818]
Cho Tot team is expanding to continuously innovate our marketplace ecosystem to better serve Vietnamese via advanced technology. We are looking for talented and passionate individuals to join our foundation software engineering team.  

You will be one of the few key talents who build and run services that are used by ten of millions of Vietnamese people. You will need to tackle highly scaled distributed systems, work in a highly automated devops environment on top of many open source, CNCF software. You will be supported by our solid SRE team to really craft the software and run the product that you are proud of and other engineers admire.  

Responsibilities:
Solve engineering problems to enable a smart Marketplace ecosystem of products and services.
Design, Build, Run and improve backend services and framework of creating microservices.
Manage individual project priorities, deadlines and deliverables.
Improve engineer efficiency with common libraries, tooling and platforms.

Your skills and experiences:
 At least 2 years of backend development experience
Experience working with one or more from the following: web application development, Unix/Linux environments, distributed systems, developing large software systems.
Experience in Golang or confidence that you can pick it up in no time.
Solid production experience with one or more general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6.
Experience with two or more data systems but not limited to: Postgres, Mongodb, Elasticsearch, Redis, Kafka, Cassandra.
Experience with Docker, Kubernetes.
Familiar with Microservices, event driven architecture.
Understood, practice programming design patterns and SOLID principles
BA or MA degree in engineering, computer science or other technical related field. Or formerly competitive programmers.

Why you'll love working here
Sports club: Running, football, badminton 
Challenging working environment with attractive domain as ecommerce
Join plenty of Sharing and Learning activities as part of our initiatives to contribute to the tech community in Vietnam
Get 15 days of annual leave and 5 days of sick leave per year
Health insurance for employee and their family members
Get a Macbook Pro as your workstation
Get 13th month salary and annual performance bonus
Participate in regular team building activities and company parties
Get opportunities to attend training courses abroad

Skype: tremlobisi94
Mail: anhhoang@chotot.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
