### ISSUE TITLE
Quod AI Vietnam - Java Developer Intern - Remote/Saigon - FT/PT

### ISSUE THREAD

**Issue by QuodAIJobs** [awesome-jobs/vietnam#2819]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* At the market rate

## Requirements

* Experience with Java
* Good understanding of micro-services
* Relevant experience with Google Cloud or AWS or Azure.
* The ability to learn and iterate quickly.
* An obsession with agile and lean principles (GitHub, Trello).
* Prior development of JetBrains plugin would be a plus

### Education and Experience

* Strong verbal and written communication skills in English.

### Responsibilities

* Work closely with the product team to develop and maintain JetBrains plugins for our core-product.
* Work on the implementation of new features, leaving things properly implemented, well documented and delivered on time.
* Always be on the lookout for opportunities to create and improve. From our development process, up to final user’s experiences.

### Contact
Homepage: [https://www.quod.ai/](https://www.quod.ai/)
[Apply here](https://forms.gle/rxLvZZFWTSgW68sx7)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
