### ISSUE TITLE
Data Engineer

### ISSUE THREAD

**Issue by diepdt** [awesome-jobs/vietnam#282]
## Sentifi
Sentifi is the leading platform to access, monitor, and collaborate on the wisdom of the financial crowd. This can help participants in the financial markets to be closer to the heartbeat of market stakeholders and eventually do better long- and short term investment decisions. To understand what the financial crowd say about different companies and financial products is also valuable information for professionals involved with Investor Relations, Corporate Communication and Marketing of Financial Products. Also for journalists and news publishers, the wisdom of the crowd is gaining more importance every day and cannot be ignored anymore.
## Location

* 77 Tran Nhan Ton, District 5, Ho Chi Minh City

## Salary Expectation

* Attractive

## Requirements
* Python, Java or Scala
* Big Data
* 1+ years Software Engineering experience

### Must Have

* Bachelor or higher degree in Computer Science, Software Engineer

### Ideally

* Experience with Elasticsearch, PostgreSQL, Mongo, S3
* Familiar with Big Data framework: Hadoop, Spark, Akka,..
* Familiar with Streaming system: Storm, Spark Streaming,..
* Familiar with message queuing system: RabbitMQ, Kafka,...

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a Semantic Engine that analyze million messages per day.

### You can bring

* A good eyes for design
* A good analyis skill

### Contact

Diep Dao: diepdao.cs@gmail.com (+841672159019)

**Comment by joneslee85** [comment]
Thanks for posting with us.

Can you please update your post format so that the title comply with the [guideline](https://github.com/awesome-jobs/vietnam/blob/master/README.md)? Furthermore, can you please provide your company details? Job post does not have detail information about the companies and if the poster does not represent the HR of the company, it is considered invalid.

**Comment by joneslee85** [comment]
I am closing this job post because I haven't seen any amendment made for the last 2 days.
