### ISSUE TITLE
FETCH TECHNOLOGY - 02 Fullstack (React JS, Node JS) - HCM/HN

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2820]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/130891123-9d2d9471-1400-4217-8aa2-90ac2a6c1fea.jpg)

# HCM/HN

# 1,000 - 2,000 USD

# INTRODUCTION
**a. About Fetch:**
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client**

Our client is one of Singapore's six autonomous universities and their mission is to provide lifelong education that equips learners to serve society. With over 15,000 students, they offer an applied education. They are aimed at both newcomers and adult learners, with a focus on the social sciences.
They adopt a flexible and practice-focused learning approach and offer more than 70-degree programs in various disciplines. Their students eligible undergraduate programs enjoy government subsidies and access to Government funds, tuition loans, and academic loans
# RESPONSIBILITIES
**Application Development**

* To provide, recommend and evaluate various possible solutions and clearly communicate the cost and benefits of the various solutions.
* To design, develop and continuously enhance software applications.
* To document software applications to serve maintenance requirements on the system.
* To align system design and development to organizational standards and best practices for security and development. 
* To ensure systems are robust, available and scalable as needed. 
* To perform peer code review.
* To ensure the technical feasibility of UI/UX designs.

**Maintenance**

* To maintain software applications and support user inquiries and requests.
* To troubleshoot errors and issues.
* To perform bug fixes and data patching.
* To perform system upgrading and enhancement.

**General**

* Innovative and flexible. 
* Able to collaborate with other team members and stakeholders on various projects.
* Able to work independently.
* To plan and budget for software development.
# REQUIREMENT
* Bachelor’s Degree in Computer Science/Information Technology/Software.
* At least 3 years of software development experience and minimum 3 complete SDLC projects.
* Experience in Full-stack development, object-oriented analysis & design, building web applications and familiar with the following technology:
* Application Tier: Node.js, React.js and Restful Web Services, JSON, XML, etc.
* User interface Tier: responsive user-facing web interfaces for Web and mobile using HTML5, CSS3, Material UI and JavaScript. 
* Database Tier: Relational database like MySQL or Object-Relational database (No SQL Db) is required.
* Server Tier: Amazon Web Services (EC2, beanstalk and RDS) along with basic Linux or Windows Server administration. 
* General understanding of RESTful API architecture.
* Solid understanding of the full web technology stack, including protocols and Web server optimization techniques (e.g HTTP, cookies, headers, asset loading/caching).
* Proficient understanding of cross-browser compatibility issues and ways to work around them.
* Good interpersonal skills. 

# WHY YOU‘LL LOVE WORKING HERE
* Being a Full-stack developer at Fetch Technology, you will experience a youthful, flexible and creative work environment.  

* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese. 
* Extensive on job training, you will always have a chance to work with new emerging technologies. 
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law. 
Birthday, Wedding, Newborn bonus.
* 12-day annual leave per year. 
* 13th-month salary. 
* PVI Health Care.
* Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).   

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
