### ISSUE TITLE
FETCH TECHNOLOGY - Middle Frontend Engineer (VueJS) - FT - HN

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2821]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/130891258-863c8818-7ddf-4fc0-8e3c-07ab3bcca9f4.jpg)

# HN

# 700 -  1,300 USD

# INTRODUCTION

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily on the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client**

This is a branch of CAS holding Financial Group (Japan & Singapore). In 2020-2021, realize the outstanding potential of talented IT human resources in Vietnam, as well as the untapped potential in the field of Blockchain and Cryptocurrency globally. CAS Holdings Pte Ltd has been boldly investing and building a research and development center for Blockchain and Cryptocurrency related services and products in Hanoi.

Our Vision: Use disruptive technologies that can change the world – Create globally recognized products and services that are trusted and used by users.

**Core values:**

- Achievements: Create valuable results for yourself, colleagues, customers, partners...

- Maturity: Always growing up, becoming more stable in each step

- Optimism: Always maintain the spirit of optimism, eagerness on the path of discovery, construction and development

- Mutual support: Overcoming individual views and thinking, supporting each other to develop together, creating spillover and synergy

- Nature: Find the essence, consider all problems, solve from the root

# RESPONSIBILITIES

* Develop and maintain front-end web applications based on Javascript, PHP, Vuejs, Docker for cryptocurrency exchange and binary options exchange.
* Programming feature modules according to design analysis.
* Participate in building solutions, writing software according to the company's requirements.
# REQUIREMENT

* Have 3+ years of experience or confidence with equivalent qualifications.
* Proficient in Javascript programming language, Vuejs framework.
* Proficient in HTML/Javascript/jQuery/CSS/AJAX.
* Proficient in building frontend web applications, microservices.
* Can communicate in English.
**Nice to have:**

* Knowing how to use Docker for dev, testing and production environments.
* Proficient in PHP, laravel.
* The ability to lead frontend engineers in the team.
# WHY YOU‘LL LOVE WORKING HERE

* Attractive starting salary, competitive, commensurate with ability and work experience from $700-$1300 NET.
* 13,14 month salary + Soft bonus 2 times/year (0.8 ~ 1.2-month salary depending on contribution).
* Consider salary increase once a year according to capacity and work efficiency.
* Enjoy social insurance, health insurance, unemployment insurance according to the regime promulgated by the state.
* Maternity allowance for female employees.
* Trained, sponsored to participate in courses to develop into Key member, Manager of the Company.
* Flexible working time (core time from 9:30 to 16:30).
* Annual travel mode and regular teambuilding activities.
* Be challenged in big projects, have the opportunity to assert yourself and develop a career.
* Working in a friendly, dynamic, creative environment, encouraging personal development core.
# WORKING HOURS & LOCATION

* Working Hours: from Monday to Friday, flexible working time (core time from 9:30 to 16:30).
* Location:13th floor, Block B, Song Da Building, Pham Hung street, My Dinh I ward, Nam Tu Liem district, Hanoi city.

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
