### ISSUE TITLE
FETCH TECHNOLOGY - Java Developer - FT - HCM/HN

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2822]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/130892073-14c24dbc-d4c0-4b9d-b056-a9ccbac81df2.jpg)

# HCM/HN

# 1,000 - 2,000 USD

# INTRODUCTION

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily on the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client**

Our client is creating an empowering and revolutionary F&B platform that seamlessly integrates all technological solutions associated with the industry, resulting in an ecosystem that allows merchants to focus on the main task of running their business efficiently.

Their vision is to build an innovation platform that empowers the people they work with to turn their dreams into reality. One key ingredient of this is having the right technical minds – and they’re looking for someone like you to fill this role. If you think this is a match made in heaven, read on.

As their Java Developer, you will work both on product features as well as on building their team and capabilities. You will be responsible for features development and launch and be the technical pillar of their development team. By joining their team, you will have the opportunity to be part of innovative technology products that have a real business or social impact.

# RESPONSIBILITIES

* Write elegant, semantic, and easily maintainable code.
* Work side-by-side with the product team to develop high-quality user interfaces. 
* Work with the business analysts to create and maintain a robust framework to support existing products.
* Create compelling device-specific user interfaces and experiences. 
# REQUIREMENT

* Minimum 3 years of current, hands-on experience in software and/or web development with a Bachelor's or Master's degree in * Computer Science, Information Systems, or equivalent. 
* Ability to pay excessive attention to application quality and ease of use.
* Ability to write good unit tests.
* Passion for intuitive user interfaces.
* Strong Java / Groovy abilities. 
* Good understanding of MySQL, Hibernate, and ORMs.
* Good understanding of RESTful services.
* Reasonable HTML, CSS, JavaScript abilities and front-end frameworks like VueJS.
* Comfortable in using Git for version control, ticketing systems and other supplementary tools 
* Enjoy communicating with people. 
* An aptitude for learning and having lots of fun.
# WHY YOU‘LL LOVE WORKING HERE
Being a Java Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment:

* Attractive salary and annual salary review.
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* With extensive on-the-job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th-month salary.
* PVI Health Care.
* Enjoy diversified activities: Free snack, Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 
# WORKING HOURS & LOCATION

* Working hours: 5 days/week (work in rotational shifts, discuss more in the interview).
* Location: 
+ HCM: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC. 

+ HN: 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Hanoi. 

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
