### ISSUE TITLE
DXC Technology Vietnam – Junior Frontend - Angular Developer – Work from home – FT

### ISSUE THREAD

**Issue by ThamH7** [awesome-jobs/vietnam#2823]
## Location

* Etown 5 Building, 364 Cong Hoa St, Tan Binh Dist, HCMC
* Remote

## Salary Expectation

* Negotiable

## Requirements
•	Bachelor’s degree in Computer Science, Information Technology, Software Engineering or related technical field
•	01 year of experience
•	Basic English communication skills
•	Sufficient knowledge in Object-oriented programming concept
•	Ability to learn in a short time and work under pressure
•	Good analytical and communication skills
•	Be able to work independently and in a workgroup. 

### You’ll be responsible for

•	Develops and enhance software applications through coding and testing.
•	Involves in code reviews and training.
•	Delivers highest quality software by creating unit test plan and testing code thoroughly.
•	Adept with the tools, applications, and processes used for software development.
•	Implements solutions as designed in technical documentation specification and coding standards.
•	Creates project documentations and coordinate technical issues.
•	Reports to a technical lead / project manager
•	Knows the business rules and concepts, software specifications and designs provided by the technical lead and apply them in completing the assigned task.
•	Actively search in new technologies, tools for working purposes

### Contact
Homepage: http://www.dxc.technology/vn_en
Email: thamhohong.huynh@dxc.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
