### ISSUE TITLE
Star Global - Junior Android Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2824]
## Location

Ho Chi Minh City, Vietnam (Flexible to work between home and office)

## Salary Expectation

* Very attractive for juniors!

## Qualifications & experience:

- 2+ years of Android experience;
- Good programming knowledge of Java/Kotlin;
- Understanding of algorithms, data structures, complexity and optimization;
- Knowledge of development tools, environments and utilities;
- Familiar with Material Guidelines;
- Proactive goal-focused mindset and the desire to create high-quality products;
- Passion for continuous learning and adapting to new technologies;
- Good written and spoken English as well as good communication skills.

_We appreciate:_

- Knowledge of mobile application architecture, design patterns, understanding of refactoring techniques;
- Knowledge of CI, CD, TDD, Unit and UI Testing;
- Familiar with Agile development methodologies (Scrum, Kanban);
- Knowledge of the latest trends in the mobile industry and platforms;
- BSc/MSc degree in Computer Science;
- Your own apps on Google Play Store.

### Responsibilities

We are looking for a Junior Android Engineer to join our team! You will handle the entire product development or its significant part. You will communicate with the customer, determine the product functionality, define the architecture and estimate the overall work.
Our Senior Engineers will work with you to make sure you are delivering quality works for the project!

### Why it would be awesome to work with us
▪ Impressive salary package
▪ 20 days of annual leaves, 01 Christmas leave and 01 birthday leave
▪ Flexible working hours with 05 working-from-home days in a month
▪ Global consulting environment & opportunities to learn and use trending tech stacks
▪ Latest MacBook Pro & monitor or you can Bring your own Device, we'll compensate you monthly!
▪ Full social insurance and private healthcare insurance from PVI
▪ Free English classes and many more to come!

### Contact
JD Page: https://star.global/careers/junior-android-engineer-6103/
Recruiter: quyenphan@star.global (Skype: pmq0406)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
