### ISSUE TITLE
InnomizeTech - Technical Leader - HCM - FT

### ISSUE THREAD

**Issue by thanhthi** [awesome-jobs/vietnam#2825]
## Requirements
* At least 2-5 years of professional experience in Technical Lead/ Technical Project
Management.
* Have experience with any frameworks/ languages of software development such as
Javascript, Java, Nodejs, Angular, Reactjs, Vuejs,..
* Experience with Docker containers and Microservices.
* Proficient communication in English.
* Have good documentation and presentation skills.
* Ability to multi-task and manage various project elements simultaneously
* Strong familiarity with project management software tools, methodologies, and best
practices
* Experience and success with truly Scrum/Agile development teams.
* People management skills, project management skills, organization skills, negotiation
skills, time management skills.
* Be able to manage client relationships and negotiate changes to commitments/
requirements.
* Strong knowledge in technical management, information analysis
* Wide range of domain knowledge: Banking, E-commerce, Insurance, Fintech, Logistic,
BlockChain (BitCoin)...

### Ideally
* Have PMP, CSM, PSM certification is preferred
* Basic knowledge about Cloud computing such as Amazon Web Services, Microsoft
Azure, or Google Cloud.

### Responsibilities
* You will be responsible for taking requirements, estimations, and clarifying the needs
with the project to define user stories and project plan.
* Serve as the program lead, responsible and accountable in the planning, development
and delivery of new projects and programs.
* Be responsible for building and training team members.
* Define and apply Agile/Scrum processes and train new team members.
* Work closely with international clients to clarify high-level specifications, estimate
efforts, support the business development team to meet client’s requirements.
* Gather, analyze, and translate business requirements into documents such as project
scope, project description, functional requirements, user stories.
* Work closely with all stakeholders to deliver projects on time and within budget.
* Manage changes to the project scope, project schedule, and costs.
* Oversee and perform risk management to mitigate risks.
* Create and maintain comprehensive project documentation.
* Build project team spirit by coaching, motivating, connecting team members toward
contributing to company and client’s success.

### Contact
Email: hr@innomizetech.com
Skype: thanhthi.hr
LinkedIn: https://www.linkedin.com/in/lethanhthihr/
Facebook: https://www.facebook.com/lethanhthihr/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
