### ISSUE TITLE
Cốc Cốc - C++ Software Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by CocCocRecruitment** [awesome-jobs/vietnam#2826]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1,200 - $2,000/month

### Must Have

* Solid knowledge of C++
* Knowledge of OOP
* Experience with Linux-based systems

### Ideally

* Work well with one or more of the server-side languages: PHP Python, Golang is a plus
* Good knowledge of algorithms and data structures

### Soft Skills
* Proactive seeks learning opportunities beyond current requirements
* Ability to self-study and overcome the weaknesses
* Good teamwork player
* Good communication skills in written and spoken English.

## Responsibilities

We are looking for talented developers to join our prosperous Browser Backend team. With the mission to be a team that designs, develops, and maintains backend products consisting of backend core systems, API services, web applications.
As a Browser Backend engineer, besides developing and maintaining back-end services of Cốc Cốc products (such as browser, business intelligence, etc), you will also cooperate with other teams to design and develop new web applications.
### You’ll be responsible for

* Work on one Back-end service for Browser that is written in pure C++.
* You can also take part in developing other features/tasks that are implemented with other server-side languages
* Developing new and supporting existing features for sales, platforms, search team, browser team, and others
* Searching and fixing/optimizing problems in developed products
* Pro-actively enhance our products
* Sharing knowledge and contribute ideas to have good solutions for new features & services

### Professional growth:
* What we are doing is difficult. This is why there are a lot of opportunities for you to learn and grow with support from a mix of learning & development programs
* You will work alongside talented team members who have a unique skill set and expertise in this market
* Coc Coc is a Vietnamese company but you will be working in an international environment with team members/partners/customers who are local and international

### Compensations and benefits:
* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, newborn child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 
 

### Working environment: 
* A culture of flexibility and responsibility, no dress code and annual Work From Home policy
* Exciting internal events to help you understand the whole business and make you part of the Cốc Cốc family
* Modern and cozy kitchens with plenty of snacks and coffee/tea bars every day, to make sure energy level is high when you need it
* There are many interesting hobby clubs to share your non-professional passions like English Club, Yoga, Football and many other clubs are forming ...

### Contact
Homepage: https://careers.coccoc.com/job/c-software-engineer-backend-browser
Giang Trịnh: giang.trinh@coccoc.com (Skype: jangin.kan)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
