### ISSUE TITLE
Data Engineer

### ISSUE THREAD

**Issue by Giang-Vo** [awesome-jobs/vietnam#2828]
## Location

* Saigon, Vietnam
* Quận1

## Salary Expectation

* 1000-2500$
## Requirements
Reporting to the Chief Technology Officer you will be responsible for :
* Design and implement data models, data-marts, and datasets on a Hadoop-based data warehouse and data hub
* Interface directly with business and systems subject matter experts to understand analytic needs and determine logical data model requirements
* Develop and implement ETL processes across Hadoop, BI systems, and databases
* Work closely with data architects to identify common data requirements and develop shared solutions
* Develop close collaboration with senior analysts and data owners across multiple business domains
* Maintain data modeling standards and ETL best practices
* Support data model and ETL solutions in production

## Skills
*Elixir, Python, Ruby, or Go
### Must Have
*Python
### Responsibilities
* Have a B.A./B.S. and 3-5 years of relevant work experience; or an equivalent in education and experience
* Hands-on experience with AWS Stacks, SQL, etc.
* Possess strong analytical skills with the ability to analyze raw data, draw conclusions, and develop actionable recommendations
* Proven track record of excellence and consistently delivered the past project successfully
* Hands-on experience with AWS, Azure, GCP

### WHY YOU'LL LOVE WORKING HERE
* An opportunity to learn at a company that is growing for regional scale (South East Asia)
* Working in a young, super talented and supportive team environment
* Attractive salary (Up to 2500 USD)
* Company trip, team building
* PTI Insurance
* Macbook Pro for Developer

### Contact
Homepage: https://www.onpoint.vn/
Send CV to hangiang.vo@onpoint.vn

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
