### ISSUE TITLE
[LARION] - [Data Analyst] - [HCM] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#2829]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 1500$ - 2000$

### Requirements

* Experience in handling and working with database
* Experience with SQL query
* Familiar with Python programming
* Be dedicated and self-disciplined with a strong work ethic and willing to help others

### Responsibilities

You will be one of the key contributors in our organization and join high quality system solution following well-known workflows and best practices. Being our data analyst, you will focus to:

* Monitor, develop, implement, forecast and drive the strategic direction, growth, performance management, and sustainability of databases
* Provide database support to development teams and business teams, developers
* Perform all lifecycle activities relating to databases
* Proactive response to incident and problem management, analyzing issues and working with wider technology teams to resolve anomalies, restore services, and resolve problems
* Perform research on related or assigned technologies, domains and techniques that are relevant to the practice or assigned by analytical leaders

### Why it would be awesome to work with us
* Attractive salary and benefits (13th Salary, Project/ Department Bonus, Outstanding employee of the quarter and the year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Lunch allowance, Free parking
* Various training on technical and soft skills, Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.

### Contact
Please send CV via email: ngocttb@larion.com
For further information, please contact via Skype: ngoctranthibao│Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
