### ISSUE TITLE
[LARION] - [Data Engineer] - [HCM] - [FT]

### ISSUE THREAD

**Issue by tranthibaongoc** [awesome-jobs/vietnam#2830]
## Location

* QTSC Building 1, Quang Trung Software City, District 12

## Salary Expectation

* 1500$ - 2000$

### Requirements

* At least 1 year of experience in handling large data sets and working with structured, unstructured datasets
* Familiarity and experience with database systems
* Experience with Python programming
* Be dedicated and self-disciplined with a strong work ethic and be willing to help others

### Responsibilities

We are looking for a great and proficient data engineer. You will be one of the key contributors in our organization and join high quality system solution following well-known workflows and best practices. Being our data engineer, you will focus to:

* Participate in a data engineering team which is responsible for data landscape, including data architecture, data extraction and collection, data manipulation, feature engineering and other data-related developments
* Proactively perform research on related or assigned technologies, domains and techniques that are relevant to the practice or assigned by analytical leaders
* Build scalable and reliable ETL pipelines and processes to assemble data from a large number and variety of data sources
* Implement solutions and processes for management across data quality metrics, metadata, lineage, data access rights and business definitions
* Collaborate with other teams to enhance capabilities of internal analytics

### Why it would be awesome to work with us
* Attractive salary and benefits (13th Salary, Project/ Department Bonus, Outstanding employee of the quarter and the year, Seniority award, etc.)
* Performance appraisal twice a year
* Premium Healthcare and Accident insurance
* Lunch allowance, Free parking
* Various training on technical and soft skills, Teambuilding, Company trip, Year-end party, etc.
* Support for personal loans such as: home loan, vehicle loan, tuition fee, etc.

### Contact
Please send CV via email: ngocttb@larion.com
For further information, please contact via Skype: ngoctranthibao│Zalo: 035.6945.706

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
