### ISSUE TITLE
Liquid Vietnam - Ruby Developer - Hochiminh - FT

### ISSUE THREAD

**Issue by rubytranquoinevn** [awesome-jobs/vietnam#2831]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $1,500 - $3,000

## Requirements
* Python
* C++
* Java
* Ruby

## Skills
* More than three years of professional experience with developing scalable and resilient services in any language.
* Proficiency in the English language, both written and verbal, is sufficient for working in a multi-national environment.
* Capability to clearly and concisely communicate complex technical, architectural, and organizational problems and propose thoroughly iterative solutions.
* A mindset of ownership and be proud of what you are building.
* Understanding of asynchronous programming techniques, design patterns, algorithmic complexity
* Love automation testing

### Must Have

*(Python, Java, C++…) and good at algorithms

### Responsibilities

* Involve and have a saying in every part of a project: from idea, research, MVP, enhancements, monitor, and measurement.
* Confidently ship moderately sized features and improvements.
*Solve technical problems of high scope and complexity with the simplest solution possible.
* Work closely with the Product team to define and validate requirements.
* Consider user experience throughout your work.
*Help define and improve our internal standards for style, maintainability, and best practices for a high-scale web environment. Maintain and advocate for these standards through code review.

### Why it would be awesome to work with us

* Provided Macbook Pro
* Daily snacks & drinks
* promote an open and flexible working environment 

### Contact
Homepage: https://www.liquid.com/jobs/?gh_jid=4187275002
Trollman: ruby.tran@quoine.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
