### ISSUE TITLE
TRS Sea - Fullstack Mobile Developer Leader - Ha Noi - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2832]
## Location

* Hanoi, Vietnam
* Fulltime Job

## Salary Expectation

* Salary: ~40M/month

## Requirements
* 1 year working experience as a Full Stack Mobile Developer
* Backend: Understanding of Cloud service (AWS), have experience in Node.JS
* Frontend: React.JS, Rest API
* Have knowledge about React Native is a plus
* Good problem solving skills, logical thinking

### Responsibilities

* Participate in the process of designing, developing features and functions of the application.
* Conduct discussions, build potential applications with the goal of having hundreds of millions user.
* Improve the Dev team's operation process
* Support, monitor, coordinate team members and operational processes

### Why it would be awesome to work with us
* Salary: negotiable according to experience and capacity (up to 40 million)
* Clear promotion path, self-development in a dynamic start-up environment
* 5 official working days/week (Monday - Friday)
* 1 day off/month, 12 days off/year
* Other regimes in accordance with the law

### Contact
* Email: diepnguyen@r-starsea.com
* Phone/ Zalo: 0374 118 602
* LinkedIn: https://www.linkedin.com/in/nguyen-diep-64963b166/
* Skype: Diep Nguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
