### ISSUE TITLE
TRS Sea - Frontend Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2834]
## Location

* Hanoi, Vietnam
* Fulltime Job

## Salary Expectation

* Salary: ~20M/month 

## Requirements
* 2+ years working experience in developing mobile dev. 
* Have knowledge about iOS - Swift & Android - Java 
* Capable of developing the app overall, except for the camera feature (Frontend Developer 1) 
* Or know how to use external SDK and self-develop camera module (Frontend Developer 2) 
* Have experience in React Native is a plus

### Responsibilities

* Analyze and develop application features as required
* Develop new ideas and applications
* Coordinate with other members according to project requirements

### Why it would be awesome to work with us
* Salary: negotiable according to experience and capacity (up to 20 million)
* Clear promotion path, self-development in a dynamic start-up environment
* Salary review according to ability
* 5 official working days/week (Monday - Friday)
* 1 day off/month, 12 days off/year
* Other regimes in accordance with the law

### How to apply: 
Send your CV/resume to my email: diepnguyen@r-starsea.com

### Contact
* Email: diepnguyen@r-starsea.com
* Phone/ Zalo: 0374 118 602
* LinkedIn: https://www.linkedin.com/in/nguyen-diep-64963b166/
* Skype: Diep Nguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
