### ISSUE TITLE
TRS Sea - Web Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2835]
## Location

* Hanoi, Vietnam
* Fulltime Job

## Salary Expectation

* Salary: ~20M/month 

## Requirements
* 2+ years working experience in developing web. 
* Understanding and having experience in React.JS, Rest API
* Capable of developing web projects, building front-end functions of Website, Web
Application like create plan page, homepage etc & event page in app etc

### Responsibilities

* Analyze and develop application features as required
* Develop new ideas and applications
* Coordinate with other members according to project requirements

### Why it would be awesome to work with us
* Salary: negotiable according to experience and capacity (up to 20 million)
* Clear promotion path, self-development in a dynamic start-up environment
* Salary review according to ability
* 5 official working days/week (Monday - Friday)
* 1 day off/month, 12 days off/year
* Other regimes in accordance with the law

### How to apply: 
Send your CV/resume to my email: diepnguyen@r-starsea.com

### Contact
* Email: diepnguyen@r-starsea.com
* Phone/ Zalo: 0374 118 602
* Skype: Diep Nguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
