### ISSUE TITLE
Quoine - Backend Ruby Developer (Java/Python) - Saigon - FT

### ISSUE THREAD

**Issue by Liquid-Quoine** [awesome-jobs/vietnam#2836]
## Location

* Saigon, Vietnam

## Job Description
* Involve and have a saying in every part of a project: from idea, research, MVP, enhancements, monitor and measurement.- Confidently ship moderately sized features and improvements.
* Solve technical problems of high scope and complexity with the simplest solution possible.- Work closely with the Product team to define and validate requirements.
* Consider user experience throughout your work.
* Help define and improve our internal standards for style, maintainability, and best practices for a high-scale web environment. Maintain and advocate for these standards through code review.

## Your Skills and Experience
* More than three years of professional experience with developing scalable and resilient services in any language.
* Proficiency in the English language, both written and verbal, is sufficient for working in a multi-national environment.
* Capability to clearly and concisely communicate complex technical, architectural, and organizational problems and propose thoroughly iterative solutions.
* A mindset of ownership and be proud of what you are building.
* Understanding of asynchronous programming techniques, design patterns, algorithmic complexity
* Love automation testing
* C++
* Java
* Python

_You'll stand out if you bring:_
* Strong experience with Ruby on Rails, Postgres, Redis.
* Familiarity with Domain
* Driven Design.

## Why You'll Love Working Here

**Health Insurance**
* 100% coverage for you and your wife/husband and kids.
* Provider: PTI Saigon
* Insurance benefits: Personal accident; Term-life due to illness, diseases, pregnancy; Hospital, surgical and dental treatment

**Annual Health Check-up**

**Money in your pocket - Working hard pays off**
* Meaningful performance-based incentives are distributed to you yearly based on the company business outcome and your performance rating, which plays a significant role in how much of the bonus amount you'll receive.
* Attractive project-based bonuses are granted to people who have significant contributions to the success of the projects. This type of incentive is defined depending on the performance of the project and individuals involved.

**We want you to achieve your fullest potential while working at Quoine:**
So, we've developed a range of related training courses for you to pick from. You can also get discretionary funding to attend external training or speak at conferences, conventions relevant to our industry, and your expertise since we want you to be a leader in your professional community.

**Have your cake and eat it too - work-life balance**
* Paid Time-Off
* Do great things and recharge with
> * 15 days annual leave/year
> * 5 single days sick leave covered by company/year (without a doctor’s note)

**Work/Life:**
* **We want you to love where you work**, so we provide a creative workspace, inspiring people, and the latest tech to help you do your best work.
* **Daily snacks & drinks** provided at Pantry to keep you fueled anytime.
* We **promote an open and flexible working environment** where you are empowered to perform your best and are encouraged to give constructive feedback and innovative ideas to the development of the company and yourself.
* To help you have fun and bond with your colleagues, besides team **outing activities** organized as per the company's annual plan, we have Xbox One, Pool, Table soccer, etc. available in the entertainment place during off-hour.

### How to apply
Send your CV/resume to this email: Talent Acquisition Manager - ruby.tran@quoine.com

![223784807_126539376268240_4747164498492871248_n](https://user-images.githubusercontent.com/89761348/131300004-5f1f5a3f-98e3-418e-80da-34e09f867e71.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
