### ISSUE TITLE
Quoine - Full Stack Engineer NodeJS, C++ - Saigon - FT

### ISSUE THREAD

**Issue by Liquid-Quoine** [awesome-jobs/vietnam#2837]
## Location

* Saigon, Vietnam

## Job Description
We are looking for a capable Full-stack Developer responsible for building our applications supporting our global trading platforms. Scope includes everything between complex groups of back-end services and their client-end (desktop and mobile) counterparts

**Responsible**
* Work alongside other teams to translate application storyboards and use cases into functional applications
* Engineer and deploy data integrations, APIs, and other services on AWS infrastructure
* Ensure the best possible performance, quality, and responsiveness of the applications
* Identify bottlenecks and bugs, and devise solutions to these problems

## Your Skills and Experience
You might be a good fit if you:
* Are proficient in Ruby on Rails or C++, Javascript (ReactJS & NodeJS), HTML/CSS with a good knowledge of their ecosystems
* Have a solid understanding of object-oriented programming
* Are familiar with Amazon Web Services
* Enjoy writing clean, maintainable, teammate-friendly code, tests, and documentation
* Are comfortable engaging with vendors and solution partners on a highly technical level
* Find yourself at ease solving difficult problems with little direct guidance
* Experience with popular web application frameworks, such as Play and Spark
* Have a deep understanding of fundamental design principles behind a scalable application
* May not be deeply familiar with marketing technology, but you're motivated to learn
* Highly proficient in spoken and written English

## Why You'll Love Working Here

**Health Insurance**
* 100% coverage for you and your wife/husband and kids.
* Provider: PTI Saigon
* Insurance benefits: Personal accident; Term-life due to illness, diseases, pregnancy; Hospital, surgical and dental treatment

**Annual Health Check-up**

**Money in your pocket - Working hard pays off**
* Meaningful performance-based incentives are distributed to you yearly based on the company business outcome and your performance rating, which plays a significant role in how much of the bonus amount you'll receive.
* Attractive project-based bonuses are granted to people who have significant contributions to the success of the projects. This type of incentive is defined depending on the performance of the project and individuals involved.

**We want you to achieve your fullest potential while working at Quoine:**
So, we've developed a range of related training courses for you to pick from. You can also get discretionary funding to attend external training or speak at conferences, conventions relevant to our industry, and your expertise since we want you to be a leader in your professional community.

**Have your cake and eat it too - work-life balance**
* Paid Time-Off
* Do great things and recharge with
  * 15 days annual leave/year
  * 5 single days sick leave covered by company/year (without a doctor’s note)

**Work/Life:**
* **We want you to love where you work**, so we provide a creative workspace, inspiring people, and the latest tech to help you do your best work.
* **Daily snacks & drinks** provided at Pantry to keep you fueled anytime.
* We **promote an open and flexible working environment** where you are empowered to perform your best and are encouraged to give constructive feedback and innovative ideas to the development of the company and yourself.
* To help you have fun and bond with your colleagues, besides team **outing activities** organized as per the company's annual plan, we have Xbox One, Pool, Table soccer, etc. available in the entertainment place during off-hour.

### How to Apply
Send your CV/resume to this email:  Talent Acquisition Manager - ruby.tran@quoine.com

![223784807_126539376268240_4747164498492871248_n](https://user-images.githubusercontent.com/89761348/131300004-5f1f5a3f-98e3-418e-80da-34e09f867e71.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
