### ISSUE TITLE
Saigon Technology Solutions - .NET Developer - HCM - FT

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2838]
## Location

* 02 Nguyen The Loc, Ward 12, Tan Binh District, HCMC

## Salary Expectation

* Up to $2000 NET/month
* **Signing Bonus up to 20.000.000 VND for candidates who onboard before 1 Oct**

### Top 3 Reasons To Join Us

* Technical training sessions (internal-external)
* Attractive salary, benefits and signing bonus
* Premium healthcare insurance for employees and family

### Must Have

* Have **at least 3 years of experience** in .NET projects
* Web App/ Restful API, SPA
* MVC 5, Web API 2.2, Entity Framework
* .NET Core 2.0+, Entity Framework Core 2+
* SQL Server 2012+,  PostgreSQL, Cosmos DB
* Windows Server 2012+
* HTML 5, CSS3, Bootstrap 3 or 4
* Dependency Injection and Inversion (in **SOLID**)
* **Good verbal/non-verbal English**

### Nice to have

* WPF
* Fintech
* Angular2+, React JS
* Microsoft Azure / Amazon
* Algorithm knowledge
* Leadership skill is a plus

### Responsibilities

* **Work directly with US/ Europe/ Canada clients** to clarify requirements
* Assist with application architecture design and implementation.
* Adhere to and recommend improvements to project coding standards.
* Work in a team environment with shared code; disciplined use of source code control and process documentation.
* Solve technical problems

### Why it would be awesome to work with us

At **Saigon Technology Solutions**, we believe that "_Your success is our mission_", that’s why we build an excellent working environment along with exceptional benefits:

* Attractive salary and benefits (13th, **Salary review – twice/year**)
* Project bonus
* **Free English courses**
* **PVI health care program**
* Company trip every year
* Weekly happy hour
* The staff of the month/year reward
* Party celebration(Christmas, Birthday,...)
* Team-building activities
* Technical training sessions (internal-external)
* Weekly Knowledge Exchange
* A professional working environment with Agile – Scrum
* Sports clubs (football, badminton…)
* Enjoy Relax and beautiful Pantry in the company
* Periodic health examination

### Contact
Homepage: www.saigontechnology.com
Contact person: Kien Tran - Talent Acquisition Lead
Email: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
