### ISSUE TITLE
MCVGo - Java Back-end developer- HCM D7

### ISSUE THREAD

**Issue by hungmcvgo** [awesome-jobs/vietnam#2839]
## Location

* Saigon, Vietnam
* Fulltime
* District 7

### Company domain:
* Live Streaming
* Real-time Interactive
* Private Social Network

## Salary Expectation

* $1100-1500

## Requirements
* Java
* Nginx
* PostgreSQL/MySQL/MongoDB

### Must Have

* BA in Computer Science, Information Systems, or related field
* At least 2 years of working experience with Java 
* Good experience in API design & implementation
* Familiarity with Linux, MySQL, MongoDB, Nginx
* Good experience in understanding & applying Design Patterns/Design Principles
* Front-end or app development experience is a plus

### You’ll be responsible for

* Design, Build, Deploy, and Maintain software components for projects on Server side
* Analyze and improve efficiency, scalability, and stability of various system resources
* Practice disciplined software engineering (e.g. unit test, code reviews, gitflow)
* Write technical documentation
* Guide fresher or junior developers

### Why it would be awesome to work with us
* Dynamic, technological and Agile working environment
* Self-development: online technical seminar, career talk and various trainings on hot-trend technologies, languages and soft-skills
* Talented and enthusiastic fellows
* Creative office spaces with free coffee, snacks and table tennis, billiards
* 13th-month salary, Annual salary raise review
* Macbook 

### Contact
Mr. Hùng
hungvd@mcvgo.com
0936907925

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
