### ISSUE TITLE
Australia Product Company - Senior Mobile/Web Developer - HCM - FT

### ISSUE THREAD

**Issue by GiauRecruitmentConsultant** [awesome-jobs/vietnam#284]
### Location
* District 11, HCMC, Vietnam
* Full-time

### Salary Expectation
* 1,000 - 1,500$ NET ( Can negotiate base on experience)

### NIC Human Resources's Client
Our client a leading developer and supplier of cloud-based software solutions for Automotive Dealers and Manufacturers.

### Responsibilities
- Be able to analyze, design, code, test, document and implement new applications or enhancements to existing systems.
- Assess the impact of change requests, and develop solutions and mitigation strategies
- Apply the project design, system development and maintenance methodologies
- Interpret business requirements and provide systems/technical documentation
- Work as an effective team member; share knowledge and information with the team and assist others in meeting team priorities
- Working as part of a larger team to provide ongoing Production support to our customers and internal staff. This involves with investigating Production issues, find the root cause, apply the appropriate fixes or change requests and documentation.

## Requirements
- 6+ years commercial experience in .Net ( 3.5, 4.X) development in C#.
- Strong technical skills in ASP.NET WebAPI and MVC
- Strong knowledge and experience in Javascript, HTML5, CSS3.
- Strong knowledge and experience in MVVM framework and Javascript framework (jQuery, Knock-out, Require, AngularJS)
- Experience with PhoneGap/Cordova
- Experience with API integration through web services
- Experience with mobile development using Xamarin, iOS, Android or Windows Store is a bonus
- Experience with web app development using HTML responsive frameworks
- Experience in front-end design, development and UX is a bonus
- An extensive background working with Microsoft SQL Server, SQL queries and Microsoft reporting tools.

### Skills
- Expert problem-solving skills and a strong work ethic.
- Ability to participate in code reviews as well as working autonomously and as part of a team.
- Strong interpersonal and communication skills - written and verbal
- Strong attention to detail, analytical and conceptual thinker
- A flexible and respectful approach in liaising with colleagues
- An ability to relate to people at all levels
- "Trainable" with the ability to quickly learn different types of technologies
- Enthusiastic, "can do" attitude!
- Always striving to develop both personally and professionally

### Ideally
Additionally, preference may be given to candidates who possess the following:
- Working knowledge of or experience in ERP type system.
- Working knowledge of or experience in Accounting or Retail POS systems
- Experience with workflow based systems also beneficial
- Experience in Agile Development methodologies
- Excellent academic and Tertiary Qualifications
- Oversea or international tertiary qualifications (especially Australia)

### Benefits
- Chance for on-site trips in Australia
- 13th-month salary
- Bonus for every 2 years of service on the day of anniversary
- Bonus programs for staff based on performance and projects
- Weekly budget for team buildings and social purposes (150,000 VND per week per person)
- Life and Personal Health Insurance package for full-time and permanent staff.

### Contact
Please kindly send your updated CV to us or contact for further information via:
Ms. Giau - Recruitment Consultant
Email: giauntn@nicvn.com
Phone: 0903 765 748
Skype: ngocgiau192

**Comment by joneslee85** [comment]
Thanks for posting with us Ms. Giau. The job guideline requires job post reveal the company name. Furthermore, we do not allow recruiter agent to post the job here _unless_ the recruiter agent is hiring people for themselves.
