### ISSUE TITLE
Saigon Technology Solutions - DevOps Engineer - HCM - FT

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#2841]
## Location

* 02 Nguyen The Loc, Ward 12, Tan Binh District, HCMC

## Salary Expectation

* **Up to $2000 NET/month**

### Top 3 Reasons To Join Us

* Technical training sessions (internal-external)
* Attractive salary, benefits and signing bonus
* Premium healthcare insurance for employees and family

### Must Have

* **At least 1 year of experience** with public cloud providers (**AWS, Azure, Google Cloud Platform**)
* Experience using Infrastructure as Code tools such as Terraform/Terragrunt is a big plus
* Experience with the following languages:  PowerShell script, bash script
* Experience with databases, for example, PostgresSQL and/or MS SQL
* Experience with one of the following tools: Ansible, Team City
* Experience with Docker or another container-based system
* Experience with monitoring tools, for example, Zabbix
* **MUST be good at verbal/non-verbal English**

### Nice to have

* Experience with one programming language: Python, Java...
* Willing to work over the weekend when the production server has issues
* Experience to migrate on-premise systems into the clouds

### Responsibilities

* Support deploy and configure tooling to support continuous integration and continuous delivery pipelines
* Engage in projects as needed, work collaboratively with other team members, communicate effectively, and contribute to team success
* Collaborate in technical discussions both internally and with external customer teams
* Support future customer-facing teams with root cause analysis and resolution of escalated technical issues

### Why it would be awesome to work with us

At **Saigon Technology Solutions**, we believe that "_Your success is our mission_", that’s why we build an excellent working environment along with exceptional benefits:

* Attractive salary and benefits (13th, **Salary review – twice/year**)
* Project bonus
* **Free English courses**
* **PVI health care program**
* Company trip every year
* Weekly happy hour
* The staff of the month/year reward
* Party celebration(Christmas, Birthday,...)
* Team-building activities
* Technical training sessions (internal-external)
* Weekly Knowledge Exchange
* A professional working environment with Agile – Scrum
* Sports clubs (football, badminton…)
* Enjoy Relax and beautiful Pantry in the company
* Periodic health examination

### Contact
Homepage: www.saigontechnology.com
Contact person: Kien Tran - Talent Acquisition Lead
Email: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
