### ISSUE TITLE
[VTI Japan] - [Bridge Engineer/BrSE] - [Tokyo, Japan] - [FT]

### ISSUE THREAD

**Issue by hanlevtihr14** [awesome-jobs/vietnam#2842]
## Location

* Tokyo/Osaka, Japan
* Remote/Face-to-face depends on different projects

## Salary Expectation
* up to 700万円～/year

## Requirements
- JLPT Level N2, being able to communicate fluently with Japanese customers
- 2 years experience in Java,  AWS experience is an advantage

### Must Have

* Ready to meet challenges 
* Good communication skill
* Teamwork spirit

### Contact

Homepage: 
https://vti.com.vn/ja/home/
https://tuyendung.vti.com.vn/

HR Han Le  
Email: han.lengoc@vti.com.vn
Phone: 03-6261-5638

**Comment by qcam** [comment]
@hanlevtihr14 Could you please provide more info for role? This post will remain closed until the concerns are addressed.
