### ISSUE TITLE
Cobblestone Energy - Python Backend Developer (Dubai/Remote l AED 15K++ per month, 0% Tax)

### ISSUE THREAD

**Issue by HungNguyenAalto** [awesome-jobs/vietnam#2843]
_Cobblestone Energy is an independent trading firm. Founded in 2017, we are part of the next generation of companies defining the future of global commodity trading. We specialise in the proprietary trading of the intraday and short-term wholesale electricity markets across Europe. We make use of advanced data analytics and extensive research to drive profitable decision making, trading enough electricity every day to power a small country and growing every day. Technology and risk management form the backbone of our business._ 

## Location

* Dubai
* Remote in Dubai

## Salary Expectation

*  15K - 22K AED per month, 0% Tax 

## Responsibilities
* Gather and address technical and design requirements. 
* Implement new features requested by our business and trading team. 
* Refactor existing applications to optimize its performance through setting the appropriate architecture and integrating the best practices and standards. 
* Participate in the entire application lifecycle mainly focusing on coding, debugging and testing. 
* Troubleshoot and debug applications. 

## Requirements
* BSc degree in Computer Science/Computer Engineering. Masters is a plus. 
* Strong in-depth understanding of the entire web development process (design, development, and deployment) 
* Strong competencies in algorithms and software architecture.
* 3+ years of experience as a Python Back-end developer. 
* 4+ years of work experience in Python coding language. 
* 3+ years of experience in developing REST APIs. 
* Strong experience in Relational Databases (MySQL, SQL Server or PostgreSQL).
* Experience in non-relational databases (Mongo DB, Cassandra) is a big plus. 
* Experience using AWS cloud and its resources/services is a big plus. 
* Previous experience in automated testing including unit testing & UI testing. 
* Strong knowledge in Continuous Integration & Continuous Deployment (CI/CD) utilizing Docker containers. 
* Familiarity with front-end languages (e.g. HTML, JavaScript, and CSS). 
* Excellent analytical, time management and teamwork skills. 

## FastTrack Relocation supports to Dubai:
* Flights to office location 
* Applying for residence permit (including guidance with legalization of necessary documents in your home country)
* Temporary housing in furnished apartment/ApartHotel for 2 months (if needed) and assistance for arranging this accommodation
* Registration with relevant authorities and setting up a bank account acquiring a local ID card, which you can use for identification in your new location.

### Contact
Nguyen Thai Hung
Email: thaihung.nguyen2606@gmail.com (OR) hung.nguyen@cobblestoneenergy.com (only from Sun-Thu: 8a.m-17p.m Dubai time)
Linkedin (24/7): https://www.linkedin.com/in/nguyenthaihung/

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by HungNguyenAalto** [comment]
Hi there,

Thanks for your review!

I already shared full contact info in the JD in case you might need to check it more carefully. An introduction about our company was also included in the job description as well.

Cobblestone Energy is an independent trading firm and not a HR staffing agency. The job was also posted by an in-house recruiter.

Thanks & Best Regards,
Hung Nguyễn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
