### ISSUE TITLE
Japanese Outsourcing Company - Java Developer - HCM - FT

### ISSUE THREAD

**Issue by GiauRecruitmentConsultant** [awesome-jobs/vietnam#285]
### Địa Điểm
- Quận 1, Hồ Chí Minh City, Vietnam
- Full-time

### Mức lương
- 600$ - 1,200$

### Khách hàng của NIC Human Resources
Khách hàng của NIC là công ty IT Nhật Bản chuyên thiết kế, phát triển ứng dụng chạy trên nền tảng Smartphone, nền tảng các mạng xã hội, sản xuất và phát triển ứng dụng website.

### Công việc chính:
- Tham gia vào các dự án phần mềm với những doanh nghiệp hàng đầu Nhật Bản
- Xây dụng các apps trên Android, tìm hiểu các công nghệ mới
- Tham gia vào thiết kế và review source code
- Báo cáo tiến độ và tình trạng công việc trực tiếp tới quản lý dự án
- Tiếp cận và được đào tạo theo mô hình phát triển dự án Agile, Scrum

## Yêu cầu công việc: 
- Nắm vững Java Core và J2EE, có kinh nghiệm làm các ứng dụng Java Web
- Có kinh nghiệm với Struts, Spring, Hibernate, ... Biết Seasar2 là một lợi thế
- Thao tác tốt với HTML, CSS, JavaScript (Jquery, AngularJS, Ajax, ...), Bootstrap, JSON, XML, ...
- Có hiểu biết về DI, OOP, MVC Framework, ORM, RESTful, Design Patterns
- Thành thạo các công cụ quản lý mã nguồn: GIT, SVN, Ant, Maven, ...
- Sử dụng tốt các IDEs: Eclipse, NetBeans, ...
- Có kinh nghiệm làm việc với một trong các WebServer: Apache, Tomcat, Jboss, Websphere ...
- Thao tác tốt với một trong các Database: MySQL, PostgreSQL, Oracle, ... có kinh nghiệm làm việc với Big Data là một lợi thế
- Có kinh nghiệm làm việc trong các dự án theo mô hình Agile

### Kỹ năng 

- Có khả năng làm việc teamwork cũng như làm việc độc lập
- Có thể làm việc dưới áp lực cao về deadline cũng như chất lượng sản phẩm
- Khả năng tuy duy tốt, chủ động trong công việc, có tinh thần trách nhiệm cao để hoàn thành công
- việc được giao
- Sử dụng thành thạo tiếng Anh đọc và viết.

### Lương & hợp đồng làm việc & Những phúc lợi khác
-  Mức lương: USD $600~$1200
-  Thử việc 2 tháng
-  Sau thử việc, ký hợp đồng chính thức, lương thỏa thuận theo kết quả thử việc
-  Tuần làm việc 5 ngày (thứ 2- thứ 6), 16h self - study/tháng
- Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo chế độ nhà nước ban hành
- Lương tháng 13, thực hiện review kết quả công việc, thưởng theo kết quả dự án, xét tăng lương 6 tháng một lần
- Được hưởng trợ cấp ăn trưa từ 840,000VND/1 tháng (40.000VND/1 ngày làm việc thực tế)
- Trợ cấp Beauty Care 300.000VND/Tháng với nhân viên nữ ký hợp đồng chính thức
- Trợ cấp đi lại từ 210.000 VND~ 630.000VND/1 tháng (Phụ thuộc vào khoảng cách từ nhà đến Công ty, mức tối thiểu là 10.000VND/1 ngày làm việc thực tế)
- Trợ cấp tiếng Nhật, tiếng Anh, và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...)
- Hỗ trợ phí tham gia Hội thảo ngoài Công ty 100.000 VND/ ngày
- Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, các CLB Game, CLB dạy và học tiếng Nhật, tham gia các bữa tiệc, hoạt động ngoại khóa của công ty ...
- Du lịch hàng năm
- Khám sức khỏe 1 năm/1 lần

### Liên hệ
Please kindly send your updated CV to us or contact us for futher information via:
Ms. Giau - Recruitment Consultant
Email: giauntn@nicvn.com
Phone: 0903 765 748
Skype: ngocgiau192

**Comment by joneslee85** [comment]
Thanks for posting with us Ms. Giau. The job guideline requires job post reveal the company name. Furthermore, we do not allow recruiter agent to post the job here unless the recruiter agent is hiring people for themselves.
