### ISSUE TITLE
Cobblestone Energy - Tech Lead - Dubai/Remote - FT 0% Tax

### ISSUE THREAD

**Issue by HungNguyenAalto** [awesome-jobs/vietnam#2859]
_Cobblestone Energy is an independent trading firm. Founded in 2017, we are part of the next generation of companies defining the future of global commodity trading. We specialise in the proprietary trading of the intraday and short-term wholesale electricity markets across Europe. We make use of advanced data analytics and extensive research to drive profitable decision making, trading enough electricity every day to power a small country and growing every day. Technology and risk management form the backbone of our business._

## Location
* Dubai
* Remote within Dubai

## Responsibilities:
* Take full ownership of all project stages from business requirements gathering to product delivery
* Responsible for end-to-end planning of the project including resources, sprints, milestones, timeline, and deadlines
* Take the initiative to report and resolve any bottlenecks or issues related to the projects & members they are managing autonomously
* Assist substantially in designing, documenting, and sharing/discussing the project architecture with the team. 
* Own and shape our best practices & processes and improve/optimize them to ensure they are up to standards 
* Ensure our best development practices are being followed by the dev team and report any findings or red flags 
* Own the technical implementation of the project they are handling and ensure that project is on track, deadlines are met, and progress/bottlenecks is communicated to management
* Strong focus on Code Quality thorough conducting project code reviews on frequent basis and integrating the needed optimizations and changes
* Prepare, review, and own the technical documentation of his/her projects
* Mentor & Coach Junior team members and their project colleagues
* Manage small teams of developers

## Requirements
* BS degree in Computer Engineering/Computer Science/Electrical Engineering Masters is a plus
* 7+ years of work experience in Python
* 2+ years of work experience as a Senior Python Back-end Developer
* 1+ years of work experience as a Tech Lead
* 2+ years of work experience leading small teams
* 2+ years of experience in Python Frameworks (Flask or Django)
* 3+ years of experience in developing REST APIs
* 3+ years of work-experience using AWS cloud and its resources/services
* AWS certificates are a big plus
* Processing, storing, and managing Real-time data of large volume is a big plus
* Strong design and architecture skills
* Strong coding skills with strong competencies in data structures and algorithms
* Strong work-experience in Relational Databases including PostgreSQL
* 2+ years of work-experience in non-relational databases including Timeseries Db 
* Previous experience in automated testing tools including unit testing & UI testing 
* Strong knowledge in DevOps, CI/CD, Docker containers
* Experience with Scrum/Agile Development methodologies
* Experience managing multiple projects at the same time

## FastTrack Relocation supports to Dubai:
* Flights to office location 
* Applying for residence permit (including guidance with legalization of necessary documents in your home country)
* Temporary housing in furnished apartment/ApartHotel for 2 months (if needed) and assistance for arranging this accommodation
* Registration with relevant authorities and setting up a bank account acquiring a local ID card, which you can use for identification in your new location.

### Contact
Nguyen Thai Hung
Email: thaihung.nguyen2606@gmail.com (OR) hung.nguyen@cobblestoneenergy.com (only from Sun-Thu: 8a.m-17p.m Dubai time)
Linkedin (24/7): https://www.linkedin.com/in/nguyenthaihung/

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by HungNguyenAalto** [comment]
Hi there,

Thanks for your review!

I already shared full contact info in the JD in case you might need to check it more carefully. An introduction about our company was also included in the job description as well.

Cobblestone Energy is an independent trading firm and not a HR staffing agency. The job was also posted by an in-house recruiter.

Thanks & Best Regards,
Hung Nguyễn

**Comment by qcam** [comment]
Thanks for clarifying. Just one more minor nitpick: could you please update the title to not be all caps?

https://github.com/awesome-jobs/vietnam#title-format

Same for the other post at #2843 please.

**Comment by HungNguyenAalto** [comment]
Sure, I will make corrections now.

Thanks again!
Hung

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
