### ISSUE TITLE
PIXTA VIETNAM - Junior/Senior Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by lomojp** [awesome-jobs/vietnam#286]
## Location
Duy Tan, Ha Noi, Viet Nam

## About Company
PIXTA is Japanese leading marketplace site of stock photos, illustrations, vectors and footage. Launched in May 2006 with only a few hundreds of images and 50 contributors, we have grown as one of the largest stock image providers in Japan. Today our library includes over 14 million images from over 170,000 contributors.

PIXTA is sourced by diverse contributors such as stock photo agencies, professional photographers / illustrators / videographers and highly qualified amateur creators.
PIXTA’s images are used for various kinds of professional creative projects such as advertisements, Web design, publications and TV programs. 
Many of our customers are designers, web directors, publishers or other creative professionals.Stock images enable them to achieve highly qualified and effective visuals while saving a lot of time and money.

PIXTA VIETNAM’s established in May, 2016. 
Start-up company: 6 staff

## Salary Expectation
$ 500-$1000 

## Requirements
* 1-3 years experience in software development
* development experience on Linux/Unix environment

### Ideally
* Ruby on Rails development experience
* The development and operational experience of large-scale website or E-commerce website.
* Setting up, configuration and operating of middlewares - Apache/Nginx/Memcached/Redis/MySQL etc.
* Experience of working on Amazon Web Services(AWS)

### Job Description
Develope the existing System’s new feature  and improve using feature: 
-    Retrieval system
-    Upload system
-    Examination system
-    Database design
-    Data analysis

### Dev enviroment
- Languages: Ruby, JavaScript
- Framework: Ruby on Rails, Knockout.js
- Database: MySQL, PostgreSQL
- Infrastructure: Amazon Web Services(AWS)
- Tools: Git, GitHub, SideCI, CircleCI, CodeClimate, Zabbix, NewRelic, esa, Backlog, Chatwork, Slack
- Dual Monitor

### Why do you join us
- An international-standard and professional environment with great chances to learn new skills and gain valuable experience, receive competitive salary, and a number of other benefits.
- Lots of opportunities to work in the special fields
- To work as global engineer
- Working hours: from 08:00 to 17:00 from Mon to Fri
- Entitled for day off every Saturday, Sunday and VietNam holiday
- Competitive salary, negotiation.
- The remuneration for the company's other attractions: annual company trip, health care and periodic input, insurance, lunch allowance …

### Contact
Lien Nguyen / GA_HR Department 
lien.nguyenthuy@pixta.co.jp /
https://www.pixtastock.com/
https://recruit.pixta.co.jp/

**Comment by joneslee85** [comment]
Thanks for posting with us. Can you please revise your post content? It does miss words

* `1-3 experience in software development` - what is `1-3`? is it `years`?
* the format of the `Dev enviroment` should not be bullet point
* the last line of `Ideally` miss word too, `Experience with`? exp with what?
* `500-1000 USD`, the number should have `$` prefix
* typo `Develope`
* the trailing `,` of `Young, Creative,` should be removed
* duplication in the address details, there should be only 1 address section, either at the bottom or in the `About Company`
* the job description is not very clear about the role of the dev, is it a Ruby job? or JS job? or you will provide training?
* the `Develope the existing System’s new feature and improve using feature .` sentence can be rephrased as its grammar is very poor

I hope to see your amendment.

**Comment by lomojp** [comment]
Well-noted with thanks!

**Comment by lomojp** [comment]
Dear Mr Trung,

Thank you so much for your check and advise.
Actually, I often use Japanese bot English, so maybe my English is not
good, especially on IT words.
I've revised my post, so pls kindly re-check and support.

Thanks you so much!


Thanks for your help and corporation so far!!!

[image: PIXTA VIETNAM Co.,Ltd] <https://www.pixtastock.com/>

Lien Nguyen / GA_HR Department
lien.nguyenthuy@pixta.co.jp / (+84) 978.039.143

PIXTA VIETNAM Co.,Ltd
Office: (+84).4. 3226.2520 / Fax: (+84).4. 3226.2504
MST: 01074282077F, IC Building, 82 Duy Tan, Cau Giay, Ha Noi, VietNam
https://www.pixtastock.com/

[image: Facebook]  <https://htmlsig.com/t/0000001BRZK8J> [image: Skype]
<https://htmlsig.com/t/0000001BMFRS3>


2016-08-11 19:08 GMT+07:00 Trung Lê <notifications@github.com>:

**Comment by joneslee85** [comment]
@lomojp please revise:

* `$ 500-$1000`, remove the space after `$` sign and ensure you specify the `USD` at the end of the sentence
* typo `Develope`

**Comment by joneslee85** [comment]
There is no amendment in the last 2 days, I am closing this job.

**Comment by lomojp** [comment]
<< English followings...>>

Công ty TNHH PIXTA VIETNAM  xin trân trọng thông báo, kể từ ngày 18/08/2017
chúng tôi thay đổi địa chỉ giao dịch và địa chỉ trên giấy đăng ký kinh
doanh như sau:

*Thông tin giao dịch mới:*

-        Tên Công ty: Công ty TNHH PIXTA VIETNAM

-        MST: 0107428207

-        Địa chỉ: Tầng 8, tòa nhà Trường Thịnh, số 1 Phùng Chí Kiên, phường
Nghĩa Đô, Quận Cầu Giấy, Thành phố Hà Nội, Việt Nam.

-        SĐT : (+84) 24.6.664.1988
Fax:(+84) 24.6.666.1989

Thông tin chi tiết, xin tham khảo trong file đính kèm !!!


 PIXTA Vietnam Co. Ltd. would like to inform that: since 18/08/2017, our
transaction address and registered address have been changed hereunder:

*New transaction information:*

-        Company name: Công ty TNHH PIXTA VIETNAM

-        MST: 0107428207

-        Address: Level 8, Truong Thinh Building, no. 1 Phung Chi Kien
Street, Nghia Do Ward, Cau Giay district, Hanoi city, Vietnam

-        Phone number : (+84)
24.6.664.1988                                     Fax:(+84) 24.6.666.1989

For more information, please refer to the attached file !!!


Thanks for your help and corporation so far!!!

[image: PIXTA VIETNAM Co.,Ltd] <https://www.pixtastock.com/>

Lien Nguyen / GA_HR Department
lien.nguyenthuy@pixta.co.jp / (+84) 978.039.143

PIXTA VIETNAM Co.,Ltd
Office: (+84).4. 3226.2520 / Fax: (+84).4. 3226.2504
MST: 01074282077F, IC Building, 82 Duy Tan, Cau Giay, Ha Noi, VietNam
https://www.pixtastock.com/

[image: Facebook]  <https://htmlsig.com/t/0000001BRZK8J> [image: Skype]
<https://htmlsig.com/t/0000001BMFRS3>
