### ISSUE TITLE
ORIENT SOFTWARE - VUEJS DEVELOPER (JUNIOR/MIDDLE) - 1 MONTH SALARY SIGN-ON BONUS

### ISSUE THREAD

**Issue by baotran0803** [awesome-jobs/vietnam#2861]
## Location

* Da Nang, Vietnam

## Salary Expectation

* 500-1000$

## Requirements
* At least 1-year experience with VueJS and keep up with the latest version to build the new application from scratch
* Strong knowledge on JavaScript
* Proficient in HTML, CSS
* Familiar with Vuex, Vue CLI, GraphQL
* Work well with Jira or TeamCity, Scrum
* Good communication in English.

### Responsibilities

* Work on a large-scale software product in the frontend web application development project using VueJS.
* Work in collaborative teams and building quality code. Help the team to champion software quality and engender technical vision and ensuring clients are satisfied.
* Be problem solvers, think through hard problems and work with amazing people to make the reality of the solution.
* Practice agile software development and be a great team player.
* Learn something new every day, work your great innovative idea with a team to apply to the project.

### Why it would be awesome to work with us
* Attractive salary based on your performance
* Annual 13th month salary
* Dedication bonus goes up to 40% monthly salary
* Project bonus will be paid twice a year
* Premium healthcare insurance, Annual health checks up.
* Breakfast are available at office in early morning and snack in late afternoon.
* Happy Lunch every two weeks.
* Team building allowance.
* Annual Company team building trip.
* Clubs (Football, Badminton, Swimming, Chess, Music band).
* Exclusive training programs for all staff in technical, soft skills and process.
* Outdoor training every 6 months.
* English class.
* Technical clubs.
* Marriage allowance, having newborn baby allowance, bereavement allowance.

### Contact
Email: tran.dang@orientsoftware.com
Skype: baotran0803

**Comment by qcam** [comment]
Thanks for posting. Could you please update the job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), and please make sure to fill out every `REQUIRED` section.
