### ISSUE TITLE
Tulpo Software - Blockchain Developer - Hanoi - Fulltime

### ISSUE THREAD

**Issue by HoaHR** [awesome-jobs/vietnam#2862]
## Location

* Hanoi, Vietnam
* Full-time

## Salary Expectation

* Upto: $2500

## Requirements

* Understanding of Blockchain technology. 
* 2-5 years of Solidity or Vyper development experience.
* Experience with smart contract static analysis tooling (e.g. Manticore) or formal verification (e.g. KEVM) would be a plus.
* 2-5 years of experience in server-side programming languages (e.g. Typescript, Golang, NodeJS).
* Strong organizational skills, interpersonal skills, and having the ability to juggle conflicting requirements from many different stakeholders.
* Docker, Linux, gRPC, database (MySQL, Postgres), API, continuous integration
* Knowledge of peer-to-peer distributed networks
* Know how to deploy and configure Blockchain nodes such as Bitcoin, Ethereum, EOS
* Knowledge of front-end frameworks and technologies (e.g. React.js, Vue.js, Mobx, Redux) would be a plus.

### Responsibilities

* Research, design, implement, and maintain all decentralized finance systems incubated/supported.
* Work closely with product managers, designers, strategists, DevOps engineers, security engineers, and quants to ensure the high-quality systems by following the product and technical standards and deliver to the market on time.

### Why it would be awesome to work with us

* We offer an attractive compensation package working in a cutting-edge field of Fintech (From $1300 to $2500) + Monthly allowances
* Salary review 2 times/ year, based on work performance and company’s performance
* Performance bonus, 13th- month salary, public holidays bonus
* Young, dynamic and creative working environment
* Be part of a special experience in an ever-growing company
* Tea, Coffee and snacks are always ready for the working day.
* To be insured according to the provisions of the law.
* Probation period: 1 month
* Participate in team building activities, annual vacation… "work hard, play hard"

### Contact
Homepage:  https://tulpo.vn
Should you have any queries, please don't hesitate to contact us:
* Tel: 0334 532 210
* Mail: nhuhoahr@tulpo.vn  or hr@tulpo.vn                            
* Skype: leuhoavc_1

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
