### ISSUE TITLE
Senior Solutions Architect - HN - Upto 7000$

### ISSUE THREAD

**Issue by hanhhnguyenn** [awesome-jobs/vietnam#2863]
## Location

* Hoan Kiem, Ha Noi, Vietnam
* Company: Multinational Corporations - BIG3 the largest management consulting firms 

## Salary Expectation

* Open Budget: 4000$ - 7000$ (and higher)/month

## Requirements
* 4+ years of experience in the role of Solutions Architect
* Having knowledge and in-depth understanding of enterprise architect, systems, technologies, ...
* Experience with newest technology trends (e.g. AI/ML, IoT, RPA, Edge Computing, Blockchain, AR/VR, etc.) 
* Experience working on projects that span multiple journeys and squads 
* Good English skill

### Responsibilities

* Produce high level and detail solution designs 
* Define impacted systems & proactively solves architectural ambiguities 
* Establishes opportunities and constraints for technology architecture 
*  Works with PO to put dependencies & external deliverables into backlog 
*  Proactively solves architectural ambiguities 
* Drive analysis how business requirements can be technically implemented 
* Engage in creating develop solution designs to ensure alignment with enterprise architecture principles, standards, policies, and patterns 

### Contact Hazel for more information if you're interested in this position:
Gmail: hazel.nguyenminh@gmail.com
Linkedin: https://www.linkedin.com/in/hazel-nguyen-minh/

Hope you guys and your family are safe and healthy amid the pandemic!
Cheers,

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
