### ISSUE TITLE
VieON - 08 Backend Developer - HCM - Fulltime

### ISSUE THREAD

**Issue by ducminhgd** [awesome-jobs/vietnam#2864]
## Location

* District 1, Sài Gòn, Việt Nam

## Salary Expectation (Gross)

* Technical Lead: 50,000,000 - 80,000,000
* Senior: 40,000,000 - 65,000,000
* Mid-level: 30,000,000 - 40,000,000
* Engineer: 15,000,000 - 30,000,000
* Junior: 10,000,000 - 15,000,000

## Requirements

* No degree is required

### Must Have

* Programming language: Go (is a plus), Python, NodeJS
* Database: MySQL, MongoDB
* Caching
* Docker
* Kubernetes
* Git, CI/CD
* Have knowledge in Unit Test and applying Unit test.
* High responsibility, meet commitments.
* Keep in mind that _DevOps is a culture not a position_

### Ideally

* Knowledge in other languages
* Has experiences in  OTT Streaming.
* Has experiences in high request rate system, high CCU system.
* Has experiences in design software architecture.

### Responsibilities

* Develop and operate Backend Services of an OTT product.
* Ensure releasing on time.
* High availability and low latency system.

### You’ll be responsible for

* Develop and operate Services of VieON.

### Why it would be awesome to work with us

* Work with services which have a huge number of requests.
* Challenge with _alien's requests_, _strange things_ to learn new knowledges
* Free VIP account of VieON.

### Other positions:

* 01 QC Manager: Manual or Automation.
* 01 Frontend Manager.

### Contact

Homepage: https://vieon.vn
Email: minh.gia@vieon.vn

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by ducminhgd** [comment]
> Thank you for posting! Unfortunately, we require job posts to be written in English.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

I have just updated JD. Please have a check and approve this job. Thank you!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by ducminhgd** [comment]
@lactroi , since we have not recruited enough employees, please re-open this issue. Or should I create a new one? Please guide me.
