### ISSUE TITLE
Sky Mavis (Axie Infinity) - Senior Backend Engineer - HCM - FT

### ISSUE THREAD

**Issue by NgocAnhTran** [awesome-jobs/vietnam#2865]
## Location
* HCMC, Vietnam

## Who we are
Sky Mavis is a team of nation builders. Together, we build both the virtual worlds of the future and the infrastructure that makes them possible. When it comes to building our internal nation, we put lots of effort into creating a working environment where you will find fulfillment every day and can be yourself just as much as you are when at home. At our cores, we are entrepreneurs, innovators, nerds, and gamers. We are a group of people who are curious about new things, passionate about creating impactful changes, and candid when it comes to challenges and critics.

We are at the forefront of technological innovation and we are moving fast. As part of our team, you’ll join a group of talented young people, who are making changes while having fun doing it.

## Requirements
* You're proficient in at least one modern backend language, ideally experience with Go, Typescripts, Rust, Solidity.
* You have experience working with database systems like Postgres and Redis.
* You write secure, efficient, and elegant code.
* You learn quickly and adapt to new principles and ideas.
* You're a team player and can work closely with the rest of our team.

### Responsibilities
Our Backend Engineers are responsible for building scalable systems that enable our products to operate and scale to potentially millions of users.
We are operating at the bleeding edge of blockchain technology, so many of your prerogatives may be experiments that have never been conducted before. You'll need to be bright, nimble, and willing to innovate to succeed in this role. Your day to day might include:
* Delivering our core platform architecture.
* Solving difficult problems around data-intensive and complex data flow systems.
* Building highly scalable and dynamic game and web servers that can withstand massive user traffic.
* Finding elegant ways to incorporate state-of-the-art solutions from our research initiatives into our products.

Great power comes with great responsibilities!

### Why it would be awesome to work with us
* Front row seat to one of the most exciting blockchain projects that make positive impacts in changing many people’s lives globally
* A fast-paced, young, active, and fun working environment where everything revolves around games and cute species
* A competitive salary package that fit your skills, experiences, and contributions
* Give you freedom & ownership to your work
* Embrace your nature as a gamer (Why else would you want to join us?)
* You’ll acquire new skills as we usher in a new era of ownership.
* Help you to give your family the security that they deserve

### Contact
Homepage: skymavis.com
Email: ngocanh@axieinfinity.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
