### ISSUE TITLE
Sky Mavis (Axie Infinity) - Senior DevOps Engineer - HCM - FT

### ISSUE THREAD

**Issue by NgocAnhTran** [awesome-jobs/vietnam#2866]
## Location
* HCMC, Vietnam

## Salary range
Open for negotiation

## Who we are
Sky Mavis is a team of nation builders. Together, we build both the virtual worlds of the future and the infrastructure that makes them possible. When it comes to building our internal nation, we put lots of effort into creating a working environment where you will find fulfillment every day and can be yourself just as much as you are when at home. At our cores, we are entrepreneurs, innovators, nerds, and gamers. We are a group of people who are curious about new things, passionate about creating impactful changes, and candid when it comes to challenges and critics.

We are at the forefront of technological innovation and we are moving fast. As part of our team, you’ll join a group of talented young people, who are making changes while having fun doing it.

## Requirements
* It would be awesome if you have a passionate curiosity about how the Internet fundamentally works and with strong coding ability in Bash, Python or Go.
* You have experience working with container technologies (Docker, Kubernetes).
* You have experience setting up automation pipelines (CI/CD, Jenkins).
* You're comfortable working with cloud services (AWS, Azure, GCP).
* Experience with Postgres, Redis, Typescripts, Go, Solidity would be highly preferable
* You learn quickly and adapt to new principles and ideas.
* You're a team player and can work closely with the rest of our team.

### Responsibilities
Our DevOps Engineers are responsible for maintaining the robustness and reliability of our system to operate and scale to potentially millions of users. This is not a traditional role - more of a fusion between classic DevOps and Site Reliability Engineering.
We are operating at the bleeding edge of blockchain technology, so many of your prerogatives may be experiments that have never been conducted before. You'll need to be bright, nimble, and willing to innovate to succeed in this role. Your day to day might include:
* Apply cloud (AWS, Azure, GCP) computing skills to deploy releases and upgrades.
* Apply best practices to improve the company's computing architecture (server monitoring, micro-services management).
* Implement automation tools and frameworks (CI/CD pipelines).
* Improve company engineering tools, procedures and data security

### Why it would be awesome to work with us
* Front row seat to one of the most exciting blockchain projects that make positive impacts in changing many people’s lives globally
* A fast-paced, young, active, and fun working environment where everything revolves around games and cute species
* A competitive salary package that fit your skills, experiences, and contributions
* Give you freedom & ownership to your work
* Embrace your nature as a gamer (Why else would you want to join us?)
* You’ll acquire new skills as we usher in a new era of ownership.
* Help you to give your family the security that they deserve

### Contact
Homepage: skymavis.com
Email: ngocanh@axieinfinity.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
