### ISSUE TITLE
Sky Mavis (Axie Infinity) - Senior Frontend Engineer - HCM - FT 

### ISSUE THREAD

**Issue by NgocAnhTran** [awesome-jobs/vietnam#2867]
## Location
* HCMC, Vietnam

## Salary range:
open for negotiation

## Who we are
Sky Mavis is a team of nation builders. Together, we build both the virtual worlds of the future and the infrastructure that makes them possible. When it comes to building our internal nation, we put lots of effort into creating a working environment where you will find fulfillment every day and can be yourself just as much as you are when at home. At our cores, we are entrepreneurs, innovators, nerds, and gamers. We are a group of people who are curious about new things, passionate about creating impactful changes, and candid when it comes to challenges and critics.

We are at the forefront of technological innovation and we are moving fast. As part of our team, you’ll join a group of talented young people, who are making changes while having fun doing it.

## Requirements
* You're proficient in at least one modern frontend language, ideally you’d have experience with Typescripts, React/Vue, GraphQL, Pixi
* You write secure, efficient, and elegant code.
* You learn quickly and adapt to new principles and ideas.
* You're a team player and can work closely with the rest of our team.

Benefits
### Responsibilities
Our Front-end Engineers have the vital role of building what we show to the world.
Due to the crucial role that art, design, and UI play in our products, you will have a huge impact on the success and growth of them. You'll need a deep understanding of our users and an eye for good UI/UX to excel in this role. Your day to day might include:
*  Providing technical input to the planning and design for new products and features.
*  Developing and maintaining our web products and internal web-based systems.
*  Polishing and optimizing our products with strong attention to detail and aesthetic sense.
*  Working with our growth team on optimizing our products for viral growth.

### Why it would be awesome to work with us
* Front row seat to one of the most exciting blockchain projects that make positive impacts in changing many people’s lives globally
* A fast-paced, young, active, and fun working environment where everything revolves around games and cute species
* A competitive salary package that fit your skills, experiences, and contributions
* Give you freedom & ownership to your work
* Embrace your nature as a gamer (Why else would you want to join us?)
* You’ll acquire new skills as we usher in a new era of ownership.
* Help you to give your family the security that they deserve

### Contact
Homepage: skymavis.com
Email: ngocanh@axieinfinity.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
