### ISSUE TITLE
DEK Technologies Vietnam - Telecommunication Application Developer - Saigon - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#2868]
## Location

* Saigon, Vietnam

## Join our winning team!
DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be a proud, integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

### At DEK Technologies you will find yourself in an exciting career with:

- Attractive, competitive salary and incentives
- Opportunities for short and long-term training/work overseas
- An excellent working environment in developing tomorrow’s features
- Open and honest culture where people are valued, treated fairly, trusted and empowered
- Training and career development opportunities
- 40 flexible working hours per week from Monday to Friday
- English classes 3 hours a week with qualified foreign teachers
- Extra 24/7 Health and Accident Insurance
- Annual health check-up
- Annual company trip & annual family day
- Activities such as; sport & music clubs, yoga & piano classes

## Job description

We are looking for IT Fresher to join our distributed cross-functional teams between Sweden and Vietnam, you will be involved in the full system development lifecycle:

- Analyse and provide solutions for new requirements;
- Implement new features;
- Design and execute test scenarios in both feature and system test levels;
- Work with Continuous Integration (CI) system (Jenkin, Bazel, …);

You will take opportunities to work with new technologies such as Voice over LTE (VoLTE), OpenStack, Virtualization (KVM, VMware), …

You will live a true Agile & Lean culture where employees are empowered at all levels to collaborate and take ownership. At DEK Vietnam, we constantly run the Scrum mentorship and Agile Coaching programs to help build up your career path.

## Job requirements

If you have just graduated from University with a Bachelor Degree in either Information Technology, Computer Science or a related degree with:

- Strong IT background;
- Fluent in at least one programming language;
- High teamwork spirit;
- Eager to learn new technologies;
- Basic English communication;

### Contact
Website: https://www.dektech.com.au/
Fanpage: https://www.facebook.com/DEKTechnologiesGlobal/
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
