### ISSUE TITLE
MySQUAR - [Senior] Fullstack Javascript/NodeJS Engineer - HCM - FT

### ISSUE THREAD

**Issue by ThaoMySQUAR** [awesome-jobs/vietnam#287]
## Location
- 246 Cong Quynh, District 1, HCM, Vietnam
## Salary Expectation
- Above 1200$
## About Job

Backend is at the heart of our products. It is the brain and lungs of it, and we grow it with a lot of care. We are looking at working with passionate people that love to polish their craft, that love design patterns and are not worried about learning new things or just using what works best.
Working together but on the other end of the spectrum, frontend delights your users. You build the backend that backs your frontend and the frontend that will make your users happy.
- TDD all-the-things
- Write NodeJS in the backend, ReactJS in the frontend
- Micro-services centric approach with Docker, Kubernetes based infrastructure
- Continuous integration/ deployment 
- Cutting-edge tools Github, Code Climate, New Relic, Airbrake, Pager Duty
- We use Redis, BigQuery, PostgreSQL, Cassandra, GraphDB databases with our services
- We write code that scales, we deploy code to a PaaS and we upgrade our system as it grows
- Doing a lot of code review and refactoring. That requires solid knowledge of Javascript and NodeJS, not just the pros but also the cons
## Requirements
- A lot of passion and a good mind
- Mid-level to Senior Position, above 2 years experiences
- Ability to grow, learn, challenge and be challenged
- Proficient on Javascript/ ES6/ ES7/ ReactJS/ HTML5/ CSS3
- Rock solid NodeJS skills
  PostgreSQL, Redis
- Know your s\* about patterns, scalable code, debugging, optimization, etc…
- Knowledge of distributed and scalable system design is a plus
- Knowledge on DevOps and tools such as Docker is a plus
- Experience with React Native/ Android/ iOS is a plus
## What you get
- Love from the team
- A competitive salary
- Full health benefits and social insurance
- A training budget
- A macbook and a 21" screen
- ESOP
- Possible travel to Myanmar to meet users and the team as well as Singapore
- Lots of cool stuff to relax (who said Foosball?)
## Contact us

Would you like to know more? Resumes and questions, please get in touch with thao@mysquar.com, or
apply at: http://vietnam.mysquar.com

**Comment by AlecksJohanssen** [comment]
Ahh no more dodging bullet and flying <3
