### ISSUE TITLE
DEK Technologies Vietnam - C/C++ Software Developer - Saigon - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#2870]
## Location

* Saigon, Vietnam

## Join our winning team!
DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be a proud, integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

### At DEK Technologies you will find yourself in an exciting career with:

- Attractive, competitive salary and incentives
- Opportunities for short and long-term training/work overseas
- An excellent working environment in developing tomorrow’s features
- Open and honest culture where people are valued, treated fairly, trusted and empowered
- Training and career development opportunities
- 40 flexible working hours per week from Monday to Friday
- English classes 3 hours a week with qualified foreign teachers
- Extra 24/7 Health and Accident Insurance
- Annual health check-up
- Annual company trip & annual family day
- Activities such as; sport & music clubs, yoga & piano classes

## Job description

We have many new wonderful C/C++ opportunities for IT Freshers. You will be involved in software development, maintenance and testing for the following products:

- New generation of mobile core network infrastructure that enables various types of multimedia services to end-users using common TCP/IP-based protocols;
- A high capacity, high availability, scalability cluster platform used in mission-critical products that can serve extremely huge number of users at the same time;
- Linux Operating System (OS) customization;

By joining our team, you will have a chance to collaborate with senior engineers from Australia, Sweden and other countries.

_At DEK Technologies Vietnam, you will live with Agile & Lean principles where employees are empowered at all levels to collaborate cross-functionally, to take pride in collective ownership, to improve yourself by continuously learning, practicing & sharing with others._

## Job requirements

If you have just graduated from University with a Bachelor Degree in either Information Technology, Computer Science or a related degree with:

- C/C++ software development passion;
- High teamwork spirit;
- Basic English communication.

### Contact
Website: https://www.dektech.com.au/
Fanpage: https://www.facebook.com/DEKTechnologiesGlobal/
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
