### ISSUE TITLE
DEK Technologies Vietnam - C++ Software Developers - Saigon - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#2874]
## Location

* Saigon, Vietnam

## Join our winning team!
DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be a proud, integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

### At DEK Technologies you will find yourself in an exciting career with:

- Attractive, competitive salary and incentives
- Opportunities for short and long-term training/work overseas
- An excellent working environment in developing tomorrow’s features
- Open and honest culture where people are valued, treated fairly, trusted and empowered
- Training and career development opportunities
- 40 flexible working hours per week from Monday to Friday
- English classes 3 hours a week with qualified foreign teachers
- Extra 24/7 Health and Accident Insurance
- Annual health check-up
- Annual company trip & annual family day
- Activities such as; sport & music clubs, yoga & piano classes

## Job description

We have many opportunities for C++ Developers to work on a product for one of the world’s leading system providers. You will be working with common components used by several applications in a core network solution.

By joining our team, you will have a chance to collaborate with senior engineers from Australia, Sweden and other countries to:

- Understand the requirement, design, and implement new features
- Troubleshoot issues, suggest and implement solutions
- Continuously improve together with the team

_At DEK Technologies Vietnam, you will live with Agile & Lean principles where employees are empowered at all levels to collaborate cross-functionally, to take pride in collective ownership, to improve yourself by continuously learning, practicing & sharing with others._

## Job requirements

**A University Qualification in Software Engineering or a related degree is required.**

- At least 2 years of experience with C++ Programming Language

### Contact
Website: https://www.dektech.com.au/
Fanpage: https://www.facebook.com/DEKTechnologiesGlobal/
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
