### ISSUE TITLE
DEK Technologies Vietnam - Cloud Engineer - Saigon - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#2875]
## Location

* Saigon, Vietnam

## Join our winning team!
DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be a proud, integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

### At DEK Technologies you will find yourself in an exciting career with:

- Attractive, competitive salary and incentives
- Opportunities for short and long-term training/work overseas
- An excellent working environment in developing tomorrow’s features
- Open and honest culture where people are valued, treated fairly, trusted and empowered
- Training and career development opportunities
- 40 flexible working hours per week from Monday to Friday
- English classes 3 hours a week with qualified foreign teachers
- Extra 24/7 Health and Accident Insurance
- Annual health check-up
- Annual company trip & annual family day
- Activities such as; sport & music clubs, yoga & piano classes

## Job description

Exciting, new opportunities exist in our development team responsible for a large-scale system from a world-leading company. We are looking for Cloud Engineers to work on the project Life Cycle Management, which includes deployment, installation, integration, backup and restoration.

By joining our team, you will have a chance to collaborate with senior engineers from Australia, Sweden and other countries to:

- Build tools, and develop features that manage and deploy the applications in Cloud infrastructures (OpenStack, VMware)
- Perform pre-studies, make prototypes and provide work instructions based on different kinds of Cloud infrastructures
- Automate the installation and deployment
- Design, develop, test and maintain features
- Work with Continuous Integration (CI) systems (Jenkin, Travis CI, etc)

_You will live a true Agile & Lean culture where employees are empowered at all levels to collaborate and take ownership. At DEK Vietnam, we constantly run the Scrum mentorship and Agile Coaching programs to help build up your career path._

### Must have

- A University Qualification or College degree in Software Engineering or related fields
- Experience with Bash script or Python
- Familiar with Linux environment
- Basic knowledge about Network configuration

### Nice to have

- Familiar with version control tools (Git, SVN, etc)
- Experienced with Cloud environment

### Contact
Website: https://www.dektech.com.au/
Fanpage: https://www.facebook.com/DEKTechnologiesGlobal/
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
