### ISSUE TITLE
DEK Technologies Vietnam - C/C++ Software Developers - Saigon - FT

### ISSUE THREAD

**Issue by nguyenhoangthuyvy** [awesome-jobs/vietnam#2876]
## Location

* Saigon, Vietnam

## Join our winning team!
DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be a proud, integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

### At DEK Technologies you will find yourself in an exciting career with:

- Attractive, competitive salary and incentives
- Opportunities for short and long-term training/work overseas
- An excellent working environment in developing tomorrow’s features
- Open and honest culture where people are valued, treated fairly, trusted and empowered
- Training and career development opportunities
- 40 flexible working hours per week from Monday to Friday
- English classes 3 hours a week with qualified foreign teachers
- Extra 24/7 Health and Accident Insurance
- Annual health check-up
- Annual company trip & annual family day
- Activities such as; sport & music clubs, yoga & piano classes

## Job description

As a key member of the Software Engineering team, you will be involved in the delivery of projects for both internal and external projects – from initial concept design, advising leading global automotive manufacturers on all aspects of the Software Development Life Cycle, right through to design for testing and manufacture on internal projects. Working with C++, you will apply your skills and knowledge of the Linux Operating Systems, processor architecture and hardware designs to develop computer vision systems such as driver monitoring that comply to relevant safety and process standards.

Our close-knit team fosters an environment of product innovation, quality software, rapid product iteration and collaboration on a wide range of hardware and software products, where you will be responsible for:

- Designing, implementing and testing Linux kernel drivers/applications for the Driver Monitoring solution for a number of driver monitoring applications
- Designing, developing and problem-solving embedded systems – including prototyping of concepts as well as optimizing and improving system architecture

_At DEK Technologies Vietnam, you will live with Agile & Lean principles where employees are empowered at all levels to collaborate cross-functionally, to take pride in collective ownership, to improve yourself by continuously learning, practicing & sharing with others._

## Job requirements

- Experience developing production-quality C++ code
- Experience writing code for multi-core SoCs and multi-threading system
- Experience developing embedded Linux kernel drivers/applications

### Contact
Website: https://www.dektech.com.au/
Fanpage: https://www.facebook.com/DEKTechnologiesGlobal/
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
