### ISSUE TITLE
Groove Technology - Senior ReactJS Developer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by tonynguyen11** [awesome-jobs/vietnam#2879]
## Location

* Ho Chi Minh, Vietnam

## Salary Expectation

* Negotiate (attractive)

## Requirements
* At least 4 years of experience in ReactJS/ Redux
* Strong experience in developing responsive UI design
* Good in English communication

### Must Have

* Reactjs
* Redux

### Ideally

* Experience with Apache Cordova for building hybrid mobile applications

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Translate wireframes and designs into good quality codes
* Collaborate with cross-functional team to design and develop product features with a view to
scalability, stability, in an agile development environment.
* Write clean, reusable, and testable code with strong unit test & debugging skills.
* Communicate to back-end via APIs.
* Offering open and honest communication (to both business and technical partners) is an
absolute requirement.
* Keep your Project Manager, and Technical Lead reported on your development status.

### You can bring

* Troubleshooting skill
* Critical thinking, creativity, and problem-solving

### Why it would be awesome to work with us

* Full 13th month salary
* Full social insurance
* Free English course and technical training session

### Interesting engineering projects

* Sports domain - a big new project
* Working with teammates in oversea

### Contact

* Skype: skyfall_0508
* Email: toan.nguyen@groovetechnology.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
