### ISSUE TITLE
Splus Software - Ruby on Rails Developer - FT - HCM - Negotiable

### ISSUE THREAD

**Issue by Kieuly1708** [awesome-jobs/vietnam#2880]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

## Requirements

•	Bachelor’s degree in Computer Science Engineering or other related courses.
•	At least 1-year experience working with Ruby on Rails using RSpec library
•	Good knowledge of relational databases, SQL
•	Proficiency with code versioning tools including Git, Github, SVN, and Mercurial
•	Strong knowledge of front-end technologies including HTML5, JavaScript, and CSS3
•	Good problem-solving skills
•	Willing to work hard and learn new technologies
•	Having Japanese (equivalent to N3) or English is an advantage.

### Responsibilities

•	Developing projects for Japanese, English, and domestic customers 
•	Creating Backend components with Ruby on rails
•	Integrating data storage solutions
•	Maintaining and troubleshooting existing web applications
•	Optimize our web applications for maximum speed
•	Participating in all works in the software development process, including requirements inquiry, analysis, design, research new technology ...
•	Contributing ideas to leaders and customers to improve products or work processes
•	Solving issues, executing work according to plan, report work progress for direct management (PM)
•	Detailed information about the project's profession will be discussed in the interview.

### Why it would be awesome to work with us

•	Competitive salary package and specific benefits
•	TET bonus from 1 to 2-month salary according to seniority, work results, and business situation of the company.
•	The company pays (32%) the costs of social insurance, health insurance, and unemployment insurance for its employees.
•	Performance review twice a year
•	Annual holiday: 12 annual leave and Corporate Birthday 11/27
•	Working in a dynamic and professional environment with many promotion opportunities.
•	Receive benefits according to seniority
•	Being trained in foreign languages, sponsored to learn certificates to improve professional skills and soft skills.
•	Lots of opportunities to go to Onsite at SPLUS JAPAN (for staff with Japanese proficiency from N3 and above)
•	Sports activities: Football
•	Annual company trip, team building, birthdays for employees in the month, and special events of the year (March 8, October 20, Mid-Autumn Festival, Christmas ...).
•	Time working: Monday – Friday (9:00 – 18:00).

### Contact
Homepage: https://www.splus-software.com.vn/
Kindly, send your CV via mail: lykty@splus-software.com.vn or contact me via Skype: kieuly1708 for more information
Title: [Position - Your Name]

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
