### ISSUE TITLE
InnomizeTech - Fullstack Engineer (Senior/Lead) - HCM- FT

### ISSUE THREAD

**Issue by thanhthi** [awesome-jobs/vietnam#2883]
## Location: HCMC
* Remote during the covid-19 pandemic

## Salary Expectation

* Maximum $2500 Gross

## Requirements
* Bachelor’s Degree
* 5+ years of experience on full stack development
* Full-Stack software development experience preferred with an emphasis on Front End architecting and building robust distributed systems that scale well 
* Working understanding of HTML, CSS, JavaScript/ TypeScript
*  Experience in developing unit tests
*  Strong problem solving skills
*  Ability to architect and design SaaS products
*  Ability to writing reusable libraries
*  Working experience with one or more of the following: .Net Core, Java, NodeJs, PHP, Go
*  Strong in cloud computing with one or more of the following: AWS, Azure, Google Cloud

## Skills
* Knowledge of and skills in Swagger, Microservices (Docker)
*  Good English communication

### Responsibilities
* Develop web applications using Java / Go / NodeJs / .Net, javascript technology stack and object oriented methodologies.
* Perform as technical lead on software development projects with responsibility for overall delivery of software components including writing code.
*  Collaborating with other tech leads to ensure integrated end-to-end design.
*  Documenting design decisions and ensuring adherence.
*  Supporting automated testing, and oversight during implementation into production.
*  Conduct design & code reviews
*  Work within and across Agile teams to design, develop, test, and implement technical solutions across a full-stack development tools and technologies
*  Leverage engineering practices like pair programming, CI/CD, and Refactoring techniques
*  Bring a passion to stay on top of tech trends and best practices: Experiment with and learn new technologies, participate in community of practice groups, and mentor more junior members of the engineering community
*  Encourage inclusion, outside-of-the-box thinking, teamwork, self-organization, and diversity
*  Lead developers in IT projects

### Why it would be awesome to work with us
As a start-up company, our team is our highest priority and we welcome new talent in our team. Along
with our young spirit, our aim is to create an ideal and open environment where each person is eager
to work and encouraged by the creative ability of every member of our team.
* We put human development as the first priority.
*  We give you challenging and interesting work to develop your career path.
*  Flexibility and authorizing culture in our company.
*  Activities: BBQ, Yearly company trips, Year-end Party, Teambuilding, Football Clubs.
*  Exciting internal events to help you understand the whole business and make you feel like you are part of the Innomize Family.
*   Modern and cozy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day, to make sure energy level is high when you need it.
*  There are a lot of opportunities to learn and grow with training activities weekly such as English, Management, Soft Skills, Technology.
*  Career guidance and support daily from Manager, Leader and Senior Level.
*  13th payment, and extra bonus for excellent employees.
*  Salary and promotion review: twice / year
*  Promotion opportunities for Senior and Leader level.
*  Special bonus on Public holiday.

### Contact
Website: www.innomizetech.com
Email: hr@innomizetech.com
Skype: thanhthi.hr
WhatsApp: 0988428440

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
