### ISSUE TITLE
Money Forward Vietnam - Flutter Mobile Dev (Android, iOS) - HCMC - FT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#2885]
## Location

* Saigon, Vietnam
* Currently working online 100% due to Covid19

## Salary Expectation
* We offer salary based on your expectation

## Requirements
* Education: Bachelor of IT or equivalent
* Language: English 

## Skills
* 2+ years’ experience in developing apps for Mobile using Flutter.
* Experience with Redux, or BLoC or Provider model.
* Strong understanding of Functional programming.
* Experience with unit tests to improve software quality.
* Experience with code review
* Experience of team development using Git
* If you don‘t have enough experience, you still can apply for this job!

### Must Have
* Experience in Android and iOS development
* Motivation to learn a new programming language
* English skill for business
* Excellent at teamwork
* Built at least two Android and/or iOS apps with Flutter

### Ideally
* Experience with clean-code, readable-code
* Excellent troubleshooting skills, able to dive into complex code/infrastructures, and find the root cause.
* Excellent communication and presentation skills, able to communicate with business and technical stakeholders also external customers.
* Shipped one or more apps in the Store.
* A person who wants to become a playing manager in the future, or is interested in management

### Responsibilities

* Develop and maintain our service
* Developing a clean and maintainable code
* Discussing about architecture with the team
* Training for junior/middle software engineers
* Deliver outputs with expected quality, speed in order to bring the best values to service

### Why it would be awesome to work with us
* No probation applied for technical positions (all levels)
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee
Interesting engineering projects

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009
Phone: 0906 516 291 (Direct call/Zalo/WhatsApp/Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
