### ISSUE TITLE
MONSTARRIOR - C++ Engineer 

### ISSUE THREAD

**Issue by trungnguyen2CS** [awesome-jobs/vietnam#2886]
## Location

* Vietnam
* Remote

## Salary Range

* $1000 to $1500

## Responsibility

- Use C/C++ language to develop EOS smart contract.
- Maintain and extend existing smart contract projects serving 10.000+ daily users.
- Research, design, develop, and test blockchain technologies.
- Document new solutions as well as maintain that of existing ones.

## Skills

- Experience working with C/C++ projects.
- Strong knowledge of common algorithms and data structures.
- Strong knowledge of STL, C++11.

### Contact
Homepage: https://monstarrior.io/
Skype: nguyenthitrunglopa1
Mail: trung.nguyen@2clicksolutions.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by trungnguyen2CS** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

Sorry for wrong email, I have updated my company email, please check again

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
