### ISSUE TITLE
Yojee - React Native Engineer  - Saigon, District 4 - FT

### ISSUE THREAD

**Issue by Lilyyojee** [awesome-jobs/vietnam#2888]
## Location

* District 4, Saigon, Vietnam

## Salary 

* Negotiate 

## About the role

Yojee is looking for a React Native Developer to join our Engineering team, to develop and maintain our mobile applications and support for the entire application lifecycle. This candidate should also appreciate the notions of their running efforts which will empower and enhance the logistic services for potentially millions of users across a wide variety of industries.

## Requirements

* Minimum Bachelor Degree in Computer Science or Computer Engineering or its equivalent.
* 2-3 years of relevant experience in mobile development.
* Being able to write well-documented, clean JavaScript/Typescript code.
* Familiar with modern FE development toolchain: NPM, Babel, ESLint, Flow, Jest, etc
* An understanding of React Native best practices and a commitment to following them.
* Familiarity with code versioning tools such as Git.
* Good understanding of the full mobile development life cycle.
* Able to work independently, self-directed and solutions-oriented.
* Excellent working attitude, problem-solving, and willingness to tackle any challenges.
* Effective written/oral communication skills and ability to communicate ideas effectively to a corporate audience and excellent interpersonal skills.
* Proficient in English.

### Nice to have 
* Knowledge of Ruby on Rails, Elixir, and being a polyglot is a bonus.
* Ability to learn new technologies and APIs.

## Responsibilities

* Design and build advanced logistics applications for mobile apps/platforms.
* Collaborate with cross-platform and product development teams to define interfaces and ensure feature interoperability.
* Identify performance improvements and efficiency optimizations for implementation, build, and deployments of the technology.
* Architect, build, and maintain our React Native applications with clean code.
* Implement UI from specifications provided by the UX/UI team.
* Undertake any other ad-hoc work as assigned.
* May be required to perform other related duties as required.

## Why it would be awesome to work with us

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ). We are growing our team in Vietnam which is developing our core product. Don't miss this opportunity to join us early.

* Performance bonus: equivalent to 1-3months salary based on your performance
* Provided Macbook pro
* Occasional onsite trip to Singapore, Indonesia
* International environment : Australia, India, Singapore, Indonesia, Vietnam,..
* No 13th month salary
* Unlimited paid day off
* 100% official salary in probation time
* Full social insurance paid based on salary
* Free parking 

## About Yojee

Yojee Limited (ASX: YOJ) is a cloud based (SaaS) logistics platform that seamlessly and uniquely manages, tracks and optimizes freight movements along the entire logistics chain, from sender to end customer, across borders and between logistics providers (land, sea, air), with subcontractors and for multi-leg journeys. Rarely is a single carrier servicing an entire goods journey from sender to end customer, or exclusively using one type of transportation method. Yojee ensures connectivity and more efficient planning along the entire journey.

### About the Engineering team at Yojee

The backbone of Yojee focused on building the core platform and product using best in class technology. We love clean code, well-designed architecture and applying best practices.  We build cool technology that lasts long and scales well.

### How to apply

Please apply [here ](https://yojee.bamboohr.com/jobs/view.php?id=119&source=Github) if you are interested in. 

### Contact
Homepage: Yojee.com
Lily: lily@yojee.com
Phone: 0924605299

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
