### ISSUE TITLE
Techcombank - Data Engineer (Scala, Java, Python) - Hanoi/Saigon - FT

### ISSUE THREAD

**Issue by htrang167** [awesome-jobs/vietnam#2889]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
We are looking for **Data Engineers** who are fully capable of handling software development and have an interest in Big Data technologies.

### Must Have

* Proficiency in Scala/Java/Python
* Solid knowledge in Computer Science fundamentals
* Interest and passion to "dig deep" into Big Data tech stacks (e.g. Hadoop, Spark, Flink, Kafka, etc.)

### Ideally

* Experience with AWS, high availability and scalability is a plus
* Experience with highly parallelized, distributed, extremely large volumes of all sorts of data is a plus
* Familiarity with Rust/Kotlin for backend development is a plus

### Responsibilities
A **Data Engineer** is expected to take initiative in experimenting with various technologies and tools with the vision of creating innovative data-driven solutions for the business.

### You’ll be responsible for

* Deliver functionality required for business and data analysts, data scientists and other business roles to advance the overall analytic performance and strategy of the bank.
* Build the best practices and strategies for data infrastructure to fulfill data analytic and utilization needs of the business with emerging latest technologies and capabilities.
* Drive the delivery of data products and services into systems and business processes in compliance with internal regulatory requirements.
* Strategically obtain and integrate data and information from various sources into the firm’s platforms, solutions and statistical models.
* Design, build, and maintain optimized data pipelines and ETL solutions as business support tools in providing analysis and real time analytics platform for critical decision making.

### You can bring

* Bachelor's or Master’s degree in Statistics, Mathematics, Quantitative Analysis, Computer Science, Software Engineering, Information Technology or any other Numerical disciplines.
* Relevant experience with developing, debugging, scripting and employing big data technologies (e.g. Hadoop, Spark, Flink, Kafka, Arrow, Tableau), database technologies (e.g. SQL, NoSQL, Graph databases), and programming languages (e.g. Python, R, Scala, Java, Rust, Kotlin) with preference towards functional/trait oriented.
* Experience in designing and building dimensional data models, ETL processes, applied data warehouse concepts and methodologies, optimized data pipelines.
* Has the know-how and the scripting and coding prowess to set up, configure & maintain a machine learning model development environment.

### Why it would be awesome to work with us
**Techcombank** is one of the leading commercial banks in Vietnam going **“Cloud First” with AWS**, pioneering in **Digital Transformation** and **ML/AI-enabled Technology** to transform customer experience and become the central fintech hub in the region. Techcombank will migrate the majority of applications from on-premises infrastructure to AWS, taking advantage of the cloud’s scalability, and build an integrated Data Platform to leverage the Cloud’s Data Analytics capabilities. This platform will enable the bank to make decisions in real-time, understand customers better, accelerate the innovation of new products and services, and enhance customer service and online experience.

For more information, please see this article: [Link](https://technuter.com/breaking-news/techcombank-goes-cloud-first-with-aws-to-transform-customer-experience.html)

### Contact: 
**Trang Nguyen**
Email: trangnh.rpo@techcombank.com.vn
Telegram: https://t.me/htrang167
Skype: live:htrang167

**Comment by htrang167** [comment]
@lactroi Hi, could you please update the tags with programming languages? Thanks in advance.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
