### ISSUE TITLE
Jenfi - Senior Ruby on Rails - Vietnam - Remote FT

### ISSUE THREAD

**Issue by admin-tony** [awesome-jobs/vietnam#2893]
## Location

* Vietnam
* Remote

## Salary Expectation

* $2,000-3,000/month

## Requirements
* Has shipped and iterated multiple features
* 5+ years of experience with Rails as Full Stack Engineer
* University degree in Computer Science, Engineering or equivalent
* Strong command of English language

## Skills
*Experience with Ruby on Rails, RSpec
* Senior level understanding of the syntax of Ruby and its nuances
* Good understanding of Ruby/Rails ecosystem, gems
* Ability to integrate multiple data sources and databases into one system
* Understanding of fundamental design principles behind a scalable application
* Familiarity with CI/CD, AWS, Docker

### You’ll be responsible for

Architecting and managing Jenfi’s business logic and data structures. Your primary focus will be development of server-side logic, definition and maintenance of the central database, and ensuring high performance and reliability to the end user.

### Contact
Homepage: jenfi.com
Trollman: tony_at_jenfi_dot_com (mobile number optional)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
