### ISSUE TITLE
Ascenda Loyalty - Senior Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by longkt90** [awesome-jobs/vietnam#2896]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* US$3000 - $5000 / month 

## Requirements
You are a good fit if you:

* Strong technical background in building trafficked large scale frontend applications on a modern frontend stack
* Have strong knowledge of how modern web applications work 
* Have strong fundamentals in Javascript
* Have experience building responsive web applications that work well across multiple devices and resolutions
* Have a good appreciation for web accessibility and internationalisation (i18n)
* Have a good understanding of quality code and the role of automated testing
* You enjoy working with cross-functional teams across the organization, and across multiple geographical locations
* You have previous experience with our frontend stack (Angular, Typescript). This would be a plus but not necessary. 

## Job description

Ascenda solutions make loyalty simple for financial institutions globally. Previously, these companies had to endure complex patchworks of third-party systems, mediocre user experiences, and 18-month implementation projects to deploy a competitive rewards program. We turn things upside down with loyalty solutions rooted in beautiful design, exceptional customer value, and rapid implementation.

The Frontend Engineering team builds and maintains our beautiful frontends that empower millions of consumers to transact using their loyalty points. From booking a dream vacation, to converting loyalty points to cash back on their credit cards and redeeming gift cards. These are some of the features that our well designed, performant and accessible frontends enable. We place a high degree of focus on building highly reusable and configurable design systems. As we continue to scale this platform to serve a wider array of financial institutions, our design system enables the creation of highly customisable and themed frontends to serve the greater needs of consumers.

In this job you will:

- Work closely with fellow likeminded engineers on a critical user interface used by millions of users worldwide
- Be a core contributor and have a say in how our design system grows and evolves to meet business requirements
- Solve many interesting and challenging problems that come with building highly configurable and dynamic frontends
- Play a key role in designing and building great monitoring and observability in our frontends
- Be part of setting the standard for best practices across the engineering organisation, especially across our frontend chapter
- Work closely with designers, UX engineers, product owners, and engineers from multiple teams to develop and design solid user experiences
- Contribute to the growth of junior developers, and of Ascenda’s engineering culture
- Have the opportunity to solve problems across multiple areas, such as performance, internationalization, and multi-tenancy

This role is open for our Vietnam Office, located in Ho Chi Minh, District 2. Remote 100% can be considered.

### Contact

Apply directly via https://careers.ascendaloyalty.com/o/senior-frontend-engineer-core-fintech-platform

Check out other roles we are hiring: https://careers.ascendaloyalty.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
