### ISSUE TITLE
Techcombank - Senior Cloud Engineer (AWS) - Hanoi/Saigon - FT

### ISSUE THREAD

**Issue by htrang167** [awesome-jobs/vietnam#2897]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
We are looking for **Senior Cloud Engineers** to join our **Cloud Journey** migrating the whole Infrastructure from On-Premise to AWS Cloud.

### Must Have

* In-depth knowledge of Amazon Web Services (AWS)
* DevOps/SecOps/NetOps/SysOps experience

### Ideally

* Experience with Infrastructure as Code (IaC)
* Experience with Kubernetes (K8s)
* Ability to learn/use open source technologies 

### Responsibilities
A **Senior Cloud Engineer** is expected to design & implement cloud-based technology solutions for units/projects in the whole Bank.

### You’ll be responsible for

* Analyze the needs of units and help them choose the right cloud technology. Deploy cloud solutions, consider potential effectiveness and risk of cloud solutions.
* Perform tests and evaluate the effectiveness as well as the security of cloud solutions
* Identify risks and coordinate with related units to propose methods to measure and minimize risks in operations.
* Make recommendations, improvements and enhancements through continuous assessment of security threats and vulnerabilities in the cloud.
* Ensure the cloud solutions align with service quality, comply with the Bank's regulations and policies.

### You can bring

* Bachelor's or Master’s degree in Computer Science, Software Engineering, Information Technology or any other IT disciplines.
Hands-on experience in deploying and maintaining Cloud infrastructure as code (Terraform, Cloudformation, GitOps).
* Strong understanding of how to secure Cloud environments and meet compliance requirements.
* Ability to learn/use a wide variety of open source technologies/tools (Docker, Jenkins, Ansible, Puppet, k8s), and programming languages (Bash, Python, Golang).
* Having AWS Certificates is a plus (not a must), we believe in your hands-on experience over certificates.

### Why it would be awesome to work with us
**Techcombank** is one of the leading commercial banks in Vietnam going **“Cloud First” with AWS**, pioneering in **Digital Transformation** and **ML/AI-enabled Technology**, migrating the majority of applications from on-premises infrastructure to AWS, taking advantage of the cloud’s scalability. Transforming our workforce with AWS cloud skills is key to achieving our vision of enabling individuals, businesses, and corporations to progress and thrive sustainably. By building cloud capabilities and leveraging AWS, we strengthen our resilience, and can focus on innovating financial products and services faster to solve customer challenges and uplift communities.

For more information, please see this article: [Link](https://technuter.com/breaking-news/techcombank-goes-cloud-first-with-aws-to-transform-customer-experience.html)

### Contact: 
**Trang Nguyen**
Email: trangnh.rpo@techcombank.com.vn
Telegram: https://t.me/htrang167
Skype: live:htrang167

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
