### ISSUE TITLE
Techcombank - Senior Data Platform Developer (DWH, ETL) - Hanoi/Saigon - FT

### ISSUE THREAD

**Issue by htrang167** [awesome-jobs/vietnam#2898]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
We are looking for **Senior Data Platform Developers** who are responsible for **transitioning data workloads to the Cloud**.

### Must Have

* Strong experience in DWH, ETL and Data Modeling
* Experience with Cloud technologies (AWS is preferred), the stronger the better

### Ideally

* Experience in Banking & Financial Services is a plus
* Experience with highly parallelized, distributed, extremely large volumes of all sorts of data is a plus

### Responsibilities
A **Senior Data Platform Developers** is expected to build out the data pipelines (data ingestion framework and ETL processing) that are scalable and reusable on both On-Premise & Cloud platforms.

### You’ll be responsible for

* Design, create and maintain optimal data pipeline architecture
* Assemble large, complex data sets that meet functional/non-functional business requirements
* Identify, design, and implement internal process improvements: automating manual processes, optimizing data delivery, re-designing infrastructure for greater scalability, etc.
* Build the infrastructure required for optimal extraction, transformation, and loading of data from a wide variety of data sources using SQL and Cloud technologies
* Work with stakeholders including the Executive, Product, Data and Design teams to assist with data-related technical issues and support their data infrastructure needs
* Able to work in a fast-paced, multi-site location, team-oriented environment

### You can bring

* Advanced working SQL knowledge and experience working with relational databases, query authoring (SQL) as well as working familiarity with a variety of databases.
* Knowledge of modern Cloud computing platforms and concepts
* Experience with data warehousing architecture and data modeling
* Experience performing root cause analysis on internal and external data and processes to answer specific business questions and identify opportunities for improvement.
* Experience in manipulating, processing and extracting data from various source systems.

### Why it would be awesome to work with us
**Techcombank** is one of the leading commercial banks in Vietnam going **“Cloud First” with AWS**, pioneering in **Digital Transformation** and **ML/AI-enabled Technology** to transform customer experience and become the central fintech hub in the region. Techcombank will migrate the majority of applications from on-premises infrastructure to AWS, taking advantage of the cloud’s scalability, and build an integrated Data Platform to leverage the Cloud’s Data Analytics capabilities. This platform will enable the bank to make decisions in real-time, understand customers better, accelerate the innovation of new products and services, and enhance customer service and online experience.

For more information, please see this article: [Link](https://technuter.com/breaking-news/techcombank-goes-cloud-first-with-aws-to-transform-customer-experience.html)

### Contact: 
**Trang Nguyen**
Email: trangnh.rpo@techcombank.com.vn
Telegram: https://t.me/htrang167
Skype: live:htrang167

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
