### ISSUE TITLE
Techcombank - DevOps Engineer (Docker, Kubernetes) - Hanoi - FT

### ISSUE THREAD

**Issue by htrang167** [awesome-jobs/vietnam#2899]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Requirements
We are looking for **DevOps/DevSecOps Engineers** who will assist to build and maintain The Continuous Delivery Pipeline (CDP), which represents the workflows, activities, and automation needed to shepherd a new piece of functionality from ideation to an on-demand release of value to the end user. The pipeline consists of four aspects: **Continuous Exploration (CE), Continuous Integration (CI), Continuous Deployment (CD), and Release on Demand (RoD)**.

### Must Have

* Docker
* Kubernetes (K8s)

### Ideally

* Openshift is a plus
* AWS is a plus
* Security/SecOps is a big plus

### Responsibilities
A **DevOps/DevSecOps Engineer** is expected to embed the security into DevOps and build a highly automated DevSecOps.

### You’ll be responsible for

* Build, map and optimize the delivery of the Continuous Delivery Pipeline (CDP) by addressing key elements like process time, lead time, delay time and percent of complete and accurate and visualize the progress of these processes on the kanban project.
* Continuous Exploration (CE) – understand the market problem/customer need by analyzing and researching to identify the solution required to meet that need, from which suggest the development of new features or modification from existing architectures, define and prioritize activities in the Program Backlog.
* Continuous Integration (CI) – take features from the Program Backlog and implement them to deliver a completed work which is committed to version control, built and integrated into a full system or solution, and tested end• to• end before being validated in a staging environment.
* Continuous Deployment (CD) - take the changes from the staging environment and deploy them to production.
* Release on Demand (RoD) - make value available to customers all at once, or in a staggered fashion based market and business needs.

### You can bring

* Bachelor's or Master’s degree in Computer Science, Software Engineering, Information Technology or any other IT disciplines.
* Relevant experience in DevOps/DevSecOps
* Experience with Docker, Kubernetes (K8s), Containerization, etc. and deploying applications
* Solid foundation of Linux administration
* Ability to learn/use a wide variety of open source technologies and tools

### Why it would be awesome to work with us
**Techcombank** is one of the leading commercial banks in Vietnam going **“Cloud First” with AWS**, pioneering in **Digital Transformation** and **ML/AI-enabled Technology**, migrating the majority of applications from on-premises infrastructure to AWS, taking advantage of the cloud’s scalability. Transforming our workforce with AWS cloud skills is key to achieving our vision of enabling individuals, businesses, and corporations to progress and thrive sustainably. By building cloud capabilities and leveraging AWS, we strengthen our resilience, and can focus on innovating financial products and services faster to solve customer challenges and uplift communities.

For more information, please see this article: [Link](https://technuter.com/breaking-news/techcombank-goes-cloud-first-with-aws-to-transform-customer-experience.html)

### Contact: 
**Trang Nguyen**
Email: trangnh.rpo@techcombank.com.vn
Telegram: https://t.me/htrang167
Skype: live:htrang167

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
