### ISSUE TITLE
Mobile Developer (React Native)

### ISSUE THREAD

**Issue by leovinh** [awesome-jobs/vietnam#290]
## Company

Cititech is the Vietnam leader in innovative technology that leads the hospitality industry. We are always looking for bright and driven people who have a penchant for technology and want to hone their skills. If you are interested in challenging work, being part of Cititech team, and solving complex problems through technology.

## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Requirements

- Reasonable experience with React, React Native, React Stylesheet & Redux (We know it’s new)
- or strong experience with AngularJs, BackboneJS
- Strong and professional experience using
- ECMA Script 6
- Solid understanding of software architecture best practices
- REST APIs
- Realtime application event based design patterns
- Webpack, babel, Node

### Must Have

We are building our apps in React Native. If you don't have experience in React Native, that's okay. We are open to someone who has React.js experience with a passion for mobile and willingness to learn React Native or someone who is a rockstar mobile developer that wants to dive into the React Native world. It's more important to us that you have the technical chops and aptitude, passion to learn React Native and confidence in the business we're building.

### Ideally

* Experience with NodeJS, MongoDB, Native mobile dev (iOS, Android).

### Responsibilities

Join team build app [Grabhotel](http://grabhotel.co/) version iOS & Android with React Native.

### You’ll be responsible for

* Building a new Facebook

### Contact

Vinh via e-mail >> vinh@cititech.xyz

**Comment by joneslee85** [comment]
@leovinh thanks for submitting the job with us. Please revise the format of the post to ensure it meets our [guideline](https://github.com/awesome-jobs/vietnam/blob/master/README.md).

**Comment by joneslee85** [comment]
I am closing this job post as no amendment has been made
