### ISSUE TITLE
Groove Technology - Mid/ Senior .NET Developer (ASP .NET MVC) - Saigon - FT

### ISSUE THREAD

**Issue by tonynguyen11** [awesome-jobs/vietnam#2900]
## Location

* Saigon, Vietnam

## Salary Expectation

* Upto $1700

## Requirements
* 3+ years .net
* Experience with the ASP.net MVC
* Experience with MS SQL
* Experience with WCF and web API and IIS
* Experience working with 3rd party APIs as Google, Apple, Facebook,...
* Experience with a message broker/message bus framework such as nServiceBus or similar.

### Must Have

* ASP .NET MVC
* MS SQL

### Ideally

* Experience with JavaScript
* Experience with Lucene
* Experience with RavenDB
* Experience using an ORM library such as nHibernate
* Good speaking 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Participate in requirement analysis, estimation, implementation, code review, unit test, test and
deployment process.
* Identify and mitigate risk in the project’s implementation
* Optimize SEO, Mobile, UI/UX, Page Speed, Performance
* Build/Maintain/Create new function on the website
* Write reusable and clean code
* Contributing to documentation (instructional and technical specification)
* Report to the Project Manager and Tech Lead.
* Collaborate with team members and stakeholders
* Work directly with foreign customer in AU

### You can bring

* Critical thinking, creativity, troubleshooting.
* Good time management, software project management and planning skills.

### Why it would be awesome to work with us

* 13th month salary and 14 annual leave.
* Medical and Accident Insurance program.
* International, dynamic, friendly working environment.
* Clear and stable career growth.
* Many opportunities for personal and professional development.
* Professional training, English course
* Company trip and regular team building events, sports activities…
* Quarterly party: For any staff who has birthday and newcomers in the quarter
* Game: Table football, ping-pong, Play Station 4 …

### Interesting engineering projects

* Work regularly with server, domain, aws service, api, machine learning…
* Build user-centric culture
* Truly value members' opinions
* Friendly & sharing working environment

### Contact
* Homepage: Groovetechnology.com
* Email: toan.nguyen@groovetechnology.com
* Skype: skyfall_0508

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
