### ISSUE TITLE
Groove Technology - Mid/ Senior .NET Developer (.NET Core) - Saigon - FT 

### ISSUE THREAD

**Issue by tonynguyen11** [awesome-jobs/vietnam#2901]
## Location

* Saigon, Vietnam

## Salary Expectation

* Upto $2000

## Requirements
* 3+ years working as an Engineer delivering projects using the Microsoft stack with C# .NET
Framework or .NET Core
* Experience creating, maintaining, optimizing and writing queries for relational database: MS SQL
Server,..
* Experience with data parsing - knowledge of regular expression, HTML, DOM, and XPATH
* Experience with a message broker/message bus framework such as AWS SQS, RabbitMQ,
nServiceBus or similar.
* Experience using various dependency injection frameworks such as Ninject, Autofac, Unity, Spring
etc.
* Experience building and integrating with RESTful web services built using ASP .NET Web API or
ASP .NET Core.
* Experience with source control systems such as SVN or GIT.
* Ability to work independently with little supervision.

### Must Have

* .NET stack
* AWS
* Web API

### Ideally

* Experience with ETL or data transform/processing project.
* Experience with AWS: SQS, S3, Lambda, ... or similar.
* Experience with website crawling/parsing.
* Experience with data manipulation/wrangling.
* Experience with .NET Core.
* Experience using an ORM library such as Entity Framework.
* Exposure to any kind of No-SQL database technologies.
* Experience integrating with 3rd party systems

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Work directly with foreign software engineers in AU.
* Using, modifying and maintaining ETL/data-pipeline/parsing framework to work with multiple
data source.
* Reporting to the Project Manager and Tech Lead.
* Liaising with the key stakeholders of the project.
* Delivering fully implemented vertical feature sets based on the specification within estimates and
without defects.
* Identify and mitigate risk in the projects implementation.
* Participating in code reviews.
* Designing and optimizing tables and queries for MS SQL Server.
* Lead and mentor less senior members of the team.

### You can bring

* Critical thinking, creativity, troubleshooting.
* Team work.

### Why it would be awesome to work with us

* 13th month salary and 14 annual leave.
* Medical and Accident Insurance program.
* International, dynamic, friendly working environment.
* Clear and stable career growth.
* Many opportunities for personal and professional development.
* Professional training, English course
* Company trip and regular team building events, sports activities…
* Quarterly party: For any staff who has birthday and newcomers in the quarter
* Game: Table football, ping-pong, Play Station 4 …

### Interesting engineering projects

* Work on trending technologies: .NET Core, AWS, ...
* Propose technical solutions
* Work closely with project owner (Co-founder) from Australia
* Friendly & sharing working environment

### Contact
* Homepage: Groovetechnology.com
* Email: toan.nguyen@groovetechnology.com
* Skype: skyfall_0508

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
