### ISSUE TITLE
Groove Technology - .NET Tech Lead (Azure) - Saigon - FT

### ISSUE THREAD

**Issue by tonynguyen11** [awesome-jobs/vietnam#2902]
## Location

* Saigon, Vietnam

## Salary Expectation

* Attractive salary

## Requirements
* Bachelor degree in Computer Science, Computer Engineering, Mathematics or in a related field.
* Have 5+ years of experience using .NET development environment, understand basic server
commands.
* Experience in .NET Core
* Have a solid understanding of OOP, Coding Principles, Design Patterns, and Architectures.
* Hand on Web Development technologies using Jquery, AngularJS, HTML5/CSS3.
* Strong at database modelling and understanding of transactions.
* Able to obtain a deep knowledge of the project technologies and work independently.
* Effective use of source control system including branching, merging code, and create pull
requests.
* Experience in mentoring, supporting, and doing code review.
* Able to self-learn and adapt to new technologies quickly.
* Strong leadership skills, both organizational and technical.
* The confidence to communicate your own technical ideas in an open forum and to encourage
your team mates to communicate theirs.
* Excellent English communication skills.
* Familiar with Agile development methodologies.

### Must Have

* .NET Core
* Strong in Azure DevOps (CI/CD)
* Strong leading skill

### Ideally

* Azure certification
* Experience using Jira and Confluence
* BS’c degree in Computer Science or relevant field
* Logistics domain experience

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Work with UK Technical Architect on “Core Technology” Product development.
* Build and maintain deep-level knowledge of Core Tech approved development
frameworks/platforms, i.e. Azure, .NET Core, .NET Framework, SQL, AngularJS, Node.js.
* Responsible for the coaching and mentorship of the offshore development teams in the
application of Core Technology.
* Help drive quality through performing code reviews, ensuring adherence to existing standards
and processes while providing input into further improvement measures.
* Maintain awareness of all concurrent development workstreams, help resolve technical
blockers, reduce conflicts between workstreams, and identify potential synergies for improved
efficiency.
* Lead the onboarding process for all new development recruits.
* Be a senior technical advisor to the Development Manager; help identify strengths, weaknesses,
opportunities, and threats within the team

### You can bring

* Critical thinking, creativity, troubleshooting.
* Team work.

### Why it would be awesome to work with us

* 13th month salary and 14 annual leave.
* Medical and Accident Insurance program.
* International, dynamic, friendly working environment.
* Clear and stable career growth.
* Many opportunities for personal and professional development.
* Professional training, English course
* Company trip and regular team building events, sports activities…
* Quarterly party: For any staff who has birthday and newcomers in the quarter
* Game: Table football, ping-pong, Play Station 4 …

### Interesting engineering projects

* Work closesly wit Technical Architect in UK
* Join in 1 of our biggest and the most challenging project 
* Work on a large database
* Career path: promotion to Software Architect in near future

### Contact
* Homepage: Groovetechnology.com
* Email: toan.nguyen@groovetechnology.com
* Skype: skyfall_0508

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
