### ISSUE TITLE
Cohart Inc - Senior Back End Developer (AWS) - Remote/HCMC - Contract

### ISSUE THREAD

**Issue by trinh211** [awesome-jobs/vietnam#2905]
## Location
* Remote
* After covid, there will be an office in HCMC, but remote work can continue

# Job Overview
Cohart is a global discovery platform for art and creativity which uses personalization algorithms to match Creators, Curators, and Collectors, enabling them to build relationships, exchange ideas, and buy and sell directly.
We are urgently looking for an experienced Full Stack freelancer to assist in building products for the global creator markets.

# Salary Expectation
* $20 - $30 per hour
* 3 months initially with extensions very likely

# Requirements
* Degree or equivalent
* No Degree + 3 additional years experience
* Excellent written and moderate spoken English
* 3 years+ writing server side service functions either as part of a micro services and/or full serverless architecture.

# Skills
## Required
* Fluent in the JavaScript and/or TypeScript language and its nuances, including ES6+ syntax
* Know how to write, deploy and debug serverless functions implemented using serverless.com (using AWS services such as ApiGateway, Lambda, CloudFormation, IAM, S3, CloudWatch, Secrets Manager, etc.)
* Experience with MongoDB writing performant queries/updates and know techniques for maintaining a consistent database when using NoSQL technologies
* Know about AWS service limits and their implications/consequences
* Understand what it means to design Rest APIs and document them clearly using Swagger or similar.
* Experience with automated testing suites and familiarity with unit tests like Jest or Mocha
* Familiarity with code versioning tools Git
* Knowledge of modern functional programming or object-oriented programming
* Ability to write well-documented and clean Typescript/Javascript code

## Ideally
* Ability to set up, maintain and operate CI/CD pipelines that deploy to AWS
* Knowledge of other AWS Services such as Route53, VPCs, CloudFront, Cognito
* Ability to design solutions using the full AWS service suite
* Have experience of the challenges and techniques of designing, building and running high volume transactional distributed systems.

# Responsibilities
* Working with team members to understand and implement feature designs
* Identify and estimate tasks for feature design implementation
* Writing tests to ensure implementation meets design requirements
* Create PRs for review before code merge
* Take part in review of PRs from other team members
* Working with technical lead to continuously improve code design and implementation 
* Work together with other developers on backend API designs
* Assist writing integration and performance tests (sometimes)
* Fixing bugs identified during acceptance and user testing

# Why it would be awesome to work with us
* Leading the way in the passion economy for artists and creators * Exciting technology and problem solving
* Attractive VN freelance rates
* Fun and young dynamic team
* Regular VN working day
* VN public holidays and time off when you need it
* Post covid, local get togethers in HCMC

# About Us
**Website:** https://www.cohart.co/
**Linkedin:** https://www.linkedin.com/company/joincohart/
**Download app:** https://apps.apple.com/vn/app/cohart/id1554034352

# Contact
Please send your CV and introduction to: hello@cohart.co or/and trinh@cohart.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
