### ISSUE TITLE
Cohart Inc - Senior Front End Developer (React Native) - Remote/HCMC - Contract

### ISSUE THREAD

**Issue by trinh211** [awesome-jobs/vietnam#2906]
# Location
* Remote
* After covid, there will be an office in HCMC, but remote work can continue

# Job Overview
Cohart is a global discovery platform for art and creativity which uses personalization algorithms to match Creators, Curators, and Collectors, enabling them to build relationships, exchange ideas, and buy and sell directly.
We are urgently looking for an experienced React Native freelancer to assist in building products for the global creator markets.

# Salary Expectation
* $20 - $30 per hour
* 3 months initially with extensions very likely

# Requirements
* Degree or equivalent
* No Degree + 3 additional years experience
* Excellent written and moderate spoken English 
* 3 years+ writing mobile applications

# Skills
## Required
* React Native (1yr+ experience)
* React Navigation 5 or 6
* Fluently in the JavaScript and TypeScript language and its nuances, including ES6+ syntax
* Understanding of Rest APIs and offline storage (Using HTTP Services)
* Experiences with automated testing suites and familiarity with unit tests like Jest or Mocha 
* Familiarity with code versioning tools Git
* Knowledge of modern functional programming or object-oriented programming
* Ability to write well-documented and clean Typescript/Javascript code
* Familiarity with native build tools, like XCode, Gradle Android Studio

## Ideally
* Comfortable writing sagas
* Writing Animations
* Working with video player technologies (JWPlayer)

# Responsibilities
* Working with team leader to understand and implement feature designs 
* Identify and estimate tasks for feature design implementation
* Writing tests to ensure implementation meets design requirements
* Create PRs for review before code merge
* Take part in review of PRs from other team members
* Working with technical lead to continuously improve code design and implementation 
* Work together with other developers on backend API designs
* Assist writing integration and performance tests (sometimes)
* Fixing bugs identified during acceptance and user testing

# Why it would be awesome to work with us
* Leading the way in the passion economy for artists and creators 
* Exciting technology and problem solving
* Attractive VN freelance rates
* Fun and young dynamic team
* Regular VN working day
* VN public holidays and time off when you need it
* Post covid, local get togethers in HCMC

# About Us
**Website:** https://www.cohart.co/
**Linkedin:** https://www.linkedin.com/company/joincohart/
**Download app:** https://apps.apple.com/vn/app/cohart/id1554034352

# Contact
Please send your CV and introduction to: hello@cohart.co or/and trinh@cohart.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
