### ISSUE TITLE
TRS SEA - IT Team Leader | E-waller Project - Ha Noi - FT 

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#2907]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Open to nego 

## Requirements
* Bachelor degree in IT or related IT majors. 
* 2+ years of experience in a Team Leader position or equivalent
* 5+ years of experience in software development
* Have experience in developing products related to e-wallets, payment gateways. 
* Experience working with Java, Oracle; Proficient use of management tools sourcecode like Github.
* Ability to build projects from scratch, read and review code for the team;
* Good logical thinking and ability to analyze problems
* Ability to communicate, organize and solve problems.

## Skills
* Technical: Java, Oracle
* Soft skills: team leader, communication, problem solving, management, etc

### Responsibilities
* Lead and manage a team of 6-7 persons. 
* Participating in e-wallet project: analysis, system design, wallet implementation.
* Work, coordinate with other departments and coordinate and divide work in the team.
* Urging, monitoring and supporting the team to ensure the project progress.
* Planning, giving product orientation and solutions when needed.
* Code review, team evaluation;
* Solve problems that arise.
* Writing documents and guidelines for project implementation;
* Report & perform other tasks as required by CTO.

### Why it would be awesome to work with us: 
* Salary range: open to negotiate (Depends on your expectation and experience) 
* Allowances for lunch, phone, travel, business... as required
* Salary review once/year; 13th month salary and quarterly bonuses, project bonuses, periodic bonus, holiday bonus, Tet.
* Insurance paid according to state regulations;
* Buy health insurance and periodical intensive medical examination 1 times/year;
* Participate in company activities: Watching movies, team building, company trip with 5-star quality and other cohesive sports and cultural activities of the company. 

### How to apply:
Send your CV/resume to my email: diepnguyen@r-starsea.com

### Contact
* Email: diepnguyen@r-starsea.com
* Phone/ Zalo: 0374 118 602
* Skype: Diep Nguyen

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
