### ISSUE TITLE
INNOMIZETECH - DEVOPS ENGINEER (JUNIOR/MIDDLE) - HCM  - FT

### ISSUE THREAD

**Issue by thanhthi** [awesome-jobs/vietnam#2909]
## Location

* 2A/64A Bach Dang Street, Ward 2, Tan Binh Dist, HCMC
* Remotely during the Covid-19 Pandemic

## Requirements
* At least 1+ years of experience in systems engineering or DevOps on major infrastructure.
* Expertise in Linux system administration and standard infra components (DNS, Network stack, virtualization, certificates).
* Demonstrable experience with containers (Docker), orchestration (Kubernetes) and autoscaling.
* Experience with service architecture, including service discovery, monitoring and caching such as Apache Kafka, Prometheus.
* Knowledge of provisioning solutions applying infrastructure as code (IaC) such as Terraform, Puppet, Ansible, Gitlab, Jenkins.
* Ability to use a wide variety of open source technologies and cloud services (AWS/ Azure).
* English is required.

### Ideally
* Experience with TDD and UML, in a particular sequence and deployment diagrams, infrastructure as code is code and is governed as such.
* Experience with backup and recovery including data assets.
* Be familiar with other cloud platforms such as GCP, Azure and AliCloud.
* Programming ability in languages such as Python, Go, Kotlin, and Java.
* Experience in MS Windows system administration.
* Blockchain (Hyperledger Fabric), Kong, Nginx, Service Mesh.

### Responsibilities
* Leverage automation and guide the evolution of our code-based infrastructure.
* Own the scalability, availability, and performance of infrastructure and cloud environments.
* Instantly deploy flavours of the environment for disparate use cases, data and different stages of the SDLC including ad hoc requests.
* Infrastructure review taking into account our long term direction ie. serverless, lambda.
* Integrate infrastructure as code into DevOps pipeline, demonstrate quality with tests as per pipeline.
* Own the environmental vision advising the Head of Engineering and CTO.

### Why it would be awesome to work with us
As a start-up company, our team is our highest priority and we welcome new talent to our team. Along
with our young spirit, our aim is to create an ideal and open environment where each person is eager to
work and encouraged by the creative ability of every member of our team.
* We put human development as the first priority.
* We give you challenging and interesting work to develop your career path.
* Flexibility and authorizing culture in our company.
* Activities: Yearly company trips, Year-end Party, Teambuilding, Football Clubs.
* Exciting internal events to help you understand the whole business and make you feel
* like you are part of the Innomize Family.
* Modern and cosy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day,
to make sure your energy level is high when you need it.
* There are a lot of opportunities to learn and grow with training activities weekly such as English,
Management, Soft Skills, Technology.
* Career guidance and support daily from Manager, Leader and Senior Level.
* 13th payment, and extra bonus for excellent employees.
* Salary and promotion review: twice / year
* Promotion opportunities for Senior and Leader level.
* Special bonus on Public holiday.
* Overtime is rarely required, you will get paid for the extra work.

### Contact
Email: hr@innomizetech.com
Skype: thanhthi.hr
Telegram: 0988428440

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
