### ISSUE TITLE
Kitfe - Ruby on rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by TaPhuocHai** [awesome-jobs/vietnam#291]
## Company

Kitfe là một startup về food delivery. 
Kitfe mang đến bữa ăn ngon, chất lượng cho những con người linh hoạt, năng động.

## Location
* Saigon, Vietnam
* Bụi, hơn 1000 địa điểm quán cafe bất kỳ anh em có thể lựa chọn

## Salary Expectation

* Thỏa thuận
* Kinh nghiệm càng nhiều lương càng cao thôi nhé

## Requirements

* Ruby
* Bootstrap/HTML/CSS
* PostgreSQL
* Yêu cầu tối thiếu 2 năm kinh nghiệm làm việc với ruby on rails.
* Không ngại đụng vào frontend nếu cần.
* Làm việc linh động 2 tháng fulltime tại Kitfe

### Must Have

* Xử lý vấn đề nhanh
* Tinh thần trách nhiệm

### You’ll be responsible for

* Chiệu trách nhiệm phát triển thêm tính năng cho Kitfe.com
* Làm việc với các thể loại C (CTO/CEO/COO) để phát triển và hoàn thiện nền tảng cho Kitfe.
* Nếu bạn thích môi trường startup Kitfe. Có thể hòa nhập luôn nếu muốn.

### You can bring

* Có kinh nghiệm về UI/UX tất nhiên là một lợi thế. Biết chỗ nào cần sửa thì nên sửa, chỗ nào cần bỏ thì nên bỏ.
* Có góc nhìn về sản phẩm là điểm cộng.

### Contact

phuochai@kitfe.com (0976786644)

**Comment by joneslee85** [comment]
@TaPhuocHai Thanks for posting with us. FYI, we've just updated our guideline and we now only accept English job post. Please revise the job in accordance to our gudeline.

**Comment by joneslee85** [comment]
I am closing this job now as no amendment made for one week
