### ISSUE TITLE
FETCH TECHNOLOGY - BE/FS Javascript Developer - REMOTE - FT - (2,000 - 3,500 USD)

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2910]
![68643884_2331468343786221_1834116614971195392_n](https://user-images.githubusercontent.com/60914247/134125029-f4e9288b-cb72-45ac-8f67-9c2a323c6fcc.jpg)

# REMOTE
# 2,000 - 3,500 USD
# INTRODUCTION
**a. About Fetch:**
Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About our client**

This product building the most iconic digital men’s clinic in Southeast Asia. They are made up of a bunch of creatives, entrepreneurs and tech-driven individuals. They’re far from the straight-laced corporates that you might imagine pulling the strings behind healthcare companies. They represent a new breed of healthcare companies, at the forefront of revolutionizing how people receive medical treatment.

Our client was founded in the midst of COVID-19, and in a matter of 6 months, they've grown to thousands of patients and hit over 7 figures in Annual Run Rate. They have also been featured on Tech In Asia, Augustman, FM91.3, Vulcan Post, e27, etc. They see themselves continuing to grow to all new heights and therefore are looking for someone with the skills to help them meet the technological demands that come with it.

More than a healthcare company

They cater to men suffering from erectile dysfunction, premature ejaculation and hair loss. However, it is not just another healthcare provider. As part of our broader mission to destigmatize these conditions, they started Ordinary Folk by its. Through Ordinary Folk, they’ll be creating original content - written, spoken and visual. The first episode of their podcast went live recently and it’s available on 7 platforms including Spotify, Apple and Google Podcast. In each episode, they'll be covering unexplored topics from bedroom intimacy to sexual dysfunction with the help of a rotating list of guest stars, from health practitioners to porn stars.

As they expand the team, they’re simultaneously thinking about how they can improve their services and offer more to our customers. They believe that the possibilities are endless, and are always looking for ways to innovate and exceed themselves.

# RESPONSIBILITIES
This is a full-time role and you will become the 25th full-time hire at their company. 

The mission of our client is to provide men with a safe haven for all things men’s health, whether it’s making discreet, affordable and convenient alternatives to receiving treatment more accessible to men, or raising awareness and acceptance of some of the more private conditions that men may feel embarrassed about. 

You’ll be involved in building the most ambitious digital healthcare platform in the region.  

# REQUIREMENT
Your background is less important than the key skills, which might include:

* Great communication and articulation skills (English).
* ReactJS/NextJS framework (SSR – good to have an understanding of onserver-side rendering).
* Good understanding of functional components, React hooks and React lifecycle.
* Good understanding of react debugging tools and optimizing for best performance.
* Worked with common JS libraries such as dayjs, Immutable.js.
* Good understanding of data management tools such a React context and redux.
* Experience building reusable components and libraries for multi-project use.
* Worked with UI libraries such as Chakra UI, material UI and Tailwind CSS.
* Cross-Browser Compatibility and Multi-Device knowledge.
* Worked with codebase written in Typescript.
* The ability to think quickly and integrate 3 rd party APIs like stripe, acuity and many more.
* Good with versioning tools such as Git.
* Worked with deploying CI/CD pipelines and writing automation scripts to improve build process.
* Deploy libraries/packages to NPM and use them as submodules.
* A good understanding and have developed projects in serverless architecture.
* Worked with serverless function providers such as AWS Lambda or Google Cloud Functions with frameworks such as ExpressJs and NestJS.
* Understands the microservice architecture. 
* Worked with ORMs such as Typeform.
* Worked with PostgreSQL.
* Worked with Firebase firestore and authentication.
* Integrate front-end communication with the backend through internal APIs and 3 rd party external SDKs.
* Good eye for translating designs into modular components structure for multiple projects.
* Familiar with RESTful APIs.
* Good understanding of GraphQl.
# WHY YOU‘LL LOVE WORKING HERE
You will be joining a young startup in a growth phase and you will also be working remotely (they don't intend to get an office anytime soon). This means a couple of things: 

* Flexible schedule. You will have a more flexible schedule but you will also have to be prepared to fight fires at odd hours when you least expect. 
* Pull your own weight. As employee 25, you make up 8.3% of our company. There'll be no hand-holding and they expect you to pull your own weight - like everyone else. 
* Things get messy. There's no sugarcoating this. Things are unstructured and processes might be lacking. They're not where they want to be but they're getting there. 
* You must be able to thrive in ambiguous situations (see point above). 
* You are willing to put in the time to get the most out of any opportunity.  

# CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
