### ISSUE TITLE
JobHopin - Senior Backend PHP Developer - REMOTE - FT

### ISSUE THREAD

**Issue by thonguyen2501** [awesome-jobs/vietnam#2911]
**Location**
**REMOTE**

**Salary Expectation**
$1500 - $3000

**Description**
- Develop, record and maintain cutting edge web-based Laravel applications on portal plus premium service platforms 
- Build innovative, state-of-the-art applications and collaborate with the User Experience (UX) team 
- Utilize backend data services and contribute to increase existing data services API       
- Lead the entire web application development life cycle right from concept stage to delivery and post launch support         
- Convey effectively with all task progress, evaluations, suggestions, schedules along with technical and process issues       
- Document the development process, architecture, and standard components 

**Requirements**
- You possess a Degree/Diploma in Computer Science, Engineering or related field.
- You have at least 4 years experience, ideally within a Software Engineer role.
- You possess strong knowledge of PHP and Laravel.
- Good knowledge of MySQL databases.
- You pay strong attention to detail and deliver work that is of a high standard
- You are a strong mentor and coach who can build high performing teams
- You enjoy finding creative solutions to problems

 **Why it would be awesome to work with us**
- 14-16 days off
- Insurance full salary
- 13th month salary

**Contact**
Skype: tho.nguyenthicam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
