### ISSUE TITLE
McKinsey & Company - Full-stacks/ Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by kienf** [awesome-jobs/vietnam#2912]
## Location

* Saigon, Vietnam
* Open to remote from Hanoi

## Salary & benefits

* You'll love it ;)

## Requirements (not all but nice to have)

* JS +/- HTML, CSS, SQL, C#, PHP, Swift, TypeScript, Go
* ES6, Babel, Web Workers, React, Angular, Nodejs
* Package managers (npm), task runners (Gulp, Webpack, Grunt)
* CSS processors (Sass, Stylus), and APIs (WebSocket)
* 5+ years Software Engineering experience

### Must Have

* Ability to write high-quality, self-documenting code using test-driven development techniques
* Familiarity with testing and debugging processes, including unit testing and UI testing
* Fluent English communication skills + international experience 

### Ideally

* Experience with Full-stack development
* Open for Frontend engineers to apply then skill up

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop and maintain advanced features, tools, and applications according to the best practices in UI/UX, front-end to back-end development, and hybrid mobile application development. 
* Test and debug our ever-evolving product line to improve its speed, scalability, and usability across multiple browsers, devices, and web standards. 
* Stay on top of the latest JavaScript frameworks, libraries, and tools in order to apply them when necessary to solve challenges related to web and mobile development. 

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

* Our office culture is casual and social, with an emphasis on education and innovation. 
* We have the freedom to try new ideas, experiment and are expected to be constantly learning and growing. * Truly international environment where you work with colleagues around the globe and in meaningful projects across Asia.

### Interesting engineering projects

*  You’ll join a global team working on everything from IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation across all industries and functions.

### Contact
Full JD and apply here: [https://mck.co/2UCyJtJ](url)
Homepage: https://www.mckinsey.com/business-functions/mckinsey-digital/
Contact: kien_pham (at) mckinsey.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
