### ISSUE TITLE
McKinsey & Company - Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by kienf** [awesome-jobs/vietnam#2913]
## Location

* Saigon, Vietnam
* Open to remote 

## Salary Expectation

* You'll love it ;)

## Requirements
* Java (Spring, Play, etc.)
* Nodejs(Express, Hapi, etc.) 
* Perl, Python, PHP, C/C++, Go, or Ruby (optional)
* 5+ years Software Engineering experience

### Must Have

* Good understanding of how to use/set up several different types of back ends software
* Ability to work with continuous integration and delivery
* Fluent English communication skills + international experience 

### Ideally

* Working knowledge and ability to use frameworks on React or AngularJS
* Knowledge of information security and data protection

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Configure software packages and build custom applications, creating the foundation for rapid and cost-effective implementation of systems that maximize value from day one 
* Test and debug our ever-evolving product line to improve its speed, scalability, and usability across multiple browsers, devices, and web standards. 
* Stay on top of the latest JavaScript frameworks, libraries, and tools in order to apply them when necessary to solve challenges related to web and mobile development. 

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

* Our office culture is casual and social, with an emphasis on education and innovation. 
* We have the freedom to try new ideas, experiment and are expected to be constantly learning and growing. * Truly international environment where you work with colleagues around the globe and in meaningful projects across Asia.

### Interesting engineering projects

*  You’ll join a global team working on everything from IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation across all industries and functions.

### Contact
Full JD and apply here: [https://mck.co/3vBZxH4](url)
Homepage: https://www.mckinsey.com/business-functions/mckinsey-digital/
Contact: kien_pham (at) mckinsey.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
