### ISSUE TITLE
McKinsey & Company - Lead Engineer - Saigon - FT

### ISSUE THREAD

**Issue by kienf** [awesome-jobs/vietnam#2914]
## Location

* District 1, Saigon, Vietnam

## Salary Expectation

* You'll love it ;)

## Requirements
* Experience in high-level programming/ scripting language(s) (e.g. Python, Golang, JavaScript, Java, C++, etc.)
* Fundamental know-how of one or more of the frameworks/ecosystem (e.g. NodeJS, Vue.js, ReactJS, AngularJS, Tomcat, Nginx, Apache)
* Relational data stores (Postgres, MySQL, Oracle, etc) 
* 7+ years Software Engineering experience

### Must Have

* Experience in engineering practices such as code refactoring, design patterns, data structures, CI/CD
* Hands-on experience architecting and implementing software that is deployed in a production environment; good grasp of modular, distributed architecture principles
* Fluent English communication skills + international experience 

### Ideally

* Experience with non-relational DBs is a plus
* Experience with containerization technology, cloud computing services and web services especially in REST API and tools

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Shaping and implementing strategic products to ensuring that our craft stays on the leading edge of technology. 
* Designing end-to-end architectural landscapes as well as creating solutions for new businesses. 
* Maintaining code quality and ensure responsiveness of applications. 
* Collaborating with the rest of the engineering team to design and develop new features and develop applications for both mobile and desktop. 

### You can bring

* A good eyes for architecture design
* A good leadership skill

### Why it would be awesome to work with us

* Our office culture is casual and social, with an emphasis on education and innovation. 
* We have the freedom to try new ideas, experiment and are expected to be constantly learning and growing. * Truly international environment where you work with colleagues around the globe and in meaningful projects across Asia.

### Interesting engineering projects

*  You’ll join a global team working on everything from IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation across all industries and functions.

### Contact
Full JD and apply here: [http://mck.co/3b514ym](url)
Homepage: https://www.mckinsey.com/business-functions/mckinsey-digital/
Contact: kien_pham (at) mckinsey.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
