### ISSUE TITLE
VSHS Pro Academy - Java Team Lead - Hanoi - FT

### ISSUE THREAD

**Issue by mioqee** [awesome-jobs/vietnam#2915]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $2000/month or range

## Requirements
* 2+ experience in Spring Boot, Hibernate, Microservices, Angular, Typescript
* Managing a team of 3-7 employees applying Agile Scrum
* Degree in IT, Computer Science or equivalent.

### Ideally

* Knowledge and experience in one of the technologies Redux, React JS, NodeJS, Asynchronous, Non Blocking IO, Microservices,etc

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Analysis, functional design, database, cloud computing software development, multi tenancy on Java platform; microservices architecture; support web terminal, mobile native app and IoT.
* Project/team management according to Agile Scrum model 
* Details will be discussed during the interview

### Contact
Email: fulfillment@health-revolution.org
Zalo: 0707263328

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
