### ISSUE TITLE
PLUSTEAM GLOBAL - Senior Golang Engineer - Saigon - FT

### ISSUE THREAD

**Issue by moka1812** [awesome-jobs/vietnam#2916]
## Location

* District 1, Saigon, Vietnam

## Salary Expectation

* 2k$-4k$/month

## About project

KoinWorks is the leading P2P lending and building first Neo Banking for SMB's in Indonesia. We look for highly motivated individuals who want to grow rapidly along with the organization.

## Requirements
* Understanding fundamental design principles of scalable application.
* Strong proficiency with Go-Lang and knowledge of Go-Lang frameworks available.
* Creating database schemas that represent and support business processes.
* Integration of multiple data sources and databases into one system.
* User authentication and authorization between multiple systems, servers, and environments.
* Implementing automated testing platforms and unit tests.
* Proficient understanding of code versioning tools, such as Git.
* Good understanding of Kafka.
* Good understanding of Kubernetes.
* Good Knowledge of cloud providers like Ali-Cloud(recomemmded), AWS or GCP.
* Good understanding of third party API integration
* Good understanding of Log management & APM tools.
* Able to communicate with peers and cross team without friction.

## Responsibilities

* Develop new systems and maintain and modify existing systems when required.
* Integration of user-facing elements developed by app developers with server-side logic.
* Writing reusable, testable, and efficient code.
* Design and implementation of low-latency, high-availability, and performant applications.
* Implementation of security and data protection.
* Participation in spint backlog & planning
* Provide analysis at design, implementations and execution phases.
* Review and recommend improvements to existing system designs.

## Why it would be awesome to work with us
Being a member of us, you will experience a youthful, flexible and creative work environment
* Onsite Singapore opportunity.
* MacBook for working.
* Attractive salary and annual salary review
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese
* Extensive on job training, you will always have a chance to work with new emerging technologies
* Social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* 12-day annual leave per year.
* 13th month salary.

## Contact
Email: support@plusteam.io
Phone: 0931959588

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
