### ISSUE TITLE
IPSIP Group - Site Reliability Engineer - Ho Chi Minh, Vietnam - FT

### ISSUE THREAD

**Issue by Nganle0201** [awesome-jobs/vietnam#2917]
## Location

* Sarina Town SH05.01, B4 Street, Sala City, An Loi Dong Ward, District 2, Ho Chi Minh City.

## Who we are

* Founded in 2002, IPSIP Group started with the service for tailored data centers. Established in 2014, IPSIP Vietnam - subsidiary in Vietnam of IPSIP Group completes its panel of IT solutions, including 24/7/365 remote monitoring via their Network Operations Center (NOC), IT infrastructure audit and consulting and development of business solutions.

## Top 3 Reasons To Join Us

* International and multicultural environment
* Continuous learning and internal evolution opportunities
* Opportunity to boost your career

## The Job

* Define the reliability goals of our systems via Service Level Objectives (SLOs)
* Work with other members (overseas) to ensure that the in-scope applications/platforms are meeting performance and stability requirements, this includes managing major incidents to mitigation/resolution
* Build reusable automation to empower multiple teams to achieve their reliability goals, perform post-incident reviews of all major incidents and determine action items required to avoid similar issues/minimize downtime for future incidents
* Influence the product architecture and roadmap to make sure the customer-experienced reliability is always a key consideration when evolving the product
* Build and run production environments in Azure using Infrastructure as code methods
* Work closely with the team to meet the environment setup and service automation needs
* System monitoring & analytics
* Sharing 24/7 rotation as part of the team

## Your Skills and Experience

* Engineering or CS degree
* 3+ years of experience in the production team of a SaaS company, 3+ years of experience working with Microsoft Azure and AZ 301 certification or higher.
* Expertise with infrastructure configuration management and orchestration tools, such as Terraform, Pulumi, etc.
* Expertise in delivering secure, scalable SaaS solutions
* Knowledge of C# programming language
* Awareness and understanding of best practices required to maintain security standards and certifications
* Requires the ability to multitask and work well under pressure
* Ability to think outside-of-the-box to generate creative solutions to problems

### Bonus Points

* Previous experience working with Jira, Confluence and Git-Hub
* Experience working within an international team
* Experience with MS windows server

## Why You'll Love Working Here

* Medical Healthcare Insurance to take care of you and your family
* Chance to work in Europe, Japan, US
* Tet bonus, salary review 1 time/year or when you have excellence achievement
* Great chance to develop your skills and competences, with Inner training and approach new technologies
* Opportunities for promotions and career development in a dynamic
* Company trip, many exciting activities for team building
* Free parking, coffee and tea

### Contact
* Email: [nganleqm@gmail.com](https://nganleqm@gmail.com/)
* Or LinkedIn: [Lê Quỳnh Minh Ngân](https://www.linkedin.com/in/l%C3%AA-qu%E1%BB%B3nh-minh-ng%C3%A2n-674842203/)
* IPSIP Vietnam
[https://www.ipsip.eu/](https://www.ipsip.eu/)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by Nganle0201** [comment]
Dear Admin,

Thanks for your comment. I currently work as HR executive Intern for IPSIP Group. Therefore, I am waiting for approved company email but I believe that it takes a lot of time. 

During this waiting time, would you please approve my job posting for ensuring the workflow?

Thank you very much for your understanding and support!

Best regards,
Minh Ngân
