### ISSUE TITLE
NAKIVO - Senior Java Developer - HCM/Remote - Fulltime

### ISSUE THREAD

**Issue by huongnguyenhr** [awesome-jobs/vietnam#2919]
## Location

* **Halo Building**, 16 Le Quy Don, Ward 12, Phu Nhuan District, HCMC. (Currently working online 100% due to Covid-19)
* Remote working for candidates living in Hanoi and Danang.  

## Salary Expectation

* $1800 - $2400 

## Requirements: 
* Strong understanding of object-oriented, design patterns and programming principles
* Fluency in Java 8 and relevant ecosystem.
* Knowledge of Spring framework, Hibernate, ExtJs, Design patterns.
* Good at JavaScript, SQL, HTML, CSS.
* Able to quickly learn and work with new APIs, SDKs.
* Able to follow existing code standards.
* Able to write module, clean and well tested code.
* Knowledge of web and network programming, multi-threaded, virtualization and cloud computing
* Able to analyze and design system
* Able to use SVN
* At least 5 years of experience in relevant position.
* Intermediate level in English.

### Ideally

* You would be a strong candidate, if you have one of these following: Jira, Confluence, TeamCity, VMware, Hyper-V, AWS EC2, IntelliJ IDEA, Eclipse, Linux bash, PowerShell.

### Responsibilities

* Investigate, analyze, design, and estimate new features based on written specification.
* Implement the feature, full stack, working independently with minimum guidance.
* Work with others department: PM, QA, Support, etc. to resolve the problems and complete assigned tasks.
* Work in parallel tasks.
* Ensure the best code quality personally.

### Why it would be awesome to work with us

The Nakivo team in Vietnam has been changing very fast in the recent years, we have grown from a group of 6 engineers to the current team size of 80 and we are expecting to grow even more in the next following years. 

We welcome and embrace people, regardless of their background, religion, nationality or gender, but focus on diversity, contribution, determination and work ethic. At Nakivo, we are trying to improve everyday, to become a competitive choice for talented people, by offering

* Flexible working hours: Office opens from 6.00 AM to 10.00 PM
* 13-month bonus & performance bonus
* 100% salary on probationary period
* Private health care package
* Premium health care check
* Gift (cash/voucher) for every special occasion: New Year's Eve, Tet holidays, International Women's Day, International Children's Day, Mid-Autumn Festival and Birthday
* Up to 15 annual leaves/year and additional leaves (up to 3 days)
* Team building
* Free and un-limited snack, tea, coffee and by-choice request.

### About Nakivo Inc. 

NAKIVO Inc. is a privately held company that develops data protection and site recovery software for SMB and enterprise market since 2012.

The solution developed by the company, NAKIVO Backup & Replication, is used by over 15,000 companies worldwide to protect their critical data in virtualized and hybrid environments.

NAKIVO has a global presence with over 4,000 channel partners in 140+ countries.

Close to 300 hosting, managed, and cloud service providers are currently using NAKIVOs software to deliver VM BaaS, RaaS, and DRaaS to their customers.

NAKIVO has an impressive track record of 5-star community reviews and over 97% customer satisfaction with support, and has also won a Best of VMworld 2018” Gold Award for Data Protection at VMworld 2018 US. Customers trust us and we aim to deliver on that trust.

Website: https://www.nakivo.com/

### Contact
Email: hr.vn@nakivo.com | huong.nguyen@nakivo.com
Phone: +84964210168 (Skype/ Zalo) - Ms. Hương

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
