### ISSUE TITLE
Senior PHP developer ( Salary up to 2000$)

### ISSUE THREAD

**Issue by vanha224** [awesome-jobs/vietnam#292]
## Location

* Ha Noi, Vietnam
Requirements:

•	At least 3 years of experience in PHP coding
•	Excellent in object-oriented programing knowledge and experience
•	Understand and can implement various structure and design patterns
•	Up to date with current PHP programming practices and principles
•	Good experience with popular PHP frameworks
•	Can design the structure and optimize the code for high traffic websites
•	Experienced with various cache systems of relational databases
•	Solid knowledge of JavaScript and can apply OOP practice with JavaScript
Having the following skills is an advantage:
•	Experienced working with GIT/SVN, LAMP technology
•	Experienced with e-commerce, SEO, HTML/CSS, HTML5, JavaScript, JQuery.
•	Experienced with Magento/Laravel/Symfony and other CMS and e-commerce system.
•	Experienced with Linux or Windows server, deployment and configuration
•	Good teamwork skills and have experience in highly-standardized work environments
•	Professional and ethical behaviors
•	Critical thinking and problem solving skill
•	Good at both verbal and written communication skill

Benefit: At SmartOSC, we offer the bests to your values:
•	Attractive salary package, up to 2000$
•	Onsite opportunity in Europe, Australia, US.
•	Salary review twice a year
•	Premium health care up to $3,000/year
•	Working in No.1 Magento's partner in Vietnam – Professional English environment
•	Free English and Management training packages 
To Apply: Please submit your CV to job@smartosc.com with the following information: 
•	Job Application Letter with “Senior PHP Developer” in the subject line.
•	Updated CV in English, including your contact e-mail, phone number and salary expectations.

**Comment by joneslee85** [comment]
@vanha224 thanks for submitting the job with us. Please revise the format of the post to ensure it meets our [guideline](https://github.com/awesome-jobs/vietnam/blob/master/README.md). Should no amendment is to be made in 2 days, the job post will be removed.

**Comment by joneslee85** [comment]
I am closing this job post as no amendment has been made
