### ISSUE TITLE
NAKIVO - Junior QA Engineer - Phu Nhuan, HCM - Fulltime

### ISSUE THREAD

**Issue by huongnguyenhr** [awesome-jobs/vietnam#2920]
## Location

* **Halo Building**, 16 Le Quy Don, Ward 12, Phu Nhuan District, HCMC. 
* Currently working online 100% due to Covid-19 

## Salary Expectation

* $700 - $900 (+ Bonus KPI) 

## Requirements: 
* 1.5+ years of experience in QA/QC Testing (IT/software network/Web app is a plus)
* Knowledge of testing methodologies and concepts
* Experience in manual testing (regression, smoke, exploratory testing)
* Experience in creating test cases
* Experience in Bug Tracking and Test Management Tools (JIRA, TestRail, etc.)
* Strong capacity to learn new business and systems
* Conversational English

### Ideally

* Experience with Agile and Scrum
* Strong capacity to learn new business and systems
* Knowledge of Computer Networking, Cloud Computing, Virtualization, Linux
* Previous experience of working in international company is a plus

### Responsibilities

* Study product features and technologies
* Create test cases for new features
* Update test cases for old features due to requirement changes
* Execute test following test plan
* Report bugs with detailed information
* Do bug verification
* Quality bug severity and priority
* Report on task progress
* Provide task estimation
* Work closely with cross-functioning teams within the company (QA, Dev, Support, Sales, Product, etc.) to deliver best product quality

### Why it would be awesome to work with us

The Nakivo team in Vietnam has been changing very fast in the recent years, we have grown from a group of 6 engineers to the current team size of 80 and we are expecting to grow even more in the next following years. 

We welcome and embrace people, regardless of their background, religion, nationality or gender, but focus on diversity, contribution, determination and work ethic. At Nakivo, we are trying to improve everyday, to become a competitive choice for talented people, by offering

* Flexible working hours: Office opens from 6.00 AM to 10.00 PM
* 13-month bonus & performance bonus
* 100% salary on probationary period
* Private health care package
* Premium health care check
* Gift (cash/voucher) for every special occasion: New Year's Eve, Tet holidays, International Women's Day, International Children's Day, Mid-Autumn Festival and Birthday
* Up to 15 annual leaves/year and additional leaves (up to 3 days)
* Team building
* Free and un-limited snack, tea, coffee and by-choice request.

### About Nakivo Inc. 

NAKIVO Inc. is a privately held company that develops data protection and site recovery software for SMB and enterprise market since 2012.

The solution developed by the company, NAKIVO Backup & Replication, is used by over 15,000 companies worldwide to protect their critical data in virtualized and hybrid environments.

NAKIVO has a global presence with over 4,000 channel partners in 140+ countries.

Close to 300 hosting, managed, and cloud service providers are currently using NAKIVOs software to deliver VM BaaS, RaaS, and DRaaS to their customers.

NAKIVO has an impressive track record of 5-star community reviews and over 97% customer satisfaction with support, and has also won a Best of VMworld 2018” Gold Award for Data Protection at VMworld 2018 US. Customers trust us and we aim to deliver on that trust.

Website: https://www.nakivo.com/

### Contact
Email: hr.vn@nakivo.com | huong.nguyen@nakivo.com
Phone: +84964210168 (Skype/ Zalo) - Ms. Hương

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
