### ISSUE TITLE
Nakivo - Performance QA Engineer - Phu Nhuan, HCM - Fulltime

### ISSUE THREAD

**Issue by Phuongthu9996** [awesome-jobs/vietnam#2923]
## Location

* Halo Building, 16 Le Quy Don, Ward 12, Phu Nhuan District, HCMC.
* Currently working online 100% due to Covid-19

## Salary Expectation

* $1100 - $1400

## Requirements
* Implement Performance test design
* Configure test environment
* Run Performance and competitive testing.
* Analyze results and create reports: CPU Utilization, Memory usage, Network
usage, Processing time, Processing Rate...
* Investigate new products and their features to properly identify acceptance
criteria for performance testing
* Identify environment, memory leakage, connection issues and product
bottlenecks

### Ideally

* Higher education in computer science/technical field
* 2.5 + years of experience in testing and good understanding of its concepts
* Performance testing experience, experience in identifying performance issues.
* Conversational English

### Responsibilities

Implement Performance test design

### Why it would be awesome to work with us
The Nakivo team in Vietnam has been changing very fast in the recent years, we have grown from a group of 6 engineers to the current team size of 80 and we are expecting to grow even more in the next following years.

We welcome and embrace people, regardless of their background, religion, nationality or gender, but focus on diversity, contribution, determination and work ethic. At Nakivo, we are trying to improve everyday, to become a competitive choice for talented people, by offering

* Flexible working hours: Office opens from 6.00 AM to 10.00 PM
* 13-month bonus & performance bonus
* 100% salary on probationary period
* Private health care package
* Premium health care check
* Gift (cash/voucher) for every special occasion: New Year's Eve, Tet holidays, International Women's Day, International Children's Day, Mid-Autumn Festival and Birthday
* Up to 15 annual leaves/year and additional leaves (up to 3 days)
* Team building
* Free and un-limited snack, tea, coffee and by-choice request.

### Contact
Email: hr.vn@nakivo.com | thu.pham@nakivo.com
Phone: +84387280154 (Skype/ Zalo(0765178898)) - Ms. Thư

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
