### ISSUE TITLE
CodeLink - Devops Engineer (AWS/Docker) - HCMC - FT (currently remote)

### ISSUE THREAD

**Issue by gs-codelink** [awesome-jobs/vietnam#2925]
![CodeLink Year-end Party](https://user-images.githubusercontent.com/122055/73826276-17042880-4830-11ea-99d8-1495c6362e94.jpg)

## Location
* We are conveniently located on Xo Viet Nghe Tinh at the border of District 1 and Binh Thanh District, with easy access for all districts and a plentiful amount of awesome food and great coffee shops around the office.

## Salary Expectation
* $1,500-$2,500/month

## Requirements
- We are looking for a Devops Engineer to help manage complex deployments and harden different CI / CD workflows.
- This is the first full-time position so we expect the candidate to take initiatives and help improve the devops process across teams and projects.
- Our engineers will work directly with the clients in North America therefore we expect excellent communication skills.

### Must Have
- Hands-on experience with Docker and Kubernetes
- Experience with at least these Amazon services: EC2, Elastic Beanstalk, SQS, S3, Lambda
- Had setup several CI and CD systems for both web and mobile applications
- Hands-on experience with deployment, scaling, monitoring and performance tuning
- Git, Github and Pull Request knowledge
- Excellent written and verbal communication skills in English

### Ideally
- Familiar with Microservices architecture
- Familiar with GCP: Google Container Engine, GCE, GAE etc.
- Familiar with Microsoft Azure
- Familiar with System Design and multi-component Architecture experience
- Familiar with Agile process and scrum methodologies

### Why it would be awesome to work with us

**Who We Are**

CodeLink is an innovative and design-focused development agency. We focus on user-centric design and agile development to bring the product vision of our clients to life. We handle the end-to-end development of products, developing the product vision through product understanding, designing experiences through UX design, refining these flows with modern UI design, and developing products through iterative agile development.

We work with both early-stage product teams and teams with existing products from a wide range of countries and industries. We focus on modern technologies and work directly with our clients. We design using design-thinking principals on tools such as Sketch, Figma, Zeplin and more, and develop products leveraging our tech stack of React, React Native, Rails, Python, and Node.JS.

**Our Core Values**

1. Take full ownership for delivery
We take ownership for our client projects and ensure that we deliver what we are in charge of to the best possible outcome.

2. Deliver our highest level of quality
We take pride in the high quality that we deliver and work at a sustainable pace to ensure we can always deliver on that quality.

3. Stay consistent in plans and processes
We keep open and transparent communication with our teammates and our client whilst following agile development practices.

4. Have empathy for all those we work with
We show empathy and respect to all those we work with to gain a deeper understanding without any judgment or assumption.

5. Continuously improve and grow
We aim high with a growth mindset and see every day as an opportunity to develop ourselves, our processes, and our products.

**Top 3 Reasons To Join Us**

- Use cutting-edge & proven technologies
- Work directly with international clients
- Open environment with a focus on learning

**Why You’ll Love Working With Us**

- We work hand-in-hand with our clients to fully invest in their product development and build solutions together for their target market.
- We fully invest in our team, we will help you build yourself up in any area you feel you need development, be it in English, learning a new design tool, developing your design thinking and more. We want to make sure that you’re always learning and developing yourself whilst a part of our team.
- We respect both Product and Technology equally, ensuring all of the Products we work on have features with true market potential and ensuring all of the team contribute to, understand and believe in what they are developing.
- We are very selective with our clients, we only work on awesome Products we believe in and that show strong market potential.
- We respect you and your personal hours, we keep sustainable pace by working standard 8 hour days from Monday to Friday, ensuring we only plan for what we can achieve.
- We are fully agile and only work with Clients who work the same, working with set sprint goals and working at our rate of velocity.
- You will have ownership over your role, giving you the opportunity to experiment and try new processes to better improve your day-to-day responsibilities. We are always open to improving our processes.

**Company Benefits**

- An open and dynamic with working environment with no dress code and the freedom to be yourself.
- Modern open-space office with comfortable work space, a PS4 games room, and chill-out areas.
- Salary review twice a year with opportunities for promotions and spot awards.
- Culture of recognition with monthly rewards for those with the most kudos.
- All office benefits and full salary during probation.
- Flexible starting time up to 10AM working Monday - Friday with no overtime and a long lunch break.
- 2 days remote every month taken on any days you choose so you can work from wherever you like.
- Full Vietnamese holidays off with 12 annual leave days per year with all days not taken paid out in cash.
- Yearly company trip, monthly team all-hands activities, welcome lunches for new members, monthly budget for team celebrations.
- Celebrations for special days in the year, such as Women’s Day, YEP, Christmas.
- Gold level Health Insurance coverage from Bao Viet Insurance and a yearly complete Health Check.
- Employee-led clubs within the company; games teams, sports teams, etc.
- Buddy system, tech and product talks, mentoring, and paid-for training for any skills you’d like to develop.
- Weekly agile sessions and professional coaching.
- Meal allowance, parking allowance, petrol allowance, and unlimited snacks and coffee every day.
- Options for a full MAC or PC set-up completely provided.

### Contact
Homepage: Codelink.io
Email: hr_at_codelink_dot_io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
