### ISSUE TITLE
GFT Technologies Vietnam - Java BackEnd Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by ngannguyen97** [awesome-jobs/vietnam#2926]
![166a4d740e80fddea491](https://user-images.githubusercontent.com/72273695/134911116-65ec97ef-82d2-4541-a32e-a520ec21c387.png)

## Location

* District 1, Ho Chi Minh City

## Salary Expectation

* Attractive, Negotiable

## Responsibilities:

- Design, develop, implement and maintain Java application
- Write high quality, maintainable code using TDD and DDD
- Translating user stories into working solution
- Design and implement RESTful APIs
- Design and implement microservice architecture within the given domain
- Work with the distributed team in multiple time zones
- Actively participate in Scrum technologies
- At least 4 years of practical experience in Java (Java SE/Kotlin, Java EE/Spring/Spring Boot)
- Practical knowledge of version control systems, Git flow, Trunk, and GitHub flow branching strategies
- Experience with SQL and JPA/Hibernate
- Experience with a messaging system like Kafka, alternatively Solace/RabbitMQ/AWS Kinesis
- Experience developing RESTful APIs
- Experience developing event-driven microservices using Kafka
- Hands-on experience with Kubernetes and Docker experience
- Familiar with DevOps toolchain: GitHub, CircleCI, Artifactory, SonarQube, et al.
- Knowledge of NoSQL databases such as DynamoDB,
- Practically experience with elastic AWS infrastructure
- Experience in Agile (Scrum or Kanban)
- Knowledge of Test Driven Development methodology

## Skills

- Bachelor's degree in Computer Science, Computer Engineering, or equivalent industry experience.
- Excellent  command of English and good communication in Vietnamese when working with cross-functional teams.
- Have financial  technology  working  experience s (advantages of the previous working in the digital bank, payment gateway, lending/risk management, payment, eKYC, liveness, fraud, AML)
- Have proficient and practical knowledge in core Java, and practical experiences with Spring framework, Spring boot, and dependencies
- Have a practical, structural mindset and be a quick learner able to adapt to the changes from a fast-growing organization
- Practical knowledge of agile software development methodologies
- Quick learner with an ambitious and results-driven personality.
- Work well as part of a team in a fast-paced environment.
- Fluent English in speech and writing

### HR Benefits:

- Competitive salary
- Salary band per level and employee benefits are reviewed once per year
- 13th month salary pro rata depending on the employee’s length of service (within a calender year), paid with the December salary
- Monthly lunch allowance: 700,000 VND/employee
- Parking: GFT covers the monthly parking fee for employee motorbikes
- Performance evaluation is once per year, for 2 purposes: > Performance bonus   > Salary increments

### Talent retention policy (Retention bonus)

- 2-year anniversary = 0.5x monthly salary
- 3-year anniversary = 1x monthly salary
- 5-year anniversary = 2x monthly salary
- Paid with salary of month of anniversary.

### Health care

- Private health insurance: including accident, outpatient, in-patient, maternity, and dental for all permanent employees who pass 2-month probation.
- Optical: expense claim for eyewear
- Annual health check-ups.

### Vacation

- Maximum 18-day vacation leave/year (with the ability to carry over 05 days till 31st March of the following year)
- Adding one more annual leave day for each two-year anniversary.

### Healthy lifestyle

- Sports and hobby clubs: company has an annual fund for fitness activities, which is allocated per month as team’s vote.
- Range of healthy snacks, tea, coffee, milk and beer on tap:

### Social

- Company townhall: each 6 weeks
- Monthly team lunch at restaurants
- Monthly team engagement activities: one activity per month
- CSR activities: as per company’s CSR guideline and practice
- Onsite tour/training courses at other GFT offices and client’s destination overseas (where applicable).

## Contact
Homepage: gft.com
Skype: ngxuanthaongan261
Phone: 0912442406

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
