### ISSUE TITLE
JobHopin - Senior Mobile React Native - Remote - Fulltime

### ISSUE THREAD

**Issue by thonguyen2501** [awesome-jobs/vietnam#2927]
**Location**
**REMOTE**

**Salary Expectation
$1500 - $3000**

**Description**

- Build pixel-perfect, buttery smooth UIs across both mobile platforms.
- Leverage native APIs for deep integrations with both platforms.
- Diagnose and fix bugs and performance bottlenecks for performance that feels native.
- Transition existing VueJS web apps to React Native.
- Coordinate with co-developers and keep project managers well informed of the status of development effort and serves as liaison between development staff and project manager

**Requirements**

- At least 4 years in Mobile React Native
- Firm grasp of the JavaScript and TypeScript language and its nuances, including ES6+ syntax
- Knowledge of functional programming
- Ability to write well-documented, clean Javascript code
- Rock solid at working with third-party dependencies and debugging dependency conflicts
- Familiarity with native build tools.
- Understanding of REST APIs, the document request model, and offline storage
- Good command of English speaking.

**Benefits**

- 14-16 days off
- Insurance full salary
- 13th month salary

**Contact**

Skype: tho.nguyenthicam
Email: thonguyen@jobhopin.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
