### ISSUE TITLE
JobHopin - Senior Frontend VueJS Developer - REMOTE - Fulltime

### ISSUE THREAD

**Issue by thonguyen2501** [awesome-jobs/vietnam#2928]
**Location
REMOTE

Salary Expectation
$1500 - $3000**

**Description**

- Develop, record and maintain cutting edge Vuejs web applications with mobile first in mindset
- Build innovative, state-of-the-art applications and collaborate with the User Experience (UX) team
- Cooperate with BE developers to consume backend data services via REST API.
- Lead the entire web application development life cycle right from concept stage to delivery and post launch support
- Convey effectively with all task progress, evaluations, suggestions, schedules along with technical and process issues
- Coordinate with co-developers and keep project managers well informed of the status of development effort and serves as liaison between development staff and project manager

**Requirements**

- At least 4 years of experience
- Good knowledge of VueJS.
- In depth knowledge of Javascript, CSS.
- BS/MS degree in Computer Science, Engineering, MIS or similar relevant field
- Experience in unit testing and Quasar Framework is a plus.
- Hands on experience with REST API as a consumer.
- Creative and efficient problem solver
- Ability to speak in both Vietnamese and English

**Benefits**

- 14-16 days off
- Insurance full salary
- 13th month salary

**Contact**

Skype: tho.nguyenthicam
Email: thonguyen@jobhopin.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
