### ISSUE TITLE
QUOINE - Ruby on Rails - Saigon - FT

### ISSUE THREAD

**Issue by chinh7** [awesome-jobs/vietnam#293]
We are looking for kick-ass engineers to join our engineering team here in Ho Chi Minh.
_If you never work with Ruby on Rails but you are confident that you are a quick learner with strong development background, don't hesitate to apply._

## Company
QUOINE is a Financial Technology (Fintech) company headquartered in Japan. Our core product is a highly sophisticated crypto-currencies trading platform supporting up to 10 fiat currencies and 2 crypto-currencies. We are a top global crypto-currencies exchange with the latest funding of $20M. Our ultimate mission is to revolutionize banking and financial services and to bring financial services to the un/under-banked.

## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1000 - $3000/month

## Requirements
• Experience shipping production Ruby on Rails app. 
• Knowledge of web technologies is a big plus.
• Experience with programming competitions (IOI, ACM, etc) is a big plus.

## Responsibilities
• Solving hard business logic with elegant design. 
• Ensuring system robustness, performance and scalability. 
• Writing well tested, bug-free code using BDD (RSpec)

### Contact
Chinh Nguyen: chinh _at_ quoine.com

**Comment by joneslee85** [comment]
@chinh7 thanks for posting with us. Please revise the formats:

* Bullet points of _Requirements_ and _Responsibilities_ section
* The title lack the position title, is it a developer? what level is it? Senior? Junior? or both?

**Comment by joneslee85** [comment]
No amendment made within 2 days. Closing.
