### ISSUE TITLE
LINE VietNam - Frontend Engineer - Saigon, District 10 - Fulltime

### ISSUE THREAD

**Issue by ngthtung** [awesome-jobs/vietnam#2930]
## Location

* Viettel Building, 285 Cach Mang Thang Tam Street, Ward 12, District 10, Ho Chi Minh

## Salary Expectation

* Negotiate

## Position Summary
* We are looking for talented, self-motivated web developers with a track record of creating and optimizing web application UX/UI to join our team in the next phase of our development.

## Requirements
* Fluent in JavaScript, HTML5, CSS3 and have interest in core.
* Passionate about development, building highly functional, great eyes on details, always look for
* UX improvement to deliver outstanding user experience.
* Familiarity with source control (git/git-flow) and code review.
* Experience in SPA development based on MV*
* Basic understanding of server, database and good experience in RESTful API design and
development.
* High ownership, self-sufficient and continious effort to find solutions for doing repeated tasks, easily
adapt and learn new things.
* Able to work overseas and/or a business trips overseas.

### Must Have

* Fluent with JavaScript, HTML5, CSS3, and have an interest in fundamental technologies (fresh graduates and juniors are welcome to apply)
* Experienced in the development of SPAs utilizing modern frontend frameworks (at least one popular JS framework like React, Vue or Angular is a must)
* Outstanding in both verbal and nonverbal English.

### Responsibilities

* Implement frontend for web applications with modern technologies (HTML5/ CSS3/ JS...) 
* Improve the efficiency of existing products
* Build the architecture and design of new products and features
* Research new technologies to apply in the current and future projects
* Implement UI components and libraries
* Write technical specifications based on conceptual design, business/technical requirements

### Contact
Send your CV to email: tungnt@linecorp.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
