### ISSUE TITLE
Chopp - Lead Full-Stack Engineer - HCMC - FT

### ISSUE THREAD

**Issue by constantx** [awesome-jobs/vietnam#2931]
## Location

* Saigon, Vietnam
* Remote Ok

## Salary Expectation

* $1000-$2000/month
* Stock Options for the right candidate (equity)

## Requirements
- 4+ years of experience as a Software Engineer or similar role
- 2+ years of experience in any of the following languages/frameworks: JavaScript/NodeJS (preferred), Go, Python
- Experienced in system architectures & data pipelines
- Experienced in querying and working with SQL and NoSQL databases
- Experienced in debugging and performance optimization
- Solid understanding of RESTful APIs
- Experienced with cloud service provider like AWS or GCP
- Experienced with web technologies and frameworks (NodeJS, ReactJS)
- Experienced with source code management practice using Git
- Experienced with DevOps and Continuous Integration and Delivery Practice

### Ideally
- Solid grasp of algorithms
- Writes clean, modular and well-documented code
- A passion for Developer Experience
- English reading and writing skills

### Responsibilities
- Manage a team of software engineers to develop the best-in-class E-grocery service at Chopp
- Coordinating with Product, Marketing, and other teams to identify problems and develop solutions for growth
- Monitor, maintain and scale our backend infrastructure
- Work with web and mobile engineering team to implement and improve our customer experience
- Support the marketing and operation teams with business intelligence

### Preferred
- Be open-minded, collaborative, accountable, yet independent
- Don’t tolerate BS, question authority and say what you mean
- Embrace uncertainty and face challenges head on
- Pay attention to detail
- Be passionate and take ownership of your work
- Be scrappy and take initiative
- Wear multiple hats, even the straw-hat ones
- Have a deep curiosity and passion for how things are designed, how things work and how to best bring ideas to the world

### Why it would be awesome to work with us
- True startup culture with no BS
- Make a difference and make people's lives better
- Cutting edge technology
- Awesome product/perks/office
- Cool, talented and passionate colleagues
- Generous stocks/equity
- Quarterly performance-based bonus
- Stock options for the right candidate
- Lunch, snacks & drinks in office
- Monthly allowance for gym, recreation
- Sponsor for tickets to events and training workshops
- Monthly team happy hour
- Quarterly Team Off-Site

### Contact
Homepage: https://chopp.vn | https://about.chopp.vn/careers
T. Nguyen (CEO/CTO/CDO): t_at_chopp_dot_vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
