### ISSUE TITLE
MCVGo - Senior Backend Developer - HCM District 7

### ISSUE THREAD

**Issue by hungmcvgo** [awesome-jobs/vietnam#2932]
## Location

* Saigon, Vietnam
* Fulltime
* District 7

### Company domain:
* Live Streaming
* Real-time Interactive
* Private Social Network

## Salary Expectation

* $1800-2500

## Requirements
* Java
* Nginx
* PostgreSQL/MySQL/MongoDB

### Must Have

* BA in Computer Science, Information Systems, or related field
* At least 4 years of working experience as Backend Developer 
* Good experience in API design & implementation in high scale
* Familiarity with Linux, MySQL, MongoDB, Nginx
* Good experience in understanding & applying Design Patterns/Design Principles
* Social Network & Video Streaming product development experience is a huge plus

### You’ll be responsible for

* Design, Build, Deploy, and Maintain software components for projects on Server-side
* Analyze and improve efficiency, scalability, and stability of various system resources
* Practice disciplined software engineering (e.g. unit test, code reviews, git-flow)
* Write technical documentation
* Guide fresher or junior developers

### Why it would be awesome to work with us
* Dynamic, technological, and Agile working environment
* Self-development: online technical seminar, career talk, and various training on hot-trend technologies, languages, and soft-skills
* Talented and enthusiastic fellows
* Creative office spaces with free coffee, snacks and table tennis, billiards
* 13th-month salary, Annual salary raise review
* Macbook Pro

### Contact
Mr. Kevin (Delivery Manager)
hungvd@mcvgo.com
0936907925 (Telegram/Zalo/Viber is available for chat/call)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
