### ISSUE TITLE
Chopp - Lead iOS Engineer - HCMC - FT

### ISSUE THREAD

**Issue by constantx** [awesome-jobs/vietnam#2933]
## Location

* Saigon, Vietnam
* Remote Ok

## Salary Expectation

* $1000-$2000/month
* Stock Options for the right candidate (equity)

## Requirements
- Minimum 3 years of professional experience in iOS development
- Practical knowledge of Objective C and/or Swift
- Ability to develop rich UI for iOS that follows Human Interface Guidelines
- Have built app(s) published on the App Store demonstrating a strong product focus
- Solid understanding of RESTful APIs
- Writes clean, modular and well-documented code
- Solid grasp of algorithms
- Ability to debug and do performance optimization
- Comfortable with source code management practice using Git/GitHub
- A real passion for user experience and design
- Proficient English reading and writing skills
- Bonus: Experience in micro interaction and animation

### Ideally
- Experienced with source code management practice using Git
- Experienced with DevOps and Continuous Integration and Delivery Practice
- Solid grasp of algorithms
- Writes clean, modular and well-documented code
- A passion for Developer Experience
- English reading and writing skills

### Responsibilities
- Develop, maintain, and optimize our in-house products (2 currently, 1 for customers, 1 for internal)
- Coordinating with Product, Marketing, and other teams to identify problems and develop solutions for best user experience
- Work with engineering team to implement and improve developer experience

### Preferred
- Be open-minded, collaborative, accountable, yet independent
- Don’t tolerate BS, question authority and say what you mean
- Embrace uncertainty and face challenges head on
- Pay attention to detail
- Be passionate and take ownership of your work
- Be scrappy and take initiative
- Wear multiple hats, even the straw-hat ones
- Have a deep curiosity and passion for how things are designed, how things work and how to best bring ideas to the world

### Why it would be awesome to work with us
- True startup culture with no BS
- Make a difference and make people's lives better
- Cutting edge technology
- Awesome product/perks/office
- Cool, talented and passionate colleagues
- Generous stocks/equity
- Quarterly performance-based bonus
- Stock options for the right candidate
- Lunch, snacks & drinks in office
- Monthly allowance for gym, recreation
- Sponsor for tickets to events and training workshops
- Monthly team happy hour
- Quarterly Team Off-Site

### Contact
Homepage: https://chopp.vn | https://about.chopp.vn/careers
T. Nguyen (CEO/CTO/CDO): t_at_chopp_dot_vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
