### ISSUE TITLE
CMC Global - Frontend developer (ReactJS, English) - Ha Noi - FT

### ISSUE THREAD

**Issue by ngocdbhr** [awesome-jobs/vietnam#2939]
## Location

* Duy Tan, Ha Noi, Vietnam
* Fulltime

## Salary Expectation

* $2500/month

## Describe
* Develop web applications, frontend features using ReactJS
* Working directly with client team
* Analyzing requirements, investigating, proposing solution
* Creating design documents as needed
* Perform peer review as needed
* Reporting status, issues to customer and CMC Global direct manager
* Working in CMC Global office and meeting with client onsite 1~2 times per week

## Requirements
* 3+ years in-depth experience in ReactJS design and development using the modern web stack
* Experience with Framework/Tool: React, CircleCI, Kibela, Slack, Jira 
* Great knowledge with HTML5, CSS3, SASS/SCSS and JavaScript/ES5, ES6+
* Experience with SaaS platform development is a plus
* Experience with Git tools/Git flow

## Soft Skills
* Strong written and verbal communication skills in English Possible to co-work with team
* Good at investigating and solving incident and problem skill
* Self-motivated and Self-directed

### Why it would be awesome to work with us
* Package: 14 salary months + Project bonus (If any) + Extra package: 16M/year
* Young and dynamic working environment. 
* Opportunity to approach newest technology trends
* Exciting leisure: sport and art events (football club, family day...)
* Company's labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trip, Holiday, etc.)

### Interesting engineering projects
* Interesting engineering projects
* Projects with Japanese customers

### Contact
Email: dbngoc@cmc.com.vn
Skype: ngocdb.hr

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
