### ISSUE TITLE
QUOINE - Web Frontend - Saigon - FT

### ISSUE THREAD

**Issue by chinh7** [awesome-jobs/vietnam#294]
We are looking for kick-ass engineers to join our engineering team here in Ho Chi Minh.

## Company
QUOINE is a Financial Technology (Fintech) company headquartered in Japan. Our core product is a highly sophisticated crypto-currencies trading platform supporting up to 10 fiat currencies and 2 crypto-currencies. We are a top global crypto-currencies exchange with the latest funding of $20M. Our ultimate mission is to revolutionize banking and financial services and to bring financial services to the un/under-banked.

## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Very attractive

## Requirements
• Expert knowledge of JavaScript and web technologies (HTML/CSS) 
• Passion for leading-edge front end UI and UX.
• Knowledge of JavaScript Frameworks is a plus (AngularJS, ReactJS)
• Experience with programming competitions (IOI, ACM, etc) is a plus.

## Responsibilities
• Build efficient and reusable frontend systems that ensure performance and robustness
• Collaborate with Product Designers and Backend Developers to deliver compelling user-facing web applications
• Writing well tested, bug-free code using BDD

### Contact
Chinh Nguyen: chinh _at_ quoine.com

**Comment by joneslee85** [comment]
thanks for posting with us. Please revise the formats:

Bullet points of Requirements and Responsibilities section
The title lack the position title, is it a developer? what level is it? Senior? Junior? or both?

**Comment by joneslee85** [comment]
No amendment made within 2 days. Closing.
