### ISSUE TITLE
Hybris developers (All level) - SAI Digital

### ISSUE THREAD

**Issue by TrucLinhVo** [awesome-jobs/vietnam#2943]
## Requirements
* Bachelor of Computer Science, Software Engineering or equivalent 
* Minimum of +1 years of experience using SAP Commerce (Hybris), Java/J2EE (Spring, MVC, Lucene, Solr) 
* Good to have knowledge in Javascript or AngularJS
* Nice to have: architecture and design experience with SAP Commerce (Hybris) platform. Database skills (Postgres, My SQL, Oracle) 
* Excellent troubleshooting skills, especially in a complex application stack 
* Ability to handle multi-tasks in dynamic environment

## Skills
* Java Enterprise (JSP, Tomcat, JPA/Hibernate)
* Spring Framework (Core and MVC)
* Web Services (including SOA)

### Must Have
* Minimum of +1 years of experience using SAP Commerce (Hybris), Java/J2EE (Spring, MVC, Lucene, Solr)
* Good to have knowledge in Javascript or AngularJS

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Work on complex Enterprise eCommerce projects for reputed International Clients spread across the planet!
* Be part of our agile teams (using Scrum) using SAP Commerce (Hybris), Java Enterprise (JSP, Tomcat, JPA/Hibernate), Spring Framework (Core and MVC) and Web Services (including SOA)
* Be actively involved in international client-facing work. 
* Mentor, influence and upskill junior developers, if any. 

### Why it would be awesome to work with us
* 13th-month salary bonus.
* One additional day for Annual leave after each year of service.
* Full base insurance contribution (Social, Health and Unemployment insurance).
* Attractive premium private Healthcare insurance.
* Lunch & parking allowance, gifts in special events.
* Sponsorship for training courses, professional certificates.
* English speaking, professional, dynamic work environment with multi-national team members.
* Opportunity to work on-site abroad.
* Monthly Company’s meeting for employees’ understanding about company’s strategy and development plan; Happy Hour with snack and fresh fruit.
* Various team building, sports activities, company trips, parties, and Trade Union activities, weekly social activities for Cycling club, football club, etc.
* Multi charity activities to create opportunities for employees to help unfortunate people in community.
* Above benefits are designed for Vietnamese employees. Expat’s package will be communicated in offer letter, including work permit support term and condition.

### Contact
Email: linh.vo@sai-digital.com
Or skype: TrucLinh Vo
Website: https://www.sai-digital.com/careers/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
