### ISSUE TITLE
Fintech - Full Stack Engineer - Full time, HCM #javascript #nodejs #react

### ISSUE THREAD

**Issue by thaoanhnguyen** [awesome-jobs/vietnam#2944]
## Location

* District 4, HCMC

## Salary Expectation

* Up to $3,000 (Negotiable)
## Requirements
* Min 5 years of relevant experience in mobile software development (Android / iOS platform); 
* Knowledge of Kubernetes and Docker
* Familiar with AWS cloud solutions.
* Implement a frontend for web applications with modern technologies (HTML5/ CSS3/ JS...) and framework (angularjs/ vuejs/ reactjs…);
* Knowledge of programming communication between mobile and server via TCP / IP, Firebase, Websocket, WebService and JSON / XML protocols
* SVN, GIT tool.

### Responsibilities
* Code and Technical Design Reviews, Deployments and refactoring of application state to ensure scaling and performance. Work closely with the Product Owner.
* Ensure that work plan is properly assigned, major timelines are cascaded with the Digital product team and the correct documentation is in place and communicated regularly.
* Analysis on the Digital Technology Platform, In-house System to review source code deliveries from vendors and control deployment operations
* Ensure that service, operational and support requirements are taken into consideration and solutions are ready to be transitioned to the live
* Ensure that sufficient testing of solutions has taken place to minimise any disruption during transition to live
* Ensure that the right levels of communication are provided, expectations of key stakeholders are managed.

### Why us?
As an early key member of IT team, you'll get the unique opportunity to participate in developing a disruptive digital platform for insurance distribution. All your opinions matter to us. We will together build an amazing platform to deliver pioneering service in Vietnam market.
* Autonomy to perform your role in technical reviews.
* Laptop provided.
* Full salary during probation
* 13th salary, performance bonus
* Health insurance for employee

### Contact
* Mr. Ngoc (093 207 3000)
* Email: ngoc.nguyen@ideallife.com.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
