### ISSUE TITLE
InnomizeTech - Fullstack Drupal Developer - HCM - FT

### ISSUE THREAD

**Issue by thanhthi** [awesome-jobs/vietnam#2945]
## Location: 2A/64A Bach Dang Street, Ward 2, Tan Binh District, HCMC

* Saigon, Vietnam
* Remote during the Covid-19 pendamic

## Requirements
* At least 3+ years of experience in PHP development (Drupal) and MySQL.
● Good English skills.
● Knowledge of Prosody & Docker is a big plus.
● Understand the technical architecture and you are able to quickly master the technical
components.
● Have extensive experience in managing, setting up and maintaining Drupal (7, 8 & 9)
installations.
● Be familiar with the open-source Drupal community, coding standards and architecture and a
number of frequently used modules.
● Be familiar with the various facets of CMS solutions, such as workflow, media management,
theming and templates, views, search solutions, etc.
● Have knowledge of Elastic search.
● Experience with Javascript (Jquery), Angular/React, HTML5, CSS3, Ajax,...
● Ability to integrate web services, single sign-on

NICE TO HAVE:
● Knowledge of PHP frameworks like Symfony
● Knowledge of cloud hosting via AWS and Azure

### Responsibilities
* Build new websites in Drupal 8 and 9 and take care of existing Drupal installations (8 & 9).
● Provide technical and functional input for the analysis.
● Guarantee the quality of your work by carrying out tests yourself and by writing and maintaining
automatic tests.
● Be active in the Drupal community and do not hesitate to contribute to the use, testing or
creation of patches.
● Work autonomously but are part of an expert team.
● Work on multiple projects simultaneously.

### WORKING WITH US
As a start-up company, our team is our highest priority and we welcome new talent to our team. Along
with our young spirit, our aim is to create an ideal and open environment where each person is eager to
work and encouraged by the creative ability of every member of our team.
● We put human development as the first priority.
● We give you challenging and interesting work to develop your career path.
● Flexibility and authorizing culture in our company.
● Activities: Yearly company trips, Year-end Party, Teambuilding, Football Clubs.
● Exciting internal events to help you understand the whole business and make you feel
● like you are part of the Innomize Family.
● Modern and cosy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day,
to make sure your energy level is high when you need it.
● There are a lot of opportunities to learn and grow with training activities weekly such as English,
Management, Soft Skills, Technology.
● Career guidance and support daily from Manager, Leader and Senior Level.
● 13th payment, and extra bonus for excellent employees.
● Salary and promotion review: twice / year
● Promotion opportunities for Senior and Leader level.
● Special bonus on Public holiday.
● Overtime is rarely required, you will get paid for the extra work.

### Contact
Email: hr@innomizetech.com
Skype: thanhthi.hr

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
