### ISSUE TITLE
InnomizeTech - Mobile React Native Developer - HCM - FT

### ISSUE THREAD

**Issue by thanhthi** [awesome-jobs/vietnam#2946]
## Requirements
● 3+ years of production experience building and maintaining React Native mobile applications.
● Strong knowledge of React Native development practices.
● Experience in using JSX, React Components and Redux.
● Experience in HTML5 / CSS3 (Flexbox) and responsive design.
● Firm grasp of the JavaScript (and TypeScript or ClojureScript) language, including ES6+ syntax.
● Knowledge of functional or object-oriented programming and its design principles.
● Understanding of REST APIs or GraphQL, the document request model, and offline storage.
● Ability to write well-documented, clean Javascript code.
● Excellent analytical skills with a good problem-solving attitude.
● Rock-solid at working with third-party dependencies and debugging dependency conflicts.
● Familiarity with native build tools, like XCode, Gradle, Android Studio, IntelliJ.

### NICE TO HAVE:
● Knowledge of AWS mobile services such as AWS AppSync, AWS Cognito User Pool, Push
Notification.
● Be able to use the AWS Amplify framework to build mobile applications.
● Having existing mobile apps on Apple App Store or Google Play is a plus.
● Dart + Java/Kotlin/Swift/ Objective-C or Flutter

### Responsibilities
● Development of React Native applications for iOS and Android.
● Work closely with the Team leader to provide ideas and solutions to the development of new
features.
● Cooperate with UI Designer to implement modern minimalist designs into production.
● Build pixel-perfect, buttery smooth UIs across both mobile platforms (IOS and Android).
● Integrate third-party API's.
● Release applications to IOS and Google Play stores.
● Work with modern tools including Jira, Slack, GitHub, Google Docs, etc.

### WORKING WITH US
As a start-up company, our team is our highest priority and we welcome new talent to our team. Along
with our young spirit, our aim is to create an ideal and open environment where each person is eager to
work and encouraged by the creative ability of every member of our team.
● We put human development as the first priority.
● We give you challenging and interesting work to develop your career path.
● Flexibility and authorizing culture in our company.
● Activities: Yearly company trips, Year-end Party, Teambuilding, Football Clubs.
● Exciting internal events to help you understand the whole business and make you feel
● like you are part of the Innomize Family.
● Modern and cosy kitchens with plenty of free noodles, coffee/tea bar and fresh fruits every day,
to make sure your energy level is high when you need it.
● There are a lot of opportunities to learn and grow with training activities weekly such as English,
Management, Soft Skills, Technology.
● Career guidance and support daily from Manager, Leader and Senior Level.
● 13th payment, and extra bonus for excellent employees.
● Salary and promotion review: twice / year
● Promotion opportunities for Senior and Leader level.
● Special bonus on Public holiday.
● Overtime is rarely required, you will get paid for the extra work.

### Contact
Email: hr@innomizetech.com
Skype: thanhthi.hr

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
