### ISSUE TITLE
[Software Tester /QA QC (Mobile Apps)] - [HCM] - [Full-time]

### ISSUE THREAD

**Issue by tracy-digisource** [awesome-jobs/vietnam#2947]
### **JOB DESCRIPTION**
* Participate in the development of exciting live-streaming applications that extremely growing fast at the moment. 
Work with us, your skill will be improved step by step, you should have a keen eye for detail and competent in executing test cases.
* Good English communication skills is to discuss with colleagues and customer. 
* Also get involved in testing API, stress-testing and almost assure the quality of mobile native apps (iOS, Android, Web…)
 ### **REQUIREMENT** 
* Firm knowledge in writing and executing test cases and test scripts
* Minimum 2 years of experience in manual testing for enterprise mobile NATIVE apps.
* Strong English skills (writing and speaking)
* Good understanding of Software Testing Life Cycle
 ### **WHY YOU’LL LOVE WORKING HERE** 
* Office situated in centralise location and close to amenities.
* Providing modern equipment to work.
* 5 days work week,1.5 hours rest time.
* Having good and fair reward and promotion system.
* Full insurance coverage
* 13 month salary plus full coverage insurance
* Annual performance review
* 12 annual leave, 18 days sick leave per year
### **LOCATION**
Working from 8.30 to 18.00 Mon to Fri (1.5 hour lunch break) at our office in 133 Dương Bá Trạc, Ward 1, District 8, HCMC.
### **CONTACT**
Email:      linhtrang@digisource.vn
Website:  digisource.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
