### ISSUE TITLE
Mirabo JSC - ReactJS Developer - Hanoi - FT

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2949]
**Location**

> - Tay Son, Ha Noi, Vietnam
> - Fulltime

**Salary Expectation**
15.000.000 - 30.000.000 VND/tháng

**Job description**

> - Tham gia phát triển các dự án Outsourcing cho khách hàng
> - Phối hợp với team nghiên cứu và ứng dụng các công nghệ mới đáp ứng yêu cầu dự án
> - Trao đổi, phân tích và tìm giải pháp cho các yêu cầu của dự án;

**Requirements**

> - Có kiến thức nền tảng về Javascript, CSS, HTML,.. tốt
> - Có ít nhất từ 1 năm kinh nghiệm và thông thạo một trong các framework: Reactjs / Vuejs / NuxtJs,..
> - Có hiểu biết về Restful APIs
> - Có tinh thần trách nhiệm cao
> - Khả năng làm việc nhóm, chịu được áp lực công việc;
> - Tư duy logic tốt, năng động, sáng tạo, chủ động trong công việc;
> - Ưu tiên ứng viên có định hướng trở thành Leader hoặc có kinh nghiệm Leader

**Why it would be awesome to work with us**

> - Thu nhập từ 18-25M/tháng + thưởng dự án;
> - Thưởng lương tháng 13, thưởng hiệu suất kinh doanh,...;
> - Hưởng đầy đủ các chế độ bảo hiểm theo Luật lao động Việt Nam và theo quy định của công ty;
> - Xét tăng lương 2 lần/năm (tháng 7 và tháng 1) và tăng lương ngay khi có thành tích xuất sắc;
> - Nghỉ quốc khánh, nghỉ lễ, nghỉ Tết, giỗ tổ, nghỉ chiến thắng/lao động, Nghỉ mát, nghỉ hè, nghỉ bù, nghỉ phép, các hoạt động teambuilding hàng tháng, hàng quý, hàng năm,...;
> - Được hỗ trợ kinh phí tham gia các chương trình học lấy chứng chỉ IT, các chương trình học phát triển chuyên môn,...;
> - Có cơ hội được tham gia lớp học tiếng Nhật do Công ty tổ chức;
> - Thời gian làm việc từ 8h30 a.m – 5h30 p.m, nghỉ thứ 7 và CN (Check in linh hoạt từ 8h-9h).

**Contact**
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c (Hoa Nguyen)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
