### ISSUE TITLE
A French StartUp - TechLead - Ho Chi Minh city - FullTime

### ISSUE THREAD

**Issue by lamducduong184** [awesome-jobs/vietnam#2950]
## Location

Saigon, Vietnam
FullTime

## Salary Expectation
Min: 3000$
Max: ~ 10000S (Negociate)

## Requirements
![GolangJD_MapHuynh](https://user-images.githubusercontent.com/19955070/136055528-9142b526-9e51-4dc1-b478-e300dd3be00a.png)

### Why it would be awesome to work with us
Liên minh Unicorn leading về Adtech + AI giữa Startup các chuyên gia công nghệ #BigData #AI Tây học ở châu Âu với 1 tập đoàn hàng đầu Việt Nam đang cần tìm 01 Techlead để xây đựng chi nhánh ở Saigon. 
Ưu tiên các bạn đã có ~ 4 năm kinh nghiệm làm Golang.
Team sẽ làm việc trực tiếp với chuyên gia hiện đang làm Lead ở 1 công ty công nghệ lớn thứ 4 ở Pháp (chỉ sau Miccrosoft, Google và Facebook). Không chỉ được tiếp cận với trình độ công nghệ ở tầm vóc quốc tế, bạn sẽ được làm việc với 1 người anh, mentor hào sảng, nhân văn, người mà bản thân mình biết rất rõ. Thiên hạ xưa nay chỉ có 02 người được xem là đối trọng với Mộ Dung Phục, người thứ thứ nhất thì mình ko cần phải nêu tên, còn người thứ 2 thì chính là vị sư huynh này.
Salary: thương lượng, minimum 3000$
+ Full các chế độ về điều kiện làm việc, đãi ngộ thưởng, bảo hiểm,...

### Contact
Homepage: 
Email: Info@analyticslab.vn (0942492607)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by lamducduong184** [comment]
I have edited the post.

**Comment by lamducduong184** [comment]
I just help my friend who currently living in Paris - France. I am not Agency. Could you please check my post.
