### ISSUE TITLE
Mirabo JSC - Frontend Developer (ReactJS, VueJS) - Ha Noi - FT

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2951]
## Location

* Tay Son, Hanoi, Vietnam

## Salary Expectation

* 15.000.000 - 30.000.000/month
## Requirements
* 1+ years in-depth experience with framework: ReactJS. VueJS
* Have knowledge with Javascript, CSS, HTML,...
* Experience with Restful APIs

## Skills

Self-motivated and Self-directed

### Why it would be awesome to work with us

* SIGNING BONUS
* Package: 13 salary months + Project bonus (If any)
* Young and dynamic working environment.
* Opportunity to approach newest technology trends
* Company's labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trip, Holiday, etc.)

### Interesting engineering projects

*Interesting engineering projects
*Projects with Japanese customers

### Contact
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c (Hoa Nguyen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
