### ISSUE TITLE
Nakivo - Java Developer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by vananh39** [awesome-jobs/vietnam#2952]
## Location

* Phu Nhuan, Ho Chi Minh

## Salary Range

* $1800 - $2400/ month (+ Sign-in Bonus 75% of 1 month salary)

## Requirements
* Strong understanding of object-oriented, design patterns and programming principles
* Fluency in Java 8 and relevant ecosystem.
* Knowledge of Spring framework, Hibernate, ExtJs, Design patterns.
* Good at JavaScript, SQL, HTML, CSS.
* Able to quickly learn and work with new APIs, SDKs.
* Able to follow existing code standards.
* Able to write module, clean and well tested code.
* Knowledge of web and network programming, multi-threaded, virtualization and cloud computing
* Able to analyze and design system
* Able to use SVN
* At least 4 years of experience in relevant position.
* Intermediate level in English.

### Ideally

* Jira, Confluence, TeamCity, VMware, Hyper-V, AWS EC2, IntelliJ IDEA, Eclipse, Linux bash, PowerShell.

### You’ll be responsible for

* Investigate, analyze, design, and estimate new features based on written specification.
* Implement the feature, full stack, working independently with minimum guidance.
* Work with others department: PM, QA, Support, etc. to resolve the problems and complete assigned tasks.
* Work in parallel tasks.
* Ensure the best code quality personally.

### Why it would be awesome to work with us

The Nakivo team in Vietnam has been changing very fast in the recent years, we have grown from a group of 6 engineers to the current team size of 70 and we are expecting to grow even more in the next following years. 

We welcome and embrace people, regardless of their background, religion, nationality or gender, but focus on diversity, contribution, determination and work ethic. At Nakivo, we are trying to improve everyday, to become a competitive choice for talented people, by offering

* Flexible working hours: Office opens from 6.00 AM to 10.00 PM
* 13-month bonus & performance bonus
* 100% salary on probationary period
* Private health care package
* Premium health care check
* Gift (cash/voucher) for every special occasion: New Year's Eve, Tet holidays, International Women's Day, International Children's Day, Mid-Autumn Festival and Birthday
* Up to 15 annual leaves/year and additional leaves (up to 3 days)
* Team building
* Free and un-limited snack, tea, coffee and by-choice request.

### Contact
* Website: nakivo.com
* Skype ID: anhntv189@gmail.com
* Telegram/ Zalo: 096 121 1545
* Email: hr.vn@nakivo.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by vananh39** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

Hi. The personal email is my Skype ID, I mentioned so that candidates can contact me via Skype. I also mentioned my company email: hr.vn@nakivo.com. Please help to check again. Thank you.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
