### ISSUE TITLE
Java Developer - SAI Digital

### ISSUE THREAD

**Issue by TrucLinhVo** [awesome-jobs/vietnam#2953]
## Requirements
* Good experience with Java-based technologies (Java, J2EE, Hibernate, Spring Framework)
* Good knowledge about OOP and have practice on Unit Test, TDD programing
* Nice to have Design Patterns and Web Services: XML, XSD, XSLT, and JSON
* Experience with Web Layout Design and Development: HTML5, JavaScript, CSS, JQuery, AJAX is a plus
* Good to have knowledge in eCommerce systems, Hybris SAP
* Good willingness to learn new technologies required for work

## Skills
* Java
* J2EE
* Hibernate
* Spring Framework

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop user-friendly eCommerce systems.
* Be a part of our agile teams (Scrum) that uses Java Enterprise (JSP, Tomcat, JPA/Hibernate), Spring Framework (Core, MVC) and Web Services (including SOA).
* Review platform requirements and use your skills to implement great solutions.
* Interact with customers and partners, including business analysts, project managers and developers.
* Make quality and usability your primary goals.
* Problem investigation, system troubleshooting and bug fixing.

### Why it would be awesome to work with us
* 13th-month salary bonus.
* One additional day for Annual leave after each year of service.
* Full base insurance contribution (Social, Health and Unemployment insurance).
* Attractive premium private Healthcare insurance.
* Lunch & parking allowance, gifts in special events.
* Sponsorship for training courses, professional certificates.
* English speaking, professional, dynamic work environment with multi-national team members.
* Opportunity to work on-site abroad.
* Monthly Company’s meeting for employees’ understanding about company’s strategy and development plan; Happy Hour with snack and fresh fruit.
* Various team building, sports activities, company trips, parties, and Trade Union activities, weekly social activities for Cycling club, football club, etc.
* Multi charity activities to create opportunities for employees to help unfortunate people in community.
* Above benefits are designed for Vietnamese employees. Expat’s package will be communicated in offer letter, including work permit support term and condition.

### Contact
Email: linh.vo@sai-digital.com
Or skype: TrucLinh Vo
Website: https://www.sai-digital.com/careers/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
