### ISSUE TITLE
PHP Developer (Mid/Senior Level) - SAI Digital

### ISSUE THREAD

**Issue by TrucLinhVo** [awesome-jobs/vietnam#2954]
#Location 4th Floor, Block A2, Viettel Complex Building, 285 CMT8, W.12, D.10, HCMC, Vietnam

##Salary: 1,500 - 2,500 USD

###Requirements
* 3-5 years of experience in PHP, OOP, Laravel 
* Experienced in optimizing the code & server for high traffic websites 
* Familiar with MySQL, SQL, design database, solve performance issues 
* Familiar with writing unit test in PHPUnit 
* You are well versed in best practices in OOP, design patterns, SOLID principles, and data driven design 
* Able to write well-structured, maintainable code in English 
* Confident in conversational English (written and spoken) 
* Can-do-attitude and put the goals of the team before your own prestige 
* Proactive in finding technical practical solutions to business problems. 

######Nice to have:
* Previous work experience with Amazon Web Services 
* Familiar with front-end web technologies like React, Angular, Node.js, RequireJS, JQuery, WebServices HTML/ CSS coding skills and Ajax. 
* Experience with GIT, CLI 
* Comfort working with Linux server, deployment and configuration 
* Experienced in Magento 2.1+ and follow Magento best practices 
* Autoscaling AWS 
* No SQL platforms e.g. MongoDB 
* Experienced with Redis, Memcached 
* Java coding experience 
* Experience in Machine Learning, AI, Data Analysis 
* Experience with Blockchain, Blockchain Ledgers or Quantum Ledger DB 

#####Great power comes with great responsibilities!

#You’ll be responsible for
* The Developer will develop and improve existing custom software solutions including Content Management System and Ecommerce platforms, Merchandise, Textile domain. 
* You will work in a SCRUM AGILE development team and be familiar with developing enterprise quality code for multinational clients. 
* You are able to work well independently and in groups, you deliver on time and you take initiative to keep team communication alive at all times. 

######13th-month salary bonus.
* One additional day for Annual leave after each year of service.
* Full base insurance contribution (Social, Health and Unemployment insurance).
* Attractive premium private Healthcare insurance.
* Lunch & parking allowance, gifts in special events.
* Sponsorship for training courses, professional certificates.
* English speaking, professional, dynamic work environment with multi-national team members.
* Opportunity to work on-site abroad.
* Monthly Company’s meeting for employees’ understanding about company’s strategy and development plan; Happy Hour with snack and fresh fruit.
* Various team building, sports activities, company trips, parties, and Trade Union activities, weekly social activities for Cycling club, football club, etc.
* Multi charity activities to create opportunities for employees to help unfortunate people in community.
* Above benefits are designed for Vietnamese employees. Expat’s package will be communicated in offer letter, including work permit support term and condition.

#######Contact
Email: linh.vo@sai-digital.com
Or skype: TrucLinh Vo
Website: https://www.sai-digital.com/careers/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
