### ISSUE TITLE
VieON - 04 DevOps - HCM - Fulltime

### ISSUE THREAD

**Issue by ducminhgd** [awesome-jobs/vietnam#2955]
## Location

* District 1, Sài Gòn, Việt Nam

## Salary Expectation (Gross)

* Senior: $3,500 - $6,000
* Mid-level: $1,800 - $3,700
* Engineer: $1,200 - $1,800
* Junior: $600 - $1,200

## Requirements

* No degree is required

### Must Have

* Having knowledge in network and security.
* Having knowledge in CI/CD and tools, such as Git, Jenkins, Ansible.
* Deeply know about OSes: CentOS, Ubuntu.
* Experienced in performance testing and stress testing.
* Experienced in Cloud platforms: Google, Azure, AWS.
* Deeply knowledge in Docker, Kubernetes.
* Deeply knowledge in database: MySQL, PostgreSQL.
* Deeply knowledge in No-SQL database: Redis, MongoDB, Cassandra.
* Having knowledge in Message Queue and Message Broker: RabbitMQ, Kafka
* Having knowledge in building and operating logging service: Sentry, graylog, ELK.
* Having knowledge in building and operating Big Data systems.
* Having knowledge in monitoring tools: Zabbix, Grafana, Nagios.
* Having knowledge in operating web servers: nginx, apache.
* Carefulness, precise.

### Ideally

* Good at communication and cooperation.
* Research and apply tools and technology.
* It is a plus if having knowledge in programming languages: Go, Python, Shell or Lua, etc.
* Be able to read and understand English documents
* Can work under high pressure.
* Having automation mindset.
* Has experiences in high request rate system, high CCU system.
* Has experiences in design software architecture.

### Responsibilities

* Builds environments for OTT products, such as: production, testing and develop.
* Builds services and tools to manage and to store source code, to build and to store built products.
* Logging services.
* CI/CD service.
* Monitor services, dashboards.
* Automation validating and testing services.
* Systems: storage, media transcoder, Big data, live TV.
* Research technology and apply to systems and services.
* Research scaling systems and services.
* Optimize systems and services.

### Why it would be awesome to work with us

* Work with services which have a huge number of requests.
* Challenge with _alien's requests_, _strange things_ to learn new knowledges
* Free VIP account of VieON.

### Contact

Homepage: https://vieon.vn
Email: minh.gia@vieon.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
