### ISSUE TITLE
VieON - 02 SmartTV Developer - HCM - Fulltime

### ISSUE THREAD

**Issue by ducminhgd** [awesome-jobs/vietnam#2956]
## Location

* District 1, Sài Gòn, Việt Nam

## Salary Expectation (Gross)

* Senior: 40,000,000 - 65,000,000
* Mid-level: 30,000,000 - 40,000,000
* Engineer: 15,000,000 - 30,000,000
* Junior: 10,000,000 - 15,000,000

## Requirements

* No degree is required

### Must Have

* Up-to-date, in-depth knowledge of modern web technologies: HTML5, CSS3, JS (ReactJS, TypeScript), NodeJS
* Experience with detect and optimize applications;
* Willingness to learn and able to pick up new technology or new concepts fast;
* Able to work independently as well as in collaborative mode with minimum supervision;
* Work productively even under pressure;
* Possess good work ethic, attitude with good follow-through;
* Have knowledge in Unit Test and applying Unit test;

### Ideally

* Experience with develop application for TV (Samsung, LG) is plus;
* Experience with build video streaming web/app is plus.

### Responsibilities

* Developing features for VieON app (web app) to enhance the user experience, as per the specifications provided by Product and Design teams;
* Write and optimize client-side code of the web applications, create fast application with good UI/UX
* Works closely with API, Product Design and Product Management teams to brainstorm and chalk out details of features;
* Work with other members to develop and integrate new features;
* Writes unit tests for all features;
* Building reusable code for future use;
* Evaluate and identify new technologies for implementation and incorporation.

### You’ll be responsible for

* Develop VieON application for Samsung/LG TV (web app).

### Why it would be awesome to work with us

* Free VIP account of VieON.
* Coffee 5k
* Join company events with many famous top-of-class artists 
* Challenging projects with a casual and friendly work environment;
* Creativity and innovation are highly appreciated;
* The chance to improve your hard and soft skills through workshops, knowledge sharing sessions and presentations on multiple IT-related topics;
* The possibility to become acquainted with trending technologies and frameworks and interact with professional teams that use them;
* Occasional team buildings that let you know your colleagues.

### Contact

Homepage: https://vieon.vn
Email: minh.gia@vieon.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
