### ISSUE TITLE
VieON - 02 Android Developer - HCM - Fulltime

### ISSUE THREAD

**Issue by ducminhgd** [awesome-jobs/vietnam#2957]
## Location

* District 1, Sài Gòn, Việt Nam

## Salary Expectation (Gross)

* Senior: 40,000,000 - 65,000,000
* Mid-level: 30,000,000 - 40,000,000
* Engineer: 15,000,000 - 30,000,000
* Junior: 10,000,000 - 15,000,000

## Responsibilities

* Designs and codes feature for VieON app as per the specifications provided by Product and Design teams.
* Write unit tests for all features.
* Ships feature fast-moving agile sprints.
* Works closely with API, Product Design and Product Management teams to brainstorm and chalk out details of features.

### Requirements

* Software Developer with at least 3 years of experience in building apps for the 
Android platform.
* Good understanding of Kotlin language.
* Good understanding of Android application architecture and design.
* Keep optimization & performance tuning in mind
* Understanding of complete application development, continuous integration & testing and app distribution infrastructure.
* Have a decent knowledge of testing in Android (Unit test, Intergration test, UI test)

### Good to have

* Past experience of working in large scale multi-module apps.
* Past experience of building video streaming apps.

### Ideally

* Writes clean, modular and well-structured code
* Be open-minded, collaborative, accountable, yet independent
* Pay attention to detail
* Be passionate and take ownership of your work
* A passion for Android Development

## Why it would be awesome to work with us

* Free VIP account of VieON.
* Coffee 5k
* Join company events with many famous top-of-class artists
* Challenging projects with a casual and friendly work environment;
* Creativity and innovation are highly appreciated;
* The chance to improve your hard and soft skills through workshops, knowledge sharing sessions and presentations on multiple IT-related topics;
* The possibility to become acquainted with trending technologies and frameworks and interact with professional teams that use them;
* Occasional team buildings that let you know your colleagues.

## Contact

Homepage: https://vieon.vn
Email: thang.nguyen.minh@vieon.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
