### ISSUE TITLE
Ruby Yoda - 2 Senior Ruby Developers - Saigon - FT

### ISSUE THREAD

**Issue by webgago** [awesome-jobs/vietnam#296]
## Location

* Saigon, Vietnam

### Ruby Yoda Vietnam

We are small and young yet. We solve problems of our clients and build own startups.
These positions are for our startup in logistics market (worldwide).

## Salary Expectation

* $1600/month, negotiable (really depends on your skills)

## Requirements
* Ruby
* PostgreSQL
* TDD/BDD, know how to write good specs.
* English proficiency

### Responsibilities
* Build SOLID, good tested json API for iOS, Android and Web clients

### You’ll be responsible for

* Building a new API for logistics market 
* Solve tricky maps, routes and time related tasks 

### You can bring

* All your knowledge in how to build great products
* Know how to test code? Great we have a lot of things to discuss! 😄  

### Contact

Tony: asozontov at gmail dot com
https://www.facebook.com/rubyyodavietnam

**Comment by joneslee85** [comment]
@webgago thanks for posting with us. Are you the HR representative of Ruby Yoda? Besides, wondering if this FB page https://www.facebook.com/rubyyodavietnam/ is your company? Would you be able to provide the product details?

**Comment by webgago** [comment]
@joneslee85 Yes, this is the page. I'm the CEO. We just starting and that's why there is no website yet.

The product is a web platform in logistic market: API, Mobile Apps, Web App.

**Comment by webgago** [comment]
@joneslee85 updated as well

**Comment by joneslee85** [comment]
Please see https://github.com/awesome-jobs/vietnam/issues/297
