### ISSUE TITLE
Mirabo JSC - 02 iOS Developer - Ha Noi - FT

### ISSUE THREAD

**Issue by ashleyngn** [awesome-jobs/vietnam#2960]
## Location

> * Tay Son, Ha Noi

## Salary Expectation

> * up to $1500/month 

## Requirements

> * Develop software features on iOS using Swift
> * Work in a team - cooperating, designing, implementing, deploying, and supporting mobile applications
> * Actively keep track of work requests and progress

## Skills
> * Experienced in iOS native application development using Swift.
> * Experience working in iOS native applications (3+ years).
> * Basic knowledge in computer science (e.g. algorithm, data structure, asynchronous I/O, network).
> * Work experience using version control systems (VCS), dependency management systems, and continuous-integration systems (CI).

### Ideally

> * Open-source software development experience and/or participation in open source communities is also a plus.
> * UI/UX design and implementation (e.g. custom views and interactions).
> * Experienced in iOS native application development using Objective-C.

### Why it would be awesome to work with us

> * Bonus: 13 salary months + Project bonus (If any)
> * Young and dynamic working environment.
> * Opportunity to approach newest technology trends
> * Company's labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trip, Holiday, etc.)

### Contact
Email: hoand@mirabo.com.vn
Skype: live:.cid.a95e5ddf818b8a1c (Hoa Nguyen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
