### ISSUE TITLE
CMC Global - Java Developer - Hanoi - FT

### ISSUE THREAD

**Issue by hvtai** [awesome-jobs/vietnam#2962]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* upto 1600$/month

## Requirements
* Microservices with Java 1.8+, Spring, SpringBoot, Hibernate...
* Apigee, Ping Federate, OAuth and OpenID Connect
* Rabbit MQ, Kafka
* Databases: NoSQL/MySQL/MongoDB/Oracle...
* Git, Jira
* 3+ years Software Engineering experience

## Skills

* Teamwork skill
* Good at investigating and solving incident and problem skill
* Good English skill is a plus

## You’ll be responsible for

* Demonstrated ability to simplify a complex solution into discrete components to parallelize development efforts reducing the overall time to market
* Parner with team to define, analyze, estimate levels of effort to deliver at-scale solutions to meet customer requirements.
* Guide and advocate with technical expertise in the areas of architecture, design, implementation and testing
* Write well designed, testable, efficient code
* Ensure designs are in compliance with specifications
* Prepare and produce releases of software components

## Why it would be awesome to work with us

* Package 14 months of salary
* Project bonus
* Annual package: 16M
* Social Insurance, CMC Care Insurance
* Opportunity to approach newest technology trends
* Exciting leisure: football club, family day...
* Company trip, Holiday...

## Contact
Email: hvtai@cmc.com.vn
Skype: taihv.hr
Linkedin: [http://linkedin.com/in/hoang-van-tai](http://linkedin.com/in/hoang-van-tai)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
