### ISSUE TITLE
[Gameloft] - [Unity Game Developer] - [Ho Chi Minh] - [FT]

### ISSUE THREAD

**Issue by TrucLam3010** [awesome-jobs/vietnam#2965]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $880/month

## Requirements
* Unity
* C#
* Game development
* 2+ year experience

### Must Have

* Be able to develop games from the scratch
* Be able to manage projects

### Ideally

* Experience with game development using Unity

### Responsibilities

- Take part in the development of games using Unity Engine
- Program, debug and optimize codes to implement the gameplay ideas into a game prototype, and polish the prototype to be ready for publishing
- Actively detect issues on programming side, take initiative and propose solutions to prevent and solve those issues
- Analyze existing features of the game and making changes to meet current needs 
- Constantly learn and stay in touch with evolving game standards and development technologies
- Take responsibility for parts of certain medium-level functionality elements or modules 
- Submit constructive opinions 
- Well understand technical requirements 
- Program medium-scale functionality; debugging their own code 
- Use classic data structures and algorithms as well as resource-management techniques 
- Identify and share alternative technologies and techniques 
- Collect metrics and analyzing them 
- Identify problems and resulting dependencies 
- Identify and share alternative technologies and techniques 
- Provide plans that account for assignment of their tasks, dependencies and time
- Document all technical skills and experience to enrich team’s knowledge

### Why it would be awesome to work with us

- Monthly salary alongside Tet and other performance bonuses;
- 100% coverage of mandatory insurances (SI, HI, UI), as well as extra healthcare insurance (PTI);
- Various training packages, including annual training (1), sponsorship training (2) and e-learning (3);
- 12 days of paid annual leave, 5 days of paid sick leave, 12 days of paid holiday leave (including 1 day for Christmas);
- WFH is available during times of Covid-19 (only to local and local expatriates);
- A monthly allowance to cover electricity and Internet bills during WFH periods;
- A range of policies of support employees physically, mentally and emotionally while working from home;
- A dynamic workplace environment, with over 18 nationalities, where hundreds of world-renowned game titles were born;
- Opportunities to train with experts and develop yourselves;
- An open-space office, a cafeteria, a terrace and a Gaming Area;
- Other benefits from one of the best employers in Vietnam.

### Contact
Directly apply via: https://smrtr.io/6v8XQ
OR: Send your CV to: sai-recruitment@gameloft.com, titled: Unity Developer_Your full name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
