### ISSUE TITLE
Viettel Big Data Analytics Center

### ISSUE THREAD

**Issue by huyennguyen362** [awesome-jobs/vietnam#2967]
Viettel Big Data Analytics Center - DAC - TUYỂN DỤNG TTS TÀI NĂNG CÁC VỊ TRÍ
![Neutral Abstract Instagram Course List](https://user-images.githubusercontent.com/92288232/136749915-ceb4722b-3644-4c61-a3da-9517906e5e57.png)

👉Yêu cầu:
Tốt nghiệp loại Khá trở lên các chuyên ngành CNTT hoặc các chuyên ngành liên quan
Toeic từ 550 trở lên (có thể nộp sau)
Có thể làm được full-time
👉Cơ hội
Mức lương cao với các bạn Intern/Fresher
Cơ hội học hỏi trực tiếp, nhận đào tạo và “coaching” từ các Teamlead, Trưởng đơn vị kỳ cựu trong lĩnh vực
Được đào tạo, định hướng thường xuyên, hỗ trợ kinh phí các khóa học và chứng chỉ quốc tế
📩Cách thức ứng tuyển: send CV: tuyendung.dac@gmail.com

**Comment by huyennguyen362** [comment]
Bạn nào quan tâm thì nhắn mình nhé

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
