### ISSUE TITLE
Remote Ruby on Rails Engineers - Middle to Senior Level

### ISSUE THREAD

**Issue by Quynhnhx** [awesome-jobs/vietnam#2968]
## Location

* WorldWide
* Remote

## Salary Expectation

* $2500-5000/month or range

### Development skills

- RoR skills (at least 2-3 years)
- Have knowledge about MVC, service, decorator, serializer, or any other architecture
- Well know about the database (MySQL, PostgreSQL...etc)
- Restful Architecture
- Unit testing
- Experience with React skills
- Good knowledge of redux, component life cycle, react hook
- Good at front-end development. implement with good design will be needed to *don't need to create a design with Figma or adobe xd or sketch... etc. But need to implement these design tools.
### Hope to know about
* Infrastructure and DevOps
* Infrastructure as a code
* AWS, GCP, Azure...
* Deep knowledge about computer science
* Experience of No code or OSS contribution
### You will be a great fit if you have:
* High sense of responsibility and teamwork.
* The passion to remove unnecessary coding and create innovation
* Honesty and a good heart
* Able to communicate fluently in English
* Good at writing and reading in English is a big plus
### Benefits

- Can work part-time during the probation if you recently have a full-time job.
- Full remote and you can work from all over the world and work in your timezone
- At least you need to attend video calls without delay and work on a stable internet. We may ask to meet in JST but we can make arrangements for a meeting schedule.
- We'll provide some benefits if you'll work as a full-time regular employee.
- Tax (maximum 10% of salary- Employer's Support)
- Premium insurance
- 20 Annual Leaves
- MacBook Pro provided
- Happy Hours
- Sponsorship for classes - English/ Training

### Read this before apply
* Please provide source code you write by attach zip, by Github repo... etc
* Please provide your github profile. If you are not using github, any other git hosting site would be welcome.
* Tell us about your expectation of monthly salary in USD
* We would ask trial work for 1-3 months. (can work as part-time if you want in this period)

### Our Mission:
Build the Next Era of Software Development There are so many problems and difficulties in software development. I know you faced a lot of problems when you create software. Like hard to learn, delay for release, incident with fatal bug. But every company and every person needs software. It's obvious. So, currently, in this world, too much demand and less supply. If we can find a better way to create software, If we can change the way of software development If we can establish brand new software development, things will change and we can build the next era of software development. Let's Build the Next Era of Software Development with us. And let's create move values of software for everyone.

### Our Value:
* Love & Success

For our client, for teammates, for everyone, strongly recommend you to love ppl who will work with. Because without love, it's too hard for you to use your important time. Do you know that love is technology? Everyone wants to be loved, but it's rare to know how to love. I recommend you to read this if you wanna know more And once, you can learn how to love, your work will be happier than before. But don't forget about success. Love is just for preparation for success. We need to guide our clients to success. Because we are doing business. So love them until their success, and after their success, let's celebrate! But Don't forget! The most successful company should be us!

* Professional

We need to be professional because our mission is "Build the Next Era of Software Development". To archive this, we'll require so high-level skill. Because only ppl who have high skill can change the software development way. Without software development skills, we cannot change the way of it of course. For project management, business analysis, for coding, we need a lot of skills. So let's be professional. And not only skill, but we also need output too of course. Only skill doesn't mean good work. To "Build the Next Era of Software Development", we need to be professional for any work and need to create great output with high skill!

* Hack

Find the beak through point. Find Leverage point. Find where we can hack so that we can get great output. Don't be tied up with old ideas. Our mission is Build the Next Era of Software Development and to archive this, we need to find the point of hack. Then we can change this software development which is so difficult and having too many problems. Without hack, we'll be just normal or just good company. To be great company, let's find where we can hack, and let's execute it!! Don't think your current work is the best. The key is to get the biggest achievement with the smallest effort.

### Contact
* Homepage: https://iruuza-inc.com/
* Email: quynh.xuan@iruuza.com
* Link JD: https://apply.workable.com/jitera/j/B2598515D8/

**Comment by zrg-team** [comment]
Very good nice opportunity.
