### ISSUE TITLE
JobSeekervn - Blockchain Developer - Fulltime - Saigon 

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#2970]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1800 - $2200 Net /month or range

## Requirements
* Strong cryptography knowledge
* At least 3 years of experience with ReactJS & NodeJS 
* Knowledge of blockchain and smart contracts concepts (especially Ethereum, BSC, NFT), with at least 1 year of experience in development and deploying production code to mainnet
* English speaking

### Responsibilities

* Research, design, develop, and test blockchain technologies that could be utilized in EcoSystem.
* Analyze, brainstorm and evaluate applications of newly emerged tools and technology.
* Maintain and extend the current platform, responsible both for the blockchain smart contract and the integration to the client & server side application.
* Document new solutions and maintain the existing one.
* And perform similar duties as he deems fit for the proper execution of his duties and duties as delegated by the direct manager or the Employer.

### Why it would be awesome to work with us
* Laptop provided 
* 13th month salary, social insurance, annual health check
* 14 days leave 
* Company trip, happy hours 

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
