### ISSUE TITLE
[Ha Noi] CMC Global hiring Java developer (middle/senior)

### ISSUE THREAD

**Issue by huyenvu301** [awesome-jobs/vietnam#2971]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to $1500/month

## Requirements
- At least 2 years of working experience in java development.
- Familiar with Spring Boot, Spring, Spring MVC, Mybatis, PostgresSQL, or MySQL
- Knowledge Microservice Architecture
- Has some knowledge of widely used middleware, like Kafka, Redis, rabbitMQ, etc
- Well understand of JVM, multithread, etc.
- Good teamwork capability and communication skills

### Responsibilities
We’re looking for candidates to work as part of a team is responsible for Java application development and delivery. The candidate would focus on investigating and resolving application issues, building the rich frontend and the scalable backend based on Java & other integration frameworks.
Primary roles & responsibilities:
- Handle end to end software development life cycle
- Application development/unit testing
- Design, build and implement Java-based applications
- Guiding junior developers
- Brainstorming various strategies to deliver optimum and high quality code
- Partnering with the business to achieve its goals with respect technology
Great power comes with great responsibilities!

### Benefits
- Up to 1500$ per month
- 13th month salary bonus
- Bonus based on project and performance 14th
- “CMC care” health insurance
- Annual Summer Vacation: follows company’s policy
- Salary review 2 times/year or on excellent performance
- International, dynamic, friendly working environment
- Annual leave, working conditions follow Vietnam labor laws.
- Other allowances: working on-site allowance, etc.
- Total allowances: 16.000.000 VND ~ 17.000.000 VND per year

### Contact
Huyen Vu: 0981.096.290
Skype: huyenvu301

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
