### ISSUE TITLE
NMS - Python (Odoo/Django) - Hanoi - FT

### ISSUE THREAD

**Issue by mhang285** [awesome-jobs/vietnam#2972]
## Location

* Hanoi, Vietnam
* Full-time

## Salary Expectation

* Up to $650/month

## Requirements
* At least 1 years of working experience in Python Odoo/Django, from level Junior
* Have knowledge of Agile/Scrum is a plus
* Good teamwork capability and communication skills
* No requirements in English communication skill

### Responsibilities

* Participate in research and development of network security solutions
* Monitor and detect attacks.
* Information security management for organizations/enterprises.
* Analyze requirements, design system.
* Optimize system performance.

### Why it would be awesome to work with us
* Up to 1500$ per month
* 13th month salary bonus
* “NMS care” health insurance
* Annual Summer Vacation: follows company’s policy
* Friendly working environment
* Annual leave, working conditions follow Vietnam labor laws.
probation

### Contact
Ms Hang
Gmail: hangnpm@nms.com.vn
Skype: mhang.285@gmail.com
Phone/Zalo: 0915804468

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by mhang285** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

I edited. Thank you!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
