### ISSUE TITLE
[HCM/HN] - Fintech - Senior/Medior Java Engineer

### ISSUE THREAD

**Issue by Samle2101** [awesome-jobs/vietnam#2973]
### Location: Hanoi and Ho Chi Minh
* Fulltime

## Salary Expectation

*** Negotiation (up to 2800$/month)**

## Responsibilities
* Work with the dedicated mobile team to ensure projects are delivered on time, and to best practice & quality guidelines
* Enhancing applications by identifying opportunities for improvement, making recommendations and designing and implementing systems
* Maintaining and improving existing codebases and peer review code changes
* Liaising with colleagues to implement technical designs
* Investigating and using new technologies where relevant
* Providing written knowledge transfer material

## Our Steck

**Our services tech stack consists of Java, Kotlin, Redis, Async Queues(SQS, SNS), and PostgreSQL. Currently, all run on the  cloud infrastructure with auto-scaling abilities and are maintained through CI/CD & IAAC (Terraform)**

### Requirement

* Having a minimum of 3-5 years of experience in software engineering, application development or system development
* Passion in software engineering, application development, or systems development
* Excellent understanding of software engineering concepts, clean code, OOPs, minimalist/lean design, trade offs, automated testing and algorithms
* Comfortable working up and down the technology stack
* Curiosity to explore creative solutions and try new things
* Bachelors’ degree in Computer Science or equivalent from a reputable university
* Proficiency in  with outstanding written+verbal communication skills and ability to work collaboratively

### Interesting engineering projects

**It is the online credit lending facility that enables users to pay for various products on Ecommerce Platforms with short-term loans (installments from 1 to 12 months). The goals for the team are to ensure that we have sufficient funding to sustain our business growth and the optimizing funding structure and execution so that we obtain the best cost of funds.**

### Contact
**Skype:  live:.cid.3574192feff64ebf
Zalo/Whatsapp: 0348686427**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
