### ISSUE TITLE
[Zigexn Ventura] - [Ruby on Rails Developer] - [Sai Gon] - [FT]

### ISSUE THREAD

**Issue by DungPham1112** [awesome-jobs/vietnam#2974]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Up to $2500 Gross/month or range

## Requirements
* At least 3 years of experience with Ruby on Rails
* High-level Object-oriented programming skills.
* Relational database design and implementation using PostgreSQL/MySQL.
* Basic understanding of front-end technologies, such as HTML, JavaScript, CSS, and jQuery.
* Strong analytical and problem-solving abilities, support other members and can do code reviews.

### Responsibilities

* Join in a product/system design phase with a Japan team to analyze system requirements.
* Suggest, propose creative solutions to solve problems.
* Design, develop and test high-traffic Web applications in Ruby on Rails (sometimes do DevOps to deploy to production).
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

### Why it would be awesome to work with us

+ Salary: Upto $2500
+ 100% salary on 2 months of probation
+ 13th-month salary.
+ 15-18 days of paid leave for employees with 1+ years of working.
+ Language support program for Japanese, English.

### Contact
Homepage: Zigexn.vn
Mail: dungptt@zigexn.vn
Skype: live:.cid.f512cbec13c5904c

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
