### ISSUE TITLE
[Base Global] Software Engineer (for Talent Fresher) - Hanoi - Fulltime

### ISSUE THREAD

**Issue by BaseTalent** [awesome-jobs/vietnam#2975]
## Location

Hanoi, Vietnam

## Salary Expectation

Up to 1200$ 

## Job Description
* Tham gia phân tích, lên kế hoạch, thiết kế, phát triển và bảo trì sản phẩm;
* Lập trình full-stack trên framework của công ty sử dụng ngôn ngữ PHP, Javascript và JQuery;
* Đóng góp những ý tưởng sáng tạo, giải quyết các vấn đề công nghệ phức tạp.

## Requirements
*  Nắm vững lý thuyết về cấu trúc dữ liệu và giải thuật;
* Có kiến thức vững chắc và kinh nghiệm sử dụng một ngôn ngữ lập trình bất kỳ (PHP/Javascript là lợi thế);
* Có kiến thức hoặc kinh nghiệm sử dụng Restful API, MySQL, HTML5, CSS3, Javascript, jQuery, AJAX, JSON;
* Hiểu về tối ưu hiệu năng hoặc đã từng có kinh nghiệm cho những ứng dụng thực tế trên production, phục vụ lượng lớn người dùng và dữ liệu - là một lợi thế.
* Mong muốn tham gia xây dựng sản phẩm “B2B SaaS - Make in VietNam" phát triển ở thị trường quốc tế.

## Why it would be awesome to work with us
**Hỗ trợ tối đa phát triển cá nhân :**
- Môi trường khuyến khích tự do sáng tạo và khởi xướng ý tưởng, phát triển sản phẩm cá nhân (được hỗ trợ) để hướng tới mỗi cá nhân có thể trở thành 1 Product Owner; chủ động, năng động, sáng tạo và có lộ trình thăng tiến rõ ràng;
- Làm việc cùng đội ngũ nhân sự đầy nhiệt huyết, chuyên môn dày dặn kinh nghiệm, tốt nghiệp từ các trường hàng đầu Việt Nam và thế giới: Stanford, UCLA, HUST, NEU, FTU,...;
- Nâng cao chuyên môn thông qua training trực tiếp, các buổi sharing nội bộ và khuyến khích đề xuất các khóa học để bổ trợ và phát triển năng lực, kiến thức. 
**Quyền lợi đặc biệt tới nhân viên:**
- Gói lương thưởng hấp dẫn: Lương cứng lên đến $1200 + bonus hiệu quả sản phẩm;
- Đánh giá tăng lương linh hoạt (4 lần/năm) tương xứng theo kết quả công việc;
- Có cơ hội nhận thưởng cổ phiếu ESOP cho các cá nhân có đóng góp xuất sắc;
- Gift code cho các bạn tập gym bơi lội tại tòa nhà công ty;
- Các chế độ khác theo quy định Luật lao động;
- Nghỉ mát tối thiểu 2 lần/năm;
- Tham gia các hoạt động teambuilding, liên hoan,... theo chế độ công ty, bộ phận

## Apply
Mail: phuong.tran@platform.inc
Skype: hrm.minhphuong     

## More About Base
Website & Product: https://base.vn/
People & Career: https://www.facebook.com/Base.Tuyen.Dung
Base - Giải nhất nền tảng số xuất sắc nhất 2020
https://ictvietnam.vn/tu-hao-cac-san-pham-cong-nghe-so-make-in-viet-nam-duoc-vinh-danh-lan-dau-tien-20201223135105817.htm
Base - Top 10 Doanh nghiệp CNTT về Chuyển đổi số 2020
https://cafebiz.vn/basevn-nhan-cu-dup-giai-thuong-chuyen-doi-so-tai-top-10-doanh-nghiep-cntt-2020-2020121517001492.chn

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
