### ISSUE TITLE
[Base Global] JavaScript Engineer - Hanoi - Fulltime

### ISSUE THREAD

**Issue by BaseTalent** [awesome-jobs/vietnam#2976]
## Location
 Hanoi, Vietnam

## Salary Expectation
Upto 2000$ + Performance Bonus

## JOB DESCRIPTION
We would like to invite you to join a team of many young talented engineers who have already built a highly large-scale system serving 50+ millions of pageviews and hundreds of thousands users each month.
**You will be responsible for building and maintaining sophisticated frontend components (including: Editor, Diagram, FlowChart, Notification, ..) that will be the core of True Platform's frontend framework.** Your work will improve the quality of the products and set out a foundation for many other's codebase. It will profoundly impact the work life of thousands of companies.
You will work and report directly to the CEO (who happens to be the CTO at the same time). As being a culture of Builders, we would love to work with someone who's humble, open to learning, loves coding, loves to solve challenging technical problems and is motivated by making good values for people and the world.

## REQUIREMENTS
* **Highly experienced in JavaScript**: It's just not possible to complete the task if you aren't;
* **Good knowledge in Data structure and Algorithm**: JS is definitely a fun and elegant language to work and you could already write a lot of JS. However, we would like to assure you that this task is not like writing a simple jQuery plugin. Components are complex, performance is a crucial issue and we couldn't talk about performance-related issues if you do not have a solid understanding of Algorithm and Data Structure;
* **Proficient in HTML/CSS**: We don't expect UI experience much; in fact, UI may not be crucial for this job. However, you should be able to write HTML/CSS easily;
* **Experienced in OOP and know (love) to write modular code**: Once you work in a large-scaled system, you won't be able to tolerate non-modular code with no structure again;
* **Love coding.** Coding should be fun and enjoyable to you - as we all are;
* We expect to work with respectful team members who are eager to learn, have a strong passion in making good value to people and the world;
* Graduated from university with Computer-science major.

## BENEFITS
**Career Growth**
- Opportunity to promptly boost your capability by solving challenging issues of a large-scaled system . It’s worth your try;
- An environment that encourages the freedom to create and initiate ideas, develop personal products (supported). Each individual can become a Product Owner; Proactive, dynamic, creative and has a clear promotion roadmap;
- Experience a great workplace where young & professional talents work together passionately;
- Improve expertise through face-to-face training, internal sharing sessions, and encourage recommending courses to supplement and develop capacity and knowledge.
**Salary & Allowances**
- Competitive salary: upto 2000$ + bonus based on performance;
- 4 times review per year based on your work result (optional: and/or reward in token based on your performance, contribution);
- 12 full-paid days off per year, public holidays and insurance in accordance with the Labor Law of Vietnam;
- Be provided with high performance computer and screen (iMac);

## APPLY
Mail: phuong.tran@platform.inc
Contact: hrm.minhphuong (Skype) or 0986865560 (Zalo)

------------------------
## ABOUT BASE:
Website & Product: https://base.vn/
People & Career: https://www.facebook.com/Base.Tuyen.Dung

Base - Giải nhất nền tảng số xuất sắc nhất 2020
https://ictvietnam.vn/tu-hao-cac-san-pham-cong-nghe-so-make-in-viet-nam-duoc-vinh-danh-lan-dau-tien-20201223135105817.htm
Base - Top 10 Doanh nghiệp CNTT về Chuyển đổi số 2020
https://cafebiz.vn/basevn-nhan-cu-dup-giai-thuong-chuyen-doi-so-tai-top-10-doanh-nghiep-cntt-2020-2020121517001492.chn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
