### ISSUE TITLE
Star Global - [Sign-on Bonus] Lead/Senior Frontend Engineer - ReactJS - HCMC - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2977]
## Location
* Saigon, Vietnam

## Salary Expectation
* Yes, we have a budget for every Engineering level but...
* Due to the company policy, we can only let you how your salary expectation will fit in our budget but it definitely matches with the current market or even higher *wink

## Requirements
- Experience architecting solutions and leading a team
- 5+ years of experience as a Frontend Engineer (Front-end: React, Redux, rxjs; DB: PSQL, Redis)
- Experience developing responsive web apps
- Experience in writing semantic HTML5, CSS3, and CSS preprocessors like Sass and Less
- Experience in writing unit tests for JavaScript code (Jest, Enzyme)
- Understanding of app/browser performance improvement techniques and potential cross-browser issues 
- Understanding of continuous integration and continuous delivery 
- Understanding of microservices approaches and practices
- Strong spoken and written English
Nice to have:
- Experience with AWS Cloud Services
- Experience with fintech products
- Experience with NodeJS

## Skills
React - Javascript

### Responsibilities
- Adapts existing methods and procedures to create alternative solutions to moderately complex problems
- Development of the new functionality to support web/mobile application
- Participation in the architecture sessions, deciding on solutions together with the client
- Team management
- Implementation of the unit tests
- Conduction of the code reviews
- Use of own judgment to determine the optimal solution to recommend
- Performance of primary upward interaction with direct supervisor or teams’ leads. Generally interacts with peers and/or management levels
- Determination of the methods and procedures on new assignments with minimal guidance

### You’ll be responsible for

A very interesting **fintech project** that Star is working with a **startup**!

### Why it would be awesome to work with us
_**1 month Sign-on Bonus is applied for this position, onboard with our crew from now to Jan 2022 to be eligible!**_
- Flexible working hours with hybrid working policy (remote & office);
- Global consulting environment & opportunities to learn and use trending tech stacks through high-quality projects;
- Impressive salary package;
- 20 days of paid leaves, 01 Christmas leave and 01 birthday leave;
- 10 days of paid sick leaves offered by Star;
- Latest MacBook Pro & monitor or you can bring your own device, we'll compensate you monthly;
- Full social insurance and private healthcare insurance from PVI starting from your probation;
- Free English classes and many more to come!

### Contact
Vietnam Career Homepage: https://star.global/careers/?location=824
Send your CV directly to: quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
