### ISSUE TITLE
Star Global - [Sign-on Bonus] Solution Architect - Java - HCMC - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#2978]
## Location

* Saigon, Vietnam
* Hybrid working mode - remote + office

## Salary Expectation

Yes, we have a budget for every Engineering level but...
Due to the company policy, we can only let you how your salary expectation will fit in our budget but it definitely matches with the current market or even higher *wink

## Requirements
- 5+ years of Java development experience;
- 2+ years of Team Leading experience;
- Proven experience in designing architecture as well as building and deploying scalable solutions using AWS cloud platform;
- Expert knowledge in designing RESTful API contracts;
- Strong knowledge of Java 8+ and Spring (Boot, Cloud, Data, Security);
- Hands-on experience with RDBMS (Postgres) and NoSQL (MongoDB, Redis);
- Knowledge of design principles, patterns and best-practices such as Service Registration and Discovery, Load Balancing, Caching, Observability, Resiliency and Redundancy;
- Advanced level of English and the ability to communicate with a client directly.

Nice to have:
- Understanding of microservices architecture and practical experience building microservices within a cloud platform;
- Experience with event-driven architectures and messaging systems (Kafka, Amazon SQS);
- Experience with ElasticSearch;
- Passion for various engineering practices and proper process setup;
- Experience with Docker and CI/CD.

## Skills
Java + Spring + AWS + Upper-intermediate English communication skills

### Responsibilities
- Work closely with the client to design the architecture of the cloud platform and its core components;
- Participate in pre-sale activities as Solution Architect – provide estimations and solution suggestions.
- Provide technical leadership and guidance to the development team to ensure that platform services are built according to defined contracts;
- Develop server-side components and integrations with external systems;
- Define non-functional requirements for scalability, throughput, response time and ensure proper implementation;
- Conduct architecture meetings, assist the development team in presenting technical solutions and accelerate their implementation;
- Maintain technical excellence backlog and facilitate the process of decreasing amount of technical debt on the project;
- Adapt existing methods and procedures to create alternative solutions to moderately complex problems;
- Use own judgment to determine the optimal solution to recommend;
- Determine methods and procedures on new assignments with minimal guidance;
- Manage medium-small sized teams and/or work efforts;

### Why it would be awesome to work with us
**_1 month Sign-on Bonus is applied for this position, onboard with our crew from now to Jan 2022 to be eligible!_**
- Flexible working hours with hybrid working policy (remote & office);
- Global consulting environment & opportunities to learn and use trending tech stacks through high-quality projects;
- Impressive salary package;
- 20 days of paid leaves, 01 Christmas leave and 01 birthday leave;
- 10 days of paid sick leaves offered by Star;
- Latest MacBook Pro & monitor or you can bring your own device, we'll compensate you monthly;
- Full social insurance and private healthcare insurance from PVI starting from your probation;
- Free English classes and many more to come!

### Contact
Vietnam Career Homepage: https://star.global/careers/?location=824
Send your CV directly to: quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
