### ISSUE TITLE
IPSIP - Azure SRE - C# Pulumi - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by jdipsip** [awesome-jobs/vietnam#2979]
## Location

* Saigon, Q2, Vietnam

## Salary Expectation

* Up to 2000$/month

## Requirements

* Azure Cloud experience
* Infrastructure as code (terraform, pulumi)
* C#

### Must Have

* Experience working on an Azure Infrastructure
* Experience using Infrastructure as Code tools (terraform / pulumi)
* Able to work and communicate in English
* C# basic knowledge

### Ideally

* Previous experience managing a large scale SaaS platform is a plus
* Development experience (basic OOP understanding)

### Responsibilities

You will be joining a SRE team on a large scale Enterprise Content management solution targeting Fortune 2000 companies and migrating it from an on premise solution to a cloud base solution on Microsoft Azure.

### You’ll be responsible for

* developing new and maintaining infrastructure as code definitions
* collaborate with the customer to define and implement all automation mechanisms for their teams
* participating in the daily life of the project

### You can bring

* Out of the box thinking - finding innovative solution to existing challenges

### Why it would be awesome to work with us

* Full social insurance during probation
* Full salary in probation
* 100% Tet bonus
* Medical Healthcare Insurance to take care of you and your family
* Salary review 1 time/year or when you have excellence achievement
* Great chance to develop your skills and competences, with Internal and / or external training and discover new technologies
* Opportunities for promotions and career development in a dynamic
* Company trip, many exciting activities for team building
* Free parking, coffee and tea

### Interesting engineering projects

IPSIP is a company offering Infrastructure architecting, implementation and monitoring services to our customers in various sectors (finance, enterprise systems, accounting, content management, ...) as well as on various kind of "basis" (AWS / Azure / GCP / On Premise / ...). 
You will be working in a multi cultural and multi "technological" environment where the keyword is : Make IT easy and Make IT work ... (more than often ... the "easiest" solution is also the "safest" solution !) 

### Contact
Homepage: www.ipsip.eu
Jean-David Silberzahn: jd@ipsip.eu

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
