### ISSUE TITLE
Golden Owl - Fresher/junior trainee ruby on rails - Saigon - FT

### ISSUE THREAD

**Issue by Rosedao03** [awesome-jobs/vietnam#298]
## Location

* Saigon, Vietnam
* Full time

## Salary Expectation

* up to $500/month hoặc thương lượng

## Requirements
* Tốt nghiệp chuyên ngành CNTT hoặc sinh viên mới ra trường, Công nghệ phần mềm,... 
* Biết về Ruby/Javascript
* Tư duy logic tốt, nắm được căn bản lập trình hướng đối tượng
* Sáng tạo, cẩn thận, ham học hỏi, yêu thích và đam mê phát triển sản phẩm

### Ideally

* Experience with Ruby on Rails

### Responsibilities
* Làm việc với khách hàng Singapore và thảo luận với các thành viên trong team
* Làm việc theo sự phân công của Team leader

### Benifits
* Được học hỏi các kỹ năng làm việc từ môi trường thực tế 
* Làm việc trong môi trường quốc tế năng động sáng tạo
* Team building và trợ cấp ăn trưa + gửi xe 
* Được xem xét tăng lương 6 tháng 1 lần 
* Cơ hội làm việc và học tập từ công nghệ và cách làm việc ở Singapore.

### Contact

Rose Dao : rose.dao712@gmail.com
Justin Nguyen: justin@goldenowl.asia

**Comment by joneslee85** [comment]
@Rosedao03 We've revise our guideline, job post now must be written in English. Please feel free to submit a new one.
