### ISSUE TITLE
IPSIP - C# developer - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by jdipsip** [awesome-jobs/vietnam#2980]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500/month (negotiable)

## Requirements
* 3+ years software engineering experience (C#)
* Knowledge of object-oriented design and design patterns
* Practical knowledge of  Backend WEB technologies and SQL
* Knowledge on REST / SOAP api and interested in Enterprise Content Management
* Interest (or experience) in content analysis (information retrieval / query processing algorithms)

### Must Have

* C#
* OOP and design patterns
* REST / SOAP API
* able to work and communicate in english

### Ideally

* Experience working within an international team
* Experience or interest working and integrating Enterprise content management system (eg: sharepoint / ...) into other solution 

### Responsibilities

You'll be working in the team responsible to write connectors for the integration of new Enterprise Content Management systems into a global Enterprise document indexing platform

### Why it would be awesome to work with us

Full social insurance during probation
Full salary in probation
100% Tet bonus
Medical Healthcare Insurance to take care of you and your family
Salary review 1 time/year or when you have excellence achievement
Great chance to develop your skills and competences, with Internal and / or external training and discover new technologies
Opportunities for promotions and career development in a dynamic
Company trip, many exciting activities for team building
Free parking, coffee and tea

### Contact
Homepage: www.ipsip.eu
Jean-David Silberzahn: jd@ipsip.eu

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
