### ISSUE TITLE
WebGL Developer (Fulltime Remote) 1600-2000 USD

### ISSUE THREAD

**Issue by tranphuong0211** [awesome-jobs/vietnam#2981]
## Location

* Remote

## Salary Expectation

* USD 1600-2000/month 

## Requirements
* The knowledge of THREE.js
* Experience in JavaScript (ES6 / ES7), React, CSS 3D transitions
* Experience with PIXI, PlayCanvas or 8th Wall will be a strong advantage
* Familiarity with continuous integration and automated deployment systems
* Solid understanding of how the back end works and understand the role of a framework like Node. js or a language like Java. If you ve got experience with building things on the back-end (APIs, services etc.) even better.
* Bachelor's degree in Computer Science, Design or other relevant field

### Responsibilities

* Building online visualization tools primarily using WebGL for rendering alongside JavaScript / TypeScript and with some exposure to the Node / Java backend. 
* You'll take ownership of the software you build but also be an active member of the engineering team, collaborating with other developers to ensure standards are kept high and improvements are made.

### Why it would be awesome to work with us

* Attractive Salary
* International and friendly working environment

### Contact
* Zalo/Phone: (84) 777047369
* Email: recruiter.it@gmail.com
* Skype: tranphuong0211
* Website: www.ideabox.com.au

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
