### ISSUE TITLE
Kilo - Full-Stack Software Engineer (NodeJS/ReactJS) - Ho Chi Minh City - FT 

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#2982]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

- Up to 3,000 USD Gross for Mid Level 
- Up to 5,000 USD Gross for Senior Level (or higher if you are a talent)

## Who we are

Kilo is a technology start-up in Vietnam. Our customers are primarily small and medium-sized retailers and  distributors. 
Kilo’s mission is to shift the B2B2C ecosystem with a mission to empower retailers. This is done by  democratizing access to the best pricing, assortment, and inventory management. We are building the next  generation retail platform by bridging the gap between traditional distribution channels with robust software  systems 
Kilo was founded on the principle that technology can affect change in traditional and deeply entrenched  sectors such as offline retail stores. Our sales and technology platform is one-a-kind specifically built to  address retailer and brand pain points and solve them at scale.

## About the role

At Kilo, we care deeply about our team and we are obsessed with crafting a fun, productive, collaborative,  diverse, friendly environment that can enable everyone to do the best work of their careers, and have the best  time doing it. 
After a lot of hard work over the last year, we are ready to expand our product lines and thoughtfully grow the  team! We are hiring passionate, collaborative, customer-driven engineers who share our belief that modern  business software can be fast, fluid, beautiful, and even joyful to use.  
We leverage iterative, test-driven development and continuous integration to reliably deliver value to customers  and we prioritize a high-ownership, low-overhead approach to software development, where you'll be expected  to build, launch, and operate product features end-to-end.

## How we work & What we use

- JIRA for ticket & task management
- SCRUM as project management methodology
- Planning meeting at the beginning of a two-week sprint and daily meetings
- Macbook for software development
- Github for VCS, CircleCI for CI/CD
- Slack for communication
- Google workspace for emails, calendars, drive and meeting
- English for communication

## Requirements

  - 3+ years of experience as a full-stack engineer & being able to work on both front-end and back-end side
  - Familiar with building web services & web application using NodeJS, Typescript, ReactJS (or similar technologies / languages like Python or Java)
  - Familiar with *nix (Mac OS X, Ubuntu, CentOS, etc.) based development and execution environments
  - Familiar with the RDBMS (e.g. Postgres, MySQL …)
  - Good problem solving skill (we pay more attention to your mindset, not the programming languages you know)
  - Being a good team player who can cooperate with others and also able to work independently in the daily work
  - Being able to communicate in English

### Nice to have

- Knowledge about AWS or devops task (manage the AWS infrastructure using terraform or similar tool)
- Experience with application design
- Experience with building scalable application to deal with high web traffic
- Experience with common methods for securing the connections in distributed environment

### Why it would be awesome to work with us

- Flexible working time
- Latest Macbook & external monitor are provided
- Young and dynamic environment (we always trying to improve ourselves day-by-day)
- Annual salary review
- Company trip, many exciting activities for team building
- Free parking, coffee and tea

### Contact
tran.ngo@kilo.vn OR mobile (0901091161) for more details.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
