### ISSUE TITLE
Python Developer - Orient Software Da Nang

### ISSUE THREAD

**Issue by Diemphamm** [awesome-jobs/vietnam#2983]
**Responsibilities**

- Create well design background process to handle high volume of data (utilizing queueing system)
- Create and manage several API integrations
- Build high performance, scalable solutions using Kubernetes, AWS Lambda, and Google Cloud BigQuery
- Contributing to our unit testing suite
- Ensuring security best practices

**Requirements**

- Development experience in a professional capacity for 2 or more years
- Experience in using Python and Flask or Django
- Have knowledge with Microservices
- Experience in using a Queue system (RabbitMQ, SNS, etc)
- Good knowledge & proficient in using: SQL, MySQL, PostgreSQL, or similar
- Experience with a cloud service provider like AWS or Google
- Experience with Docker
- Proficiency in GIT using GIT flow

**Monthly Salary and Benefits**

- Attractive salary based on your performance
- Annual 13th month salary
- Dedication bonus goes up to 40% monthly salary
- Project bonus will be paid twice a year
- Premium healthcare insurance, Annual health checks up.
- Breakfast are available at office in early morning and snack in late afternoon.
- Happy Lunch every two weeks.
- Team building allowance.
- Annual Company team building trip.
- Clubs (Football, Badminton, Swimming, Chess, Music band).
- Exclusive training programs for all staff in technical, soft skills and process.
- Outdoor training every 6 months.
- English class.
- Technical clubs.
- Marriage allowance, having newborn baby allowance, bereavement allowance.

Apply via email: diem.pham@orientsoftware.com
For further information, please contact via Skype: Diem.phamm

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
