### ISSUE TITLE
SERVISHERO - Fullstack NodeJS/ReactJS Engineer (All levels - Junior/Mid/Senior) - HCM - FT

### ISSUE THREAD

**Issue by nvtin** [awesome-jobs/vietnam#2986]
## Location

UPGEN - BKHCM 268 Ly Thuong Kiet, Dist 10, HCMC

## Salary Expectation

* $1200 - $3000/month

## About Job
Be your best, and join us to radically transform labour productivity in Southeast Asia!

In 2020, ServisHero Group ("SHG") launched its SaaS software for the service industry called Workmagic (www.workmagic.app) - you will be part of a team developing this revolutionary cloud solution and we hope that tens of thousands of small businesses will adopt this tool within the next years. The product is first of its kind in Southeast Asia - it combines labour management, with digital payments and digital marketing functions.

We operate on the philosophy of building fast (execution matters), coming to the table with solutions, and delivering extraordinary quality. Our distributed team is multinational and diverse. You'll get to work on game-changing and exciting technologies and will be given an opportunity (and be expected) to be innovative in the solutions you build.

## Requirements
* At least 1 year hands-on experience on software engineering with at least one of the languages NodeJS/Ruby/Python, and willing to learn and use NodeJS..
* Hands-on experience with ReactJS/Redux is a plus.
* Good communication skills in English and Vietnamese.
* Solid understanding of a web framework, database and Object-relational mapping. Experience in Express JS, Feathers JS, * Postgres, Redis and/or Sequelize ORM is a plus.
* Able to use Git and review pull-requests.
* Experience with CI/CD build and deployment processes. Experience with Jenkin, Google Cloud Service is a plus.
* (**Senior**) Able to provide technical solutions that meet the requirements and timelines. These solutions should also be performant, scalable and easy troubleshooting.

## Skills
* Good at teamwork skills

### Responsibilities
You will be part of a team developing a cloud solution for Home Service Business community in Southeast Asia. The product has been released last year and growing rapidly. The platform runs on Google Cloud infrastructure, supporting web and Android clients. Your role is as important as any other members in the team. You will participate fully in defining, developing, validating and maintaining the products. You will work on all the features, both front-end and back-end. You will communicate directly to remote teams (Sales, Marketing, Customer Support, Leadership) in Malaysia.

### Why it would be awesome to work with us
 ServisHero Group is on a mission to make lives and businesses better in Southeast Asia. We believe we can do this by utilizing technology to improve the productivity of citizens around the SEA region.
### _You’ll_ love working at ServisHero Group because:

- Young, motivated and energetic team
- Outstanding product in Home Service Business field in Southeast Asia.
- A solution-focussed environment where extraordinary talent is rewarded.
- Flexible working hours and space.
- 12 days annual leave + extra public holidays.
- Offices across Southeast Asia, with an opportunity to be based either in HCMC or Kuala Lumpur, Malaysia.

### Contact
Homepage: www.servishero.com
Tin Ngo: tin@servishero.com
Phone: 0868 890 001

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
