### ISSUE TITLE
Fetch - Security Analyst/Engineer - HCM - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#2988]
![company trip](https://user-images.githubusercontent.com/60914247/137840630-9e117244-ceab-472b-859f-e86a19872e67.jpg)

# **INTRODUCTION**

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily on the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client:**
Originally founded in Silicon Valley in 2014 and headquartered in Singapore, our client is a market-leading, and one of the oldest, homegrown cryptocurrency platforms. Their aim is to accelerate access to cryptocurrencies throughout the ASEAN region and we focus on localized cryptocurrency exchange services – acting as cryptocurrency gateway services in multiple countries.

# RESPONSIBILITIES

- Responsible for analyst information security, protection and management framework, guidelines and best practices for the organization.
- Manage cloud security services to ensure the latest security improvements can be implemented.
- Implement security solutions for the protection of cloud/on-prem environment, endpoint, networks, information.
- Apply adept understanding and experience with systems automation platforms and technologies.
- Interpret security and technical requirements into business requirements and communicate security risks to relevant stakeholders ranging from business leaders to engineers.
- Direct and influence multi-disciplinary teams in implementing and operating Cyber Security controls.
- Collaborate with application developers and database administrators to deliver creative solutions to difficult technical challenges and business requirements.
- Employ cloud-based APIs when suitable to write network/system-level tools for safeguarding cloud environments.
- Stay abreast of emerging security threats, vulnerabilities and controls.

# REQUIREMENT

- Degree in Computer Science, Information Systems, Engineering.
- Competency gained from 2+ years of production deployment experience using AWS security services and features.
- Experience in working AWS Kubernetes, EKS, ECS, Fargate Lambda... & AWS Security Services: Security Hub, Guarduty, CloudWatch, CloudTrail...
- Strong familiarity with Linux and Windows operating systems and cloud provider ecosystems like Amazon AWS.
- Hands-on experience in security systems, including NextGen Firewall: Palo Alto, Checkpoint, Fortinet, EDR, SIEM/SOC....
- Capability architecting highly available systems that utilize load balancing, horizontal scalability and high availability.
- Working knowledge of AWS security services and features of services to provide a secure production environment.
- Understanding of complex enterprise environments and current technology areas like cloud and mobility
- Knowledge of Operating and maintaining tools across Cloud security technology stack (CSPM, CWPP, SASE, CASB, CIEM, Cloud-native features like Guard Duty, etc.).
- Able to work with various multi-disciplinary teams, team-oriented individuals with priority on the successful completion of business goals.

**Nice to have:**

- Familiar with and passionate about digital assets, its network and protocol.
- Desirable Skill(s): AWS Security / AWS Associate Architecture or similar Certified

# WHY YOU‘LL LOVE WORKING HERE
Being a Security Analyst / Engineer at this company, you will experience a youthful, flexible and creative work environment.  

- MacBook or high-end laptop for working.
- Attractive salary and bonus package (13th-month salary, performance bonus).
- Salary review twice a year.
- 14+ annual leave, 60 days working from home per year.
- Working in a professional, friendly, flexible, well-equipped environment.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law; Premium Health Care.
- Personal Growth Development Plan.
- Enjoy diversified activities: Snack every day, Happy Friday every week, Monthly Team-building, Company trip (2 trips per year), Game, Sport (Football, Badminton...). 

# WORKING TIME & LOCATION

- Working time: 9AM - 6PM from Monday to Friday.
- Location: 4th floor, HQ Tower - No. 9, Tran Nao Street, Binh An Ward, Thu Duc City (District 2), Ho Chi Minh City. 

# CONTACT:
Mail: trangdong@fetch.tech
Skype: trangdong0111@gmail.com

# OR APPLY THROUGH THIS JD: https://bit.ly/3DFOQYB

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
