### ISSUE TITLE
LINE Vietnam - Backend Engineer - HCM - FT

### ISSUE THREAD

**Issue by dattnguyen1991** [awesome-jobs/vietnam#2989]
## Location

* Viettel Tower, 285 CMT8, District 10, Ho Chi Minh city

## Salary Expectation

* Top market salary package
* Sign-on Bonus is applied for this position, onboard from now till the end of Dec 2021 to be eligible!

## Requirements

* At least 3 years (or equivalent) experience in software development
* Knowledge software design patterns
* Experience in server architecture design for handling massive traffic
* Good at communication skills in general and English
* Strong at the problem-solving skill

### Must Have

* Deep knowledge and experience in Object-Oriented programming and applying Design Patterns
* Experience in Data Structure, Algorithm, Distributed Service
* Experienced in merging, branching source code using a distributed VCS such as GIT/BitBucket/SourceTree etc
* Experienced in System Analysis & Design, n-Tier Architecture, Micro Service Architecture is a PLUS
* In-depth experience in designing, developing, testing, and deploying backend API across development environments DEV, TEST, STAGING, and PRODUCTION

### Ideally

* Experience in Software Development with Java
* Experience in Web Development using Spring/Spring Boot framework
* Experience in constructing & operating storage in Large Data Distributed Environments (MySQL, Hadoop, HBase, Redis, MongoDB)
* Experience in Cloud-based, Containerized application development

### Responsibilities

* Working closely with our products and planning teams to build products with the goal of delighting and increasing the success of our services.
* Rapidly build, iterate, test, and deploy new features and products
* Maintain a high-quality robust codebase
* Being parts of the product development from inception to launch, and own large parts of the product and its features
* Architecting, building, testing, and releasing features with the highest quality
* Automating everything that an engineer should not work on

### Why it would be awesome to work with us

* Developing your career in a famous international product company and having opportunities to work with the latest technologies through high-quality projects.
* Training with senior mentors on hot-trend technologies, best practices, and soft skills
* Opportunities to Travel/Work overseas (Korea, Japan, Thailand, Taiwan...)
* Impressive salaries package, incentives, and benefits.
* 13th-month bonus, performance bonus
* Stock options
* Flexible working hours with hybrid working policy (remote & office)
* Latest Macbook Pro model with 27" 2K monitor
* Free snack and drinks
* Working at our brand new office in Viettel Tower
* Free Korean classes and many more to come
* Provide Team building funds for the individual employees so you can build your own event with your own beloved team.
* 14 days of paid leaves (increase 1 day per year), 01 birthday leave
* Private health care package
* 100% salary on probation period
* All default benefits follow Viet Nam labor laws

### Interesting Engineering Projects

* Zero-downtime deployment for long-running background jobs
* [LINE App](https://line.me/) ecosystem with monthly 200m active users from Japan, Thailand, Taiwan, Indonesia...

### Contact
Kindly send your CV to email: dat.nguyen@linecorp.com
Linkedin: https://www.linkedin.com/in/dattnguyen1991/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
