### ISSUE TITLE
Golden Owl - Junior trainee Ruby on Rails/JavaScript - Saigon - FT

### ISSUE THREAD

**Issue by Rosedao03** [awesome-jobs/vietnam#299]
## Intro

Golden Owl is  a HCMC-Singapore joint venture group focusing on helping customers turn their ideas into websites. Our customers' satisfaction will always be our priority! 
We are a young, responsible, and professional team based in Ho Chi Minh City, Vietnam, specializing in web and mobile development with the latest Ruby on Rails and JavaScript technologies. We are a group of creative experts who build full-stack solutions for our customers in multiple platforms with highly scalable back-ends and rich media front-ends. We provide fast, reliable, and professional software outsourcing, IT service consulting, website designing, and automation testing.
## Location
- Saigon, Vietnam
- Full time
## Salary Expectation
- up to $500/month or negotiable
## Requirements
- Fresher/gradudated university related to Technology, computer science....
- Have knowledge about ReactJS/AngularJS/EmberJS or Ruby
- Good logic thinking, good knowledge about basic object devlelopment
- Creative, careful, eager to learn new things, have passion on product development
## Skills
- Ruby/JavaScript
### Ideally
- Experience with Ruby
### Responsibilities
- Work and discuss with Singaporean clients and other members in team
- Work under Team leader's delegation
### Benefit
- Learn working skills from reality working environment
- Learn new things in dynamic international environment
- Team building and allowance (lunch + parking)
- Salary increment every 6 months
- There is PS4 for you to play when joining us 
### Contact

Rose Dao: rose.dao712@gmail.com
Justin: Justin@goldenowl.asia

**Comment by joneslee85** [comment]
@Rosedao03 looks okay. Please make following amendment:

* What is Golden Owl? Can you please do a section intro?
* the `#Contact` header is on wrong line
* terminology terms should be respected such as `reactjs/angular/ember` must be changed to `ReactJS/AngularJS/EmberJS`
* remove the space after `/` as in `Fresher/ gradudated`
* `s/ruby on rails/Ruby on Rails` in the title
* the word `fresher/junior` can be change to `Junior Ruby On Rails Developer` (if you like).

**Comment by Rosedao03** [comment]
done @joneslee85 please help me check if there is any problem :)
thanks!!!

**Comment by joneslee85** [comment]
* `s/Javascript/JavaScript` (for every occurrences)
