### ISSUE TITLE
LINE Vietnam - Automation QA - HCM - FT

### ISSUE THREAD

**Issue by dattnguyen1991** [awesome-jobs/vietnam#2990]
## Location

* Viettel Tower, 285 CMT8, District 10, Ho Chi Minh city

## Salary Expectation

* Top market salary package
* Sign-on Bonus is applied for this position, onboard from now till the end of Dec 2021 to be eligible!

## Position Summary

* We are looking for engineer with broad experience controlling and evaluating project quality. We expect candidates capable of automation and manual testing (Related to APIs, Mobile, Web, service servers, databases,...)

## Requirements

* At least 3 years (or equivalent) experience in software development
* Knowledge software design patterns
* Experience in server architecture design for handling massive traffic
* Good at communication skills in general and English
* Strong at the problem-solving skill

### Must Have

* Strong experience in automation testing
* Strong computer science fundamentals in algorithms and data structures
* Experience in Database testing, be able to test at Function level and Non-Function level
* Experience with test frameworks: REST- Assured, JUnit, and TestNG
* Be able to execute some basic non-functional testing such as Performance, Security, etc.
* Prefer candidates being capable of executing automation test for the project if necessary, with any program
language: Java, Python, etc.
* Ability to evaluate, predict risk when receiving a project, or to analyze the problems related logic (such as mistake or lack ...), latent errors in the system is a big plus.

### Responsibilities

* Ensure the assigned tasks to be performed on time and with high quality
* Provide functional and regression level testing for API, Web, and Mobile Applications
* Develop and execute automated functional and regression test cases and integrate into the CI/CD pipeline
* Participate in code and design reviews to maintain our high development standards

### Why it would be awesome to work with us

* Developing your career in a famous international product company and having opportunities to work with the latest technologies through high-quality projects.
* Training with senior mentors on hot-trend technologies, best practices, and soft skills
* Opportunities to Travel/Work overseas (Korea, Japan, Thailand, Taiwan...)
* Impressive salaries package, incentives, and benefits.
* 13th-month bonus, performance bonus
* Stock options
* Flexible working hours with hybrid working policy (remote & office)
* Latest Macbook Pro model with 27" 2K monitor
* Free snack and drinks
* Working at our brand new office in Viettel Tower
* Free Korean classes and many more to come
* Provide Team building funds for individual employees so you can build your own event with your own beloved team.
* 14 days of paid leaves (increase 1 day per year), 01 birthday leave
* Private health care package
* 100% salary on probation period
* All default benefits follow Viet Nam labor laws

### Interesting Engineering Projects

* [LINE App](https://line.me/) ecosystem with monthly 200m active users from Japan, Thailand, Taiwan, Indonesia...

### Contact
Kindly send your CV to email: dat.nguyen@linecorp.com
Linkedin: https://www.linkedin.com/in/dattnguyen1991/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
