### ISSUE TITLE
TurnDotMedia - JR PHP DEVELOPER - REMOTE - PT

### ISSUE THREAD

**Issue by CharlesSOo** [awesome-jobs/vietnam#2992]
## Location

* Remote

## Salary Expectation

* Depending on skillset

## Requirements

* Strong English Skills 
* PHP
* Wordpress
* MySQL
* CSS/HTML basic (not design work, but should be able to add some front end features without it looking like a blind person did it)
* 5-10 hours week
* Telegram IS A MUST
* Timedoctor for logging hours (no tracking)

### Must Have

* Wordpress
* Woocommerce Experience 

### Responsibilities

* Completing Task in a timely manner 
* Optimizing large ecommerce site

### Why it would be awesome to work with us

This would be a gig/part time, it's perfect for someone looking for extra work after their day job. We're flexible, work within weekly task meaning issues are provided on Monday and must be completed by Sunday unless there any major urgent issue.   

We respect you have a life, we just care about the quality of your work rather than anything else. 

**We can pay in crypto**

### Contact

Telegram: Coop0x

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
