### ISSUE TITLE
LINE Vietnam - Blockchain Software Engineer - HCM - FT

### ISSUE THREAD

**Issue by dattnguyen1991** [awesome-jobs/vietnam#2993]
## Location

* Viettel Tower, 285 CMT8, District 10, Ho Chi Minh city

## Salary Expectation

* Top market salary package
* Sign-on Bonus is applied for this position, onboard from now till the end of Dec 2021 to be eligible!

## Position Summary

* Develop/Enhance LINE Blockchain MainNet/TestNet and Research/Develop its application service
* Research/Design/Develop/Operate next generation’s Blockchain platform
* Research/Design/Develop/Operate Blockchain Protocol Standard for dAPP
* Research/Develop/Operate Consensus Algorithm to improve Blockchain Performance
* Design/Develop/Operate Scaling Algorithm for Blockchain’s usability
* Develop on-chain governance for Blockchain platform
* Research/Design/Develop/Operate Central Bank Digital Currency (CBDC) Platform

## Requirements

* Strong at the problem-solving skill
* Fluent English
* Those who have no reasons for disqualification for overseas business trip/work
* Have an interest in Blockchain technology and services that are utilizing it
* Have a lot of interest and understanding in Cryptocurrency and its related newest trends

### Must Have

* Proficient in Go language
* Skilled in acquiring new languages and adaptive in given tasks
* Understand and can apply data structures, algorithms necessary for distributed systems
* Experienced with using JIRA, Confluence, GitHub
* Actively expresses one’s opinion and can positively contribute to the team and project
* Open to Pair Programming and Code Review, well aware of the necessity of writing Test Code
* Those who value the equality structure between team members; those with an open mindset, who can communicate smoothly with business, planning, development and UX members about various issues while creating a service.
* Want to actively participate in global challenges when developing LINE Blockchain Platform in order to create a successful service experience

### Ideally

* Those who have experience in design review and analysis for open-source blockchain core technologies such as Ethereum, EOS, Cosmos, Substrate, Algorand, etc.
* Those who have vast basic knowledge of consensus algorithms, blockchain protocols, and smart contract operating environments
* Experience in distributed network programming
* Those with global service/platform operation and development experience
* Those who have experience working as an open-source contributor

### Why it would be awesome to work with us

* Developing your career in a famous international product company and having opportunities to work with the latest technologies through high-quality projects.
* Training with senior mentors on hot-trend technologies, best practices, and soft skills
* Opportunities to Travel/Work overseas (Korea, Japan, Thailand, Taiwan...)
* Impressive salaries package, incentives, and benefits.
* 13th-month bonus, performance bonus
* Stock options
* Flexible working hours with hybrid working policy (remote & office)
* Latest Macbook Pro model with 27" 2K monitor
* Free snack and drinks
* Working at our brand new office in Viettel Tower
* Free Korean classes and many more to come
* Provide Team building funds for individual employees so you can build your own event with your own beloved team.
* 14 days of paid leaves (increase 1 day per year), 01 birthday leave
* Private health care package
* 100% salary on probation period
* All default benefits follow Viet Nam labor laws

### Interesting Engineering Projects

* [LINE App](https://line.me/) ecosystem with monthly 200m active users from Japan, Thailand, Taiwan, Indonesia...

### Contact
Kindly send your CV to email: dat.nguyen@linecorp.com
Linkedin: https://www.linkedin.com/in/dattnguyen1991/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
