### ISSUE TITLE
LINE Vietnam - Application Security Engineer - HCM - FT

### ISSUE THREAD

**Issue by dattnguyen1991** [awesome-jobs/vietnam#2994]
## Location

* Viettel Tower, 285 CMT8, District 10, Ho Chi Minh city

## Salary Expectation

* Top market salary package
* Sign-on Bonus is applied for this position, onboard from now till the end of Dec 2021 to be eligible!

## Position Summary

* We work to make LINE's products and systems safe. You'll be primarily tasked with finding problems through code reviews. This position requires knowledge of Security & Hacking in application-level. LINE is a global messenger service serving users all around the world, and we take safety and privacy of our customers very seriously. Members of the LINE Security team working in Japan, Korea, Taiwan, and Thailand are collaborating globally. We are looking for people who have hacker mindset, yet understand the importance of business. We don't just look for vulnerabilities, we spend our time thinking about making our products and customers safe.

### Must Have

* 3 years of experience in application-level security testing and code auditing.
* Work experience in web application security, especially -Java applications
* Work experience in mobile security
* Knowledge of software engineering, applied cryptography, authentication, and network security
* We'd love to check your github repos and presentations in the fields of information security
* Work experience in mobile security

### Responsibilities

* Code audits, design reviews, and security assessment task
* Hunting new attack vectors through research
* Mitigating security vulnerabilities
* Hacker mindset as defender, helping developers and securing the products

### Why it would be awesome to work with us

* Developing your career in a famous international product company and having opportunities to work with the latest technologies through high-quality projects.
* Training with senior mentors on hot-trend technologies, best practices, and soft skills
* Opportunities to Travel/Work overseas (Korea, Japan, Thailand, Taiwan...)
* Impressive salaries package, incentives, and benefits.
* 13th-month bonus, performance bonus
* Stock options
* Flexible working hours with hybrid working policy (remote & office)
* Latest Macbook Pro model with 27" 2K monitor
* Free snack and drinks
* Working at our brand new office in Viettel Tower
* Free Korean classes and many more to come
* Provide Team building funds for individual employees so you can build your own event with your own beloved team.
* 14 days of paid leaves (increase 1 day per year), 01 birthday leave
* Private health care package
* 100% salary on probation period
* All default benefits follow Viet Nam labor laws

### Interesting Engineering Projects

* [LINE App](https://line.me/) ecosystem with monthly 200m active users from Japan, Thailand, Taiwan, Indonesia...

### Contact
Kindly send your CV to email: dat.nguyen@linecorp.com
Linkedin: https://www.linkedin.com/in/dattnguyen1991/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
