### ISSUE TITLE
JobHopin - Research Blockchain Engineer - HCMC - FT

### ISSUE THREAD

**Issue by thonguyen2501** [awesome-jobs/vietnam#2995]
**Location: HCMC**

**Salary: up to $2000**

**Description**

- Research and development of software of Blockchain
- Fully implemented and involved in the blockchain ecosystem for integrating the latest possible improvements.
- Undertake necessary research to identify, develop or customize appropriately software applications
- Act as a source of information and advice to other members of the project on software techniques and capabilities
- Carry out other appropriate duties as may be assigned from time to time as required
- Contribute to the smooth running of the group’s research by establishing and maintaining effective working relationships with a very diverse range of people

**Requirement**

- Bachelor's degree in computer science, information science, or similar.
- Experience in research about Blockchain (at least 2 years)
- Basic understanding of Cryptography
- Standard algorithms and data structures knowledge
- General knowledge in Software Engineering
- Experience with the top blockchain technology like Bitcoin and Ethereum
- Able to speak, read and write in English is a plus

**Benefits**

- 13-month salary.
- Working in a dynamic, technological environment
- Social/health/unemployment insurance
- Health check annually
- 100% probation salary
- Insurance full salary

**Contact me via:
Skype: tho.nguyenthicam**

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
