### ISSUE TITLE
HÀ NỘI - FULLTIME - GOLANG DEVELOPER TỪ 6 THÁNG KINH NGHIỆM

### ISSUE THREAD

**Issue by thu192** [awesome-jobs/vietnam#2999]
## Địa điểm

* Hanoi, Vietnam
* Fulltime

### Mô tả dự án
* Phát triển ứng dụng trên kiến trúc Micro services sử dụng Golang, Restful/GraphQL/gRPC, Redis
* Tham gia vào việc nghiên cứu giải pháp, phân tích thiết kế và tối ưu hoá hệ thống.
* Tìm hiểu, nghiên cứu công nghệ mới.

## Yêu cầu công việc
* Có ít nhất 6 tháng kinh nghiệm lập trình backend sử dụng Golang
* Kinh nghiệm làm việc với 1 Golang framework: Gin, Revel
* Nắm vững kiến thức về OOP, hiểu biết về Design Patterns, SOLID
* Có kiến thức về database design, query optimization, DB tuning, clustering
* Hiểu biết về xử lý tối ưu performance và security
* Có tư duy tốt, có khả năng tự học hỏi cao, cập nhật kiến thức nhanh
* Khả năng teamwork tốt
* Có hiểu biết về mô hình Agile/Scrum

### Quyền lợi và chế độ đãi ngộ
* Thời gian làm việc: 8h00 – 17h30 (Trưa nghỉ 1,5 giờ) thứ 2 đến thứ 6 hàng tuần
*  Mức lương từ 800$ - 1500$
*  Môi trường Open & Flat luôn mong muốn tạo mọi điều kiện, sân chơi riêng cho nhân viên để có thể phát huy năng lực
* Thưởng tháng lương 13, thưởng theo dự án, thưởng nóng, thưởng nhân viên xuất sắc…
*  Xét điều chỉnh lương 2 lần/năm
*  Bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo quy định của Luật lao động
*  Tạo điều kiện để nhân viên có thể công tác ngắn hạn tại Nhật Bản hoặc làm việc dài hạn tại Fabbi Japan
*  Tham gia miễn phí các hoạt động đào tạo của công ty: Đào tạo tiếng Nhật, Technical, Business manner…
*  Tham gia hoạt động tập thể: Du lịch, teambuilding định kì…
*  Có cơ hội trở thành Key member, Leader, PM

### Về chúng tôi 
Công ty cổ phần nghiên cứu và phát triển FABBI được thành lập từ tháng 3/2018, chuyên cung cấp các services/solutions cho đối tác IT tại Nhật Bản.
Sau hơn 3 năm hoạt động, Fabbi đã và đang dần khẳng định vị thế của mình trên thị trường IT,
Với tốc độ tăng trưởng nhanh chóng, hiện công ty có gần 250 nhân sự tại Việt Nam và Nhật Bản, với 5 văn phòng tại Hà Nội và 1 văn phòng tại Tokyo.
Fabbi đặt mục tiêu trở thành Top 5 tập đoàn công nghệ hàng đầu Việt Nam và Top 3 doanh nghiệp IT Việt Nam tốt nhất tại Nhật Bản vào năm 2025, với quy mô nhân sự 1000 kỹ sư IT tại Việt Nam và hơn 200 kỹ sư tại Nhật Bản.

Ngoài việc, đẩy mạnh phát triển các hệ thống IT hạ tầng cơ sở như quản lý sản xuất, quản lý nghiệp vụ tài chính ... Fabbi coi: ① tư vấn và triển khai chuyển đổi số doanh nghiệp, ② nghiên cứu và phát triển những sản phẩm / dịch vụ mang thương hiệu Fabbi dựa trên nền tảng công nghệ mới nhất như AI / Blockchain, là mũi nhọn phát triển doanh nghiệp.
Fabbi mong muốn dùng sức lực, trí lực của mình để phát triển đất nước, “Vì một Việt Nam Hùng Cường”. Và Việt Nam & Nhật Bản là bệ phóng để Fabbi mang trí tuệ Việt Go Global trong 5 đến 10 năm tới

Địa chỉ làm việc: Tầng 11, tòa nhà Detech 2 Tower, số 107 Nguyễn Phong Sắc, Cầu Giấy, HN

### Contact
Homepage: https://www.facebook.com/hr.fabbijsc
Skype: sandsea192

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by thu192** [comment]
Thank you for your response.

Do I need to translate this post to English?
*--*
*Best regards, *
*Ms. Thu Nguyen*
*Tel :* (+84)968456059
*Skype:* sandsea192
*Email: ***@***.***




Vào Th 6, 22 thg 10, 2021 vào lúc 09:17 Lạc Trôi ***@***.***>
đã viết:
