### ISSUE TITLE
[LOSHIP] - [ANDROID DEVELOPER] - [HCM] - [FT]

### ISSUE THREAD

**Issue by ThienTTz** [awesome-jobs/vietnam#3001]
## **Location**

* Saigon, Vietnam

## **Salary**

* 1000 - 1800 / Month

## **Skills**
* Android Native
* * MVVM

### Ideally 

> Extensive Android app experience (1+ year experience)
> Extensive knowledge of core Computer Science concepts, including Object-Oriented programming, multi-threading, MVVM/VIPER, etc.
> Significant experience architecting and designing applications
> Experience using source control and bug tracking software such as Git and Jira or Trello.
> Leveraging industry best practices for quality code, including unit tests, automated UI tests, API stubs/mocks, etc.
> Profound and broad knowledge of the Android SDK
> Producing responsive, beautiful UIs, as well as different screen size and various android version classes compatibility
> Experience with a wide breadth of data storage techniques, including SQLite, Realm(will be good), etc.
> Understanding API interactions from end-to-end, particularly with RESTful APIs.

### **Contact**
Homepage: https://loship.vn/careers/jobs/
Mail: ta@lozi.vn
skype: okies11
Phone: 079 362 6408 Ms. Trang

**Comment by qcam** [comment]
Please kindly provide more information about the position. This post will remain closed until fully elaborated. Thanks.
