### ISSUE TITLE
[Vulcan Labs] - [Fullstack Developers] - [HCM] - [FT] 

### ISSUE THREAD

**Issue by lstrgiang** [awesome-jobs/vietnam#3002]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1k - $1k8 per month

## Requirements
* A degree in Computer Science or Software Engineering is a must.
* 2-4 years (junior or middle roles)

### Must Have
* Good understanding of DSA, OS & networking protocols
* Familiar with or willing to learn Python & Golang
* Familiar with SPA applications (ReactJS, VueJs, etc.)
* Familiar with popular development processes (Scrum, Agile, etc.) 

### Ideally
* Have experiences with DevOps and Cloud Services
* Have experiences with CMS 

### Responsibilities

* Develop server side of cross-platform applications
* Develop client side of a website application with provided design
* Provide clear documentation on the system and implemented APIs
* Design architecture based on business specifications
* Integrate CMS to provide marketing strategic operations

### Why it would be awesome to work with us
* FLEXIBLE WORKING TIME: 5 working days/ week with no overtime.
* SALARY & BONUS: Additionally to the 13th-month salary, you will have an attractive remuneration package including KPI bonuses and hot rewards for each project. Salary review occurs once annually based on performance and contribution. Full salary paid during work remotely period
* BEING A GREAT CULTURE: You will participate in the development team of top chart applications globally at a cool office with young and friendly talents with a global approach.
* CHALLENGE YOURSELF: You have an opportunity to work with cutting-edge technology: Virtual Reality, Augmented Reality, Artificial Intelligence and challenge your career path with the meaning of “ Go Big or Go Home”.
* NO BARRIERS: You are independent to give ideas and design innovative products to serve millions of global users and products will stand on top of technological trends.
* OTHER BENEFITS: 01 duvet day/month and Netflix package during work from home period. We have so many events such as company trips, team building, birthday party, year-end party

### Contact
* Homepage: vulcanlabs.co
* HR: tramnguyen@vulcanlabs.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
