### ISSUE TITLE
RedFOX Labs - Fullstack Developer - RemoteWork - Fulltime

### ISSUE THREAD

**Issue by AnhRFL** [awesome-jobs/vietnam#3003]
**Location**

* Saigon, Vietnam
* Remote

## Requirements
* JavaScript Framework (Reactjs)
* Nodejs
* MongoDB
* 5+ years Software Engineering experience

## Skills
* Strong organizational and project management skills
* Proficiency with fundamental front-end languages such as HTML, CSS, and JavaScript
* Familiarity with JavaScript frameworks such as React JS (Angular JS and Amber is a big plus)
* Proficiency with server-side languages such as Node.js (PHP, Python, Ruby, Java, .Net big plus)
* Familiarity with database technology such as MongoDB (MSSQL, Oracle big plus)
* Excellent verbal communication skills
* Good problem-solving skills
* Attention to detail

### Must Have

* Nodejs
* Reactjs
* MongoDB
* English communciation (verbal and written)

### Ideally

* Experience with Amber, PHP, Python, Angularjs, Ruby,.net

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Developing front end website architecture
* Software Engineering background using DevOps and / or Google SRE
* Building and using a software QA and deployment pipeline - CI/CD
* Designing user interactions on web pages
* Developing back-end website / cron applications
* Creating servers and databases for functionality
* Ensuring cross-platform optimization for mobile phones
* Ensuring responsiveness of applications
* Working alongside graphic designers for web design features
* Seeing through a project from conception to finished product
* Designing and developing APIs
* Meeting both technical and consumer needs
* Staying abreast of developments in web applications and programming languages

### You can bring

* A good analysis skill
* Result-oriented spirit

### Why it would be awesome to work with us
* Remote working Opportunity
* People First Culture
* A talent Team, Diversified team from all over the world
* Career growth
* Awsome projects/products
* Emerging Technology (Blockchain, AI, AR/VR,etc)

### Interesting engineering projects
* Virtual space
* NFT Games
* and more

### Contact
Homepage: https://redfoxlabs.applytojob.com/apply/oe4Qu3DL9w/Full-Stack-Developer?source=Github
Anh Tran: anh@redfoxlabs.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
