### ISSUE TITLE
OOOLAB - Senior Frontend Developer - HCMC - FT (Remote)

### ISSUE THREAD

**Issue by NhungLeee** [awesome-jobs/vietnam#3007]
## Location

* Saigon, Vietnam
* Remote 80%. You may go to the office 1 or 2 times per week (if needed)

## Salary Expectation

* $2500 - 2700/month 

## Requirements
* ReactJS
* Typescript
* AWS
* 4+ years Software Engineering experience with at least 3 years in ReactJS

### Responsibilities

* Develop new user-facing features, maintain the current features
* Assist with architecture as well as work on actual implementation
* Build reusable code and libraries for future use, review other team members’ coding, ensure the implementation of agreed architecture and infrastructure.
* Work with frontend/backend team to plan and design structure of platform technology solution, help define the standard for Laboratory
* Address technical concerns, ideas and suggestions
* Focus on UI/UX and work with designers and PO’s when necessary
* Optimize platform applications for maximum speed and scalability
* Monitor systems to ensure they meet both user needs and business goals
* Collaborate with other team members and stakeholders

### You’ll be responsible for

* Building a superrrrr cool platform which helps educators digitalize their works

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.

### Contact
Homepage:  #https://ooolab.edu.vn/
Email: nhung.le@ooolab.edu.vn
LinkedIn: https://www.linkedin.com/in/nhung-le-22a41180/
Skype: rosie.307

**Comment by NhungLeee** [comment]
Add ơi ad có thể add label lang:reactjs, saigon, senior và remote giúp mình đc ko ạ huhu đội ơn add mình ko biết add labels @lactroi

**Comment by qcam** [comment]
@NhungLeee Bạn vui lòng chỉnh lại tiêu đề theo mẫu

```
[Company Name] - [Job Title] - [Location] - [Job Type]
```

tại https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post thì bài sẽ được đánh nhãn nhé. Cảm ơn bạn.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
