### ISSUE TITLE
[GHN] Senior Software Engineer (Golang) - HCM - FT

### ISSUE THREAD

**Issue by TongTrangHr** [awesome-jobs/vietnam#3009]
## Location

* Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
* Fulltime

## Salary Expectation
* Negotiable

## Requirements
* At least 3+ years of experience as Software Engineer (1 year as a senior software engineer)
* Knowledge and experience in Golang or any general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6. and be willing to change to Golang.
* Experience with two or more data systems but not limited to: Postgres, Mongodb, Elasticsearch, Redis, RabbitMQ, Kafka, Cassandra.
* Good understanding and knowledge of OOP, data structure, design patterns. 
* Familiar with Microservices, event driven architecture.
* Self-motivated to explore new technologies, applications, and environments. 
* Can work in both independent and teamwork environments.
* Experience with Front End (ReactJS or VueJS or SPA...) **(a plus)**
* Having knowledge with offline web apps, websocket, networking, caching **(a plus)**
* Have experience with Docker, K8s **(a plus)**
* Have at least 2 years working in a company **(a plus)**

##  You’ll be responsible for
* Optimizing components for consistency and performance across desktops, tablets, and mobiles.
* Collaborate with cross-functional teams to design, develop and ship new features. 
* Optimize the system for reliability and performance. 
* Fix bugs and improve the system. 
* Write unit test code to prevent similar bugs Responsibility to resolve bugs as soon as possible. 
* Provide methodology and metrics to monitor the system. 
* Improve performance, the reliability of the system. 
* Contribute knowledge to the technical team. 
* Review team member code.
* 
## WHY YOU'LL LOVE WORKING HERE
* Top 3 Logistic company in Vietnam 
* Fair team
* Annual health check-ups.
* 13th salary
* PVI Care
* Performance bonus Comfortable Private working Area for TECH team
* Sports club: Running, football, badminton
* Open communication with Senior Engineer & Technical Leader
* Challenging working environment with attractive domain as Logistics
* Specific pantry with nice decoration & Coffee/Milk Coffee/Chocolate & Tea
* Comfortable Private working Area for TECH team
* Annual Team-building + Outing trip
* Join Training Courses and Tech Sharing
* Mid-Autumn Party, Christmas party, Year-end Party
* With the delivery network cover more than 98% geographical area of Vietnam, you will be welcome anywhere in Vietnam for traveling

### HOW TO APPLY
Tong Trang (Ms.)
Email: tongtrang96@gmail.com
Skype: live:.cid.b71ee10d04a05617
Mobile: 0906738591
Title: [Position - Your Name]
Homepage: http://scommerce.asia/

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
