### ISSUE TITLE
Pangara - iOS/Android Developer (freelancer) - Remote - PT

### ISSUE THREAD

**Issue by pangarajobs** [awesome-jobs/vietnam#301]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Remote

## Project Background
Pangara needs help of a skilled iOS/Android Developer Freelancer to build an Android app from an existing iOS app. The iOS app is a generic app that is adjusted for each specific client case. Technology used is mainly React Native but there are some native Objective-C parts in the code. 

The freelancer needs to make an estimate on time and workload. The iOS app is available with a login account. More information will be provided when the project started.

## Salary Expectation
* Starting from 15 USD/hour and could be negotiated depends on project requirements.

## Requirements
* iOS/Android app development 
* Javascript 
* React Native 
* Objective-C

## Responsibilities
* Port existing iOS app to Android app

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by PangaraTeam** [comment]
@hieuk09 We just updated. Thanks for your inform.

**Comment by joneslee85** [comment]
@PangaraTeam thanks for posting with us. Can you please clarify if this is Pangara project or of Pangara's clients?

**Comment by pangarajobs** [comment]
It's one of our client's project. So you guys do not allow freelance job posts here?

**Comment by joneslee85** [comment]
@pangarajobs no, we don't.
