### ISSUE TITLE
[ubitec] - [Full stack Java] - [HCM office or remote] - [Full Time]

### ISSUE THREAD

**Issue by UyenTong** [awesome-jobs/vietnam#3011]
## Location

* Saigon, Vietnam
* Remote or at the office

## Salary Expectation

* $1800/month or range

## Requirements

* Experience with J2EE
* Springboost Framework
* ReactJS or Angular
* Familiar with JavaScript ecosystem (Node.js, Webpack, ESLint, Polyfill, etc).
* 2+ years Software Engineering experience
* Good communication skills in English - both written and verbal.

### You’ll be responsible for

* Plan, analyze, implement feature base on specific requirement.
* Responsible for keeping good project quality and stable development environment.
* Self-organize time and work.
* Collaborate, guide, remind teammate to do the right things.

### You can bring

* Take responsibility to get the job done.

### Why it would be awesome to work with us
17 Annual leaves, 5 Sick leaves and 3 Funeral leaves each year
Annual salary review and bonus based on performance and contribution
Flexible working time policy - including remote working
Laptop, lunch and parking fee provided
Kid allowance
Annual Health check, PVI healthcare and full-salary based insurance
Annual company trip (foreign country trip every 3 year) every even year
Family trip (provided for your close relative) every odd year
Onsite work in Switzerland (few weeks) for training and team meeting
Office located in the central with great accommodations (standing desk, free drinks and snacks, game room,...)

### Contact
Skype: uyentong
Email: uyen.tong@umb.ch
[ubitec - Fullstack Java Developer-2021.pdf](https://github.com/awesome-jobs/vietnam/files/7433456/ubitec.-.Fullstack.Java.Developer-2021.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
