### ISSUE TITLE
 [AvoVietnam] - [React Native] - [remote] - [Part Time] 

### ISSUE THREAD

**Issue by avocadojiggles** [awesome-jobs/vietnam#3013]
## Location

* Remote

## Salary Expectation

* $16 USD/hr (363k vnd/hr) with minimum payment of $1,300 USD (22,7m vnd)

## Requirements
* 2+ years experience with RN
* Strong English skills
* Need to have access to Android and iOS devices to dev on, does not need to be the latest.
* Need to have MacBook for building project.

### Must Have

* React Native
* GraphQL
* Subscriptions
* IAP

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* updating RN app and bug fixes

### You can bring

* Fix edge cases before they come up

### Why it would be awesome to work with us

Full autonomy. Work when and where you want. Just get the work done and be honest. Please dedicate at least 10 hours per week, but I don't care if you do 10 hours in 1 day or 2 hours over 5 days. Perfect for someone that wants extra beer money.

### Interesting engineering projects

A friend is looking too hire a part-time react native dev to update an mobile RN app to latest version of RN, and fix bugs.
The app has chat, IAP, user profiles, and basic animations (tinder-like swiping).

### Contact
Send Resume/CVs, Github/Example code you've written to
dev@avodating.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
