### ISSUE TITLE
[GHN] - [Mobile Engineer] - [HCM office] - [Full Time]

### ISSUE THREAD

**Issue by TongTrangHr** [awesome-jobs/vietnam#3015]
## Location
* Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
* Fulltime

## Salary Expectation
* $800~$1500/range

## Requirements
* At least 1 years of experience as a Mobile Engineer
* Have knowledge with native code (iOS or Android) (*a big plus*)
* Good experience in React Native is prerequisite requirement or willing to change to the React Native (*required*)
* Knowledge of at least one programming language like Swift and Java(Kotlin)
* Familiarity with OOP design principles 
* Knowledge with JavaScript and strong in algorithm 
* Experience with popular React.js workflows (such as Flux or Redux)
* Have a mindset to the customer-oriented is a big plus

### You’ll be responsible for
* Collaborate with cross-functional teams to design, develop and ship new features. 
* Optimize the system for reliability and performance. 
* Fix bugs and improve the system. 
* Write unit test code to prevent similar bugs Responsibility to resolve bugs as soon as possible. 
* Provide methodology and metrics to monitor the system. 
* Improve performance, the reliability of the system. 
* Contribute knowledge to the technical team. 
* Write clean, modular, robust code to implement the desired requirements with little or no supervision 
* Contribute ideas for making the application better and easier to use

### Must Have
* React Native
* Swift or Java(Kotlin)

### Why it would be awesome to work with us
* Top 3 Logistic company in Vietnam 
* Fair team
* Annual health check-ups.
* 13th salary
* PVI Care
* Performance bonus Comfortable Private working Area for TECH team
* Sports club: Running, football, badminton
* Open communication with Senior Engineer & Technical Leader
* Challenging working environment with attractive domain as Logistics
* Specific pantry with nice decoration & Coffee/Milk Coffee/Chocolate & Tea
* Comfortable Private working Area for TECH team
* Annual Team-building + Outing trip
* Join Training Courses and Tech Sharing
* Mid-Autumn Party, Christmas party, Year-end Party
* With the delivery network cover more than 98% geographical area of Vietnam, you will be welcome anywhere in Vietnam for traveling

### How to apply
Tong Trang (Ms.)
Email: trangtq@ghn.vn
SkypeID: live:.cid.b71ee10d04a05617
Mobile: 0826256407

Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
Homepage: http://scommerce.asia/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
