### ISSUE TITLE
[GHN] - [Senior Software Engineer (Golang) ] - [HCM office] - [Full Time]

### ISSUE THREAD

**Issue by TongTrangHr** [awesome-jobs/vietnam#3017]
## Location
* Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
* Fulltime

## Salary Expectation
* $1500~$2200/range

## Requirements
* At least 4+ years of experience as Software Engineer (1 year as a senior software engineer)
* Knowledge and experience in Golang or any general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6. and be willing to change to Golang.
* Experience with two or more data systems but not limited to: Postgres, Mongodb, Elasticsearch, Redis, RabbitMQ, Kafka, Cassandra.
* Good understanding and knowledge of OOP, data structure, design patterns. 
* Familiar with Microservices, event driven architecture.
* Self-motivated to explore new technologies, applications, and environments. 
* Can work in both independent and teamwork environments.
* Experience with Front End (ReactJS or VueJS or SPA...) (*a plus*)
* Having knowledge with offline web apps, websocket, networking, caching (*a plus*)
* Have experience with Docker, K8s (*a plus*)
* Have at least 2 years working in a company (*a plus*)

### Must Have
* Golang
* Be willing to change to Golang

### You’ll be responsible for
* Optimizing components for consistency and performance across desktops, tablets, and mobiles.
* Collaborate with cross-functional teams to design, develop and ship new features. 
* Optimize the system for reliability and performance. 
* Fix bugs and improve the system. 
* Write unit test code to prevent similar bugs Responsibility to resolve bugs as soon as possible. 
* Provide methodology and metrics to monitor the system. 
* Improve performance, the reliability of the system. 
* Contribute knowledge to the technical team. 
* Review team member code.

### How to apply 
Tong Trang (Ms.)
Email: trangtq@ghn.vn
SkypeID: live:.cid.b71ee10d04a05617
Mobile: 0826256407

Level 3, Rivera Park - 7/28 Thanh Thai Street, Ward 14, District 10, HCMC
Homepage: http://scommerce.asia/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
