### ISSUE TITLE
[Y42] - Infrastructure Engineer - HCM - Fulltime

### ISSUE THREAD

**Issue by shaxbee** [awesome-jobs/vietnam#3018]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500-2800

## Requirements
* Go and/or Python
* PostgreSQL
* Kubernetes
* REST and/or GRPC
* 5+ years Software Engineering experience

### Must Have

* extensively used Go and/or Python in production projects building products and services
* ability to be hands on when needed but also have the experience to lead on technical architecture/product architecture decisions

### Ideally

* completed a Master’s/ Bachelor’s degree, preferably in an information technology field

### Responsibilities

In this role, you will be creating a scalable architecture and extend the existing system. 

You will work directly with Testers and Product Managers to ensure quality development practices are followed to create the best possible products.

You will work with a highly ambitious team that strives to build the world’s leading no-code business intelligence software and become the next European decacorn. Our tech stack: https://stackshare.io/y42/y42

### Why it would be awesome to work with us

The opportunity to significantly shape a future unicorn startup early on.

A competitive salary along with employee stock options to participate in the company’s success.

State-of-the-art work equipment, incl. MacBook Pro, Bose headphones and monitor.

Regular team events.

Flexibility to work from home or our office.

### Interesting engineering projects

Event sourcing architecture.
Developing custom Kubernetes operators and monitors.
Multi-region deployments.

### Contact
https://boards.eu.greenhouse.io/y42/jobs/4004631101

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
