### ISSUE TITLE
FunnelBeam- QA Engineer- Toan Quoc- Fulltime remote 

### ISSUE THREAD

**Issue by KhayLy** [awesome-jobs/vietnam#3019]
**𝐐𝐮𝐚𝐥𝐢𝐭𝐲 𝐀𝐬𝐬𝐮𝐫𝐚𝐧𝐜𝐞 𝐄𝐧𝐠𝐢𝐧𝐞𝐞𝐫 (𝐅𝐮𝐥𝐥𝐭𝐢𝐦𝐞)**

We are looking for a highly-skilled Quality Assurance Engineer to design, implement, deploy and maintain automated tests for our enterprise SaaS products.
Your goal will be to ensure that every release of our products meets the highest quality standards. To make that happen, you will work with the Product Manager, the developers and other QA staff during every phase of our development
cycle to design and create comprehensive, efficient and maintainable test suites. Your primary focus will be on automated User Interface testing -- but server-side testing is also part of the picture.
You will ensure tests are seamlessly integrated into our Continuous Integration tools and
processes and you will track quality assurance metrics (such as test coverage and defect
densities) for the development team and company executives.

Salary range: 1800USD - 2500USD (can be higher depending on skills and experiences)

**Responsibilities**

Your responsibilities include:
● Create detailed, comprehensive and well-structured test plans
● Design, develop and debug UI test automation scripts based on requirements
specifications and existing functionality
● Integrate test automation with Continuous Integration processes, including on GitHub,
Amazon CodeBuild
● Create, document and communicate best practices to help developers create and
maintain test scripts
● Assist developers in researching and understanding test failures
● Estimate, prioritize, plan and coordinate quality testing activities
● Work with the customer support and services teams to analyze defects and create test
cases to prevent their recurrence
Skills

**You must have:**
● 3+ years of industry experience writing efficient, scalable, reliable, modular and
maintainable test scripts for complex enterprise SaaS applications with web-based user
interfaces
● Experience writing effective and maintainable test code with Jest, Playwright or
equivalent tools for JavaScript testing
● Demonstrated ability to work productively with developers
● Experience working with Git and GitHub, including GitHub Actions
● Experience working in an Agile development environment
● Strong verbal and written communication skills in English
● Ability to diagnose and resolve problems independently, including consulting online
resources and effectively asking for help
● A strong desire to stay up to date with evolving standards, best practices and tools in
test automation
Ideally you will also have:
● Experience creating automated tests for REST APIs
● Experience creating automated tests for server side components written in Java or
Python
● Experience creating tests for Salesforce user interfaces -- ideally with Lightning Web
Components
● Experience working with Amazon CodeBuild or similar products

Q&A:
1. About the company
The company is a data intelligence and AI company, building products and technology to
help enterprise sales teams and large tech companies. We are about 10 people, looking
to bring on more backend engineers, the rest are in job description. Company exist for
about 7 years. We are a VERY stable company!
2. Working hours
- 8 hours/per day. Total: 40 hours/week, work from home and can be in Vietnam
hours.
3. Application
Please send to: dory@funnelbeam.com
Process of interview: 1-2 weeks.
Skype: Ly (live:.cid.23b00a3184b4ce6f)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by KhayLy** [comment]
Hi @lactroi, I have updated the post. Please check and hope to receive your approval soon!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
