### ISSUE TITLE
Pangara - Javascript Developer (freelancer) - Remote - PT

### ISSUE THREAD

**Issue by PangaraTeam** [awesome-jobs/vietnam#302]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Remote

## Project Background
Our client wants to strengthen their team with another Web Developer freelancer. The assignment is to work with assigned tasks from the team leader within development of their website.

The freelancer should be a thoughtful, well-rounded front end web engineer and will help build on fundamental our webpages, GUI’s and Tools. You will play a leading role in the clients web engineering practice, implementing new features, improving performance, and building beautiful user interfaces.

## Salary Expectation
* Starting from 15 USD/hour and could be negotiated depends on project requirements.

## Requirements
* You know how to write readable, idiomatic JavaScript.
* You are experienced with a variety of Web frameworks.
* You have a deep understanding of JavaScript design patterns and API design.
* You care about quality and you know what it means to ship high quality code.
* You have released at least one Web app based mostly on JavaScript.
* You have at least 2-3 years of professional experience working in JavaScript.
* Plus to have been actively working on open-source projects in the JavaScript community.
* Plus to have been working with Ruby on Rails, or simply Ruby.
* Plus to have been working with autonomous deployment systems and continuous integration (Such as Chef, TeamCity).
* Plus to have been working with Amazon Cloud Services.
* Plus to have been working with Social Media Integration in Front-End for Twitter, Facebook and Instagram.

Our client strongly believes that diversity of experience, perspectives, and background will lead to a better workplace for our employees and a better product for our users and our creators.

## Responsibilities
* Build cutting edge Web apps using primarily JavaScript and CSS3 for latest Chrome/Safari Browser
* Collaborate closely with other engineers
* Write clear, maintainable code that will scale across a number of projects and distributed development teams
* Become a valued member of an autonomous, cross- functional team

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by PangaraTeam** [comment]
@hieuk09 We just updated. Thanks for your inform.

**Comment by joneslee85** [comment]
Closed. We do not allow this freelancing model here. Thanks for your understanding.
