### ISSUE TITLE
FunnelBeam- Backend Developer- Toan quoc- Fulltime Remote

### ISSUE THREAD

**Issue by KhayLy** [awesome-jobs/vietnam#3020]
**Backend Software Engineer (Fulltime)**
We are looking for an experienced Backend Developer to play a key role in the development and maintenance of our B2B SaaS products.

1. You will take full, hands-on ownership of key modules of our product, making sure that they are robust, scalable and maintainable, and ready to support exponential growth in our customer base.
2. You should be able to develop new features from scratch, but also willing to get into existing code to add new capabilities and improve the quality. You will also assist in the deployment and management of applications on Google Cloud.
3. . This highly motivated individual needs to be independent, hands-on with code, highly technical and not afraid to get into existing code.
4. . Salary range: 2500USD - 3000USD (can be higher depending on skills and experiences)

**Responsibilities**

Your responsibilities will include:

- Actively participate in requirements analysis and design
- Implement key product features for our B2B SaaS products, primarily using Python
- Write modular, reusable, well tested code and the associated internal documentation
- Support the deployment of code to Google Cloud (GCP) and the implementation of robust management and monitoring tools to ensure maximum reliability of our services
- Work with the rest of the development team to develop and document best practices, and ensure they are followed by code reviews and knowledge sharing
- Support the QA team in creating thorough automated tests for all components
- Facilitate Continuous Deployment from our GitHub code repositories to GCP

Skills

You must have:
● A bachelor’s degree in computer science or a related study
● 4+ years of hands-on experience developing using Python with some or all of Celery,
Django, Flask, Kafka, Beautiful Soup, MongoDB
● Hands-on experience with GCP and/or AWS
● Excellent written and spoken English
● Experience working in an agile development environment using GitHub
● Ability to diagnose and resolve problems independently, including consulting online
resources and effectively asking the developer community for help
● A strong desire to stay up to date with evolving standards, best practices and tools in
cloud architecture
Ideally you will also have:
● Web scraping/crawling experience
● Experience building micro services based architectures
● Experience integrating with enterprise applications like Salesforce through REST APIs
● Knowledge of the Sales and CRM domains
● Experience with big data or related technologies

Q&A:
1. About the company
The company is a data intelligence and AI company, building products and technology to
help enterprise sales teams and large tech companies. We are about 10 people, looking
to bring on more backend engineers, the rest are in job description. Company exist for
about 7 years. We are a VERY stable company!
2. Working hours
- 8 hours/per day. Total: 40 hours/week, work from home and can be in Vietnam
hours.
3. Application

Please send to: dory@funnelbeam.com
Process of interview: 1-2 weeks.
Skype: Ly (live:.cid.23b00a3184b4ce6f)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by KhayLy** [comment]
Hi @lactroi, I have updated the post. Please check and hope to receive your approval soon!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
