### ISSUE TITLE
FunnelBeam- Front End Developer- Toan quoc- Fulltime Remote

### ISSUE THREAD

**Issue by KhayLy** [awesome-jobs/vietnam#3021]
**Responsibilities**

**Your responsibilities will include:**

- Actively participate in requirements analysis and design
- Work with the backend team, UI/UX designer and product management
- Implement key product features for our web applications using React (optionally) participate in development of Salesforce user interface (using LWC) and/or Chrome Plugins
- Write modular, reusable, well tested code and the associated internal documentation
- Support the deployment of applications to Google Cloud (GCP)
- Work with the rest of the development team to develop and document best practices, and ensure they are followed by code reviews and knowledge sharing
- Support the QA team in creating thorough automated tests for all components, including UI tests using Jest and Playwright
- Facilitate Continuous Deployment from our GitHub code repositories to GCP

**Skills**

- A bachelor’s degree in computer science or a related study 4+ years of hands-on experience developing web applications using JavaScript, including at least 2 using React
- Deep knowledge of JavaScript, HTML5 and CSS2/3
- Extensive experience handling browser quirks.
- Knowledge of JavaScript Patterns including MVC & AMD
- Good understanding of secure web development best practices
- Experience translating wireframes and prototypes into working code.
- Experience developing automated tests for JavaScript user interfaces
- Excellent written and spoken English
- Experience working in an agile development environment using GitHub
- Ability to diagnose and resolve problems independently, including consulting online resources and effectively asking the developer community for help
- A strong desire to stay up to date with evolving standards, best practices and tools in cloud architecture 

Ideally you will also have:

- Knowledge of JQuery, Bootstrap, Node.js
- Experience using Jest and Playwright
- Experience developing user interfaces for Salesforce
- Experience developing Chrome plugins
- Hands-on experience with GCP and/or AWS
- Knowledge of the Sales and CRM domains

**Q&A:

About the company**
The company is a data intelligence and AI company, building products and technology to
help enterprise sales teams and large tech companies. We are about 10 people, looking
to bring on more backend engineers, the rest are in job description. Company exist for
about 7 years. We are a VERY stable company!

**Working hours**

8 hours/per day. Total: 40 hours/week, 8 hours/day x 20 days/month. Work from home and can be in Vietnam
hours.
**Application**
Please send to: dory@funnelbeam.com
Process of interview: 1-2 weeks.
Skype: Ly (live:.cid.23b00a3184b4ce6f)

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by KhayLy** [comment]
Hi @lactroi, I have updated the post. Please check and hope to receive your approval soon

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
