### ISSUE TITLE
INSPIUS Singapore - ReactJS Developer - Hanoi/Remote - FT

### ISSUE THREAD

**Issue by inspiusrecruitment** [awesome-jobs/vietnam#3023]
## Location

* Hanoi Office: 42 Vu Ngoc Phan, Dong Da, HN
* Remote

## Salary Expectation

* Up to 35M Gross / month

## Requirements

We are looking for a **ReactJS Developer** with 2 - 3 years of experience.

### Must Have

* JavaScript
* ReactJS

### Ideally

* Familiarity with HackerRank and Algorithm

### You’ll be responsible for

* Design, build and maintain high performance, reusable and reliable JavaScript code
* Be responsible for overall feature development, define how the applications look and work
* Develop modern solutions applying industry best practices and technologies
* Identify bottlenecks & bugs, devise solutions and make improvements to these problems 
* Ensure the best possible performance, quality, and responsiveness of the applications

### You can bring

* Strong in JavaScript, thorough understanding of ReactJS and its core principles, good knowledge in HTML/CSS
* Proficiency in REACT tools including Redux, Webpack/plugins, AJAX, RESTful APIs
* Knowledge of Git, Jenkins, Algorithm and Unit Test framework like Jest/Mocha/Jasmine
* Familiarity with HackerRank is a plus
* Experience with Typescript and AWS is a plus
* Good command of English

### Why it would be awesome to work with us

* Competitive & negotiable salary
* Flexible work arrangements in office or from home
* Opportunity for work rotation to Singapore office
* Great opportunity to grow with a Product Company in a technologically advanced market
* Generous opportunities for promotion and cash rewards
* Progressive company culture, focusing on result, growth, and human development
* Opportunities to improve your English to the next level
* Annual Leaves: 12 paid-leave days, holiday leaves apply in both Vietnam & Singapore
* Working time: 9 AM – 6 PM from Monday – Friday, lunchtime 12 PM – 1.30 PM

### Contact
**Trang Nguyen**
Emaill: nguyentrang.ns@inspius.com
Telegram: https://t.me/htrang167
Homepage: https://inspius.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
