### ISSUE TITLE
Pangara - Data Scraping and Visualization (freelancer) - Remote - PT

### ISSUE THREAD

**Issue by pangarajobs** [awesome-jobs/vietnam#303]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Remote

## Project Background
We're looking for a person that can scrape information from different websites and then visualize it on the homepage

## Salary Expectation
* Starting from 15 USD/hour and could be negotiated depends on project requirements.

## Requirements
* Experience with data scraping
* Experience with visualized in a html table

## Responsibilities
The freelancer need to know about scraping, hence, gathering data from XML feeds. The data should be visualized in a html table on the clients webpage in a nice, clean way. We have own designer that will be the project manager and speaking partner - but we want the freelancer to come with ideas how the data can be presented in a nice way.

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by huydx** [comment]
@PangaraTeam can you add more information about needed language, experience, and fix the title to contain location as well. Thanks

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by joneslee85** [comment]
@PangaraTeam Is this for Pangara or for the clients of Pangara?
