### ISSUE TITLE
Away digital Group - Python Integrations Engineer - Fulltime

### ISSUE THREAD

**Issue by trungnguyen2CS** [awesome-jobs/vietnam#3034]
## Location

* Saigon, Vietnam

## Salary Expectation

* Upto $4000

## Requirements
* Python/Ruby
* AWS tools
* PostgreSQL
* 3+ years of experience
* Fluently in English

### Ideally

* Familiarity with big data systems and tools such as Spark

### Responsibilities

- Software Engineering (65% of the time) - write code, add new features, perform
maintenance, fix bugs, write tests, perform code reviews, produce technical
documentation.
- Team Assistance (15% of the time) - pair with other developers, help others solve
problems, teach others how the system works, discuss improvements in technology
and processes, work with product owners and delivery managers to scope changes
and ship projects.
- Dev Ops (10% of the time) - building and maintaining infrastructure as code,
deploying code into production, monitoring the performance of the system, assisting
upgrades.
- Support (10% of the time) - quickly respond to bugs or issues, investigate data
issues, clearly communicate with the Support or Solutions team, produce
documentation for the Solutions team to operate integrations, participate in the
regular dev first responder roster.

### You can bring

* High Standards 
* Team Player

### Why it would be awesome to work with us
•	Fast English professional pace, Great working environment
•	Joining global projects
•	Working & growing with Passionate & Talented Team
•	Diverse careers opportunities with Software Outsourcing, Software Product Development, IT Solutions & Consulting
•	Attractive Salary and Benefits
•	13th salary + yearly review
•	Yearly health-check, Premium healthcare Insurance
•	Fully paid for Social Insurance.
•	Flexible working time, Monday - Friday, support working remotely at least 1 -2 days per week.
•	Company trip, big annual year-end party every year, team building, etc.
•	Sports activities: football, table tennis, badminton, swimming…
•	Gifts for Birthday, Wedding, Mid-Autumn Fesstival, ...
•	Movie club, monthly party ...
•	Free in-house food and beverage.

### Contact
Homepage: https://awaydigitalteams.com/
TApply your CV to: trung.nguyen@awaydigitalteams.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
