### ISSUE TITLE
[Ha Noi] Glints Vietnam is looking for C# Developer (.Net, WPF/ Winforms)

### ISSUE THREAD

**Issue by huyenvu301** [awesome-jobs/vietnam#3035]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* Max $1500/ month + project bonus

## Requirements
• Bachelor's degree in computer programming, computer science or a related field
• At least 3 + years of development experience in the related field
• C#, .Net, WPF or Winform
• Visual Studio
• Relational database modeling and design (MySQL /MS SQL Server) is a plus
• Cloud Computing and CI/CD experience preferred is a plus
• Having experience with .NET Blazor is a plus
• Good knowledge of programming practices and design patterns
• Have experience or knowledge about parallel processing
• Solid understanding of object-oriented design concepts
• Follow and enforce the coding standards as established by team
• Ability to analyze and familiarize with complex systems
• Adaptable to a dynamic work environment
• Having basic English skills

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

• Develop desktop application using WPF for Traffic Engineering
• Participate and help drive the entire Development Life Cycle

### Why it would be awesome to work with us
• Attractive salary package (max $1500)• Our company is a Global Fortune 500 Preferred Vendor, so you will have an
opportunity to work with many IT Experts around Europe and USA
• Be emerged in a professional and motivating environment where you have
opportunities to express your own ideas and improve your skill set through many
interesting full-cycle projects
• Flexible working time: 9:30 A.M to 6:30 P.M, Monday to Friday, No Overtime ( Only 8
working hours)
• Performance review and appropriate gratification: twice a year
• 13th month salary + Project bonus
• Free snacks, video gaming & movie nights, team social and sport activities
• 15 leave days/year (will be added an extra day each year and maximum 20 days
for annual leave)
### Contact
Huyen Vu | Senior Recruitment Consultant | Glints Vietnam
Huyen.vu@glints.com | +84- 981 096 290 / Skype: huyenvu301

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
