### ISSUE TITLE
CH RESOURCE VIETNAM - Senior Backend Engineer (Ruby on Rails) - HCM/Fulltime

### ISSUE THREAD

**Issue by duongle2111** [awesome-jobs/vietnam#3036]
**#About Us - CH RESOURCE VIETNAM**

Founded in 2014, CH Resource Viet Nam is a market-leading platform for access to Digital Super Wallet. Headquartered in Singapore, we specialize in on-and-off ramp services for Digital Super Wallet with local currencies, and we are present in multiple countries across the Asia Pacific. Our platform was founded by Singaporean entrepreneurs, and we are backed by prominent investors from Silicon Valley such as Tim Draper, Josh Jones, as well as established venture capital firms such as Boost VC.

### You’ll be responsible for build and development of our Digital Super Wallet products.

- Full-stack developer to maintain and develop online services.
- Work closely with the product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile and web and applications. 
- Participate in user testing on product

### Requirement

* Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
* 4+ years of software development experience (with at least 2 years in Ruby on Rails).
* Good UI/UX design sense and able to develop designs in HTML/CSS/JS.
* Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS.
* Able to apply good security practices.
* Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain, etc.
* Enjoy challenging (and fun) software development work.
* Keen to communicate with the team (err on the side of over communicating).
* Language barriers aside, you must be willing to make an effort to communicate as much as Overthink security.
* Able to communicate by English.

Being an Engineer at CH Resource Vietnam, you will experience a youthful, flexible and creative work environment!

- MacBook or high-end laptop for working
- Attractive salary and annual salary review
- Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
- Extensive on job training, you will always have a chance to work with new emerging technologies.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
- 13th month salary + Performance Bonus
- PVI Health Care. 
- Enjoy diversified activities: Happy time every day, Monthly Team-building, Company trip, Play Game (PlayStation, board games), Play Sport (Football, Badminton...).

Working location: 9 Tran Nao, Dist 2, HCMC
Working time: 9AM - 6PM (Flexible + Work-from-home policy)
Salary range: Up to **3500USD** **_(can be higher depending on skills and experiences)_**
** Sign-on bonus till _31/12/2021_
Please contact me via: duong.le@ch-resource.tech
Skype: duongph2111

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
