### ISSUE TITLE
[Cốc Cốc HCM] Senior/Middle PHP Developer (Laravel)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3037]
## Location

* Saigon, Vietnam

## Salary Range

* $1500-$2000/month 

### Must Have

* 5+ years of PHP development experience
* Hands-on experience working with PHP frameworks Laravel, Slim
* Familiar with SOLID principles, design patterns, Domain Driven Design
* Experience working with container environment: docker, docker-compose, Kubernetes
* Experience working with Linux environment
* Experience with different databases. Relational (eg. PostgreSQL, MySQL) or NoSQL (eg. MongoDB, …)

### Ideally

* Experience in leading a small team is a plus
* Experience working with queue system (RabbitMQ, Kafka)
* Experience working with cache system (Redis, Memcache)
* Experience working with Nginx as proxy
* Experience with large-scale and high-traffic projects
* Extensive REST API development experience

### You’ll be responsible for

* Developing new and supporting old features for sales, platforms; search team, browser team and others;
* Searching and fixing/optimizing problems in developed products;
* Pro-actively enhance our products;
* Mentoring newcomers to grow as successful developers;
* Other tasks requested by Direct Manager.

## Why it would be awesome to work with us

* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 

## Contact
Email: hattk@coccoc.com
Careersite: https://careers.coccoc.com/job/php-software-engineer-back-end-browser

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
