### ISSUE TITLE
[Cốc Cốc HCM] Senior IOS Developer (Object-C)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3038]
## Location

* Saigon, Vietnam

## Salary Range

* $1500-$2000/month 

## Skills you should have
* At least 3-4 years experience in IOS development using Objective-C
* Will be a plus if you have experience with C++ and/or JavaScript
* Strong communication and interpersonal skills (including reading-writing in English).

### You’ll be responsible for

* Development of Cốc Cốc browser for iOS
* Optimizing performance and quality of the application
* Identify and correct bottlenecks and fix bugs
* Review and document code.

## Why it would be awesome to work with us

* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 

## Contact
Email: hattk@coccoc.com
Careersite: https://careers.coccoc.com/job/senior-software-engineer-ios

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
