### ISSUE TITLE
INSPIUS Singapore - NodeJS Developer - Hanoi/Remote - FT

### ISSUE THREAD

**Issue by inspiusrecruitment** [awesome-jobs/vietnam#3039]
## Location

* Hanoi Office: 42 Vu Ngoc Phan, Dong Da, HN
* Remote (Flexible Working Arrangement)

## Salary Expectation

* Up to 50M Gross / month

## Requirements

We are looking for a **NodeJS Developer** with 2 - 5 years of experience.

### Must Have

* JavaScript
* NodeJS
* English

### Ideally

* Familiarity with HackerRank and Algorithm / Data Structure

### You’ll be responsible for

* Design, build and maintain high performance, reusable and reliable JavaScript code
* Be responsible for overall feature development and define how the applications work
* Develop modern solutions applying industry best practices and technologies
* Identify bottlenecks & bugs, devise solutions and make improvements to these problems 
* Ensure the best possible performance, quality, and responsiveness of the applications

### You can bring

* Strong in JavaScript, proficiency in server-side programming with NodeJS and ability to design scalable solution with large dataset
* Exposure to using any Object Relational Mapping’s (ORM's) like Mongoose, Sequelize, NodeJS or NestJS
* Experience with design patterns and data structures
* Experience with SQL (MySQL preferred) / NoSQL (MongoDB preferred) databases
* Knowledge of Git, Jenkins, Unit Test, Algorithm and the code flow from FE to BE to DB
* Experience with Typescript and AWS (serverless, cognito, etc.) is a plus
* Good command of English

### Why it would be awesome to work with us

* Competitive & negotiable salary
* Flexible work arrangements in office or from home
* Opportunity for work rotation to Singapore office
* Great opportunity to grow with a Product Company in a technologically advanced market
* Generous opportunities for promotion and cash rewards
* Progressive company culture, focusing on result, growth, and human development
* Opportunities to improve your English to the next level
* Annual Leaves: 12 paid-leave days, holiday leaves apply in both Vietnam & Singapore
* Working time: 9 AM – 6 PM from Monday – Friday, lunchtime 12 PM – 1.30 PM

### Contact
**Trang Nguyen**
Emaill: nguyentrang.ns@inspius.com
Telegram: https://t.me/htrang167
Homepage: https://inspius.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
