### ISSUE TITLE
INSPIUS Singapore - Java Developer - Hanoi/Remote - FT

### ISSUE THREAD

**Issue by inspiusrecruitment** [awesome-jobs/vietnam#3040]
## Location

* Hanoi Office: 42 Vu Ngoc Phan, Dong Da, HN
* Remote (Flexible Working Arrangement)

## Salary Expectation

* Up to 35M Gross / month

## Requirements

We are looking for a **Java Developer** with 2 - 3 years of experience.

### Must Have

* Java
* English

### Ideally

* Familiarity with HackerRank and Algorithm / Data Structure

### You’ll be responsible for

* Write elegant, semantic and easily maintainable code
* Champion product development by coordinating requirements, schedules, activities, contributing to team meetings, troubleshooting development and production problems across multiple environments and operating platforms
* Complete/oversee the product development and quality assurance efforts
* Work with Product Manager to create and maintain a robust framework to support existing products.
* Work with peer developers to review technical implementation and identifying areas of improvement
* Ensure best practices are well documented, up-to-date and adhered to on a day-to-day basis

### You can bring

* Strong Java / Groovy abilities, good understanding of MySQL, Hibernate, RESTful services and ORMs
* Ability to write good unit tests, pay attention to application quality and ease of use
* Comfortable in using Git for version control, ticketing systems, and other supplementary tools
* Understanding of Algorithm, HTML, CSS and JavaScript
* An aptitude for learning and having lots of fun
* Good command of English

### Why it would be awesome to work with us

* Competitive & negotiable salary
* Flexible work arrangements in office or from home
* Opportunity for work rotation to Singapore office
* Great opportunity to grow with a Product Company in a technologically advanced market
* Generous opportunities for promotion and cash rewards
* Progressive company culture, focusing on result, growth, and human development
* Opportunities to improve your English to the next level
* Annual Leaves: 12 paid-leave days, holiday leaves apply in both Vietnam & Singapore
* Working time: 9 AM – 6 PM from Monday – Friday, lunchtime 12 PM – 1.30 PM

### Contact
**Trang Nguyen**
Emaill: nguyentrang.ns@inspius.com
Telegram: https://t.me/htrang167
Homepage: https://inspius.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
