### ISSUE TITLE
[Cốc Cốc HCM] Test Engineer (Manual)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3041]
## Location

* Saigon, Vietnam

## Salary Range

* $1000-$1500/month 

## Skills you should have
* Experience with manual testing, testing techniques and testing methodologies: cross-browser and cross platform
* Have experience in testing mobile application is required
* Have experience in working with various of devices: iOS devices, Android devices
* Experience in testing API, performance using Postman/SOAP UI is plus
* Have knowledge on database such as database schema and simple SQL query and familiar with entity relationship diagrams and the SQL queries is plus
* Good understanding of software development life cycle & common using software development process as Agile
* Experience in management tools such as JIRA, Confluence, testing tool

### You’ll be responsible for

* Plan and execute tests against software and hardware products using a variety of manual techniques and automated tools to ensure requirements are met
* Interact with team members and other groups to ensure all requirements have been tested, defects have been documented, and quality issues identified during the testing process have been resolved
* Create and maintain test documentation such as test cases, defect reports and test result summaries
* Communicate product and process information to other members of the team, other departments, and customers as necessary
* Monitor and coach junior Test Engineer to work in the projects

## Why it would be awesome to work with us

* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 

## Contact
Email: hattk@coccoc.com
Careersite: https://careers.coccoc.com/job/test-engineer

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
