### ISSUE TITLE
🎯 [HN, Vietnam] Fullstack Engineer (Python/Angular)

### ISSUE THREAD

**Issue by vivuvove** [awesome-jobs/vietnam#3045]
Location: Hanoi, Vietnam

**Salary: 600,000,000VND - 700,000,000VND /year**

### 
![MicrosoftTeams-image copy](https://user-images.githubusercontent.com/93895676/141248269-eb624dbd-45a0-4266-8adb-df5789f7d544.png)
Requirements
- Modern web application development using ReactJS (or Vue). Familiar with basic concepts and advanced concepts about React (required). Deep understanding of Web application development. Able to take UI design and turn into a complete feature without much supervise.  
- Have a general understanding of source control, build system, CI/CD, unit testing 
- Have experience using Python & Flask to write RESTful API 
- Have experience with MySQL and Redis 
- Strive to write clean, maintainable code, consistently follow convention. 
##Optional:  
- GraphQL / Apollo client / Apollo server. Server-side rendering 
- Jest, Cypress  
- Application monitoring (NewRelic / Elasticsearch APM) & DevOps: Kubernetes / Docker 
- General understanding about code effectiveness: clean code, design patterns, algorithm, etc.  
- General understanding about Architecture: architecture characteristics (non-function requirements), architecture styles, etc. Cloud architecture and certifications 
- Able to code refactor with confidence. Have experience in reviewing code for other developers. 
- NodeJS and Express. NodeJS ecosystem. Understand basic concept and optimization for NodeJS 

### Skills
*Prerequisites: 
- Accept feedback graciously and able to learn from past mistakes 
- Communicate status of work effectively to the team 
- Collaboration and work in-person with other team members 
- Able to work independently and know when to ask for help to get stuff done 
- Able to perform deep work and focus on task. Enjoy coding and solving problems. Try your best to complete the task with minimal support from supervisor. But know how to pull other people when requires 
* Optional: 
- Have understanding and experience with Scrum / Agile concept 
- Project management skills and task priotization 
- Presentation skills 
- Familiar with OKR management methodology 

## Business Expertise
*Prerequisites: 
- None 
* Optional:
- Have general understanding of how Cloud works. Have experience working with cloud platforms (AWS / GCP / Digital Ocean / Linode) 

### Responsibilities
- Collaborate with other team members to develop new features (coding, write unit testing, write integration testing, end-to-end testing, review code and deployment - DevOps) according to Scrum guide 
- Collaborate with other team members to support and maintain existing systems, verify bugs and fix issues. Monitor the health and SLA of the overall systems and mitigate / escalate if need be.  
- Work with team lead / architect to contribute to overall architect and design of the application. 
- Regularly update documentation to reflect the latest state of the system (in term of both functional and logical) 
- Heavily discuss with other team members regards to architect and implementation to solve problem. Communicate status of tasks with peers and line manager 
- Participate in community group’s activities to research new technology, sharing knowledge between teams 
- Participate in 1-1 review with team leader / line manager for progress reporting and feedback and career development 
- Contribute to team documents including (technical documents, detailed design documents, process-related documents, onboarding documents...) 
*** Report to: 
- Team leader for daily works and supports, career path and development 
- Team size: 5 people (1 Manager, 1 Product Owner, 1 Scrum master, 2 Full stack engineer full time, 1 Full-stack engineer part time) 

### Contact
Mr. Viet Anh - (+84)989613311
Email: ViVTK2@fpt.com.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
