### ISSUE TITLE
[JobSeekervn] Blockchain Developer - Ho Chi Minh

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3046]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $1800 - $2500/month 

## Requirements
* Knowledge of blockchain and smart contracts concepts (especially Ethereum, BSC, NFT), with at least 1 year of experience in developing and deploying production code to mainnet.
* At least 3 years of experience in front end & back-end languages (ReactJS & NodeJS preferred)
* Strong cryptography knowledge
* Experience working with system design, architecture, infra system; the popular framework for the respective development environment; source version control (Git/Github preferred).
* Maintain a good coding standard, familiar with Test Driven Development.

### Responsibilities
* Research, design, develop, and test blockchain technologies that could be utilized in EcoSystem.
* Analyze, brainstorm and evaluate applications of newly emerged tools and technology.
* Maintain and extend the current platform, responsible both for the blockchain smart contract and the integration to the client & server-side application.
* Document new solutions and maintain the existing one.
* And perform similar duties as he deems fit for the proper execution of his duties and duties as delegated by the direct manager or the Employer.

### Why it would be awesome to work with us
* Interesting project with friendly colleagues
* 13th-month salary + annual health checks + health insurance 
* 15 days vacation leave
* Laptop provided 

### Contact
Email: nhiha@jobseeker.vn 
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
