### ISSUE TITLE
Fullstack Developer

### ISSUE THREAD

**Issue by HoangYen309** [awesome-jobs/vietnam#3047]
## Location

* Ha Noi, Vietnam
* Can Remote

## Salary Expectation

* $2500/month or range

## Requirements
Background in Computer Science/ Information Technology or equivalent.
Experience in Javascript or Typescript
Backend service experience in Nodejs and frameworks like Expressjs or Fastify
Experience with JavaScript and modern frameworks like React or Vue
Experience in building Restful APIs
Experience in using Git
Good level in English skills: written and spoken

## Skills
Frontend (ReactJS/VueJS/AngularJS) + NodeJS

### Prefer:

* Experience designing and delivering high-availability, scalable cloud-based systems
* Experience working in state management like Vuex or Redux
* Experience working with SQL or NoSQL datastores
* Good Linux/Unix experience
* Experience in automated testing
* Knowledge of modern development tools, like Docker, Webpack, etc.
* Be able to dodge bullet

### Responsibilities

Write high-quality, clean, maintainable, reusable code using engineering best practices.
Analyze requirements, design, and develop features.
Understand the product, constantly optimize the product, identify and fix problems, improve stability and user experience.
Collaborate with fellow developers, product managers, user experience designers, and operation engineers to build products with web technologies.
Optimize application for maximum performance and scalability.
Participate in regular internal technology sharing and other regional tech events.

### Why it would be awesome to work with us

Work in an international team with high skilled people
Correct work/life balance
Annual company trip, other exciting activities for team building
Working 5 days/week , from Monday to Friday
Lunch allowance, 13th month salary, competitive salary
Annual health checkups and other benefits based on labor law
Participate to Open Source communities and conferences in Vietnam
Modern working space, free coffee

### Contact
Website: https://linagora.vn/vi/
Email: tyhoang@linagora.com
Mobile number: 0372019465

**Comment by HoangYen309** [comment]
14 phép/năm. Ib để nhận hỗ trợ chi tiết hơn

**Comment by HoangYen309** [comment]
có tuyển cả vị trí FE (Vuejs/AngularJs/Reactjs) từ 2 năm kinh nghiệm

**Comment by HoangYen309** [comment]
Vẫn tuyển nha các bác, có Signing bonus

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
