### ISSUE TITLE
Grand M.VN - iOS - Nhatrang - FT

### ISSUE THREAD

**Issue by grandmvn** [awesome-jobs/vietnam#3053]
## Location
NhaTrang, Vietnam

## Salary Expectation
Negotiation (based on skills and experience)

## Requirements
* Proficient with Swift, Objective-C 
* Good at using Git and X-Code 
* Having knowledge of REST API, Big data and search engine is an advantage
* 01+ years Software Engineering experience

## Why it would be awesome to work with us
Benefits
* Bonus
* Social Insurance, Health Insurance, Unemployment Insurance and Other benefits as Vietnamese Labor code
* Open and respect working environment
* Support to grow and develop
Working 5 days/week, from Monday to Friday

### Contact
Website: https://grandm.vn/
Contact: email contactus@grandm.vn, mobile phone 039 208 5174

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
