### ISSUE TITLE
JobHopin's Client - Blockchain Developer (Ethereum) - REMOTE - FT

### ISSUE THREAD

**Issue by thonguyen2501** [awesome-jobs/vietnam#3054]
**Location: REMOTE**

**Description**

- Design, develop, test, deploy, document, maintain, automate, and improve software applications.
- Identifying areas for modification in existing programs and subsequently developing these modifications.
- Writing and implementing efficient code and tests.
- Collaborate with teams in other divisions.

**Requirement**

- English– both written and verbal. The ability to communicate complex procedures to other colleagues.
- Bachelor’s degree in Computer Science, or Software Engineering, or similar field.
- 1-5 years of experience developing Blockchain technologies.
- Excellent working attitude, critical thinking skills, passion for coding and solving challenging problems.
- Strong understanding of software development life cycles, fundamental algorithms, data structures, OOP, RESTFul API, programming languages such as Java and Python.
- Familiarity with common software development tools such as Git/Github, Docker, Node, UNIX, VSCode.
- Familiar with Ethereum blockchain and other cutting-edge cryptocurrency platforms
- Ample experience working in back-end development, data structures, and algorithms
- Extensive experience in blockchain management, web development, and data protection
- Excellent working attitude, critical thinking skills, passion for coding and solving challenging problems.

**Benefits**

- Salary up to $3000
- Insurance full salary
- Others benefit

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
