### ISSUE TITLE
KILO - Senior Full-stack Engineer - Saigon/Remote - FT

### ISSUE THREAD

**Issue by tranngo161** [awesome-jobs/vietnam#3055]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* 3,000 - 5,000 USD Gross

## Who we are

Kilo is a technology start-up in Vietnam. Our customers are primarily small and medium-sized retailers and  distributors. 
Our mission is to shift the B2B2C ecosystem with a mission to empower retailers. This is done by  democratizing access to the best pricing, assortment, and inventory management. We are building the next  generation retail platform by bridging the gap between traditional distribution channels with robust software  systems 
Kilo was founded on the principle that technology can affect change in traditional and deeply entrenched  sectors such as offline retail stores. Our sales and technology platform is one-a-kind specifically built to  address retailer and brand pain points and solve them at scale.

## Requirements

- 3+ years of experience as a full-stack engineer & being able to work on both front-end and back-end side
- Familiar with building web services & web application using NodeJS, Typescript, ReactJS (or similar technologies / languages like Python or Java)
- Familiar with *nix (Mac OS X, Ubuntu, CentOS, etc.) based development and execution environments
- Familiar with the RDBMS (e.g. Postgres, MySQL …)
- Good problem solving skill (we pay more attention to your mindset, not the programming languages you know)
- Being a good team player who can cooperate with others and also able to work independently in the daily work
- Being able to communicate in English

### Nice-to-have

- Knowledge about AWS or devops task (manage the AWS infrastructure using terraform or similar tool)
- Experience with application design
- Experience with building scalable application to deal with high web traffic
- Experience with common methods for securing the connections in distributed environment

## You’ll be responsible for

At Kilo, we care deeply about our team and we are obsessed with crafting a fun, productive, collaborative,  diverse, friendly environment that can enable everyone to do the best work of their careers, and have the best  time doing it. 
After a lot of hard work over the last year, we are ready to expand our product lines and thoughtfully grow the  team! We are hiring passionate, collaborative, customer-driven engineers who share our belief that modern  business software can be fast, fluid, beautiful, and even joyful to use.  
We leverage iterative, test-driven development and continuous integration to reliably deliver value to customers  and we prioritize a high-ownership, low-overhead approach to software development, where you'll be expected  to build, launch, and operate product features end-to-end.
Our current tech stack

- ReactJs, React native, JavaScript/TypeScript, NodeJS
- Postgres
- AWS, Terraform

## Why it would be awesome to work with us

- Sign-on Bonus is applied for this position, onboard with us from now to Jan 2022 to be eligible (only apply to candidates who are under an official contract with another company).
- Macbook & external monitor are provided
- Impressive salary package and annual salary review
- 13th month salary and discretionary bonus
- 100% salary on your probation period
- 18 days of annual leave
- Full social insurance and Healthcare Insurance (for you and your family member)
- Flexible working hours with hybrid working policy (remote & office)
- Be a part of core tech team and part of one of the first companies starts in Vietnam and will expand regionally across Asia
- Chance to build a new product from scratch with international development team
- You are always welcome to contribute your ideas to Kilo's vision, technology and implementation
- Flat and supportive working environment
- Modern office with the flexible relaxing zone based in District 1, Ho Chi Minh City
- Free bike parking, fruits and coffee, happy hours weekly

## Contact
Homepage: https://kilo.vn/
More details: https://techcrunch.com/2021/11/14/vietnamese-b2b-e-commerce-platform-kilo-bags-5m-pre-series-a/
Please contact us for more information: Ms. Tran - Head of HR and Recruiting
Email: tran.ngo@kilo.vn
Mobile phone: +84 90 1091 161

**Comment by tranngo161** [comment]
We are also looking for QA Engineer, Product Owner, UI/UX Designer and high level in Engineering Team, please kindly let me know if you need more details.
Regards,

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
