### ISSUE TITLE
Fetch - Fullstack Developer (React JS, Node JS) - HCM/HN - FT

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#3057]
![Group 219789](https://user-images.githubusercontent.com/60914247/141958345-e45bd902-11dc-4568-a1dd-b621e4af1399.jpg)

# HCM/HN
# 1,500 - 2,700 USD

## INTRODUCTION

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily in the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About client**

They are made up of experienced professionals who are committed to building a meaningful marketplace service for NFTs. They're a dynamic, agile, and gritty team that only has one goal in mind: make it the best place on the internet to mint anything!

## RESPONSIBILITIES
Are you ready to join the team? We're hiring an experienced Full Stack Software Engineer with exceptional programming skills as our team is expanding rapidly. Reporting to the CEO/CTO, you will be a key member of the Tech team where you will handle front-end and application logic development. This role will contribute enormously to the success of the Tech Team and is an excellent opportunity to join an exciting industry with other focused, talented professionals. Working in collaboration with CEO/CTO and Tech Team, you will: 

- Work across the full stack, alongside a multi-disciplinary team including front-end engineers, UX/UI designers, product managers and CTO to build highly scalable solutions that enable positive user experience and measurable business growth.  
- Develop new features and infrastructure development in support of rapidly emerging business and project requirements. 
- Actively participate in all aspects of agile software development including design, implementation and deployment, adhering to best practices and pursing continued learning opportunities.
- Strike a balance between functional and aesthetic design.
- Maintain brand consistency throughout the design and build reusable code for future use.  
- Keep abreast of latest and emerging technologies in the blockchain and technology space. 

## REQUIREMENT
To succeed in this role, we'll love for you to have: 

- Interest or experience in NFTs and blockchain. 
- 2 years of experience managing and scaling AWS applications is a must.
- At least 2 years experience with at least two of the following programming languages/libraries:
- Reactjs 
- Redux 
- Typescript 
- CSS 
- Webpack 
- Node.js 
- Experience working on fullstack development and running a large production environment/application. 
- Strong communication skills to work collaborative together with the team.
- A passion for learning as everyday's a new opportunity to grow and develop your skills.

## WHY YOU‘LL LOVE WORKING HERE
Being a Full Stack Engineer (NFTs, Crypto, Blockchain) at Fetch Technology, you will experience a youthful, flexible and creative work environment:

- Attractive salary and annual salary review.
- Working in a professional, friendly, well-equipped environment both with seniors, foreigners and Vietnamese.
- With extensive on job training, you will always have a chance to work with new emerging technologies.
- Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
- 12-day annual leave per year.
- 13th month salary.
- Premium Health Care.
- Opportunity to be part of the pioneer team of a fast-growing start-up making an impact on the mobility landscape in Vietnam.
- A platform to develop your career through working closely with senior executives and managers in the organization.
- A fulfilling role with lots of learning opportunities in a fun and highly motivating working environment.
- Enjoy diversified activities: Free snack, Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...). 

## WORKING HOURS & LOCATION

- Working hours: From 9 AM - 6 PM, Monday to Friday.
- Location: 

HCM: 3rd Floor, BCONS TOWER 2 - No.42/1, Ung Van Khiem Street, Ward 25, Binh Thanh District, HCMC. 

HN: 3rd Floor, Dai Phat Building - Lane 82, Duy Tan Street, Dich Vong Hau Ward, Cau Giay District, Hanoi. 

## CONTACT:

- Mail: trangdong@fetch.tech
- Skype: trangdong0111@gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
