### ISSUE TITLE
CXP - Smart Contract Solidity (Blockchain) - HCM - Fulltime

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3061]
## Location
* Orchard View Apartment, 132 Hồng Hà, Phú Nhuận District, HCMC, Vietnam
* Currently working online 100% due to Covid-19

## Salary Expectation
* Up to $2,500

### What you’ll work on
* Build new DeFi products according to assigned requirements.
* Instruct other members on blockchain and solidity.
* Research and capture new DeFi technologies, propose ideas...
* Analytics tools to help senior management make data-led business decisions.
* Improving our platform’s security and resilience.

### Our tech stack
* Backend: Solidity, Golang
* Blockchain integrations: Ethereum, BSC, TRON,..

## Requirements
* A good understanding of how to write clean, efficient, well tested code.
* Experience implementing complex math in Solidity
* A deep understanding of the Ethereum Virtual Machine
* A deep knowledge blockchain layers, blockchain scaling solutions 
* Knowledge of DeFi, AMM, Liquidity Pool, Yield Farming, Staking, Liquidity Pool,..
* A keenness to learn and to work in a highly collaborative environment.
* Strong communication and problem-solving skills.
* Experience in financial systems, especially payment domain, is great bonus.

## Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* Annual company trip
* 13th salary bonus

## Why it would be awesome to work with us
* We are a young, lean, and strong team 
* We build a professional & fun working environment.

## About Us
CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
Ms. Jade | hr@cxptek.com
Phone: +84772997820 (Zalo)

**Comment by realsbd** [comment]
I will love to be part of your team if there is still an open position

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
