### ISSUE TITLE
Money Forward Vietnam - Technical Architect (Golang, RoR or Java) - HCMC - FT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#3063]
## Location
* D4, Saigon, Vietnam
* Currently working remotely 100% due to Covid 19

## Salary Expectation
* $3000 - $5000
* **Sign-on bonus 1 month salary gross**
* **No Probation AT ALL**
* **You can choose to onboard now or after Tet**

## Requirements
* 10+ year experience in web development with 3+ year experience of leadership

### Must Have
* Broad knowledge of different programming languages and strong expertise in at least one of Ruby, Go, Java, JavaScript
* Good understanding of common architectural patterns and design patterns in software engineering
* Hands-on experience of architecting and developing secured, high performance, high availability, scalable software systems
* Solid experience of databases (MySQL, PostgreSQL, NoSQL) including performance tuning and optimization
* Experience with application performance monitoring and error tracking systems
* Extensive knowledge of web security
* Familiarity with CI/CD, Docker, Kubernetes
* Experience of defining and rolling out company-wide technical standards
* Experience of training middle/senior developers
* Good English communication skills

### Ideally
* DevOps experience with on-premises or cloud computing (AWS, GCP, Azure)
* Experience of working as a Technical Architect, Solution Architect or similar roles
* Experience of leading/organizing technical events such as tech seminar, coding contest, hackathon
* Good knowledge of the clean architecture pattern

### Responsibilities
* Build a strong development team with high-level development skills
* Develop company-wide standards for development processes, system design and implementation methodologies
* Provide consultation about technical solutions and lead the development in one or several projects
* Perform regular review of technical implementation and give suggestions to improve product quality
* Troubleshoot and plan countermeasures of performance, security and reliability issues
* Coach and mentor middle/senior developers

### You’ll be responsible for
* Building a financial platform for ALL

### Why it would be awesome to work with us
* Sign-on bonus 1 month salary
* No probation applied for technical positions (all levels)
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009
Phone: 0906 516 291 (Zalo/Whatsapp)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
