### ISSUE TITLE
NextPay - Devops Engineer - HN - FT

### ISSUE THREAD

**Issue by Lenguyen12111995** [awesome-jobs/vietnam#3066]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1800/month or range

## Requirements
**Qualifications**
* Bachelor's degree in a related field or a combination of education and relevant experience
* 2+ years of Linux system administration experience
 
**Knowledge, Skills and Abilities:**
* Experience in managing Linux system
* Strong experience in administration of database system: MongoDB, MariaDB, MySQL
* Experience using Docker, Kubernetes is a must
* Experience building CI/CD pipeline, monitoring, logging, alerting system
* Experience with public cloud provider is a plus: AWS, GCP, Azure, DO
* Experience working in fintech & Payment gateway company is a plus
* Experience using any high level programming language: Python, Golang, Java,…
* Experience in systems design, implementation, and analysis is an advantage.

### Why it would be awesome to work with us
* Attractive starting salary, competitive, commensurate with capacity and working experience
* Approved for salary increase 2 times/year & 13th month salary
* Project bonus
* Opportunities for training and good promotion at work. Clear career development roadmap
* Enjoy benefits and regimes as prescribed by law (Holidays, social insurance, health insurance...)
* Bonuses for holidays, New Year, birthdays, annual travel, teambuilding
* Working in a young and dynamic environment
* 12 paid days off/ year.

### Contact
Homepage: nextpay.vn; nexttech.asia
Email: lent@peacesoft.net
SK-nguyenle_hattieu
Linkedin: https://www.linkedin.com/in/lệ-nguyễn-296934150/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
