### ISSUE TITLE
HAHALOLO - JUNIOR/SENIOR JAVA DEVELOPER - FULLTIME

### ISSUE THREAD

**Issue by HAHALOLO-Recruiter** [awesome-jobs/vietnam#3068]
**## Location**
* Saigon / Hue / Can Tho, Vietnam
* Junior/Senior

**## Salary Expectation**
* $700-1900/month or higher basing on your real ability (negotiable)

**## Requirements / Yêu cầu**
* Java (Java, J2EE, Hibernate, Spring Framework) and OOP / _lập trình với các công nghệ Java (Java, J2EE, Hibernate, Spring Framework) và OOP_ 
* Web-based using Spring Framework / _phát triển ứng dụng Web-based dựa trên Spring Framework_
* Spring MVC (Restful), Web services integration 
* Build / deploy: Maven, Jenskins / _Biết sử dụng công cụ phát triển build / deploy: Maven, Jenskins_
* MongoDB / _Có kiến thức về cơ sở dữ liệu: MongoDB_
* Database design and model / _thiết kế Mẫu và mô hình hóa dữ liệu_
* Networking is a plus / _Có kinh nghiệm với Networking là một lợi thế_

**### Must Have**
* 2+ years Software Engineering experience / _từ 2 năm kinh nghiệm trở lên_

**### Why it would be awesome to work with us**
* Dynamic working environment, friendly, promotion opportunities 
* KPI bonus.
* Annual salary review
* Performance Bonus
* Birthday Party monthly
* Teambuilding

**### Contact**
Homepage: https://www.hahalolo.com/
https://tuyendung.hahalolo.com/category/tuyen-dung-tphcm/
Email: tuyendung@hahalolo.com 

### Address:
TPHCM: HAHALOLO building, 400/8B Ung Van Khiem street, Ward 25, Binh Thanh District, Vietnam
Hue City: Floor 06, 02 Le Quy Don Street, Phu Hoi Ward, Hue City, Vietnam

![03](https://user-images.githubusercontent.com/94172846/142827598-424a1259-7ebf-49f0-92b1-8abe0a1073a4.jpg)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
