### ISSUE TITLE
HAHALOLO - JUNIOR/SENIOR JAVA DEVELOPER - FULLTIME

### ISSUE THREAD

**Issue by HAHALOLO-Recruiter** [awesome-jobs/vietnam#3069]
**## Location**
•	Saigon / Hue / Can Tho, Vietnam
•	Junior/Senior

**## Salary Expectation**
•	$700-1900/month or higher basing on your real ability (negotiable)

**## Requirements** 
•	Java (Java, J2EE, Hibernate, Spring Framework) and OOP 
•	Web-based using Spring Framework 
•	Spring MVC (Restful), Web services integration
•	Build / deploy: Maven, Jenskins 
•	MongoDB 
•	Database design and model 
•	Networking is a plus 

**### Must Have**
•	2+ years Software Engineering experience

**### Why it would be awesome to work with us**
•	Dynamic working environment, friendly, promotion opportunities
•	KPI bonus.
•	Annual salary review
•	Performance Bonus
•	Birthday Party monthly
•	Teambuilding

**### Contact**
Homepage: https://www.hahalolo.com/
https://tuyendung.hahalolo.com/category/tuyen-dung-tphcm/
Email: tuyendung@hahalolo.com

**###Address:**
Ho Chi Minh city: HAHALOLO building, 400/8B Ung Van Khiem street, Ward 25, Binh Thanh District, Vietnam
Hue city: Floor 06, 02 Le Quy Don Street, Phu Hoi Ward, Hue City, Vietnam

![03](https://user-images.githubusercontent.com/94172846/142827775-45eb3ff5-caf3-4c61-95f2-24e3a876d432.jpg)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
