### ISSUE TITLE
HaHaLoLo - Junior/Senior Java Developer - FT

### ISSUE THREAD

**Issue by HAHALOLO-Recruiter** [awesome-jobs/vietnam#3072]
## Location
• Saigon / Hue / Can Tho, Vietnam
• Junior/Senior

## Salary Expectation
• $700-1900/month or higher basing on your real ability (negotiable)

## Requirements
• Java (Java, J2EE, Hibernate, Spring Framework) and OOP
• Web-based using Spring Framework
• Spring MVC (Restful), Web services integration
• Build / deploy: Maven, Jenskins
• MongoDB
• Database design and model
• Networking is a plus

### Must Have
• 2+ years Software Engineering experience

### Why it would be awesome to work with us
• Dynamic working environment, friendly, promotion opportunities
• KPI bonus.
• Annual salary review
• Performance Bonus
• Birthday Party monthly
• Teambuilding

### Contact
Homepage: https://www.hahalolo.com/
https://tuyendung.hahalolo.com/category/tuyen-dung-tphcm/
Email: tuyendung@hahalolo.com
Ho Chi Minh city: HAHALOLO building, 400/8B Ung Van Khiem street, Ward 25, Binh Thanh District, Vietnam
Hue city: Floor 06, 02 Le Quy Don Street, Phu Hoi Ward, Hue City, Vietnam

![03](https://user-images.githubusercontent.com/94172846/142834729-fb19497f-e09f-4323-8f61-53a9557d7d5d.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
