### ISSUE TITLE
Treasure Gate Pte Ltd - Project Manager - HCM - FT

### ISSUE THREAD

**Issue by nmhung** [awesome-jobs/vietnam#3076]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500 - $2000

## Requirements
* 5+ years of proven experience in software product management with a focus on Crypto / Blockchain.
* Degree in Computer Science or related field
* Digital customer payments development experience
* Must be enthusiastic about cryptocurrency
* Experience in using Jira/Trello to manage the project.
* Strong knowledge of software development lifecycle
* Experience working in Agile engineering environment
* Excellent English communication skills, both written and verbal

### Responsibilities
* Develop, execute and oversee NFT product roadmap
* Define and align the work for software development teams to meet deadlines
* Create transaction flows and user experience flows in the development and guidance of IT and Operations
* Work cross-functionally with Digital Marketing Team
* Develop and manage product financials
* Provide feedback, advice, project updates and encouragement to team members
* Manage deadlines and push the team to ensure timeliness

### You’ll be responsible for

* We are looking for a passionate and experienced NFT Product Manager who can oversee the project, create a roadmap and manage the development process.

### Why it would be awesome to work with us

* Competitive salary range with annual bonus quarterly based on work performance & achievements.
* 26 paid leaves per year (18 days annual leaves + 8 sick leaves)
* Opportunities to work on world-class, innovative products and cutting-edge technologies

### Contact
Ken Nguyen
Email: ken@ar7.io
Mobile: 0358800023

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
