### ISSUE TITLE
[REMOTE/HN] - Junior/Senior UI Developer - FT

### ISSUE THREAD

**Issue by datnguyen-expert** [awesome-jobs/vietnam#3078]
## Location
* Remote

## Salary Expectation
* Negotiable

## Requirements
* HTML5
* CSS3
* CSS
* VueJS
* Adobe Photoshop

## Skills
- Proficient understanding of web markup, including HTML5, CSS3
- Basic understanding of server-side CSS pre-processing platforms, such as LESS and SASS
- Proficient understanding of client-side scripting and JavaScript frameworks VueJS, including jQuery
- Strong Hands on Experience in Bootstrap framework
- Good understanding of Responsive web framework VueJS.
- Good understanding of asynchronous request handling, partial page updates, and AJAX
- Basic knowledge of image authoring tools, to be able to crop, resize, or perform small adjustments on an image. Familiarity with tools such as Invision or Photoshop is a plus.
- Basic knowledge of JAVA and frameworks like Spring, Tiles, Freemarker, Hibernate is added advantage
- Proficient understanding of cross-browser compatibility issues and ways to work around them.
- Proficient understanding of code versioning tools, such as GIT and development tools like Eclipse.
- Good understanding of SEO principles and ensuring that application will adhere to them.

### You’ll be responsible for
- Develop new user-facing features and modify the existing pages as per the designer’s prototype
- Build reusable code and libraries for future use
- Ensure the technical feasibility of UI/UX designs
- Optimize application for maximum speed and scalability
- Assure that all user input is validated before submitting to back-end application based on the Business Rules and requirement
- Collaborate with other team members and stakeholders
- Develop/Modify the UI without breaking the existing functionalities
- Ensure proper testing has been done before pushing the changes to staging environments

### Why it would be awesome to work with us
- Great culture of transparency and openness
- High salary for high performance
- Five working days/week
- Awesome friendly team
- Remotely working from home is available
- Working on a complex software engineering project
- Be a part of core tech team and part of one of the first companies starts in Vietnam and will expand regionally across Asia
- Flat and supportive working environment
- Trust and freedom to work on the product
- Continuous learning environment
- Supportive and highly skilled coworkers

It’s a permanent position working on a complex software engineering project. We are committed to staying up to date with technology, and openly encourage cross-functionality within teams. Your passion for growth will be matched by ours.

We have been growing rapidly over the last few years and have no intention of slowing down, so there will be loads of opportunities as we continue to dominate the market and in select international markets.

The business has ambitious growth plans, and will support you to expand your skill set and tackle new challenges.

### Contact
Email: datnguyen.expert@outlook.com
Skype: dat.cbdo@gmail.com
Mobile phone: +84 96 699 2048

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
