### ISSUE TITLE
[REMOTE/HN] - Java Senior Developer/Technical Lead - FT

### ISSUE THREAD

**Issue by datnguyen-expert** [awesome-jobs/vietnam#3079]
## Location
- Remote

## Salary Expectation
- Negotiable

## Requirements
- Java
- JavaScript
- VueJS
- jQuery

## Skills
- Proficient in Java, with a good knowledge of its ecosystems
- Solid understanding of object-oriented programming
- Familiar with various design and architectural patterns
- Familiarity with concepts of MVC, JDBC, and RESTful
- Experience with popular web application frameworks, such as Spring Boot
- Experience with popular data processing frameworks like Apache Spark/Flink
- Familiarity with UI frameworks like Vue or React
- Experience with CSS would be preferred
- Knack for writing clean, readable code
- Excellent knowledge of Relational Databases, SQL and ORM technologies (JPA, Hibernate)
- Understanding fundamental design principles behind a scalable application
- Creating database schemas that represent and support business processes
- Profound insight of Java and JEE internals (Classloading, Memory Management, Transaction management etc)
- Basic understanding of JVM, its limitations, weaknesses, and workarounds
- Implementing automated testing platforms and unit tests
- Ability to gather accurate requirements and work closely with stakeholders to prioritize tasks and the scope of development.
- Proficient understanding of code versioning tools, such as Git
- Familiarity with build tools such as Ant, Maven, and Gradle
- Familiarity with continuous integration

### You’ll be responsible for
- Translate application storyboards and use cases into functional applications
- Design, build, and maintain efficient, reusable, and reliable Java and JS code
- Ensure the best possible performance, quality, and responsiveness of the applications
- Identify bottlenecks and bugs, and devise solutions to these problems
- Contributing in all phases of the development lifecycle
- Help maintain code quality, organization goals, and improve automations

### Why it would be awesome to work with us

- Great culture of transparency and openness
- High salary for high performance
- Five working days/week
- Awesome friendly team
- Remotely working from home is available
- Working on a complex software engineering project
- Be a part of core tech team and part of one of the first companies starts in Vietnam and will expand regionally across Asia
- Flat and supportive working environment
- Trust and freedom to work on the product
- Continuous learning environment
- Supportive and highly skilled coworkers

It’s a permanent position working on a complex software engineering project. We are committed to staying up to date with technology, and openly encourage cross-functionality within teams. Your passion for growth will be matched by ours.

We have been growing rapidly over the last few years and have no intention of slowing down, so there will be loads of opportunities as we continue to dominate the market and in select international markets.

The business has ambitious growth plans, and will support you to expand your skill set and tackle new challenges.

### Contact
- Email: datnguyen.expert@outlook.com
- Skype: dat.cbdo@gmail.com
- Mobile phone: +84 96 699 2048

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
