### ISSUE TITLE
East Agile - Web Developer - Remote/Saigon/Hanoi/Danang - FT

### ISSUE THREAD

**Issue by oyster** [awesome-jobs/vietnam#3080]
## Location

* Remote
* Saigon / Hanoi / Danang, Vietnam

## Salary Expectation

* $600 - $3000 / month: a wide range of salary depending on your relevant experience, and then your performance in our interview.

## Requirements

- No prior experience required if you are applying to a junior position.
- Must have commercial experience working in Python, or Ruby on Rails, or nodeJS, or Golang, or React (or even iOS or Android) development if you are applying to a senior position.
- Education: we prefer a degree in computer science, mathematics or statistics from a top Vietnamese or foreign university.
- Excellent logic skills.
- Excellent Object oriented programming skills.
- Good verbal English communications skills.
- Familiar with Unix (Mac OSX, Solaris, or Linux command line).
- Familiar with test based development, refactoring, and programming in an IDE.
- Prefer experience developing applications on the Cloud, such as AWS, GCP, Heroku, Engine Yard, using relevant tools.
- Prefer knowledge of UX/UI best practices.
- Prefer experience working in an agile development environment using eXtreme Programming and/or SCRUM.
- Willing to work closely and continuously with other programmers, almost never programming alone.

### Must Have

* Be smart
* Be open-minded

### Ideally

* Good comunication skills
* Good English

### Responsibilities

Choose to work remotely or from our offices in Da Nang, Ha Noi, or Ho Chi Minh City. You will work directly, in English, with the founders of new and rapidly growing Internet ventures to understand their vision and implement it on the web and on iPhone and Android smartphone platforms. You will use Extreme Programming and SCRUM agile development methods which include paired programming, Behavior Driven Development (BDD), Test Driven Development (TDD), and emergent business-value prioritized development. You will work in small teams of two to seven. You will enhance your skills in advanced javascript, Ruby on Rails, Python, nodeJS, Golang, iOS and Android development working with leading American companies. You will develop applications on Cloud platforms that can grow to support millions of users. You will stay on the cutting edge of Internet application development.

### You’ll be responsible for

* Doing pair programming
* Following TDD & BDD
* Working on challenging web (and/or mobile) applications
* Communicating directly with clients

### You can bring

* Your dedication
* Your humor

### Why it would be awesome to work with us

- Ability to work remotely, or transfer between our offices in Ha Noi, Ho Chi Minh City, and Da Nang,
- 15 days annual leave,
- Excellent health insurance,
- A 40-hour regular work week with little or no after-hours work requirements,
- End-of-year Tet bonus,
- A fun and flexible working environment in a modern office,
- Free office lunch,
- Salary reviews every 6 months,
- Business trips for meetings with clients in North America.

### Interesting engineering projects

- All sorts of cloud applications, varied from small startups to big enterprises.
- Challenging projects solving real-life problems with all the cutting-edge techologies applied.

### Contact
Homepage: https://eastagile.com & https://eastagile.recruiterbox.com
Email: jobs@eastagile.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.

**Comment by lwsinclair** [comment]
@lactroi This should not be expired. We are almost always hiring. This has been the case throughout our 15 years in Vietnam.
