### ISSUE TITLE
Trait Sniper - Golang Engineer - SG/Remote FT/PT

### ISSUE THREAD

**Issue by sonhnguyen** [awesome-jobs/vietnam#3082]
## Location

We have an office at D4 - Saigon, but whatever fits you.

## Salary Expectation
$1000-$3000/ month

## Job Description:
We are a startup in NFTs that aims to be the fastest NFT ranking platform. Looking for backend Golang engineer . We are highly flexible as a team, doing all fronts to make our user most profitable in the NFT market. Golang backend job currently includes serving APIs, maintaining crawling speed and designing infrastructure for crawling thousands of request per seconds. We works closely with OpenSea APIs, Ethereum network and will be expanding to other L1 chains in the futures (BSC, FTM, Solana, Matic, ...)

## Requirements
* Must knows Golang.
* Familiar with web crawling, concurrency, Redis, Postgres and scalable RESTful APIs practices.
* Years of experiences in working with APIs and backend stuff.
* Comfortable in using multiple languages (we are hacking with NodeJS/ Golang/ ReactJS).
* Must be task oriented, self-sufficient and full autonomy at your work, no one likes to micro management. Start-up spirit/ get the job done kind of guy.
* Ideally if you are into blockchain/ DeFi/ NFTs/ cryptocurrency. Our whole product might changes tomorrow but we will stick with blockchain in everything we do.
* Plus points: Web3 minded, entrepreneurial spirit,  young blood needed cuz we early stage, open-minded & fast learner. Nerds/ Geeks.

### Why it would be awesome to work with us
- Blockchain focused startup with plenty of ideas to execute.
- Highly flexible work environment.
- Working closely with customers (our chat room is in the same Discord as our customers).
- Biweekly payment, optional in cryptocurrency of your choice.
- We breath blockchain culture as a company, say GM in the morning and WAGMI at the end of the day.

### Contact
* Check our product at: http://traitsniper.com/
* Shoot me an email at: gm@traitsniper.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
