### ISSUE TITLE
CXP - Blockchain QA Engineer - Up to $2000 - HCM - Full-time

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3087]
## Location
* Orchard View Apartment, 132 Hồng Hà, Phú Nhuận District, HCMC, Vietnam
* Currently working online 100% due to Covid-19

## Salary Expectation
* up to 2,000$/month
 
## What you’ll work on
* Thorough understanding of how popular dApps work: Uniswap, Sushiswap, Compound...
* Experience in writing automated tests for dApp frontends.
* Ability to create testing setup from zero.
* Be able to work autonomously.
* The candidate should be independent enough to make important technical decisions on their own.
* The candidate should be driven and innovative, planning the best ways to get full test coverage of the product.

## Requirements
* Setup the tools needed to enable end to end testing (JS framework, local blockchain)
* Analyze and propose a test plan for each.
* Write appropriate end to end tests in order to protect the product from regressions bugs.
* Monitor newly released features and continually add tests for these.
 
## Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* Annual company trip
* 13th salary bonus

## Why it would be awesome to work with us
* We are a young, lean, and strong team 
* We build a professional & fun working environment.

## About Us
CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
Ms. Jade | hr@cxptek.com
Phone: +84772997820 (Zalo)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
