### ISSUE TITLE
[HCM] Back-end Developer (Ruby) | $400 - $1000

### ISSUE THREAD

**Issue by phongnguyensdr** [awesome-jobs/vietnam#309]
* YOMI STUDIO - Binh Thanh, HCM

*Salary: $400-$1000

*Experience Level: 2 Year

We’re looking for developers who build products, not just applications, to grow client’s businesses. We don’t receive requirements from our clients, but problems that need to be solved together.

Job Description: 

Helping crack touch business problems.
Deliver highly scalable and reliable business applications. 
Ensure code is written to quality standards, has sufficient test coverage, and adheres to design requirements. 
Assisting the Development team and Project Manager in producing functional specifications, work estimates and timescales for new development work. 
Sharing and working with other teammate to tackle problems by reviewing code and pair programming. 
Here is our requirements:

Familiar with Ruby programming language.
Knowledge of Unix/Linux environments.
Solid understanding of object-oriented programming.
Understanding of front-end technologies, such as Javascript, HTML5, CSS3.
Able to implement automated testing platforms and unit tests.
Proficient understanding of code versioning tools with GitFlow.
Have experience in key-value store engine (Redis), back-end index engines such as Sphinx, Solr is a huge plus.
Able to create database schemas that represent and support business processes.
Good at reading and listening in English.
Benefit:

We have Work retreat that to go aboard twice a year (every 6 months). Last time we went to Chiang Mai, ThaiLand in a month. 
Flexible working time. We don’t have a working schedule and a limit of days for annual leave as well. 
A Macbook, a big monitor to work with. 
Free lunch and snack. We won’t be responsible if you gain weight. 
Tech gadgets to play with : PS4, AppleTV, GearVR... If you are an old fashioned, we have books (lots of book), boardgames... 
Competitive reward. 
Work with us, a bunch of nerdy ninjas.
You'll have an awesome ever workplace with: private bedrooms, cafeteria, private quiet rooms, meeting rooms and lots of open space for working
Address: Binh Thanh District, HCMC

Send your resume and a cover letter via e-mail: phongnguyen.sdr@gmail.com

**Comment by hieuk09** [comment]
Hi @phongnguyensdr, the format of this job post is not comply to our [rule](https://github.com/awesome-jobs/vietnam), could you please fix it? If the post is not amended within 2 days, it'll be closed.

**Comment by joneslee85** [comment]
Closed. No amendment made after 2 days.
