### ISSUE TITLE
Money Forward Vietnam - Android Engineer - HCMC - FT

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#3091]
## Location
* D4, Saigon, Vietnam
* Currently working remotely 100% due to Covid 19

## Salary Expectation
* $1500 - $2700
* **Sign-on bonus 1 month salary gross**
* **No Probation AT ALL**
* **You can choose to onboard now or after Tet**

## Requirements
* 3+ years’ experience in developing native apps for Android using Java or Kotlin (ideally both).
* Experience with MVVM and MVP model.
* Experience with Dagger 2, LiveData ...
* Strong understanding of Functional Program.
* Experience with unit tests to improve software quality.
* Experience with code review
* Experience of team development using Git
* If you don‘t have enough experience, you can apply for this job!

### Must Have
* Experience with Android software development lifecycle.
* Motivation to learn a new programming language
* English skill for business
* Excellent at teamwork
* A person who wants to become a playing manager in the future, or is interested in management

### Ideally
* Experience with clean-code, readable-code
* Experience in iOS development
* Excellent troubleshooting skills, able to dive into complex code/infrastructures, and find the root cause.
* Excellent communication and presentation skills, able to communicate with business and technical stakeholders also external customers.
* Shipped one or more apps in the Store.

### Responsibilities
* Develop and maintain our service
* Developing a clean and maintainable code
* Discussing about architecture with the team
* Training for junior/middle software engineers
* Deliver outputs with expected quality, speed in order to bring the best values to service

### You’ll be responsible for
* Building a financial platform for ALL

### Why it would be awesome to work with us
* **Sign-on bonus 1 month salary**
* **No probation applied for technical positions (all levels)**
* Salary review: Twice a year
* Bonus: 13th-month salary
* Paid leave: 15 days in total, Maternity leave for partner (extra 5 days)
* Awards: Monthly Culture Hero, Half-year MVP for excellent members
* Activities: Company trip, Year-end party, Half-year party, team-building, happy hour, etc...
* Devices: MacBook Pro + Dell Monitor
* Working hour: Monday to Friday (working hour starts from 8am to 9am)
* Health care: Annual health check
* Insurance:
Social Insurance, Health Insurance, Unemployment Insurance (company will pay for full salary)
Voluntary health insurance & accident insurance (Bao Viet Tokio Marine Insurance 24/7
* Training:
External or internal training courses
Internal workshop
Support Attending Conference
Scrum training
Order books based on member's requests
* Others:
Grab expenses on the party day
Club activities, playstation, billiard, etc…
Free bike parking, fruits and coffee

### Contact
Email: nguyen.thi.to.loan@moneyforward.vn
Skype: nguyentoloan2009
Phone: 0906 516 291 (Zalo/Whatsapp)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
