### ISSUE TITLE
JobSeekervn - Frontend Developer - Fulltime - Remote

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3092]
## Location
* Saigon, Vietnam
* Remote, Fulltime

## Salary Expectation
* $1500 - $2200/month or range

## Requirements
*  Have between 3-5 years developing complex, optimized, highly available web apps.
● Good at English
● Strong understanding of HTML5 & CSS3, JS
● Extensive knowledge on SEO
* Experience with jQuery library, Shopify scripts (Ruby), Shopify AJAX API
* Experience with Vue.js, Node.js, PHP
* Experience with source control systems such as GIT. 

### You’ll be responsible for
* Liaise with the key stakeholders of the project.
* Deliver fully implemented vertical feature sets based on the specification within estimates and without defects.
* Identify and mitigate risk in the project's implementation.
* Participate in code reviews.
* Lead and mentor junior members of the team
* Report to the Project Manager and Tech Lead. 

### Why it would be awesome to work with us
 * 13th month salary & other bonuses based on the business performance and trading results of the company
* Working from home
* 12 annual leave. 
*  Interesting engineering projects

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
