### ISSUE TITLE
JobSeekervn - Backend Developer - Fulltime - Remote

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3093]
## Location
* Saigon, Vietnam
* Remote

## Salary Expectation

* $2000 - $2300/month or range

## Requirements
* Techskills: React/ React SSR, NodeJS, API/SDK 
* Familiarity with databases (e.g. MySQL, MongoDB) and web servers (e.g. IIS, Apache)
* English speaking

### Responsibilities

* Participate in product design and team planning sessions
* Assist in estimating and prioritizing proposed features
* Utilise customer feedback to recapitulate features quickly
* Create tools that allow others on the Go-To-Market team to scale up 

### Why it would be awesome to work with us
* 13th month salary + bonus
* 12 annual leave
* Medical and accident Insurance 

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
