### ISSUE TITLE
Remote Senior Ruby On Rails Engineer

### ISSUE THREAD

**Issue by karg-betacode** [awesome-jobs/vietnam#3094]
## Location

* Remote

## Salary Expectation

* USD1500 to 2000 per month

## Requirements
The ideal candidate is a self-motivated, multi-tasker, and demonstrated team-player. You will be a lead developer responsible for the development of new software products and enhancements to existing products. You should excel in working with large-scale applications and frameworks and have outstanding communication and leadership skills.

 
### Must Have

* RubyOnRails 4 to 6
* Sidekiq
* Javascript
* MySQL/ Postsql
* HTML, CSS
* Docker
* Integration to payment gateways; Stripe, Paypal

## Nice to have

* Hotwire
* Front end framework: Vue, React
* Devops experience

### Ideally

* More 7+ years of relevant work experience, mostly in Ruby On Rails
* Expertise in Object Oriented Design, Database Design, and XML Schema
* Experience with Agile or Scrum software development methodologies
* Ability to multi-task, organize, and prioritize work
* Able to speak and write clearly in English

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Writing clean, high-quality, high-performance, maintainable code
* Develop and support software including applications, database integration, interfaces, and new functionality enhancements
* Coordinate cross-functionally to insure project meets business objectives and compliance standards
* Support test and deployment of new products and features
* Participate in code reviews & pair program

### You can bring

* A good analysis skill
* Tender and loving care to the code that you touch
* Supportive to new members to the team

### Contact
Homepage: betacode.io
Trollman: karg_at_betacode_dot_io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
