### ISSUE TITLE
Resola - Senior QA engineer - Remote - FT

### ISSUE THREAD

**Issue by evert0n** [awesome-jobs/vietnam#3095]
# Job brief

We are looking for a Senior Quality Assurance (QA) engineer to develop and execute exploratory and automated tests to ensure product quality.

QA engineer responsibilities include designing and implementing tests, debugging and defining corrective actions.
You will also review system requirements and track quality assurance metrics.

The QA technician role plays an important part in our company’s product development process.

Our ideal candidate will be responsible for conducting tests before product launches to ensure software runs smoothly and meets client needs, while being cost-effective.

If you hold an engineering background and enjoy providing end-to-end solutions to software quality problems, we’d like to meet you.

Ultimately, you should monitor all stages of software development to identify and resolve system malfunctions to meet quality standards.

## Location

- Remote
- Or on-site in Tokyo, Japan

## Contract and Salary Expectation

- $1800 ~ $2500 USD
- 3 months probationary period
- Performance review every 6 months

## Responsibilities

- Review requirements, specifications and technical design documents to provide timely and meaningful feedback
- Create detailed, comprehensive and well-structured test plans and test cases
- Estimate, prioritize, plan and coordinate testing activities
- Design, develop and execute automation scripts using open source tools
- Identify, record, document thoroughly and track bugs
- Perform thorough regression testing when bugs are resolved
- Develop and apply testing processes for new and existing products to meet client needs
- Liaise with internal teams (e.g. developers and product managers) to identify system requirements
- Monitor debugging process results
- Investigate the causes of non-conforming software and train users to implement solutions
- Track quality assurance metrics, like defect densities and open defect counts
- Stay up-to-date with new testing tools and test strategies

## Requirements

- Proven work experience in software development
- Proven work experience as a Senior Quality Assurance engineer
- Strong knowledge of software QA methodologies, tools and processes
- Experience in writing clear, concise and comprehensive test plans and test cases
- Hands-on experience with both white box and black box testing
- Hands-on experience with automated testing tools
- Experience working in an Agile/Scrum development process
- Experience with performance and/or security testing is a plus
- Excellent communication and teamwork skills
- Great attention to detail
- Organizational skills

## Nice to have

- Familiarity with SQL and programming
- Can communicate in Japanese with our internal team
- Experience testing SaaS products and services
- Familiarity with AWS services

## Why it would be awesome to work with us

We are a distributed team in a multi cultural environment, 35+ engineers from 8 nationalities, 60% engineers from Vietnam
Together we develop and maintain 5 SaaS products and various tailored business solutions for our clients

## Interesting engineering projects

- Data platform
- Analytics platform
- Chatbots
- Videocalls
- Commerce
- Recommendation systems
- Integrations with messaging platforms: Slack, Microsoft Teams, Line, Line Works, Google Meet

## Our products and services

- [Synalio](https://synal.io/)
- [PEP](https://pep.work/)
- [Libero](https://libero-app.com/)
- [Shinan Maker](https://shindan-maker.com/)
- [Virtual Store](https://virtualstore.jp/)

## Apply

Please apply using this link
https://angel.co/l/2wbY7x

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
