### ISSUE TITLE
Resola - Senior Frontend Engineer - Remote - FT

### ISSUE THREAD

**Issue by evert0n** [awesome-jobs/vietnam#3097]
# Job brief

We are looking for a Senior Front-end developer to join our team.

You will be responsible for building the client-side of our web applications.
You should be able to translate our company and customer needs into functional and appealing interactive applications.

If you’re interested in developing an user-friendly product and moving forward in your career, then this job is for you.

We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design.

You should also be a team player.

## Location

- Remote
- Or on-site in Tokyo, Japan

## Contract and Salary Expectation

- $2000 ~ $3000 USD
- 3 months probationary period
- Performance review every 6 months

## Responsibilities

- Use markup languages like HTML to create user-friendly web experiences
- Maintain and improve application
- Optimize applications for performance and usability
- Design mobile-based features
- Collaborate with back-end developers and web designers to improve usability
- Get feedback from, and build solutions for, users and customers
- Write functional requirement documents and guides
- Help back-end developers with coding and troubleshooting
- Ensure high quality standards and brand consistency
- Stay up-to-date on emerging technologies

## Requirements

- Proven work experience as a Front-end developer
- In-depth understanding of the entire web development process (design,
- Understanding of layout aesthetics
- Knowledge of multiple front-end languages and libraries (e.g. HTML/ CSS,
- Knowledge of multiple frameworks (e.g. React, VueJS)
- Familiarity with browser testing and debugging
- Familiarity with development tools (e.g. Git, Docker)
- Familiarity with software like Adobe Suite
- Excellent communication and teamwork skills
- Great attention to detail
- Organizational skills

## Nice to have

- Familiarity integrating third party APIs
- Can communicate in Japanese with our internal team
- Experience developing and operating SaaS products and services
- Backend development

## Why it would be awesome to work with us

We are a distributed team in a multi cultural environment, 35+ engineers from 8 nationalities, 60% engineers from Vietnam
Together we develop and maintain 5 SaaS products and various tailored business solutions for our clients

## Interesting engineering projects

- Data platform
- Analytics platform
- Chatbots
- Video calls
- Commerce
- Recommendation systems
- Integrations with messaging platforms: Slack, Microsoft Teams, Line, Line Works, Google Meet

## Our products and services

- [Synalio](https://synal.io/)
- [PEP](https://pep.work/)
- [Libero](https://libero-app.com/)
- [Shinan Maker](https://shindan-maker.com/)
- [Virtual Store](https://virtualstore.jp/)

## Apply

Please apply using this link
https://angel.co/l/2wbYoP

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
