### ISSUE TITLE
Jitera - Remote Senior ReactJS Engineer - FT

### ISSUE THREAD

**Issue by jitera-inc** [awesome-jobs/vietnam#3099]
**About This Job**
Build Jitera product and act as important role in Jitera Team
[Create a source code generator and automate coding!!  
](https://docsend.com/view/q45jdphuj7tv9b7v)
We also have some client works *ex: create a dating app, saas platform, booking service...etc

**Requirements**
**Minimum qualification**

You can agree with our vision and can act with our value
- React (at least 3 years)* - redux, redux-saga or redux-thunk, react hook...etc
- React Native* - expo, react-navigation- JavaScript* eslint, prettier

**Hope to know about**
- You need to have knowledge about MVC, service, decorator, serializer, or any other architecture 
- Well know about the database (MySQL, PostgreSQL...etc)
- Restful architecture
- Infrastructure as a code - AWS, GCP, Azure...

**You will be a great fit if you have:**
- High sense of responsibility and teamwork.
- The passion to remove unnecessary coding and create innovation
- Honesty and a good heart
- Able to communicate fluently in English 

**Benefits**
- Can work part-time during the probation if you recently have a full-time job.
- Full remote and you can work from all over the world and work in your timezone
- At least you need to attend video calls without delay and work on a stable internet. We may ask to meet in JST but we can make arrangements for a meeting schedule.
 We'll provide some benefits if you'll work as a full-time regular employee.
- Provide Tax (maximum 10% of salary)
- Premium insurance
- 20 Annual Leaves
- MacBook Pro M1 provided
- Happy Hours/ co-working space
- Sponsorship for classes - English/ Training
- Anniversary/ Special occasion bonus/gifts

Apply via https://apply.workable.com/jitera/j/A23B9482A5/apply/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
