### ISSUE TITLE
2NF - Junior Ruby (1+ year EXP) - Hà Nội - FT

### ISSUE THREAD

**Issue by cuongnm2nf** [awesome-jobs/vietnam#310]
## Location

* HaNoi, Vietnam
* Full time in office

## Salary Expectation

* Negotiable ( You will love it )

## Requirements
* Ruby
* RailsFramework
* MySQL
* 1+ years Software Engineering experience

### Contact 
9th Floor, 3A Building, 82 Lane, Duy Tan Street, Cau Giay District, Ha Noi City.
Email: thuytt@2nf.com.vn
Mobile number: 04 3839 8714 ( 8h - 18h )

**Comment by hiendinhngoc** [comment]
I didn't see any description about your company :(

**Comment by cuongnm2nf** [comment]
This is our website www.2nf.com.vn, www.2nf.vn. You can call to our mobile number to get details.
Thank you very much

**Comment by hieuk09** [comment]
Hi @cuongnm2nf,

Thanks for using our board. I apologize about nitpicking detail, but here we must ensure the quality of job post. Therefore, could you please help us modifying these detail:

- Please add a company description 
- Remove `(1+ EXP)` from the title
- Replace `Junior Ruby` with `Junior Ruby Developer`

If the post is not amended in 2 days, it will be closed.

**Comment by joneslee85** [comment]
Closed. No amendment were made.
