### ISSUE TITLE
Apollo - Lập trình viên Golang - HCM - FT

### ISSUE THREAD

**Issue by hongloc5998** [awesome-jobs/vietnam#3100]
## Location

* Quận Phú Nhuận, Hồ Chí Minh
* Full-time

## Requirements:
* Ít nhất 2 năm kinh nghiệm phát triển phần mềm chuyên nghiệp.
* Có kinh nghiệm về Git, Golang, Restful.
* Có kinh nghiệm tốt về thiết kế và phát triển ứng dụng hướng đối tượng.

## Benefits:

* Môi trường làm việc trẻ trung. Văn phòng làm việc tiện nghi. Miễn phí trà, cafe và có tủ đồ uống,…
* Gói bảo hiểm chăm sóc sức khỏe toàn diện.
* Hỗ trợ ứng viên phỏng vấn online và làm việc tại nhà trong thời gian giãn cách Xã hội.
* Thời gian làm việc 5 ngày/tuần, từ 9h00 đến 18h00.

### Why it would be awesome to work with us
Apollo cung cấp giải pháp gia tăng năng lực phân tích dữ liệu, đẩy mạnh hoạt động chuyển đổi số, hỗ trợ ra quyết định giúp giải quyết những vấn đề thực sự, thử thách của khách hàng và cùng khách hàng xây dựng một xã hội an toàn, tốt đẹp hơn.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
