### ISSUE TITLE
Saigon Technology Solutions - Fullstack .NET Developer - HCM - FT

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#3101]
## Location

* 02 Nguyen The Loc, Ward 12, Tan Binh District, HCMC

## Salary Expectation

* Up to $2200 NET
* Full package of social insurance
* Signing bonus $1500

### Top 3 Reasons To Join Us

* Technical training sessions (internal-external)
* Attractive salary, benefits and signing bonus
* Premium healthcare insurance for employees and family

### Must Have

* At least 5 years of experience in .NET Applications especially in ERP
* Good .Net Core skills
* Good Angular skills
* Good SQL Server
* Excellent investigation skills, backed up a deep technical understanding of the platforms, together with significant experience of Agile project developments
* Good at English communication

### Nice to have

* Experience in Microsoft Dynamics 365 system or able to learn
* Financial Services
* Insurance or Loss Prevention exposure
* Sharepoint

### Responsibilities

* Developer within the Support team
* Work directly with client and development team
* Undertaking support and enhancement on systems delivered by the customer other partners. When required, this team is also responsible for the development of new functionality for any supported system. Members of this team will possess excellent investigation skills, backed up a deep technical understanding of the platforms, together with significant experience of Agile project developments

## About our client

* The client is a specialist software company based in the UK.  We have been in business for over 25 years, while our core specialism is in the Financial Services and Insurance sectors, we undertake projects in a wide variety of areas from production line control, through goods tracing and sourcing, to government and public sector contracts.
* As an organization, we do not generally engage in the mass assignment of staff, preferring to focus on the smaller, technically challenging projects, in fact, a lot of our clients come to us having already failed to achieve their goal – our reputation for ‘achieving what others cannot’ is enviable.
* We run proper agile teams, with every member of the team able and expected to contribute to the success of the project.  We pride ourselves on delivering what we said, when we said, to quality we would accept ourselves and want every team member to show a real passion for the client deliverables.  We also realize that everyone needs to grow and learn, and we look to provide the opportunity for everyone to learn and develop.  Project isn’t always smooth sailing, but our teams pull as one with no one individual taking the blame – that said, we are all passionate about what we do but also having a great time, so our teamwork principles extend well past just the tasks at hand.

## About the Project

* Methodology: Kanban/Agile (Scrum), 2-week sprints for Feature development
* Project: Our client, a large marine insurance company based in London, has been a client for many years, and over that time Jumar has worked with them to create a feature-rich Underwriting Platform and is a key partner.  The client manages Tier 1 and some Tier 2 queries, but Tier 2 and all Tier 3 incidents are addressed by a dedicated support and enhancement team.
* Stage of the project: Extending existing support team already in place
* Key technologies: .Net, Entity Framework, SQL, Azure, Microsoft Dynamics 365, Sharepoint
* This is an expansion of the existing internal support team and will allow capacity to provide enhanced support to SPL Singapore and other projects targeted for support team coverage

## Why it would be awesome to work with us

At **Saigon Technology Solutions**, we believe that "_Your success is our mission_", that’s why we build an excellent working environment along with exceptional benefits:

* Attractive salary and benefits (13th, **Salary review – twice/year**)
* Project bonus
* **Free English courses**
* **PVI health care program**
* Company trip every year
* Weekly happy hour
* The staff of the month/year reward
* Party celebration(Christmas, Birthday,...)
* Team-building activities
* Technical training sessions (internal-external)
* Weekly Knowledge Exchange
* A professional working environment with Agile – Scrum
* Sports clubs (football, badminton…)
* Enjoy Relax and beautiful Pantry in the company
* Periodic health examination

## Contact
Homepage: www.saigontechnology.com
Contact person: Kien Tran - Talent Acquisition Lead
Email: kien.tran@saigontechnology.com
Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by trankien200691** [comment]
up

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
