### ISSUE TITLE
Star Global - Junior Manual QA Engineer - Web/Mobile - HCMC - FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#3103]
## Location

- Saigon, Vietnam
- Hybrid working mode - remote + office

## Salary Expectation

Yes, we have a budget for every Engineering level but...
Due to the company policy, we can only let you how your salary expectation will fit in our budget but it definitely matches with the current market or even higher *wink

## Requirements
Skills and Experience
- Computer science degree or similar;
- Good understanding of HyperText Markup Language (HTML);
- Understanding of Continuous Integration/Continuous Deployment (CI/CD) workflows;
- Understanding of Client/Server architecture;
- REST API concept understanding, ability to interact with API;
- Data exchange formats understanding (JSON, XML);
- Understanding of Agile delivery frameworks such as Kanban or Scrum;
- Upper-intermediate level of English;
- Ability to read and write project documentation and correspondence.

### Responsibilities
- Become an essential part of the product life cycle;
- Be responsible for features quality from requirements gathering stage up until release to Production;
- Mobile and server release management in close communication with internal and client’s Development and DevOps teams;
- Create, prioritize and execute test cases, document software defects, create relevant project documentation;
- Review and resolve escalations from end-users;
- Configuration management in the Production database, system and mobile apps submission to Apple and Google Play stores;
- Coordinate with QA and Development teams on bug fixes, feature deliverables;
- Ensure that 3 million monthly users are happy with our work.

### Why it would be awesome to work with us

- Flexible working hours with hybrid working policy (remote & office);
- Global consulting environment & opportunities to learn and use trending tech stacks through high-quality projects;
- Impressive salary package;
- 20 days of paid leaves and 01 birthday leave;
- 10 days of paid sick leaves offered by Star;
- Latest MacBook Pro & monitor or you can bring your own device, we'll compensate you monthly;
- Full social insurance and private healthcare insurance from PVI starting from your probation;
- Free English classes and many more to come!

### Contact
Vietnam Career Homepage: https://star.global/careers/?location=824
Send your CV directly to: quyenphan@star.global

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
