### ISSUE TITLE
Spiderbox Design - Ruby on Rails Developer (Middle/Senior)- D2, HCM - Partially Remote/Fulltime

### ISSUE THREAD

**Issue by donnguyen** [awesome-jobs/vietnam#3104]
## Location

* Saigon, Vietnam
* Remote (2 days per week)

## Salary Expectation

* $3500/month or range

## Requirements
* Ruby on rails
* PostgreSQL
* 5+ years Software Engineering experience

### Must Have
* ROR Backend experience
* Familiar with TDD/BDD
* Good English communication
* Proficient understanding of code versioning tools, such as Git
* Clear communication skills for reporting needs and answering technical and service questions

### Ideally

* Experience working with foreign companies, in particular, Australia
* Experience working in a fast-paced agile team

### Responsibilities

* Ruby on Rails Developer will be part of a fast growing team of developers to support a range of front end and back end projects for a large Australian client.
* Domain: Financial

### Why it would be awesome to work with us

- Competitive and attractive salary
- Private health care
- New Computer (Mac/PC) that fits your needs
- Comfortable working time: 9am - 6pm (flexible), Mon - Fri
- A conveniently located office in D2, HCMC.
- International, dynamic, friendly working environment
- Annual performance review: recognize your efforts and identify development/ improvement needs
- Clear KPI’s and expectations
- Free English class
- Internal activities: weekly games, English talk with gift vouchers, free snacks & drinks

### Contact
Homepage: https://spiderbox.design/
Email: uyen.pham@spiderbox.design (Uyen - 0981235794)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
