### ISSUE TITLE
Codelight - BE, FE, Fullstack - Saigon - FT

### ISSUE THREAD

**Issue by frangte** [awesome-jobs/vietnam#3108]
## Location

* Binh Thanh, Saigon, Vietnam

## About the company

- Codelight is embarking on a new project dedicated to building an economic incentive
blockchain infrastructure to make web3 apps fully decentralized.
- We are looking for talented backend engineers to join our team.
- You will be joining a small and awesome startup team with amazing team members, who
are ex-googlers, Ph.D. (s) to design highly available and scalable systems in a fast paced
development environment. The founder is from Silicon Valley who used to be tech lead
at Google. He was also a co-founder of Harmony ONE (currently 2B valuation). So you
definitely will learn a lot from the team.

## Salary Expectation

* $1k - $1.5k/month (Junior)
* $1.5k - $2.5k/month (Senior)

### Backend:
- 3+ years of experience, smart and get things done, able to learn new technologies quickly.
- Experience in Python, NestJs.
- Devops experience is a plus.
- Solidity and blockchain experience are another big plus.

### Frontend:
- 3-years+ experience with software engineering.
- Smart and get things done.
- Experience in VueJS.
- Experience in NestJs is a plus.
- Experience with Flutter is a big plus
- Blockchain experience is another big plus.

### Why it would be awesome to work with us

- High and negotiable salary, depending on your skills and experience
- Bonus + 13th-month salary option available.
- Free Lunch offered.
 Gym, beautiful swimming pools, park for jogging available as our office is located at
Vinhomes Central Park.
- Free learning courses to upgrade your skills and knowledge.
- No worries about the job stability as the startup is well-funded.
- Growth opportunity by learning and working with ex-googlers and Silicon Valley
entrepreneurs.
- Opportunity to hold key positions (e.g. CTO) when the team scales.
- Flexible environment is provided as long as you can get the job done in the right way.
- Become one of the core members of the team.

### Contact
Homepage: codelight.co
Email: nakhoa17 `at` gmail.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
