### ISSUE TITLE
C.A.N Group - Backend Developer - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by gill502** [awesome-jobs/vietnam#311]
[CAN backend developer Recruitment .docx](https://github.com/awesome-jobs/vietnam/files/479198/CAN.backend.developer.Recruitment.docx)
## Location
- 91 Nguyen Huu Canh Street, Binh Thanh District, Ho Chi Minh City. 
## Salary:
- 650 USD – 900 USD (depending on level of skills and fulfillment of requirements)
## Requirements
- Working in Ruby on rails 
- Laravel, Wordpress knowledge is plus
- Solid understanding of object-oriented programming
- Experience with HTML5/CSS3, JavaScript, Bootstrap, Node.JS
- Setup server Unix/Linux environment, 
## Skills
- Possess good skills working independently and in groups and be be able to work under high pressure.
- Good time management and problem solving skills
- Good learning attitude, professionalism and high sense of responsibility.
### Contact
- Please send your application to: tung.pham@cangroup.io
- The applications must include: (Please specify the position you are applying in the Subject of the email)
-  Viet-Eng CV (with 01 picture attached)
-  Samples of websites done by you in the past.

**Comment by hieuk09** [comment]
Hi @gill502, could you move the file to the top of the job post?

**Comment by gill502** [comment]
@hieuk09 I did it. Thank for reminding me. :)
