### ISSUE TITLE
FunnelBeam- Solution Architect (Python)- Toan quoc- Fulltime Remote

### ISSUE THREAD

**Issue by KhayLy** [awesome-jobs/vietnam#3111]
Solution Architect (Fulltime)

We are looking for an experienced Solution Architect to provide hands-on
technical leadership to the team implementing our cloud-based B2B SaaS
applications.
Working directly under the supervision of the executive leadership team, you will
take full ownership of all backend applications and cloud infrastructure and
prepare them to support the expected exponential growth in our customer base.
Initially, there will be a heavy focus on a thorough refactoring of our back-end application code (mainly
written in Python) and a review of our Kubernetes-based infrastructure to improve maintainability, quality,
performance and scalability.
In parallel, you will work with management to reliably deliver new functionality, improve development
team productivity and bring new team members on board.
Salary range: 2000USD - 4000USD (can be higher depending on skills and experiences)

Responsibilities
Your responsibilities will include:
● Lead the refactoring / re-implementation of our existing Python codebase to improve
maintainability, quality and performance
● Take ownership of our Kubernetes-based infrastructure (running on GCP) and ensure
that it is ready to support substantially higher customer volumes
● Work with product management to plan new product features
● Provide mentoring to the development team
● Lead implementation of key new features
● Maintain a reliable monitoring system to ensure any outages or performance issues are
promptly detected and addressed
● Assist in resolution of significant customer issues in production
● Set up a state of the art CI/CD process
● Guide the development team in incorporating best practices, and ensure they are
followed by review of code and configuration updates
● Support the QA team in creating thorough automated tests for all components

Skills
You must have:
● A bachelor’s degree in computer science, systems analysis or a related study, or
equivalent experience
● Excellent written and spoken English
● 10 + years of directly relevant experience; experience as a team lead preferred
● 6+ years of hands on experience with Python, ideally including Flask, Celery and Django
● Solid knowledge of databases including MongoDB and MySQL
● Hands-on experience with GCP (preferred) or AWS
● Strong understanding of secure network architectures
● Experience working with Git and GitHub
● Experience working in an agile development environment
● Ability to diagnose and resolve problems independently, including consulting online
resources and effectively asking the developer community for help
● A strong desire to stay up to date with evolving standards, best practices and tools in
software development and cloud architecture

Q&A:
1. About the company
The company is a data intelligence and AI company, building products and technology to
help enterprise sales teams and large tech companies. We are about 10 people, looking
to bring on more backend engineers, the rest are in job description. Company exist for
about 7 years. We are a VERY stable company!
2. Working hours
- 8 hours/per day. Total: 40 hours/week, work from home and can be in Vietnam
hours.
3. Application
Please send to: khaly0620@gmail.com.
Skype: Thi Hứa(live:.cid.23b00a3184b4ce6f)
Process of interview: 1-2 weeks.

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
