### ISSUE TITLE
[HSVN] - [System Engineer (Linux/ DevOps/ Hadoop)] - [Hanoi] - [FT]

### ISSUE THREAD

**Issue by Xamnguyen** [awesome-jobs/vietnam#3112]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1500 - $2000/month + KPI bonus

## Requirements
– System:
+ At least 1 year exp in system operation (CentOS, Ubuntu, RedHat)
+ Exp in VMWare, Zabbix, Grafana, Prometheus, ELK,…
+ Exp in Database (MySQL, PostgreSQL, MariaDB,…)
+ Exp in Web Server (NGINX, Apache, Tomcat,…)
– DevOps:
+  CI/CD (Jenkins, Git,…)
+ Kubernetes, Docker, Ansible, Python,…
– Big Data:
+ Hadoop/Spark Apache

## Skills
– Manage Incident / Incident / Change / Security / SR as standard ITSM process
– Monitoring server system (Zabbix, Grafana or Kibana, Prometheus...)
– Linux (Redhat, CentOS)
– Installation & configuration management of DB system solutions (PostgreSQL, MariaDB, MySQL, NoSQL, PaceMaket, etc.)
– Installation & Configuration Management Software (NGINX, Tomcat, Apache, etc.)
– Install & configure Kubernetes/Jenkins

### Contact
Skype: live:.cid.f9a5012fddc93dbe (Xâm Nguyễn)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
