### ISSUE TITLE
Tinai - Senior Software Engineer - Remote - FT

### ISSUE THREAD

**Issue by longvtran** [awesome-jobs/vietnam#3113]
## About the role
As a **full-time Senior Software Engineer** at Tinai, you have the opportunity to shape the direction of the company. There is _no_ BA or manager ordering you around, and we do not care about ranks or seniority. **Only ideas and execution matter.** So if you are looking for a place to turn your ideas into reality and build for the millions of small businesses in Vietnam and Southeast Asia, **[join us](https://forms.gle/uJcyoAk5K21KYkVP8).**

## Location
- Remote
- Or onsite in Ho Chi Minh City

## Salary Expectation
- 2,000+ USD/month, plus stock options
 
## Why it would be awesome to work with us
Tinai's mission is to use technology to make the lives of small merchants richer and easier. We are building mobile apps to help the 6 million+ merchants in Vietnam do bookkeeping and become true owners of their businesses. 

Tinai was founded by a team of engineers from Amazon, TikTok, and Airbnb. We are also the third Vietnamese companies to receive funding from Y Combinator, the world-class accelerator that has helped great companies such as Airbnb, Reddit, and Stripe get started. Our website is https://www.tinai.com/.

## Requirements
- A strong sense of responsibility and commitment
- Constant curiosity about customers’ needs and the world at large
- Top-notch communication skills
- Willingness to voice your own ideas and opinions, and to work on new problems as they
arise
- Ability to program for Android (Kotlin/Java)
- Knowledge of basic design patterns

## Nice to have
- Strong understanding of software development principles, capabilities and limitations of mobile platforms
- Proficiency in at least one of these programming languages: Java, Kotlin
- Ability to understand and debug large and complex code bases

## Responsibiliies
- Work remotely
- Engage in and improve the whole lifecycle of Android mobile apps from
inception and design, throughout development, capacity planning, and launch reviews,
to deployment, operation, and refinement
- Collaborate with engineering, design, and marketing team members to design, program,
and maintain code systems
- Scale the codebase in terms of performance, stability, and maintainability
- Create a neat, beautiful, and engaging user experience

## Other benefits
- Network and learn from engineers of global tech companies, including Airbnb, Amazon, and TikTok.
- Autonomy to build and own critical product features while shaping the direction of the company.
- Self-managed, results-driven Silicon Valley culture.

## Contact
-  **Submit your application at https://forms.gle/uJcyoAk5K21KYkVP8**
-  Website: https://www.tinai.com/
-  Email: long@tinai.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
