### ISSUE TITLE
2359 Media - Senior iOS Developer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by namdaoviet** [awesome-jobs/vietnam#312]
## Location
- Saigon, Vietnam
### 2359 Media

In less than 4 years, we built an award-winning, multinational mobile-first studio. It has been an adventure best described as a coherent and chaotic innovation. One that would not be possible without the ingenuity of our people.
We still have the same dream. To create business value through digital experience engineering.
Those who work here describe 2359 Media as a place to grow their skills and ability. The hierarchy is very flat and our time during work is focused on delivering great work to our clients.
Website: www.2359media.com
## Salary Expectation
- Negotiable
## Requirements
- Degree in Computer Science, Information Systems, or a related field, or significant equivalent experience
- Significant experience with Swift, iOS Frameworks and Third-Party libraries
- Deep understanding of Cocoa Design Patterns, OOP, algorithms, code refactoring
- Ability to write well-abstracted, reusable and tested code
- Proficient in Xcode and Instruments
- Experience working with Git and GitHub
- Effective operation in a fast-paced and collaborative programming environment
- Experience with back-end server technologies a plus (Ruby on Rails)
### You’ll be responsible for
- Work with Project Manager to translate feature to stories
- Work with Server engineers to define APIs
- Assign logically segmented work to junior developers
- Review and improve the technical ability of junior developers
### This role is evaluated on
- Technical aptitude and Experience in iOS application development
- Ability to contribute effectively in a fast-paced, deadline-driven, and collaborative programming environment
- Ability to lead projects through the completion of all phases of application development
- Ability to problem solve keeping in mind the end goal
### Contact

Ms. Nam: nam.daoviet@2359media.com

**Comment by joneslee85** [comment]
Thanks for posting with us. Can you please revise the format of the job title to ensure all abbreviations met our guideline?

**Comment by namdaoviet** [comment]
@joneslee85 thanks. We revised that.
