### ISSUE TITLE
[Top American Firm] DevOps On-premise Engineer $3000-$5000+ HN/HCM - FT

### ISSUE THREAD

**Issue by minhhoa275** [awesome-jobs/vietnam#3123]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* **$3000-$5000+** (sign-on bonus if you join before Tet holiday)

## Requirements

* Experience in Linux administration; fluent in **Linux** standard command-line programs
* Experience in metrics and logs aggregation and analysis with a focus on performance optimization
* Demonstrated experience using **Python**; understanding of Python idioms and limitations; working experience with NumPy, pandas, SQLAlchemy, Flask/Celery is a plus
* Experience using relational databases (MySQL)
* Understanding of Git and CI/CD concept
* Familiarity with technologies like Kafka, Docker, Kubernetes, Hadoop ecosystem is a big plus
* Excellent analytical skills and a passion for solving problems
* Strong written and verbal communication skills; Fluency in the English language

### Responsibilities

* Operate company’s alpha production system, do on-call rotation, support end user’s requests, investigate and troubleshoot issues, respond to incidents.
* Build, test and deploy software and tooling around alpha production system from open sources to internal products, from scheduling/executing extreme resource-intensive jobs to automation, monitoring, test & QA.
* Integrate best-of-breed tools and technologies such as Kafka, Zookeeper, Docker, Kubernetes, Hadoop, Gitlab, MySQL.
* Work closely with other teams at WorldQuant to understand our users’ needs and act on it. 

### Why it would be awesome to work with us

*  Competitive and attractive compensation package with clear career road-map – where you feel challenged every day
*  We offer a strong culture of learning and development: training courses, library, speakers, share and learn events
*  Learn from who sits next to you! You'll be surrounded by smart and talented people
*  Employee resources groups with strong diversity and inclusion culture
*  Premium Health Insurance and Employee Assistance Program
Generous time-off policy, unlimited sick days, re-creation sabbatical leave (based on tenure), Trade Union benefits for staff and family
*  Team building activities every month: Local engagement events, monthly team lunch – Employee clubs: football, ping-pong, badminton, yoga, running, PS5, movies, etc.
*  Annual company trip and occasional global conferences – opportunity to travel and connect with our global teams
* Happy hour with tea break, snacks, and meals every day in the office!

### Contact
* Skype: ptmh27
* Zalo/Telegram: 0985084795

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
