### ISSUE TITLE
MyLong - Data Analytics Engineer - Vietnam, Remote - Fulltime

### ISSUE THREAD

**Issue by quy-ng** [awesome-jobs/vietnam#3125]
Data Analytics Engineers in MyLong sit at the intersection of Data Analytics, and Data Engineering and are responsible for bringing robust, efficient, and integrated data assets that are directly used by businesses.

## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* up to 3000$

## Requirements
* 3+ years in Software Engineering or 1.5+ years in Data Engineer
* Good English communication

### Must Have

* Bachelor's degree in Computer Science, related technical field, or equivalent practical experience.
* Experience with UNIX or GNU/Linux systems.
* Solid foundation in Python and at least another language in the JVM family.
* Experience with SQL and NoSQL database management systems.
* Experience with Docker, lib/version control tools.

### Ideally

* Experience with a data orchestrator such as Dagster, Airflow.
* Experience writing and maintaining data pipelines that operate on a variety of structured and unstructured sources.
* Experience with one or more of the following areas: Server Backend Distributed and Parallel Systems.
* Experience working with Machine Learning applications.
* Experience designing data models and warehouses with non-relational data storage systems (NoSQL and distributed database management systems).
* Experience with cloud-based tools in GCP, AWS, and transformation tools like DBT
* Excellent communication, organizational, and analytical skills.

### Responsibilities

* Create data pipelines using a variety of traditional and large-scale distributed data systems to visualize data on dashboards.
* Work closely with analysts/data scientists to productionize various statistical and machine learning models and reporting systems.
* Maintain code quality, and resolve related issues if happened.
* Implement the DataOps philosophy in everything you do

### You can bring

* Able to work independently as well as in collaborative mode with minimum supervision.
* Willingness to learn and able to pick up new technology or new concepts fast.

### Why would it be awesome to work with us?

* Comparative Salary
* A good analysis skill
* Annual Leave: 12 days/per year
* Sick Leave: 6 days/per year
* Remote work

### Contact
Homepage: [opusmatch.ai](https://opusmatch.ai/)
Linkedin: https://www.linkedin.com/company/mylong
Contact point: Quy (Mr)
Email: quy@mylong.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
