### ISSUE TITLE
Kilo - VP of Engineering - HCMC, Remote - Fulltime

### ISSUE THREAD

**Issue by ngoctranueh** [awesome-jobs/vietnam#3126]
## Location

* Saigon, Vietnam
* Remote

## About Us
Kilo is a technology start-up in Vietnam. Our customers are primarily small and medium-sized retailers, wholesalers, and distributors. Our mission is to digitize the current offline commerce of traditional trade in Vietnam to bring financial services and tools to underserved market segments. We are democratizing access to the best pricing, assortment, and inventory management tools and building the next generation retail and inventory management platform by bringing robust software systems to traditional offline distribution channels.

Kilo was founded on the principle that technology can affect change in traditional and deeply entrenched sectors such as offline retail stores and we are ready to ramp up our investment in Kilo’s technology teams across engineering, product management, and design. Over the next year we will go from a handful of software engineers to a fully fledged software, product management, and design organization of over 30 people.

## Responsibilities

The VP of Engineering role will be instrumental in hiring, shaping, and mentoring our team through this growth and have an outsized impact on Kilo’s tech DNA for years to come. The ideal candidate should be:

1. Capable of attracting, hiring, and retaining high caliber engineering talent
2. Comfortable navigating major architectural, platform, and organizational decisions
3. Comfortable rolling up their sleeves and getting hands on while coaching engineering talent.

This is an ideal role for someone who likes building organizations and teams; this is an opportunity to get in on the ground floor of a quickly growing start up and guide the growth of our engineering organization

## Qualifications

- 10+ years of engineering experience, with minimum 4 years managing organizations of 20+ engineers
- Proven capability to hire and retain high performing engineering teams
- Proficiency with Javascript, React Rative, or NodeJS
- Proficiency with relational databases
- Proficiency with Service Oriented Architecture
- Proven ability to work with team members and cross-functional partners in a highly collaborative environment
- Familiarity with AWS
- Excellent spoken and written communication skills (English).

## Why it would be awesome to work with us
- Macbook & external monitor are provided
- Impressive salary package and annual salary review
- 13th month salary and discretionary bonus
- 100% salary on your probation period
- 18 days of annual leave
- Full social insurance and Healthcare Insurance (for you and your family member)
- Premium annual health check-up
- Flexible working hours with hybrid working policy (remote & office)
- Be a part of core tech team and part of one of the first companies starts in Vietnam and will expand regionally across Asia
- Chance to build a new product from scratch with international development team
- You are always welcome to contribute your ideas to Kilo's vision, technology and implementation
- Flat and supportive working environment
- Modern office with the flexible relaxing zone based in District 3, Ho Chi Minh City
- Free bike parking, fruits and coffee, happy hours weekly

## Find us more
[https://kilo.vn/](url)
[https://techcrunch.com/2021/11/14/vietnamese-b2b-e-commerce-platform-kilo-bags-5m-pre-series-a/](url)

## Contact
tran.ngo@kilo.vn (Ms. Trân) | tran.ngoc.161 (Skype)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
