### ISSUE TITLE
Kilo - DevOps - HCMC, Remote - Fulltime

### ISSUE THREAD

**Issue by ngoctranueh** [awesome-jobs/vietnam#3127]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* USD 3,000 - 4,000 in Gross

## About Us
Kilo is a technology start-up in Vietnam. Our customers are primarily small and medium-sized retailers and distributors.

Our mission is to shift the B2B2C ecosystem with a mission to empower retailers. This is done by democratizing access to the best pricing, assortment, and inventory management. We are building the next generation retail platform by bridging the gap between traditional distribution channels with robust software systems

Kilo was founded on the principle that technology can affect change in traditional and deeply entrenched sectors such as offline retail stores. Our sales and technology platform is one-a-kind specifically built to address retailer and brand pain points and solve them at scale.

## Responsibilities
At Kilo, we care deeply about our team and we are obsessed with crafting a fun, productive, collaborative, diverse, friendly environment that can enable everyone to do the best work of their careers, and have the best time doing it.

After a lot of hard work over the last year, we are ready to expand our product lines and thoughtfully grow the team! We are hiring passionate, collaborative, customer-driven engineers who share our belief that modern business software can be fast, fluid, beautiful, and even joyful to use.

We leverage iterative, test-driven development and continuous integration to reliably deliver value to customers and we prioritize a high-ownership, low-overhead approach to software development, where you'll be expected to build, launch, and operate product features end-to-end.

## Qualifications
- Building / Proposing architecture for modern cloud-based infrastructure on AWS
- Being responsible for high availability and site reliability of infrastructure (automation, monitoring, scaling, alerting)
- Familiar with DevOps automation tools of cloud environments (CI/CD, AWS, Docker, Terraform … )
- Familiar with *nix systems as well as being proficient in CLI environment
- Know at least one of the popular programming languages (Python, NodeJs, Go …)
- Knowledge of common network concepts
- Good problem solving skill (we pay more attention to your mindset, not the programming languages / tools you know)
- Being a good team player who can cooperate with others and also able to work independently in the daily work
- Being able to communicate in English

### Nice-to-have
- Experience with orchestrating scalable application to deal with high web traffic
- Experience with common methods for securing system components in cloud-based environments

## Why it would be awesome to work with us

- Macbook & external monitor are provided
- Impressive salary package and annual salary review
- 13th month salary and discretionary bonus
- 100% salary on your probation period
- 18 days of annual leave
- Full social insurance and Healthcare Insurance (for you and your family member)
- Premium annual health check-up
- Flexible working hours with hybrid working policy (remote & office)
- Be a part of core tech team and part of one of the first companies starts in Vietnam and will expand regionally across Asia
- Chance to build a new product from scratch with international development team
- You are always welcome to contribute your ideas to Kilo's vision, technology and implementation
- Flat and supportive working environment
- Modern office with the flexible relaxing zone based in District 3, Ho Chi Minh City
- Free bike parking, fruits and coffee, happy hours weekly
## Find us more
https://kilo.vn/
https://techcrunch.com/2021/11/14/vietnamese-b2b-e-commerce-platform-kilo-bags-5m-pre-series-a/

## Contact
tran.ngo@kilo.vn (Ms. Trân) | tran.ngoc.161 (Skype)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
