### ISSUE TITLE
2359 Media - Senior Ruby on Rails Developer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by namdaoviet** [awesome-jobs/vietnam#313]
## Location
- Saigon, Vietnam
### 2359 Media

In less than 4 years, we built an award-winning, multinational mobile-first studio. It has been an adventure best described as a coherent and chaotic innovation. One that would not be possible without the ingenuity of our people.
We still have the same dream. To create business value through digital experience engineering.
Those who work here describe 2359 Media as a place to grow their skills and ability. The hierarchy is very flat and our time during work is focused on delivering great work to our clients.
Website: www.2359media.com
## Salary Expectation

Negotiable
## Requirements
- Degree in Computer Science, Information Systems, or a related field, or significant equivalent experience
- At least one year of Server programming experience
- Strong working knowledge in: 
  - .NET/Ruby, Ruby on Rails, HTML, Javascript, CSS (SASS), Coffeescript. 
  - Databases: PostgreSQL, MySQL, Redis/MongoDB, etc. 
  - Cloud Service: AWS with EC2, RDS, S3, Heroku, etc.
- In-depth knowledge of scalability, systems engineering and design patterns
- Experience in developing APIs
- Logical thinking with natural problem solving skills
- Self-Learner (i.e. Able to make good assumptions and search for solutions before asking for help)
- Good communication skills
### You’ll be responsible for
- Work with Project manager to translate feature to stories
- Work with Mobile engineers to define APIs
- Assign logically segmented work to junior developers
- Review and improve the technical ability of junior developers
### This role is evaluated on
- Technical aptitude and Experience in Server application development
- Ability to contribute effectively in a fast-paced, deadline-driven, and collaborative programming environment
- Ability to lead projects through the completion of all phases of application development
- Ability to problem solve keeping in mind the end goal
### Contact

Ms. Nam: nam.daoviet@2359media.com

**Comment by lethanh273** [comment]
adfafd

**Comment by joneslee85** [comment]
@namdaoviet can you please update the formating for the 2nd level bullet point as in `Strong working knowledge in: o .NET/Ruby, Ruby on Rails, HTML, Javascript, CSS (SASS), Coffeescript o Databases: PostgreSQL, MySQL, Redis/MongoDB, etc. o Cloud Service: AWS with EC2, RDS, S3, Heroku, etc.`

**Comment by namdaoviet** [comment]
@joneslee85: done. thank you
