### ISSUE TITLE
JobSeekervn - Blockchain Developer - Saigon - Fulltime

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3130]
## Location

* Saigon, Vietnam
* Fulltime 

## Salary Expectation

* $1500 - $2700/month or range

## Requirements
* Knowledge of blockchain and smart contracts concepts (especially Ethereum, BSC, NFT)
* Experienced in front end & back-end languages (ReactJS & NodeJS preferred)
* Strong cryptography knowledge

### Responsibilities

* Research, design, develop, and test blockchain technologies that could be utilized in EcoSystem.
* Analyze, brainstorm and evaluate applications of newly emerged tools and technology.
* Maintain and extend the current platform, responsible both for the blockchain smart contract and the integration to the client & server side application.
* Document new solutions and maintain the existing one.

### Why it would be awesome to work with us

* Interesting engineering projects
* Social insurance, health/life/disability insurance, annual health check
* 13th month salary 
* Yearly bonus up to 2 month pay depending on performance review
* 14 days of paid vacation                
* Work laptop
* Company trip and other team benefits

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
