### ISSUE TITLE
Onmic - Mobile engineer (React native) - HCMC, Remote - Fulltime 

### ISSUE THREAD

**Issue by s123121** [awesome-jobs/vietnam#3132]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* 900 - 1500$

### Must Have
* At least 6 months of working experience with React Native, must understand philosophy of React Native and React
* Have experience with push notification
* Have experience with animation in RN 
* Have knowledge of iOS SDK and/or Android SDK
* Have experience with the publishing process for both Apple and Google app stores
* Familiar with working with Graphql API

### Ideally

* Have experience working with Redux
* Have experience working with Android native (Kotlin/Java)
* Have experience with crash analytics and reporting
* Have experience with CodePush
* Have experience with unit and integration test development

### Responsibilities

* Write readable and maintainable code that not only performs the task but eases future modifications
* Work in a team environment, cooperating on designing and implementing user friendly solutions
* Take ownership of the features you design and develop
* Translate designs and wireframes into highly reusable code
* Suggest and propose features to further improve the product

### Why it would be awesome to work with us

We are building a next-gen social media platform. Seriously, Onmic is the authentic, intimate and interactive audio-streaming platform in Vietnam (and then SEA).

We are a fast growing startup (just receive our seed funding to expand in 2022). We can guarantee that you can see the impact of your code immediately on the products and the users. At the same time, as the very first core member of Onmic team, you will directly work with founders to bring all the ideas to life while fast-tracking your career.

### Contact
Homepage: getonmic.com
Email: send cv to lam@getonmic.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
