### ISSUE TITLE
Onmic - Backend Engineer - HCMC, Remote - Fulltime 

### ISSUE THREAD

**Issue by s123121** [awesome-jobs/vietnam#3133]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* 900 - 1500$

### Must Have
* At least 6 months of working experience with Nodejs
* Have experience with Graphql
* Have experience with Redis/Memcached
* Have experience with MySQL/PostgreSQL
* Have experience working with Git (Github/Gitlab)

### Ideally

* Have experience with server monitoring and reporting
* Have experience with unit and integration test development
* Have experience with Elixir is a big plus
* Have experience with k8s

### Responsibilities

* Write readable and maintainable code that not only performs the task but eases future modifications
* Work in a team environment, cooperating on designing and implementing user friendly solutions
* Take ownership of the features you design and develop
* Translate designs and wireframes into highly reusable code
* Suggest and propose features to further improve the product

### Why it would be awesome to work with us

We are building a next-gen social media platform. Seriously, Onmic is the authentic, intimate and interactive audio-streaming platform in Vietnam (and then SEA).

We are a fast growing startup (just receive our seed funding to expand in 2022). We can guarantee that you can see the impact of your code immediately on the products and the users. At the same time, as the very first core member of Onmic team, you will directly work with founders to bring all the ideas to life while fast-tracking your career.

### Contact
Homepage: getonmic.com
Email: send cv to lam@getonmic.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
