### ISSUE TITLE
LionRose - DevOps Engineer - HCMC - FT

### ISSUE THREAD

**Issue by lynnhr81** [awesome-jobs/vietnam#3137]
## Location

- Saigon, Vietnam

## Salary Expectation

- USD 800 - 1500 in NET

## Responsibilities

As a **DevOps Engineer,** you will be involved in the planning, development, and maintenance of the web & mobile app supporting our products and services in the entertainment industry for massive traffic of users in the APAC market.

- Optimize current system and server
- Support team members from BE team on Automation, **CI/CD pipeline**.
- Research new technology and apply it to our products.

## Qualifications

- +1 years of experience working with **CI/CD Systems** using **Jenkins** (big plus), and **Linu****x** (CentOS)
- Experience with or exposure to scripting & coding (**Bash** or **Groovy** or **Nodejs**).
- Proficient with **GIT**.
- Passionate about learning, finding new things and applying them to work.
- Adapt to high pressure at work.
- Have a good **product mindset** (Ability to understand and experience as a real user on the application you built).
- Can work both independently and in a team.

### Nice-to-have

- Experience in developing, integrating, building, packaging and deploying software with **Java, Nodejs**
- Automation with **Nodejs**, **Java**
- Experience in **deploying big data systems** using **Hadoop**, **Spark, Storm**,...
- Experience working with game server systems.
- Sharp and logical thinking, good at **maths** and **matrix** is a big plus.
- Knowledge and experience on the following software are desirable:
  - **Haproxy;** 
  - **ElasticSearch, Logstash, Kibana;** 
  - **MySQL, PostgreSQL;** 
  - **RabbitMQ, Apache Kafka, NATS messaging systems;** 
  - **Redis;** 
  - **CentOS/RHEL/Ubuntu**

## Why it would be awesome to work with us

- **MacBook Pro** and additional working-support **devices** provided on demand.
- Excellent and competitive salary package.
- **13th-month salary** with good **long‑term** and **performance bonus**.
- **Review performance** and **salary** every release milestone.
- Friendly working environment, no office politics.
- Free snack breaks and drinks, birthday celebration policy.
- Opportunities to gain hands-on experience in cutting-edge technologies and work on new technology.
- Experience the true start-up spirit of a fast growing and well funded studio.Find us more

## Contact

[lynn.pham@lionrose.biz](mailto:lynn.pham@l) (Ms. Linh) | 0978563759 (Zalo/phone)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
