### ISSUE TITLE
Sentifi - Service Desk Support - HCMC - FT

### ISSUE THREAD

**Issue by SentifiHiringTeam** [awesome-jobs/vietnam#314]
![30796](https://cloud.githubusercontent.com/assets/20198939/16440290/ae987ee8-3dea-11e6-8b33-f797e8dc5bbf.jpg)
_The Swiss fintech company Sentifi is a global leader in Crowd-Intelligence for financial markets. Sentifi’s big data and artificial intelligence based technology delivers insightful analysis helping millions of investors to be better informed and take better investment decisions.
Our fast growing company employs meanwhile more than 70 employees and has its technology hub in the booming Ho Chi Minh, Vietnam. One of the main objectives of Sentifi is to identify, classify and listen to 100 million people sharing information being relevant for financial markets and rank the online financial relevance of these people. The Sentifi analytics is distributed every hour to widgets on more than 20 newspapers, banks and trading platforms around the world generating more than 40 million impressions per month.
Sentifi won the Swiss FinTech Award 2016. The international jury of 22 members appraised the fast growing global reach and the unlimited scalability of the Sentifi business model._
## Salary Expectation

Competitive
## Your Engineering Team

We're looking for recent university graduates who are passionate to learn about Service Desk Support, DevOps and System Administration. This is the perfect opportunity to grow your skillset and career with a strong senior team. As the leading fintech company in Vietnam building the next generation financial information services, you'll have an opportunity to work on cutting-edge technologies employing Big Data and Machine Learning. In this position you will be responsible for Service Desk Support, DevOps and System Administration. 

With Service Desk, you will be first-level of support for staff hardware/software/account management requests as well as issue management. With DevOps you will help automate and manage solution releases. With System Administration you will ensure the uptime, performance, resources, and security of the systems that need managed. This position title will be, Associate Software Engineer.
## Your Role

The responsibilities include but are not limited to the following tasks and responsibilities:
- Being the first-level of service desk support to 100 employees for hardware, software, network and account management requests
- Provide support for internal tools and third-party services such as Git, Bitbucket, Jira, Confluence, Google Accounts, Amazon AWS
- Troubleshooting production issues using a rich and cutting edge toolset
- Deploying different tools, components, and systems into Production
- Automating and managing the deployment processes using Continuous Integration and Delivery techniques
- Monitoring and ensuring that the system infrastructure is up and running at all times
- Manage servers, applications, and all internal software used by the company
- Monitor system performance and undertake needed performance tuning
- Security of systems including establishment and monitoring of security policies for all systems
- Able to attend to system alerts on an on-call basis
## Your Requirements
- Bachelor degree in Information Technology, Computer Science, Software Engineering or Computer Engineering
- Strong English communication skills - verbal and written
- Comfortable using Linux and able to write Bash Shell scripts
## We offer
- We have a talented, international team of top-notch experts.
- We foster an open communication culture and strive to learn and improve every day.
- Competitive salary and participation in our equity incentive program
- 13th month salary and opportunity for performance bonus
- Fully Contributed Social, Medical and Unemployment Insurance
- Extra Premium Healthcare Insurance.
- Provided Annual Health Checkup.
- Other benefits: Provided daily snacks, weekly happy hours, Company trip, Football club, etc.

Most important:
- We  move fast and have fun while doing it. If you enjoy working with passionate people and seeing the results of your efforts in newspapers daily around the world, you will fit right in.
## Contact

Huyen Nguyen - Recruitment Specialist
Email: huyen.nguyen@sentifi.com
Phone: +84 6675 7906 (Direct)

**Comment by SentifiHiringTeam** [comment]
Hello admin, Please add hastag i.e "devops, it support, Linux, English skill". Thanks a lot.

**Comment by hieuk09** [comment]
@SentifiHiringTeam: Could you reindent the line below?

> The responsibilities include but are not limited to the following tasks and responsibilities:

This line should not be a bullet point.

**Comment by SentifiHiringTeam** [comment]
Done in editing
