### ISSUE TITLE
Lead Django developer

### ISSUE THREAD

**Issue by nguyenducgiang** [awesome-jobs/vietnam#3140]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* $2000 - $3500/month

## Requirements
* 3+ years of experience with Django
* Have experience with Vue/Nuxt or similar frontend frameworks
* Conversational English
* Excellent communication skill
* Have experience leading a team

### Must Have

* Python 3, Django 3
* Conversational English

### Ideally

* Experience with Vue/Nuxt
* Experience with devops

### Responsibilities

Cooperate with other team members and client teams to develop various products for internal and external use.

### You can bring

* A good analysis and communication skill

### Why it would be awesome to work with us

- Macbook pro M1 is provided for work
- 13th-month salary
- Annual allowance of 8m for private insurance.
- Annual health check at Vinmec or similar hospitals.
- Yearly vacation trip
- Salary review once a year
- Team building activities
- Grants for online courses, books & other learning materials
- Private English class (this is per case and needs to be reviewed and approved from management)

### Contact
Homepage: https://flyingwhales.io/
Facebook: https://www.facebook.com/flyingwhales.io
Email: hello@flyingwhales.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
