### ISSUE TITLE
Trait Sniper - Frontend Engineer - HCMC - FT

### ISSUE THREAD

**Issue by sonhnguyen** [awesome-jobs/vietnam#3142]
## Location

We have an office at D4 - Saigon, but whatever fits you. The position is highly remote-able and flexible.

## Salary Expectation

$750-$2500/ month

## Job Description:

We are a startup in NFTs that aims to be the fastest NFT ranking platform. We are highly flexible as a team, doing all fronts to make our user most profitable in the NFT market. We works closely with OpenSea APIs, Ethereum network and will be expanding to other L1 chains in the futures (BSC, FTM, Solana, Matic, ...)

## Requirements

- Must knows Reacts and the whole Nextjs stack.
- Must be task oriented, self-sufficient and full autonomy at your work, no one likes to micro management. Start-up spirit/ get the job done kind of guy.
- Ideally if you are into blockchain/ DeFi/ NFTs/ cryptocurrency. Our whole product might changes tomorrow but we will stick with blockchain in everything we do.
- Plus points: Web3 minded, entrepreneurial spirit, young blood needed cuz we early stage, open-minded & fast learner. Nerds/ Geeks.

### Why it would be awesome to work with us

- Blockchain focused startup with plenty of ideas to execute.
- Highly flexible work environment.
- Working closely with customers (our chat room is in the same Discord as our customers).
- Biweekly payment, optional in cryptocurrency of your choice.
- We breathe blockchain culture as a company, say GM in the morning and WAGMI at the end of the day.

### Contact

- Check our product at: [http://traitsniper.com/](http://traitsniper.com/)
- Twitter: [https://twitter.com/trait_sniper](https://twitter.com/trait_sniper)
- Shoot me an email at: [gm@traitsniper.com](mailto:gm@traitsniper.com)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
