### ISSUE TITLE
Senior/Leader IOS Developer (Swift, Objective-C)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3144]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2000-$2500

### Must Have

* 5 years of iOS experience.
* For Leader level: 3 years as manager/team leader 
* Programming languages: Swift
* Frameworks and APIs: Foundation, UIKit, GCD, WebKit, AVFoundation, Media Player, UserNotifications, JavaScriptCoreTools: Xcode, Git, Firebase, TeamCity
* Design patterns: MVC, MVVM, Singleton, Delegation, Observer, Coordinator, Factory Method,
* Mediator, Command, Adapter, Bridge, Facade
* Third-party libraries: SDWebImage, JSONModel, fmdb

### Ideally

* Programming languages: Objective-C, C++, JavaScript, Python

### You’ll be responsible for

* Plan and participate in the development of features
* Build the native features like News Feed, Media Player, ...
* Write the code to bridge between native and web view.
* Integrate new changes from Chromium to our codebase.
* Well designed, written, tested and reviewed code
* Collaborate with QA, PM, BA, UI/UX, UR team teams to define, design, and ship new features.
* Work on bug fixing and improve application performance.
* Provide technical helps for other team members
* Manage team members
* Be responsible for the team's performance

### Why it would be awesome to work with us
* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 

### Contact
Email :hattk@coccoc.com
Skype: khanhhatran213@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
