### ISSUE TITLE
Data Analyst

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3145]
## Location

* Ha Noi, Viet Nam

## Salary Expectation

* Up to $1500

## About Us

Business Intelligence department has a mission of consolidating company's data (including user, client and internal data), providing convenient access to it, extracting valuable information from it, helping other departments to incorporate data-driven solutions in their tools, products and processes.
Data Analyst team collects, cleans, manipulates and visualizes data; bring technical expertise to ensure the quality and accuracy of that data; provides valuable insights through analyzing process for other departments to make decision easily and effectively.

We are looking for a Data Analyst who is in charge of creating data measures and distribute valuable insights to stakeholders. This role will also support to implement ad-hoc analysis for stakeholders.
### Must Have

* Qualification in Statistics, Math or other analytical field (or equivalent experience);
* Knowledge of statistics;
* Strong SQL skills, ability to perform effective querying involving multiple tables and subqueries.
* Expertise in Data Visualization tools (Tableau, Google Data Studio, etc.)
* Experience with Excel, Word, and PowerPoint;
* Intellectual curiosity;
* Proven analytical skills and ability to use data to back up assumptions and complete root cause analyses;
*  Comfortable taking initiative and proactively offering recommendations through analysis of various data sources;

### Ideally

* Familiarity or basic knowledge of one of the scripting languages like R, Python, Scala etc.
* Solid business acumen and curiosity to understand our business model better.
* Passion for data investigation and finding out how things work.

## You’ll be responsible for

* Gather BI & Analytics requirements from stakeholders;
* Cleanse and analyze data from a different system;
* Support ad hoc data queries and data analysis and present findings to all levels of management;
* Build reports and dashboards in data visualization tools;
* Investigate and understand source data and how to use it to meet the reporting and analytical needs of the stakeholders;
* Interface with engineering teams to ensure relevant source data is made available;

## Why it would be awesome to work with us

* Attractive salary and bonus scheme with 13th month salary. 
* Performance review twice/year
* Special annual leave policy with minimum 20 days/year (including 1 day off on your birthday)
* Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
* Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 

### Contact
Email: hattk@coccoc.com
Skype: khanhhatran213

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
