### ISSUE TITLE
Senior Software Engineer (Backend/ Linux) HaNoi

### ISSUE THREAD

**Issue by Huees-ori** [awesome-jobs/vietnam#3146]
##Hanoi
* Hybrid
## Requirements
- Lead team phát triển sản phẩm, chịu trách nhiệm cao nhất trong phạm vi kỹ thuật của sản phẩm.
- Đảm nhiệm việc phân tích yêu cầu kỹ thuật, đưa ra giải pháp và tham gia phát triển các tính năng quan trọng.
- Nghiên cứu, tìm hiểu về các sản phẩm/nền tảng trên thị trường; thảo luận, tranh biện, đưa ra các ý tưởng phát triển, cải thiện sản phẩm đang có.
- Tuyển dụng và đào tạo team members.

## Skills
Golang, Python, Ruby, Java, linux
### Must Have
Có kinh nghiệm từ 5 năm trở lên về phát triển dự án ở vai trò Backend; có kinh nghiệm và kỹ năng thiết kế hệ thống, xây dựng APIs.
- Thành thạo ít nhất 1 ngôn ngữ lập trình: Golang, Python, Ruby, Java, ...
- Biết cách tạo và bảo trì code sạch.
- Có tư duy logic, thuật toán, cấu trúc dữ liệu tốt; hiểu về cơ chế hoạt động của 1 số cấu trúc dữ liệu phổ biến.
- Có tư duy sáng tạo khi giải quyết vấn đề, không bám theo lối mòn; có mindset của người giải quyết vấn đề.
- Sở hữu tinh thần làm việc của startup: chủ động, chịu khó học hỏi, tự chịu trách nhiệm trong công việc.
- Có kinh nghiệm lead team và/hoặc hứng thú với việc quản lý và phát triển team member của mình.
**- Không bắt buộc:**
- Có kinh nghiệm về ứng dụng mô hình học máy, học sâu cho các bài toán Computer
Vision và NLP.
- Đã từng làm việc với các dự án áp dụng DevOps/DataOps/MLOps.
- Đã từng tham gia dự án phải xử lý, tối ưu hệ thống số lượng giao dịch lớn.
- Có kinh nghiệm với AWS/Azure/GCP.

### You’ll be responsible for
Tham gia từ đầu quá trình thiết kế và xây dựng sản phẩm dạng APIs-as-a-Product, tập trung giải quyết các bài toán về số hoá thông tin và phân tích khối lượng lớn dữ liệu. Định hướng phát triển công nghệ liên quan đến Computer Vision/NLP/Data Science sử dụng các mô hình thống kê, học máy, học sâu.
Một số hướng nghiên cứu và sản phẩm công ty đang triển khai:
- Nhận dạng bóc tách thông tin biểu mẫu (OCR).
- Nhận dạng chữ viết tay dành riêng cho tiếng Việt.
Hiện vẫn đang mở rộng (không hạn chế) thêm nhiều bài toán, công nghệ mới.

### Why it would be awesome to work with us

Phòng ban tên CyberLabs với những sứ mệnh quan trọng trong việc nghiên cứu phát triển sản phẩm trọng tâm đồng thời đào tạo nhân sự tài năng cho toàn công ty. Hiện đã có các bạn sinh viên năm cuối với những thành tích ấn tượng.
Thời gian làm việc T2- T6

### Contact
Skype: huees
Zalo/tele: 0336294693

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
