### ISSUE TITLE
LionRose - Front-end ReactJS Developer - HCM - FT

### ISSUE THREAD

**Issue by lynnhr81** [awesome-jobs/vietnam#3148]
**## Location**

- Saigon, Vietnam

**## Salary Expectation**

- Maximum $2000 in NET

**## Responsibilities**

- As a **Frontend ReactJS Developer** you will be involved in the planning, development, and maintenance of the web supporting our products and services in the entertainment industry for a massive traffic of users in the APAC market.
  - Developing a flexible and well-structured front-end architecture, along with the APIs to support it on multiple platforms (Web, Mobile) from conception to delivery, including UX/UI.
  - Implementing systems and functionality for our **internal tools** based on design specifications.
  - Implementing, debugging and refining core features.
  - Collaborating effectively with the development team.
  - Keeping up to date on relevant core technologies and best practices, so as to make suggestions to the team on new mechanics or APIs available.
  - Research new technology and apply to the product.

**## Qualifications**

- **+3 years** of Front-end experience using **JavaScript, ReactJS, Redux**.
- Strong experience in **JSX, virtual DOMs, and CSS3**.
- Familiarity with **RESTful APIs & Socket IO**.
- Familiarity with newer specifications of ECMAScript.
- Experience in Git source control.
- Knowledge of security for large web systems.
- Resistant to high pressure at work.
- Have a good product mindset (Ability to understand and experience as a real user on the application they built).
- Have the ability to work well independently and in teams.

**### Nice-to-have**

- Experience in the online entertainment industry. 
- Knowledge of NodeJS.
- Knowledge or experience in UI/ UX.
- Passionate in learning, finding new things and applying them to work.
- Orientate and coordinate team activities.
- Be a good team player.

**## Why it would be awesome to work with us**

- **MacBook Pro** and additional working-support **devices** provided on demand.
- Excellent and competitive salary package.
- **13th-month salary** with good **long‑term** and **performance bonus**.
- **Review performance** and **salary** every release milestone.
- Friendly working environment, no office politics.
- Free snack breaks and drinks, birthday celebration policy.
- Opportunities to gain hands-on experience in cutting-edge technologies and work on new technology.
- Experience the true start-up spirit of a fast growing and well funded studio.

## Contact

[lynn.pham@lionrose.biz](mailto:lynn.pham@l) (Ms. Linh) | 0978563759 (Zalo/phone)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
