### ISSUE TITLE
Sentifi - Senior DevOps - HCMC - FT

### ISSUE THREAD

**Issue by SentifiHiringTeam** [awesome-jobs/vietnam#315]
![30796](https://cloud.githubusercontent.com/assets/20198939/16440290/ae987ee8-3dea-11e6-8b33-f797e8dc5bbf.jpg)
_The Swiss fintech company Sentifi is a global leader in Crowd-Intelligence for financial markets. Sentifi’s big data and artificial intelligence based technology delivers insightful analysis helping millions of investors to be better informed and take better investment decisions.
Our fast growing company employs meanwhile more than 70 employees and has its technology hub in the booming Ho Chi Minh, Vietnam. One of the main objectives of Sentifi is to identify, classify and listen to 100 million people sharing information being relevant for financial markets and rank the online financial relevance of these people. The Sentifi analytics is distributed every hour to widgets on more than 20 newspapers, banks and trading platforms around the world generating more than 40 million impressions per month.
Sentifi won the Swiss FinTech Award 2016. The international jury of 22 members appraised the fast growing global reach and the unlimited scalability of the Sentifi business model._
## Salary Expectation

Competitive
## Your Engineering Team

We're looking for software engineers who are passionate about DevOps and System Administration. As the leading fintech company in Vietnam building the next generation financial information services, you'll have an opportunity to work on cutting-edge technologies employing Big Data and Machine Learning. In this position you will be responsible for DevOps, System Administration and IT Support. With DevOps you will help automate and manage solution releases. With System Administration you will ensure the uptime, performance, resources, and security of the systems that need managed. And for IT Support you will serve the majority of users in Ho Chi Minh but could also include users in other countries (especially in order to ensure a group-based IT Security & Identity Management).
## Your role
- Deploying different tools, components, and systems into Production
- Automating and managing the deployment processes using Continuous Integration and Delivery techniques
- Monitoring and ensuring that the system infrastructure is up and running at all times
- Manage servers, applications, and all internal software used by the company
- Monitor system performance and undertake needed performance tuning
- Documenting the configuration of the system infrastructure
- Security of systems including establishment and monitoring of security policies for all systems
- Able to attend to system alerts on an on-call basis
## Requirements
- Bachelor degree in Computer Science, Software Engineering or Computer Engineering
- Good English communication skills
- 2+ years of experience of System Administration and/or DevOps
- Strong  Linux administration skills
- Experience in cloud computing services such as AWS, Azure, Google Cloud
- Experience with containerized services such as Docker, Kubernetes, et al.
- Experience with configuration management using Chef, Puppet, Salt or Ansible 
## We offer
- We have a talented, international team of top-notch experts.
- We foster an open communication culture and strive to learn and improve every day.
- Competitive salary and participation in our equity incentive program
- 13th month salary and opportunity for performance bonus
- Fully Contributed Social, Medical and Unemployment Insurance
- Extra Premium Healthcare Insurance.
- Provided Annual Health Checkup.
- Other benefits: Provided daily snacks, weekly happy hours, Company trip, Football club, etc.

Most important:
- We  move fast and have fun while doing it. If you enjoy working with passionate people and seeing the results of your efforts in newspapers daily around the world, you will fit right in.
## Contact

Huyen Nguyen - Recruitment Specialist
Email: huyen.nguyen@sentifi.com
Phone: +84 6675 7906 (Direct)

**Comment by SentifiHiringTeam** [comment]
Hello admin, please help add "DevOps, Linux, English, System admin" as the tag for the post. Thanks

**Comment by longkt90** [comment]
@SentifiHiringTeam please check the sentence bellow, should be 2 lines?
```
2+ years of experience of System Administration and/or DevOpsStrong Linux administration skills
``

**Comment by SentifiHiringTeam** [comment]
Checked and edited already. Thanks
