### ISSUE TITLE
Koina.VN - Software Engineer (Golang) - HCMC - FT

### ISSUE THREAD

**Issue by vinhdevie** [awesome-jobs/vietnam#3152]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $800~$2000/range

## Requirements
* 1+ years Software Engineering experience
* Knowledge and experience in Golang or any general purpose programming languages including but not limited to: C/C++, Python, Java, Javascript ES6. and be willing to change to Golang.
* Excellent attention to details.
* Self-motivated to explore new technologies, applications, and environments.
* Careful, detail and high responsibility
* Open mind and be willing to learning new thing

### Must Have

* Golang or willing to change to Golang

### You’ll be responsible for

* As Backend Developer you will be involved in the planning, development, and maintenance of the web & mobile app supporting our products and services, have the chance to make leading enterprise product for massive user in Vietnam market.
* Optimizing components for consistency and performance across desktops, tablets, and mobiles.
* Collaborate with cross-functional teams to design, develop and ship new features.
* Optimize the system for reliability and performance.
* Fix bugs and improve the system.
* Contribute knowledge to the technical team.

### Why it would be awesome to work with us

* A strong and friendly team, who will support you when needed, and troll you when bored
* A culture that encourage you to speak your mind and take ownership to the product that you made
* You can learn about not only technology but also business

### Contact
Email: vinh.nguyen@koina.vn
Mobile: 0984872865

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
