### ISSUE TITLE
NAB - Sr/Lead ReactJS - Hybrid/Hanoi - FT

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#3153]
## Location

* Hanoi, Vietnam
* Hybrid working

## Salary Expectation

* Up to $3000 

## Requirements
* JavaScript ES6/TypeScript working with React.js or similar technologies (Angular.js, Vue.js)
* HTML5, CSS3, Bootstrap, Foundation, JQuery, JSON
* Solid experience in modern front-end build pipelines and tools (e.g. Git, Webpack, Gulp, NPM
* Experience in Cloud computing and Amazon Web Services - particularly Serverless Development
* 5+ years Software Engineering experience

### Must Have
* Excellent in problem-solving and analytical skills;
* Strong understanding of standard Software Engineering processes, Testing, and Agile methodology;
* Strong English communication skills (both verbal & written), especially in the global software development environment.

### Ideally

* Experience in the Banking or Financial Services industry;
* Experience in using front-end testing and test runners (eg. Selenium, Mocha/Chai/Jest).

### Responsibilities

* Design, develop, review, implement, and manage React.js application code and services for the production and pre-release environments;
* Design, develop, review, implement, and manage continuous integration, build management and deployment scripts, systems and any code as required;
* Participate in Agile software development, prototyping, and code review with international development teams to build scalable microservices-based products;
* Understand the requirements of the customer or business and utilize this knowledge to develop applications that are consistent with this;
* Work with delivery teams to achieve success through development using CI/CD and DevOps practices, processes and tooling;
* Provide robust coding practices, solid unit/component test coverage, and debugging code.

### Why it would be awesome to work with us
* Very competitive remuneration package
* Generous private family healthcare for yourself and two family members
* A solid team behind you - great people who love what they do
* The pleasant, enthusiastic, international work environment
* Opportunity for traveling & training in Australia
* A brand new & state of the art Agile office
* Latest technologies, flexible working hours
* A promising training and career path
* Fun team activities & outing
* English learning with native English teachers

### Interesting engineering projects
* Projects in Banking sector with real users
* Standard Agile environment

### Contact
Lynn: Lynn.DuongHuong@nab.com.au (0934433526)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
