### ISSUE TITLE
[DEK TECHNOLOGIES VIET NAM ] - [ Automation Tester (QA QC)] - [ HA NOI/ HCM] - [FT]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3154]
## Location
* Saigon, Vietnam
* Open to remote from Hanoi
## Requirements
* At least 2 years’ experience with any Programming Language
* Experience with network configuration in Linux environment
* Desire to learn a functional programming language used to build massively scalable soft real-time systems with requirements on high availability. Its runtime system has built-in support for concurrency, distribution and fault tolerance
* 5+ years Software Engineering experience
### You’ll be responsible for
* Design traffic models and test scenarios based on requirement
* Configure test network and execute system test
* Automate system testing
* Support troubleshooting testing issues
* Work on multiple Cloud environments
* Virtualization (VMware, OpenStack, NFVI)
* Cloud Native (Microservices, Kafka, Kubernetes, Docker)
* Work with Continuous Integration (CI) system (Jenkins, etc.)
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
