### ISSUE TITLE
[DEK TECHNOLOGIES VIET NAM ] - [Senior C++ Developer] - [HCM] - [FT]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3155]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* University degree in Computer Science or Engineering
* Experienced in C++ and Python programming language
* Experienced in low-level development of modern streaming technology (DASH/HLS, MP4, MPEG-TS, DRM systems)
* Analytical mindset and ability to design complex systems
* Good knowledge about networking and Linux system
* Good English communication skill
### You’ll be responsible for
* Troubleshoot issue, suggest and provide solution for released feature
* Analyse the requirements to design and implement new features
* Continuously improve together with the team
* Actively contribute to our customer satisfaction
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes

### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
