### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Telecommunication Application Developer (Fresher) ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3156]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* Strong IT background
* Fluent in at least one programming language
* High teamwork spirit
* Eager to learn new technologies
* Basic English communication
### You’ll be responsible for

* Analyse, design and implement solutions for new features
* Design and execute test scenarios in both feature and system test levels
* Maintain product
* Work on multiple Cloud environments
* Virtualization (VMware, OpenStack, NFVI)
* Cloud Native (Microservices, Kafka, Kubernetes, Docker)
* Work with Continuous Integration (CI) system (Jenkins, etc.)
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
