### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Mobile App Developer (React Native) ] - [ HCM ] - [FT]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3157]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* Mobile app development and deployment on Android and/or iOS platforms
* 3+ years’ experience with React Native
* Strong knowledge of RESTful API design & programming
* Good knowledge in OOP, Design pattern, Unit Testing
* Experienced with GIT source control, BLE, Google SDK (Analytics / Firebase / Google Maps …), Realm database
* Experienced in working with Agile/Scrum
### You’ll be responsible for
* We are looking for Experienced Developers to design and build Android and iOS Mobile applications. You need to be self-driven and love to solve problems.
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
