### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ iOS Developer ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3158]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* At least 3 years of experience with mobile app development and deployment on iOS native development with Swift* Lotus Framework
* iOS Native
* Good knowledge in OOP, design pattern, Unit Testing
* Familiar with reactive framework likes BLE, RxSwift
### You’ll be responsible for
* We are looking for iOS Developer to design and build Mobile applications. You need to be self-driven and love to solve problems.
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
