### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ C/C++ Software Developers – Driver Monitoring System Project ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3159]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* Experience developing production-quality C++ code
* Experience writing code for multi-core SoCs and multi-threading system
* Experience developing embedded Linux kernel drivers/applications
### You’ll be responsible for
* Designing, implementing and testing Linux kernel drivers/applications for the Driver Monitoring solution for a number of driver monitoring applications
* Designing, developing and problem-solving embedded systems – including prototyping of concepts as well as optimizing and improving system architecture
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
## Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
