### ISSUE TITLE
Sentifi - Mobile Senior Engineer (React Native) - HCMC - FT

### ISSUE THREAD

**Issue by SentifiHiringTeam** [awesome-jobs/vietnam#316]
![30796](https://cloud.githubusercontent.com/assets/20198939/16440290/ae987ee8-3dea-11e6-8b33-f797e8dc5bbf.jpg)
_The Swiss fintech company Sentifi is a global leader in Crowd-Intelligence for financial markets. Sentifi’s big data and artificial intelligence based technology delivers insightful analysis helping millions of investors to be better informed and take better investment decisions.
Our fast growing company employs meanwhile more than 70 employees and has its technology hub in the booming Ho Chi Minh, Vietnam. One of the main objectives of Sentifi is to identify, classify and listen to 100 million people sharing information being relevant for financial markets and rank the online financial relevance of these people. The Sentifi analytics is distributed every hour to widgets on more than 20 newspapers, banks and trading platforms around the world generating more than 40 million impressions per month.
Sentifi won the Swiss FinTech Award 2016. The international jury of 22 members appraised the fast growing global reach and the unlimited scalability of the Sentifi business model._

## Salary Expectation
Competitive

## Your role
- Within this role you will work on building out our flagship Mobile product using React Native for iOS and Android devices. You will work on a dedicated Agile squad team. The responsibilities include but are not limited to the following tasks and responsibilities:
- Using React Native in building out Mobile products for iOS and Android devices
- Write Unit Tests and use Continuous Delivery Pipelines
- Participate in Agile meetings
- Demonstrate an aptitude to learn and grow
- Be a mentor to other software engineers

## Your must-haves
- Bachelor degree in Computer Science or Software Engineering
- Strong English verbal and written communication skills
- 5+ years building Mobile Solutions
- 2+ years using JavaScript
- 1+ years using React Native
- Strong understanding of mobile development and Android or iOS platforms
- Able to provide a portfolio of Mobile apps that have played a key role in developing

## Your nice-to-haves
- Experience using Feature Toggles and A/B testing in mobile apps
- Using one or more Analytics providers in a mobile app

## We offer
- We have a talented, international team of top-notch experts.
- We foster an open communication culture and strive to learn and improve every day.
- Competitive salary and participation in our equity incentive program
- 13th month salary and opportunity for performance bonus
- Fully Contributed Social, Medical and Unemployment Insurance
- Extra Premium Healthcare Insurance.
- Provided Annual Health Checkup.
- Other benefits: Provided daily snacks, weekly happy hours, Company trip, Football club, etc.

Most important:
- We  move fast and have fun while doing it. If you enjoy working with passionate people and seeing the results of your efforts in newspapers daily around the world, you will fit right in.

## Contact
Huyen Nguyen - Recruitment Specialist
Email: huyen.nguyen@sentifi.com
Phone: +84 6675 7906 (Direct)

**Comment by SentifiHiringTeam** [comment]
Please help add tag i.e "Mobile, React Native, iOs, Android". Thanks

**Comment by hieuk09** [comment]
@SentifiHiringTeam: sorry for the delay, but could you change the part

> Within this role you will work on building out our flagship Mobile product using React Native for iOS and Android devices. You will work on a dedicated Agile squad team. The responsibilities include but are not limited to the following tasks and responsibilities:

to normal text without the bullet point.

**Comment by hieuk09** [comment]
The name of the section should be strictly complied to our template as well (e.g. change `Your nice-to-haves` to `Ideally `)

**Comment by SentifiHiringTeam** [comment]
Ok

I'll make a change on the job post.

Best Regards,

[image: logo] <https://sentifi.com/>
Huyen Nguyen - Recruitment Specialist
----------------------

Sentifi Technology Hub Vietnam
Sentifi Group AG - Financial Market Signals from the Crowd
e: huyen.nguyen@sentifi.com |  LinkedIn Profile
<https://vn.linkedin.com/in/xuanhuyen3011>
f: +84  987 939 161
Sentifi Vietnam LLC, 77 Tran Nhan Ton, Dist 5, Ho Chi Minh city
www.sentifi.com - twitter: @sentifi <http://twitter.com/@sentifi>
WINNER OF
[image: the-swiss-fintech-award-2016]
<https://sentifi.com/community/sentifi-receives-the-swiss-fintech-award-2016/>

**Comment by hieuk09** [comment]
There is no update to this post. I'll close it.
