### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Embedded Software Testers ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3160]
## Location

* Ho Chi Minh, Vietnam
## Requirements
* Graduated or have experience as Software Tester or similar position
* Knowledge of testing methodologies, testing process, quality models, standards
* Working knowledge of scripting language such as Python, Bash Script, etc.
* Have knowledge or Experience in Embedded Testing is a plus
### You’ll be responsible for
* Develop Project Test and Timing Plans
* Design, develop and execute test specifications for Driver Monitoring System
* Interface with key stakeholders on project test activities
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
