### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ C/C++ Software Developer (Fresher) ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3161]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* C/C++ software development passion
* High teamwork spirit
* Basic English communication
### You’ll be responsible for
* New generation of mobile core network infrastructure that enables various types of multimedia services to end-users using common TCP/IP-based protocols
* A high capacity, high availability, scalability cluster platform used in mission-critical products that can serve extremely huge number of users at the same time
* Linux Operating System (OS) customization
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
