### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Telecommunication Application Developer (Experience) ] - [ HCM ] - [ FT ] 

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3162]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* Experience in software development
* Highly proficient in Erlang or functional programming languages such as Elixir on a product or system in production
* Comfortable working in a GNU/Linux environment
* Be comfortable around Makefile, shell scripts, Python, C
* Atlassian products, such as JIRA, confluence, stash
* Experience from embedded systems, databases and distributed databases and network engineering
* NETCONF, RESTCONF, YANG
* The applicant should be able to work and communicate in English
### You’ll be responsible for
* This position will be a part of the core engineering team within Engineering based in Stockholm. The team is responsible for the development of our market leading products, written mostly in Erlang, with parts in C:
   * NSO: industry-leading software for automating services across traditional and virtualized networks
   * ConfD: a powerful management agent software framework for network elements, driving the industry adoption of NETCONF and YANG Network Configuration Protocol and data structure
* The position as a Software Engineer is expected to have good technical knowledge and to work both independently and within the team to solve complex tasks, implementing and troubleshooting in our core Erlang platform carrying out the below:
   * Development and troubleshooting of core Erlang components
   * Delivering high quality code that is both tested and testable
   * Analyzing and solve complex problems as a part of a brilliant team
   * Developing business-critical high availability systems
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
