### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Android Developer ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3163]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* At least 3 years of experience in mobile application development on Android and using different frameworks such as Native Android, Flutter, React Native, etc
* Strong OOP design and programming skills in Kotlin and Java
* Strong understanding of Android application architecture such as Clean architecture, MVVM, Modularization, Live data, Data Binding
* Experience in Bluetooth Low Energy (BLE)
* Experience in working with IOT devices is a plus
* Familiar with Map API like Geocoding, Reverse Geocoding, Distance, … such as Mapbox, Google Map, …
* Good English communication
### You’ll be responsible for
* You are motivated by the idea of implementing mobile solutions and bringing clients’ mobile products to life. You enjoy exploring new technologies and have experience developing mobile projects on your own or in our global teams.
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
