### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Senior Full-stack Developer (.NET/Angular+) ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3164]
## Location
* Ho Chi Minh, Vietnam
## Requirements
* A University Qualification in Computer Science, Software Engineering, or a related degree.
* Minimum 5 years of experience in software development
* Strong knowledge of Microsoft Development Stack: C#, .NET, .NET Core, ASP.NET, MVC
* Web development knowledge:
 *HTML, CSS, JavaScript, jQuery, Bootstrap and TypeScript.
 * At least > 2 years of experience with responsive web frameworks, in particular Angular 2+, also including, Kendo, Node.js or React Js
 * Responsive UI
 * Development of web application for desktop and mobile devices
* Database knowledge:
 * Strong knowledge of Microsoft SQL
 * T-SQL
 *  Performance tuning and profiling
* Strong understanding of and appreciation for globalisation and localisation principles and techniques
* Experience in development of RESTful Web API (JSON, XML), Unit Testing
* Good knowledge of programming patterns and principles e.g., SOLID, DRY, Repository Pattern, UnitOfWork
* Knowledge of relational and/or non-relational data stores, such as PostgreSQL, Elasticsearch, MongoDB or Cassandra
* Familiarity with containerised and serverless deployment models, including Docker, Kubernetes, ECS and Lambda is as plus
* Knowledge of Atlassian Jira, Atlassian Confluence, TFS, Git
* Knowledge and/or experience with cloud platforms: AWS, Azure
* Experience in working with Agile/Scrum methodology
* Fluent English Communication
### You’ll be responsible for
* Extending and maintaining this application, as well as the services, APIs and other applications for web and mobile platforms
* Collaborating with other team members, as well as to provide support for internal, customer and partner users
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
