### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Java Developers ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3165]
## Location
* Ho Chi Minh,Vietnam
## Requirements
* At least 4 years’ experience within software development
* Strong in Java Core development
* Experience in data modelling
* Experience in networking and Linux system
* Experience in Git, Jenkins, TDD, CI/CD
* Good skills in English
### You’ll be responsible for
* We are looking for experienced and highly enthusiastic Java Developers to work on Java project. Implementing and configuring virtual or physical network devices, developing system and testing, this is the common task.  
* By joining our team, you will be responsible for development, maintenance and troubleshooting in production systems.  
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
