### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Embedded Software Developers (C, Linux) ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3166]
## Location
* Ho Chi Minh,Vietnam
## Requirements
* Experience developing production-quality C code
* Experience developing embedded Linux kernel drivers
* Good understanding on CPU-base architecture, Embedded System, and boot loaders
* Have some basic working knowledge of UART, SPI, I2C, EPROM, SRAM, and Flash Memory
### You’ll be responsible for
* Bringing up new hardware
* Designing, implementing and testing Linux kernel drivers and firmware for the new hardware platforms of the Driver Monitoring solution
* Designing, developing and problem-solving embedded systems – including prototyping of concepts as well as optimizing and improving system architecture
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
