### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ Embedded Software Developers (IoT, C/C++) ] - [ HCM ] - [ FT ] 

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3167]
## Location
* Ho Chi Minh,Vietnam
## Requirements
* Experience developing IoT devices that interact with AWS IoT Core
* Experience developing IoT devices using MQTT and/or other IoT messaging protocols (e.g. Mosquitto MQTT Broker)
* Experience with Embedded web application development
* Experience with secure web protocols like HTTPS, TLS
* Experience developing Embedded Linux devices using C/C++
### You’ll be responsible for
* Join our team of skilled engineers in architecting, developing and testing cloud connected embedded computer vision devices in the automotive space. You will use your IoT experience to architect and develop quality solutions for device data/event reporting, administration, monitoring and over-the-air updates.
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
* Activities such as; sport & music clubs, yoga & piano classes
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
