### ISSUE TITLE
[ DEK TECHNOLOGIES VIET NAM ] - [ C++ Software Developers ] - [ HCM ] - [ FT ]

### ISSUE THREAD

**Issue by tuuyenz** [awesome-jobs/vietnam#3168]
## Location
* Ho Chi Minh,Vietnam
## Requirements
* At least 2 years of experience with C++ Programming Language
### You’ll be responsible for
* Understand the requirement, design, and implement new features
* Troubleshoot issues, suggest and implement solutions
* Continuously improve together with the team
### Why it would be awesome to work with us
* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check-up
* Annual company trip & annual family day
### Contact
Homepage: https://www.dektech.com.au/
Fanpage: https://bitly.com.vn/rf76ie
Full JD and apply here: https://bit.ly/CareerDEK
Email: dek-vn-ta@dektech.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
