### ISSUE TITLE
Planday - Senior iOS Developer - Hanoi - FT

### ISSUE THREAD

**Issue by khoiln** [awesome-jobs/vietnam#317]
## Location
- Hanoi, Vietnam
- Fulltime
## Salary Expectation
- Up to 2000 USD / month
## What you'll be doing
- Working in an international environment.
- Be part of a strong creative cross-functional product team, designing, building and testing new functionality.
- Collaborate with cross-functional teams to define, design, and ship new features.
- Creating clean, concise, robust, maintainable code.
- Work on bug fixing and improving application performance.
- Work in a dynamic team oriented environment using agile methodologies.
- Continuously discover, evaluate, and implement new technologies to maximize development efficiency.
## Requirements
- Experience with iOS Development lifecycle.
- Experience working with native iOS frameworks such as Core Data, Core Animation, Core Graphics and Core Text.
- Solid understanding of computer foundation.
- Using Git like a champ.
- Excellent problem solving
- Having at least 1 well executed app on Appstore.
- Fluent English (both verbal and non-verbal). English is our company language.
- Lastly the office sport is football so big + if you are in to it as well.
## Benefits
- Macbook Pro provided
- A key part of an exciting international growth journey
- Opportunities to learn and develop your skills and career through hackathons, meetups, colleagues and other places.
- Great colleagues and a social working environment
- Beverages and snacks of your choice.
- Great location in central Hanoi, you'll feel right at home.
- Lots of team and community events
### Contact

Khoi: khoi@planday.com

**Comment by khoiln** [comment]
@huydx Please help add tag i.e "Mobile, iOs". Thanks alot

**Comment by huynhquancam** [comment]
@khoiln Thanks for posting! Could you please specify more details about Planday?

For example this is a good company description: https://github.com/awesome-jobs/vietnam/issues/132
