### ISSUE TITLE
Pangara - Javascript/React Developer (freelancer) - Remote/Saigon - PT

### ISSUE THREAD

**Issue by PangaraTeam** [awesome-jobs/vietnam#318]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Partly Remote as ***you will be sitting at the client's office for 2-3 days/week in District 11, Saigon as the full-time freelancer.***

## Salary Expectation

* Starting from 15 USD/hour and could be negotiated due to project requirements

## Requirements
* 3+ years experience designing and developing web interfaces
* 1+ years experience building web applications using React
* Significant experience in HTML5, CSS3, JavaScript, JQuery, AJAX, JSON
* Familiar with frontend web frameworks such as Bootstrap, AngularJS, Ember.js
* Experience with responsive design principles for web sites
* Proficiency with Adobe Creative Suite, Photoshop or other image editing software
* Experience in agile development disciplines and principles (preferably Scrum)
* Working knowledge of Git (or similar version control systems)
* Selfmotivated, ability to work independently and efficiently with a strong attention to detail and accuracy
* Ability to multitask and work across multiple projects
* Very good written and verbal English skills.

## Responsibilities
* Design and develop web applications with pixel perfect quality in regards to navigational layouts and appearance using the React framework
* Debug and troubleshoot layout and scripting issues across a variety of desktop and mobile browsers.

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by joneslee85** [comment]
Closed. We do not allow this freelancing model here. Thanks for your understanding.
