### ISSUE TITLE
JobSeekervn - Senior QA Engineer - Ho ChiMinh

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3184]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* $1500 - $1800/month 

## Requirements
* Demonstrate experience in test areas: web, mobile app, functional and exploratory testing.
* Experience in translating requirements and acceptance criteria into tests and test scripts.
* Have knowledge about API, database
* Solid understanding of Agile development process, software QA methodologies, tools and processes
* Hands-on technical skills to implement and maintain automation test
* Ability to collaborate, make questions and communicate directly with colleagues in US (solution-oriented)

### Responsibilities
* Participate in review and analyze the project requirement to understand test objectives, clarify unclear aspects of requirement, provide input on testability of requirements and reasonable estimation
* Collaborate and engage with the teammates to build effective test design to support developers in implementing and self-testing
* Able to assist team to let them do test ticket as well as improve testing skills/mindset
* Develop the automation scripts, training test automation for engineers on new coding and testing methodologies, guidelines, and best practices.
* Contribute to the building of continuous Integration (CI) environment and ongoing processes
* Adapt/handle changes within sprint effectively
* Provide the testing approach, develop the effective test strategy and able to build automation framework from scratch
* Play as a mentor (prefer as a coach) to guide the Agile Testing mindset and techniques to less experience QA and Scrum teammates

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
