### ISSUE TITLE
Ascenda Loyalty - Lead iOS Engineer (Swift) - HCMC - FT

### ISSUE THREAD

**Issue by longkt90** [awesome-jobs/vietnam#3186]
## Location

* Sala Saritown, Thu Duc city, HCMC, Vietnam

## Salary Expectation

* US$4000 - $6000 / month 

## Requirements
You are a good fit if:
* At least 7+ years of hands-on experience in building and releasing high quality iOS apps.
* You have previous experience in leading a iOS / Mobile Engineering team or squad. 
* You have deep technical hands-on expertise in building iOS apps - and have previously developed apps used at scale. 
* You have experience with iOS frameworks.
* You are familiar with architectures like MVC, MVP, MVVM
* You are proficient in Swift
* You have experience in Swift UI (plus)
* You have deep knowledge in areas such as mobile performance and security.
* You understand what it takes to build user friendly and robust mobile apps. 
* You have experience in cross-platform mobile development frameworks such as React Native or Flutter.
* You are a strong and self-driven team player, with ability to work at pace in a dynamic organization.
* You enjoy working with cross-functional teams in a multicultural environment.
* You have a strong sense of ownership, care deeply about code quality and maintainability

## Job description

We are looking for experienced iOS Mobile Engineers to help bring our beautiful loyalty and banking products to the smartphones of our customers. We're adopting a mobile-first approach in delivering our new fintech products to the world - and you will play an important role in helping us achieve our vision of building innovative world-class fintech products, centred around amazing loyalty propositions.

As a Lead Mobile Engineer, iOS, you will:

* Help drive the technical vision, roadmap and architecture of our iOS apps together
* Lead a team of talented Mobile Engineers to build and delivery high quality iOS apps in the banking and fintech space
* Work in cross-functional teams across the organization to build and launch high-quality product features.
* Work closely with our UX and product design teams to collaborate on designing and implementing great user experiences.
* Participate in our software development lifecycle, including participating in code reviews and sprint planning sessions.
* Drive and contribute actively in technical discussions with other Ascenda engineering teams to deliver complete end to end features.
* Partner with our QA team to define test strategy and setup automated testing.
* Drive continuous improvement for our mobile codebase and architecture.
* Secure our mobile apps, together with our in-house security engineers to ensure that our customers can transact on our apps confidently.
* Establish best-practices for the mobile and iOS teams, such as, coding style guides and release management.
* Mentor and provide technical leadership to other engineers in the team and across the engineering organisation.

This role is open for our Vietnam Office, located in Ho Chi Minh, District 2. 

### Contact

https://careers.ascendaloyalty.com/o/lead-mobile-engineer-ios

Check out other roles we are hiring: https://careers.ascendaloyalty.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
