### ISSUE TITLE
[JobSeekervn] Senior Data Analytics Engineer - HCMC -  $1800 - $2400

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3189]
## Location
* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $1800 - $2400/month 

## Requirements
* 5+ years working with relational database systems such as PostgreSQL, MySQL, MSSQL, etc.
* 5+ years developing in Python or similar C-based language.
* Experience designing and implementing module/interface contracts with Software teams to define the scope of app-to-warehouse integration.
* Demonstrated experience with designing and building dimensional data models, ETL processes, applied data warehouse concepts and methodologies.
* Experience delivering and/or maintaining data warehouses.
* Demonstrated experience using cloud-based data services in AWS/ Azure/ Google BigQuery.
* Experience with cloud data warehouse for storing data - Amazon RedShift.
* Experience designing and document the database effectively, including data flows, flowcharts, data dictionaries, etc.
* Good communication skills in English.

### Responsibilities
* The Data Analytics Engineer acts as the bridge between Data Analysts and Data Engineers.
* Partner with business stakeholders to answer questions with data, build dashboards and reporting, and carry out exploratory analysis.
* Developing and maintenance Data Lake & Data Warehouse/ ETLs for transferring data between application databases.

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
