### ISSUE TITLE
Pangara - PHP Developer Freelancers - Remote/Saigon - PT

### ISSUE THREAD

**Issue by PangaraTeam** [awesome-jobs/vietnam#319]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Partly Remote as ***you will be sitting at the client's office for 2-3 days/week in District 11, Saigon as the full-time freelancer.***

## Salary Expectation

* Starting from 15 USD/hour and could be negotiated due to project requirements

## Requirements
* 3+ years experience in PHP and related technologies (e.g. Symfony framework)
* Solid knowledge and understanding of REST API development with experience in micro services
* Demonstrated experience with SQL and relational database systems (e.g. MySQL
* Understanding of scalable web applications and APIs (caching, clustering, cloud computing, etc.
* Experience with Git (or similar version control systems
* Knowledge of unit, functional and integration testing (tools, best practices, BDD
* Wellversed in agile development disciplines and principles (preferably Scrum
* Excellent interpersonal and communication skill
* Positive and pragmatic attitude with a focus on finding solutions to problem
* Very good written and verbal English skills

## Responsibilities
* Develop and integrate custom REST APIs (micro services) written in PHP
* Profile, analyze and resolve performance bottlenecks
* Research, define and implement new and innovative features
* Work with stakeholders to discover requirements and identify core problems to be solved
* Participate in sprint planning meetings to properly scope and provide detailed estimates for proposed features
* Design, develop, test, deploy and maintain end-to-end software solutions

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by joneslee85** [comment]
Closed. We do not allow this freelancing model here. Thanks for your understanding.

**Comment by vtgroupvn** [comment]
do you ready to open new contractor?
