### ISSUE TITLE
KVY Tech - Junior Ruby on Rails Developer - HCMC or Remote - FT

### ISSUE THREAD

**Issue by khoido** [awesome-jobs/vietnam#3191]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* 18-26tr VND

## You’ll be responsible for

* Design and build reliable code, from backend to frontend.
* Involve in communicating with customers to understand their ideas and requirements
* Write clean, human-readable code with unit tests
* Provide training and support to internal teams
* Collaborate with Front-end developers to integrate user-facing elements with server-side logic

## Skills

* 1+ years of professional experience building and deploying scalable web applications in Ruby on Rails
* Good at Object-oriented Programming (OOP)
* Good at triaging bugs and troubleshooting issues
* Experienced with Relational Databases and SQL
* Rather good at speaking and writing English
* Experience or eagerness to learn other languages such as NodeJS, Elixir is preferred
* Experience or eagerness to learn ReactJS is preferred

### Why it would be awesome to work with us

* HYBRID WORKING
* 13-month salary
* 15 days off a year
* Modern and challenging startup environment
* Opportunities to learn and grow through training courses
* YOLO - Holidays on Birthday, with a special gift
* Company outing & parties

### Contact

* Homepage: https://kvytechnology.com
* Send your CV to this email address: long@kvytechnology.com
* Email subject: [Junior Ruby on Rails developer] - Your name

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
