### ISSUE TITLE
[ATALINK]_Senior Reactjs Developer_HCMC 

### ISSUE THREAD

**Issue by NhiPhi** [awesome-jobs/vietnam#3194]
## Location
3rd Floor, QTSC Building 1, Street No. 14, Quang Trung Software city, Tan Chanh Hiep Ward, District 12, Ho Chi Minh

## Salary Expectation
$1500 - $2200

## Requirements and Skills
At least 3+ years of working experience with ReactJS in developing scalable and robust software applications in web environments with exposure to frontend stacks
Good understanding of JavaScript, ECMAScript6+ & TypeScript
Good experience with HTML and CSS
Thorough understanding of ReactJS and its core principles
Have working knowledge of Unix/ Linux environment

### Must Have
Reactjs
Javascript

### You’ll be responsible for
Understand and analyze the requirements / designs clearly
Implement features from design specifications and deliver code with high quality
Perform code review, code refactor
Ensure components and the overall application are robust and easy to maintain
Contribute to all aspects of the product development process, from specification and  design, throughout integration, release and maintenance
Continuously discover, evaluate, and implement new technologies to maximize development efficiency

### Why it would be awesome to work with us
Attractive salary and benefits (13th salary, distinguished employee of the quarter and year, seniority award…)
Performance appraisal twice a year
Healthcare and accident insurance
Lunch allowance, OT meal allowance
Various training on best practices and soft skills
Team building activities in every summer, company trip, big annual year-end party every year, etc
Fitness & sports activities: football, tennis, table-tennis, badminton…
Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
Support for personal loans such as: home loan, vehicle loan, tuition fee…

### Contact
Yen Nhi (Ms.)
Homepage: https://about.atalink.com/
Email: nhipty@atalink.vn
SkypeID: https://about.atalink.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
