### ISSUE TITLE
[ATALINK]_Middle Data Engineer_HCMC

### ISSUE THREAD

**Issue by NhiPhi** [awesome-jobs/vietnam#3195]
## Location
3rd Floor, QTSC Building 1, Street No. 14, Quang Trung Software city, Tan Chanh Hiep Ward, District 12, Ho Chi Minh

## Salary Expectation
$1200 - $1500

## Requirements and Skills
* At least 1-2 years of experience in working with database (PostgreSQL/SQL Server)
* Good VBA skills
* Have knowledge of Python, Java, NodeJs… is a plus
* Problem solving and Analytical skill
* Highly effective working in a team as well as working independently 

### Must Have
* PostgreSQL
* SQL Server

### You’ll be responsible for
* Store, backup and restore database as requested
* Import/ Export data from database as required
* Write/ Update Macro / Script to help automate project processes
* Create/ Update checklist to ensure data quality
* Receive and store input data from clients, undertake assessment and write reports of data quality as required
* Create report templates to meet project's needs
* Write technical documents/ materials/ instructions for the project team 

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguished employee of the quarter and year, seniority award…)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Lunch allowance, OT meal allowance
* Various training on best practices and soft skills
* Team building activities in every summer, company trip, big annual year-end party every year, etc
* Fitness & sports activities: football, tennis, table-tennis, badminton…
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Support for personal loans such as: home loan, vehicle loan, tuition fee…

### Contact
* Yen Nhi (Ms.)
* Homepage: https://about.atalink.com/
* Email: [nhipty@atalink.vn](mailto:nhipty@atalink.vn)
* SkypeID: live:63943ea47dd3b5eb

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
