### ISSUE TITLE
HipVan - NodeJS Developer (ReactJS, NextJS, NestJS) - Saigon - FT

### ISSUE THREAD

**Issue by techhipvan** [awesome-jobs/vietnam#3197]
## Location

Saigon, Vietnam

## Salary Expectation

Up to $2500

## Requirements & Skills
* 3 years or more experience in web application development
* English reading skill to understand spec documents, requirements, etc.
* English writing skill to communicate by text during development
* The following skills and knowledge:
  o At least 1 Javascript frontend framework: ReactJs, Vue.js, Angular, etc.
  o At least 1 Node.js backend frameworks: NextJS, NestJS, Express.js, AdonisJS, etc.
  o Any Javascript testing frameworks: Jest, Mocha, etc.
* Experience with Typescript
* Experience with any of these Databases
  o NoSQL DB: MongoDB, Firestore etc.
  o Relational DB: PostgreSQL, MySQL, MariaDB, etc.
* Experience in team development with Git
* Experience with Docker in software development

## Desired
* Experience with software design is desirable
* Experience with development team management
* Following skills and knowledge
  o Mobile App development skills (React Native, Flutter, Swift, Kotlin, etc)
  o Experience with AWS is highly welcomed (Experience with Google Cloud Platform or Microsoft Azure is also welcomed)
  o Experience with Kubernetes is highly welcomed
  o Experience with CI tools is highly welcomed (Github Actions, Circle CI, Jenkins, etc)
  o Any experience with other languages and frameworks e.g. Ruby, Rails, Python, etc.

### Must Have

* NodeJS, ReactJS, NextJS
* MongoDB

### You’ll be responsible for

* Work closely in teams to develop software
* Design system architectures according to our customer's needs
* Develop reliable, scalable and maintainable applications based on specs
* Evaluate UI / internal logic with team members and share implementation ideas
* Cooperate with QA/QC members to write test code and perform various tests
* Research new technologies or techniques to develop better applications

### You can bring

* Casual working environment
* No overtime
* Free to express your opinions and develop your skills

### Why it would be awesome to work with us
* Attractive income based on individual ability of each employee
* Will be provided tools and equipment suitable for work e.g. MacBook Pro
* Employees are encouraged to express their own thoughts freely, and are to develop own individual ability
* Access to new and diversified technologies
* Health insurance provided($350/Year)
* Marriage bonus, childbirth bonus
* Always have snacks, tea, and coffee available in office
* Paid holiday: 12 days/year, unused paid holiday will be paid according to company’s policy
* Join regular staff parties, annual company trip

### Contact
Website: https://www.hipvan.com
Contact: Tuong Bui
Email: tuong_at_hipvan_dot_com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
