### ISSUE TITLE
Pangara - Automation QA Engineer Freelancers - Remote/Saigon - PT

### ISSUE THREAD

**Issue by PangaraTeam** [awesome-jobs/vietnam#320]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.

## Location

* Partly Remote as ***you will be sitting at the client's office for 2-3 days/week in District 11, Saigon as the full-time freelancer.***

## Salary Expectation

* Starting from 15 USD/hour and could be negotiated due to project requirements

## Requirements
* Minimum 4 years of experience as a software QA or test engineer with demonstrated experience in web applications and APIs (micro services)
* Familiar with technologies like PHP, Selenium, SQL
* Strong experience in automation testing
* Experience in building and maintain automation framework is a big plus
* Experience in functional, integration and performance testing
* Experience in developing test cases, test plans and performing testing
* Passion for product quality and uncovering hard to find scenarios and bugs
* Attention to details and a knack at finding edge cases
* Experience in QA of highly scalable, distributed and high performance applications and APIs
* Experience in delivering software products using an Agile methodology
* Strong research, problem solving and troubleshooting ability.
* Self-motivated and able to grasp issues quickly and make educated, critical judgment in the absence of complete information

## Responsibilities
* Own quality assurance (functional, integration, and performance) end-to-end for key products
* Hands on testing (both automation and manual)
* Participate in Agile scrum and estimation/planning session
* Define the test plan and strategy
* Define, observe, analyze and report on key QA metrics
* Work closely with product owners and engineers to develop project schedules, execute test plans and cases, and deliver high quality products
* Act as a strong advocate for quality in the product development process for software engineering
* Build and maintain automation framework as well as troubleshoot the technical issues in the team

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by joneslee85** [comment]
Closed. We do not allow jobs that is posted on someone's behalf.
