### ISSUE TITLE
Cốc Cốc - Software Engineer (C++/Go/Rust/Java) - HN/HCMC - FT

### ISSUE THREAD

**Issue by CocCocRecruitment** [awesome-jobs/vietnam#3201]
## Location

* Hanoi, Vietnam
* Hochiminh City, Vietnam

## Salary Expectation

* $1,000 - $2,500/month (Junior - Senior Level)

### Must Have

* Good knowledge of your current programming languages (we prefer one of the following languages: C++/Golang/Java/Rust).
* Strong knowledge of algorithms and data structures.
* Knowledge about computer science (networking, thread/process, OS memory management, CPU, DB, load balance, caching, etc).
* Strong in analytics and problem solving techniques.
* Able to work independently as well as in collaborative mode with minimum supervision.
* Work productively even under pressure.
* Excellent communication in writing and reading English.

### Ideally

* Strong proficiency with backend development, service-oriented architecture technology, SQL and NoSQL datastores.
* Understanding of online advertising technology and RTB is a strong plus.
* Experience with designing/developing Linux/Unix environments
* Willingness to learn and able to pick up new technology or new concepts fast.

### Responsibilities

 Cốc Cốc develops a highly scalable, all-in-one advertising and marketing platform called Cốc Cốc Ad Platform where Advertisers, Agencies and Publishers can easily create, optimize & publish ads to access over 24 million internet users; offers a variety of advertising and targeting options that allow advertisers to reach users in the right way, at the right time. Owing to the large and real-time stream of data, coming up with efficient and pragmatic solutions and algorithms to challenging problems will become imperative.

You will be joining our Ads Engine team working closely with Product Managers and Data Scientists to build a highly scalable system that can handle millions of requests per day, all delivered in milliseconds. In this role, you will be expected to possess solid experience working on large-scale, distributed and low-latency systems. You’ll acquire a deep technical understanding of the platform, work with our cross-team to learn about the business and technical analytics requirements and translate them into a production system.

### You’ll be responsible for

* Plan, design and develop components in our Cốc Cốc Ad platform, analyze and improve our algorithms and models to increase the revenue for the company.
* Drive and implement technical solutions to a variety of features that serve high throughput and also high availability.
* Document and improve the solutions over time.
* Evaluate and identify new technologies for implementation.
* Communicate with our product and data teams to understand the analytics requirements.
* Respond and follow up to incorporate feedback and draw new insights.
* Prioritize tasks to meet multiple goals.

## Why it would be awesome to work with us
Few countries have local challengers in the search and browser space. Vietnam is one of those countries thanks to Cốc Cốc. There are a lot of challenges in competing against dominant global players, but also lots of rewards when we succeed.

### Professional growth:
What we are doing is difficult. This is why there are a lot of opportunities for you to learn and grow with support from a mix of the learning & development programs
You will work alongside talented team members who have a unique skill set and expertise in this market
Coc Coc is a Vietnamese company but you will be working in an international environment with team members/partners/customers who are local and international
 
### Compensations and benefits:
Attractive salary and bonus scheme with 13th-month salary. 
Performance review twice/year
Special annual leave policy with a minimum 20 days/year (including 1 day off on your birthday)
Great Trade Union benefits for your important life events such as birthday, marriage, new born child... 
Periodic medical checkup, Bao Viet Health Insurance & Health/Social Insurances 
 
### Working environment: 
A culture of flexibility and responsibility, no dress code and annual Work From Home policy
Exciting internal events to help you understand the whole business and make you part of the Cốc Cốc family
Modern and cozy kitchens with plenty of snacks and coffee/tea bars every day, to make sure energy level is high when you need it
There are many interesting hobby clubs to share your non-professional passions like English Club, Yoga, Football and many other clubs are forming ...

### Contact
Homepage: https://careers.coccoc.com/job/c-software-engineer-ads-engine
Giang Trịnh - giang.trinh@coccoc.com (Skype: jangin.kan)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
