### ISSUE TITLE
JobSeekervn - Tech Lead - Hanoi - Fulltime 

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3209]
## Location
* Hanoi, Vietnam
* Fulltime

## Salary Expectation
* $2000 - $3000/month 

## Requirements
●         At least 3+ years of professional experience in PHP, NodeJS and Python.

●         Moderate knowledge of React Native & ReactJS

●         Understand core backend methodologies like REST, JWT, OAuth2.0, Design Patterns.

●         Experience in leading a team of software engineers.

●         A moderate level of English is preferred.

●         Proven experience in a similar role is a must.
 

### You’ll be responsible for

●         Lead and guide a team of 8-10 software engineers to deploy code up to high standards.

●         Develop technical design specifications for complex projects and implement them.

●         Delegate tasks to achieve daily and overall goals based on our product roadmap.

●         Continuously discuss and work with a dedicated product team using SCRUM methodology to ensure releases are deployed with a standard our customers love.

●         Motivate team members and be transparent with the team about challenges, failures, and successes through bi-weekly retrospective meetings.

●         Work closely with the Product Owner and CPO on the product technology strategy.

●         Experiment with new technologies to improve the platform.

### Contact
Email: nhiha@jobseeker.vn 
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
