### ISSUE TITLE
[PostCo] - [Junior Software Engineer] - [Sai Gon] - [Hybrid]

### ISSUE THREAD

**Issue by Wolong16** [awesome-jobs/vietnam#3210]
## Location

* Saigon, Vietnam
* Hybrid

## Salary Expectation

* $1000 - $1500

## Requirements
* Ruby
* Ruby on Rails
* React Native
* 1+ years Software Engineering experience

### Must Have

* Self-taught developers who are able to prove his / her abilities through group or personal projects.
* Comfortable programming in any programming language and willing to learn our stack - Ruby on Rails, React, and React Native.
* Solid conceptual understanding of full-stack software development including system architecture, web serving infrastructure, and database design.
* Product-minded: committed to building the best user experience.
* Great interpersonal and communication skills and comfort working within a small team.
* Decent English speaking and writing.

### You’ll be responsible for

* Assume ownership of features end to end through development, testing, and release.
* Design and contribute to make PostCo 360 a better, more powerful return software across the globe.
* Enjoy being a generalist working across the entire stack: frontend, backend, and anything it takes to solve problems and delight users.
* Take pride in writing clean and maintainable code.
* Open-minded and opinionated - able to voice out and take opinions in polite and objective manner.

### Why it would be awesome to work with us

* Flexible vacation time (Unlimited paid day leaves)
* Wellness, gym, and fitness stipends (Self-care is important!)
* Insurance coverage
* Work from home flexibility
* Access to our office space in WeWork E. Town Central to meet and collaborate with teammates
* Annual and occasional quarterly retreats

### Apply
[Homepage: ](https://postco.co/jobs/junior-software-engineer-vn)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
