### ISSUE TITLE
MIS Global - Frontend Developer - Ho Chi Minh - FT/Freelance

### ISSUE THREAD

**Issue by CherishMIS** [awesome-jobs/vietnam#3211]
## Required skills:
*  HTML/CSS/JavaScript
* CSS Preprocessor Experience (Sass/Less)
* Responsive Design
* Design tool experience (Figma/Sketch/Adobe XD/Axure/etc.)
* Git
* Formal Agile (SCRUM preferred)
* Strong experience with Reactjs
* CSS-in-JS development experience
* TypeScript development experience
*  NextJs development experience
* Have a good understanding of REST APIs and web integration with backend systems
* Good understanding of SPAs
* Solid soft skills: group discussion leading, teamwork, problem-solving, presentations
* Must be independent, responsible, and self-motivated with the ability to learn and achieve superior results
* Possessing strong methodologies when researching new technologies
* P/s: Don't worry If you can't meet all of these, If you're willing to learn, we're willing to have you join us.
 
## What we offer you:
* Tet bonus
* December bonus (13th salary)
* Bonus 1 month salary (14th month salary) for 2 years of service
* Bonus 2 months salary for 3 years of service (14th and 15th salary)
* Healthcare support, annual health check
* Unlimited paid days off
* Allow to work from home/ Remote
* Device equipment
* Whoopie Fridays where people can meet, chat, and exchange knowledge
* Daily happy hour
* Quarterly team building activities, summer company trip

### Contact
Email: ngan.le@mis.studio

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
