### ISSUE TITLE
ZaloPay - Backend Engineer (Java, Go), Accounting Engineering - Saigon

### ISSUE THREAD

**Issue by anhldbk** [awesome-jobs/vietnam#3212]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

### You will

* Design, build, and maintain large-scale services, data pipelines, tooling and systems. 
* Make direct business impact in some of ZaloPay’s most mission critical business domains including Accounting, Finance and Business Operations. 
* Build strict controls across pipelines to ensure super high accuracy for all financial transactions. Ensure accurate, reliable, and timely financial reporting delivered to a single source-of-truth financial data warehouse
* Work in an Agile & collaborative environment involving different stakeholders

## You may be fit for this role if you

* Have delivered distributed systems of large scale
* Write high quality & maintainable code. We work mostly in Java, Go and JavaScript. However, languages are the intellectual shell.  We care much more about your mindset & general engineering skills
* Are interested in solving business problems for ZaloPay’s Accounting team.

## The following skills would be nice to have

* Experiences with big-data technologies such as Apache Spark, Presto, Apache Kafka, and Apache Flink, and OLAP
* If you know how to work with K8S or cloud services, e.g GCP, AWS... it's really great.

## References

* [Original post](https://career.vng.com.vn/co-hoi-nghe-nghiep/chi-tiet/55.3537-zalopay-senior-software-engineer-accounting-engineering-team-java-golang#list)
* [ZaloPay's Engineering Blog](https://medium.com/zalopay-engineering)
* [Our Github](https://github.com/zalopay-oss/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
