### ISSUE TITLE
[REMOTE- SENIOR NODEJS DEVELOPER] - FT

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3213]
## Location

* Remote

## Salary Expectation

* $4000-6000/month or range

## Requirements

Must have:
- Strong experience with NodeJs, SQL/NoSQL 
- Experience deploying cloud resources on AWS 
- Proficiency in spoken and written English 
- 3+ years work experience in back-end or full-stack engineering of web applications
--
Nice to have:
- Degree in CS or STEM-related field 
- Experience with WebSockets and Solr/ElasticSearch etc 
- AWS associate or professional certification 
- Worked in fast-growing tech companies 
- Passion or knowledge of 3D animation or game engines (e.g. Maya, Blender, Unity, Unreal Engine etc)

### Responsibilities

General Description:
- Responsibilities include implementing microservices, designing data models and integrating user-facing code with the frontend.
Responsibilities:
- Implement backend microservices to support multi-user collaboration on the browser
- Contribute to cloud architecture discussions and implementation
- Design, implement and maintain existing data models and database migrations
- Write robust tests for CICD, development and production releases
- Integration with third party APIs e.g. Stripe

Report to : CEO
Processing: 1 programming assignment -> Technical interview -> Final round interview

### Why it would be awesome to work with us
Motivation3D animation remains beyond the scope of most internet users today. Existing software takes months to learn, offers little to no collaboration, and priced at $1500+ a year. Open source alternatives like Blender have not fared better beyond price.A great analogy is Canva and Graphic Design. 7-8 years ago (before Canva was introduced), Graphic Design was limited to professionals who knew Photoshop. Canva now has close to 20 million monthly active users, all by making things simple for users to create designs. We see a lot of parallels with the state of 3D animation today.MissionOur ultimate goal is to make 3D animation much simpler and accessible than its current state. To date, we have built the first 3D animation software on the web browser with animation curves, inverse kinematics and 3D human pose estimation ("AI Motion Capture"). Our goal is to leverage the cloud to allow users to work collaboratively on 3D animation for the first time possible. Our premise is similar to Figma's - the web browser will eventually be the default platform for collaborative media and editing (just like Google Docs).Current TeamCJ Looi - Co-founder, Previously Head of Deep Learning and Computer Vision at DorabotCyril Nie - Co-founder, CS @ UCLZoe - Frontend EngineerAndrew Butt - Senior Engineer, Core contributor of Babylon.jsAdvisorsMichael Gryseels - Strategic Advisor, President of True Digital Group and the former managing director of McKinsey SingaporeShaun Johnston - Animation Advisor, founder of TheCGBros, 3.2+ million subscribers on YoutubeFunded byCocoon Capital - Seed Investor, most companies in their Portfolio reach Series A and beyond Entrepreneur First - Pre-seed Investor, backed by Peter Thiel, Reid Hoffman and GreylockThe candidate will be processing all rounds according to Singapore time.
### Contact:
Skype: Huehuenoivu
Zalo/Tele: 088 600 5769

**Comment by 7x7x7eq51** [comment]
Dream job :)
