### ISSUE TITLE
NAB - Sr/Medior NodeJS - Hybrid/Hanoi - FT

### ISSUE THREAD

**Issue by Lynnduong90** [awesome-jobs/vietnam#3214]
## Location

* Ha Noi, Vietnam
* Hybrid working

## Salary Expectation

* Up to $3000

## Requirements
* 3-5 years' experience working in Software Development:
* Solid experience in JavaScript ES6 (import/export of Modules, promise, async wait, callbacks) and TypeScript working with Node.js;
* Solid experience in using Jest Node.js unit testing framework.
* Solid experience in designing & developing RESTful APIs and microservices-based systems;
* Experience in Agile development environments;
* Familiar with Front-End frameworks, specifically React.js;
* Well-versed in writing structured, well-documented, maintainable, and clean code;

### Must Have

* Good problem-solving and analytical skills;
* Good understanding of standard Software Engineering processes, Testing, and Agile methodology;
* Strong English communication skills (both verbal & written), especially in the global software development environment.

### Ideally

* Experience in AWS and Containers (ECS, Kubernetes, Docker);
* Experience in the Banking or Financial Services industry;
* Experience in scripting (Bash, Python, Groovy, PowerShell, AWS CLI);
* Experience with developing Java Microservices in SpringBoot;

### Responsibilities

* Design, develop, review, implement, and manage application code and services for the production and pre-release environments in Node.js;
* Design, develop, review, implement, and manage continuous integration, build management and deployment scripts, systems, and any code as required;
* Participate in Agile software development, prototyping, and code review with international development teams to build scalable microservices-based products;
* Understand the requirements of the customer or business and utilize this knowledge to develop applications that are consistent with this;
* Work with delivery teams to achieve success through development using CI/CD and DevOps practices, processes, and tooling;
* Provide robust coding practices and solid unit and component test coverage, and code debugging.

### Why it would be awesome to work with us

* Very competitive remuneration package
* Generous private family healthcare for yourself and two family members
* A solid team behind you - great people who love what they do
* The pleasant, enthusiastic, international work environment
* Opportunity for traveling & training in Australia
* A brand new & state of the art Agile office
* Latest technologies, flexible working hours
* A promising training and career path
* Fun team activities & outing
* English learning with native English teachers

### Interesting engineering projects

* Projects in Banking sector with real users
* Standard Agile environment

### Contact
Lynn: Lynn.DuongHuong@nab.com.au (0934433526)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
