### ISSUE TITLE
[KLC] Ruby on rails developer (Remote/ Nha Trang) fulltime

### ISSUE THREAD

**Issue by Lamky8855** [awesome-jobs/vietnam#3215]
## **Location**

* Nha Trang, Vietnam
* Remote

## **Salary Expectation**

* Negotiable

## **Job Description**
* Write and maintain Ruby on Rails code
* Maintaining and troubleshooting existing web applications
* Work with the Product and Engineering teams to plan, design and develop software solutions
* Help identify bottlenecks, bugs, and devise solutions to the problems
* Work with the existing team in maintaining and troubleshooting existing web application

## **Requirements**
* Minimum 2 years using Ruby on Rails
* Basic GIT usage
* Test-driven development experience is a plus
* SQL and database design experience also favourably considered

### **Why it would be awesome to work with us**
* Social insurance & Health insurance for employee
* Annual salary review
* Professional & modern working environment
* Probationary salary: 100% of the official wage
* 12 days annual leaves, month 13th salary
* Teambuilding, Happy Friday, Birthday,….
* Participate in Lightning Talk sessions to share knowledg

**Processing:**
2 rounds : Coding test - Interview

### Contact
**Mail:** Ky.thai@khailam.io
**Mobile:** 034 649 6767

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
