### ISSUE TITLE
Frontend Developer - Ho Chi Minh 

### ISSUE THREAD

**Issue by Giang-Vo** [awesome-jobs/vietnam#3217]
## Location

* Saigon, Vietnam
* Quận1

## Salary Expectation

* Senior up to 2000$/month
* Junior up to 1500$/month

## Requirements
* You are not required to know any CSS frameworks like Bootstrap, Tailwind or something like that. However, solid knowledge of CSS api is a must. It means that you can make frontend applications by CSS itself without any  CSS framework or React UI library.
* Solid knowledge of flex and grid layout (especially flex). Understand how relative units work like rem, em, %, fr,..
* Strongly understanding how React components work and how javascript works behind the scene is a must.
* Put web performance on top of your work. Experience with performance concepts like Rendering, Caching, FCP, LCP, FID, CLS,... or willing to learn in earnest.  Understanding how SSG, SSR, SPA work.
* Willing to pick up new technology. Great interest in becoming a professional frontend developer.

## Skills
*Reactjs, Javacsript,
### Must Have
*CSS

### Responsibilities
* Work closely with the Technical Manager, Product Manager, and Product Designer to build a next-generation web application.
* Design and develop new features for the platform/system.
* Evaluate and clarify product requirements. Participate in reviewing product design.
* Maintain quality standards of excellence and ensure compliance with standards and best practices.
* Mentor junior team members.
* Build efficient and reusable code and systems.
* Identify and address performance bottlenecks.
* Participate in architecture design and code reviews.
* Communicate with other team members to determine the best solutions to difficult problems.
* Passion for performance debugging and benchmarking.

### WHY YOU'LL LOVE WORKING HERE
* An opportunity to learn at a company that is growing for regional scale (South East Asia)
* Working in a young, super talented and supportive team environment
* Attractive salary (Up to 2500 USD)
* Company trip, team building
* PTI Insurance
* Macbook Pro for Developer

### Contact
Homepage: https://www.onpoint.vn/
Send CV to hangiang.vo@onpoint.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
