### ISSUE TITLE
Pangara - Senior DBA (Freelancer) - Remote/Saigon - PT

### ISSUE THREAD

**Issue by PangaraTeam** [awesome-jobs/vietnam#322]
## About
Pangara is a freelancer platform that connects the top 2% of the freelancer network in Vietnam with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the best of the huge freelancer network in Vietnam. Our founders are Swedish, and Pangara currently have offices in Saigon and Malmö.
## Location

* Partly Remote as ***you will be sitting at the client's office for 2-3 days/week in District 11, Saigon as the full-time freelancer***.

## Salary Expectation

* Starting from 15 USD/hour and could be negotiated due to project requirements

## Requirements
* 3+ years experience of SQL Database Server Administration, preferably MySQL
* Experience with Performance Tuning and Optimization (PTO)
* Excellent interpersonal and communication skills
* Positive and pragmatic attitude with a focus on finding solutions to problems
* Very good written and verbal English skills

### Must Have

* Database Administration
* Performance Tuning and Optimization

### You’ll be responsible for

* Perform database administration of the clients database setup using mySQL
* Be responsible for the implementation, configuration, and performance of the database system
* Be responsible for the development and sustainment
* Independently analyze, solve, and correct issues

## Contact
To apply for this project or asking for further information, kindly contact us at:

> ***Ms. Lan Anh, Talent Specialist***
> Email: `talents {at} pangara {dot} com`
> Skype: `mary.trananh`
> [http://pangara.com](http://pangara.com)

## Looking for more freelance projects?
You can have access to our curated list of freelance projects today by becoming a Pangara Talent. Create an account on [our platform](http://pangara.com) and update your profile to get started. Our Talent Specialist team will contact and guide you through the qualification process.

**Comment by hieuk09** [comment]
Hi @PangaraTeam, could you please update the job post to comply with our template?

**Comment by PangaraTeam** [comment]
@hieuk09 We just updated, thanks for your inform.

**Comment by joneslee85** [comment]
Closed. We do not allow this freelancing model here. Thanks for your understanding.
