### ISSUE TITLE
Chợ Tốt - Data Engineer 

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#3224]
Cho Tot technology foundation is growing and expanding to power our next level of growth, serving millions of Vietnamese via our digital products. Our engineering team is building a robust platform, automation and data engineering pipeline that enables continuous explorations in product innovations.

Join us to build systems that serve more than hundred of millions of requests and billions of messages passing through daily. You will be solving big scale and fast data problems in a fast paced agile software development for internet digital products. You will design and build self-serve data products, pipelines and services to enable all functions of the business to have data-driven capabilities. You will have very competitive remuneration with exposure to regional travel within Singapore, Malaysia, Myanmar, Hong Kong, Taiwan for collaboration workshops as well as specific sharing conferences.

What will you be doing?

Build self-serve data products, pipelines, services to enable all functions of the business to have data-driven capabilities
Build self-serve data products to provide training, serving data for machine learning feature
Optimizing data infrastructure on GCP
Be responsible for organizing, developing, standardizing large, complex data pipelines to generate insights, address reporting and advance analytic needs
Writes highly complex ETL processes, designs database systems, develops tools for real-time and offline analytic processing
Build analytics tools that utilize the data pipeline to provide actionable insights into operational efficiency and other key business performance metrics
Create data tools for analytics and data scientist team members that assist them in building and optimizing our product into an innovative industry leader
Work with stakeholders including the Executive, Product, Data, and Design teams to assist with data-related technical issues and support their data infrastructure needs
What do you need for the role?

3+ years of related experience in Data engineering roles with BSc, MSc degree in Computer Science related fields
Deep knowledge in message queuing, stream processing, data streaming architectures, have experience with stream-processing systems: Google Dataflow/Apache Beam, Apache Samza, etc
Experience using and optimizing services such GCP Services, Google BigQuery, Google Dataflow, Google Cloud Composer, databases, data stores and framework
Expertise in SQL, Python, or Java with experience in bash shell scripts, UNIX utilities
Proven ability to leverage multiple tools and programming languages to analyze and manipulate large data sets from disparate data sources and build innovative solutions
A team player has superior ability to communicate technical ideas and results to non-technical partners in written and verbal form
Self-motivated, detail-oriented, and responsible
Strong project management and organizational skills
Experience in data engineering work supporting ML vision and NLP is a plus
What’s in it for you?

Join plenty of Sharing and Learning activities as part of our initiatives to contribute to the tech community in Vietnam
Get 15 days of annual leave and 5 days of sick leave per year
Health insurance for employee and their family members
Get a Macbook Pro as your workstation
Get 13th month salary and annual performance bonus
Participate in regular team building activities and company parties
Get opportunities to attend training courses abroad
Most importantly, the code you write will be impacting the lives of millions!

*Be our family right here: https://careers.chotot.com/ or feel free to contact me for more information
Skype: tremlobisi94| Mail: anhhoang@chotot.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
