### ISSUE TITLE
Chợ Tốt - Android Engineer (Kotlin)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#3225]
We are looking for a talented **Android Software Engineer** that has a great passion to create nice, high-performance applications that make a difference sight. You will be an integral part of Chotot engineer team.

As the leading classified site in Vietnam, we solve real problems and bring out solutions that make a difference to our users.
In our Agile-driven working and open collaborative environment, every day coming to work is a day of joy and inspiration.
Especially, we encourage everyone to keep learning to improve their technical skills as well as soft skills. Therefore, you will have multiple options to access training materials: from internal training to external workshops, from learning online to coaching offline, from domestic seminars to overseas experience-exchange opportunities.
What will you be doing?

Read and analyze product requirements, design features, break tasks.
Develop and maintain Chotot’s applications.
Join in writing technical documentation, unit test, automation test.
Participate in troubleshooting application-related issues and maintaining high performance and device compatibility.
Participate in architecture design/code review.
Research and adopt new technologies to improve user experience.
What do you need for the role?

At least 2 years’ experience in Android development.
Skills in developing Android applications using Android Studio.
Familiar with Java, Kotlin.
Have experience in mobile UI/UX
Experience in using REST APIs to connect to backend services
Good logic skills
Be able to explain clearly  what you’ve done in your old projects
Able to communicate and collaborate effectively with the team
Familiar with code versioning tools such as Git
Degree in Computer Science, Information Technology or equivalent.
Good at both Vietnamese and English.
Love learning new technology and working in a highly dynamic, flexible, hyper-productive agile team.
What’s in it for you?

Join plenty of Sharing and Learning activities as part of our initiatives to contribute to the tech community in Vietnam
Get 15 days of annual leave and 5 days of sick leave per year
Health insurance for employee and their family members
Get a Macbook Pro as your workstation
Get 13th month salary and annual performance bonus
Participate in regular team building activities and company parties
Get opportunities to attend training courses abroad
Most importantly, the code you write will be impacting the lives of millions!

*Be our family right here: https://careers.chotot.com/
Or feel free contact me for more information
Skype: tremlobisi94| Mail: anhhoang@chotot.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
