### ISSUE TITLE
Chợ Tốt - iOS Engineer

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#3226]
We are looking for a talented iOS Developer who really loves coding and building great applications.

As the leading classified site in Vietnam, we solve real problems and bring out solutions that makes a difference to our users.
In our Agile-driven working and open collaborative environment, everyday coming to work is a day of joy and inspiration.
Especially, we encourage everyone to keep learning to improve technical skills as well as soft skills. Therefore, you will have multiple options to access training materials: from internal training to external workshops, from learning online to coaching offline, from domestic seminars to overseas experience-exchange opportunities.
What will you be doing?

Read and analyze product requirements, design features, break tasks.
Develop Chotot’s applications.
Responsible for troubleshooting application related issues and insuring/maintaining high performance and device compatibility
Participate in architecture design/code review
Deploy applications to store.
What do you need for the role?

At least 2 years’ experience in iOS development
Skills in developing iOS applications using Xcode
Proficiency in Objective-C / Swift
Passion about building a great UI/UX apps.
Good logic skills
Understand what you’ve done
Able to communicate and collaborate effectively with the team
Familiar with code versioning tools such as Git
Experience with Android plus
What’s in it for you?

Join plenty of Sharing and Learning activities as part of our initiatives to contribute to the tech community in Vietnam
Get 15 days of annual leave and 5 days of sick leave per year
Health insurance for employee and their family members
Get a Macbook Pro as your workstation
Get 13th month salary and annual performance bonus
Participate in regular team building activities and company parties
Get opportunities to attend training courses abroad
Most importantly, the code you write will be impacting the lives of millions!

*Be our family right here: https://careers.chotot.com/
Or feel free contact me for more information
Skype: tremlobisi94| Mail: anhhoang@chotot.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
