### ISSUE TITLE
MLabs is Hiring Haskellers (100% Remote, Worldwide)

### ISSUE THREAD

**Issue by oskargreda** [awesome-jobs/vietnam#3227]
Description

We are one of the leading Haskell consultancies in the fintech, blockchain and AI space, with a passion for Haskell and open source software. We are looking for a remote Haskeller to join our team.

If you are excited about Haskell, about robust and clean software and are up for a new challenge, you’ve come to the right place!

We have Haskell developer roles from Junior to Senior.

As a Haskell Developer your role may include:
- Building and testing smart contracts, traditional applications
- Helping to define best practices with new application architectures
- Building tools and libraries to support application development
- Working in emerging technologies
- For Senior and Intermediates: Systems Design, Formal Verification, Security and Performance analysis.

Requirements
Strong Haskell skills
Strong software engineering and architecture skills
Strong problem solving and analytical skills
Basic knowledge of security, concurrency, backend systems, system scaling and databases
Version control (git)
Strong verbal skills in English
Experience with blockchain, smart contracts, compilers, nix and/or purescript is a bonus

Benefits
Focus on learning and individual growth in Haskell and Computer Science
Work with other great Haskellers, open source contributors and computer scientists
Interesting and challenging projects
Talk with anyone in the organization, regardless of team
Remote work
Flexible working hours
6 weeks of paid vacation
Competitive salary

We have a variety of projects to work on at any time, ranging from payment stacks to smart contracts and blockchain to open source libraries, DSLs and compilers.

If you like Haskell and challenging projects, MLabs is the place for you, so please apply now via: https://apply.workable.com/mlabs/j/63DAAA4AEF/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
