### ISSUE TITLE
[JobSeekervn] DevOps Engineer - Remote - Fulltime

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3231]
## Location

* Vietnam
* Remote, Fulltime

## Salary Expectation

* Junior: $600 - $900/month 
* Middle: $1200 - $1800/month 

## Requirements
* About 01 year of relevant experience primarily in DevOps and cloud computing.
* Programing Language: Java, Python, Golang or other languages
* Experience with DevOps Frameworks, automation tools, Agile
* Ability to confidently build a strong CI/CD pipeline
* Have good knowledge of Development ecosystem tooling.
* And very well versed with DevOps Frameworks, Agile.
* Good understanding in any of cloud like AWS, Azure, Google cloud...
* Having knowledge of Docker and/or Kubernetes
* Good communication in English (verbal and writing)

### Contact
Skype: hahoainhi
Email: nhiha@jobseeker.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
