### ISSUE TITLE
VieON - 03 Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3237]
## Location

* Saigon, Vietnam

## Salary Expectation

* Middle Level: $1,000 - $1,500 per month
* Junior: $800 -  $1,000 per month

### Must Have

* At least 2 years of experience in equivalent position;
* Having knowledge and experiences in ReactJS/NextJS, Typescript, Node.JS;
* Having knowledge and experiences in Responsive Web, HTML 5, CSS 3, UI/UX, Caching;
* Having experiences in using Jira and Git;

### Ideally

* Having knowledge and experiences in one of these Google’s tools: Analytics, Webmaster tool, Pagespeed, SEO onpage;
* Having knowledge and experiences in Video Streaming.
* Having knowledge and experiences in Online Ads platforms: Facebook audience, Google Admob, Google Adsense, Google Ad Manager, AdNetwork is a plus;
* Having skills in presentation.

### Responsibilities

* Develop VieON for web platform and mobile web platform;
* Research new technology for Web development, optimize web;
* Develop internal web and dashboard.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
