### ISSUE TITLE
VieON - 02 Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3238]
## Location

* Saigon, Vietnam

## Salary Expectation

* Junior: $800 - $1,000 per month
* Middle level: $1,000 - $1,500 per month

### Must Have

* At least 2-year experience in programming;
* Familiar with Go, MySQL, MongoDB, Git and CI/CD;
* Ability to work under high pressure

### Ideally

* Experience in Unit Test;
* Experience in Agile;
* Experience scalable and high-performance system serving and knowledge in Elastic Search or Video Streaming is a plus.

### Responsibilities

* Design, build and operate Backend Systems for VieON;
* Support developing other products, services of VieON;
* Assignments of line supervisor.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
