### ISSUE TITLE
VieON - 02 Senior Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3239]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,500 - $2,000 per month

### Must Have

* At least 4-year experience in programming;
* Good knowledge of computer science, data structures and algorithms;
* Knowledge of micro-service architecture and Cloud infrastructure: AWS, Google Cloud Platform;
* Knowledge of Agile/SCRUM, Kanban product development process;
* Knowledge of one of the following types of databases: MongoDB, Elastic Search, or column-based databases;
* Proficient (one or more): Go, Python, PHP, Scala, Java, Node.js;
* Proficient in at least one of Relational Database types: MariaDB, MySQL, PosgreSQL, T-SQL;
* Proficient in caching technologies; Git & CI/CD;
* Experience in developing and operating scalable systems, high CCU, A/B Testing, UnitTest;
* Able to train subordinates and presentation.

### Ideally

* Experience in developing products related to streaming video an advantage;

### Responsibilities

* Design, build and operate Backend Systems for VieON;
* Support developing other products, services of VieON;
* Research, develop and apply new technology, solutions to optimize systems;
* Assignment of line supervisor.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
