### ISSUE TITLE
VieON - Site Reliable Engineer - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3240]
## Location

* Saigon, Vietnam

## Salary Expectation

* $800 - $1,500 per month

### Must Have

* At least 1 year of experience in a similar position or 2 years of experience in a DevOps position.
* Knowledge of network, protocols, TCP/IP, HTTP, DNS.
* Knowledge of Cluster/Replication model, Microservices, Failover, distributed technology, load balancing.
* Knowledge and experience in operating CI/CD tools: git, ansible, terraform, container technologies.
* Ability to program with languages: Shell Script, Go/Python. The advantage of knowing languages: Lua, PHP, JS ...
* Fluency and in-depth understanding of Linux operating system, cloud services: AWS, Google Cloud, Azure.
* Experience in monitoring, testing and analyzing system performance.
* Careful, meticulous.

### Responsibilities

Manage and analyze system products and services and system service tools:
* Automated CI/CD deployment tools.
* Tools to monitor activity, performance, stability, and crash alerts of the whole system.
* Log analysis and evaluation.
* Services: storage (CEPH), CDN, Livetv, livestream, transcode, big data...
* AWS Cloud System.

Operations:
* Monitoring and alerting the system 24/7.
* Periodically upgrade products, services and systems.
* Ensure system data security.

Research and develop system:
* Research new technologies for system operation and deployment.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
