### ISSUE TITLE
VieON - Senior Manual QC - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3241]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - $1,500 per month

### Must Have

* 05+ years of experience as a Senior software tester for web applications/mobile applications;
* Hands on programming language: Go/Java/Python/Javascript;
* Hands on experience in writing SQL queries and strong knowledge in DBMS (Relational Database, NoSQL);
* Knowledge of the software development lifecycle, agile testing methodologies;
* Experience in creating test plan, test check list, test cases, test report, bug reports;
* Experience of testing web services/API (PostMan/JMeter or similar tools);
* Good experience in version control, bug tracking (Jira), CI/CD, Docker;
* Analytical, problem solving, clarify requirement with Product owner and Technical team;

### Ideally

* Understand about OTT platform is a plus.

### Responsibilities

* Perform testing API/ BE Database Testing / Manual testing;
* Participate in development, consulting, and proposing user application solutions, technical solutions, and supporting the team when needed.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
