### ISSUE TITLE
VieON - Automation QC - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3242]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,200 - $2,000 per month

### Must Have

* Proficient in business domain knowledge and automation testing;
* Knowledgeable in three main methods of writing test case (Equivalence partitioning and boundary value, Decision table, generate TC from UC) and appropriately apply such knowledge in practice;
* Having experiences in using one of these technologies: Robot Framework, Selenium, Postman, Appium, Serenity, Jmeter;
* Skills in adhoc-testing;
* Knowledgeable in test process stages and well-performing in stages such as: analyzing requirements for test plan;
* Knowledge about programming, performance and security testing is a plus;
* Understand the logic behind a codebase.

### Responsibilities

* Design and implement test plan, test case and test procedure to ensure stability and security of the application;
* Perform functional testing at multiple levels on new features for all platforms with devised testing plan;
* Responsible for managing, stashing, notifying, and monitoring all issues that occurred;
* Develop, advise, propose solutions to user problems, technical issues and support other teams when necessary.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
