### ISSUE TITLE
Wizeline - Java Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by NhiLamThao** [awesome-jobs/vietnam#3244]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500 - $3000 per month

### Must Have

* Solid experience in software development with J2EE applications.
* Spring Boot, Spring Core, Spring MVC and Java 8 is a must. Spring Cloud is a plus.
* Hands-on experience with cloud technology like Google Cloud Platform/AWS and databases like Oracle/Postgres.
* Experienced with tools including Jira, Git/Stash, Jenkins, Maven, Gradle.
* Expert in REST API and/or gRPC.
* Good analytical and communication skills in English.

### Nice to have

* BS/MS in Computer Science, Engineering, or a related subject.
* Architecture skills, able to select the best stack for each project.
* Being a DevOps advocate.

### Responsibilities

* Partner with multidisciplinary teams (Technical Writing, User Experience, Project Management and Quality Assurance) to build scalable products from inception to completion. Solving challenging problems, working with cutting edge technology with the brightest minds in the industry.
* Work as a Software Engineer focusing on using Java and related technologies (Spring Framework, Spring Boot, Spring Cloud, Netflix OSS). Our team is distributed - you’ll be working with teams located across the world.
* We are proponents of ownership; expect to drive internal Wizeline initiatives and objectives, as well as build relationships with direct communication with customers / stakeholders.
* Mentor & coach other team members to grow together.
* Drive the engineering culture, advocate best practices to bring out the best quality for our solutions.

### Why it would be awesome to work with us
* Our culture: We offer exceptional career growth opportunities to our employees with skill development workshops, mentoring programs and support for side projects or entrepreneurial work.
* Our benefits and perks: Wizeline offers competitive compensation and employee-centric benefits including daily meals, health benefits & wellness programs and industry-leading maternity and paternity leave,. 
* Our Global Family: We connect cross countries, as well as language training and immigration support for expats.

### Contact
Homepage: https://www.wizeline.com/
Senior Talent Ambassador: Ms. Nhi Lam
Tel/WhatsApp/Zalo: +84 972 671 366
Skype: live:lamthaonhi0110
Email: nhi.lam@wizeline.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
