### ISSUE TITLE
VieON - Android Developer - Saigon - FT

### ISSUE THREAD

**Issue by LanVo87** [awesome-jobs/vietnam#3245]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - $1,500 per month

### Must Have

* Software Developer with at least 1 years of experience in building apps for the Android platform;
* Good understanding of Kotlin language;
* Good understanding of Android application architecture and design.
* Understanding of complete application development, continuous integration & testing and app distribution infrastructure;
* Have knowledge of testing in Android (Unit test, Integration test, UI test);

### Ideally

* Past experience of building video streaming apps is a plus.

### Responsibilities

* Write unit tests for all features.
* Ships feature fast-moving agile sprints.
* Works closely with API, Product Design and Product Management teams to brainstorm and chalk out details of features.

### Why it would be awesome to work with us

* Salary depending on ability + Bonus;
* Fully entitled to 14 days of leave/year and social welfare regimes in accordance with Vietnamese law;
* Professional, dynamic, friendly working environment with high promotion opportunities;
* Company trip, team building.

### Contact 

HRBP Ms. Lan Võ

Email: lan.vo.phuong@datvietvac.vn

Tel: 028. 38232246 - 337

Website: https://www.datvietvac.vn/

Address: THAP 222, 222 Pasteur Dist.3, HCMC, Vietnam

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
