### ISSUE TITLE
Outcubator - PHP Developer - Hanoi - FT 

### ISSUE THREAD

**Issue by ChloeLe9192** [awesome-jobs/vietnam#3247]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation

* Upto $2500/month

## Requirements
* 2+ years of PHP experience;
* Strong knowledge of PHP;
* Strong knowledge of OOP and Design Patterns;
* Experience with MySQL, database design, query profiling and optimization;
* Experience with NoSQL (Redis, MongoDB, Couchbase etc);
*  Experience with at least one of the PHP frameworks (Zend Framework, Yii, Laravel etc);
* Experience building high-available web applications is a plus;
* Knowledge of JavaScript, HTML, CSS;
* English communication 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Participate in the development of company products;
* Work on backend and frontend functionality of assigned project
* Build web applications, pages and interfaces for company products, using different APIs, frameworks, and libraries
* Build high-available solutions and optimize the load
* Build APIs for company products
* Integration of third-party libraries into company products
* Perform code reviews
* Take initiative and strive to make a noticeable contribution to the company
* Other assigned tasks.

### Why it would be awesome to work with us
If you are eager to take your career to the next level in the payment industry, this is the opportunity for you. We offer:

* Competitive compensation depending on experience and skills;
* Private Insurance;
* Individual career path;
* Paid vacation;
* Comfortable workplaces with the most up-to-date equipment;
* Our own chefs make delicious breakfasts, lunches and desserts for whole team;
* Convenient office location near West lake;
* High energy, international and innovative team;
* Annual assessments;
* Flexible working time;
* Optional business trips;
* Monthly team outing;
* Football, ping-pong and table football teams inside the company.

This role is the ideal opportunity for someone looking for new challenges that would allow them to make a noticeable, positive impact in the company while learning and adapting to our fast-paced scale-up environment.

As part of our growing team in Hanoi, you will have a lot of opportunities to develop your career further with us. With future expansion plans, now is a great time to join us on our journey to change the way we pay. 

### Contact
Recruiter Ms. Chloe Le 

Email: chloe@outcubator.com 

Skype: kitu2709/ Phone, Zalo: 0787185656

Address: To Ngoc Van, Tay Ho, Hanoi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
