### ISSUE TITLE
Outcubator - Quality Assurance -Hanoi - FT 

### ISSUE THREAD

**Issue by ChloeLe9192** [awesome-jobs/vietnam#3248]
## Location

* Hanoi, Vietnam
* Fulltime 

## Salary Expectation

* $1500/ month

## Requirements

* Knowledge and practical application of test methods;
* Understanding of SDLC (System Development Life Cycle);
* Experience in testing web applications, APIs, iOS and Android apps;
* Experience with Selenium WebDriver and automation tools is a plus;
* Be able to communicate in English;
* Bachelor’s degree or higher.

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

* Create test cases to cover existing and new functionality;
* Perform manual testing of web pages, widgets, mobile applications;
* Create and run automated test cases;
* Submit bug reports into issue tracking tool;
* Perform manual testing on mobile devices;
* Perform security tests against XSS attacks, SQL injections, etc;
* Communication with company teams regarding bugs and issues.

### Why it would be awesome to work with us

If you are eager to take your career to the next level in the payment industry, this is the opportunity for you. We offer:

    Competitive compensation depending on experience and skills;
    Private Insurance;
    Individual career path;
    Paid vacation;
    Comfortable workplaces with the most up-to-date equipment;
    Our own chefs make delicious breakfasts, lunches and desserts for whole team;
    Convenient office location near West lake;
    High energy, international and innovative team;
    Annual assessments;
    Flexible working time;
    Optional business trips;
    Monthly team outing;
    Football, ping-pong and table football teams inside the company.

This role is the ideal opportunity for someone looking for new challenges that would allow them to make a noticeable, positive impact in the company while learning and adapting to our fast-paced scale-up environment.

As part of our growing team in Hanoi, you will have a lot of opportunities to develop your career further with us. With future expansion plans, now is a great time to join us on our journey to change the way we pay. 

### Contact
Recruiter Ms. Chloe Le 
Email: Chloe@outcubator.com 
Skype: kitu2709 
Address: To Ngoc Van, Tay Ho, Hanoi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
