### ISSUE TITLE
[Cyber Eye] - [Senior Software Engineer] - [HaNoi] - [FT]

### ISSUE THREAD

**Issue by Huees-ori** [awesome-jobs/vietnam#3249]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* Up to $2800 per month

## Requirements

* 5+ years Software Engineering experience (backend)

### Must Have
* Previous experience as Backend Engineer more than 5 years.
* Experience in software development.
* Proficient in at least 1 programming language: Golang, Python, Ruby, Java, …
* Highly experienced in creating and maintaining clean code.
* Have good logical thinking, algorithm, data structure; understand how some common data structures work.
* Having creative thinking when solving problems, have the mindset of a problem solver.
* Proactive, hard-working, self-responsible at work.
* Experience in leading a team and/or interest in managing and developing your team members.

### Ideally

* Experience in applying machine learning models, deep learning to Computer Vision and NLP problems.
* Worked with DevOps/DataOps/MLOps projects.
* Participated in some projects to process and optimize the system with a large number of transactions.
* Experienced with public cloud services such as AWS/GCP/Azure

### You’ll be responsible for
* Lead product development team, has the highest responsibility in the technical scope of the product.
* Responsible for analyzing technical requirements, providing solutions and participating in the development of important features.
* Research about products in the market to debate and improve existing products.
* Recruiting and training team members.

### Why it would be awesome to work with us

* We want to build a talent team, and you will be a team member.
* You will be involved in the design and build process of APIs-as-a-Product from the beginning, focusing on solving problems of digitizing information and analyzing large volumes of data. Technology related to Computer Vision/NLP/Data Science using statistical models, machine learning and deep learning.
* Some technologies and products are developing such as:
- Detects and recognizes information (text) on forms (OCR).
- Vietnamese handwriting recognition.
* Currently, we are still expanding (without limitation) to work on many new problems and technologies.
* Competitive monthly salary:  Up to $2800 per month, 14-16 months per year, Salary review twice a year

### Contact
* Email: tuyendung@cybereye.vn
* Zalo/Telegram: Hue Tran - 0336 294 693 (24/7)
* Address: Cau Giay, Ha Noi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
