### ISSUE TITLE
FSOFT - Ruby on Rails Team Lead - HCM - FT

### ISSUE THREAD

**Issue by Hanaxuchi** [awesome-jobs/vietnam#325]
Company profile

FPT Software - the Software Powerhouse
•	Vietnam's largest and one of the fastest growing software outsourcing companies.
•	Over 6,000 software outsourcing projects and a total volume of 2.5 million man-days in the last 10 years.
•	A broad presence in diverse global markets.
•	Specialist in shaping world-class networks of global delivery centers.

http://fpt-software.com/About%20Us/Company%20Overview/default.aspx 

## Location

* Saigon, Vietnam

* Project info

- Customer is a sub of YAHOO
- Building ODC - Lead & build a new team - promising career

## Salary Expectation

* $1k7/month or negotiable

## Requirements

- RoR, Linux, SVN, GIT
- Web application, AWS
- English advance

## Skills
- At least 3 years of RoR, Linux, SVN, GIT
- Web application, AWS is a big plus

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

- Support member, review source code
- Basic design, detail design, Architecture design
- Backup PM in project management
- Onsite if required

### Contact

Ms. Nhung - nhungntp1@fsoft.com.vn *** Skype: Nagi8a1b

**Comment by hieuk09** [comment]
@Hanaxuchi: Could you add some detail in the responsibilities section?

**Comment by joneslee85** [comment]
@Hanaxuchi can you please revise the format of bullet points? Use `*` instead of `•`

**Comment by joneslee85** [comment]
Closed. No amendment after 2 days.
