### ISSUE TITLE
JobSeekervn - Angular Lead - Fulltime - Saigon

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3250]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $2200 - $3000 gross/month 

## Requirements
* Frontend: Angular 12, Bootstrap 
* tools
■ git, jenkins, ansible, sonarqube, jira, google workspace
■ your choice of windows/linux and IDE
* Soft skill: 
- English speaking

### Why it would be awesome to work with us
* Competitive salary & bonus base on your performance (negotiable, depending on experience)
* Coffee, tea, snack and monthly team building with friendly team.
* 15 paid annual leaves.
* Diamond health care pakage for you and your kid
* English class learning in working hours.
* Excellent working environment, motivated multi-cultural team and management
* Immediate incorporation

### Contact
Email: nhiha@jobseeker.vn 
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
