### ISSUE TITLE
Grab - Senior DevOps Engineer - Saigon/Hybrid - FT

### ISSUE THREAD

**Issue by Huyenpham2695** [awesome-jobs/vietnam#3251]
## Location

* Saigon, Vietnam
* Hybrid

## Requirements
- You are responsible for automating common cloud operations - account/subscription creation and management

- You spend time with security ensuring that their needs are built into automated guardrails for developer resources

- You support the developer community in their needs, always with a view to self-service and automation where possible

- You are responsible for the roll-out of new cross-cutting technologies - container clusters and service mesh, secrets management, monitoring and logging solutions and more

- You are involved in the design and implementation of new configurations for cloud resource use

- You bring knowledge of new ways of doing things and can clearly articulate technical solutions both within and outside the team

### Must Have

You have experience with one or more cloud environments (AWS, Azure preferred)

You are an experienced DevOps or DevSecOps practitioner, and have operated production services in cloud environments

You have experience with build and deploy tooling - Jenkins, spinnaker, and similar

You have experience with automation for infrastructure deploy/manage - terraform, cloud formation, resource manager or similar

You can easily pick up new technologies and are keen to expand your knowledge

You have experience with micro-service architectures

You have experience with the Ruby program is highly preferred

### Why it would be awesome to work with us
- Extra Medical Insurance from 1st joined date.
- 14 days Annual leaves + 5 days of other leaves
- Grabflex allowance (up to 4.000.000 VND per month) for Family’s vacation, Education, Gym, Learning, etc…
- 13-month salary
- Performance bonus
- GrabLove as vouchers for using Grab’s services.
- Relocation opportunities to Regional or other countries.
- Online Learning System & Offline Training courses are provided.
- Opportunity to work, learn & grow with world-class professional engineers.
- Opportunity to work for South East Asian Tech Decacorn.
- Young and dynamic work environment.
- Working day: Monday - Friday.
- Working place: Mapletree Building, 1060 Nguyen Van Linh, Tan Phong, District 7, Ho Chi Minh City (Working place and working time is quite flexible, now all WFH due to Covid).

### Contact
Homepage: https://grab.careers/
Email: ngochuyen.pham@grabtaxi.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
