### ISSUE TITLE
JobSeekervn - Flutter Engineer - Fulltime - Saigon

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3252]
## Location
* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $1200 - $1800/month 

## Requirements
*   At least 2 years of experience with Flutter
*   At least 3 years of experience in building mobile application (Java / Kotlin / Objective-C / Swift)
*   Built at least 1 large-scale Flutter app from scratch and published on AppStore/PlayStore
*   Experience in deployment process, publish application on AppStore and PlayStore
*   Strong experience with Firebase: Targeted Push Notification, Messaging
*   Strong foundational understanding of software engineering, including architecting user interfaces, managing application state, and interacting with APIs
*    Good at communication skills in general and English

### Responsibilities
* Analyze, propose and implement solutions for projects
* Create development process and pipeline for continuous integration and continuous delivery
* Delivery multi-platform application using Flutter framework with well-architected and high-quality solutions which testable and scalable
* Cooperate with BE developers to consume backend data services via GraphQL API
* Participate in the entire product lifecycle, from requirements, designs to implementations
* Write technical specifications based on conceptual design, business / technical requirements

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
