### ISSUE TITLE
Fetch Technology - Head of Engineering/ Lead Fullstack Developer - Remote - FT - Up to 15,000 USD

### ISSUE THREAD

**Issue by Jesse111-flyaway** [awesome-jobs/vietnam#3253]
![Al Mubarak](https://user-images.githubusercontent.com/60914247/156701103-69c181e7-8b64-4e7d-9c60-95c642026df7.png)

## INTRODUCTION

**a. About Fetch:**

Fetch Technology Vietnam is a comprehensive global provider of HR and Talent Acquisition Services, focusing primarily on the technology fields. Founded in 2016, Fetch Technology Vietnam helps foreign companies of all types and sizes reach their potential by providing the talent and support to efficiently build and scale a high-performing, distributed workforce in Vietnam.

Our mission is to offer Vietnam’s most talented technologists a platform to connect with some of the world’s leading tech companies and build their expertise on a global scale. Over 4 years, Fetch has built a good reputation and is trusted by many Vietnamese and foreign companies; And Fetch will continue its good work to bridge the divide between the World and the Vietnam Tech sector.

**b. About Client:**

Join with them, and help them build the ﬁrst ﬁnancial markets for blockchain games, enabling players to own and invest in the games they love.

They were founded on one idea: Blockchain-based games represent the ﬁrst opportunities for players to own the content they purchase and share in the ﬁnancial upside of these game economies. They are lowering the barrier to participating in GameFi. Their goal is to build the products and services that ensure an open ﬁnancial system where players can thoughtfully invest in the games they love.

Using the same passion they have for their members, they are committed to building an inclusive environment where their employees can thrive and do impactful work. They believe in a work culture that balances meritocracy and technocracy.

## RESPONSIBILITIES

- Help source, aggregate and organize data to inform Web3 game economy analytics, using both in-game events and on-chain data sources.
- Create novel game economy metrics to help power market and insight dashboards for Players and Guilds.
- Integrate ETH, SOL and POLY wallet data from gaming applications and pair it with Play-to-Earn reward mechanics.
- Ideate,design, implement and deploy new data programs,as well as other parts of our technology stack. The team will empower you to make important architecture decisionstoo!
- Support implementation of tools to create new token-based game mechanics on top of existing blockchains.
- Partnercross-functionally on product evolution from ideation, design, architecting systems,and process.
- Keepingtrack of issues and either self-implement or design ﬁxes.
- Cross-train other team memberson your designsand implementation.
- Write well-tested and documented code.

## REQUIREMENT

- Min. 5+ years of experience (Ideal candidate would have 7 - 8+ years of experience).
- Backend: NodeJS, Frontend: React.
- Integrating third-party APIs.
- Experience owning products/features end-to-end.
- Experience working closely with data scientists and/or ML devs.
- Create architecture, designs, and documentation that will lead to consistency.
- Reliability, scalability, security, and performance of our products.
- Excellent English language and communication skills.

**Nice to have:**

- Experience with blockchain protocols, python, rust, solidity (Note: Rust/Solidity can be taught in-house if candidate does not possess kills).
- Experience with game development.
- Passion for video games, data, economics, and/or blockchain Experience building analytics products.

## WHY YOU‘LL LOVE WORKING HERE

- 15 days of Annual Leave.
- 5 days of company Summer Break Annual Leave.
- 5 sick/mental health days.
- Up to 1.0% equity and 0.25% token allocation.

## CONTACT:
* Mail: trangdong@fetch.tech
* Skype: trangdong0111@gmail.com
## JD: https://bit.ly/3IzXsCO

**Comment by qcam** [comment]
@Jesse111-flyaway Hello and thanks for the posts. We received feedback from the community today regarding the legitimation of the ads posted by Fetch Technology. According to our policy, we do not accept jobs from agencies or head hunters.

In case of misunderstanding, please help to clarify with a comment. All the posts will remain closed until the concern is fully addressed.

Thank you and have a good day!
