### ISSUE TITLE
ADAPTIS - (SENIOR) QA SOFTWARE ENGINEER - Ho Chi Minh - FT/Freelance

### ISSUE THREAD

**Issue by CherishMIS** [awesome-jobs/vietnam#3255]
## Job description
* Call daily English- report (communicate, call daily standup...)
* Test API, install SQL to check database 
## Required skills:
Job requirement:
* Experience with Jira (creating tickets, assigning tasks, comments, bug reports) and Zephyr on Jira (creating test cycle).
* Experience with Charles Proxy or alternative programs to check mobile network logs.
* SQL skills to check databases.
* Experience with Postman or alternatives to check API
* Experience with using simulators or BrowserStack to test mobile.
* English level: Intermediate
 
 
## What we offer you:
* Tet bonus
* December bonus (13th salary)
* Bonus 1 month salary (14th month salary) for 2 years of service
* Bonus 2 months salary for 3 years of service (14th and 15th salary)
* Healthcare support, annual health check
* Unlimited paid days off
* Allow to work from home/ Remote
* Device equipment
* Whoopie Fridays where people can meet, chat, and exchange knowledge
* Daily happy hour
* Quarterly team building activities, summer company trip

### Contact
Email: linh.nguyen@adaptis.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
