### ISSUE TITLE
Golang Engineer - Remote/Vietnam - FT

### ISSUE THREAD

**Issue by haotangio** [awesome-jobs/vietnam#3256]
## Location

* Remote

## Salary Expectation

* $1,500 - $7,000 / Month (Gross)

## Requirements

* Must be Very Smart: Excellent at critical thinking, problem solving, design thinking; can learn and understand new things at principle and fundamental concepts, then be able to quickly and properly apply those new knowledge into real-life projects.
* Fluent in English, can communicate with the international team via English using video call. If you’re not fluent in English, you can work with a Vietnamese team.
* A university degree (BS, MS, or PhD is a plus) in Computer Science, Software Engineering or related fields.
* Good at teamwork and communication.
* Passionate about programming and solving challenging problems.
* At least 1 year of experience with Golang, familiar with its well-known libraries and tools.

## Ideally

* Knowledge or hands-on experience with Micro-services, Docker, Kubernetes, AWS, etc.
* Knowledge or hands-on experience with building Logistics, NFT, Blockchain, Banking and Fintech, etc. systems.
* Experience leading development teams.
* Top students at well-known universities; graduated from Gifted High Schools; got scholarship; got medals from provincial, regional, national and international contests about Information Technology or Mathematics. However, a University Dropout (to found company) is also a BIG plus.

### Responsibilities

* Build backend APIs for various services and interaction between them.
* Write clean, modular, testable, maintainable, beautiful and smart codebase.
* Collaborate with front-end and mobile engineers, designers, product managers and technical leaders to build products.

### Contact

Hao Tang - haotang@dayoneteams.com - Skype: haotang.io - Phone no: 0963143713
Kevin - kevinparrish@dayoneteams.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
