### ISSUE TITLE
CXP - Flutter Engineer - Fulltime - Saigon

### ISSUE THREAD

**Issue by jadenn04** [awesome-jobs/vietnam#3259]
## Location
* Botanica Premier Apartment, Block A2, 112 Hồng Hà, Tân Bình District, HCMC, Vietnam

## Salary Expectation
* Up to $2,000

### What you’ll work on
* Design and implement new user-facing features in the application for Trust Wallet
* Have the ability to balance high response, stable and efficient code with attractive and functional aesthetics
* Work together with cross-functional teams to define, design, and ship new features
* Efficiently use third-party data sources and APIs
* Create and execute unit tests on your code, to ensure its robustness, including edge cases, usability, and general reliability
* Troubleshoot issues, fix bugs and improve application performance
* Optimize web applications to maximize speed and scale.
* Development efficiency and improve code quality.

### Requirements
* Have experience with Flutter for both iOS and Android.
* Good familiarity with popular libraries and design patterns
* Good knowledge of the general mobile landscape, architectures, trends, and emerging technologies
* Familiarity with the whole web stack, including protocols and server-side techniques (Http, Websockset).
* Good experience of working with remote data via REST and JSON.
* Strong communication and problem-solving skills.
* Interest and knowledge in the crypto/blockchain/technology space preferred.

## Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* Annual company trip
* 13th salary bonus

## Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

## About Us
* CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
* Email: hr@cxptek.com 
* Phone: (+84) 38 4498 899 (Trang)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
