### ISSUE TITLE
honestbee - Software Engineer (Ruby) - Singapore / Saigon - FT

### ISSUE THREAD

**Issue by binhngoc17** [awesome-jobs/vietnam#326]
## Location
- Saigon, Vietnam
- Singapore, Singapore
## Salary Expectation
- Singapore: $4000 SGD+/month or negotiable
- Vietnam: $1300 USD +/month for junior position & $2100 USD+/month for senior position
### Backend
- Ruby
- PostgreSQL
- 2+ years Software Engineering experience
### Android
- Java
## Skills
- Good communication in English
- Ruby programming
### Ideal candidate
- Familiarity with TDD and BDD concepts and how to use them to write code that is well tested. If not, be willing to invest time to learn.
- Have experience working on the web stack and be willing to get into the Rails stack. Many of our best engineers had no prior experience with Rails.
- You enjoy working in a start-up and open environment
- You take pride and ownership in your work
- You are self motivated and can work well under pressure
- You have a good sense of humour and like fun
### Responsibilities

Great power comes with great responsibilities!
### You’ll be responsible for
- Work closely with product and design to build and improve features
- Write and improve upon existing code with attention paid to performance
- Plan and document technical specifications for features or system design
- Contribute towards improving engineering culture and approach

More details about the position can be found here: https://jobs.lever.co/honestbee/fc9f0ba6-ba5a-431c-9f16-8f96161058c5
### Contact

ngoc.tran@honestbee.com (+65 8429 8483)

**Comment by longkt90** [comment]
is it in Singapore dollar or USD? @binhngoc17

**Comment by binhngoc17** [comment]
It is in Singapore dollar

**Comment by longkt90** [comment]
That's a huge different. I think it's better updated in the JD, for Vietnamese if you dont specify, they will understand as USD

**Comment by binhngoc17** [comment]
Hey @longkt90 Let me specify it

**Comment by hieuk09** [comment]
@binhngoc17: Could you change the title to comply with our format?

**Comment by binhngoc17** [comment]
@hieuk09 thank you for your suggestion! Updated
