### ISSUE TITLE
[HSVN] - [PHP DEVELOPER] - [HANOI] - [FT]

### ISSUE THREAD

**Issue by Xamnguyen** [awesome-jobs/vietnam#3263]
## Location

* Hanoi, Vietnam

## Salary Expectation

* upto $2000
## Requirements
* Expertise in developement PHP
* Hand-on experiences & knowledge on Laravel
* Expertise in database programming or design skills, including relational database skills (SQL, Postgres, etc.) and non-relational database skills (MongoDB, Redis, etc.)
* Knowledge in devops is a big plus
* 4+ years Software Engineering experience

### Responsibilities
Working with a prestigious & global customer based in Singapore, we are recruiting a senior programmer for the following specific tasks:
• Work directly with Branch Director to build products for customers
• Optimize data structures and ensure optimal performance of the database.
• Identify and roll out new features for the product while improving existing features
• Implement and monitor product quality and improvement projects, ensuring proper maintenance and upgrading activities are performed;

### Why it would be awesome to work with us

* Working in global environment 
* Enjoy a competitive salary according to your ability, a worthy bonus according to your achievements.
* Signed contract, include social and health insurance
* Dynamic environment and many career development opportunities.
* Young, enthusiastic team, always supporting each other
* Regular participation in advanced courses in both technical and financial knowledge
* Other conditions: discuss more specifically during the interview

### Contact

live:.cid.f9a5012fddc93dbe or https://www.linkedin.com/in/lucianguyenhr/ to disscuss more
Thank you so much!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
