### ISSUE TITLE
Otto International - Solution Developer (Node.js & React.js) - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3266]
## How will you make a difference?

•	Develop large scale web-based applications by utilizing the underlying technologies and platforms
•	Implement the full-stack solution with different kinds of technologies according to both user and technical requirements
•	Work with testing team to ensure high-quality releases

## Who are we looking for?

•	Higher Diploma/ Degree holder in Computer Science or related disciplines
•	At least 2 – 3 years of hands-on experience in software development, candidates who have more experience are welcome too.
•	Strong knowledge of Node.js, ReactJS, PL/SQL and familiarity with software development cycle (SDLC / Agile), object-oriented programming and web-based application development (MVC models).
•	Applicants with the following experience can be considered as a plus:
        - Any of Spring, Hibernate, and JS frameworks (e.g. Vue.JS), Groovy/Grails, Microservices, Mobile development.
        - Familiarity in Amazon Cloud Services (e.g. S3, Lambda, ECS, etc.), Azure AD, CICD (e.g. Jenkins, Terraform, etc.)
•	Self-directed, organized, results-oriented, strong passion for driving creativity and backing changes
•	Good communication skills in English (written and spoken)

## Why working with us?

•	Collaborative, fun and challenging work environment
•	Open, transparent and diverse culture worldwide
•	Attractive pay, 13rd salary, holiday bonus, performance bonus
•	Work from home/ hybrid/ remote
•	Full insurance coverage, extra medical insurance, annual health check-up.

## Contact
Email: selina.nguyen@ottoint.com
Mob:+84 98 789 6545

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
