### ISSUE TITLE
Sun Asterisk (Sun*) - Ruby Developer all level up to $2200 - HN/DN/HCM - FT

### ISSUE THREAD

**Issue by ghost** [awesome-jobs/vietnam#3271]
# Location

* Hanoi, Da Nang, Ho Chi Minh

# Salary Expectation

* $700-$2200 + performance bonus

# Responsibilities
* Participate in the requirement analysis, system design
* Participate in company product development or outsource projects with the Japanese market:
   + On the server-side: deploy business logic, operate, maintain and ensure the performance of web systems
   + Collaborate with the frontend Unit to build website interfaces
* Research and apply new technologies to improve the quality of existing projects
* Participate in tech forums/tech shows of the company

# Requirements
## Junior/Middle:
* Have at least 1 year of experience working with Ruby
* Have knowledge of programming OOP Ruby on Rails, Web Development, DBMS, ORM (working on a lot of content related to database performance, RESTful, SPA is an advantage)
* Have experience in Unit test: test function, test integration, coverage
* Be able to Unit Test, have DRY mindset – Works well with HTML, CSS, JavaScript (Jquery, AngularJS, Ajax, …), Bootstrap, JSON, XML,
* Be proficient in version management and management tools (Git, SVN, Redmine, Jira)
* Have knowledge of Docker, AWS, CI / CD, deployment
## Senior:
* Have experience in Ruby projects for over 4 years
* Master Ruby on Rails, have experience in working with and handling large systems
* Have experience in OOP, MVC Framework, ORM, RESTful API, Design Patterns
* Have knowledge of TDD, Testing and be able to implement TDD-thinking, DRY-minded requirements
* Work well with one of the Databases: MySQL, PostgreSQL, Oracle, …; Having experience in working with Big Data is an advantage.
* Have experience in working with Cloud, Microservices
* Be proficient in AWS, Docker; Have knowledge of Infrastructure, Deployment, CI/CD
* Be proficient in source code management tools: GIT, SVN, and Redmine project, Jira.
* Work well with HTML, CSS, JavaScript (Jquery, AngularJS, Ajax, …), Bootstrap, JSON, XML, …

# Benefits and perks:

## Professional, open-minded and creative environment:

* Work with colleagues with ideas to change society.
* Respect different perspectives within a team
* Strong learning culture to promote individual development
* The culture of taking risks to experience and thrive
## Focus on individual development

* Be consulted, accompanied and supported in career development with the career path system (developing in expertise or management direction) that has been studied and tested for many years.
* Be oriented for individual, group and organization goals
* Be empowered
* Be supported to define 3-month or 6-month goal (Goal Define Support)
## Special care for employees

* Salary: $700-$2200 (Gross) with other allowances (lunch, transportation, beauty care, Japanese and IT certificates, etc.)
* 13th-month salary & performance bonus
* Performance review: Twice/year
* Comprehensive health insurance Sun* Care
* Seniority Allowance
* Women care allowance: Women’s physiological leave: 2.5 hours/month; Postpartum leave for female employees with under 1-year-old children: 1 hour/day
* Policies to support learning activities, knowledge sharing, cultural exchange (Technology Seminar – Tech Expert, Club: Reading, Japanese, Music Club, …)
* Annual tourism, quarterly team-building activities.

### Contact
Facebook: fb.com/cung123
Skype: ngoclam119
Email: tran.thi.ngoc.lam@sun-asterisk.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
