### ISSUE TITLE
Otto International - Devops Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3272]
## How will you make a difference ?

- Analyze the business process and re-engineer functional processes adapted to the need of the team in accordance with the security requirement of the group
- Solve Architecture and Infrastructure problems using development skills to build the right solution for internal stakeholders
- Plan, design, develop, test, maintain CI/CD Pipelines and onboard developers to use those pipelines
- Comfortable in helping, supporting, and answering support tickets in a timely and expedient manner
- Implement workflows, build/support interfaces and integrations, educate co-workers and assist with other development priorities as required
- Help to create formal technical/system documentation to standards and conventions as needed by team members and end users
- Communicate technical issues effectively to non-technical people as well as understand requirements given by clients and business consultants

## Who are we looking for ?

- Degree holder in computer science or related fields
- Knowledge of AWS Services such as EC2, RDS, S3, Lambda, Cloudwatch, Route 53
- Knowledge of Azure services
- Knowledge of Network deployment of VPC, Load balancers, security groups, firewalls, port management
- Experience in making backup strategies for SQL, Non-SQL DBs, Serverless components and servers
- Experience in setting up deployment pipelines for Full Stack Applications and distributed systems
- Experience using GitHub Actions and Deployment Scripts
- Experience working with Infrastructure-as-code environment tools such as Terraform is preferred
- Experience in using JSON, YAML, Bash, Zsh, Power-shell
- Experience with Linux OS, Windows OS
- Good Understanding of Vertical, Horizontal and Microservice system architectures
- Eager to learn new concepts and to contribute to Globally deployed distributed system
- Proven analytical and problem-solving skills
- Flexibility and adaptability in regard to learning and understanding new technologies
- Well-organised with ability to meet tight deadlines
- Self-starter and good team player

## Why working with us?

- Collaborative, fun and challenging work environment
- Open, transparent and diverse culture worldwide
- Attractive pay, 13rd salary, Tet bonus, holiday bonus
- Work from home/ hybrid/ remote
- Full insurance coverage, extra medical insurance, annual health check-up

## Contact
Email: selina.nguyen@ottoint.com
Mob: +84 98 789 6545

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
