### ISSUE TITLE
Otto International - BI Architect Devops - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3273]
## How will you make a difference?

- Contribute to the implementation of a modern integrative data architecture including a data lake / data warehouse solution in an AWS Cloud environment
- Achieve a comprehensive integration of the operational systems with our BI solution from Qlik.
- Manage and keep the AWS Cloud environment and the tools installed there permanently up to date
- Proactively identify, research, and resolve technical problems, esp. infrastructure and security related.
- Ensure Data Privacy and Data Security for our data
- Collaboration with external service providers like Amazon, Microsoft and Qlik
- Consultancy and technical support for other BI team members
- Join a cross-functional technical taskforce to leverage your knowledge of AWS and Azure cloud services and Windows servers.
- Develop quality documentation of technical processes and procedures

## Who are we looking for?

- Higher Diploma/ Degree holder in Computer Science or related disciplines
- At least 3 – 5 years of hands-on experience in datacenter administration, system integration and/or technical BI expertise
- Strong knowledge of AWS hosting, QLIK Sense, Data Security/Privacy
- Additional experience with any of QLIK Cloud SaaS, QLIK nPrinting, Power BI, AWS S3, AWS Redshift and/or other BI and Data Lake applications would be a plus
- Familiarity in Amazon Cloud Services (e.g., S3, Lambda, ECS, etc.), AzureAD, CICD (e.g., Jenkins, Terraform, etc.) is an advantage
- Self-directed, organised, results-oriented, strong passion for driving creativity and backing changes
- Good communication skills in English (written and spoken)

## Why working with us?

Collaborative, fun and challenging work environment
Open, transparent and diverse culture worldwide
Attractive pay, 13rd salary, holiday bonus, annual bonus
Flexible working hours, hybrid/ remote
Full insurance coverage, extra medical insurance.

## Contact
Email: selina.nguyen@ottoint.com
Mob:+84 98 789 6545

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
