### ISSUE TITLE
Otto International - BI Business Analyst - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3274]
## How will you make a difference?

- Communicate with stakeholders (management, key accounts and customers) to understand their requirements
- Translate business processes into data structure and reporting requirements.
- Define and analyze report specifications
- Design efficient reports in BI systems (Qlik, Power BI) to meet business and technology needs
- Coordinate with Data Engineers to build and implement complex data model in Qlik Sense and Power BI. Develop data models yourself.
- Fulfil ad hoc report requirements by Management
- Develop and implement test concepts to ensure implementation quality
- Analyze and correct errors
- Provide advice and training to end user
- Prepare system and training documents, such as user manual, training materials and slides
- Gather feedback from end users about system performance
- Promote BI strategy in the company
- Keep abreast of BI trends and developments

## Who are we looking for?

- Higher Diploma/ Degree holder in Business Administration, Data Management or related disciplines
- At least 3 – 5 years of hands-on experience in consulting, business analysis and/or similar position
- Strong knowledge of QLIK Sense and NPrinting or Power BI (or any other BI tools)
- Additional experience with other BI and Date Lake applications would be a plus
- Familiarity in Apparel Sourcing and Logistics processes is an advantage
- Self-directed, organized, results-oriented, strong passion for driving creativity and backing changes
- Good communication skills in English (written and spoken)

## Why working with us?

- Collaborative, fun and challenging work environment
- Open, transparent and diverse culture worldwide
- Attractive pay, 13rd salary, holiday bonus, performance bonus
- Work from home/ hybrid/ remote
- Full insurance coverage, extra medical insurance, annual health check-up.

## Contact
Email: selina.nguyen@ottoint.com
Mob:+84 98 789 6545

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
