### ISSUE TITLE
Otto International - BI Data Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3275]
## How will you make a difference?

- Contribute to the implementation of a modern integrative data architecture including a data lake /data warehouse solution
- Merge data from multiple source systems and reconcile needs of different teams
- Develop a data staging layer to achieve a consistent data quality over all consuming BI systems
- Translate business processes into data structure and reporting requirements.
- Communicate with stakeholders (management, internal teams and customers) to understand their requirements
- Support Business Analysts to develop complex reports, analysis and dashboards
- Design and build complex data models in Qlik Sense and Power BI. Implement complex BI reports based on these data models. Develop and implement test concepts to ensure implementation quality
- Analyze and correct errors
- Define and implement concept for user access rights
- Keep abreast of BI trends and developments

## Who are we looking for?

- Higher Diploma/ Degree holder in Computer Science or related disciplines
- At least 3 – 5 years of hands-on experience in Data Integration and similar position
- Strong knowledge of QLIK Sense and nPrinting or Power BI (or any other BI tools)
- Additional experience with any of QLIK Cloud SaaS, QLIK Compose, QLIK Replicate, AWS S3, AWS Redshift and/or other BI and Data Lake applications would be a plus
- Self-directed, organized, results-oriented, strong passion for driving creativity and backing changes
- Good communication skills in English (written and spoken)

## Why working with us?

•	Collaborative, fun and challenging work environment
•	Open, transparent and diverse culture worldwide
•	Attractive pay, 13rd salary, holiday bonus, performance bonus
•	Work from home/ hybrid/ remote
•	Full insurance coverage, extra medical insurance, annual health check-up.

## Contact
Email: selina.nguyen@ottoint.com
Mob:+84 98 789 6545

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
