### ISSUE TITLE
NAVER Vietnam - Frontend Engineer (Electron Framework, Desktop App)

### ISSUE THREAD

**Issue by LeeHyungGeun** [awesome-jobs/vietnam#3278]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## NAVER Corporation 
* NAVER is an IT company and leading Search, eCommerce, and Advertising in South Korea.
* Search: https://www.naver.com/
* eCommerce: https://shopping.naver.com/
* Music: https://vibe.naver.com/

## You will do 
* Develop a NAVER Music application for Windows/Mac using Electron Framework (Frontend) 

## Requirements
* Ideally, 3+ years of work experience on Electron Framework
* Experience on React, Vue.
* Experience on Mobile App, WebApp
* Good communication skills
* No problem with business trips overseas.

### Opportunity
* Global Company, you will be co-working with Korean, Japanese, and Chinese team.
* Good Career Path in new technology/domain (SSR, SmartOs, SmartTv, WebApp.)
* Working in a FE team with 30+ FE engineers

### Benefit
* Premium Health Care - You, and 2 members of your family
* Annual Health Check
* Gym Membership
* Training Budget
* Book Support
* Equipment Support
* Internet Fee
* Phone Allowance

### Contact
- Ken Lee - Head of FE Engineering - [ken.lee@navercorp.com ](ken.lee@navercorp.com)
  - Please feel free to ask any question. I am really welcome to know all of you.
- Homepage: [https://navercorp.vn](https://navercorp.vn)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
