### ISSUE TITLE
VinHMS - Senior Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by vducdm12** [awesome-jobs/vietnam#3280]
## Location

* Saigon, Vietnam

## Salary Expectation

* $3000/month or range

## Requirements
At least 7 years experiences working with a major programming language (.Net, Java, NodeJS...)

✓ Experience with .Net core, Spring Boot frameworkis plus point
✓ Experience with NodeJS, NetJSframeworkis plus point
✓ Experience with relational database such as MySQL, PostgreSQL
✓ Experience working in Microservices
✓ Experience with Git and Gitflow
✓ Experience with REST/SOAP (GraphQL, gRPC is a plus)
✓ Hands on experience with cloud technology such as AWS, GCP is a plus

### Ideally

* Kafka, GCP Pub/Sub, Redis, ElasticSearch experience
* Understand distributed cache; Understand eventual consistency

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new project in hospitality domain, amusement park, asset management...

### Why it would be awesome to work with us
Friendly, flexible, and fun working environment
✓ Salary negotiable based on individual experience and ability
✓ 13th month of salary, Great opportunity for career development
✓ Team building, monthly party, etc.

### Contact
Homepage: https://www.vinhms.com
Address: Toong Co -Working Space, No. 188 Vo Thi SauStreet, Vo Thi Sau Ward , Dist. 3, HCMC
Email to: v.tailt7@cloudhms.net; Phone No.: 0917 890 123/ Mr. Tai

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
