### ISSUE TITLE
Senior Fullstack Developer 

### ISSUE THREAD

**Issue by ngocthao205** [awesome-jobs/vietnam#3282]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Salary negotiation

## Requirements
* Develop web application using NodeJS
* Developer views with different Java scrip frameworks such as: ReactJS
* Apply Azure Cloud services on application development

### Must Have
* NodeJS
* ReactJS
* Or React Native
* At least 3+ years in Full stack Developer experience
* Be familiar with technologies: NodeJS, ReactJS, Javascript/ HTML/ CSS, MySQL, Git , Linux,...
* Knowledge in responsive design technique and frontend optimization techniques

### Ideally

* Experience with React Native/ Vue JS

### Responsibilities

Great power comes with great responsibilities!

### Why it would be awesome to work with us
* Interesting projects in many domain
* Career path clearly with Microsoft courses.
* Everyone is willing to support each other
### Activity
* Office Happy Hour, game, team buildings,...
* Sport club: soccer, badminton,...

### Contact
HR Department: 
Email: hr@nois.vn 
Contact: +84 28 6681 0782

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
