### ISSUE TITLE
ADAPTIS - Technical Recruiter - HCM - [FT Remote Hybrid]

### ISSUE THREAD

**Issue by Minhle93** [awesome-jobs/vietnam#3284]
## Location

* Ho Chi Minh, Vietnam
* Remote/Hybrid

## Salary Expectation

* Negotiable

## Requirements
* Headhunt candidates: Java, .NET, PHP, etc… via networking and Job boards (Linkedin, Facebook, Vietnamworks, ITviec, TopCV, etc.)
* Screen qualified CVs for interview round
* Interview, select high potential candidates for the shortlist
* Consult Division Manager to offer high-quality candidates for projects
* Negotiate, manage the offer process
* Take part in Employer Branding, develop communication channels to attract potential candidates

### Must Have
* 3+ years of experience in IT industry 
* Strong knowledge and solid experience in IT recruitment
* Have wide network in IT especially in Java, .NET and PHP
* Excellent skill in screening, headhunting, interviewing candidates
* Excellent communication, persuasion, and negotiation skills
* Flexibility, high responsibility, and ability to work independently and under high pressure
* Good interpersonal and teamwork skills
* Good experience in employer branding, developing communication channels to potential candidates is a plus

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us
* 13rd month salary
* Bonus 1 month salary (14th salary) for 3 years of service
* Premium healthcare package
* Unlimited paid days off 
* Allow to work from home/remote
* Whoopie Fridays where people can meet, chat, and exchange knowledge 
* Quarterly team building activities
* Macbook equipment

### Contact
Email: linh.nguyen@adaptis.io
Skype: live:.cid.246de80c0688d565
Website: https://adaptis.io/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
