### ISSUE TITLE
NAKIVO - Project Manager - HCM (Phu Nhuan) - Fulltime - *Hot Signin Bonus*

### ISSUE THREAD

**Issue by huongnguyenhr** [awesome-jobs/vietnam#3285]
## Location

* **Halo Building**, 16 Le Quy Don, Ward 12, Phu Nhuan District, HCMC. 

## Salary Expectation

* Negotiable | We are offering 0.5month of Sign-in bonus to the candidate who can join us within 30 days of you being offered. 

## Requirements: 
* Bachelor’s degree in Computer Science or related field, advanced degree preferred, or equivalent.
* 3+ years of project management experience in the IT/Software industry (with at least 5+ years of software engineering, systems engineering or similar experience).
* Experience in traditional SDLC, Agile methodologies (SCRUM, Kanban,...) and have acceptable knowledge with the others.
* Strong experience with people management and resource management for a large project or organization.
* Proven experience in scope definition, project estimation, quality management, resource management and/or risk management
* Strong familiarity with project management software tools, methodologies, and best practices.
* Ability to effectively present and report project status to high-level management.
* Ability to work with cross-functional and distributed development teams.
* Ability to react to project adjustments and alterations promptly and efficiently.
* Advanced English (fluent preferable).
* Excellent analytical, verbal, and written communication skills.

### Ideally

* Project Management Professional (PMP) certification preferred.
* Highly responsible, well-organized, communicative, pro-active, dare-to-lead and dare-to-do attitude
* Technical stacks: Java, HTML, CSS, C/C++, VMware, Hyper-V, AWS EC2,...
* Experience with Jira, Confluence, SVN, TeamCity.

### Responsibilities

* Manage the international development teams to ensure that assigned duties meet the business requirements and the company's objectives.
* Build and manage the project plans to ensure works are identified, assigned and completed on time with good quality.
* Organize and run meetings to ensure the transparency of information between management and development.
* Manage changes to different aspects of the project (scope, schedule, quality indexes,...).
* Create and maintain comprehensive project documentation throughout the entire process.
* Identify,** track, manage, prevent and resolve any project issues that may occur.
* Measure and report project performance using appropriate tools and techniques.
* Perform risk management to minimize project risks.

### Why it would be awesome to work with us

The Nakivo team in Vietnam has been changing very fast in the recent years, we have grown from a group of 6 engineers to the current team size of 80 and we are expecting to grow even more in the next following years. 

We welcome and embrace people, regardless of their background, religion, nationality or gender, but focus on diversity, contribution, determination and work ethic. At Nakivo, we are trying to improve everyday, to become a competitive choice for talented people, by offering

* Flexible working hours: Office opens from 6.00 AM to 10.00 PM
* 13-month bonus & performance bonus
* 100% salary on probationary period
* Private health care package
* Premium health care check
* Gift (cash/voucher) for every special occasion: New Year's Eve, Tet holidays, International Women's Day, International Children's Day, Mid-Autumn Festival and Birthday
* Up to 15 annual leaves/year and additional leaves (up to 3 days)
* Team building
* Free and un-limited snack, tea, coffee and by-choice request.

### About Nakivo Inc. 

NAKIVO Inc. is a privately held company that develops data protection and site recovery software for SMB and enterprise market since 2012.

The solution developed by the company, NAKIVO Backup & Replication, is used by over 15,000 companies worldwide to protect their critical data in virtualized and hybrid environments.

NAKIVO has a global presence with over 4,000 channel partners in 140+ countries.

Close to 300 hosting, managed, and cloud service providers are currently using NAKIVOs software to deliver VM BaaS, RaaS, and DRaaS to their customers.

NAKIVO has an impressive track record of 5-star community reviews and over 97% customer satisfaction with support, and has also won a Best of VMworld 2018” Gold Award for Data Protection at VMworld 2018 US. Customers trust us and we aim to deliver on that trust.

Website: https://www.nakivo.com/

### Contact
Email: hr.vn@nakivo.com | huong.nguyen@nakivo.com
Phone: +84964210168 (Skype/ Zalo) - Ms. Hương

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
