### ISSUE TITLE
Backend developers (Ruby on rails,PHP,Javascript) - gumi Vietnam

### ISSUE THREAD

**Issue by PhamQuiToan** [awesome-jobs/vietnam#329]
We are looking for experienced Developers with experience in Ruby on Rails or PHP 
This position will play the primary role to deliver high-quality projects to our customers and to boost our development team to a higher level. This is a key role in achieving further growth and requires a bright, focused and creative mind to do.
 
## Require Skills
- Experience with Ruby On Rails or PHP development and some of server-side languages such as Node JS, Java, ...
- Experience with automated test and Test Driven Development 
- Knowledge about DB design, IT-architecture and object oriented frameworks
- Knowledge about Git and preferably GitHub 
- Excited with new technology about Unity, Oculus, ...
- Basic knowledge about Javascript, HTML and CSS 
- Fluent in English

## Big Plus +++++ Doesn't require

- Knowledge about PHP frameworks
- Comfortably using Front-end frameworks such as Bootstrap, Foundation ...
- Hosting and deployment in the cloud - e.g. Amazon  - Speaking Japanese, seriously 

## Why You'll Love Working Here
- Working in a professional, friendly, well-equipped environment both with Japanese and Vietnamese.
- Month 13th salary.
- Career path promotional opportunities
Bonus base on performance.
- Labor contract ,insurance, annual days off are based on Vietnamese law.
- Birthday party, Welcome party or monthly company party.
- Company trip each year.

## Location

- 9 Nguyễn Thị Diệu, Quận 3, TP. Hồ Chí Minh

## Salary

- Negotiable

## Contact

- Please send your application to: contact@gumiviet.com
- The applications must include: (Please specify the position you are applying in the Subject of the email)
- Website: http://www.gumiviet.com/

**Comment by joneslee85** [comment]
@PhamQuiToan please revise your post, we do not allow one post to cover mixture of programming languages. Please split them into separate post and provide relevant details in accordance. Furthermore, the format of title does not comply with our guideline. Lastly, please have a section to introduce about your company and type of projects. 

Few nitpicks, `Speaking Japanese, seriously` - what do you mean by the word `seriously`?

**Comment by PhamQuiToan** [comment]
I have just updated as your comment.
Please check it again.
