### ISSUE TITLE
ADAPTIS - Technical Project Manager - HCM - [FT Remote Hybrid]

### ISSUE THREAD

**Issue by Minhle93** [awesome-jobs/vietnam#3291]
## Location

* Ho Chi Minh, Vietnam
* Remote/Hybrid

## Salary Expectation

* Negotiable

## Requirements
* Have at least 2 years experience in project management 
* Have knowledge about the process of developing software and basic knowledge about PMP (no certification required)
* Have experience of Scrum framework, rules, and practices
* Have good communication skills to work with clients
* Solid knowledge of software requirements, development process, project management and leadership
* Good human relation skills, ability to collaborate effectively across departments and teams
* English level: intermediate

### Responsibilities

* Developing a project plan, monitoring progress, and tracking the progress and workload
* Managing stakeholders’ expectations, as well as prioritizing and negotiating timelines and deliverables to meet key business objectives
* Delivering projects on time ensuring quality standards are met
* Play the role of Scrum Master to coach and facilitate one or many teams following the agile approach
* Managing project workstreams and key metrics within JIRA, Confluence, and available tools
* Generating project/program reports for executive management with metrics
* Taking initiative in improving reporting, processes, workflow, and outcomes
* Connect team members, build team spirit

### Why it would be awesome to work with us
* 13rd month salary
* Bonus 1 month salary (14th salary) for 3 years of service
* Premium healthcare package
* Unlimited paid days off 
* Allow to work from home/remote
* Whoopie Fridays where people can meet, chat, and exchange knowledge 
* Quarterly team building activities
* Macbook equipment

### Contact
Email: [linh.nguyen@adaptis.io](mailto:linh.nguyen@adaptis.io)
Skype: live:.cid.246de80c0688d565
Website: https://adaptis.io/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
