### ISSUE TITLE
Littlelives - Senior  DevOps Engineer - HCMC - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#3294]
We are looking for a performance-driven DevOps engineer who enjoys working in close-knit product team and is excited about the prospect of helping us scale our technology. LittleLives is a leading EduTech company used by thousands of preschools and we're looking to expand our team!

## Location

* Ho Chi Minh City

## Salary Expectation

* 1500$ -> 3000$ per month

## What you will be doing: 

- Building and maintaining tools to streamline various aspects of the engineering operations
- Performance testing and stress simulations of production environments
- Monitor system health to reduce detection time and provision disaster recovery systems to reduce response time
- Enforce security by design philosophy and implement safeguards at every phase of development
- Automate repetitive tasks involving deployment, maintenance and reporting
- Measure performance to expose new weaknesses in the infrastructure
- Review costs regularly with management and strategize changes to the infrastructure to meet product and scaling goals

### Must Have

- Planned and developed your development team's CI/CD process
- Managed infrastructure as code with experience using Terraform or similar tools
- First-hand experience in container development and orchestration
- Extensive knowledge in AWS, Alibaba Cloud or GCP
- Comfortable in Linux and scripting languages like Python

### Ideally

- Experience managing helm charts in Kubernetes
- Built a comprehensive monitoring framework for a large application
- Gone through infrastructure audits for compliance such as in ISO 27001 or SOC 2
- Managed a tech product used by millions of users

### Why it would be awesome to work with us

- We WILL push you to learn new things together
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Personalized leadership growth based on your strengths
- Global scale

### Contact
Homepage:  https://www.littlelives.com
Email : changinglives@littlelives.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
