### ISSUE TITLE
Littlelives - Senior Backend Engineer (NodeJs/Elixir)- HCMC - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#3295]
We are looking for an inspired Back End Developer who loves tinkering with APIs and working with data. LittleLives is a leading education technology company used in over a thousand preschools in 10 countries, and we are looking to expand our Back End team!

## Location

* Ho Chi Minh City

## Salary Expectation

* 1500$ -> 3000$ per month

### What you will be doing: 

- Develop backend services in Node.js or Elixir for in our existing APIs
- Using Java to create robust enterprise level APIs for our customer integrations
- R&D novel and ingenious solutions to create enhanced scalable applications tailored to a multitude of global regions
- Continuously enhance the app with the latest code-improving methodologies and security enhancements available
- Use modern DevOps tools and automate everything with Docker and our Kubernetes clusters

### What's in it for you

- Make running a service that is consumed by tens of thousands of users look effortless with an efficient and autoscaled infrastructure
- Expertly maintain end-to-end monitoring of our applications
- Further develop solid developer operation practices like collaborative documentation, peer review and automated testing
- Hone your security experience through closely working with our senior DevOps and external consultants

### Must Have

- Deep expertise in Elixir/Rails or NodeJs
- Containers are first class in your apps
- Familiar with GraphQL or other modern query languages and transport protocols
- Sound coding practices with tools such as git, unit testing, CI/CD, service oriented architecture
- Linux confidence
- Production experience with handling large request concurrency and performance optimizations
- Solid understanding of information security

### Ideally

- Competency in functional programming. We welcome you to our Elixir apps
- Managed Kubernetes, Helm charts on your own

### Why it would be awesome to work with us

- We WILL push you to learn new things together
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Personalized leadership growth based on your strengths
- Global scale

### Contact
Homepage:  https://www.littlelives.com
Email : changinglives@littlelives.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
