### ISSUE TITLE
Sr Full-stack NodeJS/React Dev (Remote)

### ISSUE THREAD

**Issue by liemdo** [awesome-jobs/vietnam#3296]
![Artwork 48@3x](https://user-images.githubusercontent.com/989817/160039807-93f7407a-0021-467a-8516-742134e882b8.png)

We're a small team of 5 in the US and Vietnam working on a collaborative phone system that changes the way businesses communicate. Our team has a strong business and engineering background from Expedia, Thales, and Walt Disney. Since we launched the product last year, we have over 600 customers across US and Canada and our team is growing. We're looking for a world-class engineer to join us on this exciting journey!

## Location
* Remote

## Salary Expectation

* 1,500 - 2,000 USD

## Responsibilities

- Working remotely full-time on an exciting project to build a complex web & mobile app
- Be the go-to resource for the team
- Help define architecture to grow our internal and external APIs.
- Participate in design reviews, implementation reviews
- Communicate throughout the day with the team via Slack.

### Must Have

- 3+ years in web development
- Comfort with "vanilla" JS is a must
- Love unit testing.
- Must have a strong understanding of UI, cross-platform / cross-browser compatibility, general web functions and standards.
- React

### Ideally

* Experience with (not required. You can learn from us!)
- Postgres
- GraphQL
- React Native
- NodeJS

### Why it would be awesome to work with us

By joining us, you have an opportunity to shine using your world-class skills along with a professional and passionate team. As an engineering startup at heart, here are what you can expect when working with us:

We use the latest technologies in the industry such GraphQL, Docker, and React Native. If you don't have experience in any of our technologies, a strong engineering foundation works too.
We do code reviews. Good engineers love code reviewing and writing test!
We love engineers who think big and want to be leaders in the field.
Work remotely from anywhere you like.

### Contact
Homepage: ringblaze.com
Liem Do <ldo@ringblaze.com>

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
