### ISSUE TITLE
BACKEND DEVELOPER - OOOLAB - (PYTHON/GO)

### ISSUE THREAD

**Issue by MyTien13** [awesome-jobs/vietnam#3297]
## HCM 

* Saigon, Vietnam
* Remote Full Time (Go to the office 1-2 times/month for meeting)

## Salary Expectation

* Attractive offers base on your experience and performance

## Requirements

* Minimum 2 years of experience working with Python/Flask and PostgreSQL
* Experience with automation tools such as Docker, Jenkins, Kubernetes
* Highly preferred if the candidate has experience working with any of the following: AWS, ElasticSearch, Celery, Redis.

### BONUS if you have experience with any of the following

* DevOps
* React/React Native
* NodeJS
* RealTime technologies, Jitsi
* Experience working in the field of Education

### Responsibilities

* Working on building an LMS for educational institutions all around the globe!
* Working on Virtual Classrooms, Content Builders, Logistics Apps, etc.

### Why it would be awesome to work with us
* Competitive salary depending on skills and capabilities;
* Comfortable working conditions and flexible working time;
* Friendly and funny colleagues (and free snacks!);
* Opportunities for promotion, career development, and mentorship;
* Dynamic, fast-paced, professional, fun, and exciting start-up work environment.
Interested candidates can send your resume via this link: [https://ooolab.freshteam.com/jobs/8ulPeFRxU3sh/back-end-developer](url)
### Contact
Email: tien,htm@1on1english,vn
Phone: (028) 7101 6668 (Ms. Tien) or (Ms. Phuong)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
