### ISSUE TITLE
Senior Frontend Developer - full-time Remote 

### ISSUE THREAD

**Issue by bich166** [awesome-jobs/vietnam#3299]
## Location

* Saigon, Vietnam
* Remote/ Hybrid

## Salary Expectation

* around 4000$ /month (Gross)

## Requirements and Responsibility 
We are looking for a passionate front-end developer with experience in building user-friendly web interfaces in React.

Some examples of work will be creating a widget-based dashboard for charts, images, and other various applications from within our IoT platform.

The API is stable and hosts a variety of data interrogation tools and we are looking for someone with an autonomous and driven attitude to make design choices and implement them into the specific areas requiring improvement.

The system is 100% greenfield, was started 6 months ago, and has been developed with an event-driven lightweight architecture.

Any applicant with demonstrated 5+ year commercial experience in React, or relevant tertiary qualifications will be considered.

Our Stack:

AWS Lambda Node API Microservice

AWS S3 React Typescript

Docker/GitHub/Jira

### Must Have

* Excellent in Javascript, especially in Reactjs 
* Good command in English 

### Contact
Email: bich.le@sharesource.com.au
Phone/Zalo: 0906994770 - Bich

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
