### ISSUE TITLE
Naver Vietnam - Windows Desktop App Engineer (C/C++/C#) - Saigon - FT

### ISSUE THREAD

**Issue by wendyquynhh** [awesome-jobs/vietnam#3301]
**About NAVER & NAVER VIETNAM:**
NAVER Co., Ltd. is South Korea’s largest web search engine, as well as a global ICT brand that provides services including LINE messenger, currently with over 200 million users from around the world, the SNOW video app, and the digital comics platform NAVER WEBTOON. NAVER BAND, a group social media platform, boasts one million monthly active users.

The sustained research and development of AI, robotics, mobility, and other future technology trends are propelling NAVER forward, in pursuit of the transformation and innovation of technology platforms, while it also remains devoted to a paradigm of shared growth, joining hands with users from the global community as well as a vast number of partnerships. In 2018, NAVER was ranked as the 9th most innovative company by Forbes and top 6th Future 50 company by Fortune magazine.

**Inside NAVER’s engineers:**
NAVER is a place where you can grow together with your colleagues by sharing your best skills and experience as a software engineer. NAVER engineers are the people who take pleasure in finding meaningful work and accomplishing challenging goals.

**WE ARE LOOKING FOR WINDOWS DESKTOP APP ENGINEERS** 

**Your daily tasks:**

- Participate in the development of the company service project
- Development of native Windows desktop applications (C#, C/C++, VC++)
- Continue to learn new technologies, introduce existing products, improve the product experience and create more value.

**Your Skills and Experience**

**For C#:** 
- Full time Bachelor’s degree or above in Engineering, IT or similar field, and you should have equivalent experience in software engineering with at least 5 years of hands-on work.
- Hands-on experience development of native Windows desktop .NET applications using C# code.
- Research and incorporate the latest features of C#, .NET/Core, WPF, WinUI into our applications
- Familiarity with upcoming .NET technologies such as WinUI and MAUI(.Net 6)
- Skill for writing reusable C# and C# libraries.
- Understanding fundamental design principles behind a scalable application
- Excellent design, coding, debugging, and problem-solving skills.
- In-depth understanding of object-oriented programming ideas and design patterns, excellent coding habits.
- Familiar with common network communication protocols and proficient in using common encrypting algorithms.

**For C/C++:**
- Full time Bachelor’s degree or above in Engineering, IT or similar field, and you should have equivalent experience in software engineering with at least 5 years of hands-on work.
- Strong Object-Oriented Design skills & C/C++, VC++ programming Skills
- Hands-on experience Windows SDK & WIN32 system programming
- Excellent design, coding, debugging, and problem-solving skills.
- In-depth understanding of object-oriented programming ideas and design patterns, excellent coding habits.
- Familiar with common network communication protocols and proficient in using common encrypting algorithms.

**It 'll be a big plus if you:**
- Good at communication and problem-solving.
- Experience with Windows architecture and internals.

**Our attractive offers include:**
- A-class brand new office at Viettel Building (District 10, HCM)
- Opportunity to be involved in a working environment with the latest technologies
- Competitive salary and benefits including a Premium medical insurance plan for you and your family
- Overtime, Incentive Bonus
- Performance appraisal every year
- Annual leave 14 days, add 1 day to every year
- The annual budget for self-learning
- One-off allowance for setting up working from home corner

**Contact**
Homepage: https://boards.greenhouse.io/navervietnam
Email: [wendy.quynh@navercorp.com](mailto:wendy.quynh@navercorp.com)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
