### ISSUE TITLE
Naver Vietnam - iOS Engineer (Swift) - Saigon - FT

### ISSUE THREAD

**Issue by wendyquynhh** [awesome-jobs/vietnam#3302]
**About NAVER & NAVER VIETNAM:**
NAVER Co., Ltd. is South Korea’s largest web search engine, as well as a global ICT brand that provides services including LINE messenger, currently with over 200 million users from around the world, the SNOW video app, and the digital comics platform NAVER WEBTOON. NAVER BAND, a group social media platform, boasts one million monthly active users.
The sustained research and development of AI, robotics, mobility, and other future technology trends are propelling NAVER forward, in pursuit of the transformation and innovation of technology platforms, while it also remains devoted to a paradigm of shared growth, joining hands with users from the global community as well as a vast number of partnerships. In 2018, NAVER was ranked as the 9th most innovative company by Forbes and top 6th Future 50 company by Fortune magazine.

**Inside NAVER’s engineers:**
NAVER is a place where you can grow together with your colleagues by sharing your best skills and experience as a software engineer. NAVER engineers are the people who take pleasure in finding meaningful work and accomplishing challenging goals.

**We are looking for Senior iOS Engineer.** 

**Your day-to-day :** 
- Develop iOS App part of various NAVER Services.
- Technical research, Test, Design and implement key components of the external device support for media service in the iOS environment.
  (e.g. WatchOS, AppleTV, CarPlay, google cast)

**Your qualifications:** 
- 3 years or over of experience in iOS application development.
- Background in computer science and engineering.
- knowledge in Object-Oriented and functional programming, Design Patterns.
- Understanding of Cocoa Touch Frameworks.
- Experience using Swift language.
- Understanding of Data Structure, Algorithm, Distributed System.
- Experience in Git (Merging, branching ...)
- Understand the importance of writing high Maintainable Code, Clean Code.
- Open-minded, honest and have a positive attitude towards people.
- Good at communication skills in general and English skills in particular
- No problem with business trips overseas.

**It's a big plus if you**
- Have experience in multi media projects.
- Have experience in global service operation & development.
- Have experience in using Core Animation framework.
- Have experience in using RxSwift or Combine framework.
- Have Korean speaking.

**Our attractive offers include:**
- A-class brand new office at Viettel Building (District 10, HCM)
- Opportunity to be involved in a working environment with the latest technologies
- Competitive salary and benefits including a Premium medical insurance plan for you and your family
- Overtime, Incentive Bonus
- Performance appraisal every year
- Annual leave 14 days, add 1 day to every year
- The annual budget for self-learning
- One-off allowance for setting up working from home corner

**Contact**
Homepage: https://boards.greenhouse.io/navervietnam
Email: wendy.quynh@navercorp.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
