### ISSUE TITLE
Danh Khôi - .Net Developer - All level (Urgent) - Up to 3000 USD GROSS - Saigon - FT

### ISSUE THREAD

**Issue by nghiangodinh** [awesome-jobs/vietnam#3303]
##  89 Phan Đình Phùng, P.17, Q. Phú Nhuận, Tp. HCM

* Saigon, Vietnam
*  Fulltime

## Salary Expectation

* Up to $3000/month or range

## Requirements
+ Tốt nghiệp Đại Học chuyên CNTT hoặc các chuyên ngành liên quan  
+ Kiến thức sâu rộng về C# và .NET Core 3.0+  
+ Tối thiểu 3 năm kinh nghiệm trong lĩnh vực phát triển phần mềm sử dụng công nghệ của Microsoft  
+ Có kinh nghiệm về C# và .NET Core 3.0+  
+ Có kinh nghiệm về OOP, đặc biệt các nguyên tắc SOLID  
+ Kiến thức về phát triển SQL Server và thiết kế cơ sở dữ liệu  
+ Có kinh nghiệm về [ASP.NET](http://asp.net/) MVC/Web API, Entity Framework/Dapper là một điểm cộng  
+ Có kinh nghiệm Git và Gitflow  
+ Có kinh nghiệm trong công nghệ đám mây như Azure là điểm cộng  
+ Khả năng viết code có thể bảo trì và kiểm tra tốt  
+ Tự tin về mặt kỹ thuật, có khả năng linh hoạt và tinh thần làm việc nhóm tốt  
+ Khả năng phát triển trong môi trường tự tổ chức, có mong muốn đóng góp kiến thức vào việc thiết kế và định hướng tổng thể.

## Skills
* Có kinh nghiệm C# / .NET Core / REST APIs
* Có kinh nghiệm tham gia dự án sử dụng Microserices
* Quen thuộc Agile / Scrum 
* Biết sử dụng Microsoft Azure

### You’ll be responsible for

Nhằm đẩy mạnh xây dựng giải pháp cho ngành bất động sản, Tập đoàn Danh Khôi (http://danhkhoi.com.vn/) tuyển thêm 4 vị trí cho Phòng Phát triển ứng dụng với mức lương hấp dẫn và nhiều chính sách đãi ngộ, trong một môi trường năng động và hiện đại.

### Contact
Homepage: http://danhkhoi.com.vn
Contact: nghiand@danhkhoi.com.vn (cellphone: 0903 800 622)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
