### ISSUE TITLE
Danh Khoi Group - .Net Developer - All level (Urgent) - Up to 3000 USD GROSS - Saigon - FT 

### ISSUE THREAD

**Issue by nghiangodinh** [awesome-jobs/vietnam#3306]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Up to $3000/month or range

## Requirements

* Bachelor’s degree in Computer Science 

* Minimum 3+ years of experience in software development using Microsoft Technologies 

* Experience in C# as well as .NET Core 3.0+ 

* Experience in OOP, especially SOLID principles 

* Knowledge of SQL Server development and database design 

* Experience in ASP.NET MVC/Web API, Entity Framework/Dapper is a plus 

* Experience with Git and Gitflow 

* Hands on experience with cloud technology such as Azure is a plus 

* Technically confidence, flexibility and a strong team spirit 

* Good at writing maintainable and testable codes 

### You’ll be responsible for

* Be actively involved in the complete project lifecycle, from requirements analysis to final delivery. 

* Build a customer facing product across the whole software development life cycle 

* Design and build distributed systems, including both back-end and front-end components 

* Build software that is highly available, performant, scalable, and extensible 

* Work with cross-functional teams including UI/UX designers, product managers, and other software engineers 

### Contact
Homepage: http://danhkhoi.com.vn
Email: nghiand@danhkhoi.com.vn (+84 903 800 622)

**Comment by Kieutranghd** [comment]
Cho em hỏi job này công ty có thể mở rộng cho ứng viên remote không ạ? Em cảm ơn anh Nghĩa!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
