### ISSUE TITLE
Leflair - AngularJS / NodeJS Developer - Saigon - FT

### ISSUE THREAD

**Issue by angiedang** [awesome-jobs/vietnam#331]
![img_7142-smallersize](https://cloud.githubusercontent.com/assets/22335722/18940837/e77fa266-8635-11e6-866b-f1443a01b828.jpg)
## Location
- Saigon, Vietnam
## Salary Expectation
- $2000++/month 
## Requirements
- Work with the CTO to build our ecommerce web site and management platform
- Implement site designs using HTML5, CSS3, Bootstrap, AngularJS
- Develop our backend APIs using Node.js
- Work with NoSQL and SQL databases
- Test our applications
- Code review and refactoring
### Must Have
- AngularJS / Javascript
- Node.js 
- HTML5, CSS3, Bootstrap
- Responsive Design
- Git
- Automated Testing
- Strong English skills are necessary
- Good communications skills
### Ideally
- MongoDB/Mongoose
- Grunt, Gulp etc.
- CI/CD Tools
- Cloud Infrastructure and Docker
- Microservices Architecture
### Responsibilities

Show up at work and create awesomeness
### You’ll be responsible for
- Perfecting our site www.leflair.vn
### You can bring
- Logical thinking and analysis
- Attention to detail
### Contact

angie@leflair.vn or apply on our Career Page www.leflair.co/careers

**Comment by angiedang** [comment]
![img_7142-smallersize](https://cloud.githubusercontent.com/assets/22335722/18940548/45df62d6-8633-11e6-92fe-263e666443af.jpg)

**Comment by joneslee85** [comment]
@angiedang please put the photo in the original post
