### ISSUE TITLE
EWAY.,JSC - PHP Laravel Developer - HN

### ISSUE THREAD

**Issue by tranghnnh** [awesome-jobs/vietnam#3311]
## We are
AdFlex is a company that advertises and distributes powerful products in the Vietnamese and international markets.
G8 platform is a product of AdFlex, providing solutions to help brands/merchants increase online sales and performance. Currently, G8's market is expanding across major countries in Southeast Asia such as Vietnam, Thailand, Indonesia, Malaysia, Philippines with the goal of becoming the leading platform in online sales performance in Southeast Asia.

## Location

* Ecolife Capital, Nam Tu Liem District, Hanoi, Vietnam

## Salary Expectation

* $700-1200/month

## Requirements
* 1+ year experience as PHP Laravel Developer

### Must Have

* Participated in a product project
* Familiarity with PHP (Laravel), MongoDB, Docker, K8s
* Interface mindset (UI/UX)

### Ideally

* Experience with document database ElasticSearch, MongoDB
* Have worked in a product company or built a demo product

### Responsibilities

* Responsible for developing and operating website services running in PHP
* Coordinating with business departments to implememt the project.

### Why it would be awesome to work with us

* Bonus: 13th-month salary, project, personal achievement, holiday 
* PTI insurance at leading hospitals (payment 60 million/year), support to pay for relatives.
* Free lunch at company's internal canteen.
* Company trip, Year-end party, Half-year party, team-building
* Computer allowance 400-500,000d/month (depending on machine configuration)
* Young, fun and creative environment.
* All ideas are recognized and supported
* Income commensurate with the results and value created.

### Contact
Email: [tuyendung@eway.vn](mailto:tuyendung@eway.vn)
Phone: 096 998 2552

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
