### ISSUE TITLE
UI / UX Developer - Hotwire Ruby on Rails UI - 

### ISSUE THREAD

**Issue by rafaqat** [awesome-jobs/vietnam#3312]
## Location

* 100% Remote

## Salary Expectation

* $1500/month or range

## Requirements
* Ruby/Rails
* Javascript
* React
* Figma/XD

## Skills

I am looking for a UI/UX developer for my client project - if you love build UI's and love javascript style and templates this is the job for you

We will be build amazing UI/UX screens with a global team based in US/Europe and Taiwan

https://hotwired.dev/

### Must Have

* UI experience

### Responsibilities

You will be the lead developer on an exciting e-commerce project

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analysis skill

### Why it would be awesome to work with us

* we are all developers and our company culture is developer lead

### Contact

Contact: rafaqat at gmail dot com (mobile number optional)
whatsapp: +447810155802

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
