### ISSUE TITLE
Doctor Anywhere - Mid/ Sr Frontend Engineer (ReactJS/ Angular) - HCM/ HN - FT

### ISSUE THREAD

**Issue by giangvu1304** [awesome-jobs/vietnam#3313]
## About Doctor Anywhere
Doctor Anywhere (DA) is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, **DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa**, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Malaysia, Thailand, Philippines, Vietnam, Indonesia and India, serving more than 2.5 million (and growing) users across the region.

At DA, we believe in the value of innovation and collaboration. Grounded in our motto of “Keep Going, Keep Growing”, our team strives towards excellence every day, and values diversity in perspectives brought by every member. Together, we bring quality healthcare to your doorstep!

## About the team
Our Technology team is the backbone of our business. The team is responsible for building a reliable, scalable and compatible platform for our product and services. Our Engineering team consists of talented and passionate engineers that focus on Full Stack (Back-end & Front-end), Mobile, QA across the regions and work closely with Data, Infrastructure & Security, Product team and with the cross functional team to continuously improve and scale our products forward.

## About the role
As Software Engineer, you will be responsible for all aspects of product development from initialization till rolled-out. **You will be working on architecture, design, implementation, testing, and production support**. The ideal candidate will have strong ownership, good communication skills, enjoy working in highly collaborative and fast paced environments.
* Delivering a complete front end application
* Ensuring high performance on mobile and desktop
* Writing tested, idiomatic, and documented JavaScript, HTML and CSS
* Writing non-blocking code, and resorting to advanced techniques such as multi-threading, when needed
* Cooperating with the back-end developer in the process of building the RESTful API
* Communicating with external web services
* Collaborate with cross-functional teams to define, design, and ship new features
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency
* Creating custom, general use modules and components which extend the elements and modules of core Angular
* Help maintain code quality, organization, and automatization
* Develop applications for time-sensitive projects while considering business/system requirements
* Writing extensive unit tests using automated TDD tasks
* Creating e2e test suites for all components, and running them with Protractor (or a well reasoned alternative)

## Location

* Ho Chi Minh, Vietnam
* Ha Noi, Viet Nam
* Hybrid Working

## Salary expectation

* $1500 - $3500 per month
* Open for negotiation 

## Requirements
* Bachelor's degree in Computer Science with 4+ years of relevant experience in building web applications,
* Proficiency with JavaScript, HTML5 and TypeScript 2.4
* Deep knowledge of **Angular 5+/ React practices** and commonly used modules based on extensive work experience
* Extensive knowledge of CSS and JS methods for providing performant visual effects and keeping the framerate above 30fps at all times
* Thorough understanding of the responsibilities of the platform, database, API, caching layer, proxies, and other web services used in the system
* Experienced in building the infrastructure for serving the front-end app and assets
* Experienced in architecting and automating the build process for production, using task runners or scripts
* A start-up attitude - you take full ownership of things that you do, willing to go out of your comfort zones and take on new challenges.
* Comfortable with ambiguity and flexible to learn new things - we’re not done growing, and heading into uncharted territories is part of the fun!
* English communication skills will be required to work with regional technology team and stakeholders.

### Why it would be awesome to work with us
* English & flexible working environment
* A strong tech team with leaders and members from Traveloka, Amazon,...
* Promising product-based companies with millions of users across SEA.
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th month salary
* Insurance in full gross salary, Premium Healthcare Insurance

### Fun facts about us
* Raising SGD$88 mil (US$65.8 mil) in Series C fundraising in August 2021.
* 3 regional tech hubs in Singapore, India and Vietnam.
* Acquiring Doctor Raksa, the biggest telemedicine platform in Thailand
* 50% growth in full-time employees, to 450 across the region.
* More information: [here](https://doctoranywhere.com/blog/2021/12/30/2021-year-of-impact/)

### Contact
* Direct Application for Frontend Engineer (React): [link](https://doctoranywhere.bamboohr.com/jobs/view.php?id=173)
* Direct Application for Frontend Engineer (Angular): [link](https://doctoranywhere.bamboohr.com/jobs/view.php?id=426)
* Email: giang.vu@doctoranywhere.com for further discussion. We are just a message away.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
