### ISSUE TITLE
Doctor Anywhere - Mid/ Sr Backend Engineer (Java) - HCM/ HN - FT

### ISSUE THREAD

**Issue by giangvu1304** [awesome-jobs/vietnam#3314]
## About Doctor Anywhere
Doctor Anywhere (DA) is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, **DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa**, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Malaysia, Thailand, Philippines, Vietnam, Indonesia and India, serving more than 2.5 million (and growing) users across the region.

At DA, we believe in the value of innovation and collaboration. Grounded in our motto of “Keep Going, Keep Growing”, our team strives towards excellence every day, and values diversity in perspectives brought by every member. Together, we bring quality healthcare to your doorstep!

## About the team
Our Technology team is the backbone of our business. The team is responsible for building a reliable, scalable and compatible platform for our product and services. Our Engineering team consists of talented and passionate engineers that focus on Full Stack (Back-end & Front-end), Mobile, QA across the regions and work closely with Data, Infrastructure & Security, Product team and with the cross functional team to continuously improve and scale our products forward.

## About the role
We are seeking an enthusiastic and self-motivated Backend Engineer to join our engineering team to work on large scale, complex system that brings innovation to healthcare. You will be working on modern technology stack and in a cross-functional environment that promotes collaboration within/across teams and managing both internal/external stakeholders.

You will be responsible for all aspects of product development from initialization till rolled-out. You will be working on architecture, design, implementation, testing, and production support. The ideal candidate will have strong ownership, good communication skills, enjoy working in highly collaborative and fast paced environments.

* Collaborate with cross-functional teams to define, design, and ship new features.
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.
* Ensure the performance, quality, and responsiveness of applications.
* Identify and correct bottlenecks
* Help maintain code quality, organization, and automatization.
* Develop applications for time-sensitive projects while considering business/system requirements.
* Assist with estimating work efforts required for each phase of a project.
* Provide technical guidance and mentoring to less experienced engineers.
* Identify and raise technical risks.
* Maintain working knowledge of IT industry and trends.
* Promote a risk-aware culture, ensure efficient and effective risk and compliance management practices by adhering to required standards and processes.

## Location

* Ho Chi Minh, Vietnam
* Ha Noi, Viet Nam
* Hybrid Working

## Salary expectation

* $1500 - $3500 per month
* Open for negotiation 

## Requirements
* Bachelor's degree in Computer Science with 4+ years of relevant experience in enterprise applications, preferably in Spring framework and Web services, UI frameworks (AngularJS, ReactJS etc.)
* Has experience in translating technical concepts into language for audiences, including software engineers, business and technical leaders.
* Good problem solving and analytical skills.
* Have knowledge of the software development life cycle, SCM tools and CI/CD pipeline.
* Good communication skills.
* High energy, motivated team player.
* Experience of working within a tech startup and hyper growth environment.
* Comfortable with fast paced operations and not be afraid to "roll up your sleeves" to get things done.
* Good English written and verbal communication skills

### Why it would be awesome to work with us
* English & flexible working environment
* A strong tech team with leaders and members from Traveloka, Amazon,...
* Promising product-based companies with millions of users across SEA.
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th month salary
* Insurance in full gross salary, Premium Healthcare Insurance

### Fun facts about us
* Raising SGD$88 mil (US$65.8 mil) in Series C fundraising in August 2021.
* 3 regional tech hubs in Singapore, India and Vietnam.
* Acquiring Doctor Raksa, the biggest telemedicine platform in Thailand
* 50% growth in full-time employees, to 450 across the region.
* More information: [here](https://doctoranywhere.com/blog/2021/12/30/2021-year-of-impact/)

### Contact
* Direct Application for Backend Engineer (Java): [link](https://doctoranywhere.bamboohr.com/jobs/view.php?id=46)
* Email: giang.vu@doctoranywhere.com for further discussion. We are just a message away.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
