### ISSUE TITLE
Doctor Anywhere - Automation QA Engineer (Selenium, Java) - HCM/ HN - FT 

### ISSUE THREAD

**Issue by giangvu1304** [awesome-jobs/vietnam#3315]
## About Doctor Anywhere
Doctor Anywhere (DA) is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, **DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa**, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Malaysia, Thailand, Philippines, Vietnam, Indonesia and India, serving more than 2.5 million (and growing) users across the region.

At DA, we believe in the value of innovation and collaboration. Grounded in our motto of “Keep Going, Keep Growing”, our team strives towards excellence every day, and values diversity in perspectives brought by every member. Together, we bring quality healthcare to your doorstep!

## About the team
Our Technology team is the backbone of our business. The team is responsible for building a reliable, scalable and compatible platform for our product and services. Our Engineering team consists of talented and passionate engineers that focus on Full Stack (Back-end & Front-end), Mobile, QA across the regions and work closely with Data, Infrastructure & Security, Product team and with the cross functional team to continuously improve and scale our products forward.

## About the role
As a Quality Assurance Engineer you will be responsible for designing and implementing tests, debugging and defining corrective actions. The ideal candidate will also review system requirements and track quality assurance metrics (e.g. defect densities and open defect counts.)

* Review requirements, specifications and technical design documents to provide timely and meaningful feedback
* Create detailed, comprehensive and well-structured automated and manual test plans and test cases
* Estimate, prioritize, plan and coordinate testing activities
* Design, develop and execute automation scripts using Selenium tool
* Identify, track, record and document bugs
* Perform thorough regression testing when bugs are resolved
* Develop and apply testing processes for new and existing products to meet business needs
* Liaise with internal teams (e.g. developers and product managers) to identify system requirements
* Monitor debugging process results
* Investigate the causes of non-conforming software to implement solutions
* Stay up-to-date on new testing tools and test strategies

## Location

* Ho Chi Minh, Vietnam
* Ha Noi, Viet Nam
* Hybrid Working

## Salary Expectation

* $1500 - $3500 per month

## Requirements
* Minimum 4 years of working experience in Software Quality Assurance
* Degree in Computer Science, Engineering or a related discipline
* Strong knowledge of software QA methodologies, tools and processes
* Experience in writing clear, concise and comprehensive test plans and cases
* Hands-on experience with both white box and black box testing
* Hands-on experience with automated testing tools
* Experience working in an Agile/Scrum development process
* Good English communication

### Why it would be awesome to work with us
* English & flexible working environment
* A strong tech team with leaders and members from Traveloka, Amazon,...
* Promising product-based companies with millions of users across SEA.
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th month salary
* Insurance in full gross salary, Premium Healthcare Insurance

### Fun facts about us
* Raising SGD$88 mil (US$65.8 mil) in Series C fundraising in August 2021.
* 3 regional tech hubs in Singapore, India and Vietnam.
* Acquiring Doctor Raksa, the biggest telemedicine platform in Thailand
* 50% growth in full-time employees, to 450 across the region.
* More information: [here](https://doctoranywhere.com/blog/2021/12/30/2021-year-of-impact/)

### Contact
Direct Application for Automation QA Engineer: [link](https://doctoranywhere.bamboohr.com/jobs/view.php?id=136)
Email: giang.vu@doctoranywhere.com for further discussion. We are just a message away.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
