### ISSUE TITLE
Doctor Anywhere - Senior/ DevOps Engineer - HCM/ HN - FT #3315

### ISSUE THREAD

**Issue by giangvu1304** [awesome-jobs/vietnam#3316]
## About Doctor Anywhere
Doctor Anywhere (DA) is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, **DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa**, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Malaysia, Thailand, Philippines, Vietnam, Indonesia and India, serving more than 2.5 million (and growing) users across the region.

At DA, we believe in the value of innovation and collaboration. Grounded in our motto of “Keep Going, Keep Growing”, our team strives towards excellence every day, and values diversity in perspectives brought by every member. Together, we bring quality healthcare to your doorstep!

## About the team
The Infrastructure & Security team is the backbone of our platforms and services. Our Infrastructure & Security team is responsible for ensuring day to day operations, supporting and securing our large scale and highly critical applications and availability of our platform and services.

## About the role
You will be working closely with engineering teams to design, maintain and build a distributed infrastructure. You have experience in supporting large scale and highly critical applications, automating the deployment, monitoring and scaling of the applications. You will also be working closely with the developers and QAs in investigating and resolving production issues.

* Hands-on experience in deploying and maintaining Infrastructure & Apps on AWS and Azure. Good to have knowledge of GCP.
* Managing day-to-day operations and administer cloud and on-prem infrastructure & security configuration to deliver highly available and scalable services.
* User access management with RBAC
* Setup and maintain Infrastructure and Application monitoring based on KPIs and reporting on periodic and ad hoc basis to management
* Must have experience with Infrastructure and application monitoring tools
* Must have experience working with AWS device farm
* Must be familiar with CI-CD tool-chain and have work experience with knowledge of config and administration of tools in the tool-chain
* Hands-on experience in building automated deployment and config management to minimize manual intervention and to meet security and compliance objectives.
* Implement and maintain configuration management and infrastructure as code (any one of the tools CloudFormation, Terraform, Ansible/puppet).
* Must have experience in migrating Infrastructure across AWS and Azure
* Implement cloud-based Infrastructure for new projects for data analytics, web portals, and mobile applications.
* Promote a risk-aware culture, ensure efficient and effective risk and compliance management practices by adhering to required standards and processes.

## Location

* Ho Chi Minh, Vietnam
* Ha Noi, Viet Nam
* Hybrid Working

## Salary Expectation

* Totally negotiable

## Requirements
* Degree or Master’s Degree in Computer Science/ Information Systems with *8+ years of experience in creating secured cloud-based infrastructure*
* Minimum 3 year of hands-on experience on container and orchestration technologies (Docker, Kubernetes, etc)
* Experience in assessing system architectures and technical feasibility trade-offs
* Experience with several cloud technologies, preferably in AWS and Azure 
* Hands-on experience in implementing security solutions from monitoring the infrastructure for threats
* Experience in using and administering monitoring tools like DataDog, Nagios, NewRelic for Apps and Infra monitoring on cloud
* Familiarity with systems monitoring, log aggregation, and dashboard solutions
* Experience in building and operating mission critical, highly available (24×7) systems
* Adequate knowledge of scripting with Go, Javascript, Python, or similar
* Understanding of web technologies and knowledge of REST APIs, secure network communication, Node JS, React, Python, SQL and NoSQL
* Strong written and verbal communication skills.
* A start-up attitude - you take full ownership of things that you do, willing to go out of your comfort zones and take on new challenges. 
* Comfortable with ambiguity and flexible to learn new things - we’re not done growing, and heading into uncharted territories is part of the fun!

### Why it would be awesome to work with us
* English & flexible working environment
* A strong tech team with leaders and members from Traveloka, Amazon,...
* Promising product-based companies with millions of users across SEA.
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th month salary
* Insurance in full gross salary, Premium Healthcare Insurance

### Fun facts about us
* Raising SGD$88 mil (US$65.8 mil) in Series C fundraising in August 2021.
* 3 regional tech hubs in Singapore, India and Vietnam.
* Acquiring Doctor Raksa, the biggest telemedicine platform in Thailand
* 50% growth in full-time employees, to 450 across the region.
* More information: [here](https://doctoranywhere.com/blog/2021/12/30/2021-year-of-impact/)

### Contact
Direct Application for Senior/ DevOps Engineer: [link](https://doctoranywhere.bamboohr.com/jobs/view.php?id=432)
Email: giang.vu@doctoranywhere.com for further discussion. We are just a message away.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
