### ISSUE TITLE
PIXTA Vietnam - Web developer - Hanoi - FT

### ISSUE THREAD

**Issue by ngocbuildxuan** [awesome-jobs/vietnam#3317]
## About Pixta

Pixta Inc. is a pioneering Japanese company in providing copyrighted photos, footage, illustration, audio… Established in 2005, from the dream of building an innovative platform connecting talents from all over the world; with the original website https://pixta.jp (Japanese version), Pixta has now developed a website in 5 different languages ​​with the aim of best serving customers in many markets around the world.

Pixta Vietnam is a branch of Pixta.Inc group, established in Vietnam in May 2016, with the function of product development for Pixta corporation. With a huge data warehouse and complex system including over 60 million photos, adding about 30,000 new photos every day, 330 thousand photographers and over 12 billion user behaviors, Pixta Vietnam is always changing and improving, applying the most advanced features and keeping up with market trends.

What products are PIXTA.Inc and PIXTA VIETNAM developing?
* https://www.pixtastock.com
* https://xframe.io
* https://od.pixta.jp
* https://fotowa.com

From 2021, Pixta Vietnam deploys more SaaS (Software as a Service) fields. 

The company has successfully deployed several products using AI (Artificial Intelligence), ML (Machine learning) technology and sold them to several large customers in Japan: Panasonic, SoftBank…

## Location

* Hanoi, Vietnam

## Salary Expectation

* Junior-Middle: up to 1400 USD
* Senior: 1500~ 2500 USD
* Expert: 2600~ 4500 USD

## Your scope of work

* Design and build systems using NodeJs, RoR and Serverless Architecture
* Stay up to date and recommend best solutions in the process of developing and share knowledge with colleagues
* Actively contribute and give ideas for products
* Develop and manage the entire database of the website. Analyze data, evaluate the effectiveness of features to improve and develop new features
* Manage development resources such as servers, DB, CI/CD… ensure smooth development experience
* Collaborate across time zones via Slack, GitHub comments, documents, and frequent video conferences
* Create professional working environment by following Scrum framework

## Your Skills and Experience

* Solid experience in at least 1 programming language Nodejs / Ruby / Python
(Junior with experience in other languages is acceptable)
* Understand software development architectures Microservices, Monolithic,…
* Basic knowledge of relational database, NoSQL database
* Experience in API development and authentication
* Experience in caching: Client side, Server side, CDN
* English: verbal and written communication skills

## Bonus Points

* Knowledge of Frontend technology: ReactJS, VueJS,..
* Experience in working with search engines: Elasticsearch, Solr,…
* Experience with message queuing: AWS SQS, Kafka,..
* Experienced working with Web server: Nginx, Apache,…
* Familiarity with GraphQL
* Familiarity with AWS

## Benefit Package

* Performance review: twice per year & bonus up to 2 months salary end of year; quarterly award…
* Lunch allowance (40.000 VND/day), free parking fee
* Full insurance & Bao Viet extra health care card and family bonus based on company regulation
* 5 working days/week, 13 annual leave days/year, company special holiday, senior annual leave per 2 years…

## Career Growth

* Personal growth development in both technical and business/communication skills
* Opportunity to apply your talent attraction knowledge, learn new things and contribute your expertise for a well-known company in the technology field
* Be given the freedom to develop your working plans and grow as you want to be
* Be received support from nice manager and coworkers 
* Become core members of the project, take whole responsibility for the project
* Dive deep into technologies, learn how tools truly work and contribute for a leading product company in Asian market
* Be given freedom to learn and complete tasks in your own way while still be supported by smart leader and colleagues 
* Team rotation opportunity

### Contact
Homepage: [pixta.vn](https://pixta.vn/)
Direct Application for Web Developer: [link](https://pixta.vn/jobs/web-developer-nodejs-ruby-python)
Email: [ngoc.buixuan@pixta.co.jp](mailto:ngoc.buixuan@pixta.co.jp) for further discussion. We are just a message away.

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by ngocbuildxuan** [comment]
Sorry about that. I've already changed contact email. Please re-review this issue again.
Thank you.
