### ISSUE TITLE
LINAGORA - Mobile Developer- HN/REMOTE - FT

### ISSUE THREAD

**Issue by HoangYen309** [awesome-jobs/vietnam#3320]
## Location

* Hanoi, Vietnam
* Remote (Prefer HN)

## Salary Expectation

* OFFER 999$ - 1999$ /month or range

## Requirements

Participate in product design, offer new ideas
Design and build applications for mobile platforms
Collaborate with product and business teams to define our products that are suitable for the market
Design and implement a mobile application for mobile platform using new technology
Work in a team, using AGILE methodologies, to deliver software on time
Collaborate with other team members to ensure our team maintain high standards
Support international teams in developing products to meet the client‘s requirements
Keep up to date on the latest industry trends in the mobile technologies
Coaching the member of the team and attend to interview process to scan the technical part

## Skills

2+ years’ experience in mobile software development (Android, iOS, or Flutter).
Familiarity with RESTful APIs to connect applications to back-end services.
Knowledge of other web technologies and UI/UX standards.
Understanding of State management approaches.
Proficient understanding of code versioning tools.
Familiarity with cloud message APIs and push notifications.
Strong OO design and skills in Functional programming, Reactive programming.
Good communication of English.

### Why it would be awesome to work with us

Work in an international team with high skilled people, big Product
Correct work/life balance
Annual company trip, other exciting activities for team building
Working 5 days/week , from Monday to Friday, No OT
Lunch allowance, 13th month salary, competitive salary
Annual health checkups and other benefits based on labor law
Participate to Open Source communities and conferences in Vietnam
Modern working space, free coffee

### Interesting engineering projects
You’ll develop the mobile applications of the OpenPaaS (https://open-paas.org/) platform (mail, calendar application for fulfilling OpenPaaS Eco-system).

a Drive application, giving users the ability to have their LinShare (https://linshare.org) files on their mobile devices
a Chat application, linked to the Twake, to allow people to keep chatting on their mobiles
a Subscription management application for the flagship software Twake Console
a Mail application with the modern JMAP protocol

### Contact
Homepage: linagora.com.vn
Email: [vnhr@linagora.com](mailto:vnhr@linagora.com) or contact via phone number/zalo: 0372019465 (Yen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
