### ISSUE TITLE
LINAGORA - DEVOPS - HN/REMOTE - FT

### ISSUE THREAD

**Issue by HoangYen309** [awesome-jobs/vietnam#3321]
## Location

* Ha Noi, Vietnam
* Remote (Prefer HN)

## Salary Expectation

* OFFER 999$-2499$ / month

## Requirements

Establish, maintain and maintain SaaS infrastructure and be responsible for ensuring that the infrastructure works as expected, set up alerts, analytics and logging.
Develop processes for automatic deployment and testing.
Determine what tools (API rate limiting, load balancer, security threat detection, etc.) will be needed and together with the team improve the existing infrastructure.
It will be necessary to make a roadmap for the product with requirements and deadlines.

## Skills
Experience with one of the cloud services AWS, Azure, GCloud, or OVH
Experience in managing all infrastructure including databases, replication, load-
balancers, web servers, CDNs, CI CD
Experience with any configuration management system: Ansible, Puppet, Chef, Terraform
Experience with any CI CD system: Teamcity, Jenkins, Gitlab CI, Github Actions
Experience with most of the components from our stack
Ability to independently decompose tasks and bring them to the end.

### Why it would be awesome to work with us
Work in an international team with high skilled people, big Product
Correct work/life balance
Annual company trip, other exciting activities for team building
Working 5 days/week , from Monday to Friday, No OT
Lunch allowance, 13th month salary, competitive salary
Annual health checkups and other benefits based on labor law
Participate to Open Source communities and conferences in Vietnam
Modern working space, free coffee
### Contact
Homepage: linagora.com.vn
Email: [vnhr@linagora.com](mailto:vnhr@linagora.com) or contact via phone number/zalo: 0372019465 (Yen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
