### ISSUE TITLE
LINAGORA - Senior Mobile Developer - HN/REMOTE - FT

### ISSUE THREAD

**Issue by HoangYen309** [awesome-jobs/vietnam#3322]
## Location

* Hanoi, Vietnam
* Remote (Prefer HN)

## Salary Expectation

* OFFER 999$-1999$ / month

## Requirements

Technology stack: Flutter Description: We are looking for a Flutter Senior Developer who knows how to make efficient, fluid mobile interfaces, beautiful UI, animations, transitions and interactions. Our project is Twake (https://twake.app), an open source, secure and privacy-focused chat What will need to be done:

Together with UI UX designers, developers, analysts and QA to create a beautiful interface on Flutter
Develop reusable front-end components and libraries
Proactively analyze performance and improve it
Mentor junior team members

## Skills
5+ years’ experience in mobile software development (Android, iOS, or Flutter).
Experience in developing complex mobile applications
Experience in writing unit, integration, e2e tests
Experience in writing applications in Flutter
Deep understanding of front-end optimizations
Ability to independently decompose tasks and bring them to the end.
Advanced English Will be a plus:
Ability to do UI / UX design
Good communication of English.

### Why it would be awesome to work with us

Work in an international team with high skilled people, big Product
Correct work/life balance
Annual company trip, other exciting activities for team building
Working 5 days/week , from Monday to Friday, No OT
Lunch allowance, 13th month salary, competitive salary
Annual health checkups and other benefits based on labor law
Participate to Open Source communities and conferences in Vietnam
Modern working space, free coffee
### Contact
Homepage: linagora.com.vn
Email: [vnhr@linagora.com](mailto:vnhr@linagora.com) or contact via phone number/zalo: 0372019465 (Yen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
