### ISSUE TITLE
LINAGORA - Senior/Lead Test Engineer - HN/REMOTE - FT

### ISSUE THREAD

**Issue by HoangYen309** [awesome-jobs/vietnam#3323]
## Location

* Hanoi, Vietnam
* Remote (Prefer HN)

## Salary Expectation

* OFFER 999$-1999$ /month or range

## Requirements
Gather product requirements (functionalities, speed, safety standards)
Inspect raw materials and machinery to identify defects and malfunctions
Monitor all production stages to ensure safety procedures are followed
Run quality controls on components and final products
Develop test environments and test cases for all company software products
Analyze test results, detect issues and track root causes
Suggest fixes and improvements
Document technical issues and solution
Build automated testing systems for regular checks
Ensure our products and procedures meet industry standards
Develop the test script/code for technical testing
Support/train other team members about technical test skills
Research on other technical test areas and apply to our projects

## Skills
Bachelor’s degree in information technology, or related field
3 years+ working as a test engineer or similar role.
Speaking English is required
Expertise at least one of automation test frameworks (preferably Robot framework, Flutter Driver , Selenium, Gatling, Cypress, Jest) or equivalence
Experience in development and testing Backend, Mobile, Web or similarity
Coding skill for any of programming languages such as Java, JS, PHP, C# or equivalence
Basic knowledge about docker CI/CD
Basic knowledge of Linux operating systems
Eager to learn new techniques and willing to share knowledge to other team members
Have knowledge in at least one of the following fields: automation testing, performance testing, security testing, database testing is a plus
Passionate about OpenSource and Free Software is a plus

### Why it would be awesome to work with us

Work in an international team with high skilled people, big Product
Correct work/life balance
Annual company trip, other exciting activities for team building
Working 5 days/week , from Monday to Friday, No OT
Lunch allowance, 13th month salary, competitive salary
Annual health checkups and other benefits based on labor law
Participate to Open Source communities and conferences in Vietnam
Modern working space, free coffee
### Contact
Homepage: linagora.com.vn
Email: [vnhr@linagora.com](mailto:vnhr@linagora.com) or contact via phone number/zalo: 0372019465 (Yen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
