### ISSUE TITLE
AXON ACTIVE VIETNAM - DEVOPS ENGINEER - HCM - FT

### ISSUE THREAD

**Issue by imhither** [awesome-jobs/vietnam#3324]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

* Attractive offers depend on your experience and performance in the Interview.

## Requirements

* Have background in Computer Science/Information Technology or equivalent.
* Strong knowledge of AWS infrastructures
* Hands-on experience with Terraform
* Experience with Docker container, Kubernetes, CI/CD
* Experience with Linux/Windows infrastructures
* Have knowledge of Python, Java is a plus
* Experience on Wildfly, Gradle and Setup local dev environments
* Good at English skills and Problem-solving skill

### Must Have

* Strong knowledge of AWS infrastructures
* Hands-on experience with Terraform
* Experience with Docker container, Kubernetes, CI/CD
* Experience with Linux/Windows infrastructures
* Have good English skills

### Ideally

* Have knowledge of Python, Java is a plus
* Experience on Wildfly, Gradle and Setup local dev environments

### Responsibilities

* Work in Scrum team
* Daily cooperation with Product Owner
* Be involved in planning, estimation, developing and continuously delivering software
* Self-assign tasks and be fully responsible for quality/quantity of delivered result
* Self-determine appropriate architecture, technical solutions

### You’ll be responsible for

* Being a part of Scrum team where you can develop your potential, make use of your skills, bring our ideas, initiate your solutions and make your daily work awesome. 

### You can bring

* Your dedication.
* Your professional skills.

### Why it would be awesome to work with us

* Competitive salary & 13th salary
* 100% salary in probation period 
* Working from Home option
* Flexible working hours and up to 18 days off per year 
* Fully paid compulsory insurances (Bảo hiểm xã hội, bảo hiểm thất nghiệp, bảo hiểm y tế)
* Annual premium healthcare and 24/24 personal accident insurance (Bảo hiểm sức khỏe và bảo hiểm tai nạn 24/24)
* Additional healthcare insurance for family members
* Annual health check-ups
* Free kindergarten for staff’s kids
* Onsite visit opportunities in Europe, USA or Australia
* Access to licensed Udemy training courses & Axon Active plus frequent internal knowledge exchanges
* Loyalty bonuses (additional annual leaves, travel vouchers)
* Free lunch at the office
* Company trip & other team building activities
* Sponsored sports clubs such as football, badminton, etc.
* More than a thousand useful books, e-books and magazines in our library
* Direct English communication with foreigners and English courses
* International English speaking, self-development, and growing environment 
* A focus on developing your knowledge, skills, and English 
* Open, dynamic, and professional Agile environment 
* Modern office

### Contact
Homepage: https://www.careers.axonactive.com
Contact me via: Skype: thaoluong.1304| Email: thao.luonghien@axonactive.com
Thank you very much for reading to the end!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
