### ISSUE TITLE
VietSwiss - FullStack Developer - HCM - FT

### ISSUE THREAD

**Issue by akarui2004** [awesome-jobs/vietnam#3332]
## Location

* Ho Chi Minh, Vietnam
* Fulltime

## Salary Expectation

* Attractive offers depend on your experience and performance in the Interview.

## Requirements

* Have +2 years of experience in front-end and back-end
* Proficiency in PHP
* Familiar with PHP frameworks like Laravel, Symfony, ...
* Experience with HTML5, CSS, Javascript(ES6), and other front-end technology / Have a knack with React or Vue, Jquery, Bootstrap, SASS/LESS
* Have RDS SQL (MySQL, PostgreSQL, SQL Server) and NoSQL knowledge, and can work with these
* Web responsive and cross-browser
* Strong OOP
* Git control and management
* Project management and task priority
* Understanding of analytics needs and proactive-ness to build generic solutions to improve the efficiency
* Can communicate with client / technical in English

## Skills
* PHP
* HTML, CSS, Javascript
* RDS, NoSQL

### Why it would be awesome to work with us
* Working time: 5 days/week (Monday - Friday)
* 13th month bonus + additional bonus depends on the success of the project
* Social insurance, health insurance, unemployment insurance are paid in full according to Vietnam Labor Law
* Travel to Europe (at least 1 week/year)
* Vacation up to 14 days
* Sick leave according to the law
* Get professional training and experience exchange
* Working in a dynamic international environment
* 
### Contact
Homepage: [VietSwiss](https://vietswiss.com/)
Hoa Tran: hoatran@vietswiss.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
