### ISSUE TITLE
JobSeekervn - Technical Architect - Saigon 

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3334]
## Location
* Saigon, Vietnam
* Fulltime

## Salary Expectation
* $3000 - $4000/month or range

## Requirements
* Bachelor’s degree in computer science, engineering, or a related field.
* Experience in a similar role would be advantageous.
* Excellent technical, diagnostic, and troubleshooting skills.
* Strong leadership and organizational abilities.

### You’ll be responsible for
* Strong technical background with deep experience in developing custom software, Microservices architecture applications and operating 3rd party platforms integration.
* Implement, test, and operate advanced software security techniques in compliance with technical reference architecture.
* Provide engineering designs for new software solutions to help mitigate security vulnerabilities.
* Application security experience (SSO, Federation (SAML, OpenID, OAuth2, OIDC) and Multi factor authentication.
* Have experience 5+ years in web and application development with Java/Nodejs stack.
* At least 2 years of experience working with Product development.
* Have experience in AWS.
* Fluent in English communication (both written and verbally).

### Contact
Email: nhiha@jobseeker.vn
Skype: hahoainhi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
