### ISSUE TITLE
Xendit - Frontend engineer - Remote/Saigon/Hanoi - FT

### ISSUE THREAD

**Issue by ctxendit** [awesome-jobs/vietnam#3336]
## Location

- Saigon, Vietnam
- Hanoi, Vietnam
- Remote

## Salary Expectation

- Best competitive and negotiable package for the Vietnam market.

## Requirements

- Strong knowledge of Node.js and popular JavaScript/TypeScript frameworks
- Strong knowledge of REST and pub/sub design patterns
- Strong knowledge of modern CSS frameworks
- Experience with relational and NoSQL database schema design and query optimization
- Experience with unit, integration, and E2E test frameworks

### Must Have

- 2+ years of a successful track record of developing quality software products and shipping production-ready software
- Bachelor's or Master's degree, preferably in Computer Science, or equivalent experience
- Thrive on being independent and have proven you can push towards a goal by yourself
- Communicate well
- Strong interest in growth (personally and professionally) and, therefore, a continuous improvement mindset
- Is unyielding in reliable, scalable, and readable code
- Can quickly recognize failures, take feedback and iterate immediately to move closer to customer desires

### Ideally

- Experience with Agile development
- Ability to break down complex business requirements into technical requirements
- Ability to architect distributed systems on cloud computing platforms
- Familiar with Domain-Driven Design
- Comfortable with modern DevOps: k8s, terraform

### Responsibilities

- Develop and enhance interactive user experience by using the best practices in modern Front-End development
- Improve the UI app layout and structure to ensure reliability, scalability, and security
- Quickly comes up with MVP models and propose solutions for complex problems
- Produce high-quality, maintainable code, test it, collaboratively, review it, and ship it
- Identify areas to improve and scale our architecture and application design
- Collaborate extensively with Team Leads, Product Managers, Designers, and fellow Engineers to develop features that drive our metrics
- Lead teams to the successful delivery of software projects
- Work closely with our business teams

#### Company highlight

Xendit provides payment infrastructure across Southeast Asia, with a focus on Indonesia and the Philippines. We process payments, power marketplaces, disburse payroll and loans, provide KYC solutions, prevent fraud, and help businesses grow exponentially. We serve our customers by providing a suite of world-class APIs, eCommerce platform integrations, and easy to use applications for individual entrepreneurs, SMEs, and enterprises alike.

Our main focus is building the most advanced payment rails for Southeast Asia, with a clear goal in mind — to make payments across in SEA simple, secure and easy for everyone. We serve thousands of businesses ranging from SMEs to multinational enterprises, and process millions of transactions monthly. We’ve been growing rapidly since our inception in 2015, onboarding hundreds of new customers every month, and backed by global top-10 VCs. We’re proud to be featured on among the fastest growing companies by Y-Combinator.

#### The Experiments team

The Experiments team builds new products that are complementary to our existing suite of digital infrastructure. We take ideas, customer pain points, or gaps in the market and build a new solution from the ground up. This team presents a unique opportunity for people who are looking to build something completely new and exciting, rather than improving existing products.

### Interesting engineering projects

- Abstracted API layer to interface with many banking and payment systems to provide first-class experiences to business customers
- Building massively scalable and reliable system for serving large-volume financial transactional requests

### Contact
Homepage: www.xendit.co
Email: cuong.truong@xendit.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
