### ISSUE TITLE
Xendit - Backend Engineer for Experiments - Remote/Saigon/Hanoi - FT

### ISSUE THREAD

**Issue by ctxendit** [awesome-jobs/vietnam#3339]
## Location

- Saigon, Vietnam
- Hanoi, Vietnam
- Remote

## Salary Expectation

- Best competitive and negotiable package for the Vietnam market.

## Requirements

- Strong knowledge of Golang and/or NodeJS TypeScript
- Strong knowledge of REST and pub/sub design patterns
- Strong knowledge of relational and NoSQL database schema design and query optimization
- Familiar with large-scale microservices architectural patterns
- Familiar with concurrent and distributed application design patterns
- 3+ years of experience in developing, designing, and deploying large scale applications
- Experience with unit, integration, and E2E test frameworks

### Must Have

- Bachelor's or Master's degree, preferably in Computer Science, or equivalent experience
- Thrive on being independent and have proven you can push towards a goal by yourself
- Well English spoken and written communication skills
- Strong interest in growth (personally and professionally) and, therefore, a continuous improvement mindset
- Is unyielding in reliable, scalable, and readable code
- Can quickly recognize failures, take feedback and iterate immediately to move closer to customer desires

### Ideally

- Experience with Agile development
- Ability to break down complex business requirements into technical requirements
- Ability to architect distributed systems on cloud computing platforms
- Familiar with Domain-Driven Design
- Comfortable with modern DevOps: k8s, terraform
- Bonus points if you’ve built payments infrastructure before

### Responsibilities

- Understand and translate customer needs into technical requirements that best fit to company’s standard technical stacks
- Develop, integrate API - quick research and development of proofs of concepts that serve as the base for building long-term end products
- Implementation, testing, deployment and support of the developed customers’ products, as well as company core & strategic ones
- Built products must meet mutually agreed SLOs
- Built products must be deployable and scalable within a microservice architecture
- Write concise and transferable documentation for every step of the software development life cycle
- Find issues with the company's current infrastructure and propose a new future state with management buy-in
- Act as an individual contributor (if needed) to build the proposed state on time

#### Company highlight

Xendit provides payment infrastructure across Southeast Asia, with a focus on Indonesia and the Philippines. We process payments, power marketplaces, disburse payroll and loans, provide KYC solutions, prevent fraud, and help businesses grow exponentially. We serve our customers by providing a suite of world-class APIs, eCommerce platform integrations, and easy to use applications for individual entrepreneurs, SMEs, and enterprises alike.

Our main focus is building the most advanced payment rails for Southeast Asia, with a clear goal in mind — to make payments across in SEA simple, secure and easy for everyone. We serve thousands of businesses ranging from SMEs to multinational enterprises, and process millions of transactions monthly. We’ve been growing rapidly since our inception in 2015, onboarding hundreds of new customers every month, and backed by global top-10 VCs. We’re proud to be featured on among the fastest growing companies by Y-Combinator.

#### The Experiments team

The Experiments team builds new products that are complementary to our existing suite of digital infrastructure. We take ideas, customer pain points, or gaps in the market and build a new solution from the ground up. This team presents a unique opportunity for people who are looking to build something completely new and exciting, rather than improving existing products.

### Interesting engineering projects

- Abstracted API layer to interface with many banking and payment systems to provide first-class experiences to business customers
- Building massively scalable and reliable system for serving large-volume financial transactional requests

### Contact
Homepage: www.xendit.co
Email: cuong.truong@xendit.co

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
