### ISSUE TITLE
Teko VietNam - Senior/Software Engineer (All level) (Golang) - HCM - FT

### ISSUE THREAD

**Issue by TongTrangHr** [awesome-jobs/vietnam#3340]
## Location

*Minh Long Building, 17 Ba Huyen Thanh Quan Street, Ward 6, District 3, HCMC
*Fulltime

## Salary Expectation
* Negotiable

## Requirements

- BS in Computer Science or similar field of study.
- Very solid experience of software development (Python, Golang, Java, JavaScript,..)
- Have good knowledge about computer science, data structures, algorithms.
- It’s good to have years of experience but as long as you love to code and learn new things, then you are good.
- Good to have: Experience with designing and building high traffic applications to serve millions of users.
- Good to have: Experience with devops automation tools, CI/CD.
- Good to have: Experience with containerization technologies such as Docker, Kubernetes.

## Our current tech stacks:

- Infrastructure: Linux, Network, Storage (Ceph), Kubernetes
- CI/CD: Ansible, Docker, GitOps.
- Application layers: Python, Golang, Java, JavaScript.
- Distributed systems: Elasticsearch, Apache Spark
- Databases: MongoDB, Redis, MySQL

## Responsibilities

- You will be part of an agile team, working closely with product managers, designers and technical leads to ideate, prototype, build and test new products or features. In short, you take ownership of your work and leads the effort from architecture, implementation, deployment and testing.
- Writing clean and reusable code with unit / functional tests and continually increase your code quality.
- Having lots of discussions, brainstorming with your team to make technical decisions.
- Spending lots of time to review other people’s code so you will learn and understand every piece of the system and making sure we have the best code quality as a team.
- Constantly raise your standard, learning new things and sharing knowledge with the rest of the team. We believe it’s more meaningful when we grow as a team.
- Taking ownership of the product and constantly find ways to make it better by improving the design, system maintainability, performance and reliability. You will also monitor and troubleshoot application or system issues by deep diving into technical problems. This requires you to understand the whole application and infrastructure stack.

## WHY YOU'LL LOVE WORKING HERE

- Negotiable salary according to qualification (13th month salary + Performance Bonus) ;
- The working environment is open, energetic and professional. More opportunities for career promotion;
- Free Food & Drink: lunch, fresh fruit/cake, coffee & tea.
- Premium healthcare: full benefit with social insurance, annual health check and attractive healthcare coverage under the company’s own policy;
- Employee Relationship: company trip, team bonding & sport club;
- Leave Paid: 12 days for annual leave & 6 days for sick leave (max 18 days) Working time: Monday to Friday (8:30 AM – 5:30 PM).

### Contact

Homepage: https://teko.vn/jobs/17
Email: trang.tq@teko.vn
Skype: live:.cid.b71ee10d04a05617

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
