### ISSUE TITLE
[TROODON] Backend Developer (Golang)

### ISSUE THREAD

**Issue by ThanhLam-Troodon** [awesome-jobs/vietnam#3342]
## Location

* Phu Nhuan, HCM, Vietnam
* Fulltime

## Salary Expectation

* Upto 1500$

## Requirements
- More than 2 years of experience in software development using Golang (PHP is a plus).
- Have experience in MySQL, Redis, and GRPC.
- Produce clean, efficient, scalable and testable code based on specifications.
- Ability to learn new languages and technologies.
- Experience with Docker, CI/CD.
- Good technical, analytical and problem solving skills.

## Would be great if you are also:
- Experience with microservice.
- Experience with CI/CD

### Working time

* from 8am to 17pm

### Responsibilities

Great power comes with great responsibilities!

### Contact
Homepage: https://troodonlabs.com/
Email: hr@troodonlabs.com
Phone number: (+84)984 51 96 51 or (+84)399 230 239

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
