### ISSUE TITLE
NodeJS - Hà Nội 

### ISSUE THREAD

**Issue by vgs2022** [awesome-jobs/vietnam#3343]
## Location

* Hà Nội, Vietnam
* Fulltime

## Salary Expectation

* 700-2000$/month

## Requirements
* NodeJS
* Javascript
* Typecript
* 1+ years Software Engineering experience

### Must Have

* English
### Ideally

* Experience with game NFT

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new Facebook

### You can bring

* A good eyes for design
* A good analysis skill

### Contact
Homepage: https://www.facebook.com/VGS2022
Gmail: vgstuyendung@gmail.com
Phone: 0862996468

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
