### ISSUE TITLE
[TEQNOLOGICAL ASIA] - Golang Developer (All-levels) - HCM - Fulltime

### ISSUE THREAD

**Issue by Giaoooo4197** [awesome-jobs/vietnam#3345]
## Location

* 301, Block B, Waseco Plaza, 10 Pho Quang, Tan Binh, Ho Chi Minh
* On-site

## Salary Expectation

* Negotiable

## Requirements
* **At least 1 year experience in Golang.** 
* **If you're fresher no need any experience.**
* Knowledge of development based on API , Microservices or Single web application.
* Basic Knowledge of databases (Mysql, Postgres, NoSql)
* Basic Knowledge of AWS (Lambda Function, ECS, DynamoDB, RDS, etc.)
* Experience developing highly interactive applications
* Passion for writing great, simple, clean, efficient code.
* BS/MS degree in Computer Science, Engineering or in the related field

## Skills
**[Golang] [Database] [Fresher Accepted]**

### Why You'll Love Working Here
**Compensation and benefits:**

Attractive salary and benefits (Salary review - 2 times/year)
Insurance contribution equal to 100% of salary. Year-end bonus.
Annual health check for all employees.
MacBook or personal laptop provided.
Spiritual life:

**Monthly party with food and drink.**
At least 2 trips a year: Team Building, Company Trip,.. and other big events.
Free foreign language training: English and Japanese.
Opportunity to work in Japan.
Gifts and allowances for Weddings, Childbirths, Women's Day, and Children's Day
Professional, friendly, and open working environment
The company organizes birthday parties for employees monthly, organizes bonuses and celebrations. celebrate the holidays of the year.

**Working time and place of working time:**
Working from Monday - Friday and the last Saturday of the month, working hours 8:30 - 17:30 (8 hours/day), public holidays according to state regulations;
Floors 3 - 5, Waseco Building, No. 10 Pho Quang, Ward 02, Tan Binh District, Ho Chi Minh City.

### Contact
Homepage: https://teqnological.asia/
If you are interested in this position, please email your resume/Curriculum Vitae to
Email: recruit@teqnological.asia

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
