### ISSUE TITLE
[Uptempo Vietnam] [CTO, Tech Leader, Team Leader] -[Hanoi]-[FT]

### ISSUE THREAD

**Issue by Uptempojack** [awesome-jobs/vietnam#3350]
## Location
* Hanoi, Vietnam (Quận Cầu Giấy): being newly established (Early Stage)
* Check out our HQ in Korea => http://uptempo-global.com/?lang=vi

## Salary Expectation

* $2,000 - $4,000 + Performance-based Bonus or Stock Options (Negotiable)

## Requirements
* 8+ years Software Engineering experience or Project Management experience

## Skills
* Leadership, communication & management skills
* Full stack (FE/BE) S/W engineering experience
* Up to date with new (trending) programming languages and skills

### Must Have

**Position 1: Uptempo Vietnam CEO/COO/Director**
**Position Detail**
- General management of Uptempo Vietnam’s business.
- Setting up, planning and managing teams in Uptempo Vietnam
- Communication and biz development with Uptempo Global’s HQ in Korea, Vietnam local partners, global clients
- Global sales team establishment, etc.
- Initially will be working closely with C-levels and directors from Uptempo Global for absorption and alignment of business direction and activities

**Position 2: Uptempo Vietnam CTO/Director**
**Position Detail**
- As the Company-wide Tech Leader of Uptempo Vietnam, you will have to guide and nurture Tech Team Leaders
- Support the improvement of junior and mid-senior developers
- Create a healthy company culture for developers.
- Set the direction for solutions when there is a tech/business problem
- Coordinates and deals with diverse/unusual project issues at the forefront
- Is always there for team leaders and team members.

**Position 3: Uptempo Vietnam Tech Team Leader (PL / PM)**
**Position Detail**
- Manage and guide project teams; at least 4-5 developers and at most 15 developers
- Instruct junior and mid-senior developers to carry out projects smoothly
- Create a healthy development team culture.
- Set the direction for solutions when there are unusual project issues
- Coordinates project issues at the forefront
- Hustle alongside team members

### Ideally

* Leadership: the capacity to earn respect from the team members, able to motivate team members to the right direction.
- Ownership mindset, dedicated to creating Uptempo Vietnam into a global success story
- More than 8 years of related managerial experience company-wide, department-scale, or team-scale.
- Able to speak in English or Korean
- Able to commute to Hanoi office
- Able to travel to Korea and other overseas countries

### Responsibilities

At Uptempo, we value leadership, cooperation, and communication.
It is important to acknowledge that we are not the smartest in the word and we don’t have to be. Genuine and sustainable value can be created better when a team can create a knowledge pool where new skills can be taught or guided among one another

Rather than simply being brilliant and smart alone, what is most important in Uptempo is we take care of our own. Therefore, the once-seemingly impossible had it been done as a hard working solo, can be actually be realized through “hard work together” 
A well-rounded team that  believes that “the willpower is the strongest game changer”, and that “working with the right people in the right way can be a world changer”. We are looking for leaders who can practice these values and lead a team of his/her own within Uptempo Vietnam.

### You’ll be responsible for

* Ownership mind, dedicated to creating Uptempo Vietnam into a global success story

### You can bring

* Any trait you value as your super power.

### Why it would be awesome to work with us

Established in 2015 as a one-man company, Uptempo has provided professional interpretation and translation services for all languages as its main business.

Uptempo had never conducted paid marketing until 2021, and has grown independently without investment or debt until now. We have established a self-sufficient highly recognized professional company in the interpretation and translation industry.

We have achieved an annual growth of more than 150% for 7 consecutive years, and since 2020 we have been incorporating language services with IT technology to enhance global work efficiency. In 2021, Uptempo as a group, has achieved total revenue of $2.5 million with 30 team members. In 2022, as it is our turning point for service expansion and global scale-up, we expect to grow by more than 250%.

Over the years, Uptempo has been carrying out various cross-border knowledge-based projects (professional interpretation and translation, marketing, development, design, PCO) around the world. Among them, Korea-Vietnam cross-border IT service in particular, has won the hearts and trust of many Korean clients. 

Powered with Korea-Vietnam cross-border co-working know-how and project management system, we established an IT business HQ in Korea in 2021, and have been conducting all types of IT projects jointly with Vietnamese local developers (both in-house and freelancers).

Uptempo will strive to build an IT co-working automation system that can enable more efficient operation of cross-border IT development activities. To date, cross-border IT co-working (or even IT outsourcing) has had limitations such as communication problems or language barriers.

Uptempo believes that a day will come where all developers from all regions, regardless of English speaking capabilities, can work together remotely and seamlessly free of language barriers. Uptempo will be at the forefront of creating such innovation.

Ultimately, Uptempo will go beyond the IT field. We will create diverse cross-border co-working automation systems that solve language barrier problems, hence boosting in-depth practical project communication and transfer of knowledge in various specialized fields such as legal, medical, entertainment business, etc.

* It is said that 99% of startups fail. On the contrary, there is 99% chance that Uptempo will “not fail”.
The reason is that, to date we have been self-sustaining without investment or debt (with a lot of hard work). We have created a solid and sustainable business infrastructure that will allow us to go forward.

* We’ve been saving the sweets, such as fundraising and investment opportunities, for later. Later as in, when the time is right, when we are on the brink of scaling up into a billion dollar company.

* Check out our promo video: https://www.youtube.com/watch?v=xU0NqZJc-l0

### Interesting engineering projects
* Diverse mobile apps, pc webs
* SNS based E-commerce
* NFT marketplace
* Metaverse
* Blockchain
* AI solution

### Contact
Homepage: www.uptempo-global.com
E-mail: jackoh@uptempom.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
