### ISSUE TITLE
[Dat Bike] - [Software Engineer] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by irisiris96** [awesome-jobs/vietnam#3351]
## Location

* Dat Bike Factory, 1 CN10, KCN Tân Bình, Tây Thạnh, Tân Phú
* Onsite

## Salary Expectation

* $2000 - $5000 / month

## Requirements
Bachelor’s degree in Computer Science or similar fields
At least 3 years of industry experience
Know how to balance between shipping fast and shipping robust software
Strong analytical and problem solving skill is a must

### Ideally
*Hi-tech or automotive industry experience is a plus

## Our tech stack:
Embedded: C/C++ on ESP32, STM32
Server: Java on AWS
Mobile: react-native

## Responsibilities

Great power comes with great responsibilities!

## You’ll be responsible for
Own new features from start to finish. Idea -> design -> launch -> polish.
Improve and iterate on existing features through testing or user feedback. 
Build and maintain internal tools to increase company-wide productivity.
Play an active role in shaping the future of Dat Bike.

## Why it would be awesome to work with us
3 meals a day and a place to stay (if you don’t yet have)
Free soda, drink as much as you want
Social security + insurance
Cash + meaningful equity compensation 
50% discount price to buy a Dat Bike
Short-term programs to develop skills and knowledge

## Contact
Homepage: dat.bike
Email: jobs@dat.bike

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
