### ISSUE TITLE
Mobile App Tech Lead (Elixir)_Remote working_$2500 -$3000

### ISSUE THREAD

**Issue by Michannn** [awesome-jobs/vietnam#3352]
## Location

* Vietnam
* Remote

## Salary Expectation

* $2500 - $3000/month

## Requirements
* At least 3 years of experience with Elixir 
* 2 years with React Native
* 3+ years of Software Engineering experience intotal
* Strong with OOP, design pattern
* Good English because you will work directly with the Singapore product team

### Ideally

* Strong analytical and independent thinking to propose and evaluate solutions.
* Knowledge about cloud computing (Azure, AWS, GCP...) is a plus
* Product mindset with Design thinking and Agile

### Responsibilities

* Hire, manage and lead an Engineering team (local and remote) for mobile and backend
services. 
* Work with Product, Business, and Clinical/Ops teams to build and prioritize product
a roadmap based on complexity, timeline, and resource estimations
* Write testable, clean, and efficient code that can be confidently released in production
* Ensure optimum app quality and platform stability through a system of metrics
monitoring
* Lead and manage Agile ceremonies such as backlog grooming, sprint planning and
retrospectives with team members

### Why it would be awesome to work with us

* Remote working
* Attracted salary: $2500 - $3000 /month
* Working time: 9h-18h, 5 days a week, lunchtime 12h-13h30. 
* Opportunities to improve your English to the next level.
* Progressive company culture, focusing on result, growth, and human development. 
* Year-end variable bonus, based on performance. (Eligible after working 12 months)
* Yearly appraisals.

### Contact
Homepage: https://www.linkedin.com/company/inspius/mycompany/
Email: huongthanh.do@inspius.com
Phone/Zalo/Telegram: 0866107429

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
