### ISSUE TITLE
[MobileFolk] - [Web Developer - PHP/NodeJs] - [Hanoi] - [FT]

### ISSUE THREAD

**Issue by giangmobilefolk** [awesome-jobs/vietnam#3353]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* $1,400 - $2,000/month 

### Must Have

* Excellent knowledge of one or more web development languages/frameworks (PHP, Node.js)
* Strong understanding of algorithms, data structures, design patterns
* Strong knowledge of database design, SQL knowledge, performance optimization, and NoSQL (Redis, Memcached, MongoDB)
* Experience with Linux web server management and security
* Minimum of 2 years of experience in web development with a portfolio of previous work

### Ideally

* Excellent knowledge of back-end web development 
* Experience working with / designing REST APIs
* Experience with Amazon Web Services or Google Cloud
* Some experience with search engines (Solr, Elasticsearch) is a plus
* Familiarity with modern front-end frameworks (React, AngularJS, React Native) is a plus
* Troubleshooting, debugging, optimizing performance.
* Attention to detail, quality, disciplined work.
* Organized, responsible and able to meet deadlines.
* Good English skills, especially reading/writing.

## Responsibilities

* You will be based in Hanoi and will work closely with the Toronto team to develop high-quality software for North American clients. You will report directly to a manager based in Hanoi, and all company communication will be in either English or Vietnamese.
* You will be responsible for back-end development for web applications, e-commerce applications, and REST APIs for use in mobile apps, as well as server setup, maintenance, and support. You will work on developing brand new products, as well as maintaining and adding new features to existing products.
* You will be part of a small team, and your contribution will be essential to the success of each project. You will work on a variety of projects using different technologies and will be expected to learn and grow with the rest of the team.

### Why it would be awesome to work with us
* English working environment and on the job English training;
* Flexible working hours, 5 days a week, and flexible paid leaves
* Free food and drink, lunch support with a private chef.
* Team building and company trip twice/year

### Perks:
* Be a part of a young, dynamic, multinational and multi-functional team that serves global customers with new everyday challenges (Our team has staff working in Canada and Vietnam).
* Monthly 1-1 meeting with your supervisor/manager to ensure you meet your goals and get the support you need to succeed in your position. 
* High work flexibility and ownership (We don’t count every single hour you show up at the office, what we care more is are you able to achieve your tasks each month).
* Frequent training sessions (leadership, technical knowledge...) with opportunities to learn new tools and technologies.

### Contact
giang@mobilefolk.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
