### ISSUE TITLE
Doctor Anywhere - Backend Engineer (Java) - All levels - Hybrid (Hanoi/HCMC) - FT

### ISSUE THREAD

**Issue by AnNgo-DoctorAnywhere** [awesome-jobs/vietnam#3354]
## Location
* **Hybrid Working**
* 81 Cao Thang, Ward 3, District 3, Ho Chi Minh
* 2601 Ngoc Khanh Plaza, No. 1 Pham Huy Thong, Ba Dinh, Ha Noi

## Salary Expectation

* **1,500 - 3,500 USD** per month 
* Negotiation 

## Requirements
* Java
* Spring Framework
* 4+ years Software Engineering experience

### Must Have

* Bachelor's degree in Computer Science with 4+ years of relevant experience in enterprise applications, preferably in Spring framework and Web services, UI frameworks (AngularJS, ReactJS etc.)
* Have experience in translating technical concepts into language for audiences, including software engineers, and business and technical leaders.
* Good problem-solving and analytical skills.
* Have knowledge of the software development life cycle, SCM tools, and CI/CD pipeline.
* Good communication skills.
* High energy, motivated team player.
* Experience working within a tech startup and hyper growth environment.
* Comfortable with fast-paced operations and not be afraid to "roll up your sleeves" to get things done.
* Good English written and verbal communication skills.

### You’ll be responsible for
_We are seeking an enthusiastic and self-motivated **Backend Engineer** to join our engineering team to work on a large-scale, complex system that brings innovation to healthcare. You will be working on modern technology stack and in a cross-functional environment that promotes collaboration within/across teams and managing both internal/external stakeholders._
_You will be responsible for all aspects of product development from initialization till rolled-out. You will be working on architecture, design, implementation, testing, and production support. The ideal candidate will have strong ownership, good communication skills, and enjoy working in highly collaborative and fast-paced environments._

* Collaborate with cross-functional teams to define, design, and ship new features.
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency.
* Ensure the performance, quality, and responsiveness of applications.
* Identify and correct bottlenecks.
* Help maintain code quality, organization, and automatization.
* Develop applications for time-sensitive projects while considering business/system requirements.
* Assist with estimating work efforts required for each phase of a project.
* Provide technical guidance and mentoring to less experienced engineers.
* Identify and raise technical risks.
* Maintain working knowledge of the IT industry and trends.
* Promote a risk-aware culture, and ensure efficient and effective risk and compliance management practices by adhering to required standards and processes.

### Why it would be awesome to work with us
* New and beautiful office in District 3
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th-month salary
* Insurance in full gross salary, Premium Healthcare Insurance
* Annual health check-ups
* Quarterly team outing budget
* Free snack every day
* Laptops, monitors, and anything you need!

### Interesting engineering projects
**Doctor Anywhere (DA)** is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Singapore, Malaysia, Thailand, Philippines, and Vietnam, serving more than 2.5 million (and growing) users across the region.

### Contact
Detail Job Description: https://bit.ly/DAJava
Contact me for more detail via Skype (live:tuananngo) 
Send me your CV via an.ngo@doctoranywhere.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
