### ISSUE TITLE
Doctor Anywhere - Frontend Engineer (ReactJS/ Angular) - Hybrid (Hanoi/HCMC) - FT

### ISSUE THREAD

**Issue by AnNgo-DoctorAnywhere** [awesome-jobs/vietnam#3355]
## Location
* **Hybrid Working**
* 81 Cao Thang, Ward 3, District 3, Ho Chi Minh
* 2601 Ngoc Khanh Plaza, No. 1 Pham Huy Thong, Ba Dinh, Ha Noi

## Salary Expectation

* **1,500 - 3,500 USD** per month 
* Negotiation 

## Requirements
* JavaScript
* ReactJS or Angular Framework
* 4+ years of Software Engineering experience

### Must Have

* Bachelor's degree in Computer Science with 4+ years of relevant experience in building web applications,
* Proficiency with JavaScript, HTML5 and TypeScript 2.4
* Deep knowledge of Angular 5+/ React practices and commonly used modules based on extensive work experience
* Extensive knowledge of CSS and JS methods for providing performant visual effects and keeping the framerate above 30fps at all times
* Thorough understanding of the responsibilities of the platform, database, API, caching layer, proxies, and other web services used in the system
* Experienced in building the infrastructure for serving the front-end app and assets
* Experienced in architecting and automating the build process for production, using task runners or scripts
* A start-up attitude - you take full ownership of things that you do, willing to go out of your comfort zones and take on new challenges.
* Comfortable with ambiguity and flexible to learn new things - we’re not done growing, and heading into uncharted territories is part of the fun!
* English communication skills will be required to work with the regional technology teams and stakeholders.

### You’ll be responsible for
_As **Software Engineer**, you will be responsible for all aspects of product development from initialization till rolled-out. You will be working on architecture, design, implementation, testing, and production support. The ideal candidate will have strong ownership, good communication skills, and enjoy working in highly collaborative and fast-paced environments._
* Delivering a complete front end application
* Ensuring high performance on mobile and desktop
* Writing tested, idiomatic, and documented JavaScript, HTML and CSS
* Writing non-blocking code, and resorting to advanced techniques such as multi-threading, when needed
* Cooperating with the back-end developer in the process of building the RESTful API
* Communicating with external web services
* Collaborate with cross-functional teams to define, design, and ship new features
* Continuously discover, evaluate, and implement new technologies to maximize development efficiency
* Creating custom, general use modules, and components which extend the elements and modules of core AngularJS
* Help maintain code quality, organization, and automatization
* Develop applications for time-sensitive projects while considering business/system requirements
* Writing extensive unit tests using automated TDD tasks
* Creating e2e test suites for all components, and running them with Protractor (or a well-reasoned alternative)

### Why it would be awesome to work with us
* New and beautiful office in District 3
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th-month salary
* Insurance in full gross salary, Premium Healthcare Insurance
* Annual health check-ups
* Quarterly team outing budget
* Free snack every day
* Laptops, monitors, and anything you need!

### Interesting engineering projects
**Doctor Anywhere (DA)** is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Singapore, Malaysia, Thailand, Philippines, and Vietnam, serving more than 2.5 million (and growing) users across the region.

### Contact
Detail Job Description: https://bit.ly/DA-FE
Contact me for more detail via Skype (live:tuananngo) 
Send me your CV via an.ngo@doctoranywhere.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
