### ISSUE TITLE
Doctor Anywhere - Automation QA Engineer (Selenium, Java) - Hybrid (Hanoi/HCMC) - FT

### ISSUE THREAD

**Issue by AnNgo-DoctorAnywhere** [awesome-jobs/vietnam#3356]
## Location
* **Hybrid Working**
* 81 Cao Thang, Ward 3, District 3, Ho Chi Minh
* 2601 Ngoc Khanh Plaza, No. 1 Pham Huy Thong, Ba Dinh, Ha Noi

## Salary Expectation

* **1,500 - 3,500 USD** per month 
* Negotiation 

## Requirements
* JavaScript
* Selenium tools 
* 4+ years of working experience in Software Quality Assurance

### Must Have

* Minimum 4 years of working experience in Software Quality Assurance.
* Degree in Computer Science, Engineering, or a related discipline.
* Strong knowledge of software QA methodologies, tools, and processes.
* Experience in writing clear, concise, and comprehensive test plans and cases.
* Hands-on experience with both white box and black-box testing.
* Hands-on experience with automated testing tools.
* Experience working in an Agile/Scrum development process.
* Good English communication.

### You’ll be responsible for
_As a **Quality Assurance Engineer** you will be responsible for designing and implementing tests, debugging and defining corrective actions. The ideal candidate will also review system requirements and track quality assurance metrics (e.g. defect densities and open defect counts.)
This role reports directly to the Engineering Manager in Singapore._

* Review requirements, specifications and technical design documents to provide timely and meaningful feedback
* Create detailed, comprehensive and well-structured automated and manual test plans and test cases
* Estimate, prioritize, plan and coordinate testing activities
* Design, develop and execute automation scripts using the Selenium tool
* Identify, track, record and document bugs
* Perform thorough regression testing when bugs are resolved
* Develop and apply testing processes for new and existing products to meet business needs
* Liaise with internal teams (e.g. developers and product managers) to identify system requirements
* Monitor debugging process results
* Investigate the causes of non-conforming software to implement solutions
* Stay up-to-date on new testing tools and test strategies

### Why it would be awesome to work with us
* New and beautiful office in District 3
* 16 days AL, +1 after each full-year service
* Competitive salary range and 13th-month salary
* Insurance in full gross salary, Premium Healthcare Insurance
* Annual health check-ups
* Quarterly team outing budget
* Free snack every day
* Laptops, monitors, and anything you need!

### Interesting engineering projects
**Doctor Anywhere (DA)** is on a mission to be the largest tech-enabled, omnichannel healthcare provider in Southeast Asia. First launched in Singapore in 2017, DA aims to bridge gaps in the healthcare ecosystem through developing innovative solutions and technologies. In 2021, DA raised SGD$88 million in Series C fundraising (August 2021) and acquired Doctor Raksa, the biggest telemedicine platform in Thailand which further strengthened our foundation for telehealth and healthcare offerings. Today, DA is present in Singapore, Malaysia, Thailand, Philippines, and Vietnam, serving more than 2.5 million (and growing) users across the region.

### Contact
Detail Job Description: https://bit.ly/DA-QA
Contact me for more detail via Skype (live:tuananngo) 
Send me your CV via an.ngo@doctoranywhere.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
