### ISSUE TITLE
TRS SEA - Senior Java Developer | Fullstack - Ha Noi - FT

### ISSUE THREAD

**Issue by XuanDiep55** [awesome-jobs/vietnam#3359]
## Location

* Ha Noi

## Salary Expectation

* Up to $2500/month (Open to nego) 

## Requirements
* English: Basic Communication skills
* At least 3 years of professional experience, as a developer.
* Have experience and interest in working in a distributed team.
* Proven skills in creating scalable and resilient software designs.
* Ability to follow established architectural guidelines for both design and implementation.
* Must be used to working with (and enjoy) Unit/Integration Test Automation, Scrum.
* Current technologies in use include Java Spring/.NET Web API, and Angular 2+. The more you know the better; otherwise we can help to bridge the gaps. 
* Experience with SCRUM
* Experience with Jira, Confluence

### Must Have

* English: Basic Communication skills
* At least 3 years of professional experience, as a developer.
* Must be used to working with (and enjoy) Unit/Integration Test Automation, Scrum.
* Current technologies in use include Java Spring/.NET Web API, and Angular 2+. 
* Experience with SCRUM
* Experience with Jira, Confluence

### Responsibilities

* Becoming an active part of the team and embody the culture of the tech department.
* Participating in workshops with Product Owner and team to get best possible solutions.
* Development, including coding, testing, unit-testing and code reviewing.
* Troubleshooting system issues and analyze errors for root causes and propose solution.
* Deploying bug fixes and feature releases.

### Why it would be awesome to work with us
* Becoming an active part of the team and embody the culture of the department. 
* Participating in workshops with Product Owner and team to get best possible solutions.
* Up to 14-month salary package (including performance bonus)
* 18 - 20 leaves per year (including at least 13 annual leaves, 5 personal leaves not including publics holidays and work from home).
* MacBook  is provided from probation.
* Personal medical benefit and family medical benefit (AON Insurance package).
* Have a chance to travel onsite in global office.
* Free meal, snacks, refreshment.
* Working in a global working environment
* Working time: 9:00 AM - 6:00 PM from Monday to Friday

### Contact
* Email: diepnguyen@r-starsea.com
* Phone/Zalo: 0374 118 602
* Skype: live:.cid.2d79703d7bce0ead (Diep Nguyen)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
