### ISSUE TITLE
Terralogic - Sr Frontend Web - HCMC - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#336]
Terralogic (former Infornam), headquartered in Silicon Valley, USA is an Engineering & IT services company. It with 1,000 employees and three development centers in US, India and Vietnam provides comprehensive solutions that are cost-effective, scalable and flexible.

The company serves global clients, among them technology pioneers and industry leaders. Our core team is composed of engineers and domain experts who has strong experience and understanding of Mobility, Applications, Networking & Communications and Embedded Systems.

We are building the unimagined and aspiring to be be the most loved organization in the coming years. Accordingly human resources are regarded as our jewels. Terralogic offers a dynamic working environment, professional development and high-end facilities. Our engineers have opportunities to work with foreign customers as well as working onsite in Japan, Europe and the US.
## Location
- Saigon, Vietnam
## Salary Expectation
- Negotiable
## Requirements
- 1-2 years experience frontend development
- Strong point at UI/UX and CMS such as Wordpress/Drupal
- Strong point at ReactJs and React DOM, calling REST API
- Strong knowledge of XSLT, JavaScript, DHTML, CSS skills are musts*
- Experience working with popular frameworks like jQuery, Foundations, and AngularJS 
- Development experience using Flash/ActionScript, FLEX a plus
- Understanding of OO concepts in JavaScript context
- Understanding of DOM, DOM Event Models
- Experience working with AJAX, JSON, XML, XSLT
- Overview and inspect the influence on the enterprise system 
- Good communication, solution in team
- Discuss and finalize the best-fit solutions
- Experience working in agile environment
### Responsibilities
- Code features and resolve issues in XSLT, HTLM, CSS, Nodejs, ReactJS and React DOM
- Work with internal & external teams to solve problems & design features.
- Able to work independently, to design and deliver solutions in a dynamic environment
- Analyze current features and technology and perform optimization
- Develop designs that fulfill functional requirements while proving scalability, performance and maintainability
- Drive excellence and task delivery by leveraging Agile concepts
### What Terralogic offer
- Flexible working schedule. Everything is allowed by trusting the employees
- Competitive Salary: 13th salary + performance awards + project awards; Referral Bonus
- Opportunities for advanced career development overseas: in America, Japan, India…
- Good benefit that takes care of employees work-life balance:
- Insurance: Accident Insurance 24/24 (Gras Savoye Willis); Health Insurance (Gras Savoye Willis):
- Social Insurance tax: was paid as the salary in the labor contract
- Special Leave Days: minimum 15 days/year
### Contact
- Ms Mai Ngo: mai.ngo@terralogic.com
- Skype: mai.ngo91

**Comment by joneslee85** [comment]
Dear Mai, would you be able to provide a section on company intro?

**Comment by RecruiterMaiNgo** [comment]
It's done. Thanks for reminding me.
