### ISSUE TITLE
Otto International - Solution Developer for Finance IT (System Analyst) - HCM - FT

### ISSUE THREAD

**Issue by selinanguyen4717** [awesome-jobs/vietnam#3362]
## Location

* Ho Chi Minh, Vietnam
* Remote

## Purpose

We are searching for a System Analyst interested in technology and changing the team’s work from ideation to production. You will be responsible for maintaining, fixing/debugging, supporting technically and improving the ERP finance system under our IT-Finance team. You will also help the finance users in their daily IT request and feedbacks.

## How will you make a difference?

- Design, develop and implement high-quality software applications
- Analyze the business process and re-engineer functional processes in MS Dynamics Modules
- Solve business problems using development skills to build the right solution for internal stakeholders
- Plan, design, develop, test, maintain and support the implementation of Microsoft Dynamics NAV ERP and related technologies as well as custom software applications
- Comfortable in helping, supporting, and answering support tickets in a timely and expedient manner
- Implement workflows, build/support interfaces and integrations, educate co-workers and assist with other development priorities as required
- Help to create formal technical/system documentation to standards and conventions as needed by team members and end users
- Communicate technical issues effectively to non-technical people as well as understand requirements given by clients and business consultants

## Who are we looking for?

- Degree holder in computer science or related fields
- Relevant Experience in Microsoft Dynamics NAV (preferably experience with NAV 2017 & 2009)
- SQL Server experience, SSRS or RDLC report development a must
- Familiar with integration between NAV and 3rd Party application
- Proven analytical and problem-solving skills
- Flexibility and adaptability in regard to learning and understanding new technologies
- Well-organised with ability to meet tight deadlines
- Self-starter and good team player
- Good communication skills in English (written and spoken)

## Why working with us?

- Collaborative, fun and challenging work environment
- Open, transparent and diverse culture worldwide
- Attractive pay, 13rd salary, holiday bonus, performance bonus
- Flexible working hours, remote working condition
- Full insurance coverage, extra medical insurance.

## Contact
PIC: Selina
Email: selina.nguyen@ottoint.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
