### ISSUE TITLE
Automation Software Tester (QA QC) - Onsite (HCMC) - FT

### ISSUE THREAD

**Issue by 1stFeeder** [awesome-jobs/vietnam#3365]
## Location

* Saigon, Vietnam
* Onsite

## Salary Expectation

* up to $2000

## Requirements
* Minimum of 3 years of experience in Software Testing and Automation Testing tools (Selenium, JMeter, Postman, K6, etc.)
* Experience in CI/CD deployment pipeline and tools
* Experience with web services/REST API test automation
* Experience with version control tools such as Git

### Ideally

* Bachelor/Master Computer Science / Development degree and other related fields
* Experience in Agile/Scrum
* Experience with Java

### You’ll be responsible for

* Perform automation testing on different platforms: Website, Mobile, API services
* Managing the bug life cycle
* Follow test cases that provide by the manual team to develop test scripts.
* Creation and execution for test plans, test cases, and test reports
* Ensure the assigned tasks to be performed on time and with high quality
* Transfer knowledge to team members on automation testing
* Coordinate with SW engineers to analyze and fix bugs
* Collaborate with the BA team to update documents for new requests

### Why it would be awesome to work with us

* Part of a pioneer team of a digital start-up in customer engagement and loyalty platform with huge growth opportunities and strong backing from two organizations
* 13th-month salary and performance bonus
* 12 annual leaves + 3 sick leaves
* 100% Social Insurance
* Private healthcare insurance, yearly checkup
* Training sessions
* Gathering activities in special occasions (Christmas, New Year, Women’s Day, etc.)
* Company trip and team building activities
* Snacks, tea and coffee are ready to serve
* A flexible environment with super fun and enthusiastic colleagues

### Contact

Contact me for more detail via Skype (live:.cid.35ca6c080a7ab3ff)
Send me your CV via [minh.nguyen.2@hr1vietnam.com](minh.nguyen.2@hr1vietnam.com)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
