### ISSUE TITLE
Senior DevOps - Onsite (HCMC) - FT

### ISSUE THREAD

**Issue by 1stFeeder** [awesome-jobs/vietnam#3366]
## Location

* Ho Chi Minh city, Vietnam
* Onsite

## Salary Expectation

* up to $2000

## Skills and Experience
* Bachelor/ Master degree in IT / networking / development and other related fields.
* At least 4+ years experience with automating build, deployment, and configuration of complex applications.
* Experience with container: Docker and related technologies. K8S is a plus.
* Experience in cloud infrastructure is a plus, especially with AWS or Google Cloud.
* Experience in building highly available and scalable infrastructure.
* Experience with automation/ orchestrating tools and configuration management systems such as Ansible, SaltStack, CloudFormation, Puppet, etc.
* Experienced in CI/CD tools such as Jenkins 2/Hudson, Sonar, Nexus/JFrog, ect.
* Experience in scripting (e.g., shell, python, ruby, etc.)

### You’ll be responsible for

* Manage VM/Cloud infrastructure, including but not limited to building, deploying, orchestrating clusters.
* Develop and maintain scripts and tools, for example, to take snapshots, back up clusters.
* Build monitoring system for Audit infrastructure’s security & make necessary changes.
* Define workflows to best serve the purpose of secure, stable, flexible and scalable clusters.
* Optimize infrastructure for security, performance, and cost.
* Work closely with each of our product development teams you will ensure that our CI tools, processes and methods to ensure a smooth and transition from our development to our production environments.
* Perform integration build and make sure the build is successful.
* Deploy product for sanity testing.
* Simulate end-user for platform testing.
* Compose Installation Guide, Release documents.
* Contribute to the quality management.
* Bring a culture of automation first with what you do as well as a collaborative approach to working with development and operations teams.

### Why it would be awesome to work with us

* Part of a pioneer team of a digital start-up in customer engagement and loyalty platform with huge growth opportunities and strong backing from two organizations
* 13th-month salary and performance bonus
* 12 annual leaves + 3 sick leaves
* 100% Social Insurance
* Private healthcare insurance, yearly checkup
* Training sessions
* Gathering activities in special occasions (Christmas, New Year, Women’s Day, etc.)
* Company trip and team building activities
* Snacks, tea and coffee are ready to serve
* A flexible environment with super fun and enthusiastic colleagues

### Contact

Contact me for more detail via Skype (live:.cid.35ca6c080a7ab3ff)
Send me your CV via [minh.nguyen.2@hr1vietnam.com](minh.nguyen.2@hr1vietnam.com)
Telephone: +84 779000268

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
