### ISSUE TITLE
Technical Architect (Nodejs, Java) - Onsite (HCMC) - FT

### ISSUE THREAD

**Issue by 1stFeeder** [awesome-jobs/vietnam#3367]
## Location

* Saigon, Vietnam
* Onsite

## Salary Expectation

* up to $3000

## Skills and Experience
* Bachelor’s degree or equivalent with a focus on computer science, information technology, or a related field.
* 7+ years of experience in analysis, design, and development of Java applications.
* Experience in non-functional aspects, i.e., security, performance, and scalability.
* Strong understanding and experience of common software design patterns.
* In-depth experience of clean code, coding standards, and code review.
* In-depth experience of unit tests, mocking libraries, code coverage, and code refactoring.
* In-depth experience of Java development ecosphere: Spring Core, Spring Boot, Hibernate, Spring MVC, Spring Security, Spring JPA, Spring Batch, Hazelcast, Elasticsearch, GWT, JSF/Prime Faces.
* In-depth experience in building REST APIs for scale and security.
* Experience with MongoDB and Elasticsearch.
* Advanced knowledge of Java Core and Java Concurrency Framework.
* Advanced knowledge in building and deploying Java-based web applications using Maven, Tomcat, or Embedded Jetty server.
* Experience with at least one CI/CD tool (e.g., Jenkins, GitLab, or Bitbucket).
* Experience in cloud computing (AWS EC2).

### Good to have

* Experience in microservices architecture, load balancing.
* Oracle Professional Certificates.
* UML, arc42, structure101.
* Redis, Kafka, RabbitMQ
* Good knowledge of the JVM structure
* Good knowledge of JDK tools (Java Mission Control, jmap, jstat, jstack)
* Experience in JVM profiling, Performance monitoring.
* Experience in front-end technologies (i.e., HTML/CSS, Node.js, React, TypeScript, Vue.js, or other JavaScript libraries/frameworks).
* Experience with TDD/BDD.

### You’ll be responsible for

* Participate in the entire software development life cycle of the Agile team (requirement analysis, planning, architectural design, documentation, implementation, code review, unit test, test, and deployment).
* Provide technical leadership for Java teams.
* Review source code and coach colleagues to follow coding standards, design patterns, and implement tests.
* Conduct R&D activities and make workshops.
* Advise development teams on the use of static code analysis tools and configure the tools.
* Assist the Engineering Manager and teams in their daily work to build the knowledge base and improve the development, testing, and deployment process together.
* Documenting technical documents (architectural design, system design, database schemas…).
* Adhere to programming conventions and good programming practices.
* Recommending and implementing improvements to processes and technologies.
* Keeping informed of advancements in the field of Java development.

## Why it would be awesome to work with us

* Part of a pioneer team of a digital start-up in customer engagement and loyalty platform with huge growth opportunities and strong backing from two organizations
* 13th-month salary and performance bonus
* 12 annual leaves + 3 sick leaves
* 100% Social Insurance
* Private healthcare insurance, yearly checkup
* Training sessions
* Gathering activities in special occasions (Christmas, New Year, Women’s Day, etc.)
* Company trip and team building activities
* Snacks, tea and coffee are ready to serve
* A flexible environment with super fun and enthusiastic colleagues

### Contact

Contact me for more detail via Skype (live:.cid.35ca6c080a7ab3ff)
Send me your CV via [minh.nguyen.2@hr1vietnam.com](minh.nguyen.2@hr1vietnam.com)
Telephone: +84 779000268

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
