### ISSUE TITLE
Hybrid work | Full Stack Engineer (NodeJS/ReactJS) 

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3368]
## Location

* Saigon, Vietnam
* Hybrid work

## Salary Range

* $2000

## Requirements

**Required skills:**

- Computer Science Degree or qualifications in a related field
- Minimum of 3 years’ experience programming in the information technology field with experience related to this position’s role; or an appropriate combination of education and technology field related experience.
- Solid experience in NodeJS, ReactJS, JavaScript, CSS, and Material UI.
- Experience with both MS SQL and MySQL.
- Good understanding of RESTful web services.
- Good knowledge of OOP, design patterns.
- Experience using development tools such as Jira, Confluence, Bitbucket
- Experience working with Scrum frameworks
- Strong communication skills
- Self-Starter – willing to contribute wherever needed
- Good in English

**Desired skills:**

- Good understanding of SOA, Microservices
- Experience working with Amazon Web Services, Lambda
- Experience with CI/CD
- Experience working with NoSQL

## Responsibilities

- Developing UI by utilization of new front-end technologies
- Troubleshooting end user issues and automated processes
- Developing and maintaining backend APIs
- Performing unit testing
- Analyzing errors and developing potential solutions
- Consulting with managerial, engineering, and technical personnel to clarify program intent, identify problems and suggest/implement changes
- Conducting trial runs of software application updates, and fixes, to ensure desired functionality
- Independently creating software development documents (SRSes, design documents, etc.)
- Managing technical projects involving own work under minimal supervision
- Developing and demonstrating knowledge of related systems
- Suggesting analysis and design for enhancements for current applications
- Willingness to contribute ideas to the troubleshooting and resolution of application issues in a timely manner
- Pro-actively looking for the best solution to achieve the most efficient performance of Live group systems
- Interacting with all stakeholders within IT and the user community as required
- Ad hoc duties as required.

## Your benefits

- Gross salary which includes tax, medical, social and unemployment insurance
- Performance review twice a year
- Premium healthcare plan
- 13th month salary and performance bonus
- 14 days annual leave
- Laptop provided
- Free parking, coffee, and snacks.
- Online technical training courses
- Opportunity to work with one of Australia’s fastest growing payment companies
- Regular team dinners and team building activities
- International, friendly working environment.

## Contact
Email: ha.tran@livegroup.com.au
Skype: khanhhatran213

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
