### ISSUE TITLE
.NET Developer (Hybrid work in HCMC)

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3369]
## Location

* Saigon, Vietnam
* Hybrid work (2 days at office, 3 days remote)

## Salary Range

* $2000

## Requirements

- Computer Science Degree or qualifications in a related discipline 
- Minimum of 3 years’ experience programming in the information technology field with experience related to this position’s role; or an appropriate combination of education and technology field related experience

### Must Have
**Programming Skills:**

- ASP.Net MVC Framework
- C#
- Extensive knowledge of Entity Framework
- Experience in design patterns such as Singleton, Bridge, Proxy, etc.
- Experience in Web API, jQuery, CSS, HTML, JavaScript
- Experience in Node JS would be beneficial
- Experience unit testing with NUnit

**Database skills:**

- Knowledge of Microsoft SQL Server development (ability to write triggers, stored procedures, views, functions etc.)
- Familiarity with Scrum process framework
- The ability to develop and maintain thorough software documentation
- Experience working in a matrix organization
- Must be comfortable working with a cross functional team
- Self-starter – willing to contribute wherever needed

### Ideally

**The following skills are highly regarded, though not essential:**
- Programming skills:Experience with No SQL database
- XML
- Familiarity and experience working with Jira
- Experience in DB design, data dictionary, database optimisation
- Graduated from an English-speaking country such as Australia, USA, UK, or Singapore

## Responsibilities

- Troubleshooting end user issues and automated processes
- Analyzing errors and developing potential solutions
- Consulting with managerial, engineering and technical personnel to clarify program intent, identify problems and suggest/implement changes
- Conducting trial runs of software application updates, and fixes, to ensure desired functionalities
- Independently creating software development documents (SRSes, design documents, etc.)
- Managing technical projects involving own work under minimal supervision  
- Developing and demonstrating knowledge of related systems
- Suggesting analysis and design for enhancements for current applications  
- Willingness to contribute ideas to the troubleshooting and resolution of application issues in a timely manner 
- Pro-actively looking for the best solution to achieve the most efficient performance of Live group systems
- Interacting with all stakeholders within IT and the user community as required  
- Ad hoc duties as required.

## Why it would be awesome to work with us

- Gross salary which includes tax, medical, social and unemployment insurance
- Performance review twice a year
- Premium healthcare plan
- 13th month salary and performance bonus
- 14 days annual leave
- Laptop provided
- Free parking, coffee, and snacks.
- Online technical training courses
- Opportunity to work with one of Australia’s fastest growing payment companies
- Regular team dinners and team building activities
- International, friendly working environment.

## Contact
Email: ha.tran@livegroup.com.au
Skype: khanhhatran213

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
