### ISSUE TITLE
Hybrid work | IT Business Analyst

### ISSUE THREAD

**Issue by Hattk** [awesome-jobs/vietnam#3372]
## Location

* Saigon, Vietnam
* Hybrid work

## Salary Range

* $1400-$2000

## Requirements

- University Degree Qualified in a Tech or Business field.
- 2+ years’ experience working in similar roles.
- Experience working in the payments and/or financial services industries is advantageous.

## Skills

- Excellent understanding of Agile and experience working in Agile driven environments.
- Superior ability to translate business requirements into functional, non-functional, and technical requirements.
- Highly developed technical capabilities and understanding of the systems landscape and intended architecture including potential impacts on the business and solution design implications.
- Experienced in working with various aspects of technology solutions (e.g., user interfaces, mobility, API, databases, system integration) and dealing with technology specialists.
- Outstanding presentation, communication, and technical writing skills, with the ability to convey simple and complex information to technical and non-technical audiences at any level.
- Demonstrated analytical and problem-solving skills with strong attention to detail.
- Excellent English skills in writing, reading, speaking, and listening.
- Adaptable, fast learner and proactive.

## Responsibilities

- Understanding and considering both business and technical engineering/IT needs to ensure quality digital products and related operational workflows to meet/exceed the desired business objectives.
- Using data and process modeling tools (including, but not limited to, process mapping, activity diagram, and dataflow modeling) to analyse and translate business requirements into meaningful statements of work that is acceptable to both business and technology stakeholders.
- Performing system analysis activities (e.g., “as-is”, “to-be”, gap analysis) to ensure system and data integrity.
- Translating business requirements into functional, non-functional, and technical requirements to include business processes, workflow diagrams, use cases along with requirements of user experience, system access, security, mobility, data integration, UI integration, data entry and reporting.
- Documenting best practices, business processes, requirements, technical documentation, system guides and release notes.
- Participating in the design of system and application architectures.
- Providing support in testing activities, reviewing test cases and test results, organising reviews, tracking feedbacks, and facilitating UAT when needed.
- Supporting Product Owners through Scrum activities. Playing the role of Product Owner when required.

## Why it would be awesome to work with us

- Premium healthcare plan for employee and family members (spouse and children).
- Gross salary which will include tax, medical, social, unemployment insurance.
- 13th month salary
- 14 days annual leave plus one day off for your birthday
- Regular team dinners and team building activities.
- Online technical training courses.
- Laptop with 2 external monitors.
- International, friendly working environment.
- Amazing office space which includes free parking, coffee, snacks, and games.

## Contact
Email: ha.tran@livegroup.com.au
Skype: khanhhatran213

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
