### ISSUE TITLE
[MEGAZONE] Front-end Dev (Angular/ReactJS/VueJS/JavaScript) - Up to 2500$

### ISSUE THREAD

**Issue by dangokuson** [awesome-jobs/vietnam#3376]
## Location
* Hanoi, Vietnam

## Salary Expectation

* Up to $2500/month or range

## Requirements
* University degree in Computer Sciences, or equivalent.
* Good knowledge of web service development (SOAP, RESTful). 
* Good knowledge of HTML5, CSS3, JavaScript, Ajax. 
* Have the ability to do development work for the front-end. 
* Logical thinking and problem-solving skills

### Must Have

* Strong knowledge of HTML/CSS and JavaScript
* 3+ years experience of development in the frontend, using Angular/ReactJS/VueJS
* Experience with a testing framework (e.g., Jest, Mocha, testing library, etc...)
* Experience with Agile Scrum
* Experience with Ember or other JavaScript
* Familiarity with concepts of MVC, and RESTful
* Good understanding of SOLID principles, common design patterns, and best practices
* Experience with design tools such as Sketch, Zeplin, Figma

### Responsibilities

The Front-End Developer is responsible to write software applications from design specifications

* Develop a website, and a real-time system and write frontend-code on multiple platforms: PC, Mobile, Tablet
* Improve the performance, standardize the websites, and SEO to create images for the company
* Ensure high performance on multiple platforms
* Write tested, idiomatic, and documented JavaScript, HTML, and CSS
* PSD to HTML must-have.
* Good at ReactJS, React redux, …etc.
* Coordinate the workflow between the graphic designer, the HTML coder, and yourself
* Cooperate with the back-end developer in the process of building the RESTful API.

### Why it would be awesome to work with us

* Product company with a global reputation specializing in end-point security
* Very attractive salary (Negotiation)
* 13th-month salary
* Full salary during the probation period
* Birthday gift
* Flexible working hours (Working time: 8:30 AM - 5:30 PM from Monday to Friday)
* Training & development opportunities
* Macbook Pro for everyone

### Contact

Email: sondn@mz.co.kr
JD: https://itviec.com/it-jobs/front-end-dev-javascript-up-to-2500-megazone-5333?lab_feature=employer_job

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
