### ISSUE TITLE
DanteHQ - Data Engineer - Flexible (preferably HCMC) - FT

### ISSUE THREAD

**Issue by octopus198** [awesome-jobs/vietnam#3377]
## Location

* Saigon, Vietnam (or remote)

## Salary Expectation

* Up to $2000/month

## Soft skills
* A strong sense of responsibility and commitment
* Constant curiosity about customers’ needs and the world at large
* Top-notch communication skills
* Willingness to voice your own ideas and opinions, and to work on new problems as they arise

## Tech skills
* Experience in the Big Data technologies(Hadoop, M/R, Hive, Spark, Metastore, Presto, Flume, Kafka, ClickHouse, Flink, etc.)
* Experience with performing data analysis, data ingestion, and data integration
* Experience with ETL(Extraction, Transformation & Loading) and architecting data systems
* Experience with schema design, data modeling, and SQL queries

### Responsibilities

* Design and build data transformations efficiently and reliably to gather and report blockchain-related metrics (both on-chain and off-chain)
* Design and implement reliable, scalable, robust and extensible big data systems that support core products and business
* Establish solid design and best engineering practice for engineers as well as non-technical people

### Why it would be awesome to work with us
* As a full-time Data Engineer at DanteHQ, you have the opportunity to shape the direction of the company. We do not care about ranks or seniority. There is no micro-managing here. Only execution and results matter. So if you are looking for a place to embrace all the challenges and joys of building a startup, join us.
* DanteHQ’s mission is to bring data, analysis, and insights to the crypto community. We are building a financial data and research platform to help crypto investors, traders, and developers make informed decisions.
* DanteHQ was founded by a team of engineers from Amazon and TikTok. We are also the third Vietnamese companies to receive funding from Y Combinator, the world-class accelerator that has helped great companies such as Airbnb, Reddit, and Stripe get started. Our website is https://www.dantehq.com/.  

### Contact
Homepage (under development): dantehq.com 
Email: long@dantehq.com 

[Job Description_ Data Engineer.pdf](https://github.com/awesome-jobs/vietnam/files/8679751/Job.Description_.Data.Engineer.pdf)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
