### ISSUE TITLE
[IZION24] - [SENIOR IT SOLUTIONS ANALYST] - [HCM] 

### ISSUE THREAD

**Issue by thaoanhnguyen** [awesome-jobs/vietnam#3378]
## Location

* HCM, Vietnam
* Fulltime - onsite

## Salary Expectation

* $2,000-$3,000

## Requirements
* Bachelor's degree in computer science, software engineering or IT
* Min 5 years of relevant experience
* Knowledgeable in Business and Functional Requirement Analysis, and User Acceptance Test (UAT) approaches, methodologies and tools
* Development experience in Java, Spring boot, Hibernate, Javascript, Apache Groovy and MySQL
* Experience with Microservices, REST APIs and DevOps concepts

### Responsibilities
* Deeply understanding core back-end BFF APIs to support developers enhancing existing BFF APIs or developing new BFF APIs for new products.
* Working with other project members from various business units to identify functional solutions for the objective of the project (scope: BRD, Functional Requirement study, UAT and support)
* Provide requirements specifications according to standard templates; decompose business requirements into Functional Specification Document (FSD).
* Conduct solution analysis and engage through all phases of requirements translation to system changes developments. Cover the technical design changes impact assessment in the new solutions deployed.
* Obtain functional requirements via interviews, document analysis, requirements workshops, surveys, site visits, business process descriptions, used cases, scenarios analysis, etc.

### Why it would be awesome to work with us
* Our insurance marketplace app aims to offer one-stop solution for all insurance related needs and expected to serve millions of customers through digital distribution.
* An innovative insurtech start-up that disrupts the traditional insurance market in Vietnam, our goal is to reinvent the ways people perceive insurance, making insurance accessible and available for every common man, especially for the young and dynamic generation.
* Premium healthcare plan for employee
* 13th month salary + Annual KPI Bonus
* 15 days annual leave 
* Company Laptop 
* International, friendly working environment.
* Amazing office space at heart of the city which includes free parking, coffee, snacks.

### Contact
Thao Anh Nguyen: 0779556279 (anh.nguyen@ideallife.com.vn)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
