### ISSUE TITLE
Senior AX Developer - HCMC - FT - up to $1500

### ISSUE THREAD

**Issue by 1stFeeder** [awesome-jobs/vietnam#3379]
## Location

* Saigon, Vietnam
* Onsite

## Salary Expectation

* up to $1500 Gross - Negotiatable

## Skills and Experience
* Experience with development and customization in AX 2012 is a MUST.
* Good software programming skills, comprehensive language X++.
* Good Dynamics AX 2012 framework understanding: Run Base, Sy Operation,
reporting SSRS.
* Experience with Dynamics AX 2012 integration technology: AIF, DLL embedded.
* Fluent English

### Good to have

* Microsoft Dynamics AX 2012 certificate is a PLUS.
* Knowledge about Dynamics AX 2012 retail development (Retail SDK, Data synchronize).
* Knowledge about C#, SQL, web service is a PLUS.

### You’ll be responsible for

* Create technical design documents, coding, unit testing and for developed functionality
of Microsoft Dynamics 365 for Finance and Operations or AX 2012 based on functional
design documents.
* Provide support and expertise on development technologies and environments.
* Data migration, integration development and testing

## Why it would be awesome to work with us

* Being part of one of the biggest FMCG distributors in Vietnam with an expansive global and regional network 
* 13th-month salary and performance bonus
* 12 annual leaves 
* 100% salary during probation period
* Private healthcare insurance, yearly checkup
* Training sessions
* Gathering activities in special occasions (Christmas, New Year, Women’s Day, etc.)
* Company trip and team building activities
* A flexible environment with super fun and enthusiastic colleagues

### Contact

Contact me for more detail via Skype (live:.cid.35ca6c080a7ab3ff)
Send me your CV via [minh.nguyen.2@hr1vietnam.com](minh.nguyen.2@hr1vietnam.com)
Telephone: +84 779000268

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
