### ISSUE TITLE
Leflair - AngularJS / NodeJS Developer - Saigon - FT

### ISSUE THREAD

**Issue by angiedang** [awesome-jobs/vietnam#338]
![img_7142-smallersize](https://cloud.githubusercontent.com/assets/22335722/19109942/c7887014-8b21-11e6-943e-034ced684ce9.jpg)
## Location
- Saigon, Vietnam
## About Us

Leflair is the go-to destination for smart buyers who wish to purchase branded and quality products at great price, while enjoying the same exclusive shopping experience as in luxury stores.
Leflair provides its members with exclusive access to the world’s best brands at up to 50% off retail. Every morning, we begin flash sales for women, men, kids, and home.
## Salary Expectation
- up to $2000/month 
## Requirements
- AngularJS / Javascript
- Node.js 
- HTML5, CSS3, Bootstrap
- Responsive Design
- Git
- Automated Testing
### Must Have
- Strong English skills are necessary
- Good communications skills
- Logical thinking and analysis
- Attention to detail
### Ideally
- MongoDB/Mongoose
- Grunt, Gulp etc.
- CI/CD Tools
- Cloud Infrastructure and Docker
- Microservices Architecture
### Responsibilities
- Work with the CTO (expat) to build our ecommerce web site and management platform
- Implement site designs using HTML5, CSS3, Bootstrap, AngularJS
- Develop our backend APIs using Node.js
- Work with NoSQL and SQL databases
- Test our applications
- Code review and refactoring
### You’ll be responsible for
- Building our site www.leflair.vn
### You can bring
- Your sense of humor
- Your awesomeness
### Contact

Apply on our Career Page at www.leflair.co/careers

**Comment by joneslee85** [comment]
Thanks for posting with us.

Please revise following:

* Bullet point format is not consistent, please use `*` for all
* Title does not conform with our guideline
* Please add a section on company intro
* Move photo to the top

**Comment by angiedang** [comment]
@joneslee85 thank you, I have edited the post accordingly

**Comment by angiedang** [comment]
we are still hiring everyone! Come join with us :+1: :100:
