### ISSUE TITLE
[Boost] Senior Frontend Developer (HTML,CSS, JAVASCRIPT) - Remote

### ISSUE THREAD

**Issue by jennynguyen95** [awesome-jobs/vietnam#3381]
## Location
* Remote

## Salary Expectation

* Range: $1300-$2500 NET

## Responsibilities
* Works closely with a team of software engineers to design, develop and maintain frontend web app using mainly Vanilla Javascript
* Optimization of the frontend application for the best performance and highest compatibility of multiple devices and browsers
* Building reusable code and libraries for future use
* Build widgets to increase more utilities for the main app
* Perform integration between our app and third-party apps
* Support team member to resolve complicated technical issues.
* Collaborates on best practices for all phases of development, testing, and deployment
* Participates in Agile meetings to contribute to development strategies and product roadmaps
* Advocates and champions use of industry best-practices, high-quality code, and compliance
* Writes clean, well-documented code for company's products

## Basic qualifications
* Bachelor's Degree in Computer Science or a related field.
* At least 4 years working experience in Frontend developer.
* Established skills in Problem Solving and Critical Thinking.
* Strong Knowledge of Javascript/HTML/CSS (Ajax, JSON, jQuery)
* Established skills in Debugging issue on major web browsers.
* Pay attention to every detail/aspect of the work.
* Good communication (verbal and written) and interpersonal skills.

## Prefer qualifications
* Be able to communicate in English.
* Have track of record in e-commerce.
* Having track record of Node.js.

## Benefits
* 100% remote culture. Live and work from wherever you feel happiest
* 13th-month salary and performance bonus
* Day-off: 14 days/year and Vietnam holidays
* Macbook provided after probation period
* Bao Viet Health Care Insurance (after 3-month in the role)
* Monthly company party and quarterly company trip
* Free online learning and Reimbursement for selected courses.
* Free access to the co-working space
* Annual health checks
* Allowance for gyms, fitness, yoga plus cash bonuses for lots of occasions around the year
* Great chance to improve your expertise/skills and English communication via international exposure
* Get support and work with talented and friendly members

## Working time
* From Monday to Friday with working time 8:00 am to 5:00 pm

## Contact
Website: https://boostcommerce.net/
Email: jenny@boostcommerce.net
Skype: hoaiphuong8795

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
