### ISSUE TITLE
Freelancer - Senior Ruby Developer (Full-time Remote) 

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3382]
## Location

* Remote

## Salary Expectation

* upto $2800
## Requirements
- 2+ years of Ruby on Rails experience
- Experience with ERB
- Experience with CoffeeScript
- Experience with Capybara
- Experience with developing API
- Familiarity with the following gems Pundit, Devise and DelayedJobs
- Good at analyzing & problem solving skill
- Ability to learn new technologies quickly
-  Willingness to work with a distributed team

Preferred skills and experiences
- Experience with Elastic search
- Experience with different types of database
- Experience with React
- Experience with CI/CD (CircleCI, Jenkins)
- Experience with AWS lambda
- Leadership skill is a plus

### Responsibilities
- Communicate to project coordinator, client and team to analyze, clarify requirements
- Take part in design process of source code structure, architect for the system
- Implement assigned features in the system
- Review code and work output for other members
- Train and support other junior members
- Join in delivery process for clients (packaging, documentation, deployment)
- Contributing ideas to optimizing working processes
- Weekly report to the Project Manager

### Why it would be awesome to work with us

- Competitive Compensation And Benefits
- Attractive salary (13th-month salary, salary review twice/year) and project bonus
- Bonus programs for candidate referral, technical article writing
- Interest-free loan support for personal plan
- Exciting Activities
- Annual company trip and regular team-building parties
- Party celebration (Christmas, Birthday, Mid-autumn,...)
- Sports clubs (football, badminton, swimming …)
- Valuable Training
- Sponsor examination fee for professional certificates (AWS, Azure, IELTS, PMP, Scrum Master,...)
- Sponsor fee for joining any technical training sessions and courses.
- Free English courses
- Flexible And Professional Working Environment
- A professional English-speaking working environment with Agile – Scrum model
- Flexible working time and WFH support.
Health Care Benefits
- Allowance for sickness, maternity and paternity.
- Periodic health examination
- PVI health care program
Inclusive Culture
- Friendly, open-minded, young and supportive colleagues

Report to
Project Manager

Interview process
1 interview with clients

### Contact
Skype: Huehuenoivu

**Comment by huydx** [comment]
Don't accept job from agents
