### ISSUE TITLE
We'd like to hire engineer who want to make NFT market place

### ISSUE THREAD

**Issue by mikosea** [awesome-jobs/vietnam#3383]
### Location
Remote

### Salary Expectation
$2,000 - $4,000

### Requirements
5+ years Software Engineering experience

### Skills
Full stack (FE/BE) S/W engineering experience
Leadership, communication & management skills
Up to date with new (trending) programming languages and skills

#### Frontend
TypeScript
React

#### Backend
nodejs
solidity

#### Infra
AWS

#### What we will make
NFT marketplace
Please contact me if you are interested in NFT and Blockchain.

E-mail: [toshi.naka@mikosea.io](mailto:toshi.naka@mikosea.io)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
