### ISSUE TITLE
<Ca*ro Sing> Lead Engineer - Fulltime Remote #ReactJs

### ISSUE THREAD

**Issue by tieuvu9x** [awesome-jobs/vietnam#3387]
## Location

* Remote #VietNam 

## Salary Expectation

* $4000 - $5000 

### Key responsibilities

We are looking for a lead engineer with a strong background in building extensible and scalable modern web applications, to champion our frontend engineering efforts. As a Lead engineer, you will be the expert in building solutions, raising engineering standards and promoting a strong engineering culture. 

What you will be doing:
- Work across teams with other frontend engineers, backend engineers, designers, and product managers. 
- Deconstruct complex problems and work towards a clean lightweight solution, by yourself or with the team. 
- Collaborate with senior engineers to architect and build product features and experiences
- Serve as a point-person to your team and guide them through feature planning, scoping, hiring, execution and quality assurance. 
- Collaborate with design, product teams to understand product requirements, provide technical expertise/insights and translate requirements into amazing user experiences. 
- Participate proactively in code reviews to maintain a high-quality testable code culture

### Required skills and experiences
What you will need:
- Bachelor in Computer Science / Software Engineering or at least 5 years of front-end development experience in an agile environment with a minimum of 2 years in a team lead position.
- Demonstrable expert level ReactJs development experience on consumer or business products
- In-depth knowledge of Javascript/HTML/CSS and modern libraries and tools such as React Redux, Typescript, etc..
- Knowledge cross-browser compatibility, progressive enhancement and accessibility, webAPIs, testing, profiling and debugging practices. 
- Development experience with distributed systems
- Experience with working and managing hybrid models of remote and on site teams.
### Preferred skills and experiences
- Experience working with a product-based organization, e-commerce, automotive is advantageous
- Good working knowledge of backend web framework such as Laravel (preferred), Ruby..etc

###  Benefits
- Opportunities to improve English skills
- Opportunities to gain hands-on experience in cutting-edge technologies.
- Salary review based on performance upon request.
- Fast-tracked career opportunities to lead teams as Carro scales
- 12 Days Annual Leave 
- Self Development Fund 
- Social Security 
- Pantry, Social Gathering 
- Transportation Allowance
- Professional, dynamic and open working environment
**Please note that we are a Singaporean company so we won't be able to cover the social insurance for you.
### Contact me
Skype: natsuyuki91
Phone/Zalo/Telegram: (+84) 926 953 942 (Ms Phương)

**Comment by huydx** [comment]
Need company name
