### ISSUE TITLE
Technixo - Frontend ReactJS level Middle, Junior - Onsite/Hanoi - FT

### ISSUE THREAD

**Issue by joeydang1612** [awesome-jobs/vietnam#3388]
## Location

* Thanh Xuan, Hanoi, Vietnam
* Onsite
* Fulltime

## Salary Expectation

* $800 - $1800 net/month or range

## Requirements
* React.js and Redux
* HTML/CSS, Javascript, Typescript
* Experience with Web Socket, RESTful APIs
* 1+ years of experience for junior level, and 2+ years of experience in Frontend Development for Middle level
* Experience with common front-end development tools such as Yarn, Webpack, NPM, Storybook
* Experience with Responsive Web and Cross-Browser compatibility
* Familiarity with web performance optimization techniques
* Ability to write well-documented, clean Javascript code
* High learning agility and real passion for coding and programming, innovation, and solving challenging problems
* Knowledge of blockchain and smart contracts concepts (especially Ethereum, BSC, NFT, etc.)
* Experience with the various web3 & defi protocols
* Experience with Agile Development (Scrum, Standup, Sprint)

### Must Have

* React.js and Redux
* HTML/CSS, Javascript, Typescript

### Responsibilities

* Maintain and develop new applications using Reactjs
* Building reusable components and front-end libraries for future use
* Optimizing components for maximum performance across a vast array of browsers
* Collaborating with back-end developers and web designers to improve usability, performance
* Troubleshooting/fixing problems

### Why it would be awesome to work with us
* 13 month bonus
*** Social insurance 100% salary
* Review quarterly (Upto 2-5 month salary)**
* Get 1 free card at Stellar Fitness (gym, yoga, zumba, 4-season swimming pool, healthy massage, sauna, cafe…)
* Flexible working time
* Provided with Macbook & other devices for work
* Salary review twice a year
* Chance to work, train or switch to Blockchain industry (very hot now)
* Social insurance, health insurance Travel, vacation, Tet holiday, public holiday....
* A successful qualified candidate will work with the youth dev team, develop and scale current business. We are using outsourcing and solutions to make revenue and reinvest into our team ideas to break the world

### Contact
Email: binhdtt@technixo.com
Zalo: 0854120287

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
