### ISSUE TITLE
FREELANCER - PRODUCT MANAGER - BLOCKCHAIN

### ISSUE THREAD

**Issue by phuongthuan158** [awesome-jobs/vietnam#3389]
## Location

* Freelancer

## Salary Expectation

* Negotiate

## Requirements
* Form of work: Freelance (about 20 hours per week)
* Have a minimum of 2 years working as a product manager in the blockchain sector
* Capable of product orientation, developing products based on Blockchain solutions Mastering the blockchain product development process, understanding the operation of a blockchain product
* Understanding blockchain standards Understanding industry, understanding market trends
* 5+ years Software Engineering experience

## Job Description
* Consulting support, orientation for products of VMO blockchain customers
* Support to advise VMO on how to approach the problems of customers who need to develop blockchain software
* Training and guiding VMO team on blockchain

### Contact
Mail: thuanptp@vmogroup.com
Skype: Phương Thuận

**Comment by huydx** [comment]
don't accept jobs from agents
