### ISSUE TITLE
JobSeekervn - Blockchain Developer - $1800 - $2500 - Fulltime 

### ISSUE THREAD

**Issue by hahoainhi** [awesome-jobs/vietnam#3390]
## Location
* Saigon, Vietnam
* Fulltime Office-based or Fulltime Remote

## Salary Expectation
* $1800 - $2700 /month 

## Requirements
* Knowledge of blockchain and smart contracts concepts (especially Ethereum, BSC, NFT), with at least 1 year of experience in develop and deploying production code to mainnet
* At least 3 years of experience in front end & back-end languages (ReactJS & NodeJS preferred)
* Strong cryptography knowledge
* Experience working with system design, architecture, infra system; popular framework for the respective development environment; source version control (Git/Github preferred).
* Maintain a good coding standard, familiar with Test Driven development. 

### Responsibilities
* Research, design, develop, and test blockchain technologies 
* Analyze, brainstorm and evaluate applications of newly emerged tools and technology.
* Maintain and extend the current platform, responsible both for the blockchain smart contract and the integration to the client & server side application.
* Document new solutions and maintain the existing one.

### Why it would be awesome to work with us
* Social insurance, health/life/disability insurance, annual health check
* 13th month salary 
* Yearly bonus up to 2 month pay depending on performance review
* 14 days of paid vacation                
* Laptop Provided 

### Contact
Homepage: nhiha.top
Email: nhiha@jobseeker.vn 
Skyoe: hahoainhi

**Comment by huydx** [comment]
don't accept jobs from agents
