### ISSUE TITLE
Spree - Ruby on Rails Dev

### ISSUE THREAD

**Issue by rafaqat** [awesome-jobs/vietnam#3393]
## Location

* Remote - we offer full remote and after 6 months will pay for re-location flight anywhere in the world

## Salary Expectation

* $2000 / Month

## Requirements
* Ruby
* Spree
* PostgreSQL
* 5+ years Software Engineering experience

## Skills
Ruby on Rails
AWS
API
Github Actions
Hotwire
### Must Have

* Rails dev 5+ years

### You’ll be responsible for

* Building a new e-commerce website

### Contact

Trollman: rafaqat_at_gmail_dot_com (mobile number optional) +447810155802

**Comment by huydx** [comment]
please use company email as contact point
