### ISSUE TITLE
[Sharesource Australia] - [Front-end Engineer (ReactJs/Typescript)] - [Remote] - [FT]

### ISSUE THREAD

**Issue by thaovo1012** [awesome-jobs/vietnam#3399]
## Location

* anywhere in Viet Nam
* Full-time Remote

## Salary Expectation

* Up to $35
[IT-Prospa-FrontendEngineer.pdf](https://github.com/awesome-jobs/vietnam/files/8821897/IT-Prospa-FrontendEngineer.pdf)
00 Gross

## Requirements
* ReactJs
* Typescript
* GraphQL
* At least 2 years Front-end experience

### Must Have

* Working knowledge of Cloud-based deployments, applications, systems and CI/CD pipelines
* Experience with Azure (or equivalent platform) and accompanying ecosystem

### Ideally

* Experience with ReactJs

### You’ll be responsible for

* As a Frontend Engineer, you will be a key member of the Frontend Engineering team. You will be translating designs and wire-frames into high-quality code. You have an eye for detail and are passionate to deliver value fast. You live and breathe TypeScript and are an effective member of any engineering team, willing to voice your opinion and share your knowledge.

### You can bring

* Work closely with designers, product teams and your fellow engineers to create, extend and enhance responsive, accessible and beautiful web applications.
* Work with the team to build software features that are readable, reliable, reusable and maintainable.
* Use your technical experience and knowledge to solve both business and technology problems.
* Be a driver of quality, surfacing data and metrics to guide development, quality and availability.

### Why it would be awesome to work with us 
* Hybrid working model
* Social Insurance based on full gross salary
* 13th-month salary
* 15 days annual leaves
    
### Interesting Engineering Projects:

* You will work & report directly to our Australian clients
* This project is about an online lender, supporting finance to small businesses. Their technologies are .Net & ReactJs.

### Contact
Skype: thao.vo_14
Telegram/Zalo: +84 939 236 757
Mail: thao.vo@sharesource.com.au

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
