### ISSUE TITLE
Ruby On Rails Developer - Attractive Salary $700 ~ $1500

### ISSUE THREAD

**Issue by HRVeNtura** [awesome-jobs/vietnam#340]
## Location

* Saigon, Vietnam
* 4F-A1 Mirae Business Center, 268 To Hien Thanh, 
Ward 15, District 10, HCMC

## Salary Expectation

* $700 ~ $1500

## Requirements

* Programming experience with Ruby
* Experience with Ruby on Rails frameworks (provide intensive Ruby on Rails training course for skill-up)
* Experience with Database system (MySQL/MongoDB)
* Experience with Linux (Ubuntu, CentOS)

## Education

* Graduated from College/University in Information Technology/Computer
* At least 2 year experience as a Web developer (1 year as a Ruby on Rails developer)

### Must Have - TECHNICAL EXPERIENCES

* Programming experience with Ruby
* Experience with Ruby on Rails frameworks (provide intensive Ruby on Rails training course for skill-up)
* Experience with Database system (MySQL/MongoDB)
* Experience with Linux (Ubuntu, CentOS)

### Ideally

* Experience with Redis, Index Engines (Apache Solr, Elastic Search)
* Server Deployment (Capistrano, Mina, Chef)
* Can basically communicate (writing, speaking) in English

#### BE RECOGNIZED - Well Training and Developing Environment

* Provide Intensive Ruby/Ruby on Rails training course for skill-up
* Skillful technical mentors are always there to help
*  Occationally have training in Japan and more opportunities working at ZIGExN in Japan
* Regularly receive feedbacks from Leader/Manager
* "3-months" Performance Evaluation for Income and Career Development

#### POSITIVE Team with lots of FUN & CHILLs

* Providing Free Snacks (Kitkat, Choco Pie...), Fresh Milk, Coffee, Tea, Yogurt, Red Bulls..
* Happy Events: Birthday, Pizza Party, X-mas, Halloween and Full Moon Festival...
* Sports activities: Football, Table Tennis, Swimming Clubs and Badminton...
* Company Events:Quarterly Event, Year End Party, Yearly Company Trip and Other Occationally Events/BBQ...

#### We care about your HEALTH 

* Bao Viet Premium Health-care packages 
* 24-hrs accident insurance
* Annual Health-care checkup

(JapanWorks)
japanesebeginner, VisitJapan, 160914, 160915, 160916

### Contact

Ms. Duyen. Email: g-hr@zigexn.vn. Please note **Github** on your email subject.

**Comment by joneslee85** [comment]
Thx for posting with us. Please make amend the title as it does not comply with our guideline.

**Comment by joneslee85** [comment]
Closed because there is no amendmend within 2 days
