### ISSUE TITLE
Littlelives - Lead Mobile Engineer - Onsite (HCM) - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#3401]
LittleLives is the leading EdTech platform used by a thousand preschools globally. We are looking for a Lead Mobile Developer to spearhead the mobile team. LittleLives is a leading education technology company used in over a thousand preschools in 10 countries, and we are looking to expand our mobile team!

## Location

- Ho Chi Minh
- Onsite

## Salary Expectation

- **2000 - 3000 USD per month**

### What you will be doing: 

- Lead and collaborate with a diverse multinational team of mobile developers
- Establish best development practices and processes 
- Review code implementations of team members
- Keep up to date on the latest industry trends in mobile technologies
- Be a vital voice in sprint planning and daily stand up meetings
- Play a lead role either in terms of technical development and architecture, or in terms of team management
- Mentor and nurture engineers

### What's in it for you

- Develop a wide experience in technologies, earning you respect in problem solving and leadership 
- Grow your team’s skills and pass down the knowledge to your team
- A chance to make a difference to the lives of thousands of preschool educators, parents and children all over the world

### Must Have

- Good knowledge about iOS SDK
- Good understanding of software engineering principles and techniques
- Strong knowledge of object-oriented programming.
- Good understanding of the full mobile development life cycle, structural and popular design pattern such as MVC, MVV .
- Excellent programming skills in Swift, Familiar with Git and GitflowFamiliarity with RESTful APIs (GraphQL is a plus)
- Familiarity with CocoaPods and well-known open source libraries
- Attention to detail and a keen eye for good UI/UXExperience in leadership positions
- Highly motivated and adaptable 
- Fluent in English 

### Ideally

- Basic knowledge of Functional Programming
- Experience with Android mobile app development using Java/Kotlin
- Familiarity using Firebase platform

### Why it would be awesome to work with us

- We WILL push you to learn new things together
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Personalized leadership growth based on your strengths
- 14 days annual paid leave
- Competitive salary
- Macbook Pro and additional screens
- Premium healthcare
- Yearly Bonus base on company performance

### Contact
Homepage:  https://www.littlelives.com
[Click Here To Apply](https://littlelives-talent.freshteam.com/jobs/G7ByMFpDgVCL/mobile-team-lead)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
