### ISSUE TITLE
Littlelives - Frontend Engineer (VueJS/ReactJs) - Onsite (HCM/HN) - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#3403]
LittleLives is a fast-growing technology company with a vision to revolutionise the education industry. As part of our frontend development team, you're charged with ensuring the LittleLives experience delights all our users. You will work with other developers and designers to deliver new and innovative products to market, from prototyping features to production-ready products. You will be tasked with taking wireframes or designs and turning them into fully functional, user-friendly, efficient, and delightful interfaces.

## Location

- Ho Chi Minh | Ha Noi 
- Onsite

## Salary Expectation

- **1200 - 1600 USD per month**

### What you will be doing: 

- Coding! Design and develop software with a high standard of code quality, stability, maintainability, readability, and performance.
- Collaborate with a team of designers to create efficient, responsive, delightful user interfaces.
- Collaborate with a team of programmers to advise the best software packages, hardware platforms, and techniques for implementing features, systems and tools.
- Advise the development team on the scope and resources required for new product ideas, new features and improvements to our existing product catalogue.
- Adhere to and refine our processes so that we are constantly exceeding development and release standards.
- Research and develop ingenious ways of solving unique UI/UX problems, and taking our products to the next level.
- Ensure the technical feasibility of increasingly progressive UI/UX designs.

### Must Have

- Expertise in Vue.js or React, ES6 and GraphQL.
- Sound coding practices such as git, unit testing, CI/CD, organised component library.
- Strong sense of user empathy and ownership over the products you've created.
- Sensitivity to website design, and an eye for aesthetics.
- Experience with solving complex problems and delivering significant impact as an individual contributor. 

### Ideally

- Built your own frontend boilerplate or component library.
- Worked with typed languages, Typescript, Flow.
- Good grasp of technical requirements in Start-ups and internet companies.
- An active and data-driven approach to problem-solving; you enjoy making sense of the trends and using the insights to better your process to make it more efficient.

### Why it would be awesome to work with us

- We WILL push you to learn new things together
- Multinational team, work with them in our global offices
- Experience all-around growth with exposure to various aspects of business
- Personalized leadership growth based on your strengths
- 14 days annual paid leave
- Competitive salary
- Macbook Pro and additional screens
- Premium healthcare
- Yearly Bonus base on company performance

### Contact
Homepage:  https://www.littlelives.com
[Click Here To Apply](https://littlelives-talent.freshteam.com/jobs/0eT7DbQkrJJ7/front-end-developer)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
