### ISSUE TITLE
FREELANCER JOB - PRODUCT MANAGER BLOCKCHAIN

### ISSUE THREAD

**Issue by phuongthuan158** [awesome-jobs/vietnam#3405]
## Địa điểm

* Việt Nam
* Freelancer

## Mức lương

* thương lượng

## Yêu Cầu
* Có tối thiểu 2 năm làm việc với vai trò product manager trong lĩnh vực blockchain 
* Có khả năng định hướng sản phẩm, phát triển các sản phẩm dựa trên các giải pháp Blockchain
* Nắm vững về quy trình phát triển sản phẩm Blockchain, hiểu biết về hoạt động của 1 sản phẩm blockchain
* Hiểu biết về Blockchain standards
* Hiểu biết về ngành, nắm được xu thế thị trường 

### Mô tả công việc

* Thời gian làm việc: Khoảng 20h/tuần
* Hỗ trợ tư vấn, định hướng cho sản phẩm của các khách hàng blockchain của VMO 
* Hỗ trợ tư vấn cho VMO cách thức tiếp cận với các bài toán của khách hàng cần phát triển phần mềm blockchain

### Liên hệ
Mail: thuanptp@vmogroup.com
Skype: Phương Thuận

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
