### ISSUE TITLE
Data Platform Startup - Lead/Senior Backend Engineer - Hybrid - Freelance FT

### ISSUE THREAD

**Issue by pmq1996** [awesome-jobs/vietnam#3407]
## About us
Better data, better performant models, faster deployment. Our goal is to create a robust data training platform that helps accelerate artificial intelligence development. We want you to be our partner in making this actually happen.

## Project description
You are projected to work in a team to build ML applications to automate the processing of documentation to reduce errors and time.
You are expected to develop technical aspects of the team’s strategy to ensure alignment with its business goals.

## Location

* Saigon, Vietnam

## Salary Expectation

* We're a startup with our own money, the salary is up to negotiation

## Our team mission:
Artificial intelligence is currently and already having a huge impact across the economy, with the projection of 30% of the amount of jobs that will be automated by the mid-2030s. We believe that the transition from traditional applications to softwares powered by AI is and will be the crucial shift of our time and our mission is to accelerate the process in every industry. Join us if you are willing to be part of a small, passionate team. 

## Requirements

- At least 5 years of professional experience as a Fullstack Engineer developing high-graded web applications (NodeJS, Python)
- Solid experience and knowledge in the software development process and building scalable data pipelines (ETL, Apache, Spark, Kafka, Hadoop)
- Experience with cloud (AWS, GCP or Azure) and containerization technologies (Docker, Kubernetes)  
- Well-versed in DevOps practices and can apply them in the software development lifecycle (Jenkins, CI/CD, GitHub Actions, GitLab CI, Azure DevOps etc) 
- Professional experience working in an agile development environment and ideally have Scrum certification (e.g. Scrum Developer, Scrum Master) 
- You can contribute to technical decisions based on your expertise and client requirements 
- Bachelor’s degree in Computer Science or an equivalent related field
- Strong communication in English would be a HUGE Plus
- Strong interest in working in a risky yet fast-growing startup environment

### Responsibilities

- Set up, design and implement the base of our Data platform with a well-defined development process.
- Coach junior Software Engineers: Lead the engineers in their day-to-day activities and professional development. 
- Listen, advise and transform our ideas into brilliant technical solutions, approaches and designs through code implementation
- Identify and investigate complex platform issues then present solutions
- Develop a regular cadence of communication and feedback within your team and with other teams and organizational functions in order to ensure organizational success
- Engage frequently with clients and assist with technical scoping
- Contribute to technical training and development courses for both your team and the organization

### Apply here: 
people.dataplatform@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
