### ISSUE TITLE
CXP - Devops -  Up to 4,000$ - HCM - Full-time

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3412]
## Location
* Botanica Premier Apartment, Block A2, 102 Hồng Hà, Tân Bình District, HCMC, Vietnam
* Hybrid (work at office 3 days/week)

## Salary Expectation
*  up to 4,000$/month

## Requirements
* Develop company-wide standards for development processes, system design and implementation methodologies
* Understanding and applying the software architecture and application security
* Troubleshoot and plan countermeasures of performance, security and reliability issues
* Ability to work/coordinate with developers/architects.

## Skills
* Broad knowledge of different programming languages and strong expertise in at least one of Go, Java, JavaScript
* Hands-on experience of architecting and developing secured, high performance, high availability, scalable software systems
* Very strong problem solving with deep system know-how across all layers
* Experience with application performance monitoring and error tracking systems
* Strong IT Networking knowledge and Ability to Write Scripts using Python/Shell script
* Familiarity with CI/CD, Docker, Kubernetes

### Must Have
* Experience of defining and rolling out company-wide technical standards
* Experience defining and driving SecDevOps and best practices within large teams
* Experience in Performing technical assessment including Vulnerability Assessment and Pentesting
* Interested in dealing with technical challenges and keen on exploring new things

###  Nice to Have
* Knowledge or experiences with blockchain applications and systems
* Knowledge or experiences with banking, financial or fin-tech systems

### Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* 13th salary bonus

### Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

### About Us
CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
* Email: [hr@cxptek.com](mailto:hr@cxptek.com)
* Phone: (+84) 77 299 7820 (Jade)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
