### ISSUE TITLE
Sun* Vietnam - Ruby on Rails Developer - HN/DN/HCM - Hybrid - Offer $2200

### ISSUE THREAD

**Issue by ghost** [awesome-jobs/vietnam#3413]
# LOCATION

* HN, DN, HCM
* Hybrid

## SALARY EXPECTATION

* Range lương: $700-2200 (with ~14 months salary package)

# WHO WE ARE

* Được thành lập tại Việt Nam từ tháng 10/2012, cùng với sự nỗ lực không ngừng, hiện tại Sun* đang sở hữu một trong những đội ngũ Ruby engineer chất lượng và hùng hậu nhất tại Việt Nam. Chúng tôi là những thành viên có niềm đam mê với Ruby và có khả năng phát triển các ứng dụng web có sự tương tác dày đặc giữa server và người dùng bằng framework này.

## WHAT WE DO

* Tham gia phân tích requirement, thiết kế hệ thống
* Tham gia vào phát triển các sản phẩm công ty hoặc các dự án outsource với thị trường Nhật Bản
* Nghiên cứu và áp dụng các công nghệ mới để nâng cao chất lượng các dự án hiện có
* Tham gia vào các diễn đàn/ tech show về công nghệ của công ty

# WHO YOU ARE

## Junior/Middle:

* Có ít nhất 1 năm kinh nghiệm làm việc với Ruby
* Có kiến thức về lập trình OOP Ruby on Rails, Web Development, DBMS, ORM (làm nhiều những nội dung liên quan đến database performance, RESTful, SPA là một lợi thế)
* Nắm vững và có kinh nghiệm làm việc với một số Gem cơ bản: Devise, Pundit, Kaminari v.v..
* Có khả năng Unit Test, có tư duy DRY – Thao tác tốt với HTML, CSS, JavaScript (Jquery, AngularJS, Ajax, …), Bootstrap, JSON, XML,
* Làm việc thành thạo với các tool quản lý version và management (Git, SVN, Redmine, Jira)
* Có hiểu biết về Docker, AWS, CI/CD, deployment

## Senior:

* Có kinh nghiệm làm các dự án Ruby trên 4 năm
* Nắm vững Ruby on Rails, có kinh nghiệm làm việc và xử lý các hệ thống lớn
* Có kinh nghiệm với OOP, MVC Framework, ORM, RESTful API, Design Patterns
* Hiểu biết về TDD, Testing và có thể implements các requirement theo TDD, có tư duy DRY
* Thao tác tốt với một trong các Database: MySQL, PostgreSQL, Oracle, …, có kinh nghiệm làm việc với Big Data là một lợi thế
* Có kinh nghiệm làm việc với Cloud, Microservices
* Thành thạo AWS, Docker Có kiến thức về Infrastructure, Deployment, CI/CD
* Thành thạo các công cụ quản lý mã nguồn: GIT, SVN, và dự án Redmine, Jira.
* Thao tác tốt với HTML, CSS, JavaScript (Jquery, AngularJS, Ajax, …), Bootstrap, JSON, XML, …

# BENEFITS AND PERKS

Môi trường chuyên nghiệp, cởi mở, đề cao sự sáng tạo:
* Làm việc cùng những đồng nghiệp có lý tưởng thay đổi xã hội.
* Coi trọng những góc nhìn khác biệt trong tập thể
* Văn hóa học tập mạnh mẽ và thúc đẩy phát triển
* Văn hoá chấp nhận rủi ro để trải nghiệm và phát triển

Tập trung hỗ trợ sự phát triển cá nhân:
* Được tư vấn, đồng hành và hỗ trợ phát triển sự nghiệp cùng với hệ thống career path (phát triển theo hướng chuyên gia hoặc hướng quản lý) đã được nghiên cứu, thử nghiệm trong nhiều năm
* Được định hướng mục tiêu cá nhân, nhóm và tổ chức
* Trao quyền làm chủ
* Hỗ trợ xác định mục tiêu 3 tháng-6 tháng (Goal Define Support)
* Được truy cập thư viện tài liệu online Learning Hub với nhiều khóa học đa dạng được cung cấp bởi Udemy, Linkedln,…

Quan tâm đặc biệt tới nhân viên:
* Lương: $700-2200 (Gross) cùng các khoản trợ cấp, phụ cấp khác (ăn trưa, đi lại, phái đẹp, tiếng Nhật, chứng chỉ IT,..v.v…)
* Lương tháng 13 & thưởng performance
* Performance review: 2 lần/năm
* Bảo hiểm sức khoẻ toàn diện Sun* Care
* Chế độ thâm niên
* Chế độ chăm sóc phụ nữ: Nghỉ sinh lý phụ nữ: 2,5h/ tháng; nghỉ sau sinh cho nhân viên nữ có con dưới 1 tuổi: 1h/ngày
* Chính sách hỗ trợ các hoạt động học tập, trao đổi, chia sẻ kiến thức, giao lưu văn hoá (Seminar công nghệ – Tech Expert, CLB: đọc sách, tiếng Nhật, CLB âm nhạc,…)
* Du lịch thường niên, hoạt động team building hàng quý.
### Contact
Linkedin: https://www.linkedin.com/in/ttngoclam/
Skype: ngoclam119
Facebook: fb.com/cung123
Gmail: tran.thi.ngoc.lam@sun-asterisk.com

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
