### ISSUE TITLE
CXP - BA - Up to 1,500$ - HCM - Full-time

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3414]
## Location
* Botanica Premier Apartment, Block A2, 102 Hồng Hà, Tân Bình District, HCMC, Vietnam
* Fulltime

## Description
*Business Analyst* is responsible for ensuring business requirements are fully understood and specified in a manner that will enable full understanding from development team. Business Analyst is reporting directly to the project manager, product owner and has authority on all the matters related to workflow of product.

## Salary Expectation
*  up to 1,500$/month

## Requirements
* Create User Stories and wireframe 
* Work with QC to verify that all requirements of the system are fulfilled by the implementation in the traceability manner among requirements, CR and implementation
* Support UAT in testing, verifying bugs/issues.

## Skills
* Obtaining IT knowledge-base
* At least 2 years of working experience of which 1 year in analyzing requirements
* Basic knowledge on database such as database schema and simple SQL query
* Knowledge of testing approaches and techniques

###  Nice to Have
* Knowledge or experiences with blockchain applications, banking, financial or fin-tech systems

### Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* 13th salary bonus

### Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

### About Us
CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
* Email: [hr@cxptek.com](mailto:hr@cxptek.com)
* Phone: (+84) 77 299 7820 (Jade)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
