### ISSUE TITLE
[Chợ Tốt] Quality Control Engineer (auto)

### ISSUE THREAD

**Issue by anhhoang2002** [awesome-jobs/vietnam#3415]
We are looking for Quality Control Engineer, who will focus on building automatic test frameworks as well as design and maintain test scripts to support our continuous integration and deployment process.

**Responsibilities:**

- Take ownership and responsibility for the design and development of all aspects of automated testing along with creation, execution and maintenance of automated scripts.
- To work with multiple languages such as Java, JavaScript to turn manual tests into auto test scripts, which maintain control regression bugs.
- To work closely with Product and Tech teams to understand all system architectures and business use cases, in order to be able to design comprehensive test cases and test plan, define and establish automation strategy and process.
- To work with Agile developer and system engineer teams and be responsible for the stability and robustness quality of live software in productions system.

**Requirements:**

- Degree in computer science or similar
- 2 year experience working as Quality control developer, or related position with equivalent experience
- Teamwork spirit, problem solving
- Ability to work independently with task requires high attention
- An expert in scripting and have worked with at least one or more programming language from Java, JavaScript, C/C++, Python, Ruby
- Experienced with at least one of open source tools, for e.g Selenium, Cucumber, TestNG, Appium, JMeter

**Plus points:**

- Experienced with web application testing, web services testing, performance and load testing
- Experienced building and maintaining test automation frameworks
- Experienced with Docker and micro services architecture
- Experienced integrating test suites into CI/CD tools like Gitlab, Jenkins

**What’s in it for you?**

- Join plenty of Sharing and Learning activities as part of our initiatives to contribute to the tech community in Vietnam
- Get 15 days of annual leave and 5 days of sick leave per year
- Health insurance for employee and their family members
- Get a Macbook Pro as your workstation
- Get 13th month salary and annual performance bonus
- Participate in regular team building activities and company parties
- Get opportunities to attend training courses abroad
- Most importantly, the code you write will be impacting the lives of millions!

*Be our family right here: https://careers.chotot.com/ or feel free to contact me for more information
Skype: tremlobisi94| Mail: [anhhoang@chotot.vn](mailto:anhhoang@chotot.vn)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
