### ISSUE TITLE
VietMoney - Data Engineer Fresher - HCM - Fulltime 

### ISSUE THREAD

**Issue by TinDang97** [awesome-jobs/vietnam#3416]
## Location

* Saigon, Vietnam

## Salary Expectation

* We offer a salary at your expectation

### Who we are
* In the context of many difficulties in accessing bank credit capital in Vietnam, traditional pawn services or outside social lending activities contain many risks and inconveniences in transactions. VietMoney was born with the mission of providing convenient, friendly, and secure financial solutions to customers in a completely new way of transaction. 
* Now, getting credit in cash has never been easier when you just need an internet connection to register with us, cash will be served at your home in just 30 minutes.

### What you will bring

* Should have knowledge of SDLC (Software Development Lifecycle)
* Should have knowledge of ETL/ELT (Extract, Transform, Load)
* Should have knowledge of Python and data platform tools
* Willing to Research, Learn, Suggest, and Implement new tools/technologies.
* Drive a solution mindset, work with the team, and make value.
* Display your readiness to change and work on new technologies.
* Apply knowledge of industry trends in software development best practices, accessibility standards, and developments.
* Candidate must be self-motivated and work independently with limited supervision.
* Gather, Transform, Validate, Aggregate, and Report on historical and market data
* Excellent communication and interpersonal skills

### You’ll be responsible for

* Building a new Facebook

### You can bring

* How to analyze data to apply in-house developed systematically, complex analysis techniques to test the data quality and create benchmark solutions
* How to analyze large amounts of trended industry data, identify red flags, and perform root cause analysis
* How to solve data problems and improve the in-house technology suite for validating and reporting on new data
* How to meet all operational SLAs to deliver high-quality data in a timely and consistent manner Develop data-driven exploratory analysis to solve defined problems

Directly apply here: [https://tuyendung.vietmoney.vn/job/data-engineer-fresher-2227](https://tuyendung.vietmoney.vn/job/data-engineer-fresher-2227) or feel free to contact me for more information.

### Contact
Email: tindht@vietmoney.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
