### ISSUE TITLE
Picket Homes - Backend/Scaling Developer (Senior/Mid) - Remote/Hanoi - FT

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3419]
Picket are seeking an exceptional senior developer who can build and scale **high-use data-heavy** backend services. The team’s primary focus is on building a real estate platform using Kotlin, but we also create and extend services in Node and Python. This engineer will work with our Expansion team, Product team, and others to launch new market locations, grow our solutions in existing markets, find and process new data sources at high velocity, and feed our entire real estate ecosystem.

We are always open to any candidates as long as we believe that Picket is able to provide an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $2,500/month
* Stock options 

### Minimum qualifications
* 3+ years of experience in software development and/or in building scalable, high availability data processing pipelines
* Solid knowledge of SQL databases, such PostgreSQL
* Self-motivated, organized, customer-obsessed, with a high level of integrity and ethics
* Sufficient English communication skills (both verbal and written)

### Preferred qualifications
* Thorough understanding of SW lifecycle including best practices in testing and deployment 
* Experience with infrastructure, tools, and cloud (Git, AWS, Linux, Redis, Nginx, etc.)
* Experience in asynchronous event processing in microservice world (PubSub, Apache Kafka) or similar technologies
* Proficiency and mastery of at least one strongly-typed languages ,such C#, Java or Kotlin

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/51b971ac-98f8-49d7-b1c4-3fce8d1f64ca
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
