### ISSUE TITLE
Picket Homes - Full-stack Engineer (Senior/Mid) - Remote/Hanoi - FT

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3420]
Picket are seeking a senior software developer who has passion and ability to build **full-stack** customer-facing products at a fast pace. We have employed several technologies, but the product engineer would likely be working with **ReactJS on the frontend and NodeJS on the backend**. You will work closely with product leaders, Fortune-500 clients, real estate professionals, and teammates to build, deploy, and iterate on amazing products on a frequent launch cadence.

We are always open to any candidates as long as we believe that Picket would be able to provide you with an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $2,500/month
* Stock options 
_See more in the Benefits section below_

### Skills and Experience 
* Senior full-stack TypeScript(ReactJS + NodeJS) software developer
* 3+ years of experience building, supporting, and scaling distributed REST APIs  
* Proficiency in PostgreSQL, Redis
* Thorough understanding of CI lifecycle including best practices in QA and deployment
* Experience with microservices architecture
* Understanding of CI/CD, Git 
* Basic experience with AWS, GCP, or similar cloud and infrastructural services
* Understanding of SW lifecycle including best practices in testing and deployment 
* Technical writing ability, including visual diagramming tools
* Ability to understand business requirements and translate them into technical requirements
* Self-motivated, organized, customer-obsessed, with a high level of integrity and ethics
* Sufficient English communication skills (both verbal and written) 

### Nice to have
* Some exposure to UI/UX design, research, workflows, and tools are a plus but not required
* Experience with MongoDb or other document DB

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/172ffa55-1643-434f-912e-74bdaca04976
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
