### ISSUE TITLE
Picket Homes - Technical Lead - Remote/Hanoi - FT 

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3421]
We’re seeking an exceptional startup tech leader with solid engineering fundamentals and amazing leadership skills to 1) build our systems that will acquire and manage more than one hundred thousand single-family homes and 2) support us to grow the talented team we have in Vietnam. The ideal candidate will have strong ownership, excellent communication skills and enjoy working in highly collaborative and fast paced environments. 
 
Picket will provide an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 
 
_This role reports directly to the Technical Director in the US._ 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $4,000/month
* Stock options 
_See more in the Benefits section below_

### Skills and Experience 
* Bachelor's degree in Computer Science with 5+ years of professional experience in enterprise applications, preferably in Spring framework and Web services, UI frameworks (AngularJS, ReactJS, etc.)
* Versatile technology background with depth in at least two core Picket technologies, and breadth across the modern spectrum. 
* We are currently using React, NodeJS, Flutter, Kotlin, Python and microservice architecture, and thus knowledge and expertise in some of these areas are desirable.
* Have knowledge of the software development life cycle, SCM tools and CI/CD pipeline
* Sound project management fundamentals in broad contexts, with extreme attention to detail and outstanding communication in verbal, written, and video formats
* Excellent diagnostic and troubleshooting skills
* Excellent leadership and organizational abilities
* Experience of working within a tech startup and hyper-growth environment is preferred, but the desire to do so is necessary
* Comfortable with fast-paced operations and not afraid to "roll up your sleeves" to get things done
* High energy, curious and motivated team player who learns, coaches, and mentors others
* Excellent English written and verbal communication skills

### Nice to have
* Helpful, not required: experience owning/launching consumer-facing tech products; background or passion in real estate.

## BUSINESS EXPECTATION
**In month one**
* Complete founder immersion sessions, learning and deeply understanding Picket’s near, medium, and long run vision and operational plans.
* Build a roughly prioritized calendar of tech features and manual processes to support growth plans.

**Within first three months**
* Manage a large and growing team of engineers yet also be able to build hands-on tech if necessary.
* Be able to juggle multiple workflows and projects across the organization.
* Identify and develop high-bar talent across different tech roles (developers, data, PMs, other leaders).
* Make 5+ hires into Tech teams and deliver working prototypes for skeletal PM functions.

**By the end of your first year, deliver**
* Fully functioning technology at above-average service levels (relative to traditional systems and companies).
* An overall team of 20+ engineers in high-product-bandwidth smaller teams.
* Automate heavy manual touch points to improve consumer and owner experiences with a combination of visibility, efficiency, and cost management.

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/381e2e52-5ee3-44ac-aa62-3484fa61f002
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
