### ISSUE TITLE
Picket Homes - Backend Developer (Mid/Senior) - Remote/Hanoi - FT

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3422]
Picket is looking for a talented and experienced backend engineer that will work closely with executives, real estate professionals, and engineers. An ideal candidate will pragmatically and relentlessly ideate, prioritize, manage, and refine our technology based on product offerings.

We are always open to any candidates as long as we believe that Picket would be able to provide you with an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $2,500/month
* Stock options 
_See more in the Benefits section below_

### Minimum qualifications
* Demonstrated proficiency and knowledge of backend development and general practices
  _While most of our services use NodeJS (with some Kotlin and Python), mastery of NodeJS/Kotlin/Python is preferable but not required as long as you have the ability to learn other programming languages as needed_
* 3+ years of relevant experience in building backend applications and services.
* Knowledge of source version control and familiarity with at least one VCS such as Github or Gitlab
* Self-motivated, organized, customer-obsessed, with a high level of integrity and ethics
* Sufficient English communication skills (both verbal and written)

### Preferred qualifications
* Higher degree or equivalent practical experience in Engineering, Computer Science or Software Development
* Experience with SQL databases such as PostgreSQL
* Experience with microservices architecture, distributed system, scaling applications, or full stack development
* Ability to learn new programming languages and practices as required
* Demonstrated ability to share knowledge, review code, translate business requirements to technical requirements, and take ownership of your work

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/cd7d1309-e7eb-4c0d-93f1-9cf5e417c3ba
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
