### ISSUE TITLE
Tuyển dụng .NET - Thị trường Âu Mĩ (Middle/ Senior)

### ISSUE THREAD

**Issue by dieuhienhr** [awesome-jobs/vietnam#3423]
## Requirements
- Bachelor Degree in Computer Science or Software Engineering.
- Experience in eCommerce field.
- Experience in Microservice Architect.
- Familiar with AWS services & technologies:
  Elastic Beanstalk
  RDS
  CloudFront
  Web Application Firewall
  S3
  EC2
  Route 53
- Experience (3+ years) in .NET framework or .NET Core framework for Web Application Development
- Good at English.
- Self-Management.
- Programming Languages: C# (.NET or .NET Core), Javascript, HTML, CSS
- Deep Understanding in Object Oriented Programming.
- Eager to learn new technologies.

### Why it would be awesome to work with us
- Signing bonus
- Opportunity for onsite in Singapore
- 100% probation salary
- Good offer
- Full benefits

### Contact: 
📩 hienptd2@rikkeisoft.com
💖 Skype live:.cid.cdbb9a30cbd0dd1e
🏛 RikkeiSoft Da Nang Branch
🏛 Address: 81 Quang Trung, Hai Chau, Da Nang

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
