### ISSUE TITLE
[SG] Senior PHP Laravel - Open với UV Việt Nam muốn qua Sing

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3425]
## Location

* Singapore

## Salary Expectation

* $5000 - $8000

## Requirements
- Bachelor’s degree, preferably in Computer Science or related field
- 7+ years experience in software development, with a focus on backend web development
- Mastery of PHP, Laravel, MySQL, and frameworks like Vue or React
- Strong knowledge of API design and RESTful
- Equipped with DevOps skills to deploy on AWS and ensure site reliability
- Experience with page speed optimisation and further-reaching technical concepts (API design, dependency injection, test automation, modular structures, functional and object-oriented programming, design patterns, etc.)
- Excellent written and verbal communication skills
- Can work independently and collaboratively in a remote working environment

Preferred skills and experiences
- Talents are based in Singapore or SEA

### Responsibilities

About the job
Create impact in a high-growth fintech startup!

HitPay is a one-stop payment platform for SMEs, on a mission to empower businesses with easy access to digital payments. From no-code e-commerce plugins to affordable credit card readers, we help thousands of merchants bring their business dreams to life.

HitPay is backed by Tiger Global, Global Founders Capital, HOF Capital, and Y Combinator. We're expanding rapidly across the globe and are looking for a talented Senior Backend Software Engineer to join us.

About the role
As a Senior Backend Software Engineer, you’ll build best-in-class digital payment and business tools unlike anything else on the market. Together with our team of top-notch engineers, you’ll create financial products that help thousands of merchants grow their businesses.

Currently, our product offering is unlike anything else on the market — with unique features including one-day setup and no-code installation. We're constantly developing exciting new features, and we'd love your help.

This is a full-time role with amazing growth potential. If you're responsible and self-motivated with strong technical skills, we'd love to hear from you!

What you'll do:
- Build best-in-class features with fully functional integration on the HitPay platform
- Develop Vue and Angular applications with different state-management paradigms
- Design new business and financial tools based on customer feedback and product strategy
- Troubleshoot and find creative solutions to reported problems and issues
- Improve platform interface to improve the user experience for merchants
- Review codes and conduct testing

### Why it would be awesome to work with us

HitPay is a one-stop payment platform for SMEs, on a mission to empower businesses with easy access to digital payments. From no-code e-commerce plugins to affordable credit card readers, we help thousands of merchants bring their business dreams to life.

HitPay is backed by  Global Founders Capital, HOF Capital, and Y Combinator. We're expanding rapidly across the globe and are looking for a talented **Support Engineer** to join us.

- Highly motivated, smart, and supportive team
- Flexible, remote working (you can apply from anywhere in the world)
- Clearly defined roles and targets
- Career progression path
- Learning opportunities and growth
- Stock options
- Co-working space credits
- Local GP medical reimbursement
- 21 days annual paid leave
- Unlimited medical leave

Report to
CTO

Interview process
Round 1 : Coding Test, Round 2 : Interview with CTO, Round 3: Technical Interview
------------------------------------
Noted: 
- For talents outside of Singapore:
 + Employment Pass provided
 + Relocation cost which covers flight and 1 month initial stay
 + Prefer candidates can onboard asap

### Contact
Skype: Huehuenoivu
Zalo/Tele: 0886005769

**Comment by qcam** [comment]
Unfortunately we only accept posts from in-house recruiters currently.
