### ISSUE TITLE
Automation QA Engineer - Fulltime - Onsite (HCMC)

### ISSUE THREAD

**Issue by CamThiNg** [awesome-jobs/vietnam#3427]
## Location

* District 1, Hochiminh City, Vietnam
* On-site

## Salary 

* $2,500/month

## Requirements

* Experience at least 3 years as QA Engineer with demonstrated Automation testing skills, such as Cypress, Cucumber. 
* Knowledge of testing methodologies, the test life-cycle, and BDD concept
* Good analysis skills to understand business requirements.
* Having enthusiasm and passion at work.
* Having knowledge of blockchain, identity management (e.g., OAuth, OpenID Connect) is a big plus.

### Key duty

The QA Engineer role plays an important part in our company’s development process. She/ He will be responsible for conducting tests to ensure our products work flawlessly and deliver the best UX to users, taking security aspects into consideration.

### You’ll be responsible for

* Perform automated testing and assessment of our products.
* Demonstrate experience in the QA process.
* Own quality assurance for security and create comprehensive tests: functional testing, integration testing, regression testing and performance testing, etc)
* Collaborate with our development team to continuously deliver software at high quality products.
* Work as an effective team member; share knowledge and information with the team and pursue product quality and security.

### Our benefits

* Competitive compensation and 13th month salary.
* Full SHU Insurance and private health insurance.
* Professional English environment.
* Most valuable player (MVP) allowance every month.
* Birthday allowance and family events’ allowance
* Flexible working hours, WFH applicable on occasion.
* Parking free.
* Working time: 9 AM ~ 6 PM from Monday to Friday.
* Team building activities, Company trip.

### Why it would be awesome to work with us

* Senior team members with rich and diverse backgrounds.
* An international team from America, Japan, Italy, Singapore, Spain, and Vietnam.
* Mission-driven and agile culture.

### Contact
Homepage: (https://www.credify.one/)
Email: hr@credify.one

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
