### ISSUE TITLE
CXP - ReactJS - Up to 2,000$ - HCM - Full-time

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3429]
## Location
* Botanica Premier Apartment, Block A2, 102 Hồng Hà, Tân Bình District, HCMC, Vietnam
* Fulltime

## Salary Expectation
*  up to 2,000$/month

## What To Do
* Design, build and maintain advanced front end applications for advanced user experience;
* Build reusable components/modules for static websites with responsive design;
* Work with API endpoints for dynamic content updating;
* Ensure UI/UX of developed pages and software with near pixel-perfect design;
* Develop and optimize front-end UI to ensure the application is rendered consistently in cross-browser environments;
* Cooperate to connect front end software development with backend team;
* Work together with the Leadership to establish technical strategy, architecture, and roadmap for global expansion and allow for next-generation capabilities;

## Skills
* Experience working as a ReactJS developer for at least 3 years.
* In-depth knowledge of JavaScript, CSS, HTML, and front-end languages.
* Knowledge of REACT tools including ReactJS, Webpack, Enzyme, Redux, and Flux.
* Experience with user interface design.
* Knowledge of performance testing frameworks including Mocha and Jest.
* Experience with browser-based debugging and performance testing software.

###  Nice to Have
* Experience with crypto or Web3 or Defi

### Benefits & Compensations
* Provided high settings laptop and monitors
* Working with explosive technologies
* 13th salary bonus

### Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

### About Us
CXP, Digital Asset Exchange, predominately used for trading cryptocurrencies, is looking for a new developer to join their HCMC-based team.

### Contact
* Email: [hr@cxptek.com](mailto:hr@cxptek.com)
* Phone: (+84) 77 299 7820 (Jade)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
