### ISSUE TITLE
Laberin - Front-end Developer/Internship - Hanoi - FT

### ISSUE THREAD

**Issue by cthai721** [awesome-jobs/vietnam#343]
## Location

Hanoi, Vietnam
## About us

Hello everyone, we are a B2B startup, based in Helsinki, Finland. Our product is an end-to-end platform connecting the customers to their needs. Currently, our company has a good foundation in Europe and especially, in Nordic countries. As part of our expansion plan to the US (Silicon Valley, etc), we are looking for talented Front-end developer or Interns to work with a team in Hanoi.
## Requirements
- HTML/CSS
- JavaScript (ES6)
- Web accessibility & web standards
- AngularJS or ReactJS is a bonus
## Benefits
- Salary negotiable, possibly stock options.
- International, dynamic, friendly working environment.
- Many opportunities for personal and professional growth.
- Working with the trending technologies such as Ruby on Rails, Elixir, React, Docker, etc.
- Social & health insurance, annual leave, working conditions pursuant to Vietnamese labor law.
- Performance review 2 times per year.
- Good chance to work onsite in EU and the US.
## Contact

Please email to hai@laberin.com with your CV and short introduction about yourself.

**Comment by joneslee85** [comment]
* `s/Javascript/JavaScript`
* Title does not comply with our guideline - please move the internship to the `Frontend Developer / Internship`
* The Intro section is pretty vague about what your company is on

**Comment by cthai721** [comment]
Thanks Joneslee85. It's updated now.
