### ISSUE TITLE
VinBigData -Backend Engineer (Python/Go/java)-HN-Fulltime

### ISSUE THREAD

**Issue by thiendi1205** [awesome-jobs/vietnam#3430]
## Location

* Times City, Hai Ba Trung, Ha Noi, Vietnam
* Full time

## Salary Expectation

* Top market salary

## Requirements

* Bachelor’s degree in computer science, engineering, or a related field.
* 1+ years Software Engineering experience with Python or Go or Java (open all level: junior/middle/senior)

### You’ll be responsible for

* Work with development teams and solution architecture to ideate software solutions
* Work with AI scientists to integrate AI solutions into software products.

### Why it would be awesome to work with us
* Top market salary
* Private health insurance cover for VinMec and top hospitals in VN
* The preferences when using the services of the Vingroup’s member companies: such as VinFast, VinPearl, VinMec, VinSchool, etc.
* Training course and certificates
* Team building/company trips
* Opportunities to join a diverse and inclusive team (our team is from Amazon, Google, LinkedIn and many other top companies in Vietnam)
* And many more!

### Contact
Email: v.dungtt59@vinbigdata.com
Skype: live:.cid.dc0491dd290723a2
Zalo/Telegram: 0934 583 094

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
