### ISSUE TITLE
VinBigData-DevOps Engineer-HN-Full time

### ISSUE THREAD

**Issue by thiendi1205** [awesome-jobs/vietnam#3431]
## Location

* Times City, Hai Ba Trung, Ha Noi, Viet Nam
* Full time

## Salary Expectation

* Top market salary

## Requirements
* 3+ years of experience working as a DevOps with strong Linux experience and having responsibilities of Site Reliability Engineering/Devops.
* Experience working with Kubernetes, Docker, and some Cloud Providers: GCP,AWS.
* Solid knowledge of Linux / Unix system & command line interface.
* Knowledge of network & security.
* Fluent in some programming language: Python, Golang.
* Solid understanding of automation principles; experience using tools likeTerraform and Ansible.
* Experience in monitoring systems like Grafana and Prometheus + Thanos.
* Experience with centralized logging solutions like the Elastic Stack.
* Experience with CI/CD tools.
* Experience working in a 24/7/365 service environment.

### You’ll be responsible for

* Scalability: Build, improve and expand our infrastructure so its growth is ensured.
* Reliability: Make sure we have proper monitoring and alerts to detect problems in a proactive way. Troubleshoot and fix root causes of incoming issues to prevent them in the future.
* Performance: Strive towards excellence when it comes to applications and infrastructure performance. Take special care of the production environment to offer the best experience for our players.
* Smooth operation: Set up Devops CI/CD pipelines, improve processes and encourage best practices to speed up development.
* Security: Knowledge of common web vulnerabilities, audit our infrastructure for security issues and keep it safe.

### Why it would be awesome to work with us
* Top market salary.
* Private health insurance cover for VinMec and top hospitals in Vietnam.
* The preferences when using the services of the Vingroup’s member companies.
* Training course and certificates.
* Team building/company trips.
* Opportunities to join a diverse and inclusive team (our team is from Amazon, Google, LinkedIn and many other top companies in Vietnam)
* And many more!

### Contact
Email: v.dungtt59@vinbigdata.com 
Skype: live:.cid.dc0491dd290723a2
Zalo/Telegram: 0934583094

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
