### ISSUE TITLE
VinBigData - Frontend Engineer( Vue JS, ReactJS)

### ISSUE THREAD

**Issue by thiendi1205** [awesome-jobs/vietnam#3432]
## Location

* Times City, Hai Ba Trung, Ha Noi
* Full time

## Salary Expectation

* Top market salary

## Requirements
* 1+ year hand-on experience with VueJS or ReactJS (open all level: junior/middle/senior)
* Capable of integrating Web Application with Backend using RESTAPI, WebSocket, GRPC or GraphQL
* Familiar with authentication and authorization frameworks and techniques (OAuth2, OpenID Connect, JWT)
* Having basic understanding of backend development and deployment is a strong plus
* Willing to develop new skills (Python programming, DevOps)

### Responsibilities
* Working closely with design team and API developers to develop production-standard web and mobile-web applications.
* Build and Optimize web applications for better performance and reliability
* Follow Agile and Devops practices like CI/CD to deliver quality code at speed to market

### Why it would be awesome to work with us
* Top market salary
* Private health insurance cover for VinMec and top hospitals in VN
* The preferences when using the services of the Vingroup’s member companies: such as VinFast, VinMart/VinMart+, VinPearl, VinMec, VinSchool, etc.
* Training course and certificates
* Team building/company trips
* Opportunities to join a diverse and inclusive team (our team is from Amazon, Google, LinkedIn and many other top companies in Vietnam)
* And many more!

### Contact
Email: v.dungtt59@vinbigdata.com 
Zalo/Telegram: 0934583094 
Skype: live:.cid.dc0491dd290723a2

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
