### ISSUE TITLE
[HN] PHP Developer, up to 1000$ (negotiable)

### ISSUE THREAD

**Issue by phucnd** [awesome-jobs/vietnam#344]
**Location**
SotaTek
4th Floor, Alpha building, 54 Luu Huu Phuoc, My Dinh, Nam Tu Liem, Hanoi
http://sotatek.com
recruit@sotatek.com

**Intro**
SotaTek is a global software outsourcing company and mobile game publisher providing innovative solutions for clients around the globe. We are a young, responsible, and professional team based in Hanoi who build full-stack solutions for our customers in multiple platforms with highly scalable back-ends and rich media front-ends. We're also developing our own world class product with US based partners.

**Salary**
- Up to USD 1000, negotiable upon interview.
- Competative salary and good career path. We understand talents deserve fair deals.

**Job Description**
- You will work as a web developer to build a web apps for Korea fintech startup from scratch
- Or maintain and develop new features for a chat bot platform for a Japanse client (who is quite famouse in AI in Japanese startup community recently)
- Work in other project under your direct managers' instructions
- Understand the design documents and implement them properly.
- Opportunities to work onsite oversea (Japanese level above or equivalent to N2)

**Other Benefits**
- Enjoying a nice working view with young and friendly colleagues in a start-up-like environment. Join our company trip, teambuilding and a lot of eating together.
- 13th month salary, social insurance, health insurance, unemployment insurance and other benefits under the provisions of the company.
- 8 hours per day, 5 days per week. Overtime salary is 150%, 200% on weekends.
- Project based bonus, public holidays bonus (2/9, 30/4, 1/5...)
- Working closely with technical gurus who built and operated world-class applications with million of users. This might be a good chance for graduated students to learn cutting-edge technologies and how to build scalable system from scratch.
- Opportunities to recieve % equity in our company products (if you wanna join).

**Requirements**
- Bachelor degree or up majoring in software engineer, computer sience.
- Extensive knowledge about OOP and design patterns.
- Experience with PHP and/or at least one of PHP related frameworks such as Laravel, Yii2...
- Familiar with AngularJS 1
- Worked with HTML/CSS and Javascript before
- Be able to handle tasks individually or in big team size.
- Good at English, especially Japanese is a big bonus.

**Contact**
Send us your CV to recruit@sotatek.com

**Comment by joneslee85** [comment]
Please revise the title format to comply with our guideline.

**Comment by joneslee85** [comment]
No amendment. Closed :-1: post
