### ISSUE TITLE
Findtalent - Senior .Net Developer Fullstack - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by VanyenHR** [awesome-jobs/vietnam#3441]
# Senior .Net Developer Fullstack
## Location

* Ho Chi Minh, Vietnam

## Salary Expectation

* $850 - $1400

## Requirements
* 4-5 years of experience, working with projects using Microsoft technology
* Extensive knowledge of C# and .NET Core 3.0+, OOP, SOLID
* Expertise in: Angular 2+, HTML5, CSS3, JavaScript, Typescript
* Knowledge of SQL Server development and database design
* Experienced in Git and Gitflow
* ASP.NET MVC/Web API, Entity Framework/ Dapper, cloud technology such as Azure, AWS is a plus

## Skills
* Software Development 
* User Analyze

### Must Have

* Be able to work with other functional teams including UX/UI Design, Project Management, and Other Skills software master
* Be able to maintain and test in the codebase repository

### Ideally

* Experience with design and build distributed control systems, internal software,...

### Responsibilities

* Responsible to work in whole-process projects, from analyze, develop to final implementation/ release
* Build customer-oriented products across the entire Software Development lifecycle
* Design and build distributed control systems, including back-end and frontend components
* Build software that is available, scalable and high-performance
* Work with other functional teams including UX/UI Design, Project Management, and Other Skills software master.

### You’ll be responsible for

* Support to build a new internal software that helps to manage everything in the company

### You can bring

* A good eyes for design
* A good analysis skill
* A high passion to code 

### Why it would be awesome to work with us

* Young, dynamic environment 
* Good benefits and treatment

### Contact

Zalo: 0839271908 or yen.chau@findtalents.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
