### ISSUE TITLE
[Fetch Technology] - [Backend Developer] - [Da Nang/Ho Chi Minh/Ha Noi] - FT 

### ISSUE THREAD

**Issue by Minhminh0706** [awesome-jobs/vietnam#3442]
## Location

* Danang, Vietnam
* Hochiminh, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* $600-$1500

## Requirements
* Python 
* Java
* Spring Framework
* 1+ years Backend experience

### Responsibilities
* Develop web-based projects with the use of Python, Nodejs, RDBMS, NoSQL and relevant frameworks
* Designing of API
* Deploy and manage code base to AWS using bitbucket

### Contact
Skype: minhdoan@fetch.tech
LinkedIn: https://www.linkedin.com/in/minh-doan-thi/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
