### ISSUE TITLE
[Da Nang] Salesforce Developer - DataHouse Asia

### ISSUE THREAD

**Issue by araxiele123** [awesome-jobs/vietnam#3443]
## Location

* Danang, Vietnam
* Remote

## Requirements

- Analytical mind and problem-solving attitude 
- Have real experience in Salesforce, Apex 
- Have experience in Lightning, Web Application and Database as a plus. 
- Have experience in other platforms such as Microsoft Dynamic, Lotus Notes, SharePoint or any ERP platforms as a plus. 
- Great if you are familiar with Agile / Scrum, OOA & OOD 
- Good English communication skills (verbal and written) 
- Information Technology or Computer Science degree or a related field

##JD: https://aloha1975.com/careers/salesforce-dev/
##CV send to: career@datahouse.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
