### ISSUE TITLE
[Fetch Technology] - [Front-end Developer ReactJS/Angular] - HCM/HN/DN - Fulltime

### ISSUE THREAD

**Issue by Minhminh0706** [awesome-jobs/vietnam#3444]
## Location

* Da Nang
* Ho Chi Minh
* Ha Noi

## Salary Expectation

* $1000-$1500

## Requirements
* From 1 year experience in ReactJS/Angular
* Be able to communcate in English

### Responsibilities
* Develop high-performance web applications.
* Analysis requirements and maintain technical documentation.
* Contribute ideas & solutions to the products.
* Write clear and maintainable code.
* Participate in all phases of the product development process including analyzing user requirements, designing system architecture, coding, testing and deployment. 
* Great power comes with great responsibilities!

### Benefits
* Being a Front-end Developer at Fetch Technology, you will experience a youthful, flexible and creative work environment: 
* MacBook or high-end laptop for working. 
* Attractive salary and annual salary review. 
* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese.
* Extensive on job training, you will always have a chance to work with new emerging technologies.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.
* PVI Health care.
* 12-day annual leave per year.
* 13th month salary.
* Enjoy diversified activities: Free snack, Weekly and Monthly Team-building, Company trip, Play Game (PlayStation, Board games), Play Sport (Football, Badminton...).

### Contact
Skype: minhdoan@fetch.tech
LinkedIn: https://www.linkedin.com/in/minh-doan-thi/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
