### ISSUE TITLE
Orange Logic VN - Software Engineer - HCMC - FT

### ISSUE THREAD

**Issue by ThaoNguyenOLVN** [awesome-jobs/vietnam#3445]
## Location

* Saigon Trade Center, 37 Ton Duc Thang, District 1, HCMC, Vietnam
* Onsite Mon-Fri (9AM-6PM). We offer flexible working hours.

## Salary Expectation

* Fresher: $1000/month (Gross)
* Junior: Up to $2000/month (Gross)
* Senior: Up to $3000/month (Gross)
* Lunch/Gym/Parking allowance: around $100/month
* Birthday/Wedding/Tet: $100/occasion
* Performance Bonus on a monthly basis
* Full 13th month salary if you had worked at another company before in the same year

## Other Benefits

* 18 days of annual leaves (cashback allowed if not used)
* 4 days of annual company trip abroad
* 100% salary in 2-month probation
* Social insurances based on full gross salary
* Premium healthcare insurance
* Special celebrations or gifts on holidays
* Monthly activities & Happy hours everyday

## Skills

* C#/ Java/ Python
* .NET Framework
* SQL is a plus, but not mandatory
* Practical experience on a web-based application
* English communication (both verbal and written)

## Requirements

* A Bachelor’s Degree in any relevant major (e.g. Information Technology, Computer Science, etc.)
* A strong fundamental understanding of software development
* An understanding of complex algorithms and data structures, as well as a passion for intellectual challenges
* Strong self-discipline for delivering well-tested, complete features/modules under a tight schedule and the capability for rational thinking

## Responsibilities

* Developing scalable new features for our software product that exceeds our customer’s needs
* Building architecture for our platform to ensure optimal performance
* Obtaining requirement feedback from internal teams/clients to maintain/support the product development
* Write the Unit Tests for robust development
* Performing code reviews on other team member’s work
* Taking ownership of projects and having the opportunity to further your knowledge by exploring machine learning, security, DevOps, and more

## Why it would be awesome to work with us
* Very attractive salary package depending on the profile
* Great product chosen by global clients - Daily innovation
* Flat structure, simple process, and transparency

## Contact
Homepage: https://www.orangelogic.com/ 
Email: thao.nguyen@orangelogic.com
Phone: (+84) 948 278 386
Or leave me a message via LinkedIn: https://www.linkedin.com/in/thao-nguyen-7596151ba/
Thank you.

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
