### ISSUE TITLE
Fullstack

### ISSUE THREAD

**Issue by Hao-Luong** [awesome-jobs/vietnam#3446]
## Location

* D1, HCMC, Vietnam

## Salary Expectation

* $3500/month or range

## Requirements
* Proficiency with any back-end programming languages (e.g. .NET, Java, Python, etc)
* A Bachelor’s Degree in any relevant major (e.g. Information Technology, Computer Science, etc.).
* Proficiency with English (both verbal and written)
* Practical experience on a web-based application

### You’ll be responsible for

* Take ownership of projects and have the chance to further you by exploring machine learning, security, DevOps...Develop scalable new features for software product exceeding our customer’s needs
* Build architecture for our platform Obtain feedback from internal teams/clients to maintain/support the product dev
* Write the Unit tests for robust dev
* Perform code reviews on other team member’s work

### Why it would be awesome to work with us
* Lunch, parking, and gym Birthday/wedding allowance: 100$

### Contact
If you're interested in, feel free to inbox me or send your CV via my email: lt-minhhao@pasonatech.vn
Phone: 0901595151, 0386900805 (zalo)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
