### ISSUE TITLE
Saigon Technolgy - Mid/Sr DevOps Engineer - HCM - FT (Hybrid)

### ISSUE THREAD

**Issue by trankien200691** [awesome-jobs/vietnam#3450]
## Location

* Level 02, 02 Nguyen The Loc, Ward 12, Tan Binh District, HCM City
* Hybrid (2 days remote and 3 days at the office)

## Salary Expectation

* up to $3500 gross/month

## Requirements
* Good at English communication
* 2+ years of experience in Azure (preferred) or Aws
* Software Development background is a plus

### Must Have

* **At least 2+ experience years with AWS/Azure cloud platform**.
* Experience with the following languages: Powershell script, Bash script.
* Experience with Relational Databases (MySQL/PostgreSQL/MS SQL) and NoSQL Databases (MongoDB, Cassandra)
* Experience with one of the following tools: Ansible, TeamCity.
* Experience with Docker, Jenkins
* Experience with Kubernetes and have operated production cluster(s) in cloud environments.
* **Experience with the popular AWS services like ECS, ECR, Route53, EC2, EKS, RDS, CloudFront, and WAF.**
* **Experienced in Azure DevOps, VNET, App Service, AKS, and Azure Artifacts.**
* Experience with Logging and Monitoring tools like Zabbix, Grafana, AWS CloudWatch, Prometheus, ...
* Experience with automated infrastructure deployment/management: Terraform, Terragrunt, AWS CloudFormation, Azure Resource Manager (ARM), or similar
* Experience with microservice architectures.
* Good mindset about the security audit.
* **MUST be good at verbal English communication**.

### Ideally

* Experience with one of the programming languages: Python, Java, PHP, C#, ...
* Experience with DevSecOps practitioner is a big plus.
* Experience with the technical consultant/proposals is a big plus.
* Willing to work over the weekend when the production server has issues.
* Experience to migrate on-premise systems into the cloud services.

### Responsibilities

* Support deploy and configure tooling to support continuous integration and continuous delivery pipelines
* Engage in projects as needed, work collaboratively with other team members, communicate effectively, and contribute to team success
* Collaborate in technical discussions both internally and with external customer teams
* Support the future customer-facing teams with root cause analysis and resolution of escalated technical issues

### Competitive Compensation And Benefits
* Attractive salary (13th-month salary, salary review twice/year) and project bonus
* Bonus programs for candidate referral, technical article writing
* Interest-free loan support for personal plans
* Annual Loyalty Award packages: 2 year-Award, 5-year Award, and 10-year Award

### Exciting Activities
* Annual company trip and regular team-building parties
* Party celebration (Christmas, Birthday, Mid-autumn,...)
* Sports clubs (football, badminton, swimming, gym, bi-a snooker, etc)

### Valuable Training
* Sponsor examination fee for professional certificates (AWS, Azure, IELTS, PMP, Scrum Master,...)
* Sponsor fee for joining any technical training sessions and courses.
* Free English courses

### Flexible And Professional Working Environment
* A professional English-speaking working environment with Agile – Scrum model
* Flexible working time and WFH support.

### Health Care Benefits
* Allowance for sickness, maternity and paternity.
* Periodic health examination
* PVI health care program

### Inclusive Culture
* Friendly, open-minded, young and supportive colleagues

### Contact
* Homepage: https://tinyurl.com/yc4huepz
* Kien Tran - Talent Acquisition Lead
* Email: kien.tran@saigontechnology.com
* Phone: 0398993171 (Skype, Zalo, Whatsapp, Telegram)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
