### ISSUE TITLE
Weploy - Junior/Medior/Senior Ruby On Rails Engineer - HCMC

### ISSUE THREAD

**Issue by Trangnguyen2404** [awesome-jobs/vietnam#3454]
## Location

* Tan Binh, HCMC, Vietnam

## Salary Expectation

* $1200 - $2500 Gross

We are a rapidly growing Melbourne-based startup with two product lines: 

- Weploy CX is our platform that connects businesses with talent, allowing our customers to pivot quickly and easily with the right team in place. We are really proud to have helped thousands of Weployees find meaningful work at leading companies around Australia and New Zealand. 
- Weploy Neat is an application enabling the service industry to easily coordinate their remote team. Alongside this we provide their employees an awesome experience with our application for accessing everything that they need from their phone - shift notifications, checklists, calendars and more. 

Our innovation has already won us multiple awards including the hottest and most innovative HR tech award, voted by Australia’s top HR professionals. Our products are loved and used by organisations like Medibank, Deliveroo, Peter MacCallum, Volkswagen Group, Super Retail Group, and many more. 

We are looking to add more people to our internal team, as Weploy continues to grow across the Australian market (and, globally!) Join us on our mission to make the future of work better for everyone as a Software Engineer in our Engineering team in Vietnam

**About you** 

- Have a strong technical background (equivalent to **1+ years of experience**) 
- Are an awesome human being 
- Are pragmatic and not dogmatic 
- Are proactive and like to take initiative 
- Make data and research-driven decisions 
- Understand what it takes to deliver successful product outcomes 

**Our tech set up** 

- Ruby on Rails (prior experience mandatory) 
- Turbolinks 
- Stimulus JS 
- Tailwind CSS 
- AWS Fargate 
- Docker 

**Part of the deal** 

- Full social insurance 
- 17 days of annual leave
- Accident and Private Health insurance, Yearly medical checkup 
- 10 days of public holidays, plus 2 days of Christmas and Boxing Day public holidays
- 13-month salary, provided MacBook Pro 
- Work hours allocated for Innovation and Learning sessions 
- Work-life balance. Long hours or overtime are not expected. 
- Annual performance review providing career growth opportunities 
- Direct employment with Weploy as part of its wider Engineering team. 
- Exciting industry space, exposure to Australian tech startup culture 
- A team of diverse, fun, and welcoming people

**Contact**

- Mail: trang.nguyen@weployapp.com
- Skype: live:ab833b9669160032
- Linkedin: https://www.linkedin.com/in/trang-nguyen-9b65b316a/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
