### ISSUE TITLE
Senior Fullstack Engineer (NodeJs, React/Angular) - GETLINKS PARTNER

### ISSUE THREAD

**Issue by Nhihoangftu2** [awesome-jobs/vietnam#3456]
## Location

* District 2, Saigon, Vietnam (Working hybrid)

## Salary Expectation

* Up to $4000/month

## Requirements
You have at least 5 years of professional experience using JavaScript stack
You have professional experience developing web applications using React or Angular
You understand the value of testing and practice Test Driven Development to deliver high quality software
You have experience using automated testing frameworks like Jest, Cypress, Selenium
You have professional experience with cloud (AWS, GCP or Azure) and containerisation technologies (Docker, Kubernetes) 
You understand the value of DevOps practices and can apply them in the software development lifecycle (Jenkins, CI/CD, GitHub Actions, GitLab CI, Azure DevOps etc)
You have professional experience working in an agile development environment and ideally have Scrum certification (e.g. Scrum Developer, Scrum Master)
You can contribute to technical decisions based on your expertise and client requirements
You have a degree in computer science or an equivalent related field (bachelor / master)
You are a strong communicator in English and can confidently collaborate with technical and business stakeholders

### Responsibilities

As a Senior Fullstack Software Engineer based in our Vietnam office, you will:

Cooperate with interdisciplinary regional teams in different projects and experience how technology and team spirit unite to create innovative solutions
Work closely with clients to develop, test, and ship software that meets their needs and efficiently and competently solve complex software challenges

### Contact
Skype: nhihoang.ftu2@gmail.com
Email: nhi.hoang@getlinks.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
