### ISSUE TITLE
Senior C#/ .Net Developer (Hanoi)

### ISSUE THREAD

**Issue by HDNG2629** [awesome-jobs/vietnam#3457]
## Location

* Hanoi, Vietnam
* Office workers 

## Salary Expectation

* $1500 - $1800/month 

## Requirements
* C#/ .Net
* Web development frameworks (Bootstrap, jQuery), ORM frameworks 
* Relational Databases and SQL 
* 5+ years Software Engineering experience

### Must Have

* Experience with HTML/CSS, JavaScript, and web development frameworks
* Experience with ORM frameworks 
* Experience with Web services development (SOAP, REST) 
* Strong in Object Oriented Programming, MVC, Design patterns, and SOLID principles 
* Proficiency in English 

### Responsibilities

* Interact with clients to gain an understanding of the requirements 
* Draw up milestones and ensure completion 
* Unit-test, work on bug fixing and improving products performance 
* Leveraging best software engineering practices 
* Identifying & eliminating performance and scale issues that ripple from front-end to back-end 
* Work with the distributed team in multiple time zones. 

### Why it would be awesome to work with us

* Join a global team and work directly with many talents around the world.  
* Working & growing with passionate, young, and talented team. 
* Minimum 13 months’ salary per year, plus performance bonus, pre-sales bonus. 
* Healthcare: Annual health check-up, Premium Health Insurance TECHVIFY Care 
* Salary: 35,000,000 - 45,000,000 VNĐ Gross 
* Sponsor and encourage staff to study courses by covering tuition fees, such as Udemy, Coursera 

### Contact
Skype: .cid.d9d79a557db1c33b
Phone: 0394262875 (Zalo/ Telegram)
Email: danny.pham@techvify.com.vn

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
