### ISSUE TITLE
JUNIOR PHP DEVELOPER

### ISSUE THREAD

**Issue by van1008** [awesome-jobs/vietnam#3458]
## Q1, HCM

[ HÀ ĐÔNG, HN] - 𝗣𝗛𝗣 𝗗𝗘𝗩𝗘𝗟𝗢𝗣𝗘𝗥
#PHP 

💰 Negotiable

✔️  Có từ 1-2 năm kinh nghiệm về lập trình PHP và kiến thức tốt về lập trình hướng đối tượng (OOP).
✔️  Có kinh nghiệm lập trình Full Stack (backend và frontend). 
✔️  Có thể làm việc trong môi trường tiếng Anh.

**Why it would be awesoe to work with us**
-  Đánh giá và xét tăng lương 6 tháng/lần. Hưởng lương thử việc 100%.
-  Cung cấp thiết bị làm việc đầy đủ, hiện đại.
-  Được đóng BHXH, BHYT theo quy định của nhà nước.

**Contact**
Email: vannguyen@freec.asia
Zalo: 032 8528 261

![Slide13](https://user-images.githubusercontent.com/109123888/178401929-8ddfcb32-62fd-41c0-810c-aa68d56f6f77.jpg)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
