### ISSUE TITLE
[SAIGON TECHNOLOGY] AUTOMATION QC ENGINEER (open for remote)

### ISSUE THREAD

**Issue by LCD-Nhien** [awesome-jobs/vietnam#3459]
## Location

* Remote or Da Nang city

## Salary Expectation

* $2000/month

## Requirements
* At least 4 years of experience in automation testing, web and desktop app
* Having solid knowledge of test cases design techniques and testing strategies
* Good at English communication

## Job Description
* Working in automation team
* Designing and writting test cases
* Executing test cases manually
* Implementing test scripts
* Maintaining / building automation framework

### Why it would be awesome to work with us
* Competitive Compensation And Benefits

> Attractive salary (13th-month salary, salary review twice/year) and project bonus
> Bonus programs for candidate referral, technical article writing
> Interest-free loan support for personal plan
> The staff of the quarter and year reward

* Exciting Activities

> Annual company trip and regular team-building parties
> Party celebration (Christmas, Birthday, Mid-autumn,...)
> Sports clubs (football, badminton, swimming …)
> Weekly happy hour

* Valuable Training

> Sponsor examination fee for professional certificates (AWS, Azure, IELTS, PMP, Scrum Master,...)
> Sponsor fee for joining any technical training sessions and courses
> Free English courses

* Flexible And Professional Working Environment

> A professional English-speaking working environment with Agile – Scrum model
> Flexible working time and working from home support

* Health Care Benefits

> Allowance for sickness, maternity and paternity
> Periodic health examination
> PVI health care program

* Inclusive Culture

> Friendly, open-minded, young and supportive colleagues

### Contact

🏢 [https://saigontechnology.com/](https://saigontechnology.com/?fbclid=IwAR20kkTDJv8-mgzZdsYj8zaK3MPOUiTO1hrzBJ5jaDl71emhNbtAhgfE1KU)
✉️Nhien.lam@saigontechnology.com
☎️0971970623 (zalo) or Skype: Diệu Nhiên
![293369892_338077528529741_5258163713108517376_n](https://user-images.githubusercontent.com/86979426/178425662-f38d4af7-d85c-4fd8-b8c0-f8376b7549d8.jpg)
![293165570_338075985196562_6404858679030340697_n](https://user-images.githubusercontent.com/86979426/178425692-ac46f202-de65-455a-8bb2-11f16440e320.jpg)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
