### ISSUE TITLE
Metacoders - Senior Backend Developer (NodeJS/Mysql) - Thu Duc HCM - FT

### ISSUE THREAD

**Issue by hienmetacoders** [awesome-jobs/vietnam#3460]
## Location: 

* Information Technology Park of Ho Chi Minh National University - Vo Truong Toan Street, Linh Trung, Thu Duc

## Salary Expectation:
* From $1000 - $4000 (depended on candidate's ability).

## Requirements:
- At least 3 years of hand-on coding experience Nodejs, Mysql.
- Experience in other languages is a big plus (Nestjs/ Prisma/ Typescript).
- Be able to communicate by English (preferred).

### Must Have:
- Solid experience with RESTful API.
- Solid experience with GIT source control, Agile process.
- Have strong product mindset, able to focus not only on technical but also user experience.
- Strong ability in detecting system and optimizing system performance.
- Experience in setting up, using, or configuring CI/CD pipelines and tools (e.g. Git, Ansible, Jenkins, Gulp, NPM, Gradle, ...).
- Strong understanding of standard Software Engineering processes, Testing, and Agile methodology.
- Strong knowledge in Queue system (Kafka/ RabbitMQ) and in-memory cache (Redis/ Memcached).
- Architecture, algorithm knowledge.
- Good experience with DBMS like MySQL, Redis, NoSQL, and ElasticSearch.
- Have knowledge in Test Driven Development (TDD), CI/CD.
- Experience with GIT source control, Agile process.

### Ideally:
- Experience in leading and coaching at least one software engineer team on various projects.
- Cloud-native technology (Container,  Kubernetes, Serverless) and DevOps culture.
- Experience in unit test, integration test, automated test, continuous integration on the cloud Amazon/Azure/Google.
- AWS, Serverless, Microservices, ecosystem.
- Have good grip on OOP, MVC, Functional Programming.

### Responsibilities:
- Work directly with PM, Leader and clients to clarify requirements.
- Train and coach team members.
- Support teammates to solve problems.
- Assist with application architecture design and implementation.
- Develop web services, test-driven development and unit test.
- Creating self-contained, reusable, and testable modules and components.
- Ensuring high performance.

### Why it would be awesome to work with us:
- Opportunity working onsite in Korea with talented teams.
- Professional Working Environment / Office located in Attractive Salary based on candidates’ competencies.
- 13rd Salary.
- Review salary 2 times/ year.
    
### Interesting Engineering Projects
One of our partners is The Strive, is Korean big start up and professional in car subscription service that we are going to working on.

### Contact:
Email: Hien.nguyen@metacoders.dev
Phone: 0909173713

### Company information:
_Website:_ https://metacoders.dev/
_Working time:_ 9 – 18g From Monday to Friday
_Location:_ Information Technology Park of Ho Chi Minh National University
_Google map link:_ https://goo.gl/maps/pU4BH3RaPGhAmPfz6

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
