### ISSUE TITLE
Picket Homes - Front-end Developer (JavaScript/React Engineer) - Remote/Hanoi - FT 

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3461]
Picket is seeking a software developer who has passion and ability to build customer-facing products at a fast pace. We have employed several technologies, but the product engineer would likely be working with ReactJS. You will work closely with product leaders, Fortune-500 clients, real estate professionals, and teammates to build, deploy, and iterate on amazing products on a frequent launch cadence.

We are always open to any candidates as long as we believe that Picket would be able to provide you with an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $2,500/month
* Stock options 
_See more in the Benefits section below_

### Minimum qualifications
* 3+ years of proven experience in developing and shipping high-quality web applications
* Proficiency in TypeScript and functional React   
* Self-motivated, organized, customer-obsessed, with a high level of integrity and ethics
* Sufficient English communication skills (both verbal and written)

### Preferred qualifications
* Knowledge of React ecosystem and toolings, such as react-query, redux, styled-systems, etc… 
* Knowledge of modern web applications and toolings, such as performance optimization, SEO, different testing frameworks, etc…
* Knowledge of end-to-end web architecture, such as databases, RESTful APIs development, security, and best practices
* Attention to code organization and details.
* Demonstrate ability to share knowledge, review code, translate business requirements to technical requirements, and take ownership of your work.

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/50b7818f-b8ac-437b-8428-7b5efc354de9
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/
Hanoi office: Room C54019, C5 D'Capitale Building - 199 Tran Duy Hung, Cau Giay, Hanoi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
