### ISSUE TITLE
Picket Homes - DevOps Engineer - Remote/Hanoi - FT

### ISSUE THREAD

**Issue by TaNgoc94** [awesome-jobs/vietnam#3462]
Picket is looking for a talented, experienced, and passionate DevOps engineer. You will have a chance to work with the most popular technologies and will be a part of our decision-making team.

We are always open to any candidates as long as we believe that Picket would be able to provide you with an environment for you to grow, develop, and build our company together. Hence, if you have a strong product ownership and are looking for a place to grow your career and impact millions of people, Picket might be just the right place for you. 

## LOCATION
* Hanoi, Vietnam
* Remote

## SALARY EXPECTATION
* Starting from $2,500/month
* Stock options 
_See more in the Benefits section below_

### Minimum qualifications
* 2+ years of commercial experience as a DevOps engineer
* Understanding of DevOps philosophy/practices
* Understanding of Linux internals
* Understanding of core AWS services uses, and basic architecture best practices
* Experience with CI/CD systems (Jenkins/Other)
* Good knowledge about Git/GitHub
* Knowledge of shell-scripting languages (Bash, Python, etc)
* Good communication and collaboration skills
* Motivation to learn new things and grow up as a professional

### Preferred qualifications
* Familiar with networking/load balancing
* Understanding of virtualization/ containerization technologies (KVM/Docker)
* Basic experience with microservice architecture/ patterns
* Experience with container orchestration (Kubernetes/Helm)
* Good experience with the IaC approach (Terraform/CloudFormation)
* Experience with logging systems (ELK/EFK)
* Distributed system knowledge
* Familiar with Agile development environments
* Experience with automation tools such as Ansible
* Experience with relational databases administration and performance tuning

### About Picket 
Picket is a technology-powered real estate company. With innovative technology and a customer-first philosophy, we’re transforming the experience of renting a home at every stage of the value chain. Our proprietary Decision Science platform uses advanced data science and machine learning to identify homes that fit investor criteria and optimize portfolio management and performance at scale. 

Picket is venture funded, and founded by a team of entrepreneurs and executives from top technology, real estate, and investment companies (Amazon, Google, Microsoft, etc.). Our team has been increasing from 11 to more than 100 employees within the last 18 months.

### Top 3 Reasons to Join Us
* Super fast growing Start-up with an autonomous working culture 
* Work with experienced software engineers in US, Poland and Ukraine 
* Fun place to work with competitively attractive salary and benefits 

### Benefits 
* Community of people who do their jobs with integrity and dedication to service
* Competitive compensation package with incentives, including stock options
* Performance review every 6 months 
* Onsite opportunity including short-term assignments in the U.S 
* Open working space with modern equipment (Macbook, monitors and anything you need!) 
* Flexible working model and unlimited paid time off 

## HOW TO APPLY
Submit your CV at: https://jobs.lever.co/pickethomes/cb8fd9cd-ebc4-4a89-91ce-15490800e96b
or feel free to contact me for more information: ta.ngoc@pickethomes.com or https://www.linkedin.com/in/ta-yen-ngoc-652728102

**_At Picket Homes, we are building something new and different - come build with us._**
https://pickethomes.com/
Hanoi office: Room C54019, C5 D'Capitale Building - 199 Tran Duy Hung, Cau Giay, Hanoi

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
