### ISSUE TITLE
[Chalasoft] - [Java Developer] - [Ha Noi] - [Fulltime]

### ISSUE THREAD

**Issue by Huees-ori** [awesome-jobs/vietnam#3464]
## Location

* Cau Giay,Hanoi, VietNam
* Fulltime

## Salary Expectation

* 3000-4500$/month 

## Requirements
* Java
* fluent English
* 3+ years Software Engineering (Java or  another OOP language in commercial projects)

## About Chalasoft

* We are a solid team, located in Vietnam and Russia, with 5 years experiences in working with global clients in financial software development
*  We are planning to grow the team in Vietnam to 200 in the next 3 years
* Project Devexperts
Our client is a global company in the development of software for financial markets and trading
industry. Devexperts has over 500 engineers all over the world. Devexperts products rated in
Top 5 brokerage solutions over the years. They create robust, reliable, powerful and
user-friendly solutions for brokers and exchanges around the globe

## What we expect to:
*Participate in one or more software development projects, working in a team of 3 to 10 developers
* Develop and debug program code and design system architecture
* Research into the newest software technologies and development tools as well as project domain
* Work closely with analysts, designers and staff
* Review source code of changes
* Present ideas for system improvements
* Maintain the systems once they are up and running

## Must have

* BSc/MSc in Computer Science
* At least 3 years’ experience working with Java or another OOP language in commercial projects
* Knowledge of fundamental data structures and algorithms
* Desire to work on complicated technical tasks together with experienced teammates
* Readiness to write tests, have strict code review and increase your code quality
* Willingness to deal with performance analysis, to detect and fix multi-threading issues
* Readiness to dive into complicated business requirements of finance world
* 
## Ideally
* Experience in multi-threaded and highly concurrent systems development
* Experience in development of high-performance and reliable distributed systems
* Understanding of relational database design, knowledge of SQL
* Knowledge of Unix family operating systems
* Knowledge of financial markets
* Ability to decompose complex requirements into a small and concise tasks
* Experience with PostgreSQL

## Why it would be awesome to work with us
*  Salary: $3000 - $4500 (gross)
* 13-month salary per year
* Social – Health – Insurance follow the labor law
* Healthcare: Annual health check-up
* Annual leaves: 12 days

### Contact
Telegram/Zalo: 0336 294 693 (Hue Tran)
Skype: Huees

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
