### ISSUE TITLE
McKinsey - Fullstack Engineer - Saigon/Hanoi - FT 

### ISSUE THREAD

**Issue by kienf** [awesome-jobs/vietnam#3468]
## Location

* Saigon, Vietnam
* Open to remote from Hanoi

## Salary & benefits

* Salary: you'll love it ;)
* Benefits: Mac devices, premium global health insurance, meal allowances, unlimited tech learning and certs on Udemy, getAbstract, Coursera, O'Reilly, ...

## Requirements (not all but nice to have)

* 5+ years of Software Engineering experience in an international environment
* While we advocate for using the right tech for the right task, we often leverage the following technologies: JavaScript, TypeScript, React.js, Angular.js, Next.js, Vue.js, Python, Java, C#, NodeJS, SQL, MongoDB, AWS, Azure, GCP, and more!

### Must Have

* Ability to write high-quality, self-documenting code using test-driven development techniques
* Familiarity with testing and debugging processes, including unit testing and UI testing
* Fluent English communication skills

### Ideally

* Experience with Full-stack development
* Open for Frontend engineers to apply then skill up

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop and maintain advanced features, tools, and applications according to the best practices in UI/UX, front-end to back-end development, and hybrid mobile application development. 
* Contribute to the architecture across the technology stack, from database to native apps. 
* Work with teams to create both rapid prototypes as well as full-scale applications by working collaboratively and iteratively through design and development to deliver fully functioning web-based and mobile applications that meet business goals. 

### Why it would be awesome to work with us

* Our office culture is casual and social, with an emphasis on education and innovation. 
* We have the freedom to try new ideas, and experiment and are expected to be constantly learning and growing. * Truly international environment where you work with colleagues around the globe and in meaningful projects across Asia.

### Interesting engineering projects

*  You’ll join a global team working on everything from IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation across all industries and functions.

### Contact
Full JD and apply here: [https://mck.co/3sbdxZF](url)
Homepage: https://www.mckinsey.com/business-functions/mckinsey-digital/how-we-help-clients/build-by-mckinsey/overview
Contact: kien_pham (at) mckinsey.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
