### ISSUE TITLE
McKinsey - Lead Engineer - Saigon/Hanoi - FT 

### ISSUE THREAD

**Issue by kienf** [awesome-jobs/vietnam#3469]
## Location

* Saigon, Vietnam
* Open to remote from Hanoi

## Salary & benefits

* Salary: you'll love it ;)
* Benefits: Mac devices, premium global health insurance, meal allowances, unlimited tech learning and certs on Udemy, getAbstract, Coursera, O'Reilly, ...

## Requirements (not all but nice to have)

* 8+ years of Software Engineering experience in an international environment
* While we advocate for using the right tech for the right task, we often leverage the following technologies: JavaScript, TypeScript, React.js, Angular.js, Next.js, Vue.js, Python, Java, C#, NodeJS, SQL, MongoDB, AWS, Azure, GCP, and more!

### Must Have

* Ability to write high-quality, self-documenting code using test-driven development techniques
* Familiarity with testing and debugging processes, including unit testing and UI testing
* Excellent English communication skills

### Ideally

* Experience with Full-stack development
* Client-facing experience in IT consulting business
* Leadership experience in guiding and leading a small team of 3-5 engineers

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop and maintain advanced features, tools, and applications according to the best practices in UI/UX, front-end to back-end development, and hybrid mobile application development. 
* Have responsibilities from shaping and implementing strategic products to ensuring that our craft stays on the leading edge of technology. You will also be responsible for designing end-to-end architectural landscapes as well as creating solutions for new businesses. 
* Collaborate with the rest of the engineering team to design and develop new features and applications for both mobile and desktop.

### Why it would be awesome to work with us

* Our office culture is casual and social, with an emphasis on education and innovation. 
* We have the freedom to try new ideas, and experiment and are expected to be constantly learning and growing. 
* Truly international environment where you work with colleagues around the globe and on meaningful projects.

### Interesting engineering projects

*  You’ll join a global team working on everything from IT modernization and strategy to agile, cloud, cybersecurity, and digital transformation across all industries and functions.

### Contact
Full JD and apply here: [https://mck.co/3IeOgmk](url)
Homepage: https://www.mckinsey.com/business-functions/mckinsey-digital/how-we-help-clients/build-by-mckinsey/overview
Contact: kien_pham (at) mckinsey.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
