### ISSUE TITLE
Front End Developer

### ISSUE THREAD

**Issue by tuyendung** [awesome-jobs/vietnam#347]
## Location

* Ha Noi, Vietnam
* Remote

## Salary Expectation

* Up to 800$/month or negotiable

## Requirements
* HTML5, CSS3, Bootstrap
* client-side scripting and JavaScript frameworks
* mobile development and mobile-first responsive design
*
### Ideally

* At least 3 years experience

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

*•	Work with the UI/UX designer in define gap between graphical design and technical implementation, take an active role on both sides and defining how the application looks as well as how it works
•	Use markup languages like HTML5 to create user-friendly web pages
•	Maintain and improve website
•	Develop new user-facing features
•	Build reusable code and libraries for future use
•	Ensure the technical feasibility of UI/UX designs
•	Optimize application design for maximum speed and scalability
•	Assure that all user input is validated before submitting to back-end

### Contact

Trollman: tuyendung@net2e.vn

**Comment by hieuk09** [comment]
Hi @tuyendung, your job post is not complied to our guideline. Please revise the following:
- Title must be strictly followed the guideline
- Company Info section is compulsory
- Move the text `* ## Skills` to correct plage
- Add more info or remove `You can bring` section.

**Comment by joneslee85** [comment]
No amendment - closed
