### ISSUE TITLE
ADAPTIS GMBH - Account Manager - Ha Noi - Remote Full Time

### ISSUE THREAD

**Issue by CherishMIS** [awesome-jobs/vietnam#3471]
##JOB RESPONSIBILITY:
* Establishes and maintains business relationships with internal and external customers.
* Develops IT projects to meet the business needs of the customers.
* Ensures that IT initiatives are met in a timely manner and within a prescribed budget.
* Lead other IT members of staff in actualizing company’s goal towards better service
delivery
* Oversee and manage activities of other IT staff members to ensure all work in line with
laid down procedures outlined by the organization
* Report activities directly to the agency director or IT account director, regarding the
status of any client-related transaction
* Advocate the needs and expectations of the client to ensure compliance by top
management towards achieving customer satisfaction, which is the sole goal of the
organization.
* Work with IT product development team to ensure compliance with customer’s
expectations
* Ensure that product portfolio gives reflection of ever-changing needs of the clients
* Coordinate technical support teams to provide varieties in customers’ products
* Streamline maintenance, user supports, training, installations, and solution design
towards satisfaction of clients’ needs
 
##YOUR SKILLS AND EXPERIENCES
* Bachelor’s degree in information technology, marketing, business, or other related fields, including six to eight years working experience in any of the fields
* Proven project management and customer success experience
* Working experience in IT media studies or marketing, depending on nature of account to be managed
* Familiarity with a number of IT field concepts, procedures, and practices
* Ability to plan and successfully accomplish company’s goals
* Possess latitude and creativity in handling customers’ accounts
* Ability to relate with customers, top management and junior staff members in the IT department and across other departments
* Ability to manage more than one IT account at the same time as dictated by the company’s
requirements at any particular time
* Ability to maximize all business opportunities relating to each customer, like sales and
marketing campaigns, resource requirements, and revenue forecasts
* Good command in English

##WHAT WE OFFER YOU
• 13rd month salary
• Unlimited paid days off
• Allow to work from home/remote
 
###Contact:
Email: linh.nguyen@adaptis.io
Skype: live:.cid.246de80c0688d565
Website: https://adaptis.io/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
