### ISSUE TITLE
CXP - BE Engineer - Up to $2000 - HCM - Full-time 

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3472]
## Location
* Botanica Premier Apartment, Block A2, 102 Hồng Hà, Tân Bình District, HCMC, Vietnam

## Salary Expectation
* up to 2,000$/month

## What you’ll work on
* Thorough understanding of how popular dApps work: Uniswap, Sushiswap, Compound...
* Experience in writing automated tests for dApp frontends.
* Ability to create testing setup from zero.
* Be able to work autonomously.
* The candidate should be independent enough to make important technical decisions on their own.
* The candidate should be driven and innovative, planning the best ways to get full test coverage of the product.

### What you’ll work on
* Designing and building a cryptocurrency exchange for high scalability and pauseless 24/7 operation under high-load conditions and providing low-latency responses.
* Implementing core function: wallet management, orders matching, priority limit order, risk control management, dispute management, admin and reports API.
* Analytics tools to help senior management make data-led business decisions.
* Integration new blockchain technologies.
* Improving our platform’s security and resilience.

### Our tech stack
- Backend: distributed, event-driven core Java, PostgreSQL.
- Data analytics: Python & Jupyter notebooks, Parquet, Docker.
- Blockchain integrations: Bitcoin (Litecoin, Bitcoin Cash), Ethereum and XRP (Ripple).

## Requirements
* A good understanding of how to write clean, efficient, well-tested code.
* Solid knowledge of event processing models, multi-threading, and enterprise integration patterns.
* Extensive experience in software design, architecture, and development integration.
* A keenness to learn and to work in a highly collaborative environment.
* Strong communication and problem-solving skills.
* Experience in financial systems, especially the payment domain, is a great bonus.

### Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

### About Us
CXP is Digital Asset Exchange, predominately used for trading cryptocurrencies, and is looking for a new developer to join its HCMC-based team.

Contact
Email: [hr@cxptek.com](mailto:hr@cxptek.com)
Phone: (+84) 38 4498 899 (Jade)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
