### ISSUE TITLE
Dwarves Foundation - FrontEnd Engineer - Saigon - FT/PT

### ISSUE THREAD

**Issue by gnhuy91** [awesome-jobs/vietnam#348]
<img src="https://cloud.githubusercontent.com/assets/10569203/19617736/6fcd5eb8-9862-11e6-98fc-2ea8226b124b.png" height="180" />

https://github.com/dwarvesf/WeAreHiring
## Location
- Saigon, Vietnam
## Wanted

We are looking for highly-motivated Frontend engineers with React knowledge/experience, you will build a single-page web application with React, turn designed UI/UX to codes, implement new features and make our customers happy.
## Requirement
- Good front-end skills: experience with using React, HTML, CSS and JavaScript, design patterns, good sense of UI/UX design.
- We are result-oriented - work experience is not the highest factor, we are more interested in how you can fit into our team, reliability of your works and your willingness to learn.
## Who we are?

We are a team of geeks, hustles and startup veterans. We are (forever) young, ambitious and always eager to learn. We have passion and experience in making cool products. We want to help entrepreneurs solve real problems using our approachs and solutions.

We position ourselves as a Startups Factory. We build innovative products, give a hand to build companies and also give seed investment. Join our network if you are startup veterans, can wear multiple hats at the time and want to build world class products.
## Why would you join us?
- We seek for customer's trust and happiness by providing excellent software engineering and system architecturing.
- We love learning and using new yet reliable, proven technologies.
- You are free to pick your most productivity time to work. You need to figure out yourself what you want to do and what you want to contribute aligned to the team goal.
- We encourage continous learning and sharing, because your improvement contributes to our magic pool of tech skills.
## Salary Expectation
- We offer fair and competitive income for experienced engineers.
## Interested?
- Reach out: team@dwarvesf.com
- More about us: https://github.com/dwarvesf/WeAreHiring

**Comment by joneslee85** [comment]
Looks good, please revise the title format and it's ready to go

**Comment by gnhuy91** [comment]
@joneslee85 thanks, I just revised, is it good now?
