### ISSUE TITLE
[POSITIVE THINKING COMPANY] [REACTJS DEVELOPER] - [HANOI/HCMC] - [FT HYBRID] 

### ISSUE THREAD

**Issue by Xamnguyen** [awesome-jobs/vietnam#3482]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* Negotiate

## Requirements
* Reactjs
* Nextjs
* HMTL/CSS
* 4+ years Software Engineering experience

### Must Have

* Good English communication skills

### About Positive Thinking Company
Positive Thinking Company is a global independent tech consultancy group. We are Great Place to Work-Certified™ with 90% of our team members in Vietnam agreeing that we are a great place to work! With a team of more than 3,000 talented tech specialists on the ground in over 35 cities across Europe, the USA, Asia, Australia and Africa, we serve clients of all sizes. We believe collaboration betters our world. Our unique open ecosystem model allows us to deliver end-to-end tech solutions.

### Contact
Email: xam.nguyen@positivethinking.tech
Skype: live:.cid.f9a5012fddc93dbe

**Comment by Xamnguyen** [comment]
At PTC we have Hybrid work model and flexible working time, location we have office in Hanoi, HCMC
Salary depend on your skills and your expectation, feel free to contact me for more details!
Positively yours, 
Xam Nguyen from PTC <3

**Comment by qcam** [comment]
Could you please provide more info about the position? This post will be closed until then.
