### ISSUE TITLE
[POSITIVE THINKING COMPANY] [REACTJS DEVELOPER] - [HANOI/HCMC] - [FT HYBRID] 

### ISSUE THREAD

**Issue by Xamnguyen** [awesome-jobs/vietnam#3485]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam
* Hybrid 

## Salary Expectation

* Negotiate 

## Requirements
WHAT YOU NEED FOR THE JOB?
Essential Skills & Requirements:

- Solid knowledge of web technologies (HTML/CSS/JavaScript) and frameworks in building responsive design and cross browser compatible
- Solid understanding of Javascript (ES6+)
- Solid knowledge of React, React-Native, and similar technologies
- Hands-on experience with popular JavaScript tools, frameworks and design principals, and up to date with the changing JavaScript ecosystem landscape
- Experience in analyzing UI performance metrics and optimizing the implementation
- Ability to perform and influence code reviews as well as technical design meetings
- Thorough understanding of Software Development Lifecycle and methodologies

Preferred Skills & Requirements:

- Experience in building web applications with video playback capabilities
- Working experience with Scrum or similar agile methodologies
- Experience with version control systems (e.g. Git) and understanding of branching models & strategies
- Experience with docker and deployment tools
- Experience with Xcode and Android Studio.

### Why it would be awesome to work with us

Positive Thinking Company is a global independent tech consultancy group. We are Great Place to Work-Certified™ with 90% of our team members in Vietnam agreeing that we are a great place to work! With a team of more than 3,000 talented tech specialists on the ground in over 35 cities across Europe, the USA, Asia, Australia and Africa, we serve clients of all sizes. We believe collaboration betters our world. Our unique open ecosystem model allows us to deliver end-to-end tech solutions.

### Contact
Mail: xam.nguyen@positivethinking.tech
Skype: live:.cid.f9a5012fddc93dbe

**Comment by Xamnguyen** [comment]
At PTC we have Hybrid work model and flexible working time, we have office in Hanoi, HCMC as well.
Salary depend on your skills and your expectation, feel free to contact me for more details!
Positively yours,
Xam Nguyen from PTC <3

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
