### ISSUE TITLE
[Executionlab] Junior/Middle Backend Developer (Ruby on Rails/Golang) - HCM- Fulltime

### ISSUE THREAD

**Issue by tamhuynh083** [awesome-jobs/vietnam#3489]
## Location
- Q. Tân Bình, Tp HCM, Vietnam

## Salary Expectation
- Up to $1500 Gross
- SI, HI, UI from Gross salary.

### Must have
- At least 1 year of experience in **Golang** or **Ruby on Rails**
- Knowledge of development based on API, Microservices, or Single web application.
- A passion for writing great, simple, clean, efficient code
- Basic knowledge of RDBM (MySQL, Postgres)
- Basic knowledge of Frontend Technologies: JavaScript, HTML5, CSS, ReactJS, etc
### Nice to have
- Task management skills, leadership skills
- Communication skills to verbally discuss technology with customers and other teammates.

## Responsibilities
- Design and develop services
- Design database schema
- Write clean and maintainable code
- Discuss system/software architecture with the team

## Why it would be awesome to work with us

- Great salary package. Year-end Bonus.
- Salary and performance review TWICE a year.
- A MacBook or a personal laptop is provided.
- Annual health check-up for all staff.
- Training and coaching program from our expert developers.
- Self-serving coffee machine, drinks, and a pantry full of sweets and snacks.
- Monthly party with food and drinks.
- Team Building, Company Trip,... and other significant events.
- Free language training: English and Japanese.
- Opportunity to go work on-site in Japan.
- Gifts and allowances for weddings, having babies, Women’s day, and Children's Day
- Sports clubs to maintain your balanced health: running, football, badminton,…

## Interesting engineering projects
Executionlab is a software development company based in Ho Chi Minh City that works with clients from Japan.
Domain: Fintech, Logistics, Healthcare,...

### Tech Stack
AWS, ReactJS, Ruby on Rails, Golang, Kotlin, Swift, iOS Native, Android, Flutter, …
If you want to try any new technology on real projects, let us know!

## Contact
Apply here: https://executionlab.asia/jobs/backend-developer/
Fanpage: https://www.facebook.com/ExecutionLab
Email: [contact@executionlab.asia](mailto:contact@executionlab.asia)
Phone: (+84) 28 6673 3588

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
