### ISSUE TITLE
Tech Outpost - Frontend developer - Saigon - FT

### ISSUE THREAD

**Issue by RobDoan** [awesome-jobs/vietnam#349]
![Tech Outpost](https://s3.amazonaws.com/temp.neverland/techoutpost-logo.png)

A website is not just a mash up of graphics and words, it is the gateway to your business and it tells your story, brand and vision. First impressions matter, and we believe in making it count. At Tech Outpost, we don’t just build websites, we create memorable experiences that communicates the essence of your brand.
We’re a team of dreamers, storytellers and brainiacs, coming together to help you change the world.
## Location
- Saigon, Vietnam
## Salary Expectation
- negotiable
## Requirements
- Advanced HTML, CSS and JavaScript experience
- Must have a working knowledge of a CSS framework and/or JavaScript framework
- Proficiency in Adobe Photoshop, Sketch and Illustrator
- Familiarity with GIT a plus (or the willingness to learn)
- Demonstrated ability to communicate effectively both verbally and written
- A team player who can also work independently with minimal supervision
- Must be organized and detail-oriented
- Ability to work on multiple priorities and/or projects simultaneously
- Strong problem solving/code conceptualizing skills and an intuitive nature
- Demonstrated superior visual, user interface, and interaction design skills
- Self-motivated and willing to "do what it takes" to get the job done
## Skills
- HTML, CSS and JavaScript
- Sketch, Photoshop, Zeplin, ...
### Ideally
- Experience with webpack, reactjs, gulp ...
### Responsibilities
- Deliver world-class user interaction designs, from concept to launch
- Produce designs to help the entire product team understand the desired customer experience: storyboards; flows; wireframes and prototypes
- Work in partnership with product management and development to deliver the desired experience on time
- Build new and unique application interactions based off of existing design framework
### Benefit 
- Benefits include the opportunity to join a fast growing company, where you can grow professionally and build a strong career.
- 12 PAID days off a year.
- Choice of Macbook pro laptop or PC laptop.
- Relaxing room with electronic soft-tip dartboard and many game boards.
- Free-snacks and beverages.

### Contact

Quy Doan: hr@techoutpost.co
Website: www.techoutpost.co

**Comment by joneslee85** [comment]
Please revise the title, the `Full Time` should be `FT`

**Comment by joneslee85** [comment]
Plus the photo is not displaying
