### ISSUE TITLE
Hybrid Working_Hanoi/HCM_FRONT-END (ReactJS/ VueJS)_Full-time 

### ISSUE THREAD

**Issue by manhduc77** [awesome-jobs/vietnam#3491]
## Location

- Hanoi/ HCM
- Hybrid Working Policy: 2 days WFH, 2 days WFO, 1 day optional (ONLY FOR HANOI)

## Salary Expectation

- Top salary in Vietnamese market - Negotiable

## Requirements

- Ideally, 4+ years of work experience on Front-end to serve large-scale and high-traffic projects
- Proficient understanding of HTML/CSS/JS
- Should have the knowledge of advanced JavaScript libraries, such as React, Vue
- Good understanding of asynchronous request handling, partial page updates, AJAX, NodeJS, SSR
- Deep knowledge and experience in Object-Oriented and functional programming
- Deep knowledge and experience in applying Design Patterns
- Experience in Data Structure, Algorithm, Distributed Service
- Understand the importance of writing high Maintainable Code, Clean Code
- Proficient understanding of Git (Experienced in merging, branching source code)
- Experienced in setup and using Continuous Integration (Jenkins), Continuous Delivery and Infrastructure as Code

### It's a big plus if you

- Have experience in Server Architecture Design for handling massive traffic
- Have experience in System Analysis & Design, Micro Service Architectures
- Have an understanding of cross-browser compatibility issues and ways to work around them.

### Responsibilities

Great power comes with great responsibilities!

### Why it would be awesome to work with us

-Hybrid working: 2 days WFH, 2 days WFO, 1 day optional (ONLY FOR HANOI)
- Annual health check + premium gym membership
- 14 months salary, full salary probation
- Full salary insurance, paid after probation (PVI insurance candidate + 2 family members)
- MacBook (M1) & equipment provided, working angle setup (budget 5 million)
- Fees for learning languages ​​(Korean, English) - technologies (budget $1000/year)
- 14 days of leave, add 1 day to each year.

### Contact
- Gmail/ Skype: duc.nguyen@reco-vn.com
- Zalo/ Tele/ WhatsApp: 0963269923

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
