### ISSUE TITLE
[REMOTE-FULLTIME] Senior Software Engineer

### ISSUE THREAD

**Issue by linhnguyen73** [awesome-jobs/vietnam#3492]
**Location**

* Saigon, Hanoi, Danang Vietnam
* Remote

**Salary Expectation**

* Up to $3500/month 

**Requirements**
- Bachelor’s degree (or higher) in Computer Science or related discipline (BKU, US or PTIT are preferable)
- 3+ years experience in software development building successful production software systems.
- Strong understanding of computer science fundamentals, including algorithms, complexity analysis, data structures, problem-solving, and object-oriented analysis.
- Proven record of Experience developing software services and an understanding of design for scalability, performance, and reliability.
- Excellent verbal and written communication skills.
- Experience with modern object-oriented programming languages, including but not limited to: Nodejs, Java, Python or Go.
- Proven ability to work in a fast-paced, and in an ownership and results-oriented culture.
- Experience in full-stack development ranging from front-end user interfaces through to back-end systems.

**Skills**

- Problem-solving 
- Strong in coding
- Good deep-work

**Ideally**

- Strong demonstrated skills in implementing and deploying high volume and highly scalable services.
- Familiarity/experience with AWS services
- Knowledge of professional software engineering practices & best practices for the full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations.
- Experience in communicating with users, other technical teams, and management to collect requirements, evaluate alternatives and describe product strategy, technical designs, and software product features. 

**Responsibilities**

- As a senior engineer, you will evaluate the current product tech stack and architect to come up with new innovative architecture decisions and solutions for our product: Boost’s Product Discovery platform. (We are currently the top 1 Product Discovery platform for Shopify E-commerce).
- You will be working closely with the product manager, business analyst, designers, and other engineers to ensure we are building effective solutions for E-Commerce.
- Lead engineering architecture design reviews.
- Set a high technical bar for the team through code and architecture design reviews.
- Working across teams with Product, Design, and Engineering to create integrated solutions that delight our customers.

**Why it would be awesome to work with us**
- 100% remote culture. Live and work from wherever you feel happiest.
- 13th-month salary and bonuses.
- Offers allowance for any classes supporting physical and mental health of employees, such as: gyms, fitness, yoga, dancing, vocal, etc.
- Day-off: 14 days/year and Vietnam holidays.
- MacBook provided after probation.
- Online Meet-ups: Weekly Happy Hour, Weekly Monday Funday, Internal Mini Games and Contests, Virtual Online Parties, etc.
- Offline Meet-ups: All team Co-work, Monthly Meet-ups, Year-End Party, etc.
- Boost Company Trips.
- Technical and general workshops in the company.
- Free online learning and reimbursements for selected courses.
- Bao Viet Premium Health Care Insurance (after 3-month in the role).
- Annual health check-up at Premium Clinics.
- Great chance to improve your expertise/skills and English communication via international exposure.
- Get support and work with talented and friendly members.

 **Contact**
Homepage: boostcommerce.net
Linkedin: https://www.linkedin.com/in/linh-nguyen-lucy-99810418b/

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
