### ISSUE TITLE
Momo - Java Developer - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by Linhnck** [awesome-jobs/vietnam#3498]
## Location

* Ho Chi Minh City, Vietnam
* Fulltime

## Requirements
* 2+ years experience at server-side languages such as Java
* Good knowledge of data structures, system design, and algorithms
* Experience with Spring framework (Spring Bean, Spring AOP, Spring Data, Spring MVC), Spring Boot, Hibernate

## Responsibilities

* Develop and enhancement large scale systems using Java technologies: Collection/Insurance feature, Loan/Saving/Investing feature, Mobile App Platform, Delivery Services. Contribute in all phases of the development lifecycle
* Write well designed, testable, and efficient code
* Ensure designs are in compliance with specifications
* Identify bottlenecks and bugs, and devise solutions to these problems

## Why it would be awesome to work with us

* Flexible working environment
* Healthcare insurance
* Atractive allowance and bonus
* 13th salary

### Contact
Homepage: linh.nguyen29@mservice.com.vn
Mobile/Zalo/Skype: 0978779501

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
