### ISSUE TITLE
VNG - Game Development Fresher - Hanoi - PT

### ISSUE THREAD

**Issue by Trangbth** [awesome-jobs/vietnam#3499]
## Location

* Ha Noi, Vietnam

## Salary Expectation

* 15.000.000 VND/month

## Requirements
* Any of programming languages
* No experience required
* Good at Data Structure and Algorithms & Object-oriented programming (OOP)
* Be able to work Fulltime in 2022 & 2023

### Responsibilities
* Participate in the development of domestic and international game products

### Why it would be awesome to work with us
* Professional and well-trained training provided (Mentor 1-1)
* Opportunity to become official employee after 3 training months (with higher salary and benefit)
* Games at office: Bi-a, Board Game, ...
* Free Drinks, Food every day & week

## Contact
Application: https://bit.ly/3QbL0fM
Website: https://career.vng.com.vn/
Fanpage: https://www.facebook.com/vngzpscareer

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
