### ISSUE TITLE
Beheard - Node.js Developer - HCMC - FT

### ISSUE THREAD

**Issue by Xvolver** [awesome-jobs/vietnam#350]
![xvolve-logo-170-151](https://cloud.githubusercontent.com/assets/23050879/19682235/e0050c96-9ad6-11e6-94e1-1f90ae428dce.png)
## About Us
- We are looking for an experience Back-end Developer (Node.js,AngularJS,JavaScript) to join our team! 

*We are a brand-new, global startup located in San Francisco and Ho Chi Minh.
- Our CEO has successfully sold his last startup for $20 million.
- BeHeard is funded for $3 million and aiming to be the next Unicorn by 2020.  
- We are an international team with Americans, Japanese, Korean, Vietnamese, etc.
- Our Introduction Video: https://youtu.be/-iCiU5p5D2I
## Our Product
- Our product - BeHeard
  BeHeard connects people 1 on 1 with friendly "Listeners" in the world. It is just a 10 min, uplifting conversation to brighten up your day.
- BeHeard video: https://www.beheard.co

![14441085_1317271508297741_5256097622661006519_n](https://cloud.githubusercontent.com/assets/23050879/19682172/962e3282-9ad6-11e6-8386-1f84942c480b.png)
## Location
- Saigon, Vietnam
- Saigon Pearl, 92 Nguyen Huu Canh, Binh Thanh
## Salary Expectation
- Based on skills / performance
- Up to 1,000 (Junior level)
- Up to 1,800 (Senior level)
### Must Have
- 2 years experience in AngularJS, JavaScript.
- Ability to work on the backend with Node.JS
- Knowledge and experience of Trello and Git
### Ideally
- Understanding about how to use payment services on server side (Stripe, Paypal, etc.)
- Understanding of both iOS and Android elements
- Experience with Continuous integration is a big plus
- Startup experience
- Knowledge with deploying tools (amazon web services, etc.)
### Responsibilities
- Implement new features on servers.
- Create APIs for interacting with front-end side
- Making analytics system in our admin
- Making and editing web site
### Benefits
- Be engaged in development for the early stage of a revolutionary app
- Young, passionate, energetic, and friendly colleagues.
- Startup culture, a lot of opportunities to grow on a steep learning curve.
- International team (Japanese, American, Vietnamese, Korean, etc)he world with us.
### Contact

Beheard Team: info_at_xvolve_dot_com

Or APPLY at
https://itviec.com/it-jobs/xvolve-back-end-developer-node-js-angularjs-javascript-1737

**Comment by joneslee85** [comment]
Thanks for applying with us. Please make following changes:

* The title does not comply with our guideline
* The bulletpoint format is wrong

**Comment by Xvolver** [comment]
@joneslee85 is it ok now?

**Comment by hieuk09** [comment]
@Xvolver 👍
