### ISSUE TITLE
SCS Solution - .Net Developer - Tan Binh/Saigon - FT

### ISSUE THREAD

**Issue by KimTuyen2803** [awesome-jobs/vietnam#3503]
## Location

* Tan Binh, Saigon, Vietnam

## Salary Expectation

* upto 2000$/ month or nego

## Requirements
• 2+ years’ experience working in Software Development
• Solid experience with .NET/.NET Core, MS SQL, MongoDB, and Web 
technology
• Experience with REST API
• Experience with Windows Service/ Worker Service
• Experience with OOP, design patterns
• Excellent in problem-solving and analytical skills

Skills for Front-end:
• Experience with ES6 or later, Angular or React-Js, or Vue is a plus.
• Expertise in a single page application including front-end routing, 2-way data 
binding, client-side rendering and JSON-based RESTful APIs.
• Expertise in HTML5, CSS3, JavaScript, jQuery, Typescript, and NodeJS.

## Skills

• Familiar with the software development methodologies (Agile, Scrum, Kanban).
• Have logical thinking, good analysis, and problem-solving skills.
• Good in communication (verbal and writing in English), positive attitude, time 
management, working well under pressure, quick learning.
• Working proficiency and high sense of responsibility, team spirit and resilience.
Other:
• Good in English is a plus
• Bachelor's degree (in Computer Science, Math or Engineering

### Must Have

* Solid experience with .NET/.NET Core, MS SQL, MongoDB, and Web technology
* `Experience with REST API

### Ideally
* Experience in EDI is a plus.
* Experience in GrandNode CMS is a plus.

### Responsibilities

• Translate application storyboards and use cases into functional applications
• Design, build, and maintain efficient, reusable, and reliable code
• Join to solution analyze and documents
• Ensure the best possible performance, quality, and responsiveness of applications
• Identify bottlenecks and bugs, and devise solutions to mitigate and address these 
issues
• Help maintain code quality, organization, and automation

### Why it would be awesome to work with us

● Competitive Compensation and Benefits
• Attractive salary (13th-month salary, salary review per year) and project bonus
• Good opportunity for promotion through regular performance review system.
• Be provided with high performance laptop and screen
• Attractive and clear career path.

● Exciting Activities
• Annual company trip and regular team-building parties

● Flexible And Professional Working Environment
• A professional English-speaking working environment with Agile –Scrum model
• Flexible working time.

● Social insurance and Health Care Benefits
• Allowance for sickness, maternity and paternity.
• Health care program, PVI Health Insurance

● Inclusive Culture
• Friendly, open-minded, young and supportive colleagues
• Overseas travel opportunities (US)
• Working Time: 9:00 AM –6:00 PM from Monday –Friday

### Contact
Homepage: scssolutions.io
Mail: recruitment@scssolutions.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
