### ISSUE TITLE
SCS Solutions - Ruby On Rails - Tan Binh/Saigon - FT

### ISSUE THREAD

**Issue by KimTuyen2803** [awesome-jobs/vietnam#3506]
## Location

* Tan Binh, Saigon, Vietnam

## Salary Expectation

* upto $2000/month or nego

## Requirements
• Strong experience in Ruby on Rails.
• Strong experience in web API technologies.
• Hands-on experiences with PostgreSQL other (MySQL, NoSQL ,...)
• Strong ability to communicate both verbally and in writing, especially with technical analysis
• Have knowledge of Agile (JIRA or similar management tools)
• Good experiences in working with CICD including Docker, Jenkins or related products.
• Implement best practices, standards and procedures including quality and delivery 
methodologies
• Good at English communication

### Responsibilities

• Work with the project lead, take assignments, and do effort estimation.
• Participate in designing the framework from scratch.
• Code, test and review code of other members.
• Fix bugs and provide technical support when required.

### You’ll be responsible for

Perform development activities to build and maintain WEB-based software systems.

### Why it would be awesome to work with us

**Competitive Compensation and Benefits**
• Attractive salary (13th-month salary, salary review per year) and project bonus
• Good opportunity for promotion through regular performance review system.
• Be provided with high performance laptop and screen
• Attractive and clear career path.
**Exciting Activities**
• Annual company trip and regular team-building parties
**Flexible And Professional Working Environment**
• A professional English-speaking working environment with Agile –Scrum model
• Flexible working hours.
**Social insurance and Health Care Benefits**
• Allowance for sickness, maternity and paternity.
• Health care program, PVI Health Insurance
**Inclusive Culture**
• Friendly, open-minded, young and supportive colleagues
• Overseas travel opportunities (US)
• Working Time: 9:00 AM – 6:00 PM from Monday – Friday

### Contact
Homepage: scssolutions.io
Mail: recruitment@scssolutions.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
