### ISSUE TITLE
SCS Solutions - Java Developer - Saigon - FT

### ISSUE THREAD

**Issue by KimTuyen2803** [awesome-jobs/vietnam#3507]
## Location

* Tan Binh, Ho Chi Minh City, Vietnam

## Salary Expectation

* upto $2000/ month or nego

## Requirements

• Good Diploma/Degree in Computer Science/Information Technologies.
• Project experience of CSS animation, or Mobile animation work is an added advantage.
• Familiar with Agile and Continuous Integration and Continuous Delivery (Deployment).
• Knowledge of code versioning tools including Git, or SVN.
• Able to quickly learn new technologies, framework, development languages.
• Strong interpersonal and communications skills, both oral and written.
• Strong debugging and problem-solving skills.
• Understands what to build optimize for speed and scalability
• Able to work in a dynamic and ever-changing industry.

For Senior Front-end Web Developer
• Has a STRONG background on Angular, jQuery, JavaScript, J2EE/Spring to develop webbased
Java application.
• Has 2-year ' experience in mentoring and guiding small teams.
• Has matured thinking process, good analytic and problem-solving skills.

## Skills
• Web development knowledge (HTML, CSS, Angular, Javascript, jQuery, JSON etc).
• Java EE development experience (Java Core, Java EE, SPRING).
• Database/SQL knowledge (SQL, Stored Procedures, and MySQL).

### Responsibilities
● Participate in developing web applications using Angular, CSS, Java technologies.
● Understand application requirement and workflow from mockups and converting to workable
code.
● Perform coding, testing and reviewing in line with user & system requirements to deliver
programs that meet client’s needs and meet the release milestone.
● Perform 3rd level support to rectify production issues and provide solutions

### You’ll be responsible for

Perform development activities to build and maintain WEB-based software systems.

### Why it would be awesome to work with us

**Competitive Compensation and Benefits**
• Attractive salary (13th-month salary, salary review per year) and project bonus
• Good opportunity for promotion through regular performance review system.
• Be provided with high performance laptop and screen
• Attractive and clear career path.
**Exciting Activities**
• Annual company trip and regular team-building parties
**Flexible And Professional Working Environment**
• A professional English-speaking working environment with Agile –Scrum model
• Flexible working hours.
**Social insurance and Health Care Benefits**
• Allowance for sickness, maternity and paternity.
• Health care program, PVI Health Insurance
**Inclusive Culture**
• Friendly, open-minded, young and supportive colleagues
• Overseas travel opportunities (US)
• Working Time: 9:00 AM –6:00 PM from Monday –Friday

### Contact
Homepage: www.scssolutions.io
Mail: recruitment@scssolutions.io

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
