### ISSUE TITLE
LionRose - Java Backend Game Developer - Saigon - FT

### ISSUE THREAD

**Issue by lynnhr81** [awesome-jobs/vietnam#3509]
## Location

* Binh Thanh, HCMC, Vietnam

## Salary Expectation

* Junior: up to $1500 net
* Senior: up to $3000 net 

### Must Have

* **+2 years** of experience in **Java** as backend developers.
* Experience working with **Spring Boot,** **gRPC.**
* Proficient with **NoSQL**, **Caching,** **Unit test.**
* Familiar with **Message broker.**
* Good at **algorithms**

### Ideally

* Have a good **product mindset**.
* Experience in developing **game server** systems.
* Understand the operation mechanism of **game engine**.
* Have knowledge of **security** for large systems.
* Proficient with **GIT**.
* Good understanding with **Docker, Kubernetes**.
* Familiar with **SQL systems**.
* Familiar with **Kafka, RabbitMQ**, and **NATS messaging systems**.
* Adapt to **high pressure** at work.

### You’ll be responsible for

**JAVA Developers** will be involved in the architecture, development, and maintenance the **Backend** of our products.

- Develop the **backend server architecture.**
- Integrate **new features** to the frontend.
- Ensure **server scalable, persistency, communication** and **logic** to support a high number of concurrent users.
- Improve **security**-relevant components.
- Optimize **server architecture**, code, data structure, bandwidth, memory and CPU usage.
- Writing and maintaining **fast code**, detailed **technical design** and **documentation**.

### Why it would be awesome to work with us

- Salary upto **3000$**
- **MacBook Pro** and additional working-support **devices** provided on demand.
- **100% salary** in probation.
- Competitive **long-term** **salary** package + **performance bonus**.
- **Review performance** and **salary** every release milestone.
- **13th-month salary** + **Lì xì.**
- Friendly working environment, no office politics.
- 5-star Company trip + Monthly Team building + birthday bonus.
- Snacks and drinks lounge.
- Weekly **sport clubs** (Console, Badminton, Soccer, Archery, ...).

### How to apply

Via Email: lynn.pham@lionrose.biz 

Or Phone/Zalo: 0978 563 759

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
