### ISSUE TITLE
Positive Thinking Company - Sr Golang Developer - HCMC/HN - FT - Hybrid

### ISSUE THREAD

**Issue by Xamnguyen** [awesome-jobs/vietnam#3510]
## Location

* Saigon, Vietnam
* Hanoi, Vietnam

## Salary Expectation

* Offer based on candidate expectation

## Requirements
* B.S. in Computer Science or equivalent experience. 
* Experience with Go in production.
* Solid computer science fundamentals (theory, data structures, algorithms, design patterns).
* Knowledge of networking fundamentals.

## Skills
* Golang
* Go gin, mongodb, elasticsearch
* AWS 
* ETL 

### DESCRIPTION
* Our client is looking for software engineers to work on the backend services that power the mobile apps. Join us in building our high traffic site serving millions of customers per month throughout Southeast Asia. You will be exposed to a polyglot architecture, modern development workflows, and a forward-thinking team dedicated to solving the big picture problems in e-commerce. As a member of the mobile backend team, you will hack on the mobile API and a 
portfolio of microservices to provide the functionality that our customers enjoy. 

### Responsibilities
* Build high performance, well-structured backend services.
*  Research cutting edge technologies and techniques to improve application reliability, developer experience and raw performance

### Contact
Skype: live:.cid.f9a5012fddc93dbe (Xâm Nguyễn) 
Linkedin: https://www.linkedin.com/in/lucianguyenhr/

**Comment by Xamnguyen** [comment]
We are looking for 2 headcounts, please ping me for more informations. Thank you so much!

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
