### ISSUE TITLE
Unity Developer_Remote Working_Full-time

### ISSUE THREAD

**Issue by manhduc77** [awesome-jobs/vietnam#3512]
## Location

* Optional ( Can choose between Remote/ Hybrid/ Office_HN)

## Salary Expectation

* Up to $5000/month

## Requirements
* Position: Project’s Collaborator
* Engine: Unity
* Skill level: Intermediate (4-5 years experience in programming)
* Personal source code with clean code.
* Having basic knowledge of game design.
* Having your own game projects is a huge bonus point.
* Please show every reference to the game projects you had joined to create the end-products and/or your own projects in your portfolio/CV, including links to the games and what you have done for the projects. If the projects are protected by NDA, please include your project supervisor’s contact who will be available to answer the calls from the recruiter.
* Personality at work: straightforward, self-disciplined, and rational-driven thinking.
* Education: Bachelor degree or higher

### Ideally

* Strong problem solving and debugging skills with meticulous attention to detail and
with a diligent mindset.
* Prefer married, having children, sustainable-oriented

### You’ll be responsible for

* Programming.
* Researching and creating tools to optimize productivity.
* We are a small team, be aware of taking roles in development that are not listed above with the deserving benefits.

### You can bring

* A good eyes for design
* A good analysis skill

### Benefits

* Salary from $1300/month - $5000/month
* Working with team from tech-giants overseas, you will learn professional and effective
game development techniques and procedures.
* Making games that will entertain and be recognized by people all around the world.

### Contact
Gmail/ Skype: duc.nguyen@reco-vn.com
WhatsApp/Zalo: 0963269923

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
