### ISSUE TITLE
asinzen - Sr Golang - REMOTE - FT

### ISSUE THREAD

**Issue by m8labsteam** [awesome-jobs/vietnam#3513]
## Location

* Remote

## Salary Expectation

* Up to $2500 Gross

## Skills

* Golang
* Mongodb, elasticsearch
* AWS

## Must Have

* Have a strong experience of Golang
* Be humble and willing to work hard 
* Be able to work independently but also a team player, open-minded.
* Willing to learn new technology, have a product mindset

## Ideally

* Worked with ReactJS applications before
* Have experience of AWS, CI/CD
* Experience with crawling and scraping
* Experience with docker, AWS EKS, auto deploy, setup server
* Mongodb, elasticsearch 

## Our products and services

* [asinzen](https://asinzen.com)

## Why it would be awesome to work with us

* We are a distributed small multi-cultural team
* 100% of the developer are in Vietnam
* We have over 10,000 paying users for our services and been in business for over 5+ years
* Only work from Mon-Fri
* Flexible working schedule on demand. 
* We provide insurance and extra pay

## Contact

Quynh: quynhk@asinzen.com

## Apply

You can apply by email or using this link https://itviec.com/it-jobs/remote-golang-developer-asinzen-0637?lab_feature=employer_job

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
