### ISSUE TITLE
Money Forward Vietnam - Principal Frontend Engineer - HCMC - FT - Hybrid

### ISSUE THREAD

**Issue by nguyentoloan** [awesome-jobs/vietnam#3514]
## Location
* Saigon, Vietnam
* Hybrid working, only 2 days in office

## Salary Expectation
* Offer based on candidate expectation

## Requirements
**Must-Have**
* 5+ year experience in frontend development with 2+ years of experience of leadership
* Expertise in JavaScript, TypeScript
* Solid experience with React and/or Vue.JS
* Solid experience with HTML, CSS (SASS/LESS)
* Hands-on experience with testing frameworks (e.g., Jest, Mocha, Ava)
* Good understanding of common architectural patterns for CSS and JavaScript
* Good knowledge of web security
* Good sense of UI/UX
* Experience with web performance optimization, SEO
* Good English communication skills

**Nice-To-Have**
* Backend development experience (e.g., Golang, Ruby on Rails, Laravel, Express.js, Django)
* Familiarity with CI/CD, Docker, Kubernetes
* DevOps experience with on-premises or cloud computing (AWS, GCP, Azure)
* Japanese skills (N3+)

## Responsibilities
* Analyze requirements, propose and implement solutions for our projects
* Architect and develop shared libraries or frameworks that can resolve complex designs and interactions
* Optimize web applications for maximum speed and scalability
* Troubleshoot UI/UX issues and give suggestions for improvement
* Develop company-wide standards for development processes
* Perform regular technical audit
* Coach and mentor middle/senior developers

## Top reasons to join us
* Hybrid working, flexible time
* Clear career path development
* English working environment 
* Interesting projects
* Competitive salary and benefit package

## Contact
Sunday - 0906 516 291
recruit@moneyforward.vn
Skype: nguyentoloan2009

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
