### ISSUE TITLE
[Plusteam] - [Senior Oracle Database Administrator] - [Ho Chi Minh] - [Remote-FT]

### ISSUE THREAD

**Issue by Tina191807** [awesome-jobs/vietnam#3519]
## Location

* District 2, Ho Chi Minh City, Vietnam
* Remote

## Salary Expectation

* $2500-$4000

## Requirements
* Monitor, operate, and troubleshoot problems in running databases on the cloud

* Monitor and uncover unoptimized database queries and propagate those insights into actionable for the engineering and product team to prioritize fixing.

* Managing database security/integrity and backup procedures

* Maintaining and managing database scalability and performing capacity planning

* Ensure schema designs are scalable to deal with large transactions in the next 2 years.

* Strong understanding of database design, backup, security, and disaster recovery
 
* Good knowledge of performance management and application or database tuning;
 
* Meticulous and ability to identify errors and potential risks
 
* Plan proper DB partitioning for better/consistent insert/query performance, and archiving requirements without downtime.
 
* Proper sync mechanism to duplicate prod data to dev DB

## Responsibilities
* Knowledge of MYSQL or PostgreSQL

* Knowledge of Redis

* Knowledge of Oracle DB is a big plus

* Knowledge of scripting or coding is a big plus

## WHY YOU WILL LOVE WORKING HERE?
Being a member of us, you will experience a youthful, flexible and creative work environment

* Onsite Singapore opportunity.

* Attractive salary and annual salary review

* Working in a professional, friendly, well-equipped environment both with foreigners and Vietnamese

* Extensive on-the-job training, you will always have a chance to work with new emerging technologies

* Full social insurance, health insurance & unemployment insurance according to Vietnam Labor Law.

* Annual Wage Supplement: 1x Basic salary (pro-rated if you join us for less than the full 12 months), to be paid out in December yearly

* Variable Performance bonus: 0 - 3 months (based on individual & company performance)

* Annual leaves: 18 days

* Medical leaves, Hospitalisation leaves: 14, 60 respectively

* Laptop & Equipment Purchase Reimbursement.

* A good analysis skill

### Contact
Gmail: recruit@plusteam.io
Skype: dangthao13112001@gmail.com
Linkedin: www.linkedin.com/in/đặng-thị-phương-thảo-aa0ab21bb

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
