### ISSUE TITLE
HN - WGAME - Senior Unity 3D Developer

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3522]
## Location

* Yên Hoà Sunshine, số 9 Vũ Phạm Hàm

## Salary Expectation

* upto $2000 net (senior)
* upto $1000 net (junior)

### JOB DESCRIPTION

Xây dựng và phát triển dự án Game PC MMORPG;
Xây dựng và phát triển các dự án Game mobile trên nền tảng Unity cho Android và iOS;
Xây dựng và triển khai kiến trúc hệ thống game (game architecture design);
Cùng team lên ý tưởng và giải pháp cho các tính năng mới của game;
Sửa lỗi và cải thiện tính năng, hiệu suất trò chơi;
Phối hợp với các thành viên trong team để vận hành và tối ưu hoá sản phẩm;
Tham gia quá trình xây dựng team dev; chia sẻ và phát triển chuyên môn dev của công ty.

### REQUIREMENT
Senior:
Ít nhất 3 năm kinh nghiệm Unity 3D, đã tham gia các dự án game 3D, Có sản phẩm game hoàn thiện đã release;
Có kinh nghiệm tham gia các dự án Client/Server, các dự án game Multiplayer
Có khả năng đọc hiểu tài liệu bằng Tiếng Anh là 1 lợi thế;
Sử dụng tốt GIT là 1 lợi thế
Junior:
Có 1 năm kinh nghiệm Unity3D, đã có sản phẩm game hoàn thiện
Có kiến thức tốt về thuật toán, cấu trúc dữ liệu và lập trình hướng đối tượng, Design Pattern.

### BENEFITS

Tham gia vào gia đình Wild Thunder, bạn sẽ có được:
Một môi trường làm việc sáng tạo, năng động và trẻ trung; đồng nghiệp thân thiện, hòa đồng và hỗ trợ nhau cùng phát triển;
Cơ hội tham gia xây dựng các dự án game blockchain (NFT) ở giai đoạn đầu;
Văn hóa học hỏi không ngừng, trau dồi kỹ năng chuyên ngành, kỹ năng mềm và tiếng Anh;
Các hoạt động team-building và sự kiện vô cùng hấp dẫn của công ty trong năm;
Mức lương cạnh tranh theo năng lực; hưởng đầy đủ chế độ bảo hiểm theo quy định Nhà nước;
Lương tháng thứ 13; đánh giá lương định kỳ 6 tháng, cùng thưởng Tết và thưởng theo dự án
Trợ cấp gửi xe, luôn có đồ ăn nhẹ, đồ uống miễn phí;
Công ty trang bị đầy đủ công cụ làm việc hiện đại phù hợp với tinh chất công việc.

INTERVIEW PROCESS
1 vòng

### Contact
Skype: Huehuenoivu
Zalo/Tele: 088 600 5769

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
