### ISSUE TITLE
[ SmartDev ] Middle/Senior .NET Engineer

### ISSUE THREAD

**Issue by caocuong2404** [awesome-jobs/vietnam#3525]
![SmartDevLLC](https://user-images.githubusercontent.com/50004497/185291524-1d3210f5-da42-49fb-b304-c1ced4700443.jpeg)

Location
-------------------

81 Quang Trung, Thạch Thang, Hải Châu, Đà Nẵng 550000, Vietnam

Salary Expectation
-------------------
$1100 - $2000 NET/month

Company Description
-------------------

*   SmartDev is a leading provider of global software solutions. The company was established in 2014 and is a wholly owned subsidiary of Verysell Technologies Group (Switzerland).
*   SmartDev combines renowned Swiss quality with the Vietnamese passion for providing excellence and value. We bring together smart people both internally and externally to create partnerships that push boundaries and challenge the status quo.
*   As part of SmartDev’s aggressive growth plan we are looking to expand our development team; we (https://smartdev.com/) offer tailor-made mobile apps and websites with the most popular front-end and back-end technologies. We are currently working with about 150+ developers.

Job Description
---------------

*   You will report to PM (Project Manager)
    
*   Collaborate with teams to produce software design and architecture
    
*   Write clean, scalable code using .Net programming languages
    
*   Test and deploy application and systems
    
*   Revise, update, refactor, and debugs code
    
*   Develop documentation throughout the software development life cycle
    
*   Participate in code reviews
    
*   Train fellow colleagues
    

Qualifications
--------------

*   Proven 3+ years of work experience as a .Net Developer
    
*   Be familiar with ASP.NET framework, SQL Server, and design/ architectural patterns
    
*   Knowledge of .Net languages (C#, Visual Basic .Net), and HTML5/ CSS3
    
*   Be familiar with architecture styles/ APIs (REST, RPC)
    
*   Experience in JavaScript/ TypeScript, NodeJs, ReactJs, AngularJs or similar frontend frameworks
    
*   Experience deploying to Azure/ AWS (CI/ CD)

*   Fluent English communication skills
    

Additional Information
----------------------

_**Benefits:**_

*   Good work environment and good colleagues (parties, holidays, team building activities)

*   Free Kindergarten for staff’s kids

*   13th salary

*   Extra Healthcare

*   Lunch Allowance

*   Tea, coffee, milk

*   Work on the latest technology

*   Two-day weekend: Sat and Sun

*   20 annual leave days alongside Vietnamese public holidays

*   Always new challenge (Training provided)

*   Self-organize project team

*   Work with high-profile multinational companies

*   Competitive Salary and career evolution based on your performance defined every year

Contact
----------------------

*   Email: cuong.nguyencao@smartdev.com

*   Skype: **caocuong2404**

*   Website: [SmartDev.VN](https://smartdev.com/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
