### ISSUE TITLE
[ SmartDev ] Automation QA Engineer

### ISSUE THREAD

**Issue by caocuong2404** [awesome-jobs/vietnam#3526]
![SmartDevLLC](https://user-images.githubusercontent.com/50004497/185291524-1d3210f5-da42-49fb-b304-c1ced4700443.jpeg)

Location
-------------------

81 Quang Trung, Thạch Thang, Hải Châu, Đà Nẵng 550000, Vietnam

Company Description
-------------------

SmartDev is a leading provider of global software solutions. SmartDev was established in 2014 and is a wholly owned subsidiary of Verysell Technologies Group (Switzerland).  

SmartDev combines renowned Swiss quality with the Vietnamese passion for providing excellence and value.  SmartDev brings together smart people both internally and externally to create partnerships that push boundaries and challenge the status quo. 

As part of SmartDev’s aggressive growth plan, we are looking to expand our development team

SmartDev (https://smartdev.vn/) offers tailor-made mobile apps and websites with the most popular front-end and back-end technologies. We are currently working with about 45 developers.

Job Description
---------------

*   Participate in technical discussions within the Engineering team and across functions
*   Design and Develop test cases for new features
*   Develop tools and libraries to help with automating Test cases
*   Write new features and enhancements for the Automation Framework
*   Troubleshoot CI failures and identify the root cause for Test failures
*   Identify and automate manual test processes to improve team efficiency

Qualifications
--------------

*   2+ years of experience programming in Automation skills (for any languages)
*   Experience with Test Automation Frameworks and Test Driven Development (TDD)
*   Experience with GitHub, Jenkins, CI build systems, and Automated Testing
*   Experience with Agile Software Development practices
*   Familiarity with Linux or other Unix-like Operating Systems with the ability to troubleshoot basic network issues (an optional)
*   Experience with Kubernetes and Cloud services (AWS/Azure/GCP) (an optional)
*   English communication

Additional Information
----------------------

**Benefit:**

*   Good work environment and good colleagues (parties, holidays, team building activities)

*   Free Kindergarten for staff’s kids

*   13th salary

*   Lunch Allowance

*   Tea, coffee, milk

*   Work on the latest technology

*   Two-day weekend: Sat and Sun

*   20 annual leave days alongside Vietnamese public holidays

*   Always new challenge (Training provided)

*   Self-organize project team

*   Work with high-profile multinational companies

*   Competitive Salary and career evolution based on your performance defined every year

Contact
----------------------

*   Email: cuong.nguyencao@smartdev.com

*   Skype: **caocuong2404**

*   Website: [SmartDev.VN](https://smartdev.com/)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
