### ISSUE TITLE
Tech Outpost - Ruby developer - Saigon - FT

### ISSUE THREAD

**Issue by RobDoan** [awesome-jobs/vietnam#353]
![Tech Outpost](https://s3.amazonaws.com/temp.neverland/techoutpost-logo.png)

A website is not just a mash up of graphics and words, it is the gateway to your business and it tells your story, brand and vision. First impressions matter, and we believe in making it count. At Tech Outpost, we don’t just build websites, we create memorable experiences that communicates the essence of your brand.
We’re a team of dreamers, storytellers and brainiacs, coming together to help you change the world.
## Location
- Saigon, Vietnam
## Salary Expectation
- negotiable
## Requirements
- Strong understanding of object-oriented programming principles.
- Basic understanding of front-end technologies, including JavaScript, HTML5, and CSS3.
- Familiarity with MVC, Mocking, ORM, and RESTful principles and best practices.
- Understanding of fundamental design principles behind a scalable application.
- Ability to implement automated testing platforms and unit tests.
- Proficient understanding of code versioning tools such as Git, Mercurial, or SVN.
- Familiarity with continuous integration.
- Be willing to help your teammates, share your knowledge with them, and learn from them.
## Skills
- Ruby (or Python, PHP, Elixir, etc)
- Mysql, Postgresql, Casandra
- HTML, CSS and JavaScript
- Nginx, Thin, Passenger, Unicorn, Puma
- Vagrant, Docker, AWS, ..
- Git
### Responsibilities
- Design, build, and maintain efficient, reusable, and reliable Ruby code.
- Integrate data storage solutions, including databases, key-value stores, blob stores, etc.
- Integrate user-facing elements built by your front-end developer teammates with server side logic.
- Identify bottlenecks and bugs, and devise solutions to these problems.
- Help maintain code quality, organization, and automation.

### Benefit

- Benefits include the opportunity to join a fast growing company, where you can grow professionally and build a strong career.
- 12 PAID days off a year.
-  Macbook pro laptop or PC laptop.
- Relaxing room with electronic soft-tip dartboard and many game boards.
- Free-snacks and beverages.

### Contact

Quy Doan: hr@techoutpost.co
Website: www.techoutpost.co

**Comment by dungphanx** [comment]
@RobDoan sorry, I just mail for hr@techoutpost.co but google feedback this email not exists. 
could you check your email again?

**Comment by RobDoan** [comment]
Thank you, @dungphanx. 
Sorry the group email was not set up properly

**Comment by rubyrider** [comment]
Do you offer visa sponsorship ? Remote allowed?

**Comment by RobDoan** [comment]
@rubyrider: I am sorry, we only hire local. Thanks.
