### ISSUE TITLE
LINE VietNam - Backend Engineer - Saigon, District 10 - Fulltime

### ISSUE THREAD

**Issue by ngthtung** [awesome-jobs/vietnam#3531]
## Location

* Saigon, Vietnam

## Salary Expectation

* Market-Competitive and very attractive

## Requirements
* At least 3 years (or equivalent) experience in Java Enterprise
* In-depth experience in designing, developing, testing and deploying backend API across development
environments DEV, TEST, STAG and PRODUCTION
* Experience in Server Architecture Design for handling massive traffic.
* Experience in Cloud-based, Containerized application development
* Deep knowledge and experienced in Object-Oriented programming and applying Design Patterns.
* Experience in Web Development using Spring/Spring Boot framework
* Experience in constructing & operating storage in Large Data Distributed Environments (MySQL, Hadoop,
HBase, Redis, MongoDB)
* Experience in Data Structure, Algorithm, Distributed Service
* Experienced in merging, branching source code using a distributed VCS such as GIT, BitBucket,
SourceTree etc
* Experienced in System Analysis & Design, n-Tier Architecture, Micro Service Architecture is a PLUS
* Good at communication skills in general and English

### Responsibilities

* Being a part of Global LINE Development you will contribute to the development of LINE’s offers and
services
* Kick-start the development of new products for LINE users in Vietnam
* Take responsibilities in developing for any future products for Vietnam market
* Show initiatives and demonstrate ownership of the product by suggesting new features and provide
insights during product development
* Work closely with fellow global LINE engineers in other countries
* Promote company’s reputation as “best place to work”

### Contact
Send your CV to email: tungnt@linecorp.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
