### ISSUE TITLE
CXP - Product Owner - Up to $3,000 - HCM - Full-time

### ISSUE THREAD

**Issue by jadel04** [awesome-jobs/vietnam#3532]
## Location
* Botanica Premier Apartment, Block A2, 102 Hồng Hà, Tân Bình District, HCMC, Vietnam

## Salary Expectation
* up to 3,000$/month

### Must Have
* BS/MS degree in computer science, software engineering, finance/banking, or a related field
* 3+ years of experience as product owner/product manager/business analyst
* 3+ years of experience in software development
* Experience in managing multiple products simultaneously
* Solid organizational skills and hands-on multitasking
* Experience in agile development teams, such as Scrum, Kanban
* Interested in dealing with complex challenges and keen on exploring new things
* Good problem-solving skills and teamwork spirit
* Strong communication skills to effectively collaborate with other developers and stakeholders
* Experiences in blockchain or Defi/fintech projects will be a strong plus

### Responsibilities
* Work with senior management to create product strategy and roadmap;
* Focus on user experience (UX) to ensure solutions are engaging and highly adopted by customers;
* Using modern tools to manage product backlogs, release backlogs, and measure team performance
* Work collaboratively with engineers and cutting-edge technologies;
* Analyze users' data and feedback to measure the product's effectiveness and make necessary adjustments.

### Why it would be awesome to work with us
* We are a young, lean, and strong team
* We build a professional & fun working environment.

###About Us
CXP is Digital Asset Exchange, predominately used for trading cryptocurrencies, and is looking for a new developer to join its HCMC-based team.

Contact
Email: [hr@cxptek.com](mailto:hr@cxptek.com)
Phone: (+84) 38 4498 899 (Jade)

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
