### ISSUE TITLE
GEEK Up - Product Backend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by thinhvoxuan** [awesome-jobs/vietnam#3534]
## Location

* Saigon, Vietnam

## Salary Expectation

* 1000 - 2000 USD/Month

## Requirements

* Have 2-5 years of Backend programming experience (using NodeJS/ PHP/ Go/ Java)
* Show solid computer science fundamentals (theory, data structures, algorithms, design patterns)
* Have systematic thinking and good critical-thinking skill.
* Have passion for exploring new technology research
* Show good teamwork ability to coordinate with team members
* Be ready to research technical documents in both English and Vietnamese

## Responsibilities
* Build high performance, well-structured backend services. Produce high-quality maintainable & testable code
* Design and develop robust APIs and tools based on customer needs for mobile app and frontend web
* Architect product and core infrastructure with long term reliability, scalability, and security in mind
* Learn new technologies, languages, and techniques so that you are able to adapt to the requirements of the project
* Engage in continuously deploying and scaling back-end services in Cloud Infrastructure as well as performance analysis, tuning and optimization
* Coordinate with cross-function teams in 4 stages including planning, implementation, deployment and operations
* Propose solutions and fixing problems encountered during development and operations

### Why it would be awesome to work with us
* Weekly Technical, Soft-skill Workshops & other customize activities;
* Young and dynamic working environment;
* 13th month salary and unlimited salary increments review per year;
* Laptop & work tools are supported according to the demand of the job;
* 3 company trips/ year (domestic and international);
* Having the right to purchase shares of the company;

### Contact
* Please contact our HR via email anh.ht@geekup.vn or send your profile to adventure@geekup.vn 
* Our website https://geekup.vn/ and https://geekadventure.vn/opportunity/backend-development

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
