### ISSUE TITLE
NatureEye - Backend Engineer - Remote - FT

### ISSUE THREAD

**Issue by talobin** [awesome-jobs/vietnam#3535]
## Location

* Remote

## Salary Expectation

* From 1000 to 4000USD/Month. Based on skill.

## Intro

Have you heard of Sequoia Capital, the venture capital that funded Apple, Instagram, Stripe, Airbnb, Zoom, and much more? NatureEye is their newest and fast-growing funded Silicon Valley tech startup. We are building a service to offer remote ecotourism using drone (fly-cam) technology. We are about to launch our private beta version with touring sites including the most famous parks and the best tourist attractions worldwide. 
 
NatureEye uses DJI drones for our service. DJI is the company that makes 90% of the drone in the world. Their Director of R&D, [Hai Vo,](https://www.linkedin.com/in/talobin/) is now our Director of Engineering. At DJI, Hai was the one that built the DJI Office in Silicon Valley, California. At NatureEye, Hai now is building our engineering team in his home country, Vietnam.

## Our current stack (not too committed to):

* Server: AWS, Terraform, Postgres, Typescript, AUTH0
* Client: React, Typescript, Twilio, Axios, NodeJs
* Mobile: Java,Kotlin, React Native 

### Must Have

* 2+ years of experience building web applications and consuming APIs
* Comfortable with Frontend tasks using HTML, Javascript, CSS, Bootstrap
* Ability to work in a team with experts from other fields.
* Ability to communicate ( verbal and written) in English.
* Ability to determine, develop, and document best practices
* Experience with version control software (git and GitHub)
* Deep knowledge of database architecture, and experience with database schema design and SQL syntax.
* Ability to give, receive and adapt to tactful feedback through code reviews, refinements, and everyday collaboration
* Analytical skills and teamwork skills with a problem-solving attitude

### Ideally

* Experience with all or some of the technologies we used for the server (mentioned above)
* Experience with all or some of the technologies we used for clients (mentioned above)
* Experience working with Video/Audio

### Huge plus

* Experience working with Drones
* Experience working with Agora
* Experience working with Twilio

### Responsibilities

 This is for the second Web team member for NatureEye in Vietnam. We are looking for an experienced Backend developer with some Frontend ability. The new member will be eventually taking over all the work as our first member is taking a career break in over a month. This member will be working alongside our mobile team and also a web consultant team in the US that we have been working with since the beginning. 

### You will be responsible for

 We have finished the private Beta round. The next step for development is to take the product to public Beta.

### Contact
Homepage: [NatureEye](https://www.natureeye.com/)
Email: hai.vo@natureeye.com

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
