### ISSUE TITLE
Sisu Network - Senior Golang Dev - Remote - FT

### ISSUE THREAD

**Issue by visopsys** [awesome-jobs/vietnam#3536]
## Location

* Remote

## Salary Expectation

* $2000-$4000
* Generous Token Allocation

## Requirements

We are a blockchain startup that build universal private transactions (works even for Bitcoin, Cardano, Ethereum, etc). We are looking for great engineer to join us and build robust protocol to serve our ultimate goal.

### Must Have

* Have strong system design skills. Familiar with golang (90% of our code is written in Golang).
* Worked with big and complex system before.
* Good work ethnic, always goes beyond job's requirement to take the lead of project
* Having knowledge about how Ethereum works is a big plus.

### Ideally
* Having competitive programming background is a big plus (but not required)
* Won IOI medal or participated in ACM ICPC world final or red ranking on Topcoder/CodeForce before 
* Solve complex problems before (e.g. build a database from ground up or architect a system that serves 10M/s)
* Understand how Ethereum works
* Work with Golang full-time for at least 2 years

### Responsibilities

*  Writing clean & high-quality code
* Maintain & improve running- functionality as well as design and develop new system, new feature if needed
* Deliver end-to-end, including unit test, integration test and deployment to PROD
* Participate in code reviews

### You can bring

* Good work ethnic 
* Ability to solve complex problems & build complex system

### Why it would be awesome to work with us

* Competitive salary
* Work with great team (founder is also a senior engineer & ex-Googler)
* Cutting edge technology in blockchain and cryptography (Threshold Signature & Zero Knowledge Proof)
* Awesome team. Opportunity to visit Silicon Valley.

### Contact

* benja@sisu.network

**Comment by lactroi** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
