### ISSUE TITLE
Ruby on Rails / Angular JS Wanted

### ISSUE THREAD

**Issue by namtran0110** [awesome-jobs/vietnam#354]
## Location

* Saigon, Vietnam

## Salary Expectation

* 8,000,000 vnd for the whole project: 2 months

## Requirements
* Ruby on Rails or Angular JS 

### You’ll be responsible for

* Building an e-commerce platform for food industry

### You can bring
* A good eyes for design
* A good analyis skill

### Contact

Nam Tran: namtran0110@gmail.com (0913644270)

**Comment by joneslee85** [comment]
The post does not comply with our guideline. Furthermore the content is pretty poor. I am closing it.

**Comment by trankimhieu** [comment]
Hi @namtran0110 
Building an e-commerce platform for the food industry with $400 and 2 months. It seems that you do not respect developer time and effort enough. I totally understand that you are running a startup project and don't have much money to pay well.
Truth hurts but invest more and get more. I think you understand this simple rule.
