### ISSUE TITLE
Ruby on Rails / Angular JS Wanted for Sili project -Freelance- Saigon

### ISSUE THREAD

**Issue by namtran0110** [awesome-jobs/vietnam#355]
![logo](https://cloud.githubusercontent.com/assets/11750306/19755509/b28453e2-9c40-11e6-9cfd-c7b4e013f4ed.jpg)

##  Sili Sili project:
* Creating a platform that enable cooks to present their products and sell it to the customer. 

## Location

* Saigon, Vietnam

## Salary Expectation

* 8,000,000 vnd for the whole project: 2 months

## Skills
* Ruby on Rails/Angular JS using Meteor Framework

## What you will do
* Login/Signup with Facebook
* Order
* Review & Ranking
* CMS for cook
* Live notification
* Merging the front end with backend
* Maintain the website

### Extra Offer
* Flexible working time
* Joining contest to fund startup:
Scientific and Technological Department contest: 2 billion VND
VietChallenge: $2,000 - $20,000

### Contact

Nam Tran: namtran0110@gmail.com

**Comment by trankimhieu** [comment]
Hi @namtran0110 
Building an e-commerce platform for the food industry with $400 and 2 months. It seems that you do not respect developer time and effort enough. I totally understand that you are running a startup project and don't have much money to pay well.
Truth hurts but invest more and get more. I think you understand this simple rule.

**Comment by huydx** [comment]
hi @namtran0110 , this job-board purpose is not for some kind of short-term, low income freelance job like this. So I would like to close the job.
