### ISSUE TITLE
Gamify Studios - NodeJS Backend Engineer - Ho Chi Minh/Vietnam - FT

### ISSUE THREAD

**Issue by khaiphan** [awesome-jobs/vietnam#3552]
## Location

* Saigon, Vietnam

## Salary Expectation

* Junior: Up to 1500$
* Senior: Up to 2200$
* Or higher if you can perform outstandingly at the interview.

### Must Have

* 2+ years of experience in Back-end Development
* Proficient with **NodeJS/JavaScript/TypeScript**.
* Proficient with **SQL**.
* Proficient with GIT.
* Have a **Good product mindset**.
* Have a **Good teamwork spirit**.
* Familiar with Agile Methodology.

### Ideally

* Experienced with Redis
* Experienced with RabbitMQ
* Experienced with Elastic Search
* Experienced with Docker/K8S
* Experience in developing game server systems.
* Willing to learn new programming languages, and new technologies.
* Adapt to high pressure at work.

### You’ll be responsible for

* Design/Build high performance, scalable, testable and maintainable APIs based on given requirements.
* Ensure the assigned tasks to be performed on-time and with high quality.
* Collaborate effectively with Business Analysts, QC and Front-end Engineers.
* Participate in architecture design/code review.

### Why it would be awesome to work with us

* Working in a professional, friendly, well-equipped office.
* Attractive salary and annual salary review.
* Full social insurance, health insurance & unemployment insurance according to Vietnam Labour Law.
* 12-day annual leave per year.
* 13th-month salary.
* Performance bonus.
* PVI Health Care.
* Enjoy diversified activities: Monthly Team-building, Company trip, Play Games (PlayStation, Board Games, etc...)

### Contact
Email: khaiphan@gamifystudios.co
Skype: khai.phan25
Phone: +84986868895

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by khaiphan** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

Sorry, my bad. Just update the new email address.

**Comment by khaiphan** [comment]
> Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.
> 
> In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.
> 
> Thank you and have a good day!

Do you need any more information to re-open this post? Or do I need to create a new issue?

Thank you!
