### ISSUE TITLE
1PAC Vietnam - Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by wofi-minh** [awesome-jobs/vietnam#356]
### Location

* 6F, 244 Cong Quynh, Dist.1, Ho Chi Minh City

### Salary Expectation

* Negotiable

### Skills

* 2 years working experience with Ruby ( Ruby on Rails ) or PHP ( Laravel, Symfony, CakePHP... )
* Solid understanding of object-oriented programming
* Knowledgeable in database - SQL / RDBS, Memcached
* Knowledge of configuring LAMP enviroment
* Experience with Source Version control: Github, Subversion (SVN)
* Experience with HTML5, CSS, SASS/LESS, Javascript ( backbone.js, jquery... )
* Experience with AWS stack is a plus

### You'll be responsible for

* Design and build web application and REST API
* Setup and manage server
* Plan and document technical specifications for features or system design
* Maintain and optimize existing code

### More about us

* Website: http://1pac.vn
* Facebook: https://www.facebook.com/1pacvietnam/

### What we can offer you

* Directly working and learning from senior Japanese engineer in head office
* Personal Macbook PRO
* Free snacks and drink
* Parties and gifts for special events (birthday, Christmas, Tet)
* Company trip 2 times/year
* Dinner and lunch party every month
* Educational programs (Japanese class, business trip in Japan...) 

### Contact

redstar.thao@1pac.vn (Ms.Thao) (phone: 08-3925-0000)

**Comment by joneslee85** [comment]
@wofi-minh can you please add a section intro about your company, what sort of work you do, etc. Cheers

**Comment by joneslee85** [comment]
No amendment after 2 days. Closed.
