### ISSUE TITLE
[HN] FRESHER JAVA - BONUS 2M FOR REFERRAL

### ISSUE THREAD

**Issue by maile188** [awesome-jobs/vietnam#3568]
Hi everyone, 
To prepare for the upcoming project, our DTS customer needs to recruit more Java teammates with the information as following:
- Salary: Up to 20M; Referral Bonus: 2M
- Participating in large projects of Japanese customers in the fields of finance-banking, logistics, administration, operation management,...
- Closely trained by mentors
- Only required: 1y+ Java Spring Boot experience and study in the right major
Referrers or candidates please contact me for enthusiastic support!
Phone: 0964287302
Email: ltmai.work@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
