### ISSUE TITLE
Python Developer (Django, Flask)

### ISSUE THREAD

**Issue by Thusky68** [awesome-jobs/vietnam#3570]
## Location

* 82 Dich Vong Hau, Cau Giay, Hanoi, Vietnam
* Full-time

## Salary Expectation

* $1300-$2500

## Requirements
* Python (Django, Flask)
* Web Development (HTML, CSS, JS)
* ActiveMQ, RabbitMQ, Kafka, Beanstalk, SQS, etc...
* Cache technologies such as Memcached, Redis
* AWS
* 3+ years Software Engineering experience

### Must Have

- Hands-on 3+ years of experience in developing complex projects, preferably in the communications domain, in Python (Django and Flask Frameworks).
- Hands-on experience in Web Development (HTML, CSS, JS).
- Practical experience in queuing systems/message brokers like ActiveMQ, RabbitMQ, Kafka, Beanstalk, SQS, etc...
- Practical experience with cache technologies such as Memcached, Redis.
- Solid experience in managing Linux servers and applications (Nginx, apache2, etc...).
- Proficiency in a Linux environment and in consuming and designing RESTful APIs.
- Solid experience with full Software Development Lifecycle, Distributed Architectures (REST, SOAP, Queue-based), and Microservices Architecture.

### Nice to have

- Familiarity with software project management tools similar to Agile, Maven, and Git.
- General knowledge in telecommunications (SMSC, VOIP, SMPP, etc.).
- Experienced with using cloud hosting technologies such as AWS.
- Familiar with SaaS and PaaS integration architecture and applications.
- Strong problem-solving and analytical skills.
- Excellent communication skills.

### Responsibilities

- Build and maintain solutions that scale. Serving millions of users every day.
- Contribute to building and maintaining the policies, procedures, and technical assets in Unifonic’s cloud infrastructure.
- Support various teams with a technical vision in the core areas of interest for Unifonic's products.
- Support multi-cloud-based communication products, especially as an augmentation to the internal technology team and working with partners’ software development teams.
- Work on cloud-based development and deployment, including the following: AWS (EC2, SQS, S3, RDS, Aurora).
- Work closely with service delivery teams to support product deployments to the cloud.
- Understand and use Unifonic's technical architectures, tools, and techniques to build powerful, efficient, flexible, and scalable solutions.
- Ability to perform basic database administration, performance optimization, index optimization, write advanced select queries, and replace cursor usage with relational SQL.
- Collaborate with product owners, scrum masters, and other developers to deliver a quality product using tools such as JIRA and Git.

### Why it would be awesome to work with us

- Agile teams, good teamwork, and a professional working environment. 
- Possibility to develop your career within an international company. 
- We are a global company, with many offices and projects all over the world (you have the opportunity to work onsite in one of our 13 offices on 3 continents). 
- We provide a professional roadmap, support, and onboard training. 
- Free technical learning courses, foreign language courses (English, French). 
- Enjoy interesting activities: Coding challenges, PentaBAR, Hackathon etc. 
- 100% of the salary is paid during the probation period. 
- Attractive salary and bonuses. 
- Social insurance payment is based on the full salary to keep your full benefits. 
- A premium healthcare package (Bao Viet 24/7 health insurance package + an annual health check-up). 
- Flexible working hours, no fingerprint timekeeping. 
- Working days: 5 days/week: from Monday to Friday (We don't encourage working overtime, as we value our colleague’s personal time). 
- Paid annual leave: 26 days (11 holidays +15 vacation days). 
- Providing equipment: devices and subscriptions used for work (Laptop, Case, Smartphone...). 
- Enjoy bonding activities like team building, summer holiday, Christmas party, happy hour etc. 

### Contact
Email: ttranthile@pentalog.com
Skype: tranthilethu890@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
