### ISSUE TITLE
REFERRAL (BONUS 2M)

### ISSUE THREAD

**Issue by maile188** [awesome-jobs/vietnam#3571]
## Location

* Hanoi, Vietnam

## Salary Expectation

* Up to 20M/month 

## Requirements
* 1y+ Java Spring Boot experience study in the right major
* study in the right major

### Responsibilities

Participating in large projects of Japanese customers in the fields of finance-banking, logistics, administration, operation management,...

### Contact
Phone: 0964287302
Email: ltmai.work@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
