### ISSUE TITLE
SCRUM MASTER_apply/ referral (BONUS 6M)

### ISSUE THREAD

**Issue by anhthuvu129** [awesome-jobs/vietnam#3573]
## Location

* Danang, Vietnam

## Salary Expectation

* $1200-$2500/month

## Requirements
* Experience in playing the Scrum Master role for at least one year for a software development team that was diligently applying Scrum principles, practices, and theory.
* Highly proficient in spoken and written English skills
* Good knowledge of Software Testing Technique.

### Ideally
* Certified Scrum Master is a plus
* Good knowledge of Software Testing Technique.

### You’ll be responsible for

* Responsible for promoting and supporting Scrum by helping everyone understand Scrum theory, practices, principles, and values.
* Ensure that the Scrum process works well and properly.
* Coach the team on how to use Scrum practices and values to delight customers.

### Why it would be awesome to work with us
* 05 working days/week (From Monday to Friday), applying flexible working hours
* 2 -3 days of remotely WFH per week (based on team's decision)
* Lunch + Gasoline + Coffee Allowance
* Health, Social and Unemployment Insurance (based on gross-based salary, according to Labor Code) and PVI Health Insurance
* 13th-month salary and Performance bonus

### Contact
Mobilephone: 0868900902
Email: thuva.lcc@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
