### ISSUE TITLE
Talent Acquisition Manager_APPLY/ REFERRAL (BONUS 8M)

### ISSUE THREAD

**Issue by anhthuvu129** [awesome-jobs/vietnam#3574]
## Location
* Danang, Vietnam

## Salary Expectation
* $1600-$2000

## Requirements
* Experience in leading teams, making action plans, and ensuring strategic running.
* Experience in Agile/Scrum process and methods

### Must Have
* Minimum 05 years of experience working in HR Tech Recruitment/Talent Acquisition in IT companies
* Strong communication skills (Vietnamese, English)

### Ideally
* Have hiring experience in Japanese IT company, especially high-level positions.

### Responsibilities
* Talent Acquisition (50%)
* Talent Retention and Employee Engagement (30%)
* People Growth (20%)

### Why it would be awesome to work with us
* 05 working days/week (From Monday to Friday), applying flexible working hours
* 2 -3 days of remotely WFH per week (based on team's decision)
* Lunch + Gasoline + Coffee Allowance
* Health, Social and Unemployment Insurance (based on gross-based salary, according to Labor Code) and PVI Health Insurance
* 13th-month salary and Performance bonus
* Annual salary review
* 12 days annual leave plus extra 02 days company leave

### Contact
Phone: 0868900902
Email: thuva.lcc@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
