### ISSUE TITLE
BoardPackager - RoR Lập Trình Viên - Hybrid/Hanoi - FT

### ISSUE THREAD

**Issue by anhha7** [awesome-jobs/vietnam#3576]
## Location (Địa điểm)

* Hanoi, Vietnam
* Hybrid (2 ngày làm từ xa 1 tuần)

## Salary Expectation (Lương)

* $2000/month hoặc tuỳ theo khả năng

## Requirements (Bạn là người)

* Thành thạo trong mọi lĩnh vực lập trình bao gồm front end, back end và dev-ops
* Không nản khi gặp khó khăn và sẵn sàng học hỏi kiến thức mới
* Cầu toàn với sản phẩm mình tạo ra nhưng vẫn có thể đưa ra những giải pháp thực tiễn để đảm bảo tiến độ công việc
* Có khả năng và chủ động đứng đầu dự án nhưng vẫn có thể trợ giúp dự án khác khi cần thiết
* Luôn luôn đặt trải nghiệm của người sử dụng phần mềm lên hàng đầu
* Tiếp thu góp ý một cách tích cực. Chú trọng vào lợi ích nhóm hơn bảo vệ ý kiến cá nhân
* Luôn luôn có tinh thần học hỏi và nâng cao kiến thức

## Must Have (Bạn cần có)

* Tốt nghiệp đại học chuyên ngành công nghệ máy tính, công nghệ thông tin hoặc các ngành khác liên quan đến lập trình
* Kiến thức rộng về xây dựng cấu trúc, xây dựng và duy trì APIs/Web ứng dụng với tinh phức tạp cao
* Kiến thức sâu về cấu trúc dữ liệu 
* **Hơn 3 năm kinh nghiệm làm việc sâu và rộng với Ruby on Rails**
* Thành thạo SQL
* Kinh nghiệm làm việc với modern javascript framework, React
* Kinh nghiệm làm việc với cloud-based infrastructure (AWS)
* Có kinh nghiệm chạy containerized applications
* Tiếng Anh khá là một lợi thế nhưng không bắt buộc

## Ideally (Yêu cầu thêm)

* Kinh nghiệm làm việc với Elasticsearch / Opensearch and Redis
* Kinh nghiệm làm việc với container orchestration, xây dựng các quy trình, integration và deployment thường xuyên
* Kinh nghiệm làm việc với bất kì hệ thống trả qua mạng nào (Stripe, Braintree, Paypal, etc)

## Responsibilities (Bạn sẽ)
* Phụ trách chính cho quá trình xây dựng của các tính năng và các sản phẩm mới
* Trở thành chuyên gia của công ty trong những mảng mà bạn đảm nhiệm
* Đưa ra những sáng kiến hữu ích để khắc phục code cũ cũng như tham gia vào việc kiểm tra code và xây dựng sản phẩm 
* Hỗ trợ công đoạn xây dựng quá trình testing phần mềm 
* Trở thành một thành viên nhiệt huyết của đội lập trình toàn cầu
* Luôn luôn nâng cao khả năng chuyên môn 
* Quản lý và đào tạo kỹ sư chưa có nhiều kinh nghiệm

## Why it would be awesome to work with us (Lợi ích hấp dẫn)
* **No micromanagement**
* Cơ hội thăng tiến và tăng lương thường xuyên
* Cung cấp máy tính laptop
* Lương thưởng tháng 13
* Bảo hiểm
* 14 ngày nghỉ thêm nghỉ ốm và các ngày lễ tết 
* Tiệc công ty vào ngày lễ tết
* Hoạt động ngoại khoá  (xem thể thao, dã ngoại, etc.)
* Văn phòng công ty 3 tầng mới với đầy đủ tiện nghi
* Đồ ăn nhẹ trong giờ
* Game room
* Môi trường làm việc thân thiện và luôn luôn đặt nhân viên lên hàng đầu

## Interesting engineering projects (Dự án)
BoardPackager là công ty hàng đầu trong lĩnh vực phần mềm công nghệ giao dịch bất động sản tại Mỹ và đang cần mở rộng kinh doanh toàn cầu. Dự án bạn làm sẽ phụ thuộc vào sở thích và kế hoạch phát triển bản thân của bạn :)

### Contact (Liên hệ)
* Homepage: boardpackager.com
* Anh Ha (đồng nghiệp tương lai): anh@boardpackager.com

**Comment by thang-sotatek-blanknetwork** [comment]
@anhha7 a inbox e với nhé, skype của e live:phamdat241197

**Comment by tatdat97dhbkhn** [comment]
@anhha7 a inbox e với ạ, skype của e ạ live:phamdat241197

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
