### ISSUE TITLE
Middle/Senior Nodejs Developer/ Blockchain - Remote - FT

### ISSUE THREAD

**Issue by Thuthao9x** [awesome-jobs/vietnam#3607]
## Location

* Remote

## Salary Expectation

* max 5000$/month or range

## Requirements

* Comfortable with database technology: e.g. MySQL, SQL Server, Oracle
* Knowledge of CI/CD practices
* From 2 years of experience in hands-on coding Nodejs

### Must Have

* Experience in managing Linux servers
* Experience building and deploying applications and services into cloud environments (AWS stack)
* Experience in writing applications using Typescript and JavaScript

### Ideally

* A degree in Computer Science or Software Engineering
* Foundation level knowledge and programming experience with Bitcoin, Ethereum or other crypto currencies is a must
* Ability to work effectively in a fast paced, complex technical environment with high adaptability and flexibility

### Why it would be awesome to work with us

* In-house Leadership and Skills development
* Flexible Work Hours
* ESOP
* Fun Stuff
This is the best part. They are a fun bunch, and when you work with them, it’s not hard to have a
great time. From online board games to virtual birthday celebrations, there’s so much fun stuff to be
involved in at Propine. 

### Contact

Linkerdin/Skype: thuthaohr.jb@gmail.com
Tele: ththaohr

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
