### ISSUE TITLE
Middle/Senior Nodejs Developer/ Blockchain - Remote - FT

### ISSUE THREAD

**Issue by Thuthao9x** [awesome-jobs/vietnam#3611]
## Location

* Remote

## Salary Expectation

* max $5000/month or range

## Requirements
* Comfortable with database technology: e.g. MySQL, SQL Server, Oracle
* Knowledge of CI/CD practices
* From 2 years of experience in hands-on coding Nodejs

### Must Have

* Experience in managing Linux servers
* Experience building and deploying applications and services into cloud environments (AWS stack)
* Experience in writing applications using Typescript and JavaScript

### Ideally

* A degree in Computer Science or Software Engineering is a must
* Foundation level knowledge and programming experience with Bitcoin, Ethereum or other crypto currencies is a must
* Ability to work effectively in a fast paced, complex technical environment with high adaptability and flexibility

### Why it would be awesome to work with us

* In-house Leadership and Skills development
* Flexible Work Hours
* ESOP
* Fun Stuff
This is the best part. They are a fun bunch, and when you work with them, it’s not hard to have a
great time. From online board games to virtual birthday celebrations, there’s so much fun stuff to be
involved in here

### Contact
Linkerdin: https://www.linkedin.com/in/ththaohr/ 
Tele: ththaohr

**Comment by cuongtk8** [comment]
Hi @Thuthao9x, could you please send me a Job Description for this job? Thank you!
My email: harrytran103@gmail.com
