### ISSUE TITLE
Trust Circle - iOS Software Engineer - HCMC - Fulltime

### ISSUE THREAD

**Issue by lienhuynh10991** [awesome-jobs/vietnam#362]
## Why join us?
* Supporting a team with world-class founders, world-class investors, and a gigantic global market of 3.5 trillion USD is such a rare chance. We invite you to participate in such an opportunity right in the middle of Ho Chi Minh City.
* TrustCircle is looking for a youthful, diligent, hard-working, creative and self-motivated person who want to succeed with us and commit to build solid operational software tools for the whole team. To do this, we want you to join us wholeheartedly like all other members of the team. In return, we will provide you with the best supports and resources to succeed in your taking.

## Location
* 151 Ton Dat Tien, SB – 02, Garden Court View 1, District 7, Ho Chi Minh City
* <http://bit.ly/1YvRxFr>

## Salary/Benefits
* We will do our best to make sure you are motivated, happy, healthy, and productive. Followings are the few things that we will do:
   - Being challenged to build solid operational software tools for the whole team.
   - Competitive salary: to make sure you are able to maintain a comfortable living for you and your loved ones.
    - Motivated stock plan: which will make you welloff when the company succeed.
    - Health insurance: to make sure you will not be worried about you or your loved ones get sick.
    - Onsite laundry dropoff and pickup: make sure you always look good and clean without spending much time and effort.
    - Financial support for self-study.
   - The list can go on, but the bottom line is: we want you to succeed with us, and we are willing to go far and beyond to make it happen.

## Requirements
* Proficient in Swift, with a good knowledge of its ecosystems
* Familiarity with RESTful APIs to connect mobile applications to back-end services
* Strong knowledge of iOS UI design principles, patterns, and best practices
* Experience with offline storage, threading, reactive programming and performance tuning
* Experience with automated testing platforms and unit tests
* Ability to understand business requirements and translate them into technical requirements
* Familiarity with cloud message APIs and push notifications
* Familiarity with continuous integration
* Have published one or more iOS apps in the app store

## What will you do
* Translate designs and wireframes into high quality code
* Design, build, and maintain high performance, reusable, and reliable code
* Ensure the best possible performance, quality, and responsiveness of the application
* Identify and correct bottlenecks and fix bugs
* Help maintain code quality, organization, and automatization

## Contact
* If you are compelled about what we mentioned above, please contact us with your CV at <iamin@TrustCircle.com>, you will be glad you do.

**Comment by joneslee85** [comment]
Please revise the post to meet our guideline, as of https://github.com/awesome-jobs/vietnam/blob/master/README.md

* Title format is wrong
* Nested bulletpoint format is wrong

**Comment by lienhuynh10991** [comment]
Please check and advice
Thanks

**Comment by joneslee85** [comment]
The title is still not correct. There is no `[]` in the title.

**Comment by lienhuynh10991** [comment]
Please check. Thanks

**Comment by lienhuynh10991** [comment]
Can I repost this job again?

**Comment by huydx** [comment]
@lienhuynh10991 what do you mean by repost?

**Comment by lienhuynh10991** [comment]
Post another one

**Comment by huydx** [comment]
Why you need to post another one? I think you can just edit the current
