### ISSUE TITLE
.Net Technical Team Leader - Up to $3.500 - Thanh Xuan, Hanoi

### ISSUE THREAD

**Issue by TanmyLe** [awesome-jobs/vietnam#3626]
## Location
513 Truong Chinh, Thanh Xuan Dist, Hanoi

## Salary Expectation
Monthly: $2.000-3.500
3-month bonus/ year
Premium health care

## Requirements
•	Có trên 5 năm kinh nghiệm làm dự án sử dụng công nghệ .NET
•	Hiểu và áp dụng tốt các nguyên lý chung và cách làm tốt nhất trong thiết kế và lập trình, như SOLID, Design Pattern…
•	Là một lập trình viên fullstack, thành thạo các kỹ năng lập trình cả back-end và front-end 
o	Back-end : ASP.net  MVC, Entity framework, Linq, .Net Core, Restful API,..
o	Front-end : HTML/CSS/javascrips, AngularJS,…
o	Database: SQL Server, MongoDB...
•	Có kinh nghiệm xử lý hệ thống với dữ liệu lớn; viết câu lệnh SQL truy vấn , sử dụng cache để tối ưu hiệu năng 
•	Có kinh nghiệm cài đặt, cấu hình sản phẩm để vận hành trên các môi trường khác nhau (môi trường kiểm thử, môi trường vận hành thật)
•	Có kinh nghiệm phát triển dự án theo mô hình nhanh gọn (Agile, Scrum) là lợi thế

### Responsibilities
•	Tham gia phát triển các sản phẩm Web & Mobile vận hành các nghiệp vụ khác nhau của cho tập đoàn F&B
•	Đóng góp ý kiến về chức năng sản phẩm cùng đội dự án để tạo ra sản phẩm tốt nhất cho người dùng
•	Thiết kế giải pháp kỹ thuật và phát triển sản phẩm mới
•	Phối hợp với các đối tác (ngoài công ty) hoàn thiện các sản phẩm thuê ngoài
•	Tiếp nhận, phát triển các sản phẩm hiện có 

### Contact
Email: my.ltt@ggg.com.vn
Phone/Zalo/Viber/WhatsApp/Telegram: 096 2121 411
Skype: tanmyle_1
(Ms. Mỹ)

**Comment by lactroi** [comment]
Thank you for posting! Unfortunately, we require job posts to be written in English.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!

**Comment by TanmyLe** [comment]
Dear Awwsome-jobs/Vietnam,

I don't know how to edit my issue so I've just posted the new one in
English.

Kindly accept my request.

Cause I'm the newbie so would you mind if you can share how to add the
Label such as: Hanoi/ fulltime/ DotNet...on the issue.
I absolutely appreciate your help.

Thanks so much.

Regards,
Tanmy Le


Vào 10:43, Th 4, 23 thg 11, 2022 Lạc Trôi ***@***.***> đã
viết:
