### ISSUE TITLE
Full time remote Front End Developer

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3632]
## Location

* Singapore
* Remote

## Salary Expectation

* $3000-5000

## Requirements
Knowledge Requirements:
- Strong JavaScript/Typescript skills
- Strong knowledge and experience in any reactive framework (Vue, React, Angular)
- In-depth experience with HTML5, css, canvas, and svg
- Experience with ES6, typescript, webpack and transpilers like babel
- Understanding of different browser requirements for responsive web design
- Proficiency in spoken and written English

Preferred Work Experience:
- Implemented a web app in production using VueJs
- 3+ years work experience in front-end or full-stack engineering of web applications

### Responsibilities
We are looking for a front-end developer that can use UX/UI designs of 3D design web software and implement into production ready code. The candidate will lead styling and front-end implementation of user-facing features.
- Implement GUI for managing application data in P**C browser-based animation editor with reactive frameworks (VueJS)
- Optimize application for speed, scalability, and responsive web design
- Build robust unit tests for stable and reliable releases
### INTERVIEW PROCESS
1. Test
2. Interview 1
3. Interview 2
### Contact
Skype: Huehuenoivu
Mail: Gina.recruiter@gmail.com

**Comment by lactroi** [comment]
Thank you for posting! We see that you are using personal emails for contact info. Currently we do not accept jobs from head-hunters or agencies for the sake of the high quality of the job board.

In case of misunderstanding, please help to clarify with a comment. This post will remain closed until the concern is fully addressed.

Thank you and have a good day!
