### ISSUE TITLE
Ngân hàng giao dịch quốc tế. Cake Vpbank được bảo mật của Vương Quốc Anh. Nhiều ưu đãi đặc biệt. 

### ISSUE THREAD

**Issue by BachVanDuan** [awesome-jobs/vietnam#3662]
Bạn ơi, hãy dùng ngân hàng số Cake by VPBank để được tặng đến 20k khi mở tài khoản mới! Chỉ cần click vào link này https://cakevn.onelink.me/HHDV/0h414qk6 để tải app Cake, nhớ nhập mã giới thiệu 0398592537 của mình vào ô người giới thiệu để nhận thưởng nhé.

**Comment by runlevel5** [comment]
VKL. Giờ có màn spam trên này nửa
