### ISSUE TITLE
AOI Systems Vietnam - Fresher (PHP/Java/JavaScript) - HCM - FT

### ISSUE THREAD

**Issue by ASV-recruit** [awesome-jobs/vietnam#367]
## Location

* Etown, Tan Binh, HCMC

## Salary Expectation

* from $350/month or negotiable

## Requirements
* University graduated or last year student: Software Engineer, IT, …
* Have knowledge about OOP
* Able to read documents in English

## Benefits
* 13th month salary. Annual leave 12 days. Health care Insurance.
* Company trip. Team Building. Free parking. Birthday party.
* Working time: 8 am-17:30 pm (Monday to Friday)
* Social insurance, health insurance, unemployment insurance and other benefits under the provisions of the Company. Annual medical examination.
* Working directly with Japanese clients, access to new technologies and have opportunities for personal development.

### Contact
* Please send your CV to HR Dept: **tuyendung@aoi-sys.vn**
* More information at: aoi-sys.vn

**Comment by joneslee85** [comment]
Please break this job post into 3 separate job posts. We do not accept such generic job post

**Comment by joneslee85** [comment]
Plus there is no information about company profile, what kind of works, etc. 👎

**Comment by huydx** [comment]
@ASV-recruit could you provide `Why people should love working at aoi-sys` in detail? If you can't i think this job is not accepted here.
