### ISSUE TITLE
Code Engine Studio - Sr Ruby Dev - Da Nang - FT

### ISSUE THREAD

**Issue by sahkoola** [awesome-jobs/vietnam#368]
## About Us

Looking for an exciting and challenging career opportunity at a fun, dynamic and family like English speaking environment? We are a young and energetic company that provides competitive pay and a great work life balance. We put heavy emphasis on training and development offering weekly English and soft skills classes and lunch is provided everyday. We are looking for superstar coders to join our growing team!  Travel outside of Vietnam to other countries is possible as well.

### Why it would be awesome to work with us

* Excellent salary with 13th month bonus and up to an additional 2 months performance bonus
* 5 day work week (Mon - Fri) with no overtime hours expected
* Emphasis on personal and career development (2 hours/week of English classes and weekly soft skills training during work hours)
* Opportunity to travel to other countries for training and work
* Free lunch everyday at the office and monthly team social events
* Fully English speaking environment working with clients from USA, Canada, Indonesia, Hong Kong and Singapore on portfolio piece projects for great clients

## Location

* Da Nang, Vietnam

## Salary Expectation

* Competitive / Negotiable

## Requirements

* Ruby
* JavaScript, XML/JSON and REST API experience
* MySQL, PostgreSQL, or Mongo
* 5+ years Software Engineering experience

### Must Have

* Experience with building 3rd party plugins, mobile/responsive development, APIs, source control, and troubleshooting cross-browser/platform issues.
* Demonstrated understanding of revision control, bug tracking systems, and build and deployment methodologies.
* Proven analytical and problem-solving skills and a keen attention to detail.
* Passion for technology, a willingness to learn and a good attitude.

### Ideally

* Excellent English communication skills - both verbal and written.

### Responsibilities

* Developing Apps into polished, accessible, cross-device, responsive experiences; development of any or all aspects of the systems design, code construction, database design, unit and integration testing, and implementation.
* Demonstrates and applies strong technical leadership and knowledge to develop high quality, resilient software, as an individual contributor or as part of a scrum team.
* Collaborates with Project Managers, Product owners, Scrum Master, Dev and QA team members to perform analysis of functional requirements, user stories and specifications.
* Monitors industry trends on web technologies and related concerns to aid with roadmap planning and risk mitigation.
* Helps mentor, guide and review the work of more junior software engineers.

### You’ll be responsible for

* Building a new relocation app for a Startup in Silicon Valley

### Contact

career_at_codeenginestudio_dot_com

**Comment by joneslee85** [comment]
Thanks for the job posting, starting from today, new job post must comply with new guideline in which the job post must have a section on `### Why it would be awesome to work with us`

Please make amendment in accordance

**Comment by sahkoola** [comment]
@joneslee85 Thank you!
