### ISSUE TITLE
iOS Mobile Developer - Misfit Wearables/ Fossil

### ISSUE THREAD

**Issue by hungcm0512** [awesome-jobs/vietnam#369]
You’ll be contributing to the development of next generation wearable products to improve people's health and well-being, while participating in the most innovative engineering team in Vietnam.

WHAT YOU'LL BE RESPONSIBLE FOR:
•	Design and build advanced applications for the iOS platform
•	Collaborate with cross-functional teams to define, design, and ship new features
•	Work with outside data sources and API's
•	Unit-test code for robustness, including edge cases, usability, and general reliability
•	Assist in automation test setup and testing protocol
•	Work on bug fixing and improving application performance
•	Continuously discover, evaluate, and implement new technologies to maximize development efficiency

WHAT WE NEED:
•	Bachelor Degree in Information Technology, Computer Science, or equivalent
•	At least 1 year of relevant working experience
•	Knowledge:
o	Programming languages: Objective-C, C/C++
o	Application development: basic UI elements, AutoLayout, CoreAnimation
o	Concurrency: GCD, Thread, Queue and scheduling technique
o	Memory management: nonARC, ARC and troubleshooting technique
o	Database: CoreData, SQLite, Magical Record
o	Software design: Design Pattern, DRY, SOLID.
o	Third-party libraries and APIs
•	Huge plus: strong English communications skills

IN RETURN WE OFFER (Why would it be awesome to work with us?)
•	Meaningful work
•	Subsidies for: cell phone, health/fitness, health insurance
•	Plenty of food, all the time
•	Jerk-free, ego-free environment
•	Passionate colleagues
•	A commitment to make your time with us the most transformational time in your career to date
•	Personal and professional development opportunities: 13 month training programs at our Silicon Valley Offices (most of our team members have been to a training program there at least once)

CONTACT: Ms. Ho Viet Ha - 0909152488
#iOS #Misfit #Fossil

**Comment by joneslee85** [comment]
Thanks for posting with us. The title / content format does not comply with our guideline. Please see https://github.com/awesome-jobs/vietnam for more details. Furthermore, please provide email contact of the HR or representatives at Misfit. FYI if you are middleman recruitment agency, this job post will not be accepted.

**Comment by joneslee85** [comment]
No amendment after 2 days. I take this as you don't care enough. Closing 👎
