### ISSUE TITLE
Android Mobile Developer - Misfit Wearables / Fossil

### ISSUE THREAD

**Issue by hungcm0512** [awesome-jobs/vietnam#370]
You'll be contributing to the development of next-generation wearable products to improve peoples' health and wellbeing, while participating in the most innovative engineering team in Vietnam from feasibility to implementation.

WHAT YOU'LL BE RESPONSIBLE FOR:
•	Design and build advanced applications for the Android platform.
•	Collaborate with cross-functional teams to define, design, and ship new features.
•	Work with outside data sources and API's.
•	Unit-test code for robustness, including edge cases, usability, and general reliability.
•	Work on bug fixing and improving application performance.
•	Continuously discover, evaluate, and implement new technologies to maximize development efficiency.

WHAT WE NEED:
•	Bachelor Degree in Information Technology, Computer Science, or equivalent.
•	At least 1 year of relevant working experience.
•	Knowledge of:
o	Programming languages: Java, C/C++.
o	Application development: application lifecycle, basic UI elements & layout, basic animation technique.
o	Concurrency: Thread, Handler, AsyncTask and scheduling technique.
o	Database: SQLite, ORMLite.
o	Network: JSON, REST API.
o	Native: JNI, NDK.
o	Software design: Design Pattern, DRY, SOLID.
o	Third-party libraries and APIs.
•	Huge plus: strong English communications skills.

IN RETURN WE OFFER:
•	Meaningful work
•	Subsidies for: cell phone, health/fitness, health insurance
•	Plenty of food, all the time
•	Jerk-free, ego-free environment
•	Passionate colleagues
•	A commitment to make your time with us the most transformational time in your career to date
•	Personal and professional development opportunities: 13 month training programs at our Silicon Valley Offices (most of our team members have been to a training program there at least once)

CONTACT: Ms. Ho Viet Ha - 0909 152 488

**Comment by joneslee85** [comment]
Thanks for posting with us. The title / content format does not comply with our guideline. Please see https://github.com/awesome-jobs/vietnam for more details. Furthermore, please provide email contact of the HR or representatives at Misfit. FYI if you are middleman recruitment agency, this job post will not be accepted.

**Comment by joneslee85** [comment]
v
