### ISSUE TITLE
Technical Test Engineer - Misfit Wearables / Fossil

### ISSUE THREAD

**Issue by hungcm0512** [awesome-jobs/vietnam#371]
Our team is offering an opportunity to be a part of a team working on edge-cutting products/ technologies. Our systems need to meet remarkably high standards of quality, performance and reliability, thus you will design, plan, execute test cases for large-scale web applications, mobile applications, tools and software. You are a talented, detail oriented and enthusiastic Quality Assurance Engineer who is passionate about quality and enthusiastic about building a healthcare eco-system that will help millions of users.

WHAT YOU'LL BE RESPONSIBLE FOR:
•	Be a team-player at the Technical Test Team
•	Plan, create test cases
•	Use manual testing or test automation tools to execute test plans
•	Effectively use a defect tracking system and quality assurance tools

WHAT WE NEED:
•	Bachelor Degree in Information Technology, Computer Science, or equivalent
•	0 — 3 year experience
•	Solid knowledge of software testing, especially Agile testing. Knowledge of CI is a plus.
•	Participated in the different phases of the software development life cycle including integration testing, functional testing, system testing, acceptance testing and regression testing
•	Being obsessed with perfectionism and quality
•	Skills in Java and/or C/C++ and scripting language (shell bash) is a huge plus.
•	Comfortable with using English daily
•	Able to perform solely or as a team player

IN RETURN WE OFFER:
•	Meaningful work
•	Subsidies for: health/fitness, health insurance
•	Plenty of food, all the time
•	Jerk-free, ego-free environment
•	Passionate colleagues
•	A commitment to make your time with us the most transformational time in your career to date
•	Personal and professional development opportunities: 1-3 month training programs at our Silicon 
Valley Offices (most of our team members have been to a training program there at least once)

CONTACT: Mr. Chau Minh Hung - 0945 533 773

**Comment by joneslee85** [comment]
Thanks for posting with us. The title / content format does not comply with our guideline. Please see https://github.com/awesome-jobs/vietnam for more details. Furthermore, please provide email contact of the HR or representatives at Misfit. FYI if you are middleman recruitment agency, this job post will not be accepted.

**Comment by joneslee85** [comment]
No amendment after 2 days. I take this as you don't care enough. Closing 👎
