### ISSUE TITLE
AgeCode - iOS Developer - Saigon - FT

### ISSUE THREAD

**Issue by s123121** [awesome-jobs/vietnam#372]
**The world need more innovators.**

So we built AgeCode. We set out to build AgeCode not just as a company but as a innovator hub.
We are challenging the status quo of the travel industry and now, we need more innovators like you, who always interested in creating elegant/state of the art solutions by incredible software development skill. This is your chance to work with challenge lovers, grow your skills, and make an impact

## Location

District 1, HCMC, Vietnam
## Salary Expectation
600$ - 900$

## Who you are
- You have a strong passion for learning.
- You have 1 years or above experience with iOS development
- You are familiar with working with RESTful API to connect mobile applications to back-end services
- You have experience in working with Git and GitHub/Gitlab
- You have excellent debugging skill
- You’re self driven and can work independently, while you also enjoy working in a team environment and owning the success of a project.
## What we expect
- Create prototypes with as few bugs as possible
- Connect mobile app with back-end REST API
- Be an empathetic developer. Everything you touch should be easy to use, easy to test and work as expected
- Keep abreast of trends in web/mobile development; share these lessons with the team
- Learn from everyone, no matter who they are
## Who we are

We’re a team of 4 people(Vietnamese/Japanese) who love to build things. As a early stage employee, you will be the one in charge of creating the identity of AgeCode. With us, you’ll get exposure to many aspect of running a start up and experimenting things. Come talk with us if you want to know more

### Why it would be awesome to work with us
- We build product 
- We think it is important that everyone has an opportunity to grow and try new things. For example: we  have a 7 hours work-day policy. Brilliant ideas are always welcome
- We are small team, so there are many things for you to improve on. Your only limit is your creativity! 
- **MOST** of the time, our boss pay for lunch !!!
## Contact
We like to keep things interesting. If you’re curious, talented and hungry, we want to hear from you.
Do not hesitate to send your CV to Lam: n.lam@agecode.co.jp

**Comment by joneslee85** [comment]
Thanks for posting with us. Please revise the body to include a section `### Why it would be awesome to work with us`
