### ISSUE TITLE
Ikorn Solutions - Java Team Leader - HCMC - FT

### ISSUE THREAD

**Issue by ikornsolutions** [awesome-jobs/vietnam#373]
## 

* Etown 2 Building, Saigon, Vietnam

## Salary Expectation

* $900~ $1200/month

## Requirements
* Java,JavaScript, ActionScript
* Web or Android programming
* PRDBMS (MySQL, SQLite), NoSQL (MongoDB)
* 2+ years working experience

## Skills
-Organizational and problem solving skills

### Must Have
The ability to interact professionally with a diverse group, including executives, manager, and subject matter experts.

### Ideally

* Experience with Korean working environment.

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for
- Key programming in project ; Build architecture of software
- Manage plans and have ability to support coworker in programming
- Implement complexity algorithm to make software fast and GUI smoothly
- Resolve big data, large of request concurrence 

### Why it would be awesome to work with us:

-  Bonus: 4 times per year.
- Lunch, gasoline, parking fee allowances.
- Company Trip.
- Team building activities. 
- Technical training support.
- Foreign languages studying support. 
- An international, professional, young but innovative, knowledge-share environment.

### Contact
Email: hr@ikornsolutions.com or Tel: 0862971141

**Comment by huydx** [comment]
@ikornsolutions thanks for posting with us, it seems that you mis-typed the salary range 

>$9000~ $1200/month

and could you please review the "Why it would be awesome to work with us:" session, we don't need 
some obvious items like:
```
Benefits for employee according to the Vietnam Labor Laws.
Salary will be reviewed every year.
13th salary will be included.
```
It should be great if you can provide some *reason* why an awesome engineer should work for your company.

**Comment by longkt90** [comment]
I think `13th salary will be included` should be good - not all company have this @huydx

**Comment by huydx** [comment]
it seems that @ikornsolutions no more care about the job, so i temporary close it
