### ISSUE TITLE
Remote - Smart Contract (Solidity) Developer

### ISSUE THREAD

**Issue by colus001** [awesome-jobs/vietnam#3768]
# About 0x& PTE. LTD.:

[0x&](https://0xand.com) is a leading NFT gaming company that strives to create engaging, immersive, and player-driven experiences through innovative blockchain technology. Our mission is to revolutionize the gaming industry by leveraging the power of NFTs and decentralized applications to create unique and unforgettable gaming experiences for our users.

## Job Description

We are seeking a talented and passionate Contract Blockchain Developer with 1-2 years of experience in the field to join our team. In this role, you will be responsible for developing and implementing smart contracts, integrating blockchain technology with our gaming platform, and collaborating with other developers to create cutting-edge NFT gaming experiences.

## Location

- Fully remote position (part-time or full-time)
- Company is based in Korea

## Salary Expectation

* $2,500 USD/month minimum

## Requirements
* Solidity
* Rust (optional)
* 1-2 years Blockchain Development experience
* Experience with NFTs and gaming
* Fluent in English

### Must Have

* Proficient in Solidity
* Understanding of Ethereum and the NFT ecosystem
* Experience with blockchain development tools and frameworks
* Fluent in English

### Ideally

* Experience with Rust programming language
* Passion for the gaming industry

### You’ll be responsible for

* Developing and implementing smart contracts for our NFT gaming platform
* Integrating blockchain technology with our existing gaming platform
* Collaborating with cross-functional teams to develop new features and improve the overall user experience
* Communicating effectively with team members and stakeholders in English

### You can bring

* A strong interest in NFTs and blockchain technology
* Good problem-solving and analytical skills

### Why it would be awesome to work with us

* Competitive compensation package
* Opportunity to work on cutting-edge NFT gaming projects
* Flexible work schedule and remote work options
* Collaborative and supportive team culture
* Annual trip to Korea HQ for team building and training

### Interesting engineering projects

* Revolutionizing the gaming industry by leveraging the power of NFTs and decentralized applications to create unique and unforgettable gaming experiences

### Contact
* Homepage: [0xand.com](https://0xand.com/)
* HR Contact: [recruit@0xtribe.com](mailto:recruit@0xtribe.com)

**Comment by nghanhu** [comment]
Is your company open for headhunter? I have some candidates who may be perfect fit for your vacancy.

**Comment by sumitshinde-84** [comment]
Hello,
My name is Sumit Shinde, and I am a passionate and hardworking full-stack developer. I have recently completed my education and am actively seeking job opportunities to kickstart my career. While I don't have any professional experience yet, I have gained valuable skills and knowledge through my education and by contributing to open-source projects.
