### ISSUE TITLE
CMC Soft - .NET Developer - Ha Noi - PT

### ISSUE THREAD

**Issue by NhungCMC** [awesome-jobs/vietnam#377]
Cau Giay, Ha Noi, Vietnam

##Salary 
• $700-$1,500/month 
• Partime ( 3-6 months)

## Requirements

• English skills in reading/writing
• 2+ years in Dot net Development
• 1+ years in C#
• 1+ years in Windows USB driver

## Skills

• Utilize established development tools, guidelines and conventions including but 
not limited to ASP.NET, SQL Server, HTML, CSS, JavaScript, and C#/VB.NET 
•Design, code and test new Windows and web software applications 
• Maintain existing software systems by identifying and correcting software defects 
• Investigate and develop skills in new technologies 
•Create technical specifications and test plans 

### Responsibilities

• Great power comes with great responsibilities!

### You’ll be responsible for

•Being a team member Development/Product Department.
•Being responsible for product development and solutions for the project.
•Build reusable code and libraries for future use.
•Great power comes with great responsibilities!

### Why it would be awesome to work with us
•Nice office
•We are big team, so there are many things for you to improve on.
•We build own products.

### Contact Ms Nhung CMC
• Email: ptnhung@cmc.com.vn
• Skype: nhungpham.kbl

**Comment by huydx** [comment]
hi @NhungCMC , it seems that you're copy the `Why it would be awesome to work with us` from https://github.com/awesome-jobs/vietnam/issues/376 . Is it true? Please answer honestly

To be summary, WE DON'T ACCEPTED LOW QUALITY JOB, and copying from another job post make this job looks totally low quality

![](https://gyazo.com/c990149d6c94c09227cda2773967fc52)

**Comment by joneslee85** [comment]
@huydx with you on this, this company now is black-listed

**Comment by NhungCMC** [comment]
Dear mr Huydx,

i'm so sorry, i'm a new member so a don't know this rules

Best regards
Nhung CMC

**Comment by joneslee85** [comment]
@NhungCMC just be professional please. We have clearly stated that job poster should *read carefully* instructions before posting. The job post is not correctly formatted, it is seems to be subjected to plagiarism.

It would help reviewers do their job better. It is not an excuse for being a new member. I bet you would judge a candidates poorly if he/she submit a poorly done resume. Same rules apply. Respect the candidates and our reviewers' time.

I personally give 👎 and I don't feel bad about that. Nothing personal, just professional.

**Comment by NhungCMC** [comment]
I'm say sorry with mr Huydx, not you (Jonesless85) :)

Please don't reply. Thanks you!

**Comment by huydx** [comment]
@NhungCMC me and @joneslee85 are both admin of this page, please don't be rude

**Comment by NhungCMC** [comment]
I don't like the way he says

I'll leave :)
Any way thanks a lot!
