### ISSUE TITLE
e27.co - Front-end Engineer - Saigon - FT

### ISSUE THREAD

**Issue by zweedao** [awesome-jobs/vietnam#379]
<img src="https://cloud.githubusercontent.com/assets/3747942/18309117/654bba8a-752a-11e6-8972-c4de60e6b9d7.png" width="400">

## About e27 & what we are doing
[**e27.co**](https://e27.co/) is the leading startup community builder in Asia. We provide entrepreneurs with the knowledge & tools to build their startups. Our 3 main products:
- **e27.co news**: the leading online news site about startups in Asia
- **[Echelon](https://e27.co/echelon/) Conference**: the best tech startup conference in Asia. 14 countries, 10,000 startups & investors. We have just done Echelon Vietnam in November!
- **Online products**: [Business Matching](https://e27.co/fundraise), [Job Portal](https://e27.co/jobs), [Marketplace](https://e27.co/marketplace), [Event Portal](https://e27.co/events), and more exciting product ideas to come.  

We increasingly focus on building great online product for users in Asia, and expanding Product Team. We have just started a new talented Product & Engineering team in Ho Chi Minh City, and you will be one of the first to join this adventure.

## Responsibilities
Work with UX Designer & Back-end Engineer to build awesome e27 products for users across Asia

## Requirements
- 2+ years of experience
- Entrepreneurial. Self-motivated. Like to work for startup & build awesome products.
- Good front-end skills: HTML, CSS, up to date with Javascript frameworks.
- Love to build smooth & fast front-end across different platforms
- Good sense of design & UX
- Good back-end knowledge: MVC, data structure & algorithm. A huge plus if you can do full-stack & can build back-end well.
- Good communication skill. Decent English.

## Why working with us
- Room to try out your ideas, build innovative products from ground up, and learn a lot along the way. Our motto: Don’t ask for permission, ask for forgiveness. 
- Competitive salary based on skills & experiences.
- International exposure: Base in Ho Chi Minh City. Work directly with young & energetic team in Vietnam & Singapore. Occasional travel to Singapore. 
- Room to grow into leading position in the company.

## Contact
Homepage: [e27.co](https://e27.co)
Please email to zwee@e27.co with the following items. Shortlisted candidates will be contacted for further interview.

- [x] your resume
- [x] short introduction about yourself
- [x] your portfolio / 1 or 2 projects that you’re most proud of

**Comment by huydx** [comment]
@zweedao Please review our newest template at: https://github.com/awesome-jobs/vietnam . We have some notice changed there.

**Comment by zweedao** [comment]
@huydx ok I have edited the description to fit the template

**Comment by huydx** [comment]
@zweedao what template did you look at? I see it's quite not match with https://github.com/awesome-jobs/vietnam/blob/master/ISSUE_TEMPLATE.md

**Comment by zweedao** [comment]
@huydx hey bro can I re-arrange sections in the template. Also my feedback is that the template' flow & section headers can be improved.
- "Requirements" & "Skills" seem to serve the same purpose, can be just 1 section
- "Why it would be awesome to work with us" & "What are hard problems that your company is trying to solve?" should not be under section "Skills", but should be under an "About us" section
Too many sections make the doc hard to read.

I think JD is a marketing document for company to attract employees, so it should be more flexible for company to sell in the best way. 

I suggest not to have too many detailed & rigid sub-sections, but only a few major sections. ITViec seems to do a good job in this. Require only 3 main sections, making the JD clean & easy to read, & company can be more flexible to write: https://itviec.com/it-jobs/front-end-engineer-hot-regional-startup-e27-optimatic-3838

**Comment by huydx** [comment]
@zweedao nice advice! we will take that advice, so basically template is what we needed, there is no need to matching 1-1 with the template if you already include necessary informations.
