### ISSUE TITLE
Terralogic (Former Infornam) - Java Developer  - Saigon - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#380]
Terralogic (former Infornam), headquartered in Silicon Valley, USA is an Engineering & IT services company. It with 1,000 employees and three development centers in US, India and Vietnam provides comprehensive solutions that are cost-effective, scalable and flexible.

The company serves global clients, among them technology pioneers and industry leaders. Our core team is composed of engineers and domain experts who has strong experience and understanding of Mobility, Applications, Networking & Communications and Embedded Systems.

We are building the unimagined and aspiring to be be the most loved organization in the coming years. Accordingly human resources are regarded as our jewels. Terralogic offers a dynamic working environment, professional development and high-end facilities. Our engineers have opportunities to work with foreign customers as well as working onsite in Japan, Europe and the US.
## Location
* Saigon, Vietnam
## Salary Expectation
* Negotiable
## Requirements
* Hands-on experience and deeply understanding of Java core/J2EE plug Eclipse Plugin Development
* Familiarity with Eclipse, Maven, Tcl, Jenkin.
* Familiarity with networking programme (preferred)
* Familiarity with integrating approach (preferred)
* Experience with XML, JSON, RESTful,
* Experience with development, unit testing, and modern development tools such as Git/SVN, Jira/Bugzilla, Jenkins…
* Disciplined, and familiarity with Agile/Scrum methodology (preferred)
* English proficiency: fluent in reading, writing. Intermediate in speaking/listening, able to communicate with US customers via email, chat, or conference meeting.
* Must be able to adapt with and learn new technologies quickly, normally in one week
* Documenting capability
* Be able to work overtime and under high pressure
### Must Have
* Hands-on experience and deeply understanding of Java core/J2EE plug Eclipse Plugin Development
### Responsibilities
* As a Software Engineer, you will be working on exciting and advanced RCP for Terralogic’s global technology customers in networking, e-commerce, video, media, and entertainment
* You will also apply your deep and comprehensive knowledge and understanding of Java stack for solving complex software problems
* Communicate with customer’s engineers/business owners to clarify technical requirements and business requirements, convert high level requirements into low level requirements
* Maintain and support legacy projects developed by Terralogic and customers
* Write the design documents (SAD, Developer Guide, ect.) to be delivered to customer
* Have good opportunity to speak english with customer every week.
### Why it would be awesome to work with us 
* Flexible working schedule. Everything is allowed by trusting the employees
* Competitive Salary: 13th salary + performance awards + project awards; Referral Bonus
* Opportunities for advanced career development overseas: in America, Japan, India…
* Good benefit that takes care of employees work-life balance:
* Insurance: Accident Insurance 24/24 (Gras Savoye Willis); Health Insurance (Gras Savoye Willis):
* Social Insurance tax: was paid as the salary in the labor contract
* Special Leave Days: minimum 15 days/year
### What are hard problems that Terralogic  is trying to solve? 
Finding the talents for the right positions is the big problem that Terralogic is facing.
### Contact
Homepage: http://www.terralogic.com/
Contact: mai.ngo@terralogic.com or Skype: mai.ngo91

**Comment by huydx** [comment]
@RecruiterMaiNgo Please review our newest template at: https://github.com/awesome-jobs/vietnam . We have some notice changed there.

**Comment by RecruiterMaiNgo** [comment]
@huydx I have just modified. Hope it's okay now.

**Comment by huydx** [comment]
@RecruiterMaiNgo we have a template here, what template did you look at?

**Comment by RecruiterMaiNgo** [comment]
@huydx : I found the out-updated template :(  I have edited it. Thanks for your support.

**Comment by RecruiterMaiNgo** [comment]
@huydx
