### ISSUE TITLE
Yomi Studio – Senior Ruby Developer - Saigon - FT

### ISSUE THREAD

**Issue by CuongPhungYomi** [awesome-jobs/vietnam#381]
## Location

* 292/46 Binh Loi St., Binh Thanh District, Saigon, Vietnam
* Full-time

## Salary Expectation

* **Up to $2000**

## Requirements
* Familiar with Ruby programming language.
* Knowledge of Unix/Linux environments.
* Solid understanding of object-oriented programming.
* Understanding of front-end technologies, such as Javascript, HTML5, CSS3.
* Able to implement automated testing platforms and unit tests.
* Proficient understanding of code versioning tools with GitFlow.
* Able to create database schemas that represent and support business processes.
* Good at reading and listening in English.
* 3+ years working with Ruby

### Ideally
* Have experience in key-value store engine (Redis), back-end index engines such as Sphinx, Solr is a huge plus
* You have contributed significantly to the release of a production-level (preferably not a side-project, something with actual users)
* Exposure to leadership roles, particularly on a development team
* Establish training programs for interns and junior developers
* Contributed to open source projects or presented at a conference

### Responsibilities

Developers play a big part of what makes a great Mobile App. The job starts hard and will only get harder. We believe that Developer in our team have the ability and autonomy to solve complex problems and deliver quality code as part of the team. With confidence in their own decisions and the quality of their work, they remain open to discussing better ways to solve problems and deliver features. They are comfortable communicating and collaborating with designers, product managers and clients.

### Why it would be awesome to work with us

Being part of a passionate team is a great benefit in itself. But, since loving your job doesn't pay the bills, a competitive salary and generous benefits package are also offered.
* A Macbook pro and a big monitor to work with.
* Flexible working time. Don't worry, we don't have fingerprint-scan record.
* Work retreat aboard twice a year. Last time we went to Chiang Mai, Thailand in a month.
* Trust-based Time Off (take the days you need)
* Dedicated “YOMI time” for self-directed, non-client work
* Incubator support for side projects
* Mentoring and speaking opportunities
* Conference attendance paid by YOMI Studio.
* Catered lunches, family-friendly outings, pet-friendly offices, tech gadgets to play and lots of book.

### What is hard problems that Yomi is trying to solve? (MUST)
The answer is to find a really suitable candidates for the team. We're hiring Back-end Developer with experience at all levels, but no matter your current level of experience you must:
- Be smart
- Learn quickly
- Take challenge. 
- Be a good teammate

### Contact
**Homepage**: yomi.studio
**Contact us**: If you like to work with us, please send your information with your past products to **recruitment@yomi.studio**

**Comment by huydx** [comment]
hi @CuongPhungYomi , thanks for posting job with us, currently our newest template has `### What is hard problems that your company is trying to solve? (MUST)` section, so please update this section

**Comment by CuongPhungYomi** [comment]
Ok mr Huydx. Thank you for your supporting

**Comment by Haseeb717** [comment]
Is it a remote job?

**Comment by CuongPhungYomi** [comment]
Hello @Haseeb717  Thank you for your concern about our position. Right now, we are still looking for local developer to finish our project. But in the near future if there are any chances for remote job I shall contact you.

**Comment by CuongPhungYomi** [comment]
We are still hiring guys!!
