### ISSUE TITLE
REMOTE _ Engineering Lead

### ISSUE THREAD

**Issue by gina1309** [awesome-jobs/vietnam#3835]
## Location

* Remote

## Salary Expectation

* Negotiate

## Requirements
- Minimum of 10 years of experience in a technical role, with at least 3 years as a Technical Architect.
- Expertise in mobile app development technologies such as React Native, Swift, or Kotlin.
- Strong knowledge of cloud services (AWS, Azure, or GCP) and experience in deploying applications in the cloud.
- Proficiency in coding best practices, code reviews, and agile development methodologies.
- Previous experience in successful start-ups is highly desirable.
- Excellent leadership, communication, and collaboration skills.
- Ability to drive innovation and handle multiple priorities and deadlines.

Plus: 
- Experience with edtech domain is preferred.
- Previous experience in product scaling is a plus.

### Responsibilities

ELSA is the smartest Speech AI, backed by Google, on a mission to enable 1.5 billion language learners around the globe to speak English with full confidence and unlock their opportunities in life. ELSA is also Top 5 Best Artificial Intelligence Apps by Research Sniper, and Top 4 Companies Using AI To Transform The World by Forbes.

We are currently seeking a highly-skilled Engineering Lead with a minimum of 10 years of technical experience, to oversee the technical aspects of our product. This role is crucial to our company and involves working closely with Engineering Managers and the Engineering Director. The ideal candidate should have a strong technical background, preferably with experience in successful start-ups, and will be responsible for guiding the technical direction of our mobile app product in the edtech.

Responsibilities:
- Define and implement technical strategies for the product.
- Oversee the architecture of mobile applications and ensure scalability, reliability, and security.
- Work closely with Engineering Managers and Engineering Director to ensure alignment with company objectives.
- Provide technical leadership and guidance to the engineering teams.
- Drive innovation and efficiency in the engineering processes.
- Join during the product’s scale-up phase and contribute significantly to its growth.
- Ensure that technical decisions align with product and business goals.

### Why it would be awesome to work with us
Where you'll be
- We are a distributed workforce with offices in Silicon Valley, Portugal and Vietnam. 
- Where in the world? For this role, we are looking for someone in Asia, which can overlap time with our global teams.
- This is a remote role, with opportunities to travel. 
- Equity/bonus options are available.
### Process:
4 rounds, including meeting with the Board of Directors.
Report to: VP of Product and Engineering

### Contact
Skype: Huehuenoivu

**Comment by gina1309** [comment]
Note: 
- Prefer candidates in India or Sing (NOT prefer Vietnam)​​
- Need top profile:
  + Study at top school
  ​​​​​​​+ Work at top company (Mobile app product based, successful startups)
  + Have a long working history (no job hopping)
  + Leading technical strategies => strong experience with technical (NOT leading team)
  + Working in successful startups
  + Mobile app products (Edutech or mega/super app)
​​​​​​- Each tech team already had an Engineering Manager to manage, Engineering Lead only takes care of technical strategy and shaping technical aspects for the product.
-  Working with Engineering Manager and Engineering Director
- Any nation can be recruited, and highly preferred Indian and Singaporean candidates

**Comment by trietphm** [comment]
> NOT prefer Vietnam

If you don't prefer Vietnam then why do you post in Awesome Jobs Vietnam? Is this a joke?

**Comment by develrocket** [comment]
Hi, I am from Malaysia.
I have a lot of experiences with mobile app development.
So can I work on your project?

**Comment by fxanhkhoa** [comment]
> > NOT prefer Vietnam
> 
> If you don't prefer Vietnam then why do you post in Awesome Jobs Vietnam? Is this a joke?

Absolutely a joke 😄

**Comment by ansidev** [comment]
Moderators should close this job because it is really an issue 🙃

**Comment by monodyle** [comment]
I would like to express my admiration for your exceptional hiring criteria. Remarkably, your company does not prefer individuals from Vietnam, but instead seeks candidates who have studied at top-tier universities and gained experience at leading companies within the industry.

Unfortunately, I was excluded from these criteria, sad! 😞  I sincerely hope that you will soon become a part of the esteemed FAANG conglomerates and emerge as the market leader. With such impeccable hiring standards, I am certain that you will swiftly achieve this goal.

**Comment by gina1309** [comment]
Thank you very much for your comments, I was confused about "popular repositories", I closed the job and edited the post.
Thank you for your comments, sorry for the controversial post.
Have nice day
