### ISSUE TITLE
Cogo Platform - Elixir Developer - Remote - FT

### ISSUE THREAD

**Issue by jfrolich** [awesome-jobs/vietnam#386]
## Location

* Remote

We are a distributed company, the two founders are located in Singapore and Seattle

## Salary Expectation

* Competitive

## Requirements
* Ability to work independently as this is a remote function
* Experience as a programmer
* Proactive with attention to detail
* Great communication skills
* Fluent English language skills
* Passionate about functional programming (we use elixir on the backend and react on the front-end)
* Interest in joining a high growth startup and growing as a person
* Team player
* Pragmatic yet a love for writing elegant code

### Must Have
* At least basic elixir/erlang skills, perhaps you build something as a side project in elixir. Otherwise experience with other functional programming languages such as OCaml or Clojure.
* Basic understanding of GraphQL
* Knowledge of SQL, and in particular PostgreSQL
* Understanding of what constitutes good database design
* Writing integration tests

### Ideally
* Open source contributions or projects
* Also experience with Javascript and React (for the frontend)
* Experience with building web backends in other languages
* Experience with the Phoenix framework
* Some other talents?

### Responsibilities

We are a pretty early stage startup, and are working towards creating a new platform for knowledge management. We are working with large multinational firms that are using our platform, but we are also planning to release it to SMEs next year.

Our current codebase is 100% written by Jaap the CEO of the company. The other co-founder, Nick (President) also has a background in computer science with his focus on sales.

### You’ll be responsible for

* Building out the backend of our platform together with Jaap.

### You can bring

* Ambitious personality
* Great analytical thinker
* Have initiative
* Build cool stuff

### Why it would be awesome to work with us

We run the company like an open source project. This means we heavily utilize github and slack, use an internal issue tracker, kanban board for new features, and submit our work as pull requests. If you build something great that is not part of our core business you have the opportunity to open source it and build a reputation. In fact we already open sourced a few elixir libraries.

We are a high growth startup. Building up customers and a product in 2016, and ready to hire and grow in 2017.

We plan to have a bi-annual outing twice a year to some (tropical) location in the world to come together in real life, work, and have fun together. 

### What are hard problems that your company is trying to solve?

Knowledge management is a big problem for a lot of companies. We intent to bring the technology to make it very easy to share content with people within an organization, and make it as easy to find what you need as a google search.

### Contact
Homepage: http://www.cogoplatform.com
Send your cv and motivation to: jaap@cogoplatform.com

**Comment by Gnouc** [comment]
@jfrolich I sent you an email 😄
