### ISSUE TITLE
Looking for new member Back end dev (Python)

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#388]
## Requirements

* 1 - 2 years experience with Python
* Framework: Flask, Django, Odoo
* Young, active & work under high pressure well

### You’ll be responsible for

* Dev back end for FPTPlay, Fshare, nhacso projects
* Research new technicals & apply for products
### You will get

* Salary around $650 - 700, 15-17 months/year
* Special culture, dinamic environment
* A lot of teams: game, football, volleyball, table-tennis, ...
* FPT Telecom building with more 2000 employees, good facilities
* Have good career path & have trained by good leaders, expert

### Contact
Homepage: https://fptjobs.com/
Email: chungnt12@fpt.com.vn
Phone: 08.7300.2222 - ext: 8496

**Comment by huydx** [comment]
@chung2604 please confirm to our job post guide at https://github.com/awesome-jobs/vietnam
