### ISSUE TITLE
MobileFolk - Ruby On Rails Developer - Hanoi,VN - FT

### ISSUE THREAD

**Issue by Vietvantue** [awesome-jobs/vietnam#389]
## Location

* 90 Hang Ma, Hanoi, Vietnam

## Salary Expectation

* 1K$ - 2K$
* Lunch provided
* Weekly team building activities
* Flexible working time
* Working 5 days/week

## Requirements
* Ruby On Rails (PHP, Java)
* PostgreSQL/MySQL/SQL/MongoDB
* 2+ years Software Engineering experience

## What You Are Good At
* Minimum of 2 years experience in web development with a portfolio of previous work
* Excellent knowledge of back-end web development
* Strong knowledge of database design, SQL knowledge, and performance optimization
* Excellent knowledge of at least one web programming language: Ruby, Python, Java, or PHP. We have an immediate need for Ruby skills, but will consider any candidate willing to learn.
* Strong experience with MVC frameworks such as Ruby on Rails, Laravel, Play! Framework, etc.
* Good English skills, especially reading/writing.

### Contact
* Homepage: mobilefolk.com
* Facebook: fb.me/thanggarung
* Phone: 0939.884.686
*  Email: viet@mobilefolk.com

**Comment by huydx** [comment]
@Vietvantue please conform to our guide at https://github.com/awesome-jobs/vietnam, thanks
