### ISSUE TITLE
Scuti.asia - Project manager PHP - Ha Noi - FT

### ISSUE THREAD

**Issue by JaneDang** [awesome-jobs/vietnam#393]
We are Scuti, which is the startup company established by the founder who was the previous General Director of Septeni Technology, one of famous Japanese companies in Asia about web and mobile applications.
Our mission is to provide web services which can change lives of South East Asia. If you have strong entrepreneurship and want to start business of your own in the future, this is very big chance. There is no better time to join us than right now.
Also, we really would love to contribute to Vietnamese IT industry. We can get much more experience and technical skill through development and operation of web services of our own than so to speak offshore development. Let’s keep learning and grow up.

## Location
* Cau Giay, Ha Noi, Vietnam

## Salary Expectation

* Up to $1000-$1500/month

## Requirements
* `PHP/Laravel`
* `MySQL`
* `Agile`
* `Linux servers`
### Must Have
*	Strong entrepreneurship
*	Strong mind to improve software quality
*	Strong mind to keep learning new technology
*	Experience & skill of PHP and its framework
*	Experience & skill of RDBMS such as MySQL
*	Experience to write test code
*	Experience of Agile process such as Scrum
*	Experience of source code review

### Ideally
*	Experience to develop services to consumers
*	Experience of method to keep quality such as TDD or pair programming
*	Experience to build & maintain large-scale web application
*	Experience to build & maintain mid-size of Linux servers
*	Experience to develop or operate non-stop system
*	Knowledge about performance tuning
*	Experience to build & maintain Linux servers with using Chef
*	Communication skill in English, Japanese

### Responsibilities

Great power comes with great responsibilities!

## You’ll be responsible for
* Manage progress and issues of multiple small projects
* Ensure any outputs of project members
* Build network and servers required these products above 
* Source code review 
* Educate & support the other members
* In charge of Scrum master

## Why it would be awesome to work with us
*	If you can show great performance during trial period, you can promote to project manager.
*	You have a chance to contribute to the society of not only Vietnam but also SEA
*	You can enjoy free working style
*	You get very wide range of responsibilities
*	You can be a core member of startup company
*	You can get support and review in any technical output by Japanese CEO.
*	You can experience to develop with using modern tools such as Jenkins (or CircleCI), Github, Slack, AWS, Chef-solo and so on.
*	You have a chance to make awesome business by yourself 
*	You can work in a startup environment where you can enjoy the growth of the project very closely 
*	Working in international environment with people from around the world 

## Contact
Scuti co ., ltd
R1508, N105 Building, Nguyen Phong Sac, Cau Giay, Ha Noi
Email: jane89@scuti.asia
Hotline: 04 6292 7275

**Comment by JaneDang** [comment]
`PHP/Laravel`

**Comment by hieuk09** [comment]
Hi @JaneDang, please strictly comply to our guideline here: https://github.com/awesome-jobs/vietnam/blob/master/README.md. You need to change:

- Title
- Indentation

**Comment by huydx** [comment]
@JaneDang please refer to https://github.com/awesome-jobs/vietnam/blob/master/ISSUE_TEMPLATE.md for detail template.

**Comment by hieuk09** [comment]
@JaneDang: it's almost done, you only need to change the title to 

```
Scuti.asia - Project Manager - Ha Noi - FT
```

And it should be good.

**Comment by JaneDang** [comment]
AI quan tâm gửi CVs cho em theo địa chỉ: jane89@scuti.asia nhé
Em xin chân thành cảm ơn
