### ISSUE TITLE
Holistics.io - Junior Engineer (BigData) - Ruby - Saigon - Full-time/Internship

### ISSUE THREAD

**Issue by nvquanghuy** [awesome-jobs/vietnam#395]
<img src="https://cloud.githubusercontent.com/assets/519800/14778031/e5e5f83a-0afa-11e6-8270-de16f0387aa8.png" width="300">

_We're a BigData product startup looking for a junior full-stack engineer who wants an environment to grow and enjoys working in fast-growing startup environment. Fresh graduates  and internship positions are available too._

* _Student Internship / Fresh Graduate / Junior Engineer (read below)_
* _[Senior Full-stack Engineer](https://github.com/awesome-jobs/vietnam/issues/339)_

Holistics is a data platform that allows analysts to deliver powerful analysis insights to end users.

Our product has helped improved data productivities of technology companies across the region (Singapore, Indonesia, Thailand, Malaysia, etc). Companies like **Grab**, **Traveloka** (Indonesian unicorn startup) are our proud unicorn customers among other well funded start-ups such as The Coffee House (VN), Tech In Asia, 99.co, ShopBack, KFIT, Aviasales, etc. 

We are growing rapidly during the last 1 year and we are looking for a **junior full-stack engineer/intern** to join our team to help build and scale our data platform product. This position will be based in Ho Chi Minh City.

## About Us
![Holistics Founders](http://i.imgur.com/leHG1Sz.jpg)

- We’re a small yet fast growing startup based out of Singapore and HCM. We have a strong engineering culture and understand what it takes to build a scalable software company.
- We are obsessed with code quality and code reusability, we refactor, clean up, and think about how to optimize our code everyday.
- Read how our co-founder [designed a data pipeline](http://engineering.viki.com/blog/2014/data-warehouse-and-analytics-infrastructure-at-viki/) that handled more than 100M messages a day. Joining us you’ll fully understand the Big Data landscape that people are talking about, down to the smallest technical level. 
- We recently collaborated with Grokking to teach the [BigData Engineering Course](https://www.facebook.com/grokking.engineering/photos/?tab=album&album_id=1270606876340611) in Ho Chi Minh City.

## Requirements
You'll get to work on all aspects of our product and platform: from front-end visualizations, implementing scalable, data-heavy features, helping customers with their complex SQL, to managing our servers that processed thousands of heavy jobs everyday.

- **Culture & Mindset:** You’re a team player; you want to understand how it’s like working for a startup -- doing anything and everything needed (from writing blog posts, to help customers with their data problem)
- **Technical Skills:** you are smart, fast-learner. It doesn't matter what programming languages you know, we'll teach you what we know. Btw, we use Ruby, PostgreSQL, Redis, AngularJS, ES6 and a lot of SQLs.
- **Communications:** Decent English skills

## Interesting Engineering Projects
Some interesting engineering projects we do at Holistics:

- Writing a database abstraction layer to interface with different database technologies at once: PostgreSQL, MySQL, Redshift, BigQuery, Presto
- Implement alert monitoring system using statistical algorithms
- ETL customer’s data from MongoDB to relational DBs with minimal overhead.
- Parsing SQL into an AST (abstract syntax tree) to understand semantics and suggest optimizations
- Build a sandboxed environment to execute arbitrary Python code that still ensures security

## Our Engineering Culture
- We don’t fancy free food or ping pong table, we focus on building an environment where our engineers can be productive and concentrate on solving good problems
- Our engineers own the product from end to end. They are involved in and get to speak directly with the customers to understand how they’re using it.
- We don’t write bad code to rush for deadline. We prefer spending more time refactoring the code over shipping bad code.

## Benefits
- Compensation: $700 - $1,000 (USD) for junior position, depending on skill levels.

Work location: Ho Chi Minh City, District 3.

## Internship

We welcome CS students who are looking for internship. Our internship is 3-6 month long. Internship is just title, you'll be given full responsibility just like full-time employees. 

**Notes**: It's required for intern to commit 32-40 hours / week

## Contact

Please email your resume and a short introduction about yourself to us at [talents@holistics.io](mailto:talents@holistics.io). Shortlisted candidates will be contacted for further interviews.

https://www.holistics.io

![a](https://ga-beacon-155513.appspot.com/UA-47899822-6/jobs/aj/fullstack-junior?pixel&useReferer "b")

**Comment by luvyouso** [comment]
thanks company.

**Comment by ntloi95** [comment]
I wonder about payment for internship?

**Comment by nvquanghuy** [comment]
@ntloi95 You'll receive payment depends on your skills level and your commitment/performance during your internship period. We don't have any limitation for payment. :)

**Comment by hainguyenp207** [comment]
Is still receive CV?

**Comment by duytruong** [comment]
Is this position still open?

**Comment by nvquanghuy** [comment]
Yes :)

**Comment by nvquanghuy** [comment]
We filled up this position. Please refer to this link for our new opening slot: 
https://github.com/awesome-jobs/vietnam/issues/461
