### ISSUE TITLE
Subiz Vietnam - PHP Developer - HN - FT

### ISSUE THREAD

**Issue by Vietnambiz** [awesome-jobs/vietnam#396]
## Location

* Hanoi, Vietnam
* Fulltime

## Salary Expectation

* Negotiable

## Requirements

* At least 2 years experience in PHP
* Be familiar with PHP Framwork (Laravel, Codeigniter)
* Have experience in MongoDB, Redis, Elastiecsearch
* Have experience in unit testing, documentation writing
* Proficiency in Bootstrap, JavaScript, HTML5, CSS3, jQuery
* Having experience in ReactJS, Angular JS, NodeJS, Golang, Docker is a plus
* Proficiency in using Linux, GIT
* Have ability to work individually and cooperate with others

### Responsibilities

- Optimize the stability of the current codebase
- Research and develop new features
- Find and fix bugs of the current features
- Design and develop RESTful API
- Build microservices architectures 

### Why it would be awesome to work with us
- Tech startup environment
- Young, dynamic and creative team who always work with love and fun
- Large volume of end-users
- Competitive salary
- Annual staff trip
- Health insurance, social insurance, unemployment insurance as prescribed by law

### What is hard problem your company are trying to solve
Subiz is a tech startup provides Live Chat solution for websites. Our vision is to become a Communication Platform which helps businesses around the world engage easily with their customers. 

### Contact
- Website: https://subiz.com
- Ms. Nhung - Recruiter: 0972.433.805
- Email: work@subiz.com (Subject: [SUBIZ] Position - Full name)

**Comment by huydx** [comment]
@Vietnambiz could you provide
- your homepage
- what is hard problem your company are trying to solve

**Comment by Vietnambiz** [comment]
@huydx: We've just added some information, please kindly check our issue again and let us know if there is anything missed.
