### ISSUE TITLE
Code Engine Studio - Ruby Dev - Da Nang - PT 

### ISSUE THREAD

**Issue by sahkoola** [awesome-jobs/vietnam#397]
## Location

* Da Nang, Vietnam

## Salary Expectation

* Competitive / Negotiable. Looking for a part-time Ruby contractor who can work weeknights or on weekends for up to 20hrs/week - we can pay by month or by hour.

## Requirements

* Ruby
* JavaScript, XML/JSON and REST API experience
* MySQL, PostgreSQL, or Mongo
* 2+ years Software Engineering experience

### Must Have

* Experience with building 3rd party plugins, mobile/responsive development, APIs, source control, and troubleshooting cross-browser/platform issues.
* Demonstrated understanding of revision control, bug tracking systems, and build and deployment methodologies.
* Proven analytical and problem-solving skills and a keen attention to detail.
* Passion for technology, a willingness to learn and a good attitude.

### Ideally

* Excellent English communication skills - both verbal and written.

### Responsibilities

* Developing Apps into polished, accessible, cross-device, responsive experiences; development of any or all aspects of the systems design, code construction, database design, unit and integration testing, and implementation.
* Demonstrates and applies strong technical leadership and knowledge to develop high quality, resilient software, as an individual contributor or as part of a scrum team.
* Collaborates with Project Managers, Product owners, Scrum Master, Dev and QA team members to perform analysis of functional requirements, user stories and specifications.
* Monitors industry trends on web technologies and related concerns to aid with roadmap planning and risk mitigation.
* Helps mentor, guide and review the work of more junior software engineers.

### You’ll be responsible for

* Building a new relocation app for a Startup in Silicon Valley

### You can bring

* Good friendly attitude
* Good team work 

### Why it would be awesome to work with us

For Full Time staff, some benefits include:
* Excellent salary with 13th month bonus and up to an additional 2 months performance bonus
* 5 day work week (Mon - Fri) with no overtime hours expected
* Emphasis on personal and career development (2 hours/week of English classes and weekly soft skills training during work hours)
* Opportunity to travel to other countries for training and work
* Free lunch everyday at the office and monthly team social events
* Fully English speaking environment working with clients from USA, Canada, Indonesia, Hong Kong and Singapore on portfolio piece projects for great clients

### What are hard problems that your company is trying to solve?

We have a tight project deadline and need some extra hands.  Our team is growing and if you like our team and environment, it may be possible to get a full time offer.

### Contact

career_at_codeenginestudio_dot_com 
codeenginestudio.com
facebook.com/codeengine/

## About Us

We are currently .  We are a young and energetic growing Canadian software development company in Da Nang looking for a dynamic individual who wants to work on a fun startup product from a client in Silicon Valley.

**Comment by huydx** [comment]
@sahkoola please confirm to our latest template

**Comment by sahkoola** [comment]
@huydx done.  Please let me know if you need any other edits.

**Comment by huydx** [comment]
@sahkoola looks better, but how about provide your homepage.
And your team currently not gonna solve any hard problem? so why it needs more people?

**Comment by sahkoola** [comment]
@huydx done.  thank you.
