### ISSUE TITLE
ARE YOU AN EXPERIENCED BACKEND DEVELOPER? JOIN US

### ISSUE THREAD

**Issue by Lyphan** [awesome-jobs/vietnam#398]
## Location

* Saigon, Vietnam
* Fulltime

## Salary Expectation

Up to $1,500USD

## Requirements

* Proven work experience as a backend developer
* Experience with technologies needed for a chat app like Ejabberd server, Erlang (NodeJS is welcome), XMPP protocol, Mnesia & MySQL together with other necessary skills for storage, operating system, push notifications etc
* Familiarity with front-end languages

## Skills

* Proven analytical and problem-solving skills and a keen attention to detail
* Passion for technology, a willingness to learn and a good attitude
* Ability to communicate in English

### Must Have

Be able to fly (just kidding)

### Ideally

Full stack capability is a big plus

### Responsibilities

Great power comes with great responsibilities! You are the one who designs and implements the backbone of our virtual design and construction solutions used for our product. Be responsible for managing the interchange of data between server and users. Develop all server-side logic, definition and maintenance of the central database, and ensuring high performance and responsiveness to requests from the front-end etc. You know all those stuff!

### You’ll be responsible for

Further developing our new business features. Thrilled to see all business organizations and companies using our fantastic product for daily work communication? JOIN US! 

### You can bring

Your passion

### Why it would be awesome to work with us

We are a brand-new, global and funded startup located in Australia and Da Nang - Ho Chi Minh - Viet Nam. 

We have:

* Startup culture, a lot of opportunities to grow on a steep learning curve
* Company trip, team building and a lot of eating together
* Attractive, competitive salary and incentives: up to $1,500USD/month
* Opportunity to travel to other countries for training and work
* Modern office with relax area, free snacks and beverages
* Opportunities to work with international experts and cool startup entrepreneurs

### What are hard problems that your company is trying to solve?

We need more hands to further develop our new features for business organizations. We’re excited about our growth and excited to meet the person who will join our team and help take us to the next level in our operation. If that’s you, we can’t wait to meet you!

### Contact

Email: lyphan.dn@gmail.com (Subject: [githubpost] Backend Dev - Full name)

**Comment by huydx** [comment]
@Lyphan 
1. please follow our template
2. are you representative of the company.
2.1 if yes, please give us information of the company (name), and use company-domain email (don't use gmail, please)
2.2 if no, you're not eligible to post job here

**Comment by Lyphan** [comment]
@huytd 
I closed this issue and will prepare a new one following your advice. Tks!

**Comment by Lyphan** [comment]
@huydx 
I closed this issue and will prepare a new one following your advice. Tks!
