### ISSUE TITLE
Reliasystems - RoR Developer - Saigon - FT/PT

### ISSUE THREAD

**Issue by ducle** [awesome-jobs/vietnam#40]
## Location
- Ho Chi Minh City, Vietnam
- Golden Bee building, Phu Nhuan district.
## Requirements
- Knowledge of Ruby On Rails - experienced or junior level.
- Analytics thinking and quick learning for pickup new technologies.
- English: reading and writing fluently.
## Pay and Benefits
- Great working environment
- Flexible working hours. 
- Working with real projects , great change to improvement skills.
- Ability to work and get trained with other modern web frameworks: MEAN stack/ Nodejs/ Backbonejs
- Salary negotiable once per six months.
- Suitable for newly graduates.
## Contact

Le - jobs@reliasoftware.com - 0972 016100

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
