### ISSUE TITLE
PHP Developer

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#403]
## Location

* Saigon, Vietnam

## Salary Expectation

* Up to $700/month

## Requirements
* University Qualification in Software Engineering or a related degree
* At Least 1,5 Years Experience in PHP

## Skills
* PHP
* Laravel
### Must Have

* Proven web development experience in PHP
* Familiar with at least one MVC framework (such as Laravel, Yii, etc)
* Good knowledge of relational databases (such as MySQL, PostgreSQL)
* Experience working with HTML, CSS, and Javascript

### Ideally

* Experience with PHP - Backend

### Responsibilities

* Improve all applications in Start-up Dept (FPTPlay, Fshare)
* Researching & update new technical, write new app as requirement
* Other tasks from PHP Team Leader

### You’ll be responsible for

* Building PHP backend & Front-end for Start-up apps

### You can bring

* A good skill for researching & development
* PHP Skill, teamwork & leader skill

### Why it would be awesome to work with us
* Working in an active and challenging environment
* Good in competition & benefit, we have FPTCare to protect your health
* We have unique culture with alot of vacations, team building, ...
* More and more, come with us to enjoy!

### Contact
Homepage: fptjobs.com
Email: chungnt12@fpt.com.vn

**Comment by huydx** [comment]
@chung2604 could you please read our guideline for job post?
