### ISSUE TITLE
Ownego - JS/PHP Developer - Hanoi - PT

### ISSUE THREAD

**Issue by ducnm9990** [awesome-jobs/vietnam#404]
## Location

* Hanoi, Vietnam 
* Internship or Junior

## Salary Expectation

* Agreement

## Requirements

* Javascript basic or PHP basic

### Must Have

* Familiar with Javascript or PHP  

### Responsibilities

* Join developing projects in regard to front-end or back-end development

### You’ll be responsible for  

* Building a website or mobile application 

### Why it would be awesome to work with us

* Learning by doing projects
* Joining a friendly environment of a startup
* Challenging with international market
* Joining seminar, team-building every week
* Support allowance per month

### What are hard problems that your company is trying to solve?

* Lack of employee

### Contact
Homepage: ownego.com 
contact@ownego.com
fb.com/ownego

**Comment by huydx** [comment]
@ducnm9990 your job post is too general and does not give much information. Could you please refer to another tagged job post and rewrite this properly?
