### ISSUE TITLE
ZIGExN VeNtura - PHP Developer - HCM - FT

### ISSUE THREAD

**Issue by venturahr** [awesome-jobs/vietnam#409]
## Location

* District 10, Ho Chi Minh City, Vietnam

## Salary 

* Above $700

## Description
* Join in a product/system design phase with Japan team to analyze system requirements
* Suggest, propose creative solutions to solve problems
* Design, develop and test high-traffic Web application in Ruby on Rails (sometime do DevOps to deploy to production)
* Write technical documentation

## Requirements 
**EDUCATION**
* Graduated from College/University in Information Technology/Computer
* At least 2 years experience as a Web developer in PHP or Java language

**TECHNICAL EXPERIENCES**

_MUST HAVE_
* Ability to learn fast other technologies to adapt with projects (provide intensive training course)
* Programing experience with PHP (OOP)
* Experience with MVC frameworks (Symfony, Code Igniter, Struts, Spring …)
* Experience with Database system (MySQL/MongoDB)
* Experience with Linux (Ubuntu, CentOS)

_NICE TO HAVE_
* Experience with Redis, Index Engines (Apache Solr, Elastic Search)
* Server Deployment (AWS, Chef)

_LANGUAGE SKILLS_
* Can basically communicate (writing, speaking) in English. Japanese is a huge plus. 

## Why it would be awesome to work with us

1. BE RECOGNIZED - Well Training and Developing Environment
* Provide Intensive Ruby/Ruby on Rails training course for skill-up
* Skillful technical mentors are always there to help
* Occationally have training in Japan and more opportunities working at ZIGExN in Japan
* Regularly receive feedbacks from Leader/Manager
* **"3-months" Performance Evaluation** for Income and Career Development (Total 4 times/year)

2. POSITIVE Team with lots of FUN & CHILLs
* Providing Free Snacks (Kitkat, Choco Pie...), Fresh Milk, Coffee, Tea, Yogurt, Red Bulls..
* Happy Events: Birthday, Pizza Party, X-mas, Halloween and Full Moon Festival...
* Sports activities: Football, Table Tennis, Swimming Clubs and Badminton...
* Company Events:Quarterly Event, Year End Party, Yearly Company Trip and Other Occationally Events/BBQ...

3. We care about your HEALTH
* Bao Viet Premium Health-care packages
* 24-hrs accident insurance
* Annual Health-care checkup 
Trollman: trollman_at_gmail_dot_com (mobile number optional)

## About ZIGExN VeNtura 
**ZIGExN VeNtura** is an incorporating 100% Japanese-owned company specialized in software development and Internet services. ZIGExN (http://zigexn.co.jp) in Japan is a fast-growing Internet company, has been awarded Japan Technology Fast50 by Deloitte in 2011 - 2015 and Japan Great Place to Work in from 2011 - 2015. ZIGExN is developing and operating many large Internet services in Japan such as Recruiting websites (http://arubaito-ex.jp) , Property websites (http://smocca.jp) 
With a motto “BE A CREATOR”, ZIGExN VeNtura is striving for its visions:
1. To provide an empowering platform for each individual to maximize their strength and ability
2. To develop and operate innovative Internet services for Vietnamese market
3. To bring innovative Internet services from Vietnam to the World

### Contact
Homepage: http://zigexn.vn
To apply, please send your documents to g-hr@zigexn.vn

Homepage: https://zigexn.vn
Phone:(08) 38-633-399

**Comment by joneslee85** [comment]
@venturahr can you please update the job title to comply with our [guideline](https://github.com/awesome-jobs/vietnam#title-format)? Besides why do this job mention about Rails?

**Comment by venturahr** [comment]
@joneslee85 our main language working here at ZIGExN VeNtura is ROR. However, if PHP developers are willing to learn and work with ROR, we welcome as well. Thank you.

**Comment by venturahr** [comment]
@joneslee85 Hi, please help me here with the pending label
