### ISSUE TITLE
Node Backend Developer 2-3 month contract [Full-remote, Canada]

### ISSUE THREAD

**Issue by peter-wd-1** [awesome-jobs/vietnam#4130]
Closed

**Comment by vosylienthanh** [comment]
# Personal info
- Fullname: Võ Sỹ Liên Thành
- Email: vosylienthanh@gmail.com

**Comment by peter-wd-1** [comment]
> # Personal info
> * Fullname: Võ Sỹ Liên Thành
> * Email: [vosylienthanh@gmail.com](mailto:vosylienthanh@gmail.com)

Sent you an email

**Comment by develrocket** [comment]
Name: Xiaojang Li
Email: xiaojang201224@gmail.com

https://www.hackerrank.com/profile/xiaojang201224

**Comment by peter-wd-1** [comment]
> Name: Xiaojang Li Email: [xiaojang201224@gmail.com](mailto:xiaojang201224@gmail.com)
> 
> https://www.hackerrank.com/profile/xiaojang201224

Sent you an email

**Comment by develrocket** [comment]
> > Name: Xiaojang Li Email: [xiaojang201224@gmail.com](mailto:xiaojang201224@gmail.com)
> > https://www.hackerrank.com/profile/xiaojang201224
> 
> Sent you an email

I am sorry for late reply. I replied to your email. Please check it. Thank you.

**Comment by adminGit71** [comment]
Name: Nicolas Sammaritano
Email: nicolas.edgardo1028@gmail.com
portfolio: https://adminGit71.github.io
