### ISSUE TITLE
Fastwork.co Looking for Golang Backend Developer (BKK, THAILAND)

### ISSUE THREAD

**Issue by palaa159** [awesome-jobs/vietnam#415]
## Location

* Bangkok, Thailand

## Salary Expectation

* $1,000 - 2,000 (Negotiable)

## Requirements
* Be able to work full-time at Bangkok Headquarter
* Experience with Golang
* A working knowledge of Node.js or Python is a plus

### You’ll be responsible for

* Building strong and advanced APIs, Data Pipeline for Fastwork
* Implement new features with Design, Business, and Frontend Team

### You can bring

* Data Analytics Skill

### Contact
Homepage: https://fastwork.co
Email: hello@fastwork.co
Mobile: +6683O72O888

**Comment by huydx** [comment]
@palaa159 please read our README and conform to our format
