### ISSUE TITLE
[Sparx*] - [Junior Technical Artist] - [HCM] - [FT]

### ISSUE THREAD

**Issue by Sparxvietnam** [awesome-jobs/vietnam#416]
## LOCATION

* Saigon, Vietnam

## SALARY

* Negotiable

## REQUIREMENTS
* Willing to work in the 3D industry, mostly for video games, and to act as a support for our teams of Artists.
* Enjoys working in a team: though in a small team, he will code tools and implement solutions to support bigger teams of 3D Artists and Animators. 
* Particularly interested in real-time computer graphics.
* Formal education in programming :

  -	Strong scripting skills on Python 
  -	Good Java script skills, as well as SQL and Qt
  -	Decent skills in C++ 
  -	Basic notions in network programming
  -	Basic understanding of computer hardware to be able to communicate with the IT team

* Ideally, 2 years of professional experience working with famous game engines like Unity, Unreal or Cry Engine, and with famous DCC applications like Maya or 3DSMax.
* Decent English level (speaking and listening).
* Very good English level when it comes to reading: must be able to understand software specifications written in English, and to interpret written briefs from customers. 
* Very good communication skills: must be able to share ideas, to explain a problem, and to receive feedback and suggestions on the work done.
* Must be careful, organized, proactive and willing to help.
* Flexible and willing to learn, including good ability at self-learning.

### RESPONSIBILITIES

* Works on specific 3D projects, in tight collaboration with the Art Director, the Producer and the Team Leader of those projects.
* Provides day-to-day technical support for his team of Artists, mainly regarding project configuration and pipeline, Artists workflow, QA, and enforcement of client’s technical requirements.
* Write tools under the supervision of a dedicated Senior Technical Director.
* Can also collaborate with our other Technical Directors.
* Configures and adapts proprietary tools, client tools or other existing tools depending on project specificities.
* Deploys customers tools, manages data transfers and interface customers systems with ours.
* Manages the render dispatcher for his projects when relevant.
* Constantly strives to optimize Artists workflow by helping them solve technical issues and automate repetitive tasks.

### WHY JOIN US?
* Work on Hollywood blockbusters and AAA games
* Join an elite international team
* Grow with love, fun and creativity

### ABOUT US
Sparx* is creating games, VFX and animated shows for the leading entertainment and technology companies around the world including Disney, Industrial Light and Magic, Lucasfilm Animation, Electronic Art, Square Enix, Ubisoft, Warner Bros. 

In 2011, Sparx* was acquired by Virtuos, one of the largest providers of digital entertainment production services, which today serves 15 of the world's top 20 digital entertainment publishers in the movie and game industries.

We are the only studio in Vietnam to have released a 3D feature animated movies and have worked on so many awesome Hollywood blockbusters and AAA titles.
Our mission is to provide outstanding quality services that exceeds the expectations of our clients.
Our staffs are the vibrant heart of our success and we are committed to grow their talent in a fun and creative environment.

### CONTACT
Homepage: www.sparx.com
Phone:(08) 399 768 43
To apply, please send your CV to wewantyou@virtuos-sparx.com
[Sparx - Job Description - Junior Technical Artist - 2017.pdf](https://github.com/awesome-jobs/vietnam/files/770336/Sparx.-.Job.Description.-.Junior.Technical.Artist.-.2017.pdf)

**Comment by joneslee85** [comment]
Please create the post again that follow our template (check the title format)
