### ISSUE TITLE
[Kins Solutions] - [Senior Ruby On Rails] - [HCM] - [FT]

### ISSUE THREAD

**Issue by datvo** [awesome-jobs/vietnam#417]
## Location

* Saigon, Vietnam : District 2 and District Tan Binh
38A Le Van Huan Street, Tan Binh District, HCM

## Salary Expectation

* Up to $2500 NET 

## Requirements
- Degree or Diploma in Computer Science, Computer or Electronics Engineering, Information Technology or related disciplines.
- Minimum 2 years experience in any of the followings: Ruby on Rails, Golang
- Good UI/UX design sense and able to develop designs in HTML/CSS/JS
- Familiar with at least one front-end UI framework: AngularJS, ReactJS, EmberJS
- Familiar with linux system administration and provisioning systems using Amazon Web Services
- Able to apply good security practices
- Pedantic about software engineering best practices: code formatting, refactoring, easy to maintain etc.
- Enjoys challenging (and fun) software development work
- Keen to communicate with the team (err on the side of over communicating. Language barriers aside, candidate must be willing to make an effort to communicate as much as he can)
- Overthink security
## Extra Requirements
- Familiar with and passionate about BitCoin, its network and protocol
- Able to code in multiple languages - Java, Scala, Golang, Ruby
### Must Have

* GOOD ENGLISH SPEAKING 

### You’ll be responsible for

- Full stack developer to maintain and develop CoinHako's online services.
- Work closely with product development team to improve our platforms and contribute feature ideas and designs (visual & conceptual) for our website, mobile web and applications.
- Participate in user testing on production.

### Contact
Homepage: www.kinssolutions.net
skype: datvdt
email: datvo@kinssolutions.net

**Comment by joneslee85** [comment]
Please create new post that comply with our template. Check the title format please.
