### ISSUE TITLE
JAM Group - Javascript Deveveloper - Remote/Hanoi - C

### ISSUE THREAD

**Issue by nhim175** [awesome-jobs/vietnam#419]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* up to $1200/month (will consider every 6 months based on performance)

## Requirements
* HTML
* CSS
* Javascript
* AngularJS, NodeJS
* Linux
* 3+ years Javascript programming experience

### Must Have

* A Linux or Mac PC
* Deep knowledge about Javascript, CSS

### Ideally

* Experience with Responsive web development
* Experience with Javascript test frameworks like Jasmine, Mocha

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building a new matching platform
* Finish your tasks on time

### Why it would be awesome to work with us

* We are an awesome startup based in Tokyo with team members from all around the world

### Contact
Thinh Pham: thinhpham175@gmail.com

**Comment by joneslee85** [comment]
@nhim175 would you be able to provide an intro on what your startup is about?

**Comment by nhim175** [comment]
@joneslee85: It's like a matching service that helps people find pros/helpers easier
