### ISSUE TITLE
GKIM - Ruby on Rails Developer - Remote / HCMC - PT

### ISSUE THREAD

**Issue by kythanh** [awesome-jobs/vietnam#420]
![GKIM Digital](https://s3-ap-southeast-1.amazonaws.com/gkim-digital/logo/imgpsh_fullsize.png)

## Location

* Saigon, Vietnam
* Working Remote

## Salary Expectation

* Negotiate $ per hour.

## Requirements
* Experiences on Ruby on Rails.
* PostgreSQL

### Contact
Homepage: https://gkim.digital
Please contact our HR at hr@gkxim.com for more details.

**Comment by joneslee85** [comment]
@kythanh your post lack some sections that we care. Please see the README and update the post accordingly.
