### ISSUE TITLE
Senior PHP Developer

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#423]
## Location

* Tan Thuan, District 7, Saigon, Vietnam
* Full Time

## Salary Expectation

* Around $700

## Requirements
* Engineering qualification in Software major
* At least 2 years experience in PHP
* Familiar with laravel or Yii framework

## Skills
PHP Developer; Laravel framework

### Responsibilities

Build up product for FPT-er in VAS Dept - R&D
Researching new technology for projects

### You’ll be responsible for

* Building some projects in R&D

### Why it would be awesome to work with us
* Good salary/year & competition
* Active environment
* Young & smart, funny co-workers

### Contact
Homepage: fptjobs.com
Email: chungnt12@fpt.com.vn

**Comment by huydx** [comment]
@chung2604 last time I warn you, read our guideline carefully, or you will not be eligible to post job here any more

**Comment by joneslee85** [comment]
@chung2604 there has not been any changes for the last 6 days. I am closing this post. Please create a new one that follow our template.

**Comment by chung2604** [comment]
Hi,
Sr about reply you late, 
I'v read the guideline & wanted to do all things as your requirement & other post, but i don't know how to post the right advertising
Let me know about my mistakes!
Tks u, guys
