### ISSUE TITLE
GKIM - Testers - HCMC - FT

### ISSUE THREAD

**Issue by kythanh** [awesome-jobs/vietnam#429]
![GKIM Digital](https://s3-ap-southeast-1.amazonaws.com/gkim-digital/logo/imgpsh_fullsize.png)

## Location

* Saigon, Vietnam
* Working Fulltime.

## Salary Expectation

* Negotiate during the interview.

## Requirements
* Develop test plans, test cases and testing scripts, for manual and automated testing for websites / cms / mobile applications (iOS / Android).
* Do manual testing (execute test plans follow test cases, reporting detail steps that caused the issues) for each projects.
* Working closely with developers, designers, project managers and product owners during project development life cycle.
* Review and verify all release notes for all releases that going to release to customers or deploy to production system (App stores or live server).

## Skills
* Known some testing tools like JMeter / Blazemeter.
* Used to work with testing scripts for automate test cases with complicate workflow is a plus.
* Basic knowledge on Agile to support new testing tasks from new requirements.
* Strong knowledge on UI / UX of iOS and Android is a plus.
* Good knowledge on database design is a plus.
* Experience to use Redmine / Easy Redmine is a plus.

### Contact
Homepage: https://gkim.digital
Please send your latest profile to our HR at hr@gkxim.com, we will arrange the interview with you in shortly.

**Comment by hieuk09** [comment]
Hi @kythanh, could you please update the job post to comply with our template?

**Comment by kythanh** [comment]
Hi @hieuk09,
I've udpated my post again. Thanks for your reviewing.

**Comment by joneslee85** [comment]
Your post lack:

```
### Why it would be awesome to work with us (MUST)

### What are hard problems that your company is trying to solve? (MUST)

### Contact (MUST)
Homepage: trollman.com
Trollman: trollman_at_gmail_dot_com (mobile number optional)
```
