### ISSUE TITLE
New Tech Start-up - Senior Backend Engineer - FT

### ISSUE THREAD

**Issue by hvh62** [awesome-jobs/vietnam#4290]
## Location
* Saigon, Vietnam
* On-site

## What we offer
* Salary: Up to 70M gross/month
* Opportunity to work on a product that impacts millions of users.
* A dynamic and supportive work environment.
* Premium health insurance for you and your family.
* Professional growth and development opportunities.

## Requirements
* Minimum 8 years of experience in software engineering, preferably in the VPN or network security field, with at least 3 years as senior engineer.
* Strong background in building and scaling high-traffic systems.
* Solid understanding of networking fundamentals (TCP/IP, DNS, SSL/TLS).
* Experience in VPN protocols such as WireGuard is a big plus.
* Write clean, maintainable, extensible and idiomatic Golang. Experience in Rust or C is a plus.
* Experience in designing and optimizing large databases for efficient data storage and retrieval.
* Understanding of DevOps practices, including continuous integration and deployment (CI/CD), containerization (e.g., Docker), and orchestration tools (e.g., Kubernetes).
* Good knowledge of secure coding practices.
* Excellent at teamwork and communication, great attention to detail.

## Key Responsibilities
* Designing, developing, and implementing new features for the backend system of the VPN product.
* Optimizing the performance and reliability of the system to ensure stable operation and high connection speeds.
* Participating in the analysis and resolution of complex technical issues related to the backend system.
* Working closely with other team members to ensure compatibility and consistency of the system.
* Contributing to the establishment and maintenance of best software development practices to ensure the quality and performance of the product.
* Working with the engineering team to explore and create new designs/architectures geared toward scalability, stability and performance of the product.

**Comment by rkt2spc** [comment]
@hvh62 còn tuyển không bạn?

**Comment by hvh62** [comment]
> @hvh62 còn tuyển không bạn?

Còn nhé bạn
