### ISSUE TITLE
Backend Engineering Lead (Ruby-on-Rails)

### ISSUE THREAD

**Issue by dinhthi1610** [awesome-jobs/vietnam#432]
**Backend Engineering Lead (Ruby-on-Rails)**
**Salary** : $1000 - $1500

**Location** : Ho Chi Minh City (Binh Thanh District), Vietnam

Competitive Pay & Bonus + Medical Insurance + English Lessons

**About Wonolo**

Wonolo is the leader in On-Demand Staffing.

Everyday, we are creating flexible opportunities for people to make extra income,

learn new skills, and change their lives.

Wonolo was is funded by companies and investors including The Coca-Cola

Company, PivotNorth, Temp Holdings, Duke University and Stanford University.

**The Role**

We have a rapidly growing engineering team in Ho Chi Minh City (Binh Thanh

District). Today the team is 9 people and growth will continue in 2017. Wonolo is

committed to building a culture in Vietnam that provides autonomy, ownership,

the opportunity for growth and lots of fun; very different to an outsourcing

company.

The HCMC team is currently divided into 3 teams: Backend, Mobile Apps and

QA. This role is to lead the Backend team. You will report to the Backend

Engineering Manager in San Francisco, CA, USA, who is a native Vietnamese

speaker.

This role will initially be a mixture of hands-on coding with management of the

team.

**Experience**

x 2+ years experience managing/leading an engineering team

x recent, hands-on software engineering experience in Ruby-on-Rails and

JavaScript. You must have sufficient hands-on skills to earn the respect of

the current backend development team.

x experience with agile software development, preferably with Kanban/just-
in-time development

x experience with high-traffic, consumer-facing web applications and the

scalability challenges they create

x experience with automated testing and test-driven development

x preferred, experience working remotely with a team located in the US

**Attitude**

x “can do” attitude, self-starter, able to deliver results independently without

close management (your boss will be 15 hours and 7,800 miles away)

x ability to lead and inspire a team of engineers to write great code and hold

them accountable to deliver results - you will be an important and

influential voice in building the team culture

**Contact**

skype : dinhthi1610
email: thi@wonolo.com

**Comment by hieuk09** [comment]
Please create another post followed our [guideline](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). This job post will be closed.
