### ISSUE TITLE
Front-end Web Engineer (JavaScript/Ruby-on-Rails)

### ISSUE THREAD

**Issue by dinhthi1610** [awesome-jobs/vietnam#433]
**Front-end Web Engineer (JavaScript/Ruby-on-Rails)**

**Salary** : 
 $1000 - $1300
**Location**
Ho Chi Minh City (Binh Thanh District), Vietnam

Competitive Pay & Bonus + Medical Insurance + English Lessons

**About Wonolo**

Wonolo is the leader in On-Demand Staffing.

Everyday, we are creating flexible opportunities for people to make extra income,

learn new skills, and change their lives.

Wonolo was is funded by companies and investors including The Coca-Cola

Company, PivotNorth, Temp Holdings, Duke University and Stanford University.

**The Role**

We have a rapidly growing engineering team in Ho Chi Minh City (Binh Thanh

District). Today the team is 9 people and growth will continue in 2017. Wonolo is

committed to building a culture in Vietnam that provides autonomy, ownership,

the opportunity for growth and lots of fun; very different to an outsourcing

company.

You will be responsible for enhancing our Customer Portal web application,

which is built in JavaScript/JQuery and Ruby-on-Rails. You will become the

team’s go-to JavaScript expert.

**Experience**

x 2+ years web development experience

x 1+ years jQuery and/or related front-end technologies (Backbone.js,

Angular, etc)

x experience implementing web views from designs provided

x solid, common-sense understanding of UX issues

x cross-browser compliance

x preferred, experience working remotely with a team located in the US

**Attitude**

x You will have a passion for clean, intuitive UX

x You’ll be a JavaScript athlete, adept with JQuery and familiar with other

libraries such as Angular or Backbone

x You’ll have the engineering chops to get the respect of engineers but the

design sense to get the respect of designers

**Contact**
skype : dinhthi1610
email : thi@wonolo.com

**Comment by hieuk09** [comment]
Please create another post followed our [guideline](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). This job post will be closed.
