### ISSUE TITLE
Meete HCMC is looking for PHP DEVELOPER!!

### ISSUE THREAD

**Issue by hrmeete** [awesome-jobs/vietnam#434]
## About Meete

Meete is a startup which provides restaurants and food stalls’ e-vouchers under the form of promotion codes. Currently, Meete has existed in HCMC and Ha Noi, and is planning to expand to other areas. Since establishment in 2015, Meete has been awarded Best Newcomer at the Rice Bowl Startup Awards.

## Mission

Help build Meete’s new website system, become an admin to manage and api for merchants.

## Location

* Ho Chi Minh City, Vietnam
* Full time/Part time/Internship

## Benefit package

* 8 million ~ 10 million/month depending on skills and experiences
* lunch

## Requirements
* Minimum one year experience
* Strong programming skill in PHP, MySQL
* Experience with one of frameworks Symfony, Zend, Laravel
* Experience with Git
* Experience with Linux
* Good knowledge of OOP
* Good knowledge of some popular design patterns
* Having knowledge of performance tuning (code, database)
* Having knowledge of RESTful Web Services is an advantage
* Having knowledge of Java programming skill (SE, Spring) is an advantage
* Quick-learning, active, and eager to learn

### Contact

Please kindly send your CV via email to tuan@meete.co (Mr. Tuan). Title: [Full name]Position - CV
If you have any questions, please feel free to send email.

**Comment by joneslee85** [comment]
Please read the README carefully on our guideline and feel free to re-create a new job post.
