### ISSUE TITLE
Fulltime Remote - JavaScript fullstack engineer

### ISSUE THREAD

**Issue by tieuvu9x** [awesome-jobs/vietnam#4346]
## Location

* Fulltime Remote, Viet Nam

## Salary Expectation

* up $5,000, willing open range

## Required skills and experiences
- At least 3 years of full-stack JavaScript development experience
- Excellence in NodeJS, Typescript
- Experience working with REST API
- Fluent English
- Entrepreneurial, with a high tolerance for ambiguity
- Strong work ethic and ability to work independently

**Preferred skills and experiences**
-  Proficiency in GCP, cloud deployment, CI/CD
- Experience with LLMs (OpenAI API, Langchain, HuggingFace, etc.)

## Job overview and responsibility
We are a fast-growing startup in the logistics space led by a founding team from companies like Airbnb and Uber Freight. We value independent thinking, drive, and hunger for learning, and are in search of a Founding Software Engineer to join our remote team and contribute to the foundation of our tech culture.

We believe that with the advance of AI, a small group of top-notch engineers can achieve amazing things. We keep our team lean and look for the exceptional talent. Our interview process is competitive and we pay well above the market rate for best talent. 

Here are a few signs you'd be a good fit:
You have strong applied full stack engineering experience, preferably at start-ups 
You were a top 10% performer at previous companies
You get excited about taking products from 0 to 1

## Why Candidate should apply this position
- Opportunity to work on cutting edge AI tech
- Flexible remote work team
- Stock option
- Competitive salary

### Interview process
Coding Challenge (Hackerrank - 1 hour) -> Tech Interview -> Work trial (typically lasts 5 days, but can be flexible if the candidate is currently working a job - we pay salary for this period)

- Work trial is part of the interview process NOT a probation period

- The HackerRank challenge will be a hands-on test that will involve working with JavaScipt and RestAPI

## How to Apply
Kindly contact to me for further information via +84 915 500 810 (Zalo/WhatsApp/Telegram); Skype ID: natsuyuki91/ Telegram ID: @leephuongg
https://www.linkedin.com/in/leephuong/

**Comment by kabeer95** [comment]
HERE IS MY LITTE BIT INTRODUCTION 

Myself Kabeer Anees Full Stack InfraStructure Engineer , I have 6 years plus experienceas Full stack developer having built large scale data applications with complex business logicsto incorporate cutting edge technologies . At scoro.com I used asynchronous generators in JS to stream 250K products to the S3 bucket in real-time, to generate multiple 250mb+ files via ECS and Fargate.


⚡ Architected Pub/Sub APIs and Serverless Node AWS Lambda functions leveraging AWS SQS and AWS SNS to execute functions on specific triggers and to handle complicated eCommerce flows. Engineered a solution to stream multiple 250mb+ files uploaded daily using AWS ECS on S3.

⚡️ Implemented DevOps CI/CD pipelines using Infrastructure as a Code tooling such as Terraform and AWS CDK. Developed applications on Nest.js and infrastructure involving bash Scripting, IAC, NX  monorepos, and external Integrations.


I possess an advanced understanding of the development life cycle, utilizing Test Driven
Development (TDD), iterative methodologies, and Agile Scrum practices. I am highly proficient
in backend web development with Python and JavaScript.
● Python Backend Development: Skilled in developing web applications using Flask,
Django, and FastAPI.
● JavaScript Backend Development: Experienced in building backend services with
Node.js.
● Containerized Development: Expert in Docker for containerized development and
deployment.
● AWS Cloud Expertise: Four years of extensive experience in AWS cloud development,
automating the deployment of numerous web applications across various AWS hosting
environments.
● AWS Microservices and Serverless: Proficient in leveraging AWS Serverless
technologies to build infinitely scalable applications. Expertise in AWS Lambda, API
Gateway, S3, SNS, SQS, AWS Aurora, EventBridge, SES, Pinpoint, and CloudFront.
● High Workload Management: Experienced in running high workload jobs using AWS
Batch.
● Workflow Automation: Proficient in using AWS Step Functions for building distributed
applications, automating processes, and orchestrating microservices.
● Container Management on AWS: Skilled in running containerized applications on AWS
ECS and managing container images with ECR.
● Domain and Certificate Management: Utilizing Route53 and ACM for managing
domains and SSL/TLS certificates.
● Scalable Infrastructure: Expertise in setting up EC2 instances for various workloads
with automated scaling and traffic management using Auto Scaling Groups and Load
Balancers.
● Access Management: Utilizing AWS IAM for granular access control to different AWS
services.
● Infrastructure as Code (IaC): Proficient with Serverless Framework, AWS
CloudFormation, AWS CDK, and Terraform for infrastructure provisioning and
management.


Let's get onto the short call to disucss the technical aspects of the project
