### ISSUE TITLE
foobla - Senior WordPress Developer - Hanoi - FT

### ISSUE THREAD

**Issue by nvg58** [awesome-jobs/vietnam#435]
<img src="https://cloud.githubusercontent.com/assets/5056439/19954330/ed170ee6-a1a9-11e6-91fa-9556d8cf8595.png" alt="foobla-logo" width="200">

## Who We Are
We are foobla, a global company founded in 2007 working with popular CMS like WordPress and Joomla. Since there, every product we made, we made for lazy users. Some featured products can be listed:
- obRSS - Joomla RSS Feed Syndicator
- obGrabber - Auto Content Grabber for Joomla
- obSocialSubmit - Auto Social Poster for Joomla
- WPPipes - Powerful Online Services for Making Pipeline of Data 
- LearnPress - Comprehensive WordPress LMS Plugin for WordPress

## Why We Need Your Help
We are seeking a Senior WordPress Developer responsible for back-end development, including developing new features for LearnPress and WPPipes. This position requires a combination of programming skills (namely PHP, HTML5, CSS3, and JavaScript) and aesthetics (understanding element arrangements on the screen, the color and font choices, and so on). The candidate should have a strong understanding of industry trends and content management systems. Experience with the responsive and adaptive design is strongly preferred. Also, an understanding of the entire web development process, including design, development, and deployment is preferable.

## You Will Be Responsible For
* Participate in WordPress projects including designing and implementing new features and functionality
* Ensuring high-performance and availability, and managing all technical aspects of the CMS

### Must Have
* Responsible, sociable, able to work in group
* Good ability to self-training and self-studying on new technologies
* Highly skilled in PHP or equivalent to 2 years working experience
* Experience developing web applications powered by WordPress
* Strong understanding of OOP

### Ideally
* GIT workflow
* WordPress Plugin development
* Experience with JavaScript/jQuery

### Big Plus
* Good English skills
* Familiar with Agile Development / SCRUM
* Knowledge in SEO

### Basically
* Open and honest culture where people are valued, treated fairly, trusted and empowered to do great things
* Always listen to your ideas and feedbacks
* Work as a member in fun, fast-paced, and friendly team
* Attractive, competitive salary
* Year-end bonus
* 40 hours work weeks (8:00-17:00, Mon-Fri)
* Very fun and friendly colleagues and professional working style
* Office as a villa with quiet, fresh environment and plenty of trees

### And More
* Performance and salary review every year
* *Medical Insurance* will be paid by the company
* *Hackathon* every month. You get the bonus for your awesome ideas!
* Company trip every year
* Team building events, party monthly and *birthday care pack*
* Entertainment Zone with Xbox, ping-pong table, and foosball
* Tiny room for *Reading & Thinking*
* *Carpenter toolkit* to turn your ideas into crafts

## Salary
* From $600 - $1K+, Dependent on Experience

## Location
* A26, BT5, Luu Huu Phuoc, Nam Tu Liem, Hanoi
* Map: https://foob.la/map

## Contact

HR Team: jack@foobla.com

**Comment by joneslee85** [comment]
Thanks for submission, can you please add another section on `What are hard problems that your company is trying to solve?`

**Comment by nvg58** [comment]
Hi there,

'We are seeking a Senior WordPress Developer responsible for back-end development, including developing new features for LearnPress and WPPipes.' => Those are products we are building. You can search Google for that.

Bests,

**Comment by qcam** [comment]
@nvg58 Would you please share some interesting engineering projects in your company?

**Comment by nvg58** [comment]
Hi @qcam, 

Those are all engineering projects at Foobla. If you need more information, please let me know.

Thanks,

**Comment by qcam** [comment]
@nvg58 thanks, have you added them to the job description? Or did I miss anything?

**Comment by nvg58** [comment]
You can take a look at LearnPress <https://wordpress.org/plugins/learnpress/>. LearnPress is a comprehensive WordPress LMS Plugin for WordPress, just like WordPress Moodle or Moodle for WordPress if you know what Moodle is. This is one of the best WordPress LMS Plugins can be used to easily create & sell courses online. Each course curriculum can be made with lessons & quizzes which can be managed with easy-to-use user interface, we really made it for lazy people.

Currently, LearnPress has 20K+ active installs and have more than 7k+ paid users (which are universities, training centers, languages schools, etc). This is one of the best LMS plugins for WordPress.

**Comment by qcam** [comment]
@nvg58 sounds cool, could you please add that to *Interesting Engineering Projects* section in job description? Follow this job format if you have any concern (https://github.com/awesome-jobs/vietnam#job-description-format)
