### ISSUE TITLE
Xpath - React-native/iOS developer - Saigon - FT

### ISSUE THREAD

**Issue by s123121** [awesome-jobs/vietnam#437]
**The world need more innovators.**

So we built xpath.co. We set out to build xpath not just as a company but as a innovator hub.
We are challenging the status quo of the travel industry and now, we need more innovators like you, who always interested in creating elegant/state of the art solutions by incredible software development skill. This is your chance to work with challenge lovers, grow your skills, and make an impact

## Location

District 1, HCMC, Vietnam

## Salary Expectation
500$ - 900$

## Who you are
- You have a strong passion for learning.
- You have experience in working with Git and GitHub/Gitlab
- You have excellent debugging skill
- You’re self driven and can work independently, while you also enjoy working in a team environment and owning the success of a project.

### Must have
- At least one year experience with React/React-native or iOS development
- You are familiar with working with RESTful API

## What we expect
- Create prototypes with as few bugs as possible
- Connect mobile app with back-end REST API
- Be an empathetic developer. Everything you touch should be easy to use, easy to test and work as expected
- Keep abreast of trends in web/mobile development; share these lessons with the team
- Learn from everyone, no matter who they are

## Who we are

We’re a team of 5 people(Vietnamese/Japanese) who love to build things. As a early stage employee, you will be the one in charge of creating the identity of AgeCode. With us, you’ll get exposure to many aspect of running a start up and experimenting things. Come talk with us if you want to know more

### Why it would be awesome to work with us
- We build product 
- We think it is important that everyone has an opportunity to grow and try new things. For example: we  have a 7.5 hours work-day policy. Brilliant ideas are always welcome
- We are small team, so there are many things for you to improve on. Your only limit is your creativity! 

### What are hard problems that your company is trying to solve?
Xpath is a platform connecting travelers from all over the world with locals buddy to offer unique travel experiences. Xpath offers the perfect personalized experience that you could never get from a package tour, such as amazing sights that aren’t listed in guidebooks, restaurants that only locals know, and everyday local experiences. 
As a developer, you will be in charge of making the Xpath mobile application!

## Contact
We like to keep things interesting. If you’re curious, talented and hungry, we want to hear from you.
Do not hesitate to send your CV to: [info@xpath.co](mailto:info@xpath.co)

**Comment by linhhtd** [comment]
còn tuyển nữa ko ấy ơi?
