### ISSUE TITLE
Terralogic - Senior JavaScript Developer - HCMC - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#438]
Terralogic (former Infornam), headquartered in Silicon Valley, USA is an Engineering & IT services company. It with 1,000 employees and three development centers in US, India and Vietnam provides comprehensive solutions that are cost-effective, scalable and flexible.

The company serves global clients, among them technology pioneers and industry leaders. Our core team is composed of engineers and domain experts who has strong experience and understanding of Mobility, Applications, Networking & Communications and Embedded Systems.

We are building the unimagined and aspiring to be be the most loved organization in the coming years. Accordingly human resources are regarded as our jewels. Terralogic offers a dynamic working environment, professional development and high-end facilities. Our engineers have opportunities to work with foreign customers as well as working onsite in Japan, Europe and the US.
## Location
- Saigon, Vietnam
## Salary Expectation
- Negotiable
## Requirements
MUST HAVE
- At least 2-3 years hand-on experienced with Javascript development.
- Experienced with building web applications using latest Javascript technologies (ES6, React JS, Angular JS, Node JS).
- Experienced with building responsive website.
- Familiar with Functional Programming.
- Familiar with Agile methodology.
- Experienced with task/source code management tools: JIRA, GIT.
- Fluent in English speaking to participate in meetings with US customers.
- Excellent logical thinking and problem solving.
- A good team player.
NICE TO HAVE
- Experienced with NOSQL.
- Experienced with leading a small agile team.
- Experience working onsite in Europe/US.
### Responsibilities
- Implement new features and required enhancement.
- Ensure the delivery/coding quality of an agile team.
- Technical discussion and decision making with both internal and external teams.
- Continuously research new technologies and keep the team updated with the technology trend.
- Report directly to PL/PM.
### What Terralogic offer
- Flexible working schedule. Everything is allowed by trusting the employees
- Competitive Salary: 13th salary + performance awards + project awards; Referral Bonus
- Opportunities for advanced career development overseas: in America, Japan, India…
- Good benefit that takes care of employees work-life balance:
- Insurance: Accident Insurance 24/24 (Gras Savoye Willis); Health Insurance (Gras Savoye Willis):
- Social Insurance tax: was paid as the salary in the labor contract
- Special Leave Days: minimum 15 days/year
### Contact
- Ms Mai Ngo: mai.ngo@terralogic.com
- Skype: mai.ngo91

**Comment by qcam** [comment]
Hey @RecruiterMaiNgo, would you be able to edit your job description to follow our format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?
