### ISSUE TITLE
Remote, Vietnam - Frontend Developer - Upto 70M gross

### ISSUE THREAD

**Issue by phuongtrang1205** [awesome-jobs/vietnam#4384]
## Location

* Fulltime Remote, Vietnam

## Salary Expectation

* Upto 70M gross

## Requirements
* Proficiency in frontend development with React, Nextjs
* Strong UI/UX sense to take a feature from start to finish
* Can handle complex animation if needed
* Good self test skills and discipline
* Experience with theme styling
* Familiar with GraphQL
* Familiar with front-end build pipelines & tools (Github Action, Docker, webpack...)
* Write structured and clean code
* Fluency in English and Vietnamese

### Benefits
* Full-time insurance follow VN Labor laws
* Work equipment support.
* Annual bonus, performance-based bonus.
* Monthly compensation package to help you work and live better, remotely!
* Fully support for exams to get Certification and skills improvement training.
* Receive 22 paid leaves on your 5th years. We encourage you to take one month off work.
* A competitive salary and benefits package
* Opportunities for professional development and career advancement with monthly coaching.
* A dynamic and innovative team that values creativity and collaboration.

### Contact
Phone/Zalo: 0796683001
Email: trang.dtalent@gmail.com

**Comment by tuanductran** [comment]
Chào bạn, nếu bạn đang tìm kiếm ứng viên Dev. Hãy tham gia vào nhóm Zalo này nhé. Nhóm mình hiện tại đang có khá nhiều bạn ứng viên Dev tìm job, hy vọng là bạn sẽ tìm được ứng viên phù hợp nha! [https://zalo.me/g/lgkrvf226](https://zalo.me/g/lgkrvf226)
