### ISSUE TITLE
Chopp - Full-Stack Engineer - HCMC - FT

### ISSUE THREAD

**Issue by constantx** [awesome-jobs/vietnam#439]
# Full-Stack Engineer
## Why you’ll love working with Chopp:

We are an early stage, fully-funded startup that aims to bring world-class customer service and convenience to grocery shopping in Vietnam. Our team is lean with lots of opportunities to grow and learn. If you’re ready to take on a challenging and rewarding role in a dynamic Silicon-Valley-Style team and help shape the future of on-demand service from the ground up, join us!

Checkout for other roles: https://chopp.vn/careers

## Location
- Saigon, Vietnam

## Salary Expectation
- VND12M—VND20M with generous stock / equity

## Skills
- Strong experience in JavaScript/Node.js
- Strong experience with developing RESTful web services
- Good understanding of native web technologies (HTML, CSS and Javascript)
- Good understanding of MV-Javascript frameworks such as ReactJS, AngularJS, etc
- Good understanding of security practices
- Experience in Linux /Unix environment

## Must Have
- Writes clean, modular and well-documented code
- A solid understanding of user-centered design principles 
- Careful attention to detail and ability to see the big picture
- Ability to prioritize tasks in a fast-paced environment
- Collaborates and works efficiently with cross functional team
- Entrepreneurial spirit and self-motivated
- Proficient English communication skills; speaking and writing

## Ideally
- Familiarity with Git and/or GitHub
- Comfortable with agile development environment
- Team lead experience
- Past startup experience

## You’ll be responsible for
- Our infrastructure, API and native web app.
- Bring happiness to the people of Vietnam through a world-class product and service.

## Perks and Benefits
- Startup culture with no BS
- Generous stocks / equity
- 13th month bonus + additional quarterly performance bonuses
- Bi-weekly team happy-hour
- Quarterly off-site trips
- Awesome office

## Contact
- please send CV or Linkedin to join@chopp.vn
- or ping me directly on [Facebook](https://m.me/constantx) or [Telegram](http://t.me/t_nguyen)

**Comment by qcam** [comment]
Hey @constantx, would you be able to edit your job description to follow our format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?
