### ISSUE TITLE
Not A Basement Studio - Senior Android Developer - HCMC - FT 

### ISSUE THREAD

**Issue by duynguyenNAB** [awesome-jobs/vietnam#440]
### Why NAB Studio?

At Not A Basement Studio, passion and young-at-heart spirit are what influence our works from the very first day. For that, we've been stating a strong position in such competitive industry either in Vietnam or South East Asia. If you are a CHALLENGE-SEEKER who obsesses with building awesome products for millions of users around the world - just like what we LOVE to do, join us!
## Descriptions

We are making apps for users all over the world with millions of users using our apps currently. One of the key ingredients to achieve such number and stay competitive in the global app market relies heavily on our prized developers.

They are not just coders. They are also thinkers, and solution architects.

We are looking for a talented Android developer to join our team. You will be hands-on with the development process, focusing on Android app back-end (for example, communication with servers).

As an Android developer, you will be working in our Android team to maintain existing apps, as well as develop new ones.

Work directly with our product owner, Android Lead and Design Lead to carry out our back-end requirements to support UI designs.

## Requirements

* Minimum 2 years experience in Android development with at least 1 app either published on Google Play or developed for clients
* Strong background in Java programming
* Strong background on data structures and algorithms
* Firm understanding of design patterns
* Familiar with various developer tools (Android Studio, Gradle, debugging, profiling, git, CLI, etc.) and workflows (gitflow, unit testing, continuous integration etc.)
* Experience with JavaScript, React Native is preferred
* Experience with UI programming, e.g. custom UIs, animations, or OpenGL are preferred
* A team player and cheerful personality
* Love to explore and learn new things
* Attention to details
* Communication in English is a must

## Benefits

You’ll have the chance to build world-class products for millions of people around the world.
In addition to that, here are the perks at working at NAB Studio.

* Regular on-the-job training by our team leads.
* Mac computer is provided
* Free catered lunch everyday
* Free food & drink anytime you want
* Tons of cool toys (Xbox One, PS4, Drones etc.)
* Work in one of the most comfy offices around

## Salary Expectation

* $1100 +

## Location

Thien Son Plaza 4th Floor, 800 Nguyen Van Linh, District 7, Ho Chi Minh City

### Contact

Email: jobs@notabasement.com 
Apply at: http://bit.ly/NAB_SeniorJavaDev
About us: http://bit.ly/NotABasementStudio

**Comment by qcam** [comment]
Hey @duynguyenNAB, would you be able to edit your job description to follow our format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?

**Comment by duynguyen94** [comment]
hi @qcam, thanks for your suggestion. We have finished hiring process. So I will close this Issue here. Next time, I will follow strictly to the format. Sorry about that.
