### ISSUE TITLE
Meete - PHP Developer - Remote/Saigon - FT/PT

### ISSUE THREAD

**Issue by hrmeete** [awesome-jobs/vietnam#443]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Competitive salary with lunch and accommodation

## Requirements
* PHP, MySQL
* Experience with one of frameworks Symfony, Zend, Laravel
* No certificates required, at least 1 year of experience is an advantage
* Current university students can apply

### Must Have

* Strong programming skills
* Eager to learn, responsible

### Ideally

* Experience with developing PHP

### You’ll be responsible for

* Backend. Develop a better app and system for Meete.

### Why it would be awesome to work with us
* Major - Working for Meete, everybody plays a significant role in helping the company accomplish the ultimate goal. 
* Eager - Meete's members are eager to take on any challenges, to have mistakes and to learn new things.
* Enlightened - Failure is the mother of success. Whenever we encounter mistakes, we reflect and start again in a better way. 
* Team - We work as a team, fail as a team, win as a team, laugh as a team, and cry as a team. Our close relationships among members are one of the most outstanding factors of Meete.
* Effective - Overall, the most important thing is to be effective. We fail and stand up again to be more effective in our work. 

### What are hard problems that your company is trying to solve?
* Lack of IT developers in our company. Our current IT developers have to take up a lot of responsibilities.
* Products are still on its way to its full and perfect form. We want to create a much better app and service better than now.

### Contact
Homepage: https://www.meete.co/
Please send your CV or a WORD file (clarifiying your skills and past & current projects) to email: tuan@meete.co (Mr. Tuan)

**Comment by qcam** [comment]
@hrmeete I think your might misunderstood the "What are hard problems that your company is trying to solve?" question, it's more about hard and challenging engineering problems.

Would you please edit your job description following the format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?
