### ISSUE TITLE
Mulodo Vietnam - Frontend (HTML/CSS/Javascript) Senior Developer - HCM - FT

### ISSUE THREAD

**Issue by mulodo-vietnam-hr** [awesome-jobs/vietnam#444]
![mulodo](https://cloud.githubusercontent.com/assets/25657323/23606372/0058d1e8-0293-11e7-8ec4-4264a1183548.jpg)

## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* Negotiable

## Job contents

* Developing and maintaining web service for Japanese company.
* Researching the solutions to solve problems on design and development process.
* Supporting and suggesting screen layout design.
* Estimating and scheduling for development tasks.
* Front-coding with HTML, CSS and JavaScript.

### *a)Education & Experience*

* Bachelor degree in Information Technology.
* Must have 3+ years professional front coding experience with HTML, CSS, JavaScript.

### *b)Hard Skills*

* Ability to do responsive coding with HTML5/CSS3/JavaScript(jQuery);
* Ability to design graphic with PhotoShop/Illustrator/Dreamweaver etc...;
* Ability to do responsive layout design awareness of Web and Smartphone screen;
* Good research skill.

### *c)Soft Skills*

* Reading and writing in English fluently.
* Advanced communication skill.
* Active attitude.
* Contributing to team and customer.
* Good problem-solving skill.

## Company Benefits

* Having chances to get attractive company bonus every month/year, such as “Employee of the month/year”, “Thanks award”, “Team of the month/year”,…
* Salary and position is reviewed 1 time a year based on employee’s performance;
* Getting 13th month pay every year as company rule;
* Company trip once a year;
* Joining party (lunch party, dinner party, year-end party, anniversary ceremony…)  almost every month;
* Free parking fee;
* Joining in Japanese Class and clubs (Soccer, Badminton, Guitar…);
* Annual Health Check;
* Company’s labor policy completely pursuant to Vietnamese labor legislation (social & health insurance, annual leave, working conditions, etc.);
* Building a stable career with dynamic promotion and job opportunities;
* Having the chance to work with skilled foreign professionals.
* Privileges to attend weekly Open Study sessions with company's IT experts as well as participating in presentations where engineers share knowledge of the latest technologies. 
* Consideration for promotion from Dev to Leader position based on one's ability and work performance instead of years of experience count.

### For further information please visit 

* [Mulodo vietnam Co., Ltd jobs](http://mulodo.talentnetwork.vn/job-search/all-jobs/en)
* [Mulodo Vietnam Co., Ltd facebook page](https://www.facebook.com/MulodoVietnam/?ref=bookmarks)

### Candidates please send your English CV to

* To: lam.dung@mulodo.com (Ms. Dung)
* cc: hr@mulodo-vn.com
* Note: We contact only passed CVs for interview.
![recruitment](https://cloud.githubusercontent.com/assets/25657323/23606376/08469e9e-0293-11e7-97ab-78ea0a72e595.jpg)

**Comment by qcam** [comment]
@mulodo-vietnam-hr Could you edit the job description to follow our guideline [here](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). All REQUIRED sections in the guideline must be filled.

Please note that if this ad does not meet our requirements, it will be closed after 2 days.
