### ISSUE TITLE
Not A Basement Studio - Senior iOS Developer - HCMC - FT

### ISSUE THREAD

**Issue by duynguyenNAB** [awesome-jobs/vietnam#447]
### Why NAB Studio?

At Not A Basement Studio, passion and young-at-heart spirit are what influence our works from the very first day. For that, we've been stating a strong position in such competitive industry either in Vietnam or South East Asia. If you are a CHALLENGE-SEEKER who obsesses with building awesome products for millions of users around the world - just like what we LOVE to do, join us!

## Descriptions

We are making apps for users all over the world with millions of users using our apps currently. One of the key ingredients to achieving such number and stay competitive in the global app market relies heavily on our prized developers.

They are not just coders. They are also thinkers and solution architects.

We are looking for a talented iOS developer to join our team. You will be hands-on with the development process, focusing on iOS app back-end (for example, communication with servers).

As an iOS developer, you will be working in our iOS team to maintain existing apps, as well as develop new ones.

Work directly with our product owner, iOS Lead, and Design Lead to carry out our back-end requirements to support UI designs.

Work with our back-end developers for end-to-end integration.

## Requirements

* Minimum 2 years experience in iOS development with at least 1 app either published on the store or developed for the client.
* Expert in Software Design Patterns, Cocoa, Foundation, Networking, and Concurrency.
* Familiar with various developer tools (eg. Xcode, Instruments, etc.) and workflows (debugging, profiling, unit testing, continuous integration, provisioning, distributing, and submission to the App Store).
* Strong background in programming:
* Must have the firm understanding of various design patterns. ex: MVC, Singleton, State Machine, etc.
* Only write codes that are clean, beautiful, and very DRY.
* Proficiency in English.
* Open minded, fast learner, and a #team player.
* Most important of all, you must love working on things that will make our apps not only look interactive, run smoothly but also maintainable.

## Benefits

You’ll have the chance to build world-class products for millions of people around the world.
In addition to that, here are the perks at working at NAB Studio.

* Regular on-the-job training by our team leads.
* Mac computer is provided
* Free catered lunch everyday
* Free food & drink anytime you want
* Tons of cool toys (Xbox One, PS4, Drones etc.)
* Work in one of the most comfy offices around

## Salary Expectation

* $1100 +

## Location

Thien Son Plaza 4th Floor, 800 Nguyen Van Linh, District 7, Ho Chi Minh City

### Contact

Email: jobs@notabasement.com 
Apply at: http://bit.ly/NAB_SeniorIOSDev
About us: http://bit.ly/NotABasementStudio

**Comment by qcam** [comment]
@duynguyenNAB  Would you be able to edit your job description following the format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?

**Comment by duynguyen94** [comment]
hi @qcam, thanks for your suggestion. We have finished hiring process. So I will close this Issue here. Next time, I will follow strictly to the format. Sorry about that.
