### ISSUE TITLE
2359 Media VN - Android Developer - Saigon - FT

### ISSUE THREAD

**Issue by namdaoviet** [awesome-jobs/vietnam#451]
## Location

* Saigon, Vietnam

## Salary Expectation

* 1000 - 2000 USD/month

## Requirements
* Degree in Computer Science, Information Systems, or a related field, or significant equivalent experience
* Strong OO design and programming skills in Java
* Knowledge of Android SDK, Android Studio, SQLite, MySQL or similar database management system
* Effective operation in a fast-paced, deadline-driven, and collaborative programming environment

### Responsibilities
* Work with Project manager to translate feature to stories
* Work with Server engineers to define APIs
* Assign logically segmented work to junior developers
* Review and improve the technical ability of junior developers

### This role is evaluated on
* Technical aptitude and Experience in Android application development
* Ability to contribute effectively in a fast-paced, deadline-driven, and collaborative programming environment
* Ability to lead projects through the completion of all phases of application development
* Ability to problem solve keeping in mind the end goal

### Why it would be awesome to work with us
* Lovely office in District 10, in the same building with Big C supermarket To Hien Thanh
* Flexible working hours, 14 days of annual leave
* Project bonus + 13th month bonus
* Playing room with table tennis and foosball table
* Free parking
* Lunch at office
* Pantry always have beers
* Annual company trip and other team building activities
* Training course in Singapore

### Contact
Ms. Nam: nam.daoviet@2359media.com

**Comment by qcam** [comment]
@namdaoviet Would you be able to add some interesting engineering projects to your job description following the instruction [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format). Also a brief introduction of your company would be great I think.
