### ISSUE TITLE
FPTTelecom - Java/Python Developer - Sai Gon - FT

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#454]
## Location

* FPT Telecom Building, Tan Thuan EPZ, District 7, HCMC, Vietnam

## Salary Expectation

* $1000/month

## Requirements
* At least 3 years experience in Java (Web)
* Have knowledge in Big Data, Python Dev
* Good experience with database - backend
* IT Degree Qualification

### Ideally

* Experience with Bigdata

### Responsibilities

Great power comes with great responsibilities!

### Why it would be awesome to work with us
* Salary around $650 - 700, 15-17 months/year
* Special - funny culture, dinamic environment
* A lot of teams: game, football, volleyball, table-tennis, ...
* FPT Telecom building with more 2000 employees, good facilities
* Have good career path & have trained by good leaders, expert

### Contact
Homepage: fptjobs.com
Email: chungnt12@fpt.com.vn

**Comment by qcam** [comment]
@chung2604 Would you be able to edit the job description to follow our instruction?
