### ISSUE TITLE
NeoLab HCM - Ruby developer - SaiGon

### ISSUE THREAD

**Issue by thanhbk150** [awesome-jobs/vietnam#455]
## Location

* 60 Nguyen Dinh Chieu, P. Da Kao, Q.1

## Salary Expectation

* Negotiable : 500 - 1300 $ / month

## Requirements
* Ruby
* PostgreSQL, MySQL
* 1+ year experience in Ruby on Rails development. 

## Skills
* Strong experience with client side, web technologies (HTML/CSS/JS)
* Strong analytical and problem solving skills
* Good at Teamwork, communication
* Know Japanese is an advantage.

### Responsibilities

Great power comes with great responsibilities!

### Contact
Email: thanh.n@neo-lab.vn, phone: 0973118494

**Comment by qcam** [comment]
@thanhbk150 Would you be able to edit your job description following the format [here](https://github.com/awesome-jobs/vietnam/blob/master/README.md#job-description-format)?
