### ISSUE TITLE
Limina Financial Systems - golang developer - Remote/Sweden - FT

### ISSUE THREAD

**Issue by furst** [awesome-jobs/vietnam#456]
![alt text](http://kfurst.com/images/limina-logo.png "Limina logo")

### What are hard problems that our company is trying to solve?

Our vision is system automation in one of the most lagging industries in the world – finance. The foundation is to use computers for what they excel at – reliable automation of well defined tasks. We don’t aim to replace humans with our software, but to empower them. Captron move workforces from the production line to the control room.

### Why it would be awesome to work with us

The solutions are technically challenging. Here's the list of what we use:
* Microservices
* Golang
* Javascript/React
* We have created our own calculation framework on top of Java for performance heavy calculations, kind of like: https://blogs.janestreet.com/seven-implementations-of-incremental/
* High demands on uptime, disaster recovery and backup

Cool programming tasks aside, you'll get to work on changing the financial markets to the better!

## Requirements

* Golang experience
* 2+ years hands-on coding

### Must Have

* High potential to deliver fast results (with desired quality)
* Quality awareness (we have a clear quality definition, which is high)
* Good english knowledge, both written and verbally

### Ideally

* Experience with Java
* Experience with javascript/react
* Experience with microservices
* Experience with websockets & REST

### Responsibilities

You'll likely work on different projects over time, such as
* Building a new service (microservice) from scratch
* Implementation of new features on current services
* Bug fixing current services
* Building tests for all code you write

A feature will be assigned from the backlog and you'll be responsible for scoping, technical design, user experience analysis etc (checking with relevant stakeholders internally). After that the feature is to be coded (implementation + tests). Where you leave the feature is at our first quality assurance step and given a great job, it will then flow through our QA-process into production.

### You can bring

* Creativity
* General problem solving ability
* Dedication / personal drive (however, we work normal hours as the brain needs to rest as well!)

## Location

* Remote at first
* Option to relocate to Stockholm, Sweden in the future

## Salary Expectation

* Up to $2000/month

### Contact 

Homepage: www.limina.com

Andreas (CTO): andreas_at_limina_dot_com

**Comment by anhldbk** [comment]
Is `Golang experience` a must?

**Comment by furst** [comment]
@anhldbk Not if you are a coding ninja and can learn quickly

**Comment by vielktus** [comment]
I want to learn Golang so badly, can I apply part time for this opportunity ? I'm able to provide 18 hours per week.

**Comment by furst** [comment]
@vielktus Unfortunately we are only looking for full-time at the moment

**Comment by nathanphan** [comment]
@furst I sent an email to andreas_at_limina_dot_com, can you check? thanks

**Comment by furst** [comment]
It is!
