### ISSUE TITLE
FPT Telecom - Senior PHP Dev (laravel) -Saigon - FT

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#458]
## Location

* Dis 7, Saigon, Vietnam

## Salary Expectation

* $800 - 1000

## Requirements
* At least 2 years experience in PHP, using Laravel framework
* Have experience with product development
* Young, active & wanna get more successful & career Path in product environment

## Skills
* PHP
* Backend
* Laravel

### Responsibilities
- Building a new product for FPT Telecom
- Research new technologies & apply for projects 

### You’ll be responsible for

* Building a new product for FPT Telecom

### You can bring

* A good eyes for design
* A good analyist skill

### Contact
Homepage: http://fptjobs.com
Email: chungnt12@fpt.com.vn

**Comment by qcam** [comment]
@chung2604 Could you edit the job description to follow our guideline [here](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). All REQUIRED sections in the guideline must be filled.

Please note that if this ad does not meet our requirements, it will be closed after 2 days.
