### ISSUE TITLE
💣💥 Viral Foundry - Front End Developer (Ruby/JS/React/Vue/Angular) - HCM or Remote

### ISSUE THREAD

**Issue by allbombs** [awesome-jobs/vietnam#459]
![top-talent-wanted-viral-foundry](https://cloud.githubusercontent.com/assets/2031239/24073360/53543280-0c29-11e7-8869-67ff093d7b29.png)

Viral Foundry is looking for a talented javascript rockstar. You will join a small team and help build web and mobile applications. This is a unique opportunity where you will work in Indonesia for 6 weeks leading up to Tech In Asia Singapore conference on May 17th. VF will cover the flight and you'll have the chance to have a huge impact on all of the product we build.

You will work on two products:

1) Promo.co - marketing tool for small businesses in North America
2) Brand new product - you will write the first lines of code on this new MVP. More details during interview. We're flexible on the technology. 

## Location

* Saigon, Vietnam
* Remote
* Note, we need you to travel to Indonesia for 6 weeks. We will cover these costs

## Salary Expectations

* $1,000 - 2,500 per month

## Requirements

* You are passionate about clean code and elegant solutions.
* You have at least 2 year of experience writing maintainable JavaScript, preferably with a shipped website, web app, or native app to showcase.
* Experience working with rails, react, vue, angular, jekyl
* Previous experience estimating and delivery big projects on time

### Must Have
* Outstanding communication skills, can read/write/speak english
* Be able to fly and join our team retreats (2-3 times per year we all work in the same location in SE Asia)
* Awesome attitude. Want to build amazing front end web apps
* Enjoys travel + working in team environment

### Other Perks
* Mentorship from Amazon developer in Vancouver
* Create open source projects
* Equity
* Lots of travel opportunities.

### Why it would be awesome to work with us
* 5 person team. You will have a impact in everything we do
* Fun, creative, passionate team.

### Contact
Homepage: ViralFoundry.com
kenny@viralfoundry.com

**Comment by qcam** [comment]
@allbombs  Could you edit the job description to follow our guideline [here](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). All REQUIRED sections in the guideline must be filled.

Please note that if this ad does not meet our requirements, it will be closed after 2 days.
