### ISSUE TITLE
🇻🇳 Viral Foundry - Senior Full Stack Developer - HCM / Vietnam Remote

### ISSUE THREAD

**Issue by allbombs** [awesome-jobs/vietnam#460]
![full-stack-developer-hcm-viral-foundry](https://cloud.githubusercontent.com/assets/2031239/24073660/870170e4-0c2d-11e7-8f2c-eabc55120d46.jpg)

We're looking to add a Full Stack Developer to our team, and the illustration above. We're a small knit team that builds 2-3 new products / startups per year. The illustration above is from 3 months ago when our entire team traveled to Bali to work in a villa for 2 months. It was a ton of fun, and we're looking to add another talented teammate for our next team retreat in April. This is super unique opportunity for someone that wants to work on new technologies, build beautiful + well designed products, learn a ton, and travel abroad.

## Location

* Saigon, Vietnam
* Remote
* Team retreats to work + travel, usually 3-8 weeks in length (We'll cover your flight + budget for accomm)
* Work from dreamplex2 (covered by VF), or remotely between retreats

## Salary Expectation

* $1,000 - 2,500 per month

## Requirements
* Awesome. Talented developer with a great attitude.
* 2+ years experience
* Need to be able to show some code / github code review
* Degree in Computer Science or related field a plus
* At least 2 shipped apps
* Outstanding communication skills, can read/write/speak english
* Accountable, and will do what it takes to ship products and puts customers first

## Skills / Experience
* Ruby / Node / Ember / React / Angular. You should be truly full stack.
* Have experience with designing or consuming RESTful JSON API
* Comfortable with building the entire front-end or backend stack on your own (hello internal hackathons + mvp projects)
* You should have apps that demonstrate your backend (API) + frontend skills

### Why it would be awesome to work with us

* We love product. Committed to be the #1 product company in SE Asia.
* Interesting chance to work on multiple products in different verticals (consumer, business, enterprise). You will get the chance to own development on projects, selecting technology, trying new tools and platforms.
* Level up your skills (Development), get mentorship from senior developers from NA
* Talented team. We have fun, but work very hard. Strong on product, move fast.

### You’ll be responsible for
* Supporting the launch of Promo.co
* Creating MVP's from scratch! Including selecting technology solutions that meet the project goals

### Contact
Superstars welcome, huge egos are not. Please send us an email and introduce yourself. 

Homepage: ViralFoundry.com
kenny@viralfoundry.com

**Comment by thanhnguyennguyen** [comment]
It's not really an issue, haha

**Comment by qcam** [comment]
@allbombs thanks for posting.

Could you please make sure your title and post align with our our format [here](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post)?
