### ISSUE TITLE
FPT Telecom - Android developer -Saigon - FT

### ISSUE THREAD

**Issue by chung2604** [awesome-jobs/vietnam#467]
## Location

* Saigon, Vietnam

## Salary Expectation

* $500 - $800

## Requirements
* At least 1 years experience in Android
* Young, Active
* Wanna get more new challenges
* Prefer learning new technology, new languages

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building & develop products in FPT Telecom
* Researching new technologies to apply for projects

### You can bring

* A good eyes for design
* A good analyst skill

### Why it would be awesome to work with us
* Salary around $500 - 800, 15-17 months/year
* Special - funny culture, dinamic & professional environment
* A lot of teams: game, football, volleyball, table-tennis, ...
* FPT Telecom building with more 2000 employees, good facilities
* Have good career path & have trained by good leaders, expert

### Contact
Homepage: https://fptjobs.com
Email: chungnt12@fpt.com.vn

**Comment by joneslee85** [comment]
Thanks for posting.

We request that job post must include:

`### What are hard problems that your company is trying to solve? (MUST)`

Please revise and we will be tagging the job once approved.
