### ISSUE TITLE
[Intelligence Business Solutions Vietnam Co., Ltd] - Senior Java Developer

### ISSUE THREAD

**Issue by jadephan0204** [awesome-jobs/vietnam#468]
**JOB DESCRIPTION**

Dear all, 
We are looking for developers who enjoy work as same as play with family and friend.

As a Senior Java Developer, you will: 
- Participate in analysis requirements, design mock, implementation, test process 
- Work under pressure 
- Learn and grow quickly

**JOB REQUIREMENT**

- 3+ year experience with Java language 
- English speaking, writing skill. 
- Experience about Java framework as Spring, Hibernate, and JUnit 
- Good in HTML, JQuery, CSS, Bootstrap, MySql, Oracle
- Good in Maven, AWS, Git, Redmine, IDE (Eclipse..)
- Experience in Android, IOS, Python, PHP is a plus.

**WHY YOU'LL LOVE WORKING HERE**

- Global, friendly environment. We use English in our office 
- Performance review 2 times per year 
- Full benefit with social insurance 
- 13th month salary 
- Opportunity for onsite in Tokyo 
- Activities: Football club, Guitar club, Mobile club, Camera Club, Game Club 
- Coffee & Tea for all employees. 
- Beer and Coca after working hour or finish your tasks (5:00 - 5:30)

**LOCATION & WORKING TIME**

IBSV Office: 6th Floor, An Phu Plaza, 117-119 Ly Chinh Thang, Ward 7, District 3, HCMC
Working time: 8:30 – 17:30, Monday - Friday

**HOW TO APPLY**

Please don't hesitate to send us your English CV (Subject: Internship - Your name) via: ngoc.pham@inte.co.jp (0938 05 42 93)

_Thank you for your time and consideration_!

**Comment by qcam** [comment]
@jadephan0204 
Could you edit the job description to follow our guideline [here](https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post). All REQUIRED sections in the guideline must be filled.

Also please indicate the location and job type in the title.

Please note that if this ad does not meet our requirements, it will be closed after 2 days.
