### ISSUE TITLE
[Intelligence Business Solutions Vietnam Co., Ltd] - Senior PHP Developer 

### ISSUE THREAD

**Issue by jadephan0204** [awesome-jobs/vietnam#469]
**JOB DESCRIPTION**

We are looking for many PHP developers who enjoy work as same as play with family and friend.

As a Senior PHP Developer, your will:
•	To create excellent solutions for our client and support developing,
•	To mentor and build up a strong team.
•	To join in a system design, develop and test Web application in Ruby on Rails
 
**JOB REQUIREMENT**

- 4+ year experience with PHP language 
- English speaking, writing skill. 
- Technology: Any kinds of CakePHP, CodeIgniter, Laravel Framework, smarty Framework.
- Good in HTML, JQuery, CSS, Bootstrap, MySql
- Experience in Java, Python is a plus.

**WHY YOU'LL LOVE WORKING HERE**

- Global, friendly environment. We use English in our office 
- Performance review 2 times per year 
- Full benefit with social insurance 
- 13th month salary 
- Opportunity for onsite in Tokyo 
- Activities: Football club, Guitar club, Mobile club, Camera Club, Game Club 
- Coffee & Tea for all employees. 
- Beer and Coca after working hour or finish your tasks (5:00 - 5:30)

**LOCATION & WORKING TIME** 

IBSV Office: 6th Floor, An Phu Plaza, 117-119 Ly Chinh Thang, Ward 7, District 3, HCMC
Working time: 8:30 – 17:30, Monday - Friday

**HOW TO APPLY**

Please don't hesitate to send us your English CV (Subject: Internship - Your name) via: ngoc.pham@inte.co.jp (0938 05 42 93)

_Thank you for your time and consideration!_

**Comment by joneslee85** [comment]
Please feel free to resubmit, ensure the new post has valid Markdown format (this one is not valid) and the new one must answer `What are hard problems that your company is trying to solve?`
