### ISSUE TITLE
Inspi corp - Junior/Senior Full-stack Developer - HCMC - FT

### ISSUE THREAD

**Issue by inspicorp** [awesome-jobs/vietnam#470]
# __About Us__     
* INSPI CORPORATION is a US-based company, founded by two Vietnamese who studied at MIT and worked at Microsoft, Google and Facebook. We are pursuing a startup project which aims to disrupt education with personalized learning powered with Artificial intelligence. We are starting with English learning and teaching and looking to sell not just in Vietnam but also the global market.
* Our team is small, smart, very driven and hard-working. Working OT or over weekend is the norm. You will have a chance to develop to really stretch your potential and challenge yourself here.
* We are looking for strongly-driven Full-stack engineers to join our core team. You must desire to make a difference in English education.
![adobestock_97033329](https://cloud.githubusercontent.com/assets/26568366/24185311/10b9e616-0f05-11e7-850d-ca461fafae1b.jpeg)
# __Requirements__
## __Technical Skills__: 

We are looking for full-stack developers who possess the following skills:

* __Frontend__: 
      2-year experience with HTML – CSS is must-have skill
     1-year experience with React is an advantage
* __Backend__: 
     Understand how to deploy/ configure a web server using Nginx/Apache
     1-2 year experiences working with at least one of the following technology: Nodejs / PHP / Python / Ruby / Ruby on Rails.
* __Strong CS training__:
      Strong understanding of data structures and algorithms
      Solid object oriented programming knowledge
      Solid software design pattern knowledge
* __Strong skills in searching and implementing solutions from English sources/ documentation__

Notes: If your background is Front-end or Back-end only and you're willing to learn, don't hesitate to give us a try.

## __Culture & Mindset__:
* Be ready to do anything and everything needed
* Be willing to learn and learn fast
* 8-5 does not sound like you. You’ll spend as long as you can to get your job done
* Can work great in teams
## __Communication__:
* Able to communicate in English in writing
* Feel natural being in an open, dynamic and frank environment
# __Benefit__
* Competitive salary: USD$700 - $2,200
* Opportunity to work with the latest and most advanced technology.
* Opportunity to work with a small, energetic and passionate team where you must push yourselves to the limit and stretch your potentials.
# Why you love working here:
* Be part of a vibrant culture that values being “frank, effective, professional and initiative”. We love to empower you to achieve your greatest potential.
* We work hard and also play hard.
* We care to the life of members working for Inspi. We usually organize team building so as to enhance the spirit and solidarity after hard working time.
![img_6599](https://cloud.githubusercontent.com/assets/26568366/24185470/e61ef4f4-0f05-11e7-8a4a-7614f7ca856f.JPG)

# How to apply:
* Please email your resume and tell us why you are a great fit to the team at __hr@inspicorp.com__. __Only shortlisted candidates will be contacted for further interviews.__
* Address: 182 Ben Van Don, W.6, D.4
* Phone number: +84 8 668 25026

**Comment by joneslee85** [comment]
Can you please elaborate on `Strong skills in searching and implementing solutions from English sources/ documentation`?
