### ISSUE TITLE
Spout360 - Mobile Engineer (React Native, Android, iOS) - HCM - FT

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#472]
## Location
* 224A-224B Dien Bien Phu Street, Ward 7, District 3, phường 7, Quận 3, Ho Chi Minh City, Vietnam

## Salary Expectation
* Negotiable : 1000 - 2000 $ / month

## Requirements
* Experience in API design, SDK architecture, and mobile software lifecycle development practices.
* Understanding of UX Design - experienced in converting visuals, flow to working prototypes.
* Work on performance and reliability
* Plan and document technical specifications for features or system design
* **For Senior Engineering Positions**
	* Play a lead role either in terms of technical development and architecture, or in terms of team management
	* Mentor and nurture engineers
* **For React Native Developer**
	* Expert on Javascript development experience
	* Experience with ReactJS and or React Native
	* Experience with developing for mobile platforms using Objective C/Swift/Android

### Ideally
* You want to build large scale applications that are well tested and easy to maintain.
* Enjoy working in a start-up and open environment
* Take pride and ownership in your work
* Self motivated and can work well under pressure
* Team player, doing anything and everything needed to get things done

### Responsibilities
* Great power comes with great responsibilities!

### What are hard problems that we're trying to solve
* Streaming
* Payment System
* Localisation

### Why it would be awesome to work with us
- You’ll have the chance to build world-class products for millions of people around the world.
- Mac computer /External Monitor is provided
- Work in one of the most comfy offices around
- 15 days annual leaves.
- Opportunities to travel to SPOUT ENTERTAINMENT PTE LTD located in Singapore.
- Annual salary review & 13th month salary based on performance
- Annual cohesion trip and team building activities.   There is always strength in numbers and certainly greater power in united people. We believe in taking time off work to recharge and refresh so that we can come back as a more united team.

### What do you need to apply?
* Your CV (English)
* Your Github (or equivalent open source community) profile

### Contact
* Email : `hr@spout360.com`

**Comment by joneslee85** [comment]
Please help answer `What are hard problems that your company is trying to solve?`

**Comment by dominhquan** [comment]
@joneslee85 : seriously ? I've seen lots of issues get your `Label` without answering this question
