### ISSUE TITLE
TechJDI - Ruby on Rails Dev - HCM - Fulltime - Permanent

### ISSUE THREAD

**Issue by dohoangminhquan** [awesome-jobs/vietnam#475]
## Saigon based

* Saigon, Vietnam

## Salary Expectation

* $1000 to $2500

## Requirements
● Have experience building several applications using Ruby on Rails, and sql or no sql database system
● Be able to articulate the limitations and benefits of any frameworks used
● Be able to articulate the differences between sql and no sql and how using either or both impacts the system.
● Be able to describe the architecture of a web application and where the bottlenecks are
● Be able to optimise existing bottlenecks and writing optimised code
● Be able to describe the importance of sync and async elements in a system
● Have experience utilising ElasticBeanStalk or an alternative rapid deployment system
● Familiarity with GNU/Linux operating systems for server setup, configuration and diagnostics

## Skills
Ruby on Rails
MongoDB, mySQL

### You’ll be responsible for

You will be responsible for architecting and building innovation solutions to UI/UIX and backend challenges. This includes building RESTful APIs and well-designed systems to solve important coaching challenges. You’ll be co-ordinating technical decisions with our mobile development team.
You will also be required to work directly with health and fitness coaches to help us create world- class coaching frameworks and to help them go from personal coaches to fitness demi gods!
Our backend runs primarily on Ruby on Rails, mongodb and Parse. Our backend and Parse servers are deployed via ElasticBeanstalk on AWS and mongodb is managed by ScaleGrid on AWS. We utilise Sidekiq for our asynchronous tasks.

### Why it would be awesome to work with us

We are a health and fitness coaching platform that delivers habit change to users  right on their smartphones.
Over the years, it became apparent to us that having an encouraging coach, personalised health programs, and a supportive community is integral to a successful weight loss journey.
We are on a mission to combine mobile technology, our experience in habit  creation and the knowledge of top health coaches to put personalized health programs in the hands of our users.
We are headquartered in Singapore and have recently expanded into Indonesia. Within two months of our launch in Indonesia, we have acquired more than 5000 users. We are now looking to expand our team and improve our offerings so that our users can get even more value.

### Contact
Homepage: http://techjdi.com
Trollman: dohoangminhquan at gmail.com

**Comment by joneslee85** [comment]
Please feel free to resubmit a new post that is formatted correctly with Markdown
