### ISSUE TITLE
DEK Technologies - EXPERIENCED C AND C++ DEVELOPER - Saigon - Fulltime

### ISSUE THREAD

**Issue by greenpine82** [awesome-jobs/vietnam#476]
![dek-technologies-headline-photo-compress](https://cloud.githubusercontent.com/assets/8168503/24331319/cb561bee-125b-11e7-854c-b6c28fa52911.JPG)

## Join our winning team!

DEK Technologies is a professional organization that places high value on people and the individual competence that they contribute. People enjoy working at DEK. They enjoy the team camaraderie, flexibility, opportunities for travel, and feeling part of the company’s success. Come and be proud to be an integral part of helping our international customers develop the latest products that are sold globally and used by millions of people around the world. With offices situated in Melbourne Australia, Stockholm Sweden, Rome Italy, and Ho Chi Minh City Vietnam, you too can be a key part of our success.

**At DEK Technologies you will find yourself in an exciting career with:**

* Attractive, competitive salary and incentives
* Opportunities for short and long-term training/work overseas
* An excellent working environment in developing tomorrow’s features
* Open and honest culture where people are valued, treated fairly, trusted and empowered
* Training and career development opportunities
* 40 flexible working hours per week from Monday to Friday
* English classes 3 hours a week with qualified foreign teachers
* Extra 24/7 Health and Accident Insurance
* Annual health check up
* Annual company trip
* Annual family day
* Sport clubs
* Music club
* Yoga class
* Piano class

## Job description

Develop and maintain a software system for a video delivery network platform. Your job will be involved in developing new feature for the product and maintaining the released versions. By joining the team, you have a chance to work with cutting-edge technologies in video delivery network and world-class international experts.

**Your responsibilities include but not limited to the following:**
* Understand the requirement, design, implement and test new requirements
* Troubleshoot issue, suggest and implement solution when needed
* Take design ownership and make architecture changes in the long-term
* Continuously improve together with the team

## Job requirements
**Must have:**
* University Qualification in Software Engineering or a related degree
* Strong programming skill in C and C++

## SEND IN ENGLISH CV AND JOIN US NOW!

**DEK TECHNOLOGIES VIETNAM – Human Resource Department**

Email: info-vn@dektech.com.au

Address: 121/137 Le Loi Street, Ben Thanh Ward, District 1, Ho Chi Minh City, Vietnam

Tel: +84 8 39152424

Website: www.dektech.com.au

Facebook: https://www.facebook.com/DEKTechnologiesGlobal

**Comment by joneslee85** [comment]
Like the other post, this job post lacks details. What is `strong programming skill in C and C++?`, what problem are you trying to solve?

**Comment by greenpine82** [comment]
"I want DEK Vietnam to be an employer of choice. A place where people belong, trust, develop, and grow together. It is important to me that we have people who believe strongly in our values. I don’t believe in hierarchy, its only when everyone works together as a team can we achieve the best possible outcomes for our customers and ourselves. We need to follow through, be open and honest, and appreciate that learning and improving is a never ending endeavor.

My purpose is to remove impediments, and build systems that empower people to achieve success.

Only people with intrinsic motivation and a continuous improvement mindset can persevere."
                                                                                    [Daniel Tedesco - General Director](https://vn.linkedin.com/in/teddan)
