### ISSUE TITLE
VietInterview - Web Developer - Cau Giay/Hanoi - FT

### ISSUE THREAD

**Issue by huyenbui14** [awesome-jobs/vietnam#479]
## Location (MUST)

* Hanoi, Vietnam
* Duong Dinh Nghe Street

## Salary Expectation (MUST)

* $700/month 

## Requirements (MUST)
* PHP
* Python
* JS +/- HTML/CSS
* 2+ years Software Development experience

### Must Have (MUST)

* Be able to passinate in our working environment
* Be able to work for the sake of the company

### Ideally

* Experience with Angular JS/NodeJS

### Responsibilities (MUST)

One hundred percent for developing  website

### You’ll be responsible for

* Web Application Programming

### You can bring

* A good skill in programming langguages
* A good connection with your partners

### Why it would be awesome to work with us (MUST)
*Working in an young, passionate and professional environment
### What are hard problems that your company is trying to solve? (MUST)
*Solve our customer’s problems
### Contact (MUST)
Homepage: https://vietinterview.com/
email: tuyendung@vietinterview.com (mobile number: 0168 730 8250)

**Comment by joneslee85** [comment]
I am sorry that I have to close this job post. Please freel free to submit a new one (make sure you check the format and content) because this job post quality has not reached the standard par
