### ISSUE TITLE
Viral Foundry - RoR Backend Developer - Build new MVP from scratch - HCM / Vietnam Remote - 5 week contract

### ISSUE THREAD

**Issue by allbombs** [awesome-jobs/vietnam#482]
Viral Foundry is looking for a backend developer to build a brand new MVP. You will write the first lines on a new product we're launching. This is a contract position (40 hours per week) with opportunities to convert into full-time. Looking for someone to start ASAP. 

## Location
* Saigon, Vietnam
* Remote

## Salary Expectation

* $1,500 - $3,500 

## Requirements
- Awesome. Talented developer with a great attitude.
- 2+ years experience
- Need to be able to show some code / github code review
- Degree in Computer Science or related field a plus
- At least 2 shipped apps
- Outstanding communication skills, can read/write/speak english
- Accountable, and will do what it takes to ship products and puts customers first

## Skills / Experience
Have experience with designing RESTful JSON API
You should have apps that demonstrate your backend (API) skills

## What you will be building
A brand new product! We can go into more details during the interview but you will work with designers, and a front end developer to launch an MVP in 6 weeks.

## Contact
Superstars welcome, huge egos are not. Please send us an email and introduce yourself.

Homepage: ViralFoundry.com
kenny@viralfoundry.com

**Comment by joneslee85** [comment]
@allbombs thanks for the job post. Can you please revise the post to meet our guideline?

* The title should remove Build new MVP from scratch
* Use `C` for Contract work

**Comment by joneslee85** [comment]
@allbombs it is not quiet correct yet, it should be

`Viral Foundry - Ruby on Rails Backend Developer - HCMC/Remote - C`
