### ISSUE TITLE
[PIXTA VIETNAM] - [Web Developer] - [Hanoi] - [FT]

### ISSUE THREAD

**Issue by nqtrang2793** [awesome-jobs/vietnam#483]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $500 - 1000/month

## Your skills and work experience
* Solid knowledge on web development
* Junior position: 1 - 3 year(s) of work experience on web development
* Technical leader: more than 3 years of work experience on web development + management skills
* 5+ years Software Engineering experience

### Nice to have 

* Knowledge and work experience with Ruby on Rails, Linux/Unix and AWS
* Experience in developing and operating complex and/or e-commerce websites
* Good English communication skills (speaking, reading, listening)

## Your job
Function as a full stack developer to operate and develop PIXTA's complex e-commerce websites:
* Display system
* Search system
* Control system
* Graphic system
Imagine yourself being the technical ninja that support our customers in finding the desired images from PIXTA library with more than 20 million images, videos and vectors.

### Your technical environment
* Programming language: Ruby, Javascript (on-the-job Ruby training programme is available)
* Framework: Ruby on Rails, jQuery,...
* Database: Mysql, Dynamodb
* Infrastructure: Amazon Web Services (AWS)
* Tools: GitHub, SideCl, CircleCl, CodeClimate, Zabbix, NewRelic

### Your working environment
* Professional working environment according to international standards with opportunities to acquire new skills, build up work experience and receive competitive salaries at the same time
* Opportunities to work in special fields and to be trained as international engineers
* Works which encourage innovation, transparency and idea sharing
* Opportunities to oversea trainings and business trips (Japan, Singapore, Taiwan, Thailand)
* Internal seminar every week which encourage continuous learning and idea sharing

### Contact
Website: www.pixtastock.com
Phone number: 04 3226 2520
Email: recruit.vn@pixta.co.jp

**Comment by joneslee85** [comment]
Thanks for posting with us.

Would you be able to split this job into 3 that cater for each level of candidates?

Besides, it is required that the post answers the `What are hard problems that your company is trying to solve?` question

Feel free to create a new job pots.
