### ISSUE TITLE
GO GAME VIETNAM_Game Developer (Unity/C++)

### ISSUE THREAD

**Issue by hienha592** [awesome-jobs/vietnam#484]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* Good knowledge of Unity3D (C#);
*• Good knowledge of NGUI library in Unity3D;
*• Good knowledge of C++
* 2+ years of experience in Game Industry

### Must Have

* • Good knowledge of Unity3D (C#);
*• Good knowledge of NGUI library in Unity3D;
*• Good knowledge of C++
*• Fast to read and understand code;
*• Previous experience in gaming industry;
*• Knowledge about how to integrate Android/iOS plugins into Unity3D;
*• Knowledge of Objective-C, XCode;
*• Knowledge of Java, Android SDK, Android NDK;
*• Knowledge about building/debugging on Android/iOS;
*• Knowledge about social features for games;
*• Knowledge about communication between client and server.

### Ideally

* • Have knowledge in algorithm: Path finding, collision, behavior tree..
*• Have experience with script language

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* •        Publish games for international market;
*•        Build and run the game project based on an existing source code;
*•        Understand game logic and structure;
*•        Provide solutions for additional game features;
*•        Collaborate with cross-functional teams to integrate new features;
*•        Integrate 3rd party SDK into the game;
*•        Work on bug fixing and improving game performance.
*•        Someone who possesses a unique blend of business and technical savvy; a big-picture vision, and     the drive to make that vision a reality
*•        Able to find innovative solutions for the broader market and enjoy spending time in the market to understand their problems.

### Why it would be awesome to work with us
* Good working environment
* Friendly people

### Contact
Homepage: http://gogame.net/
Email: hien.ha@gogame.net 
Skype: haanhhien031192

**Comment by joneslee85** [comment]
Please re-submit a new post that complies with Markdown format, please also read our README again, we requires the post answer questions:

`What are hard problems that your company is trying to solve?`
