### ISSUE TITLE
[Pillarcare] - [Ruby on Rails dev and team leader] - [HCMC] - [FT]

### ISSUE THREAD

**Issue by acandrei** [awesome-jobs/vietnam#487]
## Location

* Saigon, Vietnam

## Salary Expectation

* 1.5K-3K USD

## Requirements
*Solid understanding of web technologies, relational databases and object oriented design
*Specific knowledge and experience of Ruby, Rails, Chef, MySQL, and HTML5
*Source Control using Git
*Ability to lead development efforts
*Ruby gem creation/maintenance
*Ruby Meta-programming
*Practical experience implementing test driven design strategies, including experience with mocking/simulating external services

### Must Have

*We are all good, friendly guys here so we expect you to be the same;
*Good spoken and written English is a must; 
*Leadership skills;

### You’ll be responsible for

*We are now expanding our team of developers with a Vietnamese branch. We are looking for an experienced Ruby on Rails developer that can act as a team leader to build the Uber of homecare.

### Why it would be awesome to work with us

*Come work as Ruby developer at a growing company that offers great benefits and opportunities to advance, travel,  and learn alongside a great international team.

### What are hard problems that your company is trying to solve?

Pillarcare is changing the Asian homecare sector by leveraging on technology to improve the lives of elders that want to age respectfully, at home.

*We are open minded, flexible, our team is our family;
*We are in love with technology combined with social impact and we thrive for our work to score a victory for the humanity;

*The company is based in Singapore with offices in KL. Soon to expand to other places in Asia, Australia and Europe. 

### Contact
Homepage: Pillarcare.com
Trollman: andrei_at_pillarcare_dot_com (mobile number optional)

**Comment by joneslee85** [comment]
Please revise the format of the post, it does not comply with Markdown, and the Contact section shows that you mainly copy and paste without checking.

**Comment by acandrei** [comment]
Sir yes sir affirmative!

**Comment by joneslee85** [comment]
@acandrei I have not seen any amendment made. I am closing this job post.
