### ISSUE TITLE
Frontend developer - Dinosys - HCM - Fulltime

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#489]
## Location
204 Pasteur, Ward 4, District 3, HCM city

## Salary Expectation
$600-$1000

## Requirements
* HTML5
* CSS3
* Angular 2
* 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies

## Skills
Strong JavaScript and AngularJS skills. Experience with Angular 2 or TypeScript is a plus

### Must Have

• Experience building responsive web apps
• Strong analytical and problem solving abilities
• Strong communication and client facing skills

### You’ll be responsible for
• Front-end Mobile Web development (HTML5, CSS3, Angular 2, integration with RESTful Web API)
• Maintain existing software
• Constantly learn and keep abreast of emerging technologies
• Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
• Critique software designs and architectures
• Peer review colleagues code and identify areas for improvement
• Provide development task effort estimates
• Conduct client requirements gathering and analysis
• Review test plans
• Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
Come work as Front-end developer at a growing company that offers great benefits and opportunities to advance.
### Contact
Email: oanh.tang@dinosys.vn
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
Please revise the format to ensure it is compliant to valid Markdown format. also please have a section that answer `What are hard problems that your company is trying to solve? question
