### ISSUE TITLE
Back-end Developer - Dinosys - HCM - Fulltime

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#490]
## Location

204 Pasteur, Ward 4, District 3, HCM city

## Salary Expectation
$600-$1000

## Requirements
* Ruby on Rails or Grape API
* HTML5
* PostgreSQL
* 2+ years Software Engineering experience

## Skills
•	Experience with Ruby on Rails or Grape API
•	Experience writing tests with RSpec/MiniTest and doing Continuous Integration is a plus
•	Experience working with relational database (PostgreSQL)
•	Experience setting up servers (nginx etc.) and automating deployment process (Docker, Ansible, Chef etc.)
•	Experience with building beautiful and efficient APIs

### Must Have
•      Basic understanding of front-end technologies, such as JavaScript, HTML5, and CSS3
•      Solid understanding of object-oriented programming
•      Strong analytical and problem solving abilities
•      Strong communication and client facing skills

### Responsibilities

- Design, build, and maintain efficient, reusable, and reliable Ruby code
- Integration of data storage solutions
- Help maintain code quality, organization and automatization
- Constantly learn and keep abreast of emerging technologies
- Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
- Critique software designs and architectures
- Peer review colleagues code and identifying areas for improvement
- Provide development task effort estimates
- Conduct client requirements gathering and analysis
- Review test plans
- Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
Come work as Front-end developer at a growing company that offers great benefits and opportunities to advance.

### Contact
Email: oanh.tang@dinosys.vn
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
Please revise the format to ensure it is compliant to Markdown format, and please also have section `What are hard problems that your company is trying to solve?`
