### ISSUE TITLE
Rubify Technology - Junior Web Developer - HCMC - FT

### ISSUE THREAD

**Issue by jameshuynh** [awesome-jobs/vietnam#491]
## Location

* 145 Le Quang Dinh Street, 14th Ward, Binh Thanh District, Ho Chi Minh City, Vietnam

## Salary Expectation

* $300 - $600/month

## Requirements

* Proﬁcient in HTML, CSS, Javascript.
* Ability to work with databases such as MySQL.
* Desire to learn new web technologies and programming languages.
* Ability to deliver on original stated project milestones.
* Willingness to adapt to change of priorities and work under tight deadlines.
* Ability to read and thoroughly understand English documents and specifications.
* Ability to communicate well (including speaking and writing) in English is also an added advantage.
* Experience in Ruby on Rails is a plus.
* Fresh graduates are strongly encouraged to apply.

### Must Have

* Proﬁcient in HTML, CSS, Javascript
* Able to analyse and propose solutions to problems
* Able to communicate and collaborate effectively with the team

### Ideally

* Experience in Ruby on Rails
* Familiarity in Photoshop.
* Able to read and type English

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Develop, test and maintain web applications
* Work with a dynamic and co-operative internal team to execute web projects of all kinds
* Study project requirements and highlight questionable points early
* Learn and understand how existing and new applications function
* Document changes for new functionality and enhancements
* Applying knowledge of industry trends and developments to improve service to our clients
* Adapt to situations and be ﬂexible to explore solutions to counter roadblocks in projects

### Environment

Rubify Technology specialises in designing and developing web and mobile applications for people and businesses. By keeping up-to-date on the newest technological and business trends, Rubify provides excellent service and intricate tech solutions that promote productivity and proﬁtability. Rubify’s team is made up of people with complementary strengths which allows for well-rounded and thoughtful tech products suitable for each client’s unique needs.

At Rubify, we believe that team work is where ordinary people come together with their individual capabilities to achieve extraordinary results. We aspire to build a strong team where excellence and quality are sought after as we do small things to make big things happen. Our people are our greatest asset. They are exceptionally team-oriented and skilled individuals who want to do work that matters to users.

We offer you a trustworthy, caring and exciting working environment, whereby your colleagues are friendly, fun and supportive! We celebrate our birthdays together and bond with one another through various activities from dinners, dancing to playing soccer!

Join us and embark on a rewarding, challenging and meaningful career journey.

You can refer to our website: http://rubify.com

### Benefits
-   Annual salary review based on performance
-   Loyalty award starting from second year of service
-   13th month salary
-   Overtime pay (where applies)
-   Insurance beneﬁts for your health needs
-   Annual cohesion trip and team building activities.   There is always strength in numbers and certainly greater power in united people. We believe in taking time off work to recharge and refresh so that we can come back as a more united team.

### Work and Training
-   Probation: 2 months
-   Working hours: 8 hours/day (8am - 5pm), 5 days per week
-   Lunch hours: 11:45am - 1:15pm
-   Training: Training to develop web application on Ruby On Rails Framework
### Paid Leave
-   Non-working days: Saturday and Sunday
-   Holidays: Vietnam Public Holidays
-   Paid leave: 12 days per calendar year
### Contact

Please send your resume and/or CV to Nina at this email address nina@rubify.com

**Comment by luvcjssy** [comment]
Dear,
I have sent my CV to HR email. However, I do not know that your company has received my CV yet. 
Regards,
Hoan Nguyen

**Comment by jameshuynh** [comment]
Thanks Hoan for applying. We will review your CV get back to you soonest.

**Comment by Vuta** [comment]
Dear @jameshuynh,
I have sent my CV for Junior Web Developer at your company. Please let me know if there was anything else you would like to see in order to improve my candidacy. 
Thank you for your time.
Sincerely,
Tran Anh Vu

**Comment by jameshuynh** [comment]
Thanks Vuta, will review your resume and contact you soon.

**Comment by joneslee85** [comment]
Thanks for the submission, can you please also have answer for question `What are hard problems that your company is trying to solve?` in the body? Cheers
