### ISSUE TITLE
GD Systems - Java/Android Developer - Surabaya, Indonesia - FT

### ISSUE THREAD

**Issue by cinlung** [awesome-jobs/vietnam#492]
## Location
* Surabaya, Indonedia

## Salary Expectation
* $400 to 800/month depending on skills

## Requirements
* Java minimum 2 years experience
* Java script
* MySQL
* 1+ years on android development

## Skills
Java, JSP, CSS, Javascript, android or similar.

### Must Have
* Be able to live locally
* Be able to finish projects on time responsibly
* Understand lifecycle of the software
* leading programmer team is a great plus.

### Ideally
* Experience with Java for more than 3 years
* Experience to work on schedule
* Able to lead a small team for a project

### Responsibilities
* Develop the cureent ERP product and oher software
* Create proper documentation of the software created
* Well testing the created software before release

### You’ll be responsible for
* Building ERP softwqre based on web and software for devices,

### You can bring
* A good eyes for design
* A good analyis skill
* Good responsibility for finishing your work well

### Why it would be awesome to work with us
* Great lifestyle at a fraction of a cost
* Great food and cultures
* Living like kings on cents

### What are hard problems that your company is trying to solve?
* Having someone with high sense of responsibility and be able to perform right with positive attitudes for the company.

### Contact
Homepage: www.gdincorporation.com
Email: Rendra Basuki (rbasuki@gdincorporation.com) cc to gdtrinity@gmail.com

**Comment by joneslee85** [comment]
I am not convinced with the answer for `What are hard problems that your company is trying to solve?` - can you please come back with more well-thought answer on that?

**Comment by cinlung** [comment]
Dear Trung

This post was a while ago. Could you help me with yhe link to my post? I
will try to explain more as much as I could.

Thank you
Rendra

**Comment by cinlung** [comment]
Help me write these problems in a language that you think is best as human resource is the main problem in our company:
1. Our hard problem is human, both in skills and commitments
2. When people facing problems like hard coding problems, they tend to quit.
3. I need people who can work on the agreed project and keep their end of the bargain and be able to meet the greed schedules.
4. When they need resources, they can be proactive to search for solutions instead of waiting for answers and bothering other senior progrmmers or other people.
5. When they were assigned a project we always discuss upon the deadline with the progrmmers on their ability and time to both understand and deliver the result. If deadline not met, they need to work more to meet the agreed deadline and chase any late release date. Most people just quit or extends project time indefinitely
6. When they begin working in our company they often expect to be trained in programming. While where I used to work, we bring skills into the comoany and ready to work. Nowadays, graduates from computer schools expect to be trained in basic java.

Those are the problems we are facing, help me answer that questions or can I use the list above?

**Comment by joneslee85** [comment]
@cinlung I think you might have misunderstood my question. I was implying about what products you company are doing, what hard problem would those products solve?

**Comment by cinlung** [comment]
Oh,

I will fix accordingly
