### ISSUE TITLE
Magic8Labs - Python Developer Contract $3,000/month- HCM- FT or PT 💣💣

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#501]
<div class="edit-comment-hide">
    <table class="d-block">
      <tbody class="d-block">
        <tr class="d-block">
          <td height="1135" class="d-block comment-body markdown-body markdown-format js-comment-body">
              <h2><img src="http://magic8labs.com/new.jpg" width="1074" height="200" alt=""/></h2>
    <h2>Full time or Part Time OK! 1-4 Month Contract - Pay set to $3,000 /month</h2>
    <h2>Location</h2>
              <p>572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City</p>       
              <h2>Python Experts Listen up!! Magic8Labs wants to kick some butt and we need you to do it. </h2>
<p>We have taken on the challenge to make a crawler for our product server side. We have made a crawler before but need it to be made completely in python and run on the server side. We thought about Golang and some other languages as well. </p>
<h2>About our project: </h2>
<p>Our product is NOT for the Vietnamese market. It is for ecomm people in the USA market. It is totally legal and does not cause issues with anyone. There are other companies doing this software so we are not inventing something new. </p>
<h2>What we are looking for: </h2>
<ul>
  <li># 1- Python developer who loves a nice cup of coffee and challenge. </li>
  <li># 2- Love to work in a small team and impress others on how cool you are when your code works.</li>
  <li># 4- Team Player, open minded </li>
  <li># 5- See rule # 1 :)</li>
</ul>
<h2>Contract Salary:</h2>
<ul>
<li> $3000 / Month </li>
</ul>
<h2>Referral Fee:</h2>
<p>Help us find someone and we'll give you a generous referral fee  after they start out of probation. </p>
<h3>Contact:</h3>
<p>Email: Quynh Kim quynh.kimthinhu@gmail.com</p>
<p>https://itviec.com/companies/magic8labs </p>
<p>Facebook: https://www.facebook.com/kim.thinhuquynh <br>
</p></td>
        </tr>
      </tbody>
    </table>

**Comment by euronck** [comment]
who loves python! I love python ra ra.

**Comment by joneslee85** [comment]
The job post does not comply with format guideline and I am going to close it now.

Please re-submit new job post with following revised items

- job title
- remove any references to itviec
- what is this job actually? What is ecomm people? What are legal implications?
- job post does not answer prequites questions, please
