### ISSUE TITLE
Viral Foundry - Full Stack Developer - Build new MVP from scratch - Remote - 2 week contract

### ISSUE THREAD

**Issue by allbombs** [awesome-jobs/vietnam#516]
Viral Foundry is looking for a full stack developer to build a brand new MVP. You will write the first lines on a new product we're launching. This is a contract position with opportunities to convert into full-time. Looking for someone to start ASAP. 

## Location
* Saigon, Vietnam
* Remote

## Salary Expectation

* Negotiable based on experience

## Requirements
- Awesome. Talented developer with a great attitude.
- 2+ years experience
- Need to be able to show some code / github code review
- Degree in Computer Science or related field a plus
- At least 2 shipped apps
- Outstanding communication skills, can read/write/speak english
- Accountable, and will do what it takes to ship products and puts customers first

## Skills / Experience
Have experience with designing RESTful JSON API
You should have apps that demonstrate your backend (API) skills

## What you will be building
A brand new product! A small MVP that includes a small web app. It's small, but fun. Great portfolio piece.

## Contact
Superstars welcome, huge egos are not. Please send us an email and introduce yourself.

Homepage: ViralFoundry.com
kenny@viralfoundry.com

**Comment by huydx** [comment]
@allbombs please refer to our post guideline and correct your JD

**Comment by joneslee85** [comment]
No amendment after 2 weeks.
