### ISSUE TITLE
Terralogic - Associate/Fresher Frontend Developer - Saigon - FT 

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#518]
Terralogic (former Infornam), headquartered in Silicon Valley, USA is an Engineering & IT services company. It with 1,000 employees and three development centers in US, India and Vietnam provides comprehensive solutions that are cost-effective, scalable and flexible.

The company serves global clients, among them technology pioneers and industry leaders. Our core team is composed of engineers and domain experts who has strong experience and understanding of Mobility, Applications, Networking & Communications and Embedded Systems.

We are building the unimagined and aspiring to be be the most loved organization in the coming years. Accordingly human resources are regarded as our jewels. Terralogic offers a dynamic working environment, professional development and high-end facilities. Our engineers have opportunities to work with foreign customers as well as working onsite in Japan, Europe and the US.
## Location
- Saigon, Vietnam
## Salary Expectation
- Competitive
## Requirements
- 1 year experience or no experience but love to work on Javascript fullstack development
- Experience ReactJs and React DOM, using REST APIs or NodeJS
- Understand of OO concepts in JavaScript context
- Comfortable with Github, JIRA and Confluence
- Open mind and willing to learn new things
- Fluently in English is a PLUS
### Responsibilities
- Develop new features and fix bugs on cutting-edge technologies: ReactJS, NodeJS, MongoDB
- Go deep with CMS to build awesome sites
### What Terralogic offer
- Flexible working schedule. Everything is allowed by trusting the employees
- Competitive Salary: 13th salary + performance awards + project awards; Referral Bonus
- Opportunities for advanced career development overseas: in America, Japan, India…
- Good benefit that takes care of employees work-life balance:
- Insurance: Accident Insurance 24/24 (Gras Savoye Willis); Health Insurance (Gras Savoye Willis):
- Social Insurance tax: was paid as the salary in the labor contract
- Special Leave Days: minimum 15 days/year
### Contact
- Ms Mai Ngo: mai.ngo@terralogic.com
- Skype: mai.ngo91

**Comment by dvkndn** [comment]
Hi Ms. Mai,

As in your 1st requirement, I confirm I have "no experience but love to work on Javascript fullstack development".

However, as having no experience, I see that I'm far from satisfying the 2nd and 3rd requirements:
> Experience ReactJs and React DOM, using REST APIs or NodeJS
> Understand of OO concepts in JavaScript context

**So, my question is, should I apply?**

- If yes, does that mean I can apply without satisfying all requirements?
- If no, does that mean the "no experience but love..." part is redundant and should be removed?

**Comment by RecruiterMaiNgo** [comment]
Hi Thien,
Thanks for your interest in our job. Actually, we are looking for a young, passionate and enthusiastic person in JavaScript fullstack. Good english is a big PLUS for this position.  So we welcome all applications from Freshers. Because it's quite difficult to train your English, but it's possible to train you more about technical skills.
The 2nd & 3rd  requirements, just want to share more about the technology we aim to. And we also look for candidates with 1-2 yrs's exp. That's why we still keep it here.
Look forward to hearing from you!
Best regards,
Mai Ngo (Ms.)

**Comment by dvkndn** [comment]
Thank you :D I'm glad to hear that. I think it's better to be clear about your requirement on English. I agree with that but haven't see it at first (maybe because it is a "plus", and placed at the end of the list).

**Comment by RecruiterMaiNgo** [comment]
So, should you get interest in this job, please feel free to contact me as the signature above :-)

**Comment by dvkndn** [comment]
Thank you. I will sure contact you when I'm interested in this job (or give your contact to my friends who I think will interest in this).
