### ISSUE TITLE
Dinosys - Frontend Developer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#521]
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.

## Location

* Saigon, Vietnam

## Salary Expectation

* competitive

## Requirements
HTML5
CSS3
Angular 2
1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies

### Must Have
• Experience building responsive web apps
• Strong analytical and problem solving abilities
• Strong communication and client facing skills

### Ideally

• Experience building responsive web apps
• Strong analytical and problem solving abilities
• Strong communication and client facing skills

### You’ll be responsible for

• Front-end Mobile Web development (HTML5, CSS3, Angular 2, integration with RESTful Web API)
• Maintain existing software
• Constantly learn and keep abreast of emerging technologies
• Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
• Critique software designs and architectures
• Peer review colleagues code and identify areas for improvement
• Provide development task effort estimates
• Conduct client requirements gathering and analysis
• Review test plans
• Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Benefits for you
- Working in dynamic invironment, young, professional and fast growing 
- Free to raise your idea to build up your team & company.
- Laptop is provided
- 12 days annual leaves, working Monday - Friday, flexible working time
- Salary review 2 times/ year
- Free parking fee for your bike
- Got benefits according to company's regulations
- Employee Benefits: Social insurance, Health insurance, -
- Unemployment insurance and Sick leave: based on current relevant Laws
- Team building monthly
- Training new technology frequently

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
@tangoanh can you please revise the format of the body? It does not comply with the Markdown format. Lastly, the body lack the answer for two questions:

` Why it would be awesome to work with us (MUST)`
` What are hard problems that your company is trying to solve? (MUST)`

**Comment by joneslee85** [comment]
No amendment after a week
