### ISSUE TITLE
Dinosys - Back-end Developer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#522]
## Location

* Saigon, Vietnam

* competitive

## Requirements
Ruby on Rails or Grape API
PostgreSQL
JavaScript, HTML5, and CSS3

### Must Have

• Experience with Ruby on Rails or Grape API
• Experience writing tests with RSpec/MiniTest and doing Continuous Integration is a plus
• Experience working with relational database (PostgreSQL)
• Experience setting up servers (nginx etc.) and automating deployment process (Docker, Ansible, Chef etc.)
• Experience with building beautiful and efficient APIs
• Basic understanding of front-end technologies, such as JavaScript, HTML5, and CSS3
• Solid understanding of object-oriented programming
• Strong analytical and problem solving abilities
• Strong communication and client facing skills

### You’ll be responsible for

• Design, build, and maintain efficient, reusable, and reliable Ruby code
• Integration of data storage solutions
• Help maintain code quality, organization and automatization
• Constantly learn and keep abreast of emerging technologies
• Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
• Critique software designs and architectures
• Peer review colleagues code and identifying areas for improvement
• Provide development task effort estimates
• Conduct client requirements gathering and analysis
• Review test plans
• Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Benefits for you
- Working in dynamic invironment, young, professional and fast growing 
- Free to raise your idea to build up your team & company.
- Laptop is provided
- 12 days annual leaves, working Monday - Friday, flexible working time
- Salary review 2 times/ year
- Free parking fee for your bike
- Got benefits according to company's regulations
- Employee Benefits: Social insurance, Health insurance, -
- Unemployment insurance and Sick leave: based on current relevant Laws
- Team building monthly
- Training new technology frequently

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
@tangoanh can you please revise the format of the body? It does not comply with the Markdown format. Lastly, the body lack the answer for two questions:

` Why it would be awesome to work with us (MUST)`
` What are hard problems that your company is trying to solve? (MUST)`

**Comment by joneslee85** [comment]
No amendment after one week.
