### ISSUE TITLE
Dinosys - Project Manager - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#523]
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.

## Location

* Saigon, Vietnam

## Salary Expectation

* competitive

## Requirements
3-5 years of working experiences, minimum 1 year of working as a Project Manager of IT projects

### Must Have
• Bachelor degree or higher from an accredited college or university
• Knowledge in technology, computing, programming is a must 
• Strategic and analytical skills
• Fast learner, creative and communicative and self-teaching
• Team player, able to work independently and cooperatively with other BA, engineers and PM
• Good English and computer skills

### You’ll be responsible for
• Communicate and face customer business teams.
• Define and document customer business functions and processes. 
• Consult with functional unit management and personnel to identify, define and document business needs and objectives, current operational procedures, problems, input and output requirements, and levels of systems access. 
• Act as a liaison between technical team and business team (mostly clients) in the analysis, design, configuration, testing and maintenance of case management systems to ensure optimal operational performance.
• Further develop test cases for final products.
• Coordinate with testing team, QA team to ensure the quality of final products.
• Being the PM of the project in term of planning, keeping track of the projects
• Provide deliverable documents such as functional specification, blueprint, requirements documents, test cases.

### Why it would be awesome to work with us
- Working in dynamic invironment, young, professional and fast growing 
- Free to raise your idea to build up your team & company.
- Laptop is provided
- 12 days annual leaves, working Monday - Friday, flexible working time
- Salary review 2 times/ year
- Free parking fee for your bike
- Got benefits according to company's regulations
- Employee Benefits: Social insurance, Health insurance, -
- Unemployment insurance and Sick leave: based on current relevant Laws
- Team building monthly
- Training new technology frequently

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
@tangoanh can you please revise the format of the body? It does not comply with the Markdown format. Lastly, the body lack the answer for two questions:

` Why it would be awesome to work with us (MUST)`
` What are hard problems that your company is trying to solve? (MUST)`

**Comment by joneslee85** [comment]
no amendment after one week
