### ISSUE TITLE
Magic8Labs- JavaScript Node.JS Senior Developer- Saigon – FT 

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#524]
<div class="edit-comment-hide">
    <table class="d-block">
      <tbody class="d-block">
        <tr class="d-block">
          <td height="1135" class="d-block comment-body markdown-body markdown-format js-comment-body">
              <h2><img src="https://s3-us-west-2.amazonaws.com/magic8labsmediaassests/Main+Logosm.jpg" width="800" height="159" alt=""/></h2>
              <h2>&nbsp;</h2>
    <h2>Location</h2>
              <p>572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City</p>       
              <h2> Startup with founding father opportunity + equity.... Say hello to Magic 8 Labs :)</h2>
<p>This is an opptunity that just opened and its not going to come around again. We are in the business   of building software platforms that solve  problems of real users. We don't build games or make boring software for outsourcing   clients. Great achievements start with working to solve  a problem. We are doing just that! </p>
<p>If you are a hard working person, who wants to be challenged   to learn and grow. If you want to be apart of something from the ground up well here is your chance. Join us! </p>
<p>NOTE: Looking for a big company or scared of risks, want a job in a nice big office and a big fat paycheck with free snacks then we are not the company for you. Not yet anyways! Steve Jobs started in his garage! </p>
<p>&nbsp;</p>
<h2>What are we cooking at Magic 8 Labs?</h2>
<p>We working like crazy to make SaaS platform for amazon sellers  the 1st of many to come. We are a USA backed (me the owner) startup up with a vision, direction and persistence.  </p>
<p>Currently we are cooking with JavaScript framework (AngularJS, NodeJS, Meteor). We are baking a complete SaaS platform with a bootstrap and shoe string method.</p>
<p>We are looking for someone who has a programming background, knows  Javascript enough to make things happen but wants to learn all the awesome frameworks we use. Remember JavaScript is the future :P  </p>
<p>You will be employee lucky next partner/developer. </p>
<p>&nbsp;</p>
<h2>Requirements (in order of how important they are to us)</h2>
<ul>

<li># 1- Full of energy to become a JavaScript Ninja (if you have a good base of Javascript its a start)</li>
<li># 2- You have exprience with JavaScript Framework experience like NodeJS, AngularJS</li>
<li># 3- You want to work for a Startup with all the good and bad that it comes with</li>
<li># 4- Team Player, open minded </li>
<li># 5- We could careless about how talented you. If your heart isn't in the right place this job isn't for you!</li>
<li># 5- You are not married and have time to devote to your career. (sorry married guys/gals we need to work overtime)</li>
</ul>
<h2>Reasons to come to work everyday! AKA Benefits</h2>
<ul>
<li>Friendly, flexible, and fun working environment. </li>
<li>Building activities are part of our life.</li>
<li> Salary review every year or on excellent performance.</li>
<li>On-the-job training by our team leads and courses you want to take that we pay for.</li>
<li>Mac computer is provided.</li>
<li>Free lunch everyday.</li>
</ul>
<h2>Salary Expectation</h2>
<ul>
<li>Up to $2000 with other (please email for details)  </li>
</ul>
<h2>&nbsp;</h2>
<h3>Contact</h3>
<p>Email: Quynh Kim quynh.kimthinhu@gmail.com</p>
<p>Facebook: https://www.facebook.com/kim.thinhuquynh <br>
</p></td>
        </tr>
      </tbody>
    </table>

**Comment by giangnm** [comment]
Really can be up to $2,000 ? :+1:  :)

**Comment by euronck** [comment]
I know I am crazy right! But we want to attract the right person. HCM is way to overcrowded with dreamy startups but in our case we dreamy about finding the right person not the other way around. @giangnm there's a referral fee if you know a candidate :P

**Comment by giangnm** [comment]
Cool. Are you Nick? Hope so, then your remember me. I arrived your office last month.

**Comment by tiengtinh** [comment]
Hello @euronck , might I have some question?

1. By AngularJS, do you meant AngularJS 1.x? Nowadays, Angular 1.x is normally preferred as AngularJS, and Angular 2 is just Angular. And Angular 2 is a completely different beast.

2. Why Meteor? I don't know much about Meteor but I've heard it's great to get a real-time app up and running but have scaling issues down the way.

**Comment by euronck** [comment]
@tiengtinh yes Angular 1 is what we use. We are holding off on 2 until its more production ready. Agreed 2 is very different one of the reason why our guys are not using it.  Meteor was a promising framework and it still is in some ways. Don't worry about learning Meteor you will pick it up quick a new junior has already picked it up in several days. Its very easy to learn and use. We built several other projects using it and really liked the pros' over the cons. We will be using it in a production environment but are always open to something different. drop me a line at mavridisn@hop-code.com. Magic8Labs is the new outfit that we are releasing just in case if ur wondering.

**Comment by dvkndn** [comment]
Sorry if I'm bothering you guys.. I just want to say I'm actually like this job post a lot. It is not about the position, but I love how @euronck answers the technical questions here very detailed.

Recently there are more and more job that is posted by HR. They are good, but they just can't answer things like this or interact with the candidate in this way.. This makes the post a lot more "human", which somehow reflect the culture of your team ;)

**Comment by euronck** [comment]
Thanks @dvkndn . I believe every product owner / company owner should have a big part in hiring and bringing on new people to their family (employees). Too many companies worry about the bottom line. Know your stuff and the people who you trying to attract. At the end of the day! My product is about people "my family (employees)" NOT the paying customer. The value they [customer] finds from our product allows us [my family] to live better lives :)
