### ISSUE TITLE
Dinosys - UI-UX Designer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#526]
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.

## Location
* Saigon, Vietnam

## Salary Expectation
*competitive

## Requirements
* Sketch; Zeplin; InVision.
* Adobe Suite.
* English proficiency
* 1-3 years of digital design experience

### Must Have
• 1-3 years of digital design experience.
• English proficiency.
• Familiar with design and prototyping tools such as: Sketch; Zeplin; InVision.
• Familiar with graphic design tools, specially Adobe Suite.
• Experience designing for a range of platforms and devices, such as: iOS; Android; Responsive; Tablet; and Mobile.
• Strong communication, facilitation and presentation skills.
• Excellent attention to detail.
• Analytical and strong problem solving skills.
• Ability to produce results independently as well as collaboratively in a team environment.
• Experience designing for a range of industries and product types will be highly regarded.
• Curiosity, enthusiasm and willingness to learn.

### You’ll be responsible for
• Design the approach and conduct User research.
• Create and communicate User flows, Information Architecture, Wireframes and Sitemaps to a wide variety of people with varying levels of interface ability and knowledge including: Client representatives, Consumers, Development Teams, Designers, Producers, Senior Managers, Commercial team, and Suppliers
• Capture, analyze and communicate findings throughout the project.
• Present ideas, concepts and pitches in a relevant, timely and engaging manner (from casual sketches fully realized visuals)
• Deliver pixel-perfect designs that are as usable as they are beautiful.
• Assist with pitches, presentations and other graphic design needs.

### Benefits for you
• Working in dynamic invironment, young, professional and fast growing
• Laptop is provided
• 12 days annual leaves, working Monday - Friday, flexible working time
• Salary review 2 times/ year
• Free parking for your bike
• Employee Benefits: Social insurance, Health insurance, -
• Unemployment insurance and Sick leave: based on current relevant Laws
• Team building monthly
• Training new technology frequently
• Free to raise your idea to build up your team & company.

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by huydx** [comment]
@tangoanh please refer to our job post guideline and correct the JP

**Comment by joneslee85** [comment]
Closed. No amendment was made after a week.

**Comment by tangoanh** [comment]
@joneslee85: Thank you for your advise. Please help me to check it again.
