### ISSUE TITLE
Relia Software - Junior/Senior Web Developer (ReactJS/AngularJS/NodeJS)- HCMC - FT 

### ISSUE THREAD

**Issue by linhhtd** [awesome-jobs/vietnam#528]
## Location

* Phu Nhuan, Ho Chi Minh

## Salary Expectation

* $700-2000$/month

## Requirements
We are looking for reactjs/angularjs/nodejs developer to expand our team of web developers. As an innovation driven application development company we work on some of the exciting technologies and projects.

### Must Have
Proficient in javascript any framework : Reactjs, Angularjs, Nodejs.
Must work with Reactjs at least 6 months in production project.
Good knowledge in HTML5, CSS3, Object-Oriented and Functional JavaScript.
Good English speaking and written skill.
Willing to learn new technology.

### Responsibilities

As part of our team, your focus would be:

Work closely with our customers, to understand their needs and deliver them with quality
Be upto date with latest technologies
Be able to pick up new technologies
Reactjs developer must be able to travel to Italy and Spain for 1-2 month to work on-site with client.

### Why it would be awesome to work with us

Flat organization and open communication
Friendly working environment and flexible working hours.
13th salary, insurance and team building activities.
Great opportunity to develop career.
Salary: 700$-2000$

### Contact
Email: dieulinh.ht234@gmail.com 
Facebook: https://www.facebook.com/dieu.lihn

**Comment by nvs2394** [comment]
Cool

**Comment by linhhtd** [comment]
@nvs2394 : bé cưng chị tìm cho 4 công ty liên quan JS developer lận, up to 2000$ hết. Check network giùm chị nhóe

**Comment by huydx** [comment]
@linhhtd are you official representative of the company, or agent? 
If you're agent, sorry our job board currently do not accept agent job posting

**Comment by linhhtd** [comment]
@huydx : I am so sorry. I don't know that. I am freelance headhunter.
Both of jobs I posted are ones my clients need me to find for them because they do not have enough time to spend recruiting

**Comment by T-Pham** [comment]
So an agent cannot officially represent a company, apparently.
