### ISSUE TITLE
WAKUMO.VN - Rails Developer - Da Nang - FT

### ISSUE THREAD

**Issue by anhdungwkm** [awesome-jobs/vietnam#531]
## Location

* Da Nang, Vietnam

## Salary Expectation

* $800 - $1,600/month

## Requirements

* Ruby on Rails
* 1+ years Software Engineering experience

### Must Have

* Mac OS X
* Ruby on Rails
* Git
* RSpec
* SQL92
* PostgreSQL
* Basic English communication

### Ideally

* Use Linux/Ubuntu
* Use Docker/Swarm
* Design Microservices/kong
* Knowledge of Blockchain/Bitcoin
* Knowledge of Infrastructure/OpenStack
* Agile/Scrum experience
* Japanese communication
* Test-driven development
* Have experience with designing RESTful JSON API

### Responsibilities

* Keep your codes high quality and secure.
* Scalable API development.
* Do not Repeat Yourself.
* You should find your task by yourself.
* Working Monday - Friday, flexible working time (8hours/day)

### You’ll be responsible for

* Mac book /External Monitor is provided.
* 100% social and medical insurance
* 14th-month salary
* 12 days annual leaves

### Why it would be awesome to work with us

* We can develop awesome businesses in Japan because we have strong relationships with clients.
* We have own Infrastructure as a Service named [Unit Hosting](https://www.unit-hosting.com/).Our data center is located in Kyoto.
* Work with [a Top ranked ruby developer](http://git-awards.com/users?country=vietnam&language=ruby) in Viet Nam.
* Our company started up from April, 2017 with two members (1 japanese and 1 vietnamese). 
* We're planning to create an elite-team with 8 members. Hope you to become one of our best members! 

### Contact
Homepage: https://wakumo.vn/
Please sent your CV to mail: recruit@wakumo.com

**Comment by euronck** [comment]
very cool.. someone else is cooking with Blockchain 👍
