### ISSUE TITLE
Wonolo - Backend Engineering Lead - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by dinhthi1610** [awesome-jobs/vietnam#533]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2500/month or range

## Requirements
* 2+ years experience managing/leading an engineering team

*  recent, hands-on software engineering experience in Ruby-on-Rails and JavaScript. You must have sufficient hands-on skills to earn the respect of the current backend development team.

* experience with agile software development, preferably with Kanban/just-in-time development

* experience with high-traffic, consumer-facing web applications and the scalability challenges they create

* experience with automated testing and test-driven development

*  preferred, experience working remotely with a team located in the US

### Must Have

* “can do” attitude, self-starter, able to deliver results independently without

close management (your boss will be 15 hours and 7,800 miles away)

* ability to lead and inspire a team of engineers to write great code and hold

them accountable to deliver results - you will be an important and

influential voice in building the team culture

### Why it would be awesome to work with us
* Upgrading salary 1 time/year or when you have excellence achievement
* Working 5 days/week , from Monday to Friday ,work at home on Friday, off on Saturday and Sunday
* Great chance to develop your skills and competences via coaching and mentoring program
* “Share to learn and learn to share” philosophy
* Opportunities for promotions and career development in a dynamic environment
* Support sport cost for team building activities (badminton, football, tennis, swimming)
* Social insurance follow Vietnam’s law
* Quarterly company trip
* 13th month salary
* Opportunities to travel to US
* Social insurance : $250/year
* Attend English classes at the company
* Free snacks & beverages

### Contact
Homepage: wonolo.com
skype : dinhthi1610 (0902800862)

**Comment by joneslee85** [comment]
Please include answer for `What are hard problems that your company is trying to solve?` question in the job post and please remove link to itviec.com from the job post.
