### ISSUE TITLE
Wonolo - Front-end Web Engineer - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by dinhthi1610** [awesome-jobs/vietnam#534]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2000/month or range

## Requirements
* 2+ years web development experience

* 1+ years jQuery and/or related front-end technologies (Backbone.js,Angular, etc)

* experience implementing web views from designs provided

* solid, common-sense understanding of UX issues

* cross-browser compliance

* preferred, experience working remotely with a team located in the US

### Must Have

* You will have a passion for clean, intuitive UX

* You’ll be a JavaScript athlete, adept with JQuery and familiar with other libraries such as Angular or Backbone

* You’ll have the engineering chops to get the respect of engineers but the design sense to get the respect of designers

### Why it would be awesome to work with us
* Upgrading salary 1 time/year or when you have excellence achievement
* Working 5 days/week , from Monday to Friday ,work at home on Friday, off on Saturday and Sunday
* Great chance to develop your skills and competences via coaching and mentoring program
* “Share to learn and learn to share” philosophy
* Opportunities for promotions and career development in a dynamic environment
* Support sport cost for team building activities (badminton, football, tennis, swimming)
* Social insurance follow Vietnam’s law
* Quarterly company trip
* 13th month salary
* Opportunities to travel to US
* Social insurance : $250/year
* Attend English classes at the company
* Free snacks & beverages

### Contact
Homepage: wonolo.com
skype : dinhthi1610 (0902800862)

**Comment by joneslee85** [comment]
Please include answer for What are hard problems that your company is trying to solve? question in the job post and please remove link to itviec.com from the job post.

Lastly, please remove the square brackets from the title
