### ISSUE TITLE
SmartDev - Java Developer - Da Nang - FT

### ISSUE THREAD

**Issue by sevneris** [awesome-jobs/vietnam#535]
## Location

* Da Nang, Vietnam

## Salary Expectation

*  from $400 to $1500/ month based on experience 

## Requirements
* 1+ years Software Engineering experience
* Experience with Scrum, Agile methodologies and good documentation skills is a plus
* Experience in Java J2EE technologies
*  Experience using IDE like Eclipse and RAD
*  Experience in Web Services, SOA, SOAPUI

### Must Have
* Experience with Spring, Hibernate, MVC Frameworks is a plus

### Ideally

* Experience with several middle-tier components technologies is desired, including JBOSS, Tomcat, WebSphere, Weblogic
* Experience working in a fast-paced, continuous integration environment utilizing GIT and automated build server technologies (Maven/Jenkins/Hudson/Bamboo) is desired

### Responsibilities

Design, build, test and maintain scalable and stable off the shelf application or custom built technology solutions to meet business needs
•	Contribute to the entire implementation process for new applications and enhancements to existing applications
•	Work in Agile team (5 to 9 developers) to develop software products in various types of web application, enterprise application or web services using Java, J2EE and other related technologies/frameworks
•	Daily cooperate with customer to clarify requirements, initiative solutions and develop deliverable software in the iterations 
•	Be involved in every phases of Agile software development includes planning, estimating, developing and continuously delivering software
•	Self-assign tasks and fully be responsible for quality/quantity of delivered result. Self-determine appropriate architecture, technical solutions and make relevant recommendations to customer
•	Meet with business partners to understand business needs
•	Contribute to overall solution design
•	Responsible for build and test of applications
•	Conduct root cause analysis and complex performance tuning

### You’ll be responsible for

* Building a new secret project

### You can bring

* A good eyes for design
* A good analyis skill

### Why it would be awesome to work with us

* Selected candidates will be working in a friendly and agile environment that promote creativity and pro-activity. They will be able to work with XP, scrum and Kanban depending on their project. They will work on the latest technology for major company in Europe and Middle East such as bank and financial institute.

* What can you expect from us?

- Good work environment and good colleague (parties, holidays, team building activities).
- English/French language courses.
- Free Kindergarten for staff’s kids
- 13th salary
- Lunch Allowance 
- Tea, coffee, milk
- Work on the latest technology
- Two-day weekend: Sat and Sun
- 20 annual leave days alongside Vietnamese public holidays
- Always new challenge (Training provided)
- Self-organize project team
- Work with high profile multinational companies
- Competitive Salary and career evolution based on your performance defined every year

### What are hard problems that your company is trying to solve?
* new projects need new awesome developers

### Notice
*Please to send your CV in English with some apps links that you might done

### Contact
Homepage: www.smartdev.vn
Trollman: job@smartdev.vn (+84 2363 666767)

**Comment by joneslee85** [comment]
Please double check the format, some bullet points are not Markdown format. And the answer to `What are hard problems that your company is trying to solve?` is not really hitting the point. Please try harder

**Comment by joneslee85** [comment]
Closed - no reply after a week already
