### ISSUE TITLE
Silicon Straits Saigon - Senior Ruby Developer - Ho Chi Minh City - FT

### ISSUE THREAD

**Issue by minhminhsss** [awesome-jobs/vietnam#536]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* From $600 to $1200/ month based on experience

## Requirements
* At least 2 years, solid experience working with Ruby on Rails framework.
* Strong knowledge of scaling practices such as in-memory database, load balancer, caching, etc
* Worked with at least one project using Messaging Queues.
* Wide exposure to multiple technology stacks is an advantage, we love full stack guys.

### Must Have

* You will be building scalable systems with microservices. You will get to write code bases that are small and focused on doing one thing well.
* Be able to build microservices for technology freedom, resilience and scalability, though there will be lot of communication between services (does MQ ring any bell?), much automation and tons of metrics we need to keep an eye on.

### Ideally
* Such system aren’t easy. But that is ok. We aren’t here for ease anyway. We are here for people who want to operate at the next level in their career.

### Why it would be awesome to work with us
* To work in all-senior team of developers, designers and product managers.
* Great opportunities to improve your skills in many related fields.
* Flexible working time and unlimited leave days.
* Get your own Macbook.
* Nice bosses.
* Geek Toys.
### Contact
Homepage: https://www.siliconstraits.vn/
Contact: hr@siliconstraits.com (+84 8 6271 8255)

**Comment by joneslee85** [comment]
@minhminhsss please revise the job post:

* Title - the city name
* Contact session - what is Trollman?
* Please answer question "What are hard problems you are trying to solve?"
