### ISSUE TITLE
FCSVN-Frontend Web Developer (Java/Ruby)- HCMC-FT

### ISSUE THREAD

**Issue by fcsvn** [awesome-jobs/vietnam#538]
## Location

* Saigon, Vietnam

## Salary Expectation

* USD900-1300/month or range

## Requirements
•	At least three (3) years of working experience involving full software development life cycle.
•	At least three (3) years of working experience in Java SDK, J2EE, JSON, RESTful, HTML5, JavaScript , MySQL, Report development.
•	Experience with Ruby and Jekyll is a plus.
•	Must have strong frontend skills - HTML/CSS/JS and experience with Bootstrap 4.
•	Good command in both spoken and written English.

### Responsibilities

•	Software coder role – responsible to develop new products
•	Develop and maintain new corporate websites
•	Involved in full development life cycle (requirement, design, development and testing)
•	Maintains existing system/product assigned by Section Manager
•	System support
•	Installation (ad-hoc)
•	Receives and complete job assignments from Section Manager
•	Adheres to programming standard adopted by the company
•	Develops quality software as according specification.
•	Prepare documentations

### Contact
Homepage: http://www.fcscs.com/
Mr Dang : dang.nguyen@planet1world.com

**Comment by joneslee85** [comment]
Sorry but we could not accept this job post. Because:

* Ambiguous job description, I still have no clue what this job is about
* Invalid Markdown format
* Lack of answers for required questions (please see our guideline)
