### ISSUE TITLE
Sephora - API Engineer (Rails) - Singapore - FT

### ISSUE THREAD

**Issue by ericntd** [awesome-jobs/vietnam#539]
## Location

* Singapore (full time)

## Requirements
* Strong programming fundamentals and demonstrated experience with designing and building customer facing APIs
* Experience with REST, related API paradigms and general development best practices
* Strong knowledge of Ruby is preferred
* Experience with API scaling techniques: Analytical skills to identifying bottlenecks, test solutions including caching and benchmark results
* Familiarity across the technology stack is preferred (Javascript, HTML, CSS, Git, SQL, Memcache, Redis, RabbitMQ)
* Strong communication skills to be able to work with cross-functional teams

## Responsibilities
* Ownership of our API design. Conceptualize and enhance our API Interfaces to be intuitive but feature rich.
* Design APIs to be consistent, across different actions, different versions
* Implement the API with Ruby on Rails, our framework of choice
* You are expected to play an active role in planning, estimating the roadmap and ensure seamless delivery
* The API needs to be highly scalable and you will employ a matrix of design choices, caching strategies, optimizing DB dependence and infrastructure suggestions to scale the API
* You will be involved in benchmarking API performance and regular stress test on API
* Implementation of automated unit and contact testing to ensure stability
* Provide L3 Support for API and debug bugs / production issues

## Benefits
Sephora Digital SEA (formerly Luxola) is responsible for the e-commerce activities of Sephora across South East Asia, Australia & New Zealand. We provide our employees with a unique opportunity to take on senior responsibilities, accelerate their career path and be part of one of the fastest growing digital businesses in South East Asia, whilst also benefiting from being part of Sephora, a beauty trailblazer, and LVMH, the world leader in luxury. You can read more about Sephora and LVMH at http://www.lvmh.com/group/

Sephora acquired Luxola in July 2015 in order to accelerate its ecommerce capability and to deliver on the promise of omni-channel to consumers across SEA. Sephora Digital maintains an entrepreneurial, technology focused culture, and is a high-growth business unit within the group. Our employees are passionate about building businesses and we seek talent across a range of disciplines as we continue to build our team. The data is definitive: diversity leads to better teams, better performance, and better results. Consequently, we actively seek candidates of all genders, backgrounds, and experiences.

## Technical challenges
* What poses more interesting yet relatable technical challenges than e-commerce apps?
* We have ~300k active users right now and it will easily become 1m+ in the next couple of months, how do you scale up and how do you keep all of those customers happy and continue to buy through the apps?

## Why it would be awesome to work with us?
* Besides the above benefits and technical challenges, you'll be working with client-side developers who ask real good questions
* The CTO has great technical knowledge, leadership and management skills
* There are other colleagues who I can swear by the moon and the stars in the sky that they are professional and super good at what they do

## Contact
https://sephora-digital.workable.com/jobs/434052
eric at sephoradigital.com

**Comment by joneslee85** [comment]
Thanks for the job submission. Can you please answer questions "What are hard problems you try to solve?" and "Why people should work for you?"

**Comment by ericn37** [comment]
Is it ok now @joneslee85 ?

**Comment by ericn37** [comment]
May I know the reason why my post is closed @joneslee85 ?

I saw a "Pending for approval" tag but it's nowhere to be found on https://github.com/awesome-jobs/vietnam/projects/1?
What am I missing? :)
