### ISSUE TITLE
Giao Hang Nhanh - DevOps Engineer - HCM - FT

### ISSUE THREAD

**Issue by ng-vu** [awesome-jobs/vietnam#543]
Giao Hang Nhanh is a five-year-old delivery company with more than 3,000 employees focusing on using technologies to solve problems and optimize cost in logistics. We provide hybrid logistics solutions including GHN Express for traditional delivering and AhaMove for on-demand delivering. We believe technology can help people send and receive goods more quickly, more conveniently and more economically with better experience.

### Location

- Saigon, Vietnam

### Salary Expectation

- Negotiable

### Requirements

- Bachelor degree in Computer Science, Software Engineering or Computer Engineering.
- 2+ years of experience of System Administration and/or DevOps.
- Strong Linux administration skills.
- Experience with containerized services such as Docker, Kubernetes, etc.

### Must have

- Strong administration skills.
- Responsibility, careful, integrity.
- Communication directly and honestly.

### Responsibilities

- Automating and managing the deployment processes using Continuous Integration and Continuous Delivery techniques.
- Deliver system management tooling to the engineering teams.
- Manage servers, applications and all internal software used by the company.
- Monitor system performance and undertake needed performance tuning.
- Document the configuration of the system infrastructure.
- Able to attend to system alerts on an on-call basis.
- Be an advocate for engineering best practices internally and externally.

### Interesting Engineering Projects

- Scale up to hundreds of thousands active clients in Vietnam.
- Band-width, performance monitoring and optimizing for high-latency networks.

### We offer

- Competitive salary and participation in our equity incentive program.
- 13th-month salary and opportunity for performance bonus.
- Healthcare Insurance.
- Others: open workspace, happy hours, company trips, etc.

### Why it would be awesome to work with us

- Become core members of a new platform with the ability to scale to hundred thousands of stations, millions of users and transactions in Vietnam and SEA in next few years.
- Work with a talented team and lots of challenges in logistics solutions.

### Contact

- Homepage: [career.ghn.vn](https://career.ghn.vn/software-engineer/)
- vunmq@ghn.vn (097 999 4814)

**Comment by joneslee85** [comment]
Great thanks @ng-vu for this job post. Would you be able to provide the answer for one more question "What are hard problem you are trying to solve?"

**Comment by ng-vu** [comment]
The question is not required as in [README](https://github.com/awesome-jobs/vietnam/blob/master/README.md). Anw, I'll update it.

**Comment by joneslee85** [comment]
@ng-vu recently there is change to that question, it is now

```
### Interesting Engineering Projects (REQUIRED)

* Zero-downtime deployment for long-running background jobs
* Writing a database abstraction layer to interface with different database technologies at once: PostgreSQL, MySQL, Redshift, BigQuery, Presto
```

Can you please update the job description?

**Comment by qcam** [comment]
☝️ ping @ng-vu

**Comment by joneslee85** [comment]
Friendly reminder for @vu

**Comment by rebyn** [comment]
Judging from the `Responsibilities` part this is *absolutely* an ops job. Why would one frame it under DevOps? :sigh:

**Comment by Anphamthanh** [comment]
This looks very devops to me. It is hybrid role and this one although more toward Ops, it certainly has a good portion of dev component to it. For example:

**Comment by rebyn** [comment]
That's 1 out of 7. So yeah, totally _good portion_.

**Comment by ng-vu** [comment]
Hi guys,
Thanks for your feedback. I updated the description :)
