### ISSUE TITLE
1PAC Vietnam - Frontend developer - HCM - FT

### ISSUE THREAD

**Issue by thaobee** [awesome-jobs/vietnam#544]
![logotype_black](https://cloud.githubusercontent.com/assets/16432674/26290061/f3ba3a12-3ece-11e7-8d02-883786d0285e.png)

1PAC Vietnam is a new creative production company with its headquarter in Tokyo. We do planning, consulting, build and develop web system and application. We provide these services as one stop solution by cooperating with our headquarter in Japan. We will help clients optimize their ways to communicate with end-users utilizing our ideas and creatives, solve a variety of problems and take new approaches.

## Location

* District 1, Ho Chi Minh City, Vietnam
* Our homepage: http://1pac.vn 
* Our facebook: https://www.facebook.com/1pacvietnam/

## Salary Expectation

* $500-$1200

## Requirements

* 2++ years working with HTML5/CSS3 and Javascript
* Very strong skill with vanilla Javascript and Jquery is a must
* Have knowledge of OOP Javascript programming
* Experience in CSS preprocessor SASS
* Writing well organized, clean and scalable CSS/SASS
* Experience in solving cross browser compatibility
* Experience in working with API
* Have knowledge of Task runner tool Grunt/Gulp (we prefer Grunt)
* Have knowledge of Git and Github is a plus (we mainly work with Github)

### Nice to have 

* Github account with public projects
* Experienced with ES6/VueJS/Webpack/Mocha
* Ability to design web layout
* Having knowledge of server side languages (PHP, Ruby)
* Having knowledge of web security

### Your job 
* Building UI and web layout
* Designing and developing single web application (SPA)
* Researching new technology, sharing your knowledge and apply it to real product
* Delivering high quality product that run cross browser

### Why it would be awesome to work with us
* Personal Macbook Pro provided
* You can work and learn directly from senior Japanese engineer in head office
* We use the one of the coolest application: Github, slack
* Review salary 2 times/year
* Business trip in Japan 
* Company trip 1-2 times/year
* Dinner and lunch party every month
* Extra activities (watch movie, picnic…)
* Others benefits such as holidays and insurance benefits follow Vietnamese law.

### Interesting Engineering Projects 

* Attendance management web/ application using Ruby and ReactNative
* A Slack BOT to give appreciation and say thank you for other team member 

### Contact
* Person in charge: Ms.Thao
* Email: redstar.thao@1pac.vn
* Phone: 090-2816-440

**Comment by thaobee** [comment]
@joneslee85, could you please check the job title now. Besides that I don't see anything wrong with my job post. Thank you!

**Comment by qcam** [comment]
@thaobee thanks for posting.

We added a new required section called "Interesting Engineering Projects", could you please add it? https://github.com/awesome-jobs/vietnam#job-description-format

> Have knowledge of Git and Github.

Nitpick though, do you really need Github "knowledge" as a requirement?

**Comment by thaobee** [comment]
@qcam thank you for your feedback. I've added "Interesting Engineering Projects" as you required. For  Github "knowledge", it will be a plus, not requirement. Please check :)
