### ISSUE TITLE
TOMOSIA - Ruby on Rails developers - Hà Nội - Fulltime

### ISSUE THREAD

**Issue by anhlt-ai** [awesome-jobs/vietnam#548]
Công ty TOMOSIA đang cần tuyển 02 bạn là dev Ruby on Rails tại Hà Nội.

## Đãi ngộ
$700 ~ $1200/month

### Bắt buộc
- Ruby
- Ruby on Rails framework
- 2+ năm kinh nghiệm web developer
- Trung thực, dám thất bại, không ngại khó khăn

### Mong muốn
- Có kiến thức về frontend, AWS
- Kĩ năng quản lý thời gian và tổ chức công việc hiệu quả
- Communication tốt
- Sẵn sàng học hỏi và đam mê những điều mới mẻ

## Tại sao lại là TOMOSIA
Tên #TOMOSIA là cách chơi chữ tiếng Nhật, có nghĩa là win-win, be happy.

Ở TOMOSIA, chúng tôi đề cao văn hoá công ty và các giá trị gia đình, bạn bè. Sẽ chẳng đi đến đâu với 1 tư duy thiển cận tập trung vào lợi nhuận và những con số.

Ở TOMOSIA, bạn sẽ phải học hỏi không ngừng về các công nghệ tiên phong. Đối tác của TOMOSIA chủ yếu là các startup đến từ Nhật Bản, về fintech, IoT, AI, … Họ là những người rất năng động, sáng tạo, và TOMOSIA cũng phải như thế.

Ở TOMOSIA, bạn cứ làm những gì mình thích, nhưng bạn phải là người giỏi nhất về lĩnh vực đó.

## Contact
Homepage: [Viet on Rails](vietonrails.com)
Email: anh.luu@tomosia.com
Phone: 0934-898-137

**Comment by qcam** [comment]
@r0ckkhuya thanks for posting, could you please rewrite your post in English?

Also please make sure your post comply with our [format](https://github.com/awesome-jobs/vietnam#job-description-format).
