### ISSUE TITLE
SCUTI - JUNIOR WEB PHP DEVELOPERS

### ISSUE THREAD

**Issue by JaneDang** [awesome-jobs/vietnam#553]
## Location
* Hà Nội , Vietnam
* Full time

## Salary Expectation
* Up to $800/month

## Requirements
* Programming of products of our own and our business partners
* Build network and servers required these products above
* Source code review
* Ensure software quality
* Educate the other members

### Must Have
* Strong mind to keep learning new technology
* Experience of Laravel framework
* Experience of PHPUnit
* Experience of Scrum process
* Experience of source code review
* Experience to build & maintain mid-size of Linux servers
* Experience to develop or operate non-stop system

### Ideally
* Communication skill in English

### What We Can Offer
You have a chance to contribute to the society of not only Vietnam but also SEA
13th &14th monthly salary
Team building 
You can enjoy free working style
You can be a core member of startup company
You can get a change of quick promotion in compared with big companies
Other benefits 

### Contact
Homepage: scuti.asia
Email: jane89@scuti.asia
Tel: 04 6292 7275

**Comment by joneslee85** [comment]
@JaneDang please consult our [guideline](https://github.com/awesome-jobs/vietnam/blob/master/README.md) and make amendment accordingly. This job post is lacking details we ask.

**Comment by joneslee85** [comment]
@JaneDang please do not use all uppercase for title and please check our guideline on what we ask for the body content

**Comment by joneslee85** [comment]
@JaneDang please double-check our guideline and make sure you have all required section in our suggested template
