### ISSUE TITLE
RAKUNA.co - Ruby/Rails Developer - Hanoi - FT

### ISSUE THREAD

**Issue by minhtldm** [awesome-jobs/vietnam#556]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $500+/month (heavily depends on your skills)
* Relocation assistance may be available

## Requirements
* Outstanding in communication & collaboration (shit happens all the time. it is ok but we rather want active communication)
* Write clean, maintainable and efficient code
* Have strong knowledge of TDD, Rspec, PostgresSQL, Redis, MVC...etc
* Have a strong sense of design and experience with project management (it is in our DNA)
* Actively participate in the developer and technology community (who doesn't learn from others)
* Ability to bring practical experience and innovative ideas to successfully deliver Web and/or mobile solutions to the public domain (simply the Doer)
* Experience with Ruby/Rails and bonus points for mobile experience and designs.
![image](https://cloud.githubusercontent.com/assets/28090038/26386170/19b79092-406f-11e7-91cf-d48f1683f816.png)

### Must Have

* Love startup environment, want to challenge yourself, and aim for a leadership prospect

### Responsibilities

* Responsible for product development.
* Manage product pipelines including planning, development, and strategies.
* Collaborate with cross functional teams - Marketing, Mobile & Quality to achieve business goals.
* Spearhead the technical hiring and training.

### Contact
* Please provide your resume/CV, as well as any additional items (such as a portfolio, GitHub username, or links to projects you’ve completed) that appropriately describe your accomplishments, skills and responsibilities.
* For more information, contact: trong@rakuna.co
* For more information about Rakuna, check out our website

### About Us
Rakuna (www.rakuna.co) is HR Tech company based in the all-year sunny Silicon Valley, US. We recently expand and want to add few technical gems to our Vietnam team. Want to know more. Happy to chat.

**Comment by joneslee85** [comment]
Closed the ticket for approval. Once approved, it would be re-opened

**Comment by qcam** [comment]
@minhtldm thanks for posting. Could you please update your post to follow [our format](https://github.com/awesome-jobs/vietnam#job-description-format)? Some required sections are  missing.
