### ISSUE TITLE
Dinosys - Front-end Developer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#558]
## Location
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.
* 204 Pasteur, Ward 6, Distrist 3

## Salary Expectation

* Competive
## Requirements
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies
* Strong JavaScript and AngularJS skills. Experience with Angular 2 or TypeScript is a plus
* Experience building responsive web apps
* Strong analytical and problem solving abilities
* Strong communication and client facing skills

## Skills
* Strong JavaScript and AngularJS skills

### Must Have
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies

### Ideally
* Experience building responsive web apps
### Responsibilities

* Front-end Mobile Web development (HTML5, CSS3, Angular 2, integration with RESTful Web API)
* Maintain existing software
* Constantly learn and keep abreast of emerging technologies
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Critique software designs and architectures
* Peer review colleagues code and identify areas for improvement
* Provide development task effort estimates
* Conduct client requirements gathering and analysis
* Review test plans
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:

* Working in dynamic invironment, young, professional and fast growing
* Laptop is provided
* 12 days annual leaves, working Monday - Friday, flexible working time
* Salary review 2 times/ year
* Free parking for your bike
* Employee Benefits: Social insurance, Health insurance.
* Unemployment insurance and Sick leave: based on current relevant Laws
* Team building monthly
* Training new technology frequently

###  Interesting Projects
* We use international standard in building system such as agile, test driven development, continuous integration and continuous deployment.
* You will be trained and apply new technologies such as Go, Elixir,.. or new frameworks: Hanami, Phoenix,... 

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
@tangoanh please revise the body of this job post:

* Invalid Markdown format for bullet point
* Missing required section

Please see our [guideline](https://github.com/awesome-jobs/vietnam/blob/master/README.md) and make amendment accordingly. Please do not create any new job until you have all existing jobs touched up. New job post would be rejected automatically.

**Comment by tangoanh** [comment]
Okay. Thank you

**Comment by tangoanh** [comment]
@joneslee85: I format as your guideline, Please help me to approve this job
Thank you

**Comment by tangoanh** [comment]
@joneslee85: Thank you for your advise. Please help me to check it again.
