### ISSUE TITLE
Dinosys - Back-end Developer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#559]
## Location
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.
* 204 Pasteur, Ward 6, Distrist 3

## Salary Expectation

* competitive

## Requirements
• Experience with Ruby on Rails or Grape API
• Experience writing tests with RSpec/MiniTest and doing Continuous Integration is a plus
• Experience working with relational database (PostgreSQL)
• Experience setting up servers (nginx etc.) and automating deployment process (Docker, Ansible, Chef etc.)
• Experience with building beautiful and efficient APIs
• Basic understanding of front-end technologies, such as JavaScript, HTML5, and CSS3
• Solid understanding of object-oriented programming
• Strong analytical and problem solving abilities
• Strong communication and client facing skills
### Responsibilities

• Design, build, and maintain efficient, reusable, and reliable Ruby code
• Integration of data storage solutions
• Help maintain code quality, organization and automatization
• Constantly learn and keep abreast of emerging technologies
• Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
• Critique software designs and architectures
• Peer review colleagues code and identifying areas for improvement
• Provide development task effort estimates
• Conduct client requirements gathering and analysis
• Review test plans
• Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us

Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:

- Working in dynamic invironment, young, professional and fast growing
- Laptop is provided
- 12 days annual leaves, working Monday - Friday, flexible working time
- Salary review 2 times/ year
- Free parking for your bike
- Employee Benefits: Social insurance, Health insurance.
- Unemployment insurance and Sick leave: based on current relevant Laws
- Team building monthly
- Training new technology frequently

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/joinus/

**Comment by joneslee85** [comment]
@tangoanh please revise the body of this job post:

Invalid Markdown format for bullet point
Missing required section

Please see our guideline and make amendment accordingly.

**Comment by tangoanh** [comment]
Okay. Thank you

**Comment by tangoanh** [comment]
@joneslee85: I format as your guideline, Please help me to approve this job
Thank you

**Comment by tangoanh** [comment]
@joneslee85: Thank you for your advise. Please help me to check it again.

**Comment by qcam** [comment]
@tangoanh your post body is still invalid, there's some malformed bullet points in it.

You can use asterisk  `*` for bullet points in markdown.

```
* I eat rice.
* I don't eat noodles.
```
