### ISSUE TITLE
LARION - Senior Software Engineer (.NET, JS, C#) - Saigon - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#563]
## Location
* Hall 5, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCMC

## Salary Expectation
* $1200 ~ $1600

## Requirements
* At least 4 years working experience as software developer
* Working experience in developing .NET, C#, Java Script, MS Excel
* Working experience in object oriented programming
* Good knowledge of SQL / SQL Server (relational database)
* Quickly absorb and understand new technologies
* Highly responsible for the assigned tasks
* Good decision making and time management skills
* Team-oriented.
* Be proactive, creative and positive attitude at work
* Willing to adapt and to take advantage of new technologies and market shifts

## Skills
* .NET, C#, Java Script, MS Excel

### Must Have
* Good communication skill in Japanese (N3~N1)
* Japanese company experience is preferable
### Ideally
* Working experience in developing Delphi, Lua language
* Knowledge of software development process, especially software analysis and design processes, implementation process
* Working experience with front-end: Jquery, AngularJS1, KnowoutJS, TypeScript, Bootstrap, AutoMapper
* Working experience with design pattern: MVC, Web API, Repository Pattern, Design Pattern (Unity), Inversion of control (IOC) and Dependency injection (DI)
* Understanding of WWW principles, technologies and protocols Dynamic HTMK, JavaScript

### Responsibilities
* Directly working with Japanese-speaking stakeholders to gather business and system requirement. Become the hub of development and communication in the team
* Analyze client requirements to develop functional and technical software requirements
* Produce a solid and detailed technical design documents
* Write clean, modular, robust code to implement the desired requirements
* Setup environment and release applications. Write guideline documents as required
* Conduct code re-factoring, optimization. Maintain efficient, reusable, and reliable source code
* Contribute ideas for making the application better and easier to use
* Contribute in all phases of the development life-cycle. Ensure on time, on budget, and the quality of the product
* Supervise and support other junior developers in fulfilling tasks as well as improving their skills
* Support PM to manage the progress, quality and ensure the demand of the company and customer's requirement
* Perform other technical tasks assigned by the PM

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Interesting Engineering Projects 
* We provide full-stack services of Ruby on Rails Application Development. Generally, our Ruby on Rails Application Development Services consist of Web App Development and Web App Maintenance.
* Saving working time by 25%, LARION helped Customer save cash, headcount and customer satisfaction with the SurroundCore Solution

### Contact
Email: recruitment@elarion.com

**Comment by joneslee85** [comment]
Sorry but we do not accept this job post because:

* Too many stacks for a role, maybe what you are looking for is an architect role
* What is `and protocols Dynamic HTMK, JavaScript`?
* What is `Design Pattern (Unity)`?

And for such all-rounded genius that fit this role, your salary is no where near a fair rate.
