### ISSUE TITLE
Wefit -Software Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by duyetpt** [awesome-jobs/vietnam#565]
## Location

* HaNoi, Vietnam

## Salary Expectation

* Negotiate

## Requirements

* Have passion in developing products for end user, willing to learn new technology 
* Have knowledge about HTML5/CSS3/Javascript, SASS/SCSS
* Have knowledge about Jquery and one of frameworks: ReactJS, AngularJS, VueJS
* Familiar with Git
* Have basic Photoshop skill: crop, resize, measure,…

## Skills
* Javascript, html, css, sass/scss
* Photoshop

### Must Have
* Have passion in developing products for end user, willing to learn new technology

* Javascript(ES5, ES6), html, css

### Ideally

* ReactJS, AngularJS, VueJS

### Responsibilities

* Build and develop components of WeFit webapp
* Teamwork with engineering team and UI/UX team 
* Attend meetings and contribute ideas for the product

### Why it would be awesome to work with us (REQUIRED)

* Being train both in programming and product developing with young dynamic team 
* Transparent evaluation process, fast growing salary (15%/year in average)
* Have chance to join ESOP (employee stock ownership plan) every 6 months
    
### Interesting Engineering Projects

* Build flexible components for wefit webapp

### Contact
Homepage: wefit.vn
Wefit: anhhth@wefit.vn (+84 047 304 1155)

**Comment by qcam** [comment]
@duyetpt Thanks for posting.

As clearly stated in repo README, job post must be written in English, and must strictly follow [this format](https://github.com/awesome-jobs/vietnam#job-description-format).

Please help to adjust accordingly. Kindly note that this job will be marked as invalid if there's no adjustment made within two days.

**Comment by duyetpt** [comment]
@qcam Thanks for your mention. I edited my post, please help to public it.
