### ISSUE TITLE
Wefit - Mobile Apps Engineer - Hanoi - FT

### ISSUE THREAD

**Issue by duyetpt** [awesome-jobs/vietnam#566]
## Location

* HaNoi, Vietnam

## Salary Expectation

* Negotiate

## Requirements

* Have passion in developing products for end user, willing to learn new technology 
* Have basic knowledge about ReactNative or at least a mobile developing language (Objective C, Java, etc)
* Having a real product on AppStore or Google Play Store is an advantage 
* Familiar with Git
* Have basic Photoshop skill: crop, resize, measure,…

## Skills
* Javascript(ES5, ES6)
* Photoshop

### Must Have
* Have passion in developing products for end user, willing to learn new technology

* Javascript(ES5, ES6)

### Ideally

* ReactNative, ios, android

### Responsibilities

* Build and develop WeFit app on iOS and Android 
* Develop reusable and flexible components 
* Teamwork with engineering team and UI/UX team 
* Attend meetings and contribute ideas for the product

### Why it would be awesome to work with us (REQUIRED)

* Being train both in programming and product developing with young dynamic team 
* Transparent evaluation process, fast growing salary (15%/year in average)
* Have chance to join ESOP (employee stock ownership plan) every 6 months
    
### Interesting Engineering Projects

* Build flexible components using react native for android, ios platform

### Contact
Homepage: wefit.vn
Wefit: anhhth@wefit.vn (+84 047 304 1155)

**Comment by qcam** [comment]
@duyetpt Thanks for posting.

As clearly stated in repo README, job post must be written in English, and must strictly follow [this format](https://github.com/awesome-jobs/vietnam#job-description-format).

Please help to adjust accordingly. Kindly note that this job will be marked as invalid if there's no adjustment made within two days.

**Comment by duyetpt** [comment]
@qcam Thanks for your mention. I edited my post, please help to public it.
