### ISSUE TITLE
Spark Start - Engineer - Remote - Full stack Engineering (RoR, Nodejs, Elixir)

### ISSUE THREAD

**Issue by KevinColemanInc** [awesome-jobs/vietnam#571]
## Location

* Remote

## Salary Expectation

* $1000-2000/month USD

## Requirements
* Full stack:
  * Backend: NodeJS, Elixir/Phoenix, or RoR
  * Frontend: ReactJS, VueJS, or similar frameworks
* PostgreSQL
* 2+ years Software Engineering experience

## Skills
* Fluent English

### Must Have
* Source code
* Example projects
* Pass a technical interview

### Ideally
* Better in the front end than the backend
* Experience with Bitcoin
* Statistics
* Dev Ops

### Responsibilities

Build the project from the ground up.

### You’ll be responsible for

* Building a new blockchain gambling platform

### You can bring

* A good eye for design

### Why it would be awesome to work with us
You will be working with an experience senior software engineer from SF that will also help you develop your career.

### What are hard problems that your company is trying to solve?
Security is a very high priority.

### Contact
DM me on Slack (@kevin)

**Comment by qcam** [comment]
@KevinColemanInc thanks for posting.

For `CT` did you mean `Contract`? If so please change it to `C`.

Can you please be more specific about the job description?

- I think your requirement is rather vague and fluffy. Full-stack developers who expertise in RoR, Elixir, NodeJS with great front-end skills and ideally experienced in DevOps are extremely hard to find; the range of $1000-$2000 might not find you that.
- What is the detailed definition of `EXPERIENCED`?
- Why "working with an experience senior software engineer from SF" will be awesome and help the candidates develop their career?
- I agree Security is a hard problem to solve, but it is a broad industry of different fields that require different highly-specialized skills. Which field of the industry are your business trying to tackle? Another equivalent question is "Do you have any interesting engineering projects in your company to share?"

**Comment by KevinColemanInc** [comment]
I updated the title.

I need a web app built and I need someone with experience in one of those languages to build.  I said "or", not "and".

Dev Ops is not a requirement, but a nice to have.

I added what I mean by experienced

I guess that isn't clear.  But for me personally, it is a huge perk to work with smart experienced people, because they will help train me to grow my career.

**Comment by joneslee85** [comment]
@KevinColemanInc thanks for the submission. I find your job description is very vague. It does not give me a clear picture what you want to achieve. Furthermore, the salary is unrealistic for what you want. And if there is one person that tick all those boxes, they must have already known their skills are worth.

**Comment by joneslee85** [comment]
@KevinColemanInc I am sorry but we could not approve this job. I don't think there are any candidates here would fit your requirements, I highly suggest you seek other outsource firms or freelancer on sites like freelancer.com

**Comment by rebyn** [comment]
@joneslee85 I'd have to disagree. The number of blockchain startups being based in Saigon has reached a healthy number I believe there's also a healthy set of engineers who can be geared to this position. Also, I'd also leave the judgement re: compensation to the engineers themselves :).

**Comment by KevinColemanInc** [comment]
This [job posting](https://github.com/awesome-jobs/vietnam/issues/531) accepted 26 days ago is 20% lower than what I am offering and you are saying my posting is not matching market rate? 

Not only are they paying less than I will, they also have no job description.

What is up with this double standard?

**Comment by KevinColemanInc** [comment]
@rebyn I do not need any blockchain developers.  This project will be using a 3rd party service for processing blockchain events and will integrate with them via web hooks.

**Comment by KevinColemanInc** [comment]
@joneslee85 [This posting](https://github.com/awesome-jobs/vietnam/issues/555) does not even mention comp.

**Comment by KevinColemanInc** [comment]
@joneslee85 [This posting](https://github.com/awesome-jobs/vietnam/issues/540) only offer $1,500/mo max for a rails developer.

[This posting)(https://github.com/awesome-jobs/vietnam/issues/510) offers $900 / mo for a rails developer.

[This posting](https://github.com/awesome-jobs/vietnam/issues/520) offers $1000 / mo for a rails developer.

Looking at these numbers, I am almost double market rate for RoR devs.
