### ISSUE TITLE
Oddle - Lead Java Engineer - Saigon - FT

### ISSUE THREAD

**Issue by chelseanguyen** [awesome-jobs/vietnam#572]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable

## Requirements
* 5+ years experience in relevant position
* Experience with Relational Databases and SQL
* Experience with API and Framework Design and third-party API integration
* Experience with team management
* Experience as a full-stack engineer
* Strong English command and communication skills
* Degree in Computer Science, Software Engineering or a related subject is preferred

### Must Have

* 5 years or more experience in Java with Spring Framework and Hibernate ORM

### Responsibilities

* Design and build scalable REST APIs for Oddle platform and other microservices
* Collaborate with frontend team to decide how an API method should work
* Work with Product team to build innovative, robust, and easy-to-use features for our users
* Improve and optimise performance of infrastructure and database
* Write clean, human-readable code with unit tests
* Triage bugs and troubleshoot production issues
* Improve code quality and increase unit and end-to-end test coverage
* Mentor junior engineers when necessary

### Why it would be awesome to work with us

* Opportunity to work on our product development and major projects
* Working with a brilliant and supportive technical and product teams, where you can learn and challenge each other to make a meaningful impact
* Hack your growth by forcing yourself out of comfort zone and learning new skills and technologies
* Competitive salary and benefits, with 2 performance bonus a year
* Monthly happy hour, annual company trip
* Join us to find out more for yourself!

### What are hard problems that your company is trying to solve?
Oddle is a Singapore-based startup that provides a smart online ordering system which enables F&B business owners to manage their own take-away orders and grow their business. Since our platform launched in 2014, Oddle is heating up the food delivery space, with over USD16 million worth of orders transacted! 

Unlike marketplaces, Oddle is a cloud-based, e-commerce and orders management solution which caters specifically to the operations of F&B businesses. Our solution is a unified, all-in-one online ordering system  which funnels all orders to designated restaurants.

### Contact
Homepage: https://oddle.me/

If you are someone who appreciates writing elegant APIs, solving complex problems, or building scalable infrastructure, we want to speak to you! Drop in your resume now to chelsea@oddle.me!

**Comment by qcam** [comment]
@chelseanguyen thanks for posting.

The post looks good to me, just one thing could you remove the quote in Must have section?

**Comment by chelseanguyen** [comment]
@qcam Thanks for the feedback. The quote is removed!
