### ISSUE TITLE
Magic8Labs - Python Loving Junior Developer Startup - HCM - F

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#576]
<div class="edit-comment-hide">
    <table class="d-block">
      <tbody class="d-block">
        <tr class="d-block">
          <td height="1135" class="d-block comment-body markdown-body markdown-format js-comment-body">
              <h2><img src="https://s3-us-west-2.amazonaws.com/magic8labsmediaassests/Main+Logosm.jpg" width="800" height="159" alt=""/></h2>
              <h2>&nbsp;</h2>
              <h2>Location</h2>
              <p>572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City</p>
              <p>&nbsp;</p>
              <h2>A Startup with an opportunity   for profit sharing....Say hello to Magic 8 Labs</h2>
<p>All great achievements start with working to solve  a problem. We are doing just that! We are in the business   of building software platforms for people willing to pay us. We aren't an outsourcing company! </p>
<p>If you are a hard working person, who wants to be challenged   to learn and grow. If you want to be apart of something from the ground up well here is your chance. Join us! </p>
<p>If your scared of risks, want a job in a nice big office and a big fat paycheck with free snacks we are not the company for you. Not yet anyways! Hey Steve Jobs started in his garage! </p>
<p>&nbsp;</p>
<h2>What are we cooking at Magic 8 Labs?</h2>
<p>A USA backed (me the owner) Startup up with a vision, a direction and persistence with a SaaS product in Alpha Release. Currently we are cooking with JavaScript framework (AngularJS, NodeJS, Meteor) with a part in Python. </p>
<ul>
  <li>Seeking a back-end developer interested in just python (Maybe Go using Big Data, Artificial Intelligence projects coming soon.</li>
  <li>A developer who knows  Python enough to make things happen but wants to learn and grow with us.</li>
  </ul>
<p>Recent graduates and experienced developers looking for good home apply. You will be employee lucky next partner/developer. </p>
<p>&nbsp;</p>
<h2>Requirements (in order of how important they are to us)</h2>
<ul>
<li># 1- Full of energy and love Python and want to dig deeper </li>
<li># 2- You want to work for a Startup with all the good and bad that it comes with</li>
<li># 3- Team Player, open minded </li>
<li># 4- We could careless about how talented you. If your heart isn't in the right place this job isn't for you!</li>
<li># 5- You are not married and have time to devote to your career. (sorry married guys/gals we need to work overtime)</li>
</ul>
<h2>Reasons to come to work everyday! AKA Benefits</h2>
<ul>
<li>No bosses! We are our own boss - no emails we talk here.</li>
<li>Friendly, flexible, and fun working environment.</li>
<li>Various team building activities.</li>
<li> Salary review every year or on excellent performance.</li>
<li>On-the-job training by our team leads.</li>
<li>Mac computer is provided.</li>
<li>Free  lunch everyday.</li>
<li>13th Salary.</li>
<li>Generous time off.</li>
</ul>
<h2>Salary Expectation</h2>
<ul>
<li>Up to $700 </li>
</ul>
<h2>&nbsp;</h2>
<h3>Contact</h3>
<p>Quynh Kim quynh.kimthinhu@gmail.com</p>
<p>https://www.facebook.com/kim.thinhuquynh </p>
<p> Nick Mavridis mavridisn@gmail.com </p>
<p>https://www.facebook.com/nick.mavridis.1</p>
<p><br>
</p></td>
        </tr>
      </tbody>
    </table>

**Comment by euronck** [comment]
Cam.. wasn't sure what was wrong with my Python post on Github

**Comment by qcam** [comment]
@euronck thanks for posting, personally I like your creative headings.

Could you please rewrite job post in Markdown instead of HTML? Also [some required sections are missing](https://github.com/awesome-jobs/vietnam#job-description-format).
