### ISSUE TITLE
Freelancer - Javascript developer

### ISSUE THREAD

**Issue by hoanvo** [awesome-jobs/vietnam#577]
## Location
Saigon, Vietnam
Or Remote

## Salary 
Negotiate

## Requirements
* Javascript

## You’ll be responsible for
Build a javascript module about sheet music. The description as below:
- Input is a musicxml format, also maybe another format which my team will define.
- You will parse this format and draw it into sheet music. Besides, you will use soundfont to play that sheet music with cursor moving on it. Moreover, you also draw piano keyboard and active these keys follow the sheet music.
- If you can't read the sheet music format to code, we already train you.

## Contact
Email: vvhoan2004@gmail.com 
Skype ID: hans010909.

**Comment by huydx** [comment]
@hoanvo see our Guide to create JD at README

**Comment by hoanvo** [comment]
@huydx : Sorry you, I will reformat my post.
