### ISSUE TITLE
PianoTeam - Javascript Developer - Remote/Saigon - C

### ISSUE THREAD

**Issue by hoanvo** [awesome-jobs/vietnam#578]
## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* Negotiable

## Requirements
* 2+ years Javascript experience
* Degree in Computer Science, Software Engineering or a related subject is preferred

### Must Have

* 2+ years Javascript experience

### Ideally

* 2+ years Javascript experience

### Responsibilities

* Build a javascript module about sheet music
* Input is a musicxml format, also maybe another format which my team will define. You will parse this format and draw it into sheet music. Besides, you will use soundfont to play that sheet music with cursor moving on it. Moreover, you also draw piano keyboard and active these keys follow the sheet music.

### Interesting Engineering Projects

* The team is building musical platform for the person is learning piano
* They can listen the sheet music with the cursor moving on the sheet music, and activated piano's keyboard
 * They also can convert the sheet music to pdf, midi
   

### Why it would be awesome to work with us
* You have a chance to learn about piano music
* You can understand sheet music
* We are both musician and developer, so, you will easily to discuss with us.

### Contact
Email: vvhoan2004@gmail.com

**Comment by huydx** [comment]
@hoanvo  we add some requirements for JD, include this section
```
### Interesting Engineering Projects (REQUIRED)
```
Could you please take a look?
