### ISSUE TITLE
honestbee - Senior / Lead Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by binhngoc17** [awesome-jobs/vietnam#579]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,800 - 2,700

## Requirements
* Ruby or Golang
* PostgreSQL
* Experience with building scalable system
* Experience with micro-service architecture
* 5+ years Software Engineering experience

## About honestbee

honestbee is a more than just a grocery delivery app. We are Asia's leading online concierge and delivery service for all your lifestyle needs. We take care of those time-consuming daily chores and create time for you to spend doing what you love and care about. With our technical expertise, data-fuelled operations and our network of partners, people experience how life’s just easier with honestbee. 

### OUR VISION
The world’s most convenient services marketplace.

### OUR MISSION
Provide positive social and financial impact on the lives and businesses that we touch

Three months at honestbee are like a year at any other company. Things move fast. You learn more, you accomplish more. Our teams come from a diverse range of cultures, giving us a competitive edge when working across SE Asia. We are looking for people who are excited about empowering communities as much as we are.

Solving the riddles of e-Commerce and logistics. We work on practical solutions for the real world and we are obsessed about building a platform that awes and delights our customers - that’s our commitment to them!  

Dare, try, do - we encourage our people to innovate from within and we will never ever stop experimenting and taking risks. If all that makes you buzz in excitement, come join our ambitious, strong-minded and determined team that takes both work and play seriously.

## Skills

* Prior experience working on developing payment gateways highly beneficial
* Experience with mentoring other team members
* Familiarity with TDD and BDD concepts and how to use them to write code that is well tested
* Experience working on the web stack and willing to get into the Rails stack. 
* You enjoy working in a start-up and open environment
* You take pride and ownership in your work
* You are self-motivated and can work well under pressure
* You have a good sense of humor and like fun

### Responsibilities

* Helping to develop better architecture and establish ways for improving payment solutions
* Mentor and nurture more junior members of the team
* Work closely with product and design to build and improve features
* Write and improve upon existing code with attention paid to performance
* Plan and document technical specifications for features or system design
* Contribute towards improving engineering culture and approach

### Interesting Engineering Projects

The team is building payment solution suite for the e-commerce solution:
- How to architect a money storage solution with transactional integrity? (race condition handling & idempotency support)
- How to build automatic integration testing for multiple services architecture based on Docker?
- How to monitor fraudulent activity for a wallet? (by transaction activities, user information, etc)

### Contact
Homepage: honestbee.com
Trollman: ngoc.tran@honestbee.com (+84937362841)

**Comment by huydx** [comment]
@binhngoc17 we add some requirements for JD, include this section
```
### Interesting Engineering Projects (REQUIRED)
```
Could you please take a look?
