### ISSUE TITLE
Dinosys - Java Developer - HCM - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#581]
## Location
Founded by a group of seasoned IT professionals, Dinosys is an innovator in the business of designing, integrating and managing world-class technology products and solutions. Our founders realized the power of digitalization in providing solutions to businesses with pressing challenges and exciting opportunities in today’s increasingly interconnected world. Specialized in system integration, software development and outsourcing, Dinosys is striving to become a leading ICT company in Vietnam and Southeast Asia. Combining unrivalled experience across many industries and business functions, and extensive relationship with the world’s biggest technology companies, Dinosys partners with clients to help develop capabilities, drive performance improvements and achieve enduring successes.

204 Pasteur, Ward 6, Distrist 3

## Salary Expectation
* $1000 - $1500/month 

## Requirements
* Javascript
* Spring MVC
* Spring Boot
* Thymeleaf
* Maven
* Apache/Tomcat
* 3+ years Java Spring Back-end experience

### Must Have

* Working knowledge of Java Programming Language
* Working knowledge of JDBC, Hibernate, Spring MVC, Thymeleaf, Spring Boot
* Working knowledge of Javascript, JQuery

### Ideally

* Experience with Maven or Gradle
* Experience with CSS, HTML5, web-/application-server (Apache/Tomcat), data modelling and SQL queries
* Very good communication skills
* The ability to work independently, responsibly, accurately and reliably
* Good English and computer skills

### You’ll be responsible for

* Design and implement web-based applications
* Build the core frameworks for a high-scale web-services/microservices and RESTful APIs
* Maintain and develop the existing products
* Further development of software components
* Troubleshoot complex software systems under dynamic boundary constraints
* Provide document of software development
* Deploy and test software application

### Why it would be awesome to work with us
* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:

* Working in dynamic invironment, young, professional and fast growing

* Laptop is provided

* 12 days annual leaves, working Monday - Friday

* Salary review 2 times/ year

* Free parking for your bike

* Employee Benefits: Social insurance, Health insurance.

* Unemployment insurance and Sick leave: based on current relevant Laws

* Team building monthly

* Training new technology frequently
### Interesting Projects
* We use international standard in building system such as agile, test driven development, continuous integration and continuous deployment.
* Project that you will build: 2 level tokenization for banking, Infrastructure management for public architecture of Singapore

### Contact
Email: oanh.tang@dinosys.vn
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195
Website: https://dinosys.vn/

**Comment by qcam** [comment]
@tangoanh thanks for posting, in requirement section, by `Javascript` did you mean `Java`?

**Comment by tangoanh** [comment]
Hi @qcam: I mean Java and javascript (full stack)
