### ISSUE TITLE
Wonolo - Senior / Lead Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by chacharoti** [awesome-jobs/vietnam#582]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500 -> $2500

## Requirements

* Ruby
* PostgreSQL
* Experience with agile software development, preferably with Kanban/justin-time development
* Experience with building scalable system
* 4+ years Software Engineering experience

## Skills

* Drink beer
* Drink a lot
* Drink al night 

### You’ll be responsible for

* “Can do” attitude, self-starter, able to deliver results independently without close management (your boss will be 15 hours and 7,800 miles away)
* Ability to lead and inspire a team of engineers to write great code and hold them accountable to deliver results - you will be an important and influential voice in building the team culture

### Why it would be awesome to work with us

* Get bonus 10% your salary if company got target each month
* Upgrading salary 1 time/year or when you have excellence achievement
* Working 5 days/week , from Monday to Friday ,work at home on Friday
* Great chance to develop your skills and competences via coaching and mentoring program
“Share to learn and learn to share” philosophy
* Opportunities for promotions and career development in a dynamic environment
* Support sport cost for team building activities (badminton, football, tennis, swimming)
* Social insurance follow Vietnam’s law
* Quarterly company trip
* 13th month salary
* Opportunities to travel to US
* Social insurance : $250/year
* Attend English classes at the company
* Free snacks & beverages

### Contact
Homepage: https://www.wonolo.com/
Email: trunghdm@gmail.com
Phone: 090 989 7531

**Comment by qcam** [comment]
hi @chacharoti, thanks for posting. Could you please update your post to be aligned with [our format here](https://github.com/awesome-jobs/vietnam#job-description-format)? All the REQUIRED sections must be filled.
