### ISSUE TITLE
FiteGlobal - Senior/Lead Full stack Developer - Saigon - FT

### ISSUE THREAD

**Issue by truongvan** [awesome-jobs/vietnam#583]
## Location

* Saigon, Vietnam

## Salary Expectation

* From $1400 to $1500 per month

## Requirements

* Python, Ruby, SQL, noSQL, 
* Experience with micro-service architecture
* 3+ years Full stack Developer experience
* Solid understanding of Data Modeling
* Understanding of agile software development
* Experience with team management

### Must Have

* Understanding of Automated testing
* Experience working with RESTful API type web services
* Experience in developing applications leveraging XML/JSON

### Ideally

* Well-versed and active user of GitHub
* Prefer experience working in an agile development environment.
* Prefer experience developing applications on the Cloud, such as EC2 using relevant tools.
* Prefer knowledge of cryptocurrency, blockchain, smart contract.

### Responsibilities

* Maintain code quality, organization and automation
* Design, build, and maintain efficient, reusable, and reliable Javascript code
* Full stack Web development 
* Provide development task effort estimates
* Triage bugs and troubleshoot production issues
* Collaborate with frontend team to decide how an API method should work

### Why it would be awesome to work with us
* Money money money
* Pioneering new digital industry.
* Brotherhood working environment.

### Interesting Engineering Projects
* Get brand new issues.
* Massive data though the server, deal with it.

### Contact
Homepage: https://itviec.com/it-jobs/sr-front-end-engineer-javascript-fiteglobal-2624
Trollman: truongvan at fiteglobal dot com

**Comment by truongvan** [comment]
Bài của em có gì sai mà bị closed ạ? Anh có thể nói để em có thể sửa không?

**Comment by huydx** [comment]
@truongvan chỉ là ban quản trị đang tiến hành review thôi bạn nhé

**Comment by qcam** [comment]
@truongvan thanks for posting. Could you please update your post to be aligned with [our format here](https://github.com/awesome-jobs/vietnam#job-description-format)? All the REQUIRED sections must be filled.

**Comment by truongvan** [comment]
I have updated the post.
Thank you for your patient.
