### ISSUE TITLE
Zalora - Software Engineer - Saigon - FT

### ISSUE THREAD

**Issue by thanhnguyennguyen** [awesome-jobs/vietnam#584]
## Location

* Saigon, Vietnam

## Salary Expectation

* From $1000 to $2000 gross per month

## Requirements
ZALORA Engineering has a penchant for solving complex and interesting problems to serve millions of users across South East Asia. We are looking for fearless software engineers in Singapore and Vietnam offices with expertise in any of these technologies: Objective-C, Swift, Android, Java, PHP, NodeJS, Golang, Python, Ruby, MySQL, Solr/ElasticSearch, Redis/Memcached, Backbone.js.
- Software Engineer, Golang
- Software Engineer, Java
- Software Engineer, iOS
- Backend and Frontend Software Engineer (PHP)

### Must Have
* Data structures & algorithms
* Object oriented design
* Design patterns
* Building scalable systems
* BS degree in Computer Science or related technical discipline

### Ideally
* Having knowledge with any of the following would be nice: Golang, Java, Python, Ruby
* 2+ years of experience with high-traffic distributed systems and client-server architectures

### Responsibilities

As a Software Engineer, you will build high performance, scalable and testable components for our shop platform with PHP, MySQL and other technologies. You will be working in a diverse, international setting with teammates who are experts in various topics. We often conduct workshops to improve our individual skill sets, and to improve our workflow as a team. The role is based in our Vietnam office.

## Why it would be awesome to work with us

* Growth
We are lifelong learners. We innovate to achieve beyond expectation. We are eager to amaze our colleagues and to inspire each other. 
We are thirsty to learn new technologies. We actively share knowledge and help each other improve.An amazing place where the top Engineering Values are practising by our team members:
* Integrity
We act with personal integrity. This is the fundamental block with which our chain of trust is built. Without trust, we do not have a team.
We also maintain professional integrity. We do not cut corners. We do what is right, we solve problems at their root.
* Simplicity
We opt for the simplest possible solution without compromising professional integrity. When faced with two alternative solutions which are theoretically equivalent, we choose the simpler one.
* Alignment
Our rules and processes enable each other, not disable each other. These help us move faster both individually and as a team.
Alignment evolves. It constantly changes to meet our needs and challenges. If a rule is no longer effective, we revise it.
Alignment is enabled by communication. We communicate our ideas as directly as possible.
* Autonomy
We are given the full freedom to complete the work assigned to us. This freedom comes with responsibility and accountability.
* Data-driven
We do not make assumptions. We use data to understand our problems and to make decisions.
We fail fast when our plan does not work out. This way we are able to innovate fast and to create value for our customers.

* Also:
Mac Pro is provided
Free Gym membership
Free English class in the office (twice a week)
24/7 Social & medical insurance
15 days annual leave
Tons of cool toys (PS4, Foosball etc.)
Opportunity to gain exposure working in 6 Southeast Asian market
A comfortable and productive working environment, complete with fun distractions such as ping pong, foosball, PS4 and more.
### Contact

NguyenNguyen: thanhnguyen.nguyen@zalora.com (0868649697)

Thanks!

**Comment by qcam** [comment]
hi @thanhnguyennguyen, thanks for posting. Could you please update your post to be aligned with [our format here](https://github.com/awesome-jobs/vietnam#job-description-format)? All the REQUIRED sections must be filled.

**Comment by thanhnguyennguyen** [comment]
Hi @qcam , Can you tell me what is my mistake? Thank you very much!

**Comment by joneslee85** [comment]
@thanhnguyennguyen in our guideline, we require submission must answer to section that are suffixed with `REQUIRED`

**Comment by thanhnguyennguyen** [comment]
Updated! 
@qcam Please help me review again

**Comment by joneslee85** [comment]
@thanhnguyennguyen I don't think you quite nail that section, it is not a section to re-iterate what you are looking for, but more about technical prowess. Sure, good app serve million customers, but why is it interesting? It is just a statement of a problem that your engineers have to overcome, but it does not state how you overcome it. Let me give you one example how one would write this section:

```
We have a project X to solve a large scale biz, that is global marketplace with x millions requests / day spreading on multiple timezones, it is imperative that the system be able to withstand the heavy load, yet at the same time simple to maintain, we employ technology A, B, C, D and wrote our custom open source software E that helps us identify bottleneck, autoscale, etc
```
