### ISSUE TITLE
Silicon Straits - Senior System Administrator - HCMC - Fulltime

### ISSUE THREAD

**Issue by trangpham88** [awesome-jobs/vietnam#585]
## Location
*  147 Ton Dat Tien, Ho Chi Minh City, Vietnam 70000
* Fulltime
## Salary Expectation

* $600-$800/month or range

## Requirements
* At least 3 years experience in Linux system administration.
* Fluent with scripting languages (Perl, Bash, Batch, PowerShell, etc.)
*  Specialise in at least one of popular Linux distros CentOS, Ubuntu, Fedora,
Debian, FreeBSD.
*  Experience in scaling, optimizing and hardening web application infrastructure including web, files, database, load balancing servers.
*  Solid understanding of computer network.
*  Experience in working with popular cloud services (AWS, DO, GCP…)
*  Strong understanding of hardware performance, memory and I/O.
*  Experience in configuration management tools (Ansible, Chef, Salt…)
*  Ability to manage multiple tasks with shifting priorities.
*  Fast troubleshooting and resolution skills.

## Skills
*  Ability to clearly document system architecture.
*  Understand and experience in following Infrastructure as Code
*  Related hobby projects in sys-admin or hardware field.

### Must Have

* Specialise in at least one of popular Linux distros CentOS, Ubuntu, Fedora,
Debian, FreeBSD.
*  Experience in scaling, optimizing and hardening web application infrastructure including web, files, database, load balancing servers.
*  Solid understanding of computer network
 
### Ideally
* Ability to manage multiple tasks with shifting priorities.
* Fast troubleshooting and resolution skills.
### Responsibilities
* Supporting software development projects at different stages of development (development, staging, production).
* Building up the automation playbook for deployment, testing and releasing code.
### You’ll be responsible for
* Involved in new exciting hardware projects on Raspberry Pi, BeagleBone, Arduino, OpenWRT etc.
* Exposure to multiple non-conventional stack or Linux distro.
### You can bring
* Experience in configuration management tools (Ansible, Chef, Salt...)
*  Ability to manage multiple tasks with shifting priorities.
*  Fast troubleshooting and resolution skills.
### Why it would be awesome to work with us
*  reat opportunities to improve your skills in many related fields.
*  working with other talented developers, designers and product managers.
*  flexible working time and unlimited leave days.
*  get your own Macbook.
*  take part in our exciting events (Hackathon, Drinkathon,...).

### Contact
If you think you have what it takes, send your CV to us at **hr@siliconstraits.vn** and we’ll get back to you soon.

**Comment by qcam** [comment]
@trangpham88 thanks for posting. Could you please update your post to follow [our format](https://github.com/awesome-jobs/vietnam#job-description-format)? **Interesting Engineering Projects** section must be filled.
