### ISSUE TITLE
Magic8Labs - Python Cookie Monster Developer - Startup HCM- FT

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#587]
## Location of Cookie Factory
* 572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City

## The Cookie Factory Formula with opportunity for profit sharing....Say hello to Magic 8 Labs
We comming into BETA on our SaaS amazon seller support tool (the 1st of many to come) and ready to kick some butt. We are a USA backed (me the owner) startup up with a vision, a direction and persistence. 

Currently we are cooking with JavaScript framework (AngularJS, NodeJS, Meteor)and Python. 

If you are a hard working person, who wants to be challenged to learn and grow and wants to be apart of something from the ground up well here is your chance. Join us!

If your scared of risks, want a job in a nice big office and a big fat paycheck with free snacks we are not the company for you (PS we do stock RedBull). Hey Steve Jobs started in his garage! 

### Cookie Monster Characteristics We admire (in order of how important they are to us)

* #1 Full of energy to become a Python Ninja and work on Big Data, Artifical Intellengce, Machine Learning all that good stuff.
* #2 You are a Team Player, open minded.
* #3 You can code on backend end and not afraid to make mistakes and you can laugh at yourself.
* #4 You love challenges.

* Note: We could careless about what a super duper talented coder you are. If your heart isn't in the right place this job isn't for you!

### Why come to work at the Cookie Factory?

* Product equity sharing opportunity.
* Friendly, flexible, and fun working environment.
* Salary review every year or on excellent Cookie Monster performance.
* We pay for courses you want to take.
* Mac computer is provided.
* Free lunch everyday.
* Generous time off. 

## Monthly Compensation (Not paid in Cookies)

* Up to $1200 

### Contact
Email: Nick Mavridis , mavridisn@magic8labs.com  
Facebook: https://www.facebook.com/nick.mavridis.1

**Comment by euronck** [comment]
the cookie monster strikes again :) This ones for you Cẩm :)

**Comment by qcam** [comment]
@euronck Does this duplicate https://github.com/awesome-jobs/vietnam/issues/576?

**Comment by euronck** [comment]
Yes this supersedes (replaces) 576. 

 

This was the rewrite for that one with more humor. To catch those with a lighter sprinter :)
