### ISSUE TITLE
Niteco Vietnam - Senior Java Developer - Hanoi - FT

### ISSUE THREAD

**Issue by thanhdtp** [awesome-jobs/vietnam#592]
![niteco_hiring3](https://user-images.githubusercontent.com/29473859/27214260-a7f0878c-5295-11e7-8b67-c44edb83b7db.png)

## Location

* Hanoi, Vietnam

## Salary Expectation

* Negotiable

## Job description
To champion technology roadmaps, develop best practice and a highly scalable architecture for an ultra-large-scale system (ULSS)
* Primarily focus on providing high performance, reliable, and scalable solutions, architecture consultation
* Oversee project teams’ architectural solutions (e.g. code-reviews, code-samples, training/mentoring less experienced developers, etc.)
* Write documentation for features of high complexity
* Help troubleshoot performance, scaling, availability issues and debugging production problems
* Create prototype/test applications

### Must Have

* Bachelor’s or Master’s degree in IT (or equivalent)
* English, fluent in verbal and written communication
* 6+ years of experience in software development
* At least 3 years' experience in designing solutions with multiple servers, complex problems, large-scaled distributed system and data storage, super high performance (low response time) on server & client side, highly scalable architectures.
* Strong experience in extensive and scalable search solutions for massive amount of contents on multiple database server.
* In-depth knowledge of Java. 
* Strong experience in architecture design of systems (small to large-scale)
* Excellent architectural & design thinking when building application. Proficient using Domain-Driven Design (DDD) and architecture pattern (CQRS, Event Sourcing) to build high performance and complex distributed system.
* Experience with standard-compliance authentication and authorization mechanism: oAuth2, openId connect, Identity provider.
* Experience with Redis, Memcache, and the other caching solutions.
* Experience with HTTP accelerators (Varnish, Squid …). 
* Knowledgeable in containerization and virtualization, for example: Docker, Helios, Service Discovery.
* Excellent soft skills
* Strong work ethic, research skills, self-motivation, dedication, and commitment.

### Cool to have

* Knowing Java 8, Scala and HTTP 2.0. 
* Experience in Lucence, Elastic Search or Solr indexing.

## Company benefits

* Highly competitive remuneration package: attractive monthly salary with allowances (including allowance for employees with children under 03 years old, gas and telephone), 13th month salary, and additional performance bonus for top performers, high public holiday bonuses, and birthday gift, employee service award up to $1,000 for employees with 3+ years.
* Attractive AON healthcare coverage including health and accident insurance in addition to basic insurances regulated by the Labor Code. Annual company summer vacation and team-building budget.
* Potential opportunities for onsite work for international projects abroad.
* Organized training and a support in building your career.
* English-speaking, international and professional work environment: working with expatriates from a number of countries, state of the art working space with a wonderful view over the city skyline, modern facilities include computer dual 23.5” screens running recent versions of Windows 10, MS Office 2016, and Visual Studio, work station with 16 GB Ram, 256 GB SSD.
* Western management style: professional, dynamic, open minded, creative, supportive, friendly, and encouraged for feedback.
* Company Management that regularly communicates Company’s strategy, development plan and new opportunities to employees.
* An active workplace with   many activities provided by the company and the Trade Union.
* Diversified social and charity activities often organized by NICEF, Niteco Charity Engagement Foundation, to create opportunities for our young employees to raise funds and help people with difficulties in Vietnam.
* Physical care environment where you are taken care, feeling relaxed and enjoying lots of leisure activities clubs such like badminton, ping pong, football, dancing, etc.

## For more information, you can: 

* Visit our company website: www.niteco.com
* Visit our Facebook fan page: www.facebook.com/Niteco
* Contact Thanh on:
LinkedIn: http://www.linkedin.com/in/duongthiphuongthanh; or
Skype: thanhdtp or thanh-duong-niteco

## To apply, please kindly send your updated English resume to:

* Email: thanh.duong@niteco.com
cc: hr@niteco.com

Thank you for your attention and interest!

**Comment by thanhdtp** [comment]
Dear @qcam 
Could you please let me know why the issue was not approved and closed?
Thank you!
Thanh.

**Comment by qcam** [comment]
@thanhdtp hey, this post is pending for review

**Comment by thanhdtp** [comment]
@qcam Oops... sorry, and thank you for your time reviewing. I'm looking forward to seeing it approved to get online.
Have a great day!
Thanh.

**Comment by qcam** [comment]
Hi @thanhdtp Could you please revise the post to follow [our guide here](https://github.com/awesome-jobs/vietnam#job-description-format)? All required sections are mandatory.
