### ISSUE TITLE
Rakuna/CDI - Design Intern - Hanoi - PT

### ISSUE THREAD

**Issue by minhtldm** [awesome-jobs/vietnam#595]
## Location

Hanoi, Vietnam

 

## Job Description

The designer’s responsibilties include, but not limited to:

* For Rakuna Mobile Application:

Creating design deliverables such as specifications, wireframes, prototype and mock-ups.

Providing design ideas and strategy.

Collaborating with the web development, mobile application development and quality assurance team.

* For Chinh Dai Industries (CDI) Company:

Develop creative concepts into prominent designs matched with brand guidelines and positioning according to products requirements, such as banners, marketing materials, website, online banners,...etc.

 

## Requirements

* Design software skill: Adobe Illustrator, Adobe Photoshop.

* Knowledge about web and mobile design trend.

* Creative, responsible, teamwork, attention to detail.

* Fair communication in English.

* Understanding about software development or experience in application design is a plus.

* Self-motivated to deliver work on-time and with quality.

* Ability to work part-time at least 28 hours/week.

 

## Benefits:

* Salary: 2,000,000VND /month

* Opportunity to full-time employee.

* Working in friendly environment.

## Contact
* Please provide your resume/CV, as well as any additional items (such as a portfolio, GitHub username, or links to projects you’ve completed) that appropriately describe your accomplishments, skills and responsibilities.
* For more information, contact: trong@rakuna.co
* For more information about Rakuna, check out our website

**Comment by qcam** [comment]
@minhtldm  Thanks for posting. Could you please revise the post to follow [our guideline here](https://github.com/awesome-jobs/vietnam#job-description-format)? All required sections are mandatory.
