### ISSUE TITLE
URBN8 - Senior PHP DEVELOPER - Ho Chi Minh City - Full time

### ISSUE THREAD

**Issue by tiengtinh** [awesome-jobs/vietnam#596]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* $800 - $1000

### Technical Skills Required

- Bachelor&#39;s degree in Computer Science or related field or equivalent work experience.
- Must have experience in working with database backend (PostgreSQL, MySQL or MongoDB).
- Good practice experiences with CSS, HTML(5), Javascript, JSON.
- Having good knowledge of Design Pattern, Restful, OOP.
- Good experiences with Magento/ Lavarel framework, October CMS.
- Have 1 or 2 year experiences on programming.
- Experienced in Agile software development methods (such as Scrum or Kanban) or eager to learn them.

### Personal Skills Required

- Good spoken and written command of English.
- Excellent problem solving skills with strong attention to detail.
- Strong communication skills.
- Demonstrated ability to set and meet tight deadlines and function well under pressure.
- Ability to help others; work in a team where a culture of learning and sharing knowledge is encouraged.
- Great sense of humour and a passion for life is a must!

### Must Have

* Magento/ Lavarel framework.
* CSS, HTML(5), Javascript, JSON.
* Experience working with database (PostgreSQL, MySQL or MongoDB...).
* Design Pattern, Restful, OOP knowledge.

### Ideally

* October CMS, WordPress.
* Agile software development methods (such as Scrum or Kanban).

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* As a PHP/HTML Designer / Developer, you will work on full stack, and should have solid exposure / experience with any of the following: Magento, WordPress, Lavarel Framework, October CMS, in addition, you need to be able to work on both backend API and front end HTML, CSS and basic design work (layout etc.).

* You will be responsible for building, testing, debugging and troubleshooting web services, programs, and scripts for various functions, and modifying existing code to add new features.

* Participate in analyzing requirements, design architecture, implementation, test and deployment process.

### Why it would be awesome to work with us

* Training opportunities: We will provide professional training and official certification for Magento, on a range of subjects either technical or non-technical such as English pronunciation, Agile / Scrum coaching.
* Colleagues: In order to make you feel like "home", we will ensure coffee, snacks, regular BBQ’s, parties and team building events on a bi-monthly basis to keep you and the team fully engaged.
* Holidays: In addition to the standard government compulsory holidays, we will provide you with 20 working days paid holiday and 10 working days paid sick leave. Total of 32 holiday plus sick leave.
    
### Interesting Engineering Projects

* Opportunity to work with brand new Magento 2 projects.
* Build and nurture Magento Plugin/Service utilizing Microservices Architecture on the Magento marketplace.
* Work on Frontend with the latest technologies e.g. ES2015/2016, CSS3.

### Contact
* [urbn8](https://www.facebook.com/urbn8/)
* For further detail about our company and this position, feel free to reach me at: anh.nguyen@tripolis.com

**Comment by qcam** [comment]
@tiengtinh Could you please be more specific on how interesting Magento 1/2, Micro-services Architecture, and ES 2015/2016 are in your company?

Also `(MUST)` in `Contact (MUST)` can be removed.

**Comment by tiengtinh** [comment]
Hi @qcam I've updated the post. Thanks for your feedbacks,
