### ISSUE TITLE
hasBrain - Backend Developer (Junior/Senior) - Saigon - FT 

### ISSUE THREAD

**Issue by linhphamhr** [awesome-jobs/vietnam#598]
## Location

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, HCMC, Vietnam

## Salary Expectation

* Negotiate

## Job Description 

* We are looking for a Backend Developer who will report directly to the CEO and will be responsible for multiple web apps, including design, architecture, development, and testing
* Our forward product is Brain Tracker, an analytics-driven tool to answer the question of how good a developer is. With Brain Tracker, we’ll help build the next generation of elite developers. You will also be exposed and require to work with Userkit, a set of APIs and our identity management and engagement system which plays a huge role in Brain Tracker. 

## Requirements

* Programming Language: NodeJS / Python / Scala
* 2-5+ years of experience in software development
* Knowledge of CI/CD, Docker and microservices
* Able to integrate multiple data sources and databases into one system
* Understanding of accessibility and security compliance
* Knowledge of user authentication and authorization between multiple systems, servers, and
environments
* Understanding of fundamental design principles behind a scalable application
* Understanding of the differences between multiple delivery platforms, such as mobile vs
desktop, and optimizing output to match the specific platform
* Able to create database schemas that represent and support business processes
* Strong unit test and debugging skills
* Proficient understanding of Git
* Knowledge in Big data technologies is a plus
* Ability to develop and implement open source software projects
* Effective operation in a fast-paced, deadline-driven, and collaborative programming
environment

### Attitudes

- Meticulous
- Positive attitude with a hunger for learning
- Ability to self-study and research, willing to learn attitude
- Like to work in an agile development environment
- Self-driven and able work well in a team
- Ability to work in areas outside of their usual comfort zone and get things done quickly
- "Do what it takes" attitude is critical
- Good verbal and written English communications skills and demonstrated experience in presenting details and resolving differences across a variety of tasks.

### Why it would be awesome to work with us

- Work with a product driven team of founders and developers directly to drive change
- Be exposed to our users to see the change and value you are bringing to society
- Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
- International exposure. We are an result driven international team. The core team worked in Silicon Valley, Singapore, Hong Kong, New Zealand and you can expect the culture to be built on trust and results
- Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm on Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours 
- Further benefits including flights, training and other living expenses while training, exchanging with other teams and liaising with clients
- Homey office in Binh Thanh District including breakfast and lunch
- 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
- No dress code. It’s your choice to be confident and comfortable
- Pantry area with snacks, beer and other beverages.

### Interested?
Homepage: http://www.hasbrain.com/
Master your crafts and make impacts with us by emailing the below to linh@hasbrain.com

- CV (no more than 2 pages with relevant experiences. Just keep this simple)
- We do not need a cover letter, just two sentences to sum up yourself
- For shortlisted candidates, be prepared for a short interview on Skype followed by a round at our office.

**Comment by phanhongan** [comment]
Why was it closed? @qcam

**Comment by qcam** [comment]
@phanhongan it is being review and will be reopen when it passes the process.

**Comment by qcam** [comment]
@linhphamhr Could you please update the post to align with [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All required sections must be filled.
