### ISSUE TITLE
JAVIS - Freerance part-time developer - Hanoi

### ISSUE THREAD

**Issue by YoshinoriTone** [awesome-jobs/vietnam#599]
## Location

* Hanoi, Vietnam
* Remote

## Salary Expectation

* 80,000 VND / hour ~. Each task has expected time(hour). We will pay for tasks you finished calculating total hours.
* For ex, The task expected hour is 3, if you finished in 2 hours, you can take fee for 3 hours.  
* You can start immediately.

## Requirements

* Ruby on Rails
* PostgreSQL
* MySQL
* 3+ years Software Engineering experience

### Must Have

* git ( git flow )
* English communication.
* professional mind.
* communication frequently
* never mind to use japanese characters on product. ( of course we can translate )

### Ideally

* Experience with redmine.
* Knowledge about docker.

### Responsibilities

* Clean code and commit
* Follow spec strictly

### Contact

Homepage: https://www.facebook.com/javisenterprise/
yosinori.tone@gmail.com

**Comment by YoshinoriTone** [comment]
Dear @qcam

hi, we want to publish this post as soon as possible. 
Please advice us to open this issue.

Thank you.

**Comment by qcam** [comment]
@YoshinoriTone

* For **Freerance** do you mean **Freelance**?
* Please update your post to match [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all required sections must be filled.
* Also this post looks too lean and lack of information to me, could you please provide more details about the job and the company?
