### ISSUE TITLE
Earlybird.vn - Website TMĐT Của Cộng Đồng Handmade Việt Nam - Ruby on Rails Developer - Hanoi, Vietnam - FT

### ISSUE THREAD

**Issue by hungle88** [awesome-jobs/vietnam#6]
## Location
- Hanoi, Vietnam
## Salary Expectation
- $500+/negotiable
## Requirements
- A solid understanding of basic concepts such as OOP, MVC
- Git is the go-to version control tool.
- Experiences with Javascript/ JQuery/ Ajax/ HTML5/ CSS3
- Experiences with the Ruby Programming Language & the Ruby on Rails Framework as well as its best practices 
- Experiences with building Web Application & familiar with web technologies like Mysql, Postgresql, Apache, NginX ... 
- Comfortably working in Linux environment (Ubuntu & CentOS)
- Attention for performance, maintainability & scalability
- Having knowledge of Redis & ElasticSearch is a plus
- Good problem solving skill
- Read & Write English.
### Must Have
- Highly responsible
- Open-minded
- Friendly & fun to be around.
### You’ll be responsible for
- Developing our current Ruby on Rails application
- Building new APIs for third-party apps
### Contact

[Earlybird](http://earlybird.vn/) is a community and marketplace for trading modern art and handmade goods in Vietnam. Our missions are empowering creative individuals to work independently & bring a positive impact on the local economy.

If you have passion for building great product, a desire to serve the people of Vietnam and have the necessary skills for doing so. We would love to hear from you. 

Lê Quốc Hưng 
Email: hunglq[at]earlybird.vn

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by hungle88** [comment]
Just updated!

**Comment by joneslee85** [comment]
@hungle88 :+1: :+1:
