### ISSUE TITLE
fram^ Vietnam - Senior PHP Engineer - Da Nang - FT

### ISSUE THREAD

**Issue by framvietnam** [awesome-jobs/vietnam#602]
![logo](https://user-images.githubusercontent.com/29363533/27818283-338d348e-60bf-11e7-8540-aee3c287ad95.png)

## Location

* Da Nang, Vietnam

## Salary Expectation

* $1200 - $2000 gross/month

## Requirements
* PHP
* Laravel Framework
* Fluent English skills
* 3+ years Software Engineering experience

### Must Have

* Smart and experienced in Backend development (more than 3 years).
* Experienced in PHP and Laravel (version > 5.0) for 1 year, at least
* Good understanding about OOP concepts
* Good understanding about relational database (Oracle, Postgres, MySQL)
* Experienced with cache frameworks (Redis, Memcached)
* Experienced with Version control systems (Git/ Mercurial)
* Experience with UnitTest in PHP
* Not afraid of Frontend tasks, HTML/CSS/Javascript
* Good at English communication skills, responds to questions directly, promptly, without diverging from the subject too much
* Able to write well-structured, maintainable code
* Worked with Agile (SCRUM/ Kanban)

### Ideally

* Good understanding about Microservices, Service Oriented Design, DDD (Domain Driven Design)
* Good awareness about TDD, BDD
* Worked with statically typed programming languages (Java/C/C++/C#)
* Interested in devops
* Experienced in Docker/Vagrant
* Eager to learn new technologies and stay up-to-dated with modern frameworks
* You have a can-do-attitude and put the goals of the team before your own prestige
* You are able and hungry to take on a lot of responsibility

### Responsibilities

You will improve the product and develop new features of a web-based SaaS technology startup in the HR and recruiting space . Most important is that your coding should be at the highest standard, easily maintainable and easy to read. You are able to work independently, you deliver on time and you take initiative to keep team communication alive at all times.

### Why it would be awesome to work with us

* Excellent and competitive salary package with 13th monthly salary and a good long‐term and performance bonus
* 5-day working week (Monday-Friday), working hours to some extent flexible
* Professional and open working environment, with the culture and office of a Scandinavian online company, in Indochina Riverside Tower, Da Nang city.
* More annual leaves than Vietnam’s Labor Law (Swedish national day and Christmas Eve) and will increase by working years. Vietnamese standard health insurance plus Premium health care package.
* Opportunities to improve English skills within an international team – English is an official language in fram^ office. Also regular English lessons two times per week by native English teachers in the office
* Opportunities to gain hands-on experience in cutting-edge technologies
* Opportunities to become one of the key members of fram^ as we build this fast growing company together!
* Guaranteed permanent employment and career development.

### Interesting Engineering Projects

fram^ was founded by people who have spent most of their professional careers on or around the web. The first seeds of fram^ was planted within e-commerce development. Today, fram^ has expanded into the four core pillars of web engineering - E-commerce, Core web, Mobile web, and New web technologies.

![fram 1](https://user-images.githubusercontent.com/29363533/27818168-c654e628-60be-11e7-941d-8529422344f5.jpg)

![fram 2](https://user-images.githubusercontent.com/29363533/27818172-cea46db2-60be-11e7-8331-a261edf5cb0c.jpg)

### Contact
Homepage: https://wearefram.com/
Contact person: Ms. Hao
Contact address: careers@wearefram.com (Telephone number: 02838217790)

**Comment by buihoang95** [comment]
Hi recruiter,
I'm Hoang, a senior student from University of Engineering and Technology, VNU Hanoi
I'm wondering that do u recruit for junior?

**Comment by framvietnam** [comment]
Hi Hoang,
Thank you for your interest in our company.
So regret that there are no current openings for junior level right now. However, do please send us your CV so we can keep you in view for upcoming roles - Fram is growing fast and we will be in need of hungry talents!

**Comment by qcam** [comment]
@framvietnam Could you please update the post to follow our [guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all required sections must be filled.

**Comment by framvietnam** [comment]
Hi, I've updated the post already. Could you please open it again? 
Thanks so much.
