### ISSUE TITLE
LARION - Business Analyst Internship - Saigon - PT/FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#603]
## Location
* Hall 5, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCMC

## Salary Expectation
* 2,000,000 VND/month

## Requirements
* Excellence in English (written and verbal skills)
* Have a strong passion in communicating with customer

## Skills
* Business Analyst

### Must Have
* Excellent in English (written and verbal skills)
* Good presentation and documentation skills
* Enthusiastic and supportive team-player, reliable and responsible

### Responsibilities
* Gather business and system requirements from client
* Communicate with customers to clarify any unclear information about the business requirements
* Analyze and specify requirements, synthesize information provided by relevant stakeholders

### Why it would be awesome to work with us
* Salary
* Lunch & parking free
* On-the-job training
* Learn both soft and technical skills
* Develop a long-term career path with LARION

### Interesting Engineering Projects 
Our wide range of services includes:
* Ruby on Rails Web Application Development
* Big Data – Data Analytics especially in Healthcare
* Supply Chain Management Application Development
* Social E-commerce App Development
* Securities Trading Solutions Development
* SurroundCore Banking Solutions Development

### Contact
Email: recruitment@elarion.com

**Comment by qcam** [comment]
@joneslee85 @huydx any ideas on this job? I'm on the fence 🤔
