### ISSUE TITLE
hasBrain - ReactJS Developer (Junior/Senior) - Saigon - FT

### ISSUE THREAD

**Issue by linhphamhr** [awesome-jobs/vietnam#604]
## Location 

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, Saigon, Vietnam.

## Salary Expectation 

* Competitive 

## Requirements 

* Degree in Computer Science, Information Systems, or a related field, or significant equivalent experience
* At least 3 years professional front-end development experience in a senior developer role
* 5+ years of experience in software development
* Strong working knowledge of HTML5, CSS, and JavaScript
* At least 1-year experience in ReactJS or equivalent experience in other JS front end frameworks with an interest in ReactJS
* Ability to develop and implement open source software projects

### Must Have 

* At least 1-year experience in ReactJS or equivalent experience in other JS front end frameworks with an interest in ReactJS

### Ideally

* Effective operation in a fast-paced, deadline-driven, and collaborative programming environment
* Good understanding of back-end technologies, such as NodeJS

### Responsibilities
* Using the cutting edge of HTML 5, Javascript, jQuery, AJAX and CSS to develop and test on the latest desktop and mobile browsers
* Learn and absorb new technologies quickly, be a strong team player and rapidly adapt to changing business and customer demands
* Develop innovative Web-based tools and specifications, and make recommendations on the use of new and emerging technologies for a wide variety of projects for our client

### Why it would be awesome to work with us 

* Work with a product driven team of founders and developers directly to drive change
* Be exposed to our users to see the change and value you are bringing to society
* Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
* International exposure. We are a result-driven international team. The core team worked in Silicon Valley, Singapore, Hong Kong, New Zealand and you can expect the culture to be built on trust and results
* Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm on Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours 
* Further benefits including flights, training, and other living expenses while training, exchanging with other teams and liaising with clients
* Homey office in District Binh Thanh including breakfast and lunch
* 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
* No dress code. It’s your choice to be confident and comfortable
* Pantry area with snacks, beer, and other beverages.

    
### Interesting Engineering Projects 

* Move the next wave of digital video consumption through collaborations with media companies. We work with the best content companies to build experiences that matter.

### Contact 
Homepage: http://www.hasbrain.com/
Email: linh@hasbrain.com 
Skype: linhhling

**Comment by qcam** [comment]
@linhphamhr Could you please update the post to align with [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All required sections must be filled.

**Comment by linhphamhr** [comment]
@qcam Hi, thank you so much for the reviewing and comment. I just updated it, could you please take a look and let me know if there any other issue. Thank you in advance.

**Comment by HuyPhat** [comment]
Can I do part time?

**Comment by linhphamhr** [comment]
Hi @HuyPhat, 
Thank you for your interested in our Job Opportunity. Unfortunately, at the moment, this position is unavailable for part-time. Please leave your Skype id or email, I will contact you for further information.
