### ISSUE TITLE
hasBrain - Senior Android Developer - Saigon - FT

### ISSUE THREAD

**Issue by linhphamhr** [awesome-jobs/vietnam#605]
## Location (MUST)

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, Saigon, Vietnam

## Salary Expectation (MUST)

* Competitive

## Requirements 

* At least 3 years professional Android development experience in a senior developer role
* At least 5 years of experience in software development

### Must Have

* Strong knowledge of Android SDK, different versions of Android, and how to deal with different screen sizes
* Familiarity with RESTful APIs to connect Android applications to backend services
* Strong knowledge of Android UI design principles, patterns, and best practices
* Experience with offline storage, threading, and performance tuning
* Ability to design applications around natural user interfaces
* Knowledge of the open-source Android ecosystem and libraries
* Ability to understand business requirements and translate them into technical requirements
* Familiarity with cloud message APIs and push notifications
* A knack for benchmarking and optimization
* Strong knowledge of Android UI design principles
* Proficient in Git code version tools
* Familiarity with continuous integration
* Open mind

### Responsibilities

* Translate designs and wireframes into high-quality code
* Design, build and maintain high-performance, reusable, and reliable code
* Ensure the best possible performance, quality, and responsiveness of the application
* Identify and correct bottlenecks and fix bugs
* Help maintain code quality, organization, and automatization

### Why it would be awesome to work with us (REQUIRED)

* Work with a product driven team of founders and developers directly to drive change
* Be exposed to our users to see the change and value you are bringing to society
* Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
* International exposure. We are a result-driven international team. The core team worked in Silicon Valley, Singapore, Hong Kong, New Zealand and you can expect the culture to be built on trust and results
* Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm on Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours
* Further benefits including flights, training, and other living expenses while training, exchanging with other teams and liaising with clients
* Homey office in Binh Thanh District including breakfast and lunch
* 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
* No dress code. It’s your choice to be confident and comfortable
* Pantry area with snacks, beer, and other beverages.

    
### Interesting Engineering Projects

Move the next wave of digital video consumption through collaborations with media companies. We work with the best content companies to build experiences that matter.

### Contact 
Homepage:http://www.hasbrain.com/
Email: linh@hasbrain.com
Skype: linhhling

**Comment by qcam** [comment]
@linhphamhr Could you please update the post to align with [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All required sections must be filled.

**Comment by linhphamhr** [comment]
@qcam Hi, all the sections required has been updated. Please have a review and let me know if there any other sections must be changed. Thank you for your patient.
