### ISSUE TITLE
Cho Tot - Senior Backend Engineer - HCMC - FT

### ISSUE THREAD

**Issue by minhlyandyou** [awesome-jobs/vietnam#607]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1000 - $2000/month or range

## Requirements
* Strong Computer Science foundation
* Strong understanding of system performance and scaling
* Experienced with micro services architecture, containerized and distributed system

### Must Have

* Good communication skills
* Problem solver and critical thinking
* Ability to be jack of all trades to code in any languages (Nodejs, Python, C…), but willing to work on Golang

### Ideally

* Experienced with ElasticSearch, Kubernetes, Kafka is a strong plus.

### Responsibilities

* Develop high-scale / high-load / distributed backend solutions
* Implement, troubleshoot and maintain current software systems
* Develop internal tool to support back office operations and improve developer’s efficiency
* Build and support big/fast data platform

### You’ll be responsible for

* Develop backend system to support mobile solution for the Cho Tot;
* Assist existing countries in the Company group to develop required solutions; and
* Travel to the Countries to support in any of the above activities when necessary or when directed by the Company

### You can bring

* A good jack of all trades.

### Why it would be awesome to work with us
* Rooms for self challenge and development.
* Super capable and fun-loving team.
* Competitive package.

### Interesting engineering projects
- Architect and build cutting edge, cloud native micro services and platform. High requests, low latency, resilence, on one of the highest traffic website in Viet Nam
- Advanced AI/ML supported system on big data. For automatic review, and fraud detection, user recommendation
- Keeping up to date, and stay competitive with latest tech stack.  Currently on fully dockerized system, Kubernetes deployment, Golang based backend and tooling, React web, event driven system Kafka based….

### Contact
Career page: http://careers.chotot.com/job/backend-developer/
Email: lyvo@chotot.vn

**Comment by qcam** [comment]
@minhlyandyou thanks for posting. Please find my comments below:

* Job title shall have no `[]`.
* Interesting engineering projects* section is required.

**Comment by minhlyandyou** [comment]
Hi @qcam, thanks for your comment. I've adjusted the JD. Your approval please!
