### ISSUE TITLE
Leflair - React/Node.js Developer - Saigon - FT

### ISSUE THREAD

**Issue by leflairvietnam** [awesome-jobs/vietnam#608]
As a Javascript, React, Node.js, Front End Developer, you will have an opportunity to learn the skills required to be a full-stack developer, including modern infrastructure technologies. As part of a human-sized team you will have a big impact at Leflair.

## Location: 
Copac Square, 12 Ton Dan, District 4, HCMC

## Salary range:
 $1000 - $2000 ( experienced)

## Job description
- Work with the CTO to build our ecommerce web site and management platform
- Implement site designs using HTML5, CSS3, Bootstrap, React
- Develop our backend APIs using Node.js
- Work with NoSQL and SQL databases
- Test our applications
- Code review and refactoring

### Technical
- React / Javascript
- Node.js
- HTML5, CSS3, Bootstrap
- Responsive Design
- Git
- Automated Testing
### Personal
- Strong English skills are necessary
- Good communications skills
- Logical thinking and analysis
- Attention to detail
### Bonus Points
- MongoDB/Mongoose
- Typescript
- Grunt, Gulp etc.
- CI/CD Tools
- Cloud Infrastructure and Docker

## What We Offer In Return
- A chance to work in a developing industry with skyrocketing growth rates
- Rapid knowledge growth as full stack developer and big impact on the company
- High performing environment where results are more important than effort
- Competitive salary and promotions based on skill set and success
- A chance to work with high energy, international and innovative teams
- Freedom in a responsible, collaborative and creative environment
- Access to our Employee Stock Options

## Interesting engineering projects

Our website https://www.leflair.vn was created by our 3 awesome tech guys.

## Contact person: 
Email: careers@leflair.vn
Linkdln: https://www.linkedin.com/company-beta/6458506/

**Comment by qcam** [comment]
@angiedang thanks for posting. Generally the post looks good except of a few nitpicks.

* Separate contents from headings.
* A few of sections like *Interesting Engineering Projects* are missing. Please see our [guideline](https://github.com/awesome-jobs/vietnam#job-description-format) and ensure all required sections are well filled.

**Comment by angiedang** [comment]
Thank you for your support. I found my mistakes and apply the right one with request No. 612. Hope it could ensure our group guideline.

**Comment by qcam** [comment]
@leflairvietnam thanks, but could you please update this one instead?

**Comment by leflairvietnam** [comment]
@qcam Yes, I updated. Sorry for taking your time to check the post. Have a nice day!

**Comment by rebyn** [comment]
Too bad this is closed (https://github.com/awesome-jobs/vietnam/issues/366), your site has been down / up & idle horrendously this morning 🐼 .

**Comment by leflairvietnam** [comment]
Hi Guys,

Please check again the reason you closed #366.
Today our website has the shopping battle ( big campaign of this month), so
the traffic of visitors in this morning may caused the issues.
Our Tech team fixed already. Therefore, please give me a logical reason to
close #366.

Thanks a lot for your supporting!
TB

*Thao Bui*
*People Operations Executive*

We’re hiring! Check it out here
<https://recruit.zohopublic.com/recruit/Portal.na?digest=NxNHXXxClmm2TT%40TF.DleXGAUnkE7bVo.a85bxdBEmQ-&iframe=false&mode=home>

thao.bui@leflair.vn
www.leflair.vn

T +84 1677 3789 06

(08) 3825 3222

*Leflair Vietnam*
Floor 1, 12 Ton Dan
Quan 4, Tp. HCM
[image: Facebook] <https://www.facebook.com/LeflairVN/> [image: Instagram]
<https://www.instagram.com/leflairvietnam/> [image: LinkedIn]
<https://www.linkedin.com/company/leflair>
<http://www.leflair.vn/>

The most desirable brands made accessible.

Leflair provides its members with exclusive access to the world’s best
brands at up to 70% off retail. Every morning, we open new sales for women,
men, kids, home, and much more.
