### ISSUE TITLE
Leflair - React/Node.js Developer - Saigon - FT

### ISSUE THREAD

**Issue by leflairvietnam** [awesome-jobs/vietnam#612]
As a Javascript, React, Node.js, Front End Developer, you will have an opportunity to learn the skills required to be a full-stack developer, including modern infrastructure technologies. As part of a human-sized team you will have a big impact at Leflair.
## Location

* Copac Square, 12 Ton Dan, District 4, HCMC

## Salary Expectation

* $1000 - $2000/month 

### Technical

*React / Javascript
*Node.js
*HTML5, CSS3, Bootstrap
*Responsive Design
*Git
*Automated Testing

### Bonus Point

*MongoDB/Mongoose
*Typescript
*Grunt, Gulp etc.
*CI/CD Tools
*Cloud Infrastructure and Docker

### Must Have

* 2 years experiences in React/Node.js at least
* strong English communication

### You’ll be responsible for

* Work with the CTO to build our ecommerce web site and management platform
* Implement site designs using HTML5, CSS3, Bootstrap, React
* Develop our backend APIs using Node.js
* Work with NoSQL and SQL databases
* Test our applications
* Code review and refactoring

### Interesting engineering projects

* Our website https://www.leflair.vn was created by our 3 awesome tech guys.

### Contact
Email: careers@leflair.vn
Linkdln: https://www.linkedin.com/company-beta/6458506/

**Comment by qcam** [comment]
Closing due to duplication
