### ISSUE TITLE
Pangara - Pangara Freelancer - Remote/Vietnam - PT/C

### ISSUE THREAD

**Issue by nghiato** [awesome-jobs/vietnam#613]
![for danny 1](https://user-images.githubusercontent.com/28036275/28155578-8a6d063c-67d9-11e7-8bc7-d18beb5626fb.jpg)

## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $15-17/h
* Can be higher, depends on the assignments!

## Requirements
* At least 3 years' hands-on experience
* Strong English communication
* Available at least 15h/w for Pangara's freelance opportunities
* Vietnamese only!
* Passed our unique online qualification process with the tests supplied by Cut-e and Codility

### We are looking for talents with skills of:
* PHP with Drupal CMS 7/8 ( especially version 8 )
* Mobile development with React Native or Xamarin
* Frontend Developer with ReactJS/VueJS frameworks ( we are also looking for a full-time Frontend developer with ReactJS/VueJS experience with range of salary; $1200-1400/month )

## Why it would be awesome to work with us
* Competitive rate ( per hour ) in Vietnamese freelance market
* Sharpen your skill set and challenge yourself with international projects coming from our worldwide clients ( mostly coming from Scandinavian countries like Sweden, Switzerland )
* Enhance your English skills through working with other +350 senior developer in Pangara Network!
* Safe projects - Credible clients - Professional environment

## We also prefer interesting incentives for the referee!
![talents referral scheme](https://user-images.githubusercontent.com/28036275/28155629-b80cf552-67d9-11e7-859a-544d53ea0b89.jpg)

## Contact
Nghia (Danny) To - Talent Specialist
Email: nghia.to@pangara.com
Skype: minhnghiato@outlook.com
Handphone: 0937.333.831

**Comment by huydx** [comment]
Hi @nghiato , this job post is NOT for 3rd party recruiter. 
Thanks
