### ISSUE TITLE
Wizeline - Full-stack Software Engineer - Ho Chi Minh city - FT

### ISSUE THREAD

**Issue by hongduong18** [awesome-jobs/vietnam#614]
## Location

* Ho Chi Minh, Vietnam
* Full time

## Requirements

* 2+ years of development experience on Front and Back End.
* Outstanding software engineering skills (Data structures, algorithms, coding skills).
* Strong analytical and communication skills.
* A positive disposition and good attitude under pressure.
* BS/MS in Computer Science, Engineering or related subject from a top tier school.

### How are you going to make difference? 
* Build responsive and elegant web applications that are scalable.
* Optimize web applications to maximize speed and scale.
* Support, maintain and enhance existing web applications.
* Develop new APIs to be consumed by millions of users.
* Write clean and maintainable code.

### Why it would be awesome to work with us

- Macbook, trackpad, keyboard, monitor for your working station
- Flexible working time
- Catered meals & fully stocked kitchen
- International health insurance
- Stock option plan
- Free English class
- Internal training class
- Flexible vacation policy
- Inter-office fun between San Francisco & Mexico & Vietnam
- Working abroad program and so much more

### Contact
Homepage: www.wizeline.com/careers  
Email: jobsvn@wizeline.com 

![software-engineer-ad 1](https://user-images.githubusercontent.com/24561711/28204709-493cda18-68a9-11e7-9dc7-fb194c838999.png)

**Comment by huydx** [comment]
Hi, your JD lacks `Interesting engineering projects` parts. Please amend and we will consider to reopen it again

**Comment by hongduong18** [comment]
@huydx I edited it. Thank you!
