### ISSUE TITLE
INNAWAY - Senior PHP Developer (Full-Stack Engineer) - Hanoi - FT

### ISSUE THREAD

**Issue by Dawensky** [awesome-jobs/vietnam#615]
## Location
* Saigon, Vietnam
* Remote

## Salary Expectation
* $1000 - $1200/month or range

## Requirements
1. Strong knowledge of PHP web frameworks (Laravel)
2. Knowledge of web technologies and tools, such as JavaScript, HTML5, and CSS3, Bootstrap, etc.
3. Knowledge of distributed application and MVC design patterns
4. Knowledge of database schema implementation that represent and support business processes
5. Knowledge of MySQL, AWS, and AngularJS (will give you edge),
6. Proficient understanding of code versioning tools, such as Git (Bitbucket)
7. Knowledge of Agile/Scrum practices not so important. Training can be provided if required).
8. Average written and verbal communication skills (Intermediate level of English language). Able to discuss technical problems with peers (in written is good enough)

## Skills
1. Languages & Scripting - PHP Laravel, HTML, DHTML, Java Script, CSS, Bootstrap
2. Software Framework	- Distributed and/or 3-tier
3. Databases - MySQL
4. Remote Server - AWS
5. Code Versioning Tool	- Bitbucket (GIT)
6. Operating Systems	- Linux and/or Windows
7. SDLC Methodology - SCRUM (JIRA software)

### Must Have
1. Experience in PHP Laravel, HTML, DHTML, MySQL, AngularJS
2. Be able to communicate in English (written and verbal) at least intermediate level.
3. Be able to discuss technical problems with peers.
4. 2 - 4 years experience in software development (web application)
5. Bachelor's Degree / Higher Diploma in software engineering / development

###Ideally
1. Strong experience with PHP web frameworks (Laravel)
2. Experience with web technologies and tools, such as JavaScript, HTML5, and CSS3, Bootstrap, etc.
3. Knowledge of distributed application and MVC design patterns
4. Knowledge of database schema implementation that represent and support business processes
5. Knowledge of MySQL, AWS, and AngularJS (will give you edge),
6. Proficient understanding of code versioning tools, such as Git (Bitbucket)
7. Knowledge of Agile/Scrum practices not so important. Training can be provided if required).

### Responsibilities
1. Integration of user-facing elements developed by front-end developers
2. Build efficient, testable, scalable, and reusable modules
3. Solve complex performance problems and architectural challenges.
4. Integration of data storage solutions
5. Deployment of code unit to repository and migration to remote server

### You can bring
1. Interpersonal skills
2. Analytical skills

### Why it would be awesome to work with us
We’re passionate about opening access to a historically exclusive marketplace to an ever broader customers, we’re relentlessly building a system, so intuitive that customers with quality driven will easily get their appetite satisfied on our platform. Join our growing team, with intelligent individuals from hospitality, business, and technology. And below are some captivating benefits provided

1. You can work remotely (if not in Ha Noi city or if you are living far from our office location in Ha Noi)
2. We are using distributed tools for development : JIRA, Bitbucket, Slack, AWS, and etc
3. Company trip 1 time/year within the country
4. Review salary 1 time/year
5. Monthly team building lunch and/or dinner
6. Extra activities (games, movies, picnic, etc)
7. Holidays are in accordance with Vietnamese law.

### Interesting engineering projects
We are building the fastest and user friendly scalable system for mid-range travelers. A system that will have a huge positive influence in the hospitality industry, as well as impacting the social and economic growth of each country it is adopted. We are partnering only with boutique and styles hotels as they exemplify and possess the doctrine of our solution. 

### Contact
Homepage: innaway.co
HR Department: hr@innaway.co

**Comment by Dawensky** [comment]
Hi @huydx, could you reopen this job post. It is legit and I just completed is description. Look through it and let me know any changes required so that job seekers can apply. 
Thanks

**Comment by huydx** [comment]
@Dawensky I believe we have a section called "Interesting Projects"
And, some parts have poor format  (###Ideally )
Please review your JD CAREFULLY before submit.

**Comment by Dawensky** [comment]
Okay! Will modify

**Comment by Dawensky** [comment]
@huydx it is done. Could you review and let me know if there is any other thing to change. If not, could you OPEN it and make it accessible? 
Thanks
