### ISSUE TITLE
Pangara Vietnam - Frontend Developer - Saigon - FT

### ISSUE THREAD

**Issue by nghiato** [awesome-jobs/vietnam#617]
## Location

* District 1, Saigon, Vietnam
* Full-time at Pangara's Office

## Salary Expectation

* $1200 - 1400/month

## Requirements

* At least 2 years experience
* JS/CSS/React/VueJS
* Fluent English communication

### Must Have

- Extensive experience working with Javascript, preferably ECMAScript 2015 version and later
- Several years of experience developing web interfaces as a frontend developer
- Work with one of those Vue/React/Angular/Meteor frameworks before
- Use linters (ESLint, JSLint) to control code quality
- Decent knowledge of web development and security best practices
- A keen eye for UI details, animations and user interaction, attention to details
- Able to work autonomously, know how to use task runners and bundlers to help optimizing application performance
- An ability to take ownership and create quality code independently
- Result oriented, get it done attitude
- Use Git actively in an Agile team

### Ideally

- Experience with Vuejs ecosystem: Vuex, vue-router
- Write modular Javascript and CSS
- Working with Scrum and Agile methodology
- Familiar with git-flow
- RESTful web services
- Docker
- Automation testing

### Responsibilities

We're looking for a passionate Front-end Engineer to join our development team to help to build our SaaS product. You will take the lead of our front-end development work, shaping our development stack and processes in collaboration with our Technical Lead.

- Building the web components for the platform
- Working closely with the product team and sharing the ownership of the user experience
- Transform features and mock-ups into user-facing web components
- Aiming to provide the best UX in the industry
- Continuously test, iterate and optimize the product

You'll work on a rapidly changing product, and will have to find innovative solutions to the stream of new challenges coming your way.

### Interesting Engineering Projects

Pangara is a freelancer platform connecting top tech freelancers in Southeast Asia with clients worldwide. Pangara uses a customized, unique, qualification process to gather and offer only the best of the freelancer network in Southeast Asia - www.pangara.com

![ext](https://user-images.githubusercontent.com/28036275/28255644-d0bb8624-6ae3-11e7-9f89-24b7f1f90784.jpg)

## Why it would be awesome to work with us

- Excellent and competitive salary package
- Modern development stack: Laravel, Vuejs, Webpack, Docker, AWS, Gitlab CI, etc.
- Budget for training courses in the field (front-end, back-end, cloud, DevOps, you name it)
- 5-day working week (Monday-Friday), working hours to some extent flexible
- Professional and open working environment, with the culture and office of a Scandinavian online company, on Nguyen Cong Tru in central
- Ho Chi Minh City
- Annual leave and insurance policies in compliance with Vietnam’s Labor Law and company's regulations
- Opportunities to improve English skills within an international team – English is the official language in Pangara office.
- Opportunities to gain hands-on experience in cutting-edge technologies
- Opportunities to become one of the key members of Pangara as we build this fast growing company together!

## If you think you’ve got what it takes we would love to hear from you - Apply now!

Nghia (Danny) To

- Email: nghia.to@pangara.com
- Handphone: +84 937.333.831
- Skype: minhnghiato@outlook.com

**Comment by huydx** [comment]
We DO NOT accept third party recruiter

**Comment by nghiato** [comment]
Hi HuyDx,
We are looking for a Full-time position for our company, not as a third recruitment party. Please review and hope that you can open this news again since this is a really competitive job with good salary package.

**Comment by huydx** [comment]
@nghiato so you please input your product name and `Interesting projects` section please

**Comment by nghiato** [comment]
@huydx I updated the news. Please take a look :)

**Comment by euronck** [comment]
wow a recruiting company recruiting on here... things must be really bad in HCM for this to happen :(
