### ISSUE TITLE
gumi Vietnam - Junior Ruby on Rails developer - Saigon - FT

### ISSUE THREAD

**Issue by trongthaonh** [awesome-jobs/vietnam#620]
## Location

* 39 Nguyen Thi Dieu, Ward 6, District 3, HCM city

## Salary Expectation

* Up to $1000

## Requirements
* At least 1 year experience with Ruby On Rails development and some of server-side languages such as Node JS, Java...
* At least 1 year experience with Automated Test and Test Driven Development 
* Knowledge about DB design, IT-architecture and object oriented frameworks
* Knowledge about Git and preferably GitHub 
* Basic knowledge about Javascript, HTML and CSS 
* Knowledge about Angular JS or React JS

## Skills
* Ruby on Rails
* Angular JS or React JS

### Must Have

* Have passion in programing and willing to learn new technology
* Solid understanding of object-oriented programming

### Ideally

* Comfortably using Front-end frameworks such as Bootstrap, Foundation ...
* Hosting and deployment in the cloud - e.g. Amazon 
* Speaking Japanese

### You’ll be responsible for

* Develop & maintain web applications.
* Participate in daily standups meetings.
* Participate in client and project manager meetings.
* Contribute idea and play role in the growth of the company.
* Enjoy great career growth opportunities.

### Why it would be awesome to work with us

* Working in a professional, friendly, well-equipped environment both with Japanese and Vietnamese.
* Month 13th salary.
* Review salary: 2 twice/year
* Career path promotional opportunities
* Bonus base on performance.
* Labor contract ,insurance, annual days off are based on Vietnamese law.
* Birthday party, Welcome party, Team building events or monthly company party.
* Company trip each year.
* 40 hour work weeks (8:00-17:30, Mon-Fri)
* 14 days of vacation per year

### Contact
Email: thaonguyen@gumiviet.com

![](https://scontent.fsgn5-1.fna.fbcdn.net/v/t1.0-9/19875252_1404773709615914_8099951562854988325_n.jpg?oh=258498d5cee0072eaec865360a522847&oe=59C734C7)

**Comment by huydx** [comment]
@trongthaonh I believe we have 'Interesting project session', please amend your JD

**Comment by qcam** [comment]
@trongthaonh personally I think the requirements are rather tough for a junior developer.

> At least 1 year experience with Ruby On Rails development and some of server-side languages such as Node JS, Java...
> At least 1 year experience with Automated Test and Test Driven Development

By these do you mean Ruby on Rails + RSpec/MiniTest + TDD?

> Knowledge about DB design, IT-architecture and object oriented frameworks

Just to make it clear, what do you mean by **IT architecture** and **object oriented frameworks**?
