### ISSUE TITLE
hasBrain - Junior iOS Developer - Saigon - FT

### ISSUE THREAD

**Issue by linhphamhr** [awesome-jobs/vietnam#621]
## Location

* Saigon Pearl, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, Saigon, Vietnam

## Salary Expectation

* Competitive

## Requirements
* Have strong Computer Science Foundation

### Must Have

* Have the ability to write code with efficiency and readability
### Ideally

* Have experience with iOS development using Swift
* Be familiar with Git and GitHub

### Responsibilities

* Work with the mobile team to estimate, develop, test and maintain iOS apps and libraries
* Support the technical design process for the iOS projects
* Assist in documenting the products
* Provide technical support on the iOS projects to other members of the team
* Take part in the server APIs definition process

### Why it would be awesome to work with us

* Work with a product driven team of founders and developers directly to drive change
* Be exposed to our users to see the change and value you are bringing to society
* Meet and learn from experienced entrepreneurs. Be part of an experienced team that sets out to create positive social impact
* International exposure. We are a result-driven international team. The core team worked in Silicon Valley, Singapore, Hong Kong, New Zealand and you can expect the culture to be built on trust and results
* Freedom and flexibility. In terms of work hours, responsibility and autonomy, you get to decide what works best for you. Usually between 9.00 am and 6.00 pm on Monday to Friday. And it can be flexible, we don’t measure your success by the number of office hours
* Further benefits including flights, training, and other living expenses while training, exchanging with other teams and liaising with clients
* Homey office in Binh Thanh District including breakfast and lunch
* 14 days of annual leave, 14 days of medical leave, and public holidays in Vietnam
* No dress code. It’s your choice to be confident and comfortable
* Pantry area with snacks, beer, and other beverages.

### Interesting engineering projects
Move the next wave of digital video consumption through collaborations with media companies. We work with the best content companies to build experiences that matter.

### Contact
Homepage: http://www.mstage.io/ or http://www.hasbrain.com/
Email: linh@hasbrain.com
Skype: linhhling

**Comment by huy-le** [comment]
This is a copy-paste description from Middle / Senior job. Juniors never have enough experience / proficient skill sets above.

And they never have responsibilities to who is equal level with them:

> Assign logically segmented work to junior developers
> Review and improve the technical ability of junior developers

**Comment by linhphamhr** [comment]
Dear guys, 



Thank you so much for your kindly remind and supporting, 

I will inform our Mobile team to have a review and will be update on that today. 

Have a great day to you all.


Best Regards,

Linh Pham

Business Operations Associate



 



hasBrain Pte. Ltd.

SaiGon Pearl Tower, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, HCMC, VN



http://hasbrain.com/

Tel: (+84)946390099

Mail: linh@hasbrain.com

Skype: linhhling






---- On Thu, 20 Jul 2017 08:11:00 +0700 Huy Le &lt;notifications@github.com&gt; wrote ----




This is a copy-paste description from Middle / Senior job. Juniors never have enough experience / proficient skill sets above.

And they never have responsibilities to who is equal level with them:

Assign logically segmented work to junior developers

 Review and improve the technical ability of junior developers

**Comment by rebyn** [comment]
btw your corp site is down @linhphamhr

**Comment by linhphamhr** [comment]
Dear sir, 



Was the reason due on the incorrect Job Description of Junior iOs developer, sir?

Thank you for supporting, 

I look to hearing more from you.


Best Regards,

Linh Pham

Business Operations Associate



 



hasBrain Pte. Ltd.

SaiGon Pearl Tower, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, HCMC, VN



http://hasbrain.com/

Tel: (+84)946390099

Mail: linh@hasbrain.com

Skype: linhhling






---- On Thu, 20 Jul 2017 10:01:11 +0700 Tu Hoang &lt;notifications@github.com&gt; wrote ----




btw your corp site is down @linhphamhr

**Comment by rebyn** [comment]
What I meant was your company's site (http://hasbrain.com/) is down.

**Comment by linhphamhr** [comment]
Hi Tu,



Ah I see, 

Thank you so much for the report :) 

I am going to check it now, update in a minute.


Best Regards,

Linh Pham

Business Operations Associate



 



hasBrain Pte. Ltd.

SaiGon Pearl Tower, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, HCMC, VN



http://hasbrain.com/

Tel: (+84)946390099

Mail: linh@hasbrain.com

Skype: linhhling






---- On Thu, 20 Jul 2017 10:05:27 +0700 Tu Hoang &lt;notifications@github.com&gt; wrote ----




What I meant was your company's site (http://hasbrain.com/) is down.

**Comment by huy-le** [comment]
Great description!

**Comment by linhphamhr** [comment]
Hi Huy,



Thank you :)


Best Regards,

Linh Pham

Business Operations Associate



 



hasBrain Pte. Ltd.

SaiGon Pearl Tower, 92 Nguyen Huu Canh, Ward 22, Binh Thanh District, HCMC, VN



http://www.hasbrain.com/​

Tel: (+84)946390099

Mail: linh@hasbrain.com

Skype: linhhling






---- On Sat, 22 Jul 2017 13:26:25 +0700 Huy Le &lt;notifications@github.com&gt; wrote ----




Great description!
