### ISSUE TITLE
Junior PHP Developer

### ISSUE THREAD

**Issue by JobSeekersvn** [awesome-jobs/vietnam#623]
## Location

* Quận 3, Saigon, Vietnam

## Salary Expectation

* $300 - $700

**Job Details**

Developing and maintaining web service for Japanese company;
Researching the solutions for solving problem on design and development process;
Creating detailed design, designing database based on analyzed specification;
Supporting estimate for related development tasks and risks for team leader.
**Job Requirements**

Bachelor degree in Information Technology.
Must have some web service development experience with PHP Framework at work or university class.
Basic knowledge of MVC and PHP Framework(Laravel, Codeigniter, Yii, Zend etc..).
Basic knowledge of JavaScript, HTML, CSS.
Basic knowledge of Apache, MySQL, Linux server and network.
Basic knowledge of security.
Good research skill.
Reading and writing in English fluently.
Advanced communication skill.
Active attitude.
Contributing to team and customer.
Good problem-solving skill.

### Contact
Homepage: http://jobseekers.vn/job/79-junior-php-developer/
Email: duong.le@jobseeker.vn
Skype: ltduong2006

**Comment by huydx** [comment]
we DO NOT accept 3rd recruiter JD
