### ISSUE TITLE
Remote Resources/Magmic - Game Developer - Dist. 5, HCMC - FT

### ISSUE THREAD

**Issue by lilytaller** [awesome-jobs/vietnam#625]
## Location

* Dist. 5, HCMC, Vietnam

## Salary range

* $1000 - $2000 USD gross/month

## Requirements

* Proven experience working with C++/C#
* Unity 3D (2D experience a major plus), Cocos 2D-X, Native iOS, Native Android

## Responsibilities

* Implementing new gameplay features
* Help improve and iterate on designs
* Develop tools to improve workflow
* Collaborate with the team to estimate and plan out the development
* Design software requirements with the team and develop software to match the requirements
* Deliver features on time

## Why it would be awesome to work with us

* Work with talented and cool colleagues in game development from HCMC and Ottawa 
* Competitive salary and benefits package
* Supportive work environment which provides a lot of training and mentoring courses

## Contact

* Company website: http://magmic.com/
* Submit application and questions to linh_dot_truong_at_remoteresources_dot_com OR call us on 01287 363 214

### Thank you!

**Comment by qcam** [comment]
Hi @lilytaller, thanks for posting but unfortunately we don't accept third party jobs.
