### ISSUE TITLE
AdAsia Holdings - Senior Data Engineer - Saigon - FT

### ISSUE THREAD

**Issue by shiorimichellematsuyama** [awesome-jobs/vietnam#630]
## Location
* 22F Saigon Trade Center, 37 Ton Duc Thang, District 1, HCMC  
* (Moving to BITEXCO TOWER in August)

## Salary Expectation

* 1000-2000 USD/month
* Performance Bonus (0.5 to 3 months amount)

## Requirements
* 2+ years of data engineering experience
* Passion for data
* Distinctive problem solving and analytic skills with a high degree of analytical rigor
* Ability to effectively and efficiently collect, assimilate and organize data from multiple sources
* Demonstrable familiarity with Python and Data Processing
* A quick learner with regards to (new) technology
* Independently driven, proactive, accountable, and reliable team player

### Must Have
* Full working proficiency in English
* Exposure in Machine Learning

### Ideally
* Crawling technologies: Scrapy or any other framework
* Process automatisation: Ansible, Docker, Kubernetes)
* Big data processing: Spark, Mapreduce, Hadoop, Pig, Hive
* Storage: Cassandra, Redis, MongoDB, CouchDB, Kafka. Any NoSQL
* Search engines: Solr, ElasticSearch

## Responsibilities
* Become the hub of development and communication in the team
* Set up multiple new high-quality data pipelines, which require no or very limited maintenance by automating data input processes and effectively scaling these
* Effectively collect, assimilate and organize data from a wide variety of source
* Identify new opportunities, bottle-necks, and efficiency-issues
* Bring solutions to day-to-day challenges
* Contribute in a positive way to the atmosphere within the team

## Why it would be awesome to work with us
* Competitive Salary
* Performance Review (2 times per year)
* Performance Bonus 
* Quarterly, Annual MVP Awards (prizes up to 8,000USD)
* MacBook to be provided
* Work in professional and dynamic environment
* Good chance to explore new trends in a digital market
* Opportunity to learn most advanced advertising technology platforms
* No fixed day for promotion – Perform well and get promoted anytime!

### Interesting Engineering Projects
* [AdAsia Digital Platform](https://adasiaholdings.com/service/adasia_digital_platform/)
* [AdAsia Ad Network](https://adasiaholdings.com/service/adasia_ad_network/)
* [AdAsia Video Network](https://adasiaholdings.com/adasia-video-network/)
* [Casting Asia](https://adasiaholdings.com/service/castingasia_influencer_marketing/) 

## Contact
Website: https://adasiaholdings.com/join_us/
Shiori Michelle: job@adasiaholdings.com

## How to apply
* [UPLOAD YOUR ENGLISH CV HERE](https://adasiaholdings.com/jp/job/?gh_jid=746572)

**Comment by feliu** [comment]
amazing opportunity! +1

**Comment by buihoang95** [comment]
I'm sorry but I can't find my school University of Engineering and Technology, VNUH in `school name`

**Comment by shiorimichellematsuyama** [comment]
Hello!
Will you send us back you CV to my email?
Thank you!
Shiori

**Comment by buihoang95** [comment]
can you send to me back your email address?
thanks
Hoang

**Comment by shiorimichellematsuyama** [comment]
Hello,

its shiori@adasiaholdings.com


Shiori

**Comment by shiorimichellematsuyama** [comment]
@qcam Hello. I have double checked the guideline and revised. please kindly check the JD again.
