### ISSUE TITLE
AdAsia Holdings - Senior Full Stack Engineer - Saigon - FT

### ISSUE THREAD

**Issue by shiorimichellematsuyama** [awesome-jobs/vietnam#631]
## Location
* 22F Saigon Trade Center, 37 Ton Duc Thang, District 1, HCMC  
* (Moving to BITEXCO TOWER in August)

## Salary Expectation
* 1000-2000 USD/month
* Performance Bonus (0.5 to 3 months amount)

## Requirements
* Experience as Full Stack Developer for 2+ years
* Strong Computer Science fundamentals
* HTML, CSS, Javascript and Angular 2
* Outstanding programming skills
* Experience in fast-paced work environment
* Can ship quality code quickly

### Must Have
* Full working proficiency in English
* Java, C# or Python

## Responsibilities
* Develop new features for AdAsia's web-based products
* Build features that touch the frontend website and backend API
* Write test-driven code and test for 100% functionality
* Maintain and constantly improve our current code
* Work closely with engineering team and product management team

## Why it would be awesome to work with us
* Competitive Salary
* Performance Review (2 times per year)
* Performance Bonus 
* Quarterly, Annual MVP Awards (prizes up to 8,000USD)
* MacBook to be provided
* Work in professional and dynamic environment
* Good chance to explore new trends in a digital market
* Opportunity to learn most advanced advertising technology platforms
* No fixed day for promotion – Perform well and get promoted anytime!

### Interesting Engineering Projects
* [AdAsia Digital Platform](https://adasiaholdings.com/service/adasia_digital_platform/)
* [AdAsia Ad Network](https://adasiaholdings.com/service/adasia_ad_network/)
* [AdAsia Video Network](https://adasiaholdings.com/adasia-video-network/)
* [Casting Asia](https://adasiaholdings.com/service/castingasia_influencer_marketing/) 

## Contact
Website: https://adasiaholdings.com/join_us/
Shiori Michelle: job@adasiaholdings.com

## How to apply
* [UPLOAD YOUR ENGLISH CV HERE](https://adasiaholdings.com/jp/job/?gh_jid=746555)

**Comment by qcam** [comment]
Hi @shiorimichellematsuyama could you update your job description to match our [guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All sections with `REQUIRED` suffix must be filled.

**Comment by shiorimichellematsuyama** [comment]
@qcam Hello. I have double checked the guideline and revised. please kindly check the JD again.

**Comment by qcam** [comment]
@shiorimichellematsuyama sorry but I have one more question, what is the different between this job and the other https://github.com/awesome-jobs/vietnam/issues/632? From the job descriptions they looks quite alike to each other.

**Comment by shiorimichellematsuyama** [comment]
@qcam This one requires backend knowledge and experience too. But because I did not want to limit the language, I didn't mention earlier. I added Java or C in required skill and 2+ yrs of fullstack experience in the requirement.
