### ISSUE TITLE
AdAsia Holdings - Senior Frontend Engineer - Saigon - FT

### ISSUE THREAD

**Issue by shiorimichellematsuyama** [awesome-jobs/vietnam#632]
## Location
* 22F Saigon Trade Center, 37 Ton Duc Thang, District 1, HCMC  
* (Moving to BITEXCO TOWER in August)

## Salary Expectation
* 1000-2000 USD/month
* Performance Bonus (0.5 to 3 months amount)

## Who You Are
* Strong Computer Science fundamentals
* HTML, CSS, Javascript and Angular 2
* Outstanding programming skills
* Experience in fast-paced work environment
* Can ship quality code quickly

### Must Have
* Full working proficiency in English

## Requirements
* Be responsible for the client side of our product, AdAsia Digital Platform.
* Implement a complete UI for desktop and mobile with a focus on performance.
* Create application with Angular 2, HTML5, CSS3, Javascript and TypeScript
* Build landing pages for clients
* Improve UI/UX
* Create detailed technical specifications based on wireframes and functional specifications
* Creating modules / components and coupling them together into a functional application
* Work with a team of developers, designers and product managers

## Why it would be awesome to work with us
* Competitive Salary
* Performance Review (2 times per year)
* Performance Bonus 
* Quarterly, Annual MVP Awards (prizes up to 8,000USD)
* MacBook to be provided
* Work in professional and dynamic environment
* Good chance to explore new trends in a digital market
* Opportunity to learn most advanced advertising technology platforms
* No fixed day for promotion – Perform well and get promoted anytime!

### Interesting Engineering Projects
* [AdAsia Digital Platform](https://adasiaholdings.com/service/adasia_digital_platform/)
* [AdAsia Ad Network](https://adasiaholdings.com/service/adasia_ad_network/)
* [AdAsia Video Network](https://adasiaholdings.com/adasia-video-network/)
* [Casting Asia](https://adasiaholdings.com/service/castingasia_influencer_marketing/) 

## Contact
Website: https://adasiaholdings.com/join_us/
Shiori Michelle: job@adasiaholdings.com

## How to apply
* [UPLOAD YOUR ENGLISH CV HERE](https://adasiaholdings.com/jp/job/?gh_jid=761496)

**Comment by qcam** [comment]
Hi @shiorimichellematsuyama, could you update your job description to match our [guideline](https://github.com/awesome-jobs/vietnam#job-description-format)? All sections with `REQUIRED` suffix must be filled.

**Comment by shiorimichellematsuyama** [comment]
@qcam Hello. I have double checked the guideline and revised. please kindly check the JD again.
