### ISSUE TITLE
IT Consultis - Laravel Technical Leader - Saigon - FT

### ISSUE THREAD

**Issue by tguillemaud** [awesome-jobs/vietnam#633]
## Location

Saigon, Vietnam

## Salary Expectation

From 1500 to 2500 USD/month

## Requirement

* You had a similar roles of leader/manager of a Laravel team composed of more than 5 members and you have have experience inside multicultural team
* Proven experience developing and deploying large traffic web applications

### Must have

* Advanced knowledge of Linux fundamentals, including networking, file systems, security, and SSH
* Experience with MySQL databases, including query optimization
* Understand the value of commitments to delivery made by a development team
* You need to master these technologies:
  * Laravel 5.x
  * HTML5/CSS3 and JS
  * REST
  * CSV
  * XML
  * JSON
  * Git, Gitlab and Gitlab CI
  * Docker
  * Unit testing
* Security oriented
* Deep understanding of the MVC and MVVM patterns
* You need to be focused on performance and cross platform compatibility
* Basic Knowledge of one at least one of the following: Drupal, Magento, Wordpress  
* Knowledge of Javascript (ES5/ES6)
* Deep understanding of the  Object Oriented Programming (OOP) pattern
* Experience in developing composer packages
* Experience in integrating third party APIs
* Understanding of openapi specifications and experience working with swagger.io

### Ideally

* Any additional language is a plus
* Knowledge of React.js and node.js is a plus
* Completely understanding of the HTTP protocol, expert proficiency with nginx and Apache web servers; HTTP caching know-how is a big plus
* Experience with monitoring tools, such as Zabbix or Nagios, is highly desirable
* Knowledge of SEO best practices
* Experience in working with WeChat API

## Responsibilities

* Participate in the conception of websites and APIs ensuring feasibility of requirements.
* Work on Laravel integration with external system CMS/CRM/ERP/Payment/Shipping …
* Analyze, debug and test code
* Build web application by making clean, tested and maintainable code
* Review the code of other Laravel team members in Saigon and Shanghai
* Find the best solutions to maximize the efficiency of Laravel and to ensure developers adhere to best practices across the entire spectrum of tools, languages and frameworks used at ITC.
* Understand the training needs and development trend of the team, propose for training schedule, sources and implement it; train the junior members and be in charge of presentation internally regarding the knowledge updates
* Be the link between project managers and the developers by providing technical support to project managers, account and sales team.
* Reporting to the CTO about the Laravel team challenges and progress
* Making sure all the KPIs are well spread across the team members and management
* Support the recruitment process by qualifying candidates and interviewing them

## You can bring:

* Excellent written, verbal and interpersonal English communication skills. The position requires frequent communication with colleagues and in several different geographic locations and time zones 
* Proven ability to work with all members of an extended and diverse project team
* Must be detail-oriented, self-organized, be committed to quality and be capable of tracking multiple issues simultaneously
* Capability of mentoring and guidance skills to provide oversight and direction to contractors and junior members of the team
* Excellent time management skills
* Confidence and ability to perform effectively and make decisions with minimal management oversight
* Ability and desire to effectively mentor others and contribute to a collaborative team environment

## Why it would be awesome to work with us:

* Competitive salary
* Frequently review 
* Working from 08:00 am to 05:00 pm, Mon to Fri only
* Flexible public holiday exchange
* Premium health care insurance
* ITC welcome package
* Soft skills improvements 
* Career development path

## Interesting Engineering Projects:

* The ITC development team is composed of developers from junior to senior, working with different strengths. In a dynamic, multi-project and multi-timeline environment, ITC needs someone with proven leading skills to liaison with our CTO, Project Director and team in order to constantly improve our team, our processes and our delivery.
* You will work side by side with some of the most influential minds in the digital world, and approach the latest trends of advanced technologies. You will get great mentoring and chance to practice in order to enhance your skills with solid process & techniques.
  * Opportunity to engage in projects  with Fortune 500 clients as well as promising startups
  * Develop a fine-tuned view of what you want for your future professional career
  * Strong professional skills from mentorship developed by working alongside CTO and COO
  * Performance based career evolution

## Contact:

Homepage: it-consultis.com

Email: ninh.nguyen@it-consultis.com

**Comment by qcam** [comment]
Hey @tguillemaud, just wondering if it would make sense to group this job with https://github.com/awesome-jobs/vietnam/issues/634 with a title like  "PHP technical leader"? "Laravel Technical Leader" and "Magento Technical Leader" sound too much specific to me.

**Comment by tguillemaud** [comment]
Hi @qcam 

I'm actually looking to find two distinct candidates. Would that work for you?

Thanks
