### ISSUE TITLE
JAVIS - Freelance remote part-time php developer - Hanoi

### ISSUE THREAD

**Issue by YoshinoriTone** [awesome-jobs/vietnam#637]
## Location

* Hanoi, Vietnam ( Landmark 72 )
* Remote

## Salary Expectation

* 80,000 VND / hour ~. Each task has expected time(hour). We will pay for tasks you finished calculating total hours.
* For ex, The task expected hour is 3, if you finished in 2 hours, you can take fee for 3 hours.  
* You can start immediately.

* Your first project is to improve style of existed website (CakePHP).
* We have some projects and getting more. If you are good, we will ask continuously. ( we will invite you to our slack community 😸 )

## Requirements

* PHP  (CakePHP)
* MySQL
* html, css coding
* Bootstrap
* 3+ years Software Engineering experience

### Must Have

* git ( git flow )
* English communication.
* professional mind.
* communication frequently
* never mind to use japanese characters on product. ( of course we can translate )

### Ideally

* Experience with redmine.
* Knowledge about docker.
* Have experience with CodeIgniter and CakePHP

### Responsibilities

* Clean code and commit
* Follow spec strictly

## Contact

Homepage: https://www.facebook.com/javisenterprise/
yosinori.tone@gmail.com

**Comment by nathanphan** [comment]
wow it is 80 THOUSAND per hour haha

**Comment by cuonggt** [comment]
80,000 VND / hour ~ Unbelievable :D

**Comment by TanNgocDo** [comment]
Amazing Price. LoL :D

**Comment by YoshinoriTone** [comment]
Of course please negotiate with us if not satisfied. It is minimum fee.

**Comment by vtgroupvn** [comment]
do you ready to open new contractor?
