### ISSUE TITLE
Human Benefits - Lead Dev - Saigon - FT

### ISSUE THREAD

**Issue by jbk2** [awesome-jobs/vietnam#643]
## Location

* Saigon, Vietnam

## Salary Expectation

* Negotiable pending experience.
 
## Requirements

* 2 developers req’d
* 4yrs+ commercial experience Ruby/RoR
* Full stack, but back end lean
* Usual small scale DevOps
* Testing

### Must Have

* Great communication skills and technical fluency in English.
* Application architecture experience.

### Ideally

* Lead dev + project mgt experience.
* Experience with complex crawl & scraping, state machines, APIs.

### You’ll be responsible for

* Lead dev for completion of a 50% pre-completed code base.
* Working as lead dev with product owner as junior dev.
* Working with one or two other developers and an external part time designer.

### You can bring

* Eye for design, head for efficiency.

### Why it would be awesome to work with us.

* Lead development of the entire product.
* Work across a range of business problems and required technical solutions.
* Work with a fun mini team with a knowledgeable and fun product owner.
* Potential opportunity to build and lead the Vietnam dev office for the company.
* Some remote, some office based work.

### Interesting Engineering Projects

* External Rails 5.0.3. crawling and scraping API app.
* Main Rails 4.2 app, multiple external API integrations.

### Contact

Homepage: humanbenefits.com
james@humanbenefits.com

**Comment by qcam** [comment]
@jbk2 thanks for posting but we are not accepting third-party job ads for now.

**Comment by jbk2** [comment]
@qcam, thats fine, but why can't this ad be accepted? (Not sure what you mean by 3rd party, but this isn't 3rd party in the sense of some recruiter. This is for me and my company)

**Comment by qcam** [comment]
@jbk2 that sounds fair enough. I was confused by the company being "Bibble" while the home page being "humanbenefits.com". Could you please address that?

**Comment by jbk2** [comment]
Aha understood, ok, done @qcam.
