### ISSUE TITLE
SSS - Senior Ruby Developer - HCMC - Full time or Freelance

### ISSUE THREAD

**Issue by taiphan** [awesome-jobs/vietnam#645]
https://itviec.com/it-jobs/ruby-on-rails-developer-silicon-straits-saigon-1805
## Location

* Saigon, Vietnam
* Remote or fulltime

## Salary Expectation

* $????/month or range

## Requirements
1 years experience in Ruby and Ruby on Rails framework is required.
Knowledge of UI/UX.
Solid knowledge in OOP, TDD, clean code…
Experience with unit tests and other testing methodologies
Experience in scaling and optimizing web applications.
Ability to quickly adapt new technologies.

### Must Have

* Be able to fly
* Be able to dodge bullet

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Build an responsive web voting

### You can bring

* A good eyes for design
* A good analyis skill

### Contact
Homepage: www.siliconstraits.com
Trollman: tuantai@siliconstraits.com (0909966331)

**Comment by tranquangvu** [comment]
@taiphan How i can apply for freelance position? Your posted job on itviec is expired.

**Comment by taiphan** [comment]
@tranquangvu send to my email tuantai@siliconstraits.com. Thanks

**Comment by qcam** [comment]
@taiphan Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
