### ISSUE TITLE
Product Manager

### ISSUE THREAD

**Issue by yeah1network** [awesome-jobs/vietnam#646]
## Any question more: 028 7300 6071

**Job Description**

- Do market research about Brand and Social trend.
- Analyze information collected from various data sources to identify and forecast user needs based on market trends.
- Propose new features based on product position. Design solutions for those features including wireframes and mockups with navigations, UX/UI and layouts with a user-centric mindset.Compose requirement specifications for each feature.
- Document product’s vision and project’s scope;
- Document client’s business requirements in detail, (using use cases or functional specifications) with all assumptions and caveats included
- Initiate product ideas based on statistical data and product roadmap then sell them: explain and convince team members, the management, and development teams to agree with your proposed features.
- Support UAT in testing, verifying bugs/issues with client;
- Analyze feature in product (UX/UI, document)

**Requirements:** 

- Have knowledge about Social Listening, Influencer Market, Digital marketing
- A mobile app and website geek: familiar with well-designed, especially communication.
- Able to use mockup software (i.e. Balsamiq) to design UX/UI, layout and navigation flows.
- Have a superb critical reasoning skill: able to strengthen or weaken arguments based on logics.
- Communicate with impact: able to explain complex problems in one or two sentences.
- An attention to details and a never-satisfying attitude: able to pick out small discrepancies in layout design and propose solutions.
- Can read and write in English
- At least 2 years  experience works as Product Manager Role.
- Proven ability to document business requirements in an accurate, unambiguous and succinct fashion
- Problem-solving.
- Demonstrated ability to plan and conduct research in close collaboration with people in a variety of roles, including design, engineering, and product management.

**Comment by qcam** [comment]
@yeah1network Thanks for posting.

Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), it must be in valid Markdown format and all `REQUIRED` section must be filled.
