### ISSUE TITLE
Junior Web Developer

### ISSUE THREAD

**Issue by yeah1network** [awesome-jobs/vietnam#647]
## District 3, HCMC

* Saigon, Vietnam
* Full time

## Salary Expectation

* $700/month

## Requirements
- At least 2 years experience in web development.
- Experience with multiple programming languages(Python, Ruby, Go,...). Python must have
- Experience with Redis, Elasticsearch have knowledge about Caching is a plus.
- Experience integrating with third parties (Youtube, Facebook, Payment gateway,...)
- Experience with web API technologies: RESTful, Authentication, Authorization, and multi devices session.
- Experience with Postgresql other (Mysql, NoSQL,...) is a plus
- Experience with version control (Git)
- Experience with frontend work: HTML/CSS, bootstrap, SASS,...
- Have knowledge about Video Streaming is a big plus.
- Ability to quickly master new technologies and push the envelope for performance and reliability.
- Experience with Agile (Scrum or Kanban)

## Why You'll Love Working Here
- Competitive salary, various bonus and raise base on your performance.
- Work with the online video leading of Asia and International partners.
- Have chance to work with Vietnamese and International stars as well as top Asian Vbloggers.
- Opportunity to be promoted to higher position.
- Participate in training courses by Prof.
- Explore your capacities and abilities when work in an active, creative, fast moving environment.
- Enjoy working time with daily coffee, snacks, massage chair, cinema tickets and special shopping voucher.
- Company trip, travel once per year.

##How to apply
Please submit your resume to our email: tuyendung@yeah1.vn

**Comment by qcam** [comment]
@yeah1network 
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
