### ISSUE TITLE
MIC International Lab - Fresher Ruby on Rails - Full Time - Ho Chi Minh

### ISSUE THREAD

**Issue by jackyvo** [awesome-jobs/vietnam#650]
## Location

* 661/3, Nguyen Kiem, Phu Nhuan, Ho Chi Minh City

## Salary Expectation

* $500 - $1000/month

## Requirements

* Web development experience
* Solid understanding of object-oriented programming
* English: Intermediate level or above
* Proficient in Bootstrap, JQuery, CSS3, HTML5

## Skills

* PHP or Ruby on Rails
* Angular, Ember, React, Backbone
* Git version control

### Responsibilities

* Design, build and maintain efficient, reusable, and reliable Ruby code
* Analyze client requirements to develop functional and technical software requirements
* Setup environment and release web applications
* Contribute in all phases of the development lifecycle
* Drive continuous adoption and integration of relevant new technologies into design
* Conduct code refactoring, optimization
* Perform other technical tasks assigned by the PM

### You can bring
* Whatever you love. Feels free to be at home

### Why it would be awesome to work with us
* We are young, creative and full of power
* We are looking for key members for new team and long-time working relationship
* We are building the best working environment for all developers

### Contact
Homepage: www.micslabs.com
Contact me An: jackyinvn@gmail.com - 01682931518

**Comment by qcam** [comment]
@jackyvo Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
