### ISSUE TITLE
VE Source Magento Developer Ho Chi Minh City FT

### ISSUE THREAD

**Issue by i-lean-dev** [awesome-jobs/vietnam#651]
## Location

* Saigon, District 2, Thao dien, Vietnam
* On Location (partly remote allowed)

## Salary Expectation

* $700-1500/month depending on experience level

## Requirements
* PHP (OO) 3+ Years
* Magento 1 experience: 2 years experience or 10 projects
* Magento 2 experience: 6 months+ or 2 projects
* Knock-Out JS/Angular JS experience 1+ years
* Html experience: 4+ years.

### Must Have

* Be able to work in a team
* Be able to work on location District 2 Thao Dien
* Know how to work within a GIT environment

### Ideally (extras)

* Experience with Wordpress is a pre
* Experience with Zend is a big pre
* Good english speaker, excellent english reader.
* Apache server knowledge
* JIRA knowledge

### Responsibilities

Developing Magento 2 webshops for clients all over the world together with our team of Magento specialists. 

### Why it would be awesome to work with us

We are a family like company with high profile clients. There is a lot of work to do, but in our Dutch (English spoken) environment there is low stress and room for your opinion. We'd love for you to join our family friendly work style! Remote working can be requested for up to 3 days a week. We have free small snacks and drinks including noodles. We also have a pool in the nice villa we all work in. Company trip 1x a year and 13th (tet) bonus.

### Contact
Homepage: vesource.nl
HR: guido@vesource.nl

**Comment by qcam** [comment]
@i-lean-dev 
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
