### ISSUE TITLE
Senior PHP Developer - Malaysia - Full time

### ISSUE THREAD

**Issue by uyentran07** [awesome-jobs/vietnam#652]
## Location

* Selangor - Malaysia

## Salary Expectation

* $1300 - $1800/month

## Requirements

* Bachelor’s Degree in Computer Science or any related discipline preferred
* Must have at least 3 years working experience.
* Advantage if familiar with PHP framework: Lavarel, Symfony, CodeIgniter, Yii etc.
* Advantage if familiar with, Retail System, Inventory System, Shopping Cart System
* English or Chinese speaking

### Must Have 

* Strong in PHP programming, MYSQL Database
* English or Chinese speaking

### Ideally

* Advantage if familiar with, Retail System, Inventory System, Shopping Cart System

### You’ll be responsible for

* Build efficient, testable, and reusable PHP modules.
* Coordinate with the rest of the team working on different layers of the web application.
* Develop and support the following:
1. Direct selling projects
2. Reward and referral system
3. Mobile app backend  

### Why it would be awesome to work with us

* 14 days annual leave + Malaysian National Holidays
* Fully subsidised Sportsclub 
* Fully subsidised Car Parking
* Gym, Kitchen, Massage Chair, Bar counter, Table Tennis, TV, Games, Refreshments etc..
* Company will provide accommodation (5 minute walk to work-place), Visa, Work Permit.
    
### Interesting Engineering Projects

* Develop and support the following:
1. Direct selling projects
2. Reward and referral system
3. Mobile app backend  

### Contact
Homepage: vipsearch.com
Ms Uyên: uyen_dot_tran_at_vipsearch_dot_com (0933697659)

**Comment by nathanphan** [comment]
Hi Uyên, can I have more information on this?

**Comment by uyentran07** [comment]
Hi nathanphan, bạn vui lòng để lại sdt hoặc email, Uyên sẽ gửi thông tin chi tiết nhé! Thanks

**Comment by nathanphan** [comment]
please add me https://www.linkedin.com/in/phanhuungoc/

**Comment by qcam** [comment]
@uyentran07 
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.

**Comment by uyentran07** [comment]
@qcam  thank you and please check again!
