### ISSUE TITLE
R&D Software Engineer 

### ISSUE THREAD

**Issue by huyenho2512** [awesome-jobs/vietnam#653]
## Location

* Saigon, Vietnam

## Salary Expectation

* USD 1000 - USD 2000

## Requirements

* Bachelor’s degree in Computer Science or equivalent knowledge and skills 
* Proficiency in at least one modern programming language (C#, Java, C++, Python,...) 
* Knowledge of algorithms and data structures 
* Real passion for programming 
* Desire for continuous learning and intellectual challenges 

### You’ll be responsible for

* Design and implementation of new features to our flagship product: Cortex 
* Choose projects to work on based on your preference and strengths: back-end API, machine learning, cloud storage, security, client-facing interfaces, web services, DevOps
* Take ownership of projects entirely: from design, implement to release and maintenance 
* Participate in the ongoing optimization of our methodology, to ensure quick and quality results 

### Why it would be awesome to work with us

* 18 days annual leave
* A very competitive salary and benefits 
* 13th-month salary + bonus 
* Nice, modern office with state-of-the-art equipment: powerful machines, multiple screens, high quality ergonomic chairs, etc. 
* Lunch & parking allowance 
* Healthy snacks, fresh food, coffee provided 
* Premium health insurance with gym tickets and other fitness perks sponsored 

### Contact
Homepage: https://www.orangelogic.com/
Trollman: huyen.ho_at_orangelogic_dot_com (0935 833 329)

**Comment by qcam** [comment]
@huyenho2512 Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
