### ISSUE TITLE
Spout360 - QA / QC / Software Tester - HCMC - Full-time

### ISSUE THREAD

**Issue by dominhquan** [awesome-jobs/vietnam#659]
## Location
* 88 Huỳnh Văn Bánh, phường 17, Phú Nhuận, Hồ Chí Minh, Việt Nam (BIGWork – Ho Chi Minh)

## Salary Expectation
* Negotiable

## Requirements
- Good experience in manual testing for web-based and standalone applications
- Good experience in writing new test cases based on requirements
- Ability to effectively manage time, and individually prioritize multiple tasks of competing priority
- Experience in developing, documenting and implementing quality assurance standards
- Experience with cross browser, cross platform and responsive testing (PC, mobile and tablet)
- Good oral and written communication skills

## Responsibilities
- Develop, maintain and execute manual test cases for major projects, maintenance, and emergency releases
- Design and implement automation tests scripts, debug and define corrective actions
- Identify, analyze and report test results
- Report, track, and monitor defects in the defect tracking system
- Investigate defect reports from production support and isolate their causes
- Prepare test documentation and review with development team
- Work closely with development team to design testing strategies
- Work on the interpretation of quality assurance issues and problems for technical and non-technical users

## Ideally
* Enjoy working in a start-up and open environment
* Take pride and ownership in your work
* Self motivated and can work well under pressure
* Team player, doing anything and everything needed to get things done

## Why it would be awesome to work with us
* You’ll have the chance to build world-class products for millions of people around the world.
* Laptop / External Monitor is provided
* 15 days annual leaves.
* Opportunities to travel to SPOUT ENTERTAINMENT PTE LTD located in Singapore.
* Annual salary review & 13th month salary based on performance
* Annual cohesion trip and team building activities.   There is always strength in numbers and certainly greater power in united people. We believe in taking time off work to recharge and refresh so that we can come back as a more united team.

## What are hard problems that we're trying to solve
* SpoutPay - The universal e-wallet for gamers in Southeast Asia. SpoutPay allows users to elevate their gaming experience by utilising a digital credit platform to pay for games, F&B, premium content as well as to earn rewards.

## What do you need to apply?
* Your CV (English)

## Contact
* Email : `hr@spout360.com`

**Comment by chuyencuadev** [comment]
Vui lòng ghi benefit chính xác nếu không sẽ bị bóc phốt!

**Comment by qcam** [comment]
@chuyencuadev Bạn vui lòng đưa ra thông tin giải thích cho lời bình luận của bạn, nếu không mình sẽ xem đây là một hành vi bôi nhọ và sẽ block bạn.
