### ISSUE TITLE
Ruby on Rails Developer

### ISSUE THREAD

**Issue by inspire2017** [awesome-jobs/vietnam#661]
**Summary of Opportunity**

- Title: Ruby on Rails developer
- Rank: Developer
- Position: Full-time
- Length: Long-term

**You should be best at**

- Ruby
- Ruby on Rails
- English - Good

**What You Will Do (Job Description)**

- You love product development and see your features and ideas being implemented and used by thousands of users everyday.
- You will join a young, winning and regional team working on disruptive technologies.
- You will work closely with the regional teams (product, businesses) to see user’s and business teams feedback and provide solutions to improve your own product.
- You will work in Agile/Scrum environment.

**Job Requirement** 
_MUST-HAVE_

- At least 3 years experience as Ruby on Rails developer
- Experience with web front-end such as HTML, JavaScript, CoffeeScript, CSS, SASS, jQuery.
- Experience with Restful API
- Experience with cloud server
- Experience with Postgres, MongoDB.
- Experience with GIT/Bitbucket source control system
- Good English verbal and written communication skills

_NICE-TO-HAVE_

- Experience with  Angular JS, React JS is a plus
- Experience with Firebase is a plus
- Good English verbal and written communication skills

**How to Apply**
Please submit a brief email to Mr Duke Nguyen : duke@deliveree.com with following documents :
- Resume
- Marksheet/Transcript
- Fill up the preform here: https://drive.google.com/open?id=0B1FqbgL_N0nNmJBTHJtcHlPMWM

**Comment by viphat** [comment]
The form is not found. I think it's not a correct link.

**Comment by qcam** [comment]
@inspire2017 Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
