### ISSUE TITLE
Yojee - React Native Mobile Developer - Saigon - FT

### ISSUE THREAD

**Issue by vnnoder** [awesome-jobs/vietnam#668]
## Location

* Saigon, Vietnam

* Potentially relocated to Singapore

## Salary Expectation

* Competitive remuneration

We are seeking a mobile developer is a qualified candidate to join our Engineering team, to develop and maintain high-quality mobile applications and support the entire application lifecycle. This candidate also appreciates the notion that running their efforts will enable enhanced logistic services for potentially millions of users across a wide variety of industries.

## About Yojee

We built software that uses artificial intelligence (AI) and the blockchain to help logistics businesses coordinate their fleets and make the most out of existing last-mile delivery infrastructure. The system, powered by machine learning, automatically assigns delivery jobs to drivers, reducing the need for a human dispatcher. This lowers costs for logistics providers and makes deliveries faster for customers. It also uses a blockchain to track and archive transactions and deliveries so they can always be verified if necessary.

We are not a startup although the company structure is organized in such a way. Yojee is a public listed company on Australian stock exchange (ASX: YOJ), our stock has tripled over the last 12 months. We are building a team in Vietnam to develop the core product and we expect the team to grow quickly. Don't miss this opportunity to join us early.

## Responsibilities:

* Design and build advanced logistics applications for the mobile apps / platforms 

* Collaborate with cross-platform and product development teams to define interfaces and ensure feature interoperability; 

* Write in unit-tests, integration tests, and interoperability test for our SDK and applications built on our SDKs;

* Identify performance improvements and efficiency optimizations for implementation, build, and deployments of the technology;

* Implement UI from specifications provided by the UX/UI team;

* Act in a developer support role for those implementing using our SDKs or WhiteLabel applications; 

## Job Requirements

* Bachelors’ Degree in Computer Science or Computer Engineering in education or its equivalent related experience. 

* Experience working with Javascript and React Native

* Min. 4-5 years’ relevant work experience

* 2-3 years’ relevant work experience in mobile development (Android/iOS)

* Existing apps in app store or play store with considerable usage would be a huge bonus.

* Excellent understanding of the full mobile development life cycle

* Experience working with Git

* Effective written/oral communication skills and able to communicate ideas effectively to a corporate audience and excellent interpersonal skills

* Able to work independently, self-directed and solutions-oriented

* Speak English fluently, proficient in written English

## Contact

Please drop us an email at `1011011010010110001011101000011001110110100001101100011000000010111001101011011010000110100101100011011001110100110001101111011010110110` or call at `0000110010001100011011001100110001001100111011000000110001101100111011001100110000001100` if you're interested.

**Comment by haconglinh1990** [comment]
Is this a correct code ???, 
That binary code has no meaning !!!, 
Can you give me some suggest ???
