### ISSUE TITLE
 Magic8Labs - Senior Python / Large Data Cawler Engineer - HCM - Full Time

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#672]
## Location
572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City

## Salary Expectation

*	Up to $1500/month

## Requirements

*	You love Python
*	You are interested in data farming and Crawlers 
*	Want to master scraping methodologies and frameworks, and ways to control these with tools like Celery and RabbitMQ. 
*	You are a Team Player, open minded.
*	You can code on back-end and not afraid to make mistakes and you can laugh at yourself.
*	You love challenges.

## Skills

*	Python 
*	Django 

## Must Have

*	Senior Level experience with Python
*	Senior Level experience with Django, JQuery
*	Would be great if you have experience with Celery / RabbitMQ

## Responsibilities

*	Work on Back-end Python Crawler 

## Why it would be awesome to work with us

*	Friendly, flexible, and fun working environment.
*	Salary review every year or on performance review.
*	We pay for courses you want to take.
*	Laptop provided if you need one.
*	Product equity sharing opportunity. Make money as partner on the tool we developed up to 4%.
*	Free lunch everyday.

## Interesting Engineering Projects

At Magic8Labs we are making our own software products. Our current niche is SaaS Software for amazon sellers. We have are tackling issues dealing with Distributed Web Crawlers, crafting real time large user systems. 

## Contact

Email: Nick Mavridis , mavridisn@magic8labs.com
Email: Quynh Kim, quynh.kimthinhu@gmail.com
Facebook: https://www.facebook.com/nick.mavridis.1

**Comment by euronck** [comment]
please admin don't close. Let me know what is wrong and I will fix thanks :)

**Comment by qcam** [comment]
@euronck Could you specify whether this is a full-time / part-time / contract job on the title please? https://github.com/awesome-jobs/vietnam#title-format

**Comment by euronck** [comment]
Full time.. 

 

Thanks Cam for fixing it

**Comment by euronck** [comment]
its full time Cam. thanks for fixing it
