### ISSUE TITLE
Ruby Development Vietnam - Fullstack Ruby on Rails - Hanoi - FT

### ISSUE THREAD

**Issue by h-dang** [awesome-jobs/vietnam#673]
## Location

* 15th floor, Icon 4 Building, 243A Đê la Thành, Láng Thượng, Đống Đa, Hà Nội, Vietnam

## Salary Expectation

* $800 - $1,500

## Requirements

* 2+ years exp working with Ruby, Rails, javascript
* Hands-on exp with Angular 1/2, reactjs, Vue.js
* Be able to read and write in English

### Must Have

* Excellent understanding of MVC, ORM, RESTful, OOP
* Good knowledge of Ruby, Ruby on Rails, javascript
* Good teamwork
* Experienced with Mysql
* Experienced with one of morden javascript framework: Angular 1/2, Reactjs, Vue.js
* Experienced working in agile development process

### Ideally

* Good knowledge about software testing, automation testing (Rspec, Capybara)
* Experienced with responsive web development
* Experience with HTML/CSS
* Familiarity with PostgreSQL, MongoDB, Amazon Web Service, GitLab, CircleCI, CodeClimate
* Be able to communicate in Japanese

### Responsibilities

* Analyze client requirements to develop functional and technical software requirements (outsourcing projects)
* Contribute in all phases of the development life-cycle
* Code refactoring, optimization
* Participate in our product projects
* Participate in OSS projects

### Why it would be awesome to work with us

Ruby Development's projects bases on Ruby on Rails framework and using various technologies including Cloud Computing, and follow the agile management process.
You will work as a full-stack developer, participate in all development processes which leaded by our specialists. 
Our headquarter is based in Tokyo, Hanoi is the lastest office which we can offer: 

* Professional and creative working environment
* Opportunities to relocate to Japan (short-term or long-term in one of our company's branch offices)
* Opportunities to develop highly efficient and high quality web services using latest technologies
* High opportunities to be key members including technical leaders and project managers
* We would love to create an environment where you can develop yourself and have fun~
* You will be supported to learn and improve your skills

### Working in Japan

* As your desire, we willingly relocate you to Japan when you reach our technical skills target and Japanese level (you can choose one of our 4 branch offices in big cities including Tokyo, Osaka, Sendai and Fukuoka)

### Contact

Homepage: http://ruby-dev.jp
hr@ruby-dev.jp
Please kinldy write down in your email title: `[Vietnam] - yourname - fullstack Ruby on Rails` 
Example: `[Vietnam] - PhucBD - Fullstack Ruby on Rails`

**Comment by h-dang** [comment]
excuse me, is this job reviewed or waiting? thanks~

**Comment by duet-ngyen** [comment]
Excuse me, is this job openning?

**Comment by h-dang** [comment]
@duet-ngyen yes~

**Comment by HaChan** [comment]
@h-dang Job còn open ko anh ?

**Comment by h-dang** [comment]
@HaChan còn em 😄  a có fb messenger của e chưa nhỉ? hay skype cũng dc

**Comment by HaChan** [comment]
@h-dang skype em la hades.24791 
add ho em nhe :smile:

**Comment by buithehien1991** [comment]
@h-dang jobs còn không anh. nếu còn add nick skype em là: buithehien1991  :)

**Comment by h-dang** [comment]
@buithehien1991  còn e nhé, a hoặc a manager sẽ contact e nhé :)

**Comment by b-phuc** [comment]
@buithehien1991  Cảm ơn em đã quan tậm. Em gửi CV vào mail b-phuc@ruby-dev.jp cho anh nhé :)

**Comment by HoangTuyetUET** [comment]
@h-dang có tuyển sinh viên mới ra trường không a? :)) arigatou

**Comment by b-phuc** [comment]
@HoangTuyetUET em gửi CV sang cho anh b-phuc@ruby-dev.jp
