### ISSUE TITLE
[MySQUAR] PHP Engineer - HCMC 

### ISSUE THREAD

**Issue by hoadth** [awesome-jobs/vietnam#674]
## Location

246 Cong Quynh, District 1, HCM, Vietnam
## Salary Expectation

500$ - 900$
## About Job
https://careers.mysquar.com/php-engineer/
MySQUAR is a mobile app company exclusively focused on bringing high quality mobile products to Myanmar people. Your talents will contribute to our products more and more different.
We are also a big premium online games publisher, MyGame with increasing number of game as listed here http://mygame.mysquar.com/.

- We love challenges, we love to learn new things every day. If you do too, we would love to work with you and here is the job:
- Write clean, well designed code with PHP
- Develop features for our site. The products must have the best performance.
- Research and apply best practice tools and technologies
- Work in a highly productive and collaborative team where your ideas will be listened to and actioned
- Takes ownership of assigned work
- Analysis requirements and maintain technical documentation.
- Participate to all phases in product development process including analyzing user requirements, designing system architecture, coding, testing and deployment.

## Requirements

- At least 1 year experience
- Has general knowledge about other fields ( Java , etc )
- Strong background in PHP Development, SQL databases (preferably MySQL)
- Experience in Web Application technologies like HTML, CSS, JavaScript
- Has knowledge about OOP and MVC, Design patterns
- Work both independently and teamwork
- Willingness to learn new technologies both by training and self-learning.
- Familiarity with web-services, either JSON- or XML-based or both

## What you get

- Love from the team. We are very friendly.
- Competitive salary and annual bonus.
- Full healthcare benefits
- Training program for soft skills and management skill.
- Team building and reward budget for teams.
- Annual company trips and parties
- Free snack and fruit everyday, enjoy happy hour party monthly.
- Possible travel to Myanmar to meet users and the team
- Lots of cool stuff to relax (who said Foosball?)
## Contact us

**Would you like to know more? Resumes and questions, please get in touch with hieuhoa@mysquar.com, or skype ID: hoahieu1705 - Ms. Hòa for more information.**

**Comment by rebyn** [comment]
mySquar started out with Ruby, I believe. Is there a writeup somewhere re: your decision to move to PHP?

**Comment by xluffy** [comment]
@rebyn I think PHP engineer for another product, not for OTT. Btw,I read a post from a Tech Lead Mysquar at https://www.facebook.com/groups/1947000132181181/permalink/1961295777418283

**Comment by qcam** [comment]
@hoadth Could you please revise the title and description to match our format?
