### ISSUE TITLE
JobReady (since 1997) - 05 Ruby Developers - Nha Trang/Remote - FullTime

### ISSUE THREAD

**Issue by rauxalach** [awesome-jobs/vietnam#675]
![jobready](https://user-images.githubusercontent.com/1320349/30145666-23a266da-93bd-11e7-8397-e4ff30a5eb43.jpg)

## Location

  Nha Trang city. (VN Head Office)
  Ho Chi Minh city. (Remote)

## Salary Expectation

Depends on what you capable of (up to $2000 AUD)

### MUST HAVE
* Ruby
* Ruby On Rails framework
* PostgreSQL / MySQL
* 5+ years Software Engineering experience
* Strong background in object-oriented software development

## Skills
- Be able to communicate and write in English
- Ability to understand and debug large and complex code bases
- Be able to write unit tests and maintainable code

## Responsibilities

We're looking for best engineering to further fuel this transition.

You will join our team in Vietnam and work closely with Australia team to design, implement and support our web applications.
- Maintain current web applications using by our 250+ clients
- Building features to a high quality bar using Ruby on Rails
- Be swapped between projects to maintain and develop new features

### Why it would be awesome to work with us

- We work closely with every member of the team, to help them define their own path for personal and professional development.
- We embrace remote work. We focus on finding the best people, regardless of where they live.

This is a great opportunity to get in to a rapidly growing and passionate software company.

### Contact

Huy Le: huyl at jobready.com.au (0908.108.625)

**Comment by Gnouc** [comment]
@rauxalach Is knowledge about Ruby without ROR acceptable?

**Comment by rauxalach** [comment]
@Gnouc Our wep app solutions are 100% RoR based. However it is considerable for candidates having good Ruby and OOP skill, other Web framework programming experiences, be able to write spec.

Thanks.
