### ISSUE TITLE
LARION - Japanese IT Communicator - Saigon - FT

### ISSUE THREAD

**Issue by Lytructran** [awesome-jobs/vietnam#684]
## Location
* 3rd Floor, QTSC Building 1, Street 14, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, HCM City

## Salary Expectation
* $1000 - $2000

## Requirements
* Good communication skills in Japanese both verbal and written (level N2 or above)
* Good experience in using MS Office tools (MS Word, Excel, PowerPoint..)
* Highly responsible for the assigned tasks
* Proactive, creative and positive attitude at work
* Flexible in adjusting the personal priority to meet the project priority

## Skills
* N2

### Must Have
* Good communication skills in Japanese both verbal and written (level N2 or above)

### Ideally
* Having experience working with IT fields is a great plus

### Responsibilities
* Support the project team to communicate with Japanese clients, through online conferences and/or face-to-face meetings,
* Interpret and translate documents from Japanese to Vietnamese and vice versus

### Why it would be awesome to work with us
* Attractive salary and benefits (13th salary, distinguised employee of the quater and year, seniority award...)
* Performance appraisal twice a year
* Healthcare and accident insurance
* Various training on best practices and soft skills
* Teambuilding activities in every summer, company trip, big annual year-end party every year, etc.
Fitness & sports activities: football, tennis, table-tennis, badminton...
* Commitment to community development: charity every quarter, blood donation, public seminars, career orientation talks…
* Free in-house entertainment facilities (foodball, table tennis, boxing, coffee...)
* Support for personal loans such as: home loan, vehicle loan, tuition fee...

### Interesting engineering projects
* We provide full-stack services of Ruby on Rails Application Development. Generally, our Ruby on Rails Application Development Services consist of Web App Development and Web App Maintenance.
* Saving working time by 25%, LARION helped Customer save cash, headcount and customer satisfaction with the SurroundCore Solution

### Contact
Email: recruitment@larion.com

**Comment by qcam** [comment]
@Lytructran I am closing this because I could not find this job relevant to "developers".
