### ISSUE TITLE
Senior Ruby Web Developer

### ISSUE THREAD

**Issue by btphuongnhi79** [awesome-jobs/vietnam#688]
We're looking for a talented individual to join us at YOOSE Saigon office to be part of Development team. 
Do you have experience with eloquent Ruby on Rails design? Can you develop complex web based applications? Do you love building cool tech and coding? Consider joining our team and have an opportunity to build something from the very beginning and apply most of the latest technologies such as: Ruby on Rail, React, NodeJs, Redis, MongoDB and AWS services to create the core technology for the next successful startups in Vietnam and Asia. Our headquarter is located in Singapore (www.yoose.com) 

Role
You will be the senior Ruby developer to create the majority of our user interface for a web application facing, big data and marketing platform. You will be expected to create awesome, interactive and compelling front end Ruby on Rails interfaces into our framework. Additionally as we build the team out, you will also be expected to utilize your design along with the legacy system and operationally support the environment.

Skills Expected
● Web Application Development
● 5+ years in Ruby is the most preferred
● GIt
● Agile Development / Scrum
● Good understanding of written English

Skills that are Nice to Have
● JQuery & Ajax, NodeJs, React, AngularJS
● Big Data, MongoDB, Redis
● Twitter Bootstrap
● Release Automation
● Automated Testing
● Amazon Web Services or other Cloud Providers
● Open Source Development

Benefit

• Attractive net salary, based on skills and experiences 
• 13-month salary bonus. 
• Yearly company trip 
• Private Medical Insurance will be paid by the company (beside the compulsory government medial insurance) 
• Work onsite in head office if necessary
• Working time: Monday to Friday (9 a.m to 6 a.m) 
• Very friendly colleagues, global and professional working environment

Contact
Please send your CV by attached files to phuong.bui@yoose.com

**Comment by qcam** [comment]
@btphuongnhi79  Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)?
