### ISSUE TITLE
Vincere - Front-end Developer - Saigon - FT

### ISSUE THREAD

**Issue by nellyhuynh** [awesome-jobs/vietnam#689]
## Location
21 Nguyen Trung Ngan, District 1, Sai Gon, Viet Nam

## Salary
Negotiate 

## About us

Vincere is an award winning tech startup with offices in Singapore, Vietnam and Sydney, Australia.  We have almost 400 customers across 42 countries around the world. Our Development center is based in the buzzing city of Ho Chi Minh. We don’t take orders from other developers in the US or Australia, we make all of the development decisions in-house in HCMC, and due to this unique experience we have some of the best devs in our market. Due to our crazy global growth, we need more like minded developers to join our team and experience the freedom and responsibilities of working with a world class team. 

**Learn more about us:** https://vincere.io/

Our front-end developers are required to implement gorgeous interfaces that users fall in love with; work closely with the Business Analysts, Developers, QC, Operations teams and the Project Manager. Also he or she has to stay on top of industry issues and trends, and take a hand in introducing what they've learn and get involved in architectural discussions and decisions, and provide innovative new ideas.

## Responsibilities:
* To produce (HTML/CSS/JS/AJAX), modify and maintain website and web application user interfaces. You will also be required to design wireframes and UX for applications.
* To create interactive user control over the software thru multiple interfaces (mobile, tablet PCs, Monitors) and cross browsers.
* To ensure Design Guideline is followed and to maintain the same design branding throughout the applications.
* Working closely with designers you’ll use semantic mark-up language like XTMTL/CSS to turn static Photoshop designs into working browser-based web pages.
* You’ll also work closely with Server-side developers and Marketing team to implement their server-side code in order to develop complex, interactive and database driven websites.
* Work in Java/PHP environment for the front end scope only

### Must Have
* In-depth knowledge of JavaScript, jQuery, Ajax
* Experience with KENDO UI, jQuery (AngularJS, NodeJS)
* Enjoy integrating with server-side APIs to produce dynamic web applications.
* Experience with a JavaScript application framework such as Backbone, Angular, Ember or React.
* Experience working with CSS pre-processors such as LESS and SASS. 
* Attention to detail especially in ensuring the web components are laid out perfectly with the agreed alignment
* Working with version control systems such as Git.
* English & Vietnamese proficiency is a must.
* Basic knowledge of image authoring tools, to be able to crop, resize, or perform small adjustments on an image. Familiarity with tools such as as Gimp or Photoshop is a plus.

## Contact:
You can apply online at: https://jointheteam.vincere.io/careers 
or send your cv to: applications@vincere.io

**Comment by qcam** [comment]
@nellyhuynh  Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
