### ISSUE TITLE
Magic8Labs - Node.JS Developer - HCM - Full Time

### ISSUE THREAD

**Issue by euronck** [awesome-jobs/vietnam#693]
## Location
572 Le Quang Dinh, Go Vap, Ho Chi Minh , Ho Chi Minh City

## Salary Expectation

*	Up to $1500/month

## Requirements

*	Strong HTML5, CSS3, Javascript skills,Nodejs, Bootstrap, jQuery
*	Good to have experience in Meteorjs, Angularjs, Reactjs
*	Have at least 1 year experience with any Javascript framework 
*	You are a Team Player, open minded and love challenges.
*	You can code on back-end and not afraid to make mistakes and you can laugh at yourself.
*	English in listening & speaking is a plus. But not necessary. (you will learn here by talking)

## Skills

*	Node.JS
*	MongoDb

## Must Have

*	Experience with Node.JS

## Responsibilities

*	Work on Back-end Node.JS and Meteor on a real time application 

## Why it would be awesome to work with us

*	Work with American Founder on a product that is in demand and isn't in risk of failing.
*	Friendly, flexible, and fun working environment.
*	Salary review every year or on performance review.
*	We pay for courses you want to take.
*	Free lunch everyday.
*	Generous time off.

## Interesting Engineering Projects

At Magic8Labs we are making our own software products. Our current niche is software for amazon sellers. We have are tackling issues dealing with Big Data, Web Crawlers, Crafting real time large user systems.  Easter Egg: Cookie Monsters hired on the spot.

## Contact

Email: Nick Mavridis , mavridisn@magic8labs.com
Email: Quynh Kim, quynh.kimthinhu@gmail.com
Facebook: https://www.facebook.com/nick.mavridis.1

**Comment by euronck** [comment]
admin please don't close let me know whats wrong and i'll fix it.. Software bugs aren't the only things i fix. :)

**Comment by sonnguyenvan** [comment]
Good job . Good company

**Comment by giangnm** [comment]
$15000/month?

**Comment by daniel93cs** [comment]
Haha

**Comment by euronck** [comment]
yes thats how we roll Giang... we start you off at 15,000 a month then drop you down to 1,500 and if you lucky you get to 0.  I never was good at math but i was great at business math.

**Comment by Anphamthanh** [comment]
I think everybody going to get a special promotion from 15,000/month to 1,500/month on their first day of the job. I like your compensation model. :-)

**Comment by T-Pham** [comment]
Eh. Is math related to science? Asking for a friend.

**Comment by euronck** [comment]
math is indirectly but proportionately to science. In my case math is square root of pain in the butt. Even if I have a undergraduate degree in it from a 4 year university.
