### ISSUE TITLE
05 C# WINFORMS DEVELOPER - Evolable Asia 

### ISSUE THREAD

**Issue by NguyenVuDieuLien** [awesome-jobs/vietnam#696]
# **Job description**
– Triển khai các giải pháp về thông tin người dùng bằng việc thực hiện và bảo trì các thành phần (component) cũng như các giao diện (interface) trên nền tảng .NET
– Tham gia vào quá trình phân tích, thiết kế và phát triển hệ thống
– Thiết kế và review source code cho team

# **Location**

Da Nang, Vietnam
# **Salary Expectation**

$500 ~ $700
**Must Have**

– Tốt nghiệp đại học, cao đẳng chuyên ngành IT
– Có ít nhất 1 năm kinh nghiệm về lập trình trên nền tảng .Net, C#
– Thao tác tốt với HTML, CSS, Javascript, Jquery
– Có kinh nghiệm về lập trình Windows app và Windows Phone app là một lợi thế
– Ưu tiên các ứng viên có kinh nghiệm làm việc với WPF, SQL Server
– Chăm chỉ, tinh thần trách nhiệm, giao tiếp tốt;
– Khả năng làm việc độc lập, teamwork và chịu áp lực cao;

# **Benefit:**
– Mức lương cạnh tranh tương xứng với khả năng và kinh nghiệm
– Thời gian làm việc 8:00~ 17:00, nghỉ thứ 7, chủ nhật (no OT)
– Điều chỉnh tăng lương 2 lần/năm
– 13 tháng lương
– Nghỉ phép: 12 ngày/năm
– Được hưởng BHXH, BHYT, BHTN full lương theo pháp luật hiện hành
– Bảo hiểm sức khỏe Bảo Việt toàn phần mở rộng
– Làm việc trong môi trường nước ngoài chuyên nghiệp, trẻ, thân thiện và năng động
– Cơ hội thăng tiến trong công việc cao
– Tham gia lớp tiếng Nhật, tiếng Anh do công ty tổ chức; tham gia các câu lạc bộ bóng đá, bơi lội, yoga, nhiếp ảnh,…
– Khám sức khỏe định kỳ 1 lần/năm tại các bệnh viện uy tín; Du lịch, kick off định kỳ hàng quý, hàng năm

Send us the following to dieulienk34b@gmail.com.

Your CV in English
Your GitHub profile

**Comment by qcam** [comment]
@NguyenVuDieuLien could you please rewrite your job post in English?
