### ISSUE TITLE
Oracle Developer

### ISSUE THREAD

**Issue by Rvor** [awesome-jobs/vietnam#698]
## Location

* Saigon, Vietnam

## Salary Expectation
Up to $2,000 net

## Requirements

This is a truly challenging role, suited to an experienced and competent PL/SQL developer who has strong programming, analytical and communication skills supported by a proven track record of completed projects.

### Must Have

* Deep understanding of Oracle 10g/11g/12c architecture, performance tuning, bottle-neck analysis,
Strong SQL skills, ability to analyze and optimize SQL queries,
* Considerable previous experience of developing big commercial projects using PL/SQL (minimum of 3 years project experience in development),
* Practical experience in developing, implementing and supporting of IT-systems processing big volumes of data,
* Knowledge and practical experience of all development stages and types (architecture, design, prototype, system design and development, re-engineering, profiling, migration, testing, bug-fixing, acceptance),
* Ability to work in a team, knowledge of team work tools such as Jira, Subversion, Git,
* Written and spoken English; ability to author and maintain technical documentation and discuss project related matters over the phone, email and instant messaging.

### Ideally

* Payment system

### Responsibilities

* Develop and implement new software features,
* Maintain existing code,
* Carry out peer/formal reviews of source code and supplementary documentation,
* Collaborate with business analysts, testers and possibly end users,
* Report on expended efforts and status of tasks/problems,
* Follow software engineering processes and procedures,
* Contribute to best practices and internal knowledge base.

### Why it would be awesome to work with us
* Competitive salary
* Salary review 1 time/year
* Year end bonus
* Performance based bonuses
* Each 2 year add 1 annual leave day bonus
* Badminton club and other community Tech activities
* Play dart area, fresh fruit and snack every day
* Team building end of the year
* Independent and responsible work
* Work with latest developer tools
* Work in great, talented and experienced team
* Excellent career opportunities in an expanding & international team
* Onsite opportunities in Asia-Pacific area
### Contact
Homepage:  http://www.bpcbt.com/
Trollman: v.bui_at_bpcbt_dot_com

**Comment by qcam** [comment]
@Rvor Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
