### ISSUE TITLE
HTML/CSS Chopper / Frontend Developer - Outlets - Ha Noi

### ISSUE THREAD

**Issue by ngocdb** [awesome-jobs/vietnam#699]
# Job description

– Tham gia vào 1 startup về thương mại điện tử hàng đấu Singapore.
– Convert từ PSD sang HTML/CSS (HTML5/CSS3/JS), tạo các template responsive, hiển thị trên nhiều nền tảng và thiết bị (desktop, mobile, tablet,...).

# Location

Ha Noi, Vietnam

# Salary Expectation

450$ - 1000$++ tùy năng lực và kinh nghiệm thực tế.

Must Have

– Có từ 1 năm kinh nghiệm code HTML/CSS, html5/css3, bootstrap, js,...
– Sử dụng thành thạo HTML, CSS, Javascript
– Ưu tiên các ứng viên có kinh nghiệm làm theme, đặc biệt cho Magento.
– Ưu tiên các ứng viên có kỹ năng về thiết kế website (cơ bản)
– Ưu tiên các ứng viên có thể trao đổi công việc bằng English
– Chăm chỉ, tinh thần trách nhiệm, giao tiếp tốt;
– Khả năng làm việc độc lập, teamwork và chịu áp lực cao;

# Benefit:

– Mức lương cạnh tranh tương xứng với khả năng và kinh nghiệm
– Thời gian làm việc flexible 8:45 ~ 6:00, nghỉ thứ 7, chủ nhật (no OT), đánh giá dựa trên hiệu quả & chất lượng công việc.
– Có chính sách riêng của công ty, ngoài ra tuân theo pháp luật của Việt Nam
– Làm việc trong môi trường nước ngoài chuyên nghiệp, trẻ, thân thiện và năng động
– Làm trong office rất đẹp ở Toong.
– Cơ hội thăng tiến trong công việc cao, cơ hội trở thành key member.

Send us the following to ngocdb@live.com, vui lòng ghi rõ tiêu đề: Vị trí ứng tuyển _ Full Name
VD: Frontend Developer _ Nguyen Van A

**Comment by qcam** [comment]
@ngocdb Could you please rewrite your job post in English and follow our prison rules in guideline?
