### ISSUE TITLE
[Magnolia Vietnam] - [Senior DevOps Engineer] - [Ho Chi Minh] - [Full-time]

### ISSUE THREAD

**Issue by linhnguyenlethao** [awesome-jobs/vietnam#707]
## Location

* 7th Floor, Etown 1 Building, 364 Cong Hoa St., Ward 13, Tan Binh Dist, Ho Chi Minh, Vietnam

## Salary Expectation

Negotiable 

### Must Have

*Strong background in Linux/Unix Administration and scripting using shell scripts
*Experience with automation/configuration management using either Ansible, Puppet, Chef or an equivalent
*Ability to use a wide variety of open source technologies and cloud services (experience with AWS is mandatory)
*Strong experience with SQL and MySQL
*Relevant working experiences of code and script (Python, Perl and/or Ruby)
*Knowledge of best practices and IT operations in an always-up, always-available service
*Demonstrated experience in enterprise network administration and troubleshooting/analysis (DNS, IPsec VPN, BGP, Load Balancing)
*Proven expertise in virtualization, experience with Vagrant
*An upper english level is required as you will evolve in an international environment (good in all skills, especially in writing and communicating).
*Having the ability to clearly understand and focus on business outcomes is a real additional value.

### Ideally

*Additional knowledge in other Cloud Platforms preferable, aka: Google Cloud Platform, IBM Bluemix, Cloud Foundry, etc.

### Responsibilities

*Magnolia Cloud Platform is an agile, enterprise-grade CMS delivered as a convenient cloud-based service. 
*Entirely developed in our production center in Vietnam, we are looking for DevOps engineers with strong Amazon Cloud computing experience.
*As a DevOps Engineer, you will be part of a team to build AWS cloud architecture for our Java applications, delivering products as PaaS. 
*You'll define and manage cloud infrastructure as code (IAC), improve CI/CD pipeline, ensure scalability and availability of the system, build monitoring stack, automate build, configuration and deployment orchestration scripts, ... 
*You can also participate in developing Java and Python applications & services for our cloud platform.
*We're utilizing a broad toolset for DevOps/Infra like Terraform, Packer, Ansible, Vagrant, Jenkins, Grafana, ... and leveraging multiple services from AWS: EC2, S3, RDS, ACM, Route53, CloudWatch

### Why it would be awesome to work with us
*Magnolia is a great place to work.
The founders have established a healthy, diverse and multicultural environment, based on friendliness, respect, and a responsible “work/life” balance.
We participate in the Magnolia community by contributing to the forums, blogging, attending conferences and hosting our own annual conference.
We’re passionate about what we create; design and craft matter to us - whether it be in the graphics, the user experience or the code.

*Here at the Magnolia Vietnam, we don’t just offer you a job, we offer you future. Here’s your chance to get your hands on…
13th-month salary
Private health care program for you and your family members
English training with a native English teacher
Potential opportunities for exchange program to Europe as 2 off-weeks
Telecommuting if needed
Whoopie Fridays where people can meet, chat, and exchange knowledge
A refrigerator fully stocked with snacks, fruit, and beer 
Monthly team building activities, outings, and luncheon meetings for knowledge sharing
Stylish office, equipped with a 15” Macbook Pro and 27” Apple Thunderbolt Display for each  employee

### Contact
Say hello! If this looks like something for you, please send us your resume via email: linh.nguyenlethao@magnolia-cms.com or skype thaolinh.nguyenle

Website: https://www.magnolia-cms.com/

**Comment by qcam** [comment]
@linhnguyenlethao could you please update your post to comply with Markdown?
