### ISSUE TITLE
redWEB Vietnam - Senior PHP Backend Developer - Ho Chi Minh City - Full time

### ISSUE THREAD

**Issue by JerryChr** [awesome-jobs/vietnam#708]
## Location

* Saigon, Vietnam

## Salary Expectation

* $500-$2500

## Summary
We’re looking to increase our team of PHP developers to lead the way in our company’s exciting new ventures and growth in Vietnam. We have a fast increasing amount of projects both local and international that you will be working on. You will be working with other top devs from around the globe and have the opportunity to challenge yourself and further your career. 

## Requirements
* Strong knowledge & Experience PHP coding (3 years+)
* Strong knowledge & Experience on SQL script (3 years+)
* Good English both speaking and writing
* Be forward-thinking, have common sense and logical thinking
* Able to work and problem-solve independently
* Preferably good experience with Joomla development

### Must Have
* Experience in PHP development
* Great understanding of OOP/OOD/Design Patterns
* Good English communication skill 

### Responsibilities
You will work at our office in Vietnam (HCM City) and be a part of our international developer team consisting of developers from 10 countries. Every day, you have to communicate in English, report status to project leader and work by project management tools and task on Atlassian.

### Why it would be awesome to work with us
* A top salary if you pass the interview
* You will work for one of the world’s leading Joomla Providers and Extension houses.
* Open & young environment and a chance to grow fast with the growth of our company in VN.
* Join in the extracurricular activities every week/month (Play football, cooking, and some short travel every year)
* Yearly company trip
* Chance to go on the yearly bonus trip to Denmark(all expenses paid)
* English classes with native teachers

### Contact
Homepage: redWEB.vn
Mail: job@redweb.vn

**Comment by qcam** [comment]
@JerryChr Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.

**Comment by JerryChr** [comment]
@qcam updated and added the missing parts.
