### ISSUE TITLE
Ecommerce - QA Manager

### ISSUE THREAD

**Issue by shinsh1n** [awesome-jobs/vietnam#710]
## Location

* Saigon, Vietnam

## Company Overview

A fast growing mobile e-commerce company based out of Singapore with development operations in Vietnam and boasts a first class team of international investors seeks talented QA Manager to help us scale.

Our founding management team has had prior successes worldwide in the e-commerce and mobile space and we are looking for passionate and talented people to help us change the world

## Salary Expectation

* $2000/month 

## Main responsibilities: 
Manage tester team to keep high quality deliverable, ensure bug-free software within schedule
- Manage team of testers to develop/test/maintain mobile apps
- Keep quality of deliverables
- Control project schedule and state

## Overall requirements:
   - 7 - 10+ years of overall QC/QA/Tester experience
   - Strong knowledge and experience with Rapid / Efficient Development
   - Experience with Continuous Integration and Software Development
   - Experience with Mistakes / Error Avoidance
   - Experience with Test Plan, Test Case, Test Scripts
   - Experience with Agile Scrum
   - Advanced in Automation Testing

## Other skills:
   - Technical Capacity with Mobile / Web / Server system model
   - Organizational skills
   - Problem Solving / Analytical skills
   - Customer / Client Focus
   - Time Management
   - Performance Management
   - Efficient Management
   - Collaboration

## Good to have (not required):
- Trello / JIRA / ZenHub / Waffle
- GitHub / Bitbucket
- Android OS / iOS in general
- UML Diagram
- Project Wiki / FAQ
- CodeShip

### Contact
anh.nguyen@500startups.com

**Comment by qcam** [comment]
@shinsh1n Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
