### ISSUE TITLE
Undisclosed Ecommerce Company - QA Manager - Saigon - FT

### ISSUE THREAD

**Issue by shinsh1n** [awesome-jobs/vietnam#714]
## Location

* Saigon, Vietnam

## Salary Expectation

* $2,000/month or range

## Requirements

* 7 - 10+ years of overall QC/QA/Tester experience
* Strong knowledge and experience with Rapid / Efficient Development
* Experience with Continuous Integration and Software Development
* Experience with Mistakes / Error Avoidance
* Experience with Test Plan, Test Case, Test Scripts
* Experience with Agile Scrum
* Advanced in Automation Testing

### Must Have

* Technical Capacity with Mobile / Web / Server system model
* Organizational skills
* Problem Solving / Analytical skills
* Customer / Client Focus
* Time Management
* Performance Management
* Efficient Management
* Collaboration

### Ideally

* Trello / JIRA / ZenHub / Waffle
* GitHub / Bitbucket
* Android OS / iOS in general
* UML Diagram
* Project Wiki / FAQ
* CodeShip

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Manage team of testers to develop/test/maintain mobile apps
* Keep quality of deliverables
* Control project schedule and state

### Why it would be awesome to work with us

* A fast growing mobile e-commerce company based out of Singapore with development operations in Vietnam and boasts a first class team of international investors
* Our founding management team has had prior successes worldwide in the e-commerce and mobile space and we are looking for passionate and talented people to help us change the world

### Contact
Email: anh.nguyen@500startups.com

**Comment by qcam** [comment]
@shinsh1n Could you please disclose the the company name? Please note that we are not accepting jobs submitted by third-parties.
