### ISSUE TITLE
Ruby on Rails Developer (Junior to Mid-Level) - Full-time - 100% salary for probation period

### ISSUE THREAD

**Issue by trinhhang2303** [awesome-jobs/vietnam#715]
## Location

* Saigon, Vietnam (District 1)

## Salary Expectation

* $500 - $800

## Requirements
* Require Git, Github and Pull Request knowledge.
* Require relevant knowledge of relational database systems like PostgreSQL and MySQL.
* Require solid knowledge of web technologies like REST API, security, performance etc.
* Basic knowledge about Javascript, HTML and CSS.

### Must Have
* Experience with Ruby On Rails development **[at least 1 year experience]**

### Responsibilities
* Work on Web and Mobile products for a diverse range of Clients and industries
* Work and pair program with other developers to build applications with Rails / Node.js and React / React-Native.
* Work with Product Owner to convert business requirements into technical designs.
* Cooperate with UI Designer to implement modern minimalist designs into production.

### You’ll be responsible for
* Building a new social app network

### Why it would be awesome to work with us
> **100% official salary during the probation period**

* Free lunch, snacks and coffee.
* Healthy Insurance.
* An open and friendly working environment, we are all equals.
* Month 13th salary.
* Annual days off are based on Vietnamese law, 12-day annual leave per year, **all days not taken paid end of year as bonus**
* Birthday party, Welcome party Team building events or monthly company party.
* Company trip.

### Contact
Homepage: https://freerangetechnology.com/
Fanpage: https://www.facebook.com/freerangevn/
Email: hang.trinh@freerangetechnology.com

**Comment by enixdark** [comment]
@trinhhang2303: is this job available for remote dev ? sorry, i see `remote` word on your post.

**Comment by trinhhang2303** [comment]
yes, some special cases, we accept that dev can remote, however in-house dev will be better :)

**Comment by qcam** [comment]
@trinhhang2303  Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
