### ISSUE TITLE
AhaMove - Senior iOS Software Engineer

### ISSUE THREAD

**Issue by baotlh** [awesome-jobs/vietnam#716]
## About us

Founded in 2015 in Ho Chi Minh City, Vietnam, AhaMove is an on-demand logistics service based on the concept of a shared economy, providing customers to fill excess capacity for logistics suppliers and reduce costs for consumers. 
You can find more about us as a Facebook case study or on prestigious Asia Nikkei news
This is a tremendous opportunity to take your career to the next level. Please review the information below and if you are interested, follow the Apply instructions.

## The Job

* Design and build applications for the iOS platform
* Ensure the performance, quality, and responsiveness of applications
* Collaborate with a team to define, design, and ship new features
* Identify and correct bottlenecks and fix bugs
* Help maintain code quality, organization, and automatization

## Your Skills and Experience
* Bachelor’s degree in Computer Science, Software Engineering, or related field with 3+ years’ experience in iOS development.
* Proficient with Swift
* Familiarity with RESTful APIs to connect iOS applications to back-end services
* Deep knowledge of Google’s iOS SDK framework
* Have a good understanding of UI/UX and iOS animation
* Experience with offline storage, threading, and performance tuning
* Hands-on experienced with localization methodology, strategy, and delivered at least one verifiable app deployed internationally
* Unit-test code and UI test for robustness
* Understanding of the full mobile development life cycle
* Worked on location-based or e-commerce applications is a plus

## Why you love working here

* Disruptive innovations
* People-oriented philosophy of doing business
* Your footprint on regional on-demand market
* Sharp, motivated colleagues in a fun office environment
* Working 5 days/week at Dreamplex, the best co-working space in HCMC
* Competitive salaries and benefits according to experience and education level

## How to apply

Send us your CV to tech@ahamove.com

**Comment by rebyn** [comment]
Do you mind elaborating on the `disruptive innovations` point?

**Comment by qcam** [comment]
@baotlh Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
