### ISSUE TITLE
AdAsia Holdings - Senior Python Engineer - Saigon - FT

### ISSUE THREAD

**Issue by shiorimichellematsuyama** [awesome-jobs/vietnam#718]
## Location
*53F Bitexco Financial Tower, 2 Hai Trieu, Ben Nghe, District 1, Ho Chi Minh City

## Salary Expectation
* 1000-2000 USD/month
* Performance Bonus (0.5 to 3 months amount)

## Who You Are
* Strong Computer Science fundamentals
* 4+ years of experience in Python
* Good understanding of RESTful API
* Experienced in agile development
* Strong database knowledge (SQL, NoSQL)
* Can ship quality code quickly

### Must Have
* Full working proficiency in English

## Requirements
* Develop new features for AdAsia's web-based products (platforms with AI technology)
* Build features that touch the frontend website and backend API
* Write test-driven code and test for 100% functionality
* Maintain and constantly improve our current code
* Work closely with engineering team and product management team
* Create detailed technical specifications based on wireframes and functional specifications

## Why it would be awesome to work with us
* Competitive Salary
* Performance Review (2 times per year)
* Performance Bonus 
* Quarterly, Annual MVP Awards (prizes up to 8,000USD)
* MacBook to be provided
* Work in professional and dynamic environment
* Good chance to explore new trends in a digital market
* Opportunity to learn most advanced advertising technology platforms
* No fixed day for promotion – Perform well and get promoted anytime!

### Interesting Engineering Projects
* [AdAsia Digital Platform](https://adasiaholdings.com/service/adasia_digital_platform/)
* [AdAsia Ad Network](https://adasiaholdings.com/service/adasia_ad_network/)
* [AdAsia Video Network](https://adasiaholdings.com/adasia-video-network/)
* [Casting Asia](https://adasiaholdings.com/service/castingasia_influencer_marketing/) 

## Contact
Website: https://adasiaholdings.com/join_us/
Shiori Michelle: job@adasiaholdings.com

## How to apply
* [UPLOAD YOUR ENGLISH CV HERE](https://adasiaholdings.com/job/?gh_jid=746555)

**Comment by Basputaek13** [comment]
Thank you
