### ISSUE TITLE
GHN- Devops Engineer - HCMC - Full Time

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#720]
## Location

* Saigon, Vietnam

## Salary Expectation
 * 1000-1500$/month

**JOB DESCRIPTION ** 
Automating and managing the deployment processes using Continuous Integration and Continuous Delivery techniques.
Deliver system management tooling to the engineering teams.
Manage servers, applications and all internal software used by the company.
Monitor system performance and undertake needed performance tuningDocument the configuration of the system infrastructure
Able to attend to system alerts on an on-call basis.
Be an advocate for engineering best practices internally and externally.

**YOUR SKILLS AND EXPERIENCE**
1+ year exprience at DevOps Engineer.
Great documentation skills.
Experience with highly scalable system is preferred.
Strong Linux administration skills.Experience with cloud services such as AWS (Amazon), Rackspace or GCE, etc.
Experience with containerized services such as Docker, Kubernetes, etc.
Prior experience with configuration management using Chef, Puppet or Ansible expected.
Monitoring systems such as Sensu, Nagios, Grafana, Graphite, InfluxDB, etc.
Experience with Golang, C, Java or Python or any high level programming language is a plusStrong administration skills.
Responsibility, careful, integrity.
Communication directly and honestly.

### Contact
Homepage: https://giaohangnhanh.vn
https://www.linkedin.com/company/2721159/
Mr. Dong
E. dongdd@scommerce.asia
M & telegram 091 291 0678
S. Mrdongdo@live.com

**Comment by qcam** [comment]
@Dongdod 
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
