### ISSUE TITLE
[Recruiting infor] Senior Python Engineer-Ho Chi Minh

### ISSUE THREAD

**Issue by nhube** [awesome-jobs/vietnam#722]
## Location
Ho Chi Minh
* Saigon, Vietnam
* Remote

## Salary Expectation
15.000.000-20.000.000VND/month

## Requirements
- At least 2 years of experience
– Proven software development experience in Python 2.X or 3.X
– Experienced in RDB (Relation database)
– Good knowledge of Web App, RDB (Relation database).
– Knowledge of Docker, NoSQL & AWS are plus          
– Effective communication English skill

### Responsibilities
We are in urgent need of enthusiastic and professional Software Engineers who are strong at Python language to collaborate with team members to define and implement software architecture.
Scopes of work:
– Liaise with business owners to understand product’s requirements
– Deliver high quality, clearly commented and well Unit tested code
– Review other members’ code to ensure team’s work quality

###Benifits
-	Salary: 15.000.000 – 20.000.000 VND
-	Language training: Japanese, English (Company sponsor).
-	Salary review: 2 times/ year and incentive bonus at the end of the year.
-	Salary package: competitive and negotiable 
-	Lunch & parking allowance 
-	Applicable for all normal benefits: insurances, 13th salary, annual outing trip, team building activities, kick off 01 time/quarter.
-	Sport and club activities: Football, swimming, badminton etc. (Company sponsor)

### Contact
Please send CV to me at : be.nguyen@dctsolution.com
Company address: 64/1k D3, P25, Binh Thanh, HCM

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
