### ISSUE TITLE
[Recruit] Python Engineer Fresher-Ho Chi Minh

### ISSUE THREAD

**Issue by nhube** [awesome-jobs/vietnam#723]
## Location
Ho Chi Minh
* Saigon, Vietnam
* Remote

## Salary Expectation

7.000.000+ bonus+13rd salary

## Requirements
- New graduated students
- Have knowledge about python language
-Ability to work under pressure

### Contact
Please send CV to me at : be.nguyen@dctsolution.com
Company address: 64/1k D3, P25, Binh Thanh, HCM

**Comment by LordHung** [comment]
Does this job available for 4th year student?

**Comment by nhube** [comment]
@LordHung  yes. If you could work full time, please send me your CV.
or contact me at skype Nhube93 for more information.

**Comment by qcam** [comment]
@nhube 
Please write a proper job description and make sure it follows [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), otherwise it won't be accepted.
