### ISSUE TITLE
GHN- TechLead (Java) - HCMC - Full Time

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#725]
## Location

* Saigon, Vietnam

## Salary Expectation

*1800-2500 $/month

## Requirements
**KIẾN THỨC**
 
- Có kiến thức tốt về OOP, OOD.
- Có kiến thức tốt về các hệ quản trị CSDL và truy vấn dữ liệu qua SQL.
- Có kiến thức và hiểu biết về nguyên lý hoạt động của HTTP, cookie,
session, cache.
- Có kiến thức tốt về các hệ thống NoSQL phổ biến.
- Có kiến thức về quản lý team/dự án.
- Có kiến thức căn bản về lập trình web frontend (HTML, CSS, Javascript).
- Có kiến thức căn bản về Linux.
- Có kiến thức và kinh nghiệm về Hadoop Ecosystem là lợi thế.

**THÁI ĐỘ**
- Đặt sự hài lòng của khách hàng lên đầu tiên.
- Thích nghi và làm việc tốt trong môi trường “customer-first” và “customer-oriented
delivery”.
- Có mindset về system performance optimization và application security.
- Chủ động phối hợp với đồng nghiệp trong công việc.

**KỸ NĂNG**
- Thành thạo ít nhất một trong số các ngôn ngữ lập trình Java, Scala, Python, NodeJS, PHP, C/C++.
- Thành thạo ít nhất một trong số các hệ thống CSDL MySQL, Postgresql, v.v...
- Có kiến thức về NoSQL (Redis, Cassandra, MongoDB, v.v...)
- Có kiến thức về hệ thống thu thập log, search & xử lý data: Hadoop ecosystem,
Spark, ElasticSearch, v.v...
- Sử dụng tốt HTML/CSS/Javascript và các framework thông dụng (bootstrap,
Jquery v.v...)

**KINH NGHIỆM LÀM VIỆC**
- 2+ năm làm việc ở vị trí quản lý/lead
- 5+ năm kinh nghiệm xây dựng các hệ thống backend & webservice.
- 5+ năm kinh nghiệm làm việc với MySQL hoặc/và PostgreSQL.
- 1+ năm làm việc với các hệ thống NoSQL (Redis, Cassandra, MonggoDB, v.v...)
- 6+ tháng làm việc với các hệ thống thu thập log, search, xử lý data (Hadoop
ecosystem, Spark, ElasticSearch, v.v...).
- Có kinh nghiệm/kiến thức về data mining và/hoặc machine learning là lợi thế.

### Contact
Homepage: https://giaohangnhanh.vn
https://www.linkedin.com/company/2721159/
Email : ngocdtd@ghn.vn
Skype: ngoctrongda168

**Comment by lucduong** [comment]
Mình có tất cả và đang làm về Machine Learning,

**Comment by Dongdod** [comment]
Nếu bạn quan tâm đến vị trí này thì gửi cho  Đông CV vào email ngocdtd@ghn.vn nha, thanks

**Comment by chuyencuadev** [comment]
Mình cũng biết hết mấy cái trên nhưng mà làm ko được thôi :)

**Comment by qcam** [comment]
@Dongdod Could you please rewrite your job post(s) in English?
