### ISSUE TITLE
GHN- Senior Backend Developer (Golang) - HCMC - Full Time

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#732]
## Location
 BIDV Building 70 Lu Gia, District 11, Ho Chi Minh City

## Salary Expectation

* up to 1500 USD /month 

## Requirements

**Job Description**
As a Senior Backend developer, you will work with the team to deliver the significant web base products.
Key job functions:
- Tham gia vào đội ngũ thiết kế, xây dựng hệ thống Online Platform.
- Tiếp nhận - quản lý thông tin đơn hàng và giao tiếp với hệ thống đối tác, mang lại trải nghiệm tốt nhất cho khách hàng.
- Phân tích và đưa giải pháp duy trì, đảm bảo các vấn đề về khả năng chịu tải, ổn định và mở rộng hệ thống.
- Phối hợp với team QC, đảm bảo chất lượng sản phẩm.
- Nghiên cứu giải pháp, công nghệ mới áp dụng vào dự án

**Job Requirements**

- Thành thạo ngôn ngữ lập trình **Golang** .
- 3 năm kinh nghiệm trở lên trong việc xây dựng các hệ thống backend & webservice.
- Trên 2 năm kinh nghiệm làm việc với NoSQL (Mongo, Redis, Neo4j ..v.v), trên 1 năm với SQL.
- Có kinh nghiệm làm việc với các hệ thống thu thập log, search, xử lý data (Hadoop ecosystem, Spark, ElasticSearch, v.v…).
- ó kiến thức về hệ thống thu thập log, search & xử lý data: Hadoop ecosystem, Spark, ElasticSearch, v.v…
- Sử dụng tốt HTML/CSS/Javascript và các framework thông dụng (bootstrap, Jquery v.v…). **Ưu tiên từng phát triển dự án SPA, sử dụng ReactJS, VueJS, AngularJS..v.v.**
- Có kiến thức và hiểu biết sâu sắc về nguyên lý hoạt động của HTTP, cookie, session, cache.
- Có kiến thức tốt về OOP, OOD.

### Contact

Homepage: https://giaohangnhanh.vn
https://www.linkedin.com/company/2721159/
Email : ngocdtd@ghn.vn
Skype: ngoctrongda168

**Comment by qcam** [comment]
@Dongdod Please rewrite your job post in English.
