### ISSUE TITLE
Magnolia Vietnam - Senior DevOps - SaiGon - FT

### ISSUE THREAD

**Issue by linhnguyenlethao** [awesome-jobs/vietnam#734]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1500 - $2500

## Requirements
* Strong background in Linux/Unix Administration and scripting using shell scripts
* Experience with automation/configuration management using either Ansible, Puppet, Chef or an equivalent
* Ability to use a wide variety of open source technologies and cloud services (experience with AWS is mandatory)
* Strong experience with SQL and MySQL
* Relevant working experiences of code and script (Python, Perl and/or Ruby)
* Knowledge of best practices and IT operations in an always-up, always-available service
* Demonstrated experience in enterprise network administration and troubleshooting/analysis (DNS, IPsec VPN, BGP, Load Balancing)
* Proven expertise in virtualization, experience with Vagrant
* Additional knowledge in other Cloud Platforms preferable, aka: Google Cloud Platform, IBM Bluemix, Cloud Foundry, etc.
* An upper english level is required as you will evolve in an international environment (good in all skills, especially in writing and communicating).
* Having the ability to clearly understand and focus on business outcomes is a real additional value.

### Must Have

* An upper english level is required as you will evolve in an international environment (good in all skills, especially in writing and communicating).
*  Strong background in Linux/Unix Administration and scripting using shell scripts
* Experience with automation/configuration management using either Ansible, Puppet, Chef or an equivalent
* Ability to use a wide variety of open source technologies and cloud services (experience with AWS is mandatory)
* Strong experience with SQL and MySQL
* Relevant working experiences of code and script (Python, Perl and/or Ruby)

### Responsibilities

Magnolia Cloud Platform is an agile, enterprise-grade CMS delivered as a convenient cloud-based service. 
Entirely developed in our production center in Vietnam, we are looking for DevOps engineers with strong Amazon Cloud computing experience.

### You’ll be responsible for

* As a DevOps Engineer, you will be part of a team to build AWS cloud architecture for our Java applications, delivering products as PaaS. 
* You'll define and manage cloud infrastructure as code (IAC), improve CI/CD pipeline, ensure scalability and availability of the system, build monitoring stack, automate build, configuration and deployment orchestration scripts, ... 
* You can also participate in developing Java and Python applications & services for our cloud platform.
* We're utilizing a broad toolset for DevOps/Infra like Terraform, Packer, Ansible, Vagrant, Jenkins, Grafana, ... and leveraging multiple services from AWS: EC2, S3, RDS, ACM, Route53, CloudWatch

### Why it would be awesome to work with us

Magnolia is a great place to work.
The founders have established a healthy, diverse and multicultural environment, based on friendliness, respect and a responsible “work/life” balance.
We participate in the Magnolia community by contributing to the forums, blogging, attending conferences and hosting our own annual conference.
We’re passionate about what we create; design and craft matter to us - whether it be in the graphics, the user experience or the code.
Say hello! If this looks like something for you, please send us your resume and a link to some online projects.

Here at the Magnolia Vietnam, we don’t just offer you a job, we offer you future. Here’s your chance to get your hands on…

* 13th-month salary
* Private health care program for you and your family members
* English training with a native English teacher
* Potential opportunities for exchange program to Europe as 2 off-weeks
* Telecommuting if needed
* Whoopie Fridays where people can meet, chat, and exchange knowledge
* A refrigerator fully stocked with snacks, fruit, and beer 
* Monthly team building activities, outings, and luncheon meetings for knowledge sharing
* Stylish office, equipped with a 15” Macbook Pro and 27” Apple Thunderbolt Display for each  employee

### Contact
Homepage: https://www.magnolia-cms.com/
Linh Nguyen (Ms.): linh.nguyenlethao@magnolia-cms.com (skype:thaolinh.nguyenle)

**Comment by qcam** [comment]
@linhnguyenlethao thanks for posting. Could you please fix all malformed bullet points above?

**Comment by linhnguyenlethao** [comment]
@qcam: fixed, thank you a lot for your support!
