### ISSUE TITLE
TOMOSIA - Junior/Senior ROR Developer - Hanoi - Full Time

### ISSUE THREAD

**Issue by r0ckkhuya** [awesome-jobs/vietnam#745]
TOMOSIA is looking for two Ruby on Rails dev in Hanoi.

## Location
601, N07-B3, Thanh Thai, Ha Noi. 

## Salary
$500 ~ $1200 / month

### Mandatory:
- Ruby
- Ruby on Rails framework
- 2+ years of web developer experience
- Honest, dare to fail, not afraid of difficulties

### Expected:
- Knowledge of frontend, AWS
- Time management skills
- Good communication
- Willing to learn and be passionate about new technology

## Why TOMOSIA?
Name #TOMOSIA is a Japanese word play, meaning win-win, be happy.
At TOMOSIA, we value company culture and family values, friends. Can not archive anything if we have a short-sighted mind and focus on profits and numbers.

At TOMOSIA, you will have to learn the newest technologies. TOMOSIA's partners are Japanese startups that work on fintech, IoT, AI, etc. They are very active, creative, and TOMOSIA must be the same.

At TOMOSIA, you keep doing what you love, but you have to be the best in the field.

## Contact : 
Email : anh.luu @ tomosia.com

**Comment by qcam** [comment]
@r0ckkhuya Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
