### ISSUE TITLE
IOS & Android Developer

### ISSUE THREAD

**Issue by SilentDev1** [awesome-jobs/vietnam#750]
## Location : Remote

* Saigon, Vietnam
* Remote

## Salary Expectation
Part-Time / $300 - $500 pay monthly depend on experience
* $????/month or range

## Requirements
Swift, Android, Back4App, JavaScript JS, HTML, CSS, PHP

## Skills
Worked with Swift before, and have build IOS & Android App

### Must Have
Build IOS & Android App

### Ideally
Swift, Android, Back4App, JavaScript JS, HTML, CSS, PHP

### Responsibilities
Adding new features to the app, solving errors
Great power comes with great responsibilities!

### You can bring

* A good eyes for design
* A good analyis skill

### Why it would be awesome to work with us
We are a startup company in the US, the founders are also Vietnamese. If you are looking to make new friends and connect I think you will enjoy working with us!

Homepage: www.sidegigs.io
Trollman: info@sidegigs.io

**Comment by hitechworm** [comment]
Hi Hung, have you still looking for Android dev?

**Comment by SilentDev1** [comment]
Hi, yes we are. Can you send me a cv/ resume.

**Comment by kyokid** [comment]
Hi Hung, are you still looking for iOS Dev?

**Comment by qcam** [comment]
@SilentDev1 Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
