### ISSUE TITLE
Axon Active - Artificial Intelligence Software Engineers (Python, Java, C/C++)

### ISSUE THREAD

**Issue by AxonActive** [awesome-jobs/vietnam#751]
Coming to Axon Active, you will work directly in trendy projects in Fintech, Big Data, Mobile, IoT, BPM, Biotech, Machine Learning, etc. Our Scrum teams are growing in dynamic spirit with teamwork & passion. You will be offered premium benefits and attractive salary. Besides, we are focusing on developing your knowledge, skills and English wherever you work in Ho Chi Minh, Da Nang or Can Tho.

Many users may not realize that AI is being applied everywhere. It’s the way Google Search, Amazon are showing best results/recommendations matching your needs; it’s Facebook is tagging people automatically in uploaded photos; it’s Tesla is driving itself without driver’s intervention and countless examples.

With the advances of deep learning, AI is transforming almost any industry. That’s why there is a growing need of AI Engineers these days. Being the AI Software Engineer in Axon Active Vietnam, you will work in a dynamic Scrum team to study, design and implement state-of-the-art machine learning algorithms for our AI products.

## Location
* Saigon, Vietnam

## Salary 
Negotiable

## Responsibility:

* Work in Scrum team (5 to 9 developers) to develop software products applying machine learning techniques
* Daily cooperate with Product Owner to clarify requirements, initiative solutions and develop deliverable software in the iterations of Scrum
* Be involved in every phases of Agile software development includes planning, estimation, developing and continuously delivering software
* Self-assign tasks and fully be responsible for quality/quantity of delivered result. Self-determine appropriate architecture, technical solutions and make relevant recommendations to Product Owner

## Requirements
* Good knowledge in mathematics and algorithms
* Solid fundamental of OOP, data structures and software design
* Experience in Python and Java (or C/C++)
* Knowledge of distributed data processing technology
* Passion on cutting edge technologies and product delivery
* Good English communication, both verbal and written

### Contact information:
Homepage: http://www.axonactive.com/
Email: job@axonactive.com
Skype: tran.yen6 (Ms. Yen)

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
