### ISSUE TITLE
Axon Active - Automation Testers (Selenium)

### ISSUE THREAD

**Issue by AxonActive** [awesome-jobs/vietnam#752]
We are looking for outstanding Automation Testers to work directly and permanently with our customers in Europe. You will be a part of Scrum team where you can develop your potential, make use of your skills, bring our ideas to the world, initiate your solutions and make your daily work be awesome.

Join our elite Scrum teams, step your career up in our international environment and become one of the most active professional Agile practitioners in Vietnam.

## Location
* Saigon, Vietnam

## Salary 
* Negotiable

## Responsibility:
* Work in Scrum team, directly with foreign customer
* Create and maintain test cases

## Requirements
* Have background knowledge in IT
* Have good English skills
* Experience with Manual and Automation test
* Familiar with testing tools eg: Selenium

## Contact information:
Homepage: http://www.axonactive.com/
Email: job@axonactive.com
Skype: tran.yen6 (ms. Yen)

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
