### ISSUE TITLE
OrangeLogic - Software Engineers (.Net, SQL, Java) - HCMC - FT 

### ISSUE THREAD

**Issue by OLhiringteam** [awesome-jobs/vietnam#755]
## Location

* Saigon, Vietnam
* Full time 

At Orange Logic, you will be joining a team of dedicated and talented colleagues who share in your desire to build one of the most sophisticated softwares in managing digital media. Orange Logic’s premium SaaS offering, CORTEX | DAM, was created to aid companies around the world in scaling up their digital operations. Our customers come from a multitude of industries including aerospace, finance, broadcast, fashion, and global NGOs amongst others.

## Responsibilities
With offices located in the United States and Europe, Orange Logic has recently opened its first Southeast Asian location in Ho Chi Minh City. We are establishing a team of tech-savvy engineers that will design and implement new features to our software. Your responsibilities will include, but are not limited to:

- Taking ownership of projects and having the opportunity to further your knowledge by exploring machine learning, security, DevOps, and more.
- Developing scalable new features for our software product that exceeds our customer’s needs.
- Building architecture for our platform to ensure optimal performance.
- Obtaining requirement feedback from internal teams/clients to maintain/support the product development.
- Write the Unit Tests for robust development.
- Performing code reviews on other team member’s work.

## Requirements
Due to our entrepreneurial nature, we have cultivated an environment that allows our engineers to take initiative, propose novel ideas, and provides them with the opportunity to dive into multiple projects. We are looking for Engineers who possess the following:

- A Bachelor’s Degree in any relevant major (e.g. Information Technology, Computer Science, etc.).
- Proficiency with English (both verbal and written).
- 3+ years’ practical experience on a web-based application.
- Proficiency with any backend programming languages (e.g. .NET, Java, Python, etc.).
- A strong fundamental understanding of software development.
- An understanding of complex algorithms and data structures, as well as a passion for intellectual challenges.
- Strong self-discipline for delivering well-tested, complete features/modules under a tight schedule and the capability for rational thinking.
- Experience with the database management tool SQL is a plus, but not mandatory.

### Why it would be awesome to work with us

- Nice, modern office with state-of-the-art equipment: powerful machines, multiple screens, high quality ergonomic chairs, etc.
- Sign on bonus* for joining before Feb 14th 2018
- A very competitive salary and benefits
- 13th-month salary + bonus
- Lunch & parking allowance
- Healthy snacks, fresh food, coffee provided
- Premium health insurance with gym tickets
- Fitness perks sponsored
- 15 days annual leave

### Contact
Huyen Nguyen - HR & Recruitment
huyen.nguyen@orangelogic.com

**Comment by OLhiringteam** [comment]
Label: Saigon, .Net, C#, Java, SQL, Fulltime
Thanks admin

**Comment by qcam** [comment]
@OLhiringteam Please remove URGENT in the title, thanks.
