### ISSUE TITLE
PYCO - Senior Java Developer - HCMC - FT

### ISSUE THREAD

**Issue by hienhapyco** [awesome-jobs/vietnam#756]
## Location

* Saigon, Vietnam

## Salary Expectation

* From $1500/month

## Requirements
* Java
* AWS
* Microservices
* 5+ years Software Engineering experience

### Must Have

* Strong knowledge and experience with JAVA-related technologies in web-based programming, system design, technical troubleshooting, problem solving...
*Experience with one of the flowing IDEs: Eclipse, NetBeans, IntelliJ
*Experienced in web servers, application servers (Apache, Tomcat, JBoss, IBM Websphere)
*Good at database design and programming (MS SQL Server, or Oracle, MySQL,...)
*Good at using CASE tools and frameworks (such as such as CVS, SVN, JMeter, Ant, Maven, Continuous Integration)

### Ideally

*Experienced in Struts 2, Velocity, JPA, Hibernate, Spring, Spring MVC, Liferay, CQ5, JIVE, Tapestry 5, Lucene is a plus
*Experienced in open source solutions such as cms, portal, social network... is a plus

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

*Analyze system requirements
*Participate in system design and implementation.
*Perform as a key member in technical problem resolution in projects with Team Leaders
*Can play the role of a Team Leader to manage several developers in projects.

### Why it would be awesome to work with us

*The latest technologies for mobile & web development
*Teammates that challenge you to exceed your limits
*The finest IT tools to raise your potential to even greater heights
*The power to deliver some truly awesome products & services
*Cutting-edge collaborative software development
*A career path that allows you to learn and grow
*Attractive annual bonuses
*Private health care program

### Contact
Homepage: http://www.pycogroup.com/
Hien Ha: hien.ha@pycogroup.com | Skype: haanhhien031192 | Phone: 0989228816

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` section must be filled.
