### ISSUE TITLE
[AdAsia Holdings] - Senior Python Engineer - HCMC - FT

### ISSUE THREAD

**Issue by bodrago** [awesome-jobs/vietnam#757]
## Location

* 22 Flr, Saigon Trade Center, 37 Ton Duc Thang, District 1, Ho Chi Minh, Vietnam
# Salary Expectation

* 2000$/month or range

## Requirements

- Academic background in Computer Science or relevant
- Strong in English communication
- 4+ years of experience in Python
- Good understanding of RESTful API
- Experienced in agile development
- Strong database knowledge (SQL, NoSQL)
- Can ship quality code quickly

## Skills
Python
SQL, NoSQL

### You’ll be responsible for

- Develop new features for AdAsia's web-based products
- Build features that touch the frontend website and backend API
- Write test-driven code and test for 100% functionality
- Maintain and constantly improve our current code
- Work closely with engineering team and product management team

### Why it would be awesome to work with us

- Competitive Salary
- Performance Review (2 times per year)
- Performance Bonus (1 time per year from 0.5-month to 3-month salary amount )
- Annual Paid Leave
- Quarterly, Annual MVP Awards (prizes up to 8,000USD)
- MacBook to be provided
- Work in professional and dynamic environment
- Good chance to explore new trends in a digital market
- Opportunity to learn most advanced advertising technology platforms
- No fixed day for promotion - Perform well and get promoted anytime!

### Interesting engineering projects
Building one of the most awesome product powered by Artificial Intelligent!
### Contact

Email: baole@adasiaholdings.com
Mobile: 0909 222 970
Skype: bond.le

**Comment by qcam** [comment]
@bodrago Could you please remove the square brackets around your company name? Also please elaborate on the AI product in the Interesting Engineering Project section.
