### ISSUE TITLE
Futureworkz - Junior/Senior Ruby on Rails Developer - Saigon - FT/C

### ISSUE THREAD

**Issue by stevenyap** [awesome-jobs/vietnam#76]
## Who we are

Futureworkz is a Singapore-based Web Design company that specialized in Agile development with (mainly) Ruby on Rails. We are a strong vibrant team of designers and developers. All our projects are mainly from Singapore.

We are a totally geeky company that loves coding and designing for great web and mobile applications. We adopt world-class development methodologies and project management processes.

Futureworkz is a learning and family culture company. The world is moving fast and we are constantly evolving ourselves to learn new things and adopt new thinkings.

Join us to grow yourself as a coder and as a person. Let's grow together!

To understand us better, read our playbook: http://playbook.futureworkz.com
This is who we are, what we do and why we do what we do

Company Size: 20+
## What we are looking for

We are looking for highly-motivated and totally-geekish Ruby on Rails programmers to develop web app. We have a wide diversity of projects from NoSQL data system, ReactJS interface, video streaming, chat apps, mobile apps, API servers and of course the plain-O-simple-sites.

There will be training and upgrading courses to improve your skills as a coder. We are a world-class development company and we expect you to learn the best practices and apply it in your daily work. Developing yourself as a coder also means you have to present/share new knowledge to other co-workers.

Futureworkz believes in having a balanced work-life. We strongly discourage overtime in the company. We believe each project needs time to develop instead of rushing to just meet dateline.
## What you will be doing
- Develop & maintain web applications
- Participate in daily standups and sprint meetings
- Participate in client and project manager meetings
- Provide assistance to project manager in managing projects
- Do presentation or workshop on new technologies to co-workers
- Learning English
## What you will be getting
- 5 work days a week
- 13th month bonus 
- Annual paid leave of 14 working days per calendar year
- 3 days paid compassionate leave 
- 7 days paid medical leave 
- Special bonus
- Social insurance
- Monthly gathering programs
- Annual company holiday
- Code training
- MacBook Air
## What you must bring to the company
- At least some experience in Ruby on Rails
- An open mind to learn
- Team spirit to work and learn together
- Willingness to share with others
## What you will grow into
- An experienced Ruby on Rails developer with many different kinds of projects under your belt
- Adopter of world-class development practices such as Git, CI, CM tools, TDD
- Able to contribute back to the world through presentations or OSS
## What you may grow into
- Able to speak English (Singapore-style lah~!)
- Able to manage a project by yourself with Singapore clients
- Able to consult clients on their business objectives aligned with development needs
## Contact Information

www.futureworkz.com
184/17 Dien Bien Phu Street, Ward 17, Bình Thạnh District, HCMC
HR: recruitment_at_futureworkz_dot_com

**Comment by huynhquancam** [comment]
:+1:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by stevenyap** [comment]
Thanks for the heads up. I have edited the title to comply with your job post guideline. As far as I can see, it seems that our post is in compliance now. Please let me know if there is anything else I should change.

Thank you.

**Comment by joneslee85** [comment]
@stevenyap all good mate
