### ISSUE TITLE
Junior/Senior ReactJS offer upto 1200$

### ISSUE THREAD

**Issue by JaneDang** [awesome-jobs/vietnam#766]
## Location

* Hà Nội, Vietnam

## Salary Expectation

* 1200$/month

## Requirements
* Phát triển ứng dụng di dộng platform/thương mại điện tử với ReactJS 
* Làm việc cùng với team, dưới sự hướng dẫn của Team Leader.

## Skills
* Yêu thích lập trình Mobile.  Ít nhất 1- 2 năm kinh nghiệm trở nên.
* Có kiến thức vững chắc về OOP
* Có kiến thức tốt về phát triển web.
* Có kiến thức tốt về ReactJS, React Native và nắm vững kiến trúc Flux.
* Có kinh nghiệm làm việc với JSX.
* Có kiến thức tốt về iOS/Android SDK và các loại API (Facebook, Google API,...) .
* Khát khao và tò mò tìm hiểu những công nghệ mới hiện nay như: ES6, AI, machine learning.

### Must Have

* Có kỹ năng phân tích & giải quyết vấn đề, kỹ năng cộng tác & giao tiếp tốt.
* Tinh thần Can-Do, thích thử thách và không lùi bước. Chủ động, khiêm tốn học hỏi.

### Why it would be awesome to work with us

* Mức lương: Từ 800$ - 1200$
* Được tham gia làm việc trên hệ thống có lượng truy xuất lớn.
* Được hưởng đầy đủ các phúc lợi, đãi ngộ theo quy định của Nhà nước.
* Hưởng tháng lương thứ 13&14, xét tăng lương 2 lần/ năm.
* Được tham gia đầy đủ BHXH, BHYT, BHTN theo quy định của Nhà nước khi trở thành nhân viên chính thức.
* Được tham gia các sự kiện hàng tháng, hàng quý của Công ty.
* Làm việc trong môi trường tươi trẻ, năng động, sáng tạo, thân thiện và vui vẻ.

## Contact

* Công ty TNHH Scuti
* Địa chỉ: P1508- Toà nhà N105- Ngõ 89 Nguyễn Phong Sắc- Cầu Giấy- Hà Nội
* Hotline: 024 6292 7275 - 098 1234 144
* Email: jane89@scuti.asia            Skype:  #sakyra.janny
* Website: scuti.asia

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.

Also please rewrite the post in English.
