### ISSUE TITLE
Judge.me - (Technical) Customer Support - HCMC - FT/PT/flex.

### ISSUE THREAD

**Issue by felixsuellwold** [awesome-jobs/vietnam#768]
## Location

* District 4, HCMC, Vietnam

## Salary Expectation

* $500/month

We are looking for a new customer support team member to take care of the night shift from Monday to Friday with working hours from 9pm to 6am (1-hour 'lunch' break).

However, we also have positions open for other time slots (weekday and weekend) and can offer flexible schedules or part-time solutions. If you are interested in these, please contact us with your suggestions. 

## Requirements
* Great command of written English
* Some experience in HTML, CSS
* Previous experience with liquid (Shopify) is a big plus
* Previous experience in ecommerce is a big plus

### Must Have

* **A positive attitude**, focused on making our users successful (instead of a ‘just getting a job done’ or ‘following a process’ attitude)
* Reading HTML and CSS code will become part of your daily job (but we teach you intensively)
* Willingness to learn about e-commerce, how to understand code, handling users in customer support
* Document what you learn and share it with your team

### Responsibilities

Make our Judge.me users happy, by handling:

1. Installation help
2. Questions about Judge.me features
3. Questions about technical issues

### You’ll be responsible for

1. Installation help: Every shop is different so therefore there is always some manual adjustments needed to install our features as nicely as possible based on the user’s shop, preference, and experience.
2. Feature questions: Answer user questions about specific Judge.me features by using our internal and external documentation, your understanding of Judge.me and Shopify, or common sense (and your own test shop).
3. Technical questions: At best, you can solve technical questions yourself. However, it is always fine to prepare the question for the developer while informing our user about the next steps.

### Why it would be awesome to work with us

We are currently a team of 3 developers, 2 customer support team members, one director of marketing and our founder. The team has its origins in Belgium, Germany, Romania, Colombia and of course Vietnam. Judge.me is laser-focused on developing a product that makes a difference while upholding the highest standard of customer support. Also there are team lunches on Friday with Sushi or Pizza :)

Working as a customer support team member, you will:

- Get to know one of the most globally relevant ecommerce solutions, Shopify
- Learn how to read HTML and CSS code
- Practice dealing with customers, mainly in the U.S. and Canada
- Experience the product development of a highly user-focused app

You will receive a lot of one-on-one teaching to allow you to learn as fast as possible about our product and the ecommerce environment we operate in.

We have a two week trial period (“probation”) after which you will receive private medical insurance (if needed).

## About the Job

Judge.me is a solution for ecommerce shop owners to collect and publish product reviews (collection: web, email; publishing: Shopify, Facebook, Google).

Check out our Shopify app, especially our reviews: https://apps.shopify.com/judgeme

Shopify is a hosted e-commerce solution with global impact. See websites using Shopify here: https://trends.builtwith.com/shop/Shopify

Working in customer support for Judge.me is challenging and fun because we help our users to be successful with their ecommerce business and they show a lot of appreciation for all the hard work we invest in the relationship with them! 

## Perspectives

Starting out in the customer support team at Judge.me offers various career perspectives. We want you to grow as much as possible and hope that you are interested in making Judge.me a milestone in your career. 

We see the following perspectives for you:

1. Advance to customer support manager: Hire, train, and supervise more customer support staff as well as document the process of customer support at Judge.me to onboard new team members quickly.
2. Account management: Take care of our users, understand the context they operate in, and try to introduce new features, upsell our plan, or improve their Judge.me experience with detailed help.
3. Marketing / Business development: Increase the Judge.me user base by working on paid ads, inbound marketing, or partnerships.
4. Customer Support Engineer: Take care of difficult user problems with your extensive knowledge about HTML and CSS gained as a customer support team member. From this position, you can also advance into our development team. 

### Contact
Homepage: Judge.me
PJ: pj_at_judge_dot_me

Send your CV or LinkedIn profile. Please state your previous work experience, your personal career perspectives, your possible working schedule and your current occupation, as well as questions about the job or Judge.me itself. Please also state your food preferences in the email for our weekly team lunches :)

**Comment by khacanh** [comment]
:+1:

**Comment by kimquy** [comment]
❤️

**Comment by qcam** [comment]
I am a bit on the fence of accepting this post since this does not look like a technical position to me.

@huydx do you have any comment?

**Comment by huydx** [comment]
Tech support engineer still a valid type of position, so I think this JD is acceptable
