### ISSUE TITLE
[Gamarist] -  Node.js Developer -  Da Nang - Part-time

### ISSUE THREAD

**Issue by huytd** [awesome-jobs/vietnam#769]
At Gamarist, you will join an awesome team building great online products, employing the power of React, Node.js, PostgreSQL and Amazon Web Services.

We are the team behind [xepkeo.vn](https://xepkeo.vn) and we're now looking for a part-time Node.js developer to join our team, please see the information below for more details.

## Location

* Danang, Vietnam

## Salary Expectation

* 2,000,000 to 3,000,000 VND / month 
* With just 4 hours a day, this position is suitable for university student who looking for a part-time job

## Responsibilities

You will act as a full-stack developer, working with a team of 4 to build web applications from coding to shipping, based on the requirements from customers.

Since we're a small team, it's recommended for you to be at our office, anytime, but make sure you made it at least 4 hours a day, from Monday to Saturday.

And don't worry, it's gonna be fun, I promise!

## Requirements

* A programmer mindset
* HTML/JavaScript/CSS
* Having knowledge in React, Node.js, and AWS is a plus, but not a must. You can learn as you go.

## You can bring

* Your own laptop

## Contact
Homepage: https://gamarist.com
Contact: Mr. Lê Hồng Minh (lehongminh@gamarist.com)

**Comment by qcam** [comment]
@huytd Could you write more information about the position?

**Comment by huytd** [comment]
Company shutdown already. There’s no need to provide anything now.
