### ISSUE TITLE
Cogini - Senior RoR - Ho Chi Minh - FT

### ISSUE THREAD

**Issue by hupahupa** [awesome-jobs/vietnam#77]
## Location
- Dist 7, Ho Chi Minh City, Vietnam
## Salary expectation
- High salary compare with the market(over 1000$)
## Requirements
- English proficiency a MUST, any other language a plus;
- Good OOP Background;
- More than 2 years experience with Ruby on Rails (others languages: Python, PHP, Elixir, Erlang will be a plus);
- PostgreSQL, MySQL understanding a must;
- Familiar with Agile management.
## Skills
- Can work on Linux, Mac OS
- Know Git, SSH to remote server, chef and vagrant are a plus
- Good team-working and communication ability.
- Be able to work independently and under high pressure.
### Responsibilities
- You will develop custom applications such as e-Commerce, social networking, and logistics. 
- While working within a multi-national distributed team, you will need to design and implement projects according to specifications provided by project leads. 
- You will also be asked to contribute to estimates and to design and develop modules and unit-test them. 
- Familiarity with testing methodologies essential. Projects will receive code and design reviews and you are expected to contribute to all aspects of the project on an as-needed basis.
### Benefit
- 13th month salary;
- Flexible working time;
- Company trips per year;
- Lunch allowance;
- Birthday parties;
- Health care insurance.
- Macbook pro
- Sport activities
- PS4 game after work
### Contact

Duy Le: duylm@cogini.com

**Comment by oItachi** [comment]
Lương hấp dẫn quá :)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by hupahupa** [comment]
@joneslee85 Thanks for notice me, I've updated the post.

**Comment by joneslee85** [comment]
:+1:
