### ISSUE TITLE
INSPECTORIO - Technical Writer - HCMC

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#771]
# Location: Ho Chi Minh City

# Salary: $1500 ~ $3000

# About Us
At Inspectorio we are making our own software product, SaaS platform, that use IoT and Data to help retailers verify supplier compliance and bring transparency to their supply chains.

Founded in Hong Kong in 2015, Inspectorio is now headquartered in Minneapolis, with R&D lab in Ho Chi Minh City and offices in Hangzhou, Quito.

Our diverse team is comprised of Mathematician, Neuroscientist, Data Scientist to Pianist, Magician, Running Champion, Kendo Master, Wood Crafter…

We are the only Vietnam based Techstars company and are working with leading retailers and brands around the globe, our initial market focus on China and Vietnam, and expanding 5 new markets in 2017.
Get to know what Inspectorio is doing at: www.inspectorio.com

# Job Description

- To craft documentation that is easily digestible and that will aid in the client adoption of our software products and help business users successfully adopt Inspectorio’s SaaS platform.
- To work closely with subject matter experts, software engineers, and other stakeholders to gather, analyze, translate and compose technical information concerning Inspectorio’s SaaS products into clear, readable documents to be used by technical and nontechnical end users.
- Create in-application, in-line help and guidance to improve product ease of use.
- Compose technical documents including, but not limited to, software user manuals, training materials, installation guides, proposals, job aids, reference guides, whitepapers and other reports.
- To work closely with the Product Management and Development teams to develop in-application help and guidance. The ideal candidate will have a knack for grasping new technologies quickly and will enjoy writing, driving complex documentation projects, and producing a high volume of documentation and content with ease.

#  Requirements

- 3+ year experience writing technical documentation, with preference given to candidates with Software-as-a-Service or internet-related product experience.
- Must have excellent writing, editing, drafting, and verbal communication skills.
- Ability to grasp highly technical concepts and adapt documentation products to technical and non-technical audiences.
- Bachelor’s degree required, preferably in related field.
- Experience in CSS3 and HTML5 is a plus.
- Must be able to provide examples of past technical documentation work.

# Why it would be awesome to work with us
 **BE HEALTHY**
We recognize that our employees are the key to our success. Healthier employees are happier employees who perform well! We not only provide health insurance benefits, but we also get out of the office for fun activities like weekly soccer games.
 **HAVE FUN**
Having fun makes work much more enjoyable. We host company foosball tournaments and events to make sure our employees feel the love. Events may vary by office location, but the sentiment is the same: Fun matters.
 **COMMITMENT**
When you join Inspectorio, you join a team. You have our leadership’s commitment to treat all team members with respect. All our team members commit to performing the best for each other, and our customers.

# Contact
dao@inspectorio.com
www.inspectorio.com/careers/

**Comment by qcam** [comment]
@Dao-Nguyen The text looks good but could you update your post to comply with [Markdown syntax](https://guides.github.com/features/mastering-markdown/)?
