### ISSUE TITLE
INSPECTORIO - IT Admin - HCMC

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#772]
# Location: Ho Chi Minh City

# Salary: Negotiable

# About Us

At Inspectorio we are making our own software product, SaaS platform, that use IoT and Data to help retailers verify supplier compliance and bring transparency to their supply chains.

Founded in Hong Kong in 2015, Inspectorio is now headquartered in Minneapolis, with R&D lab in Ho Chi Minh City and offices in Hangzhou, Quito.

Our diverse team is comprised of Mathematician, Neuroscientist, Data Scientist to Pianist, Magician, Running Champion, Kendo Master, Wood Crafter…

We are the only Vietnam based Techstars company and are working with leading retailers and brands around the globe, our initial market focus on China and Vietnam, and expanding 5 new markets in 2017.
Get to know what Inspectorio is doing at: www.inspectorio.com

# Job Description

- Maintain the company IT network, internal servers and security systems. Most notably, the internet traffic load balancer, router, switch, access points and VPN.
- Support colleagues with basic IT needs. Setting up computers, installing various software as well as anti-virus.
- Manage MS Office 365, Jira and Confluence.
- Help to promote and enforce the company IT policies. This includes internet monitoring, security, and password policies among others.

# Requirements

- Good problem-solving skills.
- Effective interpersonal and communications skills.
- Effective organizational and time management skills.
- Working knowledge of IT operating systems, particularly Windows and Mac-OS.
- Hands on experience of installing IT hardware, software, firewall and IDS/IPS.
- Proven experience with network troubleshooting.
- Experience with ISO 27001 certification is a plus.
- Experience with MikroTik hardware and software is a plus.

# Why it would be awesome to work with us
**BE HEALTHY**
We recognize that our employees are the key to our success. Healthier employees are happier employees who perform well! We not only provide health insurance benefits, but we also get out of the office for fun activities like weekly soccer games.
**HAVE FUN**
Having fun makes work much more enjoyable. We host company foosball tournaments and events to make sure our employees feel the love. Events may vary by office location, but the sentiment is the same: Fun matters.
**COMMITMENT**
When you join Inspectorio, you join a team. You have our leadership’s commitment to treat all team members with respect. All our team members commit to performing the best for each other, and our customers.

# Contact
dao@inspectorio.com
www.inspectorio.com/careers/

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)?
