### ISSUE TITLE
INSPECTORIO - Product Owner - HCMC

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#773]
# Location: Ho Chi Minh City

# Salary: Up to $2500

# About Us

At Inspectorio we are making our own software product, SaaS platform, that use IoT and Data to help retailers verify supplier compliance and bring transparency to their supply chains.

Founded in Hong Kong in 2015, Inspectorio is now headquartered in Minneapolis, with R&D lab in Ho Chi Minh City and offices in Hangzhou, Quito.

Our diverse team is comprised of Mathematician, Neuroscientist, Data Scientist to Pianist, Magician, Running Champion, Kendo Master, Wood Crafter…

We are the only Vietnam based Techstars company and are working with leading retailers and brands around the globe, our initial market focus on China and Vietnam, and expanding 5 new markets in 2017.

Get to know what Inspectorio is doing at: www.inspectorio.com

# Job Description

- Act as Product Owner for one or several Scrum teams being the empowered central point of the Product Leadership as representative of the Business and Marketing areas.
- Business and Product analysis, Product Value delivery strategy and Product Vision communication.
- Active and close collaboration with the Delivery Manager and Product Manager.
- Create and communicate the Product Backlog and keep it well organized. Maintain it updated and by collaborating with the Scrum Team keep it groomed to allow the team estimations (ensure that backlog keeps DEEP property).
- Create good User Stories following INVEST principle. That including but not limited to wireframes, data flows, or any other material needed to transfer the requirements. The User Stories must have good descriptions taking into account the assumptions, restrictions and scenarios of the feature. Define Acceptance Criteria and verify that they are met.
- Participate in planning sessions: Product planning, Sprint Planning.
- Prepare and Participate in Groomings with the team.
- Participate on the Sprint Review and Sprint Retrospective.
- Be experienced and used to managing the priorities according to Return of Investment, Size, Roadmaps, and sprint commitments.
- Collaborate with the Development Team and be able to attend their questions in short time.
- Collaborate with Stakeholders and Influence them to align with the Product Vision.
- Work close with design team to improve UI-UX of mobile and web.

# Requirements

- Agile Knowledge and Experience: Agile principles knowledge and embracement and deep knowledge in Scrum methodology. More than two years of experience working as Product Owner.
- Domain Skills: Experience in Mobile and or Web solutions and E-commerce. Is a product visionary; Works with just enough anticipation in adaptive environments; Has Business and Domain expertise.
- People Skills: Is a good communicator; can build good relationships with stakeholders; Is a negotiator/consensus builder; Motivates the Scrum Team explaining the product vision; Experience working in a team-oriented, collaborative environment.
- Decision Making: Is empowered to make decisions; is willing to make hard decisions; Is decisive; Takes an economic view to balance business/technical tasks.
- Accountability: Accepts responsibility for the product; Is committed and available for. Acts like a Scrum Team member and not as a manager.
- Excellent written and verbal communications skills.
- Bachelor’s Degree or higher preferred.
- Leader able to make influence in stakeholders’ decision.
- Passion to create worldwide first class products.

# Why it would be awesome to work with us
**BE HEALTHY**
We recognize that our employees are the key to our success. Healthier employees are happier employees who perform well! We not only provide health insurance benefits, but we also get out of the office for fun activities like weekly soccer games.
**HAVE FUN**
Having fun makes work much more enjoyable. We host company foosball tournaments and events to make sure our employees feel the love. Events may vary by office location, but the sentiment is the same: Fun matters.
**COMMITMENT**
When you join Inspectorio, you join a team. You have our leadership’s commitment to treat all team members with respect. All our team members commit to performing the best for each other, and our customers.

# Contact
dao@inspectorio.com
www.inspectorio.com/careers/

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format)?
