### ISSUE TITLE
INSPECTORIO - Technical Architect - HCMC

### ISSUE THREAD

**Issue by Dao-Nguyen** [awesome-jobs/vietnam#775]
# Location: Ho Chi Minh City

# Salary: Up to $7000

# About Us
At Inspectorio we are making our own software product, SaaS platform, that use IoT and Data to help retailers verify supplier compliance and bring transparency to their supply chains.

Founded in Hong Kong in 2015, Inspectorio is now headquartered in Minneapolis, with R&D lab in Ho Chi Minh City and offices in Hangzhou, Quito.

Our diverse team is comprised of Mathematician, Neuroscientist, Data Scientist to Pianist, Magician, Running Champion, Kendo Master, Wood Crafter…

We are the only Vietnam based Techstars company and are working with leading retailers and brands around the globe, our initial market focus on China and Vietnam, and expanding 5 new markets in 2017.
 
Get to know what Inspectorio is doing at: www.inspectorio.com

# Job Description
• Lead with innovative technical solutions to improve our platform
• Identifying key business and technology drivers that impact application architectures. Such as user requirements, existing application environment and performance requirements.
• Provides guidance and institute best practices through design decisions, process, tools, and code
• Manage relationship and smooth integrations with our technical partners
• Help to build a strong ownership feeling

# Requirements
• As a Team Player, you value Innovation and Integrity. You believe that Excellence is the key to nurture the success
• Understand implications of design choices (Trade-offs of CAP theorem)
• Extensive knowledge, of, and experience of REST, service oriented and event-based architectures
• Experience working with cloud products (docker, k8s, AWS, GCP …)
• Agile expertise and mindset
• Proficient with git
• Extensive knowledge of the Python ecosystem is a plus
• Significant contribution to an open-source project and or a well-known product is a plus
• Experience working on a platform available on multiple zones is a plus
• Experience building your own team is a plus

# Why it would be awesome to work with us
**BE HEALTHY**
We recognize that our employees are the key to our success. Healthier employees are happier employees who perform well! We not only provide health insurance benefits, but we also get out of the office for fun activities like weekly soccer games.
**HAVE FUN**
Having fun makes work much more enjoyable. We host company foosball tournaments and events to make sure our employees feel the love. Events may vary by office location, but the sentiment is the same: Fun matters.
**COMMITMENT**
When you join Inspectorio, you join a team. You have our leadership’s commitment to treat all team members with respect. All our team members commit to performing the best for each other, and our customers.

# Contact
dao@inspectorio.com
www.inspectorio.com/careers/

**Comment by qcam** [comment]
@Dao-Nguyen Could you please update your job post to follow Markdown syntax?
