### ISSUE TITLE
SEEKING ReactJS Native - $1.3k USD

### ISSUE THREAD

**Issue by KevinColemanInc** [awesome-jobs/vietnam#776]
# ReactJS Native Developer [$1.3k USD]

![ReactJS native](https://www.progville.com/wp-content/uploads/2015/01/react-native-ios-javascript-825x510.jpg)

## Location

* _mostly_ remote (if you are in Saigon, we may meet once per week)

## Salary

* $1.2k USD / month
* Generous vacation policy

## Requirements

* Strong English skills
* 1 years reactjs
* 2-3 portfolio projects
* Contract 40hrs / week for 1-2 months

## Project description

Think Tinder, but *much more serious*.

At XOME, we are building a next generation social media mobile and web app to cultivate serious dating relationships in SEA.

We are a team of expat developers from San Francisco that have worked at CareerBuilder.com, Hired.com, and PayPal.  We use Ruby on Rails and Docker to power our backend on AWS.

## Nice to have

* GraphQL
* Reactjs Native
* VoIP and chat communications

## You can bring

* A good eyes for design
* Laptop

## Why it would be awesome to work with us

* Career mentorship
* Meet our angel investors
* No overtime.

We have a "Get things done" culture.  We look for results, not how long you have been sitting at a desk all day.

## Interesting Engineering Problems

* Real time communication
* GraphQL
* VoIP and Video conferencing
* Docker

# Contact

Please send CV and portfolio links (github, blog, etc.) to kevin.coleman@sparkstart.io

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job title and description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), please note that all `REQUIRED` sections must be filled.
