### ISSUE TITLE
Outco Inc. - Algorithms Interviewer - Remote - FT/PT/C

### ISSUE THREAD

**Issue by andyttran** [awesome-jobs/vietnam#779]
## Location

* Remote

## Salary Expectation

* Competitive, Negotiable

### Must Have

* Fluent/Native in English Speaker
* Strong communication skills
* Strong knowledge algorithm and data structures
* Proficiency in at least one of the following languages: JavaScript, Java, Ruby, Python, C++, C#, Swift
* Bachelors Degree in Computer Science or Equivalent
* Be available to work a few hours in between 8AM-8PM PST 
* Strong internet connection: 20Mbps up and 5Mbps down

### Ideally

* 2 years+ experience in software engineering
* Proficient in Java or C++ as well as 2 or more of the following languages: JavaScript, Ruby, Python, C#, Swift

### Responsibilities

* Conduct coding interviews with other software engineers. 
* The coding interviews involve asking a set of 2-3 algorithms questions in 40 minutes.
* Also reading from a script of about 5 interpersonal questions totaling 20 minutes.
* A typically 60 minutes in length.
* Report back feedback on a grading scale on communication and technical ability

### You’ll be responsible for

Screening software engineering candidates that apply for our career accelerator program. 

### Why it would be awesome to work with us

Outco Inc. is a fast-growing startup that accelerates the careers of software engineers. We know what it takes to develop create engineers. Join a team whose mission is to help others unlock their full potential.  Develop yourself into an algorithms master, and develop skills that will strengthen your professional communication skills. 

- Highly competitive salary
- Flexible work schedule (set your own hours)
- 100% fully remote
- Growth opportunities to quickly expand role and responsibilities.

### Contact
Site: https://outco.io  
Andy: andy@outco.io

**Comment by T-Pham** [comment]
This kind of job seems interesting!

**Comment by Anphamthanh** [comment]
Is this a one-time job? It looks like you need someone to screen *a qualify candidate* or was it a typo?

**Comment by KevinColemanInc** [comment]
@Anphamthanh Not OP, but if you look at the poster's company, their business is to train job seekers in the interviewing process.

My guess is they need someone to help practice interviewing with their clients.

**Comment by Anphamthanh** [comment]
Thanks @KevinColemanInc. I checked their website out. It is an interesting market and they seem to be doing well. I am pretty sure it was a typo.

**Comment by TanNgocDo** [comment]
Maybe the qualified candidates should have an opportunity to join their training programing too

**Comment by andyttran** [comment]
Hey @Anphamthanh that was indeed a typo, I'll make a fix.  

@KevinColemanInc thanks, you are right on point.  We are looking for someone to help screen candidates that want to join our program.  The responsibilities can later be expanded to help provide practice mock interviews with students and alumni of the program.  

@TanNgocDo definitely!

**Comment by TanNgocDo** [comment]
Can you share your interview process: screening, coding interview ...... ?

**Comment by andyttran** [comment]
@TanNgocDo our interview process will have a phone screen (10-20 minutes), then a technical live coding challenge (60 minutes), followed by a behavioral interview with the founders (30-60 minutes).
