### ISSUE TITLE
Schola - Full Stack Developer (PHP, JS) - Singapore & Saigon - FT

### ISSUE THREAD

**Issue by tranlethanhnhu** [awesome-jobs/vietnam#787]
## About Us 
 
Schola is a Singapore based company, with offices both in Singapore and Ho Chi Minh city. You will be working with a high energy and experienced team - ex-Facebook Product Managers, Senior Software Engineers and more.

Schola is on a mission to revolutionise online education and provide wider access to students around the world, access to quality teacher and content. The platform we are building is purely LIVE interactions and LIVE video based, which will increase the effectiveness of the learning experience. We are also making learning fun, by building AR tools, micro games and in video interactivity features. By joining this company at its early stage you will have the opportunity to build amazing product, work in an innovative and independent environment, learn and grow very fast in your career - that is a promise! 

You should love programming, rapid development, work in an agile environment, be a team player and have good communication.
Stack - PHP, MySQL, WebRTC. Future Development Opportunities - iOS, Android etc.

Come join us in this multi-million dollar opportunity and make a difference to Vietnam and around the world!

## Location 

• Singapore & Saigon 

## Salary Expectation 

• Up to 1200 USD/month based on experience 

## Requirements 

• 1+ years’ experience in application development. 
• Should be smart and have the ability to figure out optimal solutions
• Have minimum of an Undergraduate degree from a renowned university
• Strong understanding of PHP back-end development
• Strong understanding of front-end technologies, including HTML5, CSS3, JavaScript, jQuery
• Knowledge of how to create and interact with RESTful APIs and formats (JSON, XML)
• Proficient understanding of code versioning tools - SVN
• Must be a good communicator, can communicate in moderate English and be a team player.

## Responsibilities 

• Designing and implementing new features and functionality
• Establishing and guiding the website’s architecture
• Ensuring high-performance and availability, and managing all technical aspects of the Website
• Be a critical thinker and communicator
• Take ownership of specifications, work breakdown, planning and scheduling. Communicate regularly with product management team
• Growth Hacking and RAPID development.
• Maintain code quality, integrity and responsiveness of the applications. Provide assistance to team members
• Be data driven in measuring performance, efficiency and decision making.

## Benefits 
• Build a next BIG Billion dollar company 
• Work directly with CTO and other talented engineers (ex- Facebook, ex-Garena employees)
• Minimum 3-month working in Singapore office every year. Visa sponsored for foreigners
• Free lunch and snacks every day
• International, fast-paced, and friendly working environment
• Medical insurance paid by company

## Contact 
• Apply directly to recruiting@schola.tv. Please provide your resume/CV, as well as any additional items (such as a portfolio, GitHub username, or links to projects you’ve completed) that appropriately describe your accomplishments, skills and responsibilities.
• For more information, please contact Aditya Gupta (adityag@schola.tv)
• Website: https://schola.tv/

**Comment by qcam** [comment]
@tranlethanhnhu Could you please update your job post to follow Markdown syntax?
