### ISSUE TITLE
CodeLynx - Full Stack Developer (JavaScript/Node.js) - Binh Thanh/HCMC

### ISSUE THREAD

**Issue by hongquy6691** [awesome-jobs/vietnam#789]
## Location
* Ho Chi Minh, Binh Thanh district, Vinhomes Central Park, 208 Nguyen Huu Canh 

### What You Will Do
CodeLynx is a start-up from Israel. Our founder is an Israelic with about 17 years experience in software development. We are doing our own products as well as projects for our clients. With that foundation, we have many innovative ideas and a belief to bring it to real life. We welcome you to join us and together we make it come true real soon.
CodeLynx is looking for a Developer with excellent coding skills to join the team. We are seeking developer who loves programming and can apply it to building web apps and mobile apps that support thousands to millions of users. We’re looking for talented people who want to learn a lot and build amazing things.
Joining us at CodeLynx will give you the opportunity to use your skills to the fullest capacity, and to know that what you do has major influence in a young and dynamic team. Our say is “Born to code, no plan B”
As our Developer, your responsibilities will include:
●	Analyze requirements and design solutions
●	Create fully functional websites or mobile Apps
●	Research new technologies

### What You Are Good At
The ideal candidate for Full Stack Developer position should have the following qualifications:
●	B.Sc. in Computer Science / Software Engineering (or similar) or have exceptional coding skills.
●	Strong JavaScript skills
●	Strong with Node.js
●	Familiar with JavaScript frameworks (e.g., React.js, jQuery, Angular.js, jQuery, Bootstrap)
●	Experience with using Git
●	Experience with using databases like Mongodb, MySQL, Redis
●	Familiar with C++, .NET
●	Good at Machine Learning, Python
●	Excellent communicator
●	Good level of English
    
Bonus Points
●	Experience with Meteor
●	Experience with React Native - Major advantage.
●	Devops experience

### What We Offer
Being a Full Stack developer at CodeLynx, you will experience a dynamic, flexible and creative work environment
●	Attractive salary and annual salary review
●	Working in a professional, friendly, international environment
●	Exposure to new and emerging technologies
●	Free gym and swimming pool services in Vinhomes residential 

## Salary Expectation
* 800$ - 1200$

### Contact: Ms. Quý
* Email: quy.nth6691@gmail.com
* LinkedIn: https://www.linkedin.com/in/nguy%E1%BB%85n-th%E1%BB%8B-h%E1%BB%93ng-qu%C3%BD-01972992/
* Facebook: https://www.facebook.com/profile.php?id=100006652366003
* Skype: hongquy6691
* Tel number: 09727.09390

**Comment by qcam** [comment]
@hongquy6691 Could you please revise your job post to follow Markdown syntax?
