### ISSUE TITLE
Robert Bosch Engineering Vietnam - Fresher Embedded Software Developer - HCMC - FT

### ISSUE THREAD

**Issue by trnhuphung** [awesome-jobs/vietnam#802]
**_Robert Bosch Engineering and Business Solutions Vietnam Company Limited (RBVH)_**, is a 100% owned subsidiary of Robert Bosch GmbH, one of the world’s leading global supplier of technology and services, offering end to end engineering, IT and business solutions. Founded in October 2010 at Ho Chi Minh City, RBVH is the first state-of-the-art software development center of Bosch in the South East Asian region. RBVH provides solutions for businesses in the following areas: Engineering services, IT services, Business services.

## **Location**

- Etown 2, 364 Cong Hoa, Tan Binh District, HCMC

## **Salary Expectation**

- Competitive

## **Your Contribution to Something Big**

- Analyze requirements, design and develop embedded software/test suites. 
- Research new technology, new method and be a pioneer in embedded Software development/Testing.
- Assist technical experts to implement the advanced solutions for automotive challenges.
- Develop and execute unit and functional tests. 
- Document design, design changes and updates.

## **What distinguishes you**

- Strong in C/C++ language Programming
- Exposure to Micro-controllers or Microprocessors
- Base knowledge of embedded system design methodology.
- Good English language skills (Reading, Writing, Speaking and Listening) 

## **Your future job locations offer you**

- Work in a dynamic and fast growing global company.
- Advanced career development with overseas training and working opportunities.
- Minimum 15 annual leaves and 1 day leave on your birthday per year.
- Health insurance for employees and family.
- Lunch and parking allowances.
- Join in various team building and sport activities.
- 13th-month salary and annual bonus.
- Annual performance appraisal.

## **Contact**

- Email: phung.trannhu@vn.bosch.com
- Linkedin: www.linkedin.com/in/phung-tran-32b2729b
- Phone: (+028) 3812 8206

**Comment by qcam** [comment]
This job has been expired!
