### ISSUE TITLE
Qamera - Front End Developer - Saigon - C

### ISSUE THREAD

**Issue by leonatqamera** [awesome-jobs/vietnam#803]
## Location

* Dist 1, Saigon, Vietnam

## Salary Expectation

* $600 - $1,000

## Requirements
* Proven JavaScript development experience
* Experience in UI based JS framework like Node JS is preferable.
* Familiar with Grunt, Gulp, Webpack
* Solid knowledge of markup HTML5, CSS3
* Familiar with Content Management Systems (such as WordPress or Drupal)
* Familiar with WordPress theme, Bootstrap.
* Experience in cross-browser debugging and testing
* Knowledgeable in latest standards for responsive design
* Basic understanding of CSS pre-processing platforms, such as LESS and SASS is a plus
* Can use Photoshop, Illustrator, Sketch App (plus)
* Have knowledge in UI UX is an advantage
* Be an evangelist for learner-first mindset

### Must Have

* JavaScript
* HTML5
* CSS3

### Ideally

* Experience with Node.JS
* Experience with Grunt, Gulp, Webpack
* Experience with Content Management Systems (such as WordPress or Drupal)

### You can bring

* A good eyes for UI/UX design
* A good knowledge of latest standards for responsive design

## Responsibilities

* Assist in one of our current projects which is the creation of eLearning courses around cyber-security training.
* In this role, you will be rewarded with an opportunity to learn about design processes across the end-to-end publishing life cycle. Also, you can expect to further your experience with prototyping new ways of showcasing online training content within the context of a Content Management System.
* You will be working with a distributed delivery team that consists of designers, animators, instructors, and developers. This role will help you build skills in new web-based authoring frameworks and content delivery systems.

## Why it would be awesome to work with us

* Meaningful work with international experienced designers and developers;
* Huge opportunity for professional development by learning the latest design and development techniques;
* Enjoyable work in flexible, fun and motivational space;
* Very attractive salary based on skills, experience and contributions;
* Meaningful relationship bonded with friendly members in company retreats, celebrations and leisure activities;
* Meaningful recognition for your effort with wide array of rewards and benefits;
* Chance to go to United States for training or business conference.

## Contact
Email: huy_at_qamera_dot_com
[FRONT END DEVELOPER JD.pdf](https://github.com/awesome-jobs/vietnam/files/1558007/FRONT.END.DEVELOPER.JD.pdf)

**Comment by qcam** [comment]
This job has been expired!
