### ISSUE TITLE
Reachoo - Senior Ruby on Rails developer - San Francisco, CA, USA / Remote - Contract

### ISSUE THREAD

**Issue by quinnie0930** [awesome-jobs/vietnam#808]
Reachoo is classifieds app, allowing users to post ads directly for their classified listing. Reachoo is currently serving hundreds of thousands monthly, supporting more than 1000 locations from all over the world across different verticals like housing, for sale, services, jobs and dating. 

## Location
- San Francisco, California, USA
- Remote
## Salary Expectation
- $1500-2200/month - Contract for 2 months
## Requirements
- B.S in Computer Science
- At least 4 years experience with Ruby On Rails
- JavaScript (React JS,  Angular, etc)
- PostgreSQL
- 5+ years Software Engineering experience
- Use TDD for their code
- English proficiency
- involve and contribute to open source community
### Responsibilities

- Redesign reachoo.com with new Ruby and Rails front end to back end but keep current database schema
- Elasticsearch for search
- XML API for different users to import ads into our system
- Each ad attributes/models are similar to craigslist.org.
- Post ad functionality
### Contact

Email resume and github account to quynhpham at gmail dot com

**Comment by qcam** [comment]
@quinnie0930 Could you please provide more information about the position and also update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), with `REQUIRED` sections filled?
