### ISSUE TITLE
Silicon Straits Saigon - Back end developers - HCM, Vietnam - FT

### ISSUE THREAD

**Issue by khaiql** [awesome-jobs/vietnam#81]
![SSS Logo](http://blog.siliconstraits.vn/wp-content/uploads/2013/08/SS-Final-Logo-200x200.png)
# Who we are

**Silicon Straits Saigon** is a Product Development Lab that works with startups and enterprises in South East Asia to help build and launch new and exciting web and mobile products. We don't just develop softwares or apps, we build PRODUCTS and BUSINESS.
We have the best office in town to provide not just a cool working environment but also the playground for all hackers, builders and makers like yourself to build the next big thing.

Company Size: 50+
Our website: http://siliconstraits.vn/
## Location
- Saigon, Vietnam
## Salary Expectation
- $800 - $1500/month
### Senior back-end developers
- At least 2 years experience in Ruby and Ruby on Rails framework is required.
- Solid knowledge of OOP, TDD, clean code...
- Ability to quickly adapt new technologies.
- Experience in scaling and optimizing web applications.
- Experience in other back-end technologies.
### Junior back-end developer
- Experience in Ruby on Rails.
- Have knowledge of OOP.
- Ability to quickly adapt new technologies.
### Ideally
- Experience in front-end JS frameworks, such as React, Angular, Ember....
- Knowledge of UI/UX.
- Professional (or hobby) mobile development experience.
### Other great things
- Great opportunities to improve your skills in many related fields.
- Working with other talented developers, designers and product managers.
- Flexible working time and unlimited leave days.
- Get your own Macbook.
- Free classes (English class, UI/UX class...)
- Nice bosses.
- Geek Toys.
- Take part in our exciting events (Hackathon, Drinkathon,…)
### Contact us

If you are an outstanding back-end developer and want to be part of this crew, solve our [online puzzle](http://hiring.siliconstraits.vn/) and tell us about yourself!

**Comment by danhnguyenvh** [comment]
@khaiql the possition of senior back-end still available now?

**Comment by danhnguyenvh** [comment]
@khaiql the possition of senior back-end still available now? 
Thanks.

**Comment by khaiql** [comment]
Hi @danhnguyenvh and all, we are still hiring, let me know if you have any question. Thanks

**Comment by danhnguyenvh** [comment]
@khaiql Thank you for you reply. I have experienced 3 over years with RoR (almost back-end).
How can i contact with you? My email: danhnguyenvh@gmail.com
Thanks.

**Comment by Anphamthanh** [comment]
@danhnguyenvh Do you not read the posting?!?! 
"If you are an outstanding back-end developer and want to be part of this crew, solve our online puzzle and tell us about yourself! "
http://hiring.siliconstraits.vn/

**Comment by khaiql** [comment]
@danhnguyenvh please try our small quiz on http://hiring.siliconstraits.vn/. It would be great if you have any side project that you can share source code to us. We would use it to assess your coding skill. Looking forward to receive your application. Thanks.

**Comment by danhnguyenvh** [comment]
@khaiql I have tried your small quiz on http://hiring.siliconstraits.vn/.
I has gone to http://www.geeky.vn/cli console to register.
But i got "Failed!" result when try run "register <MD5hash>".
What is wrong something?

Another question: Will i submit my project to share source code to you by Geeky.vn or where? 
Thanks

**Comment by khaiql** [comment]
@danhnguyenvh we don't receive application as usual way, you have to solve our hiring quiz (see the QR Code, right?). This is the first step for us to assess your ability. Geeky is something you can take for fun.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by khaiql** [comment]
@joneslee85 I updated the content, please check

**Comment by joneslee85** [comment]
@khaiql perfect, thanks
