### ISSUE TITLE
fram^ - PHP Freelancer/ PHP Developer (3 month contract) - HCMC - FT

### ISSUE THREAD

**Issue by framvietnam** [awesome-jobs/vietnam#815]
# **fram^ Vietnam**
https://wearefram.com/
hao.nguyen@wearefram.com
TNR Building, 180 - 192 Nguyen Cong Tru, Nguyen Thai Binh Ward, Ho Chi Minh city, Vietnam

Email CV to hao.nguyen@wearefram.com

## Salary Expectation

* 25,000,000 VND - 40,000,000 VND gross 

## Responsibilities
You will join a dynamic development team and develop our e-commerce product for the car industry. You can code independently but team support is always available.

## Skills
* PHP
* MySQL
* SEO
* Wordpress

### Must Have

* 2-3 years experience in PHP programming
* Experience in MySQL
* Experience in SEO development
* Having knowledge or experience in Wordpress is a big plus
* Good English command is an advantage

### Job duration and location
- 2-3 months (From the beginning of Feb 2018 - Apr 2018)
- 160 hours/ month
- Venue: fram^ office

### Contact point
hao.nguyen@wearefram.com (Skype: haominhtn)

**Comment by qcam** [comment]
@framvietnam Please write more information about the position. Also the title needs to be updated accordingly if this is not a full-time (FT) job.
