### ISSUE TITLE
Yojee - Backend/Senior Backend Engineer (Elixir) - Saigon - FT 

### ISSUE THREAD

**Issue by vnnoder** [awesome-jobs/vietnam#823]
## Location

* Saigon, Vietnam

## Salary Expectation

* Competitive remuneration, in the top range of the market

## Skills

* Experienced and proficient working with at least two languages, preferrably Elixir, Ruby or any functional programming language.

### Must Have

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* Minimum 2 years of relevant backend development experience.
* Attention to detail and reliability are what you take pride in.
* You enjoy driving things over getting tasks assigned
* You are willing to learn new technologies

### Nice to have

* Experience with Elixir/Phoenix is not required
* Experience with Microservice architecture 
* DevOPs experience with Heroku, AWS or Azure

### Responsibilities

Yojee is looking for a Backend Engineer who enjoys developing and designing backend services in a cloud platform environment with Elixir/Phoenix. Together with the team,  you will have ownership of the services you build, and you love to share your ideas regarding architecture and functionality. 

### Why it would be awesome to work with us

Our mission is to bring the hundreds of thousands of logistics companies into the digital era, the same way the web browser enabled consumers and sellers to trade online securely.

We are a young team of software engineers who are enthusiastic about using the right technologies for the right job, while sticking to best practices and keeping the quality high. This approach helped us to create a platform that reliably handles millions of transactions. We have a strong engineering culture and embrace bottom up decision making.

The engineering team in Vietnam is responsible for building a scalable and modular SAAS backend api with Elixir and Phoenix. Our platform allows traditional logistic companies to be able to provide services similar to Giao Hang Nhanh. We are building features to support international shipment and a blockchain to connect our clients into one Yojee Network. 

Our office is at Circo Hoang Dieu, District 4.

### Contact

Please send your resume to hiring.vn@yojee.com

**Comment by enixdark** [comment]
@vnnoder sorry,  althought i don't see remote job however i still want to ask to apply for this job if your company accept remote ?

**Comment by vnnoder** [comment]
@enixdark @Gnouc We don't have plan for remote office in Vietnam apart from Ho Chi Minh yet. May I know which city are you from?

**Comment by enixdark** [comment]
@vnnoder I come from Ha noi,  I'm looking for job which use Erlang/Elixir and FP style.

**Comment by vnnoder** [comment]
@enixdark we will notify you if we open an office in Hanoi.

**Comment by anhnt14** [comment]
@enixdark Do you wana try other job in hanoi, send me your CV to anhnt14@topica.edu.vn

**Comment by enixdark** [comment]
@anhnt14 ah sorry currently, i'm only looking for a job relate to use functional with Elixir/Erlang or some pure functionals such as Haskell , if you have a job relate to it, please notify to me.

**Comment by namhoang1604** [comment]
is this position empty? I want to apply this job

**Comment by vnnoder** [comment]
@namhoang1604 sorry, this position is no longer available

**Comment by hongngocanhthu** [comment]
@namhoang1604 : Hi Nam, please contact me for Elixir job. We are hiring this vacancy for Sendo.vn.

**Comment by namhoang1604** [comment]
@hongngocanhthu Please send me job detail.
hoangxuannam160493@gmail.com
