### ISSUE TITLE
Junior System Engineer

### ISSUE THREAD

**Issue by hanxkang** [awesome-jobs/vietnam#826]
## Location

* Vinhomes Central Park, Saigon, Vietnam

## Salary Expectation

* $450 - $700/month

## Skills
* 1+ years experience working as System Admin.
* Experience with AWS, GCP.
* Experience with Linux System (CentOS, Ubuntu).
* Knowledge in scripting (Bash, Python).
* Knowledge in system monitoring, metrics, logging tools (Graylog, Prometheus, ELK).
### Must Have

* Laptop 
* Product company mindset (not outsource)
* Desire to learn and grow

### Responsibilities
* Install, configure and maintain systems and applications.
* Managing incidents and problems on a daily basis to minimize downtime on customer activities.
* Understand customer demands and propose best solutions.
* Troubleshoot system and applications issues.
* Maintaining documents, procedures and technical guides
* Report to the team leader about activities and projects.

### You’ll be responsible for

* In charge of the system of Meete

### You can bring

* Laptop
* A good analysis skill

### Why it would be awesome to work with us

* Startup environment enable you to be trained, learn and lead.
* Yummy home-cooked lunches also more nutritious
* Free sport activities: gym, swimming, badminton’s place,...

### Interesting engineering projects
* Our full strategic project for 2018 is waiting for you

### Contact
Homepage: https://meete.co
Send CV to: hr_at_meete_dot_co (01655294994)

**Comment by huydx** [comment]
Close due to wrong format
