### ISSUE TITLE
SourceSage - Senior Software Engineer - HCM - Remote - FT

### ISSUE THREAD

**Issue by jianminsim** [awesome-jobs/vietnam#827]
## Location

* Saigon, Vietnam
* At HCM Office

## Salary Expectation

* $1000-2000/month depending on experience

## Requirements
•Experience with React
•Experience in TypeScript/JavaScript
•Experience writing tests for code
•Good understanding of web technologies like HTML5, CSS, DOM, & browser APIs.
•Experience in iOS or Android is a plus

### Must Have
•Experience with React
•Experience in TypeScript/JavaScript
•Experience writing tests for code
•Good understanding of web technologies like HTML5, CSS, DOM, & browser APIs.
•Experience in iOS or Android is a plus

### Ideally
•Experience with React
•Experience in TypeScript/JavaScript
•Experience writing tests for code
•Good understanding of web technologies like HTML5, CSS, DOM, & browser APIs.
•Experience in iOS or Android is a plus

### Responsibilities
Great power comes with great responsibilities!

### You’ll be responsible for
* Frontend or Backend

### You can bring
Your skillsets and also an impact to the real-world with your skills!

### Why it would be awesome to work with us
Our current frontend stack is built using React ecosystem, these include: Redux, Typescript, webpack, jest, etc. over web browser and mobile webview platforms. If you have experience with these technologies and you enjoy developing UI for users, we would love to speak to you!

•Travel very regularly to Singapore for team meetups and also to work with our product team in Singapore on a game changing product which impacts the physical commodity space
•Competitive salary
•Work from our Co-Working Space in Ho Chi Minh, and work with other engineers and business development manager

### Interesting engineering projects
Reactnative, Erlang & EJ, and various cool technologies you can be using
Change the world of physical commodity by joining us today!

### Contact
Sim Jian Min
jian.sim@sourcesage.co (+6591508236)

**Comment by qcam** [comment]
@jianminsim Could you please update your post to follow [Markdown syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)?
