### ISSUE TITLE
Junior/Senior JavaScript Developer (ReactJS and NodeJS)

### ISSUE THREAD

**Issue by duyenho94** [awesome-jobs/vietnam#828]
## Location
Tan Binh District, Ho Chi Minh City, Vietnam

## Salary Expectation
You will love it

## Skills
_Opportunity to work with new front-end technologies, which is a growing and unavoidable technology trend for programming enthusiasts, especially those who want to be full-stack developers_

- Good at HTML5, CSS3 and JavaScript
- Strong at least one of professional programming foundation by:
             * Extensive experience in any programming platform (preferable Java, .NET or PHP)
             * Experience building web-based complex application, or enterprise applications
             * Write high-quality code and tests
- Strong passion and commitment to learn and work with modern JavaScript frameworks/libraries (ReactJS, AngularJS, NodeJS, …)
- Ability to quickly learn and use new technology to write great codes and build great software
- Competent in English and has the ability to communicate with native English speakers effectively

### Responsibilities

- Love Coding.
- Follow Your Passion.
- Enjoy Every Single Working Day with Your Nice Colleagues and Our Kind Clients.
- Take Your Skill to the Next Level.
- The responsibility includes: design, coding, troubleshooting and working with project team as well as customers on features/bug fixes. 

### Why it would be awesome to work with us

- Working in one of the Best Places to Work in Vietnam
- Building large-scale & latest technology software products
- Working & growing with Passionate & Talented Team
- Attractive Salary and Benefits
- Performance appraisal twice a year
- Onsite opportunities: short-term and long-term assignments in U.S
- Flexible working time
- Various training on hot-trend technologies, best practices, and soft skills
- Premium health care insurance for you and your loved ones
- Company trip in every summer, big annual year-end party every year, team building, etc.
- Fitness & sports activities: football, tennis, table-tennis, badminton, yoga, swimming…
- Joining community development activities: 1% Pledge, charity every quarter, blood donation, public seminars, career orientation talks,…
- Free in-house entertainment facilities (foosball, ping pong, boxing, gym…), coffee (latte, cappuccino, espresso) and snack (instant noodles, cookies, candies…)
- And much more, join us and let yourself explore other fantastic things!

### Contact
Homepage: https://careers.kms-technology.com/all
Email: duyenho@kms-technology.com
Skype: honey_duyen
Hotline: 0938118997

**Comment by huydx** [comment]
close due to wrong format
