### ISSUE TITLE
Multiple Senior Engineer - Java/Ruby/Scala/Haskell in Fintech 

### ISSUE THREAD

**Issue by enalim** [awesome-jobs/vietnam#829]
Based in District 1, Ho Chi Minh City

An opportunity with a Singapore-based Fintech building a powerful web platform to be the 'Google' for lifestyle products.

* Saigon, Vietnam
* Min USD1,700/month onwards

## Requirements
* Java and ( Scala / Haskell / Ruby / Python / PHP / Elixir)
* Knowledge of TDD, BDD, CI, CD
* Experienced in managing high traffic web platforms
* 5+ years Software Engineering experience

What to expect:
* International exposure
* High engineering culture
* Highly technical leaders 
* Room to explore => career growth
* Opportunity to be part of the pioneer team, be the key influential figure in technical decision that shapes the processes

Interested/referral, please email to ena.lim@cogsagency.com | SkypeID: ena.is.here
*Reward programme applicable for successful referral

**Comment by huydx** [comment]
close due to wrong format
