### ISSUE TITLE
[GoBear] (Senior) Software Engineer - Java + 1 other Functional Programming Language - FT

### ISSUE THREAD

**Issue by enalim** [awesome-jobs/vietnam#833]
## Location

* Ho Chi Minh City, Vietnam

## Salary Expectation

* Min US$15000/month 

## Requirements
* Java
* 1 other functional programming language e.g. Scala, Haskell, Ruby
* PostgreSQL
* Knowledge of TDD, BDD, CI, CD
* 5+ years Software Engineering experience

### You’ll be responsible for

* Be the technical advisor to the business in building a highly scalable platform with optimized performance that able to handle the high load traffic

### Why it would be awesome to work with us

* Attractive salary pay grade
* A team of highly skilled engineers
* A leader that highly technical that can lead and hands-on at the same time
* Flexible working hours
* International exposure

### Contact

* Multiple positions available
* For application, please email ena.lim@cogsagency.com / Skype @ ena.is.here

**Comment by qcam** [comment]
Hi @enalim Hi, is this an in house position for your company? Or are you recruiting on the behalf of your client? Please note that we are only accepting ads for in house position at the moment.

Please also be more informative about the company and the job.

This job will be temporarily closed and I will reopen when the description is improved.
