### ISSUE TITLE
TOPICA - PHP DEVELOPER $800-$1500 -HN VIETNAM

### ISSUE THREAD

**Issue by anhnt14** [awesome-jobs/vietnam#834]
## Location

* HN, Vietnam Fulltime job

## Salary Expectation

* $800 - $1200/month or range

## Requirements
[RECRUITMENT] PHP DEVELOPER CHANCES YOU GET UPON JOINING US
--
- Being trained to become full-stack developer
- Receiving income up to $1500/month
- Experiencing 3 key projects with different technology in 12 months, belonging to 5 products in 6 countries: Vietnam, Singapore, Phillipines, Thailand, Indonesia, USA
- Being instructed and guided by top seniors, who has successfully built technology products for millions users
- Having 2 Free Days each month (no work) for new technology research: AI, Machine Learning, AR, VR, IoT,... or your favorite technology
- Working in young, energetic, straight-forward startup environment with boosts to your creativity and development
- Getting evaluation every 6 months and getting salary raise, getting promoted with chances to get raise 50-80% of previous income per year.

IF YOU ARE:
--
- From 22 to 26 years old
- Develop fluently at least 1 backend programming language as PHP, .NET, Python, NodeJS, Java,...
- Have knowledge in at least 1 database management as MySQL, SQLserver, MongoDB,...
- Have advantage with experiences in Javascript (Angular2, TypeScript, jQuery), HTML, REST API-s
- Good logic thinking
CLICK TO JOIN NOW

### Contact
Send me an email with your CV: Mr. Anh
Email: anhnt14@topica.edu.vn
Phone: +84949308575

**Comment by huydx** [comment]
please review our format
