### ISSUE TITLE
Google Adwords

### ISSUE THREAD

**Issue by TUYENDUNG-ITBIZ** [awesome-jobs/vietnam#837]
Mô tả công việc:
-	Lập kế hoạch và triển khai tất cả các chiến dịch quảng cáo Google Ads.
-	 Thực hiện và tối ưu các chiến dịch chạy quảng cáo Google Adwords cho khách hàng, đảm bảo KPIs cam kết với khách hàng.
-	 Tìm hiểu nghiên cứu các sản phẩm, dịch vụ mới mà Google mới phát triển.
-	Hỗ trợ phòng Triển khai dịch vụ và hoàn thành các KPIs.
-	 Lên kế hoạch và làm brife cùng đội Sale (nếu cần).
-	Tiếp nhận và thực hiện các chiến dịch quảng cáo Google Ads cho từng sản phẩm theo yêu cầu của giám đốc và Marketing Manager, chi tiết phù hợp với chiến dịch Marketing cho khách hàng của công ty.
-	Theo dõi, phân tích, thống kê các số liệu, hiệu chỉnh và tối ưu các chiến dịch quảng cáo (thiết kế, nội dung, chi phí và tỷ lệ chuyển đổi của các chiến dịch quảng cáo đảm bảo kết quả theo đúng lộ trình và mục tiêu đề ra).
-	Lập báo cáo kết quả chạy quảng cáo theo tuần, tháng.
-	 Liên tục theo sát, tối ưu hóa từng nội dung để mang lại hiệu quả cao nhất cho từng chiến dịch quảng cáo.
-	Đảm bảo các tài khoản quảng cáo luôn có đủ tiền để phục vụ cho các chiến dịch.

Quyền lợi:
-	Lương: 400$ - 700$
-	Chính sách thưởng phong phú: Thưởng hiệu quả công việc + Thưởng dự án + Thưởng nhân viên xuất sắc + Thưởng khác
-	Tăng lương 2 lần/năm
-	Cơ hội thăng tiến sớm nhất
-	Chế độ BHXH theo pháp luật quy định
-	Làm việc trong môi trường thân thiện, năng động
-	Cơ hội được đào tạo và phát triển bản thân một cách chuyên nghiệp nhất

Yêu cầu công việc:
•	Trình độ học vấn:
-	Tốt nghiệp cao đẳng trở lên chuyên ngành liên quan.
-	Ưu tiên có chứng chỉ Google search + display, am hiểu về quảng cáo PPC.
•	Kinh nghiệm làm việc:
-	Có ít nhất 1 năm kinh nghiệm ở lĩnh vực quảng cáo trên Google adwords/ nắm rõ các chiến lược và cơ chế quảng cáo.
-	Tối ưu tốt các case về di động, CPA (install, order, like, tương tác, đăng ký, …), CTR và theo analytics là 1 lợi thế.
•	Kỹ năng/ Phẩm chất cá nhân:
-	Khả năng làm việc độc lập, làm việc nhóm tốt.
-	Khả năng xử lý tình huống tốt.
-	Cập nhật nhanh chóng kiến thức chuyên môn cũng như các tính năng mới từ  Google Adwords.
-	Có khả năng sử dụng Tiếng Anh cơ bản. 
-	Năng động, nhiệt tình.
-	Trách nhiệm công việc cao.

Ứng viên Gửi CV về email: tuyendung@itbiz.vn
Hoặc liên hệ bộ phận nhân sự theo SĐT: 0936289999

**Comment by huydx** [comment]
stop this kind of suck job post
