### ISSUE TITLE
[ITBIZ] PHP DEVELOPER - HA NOI - FT

### ISSUE THREAD

**Issue by TUYENDUNG-ITBIZ** [awesome-jobs/vietnam#842]
## Location
Ha Noi

## Salary Expectation

* Up to $1200/month 

## Requirements
•	College degree or higher with major:  Software Engineer/ Information Technology
•	Junior: At least 1 year professional web service development experience with PHP Framework.
•	Senior: At least 3 years professional web service development experience with PHP Framework
•	Worked with HTML5 and CSS3, JavaScript
•	Strong understanding of PHP back-end development
•	Experienced in Laravel, Yii, Zend framework

### Responsibilities

•	Making the project of company (backend & frontend)
•	Establishing, managing and developing the website
•	Ensuring high-performance and availability, and managing all technical aspects of the Website
•	Be data driven in measuring performance, efficiency and decision making

### Why it would be awesome to work with us

•	Getting 13th month pay every year as company rule;
•	Company trip once a year
•	Friendly & active working environment
•	Project based bonus, public holidays bonus pursuant to Vietnamese labor legislation
•	Social insurance, health insurance, unemployment insurance and other benefits under the provisions of the Company

### Contact
Apply directly to email: Tuyendung@itbiz.vn 
Number Phone: 0986723730

**Comment by huydx** [comment]
Go to itbiz.vn, and found that the site looks like a ... fake site.

![image](https://user-images.githubusercontent.com/535718/35472947-fd38e7a2-03bb-11e8-943c-92747de0d6da.png)

Sorry but we DON'T accept this kind of shitty job post.
