### ISSUE TITLE
Scuti - Senior PHP Developer - Hanoi - FT

### ISSUE THREAD

**Issue by JaneDang** [awesome-jobs/vietnam#849]
## Location

* Hanoi, Vietnam

## Salary Expectation

* 800$-1500$/month

## Requirements
* Senior PHP dev
* 2+ years of working experience in developing web applications using PHP, JavaScript, AngularJS, HTML, CSS, MySQL
* Experience with Laravel is a plus
* Experience with Magento 1 + 2 or Woocommerce is a plus
* Chance to become the stable developer for the Sparklebox company
* Good at working individually
* Japanese language skills are a big plus

## Responsibilities
* Programming web applications using PHP, AngularJS, NodeJS;
* Designing and developing APIs for Mobile and Web;
* Optimizing the applications to improve performance and to enhance the scalability of the product;
* Participating in the process of designing and reviewing source code for the team;

## Why it would be awesome to work with us
* You have a chance to contribute to the society of not only Vietnam but also SEA
* You can enjoy free working style
* 13th &14th of salary bonus
* Increase your salary 2 times per year
* Team building and company trip
* Training course, Moonshot award
* You can be a core member of startup company
* You can get a chance of quick promotion compared with big companies
* You have a chance to make awesome business by yourself 
* Working in international environment with people from around the world 

## Contact
Ms Đặng Mùi - Recruiter
Tel: 098 1234 144
Email: jane89@scuti.asia
Skype: sakyra.janny
Company: Scuti Co .,Ltd
Ad: Cau Giay, Ha Noi, Viet Nam

**Comment by JaneDang** [comment]
@huydx: Cho em hỏi tại sao lại đóng bài post vậy ạ?

**Comment by huydx** [comment]
@JaneDang Bạn tham khảo tại https://github.com/awesome-jobs/vietnam#what-is-the-format-of-the-job-post

**Comment by JaneDang** [comment]
@huydx : em update lại rồi anh xem được chưa ạ? Nếu ổn thì mở lại giúp em :D

**Comment by huydx** [comment]
@JaneDang 
Bạn đọc kĩ lại đoạn dưới này nhé:

```
Every job post MUST strictly be written in English. Furthermore, it must comply the following rules:

Title Format
[Company Name] - [Job Title] - [Location] - [Job Type]
```

**Comment by JaneDang** [comment]
@huydx : Anh kiểm tra và mở lại giúp em nhé
