### ISSUE TITLE
Scuti - Senior PHP/Laravel - Hanoi - FT

### ISSUE THREAD

**Issue by JaneDang** [awesome-jobs/vietnam#853]
## Location

* Hanoi, Vietnam

## Salary Expectation

* $1500/month or range

## Requirements
* Experience & skill of PHP, Laravel framework
* Experience & skill of React/React Native (plus requirement)
* Experience & skill of RDBMS such as MySQL
* Experience of PHPUnit
* Experience of source code review
* Experience to build & maintain mid-size of Linux servers using Chef
* Experience to develop or operate non-stop system
* Experience & skill of Docker
* Experience to develop services for consumers
* Experience of methods to assure quality such as TDD or pair programming
* Knowledge about performance tuning
* Communication skill in English and experience of Scrum process

## Responsibilities
* Programming of products of our own and our business partners 
* Build network and servers required these products above 
* Source code review 
* Ensure software quality
* Educate the other members
* In charge of Scrum master

### Why it would be awesome to work with us
* You have a chance to contribute to the society of not only Vietnam but also SEA
* You can enjoy free working style
* 13th &14th of salary bonus
* Increase your salary 2 times per year
* Team building and company trip
* Training course, Moonshot Award
* You can be a core member of startup company
* You can get a chance of quick promotion compared with big companies
* You have a chance to make awesome business by yourself 
* Working in international environment with people from around the world

## Contact 
Ms. Mùi_Recruiter
Phone number: 098 1234 144
Email: jane89@scuti.asia
Skype: sakyra.janny
Website: http://www.scuti.asia/

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
