### ISSUE TITLE
AMI Dental Group - Senior PHP - Seoul, Korea

### ISSUE THREAD

**Issue by mskcodes** [awesome-jobs/vietnam#856]
## Location

* Seoul, Korea
* Remote in Vietnam

## Salary Expectation

* $1000+/month

## Requirements

* PHP
* Codeigniter / CakePHP / Laravel Framework
* MySQL / PostgreSQL
* 3+ years Software Engineering experience

## Skills

- Experience & skill of PHP MVC framework
- Experience & skill of RDBMS such as MySQL
- Experience of PHPUnit
- Experience of source code review
- Experience to build & maintain mid-size of Linux servers using Chef
- Experience to develop or operate non-stop system
- Experience to develop services for consumers
- Experience of methods to assure quality such as TDD or pair programming
- Knowledge about performance tuning
- Communication skill in English and experience of Scrum process

### Must Have

You must pass a web development experience in PHP and a simple remote development test, receive a visa in Korea, stay at least 3 months, You can continue working in Korea if you want to. We offer all round-trip tickets and accommodation.

### Why it would be awesome to work with us

We are a healthcare start-up company located in Seoul, Korea. I am looking for a manager to make a development team in Vietnam. We are looking for experienced people who can communicate in English and have years of experience and teaming and management of one of the PHP / Codeigniter / CakePHP / Laravel frameworks.

### Contact
Homepage: http://amidh.net
contact: brian@amidh.net

**Comment by T-Pham** [comment]
May I know the reason that the position requires candidate to be a female?

**Comment by mskcodes** [comment]
@T-Pham our company's house can be allow only female.

**Comment by nathanphan** [comment]
are there other purposes for recruit only young female?

**Comment by qcam** [comment]
@mskcodes We will have to close this job post because of the gender discriminating and scamming suspicion. The explanation of "female-only" company house just does not cut it.

**Comment by mskcodes** [comment]
Please reopen. I did delete that problem section.

**Comment by qcam** [comment]
@mskcodes could you please elaborate how you would tackle relocation? Would you sponsor visa and such? Since the position  would be based in Seoul?

**Comment by mskcodes** [comment]
We can support visa sponsor also We have plan establish office at vietnam.
