### ISSUE TITLE
Pangara Vietnam is looking for a Vietnamese Spree Commerce Developer

### ISSUE THREAD

**Issue by AnnaPhamm** [awesome-jobs/vietnam#866]
## Location

* Saigon, Vietnam
* Remote 

## Salary Expectation

* $17/h

## Requirements
* Build a similar took as Zazzle
* Add all styling colors/fonts/css throughout app
* Optimize for all devices
* Create mega menu for shop and discover
* Update Footer for new UI
* Allow for multiple currency settings
* Allow for language translator - built into spree, need to pass through i18n with custom language mappings will only work with non user inputted data, the maker will have to supply the translated data
* Add tags to products for safe content and allow for filters on product side
* Report this artwork: Inappropriate Content or Copyright Infringement alerts an admin of content
* Add sharer.js to product page
* Cart Add Cross-selling functionality in Cart.
* Checkout Remove Header & Footer, only Logo will be present at same position.
* Add content to who we are, careers, contact, faq, user agreement, privacy policy, DCMA, ads - given content exists - adding and styling
* Add track order functionality - need to know which shipping providers we’d be using, if Fedex and UPS
* Add help page - would recommend a Helpdesk software such as zen desk and link out to it
* Styling signup for the artist, maker, and admin dashboards
* Customize editor for the artist - This is the largest bit of the work will come in. Adding the t-shirt placement is only a small part of it. There is a large amount of work to change how the functionality exists.
* Add transactional email support (Postmark app).
* Add analytics.
* eCommerce Marketing Tool
* Checkout UI & Errors/Bugs needs to be fixed
* Other products from this collection not functioning 
* Cart UI & Errors/Bugs needs to be fixed
* Product UI & Errors/Bugs needs to be fixed
* Front Page UI

## Skills

* Must Have: Ruby, Ruby on Rails, Spree Commerce, React JS, Node JS, Fabric.js Imagemagick (Fred's Script) http://www.fmwconcepts.com/imagemagick/tshirtwarper/index.php and http://www.fmwconcepts.com/imagemagick/tshirt/index.php SVG.JS Warp.JS Caman.JS

* Vietnamese Developer 

### Contact
Skype: giaanup
Email: an.pham@pangara.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
