### ISSUE TITLE
IRD VN - Mobile developer - Saigon - FT

### ISSUE THREAD

**Issue by xgdygcdks** [awesome-jobs/vietnam#868]
## Location

* Saigon, Vietnam

## Salary Expectation

* $1,000 - 1,500 or more (after negotiation, shares can be given) /month

## Requirements
* C/C++/Java/Kotlin/Whatever you may handle well
* Good communication skills with english
* Self motivated, mind-set to work under the pressure, who will be able to work with full authority.
* 5+ years Software Engineering experience

### Must Have

* Be able to do work without direction
* Be able to create the value from zero-base

### Ideally

* Experience with developing Application and managing employees

### Responsibilities

Direct, manage and motivate subordinates.
Be ambitious and keep huge responsibilties. 

### You’ll be responsible for

* Develop the android app., be a head of develop team.

### You can bring

* communication skill, English skill
* mind-set to do a job with self-direction.

### Why it would be awesome to work with us

Our mother company is a Korean trading company which decided to start a new IT business with Passion.
For it, I am appointed as a chief manager without any knowledge for programming.
I can plan strategy, get investment, give you ideas, make/do presentation but can't do programming.
I do not need a employee but a team member as a co-founder.

### Interesting engineering projects

Developing Android application as people's lifestyle,analyzing preference and/or hobbies.

### Contact
Homepage: N/A
Jason An: yonghoonan@gmail.com

**Comment by huydx** [comment]
please conform to our format

**Comment by xgdygcdks** [comment]
sorry, i couldn't find your format. can you tell me where it is?

**Comment by xgdygcdks** [comment]
I edited the post as like other posts. Please reopen this post if it's okay

**Comment by huydx** [comment]
lgtm
