### ISSUE TITLE
Pixta Vietnam - Developer/Senior Developer - Hanoi - FT

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#875]
## Company Information

* The 1st top of Japan's marketplace site of stock photos, illustrations, vectors and footage
* Provides E-commerce platform for digital contents, Huge data volumes with cloud computing management, Service for creative industry
* Office in Japan, Korea, Taiwan, Singapore and Vietnam
* Website: https://pixta.co.jp/en 

## Who are suitable?

* Be keen on products and passionate on researching new technologies 
* Want to learn more about machine learning, search engine, customer's behavior..
* Want to work in multi culture environment and use English/Japanese/Korean every working day
* Have experience about Java/Ruby on Rails/ Python/Linux...

##  Vacancies:
 
* Link for Developer: http://bit.ly/2BnfuW8
* Link for Front-end Developer: http://bit.ly/2E3RY2T

## Benefits:

* Salary: from 500$ - 2000$ (open for discussion for SENIOR/TEAM LEADER level)
* Chance to be trained oversea (Japan, Korea, Taiwan…)
* Working environment: Friendly, young and professional working environment which encourages innovation, transparency and idea sharing
* Good End of Year bonus, Company trips...

## Contact point: 

Please send CV to van.phamthi@pixta.co.jp or contact mobile: 0165.595.9339 (Ms. Van) for further discussion!

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
