### ISSUE TITLE
ZinZa Technology-Golang/Blockchain Developer--Parttime/Fulltime-HN

### ISSUE THREAD

**Issue by thaontp39** [awesome-jobs/vietnam#883]
## Location

* 3rd Floor, Hoang Ngoc Tower, Plot C2C, Lane 92, Tran Thai Tong Street, Cau Giay District, Ha Noi, Vietnam
* parttime/fulltime

## Salary Expectation

* 1200$/month 

## Requirements
- Có ít nhất 02 năm đến 04 năm kinh nghiệm làm việc.
- Hiểu biết sâu về Go Lang / C/C++ , OOP. 
- Có kinh nghiệm làm việc với hệ thống có sử dụng một số công nghệ như: message queue (rabbitMQ, ActiveMQ,ZeroMQ, Kafka,..) , memory cache (redis, hazelcast…) 
- Có kiến thức tốt về Http, WebService , Socket ( optional )
- Có kiến thức về SQL, NoSQL
- Thành thạo: GIT, Linux
- Có kinh nghiệm làm việc trong các dự án theo mô hình Agile.
- Có khả năng đọc tài liệu bằng tiếng Anh.
- Ưu tiên các bạn có kinh nghiệm làm việc với BlockChain,  có niềm đam mê, khám phá, học hỏi công nghệ mới. Sẵn sàng chuyển đổi công nghệ, ngôn ngữ mới.
- Nhiệt tình và cẩn thận trong công việc.

### Must Have

- Có kinh nghiệm làm Technical Leader or Team Leader trong dự án
- Có khả năng dựng server, môi trường phát triển dự án, thiết kế hệ thống

### Why it would be awesome to work with us
● Có cơ hội được onsite tại thị trường Mỹ,Nhật Bản.
● Thời gian làm việc: từ thứ 2 đến thứ 6 từ 8h30 - 17h30 (Nghỉ thứ 7,CN)
● Môi trường làm việc chuyên nghiệp, cởi mở, thân thiện
● Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo chế độ nhà nước ban hành.
● Xét tăng lương theo năng lực và kết quả công việc: 1-2 lần/năm.
● Điều chỉnh lương theo trượt giá thị trường: 1 lần/năm.
● Lương tháng 13
● Được đi du lịch hàng năm
● Cơ hội thăng tiến cao trong môi trường tăng trưởng liên tục
● Du lịch hàng năm.

### Contact
Fanpage: https://www.facebook.com/ZINZATech/
Email: thao.ntp@zinza.com.vn
Skype: thaonguyenn993
phone: 0977507453

**Comment by huydx** [comment]
@thaontp39 revise our format , and job post should be in English
