### ISSUE TITLE
PIXTA Vietnam - Web Developer/Senior Developer/Team Leader - Hanoi - FT

### ISSUE THREAD

**Issue by VanPham289** [awesome-jobs/vietnam#886]
## Location
* Hanoi, Vietnam

## Salary Expectation 
* 700$ - 1500$

## Requirements
* Solid knowledge of Web development
* Master at least one of the OOP programming languages (Ruby, Java, Python, C++)
* Familiarity with software/web development based on Unix/Linux
* Experience in modern front-end framework including AngularJS, React, Vue, Emberjs
* Tools: GitHub, Trello, CircleCl, ...
* Programming language: Python, Ruby (Ruby training programme is available)
* Frameworks/ Libraries: Tensorflow, Ruby on Rails, ...
* Database: MySql, DynamoDB, TreasureData
* Infrastructure: Amazon Web Services (AWS): Opsworks, EC2, S3, DynamoDB, Cloudsearch, Elastic
Search, ...
* Be able to communicate in English
* Capability to solve hand-on and complex problems

### Must have
* Solid knowledge of web development
* Be able to use English at least communication level
* Be keen on products and passionate on researching new technologies 
* Want to learn more about machine learning, search engine, customer's behavior..

### Ideally 
* Experience with Ruby on Rails

### Responsibilities
* Design and develop next generation e-commerce system which are fault-tolerant for stock market.

### Why it would be awesome to work with us
* The 1st top of Japan's marketplace site of stock photos, illustrations, vectors and footage
* Provides E-commerce platform for digital contents, Huge data volumes with cloud computing management, Service for creative industry
* Multi culture environment and use English/Japanese/Korean every working day
* Chance to be trained oversea (Japan, Korea, Taiwan…)
* Working environment: Friendly, young and professional working environment which encourages innovation, transparency and idea sharing
* Good End of Year bonus, Company trips...

### Interesting Engineering Projects
* Discuss during Interview

### Contact 
Please send CV to van.phamthi@pixta.co.jp or contact mobile: 0165.595.9339 (Ms. Van) for further discussion!
Website: https://pixta.co.jp/en

**Comment by duytd** [comment]
:+1:

**Comment by qcam** [comment]
:robot: Closing this job post because it has been expired :alarm_clock:.
