### ISSUE TITLE
30 FULLSTACK DEVELOPERS (PHP, JAVA, MAGENTO) ENTRY CANADA AFTER 1 YEAR

### ISSUE THREAD

**Issue by tudoa89** [awesome-jobs/vietnam#887]
## Location
* Saigon, Vietnam

## Salary Expectation
* 2,000 - 2,500 USD

## Requirements
* Creating enterprise standalone applications (3+ years)
* Architecting front-end and back-end logic
* Feel comfortable developing for NodeJS (3+ years)
* Using modern, complex concepts in day-to-day work (async, es6, immutable, etc)
* Using Javascript frameworks in production (at least one of BackboneJS, ReactJS, MarionetteJS or Redux)
* Proficiency in object oriented programming and at least 3+ years of solid experience with all of the  following languages: PHP, HTML, CSS, JavaScript, Ajax, XML, MySQL
* Ideal candidates may also possess strong skills In: System Integration, API Development, Strong * understanding of e-Commerce best practices ,Data Mapping ,GIT and Version Control, LAMP StacK Expertise, Plug-in Development 

### Must Have
* Able to work on a tight-knit, collaborative and diverse team—you have an open mind and love learning from others
* Curious and entrepreneurial
* Very comfortable giving and receiving feedback
* Results-oriented and process-driven, with high expectations of yourself and others
* An excellent communicator
* Comfortable giving opinions—you ask questions and aren’t afraid to suggest a better solution

### Responsibilities
* Working with foreigner client (Canada)

### You can bring
* communication skill, English skill
* mind-set to do a job with self-direction.

### Why it would be awesome to work with us
* Collaborate with overseas technical teams
* Travel/work/relocate overseas.
* Join venture-backed start-ups
### Contact
Skype: tudoa89
Mail: thucdoanki@gmail.com

**Comment by huydx** [comment]
revise our format, and we do not accept 3rd party JD
