### ISSUE TITLE
JobReady (since 1997) - Looking for Ruby Developer (Salary upto $3000)

### ISSUE THREAD

**Issue by rauxalach** [awesome-jobs/vietnam#89]
![rto4](https://cloud.githubusercontent.com/assets/1320349/9030435/cb850b20-39cc-11e5-8509-2bbbcc665372.jpg)
## About Us

 Our site: www.jobready.com.au
 Our Devs: 100+
 Our Corporate Clients: 250+
 Our Users: 22,465
## Location

  Nha Trang, Ho Chi Minh city
  Remote
## Responsibilities

We are re-architecting industry leading software built using Ruby on Rails into a modern micro service based platform. We're looking for best engineering to further fuel this transition.

You will join our team in Vietnam and work closely with Australia team to design, implement and support our web applications.
## Requirements
- Strong background in object-oriented software development
- A can-do attitude
- Teamwork skill
- A problem solver and Google master
## Skills
- Experience writing web applications using Ruby, RoR, JavaScript, .Net, Python
- Experience with MySQL/Postgres
- Be able to communicate and write in English
- Ability to understand and debug large and complex code bases
- Be able to write unit tests and maintainable code
### Responsibilities
- Maintain current web applications using by our 200+ clients
- Building features to a high quality bar using Ruby on Rails
- Actively working on projects from our SOA roadmap
- Be swapped between projects to maintain and develop new features
### Contact

Huy Le: huyl@jobready.com.au (0908.108.625)

**Comment by joneslee85** [comment]
:+1:

**Comment by donnguyen** [comment]
:+1:

**Comment by nhattan** [comment]
:+1:

**Comment by huynhquancam** [comment]
:+1:

**Comment by tranthanhcntt** [comment]
(y)
