### ISSUE TITLE
Freelensia - full-stack Rails developer - FT or PT - Saigon

### ISSUE THREAD

**Issue by Freelensia** [awesome-jobs/vietnam#890]
![image](https://user-images.githubusercontent.com/27481639/37415135-48c94f6e-27dd-11e8-9855-b5fb459c7b29.png)

## About us
* [Freelensia](https://www.freelensia.com) is the world's first online interpreter reservation platform. Based in Vietnam, the website launched in March 2017 and now have more than 1000 members from Vietnam, China and Japan. On Freelensia, interpreters post listings advertising their language skills, while companies browse and make a reservation online. We aspire to become the AirBNB for interpreters and are looking for a tech lead / CTO to realize our vision.

## Location
* Saigon, Vietnam (FT), or
* Remote (PT)

## Compensation
* $1000-1800/month with up to 10% equity for those interested
* $10-$15/hour for PT

## Technical Requirements
* Full-stack mid to senior developer with at least 3 years of experience at top-tier startups or outsourcing companies
* Experience with: 
    * Rails 5.1.1 
    * React + jQuery
    * MySQL 5.7
    * Node.js 7.8
    * Testing frameworks (RSpec, Cucumber)
* Familiarity with AWS, S3, ability to set up and perform deployments preferred
* Familiarity of Clojure a big bonus

## Other requirements
* Can translate a business requirement into multiple technical solutions and explain the pros and cons of each
* Familiar with task management and chat program (Asana, Trello, Slack, etc.)
* Can break a task into sub-tasks, estimate required hours and completion date
* Disciplined and hard-working, do what it takes to complete a task on-time
* English is not required (you can practice your English as most of us are fluent, but not necessary)
* For FT: candidates living near D7 preferred

### Responsibilities
* Build and refine new features for our platform such as our interactive landing page, user profiles, search engine, reservation calendar, blog, payment, etc.
* Fix bugs, write tests
* Help recruit and train junior / freelancers

### Why it would be awesome to work with us
* The very first FT tech position in a global-aiming startup
* Office in D7 with all of the greenies and fresh air
* A laid-back and simple culture: be bold, work hard, earn what you deserve and enjoy the show!
* You are encouraged to contribute your ideas to our vision, technical road map and implementation processes

### Contact
Homepage: https://www.freelensia.com
Contact: support@freelensia.com
(Please title your subject as: **Rails awesome-jobs posting**)

**Comment by huydx** [comment]
revise our format please

**Comment by Freelensia** [comment]
Hi @huydx  could you tell me what is wrong with this posting?
- The title is the right format
- The posting is in markdown language

Thanks!
