### ISSUE TITLE
EVOLABLE ASIA - 02 C#/.Net TeamLeader - Đà Nẵng 

### ISSUE THREAD

**Issue by NguyenVuDieuLien** [awesome-jobs/vietnam#893]
Location
EVOLABLE ASIA -  Đà Nẵng
Salary Expectation
Up to $1000
Requirements
* Bachelor's Degree in any relevant major (Software Engineering, Computer Science, ect.);
* At least 4 years experience in using .NET; MVC, Web API;
* Have experience or research about Signal R;
* Have knowlegde about Elastic Search; Rabbit MQ;
* Experienced working with Scrum/Agile Process
* An understanding and experience in working for large scale system;
* Ability to work both independently and as a team member;

Skills
Must Have
* Algorithms and data structures
* Full stack development for web and mobile applications
* RESTful services – creating your own APIs, or integrating with 3rd party services
* Experience with Angular, Ember, React, or Backbone

Language training: Japanese, English (Company sponsor)
Salary review: 2 times/ year and incentive bonus at the end of the year
Salary package: competitive and negotiable
Lunch & parking allowance
Premium Health Insurance
Applicable for all normal benefits: insurances, 13th salary, annual outing trip, team building activities, kick off 01 time/quarter
Sport and club activities: Football, swimming, badminton, guitar, yoga etc. (Company sponsor)
Interesting engineering projects
Contact
Homepage: https://jobs.evolable.asia
Mail: dieulienk34b@gmail.com

**Comment by huydx** [comment]
Wrong format
