### ISSUE TITLE
Fintech Corp - Software Engineer & Full-stack Web Developer - Fulltime - Hanoi & HCMC

### ISSUE THREAD

**Issue by nsthaole** [awesome-jobs/vietnam#904]
**## Introduction:**
Our client is Global investment management complex (Hanoi Office and HCM Office - Vietnam). You will be working in a highly professional environment, where you will work in large scale project to develop your own product, build innovative features and optimize the operation of system.

The ideal candidates will enjoy tackling complex technical challenges, have a passion for architecting, designing extremely large-scale projects, and be self-motivated to push themselves in a team oriented culture.

**## Location:** Hanoi & HCMC

**## Benefit:**
* Salary: 2000-3000$
* Collaborating with a highly educated and experienced team
* Much international exposure including working abroad and global travel opportunities.

**## Requirements:**
* 3+ years of experience in end-to-end software development;
* Solid experience architecting large-scale web applications or distributed data system;
* Expert in programming language Java and Python or other web programming languages (PHP, Ruby on Rails,…);
* Strong knowledge in data structure and algorithms;
* Familiar with open source software package, Unix/Linux;
* Good understanding in one or more following technologies: Distributed system, Micro services, scale application, data mining, big data.

**## Apply:** Send CV or ask for further information via email **Thao.Le@navigossearch.com**

**Comment by huydx** [comment]
Don't approve 3rd party job
