### ISSUE TITLE
Dwarves Foundation - Senior PHP developer - Saigon/Remote - Full-time

### ISSUE THREAD

**Issue by anduong** [awesome-jobs/vietnam#905]
Found in 2014, we are a team of geeks, hustles and startup veterans. We live around the world but most of us based in Saigon, Vietnam. We are (forever) young and always eager to learn. We have passion and experience in making cool products, esp. cloud and mobile apps. We want to help entrepreneurs solve real problems using our approachs and solutions.

We call ourselves dwarves, the small and misshapen creatures in Norse Mythology. We are wisdom, natural good at smithing, mining, and crafting. We have Miners, Crafters, Wizards and Soliders.

We position ourselves as a Startups Factory. We build innovative products, give a hand to build companies and also give seed investment. Join our network if you are startup veterans, can wear multiple hats at the time and want to build multiple world class products.

We are driven by values, not just the money. We aim to the perfection as our standard. You can find more information about us here: https://github.com/dwarvesf/WeAreHiring

## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $800-$1800

## Requirements
* Have the same DNA with us
* We do agile
* Real git user
* Mac or Linux
* OOP Design: from STUPID to SOLID
* Convention and architecture
* Want to make world class product. All the outcome must be world class.
* Watching trends and best practices in development.
* Reading blogs and compiling ideas how to improve your skills.
* Know how to handle the entire software development life cycle, end to end.
* Contributions make you get paid, not the experiences.

## Skills
* At least 2 years of experience on PHP. Be familiar with one or many of these frameworks Laravel, Symfony, CakePHP, Zend.
* Front-end (HTML/CSS/JS) should be your hand-on tools going along with your PHP skill. We are not speaking the old JQuery but ReactJS instead.
* Responsive design is a not a nice-to-have skill. It’s required.
* You can be sick of anything else but not legacy codebase.

### Why it would be awesome to work with us
* Bonus by projects
* Remote working style and flexible working hour
* Value driven - You will always grow by learning and playing with new and cool technologies
* Yearly team retreat
* Healthcare insurance

### Contact
An: an[AT]dwarvesv[dot]com

**Comment by huydx** [comment]
@anduong please review our format (lack of some fields)

**Comment by anduong** [comment]
@huydx I have updated the JD. Please let me know if it still misses the other fields.

**Comment by anduong** [comment]
Thanks @huydx
