### ISSUE TITLE
Dwarves Foundation - Senior iOS Developer - Saigon/Remote - FT

### ISSUE THREAD

**Issue by anduong** [awesome-jobs/vietnam#906]
Found in 2014, we are a team of geeks, hustles and startup veterans. We live around the world but most of us based in Saigon, Vietnam. We are (forever) young and always eager to learn. We have passion and experience in making cool products, esp. cloud and mobile apps. We want to help entrepreneurs solve real problems using our approachs and solutions.

We call ourselves dwarves, the small and misshapen creatures in Norse Mythology. We are wisdom, natural good at smithing, mining, and crafting. We have Miners, Crafters, Wizards and Soliders.

We position ourselves as a Startups Factory. We build innovative products, give a hand to build companies and also give seed investment. Join our network if you are startup veterans, can wear multiple hats at the time and want to build multiple world class products.

We are driven by values, not just the money. We aim to the perfection as our standard. You can find more information about us here: https://github.com/dwarvesf/WeAreHiring

## Location

* Saigon, Vietnam
* Remote

## Salary Expectation

* $1000-$2000

## Requirements
* Have the same DNA with us
* We do agile
* Real git user
* Mac or Linux
* OOP Design: from STUPID to SOLID
* Convention and architecture
* Want to make world class product. All the outcome must be world class.
* Watching trends and best practices in development.
* Reading blogs and compiling ideas how to improve your skills.
* Know how to handle the entire software development life cycle, end to end.
* Contributions make you get paid, not the experiences.

## Skills
* Managing third party libraries with CocoaPods
* Using storyboards or nibs with auto layout, but also creating views in code
* Using core animations and core graphics
* Using core data and web services with JSON
* Handling multiple languages (i18n)
* Caching & pre-loading
* Push notifications (APNS, Pubnub)
* Testing skills: Write tests for your code
* Can implement world class UI
* Rx Programming
* Show us how good you are on other stuffs

### Why it would be awesome to work with us
* Bonus by projects
* Remote working style and flexible working hour
* Value driven - You will always grow by learning and playing with new and cool technologies
* Yearly team retreat
* Healthcare insurance

### Contact
team[AT]dwarvesv[dot]com
CC: an[AT]dwarvesv[dot]com

**Comment by qcam** [comment]
@anduong please remove "up to $2000" in the job title.

**Comment by anduong** [comment]
@qcam removed.

**Comment by dlpigpen** [comment]
@qcam are you still looking for an iOS developer remote. I would like to apply for this position.

**Comment by tieubao** [comment]
@dlpigpen Remote is ok 👌

**Comment by dlpigpen** [comment]
@tieubao Awesome. Could you please give me your detail to contact?
 Thank you!

**Comment by anduong** [comment]
@dlpigpen As mentioned above, please drop us an email to one of these email addresses.
team[AT]dwarvesv[dot]com
CC: an[AT]dwarvesv[dot]com
