### ISSUE TITLE
PHP Developer (Junior)_HoChiMinh City_VietNam

### ISSUE THREAD

**Issue by quynhmiu** [awesome-jobs/vietnam#909]
**THE JOB**
fram^ is  actively looking for Full-stack PHP Developers to improve the product and to develop new features for Swedish leading e-commerce platforms. Most important is that your coding should be at the highest standard, easily maintainable and easy to read. You are able to work independently, but team support is always available to back you up.

**YOUR SKILLS AND EXPERIENCE**
At least 1-2 years of experience working in IT/Software Development industry
Experienced in PHP, OOP (Magento is a plus)
Experienced in HTML/CSS/JavaScript
Experienced working with Linux server, deployment and configuration (Apache/Nginx/Varnish/APC/Memcached/Redis) and LEMP
Familiar with writing unit test in PHPUnit
Experienced in optimizing the code for high traffic websites
Able to write well-structured, maintainable code 
Excellent in both written and verbal English communication
Can-do-attitude and put the goals of the team before your own prestige
You are able and hungry to take on a lot of responsibility
 
**NICE TO HAVE:**
Previous work experience with Amazon Web Services
Experience with GIT
Experienced with various cache systems of relational databases

**MORE ON FRAM^ – WHAT IS IT LIKE TO WORK IN FRAM?**  
We are passionate individuals that are driven to succeed. Our work culture is characterized by strong team spirit, high degrees of openness and innovation, and strong collaboration across fields. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals who have a desire to build something new and actively support our young company in its growth to greatness.

**YOU WILL LOVE WORKING HERE!**
5-days working week (Monday-Friday) with flexible working hours to some extent
Professional working environment with Scandinavian culture and open spaced office on Nguyen Cong Tru in central Ho Chi Minh City
Beer time on Friday combing with technical sharing from the teams
Company meeting every quarter with transparent sharing from BOD on company plan and growth
Company trip once per year and many exciting team building and sports activities throughout the year
More annual leaves than Vietnam’s Labor Law (plus Swedish national day and Christmas Eve) and increase by working years
Vietnam’s Social Insurance contribution based on full salary plus a Premium health care package and Annual health checkup
Opportunity to improve English skills within a multinational team and business model because English is our official language
Opportunity to gain hands-on experience in cutting-edge technologies
Opportunity to develop your soft skills with technical sharing presentation
Opportunity to become one of the key members of fram^ as we build this fast growing company together!
Guaranteed long-term employment and orient your career development.

Do you think you’ve got what it takes? Apply now!

For more vacancies, visit https://wearefram.com/careers/

APPLY BEFORE APRIL 13, 2018
To apply, please send your CV, cover letter to HR department at the following address: careers@wearefram.com

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
