### ISSUE TITLE
BlueFin - Java Developers - Saigon - FT

### ISSUE THREAD

**Issue by tinnguyenz** [awesome-jobs/vietnam#910]
We are BLUEFIN - a Fintech startup based in Saigon, formed to focus on building financial products for European customers. As a fast-growing team, we are now looking for several positions full-stack Java developers. 

* D4, Saigon, Vietnam
* Fulltime

## Salary Expectation

* $800-$1500/month

## Skills & Requirements
* +2 years of experience
* Java (Core Java, Spring, Building REST API, Unit Testing)
* Nice to have AI, big data, chatbot system
* Experiences in front-end technologies: HTML/CSS, Javascript (React/Angular/jQuery)
* Being able to write efficient SQL, analyze data are huge plus
* Fairly familiar with AWS
* Decently communicate in English
* No hesitation to give your own feedback either building ideas on products
* We love parties. So get yourself prepared to explode

### Benefits
* 17 days of annual leaves
* Flexible in/out time
* You can work remotely from home when needed
* Laptop provided (Windows or Mac)
* Fully paid insurance
* 100% probation salary

### Why it would be awesome to work with us
We work hard and play hard

### Interesting engineering projects
We are building solutions to solve financial headaches across Europe. With taking advantage of AI and big-data, there will be a lot of interesting challenges to come.

### Contact
Send your CV to `tinnguyen911` at `gmail.com` if you're interested.
We will contact you as soon as you're shortlisted.

**Comment by qcam** [comment]
@tinnguyenz thanks for posting. Could you please include some information about your company in the job description?
