### ISSUE TITLE
Dinosys - Front-end Developer (React) (All level) - Saigon - FT

### ISSUE THREAD

**Issue by tangoanh** [awesome-jobs/vietnam#911]
## Location

* 204 Pasteur, Ward 6, Distrist 3

## Salary Expectation

* Negotiable

## Requirements
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies
* Strong JavaScript and ReactJS skills. Experience with React or TypeScript is a plus
* Experience building responsive web apps
* Strong analytical and problem solving abilities
* Strong communication and client facing skills

## Skills
* Strong JavaScript and ReactJS skills

### Must Have
* Minimum 1-3 year commercial experience with HTML5, JavaScript, CSS or other web technologies

### Ideally
* Experience building responsive web apps

### Responsibilities
* Front-end Mobile Web development (HTML5, CSS3, ReactJS, integration with RESTful Web API)
* Maintain existing software
* Constantly learn and keep abreast of emerging technologies
* Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
* Critique software designs and architectures
* Peer review colleagues code and identify areas for improvement
* Provide development task effort estimates
* Conduct client requirements gathering and analysis
* Review test plans
* Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us
* Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:

* Working in dynamic, young, friendly, flexible invironment
* Laptop is provided
* 12+ days annual leaves, working Monday - Friday, flexible working time
* Attractive salary based on skills and experiences
* Salary review: Once a year, base on individual performance review
* Performance bonus: Twice a year (every 6 months), base on individual performance, profit and company policy 
* Gift occasions: 8/3; 1/6 (for children); Mid-autumn festival; 20/10; Lunar New Year, Wedding 
* Free fruits/ snacks on happy hours time
* Celebration: birthday
* Party time: Team building (frequent) and Xmas
* Healthcare, Unemployment insurance and Sick leave: based on current relevant Laws
* Great opportunity for career development 
* Training new technology frequently, and become a fullstack developer

### Interesting engineering projects
* We use international standard in building system such as agile, test driven development, continuous integration and continuous deployment.
* Various projects with so many new technologies applied

### Contact
Email: oanh.tang@dinovative.com
Phone: 0909 617 173
Skype: tangoanh
FB: https://www.facebook.com/oanhtang195

**Comment by qcam** [comment]
@tangoanh You seem to have the same job opening, could you please close it first before creating a new one? https://github.com/awesome-jobs/vietnam/issues/810

**Comment by tangoanh** [comment]
@qcam: Okay. I don't know how to closed old post. Please help me how to closed it and reopen #911
Thank you.

**Comment by qcam** [comment]
You can click the "Close" button on #811 and the "Reopen" one on #911. Friendly remind that please double check duplicated posts because submitting new ones.
