### ISSUE TITLE
RoR dev for agency - Spark Start [Remote] [$30USD/hr at 15 hours per week]

### ISSUE THREAD

**Issue by KevinColemanInc** [awesome-jobs/vietnam#912]
## Location
* Saigon, Vietnam
* Remote

## Salary Expectation

* $ 30 / hour USD at 15 hours per week

## Requirements
* Strong English skills
* Ruby on Rails
* 25 hours per week
* PostgreSQL
* 3+ years Software Engineering experience

### Must Have

* RoR 5.0+
* API design
* ES6

### Ideally

* RegEx experience
* GraphQL
* DevOps (can setup a server)

### Responsibilities

Working as a contractor for US client base on various projects for small startups.

### You can bring

* English

### Why it would be awesome to work with us

We are a "get your work done" type of environment.  As long as you are delivering, we do not care when or how you get your work done.

### Contact
Homepage:  [SparkStart.io](https://sparkstart.io)
Email: kevin.coleman@sparkstart.io
Slack: @ kevin at vietnamrb.slack.com

**Comment by huydx** [comment]
please review your JD template

**Comment by KevinColemanInc** [comment]
JD template?

**Comment by Gnouc** [comment]
@KevinColemanInc Is RoR 5.0+ a must? I have worked with RoR 4.x before, but switch to other like Django. Switching back to RoR is not hard for me.
