### ISSUE TITLE
Front-end Developer (React)

### ISSUE THREAD

**Issue by lemanh2006** [awesome-jobs/vietnam#915]
## Location

* 12 Lam sơn, P.6, Q.Bình Thạnh, HCM

## Salary Expectation

* Negotiable

## Requirements

* Minimum 2 year commercial experience with HTML5, JavaScript, CSS or other web technologies
* Strong JavaScript and ReactJS skills
* Experience building responsive web apps
* Strong analytical and problem solving abilities

### Must Have

* Minimum 2 year commercial experience with HTML5, JavaScript, CSS or other web technologies

### Ideally

* Strong JavaScript and ReactJS skills

### Responsibilities

Front-end Mobile Web development (HTML5, CSS3, ReactJS, integration with RESTful Web API)
Maintain existing software
Constantly learn and keep abreast of emerging technologies
Contribute to the software design processes including whiteboarding sessions, workshops and prototyping
Critique software designs and architectures
Peer review colleagues code and identify areas for improvement
Provide development task effort estimates
Conduct client requirements gathering and analysis
Follow defined development best practice including commenting and documenting code, contribute to development wikis and using source control

### Why it would be awesome to work with us

Come and work with us. You will have opportunity to learn new technologies with international standard, build products that are different/innovative and get various benefits:

Working in dynamic, young, friendly, flexible invironment

Laptop is provided - Macbook pro

12+ days annual leaves, working Monday - Friday, flexible working time

Attractive salary based on skills and experiences

Salary review: Once a year, base on individual performance review

Performance bonus: base on individual performance, profit and company policy

Great opportunity for career development

### Interesting engineering projects

* Various projects with so many new technologies applied

### Contact

email: manh@ezyplanet.com
phone: 0979502104

**Comment by qcam** [comment]
Thanks for posting. Could you please update your job description to follow [our guideline](https://github.com/awesome-jobs/vietnam#job-description-format), all `REQUIRED` sections must be filled.
