### ISSUE TITLE
Scommerce- Business Analyst- Saigon - FT

### ISSUE THREAD

**Issue by Dongdod** [awesome-jobs/vietnam#920]
## Location

* Saigon, Vietnam
70 Lu Gia, Ward 15 District 11.

## Salary Expectation

* Up to 1000 $/Month

## Requirements
* 1+ years BA experience

## Skills
At least 1 years’ experience in software development in any position

Proven ability to document business requirements in an accurate, unambiguous and succinct fashion:

Self-learning.

Problem-solving.

Sharp, motivated co-workers in a fun office environment.

Demonstrated ability to plan and conduct research in close collaboration with people in a variety of roles, including design, engineering, and product management.

* Experience with 

### Responsibilities
Write specification to help developers implement the product.
Give opinion to improve UI/UX.
Support UAT in testing, verifying bugs/issues.
Monitoring product & tracking new features, analyze what feature need to be improved.

### You’ll be responsible for

Contribute to build the largest Vietnamese Logistic System.
Analyze operation process to provide solutions by system.
Setup plan for feature development.

### Contact
Mr. Dong
Email  dongdd@scommerce.asia
Telegram 091 291 0678
Skype Mrdongdo@live.com
Homepage: 
https://www.facebook.com/scommerce.asia/
https://www.linkedin.com/company/scommerce.asia/

**Comment by qcam** [comment]
@Dongdod Could you please revise your post?

* Skills section hasn't been complete.
* Add bullet points to items.
