### ISSUE TITLE
Yojee - Junior Backend Developer - Saigon - FT

### ISSUE THREAD

**Issue by sarah1927** [awesome-jobs/vietnam#940]
## Location

* District 4, Saigon, Vietnam
* Full time 

## Salary Expectation

* SGD 4000 gross 

## Requirements
* Experienced and proficient working with at least two languages, preferably Elixir, Ruby or any functional programming language.

## Skills
* Ruby/Elixir
### Must Have

* Minimum Bachelor Degree in Computer Engineering or its equivalent related experience.
* Minimum 2 years of relevant backend development experience.
* Attention to detail and reliability are what you take pride in.
* You enjoy driving things over getting tasks assigned.
* You are willing to learn new technologies

### Nice to have

* Experience with Elixir/Phoenix is not required
* Experience with Microservice architecture 
* DevOps experience with Heroku, AWS or Azure

Our mission is to bring the hundreds of thousands of logistics companies into the digital era, the same way the web browser enabled consumers and sellers to trade online securely.

We are a young team of software engineers who are enthusiastic about using the right technologies for the right job, while sticking to best practices and keeping the quality high. This approach helped us to create a platform that reliably handles millions of transactions. We have a strong engineering culture and embrace bottom up decision making.

The engineering team in Vietnam is responsible for building a scalable and modular SAAS platform. Our platform allows traditional logistic companies to be able to provide services similar to Giao Hang Nhanh. We are building features to support international shipment and a blockchain to connect our clients into one Yojee Network.

### Contact
Homepage: Yojee.com
Sarah: Sarah@yojee.com

**Comment by bxdoan** [comment]
Hi Sarah,
Is this position available? I want to apply this.
Thank!!!
