### ISSUE TITLE
Getlinks - Engineering Manager - SaiGon - FT

### ISSUE THREAD

**Issue by RecruiterMaiNgo** [awesome-jobs/vietnam#942]
## Location

* Saigon, Vietnam

## Salary Expectation

* $3000 - $4000 (NET)

## Requirements

* Minimally 8 years of work experience on large-scale and high-traffic projects (both Front-end and Back-end) 
* Javascript
* ReactJs
* NodeJS (Prefered)
* Fullstack

## Skills
* Minimally 10 years of work experience on large-scale and high-traffic projects (both Front-end and Back-end)
* Minimally 4 years of hands-on technical leadership or people management
* Experience with hiring and building self-sustaining teams
* Ability to coach and mentor team members in their professional development
* Hands on experience working with Web Front-end:
* Languages/frameworks: Javascript, React, Redux, and es7
* Hands on experience working with Web Back-end:
* Languages/frameworks: NodeJS (most preferred), PHP, Ruby on Rails, Golang, or Python
* Cloud service: AWS (most preferred), Google Cloud, Heroku
* Databases: PostgreSQL, MySQL, MongoDB, CouchDB, Cassandra
* APIs: RESTful

### You’ll be responsible for

* Manage and oversee the engineering team in Vietnam
* Responsible for hiring, mentoring and development of our team of engineers to grow a high performance engineering organization
* Collaborate with product & technology teams to deliver major initiatives that drive our customer growth
* Guide engineering technical strategy and roadmaps
* Commitment to high code quality and delivery requirements

### Why it would be awesome to work with us

* Be part of a World-Class Engineering Team
* Annual Company Retreat
* Attractive Stock Options in fast growing start-up

### Contact
Email: mai.ngo@getlinks.co
Skype: mai.ngo91

**Comment by rebyn** [comment]
@huydx this is a recruitment agency.
