### ISSUE TITLE
VietCV - React/Redux Web Developer - Saigon - FT

### ISSUE THREAD

**Issue by KazkiMatz** [awesome-jobs/vietnam#947]
## Location

* Saigon, Vietnam
* We are located on Nguyen Dinh Chieu, District 3, with easy access from all districts, many foods, coffee shops & convinient store around the office.

## Salary Expectation
* $650 - $2,500/month (depends on one's skills)

## About us
VietCV is a strategic partner of CareerLink = [https://www.careerlink.vn](https://www.careerlink.vn) that aims to provide jobseekers-centric solutions on the Vietnam job market rather than employers-centric.

Currently we're building a CV-improvement product - VietCV = [https://vietcv.io](https://vietcv.io) to improve jobseeker's resume to attract recruiters, to help make successful applications for great jobs and build their own careers. Our main technology stacks are React / Redux / Rails.

The amazing CV-improvement tool is only our very first step to solve jobseekers problem. We plan to develop more products to make the job finding journey a lot smoother. We need more help from the dev community of Saigon to implement cool features together.

### Must Have
* React / Redux
* ES2015
* HTML5 / CSS3
* Github and PR-driven development
* TDD experience
* Self-motivated nature and the ability to work autonomously with minimal supervision

### Ideally
* Experience with CI, Refactoring

### You’ll be responsible for

We are looking for developers who have solid background about web development, care deeply about their quality of work and want to take on new challenges.

* Work on Web product to build cool user-centered features.
* Work on pair programming with other developers to build applications with _**Rails / React / Redux**_.
* Work with Project Manager to convert business insider into technical designs.
* Cooperate with UI/UX Designer to implement designs into production
* Apply proven technologies and best practices to level up your technical skills: _**Redux, ImmutableJS, Rails5, ActionCable, Webpack, FlowType, Rspec, Capybara, Jest, Headless Chrome, Docker**_...
* Learn new languages and frameworks, analyse user needs to improve yourself and stay current in an ever-changing environment
* Contribute to the local Tech Ecosystem by mentoring, writing articles and joining events.

### You can bring

* A good eyes of designer to discuss frequently with designer for the best solution.
* A good ‘user-needs analysis’ skill so you can understand user painful and work together to solve it.

### Why it would be awesome to work with us
* We work with the newest and coolest technologies.
* We invest in developing up all of our members in any area they want to improve.
* We create an open and friendly working environment. Equal say in all product planning from all team members on what to implement and how to get it done.
* Work in pair of developer & designer will help developers build up the product knowledge and implement amazing UI.

### Contact
For applying this position, please use our product VietCV to create your CV then send it via email.
Homepage: https://vietcv.io
kazkimatz: hotro_at_vietcv_dot_io

**Comment by nghiangodinh** [comment]
Hello Mr. KazkiMatz:

Does this job support remotely work? 

Best regards,
Nghia Ngo

**Comment by KazkiMatz** [comment]
Hi @nghiangodinh,
Thank you very much for your interests on our project!
Unfortunately, currently we're looking for developers who can work on-site our Saigon office only.

**Comment by nghiangodinh** [comment]
Thanks Mr @KazkiMatz for your answer! 
 
BR,
Nghia Ngo
