### ISSUE TITLE
GO1-Senior Front-end Developer

### ISSUE THREAD

**Issue by btphuongnhi79** [awesome-jobs/vietnam#950]
## Location
271 Nguyễn Trọng Tuyển Phú Nhuận
Saigon, Vietnam

We are currently seeking out an experienced front-end developer who loves JavaScript coding backed up with solid general programming experience, problem-solving skills, and a strong work ethic.

## Salary Expectation
above $1500/month

## Requirements

Work alongside a team of engineers to implement new features for our SaaS products
Champion and adhere to - test driven development
Research and apply best practice tools and technologies
Work in a highly productive and collaborative team where your ideas will be listened to and actioned
Takes ownership of assigned work
This exciting opportunity would suit a Senior JavaScript Developer who is looking to move upwards and onwards, working closely with senior management on interesting and cool ideas. Get involved with building awesome products!!

## Skills
At least 1 year hands-on experience working on a SaaS software product
Able to use Git and follow git flow workflow
Familiar with CI/CD build and deployment processes
Experience building REST based APIs - from design through to implementation and integration support
Understanding of microservices/Service Oriented Architecture design
Experience in one or more backend languages (PHP, Javascript, Golang) is preferred
Experience with MYSQL DB Design/optimization is preferred
Experience with AWS services (specifically RDS Aurora, EC2, ECS, ElastiCache) is preferred

### Must Have
Experienced with JavaScript, AngularJS or ReactJS..

* Be able to fly
- Rotate to travel to Australia
- Great power comes with great responsibilities!

### Contact
Phuong Bui: phuongnhi.bui@go1.com (01212451188)

**Comment by huydx** [comment]
wrong format
