### ISSUE TITLE
GO1-Software Architect (AWS/SaaS/PHP/JS)

### ISSUE THREAD

**Issue by btphuongnhi79** [awesome-jobs/vietnam#951]
## Location
271 Nguyễn Trọng Tuyển Phú Nhuận
Saigon, Vietnam

We are currently seeking out a Software Architect who experience in building and maintaining product development lifecycle to help us change the learning/training experience around the world!

## Salary Expectation
Negotiation

## Requirements

- Work with Architects & CTO to develope technical architecture - the blueprint for GO1
- Support the product initiative process with technical (inc. infrastructure and hosting) solution design.
- Align customer needs with current and planned technical capabilities
- Ensure there is a clear and efficient path to production for developers at GO1
- Perform technical review of developer solutions - this will include code peer review
- Perform some software development - ensuring credibility with developer by spending 10% of your time in code 

## Skills

At least 5 years experience as technical architect in an open source environtment and have a notable and active contribution to the open source community
At least 4 years experience with cloud-base PaaS technology - namely AWS
At least 3 years experience designing or building a SaaS platform product
At least 3 years experience with at least 3 of the following PHP, MySQL, Node.js, React
At least 2 years experience as technical business analyst

* Be able to fly
- Rotate to travel to Australia
- Great power comes with great responsibilities!

### Contact
Phuong Bui: phuongnhi.bui@go1.com (01212451188)

**Comment by huydx** [comment]
wrong title format
