### ISSUE TITLE
GO1- QA QC/ Agile Tester

### ISSUE THREAD

**Issue by btphuongnhi79** [awesome-jobs/vietnam#952]
## Location
271 Nguyễn Trọng Tuyển Phú Nhuận
Saigon, Vietnam

We are currently seeking out a QA QC/ Agile Tester who experience in testing and maintaining product development lifecycle to help us change the learning/training experience around the world!

## Salary Expectation
above $1000/month

## Requirements
- Create test models for release testing (plans, data and scripts) including the identification, collection and/or creation of test data
- Determine and meet time estimates and schedules for testing efforts
- Develop, update and maintain quality testing standards and procedures
- Assist in the planning, creation and control of the test environment(s)
- Update and test release installation procedures

## Skills
- Review requirements, specifications and technical design documents to provide timely and meaningful feedback
- Create detailed, comprehensive and well-structured test plans and test cases
- Design, develop and execute automation scripts using open source tools
- Identify, record, document and track bugs
- Perform thorough regression testing when bugs are resolved
- Track quality assurance metrics, like defect densities and open defect counts
- Assist in the planning, creation and control of the test environment(s)
- Stay up-to-date with new testing tools and test strategies

* Be able to fly
- Rotate to travel to Australia
- Great power comes with great responsibilities!

### Contact
Phuong Bui: phuongnhi.bui@go1.com (01212451188)

**Comment by huydx** [comment]
wrong format
