### ISSUE TITLE
AnyMind Group - Senior DevOps Engineer

### ISSUE THREAD

**Issue by thucnhan** [awesome-jobs/vietnam#957]
![30738825_217698042322280_1915724837590925312_o copy](https://user-images.githubusercontent.com/38033330/39625281-ee9cb744-4fc6-11e8-9577-7a6d1bc487ba.jpg)

AnyMind Group (https://anymindgroup.com) provides businesses and professionals with AI-based solutions that enable businesses to achieve greater scale and efficiency.

**LOCATION**

- F16, Ruby Tower, 81-85 Ham Nghi, District 1, HCMC, Vietnam

**SALARY EXPECTATION**

- You will love it

**WHAT YOU SHOULD HAVE**

- 2+ years as SysAd, DevOps position in Web system configuration, operation, tuning
- Strong knowledge of AWS, Linux, Middleware software (Load-balancers, Web servers, Database)
- Familiar with Microservices, Serverless architecture with Docker
- Experience with CI/CD tools such as Jenkins and version-control Git (Gitflow)
- Experience with Infrastructure as Code platform such as Ansible/AWS Cloud Formation
- Be able to communicate in English (verbal and non-verbal)

**WHAT YOU WILL DO**
Dont just be a coder, be a team-player in an energetic team building life-changing products and rocking digital area:

1. DEV
- Building and operate CI (Continuous Integration) solutions to ensure smooth development to product cycle
- Implementing automation solutions to improve development productivity
- Troubleshoot errors and problems in Dev/Prod environment with product Team
- Designing and architecting Microservices Web system (Staging/Production) following up Amazon’s Architecting for the Cloud: Best Practices

 2. OPS
- Implementing Deployment pipeline from development to production environment in AWS Cloud
- Implement and operate Cloud Monitoring and Alert system to stably operate Production products
- Implementing and operate Logging system to proactively discover incidents
- Frequently verify System Performance to ensure best-performance Product to users/customers

 3. SECURITY
- Frequently running check on system to discover potential security risk and proactively provide solutions
- Proactively provide solutions to further ensure the security of sensitive data

4. DEVOPS CULTURE FOSTERING
- Actively share and train members about DevOps mindset to foster DevOps culture among the team.
- Actively research for new tools/solutions to perfecting the DevOps cycle

**HOW AWESOME IS IT TO WORK WITH US**
We don't offer you a job, we offer you an career opportunity :)

- Competitive Salary with two Performance Review per year
- Performance Bonus (1 time per year from 0.5-month to 3-month salary amount )
- MacBook to be provided, well-stocked pantry awaiting, cool team-players to have a blast with
- Join dynamic environment where growth-oriented mindset is encouraged
- Good chance to explore new trends in a digital market, where you can experience the most advanced advertising technology platforms
- No fixed day for promotion - Perform well and get promoted anytime!
- Quarterly, Annual MVP Awards (prizes up to 8,000USD)

**OUR INSPIRING PRODUCTS**
To provide businesses and professionals with AI-based solutions that enable businesses to achieve greater scale and efficiency.
Our 3 key products are: :

- ADP (https://adasiaholdings.com), provides a suite of AI-based Advertising solutions to enable marketers and publishers to achieve greater returns.

- TalentMind (https://talentmind.ai), provides human resource and recruitment professionals with an AI-driven recruitment platform to make hiring more efficient and targeted.

- CastingAsia (https://casting-asia.com) leverages on artificial intelligence to provide marketers with a smart and safe environment for their influencer marketing activities.

Love to hear more about our journey of initiating these inspiring products?
Contact us for our story, our vision, our mission
(S) tuna251095
(M) nhan@anymindgroup.com
Homepage: https://anymindgroup.com/
Life at ANYMIND: https://www.youtube.com/watch?v=Fi1YSGbhCnI

**Comment by huydx** [comment]
wrong title format
