### ISSUE TITLE
Employment Hero- Ruby on rails Developer - Saigon - FT

### ISSUE THREAD

**Issue by minhbachnguyen** [awesome-jobs/vietnam#958]
Job deleted due to violation of recruitment policy. /@qcam.

**Comment by nguyenquangminh0711** [comment]
Hi @minhbachnguyen,

I'm from the Employment Hero company. I have just got a confirm from our HR department that we prefer a direct job application and don't have any contract with independent head hunters. Therefore, this job post violates our recruitment policy. I demand you to take this post down and remove your personal contact in other job posts related to Employment Hero. We only accept the applications from official channels or via email gigi.phuong@employmenthero.com.

Hope that the admins would support us on this. cc @qcam @huydx 

Regards,
Minh Nguyen
Technical Lead @ Employment Hero

**Comment by qcam** [comment]
@nguyenquangminh0711 Thanks for reporting.
