### ISSUE TITLE
Azari - Full Stack Web Developer - Hanoi, Vietnam - FT

### ISSUE THREAD

**Issue by hnq90** [awesome-jobs/vietnam#96]
## Location
- Hanoi, Vietnam
## Who are we?
- Young and talented tech start-up aiming to transform the Vietnamese interior design and furniture market.
- Founding team with working experience working with start-up in Vietnam, US, Israel.
## Job details
- We're looking for a full stack web developer to lead the tech development of an community-focused online marketplace 
- Work with marketing and operations team to define the company’s overall strategy
## Requirements
- At least 2 years experience as a Web developer.
## Skills
- Excellent at PHP or Ruby/Ruby on Rails framework.
- Have experience with software testing, automation testing.
- Have experience working with version control system (Git).
- Familiar with agile development methodology.
- Have knowledge of UI/UX.
- Be able to communicate in English is a plus.
## We offer
- Opportunity to co-found a company and design, develop new e-commerce product.
- Young and creative working environment.
- Team of strong, experienced colleagues.
- Flexible working time.
- Competitive salary and company’s shares.
## Contact

Please send your proudest work and contact information to manhlinh.hoang at gmail.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
