### ISSUE TITLE
Zinza Technology - Ruby On Rails - HN - FT

### ISSUE THREAD

**Issue by thaontp39** [awesome-jobs/vietnam#970]
## Location

* HaNoi, Vietnam
* Fulltime

## Salary Expectation

*** 500-1000$**

## Requirements
* Experienced in Web programming
* Experienced in Ruby on Rails for at least 6 months
* Understand and operate MVC, ORM, RESTful concepts
* Have experience working with popular libraries such as Rspec, Devise, CanCanCan
* Experienced in template engine (haml, slim ...).
* Have experience working with Linux environment (CentOS, Ubuntu ...)
* Use Javascript, CSS (jQuery, Bootstrap ...) to work with the frontend "

### Responsibilities

Great power comes with great responsibilities!

### Why it would be awesome to work with us
Staffing for all employees in ZinZa Technology is as follows:
1. Japanese language allowance, and related IT certifications (form: monthly allowance, salary increase ...). Project allowance (other than salary)
2. Join the Club under the official sponsorship of the Company: Football Clubs, Game Clubs, Japanese Language and Learning Clubs, join birthday parties, team building quarterly, The lock of the company ...
3. Have the opportunity to be onsite in the Japanese market.
4. Working time: Monday to Friday from 8.30 - 17.30 (7th rest, CN). Working time, sometimes not roof.
5. Professional working environment, open, friendly
6. Salary increase according to capacity and results of work: 1-2 times / year.
7. Salary adjustment according to market price slippage: once a year.
Monthly salary 13
9. Opportunity for high promotion in a continuous growth environment
10. Annual Travel 

### Contact
Homepage: thaonguyenn993 (skype)
Email: tuyendung@zinza.com.vn

**Comment by huydx** [comment]
Please fix space in title (see another job)
