### ISSUE TITLE
HỒ CHÍ MINH_[Urgent] Ruby on Rails Dev - Up to $1500

### ISSUE THREAD

**Issue by nhung693** [awesome-jobs/vietnam#978]
## Location

*Tầng 10 toà nhà Dreamplex, 195 Điện Biên Phủ, Q Bình Thạnh, HCM

## Salary Expectation
- Mức lương hấp dẫn up to $1500

## Requirements
- Có ít nhất 2 năm kinh nghiệm lập trình với Ruby on Rails
- Sử dụng thành thạo Javascript, HTML và CSS

ƯU TIÊN:
- Có kinh nghiệm về Amazon Web Services (AWS)
- Có kinh nghiệm với Automated test và Test Driven Development
- Có kinh nghiệm làm việc với restful và các service như google, facebook...
- Hiểu và có thể vận dụng tốt metaprogramming và design pattern
- Có kinh nghiệm về git và gitflow
- Có thể sử dụng Photoshop hay AI là điểm cộng

KỸ NĂNG MỀM
- Làm việc nhóm tốt, hợp tác tốt với đồng nghiệp khác trong công việc
- Kỹ năng quản lí thời gian, quản lí task của bản thân tốt

## Skills
Ruby on Rails

### Why it would be awesome to work with us

- Làm việc 5 ngày/tuần . Nghỉ cả ngày thứ 7 & Chủ Nhật.
- Review lương 2 lần/ năm vào tháng 1 và tháng 6.
- Được cấp Macbook để thỏa sức sáng tạo
- Được tham gia các khóa đào tạo tiếng Nhật tổ chức định kì
- Được tham gia các hoạt động team building,..
- Ngay lập tức đóng đầy đủ các chế độ bảo hiểm theo luật lao động khi bạn kí hợp đồng là nhân viên chính thức của Atmarkcafe ( sau 2 tháng thử việc).
- Thưởng theo doanh thu cuối năm và các ngày lễ tết hấp dẫn.
- Tổ chức teambuiding và du lịch thường niên toàn công ty tại những địa điểm hấp dẫn ( 5 triệu/người /năm + có suất gia đình đi cùng)
- Môi trường làm việc thân thiện, năng động, đa dạng, nhiều cơ hội thăng tiến
- Liên tục tổ chức các khóa đào tạo nâng cao chuyên môn giúp nhân viên hoàn thiện kỹ năng và hoàn thành công việc tốt hơn.
- Cơ hội đi công tác nước ngoài (Nhật Bản)
- Các phúc lợi của Công ty: sinh nhật, , ăn trưa tại công ty, …được tổ chức định kì

### Contact
Homepage: http://atmarkcafe.org/
Mail: hr@atmarkcafe.org
SĐT: 024 3734 9794 (Ms Nhung)

**Comment by nhung693** [comment]
ad ơi, cho mình hỏi, sao issue của mình lại bị đóng vậy, qui định đăng như nào mới đúng ạ

**Comment by huydx** [comment]
bạn tự nhìn các JD khác xem họ làm thế nào, và đọc kĩ README https://github.com/awesome-jobs/vietnam .

**Comment by nhung693** [comment]
Thanks ad

**Comment by huydx** [comment]
Vẫn sai format, bạn đọc kĩ chưa vậy?
Bạn xem title thứ tự ra sao nhé.

**Comment by nhung693** [comment]
Mình chưa đăng lại mà ad, vẫn đang xem cái qui định đăng tuyển nãy ad gửi đó
