### ISSUE TITLE
[9CV9] Python Team Lead - Singapore Corporation

### ISSUE THREAD

**Issue by ndmthu1997** [awesome-jobs/vietnam#998]
## Location 

* Saigon, Vietnam
* Remote

## Salary Expectation

* $2500/month

## Requirements
* Able to work clean codes and to build an infrastructure from scratch
* Strong understanding of system networking

### Must Have

* Python
* Django
* Flask
### Ideally
* Frontend Javascript, ReactJS 
* AWS, Docker
* English

### You’ll be responsible for

* Building up an automated and smart loan making system. The project will be exciting and huge

### Interesting engineering projects
* The project will be exciting and huge
* Good Career Prospects
* Follow Vietnamese Labor law
### Contact
Email: minhthu@9cv9.com
Skype: ndmthu1997
#Link JD and Apply: https://bit.ly/2GNLWmQ
![33773331_1425755100904209_8764170312708259840_n](https://user-images.githubusercontent.com/39650798/40610361-42025190-629c-11e8-8041-4d53d4515f57.png)

**Comment by huydx** [comment]
wrong format

**Comment by ndmthu1997** [comment]
I apology for it. Could you please specify what wrong it is then I will follow? Thank you!!
